### ISSUE TITLE
 Right-click menu is gone when I use vim or fill in commit message

### ISSUE THREAD

**Issue by NewBie1993** [git-for-windows/git#1002]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [°æ±¾ 10.0.14393]
```
(Yes, as you can see, there are some characters garbled. My system language is Chinese.)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled

Yes, I use the default option in the installation.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No, when I back to 2.8.4, it's OK.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash.(Right-click in the explorer and choose Git Bash Here.)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Invoking vim or submit a revision to input commit message, vi will enter visual mode and right-click menu is gone.
```
 - What did you expect to occur after running these commands?

Vi in the insert mode and show then right-click menu,

 - What actually happened instead?

Vi entered the so-called visual mode.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, it's a common problem.

**Comment by dscho** [comment]
I cannot reproduce here (with Git for Windows v2.11.0):

![screenshot-issue-1002](https://cloud.githubusercontent.com/assets/127790/21354043/beb43ada-c6c8-11e6-8916-2fcf448ceb77.png)

**Comment by NewBie1993** [comment]
I have two different computers, one is my company's(windows7) and the other is my personal(windows10).  Both have this problem in  Git for Windows v2.11.0 and they all working properly when I back to old version. 

1、enter vi and right-click directly
![image](https://cloud.githubusercontent.com/assets/10355814/21358377/7c088498-c713-11e6-8dc3-504440cdc584.png)

2、input "i" enter insert mode and right-click
![image](https://cloud.githubusercontent.com/assets/10355814/21358493/d366402c-c713-11e6-9f35-62519f2b08db.png)

Do you need anything else I can offer?

**Comment by dscho** [comment]
Your original bug report mentioned Windows 10, with a funny-looking sequence of characters before the version number, suggesting that it is a localized version. Maybe that is the issue? If so, it should be addressed by the prerelease here: https://github.com/git-for-windows/git/releases/tag/prerelease-v2.11.0.windows.1.1 (and also by the "Happy Holidays" prerelease that is building as I write this).

Could you test that hypothesis, please?

**Comment by NewBie1993** [comment]
I'm sorry to reply to you for such a long time. I have test the prerelease you mentioned and it doesn't work.

I have tried to solve this problem myself and there is a way I found on the Internet. The following entry in the configuration file of vim(usr\share\vim\vim80\defaults.vim) lead to this problem.
```
if has('mouse')
  set mouse=a
endif
```
It worked as I expect when I change the config to `set mouse=`.
![image](https://cloud.githubusercontent.com/assets/10355814/22855095/03802d98-f0b5-11e6-9562-ce54f9bbf42b.png)

I downgrade my version of git from 2.11.1 to 2.10.1(It is the latest normal version I know). There is no the config entry in vim and even no the file named defaults.vim in the install directory(usr\share\vim\vim74).

So I think it is the resaon and can I think it is a problem? @dscho

**Comment by dscho** [comment]
When I ask `:verbose set mouse?` in command mode, my `vim` insists that it is set to the empty string. what does your `vim` report?

**Comment by NewBie1993** [comment]
My vim report
```
  mouse=a
        最近修改于 /usr/share/vim/vim80/defaults.vim
```
![image](https://cloud.githubusercontent.com/assets/10355814/23169635/7d781348-f887-11e6-9590-b0bda08cc05c.png)

**Comment by dscho** [comment]
@NewBie1993 I fear that the change of the default settings is actually intended by the vim project: https://github.com/vim/vim/commit/8c08b5b569e2a9e9f63dea514591ecfa2d3bb392

The workaround they suggest is to create a `$HOME/.vimrc` file. Even an empty file will disable the defaults.

Does that work for you?

**Comment by NewBie1993** [comment]
Yes, it does work.
![image](https://cloud.githubusercontent.com/assets/10355814/23215580/e7c9cef0-f94d-11e6-949e-2edd882240e4.png)

And when I ask` :verbose set mouse?` in command mode, it insists that it is set to the empty string.

**Comment by dscho** [comment]
Okay, let's close this ticket, then: your problem is resolved, and the intention of the vim project to change the defaults is also heeded.
