### ISSUE TITLE
Cloning files with different capitalization of name gets no warning.

### ISSUE THREAD

**Issue by KexyBiscuit** [git-for-windows/git#1008]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Difftool: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 None. It's a brand new Windows 10 Enterprise VM running on Hyper-V.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
PS C:\Users\GitTest\Downloads> git clone https://github.com/wuxianlin/android_kernel_zte_pluto
Cloning into 'android_kernel_zte_pluto'...
remote: Counting objects: 42428, done.
PS C:\Users\GitTest\Downloads> git clone https://github.com/wuxianlin/android_kernel_zte_pluto
Cloning into 'android_kernel_zte_pluto'...
remote: Counting objects: 42428, done.
remote: Total 42428 (delta 0), reused 0 (delta 0), pack-reused 42428
Receiving objects: 100% (42428/42428), 117.71 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (3505/3505), done.
Checking out files: 100% (40308/40308), done.
PS C:\Users\GitTest\Downloads> cd .\android_kernel_zte_pluto\
PS C:\Users\GitTest\Downloads\android_kernel_zte_pluto> git status
On branch cm-11.0
Your branch is up-to-date with 'origin/cm-11.0'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   include/linux/netfilter/xt_CONNMARK.h
        modified:   include/linux/netfilter/xt_DSCP.h
        modified:   include/linux/netfilter/xt_MARK.h
        modified:   include/linux/netfilter/xt_RATEEST.h
        modified:   include/linux/netfilter/xt_TCPMSS.h
        modified:   include/linux/netfilter_ipv4/ipt_ECN.h
        modified:   include/linux/netfilter_ipv4/ipt_TTL.h
        modified:   include/linux/netfilter_ipv6/ip6t_HL.h
        modified:   net/netfilter/xt_DSCP.c
        modified:   net/netfilter/xt_HL.c
        modified:   net/netfilter/xt_RATEEST.c
        modified:   net/netfilter/xt_TCPMSS.c

no changes added to commit (use "git add" and/or "git commit -a")
PS C:\Users\GitTest\Downloads\android_kernel_zte_pluto>
```
 - What did you expect to occur after running these commands?

 Everything committed, working directory clean. Which is the case on Linux.

 - What actually happened instead?

 I get some uncommitted changes.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 https://github.com/wuxianlin/android_kernel_zte_pluto

**Comment by KexyBiscuit** [comment]
It's just another capitalization problem...

Well, Git for Windows should warn user of this.

**Comment by KexyBiscuit** [comment]
This issue may also apply to Git on other OSes.

**Comment by PhilipOakley** [comment]
Hi Kexy,

It wasn't obvious what part was having the case sensitivity issue. I didn't see any command that specifically put you on a branch with the wrong case (which is the usual issue).

How did those files get the wrong case? was there a command I missed (e.g. checkout CCM-11.0 ).

It's true that case senitivity does need 'fixing', but from a Linux/Git perspective it's someone elses problem. 

It's likely that all the places where case senitive names are used, that a struct will need passing around the functions so that the true-path and the filename can be cross checked. At the moment the path and the name are handed around separately on the strong expectation that they can't be different (on Linux) (e.g. asking to checkout origin/CCM-11.0 would fail on linux, while on Windows it would happilly checkout ccm-11.0, leaving a disconnect, with the same happening for worktree filenames).

Philip
  ----- Original Message -----

**Comment by jeffhostetler** [comment]
I noticed that the net/netfilter/ directory contains both "xt_dscp.c" *and* "xt_DSCP.c" files.  This collision causes the problem.  Git checks out the uppercase one first (because the index is sorted) and then overwrites the file when it gets to the lowercase one.  Later when status runs, git compares both the uppercase and lowercase index-entries against the same worktree file and reports that the uppercase one is dirty.

**Comment by PhilipOakley** [comment]
I think that fixing that issue of duplicate (differnt cases) filenames during checkout is going to be just as tricky, perhaps even more so, than the branch name case issues!

Just saw a case on the main list regarding the split index: 
Re: [PATCH v2 16/21] read-cache: unlink old sharedindex files;
 Message-ID: <CAP8UFD2hE5nLXKpSEPaS_1XYqQw+Wn=nMT4paV+FtGFrHzHsFw@mail.gmail.com> 
which punted on the fspathcmp() - I understand that it's a tricky issue anyway for Windows compatibility issues with the old 8.3 and similar formats.

**Comment by KexyBiscuit** [comment]
So how would Git for Windows handle this? Give a warning to user? Or refuse to checkout?

**Comment by PhilipOakley** [comment]
> >  Cloning files with different capitalization of name gets no warning.

> So how would Git for Windows handle this? Give a warning to user? Or refuse to checkout?

My view is that Git (with a suitable option enabled) should warn users that the checked out file has a different capitalisation to that requested. At least then the user has a little bit of extra knowledge to allow them to make a choice about what to do.

I think that is the 'best' that can be done in those difficult circumstances. That is, I don't think there is a true 'right' answer for all cases. 

I'm sure it is possible to create a rather large table of conditions for the conflicts during checkout and additions of files to the repo.

--
Philip

**Comment by jeffhostetler** [comment]
Detecting and warning about collisions (or potential collisions) is a VERY hard problem.
[] How a commit created on one system would be interpreted on the another system. (A Linux user created "README" and "ReadMe" in the same directory and you want to checkout on Windows or Mac.)
[] How we access the worktree and how the OS lies to us. (Calling lstat("README") and lstat("readme") will both succeed, but FindFirstFile/FindNextFile or opendir/readdir on a Mac will only find one.)
[] Other file system quirks. (8.3 short name aliasing, Mac NFC/NFD, reserved names like "COM1", and etc.)
[] Do you warn at the time of the ADD/COMMIT (that the new file MAY cause problems later) or during the CHECKOUT and either fail or warn and park some files with conflict names?

When I worked on Veracity, I studied this problem in (way too much) detail.  I went for the proactive warning during ADD/COMMIT.  My potential collision detection code is here (https://github.com/jeffhostetler/veracity/settings).  The comments in the code pretty well summarizes the various types of problems that can arise.

I'm not saying we do something like this, but it helps to see the full problem.

**Comment by KexyBiscuit** [comment]
I prefer to warn at both commit and checkout, and try to prevent all common file system and operating system restrictions.

**Comment by KexyBiscuit** [comment]
There's a warning now. Thanks.

```shell
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'FILE'
  'file'
```
