### ISSUE TITLE
Git for Windows cannot cleanly checkout the Haiku repository

### ISSUE THREAD

**Issue by waddlesplash** [git-for-windows/git#1009]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Win10 x64.
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I know of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Command.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://github.com/haiku/haiku/
git status
git checkout .
git status
```
 - What did you expect to occur after running these commands?

A clean, no-working-tree-modifications clone of the Haiku repository.

 - What actually happened instead?

A large number of files - catkeys (translation strings, mostly) and a few others with lots of UTF-8 in them - are shown as modified (it looks like they are older versions, oddly?).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

See above.

**Comment by waddlesplash** [comment]
(This has been occuring for $long_time - I can't recall Git for Windows ever properly checking out the Haiku tree - and as far as I know, it happens to everyone.)

**Comment by jeffhostetler** [comment]
It would be helpful if you could include some of the output from status showing the dirty files.  Thanks!

**Comment by waddlesplash** [comment]
Sure:
```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   data/catalogs/apps/screenshot/Screenshot/be.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/cs.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/de.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/es.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/fi.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/fr.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/hr.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/hu.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/it.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/ja.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/lt.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/nl.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/pl.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/pt_BR.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/ro.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/ru.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/sk.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/sl.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/sv.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/uk.catkeys
        modified:   data/catalogs/apps/screenshot/Screenshot/zh_Hans.catkeys
        modified:   src/tests/kits/locale/CollatorTest.cpp

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by jeffhostetler** [comment]
It looks like there is a "data/catalogs/apps/screenshot/Screenshot/" folder colliding with a "data/catalogs/apps/screenshot/screenshot/" folder.  Both folders have the same set of file names.
This collision explains the dirty status as I described in https://github.com/git-for-windows/git/issues/1008).
Fixing git to properly handle such things will be a very difficult problem to solve -- especially since such repos are not problematic on Linux.

The best suggestion I can offer for now is for you to "fix" your repo to not have such collisions.

**Comment by waddlesplash** [comment]
Ah, whoops, I missed that.

**Comment by jeffhostetler** [comment]
Thanks for the confirmation.  Marking this closed.
