### ISSUE TITLE
error launching git: The system cannot find the path specified.

### ISSUE THREAD

**Issue by Fr1z2r** [git-for-windows/git#101]
When I run git from far or conemu I get an error:
error launching git: The system cannot find the path specified.
 
git version 2.3.5.windows.8

**Comment by Stanzilla** [comment]
The path is different, compare where the old git.exe was and where the new git.exe is and alter your paths.

**Comment by Fr1z2r** [comment]
PATH points to right directory. 
where git : C:\Program Files\Git\cmd\git.exe

If I run from far **git.exe** or run **git** from cmd - all ok.

**Comment by dscho** [comment]
http://stackoverflow.com/help/mcve please.

**Comment by Fr1z2r** [comment]
1. Download git from https://github.com/git-for-windows/git/releases/download/v2.3.5.windows.8/Git-2.3.5.8-dev-preview-64-bit.exe
2. Remove old git (1.9.5)
3. Install new
4. Check that PATH points to correct directory (C:\Program Files\Git\cmd)
5. Type **git** in Far, result: **error launching git: The system cannot find the path specified.**
6. Type **git** in Cmd, result: normal git output
7. Type **git.exe** in Far, result: normal git output

**Comment by dscho** [comment]
> [...] in Far [...]

??? Is this report really supposed to be helping me to help you?

**Comment by Fr1z2r** [comment]
What kind of information do you need?
Far - File manager
http://www.farmanager.com/

**Comment by dscho** [comment]
@Fr1z2r okay, this is not working for me... with the information available, even the latest tidbit, it is impossible for me to reproduce in a reasonable time frame and with reasonable effort from my side.

Hopefully you will find out what the culprit is. Good luck!

**Comment by Fr1z2r** [comment]
It's fixed for me in Git-2.3.6.2, thanks.

**Comment by dscho** [comment]
Good!
