### ISSUE TITLE
gitgui : Redundant recent repository bug

### ISSUE THREAD

**Issue by lijiayi0921** [git-for-windows/git#1011]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

git-gui version 0.20.GITGUI
git version 2.9.2.windows.1
sizeof-long : 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 x64

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

For some reason (I cannot remember), I have two entries of a same local repo in the recent repo list of my gitgui.
This caused problems when I want to move the repo or change it.
 - There's no option to remove a recent repo from git-gui
 - If I manually remove it from my disk, a tcl error window shows 

![image](https://cloud.githubusercontent.com/assets/10466395/21503061/bde9322c-cc54-11e6-8bf9-da1a32a0bfb9.png)

I solved the problem by removing the redundant entry in my $HOME/.gitconfig.

I think something could be done at gitgui's start-up to manage redundant recent repo entries.

Thank you

**Comment by dscho** [comment]
This does not look like a Windows-specific issue. Please report it to [the Git mailing list](mailto:git@vger.kernel.org) or even better: propose a patch as a Pull Request to https://github.com/patthoyts/git-gui
