### ISSUE TITLE
critical: 2.10.2.windows.1: git-gui crashes when opening a 3rd window

### ISSUE THREAD

**Issue by zosrothko** [git-for-windows/git#1014]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
Z:\git\javaccPlugin> git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Z:\git\javaccPlugin>cmd.exe /c ver

Microsoft Windows [version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
Z:\git\javaccPlugin>type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 _TODO_

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
"C:\Program Files\Git\cmd\git-gui.exe", then Open Existing Repository, then Selecting a disk
 - What did you expect to occur after running these commands?

A new Git Gui window

 - What actually happened instead?
Git Gui is crashing

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
The panl Open Recent Repository contains a list of 10 repository

**Comment by dscho** [comment]
> Git Gui is crashing

Could you be more specific how it crashes (e.g. how can you tell that Git GUI is not simply refusing to do stuff because it does not find any associated repository)?

**Comment by zosrothko** [comment]
Update... the Wish application crashes when opening a new repository not in the list of open recent repositories and the list  contains 10 repo.

**Comment by zosrothko** [comment]
This issue is critical since there is no way to flush the list....

**Comment by PhilipOakley** [comment]
look at my old series http://public-inbox.org/git/1450310287-4936-1-git-send-email-philipoakley@iee.org/

I can't remember if this was merged.

**Comment by PhilipOakley** [comment]
@zosrothko, It looks like the series never got near the Git 'pu' branch. The series should also go to Pat Thoyts who maintains the git-gui https://github.com/git-for-windows/git/blob/master/Documentation/SubmittingPatches#L325-L327 

If you can review Junio's comments from the V2 series that would be a help. i.e. provide some feedback - this is open source, so your help is needed.

Philip

**Comment by PhilipOakley** [comment]
Also, can you share the git-gui entries in your .gitconfig (just show the first ~5 chars of the path..). 

Try `git config --global --show-origin -l` in a bash terminal window to see all the settings (and where it is, $HOME)

My gui section (from the above, without the --show-origin) looks like:
```
gui.recentrepo=C:/Use.......
gui.recentrepo=H:/IFS.....
gui.recentrepo=N:/EO....
gui.recentrepo=//De....
gui.recentrepo=H:/Git...
```

Do you have share (//) paths? Are the all absolute drive paths?

**Comment by dscho** [comment]
@zosrothko I agree with @PhilipOakley: your assistance is required to push the resolution forward.

**Comment by zosrothko** [comment]
Here the result:
Z:\git\javacc>git config --global --show-origin -l
file:C:/Users/FrancisANDRE/.gitconfig   user.name=FrancisANDRE
file:C:/Users/FrancisANDRE/.gitconfig   user.email=zosrothko@orange.fr
file:C:/Users/FrancisANDRE/.gitconfig   gui.trustmtime=true
file:C:/Users/FrancisANDRE/.gitconfig   gui.warndetachedcommit=true
file:C:/Users/FrancisANDRE/.gitconfig   gui.tabsize=4
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/asn1cpp
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/poco
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/poco-c++11
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/gradle-mc
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/poco-gradle
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/gradle
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/gradle-cppunit
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/SPLC-JTB-JavaCC
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=Z:/git/SPLC
file:C:/Users/FrancisANDRE/.gitconfig   gui.recentrepo=C:/MXW/MI/MI-4.1.0
file:C:/Users/FrancisANDRE/.gitconfig   filter.lfs.clean=git-lfs clean %f
file:C:/Users/FrancisANDRE/.gitconfig   filter.lfs.smudge=git-lfs smudge %f
file:C:/Users/FrancisANDRE/.gitconfig   filter.lfs.required=true
file:C:/Users/FrancisANDRE/.gitconfig   core.autocrlf=input
file:C:/Users/FrancisANDRE/.gitconfig   core.filemode=true
file:C:/Users/FrancisANDRE/.gitconfig   credential.helper=manager

**Comment by dscho** [comment]
> Here the result:

@zosrothko by "your assistance is required" I was more referring to offering a review of @PhilipOakley's patches, as well as actually testing whether they fix your issue.

**Comment by PhilipOakley** [comment]
@zosrothko Thanks for that output. It at least confirms that it isn't at all related to the `\\server\path` issue, and that you have exactly 10 entries at the moment, which appears to be blocking you.

If you are able to pick up and apply those patches direct (*) to the Tcl/Tk shell script, and then check that they work for you that would be a great assistance as @dscho mentioned.

(*) If you have the full git reo and SDK then all the better. Though as the gui is a simple shel script you could bypass all that by using a local tool to apply those diffs directly!

**Comment by PhilipOakley** [comment]
@zosrothko As a workaround, you can go to the text file file: `C:/Users/FrancisANDRE/.gitconfig` and edit that one to remove one of the gui recentrepo lines to at least get you working & helping again. :wink:

**Comment by PhilipOakley** [comment]
The branch with my 4 patches is https://github.com/PhilipOakley/git/tree/dup-gui

They are not the best (in retrospect) as they work through the fault/fix sequence of incremental improvement, rather than identifying and resolving all the issues as a clean sequence.

Aside - @zosrothko - are all those repositories still in existance at those specific paths from your machine at the point that the gui is started?

**Comment by zosrothko** [comment]
I applied the 4 patches of @PhilipOakley and the issue is solved at least at first glance... Thanks for your help on this issue, but I think your oathes should be applied to the main stream to avoid the same situation when moving to the 2.11 version.

**Comment by PhilipOakley** [comment]
> zosrothko 
> your oathes should be applied to the main 

s/oathes/patches/ I presume, :wink: 
I guess that was a spell checker thinking too hard.

I do hope to update the commit messages and re-submit some updated patches in the next few days, time permitting.

Were you able to confirm any of the other questions (should they come up in the upstream code review)?

Philip

**Comment by zosrothko** [comment]
@PhilipOakley 
Are all those repositories still in existance at those specific paths from your machine at the point that the gui is started? Yes all repositories are still existing at the point the gui is started.

**Comment by PhilipOakley** [comment]
@zosrothko - another clarification - did you try the "debugger"/'debogeur' button (as per your screen shot https://github.com/git-for-windows/git/issues/1014#issuecomment-269920630 above)  to get any more information?

I'm trying to work out all the different corner cases, and make sure that they weren't reported as 'solved' previously (which would mean I need to explain what went wrong). e.g. https://github.com/git/git/commit/3c6a2870274ea629499dfb6a9 https://github.com/git/git/commit/24f7c64. (Tcl/Tk isn't that easy to get my head around..)

**Comment by zosrothko** [comment]
@PhilipOakley After your patches be applied, the Wish application does not crash anymore, thus the corresponding issue can be closed. Thanks

**Comment by dscho** [comment]
@zosrothko thank you for testing! You probably think this a little thing, but it does help incredibly.

@PhilipOakley let's get these patches into Git GUI: https://github.com/git-for-windows/git/compare/master...PhilipOakley:dup-gui

AFAIU, the proper way is to rebase the patches to https://github.com/patthoyts/git-gui and open a PR there.

I rebased your patches using

```sh
git -C /path/to/git format-patch -4 --stdout PhilipOakley/dup-gui | git am -3 -p2
```

in my clone of `git-gui.git` and pushed the resulting `dup-gui` to my fork on GitHub; https://github.com/patthoyts/git-gui/compare/master...dscho:dup-gui (for comparison).

Please note that it looks as if @patthoyts is super busy with too many things, so it may be a while before he gets to the PR. In that case, I would like to merge your patches into Git for Windows early (and I would update them in case any changes are required by upstream Git/Git GUI).

**Comment by PhilipOakley** [comment]
@dscho I'm cautious that there are other issues buried in that code that I haven't bottomed out, for instance the procedure `_unset_recentrepo` is called (inside an else) before it is declared https://github.com/git/git/blob/master/git-gui/lib/choose_repository.tcl#L242. (could be solved by a simple swap of proc declaration order - see http://public-inbox.org/git/F9099DB3F0374D898776BD2621BF36FA@PhilipOakley/T/#u for my ignorance on the declare before use issue ;-)

Then there are the cases where the recent repo list is updated in the config, but the internal list isn't updated (various for loops).

**Comment by dscho** [comment]
> the procedure _unset_recentrepo is called (inside an else) before it is declared

I sent an explanation as a reply to your mail: the call is inside another proc, so all is well.

**Comment by PhilipOakley** [comment]
@dscho Thanks for the explanation - that Tcl stuff can be tricky ;-)

The format-patch innvocation is useful!

There is still one, maybe two points still to resolve. 

First was trying to get a plausible reason that folks either get duplicate config entries, or the max limit gets busted, but that could be put aside as just a worry, not an issue. 

The second is that if the `maxrecent` repos is reduced (its a user config), then the height of the `recentlist` (#L156) won't accomodate the `sorted_recent` list (#L136) - this matches Junio's query from 2015 about simply adding 5 as a workaround.

I think that I can simply check the size of the sorted_recent list agains the maxrecent and adjust the display size to suit (between #L137-138).

As an aside there are two identical places (#L28, #L272 that does 
```
if {[set maxrecent [get_config gui.maxrecentrepo]] eq {}} {
       set maxrecent 10
```

Which suggests that it could be a `proc _getmaxrecentrepo {}` returning the config value, default, or a max value! - though that probably should be a follow up patch.

**Comment by dscho** [comment]
@PhilipOakley sounds like you are almost ready to open that PR :smile:

**Comment by PhilipOakley** [comment]
> @PhilipOakley sounds like you are almost ready to open that PR

I'm failing on testing the git gui in its stand-alone repo "C:\git-sdk-32\usr\src\git-gui" when run from the regular SDK git bash (NOT integrated with cmd ;-).

I've run 'make', and had it start directly into the commit viewer, but haven't sorted out how to make it give the options screen. I've also tried from C:\git-sdk-32\usr\src and tried ./git-gui/git-gui.sh

Looks like I'll also have to apply the patches to the regular git/git-gui/ to somehow get the GfW correct startup.

My patches (against Pat's git-gui repo) are at: https://github.com/PhilipOakley/git-gui/tree/dup-gui

I especially want to test the last patch update.

Philip

**Comment by PhilipOakley** [comment]
At the moment I've totally failed to test the updates. I've tried various different `make` methods and none appear to affect the changed code (I even cleaned the git-gui and re-made it!)

I think it is that the mods are to parts that are pre-compiled into a lib ("C:\git-sdk-32\mingw32\share\git-gui\lib\choose_repository.tcl") and I'm not sure where to look for the code that compiles that.

**Comment by dscho** [comment]
@PhilipOakley this works here: `GIT_GUI_LIB_DIR=$PWD/lib ./git-gui`

**Comment by PhilipOakley** [comment]
> @PhilipOakley this works here: GIT_GUI_LIB_DIR=$PWD/lib ./git-gui


Thanks that has helped. It didn't quite work directly, but the 
GIT_GUI_LIB_DIR clue was the key.

To do my tests it can't be run in a repo directory, as it would simply start 
in that repo. It needed to be started from else where. The other bit is I 
needed to call the .sh version.

```
    Philip@PhilipOakley MINGW32 /usr/src

    $ GIT_GUI_LIB_DIR=$PWD/git/gitgui/lib ./git/git-gui/git-gui.sh

```

I have caught a final bug in the routine that limits the list to the 
`gui.maxrecentrepo` value - I needed to add a `catch` into the `--unset-all` 
so that the second time around it didn't fail quietly.

I need to update my branch, push it, double check I have it right, then 
raise the golden PR!

--

Philip

**Comment by PhilipOakley** [comment]
Finally, updated and pushed the 4 patch series.

Now https://github.com/patthoyts/git-gui/pull/10

There are three non issues still available for others to try their hand at:
1. de-duplicating the tcl code for maxrecent value determination
2. adding a maximum allowable value, say 25, for the maxrecent list and its config entry
3. de-duplicate the whole recent repo list. Currently it only de-dups the new entry, and any entry beyond the maxrecent length. Those dup entries between the two limits are not seen and not removed. Not a user facing issue.

**Comment by PhilipOakley** [comment]
A fourth tidy up task is:
4. Provide Yes/No/All/None option for the current auto removal of deleted repos when creating the recent repo list. Users on Windows Corporate networks can be off-line or have outages (network shares H:, etc) that mimic local repo deletion, but the user would not want removed from the recent repo list just because they can't be found at the moment.
