### ISSUE TITLE
Error: could not fork child process: Resource temporarily unavailable (-1)

### ISSUE THREAD

**Issue by abuhenasobuj** [git-for-windows/git#1015]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 _TODO_

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
 _Git Bash_

 - What actually happened instead?
 _When I Open Git Bash terminal I just got message_
```
Error: could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required. See 'rebaseall / rebase --help'.
```

- Did you try something for resolving this issue?
_I reinstalled Git for Windows, But the problem still appear._

![screenshot_2017 01 02_16h34m44s_001](https://cloud.githubusercontent.com/assets/16954436/21587934/b971c478-d10b-11e6-818b-7f2fe8415581.png)

**Comment by abuhenasobuj** [comment]
## The problem is solved.
After reinstall I restart my computer.
Then open Git Bash terminal & I see it works, 
But I got screen like attached image.
![screenshot_2017 01 02_18h59m15s_001](https://cloud.githubusercontent.com/assets/16954436/21589780/9a650676-d11f-11e6-9874-63842aedbea4.png)
After that I run "`C:\Program Files\Git\git-bash.exe`" as Administrator mode.
And closed git bash terminal & reopen, & I see it's working.

Anyone tell me why I saw the screen on first open (after reinstall & restart) git bash screen?

**Comment by dscho** [comment]
> Anyone tell me why I saw the screen on first open (after reinstall & restart) git bash screen?

Something went wrong in your installation in that case, as those commands should have been run as part of the installer.

> The problem is solved.

Please close tickets in the future when the problem was addressed.

**Comment by wusandi** [comment]
I encountered the same problem. As you said , I reinstalled the installer and restarted my computer, but it still didn't work. 

Environment:
OS: Win7 64
Installer: Git-2.11.0.3-64-bit.exe

Why does this problem happen under the hood?

**Comment by abuhenasobuj** [comment]
Hello @wusandi,
You can try again,
-  Uninstall the current Git Bash with any of Uninstaller [Revo Uninstaller](http://www.revouninstaller.com/revo_uninstaller_free_download.html) or [IObit Uninstaller](http://www.iobit.com/en/advanceduninstaller.php)
- Download the latest Git Bash Installer form [here](https://github.com/git-for-windows/git/releases)
- Run the Installer file as **Administrator** mode.

If the problem isn't solve then, create an another topic with full details.
