### ISSUE TITLE
Unicode characters not handled correctly in PowerShell Windows 10

### ISSUE THREAD

**Issue by terje** [git-for-windows/git#1017]
Hi,

I am having an issue with displaying Norwegian characters (æ, ø, å) in the output from `git log` in PowerShell on Windows 10. I have reproduced this problem on a clean Windows 10 install:

[![win10-git.png](https://s29.postimg.org/few4qfgtj/win10_git.png)](https://postimg.org/image/jo0uslk2r/)

The repo in the screenshot is cloned from https://github.com/nrkno/samnorsk

As you can see, the log is displayed correctly in Git Bash, but this is only after I have set the Character Set in Git Bash to UTF-8. Before I did this, Git Bash displayed the log with the same errors as PowerShell.

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

As you can see from the screenshot I am trying both in PowerShell and Git Bash. PowerShell has the problem, Git Bash does not.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://github.com/nrkno/samnorsk.git
cd samnorsk
git log
```

 - What did you expect to occur after running these commands?

The log to display norwegian characters in committer names or commit messages.

 - What actually happened instead?

Norwegian characters in committer names and commit messages are garbled.

**Comment by PhilipOakley** [comment]
Hi @terje 

This is a known issue with a number of different bug reports (depending on the users written language..)
e.g. #981 

The latest fix is  `v2.11.1.windows-prerelease.1`. the #981 includes a link to a slightly earlier version.

Philip

**Comment by terje** [comment]
Ok, thanks for the quick response @PhilipOakley! I saw #981 but didn't immediately relate to it because it concerned the output from diff instead of log but I will try the prerelease version.

**Comment by terje** [comment]
The prerelease version solves my issue. Thanks again.
