### ISSUE TITLE
bash replace/auto-complete arguments

### ISSUE THREAD

**Issue by cpainchaud** [git-for-windows/git#1018]
I tried several version of git-for-windows, my main problem is about bash itself which seems to replace/auto complete arguments with are format ie:      myProgram  arg=/path/value/here

bash will replace it with  myProgram  arg=/%PATH TO GIT FOLDER%/path/value/here

is it expected ? can it be turned off ?

**Comment by dscho** [comment]
@cpainchaud sorry, I fail to parse your report. Like, at all. What exactly is the problem?

**Comment by cpainchaud** [comment]
I am using your shell to update a script source code and then launch it.

unfortunately, the 'bash' program you include seems to mess with arguments we put on CLI if these arguments are looking like  :    myProgram arg1=/something/here arg2=/another/thing

and replaces them with:  myProgram arg1=/%PATH TO GIT INSTALL FOLDER%/something/here arg2=/%PATH TO GIT INSTALL FOLDER%/another/thing

example:

> processRules input=./opt/panc/rules.txt out=/tmp/test.txt
error: cannot find rule file 'arg1=c:/dev/git/opt/panc/rules.txt'

**Comment by dscho** [comment]
@cpainchaud that is a much better explanation.

This issue is mentioned in the [known issues section](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues) of our release notes:

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
>
> > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
>
>  Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion.

To allow for passing paths via `my-program.exe path=/git-bash.exe`, the conversion also takes place after an equal sign, so you will have to use similar workarounds in your use case.
