### ISSUE TITLE
bash: /mingw64/bin/git: Bad address

### ISSUE THREAD

**Issue by tobit800** [git-for-windows/git#1021]
# Hello together!
I hope someone can give me a hint for my problem.
When I start _git_ I get:

```
$ git
bash: /mingw64/bin/git: Bad address
```

First I had installed the normal _git-for-windows_ from [https://git-for-windows.github.io/](https://git-for-windows.github.io/). There I got the problem after rebooting my pc, but could fix it with re-install git. But since yesterday even the re-install does not fix the problem.

So today I had installed the portable version from [https://github.com/git-for-windows/git/releases/tag/v2.11.0.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.11.0.windows.1). I have downloaded **PortableGit-2.11.0-64-bit.7z.exe** and have checked the sha256 a86cc4babfe204cc91408053b517827b4a93e6c659b85ab30910eda0e38bfc19

The error occurs only in git-bash.exe and not when I start git-cmd.exe.

I would guess that there is something wrong with my $PATH ?!?
Here is the output I get in the cmd-box:
```
D:\Apps\Portable\PortableApps\Git>git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64

D:\Apps\Portable\PortableApps\Git>set path
Path=D:\Apps\Portable\PortableApps\Git\cmd;c:\Windows;c:\Windows\system32;c:\Win
dows\System32\Wbem;c:\Windows\System32\WindowsPowerShell\v1.0\;C:\Programme\Orac
le\11.2.0\client_64\bin;D:\Apps\Entwicklung\web\node\;d:\Apps\Entwicklung\Java\j
dk8\bin;D:\Apps\Entwicklung\SQLDeveloper\sqldeveloper\bin;\\DO-IT1\app\produktio
n\public
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

```

And here is the output I get in git-bash-Box:

```
$ git --version --build-options
bash: /mingw64/bin/git: Bad address

`$ echo $PATH
/c/Users/xxx/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/xxx/bin:/c/Windows:/c/Windows/system32:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Programme/Oracle/11.2.0/client_64/bin:/d/Apps/Entwicklung/web/node:/d/Apps/Entwicklung/Java/jdk8/bin:/d/Apps/Entwicklung/SQLDeveloper/sqldeveloper/bin://DO-IT1/app/produktion/public:/usr/bin/vendor_perl:/usr/bin/core_perl`
```

## Details

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 I have Microsoft Windows [Version 6.1.7601]```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

There are a some company-specific start-up-skripts running on each windows start, which install programms und install updates. I don´t know what they do, sorry.

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
I would like to run git-bash from msysgit.

## Help wanted

- I would like to get a hint, what else I could try. 
- Where should I search? 
- What does cause this error "bad address"?

**Comment by yudindm** [comment]
Hello.

I have the same issue with 32-bit version on Windows 7.
Microsoft Windows [Version 6.1.7601]

When I run git from git-bash shell I get error
bash: /mingw32/bin/git: Bad address

On my other machine with Windows 10 installed git-bash works without error.

Any advise would be appreciated.

**Comment by shiftkey** [comment]
Some interesting clues:

> The Bad address message comes from the kernel and indicates that a the process attempted to open a terminal (pty/tty) which does not exist.
> - [Source](http://serverfault.com/a/661474)

Lots of other threads [like this](http://stackoverflow.com/questions/23282032/cygwin-bad-address) and [this](http://stackoverflow.com/questions/10308053/cygwin-reports-bash-usr-bin-svn-bad-address) which suggest a Cygwin issue, but that's only loosely related to this scenario.

@yudindm @tobit800 could you run these two commands from Git Bash and attach the output? 

```
> which git
> ldd $(which git)
```

**Comment by yudindm** [comment]
@shiftkey, thanks for response.

Here is the output:
`
yudin@w576 MINGW32 /
$ which git
/mingw32/bin/git

yudin@w576 MINGW32 /
$ ldd $(which git)
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x77bf0000)
        kernel32.dll => /c/WINDOWS/system32/kernel32.dll (0x76b50000)
        KERNELBASE.dll => /c/WINDOWS/system32/KERNELBASE.dll (0x75b80000)
        ADVAPI32.dll => /c/WINDOWS/system32/ADVAPI32.dll (0x76e70000)
        msvcrt.dll => /c/WINDOWS/system32/msvcrt.dll (0x76aa0000)
        sechost.dll => /c/WINDOWS/SYSTEM32/sechost.dll (0x76550000)
        RPCRT4.dll => /c/WINDOWS/system32/RPCRT4.dll (0x77d90000)
        USER32.dll => /c/WINDOWS/system32/USER32.dll (0x76570000)
        GDI32.dll => /c/WINDOWS/system32/GDI32.dll (0x75ee0000)
        LPK.dll => /c/WINDOWS/system32/LPK.dll (0x76540000)
        USP10.dll => /c/WINDOWS/system32/USP10.dll (0x764a0000)
        WS2_32.dll => /c/WINDOWS/system32/WS2_32.dll (0x77d40000)
        NSI.dll => /c/WINDOWS/system32/NSI.dll (0x77d80000)
        LIBEAY32.dll => /mingw32/bin/LIBEAY32.dll (0x63280000)
        libgcc_s_dw2-1.dll => /mingw32/bin/libgcc_s_dw2-1.dll (0x6eb40000)
        libwinpthread-1.dll => /mingw32/bin/libwinpthread-1.dll (0x64b40000)
        libiconv-2.dll => /mingw32/bin/libiconv-2.dll (0x66200000)
        libintl-8.dll => /mingw32/bin/libintl-8.dll (0x61ec0000)
        libpcre-1.dll => /mingw32/bin/libpcre-1.dll (0x69340000)
        zlib1.dll => /mingw32/bin/zlib1.dll (0x63080000)
        libssp-0.dll => /mingw32/bin/libssp-0.dll (0x68cc0000)
`

**Comment by dscho** [comment]
>  I was not able to find an open or closed issue matching what I'm seeing

Well, I was.

- https://github.com/git-for-windows/git/issues/303
- https://github.com/git-for-windows/git/issues/46

Issue #303 has quite a bit of information that may be helpful.

> $ git bash:
> /mingw64/bin/git: Bad address
> [...]
> yudin@w576 MINGW32 /
> $ which git
> /mingw32/bin/git

What is it? 64-bit or 32-bit? The former is output of a 64-bit installation, the latter is output of a 32-bit one. Maybe you wanted to answer @shiftkey's question using the same installation that displays the reported problem?

**Comment by tobit800** [comment]
**Thank you so much for your help!**

You gave me enough information, that I have located the problem in 32 bit /64 bit installation.
So I just installed 32-bit Version from https://github.com/git-for-windows/git/releases

Now it runs. :-)
Thank you all.

Regards,
Tobias

**Comment by dscho** [comment]
> I have located the problem in 32 bit /64 bit installation.

For our information: what was the problem?

**Comment by tobit800** [comment]
Hi @dscho 
The information was, that the problem could be related to my 64bit-installation and that there exists a 32bit-version, which I did not know before. I have added the link, where I downloaded the 32bit version, but still I do not know the cause of my problem: _"What does cause this error "bad address"?_

**Comment by dscho** [comment]
> still I do not know the cause of my problem: "What does cause this error "bad address"?

The most common cause is an incompatible `.dll` in the system directory, e.g. `libeay32.dll`. The root cause is that Git has *two* directories where it stores executables: `/mingw64/bin` and `/mingw64/libexec/git-core/` (both relative to the top-level directory of the Git installation, of course), and the `.dll` files live in the former, while many executables linking to those `.dll` files live in the latter. As a workaround, we hard-link all `.dll` files from the former into the latter, otherwise `.dll` files with matching names are picked up if they exist in Windows' system32 directory.

However, this is not the case for `git.exe`: it already lives in `/mingw64/bin`, and even if no `.dll` files are hard-linked, the correct ones should be picked up by grace of living in the same directory as the executable.

If you want to diagnose this further, a good initial step would be to try calling `git.exe` again after setting the environment variable `GIT_TRACE=1`. That would tell us whether `git.exe` manages to at least start.

**Comment by yudindm** [comment]
Hi @dscho 

You asked
>>$ git bash:
/mingw64/bin/git: Bad address
[...]
yudin@w576 MINGW32 /
$ which git
/mingw32/bin/git
>
>What is it? 64-bit or 32-bit? The former is output of a 64-bit installation, the latter is output of a 32-bit one. Maybe you wanted to answer @shiftkey's question using the same installation that displays the reported problem?

Well, I wanted to say that the problem is not specific to 64-bit version but it exists in 32-bit version too.

I'v read #303 and checked if I have any [Cygwin's Big List Of Dodgy Applications](https://cygwin.com/faq/faq.html#faq.using.bloda). I didn't see any in Task Manager but unfortunately I can't be sure because I don't have administrative privileges and I don't see system processes. By the way I have running a antivirus software - Kaspersky Endpoint Security. It is not mentioned in the list but I guess it can interfere with Cygwin as other antiviruses do.

Then I did rabaseall but without any success.

Next I tried to do some random things...

I tried to run bash.exe from C:\PortableGit\bin folder (C:\PortableGit - is folder where I unpacked git 7z archive) and I was able to run git from there:

```
yudin-da@wsrs167576 MINGW32 /bin
$ git --version
git version 2.11.0.windows.1

```
But this is not a solution as the console in that case is windows cmd.exe and many things don't work from there :(

Are there anything else I could try to work around the problem?

Thanks.

**Comment by ms-chr** [comment]
Hello @dscho, 

I have the same issue with the installations of:
- Git-2.11.0-64-bit.exe
- Git-2.11.0.3-64-bit.exe

I don't have problems with:
- Git-2.10.2-64-bit.exe

C:\Program Files\Git\git-bash.exe:
`
$ git
bash: /mingw64/bin/git: Bad address

user@pc MINGW64 /
$ which git
/mingw64/bin/git
`

If I take "C:\Program Files\Git\bin\bash.exe" all things works fine.

**Details**

    Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
    Microsoft Windows 7 SP1

    Any other interesting things about your environment that might be related
    to the issue you're seeing?

    Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
    I would like to run git-bash.

**Help wanted**

    I would like to get a hint, what else I could try.
    Where should I search?
    What does cause this error "bad address"?

**Comment by dscho** [comment]
> What does cause this error "bad address"?

All kinds of things, unfortunately. For example, one instance of "bad address" I fixed some time ago was by increasing a too-small buffer in the MSYS2 runtime.

> I would like to get a hint, what else I could try.

Maybe running the command while [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/bb896645) is running? This *may* shed light into the underlying problem.

**Comment by dscho** [comment]
This may actually have the same root cause as #1033 (which I just fixed). Could you please give https://github.com/git-for-windows/git/releases/tag/v2.11.1.windows-prerelease.2 a try?

**Comment by yudindm** [comment]
It works for me.
Thanks.

**Comment by ms-chr** [comment]
Now it works!
But on start I see this:

`
mkdir: cannot create directory '/dev/shm': Read-only file system

Creating /dev/shm directory failed.
POSIX semaphores and POSIX shared memory will not work

mkdir: cannot create directory '/dev/mqueue': Read-only file system

Creating /dev/mqueue directory failed.
POSIX message queues will not work

ln: failed to create symbolic link '/dev/stdin': Read-only file system
ln: failed to create symbolic link '/dev/stdout': Read-only file system
ln: failed to create symbolic link '/dev/stderr': Read-only file system
ln: failed to create symbolic link '/dev/fd': Read-only file system
ln: failed to create symbolic link '/etc/mtab': Permission denied
'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
/usr/bin/cp: cannot create regular file '/etc/hosts': Permission denied
'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
/usr/bin/cp: cannot create regular file '/etc/protocols': Permission denied
'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
/usr/bin/cp: cannot create regular file '/etc/services': Permission denied
'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
/usr/bin/cp: cannot create regular file '/etc/networks': Permission denied
rm: cannot remove '/etc/post-install/01-devices.post': Permission denied
rm: cannot remove '/etc/post-install/03-mtab.post': Permission denied
rm: cannot remove '/etc/post-install/06-windows-files.post': Permission denied
rm: cannot remove '/etc/post-install/99-post-install-cleanup.post': Permission d                                   enied

user@PC MINGW64 ~
$ git --version
git version 2.11.1.windows.prerelease.2
`

**Comment by dscho** [comment]
> mkdir: cannot create directory '/dev/shm': Read-only file system

How did you install the prerelease (installer? portable Git?), how did you start it (CMD? Git Bash? `bin/sh.exe`?)?

**Comment by ms-chr** [comment]
I had install the Git-prerelease-2.11.1.windows.prerelease.2-64-bit.exe and start the Git Bash.
The cmd and bin/bash.exe and bin/sh.exe works fine.
