### ISSUE TITLE
Foreign characters rendering problem

### ISSUE THREAD

**Issue by hinell** [git-for-windows/git#1022]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Description
Hi there.
Today after updating & running latest git bash version **git/bin/bash.exe** and typing foreign characters (Russian keyboard layout, i.e. Russian symbols) I got this: 
![unnamed](https://cloud.githubusercontent.com/assets/8136158/21654165/6a6596b4-d2c5-11e6-9c34-25e3149e447b.png)
As you can see it is a little bit different from what I expected. 
Tried all these bash tools running them _shelllessly_:

**git/bin/sh.exe   - _shows odd characters after typing_
git/bin/bash.exe - _same_
git/git-bash.exe  - _happen nothing when typing foreign chars_
git/git-cmd.exe   - _works well_**
Latest is ok but it is not suitable for using, cause there is no current branch & colors are shown
(at least for me, lol).

Notably, previous v2.10.1.windows.2 version worked seamlessly with any chars I'm typing in.
May be there is a problem with UTF-8 rendering inside MINGW?
Recently I've rolled back onto 10.2 version and it is working well.   
Don't know why new version hates russian lang lol. :laughing: 
I hope guys you will help me with this.

### Setup

 >Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```
 >Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
Windows 7 x64 6.1.7601 SP1 
```

> What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

>Any other interesting things about your environment that might be related
   to the issue you're seeing?

`---`

### Details

> _Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other_

Normally I use [ConEmu](https://github.com/Maximus5/ConEmu) shell for running git-bash, but this time I didn't and run all shelllessly. 

> _What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue._

NO commands at all. 
> _What did you expect to occur after running these commands?_

> _What actually happened instead?_

> _ If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?_

**Comment by dscho** [comment]
Could you test the most recent prerelease, please? https://github.com/git-for-windows/git/releases/tag/v2.11.1.windows-prerelease.1

**Comment by JoeSchr** [comment]
the prerelease fixed it for me, ty

**Comment by hinell** [comment]
>Could you test the most recent prerelease, please? https://github.com/git-for-windows/git/releases/tag/v2.11.1.windows-prerelease.1

Yes, already have done this. Used git-bash.exe from install folder. Odds characters appears normal now: 
![screenshot_3](https://cloud.githubusercontent.com/assets/8136158/21701241/970ee8f0-d3b5-11e6-8ac8-dd96b7084243.png)

Seems problem is resolved. Don't know what a magic power you have used guys but it works.
Thanks. :+1:

**Comment by dscho** [comment]
> But with git/bin/sh.exe and git/bin/bash.exe problem still exists:

Please note that the `bin/` executables are purely intended for backwards-compatibility, *for non-interactive usage*. Do not expect them to work correctly when using them interactively.
