### ISSUE TITLE
Processes are running in session .... close anyway (this comfirm should hide by default)

### ISSUE THREAD

**Issue by eromoe** [git-for-windows/git#1023]
### Setup

 - Which version of Git for Windows are you using?  

```
git version 2.11.0.windows.1  64-bit
```

 - Which version of Windows are you running? 

win 10 x64

##  Detail

Today, I update git-bash( previous version was installed on 2016.6, didn't remenber exactly version )

The problem is it keep showing below message when I close it
![c bkwn f n0_ 4 75 cthm](https://cloud.githubusercontent.com/assets/3938751/21718380/099eaca6-d452-11e6-893b-7459d6fbbb07.png)

It happen when I ssh on a remove server , which never happen on older version. 

I found I have to config this

![gy a ew1 ausjwo8tki jl](https://cloud.githubusercontent.com/assets/3938751/21718592/61657bd0-d453-11e6-8281-fc138b340d00.png)

But this confirm is totally useless and annoying, I can't imagine why one need this confirm, it should be hide by default. One useful confirm prompt would be `Confirm on close` , not `Confirm on close when I have more than one processes running `, though git-bash should ask if a user need `Confirm on close` first time.

**Comment by dscho** [comment]
What one user may find totally useless is valued by many others. I, for one, am very grateful for that warning, it helped me avoid disaster before.

So: sorry, this is not up for discussion.
