### ISSUE TITLE
Can't push to shared directories which I can push by using Git-2.10.1

### ISSUE THREAD

**Issue by yumesmile** [git-for-windows/git#1024]
I can't push my branch to shared directories, it works correctly previous version though.
share directory path is //snn41/... but this version git doesn't recognize the path correctlly.
this version git recognize it as /snn41/...     orz

I confirmed it works correctly by using previous version, Git-2.10.1

Git-2.11.0 log on tortoiseGit 2.3.0 (error occured)
```
git.exe push --progress "origin" master

Counting objects: 1385, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (551/551), done.
Writing objects: 100% (1385/1385), 1.91 MiB | 1.50 MiB/s, done.
Total 1385 (delta 985), reused 1196 (delta 806)
remote: error: object directory /snn41/LET3G_SOFT/LET30G_FuncUP.git/objects does not exist; check .git/objects/info/alternates.
remote: Resolving deltas:  16% (167/985), completed with 0 local objects.
remote: fatal: pack has 818 unresolved deltas
error: unpack failed: index-pack abnormal exit
To //snn41/LET3G_SOFT/LET30G_FuncUP.git
! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to '//snn41/LET3G_SOFT/LET30G_FuncUP.git'


git did not exit cleanly (exit code 1) (5944 ms @ 2017/01/07 12:06:44)
```

Git-2.10.1 log on tortoiseGit 2.3.0 (successed)
```
git.exe push --progress "origin" master

Counting objects: 6695, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2825/2825), done.
Writing objects: 100% (6695/6695), 10.20 MiB | 1.91 MiB/s, done.
Total 6695 (delta 4143), reused 6042 (delta 3747)
remote: Resolving deltas: 100% (4143/4143), done.
To //snn41/LET3G_SOFT/LET30G_FuncUP.git
* [new branch]      master -> master

Success (14539 ms @ 2017/01/07 13:12:21)
```

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

nothing

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 other [tortoiseGit]

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git.exe push --progress "origin" master
```
 - What did you expect to occur after running these commands?

 recognizing shared directory path incorrectly.

 - What actually happened instead?

can't push cleanly.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 ---

**Comment by tboegi** [comment]
Please have a look at
https://github.com/git-for-windows/git/issues/979
(as I strongly suspect that this is already reported and fixed)

**Comment by PhilipOakley** [comment]
Try https://github.com/git-for-windows/git/releases/tag/v2.11.1.windows-prerelease.1 to confirm it fixes it for you.

**Comment by yumesmile** [comment]
Oh I'm sorry. I didn't realize there are new release. Because I download the software from 
https://git-for-windows.github.io/

that page still provides v2.11.0 as newest one. thank you.

**Comment by dscho** [comment]
@yumesmile it is a *prerelease*. Meaning that yes, v2.11.0 is still the newest official release. But the prerelease already contains changes that the next official release will contain, ready for users (like you, hint, hint, *hint*) to test.

> Oh I'm sorry. I didn't realize there are new release. Because I download the software from
> https://git-for-windows.github.io/
> 
> that page still provides v2.11.0 as newest one. thank you.

You forgot the most important part.

To test the prerelease and to report whether it fixes your issue.

**Comment by dscho** [comment]
The newest official release is v2.11.0(3) and it contains the fix.

**Comment by yumesmile** [comment]
Sorry for late response
I confirmed with git 2.12.0 to fetch from share directory. And now it looks working good.
