### ISSUE TITLE
Redirect causes hang when setting a variable

### ISSUE THREAD

**Issue by mavericken** [git-for-windows/git#1025]
In a pre-commit hook, or when I directly execute git-bash like so:
"C:\Program Files\Git\git-bash.exe" --cd-to-home

I have only got it to happen when I do "npm ls" command in a directory with a node.js package.

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64

$ npm ls 2>&1
test-dir@1.0.0 C:\Work\test-dir
`-- lpad@2.0.1

$ test=$(npm ls 2>&1)
******hangs right here and will never return******
```

This works fine in a real bash environment.

**Comment by dscho** [comment]
> npm

You forgot to specify which version of `npm`, and where exactly you downloaded it from.

For that matter, you forgot to fill out the entire issue reporting template. This template is intended to help you with reporting any bugs efficiently, and it is not helpful to simply delete it and provide nothing like the information needed to be able to help you with your problem.

For the record, I tried this with NPM that came as part of some node.js I downloaded from https://nodejs.org/:

```sh
$ which npm
/c/Program Files (x86)/nodejs/npm

$ npm --version
2.7.4

$ npm ls
C:\git-sdk-64\usr\src\git
└── (empty)

$ test="$(npm ls 2>&1)"

$ echo "$test"
C:\git-sdk-64\usr\src\git
└── (empty)
```

That means that the Minimal, Complete & Verifiable Example the issue reporting template asked for is no joke, or something we ask to annoy users. It is something that is a very serious matter, in particular when it is missing from a report. The idea of requiring it is to avoid frustration on both sides: the bug reporter, and the people who want to help.

> This works fine in a real bash environment.

Define "real bash environment". But please only after coming back with a real MCVE.

**Comment by mavericken** [comment]
I do see that you made an effort to try to investigate this, and I can understand why you are frustrated being unable to replicate with only the information I gave you, so I am sorry for that.  I have to budget my time also, and there is not enough time for multi page forms for bug reports, so I am left with the choice of bringing something less than that or bringing nothing at all.  If nothing at all is better, then I don't mind if someone closes this.

In case this doesn't get closed, here is some extra info:

```
$ which npm
/c/Program Files/nodejs/npm

$ npm --version
3.10.3

$ node --version
v6.9.2
```

The real bash environment I was referring to is bash running in a terminal on Ubuntu.

**Comment by dscho** [comment]
There is little to nothing I can do about this bug until I get a reproducer.

In the meantime, you could try to call `test=$(strace -o /tmp/a1 npm ls 2>&1)` and see whether `/tmp/a1` contains any clues.

Good hunting!

**Comment by mavericken** [comment]
Well, I could be the only one facing this problem, and I don't need a solution as I had rather quickly decided to not even use the library that exposed the problem.  I'll close so as not to draw focus away from stuff that people need solved.  I appreciate the effort though.
