### ISSUE TITLE
How to add python support to Git for Windows?

### ISSUE THREAD

**Issue by toninlg** [git-for-windows/git#103]
Hi,
I've installed Git for Windows 2.3.5 release 8. I would like to use a python script in it but it seems to come with perl but not with python. How can I add support for python? Do I have to download the SDK and build python with it?
I saw in the wiki that pacman is used as package management but it is only for the SDK and not included in Git for Windows?

Thank you.

**Comment by dscho** [comment]
Git for Windows is really that: *Git for Windows*. Not a general purpose package system.

If you are looking for a system that lets you install packages such as Python, you will have to use MSys2, or the Git SDK (which is a slightly modified version of MSys2).

**Comment by toninlg** [comment]
Well subject is already closed... So I spent two days on installing it, setting it and trying it for something that will not work because I would like to use a git bpf script written in python?
You should really update your wiki.

**Comment by dscho** [comment]
> Well subject is already closed...

Yeah, sorry. People keep adding new tickets and I am the only one really taking care of them, so I have to close more tickets, and sooner, than I would like to.

> You should really update your wiki.

Please understand that this statement really insults me. Why do *I* have to do everything *you* want? I am already working hard on updating Git for Windows to version 2.x in conjunction with MSys2 (and mind you, this has kept me very busy for three full months now), I try to address tickets as time allows, and I answered your question in a most precise way.

Telling me to update "my" wiki (instead of trying to help me with it, for a change) just sounds ungrateful, and I am sure that was not your intention.

**Comment by nalla** [comment]
*OT*

> People keep adding new tickets and I am the only one really taking care of them

Hey! You're not alone :-)

**Comment by dscho** [comment]
@nalla Oh, sorry! You really help me a lot, thank you so much!

**Comment by toninlg** [comment]
Hi,

Sorry about this, it was not intended to be hurtful.
The lack of python was quoted there https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md.
I manage to make a new installer with python support by adjusting the make-file-list.sh from build-extra repository.
I thought that because it was included with msys2 it will work, but it's not the case. I tried it with a script for release notes generation and with the same script, the same config file, the same git repository: sometimes it works, sometimes it fails with a parse error, sometimes it doesn't fail but the output is only partial.

**Comment by dscho** [comment]
> The lack of python was quoted there https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md.

Please note that you quote from the developers' preview, where I simply did not get around to update the end-user facing documentation yet.

> I manage to make a new installer with python support by adjusting the make-file-list.sh from build-extra repository.
> I thought that because it was included with msys2 it will work, but it's not the case. I tried it with a script for release notes generation and with the same script, the same config file, the same git repository: sometimes it works, sometimes it fails with a parse error, sometimes it doesn't fail but the output is only partial.

It appears to me that it would be easiest if you stuck with MSys2 (or the Git SDK, although that is really targeting Git for Windows contributors).

**Comment by toninlg** [comment]
Thank you for your answer. I have tried with the SDK: with python2 which is the default one I have the error 'close_fds is not supported on Windows' when I execute the script (error reported in github repository for this script), with python3 this error is not there but the behavior is the same as in Git for Windows.
I'm not sure if the problem is on the Python side, on the Git side, or on the environment side. But it seems to be a problem when splitting the value received from Git:
> error1: float(self.author_date_timestamp))
ValueError: could not convert string to float: 'tag v1.1\nTagger: xxx <xxx>\n\nTagging version 1.1\n\n1430061838'

>error2: key=lambda x: int(x.committer_date_timestamp))
ValueError: invalid literal for int() with base 10: 'tag v1.0\nTagger: xxx <xxx>\n\nTagging version 1.0\n\n1430046846'

I will try to investigate this.

**Comment by sschuberth** [comment]
@dscho Would you accept a PR that adds Python to the Git for Windows user installer so that e.g. `git-p4` could be run out of the box?

**Comment by toninlg** [comment]
@sschuberth Fyi, I've included python 3.3.3 by modyfing make-file-list.sh script, but I had problems when running the python script gitchangelog (https://github.com/vaab/gitchangelog/issues/27), but it seems to be non specific-related to Windows.

**Comment by sschuberth** [comment]
@toninlg Thanks, I know this is easily possible, but I'd like to get this upstream and make Git for Windows ship Python by default. The question is whether @dscho is willing to accept the additional weight this adds to the installer.

**Comment by tkelman** [comment]
Is this the msys2 (a la cygwin) python, or the super-heavily-patched mingw-w64 python? Lots of python modules out in the wild have issues with msys2's python (virtualenv is one especially notable example), might not want to give people the wrong idea and start making git for windows into a seemingly official distribution channel for a build of python that isn't really supported by anyone.

**Comment by sschuberth** [comment]
I do not (yet) have a strong opinion on that. It seems upstream MSYS2 [has](https://github.com/Alexpux/MSYS2-packages/tree/master/python2) [both](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-python2), so we're free to choose.

**Comment by dscho** [comment]
> @dscho Would you accept a PR that adds Python to the Git for Windows user installer so that e.g. git-p4 could be run out of the box?

This would increase the size of the installer in a rather prohibitive way, methinks. At the moment, the biggest ticket for me before releasing a first official 2.x version of Git for Windows is to reduce the size of the installer again. It has increased from 23 to 45 megabytes, and that is not a laughing matter.

I would also like to point out that `git-p4` is in the `contrib/` section and as such I am less inclined to take on the maintenance burden it would add to Git for Windows.

**Comment by sschuberth** [comment]
> I would also like to point out that `git-p4` is in the `contrib/` section

Actually I do see [git-p4.py](https://github.com/git/git/blob/master/git-p4.py) in the root. Also see the contents of [contrib/fast-import/git-p4.README](https://github.com/git/git/blob/master/contrib/fast-import/git-p4.README).

**Comment by dscho** [comment]
Whoops, I missed b6f930576469052af87e96b549c37630b56aab93.

> Given that Git for Windows also already ships with git-p4 I think it would make sense for us to also support running it.

Sure. What about the heavy penalty of adding Python to the installer? Any idea how to balance that?

**Comment by sschuberth** [comment]
Well, I basically only see the option to not directly include Python into the installer but either to

* ship the installer with `pacman` instead to make Python (and any other MSYS2 package) easily installable afterwards,
* or use an Inno Setup add-on like [DwinsHs](http://www.han-soft.com/dwinshs.php) to download Python on demand at install time.

**Comment by dscho** [comment]
Urgh. Both options would add so much complexity! I am pretty much flat out against any of the two.

**Comment by nalla** [comment]
What about shipping two versions? One with `python` to support `git-p4`, describing that version explicit as _necessary bloat-ware_. One version without `python`?

**Comment by dscho** [comment]
@nalla that would be a good option. I'll see how quickly I can set up those Jenkins jobs I wanted to have for building releases. Won't be before next week, but I think with those jobs, adding an installer including Python would not be a lot of maintenance hassle. Getting things to run properly is still likely to be hairy.
