### ISSUE TITLE
Bad Address error when ORIGINAL_PATH starts with / and contains ://

### ISSUE THREAD

**Issue by Vermora** [git-for-windows/git#1033]
I get a Bad Address error whenever the ORIGINAL_PATH variable starts with ```/``` and contains ```://```.

I installed git-2.11.0.windows.3. Then I started Git Bash.
Whenever I used a git command in Git Bash, I received a Bad Address error:

```
$git --version
bash: /mingw64/bin/git: Bad address
```

I did not receive this error when using the same command in Windows command prompt:
```
C:\Windows\System32>git --version
git version 2.11.0.windows.3
```

This problem remained after multiple uninstalls and re-installs.

This problem disappeared when I removed all entries containing // from ORIGINAL_PATH.
However this is not a permanent fix; when I closed and then restarted Git Bash, the problem appeared again since ORIGINAL_PATH had reverted back to its original value.

To solve the problem permanently, I uninstalled git-2.11.0.windows.3, then removed all entries containing \\\\ from the User variable Path.

Then I re-installed git-2.11.0.windows.3, and I no longer saw the Bad Address error.

I did some further experimentation with the ORIGINAL_PATH variable. I go the Bad Address error to appear whenever ORIGINAL_PATH started with ```/``` and also contained ```://```:
```
$ ORIGINAL_PATH="abcde://"
$ git --version
git version 2.11.0.windows.3

$ ORIGINAL_PATH="/abcde//"
$ git --version
git version 2.11.0.windows.3

$ ORIGINAL_PATH="/abcde://"
git --version
bash: /mingw64/bin/git: Bad Address
```

See also: http://stackoverflow.com/questions/41699029/cant-run-git-in-git-bash-bash-mingw32-bin-git-bad-address.

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.3
built from commit: e11df2efb3072fe73153442589129d2eb8d9ea02
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

**Comment by dscho** [comment]
What a pleasantly complete bug report! I can reproduce and will investigate right now.
