### ISSUE TITLE
Updating the git-for-windows repos result in HTTP 401

### ISSUE THREAD

**Issue by Osse** [git-for-windows/git#1037]
I prefer to use Git in MSYS2 since I have other needs for MSYS2 also. Recently when running `pacman -Sy` I get. 

```
error: failed retrieving file 'git-for-windows.db' from dl.bintray.com : The requested URL returned error: 401
```
My `/etc/pacman.conf` contains exactly what is described on the wiki, and it used to work up until a few days ago. I am not sure exactly when.

**Comment by zommuter** [comment]
Same here. https://dl.bintray.com/git-for-windows/pacman/x86_64/git-for-windows.db asks for a username and password, but anything I enter results in an empty page. In fact, the whole tree https://dl.bintray.com/git-for-windows/pacman/x86_64 is empty, in contrast to https://dl.bintray.com/git-for-windows/pacman/i686 (though that also misses the `git-for-windows.db`)

**Comment by dscho** [comment]
Some artifacts were uploaded, but not published properly afterwards. This is now fixed.
