### ISSUE TITLE
Chunked push broke between 2.11.0.windows.1 and 2.11.0.windows.3

### ISSUE THREAD

**Issue by kria** [git-for-windows/git#1040]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.1.windows.prerelease.2
built from commit: 86d49ccac7afb39e03ba2632803c5ab67d4bb792
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

**I get `fatal: The remote end hung up unexpectedly` on 2.11.0.windows.3 and 2.11.1.windows.prerelease.2 using chunked transfer encoding (if I up postBuffer it works) to a Team Foundation Server 2017**
```
$ git --version
git version 2.11.0.windows.1

$ git push -v https://tfs.example.com/tfs/DefaultCollection/ALM/_git/pushtest develop
Pushing to https://tfs.example.com/tfs/DefaultCollection/ALM/_git/pushtest
Counting objects: 10578, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (8358/8358), done.
POST git-receive-pack (chunked)8)
Writing objects: 100% (10578/10578), 90.13 MiB | 14.42 MiB/s, done.
Total 10578 (delta 5183), reused 6955 (delta 1769)
remote: Analyzing objects... (10578/10578) (9168 ms)
remote: Storing packfile... done (2633 ms)
remote: Storing index... done (58 ms)
To https://tfs.example.com/tfs/DefaultCollection/ALM/_git/pushtest
 * [new branch]      develop -> develop
```

```
$ git --version
git version 2.11.0.windows.3

$ git push -v https://tfs.example.com/tfs/DefaultCollection/ALM/_git/pushtest develop
Counting objects: 10578, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (8358/8358), done.
POST git-receive-pack (chunked)8)
Writing objects: 100% (10578/10578), 90.24 MiB | 15.03 MiB/s, done.
Total 10578 (delta 5168), reused 6970 (delta 1769)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Pushing to https://tfs.example.com/tfs/DefaultCollection/ALM/_git/pushtest
Everything up-to-date
```

**Comment by dscho** [comment]
Thank you for your report.

Would you mind repeating both pushes after setting the environment variable `GIT_TRACE_CURL=1`?

**Comment by kria** [comment]
I'm not able to reproduce it on 2.12. If you're still interested in a trace of the failure on earlier version, I can send you.
