### ISSUE TITLE
git-gui ignores core.hookspath

### ISSUE THREAD

**Issue by mserfli** [git-for-windows/git#1042]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.0.windows.3
built from commit: e11df2efb3072fe73153442589129d2eb8d9ea02
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

I'm using the portable Git bundle
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git-gui.exe
```
 - What did you expect to occur after running these commands?
I have defined a pre-commit and set the path to it using core.hookspath, but when commiting in git gui it is not considered. Commiting directly on the cmd shell using git commit -a -m "ndkfnj" it works perfectly.

 - What actually happened instead?
pre-commit hook is not considered

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no it's just a local repository on my harddrive

**Comment by dscho** [comment]
I suspect that this is not limited to Windows. If that is the case, a better venue to report this bug is [the Git mailing list](mailto:git@vger.kernel.org) (which also has a *lot* more volunteers who may jump on this issue than the Git for Windows project).
