### ISSUE TITLE
Git windows 2.11.1 no longer includes git-credential-manager?

### ISSUE THREAD

**Issue by moosekaka** [git-for-windows/git#1043]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.1.windows.prerelease.2.11.g5c61ec6
built from commit: 5c61ec6be7f6de205df2189f60301cb08a79ca9e
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
I installed the sdk package by running setup-git-sdk.bat file include in the 7zip installer.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-cmd on Conemu

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
```
 - What did you expect to occur after running these commands?

Should push without having to ask for password after first attempt successful.

 - What actually happened instead?
```
git: 'credential-manager' is not a git command. See 'git --help'.
```
 Asks for password the next time I want to push

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
https://github.com/git-for-windows/build-extra/releases/tag/git-sdk-1.0.3

Previously since [v2.10.2]( https://github.com/git-for-windows/git/releases/tag/v2.10.2.windows.1)   Git Credential Manager v1.8.1 was included with the SDK. However on installing latest version of the SDK, I find that the GCM is not installed and Git complains that it cant find credential-manager. I have to do
`git config --global credential.helper wincred` in order to not have to insert my password everytime I want to push.

**Comment by shiftkey** [comment]
@moosekaka I'm curious - why you are using the SDK for regular Git tasks, instead of the public releases?

**Comment by moosekaka** [comment]
Because I want to run git-cmd in Conemu with Bash, and install other software in this bash, like manpages. I was told this was not possible with the public release.

**Comment by dscho** [comment]
In the SDK, we try to install stuff only as required. (Not always succeeding.)

You probably need to install the credential manager manually in the SDK, via `pacman -S mingw-w64-x86_64-git-credential-manager`.

Try that?

**Comment by moosekaka** [comment]
I did that last night with another machine on a fresh SDK install and it installed. However this morning on another machines, seems my pacman cant find it:
```
mingw-w64-x86_64-git-credential-manager`
error: target not found: mingw-w64-x86_64-git-credential-manager
```

The other issue is that Git-for windows v2.10.2 listed it as coming with Git Credential Manager v1.8.1  in the release notes. However I looked at the release notes for newer Git-for windows releases since then and I couldn't find anything said about Git Credential Manager v1.8.1 been taken out.

**Comment by nalla** [comment]
Try `mingw-w64-git-credential-manager`.

**Comment by moosekaka** [comment]
Already did that, same results. On visiting the mingw64 repo listed in /etc/pacman.d/mirrorlist.mingw64 (http://repo.msys2.org/mingw/x86_64), it seems that git-credential-manager isnt't listed at all.

**Comment by nalla** [comment]
It comes from https://github.com/git-for-windows/build-extra/blob/master/mingw-w64-git-credential-manager/PKGBUILD

**Comment by moosekaka** [comment]
I don't know whats going on, but cloning the above link (or forking it to my own repo and cloning it) is not downloading anything from the repo. In fact when following the instructions on that page:
```
cd /usr/src/build-extra
git fetch
git checkout master
```
I get an
`error: pathspec 'master' did not match any file(s) known to git.`

Maybe this is GCM is not installing on my install? What could possibly prevent me my git from succesfully cloning?
