### ISSUE TITLE
Every time with git pull or other commands (Enter passphrase for key ***)

### ISSUE THREAD

**Issue by lordgreg** [git-for-windows/git#1045]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64
```
$ git --version --build-options

`git version 2.11.0.windows.3`
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit

```
$ cmd.exe /c ver

`Microsoft Windows [Version 10.0.14393]`
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Always using Git Bash

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
Pulling branch or showing tracking info

 - What actually happened instead?

`Enter passphrase for key '/c/Users/me/.ssh/my-ssh.key':`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **
all on bitbucket.

### Additional info:

`.ssh/config` has two keys listed:
```
IdentityFile ~/.ssh/another_rsa_without_passphrase
IdentityFile ~/.ssh/my-ssh.key # with passphrase
```

This is just driving me nuts. Everytime I reopen bash, keys are missing from `ssh-add -l`. Why?

**Comment by nalla** [comment]
Try http://stackoverflow.com/a/2419609

**Comment by lordgreg** [comment]
Thank you @nalla for your response, I've already did this, and configured `config`, removed `known_hosts`.

My config:
```
Host myshortname github.com
    HostName github.com
    IdentityFile ~/.ssh/github_rsa
    User remoteUserOnGithub

Host myother bitbucket.org
    HostName bitbucket.org
    IdentityFile ~/.ssh/my-ssh.key
    User remoteUserOnBitbucket
```

And again, I'm constantly getting asked for passphrase.

I've even verified if I'm adding correct key with:
`ssh-keygen.exe -y -f my-ssh.key` which outputed the ssh key without errors.

**Comment by dscho** [comment]
> ssh-add -l shows agent (opened with eval $(ssh-agent -s)) has no keys. So I've added them again. Then, both keys were visible with first command. However, when closing bash window and reopening it, keys were gone again.

This is actually expected. GIt for Windows has no automatic ssh-agent setup, as many users prefer *Git CMD* over *Git Bash* (and therefore, setting up an ssh-agent in the Bash profile could actively hurt the performance).

This wiki page may be helpful to automate this: https://github.com/git-for-windows/git/wiki/Auto-launching-ssh-agent-when-git-starts#manually
