### ISSUE TITLE
git version 2.11.0.windows.3 cannot push or pull

### ISSUE THREAD

**Issue by moosekaka** [git-for-windows/git#1046]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.3
built from commit: e11df2efb3072fe73153442589129d2eb8d9ea02
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

git-sdk-installer-1.0.3-64.7z
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using the default git that is installed from the SDK (mingw64/bin), git is broken. However if I force the shell to use /usr/bin/git, git works, but it runs git version 2.11.0. No idea why this is broken. I have tried with both wincred and GCM.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash (Git SDK 64-bit)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
which git
/mingw64/bin/git
git push
```
 - What did you expect to occur after running these commands?

Commit remains unpushed. Git fetch and git clone also results in no repositories been fetched or cloned.

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by shiftkey** [comment]
@moosekaka please run `git push` with `GIT_TRACE=1` and `GIT_CURL_VERBOSE=1` set - it's really hard to say what is occurring without more information...

**Comment by moosekaka** [comment]
→ GIT_TRACE=1 git push
00:20:31.632052 git.c:371               trace: built-in: git 'push'
00:20:31.632052 run-command.c:350       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/moosekaka/sweepython'

 →GIT_CURL_VERBOSE=1 git push

no output

switching to git from /usr/bin ,  →GIT_CURL_VERBOSE=1 git push produces a long list of output which I can cut and paste if you want.

**Comment by dscho** [comment]
Why are you using Git for Windows' SDK? Do you want to contribute patches?

**Comment by moosekaka** [comment]
Because I want man pages (and other tools provided by pacman). I believe in your comments below in this issue:
```
https://github.com/git-for-windows/git/issues/696
```
You yourself said that installing Git SDK was the best way to go about it.

**Comment by dscho** [comment]
Right. But please note that the Git for Windows SDK is a really big effort, intended to *help me* with developing Git for Windows by making it easier for contributors to ... contribute. Instead, I am now stuck with taking care of issues in the SDK that will not relieve me of any maintenance/development burden.

To address your concern (since I already spent time on this rather than on making Git for Windows better): @elieux suggested on Gitter that this may be caused by an incorrect dependency declaration of `mingw-w64-gnutls` that does not list `mingw-w64-libunistring`.

So calling `pacman -S mingw-w64-x86_64-libunistring` may get you back on track.
