### ISSUE TITLE
diff --no-index between file1 and file2 fails in subdirectory

### ISSUE THREAD

**Issue by mikhailian** [git-for-windows/git#1048]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
built from commit: e11df2efb3072fe73153442589129d2eb8d9ea02
sizeof-long: 4
machine: x86_64
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
@/c/dev$ git --version
git version 2.11.0.windows.3
@/c/dev$ mkdir test
@/c/dev$ cd test
@/c/dev/test$ git init
Initialized empty Git repository in C:/dev/test/.git/
 (master)@/c/dev/test$ mkdir 1
 (master)@/c/dev/test$ touch 1/1.txt
 (master)@/c/dev/test$ git add 1/1.txt
 (master)@/c/dev/test$ git commit -m 'Initial commit'
[master (root-commit) c52c849] Initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 1/1.txt
 (master)@/c/dev/test$ git diff --no-index /dev/null 1/1.txt
diff --git a/1/1.txt b/1/1.txt
new file mode 100644
index 0000000..e69de29
 (master)@/c/dev/test$ cd 1
 (master)@/c/dev/test/1$ git diff --no-index /dev/null 1.txt
error: Could not access '1/nul'
 (master)@/c/dev/test/1$ git diff --no-index /dev/null /c/dev/test/1.txt
error: Could not access '1/nul'
 (master)@/c/dev/test/1$ git diff --no-index --relative=/c/dev/test /dev/null 1/1.txt
error: Could not access '1/nul
```
 - What did you expect to occur after running these commands?
```
new file mode 100644
index 0000000..e69de29
```
 - What actually happened instead?
```
error: Could not access '1/nul
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This only happens in a subdirectory of a repository,not in its root.

**Comment by mikhailian** [comment]
Try also 
```
touch 2.txt
git diff --no-index 1.txt 2.txt
```
you will see that  the error message will be

```
error: Could not access `1/1/2.txt`
```

The problem is a bit more explicit, now.

**Comment by PhilipOakley** [comment]
Do you have access to a Linux machine in anyway to see if this is an upstream  issue?

It's good to have your script (to summarise):
```
git --version
mkdir test
cd test
git init
mkdir 1
touch 1/1.txt
git add 1/1.txt
git commit -m 'Initial commit'

git diff --no-index /dev/null 1/1.txt

cd 1
git diff --no-index /dev/null 1.txt
git diff --no-index /dev/null /c/dev/test/1.txt
git diff --no-index --relative=/c/dev/test /dev/null 1/1.txt

touch 2.txt
git diff --no-index 1.txt 2.txt
```

**Comment by mikhailian** [comment]
I can not reproduce the issue on Linux using git 2.11.0.

**Comment by PhilipOakley** [comment]
Could this be related to https://github.com/git-for-windows/git/issues/1016 where 'nul' (note the single 'l') was accidently disabled.  I see in your report it has a similar `error: Could not access '1/nul'`.

The other option is to try the commands with `GIT_TRACE=1` (prefixed) to get a more verbose output of what is happenning (the env var is detailed on the `git help git` page)

**Comment by mikhailian** [comment]
@PhilipOakley nope, null device exists on my Windows PC. Also, It looks like there are two separate issues: one issue when diffing /dev/null and the other — when diffing normal files. See below. 
```
@/c/dev$ mkdir test
git commit -m 'Initial commit'
git diff --no-index subdir/1.txt subdir/2.txt
cd subdir
git diff --no-index  1.txt 2.txt
git diff --no-index  --relative=/c/dev/test/subdir 1.txt 2.txt
git diff --no-index  --relative=/c/dev/test subdir/1.txt subdir/2.txt@/c/dev$ cd test
@/c/dev/test$ git init
Initialized empty Git repository in C:/dev/test/.git/
 (master)@/c/dev/test$ mkdir subdir
 (master)@/c/dev/test$ touch subdir/1.txt
 (master)@/c/dev/test$ echo "some content" >subdir/2.txt
 (master)@/c/dev/test$ git add subdir/1.txt subdir/2.txt
warning: LF will be replaced by CRLF in subdir/2.txt.
The file will have its original line endings in your working directory.
 (master)@/c/dev/test$ git commit -m 'Initial commit'
[master (root-commit) d4a3e57] Initial commit
 2 files changed, 1 insertion(+)
 create mode 100644 subdir/1.txt
 create mode 100644 subdir/2.txt
 (master)@/c/dev/test$ git diff --no-index subdir/1.txt subdir/2.txt
diff --git a/subdir/1.txt b/subdir/2.txt
index e69de29..2ef267e 100644
--- a/subdir/1.txt
+++ b/subdir/2.txt
@@ -0,0 +1 @@
+some content
warning: LF will be replaced by CRLF in subdir/2.txt.
The file will have its original line endings in your working directory.
 (master)@/c/dev/test$ cd subdir
 (master)@/c/dev/test/subdir$ git diff --no-index  1.txt 2.txt
diff --git a/1.txt b/2.txt
index e69de29..2ef267e 100644
--- a/1.txt
+++ b/2.txt
@@ -0,0 +1 @@
+some content
warning: LF will be replaced by CRLF in subdir/2.txt.
The file will have its original line endings in your working directory.
 (master)@/c/dev/test/subdir$ git diff --no-index  --relative=/c/dev/test/subdir 1.txt 2.txt
diff --git a/1.txt b/2.txt
index e69de29..2ef267e 100644
--- a/1.txt
+++ b/2.txt
@@ -0,0 +1 @@
+some content
warning: LF will be replaced by CRLF in subdir/2.txt.
The file will have its original line endings in your working directory.
 (master)@/c/dev/test/subdir$ git diff --no-index  --relative=/c/dev/test subdir/1.txt subdir/2.txt
error: Could not access 'subdir/subdir/1.txt'
```

**Comment by mikhailian** [comment]
@peff, I wonder whether the issue is related to [this commit](https://github.com/git/git/commit/7d8930d903fd8b775a1db63bcf373df5ac5af0be).

**Comment by peff** [comment]
Possibly. I seem to recall we've seen other bugs related to the `--relative` code.

I cannot reproduce on Linux (and it sounds like you could not either). Can you try building Git right before and right after that commit (and/or just reverting it from the tip and building that)? If that doesn't work and you have an older, working version, try `git bisect`.

**Comment by mikhailian** [comment]
@peff, I tried `git bisect` and found 28a4e580 being the root cause.

**Comment by peff** [comment]
@mikhailian Could you clarify what test you used for the biscetion? I'm looking at your comment in https://github.com/git-for-windows/git/issues/1048#issuecomment-277525761 and I'm not sure I understand what the issue is. Yes, the last `diff` invocation complained, but that is because you asked for `subdir/1.txt` while you were already in the `subdir` directory.

So I'm unclear on what output you're seeing that is unexpected there.

**Comment by mikhailian** [comment]
Here's the minimal test:
```
git init -q
mkdir one
touch one/1.txt
git add one/1.txt
git commit -m 'Initial commit' -q
cd one
git diff --no-index /dev/null 1.txt
```
Expected output:
```
diff --git a/1.txt b/1.txt
new file mode 100644
index 0000000..e69de29
```
Observed output:
```
error: Could not access 'one/nul'
```
First bad commit: 28a4e58.

I'd be happy to help more.

**Comment by peff** [comment]
@mikhailian Thanks. I'm not sure what to look at next, though.

The big change in that commit is that we actually initialize the repository and set up the subdir prefix. So I'm not surprised that the bug is triggered by that commit, but I'm not at all sure that it isn't simply a latent bug in the way Windows handles the /dev/null pathname.

I suspect the next step is somebody spending some time walking through the test case with a debugger. But as I can't reproduce on Linux and don't have a Windows machine, I think we'd need a volunteer to do that.

**Comment by dscho** [comment]
The culprit is the MSYS2 runtime which helpfully converts `/dev/null` to `nul` before passing the parameter to `git.exe` (because `git.exe` is not linking to the MSYS2 runtime and therefore is expected to have *no idea* about POSIX-isms such as `/dev/null`).

**Comment by dscho** [comment]
> git diff --no-index /dev/null 1.txt

So here is a workaround:

```sh
MSYS_NO_PATHCONV=1 git diff --no-index /dev/null 1.txt
```

(this environment variable is described in the [Known Issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues) of our release notes, for cases where POSIX paths are used and converted in an undesired way by the MSYS2 runtime.)
