### ISSUE TITLE
git for windows be stalled without only git-bash

### ISSUE THREAD

**Issue by lakin32** [git-for-windows/git#1049]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash/CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git  // just it
```
 - What did you expect to occur after running these commands?

i wanna to use git

 - What actually happened instead?

just stalled, hang, freeze

---

git for windows be hang, if i type 'git' with any options

## end of installation

The installation was stopped by the end of the installation.
so i killed git for windows process and installation was finished properly.

![install_hang](https://cloud.githubusercontent.com/assets/9916002/22620373/ea6205d2-eb4d-11e6-8248-e3cf00e49d8d.gif)

[here is installation log](https://github.com/git-for-windows/git/files/752453/gitlog.txt)

## bash

i try to use git via `bin/bash.exe`, but it is not work properly.

![bash_hang](https://cloud.githubusercontent.com/assets/9916002/22620384/3a9f7ca0-eb4e-11e6-9fc2-a588ab40465c.gif)

## cmd

In cmd, git will still not work properly.

![cmd_hang](https://cloud.githubusercontent.com/assets/9916002/22620393/70dee120-eb4e-11e6-989d-769c5748ab22.gif)

## git bash

Only works with git bash.

![git_bash_properly](https://cloud.githubusercontent.com/assets/9916002/22620408/b020fde6-eb4e-11e6-98fa-e4bd6c9d972a.gif)

## 32 git for windows

![32bit_hang](https://cloud.githubusercontent.com/assets/9916002/22620684/6ea8e008-eb54-11e6-96a3-b6e3e5fba21a.gif)

i don't know any hint why don't work properly.

**Comment by dscho** [comment]
That is curious. Can you stop the hanging process with Ctrl+C? What do you see when you set the environment variable `set GIT_TRACE=1` before calling Git?

**Comment by lakin32** [comment]
![image](https://cloud.githubusercontent.com/assets/9916002/23585306/9269c96e-01be-11e7-8e96-2cb9e822cbd6.png)

hi @dscho 

i did set environment value `GIT_TRACE=1` before calling `git` command. but i couldn't see anything.

i don't stop the git process using `Ctrl+C`.

umm... working properly sometimes like this. 
![image](https://cloud.githubusercontent.com/assets/9916002/23585368/7675deda-01c0-11e7-912f-9973d64060f6.png)

**Comment by dscho** [comment]
Sorry, I am out of ideas (as you probably guessed judging by my long silence). Maybe other people saw something similar and could chime in?

**Comment by whoisj** [comment]
What anti-malware, if any, do you have installed?

If you have anti-malware, can you add an exception for git.exe? Does that help?

Using a tool like [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) will collect significantly more data about the situation. With a tool like Procmon, you can see if an anti-malware or OS process is interfering with Git. There's also the possibility that your installation of Windows is somehow broken (malware, bad 3rd party installation, etc).

**Comment by lakin32** [comment]
@whoisj thanks for your help. i think your opinion is right. but already i did reformat my windows, so i cant reproduce this issue.

(my anti-virus program was [V3 lite version](http://global.ahnlab.com/site/product/productSubDetail.do?prodSeq=5805), i dont use it now..)
