### ISSUE TITLE
Paste text incorrectly in Vim[insert mode].

### ISSUE THREAD

**Issue by eromoe** [git-for-windows/git#1050]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** 
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
win 10  x64
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
default
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** git-bash(mintty) **

 - What commands did you run to trigger this issue? 

I want to paste below code to a file use vim,  by **mouse right click **. (same error paste by `ctrl + shift + insert`)

```
ZSH_THEME="avit"
VIM_THEME="powerlineish"
VIM_COLORSCHEME="elflord"
OS="`uname -s`"

function getos(){
    # http://stackoverflow.com/a/27776822/1637673
    case "$(uname -s)" in
       Darwin)
         OS='mac'
         ;;
       Linux)
         OS='linux'
         ;;
       CYGWIN*|MINGW32*|MSYS*)
         OS='win'
         ;;
       # Add here more strings to compare
       # See correspondence table at the bottom of this answer
       *)
         OS='other'
         ;;
    esac
    echo $OS
}
```

 - What did you expect to occur after running these commands?

![default](https://cloud.githubusercontent.com/assets/3938751/22632023/b2cf77f4-ec50-11e6-8da4-e257d512d6d5.png)

 - What actually happened instead?

![default](https://cloud.githubusercontent.com/assets/3938751/22632037/d1428bd6-ec50-11e6-8765-0086170ce5ea.png)

Only codes with line feed and blanks/tab pasted incorrectly.

**Comment by sxlijin** [comment]
This is not an issue.

If Vim has `autoindent` set, then pasting content in insert mode will auto-indent all pasted lines. You want to `set paste` before pasting to disable this behavior, and then `set nopaste` after pasting to re-enable it.

@dscho flagging for close.

**Comment by eromoe** [comment]
Thank you for the tips !

I find can automatically set/unset Vim's paste mode by adding below to `~/.vimrc`:
```
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
```
from https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode

**Comment by dscho** [comment]
@sxlijin thanks for looking into this!

@eromoe please note also that vim's `P` shortcut pastes the clipboard directly (in command-mode, not in insert-mode) and that the code is not reformatted in that case.
