### ISSUE TITLE
Need netcat utility in git bash

### ISSUE THREAD

**Issue by APerson01** [git-for-windows/git#1051]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
git-bash 64-bit in windows

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None.

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Shortcut(Link): "C:\Program Files\Git\git-bash.exe" --cd-to-home

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I can run http(s) over ssh tunneling.  I need to run ssh command over ssh tunneling.
Examples are ...
ssh -t -o ProxyCommand='ssh vivek@Jumphost nc FooServer 22' vivek@FooServer htop

 - What did you expect to occur after running these commands?
ssh over ssh.

 - What actually happened instead?

nc command not found

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None

**Comment by APerson01** [comment]
I need nc command to use along with ssh. Is it possible to include it in future versions?

**Comment by APerson01** [comment]
Reference for nc command
https://en.wikipedia.org/wiki/Netcat

**Comment by PhilipOakley** [comment]
The Git for Windows, or GfW SDK is not meant to be a fully fledged environment, rather it's just enough to allow the GfW code to be developed and debugged. 

You can use pacman to obtian the additional parts you require. If you have a look at some of the other closed issues which also ask for extra's, you'll see dscho's similar response.

**Comment by APerson01** [comment]
Where can I find more information about pacman?

**Comment by dscho** [comment]
https://github.com/git-for-windows/git/wiki/Package-management
