### ISSUE TITLE
symbolic-ref and rev-parse cause perf issues for posh-git in large GVFS repos

### ISSUE THREAD

**Issue by dbjorge** [git-for-windows/git#1054]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

d:\>git --version --build-options
git version 2.11.0.gvfs.1.517.g5a09e71
built from commit: 5a09e71e329260e2932ff18aca5e59bed93c7a6d
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15010]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

# Defaults from GVFS installation instructions
d:\>type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
d:\>gvfs --version
GVFS 0.5.17024.1

d:\repos\posh-git>git log --oneline -n 1
2f92ba6 Merge pull request #403 from dahlbyk/quotepath
# This is current posh-git master as of writing.
# Same behavior repros on currently released posh-git (0.6.1.20160330).
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell (posh-git)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

*Note: my perf numbers/experience/repro steps are based on the Microsoft-internal OS repo, which AFAIK is the only existent repro case of its scale. I'm afraid I'm not sure how to best induce repro conditions for non-MSFT folks*

**Minimal git-only repro using slow commands**
```
D:\os\src> function time($script) { $sw = [Diagnostics.Stopwatch]::new(); $sw.Start(); & $script; $sw.Stop(); $sw }
D:\os\src> time { git symbolic-ref HEAD -q  }
refs/heads/redacted_branch_name

IsRunning Elapsed          ElapsedMilliseconds ElapsedTicks
--------- -------          ------------------- ------------
    False 00:00:01.1705539                1170     11705539
D:\os\src> time { git rev-parse --is-inside-git-dir  }
false

IsRunning Elapsed          ElapsedMilliseconds ElapsedTicks
--------- -------          ------------------- ------------
    False 00:00:00.6062610                 606      6062610
```

**End to end repro (assumes MSFT access to OS repo) showing user impact of slow commands**
```
cmd> powershell -NoProfile
PS D:\> git clone https://github.com/dahlbyk/posh-git.git
PS D:\> Import-Module -Force .\posh-git\src\posh-git.psd1
D:\> $GitPromptSettings.RepositoriesInWhichToDisableFileStatus = @('D:\os\src')
D:\> $GitPromptSettings.Debug = $true
D:\repos> cd d:\os\src
D:\os\src
VERBOSE: 00023:Finding branch
VERBOSE: 00038:Trying symbolic-ref
# Note: internally, this runs 'git symbolic-ref HEAD -q'
VERBOSE: 01237:Inside git directory?
# Note: internally, this runs 'git rev-parse --is-inside-git-dir'
VERBOSE: 01845:Building status object
VERBOSE: 01854:Finished
 [redacted_branch_name]>
```
 - What did you expect to occur after running these commands?

end-to-end-wise: Expected to be able to get a fast posh-git prompt after using `RepositoriesInWhichToDisableFileStatus` to disable its usual calls to `git status` (known to be slow in a repo of this scale).

git-command-wise: Expected `git symbolic-ref HEAD -q` and `git rev-parse --is-inside-git-dir` to require no particularly costly disk activity and to perform at <100ms each

 - What actually happened instead?

end-to-end-wise: Prompt still takes 1.8 seconds to render, which isn't really good enough for a $prompt function and forces me to disable posh-git. This time is dominated by the two git.exe calls in question.

git-command-wise:
`git symbolic-ref HEAD -q` takes 1.1-1.2s to execute in the os repo on my dev box
`git rev-parse --is-inside-git-dir` takes .6-.7s to execute in the os repo on my dev box

Prior discussion with @dscho suggests that these calls are probably not this slow by necessity ("It looks like all those calls read in way too much information, for little gain... :-("), but I have not verified this myself or done any performance profiling inside the git.exe invocations in question.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

The Microsoft-internal OS repo (see note above - apologies that I don't have a repro case for non-MSFT folks to use)

**Comment by sanoursa** [comment]
@dbjorge This is much more likely to be a GVFS issue than a Git for Windows issue. I'll chat with you offline about the best place to file these issues, but I vote to close this issue here.
