### ISSUE TITLE
Repository not found error with versions 2.11.0.2 -> 2.11.1 (64 bit)

### ISSUE THREAD

**Issue by terabyte-gc** [git-for-windows/git#1055]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.14393] 64 bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None, it is a pretty normal/standard setup.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash, SourceTree, PhpStorm

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Simple commands like Clone/Pull/Fetch.
```
 - What did you expect to occur after running these commands?

I was expecting it to clone/pull/fetch the git repo.

 - What actually happened instead?

remote: Not Found
fatal: repository 'https://repo.domain.com/path/' not found

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repo so I cannot provide it. It is an HTTPS url as mentioned just above it if makes any difference though.

 

Let me add also that going back to version 2.11.0 it starts working again just fine. I tested all 3 newer version after it (2.11.0.2, 2.11.0.3, 2.11.1) and I always get the above error with those.

**Comment by PhilipOakley** [comment]
Does your path to repo have non-ascii characters (umlauts, UTF-8, etc.)?

Also try https://github.com/git-for-windows/git/releases/tag/v2.11.1.windows-prerelease.2 (these latest pre-releases don't sort in the right order).

**Comment by terabyte-gc** [comment]
None, this is the full path I am using for the repo (I replaced the names in it but it is the same format):
`https://subdomain.codebasehq.com/repopath/reponame.git`

Could the issue be that .git at the end maybe?

I'll give that pre release version a try later, I'm in the middle of some work that requires git right now :)

**Comment by whoisj** [comment]
@terabyte-gc I recommend using the portable versions for validation, they can all live side-by-side and have no impact on your installed version of Git.

**Comment by terabyte-gc** [comment]
Good point, downloading the portable version right now.

**Comment by dscho** [comment]
In case that the portable version did not solve it, could you try with `git -c http.emptyauth=false fetch ...`?

**Comment by dscho** [comment]
> In case that the portable version did not solve it, could you try with git -c http.emptyauth=false fetch ...?

... and maybe tell us about your level of success? (Or close this ticket if there is no more problem?)

**Comment by terabyte-gc** [comment]
> ... and maybe tell us about your level of success? (Or close this ticket if there is no problem anymore?)

Sorry, I was away from home for a while and I wasn't able to test. However I have noticed a lot of other minor unrelated issues with my windows installation. I'm going to format soon to start fresh, We can close this ticket for now. If I still have the issue after I format I'll let you know.

**Comment by dscho** [comment]
Thank you for reporting back!
