### ISSUE TITLE
git clone "fatal: The remote end hung up unexpectedly"

### ISSUE THREAD

**Issue by jilili** [git-for-windows/git#1056]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\Users\jilili\Projects\test>git.exe clone --progress -v "https://gopkg.in/gographics/imagick.v2" "C:\Users\jilili\Projects\test\imagick.v2"
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

```
Cloning into 'C:\Users\jilili\Projects\test\imagick.v2'...
POST git-upload-pack (gzip 1251 to 645 bytes)
fatal: The remote end hung up unexpectedly
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://gopkg.in/gographics/imagick.v2

**Comment by shiftkey** [comment]
@jilili that URL is just the project site, and isn't a Git server. It does link to this Git repository, which should work for you: `https://github.com/gographics/imagick.git`
