### ISSUE TITLE
Fix jagged lines in `git remote -v`

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#106]
Output of `git remote -v` (and other Git subcommands) is all of a sudden jagged in `mintty`: instead of starting new lines at the left-most column, the lines start directly beneath the end of the previous line.

This seems to have been introduced with the latest merging rebase of the msys2-runtime to upstream.

**Comment by nalla** [comment]
I can confirm this. I think all of git's output is affected. `git branch` e.g. as well. `git log` seems to work. But I *think* because its directed to a pager.

**Comment by dscho** [comment]
Right, everything that gets redirected to the pager, and everything that is shown in the `cmd` still works. I am bisecting right now (already for two hours, this is really tedious).

**Comment by dscho** [comment]
This is fixed by the latest merging rebase of the msys2-runtime. Packages are building as we speak (will upload them tomorrow, as time permits). My guess is that the fix is the rather large commit git-for-windows/msys2-runtime@063e7da.

**Comment by dscho** [comment]
Uploaded!

**Comment by dscho** [comment]
Unfortunately, I had to revert the commit that fixed the jagged lines because it is the culprit for https://github.com/git-for-windows/git/issues/127.

**Comment by dscho** [comment]
So this is my current state: https://github.com/git-for-windows/msys2-runtime/compare/develop...debug-xp-git-bash-hang

With this, I get the following output when running by double-clicking `git-bash.exe` in the Windows Explorer:

```
creating pipe pty0-to-master.
created 0
start thread
succeeded
setting 1
set to_master to 0x6f4
close pty handles
to_master 0x6f4
duplicating cyg
to_master 0x6f4
verifying handle
setting output handle to 0x6b4
master fwd thread
pty master fwd thread
terminating master thread
force close io handle
force close cyg
getting output handle 0x6b4
set_handle_or_return
get_io_handle_cyg 0x6b8
<last two lines repeat over 6,000 times>
```

When running from a shortcut (created next to `git-bash.exe`) which points directly to `...\usr\bin\mintty.exe /usr/bin/bash --login -i`, the mintty window appears as expected and the output reads:

```
creating pipe pty0-to-master.
created 0
start thread
succeeded
setting 1
set to_master to 0x110
master fwd thread
pty master fwd thread
close pty handles
to_master 0x110
duplicating cyg
to_master 0x110
verifying handle
setting output handle to 0x160
fixup after fork 0 1220
force close cyg
getting output handle 0x160
force close io handle
set_handle_or_return
<last line repeats 12 times, after that it seems to work normally>
```

There are two things that immediately jump out:

- the master fwd thread is not started (i.e. [this function](https://github.com/git-for-windows/msys2-runtime/blob/388dfa8a07e4a39e88a9fc1a31660dab155f4817/winsup/cygwin/fhandler_tty.cc#L1673-L1700) seems never to be called, even if [the thread is started](https://github.com/git-for-windows/msys2-runtime/blob/388dfa8a07e4a39e88a9fc1a31660dab155f4817/winsup/cygwin/fhandler_tty.cc#L1818-L1826), and
- it makes sense that the shortcut already has a console handle (`0x110`) because it points to a console program (`mintty.exe` is compiled as a console program, I guess) but it makes less sense that starting from `Git Bash` would pass a console handle (`0x6f4`). This makes me believe that the *real* culprit might actually be that [we pass `stdin/stdout/stderr`](https://github.com/git-for-windows/git/blob/master/compat/win32/git-wrapper.c#L426-L438). It might make sense to detect when we are running as a GUI program and skip [that code](https://github.com/git-for-windows/git/blob/master/compat/win32/git-wrapper.c#L431-L438) in that case.

I'll be away from the keyboard until Monday, so if anybody else wants to look deeper into this issue, I would be glad for any help!

**Comment by dscho** [comment]
Re-fixed in https://github.com/git-for-windows/msys2-runtime/commit/069d2043921d4f90820de2f0fba22eac9e0edd4b
