### ISSUE TITLE
autocorrect message not printed until timeout has expired

### ISSUE THREAD

**Issue by GrahamClark** [git-for-windows/git#1062]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash or PowerShell (PoshGit) produce the same issue

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git kog
```
or
```
git statud
```
 - What did you expect to occur after running these commands?

Expected
```
WARNING: You called a Git command named 'kog', which does not exist.
Continuing under the assumption that you meant 'log'
in 2.0 seconds automatically...
```
to be printed, then after 2 seconds, the output of `git log` or `git status` (as appropriate) to be printed
 - What actually happened instead?

`git kog`:
The text
```
WARNING: You called a Git command named 'kog', which does not exist.
Continuing under the assumption that you meant 'log'
in 2.0 seconds automatically...
```
*and* the output of `git log` were all printed together after 2 seconds (the autocorrect message was printed before the `git log` output).

`git statud`:
After 2 seconds, the output of `git status` was printed, *followed by* the text
```
WARNING: You called a Git command named 'statud', which does not exist.
Continuing under the assumption that you meant 'status'
in 2.0 seconds automatically...
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

doesn't seem to be repository-specific

**Comment by GrahamClark** [comment]
This definitely worked "as expected" in a previous version (i.e. the autocorrect message was printed, then there was a 2-second pause, then the autocorrected git command was run), but unfortunately I'm not sure whether it worked in the previous version or several versions ago.

**Comment by PhilipOakley** [comment]
I think this has been noted upstream, (a threading/pipe issue if I recall). Don't have a link to it yet.

I _think_ the fix is here http://public-inbox.org/git/xmqq37fga9rn.fsf@gitster.mtv.corp.google.com/T/#mfe5e38031f2c6934c817bdbd8a12c5a98984b915 (i.e. ensuring that the message gets through early enough to the real tty)

**Comment by PhilipOakley** [comment]
I think this thread was the report I remember. http://public-inbox.org/git/8488f55c-37b1-1ded-53c5-7cd268210391@jeffhostetler.com/

**Comment by dscho** [comment]
@GrahamClark thanks for the report!

The issue had been reported elsewhere by @j6t: http://public-inbox.org/git/6bc02b0a-a463-1f0c-3fee-ba27dd2482e4@kdbg.org/

This is the mail with the fix: http://public-inbox.org/git/c88612da0a62bfcbc3e278296f9d3eb010057071.1487025228.git.johannes.schindelin@gmx.de/

And this is the commit that fixes it, in our `master` since Tuesday late in the evening: 87ad093f001e7146e5e521914255199e49c212a7
