### ISSUE TITLE
git cat-file --batch reports object is missing when there is trailing whitespace

### ISSUE THREAD

**Issue by wilbaker** [git-for-windows/git#1065]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

C:\Repos\git>git --version --build-options
git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 - 64 bit

```
$ cmd.exe /c ver

C:\Repos\git>cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

C:\Repos\git>type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\Repos>git clone https://github.com/git-for-windows/git
C:\Repos>cd git
C:\Repos\git>git rev-parse HEAD

[NOTE: In git cat-file --batch below, the SHA was copied from the output of git rev-parse HEAD.  The first time the SHA was pasted a trailing whitespace character was manually added after the SHA and git reported the object as missing]

C:\Repos\git>git cat-file --batch
87ad093f001e7146e5e521914255199e49c212a7
87ad093f001e7146e5e521914255199e49c212a7  missing
87ad093f001e7146e5e521914255199e49c212a7
87ad093f001e7146e5e521914255199e49c212a7 commit 832

```
 - What did you expect to occur after running these commands?

I expected git to return the object

 - What actually happened instead?

Git reported the object was missing (due to trailing whitespace character after SHA)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not repo specific.  I tested with https://github.com/git-for-windows/git repo

**Comment by shiftkey** [comment]
> [NOTE: In git cat-file --batch below, the SHA was copied from the output of git rev-parse HEAD.  The first time the SHA was pasted there was a trailing whitespace character and git reported the object as missing]

This step needs to be clearer, as I have a repro here in PowerShell that interacts with the clipboard and doesn't trigger the issue:

```
> git rev-parse HEAD | Set-Clipboard
> Get-Clipboard | git cat-file --batch
d09b6927978d70ca53126e80d0dc8a070cc06635 commit 236
tree d329145ec5e9376c132c1e0bdc7c5e755311f02a
parent 57f7345b50d3b546ad3f7f07306f1402a00c581b
author Junio C Hamano <gitster@pobox.com> 1487199505 -0800
committer Junio C Hamano <gitster@pobox.com> 1487199505 -0800

A bit more for -rc2
```

**Comment by wilbaker** [comment]
> This step needs to be clearer, as I have a repro here in PowerShell that interacts with the clipboard and doesn't trigger the issue

Thanks for the feedback,  I've updated the original post to make it clear that in these repro steps I manually added a whitespace character after copy/pasting the SHA in CMD.

In practice I've hit this issue when copy/pasting from other places (websites, emails, etc.).  Often when copy\pasting from these locations there will be a trailing whitespace that is inadvertently copied along with the SHA.

For the sake of a simple repro though, the whitespace character can be manually added be pressing spacebar after pasting.

**Comment by dscho** [comment]
@wilbaker thank you for reporting this issue.

Please keep in mind that the `--batch` mode was primarily introduced to support applications better that need to do bulk queries. As such, that mode is optimized for speed, specifically avoiding trimming the lines.

So I am afraid that Git works as designed here.

You may want to filter your pasted text before piping it to `cat-file`. This works here:

```cmd
git -c alias.a="!sh -c 'tr -d \\ | git cat-file --batch'" a
```

(You can paste the white-space-augmented SHA-1s and end with Ctrl+D as before, but this time it will work...)

This also shows you how you could define an alias if you need to do this more often.
