### ISSUE TITLE
Unable to run git commands on Windows 10 Powershell

### ISSUE THREAD

**Issue by sriksm19** [git-for-windows/git#1066]
hi

Whenever I enter any of the git commands (or simply "git")  in Windows 10 Powershell, i get the "Open with" dialogue box. Opening with notepad gives me a blank screen. Tried uninstalling git from my pc, removed all paths. Although the commands do not work in cmd, it still shows the same behaviour in Powershell. What to do?

P.S. the following details were derived from cmd.exe . I would like to use powershell as it has now become the default terminal for VSCode. I know i can change it to cmd but my colleagues do not get the same error. Just want to figure out what is causing this behaviour.

Thanks

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

none

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
anything with git . or simply git
```
 - What did you expect to occur after running these commands?

work normally

 - What actually happened instead?

Getting "Open With" dialogue box

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

generic

**Comment by dscho** [comment]
Does `get-command git` find the correct `.exe`?

**Comment by sriksm19** [comment]
thanks a lot! it was pointing to a C:\WINDOWS\system32\git (empty file with no extension) . deleted that file and now its pointing to the right path!
