### ISSUE TITLE
GfW ships with two different curl versions - intentional?

### ISSUE THREAD

**Issue by larsxschneider** [git-for-windows/git#1069]
I installed [Git for Windows 2.11.1 64-bit](https://github.com/git-for-windows/git/releases/download/v2.11.1.windows.1/Git-2.11.1-64-bit.exe) cleanly and realized that it ships with two slightly different `curl` versions (see output below). Is this intentional/known? I wasn't able to find a related ticket.

```
MINGW64 /
$ git --version
git version 2.11.1.windows.1

MINGW64 /
$ ./bin/curl.exe --version
curl 7.51.0 (x86_64-pc-msys) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.11 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink

MINGW64 /
$ ./mingw64/bin/curl.exe --version
curl 7.51.0 (x86_64-w64-mingw32) libcurl/7.51.0 OpenSSL/1.0.2k zlib/1.2.11 libssh2/1.8.0 nghttp2/1.19.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 Metalink

MINGW64 /
```

**Comment by dscho** [comment]
> ./bin/curl.exe --version

It's actually `/usr/bin/curl.exe`. The reason why this is shipped: it is part of the `curl` package, i.e. the equivalent of the MINGW cURL included in the `mingw-w64-curl` package.

The reason why the `curl` package's contents are included in the Git for Windows installer is simple: I assumed that it is used by Subversion (or at least by `git svn`) to connect via https. This appears not to be the case, though: `pactree -r curl` reports that only `git` (the MSYS2 version, which we exclude explicitly from the installer; it is dragged in as a dependency of `git-flow`), `pacman` and `pkgfile` are depending on that package.

And as the `curl` package is different from the `libcurl` package (that contains the library on which `gnupg` depends, hence it is required for Git for Windows), it seems that we can simply exclude the `curl` package from the list of packages whose contents are included in the installer.

**Comment by petteyg** [comment]
The mingw curl executable reliably hangs for any operation. I'd rather have just the msys2 version than just a broken version...

**Comment by larsxschneider** [comment]
@petteyg Can you tell us more about your setup to reproduce the issue? See [these questions](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md).
