### ISSUE TITLE
When installing Git for Windows 2.x on top of 1.x, make sure to clean up

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#107]
It is a bit unclear how this worked previously to this developer (who got the impression that reinstalling via the Inno installer would automatically delete previously installed files, but according to [this comment](https://github.com/git-for-windows/git/issues/84#issuecomment-91663642) that is wrong...)

So we need to make sure that 32-bit Git is removed when installing 64-bit Git.

We should also make sure to move the old config to `%PROGRAMDATA%\Git\config` (or on XP, `%ALLUSERSPROFILE%\Application Data\Git\config`) and to make our modifications there instead of `/mingw??/etc/gitconfig` (we should also make sure that we remove the respective keys from the latter location, probably already in `git-extra`).

**Comment by bviktor** [comment]
You may wanna have a look at the [HexChat installer](https://github.com/hexchat/hexchat/blob/master/win32/installer/hexchat.iss.tt#L328).

**Comment by dscho** [comment]
@bviktor I know you want to help, but [our InnoSetup script](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss.in) looks quite different, so it may not have been the best idea to send me to the HexChat installer. Please have a look at Git for Windows' InnoSetup script, compare for yourself how different it is from the HexChat installer, and then maybe try to figure out how to apply the lesson from HexChat's installer to Git for Windows'? I would be really glad to accept a Pull Request in that regard.
