### ISSUE TITLE
Rebase squashes commits on a rebase that should gpg sign them.

### ISSUE THREAD

**Issue by AraHaan** [git-for-windows/git#1072]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
There are a few bugs In that git I noticed when using mingw, mingw64,
cygwin, and cygwin64. These bugs are the following:

if I do ``git rebase -i --root`` and tell it to edit every commit to
``gpg sign`` all my commits it bugs out and squashes all of the commits into
1 commit instead of only appending the ``-S`` to each and every commit
and keeping all of the commits. It is as if I told it to squash the
commits but yet I did not. It is super annoying.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.11.0.windows.1
I am using git on mingw, mingw64, cygwin, and cygwin64.

```
$ git --version --build-options

git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 Ultimate SP1 Build 7601 x64
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Difftool: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I know of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rebase -i --root
git commit --amend '-S'
git rebase --continue
```
 - What did you expect to occur after running these commands?

The commits to not get discarded on the PR's I opened and for the commits in my Repo to not get squashed.

 - What actually happened instead?

if I do ``git rebase -i --root`` and tell it to edit every commit to
``gpg sign`` all my commits it bugs out and squashes all of the commits into
1 commit instead of only appending the ``-S`` to each and every commit
and keeping all of the commits. It is as if I told it to squash the
commits but yet I did not. It is super annoying.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

My Repo that I need to gpg sign the commits that git happily squashes instead of keeps them (does not happen on linux git): https://github.com/AraHaan/TinyURL

**Comment by dscho** [comment]
> if I do git rebase -i --root and tell it to edit every commit to
> gpg sign all my commits

How do you do that? By passing the `-S` option? Or by adding `edit` lines to the script?

**Comment by AraHaan** [comment]
the edit

**Comment by dscho** [comment]
> editing the lines that has every commit on vim

And how? Could you maybe specify a *precise* line after editing? I still have no clue what exactly you are doing there, and I doubt anybody else has an idea, either. However, understanding that is a prerequisite for helping you. Maybe you could be a little less terse in your replies and volunteer more information from the start?

**Comment by AraHaan** [comment]
```
edit 95c8297 :space_invader: Added .gitattributes
edit 709e6ac TinyURL for Python 3.x Test Repo for now.
edit dcf2d17 Test #2 on getting it able to pip install.
edit bc26dd4 Port 100% working now. Enjoy TinyURL in Python 3.x like it did in 2.x.
edit 3d1f8a4 Version bump and Some changes.
edit 84dafcf Version Bump and Added URL checker.
edit bd3eb87 Fixes and Version bump.
edit 0eae839 Version bump and tests for stuff (beta)
edit f321a1b v0.1.6
edit db10121 Changes to a few things for installing from pip.
edit 55da3fb Version bump to v0.1.7 and fixed not seeing the error classes.
edit a2a54d5 v0.1.8
edit 12c1d76 Update and rename README to README.md
edit 4c9f0bb Update README.md
edit f39d53c Update README.md
edit bccb8bb Update setup.py
edit 0ab801f Fixed setup.py
edit acdc844 Fixed some other things.
edit 58aef01 Fixed setup.py
edit f9b39a2 Reworded README.md

# Rebase f9b39a2 onto 5492a9a (20 commands)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
````
That is what I had in VIM and when I save and exit that then it would do all of the squashing for some reason.

**Comment by dscho** [comment]
> I have set it to automatically gpg sign all commits anyway

Please do not omit the information how you configured that.

> it would Error out on the rebase telling me to git commit --amend '-S' and then git rebase --continue.

This is not the precise error message. It reflects just the part where it says how you continue after resolving the issue. But the part of the error message that said what *actually went wrong* is missing.

My *guess* is that something went wrong before the changes were actually committed, and therefore the `--amend` in the suggestion was incorrect (and therefore you simply amended the root commit over and over and over again, which you probably noticed as the root commit's commit message should have shown up in your editor over and over and over again).

But without more precise information (like, copy-paste verbatim instead of describing what happened in English prose), it is hard to impossible to fix this issue.

**Comment by dscho** [comment]
> There is also another bug where if I clone
> a repo on Windows and not on github desktop and that I placed commits
> to the repo on github web and then when I rebase to squash the commits
> to 1 commit (some repos are doing it as a requirement for 1 commit
> PR's) that all of my commits on the remote (fork in this case) that is
> linked to an open pull request are discarded and then the pull request
> is somehow and oddly closed. It is super annoying.

First of all, open one ticket per issue.

Second, this description may make sense to others, but not to me. I need a very precise account of the bug, and preferably a distilled set of exact commands that will demonstrate the problem. This is what we call an MCVE (Minimal, Complete, Verifiable Example) over here, inspired by StackOverflow.

That requirement for a clear description of the bug is not a formality, nor is it designed to hassle bug reporters. Instead, this requirement tries to fend off real frustration that sets in when a bug is reported, nobody can make heads nor tails of the report, and despite everybody spending time and effort, the bug goes unfixed. So please improve your bug report.

**Comment by AraHaan** [comment]
I configured it using the clobal config steps for automatically gpg signing commits using:

    git config --global commit.gpgsign true

As explained at https://help.github.com/articles/signing-commits-using-gpg/

However it does say that it fails to apply the commit after doing ``git rebase --continue`` after I do ``git commit --amend '-S'`` and does squash it together (All of these Errors within git bash itself):

    gpg: cannot open tty `no tty': No such file or directory
    error: gpg failed to sign the data
    fatal: failed to write commit object
    Could not apply [commit hash]... [commit name]

After that when it gets all the way done with the rebase the HEAD on my local master branch would be exactly this one commit:

    $ git log
    commit c82a04f33cf1d79ff8a3bc140b6aaf6f96bf62b6
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Tue Apr 5 01:16:12 2016 -0500
    
        :space_invader: Added .gitattributes


However Origin/master is like this:

    $ git log origin/master
    commit 5a25bf39373e06e4d7f1aca68f332d01d12bfcaf
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Wed Mar 1 17:24:43 2017 -0600
    
        Version bump to 0.1.9.
    
    commit 21e0b6af19941d4b52a9d7f6d64bddf7b34206f1
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Wed Mar 1 17:23:01 2017 -0600
    
        Fixed space in regex.
    
        A wild space appeared in the regex.
    
    commit 92beaf76c9ca7dc0d8db0f372b6a0646e7de1e54
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Thu Feb 23 18:54:50 2017 -0600
    
        Update __init__.py

    commit f9b39a2b600be9bc63d248a9aebfb3203bd6c15d
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Thu Feb 23 03:35:33 2017 -0600
    
        Reworded README.md
    
    commit 58aef01ca677daead08f77fc660bb39a3f7330dc
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Thu Feb 23 03:23:52 2017 -0600
    
        Fixed setup.py
    
    commit acdc84475796e59cd80fd66994d50087c30c826d
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Thu Feb 23 02:58:24 2017 -0600
    
        Fixed some other things.
    
    commit 0ab801fcec1cfee97f631fe4a68f1aa7e2f8d1f2
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Wed Feb 22 22:36:52 2017 -0600
    
        Fixed setup.py
    
    commit 07329ba313223f91fa7ca37c3732d895b88c0ba2
    Merge: a2a54d5 bccb8bb
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Wed Feb 22 22:31:30 2017 -0600
    
        Updated things.
    
    commit bccb8bb53672599419fb9220dccbf859144937c2
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Wed Feb 22 22:05:32 2017 -0600
    
        Update setup.py
    
    commit f39d53ca8dd49337b516a86bfcb3c3b7e1e6619a
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sun Feb 19 22:39:11 2017 -0600
    
        Update README.md
    
    commit 4c9f0bb2f624ddcde65a5ca6ff99a3dcf2b49934
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sun Feb 19 22:32:19 2017 -0600
    
        Update README.md
    
    commit 12c1d76e7378c092fd067c04cff4be12fe10237b
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sun Feb 19 22:30:25 2017 -0600
    
        Update and rename README to README.md
    
    commit a2a54d5a1ab08b54432d255288d168ecd29dca46
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sat Dec 31 00:16:28 2016 -0600
    
        v0.1.8
    
    commit 55da3fbf60e01a60bb81050d847031a1ae544a10
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sat Nov 12 15:19:29 2016 -0600
    
        Version bump to v0.1.7 and fixed not seeing the error classes.
    
        The Errors that the create_one function throws was not visable to other
        modules that calls it. This version fixes that.

    commit db10121d13134a4dc5e3a8527e374cb208ddf55a
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sat Nov 12 11:17:44 2016 -0600

        Changes to a few things for installing from pip.

    commit f321a1be6ae3152b557a024a8714885aa97cd11e
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sat Nov 12 01:17:23 2016 -0600

        v0.1.6

    commit 0eae839aee3e6a4c3f69b0d0c0ec0fd39c430f50
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sun Sep 11 05:44:49 2016 -0500
    
        Version bump and tests for stuff (beta)
    
    commit bd3eb879374ccf6a3593450dd1f370d0195df0aa
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sun Sep 11 00:31:12 2016 -0500
    
        Fixes and Version bump.
    
    commit 84dafcf81432221965b284dbbe3685addfb88af3
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sat Sep 10 20:48:52 2016 -0500
    
        Version Bump and Added URL checker.
    
    commit 3d1f8a494ad6b43432c1030d37c018426e46be34
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Sat Sep 10 20:07:36 2016 -0500
    
        Version bump and Some changes.
    
    commit bc26dd4a10cfcebd8015a17ee6f7b5adc4887a96
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Tue Apr 5 16:46:22 2016 -0500
    
        Port 100% working now. Enjoy TinyURL in Python 3.x like it did in 2.x.
    
    commit dcf2d17d71764fb0e13e2db8a171e64f5fb2c967
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Tue Apr 5 02:40:31 2016 -0500
    
        Test #2 on getting it able to pip install.
    
    commit 709e6ac9d39b1fd8469af7127378ddc25aad0dfd
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Tue Apr 5 01:19:44 2016 -0500
    
        TinyURL for Python 3.x Test Repo for now.
    
    commit 95c82971a4f7601a19e364a74342e5ea8a512c23
    Author: AraHaan <seandhunt_7@yahoo.com>
    Date:   Tue Apr 5 01:16:12 2016 -0500
    
        :space_invader: Added .gitattributes

**Comment by AraHaan** [comment]
Ok, updated themain message to this issue.

**Comment by dscho** [comment]
> gpg: cannot open tty `no tty': No such file or directory

That is the real problem.

And then you get bitten by another bug (if I read your report correctly), in that `rebase -i` failed to commit but still suggests to `git commit --amend '-S'` instead of `git commit '-S'` (note the `--amend` option).

**Comment by dscho** [comment]
> > gpg: cannot open tty `no tty': No such file or directory
> 
> That is the real problem.

FWIW this problem was already reported here: https://github.com/git-for-windows/git/issues/918.

And I *think* that the other issue you reported in this here ticket (the incorrect suggestion to use `--amend`) may require a patch to `sequencer.c`. But from https://github.com/git-for-windows/git/blob/ce4c6ca554ca0cd0ece9de325e7e1272b8c2ad98/sequencer.c#L1791-L1802 it looks as if we *already* only suggest `--amend` when appropriate? I know that this link refers to the current `master`, not v2.11.0 (which is behind by a couple versions), but I do not see anything in the diff that would explain the behavior you described.

Hopefully some other developer competent in C can have a look, as I have to take care of two other tickets before I can take on more work.

**Comment by dscho** [comment]
Please test with https://github.com/git-for-windows/git/releases/v2.19.0-rc0.windows.2; it comes with a new major version of GPG that tries to do its own GUI.

**Comment by AraHaan** [comment]
oh, thanks can test.

**Comment by dscho** [comment]
@AraHaan you probably don't remember what the result of the test was?

**Comment by AraHaan** [comment]
I think it worked not sure. I have not seen this much on my new computer although have not been using gpg so ye that is also the case.
