### ISSUE TITLE
Error in git GUI when trying to stage files

### ISSUE THREAD

**Issue by redmanmale** [git-for-windows/git#1075]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Win 7 x64
```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Accidently stage files from empty Unstaged Changes panel via shortcut CTRL-T.

 - What did you expect to occur after running these commands?

Nothing. Because all files have already been staged.

 - What actually happened instead?

GUI error
```
can't read "file_lists(.vpane.lower.diff.body.t)": no such element in array
can't read "file_lists(.vpane.lower.diff.body.t)": no such element in array
    while executing
"llength $file_lists($w)"
    (procedure "toggle_or_diff" line 13)
    invoked from within
"toggle_or_diff toggle .vpane.lower.diff.body.t "
    (command bound to event)
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Reproducible on any repository.

Steps to reproduce:

*    git init
*    open GitGUI
*    focus diff panel
*    focus unstaged changes panel
*    ctrl-t - and you got error via MessageBox

It's not a duplicate of #1060, it'a different bug.

**Comment by dscho** [comment]
There have been a couple of recent changes in Git GUI, could you test again?

**Comment by redmanmale** [comment]
On latest version
```
$ git --version --build-options
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```
bug is still here.

![demo](https://cloud.githubusercontent.com/assets/6782721/26245135/70f6c60c-3c9b-11e7-90d6-6a0bfcbfb002.gif)

**Comment by violinyanev** [comment]
Confirmed - also have the bug for few weeks now... Using (currently latest) 2.13.0.windows.1

**Comment by dscho** [comment]
A fixed version should appear in https://wingit.blob.core.windows.net/files/index.html within the next hour or so. Please test.

**Comment by dscho** [comment]
The snapshot is now definitely available. Please test.

**Comment by redmanmale** [comment]
This bug is still there.

**Comment by redmanmale** [comment]
```
can't read "file_lists(.vpane.lower.diff.body.t)": no such element in array
can't read "file_lists(.vpane.lower.diff.body.t)": no such element in array
    while executing
"lindex $file_lists($w) [expr {$lno - 1}]"
    (procedure "toggle_or_diff" line 29)
    invoked from within
"toggle_or_diff toggle .vpane.lower.diff.body.t "
    (command bound to event)
```

**Comment by PhilipOakley** [comment]
Looks like a similar fix needed at L2535, which is line 29 of the procedure "toggle_or_diff"

https://github.com/git-for-windows/git/blob/7cf4526635128de05c7759b0cbb678dc3a4e68f2/git-gui/git-gui.sh#L2535

(or an update of $w from the previous fix)

Philip
  ----- Original Message -----

**Comment by dscho** [comment]
@redmanmale this 1) is a different error message, and 2) should be accompanied by a description what you did, to avoid completely unnecessary frustration on both of our sides.

@PhilipOakley I tried to fix it as you suggested, and pushed to `master` hoping that it will work.

**Comment by dscho** [comment]
Please test the newest snapshot at https://wingit.blob.core.windows.net/files/index.html

**Comment by redmanmale** [comment]
Fixed. I tested version at commit 8b4e64d605.

**Comment by dscho** [comment]
@redmanmale thanks!
