### ISSUE TITLE
git add error 

### ISSUE THREAD

**Issue by jianboy** [git-for-windows/git#1079]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

**
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** win1064bit**
```

**the error alert is:**
libgit2 returned: 'bootstrap-edit/CNAME' appears as both a file and a directory.
and
fatal: Pathspec 'bootstrap-edit' is in submodule 'bootstrap-edit'

my project want to add a new folder and some files, this is a normal action,but I can not add them.
you can see the error:
![baiduhi_2017-3-3_0-3-12](https://cloud.githubusercontent.com/assets/11532015/23516734/10333d16-ffa9-11e6-9329-77c91b102c75.png)

**then ,I use the TortoiseGit tool,I also can not add them！**

![baiduhi_2017-3-3_0-8-28](https://cloud.githubusercontent.com/assets/11532015/23516806/375b334e-ffa9-11e6-8bf7-f879ba86958e.png)

**Comment by jianboy** [comment]
the folder and the sub files not same name !!!
you can see my operation from the video!
[http://tools.yoqi.me/Video_2017-03-02_234321.wmv](url)

**Comment by jianboy** [comment]
and my operation   system is win10 64bit. not Linux/Unix

**Comment by PhilipOakley** [comment]
Hi @jianboy 
The linux comment was that Git is designed to work first on Linux, hence it would automatically detect such duplicate D/F names (which are possible on Windows), but are forbidden with the git repository.

I had a look at the videoand the first error is that you were trying to add a file which is actually within a sub-module of the repo you are currently in. You need to be inside the submodule when you want to add the file that belongs inside it.

**Comment by jianboy** [comment]
oh.it is a simple git project.there don't have a submodule repo.I may know the error.
the .git folder and some files in it  may broken.

![baiduhi_2017-3-3_13-31-53](https://cloud.githubusercontent.com/assets/11532015/23539367/cc8841c0-0015-11e7-8809-65bb6573125f.png)

thank you!!
