### ISSUE TITLE
git capital error

### ISSUE THREAD

**Issue by jianboy** [git-for-windows/git#1080]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

**
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** win1064bit**
```
**the error :**
I add  the file Food**S**toreModel.class.php .but I rename it as Food**s**toreModel.class.php

then I commit and push it to server. but when I pull it ,I find it is Food**S**toreModel.class.php.

so,The file is lowercase on my PC1,but the file is capital letter on my PC2. this is a little bug,I can solve it manually.
**but other bug is that I can not add file

**Comment by nalla** [comment]
You need to use `git mv path/file path/File`.

**Comment by jianboy** [comment]
thank you,I will try it!
