### ISSUE TITLE
Some Portable Git for Windows binaries are different

### ISSUE THREAD

**Issue by davidmatson** [git-for-windows/git#1081]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
Somewhat related to #99, but not the same.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

Non-Portable:
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64

Portable:
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

(Omitting questions not related to this issue, which is more about build & documentation.)

([Related StackOverflow question](http://stackoverflow.com/questions/42562871/is-the-portable-version-of-git-for-windows-feature-equivalent).)

Is Portable Git for Windows intended to offer any different runtime behavior than normal Git for Windows Setup? (From looking at build-extra/portable, I suspect the answer is no.) When I run the latest installers and compare the program binaries they contain, some are different. Is there any intended difference in runtime behavior, for example, in how configuration data is read, in the Portable version? (Are its binaries compiled any differently?)

Specifically, the following files aren't byte-for-byte identical:
* git-bash.exe
* mingw64\bin\git-receive-pack.exe
* mingw64\bin\git-upload-archive.exe
* mingw64\etc\gitconfig mingw64\libexec\git-core\git*.exe

And there are a few interesting files not included at all (dev\stdin|out|err).

Is a difference between Portable and non-Portable binaries intended?

Thanks,

David

**Comment by davidmatson** [comment]
Or maybe these:
* mingw64\etc\gitconfig mingw64\libexec\git-core\git*.exe
Are only seen as different because of the hard links (the hard links are different but not the binaries themselves?) Is that all that's going on here?

Not sure about dev\stdin|out|err though.

**Comment by davidmatson** [comment]
No, I don't think it's just hard links. In a hex diff tool, git-bash.exe is actually different - perhaps some extra cert stuff is in the binary at the end?

**Comment by dscho** [comment]
I gave this a whirl. First, the results for v2.12.2 (after unpacking with `innounp` and `7za` respectively, *not* giving the `post-install.bat` script a chance to run):

```sh
$ sha256sum.exe */git-bash.exe
904953a202b32c4e8a4f36e24a5e5872c7b73f9a032fd577f39e505018b74008 *portable/git-bash.exe
904953a202b32c4e8a4f36e24a5e5872c7b73f9a032fd577f39e505018b74008 *{app}/git-bash.exe

$ sha256sum.exe */mingw64/bin/git-receive-pack.exe
fa671825ced00843d5468775156a71ae9cbd15bb7a23c00a2373859040a98361 *portable/mingw64/bin/git-receive-pack.exe
fa671825ced00843d5468775156a71ae9cbd15bb7a23c00a2373859040a98361 *{app}/mingw64/bin/git-receive-pack.exe

$ sha256sum.exe */mingw64/bin/git-upload-pack.exe
b8e077f99ca8d9f55567a7b3776bb374de15c623416bb8f8134c8a6edaf216a4 *portable/mingw64/bin/git-upload-pack.exe
b8e077f99ca8d9f55567a7b3776bb374de15c623416bb8f8134c8a6edaf216a4 *{app}/mingw64/bin/git-upload-pack.exe
```

After this quick test, I did not bother with the libexec files.

Now for v2.12.0:

```
97bf6ad4d19e53f2b229d8ed6d57ecb3b1538d3526682fab1bf26fcd1c793021 *portable/git-bash.exe
97bf6ad4d19e53f2b229d8ed6d57ecb3b1538d3526682fab1bf26fcd1c793021 *{app}/git-bash.exe
24375698a8396474f7c7d9f9aa2d30c3c5cc2b10ab11a5230be06b36c3309ac3 *portable/mingw64/bin/git-receive-pack.exe
24375698a8396474f7c7d9f9aa2d30c3c5cc2b10ab11a5230be06b36c3309ac3 *{app}/mingw64/bin/git-receive-pack.exe
a8f140f95fa5112977e453fac5b6e9634724272e0ee413ae08a93d92bb480114 *portable/mingw64/bin/git-upload-pack.exe
a8f140f95fa5112977e453fac5b6e9634724272e0ee413ae08a93d92bb480114 *{app}/mingw64/bin/git-upload-pack.exe
```

For the record, these are the SHA-256s of the archives/installers I unpacked:

```
0224c1cf4ff48535fdfc2555175be9a06c6d8b67fbf208b1c524f01252f8b13b *Git-2.12.0-64-bit.exe
99492acd85bad097b5952ccfd5cb37658bf3301f5d8256f345dd10937ab07899 *Git-2.12.2-64-bit.exe
5bebd0ee21e5cf3976bc71826a28b2663c7a0c9b5c98f4ab46ff03c3c0d3556f *PortableGit-2.12.0-64-bit.7z.exe
6a366a5b5702d24b401aba6b022d502b5f6597e00654075e491319878ba0a535 *PortableGit-2.12.2-64-bit.7z.exe
```

It seems that your claims are a teeny tiny bit bogus... :smile:

**Comment by davidmatson** [comment]
I confirmed that I have the same installers:
```
PS C:\Users\Me> & 'C:\Program Files\Git\usr\bin\sha256sum.exe' .\Downloads\PortableGit-2.12.0-64-bit.7z.exe
\5bebd0ee21e5cf3976bc71826a28b2663c7a0c9b5c98f4ab46ff03c3c0d3556f *.\\Downloads\\PortableGit-2.12.0-64-bit.7z.exe
PS C:\Users\Me> & 'C:\Program Files\Git\usr\bin\sha256sum.exe' .\Downloads\Git-2.12.0-64-bit.exe
\0224c1cf4ff48535fdfc2555175be9a06c6d8b67fbf208b1c524f01252f8b13b *.\\Downloads\\Git-2.12.0-64-bit.exe
```

And the Installer-extracted hashes are still different:
```
PS C:\Users\Me> & 'C:\Program Files\Git\usr\bin\sha256sum.exe' 'C:\Program Files\Git\git-bash.exe'
\940367f1b5970f8c70b7954968ea15e0dc7e2114eb66500e19d0889b42c8fa1f *C:\\Program Files\\Git\\git-bash.exe
PS C:\Users\Me> & 'C:\Program Files\Git\usr\bin\sha256sum.exe' .\Downloads\PortableGit\git-bash.exe
\97bf6ad4d19e53f2b229d8ed6d57ecb3b1538d3526682fab1bf26fcd1c793021 *.\\Downloads\\PortableGit\\git-bash.exe
```

When I use innounp rather than the exe itself to extract, the files are the same:
```
$ sha256sum.exe C:/Users/Me/Downloads/Git/{app}/git-bash.exe
97bf6ad4d19e53f2b229d8ed6d57ecb3b1538d3526682fab1bf26fcd1c793021 *C:/Users/dmatson/Me/Git/{app}/git-bash.exe
```

So it looks like the Installer is modifying some of the binaries somehow. From a quick look at file properties in Windows explorer, it looks like InnoSetup is removing the digital signature on the file. Is that a big in Git for Windows or in InnoSetup itself? At least some of the other binaries, for example \bin\git.exe, do not have the digital signature removed.

(There's still also the question about dev\stdin|out|error.)

**Comment by davidmatson** [comment]
It's not just the digital signature also that explains the discrepancy though. For example, looking at mingw64\bin\git-receive-pack.exe, both versions show the digital signature, so the contents must be different is some other way:
```
$ sha256sum.exe C:/Users/Me/Downloads/PortableGit/mingw64/bin/git-receive-pack.exe
24375698a8396474f7c7d9f9aa2d30c3c5cc2b10ab11a5230be06b36c3309ac3 *C:/Users/Me/Downloads/PortableGit/mingw64/bin/git-receive-pack.exe

$ sha256sum.exe C:/Users/Me/Downloads/Git/{app}/mingw64/bin/git-receive-pack.exe
24375698a8396474f7c7d9f9aa2d30c3c5cc2b10ab11a5230be06b36c3309ac3 *C:/Users/Me/Downloads/Git/{app}/mingw64/bin/git-receive-pack.exe

$ sha256sum.exe "C:/Program Files/Git/mingw64/bin/git-receive-pack.exe"
8c00944bc33136a650e98f314f26e611533fec800b816f7074f67a6a94d2810f *C:/Program Files/Git/mingw64/bin/git-receive-pack.exe
```

Is there some kind of general file corruption going on (perhaps a bug copying the last or oddly sized chunks in the InnoSetup exe or something like that)?

**Comment by dscho** [comment]
> Would you expect the windows Installer to do anything that modifies the git-bash.exe binary during install? (I'll try later getting the files out of the installer without running it, as you mentioned.)

Yes. You selected:

> Bash Terminal Option: ConHost

The default is MinTTY. And switching to ConHost is accomplished by editing the resources of `git-bash.exe`. Which naturally strips the digital signature, as it can no longer match.

But you reported discrepancies for other `.exe` files, which are not edited in the same way as `git-bash.exe`. i could not find anything wrong with the other `.exe` files.

> Any thoughts on why dev\stdin|out|err aren't included in the portable version?

Yes. They are special files, created in a way that 7-Zip cannot recreate. Hence they have to be re-generated upon the first Bash run.

**Comment by davidmatson** [comment]
Thanks; that explains git-bash.exe and dev\stdin|out|errr.

I tried re-installing using MinTTY. The differences now are:
* mingw64\bin\git-receive-pack.exe
* mingw64\bin\git-upload-archive.exe
* mingw64\libexec\git-core\git-*.exe

Here are a few of the hash differences:
```
24375698a8396474f7c7d9f9aa2d30c3c5cc2b10ab11a5230be06b36c3309ac3 *C:/Users/Me/Downloads/Git/{app}/mingw64/bin/git-receive-pack.exe
8c00944bc33136a650e98f314f26e611533fec800b816f7074f67a6a94d2810f *C:/Program Files/Git/mingw64/bin/git-receive-pack.exe
```

```
24375698a8396474f7c7d9f9aa2d30c3c5cc2b10ab11a5230be06b36c3309ac3 *C:/Users/Me/Downloads/Git/{app}/mingw64/bin/git-upload-archive.exe
8c00944bc33136a650e98f314f26e611533fec800b816f7074f67a6a94d2810f *C:/Program Files/Git/mingw64/bin/git-upload-archive.exe
```

```
24375698a8396474f7c7d9f9aa2d30c3c5cc2b10ab11a5230be06b36c3309ac3 *C:/Users/Me/Downloads/Git/{app}/mingw64/libexec/git-core/git-add.exe
8c00944bc33136a650e98f314f26e611533fec800b816f7074f67a6a94d2810f *C:/Program Files/Git/mingw64/libexec/git-core/git-add.exe
```

(and so on for other libexec binaries)

Do you see the same differences in these binaries? Are such difference expected?

Thanks,

David

**Comment by dscho** [comment]
> Do you see the same differences in these binaries?

As I mentioned earlier, I do not see those differences in the bundled files. There is probably a `rebase.exe` step going on in the 64-bit case. You can easily find out yourself by unpacking with 7Zip and then executing [the post-install script](https://github.com/git-for-windows/build-extra/blob/master/post-install.bat)'s statements manually, inspecting the checksums after each step.

**Comment by dscho** [comment]
Ah, I got fooled into believing that you still compared portable Git to Git for Windows, rather than the unpacked `{app}` to the installed Git for Windows.

And there is indeed a step that adjusts those `.exe` files in the installer, and I had completely forgotten about it. The `.dll` import addresses are [bound via `BindImageEx()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679279(v=vs.85).aspx), for better performance: https://github.com/git-for-windows/build-extra/blob/78f9f567e06b198ed35a19130c9244b52f4eb780/installer/install.iss#L1745-L1765.

At this point, though, I feel quite a bit DOSed (I really have to get back to bug fixing) and will have to ask you to do the rest of the digging yourself, if there is any left.

**Comment by davidmatson** [comment]
Thanks. It sounds like, other than the MinTTY/ConHost bit, that all the functionality is the same and the binary deltas are just performance- and installation-related details that wouldn't affect runtime behavior in any way. (So there isn't any functional delta to document, which was my main question.)

Thanks for all your help!
