### ISSUE TITLE
M4 not included anymore in basic install?

### ISSUE THREAD

**Issue by Dennis429** [git-for-windows/git#1089]
My team makes use of the M4 compiler that was available in the 1.9.x version of Git on windows.  After installing the new 2.x versions, M4 appears to no longer be included.  Is this something we can get added back into the basic installation of Git for Windows?

 - [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (MINGW64)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
m4 --version

```
 - What did you expect to occur after running these commands?

Something like I had in the older 1.9.x versions:

Welcome to Git (version 1.9.4-preview20140611)

$ m4 --version
m4 (GNU M4) 1.4.13
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.

 - What actually happened instead?

bash: m4: command not found

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not repository specific.

**Comment by shiftkey** [comment]
The Git for Windows 2.x releases were an opportunity to simplify the GfW environment to just what Git needs to work well on Windows. I'll defer to @dscho's comment [here](https://github.com/git-for-windows/build-extra/pull/131#issuecomment-281183361) about a similar request:

> We have enough maintenance burden in this project supporting Git already, it would do Git for Windows users a disservice to spread the available resources even thinner by trying to support anything else in addition...
