### ISSUE TITLE
A way to specify charset for "git add --patch"?

### ISSUE THREAD

**Issue by Maximus5** [git-for-windows/git#109]
I have many sources in ANSI (1251 codepage). When I try to run `git add -p` all national characters are displayed as bars `|`.

Previous git distro 1.9.x has almost similar problem but I was able to bypass it using a hack implemented by ConEmu, because perl was using codepage 1252 to output these characters

http://conemu.github.io/en/ConEmuEnvironment.html#ConEmuCpCvt

Is there a way to deal with ANSI files in Git 2.x?

**Comment by dscho** [comment]
Could you please come up with [a Minimal, Complete and Verifiable Example](http://stackoverflow.com/help/mcve) that is likely to work here?

**Comment by Maximus5** [comment]
Sure

    git clone git@github.com:Maximus5/git-bug-2.git
    cd git-bug-2
    git reset head~1
    -- modify .git/config as below
    git add -p

I have following in my .git/config. But seems like it have no effect in this case.

    [i18n]
    logOutputEncoding = cp866
    commitEncoding = cp1251
    [gui]
    encoding = cp1251

Both 1.9 and 2.0 versions failed but 1.9 can be fixed issuing the following command, but 2.0 can not.

    set ConEmuCpCvt=perl.exe:1252:1251

![2015-05-06_12-01-53](https://cloud.githubusercontent.com/assets/1222388/7490317/dbd3e88c-f3e7-11e4-8239-ad539f00e5bb.png)

**Comment by kblees** [comment]
```
[i18n]
logOutputEncoding = cp866
commitEncoding = cp1251
```

With these settings, its impossible to specify non-ASCII commit messages on the command line (`git commit -m "my cömmit messäge"`). Please stick to UTF-8, as described [here](https://github.com/msysgit/msysgit/wiki/Git-for-Windows-Unicode-Support). Additionally, these settings only affect the commit message, not the encoding of content files.

**Comment by Maximus5** [comment]
I know. But as I said, these settings seems like have no effect at the issue.

**Comment by kblees** [comment]
Have you tried `git-gui` and `gitk`? These should honor the `gui.encoding` setting (and also the per file `encoding` option in .gitattributes, if you enable it).

**Comment by Maximus5** [comment]
Have not tried, but I don't like git gui.

**Comment by kblees** [comment]
The command line tools typically print file content as is, sorry. For `git diff` and friends, you could work around this by using custom diff settings. This doesn't seem to affect `git add -p`, though.

E.g. in .git/config:
```
[diff "cyrillic"]
	textconv = iconv -f cp1251 -t utf-8
```
and in .gitattributes:
```
*.txt diff=cyrillic
```

I'm closing this as its not Windows-specific.
