### ISSUE TITLE
Source for sort.exe

### ISSUE THREAD

**Issue by greenbergjosh** [git-for-windows/git#1091]
I apologize for asking what I imagine is obvious. I would like to read the source for sort.exe.  I thought I might find a file called sort.c. Other UNIX core tools implementations on windows have a sort.c. I could not find it, nor could I find a make target of sort.exe. I have not coded C in 15 years. Your kind assistance in helping to set me in the right direction is greatly appreciated.  Thank you.

**Comment by cpackham** [comment]
Git for Windows ships with a number of ports of UNIX tools like sort, sed etc provided by the MSYS2/MinGW project (someone might correct me on the technical details).

If your interested in sort.exe in particular that's from the coreutils package https://github.com/git-for-windows/MSYS2-packages/tree/master/coreutils which is actually the gnu coreutils package with a few local patches to get things compiling under windows. 

None of those patches appear to touch "sort" in particular so the actual source is over at http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/sort.c

**Comment by greenbergjosh** [comment]
Thank you so much for your answer. That is a huge jumpstart for me. Have a great day.
