### ISSUE TITLE
git flow update to 1.10.2

### ISSUE THREAD

**Issue by vielhuber** [git-for-windows/git#1092]
According to this issue, I need to update git flow to 1.10.2:
https://github.com/petervanderdoes/gitflow-avh/issues/290

In the current version 2.12.0 of "git-for-windows" there is 1.10.1 of git flow included.
Can you please include the current version in the next release?

**Comment by shiftkey** [comment]
@vielhuber the source for this package is here https://github.com/git-for-windows/MSYS2-packages/blob/master/git-flow/PKGBUILD

I suspect a simple PR to update the `pkgver` to the right tag is all you need to do here. There's CI setup to test that everything is packaged fine...

**Comment by vielhuber** [comment]
@shiftkey thanks for your information.
Is this correct? https://github.com/git-for-windows/MSYS2-packages/pull/20
If the maintainer of MSYS2-packages now includes my pull, what happens next?

**Comment by shiftkey** [comment]
@vielhuber once it's merged, the release process for Git for Windows includes `git-flow` along with some other core packages [here](https://github.com/git-for-windows/build-extra/blob/425b0fdbfd5ec1adc73cf53889765c0cd0a4ed81/make-file-list.sh#L42-L50) when it creates it's installers.

There's another step in the middle around publishing the new package to bintray, but I'm pretty sure that's mostly automated.

**Comment by dscho** [comment]
@shiftkey almost. I had to create the package on BinTray first, and since that is a rare task, I do not have automated it (https://xkcd.com/1205/).

Unfortunately, I just realized that the `PKGBUILD` needs some love: it tracks the `master` branch instead of going for tagged revisions.
