### ISSUE TITLE
Trouble finding core.excludesfile path that works for both cmd.exe and bash.exe

### ISSUE THREAD

**Issue by mcandre** [git-for-windows/git#1096]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

From cmd.exe:

```console
C:\>git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```

From WLS bash.exe:

```console
$ git --version --build-options
git version 1.9.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
C:\>cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd.exe and WLS bash, though I also use PowerShell sometimes.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

`git status`, fool.

 - What did you expect to occur after running these commands?

`git status` would interpret the `core.excludesfile` path, such as `~/.gitignore`, in a way that intuitively, successfully evaluates, no matter whether git was executed from Command Prompt or WLS bash.

 - What actually happened instead?

`core.execludesfile` seems to strictly support Unix (`/`...) paths in WLS bash, and wholly Windows (`<drive>:\`...) paths in Windows.

I tried absolute paths (`C:\`..., `/`..., `/mnt/`...) and relative paths (`~/`..., `$HOME/`..., `%USERPROFILE%\`.... `$USERPROFILE/`...), no dice.

If git for WLS, via `trusty-security` Ubuntu repo, supported Windows backslashed paths, then `core.excludesfile` could be set to something like `C:\`... .

More likely, git for Windows should integrate with WLS bash by supporting Unix forward-slashed paths like `/mnt/c/Users/andrew/.gitignore` as a fallback.

**Comment by shiftkey** [comment]
@mcandre I think there's some confusion here, as Git CMD (and Git for Windows) will work fine with `~` and forward slashes in it's shell. Note the `FOO.txt` file which exists in that folder but is being hidden to Git.

```
C:\Users\shiftkey\src\some-test-directory>git config core.excludesfile
~/.gitignore

C:\Users\shiftkey\src\some-test-directory>type C:\Users\shiftkey\.gitignore
*.txt

C:\Users\shiftkey\src\some-test-directory>git status
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)

C:\Users\shiftkey\src\some-test-directory>dir
 Volume in drive C has no label.
 Volume Serial Number is 02FA-42C2

 Directory of C:\Users\shiftkey\src\some-test-directory

20/03/17  05:17 pm    <DIR>          .
20/03/17  05:17 pm    <DIR>          ..
20/03/17  05:17 pm                 0 FOO.txt
               1 File(s)              0 bytes
               2 Dir(s)  103,522,029,568 bytes free

C:\Users\shiftkey\src\some-test-directory>
```

Git for Windows also ships with it's own Bash shell.

> `git status` would interpret the `core.excludesfile` path, such as `~/.gitignore`, in a way that intuitively, successfully evaluates, no matter whether git was executed from Command Prompt or WLS bash.

Given Windows Subsystem for Linux will write your `~` directory to `%LOCALAPPDATA%\lxss\home\{user}`, instead of `%USERPROFILE%` which is what Git for Windows uses for it's Git CMD and Git Bash shells, I'm not sure how you're getting a shared global Git config and need to deal with this issue. Please be explicit with what configuration values you think should work.

PS: I updated my version of Git in Bash on Ubuntu on Windows to 2.11 - I recommend you do the same.

```
$ sudo add-apt-repository ppa:git-core/ppa
$ sudo apt-get update
$ sudo apt-get upgrade
```

**Comment by dscho** [comment]
> core.execludesfile seems to strictly support Unix (/...) paths in WLS bash, and wholly Windows (<drive>:\...) paths in Windows.

Correct (except for the spelling of `excludesfile`).

> git status would interpret the core.excludesfile path, such as ~/.gitignore, in a way that intuitively, successfully evaluates, no matter whether git was executed from Command Prompt or WLS bash.

That is also correct, with one crucial addition: `~/` refers to the home directory *which is different between CMD and WSL*. The home directory in CMD is typically what your `%USERPROFILE%` says. The home directory in the Linux subsystem lives inside the Linux pseudo root.

The reason why there are different home directories is obvious, too: as you correctly discovered, the way paths are specified is incompatible between CMD and WSL.

Conclusion: there is obviously no way you can make the same `core.excludesfile` setting work for both CMD and WSL. You need to specify the differently.
