### ISSUE TITLE
default git push to git pull instead of git merge when it finds that someone else pushed just before you did.

### ISSUE THREAD

**Issue by AraHaan** [git-for-windows/git#1097]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 Ultimate x64 SP1 Build 7601. All windows updates installed.

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Difftool: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I am aware of other than forced gpg signing on new commits on here even if I do not specify ``-S``.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
```
 - What did you expect to occur after running these commands?

git push to push the changesets without forcing an annoying merge commit on me right before actually pushing. (simulate doing an ``git pull`` instead.

 - What actually happened instead?

instead of pushing it opens up Vim and wants to force me to create an merge commit before letting me push the changes even with force push.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

it happens with every single github repository. Not just mine. It is annoying to have merge commits not from pull requests only and clutters git repositories with useless commits that do absolutely no change but merges.

**Comment by AraHaan** [comment]
Or another option is to default git merge with ``-no-ff`` to not create additional commits.

**Comment by dscho** [comment]
> git push to push the changesets without forcing an annoying merge commit on me right before actually pushing. (simulate doing an git pull instead.

There are other ways, you could also rebase.

> instead of pushing it opens up Vim and wants to force me to create an merge commit before letting me push the changes even with force push.

You probably have a custom hook installed: this is *not* the default behavior of Git. By default, Git would error out if you tried push non-fast-forwarding history.

Meaning that this question most likely has not been answered fully yet:

> Any other interesting things about your environment that might be related
> to the issue you're seeing?
