### ISSUE TITLE
Clearly state Git for Windows' governance model

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#110]
We really need to have a clear statement how this project is run. So let http://oss-watch.ac.uk/resources/governancemodels inspire a document to be put onto the https://git-for-windows.github.io/ website (not on the wiki because that would be too hard to protect against unwanted changes).

**Comment by dscho** [comment]
Moved to https://github.com/git-for-windows/git-for-windows.github.io/pull/2

**Comment by elyscape** [comment]
It might be worth noting in the document who the benevolent dictator is.

**Comment by dscho** [comment]
@elyscape sure. It's me.

**Comment by elyscape** [comment]
I'm not sure how you'd like to phrase it (e.g. your name? your handle?), otherwise I'd submit a PR to the website repo.

**Comment by dscho** [comment]
@elyscape I [took care of it](https://github.com/git-for-windows/git-for-windows.github.io/commit/d2f2d1522f84811da44729e4c83c7cec31dc9231). Thanks for the suggestion.
