### ISSUE TITLE
git merge --no-commit option doesn't work

### ISSUE THREAD

**Issue by techcap** [git-for-windows/git#1102]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
2.12.1.windows.1 64bit
```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.12.1.windows.1
built from commit: 2c6cf4e358dd1395091e1d7f9544028e6df674a7
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

nothing special

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git merge --no-commit origin/workingBranch
```
 - What did you expect to occur after running these commands?

merge but no commit.

 - What actually happened instead?

commited

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/techcap/nf-interpreter
I tried to merge from MergeTest to master.
After checking out master, I run below command.
> git merge --no-commit origin/MergeTest
```
C:\work\nf-interpreter-techcap>git branch
  MergeTest
  TemplateModification
  UpdateBuildInstruction
* master

C:\work\nf-interpreter-techcap>git merge --no-commit origin/MergeTest
Updating 197ad33..028f9f5
Fast-forward
 mergeTest.txt | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 mergeTest.txt

C:\work\nf-interpreter-techcap>git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
```

**Comment by kgybels** [comment]
Your merge resolved as a fast-forward. You can disable this with `--no-ff`.

Try the following:

    git merge --no-commit --no-ff origin/MergeTest

**Comment by mfriedrich74** [comment]
The manual indicates the fast forward would also not be performed.

"With --no-commit perform the merge but pretend the merge failed and do not autocommit, to give the user a chance to inspect and further tweak the merge result before committing."

**Comment by techcap** [comment]
@kgybels it works. It could be a workaround. Thanks.

It worked at old version without --no-ff. I agree @mfriedrich74

**Comment by dscho** [comment]
Please take this to [the Git mailing list](mailto:git@vger.kernel.org), as it is a general Git problem (not limited to Windows), and they have a lot more contributors available to help than Git for Windows.
