### ISSUE TITLE
git rev-parse --short return a sha1 of length 8 instead of 7 by default

### ISSUE THREAD

**Issue by MeTaNoV** [git-for-windows/git#1103]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope...

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

The problem can be reproduced using PowerShell and Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rev-parse --short HEAD
```
 - What did you expect to occur after running these commands?

I expect a sha1 value of length 7 which seems to be the default value [cf. Git Doc](https://git-scm.com/docs/git-rev-parse#git-rev-parse---shortnumber)

 - What actually happened instead?

It returns a sha1 value of length 8...

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Internal project, I suppose this could be reproduce on any project...

**Comment by MeTaNoV** [comment]
FYI @naure

**Comment by kgybels** [comment]
The documentation for `rev-parse --short` is not up to date. The correct information can be found under the documentation for [config.abbrev](https://git-scm.com/docs/git-config#git-config-coreabbrev):

>Set the length object names are abbreviated to. If unspecified or set to "auto", an appropriate value is computed based on the approximate number of packed objects in your repository, which hopefully is enough for abbreviated object names to stay unique for some time.

So the default is no longer 7, but a value based on the number of packed objects. Also note that `rev-parse --short` will always return a SHA-1 value that is unambiguous, so it might be longer than what you request as minimum length.

**Comment by MeTaNoV** [comment]
@kgybels thx for the quick reply, is there already some PR for the update of the documentation somewhere?

**Comment by kgybels** [comment]
@MeTaNoV Not that I'm aware of.

**Comment by shiftkey** [comment]
I suspect this is an [upstream](https://github.com/git/git/blob/master/Documentation/git-rev-parse.txt#L139-L143) issue, but I'll let @dscho confirm it.

```
--short::
--short=number::
	Instead of outputting the full SHA-1 values of object names try to
	abbreviate them to a shorter unique name. When no length is specified
	7 is used. The minimum length is 4.
```

**Comment by dscho** [comment]
> I suspect this is an upstream issue

Correct. Please report it [to the Git mailing list](mailto:git@vger.kernel.org), or even better: provide a patch.
