### ISSUE TITLE
Git failed to build on x86 due to error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'. 

### ISSUE THREAD

**Issue by KarenHuang2016** [git-for-windows/git#1104]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win10 64bit
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]

**Repro steps:**
1. git clone https://github.com/git-for-windows/git.git F:\git\src
2. git checkout vs/master
3. nuget.exe restore git.sln
4. msbuild /p:Configuration=Release;Platform=x86 /t:git git.sln

**Error info:**
c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib/amd64\invalidcontinue.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86' [F:\Git\src\git\git.vcxproj]

**Some investigations on my side:**
I found this is due to the LIBPATH is incorrect. When you build on x64, the LIBPATH is set for x64. But when you build on x86, the LIBPATH is still set for x64. Then I opened git.sln using VS and changed the LIBPATH to x86 for x86 platform and saved the solution file. This time, git.sln can be built successfully on x86. However, the LIBPATH for x64 is also changed to x86. It’s so weird. Could you please take a look at this? Thanks!

**Some build log on x86:**
Link:
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"..\git.exe" /NOLOGO **/LIBPATH:..\compat/vcbuild/GEN.DEPS/lib /LIBPATH:"c:/Program Files (x86)/Windows Kits/8.1/lib/winv6.3/um/x64" /LIBPATH:"c:/Program Files (x86)/Windows Kits/10/lib/10.0.10240.0/ucrt/x64" /LIBPATH:"c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib/amd64"** "F:\Git\src\compat\vcbuild\GEN.PKGS\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\..\..\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\Win32\Release\zlib.lib" "F:\Git\src\compat\vcbuild\GEN.PKGS\openssl.v140.windesktop.msvcstl.dyn.rt-dyn.x86.1.0.2.1\build\native\..\..\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\x86\release\libeay32.lib" "F:\Git\src\compat\vcbuild\GEN.PKGS\openssl.v140.windesktop.msvcstl.dyn.rt-dyn.x86.1.0.2.1\build\native\..\..\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\x86\release\ssleay32.lib" advapi32.lib kernel32.lib ntdll.lib shell32.lib user32.lib wininet.lib ws2_32.lib ..\compat\vcbuild\GEN.PKGS\libiconv.1.14.0.11\build\native\lib\v110\Win32\Release\dynamic\cdecl\libiconv.lib /MANIFEST:NO /DEBUG /PDB:"..\git.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"..\git.lib" /MACHINE:X86 /SAFESEH invalidcontinue.obj Release\add.obj
         Release\am.obj
         ……
         "Release\common-main.obj"
         Release\git.obj
         F:\Git\src\libgit.lib
         F:\Git\src\xdiff\xdiff_lib.lib
     2>c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib/amd64\invalidcontinue.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86' [F:\Git\src\git\git.vcxproj]

**Comment by dscho** [comment]
Thanks for the excellent bug report which allowed me to reproduce the issue within minutes, and even pointed to the solution!
