### ISSUE TITLE
Regression: `git diff C:\DifferentCasePath\file\in\repository` fails with "'...' is outside repository"

### ISSUE THREAD

**Issue by asottile** [git-for-windows/git#1106]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Seems related to #1095 and #1084 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
>git version --build-options
git version 2.12.2.windows.1
built from commit: 212247dd6345c820deeae61fcdf2f10cea10525a
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
>cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
>type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Probably not, also seeing this in appveyor: https://ci.appveyor.com/project/asottile/pre-commit/build/1.0.941/job/m5wri554ulvwsxo0

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I've only tried git bash and cmd, I expect the others to fail as well.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir -p c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1
git init c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1
cd c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1
touch f
git add f
git diff c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1\f
```
 - What did you expect to occur after running these commands?

I expect the last command to output nothing.

 - What actually happened instead?
```
>git diff c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1\f
fatal: c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1\f: 'c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1\f' is outside repository
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

My reproduction does not involve a specific repository, though this is plaguing the appveyor build of https://github.com/pre-commit/pre-commit

**Comment by FeodorFitsner** [comment]
Obviously, `install-git-2.12.2.ps1` was missing. I just added it - try rebuilding this build again please: https://ci.appveyor.com/project/asottile/pre-commit/build/1.0.951

**Comment by dscho** [comment]
> ```
> git diff C:\Temp\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\f
> fatal: C:\Temp\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\f: 'C:\Temp\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\f' is outside repository
> ```

Given that the repository was initialized in the `repo` subdirectory of the `aaa...` directory, and that you try to compare to a file `f` *next* to that `repo` subdirectory (not inside it), I would agree with Git that this path is outside the repository.

Did you maybe mean to call `git diff C:\Temp\aa...\repo\f` instead of `C:\Temp\aa...\f`?

**Comment by asottile** [comment]
woops, yeah that's a typo let me get a better reproduction

**Comment by asottile** [comment]
I've updated the ticket with my *actual* issue instead of trying (poorly!) to simplify it :D

**Comment by dscho** [comment]
By editing the original report, my comments look as if they were made up from thin air now.

**Comment by dscho** [comment]
> `git diff c:\users\ieuser\appdata\local\temp\pytest-x\test_allow_unstaged_config_opt0\1\f`

This path differs from the current directory in the case: Git's idea of the current directory would be more along the lines of `C:\Users\ieuser\AppData\Local\Temp\pytest-x\test_allow_unstaged_config_opt0\1\f`.

Yes, it is a bug, and I would welcome patches to fix it.

You can easily work around this issue by using relative paths, or by using the correct case when specifying an absolute path.

**Comment by asottile** [comment]
Lol oops sorry :)

This *did* work prior to 2.12, what changed?

**Comment by dscho** [comment]
> This did work prior to 2.12, what changed?

Lots ;-) I think the major change here was a switch to using `realpath()`.

**Comment by asottile** [comment]
Any hints as to where I should start looking to patch this?  I'm not super familiar with programming in a windows environment but I'd like to fix this regression if possible :)

**Comment by dscho** [comment]
Maybe here: https://github.com/git-for-windows/git/commit/7df5db8d31e7b384b14e488c76933d46a9e76161 :grinning:

**Comment by dscho** [comment]
Oh, and the latest snapshot should let you verify that it is fixed: https://wingit.blob.core.windows.net/files/index.html

**Comment by asottile** [comment]
It works!  Awesome!
