### ISSUE TITLE
Dark blue text is unreadable

### ISSUE THREAD

**Issue by hardhub** [git-for-windows/git#1107]
git version 2.12.1.windows.1
built from commit: 2c6cf4e358dd1395091e1d7f9544028e6df674a7
sizeof-long: 4
machine: x86_64
Windows 7 64-bit
CMD

Is possible for blue use light blue (not darkblue as it is for now)?

Dark blue text is unreadable:
![image](https://cloud.githubusercontent.com/assets/4306334/24344144/c0da01ae-12d2-11e7-847f-c0e167a5d467.png)

**Comment by shiftkey** [comment]
@hardhub please provide more details around what command you were running to trigger this output.

**Comment by hardhub** [comment]
I used "git branch -vv".

**Comment by shiftkey** [comment]
For reference, the blue color in Git Bash also has similar contrast issues:

<img width="819" src="https://cloud.githubusercontent.com/assets/359239/24349246/1b2a2060-132a-11e7-8090-f3ec59d41f83.png">

I can trace this back to at least 2.10.0, but I suspect it goes back further.

**Comment by kgybels** [comment]
@hardhub The colors used for branches can be configured. For your example, you can try the following:
`git config --global color.branch.upstream cyan`

Please refer to [color.branch.\<slot\>](https://git-scm.com/docs/git-config#git-config-colorbranchltslotgt) for the slot names and [color](https://git-scm.com/docs/git-config#git-config-color) for how to specify your desired color.

A different solution, which I use, is to configure the blue color slightly different in my terminal.

**Comment by hardhub** [comment]
@kgybels 
_The accepted values are two of normal, black, red, green, yellow, blue, magenta, cyan and white and optionally one of bold, dim, ul, blink and reverse. If two colours are given the first is the foreground and the second is the background._

So if I understand it correctly we cannot use blue for now. What I suggested is to replace blue color from DarkBlue (ColorTable01 #800000) to Blue (ColorTable09 #ff0000). It will look not ideally but much more clear.
And then we will be able to change Blue color in registry to get own ideal blue for terminal.
Why we cannot use DarkBlue to tune it in registry? Because many peoples use Far Manager as some sort of console. And background color of its panels is DarkBlue (ColorTable01). If we will change it then all other in panels will not be readable. So for _blue_ it is better to use Blue (ColorTable09) not DarkBlue(ColorTable01).

This trick is amazing:

> git config --global color.branch.upstream cyan

Thank you!

I think I can leave this issue open until Blue/DarkBlue choice is not solved.

**Comment by kgybels** [comment]
@hardhub This should do what you want:
`git config --global color.branch.upstream "blue bold"`

Note that Git uses [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to control the color of the output. This [stackoverflow answer](http://stackoverflow.com/a/38617204) has some good information about the support for these in the Windows console.

**Comment by hardhub** [comment]
@kgybels It works... Since it is totally configurable I will close issue. But please consider a changing of default color for upstream.

**Comment by kgybels** [comment]
@hardhub 
>But please consider a changing of default color for upstream.

This seems unlikely. Please keep in mind that it is hard to find defaults that work for everyone. For example, some people prefer a light background in their terminal, for them your suggested light blue might actually be less readable than the current dark blue.
