### ISSUE TITLE
Git credential authentication failed

### ISSUE THREAD

**Issue by 3kynox** [git-for-windows/git#1108]
Hello guys,

using 2.12.1 x64 - was unable to login over bitbucket, always return authentication failed.

Back to 2.11.1 x64 and everything is ok.

**Comment by ViceIce** [comment]
Version  2.12.0.windows.1 is working too. I have to downgrade too.

**Comment by ViceIce** [comment]
Version 2.12.2 is also broken.

**Comment by ViceIce** [comment]
Seems to be an issue with the credential manager update [399](/Microsoft/Git-Credential-Manager-for-Windows/issues/399)

**Comment by Memnarch** [comment]
oh thanks i was already going crazy!

**Comment by dscho** [comment]
I am fairly certain that v2.12.2(2) may fix this. Please test.

**Comment by ViceIce** [comment]
It's working for our local bitbucket server (basic auth).

**Comment by Memnarch** [comment]
it is working on my end, too!(Own Gitlab)

**Comment by dscho** [comment]
Yay! Thanks for the feedback, it is very helpful.
