### ISSUE TITLE
[python2] 'module' object has no attribute 'choice'

### ISSUE THREAD

**Issue by Campos696** [git-for-windows/git#1109]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.14393] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** python random.py **
```
 - What did you expect to occur after running these commands?

** the program to run normally **

 - What actually happened instead?

**Traceback (most recent call last):
  File "random.py", line 1, in <module>
    import random
  File "C:\Users\count\Desktop\Aula Udacity\Aulas\Stage 5\random.py", line 9, in <module>
    (one, two) = ChooseTwice(names)
  File "C:\Users\count\Desktop\Aula Udacity\Aulas\Stage 5\random.py", line 4, in ChooseTwice
    a = random.choice(items)
AttributeError: 'module' object has no attribute 'choice'

`import random

def ChooseTwice(items):
    a = random.choice(items)
    b = random.choice(items)
    return a, b

names = ["Alice", "Bob", "Charlie", "Debra"]
(one, two) = ChooseTwice(names)
if one == two:
    print "%s is happy!" % one
else:
    print "%s likes %s!" % (one, two)`

this is the code, when i tried it in repl.it it worked but in gitBash it doesn't

**Comment by shiftkey** [comment]
This is an issue with the version of Python that ships in Git for Windows. The python2 [package](https://github.com/git-for-windows/MSYS2-packages/blob/master/python2/PKGBUILD) seems recent enough to have a recent `random` module included, but I can trigger this error all the same.

A simpler repro:

```python
import random

number = random.randint(1,10)
print "randint %s!" % number
```

Output:

```sh
$ python random.py
Traceback (most recent call last):
  File "random.py", line 1, in <module>
    import random
  File "C:\Users\shiftkey\Documents\GitHub\random.py", line 3, in <module>
    number = random.randint(1,10)
AttributeError: 'module' object has no attribute 'randint'
```

With the amount of work required to support Git running on Windows, I'm not sure when this will get looked at. And it looks like you have a workaround, so unless someone has a lot of familiarity with building Python for Windows I suspect this will be a low priority.

**Comment by Campos696** [comment]
I know there is an easy workaround, but still i believe it should be reported all the same, cause someone else may be struggling with this problem thinking that his code is at fault, and maybe its an easy fix.


Anyway thanks for the quick reply!

________________________________
De: Brendan Forster <notifications@github.com>
Enviado: segunda-feira, 27 de março de 2017 18:54:11
Para: git-for-windows/git
Cc: Campos696; Author
Assunto: Re: [git-for-windows/git] random.choice error (#1109)


This is an issue with the version of Python that ships in Git for Windows. The python2 package<https://github.com/git-for-windows/MSYS2-packages/blob/master/python2/PKGBUILD> seems recent enough to have a recent random module included, but I can trigger this error all the same.

A simpler repro:

import random

number = random.randint(1,10)
print "randint %s!" % number

Output:

$ python random.py
Traceback (most recent call last):
  File "random.py", line 1, in <module>
    import random
  File "C:\Users\shiftkey\Documents\GitHub\random.py", line 3, in <module>
    number = random.randint(1,10)
AttributeError: 'module' object has no attribute 'randint'

With the amount of work required to support Git running on Windows, I'm not sure when this will get looked at. And it looks like you have a workaround, so unless someone has a lot of familiarity with building Python for Windows I suspect this will be a low priority.

**Comment by pmn** [comment]
@shiftkey this might be a filename conflict. Naming the file `random` will cause Python to look for a function called `randint` inside of random.py. Try renaming the file to something like `rando.py` (removing the `random.pyc` in the same directory if one exists) and run it again.

**Comment by shiftkey** [comment]
@pmn why didn't I think of this?

```sh
$ cat rando.py
import random

number = random.randint(1,10)
print "randint %s!" % number
$ python rando.py
randint 3!
```

![](https://cloud.githubusercontent.com/assets/359239/24382739/17acc24c-13a4-11e7-9609-930004f75525.gif)

@Campos696 I think this problem comes down to the REPL behaving differently when it would load the module, compared to when you use a file which clashes with this module name.

I'm going to close this out.

**Comment by shiftkey** [comment]
@Campos696 and here's an explainer of the behaviour you're seeing via @ncoghlan -  http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap
