### ISSUE TITLE
Post-install scripts not included in packaged builds

### ISSUE THREAD

**Issue by elyscape** [git-for-windows/git#111]
The post-install scripts that are part of [the filesystem package](https://github.com/git-for-windows/MSYS2-packages/tree/master/filesystem) are not included in the release builds.  Three of them are useful:

* [01-devices.post](https://github.com/git-for-windows/MSYS2-packages/blob/master/filesystem/01-devices.post) sets up various folders and symlinks inside `/dev`, notably including `/dev/fd`, which is required for Bash process substitution to work.
* [03-mtab.post](https://github.com/git-for-windows/MSYS2-packages/blob/master/filesystem/03-mtab.post) creates `/etc/mtab` as a symlink to `/proc/mounts`.
* [06-windows-files.post](https://github.com/git-for-windows/MSYS2-packages/blob/master/filesystem/06-windows-files.post) creates the `hosts`, `protocols`, `services`, and `networks` files in `/etc` by copying them from `C:\Windows\system32\drivers\etc`.

As a side note, the symlinks it creates are not true symlinks but [Cygwin's fancy pseudo-symlinks](https://cygwin.com/cygwin-ug-net/using.html#pathnames-symlinks), so creating them does not require admin privileges.

Normally, I'd create a pull request to include them, but there are some problems.  Problem the first:

![post-install-errors](https://cloud.githubusercontent.com/assets/792695/7336310/beb101f6-ebac-11e4-9e1c-3d86fb0b01e9.png)

This happens the first time the scripts are run.  The scripts are run, by the way, [by `/etc/profile`](https://github.com/git-for-windows/MSYS2-packages/blob/master/filesystem/profile#L104-L106), so this will be shown the first time (and only the first time, due to the way the scripts are written) that Git Bash is started.  The errors aren't terribly important, but would be scary to users who weren't expecting them.  This could potentially be worked around by putting patching the scripts to stifle output.

The other issue is that these files get written to the folder structure where Git is installed.  For a non-portable installation, that means inside Program Files.  Since Bash, `ln`, `mkdir`, and `cp` don't have manifests, they get to deal with Windows filesystem virtualization.  Even if they did have manifests, they'd have to deal with Windows filesystem virtualization if the user lacked permissions to write to the Program Files directory, which may well be the case for many users in enterprise settings.

A potential solution to this matter would be to have the installer, which is run in an elevated context, run the scripts itself to ensure that the files are created in the right place.

Thoughts?

**Comment by elieux** [comment]
> this will be shown the first time (and only the first time, due to the way the scripts are written) that Git Bash is started

Is Git Bash different in this regard from MSYS2 shells? My post-installs run on every bash login.

Having the installer run the scripts sounds good (MSYS2 installer runs `bash --login -c exit`).

> patching the scripts to stifle output

The errors you saw are rather important, aren't they? Some of the other possible errors seem absolutely unuseful though, e.g. I see this at the top of every shell window:

    chmod: changing permissions of ‘/dev/shm’: Permission denied
    chmod: changing permissions of ‘/dev/mqueue’: Permission denied

> Since Bash, `ln`, `mkdir`, and `cp` don't have manifests, they get to deal with Windows filesystem virtualization. Even if they did have manifests, they'd have to deal with Windows filesystem virtualization if the user lacked permissions to write to the Program Files directory, which may well be the case for many users in enterprise settings.

I've always found the virtualization behaviour unpredictable. I remember only a few cases where it kicked in, but that was always with an application from the 9x ages.

    $ mkdir /c/Program Files/foo
    mkdir: cannot create directory ‘/c/Program Files/foo’: Permission denied

Note that I haven't tried the new GfW, so if this post is wrong in some regard, please correct me.

**Comment by elyscape** [comment]
> Is Git Bash different in this regard from MSYS2 shells? My post-installs run on every bash login.

The scripts run every login but don't actually do anything if they detect that the files they would create already exist.

> The errors you saw are rather important, aren't they?

The first two lines aren't important and the following lines are the output of a `cp -v` operation and thus not errors.

**Comment by elieux** [comment]
You're right, I'm sorry. I misinterpreted the `mkdir:` prefix of the errors as a failure to create the directories. I agree that mode setting errors aren't very important (especially since we're mounting everything `noacl`).

**Comment by dscho** [comment]
The post-install scripts should not run everytime a Git Bash is started, that would just be wasteful. Instead they should be run at *post install* time, i.e. in the installer. PR welcome

**Comment by elyscape** [comment]
> The post-install scripts should not run everytime a Git Bash is started, that would just be wasteful. Instead they should be run at *post install* time, i.e. in the installer.

This is sensible but, unfortunately, the only way to do this would be to either delete the files after the installer runs or modify the profile script to not call them.

Actually, now that I think about it, I have an idea for how to do that that would even work with Portable Git packages. Let me see what I can do.

**Comment by elyscape** [comment]
Okay, pull request dealing with this has been submitted as git-for-windows/build-extra#46.
