### ISSUE TITLE
Git status fails with submodules

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#1110]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.12.2.windows.1
built from commit: 212247dd6345c820deeae61fcdf2f10cea10525a
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git status
```
 - What did you expect to occur after running these commands?

Status of working directory

 - What actually happened instead?

Got the following error:

```
$ GIT_TRACE=1 git st
15:38:09.053060 git.c:596               trace: exec: 'git-st'
15:38:09.053575 run-command.c:369       trace: run_command: 'git-st'
15:38:09.056061 git.c:299               trace: alias expansion: st => 'status' '-sb'
15:38:09.057061 git.c:642               trace: exec: 'git' 'status' '-sb'
15:38:09.057061 run-command.c:369       trace: run_command: 'git' 'status' '-sb'
15:38:09.064564 git.c:371               trace: built-in: git 'status' '-sb'
15:38:09.072061 run-command.c:369       trace: run_command: 'status' '--porcelain'
15:38:09.079736 git.c:371               trace: built-in: git 'status' '--porcelain'
fatal: 'git status --porcelain' failed in submodule ThirdParty
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Unfortunately I tried reproducing a MCVE locally with simple repositories with nested submodules, but I could not replicate the behavior. I also tried a public repo with submodules (hunter on Github) and was not able to repro there either. Must be something specific to the repository I'm working on at `$DAYJOB`.

My top-most repository has nested submodules:

`<root repo>` -> `Core` -> `ThirdParty`

When I run `git status` from the root repo, I get:

```
$ git status
fatal: 'git status --porcelain' failed in submodule ThirdParty
fatal: 'git status --porcelain' failed in submodule Core
```

And just from `Core` I get:

```
$ git status
fatal: 'git status --porcelain' failed in submodule ThirdParty
```

When I `cd` into `ThirdParty` and attempt a `git checkout`, I get this:

```
$ git checkout master
fatal: Unable to create 'E:/code/frontend2/source/.git/modules/Core/modules/ThirdParty/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

I remove the `index.lock` file and try the checkout again, it works. In fact, any number of checkouts will work until I go back up to the submodule above, run the `git status` again, then return back down to `ThirdParty` and I get the lock issue again. So the status command is causing weird lock issues in submodules it seems.

I also am monitoring child processes of `bash.exe` and the `git.exe` and `sh.exe` processes spawn and go away with each command (although the hierarchy of processes themselves is quite deep when they execute, not sure if that's abnormal). So there's no rogue commands that persist to keep the lock file there from what I can tell.

Sorry I don't have more information than this. Let me know if there's anything else I can provide to help.

**Comment by rcdailey** [comment]
Also FYI I do not have this problem with version 2.11.1. `git status` works fine in my parent repo and submodules are unaffected.

**Comment by shiftkey** [comment]
@rcdailey did you have any other tools/editors running at the same time, that "light-up" when they're looking at Git repositories? The presence of the lockfile often hints at another tool stomping over you at just the wrong time when you're trying to interact with a repository, and even `git status` is vulnerable to this...

**Comment by rcdailey** [comment]
I have Eclipse and Visual Studio running (both hint at some Git integration but I do not use those features), but they don't cause problems in 2.11.1, which I find strange. Never had issues with it until now.

**Comment by bturner** [comment]
My #1111 may be related to this. My test does not include any submodules, though.

If you downgrade to 2.12.1 does it work there?

**Comment by rcdailey** [comment]
@bturner: I'm not seeing this issue on v2.12.1

Not sure if it's path related, since the path to my working copy is pretty short already:

    /e/code/frontend/source/Core/ThirdParty

**Comment by bturner** [comment]
@rcdailey So if I understand you right, your `git status` issue with submodules only affects 2.12.2? 2.12.1 doesn't have any issues for you?

Note that the path _to_ the repository is only part of the story. The length of paths _within_ the repository appears to be more relevant. Does your repository happen to contain deep paths?

**Comment by dscho** [comment]
This is still unclear, and I'll just put this up for grabs in case anybody else wants to drive this forward.

**Comment by kgybels** [comment]
>@rcdailey It does have deeper paths but I'm not sure how deep it goes.

You can use something like `find . | wc -L` to find out.

**Comment by rcdailey** [comment]
Closing, not able to reproduce anymore.
