### ISSUE TITLE
difftool + beyond compare 4 behavior change between 2.11.1 and 2.12.1

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#1112]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Use these settings (make sure Beyond Compare install dir is on PATH):

```
[diff]
    tool = beyondcompare
[difftool "beyondcompare"]
    cmd = bcomp -expandall -solo "$LOCAL" "$REMOTE"
```

Simply setup a clone locally, and make some local modifications to existing, versioned files. Then run `git difftool -d` and you should see the behavior.

 - What did you expect to occur after running these commands?

Diff results should be aligned and comparable

 - What actually happened instead?

Beyond Compare 4 is showing results in a strange way, and files are not being compared with each other. This may have to do with how git 2.12.x is structuring files in temp directories for the compare tool; maybe it's using symlinks now which is confusing it?

Here is a screenshot of Beyond Compare when run from 2.12.1:

![image](https://cloud.githubusercontent.com/assets/1768054/24424744/56eed92c-13c7-11e7-94b2-d0545c6c6714.png)

And the same diff command in the same working copy with 2.11.1 installed:

![image](https://cloud.githubusercontent.com/assets/1768054/24424761/61997d50-13c7-11e7-8d15-2aee8eda8187.png)

Note that the same version of BC4 was used in both tests. Version of BC4 used is Version 4.1.9 (build 21719)

**Comment by Radrik5** [comment]
Yes, this is because of symlinks on the right side. Try this solution: http://stackoverflow.com/a/35319884/1836088

> In the Folder Compare, click the Rules toolbar button (referee icon). Go to the Handling tab. Check Follow symbolic links.
> 
> To make this affect all new sessions, change the dropdown at the bottom of the dialog from Use for this view only to Also update session defaults before you click OK.

**Comment by rcdailey** [comment]
This indeed solves the problem. I assumed incorrectly that this was a git problem, since I thought it was still supposed to be physically copying the files. I guess the symlinks makes sense, since it will be faster when diffing HEAD.
