### ISSUE TITLE
`git add *` crashes with a segmentation fault. Version 2.12.2 (most recent as of writing)

### ISSUE THREAD

**Issue by ric2b** [git-for-windows/git#1115]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.12.2.windows.1
built from commit: 212247dd6345c820deeae61fcdf2f10cea10525a
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not really, I think.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Running from MINGW64 (git bash)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
The crashing command is `git add *`.
It happens with a specific environment but is easily reproducible:
1. `git clone https://github.com/ric2b/Vivaldi-browser`
2. delete everything but the .git folder inside the `Vivaldi-browser` folder
3. download the source code for version 1.6.689 from https://vivaldi.com/source
4. extract the source code into the previously cloned repo
5. run `git add *` 
6. git crashes with a segmentation fault after a few seconds

```
 - What did you expect to occur after running these commands?

I expected all the changes to be added to staging.

 - What actually happened instead?

git crashed with a segmentation fault after a few seconds

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/ric2b/Vivaldi-browser

**Comment by flipchart** [comment]
Same issue with `git status`

```
git version 2.12.2.windows.1
built from commit: 212247dd6345c820deeae61fcdf2f10cea10525a
sizeof-long: 4
machine: x86_64
```

```
Microsoft Windows [Version 10.0.14393]
```

```
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

**Comment by dscho** [comment]
Possible duplicate of #1111

**Comment by dscho** [comment]
@ric2b @flipchart could I ask you to test [the snapshot I mentioned in #1111](https://github.com/git-for-windows/git/issues/1111#issuecomment-291153842)?

**Comment by ric2b** [comment]
@dscho I used the 64bit Portable version from your link and it worked great :)

**Comment by dscho** [comment]
Yeah! Thanks for testing!

**Comment by ric2b** [comment]
No problem, thank you for your work!

**Comment by flipchart** [comment]
@dscho Confirmed on my end as well 😄
