### ISSUE TITLE
Fetching refs with very long names fails, even when "Enable Win32 long paths" is enabled

### ISSUE THREAD

**Issue by kevin-david** [git-for-windows/git#1116]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

Git:
```
git version 2.12.1.windows.1
built from commit: 2c6cf4e358dd1395091e1d7f9544028e6df674a7
sizeof-long: 4
machine: x86_64
```

Windows: `Microsoft Windows [Version 10.0.15063]`

Installation: defaults

Environment specifics:

* I've enabled long-path support via group policy. [How to here](http://stackoverflow.com/a/27694470). You need to reboot afterwards.

### Details

Repro steps:
1. Create long ref (~250 characters) pointing to some commit. I used the web UI on [VSTS](https://www.visualstudio.com/team-services/) to do this, and pushed the repo to GitHub [here](https://github.com/kevin-david/test-shallow)
2. `git fetch`

Expected Behavior: Fetch should succeed and create/update the ref, since I enabled long path support.

Actual Behavior: Fetch fails with the following error:

```
error: cannot lock ref 'refs/remotes/origin/origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing/origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-': unable to create directory for refs/remotes/origin/origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing/origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-
From http://kedavid-dev:8080/tfs/DefaultCollection/o!_abcdefghij%C2%B6%20is%20ilex8d475dff0037cf7/_git/CacheServerTestRepo
 ! [new branch]      origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing/origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user- -> origin/origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing/origin/user/kedavid/rs_play_testing_a-revert-from-user-kedavid/rs_play_testing-revert-from-user-kedavid/rs_play_testing-revert-from-user-  (unable to update local ref)
```

### Workaround
I was able to work around this issue by manually placing the long ref in `.git\packed-refs` along with the commit it points to (and not forgetting the newline at EOF 😄 )

### Test repository
https://github.com/kevin-david/test-shallow

The behaivor can be easily reproduced if you:
1. `git clone https://github.com/kevin-david/test-shallow`
2. Open `.git\packed-refs`
3. Delete the very long ref, save + close
4. `git fetch`

**Comment by nalla** [comment]
Did you enabled `git config --global core.longpaths true` in git itself?

**Comment by kevin-david** [comment]
That fixed it! Thank you!

**Comment by nalla** [comment]
https://github.com/git-for-windows/build-extra/blame/master/ReleaseNotes.md#L22

**Comment by dscho** [comment]
> Why is that config setting disabled by default?

@kevin-david I keep trying to find the time to work on enabling it by default: two funny side effects of switching to the `\\?\` prefix are: 1) `aux.txt` can be created, and 2) performance *improves* (this is due to sidestepping some checks such as the `AUX` stuff). The real problem is that we use some Win32 API to normalize the path in that code which counteracts the performance improvements, so I want to avoid that API call.
