### ISSUE TITLE
Git for Windows installation stops at last step waiting for bash.exe to be closed, but does not continue if it is closed

### ISSUE THREAD

**Issue by jnareb** [git-for-windows/git#1118]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

I am upgrading Git for Windows to version 2.12.2 64-bit, and the problem is with the last step of upgrade.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Home, 64-bit, x64 processor
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I have chosen all defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Previous version of Git that was installed, and which Git Bash was running, was 2.10.0

### Details

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I was trying to install Git for Windows 2.12.2 64-bit, while there was open Git Bash from 2.10.0.

The installation process stopped at last step (last screen), telling that bash.exe and terminal needs to be closed. I have closed Git Bash, and checked with Task Manager that there isn't one present.

 - What did you expect to occur after running these commands?

That bash.exe and terminal process vanish from the list of processes blocking installation, and that I would be able to finish installing (upgrading) Git.

 - What actually happened instead?

I was stopped from finishing installation until I did a workaround: went back one step (to previous step), went to last step again - then there was no process blocking installation.

**Comment by dscho** [comment]
Could you re-run the installer with the `/LOG=<filename>` option? The output should contain some valuable hints where (and maybe how) things go awry.

**Comment by ryc8889** [comment]
I was having an issue as well with this.
It does seem to install "partially" even if you close the installer when it's stuck at 100%.
Then when you open up git bash it will attempt to do some post install processes(i had to run git bash as a administrator since it didn't have the proper permissions to create certain directories)
even then i was having some issues with some of my git commands

In the end I uninstalled git, and downloaded the 32-bit git for windows installer(also version 2.12.2) and it seemed to install perfectly with no hanging. I was able to install and use hubflow and all the commands for it and so far haven't had any issues with my git bash. The commands do "stall" sometimes and take a little while to start/complete(usually all finished within 1 minute or so) but I have some other issues with my laptop due to some company security applications and windows 10 built in services hogging up all my threads and my whole cpu so I can't say for certain it's due to switching to 32-bit. 

Hope this works for you

**Comment by dscho** [comment]
> Could you re-run the installer with the /LOG=<filename> option?

Could you?

**Comment by jnareb** [comment]
Below there is screenshot of this last page of install wizard, with the since closed processes; going back to repeat last step helps (as a workaround). Note: the problem persist in Git for Windows 2.12.2.2 64-bit installer.

![git-2 12 2 2-64-bit_screenshot_in-use_dialog](https://cloud.githubusercontent.com/assets/2706/24730746/c690f4b4-1a65-11e7-809f-5fb194e15af6.png)

I have attached result of installing with
```shell session
C:\Users\default\Downloads> Git-2.12.2.2-64-bit /LOG=install.txt
```
[install.txt](https://github.com/git-for-windows/git/files/901028/install.txt)

**Comment by dscho** [comment]
Oh, I finally understand. It does not auto-update... You need to hit the Refresh button on the lower left...

It would be nicer, I agree, to re-check periodically. No idea though whether InnoSetup would allow us to do that.

**Comment by jnareb** [comment]
Somehow I missed this "Refresh" button - is is not mentioned in the window description.

Also I thought that if I close those processes, then the install can continue (even if the window is not refreshed), that is that there would be check after pressing "Install" - among others to be less racy.

**Comment by dscho** [comment]
> It would be nicer, I agree, to re-check periodically. No idea though whether InnoSetup would allow us to do that.

@jnareb I researched this a bit. There is no way to have recurring calls out of the box, but there is a 3rdparty `InnoCallback.dll` we could use to register a timer that calls a custom function. But I have a little concern about that library being essentially unmaintained, and closed source (therefore it may not be possible for us to fix it in case that an InnoSetup version update breaks it).

Another idea would be to try refreshing the list automatically if we detect that the window has just come in focus (rationale: if you closed the application in question, you will then switch back to the Git for Windows installer, and the window will receive the focus again). But I did not find any event for that in http://www.jrsoftware.org/ishelp/topic_scriptclasses.htm...

Maybe you can investigate this further?

**Comment by dscho** [comment]
> @jnareb commented 12 seconds from now

BTW this. This is impressive.

**Comment by jnareb** [comment]
@dscho :`
> It would be nicer, I agree, to re-check periodically. [...]
[...]
> Another idea would be to try refreshing the list automatically if we detect that the window has just come in focus [...]

Why not simply check again when the user clicks on <kbd> Install </kbd> button?

**Comment by dscho** [comment]
> Why not simply check again when the user clicks on Install button?

Hmm. If you can get that to work, that'll do the job. I do not know off-hand where we could intercept this button click, but I guess grepping the source of [`build-extra`](https://github.com/git-for-windows/build-extra) for the text shown in the screenshot should be helpful.

**Comment by jnareb** [comment]
@dscho: Or just mention the <kbd>Refresh</kbd> button in the message, for example:

> The following applications use files that needs to be replaced, please close them  
> and press the "Refresh" button below.

Simples.

**Comment by fourpastmidnight** [comment]
@jnareb I think that would be great. I look forward to seeing a PR from you with that change!

**Comment by dscho** [comment]
@jnareb the easiest way to implement this is probably to clone https://github.com/git-for-windows/git-sdk-64, call the `git-bash.exe` in its top-level directory, in that window, call

```sh
cd /usr/src/
git clone https://github.com/git-for-windows/build-extra
cd build-extra
./installer/release.sh 0-test
```

to build your first installer.

Then, modify `installer/install.iss` to your heart's extent, building subsequent test installers until you are satisfied with the result. Then open a Pull Request.

That would go a long way to counteract the effect your remark "Simples" had on me: if it is so Simples, it should be not a problem to contribute a fix.

**Comment by jnareb** [comment]
I'm sorry that my failed attempt at joke had hurt feelings.

**Comment by dscho** [comment]
@jnareb do you mean to say that you won't take a crack at this? In that case I would just close this ticket.
