### ISSUE TITLE
Include new Git Credential Manager version

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#1126]
Ironically it was an automated code cleanup that broke an authentication dialog. We really need to wait for the code signing to complete on that version in order to avoid shipping a known bad version.

**Comment by dscho** [comment]
Done.

**Comment by YueLinHo** [comment]
How to check the GCM version number? :P

**Comment by YueLinHo** [comment]
This?
![image](https://cloud.githubusercontent.com/assets/5831804/24734253/eb480182-1aae-11e7-98f0-cbe7859db2c7.png)

**Comment by whoisj** [comment]
Yes. Also `git credential-manager version` should tell you as well.
