### ISSUE TITLE
VCRUNTIME140.dll missing

### ISSUE THREAD

**Issue by albertosantini** [git-for-windows/git#1127]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Downloaded Git for Windows 2.12.2(2), `PortableGit-2.12.2.2-64-bit.7z.exe`, on Windows 10 (64bit).

When I execute it, it displays the alert message: 

`The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix the problem`.

Any suggestion?

**Comment by landstander668** [comment]
A quick google suggests this is a Visual C++ runtime component. You should be able to download the installer from Microsoft [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by albertosantini** [comment]
@landstander668 The point of the issue is if Windows 10 stock doesn't have installed that Runtime, the portable package should not compel the installation of that Runtime, otherwise I would not call the distribution portable.

**Comment by dscho** [comment]
Workaround: use 7-Zip to extract the PortableGit.

Having said that, I agree, this is a regression. The culprit is that we had to switch away from an unsupported SFX component, and the recompiled version unfortunately depends on the VC140 runtime. Hopefully there is a way to change it so it only depends on files that are present on most, if not all Windows (>= Vista) computers.

@albertosantini any help warmly welcome.

**Comment by dscho** [comment]
@albertosantini if you have any good idea how to shrink the size of the SFX again, please let's hear it.

**Comment by fourpastmidnight** [comment]
@dscho Is there a way to statically link to this library for whatever component requires it?

**Comment by dscho** [comment]
> Is there a way to statically link to this library for whatever component requires it?

That's what I ended up doing. It comes at a price, though: it increases the SFX component from ~190kB (up from the previous ~90kB) to ~460kB.

At this point, I feel like this problem has been dumped on me as if I was consumer support instead of what I really am: an Open Source maintainer. So unless the OP steps up their game, we will have to accept the status quo.

**Comment by albertosantini** [comment]
@dscho thanks for the usual quick fix. 
For me it is fair enough the price to pay in size with respect to the installation of a dll.

**Comment by dscho** [comment]
@albertosantini You may be okay to pay the price, I am not, and I am sure that many users of the portable Git package would have appreciated if you and me would have worked together and put a little more effort into trying to keep the size of the portable Git package down.

**Comment by cleemesser** [comment]
I noticed this same problem on our company Windows 7 Enterprise (SP1) x64 computers.  Thank you for the attention above and work around. I very much appreciate GitPortable!

**Comment by dscho** [comment]
@cleemesser I do not recall off-hand whether the statically-linked SFX made it into the latest snapshot, but the next snapshot definitely will have it: https://wingit.blob.core.windows.net/files/index.html

**Comment by Ketho** [comment]
I first installed the [Visual C++ component](https://www.microsoft.com/en-us/download/details.aspx?id=48145) linked by @landstander668, which didn't resolve the issue.

Afterwards I also tried [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53840) (14.0.24215) and restarting, without any success.

So I'm looking forward to the new snapshot.

![](http://i.imgur.com/x4uHznq.png)

![](http://i.imgur.com/ZKgAwrx.png)

**Comment by cleemesser** [comment]
@dscho The snapshot (64bit Git portable) from 4/12/17 installed smoothly for me on our Windows 7 Pro. computers. Thank you!

**Comment by dscho** [comment]
@cleemesser thanks for reporting back!
