### ISSUE TITLE
Missing `AdditionalLibraryDirectories` property of git.vcxproj of vs/master branch

### ISSUE THREAD

**Issue by YueLinHo** [git-for-windows/git#1128]
I am using `vs/master` to dive some code. And looks like the newest commit (e292c1f2d0c43a7e2486782de1a05093f86cc5b1) on `vs/master` branch is broken.

The line [67](https://github.com/git-for-windows/git/blob/e292c1f2d0c43a7e2486782de1a05093f86cc5b1/git/git.vcxproj#L67) ~ 72
```
    <Link>
      <AdditionalDependencies>advapi32.lib;kernel32.lib;ntdll.lib;shell32.lib;user32.lib;wininet.lib;ws2_32.lib;..\compat\vcbuild\GEN.PKGS\libiconv.1.14.0.11\build\native\lib\v110\$(Platform)\Release\dynamic\cdecl\libiconv.lib;$(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalOptions>invalidcontinue.obj %(AdditionalOptions)</AdditionalOptions>
      <ManifestFile>..\compat\win32\git.manifest</ManifestFile>
      <SubSystem>Console</SubSystem>
    </Link>

```

which miss this line after [line 68](https://github.com/git-for-windows/git/blob/e292c1f2d0c43a7e2486782de1a05093f86cc5b1/git/git.vcxproj#L68):
```
      <AdditionalLibraryDirectories>..\compat/vcbuild/GEN.DEPS/lib;c:/Program Files (x86)/Windows Kits/8.1/lib/winv6.3/um/x64;c:/Program Files (x86)/Windows Kits/10/lib/10.0.10240.0/ucrt/x64;c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib/amd64</AdditionalLibraryDirectories>
```

It should be this:
```
    <Link>
      <AdditionalDependencies>advapi32.lib;kernel32.lib;ntdll.lib;shell32.lib;user32.lib;wininet.lib;ws2_32.lib;..\compat\vcbuild\GEN.PKGS\libiconv.1.14.0.11\build\native\lib\v110\$(Platform)\Release\dynamic\cdecl\libiconv.lib;$(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>..\compat/vcbuild/GEN.DEPS/lib;c:/Program Files (x86)/Windows Kits/8.1/lib/winv6.3/um/x64;c:/Program Files (x86)/Windows Kits/10/lib/10.0.10240.0/ucrt/x64;c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib/amd64</AdditionalLibraryDirectories>
      <AdditionalOptions>invalidcontinue.obj %(AdditionalOptions)</AdditionalOptions>
      <ManifestFile>..\compat\win32\git.manifest</ManifestFile>
      <SubSystem>Console</SubSystem>
    </Link>
```

The difference comes from commit 8f90b5b9c898164073886086d4df502c22de7467 (for 2.12.2.windows.1) and commit e292c1f2d0c43a7e2486782de1a05093f86cc5b1 (for 2.12.2.windows.2).

**Comment by YueLinHo** [comment]
I am using Debug/x64 configuration.

**Comment by YueLinHo** [comment]
I was on VS2013. It's fine after using VS2015.

**Comment by dscho** [comment]
The `GEN.DEPS\lib` directory is actually only initialized when you run `make -C compat/vcbuild`, and that requires the Git for Windows SDK. The entire point of having `vs/master` is to allow building without that SDK, with vanilla Visual Studio. By using the NuGet packages (which add their own deep lib directories automatically), I thought we had side-stepped the need to run `make -C compat/vcbuild`...
