### ISSUE TITLE
git commands running slow as hell

### ISSUE THREAD

**Issue by vocaviking** [git-for-windows/git#1129]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
**64-bit**
```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
**Windows 10, 64-bit**
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?
**defaults**
```
> type "C:\Program Files\Git\etc\install-options.txt"

$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
**I had Version 2.8 before. It ran very well.**
### Details
 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
**All of the above, depending on what I am doing.**
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
**All**
 - What did you expect to occur after running these commands?
**They work in a timely manner.**
 - What actually happened instead?
**Depending on the command, I wait a bit (roughly 2s) then it prints some output. Then I wait at least 5-7s until I can use the console again. (Even if it is somethings simple as a "cd" )**
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by shiftkey** [comment]
> (Even if it is somethings simple as a "cd" )

Without more information my gut feeling is to refer to these similar issues: #1070 & #1071

Please see if this changes your situation:

> I had the similar issue as yours on my Lenovo e450c laptop. And found the performance turned back to normal when I disabled AMD Radeon graphics driver in Windows device manager and switched to integrated Intel HD graphics.

**Comment by vocaviking** [comment]
Okay. That problem is very weird. I looked into your suggestions, and updated the graphic drivers.
After several attempts, restarts and versions, I finally got it to work properly.

However, why is this happening? It's only a shell programm, not a 2D or 3D one!

**Comment by PhilipOakley** [comment]
> Okay. That problem is very weird. I looked into your suggestions, and updated the graphic drivers.
> After several attempts, restarts and versions, I finally got it to work properly.

>However, why is this happening? It's only a shell programm, not a 2D or 3D one!

... But all of the graphic (terminal) output has to be displayed via those drivers. 

They (the drivers) get their hooks into all parts of the system with hidden interupts and time outs and goodness knows what. Shudders...

Glad to hear that your system has recovered.
--
Philip

**Comment by whoisj** [comment]
> However, why is this happening? It's only a shell programm, not a 2D or 3D one!

Starting with Windows 7 (maybe Vista?) the console had the ability to display itself via DirectWrite, which is build on top of Direct3D, which is heavily dependent on driver implementations of DirectX API.

**Comment by shiftkey** [comment]
Closing this out as there's not much else we can do here.
