### ISSUE TITLE
Submodule added with `git submodule add` has a .git directory that looks like a .git file

### ISSUE THREAD

**Issue by jk23909** [git-for-windows/git#1130]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.12.1.windows.1
built from commit: 2c6cf4e358dd1395091e1d7f9544028e6df674a7
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 Enterprise SP 1 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm at work and the network has also sorts of security "features." I won't be surprised if my situation is unique and can't be replicated. I've also installed git with symlinks disabled with the same result.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git submodule add <repository>
```
 - What did you expect to occur after running these commands?

I expected the added submodule to have a .git directory

 - What actually happened instead?

The added submodule had a .git "file" that sometimes can be used like a directory, but sometimes not.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It doesn't seem to be associated with a specific repository. I've experienced this with submodules cloned from two different git servers.
![submoduleissue](https://cloud.githubusercontent.com/assets/22966001/24862443/96c695a0-1dca-11e7-89a1-fc70b8a05e20.JPG)

**Comment by dscho** [comment]
> The added submodule had a .git "file"

That is by design.

> that sometimes can be used like a directory

It cannot really be used like a directory, but it contains the path to the directory that can.

> but sometimes not.

That is not by design. Please clarify how the use of the .git file breaks in your case.

**Comment by jk23909** [comment]
Ah, now I understand what happened. I may have moved the submodule, making the relative path listed in the .git file invalid. I, incorrectly, understood submodules to be wholly independent repositories that the parent repositories just happened to be aware of. Lesson learned.
