### ISSUE TITLE
"Headless" PortableGit installation no longer possible

### ISSUE THREAD

**Issue by sharkykh** [git-for-windows/git#1131]
Since the release of **Git 2.12.2(2)**,
the `-InstallPath="C:\\MyGit" -y -gm2` [as described here](https://github.com/git-for-windows/git/wiki/Zip-Archives---extracting-the-released-archives) is no longer working,

I'm guessing it has something, or everything to do with the switch to the "_**custom-built SFX that is based directly on 7-Zip's SFX**_".

I am using PortableGit to install Git as dependency of a program,
so it needs to be installed to a specific location.

Before opening this issue I also attempted to use the `-o` switch (as described in 7-Zip) to set output folder,
with no luck.
Am I missing something?
It is stated that the new SFX is based **directly** on 7-Zip's SFX, meaning,
as I understand it, that it **should support** 7z's command line switches.

Any help would be greatly appreciated.
Please let me know if you need more info.

**Comment by shiftkey** [comment]
This is a known issue. Reposting @dscho's [comment](https://github.com/git-for-windows/git/issues/1094#issuecomment-291635601) here:

> In the meantime, I switched to a new SFX component based on the offical 7-Zip SFX. One reason was to avoid being stuck with a no-longer-maintained SFX (the original website, http://7zsfx.info is no longer registered and there is no information what happened to the Subversion repository hosted at http://svn.7zsfx.info), another reason was to allow contributors to fix bugs.
>
> One fallout is that the command-line options mentioned in the original report will no longer work at all.
>
> But all is not lost: a fix to this ticket only needs a dedicated contributor with a little time and drive: simply clone https://github.com/git-for-windows/7-Zip, open CPP\7zip\Bundles\SFXSetup\SFXSetup.sln in Visual Studio 2017 (the free Community Edition should work just fine), switch the mode to ReleaseD and start hacking.

**Comment by sharkykh** [comment]
Thanks for the quick reply and sorry for the duplicate thread!

So I understand now that there is no workaround at the moment...
I guess I'll roll back the version just for now (doesn't really matter to me _that_ much right now)
until someone with the required skills takes on the task to implement `-InstallPath` at the very least.

Thanks again!

**Comment by whoisj** [comment]
Closing the issue due to being a duplicate, that how ever is **not** an intention to dissuade discussion. Please, carry on as needed.

**Comment by dscho** [comment]
> until someone with the required skills takes on the task

*sigh*. I wish there were less comments like these, and more users rising up to those tasks. Nobody in this project started out with the skills needed to develop Git for Windows, we all acquired them on-the-go, as needed.

**Comment by sharkykh** [comment]
Maybe it would be easier if anyone has a copy of the [SVN trunk](https://web-beta.archive.org/web/20161007051103/https://svn.7zsfx.info/listing.php?repname=7zSfx).

**Comment by dscho** [comment]
> Maybe it would be easier if anyone has a copy of the SVN trunk.

Only if someone steps up to maintain that. From your message, I gather that you'd be unwilling to do that. And so am I.

**Comment by mirh** [comment]
I sigh because you closed the other issue, like it was my, yours, or somebody else fault for being busy and *contributing to society* in other ways.

**Comment by dscho** [comment]
@mirh I understand that you are irked by "the other ticket" being closed. However, it was my understanding that neither you nor me could do anything about it. Leaving it open for some very remote and highly unlikely chance that somebody else is less busy than you or me just seemed to be an undesirable option: I do try to address the issues on this here bug tracker as much as possible, and I am simply and plainly overwhelmed with the amount already. That is the reason why I would have loved to get even a little assistance from your side. As it is, I am forced to triage tickets rather more liberally than I want to. If there is no chance for me to address them, and if there is no sign of any contributor having the chance, I need to close them.

I also understand that my relatively terse communication style may appear very rude to some. Please understand, though, that I am just trying to get bug fixed and features implemented and in general to keep this project as healthy as possible, which is sadly not accomplished by spending a lot of time on conversations.

In that light, I would like to challenge you to imagine what your comments accomplish on my side, and maybe rethink the tone, or even the content? It is okay if you contribute to society in other ways than to contribute time or code to the Git for Windows project, and maybe you want to avoid counter-balancing that good karma with your comments on this here bug tracker.

**Comment by dscho** [comment]
> > Maybe it would be easier if anyone has a copy of the SVN trunk.
> 
> Only if someone steps up to maintain that. From your message, I gather that you'd be unwilling to do that. And so am I.

For the record: while the SVN is apparently lost, the latest source code of the "modified 7-Zip SFX" project is still [available from the amazing Wayback Machine](https://web-beta.archive.org/web/20160508074540/http://7zsfx.info:80/files/7zsd_src_160_2712.7z).
