### ISSUE TITLE
We have three users that can push developer code to test and production environments. One of our user has lost the ability to right click on the folder in windows and do a Git Bash Here. She is not able to promote code at all without this. How do we get this functionality restored?  We are on V9.0.2

### ISSUE THREAD

**Issue by christinaringstad** [git-for-windows/git#1132]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?  
Windows 7, 64 bit

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by shiftkey** [comment]
> How do we get this functionality restored? We are on V9.0.2

I'm not sure what version this refers to, and without the information we've asked for in the issue template we really can't help to troubleshoot further.

**Comment by christinaringstad** [comment]
Other than telling you we are on Windows 7, 64 bit, I cannot answer any of the other questions in the template.  We have basically zero support for this tool.  I have updated the issue.

Tina Ringstad
Business Intelligence Data Analyst
Enterprise Data Warehouse
WPS Health Solutions

p: (608) 977-7667
e: Christina.Ringstad@wpsic.com<mailto:Christina.Ringstad@wpsic.com>

CONFIDENTIALITY NOTICE: This e-mail, including any attachments, may contain confidential, privileged and/or proprietary information which is solely for the use of the intended recipient(s). Any review, use, disclosure, or retention by others is strictly prohibited. If you are not an intended recipient, please contact the sender and delete this e-mail, any attachments, and all copies.

**Comment by shiftkey** [comment]
> We are on V9.0.2

This version number doesn't match any of the Git for Windows releases. Could you be referring to [GitLab](https://about.gitlab.com/) which has just had a [9.0.2](https://about.gitlab.com/2017/03/29/gitlab-9-dot-0-dot-2-released/) release?

**Comment by christinaringstad** [comment]
Yes, that is for gitlab.  Where do I find the Git for windows release number?

Tina Ringstad
Business Intelligence Data Analyst
Enterprise Data Warehouse
WPS Health Solutions

p: (608) 977-7667
e: Christina.Ringstad@wpsic.com<mailto:Christina.Ringstad@wpsic.com>

CONFIDENTIALITY NOTICE: This e-mail, including any attachments, may contain confidential, privileged and/or proprietary information which is solely for the use of the intended recipient(s). Any review, use, disclosure, or retention by others is strictly prohibited. If you are not an intended recipient, please contact the sender and delete this e-mail, any attachments, and all copies.

**Comment by shiftkey** [comment]
@christinaringstad if you launch Git CMD or Git Bash from the start menu you should be able to run the code commands from the issue template - please update the original issue with what you find.

**Comment by christinaringstad** [comment]
I keep getting command not found.  What is it that you need me to put in the Git Bash window?

Tina Ringstad
Business Intelligence Data Analyst
Enterprise Data Warehouse
WPS Health Solutions

p: (608) 977-7667
e: Christina.Ringstad@wpsic.com<mailto:Christina.Ringstad@wpsic.com>

CONFIDENTIALITY NOTICE: This e-mail, including any attachments, may contain confidential, privileged and/or proprietary information which is solely for the use of the intended recipient(s). Any review, use, disclosure, or retention by others is strictly prohibited. If you are not an intended recipient, please contact the sender and delete this e-mail, any attachments, and all copies.

**Comment by elieux** [comment]
@christinaringstad, this is just a wild guess, but is it possible that Git for Windows is suddenly missing from the disk? Can you check if one of the directories below exist?

- `C:\Program Files\Git`
- `C:\Program Files (x86)\Git`

**Comment by christinaringstad** [comment]
I will have the person who is having issues check when she is back in the office.  Thank you for your help on this.

Tina Ringstad
Business Intelligence Data Analyst
Enterprise Data Warehouse
WPS Health Solutions

p: (608) 977-7667
e: Christina.Ringstad@wpsic.com<mailto:Christina.Ringstad@wpsic.com>

CONFIDENTIALITY NOTICE: This e-mail, including any attachments, may contain confidential, privileged and/or proprietary information which is solely for the use of the intended recipient(s). Any review, use, disclosure, or retention by others is strictly prohibited. If you are not an intended recipient, please contact the sender and delete this e-mail, any attachments, and all copies.

**Comment by christinaringstad** [comment]
The person having the issue did confirm she has the following on her C drive:

[cid:image001.png@01D2B2B6.52BAEDE0]



Tina Ringstad
Business Intelligence Data Analyst
Enterprise Data Warehouse
WPS Health Solutions

p: (608) 977-7667
e: Christina.Ringstad@wpsic.com<mailto:Christina.Ringstad@wpsic.com>

CONFIDENTIALITY NOTICE: This e-mail, including any attachments, may contain confidential, privileged and/or proprietary information which is solely for the use of the intended recipient(s). Any review, use, disclosure, or retention by others is strictly prohibited. If you are not an intended recipient, please contact the sender and delete this e-mail, any attachments, and all copies.

**Comment by whoisj** [comment]
@christinaringstad since this is Windows 7, if the user presses the <Start> key, brings up the start menu, and they searches for Git-bash: is there a shortcut? If so, the user can use this shortcut to launch git-bash and then use console commands, such as `cd <path>`, to get where they need to be.

**Comment by christinaringstad** [comment]
Thank you.  I will try this out on my PC since I have both options working and see if we can’t get her to where she needs to be using this work around.

Tina Ringstad
Business Intelligence Data Analyst
Enterprise Data Warehouse
WPS Health Solutions

p: (608) 977-7667
e: Christina.Ringstad@wpsic.com<mailto:Christina.Ringstad@wpsic.com>

CONFIDENTIALITY NOTICE: This e-mail, including any attachments, may contain confidential, privileged and/or proprietary information which is solely for the use of the intended recipient(s). Any review, use, disclosure, or retention by others is strictly prohibited. If you are not an intended recipient, please contact the sender and delete this e-mail, any attachments, and all copies.

**Comment by dscho** [comment]
I am closing this until we get further information.
