### ISSUE TITLE
Change project name?

### ISSUE THREAD

**Issue by mikemaccana** [git-for-windows/git#1133]
Ended up here looking for [Git For Windows](https://git-scm.com/download/win). This project isn't released by the git project, and includes a lot of things which obviously aren't git for windows (command prompt extensions, a specific GUI, etc).

Maybe "git toolkit for Windows" or similar?

**Comment by fourpastmidnight** [comment]
This is a "friendly fork" of the git project, whose aim is to create a distribution of git which will work on Windows. In order to make that possible, several Unix told are included, and some Windows Explorer integrations were added.

**Comment by mikemaccana** [comment]
TBQH I'm not sure how 'friendly' using another project's name for 'that project +500MB of additional software' is. Most users are looking for [git for Windows](https://git-scm.com/download/win) and don't want a port of gitk or a new terminal emulator. 

msysgit was a better name.

**Comment by kostix** [comment]
@mikemaccana, two points:

* Please be easier on using the "most users" term in an argument: I don't think
neither you nor me actually did proper (or at least some) scientific research on
what the preferences of users are.

    Still, to illustrace your PoV might actually represent that of a minorify of the GfW's
user base, I invite you to search for closed issues in this very issue tracker where
users ask for inclusion of their preferred tools (such as working `rsync` etc).
They are not necessarily "right" or "wrong" in their expectations;
I'm just trying to illustrate that it's not productive to try backing your own
personal opinion by invoking that "most users…" unscientific claim.

* By all means, take the GfW's sources and tweak them to build a slim installer
which would include nothing more than whatever subset of Git you claim to be "just Git".

    Then you could propose to implement a way to produce, say, two installer packages:
"all-in-one" and "slim", and convince the team to release both.

    Even if the maintainers won't argee, I think maintaining a set of tweaked
build scripts/Makefiles on top of regular GfW releases won't be an uphill battle
so you could probably sustain that.

In either case, asking to rename a blessed Git source port is an exercise in futility IMO.

**Comment by mikemaccana** [comment]
There already is a slim installer: git for windows is only 35MB. It's just this project is using its name.

**Comment by kostix** [comment]
@mikemaccana, I think it's now apparent you're confusing the GfW's SDK with the binary installers this SDK is used to create.

If you navigate to <https://git-for-windows.github.io/> and click the "Download" button you'll end up on the Github's release page where you'll locate that same 35M installer binary linked from the main Git project page.

To verify this, I invite you to hover over the link reading "click here to download manually" on the <https://git-scm.com/download/win> page to discover it leads exactly to where the Download button at <https://git-for-windows.github.io/> leads.

Currently that's <https://github.com/git-for-windows/git/releases/download/$version/$binary.exe>
