### ISSUE TITLE
fatal error - add_item(...) with ssh.exe from Git for Windows 2.8.1+

### ISSUE THREAD

**Issue by bcoov** [git-for-windows/git#1135]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git For Windows 2.12.2 64-bit (originally GfW 2.8.1 64-bit) and Git for Windows 1.9.5 (obtained [here](https://github.com/msysgit/msysgit/releases/tag/Git-1.9.5-preview20150319))
```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64

git version 1.9.5.msysgit.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows Server 2012 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.2.9200]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

(2.12.x)
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

No output for 1.9.5. Used mostly defaults, only notable changes were
not adding a Start Menu folder, setting to only use git via the
Git Bash (a VBS script in this case), and not adding the "Git Bash here"
option for this version.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

See below

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Primarily Git Bash (2.12.x), occasionally cmd.exe for testing. The method Jenkins uses to run Git is the primary focus of my issue though.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Via Jenkins build output:
using GIT_SSH to set credentials Git SSH
> C:\Program Files (x86)\Git\cmd\git.exe fetch --tags --progress ssh://git@path/to/bitbucket.git +refs/heads/*:refs/remotes/origin/*
```
 - What did you expect to occur after running these commands?

SSH credential setting passes and build proceeds to checkout.

 - What actually happened instead?

```
One of two things:
Timeout on the step listed above (setting credentials)

or

stdout:
stderr:       0 [main] ssh 7184 C:\Program Files\Git\usr\bin\ssh.exe: *** fatal error - add_item ("\??\C:\Program Files\Git", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFF9B90  0018005CCCE (0018023F4C2, 0018021CC39, 00600010000, 000FFFF8B10)
000FFFF9B90  00180046559 (000FFFFABC0, 000FFFF9B90, 1D2B3B6FE49A790, 00000000000)
000FFFF9B90  00180046592 (000FFFF9B90, 00000000001, 00600010000, 505C3A435C3F3F5C)
000FFFF9B90  001800CAF9B (00000000000, 00140000024, 00000000000, 1D2B3B7073A8D0A)
000FFFFCBE0  001801187D5 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCB0  00180046B65 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001800457C3 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045874 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
fatal: Could not read from remote repository.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not repository specific

## Problem Description

I'm not sure if this is the appropriate place to put this, but my efforts over the past 3 days seem to have narrowed down my issue to a problem between Git for Windows 2.12.2.windows.2 (previously 2.8.1 64 bit) and Git 1.9.5.

Our environment is as follows: We have a Jenkins instance running on Windows Server 2012 64-bit (the master node), originally with Git Plugin 2.4.1 installed. Attempts to implement a Pipeline job would fail with a timeout as mentioned (on Git Plugin 2.4.1) or with the "fatal error - add_item(..." (Git Plugin 2.5.3+).

The importance of Git Plugin 2.5.3: This is the newest version where the Pipeline: Multibranch plugin would succeed when scanning the given repository while not complaining about other plugins not being new enough versions.

To clarify: The problem(s) listed above **only** occur when Git is being executed via the Git Plugin on Jenkins. Running on the server through Git Bash or Cmd.exe result in expected/normal behavior.

# How Fixed

I have finally managed to get a working setup, but in a way that does not seem intended and I honestly have no idea _why_ it works.

The first step of the fix was following the serverfault answer given [here](http://serverfault.com/a/824189/410332) which allowed the regular Pipeline jobs to pass the SSH credentials step on Git Plugin v2.4.1. Switching to Git Plugin v2.5.3 reverted this to not working again.

[This comment](https://github.com/git-for-windows/git/issues/493#issuecomment-185183834) and a comment on the above linked serverfault answer prompted me to try using Git for Windows 1.9.5. This allowed both the Multibranch repo-scan and the regular Pipeline jobs to succeed with no problems, but **only** if the ssh.exe from GfW 1.9.5 was being used, and **only** if it was located in the C:\Program Files (x86)\Git\bin directory (as opposed to C:\Program Files\Git\usr\bin. Specifically, a shortcut was added to point the x86 version).

**Comment by dscho** [comment]
> 0 [main] ssh 7184 C:\Program Files\Git\usr\bin\ssh.exe: *** fatal error - add_item ("\??\C:\Program Files\Git", "/", ...) failed, errno 1

This symptom is common when running MSYS2 programs (such as `ssh.exe`) from an account of an unhandled account type. We fixed something similar a while ago, where the MSYS2 runtime was ill-prepared to handle a "NETWORK" account.

I may be able to help if I get a lot more detail about that part of the setup.

**Comment by bcoov** [comment]
On the Windows slaves (Windows 7) and the master server (Windows Server 2012), the jenkins instance is installed as a service which runs under a "Local System Account", which should be the account that processes during the build are run as.

I ran a git checkout in the background during a build and then executed `tasklist /v` to see what account that was, which displayed as:
```
ssh.exe   ...   NT AUTHORITY\SYSTEM  ...
git.exe   ...   NT AUTHORITY\SYSTEM  ...
git.exe   ...   NT AUTHORITY\SYSTEM  ...
ssh.exe   ...   NT AUTHORITY\SYSTEM  ...
git.exe   ...   NT AUTHORITY\SYSTEM  ...
git.exe   ...   NT AUTHORITY\SYSTEM  ...
ssh.exe   ...   NT AUTHORITY\SYSTEM  ...
```
where running git/ssh directly from a cmd window on the server displayed as
```[SERVER-MACHINE_NAME]\jenkins```

I should also note that this problem only occurs when attempting a build where the git operations (requiring ssh) occur directly on the master server. None of the slave VMs exhibit these errors, although their services are configured the same with the exception of them being a jenkins-slave service as opposed to the core jenkins service.

A small disclaimer: I inherited this server setup so I'm still familiarizing myself some of the more obscure details of how everything is configured/operating.

**Comment by dscho** [comment]
This is the kind of bug that can take weeks to figure out, unfortunately. I would still be interested in seeing the root cause, so that I can do something about it.

Sadly, I think that the only way to get to the bottom of this is to spend some time instrumenting the MSYS2 runtime (meaning: introducing debug print statements, build it, copy it onto the machine in question, running an `sh.exe` process under the account in question, lather, rinse, repeat).

If you are up for this, let's coordinate some time next week when we can be online at the same time (I am in UTC+0200 for two more weeks, then UTC+0100)?

**Comment by dscho** [comment]
FWIW I would still be available to coordinate for a joint debugging session.

/remind me to maybe close this in two weeks.

**Comment by dscho** [comment]
/remind me to maybe close this in two weeks.

**Comment by lukeschlather** [comment]
anybody know how to instrument MSYS2 stuff to debug this? I just had a stack trace very similar to the above on my laptop.

I've been getting these weird hangs for a long time where sometimes for no apparent reason git will take 30 seconds to do anything, with no apparent resource usage, until it finally completes.

I'm also running an Emacs build (which I think is compiled with the same toolchain) which also is experiencing weird hangs when I try to start a new Emacs window.

**Comment by michael-markl** [comment]
I also experience this. Every once in a while, git hangs on remote operations, and I get an error such as:

```pwsh
PS C:\Users\[REDACTED]\git\unified-flow-model> git pull                  
      0 [main] ssh (12012) C:\Users\[REDACTED]\AppData\Local\Programs\Git\usr\bin\ssh.exe: *** fatal error - add_item ("\??\C:\Users\[REDACTED]\AppData\Local\Programs\Git", "/", ...) failed, errno 1
```

If there is some assistance on how to debug this, I'd happily help.

**Comment by dscho** [comment]
@michael-markl the most common cause of this is when _competing_ MSYS2 processes start up, without a common MSYS2 parent process (which a Git Bash would provide, for example). (See https://gitforwindows.org/the-difference-between-mingw-and-msys2.html for a thorough explanation what "MSYS2 process" means in this instance.) Since they lack a common MSYS2 parent process, both need to construct a (shared) heap, and since one of them wins, the other one will mistakenly use that heap prematurely, i.e. before it is fully initialized. At least that's my take on this `add_item` issue. I am at a total loss when it comes to proposing a way to fix this properly. You cannot control two independent processes, not without having a common parent process to work with.

In your particular instance, I would say that the simplest way to get out of that fix would be to use [Windows' own OpenSSH implementation](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh-overview), which neatly side-steps the need to use the MSYS2 version of OpenSSH.
