### ISSUE TITLE
how to change account info?

### ISSUE THREAD

**Issue by xbotao** [git-for-windows/git#1139]
I use `git for windows` on **win10 64bit**.
I used `Account A` to login [coding](http://coding.net) before. Now I want to push code to another account's bucket. It donnot ask me to input my `Accout B` info for [coding](http://coding.net).

How to delete the `Account A` 's save Information?

**Comment by shiftkey** [comment]
@xbotao as this is a general Git question, please ask this on the [Git Users mailing list](https://groups.google.com/forum/#!forum/git-users)
