### ISSUE TITLE
fatal: 'rebase' appears to be a git command, but we were not able to execute it. Maybe git-rebase is broken?

### ISSUE THREAD

**Issue by dongryphon** [git-for-windows/git#1140]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I did find https://groups.google.com/forum/#!topic/msysgit/VrQLAgQwJHM and it seems to be related since it implicates the way git runs these other commands... and I am not using git-bash since it starts a new terminal window (why???).

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd /c ver
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Programs\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am using ConEmu (ConEmu x64 150913.x64) and starting git-cmd with a batch file like so:
```
@echo off
cls
set GIT_SSH=C:\Programs\Git\usr\bin\ssh.exe
C:\Programs\Git\git-cmd.exe --command=usr/bin/bash.exe -l -i
```

The above runs after ConEmu inits (see below).

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I am using ConEmu and that spawns a Cmd process in each pane of the console. It runs its own init script but likely not important:
```
@rem !!! Do not change this file in-place, change its copy instead !!!
@rem !!!  Otherwise you will lose your settings after next update  !!!

@echo off

rem Simple "ver" prints empty line before Windows version
rem Use this construction to print just a version info
FOR /F "delims=#" %%v IN ('ver') DO @echo %%v

rem Now we form the command prompt

rem This will start prompt with `User@PC `
set ConEmuPrompt0=$E[32m$E]9;8;"USERNAME"$E\@$E]9;8;"COMPUTERNAME"$E\$S

rem Followed by colored `Path`
set ConEmuPrompt1=%ConEmuPrompt0%$E[92m$P$E[90m
if NOT "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
  if "%PROCESSOR_ARCHITEW6432%" == "AMD64" if "%PROCESSOR_ARCHITECTURE%" == "x86" (
    rem Use another text color if cmd was run from SysWow64
    set ConEmuPrompt1=%ConEmuPrompt0%$E[93m$P$E[90m
  )
)

rem Carriage return and `$` or `>`
rem Spare `$E[90m` was specially added because of GitShowBranch.cmd
if "%ConEmuIsAdmin%" == "ADMIN" (
  set ConEmuPrompt2=$_$E[90m$$
) else (
  set ConEmuPrompt2=$_$E[90m$G
)

rem Finally reset color and add space
set ConEmuPrompt3=$E[m$S

if /I "%~1" == "/git" goto git
if /I "%~1" == "-git" goto git
goto no_git

:git
call "%~dp0GitShowBranch.cmd" /i
goto :EOF

:no_git
rem Set new prompt
PROMPT %ConEmuPrompt1%%ConEmuPrompt2%%ConEmuPrompt3%

```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git pull --rebase origin EXT-389
From github.com:dongryphon/SDK
 * branch                  EXT-389    -> FETCH_HEAD
fatal: 'rebase' appears to be a git command, but we were not
able to execute it. Maybe git-rebase is broken?
```

 - What did you expect to occur after running these commands?

The branch is valid and all this worked with version 1.9.5 of git.

 - What actually happened instead?

The "git-rebase is broken" message.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Doesn't seem to be related to the repo - just the ability to run git-rebase from git-cmd

**Comment by dongryphon** [comment]
I tried to reinstall `Git-2.12.2.2-64-bit.exe` and the error persists. I suspect it is in the way some of the helper git commands are spawned...

**Comment by dongryphon** [comment]
Removing `--rebase` works:
```
   git pull origin EXT-389
```
Does a merge just fine

**Comment by dscho** [comment]
`git-rebase` is a shell script. Maybe you added `<Git>\mingw64\bin` to the PATH instead of `<Git>\cmd`?
