### ISSUE TITLE
Unattended setup

### ISSUE THREAD

**Issue by megamorf** [git-for-windows/git#1142]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

# Issue

We cannot get a parameterized unattended git installation to work as intended. 

## Steps

1. run `Git-2.11.0.3-64-bit.exe` with `/SAVEINF="wts-git.inf"`-switch to store installation parameters in a file
2. run `Git-2.11.0.3-64-bit.exe` with `/SILENT /LOG /NORESTART /LOADINF="wts-git.inf"` to feed it the installation parameters
3. Git is installed with default parameters, and the cli prompt hangs indefinitely

Contents of wts-git.inf:
```
[Setup]
Lang=default
Dir=C:\Program Files\Git
Group=Git
NoIcons=1
SetupType=default
Components=
Tasks=
```
This can be reproduced on freshly provisioned systems. What are we doing wrong?

The only issue that's remotely similar to our issue is this: #571

### Setup
All recent versions of git for Windows that we've tried:
```
Git-2.6.1-64-bit.exe
Git-2.7.4-64-bit.exe
Git-2.9.3.2-64-bit.exe
Git-2.11.0.3-64-bit.exe
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Server 2012 R2 Datacenter (6.3.9600)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
PS C:\> cat "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

``` 
The 2012 R2 machines are Terminal Servers
```

### Details

 - What did you expect to occur after running these commands?

```
A successful git installation that's based on the inf parameters
```

 - What actually happened instead?

```
The git for Windows setup is always installing all components regardless of specified inf
```

**Comment by shiftkey** [comment]
@megamorf it's not clear to me when this worked for the Git for Windows installer - you mention `Git-2.6.1-64-bit.exe` doesn't work, but is there an earlier version that has worked for you?

My gut feeling is that this is an Innosetup-only feature that might have been deprecated as part of the changes migrating from `msysgit` and the Git 1.x series.

**Comment by dscho** [comment]
> My gut feeling is that this is an Innosetup-only feature that might have been deprecated as part of the changes migrating from msysgit and the Git 1.x series.

The `/SAVEINF`/`/LOADINF` thing should still be supported.

There should be information in the log. I do not see it pasted here, and it would probably be easier if it was sent to a file via `/LOG="log.txt"`.

**Comment by dscho** [comment]
Assuming that the log pointed to the culprit, and that it was easy to fix, I will close this ticket.
