### ISSUE TITLE
Git.exe crashes on WinSshFs - unhandled exception

### ISSUE THREAD

**Issue by ambrt** [git-for-windows/git#1143]
- [v] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063] 


```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"


Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using Windows 10 host with VMWare Workstation Ubuntu guest.<br>
To edit files inside of guest  i use [WinSshFs](https://github.com/Foreveryone-cz/win-sshfs/) application [v1.6.0.14](https://github.com/Foreveryone-cz/win-sshfs/releases/download/1.6.1/previous.release-1.6.0-rc3.zip).

I can edit guest files correctly. They are mounted on new drive <b> F:\ </b>

But i can't run Windows Git on the mounted drive repo.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cd F:
cd myrepo
git status
```
 - What did you expect to occur after running these commands?

info about my repo.

 - What actually happened instead?

The  `git status`  launched on  folder that is inside guest git crashes with debug info:
`An unhandled win32 exception occurred in git.exe`

After that error text different numbers occur like  [18104] , [3760],[14748] etc (not sure what they are).

For other projects that are on Windows host drive same installation of git works correctly.

**Comment by dscho** [comment]
Typically, there is a "Details" button with unhandled exceptions that has more information. Do you see those details? Could you paste them here?

**Comment by ambrt** [comment]
@dscho i get first window:
![err](https://cloud.githubusercontent.com/assets/10456131/25276270/a3d01302-2699-11e7-8bbb-7c90621b094c.png)

Then in Visual Studio 2015 this window:

![err2](https://cloud.githubusercontent.com/assets/10456131/25276271/a65a8580-2699-11e7-969f-66cc9ede2917.png)

**Comment by ambrt** [comment]
From Vistual Studio debbuger i get this:
`git.exe' (Win32): Loaded 'C:\Program Files\Git\mingw64\bin\git.exe'. Module was built without symbols.
'git.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Program Files\Git\mingw64\bin\libeay32.dll'. Module was built without symbols.
'git.exe' (Win32): Loaded 'C:\Program Files\Git\mingw64\bin\libiconv-2.dll'. Module was built without symbols.
'git.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Program Files\Git\mingw64\bin\libintl-8.dll'. Module was built without symbols.
'git.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Program Files\Git\mingw64\bin\libpcre-1.dll'. Module was built without symbols.
'git.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Program Files\Git\mingw64\bin\zlib1.dll'. Module was built without symbols.
'git.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Program Files\Git\mingw64\bin\libssp-0.dll'. Module was built without symbols.
'git.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
'git.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
The thread 0xa658 has exited with code 0 (0x0).
Unhandled exception at 0x00000000003658BE in git.exe: 0xC0000006: In page error reading location 0x00000000005F0000 (status code 0xC000000D).

Exception thrown at 0x00000000003658BE in git.exe: 0xC0000006: In page error reading location 0x00000000005F0000 (status code 0xC000000E).
Exception thrown at 0x00007FF95C70C605 (KernelBase.dll) in git.exe: 0x40010005: Control-C.

Exception thrown at 0x00007FF95C70C605 (KernelBase.dll) in git.exe: 0x40010005: Control-C.

The thread 0x8abc has exited with code -1073741510 (0xc000013a).
The thread 0x6e84 has exited with code -1073741510 (0xc000013a).
The thread 0xa680 has exited with code -1073741510 (0xc000013a).
The thread 0x9d9c has exited with code -1073741510 (0xc000013a).
The thread 0x7f74 has exited with code -1073741510 (0xc000013a).
The thread 0xa5d8 has exited with code -1073741510 (0xc000013a).
The thread 0x102c has exited with code -1073741510 (0xc000013a).
The program '[33360] git.exe' has exited with code -1073741510 (0xc000013a).
`

**Comment by dscho** [comment]
Yes, Git for Windows is compiled with the GNU C Compiler, and therefore does not have debug symbols that are usable by Visual Studio.

You *could* of course [compile Git for Windows with Visual Studio](https://github.com/git-for-windows/git/wiki/Compiling-Git-with-Visual-Studio) yourself, which would make debugging a lot easier.

**Comment by ambrt** [comment]
@dscho Ok. I compiled suggested version. The git have error again . The debugger asks to break or continue. Continue points back to same  error so only option is to break.

The diagnostic tools show "Stopped at Exception" and  points to "the next statement  to be executed" on line 696 of sha1_file.c
```
696	if (hdr->idx_signature == htonl(PACK_IDX_SIGNATURE)) {
697		version = ntohl(hdr->idx_version);
698		if (version < 2 || version > 2) {
...			munmap(idx_map, idx_size);
			return error("index file %s is version %"PRIu32
				     " and is not supported by this binary"
				     " (try upgrading GIT to a newer version)",
				     path, version);
		}
	}
```

Can i provide something more?

**Comment by dscho** [comment]
> Can i provide something more?

Hopefully you can use the debugger in the intended way: to debug. If you expect me to figure this out while you drive the debugger, it will get very frustrating for both of us, very quickly.

In the line 696, you see that `hdr->idx_signature` is compared to something, and the exception should also be visible somewhere (you did not say); I would expect this to be an access violation (0xC0000005) and `hdr->idx_signature` to point to an invalid memory location (again, you should be able to verify this by adding a "watch" to the "variables" window/view).

If this suspicion turns out to reflect reality (which I hope it does not), then the fault is squarely with WinSshFs() for handling `MapViewOfFileEx()` requests incorrectly.

**Comment by ambrt** [comment]
Ok, thanks for replying. I see it could be cumbersome to do debugging like that.<br>
I'll post what i think might be related but if it's not - the issue is not that hot for me to solve. So maybe someone with time on his hands could look inside and figure it out on his own.


The exception output:

> Exception thrown at 0x00007FF783BB0722 in git.exe: 0xC0000006: In page error reading location 0x000001ABD04A0000 (status code 0xC000000D).
> Unhandled exception at 0x00007FF783BB0722 in git.exe: 0xC0000006: In page error reading location 0x000001ABD04A0000 (status code 0xC000000D).


The variables:

```
fd	4	int
hdr	0x000001abd04a0000 {idx_signature=??? idx_version=??? }	pack_idx_header *
    idx_signature	<Unable to read memory>	
    idx_version	        <Unable to read memory>	
idx_map	0x000001abd04a0000	void *
```

When i watch the `idx_signature` i get:
`		(hdr)->idx_signature	<Unable to read memory>	`

**Comment by dscho** [comment]
> When i watch the idx_signature i get:
> (hdr)->idx_signature <Unable to read memory>

This is supposed to be memory-mapped [according to the code](https://github.com/git-for-windows/git/blob/v2.12.2.windows.2/sha1_file.c#L697-L711):

```c
	idx_map = xmmap(NULL, idx_size, PROT_READ, MAP_PRIVATE, fd, 0);
	close(fd);

	hdr = idx_map;
	if (hdr->idx_signature == htonl(PACK_IDX_SIGNATURE)) {
		version = ntohl(hdr->idx_version);
		if (version < 2 || version > 2) {
			munmap(idx_map, idx_size);
			return error("index file %s is version %"PRIu32
				     " and is not supported by this binary"
				     " (try upgrading GIT to a newer version)",
				     path, version);
		}
	} else
		version = 1;
```

The `xmmap()` function wraps `mmap()` which in turn is implemented in [`compat/win32mmap.c`](https://github.com/git-for-windows/git/blob/v2.12.2.windows.2/compat/win32mmap.c), boiling down to the Win32 API call:

```c
	temp = MapViewOfFileEx(hmap, prot == PROT_READ ?
			FILE_MAP_READ : FILE_MAP_COPY, h, l, length, start);
```

If that call would fail (`temp == NULL`), we would return a failure and `xmmap()` would `die()` with an error message.

So it looks as if WinSshFs claims success incorrectly, pretending that it memory-mapped the file, but in reality having failed to do so.

This is not a bug in Git for Windows.
