### ISSUE TITLE
cannot extract PortableGit-2.12.2.2-64-bit.7z.exe from command line

### ISSUE THREAD

**Issue by nodirt** [git-for-windows/git#1144]
since the switch of Portable Git to the "[custom-built SFX that is based directly on 7-Zip's SFX](https://github.com/git-for-windows/7-Zip)" in release 2.12.2.2, an attempt to extract the archive from the command line crashes:

    PortableGit-2.12.2.2-64-bit.7z.exe -y -o"C:\\git"

The same switches work for the previous release (2.12.2).

I can install the latest release by running in Explorer just fine though.

**Comment by dscho** [comment]
Thank you for the report. I hope you have some C++ skills, as Git for Windows really needs help on that front: apart from the `-y` option, no command-line option supported by the previous (now long-unsupported) SFX has been ported to the new one.

Just clone https://github.com/git-for-windows/7-Zip in your Visual Studio (the free Community version will do nicely), open `CPP\7zip\Bundles\SFXSetup\SFXSetup.dsw`, switch the configuration to `ReleaseD` and build.

Once that works, the code to refactor is here: https://github.com/git-for-windows/7-Zip/blob/43ba45400bab95ec6d8817fef908508a90d55e62/CPP/7zip/Bundles/SFXSetup/SfxSetup.cpp#L159-L164

**Comment by gucong3000** [comment]
+1 for me

**Comment by dscho** [comment]
@gucong3000 are you prepared to do something about it? I don't have the time, but I will make time to mentor you if you do have the time.

**Comment by gucong3000** [comment]
@dscho 
I do not have the experience of C/C++ programming, I usually use JS, but I would like to try.

**Comment by dscho** [comment]
Sorry, I dropped the ball.

I had described a _little_ bit in https://github.com/git-for-windows/git/issues/1094 what needs to be done, but I fear that it will take quite a bit of effort to even learn your way around Visual Studio enough to work on this.

**Comment by dscho** [comment]
I fixed this in https://github.com/git-for-windows/build-extra/commit/ef78e61c865379ce2c07ec3b7fc01c6c930a054d. You will be able to test it in the next [snapshot](https://wingit.blob.core.windows.net/files/index.html).
