### ISSUE TITLE
post-install.bat ignores errors in .post scripts

### ISSUE THREAD

**Issue by nodirt** [git-for-windows/git#1147]
Running [post-install.bat](https://github.com/git-for-windows/build-extra/blob/4e5fff3d0bfb482b08edfd0d3cf5079caf095f4e/post-install.bat) from the [downloaded SFX archive](https://github.com/git-for-windows/git/releases/tag/v2.12.2.windows.2) may print errors, such as

    mkdir: cannot change permissions of '/dev/shm': Permission denied
    mkdir: cannot change permissions of '/dev/mqueue': Permission denied

but the post-install.bat does not check exit codes of the .post script executions, thus it ignores the errors

Is this expected?

**Comment by fourpastmidnight** [comment]
I believe this happens if this script is not ran with elevated permissions.

**Comment by nodirt** [comment]
Thanks. The issue here is that the script ignores the errors, not that the errors exist.

**Comment by nodirt** [comment]
further investigation indicates that the line `@DEL post-install.bat` in the post-install.bat always causes non-zero exit code, so I assume that the post-install.bat's exit code is ignored in the downloaded SFX archive too

**Comment by nodirt** [comment]
btw, I run with elevated permissions. I've just checked my another installation that I got by installing not-from-command-line and the result is the same: both `/dev/shm` and `/dev/mqueue` are Folders, as opposed to System Files, when looked at via Explorer.

**Comment by dscho** [comment]
The chmod cannot succeed, due to file system incompatibilities with the POSIX expectations of the post-install/ scripts. The bug is in MSYS2, actually, for not suppressing those commands: https://github.com/Alexpux/MSYS2-packages/blob/daef5ae97e50362ae621535bd68accf41d4a29af/filesystem/01-devices.post#L56

**Comment by nodirt** [comment]
Can you confirm that the SFX exe ignores non-zero exit code by post-install.bat? We run post-install.bat ourselves, but we need to know if it is OK to ignore its non-zero exit code.

**Comment by dscho** [comment]
> Can you confirm that the SFX exe ignores non-zero exit code by post-install.bat?

Yes, it has to, for the reason you identified: the `post-install.bat` script wants to delete itself in the end (and that causes a problem after it succeeded in doing it, because then the script that is still running is no longer there).

**Comment by nodirt** [comment]
thank you
