### ISSUE TITLE
Terminal gets "stuck" when there is lots of output from a command

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#1148]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git ls-files --stage
```
 - What did you expect to occur after running these commands?

Lots of output, followed by the end of that command, followed by the terminal waiting for next input/command.

 - What actually happened instead?

Terminal gets "stuck" after lots of output. Stuck here means no input is accepted and the "$" does not appear (for entering the next command). I have to CTRL+C to cancel so that I can enter the next command.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Example repo where I'm able to reproduce the issue: `git@gitlab.kitware.com:cmake/cmake.git`

Note I have seen this issue happen with `git add` as well, when adding a boat load of files. I think the issue is specific to lots of output in the terminal from a single command.

**Comment by dscho** [comment]
In a quick test, I could not reproduce this. Maybe other people can.

**Comment by alegrigoriev** [comment]
What happens looks like the shell issues the prompt before all output from the program is put on the screen. This means, the program's stderr/stdout pipe did still contain data at the time the shell printed the prompt. If you scroll the console back, you'll find the prompt amidst the program's spew.

To repro, run git ls-tree -r HEAD on git/git repo. In my test, the prompt got printed some 1500+ lines back, which was 132K of text!

**Comment by dscho** [comment]
@alegrigoriev can you still reproduce that issue?

**Comment by Abdulmanahtalib** [comment]
Thankyou

**Comment by dscho** [comment]
> To repro, run git ls-tree -r HEAD on git/git repo. In my test, the prompt got printed some 1500+ lines back, which was 132K of text!

This works here, without any problem, with Git Bash of Git for Windows v2.21.0.

I actually get more like 3,500+ lines and >280kB. But no get stuck, sorry.

**Comment by Abdulmanahtalib** [comment]
Tq
