### ISSUE TITLE
extremely slow startup on Windows 10 due to fetching printers from invalid key

### ISSUE THREAD

**Issue by Hirato** [git-for-windows/git#1150]
I have followed instructions in the wiki, and it suggested that I set the `set -x` option in the `/etc/profile` file so see where it hangs.

The lines that caused the stall were these inside the provided `/etc/profile`

	# Define default printer
	p='/proc/registry/HKEY_CURRENT_USER/Software/Microsoft/Windows NT/CurrentVersion/Windows/Device'
	if [ -e "${p}" ] ; then
	  read -r PRINTER < "${p}" 
	  PRINTER=${PRINTER%%,*}
	fi
	unset p

I had a look inside the registry, and the correct registry key defining the printers is `HKEY_CURRENT_USER/Software/Microsoft/Windows NT/CurrentVersion/Windows/Devices` (note the 's' at the end).
I substituted in the correct key and startup was pretty much instant, in other words it's stalling for nearly a minute during startup trying to read a registry key that doesn't even exist.

version used was `2.12.2.windows.2`

**Comment by dscho** [comment]
Oh wow. That's pretty horrible.
