### ISSUE TITLE
weird bash issue in git-for-windows 2.12.2 64bit

### ISSUE THREAD

**Issue by jsfaint** [git-for-windows/git#1153]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64-bit LTSB

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

git-for-windows 2.12.2.2 32-bit works well.
git subtree command not works on 64-bit

```bash
$  git subtree pull --prefix lib/ http://172.21.73.37:3000/serial/libtc.git master
Unexpected option: pull
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
#!/bin/bash

file="Neovim.zip"
echo $file | awk -F '.' '{print $1}'
nvim=$(echo $file | awk -F '.' '{print $1}')
echo "nvim=$nvim"
```
 - What did you expect to occur after running these commands?

Should print text below
```bash
Neovim
nvim=Neovim
```

 - What actually happened instead?

Only get text below
```
Neovim
nvim=
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It's not s git related issue, but in the bash of git-for-windows, and it's 64-bit only issue
On git-bash 32-bit it works fine
![image](https://cloud.githubusercontent.com/assets/571829/25520284/fc1a73d8-2c2d-11e7-83dd-09c12d993320.png)

But on git-bash 64-bit, I get this
![image](https://cloud.githubusercontent.com/assets/571829/25520328/1c36e1a6-2c2e-11e7-8fe8-06966a8be2c5.png)

**Comment by dscho** [comment]
As I stated in Gitter: this does not reproduce for me... :frowning_face:

**Comment by jeffhostetler** [comment]
You might try adding:
set -x
set -v
to your script (or interactive shell) and see if it helps debug the problem.

**Comment by jsfaint** [comment]
@dscho @jeffhostetler Thank you~
It's the weekend now, I'll response debug result later.
Sorry, I don't have windows environment in home.😂

**Comment by jsfaint** [comment]
I get the following  result after add `set -x` and `set -v`

```bash
$ ./test.sh
+ set -v

file="Neovim.zip"
+ file=Neovim.zip
echo $file | awk -F '.' '{print $1}'
+ echo Neovim.zip
+ awk -F . '{print $1}'
Neovim
nvim=$(echo $file | awk -F '.' '{print $1}')
+ nvim=
echo "nvim=$nvim"
+ echo nvim=
nvim=
```
The $nvim variable is still null.

**Comment by dscho** [comment]
Hmm. Could you patch this script so it calls `/usr/bin/awk.exe` instead of `awk`? This would verify that there is no different awk in action. Further, you could try running this through `strace -o /tmp/awk.log ...` and then see 1) whether it works around the problem or 2) `/tmp/awk.log` has anything meaningful to help us figuring this one out.

**Comment by jsfaint** [comment]
@dscho Replace `awk` with `/usr/bin/awk.exe` still with no lucky.
The interesting thing is `echo $(echo $file | /usr/bin/awk.exe -F '.' '{print $1}')` has value, but when this value assigned to a variable, the variable become null.

When I run strace, I got segmentation fault
```
$ strace.exe ./test.sh
      1 [main] strace (177720) C:\Program Files\Git\usr\bin\strace.exe: *** fatal error - cygheap base mismatch detected - 0x1802FF408/0x28EF408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Segmentation fault
```

**Comment by dscho** [comment]
> strace.exe ./test.sh

Can you run `strace.exe -c "echo Hello"` successfully?

**Comment by jsfaint** [comment]
strace doesn't work at all

```
$ strace.exe -c "echo hello"
      1 [main] strace (250220) C:\Program Files\Git\usr\bin\strace.exe: *** fatal error - cygheap base mismatch detected - 0x1802FF408/0x29DF408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
C:\Program Files\Git\usr\bin\strace.exe: unknown option -- c
Try `strace.exe --help' for more information.
```

I reinstalled git-for-windows, the issue is still exist.

**Comment by dscho** [comment]
> [main] strace (253172) C:\Program Files\Git\usr\bin\strace.exe: *** fatal error - cygheap base mismatch detected - 0x1802FF408/0x2A3F408. This problem is probably due to using incompatible versions of the cygwin DLL.

Hrm. This is typically a symptom for the dreaded "DLL base address problem". Or for the presence of any of the [applications known to interfere with Cygwin's POSIX emulation](https://cygwin.com/faq/faq.html#faq.using.bloda).

If it is the DLL base address, you may be able to fix this by following the advice in https://github.com/git-for-windows/git/wiki/32-bit-issues#adjusting-msys-20dlls-address-range-manually (never mind that the page suggests this is a 32-bit only problem). Maybe you can try that workaround in a portable Git at first, just to see whether it fixes things on your side?

**Comment by jsfaint** [comment]
I download `PortableGit-2.12.2.2-64-bit.7z.exe` package, and tried portablegit
The behavior is same with installed one

May there are some issues in windows 10 LTSB, It's not issue in git-for-windows.
I remembered  the DLL not working issue happened in an early edition of windows 10.

**Comment by dscho** [comment]
@jsfaint Could you follow the guidelines at https://github.com/git-for-windows/git/wiki/32-bit-issues#adjusting-msys-20dlls-address-range-manually to "rebase the DLLs"?

**Comment by jsfaint** [comment]
I rebased the DLLs, but nothing changed
![image](https://cloud.githubusercontent.com/assets/571829/25731033/21b0f422-3175-11e7-94d6-04957708a915.png)

**Comment by WalkreHuang** [comment]
nice

**Comment by MartyMacGyver** [comment]
I've been using `Git-2.11.1-64-bit` on Windows 7 Pro for a while now, and decided to try `Git-2.13.0-64-bit` tonight. I also got a "cygheap base mismatch" error similar to what's above (it wasn't `strace` but some other cygwin component), which I've never seen before. I updated my Cygwin (x64) install just in case, and even rebooted - same problem.

I downgraded to 2.11.1-64 and the problem immediately went away. I checked here to see if something similar had been reported and found this.

Further specs:

```
Microsoft Windows [Version 6.1.7601]

Path Option: Cmd
Plink Path: C:\Program Files\TortoiseGit\bin\TortoisePlink.exe
SSH Option: Plink
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

**Comment by piotrczarnota** [comment]
I have the same issue as @jsfaint 
OS is Microsoft Windows Enterprise [Version 10.0.14393] and Git for Windows version I tested is `Git-2.11.1-64-bit ` and `Git-2.13.0-64-bit`. Git is install in folder C:\Git.

When I run script:
`file="Neovim.zip"
echo $file | awk -F '.' '{print $1}'
nvim=$(echo $file | awk -F '.' '{print $1}')
echo "nvim=$nvim"`

On both version of GIT output is  the same:
`Neovim
nvim=
`
But I have additional result. In current directory file `bash.exe.stackdump` was created:

`Exception: STATUS_STACK_OVERFLOW at rip=7FFB40B0AAB7
rax=0000000000001058 rbx=00000000000E0DF0 rcx=48CC4072AC0F0000
rdx=0000000000000001 rsi=00000000000DFDDC rdi=0000000000000001
r8 =00000000000C7ED4 r9 =000000000000001B r10=00000000FFFFA000
r11=00000000FFE03EB0 r12=0000000000000424 r13=00000000000DFDC0
r14=0000000000000000 r15=0000000000000000
rbp=00000000000E0DF0 rsp=00000000FFFFB5A0
program=C:\Git\usr\bin\bash.exe, pid 10972, thread unknown (0x2658)
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000000E0DF0  7FFB40B0AAB7 (00180010018, 000000C22C8, 000000DFDDC, 7FFB00000002)
000000E0DF0  7FFB3CC0637A (000000C22C8, 000000DFDDC, 7FFB00000002, 000FFFFB980)
000000E0DF0  7FFB3CC0813E (000000E0E22, 000FFFFB9E0, 00000000420, 000000E002C)
000FFFFB9E0  7FFB3CC08836 (000FFFFB8C0, 00000000208, 00000000000, 00180279300)
000FFFFB9E0  7FFB3DD89FF6 (00000000001, 00000000000, 000FFFFBCB0, 00000000001)
000FFFFB9E0  7FFB3E23BF13 (000FFFFBB00, 00000000000, 00000000420, 00000000001)
000FFFFB9E0  001800AADAB (000FFFFBAA0, 00000000030, 00000000000, 00000000000)
000FFFFBB20  001800AB955 (006000EE3D0, 00000000000, 0010040FDFE, 00000000001)
00000000000  0018011B2AB (006000EE3D0, 00000000000, 0010040FDFE, 00000000001)
00000000000  0000259E458 (00000000000, 0010040FDFE, 00000000001, 00000080002)
00000000000  001004E172E (0010040FDFE, 00000000001, 00000080002, 00000080000)
00000000000  006000EE3D0 (0010040FDFE, 00000000001, 00000080002, 00000080000)
End of stack trace`

**Comment by piotrczarnota** [comment]
I find a workaround that work for me.
I install a 32-bit version of Git (exactly `Git-2.13.1-32-bit`) and problems go away. Scripts output is as I expect and I haven't `bash.exe` `STATUS_STACK_OVERFLOW` problem anymore.

But in x64 version (`Git-2.13.1-64-bit') is still the same problem that I mentioned above.

**Comment by K73SK** [comment]
@piotrczarnota 's suggestion fixed my issue (Installing 32-bit instead of 64-bit). Same version (2.13.1.2). This problem has been having since ever I tried starting from Git 2.10.1 to 2.11 and 2.12.1.. It's been around for quite a long time, frankly.

**Comment by nicorac** [comment]
I have the same issue with **Git-2.13.2-64-bit.exe**.

Running this command directly at the bash prompt will generate the bash.exe.stackdump file:
```
$ test=$(echo "foo bar" | wc -w); echo "test=$test"
test=

$ cat bash.exe.stackdump
Exception: STATUS_STACK_OVERFLOW at rip=00076D1B887
rax=0000000000001058 rbx=00000000002D5410 rcx=21A28E3AD9950000
rdx=0000000000002000 rsi=00000000002D43FC rdi=0000000000000001
r8 =000000000000000D r9 =000000000000001A r10=00000000FFFFA000
r11=00000000FFE03CE0 r12=0000000000000424 r13=00000000002D43E0
r14=0000000000000000 r15=0000000000000000
rbp=00000000002D5410 rsp=00000000FFFFB420
program=C:\Git\usr\bin\bash.exe, pid 10212, thread unknown (0x1A30)
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000002D5410  00076D1B887 (00180010018, 00000282754, 000002D43FC, 000FFFFB540)
000002D5410  7FEFC6E637A (00000282754, 000002D43FC, 000FFFFB540, 000FFFFB7C0)
000002D5410  7FEFC6E813E (000002D5442, 00000000420, 00000000420, 000002D464C)
00000000420  7FEFC6E8836 (FFFFFFFFB8797400, 00000000000, 00000000001, 00180277C20)
00000000420  00076BD064C (00000000020, 00000000020, 00000000000, 00000000001)
00000000420  001800AA372 (000FFFFB8E0, 00000000000, 7FE00000000, 00000000000)
000FFFFB960  001800AAF15 (00100410FBB, 00000000001, 00600053F60, 001004E6740)
000FFFFBB60  0018011A8FB (00100410FBB, 00000000001, 00600053F60, 001004E6740)
000FFFFBB60  0000224E458 (00100410FBB, 00000000001, 00600053F60, 001004E6740)
End of stack trace
```

It seems to me the error relies in variable assignment, because the `$(...)` command is executed correctly:
```
$ $(echo "foo bar" | wc -w)
bash: 2: command not found
```
bash tries to run "2" which is the output of `$(...)` subcommand...

**Comment by kgybels** [comment]
This reminds me of the MacType problem: https://github.com/git-for-windows/git/issues/704#issuecomment-207587879. Any of you using MacType?

**Comment by K73SK** [comment]
@kgybels Negative

**Comment by piotrczarnota** [comment]
@kgybels I don't use MacType.

**Comment by nicorac** [comment]
@kgybels No MacType here too, Win7-x64 fully updated.

**Comment by MartyMacGyver** [comment]
I've been getting the following error in recent x64 releases (as noted way above) when I run git-bash from the desktop link:

      1 [main] getent (15184) C:\cygwin\bin\getent.exe: *** fatal error - cygheap base mismatch detected - 0x1802FF408/0x180304408.
    This problem is probably due to using incompatible versions of the cygwin DLL.

My Cygwin install is also x64.

I did the usual "DLL base address" dance, but that didn't help.

I reinstalled (with the concomitant reboots), and made sure it should only work when the git-bash link is used (git for windows isn't anywhere in my path). Still, this error.

Updated Cygwin - latest DLL. Not sure why git is using a cygwin DLL from over a year ago but ok, still should've been a problem in 2.10.

But if I remove Cygwin from my path, it works. Which is nice but unacceptable - and besides, git-bash should put itself first in the path to prefer its own command set, thus never seeing Cygwin. Which is what it appears to be doing, except this `getent` thing.

So I opened a cmd shell, removed Cygwin from the path, and started git-bash from that (as it inherits the shell environment that way). Problem's gone! And I can see cygwin is nowhere in its path now...

But wait - if `getent` is nowhere to be found if Cygwin is absent, and `git-bash` is happy _even if it cannot find it_... why is `git-bash` trying to run `getent` at all? **If you try to run things within git-bash that are coming from Cygwin *only* then sure, that may cause problems, but `git-bash` itself shouldn't be dependent on unix-like things that git-for-windows never installed in the first place.**

I am starting to think that this `getent` thing is a relatively recent change since 2.10 - either it used to be installed and now it's not, or git-bash is depending on it inappropriately in a way it didn't before.

Can someone point me to the source code for `git-bash`?

**Comment by MartyMacGyver** [comment]
Update: I've opened #1226 regarding my fatal error with `getent` issue on opening `git-bash`, which appears to be a bit different from what's happening here (but which would affect anyone who has Cygwin in their path (even without git-for-windows in the path) and then runs `git-bash` here.

The commit that causes this appears to be:
https://github.com/git-for-windows/git-sdk-64/commit/abcb6463557a08597c24794a949e95e6a70b37fe

@dscho - I don't think I can tag you in #1226 but I'd appreciate if you can give some feedback on the issue there when you have time.

**Comment by K73SK** [comment]
Turns out we had some security software that injected a dll into "bash.exe" - removing that dll injection allowed it to be resolved for us.

**Comment by dscho** [comment]
> Turns out we had some security software that injected a dll into "bash.exe" - removing that dll injection allowed it to be resolved for us.

I should have thought about this first :man_facepalming:

Is your security software listed here: https://cygwin.com/faq/faq.html#faq.using.bloda? @jsfaint maybe you have the same issue, some DLL injection gone wrong?

**Comment by nicorac** [comment]
I have both AVAST and COMODO Firewall :disappointed:
Will try to add bash.exe to exclusion list...

**Comment by K73SK** [comment]
@dscho It's not on that list, no (which is why I didn't jump to that conclusion immediately, although I should have). "strace" was able to help me trace to the dll on the stack trace that was injecting to the forked process.

The software was "BeyondTrust PowerBroker"

**Comment by dscho** [comment]
Thanks for the feedback!

**Comment by piotrczarnota** [comment]
Thanks @dscho.
I ran in my case:
`strace dirname "$(echo "$0" | sed -e 's,\\,/,g')"`
and found culprit.
After uninstall **Comodo Firewall** all works fine!

**Comment by dscho** [comment]
@piotrczarnota thank you for persisting, and for reporting back! May your finding help others, too.

**Comment by dscho** [comment]
Okay, I'll just assume that software listed in https://cygwin.com/faq/faq.html#faq.using.bloda is the culprit even in @jsfaint's case.

**Comment by jsfaint** [comment]
I uninstalled mactype, it works now. 😭 
Maybe I can close this issue now.

Thanks for the help 👍

**Comment by nicorac** [comment]
@piotrczarnota thanks for yor finding and reporting, but uninstalling it is not an option for me.
@jsfaint isn't there a way to warn users about injection?

**Comment by dscho** [comment]
@jsfaint thanks for your feedback!

> uninstalling it is not an option for me.

@piotrczarnota there *may* be a way to handle MacType in Cygwin's runtime. This will require a lot of work, and since you are not paying anyone to work on that, it is safe to assume that you will have to do most of the bidding (or pay somebody to do that).

**Comment by jsfaint** [comment]
@dscho For mactype, there is a blacklist which can disable some specified process for mactype.
