### ISSUE TITLE
git hangs after resume from sleep, renders Rstudio session unresponsive

### ISSUE THREAD

**Issue by ripkrizbi** [git-for-windows/git#1154]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None. Fairly fresh DELL laptop with OEM Win10, Installed MS Office and R/Rstudio

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Open Rstudio; open/create a versioned project; send computer to sleep with the Rstudio session open.
After computer resumes, the R console is unresponsive and Rstudio GUI cannot be closed. The only thing that helps is the 'kill process tree' from within process explorer task manager. this kills the Rstudio, R session and one of the two git processes. One remains hanging and cannot be killed.
This happens ONLY on versioned projects. If I just open Rstudio and sleep/resume the computer, eveything works normally.
```
 - What did you expect to occur after running these commands?

I expected to return to normally using Rstudio session where I left off.

 - What actually happened instead?

R console unresponsive, Rstudio can be kille through task manager only

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

not specific to repositories

**Comment by dscho** [comment]
What are the command line parameters of that process (you may want to use something like `wmic process list` to find out)?

**Comment by ripkrizbi** [comment]
Hi, the process tree looks like this:


![image](https://cloud.githubusercontent.com/assets/1372240/26755918/9fd240d4-4897-11e7-98f1-abe000886fe0.png)

The last (child) git process hangs after resume from sleep.

**Comment by ripkrizbi** [comment]
Another potentially useful info. After I try to kill the entire process tree, the child git process that remains hanging  even manages to choke the Process Explorer - I am unable to view the process properties. But the property window at least shows some information:

![image](https://cloud.githubusercontent.com/assets/1372240/26755970/96a96982-4898-11e7-8b5d-9420f52d092c.png)

It seems the process hangs at Wait: WrPushLock. Could be useful...

**Comment by dscho** [comment]
This looks funny. Why is RStudio spinning up a `git status --porcelain` that does not terminate just about immediately? Maybe RStudio is not consuming all of the output? Or not closing the handle?

**Comment by ripkrizbi** [comment]
Beats me. Should I open up a ticket with the RStudio people?
Another possibly relevant piece of info - the local repo is on Dropbox-shared folder.

**Comment by dscho** [comment]
> Another possibly relevant piece of info - the local repo is on Dropbox-shared folder.

Maybe you get a chance to tes with a purely local folder.

**Comment by dscho** [comment]
> Maybe you get a chance to tes with a purely local folder.

That should have read "test", of course. And I think it would really have made sense to test with a purely local folder.

@ripkrizbi if you are still interested in figuring this out, please feel free to update us with your progress in pinpointing this issue further. In the meantime, I will close this ticket to take off some pressure.
