### ISSUE TITLE
Installation size - This doesn't look right

### ISSUE THREAD

**Issue by cst6** [git-for-windows/git#1155]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
I noticed 116 exe files each 2,149,608 bytes long which are identical (except for their names) that's just in C:\Program Files\Git\mingw64\libexec\git-core alone.

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Installation of Git-2.12.2.2-64-bit.exe
```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 Ultimate SP1
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Default on all.
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (though this is not relevant to the problem)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
A straight forward installation, shows the problem. 
```
 - What did you expect to occur after running these commands?

Installation size about 220 MB

 - What actually happened instead?

Installation size 487,475,593 bytes

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://git-for-windows.github.io/

**Comment by nalla** [comment]
If I remember correctly, that it's because we are creating hard links when copying the git wrapper and git itself to the many places. Hard links under windows double the _visual_ disk usage despite the fact that it is quite the opposite.

**Comment by cst6** [comment]
OK I can see they're all linked now.
