### ISSUE TITLE
Windows IoT Core - ARM compile

### ISSUE THREAD

**Issue by computeronix** [git-for-windows/git#1157]
Are there any plans to compile git for windows for arm?  For example Windows 10 IoT Core on RPI2/RPI3 is ARM based and as long as the git.exe is recompiled to support ARM on Windows then the exe can run.

**Comment by computeronix** [comment]
As an example node js is being worked on to be supported in Windows 10 IoT Core arm and when I attempt to run a standard install within node is says missing git, which installing git-windows / git does not work   https://github.com/nodejs/node-chakracore/releases

**Comment by shiftkey** [comment]
I think the dependency on MSYS for a [build environment](https://github.com/git-for-windows/git/wiki/Building-msys2-runtime) and runtime is going to be an limitation here.

I've not looked into what's available or possible in terms of targeting Windows 10 IoT Core, but apparently there's [some portability tools](https://developer.microsoft.com/en-us/windows/iot/docs/iotcoreportingtool) to investigate this.

@computeronix are you interested in testing that and seeing what information it yields?

**Comment by dscho** [comment]
MSYS2 is a problem in that respect, sure. But not only for the build environment. Indeed, the problem with Git is that it is *not* just portable C. It is also "portable" Unix shell and Perl scripts.

So I fear that you are asking for something that is a *lot* larger than you anticipated, @computeronix.

The easiest way forward would most likely be to cross-compile using Visual Studio, and use only those parts that do not require scripts. Nor OpenSSH...

In any case, I fear that this ARM port is outside this project's resources, realistically...

Unless, @computeronix, you can invest in this?

**Comment by computeronix** [comment]
I don't mind testing anything but yes sounds like it is bigger than what I had imagined!  Thanks for the all the response though and I am glad this was reviewed

**Comment by dscho** [comment]
Yeah, testing this is easy. Getting it even close to build, let alone to pass the test suite, is not.

Therefore I will close this as "too big a task" until the time anybody interested enough comes along.
