### ISSUE TITLE
Unable to continue rebase with submodule conflict

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#116]
First off, the whole context of the discussion can be found here:
http://www.mail-archive.com/git@vger.kernel.org/msg69044.html

During a non-interactive rebase, if I have a commit that only contains a change to a submodule *and* the rebase stops at this commit with a conflict, I am unable to do `git rebase --continue` after resolving the conflict.

I started the discussion on the Git mailing list originally. They found that the "problem" commit is here:
https://github.com/msysgit/git/commit/fbe1f041f9890f4b2eea3ed2265f82c9b845a39b

I'd like @dscho to comment on this, I'm not sure how this should be addressed.

**Comment by dscho** [comment]
I reverted that commit: 505857c
