### ISSUE TITLE
HOME environment variable is not the correct one

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#1160]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Windows 7 professional,64 bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git config --global core.qutoepath off


```
 - What did you expect to occur after running these commands?

turn off the quotepath

 - What actually happened instead?

error: could not lock config file T://.gitconfig: Permission denied

I find the environment variable HOME was set as HOME=T:\ ,found this by TortoiseGit 
But the environment variable was showed in readonly tempfile,I can not edit it.
![environment variable](https://tortoisegit.org/docs/tortoisegit/images/SettingsMain.png)

I remember int the old version(do not know the exact version number),the default HOME path is set to the user folder.
Why the new version did not keep this rule?
The T:// disk is actually a net disk,and I do not have permission to write it.

**Comment by PhilipOakley** [comment]
You will need to give more details about what you saw, what you think is wrong, what should the right answer be (in your view).

Also search the issues list for the closed items regarding the HOME variable and how it is set. It is often misunderstood.

**Comment by chucklu** [comment]
sorry,I am still updating the detail

**Comment by dscho** [comment]
> sorry,I am still updating the detail

Please don't do that. Wait with hitting the button until you filled in the details.

I will not get notified by GitHub when you update details, I only get notified about this super unhelpful bug report that says pretty much nothing.

Regarding the HOME variable: unless defined by yourself (and this is the fix I suggest: define it yourself), it is inferred automatically by concatenating the HOMEDRIVE and HOMEPATH environment variables, falling back to the USERPROFILE environment variable if `$HOMEDRIVE$HOMEPATH` does not specify an accessible directory.

**Comment by chucklu** [comment]
@dscho  sorry,I am not familiar with the markdown style.I will learn it.

I have check the HOMEDRIVE variable,it was setted by our company's colleague.The  HOMEDRIVE is T://,but I can not write to it at the root directory.I can only access the folder named "public" under the
T://.

I would like to set the HOME variable by myself,but I do not know how to define it.

**Comment by chucklu** [comment]
I have check the permission of my computer account
```
$ ls -al
total 92
drwxr-xr-x 1 clu 1049089 0 Apr 24 17:04 ./
drwxr-xr-x 1 clu 1049089 0 May  9 18:35 ../
drwxr-xr-x 1 clu 1049089 0 May  9 12:34 public/

**Comment by dscho** [comment]
> I would like to set the HOME variable by myself,but I do not know how to define it.

See e.g. https://www.computerhope.com/issues/ch000549.htm. You will want to set it the *user* section, not the *system* one.

**Comment by chucklu** [comment]
![home environment variable](https://cloud.githubusercontent.com/assets/3004057/25879802/4c923f30-3566-11e7-8bf5-de1f38d8e094.PNG)
just config the HOME environment variable as %USERPROFILE% in user section
@dscho  thanks a lot
