### ISSUE TITLE
When i press Backspace it's not working

### ISSUE THREAD

**Issue by YurySosnov** [git-for-windows/git#1161]
backspace, up, down, left , right not working in git-bash (Win10). When i try press one of this keys making something strange: cursor going next position (as i press the "space"). It's very bad.

**Comment by shiftkey** [comment]
Please fill out the issue template as it asks for relevant information about your OS, installed version and reproduction steps that we need to understand the issue better.

**Comment by dscho** [comment]
And when you fill out the issue template (remember, this is not something we ask for fun, it is designed to reduce the frustration on both sides!) please also provide a dump of your environment variables (`env` in Git Bash; you may want to remove sensitive data, if any), in particular the value of the environment variable `TERM`.
