### ISSUE TITLE
UAC Prompt w/non-Admin Account Fails - Must right click Run As Admin

### ISSUE THREAD

**Issue by SgtSQL** [git-for-windows/git#1167]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git-2.13.0-64-bit.exe
```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win-10 x64 v1607
```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.14393] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

no results
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** Avast current and EMET 5.51 - most programs install correctly regardless of these tools **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Sometimes all 3 but not related to installer **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**
Launched installer in non-adm account; UAC prompted for elevation; failed writing to tmp folder in program files; issue existed in 2.12.0 also
Right clicked Run As Administrator; UAC elevated; install succeeded
**
```
 - What did you expect to occur after running these commands?

** expected install to work whether I clicked run as adm or launched the installer and expected it to elevate correctly with adm credentials
**

 - What actually happened instead?

** only right clicking run as administrator worked; most windows programs handle this UAC elevation correctly **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** NA **

**Comment by dscho** [comment]
Do you have any logs?

**Comment by SgtSQL** [comment]
I got this resolved. I don't remember the details anymore, but I think another tool had installed it's own copy of Git. It might have been Visual Studio. I think it was a path conflict causing the side by side versions to get confused.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dscho** [comment]
Thanks for clarifying.
