### ISSUE TITLE
Git LFS clone doesn't prompt credential input  if I use "wincred" as credential.helper

### ISSUE THREAD

**Issue by xming07** [git-for-windows/git#1169]
I  have issue to run "git lfs clone" command to download lfs tracked files  via https in the windows.
Platform: Windows7/10
Git: 2.12.2
Git LFS: 2.0.2
We use the [git-for-windows](https://git-for-windows.github.io/)  and use wincred as credential.helper

And I can not run  the git credentail fill   command.
```
$ git credential fill
host=github.com
protocol=https
**Username for 'https://github.com': error: failed to execute prompt script (exit code 1)`
fatal: could not read Username for 'https://github.com': No error**
```

The solution I find would be to set variable  in the git bash. Then it will prompt for username .

```
export DISPLAY=required
export SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
export GIT_ASKPASS=$SSH_ASKPASS
```

It works fine if I use [credential manager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows),

Is is a known issue  for Git itself? Or  is  any there  configuration I need to do  during git-for-windows installation.  

Thanks!
Louis

**Comment by dscho** [comment]
Isn't this a Git LFS issue that would be more appropriately reported at https://github.com/git-lfs/git-lfs/issues?

**Comment by xming07** [comment]
@dscho  I  can not figure out what is the root cause for this and also post it to git-lfs repository.
But the git credential fill command  fail not related to git-lfs.
I am wondering why it cannot  invoke the prompt script.
```
$ git credential fill
host=github.com
protocol=https
**Username for 'https://github.com': error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error**
```
'

**Comment by dscho** [comment]
Ah, so the MCVE was not yet really minimal?

The "failed to execute prompt script" error comes from here:

https://github.com/git-for-windows/git/blob/v2.13.0.windows.1/compat/terminal.c#L141

Which suggests that somehow the connection to MSYS2's `/dev/tty` was lost.

**Comment by dscho** [comment]
To be precise: it means that some sort of circumstance makes MSYS2 fail to read from the command line.

Please tell us more about your exact setup (it would have been better to fill out the issue reporting template than to delete it, it was carefully crafted to avoid unnecessary back-and-forth such as this one which is not only frustrating to you, but also to everybody else reading this bug tracker).

And please try to come up with the *bare* minimal, complete & verifiable example. That will go a long way of accelerating the resolution of this ticket.

**Comment by xming07** [comment]
Here is my steps to produce the issue.
1. I  just download and install the git-for-windows with default settings except not enabling git windows credential managers.
Git:2.12.2.windows.2
Platform windows 10
2. Then I manually config the credential.helper with wincred
git config --global credential.helper wincred.
3. The git credential fill command will go wrong without promopt username input.
$ git credential fill
host=github.com
protocol=https

**Comment by jasjuang** [comment]
@xming07  Were you able to resolve this problem? I ran into a really similar issue

**Comment by dscho** [comment]
> I just download and install the git-for-windows with default settings except not enabling git windows credential managers.

Can you reproduce this also with PortableGit? That would be much more minimal than requiring the installer.

> Git:2.12.2.windows.2

Does this reproduce with 2.13.0? And with the latest snapshot from https://wingit.blob.core.windows.net/files/index.html?

> git config --global credential.helper wincred

I take it that it would also work without `--global`; No need to mess up my configuration here.

**Comment by xming07** [comment]
@jasjuang  You can use "manager" instead of "wincred" as credential.helper or set the following  environment variables 
```
export SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
export GIT_ASKPASS=$SSH_ASKPASS
````

**Comment by xming07** [comment]
@dscho  Sure. I will try to use the latest version

**Comment by dscho** [comment]
Okay, so this is what I consider *almost* an MCVE:

1. use PortableGit v2.13.0
2. `git init` in a freshly created directory
3. `git config credential.helper ''` to reset the list of credential helpers
4. `git config --add credential.helper wincred` to add "wincred"
5. `printf "host=github.com\nprotocol=https\n" >fill.txt` to avoid having to type it over and over again
6. `DISPLAY=required SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass GIT_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass GIT_TRACE=1 git credential fill <fill.txt`

I say this is *almost* an MCVE because it is a minimal, verifiable example alright, but it *fails* to reproduce the described problem here. Instead of 

> **Username for 'https://github.com': error: failed to execute prompt script (exit code 1)
> fatal: could not read Username for 'https://github.com': No error**

(which I do not think was copy-pasted correctly because I do not see where those asterisks could come from), I get this output:

```
15:44:58.203175 git.c:369               trace: built-in: git 'credential' 'fill'
15:44:58.204676 run-command.c:369       trace: run_command: 'git credential-wincred get'
15:44:58.583800 git.c:594               trace: exec: 'git-credential-wincred' 'get'
15:44:58.584307 run-command.c:369       trace: run_command: 'git-credential-wincred' 'get'
15:44:58.615297 run-command.c:369       trace: run_command: 'D:/PortableGit-v2.13.0/mingw64/libexec/git-core/git-gui--askpass' 'Username for '\''https://github.com'\'': '
```

and this Tcl/Tk window:

![wincred-askpass](https://cloud.githubusercontent.com/assets/127790/26682637/7a1f1cac-46e1-11e7-900c-e1d90dbaffa1.png)

So it seems that there is something different going on here than on your side. And the issue reporting template would have helped trying to figure out differences that may be responsible for this.

As I do not have this information on my hands, however, I can stop here and be very happily punt the ball back into your court and let you investigate further.

**Comment by dscho** [comment]
> I ran into a really similar issue

@jasjuang it would probably make sense to describe your issue in a rather more verbose way.

**Comment by jasjuang** [comment]
@dscho I am referring to issue #1192 which I described in details.

@xming07 Understand that using `manager` will solve everything, but I am on a shared machine so giving access to whoever is using that machine to my repository is not desired. I unset `manager` and git prompts me for credentials and works when I am cloning a normal repository, but for a repository that has lfs files, it just fails directly without prompting me to enter credentials. Very similar to what you are reporting.

**Comment by rashid-softordi** [comment]
@tsupol 
**# Issue is SOLVED!**
_error: failed to execute prompt script (exit code 1) fatal: 
could not read Username for 'https://github.com': Invalid argument_    

1- Create a ssh key using Git Bash using following command

`ssh-keygen -t rsa -b 4096 -C "your-github@email.com" `

After running this command just install the by default options and enter the password balnk when it prompts. 

2- Then run the following commands to locate the public/private key generated from step1

`cd .ssh`

`cd ~/.ssh`

3- Then run the following command to view your public: 

`cat id_rsa.pub`

4- Copy your public key and go to  your GitHub account -> settings -> create a SSH and GPG keys then click new ssh key and past your public key in the in key text field.

5- Verify your public key using Git Bash by running the following command:

`ssh -vT git@github.com `

You will get output like this

> debug1: channel 0: free: client-session, nchannels 1
> Transferred: sent 3848, received 2040 bytes, in 0.2 seconds
> Bytes per second: sent 16032.4, received 8499.5
> debug1: Exit status 1
 
Then you no longer got "could not read Username for 'https://github.com': Invalid argument"

**Comment by dscho** [comment]
This issue became stale, so I'll close it. Should anybody show up who is willing to work on debugging this issue: it is easy enough to re-open it. But it does not make sense to keep cluttering the issue tracker with open issues that nobody wants to work on.
