### ISSUE TITLE
sh.exe bash.exe won't randomly receive keystrokes

### ISSUE THREAD

**Issue by rezss** [git-for-windows/git#1172]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.0.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16199.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

latest Windows Insider Preview Build

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

C:\Program Files\Git\bin\bash.exe
C:\Program Files\Git\bin\sh.exe

This problem does not appear with the "default" git-bash.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Since the at least two last Windows 10 Insider Previews i have a wired issue regarding the bash.exe and sh.exe. Those bashes wont receive all/most of key inputs. At first it appears totally random for me, but it seems deterministic, e.g. if i enter the following key strokes:
```
[1][2][3][4][5][6][7][8][9][0]
```
 it does not show anything, if i press now `[Ctrl+C]`, a new line will appear, and the previous line shows `258`. With each time the same result...

PS: I do not know whats the different between the bash.exe and sh.exe is, but i have to use them if i want to embed the git bash into ConEmu/Cmder

**Comment by elieux** [comment]
See also Alexpux/Cygwin#36.

**Comment by Silentz0r** [comment]
@rezss @elieux 

Hi, Any workaround?

**Comment by elieux** [comment]
Working on it. But my first advice would be to use MinTTY, i.e. `git-bash`.

**Comment by rezss** [comment]
@Silentz0r start the sh.exe/bash.exe and enable the legacy mode. This will fix the issue. 
For more details see here: [Alexpux/Cygwin#36](https://github.com/Alexpux/Cygwin/issues/36)

**Comment by elieux** [comment]
People have reported that the issue no longer exists in Insider build 16215.

**Comment by dscho** [comment]
@elieux thank you for the update. As it has been fixed, I'll simply close this here ticket.
