### ISSUE TITLE
Some Git commits are missing in commit histroy

### ISSUE THREAD

**Issue by KarenHuang2016** [git-for-windows/git#1174]
We built Git source code using VS. And we found a weird thing. Some Git commits are missing in commit histroy. 
We use the git commit 920c6aa on 5/11. But we found this commit 920c6aa is missing on 5/22. Could you please take a look at this issue? Thanks in advance!

5/22/2017:
![gitcommitson05112017](https://cloud.githubusercontent.com/assets/20896121/26295086/ac5e718e-3efa-11e7-82c3-c32cca8d34a8.jpg)

5/11/2017
![gitcommitson05222017](https://cloud.githubusercontent.com/assets/20896121/26295107/c4157b56-3efa-11e7-97a7-8b34d76c1300.jpg)

**Comment by YueLinHo** [comment]
My guessing is that those are generated automatically by the special author `Git for Windows Build Agent` which may be the CI. And they will be gone next time the branch `master` is pushed to GitHub

**Comment by dscho** [comment]
Yes, `vs/master` is *always* exactly one commit ahead of `master`.

This commit adds the relevant generated files required to build with Visual Studio. The change is actually generated by `make MSVC=1 generate-vcxproj`, leveraging the original `Makefile` based build system to figure out what files need to be included in the build, and how.

Whenever `master` advances, that commit is re-generated based on the latest commit on `master` and `vs/master` is force-pushed with the result.

That means if you place your work on top of `vs/master`, you should always `git pull --rebase origin vs/master` (you can configure this behavior by `git branch --set-upstream-to=origin/vs/master` and `git config branch.<branchname>.rebase true`).

Please feel free to adjust https://github.com/git-for-windows/git/wiki/Compiling-Git-with-Visual-Studio accordingly, to help the next person running into the same question.

**Comment by KarenHuang2016** [comment]
Thanks! I got it. But it seems that "pull --rebase origin vs/master" cannot resolve my problem. When the latest revision changed, it will report merge conflict when I execute command "git pull --rebase origin vs/master" like below:
F:\Git\src>git pull --rebase origin vs/master
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by dscho** [comment]
> F:\Git\src>git pull --rebase origin vs/master
> error: Pulling is not possible because you have unmerged files.

This looks as if you had tried a `git pull` *without* `--rebase` before, and you still have to clean that up by calling `git reset --hard` before trying again.

**Comment by KarenHuang2016** [comment]
Yes, you are right. Thank you so much!

**Comment by AraHaan** [comment]
oh wait so every time a force push happens people can save their clones by doing an ``git pull --rebase origin <branch name>``?

**Comment by dscho** [comment]
@AraHaan that's correct.
