### ISSUE TITLE
git add fails with error "Filename too long"

### ISSUE THREAD

**Issue by alexanderveit** [git-for-windows/git#1177]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

Git for Windows 64-bit.

```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

Windows 8, 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

In the base directory of the project run
```
git init
git add --all .
```
 - What did you expect to occur after running these commands?

Git should add all files to the index.

 - What actually happened instead?

There exist files with long paths, e.g. 233 characters.
```
error: open("lengthy/path/.../with/233/characters"): Filename too long
error: unable to index file lengthy/path/.../with/233/characters
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

The repository could not be created due to this issue.

**Comment by tboegi** [comment]
(This may be a stupid question, but what happens if you run)
git init
git config  core.longpaths true
git add --all .

**Comment by veita** [comment]
This worked, thanks. I wonder why this isn't set by default.

**Comment by landstander668** [comment]
From the release notes:

> Many Windows programs (including the Windows Explorer) have problems with directory trees nested so deeply that the absolute path is longer than 260 characters. Therefore, Git for Windows refuses to check out such files by default. You can overrule this default by setting core.longPaths, e.g. git clone -c core.longPaths=true ...

**Comment by JackGrinningCat** [comment]
I was searching for this. I couldn't find it in this help.

Btw. I would opt for make it default :)
