### ISSUE TITLE
Worktree entry in .git/config broken while working in symlink directory

### ISSUE THREAD

**Issue by marhag87** [git-for-windows/git#1178]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
PortableGit, not sure if applicable
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Stand in a symlink created by `mklink /d <link> <target>` to trigger the bug. I tested this on 2.11.1, this version does not insert the worktree entry in .git/config. I only see this in version 2.12 and forward.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# To create the symlink, in cmd:
cd c:\tmp\
mkdir target
mklink /d link c:\tmp\target

# To see the problem, in bash:
/c/tmp/link$ git init
Initialized empty Git repository in c:/tmp/link/.git/
/c/tmp/link$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        worktree = c:/tmp/target
        symlinks = false
        ignorecase = true
/c/tmp/link$ git submodule init
fatal: $program_name cannot be used without a working tree.
```
 - What did you expect to occur after running these commands?

A .git/config that does not contain a broken worktree entry

 - What actually happened instead?

A .git/config that contains a broken worktree entry

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
I tried to reproduce the problem but failed. `git submodule init` always succeeds here, without any error message. I do not see any `core.worktree` entry in the config, either.

But then, I am using Git for Windows v2.13.0 :smile:

**Comment by dscho** [comment]
I think two years is long enough to wait for an answer. (Actually, I think it is too long to leave an overworked maintainer hanging, but who am I to judge...)
