### ISSUE TITLE
git ls-remote fails when called if the shell is on a UNC path

### ISSUE THREAD

**Issue by James-Dengel** [git-for-windows/git#1181]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 64 bit.
```
$ cmd.exe /c ver

'\\sw-filer2\Lab\Reno\reno_releases\0.1\dist'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am currently working on a UNC mount, this worked in previous version of git 2.9.13 was the version I was running previously.
If i map the drive or use a local path it works correctly.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I can reproduce this issue with Powershell or from within GitBash as long as I am on a UNC path.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cd //sw-filer2/Lab/Reno/reno_releases/0.1/dist
git ls-remote ssh://git@bitbucket:7999/lab_automation/PyCharm.idea.git merckx
```
 - What did you expect to occur after running these commands?

2918018474e9d7e408d5bb2667d91ab83aeeb53b        refs/heads/merckx
2918018474e9d7e408d5bb2667d91ab83aeeb53b        refs/svn/root/branches/merckx

 - What actually happened instead?

fatal: failed to stat '           //sw-filer2': No such file or directory

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It occurs on all repositories and only on a UNC path.

**Comment by dscho** [comment]
Please test the newest snapshot here: https://wingit.blob.core.windows.net/files/index.html

**Comment by James-Dengel** [comment]
Thanks I have tested this now and it works on a Network Path.

Thanks.

**Comment by dscho** [comment]
Thank you for testing and sharing the results.
