### ISSUE TITLE
git commit hangs

### ISSUE THREAD

**Issue by seanzer** [git-for-windows/git#1187]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16193.1001]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Visual Studio 2017 is installed

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit --amend
```
 - What did you expect to occur after running these commands?

vim should start

 - What actually happened instead?

blank console window, hitting enter 14 times shows:
```
"C:/s/myrepo/.git/COMMIT_EDITMSG"
```

**Comment by seanzer** [comment]
It seems like the same symptoms as #711, but maybe it's a new issue?

**Comment by seanzer** [comment]
I'm using **notepad** to workaround the issue, but I much prefer to use **vim**

**Comment by dscho** [comment]
Do you have a `%HOME%\.vimrc`?

**Comment by seanzer** [comment]
Do you mean a `%userprofile%\.vimrc`? I don't see one, should I have one?

**Comment by seanzer** [comment]
I just noticed git bash is unusable too..

**Comment by dscho** [comment]
> I just noticed git bash is unusable too..

Maybe describe the issues in a bit more detail?

**Comment by seanzer** [comment]
when I type into git bash, nothing shows up. Hitting enter causes random keystrokes to show up. It's difficult to describe. I don't get why no one else is having issues.. I'm seeing this behavior on two different computers.

**Comment by seanzer** [comment]
It looks like it's due to the new Windows Console.. I turned on "Use legacy console" and things are working again.
