### ISSUE TITLE
Should the installer default to enabling symlinks when running on the Windows 10 Creators Update?

### ISSUE THREAD

**Issue by toolness** [git-for-windows/git#1189]
Hello! Apologies if this is the wrong place to post this, but I just noticed that support for creating symlinks outside of elevated sessions was just added in #1188. (Thanks for that, by the way!)

I also noticed when installing Git for Windows 2.13.0.windows.1--which I realize does *not* contain #1188--that the "Enable symbolic links" setting is disabled by default. For reference, I'm referring to this dialog:

![2017-05-31_8-35-04](https://cloud.githubusercontent.com/assets/124687/26633465/7d491028-45e1-11e7-9c53-deb979e82dfc.png)

(It's checked in the above screenshot because I manually checked it, but it was originally unchecked.)

I'm curious if, in the next release of Git for Windows which includes #1188, this checkbox will default to being checked if the user is running the installer on the Windows 10 Creators Update.  This *seems* like a reasonable default and might make life easier for Windows, but I'm not sure.

Anyways, thanks again for adding symlink support!

**Comment by dscho** [comment]
@toolness excellent find. Could I ask you to try your hand at patching in the 0x02 flag into the installer when GetVersion() returns at least `14972 << 16`, just like #1188 does for Git itself?

You need to [build the installer first](https://github.com/git-for-windows/git/wiki/Making-an-installer) and then edit `/usr/src/build-extra/installer/install.iss` (look for `CreateSymbolicLink`) before making another installer that you can then test.

**Comment by dscho** [comment]
@toolness I am afraid that this feature will need your help, as I am busy elsewhere.

**Comment by dscho** [comment]
Sigh.
