### ISSUE TITLE
Rebase fails unexpectedly but succeeds after abort and retry

### ISSUE THREAD

**Issue by stdedos** [git-for-windows/git#1190]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600] (Win 8 SP1 fully updated)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** portable version **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** no clue :-( **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`Git Bash MINGW32`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Unfortunately, I cannot provide a Mn-WE :(
```
git rebase master
```
 - What did you expect to occur after running these commands?

Rebase cleanly on top of master (re-re-re enabled and trained)

 - What actually happened instead?

"Crashed" on a random commit (29/59)
Initiated auto-merge
Fallback on 3-way
re-re-re activated on one file (supposedly provided a solution)
Crashed (with message I lost from the window)
Dropped me to "`git rebase` fix problems and `git rebase --continue/--skip/--abort`" mode
Result: 3 files (referenced on the commit) were deleted by git (not me)

I aborted the rebase and re-ran it.
Rebased cleanly on top of master (Commit did not "crash" on the second time).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

NDA / Private Repo :/
Big enough in size (LOC 100k+) and somewhat-big in objects (2.8k).

I know I am not helping a lot here, but maybe other future references will assist (or will somehow solve race conditions)

**Comment by whoisj** [comment]
When you say "crashed" do you get a stack dump to console or just an error message?

**Comment by stdedos** [comment]
Merging error in console. I am not sure how to call it :/

**Comment by whoisj** [comment]
I'd refer to that as "rebase failed unexpectedly". Now, rebase failing and asking for human intervention isn't that unusual, but rebase failing and succeeding after an abort + retry is something I've not seen before.

Schrodinger's rebase? 😕

**Comment by stdedos** [comment]
I know. It has happened one more time - only then the messages seemed as a "natural" request for an intervention. And the files in-question were looking "normal": Some to-be-merged, some staged ...

But I knew it was weird (because re-re-re has saved me over 20 times at the time), so I canceled and redid it, cleanly.

I know, that's why I wanted to bring it to attention, even with so few details and/or little replication possibility.

One thing I am thinking, is that I am using SourceTree, which I am asking to poll the repository every minute. Can a weird race condition between a `git fetch` variant cause all this?

**Comment by dscho** [comment]
> It has happened one more time

Next time it happens, copy the output. Paste it here, verbatim. And then reopen the issue.
