### ISSUE TITLE
ssh can not recognize custom HOME environment variable

### ISSUE THREAD

**Issue by gdh1995** [git-for-windows/git#1193]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Portable Git v2.12.2 (March 27th 2017)

```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

cat: /etc/install-options.txt: No such file or directory
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I unzipped `PortableGit` to `D:\Git` and ran `git-bash.exe`, changed some scripts including /etc/profile and most lines of them are different from the original.

I created a folder /home (D:\Git\home) and sub-folders, and then the **`HOME`** variable has been changed into `/home/$USERNAME` in `/etc/profile` and **exported** whenever `bash` starts.

In `$HOME` (/home/gdh1995), there're `~/.ssh` (folder), `~/.ssh/id_rsa` (valid rsa private key file), `~/.ssh/ssh_config` (empty file). `/etc/ssh/ssh_config` is not modified. The private key file has been tested and it works very well on msys-Git 1.9 and WSL bash. Added: PuTTY is also able to connect target hosts using the corresponding ppk file.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

/usr/bin/bash.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ ssh example.com
...
$ HOME=/home/gdh1995 ssh -v example.com
```
 - What did you expect to occur after running these commands?

`ssh` loads `~/.ssh/id_rsa` and logs in the server sucessfully at once.

 - What actually happened instead?

`ssh example.com` didn't try private key file and required a password. and `HOME=/home/gdh1995 ssh -v example.com` reported:

```
OpenSSH_7.3p1, OpenSSL 1.0.2k  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to ****** [***.***.***.***] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/gdh1995/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/gdh1995/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/gdh1995/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
```

 - Other tries

I changed `/etc/ssh/ssh_config` and tested some different values of `IdentityFile` key, including `~/.ssh/id_rsa` and `$HOME/.ssh/id_rsa`, but this didn't work. And `/home/gdh1995/.ssh/ssh_config` is not read by `ssh` and doesn't work neither.

Now I don't want to write an absolute path in `/etc/ssh/ssh_config`, neither create any files or links under `C:\Users\$USERNAME`, so is there any other method?

**Comment by dscho** [comment]
> the HOME variable has been changed into /home/$USERNAME in /etc/profile

That is too late. The MSYS2 runtime interprets the `HOME` variable upon startup (and as Bash is an MSYS2 program, therefore the MSYS2 runtime starts up *before any Bash script can run*, including `/etc/profile`).

You can work around this by editing `/etc/nsswitch.conf` and setting `db_home: /home/<name>`.

Otherwise, you will have to come up with a way to set the `HOME` variable *before* starting Bash.

**Comment by gdh1995** [comment]
@dscho Why does `ssh` not read `HOME` env variable? For safty?

**Comment by dscho** [comment]
> Why does ssh not read HOME env variable?

It uses the POSIX-y way to determine the home directory. And that information has been set up by the MSYS2 runtime at startup. The `env` part of `db_home: env ...` in `/etc/nsswitch.conf` tells *Git for Windows*' version of the MSYS2 runtime that it should look at the `HOME` environment variable to determine that information. MSYS2's own `/etc/nsswitch.conf` *completely* ignores `HOME`. That's why this information has to be filled at startup of the runtime.

**Comment by gdh1995** [comment]
Thanks a lot!

I've solved this problem by setting **`db_home`** to **`/home/%u env ...`,** although `env /home/%u ...` doesn't work on the newest realese 2.13.0.windows.1 of PortableGit (my Windows has no `HOME` env).

PS: I notice that `db_home` has no comments saying `cygwin desc`, while `db_shell` and `db_gecos` have. Is this the reason `env` can not be before `/path`?

Document: https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-mapping-nsswitch-syntax

**Comment by dscho** [comment]
> although env /home/%u ... doesn't work on the newest realese 2.13.0.windows.1 of PortableGit (my Windows has no HOME env).

If you are launching through `git-bash.exe`, the `HOME` variable is initalized automagically.

> PS: I notice that db_home has no comments saying cygwin desc, while db_shell and db_gecos have.

The idea is to accelerate startup by not enquiring needless information from the domain controller.
