### ISSUE TITLE
Symbolic link to a directory that doesn't exist (yet) fails

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#1197]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.13.0.windows.1.7.g80a6209eb5
built from commit: 80a6209eb5e70f50ffe1cea0da0c24d123a877a6
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using submodules.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init
hash=$(echo -n 'some-dir' | git hash-object -w --stdin)
git update-index --add --cacheinfo 120000 $hash link
git checkout -f link
mkdir some-dir
cd link
# bash: cd: link: No such file or directory
cmd.exe /c dir
# ...
# <SYMLINK>     link [some-dir]
# ...
rm link
git checkout -f link
cd link # works
cd ..
cmd.exe /c dir
# ...
# <SYMLINKD>     link [some-dir]
# ...

```
 - What did you expect to occur after running these commands?

I expect the link to be a directory link rather than a file link.

 - What actually happened instead?

The default link type is file, so it doesn't work when the directory is created later.

I'm not sure if/how this is solvable. Maybe Git needs 2 link types.

In my real case, the symbolic links references a directory in a submodule, which doesn't exist during first clone. When the submodule is initialized later, the link is invalid.

**Comment by dscho** [comment]
What you experience is result of a very real difference between NTFS symlinks and Unix symlinks. At the time you ask Git to create the symlink, it has *no* chance to know the type of the target (therefore it defaults to type `file`). And once you created the target, Git again has *no* chance to adjust the type.

I am pretty certain that this cannot be fixed, at least not in the scenario you presented (you literally use *only* non-Git commands to create the symlink target and immediately after that to change the current directory).

**Comment by dscho** [comment]
@orgads do you disagree with my reasoning in any way?

**Comment by orgads** [comment]
Sorry, I thought I already answered you :)

The reason for this failure was clear to me. That's why I suggested having a separate link type, but I guess this is not feasible.

Another way to solve this issue is to keep broken links unindexed (meaning they will be scanned on each operation. I'm not sure if/how this is possible). Then if the link becomes valid, either mark it as _changed_, and recreate is as a directory link on checkout, or just automatically fix the link type.

Is it even possible to tell that the link is changed if it was converted from a file to a directory or the other way around? If it is possible, we can suggest a workaround by touching the link, then checking it out.

What do you say?

**Comment by dscho** [comment]
Hmm. In the example you provided, there was no Git command between creating the link target and using the link. That means that no code change in Git would have helped...

**Comment by orgads** [comment]
Of course nothing can be done without Git. That was just a minimal example to demonstrate the problem. But what if `git diff` or `git status` would detect this, allowing to checkout in the correct form?

**Comment by dscho** [comment]
> But what if git diff or git status would detect this, allowing to checkout in the correct form?

That would violate the law of least surprises: who would think that `git diff` or `git status` are anything but read-only operations?

(I know that they update the index if they can, and I am not happy about that, either.)

**Comment by orgads** [comment]
I didn't mean that `git diff` itself would change the link. Only that it can inform the user that the link is "modified", allowing the user to run `git checkout` that will fix it.

**Comment by dscho** [comment]
Okay. If you find the time to implement this, I will be the last person to reject  the Pull Request.

**Comment by erobledo** [comment]
There is a situation where this problem is specially painful and could be avoided by git: When the target of the symbolic link is a folder inside a git submodule that has not been checked out yet.

In this situation, git itself creates the target folder, but only after the symbolic link has been created with the wrong target type, and currently git does not update the symbolic link to make it of the right target type after the submodule is checked out, so it remains broken with a File target type. 

This can be particularly confusing when doing `git clone --recurse-submodules`. One could argue that the user should not need to know the details about the order in which things happen, and is reasonable to expect the symbolic links, even across submodules, to be correct when that git command completes.

**Comment by dscho** [comment]
I think this ticket has been addressed by https://github.com/git-for-windows/git/pull/1897: just add the attribute `symlink=dir` to your entry in `.gitattributes` (or add the entry).
