### ISSUE TITLE
Removed carriage returns don't appear with `cr-at-eol` enabled

### ISSUE THREAD

**Issue by masaeedu** [git-for-windows/git#1198]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global core.whitespace cr-at-eol
git config --global core.autocrlf false
git config --global diff.wsErrorHighlight all

mkdir test
cd test
git init

echo "Test`r`nTest" | out-file -encoding ascii -nonewline test.txt
git add -A
git commit -m "File with carriage return"

rm test.txt
echo "Test`nTest" | out-file -encoding ascii -nonewline test.txt
git commit -am "Removed carriage return"

git diff HEAD~
```
 - What did you expect to occur after running these commands?

`git diff` should explicitly display the removed carriage returns, since I have `diff.wsErrorHighlight` set to `all`.

 - What actually happened instead?

`git diff` displays the same line as added and removed, without any indication of the removed carriage return. The removed carriage return only appears if I disable `core.whitespace cr-at-eol`, but this results in seeing carriage returns all the time, even though I don't care about unchanged carriage returns and don't inherently consider them an error.

Here's a screenshot:

![demo](https://rrg9vq.by3302.livefilestore.com/y4m9Pn3jdF2HUAUExvUGbzuD6D8yvMHuMzdQiW-RB4KDWuVUjPI4em4k7eZEf4Yl5502-YvIYzFDQYVM3iiYF_638IQRv9m7DzokhAL9VO8oTBolwYwrWd0BLeN-cu8UBXTy1LiJTwBThLbcwkrp1wOn0pftyxcmojjqWKDD3wZrgsKtpmWx5JM9DJIg-Zk1XQmcjK2_aWO55v_pQ6QQxVJUA/ConEmu64_2017-06-05_18-55-38.png?psid=1)

**Comment by dscho** [comment]
I just tested this on Linux, and the behavior is the same. Therefore this is not a Windows-specific issue and hence better reported to the [Git mailing list](mailto:git@vger.kernel.org).

However, I could imagine that the expectation is based on a misunderstanding of what `cr-at-eol` does. From [Git's documentation](https://git-scm.com/docs/git-config):

> * `cr-at-eol` treats a carriage-return at the end of line as  part of the line terminator, i.e. with it, `trailing-space`  does not trigger if the character before such a carriage-return  is not a whitespace (not enabled by default).

In other words, this flag *suppresses* errors. It does not enable additional error messages.
