### ISSUE TITLE
Switch over from msysgit.github.io to git-for-windows.io

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#12]
I already started to populate https://git-for-windows.github.io/ with a website modified from https://msysgit.github.io/.

To finalize this ticket, we need to
- [x] release a new installer generated using the new Git for Windows SDK
- [x] replace msysgit.github.io by a redirect to the new home page
- [x] notify the readers of the Git mailing lists of the switch
- [x] add a note to the msysGit repositories

**Comment by nalla** [comment]
Well, I just want to help, so I drew up a *draft* for an announcement message. Maybe you can take something from that.

```
[ANNOUNCE] Git for Windows Release 2.x

For reasons listed in [1] and [2] an investigation occurred to use a new
platform to build Git for Windows. There were several approaches to use
different platforms. Finally it was settled to use the MSYS2[3] platform
to build Git for Windows.

Thus a new Git for Windows SDK was developed based on MSYS2. This
development took quite a bit of time. But this journey is finally at an
end. Thanks to the hard work of some good developers there is now a
working Git for Windows SDK[4], a working Git for Windows Portable
Release[5] and a full Git for Windows installer[6]. All based on the 2.x
release of git.

There was also some change in the naming. The msysgit[7] project will be
superseded by the git-for-windows[8] project. This is now the place where
Git for Windows builds will be maintained.

[1] https://github.com/git-for-windows/git/issues/12
[2] https://github.com/git-for-windows/sdk#todos-roughly-in-order-of-priority
[3] http://msys2.github.io/
[4] https://github.com/git-for-windows/build-extra/releases
[5] TODO
[6] TODO
[7] https://github.com/msysgit
[8] https://github.com/git-for-windows
```

**Comment by JBlond** [comment]
Is it possible to have the "replace msysgit.github.io by a redirect to the new home page" soon'ish?  Cause https://git-for-windows.github.io/ is very hard to find on google.

**Comment by dscho** [comment]
> Is it possible to have the "replace msysgit.github.io by a redirect to the new home page" soon'ish?

Why, that would be premature. We do not have any official Git for Windows 2.x for end users out yet, just one release candidate.

**Comment by JBlond** [comment]
All downloads on msysgit say preview. Is that so different? 
However if you say that the current RC's not stable enough then don't switch.

Also the wandisco com wandisco-certified-git-binaries are not as good as your binaries ;) I love the copy and paste option.

**Comment by dscho** [comment]
> However if you say that the current RC's not stable enough then don't switch.

... yet. Exactly.

**Comment by DanRigby** [comment]
Item 1 is complete as of yesterday.

**Comment by dscho** [comment]
Announcement sent: http://article.gmane.org/gmane.comp.version-control.msysgit/21805

**Comment by dscho** [comment]
Redirect in place: https://github.com/msysgit/msysgit.github.com/commit/2a3c4da85c4144fc34591ea2e2d07ab2b155fab9

**Comment by dscho** [comment]
With https://github.com/msysgit/msysgit/commit/088d25f31e34544c90a3c3f7342ea424333f2805 and https://github.com/msysgit/git/commit/3259ef981084f72b35d17b5ebbcff7f6db1d9e77, this ticket is finally addressed.

**Comment by techtonik** [comment]
Good job! =)

**Comment by linquize** [comment]
Also, git-scm.com is updated too!
Now, git-scm.com can also show you 4 variants in a list: 32/64 installer/portable
