### ISSUE TITLE
.sh file association doesn't work

### ISSUE THREAD

**Issue by Animeye** [git-for-windows/git#120]
The current command used to execute .sh files seems to be failing, especially for paths with spaces. The "--cd=%1" seems to fail due to it pointing at a file instead of a directory, and the %* fails due to the paths not being quoted.

Changing https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss.in#L147 (also 154) to use """{app}\git-bash.exe"" ""--cd=%w"" ""%L""" seems to work correctly

**Comment by dscho** [comment]
Seeing as you tested the developers' preview, I would like to ask you to use your developer-fu to make a stronger case than "it seems to work correctly" and to open a PR after that, using that strong argument in the commit message. This would help Git for Windows very much....

**Comment by Animeye** [comment]
Been working with this a bit more --
The quoted %w and %L changes do work for correcting double-click functionality, while the %* can probably be dropped all together (not finding any case that would actually put any real arguments into that).
Drag-and-drop onto a .sh file seems to also be suffering from the "can't handle paths with spaces" issue.  Seems to be an issue with the exe drophandler guid (its not converting the full path to 8.3 format for some reason).  Switching DROP_HANDLER_GUID to "({60254CA5-953B-11CF-8C96-00AA00B8708C}" (WSH drophandler, passes paths as quoted full-length) seems to be resolving that.

The installer should probably also have ChangesAssociations=yes to have windows update the association data after install/uninstall.
Additionally, I'm not sure if the 'createvalueifdoesntexist' flag needs to be removed to allow the fixed values to get written (haven't had the chance to test that yet, but I suspect it is similar to https://github.com/msysgit/msysgit/commit/be9af3f79a5685098e16be9318d266bd65e855cf).

These changes seem to resolve everything except a strange issue with jump lists.  Selecting a file from git-bash's 'recent files' jump list is just giving me an error about the file not being associated with any program.  Haven't been able to find a fix for that (everything else confirms the file association is correct, so I'm not sure why jump lists are behaving differently).

**Comment by elyscape** [comment]
Changes added to git-for-windows/build-extra#51.  How do you want to be credited, @Animeye?  Right now I have just `Helped-by: Animeye` in the commit message.

**Comment by Animeye** [comment]
That crediting is fine for me.  Glad I could help

**Comment by dscho** [comment]
> Drag-and-drop onto a .sh file seems to also be suffering from the "can't handle paths with spaces" issue. Seems to be an issue with the exe drophandler guid (its not converting the full path to 8.3 format for some reason). Switching DROP_HANDLER_GUID to "({60254CA5-953B-11CF-8C96-00AA00B8708C}" (WSH drophandler, passes paths as quoted full-length) seems to be resolving that.

@Animeye could you please test whether the WSH DropHandler handles Unicode names alright? While trying to figure out whether XP supports that DropHandler, I found [this report](http://answers.microsoft.com/en-us/windows/forum/windows8_1-files/wshvbs-drophandler-doesnt-support-unicode/6c74a306-0655-489a-a22c-99909bf74a02) that it does not...

**Comment by dscho** [comment]
> While trying to figure out whether XP supports that DropHandler

For the record, it appears that it does: [this page](http://www.nilpo.com/2009/07/windows-xp/restoring-vbs-vbscript-script-file-file-associations/) shows how to repair `.vbs` file associations on XP and Vista and it references the *same* DropHandler for both cases.

**Comment by dscho** [comment]
Let's move the discussion [to the Pull Request](https://github.com/git-for-windows/build-extra/pull/51).
