### ISSUE TITLE
When amending message, file open path is erroneous

### ISSUE THREAD

**Issue by stdedos** [git-for-windows/git#1201]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I found some, but they are referring to old Vim (7.4* vs 8.0 for me) and old Git (2.8 instead of 2.12)

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

$ git --version --build-options
git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600] (Win 8 SP1 x64 fully updated)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** portable version **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** no clue :-( **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`Git Bash MINGW32`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit --amend ${EXTRA_ARGUMENTS}
```
 - What did you expect to occur after running these commands?

Open the vim editor to amend the message

 - What actually happened instead?

Vim file path is
```
/e/Stdedos/Documents/Some/Directory Structure/follows/"E:/Stdedos/Documents/Some/Directory Structure/follows/.git/COMMIT_EDITMSG" [unix] (01:59 01/01/1970)
```
and hence, file is not openable

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

NDA / Private Repo :/
Big enough in size (LOC 100k+) and somewhat-big in objects (2.8k).

**Comment by PhilipOakley** [comment]
I believe this path mangling issue (`/follows/"E:/Stdedos/Docum..`) is being fixed in either the latest release or coming release. 

I've ceratianly seen fixes on the main list for this style of problem caused by a prefix being added to a misunderstood Windows path which gained quotng and the drive letter.

See if https://github.com/git-for-windows/git/releases/tag/v2.13.0.windows.1 helps.

**Comment by stdedos** [comment]
Merged https://github.com/git-for-windows/git/releases/tag/v2.13.0.windows.1 with my portable version, no change

**Comment by PhilipOakley** [comment]
@stdedos, 

The release 2.13.1 has been delayed. There was an announcement (on the google groups list) a few days back. Maybe try the latest snapshot.

From: "Johannes Schindelin" <Johannes.Schindelin@gmx.de>
Sent: Monday, June 05, 2017 12:47 PM
Subject: [git-for-windows] Git for Windows v2.13.1 delayed, was Re: [ANNOUNCE] Git v2.13.1

> Hi team,
> 
> On Mon, 5 Jun 2017, Junio C Hamano wrote:
> 
>> The latest maintenance release Git v2.13.1 is now available at
>> the usual places.
> 
> Due to unexpected problems in renewing my code-signing certificate, and
> another set of unexpected obstacles in obtaining a new one, Git for
> Windows v2.13.1 is being delayed.
> 
> In case you need any of the fixes that made it into v2.13.1, you have the
> following options:
> 
> - Build a custom Git for Windows:
> 
> https://github.com/git-for-windows/git/wiki/Making-an-installer
> 
>  Git for Windows' current master was just updated to be based on Git
>  v2.13.1.
> 
> - Download a snapshot (with unsigned executables) from
> 
> https://wingit.blob.core.windows.net/files/index.html
> 
>  The snapshots are built from Git for Windows `master` branch, meaning
>  that it may take a little while before the snapshot for the current
>  revision is available.
> 
> Sorry for the inconvenience,
> Johannes
> 
> --

**Comment by dscho** [comment]
> > What commands did you run to trigger this issue? If you can provide a
> >  Minimal, Complete, and Verifiable example
> >  this will help us understand the issue.
> 
> git commit --amend ${EXTRA_ARGUMENTS}

This is *not* a verifiable example. Please do spend a little bit more effort to come up with a minimal, verifiable example that is easy to follow and will likely reproduce the issue on somebody else's computer.

I amend commits all the time, and have *never* had any of these issues.

Which means that there is something substantially different in your use case than in all of my use cases. I would even wager a guess that it would work for you if you called

```
mkdir amend-test
cd amend-test
git init
echo 1 >txt
git add txt
git commit -m initial
echo 2 >txt
git commit --amend -a
```

**Comment by stdedos** [comment]
I am sorry it does not verify for you. And I believe bug reports are for something _that happens to some people_, not necessarily everyone

![image](https://user-images.githubusercontent.com/133706/27088770-4972a8c4-5061-11e7-8056-0965227d1419.png)

Do you require something more to be convinced that I am not looney?

* Perhaps it's the issue of spaces?
* Non-english characters?
* Both?
* None?

**Comment by dscho** [comment]
> I am sorry it does not verify for you.

Well, to be quite honest, if you mean `git commit --amend ${EXTRA_ARGUMENTS}` by "it", then yes, it does not verify for me. I would be surprised if it verified for anybody.

> Do you require something more to be convinced that I am not looney?

I do not believe that you are a looney.

i am convinced, however, that this report is too incomplete to allow me to help.

**Comment by stdedos** [comment]
Well, how can I help then?
Other than copy my entire installation / repository or give you access to my machine, I can pretty much tell you whatever you want.

Just ask me :)

**Comment by dscho** [comment]
> Well, how can I help then?

Try to reproduce the issue with a very, very minimal repository. If it fails, report the exact steps. Just like I did here: https://github.com/git-for-windows/git/issues/1201#issuecomment-308069891

You could even follow the very same steps I indicated there and see whether you can reproduce the issue then.

What will not work is to leave the problem as fuzzy and unclear as it is right now. There must be a difference between the problem you encountered and what I do all the time, and it is likely to be a path problem or some such. You will have to experiment to find out.

**Comment by stdedos** [comment]
I guess I wasn't clear enough with the image I uploaded.

I ran the commands you gave me:
```
mkdir amend-test
cd amend-test
git init
echo 1 >txt
git add txt
git commit -m initial
echo 2 >txt
git commit --amend -a
```

The image is from the `git commit --amend -a` command.
Notice the path on both the Vim Status line (ending both times in `amend-test`) and the title bar of MINGW32 (ends in `amend-test`)

**Comment by dscho** [comment]
> I guess I wasn't clear enough with the image I uploaded.

That image does not clear anything up for me, as it is way too large and gets resized to fit inside my browser window.

**Comment by stdedos** [comment]
The path on the Vim status bar is too big to fit in a smaller image :/

**Comment by dscho** [comment]
Maybe there is something in your config that makes this happen.

**Comment by dscho** [comment]
BTW I meant for the minimal example to be really minimal. For example, you still use the `E:` drive and a deep directory structure, both of which could trigger the problem. You need to instead try to *reduce* the number of possible culprits to the bare minimum. And if somewhere along the way the bug vanishes, you know that you eliminated the culprit.

For the record, I tried again, on a drive other than `C:` (but still a local NTFS drive), with a deep directory structure, with a space in a directory name, and I *still* cannot verify that there is a problem.

**Comment by stdedos** [comment]
```
Stdedos@Stdedos-PC MINGW32 /e/Stdedos/Documents/Some/Διρεκτορυ Στρακτουρ/amend-test (master)
$ git config --list
core.symlinks=false
core.autocrlf=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
filter.lfs.process=git-lfs filter-process
credential.helper=manager
difftool.sourcetree.cmd='E:/Portable Applications/Duplicates/DiffMerge/sgdm.exe' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd='E:/Portable Applications/Duplicates/DiffMerge/sgdm.exe' -merge -result="$MERGED" "$LOCAL" "$BASE" "$REMOTE"
mergetool.sourcetree.trustexitcode=true
difftool.DiffMerge.cmd='E:/Portable Applications/Duplicates/DiffMerge/sgdm.exe' "$LOCAL" "$REMOTE"
mergetool.DiffMerge.cmd='E:/Portable Applications/Duplicates/DiffMerge/sgdm.exe' -merge -result="$MERGED" "$LOCAL" "$BASE" "$REMOTE"
mergetool.DiffMerge.trustexitcode=true
diff.tool=DiffMerge
diff.algorithm=histogram
merge.tool=DiffMerge
user.name=Stavros
user.email=me@you.com
core.autocrlf=true
core.excludesfile=
rerere.enabled=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
```

And vimrc from ${git_path}\git_local\etc: [vimrc.txt](https://github.com/git-for-windows/git/files/1072728/vimrc.txt)

**Comment by stdedos** [comment]
`E:` is a local, dedicated (i.e. not partition, real physical) NTFS drive of mine (storage).

If I run the commands on `E:\Temp\amend-test`, then amend happens as natural.

By your test (deep structure on `C:`) and my test (`E:\Temp`) both succeeding, then the bug is either on directory with spaces, or non-english characters on path.

I tested a directory `sadas sadas` under `E:\Temp`, it still works
I tested a directory `σαδδσαδασ` under `E:\Temp`, it still works
I tested a directory `σαδδ σαδασ` under `E:\Temp`, then it *crashes*.

**Comment by dscho** [comment]
> /e/Stdedos/Documents/Some/Διρεκτορυ Στρακτουρ/amend-test

And now try with a simple path again, to reduce the possible number of culprits. I.e. in a path that is on the C: drive, without spaces in the name, and without Greek letters.

Again, if the problem does not occur, you removed the culprit and can add back a couple of possible problems, until you identified *the* problem.

**Comment by dscho** [comment]
> I tested a directory σαδδ σαδασ under E:\Temp, then it crashes.

That looks more like a minimal example now.

**Comment by dscho** [comment]
However, I just tried with that directory name (in `/d/test-git/abspath-1201`), and for me VIM reports a different path. It shows

> "D:/test-git/abspath-1201/σαδδ σαδασ/.git/COMMIT_EDITMSG" [unix] (00:59 01/01/1970)

In particular, it does *not* have the Unix-y path prepended, but the DOS-y path with forward slashes. But it has quotes around the path.

However, if I set `export LANG=en_US.UTF-8`, it works as expected.

**Comment by stdedos** [comment]
If I re-write the image with the paths you are using, it would look like:
```
/d/test-git/abspath-1201/"D:/test-git/abspath-1201/σαδδ σαδασ/.git/COMMIT_EDITMSG" [unix] (00:59 01/01/1970)
```
It says `01:59` for me, but I guess that not important.

Confirmed solution. I added `export LANG=en_US.UTF-8` to .profile and it works as expected
