### ISSUE TITLE
Git 2.13.1 x64 crashes/segfaults on commit

### ISSUE THREAD

**Issue by csrakowski** [git-for-windows/git#1202]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.1.windows.1
built from commit: 13f583bedb59f9a11b3f2e91673c10c250f84576
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

It works/worked fine in 2.13.0

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Crash happens in PowerShell (in Cmder), Cmd and Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Either of:
git commit -am ""
git commit -m ""
git commit

```
 - What did you expect to occur after running these commands?

The normal commit flow

 - What actually happened instead?

Segfault :-(
I don't have the debug symbols at this time, but I have attached a screenshot of the disassembly.
If you can point me to the pdb's, I can try again with those.

![git-for-windows-crash](https://user-images.githubusercontent.com/1303967/27126965-724da2ba-50f9-11e7-8a56-bc5fc40f734c.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by Radrik5** [comment]
I have segfault on checkout with git 2.13.1. The repository is private.
```
$ GIT_TRACE=1 git checkout clnt18x4x8011x1
13:22:07.236517 git.c:369               trace: built-in: git 'checkout' 'clnt18x4x8011x1'
Segmentation fault
```

**Comment by seishun** [comment]
`git checkout .` and `git diff` crash for me. Same version, same trace as above.

**Comment by verkruemelt** [comment]
`git commit` (segfault) and `git GUI` crashes on loading repo.

Going back to git 2.13.0 - no problems.

**Comment by veikkoeeva** [comment]
Looks like being the same problem for me too, `git checkout <anybranch>` will crash with segfault.

**Comment by cvalerio** [comment]
Same issue here!

**Comment by dscho** [comment]
Please test with the current snapshot: https://wingit.blob.core.windows.net/files/index.html

**Comment by seishun** [comment]
Works for me.

**Comment by rongjiecomputer** [comment]
Snapshot works for me.

(I am the same person in https://groups.google.com/d/msg/git-for-windows/Bsulx6y9RtI/tH3bNQ4VAAAJ)

**Comment by csrakowski** [comment]
Snapshot fixed it for me too 👍

**Comment by jeyoung** [comment]
This is happening to me, too.

D:\>git --version --build-options
git version 2.13.1.windows.1
built from commit: 13f583bedb59f9a11b3f2e91673c10c250f84576
sizeof-long: 4
machine: x86_64

**Comment by dscho** [comment]
Fixed in https://github.com/git-for-windows/git/releases/tag/v2.13.1.windows.2.

Thanks all!
