### ISSUE TITLE
GITK don't show unstaged changes. 

### ISSUE THREAD

**Issue by ccfelix** [git-for-windows/git#1203]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64 bits
$ git --version --build-options

** git version 2.13.1.windows.1
built from commit: 13f583bedb59f9a11b3f2e91673c10c250f84576
sizeof-long: 4
machine: x86_64
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
** Windows 7 Pro 64 bits **

```
$ cmd.exe /c ver

** Microsoft Windows [versão 6.1.7601] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
** notepad as editor **

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** no **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** bash from git **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** gitk **
```
 - What did you expect to occur after running these commands?

** show staged and UNSTAGED changes **

 - What actually happened instead?

** dont show unstaged changes **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** local private repository **

![gitk-error2](https://user-images.githubusercontent.com/11245148/27137796-338ef744-50f5-11e7-88a8-6926854b4e38.jpg)

**Comment by dscho** [comment]
I fear this is a misunderstanding of `gitk`'s purpose. The `gitk` command shows the commit history, it does not ever look at the worktree.

Maybe you were looking for Git GUI?

In any case, this is not a behavior specific to the Windows port of Git, therefore I suggest to direct follow-up questions to [the Git mailing list](mailto:git@vger.kernel.org).

**Comment by ccfelix** [comment]
I'm afraid it's you who does not understand the purpose of gitk. I use it to review before committing. And yes, it looks at the worktree. See picture atached from 2.13.0

![erro-gitk](https://user-images.githubusercontent.com/11245148/27154401-4fb7b04c-512b-11e7-9593-a25a0c77df86.jpg)

**Comment by dscho** [comment]
Okay. i had verified that the symptom was identical on Linux and assumed that `gitk` was intended to work that way.

My point about this not being Windows-specific stands, though.
