### ISSUE TITLE
git vim cursor is not always at the first line

### ISSUE THREAD

**Issue by zjturner** [git-for-windows/git#1207]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit
```
 - What did you expect to occur after running these commands?

Expected a vim window to be open with a pending commit message and the cursor in the upper left corner.

 - What actually happened instead?

The problem is non-deterministic.  I can do the same thing 5 times and the problem might only happen once.  But the cursor will be on the first column of a random line.  Pressing i to start typing a commit message then starts editing in the middle of the auto-generated commit-message comments.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I don't think it's repository specific, but regardless I am using this repository `https://github.com/llvm-project/llvm-project-20170507.git`.   

 Here is my entire git config.

```
core.symlinks=false
core.autocrlf=false
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
filter.lfs.process=git-lfs filter-process
credential.helper=manager
user.name=foo
user.email=foo@foo.com
core.whitespace=trailing-space,space-before-tab
core.longpaths=true
format.signature=
color.ui=true
diff.tool=araxis
difftool.araxis.path=C:\Program Files\Araxis\Araxis Merge\compare.exe
merge.tool=araxis
mergetool.araxis.path=C:\Program Files\Araxis\Araxis Merge\compare.exe
alias.dos2unix=!git diff --name-only --cached | xargs dos2unix
alias.tidy=!git diff --name-only --cached | xargs sed --in-place 's/[[:space:]]\+$//' | xargs dos2unix
color.status.changed=cyan
color.status.untracked=cyan
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
remote.origin.url=https://github.com/llvm-project/llvm-project-20170507.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.rawstyle.remote=origin
branch.rawstyle.merge=refs/heads/master
branch.support.remote=origin
branch.support.merge=refs/heads/master
branch.commit.remote=origin
branch.commit.merge=refs/heads/master
branch.fixbuild.remote=origin
branch.fixbuild.merge=refs/heads/master
```

**Comment by dscho** [comment]
I think this is related to [this part of `/etc/vimrc`](https://github.com/git-for-windows/build-extra/blob/61e41d9503ced0a3cee43f12e82b0339effe5897/git-extra/vimrc#L24-L32):

```vim
    "Remember the positions in files with some git-specific exceptions"
    autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$")
      \           && expand("%") !~ "COMMIT_EDITMSG"
      \           && expand("%") !~ "ADD_EDIT.patch"
      \           && expand("%") !~ "addp-hunk-edit.diff"
      \           && expand("%") !~ "git-rebase-todo" |
      \   exe "normal g`\"" |
      \ endif
```

I could imagine that there are other basenames we need to add. Could you see whether you can find out what is the precise file name of the file to be edited, next time this happens?

**Comment by zjturner** [comment]
Attached is a screenshot of my window immediately upon typing `git commit`.  You can see the filename at the bottom, and you can see the cursor about halfway down in the first column.  It seems plausible that the above code is related, but the filename seems to match the pattern, so maybe this code isn't being executed for some reason?

![untitled](https://user-images.githubusercontent.com/11823433/27243395-71217026-5296-11e7-884e-512afd32a313.png)

**Comment by zjturner** [comment]
Note that this seems to be a regression.  I recently upgraded from 2.10 and did not have this problem.

**Comment by zjturner** [comment]
It definitely does seem to be related to remembering the file position.  If I do `git commit`, type an arbitrary commit message, then make a trivial change and use `git commit --amend` the cursor is usually on the last character of the previously typed commit message, which implies the remembering logic is not working.

That said, I don't know anything about editing `.vimrc` files by hand, so I can't tell if it's a bug in the `.vimrc` file or a bug in `vim` itself.

**Comment by dscho** [comment]
I just had a quick look and it would appear that `expand("%")` expands to the full path.

Could you try the following: in `C:\Program Files\Git\etc\vimrc`, change the `expand("%")` calls by `expand("%:t")` in the part [to which I referred earlier](https://github.com/git-for-windows/git/issues/1207#issuecomment-309012162).

Note: you will have to edit the file as administrator. The easiest way may be to right-click on *Git CMD* in the Start Menu, select *Run as Administrator* and then call `git config -f "C:\Program Files\Git\etc\vimrc" -e`.

Sidenote: I got that information from http://vimdoc.sourceforge.net/htmldoc/eval.html#expand(), and I tried it out using `:echom expand("%:t")` in vim.

If that change fixes the symptoms on your side, I will take it from there.

**Comment by toby-allsopp** [comment]
I have the same problem. I tried replacing all the `"%"` with `"%:t"` in `/etc/vimrc` and it didn't make any difference. I added an `echom` inside the `if` to see if it's actually running the `normal g` command, and after your suggested change, it is *not* running it, but the cursor position is still updated.

There is suspicious looking code in `/usr/share/vim/vim80/defaults.vim` that does a similar thing. This file is sourced if there is no `~/.vimrc`, which is new behaviour is Vim 8.0.

So, to fix this, simply create `~/.vimrc` (it can be empty)/

**Comment by toby-allsopp** [comment]
Might be a good idea to add "MERGE_MSG" to the list as well.

**Comment by dscho** [comment]
@toby-allsopp good point about that new `defaults.vim` feature. It's not the first time this has caused surprise.

I tried to disable the `vimStartup` autogroup, [as recommended](https://github.com/vim/vim/blob/fadacf01d0dbcc7a96ef5eee0ad57956eeab04d7/runtime/defaults.vim#L103-L104), but as I did it in `/etc/vimrc` (and that file is parsed *before* `defaults.vim`) it did not work.

Now, I could skip the `defaults.vim` entirely [by defining `skip_defaults_vim`](https://github.com/vim/vim/blob/fadacf01d0dbcc7a96ef5eee0ad57956eeab04d7/runtime/defaults.vim#L16-L20), but that seems quite a bit heavy-handed.

Probably the best I can do is to edit `defaults.vim` via `git-extra`'s post-install script. Ugly, but probably would work...

**Comment by toby-allsopp** [comment]
It seems that this problem is known upstream also: https://github.com/vim/vim/commit/9a48961d8bd7ffea14330b9b0181a6cdbe9288f7

**Comment by dscho** [comment]
> It seems that this problem is known upstream also: vim/vim@9a48961

Thanks. This is only half a solution, though, as it does not take into account other file types that need adjusting... So I am relatively comfortable with the workaround I implemented.
