### ISSUE TITLE
Latest git on Windows 10 causes a segmentation fault trying to checkout a branch

### ISSUE THREAD

**Issue by jjohnstn** [git-for-windows/git#1208]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.1.windows.1
built from commit: 13f583bedb59f9a11b3f2e91673c10c250f84576
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git shell (mingw64)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git checkout containerBuild
```
 - What did you expect to occur after running these commands?

I expected the upstream containerBuild branch to be checked out to replace the master branch
that was originally cloned from my GitHub repo

 - What actually happened instead?

I get a segmentation fault.  Then the .git/index.lock file must be removed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

git clone https://github.com/jjohnstn/cdt.git
cd cdt
git checkout containerBuild

**Comment by YueLinHo** [comment]
Maybe duplicate to issue #1202? 
And try https://github.com/git-for-windows/git/releases/tag/v2.13.1.windows.2?

**Comment by damon-atkins** [comment]
$ git --version --build-options
git version 2.13.1.windows.1
built from commit: 13f583bedb59f9a11b3f2e91673c10c250f84576
sizeof-long: 4
machine: x86_64

Fresh Start
1. "git clone ...." works
2. "git log" works
3. "git branch"  indicates on develop branch ( note this is used instead of master)
4. "git diff" segmentation fault

**Comment by damon-atkins** [comment]
$ git --version --build-options
git version 2.13.1.windows.2
built from commit: a36e14b3aaa0ddb633c40a9c8483e6fe12d99616
sizeof-long: 4
machine: x86_64 version 2.13.1.windows.2

Looks like it is fixed in https://github.com/git-for-windows/git/releases/tag/v2.13.1.windows.2

**Comment by jjohnstn** [comment]
Thanks.  It works with the .2 release.
