### ISSUE TITLE
installer: respect systemwide config `%PROGRAMDATA%\Git\config`

### ISSUE THREAD

**Issue by nalla** [git-for-windows/git#121]
Probably [install.iss.in#L1117](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss.in#L1117) and [install.iss.in#L1133](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss.in#L1133) have to be adjusted.

Also `mingw[32|64]/etc/gitconfig` should not be installed into the `AppDir` by the installer. Instead it should be *merged* with a possible `%PROGRAMDATA%\Git\config`.

I would propose the following mechanism to be ran by the installer code before tampering the file with the user choices.

```
if not exists %PROGRAMDATA%\Git\config
  move mingw[32|64]/etc/gitconfig %PROGRAMDATA%\Git\config
delete mingw[32|64]/etc/gitconfig
```

**Comment by dscho** [comment]
> I would propose the following mechanism to be ran by the installer code before tampering the file with the user choices.
> 
> if not exists %PROGRAMDATA%\Git\config
>   move mingw[32|64]/etc/gitconfig %PROGRAMDATA%\Git\config
> delete mingw[32|64]/etc/gitconfig

That makes the most sense to me, too.

**Comment by dscho** [comment]
Since I merged the PR and included it in the (still experimental, i.e. developers' preview) 2.3.7.1 installer, this issue has been addressed! Thanks @nalla!
