### ISSUE TITLE
how to set the color for the tracking remote branch showed in git branch -vv

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#1210]
The  default color for tracking branch is blue, it is not friendly for me.
The background color is black,the foreground color is blue.
The blue color in black background is illegible

![image](https://user-images.githubusercontent.com/3004057/27251179-240815ae-5374-11e7-8228-66a79c499354.png)

I want to change the blue color to yellow or something else.
Could you tell where to set the color? I have check the options of git bash,can not find the place to set the color

**Comment by PhilipOakley** [comment]
I use
```
[color "branch"]
	upstream = green
```

in my `.gitconfig`


I'm mainly on a little old XP netbook (portability issues) with f.lux for toning down the blues at night so I also have..

I also have my .minttyrc set as
```
BoldAsFont=yes
FontHeight=10
ForegroundColour=248,248,242
BackgroundColour=39,40,34
CursorColour=253,157,79
Black=39,40,34
BoldBlack=117,113,94
Red=249,38,114
BoldRed=204,6,78
Green=166,226,46
BoldGreen=122,172,24
Yellow=244,191,117
BoldYellow=240,169,69
Blue=102,217,239
BoldBlue=33,199,233
Magenta=174,129,255
BoldMagenta=126,51,255
Cyan=161,239,228
BoldCyan=95,227,210
White=248,248,242
BoldWhite=249,248,245
BoldAsColour=yes
```
This is something from a github repo (https://github.com/oumu/mintty-color-schemes ?) on such soft colours, but the source comments got lost (bug in mintty which is now fixed https://github.com/mintty/mintty/issues/574).

**Comment by chucklu** [comment]
@PhilipOakley  Thanks a lot,
I have added the section below  in global .gitconfig file,it works perfectly.
> [color "branch"]
> 	upstream = green

Another suggestion is, could you assign a more recognizable color for the upstream branch, since the default color blue is hard to recognize from the black background color

**Comment by shiftkey** [comment]
> Another suggestion is, could you assign a more recognizable color for the upstream branch by default, since the default color blue is hard to recognize from the black background color

@chucklu this has come up before #1107 and because this is [part of the default behaviour of Git](https://github.com/git/git/blob/master/builtin/branch.c#L45) this is something that should be discussed on [the mailing list](https://git.wiki.kernel.org/index.php/GitCommunity) rather than here.

**Comment by chucklu** [comment]
@shiftkey  got you ,thanks a lot.
