### ISSUE TITLE
Git Bash string expansion

### ISSUE THREAD

**Issue by sxlijin** [git-for-windows/git#1211]
I'm not sure how to root cause this, mostly because I don't know where to look for this. To reproduce, from Git Bash, pass a string into a command that starts with a forward slash, like so (single quotes vs double quotes make no difference):

     $ git commit --allow-empty -m '/bar/ asdf'
     $ git commit --allow-empty -m "$(echo /bar)"
     $ git tag v0 -m "/foo"

The result is that the leading token (space-delimited? not sure) will be rewritten from a *nix pathspec to a Windows-style pathspec:

```
$ git show v0
tag v0
Tagger: Samuel Lijin <email>
Date:   Sat Jun 17 13:24:06 2017 -0400

C:/Program Files/Git/foo

commit ede90a7ebb2c3bf0f0d056cc4db05113fed68a80
Author: Samuel Lijin <email>
Date:   Sat Jun 17 13:21:39 2017 -0400

    C:/Program Files/Git/bar/ asdf
```

This does not happen when invoking Git from `cmd`. Observed in git 2.11.0.windows.3, also in this [StackOverflow question](https://stackoverflow.com/questions/44606854/).

Am happy to help by diving into source if you point me somewhere, but in a few days I won't have a lot of free time or a laptop.

**Comment by dscho** [comment]
I think that this entry of our [known issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues) covers this:

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
>
>    > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
>
>    Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "`//usr/bin/bash.exe`".

**Comment by dscho** [comment]
I assume that the reported issue is covered by said known issue, although I would have much preferred not having been forced to guess.

**Comment by sxlijin** [comment]
Oh, wow, yes, you're right. So sorry, I completely forgot about this.
