### ISSUE TITLE
Doing `git push --recurse-submodules=on-demand` when the parent repo is on the `develop` branch is broken on this new git version 2.13

### ISSUE THREAD

**Issue by evandrocoan** [git-for-windows/git#1212]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
The system cannot find the path specified.

$ type "C:\Program Files (x86)\Git\etc\install-options.txt"4
The system cannot find the file specified.

$ type "C:\Program Files\Git\etc\install-options.txt"
The system cannot find the path specified.

$ cat /etc/install-options.txt
cat: /etc/install-options.txt: No such file or directory

$ 
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Before the `git version 2.13`, everything was perfect around here, but now with this version they broke my workflow:

    Push: process for submodule 'Packages/Advanced CSV' failed
        D:\SublimeText\Data> git.exe push --porcelain --progress --tags --recurse-submodules=on-demand origin refs/heads/develop:refs/heads/develop
        src refspec 'refs/heads/develop' must name a ref
        process for submodule 'Packages/Advanced CSV' failed

I am using the `Smartgit` client, and now when I hit the push button, I got this error above. Searching I found it was a new update on git client the problem:

1. [\[smartgit\] Push on demand stopped working on SmartGit 17.0.4][1]

> It looks like the git push recurse-submodules behavior has changed.
Currently with 2.13 you cannot run "git push
--recurse-submodules=on-demand" if the parent repo is on a different
branch than the sub repos, e.g. parent repo is on "develop" and
sub-repo on "master". 

...

> I was under the impression that Jonathan and may be others considered
the fact that `git push --recurse-submodules=on-demand` doesn't work
as before an unintentional change. He asked me previously if pushing
without a refspec will work for us and I responded with a yes. The
question remains if everyone is on board with change push without
refspec to use `push.default` in the parent repo as well as
submodules.

> Cheers,

> JS

1. [git push recurse.submodules behavior changed in 2.13][2]
1. [How can I do `git push --recurse-submodules=on-demand` when the parent repo is on the `develop` branch with this new git version 2.13?](https://stackoverflow.com/questions/44641872/how-can-i-do-git-push-recurse-submodules-on-demand-when-the-parent-repo-is-o)

I did not understand the last part `without refspec to use push.default in the parent repo as well as submodules`, is it a way to `git push --recurse-submodules=on-demand` when the parent repo is on the `develop` branch and the submodules are on the `master` branch?

If it is not, how can I do `git push --recurse-submodules=on-demand` when the parent repo is on the `develop` branch, but the submodules are on the `master` branch with this new git version?

  [1]: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/smartgit/xVbPY2Hypro/GutIp9QTBAAJ
  [2]: https://public-inbox.org/git/CAE5=+KX57KM+6n9NpePw9KYPXFy7UH-WRgSwaJDnvRofYFXm7Q@mail.gmail.com/T/

___ 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
    $ git --version
    git version 2.13.0.windows.1

    $ systeminfo | findstr /B /C:"OS Version"
    OS Version:                10.0.15063 N/A Build 15063

    $ python --version
    Python 3.6.1 :: Anaconda 4.4.0 (32-bit)
```
___

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

1. You need create a main repository
1. Add a git submodule to it and checkout on the master branch
1. Go to your main repository and add the master branch.
1. Go to the submodule and commit some changes on its master branch, but do not push them.
1. Go to the main repository and commit the submodule head pointer change.
1. Go to the main repository and run the command `git.exe push --recurse-submodules=on-demand`

 - What did you expect to occur after running these commands?

I expect to the main repository and the submodule to be pushed to the its remote branch.

 - What actually happened instead?

After git version `2.13` I see the error `src refspec 'refs/heads/develop' must name a ref`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This issue happens mostly with my repository:

1. https://github.com/evandrocoan/SublimeTextStudio

Which as about 73 git submodules, checkout on the master branch, while the main repository is checkout on the development branch.

  [1]: https://github.com/wbond/package_control/issues
  [2]: https://github.com/wbond/package_control/issues/1233#issuecomment-308921923

**Comment by dscho** [comment]
Is this really a Windows-specific problem? If not, the Git project (which is blessed with more developers than this here project) may be a much better venue to discuss this problem.

It may also just be an intended change, in which case SmartGit needs to become "SmarterGit" ;-)

BTW it would be much easier to verify locally if a ready-to-be-cloned repository was available. I, for one, have no time right now to create a main repository with a submodule and then check things out and then commit some things and change directories multiple times and then call a special command, just to see whether I can reproduce a problem locally.

**Comment by evandrocoan** [comment]
Thanks for the time. Tomorrow I will look into writing a shell script which creates a repo ready to run the issue, and send this report to their mailing list: 

1. git@vger.kernel.org (https://public-inbox.org/git/)
1. https://groups.google.com/forum/?fromgroups#!forum/git-users

**Comment by dscho** [comment]
> Tomorrow I will look into writing a shell script which creates a repo ready to run the issue, and send this report to their mailing list

Great!

**Comment by evandrocoan** [comment]
I posted it on the email and google's group. This is the automated shell script to create the problem:
```shell
# Create the directory structure
rm -r -f main_repo
rm -r -f main_repo_remote
rm -r -f submodule_remote

mkdir main_repo_remote
mkdir submodule_remote
mkdir main_repo
mkdir main_repo/first_submodule

cd main_repo

# Setup the first_submodule
cd first_submodule
printf "# Submodule Repository\n\n" > README.md
git init
git add README.md
git commit -m "Added the repository first commit."

git init --bare ../../submodule_remote
git remote add origin ../../submodule_remote
git push origin master

# Setup the main_repo
cd ..
printf "# Main Repo\n\nThis is the main repository which contains submodules\n" > README.md
git init
git add README.md
git submodule add -- https://github.com/user/first_submodule "first_submodule"
git commit -m "Added the main repository first commit."

git init --bare ../main_repo_remote
git remote add origin ../main_repo_remote
git push origin master
git checkout -b develop
git push origin develop

# Add an unpushed commit to the submodule
cd first_submodule
printf "Dirty\n\n" >> README.md
git add README.md
git commit -m "Added the repository second commit."

# Go to the main repository and do the push
cd ..
git add first_submodule
git commit -m "Added the main repository second commit."
git push --recurse-submodules=on-demand --set-upstream origin develop
```

At its last line, I am doing the push on the main repo, but it is failing on the new git version.
Currently the solution is to manually open the submodules which need to be pushed and push them before to push the main repository, as the option `--recurse-submodules=on-demand` does not work on the main repository.

**Comment by dscho** [comment]
> I posted it on the email and google's group.

I seem to be unable to find it, though: https://public-inbox.org/git/?q=This+is+the+main+repository+which+contains+submodules

Maybe it was posted using plain text and HTML? The Git mailing list drops such mails silently (I know, this makes for a bad user experience, I am very sorry...)

But there is something in the release notes of 2.13.2 that looks as it may address your issue: https://github.com/git/git/blob/master/Documentation/RelNotes/2.13.2.txt#L11-L12.

Maybe the newest snapshot (which is slated to become Git for Windows v2.13.2) fixes it for you? https://wingit.blob.core.windows.net/files/index.html

**Comment by evandrocoan** [comment]
Thanks for looking into it. The issue fixed is just related to submodules on the second level deep. My problem is to push them on the first level deep. 

I tried this new version, but it stills failing on the script I posted here:
<details><p>

```
Professional@PROFESSIONAL-PC$ git --version
git version 2.13.1.windows.2.418.g914b84c9d9

Professional@PROFESSIONAL-PC$ sh bug.sh
Initialized empty Git repository in D:/User/Downloads/bug/main_repo/first_submodule/.git/
[master (root-commit) 65a4b59] Added the repository first commit.
 1 file changed, 2 insertions(+)
 create mode 100644 README.md
Initialized empty Git repository in D:/User/Downloads/bug/submodule_remote/
Counting objects: 3, done.
Writing objects: 100% (3/3), 249 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../../submodule_remote
 * [new branch]      master -> master
Initialized empty Git repository in D:/User/Downloads/bug/main_repo/.git/
Adding existing repo at 'first_submodule' to the index
[master (root-commit) bf0fd5b] Added the main repository first commit.
 3 files changed, 7 insertions(+)
 create mode 100644 .gitmodules
 create mode 100644 README.md
 create mode 160000 first_submodule
Initialized empty Git repository in D:/User/Downloads/bug/main_repo_remote/
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 427 bytes | 0 bytes/s, done.
Total 4 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master
Switched to a new branch 'develop'
Total 0 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      develop -> develop
[master ece9755] Added the repository second commit.
 1 file changed, 2 insertions(+)
[develop a67d44f] Added the main repository second commit.
 1 file changed, 1 insertion(+), 1 deletion(-)
fatal: src refspec 'develop' must name a ref
fatal: process for submodule 'first_submodule' failed
fatal: The remote end hung up unexpectedly
```
</p></details>

I am going to try to post there again only on plain text.

**Comment by evandrocoan** [comment]
I just found on my junk email folder, the response from the `git@vger.kernel.org ` saying ` Your address is not liked source for email`.

This is the email contents:

<details>

```
Originally posted on:
 
https://github.com/git-for-windows/git/issues/1212
 
My git version is:
git --version --build-options
 
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86
 
cmd.exe /c ver
Microsoft Windows [Version 10.0.15063]
 
Before the `git version 2.13`, everything was perfect around here, but now with this version they broke my workflow:
 
Push: process for submodule 'Packages/Advanced CSV' failed
D:\SublimeText\Data> git.exe push --porcelain --progress --tags --recurse-submodules=on-demand origin refs/heads/develop:refs/heads/develop
src refspec 'refs/heads/develop' must name a ref
process for submodule 'Packages/Advanced CSV' failed
 
 
quote:
It looks like the git push recurse-submodules behavior has changed.
Currently with 2.13 you cannot run "git push
--recurse-submodules=on-demand" if the parent repo is on a different
branch than the sub repos, e.g. parent repo is on "develop" and
sub-repo on "master".
...
I was under the impression that Jonathan and may be others considered
the fact that `git push --recurse-submodules=on-demand` doesn't work
as before an unintentional change. He asked me previously if pushing
without a refspec will work for us and I responded with a yes. The
question remains if everyone is on board with change push without
refspec to use `push.default` in the parent repo as well as
submodules.
 
Cheers,
JS
 
git push recurse.submodules behavior changed in 2.13 https://public-inbox.org/git/CAE5=+KX57KM+6n9NpePw9KYPXFy7UH-WRgSwaJDnvRofYFXm7Q@mail.gmail.com/T/
 
I did not understand the last part `without refspec to use push.default in the parent repo as well
as submodules`, is it a way to `git push --recurse-submodules=on-demand` when the parent repo is on
the `develop` branch and the submodules are on the `master` branch?
 
If it is not, how can I do `git push --recurse-submodules=on-demand` when the parent repo is on the
`develop` branch, but the submodules are on the `master` branch with this new git version?
 
 
 
What commands did you run to trigger this issue? If you can provide a
Minimal, Complete, and Verifiable example http://stackoverflow.com/help/mcve
this will help us understand the issue.
 
1. You need create a main repository
2. Add a git submodule to it and checkout on the master branch
3. Go to your main repository and add the master branch.
4. Go to the submodule and commit some changes on its master branch, but do not push them.
5. Go to the main repository and commit the submodule head pointer change.
6. Go to the main repository and run the command `git.exe push --recurse-submodules=on-demand`
 
This shell script creates some repositories and remotes which reproduce the problem:
 
 
# Create the directory structure
rm -r -f main_repo
rm -r -f main_repo_remote
rm -r -f submodule_remote
 
mkdir main_repo_remote
mkdir submodule_remote
mkdir main_repo
mkdir main_repo/first_submodule
 
cd main_repo
 
# Setup the first_submodule
cd first_submodule
printf "# Submodule Repository\n\n" > README.md
git init
git add README.md
git commit -m "Added the repository first commit."
 
git init --bare ../../submodule_remote
git remote add origin ../../submodule_remote
git push origin master
 
# Setup the main_repo
cd ..
printf "# Main Repo\n\nThis is the main repository which contains submodules\n" > README.md
git init
git add README.md
git submodule add -- https://github.com/user/first_submodule "first_submodule"
git commit -m "Added the main repository first commit."
 
git init --bare ../main_repo_remote
git remote add origin ../main_repo_remote
git push origin master
git checkout -b develop
git push origin develop
 
# Add an unpushed commit to the submodule
cd first_submodule
printf "Dirty\n\n" >> README.md
git add README.md
git commit -m "Added the repository second commit."
 
# Go to the main repository and do the push
cd ..
git add first_submodule
git commit -m "Added the main repository second commit."
git push --recurse-submodules=on-demand --set-upstream origin develop
 
 
At its last line, I am doing the push on the main repo, but it is failing on the new git version.
Currently the solution is to open the submodules which need to be pushed and push them before to
push the main repository. The problem is that the `--recurse-submodules=on-demand` should work, but
it is not.
 
 
What did you expect to occur after running these commands?
I expect to the main repository and the submodule to be pushed to the its remote branch.
 
 
What actually happened instead?
After git version `2.13` I see the error `src refspec 'refs/heads/develop' must name a ref`
 
If the problem was occurring with a specific repository, can you provide the URL to that repository
to help us with testing?
 
This issue happens mostly with my repository on its develop branch:
 
https://github.com/evandrocoan/SublimeTextStudio
 
Which has about 73 git submodules, checkout on the master branch, while the main repository is
checkout on the develop branch.
```
</details>

**Comment by dscho** [comment]
Let's see whether we can raise some experts here, if vger is keeping people out again.

@sbeller? @bmwill? Any idea what's up with those submodule operations now failing?

**Comment by stefanbeller** [comment]
I still see no email on the list containing "Which has about 73 git submodules," 
Thanks for reaching out here.

I haven't had much time lately (as I was deep in other stuff), but I think we should either allow more submodule related refspecs to go through, or introduce a mode similar to the push.default option, which when unset warns the user boldly.

**Comment by jrn** [comment]
> Let's see whether we can raise some experts here, if vger is keeping people out again.

Any idea what the nature of vger keeping people out is? Since as you correctly pointed out this isn't Windows-specific, this really is not the place to solve it.

Sent http://public-inbox.org/git/20170627162307.GE161648@aiede.mtv.corp.google.com on evandrocoan's behalf. Please continue discussion there.

**Comment by PhilipOakley** [comment]
There are two or three (or more) methods that vger uses to control spam.

1. it demands that there is no HTML. Almost all spam has HTML in it, and so it's a good filter...
2. it has a big list of banned words and phrases. so don't use the any of the classic spam words. 
3. it has a size limit of about 150kb (IIRC), so very big patches can get lost.
4. Then there is the sender white list (of some sort). The first posting can take up to 48 hours to appear, even if it passes 1-3. So getting it right can be frustrating if the advice about doing a self test isn't followed.

http://vger.kernel.org/majordomo-info.html is the place to start

**Comment by goostleek** [comment]
The latest version is 2.18 and the problem still exists.

**Comment by dscho** [comment]
@goostleek pinging here won't have much effect, as it will only reach one overworked maintainer and preciously few submodule experts. Please do consider to reply to @jrn's mail on the mailing list, to prod gently the people who may be able to help you.
