### ISSUE TITLE
Git's filter stdin not work for large file size (>= 4GBs)

### ISSUE THREAD

**Issue by quangnt** [git-for-windows/git#1213]
Salutations!
I encounter issue that when use "git-fat" to add large file size (>= 4GBs) in windows (Windows 64 bits, git 2.8.3 64bit, and python 2.7.11 64 bit), after run git add <large file size> and call "git-fat filter-clean" in git's mingw with standard input(stdin) is large file size, it didn't work but it worked for file size < 4GBs. Is there anyone know the reason of this?

**Comment by dscho** [comment]
What is git-fat?

**Comment by quangnt** [comment]
@dscho  Sorry for confusing. git-fat is a tool that uses git-filter to process add large file to project without adding real large file size (just add an index file point to another repo which stores large file) you can refer following link [git-fat](https://github.com/jedbrown/git-fat) for more information.

**Comment by dscho** [comment]
While `git-fat` sounds interesting to play with, I have too much else to do these days :frowning_face: 

If you can come up with a concise test case reproducing the issue without any external dependencies, using only a minimal set of commands, I will see what I can do about fixing the bug.

**Comment by quangnt** [comment]
Thank so much for your reply, but currently don't know how to create a minimal set of git commands to reproduce this issue yet so close this here, when I figure out how to create reproduce commands will reopen this again.
