### ISSUE TITLE
ssh double key input with windows 10

### ISSUE THREAD

**Issue by rvhelden** [git-for-windows/git#1215]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.13.1.windows.2
built from commit: a36e14b3aaa0ddb633c40a9c8483e6fe12d99616
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.16199.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using a preview version of windows 10 enterprise

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh user@address
```
 - What did you expect to occur after running these commands?

It asks for the password, after entering it correctly it should show the following

```
Welcome to Ubuntu 17.04 (GNU/Linux 4.10.0-19-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * UbuCon Latin America, Lima, Peru, August 17-18, 2017
   - https://ubu.one/ubulat17
```

 - What actually happened instead?

After entering the correct password it shows nothing until I hit the key 'Enter' four times.
From there after I have to enter every character twice for it to show up on the screen.

I have reproduced it also at another windows 10 pc having the exact same issues. Tried a windows 7 machine and it works as expected. Haven't tried the latest public build of windows 10.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It happens with every version went even back to version 2.11.0 and happens there to.

**Comment by dscho** [comment]
> Microsoft Windows [Version 10.0.16199.1000]

This is a pretty good tell-tale for the real issue: there have been reports of Insider builds displaying problems like the one you reported. Have a look at https://github.com/git-for-windows/git/issues/1172. It seems that 16215 has a fix.
