### ISSUE TITLE
the command: git log --pretty=format:'%H %ci' does not work, requires double-quotes ("") on Windows

### ISSUE THREAD

**Issue by alvinpenner** [git-for-windows/git#1216]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git for Windows are you using? 32-bit

```
$ git --version --build-options

** insert your machine's response here **
git version 2.7.1.windows.2

 - Which version of Windows are you running? Vista, 7, 8, 10? Windows 10 - 64-bit

```
$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [Version 10.0.15063]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

``` defaults

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\Users\penne_000\AppData\Roaming\InkscapeGit>git log --pretty=format:'%H %ci' 0edfdf95
fatal: ambiguous argument '%ci'': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'```
 - What did you expect to occur after running these commands?

C:\Users\penne_000\AppData\Roaming\InkscapeGit>git log --pretty=format:"%H %ci" 0edfdf95
0edfdf950796befdb42ab9b2ef76c76483d9dbb1 2017-06-21 21:04:53 -0300

 - What actually happened instead?

see above

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://gitlab.com/inkscape/inkscape

**Comment by tbnorth** [comment]
Not sure if my message got through on inkscape-devel, but this isn't a git issue, it's just a matter of how different command line environments quote text.  "" or '' will work in unix style command lines like bash, only "" works in Windows' cmd environment.

**Comment by Ede123** [comment]
If that command works depends on implementation...
While the Windows shell might not offer argument grouping via `'` Git for Windows might well work around this by combining separate arguments until finding the closing quote...

**Comment by dscho** [comment]
> this isn't a git issue, it's just a matter of how different command line environments quote text. "" or '' will work in unix style command lines like bash, only "" works in Windows' cmd environment.

I agree.

Unix-y people may be so used to having double-quoted and single-quoted arguments (with double-quoted arguments interpolating environment variables) that they forget that un-quoting is the duty of the shell. Windows' command prompts work differently from Unix shells, which should not come as a surprise.
