### ISSUE TITLE
Investigate why repo-add does not understand the -f flag anymore

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#122]
There is now a warning when running `pacman-mirror.sh push` because the -f flag is not supported anymore, apparently. Have a look at the Pacman repository to figure out whether we simply need to skip the "big" package index.

**Comment by elieux** [comment]
Pacman upstream removed this option in favor of automatic creation of the `files` database. See Alexpux/MSYS2-pacman@cb0f2bd0385f447e045e2b2aab9ffa55df3c2d8a and
Alexpux/MSYS2-pacman@b630f455d2cb3a4c11b2de65285657ea7ec6f3c3.

In effect, `repo-add foo.db.tar.xz` will now update both `foo.db.tar.xz` and `foo.files.tar.xz` (and the symlinks/copies and backups).

**Comment by dscho** [comment]
Thanks, @elieux, You saved me quite some time!
