### ISSUE TITLE
Just a little help pls

### ISSUE THREAD

**Issue by MarcusCaepio** [git-for-windows/git#1221]
Hey all,
just installed git for win today, but need a few starter tipps. So please excuse that I did not fill the template.
I nearly need two things right now:
- change the homedirectory, which is set when I open git bash. Because of reasons, I cannot change Win Environemnts, so I have to set this for git only. ATM when I create SSH keys or simple just start the bash, I start in a directory, where I don't want to get to
- How do I change the git prompt? I already tried to change the PS1 values in /etc/profile but it seems not to work. As I now have as prompt my "verylongname"@"evenlongerhostname"+etc. it is not very comfortable. I also want to delete the "newline" after the prompt and after every command execution.

Thanks in advance! And thanks for making git on windows happen!

**Comment by shiftkey** [comment]
These are general bash usage questions, and there's other places to ask than here:

 - [How to change your default directory in bash](https://unix.stackexchange.com/a/140603)
 - [Bash prompt basics](https://linuxconfig.org/bash-prompt-basics)

**Comment by MarcusCaepio** [comment]
Sorry, but I know how to edit my prompt and directory on Linux. But here we are talking about a git bash on Windows and the steps either don't work or I make it wrong. So instead of just closing my question, it just would be nice to answer my question, since I am testing git for win the first time. Of course I just could go back to Linux, but I don't think that's the sense why you guys are making this.

**Comment by kostix** [comment]
Hi, @MarcusCaepio!

One problem with your query is that you've posted it into a bug tracker which is not a place for asking general questions — it's for reporting bugs and tracking progress on squashing them.

Please try posting your question to the [mailing list dedicated to Git for Windows](http://groups.google.com/group/git-for-windows) insted — chances are high you'll get help there.
