### ISSUE TITLE
Enhancement: Separate sh.exe into a different bin directory

### ISSUE THREAD

**Issue by mcandre** [git-for-windows/git#1223]
I would like to be able to invoke `sh -c "..."` from a native Command Prompt terminal session, without overriding Windows tools like find.exe. Accordingly, could we move the sh.exe to a different bin directory?

That way, users can add sh.exe to PATH without overriding Windows utilities.

**Comment by dscho** [comment]
Sure, if you work on it, get it to run correctly, and open a Pull Request, I will certainly merge it.
