### ISSUE TITLE
HEAD and head refer to different revisions when in a worktree

### ISSUE THREAD

**Issue by warwickmm** [git-for-windows/git#1225]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

I am using the portable installation with default settings.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash
```
$ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

In version 2.13.0, `head` and `HEAD` refer to different revisions when in a worktree:
```
$ git --version
git version 2.13.0.windows.1

$ git init
Initialized empty Git repository in C:/Users/warwickmm/Documents/projects/test/.git/

$ echo "Hello" > hello.txt
$ git add . && git commit -m "Add hello."
[master (root-commit) d10516b] Add hello.
 1 file changed, 1 insertion(+)
 create mode 100644 hello.txt

$ echo "Bye" > bye.txt
$ git add . && git commit -m "Add bye."
[master 80ef77d] Add bye.
 1 file changed, 1 insertion(+)
 create mode 100644 bye.txt

$ git worktree add -b feature/branch ../branch master~
Preparing ../branch (identifier branch)
HEAD is now at d10516b Add hello.

$ cd ../branch

$ git symbolic-ref head
refs/heads/master

$ git symbolic-ref HEAD
refs/heads/feature/branch
```

If I then open a new shell using version 2.12.2, `head` and `HEAD` both refer to the same revisions when in the worktree created above:
```
$ git --version
git version 2.12.2.windows.2

$ cd /c/Users/warwickmm/Documents/projects/test

$ git symbolic-ref head
refs/heads/feature/branch

$ git symbolic-ref HEAD
refs/heads/feature/branch
```

This does not appear to be an issue when _not_ in a worktree:
```
$ git --version
git version 2.13.0.windows.1

$ git init
Initialized empty Git repository in C:/Users/warwickmm/Documents/projects/test/.git/

$ echo "Hello" > hello.txt
$ git add . && git commit -m "Add hello."
[master (root-commit) b280df9] Add hello.
 1 file changed, 1 insertion(+)
 create mode 100644 hello.txt

$ echo "Bye" > bye.txt
$ git add . && git commit -m "Add bye."
[master 454dbf6] Add bye.
 1 file changed, 1 insertion(+)
 create mode 100644 bye.txt

$ git checkout -b feature/branch master~
Switched to a new branch 'feature/branch'

$ git symbolic-ref head
refs/heads/feature/branch

$ git symbolic-ref HEAD
refs/heads/feature/branch
```

 - What did you expect to occur after running these commands?

I expected that `head` and `HEAD` will always point to the same revision (the tip of the current branch).

**Comment by warwickmm** [comment]
This issue can also be reproduced in version `git version 2.13.2.windows.1`.

**Comment by warwickmm** [comment]
It turns out that this is something that affects all case-insensitive filesystems, and isn't specific to this project.  See the git mailing list discussion here:

https://public-inbox.org/git/20170711033236.GA11492@lenny.localdomain/

Best practice is to _not_ use `head`, as there are many other examples where it can lead to undesired behavior.

**Comment by kostix** [comment]
To make it (maybe more) clear: the current implementation of Git (and GfW, too) uses physical files located in the "Git data directory" (typically it's the ".git" folder located in every non-bare repository) to represent most¹ "refs" — which are tags and branches.

This interacts badly with case-insensitive filesystems

----

¹ The refs which are not used for some amount of time may eventually transition to the so-called "pack files" due to bookkeeping procedures.  In this state, they are no longer represented as regular files.
