### ISSUE TITLE
Can't find "git bash here" in context menu when I am in windows libraries

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#1229]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.10586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

### Details

I have multi git repositories on my computer,and they are in different folders.
So,I am using the libraries to include the repository,then I can quickly find the repository in the library I created.
But when I right click in a repository I opened in library.I can not find the "git bash here" in the context menu.
[how-to-use-libraries-in-windows-10](https://www.geeksinphoenix.com/blog/post/2016/07/06/how-to-use-libraries-in-windows-10.aspx)

**Comment by dscho** [comment]
> how-to-use-libraries-in-windows-10

From this link:

> unlike a folder, a Library gathers files that are stored in several locations. This is a subtle, but important, difference. Libraries don't actually store your files, just shortcuts to them. 

That means: it is not a directory. You cannot create directories in it, including `.git`. It cannot be the current working directory of any program, including Git Bash.

In short: this is probably never going to work.

**Comment by chucklu** [comment]
@dscho Hi,  I have test it. I can create a new folder in library.
When I right click,I can see the context menu from TortoiseGit
![default](https://user-images.githubusercontent.com/3004057/28200052-47a799e8-689c-11e7-8ef5-6f31cb166572.png)

The default path showed is Librarie-->Git-->gitignore
When I click the path,it become the actual path directly.
![default](https://user-images.githubusercontent.com/3004057/28200098-8cfadb9a-689c-11e7-9555-0b6f2b7bb6ca.png)
![default](https://user-images.githubusercontent.com/3004057/28200094-851ed7dc-689c-11e7-98ce-7c965fd321f4.png)

**Comment by chucklu** [comment]
Libraries was first introduced in win7 https://en.wikipedia.org/wiki/Features_new_to_Windows_7#Libraries

**Comment by YueLinHo** [comment]
cf. https://github.com/TortoiseGit/TortoiseGit/blob/master/src/Utils/Libraries.cpp

**Comment by dscho** [comment]
This is how Git for Windows installs `Git Bash Here`: https://github.com/git-for-windows/build-extra/blob/a8f38d62572a4b5c8477ebeb0857316ba36c3016/installer/install.iss#L1988-L1999.

If anyone figures out which other registry keys we would need to add to support Libraries, I'll be happy to merge a Pull Request adding said support.

**Comment by dscho** [comment]
(A quick look at https://msdn.microsoft.com/en-us/library/windows/desktop/cc144110(v=vs.85).aspx did not reveal anything that would jump into my eye.)

**Comment by YueLinHo** [comment]
@chucklu After some further testing, I got a workaround for you: Using Right click **on** folder

See:

Further testing...

# Good 1

![image](https://user-images.githubusercontent.com/5831804/28235646-c789bf4e-6944-11e7-81f8-38a4e826cdc0.png)

# Bad 1

![image](https://user-images.githubusercontent.com/5831804/28235717-2a2c7e92-6946-11e7-823d-26de1384ae77.png)


# Good 2 (Can be a workaround)

![image](https://user-images.githubusercontent.com/5831804/28235673-3f7b1b42-6945-11e7-90b3-8fbd428b99c4.png)

# Bad 2

![image](https://user-images.githubusercontent.com/5831804/28235703-de97e534-6945-11e7-87fd-8867a2984e35.png)

**Comment by chucklu** [comment]
@YueLinHo  thanks a  lot

@dscho Could you reopen this issue,maybe someone can fix this. Or you can add a label "help wanted",thanks.

**Comment by chucklu** [comment]
@dscho would you fix this ?or reopen it?

**Comment by dscho** [comment]
> would you fix this ?

As I mentioned earlier, I have no idea whatsoever whether this *can* be fixed.

> or reopen it?

You will have to put in some effort to show that your wish *can* be addressed, that it *is* possible to initialize a repository in a Library. Otherwise it would just waste everybody's time if I reopened this ticket.

**Comment by chucklu** [comment]
@dscho   I have test it,I can create a repository in Library folder by TortoiseGit
You can check the screenshot
![default](https://user-images.githubusercontent.com/3004057/29101693-9c22587e-7ce6-11e7-99b0-3f88ec21fd55.png)
![default](https://user-images.githubusercontent.com/3004057/29101697-a9103452-7ce6-11e7-8a52-ff4a06a4d1bb.png)
![default](https://user-images.githubusercontent.com/3004057/29101702-b7885e7e-7ce6-11e7-914e-0770c682a3b7.png)

**Comment by YueLinHo** [comment]
@dscho Based on your [comment](https://github.com/git-for-windows/git/issues/1229#issuecomment-315462647) which shows me the way how GfW to add context menu items. I studied some, then, I finally found the possible way to go, that I use the following registry:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\LibraryFolder\background\shell\git_gui]
@="Git &GUI Here"
"Icon"="C:\\Program Files\\Git\\cmd\\git-gui.exe"

[HKEY_CLASSES_ROOT\LibraryFolder\background\shell\git_gui\command]
@="\"C:\\Program Files\\Git\\cmd\\git-gui.exe\" \"--working-dir\" \"%v.\""

[HKEY_CLASSES_ROOT\LibraryFolder\background\shell\git_shell]
@="Git Ba&sh Here"
"Icon"="C:\\Program Files\\Git\\git-bash.exe"

[HKEY_CLASSES_ROOT\LibraryFolder\background\shell\git_shell\command]
@="\"C:\\Program Files\\Git\\git-bash.exe\" \"--cd=%v.\""
```

![before](https://github.com/YueLinHo/build-extra/blob/temp/gi_1229_before.png) & ![after](https://github.com/YueLinHo/build-extra/blob/temp/gi_1229_after.png) (Somehow I can't attach the image files)

PR? I don't know how to test the changes in build-extra. Should I build the whole Git for Windows? and build the installer?

----

For a record, TortoiseGit uses [Shell Extension](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144110.aspx), not [Shortcut (Context) Menus](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144175.aspx) which is used by GfW.

**Comment by YueLinHo** [comment]
For testing, first of all, you need to create the Git Library:
1. Go TortoiseGit Settings
2. Push the "Create Library" button see [image](https://github.com/YueLinHo/build-extra/blob/temp/gi_1229_how%20to%20create%20libraries.png)

**Comment by dscho** [comment]
@YueLinHo what a lovely contribution, thank you so much!!!

**Comment by YueLinHo** [comment]
@dscho Thanks for your help. b^^d

**Comment by chucklu** [comment]
@YueLinHo  @dscho  Thanks a lot!
