### ISSUE TITLE
Permission denied for /tmp

### ISSUE THREAD

**Issue by danny0838** [git-for-windows/git#123]
Using Git-2.3.7.1-dev-preview-64-bit.exe, it seems that /tmp is not writable so that some programs using /tmp for temp files cannot work properly. Am I doing something wrong and how to fix this?

**Comment by dscho** [comment]
@danny0838 Please state which programs use `/tmp` and what the values of your `TMP`, `TEMP` and `TMPDIR` environment variables are (both Windows-global and inside the Git Bash).

**Comment by danny0838** [comment]
I'm not sure if I get it correctly. Here is the result in Git Bash:

```
Danny@DANNY-CJ MINGW64 /d/Users/Danny/Desktop
$ echo $TMP
/c/Users/Danny/AppData/Local/Temp

Danny@DANNY-CJ MINGW64 /d/Users/Danny/Desktop
$ echo $TEMP
/c/Users/Danny/AppData/Local/Temp

Danny@DANNY-CJ MINGW64 /d/Users/Danny/Desktop
$ echo $TMPDIR
/c/Users/Danny/AppData/Local/Temp
```

And in Windows command:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Danny>echo %TMP%
C:\Users\Danny\AppData\Local\Temp

C:\Users\Danny>echo %TEMP%
C:\Users\Danny\AppData\Local\Temp

C:\Users\Danny>echo %TMPDIR%
%TMPDIR%
```

**Comment by dscho** [comment]
That all looks correct, except for the explicit `echo ... >/tmp/...`. The `/tmp` directory is required by the bash, but it is not really used, at least in my tests here (one exception: the installer writes a `git-wrapper.exe` there, but it also removes it right away, as per the newest development versoin).

**Comment by dscho** [comment]
> @danny0838 Please state which programs use /tmp

I guess this is still an open question...

**Comment by nalla** [comment]
When you installed `Git-2.3.7.1-dev-preview-64-bit.exe` did the *UAC* (User Access Control) popped up for you? If so, maybe the `tmp` dir within `C:\path\to\Git\tmp` is *really* restricted for you (the user that runs the *Git Bash*.

**Comment by danny0838** [comment]
Oh! I install it using the Administrator privilege and installed it to C:\Program Files\Git\tmp. And yes it's restricted for a normal windows user to access.

**Comment by dscho** [comment]
> Maybe the problem is that programs using /tmp should use $TMPDIR instead.

Indeed, that is the problem. Note: this was *already* a problem with Git for Windows 1.x; it is not new.

For a while I was wondering whether the program accessing `/tmp/` directly was part of Git for Windows, but I guess it is not? You still have not mentioned [which program it is](https://github.com/git-for-windows/git/issues/123#issuecomment-97756299)...

**Comment by danny0838** [comment]
The only one I can recall is `tac`, but it appears to work now. Since I've upgrade Git for Windows recently I probably have messed it up. Currently I can only make sure that `echo "test" > /tmp/test.txt` doesn't work in 2.3.7.1. I'll make a further report if another one found.
