### ISSUE TITLE
zsh breaks after msys2-runtime v2.8.1

### ISSUE THREAD

**Issue by the-nic** [git-for-windows/git#1230]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options
git version 2.13.2.windows.1
built from commit: 914b84c9d949b14a135ab50c8b881cdee9be116c
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

n/a
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This is Git-Sdk-64

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Using the git-sdk installation, install zsh using pacman. Configured zprezto for zsh, now it will crash
```
zsh --login
```
 - What did you expect to occur after running these commands?

zsh starts

 - What actually happened instead?

zsh Segfaults

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

### Addititional information

This regression was introduced by commit f73bc7ddae44

As discussed in the MSYS2 issue (https://github.com/Alexpux/MSYS2-packages/issues/793 ), this is caused by the patches that are supposed to fix undefined behavior:
```
msys2-runtime/0050-Avoid-comparing-this-to-NULL.patch
msys2-runtime/0051-Avoid-assert-this-statements.patch
```
And was eventually worked around by https://github.com/Alexpux/MSYS2-packages/pull/804/commits/914147e3d3f7c46bf7aee2e3d9235cb4e210b388

Also, cygwin reverted a similar patch, also citing a zsh issue: https://sourceware.org/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=41abcc5825d33d78bd370997ba664e3c64eb6683

**Comment by oysteinkrog** [comment]
I can confirm this, fairly annoying as there is no good workaround.

**Comment by oysteinkrog** [comment]
Found a workaround:
pacman -U http://repo.msys2.org/msys/x86_64/msys2-runtime-2.6.1-1-x86_64.pkg.tar.xz http://repo.msys2.org/msys/x86_64/msys2-runtime-devel-2.6.1-1-x86_64.pkg.tar.xz

**Comment by dscho** [comment]
> I can confirm this,

Good.

> fairly annoying as there is no good workaround.

Not so good. Unnecessarily inflammatory, and thereby fairly annoying a statement itself.

> Found a workaround:
> pacman -U http://repo.msys2.org/msys/x86_64/msys2-runtime-2.6.1-1-x86_64.pkg.tar.xz http://repo.msys2.org/msys/x86_64/msys2-runtime-devel-2.6.1-1-x86_64.pkg.tar.xz

A better idea would be to follow https://github.com/git-for-windows/git/wiki/Building-msys2-runtime#rebuild-the-msys2-runtime, try to revert those patches, or dig deeper otherwise, to get this fixed.

This is really a very low-priority bug as far as I am concerned in my role as the Git for Windows maintainer: Git for Windows does not even ship with `zsh`. You have to be a power user to set up a system with `zsh` as your shell. And as you are a power user who is able to do that, I can rightfully expect you to be competent enough not to throw this into my court, but to debug at least a little bit on your own.

**Comment by oysteinkrog** [comment]
@dscho: sorry about that, was not intended to annoy.
You are correct in everything you say, except that I don't actually think this bug is specific to zsh, it just so happens to manifest badly there.

**Comment by oysteinkrog** [comment]
I tested latest updates/runtime now, and this appears to be fixed. I think this issue can be closed.

**Comment by dscho** [comment]
> I tested latest updates/runtime now, and this appears to be fixed.

Thanks for reporting back.

> I think this issue can be closed.

Done!
