### ISSUE TITLE
cmd behaves strangely in Git bash

### ISSUE THREAD

**Issue by mcandre** [git-for-windows/git#1231]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.2.windows.1
built from commit: 914b84c9d949b14a135ab50c8b881cdee9be116c
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cmd /c "echo howdy"
```
 - What did you expect to occur after running these commands?

"howdy" is displayed.

 - What actually happened instead?

An unterminated cmd session appears.

As a workaround, cmd can be invoked from Git bash as `cmd.exe`:

```console
$ cmd.exe /c "echo howdy"
howdy
```

In bash on Ubuntu on Windows, AKA Windows Subsystem for Linux, `cmd` is not found in `$PATH`, so `cmd.exe` must be used instead.

Note that the command, `cmd /c "echo howdy"`, does work without modification in other shells:

* cmd.exe
* Powershell
* MSYS2

Curious what's causing `cmd` to behave differently from `cmd.exe` in Git bash. It's like the former receives an empty argv or something.

**Comment by landstander668** [comment]
This is caused by the POSIX-to-Windows path conversion which MSYS2 performs, which is mentioned in the release notes. Your options are to double up the first slash, or set the environment variable MSYS_NO_PATHCONV to 1... both options disable this behaviour. For example:

```
adrics@VM1$ cmd //c "echo howdy"
howdy

adric@VM1$ MSYS_NO_PATHCONV=1 cmd /c "echo howdy"
howdy
```

**Comment by dscho** [comment]
No feedback means it worked. I guess.
