### ISSUE TITLE
Git failed to build with VS2017 due to error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory

### ISSUE THREAD

**Issue by KarenHuang2016** [git-for-windows/git#1234]
### Setup
 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
$ git --version --build-options
git version 2.9.2.windows.1
sizeof-long: 4
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows Server 2016 64-bit + VS2017.2
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]

**Repro steps:**
1. git clone https://github.com/git-for-windows/git.git D:\git\src
2. git checkout vs/master
3. devenv /upgrade git.sln
4. nuget.exe restore git.sln
5. msbuild /m /p:Configuration=Release;Platform=x86 /p:WindowsTargetPlatformVersion=10.0.15063.0 /t:Rebuild git.sln

**Error info:**
d:\git\src\compat/mingw.h(179): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory (s:\dd\feature\winc\src\vctools\compiler\cxxfe\sl\p1\c\p0prepro.c:1654) [D:\Git\src\libgit\libgit.vcxproj]

**Comment by dscho** [comment]
I think that the OpenSSL dependency only works for platform toolset v140 for now. can you give that a try?

**Comment by KarenHuang2016** [comment]
@dscho, yes, we can build git sucessfully with VS2015. We moved to VS2017 now. Could you please try to support VS2017?

**Comment by dscho** [comment]
@KarenHuang2016 as far as I recall, VS2017 supports platform toolset v140, you just have to configure it correctly?

As to adding support for VS2017: I would love to, I simply do not have the time. Feel free, however, to help with this effort, e.g. by editing `libgit/libgit.vcxproj` so that it finds `openssl/ssl.h`. We have some conditional blocks in there that already demonstrate how to add include paths for dependencies that do not support even platform toolset v140.

**Comment by KarenHuang2016** [comment]
@dscho, I tried to add the v140 openssl path (openssl.v140.windesktop.msvcstl.dyn.rt-dyn.x86.1.0.2.1\build\native\include) to AdditionalIncludeDirectores for libgit.vcxproj. libgit.vcxproj can be built sucessfully.
But all the test projects like test-delta failed due to some link errors:
1>------ Build started: Project: test-delta, Configuration: Debug x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\CL.exe /c /ID:\Git\src\compat\vcbuild\GEN.PKGS\libssh2.1.4.3.3\build\native\../..//build/native/include/ /ID:\Git\src\compat\vcbuild\GEN.PKGS\libiconv.1.14.0.11\build\native\../..//build/native/include/ /ID:\Git\src\compat\vcbuild\GEN.PKGS\expat.2.1.0.11\build\native\../..//build/native/include/ /ID:\Git\src\compat\vcbuild\GEN.PKGS\curl.7.30.0.2\build\native\../..//build/native/include/ /I..\..\..\. /I"..\..\..\compat\vcbuild\GEN.PKGS\openssl.v140.windesktop.msvcstl.dyn.rt-dyn.x86.1.0.2.1\build\native\include" /I"..\..\..\compat\vcbuild\GEN.PKGS\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\include" /I..\..\..\compat /I..\..\..\compat\poll /I..\..\..\compat\regex /I..\..\..\compat\vcbuild\GEN.DEPS\include /I..\..\..\compat\vcbuild\GEN.DEPS\include\expat /I..\..\..\compat\vcbuild\GEN.DEPS\include\zlib /I..\..\..\compat\vcbuild\include /I..\..\..\compat\win32 /I"c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" /I"c:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt" /I"c:\Program Files (x86)\Windows Kits\8.1\Include\shared" /I"c:\Program Files (x86)\Windows Kits\8.1\Include\um" /Zi /nologo /W1 /WX- /diagnostics:classic /Od /Ob1 /D HAS_EXPAT /D HAS_LIBCURL /D WIN32 /D _DEBUG /D "DEFAULT_HELP_FORMAT=\"html\"" /D DETECT_MSYS_TTY /D HAVE_ALLOCA_H /D HAVE_STRING_H /D NATIVE_CRLF /D NDEBUG /D NOGDI /D NO_GETTEXT /D NO_INET_NTOP /D NO_INET_PTON /D NO_INTTYPES_H /D NO_IPV6 /D NO_LIBGEN_H /D NO_MEMMEM /D NO_MKDTEMP /D NO_POLL /D NO_POSIX_GOODIES /D NO_PREAD /D NO_SETENV /D NO_STRCASESTR /D NO_STRLCPY /D NO_STRTOUMAX /D NO_ST_BLOCKS_IN_STRUCT_STAT /D NO_SYMLINK_HEAD /D NO_SYS_POLL_H /D OBJECT_CREATION_MODE=1 /D "PAGER_ENV=\"LESS=FRX LV=-c\"" /D PROTECT_NTFS_DEFAULT=1 /D RUNTIME_PREFIX /D "SHA1DC_CUSTOM_INCLUDE_SHA1_C=\"cache.h\"" /D "SHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"git-compat-util.h\"" /D "SHA1DC_CUSTOM_TRAILING_INCLUDE_SHA1_C=\"sha1dc_git.c\"" /D "SHA1DC_CUSTOM_TRAILING_INCLUDE_SHA1_H=\"sha1dc_git.h\"" /D SHA1DC_INIT_SAFE_HASH_DEFAULT=0 /D SHA1DC_NO_STANDARD_INCLUDES /D SHA1_DC /D "SHELL_PATH=\"/bin/sh\"" /D "STRIP_EXTENSION=\".exe\"" /D UNRELIABLE_FSTAT /D USE_CURL_FOR_IMAP_SEND /D USE_WIN32_MMAP /D WIN32 /D _CONSOLE /D _CRT_NONSTDC_NO_DEPRECATE /D _CRT_SECURE_NO_WARNINGS /D __USE_MINGW_ACCESS /Gm /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\Debug\\" /Fd"x64\Debug\vc141.pdb" /Gd /TC /errorReport:prompt           -nologo "..\..\..\common-main.c" "..\..\..\t\helper\test-delta.c"
1>test-delta.c
1>common-main.c
1>Generating Code...
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\link.exe /ERRORREPORT:PROMPT /OUT:"..\test-delta.exe" /INCREMENTAL /NOLOGO advapi32.lib kernel32.lib ntdll.lib shell32.lib user32.lib wininet.lib ws2_32.lib ..\..\..\compat\vcbuild\GEN.PKGS\libiconv.1.14.0.11\build\native\lib\v110\x64\Release\dynamic\cdecl\libiconv.lib /MANIFEST:NO /DEBUG:FASTLINK /PDB:"..\test-delta.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"..\test-delta.lib" /MACHINE:X64 invalidcontinue.obj "x64\Debug\common-main.obj"
1>"x64\Debug\test-delta.obj"
1>D:\Git\src\libgit.lib
1>D:\Git\src\xdiff\xdiff_lib.lib
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflate referenced in function git_deflate
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateEnd referenced in function git_deflate_abort
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflate referenced in function git_inflate
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function git_inflate_end
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateBound referenced in function git_deflate_bound
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateInit_ referenced in function git_deflate_init
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflateInit_ referenced in function git_inflate_init
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateInit2_ referenced in function do_git_deflate_init
1>libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function git_inflate_init_gzip_only
1>libgit.lib(pack-check.obj) : error LNK2019: unresolved external symbol crc32 referenced in function check_pack_crc
1>libgit.lib(csum-file.obj) : error LNK2001: unresolved external symbol crc32
1>..\test-delta.exe : fatal error LNK1120: 10 unresolved externals
1>Done building project "test-delta.vcxproj" -- FAILED.

**Comment by dscho** [comment]
Oh my. I guess I will have to spend some time on this issue, then. Unless anybody beats me to it, I hope to get back to this by November (that's how far my current backlog looks to me).
