### ISSUE TITLE
service is searching for id_rsa in different location 2.11.0 v. 2.13.3

### ISSUE THREAD

**Issue by robe070** [git-for-windows/git#1245]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

Works: 
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64

Fails: 
git version 2.13.3.windows.1
built from commit: faaf2320f32f6ac52a69502c6b157b6ea4781f50
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Both machines: Microsoft Windows [Version 10.0.14393]
both 64-bit Windows 10
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Works:
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled

Fails:
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
I ran Process Monitor on both machines. See results in attached files.
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch

The two machines are identical - they are VMs. Apart from the version of Git for Windows.

A service runs a powershell script from an IIS web site. The Identity of the Application Pool user
is the logged on user and is the same on both machines.

I ran Process Monitor filtering by the path containing id_rsa. These are the results:
[work.txt](https://github.com/git-for-windows/git/files/1164461/work.txt)
[fail.txt](https://github.com/git-for-windows/git/files/1164464/fail.txt)
Notice that the failing machine does not attempt to access c:\users\user1\.ssh\id_rsa, which the
successful one does access.

```
 - What did you expect to occur after running these commands?

```
It works
```
 - What actually happened instead?
```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by robe070** [comment]
I have placed id_rsa and id_rsa.pub in C:\Windows\System32\config\systemprofile\.ssh. They are successfully opened by ssh.exe as indicated by this Process Monitor log file:
[systemprofile.txt](https://github.com/git-for-windows/git/files/1164608/systemprofile.txt)
But it still gets the permission error. Is it related to failing to open C:\Windows\System32\config\systemprofile\.ssh\id_rsa-cert.*?

Note that this all works perfectly well from git bash, cmd, powershell and Git Extensions.

So I don't have a workaround, except installing the older version of Git for Windows.

**Comment by robe070** [comment]
The command shell environments are using the ssh key in c:\users\user1\.ssh

**Comment by mfriedrich74** [comment]
You may want to check IIS user/service account settings. There should be
something in there which defines whether the users profile will be loaded
or not.
I would think that your both IIS instances have different settings. Have
you tried the different git version on the machine which works?

I am saying this, because:
What you see is typical for Windows services running under a particular
user. By default windows uses the system profile for it.

**Comment by robe070** [comment]
The Process Monitor confirmed that both are using the same user profile.

And I double-checked IIS and both App Pools are configured with the same Identity and to use the User Profile.

**Comment by mfriedrich74** [comment]
Please open process explorer and check the value of these process environment variables:
HOME
HOMEDRIVE
HOMEPATH
USERPROFILE
USERNAME
USERDOMAIN

**Comment by robe070** [comment]
There are no HOME variables set in the failing machine. But the working one does! Thank you for your help. The global HOME environment variable is set to the user's home directory that is administering the machine.

WORKING:
HOME=c:\users\user1
USERDOMAIN=WORKGROUP
USERNAME=LANSA1$
USERPROFILE=c:\windows\system32\config\systemprofile

FAILING:
USERDOMAIN=WORKGROUP
USERNAME=LANSA5$
USERPROFILE=c:\windows\system32\config\systemprofile
