### ISSUE TITLE
Authentication Issue when cloning a gerrit repo using git 2.13.2 via https

### ISSUE THREAD

**Issue by malnasse** [git-for-windows/git#1246]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - 64-bit: 2.13.0  2.13.2 and 2.13.3

```
$ git --version --build-options

git version 2.13.3.windows.1
built from commit: faaf2320f32f6ac52a69502c6b157b6ea4781f50
sizeof-long: 4
machine: x86_64
```

 -Windows 7 64-bit, Windows 10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Mostly defaults, except for choosing cmd as the default environment.

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None.
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git clone https://<user_name_xxx>@gerrit.khronos.org/a/vk-gl-cts
```

 - What did you expect to occur after running these commands?

clone to succeed.
```

 - What actually happened instead?

The error reported is this:
Cloning into 'vk-gl-cts'...
remote: Unauthorized
fatal: Authentication failed for 'https://<user_name_xxx>@gerrit.khronos.org/a/vk-gl-cts/'
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://gerrit.khronos.org/#/admin/projects/vk-gl-cts
```

Additional Notes:
An older version of git still works (2.10.1 64-bit).
I switched multiple times between various versions. 2.10.1 works reliably. 2.13.x fails consistently.
```

**Comment by dscho** [comment]
A couple of ideas how you can proceed to figure this out further:

- maybe setting `http.emptyAuth` to `true` will work around it
- setting the environment variable `GIT_TRACE_CURL` will output more information that might give you a clue what goes wrong.

**Comment by dscho** [comment]
@malnasse are you interested in taking this further at all?

**Comment by malnasse** [comment]
I'm sorry I never followed up on this. I will try your suggestion tomorrow and let you know.
A couple of questions, what should I set the GIT_TRACE_CURL env variable to?
Also, where do I add the emptyAuth setting?
Thank you!

**Comment by dscho** [comment]
> what should I set the GIT_TRACE_CURL env variable to?

I typically set it to `1`, so that it reports back to the terminal. I *think* you can also set it to a filename, which is sometimes useful (e.g. when there is too much output, or when a script calling `git` would be confused by the output).

> where do I add the emptyAuth setting

You can configure it either as repository setting:

```sh
git config http.emptyAuth true
```

or transitively by specifying it as part of your Git call:

```sh
git -c http.emptyAuth=true clone [...]
```

**Comment by PhilipOakley** [comment]
@malnasse @dscho on #1321 I spotted the (https://projects.cs.uaf.edu/redmine/projects/public/wiki/How_do_I_make_Git_give_more_verbose_output for a random internet explanation;-) which says that the value is the file descriptor that the output is sent to, so direct fd 4 to some file and there you have it (fd 1 being the terminal)

**Comment by malnasse** [comment]
Thanks for the tip @PhilipOakley :)

@dscho 
I retested with the most recent Git version and the issue seems to already be resolved. This issue can be closed. Thank you very much for following up on it.

**Comment by dscho** [comment]
Thanks for letting us know, @malnasse! I am glad the issue is resolved.
