### ISSUE TITLE
post-install.vbs instead of post-install.bat?

### ISSUE THREAD

**Issue by ryanspletzer** [git-for-windows/git#1247]
This issue is more around the Git for Windows installer. At a certain point in the install it invokes post-install.bat. This is fine in many scenarios, except in large organizations / enteprises that employ application whitelisting. Ideally we'd like to trust the Git for Windows installer by its publisher signing certificate, but because .bat files can't be signed this causes an issue, wherein we then have to manually take the binary installer / its installed content on disk and whitelist by file hash.

If post-install.bat were instead post-install.vbs which is a vbscript that could be signed, we could avoid the issue and trust the publisher certificate for that script file.

I'm curious if there are others out there in the community that work with whitelisting Git for Windows in a large enterprise.

 - [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.3.windows.1
built from commit: faaf2320f32f6ac52a69502c6b157b6ea4781f50
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Any

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Git-2.13.3-64-bit.exe
```
 - What did you expect to occur after running these commands?

Installed

 - What actually happened instead?

Our Bit9 whitelisting agent blocked post-install.bat because it was not trusted -- it may be avoidable if this were instead a post-install.vbs file that were signed with the publishers certificate.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None

**Comment by dscho** [comment]
The installer is only one user of that `.bat` script, other users may not have such an easy time to execute Visual Basic scripts. Also: how certain are you that Visual Basic scripts can be executed in every instance where `.bat` scripts can be executed without problems? Finally, I tried very hard to *reduce* the number of languages used by the Git for Windows project, in an attempt to lower the bar for contributors. Knowledge of Visual Basic is not currently required to contribute to this project.

As to the trust: this is a red herring. If you care to inspect `post-install.bat`, you will see that it calls `bash.exe` with the express purpose of running the `.post` scripts. Those scripts are Unix shell scripts, therefore they fall *squarely* outside the code-signed part. In other words, your proposed `.bat` -> `.vbs` move would not address the issue you want to see addressed.
