### ISSUE TITLE
[Question] How can I capture the directory from "Git Bash Here" in a script? (eg. for .bashrc)

### ISSUE THREAD

**Issue by Nightfirecat** [git-for-windows/git#1252]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.13.3.windows.1
built from commit: faaf2320f32f6ac52a69502c6b157b6ea4781f50
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**N/A**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Bash**

---

Title is self-explanatory. I'm interested in capturing the directory used by the Windows "Git Bash Here" context menu within a Bash script, namely within my `.bashrc`, but have not been able to find whether this is exposed to Bash.

```
# ...
# Change to "Git Bash Here" directory
cd $...
```

**Comment by PhilipOakley** [comment]
Title is self-explanatory. I'm interested in capturing the directory used by the Windows "Git Bash Here" context menu within a Bash script, namely within my .bashrc, but have not been able to find whether this is exposed to Bash.
# ...
# Change to "Git Bash Here" directory
cd $...


Try 

pwd -W

Works for me... Use it all the time for just that purpose as there is no definitive 'root' directory for the GfW on Windows (too many drives...)

--
Philip

**Comment by Nightfirecat** [comment]
So I should be writing something like this?

```
# Change to home directory if "Git Bash Here" was not invoked
if [[ "$(pwd)" != '/' ]]; then
  cd "$HOME"
fi
```

If so, is there no way to differentiate launching in the root directory by default and "Git Bash Here" being invoked in the root directory?

**Comment by PhilipOakley** [comment]
Part of the problem is non-transferable terminology. Primarily the"root" directory is a meaningless term in Windows.

What is the problem that you are trying to solve?

I think you can just do `(cd /; pwd -W)` to get the windows description of the *current* root directory, and then compare that with a particular install's expectation (as long as you know that...).

On my machine I have the SDK, with both the git bash (Msys2) it installs, and the git bash I can 'compile', and then I have the regular GfW. So depending on how I started the terminal window as to where that terminal window (which runs bash and git) thinks its root directory is located. I often find I'm not testing what I think because I'm not in the right path.

**Comment by Nightfirecat** [comment]
Problem: Within .bashrc, if "Git Bash Here" was invoked, I want to avoid changing directories, otherwise I want to change to a home directory (for this example, let's assume `$HOME`).

**Comment by dscho** [comment]
> Within .bashrc, if "Git Bash Here" was invoked, I want to avoid changing directories,

Try it. `$HOME/.bashrc` is sourced, even if the current directory does not change.

**Comment by dscho** [comment]
> (cd /; pwd -W)

A shorter way is `cygpath -aw /`

**Comment by Nightfirecat** [comment]
> Try it. `$HOME/.bashrc` is sourced, even if the current directory does not change.

I'm not sure I understand. Try _what_? `.bashrc` is sourced, and hence knows the directory it is being run from, but how am I to know whether its shell was launched from the "Git Bash Here" invocation, or if Git Bash was opened outside of the context menu?

**Comment by PhilipOakley** [comment]
I presume that what you want is a consistent look/feel:

1.  to these many bash windows that are started for different purposes
2.  from different places, and
3.  on different machines (including both Windows (GfW/Msys2) and Linux (posix)).

i.e. start at `~`.

However, there is that the one 'funny' feature that may be needed for the "Git Bash Here" invocation such that only in that special case do you _not_ `cd ~` (which may, or many not, be the windows %HOME?) but _stay_ in the startup directory ("bash there!").

And to do that, you are looking for common code for the `.bashrc` file that runs on both Linus/GfW (so `cygpath` might not be acceptable for some distros), and detects the special case of being started from the windows context menu (while any Linux invocation that starts in some random directory [can that happen?] should `cd ~`)

Would that be a reasonable summary (sorry for being pedantic, but that's the systems engineer in me)?

At the moment I'm not aware of any 'hidden'/unmentioned environment variable that tells you you are on Windows, or that it came from the context menu. There may be ways of checking for a command or option error to indicate that (not my area of knowledge).

**Comment by dscho** [comment]
The "source" for the "Git Bash Here" functionality is here: https://github.com/git-for-windows/build-extra/blob/96d20afb924542e2cae47d8e0264caa84d3bc9d8/installer/install.iss#L1991-L2003. It does indeed look as if it is pretty indistinguishable from running Git Bash in other ways.

**Comment by Nightfirecat** [comment]
Darn, alright. Well, thanks for checking anyway!
