### ISSUE TITLE
Please add COMODO CA to the store

### ISSUE THREAD

**Issue by robstoddard** [git-for-windows/git#1253]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Since this is a pretty cut & dried bug submission, I'll start with the fact that my current install is rather old, and a more recent install may represent the COMODO key, however, mine does not.   If there is one that does, then perhaps some form of updater needs to exist to allow Git-for-Windows to get a recent list of certificates... unless somehow it starts using the system store, which was covered ad-nauseum in another submission.  I may not have spoken up in that bug, since I didn't realize there was an issue until today, but I am interested in seeing that issue fixed as well...  but I understand it's entrenched in libcurl+openssl, and my bandwidth is pretty well utilized by my current company, so I cannot offer assistance in that matter.

*anyway*

The COMODO CA is not represented in the certificate store, or, if it is, the wrong key is there.   The key can be obtained here:
[
https://support.comodo.com/index.php?/Knowledgebase/Article/View/970/108/intermediate-2-sha-2-comodo-rsa-domain-validation-secure-server-ca](
https://support.comodo.com/index.php?/Knowledgebase/Article/View/970/108/intermediate-2-sha-2-comodo-rsa-domain-validation-secure-server-ca)

Could you please add it to the store?   I would greatly appreciate it.

**Comment by dscho** [comment]
> I'll start with the fact that my current install is rather old, and a more recent install may represent the COMODO key

There is a way to find out. You can even use a portable Git so that you do not have to overwrite your current installation.

> f there is one that does, then perhaps some form of updater needs to exist

Whoa, whoa, sloooooow down. Some for of updater needs to exist? Are you going to implement it? If not, what makes you think that you can tell anybody else to do it?

> unless somehow it starts using the system store, which was covered ad-nauseum in another submission.

Which you dutifully followed and therefore know that the Secure Channel support has made it into several Git for Windows releases. Or maybe that was missed.
