### ISSUE TITLE
Error: the download URL is wrong of the version 2.13.4

### ISSUE THREAD

**Issue by yaray** [git-for-windows/git#1255]
The page (https://git-scm.com/downloads) shows the version is 2.13.4, but click the "Downloads for Windows" button (enter the page: https://git-scm.com/download/win ), it shows the version 2.13.3, and auto start to download this version software (it is NOT version 2.13.4).

PS: This issue is NOT post bug for git software.

**Comment by avih** [comment]
If you read the text after you click the download link, you'll see this:

> Your download is starting...
>
> You are downloading the latest (2.13.3) 32-bit version of Git for Windows. This is the most recent maintained build. It was released 21 days ago, on 2017-07-13.

Which is correct, because apparently 2.13.4 wasn't yet released for windows. Give it a day or two and it'll get released.

**Comment by yaray** [comment]
@avih  OK, it seems that I just wait to release the 2.13.4 for Windows version, maybe I'm too anxious :-)
Thanks for your reply!

**Comment by dscho** [comment]
I am skipping Git for Windows v2.13.4 because v2.14.0 is due either late tomorrow or Saturday (more likely the latter).

**Comment by avih** [comment]
While I'm unfamiliar with upstream git release practices, does that mean that once upstream released version A.B[.C] there will be no more releases of minor versions lower than A.X.D where X < B ? Is this the case upstream too?

**Comment by PhilipOakley** [comment]
It's more of a timing issue than a limit on the number of minor (maintenance) releases. In the current case, the maintenance release and the next full release were hot on the heels of each other, and _Dscho's time is limited_, so a bit of triage meant that only the latest full usptream release is being done. (In another issue, Dscho notes his backlog looks like it could take until November <shriek>)

Anything that you/we can do to help dscho is good, even if it is only curating some of the easy issues from list (you can tell if they are 'easy': If you think you may be able just a little, then that makes it 'easy'....)
