### ISSUE TITLE
ssh can't find id_rsa in ~/.ssh/ folder

### ISSUE THREAD

**Issue by MichaelTheriot** [git-for-windows/git#1259]
For the first time today I need specify the full path to my keys when using ssh.

Before
* `ssh -i id_rsa` is fine
* `ssh -i ~/.ssh/id_rsa` is fine

After
* `ssh -i id_rsa` cannot find file
* `ssh -i ~/.ssh/id_rsa` is fine

I've attempted to install git bash on another desktop and am not experiencing this issue, so I believe it's one with my configuration. To be safe I did a complete reinstall and I am still experiencing the issue despite it working before.

I think I've narrowed the issue down to ssh simply not checking the `~/.ssh/` folder but I don't know how to fix that. I was expecting a full reinstall to resolve any issues.

---

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.0.windows.1
built from commit: 8d74ef6015f82b428680388d508def2af1e03932
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I did a fresh install right now...

![image](https://user-images.githubusercontent.com/3187409/29006509-21e4d3f6-7ab7-11e7-9195-66a9fb74ac73.png)
![image](https://user-images.githubusercontent.com/3187409/29006515-3644222a-7ab7-11e7-9562-dc733b6d64fd.png)
![image](https://user-images.githubusercontent.com/3187409/29006519-3f6a00b8-7ab7-11e7-965f-ee999b528616.png)
![image](https://user-images.githubusercontent.com/3187409/29006522-4fe9e6f6-7ab7-11e7-980d-33cf48d9a4a5.png)
![image](https://user-images.githubusercontent.com/3187409/29006523-58176f4c-7ab7-11e7-8988-87fabf7b040d.png)
![image](https://user-images.githubusercontent.com/3187409/29006524-5f9485ac-7ab7-11e7-8bf5-b7bb66ea907b.png)
![image](https://user-images.githubusercontent.com/3187409/29006526-66d385fc-7ab7-11e7-92f3-e0ee709258d0.png)
![image](https://user-images.githubusercontent.com/3187409/29006528-6e1c9dc6-7ab7-11e7-93b0-a656bd4d9e4b.png)
![image](https://user-images.githubusercontent.com/3187409/29006531-776e68aa-7ab7-11e7-8c62-d8c53adcb34a.png)

```

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I downloaded the Windows 10 creator update and Ubuntu for Windows 10 yesterday.

I removed my `~/.ssh/` folder located at `C:\Users\Michael\.ssh\`.

My env variables:

![image](https://user-images.githubusercontent.com/3187409/29006554-f6c1c03e-7ab7-11e7-93be-fd693b368a1f.png)
![image](https://user-images.githubusercontent.com/3187409/29006563-1278c17e-7ab8-11e7-94d9-1f5523a440fa.png)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

![image](https://user-images.githubusercontent.com/3187409/29006573-263811c4-7ab8-11e7-9054-5582bd3d3659.png)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh-keygen -t rsa -b 4096 -C "test@test.com"
ssh -i id_rsa
```

![image](https://user-images.githubusercontent.com/3187409/29006604-b7f72d52-7ab8-11e7-9522-5e90bdc9d770.png)

And then...

```
ssh -i ~/.ssh/id_rsa
```

![image](https://user-images.githubusercontent.com/3187409/29006612-de858f2c-7ab8-11e7-8690-92ab853ab593.png)

 - What did you expect to occur after running these commands?

I expected the first call to `ssh -i id_rsa` to be identical to `ssh -i ~/.ssh/id_rsa`

 - What actually happened instead?

I received `Warning: Identity file id_rsa not accessible: No such file or directory.` message.

---

Not a critical issue or anything, but I am reporting in case a solution is known / others experience the same. Thanks!

**Comment by redmanmale** [comment]
> Not a critical issue or anything

So-so. With this version there's no way to work with ssh remote repos.

```
$ git fetch

GitLab: Disallowed command
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dscho** [comment]
When you specify a path directly via `-i`, it is either an absolute path (`~/.ssh/id_rsa`) or a relative path (`id_rsa`). If it is relative, it should be relative to the *current* working directory. That is, `ssh -i id_rsa` should only work as long as you're in the `~/.ssh` directory.

I am not sure whether this changed in OpenSSH, maybe you can figure it out? OpenSSH's release notes are here: https://www.openssh.com/releasenotes.html.

**Comment by dscho** [comment]
I just tested with an older `ssh` (7.3p1, shipped with Git for Windows e.g. v2.10.0), and the behavior is as I would have expected it: `ssh -i id_rsa` complains unless there is a file named `id_rsa` in the *current* directory. So I don't think this is a bug...
