### ISSUE TITLE
Git Bash doesn't mask/hide passwords

### ISSUE THREAD

**Issue by daniel-white** [git-for-windows/git#1267]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10, Creators, x64
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope just a problem with Git Bash

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
vagrant up
```
 - What did you expect to occur after running these commands?

In this process vagrant will ask for my Windows password. Typing it will be echoed. In CMD, this isn't a problem.

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'wholebits/ubuntu17.04-64' is up to date...
==> default: A newer version of the box 'wholebits/ubuntu17.04-64' is available! You currently
==> default: have version '2017.07.01'. The latest is version '2017.08.04'. Run
==> default: `vagrant box update` to update.
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: Windows account.
    default:
    default: Username: (redacted)
    default: Password (will be hidden):
Error! Your console doesn't support hiding input. We'll ask for
input again below, but we WILL NOT be able to hide input. If this
is a problem for you, ctrl-C to exit and fix your stdin.
     default: Password (will be hidden):
```
Notice the error: 
> Error! Your console doesn't support hiding input. We'll ask for
> input again below, but we WILL NOT be able to hide input. If this
> is a problem for you, ctrl-C to exit and fix your stdin."

 - What actually happened instead?

I would hope Git Bash would mask or hide my password.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A.

**Comment by dscho** [comment]
Have you tried `winpty` as per [the Known Issues](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues)?

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

**Comment by daniel-white** [comment]
@dscho that works just fine. are there plans of fixing this known issue or provide some sort of bandaid? 
additional documentation might be helpful in the known issues to describe some of the behavior.

**Comment by dscho** [comment]
> are there plans of fixing this known issue

The thing to understand first is that MinTTY does *not* implement a Win32 Console. Instead, it uses MSYS2's pty emulation. Therefore vagrant is absolutely correct in saying that it cannot hide the password: it really cannot, unless it learns about MSYS2's pty emulation. Which would of course be asking a bit much... what other terminal emulators should vagrant support in addition to MinTTY?

That is why you have `winpty`. It *does* offer a Win32 Console to the spawned process. And then polls that to update MinTTY's pty accordingly. Obviously, this is somewhat slow, and even error-prone. That's why it is not the default.

If you want a TL;DR, I first have to tell you: it is a mistake to not read what I wrote above, because it is a rather crucial bit of information. The answer to your question is obviously: no, there is no known way to fix this issue, and therefore it likely won't be fixed.
