### ISSUE TITLE
git push to local UNC-path (\\?\c\...) no longer works

### ISSUE THREAD

**Issue by stpag-cv** [git-for-windows/git#1269]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
$ git --version --build-options
git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows Server 2008 R2 64Bit
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The error occurs on our buildserver where git is executed as part of our build process.
The buildserver uses local unc paths (\\?\) to mitigate some of the MAXPATH=260 chars problem.
For further info, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

The error first occurred after upgrading from an unknown older version to git 2.14.1.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Git is executed as part of our build script executed in FinalBuilder.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Working Directory:     \\?\D:\Projects\KMS53undFPs_NB
Command Line:          git push origin --verbose

 - What did you expect to occur after running these commands?
git pushes the local commit(s) to origin.

 - What actually happened instead?
Error: fatal: ArgumentException encountered.
   illegal character in path.

 - Boundaries
git pull still works without any issues.

 - Further information
The windows event log shows the following error from the source "Git Credential manager":
System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   bei System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   bei System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   bei System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   bei System.IO.Directory.InternalGetCurrentDirectory(Boolean checkHost)
   bei Microsoft.Alm.Cli.OperationArguments.Impl.LoadConfiguration()
   bei Microsoft.Alm.Cli.OperationArguments.Impl.get_GitConfiguration()
   bei Microsoft.Alm.Cli.CommonFunctions.TryReadBoolean(Program program, OperationArguments operationArguments, String configKey, String environKey, Nullable`1& value)
   bei Microsoft.Alm.Cli.Program.TryReadBoolean(OperationArguments operationArguments, String configKey, String environKey, Nullable`1& value)
   bei Microsoft.Alm.Cli.CommonFunctions.LoadOperationArguments(Program program, OperationArguments operationArguments)
   bei Microsoft.Alm.Cli.Program.Get()
   bei Microsoft.Alm.Cli.Program.Run(String[] args)

**Comment by dscho** [comment]
@whoisj I think this may be in Git Credential Manager... ("Illegales Zeichen im Pfad." means "illegal character in path" and "bei" means "at"...) Do you concur?

**Comment by stpag-cv** [comment]
I would agree. But the bug only occurs when trying to push commits to the git server.
Git pull still works.

**Comment by whoisj** [comment]
Yup, it seems the path to the configuration file is confounding the GCM.

@stpag-cv can you provide the paths to you various config files? Easiest way I know to collect them is to run `git config --list --show-origin` and manually copy-pasta the paths into a response to this thread.

Thanks!

**Comment by whoisj** [comment]
Ah-ha! I've been able to reproduce the issue. It seems NetFx cannot handle long-path format paths. The "//?/<drive>:<path>" format breaks NetFx.

The solution for @stpag-cv  is to use a more traditional (though vastly inferior) "<drive>:<path>" format, or wait for a patch to the GCM which enable long-path support.

**Comment by stpag-cv** [comment]
Following is the output:
$ git config --list --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=false
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:C:/Users/kms.builder/.gitconfig    user.name=<HIDDEN for privacy>
file:C:/Users/kms.builder/.gitconfig    user.email=<HIDDEN for privacy@domain.com>
file:C:/Users/kms.builder/.gitconfig    pull.rebase=true
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        core.hidedotfiles=dotGitOnly
file:.git/config        remote.origin.url=http://<INTERNALSERVER>/git/<REPOSITORY>.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        branch.KMS_Version_5_1_und_FPs.remote=origin
file:.git/config        branch.KMS_Version_5_1_und_FPs.merge=refs/heads/KMS_Version_5_1_und_FPs
file:.git/config        gui.wmstate=normal
file:.git/config        gui.geometry=787x377+198+198 152 169

**Comment by whoisj** [comment]
@stpag-cv thanks for that, the root cause here is the GCM depends on .NET Framework, and it appears that the .NET Framework does not support long-path format path names.

As I mentioned, the quick fix here is for you to use traditional path names (i.e. not starting with //?/ and less than 260 characters).

**Comment by stpag-cv** [comment]
We already use your workaround for our nightly build for the last two days.
I just was not sure if you still need the additional information.

Thanks

**Comment by dscho** [comment]
Okay, let's track this issue there: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/479

**Comment by stpag-cv** [comment]
Please keep in mind that this bug is a regression.
UNC paths worked before in an unknown version (probably around git 1.9.X).
Are there any (de-)installation logs left over from the former version after upgrading?

**Comment by dscho** [comment]
Sure, it is a regression from that ancient version *because Git Credential Manager was not installed*.

I am not aware of any uninstall log, certainly not from a Git for Windows version older than 2 years (!!!).

**Comment by stpag-cv** [comment]
Thanks for the clarification.

**Comment by dscho** [comment]
BTW @whoisj 's workaround should also help (using non-`\\?\`-prefixed paths when possible).
