### ISSUE TITLE
Fix msys-2.0.dll to be able to run git-bash.exe on Windows XP again

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#127]
Only on Windows XP (tested on 32-bit) is there a regression between Git for Windows 2.3.5.8 and 2.3.6.2.

The symptom is that `git-bash.exe` hangs. There are two `mintty.exe` processes hanging with the Bash, and killing one of them lets the terminal window appear, with a note that it had problems with forking and maybe calling `/usr/bin/rebaseall` would fix it.

If I recompile `git-bash.exe` as a console program (with `-mconsole` as opposed to `-mwindows), it works again.

Simply copying over an `msys-2.0.dll` from a portable Git for Windows 2.3.5.8 makes it work again, either.

So it is a regression introduced by the update from the msys2-runtime bundled in 2.3.5.8 to the one bundled in 2.3.6.2.

A quick test shows that the regression persists also when picking the current msys2-runtime package version of MSys2 (instead of Git for Windows' forked one).

**Comment by dscho** [comment]
Unfortunately, this was caused by the fix for #106. Since a non-starting Git Bash is a non-starter, it is more important to fix that bug for now, and hope that the Cygwin mailing list [can help us with this bug](https://cygwin.com/ml/cygwin/2015-05/msg00009.html).

**Comment by dscho** [comment]
Good news. I figured out that all I need to do is to allocate a Win32 Console when running the *Git Bash* (and probably also when running `gitk` or `git-gui`) because `msys-2.0.dll` apparently requires a console now (and XP seems to pass an invalid console when launching from a GUI process).

Will clean up my patches and test thoroughly during the rest of the day.

**Comment by nalla** [comment]
Great work @dscho!

**Comment by dscho** [comment]
Fixed in https://github.com/git-for-windows/git/commit/dbd0783837d2ea7ff2e8bcc543b81c4faf398d55 and https://github.com/git-for-windows/MINGW-packages/commit/2c3ee8622114f9d9438c93d5e205f6b428255c53
