### ISSUE TITLE
git rm directory/file removes both directory and file

### ISSUE THREAD

**Issue by plorch** [git-for-windows/git#1272]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I can think of.
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rm data/MOCK_DATA.csv
```
 - What did you expect to occur after running these commands?

removal of file MOCK_DATA.csv but not directory data

 - What actually happened instead?

removal of file MOCK_DATA.csv and directory data

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

a local clone of https://github.com/plorch/goodEnough

**Comment by landstander668** [comment]
I don't know if it's expected behaviour, but it's definitely not specific to Git for Windows. Here's a quick test from an Ubuntu 17.04 machine.

```
[2017-08-21 10:57:34] adric@myhost test
$ git version
git version 2.14.1

[2017-08-21 10:57:40] adric@myhost test
$ uname -a
Linux myhost 4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[2017-08-21 10:57:43] adric@myhost test
$ git clone https://github.com/plorch/goodEnough && cd goodEnough
Cloning into 'goodEnough'...
remote: Counting objects: 47, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 47 (delta 12), reused 47 (delta 12), pack-reused 0
Unpacking objects: 100% (47/47), done.

[2017-08-21 10:57:48] adric@myhost goodEnough (master)
$ ls -l
total 44
-rw-r----- 1 adric adric     0 Aug 21 10:57 CITATION
-rw-r----- 1 adric adric 35146 Aug 21 10:57 LICENSE
-rw-r----- 1 adric adric   159 Aug 21 10:57 README.md
drwxr-x--- 2 adric adric  4096 Aug 21 10:57 src

[2017-08-21 10:57:50] adric@myhost goodEnough (master)
$ ls -l src
total 4
-rw-r----- 1 adric adric 784 Aug 21 10:57 templatewithcopyright.py

[2017-08-21 10:57:53] adric@myhost goodEnough (master)
$ git rm src/templatewithcopyright.py 
rm 'src/templatewithcopyright.py'

[2017-08-21 10:57:57] adric@myhost goodEnough (master +)
$ ls -l
total 40
-rw-r----- 1 adric adric     0 Aug 21 10:57 CITATION
-rw-r----- 1 adric adric 35146 Aug 21 10:57 LICENSE
-rw-r----- 1 adric adric   159 Aug 21 10:57 README.md
```

**Comment by landstander668** [comment]
After a bit of googling I'm pretty sure this is expected behaviour, simply because Git only tracks files... directories are treated more-or-less like a component of the filename. This is fairly easy to see when attempting to add an empty directory to the repository, as `git add empty_directory_name` effectively behaves as a no-op in that case, with nothing being added to the index. The `git status` output doesn't include empty directories either.

Since this is (probably) by design, I'd be a bit surprised if the current behaviour changes since this would affect comparability with earlier versions. It might be possible to add an optional parameter to `git rm` which prevents the empty directory from being removed, however. Naturally this would need to either be pushed to upstream, or originate there and flow into Git for Windows.

@dscho I don't mind taking a crack at adding the parameter, unless you have reason to believe it wouldn't be accepted upstream.

**Comment by dscho** [comment]
@landstander668 go right ahead! I guess upstream can be convinced to accept this option, as long as the default behavior is unchanged.

**Comment by landstander668** [comment]
OK, will do. I can't promise a timeframe (the next 2 weeks are looking particularly busy), but I should be able to get to it before too long.
