### ISSUE TITLE
git not working after setting http.sslBackend config

### ISSUE THREAD

**Issue by saqib-ali** [git-for-windows/git#1274]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64-bit 

```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Window 7
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git not working after setting http.sslBackend config

** insert your commands here **

```
c:\> git config --global http.sslBackend schannel
c:\> git clone https://nnn.nnn.nnn/xyz
```

```
 - What did you expect to occur after running these commands?

Able to clone the project using schannel as the sslBackend on Windows

 - What actually happened instead?

got the following error:
`fatal: Could not set SSL backend to 'schannel': already set`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> ** insert your commands here **

Please replace those placeholders completely while filling out a bug report.


> fatal: Could not set SSL backend to 'schannel': already set

This was fixed already, and you should be able to verify by installing a snapshot: https://wingit.blob.core.windows.net/files/index.html

**Comment by dscho** [comment]
For the record, I would have really appreciated testing. Or for that matter, *any* feedback.
