### ISSUE TITLE
FR: upgrade mintty to >= 2.7.8

### ISSUE THREAD

**Issue by max630** [git-for-windows/git#1275]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
Git-2.14.1-64-bit.tar.bz2
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Not relevant
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Not relevant
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

mintty

As I can see in Git-2.14.1-64-bit.tar.bz2:etc/package-versions.txt. mintty is of version mintty 1~2.7.7-1
mpfr.

There is a defect in mintty which was fixed in 2.7.8: https://github.com/mintty/mintty/commit/41489236ded1 , and which affects git-for-windows installation. It would be nice to have it upgraded. If there anything which prevents it?

**Comment by dscho** [comment]
As Git for Windows simply consumes most of [MSYS2](https://msys2.github.io)'s packages, including `mintty`, this is more of a feature request for https://github.com/Alexpux/MSYS2-packages. If you are serious about this issue, you should consider working on a Pull Request, this page should get you started: https://github.com/git-for-windows/git/wiki/Package-management

**Comment by max630** [comment]
Thanks.

Is [this](https://github.com/Alexpux/MSYS2-packages/pull/979) correct?

**Comment by dscho** [comment]
> Is this correct?

AFAICT yes. You did test this by running `makepkg`, in an MSYS2 shell, yes?

**Comment by dscho** [comment]
> You did test this by running makepkg, in an MSYS2 shell, yes?

@max630 well, did you?

**Comment by max630** [comment]
Hi.

No, to be honest, I did not, I just applied the patches manually and built with make. I'm not sure if I can run proper package making soon, I happen to have little free time lately.

However I can see there is some CI which performed the build, and produced the x64 build. I I'll try to check those if they work.

**Comment by max630** [comment]
I have tried it with laters Git for Windows/x64 installation, seems to work.

**Comment by kgybels** [comment]
@max630 Git for Windows 2.14.2 comes with mintty 2.7.9. Can you close this issue?

**Comment by max630** [comment]
Thanks for noticing. Closing.
