### ISSUE TITLE
git-gui commit sometimes hangs when calling pre-commit hook

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#1276]
- [ X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64
```
$ git --version --build-options

** git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 6.1.7601] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** My machine is occasionally on a work domain but this doesn't seem to make a difference in seeing this issue. **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git gui (and then commit)
```
 - What did you expect to occur after running these commands?

** git should have quickly committed the change **

 - What actually happened instead?

** git-gui froze for many seconds while displaying in the bottom status bar that it was calling the 'pre-commit hook'.  I do not have any custom pre-commit hooks.  This doesn't happen all the time but does happen on a lot of commits.  Commit size does not seem to matter **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Is it possible that your domain controller was somehow unreachable at that point?

**Comment by kjeremy** [comment]
Yes, typically I am disconnected or on a separate network.

**Comment by dscho** [comment]
That's probably the problem (the separate network, timing out while looking for the domain controller). I imagine that git gui does not even try to figure out whether there is a pre-commit hook, calling bash to figure that one out (I might be wrong on that, feel free to study the code in `mingw64\lib\git-gui` or similar, it is plain Tcl). Whenever Bash starts, it tries to determine user info by querying the domain controller...

**Comment by dscho** [comment]
I fear that there is little that we can do about it at this point, so I am closing this for now.

If anybody shows up to take on this issue, it'll be easy enough to re-open the issue.
