### ISSUE TITLE
Do not store credentials from url with the credential-manager

### ISSUE THREAD

**Issue by oledid** [git-for-windows/git#1280]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.0.windows.2
built from commit: 0f3342804fc6fa558a7c9e220e7e9ab4c86e8226
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

When calling `git ls-remote https://{USERNAME}:{TOKEN}@github.com/{REPOSITORY} refs/tags/* refs/heads/*` (with credentials as part of the actual URL), git will skip calling `git credential-manager get` but still call `git credential-manager store`, which overrides the stored credentials with the url-credentials.

```
10:33:27.538978 git.c:328               trace: built-in: git 'ls-remote' 'https://{USERNAME}:{TOKEN}@github.com/systemjs/plugin-json.git' 'refs/tags/*' 'refs/heads/*'
10:33:27.539977 run-command.c:626       trace: run_command: 'remote-https' 'https://{USERNAME}:{TOKEN}@github.com/systemjs/plugin-json.git' 'https://{USERNAME}:{TOKEN}@github.com/systemjs/plugin-json.git'
10:33:27.605977 git.c:560               trace: exec: 'git-remote-https' 'https://{USERNAME}:{TOKEN}@github.com/systemjs/plugin-json.git' 'https://{USERNAME}:{TOKEN}@github.com/systemjs/plugin-json.git'
10:33:27.606976 run-command.c:626       trace: run_command: 'git-remote-https' 'https://{USERNAME}:{TOKEN}@github.com/systemjs/plugin-json.git' 'https://{USERNAME}:{TOKEN}@github.com/systemjs/plugin-json.git'
10:33:28.177684 run-command.c:626       trace: run_command: 'git credential-manager store'
10:33:28.314690 git.c:560               trace: exec: 'git-credential-manager' 'store'
10:33:28.314690 run-command.c:626       trace: run_command: 'git-credential-manager' 'store'
10:33:28.362683 ...\Common.cs:524       trace: [Main] git-credential-manager (v1.12.0) 'store'
10:33:28.433683 ...\Where.cs:239        trace: [FindGitInstallations] found 1 Git installation(s).
10:33:28.438689 ...Configuration.cs:405 trace: [LoadGitConfiguration] git All config read, 31 entries.
10:33:28.439689 ...\Where.cs:239        trace: [FindGitInstallations] found 1 Git installation(s).
10:33:28.440688 ...Configuration.cs:405 trace: [LoadGitConfiguration] git All config read, 31 entries.
10:33:28.443688 ...\Common.cs:418       trace: [LoadOperationArguments] writelog = 'True'.
10:33:28.444688 ...\Common.cs:243       trace: [EnableTraceLogging] trace logging enabled.
10:33:28.444688 ...\Common.cs:248       trace: [EnableTraceLogging] git local config found at 'C:\Git\temp\test-jspm\.git\config'.
10:33:28.446696 ...\Common.cs:296       trace: [EnableTraceLoggingFile] trace log destination is 'C:\Git\temp\test-jspm\.git'.
10:33:28.463682 ...\Common.cs:74        trace: [CreateAuthentication] detecting authority type for 'https://github.com/'.
10:33:28.474695 ...uthentication.cs:134 trace: [GetAuthentication] created GitHub authentication for 'https://github.com/'.
10:33:28.474695 ...\Common.cs:139       trace: [CreateAuthentication] authority for 'https://github.com/' is GitHub.
10:33:28.474695 ...\Program.cs:351      trace: [Store] storing GitHub credentials for 'https://github.com/'.
10:33:28.495708 ...seSecureStore.cs:210 trace: [WriteCredential] credentials for 'git:https://github.com' written to store.
```

I would suggest that git should skip storing credentials when it already skips fetching them.

*Why?*
I've had trouble with "git loosing my credentials". After debugging, I found that this is due to jspm package manager asking for a git api key to resolve it's github api limit-problems. When jspm has configured a token, it puts it in the url requests. This results in this workflow:

```
> cd c:\git\oledid\private-repo
> git pull
# windows credential manager asks for credentials
# credentials entered and succeeds
Already up to date.
> git pull
Already up to date.
> jspm install
# jspm makes a lot of calls to git ls-remote https://{USERNAME}:{TOKEN}@github.com/{REPOSITORY} refs/tags/* refs/heads/*
# the provided token has only access to public repositories, because that is all it needs for its tasks
# git stores the username and token from the url with the credential-manager for the entirety of github.com, overriding the previous credentials from the Git Credential Manager for Windows-login
> git pull
remote: Repository not found.
fatal: repository 'https://github.com/oledid/private-repo.git/' not found
```

Relevant tasks: 
* https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/429
* https://github.com/jspm/jspm-cli/issues/2355

**Comment by whoisj** [comment]
Perhaps this

> When jspm has configured a token, it puts it in the url requests. 

Is a core part of the problem.

Since chances to the core behavior of Git are not a "Git for Windows" issue, but a core Git (aka "The Mailing List") issues - we should consider reasonable work around that do not require the core Git maintainers to consider first. IMO that'll be the quickest route to success for @oledid .

Here's a suggestion:

Ask Jspm to set an environment variable (perhaps `CREDENTIAL_STORE`) if the value is set to `FALSE`, `NO`, or `0` then the GCM will read the value and no store any credentials. If the variable is not set or set to anything else, then the GCM will perform the task asked of it (store the credentials).

That seems simpler, thoughts?

**Comment by dscho** [comment]
No idea how `jspm` calls the `git` executable; If there is some sort of control over it, you could always pass `-c credential.helper=` before the `fetch` command in order to disable *any* credential helper.

**Comment by oledid** [comment]
@dscho jspm executes commands like `git ls-remote https://{USERNAME}:{TOKEN}@github.com/{REPOSITORY} refs/tags/* refs/heads/*` for the most part.

Would `git ls-remote https://{USERNAME}:{TOKEN}@github.com/{REPOSITORY} refs/tags/* refs/heads/* -c credential.helper=` be correct?

**Comment by whoisj** [comment]
@oledid the command would look like `git -c credential.helper= ls-remote https://{USERNAME}:{TOKEN}@github.com/{REPOSITORY} refs/tags/* refs/heads/*` the `-c` option needs to passed to `git` and precede the verb.

**Comment by oledid** [comment]
Alright, thanks. That sounds like an ok workaround for jspm. I will suggest it.

I will close this issue since I've learned that the issue has nothing to do with git for windows.

I'm still going to send a suggestion to the mailing list, because I believe that the credential manager should be skipped if the credentials are already "hard-coded" into the url. But it will be nothing more than a suggestion.
