### ISSUE TITLE
GfW SDK: getopt and util-linux are in conflict

### ISSUE THREAD

**Issue by larsxschneider** [git-for-windows/git#1281]
I just installed the latest version of the GfW SDK (1.0.6) on Windows [Version 6.3.9600] and I ran into the following issue:

```
...
resolving dependencies...
looking for conflicting packages...
:: getopt and util-linux are in conflict. Remove util-linux? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: getopt and util-linux are in conflict
Could not install the remaining packages
Press any key to continue . . .
```

Is this a known issue? Is this the right place to report the issue? Other package mechanisms ran into the [same issue](https://github.com/Linuxbrew/homebrew-core/issues/144).

Thanks,
Lars

**Comment by dscho** [comment]
My Git for Windows SDKs do not have `getopt` installed. What is using it on your end?

**Comment by larsxschneider** [comment]
Not sure. I am just running the default installer exe. I had GfW SDK installed on that machine before but I think I deleted all previous traces. I can try it again on a completely clean VM tomorrow.

**Comment by dscho** [comment]
`pactree -r getopt` should help determine what uses that package.

**Comment by dscho** [comment]
Oh, I forgot to close this: if it really is a bug, it is a bug in the MSYS2-packages provided by MSYS2.
