### ISSUE TITLE
Remember the window state (minimized, maximized, position, width and height)

### ISSUE THREAD

**Issue by asesh** [git-for-windows/git#1282]
Every time I open git-bash from my taskbar or shortcut, we have to either maximize it or scale it's window as it's default size is too small. You guys should add support for remembering the window state (minimized, maximized, position, width and height) and act accordingly when another instance of git bash is open again. 

Thanks

**Comment by dscho** [comment]
"you guys should..." immediately gets returned to you. You have been given some pretty useful piece of software for free, and the deal is that you contribute back improvements as way of "paying".

**Comment by bbolli** [comment]
You can set the default window size (among others) in MinTTY's options dialog. You can reach it by right-clicking the window's title bar.
