### ISSUE TITLE
Be a good Windows citizen (don't pollute %USERPROFILE%).

### ISSUE THREAD

**Issue by MicahZoltu** [git-for-windows/git#1285]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit

```
$ git --version --build-options

git version 2.13.2.windows.1
built from commit: 914b84c9d949b14a135ab50c8b881cdee9be116c
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? 10 64-bit Insider (Fall Creators Update)

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16251.1002]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Any.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch --all
```
 - What did you expect to occur after running these commands?

`%USERPROFILE%` not polluted.

 - What actually happened instead?

`%USERPROFILE%` a `.ssh` directory created in `%USERPROFILE%`.

----

On Windows, the only files/folders that should be put into `%USERPROFILE%` are those explicitly put there by a user via a save dialog box.  While it is common for apps ported from Linux to treat `%USERPROFILE% the same as `$HOME` on Linux, this is _not_ the right thing to do on Windows.  Windows has directories for per-user app configuration (`%APPDATA%`), per-user app caches `%LOCALAPPDATA%` and shared data (`%PROGRAMDATA%`).  Git should be using `%APPDATA%\<vendor>\<product>` (`%APPDATA%\git\ssh`) for these files rather than its current location.  Similarly, the global git config file should be in `%APPDATA%\git\config` rather than its current location in `%USERPROFILE%`.

I recognize that migration is a long and hard road, so in the meantime there should be an environment variable that can be set to redirect where Git stores its files.  At the moment, from what I can tell there is no way to redirect Git's configuration and SSH directories away from `%USERPROFILE%`.  It is currently possible to redirect `.gitconfig` via `GIT_CONFIG` environment variable, but I have been unable to figure out any way to redirect `.ssh` folder.

**Comment by dscho** [comment]
> I recognize that migration is a long and hard road,

Not to mention, impossible without breaking everybody's setup and also their neighbors'.

**Comment by MicahZoltu** [comment]
It would likely need to either be part of a semver major update, or there would need to be a migration period during which git will read from the old location and write to the new location, then after it is believed most users have used such an intermediate version then remove the "read from old" bit in a future release.

**Comment by dscho** [comment]
@MicahZoltu if you are asking me to break millions of existing installations, we can stop right there.

**Comment by MicahZoltu** [comment]
I'm not sure how you got that out of my comment?  Are you referring to semver major update?  If so, I assume that _eventually_ git will do another semver major update (git v3).  I also assume (if you are following semver) that it will include some number of breaking changes.  The idea with the first option would be to include this change in the semver 3 update.

Another option would be to make it so the git installer knows how to migrate between old config location and new config location.  This of course depends on the majority of users using an installer rather than just dropping some executables into their path (I'm not sure what install distribution looks like for Git).

**Comment by dscho** [comment]
@MicahZoltu would you agree that your proposed change would pretty much make *every* user's setup fail?

Like, `$HOME/.gitconfig` would be ignored.

An even bigger change that your proposition would require is that `curl`'s configuration would need to move from `$HOME/_netrc`. Again, it would break existing setups.

And that would affect more than just Git for Windows. Everything that uses cURL internally.

Yet another, even bigger change would be that OpenSSH would need to move its `$HOME/.ssh/` out of the top-level of the home directory. And that would break existing setups, too.

Again. This change would also interfere with other application on the same machine using OpenSSH.

Even if there would be no other cURL or OpenSSH user: Your idea to patch the Git installer assumes that users have only one Git for Windows installation. Which is not true: if you have GitHub Desktop installed, you have a portable Git. If you have Visual Studio installed, you have a MinGit installed. You may have yet another application installed which also has a version of Git for Windows included.

If you update *one* of them, and if that version migrates those configuration files out of the home directory into what you deem a more appropriate place, the other Git for Windows installations will fail to find them.

So while I kind of agree with you that from a Windows point of view, the decision to put things directly into the home directory is too Unix-y for Windows, it is a fait accompli.

You can talk about SemVer all you want, it does not matter. What matters is whether end users would be required to change their setups, *after* realizing that one upgrade *broke* their perfectly fine Git for Windows installation. Just out of a whim that some architectural decision in the past may need to be reconsidered.

It simply would cause users too much pain and suffering, merely to accommodate some sense of elegant design. That's not enough reason for me to break users' existing installations.

Not even under the thin veil of a major version bump.

**Comment by MicahZoltu** [comment]
Many products have moved the location of files in the past even with existing install bases.  It is not a simple problem to solve, but it isn't impossible either.  Also, I think even if Git for Windows can't come up with a reasonable migration strategy, having environment variables to override the defaults is a big step forward.  Though, it sounds like perhaps GIT _does_ provide overrides via environment variables and the problem is that it depends on OpenSSH which does not provide an environment variable override for the `.ssh` directory?

If you are unwilling to do a breaking change in a major version bump then that suggests to me you aren't following SemVer, since that is the entire point of major changes (backward incompatible changes/deprecations)?

Ultimately, this is your project of course so your call.  I will say that this and other unix-isms on Windows is one of the reasons I tend to advise projects to move to libgit2 rather than Git, because git for Windows isn't a particularly good Windows citizen.

**Comment by dscho** [comment]
> If you are unwilling to do a breaking change in a major version bump then that suggests to me you aren't following SemVer, since that is the entire point of major changes (backward incompatible changes/deprecations)?

Stop right there. You are arguing for arguing's sake, and I refuse to spend time on such a discussion.

The point is: you want to force a change on Git for Windows users that most users simply won't care to have to spend time and effort on. That's just a bad thing to do, and your waving SemVer around simply misses the point that most users *don't care* that the files are in their home directory.

You care, sure. But that does not allow you to inflict a backwards-incompatible change onto users.

And I do *not* appreciate your waving that "not a good Windows citizen" flag around when Windows is focused on users. If you want to make life difficult for users, then that is incompatible with the philosophy of Windows.

If you are serious about "uncluttering the home directory", you should feel very, very free to work on patches and contribute them. We can discuss their merits then and there.

**Comment by MicahZoltu** [comment]
From this discussion, I get the impression that a patch for this would _not_ be welcome.  Is that not the case?  I always start with an issue rather than PR because I don't want to spend time/effort on work that won't be accepted/merged.  If submitting a PR is a better course of action and likely to get approved then I can investigate going that route, but that definitely isn't the feeling I am getting from this conversation.

**Comment by dscho** [comment]
@MicahZoltu breaking users' setups is a simple no-no.

If you want to unclutter your home directory, and if you are nice to others about it, then that contribution would certainly be integrated.

You just can't go around and annoy users by breaking their setups, in the name of "being a good Windows citizen". That would make you a *bad* one, not a good one. Don't be that person.

But again, if you have an improvement that does not affect other users negatively, it is a welcome contribution.

**Comment by MicahZoltu** [comment]
The long term goal would be to change the default.  It sounds like you are uninterested in any solution that involves changing the default though.

The strategies I have seen used in the past are SemVer breaking change and a long-term migration strategy.  In the long term migration strategy the app reads from two sources for a while and writes to old with an option (environment variable) to write to the new.  Then sometime later the default write location changes.  Then sometime after that it stops reading from the old location.  Unless I am mis-interpreting you, neither of these solutions are palatable to you and I can't think of any other options forward.

It _does_ sound like you indicated that Git creating a folder `%USERPROFILE%\.ssh` is actually OpenSSH, not Git?  If so I can try to see if they are interested in resolving that issue or not.  At least with that Windows users can use Putty instead.

**Comment by MicahZoltu** [comment]
I'm not trying to complain, I'm trying to understand.

This is how I have interpreted this conversation (attempting to remove some emotion from both sides):
1. I have an issue with the way Git for Windows behaves on Windows, so I filed an issue.
2. You expressed concerns about negative end-user impact of resolving the issue. (very reasonable)
3. I provided some mitigations to the concerns that I have seen employed in the past (major version bump and long-term migration strategy).
4. You indicated that the proposed mitigations were not acceptable in your eyes.
5. I expressed displeasure at your conclusion, but admitted that it was ultimately your choice.
6. You indicated that I should submit a patch.
7. I asked if a patch for what I proposed would be accepted.
8. You indicated that it would not be.

Step 8 is where I became confused since you told me to submit a patch, but it is unclear what exactly I should submit a patch for.  If my understanding is correct, the solutions I have proposed are not acceptable to you (the maintainer) so there isn't anything to submit a patch for.

Perhaps you are suggesting that I try to come up with a new solution for resolving the default location problem beyond the solutions I have already proposed?  If so then I'll continue to think about it, but I have thought about this problem a lot in the past (having to had to deal with it myself in other projects) and those two are the best I have seen, and I don't expect to get any sudden inspiration this time around.

**Comment by dscho** [comment]
I indicated that I see holes in your reasoning as to addressing the upgrade path issues with *multiple* versions of Git for Windows running at the same time, with *multiple* users of cURL (most of which you would not know use cURL), with *multiple* callers of OpenSSH.

I asked you to submit a patch to see how far you thought things through.
