### ISSUE TITLE
Where do you put aliases and exports without breaking the shell?

### ISSUE THREAD

**Issue by SmailBech** [git-for-windows/git#1288]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit
$ git --version --build-options

** insert your machine's response here **
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
7 64-bit

$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

> type "C:\Program Files\Git\etc\install-options.txt"

$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Disabled

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

### Details

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I have created a ~/.bashrc file containing aliases and exporting some variables. I lose git's command auto-completion and regain it back when I delete the file. I tried with ~/.profile to no avail.

when looking for help on a command.

$ git help stash
No known browser available.

cat doesn't work

Can you please show me how I can fix it ?

Thank you.

**Comment by dscho** [comment]
> I have created a ~/.bashrc file containing aliases and exporting some variables. I lose git's command auto-completion and regain it back when I delete the file. I tried with ~/.profile to no avail.

I have both ``/.bashrc` and `~/.profile`, and I do not lose any auto-completion.

Maybe you can verify that `touch ~/.bashrc && touch ~/.profile` before opening a new Git Bash *still* kills completion for you? If it does not (which I would expect), then maybe the contents of your startup scripts interfere with the Git completion.

**Comment by SmailBech** [comment]
Thank you for the answer.
It was my fault. I had to update the $PATH . concatenation at the end of the paths solved my problem. I was doing it at the beginning which broke everything.

Best regards
