### ISSUE TITLE
problem to work with IntelliJ IDEA

### ISSUE THREAD

**Issue by bahaluly** [git-for-windows/git#1289]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

evrey few days or less, when I open the IntelliJ IDEA, I get that: can't start Git: (...PATH), and I asked to fix the path to the git.exe file, also it in the right path. to fix it I need to reinstall git but anytime it get back that problem. it happand on DELL laptop, windows 10 OS, 64 bit. checked for updates for OS and apps. evreything is UP-TO-DATE and the last verisions.

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options
$  git --version --build-options
git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bi
```10 Home X64 , Dell laptop Vostro 14 5000 Series. Intel core i5 7200UCPU 2.5GHz-2.7DHz, 8GB RAM
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]

** insert your machine's response here **
```

![intellj idea problem](https://user-images.githubusercontent.com/30656158/30123425-a259d28e-933a-11e7-997b-8028bc723143.png)
![intellj idea 2 problem](https://user-images.githubusercontent.com/30656158/30123434-a8e243b6-933a-11e7-89f9-2cc617e41829.png)
![intellj idea 3 problem](https://user-images.githubusercontent.com/30656158/30123479-c6ac549a-933a-11e7-9b1c-6ab78fa7f687.png)
![intellj idea 4 problem](https://user-images.githubusercontent.com/30656158/30123487-cac2d36a-933a-11e7-9795-0c8221ea6dac.png)

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Bash
** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
So when that dialog box appears, can you have a look at that path? What is at `C:\Program Files\Git\mingw64\bin\libssp-0.dll`? Is the file still there? Is it still intact? You can check by opening a *Git Bash* and executing

```sh
$ sha256sum /mingw64/bin/libssp-0.dll
cd2663702076ebdf8c6071ea199263ee805c921b66c883208132ff22b78a6e3a */mingw64/bin/libssp-0.dll
```

(Obviously, only the command after the first `$`, excluding the dollar character.) If the checksum differs, something on your system tampers with that file. If the file is not even there, something in your system tampers with your Git installation itself.

**Comment by bahaluly** [comment]
Hi dscho 
thanks for answering...well I just saw your response and tried to open git bassh and got that dialog box:
![image](https://user-images.githubusercontent.com/30656158/30480499-bc97dbfc-9a22-11e7-9be8-74b673121806.png)
 !!!!!!!
So frustrating )-: I have a project to do and now can not work on it...
Just befor I done that in the frustrating:
open File -> New -> Project frome version control -> Git ... a dialog box opend and than I just cancel it by pressing Escape button...
Now I can't open git bash and keep getting that massage....

what to do?

**Comment by dscho** [comment]
A corrupted `msys-2.0.dll` means that something on your system messes with the Git for Windows installation. Not sure what else to tell you...

**Comment by bahaluly** [comment]
Well I fixed it by reinstall GIT again... for the unlimited time!!!
check the file you asked for and it is the same checksum, for now...I will wait till it happend again..

**Comment by dscho** [comment]
@bahaluly here's hoping that it stays fixed ;-)

I'll just close this for now, but please update this ticket immediately when things go awry again.
