### ISSUE TITLE
GitSDK x64 installation fail on Windows 10 build 10074

### ISSUE THREAD

**Issue by Maximus5** [git-for-windows/git#129]
Tried to install GitSDK x64 on Windows 10 build 10074. Installation failed.

    ( 0/39) checking keys in keyring                                         [----------------------------------------]   0%
          1 [main] pacman 4532 child_copy: dll bss read copy failed, 0x1802AD000..0x1802E5410, done 0, windows pid 4532, Win
    32 error 5
     
    error: segmentation fault
    Please submit a full bug report with --debug if appropriate.
    error: failed to init transaction (unable to lock database)
    error: could not lock database: File exists
      if you're sure a package manager is not already
      running, you can remove /var/lib/pacman/db.lck
    error: failed to init transaction (unable to lock database)
    error: could not lock database: File exists
      if you're sure a package manager is not already
      running, you can remove /var/lib/pacman/db.lck
    error: failed to init transaction (unable to lock database)
    error: could not lock database: File exists
      if you're sure a package manager is not already
      running, you can remove /var/lib/pacman/db.lck
    Could not install pacman

Full log here: https://gist.github.com/Maximus5/fe98fa8e710c16059e3f

There was two installer running simultaneously. But they were installed in separate (default) folders, so they must not conflict.

One more note. It's strange that x64 installer uses 32-bit command processor.

**Comment by dscho** [comment]
> error: segmentation fault

Does [MSys2](https://msys.github.io/) work?

> There was two installer running simultaneously

Please test individually.

> It's strange that x64 installer uses 32-bit command processor.

If you are referring to the installer being a 32-bit executable, yes, we know that, but it is not a critical issue because 32-bit executables run on Windows and it needs to run only one time anyways. So I decided to work on bugs that are actually affecting the way Git works on Windows instead.

**Comment by bviktor** [comment]
I cannot reproduce. Started both git-sdk-installer-1.0.0-rc-3-32.7z.exe and git-sdk-installer-1.0.0-rc-3-64.7z.exe almost simultaneously on Windows 10 10074, they both succeeded.

**Comment by dscho** [comment]
Since this is not reproducible and my question are unanswered, I think it is safe to assume that this problem magically went away.
