### ISSUE TITLE
System.ObjectDisposedException: Cannot access a closed file

### ISSUE THREAD

**Issue by andreanironi** [git-for-windows/git#1295]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.1.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

I'm using portable git, couldn't find any install-options.txt file.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I uninstalled the GitHub desktop app before getting this error.
Git configuration: credential.helper=manager

$ GIT_TRACE=2 git pull origin
15:06:34.755326 git.c:328               trace: built-in: git 'pull' 'origin'
15:06:34.761326 run-command.c:626       trace: run_command: 'fetch' '--update-head-ok' 'origin'
15:06:34.854326 git.c:328               trace: built-in: git 'fetch' '--update-head-ok' 'origin'
15:06:34.994326 run-command.c:626       trace: run_command: 'remote-https' 'origin' 'https://github.com/ec-europa/efsa-reference.git'
15:06:35.106326 git.c:560               trace: exec: 'git-remote-https' 'origin' 'https://github.com/ec-europa/efsa-reference.git'
15:06:35.107326 run-command.c:626       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/ec-europa/efsa-reference.git'
15:06:36.094326 run-command.c:626       trace: run_command: 'git credential-manager get'
15:06:36.329326 git.c:560               trace: exec: 'git-credential-manager' 'get'
15:06:36.330326 run-command.c:626       trace: run_command: 'git-credential-manager' 'get'
fatal: HttpRequestException encountered.
   An error occurred while sending the request.

Unhandled Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at Microsoft.Alm.Git.Trace.Microsoft.Alm.Git.ITrace.Flush()
   at Microsoft.Alm.Cli.ConsoleFunctions.Exit(Program program, Int32 exitcode, String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.Program.Exit(Int32 exitcode, String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.CommonFunctions.DieMessage(Program program, String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.Program.Die(String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.Program.Run(String[] args)
   at Microsoft.Alm.Cli.Program.Main(String[] args)
15:06:37.473326 run-command.c:626       trace: run_command: 'bash' '-c' 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash (mingw 64)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Each command that interacts with the remote trigger this issue; e.g.: 
$ git pull
fatal: HttpRequestException encountered.
   An error occurred while sending the request.

Unhandled Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at Microsoft.Alm.Git.Trace.Microsoft.Alm.Git.ITrace.Flush()
   at Microsoft.Alm.Cli.ConsoleFunctions.Exit(Program program, Int32 exitcode, String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.Program.Exit(Int32 exitcode, String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.CommonFunctions.DieMessage(Program program, String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.Program.Die(String message, String path, Int32 line, String name)
   at Microsoft.Alm.Cli.Program.Run(String[] args)
   at Microsoft.Alm.Cli.Program.Main(String[] args)

```
 - What did you expect to occur after running these commands?

I would expect a pop-up to store my password on the first execution, and a flawless execution on each subsequent request.

 - What actually happened instead?

I'm getting a _fatal: HttpRequestException encountered._ at each request, and I have to insert my username + password each time. The login works (as well as the git commands) anyway.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I'm using a private repository on github...

**Comment by dscho** [comment]
Maybe a trace file is configured in a location that no longer exists? @whoisj could you have a look?

**Comment by whoisj** [comment]
Looks like the pipe to the GIT_TRACE file (perhaps standard error) was while the GCM was attempting to write to it. Given that it's a .NET application it fails to fail gracefully.

@andreanironi the GCM repo is here: https://github.com/Microsoft/Git-Credential-Manager-for-Windows if you wanted to file an issue there as well.

**Comment by dscho** [comment]
> GIT_TRACE=2 git pull origin

Another idea (since you did not seem to have any luck answering @whoisj's and my questions so far): could you try writing to a file, say, `GIT_TRACE=/c/Users/andreanironi/git.log git pull origin`?

**Comment by dscho** [comment]
> could you try writing to a file, say, `GIT_TRACE=/c/Users/andreanironi/git.log git pull origin`?

I take that as a "no".

**Comment by razvanone** [comment]
Had the same issue.

Upgraded git to the latest version:
$ git --version --build-options
git version 2.29.2.windows.2
cpu: x86_64

$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

And installed the https://github.com/microsoft/Git-Credential-Manager-Core as directed from https://github.com/Microsoft/Git-Credential-Manager-for-Windows. No more problems on push to github.
