### ISSUE TITLE
Mintty themes not getting applied

### ISSUE THREAD

**Issue by msowka** [git-for-windows/git#1297]
I've installed 'Git-2.14.1-64-bit' :
```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64
```

Running Win 10 Pro 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

### Details

I'm running mintty based git-bash, loading a theme from https://github.com/oumu/mintty-color-schemes, by dragging one of the <theme>.minttyrc files onto the dialog box has no effect. No effect is seen after clicking Apply, or Save and subsequent restart of minttyrc. I can confirm that on clicking save the theme is saved in the ~/.minttyrc file but does not have any effect on mintty colors.

I expect that on dragging & dropping the theme onto the dialog box, and Apply / Save that the current  future terminals take on the colors defined in the theme.

Note that changing the foreground works. Also, an aside separate ticket, try the 'Glass' Transparancy turns the whole terminal window white, with no perceptible terminal text...

**Comment by PhilipOakley** [comment]
> by dragging one of the .minttyrc files onto the dialog box has no effect.

Personally, I would not have expected that to work as it mixes different operating paradigms. Maybe it does elsewhere (personal ignorance).

I just saved the appropriate `.minttyrc` file in my home drive for that particular Git/bash (remembering that even the root/home drive paths are confused between *nix/Windows).  Currently mine is in "C:\Documents and Settings\Philip\.minttyrc". Simply drag and drop the file (via explorer) into your appropriate folder?

**Comment by msowka** [comment]
Philip, this works out of the box for me on a Win 7 machine, with following differences:
- git version  2.13.0.windows.1
- in shortcut: ".../git-bash.exe" contains no arguments (above win10 include "... --cd-to-home")
- in shortcut: Start in: is set to %USERPROFILE% (above win10 is %HOMEDRIVE%%HOMEPATH%)

**Comment by kgybels** [comment]
@PhilipOakley It is in the documentation for [mintty](https://github.com/mintty/mintty/wiki/Tips#using-colour-schemes-themes):
>In the Options menu, section Looks, the Theme popup offers theme files as stored in a resource directory for selection. This dialog field can be used in different ways:
>
> * Popup the selection to choose a theme configured in your resource directory
> * Insert a file name (e.g. by pasting or drag-and-drop from Windows Explorer)
> * Drag-and-drop a theme file from the Internet (may be embedded in HTML page)
> * Drag-and-drop a colour scheme directly from the Color Scheme Designer (see below)

@msowka For me, the theme doesn't work if it has Windows line endings (CR LF), can you make sure it uses Unix line endings (LF)?

@mintty Does mintty only accept Unix line endings for the theme files?

**Comment by mintty** [comment]
Strict parsing of line-ends had been introduced in 2.7.5 in order to support two new settings (DropCommands, UserCommands) that may contain verbatim CR characters.
This was relaxed again for most settings in 2.7.8.

**Comment by msowka** [comment]
@kgybels, @mintty, good catch w/ line endings; this must be it, I will confirm this evening

**Comment by PhilipOakley** [comment]
> @PhilipOakley - It is in the documentation for mintty:
> In the Options menu, section Looks, the Theme popup offers theme files as 
> stored in a resource directory for selection. This dialog field can be 
> used in different ways:
> Popup the selection to choose a theme configured in your resource 
> directory
> Insert a file name (e.g. by pasting or drag-and-drop from Windows 
> Explorer)
> Drag-and-drop a theme file from the Internet (may be embedded in HTML 
> page)
> Drag-and-drop a colour scheme directly from the Color Scheme Designer (see 
> below)

Thanks. I learnt something just there.

**Comment by dscho** [comment]
@msowka have you found time to test it yesterday evening?

**Comment by msowka** [comment]
I'm afraid that did not do the trick :(, such close. For the record, the mintty version is 2.7.7.

**Comment by mintty** [comment]
Referring to the initial report (rather than the lineend issue):

> I'm running mintty based git-bash, loading a theme from https://github.com/oumu/mintty-color-schemes, by dragging one of the .minttyrc files onto the dialog box has no effect.

Dragging anywhere onto the dialog box is not sufficient. Please drag into the popup field labelled "Theme" or onto the button labelled "Color Scheme Designer". Wait a second, until the scheme is downloaded (its name then appears in the Theme field), then click "Apply". Works here.

**Comment by kgybels** [comment]
> @msowka I can confirm that on clicking save the theme is saved in the ~/.minttyrc file but does not have any effect on mintty colors.

What is being saved in your ~/.minttyrc file? And does this file have correct line endings?

@mintty I think @msowka is dragging into the right place, because something does get saved in ~/.minttyrc.

**Comment by msowka** [comment]
@mintty sorry I was a little loose in my description, yes I was doing precisely as you describe, dragging it onto the Theme drop-down control.

@kgybels On saving the theme file does get placed into the ~/.minttyrc, with no effect on restart. The line endings clones from the repo were unix (these are the ones that should have worked), this morning I tried running them through unix2dos and for the heck of it tried those lendings.

**Comment by mintty** [comment]
Please upload (not paste) your ~/.minttyrc file. Did you also use the "Store" button? If so, please also `ls -l` the stored theme file.

**Comment by kgybels** [comment]
Please upload the theme file in addition to the config file (~/.minttyrc). You can drag files into the comment editor of github, it will upload the file and add a link, however, you will have to change extension to txt or create a zip with both files.

**Comment by msowka** [comment]
My bad for assuming that git would have cloned with Unix line ending! I dos2unixed the themes and all is well!

Thanks for your trouble shooting!
