### ISSUE TITLE
Infinite loop in mingw_rename if rename fails

### ISSUE THREAD

**Issue by WesleySSmith** [git-for-windows/git#1299]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.1.windows.1.1017.gb5915c6ae8.MSVC
built from commit: b5915c6ae881518927b9fa0b3c4df4d3edd37f23
sizeof-long: 4
machine: unknown
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD, PowerShell, Jenkins

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init D:\XXX\workspace
git fetch --no-tags --progress https://XXX/_git/PAPI +refs/heads/*:refs/remotes/origin/* --depth=20
git fetch --no-tags --progress https://XXX/_git/PAPI +refs/heads/*:refs/remotes/origin/* --depth=20
git fetch --no-tags --progress https://XXX/_git/PAPI +refs/heads/*:refs/remotes/origin/* --depth=20
```
 - What did you expect to occur after running these commands?

3 successful  fetches

 - What actually happened instead?

Third fetch hangs

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repo, so can't post.

Process Explorer shows that the git that's hanging is not the one launched.  Instead:
git.exe -> git.exe -> git.exe -> git-remote-https.exe -> git.exe -> git.exe,
The last git.exe in the chain is the one that's hanging - it takes 100% of the CPU and never exits.  Its command line is:

git --shallow-file D:/XXX/workspace/.git/shallow.lock index-pack --stdin -v --fix-thin "--keep=fetch-pack 6676 on XXXBLD03" --pack_header=2,3425

I've compiled a debug version of git and have looked at the hang.  There's an infinite loop in mingw_rename:

On line 2411, MoveFileExW fails
On line 2414, gle = 5 (ACCESS_DENIED)
On line 2418, SetFileAttributesW is called as expected
On line 2420 the "if" is false, so the function doesn't return on line 2422
On line 2425 condition is true, so if block is evaluated
On line 2435, the condition is true so the if block is evaluated
On line 2437, the goto repeat; command runs, which starts the loop again from line 2410.

So, it appears that if the rename fails, the code tries to fix up the file attributes and tries again, but if that's not the problem, then there's an infinite loop.

As to why exactly this rename is failing, it seems that a file is being renamed from .git/objects/pack/tmp_pack_96bdnb to .git/objects/pack/pack-ae983dc9c8057f4d5d2c8cdc3485cb6badde864b.pack,  but a file with the destination name already exists.

**Comment by dscho** [comment]
Does 

```diff
diff --git a/compat/mingw.c b/compat/mingw.c
index 973965b2cda..44af609c4eb 100644
--- a/compat/mingw.c
+++ b/compat/mingw.c
@@ -2422,7 +2422,8 @@ int mingw_rename(const char *pold, const char *pnew)
 		return -1;
 	}
 
-	if ((attrs = GetFileAttributesW(wpnew)) != INVALID_FILE_ATTRIBUTES) {
+	if (attrs != INVALID_FILE_ATTRIBUTES &&
+	    (attrs = GetFileAttributesW(wpnew)) != INVALID_FILE_ATTRIBUTES) {
 		if (attrs & FILE_ATTRIBUTE_DIRECTORY) {
 			DWORD attrsold = GetFileAttributesW(wpold);
 			if (attrsold == INVALID_FILE_ATTRIBUTES ||
```

fix it for you?

**Comment by WesleySSmith** [comment]
The change proposed fixes the issue for me.  I now no longer see the infinite loop and correctly see this error on the console:

```
error: unable to write sha1 filename .git/objects/pack/pack-ae983dc9c8057f4d5d2c8cdc3485cb6badde864b.pack: Permission denied
fatal: cannot store pack file
fatal: index-pack failed
```

Now that this infinite loop is fixed, mingw_rename is correctly returning an errno of EACCES, but it turns out that there is an error in the main git implementation that's causing the git command to fail even after this proposed fix is made to the Windows-specific code.

See the thread I started on the git mailing list at https://public-inbox.org/git/c9b3bc17110048f0b7943704cfbd8f68@APEXC04.auctionpay.com/T/#u for the full details, but the short version is that the caller (finalize_object_file) is incorrectly interpreting the EACCES errno from rename.  That bug in sha1_file.c  is seeing the EACCES result and is considering it a failure, when it should just be ignoring the fact that a file with the newfile name already exists and continuing on.

Thanks for your help in resolving the Windows specific aspect of this issue.

**Comment by dscho** [comment]
The real question is: why is that pack already there. We should not write it if it is there, let alone force-rename a "new" version.
