### ISSUE TITLE
[minor] README.portable update git.cmd to git.exe

### ISSUE THREAD

**Issue by eladkarako** [git-for-windows/git#1307]
possibly folder structure updated from some time ago.

<blockquote>
Adjust the 'gitdir' according to your setup.  As long as you do not
close the command window, you can now simply type "git" or "gitk" to
really call "c:\portablegit\cmd\git.cmd" or "c:\portablegit\cmd\gitk.cmd".

By default, git-cmd and git-bash use the directory they were started from as
</blockquote>

<img src="https://i.imgur.com/cv2QtQV.gif"/>

it will still work if cmd suffix won't be explicitly specified,
since both cmd and exe are runnable in Windows.
but if a user specify <code>git.cmd</code> in a batch-script, it will fail in newer versions.

possibly need to update the README for other variations too (didn't check).

**Comment by dscho** [comment]
> possibly need to update the README for other variations too (didn't check).

Could you please check? And could you please open a PR to fix this (the file to be patched is here: https://github.com/git-for-windows/build-extra/blob/master/portable/root/README.portable)?

This would help enormously.
