### ISSUE TITLE
Case rename not detected

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#131]
Renaming a file by changing only its case is not detected by git. git mv does support it though.

```
git init
echo hello > foo
git add foo
git commit -m initial
mv foo Foo
git status # No changes
git add . -A # Doesn't add anything
```

**Comment by dscho** [comment]
This is not specific to Windows, but it happens with *all* case-insensitive file systems. Therefore it would be better to report this on (and to work on a solution with) [the Git mailing list](mailto:git@vger.kernel.org).

**Comment by orgads** [comment]
Done. Thanks.
