### ISSUE TITLE
Windows 10 : Git-bash : exit code 3221225477 when using gulp and gulp-shell

### ISSUE THREAD

**Issue by craph** [git-for-windows/git#1311]
Currently I have an issue on my windows 10 computer when I am trying to launch a gulp task that runs a gulp-shell to execute a shell script.

I have installed: 
Git-for-windows version 2.14.1.windows.1 with Git bash 4.4.12(1)
NodeJs : v6.9.1
Npm : 5.0.4

the .sh file are associated with the Git bash application as default program

When I start my gulp task I get this error :

> [10:46:26] Error in plugin 'gulp-shell'
> Message:
>     Command `deploy-res.sh 1.0-SNAPSHOT` failed with exit code **3221225477**

Here is my Gulp tasks :
```
gulp.task('deploy-res', shell.task([
    'deploy-res.sh ' + '1.0-SNAPSHOT'
], {
    cwd: 'scripts'
}));
```
And here my shell script
```
#!/usr/bin/env bash
echo "Deploying Resources to '$JBOSS_HOME/standalone/deployments'"
...
echo "Deploying Resources...DONE"
read -p "Press enter to continue"
```

I have tryed to launch the gulp task in windows cmd.exe, git bash, powershell and I always get the same issue.

If I installed an old version of Git bash I didn't get the error. 
Git-for-windows version : 2.12.2.windows.1
Bash version 4.4.12(1)

May be an important changes has been made between git-for-windows 2.13.2.windows.1 and 2.13.3.windows.1 and more recent version.

Please could you have a look on the issue ?

Best regards,

**Comment by dscho** [comment]
```sh
$ printf "%x" 3221225477
c0000005
```

So this is our old friend, the Access Violation (what Unix/Linux call "segmentation fault").

Is there *any* easier way to reproduce this than to install all of those node.js things?

**Comment by dscho** [comment]
There is a time when I get not only tired, but actually quite a bit annoyed of being left waiting.
