### ISSUE TITLE
Latest Git kills command prompt (Windows) when using "git submodule update --init --recursive".  Previous version does not

### ISSUE THREAD

**Issue by kkennett** [git-for-windows/git#1312]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.2.windows.1
built from commit: 788debdfb6b794425a3b949dd1a0eb2425a72e96
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.  Install 2.14.1.windows.1 and things work fine.  Install 2.14.2.windows.1 and problem presents.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

git clone <url> <local name>
git submodule update --init --recursive

```
 - What did you expect to occur after running these commands?

submodules to update

 - What actually happened instead?

submodules start to update, but then command window just disappears (crashed).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No. Internal private repository.

**Comment by dscho** [comment]
> No. Internal private repository.

Maybe you can initialize a minimal *public* repository to make this much easier to reproduce, and to verify in the process that this is not specific to your repository.

**Comment by patrick984** [comment]
I have observed the same issue when using the git-subrepo module. Any of the `git subrepo ...` commands cause the terminal window to disappear immediately (however the bash.exe process stays alive forever). Reverting to 2.14.1.windows.1 fixes the problem.

To reproduce first install git subrepo (https://github.com/ingydotnet/git-subrepo) then using git bash:

```
mkdir test-repo
cd test-repo
git init
mkdir test-subrepo
touch test-subrepo/a.txt
git add test-subrepo/a.txt
git commit -m initial
git subrepo init test-subrepo
```

**Comment by csmager** [comment]
This sounds like the same thing I get with git lfs when using 2.14.2. I logged at git-lfs: https://github.com/git-lfs/git-lfs/issues/263.

**Comment by kkennett** [comment]
i am not able to do much right now as i am away from my system.  patrick984 has a repo - can you try that?  Can we roll back to the previous version until this problem is resolved?

**Comment by dscho** [comment]
> I logged at git-lfs: git-lfs/git-lfs#263.

@csmager you probably meant git-lfs/git-lfs#2631 instead.

**Comment by dscho** [comment]
After 3h of bug hunting, I found not only the problem, but also that it was already fixed in Cygwin: cygwin/cygwin@21a39b20a53d6c26959296765a7006af377ce37b (I simply did not see it before today and consequently failed to adjust Git for Windows accordingly).

**Comment by dscho** [comment]
I think this is fixed by https://github.com/git-for-windows/MSYS2-packages/commit/e9d0a2be2720007c2a734866ebbb4c15e503003c.

**Comment by dscho** [comment]
If all goes well, a new snapshot will appear at https://wingit.blob.core.windows.net/files/index.html within the hour. When it does, please test?

**Comment by OtherShadeOfBlue** [comment]
@dscho That snapshot fixes it for me.
I have a several scripts that broke for the same reason and work again using your snapshot.

**Comment by dscho** [comment]
@OtherShadeOfBlue thanks for the feedback!
