### ISSUE TITLE
Standalone git-bash without git

### ISSUE THREAD

**Issue by pptime** [git-for-windows/git#1313]
Hi,

Is it possible to extract the bash from the git-for-windows project?

May I know if there is any build option that allows to generate a portable bash only release?

Kind regards,

Hao

**Comment by PhilipOakley** [comment]
Look for the Msys2 project, which is the basis that the GfW sits on top.
  ----- Original Message ----- 
  From: How Who 
  To: git-for-windows/git 
  Cc: Subscribed 
  Sent: Tuesday, October 03, 2017 1:31 PM
  Subject: [git-for-windows/git] Standalone git-bash without git (#1313)


  Hi,

  Is it possible to extract the bash from the git-for-windows project?

  May I know if there is any build option that allows to generate a portable bash only release?

  Kind regards,

  Hao

**Comment by pptime** [comment]
Yes, I found it out. There is a portable build as well. 
Thx.
