### ISSUE TITLE
GfW should not prevent third-party diff tools from saving to local copy of file

### ISSUE THREAD

**Issue by arx-kh** [git-for-windows/git#1315]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit
```
$ git --version --build-options

git version 2.14.2.windows.1
built from commit: 788debdfb6b794425a3b949dd1a0eb2425a72e96
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Creators Update 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No. Using a newly installed and updated test machine. No other software, such as antivirus.

.gitconfig configured to to make Git use external tool such as 'Araxis Merge' or 'WinMerge' for file comparisons in the standard way:

```
[diff]
    tool = winmerge
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Either Git Bash or CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

With a trivial repo containing a modified file in the local working copy.
```
git difftool
```
Then modify and save change to local copy using the diff tool.

 - What did you expect to occur after running these commands?

Expected files to open in external GUI diff tool and be able to save changes to file.

 - What actually happened instead?

Files opened in external GUI diff tool but unable to save changes to local working copy. The following error message displayed in a dialog window.
```The requested operation cannot be performed on a file with user-mapped section open```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No. Every repo.

### Additional Details

This is a problem in every release since v2.12.2. In v2.12.1 and earlier, it was possible to save changes to files opened in external tools using `git difftool`

Further testing has shown that the problem occurs on Windows 7 SP1 and Windows 8.1. And is independent of versions of the external diff tool.

**Comment by dscho** [comment]
Thanks to the instructions, and the hint that this happens for every repo, I could reproduce (not with `vimdiff`, BTW, which I tried first) on Windows 10.

Digging into the issue with [Sysinternals' Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) it looks as if `git diff` (which is called with `GIT_EXTERNAL_DIFF=git-difftool--helper`) still has a view open to the modified file.

**Comment by dscho** [comment]
Please test the newest snapshot: https://wingit.blob.core.windows.net/files/index.html

**Comment by arx-kh** [comment]
Thank you. The snapshot _Git-prerelease-2.14.2.windows.1.3.g327fab0447-64-bit.exe_ fixes the problem for me.

**Comment by dscho** [comment]
Awesome. I plan to publish Git for Windows v2.14.2(2) later today, based on your feedback. Thank you.

**Comment by gkv311** [comment]
Thank you for fixing the issue! I've just checked snapshot on my #1287.
Sorry to be to slow on providing feedback (just started to check releases, before I've realized that bug has been already found and fixed).

**Comment by dscho** [comment]
@gkv311 I am glad it works for you.
