### ISSUE TITLE
Git submodule update fails if ssh key uses passphrase

### ISSUE THREAD

**Issue by Hickstone** [git-for-windows/git#1319]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

$ git --version --build-options
git version 2.14.2.windows.1
built from commit: 788debdfb6b794425a3b949dd1a0eb2425a72e96
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
64-bit

$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Enabled

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git-Bash and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git clone <my-repo-url>
cd my-repo
git submodule update --init --recursive

 - What did you expect to occur after running these commands?

The submodule defined in .gitmodules appear in the specified path

 - What actually happened instead?

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(two times)

It actually helps using a ssh key with no pass phrase or using the ssh-agent.
So my assumption is that there is no "password input" and the update fails.

**Comment by kgybels** [comment]
I can't reproduce. I disabled ssh-agent and gave it a try, it is asking for passphrase using the following dialog:
![image](https://user-images.githubusercontent.com/2051188/31394549-dfbd90c0-adde-11e7-9124-2a113067fe8a.png)

@Hickstone What is SSH_ASKPASS set to?
```
KGybels@PC-KIM MINGW64 /
$ echo $SSH_ASKPASS
/mingw64/libexec/git-core/git-gui--askpass
```

**Comment by Hickstone** [comment]
I was able to find the issue and implement a workaround.
To find the issue, i set the ssh log level to DEBUG3
The log showed suspicious lines:
debug1: read_passphrase: can't open /dev/tty: No such device or address
debug2: no passphrase given, try next key

I follwed the steps in the comment of this issue:
https://github.com/git-for-windows/git/issues/327#issuecomment-142883258 

The "DISPLAY=require" did the trick for me.
My Computer was nearly untouched with a standard git installation. Shouldn't the variables be set when the package is installed?
A colleague had the same problem on his Windows 10 machine.

**Comment by dscho** [comment]
@Hickstone can you re-try with v2.14.2(3)? (There was a Console-related fix in v2.14.2(2), but you really want to try the latest for other reasons)

If that still does not fix the issue, please try to figure out a minimal example. I could imagine that the problem occurs when you use a submodule with a fictitious SSH URL (e.g. `nobody@github.com:invalid`), and making sure that you can provide an example that fails for you and that also fails for others will already go a long way to facilitate others' assistance in helping you resolve your issue.

**Comment by Hickstone** [comment]
The issue persists in version 2.14.3.
Steps to reproduce:
  - git clone git@github.com:Hickstone/mainrepo.git
  - cd mainrepo
  - git submodule update --init --recursive
Alternative:
  - git clone git@github.com:Hickstone/mainrepo.git --recurse-submodules

**Comment by kgybels** [comment]
> @Hickstone My Computer was nearly untouched with a standard git installation. Shouldn't the variables be set when the package is installed?

`DISPLAY` and `SSH_ASKPASS` are set in [`C:\Program Files\Git\etc\profile.d\env.sh`](https://github.com/git-for-windows/build-extra/blob/git-sdk-1.0.6/git-extra/env.sh):
```
# Add bin path in the home directory ontop of the PATH variable
export PATH="$HOME/bin:$PATH"

# Allow SSH to ask via GUI if the terminal is not usable
test -n "$SSH_ASKPASS" || {
	case "$MSYSTEM" in
	MINGW64)
		export DISPLAY=needs-to-be-defined
		export SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
		;;
	MINGW32)
		export DISPLAY=needs-to-be-defined
		export SSH_ASKPASS=/mingw32/libexec/git-core/git-gui--askpass
		;;
	esac
}
```

Note that it is only set if `SSH_ASKPASS` isn't already set.

**Comment by Hickstone** [comment]
@kgybels That helped me find the cause.
SSH_ASKPASS ist set via an install script (after the git installation). That is, because git is deployed by SCCM.
The env.sh is only set when starting the git bash and not in the installation itself.
Therefore the DISPLAY variable never gets set ...
