### ISSUE TITLE
_netrc doesn't work on https push

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#132]
I have an entry for github in ~/_netrc:
`machine github.com login <login> password <password>`

My remote is `https://github.com/<repo>`

When I push, it requests for username and password.

It worked for me with 1.9.5. With 2.3.7 it doesn't.

**Comment by dscho** [comment]
https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines

**Comment by orgads** [comment]
Sorry, I thought the subject was self-descriptive. Extended it.

**Comment by dscho** [comment]
You could try to use `GIT_CURL_VERBOSE=1` to find out more.

**Comment by orgads** [comment]
Thanks for this information. The problem was that I had CRLF line endings in _netrc.

Is is possible to support it in order to maintain backwards compatibility?

**Comment by dscho** [comment]
> Is is possible to support it in order to maintain backwards compatibility?

Everything is possible in Open Source. It just takes a volunteer to do it ;-)

If you are that volunteer, here is how to go about it:

```bash
cd /usr/src/MINGW-packages/mingw-w64-curl
git remote add -f upstream https://github.com/Alexpux/MINGW-packages
git checkout -t upstream/master
makepkg-mingw -s
```

That will build the current cURL package using the `PKGBUILD` file in that directory.

Then switch to `src/curl*` and initialize a Git repository so you can make a patch that fixes the issue. This patch needs to be applied as part of the `PKGBUILD`, then a Pull Request should be opened (preferably to [the upstream repository](https://github.com/Alexpux/MINGW-packages)).

**Comment by orgads** [comment]
Done: https://github.com/Alexpux/MINGW-packages/pull/613

**Comment by orgads** [comment]
Added a PR also to real upstream: https://github.com/bagder/curl/pull/258

**Comment by dscho** [comment]
@orgads this is outstanding, you made my day!

**Comment by dscho** [comment]
According to http://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/, no new package has been released yet. Let's close the bug when there is a new `mingw-w64-curl` package available from the Pacman repositories (which will thereby enter the next release of Git for Windows).

**Comment by dscho** [comment]
@orgads could you run `pacman -Syu` and then test again? Your fixes should be in, judging by the pkgrel being `3` in the newest release. Feel free to close the ticket if everything pans out alright.

**Comment by nalla** [comment]
I took liberty of testing this issue.
```_netrc
[OK]  machine github.com login foo password bar<cr><lf>
[OK]  machine github.com login foo password bar<lf>
[NOk] machine github.com login foo password bar<cr>
```
The old mac way does **not** work. I believe we can mark this as *passed*, since the old mac way is not really in use on windows environments.

**Comment by orgads** [comment]
Running `pacman -Syu` doesn't update curl here... It updated some other packages, but not curl.

**Comment by dscho** [comment]
@orgads it would update `mingw-w64-x86_64-curl` and/or `mingw-w64-i686-curl`... Can you paste what `pacman -Q mingw-w64-x86_64-curl` says (adjust it if you have a 32-bit setup)?

**Comment by dscho** [comment]
> The old mac way does not work.

:-) That's what I call thorough testing! You're right, though, we do not need to care about CR-only line endings. Even MacOSX deviated from that MacOS practice.

**Comment by orgads** [comment]
Yup, seems to work fine.
