### ISSUE TITLE
2.14.2(3) = git-lfs/2.3.2 NOT 2.3.3 in the release notes.

### ISSUE THREAD

**Issue by zezba9000** [git-for-windows/git#1324]
"git lfs version" reports git-lfs/2.3.2. However the release notes for 2.14.2(3) say it should be 2.3.3.

**Comment by dscho** [comment]
Correct. I had been made aware of that already: https://public-inbox.org/git/alpine.DEB.2.21.1.1710171101280.40514@virtualbox/T/#m3905be695573a5317aca5dc646d9e93f92f989ea

As there is an imminent release of a new cURL version on Monday, and as I also want to finish a couple of installer/upgrade improvements, as well as some changes in the release engineering that will hopefully prevent similar problems in the future, I decided to defer a new Git for Windows version to Monday.

**Comment by dscho** [comment]
v2.14.3 was released with Git LFS v2.3.4, even.
