### ISSUE TITLE
find command not working properly when combined with sed

### ISSUE THREAD

**Issue by sumithar** [git-for-windows/git#1328]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```$ git --version --build-options
git version 1.9.5.msysgit.1

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

$ cmd.exe /c ver
```Microsoft Windows [Version 6.3.9600]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```defaults
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Gitbash
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```Trying to execute a find command and then a sed to do some text replace. It fails
 
```find  . -type f -name pom.xml -exec sed -i 's/3.0.0-SNAPSHOT/3.1.0-SNAPSHOT/g' {} +
 - What did you expect to occur after running these commands?

It should replace the text string in pom.xml files in the directory and subdirectories

 - What actually happened instead?

`find: missing argument to `-exec'`
This command works fine in Babun and Cygwin
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> ** insert your machine's response here **

Please replace those comments, not add to them.

> ```
> $ git --version --build-options
> git version 1.9.5.msysgit.1
> ```

This version is deprecated for several years, it is very unsafe to use it still.

Git for Windows 1.x was superseded by this project, so technically this is the wrong bug tracker, too. I highly encourage you to upgrade to Git for Windows 2.x to stay on the safe side (it may require a bit of effort to make things work again after staying with Git for Windows 1.x for so long).

> ```
> find . -type f -name pom.xml -exec sed -i 's/3.0.0-SNAPSHOT/3.1.0-SNAPSHOT/g' {} +
> ```

Please note first of all that this is not a Git problem, so a more appropriate forum would be the MSYS2 project's help channels.

I am a bit surprised that you did not end the command with `\;`, though, like so:

```
find  . -type f -name pom.xml -exec sed -i 's/3.0.0-SNAPSHOT/3.1.0-SNAPSHOT/g' {} \;
```

Do note that this invocation of `sed` is not portable, and will fail on macOS.

**Comment by sumithar** [comment]
I have upgraded the git and it works fine.
