### ISSUE TITLE
Git Bash: Not showing my keyboard input

### ISSUE THREAD

**Issue by ahmedmohiduet** [git-for-windows/git#1330]
So, running:
`git ls-files|grep navbar.html|xargs vim`

making my git bash no longer show my keyboard input any more until i'm doing `reset`
Please see: https://stackoverflow.com/questions/45893050/git-bash-not-accepting-my-keyboard-input

Can you give me some idea why this is happening? I would like to contribute some codes fix this myself if need be

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> ** insert your machine's response here **

Please note that it really sends a message if the bug report does not even bother to fill out the information that was requested. You may want to consider in the future putting as much diligence into a bug report as you wish anybody else to pay to it.

Also, there was a crucial bit of information just left out: just after executing that command-line, it shows this:

```
Vim: Warning: Input is not from a terminal
```

First of all, how to get the terminal to accept input again? This is performed by the `reset` command.

Now, a straight-forward web search for this warning turns up e.g. https://groups.google.com/forum/#!topic/vim_use/7yDOngWLaT4, which clarifies that this is yet another unintuitive design of vim: if you want vim to take file names from stdin, you have to pass `-` as the "file name". In your case:

```sh
git ls-files | grep navbar.html | xargs vim -
```

**Comment by ahmedmohiduet** [comment]
Hi dscho! It looks like my vim now giving:
$ git ls-files|grep navbar.html|xargs vim -
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun  1 2017 21:25:47)
Too many edit arguments: "src/main/resources/templates/fragments/navbar.html"
More info with: "vim -h"

**Comment by dscho** [comment]
Oh, you're right, the correct invocation would have been `... | vim -`, i.e. *dropping* the `xargs`, but that opens the file list in vim, not the files themselves.

However, again a web search is your best friend: https://unix.stackexchange.com/questions/77395/grep-l-xargs-vim-generates-a-warning-why

Essentially, you will have to trick `vim` to use the terminal for `stdin` again, like so:

```sh
git ls-files | grep navbar.html | xargs sh -c 'vim "$@" <$0' /dev/tty
```

You may want to use `xargs`' `-r` option to prevent `vim` from being called if there is no matching file, and then use `-d '\n'` option to handle file names with spaces (or cut out the `grep` altogether by using `git ls-files -z \*navbar.html | xargs -0 ...`), too.

Please note, however, that nothing in this ticket is specific to Git, or even to Windows! Meaning that I could not really afford the time to answer your question, as there are very real Git issues waiting for my attention. Maybe you want to alleviate this by contributing back a little, e.g. trying to help others in other tickets?
