### ISSUE TITLE
"fatal error - cygheap base mismatch detected" on FCU

### ISSUE THREAD

**Issue by sylveon** [git-for-windows/git#1331]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.14.2.windows.3
built from commit: 924c19fc000d3759486b68bd73bc592fa02e367c
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.16299.19]
```

(64-bits)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

 - Which terminal/shell are you running Git from?

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull # on my old install, but works on clean install
git add -p # on my clean install
```
 - What did you expect to occur after running these commands?

git pulls or uses patch mode to add changes

 - What actually happened instead?

```
C:\Users\Charles\Git\ShareX>git add -p
      1 [main] perl (10124) C:\Program Files\Git\usr\bin\perl.exe: *** fatal error - cygheap base mismatch detected - 0x2EE7408/0x2D97408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] perl 7588 fork: child -1 - forked process 10124 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
      2 [main] perl (11072) C:\Program Files\Git\usr\bin\perl.exe: *** fatal error - cygheap base mismatch detected - 0x2EE7408/0x3157408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
5037298 [main] perl 7588 fork: child -1 - forked process 11072 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
^C
C:\Users\Charles\Git\ShareX>
```

```
Unpacking objects: 100% (6/6), done.
From https://github.com/DiscordInjections/DiscordInjections
   dc3658e..f82109f  master     -> origin/master
      2 [main] sh (5924) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x3330400/0x33C0400.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 8388 fork: child -1 - forked process 5924 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: No child processes
      1 [main] sh (6240) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x3330400/0x32C0400.
```

Please note this is a completely clean install, and I do not have any other cygwin version installed. It only happens on the Fall Creator's Update, every update before works fine.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Occurs with multiple repos

**Comment by sylveon** [comment]
Seems related to https://github.com/desktop/desktop/issues/3096

**Comment by forrestcoward** [comment]
I'm experiencing the same issue on clean Git for Windows installations on Windows Server 2016 boxes. Rebooting fixes the issue for me most of the time (until the next reboot, which may it may not work)

```
      1 [main] sh (8200) C:\1image\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x10D9408/0xEC9408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

Note this is a clean installation. Cygwin is not installed nor has it ever been installed. 

I'm running version 2.14.1.windows.1, and have not seen this issue prior to moving machines to Windows Server 2016.

Thanks for the help, and can answer any other questions.

Thanks!

**Comment by sylveon** [comment]
I still have it after a reboot, but as mentionned earlier, I don't have a msys or cygwin install.

**Comment by shiftkey** [comment]
@sylveon we believe we have a workaround but I'd also like to see what base address is set for your `msys-2.0.dll` assembly. Could you run these steps in a command prompt and attach what `rebase.exe` returns on that last line?

```cmd
REM change this to the appropriate Git installation's location:
C:
CD "\Program Files (x86)\Git\usr\bin"
.\rebase.exe -i msys-2.0.dll
```

**Comment by sylveon** [comment]
```
C:\Program Files\Git\usr\bin>.\rebase.exe -i msys-2.0.dll
/usr/bin/msys-2.0.dll                     base 0x000180040000 size 0x005c0000
```
This is mine.

**Comment by dscho** [comment]
@sylveon since desktop/desktop#3096 talks about ASLR being forced on for all executables, is this the case for you, too?

**Comment by sylveon** [comment]
https://github.com/desktop/desktop/issues/3096#issuecomment-339403094 🤔 

----

I found a "fix". Add an exclusion for each program that crashes with that message until it works as desired. Example for `git add -p` with perl excluded:
![image](https://user-images.githubusercontent.com/6440374/32028106-c98803a2-b9ba-11e7-99e0-c67b76918e12.png)
with sh and perl excluded:
![image](https://user-images.githubusercontent.com/6440374/32028162-05d0196c-b9bb-11e7-9d1f-fa7a0c6d2c93.png)

Just add more until it works :D
