### ISSUE TITLE
Update checker is intrusive

### ISSUE THREAD

**Issue by seishun** [git-for-windows/git#1335]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
```

```
git version 2.14.2.windows.3
built from commit: 924c19fc000d3759486b68bd73bc592fa02e367c
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

I enabled the update checker when installing Git for Windows. I randomly got an update notification while watching a video. It should only notify about updates when actually running a git command.

**Comment by dscho** [comment]
> I randomly got an update notification while watching a video. It should only notify about updates when actually running a git command.

There is a plan to use "toasts", i.e. notifications when possible (i.e. Windows 8 and later). I cannot say how quickly I will get to this.

If you find some time to help this issue, it would be greatly appreciated.

**Comment by dscho** [comment]
This is now implemented, and will be part of the next Git for Windows version. It's a little sad that I did not get any help here, but in hindsight I understand: it took a *long* time to implement. Still, help is always appreciated.

**Comment by 391861737** [comment]
> This is now implemented, and will be part of the next Git for Windows version. It's a little sad that I did not get any help here, but in hindsight I understand: it took a _long_ time to implement. Still, help is always appreciated.

I recently wrote a shell script that is intended to install and update `Git-for-windows` on my own msys2 environment which contains lots of tools I downloaded, compiled, ported from some other Linux environment and whatnot. 
That script managed to gather the necessary information such as `{ latest: "v2.23.0.windows.1", version: "2.23.0" }` from [This repo's tags](https://github.com/git-for-windows/git/tags), and then forge the download URL, then download, then unpack it with [innounp](http://innounp.sourceforge.net/), then copy the necessary folders, files respectively to its place (Which may not match the complete list, but works fine as I tested).

So, might this help with this feature, and how may I manage it?

**Comment by dscho** [comment]
> might this help with this feature, and is it does then how may I manage to help?

I think that your use case is targeted more at power users who really want Git as an integrated package in their MSYS2 setup. This is not the common case with the vast majority of Git for Windows users ;-)

Having said that, your script could probably find a really good home in https://github.com/git-for-windows/build-extra, for other power users similar to you.

**Comment by 391861737** [comment]
> > might this help with this feature, and is it does then how may I manage to help?
> 
> I think that your use case is targeted more at power users who really want Git as an integrated package in their MSYS2 setup. This is not the common case with the vast majority of Git for Windows users ;-)
> 
> Having said that, your script could probably find a really good home in https://github.com/git-for-windows/build-extra, for other power users similar to you.

I'm sorry that I did not reply in time, I've been in a very busy state lately... 
Thank you for your advice, I'll fork and create a PR in the next few days...
