### ISSUE TITLE
Newest git for windows seems to be missing msys-icuuc59.dll

### ISSUE THREAD

**Issue by filcab** [git-for-windows/git#1336]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.14.2(2) and 2.14.2(4) both have this problem.

```
$ git --version --build-options
git version 2.14.3.windows.1
built from commit: dbc8d81072630bc50324938b9ac950140669ced9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not really

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Included bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ xmllint --help
E:/software/Git/usr/bin/xmllint.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```
 - What did you expect to occur after running these commands?

I expected xmllint to run and show its help.

 - What actually happened instead?

A dialog box comes up telling me it can't find msys-icuuc59.dll.

Also:
```
$ find /usr -iname '*icu*'
/usr/bin/msys-sqlite3icu-0.dll
$ # The library doesn't seem to ship with the git for windows package
```

I am aware that xmllint isn't git, but it is being packaged with it. I expect it to either not be packaged, or be packaged with all the DSOs it needs.

Thank you,

 Filipe

**Comment by dscho** [comment]
> I am aware that xmllint isn't git, but it is being packaged with it. I expect it to either not be packaged, or be packaged with all the DSOs it needs.

Indeed, the error is that xmllint is packaged with Git for Windows.

**Comment by filcab** [comment]
Thank you.
Can confirm that 2.15.0 is fixed.

 Filipe

**Comment by zakkirkharim** [comment]
We are trying to use yang2dsdl with gitbash and we get a similar of missing DLL. We are using git version 2.15.1, and I wonder why this issue there if 2.15.0 itself is fixed. i.e. it has msys-xml2-2.dll but not this icuuc dll.
Is the solution suggested that git should not have any such libxml2 related dll and we should separately download xsltproc/xml dlls if wants to use those libraries?

**Comment by dscho** [comment]
@zakkirkharim could you please elaborate a bit more? I do not understand what the problem is.

**Comment by k2ksk2k** [comment]
@dscho The xmllint.exe could be compiled without msys-icuuc59.dll. You can compile a new xmllint.exe with source code in mingw/msys, then replace the xmllint.exe in the Git/usr/bin. Or you can download the missing dlls from some website, what you need is msys-icuuc59.dll, msys-stdc++-6.dll and msys-icudata59.dll.

**Comment by dscho** [comment]
@k2ksk2k Indeed, you could compile a new `xmllint.exe` if you need one. That executable is in no way necessary for Git to work, so the bug was to bundle it in Git for Windows to begin with. And this bug has been addressed.
