### ISSUE TITLE
installer - options checkboxes cannot be seen

### ISSUE THREAD

**Issue by vtbassmatt** [git-for-windows/git#1342]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17025.1000]   (64-bit)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Windows Insider "Selfhost" level. This is a Surface Book connected to two external monitors, so there are occasional DPI issues. (But I've never seen a bug like this before in the GfW installer, even on this hardware.) Screens are:

- 3000x2000 @ 200% (Surface Book screen)
- 2560x1440 @ 100% (each external monitor)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
n/a, this is an installer bug
```
 - What did you expect to occur after running these commands?

On the options screen, I expected the usual hierarchical treeview of checkboxes

 - What actually happened instead?

Checkboxes were dedented to the left so far that I couldn't see them. I didn't want to change any options anyhow (this was an upgrade from 2.14.something), it wasn't a blocking issue.

![image](https://user-images.githubusercontent.com/714283/32220644-d9bf945e-be08-11e7-9d54-7b9c16774c21.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by dscho** [comment]
First time I see a problem like this...

> Microsoft Windows [Version 10.0.17025.1000] (64-bit)

That may be the culprit. Did you get a chance to give feedback via the Insider track yet?

**Comment by vtbassmatt** [comment]
That's what I'll do. Thanks!

**Comment by k-j-kleist** [comment]
I'm a Windows Insider in the Slow Ring, and also encountered this issue using build 17025.

Just now, I updated to build 17063 and this issue now seems to be history.

**Comment by dscho** [comment]
Excellent, thanks for the feedback!
