### ISSUE TITLE
git rebase --continue/abort showing usage message instead of performing expected action

### ISSUE THREAD

**Issue by marrhub** [git-for-windows/git#1346]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.2.windows.3
built from commit: 924c19fc000d3759486b68bd73bc592fa02e367c
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I've tried reinstalling Git for Windows to no avail.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git pull --rebase
remote: Counting objects: 111, done
...
error: Failed to merge in the changes.
...
Falling back to patching base and 3-way merge...
Auto-merging ...
CONFLICT (add/add): 
...
Patch failed at 0001 ...
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

{ resolving conflicts }

$ git rebase --continue
usage: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] [<upstream>] [<branch>]
   or: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] --root [<branch>]
   or: git-rebase --continue | --abort | --skip | --edit-todo

Available options are
    -v, --verbose         display a diffstat of what changed upstream
...

$ git-rebase --continue
bash: git-rebase: command not found

$ git rebase --abort
usage: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] [<upstream>] [<branch>]
...
```
 - What did you expect to occur after running these commands?

I expected git rebase --continue or git rebase --abort to perform appropriate actions.

 - What actually happened instead?

Usage help message is being displayed as if I've mistyped the command which is not the case.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Nope. Internal repository.

**Comment by dscho** [comment]
Hmm, that's not a lot to work with, as you did not even try to verify that the problem can be reproduced with a public project.

On the upside, this allows me to sit back and let you do all the work, such as verifiying that you call the correct executable (`type git`), that `git-rebase` exists in the location indicated by `git --exec-path`, that the output with `GIT_TRACE=1` does look correct, etc

**Comment by marrhub** [comment]
Unfortunately this incident occures in git at work and I don't have much time to reproduce issue with some 3rd party repository. Also in this case I was fortunate enough that it was not critical to  make this rebase continue. I just removed commits that caused conflicts and pulled rebase clear so I can't reproduce the git rebase continue issue at the moment. But it's second time I've encountered it so I know it's not one time thing. At work I can't afford to keep repository at failed state as I must submit commits.
Please find below veryfication status.

$ type git
git is hashed (/mingw64/bin/git)

$ git --exec-path
C:\usr\bin\git\mingw64/libexec/git-core

$ cd /c/usr/bin/git/mingw64/libexec/git-core

$ ls -al  git-rebase*
-rwxr-xr-x   1 marrhub 1049089   16288 Oct 12 23:24 git-rebase*
-rw-r--r--   1 marrhub 1049089    2525 Oct 12 23:24 git-rebase--am
-rwxr-xr-x 118 marrhub 1049089 2240152 Oct 12 23:24 git-rebase--helper.exe*
-rw-r--r--   1 marrhub 1049089   28708 Oct 12 23:24 git-rebase--interactive
-rw-r--r--   1 marrhub 1049089    3933 Oct 12 23:24 git-rebase--merge

So there is git-rebase executable as /bin/sh script. There is no Windows exe.

**Comment by gen-azarov** [comment]
The issue is reproduced on my machine also.  

$ git --version --build-options
git version 2.14.0.windows.2
built from commit: 0f3342804fc6fa558a7c9e220e7e9ab4c86e8226
sizeof-long: 4
machine: x86_64

git-rebase executable exists:
$ ls -al git-rebase*
-rwxr-xr-x   1 g.azarov 1049089   16288 Aug  7 12:07 git-rebase*
-rw-r--r--   1 g.azarov 1049089    2471 Aug  7 12:07 git-rebase--am
-rwxr-xr-x 118 g.azarov 1049089 2236560 Aug  7 12:07 git-rebase--helper.exe*
-rw-r--r--   1 g.azarov 1049089   28627 Aug  7 12:07 git-rebase--interactive
-rw-r--r--   1 g.azarov 1049089    3933 Aug  7 12:07 git-rebase--merge

@dscho Let us know your plans about this issue.

**Comment by PhilipOakley** [comment]
Can anyone make a [MCVE](https://stackoverflow.com/help/mcve) that creates a simple repo, sets config variables, starts the rebase, and then reliably fails, with instrumentation (as noted by dscho)?

**Comment by marrhub** [comment]
It seems the issue was encountered already on Aug 6 '16:
[https://stackoverflow.com/questions/38806713/git-rebase-fails-to-continue-by-printing-help-message](url)

**Comment by PhilipOakley** [comment]
Aside: a guess, maybe https://public-inbox.org/git/20171028000152.2760-1-jacob.e.keller@intel.com/ 'rebase: exec leaks GIT_DIR to environment' just might be relevant.

**Comment by marrhub** [comment]
I don't have Comodo installed and git doesn't spew random messages. Message is always the same - help message.
Actually it's getting worse. Now it has started spewing help message on git pull --rebase which renders Git for Windows unusable.
I've tried reinstalling Git for Windows with latest version to no avail. Currently installed Git for Windows:
$ git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4

I've created MVCE available at:

https://github.com/marrhub/issue-1346-mvce.git

Actually Cygwin version of git:

$ git --version --build-options
git version 2.15.1
sizeof-long: 8

demonstrates exactly same problem on this machine.

Below please find git pull --rebase command output with trace. Last operation before help message is displayed contains -h option which I assume is responsible for showing help message i.e:

16:13:12.023898 git.c:415 trace: built-in: git rev-parse --parseopt --stuck-long -- -h



$ GIT_TRACE=1 git pull --rebase

16:12:57.726468 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/bin
16:12:57.742470 git.c:415 trace: built-in: git pull --rebase
16:12:57.770473 run-command.c:637 trace: run_command: git merge-base --fork-point refs/remotes/origin/master master
16:12:58.261522 run-command.c:637 trace: run_command: git fetch --update-head-ok
16:12:58.482544 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:12:58.495545 git.c:415 trace: built-in: git fetch --update-head-ok
16:12:58.513547 run-command.c:637 trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/marrhub/issue-1346-mvce.git
16:12:58.750571 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:12:58.763572 git.c:654 trace: exec: git-remote-https origin https://github.com/marrhub/issue-1346-mvce.git
16:12:58.763572 run-command.c:637 trace: run_command: git-remote-https origin https://github.com/marrhub/issue-1346-mvce.git
16:12:59.001596 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:01.003796 run-command.c:637 trace: run_command: git rev-list --objects --stdin --not --all --quiet
16:13:01.501846 run-command.c:637 trace: run_command: git rev-list --objects --stdin --not --all --quiet
16:13:01.737869 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:01.752871 git.c:415 trace: built-in: git rev-list --objects --stdin --not --all --quiet
16:13:02.383934 run-command.c:1553 run_processes_parallel: preparing to run up to 1 tasks
16:13:02.383934 run-command.c:1585 run_processes_parallel: done
16:13:02.383934 run-command.c:637 trace: run_command: git gc --auto
16:13:02.622958 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:02.640960 git.c:415 trace: built-in: git gc --auto
16:13:03.045000 run-command.c:637 trace: run_command: git merge --ff-only FETCH_HEAD
16:13:03.277023 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:03.292025 git.c:415 trace: built-in: git merge --ff-only FETCH_HEAD
Already up to date.
16:13:03.513047 run-command.c:637 trace: run_command: git rebase --onto 691d95d764c15b6cf850cb4d2398d40c6add12b2 691d95d764c15b6cf850cb4d2398d40c6add12b2
16:13:03.750070 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:03.766072 git.c:654 trace: exec: git-rebase --onto 691d95d764c15b6cf850cb4d2398d40c6add12b2 691d95d764c15b6cf850cb4d2398d40c6add12b2
16:13:03.767072 run-command.c:637 trace: run_command: git-rebase --onto 691d95d764c15b6cf850cb4d2398d40c6add12b2 691d95d764c15b6cf850cb4d2398d40c6add12b2
16:13:04.365132 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:06.603356 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:06.608356 git.c:415 trace: built-in: git rev-parse --git-dir
16:13:07.248420 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:07.253421 git.c:415 trace: built-in: git rev-parse --git-path objects
16:13:07.765472 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:07.771473 git.c:415 trace: built-in: git rev-parse --is-bare-repository
16:13:08.303526 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:08.307526 git.c:415 trace: built-in: git rev-parse --show-toplevel
16:13:08.893585 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:08.905586 git.c:415 trace: built-in: git config --bool rebase.stat
16:13:09.484644 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:09.496645 git.c:415 trace: built-in: git config --bool rebase.autostash
16:13:10.035699 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:10.045700 git.c:415 trace: built-in: git config --bool rebase.autosquash
16:13:10.535749 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:10.545750 git.c:415 trace: built-in: git config --bool commit.gpgsign
16:13:11.342830 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:12.015897 exec-cmd.c:236 trace: resolved executable dir: C:/usr/bin/Git/mingw64/libexec/git-core
16:13:12.023898 git.c:415 trace: built-in: git rev-parse --parseopt --stuck-long -- -h
usage: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] [<upstream>] [<branch>]
or: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] --root [<branch>]
or: git rebase --continue | --abort | --skip | --edit-todo
Available options are
-v, --verbose display a diffstat of what changed upstream
-q, --quiet be quiet. implies --no-stat
--autostash automatically stash/stash pop before and after
--fork-point use 'merge-base --fork-point' to refine upstream
--onto ... rebase onto given branch instead of upstream
-r, --rebase-merges[=...]
try to rebase merges instead of skipping them
-p, --preserve-merges
try to recreate merges instead of ignoring them
-s, --strategy ... use the given merge strategy
--no-ff cherry-pick all commits, even if unchanged
-m, --merge use merging strategies to rebase
-i, --interactive let the user edit the list of commits to rebase
-x, --exec ... add exec lines after each commit of the editable list
-k, --keep-empty preserve empty commits during rebase
--allow-empty-message
allow rebasing commits with empty messages
-f, --force-rebase force rebase even if branch is up to date
-X, --strategy-option ...
pass the argument through to the merge strategy
--stat display a diffstat of what changed upstream
-n, --no-stat do not show diffstat of what changed upstream
--verify allow pre-rebase hook to run
--rerere-autoupdate allow rerere to update index with resolved conflicts
--root rebase all reachable commits up to the root(s)
--autosquash move commits that begin with squash!/fixup! under -i
--committer-date-is-author-date
passed to 'git am'
--ignore-date passed to 'git am'
--signoff passed to 'git am'
--whitespace ... passed to 'git apply'
--ignore-whitespace passed to 'git apply'
-C ... passed to 'git apply'
-S, --gpg-sign[=...] GPG-sign commits
Actions:
--continue continue
--abort abort and check out the original branch
--skip skip current patch and continue
--edit-todo edit the todo list during an interactive rebase
--quit abort but keep HEAD where it is
--show-current-patch show the patch file being applied or merged

**Comment by dscho** [comment]
> When `git rebase` spews out random usage messages, maybe the culprit is an over-eager Comodo software, as suggested in #1562.

That is probably still the issue.

The good news is that rebase has become a built-in command in Git, so no Unix shell is required anymore, and therefore those overzealous antimalware programs can go be overzealous and won't bother us anymore, at least when we're rebasing.
