### ISSUE TITLE
Git Bash Drag & Drop Option Not Available

### ISSUE THREAD

**Issue by edherroj** [git-for-windows/git#1347]
Hello. 

I used to drag and drop folders to the Git Bash command line in order to change the working directory or to create new repos on new projects. This option is very convenient becasuse you can just drop the folder instead of typing the complete path for a specific folder.

However this option is no longer available to me, and when I attempt to do it, my cursor turns into a lock symbol.

I installed Git 2.15.0 for Windows 10 64bit.

I appreciate any solution you can give. Thank you.

**Comment by dscho** [comment]
That Drag ' Drop still works for me...

Can you first make sure that when you right-click the window icon and then click `Options` and then the `About...` button, you see something like this?

![image](https://user-images.githubusercontent.com/127790/32370848-cf8d815c-c08e-11e7-94c5-9428a3fb7437.png)

Next, do you have any custom configuration of your MinTTY, such as `DropCommands`?

Please also note that this may very well be an [`MSYS2 issue`](https://github.com/Alexpux/MSYS2-packages/issues).

**Comment by edherroj** [comment]
I was informed that Git Bash or any other command line will disable this drag and drop option when using admin privileges.

Thanks for your time.

**Comment by PhilipOakley** [comment]
> I was informed that Git Bash or any other command line will disable this drag and drop option when using admin privileges.

@edherroj, Do you have a reference or web link for the information. It would be good to know who owned the decision to do the disabling.

Philip

**Comment by edherroj** [comment]
@PhilipOakley here is the reference I was given. They are actually talking about electron, not Git Bash, but in one of the answers the person explained why this happens. I did tried what they said and its true (in my case). As I understand it's caused by Windows and not the command line itself. Thanks.

https://github.com/electron/electron/issues/5243

**Comment by shiftkey** [comment]
@edherroj @PhilipOakley yeah, this is some classic Windows behaviour around the UI for an elevated process and blocking interactions from non-elevated processes (like Explorer).
