### ISSUE TITLE
Failures when build git with VS2017

### ISSUE THREAD

**Issue by PhoebeHui** [git-for-windows/git#1348]
Since issue https://github.com/git-for-windows/git/issues/1234 closed, I open this new one.
Build Git latest revision on master with 2017 still failed with the following errors:

fatal error C1083: Cannot open include file: 'openssl/ssl.h'
fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory

Since  the above errors emit from lots of projects, I include the file by passing extra flag: /ID:\Git\src\compat\vcbuild\GEN.PKGS\openssl.v140.windesktop.msvcstl.dyn.rt-dyn.x64.1.0.2.1\build\native\include /ID:\Git\src\compat\vcbuild\GEN.PKGS\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\include

 Then the above errors have gone, but it emit another links issue like this:
       "D:\Git\src\git.sln" (Rebuild target) (1) ->
       "D:\Git\src\git\git.vcxproj" (Rebuild target) (2) ->
         index-pack.obj : error LNK2001: unresolved external symbol _crc32 [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _inflateInit_ [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _deflateInit_ [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _inflateEnd [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _inflate [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _inflateInit2_ [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _deflateInit2_ [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _deflateBound [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _deflateEnd [D:\Git\src\git\git.vcxproj]
         libgit.lib(zlib.obj) : error LNK2001: unresolved external symbol _deflate [D:\Git\src\git\git.vcxproj]
         ..\git.exe : fatal error LNK1120: 10 unresolved externals [D:\Git\src\git\git.vcxproj]

Setup
•Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64-bit
 $ git --version --build-options
 git version 2.9.2.windows.1
 sizeof-long: 4
•Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 Windows Server 2016 64-bit + VS2017.2
 $ cmd.exe /c ver
 Microsoft Windows [Version 10.0.15063]

Repro steps:
1.git clone https://github.com/git-for-windows/git.git D:\git\src
2.git checkout vs/master
3.devenv /upgrade git.sln
4.nuget.exe restore git.sln
5.msbuild /m /p:Configuration=Release;Platform=x86 /p:WindowsTargetPlatformVersion=10.0.15063.0 /t:Rebuild git.sln

**Comment by dscho** [comment]
I am fairly certain that the previous way we initialized NuGet packages was not performed automatically with MSBuild, only when building in Visual Studio.

However, we completely revamped (in a *major* effort between @jeffhostetler and myself) the way the Visual Studio integration works, and now your recipe should succeed.

@PhoebeHui may I ask you to test it?

**Comment by PhoebeHui** [comment]
Thanks dscho, GIt is clean in our testing!
