### ISSUE TITLE
VSTS Authentication (PAT)

### ISSUE THREAD

**Issue by snodsix** [git-for-windows/git#1350]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Cloning a repository from VSTS
```
 - What did you expect to occur after running these commands?

Prompt for username and password or PAT.

 - What actually happened instead?

Window appeared prompting for username.  Upon entering username, password prompt appeared.  Typed 2 characters and that disappeared, sending me back to command prompt with this message:
C:\fred>git clone https://csaaig.visualstudio.com/_git/PartsUnlimitedMRP
Cloning into 'PartsUnlimitedMRP'...
Logon failed, use ctrl+c to cancel basic credential prompt.
Username for 'https://csaaig.visualstudio.com':

I can enter my username and PAT, at this point and it works, but it appears that authentication is not performing as expected.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
@snodsix I am closing this ticket because there has not been any feedback to @shiftkey's answer. Please do take this as encouragement to respond. I can easily reopen once this ticket becomes less dead.
