### ISSUE TITLE
Microsoft Windows Automatically closes the Git Bash Window

### ISSUE THREAD

**Issue by wcdeich4** [git-for-windows/git#1351]
After installing Git-2.15.0-64-bit.exe on Windows 8.1, and using the RT-Click "Git Bash Here" the Bash window always opens, then closes immediately.  I tried the "Use MinTTY (the default terminal of MSYS2)" and "Use Windows' default console window" but either way, when I try to pen the Git Bash Window, Microsoft Windows closes it immediately.  It appears one of the Microsoft Updates in the last several months is causing the problem.  (Maybe a Microsoft Update on September 17th?)  My friends with Windows 10 say they have the same problem. 

When I tried PortableGit-2.6.4-64-bit, git-cmd.exe worked,  but  git-bash.exe still did not work - so if the version of git-cmd.exe in PortableGit-2.6.4-64-bit does work, maybe that can be used as an example of how to find a way to avoid Microsoft Windows closing the Bash Window in general.

Sincerely, Will

**Comment by wcdeich4** [comment]
Update:  going directly to the installed C:\Program Files\Git\git-cmd.exe on my hard drive and running git-cmd.exe As Administrator also worked.  However, the RT-Click "Git Bash Here" and the "Git Bash" icon on the desktop did not work, even when I reinstalled Git and chose "Use Windows' default console window"

**Comment by dscho** [comment]
@wcdeich4 can you run [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) while trying to launch Git Bash? Hopefully that will give us some insight.

It would also be helpful to fill out at least some of the information asked in the issue reporting template, such as the exact Windows version.

**Comment by wcdeich4** [comment]
OK.  I'm using Windows 8.1 Pro, but there were some similar problems on Windows 10  

[Logfile.zip](https://github.com/git-for-windows/git/files/1458075/Logfile.zip)

**Comment by dscho** [comment]
@wcdeich4 did you find anything sticking out in the logs?

**Comment by ktr4z** [comment]
I also have the same problem on windows 10. Git-bash doesn't work but git-cmd does, even when reinstalling git or using PortableGit.

**Comment by dscho** [comment]
Coming from a different ticket that looks like it describes the same symptoms: do y'all have a `.minttyrc` in your home directory?

**Comment by wcdeich4** [comment]
I do not have a .minttyrc file

**Comment by dscho** [comment]
And a current Git for Windows does not fix things either? (v2.15.0 is kinda old.)

**Comment by Abdulmanahtalib** [comment]
Tq
