### ISSUE TITLE
The installer isn’t drawing checkboxes (Select Components screen and final screen)

### ISSUE THREAD

**Issue by chris-morgan** [git-for-windows/git#1353]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Windows 10.0.17025.1000, 64-bit, mixed-DPI environment (primary monitor 2×, two additional 1× displays).

Here’s what the Select Components screen of the installer looks like for me:

<img src=https://user-images.githubusercontent.com/392868/32585749-112b78e4-c553-11e7-8b9d-8b417e04e4c7.png width=499 height=371 alt="Screenshot of the Select Components screen of the installer, with no checkboxes rendered (nor yet any blank space left for them)">

No checkboxes. I determined that clicking on an item or pressing Space when one is selected toggles its selectedness, but there’s no checkbox drawn which makes life hard.

<img src=https://user-images.githubusercontent.com/392868/32585946-12f71204-c554-11e7-8e28-c9a1989c995d.png width=499 height=371 alt="Screenshot of the final screen of the installer, with no checkboxes rendered besides “Launch Git Bash” and “View Release Notes”">

No checkboxes there, either.

I had a 2.9.2 installer still handy, and it shows the same thing, but I expect I would have filed a bug about it if that had been the case when I first installed it, so I suspect it’s connected with changes in Windows. I’m on the latest Insider Preview build, but the Fall Creators Update is pretty recent, so it’s probably worth checking there.

**Comment by chris-morgan** [comment]
I believe this uses Inno Setup; I didn’t observe anything in the newsgroup or changelogs obviously about checkboxes not rendering, and the latest release was a year and a half ago.

**Comment by dscho** [comment]
> I was not able to find an open or closed issue matching what I'm seeing

I was :grin:

https://github.com/git-for-windows/git/issues/1342

**Comment by chris-morgan** [comment]
Ugh, my searches only got as generic as “installer checkbox”, and apparently GitHub either doesn’t do stemming or doesn’t do it properly (I expected it to stem). If I search for “installer checkbox*es*”, *then* I find it.
