### ISSUE TITLE
module.js:538     throw err;     ^

### ISSUE THREAD

**Issue by edherroj** [git-for-windows/git#1355]
I was not able to find an open/closed issue matching what I'm seeing.

### Setup ###

- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
**git version 2.15.0.windows.1
64-bit**

$ git --version --build-options
**git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64**

- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
**Windows 10 _ 64-bit**

$ cmd.exe /c ver
**Microsoft Windows [Versi▒n 10.0.15063]**

- What options did you set as part of the installation? Or did you choose the
   defaults?
**Defauts**

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"

$ cat /etc/install-options.txt
**Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled**

- Any other interesting things about your environment that might be related
   to the issue you're seeing?

**Error only occurs when using git bash for windows command line. Windows command line and Node command prompt work perfectly.**

### Details

- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Git Bash**

- What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

**$npm install gulp-cli -g
$ gulp --version**

 - What did you expect to occur after running these commands?

**Global installation of gulp went well. Expected to see the gulp version. Cannot run gulp watch or anything that has to do with gulp tool. Again, these commands work fine on Windows command line and Node command Prompt.**

- What actually happened instead?

```
module.js:538
    throw err;
    ^
Error: Cannot find module 'C:\c\Users\Eduardo's PC\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

- If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**N/A working locally**
![screenshot](https://user-images.githubusercontent.com/31143519/32637714-1169733c-c581-11e7-8709-14e51879e709.png)

**Comment by shiftkey** [comment]
You haven't specified which version of Node and NPM you have installed, which matters for reproducing the issue correctly.

```
Error: Cannot find module 'C:\c\Users\Eduardo's PC\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js'
```

Notice the beginning `C:\c\` path here - Node is trying to resolve an invalid file path.

**Comment by edherroj** [comment]
@shiftkey here you have. Thanks for your time. I really appreciate it.

node --version
v8.9.0
npm --version
5.51

**Comment by shiftkey** [comment]
@edherroj can you retest this on `8.9.1` of Node? I can't reproduce it here on the same version and build of Windows 10:

```
shiftkey@BRENDANFORSB1B7 MINGW64 ~
$ node --version
v8.9.1

shiftkey@BRENDANFORSB1B7 MINGW64 ~
$ git --version
git version 2.15.0.windows.1

shiftkey@BRENDANFORSB1B7 MINGW64 ~
$ npm --version
5.5.1

shiftkey@BRENDANFORSB1B7 MINGW64 ~
$ npm install -g  gulp-cli
C:\Users\shiftkey\AppData\Roaming\npm\gulp -> C:\Users\shiftkey\AppData\Roaming\                                            npm\node_modules\gulp-cli\bin\gulp.js
+ gulp-cli@1.4.0
added 139 packages in 6.734s

shiftkey@BRENDANFORSB1B7 MINGW64 ~
$ gulp --version
[12:31:15] CLI version 1.4.0
```

**Comment by edherroj** [comment]
So, I updated to node v8.9.1 and I'm still getting the same error.

```
Eduardo's PC@LAPTOP-7MVVJUG0 MINGW64 ~
$ node --version
v8.9.1

Eduardo's PC@LAPTOP-7MVVJUG0 MINGW64 ~
$ git --version
git version 2.15.0.windows.1

Eduardo's PC@LAPTOP-7MVVJUG0 MINGW64 ~
$ npm --version
5.5.1

Eduardo's PC@LAPTOP-7MVVJUG0 MINGW64 ~
$ npm install -g gulp-cli
C:\Users\Eduardo's PC\AppData\Roaming\npm\gulp -> C:\Users\Eduardo's PC\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js
+ gulp-cli@1.4.0
updated 1 package in 5.016s

Eduardo's PC@LAPTOP-7MVVJUG0 MINGW64 ~
$ gulp --version
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\c\Users\Eduardo's PC\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```


You mentioned that the file path node is looking at is invalid. Is there a way to correct it?

Thanks again!

**Comment by dscho** [comment]
Does `gulp` not need  a Win32 console? I.e. either run it from CMD, or prefix the command with `winpty` (as mentioned in the [release notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues))?

**Comment by shiftkey** [comment]
@dscho @edherroj it's working fine from Git Bash on my side 🤷‍♂️

**Comment by edherroj** [comment]
Thank you for following up. I'll continue troubleshooting this.

**Comment by edherroj** [comment]
I read that there is a possible solution to this problem but to be honest I don't understand how to do it.

[https://stackoverflow.com/questions/24027551/gulp-command-not-found-error-after-installing-gulp](url)

I've been trying to follow up but I get lost. Does anyone know where to find a more understandable troubleshooting steps?

Thanks all!

**Comment by dscho** [comment]
I *think* this is a problem with the apostrophe in the name of your home directory. MSYS2's automagic conversion from pseudo-POSIX to Windows paths skips conversion when it detects quotes (and the apostrophe is mistaken for a single quote).

You *might* be able to work around this by setting your environment variable `APPDATA`, e.g.

```sh
export APPDATA=$(cygpath -sm "$APPDATA")
```

**Comment by edherroj** [comment]
@dscho I tried that and did not work. Do you know a website I can check to get support on this problem. Or maybe chat room I can check? Thank you.

**Comment by dscho** [comment]
> Do you know a website I can check to get support on this problem.

Afraid not :smiley:
