### ISSUE TITLE
`GIT_CONFIG` is ignored in all cases other than `git config --list`

### ISSUE THREAD

**Issue by erichiller** [git-for-windows/git#1358]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.15.0 (but prior versions  exhibited the same behavior)

```
$ git --version --build-options
git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
10.0.15063.674
x64, Pro

```
Powershell: 10.0.15063.674

$ cmd.exe /c ver

`Microsoft Windows [Version 10.0.15063]`

 - What options did you set as part of the installation? Or did you choose the
   defaults?

**Response:** Defaults, no installation, running using `Git-2.15.0-64-bit.tar.gz` expanded into a directory with 
`C:\Users\ehiller\AppData\Local\omega\system\git\bin` on my path. I've also tried
`C:\Users\ehiller\AppData\Local\omega\system\git\cmd`, same symptom.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**Response:** I will detail all below

### Details

 - Which terminal/shell are you running Git from?

**Response:** I typically run Git within Powershell within ConEmu. For all tests I ran it within Windows native Powershell and also in `cmd.exe`

 - What commands did you run to trigger this issue?

**Response & Actual Bug Report**   
**Experiment Outline**  
 As System variables I had  `GIT_CONFIG` set solo to `C:\Users\ehiller\AppData\Local\omega\config\omega.gitconfig` and later tried with `GIT_CONFIG_NOSYSTEM` set to `True` and to `1` neither had any effect. I've been testing whether or not my config is truly "being utilized" by checking if a simple coloration setting is being applied (see test config below):

**Test Config**
```
[color]
	ui = true

[color "status"]
    changed   = magenta
    # or cyan in ~/.gitconfig
```
**magenta** is set in the `GIT_CONFIG` config, and **cyan** is set in `~/.gitconfig`

With `GIT_CONFIG` pointed to a file and nothing in my `~\.gitconfig`, I will have the default appearance when executing `git status` yet `git config --list --includes --show-origin` will run and display results as if my `GIT_CONFIG` is being read as the only config I have (see output below). If I specify settings in `~\.gitconfig` then my settings are applied from `~\.gitconfig` when running `git status` (the modified color is cyan`,  **HOWEVER** even though `git status` will output as though its config is from `~\.gitconfig`, if I run

```
git config --list --includes --show-origin
```

I will receive:

```
file:"C:\\Users\\ehiller\\AppData\\Local\\omega\\config\\omega.gitconfig"       color.ui=true
file:"C:\\Users\\ehiller\\AppData\\Local\\omega\\config\\omega.gitconfig"       color.status.changed=magenta
```

So to sum:

`GIT_CONFIG`   |   `~\.gitconfig`    |  `git status` output | `git config` output
--- | --- | --- | ---
magenta | cyan | cyan | magenta
magenta | non-existing | red (default git) | magenta

**_Note_**: I did not discover this originally because of color, that was simply an effective test. I discovered this because my line ending settings were being ignored. So if a question you may have posed was _"Does this extend beyond coloring?"_ the answer is yes.

Any further information, please let me know!

**Response:** above

 - What did you expect to occur after running these commands?

**Response:** I expected git to read `GIT_CONFIG` as my configuration file for all activities.

 - What actually happened instead?

**Response:** `GIT_CONFIG` is ignored for all activities EXCEPT `git config`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Response:** this is for any repo

**Comment by dscho** [comment]
Please note that the `GIT_CONFIG` variable is documented only in [the help page for `git config`](https://git-scm.com/docs/git-config), i.e. its designed behavior is to really only override which file `git config` reads/writes.

In other words, what you describe is the designed behavior.

If you do not like that behavior, please send a (non-HTML) mail to [the Git mailing list](mailto:git@vger.kernel.org), as this is not a Windows-specific design.
