### ISSUE TITLE
npm install is not working with git for windows

### ISSUE THREAD

**Issue by qualityking** [git-for-windows/git#1359]
npm install is not working from git bash from windows where it is working with windows command prompt 

### Setup

 - latest 64 bit 2.15
```
$ git --version --build-options
git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64

** insert your machine's response here **
``` using command npm install -g @angular/cli
its just keep on waiting and not moving ahead

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> ** insert your machine's response here **



> ** insert your response here **



> ** insert your response here **



> ** insert your commands here **



> ** insert here **



> ** insert here **



> ** insert URL here **

** insert a suggestion that the `winpty` hint in the [known issues](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues) may help **

**Comment by dscho** [comment]
** insert any variation of some creative snark here **
