### ISSUE TITLE
Commit cannot open vim after vim is interrupted with Ctrl-Z

### ISSUE THREAD

**Issue by HiddenTesla** [git-for-windows/git#1360]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.3.windows.1 
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not yet

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
git bash
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Set vim as the editor in ~/.gitconfig
$ git commit
Ctrl-Z to suspend the editor
(Commit again)
$ git commit
```
 - What did you expect to occur after running these commands?

Open the editor 'vim' as usual

 - What actually happened instead?

Error says:
```
E325: ATTENTIONerror: There was a problem with the editor 'vim'.
                                                                Please supply the message using either -m or -F option.
```
And then the terminal is garbled. Cannot see input from keyboard, and the output cannot correctly display the carriage return. The scroll bar is missing. If you resize the terminal, all characters will be gone.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

```
My local repository on my computer
```

I have googled this problem, with keyword
```
There was a problem with the editor 'vim'
```
but not found a solution. 
Suggestions such as set editor ti full path vim does not work.
vim itself works fine.
git commit with vim also works in other repos.

I guess something is wrong in the .git folder.

Is there any way to come back to normal? Other than deleting this repo and re-clone.

**Comment by HiddenTesla** [comment]
Sorry I know this is due to my own operation and not a flaw of git. But nowhere can I find a forum, nor can I find a solution.

**Comment by dscho** [comment]
When I use `vim` (which requires no special configuration, by the way, it is the default), I can suspend with Ctrl+Z only when working in MinTTY (and it works, a `fg` will get `vim` into the foreground again). In CMD, it is not supported, Ctrl+Z does not do anything.

I suspect that you are talking about a different `vim`, though.

**Comment by HiddenTesla** [comment]
@dscho 
I am just using `vim` that comes with the `git`.
By the way the repo is pretty big. Tracked files are about 6GB. Nearly 14GB if fully built.

Anyway thank you for attention.

**Comment by dscho** [comment]
I simply cannot reproduce. Maybe you can provide more detailed a recipe to verify that this is indeed a reproducible problem (if it is not reproducible, there is little we can do to solve it).

**Comment by HiddenTesla** [comment]
@dscho 
No problem.The repository was really big (over 13GB after build), and the computer had been running for days.
Maybe something happened to go wrong, and it was just an occasional malfunction.
If not reproducible, can we close this ticket, or follow up?

**Comment by dscho** [comment]
@HiddenTesla can *you* reproduce? If so, can *you* reproduce with a smaller repo? Please perform this diligence.

**Comment by dscho** [comment]
Closing until we have a reproducer (MCVE).

**Comment by bartsblues** [comment]
I had the same issue. I was rebasing and during a commit amend I hit `ctrl + z`. From then on out vim would crash with the same error listed above. The solution was to remove all `.swp` files from `./.git/`. That is, `rm -vf .git/*.swp`

**Comment by dscho** [comment]
@bartsblue can *you* find a reliable way to reproduce the issue? If so, please describe it in detail.

**Comment by bartsblues** [comment]
@dscho here you go:

1. Open a Git Bash terminal
2. Create a test directory:
`$ mkdir test`
3. Initialize a git repo:
`$ cd test && git init`
4. Create a text file:
`$ echo 'This is a test' >> test.txt`
5. Stage and commit the file:
`$ git add text.txt && git commit -m 'initial commit'`
6. Add another line and commit:
`$ echo 'Another line' >> test.txt && git commit -am 'another commit'`
7. Add one more line and commit:
`$ echo 'One more line' >> test.txt && git commit -am 'one more commit'`
8. Perform an interactive rebase:
`$ git rebase -i HEAD~2 HEAD`
9. When Vim opens, squash the newest commit and edit the oldest:
> edit c19e1fe another commit
> squash 160c957 one more commit
10. Save and exit Vim normally
`:wq`
11. When rebasing pauses to edit the commit, type:
`git commit --amend`
12. When Vim opens, hit `ctrl+z` to stop the process
13. Attempt to edit the commit again
`git commit --amend`

You should hit the error at this point. An additional problem is that characters are no longer echoed as you type. You can `git rebase --abort` to stop rebasing.

**Comment by HiddenTesla** [comment]
@bartsblues 
Thank you. I can reproduce it following your steps.

**Comment by dscho** [comment]
/remind me to look at this next week (after GitMerge)

**Comment by dscho** [comment]
> ```
> 11. When rebasing pauses to edit the commit, type:
> git commit --amend
> 12. When Vim opens, hit ctrl+z to stop the process
> 13. Attempt to edit the commit again
> git commit --amend

@bartsblues are you sure that you intended to keep the first commit in limbo by *not* finishing to edit the commit message (`fg` to get `vim` into the foreground again)?

**Comment by bartsblues** [comment]
No, I didn't. I'm sure using `fg` would have solved the issue.

**Comment by thebia** [comment]
In my installation vim regularly crashes and I don't even do anything special. It hardly ever works.

- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
![image](https://user-images.githubusercontent.com/25981281/44086857-456d67d4-9fbe-11e8-95ca-29ed83d0d0a9.png)
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
![image](https://user-images.githubusercontent.com/25981281/44086918-6ab6cdaa-9fbe-11e8-89a3-cde5647aef9a.png)
- What options did you set as part of the installation? Or did you choose the
defaults?
![image](https://user-images.githubusercontent.com/25981281/44087015-b77488e4-9fbe-11e8-9a57-c91824a9875b.png)
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
git bash with underlying cmd (not mintty because with that I couldn't Ctrl+C any processes)

I ran _git commit --amend_ but it also regularly happens with plain _git commit_. This is the error message:
![image](https://user-images.githubusercontent.com/25981281/44087073-e3987a52-9fbe-11e8-833f-ad0ad8994f59.png)
And this is the stackdump mentioned:
[vim.exe.stackdump.txt](https://github.com/git-for-windows/git/files/2286557/vim.exe.stackdump.txt)

**Comment by dscho** [comment]
Closing stale ticket.
