### ISSUE TITLE
Problems resolving GIT_EDITOR in paths with spaces

### ISSUE THREAD

**Issue by tmssngr** [git-for-windows/git#1361]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

none
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Just unpacked the portable 7z-bundle to a path with spaces, here "C:\Git Windows"

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Plain cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
@REM we now create a tiny script in a path with spaces, the content does not
@REM matter but should do no harm
mkdir "path with space"
echo echo 'hello' > "path with space\editor.cmd"
@REM ... set GIT_EDITOR without spaces
set GIT_EDITOR=editor.cmd
@REM but instead add the script directory to PATH
set PATH=%PATH%;%CD%\path with space

@REM we check that it still works
call editor.cmd

@REM Now create a repository
mkdir "repository with space"
git init "%CD%\repository with space"
cd "repository with space"

@REM add a single revision so it is easier to work with this repository
git commit --allow-empty -m "initial, empty commit"

@REM and add two files in two commits
echo file 1 > file1.txt
git add -- file1.txt
git commit -m "added file1.txt"

echo file 2 > file2.txt
git add -- file2.txt
git commit -m "added file2.txt"

@REM Now try to start the interactive rebase
git rebase --interactive HEAD~2
```
 - What did you expect to occur after running these commands?

The configured GIT_EDITOR should have been invoked

 - What actually happened instead?
```
C:\temp\a\repository with space>git rebase --interactive HEAD~2
'C:\temp\a\path' is not recognized as an internal or external command,
operable program or batch file.
Could not execute editor
```

**Comment by fourpastmidnight** [comment]
I think the problem is where you set `PATH`. When you add the path with spaces, you're not quoting it, so it's not being set correctly. Try this:

```
set PATH=%PATH%;"%CD%\path with space"
```

When you add your repository directory to the `PATH`, you should also enclose the path with double-quotes since it contains supposed, too.

**Comment by tmssngr** [comment]
Windows has no problems without the quotes and, adding the quotes to my test script does not make any difference. The error remains the same.

**Comment by tmssngr** [comment]
I think, the problem is reproducible on OS X, too:

```
export PATH=$PATH:/Applications/SmartGit\ 17.1.app/Contents/Resources/git/bin
which git

mkdir path\ with\ space
echo echo hello > path\ with\ space/editor.sh
chmod u+x path\ with\ space/editor.sh
export GIT_EDITOR=editor.sh

export PATH=$PATH:$CWD/path\ with\ space

mkdir repository\ with\ space
git init repository\ with\ space
cd repository\ with\ space

git commit --allow-empty -m "initial, empty commit"

touch file1.txt
git add -- file1.txt
git commit -m "added file1.txt"

touch file2.txt
git add -- file2.txt
git commit -m "added file2.txt"

git rebase --interactive HEAD~2
```

**Comment by dscho** [comment]
Could you also set `GIT_TRACE=1`?

**Comment by tmssngr** [comment]
Sure. Here is the output for the "git rebase --interactive HEAD~2":

```
14:08:58.830263 git.c:576               trace: exec: 'git-rebase' '--interactive' 'HEAD~2'
14:08:58.830763 run-command.c:626       trace: run_command: 'git-rebase' '--interactive' 'HEAD~2'
14:08:58.904657 git.c:344               trace: built-in: git 'rev-parse' '--parseopt' '--stuck-long' '--' '--interactive' 'HEAD~2'
14:08:58.953806 git.c:344               trace: built-in: git 'rev-parse' '--git-dir'
14:08:58.985192 git.c:344               trace: built-in: git 'rev-parse' '--git-path' 'objects'
14:08:59.005525 git.c:344               trace: built-in: git 'rev-parse' '--is-bare-repository'
14:08:59.025467 git.c:344               trace: built-in: git 'rev-parse' '--show-toplevel'
14:08:59.051414 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.stat'
14:08:59.078761 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autostash'
14:08:59.099746 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autosquash'
14:08:59.119916 git.c:344               trace: built-in: git 'config' '--bool' 'commit.gpgsign'
14:08:59.144988 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD~2^0'
14:08:59.173382 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD~2^0'
14:08:59.196318 git.c:344               trace: built-in: git 'symbolic-ref' '-q' 'HEAD'
14:08:59.226994 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
14:08:59.252427 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
14:08:59.273442 git.c:344               trace: built-in: git 'update-index' '-q' '--ignore-submodules' '--refresh'
14:08:59.298903 git.c:344               trace: built-in: git 'diff-files' '--quiet' '--ignore-submodules'
14:08:59.319939 git.c:344               trace: built-in: git 'diff-index' '--cached' '--quiet' '--ignore-submodules' 'HEAD' '--'
14:08:59.341337 git.c:344               trace: built-in: git 'merge-base' 'bf7991b27b72acb8c3cdac7a794fa8f0956a38a8' '75b6e60ca1f5f70b01bbefbedb5aa0b99837950d'
14:08:59.362035 git.c:344               trace: built-in: git 'rev-parse' '--git-path' 'hooks/pre-rebase'
14:08:59.424371 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
14:08:59.466309 git.c:344               trace: built-in: git 'rev-parse' '--short' '75b6e60ca1f5f70b01bbefbedb5aa0b99837950d'
14:08:59.492415 git.c:344               trace: built-in: git 'rev-parse' '--short' 'bf7991b27b72acb8c3cdac7a794fa8f0956a38a8'
14:08:59.519188 git.c:344               trace: built-in: git 'rev-parse' '--short' 'bf7991b27b72acb8c3cdac7a794fa8f0956a38a8'
14:08:59.542026 git.c:344               trace: built-in: git 'rebase--helper' '--make-script' 'bf7991b27b72acb8c3cdac7a794fa8f0956a38a8...75b6e60ca1f5f70b01bbefbedb5aa0b99837950d'
14:08:59.564942 git.c:344               trace: built-in: git 'rebase--helper' '--rearrange-squash'
14:08:59.589959 git.c:344               trace: built-in: git 'stripspace' '--strip-comments'
14:08:59.638729 git.c:576               trace: exec: 'git-sh-i18n--envsubst' '--variables' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
14:08:59.639730 run-command.c:626       trace: run_command: 'git-sh-i18n--envsubst' '--variables' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
14:08:59.670262 git.c:576               trace: exec: 'git-sh-i18n--envsubst' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
14:08:59.670262 run-command.c:626       trace: run_command: 'git-sh-i18n--envsubst' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
14:08:59.720982 git.c:344               trace: built-in: git 'stripspace' '--comment-lines'
14:08:59.752959 git.c:344               trace: built-in: git 'config' '--get' 'rebase.missingCommitsCheck'
14:08:59.794181 git.c:344               trace: built-in: git 'stripspace' '--comment-lines'
14:08:59.819177 git.c:344               trace: built-in: git 'stripspace' '--comment-lines'
14:08:59.855974 git.c:344               trace: built-in: git 'stripspace' '--strip-comments'
Nothing to do
```

**Comment by dscho** [comment]
> export PATH=$PATH:$CWD/path\ with\ space

I think this one is the actual problem: I have to use `$PWD` instead of `$CWD`.

**Comment by dscho** [comment]
As to the originally-reported issue: I can give you a *substantially-reduced* minimal example, one that does not even involve Git, but MSYS2 (which is used to evaluate Git's Unix shell scripts):

```cmd
mkdir "path with space"
echo echo 'hello' > "path with space\editor.cmd"
set PATH=%PATH%;%CD%\path with space

editor.cmd 'a b'
```

The problem would appear to be the single quotes around a parameter with spaces. And I am fairly certain that the problem is actually a bug in the MSYS2 runtime (you could try to report it [here](https://github.com/Alexpux/Cygwin/issues), but the MSYS2 maintainer is notoriously short on time...).

**Comment by dscho** [comment]
BTW the common work-around would be to use a Unix shell script instead. I know, it is not beautiful, but it works. And it is actually not slower because Git uses Bash to evaluate `git-rebase--interactive` *anyway*.

**Comment by tmssngr** [comment]
This problem occurs when launching Git from within SmartGit. I just created a reproducible test-case without SmartGit. From SmartGit we directly invoke the git executable and are able to set some environment variables. Launching a Bash instead would be no option.

**Comment by dscho** [comment]
@tmssngr I hope you have some time available to spend on this issue, then.

# First step:

Build the MSYS2 runtime. It is not *altogether* straight-forward, and it comes up often enough that I wrote up a detailed description how to get that done:

https://github.com/git-for-windows/git/wiki/Building-msys2-runtime

# Next step: find out where the faulty command-line is constructed

Typically, the easiest way to get closer to anything in the MSYS2 runtime is to use `strace.exe`. I usually launch this from a plain `cmd.exe`, in a freshly unpacked Portable Git (to be able to overwrite the `msys-2.0.dll` easily and not affect my SDK).

So: simply call:

```cmd
set MSYSTEM=MINGW64
set PATH=... (to include the `.cmd`)
usr\bin\strace.exe -o strace.out usr\bin\bash.exe -l -c "editor.cmd 'a 'b"
```

The generated file `strace.out` should have some information also about the command-line that was constructed to spawn `editor.cmd`.

If that does not lead you anywhere, you will want to read closely the code in `/usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime/winsup/cygwin/spawn.cc` (this path really only exists after you have built the MSYS2 runtime, read: the first step above was not suggested lightly).

# Step 3: try to change the code to fix the command-line

Once you found candidates in the code that may be responsible for the current behavior, you can start playing with possible solutions.

To resolve similar cases in the past, I have kept an editor open in one SDK Git Bash, then had a second MSYS2 window to run the build (as described here: https://github.com/git-for-windows/git/wiki/Building-msys2-runtime#rebuild-the-msys2-runtime), and immediately copied the generated `msys0.dll` over the portable Git's `msys-2.0.dll`. Then, I would run my test in the `cmd.exe` window.

I hope that this will help you not only pinpoint the problem, but even to come up with a patch to fix it.

**Comment by tmssngr** [comment]
Sorry, I don't have the weeks available to learn compiling/debugging/fixing C applications. I'm just a Java developer, no C guru like you.

**Comment by dscho** [comment]
I also was just a Java developer myself. That was no reason for me to stop learning 😃
