### ISSUE TITLE
Enhancement: skip gitweb from Git for Windows

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#1362]
Git for Windows is intended to be used by end users. GitWeb, however, wants to be used in conjunction with a web server such as Apache, and even requires a Perl module to be installed in that web server.

It is almost guaranteed that nobody uses Git for Windows that way, so let's just exclude those files from the installer.

# How to get started with this?

As always, install a [Git for Windows SDK](https://git-for-windows.github.io/#download-sdk).

This will take a while, so please plan ahead and do something else while it is installing the SDK (it will download something like 200+ megabytes and unpack everything into a neat directory structure).

It will open a Git SDK Bash, and leave it open for you to use. The same Git SDK Bash is also installed as a Desktop shortcut automatically.

# Build a portable Git (to verify that you can)

The idea of building a portable Git (as opposed to a Git for Windows installer) is that you will want to compare the output with and without your new patches. But the installer allows only one installation, not side-by-side installations. The portable Git, however, does allow that.

In the Git SDK Bash, switch the current working directory to `/usr/src/build-extra`. This is the worktree of the repository that has all the scripts to orchestrate the release engineering, including how to build an installer.

Run `./portable/release.sh 0-test`. This will create a new portable Git "installer" in your home directory, called `PortableGit-0-test-64-bit.7z.exe` (or `...-32-bit...` if you do this with a 32-bit Git for Windows SDK).

The portable Git installer is actually a self-extracting 7-Zip archive that simply runs one very simple `.bat` script to initialize certain files and directories required by the MSYS2 system Git uses to execute Unix shell scripts.

You can execute this file and choose a location where Git should be extracted. Let's do this right away, and perform a brief test to verify that it worked: simply execute `git-bash.exe` in the extracted top-level directory.

# Exclude the gitweb files

## Identify the files

First of all, let's identify the gitweb files. To that end, we use the fact that the Git for Windows SDK is actually a slightly modified [MSYS2](https://msys2.github.io/) setup, with a proper package management system called "Pacman". This allows us to "install" software into the SDK (which internally simply means that an archive is unpacked, and for some packages a simple shell script is executed afterwards).

Git itself is maintained as one of those Pacman packages, called `mingw-w64-x86_64-git` package (or if you are using a 32-bit SDK, `mingw-w64-i686-git`).

In the Git for Windows SDK, you can see the list of files included in this package using the following command:

```sh
pacman -Ql mingw-w64-x86_64-git | less
```

(`| less` simply means that the output of the `pacman` command is not printed directly, but fed to the program "less" which lets you scroll forwards and backwards, and most importantly: search).

To find the files related to gitweb, let's use `less`' search capabilities. First of all, switch off case-sensitivity, just in case, by pressing <kbd>-</kbd><kbd>i</kbd><kbd>Enter</kbd>. Then, press the forward slash key (<kbd>/</kbd>), then type in `gitweb` and then press <kbd>Enter</kbd>. This will skip to the first line containing that string and highlight it. To get to the next matching line, hit <kbd>n</kbd>. To jump back to the previous match, hit <kbd>Shift</kbd>+<kbd>n</kbd>.

## Actually exclude the files

The script that is used by `./portable/release.sh` to generate the list of files to include in the 7-Zip archive is called `make-file-list.sh`, and lives directly in `/usr/src/build-extra/`.

This `make-file-list.sh` script already contains tons of exclusions , e.g. the plain `.txt` versions of the help pages, or `git-cvsserver`.

We will have to imitate, say, `git-cvsserver`'s exclusions to also exclude the gitweb files.

Instead of excluding them one by one (which would add a huge list to the `make-file-list.sh` script), we should use a pattern. The way `make-file-list.sh` excludes files is to use `grep`, and this program allows specifying patterns as *regular expressions*. No need to worry, though, we will use only very rudimentary regular expressions of the form `^/mingw../.*/gitweb/`, where the `^` anchors the pattern to the start of the line, a single `.` means *any* character, and `.*` means *any number* of *any characters* (i.e. a variable-length string of pretty much anything).

This pattern, `^/mingw../.*/gitweb/` should already catch most of the gitweb files identified in the previous step, you probably have to add one or more patterns to catch them all.

Now, simply copy-edit the line that excludes the `git-cvsserver` script, once for every pattern.

# Test the new portable Git

Simply generate a new portable Git, say, by executing `./portable/release.sh 1-test`, and run it to extract a new portable Git.

Now, verify first of all that `git-bash.exe` of that new portable still runs fine.

After that, compare the files in the two portable Gits that you generated, by any directory tree comparer you like. If you like bare-bones command-line, you could do this, for example:

```sh
find /path/to/first/portable/git >with-gitweb.txt
find/path/to/second/portable/git >without-gitweb.txt
git diff --no-index with-gitweb.txt without-gitweb.txt
```

# Wrap your work in a neat Pull Request

Once you verified that it all works as extended, and that the correct files are excluded,

1. commit your work in `/usr/src/build-extra`. (Please do not forget to [sign off](https://github.com/git-for-windows/git/blob/v2.15.0.windows.1/Documentation/SubmittingPatches#L254-L306) on your work, and also please spend a few minutes to write a nice commit message explaining the rationale, probably just copy-editing the first paragraph(s) of this ticket.)
2. Then, create a fork of https://github.com/git-for-windows/build-extra (unless you already have one).
3. Push your commits to your fork.
4. Direct your browser to https://github.com/git-for-windows/build-extra; after a couple of seconds, it should offer you to open a new Pull Request from the just-pushed branch.

**Comment by Hk1020** [comment]
Brilliant. How do I get it now? I do want it!!!

**Comment by PhilipOakley** [comment]
@Hk1020 this was the removal of gitweb from Git for Windows.... 

If you want the 'web server such as Apache', you'll need a Linux box for that, or a bit of searching with your favourite engine for other alternates...

**Comment by garu57** [comment]
I'm just curious who told you that

> It is almost guaranteed that nobody uses Git for Windows that way...

and 

> If you want the 'web server such as Apache', you'll need a Linux box for that...

It's been years now that i've been using apache for windows from [Apache Lounge ](https://www.apachelounge.com/) and gitweb from git for windows to connect git repos to [Mantisbt ](http://www.mantisbt.org/) on windows machines.

Now i need to recover gitweb from github repo and rebuild the whole env by hands. Thanks...

And you even called this an **enhancement!!!**

**Comment by Hk1020** [comment]
> 
> 
> I'm just curious who told you that
> 
> > It is almost guaranteed that nobody uses Git for Windows that way...
> 
I am sure there is a study somewhere...
> and
> 
> > If you want the 'web server such as Apache', you'll need a Linux box for that...
> 
> It's been years now that i've been using apache for windows from [Apache Lounge ](https://www.apachelounge.com/) and gitweb from git for windows to connect git repos to [Mantisbt ](http://www.mantisbt.org/) on windows machines.
> 
So have I (except for the Mantis bit). Need to replace the machine with something recent and now this. 
> Now i need to recover gitweb from github repo and rebuild the whole env by hands. Thanks...
> 
So what is the current way to set up a git repo server **on Windows**? With git-for-windows I am stuck at 2.18.0 obviously.

**Comment by garu57** [comment]
Foutunately building gitweb do not require C or C++ compilations, that on windows could become a nightmare to setup, so with some manual work it can be done.
It's a quick and dirty solution but for private/internal usage (no security) it works.

- copy [make](https://sourceforge.net/projects/ezwinports/files/make-4.2.1-without-guile-w32-bin.zip/download) into `<GIT_INSTALL_DIR>\mingw64`
- download [git-for-windows](https://github.com/git-for-windows/git) repo and unpack it
- `cd` into unpacked `git\gitweb` and launch `<GIT_INSTALL_DIR>\mingw64\bin\make`, this will build `gitweb.cgi` and `static\gitweb.js`
- copy `gitweb.cgi`, `static\gitweb.js` and the rest of the files into `static`, but the directory `js`, toghether with your `gitweb.conf` into a new directory
- make directory `%GIT_INSTALL_DIR%\usr\share\perl5\site_perl`
- download [CGI](https://cpan.metacpan.org/authors/id/L/LE/LEEJO/CGI-4.40.tar.gz) and copy `lib` content into above directory
- reconfigure your virtualhost adding the new `gitweb.cgi` location, enable it for CGI execution and there you go

If you installed git with the exe installer, you can safely continue to update it in place, since the installer does not touch anything added manually to git installation (in our case `make` and `site_perl`) and forget about gitweb until git will introduce some changes that need a new gitweb build or a new CGI version.

**Comment by PhilipOakley** [comment]
@garu57 Thank you for the concise instruction for folks to follow. It provides a route for those wanting gitweb to use.

**Comment by dscho** [comment]
> I'm just curious who told you that

There were no bug reports on the bug tracker, despite the occasional one floating by on the Git mailing list, so I was pretty certain that the absolute number of gitweb users on Git for Windows must surely be smaller than 12. 😄 


> building gitweb do not require C or C++ compilations

You could even just extract it yourself, from the Pacman package, e.g. download https://wingit.blob.core.windows.net/x86-64/mingw-w64-x86_64-git-2.20.1.1.7c9fbc07db-1-any.pkg.tar.xz and extract `mingw64/share/gitweb/` from it. That should be quite a bit easier than building it.

**Comment by Hk1020** [comment]
> 
> 
> > I'm just curious who told you that
> 
> There were no bug reports on the bug tracker, despite the occasional one floating by on the Git mailing list, so I was pretty certain that the absolute number of gitweb users on Git for Windows must surely be smaller than 12. 😄
The other 10 didn't speak up yet.
> 
> > building gitweb do not require C or C++ compilations
> 
> You could even just extract it yourself, from the Pacman package, e.g. download https://wingit.blob.core.windows.net/x86-64/mingw-w64-x86_64-git-2.20.1.1.7c9fbc07db-1-any.pkg.tar.xz and extract `mingw64/share/gitweb/` from it. That should be quite a bit easier than building it.

Thanks, it certainly is. I've just spend a day to get gitweb to work. The major problem was to get perl to speak to Apache httpd. I could not make perl from Git-2.18.0 or newer work with Apache, neither in 64bit or 32bit versions. A simple perl script that just prints the environment created an endless loop in perl. The perl process would take up all CPU until Apache eventually kills it. 

I tried to replace git-for-windows' perl with ActiveState perl. With it perl cgi-scripts work fine but gitweb doesn't. gitweb requires getpwuid and possibly more which is unavailable in ActiveState perl.

So I ended up to install Git-1.8.3-preview20130601 which works fine with Apache. Only problem were libiconv{,-}2.dll which had to be copied to libexec/git-core in order to get git-httpd-backend to work.

**Comment by dscho** [comment]
> The other 10 didn't speak up yet I guess.

And they also did not do anything to get what they wish for...
