### ISSUE TITLE
git update: No feedback/error message when server can not be reached (because of proxy)

### ISSUE THREAD

**Issue by versat** [git-for-windows/git#1363]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Internet access is only possible via proxy.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git update
```
 - What did you expect to occur after running these commands?

Print any information whether the update command was able to connect to the server or not and if there is an update. In my case (no http.proxy set) it could print that the server cannot be reached.

 - What actually happened instead?

Nothing was printed at all.
After a few seconds the command finished and the command line was shown again.
I was not sure if there is just no update or if there is an issue with the proxy settings or if the command works at all.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Repository does not matter.

**Comment by dscho** [comment]
Thank you for the report. Indeed, it would seem that the `git-update` script does not bother to look at the proxy settings at all.

**Comment by versat** [comment]
If i add proxy settings via a command like
`git config --global http.proxy http://proxyuser:proxypassword@proxy_ip:proxy_port`
then the output of "git update" is something like:
`Using proxy server http://proxy_ip:proxy_port detected from git http.proxy`

So somehow the http.proxy settings are used and the update works (i've tested it).

**Comment by dscho** [comment]
@versat hmm. I was under the impression that the Git for Windows installer already configured `http.proxy`... Was that not the case in your setup?

**Comment by dscho** [comment]
Hmpf. I just had a quick look and it would appear that the installer does *not* configure a proxy.

Could I ask you (since you have a setup requiring a proxy, which I do not have, so I would have to set up a VM just to answer such simple questions) to see what the exit code of the `curl` call is when the proxy is *not* set? I.e. what does `curl -s https://api.github.com/repos/git-for-windows/git/releases/latest; echo $?` show?

**Comment by versat** [comment]
No the installer did not configure a proxy.
Bad news: The return code is always 7:
```
user MINGW64 ~
$ git config --global --unset http.proxy

user MINGW64 ~
$ git config --global --get http.proxy

user MINGW64 ~
$ curl -s https://api.github.com/repos/git-for-windows/git/releases/latest; echo $?
7

user MINGW64 ~
$ git update

user MINGW64 ~
$ git config --global http.proxy http://127.0.0.1:3125

user MINGW64 ~
$ git config --global --get http.proxy
http://127.0.0.1:3125

user MINGW64 ~
$ curl -s https://api.github.com/repos/git-for-windows/git/releases/latest; echo $?
7

user MINGW64 ~
$ git update
Using proxy server http://127.0.0.1:3125 detected from git http.proxy
```

BTW: I'm using the local proxy "cntlm" to connect to the company proxy to not have to enter the user/pw everywhere.

**Comment by dscho** [comment]
> Bad news: The return code is always 7:

Oh, that's fine. `http.proxy` is not heeded by `curl.exe`. It is heeded by `git-update` ;-)

Looking at the man page of `curl`, it would appear that the exit code 7 means:

```
       7      Failed to connect to host.
```

So probably we have to reinstate [the work by @bufferoverflow](https://github.com/git-for-windows/build-extra/pull/153/commits/d15dec25a1cf792ba99a9eb77d441bfbb27207dd) that I so foolishly rejected...

**Comment by dscho** [comment]
I just pushed a topic branch to https://github.com/git-for-windows/build-extra/compare/master...dscho:updater-proxy that implements what I asked [here](https://github.com/git-for-windows/build-extra/pull/153#discussion_r135351748), and then zipped up the `proxy-lookup.exe` tool in [proxy-lookup.zip](https://github.com/git-for-windows/git/files/1470703/proxy-lookup.zip).

@versat could you do me a favor and unpack the `.exe`, then verify that `proxy-lookup.exe https://api.github.com/` shows you the correct proxy URL?

**Comment by versat** [comment]
$ ./proxy-lookup.exe https://api.github.com/
127.0.0.1:3125

Looks good.

**Comment by dscho** [comment]
Excellent. Next ask: could you copy that `.exe` to, say, `~/bin/` (you may need to create that directory in Git Bash first), then copy also https://raw.githubusercontent.com/dscho/build-extra/c6258e1c65638df4f2b954f655e559dc7a701cce/git-extra/git-update as `git-update` to that directory, then ensure that `http.proxy` is *not* set, and run `git update`? It *should* pick up the proxy correctly (and also print as much on the command-line).

**Comment by versat** [comment]
```
$ git config --global --get http.proxy

$ ./git-update
Using proxy 127.0.0.1:3125 as per lookup
```

Yeah works :)

**Comment by dscho** [comment]
Okay! Thank you for testing!

**Comment by david-russo** [comment]
I'm still running into a variation of this issue.

With version 2.15.1.2 it now returns the following, but nothing else:
```
Using proxy first-proxy:8080;second-proxy:8080 as per lookup
```

It seems like it might not be taking into account the specification of multiple proxy servers.

**Comment by dscho** [comment]
@david-russo that's an interesting setup. I *think* the solution should be as easy as patching `C:\Program Files\Git\mingw64\libexec\git-update` to insert `https_proxy="${https_proxy%%;*}"` before https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-update#L99 (essentially dropping the second proxy). Can you test that?

**Comment by david-russo** [comment]
I'm afraid my old workstation was decommissioned two days ago, though I imagine it will still be a problem eventually since the proxy situation hasn't changed:

The two proxy options were not part of my Git configuration, but seemed to come from a PAC script. I did test the `proxy-lookup.exe` you posted above on my last workstation and it returned "first-proxy:8080;second-proxy:8080", so your fix might be better placed before [line 145](https://github.com/git-for-windows/build-extra/blob/20265444f61eb4b26404e70319e9087285babc38/git-extra/git-update#L145) instead.

The reason I can't test it right now, unfortunately, is that I'm having a separate issue on my new workstation where `git update` returns no output at all. Executing `curl https://api.github.com/repos/git-for-windows/git/releases/latest` returns the following though:
```
curl: (77) error setting certificate verify locations:
  CAfile: /mingw64/ssl/certs/ca-bundle.crt
  CApath: none
```
I can confirm that the file exists and is readable at that location. I've tried configuring it to use the OpenSSL and Windows Secure Channel libraries, but get no response from `git update` either way. Other Git functionality, such as cloning, seems to function fine over HTTPS.

A possible difference between the two workstations is that Git has been installed locally (in AppData) without administrative rights, instead of globally like it may have been on the last machine.

**Comment by dscho** [comment]
Is that `ca-bundle.crt` empty, perhaps? You can also ask `curl` to be more verbose in its output by using `--verbose` or even `--trace-ascii`.

**Comment by david-russo** [comment]
The `ca-bundle.crt` contains valid-looking certificates. Here's the `--trace-ascii` output:
```
== Info: Trying <proxy-ip>...
== Info: TCP_NODELAY set
== Info: Connected to <first-proxy> (<proxy-ip>) port 8080 (#0)
== Info: ALPN, offering http/1.1
== Info: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
== Info: error setting certificate verify locations:
  CAfile: /mingw64/ssl/certs/ca-bundle.crt
  CApath: none
== Info: Closing connection 0
```

**Comment by dscho** [comment]
Hmm. The only thing I can think of that might be going wrong here is that the location is not resolved to a path relative to the top-level directory of the Git installation.

Any chance that you can run this again after starting a [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon), to find out what exact problem the process has to access `ca-bundle.crt`?

**Comment by david-russo** [comment]
Looking through Process Monitor's logs, I see `curl.exe` looking for `curl-ca-bundle.crt` in my `PATH` locations and maybe a few other places, before finally looking for `C:\mingw64\ssl\certs\ca-bundle.crt` and receiving a `PATH NOT FOUND` response.

It should instead be resolving to `%LOCALAPPDATA%\Programs\Git\mingw64\ssl\certs\ca-bundle.crt`

**Comment by dscho** [comment]
> I see curl.exe looking for curl-ca-bundle.crt in my PATH locations and maybe a few other places, before finally looking for C:\mingw64\ssl\certs\ca-bundle.crt and receiving a PATH NOT FOUND response.

Hrm. That is unexpected. If I run my `curl.exe` in my Git Bash, it uses WinSSL and does not even bother to look for `ca-bundle.crt`. Oh, and `which curl` reports: `/mingw64/bin/curl`, your's too?

For the record, if I force my `curl.exe` to use OpenSSL (by setting `CURL_SSL_BACKEND=openssl`), my Process Monitor indeed shows me a bunch of unsuccessful attempts to open `ca-bundle.crt` in all kinds of locations along the `PATH`, the time difference between the first and the last of these is 0.0110635 seconds. Then it tries to create a new thread, performs a bunch of operations on `C:\Windows\System32\dnsapi.dl` and a lot of other DLLs, opens the TCP connection 0.2625920 seconds after the latest attempt to read `ca-bundle.crt`, and finally, finally opens `C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt` successfully another 0.1440292 seconds later, reads it, and obviously succeeds in validating the server's certificate.

**Comment by david-russo** [comment]
Yeah, I have the same `which curl` output.

I should note that the crt file being searched for in all cases except the last seems to be curl's default `curl-ca-bundle.crt` and not `ca-bundle.crt`, and the access attempt for the only correctly named file (the last) happens after some further processing, is done *twice* in quick succession for the same path, and fails both times. Everything occurs in well under a second.

Setting `CURL_SSL_BACKEND` to `openssl` or `winssl` (assuming that's a valid value) results in the same error message.

**Comment by dscho** [comment]
> Setting CURL_SSL_BACKEND to openssl or winssl (assuming that's a valid value) results in the same errors.

That is interesting. What does `curl -V` say (and `curl.exe -V`)?

**Comment by david-russo** [comment]
Both (in Git Bash) report:
```
curl 7.57.0 (x86_64-w64-mingw32) libcurl/7.57.0 OpenSSL/1.0.2m (WinSSL) zlib/1.2.11 libidn2/2.0.4 libssh2/1.8.0 nghttp2/1.26.0
Release-Date: 2017-11-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy MultiSSL Metalink
```

**Comment by dscho** [comment]
> (WinSSL)

In this mode, cURL does not (need to) look for `ca-bundle.crt`.

**Comment by david-russo** [comment]
I uninstalled Git and then re-installed with the Windows Secure Channel option selected, but results are still the same. Do you not receive an error if you rename `/mingw64/ssl/certs/ca-bundle.crt` when using WinSSL?

I'm not sure if this is related, but just in case it could be: my "My Documents" folder is mapped to a network drive, which is where the git settings are kept, and in Git Bash `$HOME` resolves to this location.

**Comment by dscho** [comment]
> Do you not receive the error if you rename /mingw64/ssl/certs/ca-bundle.crt when using WinSSL?

Indeed, I don't. I still suspect that a different `curl` is at work, maybe you have an alias or something. You can verify my suspicion (or disprove it) by using Process Monitor and right-clicking on the label `curl.exe` in Process Monitor's output, then selecting "Properties".

> I'm not sure if this is related, but just in case it could be: my "My Documents" folder is mapped to a network drive, which is where Git's settings are kept, and in Git Bash $HOME resolves to this location.

That should not affect things. I am quite puzzled that your `curl.exe` claims to be at the correct version, using WinSSL (Secure Channel), and then does things totally different from mine.

**Comment by dscho** [comment]
> Do you not receive the error if you rename /mingw64/ssl/certs/ca-bundle.crt when using WinSSL?
> 
> Indeed, I don't.

Let me clarify that I did not rename `C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt`. Did you?

What I meant is that I do not get an error about reading that file, because cURL should not even read it in WinSSL mode.

**Comment by david-russo** [comment]
No, I've never renamed it or modified any of the files under the installation directory.

Under Process Monitor's Event Properties, and Process tab, the path given is:
`C:\Users\<Username>\AppData\Local\Programs\Git\mingw64\bin\curl.exe`

**Comment by david-russo** [comment]
OK, as mentioned [here](https://github.com/curl/curl/issues/2209), the backends in parentheses, such as "(WinSSL)", apparently refer to the *inactive* backends. I've found the correct keyword to use is `schannel`, not `winssl`. So this works fine for me:

`CURL_SSL_BACKEND=schannel curl https://api.github.com/repos/git-for-windows/git/releases/latest`

Should my installation configuration to use Secure Channel be honoured if I'm calling `curl` directly from Git Bash?

**Comment by dscho** [comment]
> the correct keyword to use is schannel, not winssl.

Oh, right! I forgot about that.

And you're correct, we should force this in `git-update` by setting `CURL_SSL_BACKEND=schannel`.

But I am still curious why you have those problems, and I figure it *might* have something to do with the patch `C:\Users\<Username>\AppData\Local\Programs\Git\mingw64\bin\`. Is there a space in your username? (It should not matter... there is a space in `Program Files` and it works there.) Oh, maybe you have a non-ASCII character in your username?

I really would like to figure out what is going wrong in your setup because it sounds like a bug in https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-curl/0001-Make-cURL-relocatable.patch and I would really like to fix it if that's the case.

**Comment by david-russo** [comment]
I'm sorry to say my username consists entirely of plain, vanilla, lowercase ASCII letters, but I'm open to suggestions for any further testing you'd like to have me do :)

**Comment by david-russo** [comment]
After fooling around with `git-update.sh`, I've discovered that there doesn't seem to be any kind of issue with curl use in the script – it finds the CA bundle just fine – the lack of output I'm currently experiencing is due to this line:
https://github.com/git-for-windows/build-extra/blob/bf7da38ebe6444af795a2a4789e02cae5721aab8/git-extra/git-update#L160

Removing the line allows the script to report that Git is currently up-to-date.

**Comment by dscho** [comment]
> It finds the CA bundle just fine

Splendid!

> the lack of output I'm currently experiencing is instead due to line 160.

Yeah, the idea is that it should not notify the user multiple times (it can get quite annoying if it does remind the user every single day that there is a new version when the user already declined to update).

There is a `--testing` option that overrides this behavior...

**Comment by david-russo** [comment]
Ah, I see. That makes sense from an automatic-check perspective, but if I'm running `git update` manually I'd expect a response.

**Comment by dscho** [comment]
Makes sense. So instead of `--testing`, it should be renamed to `--quiet` and invert the meaning.

Sadly, I won't have time to implement this anytime soon. If you open a Pull Request, though... 😁
