### ISSUE TITLE
[Enhancement] override core Git's PULL_REQUEST_TEMPLATE.md that does not apply to Git for Windows

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#1364]
Apparently, core Git recently added the file `.github/PULL_REQUEST_TEMPLATE.md` which discourages developers from opening Pull Request in https://github.com/git/git.

This is not what Git for Windows wants, though, so we need to override it.

# How to fix this

This is probably the easiest of the "up for grabs" task, as you do not even need to clone any repository. Just head over to https://github.com/git-for-windows/git/blob/master/.github/PULL_REQUEST_TEMPLATE.md, hit the "Edit" button and write something designed to make contributors feel as good as they deserve to feel for contributing.

**Comment by PhilipOakley** [comment]
Job done (hopefully; forget to mention this issue in the commit)
https://github.com/git-for-windows/git/commit/a8eb2a23a6a462caf8dc0208544c9361c880aa81

**Comment by PhilipOakley** [comment]
Also updated the main README.md -> Upstream ?
https://github.com/git-for-windows/git/commit/183cb6761df52aa09ff5d23b6988ee5d1c946255#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by dscho** [comment]
Thanks @PhilipOakley!

I will have to remember to squash this into 434e7974024e5acbccd56e85199c83bc3309defa next time I rebase... maybe next time you change `README.md` mark it as a `fixup!` commit?
