### ISSUE TITLE
Git crashing on shutdown/logout

### ISSUE THREAD

**Issue by Stanzilla** [git-for-windows/git#1365]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.64]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
Plink Path: C:\Program Files\TortoiseSVN\bin\TortoisePlink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

Sometimes when I log out of Windows and/or shut it down, Git crashes with the following error

![csrss_2017-11-14_22-40-22](https://user-images.githubusercontent.com/75278/32806634-80446b26-c98d-11e7-8914-b074e208ebc8.png)

**Comment by dscho** [comment]
Have you tried a web search for "0xc0000142"?

**Comment by Stanzilla** [comment]
Yes but none of the suggestions made a lot of sense, I have no corrupted files. My guess is that some program is trying to call git during shutdown but I figured it might be worth reporting it as a bug anyway.

**Comment by rexdf** [comment]
just guess

0. install VC++ runtime .Net runtime etc
1.  dll conflict, check the path environment, is there any other msys path in it? Or missing something important like system32.
2.  antivrus software injection
3.  virus

**Comment by Stanzilla** [comment]
Nope, checked all of that. My current guess is that VSCode or SourceTree is trying to `git status` right when the PC is trying to shut down and that makes it error.

**Comment by rexdf** [comment]
What about a screenshot of `Dependency Walker` ?  View/Collapse all.

Type `path` in command line. what's the result?

Type `where git` in command line? What's the result? How many are there?

Which git is vscode using? prove it.

**Comment by dscho** [comment]
I cannot find it anymore, but there *was* a suggestion to somehow let `git.exe` prevent a shutdown. I forgot the details. @Stanzilla maybe you can find out how that can be done?

**Comment by dscho** [comment]
I looked a bit further, and it seems there is an API since Vista. "Happily", we dropped XP support some time ago.

Here is an example how to do it in a console app: https://stackoverflow.com/a/29190591

Maybe you could find it in you to implement this in https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/git-wrapper.c and send a PR?

**Comment by dscho** [comment]
@Stanzilla then let's close this until you have time, okay?
