### ISSUE TITLE
Git Installer Select Components area is cut from visible area

### ISSUE THREAD

**Issue by rexdf** [git-for-windows/git#1367]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
Git-2.15.0-64-bit.exe
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.17025.1000] x64
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**Scale and layout is always 120%, I just notice this problem with windows 10 17025.**

### Details

 - What did you expect to occur after running these commands?

**Optional checkbox is visible and changable. A scrollbar is ok.**

**I even tried [Winsize2](http://winsize2.sourceforge.net), it did not work neither.**

 - What actually happened instead?

![git_bug](https://user-images.githubusercontent.com/4038241/32976419-549bad34-cc50-11e7-8f9b-627c6f69498c.PNG)

**not working**

 - Questions.

**Are there any command line arguments to bypass it?**

**Comment by AdamBryantSkybox** [comment]
This is happening to me as well.
Same version of windows: `Microsoft Windows [Version 10.0.17025.1000] x64`
Cheers,

**Comment by dscho** [comment]
> I was not able to find an open or closed issue matching what I'm seeing

I was: https://github.com/git-for-windows/git/issues/1353 (which is itself already a duplicate of https://github.com/git-for-windows/git/issues/1342).

In short: y'all are using Insider Previews. Please use the feedback channel to report this issue so that it can be fixed soon.

**Comment by rexdf** [comment]
Hm, I submitted it to microsoft Feedback Hub. Maybe I can dig into the Inno Setup. 
Qt and other program installers render checkboxes quite well.
