### ISSUE TITLE
git diff exception

### ISSUE THREAD

**Issue by binave** [git-for-windows/git#1369]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
MinGit-2.15.0-busybox-64-bit
MinGit-2.14.3-busybox-64-bit
```

```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.64] 64-bit, or early version.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

The system cannot find the path specified.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
PATH=C:\Program Files\ExtCmd\MinGit-2.15.0-busybox-64-bit\mingw64\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\ExtCmd\MinGit-2.15.0-busybox-64-bit\usr\bin
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd.exe
busybox.exe bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git diff
```
 - What did you expect to occur after running these commands?

git diff will print the color code,
not colored characters.

 - What actually happened instead?

git diff will print the color code,
not colored characters.

**Comment by dscho** [comment]
MinGit is "Git for Windows applications". Its output is not intended to be consumed by humans. In particular, as many interactive features of Git for Windows are omitted as is easily possible, in favor of size.

As such, what you see is expected behavior..
