### ISSUE TITLE
"start" doesn't work

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#137]
Executing "start <command|directory>" in msys bash doesn't work.

e.g.
```
start .
bash: start: command not found
```

Notice that start is an internal "cmd" command, and has no executable file.

It does work with MsysGit 1.9.5 and with plain msys2.

**Comment by dscho** [comment]
`/usr/bin/start` is part of the `filesystem` package in MSys2. Unfortunately, that package is quite large, and we actually do not need most of those files.

So I fixed it thusly: https://github.com/git-for-windows/build-extra/commit/fd0095c0ea3bdf141d57c563b84c8e8bb0f9219b
