### ISSUE TITLE
Git log for a file is has all changes which involve submodules too

### ISSUE THREAD

**Issue by kumarharsh** [git-for-windows/git#1371]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 FCU

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.16299.64]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: CmdTools              
SSH Option: OpenSSH                
CURL Option: OpenSSL               
CRLF Option: CRLFAlways            
Bash Terminal Option: ConHost      
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled    
Enable Symlinks: Enabled           
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using ConEmu.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash, CMD, Powershell, WSL Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I'm filing this issue from this stackoverflow question: https://stackoverflow.com/questions/47185944/git-log-with-square-bracket-in-name

Reproduce it by:
* running this [shell-script](https://gist.github.com/kumarharsh/e1948c6971f1c68577792ff914a00af7) in WSL or git bash.
And then,

```
1. Open powershell, type `git log .\[__Odd__].txt`
2. Open CMD, type `git log ./"[__Odd__].txt"`
3. Open WSL bash, type `git log ./\[__Odd__\].txt`
4. Still in WSL, type `git.exe log ./\[__Odd__\].txt`
```

 - What did you expect to occur after running these commands?

All git log outputs should have been the same.

 - What actually happened instead?

The output of 1, 2, 4 is different from the output of 3. The output of 3 is correct (git log should not show changes for submodules while viewing git log for a particular file). Hence, it follows that git-for-windows' `git.exe` might have a bug.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://stackoverflow.com/questions/47185944/git-log-with-square-bracket-in-name

**Comment by dscho** [comment]
> running this shell-script in WSL or git bash.

Note that you never showed how you call it in Git Bash, only in Git CMD and Powershell, and in WSL's bash (which is distinctly not Git Bash).

Also, the CVE can be wittled down to an MCVE:

```sh
#!/usr/bin/env bash

set -e
export GIT_AUTHOR_NAME=x
export GIT_AUTHOR_EMAIL=x@y

rm -rf repo submodule

git init repo
cd repo

git init submodule
git -C submodule commit -m initial --allow-empty

touch "[bracket]"
git add "[bracket]"
git commit -m bracket
git add submodule
git commit -m submodule

git log -- "[bracket]"
```

Running it in Git Bash will also show the submodule commit.

Running it *on Linux* with v2.15.0 will also show the submodule commit.

Running it on Linux with v2.7.4 (which is sadly the current state of Ubuntu's LTS, as used by WSL) will *not* show the submodule commit.

So what you see at work is a regression that is not specific to Windows. I bisected it down to 74ed43711fd1cd7ce155d338f87ebe52cb74d9e2

**Comment by dscho** [comment]
I analyzed a bit further and [asked for help on the Git mailing list](https://public-inbox.org/git/alpine.DEB.2.21.1.1711260210060.6482@virtualbox/T/#u).

**Comment by kumarharsh** [comment]
Thanks for looking into this @dscho and for simplifying the MCVE.

**Comment by kumarharsh** [comment]
Yay! That was fast!

Is this considered 'solved' now? Can this issue be closed?

**Comment by dscho** [comment]
> Can this issue be closed?

The patch only made it into the "proposed updates" so far, I would wait a couple of days.

If nothing happened with it in a few days, would you mind reminding me of this so I can 1) cherry-pick it to Git for Windows' `master` and 2) prod upstream to get things moving further?

**Comment by kumarharsh** [comment]
Sure.

**Comment by dscho** [comment]
@larsxschneider hah. I think you closed this inadvertently, by pulling core Git's `master` into your own fork, and since you are part of the trusted Git for Windows reviewers, GitHub thought that you meant to close this ticket.

However, since the commit in question made it into core Git's `master`, from which v2.16.0 is slated to be released [on or around January 17th 2018](http://tinyurl.com/gitCal), I think this is actually appropriate: I do not think that we will release a new Git for Windows version before v2.16.0.

**Comment by larsxschneider** [comment]
Woah. I wasn't aware of these side effects. Thanks for letting me know!

I try to avoid that in the future (I don't need a master branch in my fork anyways).
