### ISSUE TITLE
git filter-branch --parent-filter 'test ...' HEAD not working

### ISSUE THREAD

**Issue by fjbsaper** [git-for-windows/git#1377]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit

```
$ git --version --build-options

** insert your machine's response here **
$ git --version --build-options
git --version --build-options
git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [Version 10.0.16299.64]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
my repository is a file repository created with git init --bare and referenced in git remote
Over time the repository is growing.
Usually I use the git command shown below to prune the local repository, then remove the old refs and force push to remote and shrink using git gc.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
 running under Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
git filter-branch --parent-filter 'test $GIT_COMMIT == 524559cd6c0769418d17e587e69d0d58f1dff1dd && echo "" || cat ' HEAD
```
 - What did you expect to occur after running these commands?

** insert here **
I expected to rewrite the history dumping everything before the said commit

 - What actually happened instead?
I am getting error messages and a dump:
 **dump**
cat sh.exe.stackdump
Exception: STATUS_STACK_OVERFLOW at rip=7FF8DB6F4B57
rax=0000000000001250 rbx=00000000FFFFAD80 rcx=0000000000000000
rdx=0000000180010018 rsi=0000000180271780 rdi=000000018021C490
r8 =00000000027D4590 r9 =0000000180271780 r10=00000000FFFF9000
r11=00000000FFE03120 r12=00000000FFFFAC60 r13=000000018021C490
r14=00000000FFFFAC00 r15=00000000FFFFAD88
rbp=0000000000000420 rsp=00000000FFFFAA68
program=C:\Program Files\Git\usr\bin\sh.exe, pid 11452, thread unknown (0x3534)
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B

**error message**
Rewrite 3f6bf4c315c857f1960eab5736101df770a84200 (1/) (1 seconds passed, remaining -1 predicted)    parent filter failed: test $GIT_COMMIT == 524559cd6c0769418d17e587e69d0d58f1dff1dd && echo "" || cat

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
@fjbsaper  Has the report formatted the way you wanted?
- sometime the hash (#) chars in the template or report end up unexpectedly as headings..

Apart from wondering why you find the repo to be growing too large (how large, etc?), which is a side question that may end up with "manage the repo a little differently so you don't have to do the command..."...

Can you try running the command with GIT_TRACE=1 so that the sequence of internal actions and commands can be seen? If the trace is long, could you also report the organisation of the repo such that we can see how the final actions proceded. 

You can redirect the trace output to an open file descriptor by using GIT_TRACE=<fd> (there is also a trace env var for networking https://projects.cs.uaf.edu/redmine/projects/public/wiki/How_do_I_make_Git_give_more_verbose_output )

**Comment by PhilipOakley** [comment]
@fjbsaper the final line should say
`GIT_TRACE=<fd>` 
Hopefully this time the 'fill in the blank with the file descriptor number' will show in the emails.

**Comment by fjbsaper** [comment]
This is the output with export GIT_TRACE=1
`$ git filter-branch --parent-branch 'test $GIT_COMMIT == 95007d1b64c3859043ec4aee4065671d6ac481ab && echo "" || cat ' HEAD
git filter-branch --parent-branch 'test $GIT_COMMIT == 95007d1b64c3859043ec4aee4065671d6ac481ab && echo "" || cat ' HEAD
15:14:07.985063 git.c:576               trace: exec: 'git-filter-branch' '--parent-branch' 'test $GIT_COMMIT == 95007d1b64c3859043ec4aee4065671d6ac481ab && echo "" || cat ' 'HEAD'
15:14:07.985063 run-command.c:626       trace: run_command: 'git-filter-branch' '--parent-branch' 'test $GIT_COMMIT == 95007d1b64c3859043ec4aee4065671d6ac481ab && echo "" || cat ' 'HEAD'
15:14:12.710731 git.c:576               trace: exec: 'git-sh-i18n--envsubst' '--variables' 'usage: $dashless $USAGE'
15:14:12.710731 run-command.c:626       trace: run_command: 'git-sh-i18n--envsubst' '--variables' 'usage: $dashless $USAGE'
15:14:12.804813 git.c:576               trace: exec: 'git-sh-i18n--envsubst' 'usage: $dashless $USAGE'
15:14:12.804813 run-command.c:626       trace: run_command: 'git-sh-i18n--envsubst' 'usage: $dashless $USAGE'
15:14:14.227847 git.c:344               trace: built-in: git 'rev-parse' '--git-dir'
15:14:14.620178 git.c:344               trace: built-in: git 'rev-parse' '--show-cdup'
15:14:17.372420 git.c:344               trace: built-in: git 'rev-parse' '--git-path' 'objects'
15:14:17.551906 git.c:344               trace: built-in: git 'rev-parse' '--is-bare-repository'
15:14:17.740853 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
15:14:18.590440 git.c:344               trace: built-in: git 'update-index' '-q' '--ignore-submodules' '--refresh'
15:14:18.945686 git.c:344               trace: built-in: git 'diff-files' '--quiet' '--ignore-submodules'
15:14:19.209368 git.c:344               trace: built-in: git 'diff-index' '--cached' '--quiet' '--ignore-submodules' 'HEAD' '--'`
I hope this helps you to pinpoint where the pain is.

I am doing this to keep the size of the repository between 380 and 900 MB. (so you could easily carry it on a jump drive)... and about worth a month's history of changing db content...

Stack dump still looks the same:
'cat sh.exe.stackdump
Exception: STATUS_STACK_OVERFLOW at rip=7FF8DB6F4B57
rax=0000000000001250 rbx=00000000FFFFAD10 rcx=0000000000000000
rdx=0000000180010018 rsi=0000000180271780 rdi=000000018021C490
r8 =00000000027346B0 r9 =0000000180271780 r10=00000000FFFF9000
r11=00000000FFE034D0 r12=00000000FFFFABF0 r13=000000018021C490
r14=00000000FFFFAB90 r15=00000000FFFFAD18
rbp=0000000000000420 rsp=00000000FFFFA9F8
program=C:\Program Files\Git\usr\bin\sh.exe, pid 5352, thread unknown (0x3CB0)
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B'

**Comment by dscho** [comment]
> `git filter-branch --parent-filter 'test $GIT_COMMIT == 524559cd6c0769418d17e587e69d0d58f1dff1dd && echo "" || cat ' HEAD`

With this specific commit, the MCVE is incomplete without a concrete repository.

**Comment by fjbsaper** [comment]
The repository is an absolute file path
.git remote -v
16:26:17.695134 git.c:344               trace: built-in: git 'remote' '-v'
origin  C:/Users/F.J/gitrepo/usa2.git/ (fetch)
origin  C:/Users/F.J/gitrepo/usa2.git/ (push)
.

**Comment by dscho** [comment]
> The repository is an absolute file path

Unfortunately, that makes the MCVE an ME (i.e. it is neither complete nor verifiable).

> I am doing this to keep the size of the repository between 380 and 900 MB. (so you could easily carry it on a jump drive)... and about worth a month's history of changing db content...

Would you not be better served by shallow fetches?

**Comment by PhilipOakley** [comment]
@fjbsaper Is the repo available publically, or at least can you do a fast export --annonymise(d) version of it that will show the fault?

Is it right that the error message was the two lines:
```
Rewrite 3f6bf4c315c857f1960eab5736101df770a84200 (1/) (1 seconds passed, remaining -1 predicted)
parent filter failed: test $GIT_COMMIT == 524559cd6c0769418d17e587e69d0d58f1dff1dd && echo "" || cat
```
Is the line break in the right place?

Has the script worked before? My googling found http://git.661346.n2.nabble.com/purging-unwanted-history-td1507638.html which, to me, suggests a slightly different code is required. (doesn't resolve what caused the stackdump, but would get the repo fixed)

(I agree with dscho that a repacked shallow clone may be the way to go for local portability. What's in the repo that is making it large?)

**Comment by fjbsaper** [comment]
@PhilipOakley Sorry the repo is not available publicly, way too much sensitive data in it and It take me forever to sanitize it. However may be you can reconstruct. The data is in Dbase (so digital) and each change to the db (session could be multiple changes) gives a commit.
Yes the error message was the 2 lines. I was beginning to wonder if it had something to do with the child process not being able to grab the lock from the parent??

In the past I used the filter-branch --parent-filter to prune the repository. You have to add the delete for the original reflogs but after that and a git gc (on the local and the repository) the space used was nearly reduced in half and the only inconvenience was a rewrite of the commits in the new tree that I can easily live with. It used to work fine until i upgraded to this latest version. As I don't have the previous version to install anymore, I am looking for a way to get the behavior back and fix the filter-branch --parent-filter

Since the last 2 or 3 versions I am also getting the reference to unary operator to be used in the test. This has always been more of a warning and did not use to affect the results.

Which part did you mean with the link. The one that looked almost identical to what I used but with and if -- else -- fi test?

**Comment by dscho** [comment]
> However may be you can reconstruct.

Sorry, this is not going to work. If you care to take even the slightest look: there are over 100 open tickets to be addressed, and if every reporter expected Philip or me to just take the few crumbs of information and then spend days to try to even just reproduce the issue, it would simply not scale. In fact, that is what keeps most of those tickets frustratingly stale.

There is no reason to expect your report to fare any differently.

And quite honestly, if you cannot be bothered to try to come up with a tiny public repository where you can reproduce the problem, and which somebody else could clone very quickly and verify very quickly whether they can reproduce the problem, too, why should anybody else feel the need to chip in and help you?

No, the appropriate course of action is to work on your side, create a repository from scratch and try to make it a true Minimal, Complete *and* Verifiable Example. Work on it as hard as you would like anybody knowledgeable in the Git internals to work on fixing the issue once they can reproduce the issue. That will get you what you want (have your problem fixed), and the person helping you what they want (improve the project).

**Comment by dscho** [comment]
> I am also getting the reference to unary operator to be used in the test.

This means that your code snippet encounters an empty `$GIT_COMMIT`, and because you did not quote it, the `test` command is called as `[ == 95007d1b64c3859043ec4aee4065671d6ac481ab ]`, which is obviously incorrect.

**Comment by fjbsaper** [comment]
@PhilipOakley 
Here is a repo that you can use. I get the same behavior across any repository: 
[(https://github.com/fjbsaper/apiconnect-docker)]
I believe the solution will come once the core dump is fixed.

**Comment by fjbsaper** [comment]
Update: The issue is only present in the 64 bit version. The 32 bit version works as expected.

**Comment by dscho** [comment]
No dice:

```sh
me@work MINGW64 /d/test-git/stack-overflow-1377/apiconnect-docker (master)
$ git filter-branch --parent-filter 'test $GIT_COMMIT == 524559cd6c0769418d17e58                                                                                                                           7e69d0d58f1dff1dd && echo "" || cat ' HEAD
Rewrite bf21761ab88bada225293919261a4f6469969fa9 (1/19) (0 seconds passed, remai                                                                                                                           Rewrite 830164fcd0054a4fd895fa79dbd77dd5cc47871c (2/19) (1 seconds passed, remai                                                                                                                           Rewrite 2d893c9afd828bccbbc6cf9b70a13c537e843c39 (2/19) (1 seconds passed, remai                                                                                                                           Rewrite 3ddc93c84e5d7a917ba0a1d0a1e13b28fa11045a (2/19) (1 seconds passed, remai                                                                                                                           Rewrite df941209884cd154c64620b9c05227e54c5fc2a6 (5/19) (3 seconds passed, remai                                                                                                                           Rewrite cec06c33293dc40952f63833711f79d582d413ad (5/19) (3 seconds passed, remai                                                                                                                           Rewrite b3fa8b900947207c856d607385bffdef5cdd45e0 (7/19) (4 seconds passed, remai                                                                                                                           Rewrite 2f21cf5097dd1f55a9bb78962399719e32521a02 (7/19) (4 seconds passed, remai                                                                                                                           Rewrite c555b7dd0b1f2967a0e3fcecce040eed17b9d267 (9/19) (5 seconds passed, remai                                                                                                                           Rewrite e8cc83d7484222444ca3912ca1f083d3e261641b (9/19) (5 seconds passed, remai                                                                                                                           Rewrite e309700e66dc8f763c92650581591f4ccd5a72f4 (11/19) (7 seconds passed, rema                                                                                                                           Rewrite c29330066932f28802868c4946fa5d60744e9e4e (11/19) (7 seconds passed, rema                                                                                                                           Rewrite 8f4afc5fadccaba39dce37de0b3aa7c39952754d (13/19) (8 seconds passed, rema                                                                                                                           Rewrite 65d7890ad76de66733f49ad4f0d258ae72fb6a9c (13/19) (8 seconds passed, rema                                                                                                                           Rewrite 04a9aa3185b3eebbcf557f9856cfaa228e8215e9 (15/19) (9 seconds passed, rema                                                                                                                           Rewrite 63179a32598547c71271a63e40fc66ae37c1ff01 (15/19) (9 seconds passed, rema                                                                                                                           Rewrite eb9056489386a4e25a18f7b9f7356d49f1c2b59b (17/19) (11 seconds passed, rem                                                                                                                           Rewrite 025b24d3ab4adea8449b7efdc4047fb90b84655a (19/19) (12 seconds passed, remaining 0 predicted)
WARNING: Ref 'refs/heads/master' is unchanged
```

This is with 64-bit v2.15.1(2).

I did see similar issues in the past, and they frequently had to do with overzealous environment handling, e.g. trying to convert the `PATH` variable (and entering an infinite recursion due to a bug in the MSYS2 runtime).

**Comment by fjbsaper** [comment]
@dscho 
I hear your comment that it is environmental. And I would say you're most certainly right that it is in SYS2. Because in the 32 bit version I'm neither seeing the problem with the -eq unary operator, nor the core dump, nor the problem with parent filter failed.

So concretely what are my solutions here:
a) wait for somebody to fix the bug in MSYS2?
b) continue using the 32 bit version

Right now I am leaning towards b) because it works. I would like to see the 64 bit version fixed some time in the future and would be happy to test the fix should somebody want me to.

Hope you all had a Merry Christmas and wishing you all a very Happy New Year

**Comment by dscho** [comment]
> So concretely what are my solutions here:
> a) wait for somebody to fix the bug in MSYS2?
> b) continue using the 32 bit version

If you try a) without doing anything yourself, I fear that you will be waiting until hell freezes over.

You can do b), but that won't solve anything, will it? And once you *need* 64-bit support, you're screwed.

There is also c), of course, which you left out (conveniently?): dive in, spend some effort, and drive this problem to its solution. Naturally, you will need to spend some time for this, or somebody else. Not me, though: after the way this ticket went, you will understand that I am quite unwilling to do the work.

Here is a hint that may help you figure things out: `git-filter-branch` is a Unix shell script, and as such it is pretty easy to add tracing to it: simply insert (as administrator, because the script is inside `C:\Program Files` which does not let mere mortals write into it) a line saying `set -x` after the first line that says `#!/bin/sh`. Once you did that, and run `git filter-branch` again, you will see tons more output, as every Unix shell command that is executed will be printed to the terminal, too. It should be relatively easy to see why `GIT_COMMIT` is empty from that output and cross-referencing the output's lines to the corresponding lines in `git-filter-branch`.

**Comment by fjbsaper** [comment]
@dscho 
Well the old laptop I was having the problem with turned to slag. (corrupted bios) and the new one luckily doesn't have this problem...
