### ISSUE TITLE
Fatal error during checkout: Not a git repository 

### ISSUE THREAD

**Issue by physhh** [git-for-windows/git#1378]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Tried both CMD and Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone --recursive -c core.longpaths=true -j 20 https://github.com/boostorg/boost.git .
git checkout --recurse-submodules tags/boost-1.65.1
```
 - What did you expect to occur after running these commands?

The directory should contain the specified boost version and there should be no errors (the warning about the detached head is ofcourse correct). 

 - What actually happened instead?

This is the output i get for the checkout command

```
fatal: Not a git repository: ../../.git/modules/libs/hana
fatal: Not a git repository: ../../.git/modules/libs/metaparse
Note: checking out 'tags/boost-1.65.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 436ad1dfc... Revert accidental submodule changes  in last commit
M       libs/hana
M       libs/metaparse
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/boostorg/boost.git

## Additional information
It looks like the issue was introduced with a recent version. I just tried 
```
git version 2.13.1.windows.3
built from commit: cdf40a8b0dd28a26cbdf818aa493bd10a7d62095
sizeof-long: 4
machine: x86_64
```
Which works fine

**Comment by dscho** [comment]
> git clone --recursive -c core.longpaths=true -j 20 https://github.com/boostorg/boost.git .

I do not know in which world this is a *minimal* example... It is running for ages here already, and downloading the entire internet twice.

**Comment by physhh** [comment]
@dscho It is minimal regarding the commands you have to type into your terminal. I know that the boost repository itself is quite large but the bug only happens with this repository and it might be that it has to do with all the submodules.

**Comment by dscho** [comment]
Well, I cannot reproduce because of the bandwidth and size requirements.

If you still want me to help, you might want to come up with a small script that recreates the submodule structure of Boost, with dummy (read: generated) repositories.

**Comment by dscho** [comment]
> If you still want me to help [...]

Alternatively, you can investigate a little more yourself. It looks like:



> ```
> fatal: Not a git repository: ../../.git/modules/libs/hana
> fatal: Not a git repository: ../../.git/modules/libs/metaparse
>```

... this should give you a good starting point: two directories that are supposed to be .git directories (most likely for the submodules that are named very similarly to the reported paths), and probably are either malformed, incomplete, or in an unexpected spot.

**Comment by tboegi** [comment]
I can't reproduce the error.
Side note:
- I used the latest Gwf (2.15)
- The boost project has 137 submodules
- Some of them failed to clone, they had been re-scheduled, with success.
- Re-done the cloning one more time:
- It tool 11 minutes
- I didn't use -j 20 
- It run without any problems

Does it work for you, if you run without -j 20 ?

**Comment by physhh** [comment]
@tboegi It didn't work without -j 20 either. I will try to recreate the boost repository structure as @dscho suggested. Will take some time because I am kind of busy right now. Maybe I can reproduce it with this. I was able to reproduce it on a windows 10 system too. Hope i can figure out some more information...

**Comment by dscho** [comment]
@physhh any news?
