### ISSUE TITLE
Bash home Env Variable or "/" parsing problem?

### ISSUE THREAD

**Issue by c33s** [git-for-windows/git#1381]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

not sure if this is the right repo to open the issue in, it is a problem with bash but as it comes with git for windows i assume i should open an issue here.

the problem first occured as i ran [r10k](https://github.com/puppetlabs/r10k) which basically clones all repos listed in a special file `Puppetfile` and also caches the repos. running `r10k puppetfile install` showed up something like (not the exact error message, it is phrased from my memory): 
```
repo not found in 'C:/Program Files/Git/opt\puppetlabs\puppet\cache\r10k\https---github.com-user-repo.git
```
after some `r10k` runs the error was gone, i don't know how it resolved. 

now i try to run `VBoxManage.exe` the cli manager from [virtualbox](https://www.virtualbox.org/) where i have a similar error if i use the `--group` parameter. 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64bit
```
$ git --version --build-options
git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

window7x64
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
Plink Path: C:\Program Files (x86)\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

mainly [cmder](http://cmder.net/) but also tested it with `cmd.exe`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
VBoxManage createvm --name vagrant-basebox-stretch5 --ostype Debian_64 --register --groups "/vagrant-baseboxes"
```
 - What did you expect to occur after running these commands?

i would assume that a virtual machine is created in virtualbox in the group named "vagrant-baseboxes". virtualbox requires the `/` at the begining of the groupname

 - What actually happened instead?

```
VBoxManage.exe: error: Invalid machine group 'C:/Program Files/Git/vagrant-baseboxes'
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "ComposeMachineFilename(bstrName.raw(), bstrPrimaryGroup.raw(), createFlags.raw(), bstrBaseFolder.raw(), bstrSettingsFile.asOutParam())" at line 266 of file VBoxManageMisc.cpp
```

the problem only arises if i proivde the `--groups` parameter and only if it contains the `/` 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

not applicable

**Comment by dscho** [comment]
This is mentioned in our "Known Issues" section in the [Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
> 
>  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
