### ISSUE TITLE
Enhancement: bundle posh-git?

### ISSUE THREAD

**Issue by dahlbyk** [git-for-windows/git#1384]
@dscho reached out to me about bundling [posh-git](https://github.com/dahlbyk/posh-git) with Git for Windows, which I certainly support.

My tentative suggestion would be to have the Git for Windows installer detect a supported PowerShell version (see https://github.com/dahlbyk/posh-git/issues/328 for version support discussion). If available, launch PowerShell to execute a script that runs `Install-Module` (included in 5.0+, or via [PackageManagement PowerShell Modules Preview](https://www.microsoft.com/en-us/download/details.aspx?id=51451), if available.

> Do you have any way to install it system-wide? (Git for Windows installs system-wide, therefore installing posh-git for the installing user would be a little unfortunate.)

[Install-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-5.1) accepts a `-Scope` parameter of either `CurrentUser` or `AllUsers` ([paths](https://github.com/PowerShell/PowerShellGet/blob/a1b56a56d99f319b7fb13391033c22ddfce59eee/PowerShellGet/PSModule.psm1#L23-L63
)). I assume the Git for Windows installer would be able to spawn an elevated shell to install with `AllUsers`.

The other part of installation is to inject `Import-Module posh-git` into a PowerShell profile, which can be one of:

1. Current User, Current (Default) Host
2. Current User, All Hosts
3. All Users, Current (Default) Host
4. All Users, All Hosts

posh-git's [`Add-PoshGitToProfile`](https://github.com/dahlbyk/posh-git/blob/88416bad259c8905b4f4cc9a63cbb0867822f73c/src/Utils.ps1#L87) supports `-AllHosts` but does not support toggling `CurrentUser`/`AllUsers`.

> Also: what's your release cadence? Would you like to coordinate with Git for Windows releases, or are you fine with me simply picking up the latest posh-git whenever I see a new one?

Release cadence is....infrequent? I'd just let PowerShellGet install the latest for the given platform.

**Comment by dscho** [comment]
> My tentative suggestion would be to have the Git for Windows installer detect a supported PowerShell version (see dahlbyk/posh-git#328 for version support discussion). If available, launch PowerShell to execute a script that runs Install-Module (included in 5.0+, or via PackageManagement PowerShell Modules Preview, if available.

Sounds good!

> I assume the Git for Windows installer would be able to spawn an elevated shell to install with AllUsers.

Yes.

> posh-git's Add-PoshGitToProfile supports -AllHosts but does not support toggling CurrentUser/AllUsers.

Is that planned?

> Release cadence is....infrequent? I'd just let PowerShellGet install the latest for the given platform.

Makes sense. Either the user updates Git for Windows (and gets the posh-git updates via `Install-Module`), or the user should update posh-git manually.

**Comment by dahlbyk** [comment]
> > posh-git's Add-PoshGitToProfile supports -AllHosts but does not support toggling CurrentUser/AllUsers.
>
> Is that planned?

https://github.com/dahlbyk/posh-git/pull/504

I'm a month overdue for a release, so I'll ship that soon.

**Comment by dahlbyk** [comment]
> Do you still think it'd be a good idea to bundle posh-git in Git for Windows? It would give it a lot of visibility AKA increased maintenance burden...

I think it would be good for Git for Windows to provide/recommend how to do what Git Bash does (prompt, tab completion) in the default Windows shell.

If posh-git is the best option to achieve that, let's figure out how to make that sustainable. Having this goal to work towards might rekindle my interest.

**Comment by dscho** [comment]
@dahlbyk so how frequently is posh-git updated (if it really is rarely, I'll gladly reverse my stance)? What is the best way to install it system-wide (I'd like to implement this in InnoSetup, so the ideal for me would be "copy this set of files to that destination, then run this command" or something like that)?

**Comment by rimrul** [comment]
> so how frequently is posh-git updated (if it really is rarely, I'll gladly reverse my stance)

Looking at https://github.com/dahlbyk/posh-git/releases, it's roughly once a year (ignoring pre-releases and the occasional two releases on the same day (0.7.0/0.7.1 in april 2017, 0.7.2/0.7.3 in april 2018))

**Comment by dscho** [comment]
Okay, once a year-ish is totally doable. The only remaining concern is: are there occasionally vulnerabilities that require coordinated releases?

**Comment by dscho** [comment]
@dahlbyk great, thanks!

My current thinking is that we should make this a new option (probably a new checkbox just like "Check daily for updates"), and use the PSGallery option, i.e. avoid bundling a specific `posh-git` version.

Pardon my ignorance, though: what commands would I run to check if it is installed, to find out whether there is a newer version, and what commands would be needed to upgrade if there _is_ a new version?

**Comment by dscho** [comment]
> I would think a separate script would be easier to test, isolated from the installer? I've never had to ship an installer, so I'm content to defer to what you think would be easier to maintain.

I actually find it simpler to put the call directly into the installer. See for example how we [call the helper `edit-git-bash.exe`](https://github.com/git-for-windows/build-extra/blob/a272a5ed8cc88401ca82ada81262b2892b680a7a/installer/install.iss#L322).

In any case, Git for Windows v2.34.0 is expected to land this coming Monday or Tuesday, and it is a _little_ too late in the cycle for me to be comfortable with including a bigger change such as adding the option to install `posh-git` into the installer. But right after that version has been released, I am totally in favor of getting this done.

**Comment by dahlbyk** [comment]
> In any case, Git for Windows v2.34.0 is expected to land this coming Monday or Tuesday, and it is a _little_ too late in the cycle for me to be comfortable with including a bigger change such as adding the option to install `posh-git` into the installer.

Agreed.

>But right after that version has been released, I am totally in favor of getting this done.

:+1: I expect to publish a new posh-git release the week of Nov 22.

Let me know what you need from me.

**Comment by dscho** [comment]
@dahlbyk I've opened a PR over at https://github.com/git-for-windows/build-extra/pull/401, not sure whether you saw it.

Now I have a question: should we uninstall Posh-Git when uninstalling Git for Windows? If so, how do I remove it from the users' profile, programmatically?

**Comment by dahlbyk** [comment]
> @dahlbyk I've opened a PR over at [git-for-windows/build-extra#401](https://github.com/git-for-windows/build-extra/pull/401), not sure whether you saw it.

🎉 Do you have a target date for 2.35?

> Now I have a question: should we uninstall Posh-Git when uninstalling Git for Windows? If so, how do I remove it from the users' profile, programmatically?

Replied over in https://github.com/git-for-windows/build-extra/pull/401#pullrequestreview-827192545.

**Comment by rimrul** [comment]
> Do you have a target date for 2.35?

We aim to have Git for Windows releases out within a few days after the corresponding Git release. According to https://tinyurl.com/gitCal Git 2.35.0 is scheduled to release on January 24th.

**Comment by dscho** [comment]
I think it is time to close this, as experience shows that we won't ever get to it.
