### ISSUE TITLE
Git Bash expands curl paramter to include git install dir (not expected)

### ISSUE THREAD

**Issue by mresetar** [git-for-windows/git#1387]
## Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.64]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
curl -v -k -X POST -d 'scope=/api1' https://httpbin.org/post
```
 - What did you expect to occur after running these commands?

{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "'scope": "/api1'"
  },
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "13",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.57.0"
  },
  "json": null,
  "origin": "213.191.147.30",
  "url": "https://httpbin.org/post"
}

 - What actually happened instead?

{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "scope": "C:/Program Files/Git/api1"
  },
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "31",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.57.0"
  },
  "json": null,
  "origin": "213.191.147.30",
  "url": "https://httpbin.org/post"
}

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Look at the scope parameter. It was expanded to include Git installation dir in git bash. Using the same curl in Windows cmd it was not and command run as expected.

**Comment by dscho** [comment]
> What commands did you run to trigger this issue? If you can provide a
> Minimal, Complete, and Verifiable example
> this will help us understand the issue.

So which command exactly did you run?

**Comment by mresetar** [comment]
Just edited. Command was in report but no \n after ```so  it was not visible. One more time it is: `curl -v -k -X POST -d 'scope=/api1' https://httpbin.org/post`

**Comment by dscho** [comment]
This is the good old issue mentioned in the [Known Issues](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
>
>  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
>
>  Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "`//usr/bin/bash.exe`".

I also only read the release notes when I am editing them, so you are not alone.

**Comment by mresetar** [comment]
Thanks @dscho. Indeed it is known issue. It is weird (not expected) that arguments in quotes will be adjusted to windows file paths. 
As it is described I can run curl successfully with command: `MSYS_NO_PATHCONV=1 curl -v -k -X POST -d 'scope=/api1' https://httpbin.org/post`

I'm closing this issue.

**Comment by dscho** [comment]
> It is weird (not expected) that arguments in quotes will be adjusted to windows file paths.

But we have to. You see, we're in a Bash, where you can easily use paths like `/mingw64/bin/` and pass them as command-line arguments to Windows programs. So we *have* to convert them. And `scope=/api1` simply looks very similar to `tmp=/tmp`.
