### ISSUE TITLE
Git GUI - main window - minor problem with Dark theme

### ISSUE THREAD

**Issue by Yousha** [git-for-windows/git#1388]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git 2.15.0 64-bit

```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 Pro 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using **Dark Theme** for my Windows. <---- IMPORTANT!

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

None, just **Git-GUI**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Nothing, it's about **Git-GUI** colors

 - What did you expect to occur?

Git-GUI (main window) must use Windows native colors for **Links**, not it's own color(blue)
![](http://s2.zipupload.ir/direct/uid_1_fid3004_1396-09-11_13_38_44_492449095.png)

 - What actually happened instead?

Since I'm using **Dark theme** for my Windows, I'm not able to see the **links** on main window in Git-GUI. Check the SS:
![](http://s2.zipupload.ir/direct/uid_1_fid3004_1396-09-11_13_38_44_492449095.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None.

**Comment by PhilipOakley** [comment]
You linked to the same png file twice. Did you mean to link to different files. I can see that the links are awkward to see on the png you referenced.

**Comment by Yousha** [comment]
No, it's fine. They are same
Because I couldn't find a good section to post them, so I posted them twice

**Comment by shiftkey** [comment]
> Git-GUI (main window) must use Windows native colors for Links, not it's own color(blue)

It's not clear to me what you mean by "native" here. Could you elaborate?

**Comment by Yousha** [comment]
Well, look at this SS: http://s2.zipupload.ir/direct/uid_1_fid3014_1396-09-13_11_57_22_89965547.png
As you can see I changed **Hyperlinks** color to Light Red(in my Windows Theme), that means ANY **standard Hyperlink** must be Light Red

So I think you guys **Hardcoded** those links colors
That's why Windows theme is not to change it
Got it?

**Comment by dscho** [comment]
@Yousha please research how to support Dark Theme in Tcl/Tk applications, then open a Pull Request.

Thanks.

**Comment by dscho** [comment]
@Yousha the door is always open for Pull Requests.
