### ISSUE TITLE
git-bash.exe can't open python shell

### ISSUE THREAD

**Issue by EECSGEEK** [git-for-windows/git#1391]
## Problem: Git Bash on Startup menu can't open python shell
<img src="https://i.loli.net/2017/12/06/5a2746ffb02f1.png" alt="issue1.png" style="width: 75%; height: 75%" />
<h4>Git/git-bash.exe can't open python shell but other bash.exe can open python shell </h4>
<img src="https://i.loli.net/2017/12/06/5a2746ffb9d05.png" alt="issue2.png" style="width: 75%; height: 75%" />

### other bash.exe can open python shell
```
C:\Users\76320>where /r C: bash
C:\Users\76320\Software\Git\bin\bash.exe
C:\Users\76320\Software\Git\usr\bin\bash.exe
C:\Users\76320>C:\Users\76320\Software\Git\bin\bash.exe

76320@DESKTOP-ALH7QU9 MINGW64 ~
$ python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
```
### Setup

``` 
$ git --version --build-options
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
C:\Users\76320>cmd.exe /c ver

Microsoft Windows [版本 10.0.16299.98]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
C:\Users\76320> type "C:\Users\76320\Software\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

**Comment by dscho** [comment]
This issue is listed specifically in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]
