### ISSUE TITLE
Git BASH : issue using node

### ISSUE THREAD

**Issue by sebdeharlez** [git-for-windows/git#1394]
My .js files do not "print" themselves in the command (using console.log()). Moreover from the moment I enter a  node instruction on Git Bash, I cant see what the terminal writes anymore. However after typing the command and pressing enter, the command execute itself anyway. 
Looks like I type in sort of "invisible mode". 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit. 

$ git --version --build-options

** insert your machine's response here **
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
Editor Option: Nano
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
BASH

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
NODE 

 - What did you expect to occur after running these commands?

enter node mode

 - What actually happened instead?

waited about 3sec. Then got my $ sign again. Everything I type from now one does not appear on the screen.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by landstander668** [comment]
Have you tried running it under *winpty* (e.g. `winpty NODE`)? Node is mentioned specifically in the release notes as requiring this workaround when invoked under MinPTY (which is what *Git Bash* uses).

**Comment by sebdeharlez** [comment]
Hi, 
I just tried it. Unfortunately, it doesn't resolve the problem. Thanks anyway for the tip!

**Comment by dscho** [comment]
Try reinstalling Git for Windows, selecting the native Windows console instead of MinTTY on the page that says "Configuring the terminal emulator to use with Git Bash" in its title.

**Comment by sebdeharlez** [comment]
It works! Thanks a lot!

**Comment by emanshukry** [comment]
it doesn't working
