### ISSUE TITLE
Screen buffer size scroll down issue

### ISSUE THREAD

**Issue by nguyendviet** [git-for-windows/git#1395]
The cursor does not set the bottom of the terminal window (like in OSX or Linux), I can scroll down "infinitely" (the height of the screen buffer size) and use the mouse to click and drag any space below the cursor. This causes extra time looking for the cursor if I need to scroll up long rows of commands and their results, then need to scroll down.

![gitbash window](https://i.stack.imgur.com/9Tdrs.png)

In OSX or Linux, you cannot scroll down past the cursor. There's no good reasons to leave empty spaces under the cursor. I've tried editing Screen Buffer Size but it will just resize the whole window, then I cannot scroll up past the height of the screen buffer size.

I'm using Windows 10 Home. Git Bash version 2.13.2.windows.1

**Comment by dscho** [comment]
It is unclear from this description, as well as from the screenshot what options you are using, and even which window this is. Git CMD? Git Bash? MinTTY/ConHost?

**Comment by nguyendviet** [comment]
Sorry for the confusion. It's git bash.

**Comment by dscho** [comment]
> It's git bash.

That still does not answer the question whether you chose MinTTY or ConHost as Terminal for Git Bash.

I have to admit that it would really be quite a bit more pleasant if the information flow was more... voluntary. I don't like to beg for every little piece of information. And *I* am the one who is supposed to be the on helping, not asking.

**Comment by nguyendviet** [comment]
It's conhost.

I had to do some google searches to find out how to check it. didn't mean to cause you troubles.

**Comment by dscho** [comment]
> I had to do some google searches to find out how to check it.

I could have checked it for you if the bug reporting template had been filled out... there is this `install-options.txt` thing that contains that information.

As it is, this is the expected operation of ConHost, which is the built-in Windows Console. There *might* be options to override this behavior (although I am not aware of it), but that is outside the context of this here bug tracker.
