### ISSUE TITLE
SET is displaying environment variables and data that should not be displayed

### ISSUE THREAD

**Issue by Polostor** [git-for-windows/git#1397]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not really

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

mintty 2.8.1, Cmd

 - What commands did you run to trigger this issue? 

```
set
```
 - What did you expect to occur after running these commands?

Just **Windows environment variables**

 - What actually happened instead?

**Windows environment variables** and **git implemenation** (starting with methods `__git() {...}`, `__git_aliased_command() {...}`  and ending with methods `_gitk() {...}`, `profile_d () {...}`).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Nope, basic `set` did the trick. To see the difference just compare with **cmd**'s `set` and **bash** `set`.

**Comment by dscho** [comment]
This does not look right. When I call *Git CMD* from the Start Menu, `set` lists only the environment variables.

However, when I call *Git Bash* from the Start Menu and then call `set`, it looks like what you describe.

And it is even expected, because the call in a Bash to see the environment variables is actually `env`, not `set`. The `set` command is supposed to show all that stuff that you are seeing.
