### ISSUE TITLE
Git 2.15 terribly hangs on Windows 10

### ISSUE THREAD

**Issue by deathaxe** [git-for-windows/git#1398]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
https://github.com/git-for-windows/git/releases/tag/v2.15.1.windows.2

Can't provide `git --version` output as I already downgraded to git 2.14.2
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]

Windows 10 Pro 1703 x64
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

  Nothing special. Git was working fluently up to 2.14.2

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
CMD, GitExtensions, Sublime Text 3 (GitSavvy / GitGutter)
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
GitGutter runs
   git --version
   git cat-file --filters
   git ls-file --other --exclude-standard
   git -c color.status=never status -b -s -u

Not sure about the detailed command GitExtensions and GitSavvy package are using.

```
 - What did you expect to occur after running these commands?

```
The commands should finish within a reasonable time.
```

 - What actually happened instead?

```
Especially GitExtensions and Sublime Text which interact with git hang up to 5 seconds causing windows to realize them as "Not responding".

As the issue exists with all applications and only with git 2.15 I blame git for it.

GitExtensions abnormal long to built/update the history list and read the diffs and file contents.

Same with GitSavvy package. Opening the "git: status" dashboard from within Sublime Text as well as staging/commiting takes horribly long.

Sublime Text freezes from time to time with GitGutter enabled.

It feels like deadlocks when accessing the tree. I tried with both `GIT_OPTIONAL_LOCKS` set to 0 and 1.

A simple downgrade to 2.14.2 without any other changes to the system solves the issue for now.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

```
There is no special repository. It happens with all of them, no matter of size.
```

**Comment by dscho** [comment]
> GitGutter runs
> ```
> git --version
> git cat-file --filters
> git ls-file --other --exclude-standard
> git -c color.status=never status -b -s -u
>```
> Not sure about the detailed command GitExtensions and GitSavvy package are using.

This does not reproduce the issue here. Does running those commands reproduce the issue on your end?

In fact, this produces *different* errors here, as `ls-file` is missing the `s`, and the `cat-file` command is missing a parameter.

**Comment by deathaxe** [comment]
The listed commands are known to be used by the GitGutter plugin in several situations. And yes there is a typo in `ls-file` :/  

It does not represent the exact sequence of commands being executed resulting in hanging. The execution of the different command depends on several factors.

As I normally don't use git from the command prompt, I can't tell whether executing those commands from command triggers the behavior or whether it is just an issue caused by stdin/stdout communication between git and GitExtensions/Sublime Text.

Maybe worth mentioning is Sublime Text with GitGutter enabled not to hang on every evaluation but only from time to time. Just as there are race conditions which cause git to stuck sometimes. Not sure it's just a feeling.

Unfortunately I can't provide any details about GitExtensions' way of using git command. It seems to hang much more often, if it needs to read the history, generates file diffs or just reads the content of files from the database.

I already tried to disable firewalls/Anti Virus (Kaspersky)/Windows Defender. Nothing helps.

I just downgraded to git 1.14 without any change to any other application and everything is working smoothly again.

**Comment by dscho** [comment]
> It does not represent the exact sequence of commands being executed resulting in hanging.

Then what is the exact sequence that triggers the error?

> As I normally don't use git from the command prompt, I can't tell whether executing those commands from command triggers the behavior or whether it is just an issue caused by stdin/stdout communication between git and GitExtensions/Sublime Text.

I am afraid that I have to ask you to actually test that, because the closer you can get to reproduce this on your machine yourself, the closer you can get any Git for Windows contributor to reproduce it, which is usually a required step to receive help.

> I just downgraded to git 1.14 without any change to any other application and everything is working smoothly again.

That's one way to resolve your issue. If you are happy with it, you can close this ticket. Otherwise, I fear that you'll have to investigate a bit further to enable anybody else to help effectively.

**Comment by dscho** [comment]
Any chance you can look at those hanging processes with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)?

**Comment by deathaxe** [comment]
Upgraded to Win 10 1709 this weekend and the issue seems to have disappeared. So I guess it was caused by any of the underlying OS interfaces/functions.
