### ISSUE TITLE
Cannot install node version on git-bash terminal while it works fine on git-cmd terminal

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [git-for-windows/git#1399]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
No.
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
git-bash
```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I run a command to install node by using git-bash.exe. 
$ nvm install v.8.9.1

```
 - What did you expect to occur after running these commands?
```
I expect to see the node version 8.9.1 is installed.
```
 - What actually happened instead?
```
$ nvm install v8.9.1
nvm: install v8.9.1 failed!

When I used git-cmd.exe to install the node version, it worked fine. Please see the screenshot of the result on git-bash.exe and git-cmd.exe
```
![image](https://user-images.githubusercontent.com/14726381/33811221-2dbece3c-de64-11e7-9d88-266694688ede.png)

Could you please tell me why it doesn't work when I use git-bash.exe and advise what I may be missing?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No. It is not related to any specific repository.

**Comment by shiftkey** [comment]
@JoeRattanamaneesilp this feels like it's a known MinTTY issue in the [release notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

Does prefixing the command with `winpty` in Git Bash change the behaviour?

**Comment by JoeRattanamaneesilp** [comment]
@shiftkey Thanks for the information.

Yes, it does. I can install node version when I add `winpty` as a prefix.
