### ISSUE TITLE
git 2.15 x86-64 not working on windows 10 latest 

### ISSUE THREAD

**Issue by jackiilong** [git-for-windows/git#1400]
git cannot launch correctly.here is the output:

 bash: /dev/null: No such device or address 
bash: /dev/null: No such device or address

cannot get other info from command line .

**Comment by dscho** [comment]
This is all the information that is available? That is not enough to make any sense of this bug report, unfortunately.

Please note that we have put considerable care into providing a bug reporting template, with the idea that the template will help craft a report that should have enough information to at least ask informed further questions. It would be wise to imitate that care instead of casting it aside.

**Comment by Charleskie** [comment]
fatal: open /dev/null or dup failed: No such file or directory

My pc system is win 10, and I hava this trouble

**Comment by dscho** [comment]
> This is all the information that is available? That is not enough to make any sense of this bug report, unfortunately.

Same goes for your report, @Charleskie, I am afraid. There is not enough information in there for me to help.

**Comment by Charleskie** [comment]
![_20180103162120](https://user-images.githubusercontent.com/29321113/34513218-1da3f680-f0a2-11e7-8c91-cd299a2de812.png)

**Comment by dscho** [comment]
@Charleskie I am not kidding: these little bits and pieces thrown at me are not helpful, they only make me want to stay away from this ticket.

If you want to receive high-quality help, you should consider providing a high-quality bug report. Including, at the *bare* minimum the specifics about your setup, your Git for Windows version, the options chosen during the installation, i.e. pretty much the blanks in the [issue reporting template](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by sharegame** [comment]
fatal: open /dev/null or dup failed: No such file or directory
same problem as @Charleskie
system :win10x64 10.0.16299.192
git:Git-2.15.1.2-64-bit.exe
and choose all default options during the installation

**Comment by dscho** [comment]
Am I really being unclear?

I need a *lot* more complete information to be able to work on this. Please at least *try* to provide extensive information. Thank you.

**Comment by dscho** [comment]
Also: has any of you had a look at https://github.com/git-for-windows/git/issues/1016?

To me, it looks as if this here ticket were a clear duplicate of that ticket.

**Comment by dscho** [comment]
See also https://cygwin.com/ml/cygwin/2007-03/msg00358.html

**Comment by kgybels** [comment]
@jackiilong @Charleskie @sharegame Could you try opening a command prompt and executing the following:
```
echo test > NUL
sc query Null
```

Here is how that looks on my system:
```
C:\>echo test > NUL

C:\>sc query Null

SERVICE_NAME: Null
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

Please report your results here.

**Comment by dscho** [comment]
@jackiilong @Charleskie @sharegame please do provide this information. You expect us to fix this, right? So you will understand that we expect you to react?

**Comment by dscho** [comment]
Closing this issue because I really feel my time wasted very freely by others here.

**Comment by Charleskie** [comment]
c:\>echo test > NUL
系统找不到指定的文件。

c:\>sc query Null

SERVICE_NAME: Null
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 31  (0x1f)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

This is the report.
I'm so sorry. I went back my hometown for Spring Festival. So I forgot to check my email.

**Comment by Charleskie** [comment]
It's alright that you have no time on this issue. This is my fault. And the issue went away after I reinstalled my PC system. So sorry to bother you.
