### ISSUE TITLE
Git Bash exception

### ISSUE THREAD

**Issue by dingrui37** [git-for-windows/git#1406]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
C:\Users\10106591>cmd.exe /c ver
[0x7FEF79A2BE0] ANOMALY: meaningless REX prefix used
dwInstructionLength:5
Microsoft Windows [版本 6.1.7601]
Win7 64bit

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
Start git bash with a shortcut, but it throws an exception.
Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.
```

**Comment by dscho** [comment]
> ANOMALY: meaningless REX prefix used

This is a bad sign. Can you check whether you run into the [BLODA problems](https://cygwin.com/faq/faq.html#faq.using.bloda)?

**Comment by dscho** [comment]
I am assuming that my [suspicion](https://github.com/git-for-windows/git/issues/1406#issuecomment-355004002) was correct.
