### ISSUE TITLE
git subtree pull should support --no-ff option

### ISSUE THREAD

**Issue by luochen1990** [git-for-windows/git#1408]
- [yes] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
~/.gitconfig

[merge]
	ff = only
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MinTTY

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git remote add foo url/to/github/repo
git checkout -b foo foo master
git pull
git checkout master
git subtree add -P lib/foo --squash foo
# commit & push something to the foo repo here...
git subtree pull -P lib/foo --squash foo master
```
 - What did you expect to occur after running these commands?

A new commit is generated and the subtree is updated.

 - What actually happened instead?

```
fatal: Not possible to fast-forward, aborting.
```

if with `--no-ff` option, then

```
error: unknown option `no-ff'
```

**Comment by PhilipOakley** [comment]
Do you have access to a linux box to test out if this is an upstream problem. It may be that the sub-tree command just doesn't support this properly.

Perhasps an MVCE that includes a demonstration (small) github repo if you want others to test if it is the same for them. (i.e. a specific repo with branch foo..))

**Comment by dscho** [comment]
@luochen1990 hello?

**Comment by luochen1990** [comment]
@dscho Thanks for your attention, I'm not sure what should I do now.

Report an issure to the upstream project git/git ? but it seems not accepting issures from github.

Provide a mvce?  I think I already provided, since this problem is caused by the configuration and commands I executed, not the repo, you can reproduce it on any current repo and foo repo.

**Comment by dscho** [comment]
> I'm not sure what should I do now.

Answer @PhilipOakley's questions?

**Comment by luochen1990** [comment]
Not tested on linux, this chould be an upstream problem.  Anyone can help to verify that?
Maybe I can help to test it on macos .

**Comment by dscho** [comment]
> Anyone can help to verify that?

It would be a ton easier if your MCVE was really a complete example, and not something people had to think deeply about when trying to reproduce. I mean, look at this:

```sh
$ git remote add foo url/to/github/repo
fatal: Not a git repository (or any of the parent directories): .git
```

And this is already happening for the *first* step of the purportedly Minimal, _Complete_, _Verifiable_ Example...

**Comment by luochen1990** [comment]
My fault, It's just a feedback, I think this can be reproduced with any `foo` repo and current repo, but providing a permanent available url for a `foo` repo to reproduce that problem seems too expensive for me. And now I think that it must not be a problem of git-for-windows, maybe it is a problem from the upstream, or a using problem.  so just ignore me.

**Comment by dscho** [comment]
I do think that it is really necessary for you to try to come up with a minimal reproducible example. It needs to reproduce on your machine reliably first, and only then you can assume that it may reproduce elsewhere.

There is just no alternative to being thorough, please understand that. Trying to fudge your way through, probably with the intention of saving time on your side, will most likely have a surprisingly adverse effect: you will have to go back and put in the work anyway, but everything will simply take longer to be resolved.
