### ISSUE TITLE
Git for WindowsXP SP2

### ISSUE THREAD

**Issue by Desmazio** [git-for-windows/git#1411]
Hi, when i download and double click on the file, it says: "This programma requires Windows Service Pack 3 or later". There's a way to download a file that I can use? Thank

**Comment by kostix** [comment]
https://github.com/git-for-windows/git/wiki/FAQ#which-versions-of-windows-are-supported

**Comment by PhilipOakley** [comment]
to extend Konstantin's link

"Git for Windows version 2.10.0 was the last version supporting Windows XP 
and Server 2003."

The V2.10.0 still works! (at least on my little netbook!)
--
philip

----- Original Message ----- 
From: "Konstantin Khomoutov" <notifications@github.com>

> https://github.com/git-for-windows/git/wiki/FAQ#which-versions-of-windows-are-supported
>
