### ISSUE TITLE
Unable to clone svn repositories with svn protocol on Windows10/7

### ISSUE THREAD

**Issue by raymondoyj** [git-for-windows/git#1413]
I try to use `git svn` clone a svn repository which address is begin with `svn://` on Windows10, it say can't create session.But I try again on ubuntu, it is work. 
```
$ git --version
git version 2.15.1.windows.2
$ git svn --version
git-svn version 2.15.1.windows.2 (svn 1.9.7)
$ git svn clone svn://aa.com/bb/xx
Initialized empty Git repository in D:/git/xx/.git/
Can't create session: Unable to connect to a repository at URL 'svn://aa.com/bb/xx' at /mingw64/share/perl5/site_perl/Git/SVN.pm line 148.
```

**Comment by dscho** [comment]
32-bit, 64-bit? Minimal Example I could try to verify that I experience the same issue?

**Comment by raymondoyj** [comment]
64-bit. I try to verify that I run a local svn repository. It works. Maybe it is limited in the network of my company.
