### ISSUE TITLE
Cannot get [ctrl+tab] working

### ISSUE THREAD

**Issue by ahmedmohiduet** [git-for-windows/git#1417]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

My Ctrl+[shift]+tab key combination do not appear to be working properly. I have 8 Git Bash windows open. My 'ctrl+tab' key combinations letting switch me among only 3 Git Bash windows. This behaviour is changing as soon as I am switching to other Git Bash windows using 'alt+tab'. And then my 'ctrl+tab' keys letting me switch among only 4 windows with my newly focused git bash window. Any ideas how can I get around this?

I can't use 'alt+tab' since they bring up a long list of windows with other applications as well

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64 bit

$ git --version --build-options

** insert your machine's response here **
git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64bit
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.10240]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
> type "C:\Program Files\Git\etc\install-options.txt"

Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

![screenshot 2018-01-02 23 20 39](https://user-images.githubusercontent.com/3110101/34492874-a026ee08-f013-11e7-8472-83b11c8b3ba9.png)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
I cannot reproduce the issue here. Ctrl+Tab cycles through all of my MinTTY windows, whether they be from the current Git for Windows installation or from my Git for Windows SDK.

I suspect, though, that this may be an issue with MinTTY... Have you looked at https://github.com/mintty/mintty/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen?

Also, I tested this with Git for Windows v2.16.0-rc0 which comes with the same MinTTY (v2.8.1) as Git for Windows v2.15.1(2) (the latest official release). That is different from the MinTTY version shipped with v2.14.1, which you seem to have: MinTTY v2.7.1.

Care to test with an up-to-date Git for Windows?

**Comment by ahmedmohiduet** [comment]
let me check

**Comment by ahmedmohiduet** [comment]
tried. still same result. I am starting new windows by:
`start "" "C:\Program Files\Git\usr\bin\mintty.exe" -w full "C:\Program Files\Git\bin\bash.exe" --login`

**Comment by dscho** [comment]
I am starting new windows essentially by calling `C:\Program Files\Git\git-bash.exe` (which internally launches `mintty.exe` but also sets things up a bit more properly, e.g. forcing MSYS2 into MINGW mode, setting an AppId, etc). Maybe try that?

**Comment by dscho** [comment]
Did you try that?

**Comment by ahmedmohiduet** [comment]
Hi dscho, sorry on super delay on that. I tried and its not working yet. I had been noticing another rissue is that resuming from hibernate making my other mingw windows not get focesed while pressing ctrl+tab in any ming windows

**Comment by dscho** [comment]
Are you sure that the options are set correctly?

![image](https://user-images.githubusercontent.com/127790/35560512-f174003e-05ad-11e8-9402-d20676e231bd.png)

**Comment by ahmedmohiduet** [comment]
yup. my settings.....
![screenshot 2018-01-30 16 16 29](https://user-images.githubusercontent.com/3110101/35560944-1a61be16-05d9-11e8-85cb-299e37e685be.png)

**Comment by dscho** [comment]
Maybe you could try Git for Windows v2.16.1, which comes with MinTTY 2.8.3.

If in doubt, you can always try a portable Git first, and if it works, upgrade your installation.

**Comment by ahmedmohiduet** [comment]
let me check

**Comment by ahmedmohiduet** [comment]
Hi dscho! I had tried and its not working still.

**Comment by dscho** [comment]
Maybe you can get more help at https://github.com/mintty/mintty/issues, as this really is not a Git-specific issue and I am at the end of my domain knowledge about MinTTY?

**Comment by ahmedmohiduet** [comment]
got it. let me move it at mintty
