### ISSUE TITLE
Properly Color Failed Remote Push Messages

### ISSUE THREAD

**Issue by maplion** [git-for-windows/git#1422]
I have some colleagues that occasionally have issues with Git [in a team setting] simply because they miss the message when a push is made prior to a required pull and they miss the message that it failed to successfully push.  This is because a success shows a block of white text and a failure shows a block of white text.  It would make sense for usability purposes if a `git push origin <branch name>` fails, for example, that the text returned is a different color (e.g. yellow/red).  I tried to find ways to do this in Windows Git Bash and it seems less than trivial -- and I also think it is something that should be built in; so I am requesting this feature.

Example message:
![git-push-message](https://user-images.githubusercontent.com/8908849/34681672-d674ab72-f459-11e7-9cff-a33567434902.JPG)

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options
git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
`git push origin <branch name>` when a pull is required first
```
 - What did you expect to occur after running these commands?

Not relevant

 - What actually happened instead?

Not relevant

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
Not relevant

**Comment by shiftkey** [comment]
@maplion can you attach screenshots of the error messages, for completeness?

Also, I think this might need to be addressed in Git core, rather than Git for Windows. But we can talk about that in more detail later.

**Comment by dscho** [comment]
> It would make sense for usability purposes if a git push origin <branch name> fails, for example, that the text returned is a different color (e.g. yellow/red). I tried to find ways to do this in Windows Git Bash and it seems less than trivial -- and I also think it is something that should be built in; so I am requesting this feature.

That's a good idea.

Please understand that this project is not lacking in feature requests, but seriously lacking in contributors implementing said features.

So here is a New Year's challenge for you: implement the desired feature yourself. It is not witch craft, look at how many contributors succeed in adding their work to Git: https://github.com/git/git/pulse

# Step 1: decide how you want to develop this

There are essentially two options:

- if you are a command-line person: [install Git for Windows' SDK](https://gitforwindows.org/#download-sdk)

- if you are more of an IDE person, [compile Git using Visual Studio](https://github.com/git-for-windows/git/wiki/Compiling-Git-with-Visual-Studio)

# Step 2: identify the code that prints the message you want color-coded

The easiest way is to use `git grep` on a substring of the message, e.g. `git grep 'Could not push'` (I do not know the exact message, you will have to adjust this obviously).

# Step 3: use color

To add color to stuff you print, look at the functions provided by `color.h`, most likely `color_fprintf()` or `color_print_strbuf()` is what you will need.

# Step 4: test locally

Once you build, you should use the Git in-place, which takes a little fiddling:

```sh
/path/to/git/git.exe --exec-path=/path/to/git push ...
```

where `/path/to/git` is the absolute path of the directory where you built Git, e.g. `/c/git-sdk-64/usr/src/git`.

To test this, you probably want to create a toy project using `git init`, add a couple of dummy commits and then clone it to simulate the situation of your co-workers.

# Step 5: contribute

Open a Pull Request and earn glory ;-)

# Questions?

If there is anything unclear, do not hesitate to ask away. Once you have code to show, a Pull Request will do fine (mark it as [Do not merge yet]), before that this here ticket will do just fine.

**Comment by maplion** [comment]
@shiftkey Yes, I thought that might be the case, but since I am primarily using Git for Windows, I figured I'd start here and work up if needed.

**Comment by maplion** [comment]
@dscho Thank you for the information.  If I get a spot of free time, I'll take you up on your challenge.

**Comment by maplion** [comment]
@dscho I am having difficulty in building my project.  I went with the IDE option running it in Visual Studio with the solution file.  With a fresh pull (no changes), it doesn't seem to recognize a lot of identifiers, such as stderr, time_t, FILE, SSL, DWORD, etc., etc.  Is there a library or something I am missing?  I thought it had me install what it needed when I first loaded the solution.  Any recommendations on how to resolve this?

![capture](https://user-images.githubusercontent.com/8908849/34928627-2694d8c6-f97c-11e7-90ff-08901cf48662.PNG)

**Comment by PhilipOakley** [comment]
@maplion Which of the steps had you done, and which not? 

I'm suspecting that you may need something that is downloaded via the SDK, even though you are using the Visual Studio build process. It (compiling) will depend on the state of the repository work tree, and if bits are 'missing' they maybe part of the SDK's download (most contributors at some time or other have downloaded the SDK, so that may be where the mising definitions are hidden).

Philip

**Comment by maplion** [comment]
How do I run the test suite?

**Comment by maplion** [comment]
Also, could someone explain the documentation and how to properly contribute to it in my case [not sure how this particular change would be relevant to the documentation I am seeing]?

**Comment by maplion** [comment]
How do I create a production-like build so I can use it in the mean time?

**Comment by kgybels** [comment]
>@maplion How do I create a production-like build so I can use it in the mean time?

Check the [Making an installer](git-for-windows/git/wiki/Making-an-installer) and [Making a portable Git](git-for-windows/git/wiki/Making-a-portable-Git) topics on the wiki, both methods require you to install the Git for Windows SDK though.

I think it would also work to install a Git for Windows release, and then copy a release build over the provided git.exe. However, do keep in mind that there are lots of files hardlinked to it, so you might need to update those as well.

**Comment by maplion** [comment]
@kgybels thank you again.  I will try out the SDK for the learning experience, if nothing else.

**Comment by michaelblyons** [comment]
Coming v2.18.0? 😃 https://github.com/git/git/commit/a56fb3dcc09239795823de40ffcbbf5713114eb5

**Comment by dscho** [comment]
Yaaaaay! It only took, what, [3 iterations](https://github.com/dscho/git/releases/tag/colorize-push-errors-v3) to get it into core Git...
