### ISSUE TITLE
Git hangs on interactive rebase command (Windows 10 Enterprise 1709)

### ISSUE THREAD

**Issue by mvmalygin** [git-for-windows/git#1424]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
64-bit

$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Windows 10 Enterprise 64-bit

$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
I was choosing defaults

$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Windows 10 Enterprise has resently updated

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rebase -i HEAD~2
```
 - What did you expect to occur after running these commands?

I expected for proper interactive rebase process

 - What actually happened instead?

It has hanging. No response until <Ctrl+C> is pressed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, it does not depend on specific repo.

**Comment by dscho** [comment]
This issue does not reproduce here at all, so you will have to look a bit deeper on your side (as it only reproduces on your system)...

Maybe executing it with `GIT_TRACE=1` will make it more obvious what is going wrong? Or with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)?

**Comment by mvmalygin** [comment]
There is some looping:
 GIT_TRACE=1 git rebase -i HEAD~2
22:35:30.178986 git.c:576               trace: exec: 'git-rebase' '-i' 'HEAD~2'
22:35:30.178986 run-command.c:626       trace: run_command: 'git-rebase' '-i' 'HEAD~2'
22:35:30.699754 git.c:344               trace: built-in: git 'rev-parse' '--git-dir'
22:35:30.824750 git.c:344               trace: built-in: git 'rev-parse' '--git-path' 'objects'
22:35:30.902885 git.c:344               trace: built-in: git 'rev-parse' '--is-bare-repository'
22:35:30.965407 git.c:344               trace: built-in: git 'rev-parse' '--show-toplevel'
22:35:31.059123 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.stat'
22:35:31.137252 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autostash'
22:35:31.215406 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autosquash'
22:35:31.277875 git.c:344               trace: built-in: git 'config' '--bool' 'commit.gpgsign'
22:35:31.902894 git.c:344               trace: built-in: git 'rev-parse' '--git-dir'
22:35:32.027890 git.c:344               trace: built-in: git 'rev-parse' '--git-path' 'objects'
22:35:32.090392 git.c:344               trace: built-in: git 'rev-parse' '--is-bare-repository'
22:35:32.152890 git.c:344               trace: built-in: git 'rev-parse' '--show-toplevel'
22:35:32.262232 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.stat'
22:35:32.356028 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autostash'
22:35:32.418510 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autosquash'
22:35:32.496617 git.c:344               trace: built-in: git 'config' '--bool' 'commit.gpgsign'
...
and so on

**Comment by dscho** [comment]
Is there *any* chance to get you to work on providing a [Minimal, Complete & Verifiable Example](https://stackoverflow.com/help/mcve)?

The information so far leaves me more puzzled than anything else...

**Comment by kgybels** [comment]
I think this in another case of DLL injection causing problems, see issue #1153.

@mvmalygin Can you try [tanmatra's example](https://github.com/git-for-windows/git/issues/710#issuecomment-205323939):
`count=$(cat "/etc/fstab" | wc -l); echo count=$count`

Here is what it should look like:
```
$ count=$(cat "/etc/fstab" | wc -l); echo count=$count
count=6
```

However, if my guess is right, you will not get any output.

---

More information about my investigation:
Here is what my trace looks like for `GIT_TRACE=1 git rebase -i HEAD~2`:
```
$ GIT_TRACE=1 git rebase -i HEAD~2
21:53:03.677464 git.c:576               trace: exec: 'git-rebase' '-i' 'HEAD~2'
21:53:03.677464 run-command.c:626       trace: run_command: 'git-rebase' '-i' 'HEAD~2'
21:53:03.958715 git.c:344               trace: built-in: git 'rev-parse' '--parseopt' '--stuck-long' '--' '-i' 'HEAD~2'
21:53:04.099340 git.c:344               trace: built-in: git 'rev-parse' '--git-dir'
21:53:04.193090 git.c:344               trace: built-in: git 'rev-parse' '--git-path' 'objects'
21:53:04.255591 git.c:344               trace: built-in: git 'rev-parse' '--is-bare-repository'
21:53:04.318090 git.c:344               trace: built-in: git 'rev-parse' '--show-toplevel'
21:53:04.396216 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.stat'
21:53:04.474341 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autostash'
21:53:04.536841 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autosquash'
21:53:04.599341 git.c:344               trace: built-in: git 'config' '--bool' 'commit.gpgsign'
21:53:04.677466 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD~2^0'
21:53:04.755591 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD~2^0'
21:53:04.818091 git.c:344               trace: built-in: git 'symbolic-ref' '-q' 'HEAD'
21:53:04.927466 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
21:53:05.005592 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
21:53:05.068092 git.c:344               trace: built-in: git 'update-index' '-q' '--ignore-submodules' '--refresh'
21:53:05.130592 git.c:344               trace: built-in: git 'diff-files' '--quiet' '--ignore-submodules'
21:53:05.193092 git.c:344               trace: built-in: git 'diff-index' '--cached' '--quiet' '--ignore-submodules' 'HEAD' '--'
21:53:05.239967 git.c:344               trace: built-in: git 'merge-base' '6eabf84042f1d173f38ae56e645fecb2fcaad9f2' '27c86da744817d30aa9ef2bcbf52e4c9cff18044'
21:53:05.302467 git.c:344               trace: built-in: git 'rev-parse' '--git-path' 'hooks/pre-rebase'
21:53:05.505592 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
21:53:05.630592 git.c:344               trace: built-in: git 'rev-parse' '--short' '27c86da744817d30aa9ef2bcbf52e4c9cff18044'
21:53:05.708718 git.c:344               trace: built-in: git 'rev-parse' '--short' '6eabf84042f1d173f38ae56e645fecb2fcaad9f2'
21:53:05.802468 git.c:344               trace: built-in: git 'rev-parse' '--short' '6eabf84042f1d173f38ae56e645fecb2fcaad9f2'
21:53:05.849343 git.c:344               trace: built-in: git 'rebase--helper' '--make-script' '6eabf84042f1d173f38ae56e645fecb2fcaad9f2...27c86da744817d30aa9ef2bcbf52e4c9cff18044'
21:53:05.911843 git.c:344               trace: built-in: git 'rebase--helper' '--rearrange-squash'
21:53:06.005593 git.c:344               trace: built-in: git 'stripspace' '--strip-comments'
21:53:06.193094 git.c:576               trace: exec: 'git-sh-i18n--envsubst' '--variables' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
21:53:06.193094 run-command.c:626       trace: run_command: 'git-sh-i18n--envsubst' '--variables' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
21:53:06.286844 git.c:576               trace: exec: 'git-sh-i18n--envsubst' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
21:53:06.286844 run-command.c:626       trace: run_command: 'git-sh-i18n--envsubst' 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
21:53:06.443093 git.c:344               trace: built-in: git 'stripspace' '--comment-lines'
21:53:06.552469 git.c:344               trace: built-in: git 'config' '--get' 'rebase.missingCommitsCheck'
21:53:06.708720 git.c:344               trace: built-in: git 'stripspace' '--comment-lines'
21:53:06.786845 git.c:344               trace: built-in: git 'stripspace' '--comment-lines'
21:53:06.880595 git.c:344               trace: built-in: git 'stripspace' '--strip-comments'
21:53:06.989970 git.c:344               trace: built-in: git 'rebase--helper' '--shorten-ids'
21:53:07.068096 git.c:344               trace: built-in: git 'config' 'sequence.editor'
21:53:07.161845 git.c:344               trace: built-in: git 'var' 'GIT_EDITOR'
21:53:09.458724 git.c:344               trace: built-in: git 'stripspace' '--strip-comments'
21:53:09.521225 git.c:344               trace: built-in: git 'rebase--helper' '--check-todo-list'
21:53:09.583725 git.c:344               trace: built-in: git 'rebase--helper' '--expand-ids'
21:53:09.661849 git.c:344               trace: built-in: git 'rebase--helper' '--skip-unnecessary-picks'
21:53:09.818100 git.c:344               trace: built-in: git 'update-ref' 'ORIG_HEAD' '27c86da744817d30aa9ef2bcbf52e4c9cff18044'
21:53:09.880600 git.c:344               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
21:53:09.943100 git.c:344               trace: built-in: git 'update-index' '-q' '--ignore-submodules' '--refresh'
21:53:10.005600 git.c:344               trace: built-in: git 'diff-files' '--quiet' '--ignore-submodules'
21:53:10.052475 git.c:344               trace: built-in: git 'diff-index' '--cached' '--quiet' '--ignore-submodules' 'HEAD' '--'
21:53:10.099350 git.c:344               trace: built-in: git 'rebase--helper' '--continue'
Successfully rebased and updated refs/heads/master.
```

When the editor came up, I left everything set to pick.

Notice how the third line of my trace is missing in the problematic trace:
```
22:19:28.205861 git.c:344               trace: built-in: git 'rev-parse' '--parseopt' '--stuck-long' '--' '-i' 'HEAD~2'
```

That trace output belongs to the following command being executed at [git-sh-setup.sh#L83](https://github.com/git-for-windows/git/blob/v2.15.1.windows.2/git-sh-setup.sh#L83):
```
	eval "$(
		echo "$OPTIONS_SPEC" |
			git rev-parse --parseopt $parseopt_extra -- "$@" ||
		echo exit $?
	)"
```

That code is structured similarly as the test example.

Additionally I noticed that the following four lines:
```
21:53:04.396216 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.stat'
21:53:04.474341 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autostash'
21:53:04.536841 git.c:344               trace: built-in: git 'config' '--bool' 'rebase.autosquash'
21:53:04.599341 git.c:344               trace: built-in: git 'config' '--bool' 'commit.gpgsign'
```

Correspond to the code at [git-rebase.sh#L73-L74](https://github.com/git-for-windows/git/blob/v2.15.1.windows.2/git-rebase.sh#L73-L74) and [git-rebase.sh#L92-L93](https://github.com/git-for-windows/git/blob/v2.15.1.windows.2/git-rebase.sh#L92-L93), which seems to imply that the above problem is causing the `git-rebase` script to recurse.

**Comment by mvmalygin** [comment]
@kgybels You're right. Output is empty:
```
count=$(cat "/etc/fstab" | wc -l); echo count=$count
count=
```
But I do not fully understand, how to fix the problem.
I will try to uninstall my COMODO Internet Security just later.

**Comment by mvmalygin** [comment]
@kgybels Thanks. I will report about result.

**Comment by mvmalygin** [comment]
After removing of COMODO software, Git began to function normally.
However, both turning it off and exclusions tuning, have no any effect. Full uninstall only!
Thank to @kgybels and all the others!

**Comment by kgybels** [comment]
@mvmalygin I'm glad to hear you were able to resolve your issue. Can you please close the issue report?
