### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git (but .git exists)

### ISSUE THREAD

**Issue by sryze** [git-for-windows/git#1428]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git 2.15.1.windows.2
 - 64-bit
 - Windows 10

```
$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.192]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

I copied my repository from one Windows machine to another (which has a newer version of Windows 10), and on the second system I'm getting this error. The `.git` directory exists. Both repos were on an NTFS drive.

I actually used [Syncthing](https://syncthing.net/) (a P2P file sync tool) to sync the two repositories. I'm not sure if it could damage the repo while copying.

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash, cmd.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status
```

 - What did you expect to occur after running these commands?

Repository status

 - What actually happened instead?

```
$ git status
fatal: Not a git repository (or any of the parent directories): .git

$ ls .git
COMMIT_EDITMSG  description  HEAD   index  logs     ORIG_HEAD    refs      sourcetreeconfig  tortoisegit.index
config          FETCH_HEAD   hooks  info   objects  packed-refs  rr-cache  tortoisegit.data  worktrees
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Sorry, it's a private repository.

**Comment by sryze** [comment]
For some odd reason the `git/HEAD` and `.git/index` files contained a bunch of zeros instead of whatever should have been there. After I deleted `.git/index` and added `ref: refs/heads/master` to `.git/HEAD` I was able to use the repository again.

**Comment by dscho** [comment]
That sounds as if the Syncthing did not copy the files correctly?

**Comment by sryze** [comment]
Sounds like it.
