### ISSUE TITLE
/tmp is not mounted to %TEMP%

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#143]
It used to be in MsysGit.

**Comment by PhilipOakley** [comment]
There has been quite some discussion around the tmp/TEMP directories you may want to look at in the various issue/PR discussions. e.g. #123 

How is this affecting you (do you have an example to help with a Minimal, Complete and Verifiable Example ;-)

**Comment by PhilipOakley** [comment]
For searching, try putting "%TEMP% in:title,body" in the filter box of the issues page (you (& I) learn something every day) or "%TEMP% in:title,body,comment" etc. See the https://help.github.com/articles/searching-issues/ page for some examples

**Comment by dscho** [comment]
Since `%TEMP%` is user-dependent, I am not quite sure how that would be encoded properly in an `fstab` (the file where drive mappings are specified for Cygwin/MSys2). There might already be an option for that, or it will require appropriate changes in [`msys-2.0.dll`](https://github.com/git-for-windows/msys2-runtime) -- accompanied by the corresponding [change in the `git-extra` package](https://github.com/git-for-windows/build-extra/blob/03c5556d5ae48d7184da6e1aca7dfca82eab3778/git-extra/git-extra.install.in#L16).

@orgads if you are interested in tackling this, please have a look at [this description how to build the MSys2 runtime ("`msys-2.0.dll`")](https://github.com/git-for-windows/git/wiki/Building-msys2-runtime) first.

**Comment by dscho** [comment]
@orgads I was hoping to interest you in this issue, so I implemented a very first version of a topic branch to help with this issue, but I need your help now: could you have a look, test, and see whether you can do something about the output of `mount.exe` when called without arguments?

**Comment by orgads** [comment]
@dscho Thanks for your efforts. I'm sorry for not being responsive lately. I was loaded with work.

I'll try to get to this on next Monday.

**Comment by dscho** [comment]
@orgads thanks. Please note that my current plan is to release Git for Windows on Monday.

**Comment by dscho** [comment]
@orgads out of curiosity: did you work on this yet?

**Comment by orgads** [comment]
I won't have time today. Hopefully tomorrow. Let's leave it for the next
release.
בתאריך 25 במאי 2015 3:21 אחה״צ,‏ "dscho" <notifications@github.com> כתב:

**Comment by dscho** [comment]
I just merged an updated version of https://github.com/git-for-windows/msys2-runtime/pull/9. It lists `/tmp/` correctly in the `mount` output.

**Comment by orgads** [comment]
Great!

I actually tried to build msys2-runtime but couldn't get it to compile (some fpermissive errors...)

**Comment by dscho** [comment]
You have to build it from the *MSys2* shell, i.e. start `C:\git-sdk-64\msys2_shell.bat`. Otherwise you are in a MINGW instead of an MSYS build environment.

**Comment by orgads** [comment]
That's what I did. It starts building fine, but after a few minutes I'm getting many errors such as:

```c++wrap -pipe -O2 -g -ggdb -fno-rtti -fno-exceptions -fno-use-cxa-atexit -Wall -Wstrict-aliasing -Wwrite-strings -fno-common -pipe -fbuiltin -fmessage-length=0 -MMD -Werror -fmerge-constants -ftracer -mcmodel=small -c -o dlfcn.o /usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime/winsup/cygwin/dlfcn.cc
In file included from ./globals.h:6:0,
                 from /usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime/winsup/cygwin/winsup.h:311,
                 from /usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime/winsup/cygwin/debug.cc:11:
/usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime/winsup/cygwin/winsup.h:192:45: error: default argument given for parameter 1 of 'void close_all_files(bool)' [-fpermissive]
 void __stdcall close_all_files (bool = false);```

**Comment by dscho** [comment]
Oh, *slaps-his-head*. To build the `msys2-runtime`, actually, any MSys2 package, you need to call

```sh
pacman -Sy base-devel binutils
```

once, to initialize the build system.

**Comment by orgads** [comment]
@dscho Thanks. I already did that. I'm building by running makepkg in msys2-runtime directory in MSYS2-packages. Should I use something else?

**Comment by dscho** [comment]
no, that's correct. Maybe your `PATH` is wrong? What does `which c++wrap.exe` say?

**Comment by orgads** [comment]
which: no c++wrap.exe in (...my path...)

**Comment by dscho** [comment]
Hmm, neither is it in the PATH here. So that means that something went wrong at configure time.

**Comment by dscho** [comment]
Okay, so this is the output here:

```sh
$ echo $MSYSTEM
MSYS
$ uname -a
MSYS_NT-6.3 dscho 2.1.2(0.288/5/3) 2015-05-25 15:48 x86_64 Msys
$ cd  /usr/src/MSYS2-packages/msys2-runtime/src/build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin
$ rm -f dlfcn.o && make dflcn.o
c++wrap -pipe -O2 -g -ggdb -fno-rtti -fno-exceptions -fno-use-cxa-atexit -Wall -Wstrict-aliasing -Wwrite-strings -fno-common -pipe -fbuiltin -fmessage-length=0 -MMD -Werror -fmerge-constants -ftracer -mcmodel=small -c -o dlfcn.o /usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime/winsup/cygwin/dlfcn.cc
```

And it works correctly here, obviously... Maybe you can spot differences in your setup?

**Comment by orgads** [comment]
It's exactly the same.

```
gcc --version
gcc (GCC) 4.9.2
```

Yours?

**Comment by dscho** [comment]
```sh
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/4.9.2/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /build2/gcc/src/gcc-4.9.2/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --disable-multilib --with-tune=generic --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib
Thread model: posix
gcc version 4.9.2 (GCC)
```

**Comment by orgads** [comment]
Finally found the reason for the compilation error: https://github.com/git-for-windows/msys2-runtime/pull/12
