### ISSUE TITLE
Link to download latest version is broken

### ISSUE THREAD

**Issue by Cogito** [git-for-windows/git#1434]
Looking at https://gitforwindows.org/ and clicking the link 'Download' directs me to the following URL which 404s:

https://github.com/git-for-windows/git/releases/download/v2.16.0.windows.2/Git-2.16.0-64-bit.exe

It appears as though this is meant to be:

https://github.com/git-for-windows/git/releases/download/v2.16.0.windows.2/Git-2.16.0.2-64-bit.exe

This is potentially related to #1433 but might be worth fixing in the meantime as it breaks the download functionality.

**Comment by shiftkey** [comment]
@Cogito can you re-test? I think this is working fine now.

**Comment by Cogito** [comment]
@shiftkey I am currently seeing the following, broken URL when clicking the link:

https://github.com/git-for-windows/git/releases/download/v2.16.0.windows.2/Git-2.16.0-64-bit.exe

**Comment by shiftkey** [comment]
@Cogito aha, I was testing it on a non-Windows OS. There's something in [this code](https://github.com/git-for-windows/git-for-windows.github.io/blob/master/index.html#L125-L136) that isn't detecting the right version values.

**Comment by Cogito** [comment]
@shiftkey Yes, that code is assuming the release artefact will be called 2.16.0, not 2.16.0.2

That's why I think the root cause is #1433 

The fix, I think, is to either

1. Publish release artefacts with the correct name
2. Change the 'version' on the gitforwindows.org page to be 2.16.0(2) rather than 2.16.0, until the correctly named artefact is released.

**Comment by Cogito** [comment]
The commit which broke the link is this one: https://github.com/git-for-windows/git-for-windows.github.io/commit/ae93ce6cf0b1e36eeceb7d070cc2469934b15f2c

**Comment by dscho** [comment]
For the record, a PR would have been nice (I could have accepted that on my phone instead of cutting into vacation time and whipping out the laptop).

**Comment by shiftkey** [comment]
@dscho apologies for the interruption!

**Comment by dscho** [comment]
@shiftkey no apologies necessary. Does the link work now?

**Comment by shiftkey** [comment]
@dscho all good here!

<img width="1009" src="https://user-images.githubusercontent.com/359239/35175247-9c5afc30-fd27-11e7-957f-5920519373e4.png">
