### ISSUE TITLE
How to disable SSH agent login warning?

### ISSUE THREAD

**Issue by GuiAlmeida** [git-for-windows/git#1436]
after I installed git, this annoying warning appears, I wanted to disable it, it did not appear in the old days.

![1](https://user-images.githubusercontent.com/5199435/35162821-a7e5a6b4-fd2b-11e7-96f0-289771cff85a.PNG)
![capturar](https://user-images.githubusercontent.com/5199435/35162822-a811e896-fd2b-11e7-934e-e2f4c2c9c173.PNG)

**Comment by dscho** [comment]
Please provide enough information. It is in general a very wise idea to fill out a carefully-crafted issue reporting template such as ours.

Git for Windows does not start the `ssh-agent` by default. You must have added that in your `~/.bash_brofile` or something.
