### ISSUE TITLE
Artemis Trojan in PortableGit-2.4.0.2-dev-preview-64-bit

### ISSUE THREAD

**Issue by radum** [git-for-windows/git#144]
Just downloaded `PortableGit-2.4.0.2-dev-preview-64-bit.7z.exe` from Github and my McAfee antivirus sees `cygwin-console-helper.exe` as `Trojan Artemis!3F7862F17BA9`.

I guess this is a false positive for sure but still it should be addressed.

I can help with testing.

**Comment by nalla** [comment]
See [issue#113](https://github.com/git-for-windows/git/issues/113)

**Comment by radum** [comment]
Yeah sorry my bad for no searching issues properly. I only searched for Artemis.

This can be closed now.
