### ISSUE TITLE
Git Worktree Broken in 2.16.0

### ISSUE THREAD

**Issue by KellyDeveloped** [git-for-windows/git#1440]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** PS F:\git-test> git --version --build-options
git version 2.16.0.windows.2
cpu: x86_64
built from commit: a56c4f9e2a9513d2be57dc4346e0e84887399cd9
sizeof-long: 4 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.16299.192] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** N/A **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** PowerShell, CMD **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**  PS F:\git-test> git init
Initialized empty Git repository in F:/git-test/.git/
PS F:\git-test> echo "test file" > test.txt
PS F:\git-test> git add test.txt
PS F:\git-test> git commit -m "Test Commit"
[master (root-commit) 3db9464] Test Commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt
PS F:\git-test> git worktree add -b branch test
Preparing test (identifier test)
error: unable to stat just-written file test.txt: No such file or directory
fatal: Could not reset index file to revision 'HEAD'. **
```
 - What did you expect to occur after running these commands?

** I expected two things to have happened - a new branch named "branch" to have been created, and for it to be viewable in a folder named "test" **

 - What actually happened instead?

** Instead, the command threw an error saying

error: unable to stat just-written file test.txt: No such file or directory
fatal: Could not reset index file to revision 'HEAD'. 

This meant that the folder containing the branch was not made.

This branch  CAN be checked out using the git checkout command without issue. But cannot be  used as a worktree **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** N/A - this occurs on multiple repositories **

**Comment by atetubou** [comment]
Sorry, I confirmed my commit fcba80a2696c48fba77dd2ab3810092476e36fc2 introduced this regression. This commits also caused similar issue #1437
@dscho please revert this.

**Comment by KellyDeveloped** [comment]
How long will it take for a patch/revert to come out? Just so I know whether to roll back to a previous version or wait.

**Comment by PhilipOakley** [comment]
There are upstream breakages as well that probably hit some GfW repos as well, plus @dscho is currently on an well earned vacation. So a maintenance release could be a a week or two away.

@atetubou could you create a PR that does the revert? That way @dscho can apply it easily.

**Comment by atetubou** [comment]
@PhilipOakley sure.
