### ISSUE TITLE
git clone https://... failed with error "SSL_CTX_set_alpn_protos not found"

### ISSUE THREAD

**Issue by Maximus5** [git-for-windows/git#145]
Just unpacked newly downloaded `PortableGit-2.4.0.2-dev-preview-64-bit.7z.exe`. Trying to clone https repository and get an error message and a crash later.
OS: Windows 8.1 x64 (russian)

> git clone https://github.com/Maximus5/git-bug-3-main.git
> Клонирование в «git-bug-3-main»…

The error message (translated from russian)

    git-remote-https.exe - Entry point not found
    ----
    Entry point procedure SSL_CTX_set_alpn_protos not found
    in DLL T:\Utils\Lans\GIT\mingw64\bin\libcurl-4.dll. 

After that a crash message appears

    [Window Title]
    Git for Windows
    [Main Instruction]
    Git for Windows has stopped working
    [Content]
    A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.
    [Close program]

That happens from `git-cmd.exe` (started in standard Windows terminal, no ConEmu).

If I try to run same command from `git-bash.exe` - it just prints `Клонирование в «git-bug-3-main»…` and returns to prompt immediately without showing any more errors.

Build `git version 2.3.5.windows.8` did not have that problem.

BTW. I strongly dislike russian in any output of programming tools. Why? Who needs it? Previous builds works fine for me.

**Comment by elieux** [comment]
Issue #133 seems to be tangentially related (it's the same type of failure, but probably for different reasons). I'll post more if I find out anything useful.

> I strongly dislike russian in any output of programming tools. Why? Who needs it? Previous builds works fine for me.

I assume GfW ships with all Git translations and a correct locale detection. You can override the detection by setting the environment variable `LANG` to `en_US.UTF-8`. You can do this globally (either for your account, or for the whole system) in the System control panel.

**Comment by Maximus5** [comment]
Setting LANG variable changes output to English. Thanks!

**Comment by elieux** [comment]
Is `T:\Utils\Lans\GIT` where you installed GfW? Was there an older version present? I tried downloading and installing the exact version you mentioned in your post and I don't see any problems. It looks like a conflict between different versions of DLLs, due to `PATH` pollution or an upgrade gone wrong.

**Comment by Maximus5** [comment]
Yes, `T:\Utils\Lans\GIT` is installation location. This directory was clear before unpacking downloaded portable. Trying to check `PATH`...

**Comment by elieux** [comment]
An easy way to check would be to open a command prompt, `set PATH=` and then launch `git-cmd` from that window. This should result in a fairly clear `PATH` to test with.

**Comment by Maximus5** [comment]
Checked both 32-bit and 64-bit versions. Installed in clear folders. Both produce this errors.

**x64 version**
![2015-05-12_03-02-43](https://cloud.githubusercontent.com/assets/1222388/7577637/56f369c4-f853-11e4-885e-467c82588ca5.png)

**x32 version**
![2015-05-12_02-58-46](https://cloud.githubusercontent.com/assets/1222388/7577598/c33a108e-f852-11e4-8cc1-dd7708d0afab.png)
![2015-05-12_03-00-20](https://cloud.githubusercontent.com/assets/1222388/7577612/ff977fbc-f852-11e4-89b9-c073565e69a0.png)

**Comment by Maximus5** [comment]
OK. Testing 32-bit version. Just ran `git-remote-https.exe` from `git-cmd` prompt, added `T:\Temp\x86\mingw32\bin` to the `PATH`.
Entry point not found and crash.

Copied `libcurl-4.dll` from old installation. `git-remote-https.exe` successfully started.

**Comment by elieux** [comment]
This is really weird. Are you running some anti-malware software that could be modifying the DLL after installation?

**Comment by elieux** [comment]
Maybe post MD5 sums of the files in your `mingw64` directory, so we can compare?

**Comment by Maximus5** [comment]
Current (bad) from 2.4.0.w.2 32-bit libcurl-4.dll, size 511834 bytes, md5 6e97157e49b9500bf44871557f6d504e
Old (good) from 2.3.5.w.8 32-bit libcurl-4.dll, size 506175 bytes, md5 5a1e58e8d90615a19ee34915dc0c5798

Have Kaspersky Internet Security 2015 installed.

**Comment by Maximus5** [comment]
From mingw64: 6d01a5ee6bd4a4562b2772f9206d1e32 *libcurl-4.dll

**Comment by elieux** [comment]
> mingw64: 6d01a5ee6bd4a4562b2772f9206d1e32 *libcurl-4.dll

Same here. I'm out of ideas. Can you try temporarily disabling (or even uninstalling) your security suite? It's not listed on the [list of BLODApps](https://cygwin.com/faq/faq.html#faq.using.bloda), but as I said -- out of ideas. :/

**Comment by dscho** [comment]
The strange thing jumping into my eye is that there is a `ssleay32.dll` in `C:\Windows\SysWOW64` that is picked up, as per the ProcessExplorer. In my setup, there is no such file there, instead I have the correct version in `/mingw32/bin/`:

```sh
$ which ssleay32.dll
/mingw32/bin/ssleay32.dll
```

**Comment by Maximus5** [comment]
That's interesting. Due to creation dates seems like files `ssleay32.dll` appears in SysWow64 and System32 after installing Visual Studio redistributables.

**Comment by dscho** [comment]
> Due to creation dates seems like files ssleay32.dll appears in SysWow64 and System32 after installing Visual Studio redistributables.

If you try to imply that Visual Studio redistributes OpenSSL, I have contradicting evidence: I just looked on a machine which has Visual Studio 2010 Express (including redistributables) installed, and the file in question is neither in `SysWOW64` nor in `System32`.

**Comment by Maximus5** [comment]
I can't confirm now who exactly put these files in system32. That was long ago in 2014 )

**Comment by dscho** [comment]
@Maximus5 it would be good if you could try to copy the affected `.dll` file(s) (at *least* `ssleay32.dll) from `mingw64/bin/` to `mingw64/libexec/git-core/`, test my hypothesis that this works around the problem, and report back. Would you do that, please?

**Comment by Maximus5** [comment]
Yes, if `ssleay32.dll` is copied to `git-core` then `git-remote-https.exe` loads properly. Cloning repository over `https` succeeds.

**Comment by dscho** [comment]
Okay, so the work-around I have in mind will test at installation time whether any of the `.dll` files in `/mingw??/bin/` have counterparts in `$SYSTEMROOT/system32` and in that case, try to hard-link them into `/mingw??/libexec/git-core/`.

The idea is to insert code into [`install.iss.in`](https://github.com/git-for-windows/build-extra/blob/82553c945bb398f68425770f8e2f7afc205f10b1/installer/install.iss.in#L1178) that looks somewhat like this (modulo bugs, of course):

```pascal
procedure HardlinkOrCopy(Target,SourceString);
begin
    try
        // This will throw an exception on pre-Win2k systems.
        LinkCreated:=CreateHardLink(Target,Source,0);
    except
        LinkCreated:=False;
        Log('Line {#__LINE__}: Creating hardlink "'+Target+'" failed, will try a copy.');
    end;

    if not LinkCreated then begin
        if not FileCopy(Source,Target,False) then begin
            Log('Line {#__LINE__}: Creating copy "'+Target+'" failed.');
        end;
    end;
end;

procedure MaybeHardlinkDLLFiles;
var
    FindRec: TFindRec;
    Bin,LibExec,System32: String;
begin
    Bin:=AppDir+'\{#MINGW_BITNESS}\bin\';
    LibExec:=AppDir+'\{#MINGW_BITNESS}\libexec\git-core\';
    System32:=GetEnv('SYSTEMROOT')+'\system32\';
    if FindFirst(ExpandConstant(Bin+'*.dll'), FindRec) then
    try
        repeat
            if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 and
                    FileExists(System32+FindRec.Name) then
                HardlinkOrCopy(LibExec+FindRec.Name,Bni+FindRec.Name);
        until
            not FindNext(FindRec);
    finally
        FindClose(FindRec);
    end;
end;
```

@Maximus5 please feel free to perform those edits, then make a test installer with `/usr/src/build-extra/installer/release.sh 2.4.0-Maximustest` and test whether it does what we expect it to.

**Comment by maoueh** [comment]
Had the same problem today, in my case, the problem was a PHP installation that had the DLL `ssleay32.dll` in a directory that was in my PATH before the `/mingw64/bin` directory. This DLL does not have the `SSL_CTX_set_alpn_protos` function at all hence the error.

If you have this problem, you can check out where the DLL is loaded by using the `which` command:

    $ which ssleay32.dll
    /c/Local/Php/5.3.28/ssleay32.dll

The workaround described earlier to copy `ssleay32.dll` from `<GIT_INSTALL_PATH>/mingw64/bin/ssleay32.dll` to `<GIT_INSTALL_PATH/mingw64/libexec/git-core/ssleay32.dll` until the installer does this automatically.

On a side note, I will try to build an installer with the patch mentioned by @dscho next monday.
