### ISSUE TITLE
Feature Request: Support for encryption

### ISSUE THREAD

**Issue by pankajazad** [git-for-windows/git#1451]
Support for encryption at git objects level will be a step in making the git repositories secure. The way I envisage it to work is following.
1. Git takes the objects as usual, computes sha1 and performs compression
2. Just before the contents are stored in file, it applies encryption on each git object.
3. Similarly the first thing it does after reading a file is decryption
4. This way it'll be transparent to the user

The mechanism/command to use for encryption can be made configurable by the user.  i.e. a user configured program/command will be invoked to get the git objects' contents encrypted/decrypted. So the users free to use encryption tool of their choice, or not use anything at all. In that case it'll be a regular git repository.

**Comment by dscho** [comment]
Thank you for your suggestion.

However, this feature request is safely outside the *Windows-specific* realm of Git for Windows. Therefore, it would be better to direct the feature request to the [Git mailing list](mailto:git@vger.kernel.org) (please avoid sending HTML mails, as they will be silently dropped, plain text mails are the only ones that are accepted).

**Comment by pankajazad** [comment]
Thanks. I tried sending and got following error.
vger.kernel.org rejected your message to the following email addresses:

git@vger.kernel.org (git@vger.kernel.org)
Your message wasn't delivered because the destination email system rejected your message for security or policy reasons. For example, the email address might only accept messages from certain senders, or it might not accept certain types of messages, like those larger than a specific size.

Contact the recipient (by phone, for example) and work with them and their email admin to determine what policy or setting blocked your message and what you should do to make sure that future messages from you won't be rejected.

For more information, see Status code 5.7.1.



vger.kernel.org gave this error:
Hello [40.92.254.102], for your MAIL FROM addresspolicy analysis reported: Your address is not liked source for email

**Comment by kostix** [comment]
@pankajazad be sure to make whatever means you're using to compose your mail messages to not produce HTML parts; see [this](https://gist.github.com/tfnico/4441562#writing-an-email-to-the-developers-list) for more info.
