### ISSUE TITLE
Git 2.16 is much slower than previous versions

### ISSUE THREAD

**Issue by AntAgna** [git-for-windows/git#1459]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git-2.16.1 64-bit

```
$ git --version --build-options
git version 2.16.1.windows.1
cpu: x86_64
built from commit: 1a4ee4d5d83bbba63f6d8b71c427f627769f3386
sizeof-long: 4
```

 - Windows 10 64

```
$ cmd.exe /c ver
Microsoft Windows [version 10.0.16299.125]
```

 - Mostly default options

```
$ type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Does not happen with version 2.15.1.2 and below

### Details

 - Which terminal/shell are you running Git from?

cmd

 - What commands did you run to trigger this issue?

git init
git status

```
$timeit git init
Initialized empty Git repository in D:/Projects/ABT/test-git-1/.git/

Elapsed Time:     0:00:02.322

$timeit git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        timeit.dat

nothing added to commit but untracked files present (use "git add" to track)

Elapsed Time:     0:00:02.225
```

 - What did you expect to occur after running these commands?

Fast execution time (<0.5s)

 - What actually happened instead?

Slow execution time (>2s)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happens with all repositories on my PC, even with a newly created empty repository.

With git version 2.15.1.windows.2 :
```
$git --version --build-options
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64

$type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

$timeit git init
Initialized empty Git repository in D:/Projects/ABT/test-git-1/.git/

Elapsed Time:     0:00:00.203

$timeit git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        timeit.dat

nothing added to commit but untracked files present (use "git add" to track)

Elapsed Time:     0:00:00.191
```

This slowness makes TortoiseGit unusable (+15s just to open Commit dialog, +60s for more complex operations).

**Comment by AntAgna** [comment]
I have tested in a Windows 7 x64 VM and I do not experience the issue.
It must be something in my environment interfering with git.

**Comment by AntAgna** [comment]
I have used Process Monitor to see what is happening. [git-status.zip](https://github.com/git-for-windows/git/files/1674913/git-status.zip)
I see activity from the F-Secure Antivirus during the time git is blocked, so it probably the culprit.
I don't know why there was no problem with the previous versions, probably some "intelligent filtering" inside the anti-virus software.
I'll try to see if I can get authorization to disable the anti-virus to confirm.
I'm closing this for now.

**Comment by dueringa** [comment]
Chipping in here to confirm, F-Secure Client Security is used in my company, too. 

Since Git for Windows 2.16.1(2) F-Secure DeepGuard even sometimes blocks git entirely. Has this to do with the "When Git spawns processes" bug fix?

**Comment by shiftkey** [comment]
@dueringa is there an older version of Git for Windows that doesn't seem to face this same problem?

Knowing that version N didn't have the problem but version N+1 did would help greatly with isolating the change (or changes) that introduced this issue, and without access to that setup it's hard for others to troubleshoot. Are you able to help us out with isolating this?

**Comment by dueringa** [comment]
@shiftkey Git for Windows 2.16.1(2) was definitely the first version the installer failed (at the end, where the settings are made. Several message boxes popped up saying that making the settings failed. Also, four F-Secure windows opened telling me git was blocked by DeepGuard). I tried installing the previous version (Git for Windows 2.16.1) afterwards and the installer ran cleanly. Installed 2.16.1(2) again and the messages appeared again.

I'm not sure if this is still reproducible, since I wrote F-Secure, I think they added this as an exception:

> Thank you for bringing this to our attention. Our analysis indicated that the  file you submitted is clean. We have identified the issue as a False Positive, which  will be resolved in an upcoming database update. In the meantime, you can exclude this file from further  scanning by the security product.

Both git.exe and git-sh-i18n--envsubst.exe were blocked.

Also, looking into the Windows/F-Secure event logs:

Probably from the initial blockings in 2.16.1(2):
```
{ "Hash": "1443883494bd9b5b41577d340891c5e375d308fb", "Path": "c:\\program  files\\git\\mingw64\\bin\\git.exe", "Rarity": 1, "Detection":  "Suspicious:W32\/Leaktool.A!DeepGuard", "Reputation": 0, "ProcessID": 14328,  "SessionID": 1, "Reason": 8 }
{ "Hash": "638a0c5f149d00262586d558debe86dd205c926e", "Path": "c:\\program  files\\git\\mingw64\\libexec\\git-core\\git-sh-i18n--envsubst.exe", "Rarity": 1,  "Detection": "Suspicious:W32\/Leaktool.A!DeepGuard", "Reputation": 0,  "ProcessID": 8380, "SessionID": 1, "Reason": 6 }
```
Entry from today with 2.16.2 when I tried to git push:

```
{ "Hash": "94bfab31ab1e90094edc723accb1d69fb2f16a30", "Path": "c:\\program  files\\git\\mingw64\\libexec\\git-core\\git-sh-i18n--envsubst.exe", "Rarity": 1,  "Detection": "Suspicious:W32\/Leaktool.A!DeepGuard", "Reputation": 0,  "ProcessID": 7572, "SessionID": 1, "Reason": 6 }
```

Maybe "LeakTool" is a hint?

**Comment by AntAgna** [comment]
I got our corporate IT to set a whitelist for Git inside F-Secure and it solved the problem.
