### ISSUE TITLE
How to update GitSDK / Git-For-Windows properly?

### ISSUE THREAD

**Issue by Maximus5** [git-for-windows/git#146]
Is there a way to update Git portable/installation from command line? Or it is recommended to install Git from scratch? I've failed to find any wiki about it.

Trying to run `pacman -Sy` from git-bash's command line (installed into T:\GitSDK) I get following error:

    $ pacman -Sy
    :: Synchronizing package databases...
    error: failed retrieving file 'git-for-windows.db' from dl.bintray.com : error setting certificate verify locations:
      CAfile: /usr/ssl/certs/ca-bundle.crt
      CApath: none
    error: failed to update git-for-windows (download library error)
     mingw32 is up to date
     mingw64 is up to date
     msys is up to date

Is it temporarily problem with dl.bintray.com or I need to configure something?

Windows 8.1 x64, git version 2.3.6.windows.2

**Comment by elieux** [comment]
How did you install this? I installed PortableGit-2.3.6.2-dev-preview-64-bit.7z.exe and it doesn't contain pacman at all. (This is probably lack of knowledge on my part.)

**Comment by Maximus5** [comment]
As recommended by @dscho [here](https://github.com/git-for-windows/git/issues/96#issuecomment-95113103) installed via [Git SDK](https://git-for-windows.github.io/#download-sdk) in separate folder.

**Comment by elieux** [comment]
I installed using git-sdk-installer-1.0.0-rc-3-64.7z.exe and `pacman -Syy` ran without an error. Is it possible your installation was incorrectly upgraded (showing errors during an upgrade)? Does re-installing `ca-certificates` (`pacman -S ca-certificates`) help?

**Comment by Maximus5** [comment]
After issuing `pacman -S ca-certificates` there is not errors with `pacman -Sy` anymore, thanks. 
But the (newbie) question is still actual. What command must update installation? `pacman -Sy`?

**Comment by elieux** [comment]
Hope these two links shine some light on the matter:
- https://github.com/git-for-windows/git/wiki/Package-management
- https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

The gist of it is that most of the time you can run `pacman -Syu`, but if it shows that `msys2-runtime` is going to be updated, you have to update it separately. Probably applies to `bash` and `pacman` packages, but I'm not so sure about that.

**Comment by dscho** [comment]
> After issuing pacman -S ca-certificates there is not errors with pacman -Sy anymore, thanks.

That bug was supposed to be fixed in @sschuberth's Pull Request: https://github.com/Alexpux/MINGW-packages/pull/570

**Comment by dscho** [comment]
I guess the answer for this ticket's question has been given [by @elieux](https://github.com/git-for-windows/git/issues/146#issuecomment-101083532).
