### ISSUE TITLE
"Application manifest has either a different computed hash than the one specified" CRLF round tripping

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#1461]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

pjo@DES162 MINGW64 ~
$ git --version --build-options
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Corporate Win7, 64 bit.
```
$ cmd.exe /c ver

pjo@DES162 MINGW64 ~
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

pjo@DES162 MINGW64 ~
$ cat /etc/install-options.txt
Editor Option: Notepad++
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This was a 'student' project, compiled in VS15 pro, being stored in Git, and subsequently cloned to a second machine where execution of the setup.exe reported the manifest file error, yet Git prides itself on data integrity. This is a record of the underlying issue. Hopefully it is fixed in v2.16 with the improved CRLF by @tboegi 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

The clone and checkout was from bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

The running of the checked out  setup.exe was right click from Windows explorer.

 - What did you expect to occur after running these commands?

The compiled programme should have been setup/installed, however..

 - What actually happened instead?

The following error log was produced, with the reported error message regarding the manifest file.
[4KW6UIBX.LOG](https://github.com/git-for-windows/git/files/1666161/4KW6UIBX.LOG)

The manifest itself (.TXT extension added) is here
[Linear Slider Control.exe.manifest.TXT](https://github.com/git-for-windows/git/files/1666165/Linear.Slider.Control.exe.manifest.TXT)

- So what was the problem

The issue is that the manifest has mixed line ending. it contains both CRLF and LF line endings, which was not correctly round tripped checkin-checkout, which was suprising (being a VS compiler product I expected all CRLF) and difficult to see (needed a hex compare with Beyond Compare).

The original file location/name was D:\ .. \Installs\x64\Application Files\Linear Slider Control_1_0_0_7\Linear Slider Control.exe.manifest

The error in the file is after the comment tags within the manifest
``` 
       <!--
          UAC Manifest Options
          If you want to change the Windows User Account Control level replace the 
          requestedExecutionLevel node with one of the following.

        <requestedExecutionLevel  level="asInvoker" uiAccess="false" />
        <requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />
        <requestedExecutionLevel  level="highestAvailable" uiAccess="false" />

         If you want to utilize File and Registry Virtualization for backward 
         compatibility then delete the requestedExecutionLevel node.
    -->
```

Lines. All the internal line endings are LF (0A) only.

To see them, perhaps use Notepad++ and set the CRLF paragraph mark display to on, (Line 17-27) to easily see them.
You can probably get a regex to find standalone LF, !not! preceded by CR.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

corporate repo, but the example file and log are attached (the manifest may even be corrupted here, dunno yet)

- Summary

This report is to provide a real world example file that has mixed EOL for checking Window to LF repo round trip capability. Provide an alternate web reference for those seeking a reason for the manifest file error (which will happen if the file is passed through any tool that isn't careful enough about line endings, such as on-the-fly virus checks, file copies, etc). And to show that the mixed EOL case that @tboegi  has been chasing is real.

**Comment by PhilipOakley** [comment]
The uploaded `Linear Slider Control.exe.manifest` file does correctly have the original (mixed) line endings, while the round tripped file had all CRLF line ending.

**Comment by dscho** [comment]
@PhilipOakley what do you want to do with this ticket? Wouldn't this info be better sent to the Git mailing list instead of pretending that we are reporting a bug in Git for Windows? ;-)

**Comment by PhilipOakley** [comment]
Hi @dscho This was the first step in recording an 'in the wild' practical example of a mixed CRLF file (That I have come across). There are various related questions on the web about the manifest files, and tis is certainly a plausible reason that folk aren't noting how/why they get the 'bad manifest' errors.

I will close this as it isn't a bug per se, but is an 'Issue'. I can offer it upstream, but I have a suspicion they will, in the main, just mark it as a Microsoft / Windows problem, and it will languish in the list, and not be see by those most likely to benefit from it...  That was my reasoning anyway.

Closing now.

**Comment by dscho** [comment]
> I can offer it upstream, but I have a suspicion they will, in the main, just mark it as a Microsoft / Windows problem, and it will languish in the list, and not be see by those most likely to benefit from it...

How about adding it as a project to the project ideas page at https://git.github.io/SoC-2018-Microprojects/ ?

**Comment by PhilipOakley** [comment]
@dscho Hmm, perhaps a misunderstanding. I didn't think there was a project in there ;-) Hopefully @tb's work will have fixed this upstream by detecting when there is mixed EOLs when the checking is enabled. 

On the flip side is whether .manifest files should be marked as 'binary' in the .git attributes because of the poor CRLF round tripping. 

Or maybe (a real project) adding a variant of the 'text' attribute that says a file type 'text-mix-eol', so that diffs don't drop into binary comparison, but the EOL conversion knows not to touch it. I haven't thought too deeply about it. It's one of those cases where one should stop digging before the hole gets too deep!

[I may not get round to sending a note upstream any time soon as I'll be essentially off line for 6 weeks on a grand tour]
