### ISSUE TITLE
Leading slash in command line argument gets converted to absolute path

### ISSUE THREAD

**Issue by laudeam** [git-for-windows/git#1462]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
git version 2.16.1.windows.1
cpu: x86_64
built from commit: 1a4ee4d5d83bbba63f6d8b71c427f627769f3386
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
`Microsoft Windows [version 10.0.16299.125]`
`node v8.9.1`

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Nano
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Node.js script to extract command line arguments:
```
console.log('showing args: ')
process.argv.forEach(function (val, index, array) {
  console.log(index + ': ' + val);
});
```

Command to run the script:

`node test.js /url/`

 - What did you expect to occur after running these commands?

I get the following (correct) output when using:
- Windows Powershell 
- cmd.exe
- bash (Debian 9)

```
showing args:
0: C:\Program Files\nodejs\node.exe
1: C:\test.js
2: /url/
```

 - What actually happened instead?

```
showing args:
0: C:\Program Files\nodejs\node.exe
1: C:\test.js
2: "C:/Program
3: Files/Git/url/"
```

These commands also yield the same wrong output:
`node test.js "/url/"`
`node test.js '/url/'`

Other trials:
_____________________
`node test.js //url/` yields:
```
showing args:
0: C:\Program Files\nodejs\node.exe
1: C:\test.js
2: //url/
```

_______________________
`node test.js //url` yields:

```
showing args:
0: C:\Program Files\nodejs\node.exe
1: C:\test.js
2: /url
```
almost good but still not what I want (I want to use `/url/` as input argument)

Thank you for your time :-)

**Comment by PhilipOakley** [comment]
try the Release notes.....

https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues

•If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "/usr/bin/bash.exe" to "C:\Program Files\Git\usr\bin\bash.exe". When that is not desired -- e.g. "--upload-pack=/opt/git/bin/git-upload-pack" or "-L/regex/" -- you need to set the environment variable MSYS_NO_PATHCONV temporarily, like so:

MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc

Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "//usr/bin/bash.exe".


•Windows drives are normally recognised within the POSIX path as /c/path/to/dir/ where /c/ (or appropriate drive letter) is equivalent to the C:\ Windows prefix to the \path\to\dir. If this is not recognised, revert to the C:\path\to\dir Windows style.

-

If you can confirm that it solves you issue that would be great, If so, then please close the issue..

**Comment by laudeam** [comment]
Thanks for pointing out this ressource, I somehow missed it.

As stated above I tried doubling the leading slash. Can you confirm this is the expected behaviour ?

**This looks ok:**
`node test.js //url ` yields:
```
0: C:\Program Files\nodejs\node.exe
1: C:\test.js
2: /url
```

**This looks not ok:**
`node test.js //url/ ` yields:
```
0: C:\Program Files\nodejs\node.exe
1: C:\test.js
2: //url/
```
Here I was expecting to get `/url/` instead of `//url/`
Is there any way I can get it to yield `/url/` ?

**Comment by dscho** [comment]
> Is there any way I can get it to yield /url/ ?

Try @PhilipOakley's suggestion (lifted from the Known Issues in the release notes):

> you need to set the environment variable MSYS_NO_PATHCONV temporarily, like so:
> 
> MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc

In your case, obviously, this would look more like

```cmd
set MSYS_NO_PATHCONV=1
node test.js /url/
```
