### ISSUE TITLE
Git bash freezes on 'node' commands

### ISSUE THREAD

**Issue by laudeam** [git-for-windows/git#1463]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
git version 2.16.1.windows.1
cpu: x86_64
built from commit: 1a4ee4d5d83bbba63f6d8b71c427f627769f3386
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
`Microsoft Windows [version 10.0.16299.125]`
`node v8.9.1`
`python 3.6.4`

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Nano
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Command to run the script:

```
node
```

 - What did you expect to occur after running these commands?

```
Above command should open node interpreter.
It works in Window Power Shell and cmd.exe
```

 - What actually happened instead?

```
Git bash doesn't show node prompt, returns the bash prompt but with broken behaviour:
- inputs caracters are not shown
- Ctrl + C doesn't return the prompt to normal behaviour
```

I can't run any node.js script either. 
This command yields the same result as above:
`node test.js`

Another trial with Python interpreter also failed: python prompt is not displayed.

**Comment by landstander668** [comment]
Did you try running them under *winpty* (i.e. `winpty node test.js`)? This is mentioned in the release notes as being needed for both Python (assuming a non-MSYS2 build) and node.

**Comment by laudeam** [comment]
I definitely should pay more attention to these release notes...
Thanks
