### ISSUE TITLE
gitk 'draggable resize' for horizontal panes is in middle of toolbar

### ISSUE THREAD

**Issue by adambernstein** [git-for-windows/git#1465]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

** git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
7
```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```** bash **```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** gitk **
```
 - What did you expect to occur after running these commands?
```
** The top of the horizontal toolbar should trigger the 'draggable' cursor and allow to change the size of the pane **
```
 - What actually happened instead?
```
** The position of the draggable part of the horizontal pane is in the middle of the toolbar. **
```
![gikt-drag-pane](https://user-images.githubusercontent.com/5280324/35519097-4a8a9d7c-04e1-11e8-9030-6b0de62148b2.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
This seems to be consistent with the behavior on Linux. Therefore, I think it is safe to say that this issue is not Windows-specific. As such, please report it to [the Git mailing list](mailto:git@vger.kernel.org) (watch out: they accept no HTML mail, not even an alternative plain/html one).
