### ISSUE TITLE
How to use sshd

### ISSUE THREAD

**Issue by liaowuping** [git-for-windows/git#1466]
How to use `C:\Program Files\PortableGit\usr\bin\sshd.exe`
this program always output `sshd re-exec requires execution with an absolute path`

**Comment by dscho** [comment]
You don't want to use sshd. This program would be used to offer an SSH service. Just don't use it. It is absolutely unnecessary for regular Git usage.

**Comment by liaowuping** [comment]
i just want to use ssh service on windows.

**Comment by kostix** [comment]
@liaowuping, [here it is](https://github.com/PowerShell/Win32-OpenSSH). And that's just one of them—supposedly "the most true" these days. Other implementations do exist; please do your research.

**Comment by dscho** [comment]
> i just want to use ssh service on windows.

This has nothing to do with Git, though, and we're already busy enough taking care of Git bugs in this issue tracker 😄
