### ISSUE TITLE
with Git 2.16.1 , when  using VSCode ,the  process “git for windows” was lanched again and agian，and the cpu was used 100%

### ISSUE THREAD

**Issue by Kage336** [git-for-windows/git#1467]
just like the title of the issue, I am trying to solve is by confinuring the VSCode, but it doesn't work;
and I  has gone back to the version 2.16.0 just now. The Bug doesn't happen any more.
if something wrong ？

**Comment by dscho** [comment]
This description leaves everything unclear. Care to elaborate so that even I have a chance of understanding what your exact setup is, what you are trying to accomplish, what precise steps you are executing to that end, what you expect to happen, and what is happening instead?

**Comment by Kage336** [comment]
I am sorry for my unclear description, ( my mother language is chinese, my english is not good,  LOL - -! )
here is the details:
my exact setup is the VSCode default setup on windows 10 ( yes, I try to reinstall ( both VSCode and Git ) to solve the problems, but it doesn't work - - ! ),
and I try to write a demo ( yes, just a small demo, just contain some folder, like a few "npm_modules", a entry file ( index.js ), etc ... ),
and then I update the Git ( up to V 2.16.1 ),
then open the VSCode with no operation,
yes , the end is the bug happened:
the process “git for windows” which is launched by VSCode start to run ( 2 times or more ),
and I try to kill all process "git for windows",
the bug disapper,
but a few minutes later , it happens again.
I have to disable the Git of VSCode,
it was terrible,
so I downgrade the git ( V 2.16.0 ),
the bug doesn' t happen again,
LOL

**Comment by dscho** [comment]
> the process “git for windows” which is launched by VSCode start to run ( 2 times or more ),

What command-line does `wmic process list` show for this "Git for Windows" process?

**Comment by dscho** [comment]
Please understand that I am *trying* to help, and that it is extremely frustrating to be left hanging without enough feedback.

**Comment by Kage336** [comment]
today, I update git for windows again, and the problems doesn't happened again, I don't know what 
has happened. Thank you for your help, if the problem appear again next time , I will report.
