### ISSUE TITLE
"Use a True Type font for all console windows" applicable to git for windows 2.x?

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#147]
There is an option "Use a True Type font for all console windows" in inno setup installer.
Is it still applicable to git for windows 2.x, where mintty is used instead of Windows Console?

**Comment by dscho** [comment]
There is `Git CMD`.

**Comment by linquize** [comment]
Could you say "Specific to Git CMD" only?

**Comment by kblees** [comment]
Git-Bash can be used without MinTTY (e.g. if you need to use other interactive native programs, see issue #74)

**Comment by dscho** [comment]
The newest incarnations of the installer even offer to use `Git Bash` without MinTTY, in the regular standard Windows console.

**Comment by Larry0ua** [comment]
Just tried the latest installation, first time installed with disabled option of MinTTY, had two console windows opened when Git Bash is called - one with the bash prompt, another completely blank. Is it a bug? I've reinstalled with MinTTY and it works fine now.

**Comment by dscho** [comment]
@Larry0ua please open new tickets when describing unrelated problems.

**Comment by dscho** [comment]
So I think that question has been answered ("yes, it is applicable").
