### ISSUE TITLE
Some more.pager bugs found

### ISSUE THREAD

**Issue by FalconWu2017** [git-for-windows/git#1471]
At 1st I am a Chinese and my English is not very well,so i will try my best to say what happened.
I have a problem when I user git bash in windows 7 64-bit at git version 2.16.0.windows.2.

---------------
Some command such as "git log" are not support Chinese .It will show me like "<E6><B7><BB><E5><8A><A0><E6><96><87><E4><BB><B6>" .I get the help from some website,they tell me use "git config --global core.pager more"to set core.pager.It is work, I can see my Chinese word but it show me a err at the 1st line of the command "git log".The err say:"error: cannot spawn more: No such file or directory"。This is not a serious error and I can do my work with it but it is not really a nice looking.

**So the 1st bug is either no Chinese or work with error.**

---------------
Command "git log" will not right finish，it always show me "(END)" at the last line.If I press space it will show me the log again from the last commit(the last commit at top) even the log is finish,if I press Ctrl+C to abort command ,it will show me a "(END)" as cmd dialog prompt,and then whatever I do(press enter or space) it will show the log again. So the only way that can stop this chaotic output is close dialog and open it again by cmd.exe.
**so the 2nd bug is some command that need page can not right finish**

**Comment by kgybels** [comment]
@FalconWu2017 First undo the fix you did, by unsetting `core.pager`:
`git config --global --unset core.pager`

Then try executing the following before doing `git log`:
`set LC_ALL=C.UTF-8`

This will tell `less` (the default pager) that output from `git log` is using UTF-8 encoding.

**Comment by bbolli** [comment]
@FalconWu2017 Yes, just put the line `export LC_ALL=C.UTF-8` into a file called `.bashrc` in your home folder.

**Comment by bbolli** [comment]
@FalconWu2017 To exit the pager at the end of `git log`, press the `q` key.

**Comment by FalconWu2017** [comment]
@bbolli Thank you very much.It's a good way to do it press the `q` key.

**Comment by dscho** [comment]
The newest snapshot at https://wingit.blob.core.windows.net/files/index.html has a fix where Ctrl+C works as intended: it stops Git from continuing to enumerate the commit history, but keeps the pager running. Please test.

**Comment by dscho** [comment]
Quite honestly, it is this type of (none-)reaction to my requests for testing (when testing takes _way_ less time than the time I spent on implementing the fixes) that can make Open Source maintainers walk away from their projects. It is horribly rude to be so silent.
