### ISSUE TITLE
Feature Request: include git-review in the distribution

### ISSUE THREAD

**Issue by jaltman** [git-for-windows/git#1472]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.16.1.windows.1
cpu: x86_64
built from commit: 1a4ee4d5d83bbba63f6d8b71c427f627769f3386
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This is a feature request

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Take Command 22.00

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Not applicable
```
 - What did you expect to occur after running these commands?

Not applicable

 - What actually happened instead?

Not applicable

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not applicable

Please include the "git-review" command from OpenStack in future distributions.

  docs:   http://docs.openstack.org/infra/git-review/
  source: https://github.com/openstack-infra/git-review

Thank you.

**Comment by dscho** [comment]
This would be the first user in Git for Windows requiring Python. Python 3, even. This would increase the footprint of the Git for Windows installer by megabytes, something I am not really willing to impose on Git for Windows users when the vast majority will not benefit from the `git review` script...

**Comment by jaltman** [comment]
Completely understandable
