### ISSUE TITLE
Faulting application name: git-remote-https.exe, version: 2.16.1.2

### ISSUE THREAD

**Issue by Comanche** [git-for-windows/git#1478]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.2
cpu: x86_64
built from commit: e78e3c8ee9c219723d60aa1bccd8348c2269b9ba
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.214]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Default settings for Git Portable x64 2.16.1.windows.2
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Tested on two separate machines.  Both clean install of Win 10 Version 10.0.16299.214.  No other apps other than device drivers.  Same result.  **Tested on both machines with Git Portable x64 2.16.1.windows.1 without any problems.  Problem only in Git Portable x64 2.16.1.windows.2.**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Both CMD and PowerShell.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://github.com/allenmichael/box-jwt-php
```
 - What did you expect to occur after running these commands?

Repository cloned.

 - What actually happened instead?

```
Faulting application name: git-remote-https.exe, version: 2.16.1.2, time stamp: 0x5a7491f4
Faulting module name: git-remote-https.exe, version: 2.16.1.2, time stamp: 0x5a7491f4
Exception code: 0xc0000005
Fault offset: 0x00000000000056cd
Faulting process id: 0x24ec
Faulting application start time: 0x01d39eb64bad4179
Faulting application path: D:\Apps\Version Control\GitPortable\mingw64\libexec\git-core\git-remote-https.exe
Faulting module path: D:\Apps\Version Control\GitPortable\mingw64\libexec\git-core\git-remote-https.exe
Report Id: bba517a2-a650-4a33-8916-4332b07a9026
Faulting package full name: 
Faulting package-relative application ID: 
```

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" />
        <EventID Qualifiers="0">1000</EventID>
        <Level>2</Level>
        <Task>100</Task>
        <Keywords>0x80000000000000</Keywords>
        <TimeCreated SystemTime="2018-02-05T19:19:51.540460800Z" />
        <EventRecordID>2520</EventRecordID>
        <Channel>Application</Channel>
        <Computer>DevPC</Computer>
        <Security />
    </System>
    <EventData>
        <Data>git-remote-https.exe</Data>
        <Data>2.16.1.2</Data>
        <Data>5a7491f4</Data>
        <Data>git-remote-https.exe</Data>
        <Data>2.16.1.2</Data>
        <Data>5a7491f4</Data>
        <Data>c0000005</Data>
        <Data>00000000000056cd</Data>
        <Data>24ec</Data>
        <Data>01d39eb64bad4179</Data>
        <Data>D:\Apps\Version Control\GitPortable\mingw64\libexec\git-core\git-remote-https.exe</Data>
        <Data>D:\Apps\Version Control\GitPortable\mingw64\libexec\git-core\git-remote-https.exe</Data>
        <Data>bba517a2-a650-4a33-8916-4332b07a9026</Data>
        <Data />
        <Data />
    </EventData>
</Event>
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not specific to any repo.  Cloning any repo will produce the result.

**Comment by Comanche** [comment]
If Git was installed with `Git-2.16.1.2-64-bit.exe` (all default settings), there's not a problem.  The problem is only with the portable version (`PortableGit-2.16.1.2-64-bit.7z.exe`).

**Comment by dscho** [comment]
Thank you for the report!

I am fairly certain that this is fixed via 60d8d6eae36358696027f95f0dc1a2dffc3b066b. It's a bit too late for me now, so I will release a new Git for Windows version tomorrow.

**Comment by dscho** [comment]
(I am labeling this as "duplicate" to document that the issue had been reported earlier, but that ticket was closed already, so I don't fault anybody for missing it.)

**Comment by ArminVieweg** [comment]
Cool, thanks!
