### ISSUE TITLE
Two consoles opened on Git Bash (no MinTTY)

### ISSUE THREAD

**Issue by Larry0ua** [git-for-windows/git#148]
Using latest installer Git-2.4.0.2-dev-preview-64-bit.exe I've encountered the next issue:

Wanting to install environment as close to previous, I deselected MinTTY option while installing. After the installation Git Bash shortcut (as well as executing git-bash.exe in Git folder) opens two windows - one with the shell prompt, another is blank and can be closed. After reinstalling with MinTTY enabled, only one window is shown on Git Bash launch.

I believe that git-bash on no-MinTTY installation should not show another blank console window...

Target system: Win8.1Enterprise x64

**Comment by dscho** [comment]
Thanks for the bug report!
