### ISSUE TITLE
PortableGit fails silently (return code 128)

### ISSUE THREAD

**Issue by pjturpeau** [git-for-windows/git#1482]
Similar to an old ticket : https://github.com/git-for-windows/git/issues/390

### Setup

```
$ git --version --build-options
git version 2.16.1.windows.2
cpu: x86_64
built from commit: e78e3c8ee9c219723d60aa1bccd8348c2269b9ba
sizeof-long: 4
```

```
D:\Users\T0010711>cmd /ver
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.
```

It's on my work laptop, and due to restricted installation credentials, I'm only allowed to put and launch portable executable from a dedicated subdirectory (which has spaces...) under "My Documents".

http_proxy and https_proxy environment variables setup to the right proxy:port configuration.

I did launch post-install.bat

### Details

From git-bash.exe

```
$ GIT_TRACE=1 git clone https://github.com/pjturpeau/demo-snippets.git
23:54:57.842401 git.c:344               trace: built-in: git 'clone' 'https://github.com/pjturpeau/demo-snippets.git'
Cloning into 'demo-snippets'...
23:54:57.904801 run-command.c:627       trace: run_command: 'remote-https' 'origin' 'https://github.com/pjturpeau/demo-snippets.git'
23:54:57.998400 git.c:576               trace: exec: 'git-remote-https' 'origin' 'https://github.com/pjturpeau/demo-snippets.git'
23:54:57.998400 run-command.c:627       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/pjturpeau/demo-snippets.git'

$ echo $?
128
```

I can reach the URL using curl (still from git-bash.exe):

```
$ curl -I https://github.com/pjturpeau/demo-snippets.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   178    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Date: Tue, 06 Feb 2018 22:56:53 GMT
Content-Type: text/html.
Content-Length: 178
Location: https://github.com/pjturpeau/demo-snippets
Vary: Accept-Encoding
X-GitHub-Request-Id: D390:6034:324A5D:547910:5A7A32B4
X-Frame-Options: DENY
```

I tried to install the http://gitforwindows.org/#download-sdk but the enterprise proxy keeps reject some requests (403 forbidden). I may request for exceptions to complete the operation but I don't know how to 'trace' details in the install process of git-sdk-installer-1.0.6-64.7z.exe

Any idea about where to search next is welcome.

**Comment by dscho** [comment]
> git version 2.16.1.windows.2

Please try [v2.16.1(3)](https://github.com/git-for-windows/git/releases/tag/v2.16.1.windows.3) (released yesterday), which has a fix precisely for this, also reported as #1478.

**Comment by dscho** [comment]
> I tried to install the http://gitforwindows.org/#download-sdk but the enterprise proxy keeps reject some requests (403 forbidden).

BTW this issue is also known: #1479. Please have a look at that ticket for the suggested workarounds for now.

**Comment by pjturpeau** [comment]
As suggested by Johannes, the new version PortableGit-2.16.1.3-64-bit.7z.exe fixed the problem.
Thank you for the responsiveness.
