### ISSUE TITLE
Just attempted to push some code to my GitHub Repos -- and this error pops up: "error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by pdhoward** [git-for-windows/git#1485]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by pdhoward** [comment]
weird -- error popped up per title then resolved itself 10 minutes later

**Comment by edwlarkey** [comment]
@pdhoward This might be related to GitHub disabling weak cryptography. They did a test for 1 hour today, and they plan to disable them permanently on the 22nd.

https://githubengineering.com/crypto-removal-notice/

**Comment by shiftkey** [comment]
@pdhoward can you share which version of Git for Windows and Windows you are running? The fact that the error was intermittent probably means you should update before you get caught again when it's disabled permanently...

**Comment by dscho** [comment]
> ** insert your machine's response here **

@shiftkey is there a way to auto-label new tickets where the reporter did not bother to fill out the information we suggest to provide so that it is possible to help them?

**Comment by pdhoward** [comment]
Sorry - I abandoned the thread above thinking the problem was resolved. My version of git is 1.9.5.msysgit.1   .. I am running win 10.0.16299.1921    .. any help here would be greatly appreciated!

**Comment by PhilipOakley** [comment]
> My version of git is 1.9.5.msysgit.1 .. I am running win 10.0.16299.1921 .. any help here would be greatly appreciated!

@pdhoward Ah the good (bad) old 1.9.5.msysgit.1 While there are still some users of the older versions, essentially the old 1.9.5.msysgit was the last of that ilk. The team moved over to the newer interface versions at the start of the Git 2.x series. 

If I may suggest that moving up to a much newer version of the latest and greatest (especially with security fixes!) would be the way to go. Try the last of the 2.15.x series if you are worried about the foibles of 2.16.0.x.

Also there is a change coming to Github that will stop tls v1 operating, so do make the change before the cut off date.

**Comment by pdhoward** [comment]
Thanks much! You can see I have not been paying attention to this. I'll fix it now!

**Comment by shiftkey** [comment]
> is there a way to auto-label new tickets where the reporter did not bother to fill out the information we suggest to provide so that it is possible to help them?

@dscho there's nothing in-the-box currently but I think the [Probot](https://probot.github.io/) community would be interesting to look at - [this integration](https://probot.github.io/apps/request-info/) is an interesting example related to your issue, and I'm sure there's others that could be built upon if you wanted to tailor the interactions when new issues arrive here.

**Comment by dscho** [comment]
@shiftkey what's the easiest way to set up a Probot integration? It there a convenient Azure template?

**Comment by shiftkey** [comment]
@dscho there's some docs around deployment [here](https://probot.github.io/docs/deployment/) but nothing for Azure. There's [some interest](https://github.com/probot/probot/issues/149) in getting this running on serverless infrastructure like AWS Lambda, but that's a way off I think.

**Comment by dscho** [comment]
I'd be majorly interested in getting this to run as Azure Function. If only I had abundant time on my hands and would not have to take care of 93 open tickets (and a lot of behind-the-scene work)...

**Comment by tcbyrd** [comment]
> There's some interest in getting this running on serverless infrastructure like AWS Lambda, but that's a way off I think.

Hopefully not too far off. A few people have it running on Lambda and GCF already. The tricky part is that each cloud provider has it's own HTTP Gateway and function signature. @jasonetco was able to get his running on GCF by writing [this handler](https://github.com/JasonEtco/ci-reporter/blob/master/index.js#L19), so it should work similarly on Azure by calling the `probot.receive()` method inside the Azure function handler. I'd be happy to work with someone to get it working.
