### ISSUE TITLE
bad git-diff - expected /dev/null

### ISSUE THREAD

**Issue by tkrasnukha** [git-for-windows/git#1489]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.16.1.windows.3
cpu: x86_64
built from commit: dc364ab06b41bcd142295751cef12e2c88fdc437
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
Plink Path: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
svn, version 1.9.5 (r1770682)
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
cmd.exe
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git apply | git am + patch created with svn
```

 - What actually happened instead?
```
bad git-diff - expected /dev/null
```

It happened because the patch contains additional text in the line:
```
 --- /dev/null  (nonexistent) 
```
and gets fixed by removing this text.

Could you please ignore any symbols after '/dev/null' ? I see, that case with path to a file + (working copy) or (revision xxxxx) works well, so it should be not too difficult to ignore (nonexistent) also.

**Comment by dscho** [comment]
This is not a Windows-specific feature request. Therefore, it needs to be asked on [the Git mailing list](mailto:git@vger.kernel.org). (Note: you will have to convince your mail program to refrain from sending HTML mail or it will be dropped silently.)

Unless you are willing to contribute a fix for `apply.c` in the form of a Pull Request, in which case I will work with you to get it ready for submission and take care of that submission, too.
