### ISSUE TITLE
unable to install `mingw-w64-x86_64-asciidoctor-extensions` correctly

### ISSUE THREAD

**Issue by nalla** [git-for-windows/git#149]
I *hope* somebody can reproduces this. I'm unable to install the `mingw-w64-x86_64-asciidoctor-extensions` in my *Git for Windows SDK* I even tried a complete fresh install.

```bash
# update system
$ pacman -Syu
# remove any possible ruby in the SDK
$ pacman -R ruby
$ pacman -R libyaml
$ pacman -R mingw-w64-x86_64-asciidoctor-extensions
$ pacman -R mingw-w64-x86_64-ruby
$ pacman -R mingw-w64-x86_64-libyaml
$ pacman -S mingw-w64-x86_64-asciidoctor-extensions
resolving dependencies...
looking for conflicting packages...

Packages (3) mingw-w64-x86_64-libyaml-0.1.6-1  mingw-w64-x86_64-ruby-2.2.1-1  mingw-w64-x86_64-asciidoctor-extensions-79.4c6d08e-1
# [...]
(1/3) installing mingw-w64-x86_64-libyaml                                                      [#######################################################] 100%
(2/3) installing mingw-w64-x86_64-ruby                                                         [#######################################################] 100%
:: Installing the "asciidoctor" gem (please wait)
C:/git-sdk-64/mingw64/lib/ruby/2.2.0/yaml.rb:4:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': 126: Das angegebene Modul wurde nicht gefunden.   - C:/git-sdk-64/mingw64/lib/ruby/2.2.0/x64-mingw32/psych.so (LoadError)
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/psych.rb:1:in `<top (required)>'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/yaml.rb:5:in `<top (required)>'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems.rb:624:in `load_yaml'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/config_file.rb:328:in `load_file'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/config_file.rb:197:in `initialize'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/gem_runner.rb:74:in `new'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/gem_runner.rb:74:in `do_configuration'
        from C:/git-sdk-64/mingw64/lib/ruby/2.2.0/rubygems/gem_runner.rb:39:in `run'
        from C:/git-sdk-64/mingw64/bin/gem:21:in `<main>'
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_e05hUj/.INSTALL; pre_install 79.4c6d08e-1 ) failed to execute correctly
(3/3) installing mingw-w64-x86_64-asciidoctor-extensions                                       [#######################################################] 100%
```

So. I have no idea what caused this. It seems that `gem` in general seems not to work. The *MSys2* version seems to work fine.

The file `C:/git-sdk-64/mingw64/lib/ruby/2.2.0/x64-mingw32/psych.so` is in its correct location btw.

**Labels**: `investigation`, `possible-bug`, `SDK`

**Comment by dscho** [comment]
Yep, I can reproduce by calling `gem` in a fully-up-to-date Git SDK. Which means that a recent update broke things.

I opened `psych.so` with [`depends.exe`](http://www.dependencywalker.com/) and it said that `libyaml.dll` was not found. I then found `libyaml-0-2.dll` via tab completion on the command-line, and called

```bash
cd /mingw64/bin
ln libyaml-0-2.dll libyaml.dll
```

... and all of a sudden, `gem` worked again!

So I guess a recent `mingw-w64-libyaml` update broke dependencees such as `mingw-w64-ruby`.

**Comment by nalla** [comment]
I can confirm this as workaround. Thanks @dscho!

**Comment by dscho** [comment]
I guess that this is actually a bug in `MINGW-packages` where it released the libyaml dependency with a different file name, without updating all the dependencees to now expect `libyaml-0-2.dll` instead of `libyaml.dll`. @nalla would you mind reporting this bug [upstream](https://github.com/Alexpux/MINGW-packages)?

**Comment by nalla** [comment]
I'll do that.

**Comment by nalla** [comment]
Latest `mingw-w64-ruby` upgrade seems to fix the issue. Could anyone confirm that? To confirm it, remove the created link `libyaml.dll` from `/mingw64/bin`, then remove and reinstall `mingw-w64-ruby`, `mingw-w64-libyaml`, `mingw-w64-asciidoctor-extensions`

**Comment by nalla** [comment]
`depends.exe` confirmed that the updated `psych.o` indeed is now looking for `libyaml-0-2.dll`.

**Comment by dscho** [comment]
Good analysis. Unfortunately, I won't have time to test this, but I think the `depends.exe` test confirms that this bug is fixed now.
