### ISSUE TITLE
git msutters/making-changes /n warning: failed to restrict file handles (2)

### ISSUE THREAD

**Issue by Chekonjak** [git-for-windows/git#1490]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64 bit.

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? 64-bit Windows 10 Pro.

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17074.1002]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults? Defaults, integrated into Intellij IDEA.

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Running the community edition of my IDE.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Intellij IDEA terminal.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Cannot recall exactly (sorry for the Sessions joke). I was committing a new branch for the first time.
```
 - What did you expect to occur after running these commands?

No error message.

 - What actually happened instead?

failed to restrict file handles error message and a message to post the bug here.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repo.

**Comment by dscho** [comment]
`** insert [...] here **` is far from a helpful report. In the least, the circumstances need to be described when this happens.

**Comment by BasementGamer** [comment]
I am getting this error. This is the output from git:

warning: failed to restrict file handles (2)

handle #0: 0000000000000154 (type 3, handle info (1) 0
handle #1: 0000000000000158 (type 3, handle info (1) 1
handle #2: 000000000000013c (type 2, handle info (1) 1

This happens when calling git on a previously cloned repository

**Comment by dscho** [comment]
> warning: failed to restrict file handles (2)

@BasementGamer that's ERROR_FILE_NOT_FOUND.

> This happens when calling git on a previously cloned repository

That is definitely not specific enough. *What* Git command did you call? And was the snippet you showed from the output really all that was shown?

> warning: failed to restrict file handles (87)
> [...]
> win7 sp1 x64

@bughit I *think* I fixed that in 64b1c47b8100207e39432add27dbcab109f06763. The snapshot is building as we speak, and will be available here: https://wingit.blob.core.windows.net/files/index.html (the latest snapshot currently listed is the one built from commit d1a7b3b9ef which does *not* have the fix yet). Once it hits the download site, I would like to ask you to test it.

**Comment by clemans** [comment]
Checking in to say this is an error I received as well.
Operating System: Windows 10 x64 1709 
git version 2.16.1.windows.4

**Comment by Chekonjak** [comment]
Sorry for the lack of specificity. I'm very new to Git, and I didn't know how to answer a lot of the questions correctly. It happened when I was trying to commit and push changes from a repo that I'd just cloned.

**Comment by dscho** [comment]
> Checking in to say this is an error I received as well.

Checking in to say that I would *really* need to know what commands, in what environment, you called, and what is the precise error message. I really cannot help you when given only vague information.

> I'm very new to Git, and I didn't know how to answer a lot of the questions correctly. It happened when I was trying to commit and push changes from a repo that I'd just cloned.

The easy way out from this conundrum is to simply copy/paste the precise text from your window. That way, you do not have to bother with trying to be careful, as copy/paste will be faithful by default.

**Comment by dscho** [comment]
Also, y'all, there were a couple of recent changes that may fix things for you. You may want to check out the latest snapshot: https://wingit.blob.core.windows.net/files/index.html. And you may want to be helpful and come back to this ticket with copy/pasted output if the problem still persists, or with the feedback that the recent changes fixed your problem.

**Comment by Chekonjak** [comment]
Is the lesson here that ignoring an error message is better than submitting a vague report?

**Comment by Chekonjak** [comment]
Install options: 

$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

**Comment by dscho** [comment]
@Chekonjak could you give the latest snapshot a try? You will find snapshots here: https://wingit.blob.core.windows.net/files/index.html

**Comment by dscho** [comment]
I will just assume that this is addressed.
