### ISSUE TITLE
Make git diff output easier to understand

### ISSUE THREAD

**Issue by nautilus7** [git-for-windows/git#1494]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git diff
```
 - What did you expect to occur after running these commands?

Well what I am seeing is not actually a bug. It's just that the output of the git diff command is a little bit different than than output of the **svn diff** command. For example look the attached picture. There are 3 lines inserted into the modified file. Then, on the left we have the output of the git diff and on the right we have the output of the svn diff. You see that while technically both are correct, the svn diff produces an easier to read and understand diff file. **The added lines make more sense in the svn diff file.**

(The actual git diff file is produced by an .sh script which calls git diff and then alters the output to be svn compatible. That's why you see the `@@ -6338,6 +6435,9 @@` line altered. This is not relevant to my request here though.)

So, can the git diff behavior become more similar to the svn diff?

![git-diff-svn-diff](https://user-images.githubusercontent.com/1540233/36147987-ff4a24c0-10c2-11e8-806c-c4480105dfd8.png)

**Comment by linquize** [comment]
Upstream git is also the same. Should report to git mailing list.

**Comment by dscho** [comment]
I agree that this is an upstream issue, i.e. an issue for [the Git mailing list](mailto:git@vger.kernel.org). Two things to note:

1. There have been a few discussions recently about better diff heuristics, see e.g. https://public-inbox.org/git/20171029151228.607834-1-cmn@dwim.me/
2. You definitely want to make sure to turn off HTML mails when sending to that mailing list, as even an alternative HTML will get the mail dropped :-(
