### ISSUE TITLE
Git hangs on MinTTY due to GPG signing

### ISSUE THREAD

**Issue by wolfy1339** [git-for-windows/git#1499]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.0.windows.2
cpu: x86_64
built from commit: a56c4f9e2a9513d2be57dc4346e0e84887399cd9
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? Windows 10 1710 64bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.192]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add src
git commit --amend
```
 - What did you expect to occur after running these commands?

For git to amend the commit properly

 - What actually happened instead?

Git hangs after the editor closes

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/wolfy1339/Wolfy-Powder-Toy/tree/c%2B%2B-modernization

**Comment by wolfy1339** [comment]
After updating and restarting my system, git bash won't open

**Comment by dscho** [comment]
Could you reinstall with the terminal option `ConHost` instead of `MinTTY` and see whether this works around the problem?

(I am not trying to suggest this as a permanent workaround, but poking at your setup with the hopes of understanding what the heck is going wrong.)

**Comment by wolfy1339** [comment]
This is definitely related to GPG signing. It also happens on `git rebase`
Using `ConHost` works as expected.

**Comment by dscho** [comment]
So you are not using the `gpg.exe` included in Git for Windows?

**Comment by wolfy1339** [comment]
It crashes. 
```
3 [main] gpg (15396) C:\Program Files\Git\usr\bin\gpg.exe: *** fatal error - cygheap base mismatch detected - 0x1802F7408/0x180301410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by dscho** [comment]
> It crashes.

That's too bad. Could you follow the steps described in https://github.com/git-for-windows/git/wiki/32-bit-issues#adjusting-msys-20dlls-address-range-manually (please ignore that this page talks about 32-bit for the moment) and see whether it fixes that cygheap base mismatch problem?

**Comment by dscho** [comment]
I hope my suggestion helped.
