### ISSUE TITLE
Git Bash Not Working in ConEmu After Update

### ISSUE THREAD

**Issue by connerbw** [git-for-windows/git#1500]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.16299.248]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu build: 180206 [64] {Alpha}

 - What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

```
 + Launch ConEmu
 + Git Bash
```
 - What did you expect to occur after running these commands?

Git Bash

 - What actually happened instead?

 > ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
 > Press Enter or Esc to close console...

### Possibly Related?

+ https://github.com/Maximus5/ConEmu/issues/1450
+ https://github.com/git-for-windows/git/issues/1473#issuecomment-365056424

**Comment by Maximus5** [comment]
Definitely related to #1473.

If you force terminal to `xterm` instead of default `xterm-256color` it works properly.

```
set "PATH=%ProgramFiles%\Git\usr\bin;%PATH%" & "%ProgramFiles%\Git\git-cmd.exe" --no-cd --command=%ConEmuBaseDirShort%\conemu-msys2-64.exe -t xterm /usr/bin/bash.exe -l -i -new_console:p
```

**Comment by glhez** [comment]
I had the same problem. Setting TERM=xterm (default was cygwin) seems to fix the issue, at least for the moment. I got a nice less stackdump which is probably unusable as is.

**Comment by mhou1981** [comment]
Even the plain Git Bash stop working.  Have to go into the ~/.minttyrc and remove this line in order for it to work:
`Term=xterm-256color`

**Comment by dscho** [comment]
Could you test the newest snapshot from https://wingit.blob.core.windows.net/files/index.html, please? I *hope* it fixes this issue (which I believe is the same as in #1473).

**Comment by dscho** [comment]
Thanks for confirming!
