### ISSUE TITLE
Unable to push to remote via SSH & Cygwin error/bug message

### ISSUE THREAD

**Issue by Kyle-Koivukangas** [git-for-windows/git#1501]
I'm having issues pushing to a custom remote, it denies my SSH keys even though I know the keys work, I've pushed to this remote with this key before and the key works fine to ssh in to the server. I'm able to push to github without ssh just fine, I don't have an ssh key set up with my github account so I haven't tested that. I also don't have any other repositories or remote servers to try pushing to. 

I've tried every type of shell I have on my computer and it doesn't work for any of them, they all give the same error 'Permission denied (publickey)'; except cygwin, which gives a unique error:
```
warning: failed to restrict file handles (2)

handle #0: 0000000000000128 (type 3, handle info (1) 0
handle #1: 000000000000012c (type 3, handle info (1) 1
handle #2: 0000000000000408 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn /c/Program Files (x86)/Git/bin/ssh.exe: No such file or directory
fatal: unable to fork


```

### Setup

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [Version 10.0.16299.248]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Path Option: CmdTools
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
I've tried reinstalling git multiple times with plink or openSSH options, I've recently installed cygwin and ubuntu bash for windows, not sure if that's the culprit. I also have all the issues that others are having with being unable to use SSH at all (always says public key denied even though the key works with regular ssh in terminal) and having it hang in conemu. I've tried pushing to remote with ssh in many shells (conemu (powershell), cygwin, ubuntu bash) none of them work.

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ALL OF THEM. lol
The results are all the same: "Permission denied (publickey)" or "FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)"

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push staging master

```
 - What did you expect to occur after running these commands?

Was expecting to push master branch to remote using the ssh key specified in my config.

 - What actually happened instead?

public key was denied error in every shell I've tried, cygwin which gives a unique error that prompted me to report this bug.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/Kyle-Koivukangas/My-Website-V2.0

**Comment by dscho** [comment]
> ```
> error: cannot spawn /c/Program Files (x86)/Git/bin/ssh.exe: No such file or directory
> ```

Hmm. This looks wrong, as you reported using a 64-bit Git (which should live in `/c/Program Files/Git`) and Git for Windows 2.x (where the `ssh.exe` should live in `usr/bin`, not in `bin`).

Is it possible that your environment contains something like `GIT_SSH` or `GIT_SSH_COMMAND`?

**Comment by Kyle-Koivukangas** [comment]
Oh you're right, I tried a bunch of stuff to get it working and installed the 32 bit version and changed environment variables, I have removed the .profile config settings and the cygwin error doesn't show, it now gives the same error as the other shells: "FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)" .

I'm not sure why it's not working I've tried changing a bunch of variables and have tried with plink/putty and openssh keys, it used to work just fine. 

This is my .ssh/config file:
```
Host 107.107.168.191
    HostName 107.107.168.191
    User root
    IdentityFile ~/.ssh/myWebsite
    IdentitiesOnly yes
```
I've tried changing all the settings to see if I was doing something wrong but it's the same result every time. The key works everywhere else except git, and it used to work with git.

**Comment by Kyle-Koivukangas** [comment]
I have the same config for my git config in ubuntu bash environment and I get this error: 

```
Permission denied (publickey).

```
Yet that same key still works fine to ssh to the server in that environment, too.
Although the git version is different in that environment 
```
git version 2.7.4
```
which makes me think maybe I've done something stupid and it's not a bug..

**Comment by Kyle-Koivukangas** [comment]
You know what, I think I must have screwed everything up trying to fix it last night, I was pretty tired and lost track of what I had changed. I started from scratch and set everything up with tortoise and put my key in to pageant and its working fine now. Sorry for bothering you.
