### ISSUE TITLE
Add git-lfs to path

### ISSUE THREAD

**Issue by pascalberger** [git-for-windows/git#1503]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.248]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Installer 

 - What did you expect to occur after running these commands?

It would be nice if installing Git for Windows with git-lfs is sufficient to have LFS support in VIsual Studio.

 - What actually happened instead?

Git for Windows installs git-lfs to `c:\Program Files\Git\mingw64\bin\git-lfs.exe`, without `git-lfs.exe` being available on the path. While this works for standalone Git installation, this doesn't work for Visual Studio which has its own Git installation and cannot find git-lfs. Therefore currently it is required to still install git-lfs using the standalone installer (or put `git-lfs` in the path otherwise)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by shiftkey** [comment]
> While this works for standalone Git installation, this doesn't work for Visual Studio which has its own Git installation and cannot find git-lfs. 

This behaviour was changed a while ago, https://github.com/git-for-windows/build-extra/pull/141 is the context, and I'll point out this comment:

> This prevents an issue where the user may have an older version of LFS
installed by itself and 'git-lfs' finds that version while 'git lfs' finds
the bundled version.

I'll also let @dscho chime in and see if he knows anyone on the VS team who look after the Git integration to see if they can provide any additional help.

**Comment by dscho** [comment]
@shiftkey thank you for explaining the reasoning. That's precisely what my thinking was, too.

As to Visual Studio supporting Git LFS: If I remember correctly, the official Git LFS installer from the [Git LFS project](https://git-lfs.github.io/) installs Git LFS into the `PATH`, and that should address your concerns.

I deem this ticket independent of Git for Windows itself.

**Comment by pascalberger** [comment]
> This prevents an issue where the user may have an older version of LFS installed by itself and 'git-lfs' finds that version while 'git lfs' finds the bundled version.

But this is the current behavior. If I have Git for Windows with Git LFS installed and also the standalone Git LFS installer, `git lfs` will use LFS version shipped with Git for Windows, while `git-lfs` will use the version from the standalone installer from `cmd.exe`. It will use the version from Git for Windows for both commands in a Git bash shell though, as `mingw32\bin` is on the path there. So behavior is currently inconsistent between different shells.

Using the standalone Git LFS installer puts `git-lfs` on the PATH, and is what we're using currently for getting LFS support in Visual Studio. But it would be nice if we can use the Git LFS version shipped with Git for Windows.

**Comment by dscho** [comment]
@pascalberger I understand your concerns. In your scenario, I would highly recommend *not* using Git for Windows' embedded Git LFS, but only the Git LFS installed by the official Git LFS installer.

**Comment by dscho** [comment]
@pascalberger unless you have an idea how we can make your desired feature work: we *cannot* add `mingw64\bin` to the `PATH`, as it has too much stuff in it that we do not want to expose to the user. For example, this addition would override `find` and `sort`, breaking all kinds of Windows scripts...

I'll keep this ticket open for a couple of days in the hope that you can come up with a solution other than [what I suggested](https://github.com/git-for-windows/git/issues/1503#issuecomment-366666944).

**Comment by pascalberger** [comment]
@dscho Would it be possible to add a symlink for `git-lfs.exe` to the `bin` path which links to the exe in the `mingw64\bin` path? Or how is it done for `git.exe`?

**Comment by dscho** [comment]
@pascalberger for `git.exe`, there is [a wrapper](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/git-wrapper.c) in `cmd\git.exe` which simply calls `mingw64\bin\git.exe` after setting up a couple of environment variables. We could of course do the same for `git-lfs.exe`, for which we would most likely have to add some code [here](https://github.com/git-for-windows/MINGW-packages/blob/6d1190a1963c7247c8fab609c5c5eb6279124239/mingw-w64-git/git-wrapper.c#L518) (imitating the `git.exe` case to a certain extent).

And then we would need to hard-link/copy the wrapper to `git-lfs.exe` by calling [`CopyBuiltin(AppDir+'\cmd\git-lfs.exe');`](https://github.com/git-for-windows/build-extra/blob/34b974595c593c138ebc72cb55763c2729cdb12a/installer/install.iss#L1574-L1603) probably at the same location where [the builtins are hard-linked/copied](https://github.com/git-for-windows/build-extra/blob/34b974595c593c138ebc72cb55763c2729cdb12a/installer/install.iss#L1821-L1834), but guarded by an [`if IsComponentSelected('gitlfs') then ...`](https://github.com/git-for-windows/build-extra/blob/34b974595c593c138ebc72cb55763c2729cdb12a/installer/install.iss#L2086).

We would then also have to take care of deleting that file at uninstall time, most likely it will suffice to add it to the [`[UninstallDelete]` section](https://github.com/git-for-windows/build-extra/blob/34b974595c593c138ebc72cb55763c2729cdb12a/installer/install.iss#L205-L209).

@pascalberger how about giving it a try?

**Comment by dscho** [comment]
Thank you! @stffabi!

**Comment by stffabi** [comment]
@dscho thanks so much for merging the changes. I was just able to compile the new installer and test it. Unfortunately it seems like the [CopyBuiltin](https://github.com/git-for-windows/build-extra/blob/34b974595c593c138ebc72cb55763c2729cdb12a/installer/install.iss#L1574-L1603) currently doesn't work as we both expected.

On line [L1590](https://github.com/git-for-windows/build-extra/blob/34b974595c593c138ebc72cb55763c2729cdb12a/installer/install.iss#L1590) for newer windows versions as target for the hardlink `git.exe` will be used. Therefore this won't work for the `git-lfs` case. Sorry for that, but I've just seen that the second you've merged...

Is this the intended behaviour or should this case also be hardlinked to `git-wrapper.exe`? Or was here the intention to only use the `git-wrapper.exe` in the fallback case where normal copies of the file will be created and to minimize the used disk space there?

**Comment by dscho** [comment]
> On line L1590 for newer windows versions as target for the hardlink git.exe will be used. Therefore this won't work for the git-lfs case

But it is `bin\git.exe` that is used. That should be a copy of the Git wrapper itself...

**Comment by dscho** [comment]
(Note the difference between `bin\git.exe`, which is installed only for legacy purposes, and `mingw64\bin\git.exe`, which is the real `git.exe`.)

**Comment by stffabi** [comment]
Okey, but then installer seems to use the wrong destination.

Line 1590: `LinkCreated:=CreateHardLink(FileName,AppDir+'\{#MINGW_BITNESS}\bin\git.exe',0);`

The resulted hardlink would map to `mingw64\bin\git.exe` and therefore the real `git.exe`.

**Comment by stffabi** [comment]
So we should change the line to: `LinkCreated:=CreateHardLink(FileName,AppDir+'\bin\git.exe',0);`

**Comment by dscho** [comment]
Oh, you're right! Darn, my brain is rotten today. I'll fix it up.

**Comment by dscho** [comment]
Thanks @sentiment-bot! I am sorry 😄

**Comment by stffabi** [comment]
@dscho I may create another PR for this if you would like, I'm just testing the change :)

**Comment by dscho** [comment]
Oh, I have the change, too...

**Comment by dscho** [comment]
https://github.com/git-for-windows/build-extra/compare/master...dscho:fix-git-lfs-hardlink

**Comment by stffabi** [comment]
Great, thanks then I'll let you merge yours :)...

**Comment by dscho** [comment]
Could you give this a quick glance-over?

**Comment by dscho** [comment]
Now it is even a PR: https://github.com/git-for-windows/build-extra/pull/174

**Comment by dscho** [comment]
Oh, and if you could test it, that would be awesome and give me the time to look at two other tickets... :blus

**Comment by stffabi** [comment]
Sure, I'll let you know the results of my test.

**Comment by dscho** [comment]
@stffabi thank you so much!

**Comment by stffabi** [comment]
@dscho you're welcome. I've left some comments directly on the PR.
