### ISSUE TITLE
git.sln is reported as "corrupt" by Visual Studio 2017

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#1507]
When I open `git.sln` in Visual Studio 2017 (v15.5), I get the following popup:

![image](https://user-images.githubusercontent.com/1768054/36433622-8ad94674-1622-11e8-87f2-ce4d712ccaf9.png)

I have the following SHA1 checked out: `4dab739100908644a76f3f06388bd2d250331b89` (tip of `vs/master`). Followed the steps on the [Visual Studio wiki page](https://github.com/git-for-windows/git/wiki/Compiling-Git-with-Visual-Studio).

**Comment by dscho** [comment]
Known issue. This is where I am at: https://github.com/git-for-windows/git/compare/master...dscho:fix-vcxproj-generation. I just need more time to work on it. There are higher-priority issues, though.

**Comment by rcdailey** [comment]
Thanks for the quick response. I know this is an unrelated (and much bigger) topic, but has CMake been discussed instead of a custom script to generate VS projects? I saw in the original PR for the VS support that you had concerns with VS2015 not being supported. CMake would give you every version. Just a thought. I may spend some time dropping some CMake scripts in and see how it fares. Seems simpler to me.

**Comment by dscho** [comment]
CMake has been discussed. On the Git mailing list, as it is appropriate.

**Comment by AnthonyIacono** [comment]
I wouldn't care about this issue but I am getting stuck trying to building within the SDK environment.

> make: *** [Makefile:1983: perl/PM.stamp] Error 127

**Comment by dscho** [comment]
@AnthonyIacono if you are getting stuck trying to build within the SDK, it would probably make more sense to open a new ticket, and describe your setup as well as the precise error (what command was invoked, full error message) in detail.
