### ISSUE TITLE
Git shortcuts start flashback and generate files called 'mintty.exe.stackdump'

### ISSUE THREAD

**Issue by jelly54** [git-for-windows/git#1509]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

**'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
win 10 64 bit
```
$ cmd.exe /c ver

** Microsoft Windows [版本 10.0.16299.15] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults 
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
**
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** 1.i just reinstall the win10 system and  activated myself 
     2.i install it in d:/  not use default install location**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**double-click the icon, or in the right-click menu git-bash here**
```
 - What did you expect to occur after running these commands?

**The status window does not exit quickly **

 - What actually happened instead?

** The status window  exit quickly  and generate file 'mintty.exe.stackdump'  after me click it

Exception: STATUS_ACCESS_VIOLATION at rip=00100409BA8
rax=FFFFFFFFFFFFFFFF rbx=00000000FFFFC5E0 rcx=0000000000000000
rdx=0000000000000001 rsi=0000000100468620 rdi=00000000FFFFC5DC
r8 =03FFFFFFFFFFFFFF r9 =8000000000000000 r10=0000000000000000
r11=0000000000000246 r12=0000000100468B20 r13=0000000100468608
r14=0000000000000018 r15=000000000000000E
rbp=0000000100468B20 rsp=00000000FFFFC590
program=E:\Tools\Git\usr\bin\mintty.exe, pid 4540, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00100468B20  00100409BA8 (000FFFFC6D0, 7FFC87332390, 7FFC87332390, 00600000001)
000FFFFC6D0  00100437165 (0018018C93A, 000FFFFCC51, 001800576A0, 00600041410)
000FFFFCCB0  00180047C07 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045873 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045924 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Can you please test the newest snapshot at https://wingit.blob.core.windows.net/files/index.html?

**Comment by jelly54** [comment]
Thanks ,but i fail again.The same problem,when I double-click the icon, or in the right-click menu git-bash here there will be seconds dialog and exit, then generate file 'mintty.exe.stackdump'.
```Exception: STATUS_ACCESS_VIOLATION at rip=00100409CA8
rax=FFFFFFFFFFFFFFFF rbx=00000000FFFFC410 rcx=0000000000000000
rdx=0000000000000001 rsi=000000010047E6E0 rdi=00000000FFFFC40C
r8 =03FFFFFFFFFFFFFF r9 =8000000000000000 r10=0000000000000000
r11=00000000002B1800 r12=000000010047EC20 r13=000000010047EAC8
r14=000000000000000E r15=00000000FFFFCB50
rbp=000000010047EC20 rsp=00000000FFFFC3C0
program=E:\Tools\Git\usr\bin\mintty.exe, pid 7264, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0010047EC20  00100409CA8 (000FFFFC500, 7FFD084D2390, 7FFD084D2390, 00600000001)
000FFFFC500  00100438A15 (0018018D09A, 000FFFFCC51, 00180057410, 00600071470)
000FFFFCCB0  001800479F7 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045663 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045714 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
`
this time i chose 'windows explorer integration' all, Git LFS (Large File Support), Associate .git*configuration files... and  Associate .sh file to be run withBash

then chose the 'use vim(the ubiquitous text editor) as git's default editor' ,

next chose  'use Git from Git Bash only', 'Use the Openssl Library' , 'CHeckout windows-style,commit Unix-sytle line endings' and 'Use MinTTY(the default terminal of MSYS2' (I think may be this is the problem).

then chose  Enable file system caching  and Enable Git Credential Manager

but i do not use the default installation location and I changed it to E drive。

Thank you for helping me.

**Comment by jelly54** [comment]
i do not understand this error log, is not this mintty.exe what other configuration?

**Comment by dscho** [comment]
> Thank you for helping me.

I would like you to help me first. Your bug report left most of the `** insert here **` placeholders unchanged. Please fill them in, with the latest state of affairs (i.e. after installing the snapshot installer). This information, for example, will be a lot more precise than an ad-hoc account of what installation options you remember:

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

> but i do not use the default installation location and I changed it to E drive。

Is that an NTFS drive?

Please, try to provide as much information (including potentially-relevant information you can think of, such as firewall, antivirus, proxy, etc) as you can. The problem you describe is really hard to debug, and the more information you can provide, the more likely you make it for somebody else to reproduce the problem (which is important for debugging).

**Comment by jelly54** [comment]
sorry，I am an entry level and i know little about git .If you need to know some message please teache me where i can find it or how i can judge it.
`Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
`
i  see someone said there is a problem win10 Professional Edition which Non-normal activation on Google and i just reinstall the system myself activated.I do not know if this is relevant

**Comment by dscho** [comment]
Thank you. I do see a lot of other questions still unanswered, though, starting with:

> ```cmd
> $ cmd.exe /c ver
> ```
> 
> ** insert your machine's response here **

This issue reporting template has been crafted carefully, with the intention to help you provide enough information so that people more familiar with Git's internals than you are can help you. Please do not just ignore the template, and please refrain from making me spend time asking you for every single bit of information. I would much rather spend my time figuring out bugs, which I am busy doing for another reported bug as we speak (I had a few minutes waiting for a build).

**Comment by jelly54** [comment]
OK，i know. I have made the original question changed. Excuse me, look at it again.

**Comment by dscho** [comment]
> $ git --version --build-options **'git' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 **

Can you try this again, this time in either Git Bash or Git CMD?

> double-click the icon

Which icon? In the Start Menu? What label does the icon have?

Did it work with a previous Git for Windows version? If so, which one was the last working version?

**Comment by jelly54** [comment]
run 'git --version --build-options'  in Windows cmd. it show the following

 **'git' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 **

the icon is the right-mouse menu

**Comment by dscho** [comment]
> **fatal: open /dev/null or dup failed: No such file or directory **

This sounds very familiar: it seems that this ticket is a duplicate of #1016 and #1400. Look in particular at [this comment](https://github.com/git-for-windows/git/issues/1016#issuecomment-274229032)...
