### ISSUE TITLE
git clone failed: fatal: Out of memory, malloc failed (tried to allocate 272059101 bytes) fatal: index-pack failed

### ISSUE THREAD

**Issue by navechan** [git-for-windows/git#1511]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

$ git --version --build-options

** insert your machine's response here **
git version 1.8.2.2

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Linux 64bit
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> ** insert your machine's response here **
> git version 1.8.2.2

Sorry, this version is no longer supported. Not even the 1.x versions are supported any longer, we are at [v2.16.2](https://github.com/git-for-windows/git/releases/tag/v2.16.2.windows.1) now. Please test that version and report back whether this fixes your problem (it will fix tons of security issues at the same time to which you are still exposed, and they are not even funny).

BTW if your `git version` really prints `1.8.2.2`, you probably are not even using Git for Windows (it would probably show something like `1.8.2.2.msysgit.0` even if that version was never released). Please clarify. Your bug report left pretty much all of the questions open, unhelpfully leaving all of the `** insert here **` in place, unchanged. To be quite honest, that shows a bit of disrespect to the people you are asking for help.

**Comment by dscho** [comment]
Silence can be a beautiful thing.
