### ISSUE TITLE
automate "git update-git-for-windows" ....

### ISSUE THREAD

**Issue by Dutchglory** [git-for-windows/git#1512]
when you run "git update-git-for-windows" it always ask's for confirmation.  
Would it be possible to add a  "-Y" (default=yes) option to bypass the confirmation... 
 
especially when you run git automatically (with batch script or other way)

thanks
...

**Comment by shiftkey** [comment]
@Dutchglory the script is here: https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-update-git-for-windows

You can pass `-y` or `--yes` in to bypass the confirmation.

**Comment by Dutchglory** [comment]
Ok thanks

**Comment by shiftkey** [comment]
One thing I noticed as part of this is that `--help` doesn't behave as expected:

```
$ git --version
git version 2.16.2.windows.1

$ git update-git-for-windows --help
The system cannot find the file C:\Program Files\Git\mingw64/share/doc/git-doc/git-update-git-for-windows.html.
```

@dscho I had a look into this code path and it's being intercepted by Git:

```
$ GIT_TRACE=1 git update-git-for-windows --help
21:42:17.180112 git.c:344               trace: built-in: git 'help' '--exclude-guides' 'update-git-for-windows'
21:42:17.212369 exec_cmd.c:132          trace: exec: 'git' 'web--browse' '-c' 'help.browser' 'C:\Program Files\Git\mingw64/share/doc/git-doc/git-update-git-for-windows.html'
21:42:17.242587 git.c:576               trace: exec: 'git-web--browse' '-c' 'help.browser' 'C:\Program Files\Git\mingw64/share/doc/git-doc/git-update-git-for-windows.html'
21:42:17.242587 run-command.c:627       trace: run_command: 'git-web--browse' '-c' 'help.browser' 'C:\Program Files\Git\mingw64/share/doc/git-doc/git-update-git-for-windows.html'
21:42:17.555087 git.c:576               trace: exec: 'git-sh-i18n--envsubst' '--variables' 'usage: $dashless $USAGE'
21:42:17.555087 run-command.c:627       trace: run_command: 'git-sh-i18n--envsubst' '--variables' 'usage: $dashless $USAGE'
21:42:17.633220 git.c:576               trace: exec: 'git-sh-i18n--envsubst' 'usage: $dashless $USAGE'
21:42:17.633220 run-command.c:627       trace: run_command: 'git-sh-i18n--envsubst' 'usage: $dashless $USAGE'
21:42:17.789495 git.c:344               trace: built-in: git 'config' 'help.browser'
21:42:17.837068 git.c:344               trace: built-in: git 'config' 'web.browser'
21:42:17.898829 git.c:344               trace: built-in: git 'config' 'browser.start.path'
The system cannot find the file C:\Program Files\Git\mingw64/share/doc/git-doc/git-update-git-for-windows.html.
```

Any pointers on how/whether we can bypass this to run the script directly with `--help`?

**Comment by dscho** [comment]
@shiftkey try `-h`:

```
$ git update-git-for-windows -h
Usage: git update-git-for-windows [options]
Options:
        -g, --gui Use GUI instead of terminal to prompt
        -y, --yes Automatic yes to download and install prompt
```

Also, `--help` cannot be bypassed. But what you can do is to add documentation by providing, say, a Markdown document that would then be turned into the appropriate `.html` file in the appropriate location by `git-extra`'s build script.

This document would make for a pretty good contribution via PR to https://github.com/git-for-windows/build-extra/tree/master/git-extra.

@Dutchglory you up for giving back to the project?

**Comment by Dutchglory** [comment]
unfortunately i don't have any programming experience...  
but translating to dutch NL would be possible ...

**Comment by dscho** [comment]
@Dutchglory I suspected that you have no programming experience. Hence my suggestion to write a Markdown document serving as documentation for the `git update-git-for-windows` command. You can do that without programming experience.
