### ISSUE TITLE
Installer doesn't detect VSCode Insiders.

### ISSUE THREAD

**Issue by NatoBoram** [git-for-windows/git#1513]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

`Git-2.16.2-64-bit.exe`

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```CMD
cmd.exe /c ver
Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

`Use VisualStudioCode as Git's default editor.`

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

[Visual Studio Code Insiders](https://code.visualstudio.com/insiders/) is installed.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

`start "Git for Windows" "Git-2.16.2-64-bit.exe"`

 - What did you expect to occur after running these commands?

The installer should detect that VSCode is installed.

 - What actually happened instead?

The installed doesn't allow me to install Git for Windows.

![Git for Windows](https://user-images.githubusercontent.com/10495562/36573297-237bf312-180e-11e8-9379-f752a89cb974.PNG)

**Comment by shiftkey** [comment]
> `Visual Studio Code Insiders` is installed.

I think this is the problem, because Insiders and Stable can be installed alongside eachother they use a different registry key. 

From this snippet in the installer: https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss#L1129-L1132

```
EditorAvailable[GE_VisualStudioCode]:=RegQueryStringValue(HKEY_LOCAL_MACHINE,'SOFTWARE\Classes\Applications\Code.exe\shell\open\command','',VisualStudioCodePath);
```

The Insiders build of VSCode sets a different registry key (the whitespace is important):

```
SOFTWARE\Classes\Applications\Code - Insiders.exe\shell\open\command
```

@dscho put together a guide to show how to [create your own installer](https://github.com/git-for-windows/git/wiki/Making-an-installer), after [setting up the SDK](https://github.com/git-for-windows/build-extra#build-environment-for-git-for-windows), if someone wants to have a go at modifying the install script.

**Comment by shiftkey** [comment]
As you can install VSCode Stable and Insiders side-by-side, this probably means the installer should let you choose between one or the other.

**Comment by dscho** [comment]
> As you can install VSCode Stable and Insiders side-by-side, this probably means the installer should let you choose between one or the other.

I agree.

@NatoBoram you can easily get the feature you desire by following the guides @shiftkey mentioned and by editing `/usr/src/build-extra/installer/install.iss`, imitating what was done for Visual Studio Code (just look for "VisualStudioCode"). If you then open a Pull Request to https://github.com/git-for-windows/build-extra, you will even get this feature in the official installers.

**Comment by jwittner** [comment]
I'm seeing the same issue, but I don't have the insider build. It doesn't appear to me that I have a `shell` folder underneath `Code.exe` in my registry path. Is that perhaps a new entry that's not applied on updates of VSCode?

My version info:

![image](https://user-images.githubusercontent.com/12958442/36755571-75c0cd44-1bc1-11e8-89e5-6629c7647fd4.png)

**Comment by dscho** [comment]
@jwittner the same applies to you as [what I told @NatoBoram](https://github.com/git-for-windows/git/issues/1513#issuecomment-367888193)...

**Comment by justalemon** [comment]
![imagen](https://user-images.githubusercontent.com/11861253/38789331-ed25e0ea-410f-11e8-82ea-599633dcb3b2.png)

I'm using `Windows 10 v1709 c16299.371`.

**Comment by justalemon** [comment]
As a side note, [this](https://github.com/desktop/desktop/blob/master/app/src/lib/editors/win32.ts) is how GitHub Desktop detects Code and Code Insiders at the same time (more info on desktop/desktop#3011).

**Comment by dscho** [comment]
@justalemon so how about giving it a try? https://github.com/git-for-windows/git/wiki/Making-an-installer should help making an installer, and the `/usr/src/build-extra/installer/install.iss` file is the one needing to be patches.

**Comment by justalemon** [comment]
@dscho Thanks for the idea! I forked [build-extra](https://github.com/git-for-windows/build-extra) to [my account](https://github.com/justalemon/build-extra) and i'm ready to send the Pull Request.

**Comment by schemburkar** [comment]
I hit this again.

Setting up the following registry key resolved the issue

SOFTWARE\Classes\Applications\Code - Insiders.exe\shell\open\command

**Comment by justalemon** [comment]
`HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Applications\Code - Insiders.exe\shell\open\command` will be created during the install of VS Code Insiders if you used Microsoft's installer from [here](https://code.visualstudio.com/insiders/).

**Comment by dscho** [comment]
> If you used the .zip file or it was built by yourself, then the registry key does not exist.

Is that what we were missing all along, that people "installed" from `.zip`? I do not recall reading any hint about this earlier.

**Comment by schemburkar** [comment]
@justalemon I actually did install from the site using the installer VSCodeSetup-x64-1.25.0-insider.exe. it did not create the registry keys.
Even the console command 'code' does not work.
