### ISSUE TITLE
Discussion: Should we support /bin directory for backwards compability?

### ISSUE THREAD

**Issue by nalla** [git-for-windows/git#152]
It was discovered in https://jira.atlassian.com/browse/SRCTREEWIN-3226 that e.g. *Sourcetree* is depending on `git.exe` being in a specific directory. The workaround in the linked issue is making that directory available again as symbolic link.
```
C:\Program Files\Git>mklink /D bin cmd
symbolic link created for bin <<===>> cmd
```
So is this something *we* should provide? Or is it something that *3rd parties* have to deal with. The **pro** would be to support old scripts and maybe other *3rd parties* that rely on `git.exe` is in the `/bin` directory.

The **con** would be to maintain that feature. I believe for the portable installation that would be a *no go* because of the `FAT` compatibility?

**Comment by shiftkey** [comment]
Tentative :thumbsdown: - I'd rather keep `git-for-windows` as simple as possible.

**Comment by dscho** [comment]
I think the biggest problem is that they used `/bin/git.exe` instead of `/cmd/git.exe`. An obvious mistake to make, of course, but a mistake nevertheless.

**Comment by nalla** [comment]
I think they used `/bin/git.exe` because `msysgit` shipped *Git for Windows 1.x* that way. Maybe we could create some sort of *architecture description* / *program structure readme* that ships with the *Git for Windows SDK*. Maybe outline the differences that were introduces with the switch from *msysgit* to *Git for Windows SDK*. That way *3rd parties* can easily see the outline of the resulting installer. But I think that is something with very low priority.

**Comment by dscho** [comment]
Git for Windows 1.x contains that `/cmd/` directory for quite a while now...

**Comment by nalla** [comment]
While that is true, I think their mistake was that they were depending on a folder structure that is *SDK* specific and not *Git for Windows* specific. While the */cmd* folder survived the *SDK* change, */bin* did not.

It *should* indeed be best practice to use the *Git for Windows* specific layout.
