### ISSUE TITLE
Git Bash input character missing after Ctrl+C of git diff and Terminal type ct100 crash forever

### ISSUE THREAD

**Issue by hanzhou** [git-for-windows/git#1521]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

none

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git diff (results large than one screen and needs Ctrl+C to quit)
Ctrl+C
type command in git bash (command can work but all characters are missing, see nothing)
```

```
change terminal type in Git Bash Properties to vt100, Git Bash crashes even if reinstalled
```

 - What did you expect to occur after running these commands?

input characters are visible
Git Bash works normally

**Comment by dscho** [comment]
> git diff (results large than one screen and needs Ctrl+C to quit) Ctrl+C type command in git bash (command can work but all characters are missing, see nothing)

Does `reset` help?

> change terminal type in Git Bash Properties to vt100, Git Bash crashes even if reinstalled

Can you test the latest snapshot at https://wingit.blob.core.windows.net/files/index.html? This might already be fixed.

**Comment by hanzhou** [comment]
perfectly solved~
