### ISSUE TITLE
Can't ignore folders with point in their names

### ISSUE THREAD

**Issue by MX-Lionel** [git-for-windows/git#1527]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
32-bit
```
$ git --version --build-options

** git version 1.9.4.msysgit.1 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
7 64-bit
```
$ cmd.exe /c ver

** Microsoft Windows [version 6.1.7601] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** File not found : GIT installed thru GIT-EXTENSIONS **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** No **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Console from GIT-EXTENSIONS **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** I ran Microsoft Visual Studio. My project is named "Mx.Tracteur.Asp.Web". **
```
 - What did you expect to occur after running these commands?

** I don't want to detect changes in the "Mx.Tracteur.Asp.Web/bin" and "Mx.Tracteur.Asp.Web/obj" folders like "/Mx.Tracteur.Asp.Web/bin/Mx.Tracteur.Asp.Web.dll". **

 - What actually happened instead?

** DLL files are detected in these folders. **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> ** git version 1.9.4.msysgit.1 **

Support for Git for Windows 1.x stopped in August 2015 (and support for 1.9.4.msysgit.1 was dropped as soon as 1.9.4.msysgit.2 was released).

Please try a current Git, e.g. from https://gitforwindows.org/.

But then, your issue might be Git Extensions specific. In that case, please take it up with [Git Extensions](https://sourceforge.net/projects/gitextensions/) (which is not affiliated with the Git for Windows project, but merely seems to bundle Git).
