### ISSUE TITLE
git-write-tree hangs

### ISSUE THREAD

**Issue by abergmeier** [git-for-windows/git#153]
Since two days I have the case that git commands like _fetch_ hangs and I cannot even kill it. Reinstalling git 2.4.1.1 makes it working again!? Any suggestions how to debug this?

**Comment by dscho** [comment]
I guess you want to set the environment variable `GIT_TRACE=1` to see in more detail what Git is trying to do at the moment.

**Comment by abergmeier** [comment]
The trace for `git fetch` says the following:

    git.c:348               trace: built-in: git 'fetch'
    run-command.c:347       trace: run_command: 'ssh' 'git@ourserver.net' 'git-upload-pack '\''ourprojects/project.git'\'''
    run-command.c:347       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'

**Comment by abergmeier** [comment]
Strange thing is, `git-rev-parse` cannot be killed.

**Comment by dscho** [comment]
I guess this is actually the same issue as https://github.com/git-for-windows/git/issues/158. If you leave the fetch running, does it eventually finish?

**Comment by dscho** [comment]
Actually, I am very convinced that that is the case. @abergmeier if you find that my conjecture is wrong, please reopen this ticket, I will then advise how to investigate further.

**Comment by abergmeier** [comment]
I am not so sure, since I disabled "file system caching" and it seems gone for now.
