### ISSUE TITLE
SUPPRESSMSGBOXES does not work for uninstall

### ISSUE THREAD

**Issue by tkleiber** [git-for-windows/git#1530]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Git-2.16.2-64-bit.exe  /VERYSILENT /NORESTART /NOCANCEL /SP- /CLOSEAPPLICATIONS /RESTARTAPPLICATIONS /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"
unins001.exe -ArgumentList "/VERYSILENT /NORESTART /NOCANCEL /SP- /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS"```
 - What did you expect to occur after running these commands?

 - What actually happened instead?

3 message boxes appear and are not suppressed:
- Are you sure you want to completely remove Git and all of its components?
- Progress dialog of deinstall (is closed wihout interaction)
- Git was successfully removed from your computer.


 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not relevant.

**Comment by dscho** [comment]
> unins001.exe -ArgumentList "/VERYSILENT /NORESTART /NOCANCEL /SP- /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS"```

Our own installer calls any previously version's uninstaller with `/VERYSILENT /SILENT /NORESTART /SUPPRESSMSGBOXES`: https://github.com/git-for-windows/build-extra/blob/922e32b5de8af3fff26d5f73a36ce1e9129a3d17/installer/install.iss#L1646

We do not see those message boxes. Probably due to the extra `/SILENT` option.

**Comment by tkleiber** [comment]
I had to remove "-ArgumentList" then my options works fine too.
ArgumentList seems to be an option of msiexec.
