### ISSUE TITLE
error with push hook on --set-upstream

### ISSUE THREAD

**Issue by jjoyave1** [git-for-windows/git#1532]
I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10 x64
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

powershell

```
// with pushhook [https://gist.github.com/jjoyave1/57ff3793f7f3c176107138c8d972492d]
set-upstream origin bf/resize-pmo-dash-gantt-on-max
```
 - What did you expect to occur after running these commands?

A simple push of a new branch instance to origin/[branchname]

 - What actually happened instead?

```
warning: failed to restrict file handles (2)

handle #0: 000000000000012c (type 3, handle info (1) 0
handle #1: 00000000000000f4 (type 2, handle info (1) 1
handle #2: 00000000000000f8 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://tfs.eyqahub.com/DefaultCollection/_git/TAS%20Suite'
C:\Source\TAS-Suite [bf/resize-pmo-dash-gantt-on-max +0 ~1 -0 !]> git -v
Unknown option: -v
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

(probably can't give that info, private firm with private TFS repo.)

**Comment by dscho** [comment]
> https://gist.github.com/jjoyave1/57ff3793f7f3c176107138c8d972492d

Sadly, this is a bit too much for a *Minimal*, Complete & Verifiable Example.

Do you see the same error when pushing with a much smaller `pre-push` hook, e.g.

```sh
#!/bin/sh

echo Hello
```

and/or without `--set-upstream-to`. In other words, can you wiggle down the complexity of your verifiable example?

**Comment by jjoyave1** [comment]
Coming back late -- I got around it by force committing the initial, for whatever reason it did not like remote being without the current branch.

**Comment by dscho** [comment]
So you never found out why the `pre-push` hook could not be executed, and now you cannot reproduce the bug any longer?
