### ISSUE TITLE
failed to restrict file handles

### ISSUE THREAD

**Issue by anonymouslycn** [git-for-windows/git#1539]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.16299.248]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing~~

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git https://github.com/aymericdamien/TensorFlow-Examples.git
```
 - What did you expect to occur after running these commands?

PS D:\github> git https://github.com/aymericdamien/TensorFlow-Examples.git
warning: failed to restrict file handles (2)

handle #0: 0000000000000050 (type 2, handle info (1) 0
handle #1: 0000000000000148 (type 2, handle info (1) 1
handle #2: 000000000000014c (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'https://github.com/aymericdamien/TensorFlow-Examples.git' is not a git command. See 'git --help'.


 - What actually happened instead?

It showed the texts above and have done nothing?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/aymericdamien/TensorFlow-Examples.git


<!-- probot = {"87175":{"who":"dscho","what":"look at this (after GitMerge)","when":"2018-03-13T09:00:00.000Z"}} -->

**Comment by anonymouslycn** [comment]
I forgot to add "clone " into the command and it crashed.

**Comment by dscho** [comment]
Thank you for the report.

That was not a crash. It errored out with the error message that `https:...` is not a Git command.

There is a bug, too, though: the message about the file handles should only be shown if a first attempt to spawn the subcommand failed, but the second (with relaxed handle inheritance restrictions) succeeded. But the second call failed, too, with the same error condition. So Git should be quiet about the handles.

**Comment by dscho** [comment]
/remind me next week to look at this (after GitMerge)

**Comment by bobbingwide** [comment]
I got the same problem when I forgot the command. Perhaps the suggestion to report the bug should be improved to check if it's not already been reported. 
git and Windows version very much the same as previous reporter.
Install options similar.
```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

**Comment by dscho** [comment]
@bobbingwide @anonymouslycn could you test the latest [snapshot installer](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by anonymouslycn** [comment]
Thanks to your work! It‘s fixed!

**Comment by dscho** [comment]
@anonymouslycn thank you for testing!
