### ISSUE TITLE
Error when creating symlinks to non-existent files, or to other files in repo

### ISSUE THREAD

**Issue by mehrdadn** [git-for-windows/git#1542]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2
cpu: x86_64
built from commit: 064f96e2b32f69f1904a456e0ff50d504a7089bd
sizeof-long: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.214]
```

 - What options did you set as part of the installation? Or did you choose the defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```

N/A (and I'm using MSYS2)

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I know of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Command prompt

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
D:\>mkdir Test

D:\>cd Test

D:\Test>git init
Initialized empty Git repository in /d/Test/.git/

D:\Test>git config --local core.symlinks true

D:\Test>echo X 1>B

D:\Test>mklink A B
symbolic link created for A <<===>> B

D:\Test>git add A B   && git commit -m "symlinks"
[master (root-commit) e8c4063] symlinks
 2 files changed, 2 insertions(+)
 create mode 120000 A
 create mode 100644 B

D:\Test>del A B

D:\Test>git reset --hard
error: unable to create symlink A: No such file or directory
fatal: Could not reset index file to revision 'HEAD'.

D:\Test>git reset --hard
HEAD is now at e8c4063 symlinks
```
 - What did you expect to occur after running these commands?

No `unable to create symlink` error.

 - What actually happened instead?

I get `error: unable to create symlink` because the first time the link target doesn't exist. If the link is to a file in the repo, then running it multiple times can fix the problem, but the problem will still occur for links to external files that don't exist.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
> git version 2.16.2

That is not Git for Windows ;-)

So what happens is that this Git version does not get anything out of our `compat/mingw.c`, including our symlink work. Instead, it relies on the MSYS2 runtime to handle symlinks. I could imagine that MSYS2 was not taught yet (or put more correctly: that Cygwin, from which MSYS2 inherits pretty much all functionality, has not been taught yet).

**Comment by mehrdadn** [comment]
Oops, shoot, sorry!! I've been switching back and forth between the two so much that I didn't realize!

**Comment by dscho** [comment]
No worries. Now you know what the culprit is! ;-)
