### ISSUE TITLE
Some `git subtree` subcommands only working when run with full path

### ISSUE THREAD

**Issue by ncoghlan** [git-for-windows/git#1543]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

At the msys git-bash prompt, running `git subtree --help` fails (see specific output below), but the fully qualified path to the `git-subtree` script works.

The machine was initially installed with supporting for running `git` in `cmd` windows, but uninstalling and reinstalling without that option didn't change the behaviour. 

Update: Some git subtree commands, like `git subtree add` are working fine, so the problem may be specific to less frequently exercised commands like `git subtree --help` and `git subtree split`.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.251]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$  cat /etc/install-options.txt
Editor Option: VisualStudioCode
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The original install on this machine was set up to install access from the Windows Command Prompt. The above output is after uninstalling and reinstalling without that setting in an attempt to check if the problem was in the `git subtree` executable wrapper.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (with the underlying msys terminal)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git subtree --help
```
 - What did you expect to occur after running these commands?

I expected to get the same output as I get for:

```
$ 'C:\Users\NickCoghlan\AppData\Local\Programs\Git\mingw64\libexec\git-core\git-subtree' --help
usage: git subtree add   --prefix=<prefix> <commit>
   or: git subtree add   --prefix=<prefix> <repository> <ref>
   or: git subtree merge --prefix=<prefix> <commit>
   or: git subtree pull  --prefix=<prefix> <repository> <ref>
   or: git subtree push  --prefix=<prefix> <repository> <ref>
   or: git subtree split --prefix=<prefix> <commit...>

... etc
```

 - What actually happened instead?

```
$ git subtree --help
/usr/bin/start: line 8: cmd: command not found
```

**Comment by dscho** [comment]
For any `--help` option to work, `cmd` needs to be in your `PATH`. This is generally the case on Windows. Is it not for you? Or is your `PATH` insanely long (in which case it might be cut off by Git's `bash .exe`somehow)?

**Comment by dscho** [comment]
Okay, thanks!

**Comment by ncoghlan** [comment]
I didn't, sorry - I've sent myself a reminder email to my work account, so I'll hopefully remember to check next week :)

**Comment by ncoghlan** [comment]
Checking the behaviour, there's definitely something odd going on with `cmd` vs `cmd.exe`, as from a regular Windows command prompt, both of these work as expected (printing the Windows version):

    cmd /C ver
    cmd.exe /C ver

However, at the git-bash prompt, only the second command works properly - `cmd` appears to be ignoring the `/C` option entirely. `/K` also has no apparent effect, but `/?` works as expected.

**Comment by landstander668** [comment]
I'm pretty sure this is caused by POSIX-to-Windows path conversion, which is mentioned in the release notes. For example, both of the following variants work as expected.

    cmd //C ver
    MSYS_NO_PATHCONV=1 cmd /C ver

What I'm unsure about is why invoking it as `cmd.exe /C ver` doesn't exhibit the same behaviour. I would speculate, however, that MSYS2 infers from the *.exe* suffix that this is a native Windows application and responds by implicitly disabling the conversion.

**Comment by ncoghlan** [comment]
That sounds like a plausible theory, since the `C:\\` (et al) in the full path to the executable might similarly result in the `MSYS_NO_PATHCONV=1` behaviour being selected.

I'll see what happens if I run `MSYS_NO_PATHCONV=1 git-subtree --help` on the affected system and report back (hopefully without a 3 week delay this time!).

**Comment by dscho** [comment]
> I'll see what happens if I run `MSYS_NO_PATHCONV=1 git-subtree --help` on the affected system and report back (hopefully without a 3 week delay this time!).

@ncoghlan Whenever you will reply, you will definitely have made good on the promise to not have a 3 week delay this time (but instead a multiple thereof).
