### ISSUE TITLE
warning: failed to restrict file handles (87)

### ISSUE THREAD

**Issue by mikiek** [git-for-windows/git#1544]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64b

```
$ git --version --build-options

** insert your machine's response here **
git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
Editor Option: Notepad++
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Bash inside ConEmu


 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
git pull

 - What did you expect to occur after running these commands?
pretty obvious

 - What actually happened instead?
pull was done but additionally following appeared on screen
warning: failed to restrict file handles (87)

handle #0: 000000000000000c (type 2, handle info (1) 1d3a70e
handle #1: 00000000000000a8 (type 3, handle info (1) 1
handle #2: 0000000000000013 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Could you test whether the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html) fixes this? We already invested in several fixes since v2.16.1(4).

**Comment by gw3nzie** [comment]
experienced this same issue today with Git-2.16.2-64-bit.exe, which I downloaded just before I tried publishing my Android studio project to GitHub.

**Comment by dscho** [comment]
> Could you test whether the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html) fixes this?

Would somebody *please* work with me?

**Comment by shepardo** [comment]
Found same issue:


git.exe pull --progress -v --no-rebase "origin"

warning: failed to restrict file handles (5)

handle #0: 00000000000000e8 (type 3, handle info (1) 0
handle #1: 00000000000000ec (type 3, handle info (1) 1
handle #2: 00000000000004dc (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

SUPPRESS_HANDLE_INHERITANCE_WARNING=1


$ git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

**Comment by PhilipOakley** [comment]
@shepardo - Have you tried the [ latest snapshot ](https://wingit.blob.core.windows.net/files/index.html) ?

**Comment by dscho** [comment]
*throws-hands-in-the-air*

**Comment by shepardo** [comment]
@PhilipOakley not yet, I'll check, although right the problem doesn't happen (most of the time), so I'll to work to try figure out how to repro consistently. Thanks,

**Comment by gw3nzie** [comment]
My apologies for not responding sooner. I came down hard with the flu and have been flat on my back. Let me know if you want my assistance.

**Comment by dscho** [comment]
@gw3nzie could you please test the latest snapshot at https://wingit.blob.core.windows.net/files/index.html? You can install the portable Git to avoid interfering with your currently installed Git for Windows.

**Comment by bluelovers** [comment]
```
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

```
node-novel2: warning: failed to restrict file handles (87)
												
												handle #0: 0000000000000178 (type 3, handle info (1) 0
												handle #1: 00000000000001fc (type 3, handle info (1) 1
												handle #2: 00000000000021e8 (type 3, handle info (1) 1
												
												This is a bug; please report it at
												https://github.com/git-for-windows/git/issues/new
												
												To suppress this warning, please set the environment variable
												
												SUPPRESS_HANDLE_INHERITANCE_WARNING=1
```

**Comment by PhilipOakley** [comment]
@bluelovers Do you have a command sequence that would prompt that error? Was there a longer message? We thought it had been fixed.

**Comment by bluelovers** [comment]
im not sure, because i use idea for push git
https://youtrack.jetbrains.com/issue/IDEA-210139

**Comment by PhilipOakley** [comment]
>  i use idea for push git https://youtrack.jetbrains.com/issue/IDEA-210139

You should refer the issue to them, as they will have embedded that older buggy version.
Thanks.

**Comment by dmitriysmirnovjb** [comment]
> as they will have embedded that older buggy version.
IntelliJ does not embed any git version, it uses the command-line client in the system. One can specify exact executable in Settings | Version Control | Git.

Make sure executable is specified in settings correctly, and IDE uses the correct version with fixes.

**Comment by bluelovers** [comment]
only happen when push by idea, if push by cmd line it is correctly

**Comment by PhilipOakley** [comment]
> only happen when push by 'idea', if push by cmd line' it is correctly [quoting added]

It looks like the 'idea' tool does have an older Git version embedded in it's code. Glad to see you have a work around and that you are learning the cli (command line interface) :wink: 

Have you reported the problem to the 'idea' tool suuport?

**Comment by rimrul** [comment]
> Have you reported the problem to the 'idea' tool suport?

They did and posted a link to the Jetbrains issue tracker. That link is dead now, but it showed a screenshot where they had specified an executable path that didn't look like it was Git for Windows, or bundled by the IDEA/IntelliJ (let's consider those two names identical for our purposes). It looked like it was installed via MSYS(2?).

Mister Smirnov from Jetbrains(the vendor) support also confirmed above, that

>IntelliJ does not embed any git version, it uses the command-line client in the system. One can specify exact executable in Settings | Version Control | Git.

>Make sure executable is specified in settings correctly, and IDE uses the correct version with fixes.

After a quick look at the [source of the plugin](https://github.com/JetBrains/intellij-community/tree/master/plugins/git4idea) that seems to be true. It seems like blue lovers just had multiple versions of git on their computer and pointed their IDE at the wrong one.

**Comment by bluelovers** [comment]
nope , at end problem is idea can't popup auth by it idea auth script

when disable, everything work well
https://youtrack.jetbrains.com/issue/IDEA-210577

im just install git for windows in other path i like, and it not problem
