### ISSUE TITLE
Modifications to VS projects after opening in VS2017

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#1545]
I'm opening a new issue for this to investigate any additional changes that need to be made, but I'm not sure what the goals are. I have put my VS2017 version information in the commit message of my branch. Please see [this link](https://github.com/rcdailey/git/compare/vs/master...rcdailey:vs-modifications) to view a diff of changes to the visual studio projects that were made when I opened the projects on the `vs/master` branch. Let me know if there's anything meaningful/helpful here.

Note that I was able to successfully build & debug git in vs2017, so there are no actual issues.

**Comment by shiftkey** [comment]
@rcdailey that diff looks like you're just using a later version of VS2017 and MSBuild than whoever was previously making changes to the `vs/master` branch. What version of VS2017 do you have installed?

**Comment by dscho** [comment]
> that diff looks like you're just using a later version of VS2017 and MSBuild than whoever was previously making changes to the vs/master branch.

Yep. Those changes are expected.
