### ISSUE TITLE
sh segfaulting on rebase

### ISSUE THREAD

**Issue by Jenia-Finkler** [git-for-windows/git#1552]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10, 64-bit
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults.
```
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rebase origin/master
```
 - What did you expect to occur after running these commands?

A rebase. :)

 - What actually happened instead?

git hung, and a stackdump file was left in the directory:
```$ cat sh.exe.stackdump
Exception: STATUS_STACK_OVERFLOW at rip=7FF99FF64B57
rax=0000000000001058 rbx=00000000000C3360 rcx=935FC2E0FECE0000
rdx=00000000000253F0 rsi=00000000000C234C rdi=0000000000000001
r8 =00000000000000E7 r9 =000000000000001B r10=00000000FFFF9000
r11=00000000FFE03670 r12=0000000000000424 r13=00000000000C2330
r14=0000000000000000 r15=0000000000000000
rbp=00000000000C3360 rsp=00000000FFFFABE0
program=C:\Program Files\Git\usr\bin\sh.exe, pid 20004, thread
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000000C3360  7FF99FF64B57 (00180010018, 000000A22D0, 000000C234C, 00180010018)
000000C3360  7FF99BF4637A (000000A22D0, 000000C234C, 00180010018, 000FFFFAFE0)
000000C3360  7FF99BF4813E (000000C33AA, 00000000420, 00000000420, 000000C259C)
00000000420  7FF99BF48836 (000FFFFAF00, 0000000024C, 00000000000, 001802772E0)
00000000420  7FF99D00D7A6 (00000000001, 00000000000, 000FFFFAFE0, 00100000001)
00000000420  7FF99DC6E4E3 (00000000020, 000FFFFB368, 000FFFFB160, 00000000001)
00000000420  001800AA912 (000FFFFB100, 0018030A640, 001802772E0, 00000000001)
000FFFFB370  001800AB449 (00100410FBB, 00000000000, 00600043CA0, 001004E9740)
000FFFFB370  0018011C6FB (00100410FBB, 00000000000, 00600043CA0, 001004E9740)
000FFFFB370  0000472E458 (00100410FBB, 00000000000, 00600043CA0, 001004E9740)
End of stack trace
```
when downgrade the git version to Git-2.15.1.2 it works

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Unfortunately, it's not public. :( But, I also tried a rebase in another repository and the same thing happened.

**Comment by dscho** [comment]
Thank you for reporting this bug.

Sadly, this is not enough information for me to reproduce. "A rebase" is working here, without problems.

> Unfortunately, it's not public.

The logical next step would be to test whether it also happens in a publicly available repository.

**Comment by dscho** [comment]
Probably the same issue was reported in https://github.com/git-for-windows/git/issues/1562, accompanied by a pretty good analysis and the suggestion that Comodo Internet Services might be the culprit. Maybe this is the case here, too?

In any case, I am closing this, as I outlined the next steps and nothing has happened in three weeks.
