### ISSUE TITLE
Ctrl-C in Windows cmd shell from where git gui was launched kills git gui

### ISSUE THREAD

**Issue by LouisStrous** [git-for-windows/git#1553]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

64-bit Windows 7 Professional.

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I can think of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
(start CMD shell, change to directory containing a git repository)
git gui
(click mouse inside CMD shell to give it focus again)
dir
(press Ctrl-C at any time after the dir command has finished)
```
 - What did you expect to occur after running these commands?

1. git gui window is displayed
2. a directory listing is displayed in the CMD shell (showing that the CMD shell really does have the focus at this point)
3. pressing Ctrl-C displays a new command prompt in the CMD shell, as if I had entered a newline.  The git gui windows is not affected.

 - What actually happened instead?

All as expected, except that the git gui window disappeared after pressing Ctrl-C.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None.

- Additional details

I tried the same reproduction scenario also on a 64-bit Windows 10 Home system.  With git version 2.9.3.windows.1, the issue did not occur.  With git version 2.16.2.windows.1 (same as above), the issue did occur.

The workaround is to start the git gui through

```
start /b git gui
```

**Comment by dscho** [comment]
When I start `git gui` in a Git Bash, then the command does not return until the GUI is closed. When I hit Ctrl+C in the Bash window, it interrupts the GUI.

The thing is: `git.exe` *is* a console program. And the fact that `git gui` spawns a GUI does not change that.

I think this is intended behavior...

If you want to start Git GUI as a *GUI application*, you will have to call `git-gui.exe` (from `C:\Program Files\Git\cmd`, which should be in your `PATH` by default).

**Comment by LouisStrous** [comment]
I apologize for not making myself clear enough.  When I start `git gui` from the cmd shell (not a git bash), then the GUI appears and can be used.  At the same time, the cmd shell displays a new prompt and can be used.  For example, I can start another git GUI from the same cmd shell, so that two git GUIs are visible and can be used.  So the git GUI and the cmd shell act independently, neither of them waiting for the other one to close.

My reproduction scenario mentions running a `dir` command in the cmd shell before pressing the Ctrl-C that makes the GUI disappear.  I would not be able to run the `dir` command if the cmd shell was waiting for the git GUI to close.  It is precisely the fact that the cmd shell and the GUI can be used simultaneously that makes it surprising and (to me) unexpected that the git GUI disappears when I press Ctrl-C in the cmd window from where the git GUI was started earlier.

Typically, I start a git GUI, and then use the same cmd shell for many other tasks while the GUI remains visible.  I usually have several other cmd shells open as well.  After some hours, I might run a command in the cmd shell that turns out to take longer than I am willing to wait, and then I press Ctrl-C to interrupt that command.  And that doesn't just interrupt that command but also terminates the git GUI, if the cmd shell into which I press Ctrl-C happens to be the one from which I started git GUI hours ago.  I typically have several cmd shells open at the same time, so it is a matter of chance whether the cmd shell into which I press Ctrl-C is the one from which I started the git GUI long ago.  That's why it took me a while to figure out that this is what was happening.

**Comment by dscho** [comment]
> When I start git gui from the cmd shell (not a git bash), then the GUI appears and can be used. At the same time, the cmd shell displays a new prompt and can be used.

I have no idea why that is the case, as `git gui` should wait until the GUI is closed. That is the intended behavior, and if you have any idea what is going wrong and how to fix it, that would be great.

For the record, the `git.exe` program that you call to execute `git gui` is a *Console* program, and it does not return until the GUI closes.

**Comment by dscho** [comment]
Okay, I think I figured this one out, as part of my work on https://github.com/git-for-windows/git/issues/1491. The fix should hit https://wingit.blob.core.windows.net/files/index.html Real Soon Now, so please test it then.

**Comment by dscho** [comment]
The newest snapshot at https://wingit.blob.core.windows.net/files/index.html should fix this. Please test.

**Comment by LouisStrous** [comment]
I forgot to mention that I get git commands to work from the Windows cmd shell by adding the location of the git commands (C:\Program Files\Git\bin, C:\Program Files\Git\usr\bin) to my PATH environment variable.

I reran the reproduction scenario with Git-prerelease-2.17.0.windows.1.38.g05ca542f78-64-bit.exe, and now pressing Ctrl-C in the cmd shell does not affect the git GUI window anymore.  Thank you!
