### ISSUE TITLE
failed to restrict file handles

### ISSUE THREAD

**Issue by brandonmcclure** [git-for-windows/git#1555]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
7 64 bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
Plink Path: C:\Program Files\Putty\plink.exe
SSH Option: Plink
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I have TortoiseGit installed, and my local repositories are in a directory that is exempt from our anti virus scans. 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
(checking out a local branch from another local branch)
git checkout master
```
 - What did you expect to occur after running these commands?

new branch is checked out without a warning

 - What actually happened instead?

I get a warning asking me to report the bug, and the checkout appears to be successful. cmd output:

Switched to branch 'master'
M       Misc Developer Files/Brandon McClure/SQL Scripts/Validate CaboodleX BTF with custom BTF.sql
Your branch is up to date with 'origin/master'.
warning: failed to restrict file handles (87)

handle #0: 000000000000000c (type 2, handle info (1) 1d35c96
handle #1: 0000000000000254 (type 3, handle info (1) 1
handle #2: 0000000000000013 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It is occurring with a specific repository, but it is a corporate repository that I cannot provide. If I clone a new copy of the repo from my remote, the new repository does not seem to elicit this behavior. If I copy my local repository into a new directory I still get this warning when switching.

**Comment by dscho** [comment]
Could you test whether the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) fixes your problem? (Note: v2.16.2 might also have the appropriate fix for you.)

**Comment by dscho** [comment]
I'll just claim that 0cad27b1f1a766f7e5bf53b17d94d3b2648a3710 fixes this.

**Comment by dscho** [comment]
And I'll call this a duplicate of #1539.
