### ISSUE TITLE
git database/ seems throw unexpected errors

### ISSUE THREAD

**Issue by CedricLeong** [git-for-windows/git#1560]
I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)Issue

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Using Git Bash on Windows 10 64-bit

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git database/
```
 - What did you expect to occur after running these commands?

git database/ is not a valid command

 - What actually happened instead?

warning: failed to restrict file handles (2)

handle #0: 0000000000000410 (type 3, handle info (1) 7fff
handle #1: 0000000000000414 (type 3, handle info (1) 1

**Comment by dscho** [comment]
Can you verify that this is fixed in the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)? I am fairly certain that I fixed this in reponse to https://github.com/git-for-windows/git/issues/1539.
