### ISSUE TITLE
Make gitforwindows.org responsive

### ISSUE THREAD

**Issue by sxlijin** [git-for-windows/git#1566]
Creating an issue to track responsive-ifying the G4W website, per @dscho's expressed desire in git/git-scm.com#1143.

This actually seems like a surprisingly less complicated effort than one might initially expect: the repo only shows 3 top-level pages, one of which isn't actually linked from anywhere, and if you run this in the console:

```
Array.from(document.getElementsByTagName('a')).forEach(a => console.log(a.href));
```

the only two pages to care about are `index.html` and `governance-model.html`.

**Comment by sxlijin** [comment]
I also see some JS assets in the repo - @dscho, besides image viewing (JQuery fancybox), do they serve any purpose?

**Comment by dscho** [comment]
@sxlijin AFAIR those assets were added to help responsiveness, maybe `git log` can clarify?

**Comment by dscho** [comment]
Closing this ticket due to underwhelming interest in it.
