### ISSUE TITLE
[SDK] Identical version strings trolls pacman

### ISSUE THREAD

**Issue by niklasholm** [git-for-windows/git#1571]
The core packages msys2-runtime and bash (I'm sure there are others) doesn't change the package version/release number compared to upstream, which means pacman won't recognize these as different package versions. This breaks the procedure described [here](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper) and probably will cause other issues when upgrading packages. Perhaps it's a good idea to add some pre-/postfix to all changed packages to distinguish these from the upstream versions.

EDIT: [epoch=](https://wiki.archlinux.org/index.php/PKGBUILD#epoch) is probably the most suitable for this purpose.

**Comment by dscho** [comment]
*Please* understand that I already have enough on my plate maintaining regular Git for Windows together with Git for Windows' SDK.

If people choose to go a different route (such as modifying their MSYS2 installation to use Git for Windows' Pacman repositories), I will not stop them. But I do ask to be adults about it, and not put more tasks and problems on my plate...

So opening that Pull Request was the right thing to do. Thanks.
