### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by akashilan** [git-for-windows/git#1575]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit
$ git --version --build-options

```$  git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4


 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt "

```$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled


 - Any other interesting things about your environment that might be related
   to the issue you're seeing?


### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

```
 - What did you expect to occur after running these commands?



 - What actually happened instead?



 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by dscho** [comment]
So what was the issue?

**Comment by akashilan** [comment]
hi...
thank you for coming forward to help me ....
but once again  I want to try on my own ...if I fail I will contact you
:)

**Comment by dscho** [comment]
Let's close this ticket for now. If anything comes up again, it is easy enough to reopen it.
