### ISSUE TITLE
git gc --aggressive slows to a crawl as it reaches 70%

### ISSUE THREAD

**Issue by colonelchlorine** [git-for-windows/git#1576]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Difftool: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Using Powershell along with posh-git for the terminal.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git gc --aggressive
```
 - What did you expect to occur after running these commands?

I know gc takes a long time if not done on a regular basis, but it took over an hour in a large repository (4GB).

 - What actually happened instead?

At the beginning of gc, it was very fast to get up the % of compressing objects, until it got to ~70%, at which time it slowed to a crawl. It stayed at 99% for about 15 minutes. The terminal does say it's using four _threads_, but I took a screenshot of Task Manager and it seems to me there are four _processes_ instead (no other Powershell windows were open at the time). Only one process was active and it was running at full CPU.

![image](https://user-images.githubusercontent.com/1085938/37774112-b8dda5b0-2db5-11e8-87a2-590ea26b84e9.png)

I don't know if this is intentional in the design, but I am just curious about what's going on here. Why is it not using the other three "threads".

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Can't provide URL.

**Comment by dscho** [comment]
> The terminal does say it's using four threads, but I took a screenshot of Task Manager and it seems to me there are four processes instead

No, the processes are: the `git.exe` wrapper (setting some environment variables before handing off to...),  the *real* `git.exe`, the `repack` process and the `pack-objects` process (the latter does all the work).

When things slow to a crawl with `gc`, it is typically a memory problem. You might want to reduce the amount of memory Git wants to use by setting `core.packedGitWindowSize` and/or `core.packedGitLimit` (see [the documentation of `git config`](https://git-scm.com/docs/git-config) for details).

**Comment by stahta01** [comment]
I had a similar issue and "git config --global pack.packsizelimit 250m" fixed it.
Win 7 64 bit 4 GB the problem still existed for me at 2G limit did not try values between 250m and 2g.

Tim S.

**Comment by dscho** [comment]
@stahta01 yes, that's what I meant. Thanks for spelling it out.

I had totally forgotten about this ticket, BTW, I assumed that I would get some sort of answer by the original reporter.
