### ISSUE TITLE
warning: failed to restrict file handles (2)

### ISSUE THREAD

**Issue by kaltinril** [git-for-windows/git#1578]
NOTE: This apparently was caused by me just forgetting to type "Add"

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windows 10 enterprise

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I don't think so, first ever issue.  I just added and commited a folder rename and 2 other files.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MingW64

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
It appears I simply missed the "Add" keyword.  Why it cauesed this issue I don't know

---@--- MINGW64 /c/git/RotationFrenzy (level_load_from_json)
$ git source/core/src/com/uaa/rotationfrenzy/screen/MainMenuScreen.java
warning: failed to restrict file handles (2)

handle #0: 0000000000000410 (type 3, handle info (1) 7ff8
handle #1: 0000000000000414 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'source/core/src/com/uaa/rotationfrenzy/screen/MainMenuScreen.java' is not a git command. See 'git --help'.


```
 - What did you expect to occur after running these commands?

Add the file, but obviously not now that I realize I missed the "Add" command.

 - What actually happened instead?

The error message appears and told me to report this.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I don't think it is repository specific.  It's me not making a good command

**Comment by dscho** [comment]
Could you try the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), or even better, [v2.17.0-rc0](https://github.com/git-for-windows/git/releases/tag/v2.17.0-rc0.windows.1)?

I am fairly certain that there are bug fixes in that area.

**Comment by johne53** [comment]
FWIW I also encountered this error (in my case, after updating from v2.16.2 to 2.17.0.rc0, earlier today). In my case the message says:-

warning: failed to restrict file handles (1450)

It happens whenever I issue any git command (and in some cases it'll get printed several times while processing just one command). A few minutes ago I reverted back to 2.16.2 and the problem's now gone away.

**Comment by kaltinril** [comment]
@dscho , the response from @johne53  doesn't make me want to try v2.17.0-rc0.  Again, mine was simply an invalid command (git path/to/file/filename.ext) without the "add" keyword.

I would hate to upgrade and then get the error happening for ANY command like @johne53  is reporting.

**Comment by kaltinril** [comment]
Testing in my same version with a malformed command:

```
$ git foo/
warning: failed to restrict file handles (2)

handle #0: 0000000000000418 (type 3, handle info (1) 7ff8
handle #1: 000000000000041c (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'foo/' is not a git command. See 'git --help'.

The most similar command is
        flow
```

**Comment by kaltinril** [comment]
Using the new version:

```
$ git --version --build-options
git version 2.17.0.rc0.windows.1
cpu: x86_64
built from commit: aec1b12d978b7b7d212da6af82b283c128f5daa7
sizeof-long: 4

$ git foo/
git: 'foo/' is not a git command. See 'git --help'.

The most similar command is
        flow


```

**Comment by johne53** [comment]
Ki **kaltinril** - as it happens, I didn't try any of the commands that begin with "--".

**Comment by johne53** [comment]
Hi **kaltinril** - unfortunately I've reverted back to v2.16.2 now but as it happens, I didn't try any command beginning with "--". Maybe that's a clue to what's wrong here..? Try these ones:-

> git branch
> git remote update

I definitely tried both of the above and they both gave me the warning message with v2.17.0.rc0.

**Comment by dscho** [comment]
Thank you all for testing!

> I also encountered this error (in my case, after updating from v2.16.2 to 2.17.0.rc0, earlier today). In my case the message says:-
> 
> >   warning: failed to restrict file handles (1450)

This is really strange. That error number corresponds to `ERROR_NO_SYSTEM_RESOURCES` and we *specifically* exclude this case from the warning: https://github.com/git-for-windows/git/blob/v2.17.0-rc0.windows.1/compat/mingw.c#L1757

... however... now that I read on, I realize that only the verbose part of the error message is excluded!

Let me fix this.

**Comment by dscho** [comment]
@kaltinril @johne53 could you try the latest snapshot at https://wingit.blob.core.windows.net/files/index.html? The portable Git will "install" into a directory, therefore not interfering with your current installation.

**Comment by kaltinril** [comment]
I ran the same commands (foo/, branch, remote, remote update) no issues in version:

```
 MINGW64 /c/git/RotationFrenzy (master)
$ git --version --build-options
git version 2.16.3.windows.1.1.gf2a677fb4d
cpu: x86_64
built from commit: f2a677fb4d2fc61cabe6a64c5d23d522647579fc
sizeof-long: 4

```

**Comment by johne53** [comment]
> @kaltinril @johne53 could you try the latest snapshot at https://wingit.blob.core.windows.net/files/index.html?

 

I installed it this morning and **warning: failed to restrict file handles (1450)** seems to be fixed now.

Is there any possibility of fixing the issue I reported here:-

https://github.com/git-for-windows/git/issues/1572#issuecomment-375669215

where **git branch** is issuing an (apparently unnecessary) warning message?

**Comment by dscho** [comment]
Thanks for testing!

As for the other ticket: let's discuss the issues there, not here.
