### ISSUE TITLE
[Win10 x64] Git bash does not return to the command line after running "start" command

### ISSUE THREAD

**Issue by viniciusfacco** [git-for-windows/git#1580]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
start .
```
 - What did you expect to occur after running these commands?

Open Windows Explorer in the current directory and return to the command line.

 - What actually happened instead?

Windows Explorer did open as expected, however, git bash did not return from the command. So I needed to press CTRL+Z to get back to the command line.

![image](https://user-images.githubusercontent.com/1927312/37834316-352d85fa-2e8c-11e8-8654-dda40abfa4b2.png)

**Comment by dscho** [comment]
Hmm. It works here. Maybe you have an interfering `start` command/alias?

```
$ which start
/usr/bin/start

$ type start
start is hashed (/usr/bin/start)
```

You could also try to trace the shell script:

```sh
bash -x /usr/bin/start .
```

**Comment by viniciusfacco** [comment]
Hi, I did that:
![image](https://user-images.githubusercontent.com/1927312/37905151-50f915e8-30d4-11e8-928f-ad4aa5407d57.png)

Still, the command line was wainting. So I pressed CTRL + Z:
![image](https://user-images.githubusercontent.com/1927312/37905224-8e10f82e-30d4-11e8-883c-4bae160342dc.png)

Maybe this is a problem if my Operation System.

**Comment by dscho** [comment]
No idea why your `cmd //c start .` does not return... There are probably knobs and switches to modify that behavior (see e.g. https://github.com/git-for-windows/git/issues/1585#issuecomment-377004605). Please let us know if you ever figure this out.

**Comment by viniciusfacco** [comment]
After upgrading my Windows to the version below, the problem is finally solved:
Microsoft Windows [version 10.0.18362.175]
