### ISSUE TITLE
Warning: failed to restrict file handles (2) MACH II

### ISSUE THREAD

**Issue by dhmorrison** [git-for-windows/git#1583]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

**Windows 7, 64 bit**

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

**Chose defaults.**

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

``Nope.```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```Cygwin, CMD, and/or Powershell```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

**To replicate you can type anything similar to this:**
>git branch.something-anything/everything

The "/" character is important, as without it, the error does not occur. E.G.
>git branch.what-evs

does not trigger the error condition.  Instead you get an expected response:
>git: 'branch.what-evs' is not a git command. See 'git --help'.

```
I ran the below to create the error condition:
git branch.experiment/silly-themes-ex

```
 - What did you expect to occur after running these commands?

Who even knows what I was expecting.  I let my fingers do the walking.  My intention was to create a new branch.  At the time I was a bit distracted, and typed the above instead of something like "git checkout -b 'experiment/silly-themes-ex'." 

 - What actually happened instead?

## Here's what happened instead:
```
warning: failed to restrict file handles (2)

handle #0: 0000000000000003 (type 2, handle info (1) 7fe
handle #1: 000000000000000f (type 2, handle info (1) 1
handle #2: 0000000000000007 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**The repo is internal, so no.**

**Comment by dhmorrison** [comment]
## It appears that the "/" is the real issue.  Try it with any command:

Some examples:
-

## git tag.blah/blah

```
git tag.blah/blah
warning: failed to restrict file handles (2)

handle #0: 0000000000000003 (type 2, handle info (1) 7fe
handle #1: 000000000000000f (type 2, handle info (1) 1
handle #2: 0000000000000007 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'tag.blah/blah' is not a git command. See 'git --help'.
```

## git commit.blah/blah
```
git commit.blah/blah
warning: failed to restrict file handles (2)

handle #0: 0000000000000003 (type 2, handle info (1) 7fe
handle #1: 000000000000000f (type 2, handle info (1) 1
handle #2: 0000000000000007 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'commit.blah/blah' is not a git command. See 'git --help'.
```

**Comment by dscho** [comment]
I do not get this problem with v2.16.3.

Could you try the latest snapshot at https://wingit.blob.core.windows.net/files/index.html (just to make sure you have the very latest fix)?

**Comment by dhmorrison** [comment]
Sure thing, I'll do that and report back.

**Comment by dscho** [comment]
Thanks.

**Comment by harig** [comment]
The warning `warning: failed to restrict file handles (1450)` started to show up on almost all git operations (git status, clone, etc.) after I upgraded to `git version 2.16.3.windows.1` (On reverting to 2.16.2 it is not shown).  Is there some logging that I could do to provide more information?

**Comment by dscho** [comment]
> Is there some logging that I could do to provide more information?

The best you can do is to test the latest snapshot: https://wingit.blob.core.windows.net/files/index.html

**Comment by harig** [comment]
Tried with the latest snapshot available:
git version 2.16.3.windows.1.1.gf2a677fb4d
built from commit: f2a677fb4d2fc61cabe6a64c5d23d522647579fc

The file handle warning is still visible.

**Comment by dscho** [comment]
@harig I tried with the same version:

```
$ git version --build-options
git version 2.16.3.windows.1.1.gf2a677fb4d
cpu: x86_64
built from commit: f2a677fb4d2fc61cabe6a64c5d23d522647579fc
sizeof-long: 4
```

and for me, the warning is gone:

```
$ git commit.blah/blah
git: 'commit.blah/blah' is not a git command. See 'git --help'.
```

Strange.

**Comment by harig** [comment]
I don't see the warning with 2.17.0.windows.1.

**Comment by dscho** [comment]
Thanks, @harig, for not only testing, but also reporting back your finding!
