### ISSUE TITLE
GfW 2.16.2 installer has problems with the post-install scripts

### ISSUE THREAD

**Issue by larsxschneider** [git-for-windows/git#1585]
When installing [GfW 2.16.2 64-bit](https://github.com/git-for-windows/git/releases/download/v2.16.2.windows.1/Git-2.16.2-64-bit.exe) for a particular user, then we always get the error ["Line 2125: Unable to run post-install scripts, no output?"](https://github.com/git-for-windows/build-extra/blob/4713a155cb08c3a62e14d29bf86f2e814f7abeee/installer/install.iss#L2125).

If we run the post-install command manually on machines of this user, then we don't get any output either:
```
"C:\Program Files\Git\git-bash.exe" --no-needs-console --hide --no-cd --command=post-install.cmd
```

If I run the post-install command on yet another Windows machine without this problem (my box), then I don't get any output for the post-install command too. Is this because the post-install scripts did run successful on my machine already or does it usually output nothing?

I guess even if there is no output, the file [`'{tmp}\post-install.log'`](https://github.com/git-for-windows/build-extra/blob/4713a155cb08c3a62e14d29bf86f2e814f7abeee/installer/install.iss#L2122) should have been written. Where does `{tmp}` come from? Is this the environment variable `TMP`? `TMP` is set to `C:\Users\<user>\AppData\Local\Temp` and the user can create files in that directory.

I have only a single user that is affected by this problem. I suspect there is something weird about his account. If you have a hint for me what else I could check, that would be awesome.

---

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

(on both test systems of the user - I assume the first part of the install went fine)
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
The issue is reproducible on two systems, Win 7 and Win 10:
Microsoft Windows [Version 6.1.7601]
Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

**Comment by dscho** [comment]
> I guess even if there is no output, the file '{tmp}\post-install.log' should have been written.

Yes.

> Where does {tmp} come from?

It is the temporary directory of InnoSetup, which is typically a subdirectory of `%TMP%`.

Could you run `post-install.bat` in a CMD window (as administrator)?

**Comment by larsxschneider** [comment]
OK, I think we figured it out:

1. The user configured a `bat` file that is executed on `cmd.exe` startup (similar to a `.bashrc` ... I didn't even know that this is possible 😄) 
```
[HKEY_CURRENT_USER\Software\Microsoft\Command Processor]
"AutoRun"="C:\\bin\\startup.bat"
```

2. In this `bat` file he used the pipe operator `|` in one command which was the culprit (he actually used the pipe operator in a `doskey` command and fixed the problem by escaping the pipe `^|`).

@dscho : I don't know if we can do something about it or if we even want to do something about it. I feel that's probably a pretty rare edge case 😉.

**Comment by karlpatrickespiritu** [comment]
I'm actually having this issue for a few days now.

<img width="379" alt="postinstall" src="https://user-images.githubusercontent.com/10472504/38067937-19126854-3341-11e8-99d1-d0ee81600400.png">

**Comment by larsxschneider** [comment]
@karlpatrickespiritu Did you set the registry key `[HKEY_CURRENT_USER\Software\Microsoft\Command Processor]`? Do you have some custom `bat` file somewhere that contains the string `@IF 10 LEQ @(`?

**Comment by karlpatrickespiritu** [comment]
I updated my windows 10. That seemed have to fixed the problem. Thanks @larsxschneider.

**Comment by larsxschneider** [comment]
@dscho I don't think @karlpatrickespiritu configured a `cmd.exe` startup script. The error line he was seeing came probably from here: https://github.com/git-for-windows/build-extra/blob/master/post-install.bat#L22

**Comment by dscho** [comment]
@larsxschneider but where does that path come from? What is the source of this `C:\Program Files\Git>` in that output? That path should not have been *part* of the execution...

**Comment by dscho** [comment]
> The user configured a bat file that is executed on cmd.exe startup

@larsxschneider oh what the heck. I guess I'll have to bite the bullet and "unroll" `post-install.bat` in the InnoSetup-based installer so that it does not have to call the Batch script but calls `rebaseall` directly (if needed) and then executes the dummy login shell to give Bash a chance to initialize those directories.

Or maybe you have some time to implement this? 🤞

**Comment by dscho** [comment]
I guess this problem was not _that_ pressing, after all.
