### ISSUE TITLE
died waiting for dll loading, errno 11 - Windows 10 - Git 2.17.0

### ISSUE THREAD

**Issue by 16c7x** [git-for-windows/git#1586]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
This error has been reported before but it is reported as fixed in version 2.17.0. and previous errors all seem to be related to Windows 7 not 10.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

bash-4.4$ git --version --build-options
git version 2.17.0.rc0.windows.1
cpu: x86_64
built from commit: aec1b12d978b7b7d212da6af82b283c128f5daa7
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
`Defaults`
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```
```
Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Disabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

it's running powerbroker

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`bash`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
On the windows menu click the Git Bash icon, this runs the following command
"C:\Program Files\Git\git-bash.exe" --cd-to-home

```
 - What did you expect to occur after running these commands?

```
I expected gitbash to start up normally but it displayed these errors.
      0 [main] bash 15772 fork: child 2628 - died waiting for dll loading, errno                                                                                                11
bash: fork: retry: Resource temporarily unavailable
1307105 [main] bash 15772 fork: child 16952 - died waiting for dll loading, errn                                                                                               o 11
bash: fork: retry: Resource temporarily unavailable
3574269 [main] bash 15772 fork: child 16904 - died waiting for dll loading, errn                                                                                               o 11
bash: fork: retry: Resource temporarily unavailable
7841489 [main] bash 15772 fork: child 15212 - died waiting for dll loading, errn                                                                                               o 11
bash: fork: retry: Resource temporarily unavailable
16128419 [main] bash 15772 fork: child 13660 - died waiting for dll loading, err                                                                                               no 11
bash: fork: Resource temporarily unavailable
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

I've followed this
https://www.bountysource.com/issues/34992371-launching-git-bash-gives-bash-fork-retry-error
The ```HKLM\SOFTWARE\Policies\BeyondTrust\PBDesktops``` fix had no effect.

I've also tried the Windows defender changes detailed here 
https://stackoverflow.com/questions/38494951/git-bash-cannot-be-initialized

And tried the rebaseall work around in
https://www.bountysource.com/issues/30590053-git-bash-errors-in-2-7-0-2

I'm back on 2.7.0 which is working fine.

**Comment by dscho** [comment]
Is it possible that this is related to some Comodo software (as suggested by [this StackOverflow post](https://stackoverflow.com/questions/37263702/cant-start-git-bash))?

**Comment by 16c7x** [comment]
![reg1](https://user-images.githubusercontent.com/29106076/38361248-ac9102ce-38c4-11e8-9e66-7bc5f23eccfc.png)
No comodo but Power Broker is there, I've tried ```C:\Program Files\Git\*``` and the ``` \*.sh``` entry in ```ExcludedProfilerApps```.

**Comment by dscho** [comment]
> No comodo but Power Broker is there

Okay! There are a couple of closed tickets referencing that software: https://github.com/git-for-windows/git/issues?q=is%3Aissue+powerbroker+is%3Aclosed. Maybe one of them has some helpful information (sorry, I am short on time right now, otherwise I would have a look myself and come back with what I found)?
