### ISSUE TITLE
 git update-git-for-windows is much slower than download the installer directly from Chrome

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#1588]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
 Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
  git update-git-for-windows

```
 - What did you expect to occur after running these commands?

upgrade git for windows, It should keep at least the same speed compare to download the installer

 - What actually happened instead?

The speed of download is too slow, when I finished download the installer from Chrome, the command only finish 13% .

So, I wonder if the you can make the upgrade command faster to do the upgrade.

By the way, the Chrome and bash are using the same proxy to access the Internet.

**Comment by dscho** [comment]
Oh, that's sad!

Do you know whether both downloads are routed the same way?

Also, could you test out a couple of things by copy-editing `C:\Program Files\Git\mingw64\libexec\git-core\git-update-git-for-windows` so that it only downloads the installer (not run it, not perform any up-to-date checks), then call `export CURL_SSL_BACKEND=schannel` to compare the download speed?

This assumes that you know your way around Unix shell scripting, of course... if you are unfamiliar with that language, please let me know, I will try to give you better guidance.

Thanks!

**Comment by chucklu** [comment]
Hi @dscho,
    I can modify the  git-update-git-for-windows file to download the installer without version check and only download without start it.
    I have run `export CURL_SSL_BACKEND=schannel` in git bash, but nothing happened.
    I also tried to add a new environment variable on my computer.
   
    I have tried to run  `git update-git-for-windows`, it seems faster than yesterday. But still slower than Chrome.
    If you can count the time for the update script.

**Comment by dscho** [comment]
> I have run export CURL_SSL_BACKEND=schannel in git bash, but nothing happened

Sorry, I was confusing there.

The idea of setting that environment variable is to tell `curl.exe` (which `git-update-git-for-windows` uses to download a new installer) to use Secure Channel as backend for HTTPS transfer instead of OpenSSL (to test whether the native Windows library is faster).

So after setting that variable, please run your patched script to measure the speed.

To reset the backend to the default one, set `CURL_SSL_BACKEND=openssl`.

Also, to measure the time it took, you can use the command-line `time ./my-patched-script.sh`; the `time` utility will then print out how long the command ran.

> I have tried to run git update-git-for-windows ,
> it seems faster than yesterday. But still slower than Chrome.

I wonder whether Chrome opens multiple connections and downloads chunks in parallel?

**Comment by kgybels** [comment]
> @dscho I wonder whether Chrome opens multiple connections and downloads chunks in parallel?

There is a setting for it: `chrome://flags/#enable-parallel-downloading`

I did some tests with [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview), it seems the default is no parallel downloading.

@chucklu Could you check with [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) whether Chrome is using multiple connections to download?

**Comment by chucklu** [comment]
@dscho  `time ./my-patched-script.sh`
C:\Program Files\Git\mingw64\libexec\git-core>time .\git-update-git-for-windows
The system cannot accept the time entered.
Enter the new time:
It seems the time command in winodws is not used to calculate the time spent by the procedure.

What's is this file? ./my-patched-script.sh
Is it corresponding to  .\git-update-git-for-windows?

**Comment by chucklu** [comment]
@kgybels  I did not set the enable-parallel-downloading setting for chrome browser.
The setting keeps default now.

I have searched by Google about how to use tcp view to check parallel.
But can not find information about this,could you tell me how to use it?

**Comment by dscho** [comment]
> C:\Program Files\Git\mingw64\libexec\git-core>time .\git-update-git-for-windows
> The system cannot accept the time entered

Ooops, I thought you ran this command in Git Bash, not in Git CMD...

**Comment by chucklu** [comment]
@dscho I tried to run `$ time .\git-update-git-for-windows` in git bash, but got the following error:
bash: git-update-git-for-windows: **command not found**
why git-update-git-for-windows should be a command?

there is file under /c/Program Files/git/mingw64/libexec/git-core
$ ls git-update-git-for-windows
git-update-git-for-windows*

**Comment by chucklu** [comment]
got this error
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

> $ time git update-git-for-windows
> Using proxy server sasygsha01prx11_p.asnet.accorservices.net:8080 detected from git http.proxy
> Git for Windows 2.16.3.windows.1 (64bit)
> Update 2.16.3.windows.1 is available
> Download and install Git for Windows 2.16.3 [N/y]? y
> -=O=-                        #     #     #     #
> curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
> 
> real    1m17.738s
> user    0m0.000s
> sys     0m0.000s
>

**Comment by dscho** [comment]
> I tried to run $ time .\git-update-git-for-windows in git bash

In Bash, you must use forward-slashes as directory separators.

> I tried with this time git update-git-for-windows in git bash

This will run Git's version of the script, not your modified one (and therefore it won't try to download as you have a current Git for Windows version already).

> curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

I fear that this is the `http.proxy` setting interfering :-( Maybe you can copy-edit `C:\Program Files\Git\mingw64\libexec\git-core\git-update-git-for-windows` to, say, your Desktop and remove the part about setting the proxy (which Secure Channel should not need to be set manually), then run

```bash
time ~/Desktop/git-update-git-for-windows
```

in Git Bash?

**Comment by dscho** [comment]
> Maybe you can copy-edit `C:\Program Files\Git\mingw64\libexec\git-core\git-update-git-for-windows` to, say, your Desktop and remove the part about setting the proxy (which Secure Channel should not need to be set manually), then run
> 
> ```shell
> time ~/Desktop/git-update-git-for-windows
> ```
> 
> in Git Bash?

I guess you can't.
