### ISSUE TITLE
git difftool doesn't work; instead gives warning about line endings

### ISSUE THREAD

**Issue by Ciwan1859** [git-for-windows/git#1589]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

git version 2.16.2.windows.1

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Cmder

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```git difftool <file-name-with-path>```

Here's a screenshot too

![Image of commands and response](https://i.imgur.com/zGMbm28.jpg)

 - What did you expect to occur after running these commands?

I expected Beyond Compare 4 to open up and show me the differences

 - What actually happened instead?

Nothing happened!

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not specific to any particular repository

**Comment by dscho** [comment]
If you call `git diff -w` (i.e. ignoring white-space changes), does it show anything?
