### ISSUE TITLE
Issues with `tig`

### ISSUE THREAD

**Issue by kumarharsh** [git-for-windows/git#1590]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.192]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using Powershell v5 on ConEmu 180114

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$> tig
```
 - What did you expect to occur after running these commands?

Tig works well

 - What actually happened instead?

Tig works ok - but there are serious rendering issues in some cases:

1. The line alignment is off sometimes, and bunch of artifacts show up for repo with large commit history:

![image](https://user-images.githubusercontent.com/760112/37952759-836198a8-31be-11e8-9489-42d5d606f3b7.png)

Scrolling up/down keeps changing the indentation:
![image](https://user-images.githubusercontent.com/760112/37952772-9039c762-31be-11e8-91ef-88bb3f5522c0.png)

After scrolling up from bottom, the indentation resets to a better view:
![image](https://user-images.githubusercontent.com/760112/37952815-b4772ae8-31be-11e8-9e1d-d958eb110f47.png)

Resizing the window or shell's pane in ConEmu just destroys the whole view. Scrolling once fixes it though:
![image](https://user-images.githubusercontent.com/760112/37952858-d2c204b4-31be-11e8-9deb-be97edef0c2a.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Try cloning any big repo, go to it's root and run `tig` then try scrolling around and press Enter on some commit to view it.

**Comment by dscho** [comment]
> Try cloning any big repo, go to it's root and run tig then try scrolling around and press Enter on some commit to view it.

That is not a reliable way to reproduce, but puts the burden of finding a repository with this issue on anybody who wants to help.

Also: I cannot reproduce the issue. Unless I *unset* the environment variable `LC_CTYPE` (which defaults to `C` here). What does the `LC_*` part of your environment look like (and `LANG`)?

**Comment by dscho** [comment]
FWIW running `git -c alias.t=!tig t` (I cannot run `tig` directly because I chose only to add `git` to the `PATH`, not all of Git for Windows' included Unix tools) in a fresh Powershell works for me, too...

**Comment by kumarharsh** [comment]
![image](https://user-images.githubusercontent.com/760112/37971899-b582ab20-31f4-11e8-8f77-6bd8358234e5.png)

> That is not a reliable way to reproduce, but puts the burden of finding a repository with this issue on anybody who wants to help.

Ok, try cloning the VSCode repo then: `git@github.com:Microsoft/vscode.git`

**Comment by kumarharsh** [comment]
Also, `tig` is installed in `<Git-installation-dir>\usr\bin`.
```
tig version 2.3.3
```

**Comment by kumarharsh** [comment]
Also, I didn't ever have an `LCTYPE` env variable set in the first place.

**Comment by dscho** [comment]
It is `LC_CTYPE` (with an underscore, and the `C` repeated). What happens if you set it (this is one of the things `git -c alias.t=!tig t` does implicitly)?

**Comment by kumarharsh** [comment]
Setting `LC_CTYPE` isn't helping in ConEmu - it *might* be a bug in ConEmu(?)

In plain powershell/cmd, the `git -c alias.t=!tig t` does work well, as I said.

> The problem you face mainly has to do with the fact that you expose those Unix tools to environments that are ill-prepared to handle them (as you saw). That is why this is not the default, and not even recommended...

I hadn't run into any other issue *till now* regarding exposing unix tools. Will be more mindful henceforth.

So, is there a proper way to invoke `tig`? Should I make this a permanent alias in `.gitconfig`?

**Comment by dscho** [comment]
> I hadn't run into any other issue till now regarding exposing unix tools.

Lucky you ;-)

In this instance, I am not quite sure what we could do to help this use case, as I don't think MSYS2 will ever support "cold-calling" (i.e. running executables from `<toplevel>\usr\bin` outside a login Bash)...

> So, is there a proper way to invoke tig? Should I make this a permanent alias in .gitconfig?

If I were you, yes, I would install a permanent alias (`git config --global alias.tig '!tig'`).

**Comment by dscho** [comment]
> If I were you, yes, I would install a permanent alias (git config --global alias.tig '!tig').

By the way, if that work-around is good enough for you, this ticket can probably be closed.

**Comment by kumarharsh** [comment]
> By the way, if that work-around is good enough for you, this ticket can probably be closed.

It provides some sort of closure, yeah. Though ConEmu (my goto terminal emulator) still fails even with the alias - I think I'll take it up there though. I'll close this one.

Thanks for all your help!
