### ISSUE TITLE
warning: failed to restrict file handles

### ISSUE THREAD

**Issue by dkjkj** [git-for-windows/git#1591]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 Bit 

```
$ git --version --build-options

2.16.3.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 64 bit Enterprise
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults except for commit as-is

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status
```
 - What did you expect to occur after running these commands?

On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

 - What actually happened instead?

warning: failed to restrict file handles (1450)

warning: failed to restrict file handles (1450)

On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repos with submodules and also without submodules.

- Other
Same is also seen on git commit and git push

**Comment by cobrabr** [comment]
`git pull` and `git fetch` also display the same warning message.

**Comment by dscho** [comment]
Does the latest snapshot work for you? (There has been a fix for this exact symptom...) Please find the snapshots here: https://wingit.blob.core.windows.net/files/index.html

**Comment by cobrabr** [comment]
The latest snapshot seems to be working.

**Comment by dkjkj** [comment]
The https://wingit.blob.core.windows.net/files/Git-prerelease-2.16.3.windows.1.1.gf2a677fb4d-64-bit.exe does not have this problem.

**Comment by dscho** [comment]
@cobrabr @dkjkj excellent! Thank you so much for testing.

**Comment by orient33** [comment]
dun@MI-201903110628 MINGW64 /d/mygit/document (master)
$ git push
warning: failed to restrict file handles (5)

handle #0: 00000000000002e8 (type 3, handle info (1) 0
handle #1: 00000000000002ec (type 2, handle info (1) 1
handle #2: 0000000000000194 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 2.43 KiB | 2.43 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/orient33/document.git
   45ad6b8..57aa204  master -> master

dun@MI-201903110628 MINGW64 /d/mygit/document (master)
$ git version
git version 2.21.0.windows.1

**Comment by dscho** [comment]
@orient33 what is your Windows version?

**Comment by orient33** [comment]
> @orient33 what is your Windows version?

window 10    
Microsoft Windows [版本 10.0.17134.829]

**Comment by dscho** [comment]
@orient33 does this happen with all pushes? Does it also happen if you call this from a PowerShell?
