### ISSUE TITLE
Told to report

### ISSUE THREAD

**Issue by m4delas** [git-for-windows/git#1592]
madel@DESKTOP-142RVUV MINGW64 ~
$ cd lambdaschool

madel@DESKTOP-142RVUV MINGW64 ~/lambdaschool
$ git https://github.com/m4delas/Precourse.git
warning: failed to restrict file handles (2)

handle #0: 0000000000000414 (type 3, handle info (1) 0
handle #1: 0000000000000418 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'https://github.com/m4delas/Precourse.git' is not a git command. See 'git --help'.

**Comment by dscho** [comment]
Thank you for your report.

However, without the information from the bug report template, it is hard to assess whether you are reporting a new bug or one that has already been addressed. See https://github.com/git-for-windows/git/issues?utf8=%E2%9C%93&q=is%3Aissue+%22failed+to+restrict+file+handles%22+

Also, please test whether the issue persists with the latest snapshot: https://wingit.blob.core.windows.net/files/index.html
