### ISSUE TITLE
git svn clone does not support native Windows paths

### ISSUE THREAD

**Issue by ColMelvin** [git-for-windows/git#1593]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git for Windows v2.10.2 32-bit
```
C:\>git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 8.1 64-bit
```
C:\>cmd /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
IIRC, mostly the defaults, but I selected to add git.exe (but not the commands themselves) to the PATH. 
```
C:\>type "C:\Program Files (x86)\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None I can think of

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\example>svnadmin create repo

C:\example>git svn clone file:///C:\example\repo git
```
 - What did you expect to occur after running these commands?

The repository would be cloned.

 - What actually happened instead?

The command gave the following error:
```
Initialized empty Git repository in C:/example/git/.git/
Can't create session: Unable to connect to a repository at URL 'file:///C:%5Cexample%5Crepo': Unable to open repository 'file:///C:%5Cexample%5Crepo' at /mingw32/share/perl5/site_perl/Git/SVN.pm line 148.
```

Switching to URL-style separators did little to improve the issue:
```
C:\example>git svn clone file:///C:/example/repo git
Initialized empty Git repository in C:/example/git/.git/
Can't create session: Unable to connect to a repository at URL 'file:///C:/example/repo': Unable to open repository 'file:///C:/example/repo' at /mingw32/share/perl5/site_perl/Git/SVN.pm line 148.
```

Further investigation provided a stack trace:
```
C:\example>"C:\Program Files (x86)\Git\usr\bin\perl.exe" -MCarp=verbose "C:\Program Files (x86)\Git\mingw32/libexec/git-core\git-svn" clone file:///C:/example/repo git
Initialized empty Git repository in C:/example/git/.git/
Can't create session: Unable to connect to a repository at URL 'file:///C:/example/repo': Unable to open repository 'file:///C:/example/repo' at /usr/lib/perl5/vendor_perl/SVN
/Core.pm line 633.
        SVN::Error::croak_on_error(_p_svn_error_t=SCALAR(0x809eeac8)) called at /usr/lib/perl5/vendor_perl/SVN/Ra.pm line 529
        SVN::Ra::new("SVN::Ra", "url", "file:///C:/example/repo", "auth", _p_svn_auth_baton_t=SCALAR(0x809ef578), "config", HASH(0x809fb738), "pool", SVN::Pool=REF(0x809fb7e0), ...) called at /mingw32/share/perl5/site_perl/Git/SVN/Ra.pm line 128
        Git::SVN::Ra::new("Git::SVN::Ra", "file:///C:/example/repo") called at /mingw32/share/perl5/site_perl/Git/SVN.pm line 148
        Git::SVN::fetch_all("svn") called at C:\Program Files (x86)\Git\mingw32/libexec/git-core\git-svn line 525
        main::cmd_clone("file:///C:/example/repo", "git") called at C:\Program Files (x86)\Git\mingw32/libexec/git-core\git-svn line 386
        eval {...} called at C:\Program Files (x86)\Git\mingw32/libexec/git-core\git-svn line 384
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

 - Workarounds

Using URL-style separators and stripping the colon from the drive gets the clone working.  However, this means we are no longer using Windows paths; it's now using bash/mingw32/msys paths.

```
C:\example>git svn clone file:///C/example/repo git && echo "Success"
Initialized empty Git repository in C:/example/git/.git/
"Success"
```

 - Desired result

Match the behavior of `svn checkout file://…` where Windows paths are allowed:

```
C:\example>svn checkout file:///C:\example\repo svn
Checked out revision 0.

C:\example>svn checkout file:///C:/example/repo svn2
Checked out revision 0.

C:\example>svn --version
svn, version 1.9.4 (r1740329)
   compiled Apr 24 2016, 15:40:35 on x86-microsoft-windows
```

Obviously, the behavior inside a bash environment (on Windows) should remain unchanged.

If a functional change is untenable (this is a minor issue, after all), a more descriptive error message would help.  Researching this error showed others share the issue [1-2].  A message pointing the user in the right direction would be helpful.

[1] https://stackoverflow.com/questions/15374353/git-how-can-i-clone-local-svn-repository
[2] https://gitlab.com/tortoisegit/tortoisegit/issues/1402

**Comment by dscho** [comment]
Thank you for reporting this bug.

Maybe you want to give resolving this a hand? I imagine that the `file_name_is_absolute` function of [`File::Spec::Win32`](http://perldoc.perl.org/File/Spec/Win32.html) returns `2` for absolute paths. Or maybe this should be done manually, anyway.

As to the problem where `git-svn` needs to handle this: I followed the code path in [`git-svn.perl`](https://github.com/git-for-windows/git/blob/master/git-svn.perl) all the way down to [`canonicalize_url` in `Git::SVN::Utils`](https://github.com/git-for-windows/git/blob/7e4058d72e34b6a88e69f089515600d3aaffd255/perl/Git/SVN/Utils.pm#L139-L150), and it looks as if that function was a good place to do it. Something like

```perl
if ($^O eq 'msys' && $url =~ /^(file:\/\/\/)([A-Za-z]):([\\\/].*)/) {
    $url = "$1$2$3";
    $url =~ s/\\/\//g;
}
```

My Perl fu is adequate for hacking, but not for production code, so you probably know what I mean and how to improve it.

**Comment by asheiduk** [comment]
@ColMelvin  The [RFC 1738](https://tools.ietf.org/html/rfc1738#section-3.10) specifies that the path components of a `file://` URL are separated by `/` and not the OS specific separator. Crossreading https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/ seems to agree with that.

So the URL `file:///C:\example\repo` is just invalid input.

**Comment by asheiduk** [comment]
> While that may be true, Git already has a track record of not following the URL specification closely. And it seems that neither does Subversion[...]

I've played a little and it seems to that Subversion doesn't take the parameter verbatim:

```
C:\work\tmp\> svnadmin create repo
C:\work\tmp\> svn co file:///C:\work\tmp\repo wc1
C:\work\tmp\> svn info --show-item=url wc1
file:///C:%5Dwork%5Dtmp%5Drepo
```
The next strange thing (to me) is that the same commands produce different output in git-bash:

```
/c/work/tmp$ svn co 'file:///C:\work\tmp\repo' wc2
/c/work/tmp$ svn  info --show-item=url wc2
file:///C:/work/tmp/repo
```

And yes, `svn` is the same executable from TortoiseSVN in both cases.

**Comment by ColMelvin** [comment]
How odd; I suspect there is some translation happening in git-bash.

Regardless, it seems like Subversion is not following the spec for the slashes, so I would not expect Git to match it.  Perhaps the scope can be cut back to just supporting drives.

@dscho My attention is scattered at the moment.  I'd be willing to work on this, but may not be able to get to it quickly.  Feel free to assign this case to me.

**Comment by dscho** [comment]
> My attention is scattered at the moment.

@ColMelvin no worries!

> I'd be willing to work on this, but may not be able to get to it quickly.

Since this is a feature you want: take your pace. If you need anything from my side, please just ask.

> Feel free to assign this case to me.

Thank you! Done.

**Comment by PhilipOakley** [comment]
The MSYS2 does do some path mangling, and other substitutions, which can catch git (and users) out. I think there is a similar (though not identical) issue in #1220

**Comment by ColMelvin** [comment]
I dug into the code and I suspect the _SVN_ perl library is actually the source of the problem.  Ultimately, the stack traces back to `SVN::_Ra` which, on my system, is provided by Git for Windows.  Since these modules are compiled against MinGW and not Windows proper, I suspect they can only handle MinGW paths.

Following this logic, I should be able to install `SVN::Ra` and friends on native Windows (and inject them into `@INC`) for proper handling of Windows paths.  Unfortunately, I'm having difficulty testing this hypothesis: ActivePerl does not have a PPM for `SVN::Ra` and `cpan install SVN::Ra` fails to compile because `sh` is missing (on CMD).  Does anyone know of way to get this installed on Windows proper?

If it is possible to install the SVN modules on Windows' Perl, then blindly stripping out the colon could actually break existing use cases.  We might be able to build a fallback mechanism that strips the colon on Windows systems after the first attempt fails.  However, this raises the question: _should we?_  This dives into work-around territory, which warrants taking a step back.

If I can prove a native Windows module fixes the issue, then I'd be willing to close this issue.  That said, I'm not the first - and, if left unchanged, won't be the last - to get caught up by this confusion (see references in OP), so _some_ change is desirable.  For example, we can add an entry to the docs to aid with troubleshooting.

I'm open to suggestions.

**Comment by dscho** [comment]
@ColMelvin nice analysis!

One minor correction: these modules are *MSYS* modules, i.e. they link against the MSYS2 runtime (which is a fork of the Cygwin runtime) that provides a "Unix emulation layer" including the emulation of Unix paths.

MINGW would be kind of the opposite: software that does *not* use any Unix emulation layer but uses whatever is provided by the MSVC runtime and the Win32 API.

ActiveState Perl is most notably *not* MSYS (it is not even MINGW, as it is not compiled using GCC), hence it should not share those path problems you described. But as you say: it does not come with SVN.pm.

And you cannot just take the SVN.pm from somewhere else, as it includes native parts that very much target a specific Perl version, no mixing and matching is possible.

And now you know why we have an MSYS Perl: to support `git svn`. Because it took developer-years to even get things to build where we could run `git svn` on Windows for the first time.

The proper solution would be to switch to a non-MSYS Perl and build Subversion with its Perl modules using the same system. I have *no* idea how feasible it would be with ActiveState. An alternative would be to try to switch to MINGW Perl. There is such a Perl package available in the MSYS2 project: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-perl. Sadly, there is no corresponding https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-subversion (and from experience, I would expect it to be a bit involved to get to work).

The easiest workaround for your issue might be to try to patch https://github.com/Alexpux/MSYS2-packages/tree/master/subversion to let `SVN::Ra` know about native Windows paths. But then, it might be too late at that stage already because `SVN::Ra` does not receive the paths as passed in from Git: Git is MINGW, so when it calls MSYS Perl, the paths get "translated" by the MSYS2 runtime into Unix format.

**Comment by dscho** [comment]
Let's just close this, as it seems that interest in this has died down.
