### ISSUE TITLE
Unable to clone projects on windows.

### ISSUE THREAD

**Issue by marekgebka** [git-for-windows/git#1594]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
   Git for Windows 64-bit

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
 
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 **Windows 7 / 64-bit.**

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

  **defaults**

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

C:\Program Files\Git\etc\install-options.txt

Editor Option: VisualStudioCode
Path Option: Cmd
Plink Path: C:\Program Files (x86)\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

``` 

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**Used to work just fine until a couple of weeks ago. Didn't change anything just noticed I couldn't clone anymore. Pull/push for already checked out projects worked fine as well, We already tried to set the environment variable as the error message suggests but to no avail**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
  

**Git Bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone git@github.com:marekgebka/fe-workshop-slides.git
```
 - What did you expect to occur after running these commands?

**That the Repo would have been cloned**

 - What actually happened instead?

```
warning: failed to restrict file handles (5)

handle #0: 0000000000000058 (type 2, handle info (1) 0
handle #1: 0000000000000050 (type 2, handle info (1) 1
handle #2: 000000000000004c (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn "C:\Program Files\PuTTY\": Permission denied
error: cannot spawn "C:\Program Files\PuTTY\": Permission denied
fatal: unable to fork
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**https://github.com/marekgebka/fe-workshop-slides**

**Comment by dscho** [comment]
Thank you for your report.

Could you please test whether the issue persists with the latest snapshot: https://wingit.blob.core.windows.net/files/index.html

**Comment by marekgebka** [comment]
Hey, thanks for the tip. 
I've the just installed the version you have referenced and it worked out fine.
