### ISSUE TITLE
v2.16.3 Git 5d726e0 x64  - warning failed to restrict file handles (1450)

### ISSUE THREAD

**Issue by VictorVG** [git-for-windows/git#1595]
Git for Windows v2.16.3 Git 5d726e0 x64 , OS Windows 7 SP1 x64, Git installed by default in to $PROGRAMFILES .

Whets I see? I past _git pull origin HEAD_ for any local working copy and before begin command out only for this version read:

```
git pull origin HEAD
warning: failed to restrict file handles (1450)


warning: failed to restrict file handles (1450)


warning: failed to restrict file handles (1450)


From https://github.com/yutsis/YMSPlugins
 * branch            HEAD       -> FETCH_HEAD
Already up to date.
```
On v2.16.2 this was not.

**Comment by chmolinari** [comment]
Same issue.

PS>git --version --build
git version 2.16.3.windows.1
cpu: x86_64
built from commit: 5d726e05e4c0ff9e11374e64e21d8300b0291c6d
sizeof-long: 4

OS version: Windows 7 Enterprise SP1.

**Comment by dscho** [comment]
Could you please try with the latest snapshot at https://wingit.blob.core.windows.net/files/index.html? Thank you!

**Comment by VictorVG** [comment]
I check Git-v2.16.3 Git gf2a677fb4d 64 bit : 
```
git pull origin HEAD -f
From https://github.com/VictorVG/test
 * branch            HEAD       -> FETCH_HEAD
Already up to date.

git fetch origin master
From https://github.com/VictorVG/test
 * branch            master     -> FETCH_HEAD
```
- this snapshot don't have error.

**Comment by chmolinari** [comment]
Hi Johannes,


I've tried to install version 2.17 RC 1 which still presents the issue:


PS>git --version --build
git version 2.17.0.rc1.windows.1
cpu: x86_64
built from commit: 385f9cec7cafe3b15e464ff25c2bd3ae72acd57c
sizeof-long: 4


I'm now installing the version you suggested and let you know.


Thanks for now.


— Christian Molinari

     chmolinari@christianmolinari.com<mailto:chmolinari@christianmolinari.com>

________________________________

**Comment by VictorVG** [comment]
v2.17.0 - first test, two systems, no questions. Thanks.

**Comment by dscho** [comment]
@VictorVG thanks for testing and coming back with the results! @Robbbert I assume you also confirm that v2.17.0 fixes the issue for you?

**Comment by Flightdeck73** [comment]
Just upgraded a bunch of systems with the git [2.17.0 choco package](https://chocolatey.org/packages/git). 
No more: _warning: failed to restrict file handles (1450)_
Thank you!

**Comment by Robbbert** [comment]
> @Robbbert I assume you also confirm that v2.17.0 fixes the issue for you?

Yes indeed.

**Comment by VictorVG** [comment]
I have no errors with 2.17.0. The commands I use in the [**user submenu Git of Far Manager 3.0**](https://github.com/VictorVG/FarUE3_x64/wiki/1) work flawlessly.

**Comment by chmolinari** [comment]
Yeap, no more errors.

PS>git --version --build
git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
