### ISSUE TITLE
Git GUI Command Will Not Open Git GUI

### ISSUE THREAD

**Issue by calioto** [git-for-windows/git#1596]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.1.windows.2
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Behind company proxy/firewall

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git-gui
```
 - What did you expect to occur after running these commands?

Git GUI to display

 - What actually happened instead?
![git](https://user-images.githubusercontent.com/29551362/38040345-efe1bdee-3274-11e8-91ab-f5b7e2538735.PNG)

Error popup message stating, "Cannot determine Git version".

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Could you test with the latest snapshot ad https://wingit.blob.core.windows.net/files/index.html? Thanks!

**Comment by calioto** [comment]
My company does not allow me to install software on my machine. We have certain versions available from our internal site that we request be installed and it is done remotely.

**Comment by calioto** [comment]
I previously had 2.14 installed and it was happening with that version too. But, a coworker of mine has 2.14 installed on his machine and the GUI loads up just fine.

**Comment by dscho** [comment]
Oy, I just thought of something: Do you have the environment variable `GIT_TRACE` set to `1` perchance?

**Comment by calioto** [comment]
Yes. GIT_TRACE_CURL is also set to 1.

**Comment by dscho** [comment]
@calioto that is the culprit. Please note that many Git-related tools do not work with `GIT_TRACE` and/or `GIT_TRACE_CURL` are set to `1`.

If you really want a constant record of all of your Git's internal operations, why not set them to full paths? Then Git logs into those files, and the tools won't be badly affected by spurious output.

Of course, if I were you, I would simply unset those environment variables, because they really are only intended for extended logging when investigating problems. And they slow down Git, too.
