### ISSUE TITLE
Git for windows Installer doesnt produce launch-able git bash

### ISSUE THREAD

**Issue by ronnyek** [git-for-windows/git#1600]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
**I found issues that appeared to report the same functionality, but that specific problem was fixed and issue is cropping up for other reasons or... I dont know.**

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git-2.16.2 64bit

```
$ git --version --build-options

** git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4 **

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windows 10
```
$ cmd.exe /c ver

**Microsoft Windows [Version 10.0.16299.309]**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
I chose the default options for everything, except opted to have command line tools available from both cmd and gitbash
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

```
Editor Option: VIM
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**trying to run git bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**clicked git bash in start menu after install**
```
 - What did you expect to occur after running these commands?

**popping up git bash shell**

 - What actually happened instead?

**nothing**

I have seen reports of this, some people claim they need to start with admin, some people say they cant start with admin. Neither seems to fix it in this case.

I saw some work arounds that suggested to change what the shortcut points to... that didnt actually fix it either.

If I start windows command prompt, and then type bash, it starts bash (though admittedly dont know if its forgoing any normal command line arguments or environment variables)

**Comment by dscho** [comment]
Could you start a CMD, then `cd` to `C:\Program Files\Git` and start `usr\bin\bash.exe -li`?

**Comment by ronnyek** [comment]
Actually in my case since I added path to use git tools in both cmd and gitbash, I can just launch command prompt, and then run "bash" and it works.

If I include the -li parameters I get the following
```
c:\Program Files\Git>usr\bin\bash.exe -li
      1 [main] bash 3488 fork: child 29000 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
1147016 [main] bash 3488 fork: child 27120 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
3296247 [main] bash 3488 fork: child 35872 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
7430815 [main] bash 3488 fork: child 39284 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
15568433 [main] bash 3488 fork: child 32860 - died waiting for dll loading, errno 11
bash: fork: Resource temporarily unavailable
bash-4.4$
```

**Comment by dscho** [comment]
> ```
> 1 [main] bash 3488 fork: child 29000 - died waiting for dll loading, errno 11 bash: fork: retry: Resource temporarily unavailable
> ```

According to https://stackoverflow.com/questions/37263702/cant-start-git-bash, this may be an issue with Comodo software?

**Comment by dscho** [comment]
Lacking any sort of response, I am kind of forced to think that my hunch was correct.
