### ISSUE TITLE
Git installer Git-2.16.2-32-bit can´t be downloaded

### ISSUE THREAD

**Issue by lopezpleonel** [git-for-windows/git#1605]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### the file Git-2.16.2-32-bit.exe can't be downloaded from https://github.com/git-for-windows/git/releases/tag/v2.16.3.windows.1 and also https://git-scm.com/download/win

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```Git-2.16.2-32-bit
$ git --version --build-options

** insert your machine's response here **
```download failed

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```Windows 10

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```Not apply
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```Download file failed

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by VictorVG** [comment]
Go to https://github.com/git-for-windows/git/releases/tag/v2.16.2.windows.1 and download. Your use link fo r different version.

**Comment by lopezpleonel** [comment]
Thanks Victor, the problem is that it started to download and it reaches 3 MB of 37 MB and it stops. Allways is the same.

I have tried 12 times. Can I downloaded on another site safely.

**Comment by VictorVG** [comment]
Ok.  Then it looks like it is your browser's problem, which at some point in time loses its connection to the data source. Let's do it in the simplest way - let's assign the work to the tool, which it will reliably do. For example, cURL is good in Git itself.

_cURL -C - -LR --create-dirs --output  [full path and download_file_name] download_URL_

**Comment by dscho** [comment]
I'll just assume that @VictorVG's advice was helpful (even if it was not exactly graced with an answer).

**Comment by lopezpleonel** [comment]
Yes, he was not.

Enviado desde Yahoo Mail para Android 
 
  El dom., 13 de oct. de 2019 a la(s) 7:47 PM, Johannes Schindelin<notifications@github.com> escribió:   
I'll just assume that @VictorVG's advice was helpful (even if it was not exactly graced with an answer).

**Comment by dscho** [comment]
> Yes, he was not.

This leaves me puzzled. But maybe I should not care that much, if the answer to my comment "there was no reaction!" is so terse as to be unclear.
