### ISSUE TITLE
error: cannot spawn C:\Program Files\Git\bin: Permission denied

### ISSUE THREAD

**Issue by noellowrysap** [git-for-windows/git#1609]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10, 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone
```
 - What did you expect to occur after running these commands?

repo cloned

 - What actually happened instead?

Cloning into 'Portal'...
warning: failed to restrict file handles (5)

handle #0: 00000000000000a4 (type 2, handle info (1) 1b84
handle #1: 00000000000000d8 (type 2, handle info (1) 1
handle #2: 00000000000000dc (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn C:\Program Files\Git\bin: Permission denied
error: cannot spawn C:\Program Files\Git\bin: Permission denied
fatal: unable to fork

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

seems to be any repo

**Comment by dscho** [comment]
Thank you for your report.

There are still quite a bit of things unclear to me. Could you please repeat your reproducer (which does not reproduce the problem in my setup) after setting the environment variable `GIT_TRACE=1`?

**Comment by noellowrysap** [comment]
git clone git@github.wdf.sap.corp:PharmaNetwork/Portal.git
16:45:02.472989 git.c:344               trace: built-in: git 'clone' 'git@github.wdf.sap.corp:PharmaNetwork/Portal.git'
Cloning into 'Portal'...
16:45:02.518117 run-command.c:627       trace: run_command: 'C:\Program Files\Git\bin' '-G' 'git@github.wdf.sap.corp'
warning: failed to restrict file handles (5)

handle #0: 00000000000000e0 (type 2, handle info (1) c314
handle #1: 00000000000000e8 (type 2, handle info (1) 1
handle #2: 00000000000000e4 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn C:\Program Files\Git\bin: Permission denied
16:45:02.521119 run-command.c:627       trace: run_command: 'C:\Program Files\Git\bin' 'git@github.wdf.sap.corp' 'git-upload-pack '\''PharmaNetwork/Portal.git'\'''
error: cannot spawn C:\Program Files\Git\bin: Permission denied
fatal: unable to fork

**Comment by noellowrysap** [comment]
git config -l --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Progra                                                                                                                                                                                               m Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textcon                                                                                                                                                                                               v=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs                                                                                                                                                                                                clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lf                                                                                                                                                                                               s smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-l                                                                                                                                                                                               fs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manage                                                                                                                                                                                               r
file:C:/Users/C5249189/.gitconfig       filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/C5249189/.gitconfig       filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/C5249189/.gitconfig       filter.lfs.required=true
file:C:/Users/C5249189/.gitconfig       filter.lfs.process=git-lfs filter-proces                                                                                                                                                                                               s
file:C:/Users/C5249189/.gitconfig       user.name=Noel Lowry
file:C:/Users/C5249189/.gitconfig       user.email=noel.lowry@sap.com
file:C:/Users/C5249189/.gitconfig       push.default=upstream
file:C:/Users/C5249189/.gitconfig       http.sslverify=false
file:C:/Users/C5249189/.gitconfig       http.proxy=http://C5249189@proxy.gwy.sap                                                                                                                                                                                               .corp:8080
file:C:/Users/C5249189/.gitconfig       color.ui=true
file:C:/Users/C5249189/.gitconfig       gui.recentrepo=C:/dev/github_repo/test
file:C:/Users/C5249189/.gitconfig       alias.co=checkout
file:C:/Users/C5249189/.gitconfig       alias.ci=commit
file:C:/Users/C5249189/.gitconfig       alias.st=status
file:C:/Users/C5249189/.gitconfig       alias.br=branch
file:C:/Users/C5249189/.gitconfig       alias.hist=log --pretty=format:"%h %ad |                                                                                                                                                                                                %s%d [%an]" --graph --date=short
file:C:/Users/C5249189/.gitconfig       alias.type=cat-file -t
file:C:/Users/C5249189/.gitconfig       alias.dump=cat-file -p
file:C:/Users/C5249189/.gitconfig       core.autocrlf=true
file:C:/Users/C5249189/.gitconfig       core.safecrlf=false
file:C:/Users/C5249189/.gitconfig       credential.helper=wincred
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.wdf.sap.corp/PharmaNetw                                                                                                                                                                                               ork/Portal.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        branch.QA_Deployment.remote=origin
file:.git/config        branch.QA_Deployment.merge=refs/heads/QA_Deployment
file:.git/config        branch.piper.remote=origin
file:.git/config        branch.piper.merge=refs/heads/piper

**Comment by dscho** [comment]
Okay, that was the config, and obviously there is not even a "ssh" substring in it.

So how about the environment? Do you have any `GIT_SSH` or `GIT_SSH_COMMAND` or something similar?

**Comment by Jijiri1** [comment]
Hi
