### ISSUE TITLE
Symlinks to submodules' inner directories are broken

### ISSUE THREAD

**Issue by Myllyenko** [git-for-windows/git#1610]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Windows Developer Mode is enabled

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD + TortoiseGit

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone --recurse-submodules https://github.com/Myllyenko/submodule-symlink-demo.git
```
 - What did you expect to occur after running these commands?

A cloned repo with all symlinks in a working state.

 - What actually happened instead?

A symlink that points to a directory in a submodule (`link_to_submodule_directory`) does not work. But it can be brought to a working state by simple removing and restoring:
```
cd submodule-symlink-demo
del link_to_submodule_directory
git checkout .
```
It is obviously related to the fact that at the moment when the symlink is being cloned its target does not exist as submodule is cloned later. But for some reason this issue does not affect symlinks that point to regular files in submodules.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/Myllyenko/submodule-symlink-demo.git

**Comment by dscho** [comment]
> A symlink that points to a directory in a submodule (link_to_submodule_directory) does not work. But it can be brought to a working state by simple removing and restoring:
> 
> ```
> cd submodule-symlink-demo
> del link_to_submodule_directory
> git checkout .
> ```
> 
> It is obviously related to the fact that at the moment when the symlink is being cloned its target does not exist as submodule is cloned later. But for some reason this issue does not affect symlinks that point to regular files in submodules.

Indeed, this seems to be the issue, combined with the fact that the recursive checkout is too fragmented. If the submodules would be checked out in the same process that also checks out the superproject, the `process_phantom_symlinks()` function would have a chance of catching these conditions...

**Comment by BenLubar** [comment]
Either this has regressed further or I'm doing something different than @Myllyenko's workaround:

```
git clone --recurse-submodules -b go-get https://github.com/BenLubar/gapstone.git
cd gapstone\include
del capstone
git checkout .
```

After this, `capstone` is still a text file containing `../capstone/include`.

Additionally:

```
del capstone
mklink /d capstone ..\capstone\include
git status
```

has the following `git status` output:

```
On branch go-get
Your branch is up to date with 'origin/go-get'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   capstone

no changes added to commit (use "git add" and/or "git commit -a")
```

`git diff` returns with no output, and `git add capstone` causes the working tree to become clean and no changes to be staged for commit.

**Comment by dscho** [comment]
The problem here is that the symbolic link *types* can only be determined once the targets are there, and that might not be the case depending on submodule checkout order.

To help this, Git for Windows v2.21.0 comes with support to declare the symlink types via `.gitattributes`. In your case, adding `capstone symlink=dir` to `.gitattributes` (or if you prefer not to commit this, `.git/info/attributes`) should help.
