### ISSUE TITLE
2.17.0 missing MinGit-2.17.0-busybox-32-bit.zip!

### ISSUE THREAD

**Issue by dhirschfeld** [git-for-windows/git#1611]
The 32-bit busybox git is missing in the 2.17.0 release assets.

I also checked that it's definitely not available for download - i.e. the below url gives an error page:
https://github.com/git-for-windows/git/releases/download/v2.17.0.windows.1/MinGit-2.17.0-busybox-32-bit.zip

**Comment by dhirschfeld** [comment]
![image](https://user-images.githubusercontent.com/881019/38282980-a7e6a338-37f6-11e8-8584-2711d7d6fe09.png)

**Comment by dscho** [comment]
Thanks for the report! I fixed this, and I think I also fixed the problem in the automation.
