### ISSUE TITLE
Git-Bash cygwin dll errors on launch - Win10Pro_64bit (#1523 reopened)

### ISSUE THREAD

**Issue by gopinaath007** [git-for-windows/git#1615]
Reopened as a result of owner breaching code of conduct: Failure to show empathy towards other community members

This is a continuation of issue 1523 which the owner disrespectfully closed my issue when I clearly mentioned that I will bring the rebase error screenshot after 25th May. I am currently on a 12week full-time data science bootcamp which is taking up most of my time. I promise I will come back to help resolve this git issue rebase error after 25th May.

**Comment by dscho** [comment]
Okay, let's make a deal. I reopen #1523 when you start answering my requests for precise output. I really asked for it respectfully, several times, with answers like [this one](https://github.com/git-for-windows/git/issues/1523#issuecomment-370120858) and [this one](https://github.com/git-for-windows/git/issues/1523#issuecomment-370414498) (i.e. without a trace of a precise output, which is insulting). And it is not like I am asking you for a favor. It is the other way around.

So: please copy and paste the output of [the command](https://github.com/git-for-windows/git/issues/1523#issuecomment-368852278) and its output. Into #1523, where that information was requested, multiple times.

**Comment by gopinaathragavan** [comment]
@dscho That's a deal. But i reiterate I will do that after the 25th May.  I answered all your questions with screenshots except the rebase error when I had a change of personal circumstances which you clearly still do not seem to understand after which you disrespectfully closed the thread. There is nothing insulting except for your lack of empathy and understanding.

**Comment by dscho** [comment]
Please refrain from pasting screenshots when you can copy/paste text instead.

And if you want me to help you, maybe you want to stop accusing me. Sure, you said somewhere that you would come back later. You know how many tickets I deal with on a daily basis? Do you really think you are the only one with problems? Yes, I forgot. And having your ticket open for months on end without any feedback is not making my workload easier. In any case, I do not *have* to help you. You are asking me to help you. Might just as well show a little respect for me, for a change, you could.

**Comment by gopinaath007** [comment]
I know you have 136 issues. I'm doing you a favour by not having to help me until 25th May. One less thing for you to worry about. I'm just helping you sort a bug in git bash. If you dont want to help me, I don't really care. I dont need to tolerate your attitude as I can always use other git terminals which work.

You're the one who accused me of not pasting the errors when I actually did and then you closed my issue. I have not accused you of anything for you to say I disrespected you. The techies that I have dealt with in the past usually prefer screenshots as they say a picture says a thousand words. You're the only one I have seen that seems to hate screenshots

**Comment by dscho** [comment]
> I'm doing you a favour by not having to help me until 25th May.

Thank you so much for this big favor!

**Comment by gopinaath007** [comment]
@yangshengf noted your reference to #910 which I didn't see in my initial search for similar issues to mine. My issue is resolved credits to you. Thank you. Issue closed

**Comment by gopinaath007** [comment]
@dscho https://cloud.githubusercontent.com/assets/10187424/19164379/56c4d832-8bc5-11e6-9a47-f793dd2277f6.png

This guy has the same rebase error message I had. Just copied it for your reference
