### ISSUE TITLE
Jenkins git plugin ssh clone fails in 2.17.0 (Windows)

### ISSUE THREAD

**Issue by MarkEWaite** [git-for-windows/git#1616]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Jenkins git plugin fails to clone an ssh authenticated repository with Windows git 2.17.0.  See [JENKINS-50573](https://issues.jenkins-ci.org/browse/JENKINS-50573) for more details.  The problem appears to be specific to Windows.

Successfully clones the same repository with Windows git 2.16.x and earlier.  

Successfully clones the same repository with git 2.17.0 compiled from source on my Ubuntu 16.04 installation.

The Jenkins git client plugin was modified in [Jan 2018](https://github.com/jenkinsci/git-client-plugin/commit/e8e1444c7f07b52d2d9b380257b2cc81e10bb0a5) to add the [GIT_SSH_VARIANT environment variable](https://git-scm.com/docs/git#git-codeGITSSHVARIANTcode) as required by git 2.16.x.  That resolved [JENKINS-49111](https://issues.jenkins-ci.org/browse/JENKINS-49111).

Are there additional interactions with GIT_SSH_VARIANT in the Windows git code?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Other - executing Windows git 2.17.0 from the Jenkins agent Java process.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
The Jenkins git client plugin uses the GIT_SSH environment variable to set the location of the ssh script to use and also sets SSH_ASKPASS.
```
 - What did you expect to occur after running these commands?

Repository should have cloned successfully.

 - What actually happened instead?

```
using GIT_SSH to set credentials MarkEWaite github rsa private key
 > git fetch --no-tags --progress git@github.com:MarkEWaite/bin.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=6
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:MarkEWaite/bin.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:887)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1144)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1175)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1203)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "git fetch --no-tags --progress git@github.com:MarkEWaite/bin.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: MarkEWaite@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

git@github.com:MarkEWaite/bin.git (a private repo)

**Comment by dscho** [comment]
Thank you for reporting this issue.

> Are there additional interactions with GIT_SSH_VARIANT in the Windows git code?

There should not be any left... and I cannot see any in the diff either...

> stderr: MarkEWaite@github.com: Permission denied (publickey).

Two ideas:

1. can you set `GIT_TRACE=1`, too?
2. when you override `GIT_SSH` already, can you set `GIT_SSH_COMMAND` instead and also add `-v -v -v -v -v` to it?

**Comment by MarkEWaite** [comment]
Thanks.  I'll spend time debugging from my side.  I've installed Windows git 2.17.0 on my dev machine and verified that I can see the problem.  Knowing that you're not immediately aware of any specific changes in that area makes it clear that I'll be the most effective one to investigate.

I'll post updates here as I learn more.

**Comment by dscho** [comment]
> I'll post updates here as I learn more.

Can you maybe create a minimal reproducer that does not need going through Jenkins? (No need to share your personal private key, I have my own, and there should not be any need for a private repository, nor for `fetch` (`ls-remote` should do nicely)).

**Comment by MarkEWaite** [comment]
I think I've found the minimum duplication case.

Create a file 'x.bat' with the contents

```
@echo off
"C:\Program Files\Git\usr\bin\ssh.exe" -i "C:\Users\MarkE\.ssh\id_rsa" -l "jenkins" -o StrictHostKeyChecking=no %*
```

Export the environment variable

```
GIT_SSH=..\x.bat
```

Run the command:

```
git ls-remote -h -t git@github.com:MarkEWaite/tasks.git
```

That command will report:

```
jenkins@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It works correctly if the x.bat file is instead:

```
@echo off
"C:\Program Files\Git\usr\bin\ssh.exe" -i "C:\Users\MarkE\.ssh\id_rsa" -l "git" -o StrictHostKeyChecking=no %*
```

I assume the ssh command in Windows git 2.17.0 is no longer ignoring the `-l jenkins` argument.

Did the ssh version bundled in Windows git 2.17.0 change compared to Windows git 2.16.x?

**Comment by dscho** [comment]
> Did the ssh version bundled in Windows git 2.17.0 change compared to Windows git 2.16.x?

Yes (OpenSSH v7.6p1 -> v7.7p1), but not in such a crucial way as to interpret `-l "jenkins"` all of a sudden...

However, I think that it is not as simple as ignoring `-l` or not: your command-line lists `git@github.com`, i.e. an explicit user name, and your `x.bat` has a contradicting `-l "jenkins"`. I could imagine that for some reason the order of preference changed in OpenSSH, but I do not see anything to that end in their release notes: https://www.openssh.com/txt/release-7.7

**Comment by dscho** [comment]
Maybe the diff between those versions clarifies anything? I am looking at https://github.com/openssh/openssh-portable/compare/V_7_6_P1...V_7_7_P1 (which is huge...)

**Comment by dscho** [comment]
> I do not see anything to that end in their release notes: https://www.openssh.com/txt/release-7.7

The only thing I saw there that looks vaguely related is this:

>  * ssh(1)/scp(1)/sftp(1): Add URI support to ssh, sftp and scp, e.g. ssh://user@host or sftp://user@host/path.  Additional connection parameters described in draft-ietf-secsh-scp-sftp-ssh-uri-04 are not implemented since the ssh fingerprint format in the draft uses the deprecated MD5 hash with no way to specify the any other algorithm.

Maybe the patches also inverted the order of precedence between `user@host` and `-l user`?

**Comment by dscho** [comment]
> your command-line lists git@github.com, i.e. an explicit user name, and your x.bat has a contradicting -l "jenkins". I could imagine that for some reason the order of preference changed in OpenSSH

FWIW I just tested this with Git for Windows v2.17.0 (OpenSSH v7.7p1) and with Git for Windows v2.16.2 (OpenSSH v7.6p1), and I can confirm that the order of preference *has changed*. I would call this a regression because it has not been listed in the "possibly backwards-incompatible changes".

**Comment by MarkEWaite** [comment]
Thanks very much.

That means the same problem will appear on Linux platforms when they upgrade to OpenSSH 7.7p1 or later.  I think the Jenkins plugin will need to stop relying on that order of preference.  It seems illogical (at least to me) to provide a URL that says "I'm the user named 'git'" and then provide a command line argument that says "I'm the user named 'jenkins'".

I'll submit a bug report to the OpenSSH project.

**Comment by MarkEWaite** [comment]
[OpenSSH bug 2849](http://bugzilla.mindrot.org/show_bug.cgi?id=2849) has been submitted to describe the difference in behavior.

**Comment by dscho** [comment]
... and I found something: https://github.com/openssh/openssh-portable/compare/V_7_6_P1...V_7_7_P1#diff-5bfa45f3fb322e569a8101399c9c551cR1001

See how it changes the parsing to call `parse_ssh_uri()` instead of looking for a hard-coded `@`? This change was introduced in this commit: https://github.com/openssh/openssh-portable/commit/887669ef032d63cf07f53cada216fa8a0c9a7d72, in particular in the change starting from this line: https://github.com/openssh/openssh-portable/commit/887669ef032d63cf07f53cada216fa8a0c9a7d72#diff-5bfa45f3fb322e569a8101399c9c551cL936. The *crucial* part is that the code to set the user name from the URL read like this before:

```c
                if (strrchr(*av, '@')) {
                        p = xstrdup(*av);
                        cp = strrchr(p, '@');
                        if (cp == NULL || cp == p)
                                usage();
                        options.user = p;
                        *cp = '\0';
                        host = xstrdup(++cp);
                } else
                        host = xstrdup(*av);
```

Note how it did not bother to see whether `options.user` was already set? This is in stark contrast to the new code:

```c
                switch (parse_ssh_uri(*av, &tuser, &host, &tport)) {
                case -1:
                        usage();
                        break;
                case 0:
                        if (options.user == NULL) {
                                options.user = tuser;
                                tuser = NULL;
                        }
                        free(tuser);
                        if (options.port == -1 && tport != -1)
                                options.port = tport;
                        break;
                default:
                        p = xstrdup(*av);
                        cp = strrchr(p, '@');
                        if (cp != NULL) {
                                if (cp == p)
                                        usage();
                                if (options.user == NULL) {
                                        options.user = p;
                                        p = NULL;
                                }
                                *cp++ = '\0';
                                host = xstrdup(cp);
                                free(p);
                        } else
                                host = p;
                        break;
                }
```

Note how it is now *really* careful to *not* set `options.user` when it has already been set previously (which is the exact opposite behavior of v7.6p1)?

It gets worse. While it can be argued that the command-line option should take precedence over the URI, what definitely is a regression is that specifying multiple `-l` options *keeps the first* username, as opposed to the previous behavior (where later `-l` options would override earlier ones, a well-established Best Practice):

```diff
                case 'l':
-                       options.user = optarg;
+                       if (options.user == NULL)
+                               options.user = optarg;
                        break;
```

**Comment by dscho** [comment]
> OpenSSH bug 2849 has been submitted to describe the difference in behavior.

Thanks. @MarkEWaite would you mind referencing my PR there?

**Comment by dscho** [comment]
@MarkEWaite part of the "fun" running a software project as complex as Git for Windows is that you have to rely on other projects whose world view might be very different from yours. As is the case here. I had no idea how different (and from my perspective, utterly unreasonable) OpenSSH is developed. We pointed out a regression, even showed a reproducer, demonstrated that this causes real problems out here in the real world, and they just closed it as a wont-fix.

Now I am stuck between a rock and a hard place: while I think Damien's decision is stupid and hostile toward users, I cannot undo it. I could, of course, release a stop-gap hotfix, and even promise that Git for Windows' `ssh.exe` would do the sane thing, always, but that just means we would become eternally incompatible to OpenSSH v7.7p1 and later on every platform other than Windows.

So while I want to help you, I also have to maintain this software, as complex it is and as incredibly impossible some other software maintainers make this.

Maybe ping me up on https://gitter.im/git-for-windows/git to discuss how to go from here?

**Comment by MarkEWaite** [comment]
Sorry that I never answered your question @dscho .  I think the best approach is to close this issue.  It won't be fixed because OpenSSH won't fix it.  Thanks so much for your help with it.
