### ISSUE TITLE
Trying to match a particular file in results of status.

### ISSUE THREAD

**Issue by ericus20** [git-for-windows/git#1617]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.16.1.windows.4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Windows 10 64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
ntracked files:
  (use "git add <file>..." to include in what will be committed)

        src/main/java/com/developersboard/lms/web/exceptions/LMSException.java

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\Eric\IdeaProjects\lms>git src/**/**/exceptions/**

 - What did you expect to occur after running these commands?

** insert here **
I was trying to use regex to find the class LMSException.java then discard changes.
First Attempt:
C:\Users\Eric\IdeaProjects\lms>git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/main/java/com/developersboard/lms/web/exceptions/

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\Eric\IdeaProjects\lms>git checkout .

C:\Users\Eric\IdeaProjects\lms>git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/main/java/com/developersboard/lms/web/exceptions/

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\Eric\IdeaProjects\lms>git checkout -- */exceptions/*
error: pathspec '*/exceptions/*' did not match any file(s) known to git.

C:\Users\Eric\IdeaProjects\lms>git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/main/java/com/developersboard/lms/web/exceptions/

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\Eric\IdeaProjects\lms>git src/**/**/exceptions/**
warning: failed to restrict file handles (2)

handle #0: 0000000000000008 (type 2, handle info (1) 7ff8
handle #1: 0000000000000160 (type 2, handle info (1) 1
handle #2: 0000000000000164 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'src/**/**/exceptions/**' is not a git command. See 'git --help'.

C:\Users\Eric\IdeaProjects\lms>git src/**/**/exceptions/**
warning: failed to restrict file handles (2)

handle #0: 0000000000000008 (type 2, handle info (1) 7ff8
handle #1: 0000000000000160 (type 2, handle info (1) 1
handle #2: 0000000000000164 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'src/**/**/exceptions/**' is not a git command. See 'git --help'.

 - What actually happened instead?

** insert here **

Then some weird results which can be found in the top comment.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Hi there. I suspect this is your first bug report with Git for Windows? Please do not leave the placeholders "** insert ... here **" alone, please do take your time to fill them out.

This is important, e.g. in this case the Git version would inform any reader whether you are on v2.17.0, which should have that `warning: failed to restrict file handles (2)` bug fixed already.

> ```
> Untracked files:
> (use "git add ..." to include in what will be committed)
>
>    src/main/java/com/developersboard/lms/web/exceptions/
> ```
>
> I was trying to use regex to find the class LMSException.java then discard changes.

Please note that Git thinks of this file as *untracked*, i.e. there are no changes to discard. Changes are only in files that Git was told to "track", i.e. files that were added at some stage with `git add <file>`, which was not the case here.

In your use case, you do not want to discard changes, but untracked files, for which you need to use the [`git clean` command](https://git-scm.com/docs/git-clean). You probably want to do a dry-run first (because `git clean` is one of those operations which delete data *for good*, you cannot undo them): `git clean -dn`. If the output lists only files you are sure you want to delete, *and only then*, perform the operation for real: `git clean -df`.
