### ISSUE TITLE
Git doesn't wait for editor to close

### ISSUE THREAD

**Issue by vtbassmatt** [git-for-windows/git#1618]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.334]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I have Notepad++ installed using Chocolatey, so I manually edited my .gitconfig to point to *C:/ProgramData/chocolatey/bin/notepad++.exe*.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# on branch dev, having made several commits
git rebase -i master
```
 - What did you expect to occur after running these commands?

Interactive rebase script comes up, while Git waits in the background. I edit the script, close the editor, and Git performs the rebase.

 - What actually happened instead?

The first two times, Notepad++ opened with no file. Git said "Successfully rebased and updated refs/heads/dev." immediately. I ran `git status` and found nothing changed. Now, Git does generate the interactive rebase script and open it, but it still doesn't wait for me to complete it. I can't perform the rebase, since Git thinks there's nothing to do.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repo.

**Comment by vtbassmatt** [comment]
Updated title, as it turns out Git isn't waiting for my editor under any circumstances. I'll work around by going back to vi for now.

**Comment by PhilipOakley** [comment]
Make sure that you have configured the Notepad++ correctly with all the necessary options that keep it open and alive and independent for the operation. A quick search should find them...

**Comment by dscho** [comment]
> I have Notepad++ installed using Chocolatey, so I manually edited my .gitconfig to point to C:/ProgramData/chocolatey/bin/notepad++.exe.

You should see the necessary options in `C:\ProgramData\Git\config`, as the installer sets them correctly. For the record, the options are: ` -multiInst -notabbar -nosession -noPlugin` (see also https://github.com/git-for-windows/build-extra/blob/e826d31f90cfdc98c5ea1f27b8eef93e25cb2971/installer/install.iss#L2113).

**Comment by vtbassmatt** [comment]
Those options didn't fix it.

Relevant portion of my user directory .gitconfig looked like this before I changed it to match the above:

```
[core]
        editor = 'C:/ProgramData/chocolatey/bin/notepad++.exe' -noPlugin -nosession -multiInst
```

Interestingly, my ProgramData config doesn't have an editor configured at all, despite me asking for it at install time.

```
C:\Users\me>more c:\ProgramData\Git\config
[core]
        symlinks = true
        autocrlf = false
        fscache = true
[color]
        diff = auto
        status = auto
        branch = auto
        interactive = true
[help]
        format = html
[rebase]
        autosquash = true
```

**Comment by vtbassmatt** [comment]
In this GIF, you can even see Git give up waiting for the editor before the editor gets a chance to launch.
![giteditor](https://user-images.githubusercontent.com/714283/38373878-433fab3a-38c0-11e8-9245-7f135f99bd2e.gif)

**Comment by vtbassmatt** [comment]
Results:
```
C:\Users\macoope\Projects\test>git commit
15:03:06.169492 git.c:344               trace: built-in: git commit
hint: Waiting for your editor to close the file... 15:03:06.194494 run-command.c:640       trace: run_command: GIT_INDEX_FILE=.git/index ''\''C:/ProgramData/chocolatey/bin/notepad++.exe'\'' -multiInst -notabbar -nosession -noPlugin' C:/Users/macoope/Projects/test/.git/COMMIT_EDITMSG
Aborting commit due to empty commit message.
```

Since this setting is now managed by the installer, I've removed it from my user-profile gitconfig. That seems to have fixed the problem.

However: the gitconfig in the mingw64\etc directory also uses single quotes around the exe and none around the whole thing. I'm pretty sure I didn't set that one myself, as I didn't know about the `-notabbar` setting until this bug thread.
```
[http]
        sslBackend = schannel
[diff "astextplain"]
        textconv = astextplain
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
[credential]
        helper = manager
[core]
        editor = 'C:\\Program Files\\Notepad++\\notepad++.exe' -multiInst -notabbar -nosession -noPlugin
```

I'm wondering if this is an artifact of how Chocolatey installs programs. The exe in ProgramData might be some kind of launcher which exits, tricking Git into thinking the editor is done.

Feel free to close this bug if you don't want to follow up any deeper. I'm unblocked and prefer to have the Git installer manage this setting anyhow :)

**Comment by dscho** [comment]
> The exe in ProgramData might be some kind of launcher which exits, tricking Git into thinking the editor is done.

That might very well be possible... You can test this by calling the full command line interactively in Git Bash (where you would return to the prompt immediately if your hunch is correct).

> I'm unblocked and prefer to have the Git installer manage this setting anyhow :)

Yeah!
