### ISSUE TITLE
"MoveFile failed" when installing over old Git for Windows

### ISSUE THREAD

**Issue by kusma** [git-for-windows/git#162]
Trying to install over an old Git for Windows installation throws this error:

    ---------------------------
    Error
    ---------------------------
    C:\Program Files\Git\etc\package-versions.txt
    
    
    
    An error occurred while trying to rename a file in the destination directory:
    
    MoveFile failed; code 183.
    
    Cannot create a file when that file already exists.
    
    
    
    Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
    ---------------------------
    Abort   Retry   Ignore   
    ---------------------------

**Comment by dscho** [comment]
> C:\Program Files\Git\etc\package-versions.txt

I wager a guess that this is actually a directory in your setup. The funny part is that this directory should have been removed as part of uninstalling the old Git for Windows installation. When I tested this feature, it worked here... :-(

Did you see whether there was an extra window popping up that said that it was "Uninstalling Git", just before extracting the files? Which version did you have installed previously?

**Comment by kusma** [comment]
I didn't see if that happened or not, sorry. I can give it another attempt a bit later and see if it reproduces...

**Comment by dscho** [comment]
Thanks. That would be helpful.

And which Git for Windows was installed at that time?

**Comment by dscho** [comment]
@kusma did you encounter this error again? I have not been able to reproduce it in my tests (and forgot to update this ticket, sorry).

**Comment by kusma** [comment]
I no longer have the system where this issue triggered, so I can't reproduce. Sorry.

**Comment by SamJWeissman** [comment]
Seeing a similar error when trying to update using the Git for Windows installer ( and/or Heroku )...

![cmdfail](https://user-images.githubusercontent.com/7718632/29543700-fd4d59fe-86b0-11e7-8041-22af23737a74.PNG)

I've tried deleting C:\Program Files\Git via rimraf and from File Explorer to no avail.

Any help would be greatly appreciated. Thanks!

**Comment by dscho** [comment]
Something must be using that file, still. Maybe Sysinternals' Handle tool can shed some light into it.

**Comment by SamJWeissman** [comment]
Thanks @dscho!
