### ISSUE TITLE
bash kill builtin doesn't kill windows applications

### ISSUE THREAD

**Issue by ebugusey** [git-for-windows/git#1620]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
(c) Корпорация Майкрософт (Microsoft Corporation), 2013. Все права защищены.
Clink v0.4.8 [git:d565ad] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No, I don't think so.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I tried running this example in Git-Bash and cmd with same results.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
notepad.exe &
kill %1
```
 - What did you expect to occur after running these commands?

notepad is terminated.

 - What actually happened instead?

notepad still running.

### Additional information
I tried running this example in msys2 bash and it works.
```
$ uname -a
MINGW64_NT-6.3 W801W81 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys
```

**Comment by ebugusey** [comment]
Well, you see, in msys2 bash it actually works, but in git-bash doesn't.

**Comment by dscho** [comment]
> Well, you see, in msys2 bash it actually works, but in git-bash doesn't.

Well, you see, I cannot reproduce this, and this terse explanation did not help me to help you even one bit.

**Comment by ebugusey** [comment]
This problem seems to be fixed in current version of git-for-windows.
