### ISSUE TITLE
"git add ." runs ~20 times slower with 2.14.2 and later

### ISSUE THREAD

**Issue by alexhass** [git-for-windows/git#1622]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 64-bit Portable

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4

```

 - Which version of Windows are you running? Windows 7 Enterprise 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

`
git config --system url."https://".insteadOf git://
`
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txtdir

None of these files exists in portable version.

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

- Files on local HDD
- ~3500 files in folders.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add . --verbose
```
 - What did you expect to occur after running these commands?

Very fast display of files output

 - What actually happened instead?

It displays some lines output on screen and scrolls down, than hangs, than outputs something, than hangs again and so on until it finishes.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not public.

This issue started exactly at 2.14.2. There no no version before these that has the issue. We used 2.13 in past without issues. Since we upgraded to 2.16.2 we seen the issue. We also tried 2.17.0, but failed the same. So we tried every build after 2.13 until 2.14.1 and it breaks at build 2.14.2.

As we have no idea how we can help you to identify the bug, we need some suggestions to try out. Sharing the original files / repository is not possible.

Adding the files takes around 20 times longer than before.

**Comment by dscho** [comment]
> Sharing the original files / repository is not possible.

Can you verify that the same happens when you generate a huge repository, e.g. using [`t/perf/repos/many-files.sh`](https://github.com/git-for-windows/git/blob/master/t/perf/repos/many-files.sh)?

**Comment by dscho** [comment]
Oh, and...

> ```
> $ cat /etc/install-options.txt
> [...]
>```
> None of these files exists in portable version.

Is your `core.fscache` enabled in both 2.14.1 and 2.14.2, or off in both?

**Comment by alexhass** [comment]
1. Not sure how I can run .sh scripts on windows.
2. Let me note that we are using your portable releases https://github.com/git-for-windows/git/releases/. Only setting we changed is the `git config --system url."https://".insteadOf git://`. Nothing else. So you can review all the settings in the releases.
3. `git config core.fscache` command returns nothing in both 2.13.0 and 2.17.0. I guess it means "off"?

Here are the config files from your portable version:
[gitconfig.213.txt](https://github.com/git-for-windows/git/files/1894416/gitconfig.213.txt)
[gitconfig.217.txt](https://github.com/git-for-windows/git/files/1894417/gitconfig.217.txt)

**Comment by alexhass** [comment]
> You can run them in Git Bash.

Yeah I tried later... but nothing was generated. Had no time to debug or look why. Just executed your sh script, but in the same folder there have only been a handful of files generated.

> Every setup is different, and throwing back only the system configs included in the installer is not enough. You need to look at the output of git config -l --show-origin.

Here is the output in cmd.exe:
```
\\mingw64/etc/gitconfig" core.symlinks=false
\\mingw64/etc/gitconfig" core.autocrlf=false
\\mingw64/etc/gitconfig" color.diff=auto
\\mingw64/etc/gitconfig" color.status=auto
\\mingw64/etc/gitconfig" color.branch=auto
\\mingw64/etc/gitconfig" color.interactive=true
\\mingw64/etc/gitconfig" pack.packsizelimit=2g
\\mingw64/etc/gitconfig" help.format=html
\\mingw64/etc/gitconfig" http.sslcainfo=/ssl/certs/ca-bundle.crt
\\mingw64/etc/gitconfig" diff.astextplain.textconv=astextplain
\\mingw64/etc/gitconfig" rebase.autosquash=true
\\mingw64/etc/gitconfig" filter.lfs.clean=git-lfs clean -- %f
\\mingw64/etc/gitconfig" filter.lfs.smudge=git-lfs smudge -- %f
\\mingw64/etc/gitconfig" filter.lfs.process=git-lfs filter-process
\\mingw64/etc/gitconfig" filter.lfs.required=true
\\mingw64/etc/gitconfig" credential.helper=manager
\\mingw64/etc/gitconfig" url.https://.insteadof=git://
```

> You could try re-running with GIT_TRACE=1 and/or GIT_TRACE_PERFORMANCE=1.

Sorry for stupid question, but could you just tell me what these variables are for? Are these CMD.exe variables? So I do `set GIT_TRACE=1` and `set GIT_TRACE_PERFORMANCE=1` or do I need to something different? We never debugged git yet...

**Comment by PhilipOakley** [comment]
Have a look at https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables in the debugging section for some examples. e.g.

```
$ GIT_TRACE=true git lga
20:12:49.877982 git.c:554               trace: exec: 'git-lga'
20:12:49.878369 run-command.c:341       trace: run_command: 'git-lga'
20:12:49.879529 git.c:282               trace: alias expansion: lga => 'log' '--graph' '--pretty=oneline' '--abbrev-commit' '--decorate' '--all'
20:12:49.879885 git.c:349               trace: built-in: git 'log' '--graph' '--pretty=oneline' '--abbrev-commit' '--decorate' '--all'
20:12:49.899217 run-command.c:341       trace: run_command: 'less'
20:12:49.899675 run-command.c:192       trace: exec: 'less'
```

i.e. just precede the `git` command with the `GIT_TRACE=1` on the single command line.

GIT_TRACE_PERFORMANCE is a bit further down the page.

HTH.

**Comment by alexhass** [comment]
A test on our internal repro returned below. But I'm not sure how helpful this is...

```
18:10:47.798150 trace.c:420             performance: 0.177822052 s: git command: 'GitPortable\2.17.0\mingw64\bin\git.exe' init
18:10:53.751279 read-cache.c:1889       performance: 0.000301456 s: read cache .git/index
18:10:53.751279 name-hash.c:605         performance: 0.000003226 s: initialize name hash
18:10:53.855281 dir.c:2346              performance: 0.100074279 s: read directory
18:10:53.855281 diff-lib.c:250          performance: 0.000005572 s: diff-files
18:14:10.536619 read-cache.c:2386       performance: 0.004971970 s: write index, changed mask = 8
18:14:10.536619 trace.c:420             performance: **196.815707483** s: git command: 'GitPortable\2.17.0\mingw64\bin\git.exe' add . –v
```

We also found a way to reproduce it with a public repository of https://github.com/ckeditor/ckeditor-releases, so you should be able to reproduce it easily.

`
performance: 134.611304237 s: git command: 'D:\Users\Downloads\git-2.17.0-64bit\mingw64\bin\git.exe' add .
`

**Comment by alexhass** [comment]
Are you on SSD or HDD? 

Note we can repro this on all computers and we only changed the software version of git. I have no idea what has been changed in the version step we noted, but the issue exists and is 100% reproducible. If in question we can do a remote session for debugging.

**Comment by dscho** [comment]
@alexhass have you tried to run [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) while Git is taking so long, and then analyzed the output to see what is the difference between the fast the the slow Git version? I can't do remote session these days, because I am too busy with work.
