### ISSUE TITLE
One branch also shows the changes made in the other one.

### ISSUE THREAD

**Issue by DevNicoT** [git-for-windows/git#1628]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
$ git --version --build-options

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```
NOTE: I started working on 2.16.2 and then upgraded, same result.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.371]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

As expressed above, I also experienced this issue with Git 2.16.2. 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git branch
* master
git checkout -b testing
Switched to a new branch 'testing'
cd src/
touch myawesomefile.js
git status
On branch testing
Untracked files:
(use "git add <file>..." to include in what will be committed)

myawesomefile.js

nothing added to commit but untracked files present (use "git add" to track)

# Now the the weird part comes with the following 2 commands:
git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
(use "git add <file>..." to include in what will be committed)

myawesomefile.js

nothing added to commit but untracked files present (use "git add" to track)

# If I'll make modifications on a file instead of creating a new one, same thing will happen.

```
 - What did you expect to occur after running these commands?

I might be wrong or misunderstanding (in which case, please correct me), but what I expected was that after checking out from the branch where I did the modifications or created the file (in our case from the testing branch) to the one 'untouched'(in our case, the master branch), the latter would ignore the changes made in the former.

 - What actually happened instead?

The changes / files created in one branch are reflected equally in the other branches (I tried up to three branches and same happens.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not really. It's just a little project made with (ejected) CRA.

Just one more thing: I am sincerely no expert at all, but I am willing to work on helping on this, so long as someone with the experience can point me a little in the right direction.
Thanks in advance for your reply, and also for all the work and love put into this fantastic application. :)

**Comment by PhilipOakley** [comment]
@DevNicoT Yes, this is a misunderstanding about how Git works. Because you have a single worktree (directory structure), Git will work behind the scenes to store the tracked/added/committed files into the repository. The untracked files simply stay in the worktree as random noise files. 

When you change branches, you (Git) are swapping out the currently tracked/added/committed files in the current branch, for the ones that Git has in the repository for the requested branch. All those loose files are still there and still untracked.

Obviously Git is careful to ensure that tracked files that have changes are noticed before the branch change, and to notice if there is a file in the new branch that would conflict with a currently untracked file (don't want to overwrite such files without user permission).

So it is normal Git operation. Hope that helps (HTH)

**Comment by PhilipOakley** [comment]
Just do a WIP commit when you have temporary work, either on the tracked or un tracked but precious files (adding their changes obviously). 

Then change branches (clean anything that can go), and work on the new branch, (again do a WIP commit if you need to switch back quickly).

Then after switching back you can amend / reset your old WIP commit to get back on track. It's quick, easy and usually local (almost instant). 

Or you can use a stash to hold those temporary bits of work. YMMV.

The main point is that GIT (and you local environment) should facilitate a save early, save often mentality. Git's there to support YOU, especially your local branches. Make sure you have that space (I'm saying this in case you have some management trying to control you, when they should distribute the control to you... /rant)

**Comment by DevNicoT** [comment]
Well, I'm glad I was so clumsy not to understand you at first, because now I feel I've understood a core principle of how Git works. I've checked and it works exactly as expected according to that principle, namely:
>The main point is that GIT (and you local environment) should facilitate a save early, save often mentality. 
I was already thankful for this fantastic application, but now I am doubly as thankful for your incredible kindness and patience in leading me to see I wasn't facing an actual issue, @PhilipOakley .

One more thing, I am sure I cannot help much with my little experience and knowledge. Still if ever I can be of help in anything for this project, no matter the task, I am just one mention away.
Thank you so much, I'll close this.

**Comment by PhilipOakley** [comment]
> One more thing, I am sure I cannot help much with my little experience and knowledge. Still if ever I can be of help in anything for this project, no matter the task, I am just one mention away.

@DevNicoT Thank you for the offer. Help is always welcome. Even as simple as updating the FAQs or improving the documentation by adding the little tidbits that help new starters get past little misunderstandings are a good place to start (often it's just picking out the gap between what people say and do). 

In general folk are helpful, though when it comes to code, the FB "move fast & break things" is a poor paradigm for version control, so the reviews are more steady and thorough, with efficiency and backward compatibility being important for the core Git. 

Have a look though the outstanding and tagged issues for something your interested in..
