### ISSUE TITLE
cannot execute any commands after executing git log.

### ISSUE THREAD

**Issue by vaibhavagrawal2912** [git-for-windows/git#1629]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

``` 64 bit

$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7, 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue, you're seeing?

No

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git log

 - What did you expect to occur after running these commands?

git should work normally, i.e it should execute any git commands that are entered.

 - What actually happened instead?

git stucks no keyboard input shows response in bash terminal

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repository

**Comment by dscho** [comment]
Did you quit `git log`'s pager using the <kbd>q</kbd> key or <kbd>Ctrl</kbd>+<kbd>C</kbd>? If the latter: don't. The proper way to quit the pager is to hit <kbd>q</kbd>. That should resolve your issue, too.

**Comment by dscho** [comment]
FWIW I will address a part of this issue through resolving https://github.com/git-for-windows/git/issues/1491, but in a way that you probably do not expect: <kbd>Ctrl</kbd>+<kbd>C</kbd> will no longer quit the pager. You *will* have to press <kbd>q</kbd> to quit the pager; pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> will only terminate the Git process feeding the pager.

**Comment by PhilipOakley** [comment]
@vaibhavagrawal2912, As dscho noted, you do need to know that these unix/linux tools such as the pager, will need the special key combinations such as "q" to quit them, and that Ctrl-C means different things in the two (linux/Windows) environments. 

That said, the question is, How/where would you have found that out?

 It's a common problem, so if you are able to suggest how folks should be informed of the conventions, (ideally without annoying those who heve learnt them), that would be useful, as this issue does recur, and I'm always seeking ways of reducing these frictions.

Any suggestions would be considered.
