### ISSUE TITLE
git mergetool: line 291: diff: command not found

### ISSUE THREAD

**Issue by calle2010** [git-for-windows/git#163]
Found in: PortableGit-2.4.2.1-release-candidate-64-bit.7z.exe

During execution of `git mergetool` I got this output:

    Normal merge conflict for 'src/main/java
       {local}: created file
       {remote}: created file
    /mingw64/libexec/git-core/git-sh-setup: line 291: diff: command not found
    fatal: unrecognized input

Indeed there is no diff command on the path.

In msysGit 1.9.5-preview20150319 diff and patch are included.

Thanks!
Christian.

**Comment by dscho** [comment]
Could you please provide a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve)? This would make it much practicable to verify a fix.

**Comment by dscho** [comment]
@calle2010 if you cannot quickly come up with an MCVE, please feel free to install [the Git SDK](https://git-for-windows.github.io/#download-sdk) and test https://github.com/git-for-windows/build-extra/pull/61 by calling

```sh
cd /usr/src/build-extra
git fetch origin refs/pull/61/head
git checkout -b diff FETCH_HEAD
./portable/relase.sh 2.4.2.1-calle2010
```

and then testing the resulting PortableGit installer.

**Comment by dscho** [comment]
@calle2010 please note that after I merged the Pull Request, you have to call

```sh
cd /usr/src/build-extra
git fetch origin
git checkout master
./portable release.sh 2.4.2.1-calle2010
```

instead. Please test.

**Comment by calle2010** [comment]
Thank you for the fast reaction. I will replicate the issue and test tomorrow,

**Comment by calle2010** [comment]
How to replicate the issue (new repository or file test163 must not exist):

    git checkout -b test163 master
    echo y > test163
    git add test163
    git commit -am "test163"
    git checkout master
    echo z > test163
    git add test163
    git commit -am "test163 conflict"
    git merge test163
    git mergetool

This creates a conflict where no 3-way-merge is possible and triggers the error on `git mergetool`.

Now I will install the SDK to test the fix.

**Comment by calle2010** [comment]
The original error message is fixed. But something else happens:

    Normal merge conflict for 'test163':
      {local}: created file
      {remote}: created file
    <stdin>:5: trailing whitespace.
    y
    fatal: invalid path './test163_BASE_12928'

I'm not sure where this is coming from. I use p4merge as merge tool. The BASE file is created and seemingly used by p4merge.

**Comment by calle2010** [comment]
The latest msysGit also doesn't work perfect in this test case (again with p4merge):

    <stdin>:5: trailing whitespace.
    y
    error: patch failed: ./test163.BASE.23072:1
    error: ./test163.BASE.23072: patch does not apply
    expr: non-numeric argument

Difference here is that p4merge shows an empty base file.

**Comment by calle2010** [comment]
I just tried the same with vimdiff and there is no error message. It must be an issue with my p4merge setup.

The original problem, though, occured also with vimdiff and has been fixed with your change.

Thank you!

**Comment by dscho** [comment]
@calle2010 Thanks for clarifying!

I cannot promise anything, but maybe you want to open a new ticket specifically for the p4 issue? I have no license for Perforce, so I am afraid I can only assist with that issue.

**Comment by calle2010** [comment]
I'm analyzing the issue currently. It boils down to a problem in create_virtual_base where git apply doesn't accept paths with ./ anymore since January. But even if I remove the path prefix or use --unsafe-paths the patch generated by diff doesn't apply (similar as in msysGit 1.9.5 above). I will continue investigate and open a new issue with my findings.
