### ISSUE TITLE
warning: failed to restrict file handles (2)

### ISSUE THREAD

**Issue by msgirlperl** [git-for-windows/git#1632]
** Note: this was due to omitting the 'clone' keyword **  
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10
64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.371]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The parent directory of the folder I ran this command in has a sibling that already has the same repository
I just cloned the same repository one directory up
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
>git https://github.com/StephenGrider/ReduxSimpleStarter.git

 - What did you expect to occur after running these commands?

 - What actually happened instead?
>git https://github.com/StephenGrider/ReduxSimpleStarter.git
warning: failed to restrict file handles (2)

handle #0: 0000000000000054 (type 2, handle info (1) 0
handle #1: 000000000000014c (type 2, handle info (1) 1
handle #2: 0000000000000150 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'https://github.com/StephenGrider/ReduxSimpleStarter.git' is not a git command. See 'git --help'.


 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

github.com/StephenGrider/ReduxSimpleStarter.git #

**Comment by PhilipOakley** [comment]
Thanks. This is the same issues as reported in some of the other issues. It's now fixed in the latest build.

Suggest getting the latest build.

Philip

**Comment by dscho** [comment]
Indeed, this is fixed in v2.17.0. Thank you for being diligent and reporting it @msgirlperl!

**Comment by msgirlperl** [comment]
Yup - I figured that out after.  I hadn't been in the bugs before so didn't
know my way around yet.  Sorry!

**Comment by dscho** [comment]
No worries!
