### ISSUE TITLE
Trying to download ova for Openstack Administrator Exam on windows

### ISSUE THREAD

**Issue by bshahhome** [git-for-windows/git#1633]
trying to git clone https://github.com/PacktPublishing/Preparing-for-the-Certified-Openstack-Administrator-Exam

errors on the coa-aio-newton.ova

warning: failed to restrict file handles (87)

handle #0: 000000000000000c (type 2, handle info (1) 1d3c928
handle #1: 0000000000000234 (type 3, handle info (1) 1
handle #2: 0000000000000013 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

Any advice

**Comment by dscho** [comment]
> Also, what do we need to do to help guide folk to fill in the reporting template and how to search the issues pages (inc. for fixed issues) ?

@PhilipOakley I give up ;-)

Seriously again: bug reports where the template is simply tossed away always imply to me that I can be lazy, too ;-) It is quite frustrating to me, of course, as I *want* to help, and I am fed so little, almost as if I had to come back begging for more details. When it is not me who should do the asking (I am the expert whose help is sought, after all, so a little more diligence would be perceived by me as a polite thing).
