### ISSUE TITLE
git status crash on Windows 10

### ISSUE THREAD

**Issue by kstallard** [git-for-windows/git#1635]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

When using git status using the Bash shell in Windows, it gives the error "segmentation fault".  
When SourceTree is using git (either 2.15 or 2.16) a dialogue box with the message:

'git status' failed with code -1073741819

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
This is the version I ran from Bash:
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

This is the version that SourceTree (version 2.4.8.0) was using:
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86


```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.16299.371]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Nano
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
No, it has been working great until this weekend

```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
Bash

```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status

```
 - What did you expect to occur after running these commands?

```
To receive the status of the files in the directory.

```
 - What actually happened instead?

```
Segmentation Fault

```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

```
The server is internal to a private company (one of my clients).  I can't give out access.  But it happens with all of the repos on the server.

```
![screen shot 2018-04-16 at 11 38 53 am](https://user-images.githubusercontent.com/5996043/38826051-e256d4b0-416b-11e8-8977-a90a377dd4f1.png)

**Comment by kstallard** [comment]
I should add that I have also researched this error code (1073741819) and have tried to resolve it without success.  Most of the issues were related to corrupt files  on the file system or permission settings.  However, I was unable to resolve this with the suggestions I received.

If git is not doing a status, it appears to run fine.

**Comment by dscho** [comment]
This message box is not generated by Git. Can you run `git status` in the terminal? Does it affect really only *that* worktree, or others, too? If it is specific to that worktree, can you try to wittle things down a little, maybe try to anonymize with `git fast-export --anonymize` and see whether the problem occurs also in a fast-imported version of that anonymized dump?

I really need you to come up with a reproducer, otherwise it will be too open-ended a chase for me to find time to hunt down this bug.

**Comment by kstallard** [comment]
Thanks Johannes,

I understand the need to chase done a reproducible case.  I didn't really
know where to start, I am still pretty green when it comes to the command
line version of git.

'git status crashes' in the terminal (segmentation fault).

I will try this on an anonymized version.

Do you have any other suggestions?  I would love to get a stack dump, but
not sure how to create a build that would produce one.

Thanks
Kevin

**Comment by dscho** [comment]
> I would love to get a stack dump, but not sure how to create a build that would produce one.

If you know your way around GDB, it is really easy:

- install the [Git for WIndows SDK ](https://gitforwindows.org/#download-sdk) (caveat: downloads 500MB worth of Git objects)
- run `git-bash.exe`
- inside that Git Bash, call `sdk build git`
- now run the built git in GDB: `cd /path/to/your/repository && gdb -args /usr/src/git/git.exe status`

Even if you do not know your way around GDB, here is a starter

- run the command with `r`
- print a stack trace with `bt`
- jump up and down the stack frames with `up` and `down`
- inspect a variable with `p <name>`
- quit GDB with `q`

You may want to recompile after removing the `-O2` from the `CFLAGS` in `/usr/src/git/Makefile`; in my hands, that makes things a lot easier in GDB (as it does not complain about "optimized-out" variables, and single-stepping is also more accurate).

**Comment by dscho** [comment]
Let's just close this ticket, it has become quite stale by now.
