### ISSUE TITLE
slow tab completion on git bash

### ISSUE THREAD

**Issue by mef** [git-for-windows/git#1636]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.16299.15]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

1. %HOME% is located in a network drive.
2. Two non-existing directories were removed from PATH variable:
    * removed `/usr/local/bin` from PATH in /etc/profile
    * commented out the following line inside `env.sh` ([source](https://stackoverflow.com/a/6997771))
````
export PATH="$HOME/bin:$PATH"
````

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

type the following, from any directory in git bash:
```
git stat
```
Then press <kbd>Tab</kbd> key

 - What did you expect to occur after running these commands?

Auto-completed `git status` is displayed quasi-instantly

 - What actually happened instead?

Between two and three seconds are needed for the auto-completion to happen.

This happens only with git commands. Other commands and completion of file paths have a good performance.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not applicable. problem is global, independent of repository size, or from the presence/absence of a repository in the directory in question.

**Comment by siprbaum** [comment]
My guess is that it is related to having your HOME on a network share, because git will try to read your .gitconfig from there for every git command executed.
Try if it is faster if your HOME is set to a local path before starting the git bash

**Comment by dscho** [comment]
You could also try to call `export GIT_TRACE_PERFORMANCE=1` before trying to tab-complete again. Maybe the output tells you something.

**Comment by mef** [comment]
Thanks for the suggestions

> Try if it is faster if your HOME is set to a local path before starting the git bash

I did this by adding `HOME=/c/Users/my-username/` inside the `profile` file, it didn't make the completion faster.

> You could also try to call export GIT_TRACE_PERFORMANCE=1 before trying to tab-complete again

This doesn't seem to be outputting anything related to the tab completion, the trace line is shown after the command is actually sent.

    10:25:42.102237 trace.c:417             performance: 0.004490167 s: git command: 'C:\Program Files\Git\mingw64\bin\git.exe' 'status'

**Comment by dscho** [comment]
You're right, its output is swallowed, probably redirected to `/dev/null`. Try this instead:

```sh
export GIT_TRACE_PERFORMANCE=$PWD/tab-completion.log
```

After even one tab completion, the `tab-completion.log` file should exist in your current directory, and its contents should be able to enlighten you a bit about what is happening that makes things slow on your side.

**Comment by mef** [comment]
Thanks. Here is the content of tab-completion.log, after typing `git chec`, <kbd>Tab</kbd>, then <kbd>Enter</kbd> after the completion was displayed:

````
14:06:24.766369 trace.c:417             performance: 0.005579762 s: git command: 'C:\Program Files\Git\mingw64\bin\git.exe' 'rev-parse' '--git-dir' '--is-inside-git-dir' '--is-bare-repository' '--is-inside-work-tree' '--short' 'HEAD'
14:06:28.119714 trace.c:417             performance: 0.297177029 s: git command: 'C:\Program Files\Git\mingw64\bin\git.exe' 'help' '-a'
14:06:28.888935 trace.c:417             performance: 0.007873085 s: git command: 'C:\Program Files\Git\mingw64\bin\git.exe' 'config' '--name-only' '--get-regexp' '^alias\..*'
14:06:30.398001 trace.c:417             performance: 0.005833070 s: git command: 'C:\Program Files\Git\mingw64\bin\git.exe' 'checkout'
14:06:30.781193 trace.c:417             performance: 0.005572373 s: git command: 'C:\Program Files\Git\mingw64\bin\git.exe' 'rev-parse' '--git-dir' '--is-inside-git-dir' '--is-bare-repository' '--is-inside-work-tree' '--short' 'HEAD'
14:06:38.522944 trace.c:417             performance: 0.005346571 s: git command: 'C:\Program Files\Git\mingw64\bin\git.exe' 'rev-parse' '--git-dir' '--is-inside-git-dir' '--is-bare-repository' '--is-inside-work-tree' '--short' 'HEAD'
````

**Comment by dscho** [comment]
You don't really need me to read this log, but it seems something slows things down between Git calls. Over-eager anti-malware, perhaps?

**Comment by mef** [comment]
Thanks.
There is a realtime malware protection active indeed, I just asked my sysadmin to whitelist git, will see...

**Comment by dscho** [comment]
FWIW we already code-sign `git.exe` to help anti-malware to figure out that it has already validated it, and be a lot nicer afterwards. If you find out what malware protection software it is, and how it would be helped by changes on Git for Windows' side, please do let us know. Or even open a PR ;-)

**Comment by mef** [comment]
Thanks.

sysadmin whitelisted git, it seems to be faster, much better experience than previously. The tab-completion is not as fast as on linux though, this might be caused by the fact that `$HOME` is on network mount. Not a big deal anymore anyway.

The anti-malware is "TRENDMICRO OfficeScan realtime protection". I have no idea about how to proceed regarding "code-signing"

**Comment by dscho** [comment]
Thanks for the detailed account. I agree: there is little to nothing that we can do here.
