### ISSUE TITLE
git commit bug

### ISSUE THREAD

**Issue by hilarious23** [git-for-windows/git#1638]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.16299.371]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
git commit

 - What did you expect to occur after running these commands?

** insert here **
git commit insert 

 - What actually happened instead?

** insert here **
stop CMD, and then CMD became black (delete its history)

so I did the same thing.(git status→git add .→git commit
the response is below
"hint: Waiting for your editor to close the file...       1 [main] vim 15056 C:\Program Files\Git\usr\bin\vim.exe: *** fatal error - cmalloc would have returned NULL
 195250 [main] vim 15056 cygwin_exception::open_stackdumpfile: Dumping stack trace to vim.exe.stackdump
Aborting commit due to empty commit message."

And again, git commit.
"hint: Waiting for your editor to close the file...       0 [main] vim 8264 C:\Program Files\Git\usr\bin\vim.exe: *** fatal error - cmalloc would have returned NULL
   1467 [main] vim 8264 cygwin_exception::open_stackdumpfile: Dumping stack trace to vim.exe.stackdump
Aborting commit due to empty commit message."

then, git status. In addition to same sentense as last time, new sentence came up
"Untracked files:
  (use "git add <file>..." to include in what will be committed)

then, git add.
"arning: LF will be replaced by CRLF in vim.exe.stackdump.
The file will have its original line endings in your working directory.
"

then git commit,
"
hint: Waiting for your editor to close the file...       0 [main] vim 20888 C:\Program Files\Git\usr\bin\vim.exe: *** fatal error - cmalloc would have returned NULL
   1471 [main] vim 20888 cygwin_exception::open_stackdumpfile: Dumping stack trace to vim.exe.stackdump
Aborting commit due to empty commit message.
"

again git status,
" vim.exe.stackdump" is added to change to to be committed.

then git add .→git commit
"
hint: Waiting for your editor to close the file...       0 [main] vim 10740 C:\Program Files\Git\usr\bin\vim.exe: *** fatal error - cmalloc would have returned NULL
   1016 [main] vim 10740 cygwin_exception::open_stackdumpfile: Dumping stack trace to vim.exe.stackdump
Aborting commit due to empty commit message.
"

I google about this, and I put this
$ git config --global core.editor "/usr/bin/vim"

and then, git commit, it saied
"
hint: Waiting for your editor to close the file... warning: failed to restrict file handles (2)

handle #0: 000000000000004c (type 2, handle info (1) 0
handle #1: 000000000000015c (type 2, handle info (1) 1
handle #2: 0000000000000160 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn /usr/bin/vim: No such file or directory
error: unable to start editor '/usr/bin/vim'
Please supply the message using either -m or -F option.
"

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **
https://github.com/hilarious23/Frever

**Comment by PhilipOakley** [comment]
Yep, that version contained this bug (as reported by many), so there is a newer version that fixes it https://github.com/git-for-windows/git/releases (and contains many other git upstreem developments and improvements - have a look ;-)

**Comment by hilarious23** [comment]
@PhilipOakley  Thank you for comment.

actually, still not solved.

When I put $git commit,
CMD returns
"
hint: Waiting for your editor to close the file... error: cannot spawn /usr/bin/vim: No such file or directory
error: unable to start editor '/usr/bin/vim'
Please supply the message using either -m or -F option.
"

I already I updated git. $git --version --build-options
the response is below.
"
git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
"

Can you tell me how to fix this?
Thanks in advance.

**Comment by dscho** [comment]
> 1 [main] vim 15056 C:\Program Files\Git\usr\bin\vim.exe: *** fatal error - cmalloc would have returned NULL

I did see this before, but it usually goes away with a reboot, which makes it kinda hard to debug for me...
