### ISSUE TITLE
Error connecting to agent: Bad file descriptor

### ISSUE THREAD

**Issue by markfaine** [git-for-windows/git#1639]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

I've tried both 32 bit and 64bit version 2.1.7 

```
$ git --version --build-options

** git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
 GPG4Win 2.2.6
~/.bashrc:

export GPG_AUTH_SOCK=$HOME/AppData/Roaming/gnupg/S.gpg-agent
export SSH_AUTH_SOCK=$HOME/AppData/Roaming/gnupg/S.gpg-agent.ssh
export GPG_AGENT_PID=$$
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
Git Bash 
```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh-add -l
ssh-add -L
```
 - What did you expect to occur after running these commands?

```
ssh-add -L 
Lists public key parameters of all identities currently represented by the agent, which in this case is gpg-agent from Gpg4Win version 2.2.6 
```

 - What actually happened instead?
```
Error connecting to agent: Bad file descriptor  
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

```
Not repository specific 
```

**Comment by markfaine** [comment]
To be clear, I'm attempting to use gpg-agent as an ssh-agent and in place of ssh-agent.   gpg-agent is running, however, ssh cannot read the socket.

**Comment by dscho** [comment]
GPG and SSH are fundamentally different things. I have no idea how the GPG agent is supposed to do the job of the SSH agent! And I would be starkly surprised if it ever did, or ever would.

Also, Git for Windows does *not* ship with a GPG agent. So in order to use any GPG agent you might have somewhere, you would have to make sure that GPG's idea of a Unix socket (which is emulated on Windows, as native support for Unix sockets has not hit any non-Insiders version of Windows so far) matches SSH's idea of a Unix socket.

Do you have any documentation showing that the GPG agent should be able to serve in place of the SSH agent? If so, please do show me.

**Comment by markfaine** [comment]
See: https://linux.die.net/man/1/gpg-agent

--enable-ssh-support

-Mark

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dscho** [comment]
Okay, so you want to use an obscure flag of the GPG agent?

My, my, you sure try to make your Git for Windows' maintainer's life difficult, don't ya.

**Comment by dscho** [comment]
> --enable-ssh-support

Just to make sure that you understand my comment: this was the *first* time you hinted at using that flag. And by trying to be a power user, the onus of making things work kind of fall back on you.

**Comment by markfaine** [comment]
You don't have to be a jerk.  You know you could have said "I don't want to do that".   You'd still be a jerk you just wouldn't have wasted as much of my time.  As for that being an obscure flag, there are no flags that I know about that you shouldn't have known about first.  I'll just close the issue since you obviously can't be bothered.

**Comment by dscho** [comment]
Thanks, @sentiment-bot. I agree. I'll lock this conversation because it got too unpleasant.
