### ISSUE TITLE
Unable to checkout files from git. Few files remains uncheckout after clone.

### ISSUE THREAD

**Issue by bimalkjha** [git-for-windows/git#1641]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git version 2.16.1.windows.4 , Windows Server 2008 R2 Standard, 64-bit.
```
$ git --version --build-options

D:\>git --version --build-options
git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
D:\>

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows Server 2008 R2 Standard, 64-bit.
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Yes.
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

D:\>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

D:\>
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

After cloning, my git repository size is 21GB. We are using ssh to clone the repo as
 https download fails. After cloning the repo few files remains uncheckout. When
 trying to checkout them, get errors.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
D:\db2>git checkout test/fvt/standalone/tools/utm/2.1.1.0/plugins
warning: failed to restrict file handles (87)

handle #0: 000000000000000c (type 2, handle info (1) 1d3a6fd
handle #1: 0000000000000244 (type 3, handle info (1) 1
handle #2: 0000000000000013 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

Encountered 23 file(s) that should have been pointers, but weren't:
        test/fvt/standalone/tools/utm/2.1.1.0/plugins/com.ibm.utm.biginsights_1.
0.0.201603162059.jar
        test/fvt/standalone/tools/utm/2.1.1.0/plugins/com.ibm.utm.core_1.0.0.201
603162059.jar
```
 - What did you expect to occur after running these commands?

It should not throw error and checkout the files but after the command, no change 
 in state. git status still shows these files as uncheckout.

 - What actually happened instead?

D:\db2>git checkout test/fvt/standalone/tools/utm/2.1.1.0/plugins
warning: failed to restrict file handles (87)

handle #0: 000000000000000c (type 2, handle info (1) 1d3a6fd
handle #1: 0000000000000244 (type 3, handle info (1) 1
handle #2: 0000000000000013 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**https://github.ibm.com/DB2/db2 **

**Comment by dscho** [comment]
> Encountered 23 file(s) that should have been pointers

By "pointers", do you mean "symbolic links"? If so, are you sure that you have permission to create symbolic links? You are on Windows 7 if I read that correctly, where https://github.com/git-for-windows/git/wiki/Symbolic-Links applies.

> https://github.ibm.com/DB2/db2

I seem to have no access to that.

**Comment by bimalkjha** [comment]
@dscho Thanks for the reply. Yes, we have symbolic links uploaded on github from linuxamd64 platform. This repo is hosting C++ code that gets cloned and compiled on multiple platforms.
My platform is Windows 7 and I have installed git with create symbolic link permission. Thanks.

**Comment by bimalkjha** [comment]
Note that many other symbolic links get checkedout properly without any issue. Few links only have issues. thanks.

**Comment by dscho** [comment]
@bimalkjha as you *still* have not provided me with any reproducer (I still cannot access that repository you mentioned, and you did not try to come up with something publicly accessible that shares the problem), there is pretty much nothing I can do to help more.

**Comment by drizzd** [comment]
I remember error messages like `Encountered 23 file(s) that should have been pointers, but weren't` coming from Git LFS. Are you using Git LFS?

In my experience, and also according to [this comment](https://github.com/git-lfs/git-lfs/issues/1939#issuecomment-279835210):

> The problem is that you have a file that should be using LFS (according to a pattern in .gitattributes), but it isn't.

This can happen very easily when making changes to a repository which uses Git LFS (which is one of many reasons why I hope that Git LFS will be superseded by virtual file systems like GVFS). In particular, a symblic link will frequently share a file extension with the file it links to, and if LFS files are matched by their extension, it will therefore also match the corresponding LFS pattern. I am not sure what LFS does to symbolic links, but we should keep this detail in mind.

It may simply be a follow-up effect of the first error `warning: failed to restrict file handles (87)`, but if you are using LFS, please uninstall it (please check that the filters and hooks are removed from ~/.gitconfig, .git/config, and .git/hooks), and test again to rule out an LFS issue.

In any case, if you can provide them, it would be interesting to see the results of the following commands (a successful checkout of the work tree is not necessary for these to work):
- `git ls-tree HEAD:test/fvt/standalone/tools/utm/2.1.1.0/plugins`
- `git cat-file blob HEAD:test/fvt/standalone/tools/utm/2.1.1.0/plugins/com.ibm.utm.biginsights_1.
0.0.201603162059.jar`

If the file is committed correctly as a symlink, the expected output would be the following for `ls-tree`, and the link target for `cat-file`.

```
120000 blob 7131efe38c65fd98fd18fe4a0d5a25a792b0fd72    test/fvt/standalone/tools/utm/2.1.1.0/plugins/com.ibm.utm.biginsights_1.
0.0.201603162059.jar
```
