### ISSUE TITLE
warning: failed to restrict file handles (2)

### ISSUE THREAD

**Issue by liuyujun** [git-for-windows/git#1644]
$ git capi/
warning: failed to restrict file handles (2)

handle #0: 0000000000000003 (type 2, handle info (1) 0
handle #1: 0000000000000013 (type 2, handle info (1) 1
handle #2: 0000000000000017 (type 2, handle info (1) 1

**Comment by PhilipOakley** [comment]
This is unfortunately a known bug in the previous version of Git for Windows. You will see many reports in the [open/closed issues list](https://github.com/git-for-windows/git/issues?utf8=%E2%9C%93&q=file+handles). There is a [newer release](https://github.com/git-for-windows/git/releases/). Please upgrade.
