### ISSUE TITLE
"safecrlf false" not working since last update

### ISSUE THREAD

**Issue by Thex-PiedDroit** [git-for-windows/git#1647]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.371]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global core.autocrlf true
git config --global core.safecrlf false
git gui
```
 - What did you expect to occur after running these commands?

When staging .meta files from unity (for example), no warning about CRLF conversion should appear.

 - What actually happened instead?

Warnings do appear all the time and are very annoying.

**Comment by PhilipOakley** [comment]
1. What was your previous version? The https://github.com/git/git/tree/master/Documentation/RelNotes may indicate if there have been updates in this region. (https://github.com/git/git/commit/8462ff43e4)

2. Do you have the attributes set for those files?

3. If colleagues/co-workers still have the previous version available (or use the portable Git), then could you try to create a short minimal script that demonstraes/repeats the fault for the coresponding versions. 

4. Can you shows the output?

5. Consider renormalising maybe, just in case there are issues within the codebase, especially if you are exchang files with those on *nix..

There continues to be on-going development upstream in this area to cover all the corner cases.

**Comment by Thex-PiedDroit** [comment]
1. I'm not sure. I keep it always up to date so i suppose the very previous one (2.16.3)

2. I'm not sure either, i don't really know what attributes are tbh. All i know is that i previously simply had to set core.safecrlf to false and it worked fine.

3. I do have a colleague with version 2.16.1. I had him test it with that version, version 2.16.3 and 2.17.0, and it failed at 2.17.0. To recreate, i simply created a small text file with LF end of lines and tried to stage it. With version 2.17.0, it always triggers the warning even though the safecrlf is set to false.
Also, this happened to me on two different repositories (one of which had been created after upgrading git bash) and on different computers.

4.
[https://cdn.discordapp.com/attachments/406548791374905349/437733051053768704/unknown.png](url)

5. I'm sorry i don't know what normalizing is in this context, nor what *nix is ^^'

**Comment by dscho** [comment]
There has been at least one bug fix in this area. Could you see whether v2.19.0-rc0(2) fixes your issue?
