### ISSUE TITLE
'Git <dir name>' has unnecessary error message 

### ISSUE THREAD

**Issue by EricTalv** [git-for-windows/git#1652]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

`64-bit`

```
$ git --version --build-options

 git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

 Microsoft Windows 
    Version 1607 (OS Build 14393.2125) 

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
`
 Git Bash `

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)

 1.` git <an existing random dir name>`

 - What did you expect to occur after running these commands?

  `git:  '<dir name> is not a git command. See 'git --help'. `

 - What actually happened instead?

```
 warning: failed to restrict file handles (2)

handle #0: 00000000000003a4 (type 3, handle info (1) 0
handle #1: 00000000000003a8 (type 3, handle info (1) 1

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: '<dir name>' is not a git command. See 'git --help'.

```

**Comment by dscho** [comment]
Please upgrade, this has been fixed in v2.17.0.
