### ISSUE TITLE
Maria DB mysql interface doesn't work good in git bash

### ISSUE THREAD

**Issue by tschallacka** [git-for-windows/git#1654]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I have maria DB installed on my system. I had forgotten my root password and tried to login.
So I browsed to C:\Program Files\MariaDB\bin with git bash and typed ./mysql.exe -u=root -p and expected a password prompt.
This however didn't happen, the line stayed blank as if nothing happend. I tried typing some things hitting enter but everything stayed black.
Hitting CTRL + C resulted in returning to prompt with some of the commands I had typed to try to execute as commands.

Then i tried with the password ./mysql.exe -u=root --password=mypassword and again a blank line.
I tried to type select 1; to test, but nothing happened.
I then typed lkajs;dflkjalk and mysql showed some output and exited to prompt.
This led me to try it in cmd and it works there.

Is there  a way to make git bash more compatible with mariadb/mysql output? Or should I just use git cmd for that. I rather keep working in git bash, but if there's no real solution to this, then I'll just have to use git cmd.

### Setup

git version 2.6.2.windows.1 64 bit

```
$ git --version --build-options
git version 2.6.2.windows.1

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windows 7 64 bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash mintty

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
./mysql.exe -u=root -p

```
 - What did you expect to occur after running these commands?

A password prompt for the root password

 - What actually happened instead?

Unresponsive just a blank line, nothing happening.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Maria DB

**Comment by siprbaum** [comment]
Your git version is quite ancient, pls update it to at least 2.17.0 and try if it is still an issue.

**Comment by dscho** [comment]
Is this issue maybe covered by this [known issue](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues)?

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

**Comment by vgarciadez** [comment]
Jd20352 court appeals records..20%pops in search browser and a lot of .dll.w hat about start over with DC's install again

**Comment by vgarciadez** [comment]
Computer started over with username password to start

**Comment by vgarciadez** [comment]
I'm thinking this outside .or where would I insert this.for hire.help to handle .make .takeover.(for the people and children.)of what's mine.fr doc #2018-09721.i trust you all plz help us.your call.

**Comment by vgarciadez** [comment]
That wasn't my call .due to altering

**Comment by dscho** [comment]
It would have been nice to at least hear *something* back.
