### ISSUE TITLE
File handle bug when trying to clone a repository.

### ISSUE THREAD

**Issue by tsheilds7** [git-for-windows/git#1658]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64 bit
$ git --version --build-options

** insert your machine's response here **

warning: failed to restrict file handles (2)

handle #0: 0000000000000044 (type 2, handle info (1) 0
handle #1: 0000000000000154 (type 2, handle info (1) 1
handle #2: 0000000000000158 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'clonehttps://github.com/fadyosman/godot-menu.git' is not a git command. See 'git --help'.
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64 Bit
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Default 

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

C:\Program Files\Git\etc\install-options.txt"

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No not anything out of the ordinary. I've cloned a lot of repositories throughout this past week.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

From the CMD line

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

C:\Godot>git clonehttps://github.com/fadyosman/godot-menu.git

 - What did you expect to occur after running these commands?

Was just trying to glone the repository

 - What actually happened instead?

The file handle bug popped up

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/fadyosman/godot-menu

**Comment by PhilipOakley** [comment]
Thanks for the report. Unfortunately the previous release did have that bug. The new release fixes that. All releases available at https://github.com/git-for-windows/git/releases/ or https://gitforwindows.org/
