### ISSUE TITLE
ssh fails with STATUS_DLL_INIT_FAILED in Windows Container

### ISSUE THREAD

**Issue by esman** [git-for-windows/git#1659]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
MinGit-2.17.0-busybox-64-bit

```
$ git --version --build-options
git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
c:\>type C:\MinGit\etc\install-options.txt
The system cannot find the file specified.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Running inside Windows Docker container
```
c:\>docker info
...
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
...
Debug Mode (client): false
Debug Mode (server): true
...
Experimental: false
...

c:\>docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Dockerfile:
```
FROM microsoft/windowsservercore:10.0.14393.2189

SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
Invoke-WebRequest -Uri 'https://github.com/git-for-windows/git/releases/download/v2.17.0.windows.1/MinGit-2.17.0-busybox-64-bit.zip' -OutFile MinGit.zip; \
Expand-Archive c:\MinGit.zip -DestinationPath c:\MinGit
```
Build and run docker image:
```
docker build -t git .
docker run -it git
```
Run command from interactive shell:
```
c:\>C:\MinGit\usr\bin\ssh.exe -V

c:\>echo %errorLevel%
-1073741502
```
 - What did you expect to occur after running these commands?

See ssh version provided with MinGit

 - What actually happened instead?

Command exited with no message. Exit status is -1073741502 (STATUS_DLL_INIT_FAILED)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No

**Comment by jsmouret** [comment]
It seems to be the same for any tools.

I tried reporting it there with no luck: https://github.com/docker/for-win/issues/1351

**Comment by esman** [comment]
@jsmouret Yes, looks like the same fault.

It must be environmental issue for git-for-windows, because the same binaries work perfectly on my Windows 10 PC.

I've collected some reports using Ger-Eventlog from PowerShell:
<details><summary>Crash report</summary>
<p>

```
PS C:\MinGit\usr\bin> Get-EventLog -Index 25,26,27 -LogName "Application"  | Format-List -Property *


EventID            : 1001
MachineName        : d28bdb6a4faf
Data               : {}
Index              : 27
Category           : (0)
CategoryNumber     : 0
EntryType          : Information
Message            : Fault bucket 2032554342579141560, type 4
                     Event Name: APPCRASH
                     Response: Not available
                     Cab Id: 1943186860421332568

                     Problem signature:
                     P1: ssh.exe
                     P2: 0.0.0.0
                     P3: 00000000
                     P4: msys-2.0.dll
                     P5: 2010.0.0.0
                     P6: 5aaae1ba
                     P7: c0000005
                     P8: 0000000000117265
                     P9:
                     P10:

                     Attached files:
                     \\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\WER2F97.tmp.appcompat.txt
                     \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER393D.tmp.WERInternalMetadata.xml
                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ssh.exe_5d978b72d8bd7fe8a9c7f8cbfdfda8fd8a16e2_dd951e55_cab_06914030\memory.hdmp
                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ssh.exe_5d978b72d8bd7fe8a9c7f8cbfdfda8fd8a16e2_dd951e55_cab_06914030\triagedump.dmp
                     \\?\C:\Windows\Temp\WER4532.tmp.csv
                     \\?\C:\Windows\Temp\WER4533.tmp.txt

                     These files may be available here:
                     C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ssh.exe_5d978b72d8bd7fe8a9c7f8cbfdfda8fd8a16e2_dd951e55_cab_06e1461c

                     Analysis symbol:
                     Rechecking for solution: 0
                     Report Id: 4d3f193e-728e-441d-b768-5df51db52821
                     Report Status: 8
                     Hashed bucket: c992c62e789601aa5c351567d81b7bb8
Source             : Windows Error Reporting
ReplacementStrings : {2032554342579141560, 4, APPCRASH, Not available...}
InstanceId         : 1001
TimeGenerated      : 5/3/2018 11:35:58 AM
TimeWritten        : 5/3/2018 11:35:58 AM
UserName           :
Site               :
Container          :

EventID            : 1001
MachineName        : d28bdb6a4faf
Data               : {}
Index              : 26
Category           : (0)
CategoryNumber     : 0
EntryType          : Information
Message            : Fault bucket , type 0
                     Event Name: APPCRASH
                     Response: Not available
                     Cab Id: 0

                     Problem signature:
                     P1: ssh.exe
                     P2: 0.0.0.0
                     P3: 00000000
                     P4: msys-2.0.dll
                     P5: 2010.0.0.0
                     P6: 5aaae1ba
                     P7: c0000005
                     P8: 0000000000117265
                     P9:
                     P10:

                     Attached files:
                     \\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\WER2F97.tmp.appcompat.txt
                     \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER393D.tmp.WERInternalMetadata.xml
                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ssh.exe_5d978b72d8bd7fe8a9c7f8cbfdfda8fd8a16e2_dd951e55_cab_06914030\memory.hdmp
                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ssh.exe_5d978b72d8bd7fe8a9c7f8cbfdfda8fd8a16e2_dd951e55_cab_06914030\triagedump.dmp

                     These files may be available here:
                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ssh.exe_5d978b72d8bd7fe8a9c7f8cbfdfda8fd8a16e2_dd951e55_cab_06914030

                     Analysis symbol:
                     Rechecking for solution: 0
                     Report Id: 4d3f193e-728e-441d-b768-5df51db52821
                     Report Status: 4
                     Hashed bucket:
Source             : Windows Error Reporting
ReplacementStrings : {, 0, APPCRASH, Not available...}
InstanceId         : 1001
TimeGenerated      : 5/3/2018 11:35:56 AM
TimeWritten        : 5/3/2018 11:35:56 AM
UserName           :
Site               :
Container          :

EventID            : 1000
MachineName        : d28bdb6a4faf
Data               : {}
Index              : 25
Category           : Application Crashing Events
CategoryNumber     : 100
EntryType          : Error
Message            : Faulting application name: ssh.exe, version: 0.0.0.0, time stamp: 0x00000000
                     Faulting module name: msys-2.0.dll, version: 2010.0.0.0, time stamp: 0x5aaae1ba
                     Exception code: 0xc0000005
                     Fault offset: 0x0000000000117265
                     Faulting process id: 0x54c
                     Faulting application start time: 0x01d3e2b9be865dd5
                     Faulting application path: C:\MinGit\usr\bin\ssh.exe
                     Faulting module path: C:\MinGit\usr\bin\msys-2.0.dll
                     Report Id: 4d3f193e-728e-441d-b768-5df51db52821
                     Faulting package full name:
                     Faulting package-relative application ID:
Source             : Application Error
ReplacementStrings : {ssh.exe, 0.0.0.0, 00000000, msys-2.0.dll...}
InstanceId         : 1000
TimeGenerated      : 5/3/2018 11:35:51 AM
TimeWritten        : 5/3/2018 11:35:51 AM
UserName           :
Site               :
Container          :
```

</p>
</details>


So it fails in/when-loading **msys-2.0.dll**.
The exception is **c0000005** (access violation) by address **0000000000117265**

It would be nice to get any help in further debugging this issue.

**Comment by dscho** [comment]
Maybe you can use native OpenSSH? See https://github.com/git-for-windows/git/issues/1403#issuecomment-351487560 for details.

**Comment by esman** [comment]
OpenSSH-Win64 works, but has other issues working with Jenkins Git Plugin (that's my main target actually):
E.g.: PowerShell/Win32-OpenSSH#1007

**Comment by whoisj** [comment]
@esman can you get a windbg capture of the AV? My guess here is that the issue has to do with virtualization and down-level driver management, as that has never stopped evolving despite appearances to contrary. 

[Getting Started with WinDbg (User-Mode)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/getting-started-with-windbg)

Be sure to use the correct bitness of the debugger, otherwise you'll see a ton of Wow64 obfuscation / indirection (or it'll just fail to load 😨).

**Comment by whoisj** [comment]
> @whoisj Is it possible to do without GUI?

Yes, kd.exe would your friend without the GUI.

**Comment by esman** [comment]
Found a way to workaround the issue.
````
docker run -it git
powershell
Copy-Item -Recurse c:\MinGit c:\MinGit_copy
Remove-Item -Force -Recurse c:\MinGit
Rename-Item c:\MinGit_copy c:\MinGit
c:\MinGit\usr\bin\ssh.exe -V
````
The ssh command doesn't output anything but returns '0' error code and actually works.

This is good-enough solution for my use-case, so I'm done with further debugging.

@whoisj Your assumption about low-level problem looks to be right. The fact is that ssh (or msys-2.0.dll) fails only if run from committed fs. If to copy files interactively, or try to run ssh from mounted folder ('-v' option) it works.

I suspect msys project to use some dll-comprehensives or hacks that are broken since 'Fall Creators Update'.

**Comment by casz** [comment]
Banging my head against the wall trying to dig out a solution... OpenSSH is not the answer for Jenkins and mingit doesn't work.

**Comment by whoisj** [comment]
@casz, have you looked at the Windows native SSH support?

https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6

**Comment by cmeiklejohn** [comment]
I'm running into this error with iperf3, so I don't think this is specific to SSH.

**Comment by esman** [comment]
@cmeiklejohn Sure, you're right. The problem must reside much deeper and we still lack a Hero to dig out the root cause.

**Comment by whoisj** [comment]
@cmeiklejohn @esman would a tool like [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) help understand where the failure is happening? I've had an unexpectedly high rate of success debugging random issue with not much more than a procmon trace to go on. Mostly having to do with environment + Git interactions gone wrong.

**Comment by casz** [comment]
@gistofj and others might be interested in git client plugin version 3 for Jenkins is patched with support for OpenSSH see
https://github.com/jenkinsci/git-client-plugin/pull/371
https://github.com/jenkinsci/git-client-plugin/pull/406
