### ISSUE TITLE
credential helper 'wincred' isn't working

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#166]
Logs:

```
$ GIT_TRACE=1 git fo
11:49:36.630613 git.c:557               trace: exec: 'git-fo'
11:49:36.630613 run-command.c:347       trace: run_command: 'git-fo'
11:49:36.633611 git.c:282               trace: alias expansion: fo => 'fetch' 'origin'
11:49:36.634624 git.c:348               trace: built-in: git 'fetch' 'origin'
11:49:36.644631 run-command.c:347       trace: run_command: 'git-remote-https' 'origin' 'https://Robert@stash.mydomain.com/scm/fe/core.git'
11:49:37.005883 run-command.c:347       trace: run_command: 'git credential-wincred get'
11:49:37.105957 git.c:557               trace: exec: 'git-credential-wincred' 'get'
11:49:37.105957 run-command.c:347       trace: run_command: 'git-credential-wincred' 'get'
11:49:37.130976 run-command.c:347       trace: run_command: 'bash' '-c' 'cat >/dev/tty && read -r -s line </dev/tty && echo "$line" && echo >/dev/tty'
Password for 'https://Robert@stash.mydomain.com':
```

Note that when I download `git-credential-winstore.exe` from [here](https://gitcredentialstore.codeplex.com/), and set `credential.helper = winstore`, I am properly prompted via windows dialog for username/password and that entry is saved into "Credential Manager" in Windows. This is the behavior I was expecting with `wincred`. But instead, it is prompting me for password via cin and entering that information does not create an entry in the Credential Manager.

**Comment by dscho** [comment]
It [works for others](https://github.com/git-for-windows/MINGW-packages/pull/5#issuecomment-106564712).

**Comment by rcdailey** [comment]
Confirmed working properly, apologies for the false alarm. I was looking for the stored credentials in the wrong place.
