### ISSUE TITLE
SDK installator doesn't finish correctly (also doesn't automatically request Administrator privileges)

### ISSUE THREAD

**Issue by ksulli** [git-for-windows/git#1660]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4

```
Also, I'm using the following SDK installer:
```
git-sdk-installer-1.0.7-64.7z.exe
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Verze 6.1.7601]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I just ran the installer as-is. The installer didn't prompt me for administrator access (standard UAC prompt).

### Details

I ran the installer twice without realizing I had to explicitly run the installer as admin (once in a subst'ed drive, once in c:). This is the output of the initial bash console after installation (notice the error message "could not save link"). Also, following [trying to make install](https://github.com/git-for-windows/git/wiki/Building-Git) gives an error

```
'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
Initialized empty Git repository in D:/git-sdk-64/usr/src/git/.git/
Initialized empty Git repository in D:/git-sdk-64/usr/src/build-extra/.git/
Initialized empty Git repository in D:/git-sdk-64/usr/src/MINGW-packages/.git/
Initialized empty Git repository in D:/git-sdk-64/usr/src/MSYS2-packages/.git/
Could not save link
last error: 0
Welcome to the Git for Windows SDK!

The common tasks are automated via the `sdk` function;
See `sdk help` for details.

$ cd /usr/src/git

$ make install
make: *** No rule to make target `install'.  Stop.

$ sdk create-desktop-icon
Could not save link
last error: 0
```

 - What did you expect to occur after running these commands?

Normal installation, shortcut icon gets created on desktop.

 - What actually happened instead?

Make fails, shortcuts to start the environment are not created. So i tried deleting the installation folder from disk (for some weird reason the folder has broken NTFS ownership information), installing it to a different location, and then finally i tried running the installator using "Run as administrator". This seemed to get rid of the problem of git not creating the shortcuts (and i changed the documentation).

However - this did not fix the problem that i'm not able to build anything. The installer didn't check out the git sources (the `/usr/src/git folder` is empty, eveh thoug the `.git` folder seems to be intact):
```
$ ls -l /usr/src/git
celkem 0

$ ls -l /usr/src/git/.git/
celkem 7
-rw-r--r-- 1 Sullivan 1049089 257  2. 5  16.13 config
-rw-r--r-- 1 Sullivan 1049089  73  2. 5  16.13 description
-rw-r--r-- 1 Sullivan 1049089  23  2. 5  16.13 HEAD
drwxr-xr-x 1 Sullivan 1049089   0  2. 5  16.13 hooks/
drwxr-xr-x 1 Sullivan 1049089   0  2. 5  16.13 info/
drwxr-xr-x 1 Sullivan 1049089   0  2. 5  16.13 objects/
drwxr-xr-x 1 Sullivan 1049089   0  2. 5  16.13 refs/

$ cat /usr/src/git/.git/config
$ cat /usr/src/git/.git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
        autocrlf = false
[remote "origin"]
        url = https://github.com/git-for-windows/git
        fetch = +refs/heads/*:refs/remotes/origin/*
```

So I tried to manually fetch:

```
$ git fetch origin
remote: Counting objects: 342080, done.
remote: Compressing objects: 100% (791/791), done.
remote: Total 342080 (delta 5), reused 795 (delta 5), pack-reused 341284
Receiving objects: 100% (342080/342080), 128.91 MiB | 6.77 MiB/s, done.
Resolving deltas: 100% (250950/250950), done.
From https://github.com/git-for-windows/git
 * [new branch]      maint-1.9             -> origin/maint-1.9
...
 * [new tag]               v2.9.5                -> v2.9.5

$ git checkout master
Checking out files: 100% (3255/3255), done.
Already on 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
```

Can I proceed safely? Is there any way to debug the installation process and find ouy what went wrong?

**Comment by dscho** [comment]
> ```
> 'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
> 'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
> 'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
> 'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
> ```

This is expected for now. On my long list of TODOs, there is one to streamline the `/etc/bash_profile` script (and support scripts) to refrain from making those symlinks/copies, among other things. I fear that this TODO will have to wait quite a bit longer.

> ```
> Could not save link
> last error: 0
> ```

This means that `sdk create-desktop-icon` failed...

> ```
> $ sdk create-desktop-icon
> Could not save link
> last error: 0
> ```

Yep, it failed. The source code for that command is here: https://github.com/git-for-windows/build-extra/blob/master/git-extra/create-shortcut.c. You could try to debug this by calling

```sh
sdk cd git-extra
make CFLAGS=-g create-shortcut.exe
(set -x && sdk create-desktop-icon)
```

and then running the call to `create-shortcut.exe` that the trace shows via `gdb -args ...` to find out what is going wrong.

Or improve the code to print a *much better* error message.

> ```
> $ cd /usr/src/git
>
> $ make install
> make: *** No rule to make target `install'. Stop.
> ```

The `/usr/src/git/` directory is not actually fully initialized just after installing the SDK. It needs to fetch, maybe set the autocrlf settings, and check out `master`. All of this is done automagically for you if you call

```
sdk install git
```

> Can I proceed safely [after fetching manually]?

Yes. I still would recommend to use the `sdk` function more, as it is pretty convenient, and I hope we will make it more convenient together yet.

**Comment by ksulli** [comment]
The problem with `sdk create-desktop-icon` is that the program requires running as Administrator for some reason (I have UAC turned on). I can reproduce the problem if I run `git-bash.exe` in plain usermode. After I run the command using "run as administrator", it works again. I see if I can debug something.

What threw me off track is that the [documentation](https://github.com/git-for-windows/git/wiki/Technical-overview#hacking-on-git) (used to) say

> Git is already checked out and the latest version build and installed

I re-wrote the docs saying you need to run `sdk install git`.

**Comment by bbolli** [comment]
> `last error: 0`

I assume that the [`CoUninitialize()`](https://github.com/git-for-windows/build-extra/blob/1b2bc7cc0a11b965161536f6cce10bbc21443ec2/git-extra/create-shortcut.c#L6) call clobbers the `GetLastError()` result.

**Comment by dscho** [comment]
> The problem with sdk create-desktop-icon is that the program requires running as Administrator for some reason (I have UAC turned on).

At first I thought this might be our old friend, the missing manifest. But no, I checked with ResEdit, and `create-shortcut.exe` has a manifest, including the appropriate privileges entry:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!--The ID below indicates application support for Windows Vista -->
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <!--The ID below indicates application support for Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <!--The ID below indicates application support for Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <!--The ID below indicates application support for Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/> 
      <!--The ID below indicates application support for Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/> 
    </application>
  </compatibility>
</assembly>
```

> I re-wrote the docs saying you need to run sdk install git.

You're right, I changed this so that it does not build everything anymore, as I had asked some contributors to work on the installer (and it sounded like a waste of their time to require them to wait through a full build & install).

**Comment by ksulli** [comment]
> I assume that the CoUninitialize() call clobbers the GetLastError() result.

After moving it to the end it gives me 3 - ERROR_PATH_NOT_FOUND. Since I was already able to hack the program, i added some debug statements to see what arguments are passed.

The problem isn't in the program, but in [the invocation](https://github.com/git-for-windows/build-extra/blob/1b2bc7cc0a11b965161536f6cce10bbc21443ec2/git-extra/git-sdk.sh#L62):
```
desktop_icon_path="$HOME/Desktop/Git SDK$bitness.lnk"
```

On my system I have (per company policy) a nonstandard "home" folder of `h:\` while my profile is still stored in `c:\Users\sullivan\`  - (basically %USERPROFILE%). For some reason, the environment is different when I run it as unpriviledged and priviledged (maybe this is an msys issue?)
```
$ net session &> /dev/null && echo "Running as admin" || echo "NOT running as admin"
Running as admin

$ set | grep 'HOME=\|USERPROFILE=\|HOMEPATH=\|HOMEDRIVE='
HOME=/c/Users/sullivan
HOMEDRIVE=H:
HOMEPATH='\'
SciTE_HOME='C:\ProgramData\SciTE'
SciTE_USERHOME='C:\Users\sullivan\AppData\Roaming\SciTE'
USERPROFILE='C:\Users\sullivan'
    local WINSYS32HOME="$(exec /usr/bin/cygpath -S -w)";
```

```
$ net session &> /dev/null && echo "Running as admin" || echo "NOT running as admin"
NOT running as admin

$ set | grep 'HOME=\|USERPROFILE=\|HOMEPATH=\|HOMEDRIVE='
HOME=/h/
HOMEDRIVE=H:
HOMEPATH='\'
SciTE_HOME='C:\ProgramData\SciTE'
SciTE_USERHOME='C:\Users\sullivan\AppData\Roaming\SciTE'
USERPROFILE='C:\Users\sullivan'
    local WINSYS32HOME="$(exec /usr/bin/cygpath -S -w)";
```

**Comment by dscho** [comment]
@ksulli great analysis! I guess it works as privileged user because then you are really a local admin that is not subject to the policies, and you do not have `HOME` set to something other than `USERPROFILE`.

Does it work if you replace `HOME` by `USERPROFILE` in https://github.com/git-for-windows/build-extra/blob/81ef92279b542b41989a183b7fb534679f97c678/git-extra/git-sdk.sh#L62?

**Comment by ksulli** [comment]
Yes, it works if I replace it with `USERPROFILE`.

**Comment by dscho** [comment]
> Yes, it works if I replace it with USERPROFILE.

Great! Care to contribute a PR with a nice commit message ending in a Signed-off-by: line?

**Comment by dscho** [comment]
Oh, I'm blind. There is already a PR: https://github.com/git-for-windows/build-extra/pull/184. Sorry for the noise!

**Comment by BattleBas** [comment]
Hello @ksulli regarding the documentation change to suggest `sdk install git` I'm running into an error.

When I run `sdk install git` after installing git-sdk-1.0.7 it fails to find the `install` command and prints out `sdk help`. It looks like maybe running `sdk init git` was what we need? Looking at [git-sdk.sh](https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-sdk.sh) I don't see a install command either. I might be doing something wrong so I don't want to the update the documentation until someone can confirm this.

The [building-git](https://github.com/git-for-windows/git/wiki/Building-Git) documentation probably needs to be updated as well to include the sdk command suggestion. Which I don't mind doing.

Thank you for your help! (because the documentation changed as part of this issue I'm commenting this here, hopefully that is appropriate)

**Comment by dscho** [comment]
> When I run sdk install git after installing git-sdk-1.0.7 it fails to find the install command and prints out sdk help.

Good point. I think I changed this recently to `sdk git-and-installer`... This will auto-initialize `git` and build it.

**Comment by dscho** [comment]
Is there anything left to do?

**Comment by dscho** [comment]
> Is there anything left to do?

I guess not...
