### ISSUE TITLE
Portable: post-install.bat typo in comments?!

### ISSUE THREAD

**Issue by BurtHarris** [git-for-windows/git#1663]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.1]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I installed the **portable version** into directory C:\Wham

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

C:\Wham\bin is already on the path.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**CMD.exe**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git-bash.exe --no-needs-console --hide --no-cd --command=post-install.cmd
```

 - What actually happened instead?

After installing portable version, I had a look at the file named **post-install.bat**.

It had a rather confusing set of instructions, saying:

```
@REM If run manually, it should be run via
@REM   git-bash.exe --no-needs-console --hide --no-cd --command=post-install.cmd
@REM to hide the console.
```

1.  The file extension of this script is **.bat**, not **.cmd**, so instructions seem wrong.
2.  It is unclear to me why I would run that from git-bash.exe
3.  Hiding the console leaves much to be desired...
4.  Following the instructions literally only seemed to touch etc/rebase.db.x86_64

Running post-install.bat manually (from CMD.exe) seems to have done mostly the right thing, saying:

```
C:\Wham>post-install.bat
"running post-install"
'C:\WINDOWS\system32\drivers\etc\hosts' -> '/etc/hosts'
'C:\WINDOWS\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\WINDOWS\system32\drivers\etc\services' -> '/etc/services'
'C:\WINDOWS\system32\drivers\etc\networks' -> '/etc/networks'
The batch file cannot be found.
```

I think the *The batch file cannot be found.* message is due to the script deleting itself.   That seems unnecessary.

**Comment by BurtHarris** [comment]
Could this be related to #1660?   

Am I'm better off reverting to version 2.16.x?

**Comment by ksulli** [comment]
I looked at the file history, it seems that the typo has been there for a long time, it seems it was introduced in  - https://github.com/git-for-windows/build-extra/commit/cc2c461a013f5bb575582f16337892e85384208e (the other files in the changeset refer to post-install.bat)

I don't think this has any relation to #1660 (except that the docs may be could be cleaned up a little).

**Comment by BurtHarris** [comment]
@dscho, not sure why you closed this.   There is a typo in this batch file, it doesn't work.

**Comment by dscho** [comment]
@BurtHarris have you noticed that I closed it via a commit?

**Comment by BurtHarris** [comment]
@dscho, missed that somehow, sorry.
