### ISSUE TITLE
The Vim configuration may not be optimal

### ISSUE THREAD

**Issue by chrisbra** [git-for-windows/git#1664]
First of all, thanks for the project. It is great to use on Windows and I like that it comes with a good (and updated) editor :) However, I noticed that some of the settings for Vim could be improved. (Both to have better defaults and also to be closer to upstream). So I would like to create a PR for fixing this. However I did not find the source package containing `/etc/vimrc`. 
So can you please point me to the correct repository, as this one is most likely wrong.

I am not sure if the following is required, but I complete it anyhow :)

 - [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.371]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Don't think so.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

**Comment by chrisbra** [comment]
ah, I think it is https://github.com/git-for-windows/git-sdk-64/blob/master/etc/vimrc and https://github.com/git-for-windows/git-sdk-32/blob/master/etc/vimrc right?

**Comment by bbolli** [comment]
These two repos are just the result of building Git for Windows. The original file must be changed in the build-extra repo, the file is `git-extra/vimrc`.

You can find out the package providing any file with `pacman -Qo <file>`:

```
$ pacman -Qo /etc/vimrc
/etc/vimrc is owned by git-extra 1.1.244.6ead44d-1
```

**Comment by chrisbra** [comment]
Wow, that is kind of hidden :( ...
Thanks for letting me know. Will create a PR against that file then later.
