### ISSUE TITLE
Cannot get Git/SSH to utilize GIT_ASKPASS, SSH_ASKPASS or core.askpass in Git Bash/Cmd on Windows

### ISSUE THREAD

**Issue by cleidigh** [git-for-windows/git#1669]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Goal:

I am a collaborator with the Visual Studio Code project.
I am working on better integration for Git utilizing SSH.
Specifically I want to create a shim askpass that can interact with
VSC for a GUI passphrase prompt.  As a first test I have been trying to get
the prompt to be handled by git-gui--askpass.  All my experiments
will not get either ssh or git to honor SSH_ASKPASS, GIT_ASKPASS or 
core.askpass .  All cases only show a terminal prompt.

See set up below:

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.17.0 Windows.1 64bit
```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 7x64 Professional

** insert your machine'fs response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled


 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Git Bash
Cmd

 - What commands did you run to trigger this issue? If you can provide a



After reading the documentation, SO postings and other sources,
I understood the following should work:

Under Git Bash:

[SET ASK PASS VARIABLES]
export SSH_ASKPASS="/c/Program\ Files/Git/mingw64/libexec/git-core/git-gui--askpass"
export GIT_ASKPASS="/c/Program\ Files/Git/mingw64/libexec/git-core/git-gui--askpass"
git config  core.askpass "/c/Program\ Files/Git/mingw64/libexec/git-core/git-gui--askpass"
export DISPLAY=".0"

[TRY GIT AND OR SSH] 


Christopher Leidigh@MacAir-Win7VM MINGW64 ~/Documents/TypescriptDev/sshtest1 (master)

Christopher Leidigh@MacAir-Win7VM MINGW64 ~/Documents/TypescriptDev/sshtest1 (master)
$ ssh git@github.com
Enter passphrase for key '/c/Users/Christopher Leidigh/.ssh/git-openssh-key':
git@github.com: Permission denied (publickey).
$

$ git push origin master
Enter passphrase for key '/c/Users/Christopher Leidigh/.ssh/git-openssh-key':
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$

 - What did you expect to occur after running these commands?
The tcl git-gui--askpass GUI script should run

 - What actually happened instead?
The normal terminal prompt appears

**Comment by michaelblyons** [comment]
I'm not an expert on GFW, but I'm curious whether you're actually looking to add the shim to [Microsoft/Git-Credential-Manager-for-Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) instead. Their also docs have [a short section for Askpass](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/blob/master/Docs/Askpass.md).

My apologies if that is all already known to you.

**Comment by cleidigh** [comment]
@michaelblyons 
My goal is to add more integrated support for SSH access to git repositories within VS Code directly.  I have briefly looked at GCM but, I'm looking at a solution that works on all platforms therefore working directly with the interface between SSH and GIT is my initial focus.  looking more at GCM my provide some insight.

**Comment by dscho** [comment]
> export SSH_ASKPASS="/c/Program\ Files/Git/mingw64/libexec/git-core/git-gui--askpass"

I think that backslash is too much, at least it only works here when I leave it off. However, I *also* have to use `setsid.exe ssh` (as per https://unix.stackexchange.com/questions/125427/force-ssh-to-always-use-ssh-askpass, but [`setsid.exe`](https://github.com/git-for-windows/git-sdk-64/raw/master/usr/bin/setsid.exe) is only bundled with Git for Windows' SDK so far, not with Git for Windows) in order to make it work.

**Comment by dscho** [comment]
I hope that my comment helped fix things?

**Comment by hummeleBop** [comment]
Could you please add the setsid utility in the Git for windows bundle ?
