### ISSUE TITLE
Pinned Git Bash shortcut does not execute .profile

### ISSUE THREAD

**Issue by fracz** [git-for-windows/git#167]
I have configured few items in my `~/.profile` file (like ssh-agent, aliases, $PS1 etc). Running Windows 7.

When I open new Git Bash, on taskbar it is visible with nice color git bash icon (like this: https://git-for-windows.github.io/favicon.ico).

When I right click it and select "Pin to taskbar", it seems to be pinned correctly but the icon is changed to console-like (sth like http://mricons.com/uploads/icon_sets/67/icons/111545/thumb/64x64.png).

When I close Git Bash and open it again from the pinned taskbar shortcut, it does not execute my `~/.profile` and the command line looks like

```
bash-4.3$
```

I have to go back to Start Menu -> Git Bash to have my settings executed.\

EDIT:

After executing
```
bash --login -i
```
in the "pinned command line" I get my environment set.

How to execute it automatically?

**Comment by dscho** [comment]
Hmm. Essentially the problem is that what you try to pin to the dock is *not* the `Git Bash` executable, but the `mintty` executable. The `Git Bash` executable *calls* that `mintty` executable, but with a bunch of command-line options, and after setting up some environment variables.

Quite honestly, I have no idea how to pin the `git-bash.exe` to the dock when the program that is actually running is `mintty.exe`... Maybe you have some ideas?

**Comment by linquize** [comment]
because git-bash.exe is just a wrapper.
Can we modify mintty.exe in order to achieve this, if no other method?

**Comment by dscho** [comment]
> Can we modify mintty.exe in order to achieve this, if no other method?

No, we cannot abduct `mintty` to do what it was never intended to do. `mintty` is a terminal emulator.

@fracz I wonder whether pinning works if you choose the `ConHost` instead of the `MinTTY` option in the installer?

**Comment by michaelprager** [comment]
why not drag&drop git-bash.exe onto the taskbar? This will pin the wrapper correctly instead of the executed shell.

**Comment by fracz** [comment]
Yes, but you will have two items in taskbar after launching it (the one for the shortcut and the second one for running process).

**Comment by albertosantini** [comment]
Here I have the same environment (windows 7 SP1 - 64 bit), but it works nice.

When I select `pin to taskbar` for `git-bash.exe` executable, the executable is pinned and the icon is ok, like favicon, not the terminal one. 

Clicking on it the terminal (mintty) is started correctly executing `~/.profile`.

I suppose you gave a look at `Shortcut` tab in `Git for Windows` properties (the properties of the executable you pinned). Maybe there is something misconfigured: icon, executable and so on.

Finally I suggest to use CCleaner utility, cleaning an old setup.

**Comment by fracz** [comment]
I have resolved this isse as follows:

1. Run git-bash.exe from any location.
1. Right click its icon in taskbar and select "Pin to taskbar". The icon on taskbar changes to the [mintty's](https://code.google.com/p/mintty/).
1. Close git bash window.
1. Go to `%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`. Find the Terminal shortcut with mintty's icon. Right click it and choose *Properties*.
1. In the *Target* field, add the following parameters to the terminal program: `--exec /usr/bin/bash --login -i`. As a results, it should looks like `"C:\Program Files\Git\usr\bin\mintty.exe" --exec /usr/bin/bash --login -i`. Click OK.
1. Click the pinned terminal in the taskbar - it should login automatically.

**Comment by dscho** [comment]
For future record: I could imagine that setting the [`System.AppUserModel.RelaunchCommand` property](https://msdn.microsoft.com/en-us/library/dd391571.aspx) from the Git wrapper might help (as hinted in [this blog](http://blogs.msdn.com/b/oldnewthing/archive/2011/06/01/10170113.aspx)).

**Comment by dscho** [comment]
@rcdailey feel free to work on the `RelaunchCommand` solution I described broadly.
