### ISSUE TITLE
diff.wordRegex doesn't honor LANG

### ISSUE THREAD

**Issue by danny0838** [git-for-windows/git#1671]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 6.1.7601]
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue?

```
$ echo '人' >test1.txt && echo '丁' >test2.txt
$ LANG=C.UTF-8 git diff --no-index --word-diff=plain --word-diff-regex=. -- test1.txt test2.txt
```
 - What did you expect to occur after running these commands?

```
...
[-人-]{+丁+}
```

(It works so on Linux.)

 - What actually happened instead?

```
...
<E4>[-<BA><BA>-]{+<B8><81>+}
```

**Comment by geunho** [comment]
In my case, setting the system environment variable, which name/value is `LESSCHARSET`/`UTF-8` was worked for me.

**Comment by danny0838** [comment]
@geunho: I tried this on the same platform:

    $ echo '人' >test1.txt && echo '丁' >test2.txt
    $ LESSCHARSET=UTF-8 git diff --no-index --word-diff=plain --word-diff-regex=. -- test1.txt test2.txt

and no luck...

**Comment by geunho** [comment]
I tried your example,
```bash
$ LESSCHARSET=UTF-8 git diff --no-index --word-diff=plain --word-diff-regex=. -- test1.txt test2.txt
diff --git a/test1.txt b/test2.txt
index 3ef0891..3773917 100644
--- a/test1.txt
+++ b/test2.txt
@@ -1 +1 @@
<E4>[-<BA><BA>-]{+<B8><81>+}
```
output was same as yours but without `--word-diff-regex=.` option,
```bash
$ LESSCHARSET=UTF-8 git diff --no-index --word-diff=plain -- test1.txt test2.txt
diff --git a/test1.txt b/test2.txt
index 3ef0891..3773917 100644
--- a/test1.txt
+++ b/test2.txt
@@ -1 +1 @@
[-人-]{+丁+}
```
It works! 😃

**Comment by dscho** [comment]
Unfortunately, [the `regex` library we use in Git for Windows](https://github.com/git-for-windows/git/tree/main/compat/regex/) does not support multi-byte encoding :-(

**Comment by danny0838** [comment]
This issue still persists in git version 2.33.1.windows.1. Is it considered as a `wontfix`?

**Comment by dscho** [comment]
See https://github.com/git-for-windows/git/issues/1671#issuecomment-700611917

**Comment by danny0838** [comment]
Isn't it possible to request multibyte support for the library or switch to another library?
