### ISSUE TITLE
Release notes are missing

### ISSUE THREAD

**Issue by SteveALee** [git-for-windows/git#1673]
The release notes no longer appear to be accessible from https://gitforwindows.org/ At least I could not find them. The "All Releases" link in the footer goes to github and there is no CHANGES file in the code

After installing they can be found at file:///C:/Program%20Files/Git/ReleaseNotes.html and the left hand nav hints this page is part of the full site..

**Comment by dscho** [comment]
The release notes are actually there, just not for prereleases. Is that the problem you are reporting?

**Comment by dscho** [comment]
The release notes are written out explicitly with each release. There is no link.

If you want a link to https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md, and if you have a brilliant idea where that link could live, logically, then please open a PR.
