### ISSUE TITLE
There is almost no tutorial or documentation suggesting anyone how to create your own custom git-bash.exe arguments like "--cd-to-home" . Can you kindly provide the steps and guidance to do that ?

### ISSUE THREAD

**Issue by viveklucky1986** [git-for-windows/git#1674]
There is almost no tutorial or documentation online, suggesting anyone how to create your own custom git-bash.exe arguments like "--cd-to-home" . Can you kindly provide the detailed steps and guidance to do that ?

### Setup

 - #### Git for Windows 2.17.0 64Bit

**Comment by telezhnaya** [comment]
Thank you for your question!

I created small guidance about making changes in git-bash, you could read it here: https://github.com/telezhnaya/MINGW-packages/wiki/FAQ:-Git-package

By the way, you will need to start your journey from cloning this repo: https://github.com/git-for-windows/MINGW-packages
It contains needed sources.

I hope it will help.

**Comment by dscho** [comment]
@viveklucky1986 I propose a deal: I'll answer any questions you have about options of Git Bash, show you where to find the source code, how to understand it, and in return you write a "man" page that users can then call up via `git help git-bash`. Deal?

**Comment by dscho** [comment]
I guess that means no deal. I'm just glad I did not waste time trying to answer questions preemptively.

**Comment by PhilipOakley** [comment]
#leftoverdocs ?

**Comment by PhilipOakley** [comment]
@viveklucky1986 Did you find out any more, or thoughts about the issue.

Have you seen #2352 and #2357 which has extra info. 

In fact if you can give any help to me on https://github.com/git-for-windows/git/pull/2357#issuecomment-543959154 (i.e. dscho has given a heads up, and I'm looking for collobarators for my draft)
