### ISSUE TITLE
warning: failed to restrict file handles

### ISSUE THREAD

**Issue by ymkim92** [git-for-windows/git#1675]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

  Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git stash
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

```
$ git stash
warning: failed to restrict file handles (5)

handle #0: 0000000000000104 (type 3, handle info (1) 0
handle #1: 0000000000000194 (type 3, handle info (1) 1
handle #2: 0000000000000160 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1


C:\Program Files\Git\mingw64/libexec/git-core\git-stash: line 41: /mingw64/libexec/git-core/git: Permission denied
Saved working directory and index state WIP on master: bdc676bf fixed mistake in e8b5f35817c5f1b0cca0511c690e728d327eb1f5
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> * What commands did you run to trigger this issue? If you can provide a Minimal, Complete, and Verifiable example this will help us understand the issue.
> 
> git stash

Sadly, this does not reproduce the issue here.

**Comment by ymkim92** [comment]
Even for me, it is not able to reproduce. 

git bash started working slowly about a week ago. So I updated git with Git-2.17.0-64-bit.exe. After that, nothing is changed. git stash and stash apply take about a minute each. Something is wrong but I can't find the reason.

**Comment by davidmwhynot** [comment]
im just going to chime in and say that i just got the same error after running a `git pull`... The pull seems to have went off without a hitch tough (still need to inflate some archive files to verify this completely). The only reason I am here is git told me to. The link takes me directly to open a new issue, but I thought it would be best if I searched first and I found this... relevant commands listed above but for my environment:

```
$ git --version --build-options
git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

```
$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```
`git pull`
```
git pull origin master
From ssh://yknotembroidery.com/var/repo/stariumxcv.sourcer
 * branch            master     -> FETCH_HEAD
Checking out files: 100% (287/287), done.
Updating 9cb13e0..b0a5089
Fast-forward
 .gitignore                                         |      2 +-
 functions/database/accounts/account.sql.gz         |    Bin 0 -> 5581 bytes
...
 create mode 100644 functions/utils/exporter/src/main.sh
warning: failed to restrict file handles (2)

handle #0: 0000000000000040 (type 2, handle info (1) 0
handle #1: 0000000000000138 (type 3, handle info (1) 1
handle #2: 0000000000000408 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn .git/hooks/post-merge: No such file or directory
```

**Comment by dscho** [comment]
@davidmwhynot your Git version is known to be affected. Once you upgrade to v2.17.0, it will be fixed.

**Comment by dscho** [comment]
> C:\Program Files\Git\mingw64/libexec/git-core\git-stash: line 41: /mingw64/libexec/git-core/git: Permission denied

This is the context: https://github.com/git-for-windows/git/blob/v2.17.0.windows.1/git-stash.sh#L40-L42

Note how `git` was called already in line 40. So it worked, and then it didn't. With an error 5 (Access Denied). That typically points to the blood-red hands of an antivirus.

**Comment by dscho** [comment]
I'll go ahead and assume that this is no longer an issue.
