### ISSUE TITLE
Worktree placed under a symlinked directory confuses git

### ISSUE THREAD

**Issue by kenneth-olwing** [git-for-windows/git#1676]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.371]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

No such file - using the portable build

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not at the moment

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\>mkdir MyRoot

C:\>mklink /d MyRootLink MyRoot
symbolic link created for MyRootLink <<===>> MyRoot

C:\>cd MyRootLink

C:\MyRootLink>mkdir MyNewProj

C:\MyRootLink>cd MyNewProj

C:\MyRootLink\MyNewProj>git init
Initialized empty Git repository in C:/MyRootLink/MyNewProj/.git/

C:\MyRootLink\MyNewProj>git stash
fatal: C:\ken1\Git\mingw64/libexec/git-core\git-stash cannot be used without a working tree.

C:\MyRootLink\MyNewProj>git rev-parse --is-inside-work-tree
false

```
 - What did you expect to occur after running these commands?

Stash should not give that message and the rev-parse should say true.

 - What actually happened instead?

Stash gives a non-sensical error message and rev-parse gives a false result.

After investigation I tracked it down to my use of symlinks above the worktree, Moving to the 'real' directory makes the commands work as expected.

**Comment by dscho** [comment]
Turns out that the `git stash` command was rewritten in C in the meantime, which worked around the issue, and I just opened a PR for the `git rev-parse --is-inside-work-tree` issue.

**Comment by kenneth-olwing** [comment]
Thank you for your feedback!

**Comment by dscho** [comment]
I just merged it. @kenneth-olwing Could I ask you to test the next [snapshot](https://wingit.blob.core.windows.net/files/index.html) (I might also get v2.25.0-rc1 out today)?

**Comment by dscho** [comment]
@kenneth-olwing Could you please test with github.com/git-for-windows/git/releases/tag/v2.25.0-rc1.windows.1?

**Comment by kenneth-olwing** [comment]
Sorry to be a bit behind the curve :-), but yes, it works for me (used the portable version).

Thanks, have a good 2020!

**Comment by dscho** [comment]
@kenneth-olwing thanks for testing!
