### ISSUE TITLE
Weird thing happened in command prompt

### ISSUE THREAD

**Issue by dmgolembiowski** [git-for-windows/git#1677]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
**git version 2.16.1.windows.4** and pretty sure 64-bit, but not totally certain
```
$ git --version --build-options
** igit version 2.16.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Windows 10, bittersweetly **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** defaults, maybe? **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** C:\Users\Master Chief>git /?
warning: failed to restrict file handles (2)

handle #0: 0000000000000004 (type 2, handle info (1) 0
handle #1: 000000000000015c (type 2, handle info (1) 1
handle #2: 0000000000000160 (type 2, handle info (1) 1 **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** powershell **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** git /? **
```
 - What did you expect to occur after running these commands?

** Basic help instructions **

 - What actually happened instead?

**C:\Users\Master Chief>git /?
warning: failed to restrict file handles (2)

handle #0: 0000000000000004 (type 2, handle info (1) 0
handle #1: 000000000000015c (type 2, handle info (1) 1
handle #2: 0000000000000160 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: '/?' is not a git command. See 'git --help'.

The most similar commands are
        am
        gc
        mv
        p4
        rm  **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**I'm not smart enough about how to do that. **

**Comment by dscho** [comment]
Please upgrade. This has been fixed in v2.17.0, which by this time is already six weeks old (i.e. it is half-time of the 12-week cadence used by Git to go from major version to major version).
