### ISSUE TITLE
Win10 64 bit system, Git-2.16.0-64-bit version can not be used normally

### ISSUE THREAD

**Issue by tabliu** [git-for-windows/git#1678]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.16.0.windows.2
cpu: x86_64
built from commit: a56c4f9e2a9513d2be57dc4346e0e84887399cd9
sizeof-long: 4

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [版本 10.0.15063] 64-bit

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
C:\Program Files (x86)\Git\etc\install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Bash

** insert your response here **
Git right click on Git Bash Here，Computer CPU is rapidly rising to more than 99%，and the computer into a state of false death。Generating the mintty.exe.stackdump file：
Exception: STATUS_ACCESS_VIOLATION at rip=0010041161C
rax=0000000000000018 rbx=0000000000000000 rcx=0000000000000780
rdx=0000000100468620 rsi=000006FD5F96FC20 rdi=0000000000000050
r8 =0000000000200000 r9 =00000000000001E7 r10=0000000100000000
r11=00000001004115C6 r12=000006FD611100C0 r13=00000000540BE3FF
r14=00000000540BE400 r15=0000000000000000
rbp=00000000540BE400 rsp=00000000FFFFC570
program=C:\Program Files (x86)\Git\usr\bin\mintty.exe, pid 10208, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
@tabliu you will need to use a lot more diligence than to leave most `** insert XYZ here **` unedited. You are also asking others for diligence in helping you resolve the issue, so it's only fair.

**Comment by tabliu** [comment]
@dscho Thank you for your patience.

**Comment by dscho** [comment]
This ticket would really require more details. Absent those, I am forced to close it. It is easy enough to reopen should the situation change.

**Comment by tabliu** [comment]
@dscho Sorry, this may be a problem in individual system. It can be used normally after replacing other computers with Git. Please forgive me for the inconvenience.
