### ISSUE TITLE
Git bash: fork failed (2): No such file or directory

### ISSUE THREAD

**Issue by kelvin-mkc** [git-for-windows/git#1684]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [versão 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Usually using git bash from ConEmu (version 180506 x64).
Full MSYS2 is installed on the default path, bash opens normally (4.4.19(2)-release (x86_64-pc-msys)).
TortoiseGit 2.6.0.0, it also works.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu/Git bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Open git bash from explorer on any folder (with or without a .git folder).
```
 - What did you expect to occur after running these commands?

The shell to be available.

 - What actually happened instead?

When started from explorer:

```
Error: Could not fork child process: There are no available terminals (-1).
```

When started from ConEmu:
```
{PID:6660} fork failed (2): No such file or directory
      0 [main] conemu-msys2-64 6660 cygwin_exception::open_stackdumpfile: Dumping stack trace to conemu-msys2-64.exe.stackdump


Command to be executed:
"C:\Program Files\ConEmu\..\Git\git-cmd.exe"  --no-cd --command=C:\PROGRA~1\ConEmu\ConEmu\conemu-msys2-64.exe /usr/bin/bash.exe -l -i


ConEmuC: Root process was alive less than 10 sec, ExitCode=x00008B00(35584).
```

ConEmu stack trace:
```
Exception: STATUS_ACCESS_VIOLATION at rip=00100401F0A
rax=0000000000000000 rbx=0000000100406DD0 rcx=000000018020B140
rdx=0000000000000000 rsi=000000010040609D rdi=000000060003A220
r8 =000000060003A236 r9 =0000000000000000 r10=0000000100000000
r11=0000000100401FB9 r12=00000000FFFFCBE0 r13=00000000FFFFBB30
r14=0000000000000000 r15=000000010040667D
rbp=0000000000000000 rsp=00000000FFFFBA10
program=C:\PROGRA~1\ConEmu\ConEmu\conemu-msys2-64.exe, pid 6660, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  00100401F0A (00000000002, 0010040B020, 00000000000, 00000000000)
00000000000  00100404A86 (0000000002D, 000FFFFCC55, 00000000030, FF0700010302FF00)
000FFFFCCB0  001800479F7 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045663 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045714 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by kelvin-mkc** [comment]
I had done an uninstall/install but it did not work.
Now doing the following, it worked:
* uninstall
* reboot
* rm -rf $PROGRAMFILES/Git
* install

**Comment by kelvin-mkc** [comment]
So, it happened again.

Steps:
$ git fetch
CTRL+C
Close the git bash tab on ConEmu
Try to open a new git bash tab

```
{PID:7728} fork failed (2): No such file or directory
```

Does bash put a lock on the tty devices?
Maybe it always tries to use the first one or there is an upper limit.

**Comment by kelvin-mkc** [comment]
Found the problem:

I was running this after every git upgrade to fix the slowness when the repo has
many files and the user is under a workgroup:

```bash
#!/bin/sh
# https://gist.github.com/k-takata/9b8d143f0f3fef5abdab
mkpasswd -l -c > /etc/passwd
mkgroup -l -c > /etc/group 
sed -E 's/files\s+db/files # db/' -i /etc/nsswitch.conf
```

Can reproduce with 100% certainty.

Not sure why this is happening though.

**Comment by kelvin-mkc** [comment]
https://gist.github.com/k-takata/9b8d143f0f3fef5abdab#solution-2-disable-db-in-etcnsswitchconf
>First you need to create /etc/passwd and /etc/group with the information of
>the local users (-l) and the current (domain) user (-c).

```shell
$ mkpasswd -l -c > /etc/passwd
$ mkgroup -l -c > /etc/group
```

These commands were run under a different user, which means my user was not
being added to **/etc/passwd** nor **/etc/group**. Without those and without
connecting to the AD db, the underlying MSYS2 had no permission to do anything.

After running the script from the previous comment with my user, git bash works
again and the slowness is gone.

**Comment by dscho** [comment]
> These commands were run under a different user, which means my user was not
> being added to /etc/passwd nor /etc/group. Without those and without
> connecting to the AD db, the underlying MSYS2 had no permission to do anything.

Oh, but that makes a total lot of sense now!

Thank you for writing this up so clearly. I am sure that this ticket will serve as a useful resource to users (maybe even myself included at some stage in the future) suffering the same conundrum.

**Comment by kelvin-mkc** [comment]
Thanks! I'm glad to hear that.
It was quite the showstopper for me, but luckily the fix was simple.

By the way, I made a note of this at the gist source:
https://gist.github.com/k-takata/9b8d143f0f3fef5abdab#gistcomment-2600759

**Comment by orgads** [comment]
I also have this error after upgrading to msys runtime 3.0.7-1:
```Error: Could not fork child process: There are no available terminals (-1).```

Generating /etc/passwd and /etc/group as explained above didn't solve it.

My user is in LDAP (enterprise environment).

**Comment by orgads** [comment]
Just noticed this bug is a year old. I'll file a new bug then :)
