### ISSUE TITLE
Path with glob pattern not converted

### ISSUE THREAD

**Issue by cbuchacher** [git-for-windows/git#1685]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I checked https://github.com/Alexpux/Cygwin/issues as well.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
$ node --version
v8.9.4
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

C:\Program Files (x86)\Git\git-bash.exe
```
$ which cmd
/c/Windows/system32/cmd
$ cmd //c echo /c
C:/
$ cmd //c echo '/c/*'
/c/*
$ X=/c cmd //c echo %X%
C:/
$ X='/c/*' cmd //c echo %X%
/c/*

$ which cmd.exe
/c/Windows/system32/cmd.exe
$ cmd.exe //c echo /c
C:/
$ cmd.exe //c echo '/c/*'
/c/*
$ X=/c cmd.exe //c echo %X%
C:/
$ X='/c/*' cmd.exe //c echo %X%
/c/*

# There is no node shell script involved here.
$ which node
/c/Program Files/nodejs/node
$ node -e 'console.log(process.argv[1])' /c
C:/
$ node -e 'console.log(process.argv[1])' '/c/*'
C:/*
$ X=/c node -e 'console.log(process.env["X"]);'
/c
$ X='/c/*' node -e 'console.log(process.env["X"]);'
/c/*

$ which node.exe
/c/Program Files/nodejs/node.exe
$ node.exe -e 'console.log(process.argv[1])' /c
C:/
$ node.exe -e 'console.log(process.argv[1])' '/c/*'
/c/*
$ X=/c node.exe -e 'console.log(process.env["X"]);'
C:/
$ X='/c/*' node.exe -e 'console.log(process.env["X"]);'
/c/*
```

C:\msys64\git-bash.exe with native Msys2 runtime. This is for reference, and to prepare a potential follow-up bug report to Msys2.
```
$ pacman -Ss msys2-runtime
git-for-windows/msys2-runtime 2.10.0-3 (base) [installed: 2.10.0-2]
    Posix emulation engine for Windows
git-for-windows/msys2-runtime-devel 2.10.0-3 (msys2-devel) [installed: 2.10.0-2]
    MSYS2 headers and libraries
msys/msys2-runtime 2.10.0-2 (base) [installed]
    Posix emulation engine for Windows
msys/msys2-runtime-devel 2.10.0-2 (msys2-devel) [installed]
    MSYS2 headers and libraries

$ which cmd
/usr/bin/cmd
$ cmd //c echo /c
C:/
$ cmd //c echo '/c/*'
C:/*
$ X=/c cmd //c echo %X%
C:/
$ X='/c/*' cmd //c echo %X%
C:/*

$ which cmd.exe
/c/Windows/system32/cmd.exe
$ cmd.exe //c echo /c
C:/
$ cmd.exe //c echo '/c/*'
C:/*
$ X=/c cmd.exe //c echo %X%
C:/
$ X='/c/*' cmd.exe //c echo %X%
C:/*

# There is no node shell script involved here.
$ which node
/c/Program Files/nodejs/node
$ node -e 'console.log(process.argv[1])' /c
C:/
$ node -e 'console.log(process.argv[1])' '/c/*'
C:/*
$ X=/c node -e 'console.log(process.env["X"]);'
/c
$ X='/c/*' node -e 'console.log(process.env["X"]);'
/c/*

$ which node.exe
/c/Program Files/nodejs/node.exe
$ node.exe -e 'console.log(process.argv[1])' /c
C:/
$ node.exe -e 'console.log(process.argv[1])' '/c/*'
C:/*
$  X=/c node.exe -e 'console.log(process.env["X"]);'
C:/
$ X='/c/*' node.exe -e 'console.log(process.env["X"]);'
C:/*
```

 - What did you expect to occur after running these commands?

1. I expect path conversion to behave the same for `command` and `command.exe`, if both resolve to the same executable.
1. I expect msys/msys2-runtime and git-for-windows/msys2-runtime to behave the same for the listed commands.
1. I expect `/c` to be converted to `C:\`, and `/c/*` to be converted to `C:\*` for the listed commands.

 - What actually happened instead?

1. Behavior of `node` and `node.exe` is different, even though they resolve to the same executable.
1. Msys2's native and Git-for-Windows' modified msys2-runtime behave differently.
1. In some cases, `/c` is not converted, and in some others `/c/*` is not converted.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not applicable.

**Comment by cbuchacher** [comment]
I guess the relevant code is here:
- https://github.com/git-for-windows/msys2-runtime/blob/master/winsup/cygwin/path.cc
- https://github.com/git-for-windows/msys2-runtime/blob/master/winsup/cygwin/msys2_path_conv.cc
- https://github.com/Alexpux/Cygwin/blob/master/winsup/cygwin/path.cc

But before I dive into that, it would help me to understand how we extended the behavior of Msys2's native runtime. Maybe my expected behavior is in conflict with other expectations?

I could try to have a look at the git log/diff. Where did we branch off from Msys2?

```
$ git remote -v
origin  https://github.com/git-for-windows/msys2-runtime.git (fetch)
origin  https://github.com/git-for-windows/msys2-runtime.git (push)
upstream        https://github.com/Alexpux/Cygwin (fetch)
upstream        https://github.com/Alexpux/Cygwin (push)
$ git rev-list upstream/master..origin/master|wc -l
17860
```

**Comment by rimrul** [comment]
>Behavior of node and node.exe is different, even though they resolve to the same executable.

That's a pitfall of  `which`. Your `node` command is probably an alias to `winpty node`. Have a look at `alias` or `type -a node`. 

[1] https://unix.stackexchange.com/questions/10525/how-to-use-which-on-an-aliased-command
[2] https://github.com/git-for-windows/build-extra/blob/master/git-extra/aliases.sh

**Comment by cbuchacher** [comment]
Ok. Then instead issue 1 becomes: why is path conversion suppressed if the winpty wrapper is present? Winpty links to msys-2.0.dll, so paths are not converted for winpty itself. But if I build an msys wrapper myself, then paths are still converted for any non-msys executable started as a subprocess. What is different about winpty?

- test.c
```c
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char *const *argv)
{
        printf("X: %s\n", getenv("X"));
        execvp(argv[1], &argv[1]);
        perror("execvp");
        return 1;
}
```

- Output with test.exe
```sh
$ X=/c ./test.exe node.exe -p -e "process.env['X']"
X: /c
C:/
```

- Output with winpty.exe
```sh
$ X=/c winpty.exe node.exe -p -e "process.env['X']"
/c
```

**Comment by rimrul** [comment]
It's probably because winpty does it's own path conversion. 

[1] https://github.com/rprichard/winpty/blob/850661d02bd8b9e5b7c802da51cf47d1140f49dd/src/unix-adapter/main.cc#L201-L234

[2] https://github.com/Alexpux/MSYS2-packages/blob/master/winpty-git/0001-Apply-POSIX-to-Win-conversion-on-all-arguments-on-MSYS.patch

[3] https://github.com/Alexpux/MSYS2-packages/blob/master/winpty/0001-Apply-POSIX-to-Win-conversion-on-all-arguments-on-MSYS.patch

[4] https://github.com/Alexpux/MSYS2-packages/blob/master/winpty-git/0002-fix-path-conversion.patch

[5] https://github.com/Alexpux/MSYS2-packages/blob/master/winpty/0002-fix-path-conversion.patch

**Comment by cbuchacher** [comment]
I did some research but I couldn't figure out why path conversion is not performed for winpty: https://github.com/rprichard/winpty/issues/146

I could however exclude the Msys patches since behavior is the same with upstream winpty.

**Comment by cbuchacher** [comment]
The path conversion in [1] only applies to the executable path, not to the arguments or the environment variables. So this is only related in that for Msys, it should not be necessary to manually do any conversion in the first place.

**Comment by cbuchacher** [comment]
Err, scratch that. The command line and arguments are passed from winpty to winpty-agent through a pipe. So they circumvent the path conversion which normally happens when an msys executable runs a non-msys subprocess.

This still does not explain why environment variables are not converted when winpty starts winpty-agent. Environment variables are not passed through the pipe (but maybe I should check that again). In any case, manual path conversion *is* indeed necessary.

**Comment by drizzd** [comment]
I suppose this behavior is a direct consequence of https://github.com/git-for-windows/msys2-runtime/commit/384b37d54638f36567a04fcff8a491ddfe42d7da.
@dscho Do you recall the motivation for this change?

**Comment by dscho** [comment]
> Do you recall the motivation for this change?

Based on the date, I am certain that this was necessary to have Git's test suite pass.

**Comment by dscho** [comment]
Closing this stale ticket.
