### ISSUE TITLE
Failed to restrict file handles

### ISSUE THREAD

**Issue by depressingillusion** [git-for-windows/git#1686]
- [ Maybe? ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.16299.431] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

**Editor Option: Notepad++
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
** I dont thinks so**
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit
 - What did you expect to occur after running these commands?

I realized i typed the command wrong, but still told me to report it so I am.

 - What actually happened instead?

I received
"warning: failed to restrict file handles (2)

handle #0: 0000000000000408 (type 3, handle info (1) 7ffa
handle #1: 000000000000040c (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'src/' is not a git command. See 'git --help'.
"
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None

**Comment by PhilipOakley** [comment]
Hi @depressingillusion

Thanks for reporting. This is a known bug in that version that has now been fixed, so it's time to update.

Update either via https://gitforwindows.org/ which will detect your OS type, or via https://github.com/git-for-windows/git/releases/
