### ISSUE TITLE
warning: failed to restrict file handles when `git [verb]`'s [verb] contains slashes.

### ISSUE THREAD

**Issue by dilijev** [git-for-windows/git#1688]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Possibly related to #1675 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.gvfs.1.31.g9bf6eec
cpu: x86_64
built from commit: 9bf6eeccc828c5445a431291df784f15eaf27fd6
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.48]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing in particular.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`cmd`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git hasrelrtc/release/1.8
git abc/a/b
```

 - What did you expect to occur after running these commands?

This was a typo of an alias followed by a branch name (I forgot the space). I'd expect to be told "not a git command" and no internal error.

 - What actually happened instead?

Correctly reported "not a git command", but got an error as well:

```
>git hasrelrtc/release/1.8
warning: failed to restrict file handles (2)

handle #0: 000000000000004c (type 2, handle info (1) 0
handle #1: 00000000000000f8 (type 2, handle info (1) 1
handle #2: 00000000000000fc (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'hasrelrtc/release/1.8' is not a git command. See 'git --help'.
```

In `git [verb]` if `[verb]` contains slashes, it seems to repro.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No specific repo.

**Comment by dscho** [comment]
> git version 2.16.2.gvfs.1.31.g9bf6eec

Can you switch to a newer version? It seems that [v2.17.0.gvfs.1-preview-6](https://github.com/Microsoft/git/releases/tag/v2.17.0.gvfs.1-preview-6) is the latest. Updating to at least v2.17.0 should fix the problem.

**Comment by dilijev** [comment]
It looks like SetupCanary is not updating me to the latest ("All Components Up To Date") -- should I install manually from that link?

**Comment by dscho** [comment]
@dilijev it's probably not safe to update without updating GVFS to a compatible version.

**Comment by dilijev** [comment]
Issue is fixed in the latest git.
