### ISSUE TITLE
I can proceed with installation without an editor installed.

### ISSUE THREAD

**Issue by izdwuut** [git-for-windows/git#1690]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.48]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash that was shipped with Git for windows.
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
The issue that I stumbled upon is related to the installer itself, so I'm going to stick to explaining how it can be reproduced:

1. Don't have Notepad++ installed on your system (or install it as portable).
2. Run Git for Windows 2.17.0 installer.
3. On an editor selection screen, choose Notepad++. You
should be unable to continue installation because of the "next" button
being disabled.
4. Press "prev".
5. Press "next". Notepad++ should be still highlighted, and the "next"
button should be active, allowing to continue installation.

```
 - What did you expect to occur after running these commands?

That I would be unable to proceed with installation.

 - What actually happened instead?

I was able to proceed with installation. The selected editor was set and I was able to continue installation. While it wasn't on my system, it made Git unable to use it.

 - Proposed solution
[Here](https://github.com/git-for-windows/build-extra/pull/187)'s a related PR

**Comment by dscho** [comment]
This is fixed by https://github.com/git-for-windows/build-extra/pull/187, right?

**Comment by izdwuut** [comment]
Oh, yeah. Correct. I wasn't aware that I'm required to close the issue.
