### ISSUE TITLE
Bad links in 2.17.1 release notes

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#1694]
Hi,

1. `Comes with cURL v7.60.0` appears twice
2. Two links for the Ctrl-C handling refer to the wrong commit. Instead of https://github.com/git-for-windows/msys2-runtime/commit/78e2deea8ec1db4aea1e78432ae98dac7198f6a5 they refer to https://github.com/git-for-windows/msys2-runtime/commit/fa84a1f06b83b54847e6505df2bdb6db1860f47f

**Comment by dscho** [comment]
Could you help me and open a PR?

**Comment by orgads** [comment]
Done. I didn't know where to look so I filed a bug :)
