### ISSUE TITLE
Install option to not modify path modifies path

### ISSUE THREAD

**Issue by af4jm** [git-for-windows/git#1696]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

** During installation, selected the option to not modify the path **

 - What did you expect to occur after running these commands?

** checked path before & after install, expected them to be identical **

 - What actually happened instead?

** git was deleted from the path **

Additional comment:  This leads me to believe that if I had selected to add git to my path, that it would have been deleted & re-added at either beginning or end, which is equally wrong.  "Do not modify" means just that, guaranteed to be identical at the end to what it was at the beginning.  And the add to path option should check if it's in the path already, and if it is then the path should again remain unmodified.

**Comment by rimrul** [comment]
It seems to me like you installed one version of Git for Windows with the "add Git to the Path" option and then installed a newer vesion with the "do not modify" option. It seems that the new setup detected the old installation and ran the old uninstaller (as intended) and that uninstaller removed the old entries from the path. Afterwards the new installer installed the new version and did not modify the Path.

**Comment by mfriedrich74** [comment]
That's typically called an upgrade install. When an installer calls the previous uninstaller, you usually want to preserve the previous settings. This is a common scenario in the business environment. For example, an IT department want to rollout updates to hundreds of machines (e.g. security patches) but does not want to destroy the users settings who installed it initially. 

I always wondered how git supports that and so far we dictated common defaults, knowing some users will be annoyed and have to repair their settings after such an massive rollout. The next one isn't far away because of that security issue that got fixed recently.

**Comment by dscho** [comment]
> When an installer calls the previous uninstaller, you usually want to preserve the previous settings. This is a common scenario in the business environment. For example, an IT department want to rollout updates to hundreds of machines (e.g. security patches) but does not want to destroy the users settings who installed it initially.

I have an outline how that could be implemented, but so far failed to have time to do it.

This will require conditional code (when `/KEEPEXISTINGOPTIONS=1` was passed, i.e. when `ParamIsSet('
KEEPEXISTINGOPTIONS')`) reading the previously-selected components from the `Inno Setup: Selected Components` setting in the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Git_is1`.

Then, the list of components has to be enumerated (how to tell how many there are?) via
`WizardForm.ComponentsList` and somehow we have to figure out which components correspond to the values in the comma-separated list of that registry setting.

It's a bit involved, and you'll learn a lot about InnoSetup.

**Comment by dscho** [comment]
I guess @mfriedrich74 is not interested in implementing this? Well, neither am I.
