### ISSUE TITLE
Default folder does not work properly if home folder name != username

### ISSUE THREAD

**Issue by spease** [git-for-windows/git#1697]
My home folder is C:\Users\A, but I changed my username (without renaming my home folder) and it is now B. Every version of Git for Windows that I've used ends up setting the initial working directory to "/" rather than my home folder (C:\Users\A). The ~ replacement does work properly.

I'm guessing this is just an uncommon situation and a simple oversight, but if additional information is needed I can try to provide it.

**Comment by michaelblyons** [comment]
Maybe relates to https://github.com/git-for-windows/build-extra/pull/184

**Comment by dscho** [comment]
> Maybe relates to git-for-windows/build-extra#184

Most likely, it is a different issue. The way Git for Windows determines the home directory is to look for an environment variable `HOME`. If it does not find one, or it does not point to an existing directory, Git for Windows falls back to `HOMEDRIVE` and `HOMEPATH`. If those either do not exist or do not point at an existing directory, we fall back to `USERPROFILE`.

**Comment by n9** [comment]
@dscho I have hit an issue with the behavior you described: When using runas, `HOMEDRIVE/HOMEPATH` points to `c:\Windows\System32`. However, `USERPROFILE` points to correct user's _home_ directory.

Why `USERPROFILE` is used last? What about to switch the order?

**Comment by n9** [comment]
Or should I create a separate issue for that?

**Comment by dscho** [comment]
> What about to switch the order?

I would not like to do that, as many users might have come to rely on this behavior. Remember, with a several-million download count (v2.21.0 was downloaded [over 7 million times]), if even 0.01% complain to the Git maintainer about broken behavior, that translates to several hundred complaints. Quite honestly, I have more fun ways to complicate my life than that.

Why not just use the well-documented `HOME` variable to override Git's auto-detection?

**Comment by n9** [comment]
I currently set `HOME` to override this.

But, it is really difficult to find what's going on, when you do not know this windows git's behavior.

What about to add _some_ global switch with two options `PREFER_HOMEPATH` and `PREFER_USERPROFILE`?

`PREFER_HOMEPATH` could be default now. And with new major version, the default could be changed to `PREFER_USERPROFILE`.

**Comment by dscho** [comment]
> `PREFER_HOMEPATH` could be default now. And with new major version, the default could be changed to `PREFER_USERPROFILE`.

I don't really see how that would _not_ break existing users...
