### ISSUE TITLE
Cannot amend commits with Notepad++, cannot find default editor, core.edit has correct path but Git can't understand it

### ISSUE THREAD

**Issue by starrychloe** [git-for-windows/git#1699]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Nope, nothing found
https://github.com/git-for-windows/git/issues?utf8=%E2%9C%93&q=is%3Aissue+core.edit

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.16.3.windows.1
cpu: x86_64
built from commit: 5d726e05e4c0ff9e11374e64e21d8300b0291c6d
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 8.1, 64 bit. I have no idea why it says 6 below.

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Console2

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
>git config core.edit "c:\Program Files\Notepad++\notepad++.exe"
>git config -l
core.edit=c:\Program Files\Notepad++\notepad++.exe
>git commit --amend
hint: Waiting for your editor to close the file... /C/Program Files/Notepad++/notepad++.exe: /C/Program: No such file or directory
error: There was a problem with the editor '/C/Program Files/Notepad++/notepad++.exe'.
Please supply the message using either -m or -F option.
>git config core.edit "c:/Program Files/Notepad++/notepad++.exe"
>git config --get core.edit
c:/Program Files/Notepad++/notepad++.exe
>git commit --amend
hint: Waiting for your editor to close the file... /C/Program Files/Notepad++/notepad++.exe: /C/Program: No such file or directory
error: There was a problem with the editor '/C/Program Files/Notepad++/notepad++.exe'.
Please supply the message using either -m or -F option.

```
What's worse you can't even unset it and go back to VI!

```
>git config --unset core.edit
>git config --get core.edit
C:\\Program Files\\Notepad++\\notepad++.exe
>git commit --amend
hint: Waiting for your editor to close the file... /C/Program Files/Notepad++/notepad++.exe: /C/Program: No such file or directory
error: There was a problem with the editor '/C/Program Files/Notepad++/notepad++.exe'.
Please supply the message using either -m or -F option.
```

 - What did you expect to occur after running these commands?

The editor would pop up and I would edit the commit message and close the file.

 - What actually happened instead?

The error above.

**Comment by PhilipOakley** [comment]
To make Notepad++ work just right ou need a load of options set. The normal installer will do this for you usually, but you may have set up the editor config manually.

I have in my home .gitconfig file :
```
[core]
	editor = 'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noplugin
```

together that lot will make git fire up a single new instance of Notepad++ which will on save &close signal back to Git that you have finished your editing, and proceed as desired.

HTH.
