### ISSUE TITLE
git-new-workdir: ln: failed to create symbolic link

### ISSUE THREAD

**Issue by dansmith65** [git-for-windows/git#170]
v2.4.2.windows.1 (64 bit, portable install, if that matters), run from an elevated command prompt

`git-new-workdir repo test` returns:
```
ln: failed to create symbolic link 'test/.git/packed-refs': No such file or directory
unable to create new workdir 'test'!
```

The packed-refs directory doesn't exist in my repo.

**Comment by linquize** [comment]
`packed-refs` may or may not be present in a repository.
It all the refs are loose refs (all live in `refs/`), `packed-refs` does not exist.

**Comment by dscho** [comment]
@dansmith65 is this *with* or *without* the `MSYS` environment variable [set appropriately](https://github.com/git-for-windows/git/issues/171#issuecomment-106883388)?

@linquize yes, the target might not exist, but @kblees worked on support for that, triggered by said `MSYS` setting.

**Comment by dansmith65** [comment]
@dscho, It was with `MSYS=winsymlinks:nativestrict`.

I think the root issue here is that `ln -s` will create a symlink, even if the target does not exist, but `mklink` will not.

**Comment by dscho** [comment]
@dansmith65 oh, but then the bug is in the use of `mklink`, is it not? And we do not distribute the `git-new-workdir` with Git for Windows...

**Comment by dansmith65** [comment]
@dscho that depends on how you look at it. When submitting my pull request to make `git-new-workdir` work on Windows I was told that it shouldn't need to be patched because the latest version of git-for-windows had improved `ln -s` that should just work, but it doesn't.

That being said, I'm not sure how this would be fixed from the context of `ln` since Windows can't create a symlink to a file/folder that doesn't exist yet. So maybe `git-new-workdir` really does need to be fixed to work on Windows.

**Comment by dscho** [comment]
> Windows can't create a symlink to a file/folder that doesn't exist yet.

See https://github.com/git-for-windows/git/commit/d870d8d3081ef5bbd85f73c4c23369463f44efda, in particular:

> It is possible to create symlinks before the target exists (or in case of
> symlinks to symlinks: before the target type is known). If this happens,
> create a tentative file symlink and postpone the directory decision: keep
> a list of phantom symlinks to be processed whenever a new directory is
> created in mingw_mkdir().
> 
> Limitations: This algorithm may fail if a link target changes from file to
> directory or vice versa, or if the target directory is created in another
process.

**Comment by kblees** [comment]
I just tried `git-new-workdir` with `MSYS=winsymlinks:nativestrict` and it worked just fine.

Are you sure that your msys-2.0.dll is up to date? In particular, that it includes this commit: https://github.com/git-for-windows/msys2-runtime/commit/c91bda7df2870dacc9ee39bce1c6b9b44b462c24

**Comment by dscho** [comment]
Thank you, @kblees. @dansmith65 could you test again, please, and report back whether it works for you now, too?

**Comment by dansmith65** [comment]
I'll test again, but I'm swamped at the moment, so it probably won't be until next week.

**Comment by dscho** [comment]
@dansmith65 could you test with the most recent release candidate, please?

**Comment by dscho** [comment]
@dansmith65 Ping?

**Comment by dscho** [comment]
Third time's a charm: @dansmith65 Did you get a chance to test?

**Comment by dansmith65** [comment]
Worked for me without doing any additional config:
https://github.com/git-for-windows/git/releases/download/v2.4.6.windows.1/PortableGit-2.4.6-5th-release-candidate-64-bit.7z.exe

Sorry for the delayed response and thanks for the improvements on this!

**Comment by dscho** [comment]
Thanks for confirming!
