### ISSUE TITLE
When Cherry-picking, Git does not regenerate Change-Id after removing it when there's text inside the commit message

### ISSUE THREAD

**Issue by keessonnema** [git-for-windows/git#1700]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.48]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Git commit --amend
```
 - What did you expect to occur after running these commands?

Git should regenerate a Change-Id on amending the cherry-pick commit

 - What actually happened instead?

Because I have extra information in the commit message, e.g.:
(I've added this...
I've solved this issue
This bug-ticket can be closed)
Git won't regenerate a Change_id for that commit. Without the extra info it works (only the title, no extra info)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This happens on all repositories

**Comment by dscho** [comment]
Git has no code to handle or parse Change-Id. Are you sure this is a Git for Windows problem and not related to, say, Gerrit (which *does* handle Change-Id IIRC)?

**Comment by keessonnema** [comment]
@dscho Yeah it's a bit tricky. I can't test this on Linux, maybe someone else could try this for me.
Try cherry-picking a commit and remove the change-id, add some text in the commit message (a list of things changed would do), then do a git commit --amend and see if a new change-id is generated beneath the text you've added.

If it doesn't then it's definitely a Gerrit problem.

**Comment by dscho** [comment]
@keessonnema you are leaning quite a bit on others without depleting your options to debug this further.

For example, set `GIT_TRACE=1` before running that `git commit`. It is quite likely that you are running a pre-commit-msg hook or another hook, and that that hook fails to process your commit message accordingly.

Also, as to:

> I can't test this on Linux, maybe someone else could try this for me.

The first part is easily addressed via https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6. And the second part simply makes me want to run away ("wait, somebody is offering me to go on a wild goose chase to help them, and they have not done anything substantial to figure out the problem themselves yet?").

So maybe you want to do a bit more digging on your own before trying to put others to work :-)

**Comment by alegrigoriev** [comment]
ChangeId: in Gerrit shops is generated by commit-msg hook, which is only invoked during git-commit and git-merge. Not invoked during git-cherry-pick (and not in reword operation of rebase-i). Just live with it, or try to call commit-msg hook from some other appropriate hook invoked during cherry-pick.

**Comment by PhilipOakley** [comment]
> ChangeId: in Gerrit shops is generated by commit-msg hook, which is only invoked during git-commit and git-merge. Not invoked during git-cherry-pick (and not in reword operation of rebase-i).

Isn't the cherry-pick case being addressed upstream at the moment? That is, making sure that cherry-pick will invoke the appropriate commit hook. 

The upstream mail archive can be searched at https://public-inbox.org/git/?q= 
 
The thread/patch https://public-inbox.org/git/20181211234909.2855638-5-tj@kernel.org/ may be a good start, especially if it could be improved to ensure the correct cases are covered or the breadth of the documentation (so that this case (of another hook) is explained in the right places)

**Comment by dscho** [comment]
Okay, I'll go ahead and determine that the original poster really does not want this to be resolved, as no effort has been spent on it (instead there seemed to be a hope that others would spend their time, for free, on resolving their issues, which is plainly [not acceptable](https://github.com/git-for-windows/git/blob/master/CODE_OF_CONDUCT.md#our-standards) in this project).

In the event that the original poster starts to do their due diligence, we can *easily* reopen this issue.
