### ISSUE TITLE
Is it time to change the default options

### ISSUE THREAD

**Issue by SteveALee** [git-for-windows/git#1701]
# Linefeed handling

Can we finally switch to no EOL processing as the default?

For a long time I've been using LF only returns for my projects so they work for devs on Windows or *nix. Modern editors support this (and even a new notepad release). Adding an Editorconfig config file makes it explicit and you can also add `* -text` in .gitattributes. As far a I know the only files that *need* CRLF EOLs are the Visual Studio config files, and that might have changed given MSs new open ethos

I used to always set the Convert CRLF to LF on check in option but after getting fed up with those pesk warnings on checkin in have switch to no process. However I still use editorconfig and .gitattribs to make the settings explicit for my projects given users setups may vary (how  I wish this would finally go away)

# Terminal

Can we choose the windows terminal for default now?

Since the last Windows 10 release the terminal has improved greatly. Would be be possible to detect this and offer it as the default? I always switch when installing G4W.

Alternatively Zeit's [Hyper](https://hyper.is/) is shaping up nicely and lets you run all 4 common shells on windows (cmd, PowerShell, Git4 Windows bash & WSL bash)

**Comment by rimrul** [comment]
>Can we finally switch to no EOL processing as the default? 

What would the advantage of that change be? I get that it suits your development workflow, but I don't tink it's a big advantage for Git for Windows users in general.

>Since the last Windows 10 release the terminal has improved greatly. 

That's nice, but Git for Windows supports "all recent, commercially released x86 32 bit and 64 bit versions of Windows, starting with Windows Vista." and most of those don't have the improved Windows 10 terminal.

> Alternatively Zeit's Hyper is shaping up nicely

That seems to be a Wrapper for other Terminals that only supports 64 bit environments. We'd still need to use git bash or cmd under the hood and couldn't offer this option on 32 bit operating systems.

>Hyper is an Electron-based Terminal built on HTML/CSS/JS
>[...]
>Example extension: Hyperpower
The following extension renders particles as the caret moves

Every day we stray further from gods light. I want the memory of this unholy abomination purged from my mind. Preferebly with some kind of holy flame. I feel like warrants a handwritten apology letter to Ken Thompson and everyone else who worked at Bell labs on the development of Unix or contributed to basically any POSIX shell.

**Comment by dscho** [comment]
> For a long time I've been using LF only returns for my projects so they work for devs on Windows or *nix. Modern editors support this (and even a new notepad release).

That notepad release you mention is available only to Windows Insiders so far, not to anybody else. So claiming that it is time to switch is jumping the gun a little.

> Adding an Editorconfig config file makes it explicit and you can also add * -text in .gitattributes.

It is definitely the best idea to define explicitly in a `.gitattributes` file what your project's files' line endings should be. See also https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

> As far a I know the only files that need CRLF EOLs are the Visual Studio config files, and that might have changed given MSs new open ethos

I don't think that this characterizes the situation well. What we support in Git for Windows are Windows users. I.e. users who run all kinds of Windows software. Even if *all* of Microsoft's software handled LF-only line endings in the way you wish, users would still use software (and possibly be stuck with ancient versions because their companies won't pay for an upgrade) that requires CR/LF line endings.

> Can we choose the windows terminal for default now?
> 
> Since the last Windows 10 release the terminal has improved greatly.

There are still a lot of bug reports coming in from Windows 7 users.

I will *not* slam the door shut on Windows 7 users.

**Comment by dscho** [comment]
I just marked this ticket as "up for grabs" not because I agree with the suggested change of defaults, but because I think that the underlying idea has merit: to allow for easier configuration. For example, if anybody wants to support Hyper out of the box, it is just a PR away (teaching the installer a new option).

**Comment by SteveALee** [comment]
@dscho thanks. I did not mean to "claim" anything, rather i was asking the question. As you point out I only know my use cases and you have all the detailed knowledge. Thanks for making the situation clearer. I certainly would not suggest dropping win 7 support.

I did wonder if ms might backport the notepad update once released, but I think that's most unlikely as win 7 appears to be in support phase from their perspective.

Text mode is a problem since DOS that just won't go away! 

I was about to close this, so thanks for putting upforgrabs.

**Comment by SteveALee** [comment]
For many, many years I been using POSIX simulators on Windows and always prefer to sit in a bash style shell. I I used the old MSYS/MinGW rather than Cygwin, then when I discovered G4W that was one less thing to install :) Years ago I used the MKS shell on DOS (you could use / in paths - yay). 

I have worked in projects with others whom use both Windows tools and *NIX boxes. So cross platform has always been a rather painful issue. LF EOLs everywhere seemed the way to go but most Windows tools esp. editors and git (not G4W specifically) had very limited support for LF and I even once tried using scripts to convert back and forth, but that was too fragile.

Also, in general I've occasionally been badly bitten by a VCS translating files (EOL or tags). Sometimes text files with sensitive info that should not have been translated, Or binary files being treated as text. I would always much prefer the default to be no translations at all, ever! However Git chose otherwise.

So for my projects I always try to use LF only with no translation (even though G4w says it's not recommended - hehe). That involves

* Using editors that fully support LF on Windows - I've settled on VSCode with notepad++ as backup
* Use .editorconfig to set LF EOLs - code now uses this - it took them a while
* Stop git doing ANY conversion on check in and check out - this HAS to be done per project as user config is unknown and I mostly work on collaborative or OSS projects.
* Use .gitattributes to turn off text processing for all files "* -text". I tried all sorts of variations but it became much too painful to manage, and this also forces no translations.
 
As an aside, for build I mostly use npm scripts with attention to portability (a pain as npm always runs cmd when on windows even if you run npm form a bash). I still use good old Make when I want proper dependency checking and minimal build.

I keep meaning to seriously try WSL on Windows (it's actually the 3rd attempt to do such a thing, but MS gloss over the previous attempts), However, I'm very happy with the POSIX cmd line support in G4W and WSL is slower and also links/JUNCTIONS do(did) not work properly which is sometimes an issue.

I hope that helps - my approach is pretty hardcore I guess but it works for me; usually :)

PS it appears the Notepad LF fix may not allow the CREATION of new files with LF - at least from the descriptions I have seen and I could not find a way to do so after a quick test.

**Comment by SteveALee** [comment]
Oops I didn't answer your question

> Git would "suggest" .gitattributes when you add new files, based on extensions or other auto-detection, I guess. What's your take on this?

That sounds too complex and likely to go wrong. Perhaps a general suggestion during install? Defo worth saying that you should set at project level for shared dev projects. 

BTW I found locating where some of the defaults are set in G4W to be confusing as they are do not in the system git config file and seem to be set elsewhere (registry?) not described in the official git docs.

**Comment by dscho** [comment]
Closing this now-stale ticket.
