### ISSUE TITLE
[minor] Catch 22 when using code as editor

### ISSUE THREAD

**Issue by SteveALee** [git-for-windows/git#1702]
I was just setting up a new dev machine and found selecting Code as editor was a bit tricky. 

I installed G4W 1st and the install code option was disabled so I used the useful link to install Code. Code then wanted to install git! :) So  exited code and tried to select it in the got installer, even going back a step 1st, but it remained disabled. I had to exit the G4W installer and start again in order to select Code.

**Comment by dscho** [comment]
I think @izdwuut fixed this for you in https://github.com/git-for-windows/build-extra/pull/187
