### ISSUE TITLE
Unable to access 'https://github.com/xxx/xxx.git/': SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by glienard** [git-for-windows/git#1703]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.48]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

It always worked properly until it started after upgrading to the latest version of Microsoft Visual Studio Professional 2017 15.7.2

I've tried following solution I've found on the internet:
1. http.sslVerify=false
2. I've added the github.com certificate to the ca-bundle.crt.
3. I uninstalled VS and reinstalled it.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Microsoft Visual Studio Professional 2017 15.7.2

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
On my desktop at home, I always get when fetching, syncing, ... it always gives 
Error encountered while fetching: Git failed with a fatal error.
unable to access 'https://github.com/xxx/xxx.git/': SSL certificate problem: self signed certificate in certificate chain

On my desktop at work, I do not have any problems.


```
 - What did you expect to occur after running these commands?

to continue

 - What actually happened instead?

Error encountered while fetching: Git failed with a fatal error.
unable to access 'https://github.com/xxx/xxx.git/': SSL certificate problem: self signed certificate in certificate chain

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It's not a public one. Problem is not related to the repository as I can use it at the office with another desktop (and other people as well). At the office I'm still using VS 15.5.x as I do not want to get stuck there as well.

**Comment by shiftkey** [comment]
@glienard do you have any anti-virus software running on the problem machine? We've had some reports of Kaspersky introducing certificates that aren't actually trusted.

To check this, run this command in Git Bash and see what certificates are in the chain:

```
openssl s_client -showcerts -connect github.com:443
```

More details and a workaround are listed here: https://github.community/t5/How-to-use-Git-and-GitHub/Getting-quot-SSL-certificate-problem-self-signed-certificate-in/m-p/7953#M2731

**Comment by glienard** [comment]
@shiftkey I indeed run Kaspersky on both desktops. I've exited Kaspersky on the problem desktop and it is syncing and running as normal.  I'll look into to issue as you've mentionned. Thanks for putting me in the right direction!
