### ISSUE TITLE
Error when creating repo on GFS2 volume through SAMBA

### ISSUE THREAD

**Issue by ITSStorageTeam** [git-for-windows/git#1706]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Tested with both.
```
$ git --version --build-options
git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10; 64-Bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

## Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init
```
 - What did you expect to occur after running these commands?

Expected the repo to be created.

 - What actually happened instead?

Received the following error: 

error: chmod on //company.net/ndrive/Project/11112_Power_Processing_Testing/NV1/DATA/Jeff_Testing/.git/config.lock failed: Permission denied
fatal: could not set 'core.filemode' to 'false'

**Comment by dscho** [comment]
Can you see via ProcMon what the actual failing call is, and what the actual error value is?

**Comment by ITSStorageTeam** [comment]
Hard to say. A single 'git init' generates about 3,500 events.

**Comment by ITSStorageTeam** [comment]
I can see that the difference between a successful init- one done as a the owner of the directory- and an unsuccessful init- one done as anyone other than that owner- is three ACCESS DENIED messages.

Date & Time:	6/18/2018 3:21:23 PM
Event Class:	File System
Operation:	SetBasicInformationFile
Result:	ACCESS DENIED
Path:	\\company.net\ndrive\Project\11112_Power_Processing_Testing\Site1\SASDATA\Bob_Testing\.git\config
TID:	19616
Duration:	0.0008806
CreationTime:	0
LastAccessTime:	0
LastWriteTime:	0
ChangeTime:	0
FileAttributes:	AN

Date & Time:	6/18/2018 3:21:23 PM
Event Class:	File System
Operation:	SetBasicInformationFile
Result:	ACCESS DENIED
Path:	\\company.net\ndrive\Project\11112_Power_Processing_Testing\Site1\SASDATA\Bob_Testing\.git\config.lock
TID:	19616
Duration:	0.0009998
CreationTime:	0
LastAccessTime:	0
LastWriteTime:	0
ChangeTime:	0
FileAttributes:	AN


Date & Time:	6/18/2018 3:21:23 PM
Event Class:	File System
Operation:	SetBasicInformationFile
Result:	ACCESS DENIED
Path:	\\company.net\ndrive\Project\11112_Power_Processing_Testing\Site1\SASDATA\Bob_Testing\.git\config.lock
TID:	19616
Duration:	0.0015226
CreationTime:	0
LastAccessTime:	0
LastWriteTime:	0
ChangeTime:	0
FileAttributes:	AN

That's all.

**Comment by dscho** [comment]
I vaguely recall that Samba emulates the ACLs with POSIX extended attributes... maybe that's it? I am at my wit's end here...

**Comment by ITSStorageTeam** [comment]
Thanks. Anyone else? Anyone? Bueller?

**Comment by dscho** [comment]
Okay, I'll call it quits on this ticket. Until the day somebody comes up with a splendid plan to support this use case, Git for Windows simply won't handle this correctly.
