### ISSUE TITLE
Very slow Bash shell execution

### ISSUE THREAD

**Issue by oldpink** [git-for-windows/git#1707]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

PortableGit-2.7.0-64-bit.7z.exe
64-bit

```
$ git --version --build-options

git version 2.7.0.windows.1

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Portable version, so there is no install-options.txt.

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Trying to use this on a computer on which I have no administrator access at all, so it's possible that that is hindering my ability to correct the issue, and it's also possible that there is some antivirus or other software that is part of the problem, but I'm unsure about that.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Primarily running CMD to open command line, then starting Bash from there, but also tried to see if directly starting Bash would help with the issue, but that didn't solve it.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I'm not using the Git command all, but instead running several custom Bash shell scripts to execute several commands to process text files.
The programs being used in the scripts include Bash (obviously), along with the following:
grep
cut
sed
uname
cp
mv
rm
mkdir
sleep
cat
date

I have been using these scripts with a combination of Win-Bash (very old 1.x Bash ported to WIndows) and UnxUtils for the better part of a year now on the same computer, but I haven't been entirely satisfied with this arrangement, with the scripts taking just over four minutes to complete processing the text.
I had hoped to upgrade to a 64-bit Bash (Win-Bash is a 32-bit shell), plus I wanted a much more current Bash version, preferably 4.x.
I tried running the exact same scripts with the Bash that comes packaged with this version of Git for Windows, and while it worked, it took over double the time to complete the exact same operations as with Win-Bash, just short of ten minutes total.
Using the Git for Windows Bash, I tried this using the 64-bit external programs (grep, sed, etc.) that came packaged with this version of Git for Windows, then tried again, this time using the mix of 32-bit and 64-bit external programs that came with UnxUtils, but there was no significant difference either way.

I also should mention that I cannot use any version of Git for Windows newer than this on on this particular system because I get multiple errors, as follows:

0 [main] bash 10560 fork: child 9096 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
1310514 [main] bash 10560 fork: child 10576 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
3596535 [main] bash 10560 fork: child 6316 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
7871298 [main] bash 10560 fork: child 12564 - died waiting for dll loading, errno 11
bash: fork: retry: Resource temporarily unavailable
16156852 [main] bash 10560 fork: child 5456 - died waiting for dll loading, errno 11
bash: fork: Resource temporarily unavailable

I'm sure that the limitation of how my system is configured that prevents using anything newer than version 2.7.0 of Git for Windows is part of what makes it so slow to run my scripts, but I wouldn't have the first idea what that might be or how to fix it.

```
 - What did you expect to occur after running these commands?

I was hoping that it would run my shell scripts at least as quickly (really hoping for it to be much quicker, actually) as the scripts run with the combination of Win-Bash and UnxUtils (approximately 4.5 minutes), but when using the version of Bash that comes packaged with this Git for Windows, it takes just over twice as long to get the same process.

 - What actually happened instead?

The scripts went from about 4.5 minutes to process to just short of 10 minutes to process the exact same scripts and data.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A (I have no need for the Git command itself on this system)

I really appreciate that there are altruistic programmers willing to maintain this software, so I don't want to sound like an ingrate.
I'm just looking for a better solution than I'm currently using.

**Comment by larsxschneider** [comment]
👋 @oldpink ! `2.7.0.windows.1` is pretty old. Have you tried a more recent version like 2.17.1?

**Comment by oldpink** [comment]
Thanks for the reply, Lars.
You probably missed it, but I am using 2.7.0 because I cannot use anything newer on my system, specifically because of the multiple errors about "child xxx  - died waiting for dll loading, errno 11"
Since the somewhat older version of Git for Windows that I'm using is able to produce output identical to the ramshackle combination of Win-Bash and UnxUtils, I'm pretty sure that a newer version of Git for Windows would be any quicker, which is moot anyway, because it's impossible for me to find out because of whatever conflicts are in those error messages.

**Comment by larsxschneider** [comment]
Oh. I am sorry, I indeed missed that!

Do you have [Comodo Antivirus](https://stackoverflow.com/questions/37263702/cant-start-git-bash) or another Antivirus app running?

**Comment by oldpink** [comment]
I'm pretty sure I have an antivirus program running, more than likely Norton, but to be honest, I'm unsure what, if any, it could be.
TBH, I don't really know how to find a specific antivirus program, although it's trivial in Linux.
I'm not really a Windows guy, although I'm an intermediate level Linux user, since that's what I've been using for approaching thirty years straight now.
