### ISSUE TITLE
git checkout fails when switching to branch with a commit that renames folders to different casing

### ISSUE THREAD

**Issue by k15tfu** [git-for-windows/git#1709]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.461]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

core.ignorecase=false

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

The following fails on Windows:
```
test_dir> git clone https://github.com/k15tfu/git-rename-on-windows.git -b feature_branch
test_dir>cd git-rename-on-windows
test_dir\git-rename-on-windows>git config --local core.ignorecase false
test_dir\git-rename-on-windows>git checkout origin/refactor_branch
error: The following untracked working tree files would be overwritten by checkout:
        src/Impl/test_file
Please move or remove them before you switch branches.
Aborting
```

But it works on Linux.

**Comment by drizzd** [comment]
Git sets `core.ignorecase` in order to deal with case insensitive file systems. If you disable it, you should expect to run into such issues. I don't think it makes sense for Git to support case sensitivity on case insensitive file systems.

**Comment by PhilipOakley** [comment]
I suspect that this is/maybe slightly more complicated and maybe an multi-user issue where @k15tfu is suffering from being presented with a repo from someone elese that embeds the case change and is now a little stuck. However I can't be sure about that. 

The original point is true. Don't mess with ignorecase. 

Perhaps if @k15tfu explained the backgound to the case change (of the folder) that may clarify what the appropriate recovery action should/could be (if more than the existing fix is needed..)

**Comment by k15tfu** [comment]
You got it right. Okay, I understood that your point is to set ignorecase=true on Windows always.
