### ISSUE TITLE
DeleteCredentials issue since v2.17

### ISSUE THREAD

**Issue by JoshSchreuder** [git-for-windows/git#1711]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.81]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
Using Sourcetree 2.6.3
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
CMD (cmder)
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push --set-upstream origin foo
```
 - What did you expect to occur after running these commands?

```
Pushed to remote
```

 - What actually happened instead?

```
Pushed to remote worked.
Before pushing, console has error message

fatal: TypeLoadException encountered.
   Method 'DeleteCredentials' in type 'Atlassian.Bitbucket.Authentication.Authentication' from assembly 'Bitbucket.Authentication, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
fatal: TypeLoadException encountered.
   Method 'DeleteCredentials' in type 'Atlassian.Bitbucket.Authentication.Authentication' from assembly 'Bitbucket.Authentication, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

```
Occurs with all repositories
```

Seems others are experiencing this issue:
https://stackoverflow.com/questions/50708020/tfs-git-repository-asking-constantly-for-credentials-on-windows-command-prompt

It is not clear to me whether this is a problem with Sourcetree, Git For Windows or Git Credential Manager.

**Comment by Imi3est** [comment]
Same problem with git version 2.17.1.windows.2.   With 2.17.0 I haven't got this error. Same error with 32 and 64 bit git.  I have sourcetree installed but I don't use it.

**Comment by whoisj** [comment]
This one is **my** fault.

See: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/651

I'll have a fix out asap.

**Comment by whoisj** [comment]
This issue was fixed yesterday, and an update was releases last night.

@dscho is that enough to close this issue?

**Comment by dscho** [comment]
> @dscho is that enough to close this issue?

Yes, I think so ;-) Thank you so much for all your hard work!
