### ISSUE TITLE
ArgumentOutOfRangeException when trying to login to atlassian repo with CredentialManager

### ISSUE THREAD

**Issue by CorvusGloomMin** [git-for-windows/git#1712]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.17.1.2-64-bit

```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10, 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.431]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?


```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
All repositories are on a Atlassian Bitbucket account:

git clone ...
git submodule update --init
```
 - What did you expect to occur after running these commands?

Being logged in properly and continuing the command as expected

 - What actually happened instead?

When trying to enter my credentials using the credentials manager, as soon as I entered them and clicked login I get an ArgumentOutOfRangeException.
When I tried it on a "git submodule update --init" command, I also received the following immediately after:
bash: /dev/tty: No such a device or address
after which the bash just halts.

It works on 2.16.2-64bit.
I did notice a different login screen on 2.17.1.2-64bit for atlassian, might be related?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

On all my bitbucket repositories.

**Comment by whoisj** [comment]
Please see https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/651 as the cause was in the Git Credential Manager for Windows (aka GCM) utility. A fix has already been released, and is available on the GCM GitHub page.

**Comment by CorvusGloomMin** [comment]
Seems to be ok.
