### ISSUE TITLE
github: error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

### ISSUE THREAD

**Issue by martin-frydl** [git-for-windows/git#1713]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash or cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://github.com/MyGet/webhooks-sign-package.git
```
 - What did you expect to occur after running these commands?

repository clone

 - What actually happened instead?

Cloning into 'webhooks-sign-package'...
fatal: unable to access 'https://github.com/MyGet/webhooks-sign-package.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/MyGet/webhooks-sign-package.git/

 - I found somewhere it might be problem of OpenSSL 1.0 but I don't know how to downgrade it for git
 - I've also run it with more logging:
```
$ GIT_CURL_VERBOSE=1 git clone https://github.com/MyGet/webhooks-sign-package.git
Cloning into 'webhooks-sign-package'...
* Couldn't find host github.com in the _netrc file; using defaults
*   Trying 192.30.253.113...
* TCP_NODELAY set
* Connected to github.com (192.30.253.113) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied
* stopped the pause stream!
* Closing connection 0
fatal: unable to access 'https://github.com/MyGet/webhooks-sign-package.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied
```

**Comment by drizzd** [comment]
Can you show us the output of `git config -l`, please? I can reproduce if I do this:

```
git config --global --add http.sslVersion tlsv1.1
```

**Comment by martin-frydl** [comment]
```
c:\devel>git config -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
```
Are you sure you can reproduce the problem with that http.sslVersion? Because when I set exactly the same version, I get different one:
```
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```
It is still SSL23_GET_SERVER_HELLO:tlsv1 alert, but different one - protocol version, while mine is access denied.

**Comment by drizzd** [comment]
Right, my bad.

I don't know if it helps but you can install msys2, then install git-for-windows as an msys2 package:
https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

This way you could at least play with installing different openssl versions. Or maybe you go right for the Git-for-Windows SDK, which should give you a similar environment:
https://gitforwindows.org/#contribute

**Comment by tlkchew** [comment]
same error hmm ssl 1.0+ bug?  camping for solution..

**Comment by martin-frydl** [comment]
I've finally found the cause - proxy. Connections outside company network are blocked and must go though proxy. I have default windows proxy set but git does not use it. I have to manually set the proxy via "git config --global http.https://github.com.proxy http://host:port". Unfortunately the error message is so cryptic that I was not able to see the cause.
