### ISSUE TITLE
How to use Git Windows Minimal in Windows application?

### ISSUE THREAD

**Issue by viveknuna** [git-for-windows/git#1714]
I want to use https://www.nuget.org/packages/Git-Windows-Minimal/2.17.1.2 in C# windows application. I installed it using Install-Package Git-Windows-Minimal -Version 2.17.1.2 command. But I am not able to use it. Could you please provide the steps that how it can be used in C# code?

I'm trying to use this because I want to make a windows application (windows form like a calculator application in windows) in which I want to run different -different git commands and gives its output to the user. I will give this windows application to many users. The user should able to run this application and get the output on a machine which even does not have git install on his machine.

You can follow my [post](https://stackoverflow.com/questions/50770926/how-do-i-see-the-no-of-lines-added-modified-and-deleted-between-two-sprints-in/50790098?noredirect=1#comment88588043_50790098)

Version: 2.17.1.2
Visual Studio: 15.6.6

**Comment by whoisj** [comment]
@viveknuna the best way is to just use `System.Diagnostics.Process` to create git.exe processes. Unless you understand environment cooking (, etc.) I recommend that you just use the `cmd/git.exe` as the executable.

**Comment by dscho** [comment]
No response means the problem is resolved, right?
