### ISSUE TITLE
head and HEAD case sensitivity issue when using worktrees

### ISSUE THREAD

**Issue by kevin-david** [git-for-windows/git#1716]
### Setup

Git installed with default options:

```
kedavid@KEDAVID-DEV [D:\VSO_3\src] [teams/vcfp/kedavid/lazy_perf]
> git --version --build-options
git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```
Windows: `Microsoft Windows [Version 10.0.17134.48]`

### Repro

 - Shell: PowerShell

 - What commands did you run to trigger this issue?
1. clone repo
2. create 2nd worktree of repo
3. checkout new branch with different commit in worktreee

Inside the worktree: 
```
kedavid@KEDAVID-DEV [D:\VSO_3\src] [teams/vcfp/kedavid/lazy_perf]
> git rev-parse HEAD
d1cb860e145c40cc48e84d9cdf7eaa0845181578
kedavid@KEDAVID-DEV [D:\VSO_3\src] [teams/vcfp/kedavid/lazy_perf]
> git rev-parse head
6c8cd36dbe8b0442ac9d8f2735da7d48573f0a13
```

Original repo:
```
kedavid@KEDAVID-DEV [D:\VSO\src] [cvs_signing]
> git rev-parse head
6c8cd36dbe8b0442ac9d8f2735da7d48573f0a13
kedavid@KEDAVID-DEV [D:\VSO\src] [cvs_signing]
> git rev-parse HEAD
6c8cd36dbe8b0442ac9d8f2735da7d48573f0a13
```

### Problem

`head` points to the "original" repo's `HEAD`. `HEAD` works properly everywhere.

**Comment by derrickstolee** [comment]
Thanks for the report, @kevin-david! I'll get started on this today.

**Comment by derrickstolee** [comment]
The following test (when added to `t2025-worktree-add.sh`) demonstrates this bug:

```
test_expect_success '"HEAD" and "head" resolve to same ref' '
	git worktree add -b newhead headtest master &&
	(
		cd headtest &&
		test_commit advance &&
		git rev-parse HEAD >expect &&
		git rev-parse head >actual &&
		test_cmp expect actual
	)
'
```

**Comment by dscho** [comment]
I started work on this, too, in a different context (deny access via short names). @derrickstolee let's coordinate via Skype?

**Comment by dscho** [comment]
Should we just punt on this, @derrickstolee, and claim that this is not Windows-specific?

**Comment by dscho** [comment]
Closing this as stale.
