### ISSUE TITLE
warning: failed to restrict file handles (2)

### ISSUE THREAD

**Issue by dsopata** [git-for-windows/git#1717]
warning: failed to restrict file handles (2)

handle #0: 0000000000000008 (type 2, handle info (1) 7fff
handle #1: 000000000000011c (type 2, handle info (1) 1
handle #2: 0000000000000150 (type 2, handle info (1) 1

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.16.2.windows.1
cpu: x86_64
built from commit: ****
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.192]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 GIT BASH, CMD, command line integrated in PHP STORM

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
```

**Comment by rimrul** [comment]
This has been fixed in 2.17.0 (released on April 3rd 2018).  please try the [current release](https://github.com/git-for-windows/git/releases/latest) to see if that fixes your issue.

**Comment by dsopata** [comment]
GIT has been updated, hope it won't happen again. Thank you for your support.

**Comment by dscho** [comment]
> GIT has been updated, hope it won't happen again. Thank you for your support.

I take that as a "Thank you for your help, I will try to be an active Open Source community member and do my share to help in the future."
