### ISSUE TITLE
Latest Pre-Release Installer excluded libpcre2-8-0.dll for some reason.

### ISSUE THREAD

**Issue by AraHaan** [git-for-windows/git#1718]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
32 bit version of the latest pre-release.

```
$ git --version --build-options

Cannot, installer seems to have excluded libpcre2-8-0.dll.
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No idea.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git, and anything in it.
```
 - What did you expect to occur after running these commands?

git to run normally.

 - What actually happened instead?

The installer seems to have somehow excluded the libpcre2-8-0.dll file.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Issue is related to the installer.

**Comment by resb53** [comment]
I'm still getting this problem, using the default options (Other than Visual Studio Code as the default editor) with the v2.18.0-rc1.windows.2 installer package.

Windows 10 Home (64-bit)

**Comment by zouhair** [comment]
Same here, happens at the end of installation:

```
---------------------------
git.exe - System Error
---------------------------
The code execution cannot proceed because libpcre2-8-0.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```
After installation the git binary is installed but give this error when run:

```
$ /cygdrive/c/Program\ Files/Git/bin/git.exe
C:/Program Files/Git/bin/git.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by dscho** [comment]
This is fixed in https://github.com/git-for-windows/git/releases/tag/v2.18.0-rc1.windows.3

**Comment by AraHaan** [comment]
thanks

**Comment by resb53** [comment]
Worked a charm, thanks.

**Comment by rimrul** [comment]
Seems like it's fixed indeed. Ignore my comments on 80b62d5b6859

**Comment by dscho** [comment]
No worries, and thanks for reporting, y'all!
