### ISSUE TITLE
git gui is launched in foreground

### ISSUE THREAD

**Issue by gix** [git-for-windows/git#172]
Executing "git gui" in a cmd.exe shell launches it in the foreground and blocks the shell until the gui is closed. This was not the case with msysgit 1.9.5 and earlier where it was launched in the background. (I found a very old feature request for background launching from 2008 so it seems this wasn't always the case).

**Comment by dscho** [comment]
I guess that we need to re-introduce this behavior, indeed. I actually found it nicer for scripting, but you are correct that it would be a regression.

It is *hopefully* as easy as https://github.com/dscho/git/compare/git-for-windows:master...git-gui-wrapper, but I have no opportunity to test this for a week or so. Maybe you want to give it a try ([this wiki page](https://github.com/git-for-windows/git/wiki/Building-Git) will come in handy)?

**Comment by gix** [comment]
It took me a while to figure out where the cmd-wrappers are built. As just building an installer or portable archive as described in the wiki pulls them from the sdk-installation without updating, and running the packaging scripts in MINGW-packages/mingw-w64-git pulls a tagged version from your github repo. Is there a way to build/test these wrappers standalone? I hacked around it by changing the pull-url to the local file system.

Anyway, the branch checking for git-gui is the wrong one (the git-gui.exe has Windows subsystem and doesn't block). This patch works for me: https://github.com/gix/git/compare/git-for-windows:master...git-gui-wrapper

**Comment by dscho** [comment]
@gix I tried to improve the documentation a bit (since the wrappers are built as part of the MinGW Git package, I added the new section to the wiki page about package management). Feel free to improve it more, it's a wiki.
