### ISSUE TITLE
"Not a gitflow-enabled repo yet. Please run 'git flow init' first." error message on newly git flow init'ed repo.

### ISSUE THREAD

**Issue by silasfn** [git-for-windows/git#1720]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit

```
$ git --version --build-options
git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.1] - 64 bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$  cat /etc/install-options.txt
Editor Option: Notepad++
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash, on MINGW64

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
## (on newly installed Git for Windows)
cd ~
# git clone any repo - eg:
git clone --recursive git://github.com/petervanderdoes/gitflow.git
cd gitflow
git checkout master
git checkout develop
git flow init

Which branch should be used for bringing forth production releases?
   - develop
   - master
Branch name for production releases: [master]

Which branch should be used for integration of the "next release"?
   - develop
Branch name for "next release" development: [develop]

How to name your supporting branch prefixes?
Feature branches? [feature/]
Bugfix branches? [bugfix/]
Release branches? [release/]
Hotfix branches? [hotfix/]
Support branches? [support/]
Version tag prefix? []
Hooks and filters directory? [(path/to)/gitflow/.git/hooks]

git flow feature start abc-123
Fatal: Not a gitflow-enabled repo yet. Please run 'git flow init' first.


```
 - What did you expect to occur after running these commands?
After running git flow init, I expected git flow feature start to create a feature branch

 - What actually happened instead?
I got this error message:
Fatal: Not a gitflow-enabled repo yet. Please run 'git flow init' first.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Seems to occur on any git repository I have cloned, including
git clone --recursive git://github.com/petervanderdoes/gitflow.git

**Comment by shiftkey** [comment]
I'd recommend reporting this to the `git-flow` project to see if they can help with troubleshooting why initialising isn't working: https://github.com/petervanderdoes/gitflow-avh

**Comment by silasfn** [comment]
Thanks Brendan. Have reposted the issue at: https://github.com/petervanderdoes/gitflow-avh/issues/372

**Comment by dscho** [comment]
It was my understanding that not only the original git-flow project, but also the -avh fork were abandoned by their maintainers.

If your shell-scripting fu is up to par, maybe you want ho debug this further? If you come up with a patch, I am willing to work around the absence of git-flow maintenance by taking out-of-band contributions (I would start a fork of git-flow-avh in the git-for-windows org to that end).

If it was me, I would start by editing `C:\Program Files\Git\usr\bin\git-flow` (as admin because that file is write-protected) and insert `set -x` after the first line, the run the command again and try to match the command trace against the `git-flow` script to figure out where the bug comes from.

**Comment by silasfn** [comment]
Thanks Johannes. I was able to debug using the `set -x` flag.
In file C:\Program Files\Git\usr\bin\gitflow-common
Need to add a `!` just before `$(git config --get-regexp gitflow.prefix >/dev/null 2>&1)` ... ie change to this around line 297
```
gitflow_is_initialized() {
	gitflow_has_master_configured                    && \
	gitflow_has_develop_configured                   && \
	[ "$(git config --get gitflow.branch.master)" != "$(git config --get gitflow.branch.develop)" ] && \
	! $(git config --get-regexp gitflow.prefix >/dev/null 2>&1)
}
```
My limited tests seem to work - git flow feature start test succeeded after that change, and returned an error after I removed the "gitflow.prefix" lines from my .git/config file (expected behaviour).

If you fork the branch, I'll submit a pull request ... or you can apply the above change after you fork.

**Comment by silasfn** [comment]
Pull request here: https://github.com/petervanderdoes/gitflow-avh/pull/374

**Comment by dscho** [comment]
> My limited tests seem to work - git flow feature start test succeeded after that change, and returned an error after I removed the "gitflow.prefix" lines from my .git/config file (expected behaviour).

Wait, I don't understand.

```sh
$ git config --get-regexp gitflow.prefix

$ echo $?
1
```

So I am missing gitflow.prefix, and the `git config` call fails. If I call the same command with an existing config setting, it succeeds.

Ah. I think I know what it is. Does it work if you remove the `$(...)` parentheses, i.e.

```sh
gitflow_is_initialized() {
	gitflow_has_master_configured                    && \
	gitflow_has_develop_configured                   && \
	[ "$(git config --get gitflow.branch.master)" != "$(git config --get gitflow.branch.develop)" ] && \
	git config --get-regexp gitflow.prefix >/dev/null 2>&1
}
```

?
