### ISSUE TITLE
Move Visual Studio projects and/or binaries into subdirectory without name clash?

### ISSUE THREAD

**Issue by mehrdadn** [git-for-windows/git#1722]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Is there any chance the Visual Studio project directories could be moved down into some subdirectory without a name clash (like into `vsprojects/`)? The problem is that currently there are tons of name clashes between files and directories (e.g. `git/` conflicts with `git.exe`) which prevents the system from being able to correctly find commands by their names in the `PATH`. In addition, the direct clash makes it impossible to do a regular Linux build too, which is unfortunate because I find it useful to use `git-for-windows` in WSL.

Another approach (which can be done in lieu or in combination) is to change the _output_ directory so that the executables are somewhere else (like `bin/{Win32,x64}/{Debug,Release}`). This might not be as easy though since now the associated scripts, templates, etc. will probably want to be moved too.

Thanks!

**Comment by mehrdadn** [comment]
I actually indeed did this for myself (at least for `vcxproj`, not `vcproj`), but if you recall we had a little roadbump with PRs coming from me... =P

**Comment by mehrdadn** [comment]
I would definitely recommend a subdirectory though, both because `.proj` is too vague (someone might want a project that isn't a Visual Studio project at some point, or might want to simultaneously have projects for multiple VS versions), and because it also keeps the root directory less cluttered.

**Comment by dscho** [comment]
Right, you did not want your real name and email address to show up in Git's commits... I remember now...

**Comment by PhilipOakley** [comment]
@mehrdadn You may be interested in the Git list discussion [thread ](https://public-inbox.org/git/20180417191549.GA1199@helen.PLASMA.Xg8.DE/) about the [potential] effects of the European GDPR on the retrospective anonymising of commit metadata in light of someone strongly (legally?) asserting their right to be forgotten, and that then conflicting with the legal need to have licence release evidence (GPL in this case). 

I can't say that it has been resolved cleanly - such is globalisation.

**Comment by dscho** [comment]
Closing due to the obvious lack of interest.
