### ISSUE TITLE
Cannot connect to host alias under .ssh/config

### ISSUE THREAD

**Issue by mlfz** [git-for-windows/git#1724]
I am getting a cannot connect error when I am using a Host alias in `.ssh/config`

Under git bash:
```
$ git clone git@github.com:git-for-windows/git.git --depth 10
Cloning into 'git'...
remote: Counting objects: 3710, done.
remote: Compressing objects: 100% (3141/3141), done.
remote: Total 3710 (delta 586), reused 2096 (delta 433), pack-reused 0
Receiving objects: 100% (3710/3710), 7.58 MiB | 6.72 MiB/s, done.
Resolving deltas: 100% (586/586), done.
Checking out files: 100% (3260/3260), done.
```
works

But 
```
$ git clone git@git4winOnGithub:git-for-windows/git.git--depth 10
Cloning into 'git'...
Unable to open connection:
Host does not exist fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
does not.

`git4winOnGithub` is a host alias I setup in `.ssh/config`:
```
Host git4winOnGithub
	HostName github.com
	IdentityFile ~/.ssh/git4win_id_rsa

Host anotherProjectOnGithub
	HostName github.com
	IdentityFile ~/.ssh/another_id_rsa
```
to use a specific identity.

Note that, ssh test works:
```
$ ssh -T git@git4winOnGithub
Hi mlfz! You've successfully authenticated, but GitHub does not provide shell access.
```
Or for that matter, calling `sh.exe` also works:
```
"C:\Program Files\Git\bin\sh.exe" -c "ssh -T git@git4winOnGithub"
Hi mlfz! You've successfully authenticated, but GitHub does not provide shell access.
```
But `git.exe` itself appears to not respect the ssh client config file.

I am using `git-for-windows/git` as an example here.  In our organization, we have a specific need in which we use a different identity for each GitHub projects under the organization.  Recently, some wants to be able to develop under Windows environment and this bug is a major inconvenient. 

EDIT1: Add git version
```
> git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

**Comment by dscho** [comment]
You could debug this further by setting the environment variable `GIT_SSH_COMMAND` to a Unix shell script (starting with `#!/bin/sh` or it won't be executable) that hands off to `ssh -v -v -v -v "$@"`.

Or maybe you already have a `core.sshCommand` that overrides your SSH? (Find out by setting `GIT_TRACE=1`)

**Comment by drizzd** [comment]
This is just a hunch, but I frequently have this issue with the default /etc/nsswitch.conf, because ssh will look for .ssh/config in the wrong directory. As a workaround I usually hard-code my home directory in /etc/nsswitch.conf:

```
#db_home: env windows cygwin desc
db_home: /c/Users/drizzd
```

Running ssh in verbose mode as suggested by dscho will usually reveal if ssh is looking in the wrong directory.

**Comment by mlfz** [comment]
Okay, I think I have figured out what's going on.  I was not actually using `ssh`. I was using putty:
```
C:\Users\dxj9413>echo %GIT_SSH%
C:\Program Files\PuTTY\plink.exe
```

**Comment by michaelblyons** [comment]
That "file handles" thing shows up in a couple other issues.
Can you update Git for Windows? See https://github.com/git-for-windows/git/issues/1686#issuecomment-390283460

**Comment by mlfz** [comment]
Updated:
```
> echo %GIT_SSH%
"C:\Program Files\Git\usr\bin"

>git clone git@git4winOnGithub:git-for-windows/git.git
Cloning into 'git'...
error: cannot spawn "C:\Program Files\Git\usr\bin": Invalid argument
error: cannot spawn "C:\Program Files\Git\usr\bin": Permission denied
fatal: unable to fork
```

But I have found that the correct solution to use the internal ssh client is simply to unset the `GIT_SSH` environment:
```
> echo %GIT_SSH%
%GIT_SSH%

> git clone git@git4winOnGithub:git-for-windows/git.git
Cloning into 'git'...
remote: Counting objects: 360904, done.
remote: Total 360904 (delta 0), reused 0 (delta 0), pack-reused 360903
Receiving objects: 100% (360904/360904), 118.15 MiB | 2.55 MiB/s, done.
...
```

Closing this issue. Because the real issues are:
1. Do not use plink if you intend to use `.ssh/config` read by internal ssh client.
2. Unset `%GIT_SSH%` to use the internal ssh client.

**Comment by dscho** [comment]
The real issue is that `GIT_SSH` should point to an SSH executable, not to a directory ;-)

**Comment by mlfz** [comment]
Sorry about that. Actually the same error if you point it to the executable:
```
>git clone git@git4winOnGithub:git-for-windows/git.git
Cloning into 'git'...
error: cannot spawn "C:\Program Files\Git\usr\bin\ssh.exe": Invalid argument
error: cannot spawn "C:\Program Files\Git\usr\bin\ssh.exe": Permission denied
fatal: unable to fork

>echo %GIT_SSH%
"C:\Program Files\Git\usr\bin\ssh.exe"
```

**Comment by dscho** [comment]
> > ```
> >echo %GIT_SSH%
> > "C:\Program Files\Git\usr\bin\ssh.exe"
> > ```
I would wager a bet that it works if the double quotes were removed.
