### ISSUE TITLE
$0 in commit message gets converted into the string /usr/bin/bash

### ISSUE THREAD

**Issue by john-pick** [git-for-windows/git#1728]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10, 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
 git commit -m "NR-9238: alert showing with $0 debt"
```
 - What did you expect to occur after running these commands?

[master 4171686d4] NR-9238: alert showing with $0 debt
 1 file changed, 1 insertion(+), 1 deletion(-)

 - What actually happened instead?

[master 4171686d4] NR-9238: alert showing with /usr/bin/bash debt
 1 file changed, 1 insertion(+), 1 deletion(-)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no

**Comment by dscho** [comment]
Congratulations on opening ticket number 12³!

In Bash, there are two ways of quoting things: with double quotes and with single quotes. The difference is that variables in double quotes are interpolated, e.g. `x=123; echo "$x"` will print `123`. In contrast, if zou write `x=123; echo '$x'`, it will print `$x`.

The special variable with name `0` is reserved for the currently executing program/script, which is exactly what you see here.

Short answer: you wanted to single quote instead of double quote the message:

```sh
git commit -m 'NR-9238: alert showing with $0 debt'
```
