### ISSUE TITLE
during download git-2.18.0-64-bit.exe download pauses at 15.7 0bs 

### ISSUE THREAD

**Issue by selfempmfer** [git-for-windows/git#1731]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```64-bit

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```10 64-bit
$ cmd.exe /c ver

** insert your machine's response here **
```Microsoft Windows [Version 10.0.15063]

 - What options did you set as part of the installation? Or did you choose the
   defaults?


# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **clicked download button
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?
I'm downloading and installing prerequisites for windows. To install mono-develope for unity3d ver 2017.3.1f1. git-2.18.0-64-bit.exe being one of the prerequisites. Each time i try the download from the site. The download stops at 15.7 mb at 0bs. Does not start downloading
** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **https://gitforwindows.org/

**Comment by thebtm** [comment]
I am also getting the same issue, then the download fails.

**Comment by dscho** [comment]
This probably was/is some Amazon S3 issue... not sure that we can do anything over here. You might want to contact GitHub Support if that happens again.
