### ISSUE TITLE
AppVeyor fails for Git 2.18

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#1732]
Looks like it misses the `mingw-w64-x86_64-pcre2` package. See https://ci.appveyor.com/project/dscho/git/build/1.0.1335 (for https://github.com/git-for-windows/git/pull/1666)

**Comment by dscho** [comment]
Thanks for the reminder, I meant to disable AppVeyor (it has too many limitations, for example: its timeout is too low to even start running the tests and sometimes even to complete the build).

Instead, I enabled Continuous Integration using Visual Studio Team Services, which has the added benefit of testing also on macOS and Linux (Git for Windows' Git fork is intended to funnel patches back upstream, so *all* contributions must work on all platforms supported by Git, not only on Windows). See e.g. https://git-for-windows.visualstudio.com/f3317b6a-fa67-40d4-9a33-b652e06943df/_build/index?buildId=11226
