### ISSUE TITLE
Installer doesn't detect Putty

### ISSUE THREAD

**Issue by hansfn** [git-for-windows/git#1734]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Trying to install Git-2.18.0-64-bit.exe on Windows 10, 64-bit, with Putty 0.70 for a colleague at work.

### Details

I'm expecting to be given the choice between OpenSSH and Putty (Plink) when installing, but the page is missing from the installer.

The installer doesn't detect Putty unless you [have created at least one session in Putty](https://github.com/git-for-windows/build-extra/blob/0dc6cb060bcf6cbb164da75be6f69585e83edb29/installer/install.iss#L1227). Since the default session doesn't exist in the registry, you actually have to create a session before installing Git for Windows (if you want to use Plink). My experience is that most (many?) people don't create sessions in Putty.

I'm suggestion that we change the check to `HKEY_CURRENT_USER\Software\SimonTatham\PuTTY` instead of `HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions`. If there are no objections I can provide a PR if needed. (The text in the installer needs to be changed slightly.)

**Comment by dscho** [comment]
This is actually by design. We had *so many* PuTTY problems and they ate up a substantial amount of time that we decided to deprecate PuTTY support and only offer it for users who already use PuTTY with success.

**Comment by dscho** [comment]
> I'm suggestion that we change the check to `HKEY_CURRENT_USER\Software\SimonTatham\PuTTY` instead of `HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions`. If there are no objections I can provide a PR if needed. (The text in the installer needs to be changed slightly.)

If this would help you, @hansfn, please fell very free to open that PR.

**Comment by dscho** [comment]
(To be clear: I do not want to put much effort into PuTTY support, but I am always open to merging PRs by people who do.)
