### ISSUE TITLE
less.exe shell commands are slow

### ISSUE THREAD

**Issue by EvgeniyZ** [git-for-windows/git#1738]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Monitor Dell P2214H
Laptop HP ProBook 650 G2 M2 SSD

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Cmder (Powershell)
ConEmu (Powershell)
git-bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status
git diff
git log --pretty=oneline --abbrev-commit --graph --decorate
```
 - What did you expect to occur after running these commands?

Response less than or around 1 second

 - What actually happened instead?

Often after run git status, git diff runs really slow (3 to 5 seconds)
Same for git log --pretty=oneline --abbrev-commit --graph --decorate
**less.exe** responsible for delays.
Delays occur when I plugged external monitor to my laptop via display port cable (P).
**Monitor is a main display**, laptop is secondary. When I'm working only on laptop and monitor is unplugged, git commands run fast enough.
Delays also occur when I **switch the focus back to shell** and pressing git status -> git diff. 
When I have a focus on shell git diff works fine. It's not depend on Cmder, ConEmu or Powershell. Same thing for git-bash.exe, cmd.exe
I saw some tickets about AMD graphics drivers, but I have Intel HD graphics drivers.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
No, repository size is not the case in this issue.

**Comment by chriscollinsboxuk** [comment]
I'm also seeing this.

**Comment by drizzd** [comment]
When you say git-bash, do you mean in conemu, or in mintty? I have experienced slow scrolling in less when using git-bash in conemu, but not in mintty.

**Comment by leonyu** [comment]
Try disable ConEmuHk/hook functionality. I have seen virus scanners trigger a scan when ConEmuHk injects itself into other programs.

**Comment by dscho** [comment]
I'll just go ahead and assume that @leonyu's suggestion was excellent because nobody bothered to answer (in my experience, many Git for Windows users simply do not answer any longer when their issues have been addressed, which is not ideal, but unfortunately the reality).

**Comment by chriscollinsboxuk** [comment]
I still have this problem - disabling the ConEmuHk injects causes problems, as detailed here: https://conemu.github.io/en/ConEmuHk.html . At this point, it may be that this is a ConEmu issue, rather than a Git For Windows one - I'm not sure.

**Comment by dscho** [comment]
> At this point, it may be that this is a ConEmu issue, rather than a Git For Windows one - I'm not sure.

I am not sure, either. I _am_ sure, however, that the frustrating lack of speed of this conversation (combined with the lack of feedback to e.g. [@drizzd's question over 1.5 years ago](https://github.com/git-for-windows/git/issues/1738#issuecomment-404948087)) will not be conducive to resolve anything, so I'll leave this ticket closed for now.
