### ISSUE TITLE
application terminates in unusual way on clone command with custom remote helper

### ISSUE THREAD

**Issue by SoftwareArchitec** [git-for-windows/git#1743]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone xxx://localhost/test1

BUG: refs/files-backend.c:2898: initial ref transaction called with existing refs

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Finisch import :

c:\Temp\git1\local2>git clone xxx://localhost/test1>>>>>>>>>> cmd::
BUG: refs/files-backend.c:2898: initial ref transaction called with existing refs# One of the following:
fatal: Too many arguments.
```
 - What did you expect to occur after running these commands?

clone should stop with error if somethind is broken. 
HINT: Init Repo, adding remote and fetch/pull works. 

 - What actually happened instead?

process is terminated unexpected.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
This ticket fell off the table, sorry for that.

I do have to point out that this is neither minimal nor complete, let alone verifiable an example. What gives?

**Comment by Abdulmanahtalib** [comment]
Tq
