### ISSUE TITLE
Remote Helper: Push with remote helper with export command only puhses last commit

### ISSUE THREAD

**Issue by SoftwareArchitec** [git-for-windows/git#1746]
- [x   ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

-

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd
sourcetree

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push origin master
```
 - What did you expect to occur after running these commands?

'git push origin master' calls my custom remote helper. Export command will be called and I take the stdout and use it for fast-import call on my remote. The data from stdout should contain all commits to push them on the remote.

 - What actually happened instead?

The data from stdout only contains the last commit since last push instead of containing all commits. The remote git throws warning `"warning: Not updating refs/heads/master (new tip 65c0a57f9ead7b487129f563ec847cd07e8644a4 does not contain f490d7250727508e68f4100ff10f29ff71d992be)"` and commit will not be pushed to remote git.
Commit "f490d7250727508e68f4100ff10f29ff71d992be" is a commit on the remote git.
Forcing is possible but older commits on the remote git will be removed.

Calling fast-export on the local git will show  all commits.

**Remote Helper Howto got from:**
[https://rovaughn.github.io/](https://rovaughn.github.io/)

**I implemented following capabilites:**
list, import, export, refspec

**stdout dump from export command called after "git push origin master":**
> "feature done\nblob\nmark :1\ndata 7\n3333333\nblob\nmark :2\ndata 7\nxxxxxxx\ncommit refs/heads/master\nmark :3\nauthor Gogs <gogs@fake.local> 1530623286 +0200\ncommitter Gogs <gogs@fake.local> 1530623286 +0200\ndata 8\nneuvon1\nM 100644 :1 POU.txt\nM 100644 :2 POU2.txt\n\ndone\n"

**fast-export dump from local git:**

> blob
> mark :1
> data 7
> 3333333
> blob
> mark :2
> data 7
> 1111111
> reset refs/heads/master
> commit refs/heads/master
> mark :3
> author Gogs <gogs@fake.local> 1530617189 +0200
> committer Gogs <gogs@fake.local> 1530617189 +0200
> data 9
> pou2 111
> M 100644 :1 POU.txt
> M 100644 :2 POU2.txt
> 
> blob
> mark :4
> data 7
> xxxxxxx
> commit refs/heads/master
> mark :5
> author Gogs <gogs@fake.local> 1530623286 +0200
> committer Gogs <gogs@fake.local> 1530623286 +0200
> data 8
> neuvon1
> from :3
> M 100644 :4 POU2.txt
> 
> reset refs/heads/master
> from :5

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Is this a Windows-specific problem?

If unsure, just go ahead and install [Ubuntu via the Windows Store](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6) (it will run as a Desktop app, no need to dual boot or something), and try it "on Linux".

**Comment by SoftwareArchitec** [comment]
I'm confused. It works if I use command #1 and then command #2. Pull works with "origin master"
#1 `git push origin /refs/MYREMOTE/origin/heads/master`
#2 `git push origin master`

Linux tests are note possible. Local remote helper and custom git server are based on c# at the moment. LAter the git server will be ported to linux.

**Comment by dscho** [comment]
> Linux tests are note possible.

I asked mainly if this `git fast-import` behavior is the same on Linux as on Windows because the Git for Windows project is awfully short on contributors, while the Git project enjoys an active community who might be able to help you, *iff* they can reproduce the problem on Linux, and *iff* you make a succinct, complete case to the [Git mailing list](mailto:git@vger.kernel.org). That would be your best chance to get help quickly.

**Comment by SoftwareArchitec** [comment]
If rather future I would fix bugs myself and pull them. Currently I'm very busy because of a deadline. First I will check if the testgit sample works with windows and linux. 

I added some logs from the git repos. Perhaps anyone has an idea how to fix.

---------------Log local before change

> 
> commit 580dfe4d7517f8beab9b9c6b0d569c075bf961ef (HEAD -> master, origin/master, refs/MYREMOTE/origin/heads/master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:48:06 2018 +0200
> 
>     22222222222222222222
> 
> commit 4cf00c4e3dc3d682f85b4edd43d4574021800790
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:42:53 2018 +0200
> 
>     kdkdkdkkdkdkdkd

---------------Log local after change and commit local

> 
> commit c01c23f650c770d41c90f7f2310fc43255185ebf (HEAD -> master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:49:49 2018 +0200
> 
>     newChange
> 
> commit 580dfe4d7517f8beab9b9c6b0d569c075bf961ef (origin/master, refs/MYREMOTE/origin/heads/master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:48:06 2018 +0200
> 
>     22222222222222222222
> 
> commit 4cf00c4e3dc3d682f85b4edd43d4574021800790
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:42:53 2018 +0200
> 
>     kdkdkdkkdkdkdkd

---------------Log of remote 

> 
> commit 580dfe4d7517f8beab9b9c6b0d569c075bf961ef (HEAD -> master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:48:06 2018 +0200
> 
>     22222222222222222222
> 
> commit 4cf00c4e3dc3d682f85b4edd43d4574021800790
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:42:53 2018 +0200
> 
>     kdkdkdkkdkdkdkd

	
---------------Log of local after push with "git push origin refs/MYREMOTE/origin/heads/master"

> 
> commit c01c23f650c770d41c90f7f2310fc43255185ebf (HEAD -> master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:49:49 2018 +0200
> 
>     newChange
> 
> commit 580dfe4d7517f8beab9b9c6b0d569c075bf961ef
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:48:06 2018 +0200
> 
>     22222222222222222222
> 
> commit 4cf00c4e3dc3d682f85b4edd43d4574021800790
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:42:53 2018 +0200
> 
>     kdkdkdkkdkdkdkd

	
---------------Log on remote git 

> 
> commit 580dfe4d7517f8beab9b9c6b0d569c075bf961ef (HEAD -> master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:48:06 2018 +0200
> 
>     22222222222222222222
> 
> commit 4cf00c4e3dc3d682f85b4edd43d4574021800790
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:42:53 2018 +0200
> 
>     kdkdkdkkdkdkdkd

	
---------------Git log local after "git push origin master"

> 
> commit c01c23f650c770d41c90f7f2310fc43255185ebf (HEAD -> master, origin/master, refs/MYREMOTE/origin/heads/master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:49:49 2018 +0200
> 
>     newChange
> 
> commit 580dfe4d7517f8beab9b9c6b0d569c075bf961ef
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:48:06 2018 +0200
> 
>     22222222222222222222
> 
> commit 4cf00c4e3dc3d682f85b4edd43d4574021800790
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:42:53 2018 +0200
> 
>     kdkdkdkkdkdkdkd

	
---------------Git log on remote 

> 
> commit c01c23f650c770d41c90f7f2310fc43255185ebf (HEAD -> master)
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:49:49 2018 +0200
> 
>     newChange
> 
> commit 580dfe4d7517f8beab9b9c6b0d569c075bf961ef
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:48:06 2018 +0200
> 
>     22222222222222222222
> 
> commit 4cf00c4e3dc3d682f85b4edd43d4574021800790
> Author: Gogs <gogs@fake.local>
> Date:   Wed Jul 4 15:42:53 2018 +0200
> 
>     kdkdkdkkdkdkdkd

**Comment by SoftwareArchitec** [comment]
@kgybels Yes you are right. git push should push only not pushed commits. But why do I get following error message if I call "fast-import" from "export" command of my remote helper?

> Not updating refs/heads/master (new tip cd02174d1bb640655219d8674b5f568aef5217bc does not contain 5715342b3285ce3de01d12063f8e5bf03fc6964d)'

**Comment by SoftwareArchitec** [comment]
I fixed my Problem, import-marks and export-marks commands were not implemented properly. These commands are needed to use incremental exports.
Without import-marks and export-marks you only can use force.

**Comment by kgybels** [comment]
@SoftwareArchitec Good to hear you we're able to resolve your problem. Thank you for closing the issue!
