### ISSUE TITLE
warning: failed to restrict file handles when file name without extension is the same as folder

### ISSUE THREAD

**Issue by twsouthwick** [git-for-windows/git#1749]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.112]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir test
cd test
git init
new-item test.something
git test.something
```
 - What did you expect to occur after running these commands?

```
git: '.\test1.something' is not a git command. See 'git --help'.
```

 - What actually happened instead?

```
$ git .\test1.something
warning: failed to restrict file handles (2)

handle #0: 000000000000004c (type 2, handle info (1) 7ffd
handle #1: 00000000000000f0 (type 2, handle info (1) 1
handle #2: 00000000000000f4 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: '.\test1.something' is not a git command. See 'git --help'.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Can reproduce with a brand new repo

**Comment by michaelblyons** [comment]
[Known issue.](https://github.com/git-for-windows/git/issues?utf8=%E2%9C%93&q=file+handles) Try upgrading to v2.17 or higher. =)

```sh
$ git update-git-for-windows
```
