### ISSUE TITLE
"git mv" behaves differently than "move" or manual explorer move

### ISSUE THREAD

**Issue by FeBe95** [git-for-windows/git#1750]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

## Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.17134.112]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

```

### Preconditions
Issue happens in all of my repos, local and remote. Also tested with a newly created repo being in a completely "clean" state.
Uninstalled my old git version (1.9) and installed the current version to ensure, it didn't get fixed in the meantime.

### Steps to reproduce
- create/add an example (text) file
- commit the new file to the repo
- manually rename and/or move the file using Windows Explorer or cmd's `move` command
- run `git status`
- revert changes
- rename and/or move the file using `git mv`
- run `git status`

### Expected results
Both status commands should output something like:
```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        renamed:    foo.txt -> bar.txt
```

### Actual results
First "git status" outputs:
```
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    foo.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        bar.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

### Side note
I am aware of the fact, that git doesn't actually track files. It compares the content of all changes to detect moved/renamed files. I've read in some discussions, that git should be able to detect these actions just fine regardless of the OS but in my case it isn't. Or am I getting something wrong here?

**Comment by dscho** [comment]
`git mv` does actually do *two* things. It moves/renames the file in the worktree (just like `move` or the Explorer do), *and then it moves/renames the file in the Git index*.

This is the difference. `git mv` works on two, separate (if related) "filesystems": the real file system, on disk (or SSD), and the virtual file system in the Git index.

So what you see is absolutely expected. Git won't guess whether you renamed a file, unless it considers both source and target as tracked.

If you call `git add bar.txt` in your example above (or more sloppily, but conveniently, `git add -A`), you will see it "fixed", as you now told Git to synchronize the index with what is on disk.

**Comment by shiftkey** [comment]
> Do you happen to know, if I can make this work directly in GitHub Desktop? 

GitHub Desktop follows what `git status` does, and we avoid staging before committing, so the same `git mv` or `git add -A` is required to get renames to show as you expect in the app.
