### ISSUE TITLE
Cherry-pick does not complain about unknown options

### ISSUE THREAD

**Issue by rybak** [git-for-windows/git#1751]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.112]
```

### Details

I was trying to cherry pick commit(s), while simultaneously changing the author. All commits in tests existed in repository (checked via `git branch -r --contains <commit>`).

```
git cherry-pick --author='TEST' <one-commit> # case 1
git cherry-pick --author='TEST' <commit1> <commit2>  # case 2
```

Unfortunately, `cherry-pick` doesn't have the same `--author` option as `git commit` does.

 - What did you expect to occur after running these commands?

    `git cherry-pick` to complain that it doesn't know `--author` option in both cases.

 - What actually happened instead?

    + For case 1:

          error: BUG: expected exactly one commit from walk
          fatal: cherry-pick failed

    + For case 2 cherry-pick silently did nothing and return code was zero.

**Comment by dscho** [comment]
On Sun, 8 Jul 2018, Andrei Rybak wrote:

> I was trying to cherry pick commit(s), while simultaneously changing the author. All commits in tests existed in repository (checked via `git branch -r --contains <commit>`).
> 
> ```
> git cherry-pick --author='TEST' <one-commit> # case 1
> git cherry-pick --author='TEST' <commit1> <commit2>  # case 2
> ```
> 
> Unfortunately, `cherry-pick` doesn't have the same `--author` option as `git commit` does.
> 
>  - What did you expect to occur after running these commands?
> 
>     `git cherry-pick` to complain that it doesn't know `--author` option in both cases.
> 
>  - What actually happened instead?
> 
>     + For case 1:
> 
>           error: BUG: expected exactly one commit from walk
>           fatal: cherry-pick failed
> 
>     + For case 2 cherry-pick silently did nothing and return code was zero.

That is the same behavior as on Linux (I just tested). Seeing as the Git
project is enjoying a whole lot more contributors than the Git for Windows
project, and as this is not a Windows-specific issue, I would like to
suggest sending this bug report to the [Git mailing
list](mailto:git@vger.kernel.org) (make sure to send only plain text, HTML
will be rejected unfortunately).

**Comment by asheiduk** [comment]
AFAICT `git cherry-pick` calls `git rev-list` with unknown options. So you can say

    	git cherry-pick --branches  --author $USER --grep "bla"

as long as it results in one commit.

You can find a hint for this reading `git help cherry-pick` and searching for `--stdin` -- this is only mentioned in the `EXAMPLES` section.
