### ISSUE TITLE
Unable to use Git over MITM HTTPS proxy

### ISSUE THREAD

**Issue by geordee** [git-for-windows/git#1752]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

 I went through issue #1453, and felt there was no resolution. There was a discussion on Bountysource which was abandoned as well. We face this issue behind our corporate firewall, while accessing Git on VSTS.

```
$ git clone https://<tenant>.visualstudio.com/<project>/_git/<git-repository>
Cloning into '<git-repository>'...
fatal: unable to access 'https://<tenant>.visualstudio.com/<project>/_git/<git-repository>': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt
  CApath: none
```

I have then moved to a network that does not require proxy and everything worked fine.

```
$ unset https_proxy
$ git clone https://<tenant>.visualstudio.com/<project>/_git/<git-repository>
Cloning into '<git-repository>'...
remote:
remote:                    vSTs
remote:                  vSTSVSTSv
remote:                vSTSVSTSVST
remote: VSTS         vSTSVSTSVSTSV
remote: VSTSVS     vSTSVSTSV STSVS
remote: VSTSVSTSvsTSVSTSVS   TSVST
remote: VS  tSVSTSVSTSv      STSVS
remote: VS   tSVSTSVST       SVSTS
remote: VS tSVSTSVSTSVSts    VSTSV
remote: VSTSVST    SVSTSVSTs VSTSV
remote: VSTSv        STSVSTSVSTSVS
remote:                VSTSVSTSVST
remote:                  VSTSVSTs
remote:                    VSTs    (TM)
remote:
remote:  Microsoft (R) Visual Studio (R) Team Services
remote:
remote: Found 788 objects to send. (157 ms)
Receiving objects: 100% (788/788), 177.45 KiB | 644.00 KiB/s, done.
Resolving deltas: 100% (267/267), done.
$
```

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

 64-bit

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:

$ cat /etc/install-options.txt
Editor Option: VisualStudioCode
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I had 2.13.x and my colleauges had 2.16.x. I was able to work with version 2.13, while they were not able clone/fetch/pull/push.

To test the observation, I have upgraded to 2.18, and now Git does not work over HTTPS proxy.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git clone https://<tenant>.visualstudio.com/<project>/_git/<git-repository>
Cloning into '<git-repository>'...
fatal: unable to access 'https://<tenant>.visualstudio.com/<project>/_git/<git-repository>': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt
  CApath: none
```

 - What did you expect to occur after running these commands?

I expecte Git to clone the repository in my laptop

 - What actually happened instead?

It gave me a certificate error

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It happens for all repositories over HTTPS. It does not happen for repositories over HTTP. It does not happen for repositories over SSH. (I tested using a local Gitlab server over HTTP/HTTPS/SSH.)

**Comment by dscho** [comment]
Probably this proxy has its own certificate that is not recognized by any of OpenSSL's root certificates in C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt

There should be plenty of documentation out there how to add a custom certificate to that bundle...

**Comment by geordee** [comment]
Here is what I have tried.

I have obtained the root certificate the proxy requires Base64 encoded. I decided update the ca-bundle.crt since there shouldn't be anything else in between.

Since the certificate is self-signed, I have set the environment variable GIT_SSL_NO_VERIFY to true.

```
$ cd /c/Program\ Files/Git/mingw64/ssl/certs/
/c/Program Files/Git/mingw64/ssl/certs $ code ca-bundle.crt
/c/Program Files/Git/mingw64/ssl/certs $ cd /d/Code/test/
/d/Code/test $ export GIT_SSL_NO_VERIFY=true
/d/Code/test $ git clone https://<tenant>.visualstudio.com/<project>/_git/<git-repository>
Cloning into '<git-repository>'...
fatal: unable to access 'https://<tenant>.visualstudio.com/<project>/_git/<git-repository>/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt
  CApath: none
```

I exited from the Git Bash session, and tried again.

```
/d/Code/test $ exit
/d/Code $ cd /d/Code/test/
/d/Code/test $ git clone https://<tenant>.visualstudio.com/<project>/_git/<git-repository>
Cloning into '<git-repository>'...
fatal: unable to access 'https://<tenant>.visualstudio.com/<project>/_git/<git-repository>/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt
  CApath: none
/d/Code/test $
```

Again, I confirm that it was working in version 2.13. I will downgrade Git and capture the output if needed.

**Comment by belkiss** [comment]
I face the exact same issue, with the same version of git for windows (2.18.0.windows.1).

On my machine though, the path indicated by CAfile `C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt` does not exist. The `libexec` has no subfolder called `ssl`.

Instead, the file can be found within the mingw64 at this location: `C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt`.

I tried copying the `ssl` subfolder to the expected location, but when doing that I get another error:
`fatal: unable to access 'https://github.com/fastbuild/fastbuild.git/': error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`

**Comment by geordee** [comment]
@belkiss Thanks for pointing out the missing folder. I had overlooked that, when I posted the last comment.

I have copied the certificates to libexec folder, and the CAfile error is gone. Now I am getting timed out, which I am investigating.

The error SSL23_GET_SERVER_HELLO could be due to some port issues, check the proxy port configuration.
