### ISSUE TITLE
Build Git failed with error C2440: 'function': cannot convert from 'BOOL (__cdecl *)(DWORD)' to 'PHANDLER_ROUTINE'

### ISSUE THREAD

**Issue by QuellaZhang** [git-for-windows/git#1753]
Build Git latest revision on master with 2017 failed with the following errors:

d:\git\src\compat\mingw.c(3393): error C2440: 'function': cannot convert from 'BOOL (__cdecl *)(DWORD)' to 'PHANDLER_ROUTINE'
d:\git\src\compat\mingw.c(3393): warning C4024: 'SetConsoleCtrlHandler': different types for formal and actual parameter 1

Setup
•Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64-bit
 $ git --version --build-options
 git version 2.9.2.windows.1
 sizeof-long: 4
•Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 Windows Server 2016 64-bit + VS2017.2
 $ cmd.exe /c ver
 Microsoft Windows [Version 10.0.15063]

Repro steps:
 1.git clone https://github.com/git-for-windows/git.git D:\git\src
 2.git checkout vs/master
 3.devenv /upgrade git.sln
 4.nuget.exe restore git.sln 
5.msbuild /m /p:Configuration=Release;Platform=x86 /p:WindowsTargetPlatformVersion=10.0.15063.0 /t:Rebuild git.sln

**Comment by QuellaZhang** [comment]
Any update?

**Comment by dscho** [comment]
I could imagine that 5a9c83014d1a40c7c6783635328ede8d7e9083ab fixes your issue.

**Comment by QuellaZhang** [comment]
@dscho Thanks you very much! Git works well now.

**Comment by QuellaZhang** [comment]
@dscho Thank you very much! Git works well now.
