### ISSUE TITLE
Git for windows crashed

### ISSUE THREAD

**Issue by PhoebeHui** [git-for-windows/git#1754]
Hi,

I installed git for windows from https://gitforwindows.org/, it crashed, I tried different versions(Git-2.180-64-bit.exe, git-2.7.0-win10.14251-64-bit.exe, and git-2.14.1-64.exe), they all has this issue, OS is windows server 2016(64-bit OS, x64 based processor), not sure if here is right place to report this issue.

The Event log:
Faulting application name: git.exe, version: 2.14.1.1, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14393.2312, time stamp: 0x5b1a161b
Exception code: 0xc00000fd
Fault offset: 0x000000000002f02b
Faulting process id: 0x19d4
Faulting application start time: 0x01d41753b09ad71a
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 5effff1d-d97f-44cb-801c-a996cb7fe090
Faulting package full name: 
Faulting package-relative application ID:

**Comment by drizzd** [comment]
I don't know if Git for Windows works on Windows Server. Can you try to download git-for-windows SDK and compile Git from source?

**Comment by dscho** [comment]
No reaction means the ticket can be closed.
