### ISSUE TITLE
Typo in the Message on installer screen of the latest Git-2.18.0-64-bit.exe ("an" is shown instead of "and")

### ISSUE THREAD

**Issue by chaitanyatk** [git-for-windows/git#1758]
There is a typo in the Message on installer screen of the latest Git-2.18.0-64-bit.exe ("an" is shown instead of "and")

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git-2.18.0-64-bit.exe

```
$ git --version -Git-2.18.0-64-bit.exe


```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 7
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

There is a typo in the Message on installer screen of the latest Git-2.18.0-64-bit.exe ("an" is shown instead of "and")

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by shiftkey** [comment]
@chaitanyatk can you share a screenshot of the page?

My guess it's something that can be easily corrected in here if we know what message it involves: https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss

Are you interested?

**Comment by dscho** [comment]
I spent a good 5 minutes (that could have been easily avoided by a less cryptic bug report) trying to hunt down that "an" that should be an "and"), and I have to admit that all I saw was correct English.
