### ISSUE TITLE
Doesn't open terminal when started in the root

### ISSUE THREAD

**Issue by sprintr** [git-for-windows/git#176]
In case you initialize a terminal from the root, i.e. "D:\", it won't start the terminal.

**Comment by maoueh** [comment]
Hi,

Could you describe with more details your issue. Adding some steps to reproduce your problem would be perfect because in its current state, it's really unclear what needs to be done to replicate.

Cheers,
Matt

**Comment by sprintr** [comment]
1. Open any root in Windows Explorer
2. Open `Git Bash Here` from Context Menu
3. No response is given by Git Bash

Windows 7 32 Bit
Git for Windows v2.4.1

**Comment by maoueh** [comment]
Just to make it clear, when you say:

> Open any root in Windows Explorer

You mean:

 1. Open Windows Explorer
 2. Right-Click on disk `C:` (or `D:`, `E:`, etc.)
 3. From context, choose `Git Bash Here` right?

**Comment by sprintr** [comment]
No, I don't click on any drive Icon.

**Comment by dscho** [comment]
@sprintr where do you click, then?

**Comment by sprintr** [comment]
@dscho Right click anywhere in the root of a drive to open Context Menu, Select `Git Bash Here`, No response is given.
