### ISSUE TITLE
[Question] Updating the SDK

### ISSUE THREAD

**Issue by kelvin-mkc** [git-for-windows/git#1765]
### Intro
I have mostly been fighting the sdk until yesterday.  I managed to fix the
errors, but I'm still not 100% sure how the updating should be done.

I found instructions on the [wiki][1] for installing the sdk, but not for
updating it.

### Background
After running the sdk installer, it downloaded all the files (quite a lot of
GBs, I must say) and finished installing. Running `sdk build git-and-installer`
worked without any errors and so did the resulting installer.

A week later, trying to run `sdk build git-and-installer` again, it tried to
update the packages with pacman, but failed.  So I thought something was wrong
and did a git pull.  With **git-sdk-64** being a binary repo, I thought that was
the proper method for updating.  But then everything crashed and burned, and
basically I could not build the installer, since `sdk build` requires all
packages to be up-to-date.

The error was only on **mingw-w64-i686-python3** and
**mingw-w64-x86_64-python3**.  The resulting log is over 1MB (too many "$file
exists in the filesystem"), so here are the relevant portions:

```
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
error: failed to commit transaction (conflicting files)
mingw-w64-i686-python3: /mingw32/lib/python3.7/__pycache__/__future__.cpython-37.opt-1.pyc exists in filesystem
# ...
mingw-w64-x86_64-python3: /mingw64/lib/python3.7/xmlrpc/__pycache__/server.cpython-37.pyc exists in filesystem
Errors occurred, no packages were upgraded.
```

### Question
After a few `git clean`s and forcing the file overwrites in pacman, I managed to
fix it.  Now I think I got how it is supposed to work:

The **git-sdk-64** repository is meant to be only a daily snapshot that you
download only once (as in clone but never pull).

And for updating, always use pacman.

Is this it?

  [1]: https://github.com/git-for-windows/git/wiki/Technical-overview#installing-the-sdk

**Comment by dscho** [comment]
A better way might be to close all SDK windows, then open a PowerShell window, `cd` to the SDK top-level directory and issue these two commands:

```powershell
git pull
pacman -Su
```

(Explanation: the first command should update the SDK to the current version as per https://github.com/git-for-windows/git-sdk-64, and the second command should update any packages you might have installed that are *not* tracked in that repository.)

**Comment by PhilipOakley** [comment]
Very timely. I'd been having similar concerns (and tweaked the wiki with what I'd learnt). 

I think(?) I also have my setup such that `git` isn't a PowerShell command... It maybe (if true, and the problem..) that a note about SDK users/installers needing to select the right option.

**Comment by PhilipOakley** [comment]
The powershell said:
![image](https://user-images.githubusercontent.com/914343/53529513-c2ffa880-3ae4-11e9-8bf3-c2e6862d4935.png)

The bash window `git pull` gave me (first few lines):

![image](https://user-images.githubusercontent.com/914343/53529599-04905380-3ae5-11e9-8973-024819e29e22.png)

And the pacman -Su gave
![image](https://user-images.githubusercontent.com/914343/53529623-1a057d80-3ae5-11e9-8ea2-8bd44a9ba721.png)

The main bit I'm not so sure about is the date-version problems (or alternateively how to simply reload/overwrite the SDK part without losing my local repos in usr/src/git.

Sorry to be such a dumbo on this part.

**Comment by dscho** [comment]
> I also have my setup such that `git` isn't a PowerShell command...

Right, I assumed that you'd use the default, which adds `git.exe` to the `PATH` (but none of the Unix-y tools included in Git for Windows).

You can obviously work around this very easily by using absolute/relative paths:

```powershell
"C:\Program Files\Git\cmd\git.exe" pull
usr\bin\pacman -Su
```

However, this won't really work as you think it should because `pacman` runs post-install scripts as part of the installation of many packages, and they require the `PATH` to be set up so that the Unix-y tools can be found.

So I fear it will be slightly more involved.

At this point, we could probably write a shell script and run it through `C:\Program Files\Git\bin\bash.exe`, I guess. But that still irks me. I'd really like a way that is more self-contained in the SDK. I do not even like the detour to PowerShell.

In Git for Windows 1.0's SDK ("msysgit"), I copied a minimal system consisting of the Bash and few parts of Git, just to update, and then wrote out a shell script and a Desktop shortcut to run that shell script. That was still hacky, but maybe we'd want something similar to that.

**Comment by dscho** [comment]
Oh, right, I forgot to mention how you can run `pacman -Su` properly:

```powershell
$env:MSYSTEM = "MSYS"
usr\bin\bash -lc "pacman -Su"
```

(You can also use CMD and `set MSYSTEM=MSYS`, of course.)

**Comment by dscho** [comment]
FWIW these days, the SDK ships with the script `update-via-pacman.bat` that you can run (but you need to make sure that all Git SDK Bash windows are closed first, i.e. that no processes are running that might lock files that want to be updated).

**Comment by PhilipOakley** [comment]
I took the liberty of adding this info to the https://github.com/git-for-windows/git/wiki/Updating-your-SDK page.
