### ISSUE TITLE
Doesn't show output of few binaries.

### ISSUE THREAD

**Issue by sprintr** [git-for-windows/git#177]
If you initialize `php` or `node` it won't show any output.

**Comment by nalla** [comment]
Have you tried calling them with `winpty`?

**Comment by albertosantini** [comment]
With `winpty node` it works nice.

**Comment by sprintr** [comment]
Thanks @nalla and @albertosantini, It works fine with `winpty`. Any idea where to keep my `.bashrc`, since I want to add alias to `winpty php`.

**Comment by albertosantini** [comment]
@sprintr `~/.profile`

**Comment by sprintr** [comment]
@albertosantini Thanks, it worked.
