### ISSUE TITLE
Any 'git config' command results in 'Permission denied' after fresh installation of latest Git

### ISSUE THREAD

**Issue by muliar** [git-for-windows/git#1771]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.165]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Fresh installation of latest git from https://git-scm.com/download/win.
Previous installation was wiped because of this issue, no Git directories were exist:
C:\Program Files\Git\
C:\Program Files (x86)\Git\
%USERPROFILE%\AppData\Local\Programs\Git\

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash/CMD/PowerShell
The issue is the same for all shells.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git config --list
$ git config --system core.longpaths true
$ GIT_TRACE=true git lga
```
 - What did you expect to occur after running these commands?

List of config values, successful execution of git config --system

 - What actually happened instead?
```
$ git config --list
fatal: unable to access 'C:\ProgramData/Git/config': Permission denied

$ git config --system core.longpaths true
error: could not lock config file C:/Program Files/Git/mingw64/etc/gitconfig: Permission denied

$ GIT_TRACE=true git lga
01:42:25.554342 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
fatal: unable to access 'C:\ProgramData/Git/config': Permission denied
```

**Comment by muliar** [comment]
I believe this issue is the same as mine [https://github.com/desktop/desktop/issues/3746](fatal: unable to access 'C:\ProgramData/Git/config': Permission denied) but it is more general git issue, not GitHub Desktop's

**Comment by dscho** [comment]
> ```
> $ git config --list
> fatal: unable to access 'C:\ProgramData/Git/config': Permission denied
> ```

It looks as if that file is indeed not accessible to you? Have you tried opening it manually? If it does not work, then you have the problem right there: *something* took away your ability to read that file and that's not good enough for Git.

> $ git config --system core.longpaths true

Unless you are running this as administrator, this is *supposed* to fail. Non-sysadmins are not supposed to meddle with the system config.

**Comment by muliar** [comment]
Yes, this file should not be accessible to me and to everyone on Windows 10 but it is accessible to system programs. 
On other PC when I run `git config --system core.longpaths true` in MINGW without elevated rights I get 
> error: could not lock config file C:/Program Files/Git/mingw64/etc/gitconfig: Permission denied
Note the difference.

**Comment by dscho** [comment]
> Yes, this file should not be accessible to me and to everyone on Windows 10 but it is accessible to system programs.

If you are talking about `C:\ProgramData\Git\config`: it should be *readable* by everyone. That is the assumption by Git for Windows. If it is violated, you will see that error.

**Comment by robsonsobral** [comment]
Does it have something to do with the fact that the `/` are inverted?

> `fatal: unable to access 'C:\ProgramData/Git/config': Permission denied`

**Comment by robsonsobral** [comment]
Correction! I can't even open `C:\ProgramData\Git`!

**Comment by dscho** [comment]
> I can't even open `C:\ProgramData\Git`!

That means that Git cannot access that folder. That is a violation of Git's assumption (and it is pretty much a violation of the idea of `C:\ProgramData`): you *should* be able to read it. If you can't, the system administrator made a grave mistake, and is responsible for fixing your setup.

**Comment by gitname** [comment]
I observed this symptom earlier today, but it has since disappeared.

Between the time I observed it and the time it disappeared, here's what I did:

1. I used Windows Explorer to navigate to: `C:`, then to `C:\ProgramData\`, then to `C:\ProgramData\Git`
2. Somewhere along the way, Windows prompted me to click a button to open the folder as an administrator -- I clicked the button
3. Windows displayed the contents of the folder
4. At this point, I was able to run Git commands without issue

Here's my system information:

```
Microsoft Windows 10 Enterprise 2015 LTSB

$ git --version
git version 2.21.0.windows.1
```

**Comment by mfriedrich74** [comment]
With confirming that prompt, Windows added your account to the folder
permissions. You can verify this by checking the security settings (acls)
of those folders. So far I have seen those on windows servers only, they
come with stricter security settings.
