### ISSUE TITLE
Absolute UNIX symlinks always show as modified

### ISSUE THREAD

**Issue by letmaik** [git-for-windows/git#1772]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.165]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue?

```
> git clone https://github.com/wrf-model/WRF_OPEN -b master
> cd WRF_OPEN
> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   var/run/crtm_coeffs
> git diff var/run/crtm_coeffs
diff --git a/var/run/crtm_coeffs b/var/run/crtm_coeffs
index 299ff83f..7cce4bee 120000
--- a/var/run/crtm_coeffs
+++ b/var/run/crtm_coeffs
@@ -1 +1 @@
-/glade/p/work/wrfhelp/WRFDA_files/crtm_coeffs_2.2.3
\ No newline at end of file
+C:/glade/p/work/wrfhelp/WRFDA_files/crtm_coeffs_2.2.3
\ No newline at end of file
```
 - What did you expect to occur after running these commands?

There should be no modifications after a fresh clone.

 - What actually happened instead?

Git always lists the absolute UNIX symlink at var/run/crtm_coeffs as modified because it prepends `C:` to it.

I'm not saying that the practice used in this repo is in any way good, but I still consider it a bug in git as such a behaviour should not happen. It should be possible to ignore such symlinks if they are not being changed.

**Comment by kgybels** [comment]
> @letmaik It should be possible to ignore such symlinks if they are not being changed.

You can do that with the following [1]:
```
git update-index --assume-unchanged var/run/crtm_coeffs
```

[1] https://git-scm.com/docs/git-update-index#git-update-index---no-assume-unchanged

**Comment by dscho** [comment]
I do not think that these Unix type symlinks make any sense on Windows. Neither do I think that Windows even *allows* those. @letmaik So what would you like Git to do in this case? :puzzled:

**Comment by letmaik** [comment]
I'd like git to just ignore it if it can't deal with it. Imagine it's a big repo and it contains things for Windows, Linux, macOS, ... and for some reason someone thought it's a good idea to have that absolute symlink in the Linux part. Now, if I work only on the Windows part of the repo I don't want to be disturbed by this weird symlink, esp. blocking merges, showing up in diffs etc.

**Comment by dscho** [comment]
> I'd like git to just ignore it if it can't deal with it.

Git deals with it, and more importantly Windows deals with it. Just not in the way you want it to.

What happens is that you have a link to something that looks like an absolute Unix path, but that is also a legal absolute path on Windows: it simply refers to the same drive as the current directory.

Now, Git will create this symbolic link, just like you asked for it to. And Windows will then ask the NTFS layer to store it on disk, which is when it will resolve that drive letter. And when we read it back, it won't be an absolute path without a drive letter anymore, but an absolute path *with* a drive letter.

This is perfectly legal, and even the best course of action.

What you face is a problem where some developers obviously don't care about cross platform, and therefore felt free to add such a link that is not quite specific enough on Windows.

Probably the wisest way forward for you is to use a sparse checkout, excluding those symlinks that you know are ill-defined, via something like

```
*
!var
var/*
!var/run
var/run/*
!var/run/crtm_coeffs
```

in your `.git/info/sparse-checkout` and then setting `core.sparseCheckout = true` in your repo config. Of course, this should all happen before checkout, so it all is a bit cumbersome.

If you do not like what I tell you, you can still take this issue to the Git mailing list (git@vger.kernel.org); Maybe somebody there will give you a more satisfying answer than I do.

**Comment by letmaik** [comment]
Thanks for the detailed explanation. I agree there's probably nothing to do here. I think though at a minimum git should spit out of warning if an absolute symlink is added, since this is rarely what people would want. In the specific case that I mentioned here the warning would probably have been ignored, but still.

**Comment by dscho** [comment]
>  I think though at a minimum git should spit out a warning if an absolute symlink is added, since this is rarely what people would want.

How about writing that patch?

It would probably add that warning somewhere around here: https://github.com/git/git/blob/v2.21.0/read-cache.c#L709-L716

Guarded by an `S_ISLNK()` call in conjunction with a call to `is_absolute_path()` after reading the symlink target.

And for extra brownie points, add a config setting to make this warning configurable, much like `advice_rm_hints` works (use `git grep` to find out more ;-))
