### ISSUE TITLE
Git 2.18 is missing msys-icuuc60.dll

### ISSUE THREAD

**Issue by CJCombrink** [git-for-windows/git#1775]
- [x] I was ~~not~~ **able** to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
See closed issue #1336

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.18.0.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17134.191]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash, CMD and PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
> C:\Git\usr\bin\xsltproc.exe --version
```
 - What did you expect to occur after running these commands?

Version of XSLTPROC getting printed

 - What actually happened instead?

Pops up error dialog and says:
```
---------------------------
xsltproc.exe - System Error
---------------------------
The code execution cannot proceed because msys-icuuc60.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by dscho** [comment]
> xsltproc.exe

This program is not required for Git to function. It was only bundled by mistake.

If you require a full-fledged "Linux alike" system, please consider using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or [MSYS2](https://msys2.github.io/) instead.
