### ISSUE TITLE
Git version in terminal is not updated when git hooks are used

### ISSUE THREAD

**Issue by BuruY** [git-for-windows/git#1777]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
    64-bit
```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
   Windows 10 | 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
    Installed a git hook called post-merge:
``` 
#!/bin/shexec 
git submodule update --init --recursive
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
   PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status
```
 - What did you expect to occur after running these commands?

correct version was shown

 - What actually happened instead?

old version was shown

![image](https://user-images.githubusercontent.com/31062264/43577424-15ccff4c-964c-11e8-8c8f-11f9e58fe3d6.png)

So what happens is that I have a hook configured that automatically updates submodules when I pull and merge from origin. The hook is working and is executed when needed. But when after I check in my Visual code (see screenshot) you can see that the version stated there is correct, when in terminal checking version number with `git status`, it returns the old version.

When I check the submodule by hand to see if latest changes has been fetched, then I can see that all changes have been fetched and thus the version is indeed correct in VS Code, and wrong in terminal

**Comment by dscho** [comment]
Isn't this more like a Visual Studio Code issue?

**Comment by dscho** [comment]
Oh wait, no, I see it. The text in `git status`' output says:

> HEAD detached from f4bba64

Please note that it does *not* say "HEAD is at f4bba64". So I really think you're wrong and `git status` is right. You really detached HEAD at that revision *and then did some things to change HEAD*. The hint in `git status` really is meant to help you remember where you started.
