### ISSUE TITLE
Unexpected pathspec error with git-checkout command when using glob

### ISSUE THREAD

**Issue by am11** [git-for-windows/git#1778]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```pwsh
$ git --version --build-options

git version 2.16.1.windows.2
cpu: x86_64
built from commit: e78e3c8ee9c219723d60aa1bccd8348c2269b9ba
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```pwsh
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```pwsh
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```pwsh
✕ git checkout HEAD~1 *App.config
✕ git checkout HEAD~1 **/App.config
✕ git checkout HEAD~1 **/**/App.config

✕ git checkout HEAD~1 -- *App.config
✕ git checkout HEAD~1 -- **/App.config
✕ git checkout HEAD~1 -- **/**/App.config
```
 - What did you expect to occur after running these commands?

I expect `git-checkout` command to support pathspec.

 - What actually happened instead?

> error: pathspec '*App.config' did not match any file(s) known to git.

However, it works fine if I provide full paths one by one:

```pwsh
✓ git checkout HEAD~1 .\ProjectA\App.config
✓ git checkout HEAD~1 .\ProjectB\App.config
✓ git checkout HEAD~1 .\ProjectC\App.config
...
```

or combined

```pwsh
✓ git checkout HEAD~1 .\ProjectA\App.config .\ProjectB\App.config .\ProjectC\App.config
```

Most of the other git commands have no problem understanding the same glob pattern:

```pwsh
✓ git grep "assemblyBinding" *App.config
✓ git log *App.config
✓ git status *App.config
```

Similar issue was reported by a user of Windows 7: https://www.reddit.com/r/git/comments/5520na/cannot_checkout_with_pathspec/

**Comment by dscho** [comment]
I just tried something similar (your MCVE does not reproduce here, as I do not have any App.config files) in a git.git checkout.

Further analysis points to 0a1283bc3955a97557019d077b96669c5c93c551 making this explicitly-intended behavior.

Since you disagree with it, please take the issue to [the Git mailing list](mailto:git@vger.kernel.org).

**Comment by am11** [comment]
@dscho, thanks for taking time and great detective work bisecting the exact commit; commit message has very well explained the cause. 👍 

(at first, I didn't realized that it was part of upstream https://github.com/git/git/commit/0a1283bc3955a97557019d077b96669c5c93c551)

Before I can challenge that change in mailing list, I would need to study the codebase a bit and reassess in light of commit message that if it still makes sense or possible to disambiguate the corner case and if there is a comparable command.

Meanwhile, in PowerShell I am using:

`git checkout (ls -r **/App.config).FullName`

However, it's quite slower than git's glob resolution.

---

Closing this issue as per the discussion above.

Cheers

**Comment by dscho** [comment]
> it's quite slower than git's glob resolution.

Indeed. FWIW if I were you, I would kick this to the mailing list even with the current understanding of the issue. More minds thinking about it is usually a Good Thing.

**Comment by dscho** [comment]
> The vger mailing list server rejected the email from outlook.com address with the message "Your address is not liked source for email".

Is it possible that you sent HTML mail? The Git mailing list simply rejects those (yes, they do, and no, I don't like it, and no, I unfortunately cannot do anything about it).
