### ISSUE TITLE
ConEmu integration information will open two tabs

### ISSUE THREAD

**Issue by davidovich** [git-for-windows/git#178]
I want to configure ConEmu to open a new tab (task) and if I follow precisely the documentation in commit ac6b03cb4 (linked from the release notes of 2.4.2.1) to integrate git bash in ConEmu (v150513), the result is that two tabs get opened:

* one for parent task called git-bash with the following contents:
```
    GUI application (PID=xxxx was attached to ConEmu:
    C:\Program Files\Git\git-bash.exe
```
* another tab with the expected mingw64 bash shell

I would expect to have only one tab opened.

The process tree shows that a new parent ConEmu is started...

![image](https://cloud.githubusercontent.com/assets/1440370/7921374/10e62478-0873-11e5-9b76-20c7855cb2ae.png)

Is it possible to detach from the git-bash launcher ?

**Comment by dscho** [comment]
@Maximus5 your help would be much appreciated here.

**Comment by dscho** [comment]
[Confirmed to be a ConEmu bug](https://github.com/git-for-windows/git/issues/96#issuecomment-110760537).

**Comment by davidovich** [comment]
Verified fixed in ConEmu 150610

**Comment by dscho** [comment]
@davidovich thanks for following up!
