### ISSUE TITLE
git status can't show correct info when cherry-pick failed

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#1781]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

 git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.547]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
1.git cherry-pick failed
2.git reset --hard (revert back to the previous commit)
3.git status
```
 - What did you expect to occur after running these commands?

git cherry-pick (--continue | --quit | --abort)

 - What actually happened instead?

nothing to commit, working tree clean
if I try to run the cherry-pick command,then I got the error info

> $ git_trace=1 gcm_trace=1 git cherry-pick 9e3252^..126c0c
> 09:42:26.553465 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
> 09:42:26.561487 git.c:415               trace: built-in: git cherry-pick 9e3252^..126c0c
> error: a cherry-pick or revert is already in progress
> hint: try "git cherry-pick (--continue | --quit | --abort)"
> fatal: cherry-pick failed
>

**Comment by dscho** [comment]
`git status` is intended as the "dry-run" `git commit` (documented here: https://git-scm.com/docs/git-status):

> Displays paths that have differences between the index file and the current HEAD commit, paths that have differences between the working tree and the index file, and paths in the working tree that are not tracked by Git (and are not ignored by gitignore[5]). The first are what you would commit by running git commit; the second and third are what you could commit by running git add before running git commit.

So what you see is expected, if the cherry-pick failed without staging anything.
