### ISSUE TITLE
git cherry-pick did not reset the worktree back with hard option

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#1782]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

 git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.547]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Try to abort the cherry-pick when the cherry-pick failed
git cherry-pick --abort
```
 - What did you expect to occur after running these commands?

abort the cherry-pick ,and the worktree should be clean

 - What actually happened instead?

It seems the cherry-pick was aborted, but the work tree was not reset back.
when I use "git status", it told me the files was modified( the files listed come from the commit which should be cherry-pick)

**I think the cherry-pick --abort should reset back with --hard option as the git rebase --abort.**

**Comment by dscho** [comment]
Please come up with a truly *verifiable* Minimal, Complete and Verifiable example. What you wrote in the report does not verify here:

```sh
$ git cherry-pick --abort
error: no cherry-pick or revert in progress
fatal: cherry-pick failed
```

**Comment by chucklu** [comment]
can not reproduce, the cherry-pick failed situation only happened in https://github.com/git-for-windows/git/issues/1780
