### ISSUE TITLE
feature request: include some sort of terminal multiplexer

### ISSUE THREAD

**Issue by soniah** [git-for-windows/git#1787]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **

$ git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

Feature request: include some sort of terminal multiplexer e.g. tmux, screen, byobu, mtm, etc.

**Comment by PhilipOakley** [comment]
The Git for Windows package is not meant to be a fully fledged Linux style environment. One or two productivity tools are included (e.g. certain editors). 

The size of the Git for Windows package is already quite large so any extras would need to be small, reliable, require very minimal support without awkward interactions, and ideally be backed by a supporter, such as yourself. 

There are other PRs and issues that cover the addition [or not] of such packages and how to prepare and build the a package for PR. Maybe have a look at supporting the project (first would be to choose the preferred mux..)

**Comment by dscho** [comment]
Just for context: `tmux.exe` is available as MSYS2 package. Bundling it would *probably* consist of shipping `tmux.exe` and `msys-event-2-1-6.dll`, but trying to do that to explain what it would take resulted in a dysfunctional `tmux`.

Meaning: it would add more maintenance burden than I can bear to include such a terminal multiplexer. If you want it, you will have to volunteer to maintain it.

**Comment by soniah** [comment]
Thanks guys, I understand. I'm not a Windows person and at the moment I don't want to invest time in the arcaneness of Windows programming. Maybe in the future...
