### ISSUE TITLE
Git for Windows does not build after running `./configure`

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#1789]
@ungps figured out that Git for Windows' source code, when cloned and after running `./configure`, fails to build.

It would seem that a ton of things go wrong there, as even `NO_CURL` and `NO_UNSETENV` are defined, and they are incompatible with our expectations.

This would make for a very fine project for anybody who wants to get involved in Git for Windows but does not know how, or is too scared of the implementation details or the Win32 API.

**Comment by ungps** [comment]
The root of the problem was that I ran `configure` using `MSys` instead of `MSYS2`.  I ran again `./configure && make` in Git For Windows SDK and it worked like a charm. So I guess there is no problem here.

**Comment by dscho** [comment]
Okay, thanks for following up!
