### ISSUE TITLE
Git GUI taskbar icon is not referencing the program correctly when pinned

### ISSUE THREAD

**Issue by UsagiBo** [git-for-windows/git#1790]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options



**git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4


 **


```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.17134.191]
**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults? 

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: Notepad++
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

**
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** not that I can think of **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**
I use Git GUI  for convenience, but for the above questionnaire I used Git Bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**I just opened Git GUI from the start menu **
```
 - What did you expect to occur after running these commands?

** I expect to pin the Git GUI app to my taskbar and refer to is when I want to open Git GUI**
 - What actually happened instead?

**  When  having pinned Git GUI to the taskbar the icon changes immediately after I close the Git GUI window the icon changes to this Aladdin/like lamp. When proceed to open it I get two console windows what claim to be 
''Tcl for Windows 
Tcl 8.6.8. 
Tk 8.6.8.''

I want to mention that I found a similar unresolved issue in this git repo called : "Git GUI pinned to taskbar appears as "Wish Application" #737 ". Which has not been resolved but closed
 **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** No **
![screenshot_1](https://user-images.githubusercontent.com/8667167/43967681-3fd902ac-9cc5-11e8-8bd7-c84edaf64865.png)
![screenshot_2](https://user-images.githubusercontent.com/8667167/43967683-3ff83ab4-9cc5-11e8-84bd-2b6e80d22b19.png)
![screenshot_3](https://user-images.githubusercontent.com/8667167/43967684-4016d92e-9cc5-11e8-8a72-cc0275615390.png)

**Comment by rimrul** [comment]
That happens because Git GUI is a script and when you try to pin a running script to the taskbar, windows pins the executable that runs the script instead. Navigate to Git GUI in your start menu, right click the entry and select "pin to taskbar" to actually pin Git GUI (well, the GfW wrapper that launches Git GUI) to your taskbar.
