### ISSUE TITLE
Can't work with remote, everything with BitBucket!

### ISSUE THREAD

**Issue by benyaminl** [git-for-windows/git#1791]
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit (All From portable to Instaled version)

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 64bit Pro On ASUS A43SV - 16gb ram i7-2670qm 

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Everything, bash, PowerShell, CMD, and such

 - What commands did you run to trigger this issue? 
Git pull, push, and everything that work with remote server with bitbucket.

 - What did you expect to occur after running these commands?

After entering the password from pop up it doesn't work and cause Xhttpexeption, I use both busybox version of git, mingit, portable git and installed git.

 - What actually happened instead?

It authenticate with bitbucket and I shouldn't do anything else,
(I hope there's option for this, thanks)

**Comment by dscho** [comment]
> After entering the password from pop up it doesn't work and cause Xhttpexeption

Details, please.

**Comment by timmetj** [comment]
Maybe related to this:
https://github.com/Microsoft/Git-Credential-Manager-for-Windows/pull/720

new release of credential manager could help

**Comment by benyaminl** [comment]
Seems that. But when ?



Sent from My Asus Pegasus X005



Pada tanggal Sel, 14 Agt 2018 16.11, timmetj <notifications@github.com>
menulis:

**Comment by dscho** [comment]
> Seems that. But when ?

@benyaminl it is already there: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.17.1

It would be wise to test it right away...

**Comment by benyaminl** [comment]
@dscho I don't use git installer, I use git busybox, is there anyway to force the installation. Thanks

**Comment by benyaminl** [comment]
@dscho seems it's windows and GCM also bitbucket related issue,, it sucks really. Thanks anyway..

**Comment by dscho** [comment]
> I don't use git installer

I told you to use the Git Credential Manager, not the Git installer.

> I use git busybox

You mean that you use MinGit-busybox? MinGit is *not* intended for interactive usage.

> is there anyway to force the installation

No. It is on the radar, but there are too many people here who do the asking (such as you do), and too few who do the doing (such as I try, but there is just too much).

If you could find it in yourself to contribute a bit, I could help you to get what you want.

**Comment by benyaminl** [comment]
@dscho Yep, I use MinGit-busybox. It's small has small footprint. As it's working for me doesn't matter if it's not designed for interactive usage or not. 

Anyway as I stated above, it's GCM Issue, not git issue, because it's asking for oauth and it failed. and after upgrade to 1.17.1 the authentication is working again and it's GCM issue :) 

Anyway how do I contribute? *I'm not picking a fight, I hope my bad english doesn't affect the way I communicate or write, that make my statement seems I'm a douche-bag*

**Comment by dscho** [comment]
> Yep, I use MinGit-busybox. It's small has small footprint. As it's working for me doesn't matter if it's not designed for interactive usage or not (git installer is very big, takes about 1gb of disk space, and MinGit-busybox is only 30mb and it works 👍 ).

Well... it matters if you use for an unintended purpose because *you obviously want me to fix it for you* (your "it's working for me" is contradicted by your opening this here ticket).

> Anyway how do I contribute?

I am glad you ask.

One of the things I really want to see is BusyBox to be tested thoroughly. Last time I tried to run the test suite through it, it failed pretty badly, not only because it required a working `perl.exe` (which is the fault of the Git test suite, not of BusyBox, of course), but also because there were inexplicable hangs.

So here is something you can do: you can test the heart out of MinGit(BusyBox) to try to find weak spots, then investigate further where issues arise (as mentioned in https://github.com/git-for-windows/git/issues/1439#issuecomment-380504854). The more you can help, the better.

**Comment by benyaminl** [comment]
@dscho Yeah I know it sucks, I can feels that (Sometimes user asking to fix something ridiculous). But this time I see that GCW do something wrong it it.. hahaha. 

I don't have project with git submodule, maybe there's open project to test ? Thanks :)

**Comment by dscho** [comment]
> set-x

In general, `set -x` is used in Unix shell scripts to turn on "tracing", i.e. the Unix shell interpreter (in our case, Bash) will print every command in the script before it is executed.

**Comment by benyaminl** [comment]
Okay then what should I do, I mean where I should put it? I read the bash
code but I can't understand it.



Sent from My Asus Pegasus X005



Pada tanggal Sen, 20 Agt 2018 22.55, Johannes Schindelin <
notifications@github.com> menulis:
