### ISSUE TITLE
feature request: „git config merge.edit“

### ISSUE THREAD

**Issue by Thomas-Lohrum** [git-for-windows/git#1792]
By default, Git does not open an editor to edit a commit-message when merging. Instead a default message is used. When set to true, this variable tells Git to open an editor before a commit is completed (equivalent to giving the --edit option from the command line). When set to false a commit is completed without interference (equivalent to giving the --no-edit option from the command line).

**Comment by dscho** [comment]
> By default, Git does not open an editor to edit a commit-message when merging.

That is the opposite of the behavior I observe here.

Since you have been asked gently in the issue reporting template, and chose to ignore it, let me ask you not so gently anymore: please provide an [MCVE](https://stackoverflow.com/help/mcve) (and specify exactly what Git for Windows version you are using).

**Comment by dscho** [comment]
(FWIW https://git-scm.com/docs/git-merge#git-merge---edit also suggests that the default behavior is to *always* open the editor.)

**Comment by Thomas-Lohrum** [comment]
Thanks to the MCVE hint.

I did a fresh install of git (64-Bit) on Windows 10 and accepted all default settings for the install.

The git version is "git version 2.18.0.windows.1".

I opened a default Windows command window (no bash).

__Steps to reproduce:__
git init repo
cd repo
echo Hallo >file1.txt
git add .
git commit -m "file1 added"
git checkout -b featureBranch
echo Hello >file2.txt
git add .
git commit -m "file2 added"
git checkout master
git merge --no-ff featureBranch

__Result:__
- no editor gets opened here 
=> expected result "open editor"
- the editor gets opened, when i set GIT_MERGE_AUTOEDIT=true 
=> works as expected
- no editor gets opened, when GIT_MERGE_AUTOEDIT=true and a message gets passed using -m switch 
=> works as designed; an editor can still be opened by passing "--edit"

__Comments:__
When working with a GUI client such as SourceTree it is not always possible to adjust the required settings to git. As a solution i added '[branch "master"]mergeoptions = --no-ff --edit' to my repo configuration. The trouble is that i need to do this for every branch as there is no wildcard support such as '[branch "release/*"]'. I can use "merge.ff=false" as an equivalent to "--no-ff". However, there is no equivalent to the "--edit" switch. It can be controlled by the env-var "GIT_MERGE_AUTOEDIT" to some extend, but not in combination with the "-m" switch.

__Summary:__
I can now workaround by setting GIT_MERGE_AUTOEDIT=true. However it is not clear, why the editor does not open in the first place. 
The suggested setting "merge.edit=true" could by used as an alternative to the env-var. It also would allow configuration as a repository-setting. Another consideration is to also open an editor, when the -m switch is used.

**Comment by dscho** [comment]
@Thomas-Lohrum you do not intend to give back to this project by contributing a patch to implement this, do you?

**Comment by Thomas-Lohrum** [comment]
Git's default behaviour is to open an editor on a merge. As such my suggestion is not required. I can not tell why it does not work on my machine or on my colleagues. Setting GIT_MERGE_AUTOEDIT to true, does solve the requirement, though. Thanks for your offer and your help.

Thomas
