### ISSUE TITLE
Please bump GCM version

### ISSUE THREAD

**Issue by boxfoot** [git-for-windows/git#1794]
Please issue a patch release bumping the bundled GCM to version  1.17.1.   This version was released in the past week to fix an authentication problem with Bitbucket.

https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.17.1

If I try to install GCM directly, it is not recognizing my installed git-for-windows and wants to reinstall it in parallel -- would be great to update the version bundled here.  Thanks!

**Comment by shiftkey** [comment]
@boxfoot this has already been updated in source: https://github.com/git-for-windows/build-extra/commit/734b5eb12275b5a03c11c7f92af1afbe4df2dea4

Details about the next update are outlined here: https://github.com/git-for-windows/git/pull/1747#issuecomment-412654325

**Comment by boxfoot** [comment]
@shiftkey thanks - I didn't find the build-extras repo, so didn't see that change.

Your link was also helpful - so looks like next release is expected to be in early Sept or about a month off, so if I'm reading right, my best option is to directly install GCM in the meantime.  Thanks.

**Comment by shiftkey** [comment]
@boxfoot there are also pre-release builds available which you can use to verify the right GCM is installed: https://wingit.blob.core.windows.net/files/index.html

**Comment by boxfoot** [comment]
Great!   Most recent prerelease build is from Aug 9 (last commit to git) but gcm version was bumped Aug 10, so not included yet... but I'll keep my eyes out and hopefully there will be another git build soon.

**Comment by dscho** [comment]
> I didn't find the build-extras repo, so didn't see that change.
> 
> Your link was also helpful

@boxfoot feel _so_ totally free to edit the [FAQ](https://github.com/git-for-windows/git/wiki/FAQ) (linked from [Git for Windows' home page](https://gitforwindows.org/) to help others find what you did not.

> so looks like next release is expected to be in early Sept or about a month off, so if I'm reading right, my best option is to directly install GCM in the meantime.

That is always the best thing if you need a GCM fix in a hurry.
