### ISSUE TITLE
Git binaries on Windows don't have a version number

### ISSUE THREAD

**Issue by JJClements** [git-for-windows/git#1797]
Bit of a strange one, we've noticed that the git binaries on Windows don't seem to have a build version (at all) that presumably matches the release version of the application? Is there a reason for this? It's the only one of many applications that we use that doesn't seem to add the tags to the binaries when they are compiled for some reason?

This would also really help with our patching/maintenance to ensure the application is always kept up to date ;-)

Thanks

**Comment by shiftkey** [comment]
@JJClements not sure I understand the context - the version you get from `git version` is [tagged in the repository](https://github.com/git-for-windows/git/tags) and [can be tracked to releases](https://github.com/git-for-windows/git/releases): 

<img width="297" src="https://user-images.githubusercontent.com/359239/44348434-c39def00-a470-11e8-9b17-5eb218e9aa3c.png">

Is there more that you're looking for from this?

**Comment by JJClements** [comment]
Hi @shiftkey - I should have been clearer, the (file version AND the product version) properties that you see when you right click on the actual windows binary itself do not match those of the installer.

The installer version (which is correct):
<img width="537" alt="installer" src="https://user-images.githubusercontent.com/3729722/44352008-17bdc900-a49b-11e8-809e-81a287f88514.png">

The actual git.exe binary:
<img width="594" alt="binary" src="https://user-images.githubusercontent.com/3729722/44352023-21473100-a49b-11e8-9e61-55c6704e19db.png">

**Comment by JJClements** [comment]
So there are 2 issues, the first is that the format of the file version and the product version differ between the installer and the actual git.exe binary.

The second is that the version of the installer does not match the version of the git.exe binary that is installed on the filesystem.

**Comment by dscho** [comment]
@JJClements good find.

Now for the next step: figure out how to fix this. A quick web search found this for you: https://stackoverflow.com/questions/6498750/how-do-i-automatically-set-the-version-of-my-inno-setup-installer-according-to-m#6498791

The next steps for you involve:

1. installing the [Git for Windows SDK](https://gitforwindows.org/#download-sdk),
2. building an installer with `sdk build git-and-installer` just to see that everything works
3. patching `/usr/src/build-extra/installer/install.iss` and/or `/usr/src/build-extra/installer/release.sh` accordingly
4. verify with `sdk build git-and-installer` that it worked
5. commit, fork `build-extra`, push your branch and open a PR.

**Comment by r1walz** [comment]
@dscho : This is not resolved as of `v2.20.1`? I'd like to work on this one!

**Comment by dscho** [comment]
@r1walz go for it!

(It is not resolved as of v2.20.1, and if we can get it solved for v2.21.0, that'd be awesome, especially since the OP clad themselves in silence ever since asked to do something ;-))

**Comment by dscho** [comment]
@JJClements feel free to pick up work on this, as @r1walz seems to be busy applying for the Google Summer of Code, and it really is not his responsibility to fulfill your wishes, especially when you have been given all the tools to fulfill your wishes yourself.

**Comment by dscho** [comment]
@r1walz sorry, I did not mean to take this project from you! It also does not exactly look like @JJClements is super eager to help Git for Windows in any way, either, so...

You mentioned on IRC that you have some preliminary patch that however does not seem to do the job? Can you push this somewhere so I can have a look?

**Comment by r1walz** [comment]
@dscho It's not much I just changed this [line](https://github.com/git-for-windows/build-extra/blob/a5a0286f0d7fda247da11a9618c839b4913bbde3/installer/install.iss#L77), just like you suggested, but, after reading the Inno Setup Script docs that line actually changes the version of the installer, not the installed file (as far as I understood). Also, I think we have to change flags in `file-list.iss`.

**Comment by dscho** [comment]
@r1walz still, if you can commit a WIP ("Work In Progress") and push it somewhere so I can easily just pull and check things out...

**Comment by dscho** [comment]
@JJClements a suggestion: buy @r1walz a drink of his choice, as he fulfilled your wish.
