### ISSUE TITLE
git svn clone can't deal with spaces in tags/branches

### ISSUE THREAD

**Issue by dannce** [git-for-windows/git#180]
When trying to clone a SVN repository that has spaces in a branch, I get an error. Note that in git 1.9.5 for windows (and I've heard that in the latest git for *nix systems) this command works.

**Comment by dscho** [comment]
@dannce please try to come up with a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve).

**Comment by dscho** [comment]
@dannce hint: you can initialize a Subversion repository in the file system and zip it.

**Comment by dscho** [comment]
@dannce any progress? Or is this ticket no longer relevant?

**Comment by dannce** [comment]
I'm sorry, but I don't work with SVN myself and have this version of Git no longer installed. But any branch of the form "branch name" can't be copied and the "git svn clone"-command will terminate.

**Comment by nalla** [comment]
I can not reproduce this behavior, seems to work fine:
```bash
cd /usr/src
mkdir test && cd test
svn init a
svn co file:///usr/src/test/a b
cd b
mkdir trunk
svn add trunk
svn commit -m"initial"
cd ..
svn copy file:///usr/src/test/a/trunk "file:///usr/src/test/a/space adventure" -m"making a space adventure"
git svn clone file:///usr/src/test/a c
cd c
git log

```

**Comment by dannce** [comment]
I don't know SVN, but it doens't look like to me that you've created a branch or tag, only a file with a space in its name. Nevertheless, I think this issue can be closed:

I can't reproduce the bug in using git version: Git-2.4.4.2-3rd-release-candidate-64-bit. This version can clone SVN branches with spaces in it just fine.

The version I used when making the bug report was: Git-2.4.1.1-dev-preview-64-bit.

Ps. Here is a thread that discusses this whitespace problem in branches/tags:
http://stackoverflow.com/questions/11365317/git-svn-clone-fails-fatal-not-a-valid-object-name

**Comment by nalla** [comment]
http://stackoverflow.com/a/13083877 indicates that too.
