### ISSUE TITLE
Copy/Paste not working after running PHP interactive session

### ISSUE THREAD

**Issue by routinet** [git-for-windows/git#1804]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.12.2.windows.2
built from commit: 7723f38cfb0e80f010afaebdd9fec4d0822fd2e1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.547]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
$ php --version
PHP 7.1.18 (cli) (built: May 24 2018 17:55:12) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git-Bash from Windows Explorer context menu.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ php -a
Interactive shell

php > exit
```
 - What did you expect to occur after running these commands?

Mouse-enabled text marking for copy/paste to work as normal.

 - What actually happened instead?

Text is no longer highlighted by simply pressing the mouse buttons.  It is no longer copied or pasted by pressing the right mouse button.  Marking using the system menu [Alt-Space | Edit | Mark] and pasting with shift-Insert still works.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> provide a
>     Minimal, Complete, and Verifiable example
>     this will help us understand the issue.
> 
> $ php -a

Where does that `php` come from. You really need to list all the steps to reproduce this.

**Comment by routinet** [comment]
From within a git bash window, I am able to select text by left-click-dragging my mouse over it.  Once text is selected, right-click copies it to the clipboard.  A right-click without any selection will paste the clipboard contents.

Once I run `php -a`, which starts a PHP interactive session, then exit the PHP session, mouse marking/selecting/copying/pasting does not work - the mouse buttons yield no response in the git bash window.  Mouse button functionality is restored if I start a new git bash session in a new window.

**Comment by dscho** [comment]
You still have not specified how your `php` came about. Of interest would be: which version, where to download, chosen install options, etc.

**Comment by routinet** [comment]
`PHP 7.1.18 (cli) (built: May 24 2018 17:55:12) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans`

It was installed using the standard snapshots available at https://windows.php.net/.  I installed the xdebug extension as downloaded from https://xdebug.org/download.php.  Other standard extensions I have enabled:

extension=php_bz2.dll
extension=php_curl.dll
extension=php_gd2.dll
extension=php_imap.dll
extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_exif.dll
extension=php_mysqli.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll


Let me know if you'd like any other information from the ini or phpinfo().

**Comment by dscho** [comment]
> Other standard extensions I have enabled:

In order to make this a Minimal example (remember, you are trying to capture the time of volunteers here, to help you with your problem, so you will definitely want to make it as simple on those volunteers to help you so that they have an incentive to do so), you will want to verify that all of those extensions are necessary to reproduce. Because if they are not necessary to reproduce, the minimal example would be more minimal without those extensions.

**Comment by dscho** [comment]
> Bash Terminal Option: ConHost

I was about to suggest switching to this, but now I saw that this is already the case. In that instance, the issue will probably be fixed by either resetting the `php` alias, say, by adding `unalias php` to `~/.bash_profile`, or by calling `php.exe -a` (i.e. `php.exe` instead of `php`).

In any case, the progression in this ticket makes me doubt that we'll get anywhere with this, so let's just close it. It's not like PHP is an integral part of Git for Windows that we need to support or something.
