### ISSUE TITLE
ssh-copy-id command "forgets" the supplied hostname

### ISSUE THREAD

**Issue by rregier** [git-for-windows/git#1805]
$ git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4

Windows 10 Pro 64 bit

$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.228]

type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

SSH connection test works:

ssh rr@dvis2
rr@dvis2's password:
Linux dvis2 4.17.0-0.bpo.1-amd64 #1 SMP Debian 4.17.8-1~bpo9+1 (2018-07-23) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
No mail.
Last login: Tue Aug 28 11:39:54 2018 from 24.222.19.107
rr@dvis2:~$ exit
logout
Connection to dvis2 closed.

 - GIT Bash

Commands attempted:

 ssh-keygen.exe
 ssh-copy-id dvis2

Success for both expected.

Actual result:

$ ssh-keygen.exe
Generating public/private rsa key pair.
Enter file in which to save the key (/z//.ssh/id_rsa):
/z//.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /z//.ssh/id_rsa.
Your public key has been saved in /z//.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:VwbvvvpCJvEiC+ZCncal3/T4BvsYvIs1L4Yu8dmBN6w rr@RR600G2PRO
The key's randomart image is:
+---[RSA 2048]----+
|          .      |
|           o     |
|            +    |
|      . .  +     |
|   o + oSo. .    |
|  . X o.X.+.     |
| . + = @=%  .    |
|  . o EoB*+  .   |
|   . oo.+*=+o    |
+----[SHA256]-----+

rr@RR600G2PRO MINGW64 ~
$ ssh-copy-id dvis2
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/z//.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: ERROR: ssh: connect to host  port 22: Connection refused

**Comment by dscho** [comment]
> ```
> $ ssh-copy-id dvis2
> /usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/z//.ssh/id_rsa.pub"
> /usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
> 
> /usr/bin/ssh-copy-id: ERROR: ssh: connect to host port 22: Connection refused
> ```

How is your Unix shell scripting fu? I am too short on time to dig into this myself, but I could help you dig into it: start by `sh -x /usr/bin/ssh-copy-id dvis2` and see whether you can follow in the output (by correlating it to the script in `/usr/bin/ssh-copy-id`) and where things go awry.

**Comment by rregier** [comment]
My Unix shell scripting fu is almost non-existent.  I did look at a logged execution but I could not figure out where it made the host name disappear during execution.

The key point is that normally the error text would look like this:

/usr/bin/ssh-copy-id: ERROR: ssh: connect to host XXXX port 22: Connection refused

The fact that the host name has become "null" by the time it has failed and is displaying
error text is probably a big hint of where to focus upon.

**Comment by dscho** [comment]
> My Unix shell scripting fu is almost non-existent.

That's too bad, but there is always the option of learning a little bit, just enough to help yourself.

> I did look at a logged execution but I could not figure out where it made the host name disappear during execution.

Maybe you want to paste it in case *somebody* feels that they can help you.

**Comment by dscho** [comment]
Well, then, it appears to be not pressing enough a problem if it is allowed to languish this long.
