### ISSUE TITLE
Copy/Paste doesn't work in Git Bash

### ISSUE THREAD

**Issue by jalkestrup** [git-for-windows/git#1807]
Problem:
I can't use any regular windows ctrl+key commands such as copy (Ctrl+c) paste (ctrl+v), select all (ctrl+A) etc. within Git Bash. I'm new to Git, is that normal?

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

jalke@DESKTOP-07QL0PC MINGW64 ~
$ git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows [Version 10.0.17134.228]

 - What options did you set as part of the installation? Or did you choose the
   defaults? Default. 

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - Describe your problem in details.

If I'm trying to paste text, ex. link to git repository, The Bash terminal simply yiels "^V" instead of the content itself. I can use  shift+insert to paste instead. I have tried to go to options>keys and enable "compose key" - Ctrl. 

The Ctrl+key commands work in regular terminal.   

////////////////////////////////////////////////////////

Thanks for your help,

Kind regards
Jesper

**Comment by derrickstolee** [comment]
This is typical of Unix-style command windows. Specifically, CTRL+C is an important command to kill a process or erase the command you are typing.

Have you tried the following?

* Selecting automatically adds the selected text to the clipboard (replaces CTRL+C).
* SHIFT+INSERT or right-click and select "Paste" from the dropdown.
* Right-click and select "Select all" from the dropdown.

**Comment by jalkestrup** [comment]
Thanks for your help, that was simply the options I was looking for.
