### ISSUE TITLE
warning: failed to restrict file handles (2)

### ISSUE THREAD

**Issue by ravibpatel91** [git-for-windows/git#1809]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4 
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.228]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git chefeature/pep8_formation
```
 - What did you expect to occur after running these commands?

```
git: 'chefeature/pep8_formation' is not a git command. See 'git --help'.
```

 - What actually happened instead?

```
warning: failed to restrict file handles (2)

handle #0: 0000000000000184 (type 2, handle info (1) 7ffa
handle #1: 0000000000000144 (type 2, handle info (1) 1
handle #2: 000000000000014c (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

SUPPRESS_HANDLE_INHERITANCE_WARNING=1
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not Applicable

**Comment by dscho** [comment]
> git version 2.16.1.windows.4

Please upgrade. Not only will your reported problem go away, you will also be [a lot less vulnerable](https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version).
