### ISSUE TITLE
git submodule foreach fails in git for windows 2.x

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#181]
git submodule foreach fails in git for windows 2.x

I start git.exe in through a Console Application.
git 2.x does not work if `CreateNoWindow = true`, works if `false`

```
static void Main(string[] args)
{
	string git_1 = @"C:\Program Files (x86)\Git\cmd\git"; // git 1.9.5
	string git_2 = @"C:\Program Files\Git\cmd\git";  // git 2.4.0
	string[] gits = { git_1, git_2 };
	foreach (string git in gits)
	{
		for (int i = 0; i < 2; i++)
		{
			bool createNoWindow = i % 2 == 0 ? true : false;
			var psi = new ProcessStartInfo(git, "submodule foreach \"git clean -fxd\"")
			{
				UseShellExecute = false,
				CreateNoWindow = createNoWindow,
				RedirectStandardOutput = true,
				RedirectStandardError = true,
				RedirectStandardInput = false,
				WorkingDirectory = @"D:\editorconfig\editorconfig-core-c",
				// clone from https://github.com/editorconfig/editorconfig-core-c
			};
			Console.WriteLine(psi.FileName + " " + psi.Arguments);
			var p = Process.Start(psi);
			Console.WriteLine(psi.FileName + " " + psi.Arguments);
			p.OutputDataReceived += (o, e) => Console.WriteLine(e.Data);
			p.ErrorDataReceived += (o, e) => Console.WriteLine(e.Data);
			p.BeginOutputReadLine();
			p.BeginErrorReadLine();
			p.WaitForExit();
			Console.WriteLine("------");
		}
	}
}
```

Here is the output
```
C:\Program Files (x86)\Git\cmd\git submodule foreach "git clean -nxd"
Entering 'tests'
Would remove 1.txt
------
C:\Program Files (x86)\Git\cmd\git submodule foreach "git clean -nxd"
Entering 'tests'
Would remove 1.txt
------
C:\Program Files\Git\cmd\git submodule foreach "git clean -nxd"
C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 535: 0: Bad file descriptor
------
C:\Program Files\Git\cmd\git submodule foreach "git clean -nxd"
Entering 'tests'
Would remove 1.txt
------
````

No problem if you type `git submodule foreach "git clean -nxd"` directly in cmd.exe or in git bash

**Comment by linquize** [comment]
git-submodule Line 535:

	# dup stdin so that it can be restored when running the external
	# command in the subshell (and a recursive call to this function)
	exec 3<&0

**Comment by linquize** [comment]
The equivalent Win32 API `CreateProcess()`
with `dwCreationFlags = CREATE_NO_WINDOW`

**Comment by dscho** [comment]
Hmm. No idea about a proper fix yet, but you could maybe work around it by adding the command-line argument `</dev/tty`?

**Comment by dscho** [comment]
@linquize have you tried with `</dev/tty` yet?

**Comment by linquize** [comment]
where to add `</dev/tty`?

**Comment by dscho** [comment]
I actually meant `</dev/zero`. But the easier workaround should be to set `RedirectStandardInput = true`.

**Comment by linquize** [comment]
Modify line 535 of `git-submodule`?

**Comment by dscho** [comment]
> Modify line 535 of git-submodule?

Sure. But how? How do you test whether stdin is redirectable?

Have you tested the suggested workaround?

**Comment by dscho** [comment]
@linquize Have you tested the `RedirectStandardInput = true` workaround?

**Comment by linquize** [comment]
Yes, I tried `RedirectStandardInput = true` and it works for both git 1.9.5 and 2.x

**Comment by dscho** [comment]
Okay, then I close this ticket. Unless you have any idea how to fix this properly (I fear that would entail a patch to https://github.com/git-for-windows/MSYS2-packages/tree/master/bash...).
