### ISSUE TITLE
auto-updater check is broken when API rate limit exceeded 

### ISSUE THREAD

**Issue by douniwan5788** [git-for-windows/git#1813]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 6.1.7601]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**shared outbound ip/under proxy**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git update-git-for-windows
```
 - What did you expect to occur after running these commands?

```
Git for Windows 2.18.0.windows.1 (64bit)
Up to date
```

 - What actually happened instead?

```
Git for Windows 2.18.0.windows.1 (64bit)
Update  is available
Download and install  [N/y]? y
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

```

 ### What I found
The update check url (https://api.github.com/repos/git-for-windows/git/releases/latest) is API rate limit exceeded.
```
{
message: "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
documentation_url: "https://developer.github.com/v3/#rate-limiting"
}
```
and checking method is not solid enough to handle this situation
https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-update-git-for-windows#L141-L183

**Comment by douniwan5788** [comment]
@dscho @between2spaces @larsxschneider

**Comment by drizzd** [comment]
And while we are at it, we may want to add `--show-error` whenever we use `curl --silent` in order to tell the user what happened.

**Comment by chris-findlay** [comment]
So it's not just me then - which means I don't need to write it up (c:
Same build as immediately above.

**Comment by PhilipOakley** [comment]
Hi @chris-findlay @sschlesier @douniwan5788,

If you are able to contribute a little time to a PR that supports @drizzd 's suggestions so that at least users like yourselves get to see the error message (that we've hit a rate limit) then that would be a great assistance to the project, as it is a volunteer community effort.

Hoping you can help.

Philip

**Comment by drizzd** [comment]
@dscho Do you see a possibility to host GFW releases elsewhere to avoid the rate limit entirely?

Otherwise, how about a firebase cloud function which listens to Github events to mirror at least the release information, including the download link. I have some experience with that.

**Comment by drizzd** [comment]
I wouldn't mind doing the same thing with Azure, by the way.
