### ISSUE TITLE
Less crashes with STATUS_ACCESS_VIOLATION when core.pager is set

### ISSUE THREAD

**Issue by poke** [git-for-windows/git#1815]
Hey, since last night, I am getting the following error when I run things like `git log` or `git show` that invoke less to display data:

```
0 [main] less 48572 cygwin_exception::open_stackdumpfile: Dumping stack trace to less.exe.stackdump
```

The stackdump mentions a `STATUS_ACCESS_VIOLATION` exception at the beginning, so I am not sure what the cause for that is. I already checked other issues, like #1271. I do have the `$TERM` variable set to `msys` but changing that (to `cygwin` or removing it) does not help.

I am getting the exception in both PowerShell and cmd, but not on Git Bash. I originally used Git 2.18 x64 but just now installed 2.19.0.rc1 x64 to try if this changed anything. The error appears on both. I don’t know what changed about my system that made this problem suddenly appear. I could swear it happened after I tried applying a patch, but I could be wrong about that. I would guess that this is most likely caused by a recent Windows update (running version 10.0.17134.254 at the moment).

What *I did* find out however is that the problem is apparently caused by my Git setting of `core.pager`. I have it set to `less -x1,5`. If I remove that setting from my `.gitconfig`, or change it to just `less`, everything appears to work again. I *do* have the setting to `less -x1,5` active on other and similar machines though, so there shouldn’t be a problem with it by itself.

I totally understand that this issue is very likely very difficult to debug remotely. So if you have any ideas, I am happy to try your suggestions.

---

Just for completeness (in case that is actually helpful), here’s the full stackdump:
```
Exception: STATUS_ACCESS_VIOLATION at rip=00180069E1F
rax=0000000000400000 rbx=00000006000384C8 rcx=0000000180320110
rdx=00000006000384C8 rsi=0000000180320138 rdi=00000006000384C8
r8 =0000000000000001 r9 =00000000FFFFFFFF r10=0000000100000000
r11=000000006C323666 r12=0000000180320110 r13=00000006000384C8
r14=0000000000000001 r15=0000000000000000
rbp=00000000FFFFC1E0 rsp=00000000FFFFC100
program=C:\Program Files\Git\usr\bin\less.exe, pid 42600, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFC1E0  00180069E1F (00000000CF0, 00000000000, 00000000000, 00600038450)
000FFFFC1E0  0018014415F (0006C318867, 000FFFFC3C0, 0006C321D15, 0000000007E)
000FFFFC328  0018011DE4B (0006C318867, 000FFFFC3C0, 0006C321D15, 0000000007E)
000FFFFC328  0006C323666 (0018011DE4B, 00600038450, 001803218E5, 00600038450)
000FFFFC328  0006C323723 (000563F7B8E, 587C51AF7D4B, 0010041B1C8, 000FFFFCC78)
000FFFFC328  0006C31A76F (FFFFFFFFFFFFFFFE, 00000000000, 00000000000, 00000000001)
00000000001  0006C31A907 (00000000000, 000FFFFC700, 000FFFFC6D0, 00000000000)
00000000001  00100401B4B (000FFFFCC70, 00180320BD0, 000FFFFCDF0, 000FFFFCC70)
00000000001  00100416853 (00000000020, 001802F7920, 00180047EB8, 00180046E80)
000FFFFCCD0  00180047F24 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045A03 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045AB4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

**Comment by PhilipOakley** [comment]
Could this be related to the `less` update? 

> "there was a bug discovered in `less` (see
https://public-inbox.org/git/CA+55aFxjUsvhHwQGthGiLr537BGHkd-LECXVv8KzBTMMCo1bKQ@mail.gmail.com/)"

This maybe just coincident, but it maybe worth a look. (reminded via @dscho 'Plans for Git for Windows v2.19.0' https://groups.google.com/d/msgid/git-for-windows/nycvar.QRO.7.76.6.1809041448490.71%40tvgsbejvaqbjf.bet.)

**Comment by rimrul** [comment]
Does it crash if you `LESS=-x1,5 git log` with your `core.pager` set to just `less`?

**Comment by poke** [comment]
@rimrul I am not using a unix shell (and the problem does not appear in Git Bash), so I cannot run it like that, but setting the environment variable before the call does work, e.g. (PowerShell):

```powershell
PS> $env:LESS = '-x1,5'
PS> git log
```

Or (cmd):
```cmd
> set LESS=-x1,5
> git log
```

**Comment by rimrul** [comment]
Oh, I didn't even think about looking what console you use... But it seems like a weird issue with the way git calls `core.pager` with arguments.

**Comment by dscho** [comment]
I cannot reproduce with Git for Windows v2.20.1 in PowerShell.
