### ISSUE TITLE
Warped RFC2822 Date format in git log --pretty=%aD

### ISSUE THREAD

**Issue by xt449** [git-for-windows/git#1819]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.228]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log --pretty=%aD
```
 - What did you expect to occur after running these commands?

Should return the date of the author in RFC2822 format:
`ddd, DD MMM YYYY HH:mm:ss ZZ`

 - What actually happened instead?

Returned the date of the author in a warped RFC2822 format:
`ddd, D MMM YYYY HH:mm:ss ZZ`
\* Where D is the day of the month, but shows just one digit when the first is 0.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Across all repositories

**Comment by rimrul** [comment]
[RFC2822](https://www.ietf.org/rfc/rfc2822.txt) does seem to allow single digit days:
>3.3. Date and Time Specification
>
>Date and time occur in several header fields.  This section specifies
   the syntax for a full date and time specification.  Though folding
   white space is permitted throughout the date-time specification, it
   is RECOMMENDED that a single space be used in each place that FWS
   appears (whether it is required or optional); some older
   implementations may not interpret other occurrences of folding white
   space correctly.
>
>date-time       =       [ day-of-week "," ] date FWS time [CFWS]
>
>day-of-week     =       ([FWS] day-name) / obs-day-of-week
>
>day-name        =       "Mon" / "Tue" / "Wed" / "Thu" /
                        "Fri" / "Sat" / "Sun"
>
>date            =       day month year
>
>year            =       4*DIGIT / obs-year
>
>month           =       (FWS month-name FWS) / obs-month
>
>month-name      =       "Jan" / "Feb" / "Mar" / "Apr" /
                        "May" / "Jun" / "Jul" / "Aug" /
                        "Sep" / "Oct" / "Nov" / "Dec"
>
>day             =       ([FWS] 1*2DIGIT) / obs-day
>
>time            =       time-of-day FWS zone
>
>time-of-day     =       hour ":" minute [ ":" second ]
>
>hour            =       2DIGIT / obs-hour
>
>minute          =       2DIGIT / obs-minute
>
>second          =       2DIGIT / obs-second
>
>zone            =       (( "+" / "-" ) 4DIGIT) / obs-zone
>
   >The day is the numeric day of the month.  The year is any numeric
   year 1900 or later.
>
  >[...]
>
   >A date-time specification MUST be semantically valid.  That is, the
   day-of-the-week (if included) MUST be the day implied by the date,
   the numeric day-of-month MUST be between 1 and the number of days
   allowed for the specified month (in the specified year), the
   time-of-day MUST be in the range 00:00:00 through 23:59:60 (the
   number of seconds allowing for a leap second; see [STD12]), and the
   zone MUST be within the range -9959 through +9959.

**Comment by xt449** [comment]
See `date --rfc-2822` for inconsistency.

**Comment by rimrul** [comment]
How is that relevant? Their implementation could be wrong, too. The RFC specifies the standard, Not some random version of some random posix tool. I've found 3 different man pages for date. One mentions --rfc-2822, one calls it --rfc-email and refers to RFC5322 and one doesn't mention anything RFC related flags. That's hardly a reference implementation.

-------- Originalnachricht --------
Betreff: Re: [git-for-windows/git] Warped RFC2822 Date format in git log --pretty=%aD (#1819)
Von: Binary Banana
An: git-for-windows/git
Cc: Matthias Asshauer ,Comment


See date --rfc-2822 for inconsistency.

**Comment by PhilipOakley** [comment]
Interestingly [Info on ISO 8601, the date and time representation standard](http://jkorpela.fi/iso8601.html) provides the example: `Fri, 8 May 1998 15:57:33 +0300 (EET DST)` as a historical common case from the older 822 standard, and goes on to discuss all the fun and games about dates.

[RFC2234 ](https://tools.ietf.org/html/rfc2234) does explain the day format rule (referenced by 2822)
```
3.6  Variable Repetition  
   The operator "*" preceding an element indicates repetition. The full
   form is:

        <a>*<b>element

   where <a> and <b> are optional decimal values, indicating at least
   <a> and at most <b> occurrences of element.

```
So the day (` 1*2DIGIT`) can be a single digit number, without a leading zero, so in that sense it is legal.

That doesn't mean it's desired in some cases (such as yours), but it is more human friendly...

**Comment by dscho** [comment]
Despite a missing acknowledgement from the original reporter, the comments by @rimrul and by @PhilipOakley are spot on: this is a misunderstanding of the RFC, not a bug.

**Comment by PhilipOakley** [comment]
@xt449 (supplemental) If you want to take 'it' further, then look at the `%ad` author date format (format respects --date= option), which has it's options listed in the `git log` man page [--date=<format>](https://git-scm.com/docs/git-log#git-log---dateltformatgt)./

If one of those formats, such as `iso` is not suitable, then it's time to get out those coding shoes and propose to upstream a variant of rfc2822 that enforces the double digit 'rule' (even better if you can locate the appropriate rfc/iso/whoever standard for it). 

It's likely to be fairly easy in terms of the choice between the one and two digit cases within the code. A nice wee endeavour for the Hogmanay activities. PRs welcomed.

**Comment by PhilipOakley** [comment]
Maybe call the extra `--date` option `rfc2822-strict` (though more correctly it maybe should be 'inflexible';-) or `rfc2822-dd` to indicate the double digit day code.
