### ISSUE TITLE
rm: failed to get attributes of '/': No such file or directory

### ISSUE THREAD

**Issue by lchiocca** [git-for-windows/git#182]
Im running PortableGit 2.4.2.windows.1 unzipped to c:\PortableGit2421. c:\git is a dir junction to that directory. "c:\git\cmd" is in the path. When I rebase a repo then I get this very strange message:
c:\workspace\git\XXX>git rebase
First, rewinding head to replay your work on top of it...
Fast-forwarded master to refs/remotes/origin/master.
rm: failed to get attributes of '/': No such file or directory

Using git-cmd give me the same failure, but git-bash does not. What am I missing? Should I be concerned that about a "rm /" ;)

**Comment by dscho** [comment]
@lchiocca please describe precisely the steps required to reproduce your problem.

**Comment by lchiocca** [comment]
I have tried too many things and at some stage the issue was gone. And to make it worse, I didn't backup the repo to be able to correctly reproduce the issue. Closing this issue and if I get back into that situation, I will raise another issue with all the correct steps and - if possible - a repo to reproduce it

**Comment by dscho** [comment]
@lchiocca thanks for following up on this!

**Comment by Zeex** [comment]
I have the same issue after installing the new Git for Windows distribution (previously used MsysGit). Every time I do `git rebase --abort` in my repository I see:

```
rm: failed to get attributes of ‘/’: No such file or directory
```

and the rebase doesn't abort after that.

**Comment by dscho** [comment]
@Zeex without much more complete information about your exact setup, I have nothing to go on...
