### ISSUE TITLE
git checkout is not reverting the changes on the file mode of the file

### ISSUE THREAD

**Issue by evandrocoan** [git-for-windows/git#1821]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Related issue: https://github.com/git-for-windows/git/issues/418 Make sure that the executable bit is handled properly 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.19.0.rc0.windows.1
cpu: x86_64
built from commit: f9c1a9c1a4c1bf131ccf13aeac422b3820fa382f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ type "C:\Program Files\Git\etc\install-options.txt"
bash: type: C:\Program Files\Git\etc\install-options.txt: not found

$ type "C:\Program Files (x86)\Git\etc\install-options.txt"
bash: type: C:\Program Files (x86)\Git\etc\install-options.txt: not found

$ type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
bash: type: %USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt: not found

$ cat /etc/install-options.txt
cat: /etc/install-options.txt: No such file or directory
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

mintty.exe from cygwin

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I tried to create a minimal example, but I got no success. On this minimal steps, the file just keep the executable flag when I switch between branches.
```sh
printf '\nCreate the directory structure\n'
rm -r -f main_repo
rm -r -f main_repo_remote
mkdir main_repo
mkdir main_repo_remote

cd main_repo
printf '\nSetup the main_repo\n'
printf "# Main Repo\\n\\n" > README.md
git init
chmod +x README.md
git add README.md
git commit -m "Added the main repository first commit."

printf '\nCreating a local remote\n'
git init --bare ../main_repo_remote
git remote add origin ../main_repo_remote
git push origin master
git checkout -b develop
git push origin develop

printf '\nAdded an executable file\n'
chmod -x README.md
git add README.md
git commit -m "Added the repository second commit."
git push origin master
git checkout master
```

 - What did you expect to occur after running these commands?
When switching between branches, the executable flag set should change.

 - What actually happened instead?
When switching between branches, the executable flag set is not changed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

The other problem is a file I have, and I cannot reproduce it from a clean fork from of the original package.

The only way to reproduce it, is to download this fork of the repository I have: [lark-parser.zip](https://github.com/git-for-windows/git/files/2362435/lark-parser.zip)

"Unzip Here" the zip file and run these commands:
```
cd lark-parser
git checkout -- examples/standalone/create_standalone.sh
git checkout master
```
-->
```
$ cd lark-parser
$ git checkout -- examples/standalone/create_standalone.sh
$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
        examples/standalone/create_standalone.sh
Please commit your changes or stash them before you switch branches.
Aborting
```

As you noticed, I just had did `git checkout` on the file `examples/standalone/create_standalone.sh`, but it says that the file have changes.

If you run `git diff`, you will see:
```
$ git diff
diff --git a/examples/standalone/create_standalone.sh b/examples/standalone/create_standalone.sh
old mode 100755
new mode 100644
$ git checkout -- examples/standalone/create_standalone.sh
$ git diff
diff --git a/examples/standalone/create_standalone.sh b/examples/standalone/create_standalone.sh
old mode 100755
new mode 100644
```

`git checkout` is not reverting the changes on the file mode of the file.

**Comment by PhilipOakley** [comment]
Is this a competition between GfW (Git-for-Windows) and Cygwin? 

As I understand it (I don't use cygwin), on cygwin every attempt is made to match the Linux/Posix filesystem moding. However on GfW that is not the case. The moding bits on GfW as pseudo stand ins and the true Windows concepts for file "moding" are used (e.g. is it an `.exe` file?). 

In particular, 'executable' bit is not a regular windows feature, so the moding change I think you are expecting doesn't really happen properly.

**Comment by mfriedrich74** [comment]
Git for Windows still needs to handle the x bit. This important if you work
on a linux repo on windows, like I do. Obviously on Windows you can check
if the bit is set only inside git bash, I also like to be able to verify
this bit on windows with ls.

**Comment by PhilipOakley** [comment]
> Git for Windows still needs to handle the x bit.

It does, but it can't be all things to all people. Defining the mapping semantics is tricky, especially in a FOSS code first environment (see [Brooks MMM](https://archive.org/stream/mythicalmanmonth00fred/mythicalmanmonth00fred_djvu.txt), or search for pdf; see system design vs software coding, try Ch 4 "What Does the Implementer Do While Waiting?").

Unfortunately, as yet, we do not have any special documentation _inside_ our Git repo/man for users that would enquire via that route. There are various [FAQs ](https://github.com/git-for-windows/git/wiki/FAQ)and [wiki ](https://github.com/git-for-windows/git/wiki)pages. 

Generating some Git-for-Windows(GfW) man pages (our Git) covering the GfW compatibility documentation within the GfW repo would be an extra workload for the maintainer (@dscho) that would need to be frictionlessly dovetailed into the process flow between upstream git.git and GfW, which already has it's fair share of pain points.

The executable bit (in GfW) is only held IIUC in the Index, and the repo metadata (trees). The repo data is immutable, but the mapping from File System (FS) to Index to repo **is not fully reciprocal,** and never can be. 

If the Index is 'blown away' by any activity, then on Linux it's easy to recover the current FS mode bits, but 'impossible' on plain Windows. GfW makes a set of reasoned choices (`.exe` or a `#!` shell?). It also has to decide when and where to apply the reciprocity, especially when git.git may have used the 'common Linux/Posix FS' assumption.

Patches/Pull Requests with a contribution for updated documentation in this area, or the addition of a wiki page, is/are welcomed.

**Comment by drizzd** [comment]
And therefore, chmod has no effect in the msys shell and it has no effect on Git. If a .sh file does not start with `#!` then Git will consider it as not executable, even if it is committed with the executable bit set. This explains why Git diff says the executable bit has been removed, even without making a change locally.

**Comment by PhilipOakley** [comment]
@drizzd Thanks for the extra clarification for this particular instance. I hadn't looked hard enough at @mfriedrich74 's specific case.

**Comment by dscho** [comment]
> > Git for Windows still needs to handle the x bit.
> 
> It does [...]

Well, it does, and it does not.

Git for Windows does *not* mark a file as executable. That is just not the way things work on Windows. If a file name has the `.exe` suffix, that file is executable. You cannot make it non-executable (unless you move it to a drive that disallows executing files).

However, since Git insists on this model, and since Git for Windows *is* used to collaborate with non-Windows developers, it is possible to use `git add --chmod=+x <file>` to mark a file as executable *in Git*.

That's as far as that support can go, methinks.
