### ISSUE TITLE
See "unlink" warning during clone operation

### ISSUE THREAD

**Issue by msoyka-of-wharton** [git-for-windows/git#1822]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10, 64-bit

$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.228]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I'm aware of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MSYS2 terminal/bash/mintty

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git clone https://sanctum.geek.nz/code/vim-replace-operator.git

 - What did you expect to occur after running these commands?

That the clone would complete without incident.

 - What actually happened instead?

I see the following warnings:

Cloning into 'vim-replace-operator'...
warning: unable to unlink 'C:/Temp/vim-replace-operator/.git/objects/e1/e196b846c81b7cffeef04cb4429d1981d4d025.temp': Invalid argument
warning: unable to unlink 'C:/Temp/vim-replace-operator/.git/objects/6b/986405dd83a70200d1dd73642df02b59d0742c.temp': Invalid argument
warning: unable to unlink 'C:/Temp/vim-replace-operator/.git/objects/12/878740efdf460fdbc917092ae0b7c00ee84667.temp': Invalid argument

Nonetheless, the clone operation appears to have succeeded in that "master" is checked out.  The 3 files listed above have not been deleted and all have size zero.  Git fsck reports "bad sha1 files" for each of the 3 files but nothing else.  

The unlink warnings occur more often than not for this repository.  In other words, if the clone is retried, sometimes they occur and sometimes they don't.  When they do occur, they may or may not happen on  the same files.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I have seen this happen with each of the following repositories:

https://sanctum.geek.nz/code/vim-juvenile.git/
https://sanctum.geek.nz/code/vim-perl-version-bump.git/
https://sanctum.geek.nz/code/vim-replace-operator.git/
https://sanctum.geek.nz/code/vim-squeeze-repeat-blanks.git/

I learned of these repositories through the Vim web site- they contain user-contributed Vim-scripts.  

I have also tried these clone operations using version 2.10.0.windows.1 on a 32-bit Windows XP system and see the same inconsistent behavior.

**Comment by dscho** [comment]
Sorry to have let this slip for so long (in the future, feel free to ping when you did not hear back for a couple of weeks).

The most common culprit for these types of issues is an overzealous anti-virus that still holds a handle on the files when they are to be removed.

This is only a warning, though, nothing to worry about, and I am almost 100% sure that one of the automatic garbage collection runs (that Git runs every once in a while) will remove those files, as intended.
