### ISSUE TITLE
Branch refs that differ by case only

### ISSUE THREAD

**Issue by vbjay** [git-for-windows/git#1823]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.228]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Running on windows which uses a case insensitive filesystem.  

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://github.com/gitextensions/gitextensions.git
git reset --hard 58f3b6c1f44260f61095df165e9c0c7b50c9f91f
git checkout -b Master
git reset --hard 7838172ac4b459ddc31e23a215d607c6a0093635
git checkout master
git pull origin master
git checkout Master
git reset --hard 58f3b6c1f44260f61095df165e9c0c7b50c9f91f
```
 - What did you expect to occur after running these commands?

branch master to point to wherever origin/master is pointing.

 - What actually happened instead?

master branch points to a different ref than origin/master because .git/refs/heads/Master and .git/refs/heads/master are the same file in windows.  This happened when my origin pointed to a commit before upstream/master.  See https://github.com/gitextensions/gitextensions/issues/5414

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?  

Should be the same on all repos on windows.

**Comment by vbjay** [comment]
Status that I ran the above script except I used upstream in the script.

![image](https://user-images.githubusercontent.com/3629489/45259579-4b0abe00-b39e-11e8-9799-6870fb62f50c.png)

**Comment by PhilipOakley** [comment]
This is a well known problem (search the closed issues) (though not well enough for newer users, a perennial issue). 

Git (Linux) assumes and expects that file name case is sensitive, while Windows is merely case preserving but case insensitive. As Git is the Linux reference DVCS, that aspect isn't going to change.

The internal Git code would need a lot of refactoring, and the use of slow Windows case checking routines to detect the issue, so it's not likely to be resolved soon/imminently, though folk are 'working' on the problem.
