### ISSUE TITLE
installing homebrew in mac

### ISSUE THREAD

**Issue by vivekxebian** [git-for-windows/git#1824]
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
git-remote-https(721,0x7fffe1c733c0) malloc: *** mach_vm_map(size=52428800000000000) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
git-remote-https(721,0x7fffe1c733c0) malloc: *** mach_vm_map(size=52428800000000000) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
fatal: Out of memory, malloc failed (tried to allocate 52428800000000000 bytes)
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force

How to resolve this ?

**Comment by shiftkey** [comment]
@vivekxebian this is the Git for Windows project, and not responsible for Git package for Homebrew. 

Please refer to their project for troubleshooting advice: https://github.com/Homebrew/brew#troubleshooting
