### ISSUE TITLE
How can I configure the language used?

### ISSUE THREAD

**Issue by liayn** [git-for-windows/git#183]
Hi!

I'm running git bash on a German Win 7.
While bash itself is set to English by default
```
$ asdklf
bash: asdklf: command not found
```
git seems to be configured to use German
```
$ git st
Auf Branch master
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
nichts zu committen, Arbeitsverzeichnis unverändert
```

I'd like to change git to use English as well.
How to achieve that?

Thanks.

**Comment by shiftkey** [comment]
From [StackOverflow](http://stackoverflow.com/a/10872202/1363815)

> Add these lines to your ~/.bashrc or ~/.bash_profile to force git to display all messages in English:
>
> ```
> # Set Git language to English
> #alias git='LANG=en_US git'
> alias git='LANG=en_GB git'
> ```

**Comment by liayn** [comment]
Got that working now.

I already tried it via `~./bashrc` before and it didn't work, that's why I posted here.
Now gave `~/.bash_profile` a shot and this work.

Is it a bug that `~./bashrc` is ignored or is that "a matter of fact"?

**Comment by dscho** [comment]
If you want to contribute to this project, you could look into adding the language option (with "Use default" as default) to the installer, [similar to the `fscache` feature](https://github.com/git-for-windows/build-extra/pull/26).

> Is it a bug that ~/.bashrc is ignored or is that "a matter of fact"?

This is a separate issue, please open a separate ticket.

**Comment by liayn** [comment]
Sorry, I'm not that deep into the topic of "linux emulation on windows".
So I've absolutely no clue where to start searching for
* defining a default language via installer
* finding the missing piece that `.bashrc` is ignored

**Comment by dscho** [comment]
@liayn at installer time, you cannot access the `.bashrc` -- or more appropriately, `.bash_profile`, because you want to run this *once* per Bash session, not for every shell script and sub shell -- of every user. Therefore, you would write the setting into `/etc/profile.d/env.sh`.
