### ISSUE TITLE
Reporting bug as requested

### ISSUE THREAD

**Issue by ionFreeman** [git-for-windows/git#1834]
hint: Waiting for your editor to close the file... warning: failed to restrict file handles (2)

handle #0: 00000000000003e4 (type 3, handle info (1) 24a
handle #1: 00000000000003e8 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn /bin/vim: No such file or directory
error: unable to start editor '/bin/vim'
Not committing merge; use 'git commit' to complete the merge.

**Comment by shiftkey** [comment]
@sivssdn Thanks for reporting! This is a known bug in that version that has now been fixed, so it's time to update.

Update either via https://gitforwindows.org/ which will detect your OS type, or via https://github.com/git-for-windows/git/releases/

**Comment by ionFreeman** [comment]
OK, thanks!

---- On Sat, 15 Sep 2018 09:47:16 -0400 notifications@github.com wrote ----

@sivssdn Thanks for reporting! This is a known bug in that version that has now been fixed, so it's time to update.

Update either via https://gitforwindows.org/ which will detect your OS type, or via https://github.com/git-for-windows/git/releases/
