### ISSUE TITLE
Bug Encounter

### ISSUE THREAD

**Issue by sivssdn** [git-for-windows/git#1835]
On executing git commands, I get the following error and it also says to report this bug on this particular URL.
warning: failed to restrict file handles (2)

### Setup

 - Git version: 2.16.2.windows.1
 - Windows 10, 64 bit 

```
** insert your machine's response here **

handle #0: 0000000000000008 (type 2, handle info (1) 7ff8
handle #1: 00000000000000fc (type 2, handle info (1) 1
handle #2: 0000000000000100 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

**Comment by shiftkey** [comment]
@sivssdn Thanks for reporting! This is a known bug in that version that has now been fixed, so it's time to update.

Update either via https://gitforwindows.org/ which will detect your OS type, or via https://github.com/git-for-windows/git/releases/
