### ISSUE TITLE
Experimental Builtin Rebase fails to use the committer identity signing key

### ISSUE THREAD

**Issue by nebularg** [git-for-windows/git#1836]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.0.windows.1
cpu: x86_64
built from commit: d96bb8bc6c636a8869140e860e72e7bdf64bd790
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.285]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```

Editor Option: VIM
Path Option: Cmd
Plink Path: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Rebase: Enabled
Enable Builtin Stash: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

mintty/Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git config user.signingkey
DC35E715

$ git config commit.gpgsign
true

$ git rebase -i
error: switch `S' requires a value

```
 - What did you expect to occur after running these commands?

The keyid should be optional and default to user.signingkey and rebase should run.

 - What actually happened instead?

Rebase errors about an optional value. It works correctly if you pass -SDC35E715, set rebase.useBuiltin to false, or set commit.gpgsign to false.

**Comment by shiftkey** [comment]
#1847 also has some extra information about the issue

**Comment by dscho** [comment]
Thank you all for the excellent analysis! I figured out the problem: by mistake, the *optional* argument of the `-S` option was not optional but mandatory. Technically, only the `rebase -i` fix is required to fix this here issue, but I was already working on the built-in stuff, and the non-interactive `rebase` *also* needs this fix.
