### ISSUE TITLE
symbolic links - core.symlinks=true does not work - you might want to revisit problem --

### ISSUE THREAD

**Issue by aabatpurdue** [git-for-windows/git#1838]
Contrary to your documentation ala making symlinks
`core.symlinks=true` does not work for me

but setting the environment variable
`enable MSYS=winsymlinks:nativestrict` does work.

In my HOME directory:
 $ touch a
 $ ln -s a b
  $ ls -l a b
-rw-r--r-- 1 aab 197121 0 Sep 16 21:19 a
lrwxrwxrwx 1 aab 197121 1 Sep 16 21:19 b -> a
 $ rm a b
The Command Prompt `dir a b` agrees with the above.  See "interesting things" below.
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

$ git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows [Version 10.0.17134.285]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Don't remember

** insert your machine's response here **
$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I disabled the _Git for Windows_ `core.symlinks=true` option because it was not working.  Just for grins, I did
`export MSYS=winsymlinks:nativestrict`
and voila no problems with real symlinks.

For me the ONLY way to get real symlinks on the entire system for any condition REQUIRES enabling
`settings -> Update & Security -> For Developers -> Developer Mode`
Unfortunately, this requires a sysadmin to do so.  The account that I normally use does have admin privileges enabled.  I also created a **vanilla** user that has a minimal set of privileges.  I have no problems making symlinks with either account.

FWIW - As a test, removed all policy permissions and was still able to make symlinks.

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/othe
bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

** insert your commands here **
See short example in first section above.  Without MSYS, `b` is a copy of `a`.  `core.symlinks=true` has no effect.  Without `Developer Mode" enabled, no real symlinks can be made,

 - What did you expect to occur after running these commands?
n/a
 - What actually happened instead?
n/a

**Comment by dscho** [comment]
`ln -s` is not a Git command, so it should not come as a surprise that it is unaffected by the Git config.

**Comment by aabatpurdue** [comment]
Ummm. So what does `core.symlinks=true` get me?  I agree about `ln -s ...`

**Comment by dscho** [comment]
> what does `core.symlinks=true` get me?

That `git.exe` will check out symbolic links stored in repositories.

FWIW I am not completely certain that I was righ about `ln -s`... while it is not a Git command, I would think that it makes sense to call *Git Bash* with the previously-mentioned `MSYS=winsymlinks:nativestrict`. Which means we would have to edit the shortcut. Maybe even edit `git-bash.exe`...

Would you be interested in that? I am too short on time to drive this, it would need to be you...

**Comment by dscho** [comment]
@aabatpurdue you surely meant to answer, though, right?

**Comment by dscho** [comment]
Right? Oh well, apparently not.
