### ISSUE TITLE
git command `update-git-for-windows` does not work when rc releases are installed

### ISSUE THREAD

**Issue by t-b** [git-for-windows/git#1843]
I recently installed rc2 of git for windows 2.19. After the final release of 2.19 I was not prompted with an update message (auto updates are enabled). Manually updating did not work, as `git update-git-for-windows` did not return anything.

On manual installation of 2.19 the installer asked me if I want to downgrade.

**Comment by dscho** [comment]
Correct. This is a long-standing bug, and I continue to fail time to work on this.

If you have time to spare, I would really welcome your help.

**Comment by t-b** [comment]
@dscho Thanks for verifying it. I'll see what I can do. Note to future self: Here is the place to dive into -> https://github.com/git-for-windows/build-extra/blob/54a4e3f9d0b43267fd9156551b70e7df82eb383b/git-extra/git-update-git-for-windows#L11.

**Comment by dscho** [comment]
@t-b not only there: the downgrade warning you mentioned is due to InnoSetup failing to detect from looking at the version number in the registry that it was an -rc version. I *think* we need to make our InnoSetup script smarter so that it stores an extra flag "isPrerelease" or some such, together with the version number *before* that. Maybe in the PreviousData? That information would then need to be picked up by the "is this a downgrade?" check.

**Comment by dscho** [comment]
I addressed this in the meantime.

**Comment by t-b** [comment]
This is unfortunately not fixed.

Here I get

```
$ git update
Warning! `git update` has been deprecated;
Please use `git update-git-for-windows` instead.
Git for Windows 2.32.0.rc0.windows.1 (64bit)
Update 2.31.1.windows.1 is available
Download and install Git for Windows 2.31.1 [N/y]?
```

**Comment by derrickstolee** [comment]
> This is unfortunately not fixed.
> 
> Here I get
> 
> ```
> $ git update
> Warning! `git update` has been deprecated;
> Please use `git update-git-for-windows` instead.
> Git for Windows 2.32.0.rc0.windows.1 (64bit)
> Update 2.31.1.windows.1 is available
> Download and install Git for Windows 2.31.1 [N/y]?
> ```

I think this is behaving as intended: the release candidate is a "pre release" but the latest full "release" is v2.31.1.windows.1. The updater is only comparing for exact string equality in the versions, so is not detecting that v2.32.0-rc0 is "newer" than v2.31.1.

Now, there might be room for an extension of the feature to perform a (signed) version comparison that will say if the latest release is _greater than_ your current release.

**Comment by rimrul** [comment]
This was fixed, but the original fix incorrectly assumed RC numbering to start at 1. git-for-windows/build-extra#347 extends that fix to cover rc0 as well. It'll be included in future rc0 pre-releases.

**Comment by PhilipOakley** [comment]
Just to say I've also experiencing the same issue that the updater isn't suggesting moving forward from the `rc*` installed version 😃 
```
phili@Philip-Win10 MINGW64 ~
$ git version
git version 2.32.0.rc2.windows.1

phili@Philip-Win10 MINGW64 ~
$ git up
Git for Windows 2.32.0.rc2.windows.1 (64-bit)

phili@Philip-Win10 MINGW64 ~
$ git update
Warning! `git update` has been deprecated;
Please use `git update-git-for-windows` instead.
Git for Windows 2.32.0.rc2.windows.1 (64-bit)

phili@Philip-Win10 MINGW64 ~
$ git update-git-for-windows
Git for Windows 2.32.0.rc2.windows.1 (64-bit)
```

I'll update/ manually install. https://github.com/git-for-windows/git/releases/

**Comment by PhilipOakley** [comment]
Note, my `git up` is an alias for the longer `git update-git-for-windows`...

**Comment by t-b** [comment]
Upgrading from rc fails to work here as well.

Today I did:

```
$ git update-git-for-windows
Git for Windows 2.34.0.rc2.windows.1 (64-bit)
$ git --version
git version 2.34.0.rc2.windows.1
```

and I had to manually install the new version.

If preferred I can also open a new bug. I can't reopen this here.

**Comment by dscho** [comment]
> Today I did:
> 
> ```
> $ git update-git-for-windows
> Git for Windows 2.34.0.rc2.windows.1 (64-bit)
> $ git --version
> git version 2.34.0.rc2.windows.1
> ```
> 
> and I had to manually install the new version.

You did not run the `git-update-git-for-windows` script with `-x`, did you?

**Comment by PhilipOakley** [comment]
On 16/11/2021 11:24, Thomas Braun wrote:
>
> Upgrading from rc fails to work here as well.
>

Same here. I was waiting for now to have another go at the problem. It
is, for me, still the `-` vs `.` problem between the two different
sources of 'truth' that are looked up. (IIRC) One is the value obtained
from the GfW web site (the `.txt` file), and the other from the local
`git version` command.

It is a difficult problem because there is only a *partial order* on
versions, as certain release candidates need to be bypassed, so we can
have A>B, while B!<A  around the rc versions.

> Today I did:
>
> $ git update-git-for-windows Git for Windows 2.34.0.rc2.windows.1
> (64-bit) $ git --version git version 2.34.0.rc2.windows.1
>
> and I had to manually install the new version.
>
> If preferred I can also open a new bug. I can't reopen this here.
>
>

**Comment by PhilipOakley** [comment]
On 16/11/2021 14:50, Philip Oakley wrote:
> On 16/11/2021 11:24, Thomas Braun wrote:
>> Upgrading from rc fails to work here as well.
>>
> Same here. I was waiting for now to have another go at the problem. It
> is, for me, still the `-` vs `.` problem between the two different
> sources of 'truth' that are looked up. (IIRC) 
Looks like that memory is no longer true. However (below..)

https://gitforwindows.org/latest-tag.txt -> "v2.34.0.windows.1" (no dashes)
$ git version  -> " git version 2.34.0.rc2.windows.1" (again no dashes)

> One is the value obtained
> from the GfW web site (the `.txt` file), and the other from the local
> `git version` command.
>
> It is a difficult problem because there is only a *partial order* on
> versions, as certain release candidates need to be bypassed, so we can
> have A>B, while B!<A  around the rc versions.

I did spot the --testing option in my C:\Program
Files\Git\mingw64\bin\git-update-git-for-windows version, and that does
offer the update.

at #L253 I inserted `echo "$latest|  $git_label $version ($arch_bit)"`
and got
    2.34.0.windows.1|  Git for Windows 2.34.0.rc2.windows.1 (64-bit)

That's just before the `echo "$git_label $version ($arch_bit)" >&2` line.

Setting -x hasn't helped me much.

But..
C:\Program Files\Git\mingw64\bin\git-update-git-for-windows#L38-41

all the `rc` cases are `-rc` patterns. So not yet sure if this is
significant but..


>
>> Today I did:
>>
>> $ git update-git-for-windows Git for Windows 2.34.0.rc2.windows.1
>> (64-bit) $ git --version git version 2.34.0.rc2.windows.1
>>
>> and I had to manually install the new version.
>>
>> If preferred I can also open a new bug. I can't reopen this here.
>>
>>

**Comment by t-b** [comment]
Nope I did not, cause I did not know.

Here is the output:
```
$ sh -x git-update-git-for-windows
+ test --test-version-compare '!=' ''
+ update_git_for_windows
++ git config --get http.proxy
+ proxy=
+ test -n ''
+ yn=
+ use_gui=
+ quiet=
+ testing=
+ test 0 -gt 0
+ case "$(uname -m)" in
++ uname -m
+ bit=64
+ try_toast=
+ test -z ''
+ test -f git-update-git-for-windows.config
+ fork=
+ test -n ''
+ git_label='Git for Windows'
+ releases_url=https://api.github.com/repos/git-for-windows/git/releases
+ latest_tag_url=https://gitforwindows.org/latest-tag.txt
+ latest_eval='latest=${latest_tag#v}'
++ http_get https://gitforwindows.org/latest-tag.txt
++ url=https://gitforwindows.org/latest-tag.txt
+++ mktemp -t gfw-httpget-XXXXXXXX.txt
++ output=/tmp/gfw-httpget-BztmNuwb.txt
+++ curl --silent --show-error --output /tmp/gfw-httpget-BztmNuwb.txt --write-out '%{http_code}' https://gitforwindows.org/latest-tag.txt
++ code=200
++ fdout=1
++ ret=0
++ test 200 -ge 400
++ cat /tmp/gfw-httpget-BztmNuwb.txt
++ rm -f /tmp/gfw-httpget-BztmNuwb.txt
++ return 0
+ latest_tag=v2.34.0.windows.1
+ eval 'latest=${latest_tag#v}'
++ latest=2.34.0.windows.1
+ latest=2.34.0.windows.1
+ test -z ''
++ get_recently_seen
++ '[' -f /c/Users/thomas/.git-for-windows-updater ']'
++ git config -f /c/Users/thomas/.git-for-windows-updater winUpdater.recentlySeenVersion
+ recently_seen=2.31.1.windows.1
+ test -n ''
++ git --version
++ sed 's/git version //'
+ version=2.34.0.rc2.windows.1
+ test -d /arm64/bin
+ arch_bit=64-bit
+ echo 'Git for Windows 2.34.0.rc2.windows.1 (64-bit)'
Git for Windows 2.34.0.rc2.windows.1 (64-bit)
+ test -z ''
+ test 2.34.0.windows.1 = 2.34.0.rc2.windows.1
+ test -n ''
++ version_compare 2.34.0.rc2.windows.1 2.34.0.windows.1
++ a=2.34.0.rc2.windows.1
++ b=2.34.0.windows.1
++ true
++ test -n 2.34.0.windows.1
++ test -n 2.34.0.rc2.windows.1
+++ expr 2.34.0.rc2.windows.1 : '^\([0-9]*\)'
++ a1=2
++ a=.34.0.rc2.windows.1
+++ expr 2.34.0.windows.1 : '^\([0-9]*\)'
++ b1=2
++ b=.34.0.windows.1
++ test -z 2
++ test -n 2
++ test 2 -le 2
++ test 2 -le 2
+++ expr .34.0.rc2.windows.1 : '^\([^0-9]\+\)'
++ a1=.
++ a=34.0.rc2.windows.1
+++ expr .34.0.windows.1 : '^\([^0-9]\+\)'
++ b1=.
++ b=34.0.windows.1
++ case "$a1,$b1" in
++ true
++ test -n 34.0.windows.1
++ test -n 34.0.rc2.windows.1
+++ expr 34.0.rc2.windows.1 : '^\([0-9]*\)'
++ a1=34
++ a=.0.rc2.windows.1
+++ expr 34.0.windows.1 : '^\([0-9]*\)'
++ b1=34
++ b=.0.windows.1
++ test -z 34
++ test -n 34
++ test 34 -le 34
++ test 34 -le 34
+++ expr .0.rc2.windows.1 : '^\([^0-9]\+\)'
++ a1=.
++ a=0.rc2.windows.1
+++ expr .0.windows.1 : '^\([^0-9]\+\)'
++ b1=.
++ b=0.windows.1
++ case "$a1,$b1" in
++ true
++ test -n 0.windows.1
++ test -n 0.rc2.windows.1
+++ expr 0.rc2.windows.1 : '^\([0-9]*\)'
++ a1=0
++ a=.rc2.windows.1
+++ expr 0.windows.1 : '^\([0-9]*\)'
++ b1=0
++ b=.windows.1
++ test -z 0
++ test -n 0
++ test 0 -le 0
++ test 0 -le 0
+++ expr .rc2.windows.1 : '^\([^0-9]\+\)'
++ a1=.rc
++ a=2.windows.1
+++ expr .windows.1 : '^\([^0-9]\+\)'
++ b1=.windows.
++ b=1
++ case "$a1,$b1" in
++ true
++ test -n 1
++ test -n 2.windows.1
+++ expr 2.windows.1 : '^\([0-9]*\)'
++ a1=2
++ a=.windows.1
+++ expr 1 : '^\([0-9]*\)'
++ b1=1
++ b=
++ test -z 1
++ test -n 2
++ test 2 -le 1
++ echo 1
++ return
+ test 0 -lt 1
+ return
```
