### ISSUE TITLE
git: 'credential-windcred' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by Szauka** [git-for-windows/git#1845]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
        - 64-bit
```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
        - Windows 10 Pro
        - Version 1709
        - 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.551]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull [<repository>]
```
 - What actually happened instead?

I get this.
```
git: 'credential-windcred' is not a git command. See 'git --help'.

The most similar command is
        credential-wincred
```
It does look like it's pooling though.

**Comment by dscho** [comment]
Does `git config --show-origin credential.helper` say that `windcred` should be used perchance? If so, this is configured incorrectly (but not by Git for Windows' installer: it does not try to set this).

**Comment by Szauka** [comment]
Hi @dscho,

 `git config --show-origin credential.helper` returns `store`.

Is that correct?

**Comment by dscho** [comment]
> `git config --show-origin credential.helper` returns `store`.
> 
> Is that correct?

In that case, `git-credential-store` should have been used. So I am puzzled why your system talks about `credential-windcred`...

**Comment by Szauka** [comment]
Solved it!

I found that there was another `.gitconfig` file that will be used apart from the default one and this one had the `credential.helper` set to `windcred`. Setting it to `manager` solved the issue.

Used `git config --list --show-origin` to find all the config files.

Thanks @dscho for pointing me in the corret direction.

**Comment by dscho** [comment]
I am glad you found it!
