### ISSUE TITLE
New experimental rebase not working

### ISSUE THREAD

**Issue by wolfy1339** [git-for-windows/git#1847]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.0.windows.1
cpu: x86_64
built from commit: d96bb8bc6c636a8869140e860e72e7bdf64bd790
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.285]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Rebase: Enabled
Enable Builtin Stash: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rebase -i HEAD~2
```
 - What did you expect to occur after running these commands?

For the rebase command editor to pop up

 - What actually happened instead?

It errored
```
$ git rebase -i HEAD~2
error: switch `S' requires a value
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by bbolli** [comment]
Can't reproduce here. What's the output of `GIT_TRACE=1 git rebase -i HEAD~2`?

**Comment by wolfy1339** [comment]
After digging through other issues pertaining to the experimental rebase, it seems a common problem when you have GPG commit signing. (Ref: #1836).
I had disabled it, since it wasn't working (via `git config --global rebase.useBuiltin false`), going to re-enable it and try with your command

**Comment by wolfy1339** [comment]
Here's the output:
```
$ GIT_TRACE=1 git rebase -i HEAD~2
13:42:27.091876 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:42:27.092868 git.c:415               trace: built-in: git rebase -i 'HEAD~2'
13:42:27.092868 run-command.c:637       trace: run_command: git config --bool rebase.usebuiltin
13:42:27.104277 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:42:27.107252 git.c:415               trace: built-in: git config --bool rebase.usebuiltin
13:42:27.126100 run-command.c:637       trace: run_command: GIT_CHERRY_PICK_HELP='Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".' git rebase--interactive --autosquash --upstream=f14f23623f93913f0fd35b2cd99b313ae5c640bf --onto=f14f23623f93913f0fd35b2cd99b313ae5c640bf '--onto-name=HEAD~2' --head-name=refs/heads/handidashboard --allow-empty-message -S
13:42:27.136021 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:42:27.140980 git.c:415               trace: built-in: git rebase--interactive --autosquash --upstream=f14f23623f93913f0fd35b2cd99b313ae5c640bf --onto=f14f23623f93913f0fd35b2cd99b313ae5c640bf '--onto-name=HEAD~2' --head-name=refs/heads/handidashboard --allow-empty-message -S
error: switch `S' requires a value
```

**Comment by bbolli** [comment]
It looks like the builtin rebase doesn't pick up the `user.signingKey` config. Would you report this to the Git mailing list `git@vger.kernel.org`, since the issue not Git for Windows specific?

**Comment by shiftkey** [comment]
@wolfy1339 @bbolli this feels like the same as #1836 - are we able to fold this up into that to avoid tracking duplicates?

**Comment by bbolli** [comment]
@shiftkey Yeah, sure! No need to have a duplicate.
