### ISSUE TITLE
the amazon download does not work 

### ISSUE THREAD

**Issue by veto64** [git-for-windows/git#1857]
hi,
your github/amazon download links are  very slow and crashing
https://git-scm.com/download/win
please give some other download options than from the  AMAZON cooperation

**Comment by dscho** [comment]
@veto64 gladly, if you have any resources to spare?

**Comment by veto64** [comment]
sure for the free software conservancy and resistance. 
at the moment only server resources.let me know

**Comment by Weyinmik** [comment]
hi,
@veto64 , when you say it is so slow, how slow? How do you compare?

**Comment by dscho** [comment]
> sure for the free software conservancy and resistance.
> at the moment only server resources.let me know

@veto64 so if you want to change the status quo (it seems you are looking to me for that change, but I am not the person who is interested enough, nor do I have time enough), you can make sure that you have enough resources available, and then open a PR for https://github.com/git-for-windows/build-extra/blob/master/please.sh, in particular the [`publish()`](https://github.com/git-for-windows/build-extra/blob/52001cc090b3c0f83cdf7f7c9778d3390544b202/please.sh#L3943-L4114) function that does all the work. We will then have to negotiate a way for you to get the secret to me so I can install it in the Azure Pipeline I use for publishing Git for Windows versions.

**Comment by dscho** [comment]
I guess I ask for too much? But then, it was not I who asked.
