### ISSUE TITLE
Git Bash for Windows expands glob patterns even when quoted

### ISSUE THREAD

**Issue by bberstel** [git-for-windows/git#1858]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.0.windows.1
cpu: x86_64
built from commit: d96bb8bc6c636a8869140e860e72e7bdf64bd790
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.285]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
bruno@Oberkampf MINGW64 ~
$ cd tmp

bruno@Oberkampf MINGW64 ~/tmp
$ cat > foo.java
public class foo {
	public static void main(String[] args) {
		System.out.println(args.length + " args:");
		for (String arg: args) System.out.println(arg);
	}
}

bruno@Oberkampf MINGW64 ~/tmp
$ javac foo.java

bruno@Oberkampf MINGW64 ~/tmp
$ ll
total 9
-rw-r--r-- 1 bruno 197613 705 Oct  2 17:25 foo.class
-rw-r--r-- 1 bruno 197613 156 Oct  2 17:25 foo.java

bruno@Oberkampf MINGW64 ~/tmp
$ java foo
0 args:

bruno@Oberkampf MINGW64 ~/tmp
$ touch a.txt b.txt

bruno@Oberkampf MINGW64 ~/tmp
$ java foo *.txt
2 args:
a.txt
b.txt

bruno@Oberkampf MINGW64 ~/tmp
$ java foo "*.txt"
2 args:
a.txt
b.txt

bruno@Oberkampf MINGW64 ~/tmp
$ java foo '*.txt'
2 args:
a.txt
b.txt

bruno@Oberkampf MINGW64 ~/tmp
$ java foo \*.txt
2 args:
a.txt
b.txt

bruno@Oberkampf MINGW64 ~/tmp
$ java foo '*.txtd'
1 args:
*.txtd

```
 - What did you expect to occur after running these commands?

I would expect the glob patterns NOT to be expanded when quoted. Note that `"*.txt"` is not expanded when passed to `echo` or `ls`, but is when passed to the small Java program (and that program is so small that it cannot be suspected that it expands the pattern).

 - What actually happened instead?

The pattern was expanded, defeating the quotes around it.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is not dependent of a repo. Actually it seems independent from Git.

**Comment by asheiduk** [comment]
It seems this is surprising behaviour of `java` itself:

    $ cmd
    C:\>ver
    Microsoft Windows [Version 10.0.17134.320]
    C:\> echo java *.txt
    java foo *.txt

So `cmd` does not expand the arguments but...

    C:\> java foo *.txt
    2 args:
    a.txt
    b.txt

a `java does!

This [Stackoverflow Answer][1] sheds some light onto this undocumented issue and links to further usefull stuff. Another interesting note is [this comment][2] in a bug report for Eclipse - it confirms the behaviour checking with Sysinternals Procexp.

So `java` on Windows tries to mimic Unix. But if a Windows-Java is started from a Unix-"emulator" ...  strange things happen. But I guess that git-for-windows will not add special cases for `java`.

[1]: https://stackoverflow.com/a/25948775/947357
[2]: https://bugs.eclipse.org/bugs/show_bug.cgi?id=212264#c11

**Comment by bberstel** [comment]
Thanks for this precious info. It is indeed surprising to see the Java interpreter on Windows try to mimic Unix. And the cmd-bash comparison is useful, too.

Yet, Java under cmd honors quotes:
```
C:\>java foo "*.txt"
1 args:
*.txt
```

while (as illustrated earlier) it does not under git-bash for Windows. So I'm afraid there is still something.

**Comment by dscho** [comment]
> So I'm afraid there is still something

Probably that "something" is that the quotes are passed to `java` when you call it in CMD, but in Git Bash, they are interpreted by the Bash!

I could imagine that `java foo '"*.txt"'` would work in Bash.

In any case, this ticket seems to be *pretty* far off from any *Git* bug. Therefore I'll close this ticket.
