### ISSUE TITLE
"failed to restrict file handles" when typing "git tfs/default"

### ISSUE THREAD

**Issue by feelingsofwhite** [git-for-windows/git#1860]
with git-tfs bridge installed
I accidentally typed
"git tfs/default" 

and received 

warning: failed to restrict file handles (2)

handle #0: 000000000000004c (type 2, handle info (1) 7ffd
handle #1: 00000000000000f0 (type 2, handle info (1) 1
handle #2: 00000000000000f4 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'tfs/default' is not a git command. See 'git --help'.

So I'm reporting it.
Seemed repeatable, same result when typing it again

**Comment by dscho** [comment]
I have to guess that your Git for WIndows version is outdated (there have been many similar reports about versions <v2.18.0).

Can you please update and try again?
