### ISSUE TITLE
Cannot start git-bash maximized

### ISSUE THREAD

**Issue by Bilge** [git-for-windows/git#1865]
Although the operating system provides a mechanism to specify the window mode when the application starts up (normal/minimized/maximized), git-bash ignores this user preference and always starts in windowed (*normal*) mode.

![image](https://user-images.githubusercontent.com/470626/46529192-b35d9a00-c88d-11e8-835c-07c36075e3ad.png)

If the user wishes to start git-bash maximized, this setting should be respected.

---
N.B. @mintty has confirmed [this is not a mintty limitation](https://github.com/mintty/mintty/issues/806#issuecomment-427362957).

**Comment by mintty** [comment]
The request is simply about configuring maximized mode initially, not further intelligence.
@Bilge, did you try to add an explicit `-w max` parameter to git-bash?
Otherwise, the wrapper may detect shortcut properties, using the GetStartupInfo function, and maybe pass on the desired window state to mintty via command line parameter (or STARTUPINFO again...).

**Comment by Bilge** [comment]
Passing `-w max` to git-bash causes it to close immediately after it starts.

**Comment by dscho** [comment]
@Bilge you will need to edit the resources of `git-bash.exe`, using the `edit-git-bash.exe` that is included in the installer (but it is removed after installing).

Or you use [`ResEdit`](http://www.resedit.net/).

**Comment by Bilge** [comment]
@dscho That doesn't seem very intuitive or user-friendly.

**Comment by dscho** [comment]
@Bilge I agree. What I tried to give to you is a way to test this method. And once it works, I can help you turn it into an option in the Git for Windows installer (that will be remembered across upgrades). Are you up to the challenge?

**Comment by Bilge** [comment]
No, I'm busy. And it shouldn't be an installer option, it should work as
expected with zero configuration, by respecting the shortcut specification.

**Comment by PhilipOakley** [comment]
@Bilge, it still needs coding though, as the `mintty` response indicated. It's the old itchy and scratchy problem ;-)

**Comment by dscho** [comment]
> No, I'm busy.

Well, I tried to help. Let us know when your situation changes.

> And it shouldn't be an installer option, it should work as expected with zero configuration, by respecting the shortcut specification.

Since you know much more about this than I do (obviously!), you are in a much better position to work on this than I am.

Besides, this is open source, baby ;-)

**Comment by galaxylegand** [comment]
Maybe a little rusty on JavaScript or
 Java v's comd

**Comment by mintty** [comment]
I tried to find the source of the git-bash wrapper yesterday to check if I can help out but it's well hidden in the project dungeons...

**Comment by PhilipOakley** [comment]
It will be in the https://github.com/git-for-windows/build-extra repository, but I haven't had a delve to find the particular location. Maybe start at the [Installer](https://github.com/git-for-windows/build-extra/tree/master/installer) directory

**Comment by dscho** [comment]
> I tried to find the source of the git-bash wrapper yesterday to check if I can help out but it's well hidden in the project dungeons...

@mintty It is built as part of the `mingw-w64-git` package:

- https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/mingw-w64-git.mak#L21
- https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/git-wrapper.c

**Comment by mintty** [comment]
You may try the patch below. As I don't have a git-for-windows development environment, I cannot test it myself.

```
--- orig/git-wrapper.c	2018-10-23 11:37:06.425924800 +0000
+++ ./git-wrapper.c	2018-10-23 12:05:20.739796000 +0000
@@ -509,6 +509,22 @@ static void initialize_top_level_path(LP
 
 int main(void)
 {
+	// retrieve ShowWindow properties
+	STARTUPINFOW sui;
+	GetStartupInfoW(&sui);
+	WORD showWindow = sui.dwFlags & STARTF_USESHOWWINDOW
+			? sui.wShowWindow
+			: SW_SHOW;
+	// retrieve further Startup properties that could be useful
+	int invoked_with_appid = sui.dwFlags & STARTF_TITLEISAPPID;
+	int invoked_from_shortcut = sui.dwFlags & STARTF_TITLEISLINKNAME;
+	if (invoked_from_shortcut) {
+		// icon could be retrieved from sui.lpTitle
+	}
+	// optionally manipulate showWindow otherwise, e.g. from cmd parameters
+	// if (max) showWindow = SW_SHOWMAXIMIZED;
+	// if (...) showWindow = ...;
+
 	int r = 1, wait = 1, prefix_args_len = -1, needs_env_setup = 1,
 		is_git_command = 1, full_path = 1, skip_arguments = 0,
 		allocate_console = 0, show_console = 0,
@@ -653,7 +669,7 @@ int main(void)
 		}
 		if (show_console) {
 			si.dwFlags |= STARTF_USESHOWWINDOW;
-			si.wShowWindow = SW_SHOW;
+			si.wShowWindow = showWindow;
 		}
 		br = CreateProcess(/* module: null means use command line */
 				exep,
```

**Comment by dscho** [comment]
This feature will need somebody who wants it badly enough to actually put in some effort.

**Comment by MichaelDunkel** [comment]
I was searching for a solution, when I found this. Top answer took 30 seconds and works for me. 
https://stackoverflow.com/questions/33991079/git-bash-mintty-how-to-open-maximized?answertab=votes#tab-top

**Comment by dscho** [comment]
> Top answer took 30 seconds and works for me.
> https://stackoverflow.com/questions/33991079/git-bash-mintty-how-to-open-maximized?answertab=votes#tab-top

For the record, this suggests to put

```
Window=max
```

into e.g. `~/.minttyrc`.

Which sounds like a pretty painless solution, in particular given the reluctance to work with @mintty to try any patches and give feedback.
