### ISSUE TITLE
Distribute icon

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#187]
The stable release at git-scm.com used to install the git icon at `etc\git.ico`.  This was useful for other programs (such as `ConsoleZ`) that might use git in some way.  The current preview release does not include an ico file that I can find.

**Comment by linquize** [comment]
git-for-windows 2.x icon is different from the old one.
The new icon has 4 colors: red, yellow, green, blue.
The old one is the same as official git icon, which is all orange.

**Comment by kjeremy** [comment]
Yep.  I was hoping a .ico file would be installed.

**Comment by dscho** [comment]
It is installed into `mingw64/share/git/git-for-windows.ico` for use by Git for Windows' own scripts.
