### ISSUE TITLE
git credential-manager is causing huge delays

### ISSUE THREAD

**Issue by patryksuchowierski** [git-for-windows/git#1874]
* [x]  I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
 - What did you expect to occur after running these commands?

I expected it to run faster.

 - What actually happened instead?

It takes long for any remote git operation to complete due to git credential manager execution, I believe.
I tried adding all git related assemblies to firewall rules, I've checked my anti-virus (McAffe) and it doesn't seem to be the problem.

```
19:19:41.362598 http.c:724              == Info: Connection #0 to host xxxx.visualstudio.com left intact
19:19:41.363597 run-command.c:637       trace: run_command: 'git credential-manager get'
19:20:08.287401 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
```

```
19:21:01.117519 http.c:724              == Info: Connection #1 to host xxxx.visualstudio.com left intact
19:21:01.118506 run-command.c:637       trace: run_command: 'git credential-manager store'
19:22:12.622660 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
```

**Comment by PhilipOakley** [comment]
See git-for-windows/git#1868 and https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/774 and the solution (of that problem) to install the (very) new release of the Git-Credential-Manager. It may be an underlying issue for you.

Other things that can cause problems are the Anti Virus scanners which tend not to like Git..

**Comment by patryksuchowierski** [comment]
> See [git-for-windows/git#1868](https://github.com/git-for-windows/git/issues/1868) and [Microsoft/Git-Credential-Manager-for-Windows#774](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/774) and the solution (of that problem) to install the (very) new release of the Git-Credential-Manager. It may be an underlying issue for you.
> 
> Other things that can cause problems are the Anti Virus scanners which tend not to like Git..

Thank you for your reply. Unfortunately, I'm using the newest version of GCM (1.18.1). I'm afraid I'll have to keep on fighting with my AV.

**Comment by dscho** [comment]
Moving the discussion to https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/786
