### ISSUE TITLE
Git Gui open file error handling

### ISSUE THREAD

**Issue by ssrinath** [git-for-windows/git#1877]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.18.0 windows 1 (64 bit)
```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 - 64 bit
```
$ cmd.exe /c ver


** insert your machine's response here **
```Microsoft Windows [Version 10.0.17134.286]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

``` Mostly defaults
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
command prompt

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
git-guit (or open from a folder in folder explorer, right-click and start git-gui)
 - What did you expect to occur after running these commands?


** insert here **
I changed to teh directory where I had already cloned and .git was available. I then opened git-gui. Should have opened with the checked out repo and branch details for me to rescen or stage or commit etc.


 - What actually happened instead?

** insert here **
It came out with the windows asking me to clone a new repo, clone an existing repo, or open existing repo etc. I think the reason was, I had cloned in a network shared directory and when git-gui was trying to access .git or other related information, due to slow or bas connection, it could not. Instead of showing or warning me that no .git was found and the based on my response it could have asked me to clone existing or new or open existing repo. So the file opening error handling could have been better.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
I really hoped that anybody else could make sense of this bug report, because I sure cannot.

@ssrinath could you kindly try your hand at a more complete bug report, especially at an [MCVE](https://stackoverflow.com/help/mcve)?
