### ISSUE TITLE
Windows 10 cannot close existing git (sh.exe) when running setup

### ISSUE THREAD

**Issue by kvernon** [git-for-windows/git#1879]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 2.19.1 64

```
$ git --version --build-options
stunning the installer
** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 pro 64
```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.17134.285]
 - What options did you set as part of the installation? Or did you choose the
   defaults?
I cannot make it through the install because I cannot seem to figure out how to stop sh.exe, which is my question to you all.
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
Hi @kvernon , a bit more detail about where in the process you were and those other useful tidbits listed in the template might help, as, at the moment, I wouldn't even know where to start. Perhaps an MVCE statement?

**Comment by dscho** [comment]
"a bit more detail" ;-)

I strongly suspect that there was an open Git Bash somewhere (which is the culprit; all Git processes need to be exited before a successful upgrade), but there is literally no evidence to go on.

So I will close this ticket as invalid until the time when more information is made available.
