### ISSUE TITLE
Decorate bare repository's folder with a Git icon

### ISSUE THREAD

**Issue by YueLinHo** [git-for-windows/git#1883]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 6.1.7601]
```
(版本: Version)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Enabled
Enable Builtin Stash: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init --bare
```
 - What did you expect to occur after running these commands?

**Decorate bare repository's folder with a Git icon**
Something like this:
![image](https://user-images.githubusercontent.com/5831804/46926146-1e635980-d062-11e8-978c-9a9ab1832c1c.png)
![image](https://user-images.githubusercontent.com/5831804/46926147-23c0a400-d062-11e8-9baf-4f3ed76f1485.png)
From [comment of TortoiseGit issue 3154](https://gitlab.com/tortoisegit/tortoisegit/issues/3154#note_108568489)

 - What actually happened instead?

no folder icon

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Nope. It's a enhancement.

**Comment by PhilipOakley** [comment]
> TortoiseGit just added this feature (cf. TortoiseGit/TortoiseGit@0705be7, there you also find an improved version of the first icon)

@csware Is this something tfat could be cherry-picked to create a PR? (I see the code looks to have a suitable licence, but didn't check the artwork...)

**Comment by dscho** [comment]
I don't think we can do this in Git for Windows, as we explicitly stopped shipping with a shell extension for Windows Explorer.

In any case, the enthusiasm by the OP to work on this has been somewhat low, so let's just close this ticket.
