### ISSUE TITLE
Pay down technical debt

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#1884]
This is a meta work item, really: I spent some two days last week to perform a merging-rebase of our `master` onto itself, with the sole purpose of reordering patches/patch series into a shape that allows us to know exactly where we are with the patches. One outcome is the `ready-for-upstream` branch thicket, combining all of the patch series I deem ready for upstream. Here is the check list (the idea being to check every patch series as it is chomped off the list):

- [x] mingw-isatty-and-dup2
- [x] mingw-expand-absolute-user-path
- [x] mingw-git.res-bitness
- [x] mingw-load-sys-dlls
- [x] test-git-installed
- [x] fix-gc-segfault
- [x] azure-pipelines
- [x] mingw-CreateHardLink
- [x] require-windows-vista-or-later
- [x] file-url-to-unc-path
- [x] http-ssl-backend
- [x] bw/config-h
- [x] test-unc-fetch
- [x] unc-path-w-backslashes
- [x] release-gc-repack
- [x] drive-prefix
- [x] case-insensitive-abspath
- [x] jeffhostetler/register_rename_src
- [x] gitdir-at-unc-root
- [x] test-unc-alternates
- [x] mingw-safer-compat-poll
- [x] create-empty-bundle
- [x] unmask-credentials-username
- [x] aslr
- [x] mingw-getcwd
- [x] sideband-bug
- [x] fix-externals
- [x] remote-hg-prerequisites
- [x] add-e-truncate
- [x] cvsexportcommit-crlf
- [x] reset-stdin
- [x] unhidden-git
- [x] perl5lib
- [x] mingw-modernize-pthread_cond_t
- [x] default-ident

**Comment by dscho** [comment]
`http-ssl-backend` is tracked here: https://github.com/gitgitgadget/git/pull/46

**Comment by jamill** [comment]
`fix-gc-segfault` is tracked here: https://github.com/gitgitgadget/git/pull/47

**Comment by jamill** [comment]
`aslr` is tracked here: https://github.com/gitgitgadget/git/pull/48

**Comment by dscho** [comment]
`nanosecond-file-times` (which was not even listed, but which I prepared for upstream in the meantime) is tracked here: https://github.com/gitgitgadget/git/pull/53

**Comment by dscho** [comment]
`mingw-getcwd` (which needed to be adjusted to even compile, relative to what is in our `ready-to-upstream` thicket, as detected while working on moving the `nanosecond-file-times` patches to the bottom of the stack) is tracked here: https://github.com/gitgitgadget/git/pull/54

**Comment by dscho** [comment]
`mingw-load-sys-dl` is tracked here: https://github.com/gitgitgadget/git/pull/55

**Comment by dscho** [comment]
`mingw-isatty-and-dup2` is tracked here: https://github.com/gitgitgadget/git/pull/61

**Comment by dscho** [comment]
`perl5lib` is tracked here: https://github.com/gitgitgadget/git/pull/62

**Comment by dscho** [comment]
`require-windows-vista-or-later` is tracked here: https://github.com/gitgitgadget/git/pull/44

**Comment by dscho** [comment]
`mingw-safer-compat-poll` is tracked here: https://github.com/gitgitgadget/git/pull/64

**Comment by dscho** [comment]
`gitdir-at-unc-root` is tracked here: https://github.com/gitgitgadget/git/pull/65 (opened by @jamill)

**Comment by dscho** [comment]
`mingw-expand-absolute-user-path` is tracked here: https://github.com/gitgitgadget/git/pull/66

**Comment by dscho** [comment]
`mingw-git.res-bitness` is tracked in https://github.com/gitgitgadget/git/pull/67

**Comment by dscho** [comment]
`test-git-installed` is tracked in https://github.com/gitgitgadget/git/pull/73

**Comment by dscho** [comment]
`mingw-CreateHardLink` is tracked in https://github.com/gitgitgadget/git/pull/77

**Comment by dscho** [comment]
`create-empty-bundle` is tracked in https://github.com/gitgitgadget/git/pull/79

**Comment by dscho** [comment]
`mingw-modernize-pthread_cond_t` is tracked in https://github.com/gitgitgadget/git/pull/80

**Comment by dscho** [comment]
Let's hold off from sending more patches upstream, as we are [in the code freeze period leading up to Git v2.20.0](https://tinyurl.com/gitCal).

**Comment by dscho** [comment]
`file-url-to-unc-path` is tracked in https://github.com/gitgitgadget/git/pull/93.

**Comment by dscho** [comment]
` unc-path-w-backslashes` is tracked in https://github.com/gitgitgadget/git/pull/94

**Comment by dscho** [comment]
` release-gc-repack` is tracked in https://github.com/gitgitgadget/git/pull/95

**Comment by dscho** [comment]
`drive-prefix` is tracked in https://github.com/gitgitgadget/git/pull/96

**Comment by dscho** [comment]
`add-e-truncate` is tracked in https://github.com/gitgitgadget/git/pull/107

**Comment by dscho** [comment]
* `mingw-safer-compat-poll` had one obsolete patch, here is the PR to revert it out of Git for Windows: https://github.com/git-for-windows/git/pull/2092

* `ansi-unicode` is tracked in https://github.com/gitgitgadget/git/pull/147
* `program-data-config` is tracked in https://github.com/gitgitgadget/git/pull/148
* `no-perl-makemaker` is tracked in https://github.com/gitgitgadget/git/pull/146
* `msvc` is tracked in https://github.com/gitgitgadget/git/pull/149
* `dont-spawn-gzip-in-archive` is tracked in https://github.com/gitgitgadget/git/pull/145
* `open-in-gdb` is tracked in https://github.com/gitgitgadget/git/pull/150
* `remove-ipv6-fallback` is tracked in https://github.com/gitgitgadget/git/pull/144
* `funny-cased-cwd` is tracked in https://github.com/gitgitgadget/git/pull/151
* `file-url-to-unc-path` is tracked in https://github.com/gitgitgadget/git/pull/93
* `test-unc-fetch` is tracked in https://github.com/gitgitgadget/git/pull/143
* `register_rename_src` is tracked in https://github.com/gitgitgadget/git/pull/142
* `gitdir-at-unc-root` is now tracked in https://github.com/gitgitgadget/git/pull/141
* `test-unc-alternates` is tracked in https://github.com/gitgitgadget/git/pull/140
* `unmask-credentials-username` is tracked in https://github.com/gitgitgadget/git/pull/138
* `aslr` is now tracked in https://github.com/gitgitgadget/git/pull/134
* `sideband-bug` is tracked in https://github.com/gitgitgadget/git/pull/137
* `fix-externals` is tracked in https://github.com/gitgitgadget/git/pull/135
* `remote-hg-prerequisites` is tracked in https://github.com/gitgitgadget/git/pull/136
* `cvsexportcommit-crlf` is tracked in https://github.com/gitgitgadget/git/pull/132
* `reset-stdin` is tracked in https://github.com/gitgitgadget/git/pull/133
* `unhidden-git` is tracked in https://github.com/gitgitgadget/git/pull/131

* `visual-studio` is based on `msvc` and requires that patch series to hit `pu` at least.

**Comment by dscho** [comment]
I added GitGitGadget PRs for all of the branches in `ready-for-upstream` and am slowly submitting them. So let's close this here ticket, as the individual progress is tracked in those PRs.
