### ISSUE TITLE
Windows credentail manager not working

### ISSUE THREAD

**Issue by oldboysmith** [git-for-windows/git#1885]
When pushing a project to Azure DevOps, by using git on the command line in a cmd.exe window,  the credentials manager seems to fail on 2.19.1.  I reinstalled 2.18.0 and it started working again.

The error was:
_fatal: NullReferenceException encountered.
   Object reference not set to an instance of an object.
fatal: NullReferenceException encountered.
   Object reference not set to an instance of an object.
Password for ……..:_

My password would not work, but if I entered a personal access token it would display the error again, but then executed the push successfully.

When I reinstalled 2.18.0, it displayed the correct dialog box, I entered my password and it worked fine

**Comment by dscho** [comment]
This seems to be a duplicate of https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/779. Please install Git Credential Manager for Windows v1.18.2 and see whether it fixes your issue.

**Comment by oldboysmith** [comment]
I installed 2.19.1, then the Git Credential Manager 1.18.2, and now everything seems to work fine. Thank you
