### ISSUE TITLE
__git_ps1 is missing

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#189]
Every time I execute a command in git-bash I get:

`bash: __git_ps1: command not found`

This may be related to my old setup but I'm not sure.  Regardless `__git_ps1` is used in a lot of bash prompts and should be included.

**Comment by dscho** [comment]
[Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve), please.

**Comment by kjeremy** [comment]
I just reinstalled as my own user (not admin) and I can't reproduce this anymore.
