### ISSUE TITLE
git-bash.exe / mintty closes immediately

### ISSUE THREAD

**Issue by ahogen** [git-for-windows/git#1890]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Issue #1600 seems similar. But I did some poking around and I think my issue might be different.

### Setup

| - | - |
|--|--|
| Git for Windows Version | git-2.19.1-64-bit.exe |
| `$ git --version --build-options`| git version 2.19.1.windows.1<br>cpu: x86_64<br>built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a<br>sizeof-long: 4<br>sizeof-size_t: 8|
| Version of Windows | Windows 7 Professional 64-bit, 6.1.7601 Service pack 1 |
| `$ cmd.exe /c ver` | Microsoft Windows [Version 6.1.7601] |
|  `cat /etc/install-options.txt` | Editor Option: VIM<br>Custom Editor Path:<br>Path Option: Cmd<br>SSH Option: OpenSSH<br>CURL Option: OpenSSL<br>CRLF Option: LFOnly<br>Bash Terminal Option: MinTTY<br>Performance Tweaks FSCache: Enabled<br>Use Credential Manager: Enabled<br>Enable Symlinks: Disabled<br>Enable Builtin Rebase: Disabled<br>Enable Builtin Stash: Disabled |
| Interesting things about your environment | I tried to find and delete all MSYS/MINTTY, git, and bash config files I have. The problem still occurs. Maybe I missed one? |

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
    - `Bash`
 - What commands did you run to trigger this issue?
    - `"C:\Program Files\Git\git-bash.exe"`
 - What did you expect to occur after running these commands?
    - A well-behaved bash window to be opened and running, ready to obey my every command.
 - What actually happened instead?
    - It dies/closes immediately. Both when launched from the Start Menu and when launched from a windows `cmd` window with the command given above (no arguments).

### Detailed Problem Description

This issue started on my home machine and I didn't have the time to fix it and have been putting it off for a while. As such, I don't recall exactly how or when this issue started.

A short summery of what I've tried and am seeing right now:

1. `git-bash.exe` closes immediately
2. `/bin/bash.exe` seems to work normally
3. `/usr/bin/bash.exe` seems to launch normally (see note about [/usr/bin/bash.exe start error](#usr-bin-bash-start-error))
4. Both `/bin/bash.exe -li` and `/usr/bin/bash.exe -li` throw error: `Directory C:\Windows\system32\drivers\etc does not exist; exiting`
5. `/usr/bin/mintty.exe` launches a small window with three buttons. If I click *any* of the shell option buttons, it closes immediately.
6. `/usr/bin/mintty.exe -h never` Does keep the shell window open.
7. `"C:\Program Files\Git\usr\bin\mintty.exe" -e "C:\Program Files\Git\bin\bash.exe"` Does keep the bash window open. Looks very similar to how `git-bash.exe` used to look. There is no git icon in the taskbar, for example, but seems to be nearly identical to what I had before.

#### Item 5: MINTTY Closes Immediately
![Item 5, MINTTY Closes Immediately](https://user-images.githubusercontent.com/6827790/47264119-c6df4680-d4c4-11e8-8f82-9ca5a40e986a.gif)

--------------------------------------------------------------------------
#### usr-bin-bash-start-error

I get a `cut not found` error when I launch `C:\Program Files\Git\usr\bin\bash.exe`. Maybe this is normal?

```bash
C:\Users\Alex> "C:\Program Files\Git\usr\bin\bash.exe"
bash: cut: command not found
```

Going back to issue 4, if I create `/etc` in `C:/Windows/System32/drivers/`, then `bash -li` does actually launch. There are more errors thrown, but I do get a bash prompt. The output is the same for both `/bin/bash` and `/usr/bin/bash`, if that matters.

```bash
C:\Users\Alex> "C:\Program Files\Git\bin\bash.exe" -li
/usr/bin/cp: cannot stat 'C:\Windows\system32\drivers\etc\hosts': No such file or directory
/usr/bin/cp: cannot stat 'C:\Windows\system32\drivers\etc\protocol': No such file or directory
/usr/bin/cp: cannot stat 'C:\Windows\system32\drivers\etc\services': No such file or directory
/usr/bin/cp: cannot stat 'C:\Windows\system32\drivers\etc\networks': No such file or directory
rm: cannot remove '/etc/post-install/01-devices.post': Permission denied
rm: cannot remove '/etc/post-install/03-mtab.post': Permission denied
rm: cannot remove '/etc/post-install/06-windows-files.post': Permission denied
rm: cannot remove '/etc/post-install/99-post-install-cleanup.post': Permission denied

Alex@Swordfish MSYS ~
$
```
This looks like some odd path issue, where it should be `C:\Program Files\Git`, but somehow it got changed to `C:\Windows\System32\drivers`?!!

--------------------------------------------------------------------------
--------------------------------------------------------------------------

### Conclusion

- What should I change/try next?
- Is there some way I can get logs/messages out of `git-bash.exe` when it launches?

Thanks! I use GIT every day, especially on Windows. So I really appreciate all the work that's been done here!

**Comment by dscho** [comment]
This looks like the installation did not quite manage to finish... :-( Any chance that you have Comodo Internet Security installed?

**Comment by ahogen** [comment]
@dscho Thanks for your reply.

No, I don't have Comodo. The only AV is MS Security Essentials. At your suggestion, I disabled MSSE, uninstalled, and reinstalled Git 2.19.1-64bit. Same issue.

**Comment by ahogen** [comment]
Since you mentioned install, I thought maybe I'd try the portable version. Same issue. Everything closes immediately. Return codes are always zero.

Very frustrating...

**Comment by dscho** [comment]
> I thought maybe I'd try the portable version. Same issue

If you run `bash.exe -li` from the portable version, does it work? Does `git-bash.exe` after that Bash call work?

**Comment by ahogen** [comment]
No. I get errors about a directory in `system32/drivers` not existing.

Full output (from Windows CMD prompt)
```
E:\PortableGit>bin\bash.exe -li & git-bash.exe

mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue': Permission denied
Directory C:\Windows\system32\drivers\etc does not exist; exiting
If directory name is garbage you need to update your msys package
```

If I run Windows CMD as administrator, I get the same error.
```
(Administrator) E:\PortableGit>bin\bash.exe -li & git-bash.exe

Directory C:\Windows\system32\drivers\etc does not exist; exiting
If directory name is garbage you need to update your msys package
```

I executed `set` in Windows CMD to view all environment variables and none of them have `drivers` in them, so I don't understand where this is coming from. I didn't think the portable version used/read the registry so it shouldn't be in there either, right?

**Comment by dscho** [comment]
I do not actually think that those symlinks into `system32\drivers\etc` are important for Git for Windows to work. Could you simply delete `01-devices.post` and `06-windows-files.post` from your portable Git's `etc\post-install` and try again?

**Comment by ahogen** [comment]
> Could you simply delete `01-devices.post` and `06-windows-files.post` from your portable Git's etc\post-install and try again?

Those files were shown in the error messages from my installed version of Git (e.g. `C:\Program Files\Git`), not the portable version I've been using to debug this issue the last few days (`E:\PortableGit`). I don't have any `*.post` files in `PortableGit/etc`.

**Comment by dscho** [comment]
@ahogen so this ticket can be closed for now?

**Comment by ahogen** [comment]
Yep, I think so! I left it open to give you a chance to reply in case I missed something.

Thanks again for taking the time to ask questions and prod me in the right direction. I appreciate it.
