### ISSUE TITLE
git stash push with pathspec argument doesn't work as expected

### ISSUE THREAD

**Issue by adrian109** [git-for-windows/git#1892]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
64-bit
```

```
git version 2.19.0.windows.1
cpu: x86_64
built from commit: d96bb8bc6c636a8869140e860e72e7bdf64bd790
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 6.1.7601] 64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (MINGW64)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I have the below local changes I want to stash with a save name:
![image](https://user-images.githubusercontent.com/16767194/47345391-82a99d00-d6a2-11e8-9eb9-5f9031c49377.png)

```
git stash push -m "Save Name" -- *.*
```
 - What did you expect to occur after running these commands?

The files were stashed with an on screen message saying:
"Saved working directory and index state On master: 'Save Name'"

 - What actually happened instead?

A message was shown on screen:
"No local changes to save"

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Local BitBucket server

 - N.B. it works if the **pathspec** argument is omitted in the command, so that following command works as expected:

```
git stash push -m "Save Name"
```

**Comment by dscho** [comment]
Sorry, this fell under the cracks.

> ```sh
> git stash push -m "Save Name" -- *.*
> ```

When you write it this way, the `*.*` is expanded by Bash, not by Git. And Bash only looks in the current directory, matching whatever files you have there with that pattern.

What you probably wanted to do instead is this:

```sh
git stash push -m "Save Name" -- '*.*'
```

to prevent Bash from interpolating the pattern, and instead handing it to Git.
