### ISSUE TITLE
Hook execution error (separated worktree + hook + unicode in path + spaces)

### ISSUE THREAD

**Issue by gelsrc** [git-for-windows/git#1893]
### Setup
 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.345]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

```
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash or cmd.exe has the same issue
```
$ echo $BASH_VERSION
4.4.19(2)-release
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Issue description: when I use separate worktree (via `git config core.worktree ...` or `GIT_WORK_TREE=...`), setup hook `pre-commit`,  use "git dir" with path with unicode and spaces then I get error like: `sh: "Q:/Язык Test/.git/hooks/pre-commit": No such file or directory`

Step by step commands (executed by cmd.exe):

```
Q:\>mkdir "\Язык Test"
Q:\>mkdir "\Separated Worktree"
Q:\>cd "\Язык Test"
Q:\Язык Test>git init
Q:\Язык Test>copy .git\hooks\pre-commit.sample .git\hooks\pre-commit
Q:\Язык Test>git config core.worktree "\Separated Worktree"
Q:\Язык Test>git commit -m "test"
```
last command output:

```
sh: "Q:/Язык Test/.git/hooks/pre-commit": No such file or directory
```

The separate worktree is critical for the issue.

Variants when no issue:

* no separate worktree;
* unicode path but without space(s);
* ascii path with space(s);

---

 - What did you expect to occur after running these commands?

Expected:

```
Q:\Язык Test>git commit -m "test"
On branch master

Initial commit

nothing to commit
```

 - What actually happened instead?

Got error:

```
sh: "Q:/Язык Test/.git/hooks/pre-commit": No such file or directory
```

**Comment by dscho** [comment]
> Q:\Язык Test>git config core.worktree "\Separated Worktree"

This is not really an absolute path. Does it work if you turn this into a real absolute path, by prefixing it with the drive letter (i.e. `Q:\Separated Workree`)?

**Comment by gelsrc** [comment]
> Does it work if you turn this into a real absolute path, by prefixing it with the drive letter (i.e. `Q:\Separated Workree`)

No. Nothing changed. The error is the same.

**Comment by dscho** [comment]
Okay, I just gave this MCVE a try and it seems that in version 2.21.0.rc2.windows.1, it has been resolved.

Could you try with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?
