### ISSUE TITLE
Portable installer: post-install not executed

### ISSUE THREAD

**Issue by ittegrat** [git-for-windows/git#1896]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
PortableGit-2.19.1-64-bit.7z.exe
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.192]
Windows 10 1709 (OS Build 16299.192) 64bit

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Install in: C:\Programs\PortableGit
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details
The `post-install.bat` script is not run at the end of the extraction process.

If open a `cmd` and run the command `git-bash.exe --no-needs-console --hide --no-cd --command=post-install.bat` the script **is not** run.

I have to remove the `--no-needs-console` option to successfully run the script.

The same also happens on a Windows 7 machine and with previous releases of the installer.

**Comment by rimrul** [comment]
It doesn't run that script for me either. The last release that runs it is [2.14.2(3)](https://github.com/git-for-windows/git/releases/tag/v2.14.2.windows.3) It's broken from pre-release [2.15.0-rc2.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.15.0-rc2.windows.1). It seems the breaking change was introduced between 2017-10-12 and 2017-10-20. I can't quite pinpoint the issue yet, but I feel like it's related to 021d9299eb.

**Comment by ittegrat** [comment]
@rimrul I think the issue you are describing is a different one: it seems that the output of the **ver** command is not parsed correcly and the variable is set to empty.

In my case, `post-install.bat` and all the `/etc/post-install/*.post` scripts run correctly. The problem is that the argument `--no-needs-console` prevents the `git-bash.exe` to fire the script.

I tested various release back to 2.10 and I found always the same behavior.

Anyone can point me to the source code of git-bash ?

**Comment by ittegrat** [comment]
Actually it is the combination of `--no-needs-console` and `--hide` that cause the problem. Substituting `--needs-console` or `--no-hide` let the script run.

As far as I can understand, the combination of the two parameters has an impact on this this line: https://github.com/git-for-windows/MINGW-packages/blob/5c596e6d428f1320def33d0327965319bda02cde/mingw-w64-git/git-wrapper.c#L638

**Comment by hwdsl2** [comment]
Pinging @dscho because this issue breaks portable versions. Please look into it. Thanks!

**Comment by PhilipOakley** [comment]
> Pinging @ dscho because this issue breaks portable versions. Please look into it. Thanks!

I think he would much prefer a PR... Anyone? ...

**Comment by dscho** [comment]
@ittegrat I would indeed prefer a PR with a well-written commit message (you know almost all the details already, and it would be good to document them there).

The `--no-needs-console` option tries to tell the Git wrapper that no console is actually needed, and it should not even bother to allocate one. The `--hide` option, however, wants to hide the console.

I think that the problem actually comes from this line: https://github.com/git-for-windows/MINGW-packages/blob/5c596e6d428f1320def33d0327965319bda02cde/mingw-w64-git/git-wrapper.c#L664 (I guess that some thing in the post-install scripts now needs the inherited file handles or something).

Fun sidenote: https://github.com/git-for-windows/MINGW-packages/blob/5c596e6d428f1320def33d0327965319bda02cde/mingw-w64-git/git-wrapper.c#L637 has a typo in it: the `|` should be a `||`.

Anyway, with this explanation, and this suspicion that something in the post-install scripts needs the inherited handles, I think that this is the best course of action: to drop the `--no-needs-console` for now.

@ittegrat could you open that PR? We're really close to a v2.20.0, and I would like to have that patch before that version is released.

**Comment by dscho** [comment]
> It's broken from pre-release [2.15.0-rc2.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.15.0-rc2.windows.1) onwards. It seems the breaking change was introduced between 2017-10-12 and 2017-10-20. I can't quite pinpoint the issue yet, but I feel like it's related to [021d9299eb](https://github.com/git-for-windows/build-extra/commit/021d9299eb6047242884fbed06ba424f7f89f5b5).

@rimrul You know, when I look at that code comment, I cannot help but realize that this tests whether we are on a Windows <= 10, which is, like, every single Windows out there.

In other words: I think that that `@IF 10 LEQ %ver%` is now totally obsolete and unnecessary. Could you verify that things work without that condition (i.e. *always* execute that `rebase.exe`), and if so, open another PR to make it so?

**Comment by dscho** [comment]
> I cannot help but realize that this tests whether we are on a Windows <= 10

Ah, I fooled myself. It's testing 10 <= Windows version. But still, I think that this `rebase.exe` does not hurt on Windows versions earlier than that. (I might be wrong, and we'll find out, I am sure... ;-)).
