### ISSUE TITLE
2.19.1-x64: ReleaseNotes.html error

### ISSUE THREAD

**Issue by palver123** [git-for-windows/git#1898]
The ReleaseNotes.html installed by the installer '2.19.1-x64' mentions Git Credential Manager twice with different versions. So which version is included in the installer?

![image](https://user-images.githubusercontent.com/12460850/47568424-61121500-d931-11e8-9db7-47cbe99790aa.png)

I am not sure how these release notes are generated. I took a short peek at the source code but could not find it, otherwise I'd have made a PR instead of an issue report.

**Comment by michaelblyons** [comment]
I'm only guessing here, but I think it's from the annotations at [the 2.19.1 release][1], which also have GCM listed twice.

[1]: https://github.com/git-for-windows/git/releases/tag/v2.19.1.windows.1

**Comment by dscho** [comment]
The release notes are generated as part of the `/usr/src/build-extra/please.sh upgrade <package>`. So when Git Credential Manager is upgraded twice (or more times) between Git for Windows releases, those duplicates happen. See https://github.com/git-for-windows/build-extra/blob/4397c9c9c85a2d366eef9009a4e51820da341417/please.sh#L2733 for details.

FWIW this particular duplicate entry has been fixed already: https://github.com/git-for-windows/build-extra/commit/9beac3cf98450cf07f709c745d17c78654d063e5#diff-5e601b5070ec55264211202a7cf0dacd.

Of course, we could improve the tooling to avoid the duplicates, but I do not have time to do so, for the foreseeable future.

**Comment by dscho** [comment]
> Of course, we could improve the tooling to avoid the duplicates, but I do not have time to do so, for the foreseeable future.

I will leave this ticket open for a while, in case one of you gentle people is interested in tackling this, otherwise I will close it.

**Comment by palver123** [comment]
I took a look at it and even though I planned to make the above mentioned improvement, I think I give up. I am not familiar with bash scripts enough (Windows guy here) to come up with a solution.

### For other people trying to tackle it
Here's what I understood from the bash scripts:

[please.sh](https://github.com/git-for-windows/build-extra/blob/master/please.sh) has a subcommand _upgrade_ that composes a release note message in the variable _relnotes_feature_ and passes it to another subcommand: _mention_. The latter writes it in [ReleaseNotes.md](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md) and makes a git commit, just like d641b69df0dd66b2ecba19e187a474b2302cc8ff.

A possible solution I can think of is to somehow tell the subcommand  _mention_ to delete entries matching a specific regex before appending the <release-notes-item>. Like this:

`mention feature    "Comes with [Git Credential Manager v1.18.2](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.18.2)."     "Comes with \[Git Credential Manager v[\d\.]+\]\(.+\)\." `

This would tell _mention_ to delete every match for Comes with \[Git Credential Manager v[\d\.]+\]\(.+\)\. before append Comes with [Git Credential Manager v1.18.2](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.18.2). to ReleaseNotes.md

**Comment by dscho** [comment]
@palver123 thanks for this analysis! I agree with most of it, yet I think we can make it even better.

Rather than making this specific to Git Credential Manager, and rather than doing it in the `upgrade` function, I think we should introduce a function that identifies (semi-) duplicate entries and removes obsolete ones, and it should be done in the `mention` function (which is ultimately called by `upgrade`).

What I have in mind is to use a `sed` script to remove the `<url>` part from the `[<text>](<link>)` constructs, then anything that looks like a version number, prefix the lines with their line number, then use the `uniq -d` command to identify *now*-identical lines, and use the line numbers to remove those entries (in reverse order, so as to avoid having to adjust line numbers after removing lines).

**Comment by dscho** [comment]
Fixed via https://github.com/git-for-windows/build-extra/pull/213

**Comment by dscho** [comment]
BTW all thanks should go to @tanushree27 who did an outstanding job at not only reading (and understanding!) the `sed` script that adds new entries to the "New Features" section but also adjusting it to remove previous entries that are superseded by the newly added entry.

This was a high-quality contribution that makes this maintainer's heart all warm and fuzzy. ❤️
