### ISSUE TITLE
git not working after setting http.sslBackend = schannel

### ISSUE THREAD

**Issue by tianpomin** [git-for-windows/git#1899]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.345]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

we have own  .crt file and private  repo.packagist

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
composer global require "xxx/installer" -vvv
```
 - What did you expect to occur after running these commands?

working

 - What actually happened instead?

 [Composer\Downloader\TransportException]
  The "https://xxx/repository/composer-public/packages.json" file could not be downloaded: SSL operatio
  n failed with code 1. OpenSSL Error messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

something maybe help:
1.  i choose  native Windows Secure Channel Library as Https transport backend
2.  the company CA file, xxx.crt can work normally in chrome,  it seems like git windows  can not get the windows certificate store

**Comment by dscho** [comment]
When you write `composer`, I get the impression that you are talking about PHP, not about Git for Windows. Where does Git come into play here?

**Comment by dscho** [comment]
Closing for lack of an answer.
