### ISSUE TITLE
Update mgwport package

### ISSUE THREAD

**Issue by t-b** [git-for-windows/git#19]
- ~~More robust downloading https://github.com/git-for-windows/mgwport/pull/3~~
- ~~Deterministic build patches https://github.com/git-for-windows/mgwport/pull/2~~
- Add port file https://github.com/t-b/mgwport/commit/f3d97fcc99ca612c33e1ed0290e26afdbe00730a
- Create package

**Comment by dscho** [comment]
@t-b do we still need that, now that we switch to MSys2 right away?

**Comment by t-b** [comment]
@dscho Nope!
