### ISSUE TITLE
PortableGit64 does not unset `pack.packSizeLimit` like the installer does

### ISSUE THREAD

**Issue by alejandro5042** [git-for-windows/git#1903]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

I am using Portable Git 64-bit.

```
$ git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

I am running 64-bit Windows 10 Insiders.

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18252.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

There are no options as part of a portable install.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Yes, 64-bit portable Git is incorrectly packaged. More details below.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git gc --keep-largest-pack --aggressive --prune=all

# then...
$ git count-objects -vH

# or
$ ls .\.git\objects\pack\*.pack
```

Note: There were no packfiles with a `.keep` extension.

 - What did you expect to occur after running these commands?

One packfile remains in the repo.

 - What actually happened instead?

Three packfiles remained, two which were just about 2 GiB, and one that was 443 MiB.

The problem probably is that PortableGit does not run the install scripts that unset `pack.packSizeLimit`.

This limit is set here:

https://github.com/git-for-windows/build-extra/blob/master/git-extra/gitconfig

The 64-bit installer unsets this configuration:

- PR: https://github.com/git-for-windows/build-extra/pull/84
- Commit: https://github.com/git-for-windows/build-extra/commit/6b39ba714d13ec25aa800076f51edcac795517a2

But this only runs in the InnoSetup install script.

The portable version does not get this run on it before it is packaged. Therefore:

```
$ git config --show-origin pack.packSizeLimit
file:C:/FULL_PATH_REDACTED/mingw64/etc/gitconfig     2g
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A. This is a private repo. But this should reproduce with any sufficiently large repo.

**Comment by dscho** [comment]
Good point.

This would need to be added to https://github.com/git-for-windows/build-extra/blob/master/portable/release.sh, and happily we already have code that modifies the config for the purpose of the portable Git: https://github.com/git-for-windows/build-extra/blob/4397c9c9c85a2d366eef9009a4e51820da341417/portable/release.sh#L90-L95

Unfortunately, I do not have time to take care of this, but maybe you can find some time to implement this, @alejandro5042?

It should be as easy as something like

```sh
test 64 != $BITNESS ||
git config -f "$SCRIPT_PATH/root/mingw$BITNESS/etc/gitconfig" --unset pack.packSizeLimit
```

and then testing it.

**Comment by alejandro5042** [comment]
Awesome, thank you @tanushree27 and @dscho!
