### ISSUE TITLE
Running 'git gui' breaks PowerShell character echoing for one line on Windows 10 1809

### ISSUE THREAD

**Issue by simonbates** [git-for-windows/git#1906]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
> git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Home 1809 64-bit

```
> cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.55]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I did not observe this issue before upgrading to 1809.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git gui
```
 - What did you expect to occur after running these commands?

Gui to open and PowerShell prompt to operate as before `git gui` was run.

 - What actually happened instead?

Gui opens as expected, however, for one line of input, the PowerShell character echoing outputs unexpected characters. The entered command is read correctly. It's only the echoing that is not working correctly. And the issue goes away after a single line of input.

I'm using PowerShell with the standard Windows console. I also tried cmd.exe with the Windows console and the issue does not happen there. It appears to be PowerShell-specific.

I did not observe the issue before installing the 1809 upgrade.

I've attached a screenshot of the following command inputs:

```
> git gui
> echo hello
> echo hello
```

![git_gui_powershell_1809](https://user-images.githubusercontent.com/470482/47858585-cbf49d80-ddc2-11e8-8e32-07d76729eb58.PNG)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It appears to not be repository-specific.

**Comment by simonbates** [comment]
My guess would be that it's affecting the escape sequences used for colouring the command.

**Comment by simonbates** [comment]
And I've not seen this happen with any other `git` command (including `gitk`) -- so far it's limited to `git gui`.

**Comment by shiftkey** [comment]
@simonbates could you also attach the output of `$psversiontable` so we can trace what version of PowerShell you are seeing this in?

```
PS C:\Users\shiftkey> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by simonbates** [comment]
The issue does not happen when `PSReadline` is removed from the PowerShell session:

```
> Remove-Module -Name PSReadline
> git gui
> echo hello
hello
> echo hello
hello
```

**Comment by dscho** [comment]
I can add another tidbit of information: after setting `$env:GIT_TRACE = "1"`, `git gui` will fail with an error popup, and that funny escape stuff does *not* occur on the console.

This gives me hope that we can maybe figure this one out and fix it without having to patch Tcl/Tk.

You see, `Git GUI` is implemented internally as a [Tcl/Tk](https://www.tcl.tk/) script. The code is not compiled, it is still in "source code", ready to interpret, living in `C:\Program Files\Git\mingw64\libexec\git-core`, as `git-gui.tcl` and inside the `git-gui` folder.

Now, Tcl is not particularly hard to read or write. Maybe you can instrument it a little (i.e. edit the files, as administrator in your installation or if you prefer as regular user with a Portable Git, to print debug messages and to exit early) and see where things go wrong?

**Comment by dscho** [comment]
> and inside the `git-gui` folder.

Sorry, that should have been "and inside the `C:\Program Files\Git\mingw64\share\git-gui\lib` folder".

**Comment by dscho** [comment]
> Maybe you can instrument it a little

@simonbates ping?
