### ISSUE TITLE
Ctrl-C closes the console

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#192]
In trying to use git through ConsoleZ I invoke it with the following command: `PathToGit\Git\git-cmd.exe --command=PathToGit\Git\usr\bin\bash.exe --login -i`

Hitting CTRL-C closes the console, not the current executing program.  This is a regression from the git-1.9.5-preview release.

**Comment by dscho** [comment]
Is this not a ConsoleZ issue?

**Comment by kjeremy** [comment]
It may be that whatever changed triggers this issue in ConsoleZ.  I'm not really sure except that this setup did work in the past.

**Comment by dscho** [comment]
The change you are referring to is most likely that we provide `git-cmd.exe`, and previously you used `cmd.exe`. It could be that a special flag needs to be used when [creating that new process](https://github.com/git-for-windows/git/blob/v2.4.2.windows.1/compat/win32/git-wrapper.c#L533-L543) in `git-cmd.exe`, maybe `CREATE_NEW_PROCESS_GROUP` (see https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863%28v=vs.85%29.aspx for all available flags).

@kjeremy it would be good if you could try to patch Git accordingly (see https://github.com/git-for-windows/git/wiki/Package-management#build-packages-from-locally-patched-sources for details).

**Comment by linquize** [comment]
Relate to #181?

**Comment by albertosantini** [comment]
Well, something is different.

I have been catching SIGINT event in Node.js context.
Starting the app in ConEmu or in git-cmd context, the event is trapped correctly.

It is ignored if I execute the app in git-bash context,

Sadly, I cannot reproduce it with a test case.

**Comment by kjeremy** [comment]
Looks like PR #205 will fix this.

**Comment by cbucher** [comment]
Presently, when you press CTRL-C, git-cmd is terminated.
Why? because no event handler is registered, in this case the default behavior is to terminate the current process.
You can verify by yourself, press CTRL-C, git-cmd disappear from the task manager.

ConsoleZ launches git-cmd, inject a dll in git-cmd to read the console buffer and interact with this process and monitors the termination of git-cmd.
When git-cmd is terminated, ConsoleZ closes the tab.

**Comment by calle2010** [comment]
@cbucher Which version of Git for Windows do you use? I can't reproduce the behavior. Ctrl-C in git-cmd.exe just brings up a new prompt.

**Comment by cbucher** [comment]
v2.4.3.windows.1

**Comment by bviktor** [comment]
@calle2010 I believe he means `git-cmd.exe --command=usr\bin\bash.exe --login -i` not just `git-cmd.exe`.

**Comment by dscho** [comment]
Let's continue the discussion in https://github.com/git-for-windows/git/pull/205.
