### ISSUE TITLE
Can't Access Devops behind Proxy with Visual Studio Plugin OR 2.19.1 Git

### ISSUE THREAD

**Issue by Crashdummyy** [git-for-windows/git#1920]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

--   2.14.4.2 ( 32-bit embedded in Visual Studio 2017 Professional ) => Broken
--   2.17.1.2 ( 64 and 32 ) => both work fine
--   2.19.1 (latest, both architectures) => Broken again

```
$ git --version --build-options

VisualStudio
$ ./git.exe --version --build-options
git version 2.14.4.windows.2
built from commit: c5ad43e5eda4db8c734cdc6e3cf6c53353f69557
sizeof-long: 4
machine: x86

Working
$ git --version --build-options
git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Windows 10 Enterprise, 64-Bit, Build 10.0.17134 .286

$ cmd.exe /c ver
10.0.17134 .286
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Working 2.17.1.2
```
Editor Option: Nano
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

( Can't find them for Visual studio )

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Everything work(ed) fine locally and even Github.
The Connection just fails when I try to access AzureDevops behind our Proxy.
The Connection to git through a Proxy appears to work fine tho

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash with 2.17.1.2 => Works fine
Team Explorer (embedded 2.14.1 in Visual Studio) => Broken

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Literally everything...
```
 - What did you expect to occur after running these commands?

Basic Git Functionality like fetching

 - What actually happened instead?
```
Git failed with a fatal error.
Authentication failed for <giturl>
( Visual Studio Extension "Team Explorer" )

Error: cannot spawn /c/program files (x86)/microsoft visual studio/2017/professional/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
Error encountered while cloning the remote repository: Git failed with a fatal error.
could not read Password for '<proxyUrl>': terminal prompts disabled
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
```
Can't do that, Companies AzureDevops
```
** Additional Infos **

I was able to reproduce it to the CredentialManager.

- ```If I delete the tenant.cache in the AppData I can do **one** operation till it fails again with the embedded Git in Visual Studio```

- on the latest Build ( commit 11a3092e18f2201acd53e45aaa006f1601b6c02a ) 2.19.1, I need to re-enter my Proxy Credentials every time I do an operation

- With 2.17.1.2 everything works fine..

- I replaced git-core directory in **/libexec/git-core with the one from my 2.17.1.2 Installation and can then use the Team Explorer Extension again ( the embedded git from Visual Studio ).
Although I just put back the Backup to reproduce the error, I can't find my Repo in Devops anymore but now fetch, clone etc. seems to work...

- Checked it on a Colleagues PC and there I get the : "Git failed with fatal error, authentication failed for <our GitRepo's URL>

**Comment by Crashdummyy** [comment]
hey there,

forgot to mention.

I installed GCMW 1.18.3 ( was the latest that time ). With that I could at least fetch and push.
Afterwards I changed the Credentialhelper to "wincred" to get both of them working.

The Problem still persists with the bundled GCMW from 2.14.* and 2.19.*.

I am sorry I forgot to mention, yet I assumed this is a Visual Studio Problem so I just added that piece of information to the [Microsoft Ticket](https://developercommunity.visualstudio.com/content/problem/378174/cant-connect-to-devops-behind-a-proxy.html):

As far as I am concerned you can close this Issue

**Comment by dscho** [comment]
> The Problem still persists with the bundled GCMW from 2.14.* and 2.19.*.

Yes, that is unfortunately true. My hope was that Git for Windows v2.19.2 would fix that, but that release had two major regressions, so I had to demote it to "pre-release" status.

> As far as I am concerned you can close this Issue

Okay!
