### ISSUE TITLE
This is a bug; please report it at

### ISSUE THREAD

**Issue by william-denault** [git-for-windows/git#1928]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 
```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10
```
$ cmd.exe /c ver

** insert your machine's response here **
```
handle #1: 00000000000001a0 (type 3, handle info (1) 1
handle #2: 0000000000000454 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

	SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn sh: Function not implemented
error: cannot spawn rpostback-askpass: Function not implemented
error: cannot spawn bash: Function not implemented
fatal: could not read Username for 'https://github.com': Function not implemented
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by shiftkey** [comment]
@william-denault It's not clear to me the version you are currently running, but we believe this issue has been resolved in v2.17.0 (we're now on v2.18.1).

Can you please update and try again?

**Comment by PhilipOakley** [comment]
This is likely to be the same as #1809 'warning: failed to restrict file handles' 

Please upgrade to the latest release (which also fixes a security issue) 

see https://github.com/git-for-windows/git/releases/ , and then the Git Credential Manager 1.18.2
Microsoft/Git-Credential-Manager-for-Windows#779

at the moment I've lost my link to the latest 'daily' build.

**Comment by dscho** [comment]
> at the moment I've lost my link to the latest 'daily' build.

https://wingit.blob.core.windows.net/files/index.html
