### ISSUE TITLE
Alt-F2 no longer opens a new window

### ISSUE THREAD

**Issue by akerfoot** [git-for-windows/git#1931]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.17134.407]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Rebase: Enabled
Enable Builtin Stash: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash

 - What actually happened instead?

Previously, I used to be able to hit Alt-F2 to open a new window. As of one or two updates ago, this no longer works. Alt-F4 to close the window also no longer works. Both shortcuts still show up in the context menu.

**Comment by dscho** [comment]
That is most likely an issue with MinTTY: https://github.com/mintty/mintty/issues. Please report it there.

**Comment by dscho** [comment]
(For the record, Alt+F2 works here, still, with v2.19.2.)

**Comment by akerfoot** [comment]
Just to be clear, do you mean it works on MinTTY on your machine? Or are you using cmd.exe?
(I've upgraded to v2.19.2 and still see the issue.)

**Comment by dscho** [comment]
@akerfoot it works in my Git for Windows v2.19.2 (64-bit) installation.
