### ISSUE TITLE
add release notes to published RC releases 

### ISSUE THREAD

**Issue by shiftkey** [git-for-windows/git#1943]
I'd love to consume pre-release packages in [dugite-native](https://github.com/desktop/dugite-native) but releases like [`v2.20.0-rc0.windows.1`](https://github.com/git-for-windows/git/releases/tag/v2.20.0-rc0.windows.1) do not contain the checksum details for the assets in the release (which I use to verify the integrity of bits when packaging).

I'm less interested in the release notes themselves for RC packages (maybe they're still being worked on at that point, but I see your Git mailing list announcement has them too?).

**Comment by dscho** [comment]
Seems to have worked: https://github.com/git-for-windows/git/releases/tag/v2.20.0-rc1.windows.1
