### ISSUE TITLE
Cannot init a git repository because I do not have access to one folder in the specified path: fatal: unable to get current working directory: No such file or directory

### ISSUE THREAD

**Issue by rvignolo** [git-for-windows/git#1944]
I was not able to init a git repository in the following path `/c/I/cannot/access/to/this/path/but/I/can/access/to/this/one` because I do not have permissions for the path `/c/cannot/access/to/this/path/`. I believe git fails when trying to set up the working directory with `pwd` or something like that. If I run `pwd` I do not get any error.

Thanks!

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git version 2.16.2.windows.1
64-bit

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
Bash
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init
```
 - What did you expect to occur after running these commands?

I expected to init a git repository.

 - What actually happened instead?

```
fatal: unable to get current working directory: No such file or directory
```

**Comment by alegrigoriev** [comment]
This appears fixed in 4745feeb

**Comment by dscho** [comment]
> git version 2.16.2.windows.1

This version was released over 10 months ago, and the current Git for Windows version is v2.20.1. Care to give that version a go?

**Comment by dscho** [comment]
No? Well, then this ticket can be closed.

**Comment by rvignolo** [comment]
I am sorry for the delay. I was not able to update to the new version of git for windows at work... Thanks for your replies!
