### ISSUE TITLE
An idea to prevent CMD from picking up any git.exe in the current directory

### ISSUE THREAD

**Issue by gdh1995** [git-for-windows/git#1945]
The release note in https://github.com/git-for-windows/git/releases/tag/v2.19.2.windows.1 says:

> It is impossible to turn off CMD's behavior where it picks up any git.exe in the current directory, so let's discourage the use of Git CMD. 

I agree with it, but I think there may be a way to make CMD not use the `git.exe` in the current directory - according to `$PATHEXT`, `git.com` takes precedence over `git.exe`, so if only there's `/usr/bin/git.com`, then a command like `git status` will use it directly.

Just a naive idea~

**Comment by dscho** [comment]
Have you tested your idea?

**Comment by gdh1995** [comment]
> Have you tested your idea?

Sorry to bother you. My idea of using git.com can not pass any simple test.

Maybe `DOSKEY` is another solution. Here's my test (after `cp /usr/bin/ls.exe /r/working/git.exe`):

``` cmd
R:\working$ DOSKEY git=D:\Git\mingw64\bin\git.exe $*

R:\working$ git --version
git version 2.19.2.windows.1

R:\working$ .\git --version
ls (GNU coreutils) 8.30
...
```

This new idea is learned from https://stackoverflow.com/questions/20530996/aliases-in-windows-command-prompt.

**Comment by dscho** [comment]
Fixed via https://github.com/git-for-windows/MINGW-packages/commit/82172388bb51cf8b3882c39eb0130eed45fd302c

**Comment by gdh1995** [comment]
Thanks.

BTW, I just wonder whether the commit can still work even when `@@EXEPATH@@` contains any space characters.

**Comment by gdh1995** [comment]
Um... A sadly news is, I just test a new command of `echo 1 | git log`, and find that `CMD` fallback to search `PATH` for `git.exe`. `CMD` is indeed too annoying.

**Comment by dscho** [comment]
> I just wonder whether the commit can still work even when `@@EXEPATH@@` contains any space characters.

It should, as the path is inside quotes.

> A sadly news is, I just test a new command of `echo 1 | git log`, and find that `CMD` fallback to search `PATH` for `git.exe`.

That is indeed sad! Oh well. At least it works for the common case, as it is quite unusual to pipe something into `git`, especially in CMD.

So I guess we keep Git CMD deprecated, but ship with your fix from now on?

**Comment by mfriedrich74** [comment]
You could have a look here if, you get the SafeDllSearchMode somehow
enabled for the process and child processes.
https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order

**Comment by dscho** [comment]
@mfriedrich74 if you somehow get the SafeDllSearchMode to apply to CMD's .exe search, that will be quite the trick.
