### ISSUE TITLE
Installer 2.19.2 does not offer experimental options

### ISSUE THREAD

**Issue by mloskot** [git-for-windows/git#1947]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.2.windows.1
cpu: x86_64
built from commit: 26dcaa1b6b5fd862db3ec40983e33ff3432f1166
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.376]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

The 2.19.2 installer does not allow to select the experimental options. The last page is this, with `Install` button:

![image](https://user-images.githubusercontent.com/80741/48894521-3b4e3200-ee43-11e8-8923-3d325f3b2a69.png)

Installer 2.19.1 last page was this:

![install-git-9](https://user-images.githubusercontent.com/80741/48894598-6769b300-ee43-11e8-84a3-ff29f600394e.png)

The release notes do not mention anything related to the experimental options, so I think this may be a bug.

**Comment by shiftkey** [comment]
> v2.19.2 no longer marks those built-in commands as experimental.

https://github.com/git-for-windows/build-extra/pull/203#issuecomment-441066920

**Comment by mloskot** [comment]
Aha! Thanks @shiftkey
