### ISSUE TITLE
Where does installer store default core.autocrlf value?

### ISSUE THREAD

**Issue by mloskot** [git-for-windows/git#1948]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.2.windows.1
cpu: x86_64
built from commit: 26dcaa1b6b5fd862db3ec40983e33ff3432f1166
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.376]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

```
$ cd $HOME                                          # non-repo directory
$ git config --system core.autocrlf
$ git config --global core.autocrlf
$ git config core.autocrlf
true
```

Where does the non-system and non-global `core.autocrlf` come from?

**Comment by PhilipOakley** [comment]
try the 

```
git config --list --show-origin
```

command to see where the all are, or just the `--show-origin` for single items (IIRC).

**Comment by mloskot** [comment]
Blimey. I had no idea about `c:\ProgramData\Git\config`. Excellent. Thank you!
