### ISSUE TITLE
git for windows switch branch error

### ISSUE THREAD

**Issue by handelxh** [git-for-windows/git#195]
IN Git bash ,After modified the WorkSpace's file before commmit , can not switch the branch.
But can use sidebar when Right click the mouse to switch the branch . After this action, the branch control maybe crash.
For example , use mouse to switch branch A to branch B ,before commit the branch A diff . The current branch is B , execute CMD : git reset -- hard HEAD , may clean the branch A haven't commit modified~!

**Comment by dscho** [comment]
Please provide a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve).

**Comment by dscho** [comment]
@handelxh it would be a good idea to help me reproduce your issue if you want me to help you.

**Comment by handelxh** [comment]
which's idea?

**Comment by handelxh** [comment]
What idea do you mean ?

**Comment by dscho** [comment]
> What idea do you mean ?

I said it: to help me reproduce your issue. Because otherwise you would make it unnecessarily hard for me to help you, and as a consequence I would take care of other people's problems instead.
