### ISSUE TITLE
“Not a valid executable” error in installer

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [git-for-windows/git#1951]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
> cmd.exe /c ver

Microsoft Windows [Version 10.0.18272.1000]
```

### Details

When configuring installation, there is option to select the other git editor.

 - What did you expect?

When I type out the `code-exploration -w` in the field, I expect it to run the Visual Studio Code exploration once I click “Test Custom Editor” and then allow me to proceed to installation.

 - What actually happened instead?

When I press the button it says “Not a valid executable: "cod".” No matter how you try to type the path or command, it will throw an error, I tried literally everything possible, including `/d/Main/…`, `D:\Main\…`, `"D:\Main\…"` and selecting the binary via the “Browse…” button after field.

![image](https://user-images.githubusercontent.com/10401817/48998863-6b6d3c00-f187-11e8-9fa2-fe0ef6c5463f.png)

**Comment by linquize** [comment]
https://github.com/git-for-windows/build-extra/blob/4dd83144dc06971722cbf83406b2f2f8ae9f9916/installer/install.iss#L1147 `PathIsValidExecutable()` uses `FileExists()` that does not check `%PATH%`.
At this moment, you need to enter full path, e.g. `C:\path-to-exe\code-exploration.exe -w`

**Comment by DaFri-Nochiterov** [comment]
Oh, that is actually worked, thank you, @linquize! ❤️ 

I tried to provide full path to `code-insiders.bat` because thought, the Visual Studio Code requires arguments passed to that batch file. But `D:\…\Code - Exploration.exe` worked too. And I see the `.exe` check now, that's why it failed… that error is pretty bad (like `"cod"` instead of `"code-insiders"`…)!

I will probably leave this issue open as the improvement suggestion: there probably no need in using `FileExists`, instead there could be just attempt to run the command with all environment variables present and if that fails, the error must be shown, or just improve the text above the field or error message, yeah 👍

**Comment by dscho** [comment]
@DaFri-Nochiterov unfortunately, times are pretty frantic over here, so I need to ask you to do more than just leave this issue open. Could you extend the code indicated by @linquize to test also for `.cmd` and `.bat` in addition to `.exe`, then open a PR (after verifying that it works)?

**Comment by aakriti-jain** [comment]
@dscho If the issues is not taken up yet, can I work on it?

**Comment by PhilipOakley** [comment]
@aakiiti-jain if @DaFri-Nochiterov isn't able to offer a PR, then Go For It (TM). 

Contributions are welcome, as per  https://github.com/git-for-windows/git/issues/1951#issuecomment-441697324

**Comment by DaFri-Nochiterov** [comment]
Yeah. I'm not familiar with language and tools, so it'll take me much time to learn to know all the stuff so to make any PR. This is also almost Christmas and there are many things to do atm. So yeah, if you want to make a PR — do it, please! <3

**Comment by dscho** [comment]
@aakriti-jain go for it! ;-)

**Comment by dscho** [comment]
This should be addressed by https://github.com/git-for-windows/build-extra/pull/221
