### ISSUE TITLE
32-bit ver 2.19.2.1 git-bash.exe crashes by Segmentation fault on start

### ISSUE THREAD

**Issue by 2i3r** [git-for-windows/git#1962]
- \[x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
# I've installed 32-bit version from "Git-2.19.2-32-bit.exe" file.

$ git --version --build-options


git version 2.19.2.windows.1
cpu: x86_64
built from commit: 26dcaa1b6b5fd862db3ec40983e33ff3432f1166
sizeof-long: 4
sizeof-size_t: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7600]  # 32-bit
#and
Microsoft windows [Version 10.0.17134.407] # 64-bit

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled

```

`# Same happens also on portable version downloaded from [Official Download link](https://github.com/git-for-windows/git/releases/download/v2.19.2.windows.1/Git-2.19.2-32-bit.exe)`

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

My win 7 is 32-bit 
(Also tested on Win10 x86_64 ver: 10.0.17134.407 it also returned Segmentation Fault)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (git-bash.exe)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

In cygwin:
```
./git-bash.exe
```
In windows explorer, when I double click `git-bash.exe`
In windows explorer when I choose `Git Bash Here` from context menu.

 - What did you expect to occur after running these commands?

I expect `bash (MINGW)` to get started, so I can run commands.

 - What actually happened instead?

Segmentation Fault:
```
  Problem Event Name:	APPCRASH
  Application Name:	git-bash.exe
  Application Version:	2.19.2.1
  Application Timestamp:	5bf5b382
 Fault Module Name:	StackHash_0a9e
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	00000001
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

```
When debugging using MS Visual Studio:
```
Unhandled exception at 0x00000001 in git-bash.exe: 0xC0000005: Access violation reading location 0x00000001.
```

When monitoring execution by `process monitor` it crashes after the last line executed:
```
.
.
.
5:15:31.2125235 PM	git-bash.exe	5472	RegOpenKey	HKLM\Software\Microsoft\Windows\Windows Error Reporting\WMR	SUCCESS	Desired Access: Query Value
5:15:31.2125429 PM	git-bash.exe	5472	RegQueryValue	HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\WMR\Disable	SUCCESS	Type: REG_DWORD, Length: 4, Data: 1
5:15:31.2125506 PM	git-bash.exe	5472	RegCloseKey	HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\WMR	SUCCESS	
5:15:31.2131460 PM	git-bash.exe	5472	CreateFile	E:\Program Files\Git\usr\bin\mintty.exe	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
5:15:31.2135907 PM	git-bash.exe	5472	QueryBasicInformationFile	E:\Program Files\Git\usr\bin\mintty.exe	SUCCESS	CreationTime: 12/1/2018 6:51:55 PM, LastAccessTime: 12/1/2018 6:51:55 PM, LastWriteTime: 11/6/2018 2:24:10 PM, ChangeTime: 12/1/2018 6:51:55 PM, FileAttributes: A
5:15:31.2135979 PM	git-bash.exe	5472	CloseFile	E:\Program Files\Git\usr\bin\mintty.exe	SUCCESS	
5:15:31.2140001 PM	git-bash.exe	5472	CreateFile	E:\Program Files\Git\mingw32\bin	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
5:15:31.2140226 PM	git-bash.exe	5472	QueryBasicInformationFile	E:\Program Files\Git\mingw32\bin	SUCCESS	CreationTime: 12/1/2018 6:51:32 PM, LastAccessTime: 12/1/2018 6:52:37 PM, LastWriteTime: 12/1/2018 6:52:37 PM, ChangeTime: 12/1/2018 6:52:37 PM, FileAttributes: D
5:15:31.2140288 PM	git-bash.exe	5472	CloseFile	E:\Program Files\Git\mingw32\bin	SUCCESS	
5:15:31.2142824 PM	git-bash.exe	5472	CreateFile	E:\Users\[UserName]	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
5:15:31.2143024 PM	git-bash.exe	5472	QueryBasicInformationFile	E:\Users\[UserName]	SUCCESS	CreationTime: 1/16/2012 7:03:05 PM, LastAccessTime: 12/2/2018 4:25:53 PM, LastWriteTime: 12/2/2018 4:25:53 PM, ChangeTime: 12/2/2018 4:25:53 PM, FileAttributes: D
5:15:31.2143090 PM	git-bash.exe	5472	CloseFile	E:\Users\[UserName]	SUCCESS	
5:15:31.2143828 PM	git-bash.exe	5472	QueryNameInformationFile	E:\Program Files\Git\git-bash.exe	SUCCESS	Name: \Program Files\Git\git-bash.exe

```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No problem with `git` itself.

- Further Info:

Problem started to rise when `git` updated itself to 2.19.2 version (or may be an earlier version, as I installed git multiple time to may resolve the issue, but I'm sure the version is no more than 3 weeks old.). 
I tested the portable version on a new installation of windows 7 32-bit and on a Windows 10 64-bit, on all of them `git-bash.exe` execution crashes by segmentation fault. 
I tried to remove all configs and setting in `E:\Users\[UserName]\`, but problem didn't resolved. 
I tried to run the `git-bash.exe` as administrator, but problem didn't resolved.
On same machine `cygwin` installation works. 
On same machine `/bin/bash` starts without problem. 
On same machine `git-gui.exe` and `gitk.exe` start without problem.
On same machine `/usr/bin/mintty.exe` starts without problem. 
On same machine `git-cmd.exe` starts without problem. 
On the windows 10 machine, `git-bash.exe` from `git verison 2.14.2` works.

**Comment by dscho** [comment]
This has been reported before, and is one of the two reasons why v2.19.2 was demoted to "pre-release" status.

Normally, I would have published a v2.19.2(2) in one big hurry, but there have been more changes in the pipeline which would be very hard to roll back just for a v2.19.2(2), *and* I am rather busy with preparing the Windows side for v2.20.0 (which is now expected Dec 10th).

So please, for the moment, either switch to a snapshot (https://wingit.blob.core.windows.net/files/index.html) or downgrade to v2.19.1, until v2.20.0 comes out.
