### ISSUE TITLE
Unable to install "make": path with spaces?

### ISSUE THREAD

**Issue by slaout** [git-for-windows/git#1964]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [version 10.0.17134.345]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I installed mingw-get:

```
mingw-get version 0.6.3-pre-20170905-1
Copyright (C) 2009-2013, MinGW.org Project
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mingw-get install mingw32-make
```
 - What did you expect to occur after running these commands?

I wanted `mingw32-make` to become available

 - What actually happened instead?

`mingw32-make` is not available.

I suspect it installed on "C:\Program Files" and the space made the install process not working.

=> I want to be able to install Git for Windows in the directory of my choosing (one without any space, like C:\git): the installer do not provide me this option.  
=> Alternatively, there should be a solution in Git for Windows to "upgrade" the UNIX environment to a more complete one (have a mingw-get or equivalent by default...).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No

**Comment by dscho** [comment]
> mingw-get install mingw32-make

This is so not about Git for Windows. Please report this with the `mingw-get` project. Git for Windows does *not* support `mingw-get`.
