### ISSUE TITLE
GIT bash on Windows: VIM of GIT doesn't find Python3

### ISSUE THREAD

**Issue by Artisanate** [git-for-windows/git#1966]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

$ git --version --build-options)

 ![](https://github.com/Artisanate/Git_Learn/blob/master/Picture/1.png?raw=true)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [版本 6.3.9600] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

 $ cat /etc/install-options.txt **
 Editor Option: VIM 
Custom Editor Path: 
Path Option: Cmd 
SSH Option: OpenSSH 
 CURL Option: OpenSSL 
CRLF Option: CRLFAlways 
Bash Terminal Option: MinTTY 
Performance Tweaks FSCache: Enabled 
 Use Credential Manager: Enabled 
Enable Symlinks: Disabled 
Enable Builtin Rebase: Disabled 
Enable Builtin Stash: Disabled 
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Git Bash **

    First of all，I am a Chinese.So I think my English is just so so .But I will try my best let you understand my problem I am meeting.
	Yesterday,I installed the lateset Git For Windows version.I find that VIM exist.I am so happy.Beacuse it can let me work well.I want install plug of vim .The plug need the python supports.
	Furthermore i've installed the 64bit version of Python 3.6.5 in the following directory:"C:\Users\Mr.Hu\AppData\Local\Programs\Python\Python36-32" I've added "C:\Users\Mr.Hu\AppData\Local\Programs\Python\Python36-32" and"C:\Users\Mr.Hu\AppData\Local\Programs\Python\Python36-32/Scripts/" to my PATH variable.
    I have added the variable(set pythonthreedll = "~/AppData/Local/Programs/Python/Python36-32/python36.dll") in .vimrc script.
	But when I call echo has("Python") or has("Python3"),and return 0.	
	I just want  vim of git supports the python . 
       Think you very much.

**Comment by dscho** [comment]
Yes, the Vim shipped in Git for Windows was compiled without support for Python3.

You probably want to install Vim for Windows (e.g. from https://www.vim.org/download.php), and then select the `gvim.exe` and use `C:\<whereveryouinstalledit>\gvim.exe -f` as custom editor in Git for Windows' installer (why `-f`? see http://git.661346.n2.nabble.com/using-gvim-as-editor-on-Windows-td4685398.html for details).

**Comment by dscho** [comment]
No feedback = can close the ticket
