### ISSUE TITLE
Update docs to include description of `symlink` gitattribute

### ISSUE THREAD

**Issue by piscisaureus** [git-for-windows/git#1969]
I added support for the 'symlink' git attribute in https://github.com/git-for-windows/git/commit/bde36960f0ae90ab15b263a75ef1bf5ebbf88220, and this feature has now been released in git version 2.19.2.windows.1. The patch included a documentation update.

However, the added documentation isn't shown on https://git-scm.com/docs/gitattributes, and the feature wasn't mentioned in the release notes, so this shiny new thing now has a bit of a discoverability problem.

@dscho Would it be possible to push the doc change to the git docs website?

**Comment by dscho** [comment]
> the added documentation isn't shown on https://git-scm.com/docs/gitattributes

That site only shows the documentation of the latest official Git version, not the latest official Git for Windows version.

Given that the entire symbolic link support is still not quite ready for upstream Git, it would not make too much sense for Git (not for Windows) to talk about it in it documentation...

> the feature wasn't mentioned in the release notes

Whooops! My bad!

But wait... in https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#changes-since-git-for-windows-v2191-oct-5th-2018, you will see this line:

> * The type of symlinks to create (directory or file) [can now be specified via the `.gitattributes`](https://github.com/git-for-windows/git/pull/1897).

This should also be in the page shown by `git help gitattributes`... does that not work?

**Comment by piscisaureus** [comment]
> That site only shows the documentation of the latest official Git version, not the latest official Git for Windows version.

I see... there is a difference between 'git (official)' and 'git for windows'. 

> it would not make too much sense for Git (not for Windows) to talk about it in it documentation...

I have a somewhat different philosophy about that... there's no separate documentation page for "git for windows"; most users would expect that the docs they find on git-scm.org to be applicable to the software they downloaded from git-scm.org... (For that matter, I think the fact that they downloaded an unofficial version of git from the official website is also lost on most people.)

But it sounds like I would have to convince a lot more people besides you, which for now I am not going to attempt...

> Given that the entire symbolic link support is still not quite ready for upstream Git

Out of curiosity: what's holding it back?

> This should also be in the page shown by git help gitattributes... does that not work?

It does work! So we've got the 1% of the population that doesn't use google for everything covered :)
(J/K -- I'm not trying to be sarcastic, I appreciate your work on git very much.)

**Comment by dscho** [comment]
> most users would reasonably expect that the docs they find on git-scm.com are applicable to the software they downloaded from git-scm.com...

In an ideal world...

> > Given that the entire symbolic link support is still not quite ready for upstream Git
> 
> Out of curiosity: what's holding it back?

It's entangled with the long path support and the FSCache feature, and the latter saw a flurry of development recently (affecting symbolic link support, too).

In any case, there are *a lot* of patches already in the pipeline to be submitted upstream, and symlink support has to do the British thing and queue at the end, please: https://github.com/git-for-windows/git/issues/1884
