### ISSUE TITLE
The installer hangs prior to completing installation

### ISSUE THREAD

**Issue by ciaranj** [git-for-windows/git#197]
(RC-2 installer) I noticed this on the previous installer, but the installation process currently hangs indefinitely (well certainly for as long as I had patience.)  

For me this is caused by my usage of https://help.github.com/articles/working-with-ssh-key-passphrases/#auto-launching-ssh-agent-on-msysgit in my .profile file.  If I kill the 'ssh-add.exe' that appears at the end of the installation, the installation will complete as expected.

Not sure how to resolve this (but the 1.9.x installer did not suffer this beheaviour iirc.)

**Comment by dscho** [comment]
This means that in your setup, you cannot run any non-interactive Bash at all, which is a big problem if you use *any* other application that wants to call Git in the background.

I guess you will need to guard calling `ssh-agent` in your `$HOME/.bash_profile` (or wherever you have that, the report does not contain that information), e.g. by something like

```bash
if test -t 0
then
    # we know that stdin is a terminal, i.e. this session is interactive
    ...
fi
```

**Comment by ciaranj** [comment]
Ah. Ok, that makes perfect sense, thank you. Just to check, should i be doing my ssh-agent config in a different way, or with the suggested fix would that still be appropriate?

**Comment by dscho** [comment]
> should i be doing my ssh-agent config in a different way, or with the suggested fix would that still be appropriate?

I have not enough information to assess that.

**Comment by ciaranj** [comment]
@dscho I couldn't actually get your suggestion working (bash is not my thing) but I found a solution that is based on the same idea just using a different construct, I've written up the resulting instructions here: https://github.com/git-for-windows/git/wiki/Auto-launching-ssh-agent-when-git-starts

**Comment by dscho** [comment]
Very nice, great contribution!
