### ISSUE TITLE
git archive error "gzip -cn: gzip: command not found" with MinGit package on windows

### ISSUE THREAD

**Issue by Rastaban** [git-for-windows/git#1970]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

`git archive` does not work if you have the windows MinGit package installed because gzip is missing from the package.

```
gzip -cn: gzip: command not found
```

**Comment by dscho** [comment]
Full example, please.

**Comment by Rastaban** [comment]
Full example:
```
PS E:\vcpkg\vcpkg> git.exe archive FETCH_HEAD -o e:\vcpkg\vcpkgarchive.tar.gz
gzip -cn: gzip: command not found
PS E:\vcpkg\vcpkg>
```

**Comment by dscho** [comment]
Okay, it is specific to `.tar.gz` files. The major problem I have here is that `gzip.exe` would be needed *only* for this obscure command, and it would increase the size of the MinZip package (which I don't want). Also, it would encourage people to use `gzip` from the MinGit package, and that is not what MinGit is about.

Besides, the `gzip.exe` in Git for Windows' SDK is an MSYS2 one, i.e. it incurs all the problems we have occasionally with the MSYS2 runtime and its DLL base address.

So my current thinking is: If we can somehow implement the bare minimum code in `archive-tar.c` to perform `gzip` compression (we already link to zlib, and AFAIU `gzip` only adds a file header), then we could neatly side-step this issue *without* bundling `gzip.exe`.

**Comment by dscho** [comment]
> the bare minimum code in `archive-tar.c` to perform `gzip` compression

This should help: https://github.com/madler/zlib/blob/master/test/minigzip.c

**Comment by dscho** [comment]
@Rastaban I had a thorough look today, and it seems that the proper solution to this would be to change [`archive-tar.c`](https://github.com/git/git/blob/v2.20.0/archive-tar.c) to use the `git_deflate()` facility (with appropriate initialization and cleanup), essentially by changing all call sites of `write_or_die()` so that they use a `git_zstream *` (which will have to be handed all the way down in the form of function parameters).

Based on past experience with Git for Windows users, I am not sure whether you fall into the exciting group of contributors who only need minimal guidance and are eager to fix their issue?

If not, you can just go and copy `gzip.exe` e.g. from http://github.com/git-for-windows/git-sdk-64/tree/master/usr/bin.

Of course, I hope you fall into that exciting group, in which case I would be happy to assist you.

**Comment by Rastaban** [comment]
@dscho, I am unable to commit to it at this time.  In order to unblock vcpkg we will switch to one of the larger packages that already has gzip.  When I have a block of free time I will take you up on your offer to assist me in making this change (unless someone else gets to it first)

for future reference, where would I find the instructions for building git on windows?

**Comment by dscho** [comment]
> where would I find the instructions for building git on windows?

Here: https://github.com/git-for-windows/git/wiki/Building-Git

> When I have a block of free time I will take you up on your offer to assist me in making this change

Excellent.

**Comment by r1walz** [comment]
@dscho @Rastaban : If any of you haven't started to work on this issue, can I take this up? This would be my first contribution.

**Comment by Rastaban** [comment]
@r1walz I haven't had a chance to look at it yet, and would be happy to let you take it over.

**Comment by dscho** [comment]
@r1walz go for it! Do you have information to get started?

**Comment by r1walz** [comment]
@dscho : yes, I'd love to receive some extra information

**Comment by PhilipOakley** [comment]
Hi @r1walz - Is there any specific information that is currently missing in this issue (#1970) thread for you, at least to get started with a trial build of the current release, just to 'pipe clean' the process?

If any of the wiki/Building-Git steps fail to work for you then do please do tell us so we can improve them.

Philip

**Comment by dscho** [comment]
@r1walz did you manage to compile (and use) minigzip.c (mentioned in https://github.com/git-for-windows/git/issues/1970) yet?

**Comment by r1walz** [comment]
@dscho yes, I was able to compile and run `minigzip.c`, but are we not going according to this [plan](https://github.com/git-for-windows/git/issues/1970#issuecomment-445525496)?

**Comment by dscho** [comment]
For lurkers: [we talked more on IRC](https://colabti.org/irclogger/irclogger_log/git-devel?date=2019-02-12#l113).

**Comment by dscho** [comment]
@r1walz this was quite the pleasant contribution, thank you so much!
