### ISSUE TITLE
git help -a hangs v2.20

### ISSUE THREAD

**Issue by 0x0309** [git-for-windows/git#1975]
``git help -a``
Running this command hangs git version ``2.20.0.windows.1`` if there is an alias with a name longer than 18 chars. This did not happen in ``2.19.2``

.gitconfig:
```
[alias]
  alias-with-19-chars = ...
```

This hangs in cmd, powershell, and git bash.

**Comment by dscho** [comment]
It reproduces here (despite the minimalistic bug report, why is it that all of a sudden everyone simply deletes the template instead of filling it out?) and I'm on it.
