### ISSUE TITLE
The file content has not changed, but the bit size has changed.

### ISSUE THREAD

**Issue by frankful** [git-for-windows/git#1980]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windows server 2012
```
$ cmd.exe /c ver

** insert your machine's response here **
```
cmd.exe /c ver

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
"C:\Program Files\Git\etc\install-options.txt"
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
git clone   and git pull
 - What did you expect to occur after running these commands?

** insert here **
default 
 - What actually happened instead?

** insert here **

The file content has not changed, but the bit size has changed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by siprbaum** [comment]
You are supposed to run those  commands above ... and explain what the problem is. 
The above doesn't help *anyone* to reproduce the issue

**Comment by frankful** [comment]
Thanks, I have found the problem, I use dos2unix filesname, the file size is restored.
