### ISSUE TITLE
Detect and use win32 openssh if installed

### ISSUE THREAD

**Issue by WSLUser** [git-for-windows/git#1981]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 
      2.2 via Chocolatey.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

 Win 7 SP2

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD or Powershell. Often via VS Code integrated terminal.
ssh user@server.com

 - What did you expect to occur after running these commands?

 I expect to use the Win32 OpenSSH port instead of the tweaked OpenSSL. Here's the link to the [project](https://github.com/PowerShell/Win32-OpenSSH)

 - What actually happened instead?

It didn't use it.

**Comment by kghost** [comment]
This should words:

`git config --global --add core.sshCommand C:/Windows/System32/OpenSSH/ssh.exe`

**Comment by DarthSpock** [comment]
Thanks for those references, I didn't see those for whatever reason. Don't have time myself to work on those but I can adopt the tweaks mentioned for now.

**Comment by dscho** [comment]
Thanks @congyiwu for putting in a bit of effort to drive this issue, even if it is now blocked.

**Comment by dscho** [comment]
> I found two: #1556 and #1683. Of particular note: [#1556 (comment)](https://github.com/git-for-windows/git/issues/1556#issuecomment-410237781)

I'll close this ticket in favor of https://github.com/git-for-windows/git/issues/1683 (which saw more action from interested volunteers).

**Comment by TheBigBear** [comment]
What helped me the most debugging this was to enable git tracing

in cmd line set GIT_TRACE=1

in powershell or pwsh $env:GIT-TRACE=1
