### ISSUE TITLE
gitk pops up Error: couldn't execute "git": filename too long

### ISSUE THREAD

**Issue by shimpe** [git-for-windows/git#1987]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

gitk

```
 - What did you expect to occur after running these commands?

I expected to see a history of commits

 - What actually happened instead?

Error message appears:  "Error: couldn't execute "git": filename too long"

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

private repo

**Comment by shimpe** [comment]
Started after upgrade from 2.20.0 to 2.20.1

**Comment by dscho** [comment]
Sorry, cannot reproduce. I would need at least an [MCVE](https://stackoverflow.com/help/mcve) to make sense of this report.

**Comment by shimpe** [comment]
Sorry I cannot share the repository. I've downgraded and the problem is gone.

**Comment by dscho** [comment]
> Sorry I cannot share the repository.

There are many more ways that you can work on providing an MCVE than to share the original repository.

> I've downgraded and the problem is gone.

In case you become interested in seeing this issue fixed (future Git versions will most likely suffer the same bug as v2.20.1 for you, after all), we can easily reopen once you provide an MCVE.

**Comment by shimpe** [comment]
I noticed some missing info I was fairly certain I had added to the bug report, so I just reupgraded to repro once more and now it's not repro anymore on my system as well... let's just consider it a glitch for now, and if it returns it'll have to be examined in more depth.

**Comment by PhilipOakley** [comment]
Hi @shimpe, The updates to the original message aren’t emailed out to the supporters, so it is worth quoting the text in a separate comment.  

While the repo may be private, if you think that 'long' file name' may be the issue, at least quote those parts you can, and do a character replacement, say [a-z] -> 'x', [A-Z] -> 'Y', [0-9] -> '3', which should make the path secret enough but still inform us of the true length and the sorts of characters included in the path (are there non-ASCII chars?), and directory depth.

**Comment by shimpe** [comment]
@PhilipOakley  That's a possibility, but for now it's no longer repro on my system either.

**Comment by shimpe** [comment]
I found back the extra info I was looking for:

couldn't execute "git": file name too long
couldn't execute "git": file name too long
    while executing
"open $cmd r"
    (procedure "getallcommits" line 48)
    invoked from within
"getallcommits"
    (procedure "readcache" line 80)
    invoked from within
"readcache file5397160"
    ("eval" body line 1)
    invoked from within
"eval $script"
    (procedure "dorunq" line 11)
    invoked from within
"dorunq"
    ("after" script)

**Comment by pantosha** [comment]
I have the same issue. Removing of `.git/gitk.cache` is fix issue for once, but after a second `gitk` run issue is returned.

![image](https://user-images.githubusercontent.com/1799798/50284608-9ab35800-046a-11e9-923a-34ceda41c6eb.png)
[gitk.log](https://github.com/git-for-windows/git/files/2698815/gitk.log)

**Comment by pantosha** [comment]
I uninstall git and install it again. Now, gitk works without errors.

**Comment by PhilipOakley** [comment]
Thanks for confirming. If it arises again, just start a new issue and cross reference this one.

**Comment by max630** [comment]
This happens whe there are many references, maybe their name lengths also matter

Steps to reproduce:

```
# start in an empty directory
git init
for b in `seq 1 1000`; do git commit --allow-empty -m c$b; git branch long-branch-name-b$b-uhuhkjnkhnkjnknkjnknkjnkn; done
gitk --all &
# wait until it loads
git commit --allow-empty -m another
# press F5 in gitk
```
