### ISSUE TITLE
File named "..." conflicts with ../ or ./

### ISSUE THREAD

**Issue by mircearoata** [git-for-windows/git#1988]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10, 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.194]
--



```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cat > ...
Any number of dots work (at least 3)
```
 - What did you expect to occur after running these commands?

It shouldn't allow me to create such a file, as it interferes with ../ and ./ used by Windows to address folders relative to the current one.

 - What actually happened instead?

A file named "..." was created and couldn't be deleted from Windows, but only deletable from Git Bash using rm.

**Comment by rimrul** [comment]
`...` is a valid NTFS filename. Why should bash stop you from using it? It's a little frowned upon, because some Microsoft applications can't handle file names ending in a period, but I don't see how it interferes with anything.

**Comment by mircearoata** [comment]
Windows file explorer does not allow me to create a file with that name and I think there is a reason it does this. If, however this is intended, I will close the issue.

**Comment by rimrul** [comment]
>Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

(Source: https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file)

That's what I meant by "some Microsoft applications can't handle file names ending in a period". It's not strictly a Name that's not allowed, just a name that Windows Explorer, CMD and probably some other applications struggle with.
