### ISSUE TITLE
Copying and paste bug

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#199]
Please change the command for keybord from citrl + sift + ins key to windows key + v and please bring the keybords actions for other commands for default windows like windows key + c which would be copying.

**Comment by nalla** [comment]
Copy and pasting is provided by the `mintty` terminal console. If you want a different behavior, feel free to have a look at the [mintty man page](http://mintty.googlecode.com/svn-history/r1065/trunk/docs/mintty.1.html). But a quick look gave me the impression that you can not alter the short cuts. Maybe you can look into using [ConEmu](https://code.google.com/p/conemu-maximus5/) instead?

But this is clearly not a *Git for Windows* issue. So If you would be so kind to close the issue again that would be great.

**Comment by paladox** [comment]
Hi well not a bug then but a feature request please change sorcuts to match windows defaults sorcuts please.

**Comment by dscho** [comment]
@paladox the software in question is still the MinTTY software, therefore the best place to submit this feature request is with that project (Git for Windows will not fork MinTTY, not unless there are really, really compelling reasons to take on that maintenance burden).

Please note, though, that MinTTY is intended to be used with Bash whose keyboard shortcuts disagree with Windows' conventions. Ctrl+V already has a different meaning in Bash, for example, and it would be much easier for you to learn the Shift+Ins keyboard shortcut than to convince the hundreds of thousands of existing Bash users out there to retrain their fingers.
