### ISSUE TITLE
"git svn fetch" hangs (perl.exe)

### ISSUE THREAD

**Issue by dex-ds** [git-for-windows/git#1993]
on current 2.20.1 x64 portable. 2.20.0 runs fine...
cheers, ds

**Comment by CrOrc** [comment]
The same goes for "git svn rebase", "git svn dcommit"

**Comment by dscho** [comment]
This bug report is *very* short. And *very* incomplete.

**Comment by CrOrc** [comment]
Commands are running without any output at 100% CPU.
Perl hangs when fetching from any svn repo.

**Comment by CrOrc** [comment]
Here's output of `git svn rebase` with GIT_TRACE=1

> 03:44:34.928244 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/bin
03:44:34.929244 git.c:675               trace: exec: git-svn rebase
03:44:34.929244 run-command.c:643       trace: run_command: git-svn rebase
00:44:35.297265 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.297265 git.c:418               trace: built-in: git rev-parse --git-dir
00:44:35.340267 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.341268 git.c:418               trace: built-in: git rev-parse --show-cdup
00:44:35.387270 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.388270 git.c:418               trace: built-in: git config --get svn.username
00:44:35.430273 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.431273 git.c:418               trace: built-in: git config --bool --get svn.quiet
00:44:35.476275 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.476275 git.c:418               trace: built-in: git config --bool --get svn.verbose
00:44:35.520278 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.521278 git.c:418               trace: built-in: git config --bool --get svn.noauthcache
00:44:35.566280 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.566280 git.c:418               trace: built-in: git config --int --get svn.logwindowsize
00:44:35.614283 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.615283 git.c:418               trace: built-in: git config --get svn.ignorepaths
00:44:35.658286 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.659286 git.c:418               trace: built-in: git config --bool --get svn.noMetadata
00:44:35.703288 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.704288 git.c:418               trace: built-in: git config --bool --get svn.useSvmProps
00:44:35.749291 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.750291 git.c:418               trace: built-in: git config --get svn.includepaths
00:44:35.797294 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.797294 git.c:418               trace: built-in: git config --bool --get svn.nocheckout
00:44:35.838296 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.839296 git.c:418               trace: built-in: git config --bool --get svn.fetchall
00:44:35.883299 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.883299 git.c:418               trace: built-in: git config --int --get svn.repack
00:44:35.924301 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.925301 git.c:418               trace: built-in: git config --bool --get svn.addauthorfrom
00:44:35.965303 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:35.966303 git.c:418               trace: built-in: git config --get svn.authorsfile
00:44:36.007306 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.008306 git.c:418               trace: built-in: git config --bool --get svn.followparent
00:44:36.050308 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.051308 git.c:418               trace: built-in: git config --get svn.repackflags
00:44:36.095311 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.095311 git.c:418               trace: built-in: git config --bool --get svn.dryrun
00:44:36.138313 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.138313 git.c:418               trace: built-in: git config --bool --get svn.useSvnsyncProps
00:44:36.180316 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.181316 git.c:418               trace: built-in: git config --get svn.ignorerefs
00:44:36.222318 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.223318 git.c:418               trace: built-in: git config --bool --get svn.local
00:44:36.266320 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.267321 git.c:418               trace: built-in: git config --bool --get svn.merge
00:44:36.308323 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.309323 git.c:418               trace: built-in: git config --bool --get svn.preservemerges
00:44:36.351325 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.352325 git.c:418               trace: built-in: git config --get svn.strategy
00:44:36.396328 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.397328 git.c:418               trace: built-in: git config --get svn.configdir
00:44:36.438330 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.439330 git.c:418               trace: built-in: git config --bool --get svn.uselogauthor
00:44:36.484333 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.485333 git.c:418               trace: built-in: git config --get svn.authorsprog
00:44:36.527335 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.527335 git.c:418               trace: built-in: git config --bool --get svn.localtime
00:44:36.569338 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.570338 git.c:418               trace: built-in: git rev-parse --symbolic --all
00:44:36.615340 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.615340 git.c:418               trace: built-in: git rev-parse --git-path svn
00:44:36.659343 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.659343 git.c:418               trace: built-in: git config -l
00:44:36.702345 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.703345 git.c:418               trace: built-in: git config -l
00:44:36.745348 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.746348 git.c:418               trace: built-in: git update-index --refresh
00:44:36.994362 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:36.995362 git.c:418               trace: built-in: git rev-list --first-parent --pretty=medium HEAD --
00:44:37.037365 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.037365 git.c:418               trace: built-in: git config --bool svn.useSvmProps
00:44:37.080367 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.081367 git.c:418               trace: built-in: git config -l
00:44:37.128370 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.128370 git.c:418               trace: built-in: git config --get svn-remote.svn.rewriteRoot
00:44:37.172372 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.172372 git.c:418               trace: built-in: git rev-parse --git-path svn
00:44:37.216375 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.217375 git.c:418               trace: built-in: git config --get svn-remote.svn.fetch ':refs/remotes/git-svn$'
00:44:37.260377 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.261377 git.c:418               trace: built-in: git config --get svn-remote.svn.url
00:44:37.302380 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.303380 git.c:418               trace: built-in: git config --get svn-remote.svn.pushurl
00:44:37.347382 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.347382 git.c:418               trace: built-in: git rev-parse --git-path svn
00:44:37.391385 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.391385 git.c:418               trace: built-in: git config --get svn-remote.svn.uuid
00:44:37.481390 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.482390 git.c:418               trace: built-in: git rev-list --pretty=raw --reverse 72574fecc2847c3ea8a1af86a734f223a752bfd8..refs/remotes/git-svn --
00:44:37.506391 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.507391 git.c:418               trace: built-in: git config --get svn-remote.svn.rewriteRoot
00:44:37.550394 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.551394 git.c:418               trace: built-in: git config --get svn-remote.svn.rewriteUUID
00:44:37.601397 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.601397 git.c:418               trace: built-in: git diff-index HEAD --
00:44:37.849411 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.850411 git.c:418               trace: built-in: git config --get svn-remote.svn.usesvmprops
00:44:37.894414 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.895414 git.c:418               trace: built-in: git config --get svn-remote.svn.nometadata
00:44:37.939416 exec-cmd.c:236          trace: resolved executable dir: D:/PortableGit/mingw64/libexec/git-core
00:44:37.940416 git.c:418               trace: built-in: git cat-file commit 72574fecc2847c3ea8a1af86a734f223a752bfd8

**Comment by CrOrc** [comment]
Perl is hanging busy at last command

> 00:44:37.940416 git.c:418 trace: built-in: git cat-file commit 72574fecc2847c3ea8a1af86a734f223a752bfd8

**Comment by CrOrc** [comment]
Here's my config

> [core]
	fscache = true
	autocrlf = false
[credential]
	helper = wincred
[pack]
	packSizeLimit = 1g
[rebase]
	useBuiltin = true
[stash]
	useBuiltin = true

**Comment by CrOrc** [comment]
In git v2.19.1 after that goes

> 01:23:16.890053 git.c:415               trace: built-in: git rev-parse --git-path svn
01:23:16.932055 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
01:23:16.933055 git.c:415               trace: built-in: git config --get svn-remote.svn.fetch ':refs/remotes/git-svn$'
01:23:16.975057 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
01:23:16.975057 git.c:415               trace: built-in: git config --get svn-remote.svn.url
01:23:17.018060 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
01:23:17.018060 git.c:415               trace: built-in: git config --get svn-remote.svn.pushurl
01:23:17.062062 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
01:23:17.062062 git.c:415               trace: built-in: git rev-parse --git-path svn
01:23:17.105065 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
01:23:17.105065 git.c:415               trace: built-in: git config --get svn-remote.svn.uuid
01:23:17.151067 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
01:23:17.151067 git.c:415               trace: built-in: git rev-parse --git-path svn
01:23:17.194070 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
01:23:17.195070 git.c:415               trace: built-in: git config svn-remote.svn.reposRoot https://private-repo-url

**Comment by dex-ds** [comment]
Maybe helpful or not..
the stack of the hanging perl.exe

msys-serf-1-0.dll!serf__spnego_init_sec_context+0x518
msys-crypto-1.1.dll!CRYPTO_zalloc+0xd
msys-crypto-1.1.dll!CRYPTO_THREAD_lock_new+0x1c
msys-crypto-1.1.dll!HMAC_CTX_get_md+0x295
msys-2.0.dll!_getreent+0x612b
msys-2.0.dll!acl_get_perm+0x930a
msys-crypto-1.1.dll!OPENSSL_init_crypto+0x73
msys-serf-1-0.dll!serf_bucket_socket_set_read_progress_cb+0xb22
msys-serf-1-0.dll!serf_bucket_ssl_decrypt_create+0x1a
msys-svn_ra_serf-1-0.dll!svn_ra_serf__conn_setup+0x4c
msys-serf-1-0.dll!serf_listener_create+0xac3
msys-serf-1-0.dll!serf__open_connections+0x1fb
msys-serf-1-0.dll!serf_context_prerun+0x10
msys-serf-1-0.dll!serf_context_run+0x16
msys-svn_ra_serf-1-0.dll!svn_ra_serf__context_run+0x61
msys-svn_ra_serf-1-0.dll!svn_ra_serf__context_run_wait+0x55
msys-svn_ra_serf-1-0.dll!svn_ra_serf__context_run_one+0x24
msys-svn_ra_serf-1-0.dll!svn_ra_serf__exchange_capabilities+0x68
msys-svn_ra_serf-1-0.dll!svn_ra_serf__reparent+0x1765
msys-svn_ra-1-0.dll!svn_ra_open4+0x216
msys-svn_ra-1-0.dll!svn_ra_open+0xab
_Ra.dll!wrap_svn_ra_open+0x16b
msys-perl5_26.dll!Perl_pp_entersub+0x425
msys-perl5_26.dll!Perl_runops_standard+0x16
msys-perl5_26.dll!perl_run+0x275
perl.exe!main+0x14a
msys-2.0.dll!msys_dll_init+0x1234
msys-2.0.dll!setprogname+0x33b3
msys-2.0.dll!setprogname+0x3464

**Comment by dex-ds** [comment]
my git svn traces looks like crOrcs ouput.
I also tried GIT_CURL_VERBOSE=1, GIT_TRACE=2, GIT_CURL_VERBOSE=2, all attempts to get more debug output fails. (I'm not a perl specialist)

Windows environment:
Windows 10 Ent. LTSB 2016, latest patch
Portable 64bit version
git --version
git version 2.20.1.windows.1
Until this version, the "git svn" cmds working.
In my case Versions 2.20.0 (my fallback), 2.19.x are ok.

**Comment by dstcruz** [comment]
I can chase this rabbit all the way to `c:/Program Files/Git/mingw64/share/perl5/Git/SVN/Ra.pm`, but then, it wants to call something in `SVN::Ra`. I can't, for the life of me find that module. I can only find `Git::SVN::Ra`. In my case, I get to the `new` function in `Git::SVN::Ra`, and then it hangs here:

```
	my $self = SVN::Ra->new(url => $url, auth => $baton,
	                      config => $config,
			      pool => SVN::Pool->new,
	                      auth_provider_callbacks => $callbacks);
````

Hope this helps.

**Comment by fuzzzerd** [comment]
> Commands are running without any output at 100% CPU.
> Perl hangs when fetching from any svn repo.

I'm experiencing the same behavior for `git svn clone` as well. Downgrade to v2.20.0 and it works as it always had before.

**Comment by llongmanne559** [comment]
Almost same here.
The CPU usage of perl.exe is 12%..13%. It seems to hang after a message "Initialized empty Git repository in <REPO_NAME>/.git/" is shown when I execute a command "git svn clone".
v2.20.0 is OK, so I downgraded to it from v2.20.1.

**Comment by raijinsetsu** [comment]
Same symptoms and log output here as well.

**Comment by belucha** [comment]
I have the same issues on two different machines.

**Comment by 13BTurbo** [comment]
Same problem here.
Rebuilt my laptop with fresh install of Windows 10, installed latest git...
Now git svn clone, git svn fetch, and git svn rebase all hang with perl.exe using about 18% CPU.
Downgrade to 2.20.0 and it all works fine.

SVN repository is via https and requires username and password. 2.20.0 prompts to accept certificate (self signed). 2.20.1 doesn't prompt at all.

**Comment by th3ragex** [comment]
Same here. 
Windows 10 1607. The SVN repository requires username and password over HTTPS. The HTTPS is encrypted a self signed certificate and gets tunneled through a VPN connection to an internal network. The self signed certificate has been (manually) added to the windows certificate store.

I **believe** i've also accepted a git console prompt months ago (pre git 2.20.0) to add a permanent security exception for the certificate/connection, which was probably before adding the certificate to the windows cert store.

**Comment by m1ndwalker** [comment]
I faced the same issue, downgrading to 2.19.2 sorted it out

**Comment by ysae** [comment]
Same issue with 2.20.1.
`git svn fetch` just stalling, without any network activity.
Also, when try to clone another git repo from svn, it just wrote about initializing, and then stalling.
Removing svn credentials doesn't take effect: git clone asks nothing.
But, when downgrading to 2.19.1, all stuff start work well:
* `git svn clone` ask for password and start fetching commits,
* `git svn fetch` just works, downloading recent commits from svn.

**Comment by nga888** [comment]
I have just recently run into this issue with git svn dcommit.

I believe that the issue is in OpenSSL, see https://github.com/openssl/openssl/issues/2865. Pulling in the OpenSSL fix should hopefully resolve this issue.

**Comment by pisek** [comment]
> Same issue with 2.20.1.
> `git svn fetch` just stalling, without any network activity.
> Also, when try to clone another git repo from svn, it just wrote about initializing, and then stalling.
> Removing svn credentials doesn't take effect: git clone asks nothing.
> But, when downgrading to 2.19.1, all stuff start work well:
> 
> * `git svn clone` ask for password and start fetching commits,
> * `git svn fetch` just works, downloading recent commits from svn.

I can confirm that `git svn clone` error only happens on 2.20.1 version. 2.20.0 and previous seem to be working fine.

**Comment by PhilipOakley** [comment]
> `git svn clone` error only happens on 2.20.1 version. 2.20.0 and previous seem to be working fine.

Have you had chance to see what was in the 'minor' fix from 20.0 to 20.1? I have memories that suggest they were various cascaded networking library code fixes, which may give a better clue.

**Comment by nga888** [comment]
I have confirmed that this is indeed related to https://github.com/openssl/openssl/issues/2865. Pulling in the OpenSSL fix from https://github.com/openssl/openssl/commit/ef45aa14c5af024fcb8bef1c9007f3d1c115bd85 and also rebuilding the "serf" package, fixes my git svn problems.

I guess there could be other packages that might also be impacted by this OpenSSL issue.

**Comment by dscho** [comment]
@nga888 excellent work!

So what will need to happen now:

- [ ] git-for-windows/MSYS2-packages needs to be changed so that `openssl/` contains that patch and `openssl/PKGBUILD` applies that patch (similar to the already-existing patches there)
- [ ] OpenSSL needs to be rebuilt (but only the MSYS2 packages, the MINGW packages should be left alone), with a forced pkgrel 3
- [ ] the git-for-windows/build-extra repository will need a PR to adjust `please.sh` to be able to upgrade `serf`. For this, a new section like [this](https://github.com/git-for-windows/build-extra/blob/f79a80a82668d9c16ee98aa0d1bd982a8fecea67/please.sh#L436-L439) and [that](https://github.com/git-for-windows/build-extra/blob/f79a80a82668d9c16ee98aa0d1bd982a8fecea67/please.sh#L3165-L3195) (i.e. imitating `openssh`) will need to be added, for which we need some sort of a ChangeLog for serf, as well as a website stating the current version. I guess we could use https://svn.apache.org/repos/asf/serf/trunk/CHANGES for the ChangeLog, and scrape https://serf.apache.org/download for the version number.
- [ ] A new `serf` version will need to be built and published.

I will obviously be stuck with the building and publishing, and I would really appreciate help with the other two tasks.

**Comment by nga888** [comment]
Thanks and you're welcome @dscho 

I've actually been testing this in MSYS2 with git-for-windows, as that's my preferred setup. I have just created this pull request https://github.com/Alexpux/MSYS2-packages/pull/1576 for the openssl patch. If it's accepted I guess you can merge it to your fork or you can just grab it directly if you want.

**Comment by dscho** [comment]
>     * A new `serf` version will need to be built and published.

This was done by upstream MSYS2, so I avoided that for the time being.

**Comment by dscho** [comment]
FWIW [v2.21.0-rc2](https://github.com/git-for-windows/git/releases/tag/v2.21.0-rc2.windows.1) has the proposed fix.

Please, all y'all, test away.

**Comment by llongmanne559** [comment]
Thanks so much dscho! I tried "git svn clone" with v2.21.0-rc2 today and it seemed work well. Great!

**Comment by dscho** [comment]
@llongmanne559 thanks for testing!
