### ISSUE TITLE
Git pull Error

### ISSUE THREAD

**Issue by yeyouqun** [git-for-windows/git#1994]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.16299.402]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
D:\euop>git pull
warning: failed to restrict file handles (5)

handle #0: 00000000000001f0 (type 3, handle info (1) 0
handle #1: 00000000000001f4 (type 3, handle info (1) 1
handle #2: 0000000000000158 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

fatal: NullReferenceException encountered.
   未将对象引用设置到对象的实例。
Username for 'http://git.eisoo.com:7990': ye.youqun
Password for 'http://ye.youqun@git.eisoo.com:7990':
fatal: NullReferenceException encountered.
   未将对象引用设置到对象的实例。
remote: Counting objects: 59, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 40), reused 0 (delta 0)
Unpacking objects: 100% (59/59), done.
From http://git.eisoo.com:7990/scm/euop/euomp
   6a320375..5ce284a2  branch_M49_PRF_325_20181221 -> origin/branch_M49_PRF_325_20181221
   417b1004..5246f94a  branch_PRF_318_319_20181204 -> origin/branch_PRF_318_319_20181204
Already up to date.
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
Yes there was small bug "failed to restrict file handles" at around the V2.19 time-frame. There was a bug fix release for it. Also the newer V2.20 has been released by upstream and a Git for Windows release made.

see https://github.com/git-for-windows/git/releases/ for all the releases.
