### ISSUE TITLE
error: cannot spawn F:\program\tool\git\tortoisegit\bin\TortoiseGitPlink.exe: No such file or directory fatal: unable to fork

### ISSUE THREAD

**Issue by followwwind** [git-for-windows/git#2001]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
Hi @followwwind The short subject line without any of the template details makes it had to respond.

It's not clear what commands or action you were using that generated that error message nor how it was displayed.

I see that the message is about TortoiseGit and Plink. In general, we are not able to advise on Tortoise Git. Howver the Plink problem does show up moderately often.

The C:\Program Files\Git\ReleaseNotes.html do have the Known Issue "If configured to use Plink, you will have to connect with `putty` first and accept the host key.". 

There is also the wiki page https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant  (Putty)

Plus the search bar https://github.com/git-for-windows/git/issues?utf8=%E2%9C%93&q=putty (i.e. delete the filters first) shows 45 issues, and slightly more if you then search for Plink.

Hope that helps

**Comment by dscho** [comment]
> The short subject line without any of the template details makes it had to respond.

This is the equivalent of going to the doctor, saying that something hurts, and then refusing to answer any questions. Even the best of all doctors would be very challenged to help such a patient.
