### ISSUE TITLE
Not visible what you are typing in BASH.

### ISSUE THREAD

**Issue by m-chichikalov** [git-for-windows/git#2005]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
$ git --version --build-options
git version 2.16.0.windows.2
cpu: x86_64
built from commit: a56c4f9e2a9513d2be57dc4346e0e84887399cd9
sizeof-long: 4

$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

the same issue on 
Microsoft Windows [Version 10.0.17763.195]

```
$ cat /etc/install-options.txt
Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 If you run any **git**  command which produces the result longer then the screen of terminal can fit, after you scroll to the end of the output [ ]

![](https://s8.hostingkartinok.com/uploads/images/2019/01/5ac64e58acc1db99e81e40367940a69f.jpg)
press **Ctrl+C** and start typing, everything what you typing is not visible anymore, 
![](https://s8.hostingkartinok.com/uploads/images/2019/01/8038259f1ede78203594461f96c98a96.jpg)
but if you hit Enter, it will execute what you entered.
![](https://s8.hostingkartinok.com/uploads/images/2019/01/55087c1deb41e1e17565d7072887df3a.jpg)

I strugle with **git-diff*, **git-reflog* and other cmds when I need more then  30 lines...
It lasts couple years already, did not find time to report, sorry...
Thank you in advance. Happy New Year!

**Comment by dscho** [comment]
I *think* this is an issue we already saw, and fixed. Could you try v2.20.1 (i.e. the current Git for Windows version)?

**Comment by m-chichikalov** [comment]
on Windows 10 I'm using 
2.20.1.windows.  -> the bahvior the same.

I will try to update to 2.20.2

Thank you for immediate response.

**Comment by m-chichikalov** [comment]
Updated on Windows 7 to 2.20.1, the same, even worst, seems like Ctrl+C is not working any more.
Tested on Windows 10 Ctrl+C -> the same, it stuck for 20...30 seconds, and only after this time you can leave the output of git-diff.

**Comment by m-chichikalov** [comment]
BTW, I found that it happends only when you use Ctrl+C to exit the editor. If use "Ctrl+q q" or "zz" everyting works fine.

**Comment by dscho** [comment]
> it happends only when you use Ctrl+C to exit the editor

Which editor? Where is there an editor involved in `git diff`? And which editor can you exit via Ctrl+C (vim should not exit when you hit Ctrl+C).

**Comment by m-chichikalov** [comment]
Yep, looks like it vim but not sure... During installation I did not change the default one, so probably vim. This is just habbit to exit by Ctrl+C... so, yes, when I use Ctrl+q q everything is fine. Should I close this one?
