### ISSUE TITLE
Lack fileC:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt 

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#2009]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
```
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

Windows Version

```
cmd.exe /c ver

Microsoft Windows [版本 10.0.17134.472]
```

Should contains ca-bundle.crt, or https proxy not works properly.

```
C:\Users\lygstate>set http_proxy=http://127.0.0.1:7073

C:\Users\lygstate>set https_proxy=https://127.0.0.1:7073

C:\Users\lygstate>set https_proxy=https://127.0.0.1:7073

C:\Users\lygstate>git ls-remote --tags https://github.com/kripken/emscripten
fatal: unable to access 'https://github.com/kripken/emscripten/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt
  CApath: none
```

**Comment by dscho** [comment]
This has been fixed recently (the indicated location is not the correct one, `C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt` is the correct one and Git now looks for that file in that location). Please upgrade and try again.
