### ISSUE TITLE
Git crashes with application error 0xc0000017

### ISSUE THREAD

**Issue by Tragen** [git-for-windows/git#2020]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.253]
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
I have the portable version
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
any command.
eg:
git
or
git --version --build-options
```
 - What did you expect to occur after running these commands?

git works

 - What actually happened instead?

git crashes
![image](https://user-images.githubusercontent.com/1700241/50985866-a17f3900-1505-11e9-85ee-1251611ab179.png)

This happens if the path is longer then 45 characters.
On other computers, when I use the same path, it's working.

As I have no problems with other software on my development computer.
The git version shipping with smartgit is also working.
Also the portable version 2.19.2 ist working without problems.

How can I help to narrow down the problem?

**Comment by Tragen** [comment]
I've made more tests.
This happens when I start git.exe directly in the bin folder or when I use git-cmd.exe.
When I use git-bash.exe, git is working.

**Comment by dscho** [comment]
> This happens when I start git.exe directly in the bin folder or when I use git-cmd.exe.

Does it work when you use `git.exe` from the `cmd` folder (which is the supported way, not the `bin` folder)?

**Comment by dscho** [comment]
The strangest thing about this is that the error corresponds to `STATUS_NO_MEMORY`... Do you have an overzealous anti-malware running, maybe?

**Comment by Tragen** [comment]
I have enough memory and free memory and no virus scanner installed. I have even Defender disabled.

**Comment by freitaz** [comment]
I am having an issue similar to this one.

It works if I run it from Git Bash. It worked until release 2.19.2. 
Below is info I was preparing for a new ticket.
Git version is same as Tragen's. Missing info fields are also similar to Tragen's.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Pro 64-bit.
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.472]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Corporate machine with DRM/encryption programs, in-house solution.
Kaspersky Endpoint Security installed. It is not an option to disable it (controlled by corporate policy).


### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD/PowerShell. Git Bash works.

**Comment by joel0** [comment]
I have the same problem.  I'm using Windows 10 Enterprise 1809 as Windows To Go (on a flash drive).  I'm using BitLocker and Windows Defender.  The x64 portable and installed version throw the mentioned error.  The x86 portable version seems to work.  The 2.19.2 x64 portable and installed version both work.

**Comment by stahta01** [comment]
> The strangest thing about this is that the error corresponds to `STATUS_NO_MEMORY`... Do you have an overzealous anti-malware running, maybe?

I am having problem with git using 1.5 gigs of memory.
It happens after I do an "git am" command on a repo where a prior git am failed.
I then do a "git am --abort" and redo the "git am" commands and this is when the git locks up and task manger says it is using 1.4 to 1.5 gigs of memory.  I plan to try to find a single test case to duplicate the issue; I will create a separate ticket/issue report when I can.
I posted in this thread to see if the others were doing "git am" commands to trigger the issue. 

Tim S.

**Comment by dscho** [comment]
Can you re-try with v2.21.0? There have been a couple of changes in that area that *might* work around (or fix) the reported issues.

**Comment by freitaz** [comment]
For me, it is working again. Basic git commands are working across CMD/Powershell/Git Bash.

**Comment by Tragen** [comment]
I have also an Nvidia GPU.
2.21 is working also for me.
Would be interesting to know what the real problem was.
I'm happy now that it's working again.
Thanks

**Comment by dscho** [comment]
>  Would be interesting to know what the real problem was.

@Tragen if this is indeed the same issue as #1855, then https://github.com/git-for-windows/MINGW-packages/pull/32 fixes it. And I guess the Nvidia driver just made it less likely that there would be a stray NUL by random chance to terminate that command line.
