### ISSUE TITLE
Unable to update to 2.20.1 (process system closing required)

### ISSUE THREAD

**Issue by the78mole** [git-for-windows/git#2028]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.2.windows.1
cpu: x86_64
built from commit: 26dcaa1b6b5fd862db3ec40983e33ff3432f1166
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.492]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Not related to issue...

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Update Reminder --> Download and install --> Keep settings, only proceeding with "Next"-Button
```
 - What did you expect to occur after running these commands?

It installs the new Version 2.20.1

 - What actually happened instead?

A Install-Wizard step asks to close the PID 4 (system) process, which is not possible (see image attached)
![image](https://user-images.githubusercontent.com/7723396/51237220-47063280-1974-11e9-8aa1-13dacef43903.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

none

**Comment by dscho** [comment]
Does this happen even after a reboot? It is really strange that the System process should hold onto *any* `.dll` files in `C:\Program Files\Git`...

**Comment by dscho** [comment]
You could either manually uninstall Git and then install the newest version, or use a portable Git for now.

**Comment by dscho** [comment]
(Sorry, I cannot think of any better options to diagnose this.)

**Comment by dscho** [comment]
> Hope the "git config --global" will all survive...

That information is stored in your home directory, in the `.gitconfig` file. And yes, the system installation won't touch those (and likewise, neither the uninstallation).

**Comment by dscho** [comment]
I guess a manual uninstall fixed things.
