### ISSUE TITLE
error: Use of uninitialized value $hash in chomp

### ISSUE THREAD

**Issue by fgc0109** [git-for-windows/git#2029]
- [√] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [版本 10.0.17134.523]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git svn clone
```
 - What did you expect to occur after running these commands?

a complete git repository

 - What actually happened instead?

```
fatal: Cannot open '.git/Git_svn_delta_20956_0_5Pu9eq': Invalid argument  
Use of uninitialized value $hash in chomp at C:/Program Files/Git/mingw64/share/ perl5/Git.pm line 929,  line 1369.                                         
hash-object -w --stdin-paths --no-filters: command returned error: 128                                                                                            
error closing pipe: Bad file descriptor at C:/Program Files/Git/mingw64/libexec/ git-core\git-svn line 0.                                                         
error closing pipe: Bad file descriptor at C:/Program Files/Git/mingw64/libexec/ git-core\git-svn line 0.                                                                 
(in cleanup) ▒3▒▒▒/▒ at /usr/share/perl5/vendor_perl/Error.pm line 198 d uring global destruction.
```
it happened every time at same place (about r521) 
i try only clone the newest version (r1321) it still happen

r521 seems add some folder or file
in new version i can't find them , they may be delete them or rename them
![qq 20190117142802](https://user-images.githubusercontent.com/13477904/51299756-76946800-1a64-11e9-9605-219e5ed8af5d.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

sorry,it's not a public repository
but there is a same question here
[error: Use of uninitialized value $hash in chomp](https://www.spinics.net/lists/git/msg349585.html)

**Comment by dscho** [comment]
> sorry,it's not a public repository

Sorry, then there is little I can do. You could try to recreate a real MCVE (`git svn clone` does not even work, let alone reproduce the issue you described).

This bug is *very* likely to be data shape dependent.

**Comment by dscho** [comment]
Since there is not enough information to act on, the only thing I can do is close this unresolved.
