### ISSUE TITLE
Git Bash: prioritize cygwin binaries in PATH

### ISSUE THREAD

**Issue by mcandre** [git-for-windows/git#2030]
Git Bash should always order the cygwin binaries earlier than Windows binaries, as far as bash scripts see the PATH, so that common script utilities like `find` and `mkdir` don’t expand to the wrong binaries and break syntax. Out of the box, bash.exe is limited to running generic shell code and only binaries that do not conflict with Windows binaries.

Outside of bash script contexts, it is still good to allow users to choose whether and what order Git Bash ends up on PATH. But within a bash.exe context, we should probably do the right thing so that 90% of bash scripts can continue running UNIX-like external apps.

**Comment by dscho** [comment]
Thank you for your report. However, there are unfortunately serious problems with it.

First of all: this is an incomplete bug report. It not only lacks the information which Git for Windows version you use, it also lacks an [MCVE](https://stackoverflow.com/help/mcve).

Second: we do not ship with Cygwin. Never have, never will.

Do you mean MSYS2? If so, the MSYS2 binaries' directory is prepended to the `PATH` by *Git Bash*. Meaning: it already does what you claim it doesn't.

**Comment by PhilipOakley** [comment]
Supplemental to dscho's note:

Do you mean that you do have Cygwin installed, and that the Git for Windows fails to notice, and your installation's path becomes out of sync with what you need? 

If so, you could add something to the install script that detects the situation and warns Cygwin users of what they may needs to check and do. But as dscho noted, it's not something that Git for Windows can fix directly.

PRs and clarifications welcome

**Comment by rimrul** [comment]
Since @mcandre  mentions `bash.exe` and seems to use it interchangeably with `Git Bash` I think he's calling `/bin/bash.exe` without using the `git-bash.exe` wrapper.

**Comment by dscho** [comment]
Well, @mcandre what is it? There are a lot of questions awaiting answers by you.

**Comment by dscho** [comment]
Tired of waiting.
