### ISSUE TITLE
git gui and atom still asks me a ssh passphrase

### ISSUE THREAD

**Issue by devcline** [git-for-windows/git#2031]
I am able to push and pull successfully, but I am prompted for my passphrase every time, even though I put my identity into ssh-agent and in git bash it works without asking a passphrase. How can I stop atom from prompting me for my passphrase every time?

- ` ssh-agent `is running
- i can pull fetch from bash without asking me passhrase (asked only first time)
- a git on my server (not GitHub repository) and as client windows 10
- im my `.ssh` folder there is a `config, id_rsa, id_rsa.pub, agent.env and known_hosts`
- i use `ssh://` url
- `git config --global credential.helper wincred` dosent help cause its for https
 - followed [this guide ](https://help.github.com/articles/working-with-ssh-key-passphrases/)
- **GIT GUI** and **ATOM** Asks me a passphrase, but not bash

the config file
```
Host *
    IgnoreUnknown UseKeychain
    UseKeychain yes
    AddKeysToAgent yes
    IdentityFile ~/.ssh/id_rsa
```

From Git Bash:
```
XXXX@DESKTOP-6A5PT MINGW64 /h/Develop/XXX (master)          
$ git push -u origin master                                                      
stdin: is not a tty                                                              
Everything up-to-date                                                            
Branch 'master' set up to track remote branch 'master' from 'origin'.
--
```

the .bashrc
```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
```

the agent.env
```
SSH_AUTH_SOCK=/tmp/ssh-lG207sSiLY2x/agent.1752; export SSH_AUTH_SOCK;
SSH_AGENT_PID=16064; export SSH_AGENT_PID;
echo Agent pid 16064;
```

Why doesn’t ssh-agent works as it needs to? Im missing something?

![image](https://user-images.githubusercontent.com/617020/51380043-13acda80-1b11-11e9-9a1a-c3f9d4246627.png)

thanks

**Comment by dscho** [comment]
Neither Git GUI nor Atom go through a Bash, so you will have to find a way to set those environment variables in a way that is independent of Bash.

You could, for example, copy `C:\Program Files\Git\cmd\start-ssh-agent.cmd`, change the `set` calls at the bottom to use `setx` instead (i.e. write to the user-wide, or machine-wide environment instead of the environment that is local to the current CMD).
