### ISSUE TITLE
Update git flow to >= 1.12.0

### ISSUE THREAD

**Issue by dazinator** [git-for-windows/git#2038]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 Please consider updating git glow to >= 1.12.0 as there has been some issues fixed that make working with PR's less probelmatic: https://github.com/petervanderdoes/gitflow-avh/pull/330

**Comment by rimrul** [comment]
This should be in upcomming Git for Windows versions due to Alexpux/MSYS2-packages/pull/1555.

**Comment by rimrul** [comment]
This is now in upcomming Git for Windows versions as of [72bd7beced](https://github.com/git-for-windows/MSYS2-packages/commit/72bd7beced7bb6047e11e898469ba520360e025b).
