### ISSUE TITLE
Git Bash does not start at drive root

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#204]
I start Git Bash via Shell Context Menu (Git Bash Here).
If it is a drive root, such as C:\ or D:\,
Git Bash does not show up.

git 2.4.0.windows.1 64-bit

**Comment by dscho** [comment]
> git 2.4.0.windows.1 64-bit

This is not the latest release.

> I start Git Bash via Shell Context Menu (Git Bash Here).
> If it is a drive root, such as C:\ or D:\,
> Git Bash does not show up.

Is this *different* from https://github.com/git-for-windows/git/issues/176?

**Comment by linquize** [comment]
oops, duplicate issue
