### ISSUE TITLE
Could not find docs on how to build git for Windows

### ISSUE THREAD

**Issue by ader1990** [git-for-windows/git#2045]
Hello,

I tried to find any docs on how to build git on Windows, but couldn't find one.
Can someone give me some pointers?

Thanks.

**Comment by dscho** [comment]
https://github.com/git-for-windows/git/wiki/Building-Git

**Comment by ader1990** [comment]
@dscho thank you for the fast response. Can we add this piece of info on the main Readme, to be easy to find for everyone? I will be glad to make a PR for it.

**Comment by dscho** [comment]
Sure, go wild!

**Comment by PhilipOakley** [comment]
@ader1990 Please do, these improvements are always welcome.
