### ISSUE TITLE
Add README info on what is the difference between the various releases?

### ISSUE THREAD

**Issue by E3V3A** [git-for-windows/git#2051]
I'm trying to understand what release best suit my need, but I cannot find any single place that clearly explain the differences between the various releases.

![firefox_2019-02-01_21-46-51](https://user-images.githubusercontent.com/194392/52146024-831ae200-265a-11e9-91ab-a3fe678e317c.png)

In particular between:  

```
Git-XXX-64-bit.exe
PortableGit-XXX
MinGit-XXX
```

* Where are they described?
* What are their difference?

Perhaps a table with features would be helpful...

**Comment by siprbaum** [comment]
If you are interested in the Git release notes, have a look at
https://github.com/git-for-windows/git/tree/master/Documentation/RelNotes

GitForWindows is more than Git alone (e.g. like unix tools, like bash etc) and also has additional
changes on top of plain git.
See https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md for high level details

**Comment by E3V3A** [comment]
The release notes are useless, as I am trying to get a simple overview of the differences between the above packages. (Perhaps my use of the word "release" was not correct.)

**Comment by dscho** [comment]
This would make for a perfect first Pull Request.

My suggestion would be to add a section or paragraph to the [`ReleaseNotes.md`](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md) file describing that Git for Windows offers 64-bit and 32-bit versions of

- Git for Windows (regular installer, recommended),
- Portable Git (recommended if installation is not an option),
- MinGit (recommended only for use by 3rd-party applications, not for interactive use),
- BusyBox-backed MinGit (experimental, smaller version of MinGit),
- Git as a `.tar.bz2` archive (probably useful only to a couple dozen persons on this planet), and
- `.pdb` files for use with crash dump analyzers and debuggers

Furthermore, there are NuGet package versions of the Portable Git and MinGit.

This paragraph should then be included when [building the release descriptions](https://github.com/git-for-windows/build-extra/blob/86573d6efd92e271ee98255ebc34ffe1aedf4669/please.sh#L4134-L4136).

**Comment by dscho** [comment]
@E3V3A so... how's your progress?

**Comment by BSGILL012** [comment]
Great ji
