### ISSUE TITLE
Error: fatal: bad revision '^'

### ISSUE THREAD

**Issue by aenagy** [git-for-windows/git#2054]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.19.0.windows.1
cpu: x86_64
built from commit: d96bb8bc6c636a8869140e860e72e7bdf64bd790
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.904]
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

P:\>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using enterprise instance of BitBucket, using Active Directory credentials for access.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

GUI

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
After experiencing problems with my local repository (Verify Database indicated multiple errors), rather than trying to fix the problem I deleted the entire local repository including all hidden files and folders. I then re-added the remote (BitBucket) repository which worked fine but when I tried to do a local merge the following error popped up:

Title: Application Error:
Body:
Error: fatal: bad revision '^'
[OK]  [Skip Messages]  [Details> >]

Details:
fatal: bad revision '^'
fatal: bad revision '^'
    while executing
"close $fr_fd"
    (procedure "_new" line 114)
    invoked from within
"_new $path 1 $title"
    (procedure "::choose_rev::new_unmerged" line 2)
    invoked from within
"::choose_rev::new_unmerged $w.rev [mc "Revision To Merge"]"
    (procedure "merge::dialog" line 30)
    invoked from within
"merge::dialog"
    (menu invoke)



```
 - What did you expect to occur after running these commands?

The local repository should have been populated with files from the remote repository.

 - What actually happened instead?

See description.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

URL is internal to my environment.

**Comment by dscho** [comment]
> After experiencing problems with my local repository (Verify Database indicated multiple errors), rather than trying to fix the problem I deleted the entire local repository including all hidden files and folders. I then re-added the remote (BitBucket) repository which worked fine [...]

That sounds like your local repository was only half destroyed. Because if it was fully destroyed you would not be able to add a remote.

> URL is internal to my environment.

Once you make it easier to verify that there is a bug in Git, I will have another look.

**Comment by aenagy** [comment]
> That sounds like your local repository was only half destroyed. Because if it was fully destroyed you would not be able to add a remote.

How do I reset the local repository so that I can re-add the remote repository?

> Once you make it easier to verify that there is a bug in Git, I will have another look.

What do you recommend for this?

**Comment by dscho** [comment]
> How do I reset the local repository so that I can re-add the remote repository?

I would delete and re-clone the entire thing, if I were you.

**Comment by dscho** [comment]
I guess that fixed it.
