### ISSUE TITLE
Problem installing PortableGit-2.20.1-64-bit

### ISSUE THREAD

**Issue by ptatian** [git-for-windows/git#2055]
I use the portable version of Git on my Windows 7 desktop. I just tried to install the latest update using the `PortableGit-2.20.1-64-bit.7z.exe` installer. After running the installer, all of the files seem to have been unpacked properly, but when I tried to use the program I got an error message saying that it could not find the path. 

```
error launching git: The system cannot find the path specified.
```

I run the Git program in a DOS window where I have added the PortableGit\cmd folder to the Windows PATH. This has worked fine in the past but it seems not for the new version. After trying several times to get it to work, I deleted the new version and reinstalled the older one I was using before (`PortableGit-2.19.1-64-bit.7z.exe`). The reinstalled v2.19.1 works fine, as it did in the past. 

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

**I am currently running version 2.19.1, but my problem is with trying to install v2.20.1.**

```
$ git --version --build-options

git version 2.19.1.windows.1
cpu: x86_64
built from commit: 11a3092e18f2201acd53e45aaa006f1601b6c02a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Using the portable version
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

DOS command prompt

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git --version
```
 - What did you expect to occur after running these commands?

Expected git to return a message with the current version number.

 - What actually happened instead?

Got an error message
```
error launching git: The system cannot find the path specified.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
This sounds very similar to at least one of the bugs I fixed recently. Would you please test the newest snapshot at https://wingit.blob.core.windows.net/files/index.html?

**Comment by ptatian** [comment]
Hi @dscho. I tested **PortableGit-prerelease-2.20.1.windows.1.27.g9f16cdd421-64-bit.7z.exe**. It seems to work fine after I installed. 

```
>git --version
git version 2.20.1.windows.1.27.g9f16cdd421
```

**Comment by dscho** [comment]
Excellent. This will therefore be fixed in the next release, so we can close this.
