### ISSUE TITLE
Unable to Clone a Repository in Bit Bucket

### ISSUE THREAD

**Issue by r-damu** [git-for-windows/git#2057]
I am unable to clone a repository in bit bucket using the below command.
 git clone https://r-damu@bitbucket.org/r-damu/repository_personal-copy.git

I am using Git-2.19.1-64-bit.  

Below is the response received.
error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503 Service Unavailable.

This is running on Windows 7 Professional, 64 Bit.  I was running the command from Git Bash.

**Comment by dscho** [comment]
> I am using Git-2.19.1-64-bit.

Please try with the current version, or even with the latest snapshot at https://wingit.blob.core.windows.net/files/index.html

**Comment by r-damu** [comment]
I tried with the current version 2.20.1.1.  However I am getting the same error message.
error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503 Service Unavailable.

**Comment by stahta01** [comment]
I had a similar issue and used an older version of Git Credential Manager to fix it.

**Comment by dscho** [comment]
@r-damu does downgrading Git Credential Manager to version v1.14.0 work around the issue for you, too?

**Comment by r-damu** [comment]
Thank you! The issue has been resolved for me too.
