### ISSUE TITLE
Support selecting text in git

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#206]
Hi please re add support for selecting text because now you have to use the arrow keys to go to selected text you either want to delete or add something. In git 1.9.5 selecting text with mouse was supported. You could select where to start writing. please re add it.

**Comment by dscho** [comment]
You can always select text with the mouse. That behaviour has not changed at all.

**Comment by paladox** [comment]
Hi it doesent work when I try to select to where I want to start for example

exexex exeex <what to click here to start new work> exedx

It dosent work I have to use the keybord to get there.

**Comment by dscho** [comment]
Please describe the problem precisely. I cannot reproduce what was described, when I call Git Bash I can easily select text, copying it into the clipboard.

**Comment by paladox** [comment]
When I try to click in somewhere in text to add a little bit more or remove a bit I carnt use mouse since the little key that shows when you are and where you writing shows it as where it was last located it doesent move. if you try for eample write a few examples in the commit for example git commit -a --amend then try click anywhere in the text to try and insert some more text without using keybord you carnt because it seems it wont move when the mouse clicks but moves when you clik the arrow keys on keybord.

**Comment by dscho** [comment]
Ah, I think I understand. You want to move the cursor by clicking with the mouse.

This is not possible if you use the MinTTY terminal, I think, but you can easily choose the ConHost terminal when installing Git to have Git Bash start in the same manner as Git for Windows 1.x' Git Bash.

**Comment by paladox** [comment]
Oh ok why did It change to MinTTY in git v2 because what ever one was in git v1 was better.

**Comment by nalla** [comment]
It sounds as if you need to change the editor to e.g. notepad++. I think @paladox is speaking about editing the commit message.

**Comment by paladox** [comment]
Yes. but I also think this happens when you type a script like git add or something else.

**Comment by nalla** [comment]
try setting
```
git config --global core.editor "C:\\Path\\To\\Notepad++\\"
```

**Comment by paladox** [comment]
Comes up with error ( my path to it is program x86 but says error with (

**Comment by paladox** [comment]
What is the default editor in git version 1.9.5. Since the one in v2 isent as good as v1.
