### ISSUE TITLE
git-lfs.exe missing after installation

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#2062]
I have installed the latest version of Git (2.20.1) on Windows on 2 different machines and neither of them have `git-lfs.exe` installed anywhere under the git installation directory. This is weird, because existing issues seem to indicate that Git LFS should be bundled with the Git for Windows installer. If I'm wrong about this, and Git LFS must be installed separately, please close this issue. If there's documentation I'm missing, please let me know (Already checked the repo's Wiki and didn't see anything). I also checked for any optional check boxes in the installer and didn't notice any. Is this a bug? Why did `git-lfs.exe` not get installed?

**Comment by dscho** [comment]
Did you check the "Git LFS (Large File Support)" checkbox on the first (IIRC) wizard page? If not, your bug is not a bug.

**Comment by rcdailey** [comment]
You're right, I missed the checkbox. I was looking in the wizard pages later on and didn't see it there. Closing this issue.
