### ISSUE TITLE
Cannot push to repository through ssh

### ISSUE THREAD

**Issue by classicalguss** [git-for-windows/git#2063]
I'm not able to push to my repository using ssh and getting the following error

$ git push
FATAL ERROR: Couldn't agree a key exchange algorithm (available: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521)
fatal: Could not read from remote repository.

### Setup

Using git-bash in Windows, I followed exactly the setup here
(https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)
And then added my ssh key by following these instructions
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

And yet I am getting the error mentioned above
```
$ git --version --build-options
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```
```
cmd.exe ver
Microsoft Windows [Version 10.0.17134.523]
```
```
$ cat /etc/install-options.txt
Path Option: Cmd
Plink Path: C:\Program Files (x86)\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

**Comment by PhilipOakley** [comment]
Is this using the GitHub application or the Git-for-Windows application. 

Maybe have a go at completing the information template so we can see what version and OS type you are on.

**Comment by classicalguss** [comment]
@PhilipOakley Yes it is. When you install it you get the following 
Git Bash
Git CMD
Git GUI

I'm running Git Bash

**Comment by PhilipOakley** [comment]
Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

What does `git --version --build-options` say?

and `cmd.exe /c ver` and

(one of)
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt


Have you managed to pull and push with the other transport type (smart HTTP or git://) ?

Can you confirm where the remote is located - what path are you using..

All that said, ssh stuff can be tricky (it's not something I normally use, and if/when I do its already working so I don't notice...), and the message indicates that you may still be trying to use an old security standard, hence can't find an acceptable newer one.

**Comment by classicalguss** [comment]
@PhilipOakley Thank you for your reply. Here are the outputs that you requested
```
$ git --version --build-options
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64
```
```
cmd.exe ver
Microsoft Windows [Version 10.0.17134.523]
```
```
$ cat /etc/install-options.txt
Path Option: Cmd
Plink Path: C:\Program Files (x86)\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

I'm not able to push using HTTPs (despite being able to do so before, however I did add 2fa recently)
```
$ git push
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': classicalguss
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/classicalguss/carbnbnew.git/'
```

I verified that the credentials are correct by signing out and signing in on github.

**Comment by classicalguss** [comment]
@PhilipOakley 
I was able to pull and push through https when I followed this guide for 2fa
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

**Comment by PhilipOakley** [comment]
hi, your version 2.13.0.windows.1 is a bit old now and there have been security fixes since then, so first please could you at least update to the latest release. https://github.com/git-for-windows/git/releases/

Also, do check the wiki for extra details about the setting up of the ssh methods on the Git for Windows fork https://github.com/git-for-windows/git/wiki/FAQ

**Comment by classicalguss** [comment]
Upgrading was important, but it still didn't make it work. But after following some of the stuff in this link
https://gist.github.com/bsara/5c4d90db3016814a3d2fe38d314f9c23
It finally worked!
