### ISSUE TITLE
Typo in git command caused unexpected output

### ISSUE THREAD

**Issue by DJ-DJL** [git-for-windows/git#2069]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Not sure, how do I find out? git bash is in `Program Files`, rather than `Program Files(x86)`

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 64bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

C:\Users\localuser>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

not that I can think of at the moment.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

gitbash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git mergebb/ WIP-Strategy-NCNR-Engine2-fix4
```
 - What did you expect to occur after running these commands?

git: 'mergebb/ is not a git command. See 'git --help'.

 - What actually happened instead?

$ git mergebb/ WIP-Strategy-NCNR-Engine2-fix4
warning: failed to restrict file handles (2)

handle #0: 0000000000000264 (type 3, handle info (1) 7fe
handle #1: 0000000000000268 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'mergebb/' is not a git command. See 'git --help'.

I haven't tested this with any other repositories, but from the nature of the issue I do not believe the repository to be relevant.
The same happens if I change the name of the remote to 'blah', but if I remove the trailing '/' I get the correct response:

$git mergeblah WIP-Strategy-NCNR-Engine2-fix4
git: 'mergeblah' is not a git command. See 'git --help'.

This command was a typo on my part - I meant to put `git merge bb/WIP-Strategy-NCNR-Engine2-fix4` (bb is the name of the remote)
So I know how to workaround this issue, I just didn't expect the response given!

**Comment by PhilipOakley** [comment]
The error message is indicative of a bug that was fixed between your 
version and the current version, and has been triggered, in this case by 
the miss-splet command name.

The fix is to update to the latest release version.
