### ISSUE TITLE
Can Git bash save command history when window closed?

### ISSUE THREAD

**Issue by dougbreaux** [git-for-windows/git#2073]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.292]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

N/A

 - What did you expect to occur after running these commands?

Bash command history saved immediately, regardless of how the shell is closed.

 - What actually happened instead?

Bash command history is only saved on a graceful exit. Not on window close, which means not when Windows updates cause a reboot.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by landstander668** [comment]
This is actually normal unix/linux behaviour, which MSYS2 is faithfully emulating on Windows. The typical workaround I've seen is to add `export PROMPT_COMMAND='history -a'` to your bash initialization file(s). It looks like Git Bash launches BASH as a logon shell, so *~/.bash_profile* is most likely where you want to do this.

This causes the `history -a` command to be run every time the shell prompt is displayed, which flushes pending updates to the file.

**Comment by dougbreaux** [comment]
Ok. Seems weird and inefficient, but if that's all I'm going to get ... :-)

**Comment by shiraze** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/151105?

**Comment by Amnesiac9** [comment]
This is non-intuitive behavior to have within vscode even if it is emulating something on linux.
