### ISSUE TITLE
it said I shoudl report.. (?)

### ISSUE THREAD

**Issue by ElyBob** [git-for-windows/git#2076]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using?   64-bit 

```
$ git --version --build-options

$ git --version --build-options
git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.785]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

--none

### Details

 - Which terminal/shell are you running Git from?  git-Bash

** insert your response here **

$ git checkoutllouisiana/AS-163834835-Remove-testing-kludge
warning: failed to restrict file handles (2)

handle #0: 0000000000000410 (type 3, handle info (1) 7ff9
handle #1: 0000000000000414 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'checkoutllouisiana/AS-163834835-Remove-testing-kludge' is not a git command. See 'git --help'.

```
** insert your commands here **
```
I botched a checkout

** insert here **

 - What actually happened instead?

$ git checkoutllouisiana/AS-163834835-Remove-testing-kludge
warning: failed to restrict file handles (2)

handle #0: 0000000000000410 (type 3, handle info (1) 7ff9
handle #1: 0000000000000414 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'checkoutllouisiana/AS-163834835-Remove-testing-kludge' is not a git command. See 'git --help'.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I cannot..

**Comment by PhilipOakley** [comment]
Hi @ElyBob (Larry),

Thank you for taking the time to report the bug. Yes, we did have a bit of failing code in that version of Git-for-Windows. The original problem has been located and fixed in the more recent releases.

The latest releases are at https://github.com/git-for-windows/git/releases/ (the link is on the footer bar of that home page..). There will be a further new minor release in the next couple of weeks as the upstream Git is going through the release candidate process for V2.21.0 at the moment.

So it's time to upgrade, plus it includes some security improvements. Hope that helps.
