### ISSUE TITLE
Error When Attempting the Add command (Apparent bug)

### ISSUE THREAD

**Issue by jgodinez1114** [git-for-windows/git#2079]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```


git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 10
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

This is a school(public) machine
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Public environment.

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MINGW64
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I attempted to run an add command for a working Word document ```
 - What did you expect to occur after running these commands?

I am new to Git, and expected to add this document to a new repo.
 - What actually happened instead?

I encountered an error message and apparent bug.
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It is local.

Message:
$ git /m/home/Desktop/SENG/
warning: failed to restrict file handles (2)

handle #0: 0000000000000408 (type 3, handle info (1) 7ffe
handle #1: 000000000000040c (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

**Comment by PhilipOakley** [comment]
Hi @jgodinez1114, Thank you for the report. The problem is a compatibility bug in that older version of the code, which has now been fixed.

The right thing to do is to get the latest release of  Git for Windows from the release page (link at the footer of the https://gitforwindows.org/ page) https://github.com/git-for-windows/git/releases/

There is expected to be a new release in a week or so, as the upstream Git is releasing the latest and greatest soon.

I'll close the ticket as it is a know/fixed bug, though you can reply.
