### ISSUE TITLE
SourceTree and Tortoise Git do not detect an installed git for windows.

### ISSUE THREAD

**Issue by swalter** [git-for-windows/git#208]
Yesterday I've installed the RC2 of the current release to test this on my private development environment before I use it at work.
After installing the 64bit version I entered the tortoise git settings to see, witch version gets detected here. I got a dialog here mentioned that it was tortoise was not able to detect the correct version string.
The label showing the version installed however showed version 2.4.3.1.
Ignoring this fact I started SourceTree. Short time after that the dialog to choose a versioning tool popped up.
So it seems there is a problem right now to detect the installed version of your tool. Maybe this problem does not exist using the 32bit version that was not tested by me.

**Comment by nalla** [comment]
See https://github.com/git-for-windows/git/issues/152. This is due to the fact that the `/bin` directory dropped. There is a workaround described in https://jira.atlassian.com/browse/SRCTREEWIN-3226

**Comment by dscho** [comment]
I have an idea. We could re-add the `/bin/` directory and put copies of the Git wrapper there, `git.exe`, `git-receive-pack.exe` and `git-upload-pack.exe`. We could also copy an appropriately edited `git-cmd.exe` as `bash.exe` there so that the same command-lines work as before.

@nalla what do you think?

**Comment by nalla** [comment]
@dscho I think its a sound plan. Because its just the git-wrapper it would be a minimal size impact. Best let the `inno setup` script handle that.

**Comment by dscho** [comment]
> Best let the inno setup script handle that.

I'd actually also like the Portable Git users to benefit (remember, a variation of Portable Git is available with GitHub for Windows, and GitHub essentially sponsored all of the Git for Windows 2.x push).

**Comment by nalla** [comment]
If I remember correctly _SourceTree_ also uses an internal portable release that will eventually be pushed to _Git for Windows 2.x_. So that indeed makes sense.

**Comment by shiftkey** [comment]
> I'd actually also like the Portable Git users to benefit 

Given the downstream users control which version of PortableGit they're using, any extra hoops to jump through aren't really worth it. Adapting to the new structure isn't that hard, but if environments have to support 1.9.x and 2.x at the same time perhaps the workaround is necessary.

**Comment by dscho** [comment]
I implemented this and published it as part of [the 3rd release candidate](https://github.com/git-for-windows/git/releases/tag/v2.4.4.windows.2).

Please test, everybody!

**Comment by nogaff** [comment]
Seems to work fine for me with the current SourceTree release except that SourceTree's "Terminal" button tries to open a command prompt via /bin/sh.exe which obviously fails.

I got it to work properly by creating a symlink /bin/sh.exe -> /bin/bash.exe. Perhaps an sh.exe redirector needs to be put in /bin as well?

**Comment by dscho** [comment]
@nogaff please note that [this commit](https://github.com/git-for-windows/build-extra/commit/2e0d868321c58ade5f1b92ba0a679f17385e1c98) should fix the issue (not by symlinking because that does not work in general, but simply by copying; it's just 29kB, so I think that's fine).

**Comment by JoshSchreuder** [comment]
FYI - Sourcetree's current beta worked around this issue (https://www.sourcetreeapp.com/update/WindowsReleaseNotes_public_beta.html):
```
SRCTREEDEV-108 Support v2.x, 32-bit or 64-bit of Git for Windows as a System Git. NB. requires use of putty/pageant rather than ssh-agent.exe unless running as administrator.
```

**Comment by dscho** [comment]
@JoshSchreuder thanks for the update!
