### ISSUE TITLE
How to get gitweb

### ISSUE THREAD

**Issue by Hk1020** [git-for-windows/git#2080]
How to I get gitweb? It is not shipped anymore but I need it and it working.

**Comment by dscho** [comment]
GitWeb is not supported by Git for Windows.

If you want to use it nevertheless, you take up the responsibility to fix your own issues, and you can do so by using the Git for Windows SDK.

**Comment by Hk1020** [comment]
So then what is a supported way these days to get a git server on Windows? Which means push/pull over http and a graphical web frontend like gitweb.

**Comment by PhilipOakley** [comment]
At my previous work they started using https://gogs.io/ (it was an old big iron style company ;-)
" Gogs
A painless self-hosted Git service."

e.g. https://gogs.io/docs/installation/run_as_windows_service
YMMV
