### ISSUE TITLE
Shortcuts doesn't work in GUI with non-English keyboard layout

### ISSUE THREAD

**Issue by redmanmale** [git-for-windows/git#2082]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17134.523]
```
x64

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git GUI

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Open Git GUI in repo with some edited files.
Select one of them in `Unstaged Changes` panel and press CTRL-T.

I could provide screenplay (gif) if it's necessary.

 - What did you expect to occur after running these commands?

Stage selected file.

 - What actually happened instead?

Nothing.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Any repo.

This behavior only occurs with non-English keyboard layout.
If I switch my keyboard to English (in language settings) everything works just right.

**Comment by dscho** [comment]
Okay, this will require a bit of effort on your side just to investigate, as I cannot reproduce the problem here (I tried with a German keyboard and your reported problem does *not* occur here).

So save this Tcl script under any file name, and run `wish <filename>`:

```tcl
set keysym "Press any key...          "
pack [label .l -textvariable keysym -padx 2m -pady 1m]

# Bind an action to any key
bind . <Key> {
    set keysym "You pressed another key (%K)"
}

# Bind an action to Ctrl+T
bind . <Control-Key-t> {
    set keysym "YEP! You pressed Ctrl+%K"
}
```

I assume you understand what this does, as it is relatively easy to understand.

Then try to hit Ctrl+T and see whether it shows the second message rather than the first. If it does not, you will have to dig in from there, to find out what code path it takes instead.

Good luck!

**Comment by redmanmale** [comment]
English keyboard: YEP! You pressed Ctrl+T.
Russian keyboard:
![image](https://user-images.githubusercontent.com/6782721/53402954-cb13f700-39c3-11e9-82d5-821d69620106.png)

**Comment by dscho** [comment]
@redmanmale okay, so there you have the problem, and I wish you good luck finding out more about the issue. This is your investigation to drive.

**Comment by dscho** [comment]
@redmanmale you might be interested in looking here: https://core.tcl.tk/tk/tktview/62f1343ad2fd9c77d1f3
