### ISSUE TITLE
Missing text when using node

### ISSUE THREAD

**Issue by EthanRutherford** [git-for-windows/git#2084]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.253]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I don't think so.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
node
> what [enter]
```
 - What did you expect to occur after running these commands?

to see the text I'm typing, or output from running a program with node

 - What actually happened instead?

![image](https://user-images.githubusercontent.com/5589147/53278688-90f2de80-36bf-11e9-9910-b3557b409259.png)

I'm not sure what's causing this issue, but for some reason running node's interactive terminal, or executing a js file using `node foo.js`, the output is wonky and generally unusable, with a lot of extra, empty space printed out, and most of the expected output missing.

Side note: the problem does not reproduce in the windows command prompt, only in git bash.

**Comment by dscho** [comment]
The reason is that `node.exe` (BTW you forgot to specify which one you use, in the "other interesting settings" section) expects a Windows Console, but MinTTY does not offer one.

To work around this, we install a Bash alias for `node` that runs `node.exe` through `winpty`, which opens a hidden Windows Console, polls it for changes and mirrors them into MinTTY's pseudo terminal.

You might want to run Git for Windows' installer again and choose the Windows Terminal option instead of MinTTY for Git Bash.
