### ISSUE TITLE
How to rebuild .\bin\bash.exe (that is a renamed compat-bash.exe) with different relative path?

### ISSUE THREAD

**Issue by kiwi0fruit** [git-for-windows/git#2089]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

How to rebuild .\bin\bash.exe (that is a renamed compat-bash.exe) with different relative path? I guess I coud figure this out but I cannot find it's source code. Do you where it is?

**Comment by dscho** [comment]
This is not a bug report. In the future, please direct your regular questions about Git for Windows to git-for-windows@googlegroups.com.

The `compat-bash.exe` is built as part of the [`mingw-w64-git`](https://github.com/git-for-windows/MINGW-packages/tree/master/mingw-w64-git) package from the [`git-wrapper.c`](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/git-wrapper.c) file.

The easiest way to rebuild, therefore, is to

1. Install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk)
2. `sdk cd MINGW-packages`
3. `cd mingw-w64-git`
4. `MINGW_INSTALLS=mingw64 makepkg-mingw -s`

If you want to fiddle with the source code, after that you will want to

1. `cd src/git`
2. fiddle with `../git-wrapper.c`
3. `make -f ../mingw-w64-git.mak compat-bash.exe`

If you make changes that are useful, you will want to copy that `../git-wrapper.c` to `../../git-wrapper.c` and then commit that file (after `cd ../..`), push and open a Pull Request.

**Comment by kiwi0fruit** [comment]
Thanks a lot and sorry for posting I the wrong place!

>

**Comment by dscho** [comment]
@kiwi0fruit you're welcome, and sorry for coming over that grumpy. It's just a lot of work to keep the bug tracker remotely healthy already with the bug reports. Maybe you could help?

**Comment by kiwi0fruit** [comment]
@dscho I'm sorry but my open source activity is already fully occupied with some [never ending project](https://github.com/kiwi0fruit/pandoctools/issues/28)...
