### ISSUE TITLE
git-remote-https continously eating memory (> 3gb)

### ISSUE THREAD

**Issue by IceMan81** [git-for-windows/git#209]
I've the latest RC installed (2.4.3.windows.1). Git is configured to use a proxy server as I need to use a proxy on my work machine. I'm trying to do a remote fetch against a bit bucket repository using Git GUI but it does not work.
It prompts me for the bitbucket password but after that it seems to be indefinitely fetching and git-remote-https is eating up a lot of memory and continues to do so until I force kill the process.

Local operations with git works fine but I cannot do any remote operations.
Let me know if you need more information. 

![git-remote-https](https://cloud.githubusercontent.com/assets/1093778/8256213/3a02c8bc-165a-11e5-8957-d27318442cd0.png)
. 
![git gui _ fetch origin](https://cloud.githubusercontent.com/assets/1093778/8256217/4ff79ea4-165a-11e5-8a6e-19ec17689d97.png)

**Comment by dscho** [comment]
The next step is to try the same operation via the command line, i.e. start the Git Bash, change to the directory in question and call `git fetch origin`.

**Comment by IceMan81** [comment]
I expected the behavior to be same which is why I didn't explicitly try it. As I expected, its doing exactly that. I get an Open Ssh pop up, prompting for the repo password and then it just waits. git-remote-https just keeps growing in size.

![git-remote-https](https://cloud.githubusercontent.com/assets/1093778/8259987/a8b9d032-1675-11e5-8af7-8dc7a19d4486.png)
![git_cmd](https://cloud.githubusercontent.com/assets/1093778/8259988/a9d0a900-1675-11e5-90fc-2f317e82c5cc.png)

**Comment by dscho** [comment]
Next step: launch `GIT_CURL_VERBOSE=1 GIT_TRACE=1 git fetch origin`

**Comment by IceMan81** [comment]
It looks like it might be a problem only with bitbucket.org. I tried against github and it works fine. This is the error I see when running the command mentioned above.
```
* Proxy replied OK to CONNECT request
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* NPN, negotiated HTTP1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: businessCategory=Private Organization; jurisdictionC=US; juris
dictionST=Delaware; serialNumber=3928449; street=1098 Harrison Street; postalCod
e=94103; C=US; ST=CA; L=San Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbu
cket.org
*        start date: 2014-03-05 00:00:00 GMT
*        expire date: 2016-05-25 12:00:00 GMT
*        subjectAltName: bitbucket.org matched
*        issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Ext
ended Validation Server CA
*        SSL certificate verify ok.
> GET /IceMan81/uploads.git/info/refs?service=git-upload-pack HTTP/1.1
Host: bitbucket.org
User-Agent: git/2.4.3.windows.1
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-US, *;q=0.9
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Server: nginx/1.6.2
< Date: Fri, 19 Jun 2015 20:31:11 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< WWW-Authenticate: Basic realm="Bitbucket.org HTTP"
< X-Usage-User-Time: 0.004995
< X-Usage-System-Time: 0.001087
< X-Usage-Input-Ops: 0
< X-Usage-Output-Ops: 0
< X-View-Name: bitbucket.gitweb.application
<
```
Works fine with msysgit-1.9.5.

The only difference between using github & bitbucket I see is for bitbucket, I get an OpenSSH prompt for the repo password and after than it looks like the auth fails.

**Comment by dscho** [comment]
How good is your gdb fu?

**Comment by IceMan81** [comment]
Its been quite a while... What do you want me to try?

**Comment by dscho** [comment]
> What do you want me to try?

I want you to debug it ;-)

Seriously speaking again, this is what I would do:

1. recompile Git after editing out the `-O2` flag from the `Makefile` (because it messes up single-stepping in `gdb`)
2. call `make install`
3. start such a memory-eating fetch
4. figure out via `ps -W` what the process ID ("pid") of the `git-remote-https.exe` is
5. start `gdb git-remote-https.exe`
6. attach to the running process with `attach <pid>`
7. interrupt the process using Ctrl+C
8. look at the stack trace using `bt`
9. figure out what the heck is going on :smiley_cat:

**Comment by drizzd** [comment]
Does this work for you?
git clone https://bitbucket.org/achernet/git-cola.git

Works for me with the following versions:
git version 2.3.5.windows.8.7.gca15bb6
git version 2.4.5.windows.1.8.g658589f

**Comment by dscho** [comment]
Let's reopen this ticket when (or if) there is active enough a conversation to allow for a resolution.
