### ISSUE TITLE
Git Unable to create .lock file on WINDOWS,Because branch name contains '>'

### ISSUE THREAD

**Issue by LongQingRox** [git-for-windows/git#2094]
Branch api>18 wasn't deleted
cannot lock ref 'refs/heads/api>18': Unable to create 'C:/Users/Roxas/Documents/StudioProjects/ProjectName/.git/refs/heads/api>18.lock': Invalid argument
Error deleting branch 'api>18'
I can't rename or delete this branch, please help.

**Comment by dscho** [comment]
Branch names must be valid file names for the moment (and `>` is not a valid file name on Windows).

**Comment by LongQingRox** [comment]
This is my case.I create this branch in Android Studio on Mac。Then I copy project dictionary to Windows。


![image](https://user-images.githubusercontent.com/39762466/53396992-df1a2180-39e0-11e9-9662-e34ecf0935f3.png)

What can I do with this branch,please help.

**Comment by dscho** [comment]
> What can I do with this branch

You can always check it out under a different name: `git checkout -b api-greater-than-18 "origin/api>18"`

But really, this is the wrong forum to ask questions how to use Git. This is a bug tracker 😄
