### ISSUE TITLE
Typo in Documentation/gitattributes.txt

### ISSUE THREAD

**Issue by rysavyjan** [git-for-windows/git#2095]
There is typo in https://github.com/git-for-windows/git/blob/master/Documentation/gitattributes.txt#L349
Instead of `UTF-16-LE-BOM` there should be `UTF-16LE-BOM`.

This typo is also published on https://git-scm.com/docs/gitattributes

**Comment by dscho** [comment]
@rysavyjan this sounds like a fantastic opportunity for you to get your first patch contribution:

1. Install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk)
2. `sdk cd git`
3. `cd Documentation`
4. edit `gitattributes.txt`
5. test, by `make gitattributes.html && start gitattributes.html`
6. commit, push to your fork, and open a Pull Request.
