### ISSUE TITLE
Directory symlinks with trailing slash always show as modified

### ISSUE THREAD

**Issue by chrisrichard** [git-for-windows/git#210]
Possible to create directory symlinks with or without the trailing slash and they often get created with trailing slashes because tab completion includes it. On Windows, git always reports the link without the trailing slash resulting in these links always showing as modified.

I've created a simple repository demonstrating the problem: https://github.com/chrisrichard/git-windows-symlinks-test

Just clone to reproduce. Note that you have to enable symlinks with core.symlinks = true and run git shell as administrator to ensure links are created on Windows.

```
git clone git@github.com:chrisrichard/git-windows-symlinks-test.git
...

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   dir2
...

$ git diff
diff --git a/dir2 b/dir2
index 9cd0393..9011721 120000
--- a/dir2
+++ b/dir2
@@ -1 +1 @@
-dir/dir2/
+dir/dir2

**Comment by dscho** [comment]
I can reproduce the error with

```cmd
git clone -c core.symlinks=true https://github.com/chrisrichard/git-windows-symlinks-test
```

**Comment by dscho** [comment]
@chrisrichard could you please verify that it works for you, too, with Git for Windows 2.4.4.2 (which I published today)?
