### ISSUE TITLE
Git failed due to "error LNK2001: unresolved external symbol win32_skip_dos_drive_prefix" when build on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [git-for-windows/git#2100]
**Setup:**
* Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
  64-bit
  $ git --version --build-options
  git version 2.9.2.windows.1
  sizeof-long: 4
* Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
  Windows Server 2016 64-bit + VS2017.2
  $ cmd.exe /c ver
  Microsoft Windows [Version 10.0.14393]

**Description:**
Git failed when build by msvc on Windows, the first time we got the error was on 1db5a65, and the last clean build was on 182d923. Could you please help look at this?

**Repro steps:**

1. git.exe clone -b vs/master https://github.com/git-for-windows/git D:\Git\src && cd D:\Git\src
2. git.exe checkout 1db5a65
3. devenv /upgrade git.sln
4. nuget.exe restore git.sln
5. msbuild /m /p:Configuration=Release;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.17134.0 /t:Rebuild git.sln

**Error info:**
libgit.lib(msvc.obj) : error LNK2001: unresolved external symbol win32_skip_dos_drive_prefix
.\git-sh-i18n--envsubst.exe : fatal error LNK1120: 1 unresolved

**Build log:**
[log_x64_build.log](https://github.com/git-for-windows/git/files/2913813/log_x64_build.log)

**Comment by dscho** [comment]
Indeed. This is fixed in the `shears/` branches, but I have not ported the fix yet.

**Comment by dscho** [comment]
@QuellaZhang please test #2102.

**Comment by dscho** [comment]
> This is fixed in the `shears/` branches

Correction, this was fixed in the `msvc` branch (see https://github.com/gitgitgadget/git/pull/149).

**Comment by dscho** [comment]
> @QuellaZhang please test #2102.

Oh, I guess you can't, because you do not use command-line MSVC. Never mind, then. I'll just merge it.

**Comment by dscho** [comment]
@QuellaZhang can you please test the current `vs/master`? It should be fixed.

**Comment by QuellaZhang** [comment]
@dscho Thank you very much. Git can be built successfully now. : )
