### ISSUE TITLE
Unable to start editor emacs

### ISSUE THREAD

**Issue by bkline** [git-for-windows/git#2103]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ uname -a
MINGW64_NT-6.1 nci-ocdev03-v 2.10.0(0.325/5/3) 2018-02-12 08:49 x86_64 Msys
```

```
$ git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I have `core.editor` set to `emacs`. I can run `emacs` directly from the shell, but when `git` tries to invoke the editor for a commit I get the error quoted below.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
$ echo $SHELL
/usr/bin/bash

```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit
```
 - What did you expect to occur after running these commands?

My editor to be invoked for the commit message.

 - What actually happened instead?

```
$ git commit
hint: Waiting for your editor to close the file... warning: failed to restrict file handles (5)

handle #0: 0000000000000240 (type 3, handle info (1) 0
handle #1: 0000000000000244 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn emacs: Permission denied
error: unable to start editor 'emacs'
Please supply the message using either -m or -F option.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happens with any repo.

**Comment by bkline** [comment]
```
$ emacs --version
GNU Emacs 24.3.1
Copyright (C) 2013 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by PhilipOakley** [comment]
Hi, `git version 2.16.2.windows.1` had that bug of the "warning: failed to restrict file handles (5)".

It's time to upgrade, plus there is a truly latest version just released 2 days ago ... https://github.com/git-for-windows/git/releases/ - Git for Windows 2.21.0

It should fix everything...

**Comment by bkline** [comment]
Super, thanks!
