### ISSUE TITLE
No icon in taskbar

### ISSUE THREAD

**Issue by CreatorVilius** [git-for-windows/git#2104]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 > Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 > Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.590]
```

 > What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 > Any other interesting things about your environment that might be related
   to the issue you're seeing?

In /mingw64/share/git, there is `git-for-windows.ico`, so it shouldn't be the part of problem. I have seen solutions like `update`, or `fixed in newer version`, but I am using newest version.

**Comment by PhilipOakley** [comment]
do you have a (trimmed) screenshot of the offending place that should have the icon? (just to be sure we are looking at the right place)

**Comment by dscho** [comment]
In addition to a screenshot, let's also clarify what steps need to be done to reproduce this reliably. In other words, let's up our bug report game and provide an excellent [Minimal, Complete & Verifiable Example](https://stackoverflow.com/help/mcve).

**Comment by Urocza82** [comment]
Caly czas chodze w kolko i zadnych efektow. Chodzi o androida i czy mozna ściągnąć aktualizację wyzsza niz sie ma? LG K-10
