### ISSUE TITLE
Git using global configuration over local configuration

### ISSUE THREAD

**Issue by jltjohanlindqvist** [git-for-windows/git#2107]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.967]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No. I'm behind a company proxy, that's about it.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I have a few repositories, most using gitlab and one using AWS CodeCommit. In the global git config I have configured the property credential.helper = manager (using Windows Credential Manager). In the local git config in the folder for the AWS CodeCommit repository I have configured the credential.helper to use the AWS CLI that is required.

The issue I now have is that the local git configuration is overwritten by the global configuration. So even though the local git configuration has a different credential.helper value, it is still using the global configuration.

The workaround is to have no global configuration for credential.helper and instead only have local configurations. This workaround is annoying seeing as I have one or two CodeCommit repositories, but I have a lot more repositories that should use the Windows Credential Manager. So it would be a lot easier to be able to use a global setting for all non-CodeCommit repositories.

 - What did you expect to occur after running these commands?

Git will use the local configuration over the global configuration.

 - What actually happened instead?

Git uses the global configuration over the local configuration.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Any repository.

**Comment by dscho** [comment]
I updated your report for readability (the three paragraphs of description were marked as pre-formatted text, and it was not pre-formatted).

**Comment by dscho** [comment]
I think this is a misunderstanding of the `credential.helper` configuration. From https://git-scm.com/docs/git-config#git-config-credentialhelper:

> [...] Note that multiple helpers may be defined. See [gitcredentials[7]](https://git-scm.com/docs/gitcredentials) for details.

And at https://git-scm.com/docs/gitcredentials#_configuration_options:

> [...]
>
> If there are multiple instances of the credential.helper configuration variable, each helper will be tried in turn, and may provide a username, password, or nothing. Once Git has acquired both a username and a password, no more helpers will be tried.
>
> If credential.helper is configured to the empty string, this resets the helper list to empty (so you may override a helper set by a lower-priority config file by configuring the empty-string helper, followed by whatever set of helpers you would like).

In your instance, that means that you will want to insert the line `helper =` before the actual AWS helper configuration in your local config (e.g. via `git config -e`).

**Comment by jltjohanlindqvist** [comment]
Setting credential.helper to an empty string worked!

Thanks so much for the quick help and sorry about not reading the manual closely enough.
