### ISSUE TITLE
Auto Update Feature for Enterprises

### ISSUE THREAD

**Issue by sheshagirisrao** [git-for-windows/git#2108]
I work for an enterprise where packaging software is very challenging. 

Environment: Windows 10

1. Is there a way to run this as a non-admin user?  Basically no registry changes etc
2. Is there a way to auto-update like Chrome to the next stable version without admin capability?

**Comment by dscho** [comment]
> Is there a way to run this as a non-admin user? Basically no registry changes etc

No. Only Portable Git allows that, but it is not as easily automated/configured/auto-updates as the official Git for Windows installer.

Having said that, this is just the status quo. Any volunteer who feels strong can make a difference.

**Comment by dscho** [comment]
> Any volunteer who feels strong can make a difference.

@sheshagirisrao this is a strong hint from me, a really direct advice how you can get what you want.

**Comment by sheshagirisrao** [comment]
@dscho - I got the hint :) Will see what we can do to implement.
