### ISSUE TITLE
Git release 2.4.4

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#211]
Please create an exe file for this because there is none avalible. 2.4.2 has one.

**Comment by dscho** [comment]
My, my, pushy, aren't we?

As it is, I am in the middle of release engineering for 2.4.4 (and BTW 2.4.3 also has an installer), but I have to admit that I do not know about the state of https://github.com/git-for-windows/git-for-windows.github.io/pull/3 Any news on your end?

**Comment by dscho** [comment]
Released.

**Comment by paladox** [comment]
Thanks.
