### ISSUE TITLE
Help pages do not launch in browser from MSYS2 terminal

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#212]
Real output from attempt to view help page for `branch`:

```
$ GIT_TRACE=1 git branch --help
13:10:05.673209 git.c:348               trace: built-in: git 'help' 'branch'
Launching default browser to display HTML ...
```

Command halts / hangs after the last line in the logs above. No page is ever launched in any browser.

**Comment by dscho** [comment]
I cannot reproduce. This is what I did:

1. I installed Git via the installer
2. I launched the Git Bash
3. I called `git branch --help`

It does return right away and it opens the appropriate help page in my chosen default browser.

There must be something you do differently, but the report is not precise enough to tell me.

**Comment by rcdailey** [comment]
Thanks for confirming. I am not sure what other variables to check that might impact this, otherwise I'd be happy to give you more detail. Other than enabling `GIT_TRACE`, I'm not sure how else to check for issues.

**Comment by dscho** [comment]
> I'm not sure how else to check for issues.

Seeing as I cannot reproduce the issue, you will have to dive into a debugging session. That means rebuilding Git after removing the `-O2` flag in the Makefile and then calling the command with `gdb`, interrupting with Ctrl+C to see where it hangs, then taking it from there.

**Comment by dscho** [comment]
@rcdailey any progress on the `gdb` front?

**Comment by rcdailey** [comment]
No boss, sorry. I will try to get to it today. I am not familiar with debugging with `gdb` so this won't happen overnight.

**Comment by rcdailey** [comment]
I am not able to repro this on my home machine. When I get into work tomorrow, I will try debugging there.

**Comment by dscho** [comment]
I guess this is no longer an issue. Please feel free to close tickets yourself in the future when they are either resolved or no longer reproducible.
