### ISSUE TITLE
Ssh from git-with-openssh only runs in Windows compatibility mode

### ISSUE THREAD

**Issue by alexeiz** [git-for-windows/git#2120]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Installed via Scoop for Windows.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Everything worked on version 2.18.0.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
> ssh <host>
```
 - What did you expect to occur after running these commands?

Ssh login to `<host>` is successful.

 - What actually happened instead?

Ssh either waits for password, or logs in if using id_rsa key, then after a second or so it terminates.  No additional diagnostic messages are printed to the console.

- Additional information

Other ssh commands in my git-with-openssh installation exhibit the same behavior.  As I mentioned before, version 2.18.0 works just fine.  But ssh commands start working if I run them in the "compatibility" mode (with `set __COMPAT_LAYER=WIN7RTM`, `[System.Environment]::SetEnvironmentVariable("__COMPAT_LAYER", "WIN7RTM")` or via Windows Explorer).  That is: Windows 7 compat mode on Windows 7.

**Comment by dscho** [comment]
> version 2.18.0 works just fine.

Could you bisect that down a bit further?

**Comment by dscho** [comment]
Oh, and can you verify that the same issue happens with portable Git from https://github.com/git-for-windows/git/releases/tag/v2.21.0.windows.1? I don't use scoop.

**Comment by alexeiz** [comment]
It does happen with portable Git.  Scoop installs portable Git: https://github.com/lukesampson/scoop/blob/master/bucket/git-with-openssh.json

**Comment by rimrul** [comment]
>PortableGit-2.21.0-64-bit.7z.exe#/dl.7z"

>To change the filename of the downloaded URL, you can append a URL fragment (starting with #) to URLs. For example,
>
>"http://example.org/program.exe" -> "http://example.org/program.exe#/dl.7z"
>
>Note the fragment must start with #/ for this to work.
>
>In the above example, Scoop will download program.exe but save it as dl.7z, which will then be extracted automatically with 7-Zip. This technique is commonly used in Scoop manifests to bypass executable installers which might have undesirable side-effects like registry changes, files placed outside the install directory, or an admin elevation prompt.

It seems like scoop skips our post-install. Could that be the cause?

**Comment by alexeiz** [comment]
But scoop did this bypass post-install for all versions, including 2.18.0 which worked.  This can be verified by checking the history of git-with-openssh.json file.

Btw, what does the post-install do?

**Comment by dscho** [comment]
> Btw, what does the post-install do?

It runs a couple of shell scripts that are supposed to set things up like pseudo devices (which are special files, but handled as if they were devices by MSYS2/Cygwin, and they cannot be unpacked via 7-Zip).

**Comment by alexeiz** [comment]
For the record, I ran the post-install.bat manually.  It did not fix the issue.

**Comment by dscho** [comment]
Git for Windows v2.18.0 came with OpenSSH v7.7p1, while v2.21.0 comes with OpenSSH v7.9p1 (pkgrel 3).

That might amount for the difference you are seeing. I could imagine that OpenSSH v7.9 no longer supports Windows 7 (or older) properly.

If you have access to a developer machine, you will want to verify that hypothesis by installing the [Git for Windows SDK](https://gitforwindows.org/#download-sdk) and rebuilding OpenSSH v7.7 by calling

```sh
sdk cd MSYS2-packages
cd openssh
git checkout f4231a102e9b730d10ef8cb15547a25d9da2b5c3
makepkg --skippgpcheck -s
pacman -U openssh*.pkg.tar.xz
```

and then running another `ssh` call.
