### ISSUE TITLE
git-difftool illegal seek error (unable to create file, file already exists, no checkout)

### ISSUE THREAD

**Issue by gfody** [git-for-windows/git#213]
If a branch has commits for a file with different casing (e.g.: someFile.txt and SomeFile.txt)
when I run a git difftool -d to compare that branch with any other I will get this error:

here's the raw output:
```
C:\MyProject\myrepo [master]> git difftool -d somebranch...upstream/master
C:/Users/ADMINI~1/AppData/Local/Temp/git-difftool.dnajj/left/SomeFile.txt already exists, no checkout
C:\msys64\mingw64/libexec/git-core\git-difftool line 230: Illegal seek
```
I've tested the mingw packages for 2.4.2.windows.1 as well as 2.4.4.1
The msys build does not have this error

**Comment by dscho** [comment]
Please provide a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve), e.g. as an easily cloneable repository.

**Comment by gfody** [comment]
I setup a minimal example, e.g:
```
> git clone github.com:/gfody/test
> git difftool -d master...origin/testbranch
C:/Users/ADMINI~1/AppData/Local/Temp/git-difftool.9xW7u/right/filetwo already exists, no checkout
C:\msys64\mingw64/libexec/git-core\git-difftool line 239: Illegal seek
```

**Comment by dscho** [comment]
I guess you meant `git clone https://github.com/gfody/test`?

**Comment by dscho** [comment]
Running this with `GIT_TRACE=1` produces

```
12:04:50.855869 git.c:348               trace: built-in: git 'checkout-index' '--all' '--prefix=<TMP>/git-difftool.xONMg/right/'
<TMP>/git-difftool.xONMg/right/filetwo already exists, no checkout
<MSYS2>\mingw64/libexec/git-core\git-difftool line 239: Illegal seek
```

So I guess that is what you meant *actually*.

**Comment by dscho** [comment]
From that trace, it looks like this is a problem with difftool on case-insensitive file systems. As such, it is not a Windows-specific problem and I would therefore suggest to report it to the Git Mailing List: git@vger.kernel.org. Would you do that, please?

**Comment by gfody** [comment]
This isn't reproducible in linux (with a case-sensitive fs mounted) or even the msys build for windows, so it would seem to be specific to the mingw build. The illegal seek error is just the git-difftool script bombing on 'exit_cleanup' after git checkout-index failed. Indeed the *actually* minimal repro steps are:
```
> git clone github.com:/gfody/test
> cd test
> git ls-tree origin/testbranch | git update-index --index-info
> mkdir r
> git checkout-index -a --prefix=r/
```
(git-difftool doesn't actually use ls-tree to update the index, rather it loops through the results of git-diff --raw and formats the index info, this is just an easier repro)

It seems like the behavior in linux and msys is that the "already exists, no checkout" messages are non fatal and it goes on to launch the diff tool with the incomplete index. This is preferable - in the real-life-scenario where this is affecting us, the mixed case files preventing difftool from launching are otherwise inconsequential.

I noticed another thing while testing around that may be relevant. In linux, in this repo on a case-insensitive filesystem, if you try to checkout testbranch it doesn't allow it, saying:
```
error: The following untracked working tree files would be overwritten by checkout:
	FileOne
	FileTwo
Please move or remove them before you can switch branches.
Aborting
```
in git for windows (mingw and msys both) it allows the checkout and quietly overwrites the files without warning. Then if you try to switch back to master it complains with the same exact message above.

**Comment by gfody** [comment]
I think I see what's going on now. diff-tool uses `--prefix=<system temp>/right/` so on linux it doesn't matter that the repo is on a case-insensitive filesystem, if the system temp is case-sensitive then it will succeed in checking out the mixed case files. And apparently the msys build is able to write mixed case files to its temp location even though it is ntfs, lookie here:
![tmp](https://cloud.githubusercontent.com/assets/1146032/8273415/a850e90c-1821-11e5-80e7-16037ad968e5.png)

..so I think it boils down to the mingw build treating ntfs as case-insensitive [when apparently it's not](https://support.microsoft.com/en-us/kb/100625)

**Comment by gfody** [comment]
After some research I found that the win32 apis do support case sensitivity ([there's a good writeup here](http://www.nicklowe.org/2012/02/understanding-case-sensitivity-in-windows-obcaseinsensitive-file_case_sensitive_search/)), but the ms library that mingw uses for _wfopen (msvcrt.dll) does not. I think a fix would be to re implement the various file routines in compat/mingw.c to use win32 instead of msvcrt (and supposedly use FILE_FLAG_POSIX_SEMANTICS when core.ignorecase is false).

**Comment by dscho** [comment]
@gfody Win32 supports case-sensitive file systems, but by default your file system is *still* case-insensitive. And it is the *latter* problem that is the issue here.

**Comment by dscho** [comment]
... and if you use Linux with a case-insensitive file system, you run into the same issue (you can verify this by using [the Vagrant way to run Git on Windows](https://github.com/git-for-windows/git/wiki/Vagrant).

**Comment by gfody** [comment]
Yes, so it turns out that my system is configured as case-sensitive (via the obcaseinsensitive registry setting - I had done this long ago for some other reason and forgotten about it). Msys detects this and properly implements case sensitivity but mingw does not - and so this explains the different behavior between the mingw build and the msys build.

I think the way git behaves when the system temp is on a case-insensitive filesystem is at least consistent between linux and windows. Should I open a separate issue that is instead a feature request for the mingw build to support case sensitivity on windows?

**Comment by dscho** [comment]
Sorry, I missed that you set your system to case-sensitive. Since you are so tech-savvy, maybe you also want to work on a Pull Request that fixes things in `compat/mingw.c` to work through the correct APIs?

**Comment by gfody** [comment]
Happy to. Should I reference this issue in the PR or a new one that frames it as a feature request instead?

**Comment by dscho** [comment]
Yeah, referencing this issue in the PR would be good style.
