### ISSUE TITLE
Gitflow init using emtpy prefixes for branches as default

### ISSUE THREAD

**Issue by ScottGage** [git-for-windows/git#2130]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 64-bit

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? 10 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.967]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir gitflow-issue
cd gitflow-issue
git flow init -d 

```
 - What did you expect to occur after running these commands?

Initialized empty Git repository in D:/Projects/Repos/gitflow-issue/.git/
Using default branch names.
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master]
Branch name for "next release" development: [develop]

How to name your supporting branch prefixes?
Feature branches? [feature/]
Bugfix branches? [bugfix/]
Release branches? [release/]
Hotfix branches? [hotfix/]
Support branches? [support/]
Version tag prefix? []
Hooks and filters directory? [D:/projects/repos/gitflow-issue/.git/hooks]

 - What actually happened instead?

Initialized empty Git repository in D:/Projects/Repos/gitflow-issue/.git/
Using default branch names.
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master]
Branch name for "next release" development: [develop]

How to name your supporting branch prefixes?
Feature branches? []
Bugfix branches? []
Release branches? []
Hotfix branches? []
Support branches? []
Version tag prefix? []
Hooks and filters directory? [D:/projects/repos/gitflow-issue/.git/hooks]

The problem is that the default prefixes are now empty.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happening with all repos that I create

Related to this issue on petervanderdoes/gitflow-avh repo
https://github.com/petervanderdoes/gitflow-avh/issues/393

Has been fixed in that repo, but not incorporated into a release for Git fow windows.

**Comment by PhilipOakley** [comment]
So, if i understand correctly, there has been an upstream fix in git-flow that should be propagated down into Git-for-Windows ready for the next release, and it just needs "someone" to create a short PR to update the various parts of build process?

It shouldn't be hard, why not have a poke around with the SDK and have a go. I'm sure git-flow / gitflow has been mentioned in at least another issue thread..

All help welcomed.

**Comment by PhilipOakley** [comment]
@ScottGage see if #2038 will also cover your reported problem?

**Comment by schnitty** [comment]
@PhilipOakley Thanks for your response.  I think the version we need is 1.12.1
I'll take a quick look to see what is involved in creating a PR to make the required update.

**Comment by schnitty** [comment]
It looks like the version of git flow has been updated, just hasn't made it into the latest release of git for windows yet

https://github.com/git-for-windows/MSYS2-packages/blob/master/git-flow/PKGBUILD

Looks like it should get included in the next release

**Comment by dscho** [comment]
@schnitty please do test the latest snapshot at https://wingit.blob.core.windows.net/files/index.html (it [might not have Git Flow v1.12.2 yet](https://github.com/git-for-windows/git-sdk-64/commits/master/var/lib/pacman/local/git-flow-1.12.2-1), but probably it will have v1.12.1).
