### ISSUE TITLE
When i start bash, it will scanning all the node_moudles

### ISSUE THREAD

**Issue by ShawnMinh** [git-for-windows/git#2131]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

7 ， 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [▒汾 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

i install Symantec, and i run process monitor, it make bash scan all the node_modules

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash and cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
any commands 
```
 - What did you expect to occur after running these commands?

run fast like before

 - What actually happened instead?

it's was so slow

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

not

**Comment by ShawnMinh** [comment]
whatever i start cmd or bash or input any git commands , it always scann all the node_modules fields.  it make bash so slow

**Comment by ShawnMinh** [comment]
i run process monitor and  watch bash and cmd , i found it will scan all the node_modules fields when i start cmd or bash or input any git commands ,

**Comment by ShawnMinh** [comment]
![0190319140609](https://user-images.githubusercontent.com/31064728/54583772-3d6e7900-4a50-11e9-88ba-3591bb07a27d.png)

**Comment by PhilipOakley** [comment]
You may find that your "PS" (prompt script") is trying to determine some local status about your (bash) home directory, and that all those files/directorys are part of that 'check' - just a thought (I only have a few minutes today).

**Comment by PhilipOakley** [comment]
when you say 'i install Symantec' (with virus scanner?), was the install done after everything slowed down? Virus scanners are a know problem. (I saw the messages in the wrong order...)

**Comment by dscho** [comment]
@ShawnMinh are you planning on working with @PhilipOakley who kindly offered to help you resolve your problem? Otherwise, please close this ticket.
