### ISSUE TITLE
warning: failed to restrict file handles (5) (v2.21.0.windows.1, intermittent/once)

### ISSUE THREAD

**Issue by achekerylla** [git-for-windows/git#2132]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

* My issue is similar to https://github.com/git-for-windows/git/issues/1675.  My git version (2.21.0.windows.1) is different from the original reporter (version 2.16.1.windows.4) and one commenter (2.17.0.windows.1).  Perhaps this is different.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

H:\>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

* None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

* MingW64

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
* The issue is intermittent.  Only occurred once

```
 - What did you expect to occur after running these commands?

$ git checkout team/integ-v2
Checking out files: 100% (222/222), done.
Switched to branch 'team/integ-v2'
Your branch is behind 'origin/team/integ-v2' by 8 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
warning: failed to restrict file handles (5)

handle #0: 0000000000000010 (type 2, handle info (1) 0
handle #1: 00000000000001c0 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

 - What actually happened instead?

* Branch checkout was successful.  Git status after git pull was clean.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

* Repository is private

**Comment by PhilipOakley** [comment]
(Updated the title for clarity).

If this is only a single occurrence then we may ignore it as bad luck / race in the FS / gremlins...
If it happens again to you or colleagues, please report that, as without a repeatable / repeated error it is difficult to debug..

**Comment by achekerylla** [comment]
@PhilipOakley - Thank you

**Comment by PhilipOakley** [comment]
I'll close this as it occurred only once. There may also be a separate piece of software that caused the issue that had the older version embedded as discussed in https://github.com/git-for-windows/git/issues/1544#issuecomment-480207271 for the 'idea' software.
