### ISSUE TITLE
Nested submodules incompatible between Git for Windows and Git on Bash.

### ISSUE THREAD

**Issue by dmcilvaney** [git-for-windows/git#2133]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18859.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Git on Bash version is:
git version 2.7.4

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Both Bash and CMD/PowerShell/VSCode

### Background:

**This might just be an incompatibility which is too much trouble to deal with between Windows/Bash, which is fine. I figured I had spent enough time tracking this down that I might as well pass it along**

The issue pressented itself in VSCode. VSCode provides a Bash terminal through Windows Subsystem for Linux (WSL), and the commands to add the submodule were originally entered there.

VSCode uses Git for Windows to execute its internal commands to populate the GUI, manage commits etc. There appears to be an incompatibility between Bash/Windows when working with nested submodules.

All of the below commands should be run from **CMD/Powershell**, but the fail case also fails when modified to run natively from Bash (WSL)

Failure when Bash(WSL) is used to add nested submodules:
Note that the first layer of submodules work fine!
```powershell
mkdir submodule_issue_repro_failing
cd submodule_issue_repro_failing
git init
mkdir external
cd external
wsl git submodule add https://github.com/openssl/openssl.git
echo "This status should work"
git status
```
```
pushd openssl
wsl git submodule init
wsl git submodule update
popd
echo "This status should fail"
git status
```
Resulting error:
```
>>> fatal: not a git repository: /mnt/e/submodule_issue_repro_failing/.git/modules/external/openssl/modules/boringssl
>>> fatal: 'git status --porcelain=2' failed in submodule external/openssl
```
**Note 1: The __/mnt/e/submodule...__ path, it looks like Git is using a hardcoded path as generated in Bash instead of a relative one?**
**Note 2: Adding a completely new submodule inside openssl rather than initializing the existing ones also breaks in the same manner**

Success when the the modules are added from Git for Windows, note that Git on Bash **does** succesfully read the repo.
```powershell
mkdir submodule_issue_working
cd submodule_issue_working
git init
mkdir external
cd external
git submodule add https://github.com/openssl/openssl.git

pushd openssl
git submodule init
git submodule update
popd

echo "Both Git-Bash and Git for Windows work"
git status
wsl git status
```

 - What did you expect to occur after running these commands?

Normally git on Bash/Windows are both at least able to read the status of a repo, I would not have expected a __nested__ submodule to break that when a first layer submodule does not.

 - What actually happened instead?

Initializing a submodule inside another submodule from Bash causes Git for Windows to be unable to parse the root repository.

**Comment by dscho** [comment]
This is most likely not a Windows-specific issue: whenever you clone submodules, Git writes absolute paths into those internal files. The same is true for worktrees.

As it is a broader issue, and not specific to Windows, this ticket will not see as much attention as you might get on the Git mailing list. You might want to send a mail there (plain text only, no HTML, that will be rejected): git@vger.kernel.org.
