### ISSUE TITLE
Git for windows in not downloading.

### ISSUE THREAD

**Issue by yanjanendra** [git-for-windows/git#2134]
I am using window 10 Home OS build **16.0** something and my chrome version is **72.0.3626.121** (Official Build) (64-bit), but from last 2 days i am trying to download the git on my computer, but its not downloading, I also tried edge to download and i counter the same problem again and again.

**Comment by dscho** [comment]
We are using GitHub Releases. If the download is not working, it is an issue with GitHub Releases (or Amazon S3), not with Git for Windows, and we cannot really do anything about it here. Maybe contact GitHub's support team?

As a workaround, you can use the latest snapshot (which should be just as good as, if not better than, the latest official version): https://wingit.blob.core.windows.net/files/index.html

**Comment by yanjanendra** [comment]
Thanks it works for me.
