### ISSUE TITLE
Merge dracula mintty theme file changes

### ISSUE THREAD

**Issue by technic** [git-for-windows/git#2135]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### TL;DR

Please distribute latest darcula theme due to this commit https://github.com/dracula/mintty/commit/731fdd5247683fea9681ceeb29377b0e16b589ff.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cat /usr/share/mintty/themes/dracula
```
 - What did you expect to occur after running these commands?

See up to date dracula theme

 - What actually happened instead?

This [commit](https://github.com/dracula/mintty/commit/731fdd5247683fea9681ceeb29377b0e16b589ff) is missing.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** irrelevant **

**Comment by PhilipOakley** [comment]
I can't say that I approve.

Why is black being converted to some form of soft grey. As someone with an eyesight deficient from an accident, I find all these web sites and "design" rules  that make black into some insipid, soft, hard to focus, low contrast, shade to be a poor choice and contrary to various disability access guidance.

If folks are trying to distinguish black on black then I thinks that it's a different problem, with a different solution.

(also commented at https://github.com/dracula/mintty/commit/731fdd5247683fea9681ceeb29377b0e16b589ff)

**Comment by technic** [comment]
Because it was of the same color with background. For example in htop you cannot see text which is usually grey (like usernames of other users).
Anyway, if you provide a theme which is the fork of other project you should follow the upstream decisions or rename it to "dracula-git-mod" in order to not confuse others.

**Comment by technic** [comment]
@PhilipOakley 
This was original commit with the description https://github.com/dracula/mintty/commit/fb841f316f43e8aaccc8a08c1e7a4e037206654e

**Comment by dscho** [comment]
First of all, I agree with @PhilipOakley that the change is at least under-explained, and actually quite possibly not at all something we would want to take.

Second, this is not exactly a wish fest over here, but a bug tracker. What you are describing is a feature request, and we do not have the bandwidth/number of volunteers to accommodate random feature requests that have little to do with Git (which is really what we are trying to develop here: Git for Windows). So if you want to see a change in Git for Windows, in particular when it does not exactly fix a bug, you should feel more than just compelled to bring that change about by opening a Pull Request.

Third, we consume official MinTTY releases. This change did not make it into an official release, and once it does, our regular work on integrating new versions of included components will pick it up.

**Comment by technic** [comment]
> Third, we consume official MinTTY releases. This change did not make it into an official release, and once it does, our regular work on integrating new versions of included components will pick it up.

Aha, I was looking for this file to make a PR but didn't find it, so I ended up with creating this issue. Thanks, for your clarification, I will try to find the right repository to pull request.
