### ISSUE TITLE
Problems with paths that include both unicode characters and spaces

### ISSUE THREAD

**Issue by monoblaine** [git-for-windows/git#2136]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.379]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I'm aware of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir "ş ş ş"
cd "ş ş ş"
git init
echo foo > foo.txt
git add .
git commit -m hello
git commit --amend
```
 - What did you expect to occur after running these commands?

I expect that the editor is displayed with the last commit message.

 - What actually happened instead?

Nothing happens because the path given by git to `.git/COMMIT_EDITMSG` is invalid.

I've created a simple c++ console app to see what git sends to the editor as command line arguments:

```cpp
#include "pch.h"
#include <windows.h>
#include <fstream>
#include <codecvt>

int main () {
    std::wofstream wof;
    wof.imbue(std::locale(std::locale::empty(), new std::codecvt_utf8<wchar_t, 0x10ffff, std::generate_header>));
    wof.open("example.txt");
    wof << GetCommandLine();
    wof.close();
}
```

Use this app as `core.editor`:

```
git config --global core.editor "'C:/Users/Serhan/source/repos/ConsoleApplication1/Debug/ConsoleApplication1.exe'"
```

Then:

```
cd "ş ş ş"
git commit --amend
```

Here is the `example.txt` created by our fake editor:

```
C:\Users\Serhan\source\repos\ConsoleApplication1\Debug\ConsoleApplication1.exe "\"C:/Users/Serhan/Desktop/ş ş ş ş/.git/COMMIT_EDITMSG\""
```

(Path is surrounded by double quotes... Twice?)

Let's try this with a different path name (no spaces, but contains unicode letter):

```
cd ..
ren "ş ş ş" ş
cd ş
git commit --amend
```

Here is the new `example.txt` created by our fake editor:

```
C:\Users\Serhan\source\repos\ConsoleApplication1\Debug\ConsoleApplication1.exe C:/Users/Serhan/Desktop/ş/.git/COMMIT_EDITMSG
```

Looks normal.

Another take:

```
cd ..
ren ş "s s"
cd "s s"
git commit --amend
```

`example.txt`:

```
C:\Users\Serhan\source\repos\ConsoleApplication1\Debug\ConsoleApplication1.exe "C:/Users/Serhan/Desktop/s s/.git/COMMIT_EDITMSG"
```

Still looks normal.

I guess the space & unicode combination confuses git.

**Comment by dscho** [comment]
Could you re-test with v2.25.0-rc0, please? There have been some quoting/Unicode fixes in the meantime.

**Comment by monoblaine** [comment]
Hey @dscho, just tested **v2.25.0-rc2.windows.1** on a Windows VM and the same test commands gave `"C:/Users/IEUser/Desktop/ş ş ş/.git/COMMIT_EDITMSG"` as a result, so the issue is fixed. Thank you!

**Comment by dscho** [comment]
Excellent!
