### ISSUE TITLE
Bug in Git Flow 1.12.0  fixed with Version 1.12.2

### ISSUE THREAD

**Issue by mugbox** [git-for-windows/git#2139]
When using the **-d** flag during git flow init the defaults are empty.
This bug is not completely fixed within Release 1.12.1 (https://github.com/petervanderdoes/gitflow-avh/releases/tag/1.12.1)
The final fixing comes up within Version 1.12.2 (https://github.com/petervanderdoes/gitflow-avh/releases/tag/1.12.2)
It is neccessary to update git flow to version 1.12.2

**Comment by mminns** [comment]
Thanks @mugbox I cam here looking for the answer to that very question.

**Comment by dscho** [comment]
> Thanks @mugbox I cam here looking for the answer to that very question.

Look no further than here: https://github.com/git-for-windows/git/issues/2130

Meaning that this is a duplicate, and my latest comment there applies also here:

> please do test the latest snapshot at https://wingit.blob.core.windows.net/files/index.html (it might not have Git Flow v1.12.2 yet, but probably it will have v1.12.1).
