### ISSUE TITLE
Move terminal emulator Cygwin

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#214]
Hi please could we move from mintty to Cygwin.

The reason is because mintty is no longer reciving updates as far as I can tell in the source code.

Cygwin is more widly used in windows and is updated frequently it includes similer desgn to mintty but much fresher.

**Comment by paladox** [comment]
http://cygwin.com/

**Comment by paladox** [comment]
Move to Cygwin would be benifical since it is updated regualy. Bugs are fixed.

**Comment by dscho** [comment]
If you want to use Cygwin, there is nobody stopping you. It comes with its own version of Git.

**Comment by paladox** [comment]
Oh I mean text editor but I found out it run off minty.

**Comment by paladox** [comment]
Mintty source code now loacated at https://github.com/mintty/mintty
