### ISSUE TITLE
Git 2.21.0 Git LFS not working on a clean Windows Server 2019 installation

### ISSUE THREAD

**Issue by christianbumann** [git-for-windows/git#2140]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

**64-Bit**

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
Original Install Date:     3/26/2019, 7:24:51 AM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** A fresh installed Windows 2019 **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** CMD or Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**C:\repo>git version
git version 2.21.0.windows.1

C:\repo>git lfs --version
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)

C:\repo>git lfs checkout
Cannot checkout LFS objects, Git LFS is not installed.

C:\repo>git lfs install
Updated git hooks.
Git LFS initialized.

C:\repo>git lfs checkout

Now the command will run succesfull**

```
 - What did you expect to occur after running these commands?

** Git should checkout the LFS files **

 - What actually happened instead?

** Message `Cannot checkout LFS objects, Git LFS is not installed.` appears **

- Remarks

** After running `git lfs install` you can uninstall and install Git again, the issue will not be present anymore. That means you need a `fresh Windows installation`. I only tested it with Windows Server 2019,  Windows Server 2012 R2 so I don't know its even an issue with other Windows versions (10, Server 2016). Installing `Git 2.20.1` is working on a fresh installation **

**Comment by dscho** [comment]
Hmm. I think we try to imitate that by setting [some config entries](https://github.com/git-for-windows/git-sdk-64/blob/1d68933032122b461d1a9fcd9f2bdfa19a052cf5/mingw64/etc/gitconfig#L19-L23):

```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```

Maybe newer Git LFS versions do more? Can you dig deeper?

**Comment by rimrul** [comment]
Could we just add `git lfs install` to the post-install to fix this? 

Technically the `git lfs` documentation says

>On all operating systems, once git-lfs is installed, git lfs install must be run. Each user that intends to use git lfs must run this command, but they only ever need to run it once. git-lfs can be disabled by running git lfs uninstall, in which case that user would have to run git lfs install again, before git-lfs features work again.

>Some users may wish to only enable git-lfs on specific repositories instead of always having it on for all of the repositories. Instead of running git lfs install and enabling git-lfs for that entire user, git lfs install --local can be used instead on a per repository basis.

and

>Windows
>1. Download the windows installer from here
>2. Run the windows installer
>3. Start a command prompt/or git for windows prompt and run git lfs install


So I'd say this behaviour is exactly as intended by the `git lfs` creators.

Source: https://github.com/git-lfs/git-lfs/wiki/Installation

**Comment by rimrul** [comment]
It seems like they currently set the following values:

````
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge --skip -- %f
	process = git-lfs filter-process --skip
	required = true
````

if I read the source right.

**Comment by dscho** [comment]
> So I'd say this behaviour is exactly as intended by the `git lfs` creators.

Yes, but we have to install this into the system config, and in the portable Git, we want to pre-configure it. So I think we'll simply have to add the `--skip` option to our Git config (https://github.com/git-for-windows/build-extra/blob/master/mingw-w64-git-lfs/git-lfs.install).

**Comment by dscho** [comment]
Turns out that it is not a stale set of `filter.lfs` config settings that is the problem, but that we do not configure any `filter.lfs` config settings *by mistake*!
