### ISSUE TITLE
Error 500 when creating pull request

### ISSUE THREAD

**Issue by bkodre** [git-for-windows/git#2142]
- Gitea version:  1.7.4
- Git version: 2.16.2.windows.1
- Operating system: Microsoft Windows [Version 6.3.9600]
- Database: mysql
- Can you reproduce the bug at https://try.gitea.io: NO 

### Description

2019/03/28 13:21:58 [...routers/repo/pull.go:912 CompareAndPullRequestPost()] [E] PushToBaseRepo: Push: exit status 1 - warning: failed to restrict file handles (2)

**Comment by bkodre** [comment]
Sorry, i created this issue by mistake.

**Comment by PhilipOakley** [comment]
Juts to confirm, 2.16. did have the 'warning: failed to restrict file handles (2)' problem that is fixed in newer versions.
