### ISSUE TITLE
Font size options not sufficient for projector

### ISSUE THREAD

**Issue by steltenpower** [git-for-windows/git#2144]
I wanted a bigger font as the back of the room had a very hard time reading, but it was already the biggest.

**Comment by rimrul** [comment]
The font size dropdown in Git Bash caps out at 72 if you installed it with the MinTTY option, but you can manually enter larger values (tested it with 96). That's the same as Word. If you installed it with the CMD option you'll have to set it to a different font than the raster font to get it larger than 12*16 or 10*18

**Comment by steltenpower** [comment]
Thanks. Looked a couple of times and then saw that you can indeed change font in CMD
