### ISSUE TITLE
add browser-like zooming

### ISSUE THREAD

**Issue by steltenpower** [git-for-windows/git#2145]
control +
control -
control 0

**Comment by rimrul** [comment]
Assuming you went with MinTTY as your terminal option, that's already a thing and should be enabled in Git Bash by default.

**Comment by PhilipOakley** [comment]
> 
> 
> Assuming you went with MinTTY as your terminal option, that's already a thing and should be enabled in Git Bash by default.

I didn't appreciate/know that. Good to know. Thanks.

**Comment by steltenpower** [comment]
I guess I tried that on CMD, but not on MinTTY. Good to know, thanks
