### ISSUE TITLE
more backgroundcolor/fontcolor options needed

### ISSUE THREAD

**Issue by steltenpower** [git-for-windows/git#2146]
Had to install a different shell to get colors that worked on the projector :-(

**Comment by rimrul** [comment]
Git Bash with MinTTY comes with 9 preinstalled themes, gives you 24bit colours to choose a foreground, background and cursor colour and links you to a web based colour scheme generator, what more config options do you want?

**Comment by rimrul** [comment]
Even if you used the CMD option you should still have  the whole 24bit RGB colour space available for foreground and background colours.

**Comment by steltenpower** [comment]
If text was single color, you would be absolutely right.
I remember however (as I now have MinTTY instead of CMD there) that text was multi-color and the color setting only changed one of them. I hope you know if this is correct, so I can iron out any misunderstandings/incompatibilities/problems in open lesson material used by thousands.

**Comment by PhilipOakley** [comment]
@steltenpower do you have a reference/link to the "open lesson material used by thousands"? It could be linked via the [wiki](https://github.com/git-for-windows/git/wiki)

**Comment by rimrul** [comment]
To change those colours you'll need to either use one of the included schemes, the colour scheme designer or a minnty theme from the internet; or alternatively manually edit your .minttyrc file AFAIK.

**Comment by steltenpower** [comment]
@rimrul I had the problem with CMD (the color scheme it had out of the box was unreadable from the projector and it seemed I could only change (into?) one color). Using minTTY instead solved it.

@PhilipOakley carpentries.org has several (slightly different) lessons on git. It's the setup part that might need a change. It was the Software Carpentry version we used.

@vwkoppejan maybe you do have a clear memory of how this went? I want to change (the setup part of) the lesson we used to prevent future workshops from having this hiccup.

**Comment by vwkoppejan** [comment]
@steltenpower, the problem was we created and populated an online and local repo with files. This caused conflicts when pulling online to local. 

Perhaps it's a good idea to setup the remote earlier in the lesson, or make absolutely sure an empty online repo is created.

**Comment by steltenpower** [comment]
I think I figured out what happened:

The installer of Git for Windows asks
==========================
 "Which terminal emulator do you want to use with your Git Bash?"

[X] Use MinTTY (the default terminal of MSYS2)
...
[  ] Use Windows' default console window
... cmd.exe ...
===========================
I must have picked the 2nd, instead of the default 1st option there :-(
Not something others are likely to run into, so nothing to change in the material.

@vwkoppejan you're referring to the other hiccup in the lesson. I'll do a PR for the 2nd option in your suggestion
