### ISSUE TITLE
Where is system-wide gitattributes in git 2.4.4?

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#215]
Where is system-wide gitattributes in git 2.4.4?
It is not found in `C:\ProgramData\Git` after installation.

In git 1.9.5, it was located at `C:\Program Files (x86)\Git\etc\gitattributes`

**Comment by dscho** [comment]
It is found in `C:\ProgramData\Git` when running on Windows later than XP. For Windows XP, the path is `C:\Documents and Settings\All Users\Application Data\Git`. Are you on XP? Please provide such information in your future reports even if you think them irrelevant; as you see, it is quite relevant to know more about your environment when trying to help you.

**Comment by linquize** [comment]
On Win 7 x64, I upgrade to git 2.4.4 (x64) from git 2.4.0 (x64) also with git 1.9.5.

After upgrading, I found `C:\ProgramData\Git\config` only but no `gitattributes`

**Comment by dscho** [comment]
@linquize whoops, I misread your `gitattributes` for `config`... IIRC we do not handle system-wide attributes yet.

**Comment by linquize** [comment]
So it is currently missing from git 2.x?

**Comment by kblees** [comment]
`C:\Program Files\Git\mingw64\etc\gitattributes`

PR #157 moves this to `C:\ProgramData\Git`, but according to @dscho doing this for both of git`s `/etc` config files violates git's design.

**Comment by linquize** [comment]
`C:\Program Files\Git\mingw64\etc\gitattributes` also does not exist
`C:\Program Files\Git\mingw64\etc` has only `pkcs11`, pki` directories.

**Comment by kblees** [comment]
So it seems GfW 2.4.4 doesn't install one.

**Comment by dscho** [comment]
Seems like it, indeed. Pull Requests welcome!
