### ISSUE TITLE
Cannot check out files with forward slash in name in Windows

### ISSUE THREAD

**Issue by AstralStorm** [git-for-windows/git#2153]
Git is unable to clone or checkout frameworks/compile/slang repository from AOSP due to forward slash in path name. The checkout works if I create the str directory by hand which is actually invalid path for the test, but the suite would run with it.

(I'm not actually running its tests so it's fine for me, but might be pain for someone else with an actual repository where the file name matters.)

Some sort of mapping functionality should probably be provided in git-config to allow a normal checkout.

### Setup

Git for Windows 64-bit and Git on Cygwin, version 2.21.0.
Windows 7 Enterprise 64-bit.
Administrator user, symlink permissions added.
Git Repo latest master for Cygwin, latest esr-repo stable for MSys version.
All three terminals. File system is NTFS.

### Repository

https://android.googlesource.com/platform/frameworks/compile/slang

tag android-9.0.0_r35

### Trace

```
: cd /cygdrive/c/Source/AOSP/frameworks/compile/slang
: git read-tree --reset -u -v HEAD 1>| 2>|
error: unable to create file tests/P_str_escape/str\\escape.rs: No such file or directory
Checking out files: 100% (856/856), done.
Traceback (most recent call last):
  File "/cygdrive/c/Source/ims/.repo/repo/main.py", line 547, in <module>
    _Main(sys.argv[1:])
  File "/cygdrive/c/Source/ims/.repo/repo/main.py", line 522, in _Main
    result = repo._Run(argv) or 0
  File "/cygdrive/c/Source/ims/.repo/repo/main.py", line 184, in _Run
    result = cmd.Execute(copts, cargs)
  File "/cygdrive/c/Source/ims/.repo/repo/subcmds/sync.py", line 840, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/cygdrive/c/Source/ims/.repo/repo/project.py", line 1379, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "/cygdrive/c/Source/ims/.repo/repo/project.py", line 2587, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
```

**Comment by PhilipOakley** [comment]
Are you saying that you have individual components of the  path names 
that include a 'wrong way' slash in the file or directory name? Don't do 
that.

That would be one of the many cases of using illegal characters in a 
file or directory name on Windows. It's not going to happen on Git for 
Windows - look up the various answers to the problems of folks using 
colons ':' in path names.

[Clue: someone has to make a decision to not do it and change policy; or 
wait for/find some tool/process that marks the file as not being checked 
out - means you can't edit it but you bypass the problem, though it 
won't work for directories that need files checked out].

Sorry to be the purveyor of bad news.

Philip

**Comment by AstralStorm** [comment]
Well, it should be easy enough to provide a file similar to .mailmap for character mapping and/or handle some invalid paths by creating all directories in the way that happen due to forward slashes.

If I get annoyed enough I'll probably patch it on my own.

**Comment by dscho** [comment]
> I'll probably patch it on my own.

Excellent.
