### ISSUE TITLE
Git overwrites credentials prompt when git-lfs repo is different than git repo

### ISSUE THREAD

**Issue by cowlinator** [git-for-windows/git#2154]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
C:\WINDOWS\system32> git --version --build-options
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
C:\WINDOWS\system32>cmd.exe /c ver
Microsoft Windows [Version 10.0.17134.648]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
C:\WINDOWS\system32>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
git-lfs/2.7.1
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Create a repo on github enterprise.
Create a git-lfs repo on an Artifactory "on prem" server.
Ensure git-lfs is installed.
Ensure that the .lfsconfig file contains Artifactory as the lfs file storage: `url = "https://artifactory.myserver.com/artifactory/api/lfs/myrepo"`
Ensure that the .gitattributes file contains .png as a lfs file type: `*.png filter=lfs diff=lfs merge=lfs -text`
Commit and push 1 png file, ensuring that it is stored on the lfs server.  
In a new local directory, type `git clone https://artifactory.myserver.com/artifactory/api/lfs/myrepo .`
```
 - What did you expect to occur after running these commands?

The clone will succeed and will correctly prompt for credentials.  The clone will not appear to freeze.

 - What actually happened instead?

We discovered a condition where, when cloning a repo, the clone appears to freeze after the "checkout" phase is complete.

The condition is that we are using git with git-lfs.  The git remote repo is github, but the git-lfs file storage server is a 3rd party (Artifactory).

The clone does not actually freeze, what is really happening here is that it is actually asking the user for their credentials for Artifactory, but the prompt is invisible (blank), making it look like the clone has frozen/failed.  

Git is performing multiple smudge commands asynchronously and outputing to the console, but one of those commands invokes git-lfs, which in turn requests credentials.  

The credentials prompt gets overwritten.

Here is some example output:

```
C:\Temp>git clone https://github.myserver.com/org/myrepo.git .
Cloning into '.'...
Username for 'https://github.myserver.com': me
Password for 'https://me@github.myserver.com':
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 6140 (delta 2), reused 26 (delta 1), pack-reused 6109
Receiving objects: 100% (6140/6140), 3.26 MiB | 729.00 KiB/s, done.
Resolving deltas: 100% (337/337), done.
Checking out files: 100% (7537/7537), done.com': Checking out files:  12% (949/7537)

```

After typing my username into the blank line after the "Checking out files" line, the clone then correctly prompts for my Artifactory password.

You can see that the "Checking out files" line contains the string fragment `.com':`, which is part of the git-lfs/Artifactory credentials prompt.

There are workarounds, such as using the credential manager, or cloning with `-q`.  

However, since it is not clear to the user what the problem is, they are unlikely to attempt or find out about these workarounds.

There are multiple ways this could be addressed.  Perhaps you could not print the “Checking out files” text in this scenario?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, I cannot.

**Comment by cowlinator** [comment]
See also https://github.com/git-lfs/git-lfs/issues/3585

**Comment by patricklangsonos** [comment]
I don't think this is unique to Windows, I've also seen it on Mac.

**Comment by dscho** [comment]
So this seems not to be a Windows-specific issue? Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

**Comment by patricklangsonos** [comment]
This looks like the same issue https://github.com/git-lfs/git-lfs/issues/2834
