### ISSUE TITLE
git for windows 2.16.2: cannot spawn ssh: Function not implemented when running git pull (or any git command, really)

### ISSUE THREAD

**Issue by hemant2491** [git-for-windows/git#2157]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Got below error in Windows 10 , running Mobaxterm terminal
` ➤ git pull
warning: failed to restrict file handles (216)

handle #0: 00000000000001d4 (type 3, handle info (1) 0
handle #1: 00000000000001d8 (type 3, handle info (1) 1
handle #2: 00000000000001f0 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

    SUPPRESS_HANDLE_INHERITANCE_WARNING=1
error: cannot spawn ssh: Function not implemented
fatal: unable to fork
✘
──────────────────────────────────────────────────`

Setup
Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
➤ git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
                                   
Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windown 10
➤ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.1029]

What options did you set as part of the installation? Or did you choose the
defaults?
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

➤ cat "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

Details
Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
** mobaxterm terminal **

➤ echo $SHELL
/bin/bash.exe
What commands did you run to trigger this issue? If you can provide a
Minimal, Complete, and Verifiable example
this will help us understand the issue.
** git pull **
➤ git pull
warning: failed to restrict file handles (216)

handle #0: 0000000000000198 (type 3, handle info (1) 0
handle #1: 000000000000019c (type 3, handle info (1) 1
handle #2: 00000000000001f0 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn ssh: Function not implemented
fatal: unable to fork

What did you expect to occur after running these commands?
** pull latest repo changes **

What actually happened instead?
** error: cannot spawn ssh: Function not implemented
fatal: unable to fork ** #1475

**Comment by landstander668** [comment]
I'd suggest trying the [latest release](https://github.com/git-for-windows/git/releases/latest) (currently 2.21.0). Quite a number of items have been fixed since 2.16.2.

**Comment by dscho** [comment]
> Quite a number of items have been fixed since 2.16.2.

In particular this one ;-)

FWIW it has been reported [a couple of times](https://github.com/git-for-windows/git/issues?q=is%3Aissue+restrict+file+handles+is%3Aclosed) :-)
