### ISSUE TITLE
Installer locks up

### ISSUE THREAD

**Issue by CoderX71** [git-for-windows/git#2158]
The installer locks up as it reaches the end. Can't close it or minimise the installer, can only 'End Process' via Task Manager.

Only thing I changed in terms of installation options was the install path - A:\Git\

Using Windows v10
Installer: Git-2.21.0-64-bit.exe

$ git --version --build-options
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8

$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17134.706]

install-options.txt
Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

**Comment by dscho** [comment]
Thanks for editing the (really, really sparse) initial bug report.

This is still not enough information, though: have you tried running it with `/LOG=<file>`? How does your problem compare to https://github.com/git-for-windows/git/issues/1768 (i.e. is it a duplicate, really)?

**Comment by vtpeters** [comment]
I have the same issue.

At the end of the installation process the installation process of Git 2.21.0 (64-bit) on a Windows 8.1 64-bit machine the installation program seems to freeze.

When I opened the Task Manager at this point, I noticed that next to the actual installation process/program running there's another Git related background process active called "Git for Windows".

Terminate that backgrond process (NOT the installation process/program mind you) in the Task Manager seems to cause the installation process to be terminated normally. The "Completing the Git Setup Wizard" dialog appears and I can seelct the [Finish] button to finish the installation.

Hope this helps you find a solotion to solve this issue.

**Comment by the-j0k3r** [comment]
Hello.

I use chocolatey as a package manager on my dev machine, so this and other packages are updated all in one command.

I cant say I ever noticed any hung ups and works very well.

Maybe its something you may want t consider using instead of plain installer.

**Comment by kstrophus** [comment]
I have the same problem with Git 2.22 on Windows 7. It reaches the end and never completes.
