### ISSUE TITLE
"No such file or directory" if absolute path contains square brackets

### ISSUE THREAD

**Issue by ghost** [git-for-windows/git#2159]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.706]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

\---

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ ffprobe "/c/Users/Anon/Downloads/[2018] test/test.flac"
/c/Users/Anon/Downloads/[2018] test/test.flac: No such file or directory
```
 - What did you expect to occur after running these commands?

Get an output from ffprobe.

 - What actually happened instead?

The presence of square brackets makes it impossible for the program to find the file, apparently.

**Comment by PhilipOakley** [comment]
Maybe you are confusing plain _strings_ with _patterns_. In many places the thing you are typing is automatically a _regular expression_ pattern, not a simple search string. The `[]` are character selectors.

I've also been caught by that!

**Comment by leewdch** [comment]
I tried escaping the squares but without results

**Comment by PhilipOakley** [comment]
Hmm, but ffprobe isn't part of Git anyway. 

Isn't this a problem for `ffprobe` https://www.ffmpeg.org/ffprobe.html

**Comment by leewdch** [comment]
Running ffprobe in cmd.exe and Powershell gives no error, only in Git

**Comment by dscho** [comment]
>     * What commands did you run to trigger this issue? If you can provide a
>       [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
>       this will help us understand the issue.
> 
> 
> ```
> $ ffprobe "/c/Users/Anon/Downloads/[2018] test/test.flac"
> /c/Users/Anon/Downloads/[2018] test/test.flac: No such file or directory
> ```

As pointed out by @PhilipOakley, the `ffprobe` command is not part of Git.

You should therefore *in the least* provide a download URL to make that "MCVE" actually complete.

**Comment by rimrul** [comment]
Do you want to know whats happening? ffprobe expects a windows path, you're passing a unix path. Without the brackets, path conversion kicks in and passes a windows path to ffprobe. With the brackets our MSYS2 runtime skips path conversion.

https://github.com/git-for-windows/msys2-runtime/blob/master/winsup/cygwin/msys2_path_conv.cc#L372-374

You can trigger the same error for the path without brackets by prefixing you command with `MSYYS_NO_PATHCONV=1 `.

Try calling `ffprobe "c:/Users/Anon/Downloads/[2018] test/test.flac"` to get ffprobe to succeed with your brackets.

**Comment by leewdch** [comment]
Oh apparently if I drag and drop a file into the git bash it starts with `/c/` instead of `c:/`
I guess I'll have to check if input string are valid in my script. On a side note the same issue doesn't happen with ffmpeg, it accepts files in whatever path format. weird
