### ISSUE TITLE
rewrite commit, but push "everything up-to-date"

### ISSUE THREAD

**Issue by SnailDev** [git-for-windows/git#2165]
![image](https://user-images.githubusercontent.com/30819423/56495623-f0873200-6528-11e9-96f5-ceeffa695ff4.png)

![image](https://user-images.githubusercontent.com/30819423/56495655-0694f280-6529-11e9-839f-15cff66ba5e2.png)

I just want to delete big  file in the record and some one has the same problem on the comment at [this article](https://www.hollischuang.com/archives/1708).

**Comment by dscho** [comment]
This is neither a bug, nor a proper report. As you can easily see in the output of the screenshot (please refrain from taking screenshots of text, it is much harder to quote than if you had copy/pasted the text itself), there was a "WARNING: Ref 'refs/heads/master' is unchanged". So it is totally expected that the push does not have to do anything.
