### ISSUE TITLE
Merging the commit for deleted "File.txt" causes "file.txt" to be deleted

### ISSUE THREAD

**Issue by BryanLa** [git-for-windows/git#2167]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.21.0.windows.1, 64-bit
```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10, 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.437]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

**Steps:**
1. Create a new repo in a repo host (I'll use GitHub), and add 2 files:
    - File.txt
    - file.txt

2. Open the Git Bash console locally, and clone the new repo (`git clone https://github.com/<repo-path>`)
    - Note that the repo contains only the "file.txt" file

3. Go back to the repo host, and delete "File.txt"

4. Return to Git Bash, and run `git pull origin master`
    - Note that the commit for the deletion of "File.txt" is merged (shows in `git log`), but it causes  "file.txt" to be deleted.

 - What did you expect to occur after running these commands?

I would expect a "no op" in the working directory, where the commit is merged, but it doesn't cause "file.txt" to be deleted.

 - What actually happened instead?

The wrong file ("file.txt") was deleted. This occurs whether I set `ignorecase = true` or `ignorecase = false`. I can understand that Git might see "File.txt" as the same as "file.txt", given that Windows is case insensitive, but it seems like it should be able to differentiate that commit as being for a different file?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by tboegi** [comment]
>Note that the repo contains only the "file.txt" file
To be very exact:
The repo has both files,
 "git ls-files" will show both of them.
 
And yes, Windows treats file.txt and File.txt the same, and Git can't help you here.
(And changing core.ignorecase from true to false is never a good idea).

What does
"git status"
give you after the pull ?

**Comment by PhilipOakley** [comment]
As @tboegi noted this is a perennial Windows issue. 

While the underlying Git  is case sensitive (yes, you should have two files in your _repository_), the Windows FS is case insensitive so will happily overwrite one file with the other because as far as Windows is concerned, they have the same file name. Thus what you see in the worktree is just a single file.

There are a number of folks looking at the issue to give warnings or find soft workarounds, but 'it's tricky'. 

If you have a look through the open/closed issues you should find a few ideas and folks who you may be able to collaborate with to help the Git for Windows side of the Git project.

I'll close the issue at the moment. Though PRs are welcome.

**Comment by BryanLa** [comment]
@PhilipOakley, @tboegi - Thanks very much to both of you for your responses.

@tboegi - yes, sorry, to be more accurate, I should have said "Note that the *working tree* contains only the "file.txt" file.", after the `clone`. And thanks for the pointer to the `git ls-files` command. Running `git status` after the 'pull` shows a pending unstaged delete of "file.txt" :

Here's the full list of commands and output: 

```
bryanla@BRYANLA-SB2 MINGW64 /c/Git
$ git clone https://github.com/bryanla/case-test
Cloning into 'case-test'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'File.txt'
  'file.txt'

bryanla@BRYANLA-SB2 MINGW64 /c/Git
$ cd case-test

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ ls
file.txt  README.md

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git ls-files
File.txt
README.md
file.txt

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git pull origin master
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (2/2), done.
From https://github.com/bryanla/case-test
 * branch            master     -> FETCH_HEAD
   40aade7..83c3c7b  master     -> origin/master
Updating 40aade7..83c3c7b
Fast-forward
 File.txt | 1 -
 1 file changed, 1 deletion(-)
 delete mode 100644 File.txt

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    file.txt

no changes added to commit (use "git add" and/or "git commit -a")

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ ls
README.md

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git ls-files
README.md
file.txt

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git add -A

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git commit -m"case test"
[master 235f88e] case test
 1 file changed, 1 deletion(-)
 delete mode 100644 file.txt

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ ls
README.md

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git ls-files
README.md
```

I also ran another test using the same conditions, but added text to "File.txt" and "file.txt". Oddly, `git ls-files -m` shows "File.txt" as a "modified" file now, instead of "deleted". `git status` shows it as a tracked/"modified" file, not yet added to the index (even though it obviously does not exist in the working tree either), like its in limbo. Even more strange, after staging and attempting to commit, it returns the same tracked/"modified" status. Because of this, I couldn't test `git pull origin master`. Are these just anomolies, due to the case-sensitivity differences between Git and Windows?

Here's the same set of commands, using files with content in them:

```
bryanla@BRYANLA-SB2 MINGW64 /c/Git
$ git clone https://github.com/bryanla/case-test
Cloning into 'case-test'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'File.txt'
  'file.txt'

bryanla@BRYANLA-SB2 MINGW64 /c/Git
$ cd case-test

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   File.txt

no changes added to commit (use "git add" and/or "git commit -a")

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ ls
file.txt  README.md

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git ls-files
File.txt
README.md
file.txt

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git ls-files -m
File.txt

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git add -A

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git commit -m"attempt commit"
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
        modified:   File.txt

no changes added to commit

bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git pull origin master
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (2/2), done.
From https://github.com/bryanla/case-test
 * branch            master     -> FETCH_HEAD
   5fbe46a..863578b  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        File.txt
Please commit your changes or stash them before you merge.
Aborting
Updating 5fbe46a..863578b
```

I obviously don't understand this fully, but it still seems that since Git for Windows can differentiate the 2 files as they exist in the commit log, that it could detect the "File.txt" deletion and prevent "file.txt" from being deleted in the working tree. Perhaps this is where people are thinking a warning could be added, but I could see that this might add a lot of overhead (if it had to be checked for every delete commit).

If I clone the repo again (after I deleted the file), I can see the deletion commit:

```
bryanla@BRYANLA-SB2 MINGW64 /c/Git/case-test (master)
$ git log --stat
commit 863578b949a582e6d5570697f0e14338269d5c68 (HEAD -> master, origin/master, origin/HEAD)
Author: Bryan Lamos <bryanla>
Date:   Wed Apr 24 14:19:36 2019 -0700

    Delete File.txt

 File.txt | 1 -
 1 file changed, 1 deletion(-)

commit 5fbe46a6aacff28bf0f4fa9f0315435be9da6911
Author: Bryan Lamos <bryanla>
Date:   Wed Apr 24 14:16:10 2019 -0700

    Create file.txt

 file.txt | 1 +
 1 file changed, 1 insertion(+)

commit 45e27753ae15fb6902bbb91e42689e4d925961d7
Author: Bryan Lamos <bryanla>
Date:   Wed Apr 24 14:15:56 2019 -0700

    Create File.txt

 File.txt | 1 +
 1 file changed, 1 insertion(+)

commit 1f64b73901f60cf5cd75497fe6bfcc9a7f5adc56
Author: Bryan Lamos <bryanla>
Date:   Wed Apr 24 14:07:41 2019 -0700

    Initial commit

 README.md | 1 +
 1 file changed, 1 insertion(+)
```

I'll look through the issues again, as you suggested, but thanks again for your responses.

**Comment by tboegi** [comment]
Just a question from my side.
This text is intended to say it all:

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'File.txt'
  'file.txt'

**Comment by PhilipOakley** [comment]
Hi @tboegi  @BryanLa 

> Just a question from my side.   This text is intended to say it all:

Given the prompting, I scrolled back over Bryan's report and, while the report is long, I began to appreciate that the "warning:" is actually (in human factors terms) buried in a screed of text, without pause or separation, so easily missed by those _not expecting the problem_. (Human factors is an interesting subject as one starts to realise that there is a backward fool in the mirror;-).

It would be interesting if Bryan could say if he had seen the message, and appreciated it's significance at the time. Or whether it's now a 20:20 (ft) hindsight scenario.

One partial fix may be to add a separator blank line before the warnings (or errors, as seen toward the end of the `pull` messages, so blank separator front and back . For the warning I note that we book-end the file list with blank lines but not the "warning:" which is what we (initially) want users to pay attention to.

**Comment by BryanLa** [comment]
Hi @tboegi, @PhilipOakley - I think I need to rephrase my original concern...

Yes, I did see the warning, which I understand to mean only the "file.txt" file will be placed in the working tree, because Windows treats "file.txt" and "File.txt" as the same. And that's all good, and makes sense that Git would issue that warning.

As I stated in the original issue submission though, my concern is specific to the `pull`, which indicates a delete commit for the "File.txt" (ie: `delete mode 100644 File.txt`), but in reality, "file.txt" gets deleted from the working tree. The reason I posted this is because we have a very large repo with hundreds of contributors, that occasionally introduce duplicate filenames like this. But it's very hard to get them "out of the system" once they're introduced. And the behaviour I'm highlighting makes it more challenging, because the inadvertent deletion can go undetected (causing more issues). I really only wanted to raise awareness, and see whether this is a known issue (not the larger issue of filename casing, but the specific issue of the deletion of file A causing the deletion of file B).

Secondarily, in the example above where I did the same experiment, but had text in each file, the results got even more strange.

Anyway, I appreciate all of your responses, and I'll consider this closed and continue to monitor this queue.

**Comment by PhilipOakley** [comment]
Maybe the collision detection needs to be made available more widely as a config setting for such mixed environments (i.e. becomes a warning [that it's against policy] at the `git add` stage). I'm sure patches to that effect would be considered upstream.

The other option is some form of repo-cleaner to help with the policy issue, which records the canonical (chosen) spelling of such clashes. The other point is to highlight the fact that some practices don't work in the mixed environment (I've heard rumours of distinguishing between templates and filled files based on the initial capital, but have worked in Windows environments for too long, they are only hearsay)

**Comment by BryanLa** [comment]
Interesting ideas. If the policy could say "filenames must consist of this characters from this pattern", that would be extremly helpful, and stop the problem at the origin (assuming the policy comes down to each client once they clone). 

I've wondered about some type of "repo-cleaner" script as well, perhaps installed as a GitHub prereceive hook that could be enabled until the repo is clean. Or run as a local Git hook.

I also read a SO post where someone was able to use the Git sparse checkout feature, but that would only work as a reactive measure, once you know that specific filenames that have been introduced, I think. Another thought I need to explore is the Windows per-directory case sensitivity feature.
