### ISSUE TITLE
Building packages

### ISSUE THREAD

**Issue by bviktor** [git-for-windows/git#217]
This is more of a question about [rebuilding patched sources](https://github.com/git-for-windows/git/wiki/Package-management#build-packages-from-locally-patched-sources). After checking out MINGW-packages, going into mingw-w64-git and running

    makepkg-mingw --nobuild -s

I get 2 errors:

> ERROR: Cannot find the /usr/bin/git binary required for makepkg.

Git **is** in PATH, but under /mingw64/bin, but this command wants to run /usr/bin/git instead. It seems quite dumb to use an absolute path. My quickfix is:

    ln -s /mingw64/bin/git.exe /usr/bin/git.exe

Then it proceeds, but fails again soon:

> fatal: Unable to find remote helper for 'https'

This can be solved with:

    export PATH=${PATH}:/mingw64/libexec/git-core

Either I'm doing something wrong or the docs are incomplete. Or it may be a packaging error, even.

**Comment by dscho** [comment]
Oh, sorry! The problem is that we also need to install *MSys2* Git before we're able to build MINGW-packages whose sources are obtained through Git. So:

```bash
pacman -Sy git
```

(probably after removing the symbolic links to `git.exe` and `git-core`) should put you back on track.

**Comment by dscho** [comment]
By the way, I just changed `build-extra` so that the next version of the SDK installer will install that package by default.

**Comment by dscho** [comment]
Oh, and if it works for you, could you please report back and close the issue? Thanks.

**Comment by bviktor** [comment]
Sure, I'll get back to it ASAP.

**Comment by bviktor** [comment]
$ cd /usr/src
    $ rm -rf MINGW-packages
    $ git clone https://github.com/git-for-windows/MINGW-packages.git
    $ cd MINGW-packages
    $ makepkg-mingw --nobuild -s
    $ ==> ERROR: PKGBUILD does not exist.

**Comment by dscho** [comment]
@bviktor which project do you want to build? The projects all live in subdirectories of `MINGW-packages`. Git, for example, lives in `mingw-w64-git`.

**Comment by bviktor** [comment]
Yeah, I forgot to `cd mingw-w64-git`, sorry.

So yeah, with `pacman -Sy git` it works and if I understand it correctly, it won't be needed in the next release anymore.

Thanks.

**Comment by dscho** [comment]
Awesome. Thank you for reporting this bug, I think with the fix for this bug we should be all set for the final Git SDK 1.0.0.
