### ISSUE TITLE
Git flow release start with hash code fails

### ISSUE THREAD

**Issue by mamejimenez** [git-for-windows/git#2176]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Windows 64 bit

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 professional 64-bit (version 6.1 build 7601 Service pack 1)

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using SourceTool also

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mjimenez@mp-lap-28 MINGW64 /c/Retrospect_backup/Git/tserver (develop)           
$ git flow release start v12.12.12.0 8c165e101d7b2d8f8e7bd6f73edc9a56c3e9c4cf   
Fatal: Base '8c165e101d7b2d8f8e7bd6f73edc9a56c3e9c4cf' needs to be a branch. It 
does not exist and is required.
```
 - What did you expect to occur after running these commands?

New branch named v12.12.12.0 NOTE!!! The above command works in git version 2.13.1.windows.2

 - What actually happened instead?

Fatal: Base '8c165e101d7b2d8f8e7bd6f73edc9a56c3e9c4cf' needs to be a branch. It 
does not exist and is required.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
This appears to be a `git flow` error, rather than a Git for Windows problem. However I've not used git flow so a bit more background to the command and its structure (web link?) may be required. 

The error message does sound direct, in that it is saying that it expected a branch name, not a sha1 value.

**Comment by mamejimenez** [comment]
Thank you for your speedy reply.  I agree, it may be more of a git flow issue than a git issue.  I have also logged the above issue to that venue (https://github.com/nvie/gitflow/issues/6444).

As per your request and for your own edification, this is the web link to the actual source code:

_https://github.com/nvie/gitflow/blob/develop/git-flow-release_ 

and here is the command syntax (excerpt from the source code):

_git flow release start [-F] <version> [<base>]_

Thanks again, please let me know if you do think it is a change in Git for Windows that caused Git Flow to not work with the later releases.

**Comment by mamejimenez** [comment]
Phillip, just one more tidbit of information -  Upon further investigation, Git flow seems to not have changed since 2012.

**Comment by PhilipOakley** [comment]
I couldn't see where the "needs to be a branch" message originates within the codebases.

Perhaps you could do some simple debugging by adding simple `echo` statements into the `git flow` code to see where it breaks. Given that you already have the setup that breaks, you are in the best position to at least find the breaking step.

**Comment by mamejimenez** [comment]
Thanks again Phillip.  The information regarding that you don't think git is emitting that message is very useful. 

Hopefully the git flow folks will respond to the ticket I opened and debug the issue as you suggested.  Unfortunately, my employer will surely frown upon me debugging git flow :) 

Thanks again!

**Comment by dscho** [comment]
Please note that @nvie apparently lacks the decency to mark the project that made him famous and that he has no intention of maintaining as truly dead. That's why we do not rely on the original git-flow (which is indeed full of bugs).

What we use is https://github.com/petervanderdoes/gitflow-avh/.

**Comment by mamejimenez** [comment]
Thanks @dscho . 

I opened the following:

https://github.com/petervanderdoes/gitflow-avh/issues/413

Regards

**Comment by dscho** [comment]
Closing this as stale.
