### ISSUE TITLE
Directory symlinks change to file symlinks after pushing and pulling from Git

### ISSUE THREAD

**Issue by JozefVdM** [git-for-windows/git#2177]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.15063]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
CMD
```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mklink /d wwb6\dante_lic_mac ..\dante_mac_fix\WWB_compressed_lic_info_files
dir
05/01/2019  07:45 AM    <SYMLINKD>     dante_lic_mac [..\dante_mac_fix\WWB_compressed_lic_info_files]
git add .
git push
git clone into new directory
```
 - What did you expect to occur after running these commands?
Directory symlink would still be a directory symlink.

 - What actually happened instead?

It changed to a file symlink:
> dir
> `05/01/2019  09:28 PM    <SYMLINK>      dante_lic_mac  ..\dante_mac_fix\WWB_compressed_lic_info_files`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No
More details here:
(https://stackoverflow.com/questions/55945881/directory-symlinks-change-to-file-symlinks-after-pushing-and-pulling-from-git)
Note: this appears to be the same issue as what was reported here:
https://github.com/git-for-windows/git/issues/1646
However, it was for Git 2.16 and has been Closed, and I'm running Git 2.21

**Comment by JozefVdM** [comment]
The symlinks that changed type from SYMLINKD to SYMLINK after a clone point to directories inside submodules. The root directory of a submodule is created when the container project is cloned, but the contents isn't pulled down until after the clone of the container project (where the symlinks live) has completed:

`git clone --recursive -c core.symlinks=true ssh://<server>:7999/<repo>`

It appears Windows does not recreate Directory symlinks when the target does not yet exist. It creates them of type File symlink instead. This DOES work from the Windows command line though (as it does in Linux):

`mklink /d symlink ..\<some non-existing directory>\<another non-existing directory>`

...works fine.

My current workaround is to simply delete and restore them:

```
$ find . -type l -delete
$ git checkout .
Updated 14 paths from the index
```
Would prefer a fix for this though.

**Comment by dscho** [comment]
Git's internal data model unfortunately has a very Unix-centric view of symbolic links. In Git for Windows, we work around that by trying to determine the type from the target (if it exists). That heuristic breaks in your case.

However, we recently introduced the feature where you can declare the symlink type in the `.gitattributes`: simply add a line to that file (or create that file with this line as contents if it does not yet exist):

```
symlink symlink=dir
```

Of course, you will want to add and commit this file.

**Comment by JozefVdM** [comment]
@dscho Thanks a lot. That's great news. However, I can't get that to work. I made the change and pushed it:
$ cat .gitattributes
symlink symlink=dir
A new clone still does not create those symlinks as of type directory.
Our version of Git:
$ git --version
git version 2.20.1.windows.1

Am I missing something?

**Comment by landstander668** [comment]
This is just a guess, as I haven't looked at the implementation, but my expectations is that you actually want something like:

    my_symlink_name symlink=dir

**Comment by dscho** [comment]
> This is just a guess, as I haven't looked at the implementation, but my expectations is that you actually want something like:
> 
> ```
> my_symlink_name symlink=dir
> ```

Indeed. I was modeling the `.gitattributes` line after this information:

> mklink /d symlink ..\<some non-existing directory>\<another non-existing directory>

The first column in `.gitattributes` is always a file name or file name pattern. See e.g. https://github.com/git/git/blob/master/.gitattributes

**Comment by JozefVdM** [comment]
Thanks guys - I feel really sheepish now :) 
That works great on a Windows 10 box running Git 2.21 (had to create 5 .gitattributes files)
It does not work on a Windows 7 box running Git 2.17. Which version of Git was this introduced in? Is it supposed to work on Windows 7?

**Comment by dscho** [comment]
> Which version of Git was this introduced in?

You can always look in the release notes (on the [web](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md) or in your installation's top-level directory as ReleaseNotes.html) . In this instance, it is v2.20.0: https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#changes-since-git-for-windows-v2191-oct-5th-2018

And yes, it is supposed to work on Windows 7, too.
