### ISSUE TITLE
After upgrading the SDK the terminal doesn't work

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#2188]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

[more or less]. https://github.com/git-for-windows/git/issues/1684 looks related but it's a year old, and this issue is new.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0
cpu: x86_64
no commit associated with this build
sizeof-long: 8
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.316]
```

I'm using git-sdk (this issue happens with both 32 and 64).

After upgrading to msys runtime 3.0.7-1, I have this error when executing msys2.exe, mingw32.exe or mingw64.exe:
```Error: Could not fork child process: There are no available terminals (-1).```

There is no shell, and pressing Enter closes the window.

Generating /etc/passwd and /etc/group as explained in https://github.com/git-for-windows/git/issues/1684 didn't solve it.

My user is in LDAP (enterprise environment).

**Comment by dscho** [comment]
Hmm. I never start this as `msys2.exe`, always as `git-bash.exe`... And that seems to work for me.

So I tried `msys2.exe`, and it still works for me... :-(

**Comment by orgads** [comment]
I can no longer reproduce. Possibly sign out and back in solved it (I don't remember if I did).
