### ISSUE TITLE
Tracking file content on files explicitly marked as Binary in that repo

### ISSUE THREAD

**Issue by Sduibek** [git-for-windows/git#219]
Using newest version of Git for Windows.

![diff_on_bin](https://cloud.githubusercontent.com/assets/11235930/8275899/72239860-1863-11e5-91f1-445403f7d185.png)

**Comment by shiftkey** [comment]
@Sduibek GitHub for Windows is a separate effort to this project.

Could you get in touch with GitHub support - support@github.com - so we can investigate this further?

**Comment by dscho** [comment]
Thanks, @shiftkey!

**Comment by Sduibek** [comment]
Will do, thank you both.
