### ISSUE TITLE
Awk not built for readline8.dll

### ISSUE THREAD

**Issue by magneticflux-** [git-for-windows/git#2193]
`gnupg` was just rebuilt with the new version of `readline` in https://github.com/git-for-windows/MSYS2-packages/commit/514b2cd2a96428eb133323b581a5d5f28689ae0f, which provides `readline8.dll`. `awk` also needs to be rebuilt to use the new version.

```
C:/msys64/usr/bin/awk.exe: error while loading shared libraries: msys-readline7.dll: cannot open shared object file: No such file or directory
```

Packages that need to be rebuilt are included in https://github.com/msys2/MSYS2-packages/commit/900eff24de37863ecb893ef930e0ab7e564bcab6

**Comment by dscho** [comment]
For the record: requests like this one are the reason why I cannot add "support for running Git for Windows in MSYS2" to my already too full plate.

**Comment by magneticflux-** [comment]
The reason I opened this issue was because I believe it affects users _not_ running inside MSYS2. I already use pacman's `IgnorePkg` directive to delay updates from upstream MSYS2 that are incompatible with Git for Windows's packages, but these packages aren't from upstream — they're all from Git for Windows's repository.

To summarize, these are the current versions that are in the Git for Windows repository:

- `readline-8.0.000-1`: https://github.com/git-for-windows/git-sdk-64/tree/9e331f29029cea4ce62b26cc6da979c6788e551b/var/lib/pacman/local/libreadline-8.0.000-1
- `gawk-4.3.1-2` (for readline7): https://github.com/git-for-windows/git-sdk-64/tree/9e331f29029cea4ce62b26cc6da979c6788e551b/var/lib/pacman/local/gawk-4.2.1-2
- `gnupg-2.2.15-2` (for readline8): https://github.com/git-for-windows/git-sdk-64/tree/9e331f29029cea4ce62b26cc6da979c6788e551b/var/lib/pacman/local/gnupg-2.2.15-2

With the current packages available solely from Git for Windows, either `gawk` or `gnupg` is broken.

**Comment by magneticflux-** [comment]
Closed by https://github.com/git-for-windows/MSYS2-packages/commit/ba83e8ba536bebc47ddc1adbbbdbf1f5b71e09bd

Thanks! ❤️

**Comment by dscho** [comment]
> I believe it affects users _not_ running inside MSYS2

Ah. Thanks for the concern, but I worked around that issue via https://github.com/git-for-windows/build-extra/commit/ee62dc7fb624d8203fd61c77da57c8c87eb8dfca
