### ISSUE TITLE
"objects directory does not exist" Error for Google repo tool on Windows 10, when referring local mirror with --reference option

### ISSUE THREAD

**Issue by hsinghweb** [git-for-windows/git#2194]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
    64-bit
```
$ git --version --build-options
C:\git-repo\test\mirror-testing\client>git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
    Windows 10 Enterprise LTSC, 64-bit

```
$ cmd.exe /c ver

C:\git-repo\test\mirror-testing\client>cmd.exe /c ver
Microsoft Windows [Version 10.0.17763.437]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?
 

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
C:\git-repo\test\mirror-testing\client>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
   Using git for window, with google repo tool on Windows 10.
   It also make use of python and below is the python version on windows:
```
  C:\git-repo\test\mirror-testing\client>python --version
  Python 2.7.16
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
    CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

[Below testing is done recently with repo version 1.25]

Google repo tool has been updated to support Windows OS. I am able to run basic commands like repo init and repo sync using repo tool on Windows (which makes use of MinGW Git on Windows). In my work I need to create a local mirror of a repository and then use it. repo tool works fine to create mirror repository.

Here are commands used to create mirror repository on local drive on Windows OS.
```
$ repo init -u <URL> -b <branch_name> -m <manifest_file_name> --mirror
$ repo sync --no-tags
```
The above commands create the mirror in local drive C:\git-repo\test\mirror-testing\mirror
But when I refer the above mirror to sync in other drive (C:\git-repo\test\mirror-testing\client) then it shows error.
```
Command:
$ repo init -u <URL> -b <Branch_name> -m <manifest_file_name> --reference="C:\git-repo\test\mirror-testing\mirror"

Error:
error: object directory C:/git-repo/test/mirror-testing/mirror/project/manifest.git/objects? does not exist; check .git/objects/info/alternates.
```

The above command creates alternates file in C:\git-repo\test\mirror-testing\client\project\manifest.git\objects\info\ directory and that file contains below path:
C:\git-repo\test\mirror-testing\mirror\project/manifest.git\objects

 - What did you expect to occur after running these commands?
   The git command should not fail because the mentioned objects directory actually exists.

**Comment by dscho** [comment]
Can you find a simpler reproducer that does not require `repo`? I am asking because we do not ship `repo` in Git for Windows (and therefore do not support it, either).
