### ISSUE TITLE
Backspace not working in sqlplus with bash.exe

### ISSUE THREAD

**Issue by n-tchen** [git-for-windows/git#2196]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

#### Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Tested with
  - PortableGit-2.21.0-64-bit from https://github.com/git-for-windows/git/releases and
  - 2.19.0 64bit bundled with cmder https://cmder.net/

#### $ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8

and

git version 2.19.0.windows.1
cpu: x86_64
built from commit: d96bb8bc6c636a8869140e860e72e7bdf64bd790
sizeof-long: 4
sizeof-size_t: 8

#### Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Enterprise 1803 64bit

#### $ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.706]

#### What options did you set as part of the installation? Or did you choose the defaults?

No installation-options because it's a portable version in both cases (PortableGit and cmder)

#### Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
I'm using bash.exe bundled with cmder, however, I also tested and have the same problem with a directly started bash.exe coming with PortableGit 2.21

#### What commands did you run to trigger this issue?

`<start bash.exe>`
`ssh user@host`
`sqlplus / as sysdba`
`<Backspace isn't deleting input inside sqlplus>`
(see screenshot)

![bash exe_sqlplus](https://user-images.githubusercontent.com/50628205/57753520-a985fa00-76ec-11e9-9490-7219929cf3e5.PNG)

#### What did you expect to occur after running these commands?
That Backspace deletes typed input also inside sqlplus

#### What actually happened instead?
Squares with  questionsmark inside are shown

Maybe helpful:
I also tested it with git-bash.exe, where is a similar but not identical problem. In this case ^? ist shown instead of deleting input, but this problem can be resolved with `stty erase ^?`. So i would already be happy, if bash.exe would act like git-bash.exe

**Comment by landstander668** [comment]
Sqlplus almost certainly isn't mintty-aware. Have you tried running it under `winpty`? As in:

    winpty sqlplus / as sysdba

**Comment by n-tchen** [comment]
Hi,
thanks for you repIy. I didn't know winpty till now and so I have not tried it before. I just downloaded it but I am not quite sure how you mean that I should use it.
As you can see above, I have to connect to a server (Oracle Linux) per SSH before I use sqlplus. After I started the winpty-agent I tried `winpty ssh user@host` and afterwards like described above which results in the same squares with a questionmark inside when I try to delete input inside sqlplus.

**Comment by landstander668** [comment]
For that, you'd probably have to use winpty for the ssh session itself (assuming that's the issue). So you'd do `winpty ssh user@host`.

The more I think about this, however, the more it sounds like the two systems simply disagree on which code is mapped to the backspace key. Try running `stty -a` both before and immediately after the ssh command... do they show something different for *erase*? My guess is that it will be mapped to **^?** on the local system, and **^H** on the remote box.

If so, you can tell the remote system to change its mapping to match yours by running `stty erase ^?` (substitute whatever value your local system shows if it's different), and the backspace key will most likely start working as expected.

**Comment by n-tchen** [comment]
Thanks once more for your reply. As I have written in my last comment, i already tried `winpty ssh user@host` with no change in behavior.

I now tried you `stty -a` suggestion:
Before ssh: `erase = ^?;`
After ssh: `erase = ^H;`
After sqlplus / as sysdba with `!stty -a`:  `erase = ^H;`

So you guessed correct and I tried `stty erase ^?`. This results in that backspace is _technically_ working, BUT the squares with a questionmark inside are still shown. Take a Look a the screenshot: I typed `!stty -bbb` hit three-times backspace to delete the three bs and typed `a ` and the command `!stty -a` is correctly processed
![stty_erase](https://user-images.githubusercontent.com/50628205/57910293-3f548d00-7885-11e9-93dc-2a915c6a1c2a.PNG)

**Comment by landstander668** [comment]
The only other thing which comes to my mind is that maybe the LANG environment variable is set differently between the local and remote systems. Or possibly TERM, although that seems less likely.

**Comment by dscho** [comment]
> Or possibly TERM, although that seems less likely.

That could actually be the problem: we avoid shipping most of the termcap, as it would add a substantial payload to the Git for Windows installer, and we only need very little in it.

The use case described in this ticket is safely outside the purview of Git for Windows, so I see little point in supporting it.

AFAIR Windows 10 1803 ships with a native OpenSSH (I could be wrong on this!), but that might be a safer bet than using Git for Windows' copy of it.

**Comment by n-tchen** [comment]
Of course you are right that this is outside what Git for Windows is meant for. But the bash.exe coming with it, so what I want to use - who else would be the correct "contact person" if not here?
And till now I thought that I'm already using Windows' OpenSSH (it is shipped with my version, yes), unfortunately i can't verify that until may 27th.

**Comment by n-tchen** [comment]
Hello again,
I'm back at work and got a hint from a colleague which actually solved the problem. Additional to ```stty erase ^?``` I simply had to set ```stty echoe``` and Backspace is deleting signs as expected. So the issue is solved for me. Maybe this is helpful for you guys at some other point.
Thanks again for your help!
