### ISSUE TITLE
git status reporting "working tree clean" even when EOLs differs

### ISSUE THREAD

**Issue by rysavyjan** [git-for-windows/git#2197]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0
cpu: x86_64
built from commit: 0fd7b8c613aaa24e6b80ed76e239b06da9ec006f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.503]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init
git config --local core.autocrlf true
git add .
git commit -m "init"
git status
copy /Y test.x test.txt
git status
git add test.txt
git status
```
 - What did you expect to occur after running these commands?

I expect the git status will report changed files (EOLs differs).

 - What actually happened instead?

git status is reporting "nothing to commit, working tree clean"

I understand there is one-time warning:
```
git add test.txt
warning: LF will be replaced by CRLF in test.txt.
The file will have its original line endings in your working directory
```
but it should be reported every time `git status' is called.
Otherwise, is there any other option to get information that files EOLs are different?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Testing files are attached. Unpack it and use mentioned commands.
[test.zip](https://github.com/git-for-windows/git/files/3193879/test.zip)

**Comment by PhilipOakley** [comment]
This is normal if you have the settings. 

Those canonical settings are set for mutual compatibility with different operating systems, and are set that text files, when placed into the repository, will be normalised to have LF endings. Then when those stored files are checked out into the worktree/filesystem, they will be given the appropriate endings for your system, which on Git for Windows is a CRLF ending.

Thus you are 'clean', you can exchange branches/files/this repo with others...

Have a look at https://git-scm.com/docs/gitattributes for the eol discussions. There is also a check routine that will tell you what you have in various places, which I've temporarily forgotten :doh:.

**Comment by petrsol** [comment]
I think rysavyjan reports something else.

When you have test.txt file with CRLF endings in working directory and try "git status", it reports: nothing to commit, working tree clean. That's OK.

Then you change endings from CRLF to LF in test.txt file and try "git status", it reports: Changes not staged for commit: modified: test.txt. That's also OK.

But then you stage changes: "git add ." and try "git status", it reports: nothing to commit, working tree clean. You probably expected it will report something like: Changes to be committed: modified: test.txt. The reason why there is nothing to commit is that it was only endings what was changed and test.txt is stored with LF endings in repository. So, message "nothing to commit" is OK, but message "working tree clean" is not OK because test.txt file is still changed, it has LF endings instead of original CRLF.

I think problem is that staging without need of commit changes state of working directory to clean - before staging it was not clean, "git status" reported: Changes not staged for commit: modified: test.txt.

When you delete test.txt file and restore it from index by "git checkout test.txt", you will get test.txt file with CRLF endings. Then "git status" reports: nothing to commit, working tree clean. That's OK again.

**Comment by PhilipOakley** [comment]
(I think) Both files are text because they do not contain nulls within the first 1k bytes (heuristic), so the test is a 'nothing to report' problem.

**Comment by rysavyjan** [comment]
There are situations when EOLs must be set in one specific mode. Maybe some Windows utility doesn't support LF EOLs. Maybe Git Bash for Windows doesn't support CRLF, etc.

What I'm suggesting that `git status` should report my working directory containing files with EOLs that doesn't adhere to my needs. Right now I found only two solutions how to fix such state:
delete files from working directory and checking them out or
```
git rm --cached -r .
git reset --hard
```

But how do I find out there are such files in the first place?
Maybe some switch to `git status` would help here...

**Comment by tboegi** [comment]
@rysavyjan rysavyjan :What does 
git ls-files --eol
give you?

**Comment by rysavyjan** [comment]
```
>git init
Initialized empty Git repository in E:/Work/Downloads/test/test/.git/

>git config --local core.autocrlf true

>git add .

>git commit -m "init"
[master (root-commit) cfd7a3a] init
 3 files changed, 5 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 test.txt
 create mode 100644 test.x

>git status
On branch master
nothing to commit, working tree clean

>git ls-files --eol
i/lf    w/crlf  attr/text=auto          .gitattributes
i/lf    w/crlf  attr/text=auto          test.txt
i/lf    w/lf    attr/-text              test.x

>copy /Y test.x test.txt
        1 file(s) copied.

>git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   test.txt

no changes added to commit (use "git add" and/or "git commit -a")

>git ls-files --eol
i/lf    w/crlf  attr/text=auto          .gitattributes
i/lf    w/lf    attr/text=auto          test.txt
i/lf    w/lf    attr/-text              test.x

>git add test.txt
warning: LF will be replaced by CRLF in test.txt.
The file will have its original line endings in your working directory

>git status
On branch master
nothing to commit, working tree clean

>git ls-files --eol
i/lf    w/crlf  attr/text=auto          .gitattributes
i/lf    w/lf    attr/text=auto          test.txt
i/lf    w/lf    attr/-text              test.x
```

**Comment by tboegi** [comment]
I probably miss that you use a .gitattributes file - which is good.
Does the
git ls-files --eol
help you.

**Comment by rysavyjan** [comment]
Unfortunately `git ls-files --eol` doesn't help. Imagine repository containing hundreds of files. Should we really implement software to parse `git ls-files --eol` output to detect files with wrong EOLs?

I still think that 'git status' (maybe with some option that could be put into configuration) should be able report files with this problem.

**Comment by tboegi** [comment]
In your listing I see
   # That is OK:
 i/lf    w/crlf  attr/text=auto          .gitattributes
   # That is OK:
 i/lf    w/lf    attr/text=auto          test.txt
   # That is OK:
   i/lf    w/lf    attr/-text              test.x

Probably it would be good to have a real example,
where the EOLs are messed up, and how you came there.

**Comment by petrsol** [comment]
But it is on Windows, where native EOL is CRLF not LF, so this is not OK (on Windows with text=auto, it should be: w/crlf):
i/lf w/lf attr/text=auto test.txt

Line "copy /Y test.x test.txt" is the point where EOLs are "accidentally" converted from CRLF to LF - in real world it is done by saving in not properly set text editor or by some utility (e.g. text formatting which forces LF EOLs).

**Comment by tboegi** [comment]
Then just grep for
"w/lf attr/text=auto"

**Comment by rysavyjan** [comment]
I think we finally understand each other.

Parsing output of `git ls-files --eol` doesn't look like proper (fast, robust, intuitive) solution.

It should really be reported by Git status instead of `nothing to commit, working tree clean`.

Maybe I'm asking in wrong place and should post it to the Git mailing list instead?

**Comment by tboegi** [comment]
There is actually one thing that we want to know.

"git status" says
no changes added to commit

This means that there is nothing (new) to commit.
"git status" is not (yet) about the wrong EOL in the working tree.
And adding this function will make "git status --eol" (or so) really slow.
Could you give us more information, what "git status" should produce ?

**Comment by rysavyjan** [comment]
We would like to list all files with wrong EOLs  - files that received warning during `git add`:
```
warning: CRLF will be replaced by LF in script.sh.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in test.txt.
The file will have its original line endings in your working directory
```
Note that I added a new rule to .gitattributes: `*.sh text eol=lf`, and added a new file `script.sh` containing CRLF.

```
git ls-files --eol
i/lf    w/crlf  attr/text=auto          .gitattributes
i/lf    w/crlf  attr/text eol=lf        script.sh
i/lf    w/lf    attr/text=auto          test.txt
i/lf    w/lf    attr/-text              test.x
```

It would be great if we can run git command, such as proposed `git status --eol` and receive following output:
```
The following files have wrong EOLs:
i/lf    w/crlf  attr/text eol=lf        script.sh
i/lf    w/lf    attr/text=auto          test.txt
```
