### ISSUE TITLE
SDK installer should have "reset" button for component selection

### ISSUE THREAD

**Issue by SamB** [git-for-windows/git#22]
I was just trying to figure out which components I wanted to install out of the dizzying array available, and after making some changes I wanted to start over because I wasn't sure exactly what I might have changed.  Unfortunately, there was no "reset to default" button available, and the window did not want to close.  I ended up having to kill the process tree to start over.

**Comment by dscho** [comment]
I am closing this because we decided to jump to MSys2 right ahead. Therefore, we won't have a `mingw-get`-based installer anymore, and thus this issue does not apply anymore.
