### ISSUE TITLE
git subtree pull is not merging all changes

### ISSUE THREAD

**Issue by dougclutter** [git-for-windows/git#2202]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.437]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cls
rem Test git subtree

set root=d:\git-test
set librepo=%root%\librepo
set uselibrepo=%root%\uselibrepo

rem Clean-up
cd \
rd /s /q %root%

rem Initialize repos
md %librepo%
cd /d %librepo%
git init
md %uselibrepo%
cd /d %uselibrepo%
git init

rem Add files to librepo
cd /d %librepo%
echo Hi >fileInRoot.txt
md lib
cd lib
echo Mom >fileInLib.txt
cd..
git add fileInRoot.txt
git add lib\fileInLib.txt
git commit -m "Initial files in repo with lib"

rem Add files to uselibrepo
cd /d %uselibrepo%
echo Excellent>file1.txt
git add file1.txt
git commit -m "Initial files in repo that will have lib subtree"

rem Add subtree to uselibrepo
cd /d %librepo%
git subtree push --prefix=lib %uselibrepo% libBranch
cd /d %uselibrepo%
git subtree add --prefix=lib %uselibrepo% libBranch
git branch -D libBranch

rem Add/change files in lib
cd /d %librepo%\lib
echo Dad >fileInLib.txt
echo Adventure >anotherLib.txt
git add anotherLib.txt
git commit -m "Updates to lib in original location"

rem Share changes
cd /d %librepo%
git subtree push --prefix=lib %uselibrepo% libBranch
cd /d %uselibrepo%
git subtree pull --prefix=lib %uselibrepo% libBranch
git branch -D libBranch

rem New file is found in both places
type %librepo%\lib\anotherLib.txt
type %uselibrepo%\lib\anotherLib.txt

rem Changed file is NOT the same in both places
type %librepo%\lib\fileInLib.txt
type %uselibrepo%\lib\fileInLib.txt
```
 - What did you expect to occur after running these commands?

Expected both lib folders to be the same.

 - What actually happened instead?

1) The added file was added as expected.
2) The changed file was not changed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

Also posted to [stackoverflow](https://stackoverflow.com/questions/56225465/are-the-git-subtree-commands-broken-in-windows) but I got no response.

Here is a copy of the batch file shown above [gitSubtreeChangeInUseLib.bat.txt](https://github.com/git-for-windows/git/files/3208901/gitSubtreeChangeInUseLib.bat.txt).

If you don't have a D: drive, you may want to change this line **set root=d:\git-test** to a folder where the test can be run.

**Comment by dscho** [comment]
Would you have a chance to try this in Linux (e.g. via WSL), just to make sure that this is a Windows-specific issue?

**Comment by dougclutter** [comment]
Converted the script to Linux and ran it via WSL/Ubuntu and it looks like this is *not* specific to Windows. Reported it via the community mailing list.

**Comment by dscho** [comment]
@dougclutter good! Do you want to keep this ticket open? Probably not, as the discussion should continue on the Git mailing list (https://public-inbox.org/git/DM5PR2201MB10819C1E74000E91B09F157982100@DM5PR2201MB1081.namprd22.prod.outlook.com/#r), right?

**Comment by dougclutter** [comment]
I agree. I'll close this issue. Thanks!
