### ISSUE TITLE
git describe --tags --abbrev=0 fails when used in cmd `for` construct

### ISSUE THREAD

**Issue by chrisbra** [git-for-windows/git#2204]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64bit
```
$ git --version --build-options

c:\Temp\vim>git --version --build-options
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.765]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

c:\Temp\vim>type "c:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a

I am trying to get the result of `git describe --tags --abbrev=0` and parse the output in a batch script. 

```
c:\Temp\vim>git describe --tags --abbrev=0
v8.1.1364

c:\Temp\vim>for /f "delims=. tokens=1-3 usebackq" %i in (`git describe --tags --abbrev=0`) do set PATCHLEVEL=%k
fatal: Not a valid object name 0

c:\Temp\vim>for /f "delims=. tokens=1-3 usebackq" %i in (`git describe --tags `) do set PATCHLEVEL=%k

c:\Temp\vim>set PATCHLEVEL=1364
```

BTW: doesn't make a difference whether one uses `usebackq` or not (and then put the command in single quotes).

 - What did you expect to occur after running these commands?

get the latest tag from the vim repository, even if the latest commit has not been directly tagged. 

 - What actually happened instead?

see above, I get the output `fatal: not a valid object name`.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/vim/vim but looks like this should be fairly easy reproducible with any other repository.

**Comment by dscho** [comment]
> for /f "delims=. tokens=1-3 usebackq" %i in (`git describe --tags --abbrev=0`) do set PATCHLEVEL=%k

First of all, I assume that `%k` is a typo... as only `%i` is assigned.

Anyways, it seems as if the `=` is substituted with a space by CMD. Try escaping it with a caret:

```cmd
for /f "delims=. tokens=1-3 usebackq" %i in (`git describe --tags --abbrev^=0`) do set PATCHLEVEL=%k
```

**Comment by chrisbra** [comment]
> First of all, I assume that %k is a typo... as only %i is assigned.

no that is correct. `%i` will be the first field, `%j` the second and `%k` the third, which is the patchlevel and that was what I was looking for.

> Anyways, it seems as if the = is substituted with a space by CMD. Try escaping it with a caret:

Indeed that was what I was missing. Sorry, should have tried that earlier, but didn't even think about that.

**Comment by dscho** [comment]
FWIW I found out by setting `GIT_TRACE=1`. That's a very useful tool in the toolbox to use when diagnosing such issues.
