### ISSUE TITLE
The git filter-branch rewrite history over a range of commits did not work

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#2206]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.503]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue. 

I am trying to re-write the history over a range of commits according  https://stackoverflow.com/questions/15250070/running-filter-branch-over-a-range-of-commits
```
GIT_TRACE=1 GCM_TRACE=1 git filter-branch --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"' ... 67d9d9..f70bf4
```
 - What did you expect to occur after running these commands?

rewrite the history from commit 9c1580 to commit f70bf4, make the commit date same as  date.

 - What actually happened instead?

Found nothing to rewrite

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

You can clone the following repository and switch to branch **temp** 
https://github.com/chucklu/LeetCode/
The commit 67d9d9 is the common parent commit of branch temp and branch master
The commit f70bf4 is the commit which branch temp points to
![image](https://user-images.githubusercontent.com/3004057/58372142-151d6200-7f4c-11e9-82e5-366dc0c962d1.png)

**Comment by dscho** [comment]
Just to make sure: does this *also* fail in WSL?

**Comment by chucklu** [comment]
@dscho What did you mean by "WSL"? I am using the git bash of "git for windows".

**Comment by chucklu** [comment]
Did you mean Windows Subsystem for Linux?
https://docs.microsoft.com/en-us/windows/wsl/about
I can try to install it

**Comment by chucklu** [comment]
@dscho The same operation failed in WSL with "**Found nothing to rewrite**"
![image](https://user-images.githubusercontent.com/3004057/58376316-ee3a4c80-7f9a-11e9-9c55-79b43d9970ff.png)

**Comment by siprbaum** [comment]
@chucklu I am wondering what the three dots at the end of your command means. 
Quoting your commandline

> ```
> GIT_TRACE=1 GCM_TRACE=1 git filter-branch --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"' ... 67d9d9..f70bf4
> ```

I think you probably meant `--` here instead of `...`, like in the following command
```
GIT_TRACE=1 GCM_TRACE=1 git filter-branch --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"' -- 67d9d9..f70bf4
```

**Comment by chucklu** [comment]
@siprbaum  You can check the official documentation https://git-scm.com/docs/git-filter-branch about the three dots

> To restrict rewriting to only part of the history, specify a revision range in addition to the new branch name. The new branch name will point to the top-most revision that a git rev-list of this range will print.
> 
> Consider this history:
> 
>      D--E--F--G--H
>     /     /
> A--B-----C
> To rewrite only commits D,E,F,G,H, but leave A, B and C alone, use:
> 
> git filter-branch ... C..H
> To rewrite commits E,F,G,H, use one of these:
> 
> git filter-branch ... C..H --not D
> git filter-branch ... D..H --not C


I tried as your recommendation replace ... with --
And I got error "You must specify a ref to rewrite."

**Comment by dscho** [comment]
> git filter-branch ... C..H

I think that this is an unfortunate inconsistency in the documentation. Here, from what I know, the `...` clearly stands for "any option you might want to pass".

So I could imagine that you simply want to delete the three dots, as you already substituted them with your env filter.

If you *really* want to pass a `--`, then I am fairly certain that the commit range needs to come *before* it, *not afterwards*.

**Comment by dscho** [comment]
> The same operation failed in WSL with "**Found nothing to rewrite**"

Okay, I'll mark it as "question" and "git upstream". If there is a bug in Git underlying the reported issue, then it is clearly not specific to Windows.

**Comment by chucklu** [comment]
@dscho  I will ask help with git community through git@vger.kernel.org, and back to here later.

**Comment by chucklu** [comment]
@dscho  Could you help me send a report to git@vger.kernel.org? I have tried to send an email and was rejected by the email server.

> host vger.kernel.org[209.132.180.67] said: 553 5.7.1 Hello [59.36.132.77], for MAIL FROM address access is denied by the policy analysis functions. (in reply to MAIL FROM command)

**Comment by chucklu** [comment]
@dscho I have tired to send the email with my work email which under office 365 successfully.
Please ignore the above request, thanks.

**Comment by chucklu** [comment]
@dscho  Send email to git@vger.kernel.org failed again, could you do it for me?
I already tried to send the email with plain text, I add the url as plain text in email. I am not sure why it was recognized as html .
> The original message was received at Mon, 27 May 2019 05:56:33 GMT from m0118687.ppops.net [127.0.0.1]
> 
>    ----- The following addresses had permanent fatal errors ----- <git@vger.kernel.org>
>     (reason: 550 5.7.1 Content-Policy reject msg: The message contains HTML subpart, therefore we consider it SPAM or Outlook Virus.  TEXT/PLAIN is accepted.! BF:<U 0.5>; S1725940AbfE0HO2)
> 
>    ----- Transcript of session follows ----- ... while talking to vger.kernel.org.:
> >>> DATA
> <<< 550 5.7.1 Content-Policy reject msg: The message contains HTML subpart, therefore we consider it SPAM or Outlook Virus.  TEXT/PLAIN is accepted.! BF:<U 0.5>; S1725940AbfE0HO2
> 554 5.0.0 Service unavailable
>

**Comment by chucklu** [comment]
I have sent 4 emails to git@vger.kernel.org, I got two rejected html part .
It seems I send 2 emails successfully, it's painful to send the email to git@vger.kernel.org .
![image](https://user-images.githubusercontent.com/3004057/58409752-51170b00-80a3-11e9-909c-78abbc38239f.png)

**Comment by PhilipOakley** [comment]
@chucklu 

It's this part that is the 'cause'. It also makes the list archive small ;-)

> The message contains HTML subpart, therefore we consider it SPAM or Outlook Virus. TEXT/PLAIN is accepted.

Make sure you locate the settings part of Outlook that allows you to send emails to git@vger.kernel.org  as enforced plain text (I don't have outlook any more, so can't give details)

**Comment by chucklu** [comment]
@PhilipOakley  I tried with Plain text in outlook for the last sent email, hope they can receive my email.
![image](https://user-images.githubusercontent.com/3004057/58410948-d3083380-80a5-11e9-98db-29949a5d7d81.png)

**Comment by PhilipOakley** [comment]
it has shown up here https://public-inbox.org/git/DB7PR05MB5573349C498A5680A5133F1A8D1D0@DB7PR05MB5573.eurprd05.prod.outlook.com/

**Comment by chucklu** [comment]
@PhilipOakley  Thanks, I don't know how to reply the email I received.
In outlook, when I click the reply button, it was automatically using the top-posting.
Shoud I add > and >> or >>> by myself manually?
![image](https://user-images.githubusercontent.com/3004057/58451687-18c90880-8147-11e9-88bb-3074f34b0596.png)

**Comment by dscho** [comment]
@chucklu maybe https://www.lifewire.com/outlook-plain-text-message-1165895 helps?

**Comment by dscho** [comment]
(I see you already found it...)

**Comment by chucklu** [comment]
@dscho  Thanks, finally I tried with this solution
https://support.office.com/en-ie/article/reply-with-inline-comments-within-the-original-message-text-5bc44105-aeb2-49e2-8239-5aeeff52e5a7

Although it still looks weird compare to others, https://public-inbox.org/git/DB7PR05MB5573B5FC17FD1F221F7AAD558D1E0@DB7PR05MB5573.eurprd05.prod.outlook.com/

**Comment by chucklu** [comment]
Finally I works out the solution, I need use branch instead of commit id to do the git filter-branch.
The old command

> git filter-branch --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"' ... 67d9d9..f70bf4

Create a new branch temp2 point to 67d9d9 and switch to temp branch(point to f70bf4), then it works.

> git filter-branch --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"' temp2..temp

**Comment by chucklu** [comment]
The ... should be removed

**Comment by dscho** [comment]
> The ... should be removed

How about contributing that patch? That would be a neat way to say "thank you" to the Git project.

**Comment by chucklu** [comment]
@dscho  I would like to help to improve the documentation as I mentioned https://public-inbox.org/git/DB7PR05MB5573AD00490304E00CF6649D8D1F0@DB7PR05MB5573.eurprd05.prod.outlook.com/
As @PhilipOakley  mentioned in mailing  list before, the ... is confused, because the documentation did not explain it. I first think it's literally.
Here is what @PhilipOakley  mentioned :
> The three dots is provided in the literal EXAMPLES section of the man 
> page. That is probably an error, as I think it is meant to be an 
> ellipsis to indicate 'insert other options here'.
> 
> Simply remove the three dots ('symmetric diff notation') .
> 
> Not sure what the correct change to the man page should be, but clearly 
> it has caused confusion. It also takes a moment to properly realize 
> which commits the two dot notation will refer to in the example which 
> may further compound the confusion about the three dots.

I am not sure how to write the documentation correctly to make it clear for others to understand it easily.

Following your advice, I find the documentation and how submit patches guideline.
https://github.com/git/git/blob/master/Documentation/git-filter-branch.txt
https://github.com/git/git/blob/master/Documentation/SubmittingPatches

**Comment by chucklu** [comment]
@dscho By the way, I have pointed out a bug that the commits range with commit id can not be recognized by git filter-branch in mailing list,  but nobody replies.

**Comment by PhilipOakley** [comment]
Hi @chucklu - Would you be willing to have a go at the documentation update?

Go to the https://gitforwindows.org/ page, and click the 'contribute' button to get the the right section.

Read, scrolling down, select the "Download Git for Windows SDK". This should install a full environment (with tools) to allow you to (create a branch and then) edit the C:\git-sdk-64\usr\src\git\Documentation\git-filter-branch.txt file. 

See the CodingGuidelines and SubmittingPatches files for extra guidance.

Use format-patch and send-email to push the patches to upstream, or use a PR to get reviews and guidance here.

It will feel scary, but it's actually painless. Any comments are to help the code and text be better and never about the contributor (though it may not immediately feel like that, because _my code is personal_... 😃 [e.g.](https://public-inbox.org/git/xmqq5zpuel4m.fsf@gitster-ct.c.googlers.com/))

Given that _this_ author (@chucklu) found that the dual use of three dots (ellisis vs symmetric diff) notation was very confusing - see _my_ example..

**Comment by chucklu** [comment]
@PhilipOakley @dscho  Thanks for your encouragement, I will try to do it this weekend.

**Comment by dscho** [comment]
> I have pointed out a bug that the commits range with commit id can not be recognized by git filter-branch in mailing list, but nobody replies.

I guess that most people are busy with preparing for Git v2.22.0 right now (including me).

What you pointed out is that providing a commit range with commit hashes does not update the corresponding branch. This is actually intentional, as you did not specify the branch *explicitly*. There could even be multiple branches pointing at the tip commit that is referenced in the commit range, and then the question would be: which branch to update? All of them? One? None?

And finally, it is more common that *no* branch points at any given tip commit; you can still call `filter-branch` on arbitrary commit ranges  that have no relationship with any local branch. That's actually a feature ;-)

> Use format-patch and send-email to push the patches to upstream, or use a PR to get reviews and guidance here.

You can also use [GitGitGadget](https://gitgitgadget.github.io).

Since the Git mailing list can be a bit intimidating, and since the Git for Windows project may feel a bit less intimidating, you can also open a PR here, and I will shepherd it to the Git mailing list once we settled on a final version.

Just make sure that your commit message is in a similar form of the latest commits changing the file in question.

Oh yeah, the file in question would be [`Documentation/git-filter-branch.txt`](https://github.com/git-for-windows/git/blob/master/Documentation/git-filter-branch.txt). And the commit history in which to look for examples is here: https://github.com/git-for-windows/git/commits/master/Documentation/git-filter-branch.txt (I think [this commit](https://github.com/git-for-windows/git/commit/07c4984508865984fdfdedf2e1cdf86328221af4#diff-3dfd4f4f5b4bc8cfc987b64bb7f6ebfb) is a good example to follow).

> I am not sure how to write the documentation correctly to make it clear for others to understand it easily.

I hear you. Speaking for myself, when I started contributing to Git, I found writing documentation *harder* than writing the code, and I found writing good commit messages harder, still. Fast-forward a good 10 years of practice, and people start looking at me for advice on writing these things 🙀 

Seriously again, just start writing. And if you're not satisfied with your first version, rest assured that other contributors (e.g. _me_) often have to re-write a dozen times or more to be satisfied with the end result.

Also, you're not alone. Just propose something, and I am sure @PhilipOakley (or other native speakers) will chime in and help you come up with the best solution we can produce together.

**Comment by chucklu** [comment]
I find an explanation on stackoverflow
https://stackoverflow.com/questions/15250070/running-filter-branch-over-a-range-of-commits

> git filter-branch does accept range notation, **but the end of the range needs to be a reference**, not the ID of a commit.
> 
> git checkout -b tofilter commitb
> git filter-branch .... commita..tofilter
> 
> If given just commits, **it would not know what ref to update with the filtered branch**.

**Comment by PhilipOakley** [comment]
> git filter-branch does accept range notation, but the end of the range needs to be a reference, not the ID of a commit.

> git filter-branch .... commita..tofilter

> If given just commits, it would not know what ref to update with the filtered branch.

Is this worth, in your opinion as the reader/user, a short documentation update to clarify that point? 

If so, you could prepare a simple patch to help others (and reduce the maintenance burden).

**Comment by chucklu** [comment]
@PhilipOakley  I have read the official documentation  again, and search with ref, then I find

> The command will only rewrite the positive **refs** mentioned in the command line (e.g. if you pass a..b, only b will be rewritten).

The above sentence should be emphasized with red color, and the refs should with bold style(maybe a link about the definition of refs would be better).

I have read the standard about how to contribute the git, It really scarred me.  It's much more complicated than pull requests on github.

**Comment by dscho** [comment]
> I have read the standard about how to contribute the git, It really scarred me. It's much more complicated than pull requests on github.

Lucky you: Git for Windows accepts Pull Requests.

**Comment by PhilipOakley** [comment]
@chucklu 

> Git for Windows accepts Pull Requests.

It also helps make sure your contribution is captured.

I'm not sure that 'red' (colours) are available in the doc system. You may want to adjust the line spacing, and text marking (bold etc), or add an extra comment as per your 'e.g.' (the one in brackets) to create the emphasis.

Point out (in the commit message) that people do pick up on these 'hold on a moment' type comments much more than the 'yada yada yada' positive flowing narrative when it comes to making errors and mistakes. e.g. ["Human Error"](https://www.amazon.co.uk/Human-Error-James-Reason/dp/0521314194)
