### ISSUE TITLE
patch not deployed

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#221]
patch executable is missing in the release candidate.

**Comment by dscho** [comment]
`patch.exe` is not required by any of Git's components.

**Comment by orgads** [comment]
That may be right, but it occurred to me a few times that git apply/am failed, and I needed to apply a patch manually. It is useful, why not include it?

**Comment by dscho** [comment]
To clarify: *Git for Windows*' installer really only wants to ship the components necessary to run Git. If you are more of a power user, you are expected to be able to install and use MSys2 (or the Git SDK) which comes with a variety of optional packages.

**Comment by orgads** [comment]
Please reconsider:

* Patch is used by Qt Creator for reverting changes. Removing it from Git distribution required supporting [Git as a patch tool](https://codereview.qt-project.org/124425), which is implicit.
* The size of patch is really small: Total Installed Size:  0.15 MiB
* It is shipped with msysGit 1.x, so excluding it now possibly breaks other user scripts/habits.

**Comment by dscho** [comment]
@orgads if you open one of your outstanding Pull Requests, I will merge it.
