### ISSUE TITLE
`--rebase-merges` progress indicator (number of actions todo) could surprise folks.

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#2212]
from ref https://github.com/git-for-windows/git/pull/2148#issuecomment-481650187 (todo list generates ~500+ patches)

What was meant to be a simple rebase, with merges, created a mega todo list. The apparent quantity surprised me. 

As a future improvement (#leftoverbits), the progress indicator could split the actions into two groups to make the indication more palatable, match expectations, and be more informative (three ways of saying the same thing).

from #2148 
> Then I went and looked again at the range diff number ((254 patches), the values look a lot more sensible. Plus I had a brain-knot in miss-thinking what needed learning by the rerere trainer.

> So the root cause was that the merging-rebase does claim a count of more instructions than commits, which confused this mk1 brain.

Maybe (long term thought), for the _new_ `--rebase-merges`, we maybe should 'improve' the rebase progress summary to distinguish the number of classical 'commits' to be handled (picked..), from the 'other' (new style) actions (label, reset, merges..), so that the numbers doesn't panic folks...

This was W10, with v2.21.

**Comment by dscho** [comment]
Closing this stale ticket.
