### ISSUE TITLE
Fail to git clone with 'BUG: refs/files-backend.c:2926: initial ref transaction called with existing refs''

### ISSUE THREAD

**Issue by JeanZhao** [git-for-windows/git#2213]
The git version: (I downloaded from [Website homepage](https://gitforwindows.org/) for my Windows 10 system)
> git --version
git version 2.21.0.windows.1

When I try to clone remote repository code, it crashes with the following error info?
=========================================================
Cloning into 'cc'...
remote: Counting objects: 99440, done.
remote: Compressing objects: 100% (27577/27577), done.
remote: Total 99440 (delta 46717), reused 95544 (delta 44556)
Receiving objects: 100% (99440/99440), 22.18 MiB | 32.92 MiB/s, done.
Resolving deltas: 100% (46717/46717), done.
BUG: refs/files-backend.c:2926: initial ref transaction called with existing refs

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
========================================================

 I'm not sure what happened?  Or could you provide older releases please? I could not find where the lower version releases let me try.

Thanks in advance.

**Comment by PhilipOakley** [comment]
Quick reply: I think this is a variant of https://public-inbox.org/git/CAFQ2z_O7rupGS4rntiUwJCHUj3bO0U88bVAToveEo_uU0Eu96w@mail.gmail.com/ 

I think it has been looked at very recently, but please do add your  bug report to the developer list as well (it only accepts 'plain text' - all emails containing HTML is rejected as spam). 

The next release is due imminently ([currently at -rc3](https://public-inbox.org/git/xmqqlfyito3a.fsf@gitster-ct.c.googlers.com/)), so it may not be fixed in the new version - see the threads.

**Comment by dscho** [comment]
> I think this is a variant of https://public-inbox.org/git/CAFQ2z_O7rupGS4rntiUwJCHUj3bO0U88bVAToveEo_uU0Eu96w@mail.gmail.com/

I don't think this is a variant of that bug... it looks *very* different.

@JeanZhao would you mind giving https://github.com/git-for-windows/git/releases/tag/v2.22.0-rc3.windows.1 a try?

If it still does not work, *maybe* (and only if you and me work well together) we can slip in a fix into v2.22.0, still.

**Comment by dscho** [comment]
> refs/files-backend.c:2926

The comment above [that line](https://github.com/git-for-windows/git/blob/v2.21.0.windows.1/refs/files-backend.c#L2926) says:

```c
	/*
	 * It's really undefined to call this function in an active
	 * repository or when there are existing references: we are
	 * only locking and changing packed-refs, so (1) any
	 * simultaneous processes might try to change a reference at
	 * the same time we do, and (2) any existing loose versions of
	 * the references that we are setting would have precedence
	 * over our values. But some remote helpers create the remote
	 * "HEAD" and "master" branches before calling this function,
	 * so here we really only check that none of the references
	 * that we are creating already exists.
	 */
```

So I must ask a couple of questions:

- is there *any* hook installed via e.g. Git templates?
- could you re-run this with `GIT_TRACE=1`?
- is `cc` a public repository that I can clone myself, to try to reproduce?
- if it is not, does this happen for *any* public repository for you?

And to answer _your_ questions, @JeanZhao:

> I'm not sure what happened?

Neither am I. There sure has not been any mention on the Git mailing list of this particular error message.

> Or could you provide older releases please?

Absolutely. Here you go: https://github.com/git-for-windows/git/releases

> I could not find where the lower version releases let me try.

Thank you so much!

Oh, and by the way:

> 32.92 MiB/s, done.

You have a seriously wicked fast network over there. I'm jealous 😺

**Comment by JeanZhao** [comment]
Amazing! Thanks all for such a quick reply. I would try what you provided here again as soon as possible when I’m at office.




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            jeanzhao
                            
                            
                                
                                    邮箱：jeanzhao@aliyun.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 06/04/2019 20:16, Johannes Schindelin wrote: 
I think this is a variant of https://public-inbox.org/git/CAFQ2z_O7rupGS4rntiUwJCHUj3bO0U88bVAToveEo_uU0Eu96w@mail.gmail.com/

I don't think this is a variant of that bug... it looks very different.
@JeanZhao would you mind giving https://github.com/git-for-windows/git/releases/tag/v2.22.0-rc3.windows.1 a try?
If it still does not work, maybe (and only if you and me work well together) we can slip in a fix into v2.22.0, still.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/git-for-windows/git/issues/2213?email_source=notifications\u0026email_token=AJJK2CZ2KKGVTC66YZOA6SDPYZMIPA5CNFSM4HS3MJ6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4L2SI#issuecomment-498646345",
"url": "https://github.com/git-for-windows/git/issues/2213?email_source=notifications\u0026email_token=AJJK2CZ2KKGVTC66YZOA6SDPYZMIPA5CNFSM4HS3MJ6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4L2SI#issuecomment-498646345",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JeanZhao** [comment]
`is there any hook installed via e.g. Git templates?`
Sorry, I'm a new member of this git group. So I'm not sure the detailed code structure.

` - could you re-run this with GIT_TRACE=1?`
Okay.
 `- is cc a public repository that I can clone myself, to try to reproduce? if it is not, does this happen for any public repository for you?`
Sorry, currently, it is still not published now. However, my colleagues don't have such problems with  v2.20.1.windows.1 on Mac system...


Thanks a lot for providing different releases let me try. After trying several times with (vv2.22.0-rc3.windows.1, v2.21.0.windows.1, v2.20.1.windows.1) , I found that it doesn't always occur.

Case 1: trying above releases with windows powershell,
it seems everything is ok. Files are successfully cloned.

Case 2: trying above releases with windows cmd,
it seems everything is ok. Files are successfully cloned.

Case 3: trying above releases with VScode, (while set  "terminal.integrated.shell.windows" 
 as "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" or "C:\\Windows\\System32\\cmd.exe"),
Sometimes, it occurs.
Log while setting terminal as 'powershell' is here,
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 D:\Jean\workspace\test_git> git clone <remote git template>
10:14:53.803874 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:14:53.803874 git.c:439               trace: built-in: git clone <remote git template>
Cloning into <some directory address>...
10:14:53.822925 run-command.c:663       trace: run_command: git remote-http origin <remote git template>
10:14:53.833955 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:14:53.835961 git.c:704               trace: exec: git-remote-http origin <remote git template>
10:14:53.835961 run-command.c:663       trace: run_command: git-remote-http origin <remote git template>
10:14:53.847993 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:14:53.865119 run-command.c:663       trace: run_command: 'git credential-manager get'
10:14:53.909158 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:14:53.910161 git.c:704               trace: exec: git-credential-manager get
10:14:53.910161 run-command.c:663       trace: run_command: git-credential-manager get
10:14:54.145673 run-command.c:663       trace: run_command: 'git credential-manager store'
10:14:54.202336 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:14:54.203340 git.c:704               trace: exec: git-credential-manager store
10:14:54.203340 run-command.c:663       trace: run_command: git-credential-manager store
10:14:54.427375 run-command.c:663       trace: run_command: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning <remote git template>
10:14:54.444420 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:14:54.446430 git.c:439               trace: built-in: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning <remote git template>
remote: Counting objects: 99461, done.
remote: Compressing objects: 100% (27590/27590), done.
10:14:54.482523 run-command.c:663       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 228 on BG392906' --check-self-contained-and-connected --pack_header=2,99461
10:14:54.498590 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:14:54.500576 git.c:439               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 228 on BG392906' --check-self-contained-and-connected --pack_header=2,99461
remote: Total 99461 (delta 46727), reused 95540 (delta 44556)
Receiving objects: 100% (99461/99461), 22.19 MiB | 34.27 MiB/s, done.
Resolving deltas: 100% (46727/46727), done.
10:14:56.807810 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet '--progress=Checking connectivity'
10:14:56.819829 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:14:56.820834 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet '--progress=Checking connectivity'
BUG: refs/files-backend.c:2945: initial ref transaction called with existing refs

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Log while setting terminal as 'cmd' is here,
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
D:\Jean\workspace\test_git>git clone <remote git template>
10:22:11.025718 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:22:11.025718 git.c:439               trace: built-in: git clone <remote git template>
Cloning into 'q9web-qyh'...
10:22:11.042763 run-command.c:663       trace: run_command: git remote-http origin <remote git template>
10:22:11.055812 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:22:11.056803 git.c:704               trace: exec: git-remote-http origin <remote git template>
10:22:11.056803 run-command.c:663       trace: run_command: git-remote-http origin <remote git template>
10:22:11.069861 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:22:11.083901 run-command.c:663       trace: run_command: 'git credential-manager get'
10:22:11.123980 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:22:11.124982 git.c:704               trace: exec: git-credential-manager get
10:22:11.124982 run-command.c:663       trace: run_command: git-credential-manager get
10:22:11.359647 run-command.c:663       trace: run_command: 'git credential-manager store'
10:22:11.418766 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:22:11.419768 git.c:704               trace: exec: git-credential-manager store
10:22:11.419768 run-command.c:663       trace: run_command: git-credential-manager store
10:22:11.621306 run-command.c:663       trace: run_command: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning <remote git template>/
10:22:11.632335 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:22:11.633362 git.c:439               trace: built-in: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning <remote git template>/
remote: Counting objects: 99461, done.
remote: Compressing objects: 100% (27590/27590), done.
10:22:11.669435 run-command.c:663       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 11168 on BG392906' --check-self-contained-and-connected --pack_header=2,99461
10:22:11.682470 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:22:11.683473 git.c:439               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 11168 on BG392906' --check-self-contained-and-connected --pack_header=2,99461
remote: Total 99461 (delta 46727), reused 95540 (delta 44556)
Receiving objects: 100% (99461/99461), 22.19 MiB | 32.04 MiB/s, done.
Resolving deltas: 100% (46727/46727), done.
10:22:13.325850 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet '--progress=Checking connectivity'
10:22:13.339888 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:22:13.340890 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet '--progress=Checking connectivity'
B
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Maybe there are some limits in VScode...

**Comment by dscho** [comment]
> `is there any hook installed via e.g. Git templates?`
> Sorry, I'm a new member of this git group. So I'm not sure the detailed code structure.

In your checkout, there should be a (hidden) `.git` folder, and within that folder, there should be a `hooks` folder. Any file in there whose name does not end in ".sample" is an active hook.

> `- is cc a public repository that I can clone myself, to try to reproduce? if it is not, does this happen for any public repository for you?`
> Sorry, currently, it is still not published now.

The question still remains whether this happens for any *public* repository, too.
