### ISSUE TITLE
Git Bash Window is Blank in win10,I can'n use git

### ISSUE THREAD

**Issue by zh1010880729** [git-for-windows/git#2214]
When I use git bash here,the git bash window Need 1Minutes to pop up and the window is blank.Just like this.
![微信截图_20190604185847](https://user-images.githubusercontent.com/30980981/58933490-029bf780-879a-11e9-9950-8a0c1486e3be.png)

**Comment by Birgos** [comment]
After installing git (2.21.0) my Startmenu-Link contains the following Target:
`"C:\Program Files\Git\git-bash.exe" --cd-to-home`

Did you already tried to call the bash without the parameters `--login` and/or `-i`?

**Comment by zh1010880729** [comment]
of course. It used to be good, but it can't be used now.

**Comment by dscho** [comment]
> the window is blank.

Is it as blank as the issue report template?

We came up with this pretty elaborate [template](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md), which is designed to help you provide enough information to make sense of your report.

However, you chose to delete it instead. I cannot say that your bug report is better for it. I would actually claim that it is substantially worse. I have *no* idea where to start. I have no way to help you.
