### ISSUE TITLE
git help -a (CMD/Powershell Window does not exit help with CTRL+Z or CTRL+C)

### ISSUE THREAD

**Issue by NeoBeum** [git-for-windows/git#2216]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.145]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"


Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD/PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git help -a
```
 - What did you expect to occur after running these commands?

After printing help content, help program should exit and return user to input prompt

 - What actually happened instead?

Help program does not exit but remain at (END), CTRL+Z CRTL+C does not exit program.
CMD/PowerShell process must be terminated via TaskManager.
(CTRL + Break) does break from help but has different behaviour if not at (END)

**Comment by dscho** [comment]
Try <kbd>q</kbd>...

**Comment by NeoBeum** [comment]
I thought I had tried that already.. It must not have accepted q, after ctrl+c or ctrl+z and the other combinations I tried
