### ISSUE TITLE
Avoid access violations when running Bash with TERM=msys

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#222]
We used to set the environment variable `TERM=msys` in Git for Windows 1.x, so we should handle it gracefully with Git for Windows 2.x, too. Certainly an access violation is the wrong thing to do, ideally we handle `msys` as a synonym to `cygwin`.

**Comment by Alexpux** [comment]
ncurses don't have ````msys```` terminal so need always use ````cygwin````

**Comment by dscho** [comment]
It does not crash when `TERM=xterm`. In fact, it seems it only crashes whenever `TERM` is set to a value that does not correspond to a directory in `/usr/share/terminfo/??/`. That is probably a problem we want to fix in any case.

**Comment by dscho** [comment]
@Alexpux BTW why is `ncurses-devel` a build dependency, but `ncurses` not a runtime dependency?

**Comment by Alexpux** [comment]
Dependency of what?

**Comment by Alexpux** [comment]
Package ````ncurses```` itself is in group ````base```` so it always present in MSYS2 from the installer.

**Comment by dscho** [comment]
> Dependency of what?

Whoops, sorry: `bash` (I still think of this ticket as "Avoid access violations when running Bash").

**Comment by Alexpux** [comment]
bash is linked fully static, so it depends only from msys-2.0.dll

**Comment by dscho** [comment]
> Package ncurses itself is in group base so it always present in MSYS2 from the installer.

Okay. I generally prefer the dependencies in a package management system to be set up correctly because it is as much documentation as it is necessary for proper process of Pacman.

**Comment by dscho** [comment]
> bash is linked fully static, so it depends only from msys-2.0.dll

That explains it.

**Comment by Alexpux** [comment]
I'm create ````bash```` and ````pacman```` packages statically linked to simplify process of update core packages.

**Comment by KindDragon** [comment]
JFYI we use `TERM=msys` because of https://github.com/gitextensions/gitextensions/issues/1092

**Comment by dscho** [comment]
@KindDragon good point. I recall that we fixed other, similar issues by setting `TERM=msys` in the past.

**Comment by dscho** [comment]
Fixed with https://github.com/Alexpux/MSYS2-packages/pull/275
