### ISSUE TITLE
second and third RC: less and vim: stackdumps

### ISSUE THREAD

**Issue by nilleb** [git-for-windows/git#224]
C:\Users\bellinsalarin>less
      0 [main] less 7900 cygwin_exception::open_stackdumpfile: Dumping stack trace to less.exe.stackdump
    C:\Users\bellinsalarin>vim
    Vim: Caught deadly signal SEGV
    Vim: Finished.
      0 [main] vim 12912 cygwin_exception::open_stackdumpfile: Dumping stack trace to vim.exe.stackdump

stackdumps are available here: https://gist.github.com/nilleb/4c653681845f422af9d8

OS is windows 8.1 x64, git for windows is x64 too.

Works perfectly on a windows 2008.

SET PATH= doesn't solve the problem

Affects portable and msi versions

**Comment by dscho** [comment]
While this is really very little information to go on, I could imagine that setting `TERM=cygwin` might fix it. Can you confirm?

**Comment by nilleb** [comment]
good guess! that's it. TERMwas equal to msys before I changed it to cygwin.

**Comment by nilleb** [comment]
I'm closing this issue as it is a duplicate of a previous issue. Thanks a lot!

**Comment by dscho** [comment]
To be precise: this is a duplicate of https://github.com/git-for-windows/git/issues/222
