### ISSUE TITLE
Possible problem with C (gcc compiled) stdout buffer 

### ISSUE THREAD

**Issue by Shotem** [git-for-windows/git#2245]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Versi▒n 10.0.17134.765]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I don't think so

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
printf "#include <stdio.h>\n\nint main(){\n\tprintf(\"Hello World\\\n\");\n\tscanf(\"%%*s\");\n\treturn 0;\n}" > main.c && gcc main.c -o a.exe && ./a.exe
```
 - What did you expect to occur after running these commands?

I expected bash to print "Hello World" and in a new line read a string

 - What actually happened instead?

The program read a string and printed "Hello World" just before (or after) the "return 0" command

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by Shotem** [comment]
Side Note: The problem can be solved by adding the command `setvbuf(stdout, NULL, _IONBF, 0);` at the start of the main function, so I suspect is related to the way bash uses the standard output buffer on C (I had no problem with C++ and the iostream library...). If it helps, Cywin has the same problem.

**Comment by dscho** [comment]
This is well-documented behavior of `stdout`: it is buffered by default.

If you want to ensure that the message is printed, use `fflush(stdout);` after the `printf()`.

Please note that this is _pretty_ far away from anything resembling a bug report that is relevant to the Git for Windows project.
