### ISSUE TITLE
New Repository via `git init`; "fatal: This operation must be run in a work tree"

### ISSUE THREAD

**Issue by mgthomas99** [git-for-windows/git#2246]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.829]

$ wmic os get osarchitecture

OSArchitecture
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Nano
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash and CMD.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ mkdir "foo" ; cd "foo"
$ git init
$ echo "ok">"index.txt"
$ git add "./index.txt"
```
 - What did you expect to occur after running these commands?

Git to stage `index.txt`.

 - What actually happened instead?

```fatal: this operation must be run in a work tree```

I have tried re-installing Git/for Windows, as well as all Git-related software and configuration files, but the issue still persists.

**Comment by landstander668** [comment]
I'm unfortunately not able to reproduce your behaviour here. Would you please try running the `git add` command with GIT_TRACE=1, and post the results here? As in:

```
$ GIT_TRACE=1 git add "./index.txt"
```
It would probably be helpful to post your git configuration details as well (feel free to mask name/email), just in case an unexpected setting is triggering the problem.
```
git config --show-origin --list
```

**Comment by mgthomas99** [comment]
```
$ GIT_TRACE=1 git add "./index.txt"

16:51:35.805086 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
fatal: this operation must be run in a work tree
```

```
$ git config --show-origin --list

file:"C:\\ProgramData/Git/config"       core.symlinks=true
file:"C:\\ProgramData/Git/config"       core.autocrlf=false
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/mingw64/etc/gitconfig core.editor=nano.exe
file:"C:\\Program Files\\Git\\bin/config"       core.repositoryformatversion=0
file:"C:\\Program Files\\Git\\bin/config"       core.filemode=false
file:"C:\\Program Files\\Git\\bin/config"       core.bare=true
file:"C:\\Program Files\\Git\\bin/config"       core.ignorecase=true
```

My apologies to not being able to provide much information about the issue; I have never had this issue before and cannot think of any cause. 😕

**Comment by PhilipOakley** [comment]
see this config `file:"C:\\Program Files\\Git\\bin/config"       core.bare=true` 
Looks like a possible cause to me
`fatal: this operation must be run in a work tree` (if it's bare, then there is no worktree).

Not sure how that config value got there but..

**Comment by landstander668** [comment]
That seems plausible, and I am able to reproduce the behaviour if I explicitly do `git init --bare` in place of `git init`. Surprisingly, however, I'm not able to reproduce it by simply adding the setting to my global profile via `git config --global core.bare true`... this results in a normal (non-bare) repository being created. I also tried manually adding "C:\\Program Files\\Git\\bin/config" (which doesn't exist on my installation) with the setting, which again failed to reproduce.
@mgthomas99 Can you provide the output of `$ env`? Perhaps there's an environment variable set, such as GIT_DIR, which is affecting Git's behaviour.

**Comment by PhilipOakley** [comment]
See `git help config` and search for `bare`.

core.bare

    If true this repository is assumed to be bare and has no working directory associated with it. If this is the case a number of commands that require a working directory will be disabled, such as git-add(1) or git-merge(1).

so...

**Comment by landstander668** [comment]
@PhilipOakley I'm not doubting you, but the setting doesn't *appear* to effect the commands in question here. Perhaps it's only supported as a per-repository configuration? Although I certainly didn't fine anything in the docs explicitly stating that.

```
$ git version --build-options
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8

$ git config --list --show-origin | grep 'core\.bare'

$ git config --global core.bare true

$ mkdir foo && cd foo

$ git init
Initialized empty Git repository in C:/Users/adric.norris/foo/.git/

$ date >bar

$ git add bar
warning: LF will be replaced by CRLF in bar.
The file will have its original line endings in your working directory
```

**Comment by dscho** [comment]
> "C:\\Program Files\\Git\\bin/config"

That looks thoroughly broken. That file should not exist, and even if it exists, it should not be parsed.

Unless, that is, your `HOME` points to `C:\Program Files\Git\bin`?

**Comment by mgthomas99** [comment]
```
$ cat "C:\Program Files\Git\bin\config"

[core]
	repositoryformatversion = 0
	filemode = false
	bare = true
	ignorecase = true
```

I tried commenting out the `bare = true` line, which fixed Git and allowed me to work on an existing project. However, I then created a new repository via `git init`, but encountered the same issue at `git add ./index.txt`, and noticed that `bare = true` had been *automatically re-added* to the bottom of `C:\Program Files\Git\bin\config`.

**Comment by mgthomas99** [comment]
I believe I found the source of the issue... there was a system environment variable, `GIT_DIR`, set to `C:\Program Files\Git\bin`. After deleting that variable, Git seems to work as expected.

```
$ mkdir "foo" ; cd "foo"
$ git init
Initialized empty Git repository in D:/foo/.git/
$ echo "ok">index.txt
$ ls
index.txt
$ git add "./index.txt"
$ git commit -m "Initial commit"
[master (root-commit) 68d9411] Initial commit
 Committer: George Thomas <(omitted)>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 1 insertion(+)
 create mode 100644 index.txt
```

**Comment by dscho** [comment]
> there was a system environment variable, `GIT_DIR`, set to `C:\Program Files\Git\bin`. After deleting that variable, Git seems to work as expected.

Yep, that environment variable would mess things up real good: https://git-scm.com/docs/git#Documentation/git.txt-codeGITDIRcode

Glad that you found and fixed the problem!

**Comment by PhilipOakley** [comment]
@landstander668 (just replying to [earlier comment](https://github.com/git-for-windows/git/issues/2246#issuecomment-505125278))

I hadn't dug beyond just checking the docs and thinking that a message about lack of a worktree implied a bare repo. 

Having just looked at the doc history (and stepping over the recent rearrangement of the config docs) got the original blame on that code via https://github.com/git/git/blame/v2.19.0/Documentation/config.txt#L619-L622 to see its been documented that way since 2007 https://github.com/git/git/commit/e4a15f40bcd9e5679345d3cc74db3162310a7c83.

So it's good to see that an alternate root cause has been found, though how `GIT_DIR` got set to that...
