### ISSUE TITLE
Installer: "Select other editor" Crashes

### ISSUE THREAD

**Issue by brentarias** [git-for-windows/git#2247]
Install Git 2.22.0 on a new laptop, during the "choosing the default editor" step make the "Select other editor as Git's default editor" option.  Insert text manually into the "location of editor" for notepad.exe (do not use the "Browse" button) as follows:

    c:\windows\system32\notepad %1

Now press "Test Custom Editor".  It doesn't matter how the next dialogue is answered, from this point forward the installer is now locked and unable to respond to any input.  Task manager is needed to end the process.

### Setup

Using 64-bit Git.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.829]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults.

**Comment by rimrul** [comment]
Does it also crash if you remove the `%1` and maybe add `.exe` to the end of the file name?

**Comment by dscho** [comment]
Over three months is a long time to let @rimrul wait for an answer, @brentarias. I will therefore draw the curtain of charity over this ticket and close it.
