### ISSUE TITLE
BUG in git p4 unshelve

### ISSUE THREAD

**Issue by ybeapps** [git-for-windows/git#2248]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.1146]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git p4 unshelve 161340
```
 - What did you expect to occur after running these commands?

Something like this:
```
created parent commit for 161340 based on HEAD in refs/remotes/p4-unshelved/161340
unshelved changelist 161340 into refs/remotes/p4-unshelved/161340
```

 - What actually happened instead?
```
fatal: Not a valid object name HEAD0
Command failed: git cat-file commit HEAD^0
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No

Actually the solution is pretty easy (the hard thing is to submit a pull request!
When triggering git p4 unshelve it should select a parent commit which on it the shelve will commit.
The default action takes HEAD with the wrong syntax **HEAD^0**.
This is needs to be changed to the correct syntax **HEAD~0**
You can fix this in git-p4.py file. just replace line 3965 from this:
`log = extractLogMessageFromGitCommit("{0}^{1}".format(starting_point, parent))`
to this:
`log = extractLogMessageFromGitCommit("{0}~{1}".format(starting_point, parent))`

On my machine this solves the issue.

**Comment by dscho** [comment]
> fatal: Not a valid object name HEAD0

Isn't this the bug that we solved in c3f2358de39a8ac754ae68880a992835a84a6f0c?

**Comment by dscho** [comment]
> The default action takes HEAD with the wrong syntax **HEAD^0**.
> This is needs to be changed to the correct syntax **HEAD~0**

This is actually incorrect, even if `HEAD^0` is equivalent to `HEAD~0` (and so is `HEAD^1` and `HEAD~1`): in general, `HEAD^{n}` is _not_ `HEAD~{n}`. See my explanation at https://github.com/git/git/pull/617#issuecomment-505882896

**Comment by ybeapps** [comment]
Yes it looks like the same bug
If you solved it, how can I get the fix?

**Comment by dscho** [comment]
> how can I get the fix?

The easiest way is to download https://github.com/git-for-windows/git/blob/c3f2358de39a8ac754ae68880a992835a84a6f0c/git-p4.py and replace your `<git-top-level>/mingw64/libexec/git-core/git-p4`.

**Comment by dscho** [comment]
@ybeapps if you can confirm the fix, you may want to open a PR to get this into Git for Windows early.

**Comment by ybeapps** [comment]
I'll do it right away, thanks!!

**Comment by ybeapps** [comment]
I don't understand, this file [from blob](https://raw.githubusercontent.com/git-for-windows/git/c3f2358de39a8ac754ae68880a992835a84a6f0c/git-p4.py) is exactly like the one in [master](https://raw.githubusercontent.com/git/git/master/git-p4.py)

The only difference is that line 1312:
`add_actions = ( "add", "move/add" )
`
**VS**
`add_actions = ( "add", "branch", "move/add" )
`

I see that line 740 is fixed, but it keeps failing - in both versions:
```
C:\gitWorkspace\trunk>git p4 unshelve 161340
fatal: Not a valid object name HEAD^2
Command failed: ['git', 'cat-file', 'commit', 'HEAD^2']
```

**Comment by ybeapps** [comment]
I tried to play with it...

I can explain the error

This is my state:
I'm synced with Perforce, and I have 2 unsubmitted commits.
When I run this command in cmd: `git cat-file commit HEAD^^0` I'm getting my last commit details - as expected.
When I run this command in cmd: `git cat-file commit HEAD^^1` I'm getting the commit that was before that last commit, as expected - it's the single parent of that commit.
When I run this command in cmd: `git cat-file commit HEAD^^2` I see that error.

The script is searching for a direct parent that is already submitted. If it can't find one, it fails the command with that error...

**Comment by dscho** [comment]
I have literally no clue about Perforce. Maybe you want to ask on the Git mailing list?

**Comment by ybeapps** [comment]
I’ll explain, git-p4 helps developers who work on a Perforce remote repository to use git locally.
It defines all commands that are needed to interact with Perforce server (like Submit, GetRevision, Unshelve etc...).
It translates each Perforce changeset to a git commit and vice-versa.
So I have a local git repo, it has all commits from Perforce server, and I committed twice on top of it.
Now I want to unshelve changes from Perforce server, and git-p4 has to find a parent commit to commit those changes on top of it. but it currently accepts only a direct parent of HEAD which appears on Perforce server too, and because I have 2 local commits that aren’t submitted- the script fails.
Do you think this is was the script’s developer meant to do?
I really thinks he meant to search parents with ~ syntax (first parent of... as you explained) instead of searching in the multiple direct parents only...
What do you think?

**Comment by ybeapps** [comment]
By the way.. I see that "git/git" repo has the changes already merged.
Why isn't it merged in "git-for-windows"?
See the changes between repos:
![repos diff](https://user-images.githubusercontent.com/5706986/60499084-75788f80-9cc0-11e9-9625-a666d12d87ba.png)

Why not merging to git-for-windows?

**Comment by PhilipOakley** [comment]
Hi @ybeapps You didn't say what stage the changes were merged into git/git. It could be at pu, next, master, or a tagged release. 

The Git for Windows has far fewer supporters than git/git, so what 'you' (public announcements) see is that G-f-W only provides full up releases when git/git does a final tagged release. 

There are other 'internal' test versions that are available from the maintainer's repo (see the shears/xx branches).

If you would like to join the supporters club.. a good place to start is https://gitforwindows.org/#contribute

**Comment by ybeapps** [comment]
This is on master, so I guess it'll be merged soon? should we create a PR to make is sooner?
I'm considering to join.. thank you

**Comment by dscho** [comment]
> This is on master

If you mean https://github.com/git/git's `master`, then it will be part of v2.23.0 once that's out (see https://tinyurl.com/gitCal for tentative release schedules).

If you want this in Git for Windows sooner than that, e.g. in a [snapshot](https://wingit.blob.core.windows.net/files/index.html), you will want to cherry-pick it onto https://github.com/git-for-windows/git's `master` and open a PR.

**Comment by PhilipOakley** [comment]
Hi @dscho, 
How often is https://github.com/git-for-windows/git/tree/shears/master updated? I.e. does it offer an easy method for @ybeapps to try out the fix via a simple 'compile' of that shears/master branch from the SDK?.

I ask as I'd got myself confused about which repo held which artefacts, and how often they were updated.

Philip

**Comment by dscho** [comment]
> How often is https://github.com/git-for-windows/git/tree/shears/master updated?

Every time `master` of either git-for-windows/git or git/git is updated.

When possible, https://dev.azure.com/Git-for-Windows/git/_build?definitionId=26&_a=summary or https://dev.azure.com/Git-for-Windows/git/_build?definitionId=25&_a=summary will update it automatically. If the build fails, it is usually up to me to perform the rebase manually (using [`ever-green.sh`](https://github.com/git-for-windows/build-extra/blob/master/ever-green.sh)).
