### ISSUE TITLE
"failed to restrict file handles" error triggered by mistyped command

### ISSUE THREAD

**Issue by Andras88** [git-for-windows/git#2252]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.16.1.windows.4
64bit
```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 64bit
```
$ cmd.exe /c ver

Microsoft Windows [verziószám: 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
I don't remember.
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu 64bit

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git diffsrc/SomeFile.scala
# accidentally the "diff" git command was not separated from the file path, so the command is not correct
```
 - What did you expect to occur after running these commands?

N/A

 - What actually happened instead?

$ git diffsrc/SomeFile.scala
warning: failed to restrict file handles (2)

handle #0: 0000000000000003 (type 2, handle info (1) 0
handle #1: 000000000000000f (type 2, handle info (1) 1
handle #2: 0000000000000007 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'diffsrc/SomeFile.scala' is not a git command. See 'git --help'.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Please update to a current Git for Windows, the bug is long fixed.
