### ISSUE TITLE
progress for push

### ISSUE THREAD

**Issue by simonm3** [git-for-windows/git#2254]
I am pushing a commit that includes 2GB of files going to git lfs. On version 2.20 this reports progress

`Uploading LFS objects:   8% (5/62), 170 MB | 451 KB/s`

On version 2.21 and 2.22 it reports nothing. Even with the -v flag it just says it is pushing. I am not sure if it has just hung or is doing it quietly in the background. Is there any way to see progress for a long running operation like this?

**Comment by dscho** [comment]
You probably want to

- report this at https://github.com/git-lfs/git-lfs
- include the versions of `git lfs version` rather than of Git for Windows.
