### ISSUE TITLE
Is tig still included?

### ISSUE THREAD

**Issue by suntong** [git-for-windows/git#2260]
Quick question -- is tig still included?

I saw it mentioned in https://github.com/git-for-windows/git/releases/tag/v2.14.2.windows.1
but no longer in https://github.com/git-for-windows/git/releases/tag/v2.22.0.windows.1

thus asking. thx.

**Comment by rimrul** [comment]
Yes, 2.22.0 still comes with tig. It isn't mentioned in the change log, because it didn't change.

**Comment by suntong** [comment]
Thanks a lot Matthias
