### ISSUE TITLE
Git spawns new processes forever

### ISSUE THREAD

**Issue by drguildo** [git-for-windows/git#2261]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
```
I am unable to run this command as when I do, Git begins spawning processes recursively and I does not produce any output.

I am using the portable version of Git installed using scoop:

```
PS C:\Users\Simon> scoop info git-with-openssh
Name: git-with-openssh
Version: 2.22.0.windows.1
```

It is my understanding that a similar bug has been reported before but it seems that the bug was only triggered when misspelling Git commands. This bug happens even when running just "git".

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.239]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults.
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```

This file is not located anywhere on my system.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I only started experiencing this bug after updating Windows to version 1903. However, Git for Windows is the only program that seems to be exhibiting it.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I have tried Bash, CMD and PowerShell and I get the same behaviour with all three.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git
```
 - What did you expect to occur after running these commands?

Help output.

 - What actually happened instead?

Git begins recursively spawning child processes until it runs out of memory.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It doesn't happen with a specific repository.

**Comment by dscho** [comment]
Try Bash, and call `export GIT_TRACE=1` before calling `git.exe` again. That should give you more information.
