### ISSUE TITLE
Domain name prepended to username when authenticating to remotes

### ISSUE THREAD

**Issue by pbz** [git-for-windows/git#2265]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.6.1.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.1217]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

File does not exist. Git for Windows provided with SourceTree.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

  Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
fetch, push, etc.
```
 - What did you expect to occur after running these commands?

    Successful authentication. Username was passed to remote server as entered (user enters "mrfoo" as username, remote receives "mrfoo" as username in request )

 - What actually happened instead?

    Failed authentication. Username was passed to remote server with domain prepended (user enters "mrfoo" as username, remote receives "mydomain\mrfoo" as username in request). 

   See redacted excerpt from a Wireshark capture: [Git failed auth attempt redacted.txt](https://github.com/git-for-windows/git/files/3403209/Git.failed.auth.attempt.redacted.txt)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

    N/A

**Comment by dscho** [comment]
> git version 2.6.1.windows.1

Urgh, that's like, super super old. Are you sure that none of the many updates (the latest version is *sixteen* major versions ahead!) fixes your problem?

**Comment by dscho** [comment]
> $ cat /etc/install-options.txt
> 
> File does not exist. Git for Windows provided with SourceTree.

Please note that the Git for Windows project does _not_ support SourceTree. BitBucket does. So if you report a bug in Git for Windows, please make sure to verify that you can reproduce the bug _in Git for Windows_, i.e. without detouring into SourceTree.

**Comment by mfriedrich74** [comment]
Hi,

SourcTree updates are available too. The latest version ships with a much
newer git version. Please upgrade.

Additionally, you can tell SourcTree to use a system installed git, which
allows you to upgrade git independently. I recommend using this option.

Best regards, Mike

**Comment by pbz** [comment]
So, just retested with Git for Windows 2.22 (from git-scm.com) and was able to reproduce. 

Interesting detail that was discovered: What domain is prepended corresponds to what domain they've authenticated to when connecting to the VPN. So:

|Network connection|Username supplied to Git|Username sent to remote|
|--------------------|-------------------------|--------------------------|
|VPN as DomainA\username|username|DomainA\username|
|VPN as DomainB\username|username|DomainB\username|

I initially thought that Git might have been prepending the value of the USERDOMAIN environment variable, but this does not seem to be the case. No clue where it's getting the domain name from, but somehow, it knows...

Relevant details of the install used for this round of testing:

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

Thanks,
Jason

**Comment by dscho** [comment]
Maybe your VPN changes the environment variable `USERNAME`? I work on a VPN pretty much _all_ the time, and I have never encountered these problems, so it must be specific to the brand of VPN, is my guess.

**Comment by dscho** [comment]
Closing this stale ticket.
