### ISSUE TITLE
Include all Mingw tools from Mysys2

### ISSUE THREAD

**Issue by WSLUser** [git-for-windows/git#2270]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64-bit
```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
64 bit Windows 7.
```
$ cmd.exe /c ver

** insert your machine's response here **
```
64 bit Windows 7.
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Defaults
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
I would like the ability to manually update mintty and other binaries using make but git bash doesn’t provide the necessary binaries. 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
CMD, Powershell, bash (Mintty)
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue. 

```
** insert your commands here **
```
Make, cat/ls/blah somefile.someextension | more
 - What did you expect to occur after running these commands?

** insert here **
Work just as if I was running on native Linux.
 - What actually happened instead?

** insert here **
Failures
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **
Create binaries from here: https://github.com/msys2/MINGW-packages

**Comment by landstander668** [comment]
@WSLUser For this sort of use case, your best bet is probably to install the [Git for Windows SDK](https://github.com/git-for-windows/build-extra/releases/latest) rather than the general release.

**Comment by WSLUser** [comment]
I’m just surprised they don’t include gcc and make at least. If you got those, getting the others is easy enough. I’m not looking for a full blown cygwin or msys2 environment but want the benefits that mintty provides in addition to a few tools such as gcc and make. git bash provides much of the needed binaries without being as bloated as the other 2 solutions. Plus as I understand it, mingw is used whenever possible for tooling, then msys2. Seeing as they have a rolling release, it would be very easy to get the forking done similarly to how git is forked.

**Comment by dscho** [comment]
I am surprised that the reasons why GCC and GNU Make are not included in regular Git for Windows are not obvious:

- They are not required for Git to work. Like, not at all. Really. Not in the least. Git works Just Fine without them. And the name "Git for Windows" really indicates that we want to provide "Git" on Windows, not a Linux lookalike, or else we would call this project "Something looking like Linux for Windows".

- Including GCC would increase the download _dramatically_. You might not notice it, I expect you to have decent internet connection. The majority of the world does not, and a ~44 megabyte is already _a lot_.

**Comment by WSLUser** [comment]
I honestly only use this because this is the smallest install for getting a bash environment for the Win7 VM I sometimes have to work on. All my git work is done on a remote Linux server.

**Comment by binkley** [comment]
I sympathize.  "Git for Windows" is small and focused.

However, I use this tool so I can do development work.  Not asking to change the "Git for Windows" distribution.  Helpful would be:

1. FAQ or documentation on how to add additional msys2 tools, or at least links to how to build these tools
2. (wishlist item) A packaging or similar system for add-ons to "Git for Windows".  Even something as simple as sdkman would be super nice

**Comment by dscho** [comment]
@binkley you _are_ asking a lot. Git for Windows' contributors are too stretched with Git already. So how about putting the money where your mouth is and learn enough to fulfill your own wish?

**Comment by PhilipOakley** [comment]
Hi @binkley @WSLUser  the places to look are:

1. https://github.com/git-for-windows/git/wiki/FAQ (and it's associated wiki pages) to add your local docs (steal from the other pages to get started ;-). This is a self edit wiki! (if you add a page, also edit the [manual] index..)
2. https://github.com/git-for-windows/git-for-windows.github.io to improve the https://gitforwindows.org/ home page. Submissions via a PR.
3. https://github.com/git-for-windows/build-extra/blob/master/README.md, https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md particularly the https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues segment.  Submissions via a PR.

(as noted, Dscho is too stretched, so all _help_ is gratefully accepted - just jump right in there - small steps...)

**Comment by PhilipOakley** [comment]
e.g. steal dscho's explanation at https://github.com/git-for-windows/git/issues/2270#issuecomment-514213914 as a clarification to the 'known issues' (It's not actually an issue, just an explanation, but it may be the easiest place to put it to direct others in a similar situation to "Do the right thing(TM)" )
