### ISSUE TITLE
ssh-agent reports wrong PID (Regression)

### ISSUE THREAD

**Issue by skrysmanski** [git-for-windows/git#2274]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? **Windows 10 1903**

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.239]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**None**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** CMD **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
"C:\Program Files\Git\usr\bin\ssh-agent.exe" -c
```
 - What did you expect to occur after running these commands?

The command should give me an output containing the ssh-agent's PID.

 - What actually happened instead?

The command gives me a PID but the PID is wrong. The command works fine with older versions (including 2.21.0).

Running `ps x | grep ssh-agent` from within a bash gives me both the correct and the wrong pid (not sure what to make of it):

![pid-bug](https://user-images.githubusercontent.com/914747/61956721-fecc6a80-afbd-11e9-8554-31dbd137372c.png)

It seems in 2.22.0 there was some kind of PID mapping introduced.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

*no*

**Comment by rimrul** [comment]
The impostant part in the 2.22.0 release notes is this:

> Comes with MSYS2 runtime (Git for Windows flavor) based on Cygwin v3.x (see release notes for Cygwin 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, and 3.0.7).

And in the cygwin 3.0.0 release notes there's this section:

>Cygwin PIDs have been decoupled from Windows PID.  Cygwin PIDs are
  now incrementally dealt in the range from 2 up to 65535, POSIX-like.
  Native Windows processes not started by Cygwin processes are mapped
  into the range beyond 65535.

That's what causes this change in behaviour. 

> but why does `ps x` still show the PID I've expected?

Well, `ps` is a MSYS2 programm as well. If we look at the output of `ps x` without a `grep` we'll see that those first four columns are labeled

* PID
* PPID
* PGID
* WINPID

That fourth column contains the information you should have been using all along, because the fact that there is a mapping between Cygwin/MSYS2 PIDs and Windows PIDs is not new. They just became less closely related due to changes under the hood.

**Comment by dscho** [comment]
This is a feature introduced in Cygwin's runtime as of version 3.0.0. As our `ssh-agent` is an MSYS2 program (and as the MSYS2 runtime is a friendly fork of Cygwin's runtime), this is expected.

If you enhance your `grep` call to also show the first line with the column headers, you will discover that Cygwin distinguishes between PIDs and WINPIDs now.

**Comment by skrysmanski** [comment]
Thanks for the clarification. I'll update my scripts with the new information.
