### ISSUE TITLE
Arrow keys skipping menu items

### ISSUE THREAD

**Issue by mklueh** [git-for-windows/git#2280]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64 Bit

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Occurs on two different Dell notebooks

### Details

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

When having a menu with different choices, ex:

```
amplify add storage
? Please select from one of the below mentioned services
> Content (Images, audio, video, etc.)
  NoSQL Database
```

I **can not choose NoSQL Database**, because it overjumps it and goes back to **Content (Images, audio, video, etc. )** again. 

**The cursor always moves two items further instead of one**

This seem to occur mainly with Node.js installation assistants

**Comment by dscho** [comment]
> When having a menu with different choices, ex:

Care to clarify what commands you run, and what you need to set up your environment for this MCVE to actually reproduce the issue?

I ask because Git for Windows does not show any menu by default. It only installs a few Start Menu items.

**Comment by mklueh** [comment]
This is no longer an issue and can be closed.
