### ISSUE TITLE
Git installer for windows has a typo

### ISSUE THREAD

**Issue by abhikhan25** [git-for-windows/git#2284]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit - 2.22
```
$ git --version --build-options
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10
```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.17134.320]
 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
NA
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
BASH
** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
just install using windows installer
```
** insert your commands here **
```
 - What did you expect to occur after running these commands?
found a typo
** insert here **

 - What actually happened instead?
NA
** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
NA
** insert URL here **

**Comment by abhikhan25** [comment]
<img width="252" alt="Git installer typo" src="https://user-images.githubusercontent.com/29383385/62683956-3f27e180-b9dd-11e9-8442-40968b0d9864.PNG">

**Comment by rimrul** [comment]
That's not a typo. See #265.

**Comment by PhilipOakley** [comment]
@abhikhan25 though the issue has been closed, the fact that you are the second report that you have misread/misunderstood the phrasing, it does offer an opportunity for you to propose (via a PR) an alternative wording that you would understand, and still has the appropriate tone about the sportiness of the window.

The text will be in the build-extra repo within the Innosetup code.
