### ISSUE TITLE
"git log" is not displaying tag information (refs) to standard output when executed from C# System.Diagnostics.Process

### ISSUE THREAD

**Issue by clisc** [git-for-windows/git#2285]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git version 2.22.0.windows.1, 64-bit

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD, Other - C# IOSProcess

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log origin/master --pretty=oneline --decorate-refs=^tag* -1
```
 - What did you expect to occur after running these commands?
```
7f41249a3ed248e251b867a208186d494e60b29a (tag: v15.0.2161.0) Version updated to 15.0.2161.0 by the build system. ***NO_CI***
```
 - What actually happened instead?

In CMD:
```
7f41249a3ed248e251b867a208186d494e60b29a (tag: v15.0.2161.0) Version updated to 15.0.2161.0 by the build system. ***NO_CI***
```
From IOSProcess Standard Output:
```
7f41249a3ed248e251b867a208186d494e60b29a Version updated to 15.0.2161.0 by the build system. ***NO_CI***
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by shiftkey** [comment]
```
git version 2.19.0.windows.1
```

@clisc can you re-test this against a more recent version of Git? 2.19.0 was released in Sept 2018, and there are almost a year of upstream changes that might have addressed this issue.

**Comment by clisc** [comment]
I just upgraded and reproduced on:

```
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

I will edit my original post.

**Comment by rimrul** [comment]
> C# IOSProcess

What version of the .NET framework are we talking about here? And more importantly, where does this `IOSProcess` come from? Microfts .NET documentation seems to know nothing of this interface or class. The only mentions of such a thing that i could find where notes about implementing an "Instructor Operation Station" from a Richard Harrison in 2010 and from Michigan State University in collaboration with Boeing in 2008. Not ecactly well documented standard classes.

**Comment by clisc** [comment]
Thanks, that's good feedback.  I thought it was a standard class but I see now that it is not.

Looking at the code, it's actually just a wrapper for the C# Process class:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netframework-4.0

The project is targeting .NET Framework version 4.

**Comment by clisc** [comment]
I just created a minimal repro in a C# application:

```
using System;
using System.Diagnostics;
using System.IO;

namespace GitLogRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            Process gitProcess = new Process();
            string stdout;
            string stderr;
            int exitCode = -1;

            using (gitProcess)
            {
                gitProcess.StartInfo.FileName = "git.exe";
                gitProcess.StartInfo.WorkingDirectory = @"F:\Git\sqldw";
                gitProcess.StartInfo.Arguments = @"log origin/master --pretty=oneline --decorate-refs=^tag* -1";

                gitProcess.StartInfo.UseShellExecute = false;
                gitProcess.StartInfo.RedirectStandardOutput = true;
                gitProcess.StartInfo.RedirectStandardError = true;

                gitProcess.Start();
                gitProcess.WaitForExit();

                using (StreamReader standardOutput = gitProcess.StandardOutput)
                {
                    stdout = standardOutput.ReadToEnd();
                }

                using (StreamReader standardError = gitProcess.StandardError)
                {
                    stderr = standardError.ReadToEnd();
                }

                exitCode = gitProcess.ExitCode;
            }

            Console.WriteLine("Standard Output: " + stdout);
            Console.WriteLine("Standard Error: " + stderr);
            Console.WriteLine("Exit Code: " + exitCode);
            Console.ReadLine();
        }
    }
}

```

**Comment by clisc** [comment]
Also got the same results on .NET 4.6 and .NET 4.7.2.

**Comment by shiftkey** [comment]
@clisc given this works in Git CMD but not in your .NET sample I'd have a look into how arguments are being provided (and escaped) by the .NET Framework. The `^` and `*` characters may be being handled differently, and you might have to wrap them in quote marks to get `Process` to work as expected.

**Comment by clisc** [comment]
If I leave off the parameter ```--decorate-refs=^tag*``` I still have the same issue.  I will try escaping those and see if there is any luck there, but I actually added ```--decorate-refs=^tag*``` recently in order to try to fix the fact that the refs were missing from the command completely.

**Comment by clisc** [comment]
Confirmed the repro without ```decorate-refs=^tag*```:

```gitProcess.StartInfo.Arguments = @"log origin/master --pretty=oneline -1";```

**Comment by clisc** [comment]
I emailed git@vger.kernel.org and got this response:

> Decorations, like color and refs pointing to a commit, are for humans, and humans read the terminal.  If the command's output doesn't go to a terminal, then no such decorations are shown by default.
> 
> Try invoking 'git log --decorate'; or, better yet, use your custom '--format=', especially if you intend to parse the output, 

I added ```--decorate``` to the command and got the desired output.

**Comment by clisc** [comment]
Strangely, when I run this command:

Git log origin/master --pretty=oneline --decorate -1

I get the format I want from STDOUT.  However, when I try to filter it to show only the tag refs:

Git log origin/master --pretty=oneline --decorate --decorate-refs=^tag* -1

No refs are returned to standard output again.  Only on the command line.

Does --decorate-refs not return to STDOUT?

**Comment by gistofj** [comment]
The `^` character is special on Windows. Try replacing it with `~`°

**Comment by clisc** [comment]
Unfortunately using ```~``` returns the same output:

```
gitProcess.StartInfo.Arguments = @"log origin/master --pretty=oneline --decorate --decorate-refs=~tag* -1";
```

```
Standard Output: 3c695db5cac0a0420c7f9c11ce7060fe658f4ce9 Version updated to 15.0.2162.0 by the build system. ***NO_CI***

Standard Error:
Exit Code: 0
```

However, removing the ```^``` character all together gave the desired result:

```
gitProcess.StartInfo.Arguments = @"log origin/master --pretty=oneline --decorate --decorate-refs=tag* -1";
```

```
Standard Output: 3c695db5cac0a0420c7f9c11ce7060fe658f4ce9 (tag: v15.0.2162.0) Version updated to 15.0.2162.0 by the build system. ***NO_CI***

Standard Error:
Exit Code: 0
```

**Comment by fourpastmidnight** [comment]
I thought you could use ^^ to get a single ^. The ^ in CMD, IIRC, is how you begin an escape sequence, much like \ in C-like languages.

Sent from my Windows 10 phone

**Comment by clisc** [comment]
I think I will close this issue out with the following learnings:

1. Use ```--decorate``` to get ref information to display in Standard Output when using the ```git log``` command.
2. The ```--decorate-refs``` command is already left-justified so there is no need to start it with a regex character such as ```^```.

I was also told that lib2git is a good tool for interacting with git in C#, although I have not experimented with this yet.
