### ISSUE TITLE
Error in subprocess.Popen when running git p4 from within Sublime Merge

### ISSUE THREAD

**Issue by haferburg** [git-for-windows/git#2286]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.1217]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: SublimeText
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

The problem occurs when I run `git p4` from within Sublime Merge.

    >git config alias.p4
    !'C:\Python27\python.exe' 'c:\program files\Git\mingw64\libexec\git-core\git-p4'

I set up a custom menu with a file `User/Main.sublime-menu`:

    [
        {
            "id": "repository",
            "children":
            [
                {
                    "caption": "-",
                },
                {
                    "command": "git", "args": {"argv": ["p4", "sync"]},
                    "caption": "git p4 sync"
                },
            ]
        }
    ]

 - What commands did you run to trigger this issue?

```
git p4 sync
```

 - What happened?

```
    Traceback (most recent call last):
      File "c:\program files\Git\mingw64\libexec\git-core\git-p4", line 4163, in <module>
        main()
      File "c:\program files\Git\mingw64\libexec\git-core\git-p4", line 4113, in main
        cmd = klass()
      File "c:\program files\Git\mingw64\libexec\git-core\git-p4", line 2592, in __init__
        if gitConfig('git-p4.largeFileSystem'):
      File "c:\program files\Git\mingw64\libexec\git-core\git-p4", line 793, in gitConfig
        s = read_pipe(cmd, ignore_error=True)
      File "c:\program files\Git\mingw64\libexec\git-core\git-p4", line 206, in read_pipe
        (retcode, out, err) = read_pipe_full(c)
      File "c:\program files\Git\mingw64\libexec\git-core\git-p4", line 197, in read_pipe_full
        p = subprocess.Popen(c, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=expand)
      File "C:\Python27\lib\subprocess.py", line 386, in __init__
        errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
      File "C:\Python27\lib\subprocess.py", line 509, in _get_handles
        p2cread = _subprocess.GetStdHandle(_subprocess.STD_INPUT_HANDLE)
    WindowsError: [Error 6] The handle is invalid
```

I was able to fix it be adding `stdin=subprocess.PIPE, ` to every `Popen`.

**Comment by dscho** [comment]
Is this really a Git for Windows-specific problem? I ask because we do not even ship Python with Git for Windows, i.e. we do not officially support `git p4`.

**Comment by haferburg** [comment]
Probably not. I only use Windows.

**Comment by dscho** [comment]
Okay. Let's try to come up with a proper fix.

Is there maybe a documented way to tell Python's `Popen()` call that there is no `stdin`? I mean, we won't pipe anything into that process, do we?

**Comment by haferburg** [comment]
I had another look at this.

[subprocess.Popen](https://docs.python.org/2/library/subprocess.html#subprocess.Popen)
> stdin, stdout and stderr specify the executed program’s standard input, standard output and standard error file handles, respectively. Valid values are PIPE, an existing file descriptor (a positive integer), an existing file object, and None. PIPE indicates that a new pipe to the child should be created. **With the default settings of None, no redirection will occur; the child’s file handles will be inherited from the parent** [Emphasis mine].

My understanding is that leaving the `stdin` parameter to the default value `None` won't work, because in my case there is no `stdin`. 

The Popen API has changed in Python 3. There is now a `subprocess.DEVNULL`, but we don't have that in Python 2. I don't see a better way than passing in `PIPE`. And even though we don't actually need to forward stdin, I don't think that there's going to be a problem.

Ultimately I'd say the Python API is modeled poorly. `stdin=None` should mean that there is no handle, and the default should be something like `stdin=subprocess.INHERITED_FROM_PARENT`.

If you want I can open a PR from here: https://github.com/haferburg/git/commits/popen2286

**Comment by dscho** [comment]
> If you want I can open a PR from here: https://github.com/haferburg/git/commits/popen2286

I don't really think that it is _I_ who wants this PR, but _you_.

And that PR, seeing as there is nothing particularly Windows-specific about it, should probably go straight to the Git mailing list, maybe by rebasing it onto https://github.com/git/git's `master` and then opening a PR there (and using GitGitGadget, which will greet you, to submit the patch). You will probably also want to look through the output of `git shortlog -nse --since=2.years.ago git-p4.py` to find out who to Cc. (In GitGitGadget, you can Cc people by having a paragraph at the end of the form `Cc: Luke Diamand <luke@diamand.org>, Andrey Mazo <ahippo@yandex.com>`.)

**Comment by haferburg** [comment]
Oh, ok. Well then I'll just close the issue. Thank you for your input.
