### ISSUE TITLE
Copy Con command

### ISSUE THREAD

**Issue by mfraggy25** [git-for-windows/git#2287]
I am trying to use the "copy con" command on git bash for Windows 10.   

git version 2.22.0.windows.1

All other commands work fine so far except this and this is what happens:

Michael.Fragiskatos@Michaelf25 MINGW64 ~/desktop/github-slideshow/_posts (my-slide)
$ "copy con _posts/0000-01-02-mfraggy25.md"
bash: copy con _posts/0000-01-02-mfraggy25.md: No such file or directory

I've tried different variations and not sure where to go from here.  I'm very new to github and still unfamiliar as I'm currently just learning through a beginners module.

**Comment by rimrul** [comment]
You're using git bash. it doesn't know about the cmd builtin `copy` (though yours finds a `copy` command anyway, it just doesn't know that con isn't supposed to be a file) try to use `touch` instead of `copy con`
