### ISSUE TITLE
Git Path Issue

### ISSUE THREAD

**Issue by surajbshinde** [git-for-windows/git#2290]
Hi Team,

Error : The system cannot find the path specified  in windows server 2016

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

32 bit and 64 bit

**Comment by dscho** [comment]
This is seriously too little information to go on. It would have been better to fill out the issue reporting template than to delete it almost wholesale: the template is designed to help craft meaningful bug reports.
