### ISSUE TITLE
Release Notes screen--aesthetic change request

### ISSUE THREAD

**Issue by rlbyrd** [git-for-windows/git#2294]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

N/A -- documentation issue
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17763.615], but N/A

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

This isn't a bug about the actual application.  Is is, rather, an aesthetic request.  Pasted in below are three screenshots--the git for Windows post-upgrade release notes screen that pops up automagically, a Win10 BSOD, and a Win7 BSOD.  

When performing a git upgrade at 5:30am, seeing a very similar shade of blue suddenly take up an entire monitor on a multi-monitor setup is disconcerting and needlessly alarming for about a half a second.  I respectfully request you choose another damn shade of blue for your release notes screen.

![github-relnotes](https://user-images.githubusercontent.com/15219934/63268657-83bb4480-c249-11e9-9691-ce1ba26651c8.png)
![bsod-win7](https://user-images.githubusercontent.com/15219934/63268676-89b12580-c249-11e9-9968-9d2df6ecbd7a.png)
![bsod-win10](https://user-images.githubusercontent.com/15219934/63268686-8fa70680-c249-11e9-9596-dda552d12ade.png)

 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
I guess the colour will be set in the css section within the part of the build-extra repo that does the release notes (.md)

A PR to change (with screen shot for comparison) would be welcomed. Best place to start is https://gitforwindows.org/#contribute (appears to also use the same colour - so also https://github.com/git-for-windows/git-for-windows.github.io)

(PS let's avoid the 'gone with the wind' word if we can to avoid any sentiment-bot feedback ;-)

**Comment by rimrul** [comment]
Well, that's also the colour scheme of the [website](https://git-for-windows.github.io). But maybe just adding a stripped down version of that silver header (i.e. no large logo, no download/contribute buttons, reduced height, ...) to the release notes could help with looking less like a BSOD?

**Comment by dscho** [comment]
> A PR to change (with screen shot for comparison) would be welcomed.

This would definitely be the appropriate course of action.
