### ISSUE TITLE
Installation error non-admin

### ISSUE THREAD

**Issue by jeffrson** [git-for-windows/git#2295]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 2.23.0 x64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? Win 10 x64

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I strongly believe that the bug doesn't depend on options.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Working as standard user, can elevate to local admin (which is in fact another user).

### Details

Starting setup, setting options, answer UAC prompt with user name of my local admin and their password:

---------------------------
Git 2.23.0 Setup
---------------------------
Setup was unable to create the directory "C:\Program Files\Git\tmp".
Error 5: Zugriff verweigert.
---------------------------
OK   
---------------------------

(which is "access denied").

When I start the setup via right click, "Run as admin", git4windows is installed fine.

**Comment by PhilipOakley** [comment]
Are you on a network managed system where there may be other restrictions enforced by your workplace?

My previous workplace required all installs to be done via the right click 'run as admin', and even then only for a certain fraction of users.
Also can you just confirm which location/package you downloaded from

**Comment by jeffrson** [comment]
> Are you on a network managed system where there may be other restrictions enforced by your workplace?

It's a domain connected PC, but as far as I know there are no additional restrictions regarding installation other than the need for a seperate local admin.
Strange thing is, btw, all the old files have been removed, when I'm looking for this "tmp" folder. Apart from empty "cmd" and "mingw64", that is.

> My previous workplace required all installs to be done via the right click 'run as admin', and even then only for a certain fraction of users.
> Also can you just confirm which location/package you downloaded from

It's from https://git-scm.com

**Comment by jeffrson** [comment]
Just installed the new 2.24 from https://gitforwindows.org - unfortunately still an error (apparently immediately after the setup requests name and password of admin user (note, I'm working as restricted user):

> ---------------------------
> Git 2.24.0 Setup
> ---------------------------
> Setup was unable to create the directory "C:\Program Files\Git\dev".
> Error 5: Zugriff verweigert.
> ---------------------------
> OK   
> ---------------------------

(Access denied)

BTW, it says it would rollback changes, but it doesn't. It seems it uninstalled all files but "C:\Program Files\Git\mingw64\etc".

BUT - when I run the setup itself as admin, it works flawlessly. So it seems, that something with the elevation during "normal" install is broken.

**Comment by dscho** [comment]
> Installation error non-admin

@jeffrson how do you even do that?

When I start the installer over here, it automatically elevates the installer...

**Comment by jeffrson** [comment]
Well, according to its manifest, the installer is, AFAICT, run "as invoker". And I'm working as just an ordinary user, not member of administrators group.

Such it asks for elevation right after setting all parameters.

**Comment by mfriedrich74** [comment]
Hi,

Innosetup has it's own elevation handling implemented. Since there are two
types of elevation, one where and admin just needs the admin token (I guess
the environment variables are taken over to elevated) and the other is
where an non-admin gets prompted for elevation with a username and
password. The second form switches the entire login session and possibly
variables are not taken over unless special care is taken?
Just a guess.

Best regards, Mike

**Comment by ge0rdi** [comment]
I'm experiencing similar issue as OP when doing `git update-git-for-windows`.
Here is my use case:

I'm running as standard (non-admin) user by default.
I've installed Git for all users (so it is located in Program Files) by running installer as admin.

Then when new Git version was available I did `git update-git-for-windows` from standard user command line.
Installer was downloaded and started, I was asked for admin password (so far so good) but then a message box with _access denied_ message was shown.

Old version of Git was uninstalled (so I guess the elevation worked well) but new version was not installed (like at this point installer was no longer elevated?).

I was looking at Inno Setup installer options and I believe [UsePreviousPrivileges](https://jrsoftware.org/ishelp/index.php?topic=setup_usepreviousprivileges) may need to be set in installer.
But I have zero experience with Inno so this is just my guess.

Hope it will help.

**Comment by 0x4161726f6e** [comment]
I have seen this behavior in my environment.  Organization security policy requires that no user operate with admin privileges, all admin access should be done through elevation.  SysAdmins and Devs have separate active directory accounts for elevating actions with admin access, all accounts that are allowed interactive login are standard user accounts.  Myself and a co-worker have both tried the update process which ended with GIT being uninstalled.  Running the downloaded GIT installer fails to install unless manually elevated.

Given the majority of GIT users are capable troubleshooters, I wouldn't call this a show stopper but this is super annoying.

**Comment by dscho** [comment]
@0x4161726f6e any suggestions how to address this issue? Maybe there's a way to change how the installer is called from `git update-git-for-windows`?

**Comment by dscho** [comment]
Closing this stale ticket.
