### ISSUE TITLE
Unable to generate SSH key

### ISSUE THREAD

**Issue by orjanno** [git-for-windows/git#2299]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```

$ git --version --build-options
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
**> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"**

$ cat /etc/install-options.txt
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I have three similar Windows 7 machines. Issue is present on two of them. I cannot find any relevant difference.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```
 - What did you expect to occur after running these commands?

Being able to type in a file name

 - What actually happened instead?

Instead of waiting for my input, it just jumps to a new prompt, so I'm not able to type the file name

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Does it work with plain [MSYS2](https://msys2.github.io/) (from which Git for Windows inherits its `ssh-keygen`)?

**Comment by orjanno** [comment]
I have installed MSYS2, and have the same problem there...

**Comment by dscho** [comment]
> I have installed MSYS2, and have the same problem there...

Then the problem is actually an MSYS2 bug, probably. Maybe you want to report it at https://github.com/msys2/MSYS2-packages?

**Comment by orjanno** [comment]
Thanks.

I have created an issue [here](https://github.com/msys2/MSYS2-packages/issues/1731)
