### ISSUE TITLE
SDK installer shouldn't discard output from the "mingw-get" stage

### ISSUE THREAD

**Issue by SamB** [git-for-windows/git#23]
I got some errors from the mingw-get stage of the SDK installation, but I can't easily report them because the window with the output insists on disappearing after everything is done.

(At least one of them is a 404 trying to download one of the packages.)

**Comment by sschuberth** [comment]
The installer already supports the `/log-mingw-get=<file>` option to log the output of mingw-get to a file, see how it is used [here](https://github.com/git-for-windows/sdk/blob/master/ci/install-here.cmd#L13).

If the error is about `wget` like

    mingw-get.exe: *** ERROR *** internal package specification error
    mingw-get.exe: *** ERROR *** can't get 'tarname' for non-release element <<<unknown>>>
    mingw-get.exe: *** ERROR *** please report this to the package maintainer
    mingw-get.exe: *** ERROR *** wget-1.12-1-msys-1.0.13-bin.tar.lzma: requires...
    mingw-get.exe: *** ERROR *** msys-libopenssl-*-msys-*-dll-100.tar: unresolved dependency (type 'eq')
    mingw-get.exe: *** ERROR *** msys-libopenssl-*-msys-*-dll-100.tar: cannot identify any providing package
    mingw-get.exe: *** ERROR *** please report this to the package maintainer

then it's [already known](https://dscho.cloudapp.net/job/sdk-test-installer/lastSuccessfulBuild/artifact/mingw-get.log). But it's not severe, just ignore it for now.
