### ISSUE TITLE
git svn branch fails during copy

### ISSUE THREAD

**Issue by jwhite** [git-for-windows/git#230]
D:\Source\git\test2>git svn branch test2 -m "test branch"
Copying http://zsvn/SourceControl/Professional/Trunk at r36495 to http://zsvn/SourceControl/Professional/FeatureBranches/test2...
Authentication failed: Unable to connect to a repository at URL 'http://zsvn/SourceControl/Professional/Trunk': No more credentials or we tried too many times.
Authentication failed at C:\Program Files\Git\mingw64/libexec/git-core\git-svn line 1196.

Standard "svn copy" succeeds.

Manually specifying a user does not succeed.

The user is authenticated against a windows domain if that is part of the issue.

**Comment by dscho** [comment]
You might want to consider coming up with a [Minimal, Complete, Verifiable Example](http://stackoverflow.com/help/mcve) ("MCVE"). Without that, it is asking volunteers a bit much to even just try to reproduce the problem.

Ideally, that MCVE comes in the form of a patch to Git's own test suite.

**Comment by jwhite** [comment]
dscho : While I understand how that would be helpful, if I could code in python I would have solved the problem by now on my own and submitted a patch.

For me, git svn branch currently fails on *all* repositories I have access to (all are over http://)

How do you suggest I provide more of an example then that?  

It appears to me an issue in the underlying svn python extension if I dump the variables (but hey, I am on day 1 of learning python just to do that...)

Perhaps you need to update it in the distribution or take it up with the developer?  As is, git is broken in my workplace.

**Comment by dscho** [comment]
> the test suite is in c

POSIX shell.

> For me, git svn branch currently fails on all repositories I have access to (all are over http://)

It works flawlessly for me when I run

```sh
git svn clone -s https://github.com/dscho/images.git
```

> How do you suggest I provide more of an example then that?

Initialize a local (`file:`) repository. Commit to it using `svn`. Try to `git svn clone` it. If it fails, make a `.zip` from the svn repository and I will try to reproduce here. If it does not fail, try a couple more `svn` commits/branches/tags until it fails.

> It appears to me an issue in the underlying svn python extension

Perl extension.

> Perhaps you need to update it in the distribution or take it up with the developer? As is, git is broken in my workplace.

Git is not broken here. Even `git svn` works flawlessly here.
