### ISSUE TITLE
Can't pull data

### ISSUE THREAD

**Issue by ghostman221** [git-for-windows/git#2301]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git pull

** insert your machine's response here **
```	Update failed
			warning: failed to restrict file handles (87)
			
			handle #0: 0000000000000270 (type 3, handle info (1) 0
			handle #1: 00000000000003a0 (type 3, handle info (1) 1
			handle #2: 0000000000004b28 (type 3, handle info (1) 1
			
			This is a bug; please report it at
			https://github.com/git-for-windows/git/issues/new
			
			To suppress this warning, please set the environment variable
			
			SUPPRESS_HANDLE_INHERITANCE_WARNING=1
			
			remote: Invalid username or password.
			Authentication failed for 'https://github.com/*****/****.git/'

 -  Windows 10 64-bit

**Comment by PhilipOakley** [comment]
Please do fill in the template. What's your Git version `git version`. That reported warning was common on an old specific version and should have been resolved for all users. Try upgrading to a recent [release](https://github.com/git-for-windows/git/releases/).

**Comment by dscho** [comment]
Let's just close this ticket. The report is too incomplete in its current state.
