### ISSUE TITLE
New release not getting downloaded

### ISSUE THREAD

**Issue by sivaraam** [git-for-windows/git#2306]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.295]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

    - I have enabled auto-update during installation.

### Details
At random times, I see a window popping up that asks me whether to download the latest version of Git which is 2.23. When I click on 'Yes' nothing seems to be happening as a consequence. I'm not sure what it is supposed to do (or) how to make the update work.

 - What did you do to trigger this issue? If you can provide a
Clicked on 'Yes' in the auto-update window.

 - What did you expect to occur?
That the latest version would be downloaded and installed.

 - What actually happened instead?
Nothing happens. The window just goes away after I click. No new window pops up.

### Observation about updating Git for Windows
Also, I couldn't find any way to manually trigger the update. This makes me think that the only way other than auto-update (which doesn't seem to work) to update Git is to download the installer for the latest version from the releases page and install it. This is my understanding, let me know if I'm wrong.

**Comment by PhilipOakley** [comment]
> Also, I couldn't find any way to manually trigger the update. This makes me think that the only way other than auto-update (which doesn't seem to work) to update Git is to download the installer for the latest version from the releases page and install it. 

- `git update-git-for-windows`

Maybe not noticed in the release notes (find them at C:\Program Files\Git\ReleaseNotes.html)..

(bug fix note: since v2.21.0) `git update-git-for-windows` (i.e. the auto updater of Git for Windows) now reports correctly when it failed to access the GitHub API.

(bug fix note: since v2.16.1) The 'git update' command has been renamed to `git update-git-for-windows` to avoid confusion where users may think that git update updates their local repository or worktree. 

So yes, maybe the `git update-git-for-windows` could/should be referenced on the [Git for Windows](https://gitforwindows.org/) home page, straight below the download button (i.e. "For existing users since.."). 

If you can manage a PR that would be great :wink: The repository for that page is linked at the last line of that page!

**Comment by dscho** [comment]
This issue is apparently addressed. In general, I prefer it when original reporters close the tickets after their concerns are taken care of.

**Comment by sivaraam** [comment]
I actually don't think this has been addressed completely. 🤔 I still do not know why the auto-update didn't do the job automatically updating Git when I told it to. This happened multiple times. But the last time I tried it worked i.e., it the installer for the new version showed up after some time.

I think it's better to leave this closed for now as I haven't seen the issue again since the last time the auto-update worked as it should. I'll re-open if I notice the issue again.

**Comment by dscho** [comment]
> I actually don't think this has been addressed completely.

@sivaraam there was no reaction from your side, so what was I supposed to think?

> I'll re-open if I notice the issue again.

If you notice it again, please follow @PhilipOakley's advice: use `git update-git-for-windows` on the command-line, hopefully this will give you some useful messages as to why it is not working for you.

**Comment by sivaraam** [comment]
> @sivaraam there was no reaction from your side, so what was I supposed to think?

Makes sense. There was nothing wrong in your conclusion that the issue has been resolved given the information you had. I was just trying to _clarify the actual status_. May be I could have mentioned that clearly. 🙂 

> If you notice it again, please follow @PhilipOakley's advice: use git update-git-for-windows on the command-line, hopefully this will give you some useful messages as to why it is not working for you.

Sure.
