### ISSUE TITLE
Git Bash for Windows: Fails to mv a directory with a subdirectory which name contains a non-alphanumeric character

### ISSUE THREAD

**Issue by hokiedsp** [git-for-windows/git#2308]
Never mind. It was an externally caused issue. Please remove this issue if possible.

**Comment by PhilipOakley** [comment]
> Resolved.

Always wort explaining to others (https://xkcd.com/979/) with the same issue what the problem was. 

I'm guessing that it needed quoting to save it from the ravages of shell expansion, or git ref/rev expansion.

**Comment by PhilipOakley** [comment]
@hokiedsp Thanks for the clarification. 
I'd forgotten about the file locking issue, and that Matlab can do the Git version control (though only as a hack add-on in my opinion, but then ... it is better than nothing)

**Comment by dscho** [comment]
@hokiedsp thank you for the explanation. You would not believe how many times I looked for solutions, only to find an account like yours, and only _then_ realizing that I had the exact same problem! So thank you on behalf of future me, too.
