### ISSUE TITLE
How to split file with its history?

### ISSUE THREAD

**Issue by k0st1x** [git-for-windows/git#2309]
currently we have one code file with deep history.
As code file grown it is necessary to split it.
but this action will drop history for the new extracted file.
how can i split one big code file to small files and save its history for the "blame" action?

or guide me where i should post this question?

**Comment by rimrul** [comment]
AFAIK, you can't.

There is one thing you can do though:

Let's say you split your file `main.c` into a `part1.c` and a `part2.c`. 

At some point you run git blame on `part2.c`. You find the line(s) you're interested in and see that ist was introduced in `54de6ab "split main.c in two parts"`. You then checkout `54de6ab~1` and run git blame on `main.c` and see wgere your lines where introduced.

**Comment by rimrul** [comment]
>is there any way to get official answer from git dev team?

>i asked here because https://github.com/git/git repo has no "issues" tab :(

Yes, the git project works exclusively via mailing list git@vger.kernel.org (text-only mails, HTML gets automatically rejected). You can send a mail, but they'll likely tell you the same thing. 

>is there exist technical limitation for git?

git blame works on the change history of the file, but the history of the split file doesn't start until you split the main file.

**Comment by k0st1x** [comment]
rimrul, thank you for detailed response
