### ISSUE TITLE
Issue with 2.23.0 : push won't check if pull is needed

### ISSUE THREAD

**Issue by tramiere2** [git-for-windows/git#2313]
Hi,

I have rolled out to 2.18.0 since 2.23.0 seems to force push even if pulling first is needed (just using "git push" as command). This has caused corrupted data in our git repository.

I don't know if I am the only one who encountered this behaviour.

This issue doesn't occur with version 2.18.0 : a warning appears saying that pulling is needed, which is the expected behaviour.

**Comment by PhilipOakley** [comment]
I'm sorry but I'm not understanding the command sequence and error messages or symptoms from your short description. 

Please could you also include the information requested in the reporting template, and a more detailed description of the issue.

**Comment by rimrul** [comment]
This does sound like it's related to this upstream issue: https://lore.kernel.org/git/143f7207-4428-81bb-877e-8bbeb9a79a1c@web.de/T/#t

**Comment by dscho** [comment]
> This does sound like it's related to this upstream issue: https://lore.kernel.org/git/143f7207-4428-81bb-877e-8bbeb9a79a1c@web.de/T/#t

Possibly.

> Please could you also include the information requested in the reporting template, and a more detailed description of the issue.

I think we waited long enough.
