### ISSUE TITLE
Update mintty to 2.0.1

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#232]
Hi mintty has recently restarted maintaining it please update mintty to 2.0.1 which was release on july 1st. It includes fixes for windows 8, 8.1 and 10.

**Comment by dscho** [comment]
We actually just use MSys2's mintty package as-is. The Git for Windows release bundled after MSys2's mintty package is upgraded will therefore be the first release with the new mintty.

Could you please open a PR patching [MSys2's mintty build script](https://github.com/Alexpux/MSYS2-packages/tree/master/mintty)? Our documentation [how to rebuild packages](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages) will come in handy.

**Comment by paladox** [comment]
Ok they have updated at https://github.com/Alexpux/MSYS2-packages/tree/master/mintty

**Comment by dscho** [comment]
Thanks!

**Comment by dscho** [comment]
As you can see [here](http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/), the new package was uploaded, so the next Git for Windows release will have the new mintty version! Nice!

**Comment by paladox** [comment]
Ok thanks.
