### ISSUE TITLE
Suggestion/question: Provide a way to install extra MinGW packages

### ISSUE THREAD

**Issue by codeape2** [git-for-windows/git#2320]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.2.windows.1
built from commit: 788debdfb6b794425a3b949dd1a0eb2425a72e96
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

---
Is there a supported/recommended way to install extra MinGW packages into a git-for-windows bash environment? I often install git for windows on Windows computers to get a basic set of command line tools like sed, awk, grep, find, tar etc.

Is there a way to to install extra MinGW packages, like `zip`?

I also asked a question on superuser.com: https://superuser.com/questions/1478397/installing-extra-packages-into-a-git-for-windows-mingw-installation

**Comment by codeape2** [comment]
Sorry, I found https://github.com/git-for-windows/git/issues/2270 after I submitted this issue.

**Comment by rimrul** [comment]
A closer match than #2270 is #1912
