### ISSUE TITLE
Git-2.23.0-64-bit for Windows does not deploy /dev/* directory

### ISSUE THREAD

**Issue by alkazandzhiev** [git-for-windows/git#2322]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

git version 2.23.0

Windows 10 64-bit.

Editor Option: VIM
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

### Details

Bash

readarray -t BRANCHES < <(git branch --color=always)

I got an error for missing "/dev/fd/62" file descriptor. As far as I could get it from playing with 2.22.0 and 2.23.0 versions the latter does not deploy the /dev/ derectory with the /dev/fd symlink and some other in it.

**Comment by alkazandzhiev** [comment]
Also if I take the /dev directory from 2.22.0 installation it seems to fix the issue.

**Comment by rimrul** [comment]
Seems like aduplicate of #2291

**Comment by alkazandzhiev** [comment]
Definitely, thanks! I'm closing this one.

**Comment by marcelser** [comment]
I hope this leads to a 2.24 install where this is fixed. This is really a important one it breaks sourcing bash completion scripts for kubectl and all others that exist

**Comment by dscho** [comment]
@marcelser the best way to ensure that is by testing the latest snapshot from here: https://wingit.blob.core.windows.net/files/index.html
