### ISSUE TITLE
subtree push leads to segmentation fault

### ISSUE THREAD

**Issue by oliverbl** [git-for-windows/git#2332]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17134.950]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git subtree push --prefix=<directory> <origin> <branch>
```
 - What did you expect to occur after running these commands?

push my subtree to its remote

 - What actually happened instead?

C:/Program Files/Git/mingw64/libexec/git-core\git-subtree: line 757:  1641 Done                    eval "$grl"
      1642 Segmentation fault      (core dumped) | while read rev parents; do
    process_split_commit "$rev" "$parents" 0;
done

It worked for a while, but now there is always a segmentation fault.

I also tested the git subtree split method:
```
git subtree split --prefix=<directory>
```
This also leads to a segmentation fault.
I can see that git is going through all commits and at some specific commit it seems to enter an inifinite loop and goes out of memory.
After some research I found this report which seems to be related: 
https://www.spinics.net/lists/git/msg350022.html

Edit:
after trying out some older versions, I found that the problem was introduced in version v2.20.0 (https://github.com/git-for-windows/git/releases/tag/v2.20.0.windows.1)

Im using this release v2.19.2 now, which works.
https://github.com/git-for-windows/git/releases/tag/v2.19.2.windows.1

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

not possible unfortunately

**Comment by dscho** [comment]
This sounds like it might be caused by an anti-malware (we saw similar reports in the past that were caused by anti-malware going haywire about our version of the MSYS2 runtime, which tries to emulate Ctrl+C faithfully but has to create remote threads to do so).

Since you have pinpointed the exact breaking point for you, would you mind testing v2.20.0 (use a portable Git to avoid touching your working setup) with the `usr\bin\msys-2.0.dll` copied from v2.19.2?
