### ISSUE TITLE
Unescaped output

### ISSUE THREAD

**Issue by K2ouMais** [git-for-windows/git#2339]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

** git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 x64 (latest version)
```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.18362.356] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** Nothing **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Git Bash, vscode and PHPStorm **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Run "php artisan insights" after installing the package nunomaduro/phpinsights in a Laravel project. Using the same Git installation, it seems to work in vsCode, but it doesnt work on the normal Git Terminal and on PHPStorm.

```
** php artisan insights **
```
 - What did you expect to occur after running these commands?

```
** I was expecting to see a graphical output **
```
 - What actually happened instead?

```
** Lots of unescapeed chars **
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
```
** Nothing **
```
vsCode: (Here is how it should look like)
![Git_Vscode](https://user-images.githubusercontent.com/52510455/65511312-32047a80-ded7-11e9-8924-d6f2025abc0d.png)

Git Bash:
![Git_Problem](https://user-images.githubusercontent.com/52510455/65511305-2fa22080-ded7-11e9-91eb-101ef790089d.png)

PHPStorm:
![Git_PHPStorm](https://user-images.githubusercontent.com/52510455/65511314-33ce3e00-ded7-11e9-9b4a-336ee153408a.png)

**Comment by PhilipOakley** [comment]
have a look at the [FAQs ](https://github.com/git-for-windows/git/wiki/FAQ) and search for `winpty`.

See if reading the section helps.

**Comment by K2ouMais** [comment]
Even with winpty the output is broken.

**Comment by dscho** [comment]
@K2ouMais maybe you need to adjust `TERM`? If everything else fails, `TERM=dumb` should get rid of those ANSI sequences (which is not really unescaped output).
