### ISSUE TITLE
Git-Gui: failure to distinuish 3-way common ancestors in hunk markers

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#2340]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 
64-bit (sdk)
```
$ git --version --build-options

git version 2.22.0.rc3.windows.1.380.gef5ddde56c.dirty
cpu: x86_64
built from commit: ef5ddde56cd95128ec1bba450bd2e4c21dc77898
sizeof-long: 4
sizeof-size_t: 8

```
- Also
```
$ git version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8
[1]+  Done                    git gui
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.737]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This is likely a long term 'bug'. This report is to have a place to capture the screen shot.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash/mintty

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
phili@Philip-Win10 MINGW64 /c/git-sdk-64/usr/src/git (size_t_6rebase)
$ git rebase --onto origin/master 9c8cba6862abe5ac821

...
Falling back to patching base and 3-way merge...
...
error: Failed to merge in the changes.
...
$ git gui &
 [shows view below]

```
 - What did you expect to occur after running these commands?

I'd hoped that the git-gui would cope with the 3-way merge conflict markers 
`||||||| merged common ancestors`

so that they were marked in the 'third' colour (orange) and form an distinct option for selecting which side of the merge could be selected

 - What actually happened instead?

The conflict markers, and common ancestor lines, are treated as being part of the current HEAD

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I believe it is a general issue.

![image](https://user-images.githubusercontent.com/914343/65521484-39c91c80-dee1-11e9-8d87-a95090b1206a.png)

**Comment by bertwesarg** [comment]
I proposed a fix for this here: https://github.com/bertwesarg/git-gui/tree/bw/diff3-conflict-style

**Comment by dscho** [comment]
@bertwesarg great! This is what you contributed at https://public-inbox.org/git/97013a71289857767100d6a4adcb39ca99b2b21b.1569845908.git.bert.wesarg@googlemail.com/, right?

**Comment by bertwesarg** [comment]
It is, only that I already send out v3. But only 1/2 made it to the list. The branch is up-to-date though.

**Comment by prati0100** [comment]
This is merged upstream as https://github.com/prati0100/git-gui/commit/69fdb922ad1364a2752e1e444407f2aebd089ddf so this issue can be closed.
