### ISSUE TITLE
Multiple update notification message boxes

### ISSUE THREAD

**Issue by pwlsjk** [git-for-windows/git#2347]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Wersja 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Windows 7 as Hyper-V virtual machine

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

None

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
None
```
Auto updater notifications appears.

 - What did you expect to occur after running these commands?

_Single windows with notification._

 - What actually happened instead?

_Multiple windows with notifications._

![Adnotacja 2019-10-04 121302](https://user-images.githubusercontent.com/17168202/66204327-ead27280-e6aa-11e9-82a9-0c27877d3a20.png)

**Comment by PhilipOakley** [comment]
Wow. What fun. What date does the Virtual machine think it is...?

The updater is IIRC in the build-extra repo https://github.com/git-for-windows/build-extra

**Comment by dscho** [comment]
That's strange. We [try specifically to avoid multiple instances of the update](https://github.com/git-for-windows/build-extra/blob/9908e84c2403d6086c3bafb004a509a69248b6ab/installer/install.iss#L2281):

```xml
<MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
```

I see, however, that this is on Windows 7. Maybe the Task Scheduler on this operating system (that will see its end of life this coming January, by the way) ignores that tag? @pwlsjk can you check?

**Comment by rimrul** [comment]
The documentation for `MultipleInstancesPolicy` says it's supported on Vista/Server 2008 and up. That shouldn't be the problem here. How do we launch this? Does the `git-bash.exe` process launched by the scheduler exit before the message box gets closed?

**Comment by rimrul** [comment]
>Does the git-bash.exe process launched by the scheduler exit before the message box gets closed?

This does not seem to be the case. Unless I manually kill a process in the chain (`git-bash.exe`, multiple `sh.exe` processes, multiple `git.exe` processes) this does not happen. The task scheduler on Windows 7 revognizes the running process and doe not open another messagebox.

Something on @pwlsjk 's machine seems to kill one or more intermediate processes.

**Comment by dscho** [comment]
> How do we launch this?

When asked to run update checks automatically, the installer [registers a scheduled task](https://github.com/git-for-windows/build-extra/blob/9908e84c2403d6086c3bafb004a509a69248b6ab/installer/install.iss#L2269-L2309). This task [runs the following command](https://github.com/git-for-windows/build-extra/blob/9908e84c2403d6086c3bafb004a509a69248b6ab/installer/install.iss#L2300-L2301):

```cmd
git-bash.exe --hide --no-needs-console --command=cmd\git.exe update-git-for-windows --quiet --gui
```

which in turn runs [the shell script `git-update-git-for-windows`](https://github.com/git-for-windows/build-extra/blob/9908e84c2403d6086c3bafb004a509a69248b6ab/git-extra/git-update-git-for-windows).

> Something on @pwlsjk 's machine seems to kill one or more intermediate processes.

Sounds like it, doesn't it?

**Comment by rimrul** [comment]
I have a new hunch what might cause this. `StartWhenAvailable`. I think the task scheduler might not properly check for running instances (or fail to detect freshly started instances) if it missed multiple scheduled executions and tries to follow them all up. I also think we can't drop the `StartWhenAvailable` setting, as that would cause issues with systems that where installed at a time they usually not in use.

**Comment by kdekaluga** [comment]
It's Sep 2021 and I'm still having this issue on Windows 7. I just left my work PC unattended for some time (maybe, about a week), then opened RDP session and saw the following:

![image](https://user-images.githubusercontent.com/19360345/133238830-c09faa09-2409-468c-8ea0-0fbf78bcf5c1.png)

I have git version 2.32.0.windows.2

This is quite frustrating.

**Comment by dscho** [comment]
> This is quite frustrating.

It might be best if you reinstall Git for Windows and uncheck the "auto-update" option.
