### ISSUE TITLE
Git push on file remote - permission handling

### ISSUE THREAD

**Issue by toninlg** [git-for-windows/git#236]
Hi,

I had a problem with a force pushed after an amend commit. I asked the question on git mailing list: http://git.661346.n2.nabble.com/Git-force-push-fails-after-a-rejected-push-unpack-failed-td7635171.html. 
They proposed a patch, but why at the first place are the permission differents for files under objects dir on the remote?
I've made tests with git on Linux Mint and git-for-windows:
1) Linux Mint:
- ntfs share mounted (with noacl) since
$ chacl -l /the/mountpoint gives
chacl: cannot get access ACL on '/the/mountpoint': Operation not supported
- Create a remote repository on the ntfs share
- Push some test files
- ls -al for files in the objects folder gives:
-rw-r--r--
- with subsequent amend, push the permissions stays the same.

2) On Windows:
- ntfs share mapped as drive by windows
- remote repository created by git on windows
- Push some test files
- ls -al for files in the objects folder gives:
-r--r--r--
- chmod all files to add w permission
- then amend commit and push, push is successful but all files rewritten
by the push are again:
-r--r--r--
but all folders under objects are:
drwxr-xr-x 

Umask is 022 on both, but with noacl, I don't know if it's relevant?

Why does git rewrite files and attribute them read only permission while on Linux, they have always rw permissions for current user? 

git v2.3.5 (git-for-windows).

Thank you.

**Comment by dscho** [comment]
Please understand that the permission system is very different between Windows and POSIX file systems. The `-rw-r--r--` mode simply does not exist in Windows (because the ACLs are much more finegrained than the user/group/other hierarchy). I believe we cannot do anything about that... :frowning:

**Comment by toninlg** [comment]
Yes, but with a ntfs shared from a windows XP machine mounted with noacl on linux with username x, the permissions are handled by the permissions given on the windows XP machine? I'm member of a group that as rw access to the share. If I touch a file from linux, it is created with rw permissions.
With the same ntfs shared from the windows XP machine mapped as drive under Windows 7 with username x (same as the Windows 7 machine), the permissions are also handled by windows XP machine? If I touch a file from git-for-windows, it is created with rw permissions.

So in both cases, I can create rw files, but why with git under linux, files under objects folder are created with rw permissions whereas with git-for-windows, they are created with r permission only?

**Comment by dscho** [comment]
> I'm member of a group that as rw access to the share.

The point is: unlike POSIX permission system expects, NTFS files do not have one single owner and one single group attached to it. It just does not work that way with ACLs.

**Comment by toninlg** [comment]
Sorry, I don't understand.
What is the difference on git-for-windows between touching a file and pushing something? What is the mechanism by which git choose to create files under objects read-only?
Maybe should I mount directly the share under git-for-windows with noacl if possible like under linux because using Windows 7 to map the drive makes something different?

**Comment by toninlg** [comment]
Under linux the share is mounted with -t cifs, -t option doesn't exist with msys2 mount. It's not possible to do the same as in linux?

**Comment by dscho** [comment]
"Touching a file" or "pushing something" is a red herring. What you are talking about is file permissions, fair and square. It does not matter by which mechanism the files are written, but it matters that they are written via the Win32 API over a mapped drive. That means that Win32 permission semantics apply, and that something tries to map those permissions to Unix permissions if that mapped drive is actually backed by a Linux server. And that is where things go wrong.

> Under linux the share is mounted with -t cifs, -t option doesn't exist with msys2 mount.

Ah, but then it is Linux' permission semantics that apply, not Win32 API.

> It's not possible to do the same as in linux?

No. We are talking about Windows, remember? Windows and Linux are very different in certain areas, the one we are talking about being one of them.

**Comment by toninlg** [comment]
> "Touching a file" or "pushing something" is a red herring.
With git-for-windows if I touch a file on the share where my user as all access (excepted full control and special permissions) or if I push something on the share, what is the difference? The permissions are handled differently in both cases? It is not my user that asks to create the files in both cases?
I had no problem to git init the bare repository on the share from git-for-windows and the same setup used when I try to push.

> Ah, but then it is Linux' permission semantics that apply, not Win32 API.

The shared drive is backed by a windows xp machine. If it is mounted with noacl under linux, aren't the permissions handled by windows?

Is it possible to debug this and knowing if git asks to create a read only file or a rw that would not be honored by the share?

Thanks.

**Comment by dscho** [comment]
> Is it possible to debug this and knowing if git asks to create a read only file or a rw that would not be honored by the share?

Sure. You need to write and run a program to replicate the same functions as Git uses to initialize those read-only files. And then you need to go into more and more detail diagnosing the problem until you know at which point it goes wrong.

**Comment by toninlg** [comment]
Hi,
Patch 2.5.0.rc1.340.ge59e3eb solved my problem to push from git-for-windows to a smb folder shared from another Windows computer.

**Comment by dscho** [comment]
Great! Thanks for following up and concluding this ticket.
