### ISSUE TITLE
`git clean -ffdx` fails to remove some directories with "Permission denied" error

### ISSUE THREAD

**Issue by nocnokneo** [git-for-windows/git#2365]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

```
$ git --version --build-options

git version 2.23.0.windows.1                                                                                                    
cpu: x86_64                                                                                                                     
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce                                                                     
sizeof-long: 4                                                                                                                  
sizeof-size_t: 8                                                                                                                
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.1069]                                                                                     
```

Using PortableGit extracted to `C:\Git-2.23.0`

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Tested with both Bash and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
mkdir testrepo
cd testrepo
git init
curl -sSLO https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5125/qt.qt5.5125.win64_msvc2017_64/5.12.5-0-201909090442qttranslations-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z
# Tested with CMake 3.15.3
cmake -E tar xf 5.12.5-0-201909090442qttranslations-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z
git clean -ffdx
```
 - What did you expect to occur after running these commands?

No error messages and to have an empty git working directory.

 - What actually happened instead?

`git clean` fails to remove the directories:

```
Deletion of directory '5.12.5/msvc2017_64/translations' failed. Should I try again? (y/n) n
warning: failed to remove 5.12.5/msvc2017_64/translations: Permission denied
```

```
$ find *
5.12.5
5.12.5/msvc2017_64
5.12.5/msvc2017_64/translations
```

However from a Git Bash shell the directories can be removed just fine with `rm -r` or `rmdir`:

```
$ rmdir 5.12.5/msvc2017_64/translations
$ rm -r 5.12.5/
```

Running `find * -type d | xargs chmod g+w` before running `git clean -ffdx` also fixes the problem.

**Comment by assarbad** [comment]
Hello there. I was trying to reproduce this.

I can confirm the symptoms on a Windows 10 (1903) [you have 1809].

```
$ git clean -ffdx; find 5.12.5 -type d -exec ls -ld {} +
Deletion of directory '5.12.5/msvc2017_64/translations' failed. Should I try again? (y/n) y
Deletion of directory '5.12.5/msvc2017_64/translations' failed. Should I try again? (y/n) n
warning: failed to remove 5.12.5/msvc2017_64/translations: Permission denied
drwxr-xr-x 1 Oliver 197121 0 Sep  9 06:43 5.12.5
drwxr-xr-x 1 Oliver 197121 0 Sep  9 07:34 5.12.5/msvc2017_64
drwxr-xr-x 1 Oliver 197121 0 Oct 28 07:40 5.12.5/msvc2017_64/translations
```

I _think_ the reason is likely this:

```
$ find 5.12.5 -type d|while read fname; do attrib $(cygpath -w $fname); done
                     C:\Users\Oliver\Desktop\git-for-windows\testrepo\5.12.5
                     C:\Users\Oliver\Desktop\git-for-windows\testrepo\5.12.5\msvc2017_64
     R               C:\Users\Oliver\Desktop\git-for-windows\testrepo\5.12.5\msvc2017_64\translations
```

I don't know enough about how the Cygwin/MSYS2 file modes are mapped to the Windows file attributes and vice versa, but clearly the file mode `drwxr-xr-x` does _not_ properly reflect the readonly attribute set on the "Windows-side" of the affair.

**Comment by dscho** [comment]
> I can confirm the symptoms on a Windows 10 (1903) [you have 1809].

So this happens already without building via CMake, just after unpacking?

**Comment by assarbad** [comment]
> > I can confirm the symptoms on a Windows 10 (1903) [you have 1809].
> 
> So this happens already without building via CMake, just after unpacking?

Correct. The file attribute is obviously contained in the .7z archive.

**Comment by dscho** [comment]
> > > I can confirm the symptoms on a Windows 10 (1903) [you have 1809].
> > 
> > 
> > So this happens already without building via CMake, just after unpacking?
> 
> Correct. The file attribute is obviously contained in the .7z archive.
> 
> The CMake invocation in the original post above is simply an OS-agnostic means of unpacking a number of archive formats. As I understand it is internally based on `libarchive`. See [here](https://cmake.org/cmake/help/latest/manual/cmake.1.html#run-a-command-line-tool). So there is no _build_ with CMake in the given sequence of commands.

And the culprit is not that Git refuses to `git clean` write-protected directories, but that it keeps trying instead of warning about the issue, correct?

**Comment by nocnokneo** [comment]
> And the culprit is not that Git refuses to git clean write-protected directories, but that it keeps trying instead of warning about the issue, correct?

I think `git clean` should just delete the directories. `rm -r` (from Bash), `del` (from cmd), and interactively deleting the files through `explorer.exe` all have no problem deleting the directories (and according to the permissions shown by `ls -l` they are correct in doing so). So `git clean` is the odd man out here.

**Comment by dscho** [comment]
> `rm -r` (from Bash)

Oh? Are you sure you didn't mean `rm -rf` (note the `f`)?

**Comment by nocnokneo** [comment]
> Oh? Are you sure you didn't mean rm -rf (note the f)?

No, the `-f` option is not necessary.

**Comment by dscho** [comment]
@nocnokneo so a more minimal example would be to use `attrib` to set the `R` flag on an untracked, unignored file, and then use `git clean -dfx`, right?

**Comment by nocnokneo** [comment]
Yep, that sounds right. I guess I didn't distill my failing use case as far as it could go.

**Comment by dscho** [comment]
> Yep, that sounds right.

Very good.

> I guess I didn't distill my failing use case as far as it could go.

That's all right, I think this should do it, for any interested party to drive this further:

```sh
git init clean-test
cd clean-test
mkdir dir
"${COMSPEC%cmd.exe}attrib.exe" +R dir
git clean -fd
```

**Comment by dscho** [comment]
> ```shell
> "${COMSPEC%cmd.exe}attrib.exe" +R dir
> ```

(Obviously, this wants to be run in a Bash.)

**Comment by assarbad** [comment]
What's the course of action you deem sensible here, @dscho ? Do you think this is more something to fix at the MSYS/MinGW/Cygwin layer or something that should/could be specific to Git for Windows?

This seems like a "low-hanging" fruit, but one with the potential to be annoying to users, so I'm willing to step up _if_ you say it can be fixed as part of Git for Windows (i.e. discounting the layer that tries to make Windows appear unixy enough for Git).

**Comment by dscho** [comment]
> Do you think this is more something to fix at the MSYS/MinGW/Cygwin layer or something that should/could be specific to Git for Windows?

The `git clean` command is a built-in, i.e. it does not use MSYS/Cygwin. So I think any workaround will need to work specifically in Git for Windows.

I am not sure that this should be top priority, as it is kinda rare to tell Windows that certain files cannot be modified or deleted, and then ask Git to modify or delete them.

**Comment by dscho** [comment]
Closing as stale.
