### ISSUE TITLE
(German) Umlaut in passprase for https

### ISSUE THREAD

**Issue by lscheffler** [git-for-windows/git#2366]
I have problems connecting for push / pull for https remotes when password phrase conrains german umlaut äöü.  Umlaut ß is not tested.
Problem occurs only on git for windows, not on a debian system.    
Just plain username / password access

### Setup

git version 2.23.0.windows.1 , 64bit

```
$ git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win 8.1pro,  64 bit german
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push github master
```
 - What did you expect to occur after running these commands?

push?

 - What actually happened instead?

remote: Invalid username or password.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, it's Independent of repo. Independent of target server (gitlab, github) too.

**Comment by dscho** [comment]
> Use Credential Manager: Disabled

Can you verify that it works when you configure `git config --global credential.helper manager`?

**Comment by LunarLanding** [comment]
@dscho many thanks!
I had issues with a username that was an email. Configuring the global manager fixed it. However finding out the solution was frustrating experience. Hopefully one of these is done:
- prompting/forcing the user to setup the global manager
- fixing this issue in the default "manager"

**Comment by dscho** [comment]
>     * fixing this issue in the default "manager"
> 
> git-in-linux had no issues with the "at" symbol.

You mean the default "helper", there is no default "manager".

And yes, it would be nice to fix that problem, and if you have the time it would be nice if you could investigate.
