### ISSUE TITLE
[Uninstaller] Stop removing %Git%\bin from %PATH%

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [git-for-windows/git#237]
Every time Git updates, it performs uninstall of the previous version. This silently removes <Git>\bin entry from my %PATH%. This entry I add manually and only manually it must be changed. Why the uninstaller thinks it has the right to undo things the installer didn't? Version 2.4.5 32 bit

**Comment by dscho** [comment]
It is actually not users' business to out-guess the installer which directory/directories to add to the PATH. That is why we have that page in the installer that asks how you want to use Git: from `cmd.exe`, or adding all of the Unixy tools to the PATH or none of them.

Your intended goal would probably be better served by choosing the `cmd.exe` option (which adds the correct directory: `/cmd/` -- not `/bin/`, which is incorrect).

**Comment by Fr0sT-Brutal** [comment]
Okay, I moved my scripts and tools to `\cmd` and installed Git with `cmd.exe` option. Seems working for now. Thanks for showing the correct way.
