### ISSUE TITLE
git clone rpc error

### ISSUE THREAD

**Issue by xp19870106** [git-for-windows/git#2374]
- $ git clone https://github.com/ShiftMediaProject/FFmpeg.git
Cloning into 'FFmpeg'...
remote: Enumerating objects: 514693, done.
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by assarbad** [comment]
@xp19870106 could you please have a look at the [issue template](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md) and add information about the environment (OS version, Git version ... settings) and the circumstances?

Personally I like to refer to Simon Tatham's (that's the author of PuTTY) guide: [How to report bugs effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html). It's available in several languages.
