### ISSUE TITLE
How to configure git for windows use plink?

### ISSUE THREAD

**Issue by arthur-s** [git-for-windows/git#2379]
I've installed Git for Windows 2.23.0
Pointed GIT_SSH to plink.exe.

Git pull/push doesn't work.
In older versions it worked fine. How to setup git with plink now?

**Comment by rimrul** [comment]
You'll need to configure 'ssh.variant'. The possible values are 'putty' and 'tortoiseplink'.

**Comment by dscho** [comment]
Is this bug report describing a bug, or just a user question?

**Comment by arthur-s** [comment]
@dscho it was a user question.
@rimrul thank you a lot, with ssh.variant it works. Issue can be closed.
