### ISSUE TITLE
Bundle rsync with git-for-windows

### ISSUE THREAD

**Issue by gama** [git-for-windows/git#238]
Any chance of adding `rsync` to the _Git for Windows_ package? It already has a few niche applications (`rtmpdump`, for instance) but `rsync`, which I consider super-useful, is not included...

**Comment by dscho** [comment]
At the moment, the aim is to *reduce* the size of the installers.

It appears that you might be better served using MSys2 directly (or via the Git SDK).

**Comment by dscho** [comment]
@gama tell you what... if you open a Pull Request imitating https://github.com/git-for-windows/build-extra/commit/423208fe2c562b0e1cec87099c628c1c9daf0c4e and https://github.com/git-for-windows/build-extra/commit/fd7edf48400a39cb4aff137f22eba59d0a10db00 (after testing) and mention how the installer size compares before and after the change, I will merge it.
