### ISSUE TITLE
Bash truncates a program's return value/error code/errorlevel to 8bits

### ISSUE THREAD

**Issue by chadbramwell** [git-for-windows/git#2385]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.19.0.windows.1
cpu: x86_64
built from commit: d96bb8bc6c636a8869140e860e72e7bdf64bd790
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.418]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Disabled
Enable Builtin Stash: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

*Run this in Bash, expected 256 got 0:*
```
echo "int main(){return 256;}" > test.c
clang test.c
./a.exe
echo $?
```
*Run this in CMD to get 256:*
```
echo int main(){return 256;} > test.c
clang test.c
a.exe
echo %errorlevel%
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I couldn't find where Bash was generated from otherwise I'd look into the code myself. Sorry!

**Comment by dscho** [comment]
Bash emulates Unix behavior, where the exit code is always truncated to 7 bits, actually.

So I fear that you are encountering expected behavior (even if _you_ did not expect it 😄).

**Comment by landstander668** [comment]
Yeah, this is definitely the case on Linux as well.
```
$ echo "int main(){return 256;}" > test.c
$ gcc test.c
$ ./a.out ; echo rc=$?
rc=0
```
