### ISSUE TITLE
fatal: exceeded maximum include depth (10) while including C:/Program Files/Git/etc/gitconfig

### ISSUE THREAD

**Issue by lychichem** [git-for-windows/git#2387]
- [√] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options

**git version 2.24.0.windows.1
cpu: x86_64
built from commit: 6a3fa2a1833f3c7ac71cefefe44b3a4b4138e220
sizeof-long: 4
sizeof-size_t: 8 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [版本 10.0.18363.449] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** No Such file because I'm using mingit-busybox-64bit. **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** No **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Powershell and CMD **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** Any git rrelated command, just like running "git" **
```
 - What did you expect to occur after running these commands?

**usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone     Clone a repository into a new directory
   init      Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add       Add file contents to the index
   mv        Move or rename a file, a directory, or a symlink
   restore   Restore working tree files
   rm        Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect    Use binary search to find the commit that introduced a bug
   diff      Show changes between commits, commit and working tree, etc
   grep      Print lines matching a pattern
   log       Show commit logs
   show      Show various types of objects
   status    Show the working tree status

grow, mark and tweak your common history
   branch    List, create, or delete branches
   commit    Record changes to the repository
   merge     Join two or more development histories together
   rebase    Reapply commits on top of another base tip
   reset     Reset current HEAD to the specified state
   switch    Switch branches

collaborate (see also: git help workflows)
   fetch     Download objects and refs from another repository
   pull      Fetch from and integrate with another repository or a local branch
   push      Update remote refs along with associated objects
'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system. **

 - What actually happened instead?

** fatal: exceeded maximum include depth (10) while including
        C:/Program Files/Git/etc/gitconfig
from
        C:/Program Files/Git/etc/gitconfig
This might be due to circular includes. **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** No **
The problem happens because of /etc/gitconfig circular includes itself. Comment all the [include] part in this file can immediatly fix this problem.

**Comment by dscho** [comment]
> I'm using mingit-busybox-64bit.

Aha!

MinGit is not intended to be installed into `C:\Program Files\Git`. It is intended to be bundled with the application(s) that want(s) to use Git...

If you _must_ "install" it into `C:\Program Files\Git` against all recommendations, it would probably make sense for you to remove the `[include]` section from the system gitconfig manually (I do not know off-hand whether `git config --system --unset include.path` would work, it might fail due to the circular include).

**Comment by lychichem** [comment]
Okay… I just don't want to install standard git because it takes too much disk space.... I only need ~30MB files (the size of MinGit) to use ordinary functions with VS Code, but I have to install 600MB+ files if I install standard git. If you say "MinGit is intended to be bundled with the application(s) that want(s) to use git", I think making code editors (like VS code) direct users to download Mingit will be a good idea.

**Comment by saracen** [comment]
@dscho I just stumbled across this.

> If you must "install" it into C:\Program Files\Git against all recommendations

Do you know if this recommendation is documented anywhere? Thank you

**Comment by dscho** [comment]
MinGit is intended to be bundled with applications that require Git's functionality. My assumption that you install MinGit inside that application's folder was implicit. I don't think that this is documented _specifically_ anywhere.

**Comment by saracen** [comment]
Thanks @dscho - we install it as part of a Docker image to reduce the size of the installation. Since we treat the docker image as our "bundle", installing git to "C:\Program Files\git" made as much sense to us as anywhere else.

**Comment by dscho** [comment]
@saracen then this comment applies to you:

> If you _must_ "install" it into `C:\Program Files\Git` against all recommendations, it would probably make sense for you to remove the `[include]` section from the system gitconfig manually (I do not know off-hand whether `git config --system --unset include.path` would work, it might fail due to the circular include).

**Comment by saracen** [comment]
> @saracen then this comment applies to you:
> 
> > If you _must_ "install" it into `C:\Program Files\Git` against all recommendations, it would probably make sense for you to remove the `[include]` section from the system gitconfig manually (I do not know off-hand whether `git config --system --unset include.path` would work, it might fail due to the circular include).

Thanks @dscho - `$env:GIT_CONFIG_NOSYSTEM=1; git config --system --unset-all include.path` does the trick. But we'll [consider installing it to an alternative path](https://gitlab.com/gitlab-org/gitlab/-/issues/239013#note_401347751) too.

**Comment by Martin-Joergensen** [comment]
I fixed the problem by simply commenting out a line in etc/gitconfig referring to the file itself.

The section looked like this:
[include]
	; include Git for Windows' system config in order
	; to inherit settings like `core.autocrlf`
	path = C:/Program Files/Git/etc/gitconfig

I disabled the last line:
[include]
	; include Git for Windows' system config in order
	; to inherit settings like `core.autocrlf`
	; path = C:/Program Files/Git/etc/gitconfig

That did the trick.

Martin
