### ISSUE TITLE
The `git config` command doesn't allow to use `\\` prefix for a domain name. Is it a bug?

### ISSUE THREAD

**Issue by Andrey-Bushman** [git-for-windows/git#239]
Both variants work fine:

`git config --global --add include.path "d:\dev\settings\gitconfig.txt"`
`git config --global --add include.path "d:\\dev\\settings\\gitconfig.txt"`

but first variant of them existing **creates an illusion** what this is correct also:

`git config --global --add include.path "\\hyprostroy\dev\settings\gitconfig.txt"`

but it is wrong. We must to use `\\\\` instead of `\\` for a domain name. Only these variants are correct:

`git config --global --add include.path "\\\\hyprostroy\dev\settings\gitconfig.txt"`
`git config --global --add include.path "\\\\hyprostroy\\dev\\settings\\gitconfig.txt"`

At this case it would be more logical to forbid using of first and penultimate variants. Is it the bug of first variant existing?

**Comment by dscho** [comment]
I think this is a misunderstanding of command-line quoting. A backslash is an escaping character. Bash seems to be nice and keep a backslash if it encounters a character after the backslash that does not need escaping. So `d:\dev\...` is working *despite* being incorrect. However, there is no rescuing the situation when a double-backslash is encountered: it *will* be interpreted as a single backslash because the backslash *needs* escaping, being the escape character itself.

Maybe you wanted to use single-quotes instead?

**Comment by PhilipOakley** [comment]
Both variants work fine:

  git config --global --add include.path "d:\dev\settings\gitconfig.txt"
  git config --global --add include.path "d:\\dev\\settings\\gitconfig.txt"

  but first variant of them existing creates an illusion what this is correct also:

  git config --global --add include.path "\\hyprostroy\dev\settings\gitconfig.txt"

  but it is wrong. Only this variant is correct:

  git config --global --add include.path "\\\\hyprostroy\\dev\\settings\\gitconfig.txt"

  Is it the bug of first variant existing?


Isn't the 'magic' case the one that starts "d:". 

That is, it detects that the path is an absolute drive path (starts with single [a-zA-Z] followed by ':') for windows, and that all others need to be backslash "\" escaped as double backslashes?

<\bikeshed> 

--

Philip

**Comment by Andrey-Bushman** [comment]
>Maybe you wanted to use single-quotes instead?

Oh, yes. It works fine. I used double quotes before.

@PhilipOakley, I don't understand you.

**Comment by PhilipOakley** [comment]
> @PhilipOakley, I don't understand you.

My bikeshed colour was that: IIUC Msys/Msys2 can detect when a path is a 'DOS' path, i.e. a path with a drive letter followed by a colon, and then take appropriate measures...

However dscho (a much better guru than I !), has come up with a better rationale, that bash itself will pass through a single escape character if the next char doesn't need escaping, which much better explains the situation. 

HTH

Philip
