### ISSUE TITLE
refreshing (Update F5) gitk when a new commit is present results in error

### ISSUE THREAD

**Issue by andrewsensus** [git-for-windows/git#2390]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Not the same; possibly related: https://github.com/git-for-windows/git/pull/2297

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

I took the version installed by today's upgrade. From cygwin, I see the following:

$ file /cygdrive/c/Program\ Files/Git/cmd/git.exe 
/cygdrive/c/Program Files/Git/cmd/git.exe: PE32+ executable (console) x86-64, for MS Windows

```
$ git --version --build-options

git version 2.24.0.windows.1
cpu: x86_64
built from commit: 6a3fa2a1833f3c7ac71cefefe44b3a4b4138e220
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10, 64-bit.

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.1069]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I chose defaults during the upgrade. I didn't take the experimental add -i. I checkin and checkout preserving newlines.

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

type 'C:\Program Files\Git\etc\install-options.txt'

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing comes to mind.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Normally powershell. I tried the same thing from CMD and got the same results.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
gitk or gitk --all
modify a file and create a new commit with the change on the current branch
press F5 in gitk
Observe the error message
```
 - What did you expect to occur after running these commands?

I expected the new commit to be visible with the current branch shown as now pointing to the new commit.

 - What actually happened instead?

I got an error message in a dialog with an OK button:

```
Error executing git log: wrong # args: should be "escape_filter_paths paths"
```

The new commit is not visible in gitk; the current branch is no longer visible in gitk.

Closing and opening gitk makes the new commit visible and shows the current branch pointing to the new commit.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A; Doesn't seem to depend on repository.

**Comment by dscho** [comment]
@andrewsensus could you please replace your `C:\Program Files\Git\mingw64\bin\gitk` with [the version](https://raw.githubusercontent.com/git-for-windows/git/8e17f70c53834d2c6561e8f8e8caa206f6c8483b/gitk-git/gitk) from https://github.com/git-for-windows/git/pull/2391, to verify that that PR fixes your problem?

**Comment by andrewsensus** [comment]
@dscho Yes, that works; thank you!

**Comment by dscho** [comment]
Thanks for reporting and testing!
