### ISSUE TITLE
Update available dialog/prompt should have better design

### ISSUE THREAD

**Issue by longzheng** [git-for-windows/git#2395]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.10024]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

N/A

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Daily update prompt

![image](https://user-images.githubusercontent.com/484912/68385091-27fbba00-01ad-11ea-9ce0-e91622778b98.png)

Dialog design/layout is very simple and does not provide any branding. It could be mistaken for a generic prompt or worst a spam/virus/adware dialog.

The dialog also lacks useful information such as the newer version number and existing version number, as well as a link to the release notes to find what has changed.

Clicking "Yes" also hides the dialog and does not provide any information. It feels like nothing happened when in fact it is downloading in the background.

 - What did you expect to occur after running these commands?

Wireframe mock up of what it could look like

![image](https://user-images.githubusercontent.com/484912/68385256-7315cd00-01ad-11ea-80e4-d5b4a4cde77f.png)

I suggest the dialog should show app logo, newer version number, link to release notes, new version release date, currently installed version number (not in wireframe), a progress bar when downloading and allow download to be cancelled

 - What actually happened instead?

N/A

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by rimrul** [comment]
Ok. This requires significant changes.

By that I mean changing porting the update script to C and rewriting large parts (Completely new WinAPI GUI, keep existing CLI, download can't be through curl any more, ...) and some change so we can actually retrieve the release notes of the released version without the changes for the next version,...

These changes would probably be up to you. How good is your C?

**Comment by mfriedrich74** [comment]
Maybe less of a big change is using the the task dialog in Windows.
See https://docs.microsoft.com/en-us/windows/win32/controls/task-dialogs-overview

It has a couple of customization capabilities and may provide enough to keep this code change small.
I do not know, maybe Tcl or other scripting languages used by Git may even have an interface for it, if you search.

**Comment by rimrul** [comment]
Tcl probably won't work (we switched to C for git--askyesno because of issues with tcl), shell probably doesn't have an interface for this and perl doesn't have much of an interface either. But this could potentially work.

The taskdialog can contain Hyperlinks (release notes), can show yes/no/cancel buttons, a progress bar, custom icons, so most things we'd need.

**Comment by rimrul** [comment]
Give me a couple hours to get back from work and I'll whip up a quick prototype.

**Comment by rimrul** [comment]
![update available window](https://user-images.githubusercontent.com/6178234/68423900-3a70f600-01a3-11ea-8c22-3551af445a27.png)
![downloading update window](https://user-images.githubusercontent.com/6178234/68423867-2927e980-01a3-11ea-8408-4e410900f54b.png)

I'm slowly getting somewhere. Please ignore the German buttons, that's just windows chosing the system locale for these.

The text alignment is wonky because that's one long string that needs to be indented with spaces.

**Comment by rimrul** [comment]
The changes to the current shell script are probably less than I originally thought, too.

**Comment by mfriedrich74** [comment]
I am pretty sure it supports some type of line breaks, e.g. \n or <br/>.

**Comment by rimrul** [comment]
Yeah, \n works great. There's one in the Screenshots above, just after the Hyperlink.

It's the alignment within a line (i.e getting the date and version number lined up) that works on spaces alone.

**Comment by dscho** [comment]
TBH I am curious why these dialogs show in the first place. I would have expected a Toast to be shown in the Action Center.

**Comment by rimrul** [comment]
To answer the question why the toast didn't work, could you @longzheng  run 
```shell
type wintoast.exe
wintoast.exe --appname "Git for Windows" --text "Download and install?" --expirems 15000
echo $?
```

and post the results?

**Comment by rimrul** [comment]
![Dialog with fixed alignment](https://user-images.githubusercontent.com/6178234/68489366-40201780-0247-11ea-81e3-3690e07a7fab.png)

I've got the alignment fixed an the hyperlink is working. The remaining steps before the pr are (in no specific order):

- [ ] fetch version / release date
- [ ] actually download something
- [ ] finalize return codes
- [ ] code cleanup
- [ ] make sure it compiles outside VS
- [ ] modify update script
- [ ] add flag to skip yes/no dialog (script was passed `--yes` or user already clicked yes in toast)
- [ ] prepare some stuff for a future update when progress bars get added to wintoast

**Comment by dscho** [comment]
> To answer the question why the toast didn't work

@rimrul to answer this, kindly have a look at https://github.com/git-for-windows/build-extra/pull/268

**Comment by dscho** [comment]
> To answer the question why the toast didn't work, could you @longzheng run
> 
> ```shell
> type wintoast.exe
> wintoast.exe --appname "Git for Windows" --text "Download and install?" --expirems 15000
> echo $?
> ```
> 
> and post the results?

This has been left unanswered for over a year. I vote for closing this ticket as stale. @rimrul are you okay with that?

**Comment by rimrul** [comment]
>This has been left unanswered for over a year. I vote for closing this ticket as stale.

That was really only a tangent. You found the root cause and fixed the missing toasts, but the original ticket is about the lack of a progress or activity indicator during download.

From my point of view this is only stale because I'm low on time. The issue still exists and we aren't really waiting for any user feedback.

**Comment by dscho** [comment]
Okay, then let's leave it open.

**Comment by dscho** [comment]
@rimrul should we still leave this open?

**Comment by dscho** [comment]
should we still leave this open?

**Comment by dscho** [comment]
should we still, _still_ leave this open?

**Comment by rimrul** [comment]
I'll reopen this when/if I get around to working on this again.

**Comment by dscho** [comment]
> I'll reopen this when/if I get around to working on this again.

Thank you!
