### ISSUE TITLE
Git for Windows update resets contents of ssh_config file

### ISSUE THREAD

**Issue by LostMekka** [git-for-windows/git#2396]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.418]
```

### Details

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I used the update dialog to start a Git for Windows update.

 - What did you expect to occur after running these commands?

I expect an updated Git for Windows, but with intact custom configuration (INSTALLDIR\etc\ssh\ssh_config in my case)

 - What actually happened instead?

The config file was overwritten with the default file contents, like when I install it for the first time.

### Relevance / possible misuse
From the lack of search results for this problem I get the feeling, that this file is not there to be modified. (at least in Git for Windows) I use the config file to set specific private keys for specific hosts, like this:
```
Host bitbucket.somehost.com
	IdentityFile ~/.ssh/id_rsa_bitbucket
Host gitlab.someotherhost.org
	IdentityFile ~/.ssh/id_rsa_gitlab
```
And this works as I intended, until the next update resets the file. But is this even the right way to do this? Maybe I am doing it the wrong way and this actually is not a bug? I'm not sure. 😊

**Comment by michaelblyons** [comment]
> From the lack of search results for this problem I get the feeling, that this file is not there to be modified. (at least in Git for Windows) I use the config file to set specific private keys for specific hosts, like this:
>
> ```
>Host bitbucket.somehost.com
>	IdentityFile ~/.ssh/id_rsa_bitbucket
>Host gitlab.someotherhost.org
>	IdentityFile ~/.ssh/id_rsa_gitlab
>```

I really think you'd be better served by creating a file with that content at `~/.ssh/config`. That's the normal "just for me" place.

**Comment by dscho** [comment]
> I really think you'd be better served by creating a file with that content at `~/.ssh/config`. That's the normal "just for me" place

I agree. The files in `C:\Program Files\Git` are not fair game; they are owned by the Git for Windows installation, and if you change anything in there, you _need_ to expect your edits to go away with the next upgrade/downgrade/reinstallation.

**Comment by LostMekka** [comment]
Thank you for your responses/advice. So there is a better way to do it. Nice :)
