### ISSUE TITLE
Wrong prompt for Git Bash

### ISSUE THREAD

**Issue by egvimo** [git-for-windows/git#2397]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.30]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

If I run the Git Bash in any directory (right click -> Git Bash Here), then the promt looks the following:

![2019-11-07 16_09_01-_usr_bin_bash --login -i](https://user-images.githubusercontent.com/5247100/68401416-fcaba780-0179-11ea-9046-9291419ef29e.png)

On my previous machine the prompt was correct (colored and with branch name).

**Comment by rimrul** [comment]
Could you run `echo $PS1`? It should output something like this:
```
\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
```

**Comment by egvimo** [comment]
This is the output:
```
-notebook:$PWD>
```

**Comment by rimrul** [comment]
That looks like it's deliberately been set. Have a look at `~/.bashrc`

**Comment by dscho** [comment]
There is also git-for-windows/build-extra@be3efc788b30e3b6b29d3421a13844a5eb9bb37f, i.e. `~/.config/git/git-prompt.sh` can override whatever Git for Windows wants to set for your prompt.

**Comment by egvimo** [comment]
I couldn't find this file.

But you pointed me to the cause of the problem (`~`): we have a network drive for each user. And somehow the home directory was set to this location instead of the default `C:\Users\myuser`.

Unfortunately I couldn't find where this is set. No setting in the environment variables and no setting in the registry.

But I solved the problem by setting the environment variable `HOME` to my users profile directory.

**Comment by fourpastmidnight** [comment]
This can be set by Group Policy by the domain admins, in which case, you won’t find it set in the usual locations. My organization has done that, too, in the past; and yes, it can wreak havoc with GfW and other programs when all of a sudden your configuration file and scripts “can’t be found”.

Sent from my Windows 10 phone

**Comment by dscho** [comment]
If `HOME` is not set, Git for Windows will automatically define it as `%HOMEDRIVE%%HOMEPATH%`: https://github.com/git-for-windows/MINGW-packages/blob/4f930a251909c0e8a03e2c0472c6d3a7d0a6b3b8/mingw-w64-git/git-wrapper.c#L131-L163 and https://github.com/git-for-windows/git/blob/v2.24.0.windows.2/compat/mingw.c#L2981-L3003

**Comment by egvimo** [comment]
@dscho According to the code you mentioning the fallback is `%USERPROFILE%`. In my case this would result in the correct user profile location.

**Comment by dscho** [comment]
> According to the code you mentioning the fallback is `%USERPROFILE%`.

@egvimo only if `%HOMEDRIVE%` or `%HOMEPATH%` are unset, _or_ if the path `%HOMEDRIVE%%HOMEPATH%` does not exist: https://github.com/git-for-windows/MINGW-packages/blob/4f930a251909c0e8a03e2c0472c6d3a7d0a6b3b8/mingw-w64-git/git-wrapper.c#L146-L150

**Comment by egvimo** [comment]
Yes, I understood that. Sorry, if my comment was misleading.

Both variables (`%HOMEDRIVE%` and `%HOMEPATH%`) are set in my environment. Unfortunately they lead to the network drive I mentioned. And therefor result in the wrong prompt.

The `%USERPROFILE%` variable is also set. And this variable points to the correct user profile location.
