### ISSUE TITLE
Incorrect displaying of pasting from the clipboard when the text contains cyrilic chars

### ISSUE THREAD

**Issue by Andrey-Bushman** [git-for-windows/git#240]
I want to write some settings into common config file. Command is long. I try to past this command from clipboard. It has cyrilic chars (Отдел) also:

`git config -f "\\\\hyprostr\\dfs\\groups\\Отдел IT\\@Bush\\dev\\settings\\gitconfig.txt" http.proxy http://@proxy2:8080`

but I see incorrect displaying of pasting result in Git Bash. Look an attached screen. Can I fix it?
![_0](https://cloud.githubusercontent.com/assets/10530134/8650755/73459696-297d-11e5-8d15-b0322c743232.png)

**Comment by dscho** [comment]
Are you sure that the paste is incorrect, as opposed to just the display?

**Comment by Andrey-Bushman** [comment]
Sorry, you are right. I edited my message and its title.

**Comment by dscho** [comment]
Thank you for your quick and clarifying response. I fear this is a question for the [mintty project](https://github.com/mintty)...

**Comment by Andrey-Bushman** [comment]
Ok, I posted it here: https://github.com/mintty/mintty/issues/461 and I close the current issue's topic.

**Comment by dscho** [comment]
Thanks!
