### ISSUE TITLE
bug:git stash pop -q in 2.24.0

### ISSUE THREAD

**Issue by hiroyuki-okazaki-shi** [git-for-windows/git#2406]
If you run the following command All files are deleted in the stage.

### version:
git version 2.24.0.windows.2 64bit
windows 10 pro 1809 64bit (Microsoft Windows [Version 10.0.17763.805])

### commands:

> D:\temp>md test1
> 
> D:\temp>cd test1
> 
> D:\temp\test1>git init
> 
> Initialized empty Git repository in D:/temp/test1/.git/
> 
> D:\temp\test1>echo test1>text.txt
> 
> D:\temp\test1>git add text.txt
> 
> D:\temp\test1>git commit -m commit1
> 
> [master (root-commit) 38a4da6] commit1
> 
> 1 file changed, 1 insertion(+)
> 
> create mode 100644 text.txt
> 
> D:\temp\test1>echo test2>>text.txt
> 
> D:\temp\test1>**git stash**
> 
> Saved working directory and index state WIP on master: 38a4da6 commit1
> 
> D:\temp\test1>**git stash pop -q**
> 
> D:\temp\test1>git status
> 
> On branch master
> 
> Changes to be committed:
> 
> (use "git restore --staged ..." to unstage)
> 
> **deleted: text.txt**
> 
> Untracked files:
> 
> (use "git add ..." to include in what will be committed)
> 
> text.txt
> 
> D:\temp\test1>dir /b
> 
> text.txt

**Comment by dscho** [comment]
@hiroyuki-okazaki-shi Can you test whether this patch fixes it? https://public-inbox.org/git/20191113150136.GB3047@cat/
