### ISSUE TITLE
Git for Windows updater does not show toast notification on Windows 10 (WITH FIX)

### ISSUE THREAD

**Issue by adrianghc** [git-for-windows/git#2409]
### Details

Since recently, the Git for Windows updater does not show a native toast notification as expected on Windows 10 but a small dialog box window.
I've pinpointed the cause for this to [this line](https://github.com/git-for-windows/build-extra/blob/285cfd53e625e19279f13323dd483f4819900164/git-extra/git-update#L133) in the Git updater.
At some point recently, `uname -s` has changed its behavior to not only include the major and minor version of windows in the output but also the build number - presumably to distinguish Windows 10 versions:

```
$ uname -s
MINGW64_NT-10.0-18363
```

This means that

```
case "$(uname -s)" in
	*-6.[23]|*-10.0
```

is never true, as the output does not actually end with `10.0` anymore, so the body of the case is never run, in particular `try_toast=t`.

The fix is to put a wildcard at the end as well so that the case returns true again:

```
case "$(uname -s)" in
	*-6.[23]*|*-10.0*
```

![image](https://user-images.githubusercontent.com/11506007/69458342-6083c200-0d6f-11ea-8257-95c334646eba.png)

The fix is such a minor change that I feel a pull request would be overblown but I can do it if you prefer to maintain that procedure. Otherwise I think you could commit this directly.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.18363.476]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

**Comment by dscho** [comment]
> The fix is such a minor change that I feel a pull request would be overblown

It wouldn't have been overblown. It would have been a very welcome relief of my maintenance burden. As it were, I think I [beat you to it](https://github.com/git-for-windows/build-extra/pull/268).
