### ISSUE TITLE
"ln -s2 copies instead of creating a symlink - symbolic link

### ISSUE THREAD

**Issue by softwaretechniker** [git-for-windows/git#2410]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
- Git-2.24.0.2-64-bit
```
$ git --version --build-options

git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
```
- Windows 10 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.476]
```

 - Installation options:
 "C:\Program Files\Git\etc\install-options.txt"
```
Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

- [x] Runned setup as administrator explicitly
- [x] Gave SeCreateSymbolicLink permission to login user before running setup and before running Git-bash

### Details

 - running **GIT bash** with full permissions

 - What commands did you run to trigger this issue?
```
ln -s existingTarget.file newSymlink.file
ln -s existingTarget-directory newSymlink-directory
```
 - What did you **expect** to occur after running these commands?

Creation of a **symbolic link** as alias for
```
mklink newSymlink.file existingTarget.file
mklink /d newSymlink-directory existingTarget-directory
```

 - What actually **happened** instead?

A **copy** of file / directory.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No specific repository - file system topic.

- What I also did:
- [x] Running Git-bash as administrator explicitly plus loginuser having SeCreateSymbolicLink
- [x] Complete deinstalltion of old git-bash + fresh installation of latest version

**Comment by dscho** [comment]
This behavior seems to be inherited from the MSYS2 project, probably because you require either administrative privileges to create symbolic links (and Windows 7 or later), or Windows 10 _in Developer Mode_.

**Comment by Thunder2425** [comment]
> * [x]  I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
> 
> ### Setup
> * Git-2.24.0.2-64-bit
> 
> ```
> $ git --version --build-options
> 
> git version 2.24.0.windows.2
> cpu: x86_64
> built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
> sizeof-long: 4
> sizeof-size_t: 8
> ```
> 
> * Windows 10 64-bit
> 
> ```
> $ cmd.exe /c ver
> 
> Microsoft Windows [Version 10.0.18362.476]
> ```
> 
> * Installation options:
>   "C:\Program Files\Git\etc\install-options.txt"
> 
> ```
> Editor Option: Notepad++
> Custom Editor Path: 
> Path Option: Cmd
> SSH Option: OpenSSH
> Tortoise Option: false
> CURL Option: OpenSSL
> CRLF Option: CRLFAlways
> Bash Terminal Option: MinTTY
> Performance Tweaks FSCache: Enabled
> Use Credential Manager: Enabled
> Enable Symlinks: Enabled
> Enable Builtin Interactive Add: Disabled
> ```
> 
> * [x]  Runned setup as administrator explicitly
> * [x]  Gave SeCreateSymbolicLink permission to login user before running setup and before running Git-bash
> 
> ### Details
> * running **GIT bash** with full permissions
> * What commands did you run to trigger this issue?
> 
> ```
> ln -s existingTarget.file newSymlink.file
> ln -s existingTarget-directory newSymlink-directory
> ```
> 
> * What did you **expect** to occur after running these commands?
> 
> Creation of a **symbolic link** as alias for
> 
> ```
> mklink newSymlink.file existingTarget.file
> mklink /d newSymlink-directory existingTarget-directory
> ```
> 
> * What actually **happened** instead?
> 
> A **copy** of file / directory.
> 
> * If the problem was occurring with a specific repository, can you provide the
>   URL to that repository to help us with testing?
> 
> No specific repository - file system topic.
> 
> * What I also did:
> * [x]  Running Git-bash as administrator explicitly plus loginuser having SeCreateSymbolicLink
> * [x]  Complete deinstalltion of old git-bash + fresh installation of latest version

**Comment by Thunder2425** [comment]
> * [x]  I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
> 
> ### Setup
> * Git-2.24.0.2-64-bit
> 
> ```
> $ git --version --build-options
> 
> git version 2.24.0.windows.2
> cpu: x86_64
> built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
> sizeof-long: 4
> sizeof-size_t: 8
> ```
> 
> * Windows 10 64-bit
> 
> ```
> $ cmd.exe /c ver
> 
> Microsoft Windows [Version 10.0.18362.476]
> ```
> 
> * Installation options:
>   "C:\Program Files\Git\etc\install-options.txt"
> 
> ```
> Editor Option: Notepad++
> Custom Editor Path: 
> Path Option: Cmd
> SSH Option: OpenSSH
> Tortoise Option: false
> CURL Option: OpenSSL
> CRLF Option: CRLFAlways
> Bash Terminal Option: MinTTY
> Performance Tweaks FSCache: Enabled
> Use Credential Manager: Enabled
> Enable Symlinks: Enabled
> Enable Builtin Interactive Add: Disabled
> ```
> 
> * [x]  Runned setup as administrator explicitly
> * [x]  Gave SeCreateSymbolicLink permission to login user before running setup and before running Git-bash
> 
> ### Details
> * running **GIT bash** with full permissions
> * What commands did you run to trigger this issue?
> 
> ```
> ln -s existingTarget.file newSymlink.file
> ln -s existingTarget-directory newSymlink-directory
> ```
> 
> * What did you **expect** to occur after running these commands?
> 
> Creation of a **symbolic link** as alias for
> 
> ```
> mklink newSymlink.file existingTarget.file
> mklink /d newSymlink-directory existingTarget-directory
> ```
> 
> * What actually **happened** instead?
> 
> A **copy** of file / directory.
> 
> * If the problem was occurring with a specific repository, can you provide the
>   URL to that repository to help us with testing?
> 
> No specific repository - file system topic.
> 
> * What I also did:
> * [x]  Running Git-bash as administrator explicitly plus loginuser having SeCreateSymbolicLink
> * [x]  Complete deinstalltion of old git-bash + fresh installation of latest version

Thunder2425
