### ISSUE TITLE
mysql client prompt doesn't work with Git 2.4.5.1-4th-release-candidate-64bit

### ISSUE THREAD

**Issue by fabriciofx** [git-for-windows/git#242]
I installed Git 2.4.5.1-4th-release-candidate-64bit in Windows 7 64 bit with mintty and when I try running mysql prompt ($mysql -u root -p), mysql hangs out and doesn't connect. But if I try Git 2.4.5.1-4th-release-candidate-64bit  with Windows command mysql works perfect. I think there is some problem with mintty.

**Comment by Dirk1966** [comment]
I have a problem with the following PS1, which works on all previous git for Windows platforms and on all LinUX / Unix platforms I know (this enables a unified prompt even on machines which do not have git):

export PS1='\[\t \033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] $(git branch &>/dev/null; if [ $? -eq 0 ]; then echo "\[\033[01;36m\]($(git branch | grep ^*|sed s/\*\ //))\[\033[00m\]"; fi)\n$ '

=>
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `git branch &>/dev/null; if [ $? -eq 0 ]; then echo "($(git branch | grep ^*|sed s/\*\ //))"; fi)'

**Comment by dscho** [comment]
> I installed Git 2.4.5.1-4th-release-candidate-64bit in Windows 7 64 bit with mintty and when I try running mysql prompt ($mysql -u root -p), mysql hangs out and doesn't connect. But if I try Git 2.4.5.1-4th-release-candidate-64bit with Windows command mysql works perfect. I think there is some problem with mintty.

@fabriciofx this is a known problem (see https://github.com/git-for-windows/build-extra/blob/43d672f/installer/ReleaseNotes.md#known-issues):

> * Some console programs interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

If you do not like that, feel free to choose the installer option not to use MinTTY.

Please note also that Git for Windows is *not* your "Linux on Windows". It really is supporting Git on Windows and not necessarily mysql.
