### ISSUE TITLE
System-wide gitconfig wrong in Git 2.24

### ISSUE THREAD

**Issue by Osse** [git-for-windows/git#2420]
I install Git for Windows inside an MSYS2 environment because I really like to have the whole suite of tools MSYS2 provides. It's working pretty well.

Git 2.24 seems to get the path to the system-wide `gitconfig` wrong. Git 2.23 doesn't. I noticed this when files on disk suddenly kept their LF terminators instead of being converted to CRLF. 

According to #29 the 2.23 behavior is correct, though that issue is several years old now. There's been some work recently (#2358) but I don't know if that's the culprit.

```
$ GIT_EDITOR=echo git config --system --edit 2>/dev/null
C:/tools/msys64/etc/gitconfig                
$ pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-git-2.23.0.1.4db2e5cc9e-1-any.pkg.tar.xz 
loading packages...   
warning: downgrading package mingw-w64-x86_64-git (2.24.0.2.02af2cc5bf-1 => 2.23.0.1.4db2e5cc9e-1)               
resolving dependencies...                    
looking for conflicting packages...          

Package (1)           Old Version            New Version            Net Change             

mingw-w64-x86_64-git  2.24.0.2.02af2cc5bf-1  2.23.0.1.4db2e5cc9e-1   -0.21 MiB             

Total Installed Size:  32.49 MiB             
Net Upgrade Size:      -0.21 MiB             

:: Proceed with installation? [Y/n]          
(1/1) checking keys in keyring                         [############################] 100% 
(1/1) checking package integrity                       [############################] 100% 
(1/1) loading package files                            [############################] 100% 
(1/1) checking for file conflicts                      [############################] 100% 
:: Processing package changes...             
(1/1) downgrading mingw-w64-x86_64-git                 [############################] 100% 
$ GIT_EDITOR=echo git config --system --edit 2>/dev/null
C:/tools/msys64/mingw64/etc/gitconfig        
$
```

**Comment by Osse** [comment]
I forgot some details:

```
$ git --version --build-options
git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
$
```

```
U:\>cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.864]

U:\>
```

`install-options.txt` doesn't exist. I use MinTTY and Zsh from MSYS2.

**Comment by dscho** [comment]
> I forgot some details:

That appears to be true. The _entire_ bug reporting template has been deleted, without appropriate replacement.

As it were, I believe that the underlying issue might be that you missed the [rather important release notes for v2.24.0](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#changes-since-git-for-windows-v2230-august-17th-2019) (which is no surprise, given that you seem to use Git for Windows in the unsupported, or maybe better: under-supported, way of installing the `mingw-w64-git` package into an MSYS2 environment):

> Note! As a consequence of making `git config --system` work as expected, the location of the system config is now `C:\Program Files\Git\etc\gitconfig` (no longer split between `C:\Program Files\Git\mingw64\etc\gitconfig` and `C:\ProgramData\Git\config`), and likewise the location of the system gitattributes is now `C:\Program Files\Git\etc\gitattributes` (no longer `C:\Program Files\Git\mingw64\etc\gitattributes`). Any manual modifications to `C:\ProgramData\Git\config` need to be ported manually.

Meaning: this is probably not a bug, but a known change in Git for Windows' behavior that firmly puts the "install it in your MSYS2 environment" users (including you) into the "you really _have_ to know what you are trying to do, and it would be better if you helped out rather than just stayed on the unsupported usage side, to make this more of a supported use case" department.

**Comment by dscho** [comment]
> Meaning: this is probably not a bug, but a known change in Git for Windows' behavio

I had hoped for a reply that confirms my suspicion or alternatively clarifies the concern, but I guess I am forced to interpret silence, and I choose to interpret it as confirmation.

**Comment by Osse** [comment]
I must have pasted the terminal over the message template and not noticed. I did notice the template afterwards which is why I added the rest in a comment. I have been on the receiving end in other situations where I had started to write a reply but by the time I was done the original post was completely different and I found that annoying. But in this case guess I should have edited the original issue to conform to the template instead.

And you were right: I missed the Windows-specific release notes. In my opinion this is clearly not a bug and you were completely right to close it.

So, I screwed up the bug reporting and due diligence on my part, and I'm sorry for that. Still, I couldn't avoid your reply as demeaning and that discouraged me from answering.

If installing Git for Windows into MSYS2 is so under-supported I suggest putting it in large red blinking letters on the top of the wiki article on how to do it. I am not forcing Git for Windows into vanilla MSYS2, neck deep in shit because of it and too stubborn to do anything about it. When you write "would be better if you helped out" the first thing I thought was "helped out with what, exactly?", because I have not had any problems that I haven't been able to work out in around 2 minutes (e.g. wait out on upgrading Perl for a couple of days, or give the aforementioned wiki article a new read). This was literally the first time in the 3 or 4 years I've used this setup I've been caught by surprise (and, admittedly, it shouldn't even have surprised me).

I'm somewhat proud of my contributions to the main Git project, either directly or indirectly (e.g. `#git`); it is on Linux I use Git the most after all. But I will take a look at this issue tracker to see if there's anything I know a thing or two about.

**Comment by dscho** [comment]
> If installing Git for Windows into MSYS2 is so under-supported I suggest putting it in large red blinking letters on the top of the wiki article on how to do it.

Done: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper (not red, not blinking, there is no Markdown support for that, it's not Geocities...)
