### ISSUE TITLE
Typo in installer

### ISSUE THREAD

**Issue by ctahok** [git-for-windows/git#2430]
![SpellingGIT](https://user-images.githubusercontent.com/17162642/70694633-031cca00-1cb8-11ea-8766-3b55e15e483d.jpg)

 - [ ] There is a typo in latest installer

### Setup

64-bit

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows 10 64-bit?

```
$ cmd.exe /c ver 

2.24.1.2
```

**Comment by rimrul** [comment]
As discussed in #265 and #2284 that is not a typo, but we're open to PRs that improve the wording.

The file to change here would be [install.iss in build-extra](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss#L1875).
