### ISSUE TITLE
grep which shipped with git crashes when i use options `F` and `i` together

### ISSUE THREAD

**Issue by NTMan** [git-for-windows/git#2434]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
C:\git\crm.test\core>git --version --build-options
git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
C:\git\crm.test\core>cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
C:\git\crm.test\core>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

C:\git\crm.test\core>cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\git\crm.test\core>"C:\Program Files\Git\usr\bin\grep.exe" -Fi -- leadsDetailsCausesComplete
      0 [main] grep 1995 cygwin_exception::open_stackdumpfile: Dumping stack trace to grep.exe.stackdump
```
 - What did you expect to occur after running these commands?

grep result

 - What actually happened instead?

grep is crashes

[grep.exe.stackdump.zip](https://github.com/git-for-windows/git/files/3967280/grep.exe.stackdump.zip)

![image](https://user-images.githubusercontent.com/200750/70896994-98e78a80-2013-11ea-9437-a99dba8e718d.png)

**Comment by dscho** [comment]
We do not actually custom-build `grep`, we use the `grep` package from the MSYS2 project. Maybe report it there (i.e. at https://github.com/msys2/MSYS2-packages/issues/new)?

**Comment by dscho** [comment]
Oh, I think I know what it is. MSYS2's executables are not meant to be called from CMD, they are meant to be called from MSYS2's Bash, more specifically: after `/etc/profile` had a chance to run.

So it is no wonder that in your use case, `LC_ALL` is not set, and it would appear that this triggers a code path that crashes.

You can easily fix this on your side by calling `set LC_ALL=C.UTF-8` first.

**Comment by dscho** [comment]
Since

1. you have a work-around,
2. you now know which bug tracker would be more appropriate for this bug, and
3. you don't answer me,

I will close this ticket.

**Comment by NTMan** [comment]
> you have a work-around,

Unfortunately work-around not worked. Yes, it solves the issue with crashes but for now `grep.exe` hangs when I apply `set LC_ALL=C.UTF-8` to `CMD` or launch from bash.

![image](https://user-images.githubusercontent.com/200750/71149353-1992ca80-2250-11ea-8a1c-f26c220dcf0a.png)
In this window with `grep.exe` running, nothing has been happening for a day.


The previous version didn't have this issue.

Anyway thanks for respond.
