### ISSUE TITLE
Pull from remote - handles warning message 

### ISSUE THREAD

**Issue by GlebBur** [git-for-windows/git#2436]
$ git pull
warning: failed to restrict file handles (5)

handle #0: 0000000000000114 (type 3, handle info (1) 0
handle #1: 0000000000000118 (type 3, handle info (1) 1
handle #2: 0000000000000420 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

Already up to date.
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git for Windows 2.24.1.windows.2 (64bit)
Up to date

$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Pro

$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Hmm. No information how to reproduce this issue?

**Comment by GlebBur** [comment]
No. I just Pull from remote. First time I see such stuff.

вт, 17 дек. 2019 г. в 15:46, Johannes Schindelin <notifications@github.com>:

**Comment by dscho** [comment]
I asked for more information because I can obviously not reproduce your
issue. So if you want anybody to help you, you might just as well provide
more information in the hope that you provided enough of it to let others
help you.
