### ISSUE TITLE
Problems downloading git for windows

### ISSUE THREAD

**Issue by pedrorijo91** [git-for-windows/git#2443]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Hey all :)

We have been having a lot of reports about slowness downloading git for windows on https://github.com/git/git-scm.com/issues/1333 

Are you aware of it? We know the downloadable artifacts are on GitHub infrastructure (which seems to rely on Amazon S3), but have you ever considered an alternative? Just like git-scm was able to find partnership with heroku, maybe git-for-windows could find a partnership with an alternative host server? Or even use Software Freedom Conservancy infrastructure/funds?

I know GitHub had a similar problem with other repos (CocoaPods - https://youtu.be/-ZNKR9wFe8o?t=664), maybe if we report the issue we can find a solution?

**Comment by dscho** [comment]
> Are you aware of it?

I was not.

> We know the downloadable artifacts are on GitHub infrastructure (which seems to rely on Amazon S3), but have you ever considered an alternative? Just like git-scm was able to find partnership with heroku, maybe git-for-windows could find a partnership with an alternative host server? Or even use Software Freedom Conservancy infrastructure/funds?

The problem here is not so much infrastructure, the missing resource is human: there is nobody volunteering time to switch elsewhere, nor is there anybody who volunteered to keep it working after said switch.

**Comment by pedrorijo91** [comment]
I assume there's some kind of release job on some CI right? It seems to be azure pipelines. Maybe it wouldn't be too hard to upload artifacts into microsoft equivalent of Amazon S3 and provide a public link listing all artifacts (nothing too fancy). The probably of S3 and "Azure S3" being both down/slow at same time should be much smaller

**Comment by dscho** [comment]
> I assume there's some kind of release job on some CI right?

Look at the `publish` function of `please.sh` in build-extra: https://github.com/git-for-windows/build-extra/blob/524237bbf38aa99ab0215bbcdae7de07187450e2/please.sh#L4319-L4492, in particular the part that calls [`upload-to-github.sh`](https://github.com/git-for-windows/build-extra/blob/master/upload-to-github.sh).

**Comment by iskilber** [comment]
Hi I have troubles to download GIT installer for Windows. (It takes several hours to download 44Mb) I tried on WIndows, on Mac, on Chrome, on Edge, in Incognito mode as well as via Curl in bash. No difference. Download speed drops down drastically for GIT installer and make GIT installation on windows impossible.
Git v2.26.2 Windows 64-bit setup.

**Comment by dscho** [comment]
Can you download the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)? It's not all that different from v2.26.2, so if you can download from there, you'll be unblocked.

**Comment by dscho** [comment]
Oh, and the "Mon, 20 Apr 2020 16:51:56 +0200" item is actually identical to v2.26.2.

**Comment by iskilber** [comment]
Hi. Yep It helped. I can download from there without any problem. Thanks a lot.

**Comment by dscho** [comment]
I guess from now on we can always point people to the snapshots when they have problems downloading Git for Windows: a recent workflow change means that the snapshot corresponding to an officially-released version will actually be a verbatim copy of said version.

**Comment by pepypeppep** [comment]
I hope @pedrorijo91 you can make other mirror link. I feel so bad about this 😭 
![image](https://user-images.githubusercontent.com/28555319/88123656-8ced2800-cbf5-11ea-9b50-13a360f614e5.png)

**Comment by dscho** [comment]
@pepypeppep how about providing the hosting space yourself? I can upload the latest version there if you provide me with details.
