### ISSUE TITLE
gpg: can't connect to the agent: IPC connect call failed

### ISSUE THREAD

**Issue by p2poolmining** [git-for-windows/git#2445]
- [ X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.535]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
Also running GPG4Win 3.1.11

Gpg4win 3.1.11 contains:
    
GnuPG 2.2.17
Kleopatra 3.1.8
GPA 0.10.0
GpgOL 2.4.2
GpgEX 1.0.6
Kompendium (de) 4.0.1
Compendium (en) 3.0.0
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
Bash
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ gpg --list-secret-keys --keyid-format LONG
```
 - What did you expect to occur after running these commands?

 **expected to receive a list of the existing keys** 

 - What actually happened instead?

Received error...
```
gpg: can't connect to the agent: IPC connect call failed
```

- Additional Details

This is a new machine, after installing GPG4Win, I exported the keys from the old windows 7 machine into Kleopatra on the new Windows 10 machine. The import worked fine and I can see a list of the keys using Powershell.

I have tried everything that I can think of to get this to work, but I am stumped now.

**Comment by dscho** [comment]
My guess is that this issue has something to do with Git for Windows shipping with its _own_ version of GNU Privacy Guard. Most likely it cannot communicate with GPG4Win.
