### ISSUE TITLE
[Suggestion] Please open github.com git/git issues

### ISSUE THREAD

**Issue by talregev** [git-for-windows/git#2453]
Please open https://github.com/git/git issues. 
It more easy to report a bug and also suggest a feature request.

Thank you! :)

**Comment by dscho** [comment]
First of all, this here is the Git for Windows project. We cannot do anything about other projects such as git/git. I will therefore close this ticket.

Second of all, it is not your call whether the Git project wants to accept bug reports via GitHub. They did choose _not_ to, and you do not seem to be an active contributor in the Git project, so there is little hope that anybody would fulfill your wish.

Third of all, there is no shortage of feature requests in the Git project. None whatsoever. The scarce resource is the volunteers tackling them.

You _can_ send your suggestions to [the Git mailing list](mailto:git@vger.kernel.org) (no HTML or your mail will be rejected) as suggested at https://git-scm.com/community, of course. But do expect to be asked to do at least _some_ of the work yourself.
