### ISSUE TITLE
[Feature request ] git pull-rebase and git commit undo

### ISSUE THREAD

**Issue by talregev** [git-for-windows/git#2454]
Add git pull-rebase command another command that do the 5 steps:
1. stash the current changes in unique name. 
2. undo the current changes in the current branch. 
3. git pull the latest changes from original 
4. apply stash and drop it. If there will be conflict, let the user handle it. 

Add git commit undo , you can choose maybe better name for this command. 
That do the following thing:
Undo the last local commit and leave the files with the changes (modified). 
Most of the error, people make local commit and not sure how to undo it. 
And you can still undo this with the current sets of command, but this command will be more easy.

Please vote here if you like or want this suggestions.

**Comment by dscho** [comment]
> Add git pull-rebase command another command that do the 5 steps:
> 
>     1. stash the current changes in unique name.
> 
>     2. undo the current changes in the current branch.
> 
>     3. git pull the latest changes from original
> 
>     4. apply stash and drop it. If there will be conflict, let the user handle it.

Isn't this what `git -c rebase.autostash=true pull --rebase` does already? You can even register a Git alias for this: `git config --global alias.pull-rebase -c rebase.autostash=true pull --rebase"`.

> Add git commit undo , you can choose maybe better name for this command.
> That do the following thing:
> Undo the last local commit and leave the files with the changes (modified).
> Most of the error, people make local commit and not sure how to undo it.
> And you can still undo this with the current sets of command, but this command will be more easy.

This might be a bit tricky, given the many venues how a commit could have come about (`git pull`, `git merge`, `git cherry-pick`, `git revert`).

So unless you come up with very precise semantics, this is too unclear of a wish.

> Please vote here if you like or want this suggestions.

Seeing as this is _not_ a Windows-specific issue, let alone a bug, I will close this ticket. Please don't vote here. Actually, please do not even vote on feature requests. The Git project is not a "let's just tell others what we want them to work on" show.

The only way to vote on a feature request is to work on it.
