### ISSUE TITLE
Inconsistent handling of .profile/.bashrc by bash.exe/git-bash.exe

### ISSUE THREAD

**Issue by NeilStrickland** [git-for-windows/git#2458]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Installer is Git-2.24.1.2-64-bit.exe
```
git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.535]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash.  (This issue is completely about bash and not git itself)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I created files .profile and .bashrc in C:\Users\Neil Strickland, containing lines 
`export $PROFILE_READ=1` and `export $BASHRC_READ=1` respectively.
I then executed `C:\Program Files\Git\bin\bash.exe` (either by typing that 
path in a cmd.exe window, or by clicking Terminal in VS Code) and at the
resulting bash prompt I entered `echo $PROFILE_READ` and `echo $BASHRC_READ`.

I then executed `C:\Program Files\Git\git-bash.exe` (either by typing this path 
in a cmd.exe window, or by starting Git Bash from the Start Menu) and again 
entered `echo $PROFILE_READ` and `echo $BASHRC_READ` at the bash prompt.
```
 - What did you expect t o occur after running these commands?

I expected that `C:\Program Files\Git\bin\bash.exe` and `C:\Program Files\Git\git-bash.exe` would give the same result. 

 - What actually happened instead?

`C:\Program Files\Git\bin\bash.exe` apparently reads .bashrc but not .profile; 
`C:\Program Files\Git\git-bash.exe` apparently reads .profile but not .bashrc.

(Specifically, executing `echo $PROFILE_READ` gives an empty response with bash.exe and gives 1 with git-bash.exe; for `echo $BASHRC_READ` it is the other way around.)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not applicable

**Comment by rimrul** [comment]
That's by design. `.bashrc` is read by interactive subshells, `.bash_profile` is read by login shells

Modify your to say 

Try modifying your `.bashrc` to contain `echo ".bashrc"` and your `.bash_profile` to contain `echo ".bash-profile"`, change to `C:\Program Files\Git\bin\` in `CMD` and try calling `./bash.exe`, `./bash.exe -l` and `./bash.exe -c exit` a few times each. Consistent predictable behaviour.

**Comment by NeilStrickland** [comment]
OK.  But that means you are treating Git Bash started from the Start Menu as a login shell, which does not really seem to be correct.  Moreover, you are treating it differently from Git Bash started in the default way in VS Code, which can create a lot of confusion.  I can now deal with it myself, but I am trying to write and debug instructions for other users, and this will make their life harder.

**Comment by rimrul** [comment]
Git bash started from anywhere should be a login shell. How does VS code launch git bash as an interactive non-login shell?

**Comment by rimrul** [comment]
Looking at the vscode source, they don't seem to intentionally launch git bash at any point. There's some code to determine if they where launched from git bash, but I don't see any launching. Is this some sort of plugin?

**Comment by NeilStrickland** [comment]
I made a fresh install of VS Code with no extensions etc.  If I click Terminal on the top toolbar, then select New Terminal from the dropdown menu, then it opens a Powershell terminal within the VS Code window.  Just above the terminal there is a drop-down list offering alternatives to Powershell.  One of them is  C:\Program Files\Git\bin\bash.exe.

**Comment by NeilStrickland** [comment]
This is from lines 117-121 here:
https://github.com/microsoft/vscode/blob/8db441df8713e775e0716b89d2fe3a58f5919589/src/vs/workbench/contrib/terminal/node/terminal.ts

**Comment by NeilStrickland** [comment]
It's possible to make bash under VS Code read .bash_profile by adding `"terminal.integrated.shellArgs.windows": [ "-l" ]` in `settings.json`.  Is it your position that that should be the default?

**Comment by dscho** [comment]
> It's possible to make bash under VS Code read .bash_profile by adding `"terminal.integrated.shellArgs.windows": [ "-l" ]` in `settings.json`. Is it your position that that should be the default?

If the default for the integrated shell on Windows is to call Bash (Git for Windows', or any other), then yes.
