### ISSUE TITLE
git clone error under Windows with symlinks

### ISSUE THREAD

**Issue by klorinczi** [git-for-windows/git#2459]
I get "warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree" error, when using git clone:

```
 git clone -c core.symlinks=true ssh://root@11.22.33.44/etc c/Dev/GIT/mysite-etckeeper/
    Cloning into 'c/Dev/GIT/mysite-etckeeper'...
    remote: Counting objects: 1400, done.
    remote: Compressing objects: 100% (1202/1202), done.
    remote: Total 1400 (delta 195), reused 0 (delta 0)
    Receiving objects: 100% (1400/1400), 3.71 MiB | 276.00 KiB/s, done.
    Resolving deltas: 100% (195/195), done.
    Checking out files: 100% (1154/1154), done.
    warning: the following paths have collided (e.g. case-sensitive paths
    on a case-insensitive filesystem) and only one from the same
    colliding group is in the working tree:
    
      'HOSTNAME'
      'hostname'

    /etc # ls -la HOSTNAME
    lrwxrwxrwx   1 root root         8 Mar 29  2017 HOSTNAME -> hostname
    
    /etc # ls -la hostname
    -rw-r--r--   1 root root        18 Dec 21  2016 hostname
```

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
$ git --version
git version 2.22.0.windows.1
64 bit

```
$ git --version --build-options

** git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 Pro

```
$ cmd.exe /c ver

** Microsoft Windows [version: 6.1.7601] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: Notepad++
Custom Editor Path:
Path Option: CmdTools
Plink Path: c:\winprg\PuTTY\plink.exe
SSH Option: Plink
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** MINGW64 **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** git clone -c core.symlinks=true ssh://root@11.22.33.44/etc c/Dev/GIT/mysite-etckeeper/ **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

**     **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
>     * git version 2.22.0.windows.1

Please re-test with v2.25.0-rc1.

**Comment by dscho** [comment]
> Please re-test with v2.25.0-rc1.

@klorinczi if that version still behaves in an undesired way, do spend the time to create a public repository that is easily cloned and that demonstrates the issue (I would have tried that myself, but since you left all those `** insert ... here **` placeholders unaddressed, I feel free to save me some time with this ticket, too).

**Comment by klorinczi** [comment]
Ok. I will try to make a public repo.

**Comment by klorinczi** [comment]
Here is an the example repo:
https://github.com/klorinczi/test_dupe_filename

Execute this:
```
$ git clone -c core.symlinks=true https://github.com/klorinczi/test_dupe_filename 
Cloning into 'test_dupe_filename_example'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 9 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'HOSTNAME'
  'hostname'

```

**Comment by dscho** [comment]
Thank you for making that MCVE. I can reproduce. So the issue actually has nothing to do with symbolic links, but everything with a repository that simply cannot be checked out on case-insensitive file systems because it contains two items whose file names differ only in their casing?

I am afraid that this issue cannot be resolved: you simply cannot have _both_ `HOSTNAME` _and_ `hostname` in the same directory. There can only be one...
