### ISSUE TITLE
Suggestion about better log graph

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#2460]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.175]  
64bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log --graph
```
 - What did you expect to occur after running these commands?

**The branch line should not across one from another.**  The green line should locate inside the black and red line.
![image](https://user-images.githubusercontent.com/3004057/72051505-64a77700-32fe-11ea-8267-7baf5f8bae9d.png)

*   commit 5f0e760177aabefd23d5012d055cd323fa818e2c (HEAD -> test, origin/master)
|\  Merge: 318e4f6 d14a217
| | Author: Chuck Lu <chuck.lu@qq.com>
| | Date:   Thu Jan 9 14:19:54 2020 +0800
| |
| |     Merge branch 'master' into test
| |
| * commit d14a2176298c08d1739919ceb00c31abf921642e (master)
| | Author: Chuck Lu <chuck.lu@qq.com>
| | Date:   Thu Jan 9 14:14:20 2020 +0800
| |
| |     add one line
| |
* |   commit 318e4f6cd13e359fb1adb689e90a280b38ef73f5
|\ \  Merge: f3a7c74 764204a
| | | Author: Chuck Lu <chuck.lu@qq.com>
| | | Date:   Thu Jan 9 14:19:26 2020 +0800
| | | 
| | |     Merge branch 'test2' into test
| | |
| * | commit 764204af5ea7c1683e2cb2450c7691a1f72fa2b8 (test2)
| | | Author: Chuck Lu <chuck.lu@qq.com>
| | | Date:   Thu Jan 9 14:15:39 2020 +0800
| | |
| | |   add one line
| | |
| * | commit d2a9161c4c40471a76bc77b2f995cf8b0737ea21
|/  | Author: Chuck Lu <chuck.lu@qq.com>
|   | Date:   Thu Jan 9 14:15:09 2020 +0800
|  /
| /      add another file
|/
* commit f3a7c740dce6b0e55b014ef13ff48804a3d33b94
  Author: Chuck Lu <chuck.lu@qq.com>
  Date:   Thu Jan 9 14:13:32 2020 +0800

      add a new file

 - What actually happened instead?

![image](https://user-images.githubusercontent.com/3004057/72051113-8ce2a600-32fd-11ea-97b8-ac0d5962e35a.png)

*   commit 5f0e760177aabefd23d5012d055cd323fa818e2c (HEAD -> test, origin/master)
|\  Merge: 318e4f6 d14a217
| | Author: Chuck Lu <chuck.lu@qq.com>
| | Date:   Thu Jan 9 14:19:54 2020 +0800
| |
| |     Merge branch 'master' into test
| |
| * commit d14a2176298c08d1739919ceb00c31abf921642e (master)
| | Author: Chuck Lu <chuck.lu@qq.com>
| | Date:   Thu Jan 9 14:14:20 2020 +0800
| |
| |     add one line
| |
* |   commit 318e4f6cd13e359fb1adb689e90a280b38ef73f5
|\ \  Merge: f3a7c74 764204a
| |/  Author: Chuck Lu <chuck.lu@qq.com>
|/|   Date:   Thu Jan 9 14:19:26 2020 +0800
| |
| |       Merge branch 'test2' into test
| |
| * commit 764204af5ea7c1683e2cb2450c7691a1f72fa2b8 (test2)
| | Author: Chuck Lu <chuck.lu@qq.com>
| | Date:   Thu Jan 9 14:15:39 2020 +0800
| |
| |     add one line
| |
| * commit d2a9161c4c40471a76bc77b2f995cf8b0737ea21
|/  Author: Chuck Lu <chuck.lu@qq.com>
|   Date:   Thu Jan 9 14:15:09 2020 +0800
|
|       add another file
|
* commit f3a7c740dce6b0e55b014ef13ff48804a3d33b94
  Author: Chuck Lu <chuck.lu@qq.com>
  Date:   Thu Jan 9 14:13:32 2020 +0800

      add a new file

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/ChuckTest/TortoiseGit-002

**Comment by dscho** [comment]
> The branch line should not across one from another.

I doubt that this is possible with _all_ commit histories.

**Comment by chucklu** [comment]
@dscho  You are right, it's impossible to avoid across the branch line when you maintain more than three branches at the same time. The history will looks like a real tree in nature, it will require three-dimensional to avoid branch line across.

**Comment by chucklu** [comment]
I also found an interesting gist https://gist.github.com/datagrok/4221767 .

**Comment by chucklu** [comment]
Btw the git flow I used was https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow#finishing-a-hotfix-branch .
