### ISSUE TITLE
Git-for-windows detecting phantom CRLF->LF changes when changing branches

### ISSUE THREAD

**Issue by jamesmcguirepro** [git-for-windows/git#2462]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64-bit
```
$ git --version --build-options

git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8

```
This issue has existed in version of Git for Windows I've used over the past 10 months.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? Windows 10, 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.535]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

My team exclusively uses Windows.  As such, we want to use CRLF line endings in our .cs (C#) source files.

We all have `core.autocrlf` is set to false.
Our repos have `.gitattributes` files specifying CRLF for relevant source files:
```
*.cs text eol=crlf
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd, git bash, SourceTree

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

    * have branch_a checked out with no pending changes
    * run: `git checkout branch_b`

 - What did you expect to occur after running these commands?
I expect branch_b will be checked out.
I expect running `git diff` will no return no results.

 - What actually happened instead?
branch_b is checked out.
However, about 33% of the time, `git diff` will return several files that have been "changed" from CRLF to LF line endings.
(I was able to confirm this by cat'ing the output of `git diff` into a txt file and using Notepad++ to view the line ending symbols)
When I open the files returned by `git diff`, they are still CRLF.
When I launch an external diff program, like BeyondCompare, the before and after files are a binary match.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?  N/A

**Comment by dscho** [comment]
>     * If the problem was occurring with a specific repository, can you provide the
>       URL to that repository to help us with testing?  N/A

@jamesmcguirepro It would be good if you could at least _try_ to initialize a minimal public repository where you can observe the issue. It will take way more time to debug and fix this, meaning that it will make it more likely that some contributor will jump in to help you if you cover the effort of coming up with a reproducer.

**Comment by jamesmcguirepro** [comment]
Unfortunately, the repos I can consistently reproduce on are private.

I tried making a public repo, but I can reproduce on that one.

**Comment by tboegi** [comment]
You can actually do something on the private repo:
What does
git ls-files --eol
give you ?

**Comment by jamesmcguirepro** [comment]
I am seeing a mix of index and working tree eol types.

Out of all of our .cs files, ~96% have this output:
```
i/lf    w/crlf  attr/text eol=crlf
```

~4% of the files have this output:
```
i/crlf  w/crlf  attr/text eol=crlf
```

There is also a single file with this output:
```
i/-text w/-text attr/text eol=crlf
```

I'm not seeing any other combinations.

Interestingly enough, it's minority ones that are coming up as "phantom" changes.  Ie, files with:
```
i/-text w/-text attr/text eol=crlf
```
or
```
i/crlf  w/crlf  attr/text eol=crlf
```
are the ones causing problems.

**Comment by tboegi** [comment]
Please feel free to read
https://git-scm.com/docs/gitattributes

Your repo needs to be renormalized, all the 
i/crlf  w/crlf  attr/text eol=crlf
needs to become
i/lf  w/crlf  attr/text eol=crlf

And I would change those 
i/-text w/-text attr/text eol=crlf
into
i/-text w/-text attr/text=auto

In other words, adjust your .gitattributes like this, 
add more lines at the end if needed:
* text=auto
*.cs text eol=crlf

Then run these 2 commands:
git add --renormalize .
git commit -m "Introduce end-of-line normalization"

**Comment by jamesmcguirepro** [comment]
Sorry for the delayed response.

This seems to have fixed the issue for us.  Thank you much!

**Comment by dscho** [comment]
Excellent. Thanks @tboegi for providing outstanding help!
