### ISSUE TITLE
NullReferenceException encountered

### ISSUE THREAD

**Issue by klegni** [git-for-windows/git#2465]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
There are a few old issues with more or less the same issues, these however fixed in older Versions than what I'm using.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.1184]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using Azure Devops

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Visual Studio 2017

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Pull, Push
```
 - What did you expect to occur after running these commands?

I expected the command to complete without errors

 - What actually happened instead?

Git failed with a fatal error.
NullReferenceException encountered

From the log:
09:55:31.006180 run-command.c:626       trace: run_command: 'git-credential-manager' 'store'

09:55:31.089187 ...\Common.cs:677       trace: [Main] git-credential-manager (v1.17.1) 'store'

09:55:31.160181 ...\Git\Where.cs:361    trace: [FindGitInstallations] found 1 Git installation(s).

09:55:31.165188 ...Configuration.cs:222 trace: [LoadGitConfiguration] git All config read, 32 entries.

09:55:31.166183 ...\Common.cs:394       trace: [LoadOperationArguments] GCM_HTTP_USER_AGENT = 'git-credential-manager (Microsoft Windows NT 10.0.17134.0; Win32NT x64) CLR/4.0.30319 VS15/15.0.0'.

09:55:31.170182 ...\Common.cs:446       trace: [LoadOperationArguments] interactive = 'Auto'.

09:55:31.170182 ...\Common.cs:464       trace: [LoadOperationArguments] validate = 'True'.

09:55:31.170182 ...\Common.cs:480       trace: [LoadOperationArguments] modalPrompt = 'True'.

09:55:31.212992 ...\Common.cs:85        trace: [CreateAuthentication] detecting authority type for 'https://PersonalAccessToken@dev.azure.com/'.

09:55:31.459989 ...uthentication.cs:230 trace: [DetectAuthority] detected 'https://dev.azure.com/kpsconceptsgmbh/' as VSTS from GET response.

09:55:31.461988 ...\Program.cs:603      trace: [Run] ! error: 'Object reference not set to an instance of an object.'.

09:55:31.466995 ...\Common.cs:642       trace: [LogEvent] System.NullReferenceException: Object reference not set to an instance of an object.
   at VisualStudioTeamServices.Authentication.Authentication.<DetectAuthority>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VisualStudioTeamServices.Authentication.Authentication.<GetAuthentication>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Alm.Cli.CommonFunctions.<CreateAuthentication>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Alm.Cli.Program.<>c__DisplayClass26_1.<<Store>b__0>d.MoveNext()

09:55:31.468988 ...\Program.cs:603      trace: [Run] fatal: NullReferenceException encountered.
   Object reference not set to an instance of an object.

What's very weird is that my changes are pushed to the remote repo.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

All my Repos results in the same error

**Comment by dscho** [comment]
This is a Git Credential Manager issue, would you please report it over there (at https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/, please first see whether there is already a ticket about this issue)?

I could not fail to notice, by the way, that you run with Git Credential Manager v1.17.1, but the one shipped with Git for Windows v2.24.1(2) is actually at v1.20.0. Any idea what is going on there?

**Comment by klegni** [comment]
I'll post there instead. The Version is strange though, I have installed the v1.20.0
![image](https://user-images.githubusercontent.com/3420373/72333178-ad26b200-36bb-11ea-9d97-75583a231bd0.png)

When I look at the file details it also shows v1.20.0

**Comment by dscho** [comment]
> When I look at the file details it also shows v1.20.0

Then it is probably a _different_ Git Credential Manager executable that is executed. Maybe check with `git config --show-origin --get-all credential.helper`?

**Comment by klegni** [comment]
It took me some time but I found the Version getting spawned by VS here:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core (v1.17.1)

It's now pointing to v1.20.0 and working as expected.
Thank you
