### ISSUE TITLE
Using GIT_SSH_COMMAND in Git for Windows

### ISSUE THREAD

**Issue by VNek85** [git-for-windows/git#247]
I'm using Fourth release candidate of Git for Windows 2.x now, and using GIT_SSH_COMMAND in shell to avoid SSH's host verification. In Git Bash I write something like this:
$ GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push origin master
How can I do something like this in Windows cmd?

**Comment by kostix** [comment]
@VNek85, bug tracker is there for reporting bugs, not asking general questions.

The questions should be asked on one of the two project's mailing lists: [one](https://groups.google.com/forum/#!forum/git-for-windows), [two](https://groups.google.com/forum/#!forum/msysgit).

**Comment by kostix** [comment]
As to the essense of the question, in `cmd.exe` you'd do

    set GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    git push

or, if Git's `ssh.exe` is not in the %PATH% (depend on how you installed it), you might need to specify the full path to that command, like

    set GIT_SSH_COMMAND="%ProgramFiles\Git\usr\bin\ssh.exe" ...

**Comment by VNek85** [comment]
Oh, I'm sorry. Thanks for your answer!
