### ISSUE TITLE
Cannot add file COM0.c or checkout branch containing COM0.c file

### ISSUE THREAD

**Issue by MateuszKlatecki** [git-for-windows/git#2470]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.25.0.windows.1
cpu: x86_64
built from commit: 7c71c859c97853ed057da5cbab12f3c13b5554df
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.535]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode    
Custom Editor Path:                
Path Option: Cmd                   
SSH Option: OpenSSH                
Tortoise Option: false             
CURL Option: OpenSSL               
CRLF Option: CRLFCommitAsIs        
Bash Terminal Option: MinTTY       
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled    
Enable Symlinks: Enabled           
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

no matter

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git add COM0.c
error: open("COM0.c"): No such file or directory
error: unable to index file 'COM0.c'
fatal: adding files failed
```

or
```
$ git clone https://github.com/FreeRTOS/FreeRTOS-Kernel.git
$ git checkout V10.2.1
error: invalid path 'FreeRTOS/Demo/HCS12_CodeWarrior_banked/CODE/COM0.C'
error: invalid path 'FreeRTOS/Demo/HCS12_CodeWarrior_banked/CODE/COM0.H'
```

 - What did you expect to occur after running these commands?

I want to add file COM0.* and able to checkout branch containing that file

 - What actually happened instead?

git report error

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/FreeRTOS/FreeRTOS-Kernel.git

**Comment by dscho** [comment]
`COM0` is listed as a reserved file name at https://kizu514.com/blog/forbidden-file-names-on-windows-10/, but not at https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file. The latter _does_ talk about `COM0` being a thing, though, in the "NT Namespaces" section.

So Git for Windows errs on the side of caution and interprets this as a reserved file name that cannot be used, not even with a file extension.

**Comment by MateuszKlatecki** [comment]
but it possible to create file `COM0` in Windows 10 and I believe that on other Windows versions create that file is also possible

**Comment by dscho** [comment]
> but it possible to create file `COM0` in Windows 10 and I believe that on other Windows versions create that file is also possible

Sure, but I really want to make sure that this is not something that happens to work on your computer. That is why I erred on the side of caution. And I would really feel better if we had a link to official documentation that states that only `COM1`, ... `COM9` are reserved, but not `COM0`...

**Comment by dscho** [comment]
I guess https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions is good enough.

**Comment by dscho** [comment]
@MateuszKlatecki please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)

**Comment by MateuszKlatecki** [comment]
I confirm that on the latest snapshot problems I have reported are no longer present
