### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'libeay32.lib'

### ISSUE THREAD

**Issue by QuellaZhang** [git-for-windows/git#2474]
VCPKG recently do some changes with "libeay32.lib" https://github.com/microsoft/vcpkg/pull/8566, and we got the following error when build latest version of Git, can you help look at this?

**Repro steps:**
1.open VS2017 x64 Native Tools command
2.git.exe clone -b vs/master https://github.com/git-for-windows/git D:\git\src
3.cd D:\git\src
4.git checkout "latest version"
5.devenv /upgrade git.sln
6. nuget.exe restore git.sln
7.msbuild /m /p:Configuration=Release;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.17134.0 /t:Rebuild git.sln

**Failures:**
F:\git\git-http-push>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe" /ERRORREPORT:QUEUE /OUT:"..\git-http-push.exe" /NOLOGO /LIBPATH:"..\compat\vcbuild\vcpkg\installed\x64-windows\lib" advapi32.lib expat.lib kernel32.lib libcurl.lib libeay32.lib libeay32.lib libiconv.lib ntdll.lib shell32.lib ssleay32.lib ssleay32.lib user32.lib wininet.lib ws2_32.lib zlib.lib zlib.lib /MANIFEST:NO /DEBUG /PDB:"..\git-http-push.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /ENTRY:"wmainCRTStartup" /DYNAMICBASE /NXCOMPAT /IMPLIB:"..\git-http-push.lib" /MACHINE:X64 invalidcontinue.obj "x64\Release\common-main.obj" "x64\Release\http-push.obj" x64\Release\http.obj F:\gitP\KarenHuang2016\git\libgit.lib F:\gitP\KarenHuang2016\git\xdiff\xdiff_lib.lib
**LINK : fatal error LNK1181: cannot open input file 'libeay32.lib'**

**Comment by dscho** [comment]
What is the correct library name?

**Comment by QuellaZhang** [comment]
![image](https://user-images.githubusercontent.com/36754348/72420215-47b8eb00-37b9-11ea-9fc3-b75e529a5cf0.png)

**Comment by dscho** [comment]
@QuellaZhang please. This is _text_. If you paste an _image_, you prevent me from copy/pasting, and from seeing your answer quickly in a text-based notification system. All you do by making it harder for me is to make it more likely that next time, I won't do this PR for you. Have a good, long hard look at #2476 because it is not all that hard, and you really do not have to dump this work on me every single time the Visual Studio build breaks.
