### ISSUE TITLE
Git does not recognize utf16 encoded file

### ISSUE THREAD

**Issue by FalconWu2017** [git-for-windows/git#2475]
```
$ git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8
```

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
$ cat /etc/install-options.txt
Editor Option: Nano
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```
There are three different coded files in my repository.
```
$ file *
dbo.BK_ACCOUNT.Table.sql:             ISO-8859 text, with CRLF line terminators
dbo.BK_ACCOUNT.Table.sql.unicode.txt: Little-endian UTF-16 Unicode text, with CRLF line terminators
dbo.BK_ACCOUNT.Table.sql.utf8.txt:    UTF-8 Unicode (with BOM) text, with CRLF line terminators

$ file * -i
dbo.BK_ACCOUNT.Table.sql:             text/plain; charset=iso-8859-1
dbo.BK_ACCOUNT.Table.sql.unicode.txt: text/plain; charset=utf-16le
dbo.BK_ACCOUNT.Table.sql.utf8.txt:    text/plain; charset=utf-8
```
When diff look this :  
```
$ git diff
diff --git a/dbo.BK_ACCOUNT.Table.sql b/dbo.BK_ACCOUNT.Table.sql
index 5d032db..9f8740e 100644
--- a/dbo.BK_ACCOUNT.Table.sql
+++ b/dbo.BK_ACCOUNT.Table.sql
@@ -2,7 +2,6 @@ USE [mzbk]
 GO
 SET ANSI_NULLS ON
 GO
-SET QUOTED_IDENTIFIER ON
 GO
    1 <BA><EC><B5><C6>' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BK_ACCOUNT', @level2type=N'
 GO
diff --git a/dbo.BK_ACCOUNT.Table.sql.unicode.txt b/dbo.BK_ACCOUNT.Table.sql.unicode.txt
index f8b2e31..e94bb83 100644
Binary files a/dbo.BK_ACCOUNT.Table.sql.unicode.txt and b/dbo.BK_ACCOUNT.Table.sql.unicode.txt differ
diff --git a/dbo.BK_ACCOUNT.Table.sql.utf8.txt b/dbo.BK_ACCOUNT.Table.sql.utf8.txt
index b661b2a..14c0953 100644
--- a/dbo.BK_ACCOUNT.Table.sql.utf8.txt
+++ b/dbo.BK_ACCOUNT.Table.sql.utf8.txt
@@ -2,10 +2,6 @@
 GO
 SET ANSI_NULLS ON
 GO
-SET QUOTED_IDENTIFIER ON
-GO
-SET ANSI_PADDING ON
-GO
 CREATE TABLE [dbo].[BK_ACCOUNT](
        [ID] [int] IDENTITY(1,1) NOT NULL,
        [PERSON_ID] [varchar](18) NOT NULL,OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON,
```  
File `dbo.BK_ACCOUNT.Table.sql` and file `dbo.BK_ACCOUNT.Table.sql.utf8.txt` are all OK,but `dbo.BK_ACCOUNT.Table.sql.unicode.txt` is binary files. It is wrong, it is a text file too.   
I don't know if it's my system setup or git's own bug。Can somebody help me？

**Comment by dscho** [comment]
Maybe you need to configure [the `working-tree-encoding` in the `.gitattributes`](https://git-scm.com/docs/gitattributes#_code_working_tree_encoding_code)?

You might need to upgrade to a newer Git for Windows version, though, v2.25.0 is current.

**Comment by FalconWu2017** [comment]
@dscho  Do you mean `*.sql text working-tree-encoding=UTF-16` in `.gitattributes`.
I have tried it ,no work.

**Comment by dscho** [comment]
@FalconWu2017 how about making it easier for other people to help you? You could, for example, create a really small repository and put it on GitHub, ready to clone.

**Comment by FalconWu2017** [comment]
@dscho  U can clone this `https://github.com/FalconWu2017/CodeingTest`

**Comment by dscho** [comment]
I get this:

```
$ git clone https://github.com/FalconWu2017/CodeingTest
Cloning into 'CodeingTest'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 15 (delta 5), reused 15 (delta 5), pack-reused 0
Unpacking objects: 100% (15/15), done.
error: failed to encode 'dbo.BK_ACCOUNT.Table.sql' from UTF-8 to UTF-16
```

And I think I know why: the `.gitattributes` say that way more than `dbo.BK_ACCOUNT.Table.sql.unicode.txt` is UTF-16-encoded, which is incorrect. So first of all, I need this:

```diff
diff --git a/.gitattributes b/.gitattributes
index d28c7a7..b0fb634 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1 +1 @@
-*.sql text working-tree-encoding=UTF-16
\ No newline at end of file
+*.sql.unicode.txt text working-tree-encoding=UTF-16
```

After this, another step is still required: `git add --renormalize dbo.BK_ACCOUNT.Table.sql.unicode.txt`. To understand why, keep in mind that you specified a _worktree_ encoding in the `.gitattributes` file, which means that the file will be checked out in UTF-16 encoding, but internally Git still maintains it in UTF-8 encoding (which is required for the diff machinery to work correctly).

Obviously, you will want to commit both the modified `.gitattributes` and the modified text file after renormalizing the latter. This will not "fix" past commit history, but it will fix the future commit history.

**Comment by FalconWu2017** [comment]
As you say,I change `.gitattributes` and run `git add --renormalize dbo.BK_ACCOUNT.Table.sql.unicode.txt`，commit and push
Clone OK.  but it's still binary。

**Comment by dscho** [comment]
> but it's still binary。

@FalconWu2017 it is only binary in older commits. And yes, the diff of the commit where you renormalized the file has a "binary" as pre-image, therefore the diff will still say that it is binary. But the post-image is not. If you now commit _any_ change to that file, that commit will show you the diff, just as you wanted.

That's what I meant by: you cannot fix the past commit history (the pre-image of the commit in question _is_ past commit history).

**Comment by M-Schiller** [comment]
Have you considered packaging in distributing `iconv` with git for windows as mentioned [here](https://github.com/msysgit/msysgit/issues/113)? I think this would help a lot of users that have to deal with UTF16 encoded files.

**Comment by dscho** [comment]
No, I think that it is much better to handle UTF-16 files "the Git way": configuring the gitattributes and then renormalizing the files, as indicated above.

Bundling `iconv` would only help the relatively few Git for Windows users who are also familiar with Unix tools, and they are unlikely to have UTF-16-encoded files in the first place.
