### ISSUE TITLE
Git clean fail when running it from inside a sub-folder

### ISSUE THREAD

**Issue by angellaa** [git-for-windows/git#2477]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

I am using git 2.25 for windows 64 bit.

```
$ git --version --build-options

git version 2.25.0.windows.1
cpu: x86_64
built from commit: 7c71c859c97853ed057da5cbab12f3c13b5554df
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.476]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
c:\Temp>md repo
c:\Temp>cd repo
c:\Temp\repo>git init
Initialized empty Git repository in C:/Temp/repo/.git/
c:\Temp\repo>md subfolder
c:\Temp\repo>cd subfolder
c:\Temp\repo\subfolder>git clean -d -f
Deletion of directory 'subfolder/./' failed. Should I try again? (y/n) y
Deletion of directory 'subfolder/./' failed. Should I try again? (y/n) n
warning: failed to remove ./: Permission denied

```
 - What did you expect to occur after running these commands?

I expected the same behavior as git version 2.24. Running clean using version 2.24 does not produce a permission denied error and simply leave the folder behind.

 - What actually happened instead?
A permission denied occurs.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, it's not about a specific repository. 

Is this a regression or an intentional change of behavior?

**Comment by dscho** [comment]
`git clean` is supposed to remove that directory. Since it is the current directory of the CMD in which you run it, that directory cannot be removed. I would say that v2.25.0 is correct.

**Comment by angellaa** [comment]
We managed to workaround this issue by calling git clean from the root directory of the repository and passing the path to the folder to the command.

Feel free to close this issue if you believe this new behavior is correct.

**Comment by dscho** [comment]
> We managed to workaround this issue by calling git clean from the root directory of the repository and passing the path to the folder to the command.

That's a good idea, and it is less of a workaround and more like the correct solution. You definitely do not want that directory to be the current directory of the process that wants to remove it.

> Feel free to close this issue if you believe this new behavior is correct.

Will do! Thanks for getting back to us with the solution you found.
