### ISSUE TITLE
Git for Windows rebooted my PC

### ISSUE THREAD

**Issue by dannypike** [git-for-windows/git#2479]
1. I was just prompted to update Git for Windows, which is fine.
2. When I clicked "Yes" at the UAC prompt, the installation started, which is fine.
3. When the installation completed, my PC rebooted without confirmation, which is a VERY BAD THING for it to do.

I'm not sure whether the reboot was caused by the Git for Windows installation because I didn't get prompted; it just "happened". So, ...

(a) if the reboot was initiated by the Git for Windows installation, please never ever do that without asking me for confirmation;
(b) if the reboot was not initiated by the Git for Windows installation, please accept my apologies, close and ignore this ticket. :)

**Comment by mfriedrich74** [comment]
Please go into you Windows Event Log and search for reboot event messages.
They should tell you what triggered it or whether it was unexpected.

Best regards, Mike

**Comment by dannypike** [comment]
Thank you for your reply. I can see the reboot happening in the Event Viewer, but there is no reason given:

```
The process C:\WINDOWS\system32\winlogon.exe (NUTMEG) has initiated the restart of computer NUTMEG on behalf of user NT AUTHORITY\SYSTEM for the following reason: No title for this reason could be found
 Reason Code: 0x500ff
 Shutdown Type: restart
 Comment: 
```

Is the installer is configured to do a reboot?

**Comment by dscho** [comment]
> Is the installer is configured to do a reboot?

Only when overwriting files that are in use, I think.

**Comment by dannypike** [comment]
Can you change it so that it asks, rather than just reboots regardless of what the user is doing at the time (such as being in a conference call!) ?

**Comment by dscho** [comment]
> Can you change it so that it asks

It asks. You must be installing Git for Windows in silent mode, but even then it should only indicate that a reboot is required.

**Comment by mfriedrich74** [comment]
I think git is not at fault here.
Please use your favorite internet search and search for "windows restarts
reason code 0x500ff"

**Comment by dannypike** [comment]
Great, having confirmation that it asks every time is enough for me (as per my point (b) in the original question). It was just a weird coincidence, and I'll look elsewhere for the cause.

Many thanks for your help, everyone.
