### ISSUE TITLE
Git cannot stage full-path files if the path to the repository is a directory junction

### ISSUE THREAD

**Issue by monoblaine** [git-for-windows/git#2481]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.25.0.windows.1
cpu: x86_64
built from commit: 7c71c859c97853ed057da5cbab12f3c13b5554df
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.973]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No, there's none.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\>mkdir repo-dir
C:\>cd repo-dir
C:\repo-dir>git init
C:\repo-dir>echo foo > foo.txt
C:\repo-dir>mklink /J C:\repo-dir--junction C:\repo-dir
C:\repo-dir>cd ..\repo-dir--junction
C:\repo-dir--junction>git add C:\repo-dir--junction\foo.txt
```
 - What did you expect to occur after running these commands?

File `foo.txt` should've been staged successfully. This used to work before v2.25.0.

 - What actually happened instead?

We get the following error:

```
fatal: C:\repo-dir--junction\foo.txt: 'C:\repo-dir--junction\foo.txt' is outside repository
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is irrelevant to this issue.

**Additional info (More combinations):**

```
C:\repo-dir--junction>git add foo.txt                       (Works)
C:\repo-dir--junction>git add .                             (Works)
C:\repo-dir--junction>git add ..\repo-dir--junction\foo.txt (Does not work)
C:\repo-dir>git add C:\repo-dir--junction\foo.txt           (Does not work)
C:\repo-dir>git add ..\repo-dir--junction\foo.txt           (Does not work)
```

**Comment by dscho** [comment]
I can confirm that this is a change of behavior between v2.24.1(2) and v2.25.0, most likely introduced by 1e64d180a632aa6063f7dbdf019a44e95383867c (which is unfortunately a bug fix, so we cannot simply revert it).

**Comment by dscho** [comment]
So this seems to fix things for me:

```diff
diff --git a/abspath.c b/abspath.c
index 98579853299..0ca2fc70fd5 100644
--- a/abspath.c
+++ b/abspath.c
@@ -95,6 +95,9 @@ char *strbuf_realpath(struct strbuf *resolved, const char *path,
 			goto error_out;
 	}
 
+	if (git_strbuf_realpath(resolved, path))
+		return resolved->buf;
+
 	strbuf_addstr(&remaining, path);
 	get_root_part(resolved, &remaining);
 
diff --git a/compat/mingw.c b/compat/mingw.c
index f5de482c545..889e1a25c5a 100644
--- a/compat/mingw.c
+++ b/compat/mingw.c
@@ -1256,6 +1256,35 @@ struct tm *localtime_r(const time_t *timep, struct tm *result)
 	return NULL;
 }
 
+char *mingw_strbuf_realpath(struct strbuf *resolved, const char *path)
+{
+	wchar_t wpath[MAX_PATH];
+	HANDLE h;
+	DWORD ret;
+	size_t len;
+
+	if (xutftowcs_path(wpath, path) < 0)
+		return NULL;
+
+	h = CreateFileW(wpath, 0,
+			FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, NULL,
+			OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, NULL);
+	if (h == INVALID_HANDLE_VALUE)
+		return NULL;
+
+	ret = GetFinalPathNameByHandleW(h, wpath, ARRAY_SIZE(wpath), 0);
+	CloseHandle(h);
+	if (!ret || ret >= ARRAY_SIZE(wpath))
+		return NULL;
+
+	len = wcslen(wpath) * 3;
+	strbuf_grow(resolved, len);
+	if (xwcstoutf(resolved->buf, normalize_ntpath(wpath), len) < 0)
+		return NULL;
+	return resolved->buf;
+
+}
+
 char *mingw_getcwd(char *pointer, int len)
 {
 	wchar_t cwd[MAX_PATH], wpointer[MAX_PATH];
diff --git a/compat/mingw.h b/compat/mingw.h
index 797a9f9253b..7ef8747f71d 100644
--- a/compat/mingw.h
+++ b/compat/mingw.h
@@ -471,6 +471,8 @@ extern int (*win32_is_mount_point)(struct strbuf *path);
 #define PATH_SEP ';'
 char *mingw_query_user_email(void);
 #define query_user_email mingw_query_user_email
+char *mingw_strbuf_realpath(struct strbuf *resolved, const char *path);
+#define git_strbuf_realpath mingw_strbuf_realpath
 #if !defined(__MINGW64_VERSION_MAJOR) && (!defined(_MSC_VER) || _MSC_VER < 1800)
 #define PRIuMAX "I64u"
 #define PRId64 "I64d"
diff --git a/git-compat-util.h b/git-compat-util.h
index 9d0f00e75d3..a928663e7d3 100644
--- a/git-compat-util.h
+++ b/git-compat-util.h
@@ -408,6 +408,10 @@ static inline int git_create_symlink(struct index_state *index, const char *targ
 #define query_user_email() NULL
 #endif
 
+#ifndef git_strbuf_realpath
+#define git_strbuf_realpath(resolved, path) NULL
+#endif
+
 #ifdef __TANDEM
 #include <floss.h(floss_execl,floss_execlp,floss_execv,floss_execvp)>
 #include <floss.h(floss_getpwuid)>
```

The idea behind this is to teach not only `getcwd()` but also `strbuf_realpath()` to use `GetFinalPathByHandleW()` to resolve symlinks (and obviously, NTFS junctions!).

That idea would need to be wrought into a beautiful commit message, in addition to an abbreviated account of this here ticket (with a link to it).

After that, testing, testing, testing, and opening a PR.

@monoblaine are you up to it?

No worries if not, it'll probably just take ages for me to come back to this issue if you can't do it.

**Comment by dscho** [comment]
> The last time I wrote some C code was 19 years ago, but I'll try it anyway!

That's the spirit!

**Comment by dscho** [comment]
> So the fix is ready and the only thing we need is the commit of this fix, _tests_ and a PR, right?

Well, manual tests would go first ;-) This should get you started: https://github.com/git-for-windows/git/wiki/Building-Git
