### ISSUE TITLE
2.5.0 sparse checkout is including other paths that contain reserved file names (PRN)

### ISSUE THREAD

**Issue by NOYB** [git-for-windows/git#2486]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options
** insert your machine's response here **
git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
checkout branch
```
 - What did you expect to occur after running these commands?

** insert here **
branch checkout

 - What actually happened instead?

** insert here **
branch checked out but with staged file containing reserved file names in the path.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

I have a shallow repository clone and using sparse-checkout of just a handful of directories.  When I upgraded from git version 2.24.1 to 2.25.0 some files not in the sparse-checkout path were staged to be deleted.  The directory path of these files contain the Windows reserved name of “prn”.  Ex: “japanese/prn/. . .”  Unable to un-stage these files and reset the changes.

.git/info/sparse-checkout:
```
!/*/
/*/directory-*/

```
Reverting back to the previous version (2.24.1) allowed to un-stage the files and reset the changes.

**Comment by dscho** [comment]
You mean _sparse_ checkout, not _spare_ checkout, right? ☺️ 

>     * What commands did you run to trigger this issue? If you can provide a
>       [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
>       this will help us understand the issue.
> 
> 
> ```
> ** insert your commands here **
> checkout branch
> ```

FWIW it was not necessary to keep the placeholder "** insert your commands here **"...

But also, this is _not_ a reproducible example. Please do spend some quality time with this report to make it possible for contributors such as myself to copy some lines, paste them into a Git Bash and see _precisely_ what issue you are talking about.

**Comment by NOYB** [comment]
Yes sparse checkout.
Derrick Stolee on the mail list has reproduced it.
https://public-inbox.org/git/062301d5d0bc$c3e17760$4ba46620$@Frontier.com/

**Comment by dscho** [comment]
> Derrick Stolee on the mail list has reproduced it.
> https://public-inbox.org/git/062301d5d0bc$c3e17760$4ba46620$@Frontier.com/

Let's continue the conversation there, then, to avoid duplicated efforts.
