### ISSUE TITLE
TortoiseGit crashes with "git.exe diff-index --raw HEAD --numstat..."

### ISSUE THREAD

**Issue by dezertdezine** [git-for-windows/git#2487]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.25.0.windows.1
cpu: x86_64
built from commit: 7c71c859c97853ed057da5cbab12f3c13b5554df
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18363.592]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using Git with TortoiseGit: 2.9.0

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash in Vscode

 - What commands did you run to trigger this issue?

```
From TortoiseGit:
Right-click repository folder > Select Git Commit from context menu

* I initially posted this issue on TortoiseGit / Issues here:
https://gitlab.com/tortoisegit/tortoisegit/issues/3506#note_275197630
...but was told to ask here
```
 - What did you expect to occur after running these commands?

Normally the UI appears, I add a message and hit commit.

 - What actually happened instead?

TortoiseGit error window opens with:
```
"git.exe diff-index --raw HEAD --numstat -C50% -M50% -z --"
exited with an error code, but did not output any error message
```
If I close the error window, the Tortoise UI loads with updated file, I add a message and hit commit, I get:
```
git did not exit cleanly (exit code -1073741795)
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
This is only happening with one repository, but it's private

If I run git from the command line with I get this:
```
$ git commit -a
*** stack smashing detected ***:  terminated
 *** stack smashing detected ***:  terminated
 Illegal instruction
```

**Comment by dscho** [comment]
>  Illegal instruction

Hmm, this is the first time I read anything about Git for Windows and an illegal instruction (or 0xc000001d, which is what -1073741795 translates to).

The internet suggests that the most likely cause for something like this is a corrupted binary. Can you verify the SHA-256 on your side, via

```sh
$ sha256sum /mingw64/bin/git.exe
017b2f5aa11781cd293e1c412472ed3d92d08affd945fa63bb3a633b1a98785c */mingw64/bin/git.exe
```

?

**Comment by dezertdezine** [comment]
I get the same as you:

```bash
$ sha256sum /mingw64/bin/git.exe
017b2f5aa11781cd293e1c412472ed3d92d08affd945fa63bb3a633b1a98785c */mingw64/bin/git.exe
```

**Comment by dscho** [comment]
Hmm. Any chance you can download and unpack the pdbs (from the GitHub Releases page), then run this with DrMemory or WinDbg (after familiarizing yourself with the tool)?

**Comment by dezertdezine** [comment]
Sure - I'll give it my best shot - probably be a couple of days before I can get to it, but I'll be back ;)

**Comment by dscho** [comment]
@dezertdezine if you can provide a small example which lets me try to reproduce the issue on my side, I can try to set aside some time to investigate over here, too.

**Comment by dezertdezine** [comment]
I had to give up this - too many work commitments, I couldn't dedicate any more time to it. I ended up starting a new repository omitting files that never should have been committed in the first place. In the omitted files I notices some very long mangled filenames. I don't know whether that was the cause of the issue, but so far the new repository is working all OK.
