### ISSUE TITLE
Invalid executable path error for git version :: mingit bundled with vsts-agent :: RAM Disk

### ISSUE THREAD

**Issue by VenumadhavDuriseti** [git-for-windows/git#2493]
### Moving this [issue](https://github.com/microsoft/azure-pipelines-agent/issues/2747) to gitforwindows

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
- Kind of similar [issue](https://github.com/git-for-windows/git/issues/2036)
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit, that is packed with vsts-agent-[2.164.6](https://vstsagentpackage.azureedge.net/agent/2.164.6/vsts-agent-win-x64-2.164.6.zip)
```
$ git --version --build-options

Invalid executable path:
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10.0.14393  x64

### Issue summary
I set up RAM Disk drive (X:) on my machine, using imdisk (and osfmount etc) and downloaded the agent binaries from [2.164.6](https://vstsagentpackage.azureedge.net/agent/2.164.6/vsts-agent-win-x64-2.164.6.zip) and tried running git version, it fails saying "Invalid executable path"

![image](https://user-images.githubusercontent.com/9970018/73215476-09042880-4109-11ea-994a-104bbb728aef.png)

**Comment by dscho** [comment]
@VenumadhavDuriseti if you download the latest [snapshot's](https://wingit.blob.core.windows.net/files/index.html) Portable Git and extract it onto that RAM disk, does _that_ Git work?

**Comment by VenumadhavDuriseti** [comment]
I tried the Portable git and mingit, it gives the same error:
![image](https://user-images.githubusercontent.com/9970018/73223698-d9125080-411b-11ea-8137-121230634e3b.png)

**Comment by Ajaja** [comment]
I have the same problem with ImDisk RAM drives.

**Comment by dscho** [comment]
> I tried the Portable git and mingit, it gives the same error:

@VenumadhavDuriseti You delight in keeping this report the opposite of verbose, or for that matter, complete, don't you?

Like, is this CMD or Git CMD? Can you execute _any_ `.exe` you copy to the RAM drive?

It is pretty frustrating to have to work with _that_ little information, too little, in fact, to make any sense of your bug report. Essentially, you try to force me to do way more work on my side than I actually have to. Please be more considerate.

@Ajaja if you could put in a bit more effort to add missing information to this ticket, that would also be more than welcome.

**Comment by dscho** [comment]
Oh well, thanks to https://github.com/git-for-windows/git/issues/1405#issuecomment-355009257, I was able to set this up quickly.

**Comment by dscho** [comment]
> quickly.

Where "quickly" translates to "30 minutes that I could not take care of issues that affect more than a mere dozen Git for Windows users"... 😞

**Comment by dscho** [comment]
The next [snapshot](https://wingit.blob.core.windows.net/files/index.html) will have this fixed.

**Comment by VenumadhavDuriseti** [comment]
Thank you @dscho for having this fixed, and apologies for not being clear on description.
> 
> Like, is this CMD or Git CMD? Can you execute _any_ `.exe` you copy to the RAM drive?
> 
Just leaving information here, it is a normal cmd. And yes I can run any exe I copy to RAM Drive.

**Comment by dscho** [comment]
Could you verify that [the latest snapshot](https://wingit.blob.core.windows.net/files/index.html) fixes the issue?

**Comment by VenumadhavDuriseti** [comment]
Seems like it works, thank you @dscho 
![image](https://user-images.githubusercontent.com/9970018/73571782-33fdbd80-4424-11ea-8b92-ece4a2797c45.png)

**Comment by dscho** [comment]
Thank you for confirming!
