### ISSUE TITLE
Access denied for files under Git repositories after migration to Git 2.25.0.windows.1

### ISSUE THREAD

**Issue by frederic-meyrou** [git-for-windows/git#2500]
Context : I use git to maintain and deploy portable tools under many windows target servers.

Under Windows server 2K8 / 2K12 / 2K16 or Windows 7/10 all my repositories get corrupted after I pull in certain conditions just after I did the migration to latest Windows git client to cover a CVE.

Files rights get a strange "**NULL SID**" and the other windows users have incorrect permissions.
This impact all staged files but also the .git folder, for example the ".git\config" file.

This leads for application using thoses files to "**Access denied**".

The only way to fix the problem is to delete everything and clone again the repository from the server.

**Comment by dscho** [comment]
> Under Windows server 2K8 / 2K12 / 2K16 or Windows 7/10 all my repositories get corrupted after I pull in certain conditions just after I did the migration to latest Windows git client to cover a CVE.
> 
> Files rights get a strange "**NULL SID**" and the other windows users have incorrect permissions.
> This impact all staged files but also the .git folder, for example the ".git\config" file.

What "certain conditions" would those be?

**Comment by frederic-meyrou** [comment]
Dear,
You can **close** the issue, I found another Git version included in CygWin was messing up in my PATH and giving the above result, version 2.25.0 is not the faulty guy. 
Sorry for this post.
./Fred

**Comment by dscho** [comment]
Ah, good to know! Thanks for adding the detail so I don't have to worry about this ticket any further.
