### ISSUE TITLE
Shell window keeps opening on the "wrong" monitor

### ISSUE THREAD

**Issue by binkleym** [git-for-windows/git#2503]
I have a two-monitor setup at home.   My main monitor died, and I've noticed that the MinTTY shell absolutely refuses to come up on the right monitor.   Many Windows applications will remember the monitor they last ran on and will spawn there, but that isn't happening in this case.

There appears to be a fairly simple solution outlined here:

https://stackoverflow.com/questions/52755/what-determines-the-monitor-my-app-runs-on

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.25.0, 64 bit

```
$ git --version --build-options

$ git --version --build-options
git version 2.25.0.windows.1
cpu: x86_64
built from commit: 7c71c859c97853ed057da5cbab12f3c13b5554df
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 1909, 64 bit, all security updates applied

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.628]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults for all

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Clicked on Git Bash icon in taskbar.

 - What did you expect to occur after running these commands?

I expected to close the window, click on Git Bash icon again, and have the shell window open in the monitor I closed it from. 

Instead, it always opens from monitor #2.

**Comment by dscho** [comment]
That sounds like an issue for https://github.com/mintty/mintty/issues to me...
