### ISSUE TITLE
Git stash conflict shows my changes as theirs

### ISSUE THREAD

**Issue by eblis** [git-for-windows/git#251]
Not sure if this is how it's supposed to work (can't see why though) but when doing a git stash pop with conflicts I see all my changes from the stash in the "theirs" panel instead of "mine".
I'd expect the changes coming from the stash to be in the "mine" panel and the other changes in the "theirs" panel.
Like I mentioned I'm not sure if it's supposed to behave that way or not, can't remember how it used to be with the old Git for Windows and I haven't tested on Linux systems.

**Comment by dscho** [comment]
Please test using [Vagrant](https://github.com/git-for-windows/git/wiki/Vagrant).

**Comment by PhilipOakley** [comment]
Is this a Git-gui issue, or a git cli issue (command line interface)?

**Comment by eblis** [comment]
This was most probably with an external diff viewer, but I've moved to Linux since then so no longer an issue for me.
