### ISSUE TITLE
Git for windows no longer using /etc/hosts

### ISSUE THREAD

**Issue by novettaberin** [git-for-windows/git#2517]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```
Windows Version
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.592]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I use the /etc/hosts file for my dev environment since I have special requirements to get to our local nexus and other build artifact servers.  The corporate laptops are pretty locked down, so this was an ideal option to avoid escalating to admin privileges just to update the HOSTS information.  It also localized those entries to when I was doing active development.

### Details

 - Which terminal/shell are you running Git from? Bash

 - What commands did you run to trigger this issue?

```
Any command that tries to resolve DNS:

ping
mvn (contacts the nexus repository, who's entry was in the /etc/hosts file)
```
 - What did you expect to occur after running these commands?

I expected DNS to resolve the entry I had in the /etc/hosts file (not the global Windows hosts file)

 - What actually happened instead?

The /etc/hosts file was ignored.  I had to elevate privileges to edit the global Windows hosts file in order to resolve my nexus repository host.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

The URL is private, but it was a name that resolved to localhost so that the SSH tunnel I had set up could resolve it in the cloud.  The issue was resolving the name in the first place.

**Comment by rimrul** [comment]
>What commands did you run to trigger this issue?
Any command that tries to resolve DNS:
ping
mvn (contacts the nexus repository, who's entry was in the /etc/hosts file)

Are you sure that ever worked?

We ship neither `mvn` nor `ping`. `ping` should fall back to microsofts `C:\Windows\System32\ping.exe` which doesnt know about `/etc/hosts` and `mvn` is probably a third party application and doesn't know about `/etc/hosts` either.

**Comment by bericoberin** [comment]
My set up was working... but now you've got me wondering if I had those entries in both places and then an update to Docker for Windows clobbered my entries.

**Comment by altimumdelta** [comment]
GFW copies the hosts file from system once during installation and never again, and then it uses it's local version which may be outdated if you update the global one.

DNS and stuff, like DNS Client service, I don't think that has any idea about the Git copy of the hosts file, it obviously will only deal with the system one.

I don't have any DNS stuff myself so I'm not familiar, I have all the DNS services  and caching in the OS and Browsers completely disabled, as well as other caches, I don't mind the wait for lookups to ISP, it's not that long, I rather avoid the issues of outdated DNS cache even if they're rare, and the super annoying old versions of a website and refresh button reading from the damn cache, the modern browsers gotten way out of their mind with agressive caching, it's a web browser, not a cache browser.

**Comment by dscho** [comment]
> GFW copies the hosts file from system once during installation and never again, and then it uses it's local version which would get outdated if you update the global one.

I think you're right: https://github.com/git-for-windows/git-sdk-64/blob/0bd032cc2c77356039629e871356ae4597706b20/etc/post-install/06-windows-files.post#L1-L25

Maybe we should side-step this in the installer if we can create symlinks, and use symlinks for those?

**Comment by dscho** [comment]
> Maybe we should side-step this in the installer if we can create symlinks, and use symlinks for those?

This will need some work from someone else than me.
