### ISSUE TITLE
Where to post issues with bash script?

### ISSUE THREAD

**Issue by toninlg** [git-for-windows/git#252]
Hi,
I have an issue with a bash script under git-for-windows, where should I post this?

The issue is the following:
I write an here doc to a file in a script and after it is generated, I use unix2dos to convert this file to CR+LF line endings.
```
cat <<EOF > $GITROOT/version_s.h
...
EOF
if [[ $? -eq 0 ]]; then
  unix2dos "$GITROOT/version_s.h"
fi
```
Sometimes it works but most of the time it does not work. Message is:
>unix2dos: problems renaming 'D:/path/d2utmpDpOVbm' to 'D:/path/version_s.h': Device or resource busy
          output file remains in 'D:/path/d2utmpDpOVbm'

If I add a sleep, it always works and under Linux, a similar script seems to always work.

Thank you.

**Comment by dscho** [comment]
Looks like a locking problem: some process seems to access the file when `unix2dos` wants to rename it. Probably your virus scanner.

Please note that `unix2dos` is shipped with Git for Windows only as a convenience, I do not really provide support for that executable.
