### ISSUE TITLE
Git status for worktree on drive mounted to subfolder broken with 2.25.1

### ISSUE THREAD

**Issue by csware** [git-for-windows/git#2522]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git for Windows 2.25.1 x64

```
$ git --version --build-options

git version 2.25.1.windows.1
cpu: x86_64
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.657]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
Plink Path: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The directory structure is as follows:
D:\TortoiseGit <- the main repository (also is a junction to another folder)
D;\ssd <- SSD mounted to a folder
D:\ssd\tgit <- associated worktree of the main repository
D:\ssd\tgit\ext\OGDF\\.git file contains "gitdir: ../../../../TortoiseGit/.git/worktrees/tgit/modules/ext/OGDF" which is correct

Seems to be a regression of 2.25.1, worked in 2.25.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd/powershell/TortoiseGit

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status
```
 - What did you expect to occur after running these commands?

see the status of the worktree

 - What actually happened instead?

```
fatal: cannot chdir to '../../../../../../../ssd/tgit/ext/OGDF': No such file or directory
fatal: 'git status --porcelain=2' failed in submodule ext/OGDF
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/TortoiseGit/TortoiseGit

**Comment by csware** [comment]
`git.exe submodule update --progress --init --force` solved the issue.

**Comment by dscho** [comment]
> D:\ssd\tgit\ext\OGDF.git file contains "gitdir: ../../../../TortoiseGit/.git/worktrees/tgit/modules/ext/OGDF" which is correct

Shouldn't this be `../../../`, i.e. only 3 instead of 4 levels?

**Comment by csware** [comment]
> Shouldn't this be `../../../`, i.e. only 3 instead of 4 levels?

No, 4 is correct (first strips OGDF, second strips ext, third strips tgit, and the last one strips ssd).

I still wonder why I get this issue after the upgrade from 2.25 to 2.25.1 and why submodule update fixed this.

**Comment by dscho** [comment]
But OGDF is a file? You cannot traverse away from a file via `../`.

**Comment by csware** [comment]
OGDF is a submodule and, therefore, a folder

**Comment by dscho** [comment]
Sorry, I misread... in my defense, I was reading it on a cell phone...

**Comment by dscho** [comment]
As to the problem, I think this is unfortunately required in your use case, as we now resolve symlinks (and mount points) when determining the current directory. Your forced reinitialization most likely turned the relative path into an absolute one, and that is why it does not matter what the current directory is resolved as: there is simply no relative path on Windows to go from one drive letter to another one, so that would not work to begin with.

These days (and from what I recall, this has been the case fore quite a few years), the `.git` file in a submodule contains the _absolute_ path of the actual git dir. Therefore, the forced reinitialization would give you what new clones would have given you for a few years: absolute paths in the `.git` file. And those absolute paths sidestep that change where the current directory would now be reported as the SSD path instead of the `D:` one.

**Comment by csware** [comment]
Well, in the .git-file of all my submodule there is still a relative path,

**Comment by dscho** [comment]
> Well, in the .git-file of all my submodules there still are relative paths,

Then you have them for a _long_ time, I believe... These days, I don't think that relative paths are used if you clone a submodule afresh.
