### ISSUE TITLE
The ssh.exe and ssh-keygen shipped with version 2.25.1 has an issue with keyexchange algorithm/cipher

### ISSUE THREAD

**Issue by arijitmicrosoft** [git-for-windows/git#2523]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
**$ git --version --build-options

git version 2.25.1.windows.1
cpu: x86_64
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 8
```

 -  Windows10, 64-bit**

```
$ cmd.exe /c ver

**Microsoft Windows [Version 10.0.18363.657]**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
   Default settings
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 The inbuilt ssh works fine :  C:\Windows\System32\OpenSSH
 But the ssh.exe under git throws below error:
  ```
  Unable to negotiate with xx.xx.xx.xxx port 22: no matching key exchange method found. Their 
  offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
  fatal: Could not read from remote repository
  ```
 Even when I try to change key exchange algorithm using, it throws error:
 ```
 ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 user@host
 Error: shell request failed on channel 0
 ```

> **So I have copied the ssh.exe from this location C:\Windows\System32\OpenSSH to C:\Program Files\Git\usr\bin\ and it works fine**.

**There is some issue with the ssh.exe which is shipped with Latest version of Git.
    The issue started occuring after I upgraded Git to  2.25.1**

### Details

 - Which terminal/shell are you running Git from? 
    **Git Bash**

 - What commands did you run to trigger this issue?
```
    ssh-keygen
    Copied public key to server
    git pull (ssh authentication)
```
 - What did you expect to occur after running these commands?

 **Successful ssh authentication and git pull thereafter**

 - What actually happened instead?

**Got following error:**
```
  Unable to negotiate with xx.xx.xx.xxx port 22: no matching key exchange method found. Their 
  offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
  fatal: Could not read from remote repository
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**The repository is Highly Confidential and is hosted under xxx.visualstudio.com**

**Comment by arijitmicrosoft** [comment]
This info might help:
```
ssh -G user@vs-ssh.visualstudio.com

hostname vs-ssh.visualstudio.com
port 22
addkeystoagent false
addressfamily any
batchmode no
canonicalizefallbacklocal yes
canonicalizehostname false
challengeresponseauthentication yes
checkhostip yes
compression no
controlmaster false
enablesshkeysign no
clearallforwardings no
exitonforwardfailure no
fingerprinthash SHA256
forwardx11 no
forwardx11trusted no
gatewayports no
gssapiauthentication no
gssapidelegatecredentials no
hashknownhosts no
hostbasedauthentication no
identitiesonly no
kbdinteractiveauthentication yes
nohostauthenticationforlocalhost no
passwordauthentication yes
permitlocalcommand no
proxyusefdpass no
pubkeyauthentication yes
requesttty auto
streamlocalbindunlink no
stricthostkeychecking ask
tcpkeepalive yes
tunnel false
verifyhostkeydns false
visualhostkey no
updatehostkeys false
canonicalizemaxdots 1
connectionattempts 1
forwardx11timeout 1200
numberofpasswordprompts 3
serveralivecountmax 3
serveraliveinterval 0
ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,aes256-cbc,aes192-cbc
hostkeyalgorithms ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
hostbasedkeytypes ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
casignaturealgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256
loglevel INFO
macs umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
securitykeyprovider $SSH_SK_PROVIDER
pubkeyacceptedkeytypes ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
xauthlocation /usr/X11R6/bin/xauth
identityfile ~/.ssh/id_rsa
identityfile ~/.ssh/id_dsa
identityfile ~/.ssh/id_ecdsa
identityfile ~/.ssh/id_ecdsa_sk
identityfile ~/.ssh/id_ed25519
identityfile ~/.ssh/id_ed25519_sk
identityfile ~/.ssh/id_xmss
canonicaldomains
globalknownhostsfile /etc/ssh/ssh_known_hosts /etc/ssh/ssh_known_hosts2
userknownhostsfile ~/.ssh/known_hosts ~/.ssh/known_hosts2
forwardagent no
connecttimeout none
tunneldevice any:any
controlpersist no
escapechar ~
ipqos af21 cs1
rekeylimit 0 0
streamlocalbindmask 0177
syslogfacility USER

```

**Comment by dscho** [comment]
The latest OpenSSH disables SHA-1 based key exchange by default, IIRC.

If you are certain about the consequences, I *think* you can enable it via the SSH config (I don't know the details, you will have to study the SSH documentation).

**Comment by arijitmicrosoft** [comment]
> The latest OpenSSH disables SHA-1 based key exchange by default, IIRC.
> 
> If you are certain about the consequences, I _think_ you can enable it via the SSH config (I don't know the details, you will have to study the SSH documentation).

Thanks @dscho . Just a quick question: 
When I try this : ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 user@host
Error: shell request failed on channel 0
 Why it throws the error. Do I need to explicitly change the config file?

**Comment by dscho** [comment]
I *think* that this means that your host does not allow for interactive shell sessions. That's quite common for Git hosting services. Try `git ls-remote`...

**Comment by arijitmicrosoft** [comment]
> I _think_ that this means that your host does not allow for interactive shell sessions. That's quite common for Git hosting services. Try `git ls-remote`...

Can you please elaborate this because I am trying in my local and also could not get the context of ```git ls-remote``` here?

**Comment by dscho** [comment]
To use `git ls-remote`, you would have to add the option to `~/.ssh/config` instead of the command-line (probably guarded by a `Host <hostname>` line), then call `git ls-remote <ssh-url-of-repository>`.

**Comment by arijitmicrosoft** [comment]
> To use `git ls-remote`, you would have to add the option to `~/.ssh/config` instead of the command-line (probably guarded by a `Host <hostname>` line), then call `git ls-remote <ssh-url-of-repository>`.

Thanks @dscho . As far as I get it git ls-remote is used for displaying references available in a remote repository along with the associated commit IDs, what are we trying to do here with this. Let me question in other way - How do I set the specific key exchange algorithm in git config from bash ? Is it like MinTTY is an emulator so its happening?

**Comment by dscho** [comment]
> what are we trying to do here with this.

The `git ls-remote` command is a relatively cheap way to test SSH connections, that's why I wanted you to try it. You don't have to have a local clone to fetch to/push from.

> Let me question in other way - How do I set the specific key exchange algorithm in git config from bash ?

There is no way. This is an SSH setting, so it really needs to be configured in the SSH config.

Technically, you could play games with [`core.sshCommand`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand), but that would override _all_ SSH connections. You really want to restrict the use of the unsafe hash to as few connections as possible.

> Is it like MinTTY is an emulator so its happening?

MinTTY has nothing to do with it. MinTTY is like the [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701), i.e. a program that opens and manages a terminal window in which `cmd.exe` or a Bash can run.

**Comment by arijitmicrosoft** [comment]
> > what are we trying to do here with this.
> 
> The `git ls-remote` command is a relatively cheap way to test SSH connections, that's why I wanted you to try it. You don't have to have a local clone to fetch to/push from.
> 
> > Let me question in other way - How do I set the specific key exchange algorithm in git config from bash ?
> 
> There is no way. This is an SSH setting, so it really needs to be configured in the SSH config.
> 
> Technically, you could play games with [`core.sshCommand`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand), but that would override _all_ SSH connections. You really want to restrict the use of the unsafe hash to as few connections as possible.
> 
> > Is it like MinTTY is an emulator so its happening?
> 
> MinTTY has nothing to do with it. MinTTY is like the [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701), i.e. a program that opens and manages a terminal window in which `cmd.exe` or a Bash can run.

Thanks a lot @dscho for the clarification and inputs. Closing the issue.

**Comment by awei186** [comment]
C:\Program Files\Git\etc\ssh\ssh_config
open up the ssh_config file(not sshd_config file) and add the lines:
Host *
    KexAlgorithms +diffie-hellman-group1-sha1

**Comment by dscho** [comment]
> Host *
> KexAlgorithms +diffie-hellman-group1-sha1

@awei186 how about doing this only for select hosts? So far, I am aware of `ssh.dev.azure.com` needing the exception. Do you know of other ones?

**Comment by dscho** [comment]
@awei186 what I am proposing is to imitate git-for-windows/build-extra@3cadc4cd0abf69b3458e0863d6c21829654d0cfb to make these edits so that the next official Git for Windows version does this for all users.

**Comment by arijitmicrosoft** [comment]
> C:\Program Files\Git\etc\ssh\ssh_config
> open up the ssh_config file(not sshd_config file) and add the lines:
> Host *
> KexAlgorithms +diffie-hellman-group1-sha1

@awei186 - The inbuilt windows ssh.exe works fine even without adding anything. But the ssh.exe shipped with Git does not. So I replaced the Git's ssh.exe with Window's ssh.exe and it worked for me.

**Comment by dscho** [comment]
> So I replaced the Git's ssh.exe with Window's ssh.exe and it worked for me.

Please note that the latter is most likely not v8.2, but an earlier version, probably OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5.

**Comment by dscho** [comment]
It looks as if a change is being rolled out (or maybe has finished rolling out) so that at least Azure Repos can be accessed using OpenSSH v8.2.

@arijitmicrosoft could you verify that, and if it works for you, too, close this ticket?

**Comment by arijitmicrosoft** [comment]
Thanks @dscho . It is working now. :) closing the ticket
