### ISSUE TITLE
issue with bash command "git config --global"

### ISSUE THREAD

**Issue by Duraisys** [git-for-windows/git#2528]
- Above command in git bash trying to get config file from some odd directory in my computer

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

   Bash  64 bit 2.25.1

** insert your machine's response here **

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10, 64 bit
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash  64 bit 2.25.1**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

** $ git config --global user.email "*********.*@gmail.com" **
```
 - What did you expect to occur after running these commands?

** update config file **

 - What actually happened instead?

** error: could not lock config file C:/Users/*******/Documents/******/*******/******/.gitconfig: No such file or directory**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**No **

**Comment by dscho** [comment]
That's really an _awful_ lot of placeholders that have not been replaced with useful information.

The trick will be to find out where the environment variable `HOME` is set, and to what. You could of course just force your system-wide `HOME` environment variable to the appropriate value (probably identical to `USERPROFILE`) and close this ticket.

**Comment by Duraisys** [comment]
Thanks. It works now.

Regards,
Duraikkannan

**Comment by dscho** [comment]
> It works now.

@Duraisys  Wait. What happened? How was this fixed? Can you add _any_ information, so as to help other people who look for help and find this here ticket in a web search?

**Comment by PhilipOakley** [comment]
@Duraisys I also had to double check what had been written. Do you mean that @dscho suggestion that setting your system-wide `HOME` environment variable to `USERPROFILE` worked for you?

If so, would you be able to show the actual command you used to help provide a worked an example for future readers (it probably now feels obvious to you, but lets give others a clue :wink:)

**Comment by Duraisys** [comment]
I did the following with windows 10
select: System (Control Panel) Click the Advanced system settings link.
Click Environment Variables. Edited the path of the environment variable
'HOME' to %USERPROFILE%  (or the path where GIT project is, the file
.gitconfig is available at this path).  It seems I can even edit .gitconfig
opening it with NOTEPAD.

Regards,
Duraikkannan

**Comment by dscho** [comment]
@Duraisys ??????
