### ISSUE TITLE
Segmentation fault while `git subtree push`

### ISSUE THREAD

**Issue by vladipus** [git-for-windows/git#2529]
while executing git subtree push --prefix path/to/subtree repo master

git version 2.25.1.windows.1 64 bit on Windows 10

`sh.exe.stackdump`:
```
Exception: STATUS_STACK_OVERFLOW at rip=7FFC22261137
rax=0000000000001110 rbx=000000018023CCE0 rcx=0000000000000000
rdx=0000000180213D60 rsi=0000000600018190 rdi=000000018023CCE0
r8 =0000000000723600 r9 =0000000600018190 r10=00000000FFE03000
r11=00000000FFE03000 r12=00000000FFE05020 r13=000000000000031C
r14=00000000FFE05030 r15=00000000FFE04F00
rbp=0000000000000420 rsp=00000000FFE04CF8
program=C:\Program Files\Git\usr\bin\sh.exe, pid 507, thread 
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B

```

tried halting the Kaspersky antivirus with no luck

**Comment by Aboood412** [comment]
> while executing git subtree push --prefix path/to/subtree repo master
> 
> git version 2.25.1.windows.1 64 bit on Windows 10
> 
> `sh.exe.stackdump`:
> 
> ```
> Exception: STATUS_STACK_OVERFLOW at rip=7FFC22261137
> rax=0000000000001110 rbx=000000018023CCE0 rcx=0000000000000000
> rdx=0000000180213D60 rsi=0000000600018190 rdi=000000018023CCE0
> r8 =0000000000723600 r9 =0000000600018190 r10=00000000FFE03000
> r11=00000000FFE03000 r12=00000000FFE05020 r13=000000000000031C
> r14=00000000FFE05030 r15=00000000FFE04F00
> rbp=0000000000000420 rsp=00000000FFE04CF8
> program=C:\Program Files\Git\usr\bin\sh.exe, pid 507, thread 
> cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
> ```
> 
> tried halting the Kaspersky antivirus with no luck

https://github.com/git-for-windows/git/issues/2529#issue-571908451
