### ISSUE TITLE
warning: failed to restrict file handles (5)

### ISSUE THREAD

**Issue by seven-deuce** [git-for-windows/git#2532]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8


```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1039]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

BASH

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
 - What did you expect to occur after running these commands?

nothing new to pull

 - What actually happened instead?

saw this error:
$ git pull
warning: failed to restrict file handles (5)

handle #0: 000000000000022c (type 3, handle info (1) 0
handle #1: 0000000000000230 (type 3, handle info (1) 1
handle #2: 0000000000000468 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
Hi @seven-deuce 

Thanks for providing the report as requested. That bug has now been fixed in the following and subsequent releases. Time to update your Git-for-Windows.

Here is a link to the releases page https://github.com/git-for-windows/git/releases/ There have also been Git security fixes as well, so definitely worth updating.

Philip

**Comment by dscho** [comment]
The real question for me is why a failed DNS lookup in `ssh.exe` is reported as "5", i.e. as  [`ERROR_ACCESS_DENIED`](https://github.com/git-for-windows/git-sdk-64/blob/1b9e75e0fe7e1edf28d333c224c81e88e4b81cfb/mingw64/x86_64-w64-mingw32/include/winerror.h#L50)

**Comment by rimrul** [comment]
That's the problem with numerical errors. They change meaning based on context. This 5 seems to mean ERRSET_NODATA (caused by h_errno NO_DATA).

**Comment by dscho** [comment]
For the record, when I try to reproduce this (based on the provided error message, not based on any recipe to reproduce because the contributor did not provide one), I see this:

```
$ git pull ssh://does.not.exist.com/ master
ssh: Could not resolve hostname does.not.exist.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
