### ISSUE TITLE
Unable to schedule the git for windows update

### ISSUE THREAD

**Issue by peterennisrda** [git-for-windows/git#2534]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.25.1.windows.1
cpu: x86_64
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

64 bit

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17763.1039]
(c) 2018 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
C:\Users\peterennis>type "C:\Program Files\Git\etc\install-options.txt"
type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Nano
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Download and install new release

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

![Capture307](https://user-images.githubusercontent.com/1280523/75817658-66b11380-5d4c-11ea-843a-f15478d50e14.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Is it possible that the installer is correct, and you cannot schedule tasks on this computer because you do not have permissions?

**Comment by peterennisrda** [comment]
I am the admin and have permissions.


*Peter Ennis, MSc*
*Resource Development Associates*
2333 Harrison Street │Oakland, CA 94612
Direct Phone: 510.488.4342 │Main Phone: 510.488.4345 x112
*peterennis@resourcedevelopment.net
<peterennis@resourcedevelopment.net>* │*www.resourcedevelopment.net
<http://www.resourcedevelopment.net>*

**Comment by dscho** [comment]
Maybe the log would help you figure out more? You can enable it via the command-line option `/LOG=<logfile>` of the installer.

**Comment by aquetzaly** [comment]
C:\User\Usuario\AppaData\Local\Temp\is-NLRA6.tmp\git-config-get.txt

**Comment by dscho** [comment]
> I am the admin and have permissions.

@peterennisrda have you tried registering the job yourself, manually? Here is [what the installer does](https://github.com/git-for-windows/build-extra/blob/61ab85665b5a6672f3cb3cbbdc1bae05d28d3671/installer/install.iss#L2411-L2451):

```
procedure InstallAutoUpdater;
var
    Res:Longint;
    LogPath,ErrPath,AppPath,XMLPath,Start:String;
begin
    Start:=GetDateTimeString('yyyy-mm-dd','-',':')+'T'+GetDateTimeString('hh:nn:ss','-',':');
    XMLPath:=ExpandConstant('{tmp}\auto-updater.xml');
    AppPath:=ExpandConstant('{app}');
    SaveStringToFile(XMLPath,
        '<?xml version="1.0" encoding="UTF-16"?>'+
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">'+
        '  <Settings>'+
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>'+
        '    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>'+
        '    <StartWhenAvailable>true</StartWhenAvailable>'+
        '    <IdleSettings>'+
        '      <StopOnIdleEnd>false</StopOnIdleEnd>'+
        '      <RestartOnIdle>false</RestartOnIdle>'+
        '    </IdleSettings>'+
        '  </Settings>'+
        '  <Triggers>'+
        '    <CalendarTrigger>'+
        '      <StartBoundary>'+Start+'</StartBoundary>'+
        '      <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>'+
        '      <ScheduleByDay>'+
        '        <DaysInterval>1</DaysInterval>'+
        '      </ScheduleByDay>'+
        '    </CalendarTrigger>'+
        '  </Triggers>'+
        '  <Actions Context="Author">'+
        '    <Exec>'+
        '      <Command>"'+AppPath+'\git-bash.exe"</Command>'+
        '      <Arguments>--hide --no-needs-console --command=cmd\git.exe update-git-for-windows --quiet --gui</Arguments>'+
        '    </Exec>'+
        '  </Actions>'+
        '</Task>',False);
    LogPath:=ExpandConstant('{tmp}\remove-autoupdate.log');
    ErrPath:=ExpandConstant('{tmp}\remove-autoupdate.err');
    if not Exec(ExpandConstant('{sys}\cmd.exe'),ExpandConstant('/C schtasks /Create /F /TN "Git for Windows Updater" /XML "'+XMLPath+'" >"'+LogPath+'" 2>"'+ErrPath+'"'),'',SW_HIDE,ewWaitUntilTerminated,Res) or (Res<>0) then
        LogError(ExpandConstant('Line {#__LINE__}: Unable to schedule the Git for Windows updater (output: '+ReadFileAsString(LogPath)+', errors: '+ReadFileAsString(ErrPath)+').'));
end;
```

As you can see, it generates an XML file and then asks `schtasks` to create a job from that XML. You could try to look at the (incorrectly-named) `remove-autoupdate.log` and `remove-autoupdate.err` files while the installer shows this error dialog (the files should be located in the youngest `is-*` subdirectory of `%TEMP%` which is typically identical to `%APPDATA%\Local\Temp`), and you could also copy the `auto-updater.xml` file from that subdirectory and try running the indicated `schtasks` command with that XML file manually.
