### ISSUE TITLE
Installer: Suggest VSCodium

### ISSUE THREAD

**Issue by GitMensch** [git-for-windows/git#2537]
### Setup 

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Installer Git-2.25.1-64

### Issue

Installer suggests to install and use VSCode User.
As those installed binaries are explicit non-free and also include telemetry (which _can_ be seen as a security issue) I'd like to see the entry either being replaced or put next to a [VSCodium](https://github.com/VSCodium/vscodium) option.

**Comment by dscho** [comment]
> As those installed binaries are explicit non-free and also include telemetry (which _can_ be seen as a security issue) I'd like to see the entry either being replaced or put next to a [VSCodium](https://github.com/VSCodium/vscodium) option.

If you _really_ feel strongly about this, you will find no obstacle to imitating, say, how Atom is supported, by copy-editing all the Atom-related parts of https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss.

You can then test it by following the instructions at https://github.com/git-for-windows/git/wiki/Making-an-installer, and eventually open a Pull Request.
