### ISSUE TITLE
SSH sometimes doesn't work

### ISSUE THREAD

**Issue by tigerjack** [git-for-windows/git#2538]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.25.1.windows.1
cpu: x86_64
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.657]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

default options
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** Nothing relevant **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh username@remotehost
```
 - What did you expect to occur after running these commands?

A password prompt should be displayed

 - What actually happened instead?

Permission denied error.

### Further details
Trying to ssh using putty, the PowerShell or even the WSL with ubuntu worked seamlessly. I am having this problem only using `git-sdk-64` and not even on all the machines. I honestly don't know what are the differences between the different servers or ssh remote agents. Also, the same problem shows up if I try to use my ssh key pair.

A few comparisons between Powershell and Git-SDK
#### Powershell
```
$ (get-command ssh.exe).Path
C:\Windows\System32\OpenSSH\ssh.exe
```

#### Git SDK 

```
$ which ssh
/usr/bin/ssh
```
```
$ pacman -Ss openssh
git-for-windows/openssh 8.2p1-1 (net-utils) [installed]
    Free version of the SSH connectivity tools
git-for-windows/openssh  7.9p1-3

msys/openssh 8.1p1-1 (net-utils) [installed: 8.2p1-1]
    Free version of the SSH connectivity tools
```

**Comment by dscho** [comment]
> Permission denied error.

Can you paste the full log, please?

**Comment by tigerjack** [comment]
The full log of the ssh command? Do you mean by using the `-vvv` flag?

**Comment by dscho** [comment]
I meant any type of log. It wasn't pasted, but summarized instead, right? Typically I expect the full command and its output pasted in a bug report (with sensitive data redacted clearly).

**Comment by tigerjack** [comment]
Here are the three different files corresponding to the three different shells. Maybe it is just a problem of OpenSSH version or maybe it is related to the kind of protocols accepted by the server, but I'm not sure of it.

[powershell.txt](https://github.com/git-for-windows/git/files/4311298/powershell.txt)
[ubuntu_wls.txt](https://github.com/git-for-windows/git/files/4311299/ubuntu_wls.txt)
[git_sdk.txt](https://github.com/git-for-windows/git/files/4311300/git_sdk.txt)

**Comment by dscho** [comment]
I will just paste the output here myself. This is from the run in the Git for Windows SDK:

```
OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019
debug1: Reading configuration data /c/Users/MYUSERID/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolve_canonicalize: hostname HOST is address
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug2: ssh_connect_direct
debug1: Connecting to HOST [HOST] port 22.
debug1: connect to address HOST port 22: Permission denied
ssh: connect to host HOST port 22: Permission denied
```

I have never seen such an error message this early in the process, my best guess is that this is some application-level firewall blocking Git for Windows' copy of OpenSSH.

**Comment by tigerjack** [comment]
Do you think that it may be related to the version of OpenSSH? If you see the other two files, the version is at 7.x for Powershell and Ubuntu WSL.

**Comment by dscho** [comment]
> Do you think that it may be related to the version of OpenSSH? If you see the other two files, the version is at 7.x for Powershell and Ubuntu WSL.

You can easily test that theory yourself, by downloading https://wingit.blob.core.windows.net/x86-64/openssh-8.1p1-1-x86_64.pkg.tar.xz and installing it using `pacman -U openssh-8.1p1-1-x86_64.pkg.tar.xz`.

Does the same problem happen in a regular Git for Windows, as installed via the installer, e.g. https://github.com/git-for-windows/git/releases/download/v2.26.0-rc0.windows.1/Git-2.26.0-rc0-64-bit.tar.bz2 ?
