### ISSUE TITLE
Include `getopt` in release package

### ISSUE THREAD

**Issue by silverkorn** [git-for-windows/git#254]
For direct/easier support of the popular [Nvie's GitFlow](https://github.com/nvie/gitflow) & it's [AVH Edition](https://github.com/petervanderdoes/gitflow) and potentially other Git extensions, do you think the package could include the MinGW `getopt` command utility? 
(Ref: https://github.com/nvie/gitflow/wiki/Windows#msysgit)

Do you see a pitfall or risk doing so?
Thanks in advance!

**Comment by linquize** [comment]
Do mingw-64/msys2 have getopt package?

**Comment by silverkorn** [comment]
Here's some pre-built from MSYS2:
- http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/i686/getopt-1.1.5-2-i686.pkg.tar.xz/download
- http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/getopt-1.1.5-1-x86_64.pkg.tar.xz/download

**Comment by silverkorn** [comment]
The previous ones needs the MSYS2 dynamic library.

I guess you guys can get the source of it instead and fit it in the environment of Git-For-Windows: http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/Sources/getopt-1.1.5-1.src.tar.gz/download

**Comment by dscho** [comment]
@silverkorn that ("us guys getting the source of it and fit it in the environment of Git-For-Windows") is not how Git for Windows works... If you are interested to learn how it works: https://github.com/git-for-windows/git/wiki#about

**Comment by silverkorn** [comment]
Ok, so as I understand, I actually need to contribute by following your guidelines using the SDK and explaining the use?

**Comment by silverkorn** [comment]
Using the [git-sdk-installer-1.0.0-64.7z.exe](https://github.com/git-for-windows/build-extra/releases/download/git-sdk-1.0.0/git-sdk-installer-1.0.0-64.7z.exe), I'm trying to install the SDK but the following packages cannot be fetched:
- mingw-w64-x86_64-binutils-2.25.1-1-any.pkg.tar.xz
- mingw-w64-x86_64-gcc-5.2.0-3-any.pkg.tar.xz
- mingw-w64-x86_64-gcc-ada-5.2.0-3-any.pkg.tar.xz
- mingw-w64-x86_64-gcc-objc-5.2.0-3-any.pkg.tar.xz
- mingw-w64-x86_64-python2-2.7.10-4-any.pkg.tar.xz
- python-3.4.3-2-x86_64.pkg.tar.xz

```
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.25.1-1-any.pkg.tar.xz
' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred th
e last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.25.1-1-any.pkg.tar.xz
' from downloads.sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.25.1-1-any.pkg.tar.xz
' from www2.futureware.at : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed retrieving file 'mingw-w64-x86_64-gcc-5.2.0-3-any.pkg.tar.xz' from
 repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last
 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-gcc-5.2.0-3-any.pkg.tar.xz' from
 downloads.sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-gcc-5.2.0-3-any.pkg.tar.xz' from
 www2.futureware.at : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed retrieving file 'mingw-w64-x86_64-gcc-ada-5.2.0-3-any.pkg.tar.xz'
from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the
last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-gcc-ada-5.2.0-3-any.pkg.tar.xz'
from downloads.sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-gcc-ada-5.2.0-3-any.pkg.tar.xz'
from www2.futureware.at : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed retrieving file 'mingw-w64-x86_64-gcc-objc-5.2.0-3-any.pkg.tar.xz'
 from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the
 last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-gcc-objc-5.2.0-3-any.pkg.tar.xz'
 from downloads.sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-gcc-objc-5.2.0-3-any.pkg.tar.xz'
 from www2.futureware.at : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed retrieving file 'mingw-w64-x86_64-python2-2.7.10-4-any.pkg.tar.xz'
 from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the
 last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-python2-2.7.10-4-any.pkg.tar.xz'
 from downloads.sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-python2-2.7.10-4-any.pkg.tar.xz'
 from www2.futureware.at : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed retrieving file 'python-3.4.3-2-x86_64.pkg.tar.xz' from repo.msys2
.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

error: failed retrieving file 'python-3.4.3-2-x86_64.pkg.tar.xz' from downloads.
sourceforge.net : The requested URL returned error: 416
error: failed retrieving file 'python-3.4.3-2-x86_64.pkg.tar.xz' from www2.futur
eware.at : The requested URL returned error: 404
warning: failed to retrieve some files
```

I tried to look around for the package list used but it doesn't seems to be possible through the [build-extra](https://github.com/git-for-windows/build-extra) repository.

Some of those doesn't indeed exists such as `mingw-w64-x86_64-binutils-2.25.1-1-any.pkg.tar.xz` on http://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/, where `mingw-w64-x86_64-binutils-2.25-1-any.pkg.tar.xz` without the additionnal "-1" exists.

**Comment by nalla** [comment]
Try using the new msys2 mirrors. Look in the upstream msys-mirrors package for the current list. I'll provide a link tomorrow.

**Comment by nalla** [comment]
I take that back. I just checked the sdk setup. It is already using the new mirrors.

**Comment by silverkorn** [comment]
No worries, the issue was because of our proxy was not entirely trusting [repo.msys2.org](http://repo.msys2.org/) so it requested an user interaction by clicking the link manually so I managed to download them from [repo.msys2.org](http://repo.msys2.org/) by hand and drop them in the `var/cache/pacman/pkg` directory.

But now, I'm not sure where's the configuration file to build `getopt.exe` into `./mingw32/bin/` or `./mingw64/bin/`, all I can see is that it's available under `./usr/bin/`.

To be honest, unfortunately I'm not really familiar with the modulation of Git for Windows and it's kind of cryptic for me at the moment, which is why I requested to add the `getopt.exe` as default for further releases if nobody sees a pitfall.

Thanks again!

**Comment by nalla** [comment]
You could start by modifying the https://github.com/git-for-windows/build-extra/blob/master/make-file-list.sh#L32 and creating an installer that contains the `getopt` package. Then make some size tests with and without it. After testing your modification, you can create a pull request of that named file with your strong arguments for the addition.

**Comment by silverkorn** [comment]
Alright, thank you for the guidance!

**Comment by silverkorn** [comment]
Ok, the pull request was created: https://github.com/git-for-windows/build-extra/pull/68.
I will close this issue and continue on this PR.

Thanks again!
