### ISSUE TITLE
git diff strange warning for gitattributes when diff file in subfolder

### ISSUE THREAD

**Issue by toninlg** [git-for-windows/git#255]
Hi,
I've a repository with four subfolders in it and .gitattributes at the root.
When using the following command:
```
git diff adb8ff70694379ee2d339ef94900b602fa62593c:folder/file.c..cae5dc93450f6d604debfbe832790f0c2968ce48:folder/file.c
```
The diff is shown but the following warnings are shown at the end:
>warning: unable to access 'adb8ff70694379ee2d339ef94900b602fa62593c:folder/.gitattributes': Invalid argument
>warning: unable to access 'adb8ff70694379ee2d339ef94900b602fa62593c:folder/file.c..cae5dc93450f6d604debfbe832790f0c2968ce48:folder/.gitattributes': Invalid argument
>warning: unable to access 'cae5dc93450f6d604debfbe832790f0c2968ce48:folder/.gitattributes': Invalid argument

version is Git for Windows 2.3.5 release 8.
I've cloned the repository to linux with git version 2.4.6, no warnings are displayed.
I've installed the last version Git-2.4.6-5th on another computer without doing any specific git config, cloned the repository and same warnings are displayed.

I've no warning on Windows when doing:
```
git diff adb8ff70694379ee2d339ef94900b602fa62593c:.gitignore..cae5dc93450f6d604debfbe832790f0c2968ce48:.gitignore
```
Thank you.

**Comment by toninlg** [comment]
It can be reproduced with a repository with 3 commits:
- 1st commit: 
.gitattributes file at git root folder with some lines
- 2nd commit:
folder/file.txt with some lines
- 3rd commit:
add some lines in folder/file.txt

then:
git diff sha1_commit2:folder/file.txt sha1_commit3:folder/file.txt

in this case, I've only two warnings: 
- sha1_commit2:folder/.gitattributes
- sha1_commit3:folder/.gitattributes

**Comment by dscho** [comment]
@toninlg can you please provide a complete verifiable example? I.e. something like a repository that only needs to be cloned and a script inside that needs to be run to demonstrate the bug?

**Comment by toninlg** [comment]
@dscho You can clone https://github.com/toninlg/gitattributes_warning.git

**Comment by dscho** [comment]
I can confirm with the MCVE that this is a Windows-only bug.

**Comment by dscho** [comment]
@toninlg please test https://github.com/git-for-windows/git/pull/276.

**Comment by dscho** [comment]
@toninlg please test #276.

**Comment by toninlg** [comment]
Sorry for the time to reply.
I have tested #276 on top of last commit on master and I can confirm that it solves the problem.

Thank you.

**Comment by dscho** [comment]
> I have tested #276 on top of last commit on master and I can confirm that it solves the problem.

Perfect! Thanks for testing!
