### ISSUE TITLE
Forcing git to use native SSH program

### ISSUE THREAD

**Issue by grolongo** [git-for-windows/git#2552]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git for Windows version:

```
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Windows OS version:

```
Microsoft Windows [version 10.0.18362.720]
```

 - Git for Windows options:

```
Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

### Details

 - Terminal used:

PowerShell 5.1.18362.628

 - What commands did you run to trigger this issue? 

```
git push -u origin master
```
 - What did you expect to occur after running these commands?

git not asking for my passphrase since ssh-agent is already set with my rsa-key passphrase

 - What actually happened instead?

git asks for my passphrase each time I want to push a commit.

I'm using the native Windows 10 ssh program to connect to my servers.
I'm using the ssh-agent aswell to avoid typing the passphrase each time.
Everything works fine.

Now when using git, it asks me to enter the passphrase, because git uses it's internal ssh program instead of the native one.

The question is simple: how can I tell git to use the ssh provided with Windows instead of the one shipped with Git for Windows?

**Comment by dscho** [comment]
>  I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I was: #1683.

If you want to give it a hand, follow the steps indicated in https://github.com/git-for-windows/git/issues/1683#issuecomment-389831224.

If you instead only want to work around the issue, configure [`core.sshCommand`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand).
