### ISSUE TITLE
Git gui crashes on hitting commit then buttons are grayed out

### ISSUE THREAD

**Issue by Utumno** [git-for-windows/git#2554]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.719]
(c) 2019 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\_\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I just updated to git 2.26.0

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Git Bash**

 - What commands did you run to trigger this issue?

I add a commit message and hit Commit on git gui.

 - What did you expect to occur after running these commands?

Have git gui commit the staged changes with the message provided

 - What actually happened instead?

A dialog pops up with the contents:

```
child process exited abnormally
child process exited abnormally
    while executing
"close $fd_ot"
    (procedure "commit_committree" line 24)
    invoked from within
"commit_committree file3f0ef50 189422a6cec1429dc415aff0127a98339a94aada .git/GITGUI_EDITMSG"
```

The gui becomes unresponsive afterwards and must be shut down from process explorer

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It is a local repo and it does not happen to others at thius time - however I do get this crash once in a while on random repos. Commiting from git Bash `$ git commit -m FFF` works and then (a new instance of) git gui is able to commit again as normal

Please let me know if there is any steps I can take to debug this, it is a recurring issue.

**Comment by PhilipOakley** [comment]
in my system it (`close $fd_ot`) is at C:\Program Files\Git\mingw64\share\git-gui\lib\commit.tcl line 356

the files will probably be there twice, once with .tcl suffix and once without (IIRC, the executed version is the one without the file type suffix).

Also report it at https://github.com/prati0100/git-gui/issues where the maintainer lives;-)

**Comment by dscho** [comment]
> in my system it (`close $fd_ot`) is at C:\Program Files\Git\mingw64\share\git-gui\lib\commit.tcl line 356

Tcl counts the lines from the start of the `proc`, if I remember correctly.

> It is a local repo and it does not happen to others at thius time - however I do get this crash once in a while on random repos.

@Utumno The best course of action would most likely be to work with/on your local repository until you get it into a shape where other people can use it to reproduce. Everything else will just make it so excruciatingly hard on people who want to help as to prevent them from assisting you.

What I mean by "working with/on your local repository" is: try to wiggle down the problem. You likely staged a couple of files, then wrote a commit message, it failed, then you used the command line and it worked, and that was that.

You could now try to go back by resetting to the worktree state after the succeeded commit via `git reset --hard <succeeded-commit>`, then reset the `HEAD` to the state where Git GUI failed to commit, via `git reset --soft HEAD^`, and then verify that Git GUI fails again.

Then you could try with a very simple commit message, just to see whether _that_ is the problem.

If it is not, you could unstage all the files except for one, to see whether it was one or more files that were the problem.

You could run [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) in the background to figure out what the exact command-line of the `git commit` call was that was spawned from Git GUI, and the exact problem that caused it to abort.

There is so much you can do to turn this into an [MCVE](https://stackoverflow.com/help/mcve). And only you can do that.

**Comment by Utumno** [comment]
Thanks for the pointers! I will try and find some time and courage to debug this. Meanwhile, I am closing it, as it isn't much help as it stands plus it rather belongs to the  https://github.com/prati0100/git-gui/issues (seems to be a git gui rather than git issue)
