### ISSUE TITLE
cwd.dll incorrectly compiled, prevents git add -p

### ISSUE THREAD

**Issue by zoidbergthepopularone** [git-for-windows/git#2560]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing, although https://github.com/git-for-windows/git/issues/2490 may be related (not sure).

### The problem

I am listing the "setup" below, since it is required, but it if fairly irrelevant. The problem is quite obviously caused by the fact that cwd.dll (GIT\usr\lib\perl5\core_perl\auto\Cwd\cwd.dll) and apparently quite a few, if not all, other Python DLLs, are now compiled without the IMAGE_DLL_CHARACTERISTICS_DYNAMIC_BASE flag in the DllCharacteristics field. Which means that if *any* library happens to want the same space that is already occupied, then that library will fail to load and any functionality it provides will not be available.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.26.0.windows.1
cpu: i686
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 4
```
Occurs in 2.25.0 as well.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.18363.657]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
I am using portable in C:\Git. No installation was performed so install-options.txt do not exist.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
No.
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
cmd.exe
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add -p somefile.txt
```
 - What did you expect to occur after running these commands?

```
Get a choice of actions for each difference found.
```

 - What actually happened instead?

```
      1 [main] perl 297 child_info_fork::abort: address space needed by 'Cwd.dll' (0x1D0000) is already occupied                                                Can't fork, trying again in 5 seconds at C:/GIT/mingw32/share/perl5/Git.pm line 1621.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

```
Happens in all repositories but not necessarily on all computers.
```

**Comment by rimrul** [comment]
>Python dlls

I don't think we ship any python dlls, so I'll assume you meant perl.

The issue is, our perl is based on MSys2. And AFAIK MSys2 and Cygwin can't be compiled with dynamic base.

**Comment by rimrul** [comment]
See https://github.com/git-for-windows/git/wiki/32-bit-issues#solutions for some workarounds that might help.

**Comment by dscho** [comment]
Once you call `git config --system add.interactive.usebuiltin true`, the issue will be gone.

Alternatively, you can call `usr\bin\bash -lc "/usr/bin/rebase -b 0x63070000 /usr/lib/perl5/core_perl/auto/*/{*,*/*}.dll"` in the top-level directory of the portable Git. This is a [known 32-bit issue](https://github.com/git-for-windows/git/wiki/32-bit-issues)
