### ISSUE TITLE
Provide /usr/share/bash-completion/bash_completion in git-bash

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#2562]
git-bash bash_completion is unlike standard Msys2 or Linux.

In standard Msys2 or standard Linux, bash_completion directory structure is like this:

`/usr/share/bash-completion/bash_completion` is a file that contains completion functions.
`/usr/share/bash-completion/completion` is a directory that contains many scripts for different commands, including git

But in git-bash, 

`/usr/share/bash-completion/bash_completion` does not exists
`/usr/share/bash-completion/completion` is a directory that contains only several scripts for svn, vim, ..., but without git
`/mingw64/share/git/completion/git-completion.bash`: correspond to `/usr/share/bash-completion/completion/git`
`/mingw64/share/git/completion/git-prompt.sh`: only in git-for-windows

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64-bit

```
$ git --version --build-options
git version 2.26.0.windows.1
```
What I need is to provide `/usr/share/bash-completion/bash_completion` in git-bash.
This allows me to use bash completion for some other programs that uses certain functions defined in `/usr/share/bash-completion/bash_completion`

**Comment by dscho** [comment]
@linquize seems you already know how to fix this. Why not go ahead and do it?

**Comment by linquize** [comment]
I just compare the difference between git bash and msys2, but I don't know how to fix it

**Comment by glhez** [comment]
Due to some problem I ran with @, I created the pull request to introduce bash-completion. 
The bash-completion is loaded by bash, so now, you do have _filedir and so on.

You will have to install your own completion following the question "Where should I install my own local completions?" in the bash-completion FAQ: https://github.com/scop/bash-completion.

**Comment by dscho** [comment]
Closing as stale.

**Comment by mloskot** [comment]
Apparently, there is lots of tools offering Bash completions like `kubectl` which rely on `_filedir` fuction from `bash_completions` package itself. Those have limited usability in the Git Bash w/o the package:

![image](https://user-images.githubusercontent.com/80741/233077188-d445944e-651a-4bde-978d-c50f02c034f1.png)
