### ISSUE TITLE
Screen configuration change not detected on git-gui start-up

### ISSUE THREAD

**Issue by joachim-durchholz-six** [git-for-windows/git#2564]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

(Note: I didn't check closed issues, as this is clearly a bug.)

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

git-gui version 0.21.GITGUI
git version 2.24.0.windows.2
Tcl/Tk version 8.6.9

```
$ git --version --build-options
git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
C:\Users\tkd6u>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Laptop & multi-monitor setup.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Directly from the Windows Start menu.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

* Had the laptop connected to additional monitors
* Configured monitors and laptop screen in non-mirrored mode (i.e. use the additional monitors for additional desktop estate)
* Started git-gui.
* Opened a repository.
* Moved the git-gui window to an additional monitor.
* Closed git-gui again.
* Sent Windows to sleep and/or standby.
* Disconnected the additional monitors.
* Started git-gui, called up repository.

 - What did you expect to occur after running these commands?

** The repository window would be moved to the laptop display, to make it visible. **

 - What actually happened instead?

** The respository window would stay at its original position, which would now be off-screen. (Verified by pressing Alt-space, down-arrow, then left-arrow to move the window into view.) **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** This happens independently of what repository is shown. **

**Comment by dscho** [comment]
Isn't this a Git GUI issue more than a Git for Windows issue? The Git GUI maintainer once indicated that they would prefer bug reports via [the Git mailing list](mailto:git@vger.kernel.org), but apparently https://github.com/prati0100/git-gui/issues is open for everyone now.

**Comment by joachim-durchholz-six** [comment]
I can't really tell what the right project would be.
It may be that different calls are needed on different platforms. Then it would be git-for-windows
It may be that git-gui has an abstraction layer that handles the platform differences. Then it would be git-gui.
It may be that Tk is supposed to shield applications from multi-monitor hassles. Then it would be for Tk.

I supposed the "most downstream" project needs to to the triage for that, and either submit an upstream bug report or tell me what the right project to report this to would be. (YMMV.)

**Comment by dscho** [comment]
It is my understanding, indeed, that this issue might be in Git GUI *or* in Tk. The Git GUI maintainer will most likely be able to help further (but the Git for Windows maintainer, i.e. yours truly, won't be able to do that).

**Comment by joachim-durchholz-six** [comment]
Well, it's an issue in Git for Windows, which is the software I'm using.
You can still defer this upstream, but I cannot because whenever there's a problem reproducing this there will always be the questio of whether it's really a Git for Windows issue or not, and that would not be helpful.

Feel free to close, but I won't open an upstream issue - I have as little time as anybody else, but I'm less qualified to follow up with this than you so this will just drop into the cracks.

**Comment by dscho** [comment]
As you wish.

**Comment by joachim-durchholz-six** [comment]
I clearly don't wish that this be closed...

**Comment by PhilipOakley** [comment]
@joachim-durchholz-six Maybe copy-paste your text to the link dscho gave, and a ref back here, and at least you'll get one more set of eyes on it, with Github providing auto cross references.

**Comment by joachim-durchholz-six** [comment]
It's really better if you guys open any issues; you know better than me whom to contact and what to do in every single scenario that I can imagine.
I am willing to do my best to provide details if technical questions arise, or if a test is called for (but I'll need a test release of Git for Windows to do that because I don't have the build toolchain - see, you guys will stay involved no matter how we set this up).

**Comment by PhilipOakley** [comment]
"involved" => "makes the tea" ;-) [from one of my many other roles, as an adviser/mentor]

**Comment by dscho** [comment]
@joachim-durchholz-six I won't do as you ask, and here is why: there are several millions of Git for Windows users, but only one maintainer. That maintainer has to choose wisely how to spend their time. And that's precisely what I believe I am doing here. I "taught you how to fish", and that is the best I could do in this ticket.

**Comment by joachim-durchholz-six** [comment]
No need to be smug about teaching me anything. I have been knowing how to find a project's upstream and feedback channels for many years now, thank you very much.

Personal issues aside, I still don't know what the git-gui people need to hear to convince them that it's really their issue. And I don't want to waste my, their, and your time by getting sent back to you because they'll very likely say "oh you're using Git for Windows, talk it over with them first".
(I am and was a maintainer in other projects, so I know how this specific game gets started and how it plays out - been there, done that, on all sides of every fence.)

**Comment by dscho** [comment]
I guess my need to be respected was not really met, and that's why I lost track of this ticket. It's probably a good idea to lay this ticket to rest at long last, anyway.
