### ISSUE TITLE
credential.github.com.usehttppath=true Not working

### ISSUE THREAD

**Issue by shcrouch** [git-for-windows/git#2565]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64
```
$ git --version --build-options

git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.720]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:


** insert your machine's response here **
```
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

powershell, vscode and git bash for windows

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch
```
 - What did you expect to occur after running these commands?

Expected git to fetch the commits remotely using the credential I have stored for that specific repository. 
(Using Git Credential Manager for Windows plugin which utilises Windows credential manager.
The command I have used to ensure git passes the FULL https path to Windows credential manager is this: 

git config --global credential.github.com.useHttpPath true)

This means I can have been able to store a credential for http://github.com/repo1/repo.git
and another credential for  http://github.com/repo2/repo.git. 

This has stopped working recently and I think it's due to recent upgrade to 2.26.0

 - What actually happened instead?

Prompts me for credentials and when I provide the credential it then stores it for all future requests to http://github.com/* which means I can't set alternative credentials for other repos.

git config -l shows these relevant lines: 

credential.helper=manager
credential.github.com.usehttppath=true

**Comment by dscho** [comment]
> This has stopped working recently and I think it's due to recent upgrade to 2.26.0

From which version? Can you pinpoint a bit more which [snapshot](https://wingit.blob.core.windows.net/files/index.html) is the first to break this feature? Can you come up with a [Minimal, Complete & Verifiable Example](https://stackoverflow.com/help/mcve) based on running `git credential` directly (you can paste lines of the form `host=github.com` into `git credential fill`, see https://git-scm.com/docs/git-credential#IOFMT)?

**Comment by shcrouch** [comment]
I've just downloaded a few snapshots and have narrowed down the change of behavior on commit  ```235cd37426c7799ba8982fad1b61c408c0d88f43``` (2.26.0 rc0) 

BEFORE this commit when you run ```git config --global credential.github.com.useHttpPath true``` 
and then save the credential it will save it with the full path , 
e.g.

![image](https://user-images.githubusercontent.com/62308630/77930303-a4994d00-72a2-11ea-9dfd-692aca007a18.png)

When changing to the commit mentioned above, it will save the creds like this: 

![image](https://user-images.githubusercontent.com/62308630/77930370-b8dd4a00-72a2-11ea-81c7-cff9b89af85e.png)

This affects all github.com repos and so you can't store different creds for each one using credential manager. 

Shaun

**Comment by dscho** [comment]
> I've just downloaded a few snapshots and have narrowed down the change of behavior on commit 235cd37426c7799ba8982fad1b61c408c0d88f43 (2.26.0 rc0)

So it looks as if you're saying that 091745393cb11db6eb55eab509d3d0a1a243c7d5 was the last good state of `master`? Out of `git graph 091745393..235cd3742 -p -- credential.c`, this commit sticks out: 46fd7b390034. It looks like the pattern matching was shipped off to a different code path rather than doing our own, credential-specific thing here. The biggest difference seems to be that it is now a URL pattern. Which makes me suspect that the culprit might be the missing protocol. Does it work again when you do this?

```sh
git config --global credential.https://github.com.useHttpPath true
```

**Comment by sdcscripts** [comment]
Brilliant! That's exactly right, it's now working as expected and I can see the more specific URL entries in Credential Manager. 

Thanks @dscho :)

**Comment by dscho** [comment]
@shcrouch feel free to close this, unless there are outstanding concerns :-)

**Comment by shcrouch** [comment]
Many thanks 👍
