### ISSUE TITLE
Very simple python credential helper does not work

### ISSUE THREAD

**Issue by mPyth** [git-for-windows/git#2566]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows 8.1 Pro 64 bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

In order to reproduce the problem python 3 is needed (year or two old, not the problem)
```
>python --version
Python 3.8.2
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I've tried to report issue twice on [git@vger.kernel.org](git@vger.kernel.org) but unsuccessfully (I've got failure notice). I have impression that problem is not windows specific but because it is reproduced on windows client I'm trying to report it here.

I made a virtual machine with intention to be git server using HTTPS protocol with basic authentication (DDNS setup, port forwarding, apache config, ...). Address of that server machine is `grip.ddns.net`. On that machine I've created bare git repo on the path `git/test.git` with credentials `usename/password=myUsername/myPassword`.

On windows client machine where `credential.helper` is not set (`git config --global --unset credential.helper`) I successfully cloned that repo by using next command (after I entered username and password manually):
```
  git -c http.sslVerify=false clone https://grip.ddns.net/git/test.git
  cd test
  git config http.sslVerify false
```
Command `git pull` worked nice (I'm prompted to enter username and password each time).

After that I wrote a python script which represents super simple credential helper.
I configured git to use my script with following command:
```
  git config --global credential.helper abs/path/to/my/simplePythCredHelper.py
```
Below is content of mentioned python script `simplePythCredHelper.py` (exception handlers are removed for clarity). Script simply prints exactly the same credentials to standard out which work nice when I'm entering them manually (when credential helper is unset). In another words username and password are hard-coded in the form described on [Git Tools - Credential Storage](https://git-scm.com/book/sr/v2/Git-Tools-Credential-Storage) page.
```
#!/usr/bin/env python
import sys

def main():
    operation = sys.argv[1]
    #sys.stderr.write("some message" + '\n')  <-- it is possible to use this line to print something to the screen
    if operation == "get":
        #print("protocol=https")        <-- even tried to uncomment this line and the next one, but to no effect
        #print("host=grip.ddns.net")
        print("username=myUsername")
        print("password=myPassword")

if __name__ == "__main__":
    main()
```
After this I've tried to call command:
```
git pull
```

 - What did you expect to occur after running these commands?

I expected that `git pull` would work in the same way as I entered credentials manually, but that wasn't the case.

 - What actually happened instead?

I've got next error message:
```
fatal: Authentication failed for 'https://grip.ddns.net/git/test.git/'
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

URL: `https://grip.ddns.net/git/test.git/`, credentials: `myUsername/myPassword`

I've tried to set environment variables `GIT_TRACE` and `GIT_TRACE_SETUP` but didn't get anything useful. Similar Python code is possible to find on following pages: [here](https://dev.to/pratham/custom-git-credential-helper-pfa) and [here](https://github.com/z00nx/git-credential-keepasshttp/blob/master/bin/git-credential-keepasshttp) .

It would be nice if someone could take a look or give me instructions for further debugging.

**Comment by dscho** [comment]
Git for Windows does not come with a Python interpreter. You may be able to get your use case to work by installing Python.

**Comment by mPyth** [comment]
That's true, but it is not so hard to install Python (I've already mentioned the version I use is 3.8.2, but it could be 3-4 years old, as long as it's 3.x). I need simple example similar to my Python script (it has only 4 functional line of code) with hard-coded username and password in whatever language (C, C++, Java) that works. I suppose that Python is the simplest way for such demo. I will easily 'translate' that demo to python.
I have impression that I've followed instructions form documentation (and on a few web pages), but it doesn't work even though it is super simple.
I've just tried to use [git-credential-keepasshttp](https://github.com/z00nx/git-credential-keepasshttp) and find that all components in chain work as expected ([`git-credential-keepasshttp`](https://github.com/z00nx/git-credential-keepasshttp) ->[`keepasshttp`](https://github.com/MarkusFreitag/python3-keepasshttp) -> [`KeepAss`](https://keepass.info/)), the only problem is communication betwen `git` and `git-credential-keepasshttp` which is on the beginning of chain.

**Comment by rimrul** [comment]
Does a batch file version of your simple helper work?

I feel like Git know how to open your python file.

```
@echo off
IF %1 NEQ get GOTO :EOF

echo username=myUsername
echo password=myPassword
```

**Comment by rimrul** [comment]
Could you also try directly calling `/usr/bin/env python` (prefixed with the path to your git installation) from cmd?

**Comment by mPyth** [comment]
@dscho and @rimrul thanks for your effort.
**1*** Regarding the first line in python script (shebang) `#!/usr/bin/env python` . Seems that this line is simply ignored on my Windows (I've just copied from an online example). That path is Linux path which should produce error on Windows. I'm using Python in virtual environment (standard way to run multiple python projects with dependency on same libraries but different versions of those libraries). Calling directly my python script without python prefix from command line executes it fine (as it is mentioned in the script line `sys.stderr.write("some message" + '\n')` prints message on display - so I used it for a kind of debugging).
**2*** I've just made a batch that @rimrul proposed, set it as my credential helper, and it worked nice !!!
I've tried one case more: if a character is added to hard-coded username or password inside the batch script, exactly the same error is reported as in case of my python script - this is expected behavior for batch script.

Ok, I have now example that works nice (although with not so clear batch commands, but enough to continue bug chase).
Guys I would like to thank you for your help.
If I find the cause of the problem I'll post it here.

**Comment by rimrul** [comment]
Ok, I can explain.

Line 1: don't print out each command before executing it.

Line 2: If parameter 1 (`%1`) isn't equal to (`NEQ`) `get` goto the end of the file (`GOTO :EOF`)

Line 3 and 4: print out the following text

**Comment by mPyth** [comment]
I've just found the cause of the problem with Python script.
If print lines are replaced with following lines:
```
        sys.stdout.write("username=myUsername" + "\n")
        sys.stdout.write("password=myPassword" + "\n")
```
or with next ones:
```
        print("username=myUsername", flush=True)
        print("password=myPassword", flush=True)
```
python script is working without error.

The cause of the problem was default behavior of python `print()` f-on which by default directs output to buffer, and i one moment from buffer to standard output. That means although two lines are printed to standard output, it is interpreted by `git` as only one input with bad format. This subtle difference in behavior took me many hours.

If argument `flush` is set to `True` the stream is forcibly flushed (more details [here](https://docs.python.org/3/library/functions.html#print)).

@rimrul I would like to thank you, without your help I wouldn't know which direction to look for the problem.
