### ISSUE TITLE
Install Error - Cannot create file ...fd

### ISSUE THREAD

**Issue by vbjay** [git-for-windows/git#2568]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I'm not.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Installing latest git
```
 - What did you expect to occur after running these commands?

Successful install

 - What actually happened instead?

![image](https://user-images.githubusercontent.com/3629489/78034515-d5769200-7335-11ea-8e48-6fae20ba77b6.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
N/A

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/78035620-584c1c80-7337-11ea-8af2-4346d4409ed6.png)

**Comment by dscho** [comment]
So the problem is that this file... exists already?

**Comment by vbjay** [comment]
Probably.

**Comment by dscho** [comment]
You could verify by deleting those files manually and reinstalling.

**Comment by dscho** [comment]
> You could verify by deleting those files manually and reinstalling.

Would you please verify, and come back with the results? I cannot fix this issue based on guesswork, I'll have to have a little assistance from your side.

**Comment by Pentasis** [comment]
I have had this error come up every time I update git for windows (at least for a year). Last week I did a **clean** install of 2.29 and that worked _without_ this error. But today I got the 2.29.1 update and this happened again. So I think it has something to do with the update-script rather than the install-script?

**Comment by dscho** [comment]
I still can only guess. My current working hypothesis is that _some_ process holds an open handle to that file. It is deleted while the previous Git for Windows version is uninstalled, but as long as any process still holds a handle to it, it cannot be recreated.

**Comment by dscho** [comment]
Closing as stale.
