### ISSUE TITLE
git-bash utility in version 2.25.1-64-bit of Portable Git for Windows shows the password in clear text

### ISSUE THREAD

**Issue by akshayhiremath** [git-for-windows/git#2570]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

OS: Windows 10 (Version 1809 Build 177763.1039)
Portable Git version: 2.25.1-64-bit and 2.26.0-64-bit
Git utility: git-bash.exe
PSCP (secure file transfer utility): pscp.exe  64 bit v 0.73, released on 2019-09-29 (Accessory with putty.exe available at  https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)
Redirected to the above download url from www.putty.org

```
$ git --version --build-options

git version 2.25.1.windows.1
cpu: x86_64
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1039]
(c) 2018 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

I'm using  git-bash.exe in Git Portable v 2.25.1-64-bit and 2.26.0-64-bit
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The same pscp.exe utility when used to transfer files from windows to linux through Windows CMD doesn't show the password.
So it doesn't seem like a problem of pscp.exe. When I use this utility with WIndows CMD or PowerShell I don't face this problem.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
1. Download 64-bit Git for Windows Portable v 2.26.0 or 2.25.1
2. Download pscp.exe 64-bit v 0.73
3. Extract Portable Git and start git-bash.exe in the Portable Git
4. Use pscp.exe to transfer any file to a Linux/Unix machine (My target server was on OS HP-UX 11.23)
   Example usage command: 
$pscp.exe <fileName> <userId>@<serverHostname>:<pathOnTheServer>
$pscp.exe testFile.txt user1@unixServer:/home/user1

5. Password will be asked
6. Start typing password. "Password will appear in the git-bash terminal in CLEAR TEXT."

```
 - What did you expect to occur after running these commands?

the password shouldn't be visible in CLEAR text

 - What actually happened instead?

Password appears in CLEAR text

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Does it work when you call `winpty pscp` instead of just `pscp`?

**Comment by akshayhiremath** [comment]
No. When I use winpty I get error: ssh_init: Host does not exist

In earlier versions of git-bash, the password wasn't visible when pscp was used without winpty (as given in a command the issue description), last I had used pscp from git-bash on windows was somewhere around December 2018, I don't remember the version number then.

**Comment by dscho** [comment]
Maybe you had installed Git for Windows using the default Windows console window for Git Bash instead of MinTTY?

**Comment by akshayhiremath** [comment]
There was no installation. Its portable Git. You just have to unzip it and execute.

**Comment by dscho** [comment]
> There was no installation. Its portable Git. You just have to unzip it and execute.

Right, you even said so in the title, sorry. It _would_ probably work in the Windows console, but there is no easy way to configure a portable Git to use that.

**Comment by akshayhiremath** [comment]
Using PortableGit-2.27.0-64-bit. Don't see this issue anymore so closing.
