### ISSUE TITLE
Waiting for your editor to close the file

### ISSUE THREAD

**Issue by chucklu** [git-for-windows/git#2571]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.720]
(c) 2019 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rebase --continue
```
 - What did you expect to occur after running these commands?

rebase successfully

 - What actually happened instead?

hint: Waiting for your editor to close the file... "C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor: C:/Program Files (x86)/GitExtensions/GitExtensions.exe: No such file or directory
error: There was a problem with the editor '"C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.

**Comment by chucklu** [comment]
The problem is I have already uninstalled GitExtensions last year.
![image](https://user-images.githubusercontent.com/3004057/78332408-8d1bd600-75ba-11ea-9850-3ded789343c8.png)

I resolved the conflict by TortoiseGit, when will you give the error info "Waiting for your editor to close the file"?

**Comment by chucklu** [comment]
I was on branchA, and use command git rebase BranchB.
Then I encounter conflict, I resolve the conflict by TortoiseGit and try to use `git rebase --continue`.

I tried to use TortoiseGit to commit the staged changes. Then switch to bash, execute git rebase --continue, then it works.

I guess there might be a bug when you check for "Waiting for your editor to close the file".

**Comment by dscho** [comment]
You probably need to unset `core.editor` manually. Try running `git config --show-origin --get-all core:editor` to find out where.

**Comment by chucklu** [comment]
The command you provided did not work
git config --show-origin --get-all core:editor
error: key does not contain a section: core:editor

I tried with  `git config --global --list`, then  I find the configuration.
**Open C:\Users\username\.gitconfig** and remove the core.editor section manually.
[core]
	autocrlf = true
	editor = \"C:/Program Files (x86)/GitExtensions/GitExtensions.exe\" fileeditor
	commitGraph = true

Thanks.

**Comment by dscho** [comment]
Sorry, yes, typo (phone keyboards...): `core.editor`, not `core:editor`.
