### ISSUE TITLE
Windows-style paths don't work with <rev>:<path> style object references

### ISSUE THREAD

**Issue by JTBrinkmann** [git-for-windows/git#2578]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing. I searched for a combinations of "show", "path", "backslash", "unix" and "exists on disk, but not in" on the issue tracker and DuckDuckGo.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17763.1098]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

default installation using scoop, no options where set, no install-options.txt is present.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

installed via scoop

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```batch
$ git init example
Initialized empty Git repository in C:/Users/admin.NB064075/example/.git/
$ cd example
$ echo test > sample.txt
$ git add sample.txt
$ git commit -m "initial commit"
[master (root-commit) ead1705] initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 sample.txt

$ git show HEAD:.\sample.txt
fatal: path '.\sample.txt' exists on disk, but not in 'HEAD'

$ git diff HEAD:sample.txt HEAD:.\sample.txt
fatal: path '.\sample.txt' exists on disk, but not in 'HEAD'

$ git show HEAD:./sample.txt
foo
```
 - What did you expect to occur after running these commands?

I expect `git show`, `git diff`, etc to allow Windows style paths when specifying objects using the `<rev>:<path>` form

- What actually happened instead?

git does not find the objects unless using unix-style paths.

The [git documentation on `<rev>:<path>`](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emltrevgtltpathgtemegemHEADREADMEememmasterREADMEem) explicitly mentions paths beginning with "./" and "../", but that seems unrelated, yet. The issue happens with backslashes anywhere in the path (e.g. `git show HEAD:foo\bar.txt`)

**Comment by dscho** [comment]
The paths inside Git are always using forward-slashes. Git does not provide a filesystem, after all, let alone a Windows one. So what you see is quite expected: Git even allows backslashes as part of the file name, therefore `git show HEAD:.\sample.txt` would literally mean that you refer to a file with the file name `.\sample.txt` (which is not legal on Windows, but it is on Linux/macOS/Unix).
