### ISSUE TITLE
fatal: unable to update url base from redirection

### ISSUE THREAD

**Issue by turmary** [git-for-windows/git#2579]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git version 2.17.1.windows.2
64-bit
```
$ git --version --build-options
** insert your machine's response here **
git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Windows 7 64-bit.
$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [版本 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
git clone https://os.mbed.com/users/hudakz/code/CAN_Hello
```
 - What did you expect to occur after running these commands?

** insert here **
Clone successful.

 - What actually happened instead?

** insert here **
Failed.
```
git clone https://os.mbed.com/users/hudakz/code/CAN_Hello
Cloning into 'CAN_Hello'...
fatal: unable to update url base from redirection:
  asked for: https://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs?service=git-upload-pack
   redirect: https://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs/?service=git-upload-pack
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **
https://os.mbed.com/users/hudakz/code/CAN_Hello

I think the strcmp call in function update_url_from_redirect() should only compare the base part not the entire string of got->buf, tail could be changed while base url not.

**Comment by dscho** [comment]
You could try what you suggested re: strcmp. Please follow the guidance described in https://github.com/git-for-windows/git/wiki/Building-Git

**Comment by turmary** [comment]
hi,
I tested the URL https://os.mbed.com/users/hudakz/code/CAN_Hello after change the function update_url_from_redirect() with below patch.
```patch
diff --git a/http.c b/http.c
index 10f564d87b..edd8e1921a 100644
--- a/http.c
+++ b/http.c
@@ -1975,6 +1975,9 @@ static int update_url_from_redirect(struct strbuf *base,
        if (!strcmp(asked, got->buf))
                return 0;

+       if (!strncmp(asked, got->buf, base->len))
+               return 1;
+
```
so update_url_from_redirect() could return, but the clone still not work.
Now I think this problem is caused by the site os.mbed.com.

It's strange the URL above could be imported successfully by github.com.

**Comment by dscho** [comment]
> ```
> git clone https://os.mbed.com/users/hudakz/code/CAN_Hello
> Cloning into 'CAN_Hello'...
> fatal: unable to update url base from redirection:
>   asked for: https://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs?service=git-upload-pack
>    redirect: https://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs/?service=git-upload-pack
> ```

FWIW I just tried this command in WSL, and it also failed, in the exact same way.

> It's strange the URL above could be imported successfully by github.com, see https://github.com/turmary/CAN_Hello.

Maybe it's not so strange when you realize that it is actually a Mercurial repository:

```
$ hg clone https://os.mbed.com/users/hudakz/code/CAN_Hello
destination directory: CAN_Hello
requesting all changes
adding changesets
adding manifests
adding file changes
added 10 changesets with 21 changes to 4 files
new changesets 1b9561cd1c36:3211e88e30a5
updating to branch default
3 files updated, 0 files merged, 0 files removed, 0 files unresolved
```

**Comment by turmary** [comment]
Hi dscho,
Thank you for pointing out Mercurial.
will close this issue soon.

**Comment by dscho** [comment]
Reading back, I realize that I had forgotten to put a smiley... Sorry about that!
