### ISSUE TITLE
git-gui cannot start

### ISSUE THREAD

**Issue by bbolli** [git-for-windows/git#258]
Launching git gui, either from git-bash or gitk, gives this error message:
```
couldn't execute "C:\Tools\Git\mingw32\libexec\git-core\git-update-index.exe": invalid argument
couldn't execute "C:\Tools\Git\mingw32\libexec\git-core\git-update-index.exe": invalid argument
    while executing
"error $err"
    (procedure "_open_stdout_stderr" line 16)
    invoked from within
"_open_stdout_stderr [concat $opt $cmdp $args]"
    (procedure "git_read" line 26)
    invoked from within
"git_read update-index  -q  --unmerged  --ignore-missing  --refresh  "
    (procedure "rescan" line 40)
    invoked from within
"rescan ui_ready"
    (procedure "do_rescan" line 2)
    invoked from within
"do_rescan"
    ("after" script)
```

Starting `git update-index  -q  --unmerged  --ignore-missing  --refresh` from the shell works fine, so I wonder if it has to do with the DOS path that is used to start git-update-index.exe.

**Comment by bbolli** [comment]
Oh, and FWIW, this worked in the old Git for Windows (1.9.5).

**Comment by nalla** [comment]
Can not reproduce with `git version 2.4.6.windows.1`. launching `git gui` in a repository seems to work just fine. Maybe you could provide a [MCVE](http://stackoverflow.com/help/mcve)?

**Comment by bbolli** [comment]
So, here's the "MCVE":
1. Start git-bash.exe version 2.4.6.windows.1 under Windows 10 Pro Build 10240
2. `cd`into any Git repository (I've tried two different ones)
3. `git gui`
4. See the Application Error reported above
5. The Git GUI is displayed, but the "Rescan", "Stage Changed" and "Commit" buttons are disabled
I'm afraid it doesn't get much more minimal than this :-)

**Comment by dscho** [comment]
If you use 64-bit Git for Windows, does it work?

**Comment by bbolli** [comment]
I have only a 32-bit Windows, so I can't verify this.

**Comment by russellwinstead** [comment]
I was having a similar issue with git gui in the 32-bit Git for Windows.  The 64-bit Git for Windows seems to work fine though.

**Comment by borekb** [comment]
Confirming the issue on 32-big Git for Windows.

**Comment by dscho** [comment]
> I have only a 32-bit Windows,

It would have been *really* important to mention this, as per our [bug reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines).

As it is, I cannot reproduce this error at all. To illustrate as an example of what I encourage you to do when reporting issues like this one, here is the account of what I did:

1. on Windows Server 2012 R2 running in 64-bit mode, I installed the 32-bit portable Git from [here](https://github.com/git-for-windows/git/releases/download/v2.4.6.windows.1/PortableGit-2.4.6-5th-release-candidate-32-bit.7z.exe) into `C:\issue-258`, executing the downloaded file as `.exe`.
2. Then I called `C:\issue-258\git-bash.exe` from the Start menu.
3. I then switched to a tiny Git repository I had checked out from [here](https://github.com/t-pascal/tortoisegit-colons) before.
4. Then I called `git gui`.

The Git GUI started without problems.

> `bash: C:/Tools/Git/mingw32/libexec/git-core/git-update-index.exe: Permission denied`

Have you investigated further on this end? This really looks wrong, and it should have looked wrong to you, too. Does that file exist at all? Does it have executable permissions? Can you open it from the explorer? Etc etc etc

If you provide me with an MCVE that actually reproduces the problem here, I can see whether I can find the time to investigate on my end. In the alternative that investigation is for you to undertake, or for the others who claim to be able to reproduce the error on their machines.

**Comment by bbolli** [comment]
So, I have found a workaround for this issue: simpliy delete `/mingw32/libexec/git-core/git-update-index.exe`. The `update-index` subcommand is built-in to `git.exe`:

    $ GIT_TRACE=1 git update-index.exe -q --unmerged --ignore-missing --refresh
    22:38:49.260793 git.c:348               trace: built-in: git 'update-index' '-q' '--unmerged' '--ignore-missing' '--refresh'

so the external version is not needed. `git-gui` adapts automatically.

See the next comment for the underlying reason for the `Permission denied` error.

**Comment by bbolli** [comment]
Checking `/mingw/libexec/git-core` in Windows Explorer, I noticed that each binary whose name contains the word `update` has an icon with the "Admins only" shield:

![image](https://cloud.githubusercontent.com/assets/21444/9184103/83bae64c-3fb3-11e5-904b-2ceeca3e1942.png)

Double-clicking one of these files results in the Windows UAC dialog. Running `git-update-index.exe` from the prompt immediately results in the `Permission denied` error.

Is this some hare-brained protection attempt by Windows, trying not to let users run installers or updaters?

/baffled in Switzerland

**Comment by bbolli** [comment]
There's this thing called *Windows Installer Detection Technology* that can be turned off by adding an `AssemblyManifest.xml` file.

http://stackoverflow.com/questions/20096706/how-does-windows-decide-whether-to-display-the-uac-prompt

**Comment by dscho** [comment]
> There's this thing called Windows Installer Detection Technology that can be turned off by adding an AssemblyManifest.xml file.

https://github.com/git-for-windows/git/blob/41980ef55d99e02468fe33cd8beebba3d7cb3be3/git.rc#L24

and

https://github.com/git-for-windows/git/blob/41980ef55d99e02468fe33cd8beebba3d7cb3be3/compat/win32/git.manifest

are intended to provide *just* that.

Please investigate why your Windows thinks it is allowed to ignore this manifest.

**Comment by bbolli** [comment]
It's not ignoring the manifest, it just isn't there in my version -rc5 from July 18. These two commits are from July 28.

**Comment by dscho** [comment]
Oh wow. The manifest should be in there even in -rc1 (the commit 4f980ef is not the one that added the manifest, it just happened to be the state of `master` when I wanted to provide a stable link). I will need to investigate, it seems. So much to do, so little time.

**Comment by dscho** [comment]
Even more curious: when I manually unpack `mingw32/libexec/git-core/git-update-index.exe` from https://github.com/git-for-windows/git/releases/download/v2.4.6.windows.1/PortableGit-2.4.6-5th-release-candidate-32-bit.7z.exe it *has* a manifest, at least if I inspect it with ResEdit.

@bbolli how did you test that said `.exe` has no manifest?

**Comment by bbolli** [comment]
> how did you test that said .exe has no manifest?

I'm sorry for prematurely jumping to conclusions. I inferred it from the different icon and the fact that the UAC prompt appears when double-clicking it. Looking in the EXE, I can find the assembly manifest in front of the VS_VERSION_INFO resource section. Did something change in Windows 10?

**Comment by dscho** [comment]
@bbolli FWIW if you would have built Git for Windows 2.x yourself, using the Git SDK, you would have magically found this bug fixed. It took me yet another 1.5h to figure out why, though: the new version of the default manifest includes a compatibility entry for Windows 10.

**Comment by bbolli** [comment]
Great, thanks!
