### ISSUE TITLE
direnv.exe unable to find stderr (fd 3)

### ISSUE THREAD

**Issue by mcandre** [git-for-windows/git#2581]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.26.0, 64-bit.

 - Which version of Windows are you running?

10.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ direnv reload
```

(My .envrc is blank)

 - What did you expect to occur after running these commands?

direnv is able to perform its functions.

 - What actually happened instead?

direnv threw a message about the fact that it tried to print some messages, but was unable to find a file handle: `3`.

Not sure if this is direnv thing or a Git Bash thing.

**Comment by dscho** [comment]
```sh
$ direnv preload
bash: direnv: command not found
```

Sorry, this report is really too incomplete in its current form.
