### ISSUE TITLE
Version of curl included with Git Bash?

### ISSUE THREAD

**Issue by mcandre** [git-for-windows/git#2582]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Hey, does curl come with Git Bash or another system? I'm trying to diagnose an issue with a build of curl that can't `-2` SSL connections and doesn't provide enough encryption algorithms to connect to many websites.

Perhaps the bigger problem with these old builds of curl is that their exit codes tend to report zero no matter what kind of HTTP response the server sent.

**Comment by dscho** [comment]
Maybe `curl --version` has the answer? I won't, as the report does not even specify the Git for Windows version.
