### ISSUE TITLE
RFE: Please add the option to include the path

### ISSUE THREAD

**Issue by ToddAndMargo** [git-for-windows/git#2584]
Dear Git-for-windows,

Request for Enhancement: would you please consider adding an option to the installer that would add `C:\Program Files\Git\usr\bin` to the Path environmental variable.  And making it the default.

I ask this as it solved this issue with "zef", which depends on "git", not operating in correctly in Windows 7, but operating correctly in Windows 10:

git path psunzip failure in Windows 7, but not 10
https://github.com/ugexe/zef/issues/341

Plus, it is just awfully sweet to be  have access to all the wonderful utilities when operating in the cmd shell.  And guy like me don't have to constantly change ls to dir when they want a directory listing.

Many thanks,
-T

**Comment by PhilipOakley** [comment]
Are you able to do a little bit of investigation and development of the installer (and then possibly a PR pull request) if given some initial pointers as to where to look and what to check for compatibility? (i.e. a bit of time, a little bit of coding, and willingness;-)

**Comment by dscho** [comment]
This option already exists. It's called something like "add Unix tools to the PATH". (I'm on my phone right now, so I cannot say more precisely, but you should see it when reinstalling Git for Windows.)

It will never be the default, though, as e.g. `find.exe` interferes with the Windows tool (that has *totally* different semantics than GNU find) expected by many `.bat` scripts.

**Comment by PhilipOakley** [comment]
@dscho, thanks for the clarification. I'd miss-diagnosed the symptoms from the description. 

If @ToddAndMargo has any suggestions for improving the dialog info to help guide others in their situation then that could be considered.

**Comment by ToddAndMargo** [comment]
Hi Philip,

I went though the installer again and made a screen shot of every single window.  And there it was clear as day.  I must have installed Git 20 times now on various machine -- basically every one I install Raku on.  So, scratching my head, I tried to think of a better way to convey the options, but could not.  I hate to say, but I think the problem is mine.  Thank you all for being so gracious about my mistake.

Anyway, I wrote myself a note on the issue:

> https://git-for-windows.github.io/
> 
> Note: to add git's UNIX (Linux) tools (ls, tar, curl, etc.)
>       to the path:
> 
> 1) inside the installer, on the 
>    --> Adjust your PATH environment (window name at top)
>      --> Use Git and optional Unix tools from the Command
>          Prompt (bottom selection)
> 
> 2) Or, after the fact:
>    --> <win><r> sysdm.cpl
>      --> Advanced (tab at the top)
>       --> Environmental Variables (button, lower right)
>        --> Path, Edit, add to the end
>               ;C:\Program Files\Git\usr\bin
