### ISSUE TITLE
How to uninstall or upgrade to Git 2.26 ?

### ISSUE THREAD

**Issue by paulgureghian** [git-for-windows/git#2587]
I think it was installed as a dependency or something like that for another program I installed via terminal. 

![git](https://user-images.githubusercontent.com/8146561/79159621-43d33f80-7d8d-11ea-901d-5e40a0e8cacc.PNG)
 

64-bit, Windows 10.

**Comment by PhilipOakley** [comment]
The git version 1.9.4.msysgit.2 is now very old and was build differently to the newer v2.26...

Simply pick up the new V2.26 from either the https://gitforwindows.org/ page "Download" button (autodetects your bitness version), or from https://github.com/git-for-windows/git/releases/ where you can choose from a number of options, including the portable and  minimal options.

Having ensured your repos are not under the old msysgit install, I believe you can simply delete it (once you've checked that the new version works as desired).

**Comment by paulgureghian** [comment]
I tried to delete it with Choco and  that didn't work. I forgot exactly how I installed it. 
I do have Git 2.26 in the dedicated Git bash shell for Windows, how to make Git 2.26 available in my other terminals ?

**Comment by dscho** [comment]
Hit the Windows key, the type "Add or Remove Programs", then hit Enter. Git should be in the list

**Comment by paulgureghian** [comment]
I don't want to delete Git, I want to delete msysgit, which I did from the 'add - remove' control panel, but it still shows up in the terminal when I do 'git --version'. 

How to fully remove msysgit ?

**Comment by dscho** [comment]
Find out where it is installed (`git --exec-path`), remove it there, and adjust your global environment variable `PATH`.

**Comment by sokopa** [comment]
Forgive my intervention. I think `Cmder` has an `msysgit` binary in its `vendor\` folder. 

Maybe it picks this up?

**Comment by dscho** [comment]
> I think `Cmder` has an `msysgit` binary in its `vendor\` folder.

That's horrible. There are _so_ many vulnerabilities in the last msysgit, see https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version.

> Maybe it picks this up?

Thanks for chiming in. @paulgureghian is that it?

**Comment by paulgureghian** [comment]
Did  'which git' which showed me that railsinstaller had installed it. deleted rails installer and now git 2.26 is in all my terminals. probably best just to use Ruby / Rails on my Mac / Linux.

**Comment by dscho** [comment]
Good find! Could you report to railsinstaller that they're bundling an unsafe Git?

**Comment by paulgureghian** [comment]
Not just potentially unsafe, but outdated and possibly a point of failure in many ways.

**Comment by dscho** [comment]
Indeed. I wanted to be nice.

**Comment by dscho** [comment]
So from our side this is addressed, I think. @paulgureghian please do open that ticket, still.
