### ISSUE TITLE
Segmentation fault with case sensitive NTFS directory

### ISSUE THREAD

**Issue by berniegp** [git-for-windows/git#2593]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.1.windows.1
cpu: x86_64
built from commit: 14af9f9d205f4a6a033c7b6f48980d1eeee2c610
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.778]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The repo is in a case sensitive NTFS directory.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# The following command sets (in powershell or cmd) the current directory as case sensitive.
# Changing the case sensitivity attribute requires “Write attributes”, “Create files”, “Create folders” and “Delete subfolders and files” permissions on the directory.
# fsutil file setCaseSensitiveInfo . enable

git init

# Upper-case file with 1 byte
printf "A" > A

# Lower-case file with 1 byte
printf "a" > a

# Works (well... at least no errors)
git add .
git rm --cached -f *

# Lower-case file <= 32KB
printf "aa" > a
git add .
# Command output:
# error: short read while indexing A
# error: A: failed to insert into database
# error: unable to index file 'A'
# fatal: adding files failed

# Lower-case file > 32KB
printf "%-32769s" "" > a
git add .
# Command output:
# Segmentation fault

rm .git/index.lock

# Upper-case empty file (and lower-case file > 32KB)
printf "" > A
git add .
# Command output:
# fatal: mmap failed: Invalid argument
```
 - What did you expect to occur after running these commands?

Correctly track files with filenames that differ only by case

 - What actually happened instead?

See above

**Comment by rimrul** [comment]
Since this issue is partially about filenames that differ only in case, what's the output of 
`git config core.ignorecase`?

**Comment by berniegp** [comment]
`core.ignorecase` is not set.

I tried setting it to `true` which causes the first `git add` to fail with
`fatal: will not add file alias 'a' ('A' already exists in index)`

**Comment by dscho** [comment]
>  `fatal: will not add file alias 'a' ('A' already exists in index)`

That error message is produced here: https://github.com/git-for-windows/git/blob/v2.26.2.windows.1/read-cache.c#L680-L681. That function has but a single caller: https://github.com/git-for-windows/git/blob/v2.26.2.windows.1/read-cache.c#L781. And that call is guarded by `if (ignore_case && ...)`. The default value of `ignore_case` is `0`: https://github.com/git-for-windows/git/blob/v2.26.2.windows.1/environment.c#L26 (global variables are implicitly initialized to all-zero unless defined to a different value _explicitly_). The only place where `ignore_case` is assigned is here: https://github.com/git-for-windows/git/blob/v2.26.2.windows.1/config.c#L1159-L1162.

So `core.ignorecase` is set to `true` somewhere.

**Comment by berniegp** [comment]
@dscho I'm not sure I follow. What you say seems to match what I reported in my previous comment.

To restate:
 - I *only* get `fatal: will not add file alias 'a' ('A' already exists in index)` when I set `core.ignorecase` to `true`.
 - When it's *not* set, I get the results shown in my original report.

**Comment by dscho** [comment]
Sorry, I only read the last comment and misunderstood that you get that error _without_ setting `core.ignoreCase`.

**Comment by dscho** [comment]
Closing as stale.
