### ISSUE TITLE
Python thinks stdin not connected to a TTY

### ISSUE THREAD

**Issue by jakubroztocil** [git-for-windows/git#2594]
Python running inside Git Bash incorrectly thinks that `stdin` is not connected to a TTY:
```bash
$ python3 -c 'import sys; print(sys.stdin.isatty())'
False  # Should be True
```

https://github.com/jakubroztocil/httpie/issues/828

https://docs.python.org/3/library/os.html?highlight=isatty#os.isatty

**Comment by dscho** [comment]
This issue is listed specifically in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]

**Comment by jakubroztocil** [comment]
@dscho thank you for the explanation
