### ISSUE TITLE
git-send-email fails - some perl issue

### ISSUE THREAD

**Issue by shuffle2** [git-for-windows/git#2598]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

(maybe it's a recurrence of this: https://github.com/git-for-windows/git/issues/1480 - package version mismatching?)
edit: trying the diag step mentioned in #1480:
```
$ perl -e "require IO::Socket::SSL;"
Can't load '/usr/lib/perl5/vendor_perl/auto/Net/SSLeay/SSLeay.dll' for module Net::SSLeay: No such file or directory at /usr/lib/perl5/core_perl/DynaLoader.pm line 193.
  at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 19.
Compilation failed in require at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 19.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 19.
Compilation failed in require at -e line 1.
```
Continuing in this vein, my `C:\Program Files\Git\usr\lib\perl5\vendor_perl\auto\Net\SSLeay\SSLeay.dll`
is importing `msys-crypto-1.0.0` and `msys-ssl-1.0.0` . meanwhile I only have:
```
/usr/bin/msys-crypto-1.1.dll
/usr/bin/msys-ssl-1.1.dll
```
in git's msys env.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.778]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
.gitconfig:
[sendemail]
        smtpEncryption = tls
        smtpServer = smtp.gmail.com
        smtpUser = <me>@gmail.com
        smtpServerPort = 587
...
git send-email ...
```
 - What did you expect to occur after running these commands?

email to be sent via gmail

 - What actually happened instead?

```
Not using SSL_VERIFY_PEER due to out-of-date IO::Socket::SSL.
To use SSL please install IO::Socket::SSL with version>=2.007 at /usr/share/perl5/core_perl/Net/SMTP.pm line 270, <FIN> line 1.
```
Note, the same .gitconfig and git-send-email invocation does work from WSL (using ubuntu's git).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by shuffle2** [comment]
For others hitting the problem:
I've done the recommended from #1480 : copied msys-ssl-1.0.0 and msys-crypto-1.0.0 from https://github.com/git-for-windows/git/releases/download/v2.22.0-rc2.windows.1/PortableGit-2.22.0.rc2.windows.1-64-bit.7z.exe /usr/bin and put into git's /usr/bin . 

I'll leave this issue open to track it since it still applies to current releases.

**Comment by dscho** [comment]
I guess `IO::Socket::SSL` needs to be recompiled?

**Comment by dscho** [comment]
@shuffle2 would you mind re-testing with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by dscho** [comment]
Hmm. I hoped for a little more help. As it is, I fixed it locally, and it will come your way with the next release and/or snapshot.

**Comment by corthon** [comment]
@dscho, I can confirm that the latest snapshot seems to work.

**Comment by dscho** [comment]
Great!
