### ISSUE TITLE
Core dump with `LC_ALL=C grep ...`

### ISSUE THREAD

**Issue by mjunix** [git-for-windows/git#2599]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.815]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

"Git Bash"

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ mkdir foo
$ LC_ALL=C grep -Fri 'xyz' foo/
Aborted (core dumped)
```
 - What did you expect to occur after running these commands?

Not crash.

 - What actually happened instead?

Crash (Core dump).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No.

**Comment by dscho** [comment]
Is this happening 

> $ mkdir foo
> $ LC_ALL=C grep -Fri 'xyz' foo/
> Aborted (core dumped)

I can reproduce that.

The big question now is: does this also happen in a vanilla [MSYS2](https://msys2.github.io/)?

**Comment by zufuliu** [comment]
none of the three shells (MSYS, MINGW32, MINGW64) crashed with above commands.

**Comment by dscho** [comment]
Can you try again after copying `usr/bin/msys-2.0.dll` from MSYS2 to, say, a portable Git?

**Comment by zufuliu** [comment]
After replace msys-2.0.dll with the one from PortableGit-2.26.2-64-bit.7z.exe,  it prints "Aborted (core dumped)".
The working (latest) one from msys2 is in msys2-runtime-3.0.7-6-x86_64.pkg.tar.xz  (2019-07-11)
but I see msys2-runtime 3.0.7-4 in PortableGit-2.26.2-64-bit.7z\etc\package-versions.txt

**Comment by zufuliu** [comment]
PS. mintty is also outdated, 1\~3.1.0-1 in PortableGit, 1\~3.1.4-1 (2020-03-02) in msys2.

**Comment by dscho** [comment]
The version numbers of msys2-runtime are slightly misleading, as Git for Windows adds its own patches.

Would you have time to build it yourself and bisect? https://github.com/git-for-windows/git/wiki/Building-msys2-runtime has instructions how to do that.

https://github.com/git-for-windows/msys2-runtime/commit/ed55281ae85ef4dc1d4e4fad90b46ca2b19869ec should be pretty equivalent to MSYS2's tip commit.

**Comment by dscho** [comment]
BTW thank you for pointing out that MinTTY is lagging behind in Git for Windows. I ran the automated build that updated it: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=54783&view=artifacts&type=publishedArtifacts

**Comment by zufuliu** [comment]
@dscho Sorry, I'm afraid I currently don't have time to build and test msys2-runtime.

**Comment by dscho** [comment]
Yeah, me, neither. At least you have some guidance now, should this issue become urgent.

**Comment by zufuliu** [comment]
msys2-runtime 3.1.4-1 built from `git-sdk-64\usr\src\MSYS2-packages\msys2-runtime\pkg\msys2-runtime\usr` still not works.

**Comment by dscho** [comment]
Thank you for testing.

For the record: I am not going to prioritize working on this myself, as it does not seem to affect Git itself.

**Comment by dscho** [comment]
Closing as stale.
