### ISSUE TITLE
'Stacking' on the windows taskbar mixing in with 'normal' cmd.com prompts.

### ISSUE THREAD

**Issue by ciaranj** [git-for-windows/git#260]
GitForWindows (cmd.com mode) 'stacks' in with 'other' cmd.com windows on the windows taskbar (on server 2012 but happens across all windows that support the stackable tab thingies.)

Is this 'just the way it hast to be' now?, or is it something someone could point me in the direction of looking at how to fix it :/   I did try hunting around google to see how windows determines what windows should be stacked and which shouldn't but failed to find anything definitive (my initial guess would've been by process name but that appears not to be the case!)

**Comment by elieux** [comment]
There's an ID associated to every taskbar icon and to every process. Matching ID's get grouped together. The ID is usually determined automatically by Windows (from the process name, executable path and/or other factors), but can be programatically set under some conditions.

I'm not sure if it's possible to change this ID for a Command Prompt window, but I just tested an Azure SDK cmd window and it seems to somehow not group with other cmd windows, so I'm hopeful.

Use [Taskbar Inspector](http://rammichael.com/7-taskbar-tweaker) to look at the ID's.

**Comment by ciaranj** [comment]
Yeah, so git-bash (my pinned icon) gets one guid (cut'n'paste from taskbar inspector does not work sadly), all the git-bash launched command windows get a different (but shared amongst themselves) guid, and visual studio command prompts get another (but also shared amongst themselves guid).. I'll take a look at how visual studio prompts get launched to see if I can find a clue there.

**Comment by ciaranj** [comment]
right, so this https://msdn.microsoft.com/en-us/library/dd378459(VS.85).aspx is what I needed to know previously ;)

**Comment by ciaranj** [comment]
Best guess is we should? Call https://msdn.microsoft.com/en-us/library/dd378422(v=vs.85).aspx (SetCurrentProcessExplicitAppUserModelID ) in this scenario .. I'm going to try (again) to get the git sdk working for me locally

**Comment by ciaranj** [comment]
Hmm, sidenote, I fear I may have duped a closed bug #248

**Comment by ciaranj** [comment]
*sigh* once again I've failed.  The new SDK installer works a treat (yay!) and I was able to patch 'git-wrapper.c' and make install it, then I was able to checkout build-extra and create an installer (that worked, double yay!) 

However I'm completely unsure if my change has made it into git-bash.exe.  I can't see where git-wrapper.exe 'changes/evolves/relates-to' git-bash.exe ..  :(

**Comment by nalla** [comment]
It is part of the `mingw-w64-git` package. There in the `PKGBUILD` `git-bash.exe` is getting compiled and installed into the package.

That package is then being picked up by the installer.

So if you overwrite the `git-bash.exe` in the appropriate locations, you should be fine.

**Comment by ciaranj** [comment]
I'm not sure I explained myself well :/   If I want to change the git-bash.exe and test those changes, is it sufficient for me to edit git-wrapper.c  then do a make install, then make an installer, then use the installer (ideally is there a less circuitous set of steps I can follow ? :)

**Comment by nalla** [comment]
To answer you question: No, it is not sufficient.

If - however - you follow my instructions roughly outlined in my previous commit. Especially that part about compiling and replacing the `git-bash.exe` and `git-cmd.exe` you can archive what you want.

```bash
$ cd /usr/src/MINGW-packages/mingw-w64-git
$ windres -O coff git-bash.rc -o git-bash.res
$ gcc -mwindows -s -O2 -Wall -o git-bash.exe git-bash.res ../../git/compat/win32/git-wrapper.o ../../git/git.res -lshlwapi
$ cp git-bash.exe /
```

**Comment by ciaranj** [comment]
thank you, that's what I needed to know :)

**Comment by ciaranj** [comment]
However, now I'm doubly confused.  When I use the approach outlined above I end up with a git-bash.exe that is 136Kb (as opposed to the 28Kb exe I get from the installer)... and it appears to stack separately from the common.com windows ?!?!

**Comment by dscho** [comment]
@ciaranj the package contains stripped binaries. Not what you want for debugging.

**Comment by dscho** [comment]
After working on https://github.com/git-for-windows/git/issues/263 for a substantial amount of time, I am convinced that this ticket will be addressed by said ticket. As things have progressed further than here in the other ticket, I close this one.

**Comment by ciaranj** [comment]
Seems likely, I'd completely missed #167 (only skimmed the title I guess) this is clearly a dupe of that (and of #263) sorry :(

**Comment by dscho** [comment]
@ciaranj there is no need to be sorry. The good news is that it looks like this issue will be finally addressed soon!
