### ISSUE TITLE
git gui startup script error

### ISSUE THREAD

**Issue by podsvirov** [git-for-windows/git#2600]
The `git gui` command perfectly startup on `Windows`, but not from appropriate `MSYS2` shell.

![git-gui-from-msys2-vs-for-windows](https://user-images.githubusercontent.com/8400779/80281924-3451e000-8717-11ea-8a95-f9e3be1d11f3.png)

I have already suggested a possible solution. I am looking for support to promote this solution.

For more info see:

https://github.com/msys2/MSYS2-packages/pull/1912

https://github.com/gitgitgadget/git/pull/612

**Comment by dscho** [comment]
You probably want to prod @prati0100 (the Git GUI maintainer, it's their call whether to accept it or to ask for changes or to reject it) in a reply to https://lore.kernel.org/git/pull.612.git.1586900734341.gitgitgadget@gmail.com/.

**Comment by prati0100** [comment]
@podsvirov sorry, it has been lying in my to-do list for a while. Will review as soon as I can find some time.

**Comment by podsvirov** [comment]
> @podsvirov sorry, it has been lying in my to-do list for a while. Will review as soon as I can find some time.

@prati0100 thanks for the answer, this is better than silence - now I know that I am not alone with this problem.
