### ISSUE TITLE
.gitignore in parent folder seems not considered

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [git-for-windows/git#2602]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

`.gitignore` file located in `projects` folder seems ignored when working with repo at `projects\repo`

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.153]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

test.bat that should be placed in a folder or set of commands to execute except first one:
```
@ECHO OFF

md repo
cd repo
git init
echo hi > txt.txt
git status
cd ..
echo *.txt > .gitignore
cd repo
git status
echo *.txt > .gitignore
git status

```
 - What did you expect to occur after running these commands?

Expect output of 2nd `git status` with no files

 - What actually happened instead?

`txt.txt` still not ignored

```
No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        txt.txt

nothing added to commit but untracked files present (use "git add" to track)
On branch master
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** no **

**Comment by dscho** [comment]
That `.gitignore` is outside of the worktree. Git is not designed to respect such a file.

**Comment by Fr0sT-Brutal** [comment]
@dscho ah damn sure you're right. I overlooked "(up to the toplevel of the work tree)" in https://git-scm.com/docs/gitignore. My fault.

**Comment by dscho** [comment]
I'm glad I could help :-)
