### ISSUE TITLE
Ctrl-c can't kill gradlew process

### ISSUE THREAD

**Issue by hojongs** [git-for-windows/git#2603]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git for windows v2.26.2 (sorry I uninstalled it already, but it was latest release version at now)
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.778]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
./gradlew bootRun

... wait for completion bootRun task

Ctrl-c

```
 - What did you expect to occur after running these commands?

kill process

 - What actually happened instead?

nothing happen
Although I kill git-bash process, the `./gradlew bootRun` process is not killed
But, It is working fine with below version
```
git version 2.25.1.windows.1
cpu: i686
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 4
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by dscho** [comment]
I can't really search right now, but I am sure that there are very similar reports. And a not-so-WIP PR at https://github.com/git-for-windows/msys2-runtime/pulls. If you have time to work on it, that's much appreciated (I don't, but then, the issue does not affect me personally).

**Comment by hojongs** [comment]
Maybe it is duplicated by #2592

**Comment by dscho** [comment]
Among others, yes. And https://github.com/git-for-windows/git/issues/2592#issuecomment-616324751 will guide you further.
