### ISSUE TITLE
Git for Windows updater performs an automatic restart without confirmation

### ISSUE THREAD

**Issue by antidamage** [git-for-windows/git#2604]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

$ git --version --build-options
git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.778]

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Used previously set options, "only show new options" was selected, no options changed.

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

None of those locations exist.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Pretty much default Git config.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Standard Git for Windows updater. It performed the update and restarted without prompting. It should definitely prompt before doing this.

**Comment by rimrul** [comment]
I'm pretty certain it does not reboot without asking for confirmation. Could you please check the event log for reboot event messages?

**Comment by qhill** [comment]
It appeared to do this for me too yesterday.

**Comment by rimrul** [comment]
You're actually correct.

As of git-forwindows/build-extra@e119d03 we pass `/VERYSILENT` to the installer without `/NORESTART`. That's not ideal.

**Comment by dscho** [comment]
> As of [git-for-windows/build-extra@e119d03](https://github.com/git-for-windows/build-extra/commit/e119d03) we pass `/VERYSILENT` to the installer without `/NORESTART`. That's not ideal.

Whoa! I'll fix this right away.

**Comment by dscho** [comment]
The next [snapshot](https://wingit.blob.core.windows.net/files/index.html) will have this fix.

Please note that it matters _only_ (at least as far as _I_ can tell) when the files Git for Windows' installer wants to overwrite or delete are still in use.

This could be a background job such as the GPG agent, of course...

**Comment by antidamage** [comment]
The problem still exists, it just did it again with the latest update with the default installer selections.

**Comment by rimrul** [comment]
If you updated from a 2.26.x release, you've just got the fixed updater with this update. The reboot is caused by the version you're upgrading from.

**Comment by dscho** [comment]
@antidamage sorry for the trouble; I think @rimrul's analysis is spot on, and there was simply no way we could fix the script, not without an upgrade, the same upgrade which of course triggers the very same bug _again_.

Please note that this was likely due to the script being run while a process was still using Git for Windows' files (e.g. a Git Bash). This is really unfortunate, but as I said, I do not know that we had any way to fix this without triggering the bug just once more (except by strongly suggesting to close all Git for Windows processes before upgrading; I could have done a better job trying to communicate that).
