### ISSUE TITLE
dns suffix not added automatically

### ISSUE THREAD

**Issue by lefebvresam** [git-for-windows/git#2607]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64bit

```
$ git --version --build-options

git version 2.11.0
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1158]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using a DHCP server that issues a dns suffix, named 'lan'.
I also use a DNS server that resolves host names, like ds216.lan.
In windows console I don't need to type the suffix 'lan', because it is known as default:
```
C:\Windows\System32>nslookup ds216
Server:  UnKnown
Address:  192.168.2.2

Name:    ds216.lan
Address:  192.168.2.2
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

both bash and cmd, the issue is the same in both terminals.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Sam Lefebvre@DESKTOP-14FHLC1 MINGW64 ~
$ ssh admin@ds216
ssh: connect to host ds216 port 22: Connection refused

Sam Lefebvre@DESKTOP-14FHLC1 MINGW64 ~
$ ssh admin@ds216.lan
admin@ds216:~$ exit
logout
Connection to ds216.lan closed.

Sam Lefebvre@DESKTOP-14FHLC1 MINGW64 ~
$ ssh tf@red-brick
Linux red-brick 4.13.0-red-brick-1 #1 Mon Dec 2 17:53:04 CET 2019 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Apr 30 14:48:36 2020 from 192.168.2.120
tf@red-brick:~$ exit
logout
Connection to red-brick closed.

Sam Lefebvre@DESKTOP-14FHLC1 MINGW64 ~
```
 - What did you expect to occur after running these commands?

I expect that 'ssh admin@ds216' is working just like 'ssh tf@red-brick'

 - What actually happened instead?

Connection refused. In order to login, you must use 'ssh admin@ds216.lan'.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

NA

**Comment by dscho** [comment]
I suspect that OpenSSH expects this information to be present in `/etc/resolv.conf`, as Git for Windows uses an MSYS2 version of OpenSSH, which in general means that the software expects more or less a working Linux environment. However, I am fairly certain that this usage is not supported in the MSYS2 environment...

You should be able to verify or refute my suspicion by editing (as administrator!) the `/etc/resolv.conf` file (e.g. by running Git Bash as an administrator, then calling `git config -ef /etc/resolv.conf`) adding the line `search lan` and then trying again.

**Comment by lefebvresam** [comment]
Now the problem stays exactly the same. However I cannot find a resolv.conf file in the GIT folder, even after adding the line with the command you propose. Strange that for other hosts it works (like red-brick).

**Comment by rimrul** [comment]
Our OpenSSH seems to ignore resolv.conf. It's apparently smart enough to not use the unix behaviour, but not smart enough to use the corresponding windows behaviour instead. 

You could try to use OpenSSH hostname canonicalisation instead.

**Comment by lefebvresam** [comment]
When I create a file <user folder>\.ssh\config with this content, it works:
CanonicalizeHostname yes
CanonicalDomains lan
CanonicalizeMaxDots 0
CanonicalizeFallbackLocal no

**Comment by dscho** [comment]
Good find!

Having said that, where does that leave us? There seems not to be any way to update this via DHCP, right?

**Comment by rimrul** [comment]
From my perspective that leaves us with a slightly unsatisfying work-around, but the alternative would be a lot of digging around in OpenSSH and MSys2 name resolution code.

**Comment by lefebvresam** [comment]
Yes DHCP is configured to provide the default domain suffix for each interface which gets an IP address, but when a tool on a host is using a different context like OpenSSH you can have unexpected behavior.

**Comment by dscho** [comment]
Thanks for your thoughts and for working through this topic. I guess it is closing time?
