### ISSUE TITLE
duplicated filename - short and long filename (and upper/lower case)

### ISSUE THREAD

**Issue by JoseQuintas** [git-for-windows/git#261]
today I change a file called ze_xmlfun.prg
In change list there are 2 files: ze_xmlfun.prg and ze_xml~1.prg
I rename it to x, load git ok, no ze_xml*.prg in change list.
But when rename to ze_xmlfun.prg, again 2 files in change list.
If possible ignore upper/lower could be usefull in Windows too.
Windows 7 64 bits.

**Comment by dscho** [comment]
> today I change a file called ze_xmlfun.prg
> In change list there are 2 files: ze_xmlfun.prg and ze_xml~1.prg
> I rename it to x, load git ok, no ze_xml*.prg in change list.

You need to tell Git to stop tracking ze_xml~1.prg:

```bash
git rm --cached ze_xml~1.prg
```

Please note that up-to-date Git for Windows will display an error if such a file name is used.

> If possible ignore upper/lower could be usefull in Windows too.

There is no such option, neither in Windows nor in Git.

**Comment by JoseQuintas** [comment]
Thanks.
Information about git rm and git mv can help me to do anything.
