### ISSUE TITLE
Bundled gnupg (gpg) can't even create a key

### ISSUE THREAD

**Issue by jb-wisemo** [git-for-windows/git#2610]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
   (Some were similar but not as fundamental
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Network %HOMEDRIVE%%HOMEPATH% is shared with other machines, %USERPROFILE% is not, the bundled MSYS2 chooses wrong, but left as is for now.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Tried with basic CMD and with git-bash, details here are from git-bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
gpg --generate-key
```
 - What did you expect to occur after running these commands?

gpg key generated for signing commits...

 - What actually happened instead?

git bundled gpg failed to launch its own gpg-agent, no other gpg on machine and git-win appears to support nothing else

Output:
gpg (GnuPG) 2.2.20-unknown; Copyright (C) 2020 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: DBG: locking for '/u//.gnupg/pubring.kbx.lock' done via O_EXCL
Note: Use "gpg --full-generate-key" for a full featured key generation dialog.

GnuPG needs to construct a user ID to identify your key.

Real name: Test Testesen
Email address: test@example.com
You selected this USER-ID:
    "Test Testesen <test@example.com>"

Change (N)ame, (E)mail, or (O)kay/(Q)uit? o
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: DBG: locking for '/u//.gnupg/gnupg_spawn_agent_sentinel.lock' done via O_EX
CL
gpg: can't connect to the agent: IPC connect call failed
gpg: agent_genkey failed: No agent running
Key generation failed: No agent running

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No repository present, this happens before even using one

**Comment by PhilipOakley** [comment]
> Network %HOMEDRIVE%%HOMEPATH% is shared with other machines, %USERPROFILE% is not, the bundled MSYS2 chooses wrong, but left as is for now.

Hmm, most corporate networks I've seen tend to have the %HOMEPATH% specific to the user. Is that not the case for your network (just confirming)? GPG is not my area, but just wanted to check on that detail.

**Comment by dscho** [comment]
I cannot reproduce the problem: it works here. But then, I do not use a network path as home directory. See the log here:

```
$ gpg --generate-key
gpg (GnuPG) 2.2.20-unknown; Copyright (C) 2020 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Note: Use "gpg --full-generate-key" for a full featured key generation dialog.

GnuPG needs to construct a user ID to identify your key.

Real name: Test Testesen
Email address: test@example.com
You selected this USER-ID:
    "Test Testesen <test@example.com>"

Change (N)ame, (E)mail, or (O)kay/(Q)uit? o
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: key C53A21E5832FBF6E marked as ultimately trusted
gpg: directory '/c/Users/me/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/c/Users/me/.gnupg/openpgp-revocs.d/9A38F950438F79934AB9A398C53A21E5832FBF6E.rev'
public and secret key created and signed.

pub   rsa2048 2020-05-04 [SC] [expires: 2022-05-04]
      9A38F950438F79934AB9A398C53A21E5832FBF6E
uid                      Test Testesen <test@example.com>
sub   rsa2048 2020-05-04 [E] [expires: 2022-05-04]
```

Note: at some stage after I hit <kbd>o</kbd> to say that the ID was okay, I got a pop-up to enter a passphrase, followed by another pop-up to re-enter the passphrase. I captured only the second one:

![image](https://user-images.githubusercontent.com/127790/80964568-6ba84700-8e11-11ea-867e-24a65388c23e.png)

Now, you should be able to verify if the issue is indeed the network drive, simply by running `gpg --homedir "$USERPROFILE" --generate-key`.

**Comment by mfriedrich74** [comment]
"%HOMEDRIVE%%HOMEPATH% is shared with other machines" and "specific for a
user" are not mutual exclusive. Can both be true and usually is in my
experience. It could even be shared between Linux and Windows.

**Comment by dscho** [comment]
> "%HOMEDRIVE%%HOMEPATH% is shared with other machines" and "specific for a user" are not mutual exclusive. Can both be true and usually is in my experience. It could even be shared between Linux and Windows.

Sure, and you're prone to run into performance issues, and line ending issues, among other things. I'd recommend against that.

**Comment by jb-wisemo** [comment]
Yep, my %HOMEDRIVE%%HOMEPATH% is per user but on a SAMBA server.  It is also the Linux home directory when working locally on that server (but not when working locally on other Linux machines).

For anyone actually knowing Windows, this is the intended use of the HOMEDRIVE and HOMEPATH variables: The user personal workspace on a file server, NOT the location for configuration and local files.  Those things belong in the Profile directory, usually pointed to by the USERPROFILE variable, but ultimately available via dedicated API calls.  This is where the per user Registry, personal start menu entries, "My Documents" directory etc. are located.  It even has a dedicated subdirectory for dotfiles, usually pointed to by the APPDATA variable (again with dedicated API calls to get the location).

I have long since configured cygwin to use the profile directory (instead of a parallel subdir under cygwin/home), and that works beautifully on lots of machines.

I have since tried to put the correct location in the git/etc/nsswitch.conf file and the "Git Bash.lnk" shortcut, but git-bash.exe keeps forcing the wrong value.  Globally setting the unix style HOME variable in Windows could interfere with other software.

**Comment by dscho** [comment]
Okay, so you really want to make this setup work.

To do so, you most likely want to do two things:

1. Figure out why the locking does not work as intended when accessing your Linux home directory via Samba.

2. Provide a PR to allow overriding Git for Windows' idea of your home directory in the installer, persisting the choice between upgrades.

For 1. I would recommend looking in OpenSSH's source code to find out what the exact flags are when opening the lock file, then write a very simple example `.c` file to replicate it quicker, then debug into the MSYS2 runtime via `strace`, `gdb` and/or debug print statements.

For 2. my recommendation is to modify `installer/install.iss` in our build-extra repository, following the example of the free-form custom editor. You will need to find a good spot for the new option, of course.

**Comment by jb-wisemo** [comment]
Clarifications:
For 1. Why OpenSSH?, no OpenSSH code was used in the reproduction.

For 2. What could the installer possibly do if the installed binaries lack the ability to change the default?  To me it looks more like a something is broken in the MSYS2 libraries.

**Comment by dscho** [comment]
Sorry, my mind was still on another issue that revolves around OpenSSH. However, you're most likely smart enough to have realized that I meant GPG's source code.

As to the installer: it could perform those `nsswitch.conf` edits you make manually. That would probably be more effective than those manual edits.

**Comment by jb-wisemo** [comment]
Note that my nsswitch.conf edits seemed to have no effect when tested, HOME is still forced to point to HOMEDRIVE, not the value in nsswitch.conf.  Even after a reboot.
Either the value isn't read, or the code silently discards it for some reason and falls back to a hardcoded setting.

**Comment by dscho** [comment]
> Note that my nsswitch.conf edits seemed to have no effect when tested, HOME is still forced to point to HOMEDRIVE, not the value in nsswitch.conf.

A better idea might be to simply set `HOME` in your user environment as described in https://www.techjunkie.com/environment-variables-windows-10/.

**Comment by dscho** [comment]
Closing as stale.
