### ISSUE TITLE
Git Bash window (mintty?) freezes after Ctrl+C and Terminate batch job. "MSYS2 terminal is not responding"

### ISSUE THREAD

**Issue by lolmaus** [git-for-windows/git#2611]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

# Setup

### Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options
git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

### Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Pro Eng 64-bit

Version	10.0.18363 Build 18363

```
$ cmd.exe -c ver
Microsoft Windows [Version 10.0.18363.778]
(c) 2019 Microsoft Corporation. All rights reserved.
```

### What options did you set as part of the installation? Or did you choose the defaults?

Probably defaults.

```
type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Any other interesting things about your environment that might be related to the issue you're seeing?

Not really. I use ssh-agent, but it's unlikely to be related.

# Details

### Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash via `C:\Program Files\Git\git-bash.exe`.

### What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

The problem is that when I stop a Node-driven dev server with <kbd>Ctrl</kbd>+<kbd>C</kbd>, the Git Bash terminal prompts `Terminate batch job?` and then freezes. I need to kill it with Task Manager and start a new one.

Unfortunately, I cannot provide a minimal reproduction. :pensive: It only happens with larger projects.

I've also seen it freeze after <kbd>Ctrl</kbd>+<kbd>C</kbd>-ing (and `Terminate batch job?`) from other executables, such as Yarn.

Since it does not happen with a greenfield codebase, I assume something within the codebase is to blame. But regardless of the executable behavior, I believe the terminal window should not be freeezing.

Also, when the freeze happens, the Process Explorer shows that `git-bash.exe` has no child processes other than `mintty.exe`.

### If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing?

https://github.com/kaliber5/ember-cli-yadda-opinionated

```
git clone https://github.com/kaliber5/ember-cli-yadda-opinionated.git
cd ember-cli-yadda-opinionated
yarn
```

Then after some time into [Yarn](https://yarnpkg.com/) installing dependencies, press <kbd>Ctrl</kbd>+<kbd>C</kbd>, then confirm `Terminate batch job?` with `y`.

The terminal window freezes.

**Comment by rimrul** [comment]
Could you test `winpty yarn` instead of `yarn` in your last example?

**Comment by lolmaus** [comment]
@rimrul, when prefixed with `winpty` and canceled with <kbd>Ctrl</kbd>+<kbd>C</kbd>, the `Terminate batch job?` prompt does not appear and the terminal window does not freeze. 👍

**Comment by dscho** [comment]
So I think that this is covered by  our [Release Notes' "Known Issues" section](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The good news is that there _is_ some work under way to address this: we upgraded our MSYS2 runtime to benefit from Cygwin's recent work to support Windows' native pseudo terminals. The support is not yet without flaws, but it does address the problem with `yarn`. The next [snapshot](https://wingit.blob.core.windows.net/files/index.html) will have it, and I would like to encourage you, @lolmaus, to check it out.

**Comment by lolmaus** [comment]
@dscho, I've tried the following [snapshot](https://wingit.blob.core.windows.net/files/index.html):

> Sat, 9 May 2020 21:24:56 +0200
> (commit 46ad3fc87ad315c4eb557630a375b919c7a81f06)

With that snapshot and without `winpty`, <kbd>Ctrl</kbd>+<kbd>C</kbd> still sometimes yields a prompt `Terminate batch job (Y/N)?`

**But it appears already confirmed, and the terminal no longer freezes**.

🙇

**Comment by lolmaus** [comment]
Nope, it just froze for me again.

The terminal window did not go full "This process is not responding, wait or close?"

But the `Terminate batch job (Y/N)?` prompt was blinking and was not responding to <kbd>y</kbd> or <kbd>Enter</kbd> or <kbd>Ctrl</kbd>+<kbd>C</kbd>anything else.

**Comment by dscho** [comment]
Closing as stale.
