### ISSUE TITLE
Package contrib directory including diff-highlight

### ISSUE THREAD

**Issue by nkcfan** [git-for-windows/git#2612]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19041.208]
(c) 2020 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

My ~/.gitconfig is shared between Windows and Ubuntu/Debian servers. Linux version works fine. But the contrib directory is missing on windows git installation.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ cat .gitconfig | grep -A 3 pager
[pager]
    show = perl /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less
    log = perl /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less
    diff = perl /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less
$ git diff
```
 - What did you expect to occur after running these commands?

Normal diff with diff-highlight enabled

 - What actually happened instead?
```
$ git diff
Can't open perl script "/usr/share/doc/git/contrib/diff-highlight/diff-highlight": No such file or directory
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Any repo

**Comment by dscho** [comment]
> My ~/.gitconfig is shared between Windows and Ubuntu/Debian servers. Linux version works fine. But the contrib directory is missing on windows git installation.

@nkcfan The fact that the Ubuntu/Debian packages choose to include this not-quite-maintained `contrib` script does not mean that you can rely on it being present in _every_ Git distribution.

Having said that, if you work on a PR to include this (you would probably append this after [the wincred part](https://github.com/git-for-windows/MINGW-packages/blob/faf74a867a5bdaa6cfe4c2c830f566e4c0dfd1d3/mingw-w64-git/PKGBUILD#L197-L198)) and test it, I'd be happy to merge it.

**Comment by dscho** [comment]
Closing as stale.
