### ISSUE TITLE
New version of mintty?

### ISSUE THREAD

**Issue by Alpengreis** [git-for-windows/git#2613]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.815]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

Since few versions I receive in the options always the message that a new version of mintty is available - see here ...

![mintty](https://user-images.githubusercontent.com/11355601/81216761-bc6b9b80-8fdb-11ea-9172-6a7195117204.PNG)

So it would be interesting for me to know why is this not yet included ...

thank you in advance and thank you for your work!

Greetings

**Comment by rimrul** [comment]
Our MinTTY package [was updated 11 days ago](https://github.com/git-for-windows/MSYS2-packages/commit/5ba071d) from 3.1.0 to 3.1.4. The [last Git for Windows release](https://github.com/git-for-windows/git/releases/latest) was released 17 days ago, so it didn't include that update yet. The next release (probably in early June) will include MinTTY 3.1.4. In fact, the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) already includes MinTTY 3.1.4.
