### ISSUE TITLE
.gitattributes does not convert line endings for specific file type

### ISSUE THREAD

**Issue by ChristianWalch** [git-for-windows/git#2614]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.815]
(c) 2019 Microsoft Corporation. Alle Rechte vorbehalten.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

-> global gitconfig: no matter if autocrlf = true or false
-> local repo config: no core.eol set
-> gitattributes in repo:
   text=auto
   *.sh text eol=lf

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add --renormalize .
git commit -m "..."
git push
```
 - What did you expect to occur after running these commands?

all text files with line ending CRLF, except .sh files having LF

 - What actually happened instead?

all files have line endings CRLF

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

git clone https://ChristianW@bitbucket.org/ChristianW/test_repo.git

- Further information can be found here:

https://stackoverflow.com/questions/61609174/git-check-out-a-specific-file-type-with-lf-line-endings-on-windows

**Comment by dscho** [comment]
I don't think that `--renormalize` intends to rewrite _worktree_ files (nor do I think that the documentation says so).

You should be able to work around it using

```sh
find -name \*.sh -exec touch {} \;
git stash
```

**Comment by tboegi** [comment]
To acknowlegde the comment from @dscho:
`git add`
does never change files in the working tree.
You can delete them, and check them out again:
rm *.sh
git checkout *.sh

(And there is a small bug in the test repo:)

git ls-files --eol
i/lf    w/lf    attr/text=auto eol=crlf .gitattributes
i/none  w/none  attr/text=auto eol=crlf .gitignore
i/lf    w/lf    attr/text=auto eol=crlf file1.txt
i/lf    w/lf    attr/text=auto eol=crlf file2.txt
i/lf    w/lf    attr/text=auto eol=crlf file3.txt
i/none  w/none  attr/text=auto eol=crlf libs/lib1.txt
i/lf    w/lf    attr/text eol=lf        test.sh
i/lf    w/lf    attr/text eol=lf        test_A.sh

**Comment by ChristianWalch** [comment]
sorry - my bad
tried with another test repo, in which this is working just fine
(https://ChristianW@bitbucket.org/ChristianW/test_gitattributes.git),
