### ISSUE TITLE
[bug] NPM commands don't do anything and cause prompt to stop echoing commands

### ISSUE THREAD

**Issue by itunbridgedev** [git-for-windows/git#2615]
### Setup

v. 2.26.2 (64-Bit)

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

Windows v10

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.778]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Same issue exists in integrated terminal (using git/bin/bash.exe) inside VS Code

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD (same issue inside VS Code Integrated Terminal)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
yarn help
```
 - What did you expect to occur after running these commands?

The Yarn Help Menu (list of commands)

 - What actually happened instead?

It takes a few seconds, then dumps me at a new prompt. When I type, nothing is echoed back. If I press [enter] I see the command that I typed echoed on a new line, but it does nothing and dumps me at a new prompt.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by rimrul** [comment]
>    Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
>
>CMD (same issue inside VS Code Integrated Terminal)
>
>    What commands did you run to trigger this issue? If you can provide a
    Minimal, Complete, and Verifiable example
    this will help us understand the issue.
>
>yarn help

So `yarn help` doesn't even work in CMD? How is it a Git for Windows issue then?

For yarn in bash , try `winpty yarn help` (assuming it actually works in CMD). 

See also [FAQ: Some native console programs don't work when run from Git Bash. How to fix it?](https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it)

And the Text in the installer when you chose your Terminal emulator

>Use MinTTY (the default terminal of MSYS2)
>
>Git Bash will use MinTTY as terminal emulator, which sports a resizable window, non-rectangular selections and a Unicode font. **Windows console programs (such as interactive Python) must be launched via `winpty` to work in MinTTY**.
>
>Use Windows' default console window
>
>Git will use the default console window of Windows ("cmd.exe"), which **works well with Win32 console programs such as interactive Python or node.js**, but has a very limited default scroll-back, needs to be configured to use a Unicode font in order to display non-ASCII characters correctly, and prior to Windows 10 its window was not freely resizable and it only allowed rectangular text selections.

And the known issues section in the release notes for every version of Git for Windows that was released in the last 5 years

> Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

**Comment by dscho** [comment]
I just tried it with my local v2.26.2 installation, and this is what I get:

```
$ yarn help

  Usage: yarn [command] [flags]

  Displays help information.

  Options:

    --cache-folder <path>               specify a custom folder that must be used to store the yarn cache
    --check-files                       install will verify file tree of packages for consistency
    --cwd <cwd>                         working directory to use (default: C:\Users\johasc)
    --disable-pnp                       disable the Plug'n'Play installation
    --emoji [bool]                      enable emoji in output (default: false)
    --enable-pnp, --pnp                 enable the Plug'n'Play installation
    --flat                              only allow one version of a package
    --focus                             Focus on a single workspace by installing remote copies of its sibling workspaces.
    --force                             install and build packages even if they were built before, overwrite lockfile
    --frozen-lockfile                   don't generate a lockfile and fail if an update is needed
    --global-folder <path>              specify a custom folder to store global packages
    --har                               save HAR output of network traffic
    --https-proxy <host>
    --ignore-engines                    ignore engines check
    --ignore-optional                   ignore optional dependencies
    --ignore-platform                   ignore platform checks
    --ignore-scripts                    don't run lifecycle scripts
    --json                              format Yarn log messages as lines of JSON (see jsonlines.org)
    --link-duplicates                   create hardlinks to the repeated modules in node_modules
    --link-folder <path>                specify a custom folder to store global links
    --modules-folder <path>             rather than installing modules into the node_modules folder relative to the cwd, output them here
    --mutex <type>[:specifier]          use a mutex to ensure only one yarn instance is executing
    --network-concurrency <number>      maximum number of concurrent network requests
    --network-timeout <milliseconds>    TCP timeout for network requests
    --no-bin-links                      don't generate bin links when setting up packages
    --no-default-rc                     prevent Yarn from automatically detecting yarnrc and npmrc files
    --no-lockfile                       don't read or generate a lockfile
    --non-interactive                   do not show interactive prompts
    --no-node-version-check             do not warn when using a potentially unsupported Node version
    --no-progress                       disable progress bar
    --offline                           trigger an error if any required dependencies are not available in local cache
    --otp <otpcode>                     one-time password for two factor authentication
    --prefer-offline                    use network only if dependencies are not available in local cache
    --preferred-cache-folder <path>     specify a custom folder to store the yarn cache if possible
    --prod, --production [prod]
    --proxy <host>
    --pure-lockfile                     don't generate a lockfile
    --registry <url>                    override configuration registry
    -s, --silent                        skip Yarn console logs, other types of logs (script output) will be printed
    --scripts-prepend-node-path [bool]  prepend the node executable dir to the PATH in scripts
    --skip-integrity-check              run install without checking if node_modules is installed
    --strict-semver
    --update-checksums                  update package checksums from current repository
    --use-yarnrc <path>                 specifies a yarnrc file that Yarn should use (.yarnrc only, not .npmrc) (default: )
    -v, --version                       output the version number
    --verbose                           output verbose messages on internal operations
    -h, --help                          output usage information
  Commands:
    - access
    - add
    - audit
    - autoclean
    - bin
    - cache
    - check
    - config
    - create
    - exec
    - generate-lock-entry / generateLockEntry
    - global
    - help
    - import
    - info
    - init
    - install
    - licenses
    - link
    - list
    - login
    - logout
    - node
    - outdated
    - owner
    - pack
    - policies
    - publish
    - remove
    - run
    - tag
    - team
    - unlink
    - unplug
    - upgrade
    - upgrade-interactive / upgradeInteractive
    - version
    - versions
    - why
    - workspace
    - workspaces

  Run `yarn help COMMAND` for more information on specific commands.
  Visit https://yarnpkg.com/en/docs/cli/ to learn more about Yarn.
```

For the record:

```
$ yarn version
yarn version v1.22.4
error Couldn't find a package.json file in "C:\\Users\\me"
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.

$ node -v
v12.16.2
```

**Comment by itunbridgedev** [comment]
`winpty yarn help` results:
winpty: error: cannot start 'yarn': Not found in PATH

If I use `env|grep PATH` I see PATH=/c/Users/ian...<all my path entries>:/c/Program Files (x86)/Yarn/bin I also see the same path listed in ORIGINAL_PATH

**Comment by dscho** [comment]
Closing as stale.
