### ISSUE TITLE
Quotes are not escaped when saved to the Git config

### ISSUE THREAD

**Issue by isiahmeadows** [git-for-windows/git#2617]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.1.windows.1
cpu: x86_64
built from commit: 14af9f9d205f4a6a033c7b6f48980d1eeee2c610
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.778]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Atom
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope. I did run all commands with `GIT_TRACE=1`, however.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
PS> git config --global core.editor '"C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd" --wait'
20:11:03.136597 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
20:11:03.138615 git.c:439               trace: built-in: git config --global core.editor 'C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd --wait'
PS> git config --global core.editor
20:11:07.204623 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
20:11:07.205621 git.c:439               trace: built-in: git config --global core.editor
C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd --wait
PS> git rebase --interactive
20:11:24.296349 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
20:11:24.297340 git.c:439               trace: built-in: git rebase --interactive
hint: Waiting for your editor to close the file... 20:11:24.306325 run-command.c:663       trace: run_command: 'C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd --wait' C:/Users/USERNAME/projects/proposal-batched-dom/.git/rebase-merge/git-rebase-todo
C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd --wait: C:UsersUSERNAMEAppDataLocalatombinatom.cmd: command not found
```
 - What did you expect to occur after running these commands?

It to execute that command as specified.

 - What actually happened instead?

It dropped the strings in the first step and the backslashes in the second step.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happens with any repository I've tried it in. It also reproduces with other commands that open editors like `git commit --amend`.

**Edit:** Use the PS prompt to avoid confusion

**Comment by isiahmeadows** [comment]
My workaround was to manually set the user-level Git config at `%UserProfile%\.gitconfig`. And FYI, that `\` isn't a forgotten escape, if you're not aware of PowerShell syntax.

```
$ echo '"C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd" --wait'
"C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd" --wait
```

The `$` is just the prompt censored, and the repo itself is irrelevant. (It's a private repo.) Git's the one doing magic to it.

**Comment by dscho** [comment]
> ```
> $ git config --global core.editor '"C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd" --wait'
> ```

This looks like Bash, not like PowerShell. For PowerShell, I would have expected something like this:

```
PS C:\Users\me> git config --global core.editor '"C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd" --wait'
```

In any case, you could try to play around with escaping (in PowerShell, the escape character is the backtick), i.e. something like this might work:

```
PS C:\Users\me> git config --global core.editor '`"C:\Users\USERNAME\AppData\Local\atom\bin\atom.cmd`" --wait'
```

**Comment by isiahmeadows** [comment]
@dscho I swapped it to the Bash prompt so it wasn't as text-heavy, but trust me, I was using PowerShell. 😉

And no, escapes didn't make any difference.

**Comment by dscho** [comment]
> I swapped it to the Bash prompt so it wasn't as text-heavy

When reporting bugs, I do request to show the original reproducer. Otherwise I would be chasing wild geese, and I don't have the time for that (nor do I want to hunt animals).

> And no, escapes didn't make any difference - already tried it.

Well, try harder ;-)

I also was not able to make a _direct_ Git config call work in PowerShell (I used `$env:GIT_TRACE = "1"` to make it a bit more obvious what quoting style reached `git.exe`), but this one worked:

```ps
cmd /c 'git config -f test.config --replace-all some.value "\"with quotes\""'
```

Note that there are _several_ levels of escaping at play here. The outer single-quotes are necessary to pass the command-line verbatim to CMD. The surrounding double-quotes are necessary to pass the string `\"with quotes\"` as a single argument to `git.exe` rather than two. And the backslashes are needed because values inside the config can be quoted in double-quotes, too, and you want the double-quotes to be part of the value.

**Comment by isiahmeadows** [comment]
I'll close the issue for now, then. Definitely unintuitive, but I'll file another issue if I run into similar issues again. (I'll also be sure to repro it in something like Node to better control for escaping.)

**Comment by dscho** [comment]
> Definitely unintuitive

Yep, but then, like you, I also have no idea how to make it more intuitive.
