### ISSUE TITLE
Reduce size of portable Git

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#262]
It would be really nice if GitHub for Windows could download a substantially smaller PortableGit for Windows 2.x.

I previously already identified locales and most of the terminfo as unnecessary, but that still leaves a lot of room for improvement. My plan is to run the test suite on a current PortableGit, using Process Explorer to identify the list of used files, then generate the negative list and inspect it carefully, extending [the list of exclusions](https://github.com/git-for-windows/build-extra/blob/56dcda494a9389622fac3337cf9731f41f08bf3a/make-file-list.sh#L33-L46) as appropriate.

**Comment by silverkorn** [comment]
I feel bad that you created this issue while I just recently requested this: https://github.com/git-for-windows/build-extra/pull/68 :(

**Comment by dscho** [comment]
@shiftkey sorry, I forgot to Cc: you! This was on your wish list, wasn't it?

**Comment by shiftkey** [comment]
@dscho yes, yes it was! :grin:

**Comment by dscho** [comment]
Awesome! :smiley:
