### ISSUE TITLE
git doesn't output color to the (interactive) terminal when invoked from WSL

### ISSUE THREAD

**Issue by filcab** [git-for-windows/git#2627]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Preface
Really sorry if this is not the best place for this issue. Please point me to a better place to file this issue if needed. (template follows, then I'll explain the bug a bit better)

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1158]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I have WSL installed (Windows version 1809)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

(wsltty) WSL zsh->git-for-windows
cmd->WSL zsh->git-for-windows
git-bash->WSL zsh->git-for-windows

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# commands executed *inside* a WSL shell (bash/zsh/whatever)
# command that doesn't print any color (git.exe is outputting directly to TTY)
git.exe -C C:/code/dot-files show --no-patch --format=format:%C\(always,#ff00ff\)helloworld%Creset
# command that *does* colorize output because git.exe will not use whatever TTY-output features it usually uses and will print the terminal escape sequences to the pipe. Then Linux's cat command will just print them
git.exe -C C:/code/dot-files show --no-patch --format=format:%C\(always,#ff00ff\)helloworld%Creset | cat

# binary being used
which git.exe
/mnt/c/Program Files/Git/cmd/git.exe
```
 - What did you expect to occur after running these commands?

Color output on both commands
Only the piped command has color

 - What actually happened instead?

First command (at a TTY) doesn't show color

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Independent of repository

### More details
Hi all,

I understand this bug is weird, please bear with me. Any time I mention/use `git.exe`, that is specifically my git-for-windows install.

* Why do you want such a weird setup?
I'm using git-for-windows from a WSL shell so I can:
  * Run any Linux utility, including some that haven't been ported to Windows *and* compiling stuff as Linux binaries
  * Run git.exe with acceptable timings on a *huge* repo with lots of files (on Windows-land). Even git-for-windows will take longer than I'd like, but a WSL utility will just not finish scanning files for modifications in a timely manner
  * Call Windows utilities from my Linux tmux/vim sessions (I do tell (Linux) vim to use git.exe, for example)

I might (very likely) have not narrowed down the bug enough, but I don't have enough knowledge of MINGW and what it does, and how it integrates with git.exe.

Thank you,
 Filipe

**Comment by filcab** [comment]
Example with several terminal Windows:
top-left: WSLTTY, WSL zsh running
bottom-left: Windows terminal, after running `wsl` command
right: git-bash shortcut (which somehow makes it weirder, as color always works. I wonder if there's issues with MINGW TTY output interpretation?)

![git-terminal-weirdness](https://user-images.githubusercontent.com/59193/82322561-9f1cd100-99ce-11ea-884b-74da9e8c0ac9.png)

**Comment by dscho** [comment]
I didn't really have time to study the screenshots and description, but: did you try v2.27.0-rc0? It comes with support for the pseudo console, which might help your use case.

**Comment by filcab** [comment]
I haven't tried yet, but will do.
Trying to sum up the issue here, in case you want to see it quickly:
WSL terminal, run this command (maybe with the full path to Windows git):
`git.exe -C C:/code/dot-files show --no-patch --format=format:%C\(always,#ff00ff\)helloworld%Creset`
And color won't show up

**Comment by filcab** [comment]
Aww, cool!
v2.27.0-rc0 seems to work for my use-case.

Thanks a lot!

**Comment by dscho** [comment]
Good!

There are a few bugs in the pseudo console code, though, therefore it will be disabled by default starting with -rc1. I'll add a page to the installer where you can opt-in!

**Comment by filcab** [comment]
Cool, thanks!
btw, where can I learn a bit more about this change? Was this a cygwin thing? git-only thing? mingw?

**Comment by PhilipOakley** [comment]
Cygwin is a programme that runs on windows and tries to create a screen/terminal view that runs just as if you are on a Linux machine, and tries to hide all the differences in the  file system between Windows and Linux/Posix. Pure Git (rather than Git-for-Windows) is run here.

'git-only' don't see that in the previous posts. Maybe it's because the "Git for Windows" programme limits itself to being a bare minimum interface between Windows and Git (which thinks it is running in Linux). 

MINGW and MSYS are the main part of that minimal interface shim - they borrow a few things from Cygwin. Only a few Linux utilities are made available in Git for Windows.

WSL is Microsoft's 'version' of cygwin. You can then chose a distro (debian/ubuntu/etc.), and then run _pure_ Git (see above about cywin)

That's at least my simplistic view of the differences to get you started.

**Comment by filcab** [comment]
Hi Philip,

I do understand what each of those components are. I'm just trying to figure out what change @dscho was referring to with:
> It comes with support for the pseudo console, which might help your use case.

This (changed/added) support for pseudo console can be in (this is as far as I understood how the blocks fit, I might be wrong in some places):
* cygwin's base that's imported into mingw (includes *lots* of *NIX-like subsystems, including pseudo-console)
* mingw's changes to the cygwin subsystems
* (msys is a bit "unrelated" as it's there mostly to help develop mingw (or other Windows native) * software. it'll include mingw plus POSIX-like file/dir structure)
* git-for-windows *might* be able to configure some mingw (or imported cygwin base) stuff when it's compiled

(WSL is a full Linux system (can pick several distros, as you said), based on a Microsoft-patched Linux kernel. Very different from cygwin and similar solutions)

The thing is:
When using git-for-windows=>mingw DLL=>WSL pseudo-console=>terminal (wsltty, windows terminal, mintty, etc), something changed from 2.26 to 2.27. That's the change I'm interested. If it was something that git-for-windows "got for free" due to updating mingw (and, if known, if it's from mingw or imported cygwin subsystems), or if it's some support that was actually added/patched in git-for-windows.

I'll be searching for myself too, but since @dscho explicitly mentioned, I thought they could help steer me to find those changes.

Thank you,
 Filipe

**Comment by dscho** [comment]
Cygwin is not imported into mingw, but into MSYS2, as the MSYS2 runtime.

The pseudo console support came in via that Cygwin runtime, and it affects only the MSYS part of Git for Windows, i.e. the executables that use that MSYS2 runtime (or: POSIX emulation layer). `git.exe` is _not_ such an MSYS program, but Bash is, and MinTTY is (which opens that Git Bash window).

See https://github.com/cygwin/cygwin/search?q=pseudo+console&type=Commits for the commits.

There is no MINGW DLL.
