### ISSUE TITLE
Cannot clone svn with SASL authentication 

### ISSUE THREAD

**Issue by Domain** [git-for-windows/git#2629]
Normal password authentication is OK. But I cannot clone the repo with SASL authentication.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [10.0.19624.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD in Windows Terminal 0.11.1333.0

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git svn clone svn://192.168.1.2/project/trunk project
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

Initialized empty Git repository in C:/project/.git/
Can't create session: Unable to connect to a repository at URL 'svn://192.168.1.2/project/trunk' at C:/Program Files/Git/mingw64/share/perl5/Git/SVN.pm line 148.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no

**Comment by dscho** [comment]
>     * If the problem was occurring with a specific repository, can you provide the
>       URL to that repository to help us with testing?
> 
> 
> no

That will make it nigh impossible for contributors like myself to jump in and help.

Mind, I would consider `git svn` somewhat of a legacy part by now. Read: I do what I can to maintain it, but I won't put much of an effort into trying to develop it further.

In your particular case, you might actually be better off installing [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) and run `git svn` from inside there.

Having said that, if you work on this and figure out how to fix this and open a PR, I will be glad to review and merge it.

**Comment by Domain** [comment]
I am not familiar with perl. But I can confirm the problem is raised by line 128 at SVN\Ra.pm:
`	my $self = SVN::Ra->new(url => $url, auth => $baton,
	                      config => $config,
			      pool => SVN::Pool->new,
	                      auth_provider_callbacks => $callbacks);` 
But I don't know how to debug this.

**Comment by Domain** [comment]
[https://stackoverflow.com/questions/12763789/using-git-svn-over-svn-sasl-with-encryption](https://stackoverflow.com/questions/12763789/using-git-svn-over-svn-sasl-with-encryption)

**Comment by dscho** [comment]
> https://stackoverflow.com/questions/12763789/using-git-svn-over-svn-sasl-with-encryption

A link is just a bone you throw to the dogs. This is what I would have wished you'd provided:

> [...] you will need to also install this (sic!) packages
>
> * perl-Authen-SASL
> * perl-Term-ReadKey
> * libsasl2_3 (*)

@Domain so this is what you could work on. Figure out whether all three are available in [Git for Windows' SDK](https://gitforwindows.org/#download-sdk), whether `git svn` works when you install them, and then you would need to figure out how to produce a PR to get that goodness into the Git for Windows installer (I would help you with that at that point).

**Comment by Domain** [comment]
I just installed the cygwin git, and found that it had exactly the same problem. WSL works fine.
If anyone can point out how to debug this, I can give it a try.

**Comment by dscho** [comment]
> If anyone can point out how to debug this, I can give it a try.

This might be a bit involved.

Line 148 as indicated in the error message reads like this:

```perl
        my $ra = Git::SVN::Ra->new($url);
```

You could try to instrument the Perl code in the `new` subroutine in `C:/Program Files/Git/mingw64/share/perl5/Git/SVN/Ra.pm` to figure out at which point it fails. My guess it is the `SVN::Ra->new(...)` call, and I could imagine that it fails somewhere inside `C:/Program Files/Git/usr/lib/perl5/vendor_perl/SVN/Ra.pm`'s `new` subroutine, which calls the native Subversion modules, IIRC. At some stage you should hit the layer where authentication is attempted.

**Comment by Domain** [comment]
> I could imagine that it fails somewhere inside `C:/Program Files/Git/usr/lib/perl5/vendor_perl/SVN/Ra.pm`'s `new` subroutine, which calls the native Subversion modules, IIRC.

Yes:
https://github.com/git-for-windows/git-sdk-64/blob/de71d1b4dd01de276e21265b3a24e5a69cbfd717/usr/lib/perl5/vendor_perl/SVN/Ra.pm#L529

**Comment by dscho** [comment]
> > I could imagine that it fails somewhere inside `C:/Program Files/Git/usr/lib/perl5/vendor_perl/SVN/Ra.pm`'s `new` subroutine, which calls the native Subversion modules, IIRC.
> 
> Yes:
> https://github.com/git-for-windows/git-sdk-64/blob/de71d1b4dd01de276e21265b3a24e5a69cbfd717/usr/lib/perl5/vendor_perl/SVN/Ra.pm#L529

So if you still want to continue in the way _I_ would investigate further, you would build Subversion from source (`sdk build subversion` in the Git for Windows SDK), then go to the directory with the source code (`cd src/subversion-*`), try to find the `svn_ra_open()` function (something like `find -type f -exec grep -l svn_ra_open {} \;` to start), then add debug printf statements and re-build (probably `make -j$(nproc)`).

I could imagine that the edit/compile/test cycle could be accelerated if a direct `svn` invocation would already fail. Maybe that would also give you an error message that is more indicative how to fix it.

**Comment by Domain** [comment]
I built subversion from source. And then copy all files in git-sdk-64/usr/src/MSYS2-packages/subversion/pkg/subversion/usr to git-sdk-64/usr. And a direct svn invocation works fine. Then I try to run git svn to clone the repos:
git svn clone svn://192.168.1.2/project/trunk project
But it fails:
> C:/Users/domain/source/Repos/git-sdk/usr/lib/git-core/git.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
init: command returned error: 127

Should I build git from source?

**Comment by dscho** [comment]
> 127

That typically means that a `.dll` was not resolved. I _think_ that running that `git svn clone` while a [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) instance is running could potentially shed light into which `.dll` we're talking about, and where Windows looked for it.

**Comment by dscho** [comment]
Closing as stale.
