### ISSUE TITLE
Make `Git Bash` pinnable

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#263]
After starting *Git Bash*, the context menu in the Task Bar icon allows to pin the program. However, starting *Git Bash* that way does not start the same program but instead launches `mintty.exe` (and `bash.exe` is launched in there, but without the `--login` flag and without the `MSYSTEM` environment variable set appropriately).

Investigate whether this is fixed by setting the [`System.AppUserModel.RelaunchCommand` property](https://msdn.microsoft.com/en-us/library/dd391571.aspx) from the Git wrapper might help (as hinted in [this blog](http://blogs.msdn.com/b/oldnewthing/archive/2011/06/01/10170113.aspx)). (I hinted at that already [here](https://github.com/git-for-windows/git/issues/167#issuecomment-109765335) but that information was ignored there.)

**Comment by dscho** [comment]
Hmm. It seems that I fail to set the `RelaunchCommand` property in `mintty`'s properties from another process (namely the Git wrapper process that launched `mintty`): Windows always comes back with the answer "The system could not find the environment option that was entered."

It *looks* as if a hacked up `mintty` would be able to set the `RelaunchCommand` property correctly. My current thinking: add two command line options for the `RelaunchCommand` and the `RelaunchDisplayNameResource` property. Probably similar to the `ID` property handled [here](https://github.com/mintty/mintty/blob/98110239312416152b1339faf8772f33790520d2/src/config.c#L213 and [here](https://github.com/mintty/mintty/blob/ea6a43a4f93b0c4812853b82b57622317ef90552/src/winmain.c#L1130-L1144).

**Comment by nalla** [comment]
Wait a minute. I think it should be enough to set an app id for the git-wrapper. You can just provide the app id that `mintty` is using. Just call `mintty -o AppID=test`

**Comment by nalla** [comment]
You can confirm this theory following the steps outlined below.

first, change your registry so that you edit the `System.AppUserModel.ID` in the properties of the shortcut.

```
Windows Registry Editor Version 5.00

[-HKEY_CLASSES_ROOT\.lnk\ShellEx\{00021500-0000-0000-C000-000000000046}]

[HKEY_CLASSES_ROOT\lnkfile]
"InfoTip"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"ConflictPrompt"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"ContentViewModeForBrowse"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"ContentViewModeForSearch"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"ContentViewModeLayoutPatternForBrowse"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"ContentViewModeLayoutPatternForSearch"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"ExtendedTileInfo"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"PreviewDetails"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"PreviewTitle"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"QuickTip"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"SetDefaultsFor"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"TileInfo"="prop:System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay"
"FullDetails"="prop:System.PropGroup.Description;System.ItemTypeText;System.Comment;System.Link.TargetParsingPath;System.AppUserModel.ID;System.ItemFolderPathDisplay;prop:System.PropGroup.FileSystem;System.ItemNameDisplay;System.Size;System.DateCreated;System.DateModified;System.FileAttributes;*System.OfflineAvailability;*System.OfflineStatus;*System.SharedWith;*System.FileOwner;*System.ComputerName"
"FileOperationPrompt"="prop:System.ItemTypeText;System.FileOwner;System.Author;System.Title;System.Subject;System.Comment;System.DateModified;System.Link.TargetParsingPath"
```

Now open the Git for windows shortcut in the taskbar and set the id in the details pane to `test`.

Then add the following to your `/etc/minttyrc` file: `AppID=test`

And viola: it just works.

**Comment by nalla** [comment]
So I think we can avoid patching `mintty` by simply calling `SetCurrentProcessExplicitAppUserModelID` in `git-wrapper.c` and then call `mintty -o AppID=git-wrappers-id`

**Comment by dscho** [comment]
Nice!

This would not really help with portable Git, though, correct?

**Comment by nalla** [comment]
Sure. Why not? If `git-bash` sets an appid per Windows API and then calls `mintty -o AppID=` with that id?

**Comment by dscho** [comment]
Oh, wait, the registry entry is not even required if we set the AppID in the Git wrapper *as well as* the Git Bash... I get it now!

**Comment by nalla** [comment]
Right its just a way to set an id for a shortcut ig the exe provides none.

**Comment by dscho** [comment]
I really like the idea. I'm on it.

**Comment by dscho** [comment]
Sadly, it is not as easy :disappointed:... In my tests, setting the app ID via `SetCurrentProcessExplicitAppUserModelID()` in the Git wrapper and passing `-o AppID=...` to `mintty.exe` did *not* work. The pinned icon *still* launched *just* `mintty`.

I then continued to work on implementing support for [the `RelaunchCommand` property](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391571%28v=vs.85%29.aspx) and [the `RelaunchDisplayNameResource` property](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391572(v=vs.85).aspx).

Unfortunately, it also did not work at first (even if it had worked in some tests I did yesterday). Hours later, turns out that the reason is well explained in the MSDN page:

> This property is used only if a window has an explicit Application User Model ID (*AppUserModelID*) (`System.AppUserModel.ID`, set through `SHGetPropertyStoreForWindow`). If the window does not have an explicit *AppUserModelID*, this property is ignored and the window is grouped and pinned as if it were part of the process that owns it.

So the only way to get it to work was by setting the combination of *ID*, *RelaunchCommand* and *RelaunchDisplayNameResource* together. The important part is that I have to set an ID *explicitly*. Otherwise, the display name is respected but not the relaunch command.

This got me curious, though, and I tested whether things start to work properly if I tell `mintty` to set the `System.AppUserModel.ID` property *explicitly*, i.e. *in addition to* calling SetCurrentProcessExplicitAppUserModelID() (which `mintty` [does](https://github.com/mintty/mintty/blob/271b95218844eac5ba7b85fee3b0124864d099e5/src/winmain.c#L1130-L1145) when the `-o AppID=...` option is used), but *not* set the `RelaunchCommand` at all.

Alas, this works! Restarting the *Git Bash* from a pinned icon works if `mintty`'s window handle has an app ID associated with it *explicitly*, but not when it is done only implicitly via the process.

(It might be a quirk just of Windows Server 2012 R2, on which I do all my testing and development, meaning that we have to patch `mintty` in *any* case...)

So at the moment, I have patches for `mintty` and a topic branch for our `MSYS2-packages` that I still need to rebase to upstream.

**Comment by dscho** [comment]
See https://github.com/git-for-windows/MSYS2-packages/compare/master...dscho:pinning-mintty for the current state of things. Still needs serious testing.

**Comment by nalla** [comment]
The `mintty -o` solution seems only to work if the shortcut is already targeting `git-bash`. :-(

**Comment by dscho** [comment]
@nalla thanks for confirming! FYI I opened a PR for mintty: https://github.com/mintty/mintty/pull/471

**Comment by dscho** [comment]
Update: I now have topic branches in three (!) repositories that work together to address this ticket:

- in [`MSYS2-packages`](https://github.com/git-for-windows/MSYS2-packages/compare/master...dscho:pinning-mintty), to teach `mintty` to support pinning to the task bar better (more on that below)
- in [`git`](https://github.com/git-for-windows/git/compare/master...dscho:pinnable), to support setting the application ID of the Git wrapper, and
- in [`MINGW-packages](https://github.com/git-for-windows/MINGW-packages/compare/master...dscho:pinnable-git-bash), to make use of the previous two change sets in *Git Bash*.

The changes for `mintty` were implemented as a patch series, applied on top of mintty's official sources, to allow setting the application ID, the display name and the relaunch command explicitly for the mintty window. I also submitted this patch series as Pull Request to the mintty project:  https://github.com/mintty/mintty/pull/471

Long day.

**Comment by dscho** [comment]
With these three merges, this ticket is finally addressed.

**Comment by ciaranj** [comment]
Did this (awesome!) work make the 2.5.0 release?   I've updated and I still appear to have the 'jumbled' stacks issue (for git-bash.exe incidentally, git-cmd.exe appears to work as 'expected')

**Comment by dscho** [comment]
It made it into the release. You most likely have a stale `Git Bash.lnk` file somewhere in the `$HOME\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\` directory structure, most likely in the funny-named subdirectory of  `ImplicitAppShortcuts`.

Once you unpin, delete that `.lnk` file and re-pin, it should work (that is what fixed it here).
