### ISSUE TITLE
edit-git-bash.exe pops error when installing v2.27.0-rc1

### ISSUE THREAD

**Issue by KexyBiscuit** [git-for-windows/git#2631]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.rc1.windows.1
cpu: x86_64
built from commit: b9036e49ce9367a8493c2909957f257982eb598f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.264]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCodeInsiders
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Upgrade from Git for Windows 2.27.0-rc0.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Not yet, in installer.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Git-2.27.0-rc1-64-bit.exe
```
 - What did you expect to occur after running these commands?

Installer finishes its work.

 - What actually happened instead?

```
---------------------------
edit-git-bash.exe - System Error
---------------------------
The code execution cannot proceed because libssp-0.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Ouch. Thank you for the report. Will fix that.

**Comment by dscho** [comment]
The next [snapshot](https://wingit.blob.core.windows.net/files/index.html) will have this fix!
