### ISSUE TITLE
Git bash does not cooperate with Java's System.console()

### ISSUE THREAD

**Issue by sherfert** [git-for-windows/git#2633]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen+System.console) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed+System.console) issue matching what I'm seeing

In Java, `System.console()` can be used to consume standard input and write to standard output. Most importantly, it can be used to detect if input and output is interactive (i.e. not redirected). If both are interactive, `System.console()` should be defined. This works on CMD and power-shell. On git bash, however, it is `null`.

### Setup
 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64-bit

```
$ git --version --build-options
git version 2.17.1.windows.2
cpu: x86_64
built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
sizeof-long: 4
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.836]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Right-click from windows explorer, "open git bash here".

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

From git bash, execute:
```
echo 'public class X{public static void main(String[]args){System.out.println(System.console() == null);}}'>X.java;javac X.java&&java X
```
 - What did you expect to occur after running these commands?
The Java program should find `System.console()` and thus print `false`.

 - What actually happened instead?
The Java program prints `true`.

**Comment by rimrul** [comment]
Your `java` is probably expecting a conhost session, not a pty. Try `winpty java X` (or alternatively building OpenJDK for MSYS2), that should work.

**Comment by dscho** [comment]
Even better: install Git for Windows v2.27.0-rc1 and check the experimental "pseudo console" option, then try again.

**Comment by SaschaPeukert** [comment]
@dscho How/Where do you set that option?

**Comment by dscho** [comment]
> @dscho How/Where do you set that option?

It's the last page in the installer before it is installed. The page is called "Experimental Options" and looks like this:

![image](https://user-images.githubusercontent.com/127790/82812918-4e0c5180-9e94-11ea-8ada-91099d5e8461.png)

**Comment by SaschaPeukert** [comment]
Any chance that can be set for one of the portable versions?

**Comment by dscho** [comment]
You can do that manually: create the file `/etc/git-bash.config` with the contents: `MSYS=enable_pcon`.

**Comment by SaschaPeukert** [comment]
> You can do that manually: create the file `/etc/git-bash.config` with the contents: `MSYS=enable_pcon`.

Thanks. The java program from above still returns true though

**Comment by dscho** [comment]
> Thanks. The java program from above still returns true though

And what if you use `winpty`, [as suggested earlier](https://github.com/git-for-windows/git/issues/2633#issuecomment-633478406)?

**Comment by SaschaPeukert** [comment]
`winpty java X` actually gives the expected result!

**Comment by dscho** [comment]
> `winpty java X` actually gives the expected result!

Excellent.

Please note that this class of problems is mentioned specifically in our [known issues](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).
