### ISSUE TITLE
Make 64-bit downloads the default/preferred option

### ISSUE THREAD

**Issue by aaronfranke** [git-for-windows/git#2634]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Details

https://git-scm.com/download/win

On this page, it automatically starts downloading the 32-bit version. This isn't ideal considering the vast majority of systems are 64-bit. Instead, the 64-bit version should be downloaded automatically.

Additionally, the 64-bit links should be moved above the 32-bit links, and consider changing the font size of the 32-bit links to be smaller.

**Comment by PhilipOakley** [comment]
As far as I understand it Git-scm page (managed by Github) determines what it thinks your machine type is and offers the appropriate download based on that.

The full list of release is available from the [gitforwindows.org](https://gitforwindows.org/) page. The "[All Releases](https://github.com/git-for-windows/git/releases/)" link is at the footer of the page, as is the link to the latest [snapshots](https://wingit.blob.core.windows.net/files/index.html).

Does the gitforwindows.org page also determine the 'wrong' version for your machine? If so add more details from the template.

**Comment by rimrul** [comment]
git-scm.com determines what download to offer based on your browsers user agent. If your browser tells the website it's 64bit, they'll offer you the 64bit download. If your issue persists after switching to a browser that submits it's bitness, please open an issue at https://github.com/git/git-scm.com

**Comment by aaronfranke** [comment]
git-scm.com links directly to this repository, so I assumed it was managed by this repository's owners. I'll open a new issue in that repository instead.

I don't see what you mean by asking if gitforwindows.org determines the 'wrong' version. gitforwindows.org just links to the GitHub releases page, which doesn't determine anything.

**Comment by dscho** [comment]
@aaronfranke FWIW I _cannot_ reproduce your issue here. Directing my Firefox (32-bit, running in a 64-bit OS) to https://git-scm.com/download/win gives me this:

![image](https://user-images.githubusercontent.com/127790/82813060-9d528200-9e94-11ea-8c90-c0a8ab87bacf.png)

I might do things differently from you; I would not know, you left out details such as your browser and/or software versions.
