### ISSUE TITLE
Help requested to test `git diffn`, a `git diff` wrapper which shows line numbers, in the bash terminal in Git for Windows

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [git-for-windows/git#2635]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I just wrote `git diffn`, and need some help testing it since I don't have Windows. If someone can try it out please, I need to know if it works and a full set of install instructions. Start with my writeup and install instructions here: https://stackoverflow.com/questions/24455377/git-diff-with-line-numbers-git-log-with-line-numbers/61997003#61997003

I think it's pretty useful and I'm pretty excited about it. Check this out. It shows **line numbers**!

![`git diffn` screenshot](https://i.stack.imgur.com/F6gyz.png)

It relies on `gawk`, but if `gawk` doesn't work in the Git for Windows bash terminal I can make some modifications I think and make it work with regular `awk`.

<!--
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

-- >

**Comment by dscho** [comment]
Note: this ticket is not about any bug in Git for Windows.

**Comment by ElectricRCAircraftGuy** [comment]
That's right. It's a request of mine to see if a tool I wrote will work in Git For Windiws, but I don't have Windows to t

**Comment by ElectricRCAircraftGuy** [comment]
Ignore that close. Stray button press on my phone.

**Comment by chrisbra** [comment]
FWIW: git diffn work on my git-for-windows version 2.26.0
It is actually quite nice. Thanks for that!

**Comment by ElectricRCAircraftGuy** [comment]
Nice! Can you detail your install instructions?

Ideally I'd like to document how to install it well enough a 12 yr old could follow. Think: Arduino or Adafruit level detail. But, any level of detail is better than nothing.

**Comment by rimrul** [comment]
The installation should just be what you call option 2 on Stackoverflow (modified to use curl, due to missing wget).

Open Git-Bash, execute the following commands:

```

mkdir -p ~/bin
cd ~/bin
curl https://raw.githubusercontent.com/ElectricRCAircraftGuy/eRCaGuy_dotfiles/master/useful_scripts/git-diffn.sh > git-diffn

```

**Comment by chrisbra** [comment]
Well, it's a bit off topic for GFW issue tracker, but here is what I did
I copied your https://raw.githubusercontent.com/ElectricRCAircraftGuy/eRCaGuy_dotfiles/master/useful_scripts/git-diffn.sh to `~/bin/git-diffn`,  `chmod +x` it, and followed your example from the [stackoverflow page](https://stackoverflow.com/a/61997003/789222). 

I also tried briefly with a couple of `git diff` parameters and it worked, however I noted a problem. If I use this color configuration:

`
git config color.diff.meta "blue"
git config color.diff.old "black red strike"
git config color.diff.new "black green italic"
git config color.diff.context "yellow bold"
`
Then run in that repo `git diffn` I get nicely colored output, except for the `:` (colon).  That looks odd. 
![grafik](https://user-images.githubusercontent.com/244927/82895634-c5091f00-9f54-11ea-81c9-51eaaaf9e818.png)

**Comment by ElectricRCAircraftGuy** [comment]
> Then run in that repo git diffn I get nicely colored output, except for the : (colon). That looks odd.

@chrisbra , that was intentional. It helps me visually separate between the added number column on the left and the original git diff output on the right. I thought it looked better that way. Otherwise I found myself sometimes struggling to see what was what.

**Comment by PhilipOakley** [comment]
> >  Then run in that repo git diffn I get nicely colored output, except for the : (colon). That looks odd.

> that was intentional. It helps me visually separate between the added number column on the left and the original git diff output on the right. I thought it looked better that way. Otherwise I found myself sometimes struggling to see what was what.

Sounds like something to _document_ as a key feature :wink:

**Comment by rimrul** [comment]
I'm closing this issue now, because there hasn't been any more feedback in almost a year and it's become quite burried under other issues.
