### ISSUE TITLE
Network drive git rev-parse --show-toplevel

### ISSUE THREAD

**Issue by Dezmont51** [git-for-windows/git#2638]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

Y:\>git --version --build-options
git version 2.27.0.rc2.windows.1
cpu: x86_64
built from commit: 2703017a6d84c21f9558f5828506e8bfab70a290
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows Server 2012 R2
```
$ cmd.exe /c ver

Y:\>cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The folder is located on a network drive. Mounted as a disk Y:

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash/CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git rev-parse --show-toplevel
```
 - What did you expect to occur after running these commands?

** Y:/ **

 - What actually happened instead?

** //tsclient/TB/ **

 Different versions of the program on one computer.
```
Y:\>git version && git rev-parse --show-toplevel
git version 2.23.0.windows.1
Y:/


Y:\>git version && git rev-parse --show-toplevel
git version 2.27.0.rc2.windows.1
//tsclient/TB/
```
The script stopped working. 

> unc path not supported

**Comment by dscho** [comment]
>     * What did you expect to occur after running these commands?
> 
> 
> ** Y:/ **
> 
>     * What actually happened instead?
> 
> 
> ** //tsclient/TB/ **

Git resolves symbolic links and other gimmicks, and apparently in this case, it even resolves a mapped network drive. That is not a bug.

> The script stopped working.
> 
> > unc path not supported

What script?

**Comment by Dezmont51** [comment]
The script uses the path from git rev-parse
And he tries to open the file along this path, and he cannot now

**Comment by chrisbra** [comment]
Use `pushd \\server\path` to enter that directory and later `popd` to get rid of the temporary mapping.

**Comment by dscho** [comment]
As I mentioned, this feature works as intended.
