### ISSUE TITLE
.gitconfig created in ~/, that is my Y:

### ISSUE THREAD

**Issue by bo-ahlsen** [git-for-windows/git#2639]
- [ ] I have managed to create an unaccessible and trashed .gitconfig of size 0 by issuing an incorrect >git config, See below
~gitconfig --global.editor "emacs"~ 
 
Y:\>dir /Q
 Volume in drive Y is 589
 Volume Serial Number is 0000-004F

 Directory of Y:\
...
020-04-28  16:24                 0 ...                    .gitconfig

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

$ git --version --build-options
Y:\>git version --build-options
git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows Vista 10
```
$ cmd.exe /c ver
Y:\>cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1217]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Y:\>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

In order to make my environment work I have to use the defult setup for my company
net use to Y: UNC

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Unfortunately it seems I have to use CMD

 - What commands did you run to trigger this issue? If you can provide a
 ~gitconfig --global.editor "emacs"~
 ``
 - What did you expect to occur after running these commands?
Change of git editor to emacs.

 - What actually happened instead?
I am aware the tilde's actually caused the problem (copy/paste is sometimes dangerous...) but I am not able to remove the trashed .gitconfig as the file file is owned by ...
_Y:\>del /A O .gitconfig
Y:\.gitconfig
This file is currently not available for use on this computer._
`_``
I can make the problem disappear temporarily in a shell by setting HOME to another path not referring to Y:. I can start gitk from this shell (CMD) however the workaround only takes action for the local shell. All my other tools as for instance gitExtensins etc still are unavailable...
When issuing any git command or even only >git in a shell not having HOME edited
(in git-bash this time) I get the response below.
$ git
fatal: unable to access 'Y://.gitconfig': Invalid argument

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
>  ~gitconfig --global.editor "emacs"~

Are you sure that you used that command? I would have expected

```sh
git config --global core.editor emacs
```

instead. And that command should work.

**Comment by bo-ahlsen** [comment]
Youtube are right. it was core.editor I did try to chansen
BR
Bo

Den tors 28 maj 2020 13:08Johannes Schindelin <notifications@github.com>
skrev:

**Comment by bo-ahlsen** [comment]
Hmm I have to disble the Sweedish spelling checker in my mobile ;-) 
Yet the problem remain as the fused .gitconfig stays unchanged in my network drive Y:.  This as the only way for me to access git is by changing $HOME or %HOME% to for instance C:\Home which has no .gitconfig at all. 
When I do this the %HOME %\.gitconfig is changed but the y:\.gitconfig (the fused one) remains unchanged... 
Thus my main usse is to be able to actually remove my Y:\.gitconfig. This file is unaccssible for me and also when I run as admin. It seems to be owned by ... (that is - someone outside). 
I have issued a support request for my company to remove the file but do not receive any answer. I guess I am not prioritized :-/ in the organization...

**Comment by dscho** [comment]
Unfortunately, permission problems on network drives are nothing Git for Windows can help with.

**Comment by bo-ahlsen** [comment]
Thank you for trying 👍 But one question remains How is it that '>git config ... ' surrounded by tilde ~ automaically creates a .gitconfig in $HOME not owned by the issuer of the git config call? You can answer to my private mail as I mainly ask the question because I am a bit curios...

**Comment by dscho** [comment]
> How is it that '>git config ... ' surrounded by tilde ~ automaically creates a .gitconfig in $HOME not owned by the issuer of the git config call?

I have no idea.
