### ISSUE TITLE
Hooks not accepting BOM (Unicode)

### ISSUE THREAD

**Issue by LeStahL** [git-for-windows/git#2640]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.836]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
- Created a .git/hooks/pre-commit file with unicode byte order marking (BOM) at the beginning
- Commited something
```
 - What did you expect to occur after running these commands?

The commit hook being run

 - What actually happened instead?

commit hook was not run, instead the error message below was shown:
`error: cannot spawn .git/hooks/pre-commit: No such file or directory`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by dscho** [comment]
>  `error: cannot spawn .git/hooks/pre-commit: No such file or directory`

IIUC this is a limitation of Bash, and unlikely to change.

Just remove the BOM.

**Comment by LeStahL** [comment]
> IIUC this is a limitation of Bash, and unlikely to change.

I verified this (by running a script file with BOM over Bash); the marker is interpreted as prefix to the first line - which then fails. 
```bash
test.txt: line 1: ﻿#!/bin/bash: No such file or directory
```
Note that the `No such file or directory` is only printed in combination with a present shebang; a regular command fails with a different message:
```bash
test.txt: line 1: ﻿echo: command not found
```
The remaining commands in the file are run though, which does not seem to be the case in the Git hooks. 

> Just remove the BOM.

I did exactly that; however it took me some time to identify that this was the problem (the error message is not exatly elaborate). 
I suggest adding a short check and displaying a more specific error message when BOMs are present, even though Bash would be a better place for such a check.

If you point me to the correct place to implement that, I would be willing to submit a PR.

**Comment by rimrul** [comment]
The place to look is [compat/mingw.c](https://githib.com/git-for-windows/git/compat/mingw.c#L1440-L1473). From a POSIX perspective the whole shebang mechanism is just a comment in a shell script. I'm not sure if bash handles perl scripts with a shebang and a BOM, but we could pass the BOM scripts to the specified interpreter and let it decide if it cares.

POSIX does seem to specify that the portable character set (including #) needs to be encoded as single byte characters, so we'll probably only need to care about the UTF-8 BOM here.

**Comment by rimrul** [comment]
Looking at it some more, it seems like `parse_interpreter()` succeeds, but `path_lookup()` fails causing `mingw_spawnvpe` to set `errno=ENOENT`.

**Comment by dscho** [comment]
> The place to look is [compat/mingw.c](https://githib.com/git-for-windows/git/compat/mingw.c#L1440-L1473).

That would indeed be the right place for that warning (note that the link is broken, [this link](https://github.com/git-for-windows/git/blob/01c50adf56430fdd98f903691ae41a83870801c0/compat/mingw.c#L1440-L1473) works, though).

> I'm not sure if bash handles perl scripts with a shebang and a BOM

It does not. 

But the first thing would be to teach Bash to handle hash-bang lines with a BOM.

The spot to fix this would be the Bash source code, and the PR would need to touch this tree: https://github.com/git-for-windows/MSYS2-packages/tree/master/bash. To figure out what to patch, I would suggest to:

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd bash`,
3. `sdk build`
4. then initialize a git worktree from the source code by `cd src/bash-4.4 && git init && echo "*.[oad]" >> .git/info/exclude && git add . && git commit -m initial`
5. try patching the code, building it, then testing with the built `bash.exe`.
   I would recommend looking for `HAVE_HASH_BANG_EXEC` in `execute_cmd.c`, e.g. [here](https://git.savannah.gnu.org/cgit/bash.git/tree/execute_cmd.c?h=bash-4.4#n5489) and [here](https://git.savannah.gnu.org/cgit/bash.git/tree/execute_cmd.c?h=bash-4.4#n5538). You will most likely have to identify all kinds of places where the constant `2` is used to skip over the `#!`, e.g. in [`getinterp()`](https://git.savannah.gnu.org/cgit/bash.git/tree/execute_cmd.c?h=bash-4.4#n5286).
6. once things work as you want them to, clean up the changes and commit them.
7. then export the patch via `git format -1 --o ../.. --start-number=9 HEAD`.
8. after `cd ../..`, add the patch via `git add`, then also add it to the `PKGBUILD` [here](https://github.com/git-for-windows/MSYS2-packages/blob/e9c85f996a7d98b5f9c6fab8a11fb58f3fd5056b/bash/PKGBUILD#L24) and [here](https://github.com/git-for-windows/MSYS2-packages/blob/e9c85f996a7d98b5f9c6fab8a11fb58f3fd5056b/bash/PKGBUILD#L51), run `updpkgsums` and commit the whole thing.
6. open a PR?

**Comment by rimrul** [comment]
Oh, I meant the more basic approach of just handing it to bash (or other apropriate interpreter) and letting it complain about that first line.

**Comment by dscho** [comment]
Well, I think that @LeStahL got quite a bit of information to digest ;-)

**Comment by dscho** [comment]
Closing as stale.
