### ISSUE TITLE
Cannot edit bash.bashrc using Vi or Vim, "bash.bashrc" E212: Can't open file for writing

### ISSUE THREAD

**Issue by thanhtacles** [git-for-windows/git#2644]
I've tried vi vim at the etc/bash.bashrc
even echo to >> to it, but nothing works, why?

### Setup

$ git --version --build-options

**$ git --version --build-options
git version 2.9.2.windows.1
sizeof-long: 4
**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.18363.836] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled **
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** rightclick -> git bash here? **

**Comment by dscho** [comment]
You haven't pasted the error message, but I think I'm guessing correctly when I suspect that permission is denied.

The reason? This file lives inside `C:\Program Files`, which is write-protected for regular users. You'll need administrator privileges to write it.

But even if you start Git Bash as administrator and edit the file successfully, a subsequent upgrade of Git for Windows will overwrite your edits: Git for Windows does consider everything inside `C:\Program Files\Git` to be owned by it, not by the user.

You're probably better off editing (or creating `~/.bash_profile`.
