### ISSUE TITLE
Are the release notes for v2.27.0.windows.1 missing a "known issues" section?

### ISSUE THREAD

**Issue by dakotahawkins** [git-for-windows/git#2646]
[Link](https://github.com/git-for-windows/git/releases/tag/v2.27.0.windows.1)

> Meaning: finally, Git Bash can accommodate console programs like node.exe, Python or PHP, without using the winpty helper (see [Known Issues above](https://github.com/git-for-windows/git/releases/tag/v2.27.0.windows.1#known-issues)).

**Comment by dscho** [comment]
There are actually multiple release notes. The one that this link was intended for is to be found in you start menu, in the "Git" group under the name "Git Release Notes". This is how it looks when I click on that link here:

![image](https://user-images.githubusercontent.com/127790/83455855-e5f2d800-a45e-11ea-90c2-ce23a0855daa.png)

But you meant the release notes on the GitHub Release page. I manually edited that note.
