### ISSUE TITLE
Ripgrep in Git bash 2.28.0 failed to show UTF-8 output

### ISSUE THREAD

**Issue by jfcherng** [git-for-windows/git#2648]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Sorry to report here if this ends up to be a ripgrep's issue but this did not happen in `2.26.2`.

### Setup

 - Git-bash 2.27.0 x64 (2.28.0 x64 has this problem as well)

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19041.264]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

   - This problem doesn't exist in `Git-2.26.2-64-bit.exe`. If I downgrade, it just works.
   - With `Git-2.27.0-64-bit.exe`, `winpty ./rg "之"` works while `./rg "之"` doesn't. `rg` is [ripgrep](https://github.com/BurntSushi/ripgrep).

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
Just from the context menu "Git Bash Here" so it's Bash.
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

   - Pre-built ripgrep can be downloaded from https://github.com/BurntSushi/ripgrep/releases/tag/12.1.1. We only need the `rg.exe`.
   - `test.txt` is just a UTF-8 encoded txt file which contains `之`.

```
# say I want to find 之 in test.txt
$ ./rg "之" test.txt
```
 - What did you expect to occur after running these commands?

```
test.txt
1:之
```

 - What actually happened instead?

```
test.txt
1:銋?[0m
```

**Comment by PhilipOakley** [comment]
Was any of the output (before and after) colourised?

Did you try with both terminal types (in case the newer term device has another nuance) 
the `[0m` is probably a terminal code, so..

**Comment by dscho** [comment]
The underlying issue is most likely the same as for https://github.com/msys2/MSYS2-packages/issues/1974. I will upgrade the MSYS2 runtime to pick up the fixes of Cygwin v3.1.5 tomorrow, build a portable Git and will ask you to test.

**Comment by dscho** [comment]
Never mind, I just confirmed that the underlying bug appears to be present in Cygwin v3.1.5, still.

**Comment by dscho** [comment]
Seems that there is a work-around: `cmd //c chcp 65001`, but I think we have a good grasp on https://github.com/msys2/MSYS2-packages/issues/1974 and once that is resolved, this here bug will be fixed, too.

**Comment by dscho** [comment]
Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by jfcherng** [comment]
> Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

I can confirm `PortableGit-prerelease-2.28.0.windows.1-51-g87c86a26de-20200923135803-64-bit.7z.exe` works on my side.

**Comment by dscho** [comment]
Hooray!
