### ISSUE TITLE
Cherry Pick failed - failed to restrict file handles

### ISSUE THREAD

**Issue by shivam-kmr** [git-for-windows/git#2650]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.836]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git cherry-pick <commitid>
Performing inexact rename detection: 100% (176292/176292), done.
warning: failed to restrict file handles (1455)

handle #0: 0000000000000190 (type 2, handle info (1) 0
handle #1: 00000000000001c0 (type 3, handle info (1) 1
handle #2: 0000000000000434 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: 'prepare-commit-msg' hook failed
fatal: cherry-pick failed

 - What did you expect to occur after running these commands?

cherry-pick success

 - What actually happened instead?

cherry-pick failed

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by dscho** [comment]
@shivam-kmr can you provide precise instructions how to reproduce the problem? I ask because `git cherry-pick` works over here, without the indicated error message.

>  warning: failed to restrict file handles (1455)

Of course, this indicates [`ERROR_COMMITMENT_LIMIT`](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-) which says:

> The paging file is too small for this operation to complete.

so your setup might just have way too many files, or something.

**Comment by dscho** [comment]
> so your setup might just have way too many files, or something.

Does it, @shivam-kmr?

**Comment by shivam-kmr** [comment]
I am afraid that I cannot provide more precise information on that! 
FYI: My setup has too many files but that should be fine. ( git can and should handle that. )
Though I have faced this issue only 2-3 times and have noticed that when I change branch frequently and it is a big commit which includes multiple changes in different files/projects.

**Comment by dscho** [comment]
> Hi @dscho ,
> I am afraid that I cannot provide more precise information on that! 
> FYI: My setup has too many files but that should be fine. ( git can and should handle that. )
> Though I have faced this issue only 2-3 times and have noticed that when I change branch frequently and it is a big commit which includes multiple changes in different files/projects this issue occurs.

I am afraid that this is too little to allow anybody else to help you. Either you provide more precise information (figuring out when exactly this happens) or do the entire investigation yourself.

And yes, Git should be able to handle large data. Clearly it does not! And if you won't help, the bug is unlikely to be diagnosed properly, let alone be fixed.

Sorry to be bearer of bad news, but with that scarce bits of information provided in this report, it's just too frustrating on all sides.

**Comment by dscho** [comment]
Closing as stale.
