### ISSUE TITLE
node stdout is not a tty

### ISSUE THREAD

**Issue by albertosantini** [git-for-windows/git#2651]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

`PortableGit-2.27.0-64-bit.7z.exe`

$ git --version --build-options

```
git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

`Windows 10 1909`

$ cmd.exe /c ver

```
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Portable installation
```

### Details

 - Which terminal/shell are you running Git from? 

`C:\git\bin\bash.exe --login -i` from command prompt

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ node -v | cut -c2-8
stdout is not a tty
```
 - What did you expect to occur after running these commands?

```
$ node -v | cut -c2-8
12.17.0
```

 - What actually happened instead?

`stdout is not a tty` is displayed

I read from Git for Windows v2.27.0 Release Notes (https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

```
Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact 
correctly with MinTTY only when called through winpty (e.g. the Python console needs to be 
started as winpty python instead of just python).
```
And from Git for Windows 2.27.0 release:

```
This release comes with a Git Bash that optionally uses Windows-native pseudo consoles. 
Meaning: finally, Git Bash can accommodate console programs like node.exe, Python or PHP, 
without using the winpty helper (see Known Issues). Note that this is still a very new feature 
and is therefore known to have some corner-case bugs.
```

But `winpty` is added in `etc/profile.d/aliases.sh` creating `alias node='winpty node.exe'`.

```
$ node -v | cut -c2-8
stdout is not a tty
$ unalias node
$ node -v | cut -c2-8
12.17.0
```

As quick workaround I added `unalias node`  in my `.profile` file, but I was wondering if we need to remove those aliases in `aliases.sh`?

**Comment by rimrul** [comment]
That option is still experimental, disabled by default, disanled in portable and requires Windows 10 with the spring 2018 update (1803) so we can't just drop those aliases yet and probanly can't drop them for the next couple of years.

What we could do though, is introduce a wrapper script that checks for `MSYS=enable_pcon` (pseudo console support available) and `if [ -t 1]` (stdout is not a tty, the issue you encountered) before then calling those commands with/without winpty accordingly.

**Comment by dscho** [comment]
The quickest workaround is to call `node.exe` (_with_ the `.exe` suffix). That will side-step the alias.

**Comment by albertosantini** [comment]
I see. Thanks for the details.

**Comment by dscho** [comment]
@albertosantini I do hope that the pseudo console support stabilizes quickly. (But it might be a while; the first Cygwin version that had it came out last year, and they ran through 5 patch versions, the most recent came out yesterday.)

**Comment by jakub-g** [comment]
Hi, I just came across this. Thanks for the explanations. As far as I can tell this happens with default settings after upgrading.

Do you not consider the discrepancy between `node` and `node.exe` as a bug?

(Just for info, it took me a while to understand the issue, and that `node.exe` behaves differently.)

**Comment by dscho** [comment]
> (Just for info, it took me a while to understand the issue, and that `node.exe` behaves differently and that it comes from upgrading git. I guess many people could be affected by this behavior change.)

To make sure, the difference in behavior stems from the POSIX emulation provided by the MSYS2 runtime, i.e. what Git Bash is made to believe is a Unix-style pseudo terminal. _That_ changed, and that is what `winpty` (which is what that `node` alias uses to pretend to `node.exe` that we're running in a CMD window) is not handling gracefully.

**Comment by dscho** [comment]
> (Just for info, it took me a while to understand the issue, and that `node.exe` behaves differently and that it comes from upgrading git. I guess many people could be affected by this behavior change.)

To make sure, the difference in behavior stems from the POSIX emulation provided by the MSYS2 runtime, i.e. what Git Bash is made to believe is a Unix-style pseudo terminal. _That_ changed, and that is what `winpty` (which is what that `node` alias uses to pretend to `node.exe` that we're running in a CMD window) is not handling gracefully.
