### ISSUE TITLE
Typo in 2.27.0 installer 

### ISSUE THREAD

**Issue by jeanfrancoislarente** [git-for-windows/git#2652]
Typo in "Choose default behavior of `git pull`" screen

![image](https://user-images.githubusercontent.com/5884676/83511106-1e64d700-a49c-11ea-955f-71e71a41923d.png)

**Comment by dscho** [comment]
Thank you for the report, and thanks to @shanegrueling for fixing the issue!

**Comment by jeanfrancoislarente** [comment]
Quick turnaround!

**Comment by dscho** [comment]
> Quick turnaround!

By another first-time contributor, no less!

**Comment by Zenahr** [comment]
Still prevalent.

Installed on the 17th July 2020 on a Windows 10 (64bit) machine using [this link](https://git-scm.com/download/win)
[Direct Link](https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/Git-2.27.0-64-bit.exe)

### Screenshot:
![image](https://user-images.githubusercontent.com/47085752/87817132-afcfb300-c868-11ea-9fda-d07b57be81ca.png)

**Comment by rimrul** [comment]
That's the 2.27.0 Installer. The fix isn't in that one. It is in the snapshots, the 2.28.0-rc0 pre-release and will be in the 2.28.0 release.
