### ISSUE TITLE
update-git-for-windows: Minor Typo in Dialog Box During Installation

### ISSUE THREAD

**Issue by Rob-S** [git-for-windows/git#2657]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19631.1]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: C:\Program Files\IDM Computer Solutions\UltraEdit\uedit64.exe
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

n/a

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git update-git-for-windows
```
 - What did you expect to occur after running these commands?

Git for Windows is updated.

 - What actually happened instead?

Git for Windows was updated. There was a minor typo in one of the dialog boxes. For the "default behavior of 'git pull'" the last option is "Only ever fast-forard". The last word should be "fast-forward".

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by Rob-S** [comment]
![Annotation_2020-06-02_160440](https://user-images.githubusercontent.com/323132/83569929-da4cf300-a4ea-11ea-8491-8e9579662dfa.png)

**Comment by dscho** [comment]
Thank you for the bug report. This has been fixed already in https://github.com/git-for-windows/build-extra/pull/291 (and reported in https://github.com/git-for-windows/git/issues/2652, https://github.com/git-for-windows/git/issues/2654 and in https://github.com/git-for-windows/git/issues/2656).
