### ISSUE TITLE
curl not using schannel

### ISSUE THREAD

**Issue by bbodenmiller** [git-for-windows/git#2658]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1158]
(c) 2018 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using custom CA installed to system cert store

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
curl https://internalwebsite.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.```

 - What did you expect to occur after running these commands?

Load HTTPS resource and use local cert store

 - What actually happened instead?

Error as shown. Does not use local cert store. https://curl.haxx.se/docs/sslcerts.html says curl can use Schannel but does not appear it is.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Can you repeat the call after setting the environment variable `GIT_CURL_TRACE=1`, and then see whether you find clues in that output?

**Comment by rimrul** [comment]
Our `libcurl` supports switching the SSL backend, but I don't see a flag for `curl.exe` to do so. If you need a `curl.exe` that runs on `Schannel` you'll probably need to get that `curl.exe` from somewhere else. If you just need `git` to use `Schannel`, you can set the `http.sslBackend` config option to `schannel`.

**Comment by dscho** [comment]
Oh! I missed that it was `curl.exe`... there are several ways to specify the TLS backend, one of them being [`CURL_SSL_BACKEND`](https://ec.haxx.se/usingcurl/usingcurl-tls#multiple-tls-backends).

**Comment by dscho** [comment]
And note that having `curl.exe` shipped as part of Git for Windows is more of a side effect than a supported function.

MinGit, for example, does not include it, so all your Git hooks/aliases relying on `curl` being in the `PATH` are assuming incorrectly.

**Comment by bbodenmiller** [comment]
I get that it may be a byproduct but frankly at this point many rely on it. How can we make installer set appropriate backend based on the options user selects?

**Comment by dscho** [comment]
The installer *already* sets the appropriate backend, _for Git operations_.

It does not strike me as a wise idea to try configuring _curl_ via _Git for Windows'_ installer. Where would that take us? Configuring OpenSSH, too? GPG? Perl? Subversion???

It's a rabbit hole, a poisonous one, to enter.

**Comment by kevin-a-myers** [comment]
One of the specific reasons I pick the git-for-windows distribution is for the simple MingW deployment. Agree needing to update all the tools it contains is a bad precedent.

Would it be possible to use the `Schannel` capability to create a virtual file located at MingW64\ssl\certs\ca-bundle so all the MingW packaged tools that use the 'OS defaults' fall back to the windows certificate store?

This would solve the same problem for git lfs if the project hasn't already addressed that.

**Comment by dscho** [comment]
> This would solve the same problem for git lfs if the project hasn't already addressed that. That would address the requested functionality while being a reasonable line in the sand.

The reason why we delete `ssl/certs/ca-bundle.crt` when Secure Channel was selected is _specifically_ to support Git LFS: if that file is present, it will use it, otherwise fall back to the Windows Certificate Store.

> One of the specific reasons I pick the git-for-windows distribution is for the simple MingW deployment.

That's cool for you. Not so cool for me, as you try to put a bigger maintenance burden on my shoulders than I already have.

> Would it be possible to use the `Schannel` capability to create a virtual file located at MingW64\ssl\certs\ca-bundle so all the MingW packaged tools that use the 'OS defaults' fall back to the windows certificate store?

That's not how cURL works. It has to decide way before it accesses that bundle which TLS backend it wants to use.

**Comment by kevin-a-myers** [comment]
The MingW distribution installed by git-for-windows uses that specific file for the included cURL application and various other tools absent other configuration. I don't know if it is officially subject to change but the path is fairly standard and it has been stable for my 2 years of my using git-bash. Are you certain the proposed feature enhancement would add a substantial amount of maintenance after initial implementation?

Just trying pitching an idea that might improve the product.... I really don't mind manually adding certs to that file but it would be nice as the concept of a virtual file would facilitate other tools that don't support `schannel` also using the windows certificate store.

**Comment by bbodenmiller** [comment]
Looks like this may be a `curl` issue since get same issue outside of git-for-windows: https://github.com/curl/curl/issues/5515
