### ISSUE TITLE
git push (simple/upstream) fails on branches containing a slash

### ISSUE THREAD

**Issue by radioflash** [git-for-windows/git#266]
Pushing a tracking branch in "simple" or "upstream" mode (push.default) does NOT work if the name of the branch contains slashes (nothing is pushed). Example:

Create and push a tracking branch containing a slash in it's name:
```bash
git checkout -b x/y
git push -u origin x/y
```

Commit something:
```bash
git commit -am "something"
```

Git realizes that there are changes that need to be pushed:
```bash 
git status
```
> On branch x/y
> Your branch is ahead of 'origin/x/y' by 1 commit. [...]

But pushing does nothing! Neither with 'simple' nor with 'upstream' push.default!

```bash 
git push
```
> Everything up-to-date

The following command actually works:

```bash 
git push origin head
```

Is this behavior a bug? If not: What is the intention behind this?

**Comment by dscho** [comment]
As I am currently busy with other things, would you mind testing with [Vagrant](https://github.com/git-for-windows/git/wiki/Vagrant) (to find out whether the bug is Windows-specific, or whether it should be reported to the Git mailing list instead)?

**Comment by radioflash** [comment]
Nevermind this.

Turns out that the IDE had set up various remote.*.push configurations, which led to push.default being ignored and newly created branches from the cmdline not being pushed.

Sorry for the noise.
