### ISSUE TITLE
Git installer has typo - "Only ever fast-forard"

### ISSUE THREAD

**Issue by BlueBayliss** [git-for-windows/git#2660]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
2.27.0 x64
It was during the installation of this version that I saw the typo
```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 1809 x64
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1158]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git update-git-for-windows
```
 - What did you expect to occur after running these commands?

"Choose the default behavior of \`git pull\`" options page to give the option "Only ever fast-forward"

 - What actually happened instead?
There was a small typo in the installer
"Choose the default behavior of \`git pull\`" options page gave the option "Only ever _fast-forard_"

![git-fast-forard](https://user-images.githubusercontent.com/5847318/83648477-b685bd80-a57b-11ea-972c-47906f766903.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This was not specific to a repository

**Comment by scara** [comment]
From https://github.com/git-for-windows/git/issues/2657#issuecomment-637811883:
>Thank you for the bug report. This has been fixed already in git-for-windows/build-extra#291 (and reported in #2652, #2654 and in #2656).

HTH,
Matteo
