### ISSUE TITLE
Not great error message for creating branch X/Y over pruned X

### ISSUE THREAD

**Issue by will-bartlett** [git-for-windows/git#2667]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.836]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\bug>git init remote
Initialized empty Git repository in C:/bug/remote/.git/

C:\bug>cd remote

C:\bug\remote>echo test > test.txt

C:\bug\remote>git add test.txt

C:\bug\remote>git commit -m "test"
[master (root-commit) 8349fac] test
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt

C:\bug\remote>git checkout -b X
Switched to a new branch 'X'

C:\bug\remote>cd ..

C:\bug>git clone remote local
Cloning into 'local'...
done.

C:\bug>cd local

C:\bug\local>git status
On branch X
Your branch is up to date with 'origin/X'.

nothing to commit, working tree clean

C:\bug\local>git checkout master
Switched to a new branch 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.

C:\bug\local>cd ..\

C:\bug>cd remote

C:\bug\remote>git checkout master
Switched to branch 'master'

C:\bug\remote>git branch -D X
Deleted branch X (was 8349fac).

C:\bug\remote>git checkout -b X/Y
Switched to a new branch 'X/Y'

C:\bug\remote>git checkout master
Switched to branch 'master'

C:\bug\remote>echo "test2" > test2.txt

C:\bug\remote>git add test2.txt

C:\bug\remote>git commit -m "test2"
[master b3f5679] test2
 1 file changed, 1 insertion(+)
 create mode 100644 test2.txt

C:\bug\remote>cd ..\local

C:\bug\local>git fetch
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 257 bytes | 18.00 KiB/s, done.
From C:/bug/remote
   8349fac..b3f5679  master     -> origin/master
error: cannot lock ref 'refs/remotes/origin/X/Y': 'refs/remotes/origin/X' exists; cannot create 'refs/remotes/origin/X/Y'
 ! [new branch]      X/Y        -> origin/X/Y  (unable to update local ref)

C:\bug\local>git pull
error: cannot lock ref 'refs/remotes/origin/X/Y': 'refs/remotes/origin/X' exists; cannot create 'refs/remotes/origin/X/Y'
From C:/bug/remote
 ! [new branch]      X/Y        -> origin/X/Y  (unable to update local ref)

C:\bug\local>git status
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean

C:\bug\local>git fetch -p
From C:/bug/remote
 - [deleted]         (none)     -> origin/X
   (refs/remotes/origin/HEAD has become dangling)
 * [new branch]      X/Y        -> origin/X/Y

C:\bug\local>git pull
Updating 8349fac..b3f5679
Fast-forward
 test2.txt | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 test2.txt
```
 - What did you expect to occur after running these commands?

I expected the pull to successfully bring master up to origin/master even though I couldn't fetch origin/X/Y.
I hoped to see a better error message that let me know that "git fetch -p" was sufficient to resolve the issue. Indeed, it seems like "git fetch -p" will always resolve the issue, because X/Y cannot be pushed to remote unless X is first deleted.

 - What actually happened instead?

unclear error message, failed git pull

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Steps show how to repro on local repository.

**Comment by PhilipOakley** [comment]
If I remember correctly when you clone within the local file system you have hard file links between the two (to save space). 
This could mean that the remote's X branch is also the local X branch (I've not checked the details).

Check the clone man page for the use of the `file://path` way of keeping the two object stores separate, along with any confusion about which refs are which.

**Comment by will-bartlett** [comment]
The behavior is the same for a remote clone. I encountered this behavior with a remote private repository (that I cannot share) and only used a local clone for the repro. The underlying issue is that when .git/refs/.../X is a file, and you try to mkdir .git/refs/.../X/ and then write a file at .git/refs/.../X/Y, the mkdir fails.

**Comment by PhilipOakley** [comment]
> The underlying issue is that when `.git/refs/.../X` is a file, and you try to `mkdir .git/refs/.../X/` and then write a file at `.git/refs/.../X/Y`, the mkdir fails (at least, on Windows).

Ah, ok. I thought that the command sequence deleted the `.git/refs/.../X` branch ref first. 

Because Git is designed for Linux it is **not possible** to have both a file `.git/refs/.../X` and a directory `.git/refs/.../X/<anything>`. That is called a 'D/F' conflict and is a limitation of the *NIX file system semantics, and it's not going to change (a directory being a special type of 'file' in the same namespace hence the collision). 

If the `.../X/Y` is a branch on a remote repo, and  `.../X` is a branch in your local repo, then it may be a mental map issue thinking that the remote branch needs to be brought into the local repo using it's same name. That's not necessary and as seen, it fails..

The 'remote tracking branch' for that remote repo will have a branch name `.git/refs/<remote>/.../X/<something>` (note the extra remote name at the beginning), so is already in a separate filesystem 'namespace', so you can simply use that name when starting a new branch with a different non-conflicting name. (I guess you know this but, worth mentioning).

The need to have a different local branch name to the remote is moderately common when different upstream remotes both have a `master` branch, and they are different!

**Comment by dscho** [comment]
> error: cannot lock ref 'refs/remotes/origin/X/Y': 'refs/remotes/origin/X' exists; cannot create 'refs/remotes/origin/X/Y'

This generally means that you have to run `git remote prune origin`.

Of course, nothing in the error message says _that_. Which means that this is a valid report, it just needs to go [to the Git mailing list](mailto:git@vger.kernel.org) (no HTML part, please, otherwise your mail _will_ bounce), as this is not specific to Windows.

**Comment by PhilipOakley** [comment]
A short note covering my quick look at the code.

The message part "exists; cannot create" seems to be one of two that are in `refs_verify_refname_available(` in \git\refs.c #L2070
