### ISSUE TITLE
Installation: "Git Pull Behavior Option" always set to merge

### ISSUE THREAD

**Issue by TomGit27** [git-for-windows/git#2668]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 Bit

```
$ git --version --build-options

```
git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

```
Microsoft Windows [Version 10.0.18363.720]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

```
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

### Details

I selected "Only ever fast-forward" for my installation. However the value that get's persisted in "C:\Program Files\Git\etc\install-options.txt" is always:
Git Pull Behavior Option: Merge

The value written to ".gitconfig" is correct:
[pull]
	ff = only 

This does not affect the current installation. It will affect the next installation. In case "Only show new options" is checked, the user won't notice that the install will set "merge" as the new option. Thus with the next release of git, the setting will be wrong without the user realizing this.

**Comment by rimrul** [comment]
Good catch. Your analysis is almost correct. It's just the fast-forward only option that does not get recorded correctly. We're accidentally checking for the wrong radio button in http://github.com/git-for-windows/build-extra/blob/master/installer/install.iss#L3133

**Comment by TomGit27** [comment]
Glad to hear you were able to figure this out quickly. Thanks!

**Comment by rimrul** [comment]
I'll prepare a fix later today.
