### ISSUE TITLE
Unable to set system config core.editor

### ISSUE THREAD

**Issue by Bertaz** [git-for-windows/git#2669]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```bash
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```powershell
$ cmd.exe /c ver

Microsoft Windows [Versione 10.0.18363.836]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```bash
# One of the following:
> type "D:\Program Files\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: "D:\Program Files\Sublime Text 3\subl.exe" -w
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
git update-git-for-windows
```
 or if already updated
```bash
Git-2.27.0-64-bit.exe
```
 - What did you expect to occur after running these commands?

Update/reinstall git for windows without problems

 - What actually happened instead?

Unable to set system config "core.editor"
![Error](https://user-images.githubusercontent.com/44445647/83851522-ca175c80-a712-11ea-9259-c1da46979d7f.jpg)

My system config is:
```gitconfig
[http]
	sslBackend = schannel
[diff "astextplain"]
	textconv = astextplain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[credential]
	helper = manager
[core]
	autocrlf = true
	fscache = true
	symlinks = true
	editor = \"D:\\\\Program Files\\\\Sublime Text 3\\\\subl.exe\" -w
[pull]
	rebase = false
```
After the installation, core.editor gets changed from any valid value to: `\"D:\\\\Program Files\\\\Sublime Text 3\\\\subl.exe\" -w`
Originally set to: `'D:\\Program Files\\Sublime Text 3\\subl.exe' -w`

Sublime text always works without any problem, but I am receiving an error every update

**Comment by PhilipOakley** [comment]
Where is your system config located, and does it have any permission or path (server) aspects that may be 'interesting'? (e.g. you have a corporate style home drive mapping)

If you are able to build a local Git installer (see the Contribute button on the Git for Windows home page) then you could instrument the error message with a few more of those details, which could have wider benefit for the community.

**Comment by dscho** [comment]
> ```shell
> Custom Editor Path: "D:\Program Files\Sublime Text 3\subl.exe" -w
> ```

Any reason why this is hard-coded as a `CustomEditor`? We do have pre-configured `SublimeText` option...

In any case, I just downloaded the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), tried with both options, and it worked in both cases.

Maybe you can re-run the installation by starting the installer from the command-line, with the `/LOG=<filename>` option, then study the generated log file to figure out what is going on?

**Comment by Bertaz** [comment]
> Where is your system config located, and does it have any permission or path (server) aspects that may be 'interesting'? (e.g. you have a corporate style home drive mapping)

System config is in `D:/Program Files/Git/etc/gitconfig`
No interesting path and permissions should be default.
```cmd
λ icacls "D:\Program Files\\"
D:\Program Files\
                  CREATOR OWNER:(OI)(CI)(IO)(F)
                  NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                  NT AUTHORITY\SYSTEM:(M)
                  BUILTIN\Administrators:(OI)(CI)(IO)(F)
                  BUILTIN\Administrators:(M)
                  BUILTIN\Users:(OI)(CI)(IO)(GR,GE)
                  BUILTIN\Users:(RX)
                  NT SERVICE\TrustedInstaller:(CI)(IO)(F)
                  NT SERVICE\TrustedInstaller:(F)
                  APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(RX)
                  APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(OI)(CI)(IO)(GR,GE)
                  APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(RX)
                  APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(OI)(CI)(IO)(GR,GE)
λ icacls "D:\Program Files\Git\etc\\"
D:\Program Files\Git\etc\
                  BUILTIN\Users:(OI)(CI)(M)
                  BUILTIN\Administrators:(I)(F)
                  CREATOR OWNER:(I)(OI)(CI)(IO)(F)
                  NT AUTHORITY\SYSTEM:(I)(F)
                  NT AUTHORITY\SYSTEM:(I)(OI)(CI)(IO)(F)
                  BUILTIN\Administrators:(I)(OI)(CI)(IO)(F)
                  BUILTIN\Users:(I)(RX)
                  BUILTIN\Users:(I)(OI)(CI)(IO)(GR,GE)
                  NT SERVICE\TrustedInstaller:(I)(F)
                  NT SERVICE\TrustedInstaller:(I)(CI)(IO)(F)
                  APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
                  APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(OI)(CI)(IO)(GR,GE)
                  APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(I)(RX)
                  APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(I)(OI)(CI)(IO)(GR,GE)
icacls "D:\Program Files\Git\etc\gitconfig"
D:\Program Files\Git\etc\gitconfig
                  BUILTIN\Users:(I)(M)
                  BUILTIN\Administrators:(I)(F)
                  NT AUTHORITY\SYSTEM:(I)(F)
                  APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
                  APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(I)(RX)
```
> > ```shell
> > Custom Editor Path: "D:\Program Files\Sublime Text 3\subl.exe" -w
> > ```
> 
> Any reason why this is hard-coded as a `CustomEditor`? We do have pre-configured `SublimeText` option...

Don't know, maybe an old version had a problem with my non default location of Sublime Text. Tried using the pre configured option now and it works without errors.
Still using a custom editor shouldn't throw errors
> 
> In any case, I just downloaded the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), tried with both options, and it worked in both cases.
> 
> Maybe you can re-run the installation by starting the installer from the command-line, with the `/LOG=<filename>` option, then study the generated log file to figure out what is going on?

Can't find anything particular, maybe it's an unescaped quotation marks problem
[log.txt](https://github.com/git-for-windows/git/files/4766101/log.txt)

**Comment by dscho** [comment]
>                           Unable to set system config "core.editor":=""D:\Program Files\Sublime Text 3\subl.exe" -w": exit code 1

This looks a bit suspicious, indeed.

I wonder whether the problem lies with the funny way `cmd.exe` dequotes command-lines. I could imagine, for example, that this patch might fix things:

```diff
diff --git a/installer/install.iss b/installer/install.iss
index 409de9b45..71375626b 100644
--- a/installer/install.iss
+++ b/installer/install.iss
@@ -708,7 +708,7 @@ begin
             LogError('Unable to unset system config "'+Key+'": exit code '+IntToStr(i)+#10+#13+ReadFileAsString(OutPath)+#10+#13+'stderr:'+#10+#13+ReadFileAsString(ErrPath));
             Result:=False
         end
-    end else if Exec(ExpandConstant('{cmd}'),'/C .\{#MINGW_BITNESS}\bin\git.exe config --system '+ShellQuote(Key)+' '+ShellQuote(Value)+' >'+#34+OutPath+#34+' 2>'+#34+ErrPath+#34,
+    end else if Exec(ExpandConstant('{cmd}'),'/C ".\{#MINGW_BITNESS}\bin\git.exe config --system '+ShellQuote(Key)+' '+ShellQuote(Value)+'" >'+#34+OutPath+#34+' 2>'+#34+ErrPath+#34,
                 AppDir,SW_HIDE,ewWaitUntilTerminated,i) And (i=0) then
         Result:=True
     else begin
```

Could you try that, please? 
1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `install.iss`
4. build a new installer via `sdk build installer`
5. verify that that installer works as expected?
6. open a PR?

**Comment by gabyx** [comment]
I have exeactly the same problem with `Code.exe`

**Comment by gabyx** [comment]
maybe  I can try this

**Comment by dscho** [comment]
Closing as stale.
