### ISSUE TITLE
Auto-updater asks to update multiple times

### ISSUE THREAD

**Issue by darkain** [git-for-windows/git#2676]
I have a Windows Server environment where the local console is not logged into all that often. We use Git for various configuration files. When logging in after a Git for Windows update has been made available, the screen is flooded with these messages. I assume they're produced once a day. There have been times when the local console was not logged into for a few months, and there are 100+ of these to respond to.

All I ask is that the auto-updater notification checks to see if there is already a pending notification, and if there is, don't spawn another one. 

![image](https://user-images.githubusercontent.com/2524251/84180228-006b1980-aa3c-11ea-8f69-244a55515ab0.png)

**Comment by rimrul** [comment]
Duplicate of #2347. The windows scheduler does check [wether an instance of this task is already running](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss#L2513). Unless something in your environment kills processes in the chain, you shouldn't get multiple dialog boxes.

[`MultipleInstancesPolicy` should be supported on Windows Server 2008 and newer](https://docs.microsoft.com/en-us/windows/win32/taskschd/taskschedulerschema-multipleinstancespolicy-settingstype-element), so it should still work on windows server. What OS Version are you running?

**Comment by darkain** [comment]
This is on Windows Server 2008. I wasn't able to find the other open bug in my initial search. I'll close this as a dup. Thanks for the link!
