### ISSUE TITLE
fatal: invalid refspec '+refs/heads

### ISSUE THREAD

**Issue by michaellongge163** [git-for-windows/git#2679]
fatal: invalid refspec '+refs/heads/...:refs/remotes/lineage/...'
fatal: invalid refspec '+refs/heads/...:refs/remotes/aosp/...'
fatal: invalid refspec '+refs/heads/...:refs/remotes/lineage/...'
fatal: invalid refspec '+refs/heads/...:refs/remotes/lineage/...'
version 2.27

**Comment by rimrul** [comment]
There's a reason we provide an issue template.
This partial out put of some command isn't helpful. All I know from that is that you're trying to do something with android/lineageos source code.

What OS version are you running? What commands did you run? What shell did you run them in?

All these questions and some more are covered by our issue template. As it is, this issue does nothing to fix your problem.
