### ISSUE TITLE
Unable to open Git Bash CLI

### ISSUE THREAD

**Issue by kajal-thakur** [git-for-windows/git#2680]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options


** insert your machine's response here **
```I am using 64 bit
Git Version : 2.27.0

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```Windiws 8 Pro

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

 "C:\Program Files\Git\etc\install-options.txt"
``` "C:\Program Files\Git\etc\install-options.txt"

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**_I installed it as per the instruction from "https://gitforwindows.org/" this site. And click next till end and installed the software. But when am clicking on "GIT Bash" icon its not working. I am unable to open this software. So help me to resolve this issue._**

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I have installed Bash, CMD and  PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

None
[LICENSE.txt](https://github.com/git-for-windows/git/files/4756516/LICENSE.txt)

**Comment by dscho** [comment]
What Windows version are you running on? 32-bit, 64-bit? What are the install options?

**Comment by kajal-thakur** [comment]
Hello,

I'm using windows 64 but OS and when I installed the software I chose the
default settings that means I clicked only on 'next' button and then
finally clicked on 'finish'.

I hope this helps. Kindly resolve this issue as soon as possible.

Thanking you in advance.

**Comment by dscho** [comment]
You chose to not fill out any "insert here" blanks in the issue reporting template... all I tried was to ask again. It's actually important information. You answers are too vague to help, unfortunately.

**Comment by larrylau** [comment]
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
PortableGit-2.27.0-32-bit.7z.exe
```
$ git --version --build-options
```git version 2.27.0.windows.1
cpu: i686
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 4
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
$ cmd.exe /c ver
```
Microsoft Windows [版本 6.1.7601]
```
- mintty.exe.stackdump
```
Exception: STATUS_ACCESS_VIOLATION at eip=000707AC
eax=00000000 ebx=0045028B ecx=0028C5CC edx=00000000 esi=004A0410 edi=80000000
ebp=0028CB48 esp=0028C614 program=D:\PortableGit\usr\bin\mintty.exe, pid 1930, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028CB48  000707AC (80041240, 8004124A, 0028CD28, 6100AFA5)
0028CD28  6100AFA5 (00000000, 0028CD84, 61009DD0, 00000000)
0028CD84  610088B2 (00000000, 00000000, 00000000, 00000000)
End of stack trace
```

**Comment by gdh1995** [comment]
I also ran into a crash of mintty x64:

``` stackdump
Exception: STATUS_ACCESS_VIOLATION at rip=00180070B8B
rax=00000000000005A4 rbx=0000000180211F30 rcx=0000000180347BF8
rdx=0000000000000000 rsi=00000001802188E0 rdi=8000000080000000
r8 =00000000FFFFC498 r9 =00000000FFFFC670 r10=0000000000000000
r11=0000000000000246 r12=0000000180347BF8 r13=000000018022B8AC
r14=0000000000000002 r15=00000001004C8780
rbp=00000000FFFFC670 rsp=00000000FFFFC440
program=D:\Git\usr\bin\mintty.exe, pid 1014, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFC670  00180070B8B (000000002EC, 000FFFFE460, 00000000000, 00000000000)
000FFFFC670  001800759D3 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFC670  0018006E041 (000FFFFC000, 00100000000, 00000003000, 001004B345C)
000FFFFC670  00180045CC0 (00000000001, 000FFFFC63F, 001800C7718, 000FFFFCC80)
000FFFFC670  0018015AD54 (008000018B0, 0080003A530, 0080003A5A0, 00000000000)
000FFFFC6D0  0018013FC8B (008000018B0, 0080003A530, 0080003A5A0, 00000000000)
000FFFFC6D0  0010044E42A (00000000020, 8080808080808080, 0018004AE3E, 00180049D20)
000FFFFCCE0  0018004AEAA (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

Mintty always works if I open it from a plain CMD window by running `D:\Git\usr\bin\mintty.exe -`; while it **very often** fail if I run `/usr/bin/mintty.exe -` from a shell of bash.exe & conhost.

### steps to reproduce

``` cmd
R:\working\git2> set PATH=C:\Windows\System32

R:\working\git2> .\git-bash

R:\working\git2> set PATH=C:\Windows\System32

R:\working\git2> .\usr\bin\bash.exe
git2$ /usr/bin/mintty.exe -
git2$ ls mintty.exe.stackdump -l
-rw-r--r-- 1 gdh1995 197610 1372  6月 15 15:12 mintty.exe.stackdump
```

### versions
* Git for Windows x64 v 2.27.0.windows.1 (portable version)
* Win 10 1909 Professional+Education x64 (build 18363.900)

**Comment by dscho** [comment]
Could you test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), please? It has fixes that _might_ address this problem, too.

**Comment by larrylau** [comment]
> Could you test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), please? It has fixes that _might_ address this problem, too.

It's working.

**Comment by NathanGibbs3** [comment]
Had the same Issue on Windows 7 32 bit.
Installing the Snapshot for Thu, 18 Jun 2020 fixed it.
Thanks. :smile:
