### ISSUE TITLE
Segmentation fault error in VS Code on Windows 8.1

### ISSUE THREAD

**Issue by GYuriy** [git-for-windows/git#2685]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git-2.26.2-64-bit

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

After upgrading to version Git-2.27.0-64-bit.exe VS Code stopped launching the git bash terminal at all. Once I open a terminal in VS code it's just ...empty. Not able to type anything, the command line is not existing at all. I have downgraded to version 2.26.2. Terminal appeared back again but I'm getting Segmentation fault error when trying to run any command.
Fully re-installed git bash for windows
Fully re-installed vs code
Uninstall any other git/source control related software (tortoise, source tree, etc.)

Git bash for windows works fine outside VS Code

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**(Bash) terminal in VS Code**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

**Any**

 - What did you expect to occur after running these commands?

**At least something**

 - What actually happened instead?

**Segmentation fault error**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**On any repository, project, folder**

**Comment by dscho** [comment]
>  Once I open a terminal in VS code it's just ...empty.

How did you configure the terminal?

I have Windows 10, not 8.1, and it seems to work correctly here. I am using the [Shell launcher](https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher) extension with this config:

```json
    "shellLauncher.shells.windows": [
        {
            "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        },
        {
            "shell": "C:\\git-sdk-64\\bin\\bash.exe",
            "label": "Git SDK Bash"
        },
        {
            "shell": "C:\\Program Files\\Git\\bin\\bash.exe",
            "label": "Git Bash"
        },
        {
            "shell": "C:\\Windows\\System32\\cmd.exe",
            "label": "cmd"
        },
    ],
```

Other things you could try to investigate further:

- launch PowerShell instead, and then see whether `& "C:\Program Files\Git\bin\bash.exe" -li` works

- install [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon), run it, then try opening the crashing Git Bash, and see whether the Process Monitor event log provides any hints

- toggle the experimental "pseudo console support" option

I have a hunch that the underlying problem might be the pseudo console changes, as Windows 8.1 does not have pseudo console support.

**Comment by dscho** [comment]
> I have a hunch that the underlying problem might be the pseudo console changes, as Windows 8.1 does not have pseudo console support.

Oh, and you should be able to corroborate that suspicion by trying to run [Cygwin](https://cygwin.com).

**Comment by GYuriy** [comment]
@dscho  _How did you configure the terminal?_
I didn't. I have:
1) GFW (Git-2.21.0-64-bit) + Windows 10 + VS code. 
2) GFW (Git-2.27.0-64-bit) + Windows 10 + VS code.
3) GFW (Git-2.21.0-64-bit then Git-2.27.0-64-bit now Git-2.26.2-64-bit) + Windows 8.1+ VS code
Case 1 and 2 are working fine. I never ever had to configure something or use additional extensions in VS code.
The same was for case 3. I was a happy man. However, 2 weeks ago I started getting an error (actually I believe it was a warning) while performing `git push` (and some other commands). Warning said:
`git fatal: HttpRequestException encountered. An error occurred while sending the request.`
Everything seemed to work fine (I guess...) except this warning message was showing up. 
So found a solution saying I just need to upgrade to the latest version. And here where's my nightmare started:
I have upgraded GFW to 2.27 in VS code was not showing terminal at all
Then I have downgrade to 2.26 and segmentation fault started showing up.
Now I don't want to go back to 2.21 since it's showing fatal error while pushing or checking out branches and I assume it can mess up source control at some point which can be a disaster.

Also, the `segmentation fault` generates the `bash.exe.stackdump`. Can it be useful?

**Comment by dscho** [comment]
When I run the terminal in VS Code, PowerShell (or was it CMD?), not Git Bash.

**Comment by GYuriy** [comment]
@dscho here how I understood your suggestion about `& "C:\Program Files\Git\bin\bash.exe" -li`:
I changed the VS Code terminal to PowerShell. Then I run `& "C:\Program Files\Git\bin\bash.exe" -li`. After this VS Code terminal changed to Git Bash which is not working with the same error as previously. This command  `& "C:\Program Files\Git\bin\bash.exe" -li` is simply switching the current VS Code terminal to Git Bash. I'm using Git Bash outside the VS Code for now but it's really frustrating and slows me down.
From other suggestions, I found regarding segmentation fault:
I tried turning off the firewall and antivirus. Also added git bash and VS Code to antivirus exclude list. Tried to launch the VS Code as an administrator

**Comment by dscho** [comment]
The segmentation fault might be related to the pseudo console support. If you re-install Git for Windows with that experimental option enabled, does it work?

**Comment by GYuriy** [comment]
@dscho I'll try. Thank you

**Comment by GYuriy** [comment]
@dscho as far as I understand the experimental option exists starting from Git-2.27.0-64-bit. I remove Git-2.26.2-64-bit and installed 2.27.0 with experimental option ON but the results were the same as previous: VS Code can't launch terminal with gitbash 2.27.0

**Comment by dscho** [comment]
So this has nothing to do with VS Code? What about `...\Git\usr\bin\bash.exe` (note the `usr`)?

**Comment by GYuriy** [comment]
@dscho `usr/bin/bash.exe` gives the same error (different versions). However `Git/git-bash.exe` is working fine (I'm using it for the past 6 days since the issue started occurring). Just curious how it's possible that `\Git\usr\bin\bash.exe` and `\Git\bin\bash.exe` are throwing errors and `Git/git-bash.exe` is working just fine... 
Also, I tried different portable versions, and behavior is the same: git-bash.exe is working and `bin/...` and `usr/...` are not. I believe something is blocking it on my side but I didn't find anything the process monitor. I was shooting in the dark by turning off antivirus and removing the read-only flag from the folder.

**Comment by dscho** [comment]
It might be an environment variable that is set in VS Code but not when you run `git-bash.exe`? Sorry, I'm really stabbing in the dark now...

**Comment by GYuriy** [comment]
@dscho I understand how weird this situation is.  I already looking towards moving to win10 tbh... Regarding your last suggestion:
When I said that `git-bash.exe` is working I meant that it's working outside VS Code (that's how I'm using it for the past week). VS Code is acting properly: it tries to launch the `\\Git\\bin\\bash.exe` but it's not working (I said previously it throws "Segmentation fault" even outside the VS Code). 
Do you still want me to dig towards VS Code env variables (as to me this issue has nothing to do with VS Code anymore)?

**Comment by WebDevRock** [comment]
@GYuriy I don't think the issue lies with your operating system as I'm here after googling for answers to the same issue on Windows 10. I'll be watching this thread and if I find a solution before you I'll let you know

**Comment by dscho** [comment]
@GYuriy yes, it is weird all right, but I still would like to find a way to fix it.

Last week I upgraded Git for Windows' SDK to use a newer MSYS2 runtime that claims to fix a couple of bugs that _might_ be related to this. Could you try with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?

I know this is frustrating, and I would love to have more time to help, but I don't, so I can only hope that Cygwin's excellent developers pre-emptively fixed the bug you encountered.

**Comment by GYuriy** [comment]
@dscho, unfortunately, it didn't help (tried with the snapshot you posted and the next one I found in this link)

**Comment by dscho** [comment]
> > I have a hunch that the underlying problem might be the pseudo console changes, as Windows 8.1 does not have pseudo console support.
> 
> Oh, and you should be able to corroborate that suspicion by trying to run [Cygwin](https://cygwin.com).

@GYuriy did you get a chance to try that?

**Comment by GYuriy** [comment]
@dscho well. I guess so... So I have installed the Cygwin64 Terminal but I'm not pretty sure what my next steps should be...
Should I specify it as a default terminal in VS Code?
Sorry for forgetting to update you on this step.

**Comment by dscho** [comment]
Well, you could try to set up VS Code to call Cygwin instead of Git Bash, and if that reproduces the issue, I would _hope_ that Cygwin can eventually fix it (and Git Bash would inherit it).

If the problem cannot be reproduced that way, at least we know that the problem is either in MSYS2's or in Git for Windows' part of the patches on top of the Cygwin runtime. That would not buy us much because it would still require a volunteer to investigate further, and those volunteers seem to be scarce.

**Comment by dscho** [comment]
Closing as stale.
