### ISSUE TITLE
git config command ignores explicit windows file permissions

### ISSUE THREAD

**Issue by mriddell95** [git-for-windows/git#2686]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.1365]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I know of I have tried this on multiple machines

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Have tested in both CMD and Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global user.name = "test"
git config --list --show-origin
```
 - What did you expect to occur after running these commands?

Before running the git config command I removed folder inheritance on the file to make the file have explicit windows permissions. I then gave the file read only access to the user running the git config command (and all groups which the user is apart of). I expected this command to fail resulting in a permission denied error.  But still being able to read the file with the command git config list

 - What actually happened instead?

What actually happens is that git config is still allowed to modify the file and ignores the explicit file permissions set on the file and only uses the inherited permissions. After the git config command is successful it reverts the file permissions back to using inherited permissions of the parent directory. 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

NA

**Comment by dscho** [comment]
I think the reason is that we lock the config file by creating a new file with `.lock` appended to the file name (which is permitted), then deleting the original config file (which is also permitted) and then renaming the `.lock` file.

This is not actually a Windows-specific issue. I tested this in WSL:

```sh
$ >test-config

$ chmod a-w test-config

$ ls -l test-config
-r--r--r-- 1 me work 0 Jun 15 03:55 test-config

$ git config -f test-config core.hello world

$ echo $?
0
```

Could you please take this issue to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently)?
