### ISSUE TITLE
Release exe version for git 2.5.0 for windows

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#269]
Hi looking at tags the recent version to be released is 2.5.0 but I carnt find the exe setup. If you have time could you release them please.

**Comment by nalla** [comment]
If you can not wait for a maintained release, then download the SDK and release it yourself. See https://github.com/git-for-windows/git/wiki/Making-an-installer.

Since this is not an issue at all - I'll close it.

**Comment by dscho** [comment]
@paladox please refrain from opening pure "I wish..." tickets in the future. Remember: this issue tracker is intended to list bugs in our projects. Some of us are hard at work to get Git for Windows 2.x out of the door, and distracting us with tickets like this here just takes away from working on the real issues. Thanks for your understanding.

**Comment by linquize** [comment]
Why 2.5 is smaller than 2.4 a lot? just 29MB vs 46MB

**Comment by dscho** [comment]
@linquize https://github.com/git-for-windows/git/issues/262
