### ISSUE TITLE
Renaming 'Git' to something more inclusive.

### ISSUE THREAD

**Issue by johnmanko** [git-for-windows/git#2690]
All of my neighbors make fun of me because I use Git for my daily work.  They keep calling me a stupid git, foolish and worthless.  I didn't know what they meant until I looked up the term, which is very offensive.

All day long I cry at my desk because of the hurtful comments. I've literally had to replace my keyboard twice because they've been ruined by my tears.  I'm so emotional just typing this now.

I request that we rename 'git' to something more inclusive.  Maybe 'RainbowUnicornHappy'?  The word 'git' offends me.

Discuss.

**Comment by Paultergeist** [comment]
`man git` says that git is the stupid content tracker. I find it offensive to
1. Smart people. Why should smart people use the stupid content tracker?
2. Content. Content deserves to be tracked by smart tracker.
Should I create another issue to make ~git~ RainbowUnicornHappy smarter or will it be handled together with renaming?

**Comment by johnmanko** [comment]
> `man git` says that git is the stupid content tracker. I find it offensive to
> 
>     1. Smart people. Why should smart people use the stupid content tracker?
> 
>     2. Content. Content deserves to be tracked by smart tracker.
> 
> 
> Should I create another issue to make ~git~ RainbowUnicornHappy smarter or will it be handled together with renaming?

I truly believe just changing the name will solve all problems, and of course burning all of my tech books that use git.  You're comment has given me hope and tearsofjoy.Oh,no,nowthetearshavefriedmyspacebar.Ireallyreallyreeeeeeeeeeeeeee.

**Comment by PhilipOakley** [comment]
PR's welcome. Be wary of taking Scotland's national animal's name in vain.

**Comment by dscho** [comment]
While I appreciate the attempt to bring some light humor into this depressing discussion, I would like to focus on more constructive ways to foster diversity and inclusion. Maybe all of you can help, by listening to acquaintances from underrepresented groups.

**Comment by johnmanko** [comment]
> attempt to bring some light humor

That's your takeaway?
