### ISSUE TITLE
Having trouble installing Git

### ISSUE THREAD

**Issue by fuzzy-ice** [git-for-windows/git#2692]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults

### Details
I'm trying to install Git for the first time for a quick project where I need to run a .bat file and Git is apparently required to run this one, and I'm not very experienced with anything related to this. Basically when I open up the setup the first thing that pops up is:
"Unable to get system config"
After hitting OK it goes into a series of:
Could not read
"C:\Users\name\Appdata\Local\Temp\is-E0DUJ.tmp\git-config-get.txt"
then it repeats both error messages again until it gets to the public license.
After choosing all the default options and hitting install, it goes through the whole green installation bar for about 30-60 seconds and as soon as it finishes a new series of error messages pop up:
Unable to get system config
"diff.astextplain.textconv":="astextplain": exit code 2
(no output)
stderr:
(no output)

Unable to get system config "filter.lfs.clean":="git-lfs clean --%f": exit code 2
(no output)
stderr:
(no output)

Unable to get system config "filter.lfs.smudge":="git-lfs smudge --%f": exit code 2
(no output)
stderr:
(no output)

Unable to get system config "filter.lfs.process":="git-lfs filter-process": exit code 2
(no output)
stderr:
(no output)

Unable to get system config "filter.lfs.required":="true": exit code 2
(no output)
stderr:
(no output)

Unable to set system config defaults

Unable to set system config "http.sslBackend":="openssl": exit code 2
(no output)
stderr:
(no output)

Unable to set system config "http.sslCAInfo":="C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt": exit code 2
(no output)
stderr:
(no output)

Unable to set system config "core.autocrif":="true": exit code 2
(no output)
stderr:
(no output)

Unable to set system config "pull.rebase":="false": exit code 2
(no output)
stderr:
(no output)

Unable to set system config "core.fscache":="true": exit code 2
(no output)
stderr:
(no output)

Unable to set system config "credential.helper":="manager": exit code 2
(no output)
stderr:
(no output)

Unable to set system config "core.symlinks":="false": exit code 2
(no output)
stderr:
(no output)

Unable to set system config "core.editor":=""C:\Program Files(x86)\Notepadd++\notepad++.exe" -multinst -notabbar -nosession -noPlugin": exit code 2
(no output)
stderr:
(no output)

Line 3030: Unable to run post-install scripts; no output?

After clicking OK through all of these error messages it brings me to the Completing the Git Setup Wizard, I hit Next and the release notes pop open and the setup closes. Now it appears to be installed, but whenever I try to open git CMD it instantly closes as soon as it shows up, and when I run Git Bash it stays open and gives me a few more lines of error messages. Then when I try to run the .bat file using Bash it opens and loads a few lines of it and then closes with nothing happening. 

I'm pretty sure I'm doing something very wrong somewhere, so if anybody could tell me what exactly that is that would be very much appreciated. Thanks.

**Comment by dscho** [comment]
Hmm. We have had a couple reports about the same symptom, but never got to the bottom of it.

Does your `.bat` script work in a regular CMD?

**Comment by fuzzy-ice** [comment]
Sorry, turns out the problem was me being stupid. I had my cmd.exe file renamed as something else and as soon as I changed it back to cmd.exe and restarted my PC it installed fine. (At least I'm pretty sure that's what the issue was.)

**Comment by dscho** [comment]
Oh, that's a new one 😄 

Thank you for circling back with this entertaining explanation 🙇
