### ISSUE TITLE
Change non-inclusive naming

### ISSUE THREAD

**Issue by youCannotCensorMe** [git-for-windows/git#2696]
[A very easily found Wikipedia page](https://en.wikipedia.org/wiki/Git_(slang)) and the whole English-speaking community [of the last 1000 years](https://en.wiktionary.org/wiki/git#Etymology_1) have clearly brought this issue to attention: the name of the Git project itself is non-inclusive and could cause unintended consequencies. Quoting [the Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/git), "git" means "a person, especially a man, who is stupid or unpleasant".

I create this ticket to track the progress of fixing this.

The most rational and logical fix would be to completely rename the project to something more appropriate and that would not offend any gender or ethnicity, although also avoiding terms like "nerd", "geek" et similia because they could also be considered offensive. However, another more radical solution would be to completely dismantle the project, as it has been bringing hate since 2005, mostly by putting a horrible word in such good light.

Any constructive comments are welcome!

__________________________________________________________
UPDATE:

This issue was opened the first time on the 16th of of June, 2020, and then got deleted withot any motivation or warning. Thus, I opened it again: issues do not get deleted, they get closed. Deleting an issue is censorship and is against the "code of conduct", as it is not "respectful of different viewpoints" and "gracefully accepting constructive criticism".
For anyone who wants to read 16/06's responses to the issue, you can see them on the web archive: [http://web.archive.org/web/20200617011912/https://github.com/git-for-windows/git/issues/2693](http://web.archive.org/web/20200617011912/https://github.com/git-for-windows/git/issues/2693)

The issue was opened again on the 17th of June, 2020, and got deleted a few hours later, and the original author was also blocked from the repo. The issue was archieved [here](http://web.archive.org/web/20200617112553/https://github.com/git-for-windows/git/issues/2694), although unfortunately no response was archieved. However, I had set up a caching script, so I have screenshots of those responses. You can see them here:
- [screenshot 1](https://i.ibb.co/56P8fQQ/screen1-cut.png)
- [screenshot 2](https://i.ibb.co/0fz6q6N/screen2-cut.png)

**Comment by youCannotCensorMe** [comment]
I will now proceed by answering to everyone who peacefully said their opinion on the 17/06's responses.

@maxloh said:
> 
> 
> Maybe we should contact original git maintainers and have them intervened with the maintainers' decisions.
> 
> Opening more issues here may not help the situation.

I do not understand whether this comment is "sarcastic" or not, and if it isn't, I suggest you take a quick look at the three responses that yesterday's issue has got. As someone yesterday pointed out (unfortunately, the comment is not present in the archieved page), because of ["Poe's law"](https://en.wikipedia.org/wiki/Poe%27s_law) things online can easily be misunderstood.

@evandentremont said:
> 
> 
> Seems the maintainers of `git for windows` made up their mind considering what they're doing to anyone who isn't woke.
> 
> This is problematic.

Exactly. This is exactly what is happening. I am peacefully expressing disagreement and I get blocked twice, and finally banned.

@alt0173 said:
> 
> 
> I mean no disrespect. but perhaps making a petition would help your cause, because at the moment it seems like the people behind his are a tiny minority (no pun intended) of users that are not at all reflective of the opinions of the git userbase. I do agree with your point about the deletion of the previous post however, it should have been closed and a reason for doing so provided.

The problem is, the repo maintainer disagrees with this. No one in the community wanted the change, as you can see in the issue #2674. However, everyone got censored. Black people were asked, and they didn't think of "master" as a discriminatory term. Yet, the repo maintainer decided that everyone on GitHub and Reddit is not representative of the community, but a few tweets from his friends are: [https://github.com/git-for-windows/git/issues/2674#issuecomment-643840714](https://github.com/git-for-windows/git/issues/2674#issuecomment-643840714).


@UltimateForm said:
> 
> 
> yesterday @evandentremont said:
> 
> > git is mostly a Great Britain word and as the country is a majority white this name is OK as offending white colonisers of privilege is allowable under human rights legislation
> 
> **I'm not making any point for or against anything, please don't block me or mark me offtopic**, I'm just confused, what does that mean? What "human rights legislation" allows this offense against "white colonisers of privilege" and who are these "white colonisers" today and what privilege are they enjoying? If this is gonna serve as the rule for what words we can use and can't use on this community, it should be clear like everything else in this community should.

@evandentremont is the one who pointed out Poe's law. From my understanding, his comment was a "parody", a "sarcastic" one. However, I misunderstood and though he was being serious, and thus responded in a serious way. I apolozige

**Comment by UltimateForm** [comment]
> I will now proceed by answering to everyone who peacefully said their opinion on the 17/06's responses.
> 
> @maxloh said:
> 
> > Maybe we should contact original git maintainers and have them intervened with the maintainers' decisions.
> > Opening more issues here may not help the situation.
> 
> I do not understand whether this comment is "sarcastic" or not, and if it isn't, I suggest you take a quick look at the three responses that yesterday's issue has got. As someone yesterday pointed out (unfortunately, the comment is not present in the archieved page), because of ["Poe's law"](https://en.wikipedia.org/wiki/Poe%27s_law) things online can easily be misunderstood.
> 
> @evandentremont said:
> 
> > Seems the maintainers of `git for windows` made up their mind considering what they're doing to anyone who isn't woke.
> > This is problematic.
> 
> Exactly. This is exactly what is happening. I am peacefully expressing disagreement and I get blocked twice, and finally banned.
> 
> @alt0173 said:
> 
> > I mean no disrespect. but perhaps making a petition would help your cause, because at the moment it seems like the people behind his are a tiny minority (no pun intended) of users that are not at all reflective of the opinions of the git userbase. I do agree with your point about the deletion of the previous post however, it should have been closed and a reason for doing so provided.
> 
> The problem is, the repo maintainer disagrees with this. No one in the community wanted the change, as you can see in the issue #2674. However, everyone got censored. Black people were asked, and they didn't think of "master" as a discriminatory term. Yet, the repo maintainer decided that everyone on GitHub and Reddit is not representative of the community, but a few tweets from his friends are: [#2674 (comment)](https://github.com/git-for-windows/git/issues/2674#issuecomment-643840714).
> 
> @UltimateForm said:
> 
> > yesterday @evandentremont said:
> > > git is mostly a Great Britain word and as the country is a majority white this name is OK as offending white colonisers of privilege is allowable under human rights legislation
> > 
> > 
> > **I'm not making any point for or against anything, please don't block me or mark me offtopic**, I'm just confused, what does that mean? What "human rights legislation" allows this offense against "white colonisers of privilege" and who are these "white colonisers" today and what privilege are they enjoying? If this is gonna serve as the rule for what words we can use and can't use on this community, it should be clear like everything else in this community should.
> 
> @evandentremont is the one who pointed out Poe's law. From my understanding, his comment was a "parody", a "sarcastic" one. However, I misunderstood and though he was being serious, and thus responded in a serious way. I apolozige

ahah this is getting oblivion'd soon, but ill answer anyway, i figured it was sarcasm too but still the mantainers should be clear with their reasoning for deleting these issues, what are the rule they are using for deciding which words are "inclusive" or "non-inclusive"

**Comment by youCannotCensorMe** [comment]
>
> 
> ahah this is getting oblivion'd soon, but ill answer anyway, i figured it was sarcasm too but still the mantainers should be clear with their reasoning for deleting these issues, what are the rule they are using for deciding which words are "inclusive" or "non-inclusive"

Don't worry, this will not get oblivion'd. I have a lot of free time, and will do anything in my possibilities to keep this issue alive on the `git-for-windows` repo. Since they are deleting my issues without providing any reason, I can open as many as I want - and be sure that I will. As soon as this issue gets deleted, I will open a new one and link all the previous ones. It's as easy as that.

**Comment by alt0173** [comment]
I think we should just invent some new words to replace all current existing words in this repo as to avoid offending anyone on accident as we cannot ask every single person on earth if each word used in the repo is offensive to them.

**Comment by SergeyMax** [comment]
> he most rational and logical fix would be to completely rename the project

Indeed, if you are not a black gay guy, your point of view can't be cared by anybody. So I suggest you to use appropriate photo as the avatar and you will never get banned because it obviously will be racist action.
