### ISSUE TITLE
For file symlinks Git Gui shows an error modal instead of a diff

### ISSUE THREAD

**Issue by Tragetaschen** [git-for-windows/git#2697]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.27.0.windows.1.5.gaeb9254316.20200607205841
cpu: x86_64
built from commit: aeb92543162d0eb73e2b09456997ab5ecfdc387e
sizeof-long: 4
sizeof-size_t: 8
```
that is, the CI build that fixes #2653.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.18363.900]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
```

### Details

- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I'm running Git Gui from Windows Explorer

 - What commands did you run to trigger this issue? If you can provide a
```sh
# prepare the repository on a cmd prompt
md git-gui-symlink-repo
cd git-gui-symlink-repo
git init
echo a > a.txt
git add .
git commit -m 'commit'
mklink b.txt a.txt
```

Now open Git Gui from Windows Explorer for the repo folder and mark b.txt in the "Unstaged Changes".

 - What did you expect to occur after running these commands?
Some form of diff

 - What actually happened instead?
![image](https://user-images.githubusercontent.com/1947968/84918974-9e588700-b0c1-11ea-9509-4816d731fbc6.png)

**Comment by dscho** [comment]
Excellent MCVE.

When I stage the symlink and then look at the diff, it works, though.

**Comment by dscho** [comment]
Unfortunately, this seems to be a limitation of Tcl/Tk. Running `tclsh` with a file like this:

```tcl
puts [file readlink "b.txt"]
```

I see the following error:

```
could not read link "b.txt": not a directory
    while executing
"file readlink "b.txt""
    invoked from within
"puts [file readlink "b.txt"]"
    (file "a1.tcl" line 1)
```

It might be a bug specific to the mingw-w64 version of Tcl we use: it is the one from MSYS2's `mingw-w64-tcl` package.

**Comment by mfriedrich74** [comment]
Isn't TCL limited to junctions only (so far I know)? Does mklink create a
junction if /j is not specified?

**Comment by dscho** [comment]
> Isn't TCL limited to junctions only (so far I know)?

Maybe? I did not find anything in https://www.tcl.tk/man/tcl/TclCmd/file.htm#M45, though.

Ah, but there is a StackOverflow post about it: https://stackoverflow.com/questions/39456715/how-to-obtain-the-target-path-pointed-by-a-symbolic-link-in-tcl

And that post mentions the feature ticket: https://core.tcl-lang.org/tcl/tktview/c8d4f01a54d7ecf819f4881fb02467ad14fc7b0c

> Does mklink create a junction if /j is not specified?

No, it creates a new-style symlink. There are many differences between junctions and symlinks, not the least being: junctions are resolved by the NTFS driver, symlinks are not. Oh, and you cannot have file junctions AFAIR, only directory junctions.

**Comment by dscho** [comment]
@Tragetaschen do you feel strongly about this? I would be up for a live session with you where I can help you understand what needs to be changed to fix this, and where.

**Comment by Tragetaschen** [comment]
Nah, no strong feelings here. I just stumbled over it, but it's not like I'm creating symlinks every other day…

**Comment by dscho** [comment]
> Nah, no strong feelings here. I just stumbled over it, but it's not like I'm creating symlinks every other day…

Okay, let's close this ticket then.

We can always re-open it if a contributor shows up who wants to work on this.
