### ISSUE TITLE
Swaped insertions and deletions text when doing git diff --stat {id} {id}

### ISSUE THREAD

**Issue by Jiwari** [git-for-windows/git#2699]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
```
$ git --version --build-options
git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.900]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Default options

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue?
With any git repo, take an existing file do the following:
Step 1: delete 2 lines
Step 2: add 5 lines
Step 3: Commit the changes
Step 4: Run the command: `git diff --stat HEAD HEAD~1` 

 - Expected
1 file changed, 5 insertions(+), 2 deletions(-)

 - Actual
1 file changed, 2 insertions(+), 5 deletions(-)

This issue is not exclusive to adding AND removing lines on the same commit, only adding and only removing also gives swapped messages.

**Comment by dscho** [comment]
It looks as if it worked as designed: the syntax is `git diff [<options>] <old-revision> <new-revision>`. Since you specified the parent of the tip commit as the _new_ revision, it appears to be reversed.

It should work as you expect it to by calling `git diff --stat HEAD~1 HEAD` instead. Or short: `git diff --stat HEAD^!`.

**Comment by Jiwari** [comment]
@dscho  Yep, you are right, using `<old-revision> <new-revision>` displays results as intended.  
Thanks for checking this!
