### ISSUE TITLE
git status/diff/pull not working (seems like for long paths)

### ISSUE THREAD

**Issue by chdigvijay20** [git-for-windows/git#2707]
# Setup

64-bit
```
$ git --version

git version 2.27.0.windows.1
```
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1282]
```
```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```
### Details
Bash or CMD
```
git status
```
Expected to see the current status of the repository. But received the following output.

Got following output
![2020-06-19 17_02_53-Administrator_ Command Prompt](https://user-images.githubusercontent.com/17607368/85128423-e0fb9a00-b24e-11ea-80ff-37efd6f5d178.png)

The same thing happened for ```git diff``` and ```git pull```.

**Comment by PhilipOakley** [comment]
Could you try the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)? 
Your issue could be related to some similar issues that have been looked at.
If it does fix the issue, could you report that back?

**Comment by chdigvijay20** [comment]
I got the same output with the latest snapshot.

**Comment by chdigvijay20** [comment]
It's not an issue with git. There was another application that had created hooks in the kernel and was interfering with the git process.
