### ISSUE TITLE
git bash will auto exit, and it shows "...can't find configuration file..".

### ISSUE THREAD

**Issue by 442808343** [git-for-windows/git#2708]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

$ git --version --build-options

2.27.0-64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

win 10-64
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

by defaults
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I tried two git versions, 2.27.0-64 and 2.26.2-64, and they were same.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

It can't start normally, so I don't know.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I just click the "git bash here", then it will show the error.
```
 - What did you expect to occur after running these commands?

enter git bash.

 - What actually happened instead?

git bash will auto exit, and before it disappear, it shows "/usr/bin/bash: can't find configuration file /usr/local/etc/profile.global; exiting."

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

it seems just occurring in my laptop, if needed you could send me 442808343@qq.com

**Comment by dscho** [comment]
> git bash will auto exit, and before it disappear, it shows "/usr/bin/bash: can't find configuration file /usr/local/etc/profile.global; exiting."

That's funny. Do you have any `.bash_profile` or `.bashrc` files in your home directory? Git for Windows has no notion of any `profile.global` file...

**Comment by AvrilSf** [comment]
Hey, 
I installed Git 2.27.0 but was not able to open un Git Bash.  So then, I tried with Git 2.17.0 but I get:
Unable to execute file: C:\Program Files\Git\git-bash.exe
CreateProcess failed; code 740.
The requested operation requires elevation.

If I try to download this older version from github, I get a message saying I have no permissions to access the repo.
I have Windows 7
Can you help me, please?

Thank you kindly for your attention !

**Comment by dscho** [comment]
> I get a message saying I have no permissions to access the repo.

What is the exact command and the exact output?
