### ISSUE TITLE
Error message "function not implemented"

### ISSUE THREAD

**Issue by Wingthor1968** [git-for-windows/git#2710]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.900]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
WD MyCloud 4TB
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status -> fatal: failed to stat 'URL': Function not implemented
git pull -> fatal: failed to stat 'URL': Function not implemented
```
 - What did you expect to occur after running these commands?

The commands should have worked fine.

 - What actually happened instead?

The commands throw -> fatal: failed to stat 'URL': Function not implemented

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None of my repos is working.

**Comment by dscho** [comment]
I fear that you'll need to do a fair bit of digging yourself here, as your use case is a rather niche one.

How is your C fu? Have you already tried to build Git for Windows from scratch? See https://github.com/git-for-windows/git/wiki/Building-Git for details how to.

Once you successfully built it, you will want to patch `mingw_lstat()` in `compat/mingw.c` (and/or `fscache_lstat()` in `compat/win32/fscache.c`) to see what `GetLastError()` reports in the error case, then rebuild and use `bin-wrappers/git -C <directory> <command> [<argument>...]` to test.

**Comment by Wingthor1968** [comment]
Okay. I'll try my best. I tried to build git from the scratch and test it. The test failed with
```
1..1
*** t0014-alias.sh ***
ok 1 - nested aliases - internal execution
ok 2 - nested aliases - mixed execution
ok 3 - looping aliases - internal execution
not ok 4 - run-command formats empty args properly
#
#           test_must_fail env GIT_TRACE=1 git frotz a "" b " " c 2>actual.raw &&
#           sed -ne "/run_command:/s/.*trace: run_command: //p" actual.raw >actual &&
#           echo "git-frotz a '' b ' ' c" >expect &&
#           test_cmp expect actual
#
# failed 1 among 4 test(s)
1..4
make[2]: *** [Makefile:56: t0014-alias.sh] Fehler 1
make[2]: Verzeichnis „/usr/src/git/git/t“ wird verlassen
make[1]: *** [Makefile:43: test] Fehler 2
make[1]: Verzeichnis „/usr/src/git/git/t“ wird verlassen
make: *** [Makefile:2774: test] Fehler 2
```

Do I need to fix this first (or get it fixed) or is it something I don't have to worry about?

**Comment by rimrul** [comment]
That's just unexpected trace output due to busybox. I'd just work around that by changing [line 40 in t0014](https://github.com/git-for-windows/git/blob/main/t/t0014-alias.sh#L40) to `test_expect_failure`.

**Comment by dscho** [comment]
> 
> 
> That's just unexpected trace output due to busybox. I'd just work around that by changing [line 40 in t0014](https://github.com/git-for-windows/git/blob/main/t/t0014-alias.sh#L40) to `test_expect_failure`.

Or just ignore that particular test failure for now.

**Comment by Wingthor1968** [comment]
I decided to change the line yesterday and my box was busy with testing the rest of the day.

What I found out after I built git myself is:
When I call `git status` in the "git"  git repo `mingw_lscache` is called (and does not cause an error)
When I call `git status` in the "project" git repo on the NAS it fails (throws the error message) and does not call `mingw_lstat()` nor `fscache_lstat()`. So I was about to find out where I should start to investigate instead.

**Comment by Wingthor1968** [comment]
It fails in setup.c

```
static dev_t get_device_or_die(const char *path, const char *prefix, int prefix_len)
{
	struct stat buf;
	if (stat(path, &buf)) {        //<---------------------------stat throws the error
		die_errno(_("failed to stat '%*s%s%s'"),
				prefix_len,
				prefix ? prefix : "",
				prefix ? "/" : "", path);
	}
	return buf.st_dev;
}
```

I did `stat <file>` manually with success (exit code: 0, `<file>` being my repos root dir). Now I'm left puzzled.

**Comment by rimrul** [comment]
Yeah, `stat <file>` is misleading. That's calling MSYS2 `stat.exe`, the `stat()` call above is actually a [`mingw_stat()`](https://github.com/git-for-windows/git/blob/main/compat/mingw.c#L1070-L1100) call. (`#define stat mingw_stat` in `compat/mingw.h` included via `cache.h`/`git-compat-util.h`) `mingw_stat()` then either calls [`mingw_lstat()`](https://github.com/git-for-windows/git/blob/main/compat/mingw.c#L977-L1043) or [`err_win_to_posix()`](https://github.com/git-for-windows/git/blob/main/compat/mingw.c#L32-L149).

**Comment by dscho** [comment]
I am sure that you will be able to reproduce after calling `git config core.fscache true`, and it will most likely fail in `fscache_stat()`.

**Comment by dscho** [comment]
And the `mingw_stat()` shim is probably at play in the `git status` failure.

**Comment by rimrul** [comment]
I might be missing something, but i don't think there is an `fscache_stat()`. At least not in `compat/win32/fscache.c` and `compat/win32/fscache.h`.

**Comment by dscho** [comment]
Oh? I misremembered, then, sorry.

**Comment by Wingthor1968** [comment]
Where do I find the constants of mingw.c `int err_win_to_posix(DWORD winerr)`?
I get `58` translated into `40`, so I would like to know which constant is the one with the value 58.

**Comment by rimrul** [comment]
>ERROR_BAD_NET_RESP
>  58 (0x3A)
> The specified server cannot perform the requested operation.

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

**Comment by Wingthor1968** [comment]
I already saw that in `winerror.h` but this constant is **not** used in the switch statement of `int err_win_to_posix(DWORD winerr)`

**Comment by rimrul** [comment]
`err_win_to_posix()` [defaults to `ENOSYS`](https://github.com/git-for-windows/git/blob/main/compat/mingw.c#L34) (the 40).

**Comment by dscho** [comment]
> 
> I get `58` translated into `40`, so I would like to know which constant is the one with the value 58.

Which Win32 API call resulted in that error?

**Comment by Wingthor1968** [comment]
My fault. It was too obvious ;)

**Comment by Wingthor1968** [comment]
mingw.c `GetFileInformationByHandle(hnd, &fdata)`

**Comment by dscho** [comment]
> mingw.c `GetFileInformationByHandle(hnd, &fdata)`

Okay.

I fear that we will have to react to _at least_ the error value you mentioned by falling back to the `GetFileAttributesExA()` method that we used originally, as added in 5411bdc4e4b170a57a61b2d486ab344896c41500.

(You'll need to accommodate for a couple of changes we had in the meantime such as 64-bit file sizes, and I don't think that `_getdrive()` was the right thing to do.)

Would that work?

**Comment by Wingthor1968** [comment]
Hey there. Here is an update: the issue comes from mingw.c `GetFileInformationByHandle` in
```
if (!GetFileInformationByHandle(hnd, &fdata)) {
    errno = err_win_to_posix(GetLastError());
    ...
```

I tried to use `GetFileInformationByHandleEx` instead with the following result:
- the behaviour is now identical with the local and 'remote' repo (on the NAS, SMB share)
- both throw the same error: `fatal: too large to be a .git file: '<filename>'`

**Comment by dscho** [comment]
> I tried to use `GetFileInformationByHandleEx` instead with the following result:

Have you tried falling back to `GetFileAttributesExW()` instead?

**Comment by rimrul** [comment]
Could you also post your modified code for `get_file_info_by_handle()` to use `GetFileInformationByHandleEx()`?

**Comment by Wingthor1968** [comment]
> Could you also post your modified code for...

Sure. This one is easy: `GetFileInformationByHandleEx(hnd, 1, &fdata, sizeof(BY_HANDLE_FILE_INFORMATION))`

I didn't change much, because I was just curious after reading this [MS API doc](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileinformationbyhandle). Excuse my little knowledge but I'm not a Windows developer and to be honest I don't want to get one ;)

> Have you tried falling back to GetFileAttributesExW() instead?

Not yet. Since I'm not a C nor a Windows developer it will take me some time.

**Comment by rimrul** [comment]
Yeah, that means you're probably writing non-initalized data into `buf.st_size`. `GetFileInfoByHandleEx()` expects different structs depending on what you pass where you have that 1. In this case `FILE_STANDARD_INFO`, which is smaller than the `BY_HANDLE_FILE_INFO` you pass it and doesn't fill the remaining space.

**Comment by Wingthor1968** [comment]
I see the point. I try to fix that later today and let you know the outcome.

**Comment by Wingthor1968** [comment]
I made this change:
```
/*BY_HANDLE_FILE_INFORMATION*/  FILE_ID_BOTH_DIR_INFO fdata;
if (!GetFileInformationByHandleEx(hnd, 10, &fdata, sizeof(FILE_ID_BOTH_DIR_INFO))) {
...
```
It seemed to be the structure with the info copied to the buffer later on. With this outcome:
`fatal: failed to stat '<path_to_repo_folder>': Permission denied`

**Comment by rimrul** [comment]
That 10 means `FileBothDirectoryInfo`. According to the `FILE_INFO_BY_HANDLE_CLASS` documentation, that's intended for directory handles to retrieve info on files within. Judging from the previous error message about size of the `.git` file, the handle is probably not a directory handle.

**Comment by Wingthor1968** [comment]
> the handle is probably not a directory handle

I think it is a directory handle. It points to the folder containing the repo. It breaks one iteration before the former version. The former version passed the directory according to my 'debugging for poor developers' (fprintf  ;) ) and broke with the .git file. This version does stop immediatly at the directory level.

**Comment by gregstephensen** [comment]
Reinstall Git, set Performance Tweaks FSCache: Enabled to disabled using the installer GUI. This seems to have fixed it for me I think.

**Comment by Wingthor1968** [comment]
Hi! I guess I found the root cause of the issue: bad SMB2/3 support on either Windows or the NAS side. I had many network issues with other software (e.g. Visual Studio Code and even Notepad!) too. Especially funny: when using VSCode and the open dialog I saw files in the dialog and got "file not found" when I tried to open one.
When I fell back to CIFS/SMB1 on both sides everything worked fine. Obviously both ends speak a different SMB2/3 dialect ;)

**Comment by dscho** [comment]
> I guess I found the root cause of the issue: bad SMB2/3 support on either Windows or the NAS side.

@Wingthor1968 question is: _can_ we do anything about this? In particular, I would like to ask this question again:

> Have you tried falling back to `GetFileAttributesExW()` instead?

**Comment by dscho** [comment]
Closing as stale.
