### ISSUE TITLE
CRITICAL - Fatal Error on Memory Allocation due to very bad memory leak during "git fast-import --import-marks=git-marks.dat < git-dump.dat" consuming up to 13GB of free memory until windows crash or video driver failure.  Downgrade to 2.26.2 fixes the issue.

### ISSUE THREAD

**Issue by joeltoth** [git-for-windows/git#2716]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?   **64-bit**
****
```
$ git --version --build-options
**git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8**

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?   Windows 10  (1909 Build 18363.900)-  64-bit
![image](https://user-images.githubusercontent.com/18425764/85587274-df3f2700-b5fe-11ea-92d4-887bbbf2c17b.png)

```
$ cmd.exe /c ver
**Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.**

```

 - What options did you set as part of the installation? Or did you choose the
   defaults? - **Default selections in all prompts.  Same experience with upgrade from 2.26.2 and a fresh install of 2.27.0**

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

**Editor Option: SublimeText
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled**

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**Nope nothing special**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Tried with both Bash installed with git-for-windows and also the native CMD prompt.  Same issue in both cases, command hangs and eventually fails with a Fatal error memory allocation

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$  git fast-import --import-marks=git-marks.dat < E:\CVS2GIT\0-ConvertedFiles\posseport\git-dump.dat

Note: There is a very bad memory leak during "git fast-import --import-marks=git-marks.dat < git-dump.dat" consuming up to 13GB of free memory until windows crash or video driver failure.  If I downgrade to 2.26.2 the import works in a snap and it fixes the issue.
```
 - What did you expect to occur after running these commands?
If I downgrade to 2.26.2 the import works in a snap and it fixes the issue. when I run the following command:

$  git fast-import --import-marks=git-marks.dat < E:\CVS2GIT\0-ConvertedFiles\posseport\git-dump.dat
git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:      10000
Total objects:            0 (      4374 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of
       0 attempts)
      trees  :            0 (      3774 duplicates          0 deltas of
       0 attempts)
      commits:            0 (       600 duplicates          0 deltas of
       0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of
       0 attempts)
Total branches:          46 (        46 loads     )
      marks:     1073741824 (      9880 unique    )
      atoms:           1410
Memory total:          3274 KiB
       pools:          2649 KiB
     objects:           625 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =      65536
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =       4755
pack_report: pack_mmap_calls          =          2
pack_report: pack_open_windows        =          2 /          2
pack_report: pack_mapped              =   13241886 /   13241886
---------------------------------------------------------------------

Proving the downgrade:
# git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8

 - What actually happened instead?

This is Git for Windows consuming 9GB at the time of the Screenshot, the highest it got to was 13GB when it caused my video driver to flicker and then fail and my PC finally resurrected from a black screen after a solid 5 min and a few minor heart attacks.  This is the task manager:
![image](https://user-images.githubusercontent.com/18425764/85588739-31cd1300-b600-11ea-8fc4-28418d71ecfd.png)
![image](https://user-images.githubusercontent.com/18425764/85589596-ecf5ac00-b600-11ea-83f3-c67e011d154b.png)

Then in the git bash console or cmd prompt it would be hung like this:
![image](https://user-images.githubusercontent.com/18425764/85589072-7ce72600-b600-11ea-9de7-7797127d523c.png)

until this error is raised:
$ git fast-import --import-marks=git-marks.dat < E:/CVS2GIT/0-ConvertedFiles/posseport/git-dump.dat
fatal: Out of memory, malloc failed (tried to allocate 2097152 bytes)
fast-import: dumping crash report to .git/fast_import_crash_17800

[fast_import_crash_17800.zip](https://github.com/git-for-windows/git/files/4826549/fast_import_crash_17800.zip)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This should not be repo specific as I tried with more than one and I also tried this on my downstairs computer and got the exact same memory leak.  That PC downstairs is also windows 10 - 64-bit.
I cannot provide the file as the contents are proprietary.  As I have shown above in what I expected to happen, downgrading to 2.26.2 allows the import to succeed and there is no memory leak during the "--import-marks" step

**Comment by PhilipOakley** [comment]
I believe that this is currently being addressed upstream [git-fast-import out of memory](https://public-inbox.org/git/c53bb69b-682d-3b47-4ed0-5f4559e69e37@gmx.com/) so a fix should permeate soon. 

It wasn't recorded in the recent "[what's cooking](https://public-inbox.org/git/xmqqimfid2l1.fsf@gitster.c.googlers.com/)" email, but a patch is there in the first ref email.

**Comment by joeltoth** [comment]
Thank you for the reply and for the patch, I will wait for the official release to upgrade and continue to use 2.26.2 for the time being.  I was just doing my due diligence and had noticed that the issue was not in the list of reported issues against the release, nor could I find anything else about it so I thought I would make mention.  From a fellow software engineer to another, I didnt want any dropped balls here to say the least.

**Comment by dscho** [comment]
> It wasn't recorded in the recent "[what's cooking](https://public-inbox.org/git/xmqqimfid2l1.fsf@gitster.c.googlers.com/)" email, but a patch is there in the first ref email.

Right, but since it is not mentioned, it means it fell between the cracks. A good way to get it rolling again would be to report success...

@joeltoth This is how you could test it:

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk init build-extra`,
3. `sdk cd git`,
4. `/usr/src/build-extra/apply-from-public-inbox.sh https://public-inbox.org/git/20200606002241.1578150-3-sandals@crustytoothpaste.net/`
4. build Git via `make -j$(nproc)`
5. test in-place via `./git --exec-path="$PWD" -C <directory> <command>`?
6. reply to the patch [as indicated here](https://public-inbox.org/git/20200606002241.1578150-3-sandals@crustytoothpaste.net/#R).

**Comment by joeltoth** [comment]
dscho thank you for your very informative response, I really appreciate your steps mentioned for how to actually test it.  This was an excellent response and would have helped me better at the time. As a software engineer, unfamiliar of this project I was actually able to make use of your steps, unlike the link to just the patch.  The ball was dropped and it fell through the cracks but we thankfully caught it and it wasn't missed.

I will be using fast-import again soon in the official cvs2git conversion we are doing.  Since 2.28 is the latest release I will try against that or whatever the tail release is when we go to do it officially.   If any issues there I will report back.

**Comment by dscho** [comment]
Closing as stale.
