### ISSUE TITLE
Git can't find the path to the SSL certificate while pushing a project to Heroku

### ISSUE THREAD

**Issue by angeltapes** [git-for-windows/git#2718]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows [Version 10.0.18362.778]
(c) 2019 Microsoft Corporation. All rights reserved.

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults
'''
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other


Git bash
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git config --add http.sslCAinfo "C:\Program%Files\Git\mingw64\ssl\certs\ca-bundle.crt"
git push heroku master
```
 - What did you expect to occur after running these commands?

Pushing my GDS prototyping project to Heroku. See https://govuk-prototype-kit.herokuapp.com/docs/publishing-on-heroku

 - What actually happened instead?
I got the error:

```
fatal: unable to access 'https://git.heroku.com/gds-sandpit.git/': error setting certificate verify locations:
  CAfile: C:\Program%FilesGitmingw64sslcerts
  CApath: none
```
I downloaded the latest version of GIT. The SSL certificate path seems to be configured wrongly so this is is going to be an issue for anyone who tries to push a project to Heroku, as far as I can see. I'm looking for a way to change the Git config file but I thought I'd let you know in case this is an error. Thanks

**Comment by rimrul** [comment]
>Program%Files

I think I found your issue. There should probably be a space, not a percent sign in there.

**Comment by angeltapes** [comment]
That worked! 1000 thank-yous. If this isn't a flaw in the Git package I downloaded the issue can be closed.
