### ISSUE TITLE
Typo in Windows installer

### ISSUE THREAD

**Issue by JohannStudanski** [git-for-windows/git#2719]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.27.0 64-bit non-portable Windows installer from https://git-scm.com/

 - What options did you set as part of the installation? Or did you choose the
   defaults?

all default

### Details

"default behavior for git pull"-page says "fast-forard" in Option 3.
See https://i.ibb.co/5xmN2pS/Git-Typo.png

**Comment by PhilipOakley** [comment]
Thanks for noticing. It's now resolved, but GitHub's search typically doesn't find the closed issues, see https://github.com/git-for-windows/git/issues?q=is%3Aissue+forard 

Fixed in git-for-windows/build-extra#291.
