### ISSUE TITLE
pseudo console - typing while command in progress causes duplicated command

### ISSUE THREAD

**Issue by lukeapage** [git-for-windows/git#2720]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1217]
(c) 2018 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope

### Details

In git bash:

* run a command - could be yarn, could be git, doesn't matter
* before the command finishes, start typing the next command
* when the command finishes, the command prompt duplicates the text you typed twice.
* e.g. if It type `git checkout master` I get
```
> git checkout mastergit checkout master
```

**Comment by lukeapage** [comment]
I tried the latest snapshot - it no longer repeats twice - most commands work ok - some swallow everything (`git branch -v`) but I guess it might have been like that before

**Comment by dscho** [comment]
> some swallow everything (`git branch -v`)

I think that's because that command runs the pager (`less.exe`) which consumes the keystrokes. That's by design, I am afraid.
