### ISSUE TITLE
Expose sh in PATH directory

### ISSUE THREAD

**Issue by bk2204** [git-for-windows/git#2721]
- [ x I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.27.0, 64-bit, both the main and MinGit busybox version

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 Professional 2004.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

The defaults.  The main was installed by Chocolatey.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD / PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ sh -c "echo foo"
```
 - What did you expect to occur after running these commands?

"foo"

 - What actually happened instead?

An error.

To describe more in detail, `bash.exe` is exposed in the directory used by PATH, but `sh` is not.  This normally would be fine, except that the BusyBox version doesn't ship with bash, and this is the version used in many container environments.  My interest is in using the Git for Windows `sh` binary for appurtenant tooling (e.g., `gh`, `hub`, and `git lfs`) that uses `sh` for compatibility with Git (say, in places where `EDITOR` or `VISUAL` is used, which must necessarily invoke the shell).  If bash were shipped in all versions, then I'd just force the code to use `bash` on Windows, but alas, that's not possible.  Right now the only way to make things work on all Git for Windows versions is to implicitly assume the directory layout, search every PATH directory for `git.exe`, and then try to find the `sh.exe` binary in the right place based on the `git.exe` binary, which is both error-prone and gross.

Would it be possible to expose a `sh` binary in the same directory as the `git` binary (i.e., the one normally placed in `PATH`) in each version in a future Git for Windows release?

**Comment by dscho** [comment]
That would possibly interfere with WSL and with calling Git for Windows from within a Cygwin program, no?

Hm.

I could see us adding an installer option to simply copy the `bash.exe` shim from `\bin` to `\cmd`, but that would not change the default, on purpose, and therefore would not help your scenario even one bit.

A workaround would be to install a cmdkey in your setup that essentially calls `git -c alias.sh=!sh sh`, but that would be a client-side workaround.

Hmm. Not sure we can solve this puzzle.

**Comment by bk2204** [comment]
> That would possibly interfere with WSL and with calling Git for Windows from within a Cygwin program, no?

Yeah, that probably exposes some additional risk of doing that.

> I could see us adding an installer option to simply copy the `bash.exe` shim from `\bin` to `\cmd`, but that would not change the default, on purpose, and therefore would not help your scenario even one bit.

I wonder if it might be possible to install the `sh.exe` shim only for the Busybox version.  At least on my system, running `bash` from CMD and Powershell works, so I could try `bash` and then fall back to `sh` if it's missing.

> A workaround would be to install a cmdkey in your setup that essentially calls `git -c alias.sh=!sh sh`, but that would be a client-side workaround.

I wonder if we could get `git var` to learn a `SHELL_PATH` option that printed the shell path in a suitable format.  If I sent a patch for that on the list, would you be able to wire it up appropriately for Git for Windows to print a suitable shell in Windows path format?

**Comment by dscho** [comment]
> > I could see us adding an installer option to simply copy the `bash.exe` shim from `\bin` to `\cmd`, but that would not change the default, on purpose, and therefore would not help your scenario even one bit.
> 
> I wonder if it might be possible to install the `sh.exe` shim only for the Busybox version.

That's a good idea!

Do you want to give it a try? It'd be a `cp` in `mingit/release.sh` in the `build-extra` repository.

> At least on my system, running `bash` from CMD and Powershell works, so I could try `bash` and then fall back to `sh` if it's missing.
> 
> > A workaround would be to install a cmdkey in your setup that essentially calls `git -c alias.sh=!sh sh`, but that would be a client-side workaround.
> 
> I wonder if we could get `git var` to learn a `SHELL_PATH` option that printed the shell path in a suitable format.  If I sent a patch for that on the list, would you be able to wire it up appropriately for Git for Windows to print a suitable shell in Windows path format?

Totally!

**Comment by dscho** [comment]
Closing as stale.
