### ISSUE TITLE
spelling mistake  - forard instead of forward

### ISSUE THREAD

**Issue by photonkid** [git-for-windows/git#2722]
spelling mistake

![image](https://user-images.githubusercontent.com/67490671/85911432-4f58e180-b879-11ea-8147-21a328a75d3e.png)

**Comment by rimrul** [comment]
Duplicate of #2654 and [a couple other issues](https://github.com/git-for-windows/git/issues?q=is%3Aissue+forard).

Fixed in git-for-windows/build-extra#291.
