### ISSUE TITLE
Git bash: press Tab key immediately after command prompt causes a hang 

### ISSUE THREAD

**Issue by GoBigorGoHome** [git-for-windows/git#2723]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.329]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I tested with the Git Bash app (run within the bundled mintty) and CMD, the behaviors differ.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

#### For the Git Bash app:
Open the Git Bash app, press the Tab key.

#### For CMD:
Open CMD and run Git/bin/bash.exe
Press Tab, bash will hang for about 10 seconds, when the hang ends press Tab again.

 - What did you expect to occur after running these commands?

Nothing happens or what actually happened can finish in a shorter time. 

 - What actually happened instead?

#### In the Git Bash app:
After the Tab keypress, Bash hangs for about 10 secondes, and bash.exe uses 17% of the CPU. 

![bash_cpu_usage](https://user-images.githubusercontent.com/9896288/85925005-670b8680-b8c8-11ea-85c5-71b50d1d913c.png)

Then the shell prompts `Display all 7526 possibilities? (y or n)`.

#### In CMD:
With the first Tab keypress, Bash hangs for about 10 seconds, with a second Tab keypress, Bash hangs for another 10 seconds then it prompts ` Display all 7503 possibilities? (y or n)`.

Note that the two numbers are different, 7526 v.s. 7503.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
Isn't this the intended tab completion action to offer a list of all the possible commands available in the different environments (the path strings will be different)

I'm only getting "Display all 5585 possibilities? (y or n)" on my SDK bash, with lots of dll's 

Normally I only use tab completion for some refs and paths within a git command, so don't see that issue.

**Comment by GoBigorGoHome** [comment]
IMO, Tab completion action when no prefix is given is not desirable, I checked bash in WSL and msys2 and did not see this feature. Is there an option to disable the tab completion in this case or how to make bash run faster here?

**Comment by PhilipOakley** [comment]
> IMO, Tab completion action when no prefix is given is not desirable, I checked bash in WSL and msys2 and did not see this feature. Is there an option to disable the tab completion in this case or how to make Git Bash run faster here?
> 
> @PhilipOakley Did you see a hang on your machine?


I do see a short pause if I try it. 

A quick web search found https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html (`-E` option) and https://randomdrake.com/2012/01/30/disabling-empty-tab-completion-in-bash-to-prevent-delays/ (`shopt -s no_empty_cmd_completion`) as potential solutions, but it's not my area of expertise 😉 .

Tell us how you get on. Thanks

**Comment by GoBigorGoHome** [comment]
`shopt -s no_empty_cmd_completion` works. Thank you very much @PhilipOakley. I should have searched the internet a few more times before opening a issue.

**Comment by PhilipOakley** [comment]
Thanks for confirming [success ](https://xkcd.com/979/), hopefully it will help others :wink:
