### ISSUE TITLE
sh.exe would not close, unable to install 2.27.0

### ISSUE THREAD

**Issue by xhamyd** [git-for-windows/git#2724]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Running on a Microsoft Surface Laptop 3

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Tried to install Git for Windows 2.27.0

 - What did you expect to occur after running these commands?

Install to completion

 - What actually happened instead?

Would not let me install, asked me to close sh.exe. After attempting to close the process many times in Powershell, needed to quit the installer.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

![image](https://user-images.githubusercontent.com/13244158/86016456-c795e300-b9f0-11ea-9bb4-5d66abe8aaa8.png)

**Comment by dscho** [comment]
> After attempting to close the process many times in Powershell, needed to quit the installer.

Are you trying to imply that the installer called that `sh.exe`?

**Comment by PhilipOakley** [comment]
@xhamyd Usually it means that you have another 'gitish' window open somewhere that hasn't been closed. They all need closing. 

It's easy to do (Accidentally leave one running..) if you had other git windows open before you started the update (inc. the Git Gui and Gitk). 

If Windows has 'lost contact' with a file's usage you may even need to do a restart to clear out that misunderstanding about a file's 'ownership' (can happen because git runs on a number of levels). At least that's what I do ;-)

**Comment by xhamyd** [comment]
Hi @PhilipOakley, thanks for the help! That's also what I thought was happening, but I couldn't find any program in my tasklist that was Git-like (i.e. nothing named git*, nor sh*). I also tried the reinstall right after a machine restart.

**Comment by xhamyd** [comment]
So I finally found this executable in Task Manager, and it looks like it is Git for Windows' shell binary.
- Tried to close the process, failed silently
- Tried to delete the file, popup prevented me
<img width="270" alt="sh-file-location" src="https://user-images.githubusercontent.com/13244158/88838499-a2d78b80-d1a7-11ea-93d5-00323bd27b44.png">
<img width="500" alt="task-manager-sh" src="https://user-images.githubusercontent.com/13244158/88838501-a2d78b80-d1a7-11ea-999a-963607294491.png">
<img width="336" alt="unable-to-remove-sh" src="https://user-images.githubusercontent.com/13244158/88838504-a3702200-d1a7-11ea-9d03-dedd09b32122.png">

**Comment by xhamyd** [comment]
I've uninstalled and reinstalled the program manually. Turns out the uninstaller was also unable to remove sh.exe, so maybe my setup was just haunted. Closing issue, will reopen if I run into again on 2.28, thanks for the help!

**Comment by dscho** [comment]
That's curious: maybe `sh.exe` was used by the system? That would explain why you could not terminate the process. I could imagine that it was used by the "Check daily for updates" feature, for example. At this point, we cannot be sure, but it is good that we have a record so that next time this scenario arises, we can dig more efficiently. Thanks!
