### ISSUE TITLE
Failed to run '/usr/bin/bash': Permission denied

### ISSUE THREAD

**Issue by lzuliuyun** [git-for-windows/git#2728]
- [x]  I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.18362.900]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
*
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
when I execute 'git pull' command in webstorm, I get error:
.git/hooks/husky.sh: line 47: /usr/bin/basename: Permission denied

execute 'git commit' command in webstorm, I get similar error:

.git/hooks/husky.sh: line 47: /usr/bin/basename: Permission denied .git/hooks/husky.sh: line 37: /usr/bin/grep: Permission denied
.git/hooks/husky.sh: line 58: /usr/bin/dirname: Permission denied .git/hooks/husky.sh: line 58: /husky.local.sh: No such file or directory

when I start git bash, I get error:
![image](https://user-images.githubusercontent.com/6896562/86309962-88190200-bc4f-11ea-8060-a47c28f06154.png)

sometimes, I try to execute 'git commit' more times, it will work
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash、 webstorm **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

when I start  git bash, I get the following error。
![image](https://user-images.githubusercontent.com/6896562/86309962-88190200-bc4f-11ea-8060-a47c28f06154.png)

In webstorm
![image](https://user-images.githubusercontent.com/6896562/86310662-2d80a580-bc51-11ea-9490-1b31f5012d99.png)

![image](https://user-images.githubusercontent.com/6896562/86310895-aa138400-bc51-11ea-8d7c-756fde8a0b09.png)

 - What did you expect to occur after running these commands?
I expect when I execute git command,  it do not give a permission message。 Actually，it work nice before, but i don't know why bash don't work rencently。

**Comment by dscho** [comment]
This sounds like a recurring issue users saw with overzealous anti-malware. Maybe that's it?

**Comment by RiverVanRain** [comment]
Same issue on the Windows 7 32-bit, Git for Windows 2.27.0.
I can't run 'Git bash' and \usr\bin\mintty.exe.

**mintty.exe.stackdump:**
```
Exception: STATUS_ACCESS_VIOLATION at eip=00190D9A
eax=00000000 ebx=0045028B ecx=0022C6AC edx=77776B94 esi=004A0410 edi=80000000
ebp=0022CC28 esp=0022C6F4 program=C:\git\usr\bin\mintty.exe, pid 1391, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0022CC28  00190D9A (20040DB1, 20040DBB, 0022CD28, 6100AFA5)
0022CD28  6100AFA5 (00000000, 0022CD84, 61009DD0, 00000000)
0022CD84  610088B2 (00000000, 00000000, 00000000, 00000000)
End of stack trace
```

**Comment by rimrul** [comment]
That's not the same issue. That sounds a lot more like #2687 and others and should be fixed in the latest snapshots.

**Comment by RiverVanRain** [comment]
@rimrul Thanks!

**Comment by lzuliuyun** [comment]
> This sounds like a recurring issue users saw with overzealous anti-malware. Maybe that's it?

Maybe,  is there any suggestion to figure out the problem.

**Comment by dscho** [comment]
Yes.

1. Do you *have* an anti-malware? If yes, which one?

2. If you have one, try to turn it off and see whether it "fixes" the issue.
