### ISSUE TITLE
'git add --interactive' built-in doesn't exit list menu on empty input

### ISSUE THREAD

**Issue by satsuper** [git-for-windows/git#2729]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.330]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash and Powershell through Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir test
cd .\test\
git init
Initialized empty Git repository in C:/git/test/.git/
echo "foo" > bar.txt
git -c add.interactive.usebuiltin=true add -i

*** Commands ***
  1: status       2: update       3: revert       4: add untracked
  5: patch        6: diff         7: quit         8: help
What now> 4
            staged     unstaged path
  1: bar.txt
Add untracked>> 1
            staged     unstaged path
* 1: bar.txt
Add untracked>>
            staged     unstaged path
* 1: bar.txt
Add untracked>>
```
 - What did you expect to occur after running these commands?

After the empty input it should exit the list menu for adding untracked items and go back to the main list menu

 - What actually happened instead?

It presented the list menu for adding untracked items again

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by dscho** [comment]
> Enable Pseudo Console Support: Disabled

Are you sure about that? I can reproduce, but _only_ with pseudo console support enabled...

**Comment by dscho** [comment]
@satsuper once https://dev.azure.com/git-for-windows/git/_build/results?buildId=58748&view=logs&j=5437d6e9-5c1a-5300-9fd3-4614558e3141 finishes, could you download the installer or PortableGit from its artifacts and verify that #2730 fixes this?

**Comment by satsuper** [comment]
@dscho I can confirm it works with Pseudo Consoles enabled with your build.

> Are you sure about that? I can reproduce, but only with pseudo console support enabled...

So it turns out I must have installed with that option enabled some time ago and then installed a newer version without that option enabled. In `C:\Program Files\Git\etc\git-bash.config` it adds `MSYS=enable_pcon` and I guess this file isn't removed by the installer because people might add config there. Not a big deal but I can raise it as another issue if you think its a problem.

**Comment by dscho** [comment]
Oy, that's a bug in the installer, then... I'll try to take care of that later today.

**Comment by dscho** [comment]
> > Are you sure about that? I can reproduce, but only with pseudo console support enabled...
> 
> So it turns out I must have installed with that option enabled some time ago and then installed a newer version without that option enabled. In `C:\Program Files\Git\etc\git-bash.config` it adds `MSYS=enable_pcon` and I guess this file isn't removed by the installer because people might add config there.

@satsuper I just opened and merged https://github.com/git-for-windows/build-extra/pull/299, and then started https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=58754&view=results to build new Git artifacts for testing.

**Comment by satsuper** [comment]
@dscho Tested the installer from the artifacts and it removes the git-bash.config file on uninstall. Thank you for your work!

**Comment by dscho** [comment]
@satsuper excellent!
