### ISSUE TITLE
Git push/pull silently fail in latest snapshot

### ISSUE THREAD

**Issue by krryan** [git-for-windows/git#2737]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Specifically the [snapshot from here](https://wingit.blob.core.windows.net/files/index.html), as with the release version of 2.27, I had a problem with `vim`, see #2736 and #2689.

```
$ git --version --build-options

git version 2.27.0.windows.1.14.g53ca6a200a.20200703211506
cpu: x86_64
built from commit: 53ca6a200af1dac9408eb552b469b2f8b48534de
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.900]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
git push
git pull origin
git push origin
git push origin master
```
 - What did you expect to occur after running these commands?

These commands pull from the upstream branch, or push to the same, or at the very least some kind of error message.

 - What actually happened instead?

Absolutely nothing. There is no output, I’m just left with a new prompt:

```
$ git pull

$ _
```

I do note that `git fetch --all` **does** report an error, specifically

```
$ git fetch --all
Fetching origin
error: Could not fetch origin
```

Using `git fetch` or `git fetch origin` is again silent.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It appears to affect all repositories. That includes `git fetch --all`.

**Comment by dscho** [comment]
Thank you for the report! I can reproduce this locally and will work on a fix. The most likely issue is that cURL has a new dependency on libbrotli, and I think that might not be included in the distribution for some reason.

**Comment by dscho** [comment]
@krryan please note that the Pipeline to build and publish the updated `mingw-w64-curl` package [is running](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=58890&view=results), and after that, a new snapshot will have to be built. I'll try to remember to ask you to test it once it is available.

**Comment by krryan** [comment]
@dscho So is there any update on this? The latest snapshot I see (on linked page) is still from 3 July.

**Comment by dscho** [comment]
> 
> 
> @dscho So is there any update on this? The latest snapshot I see (on linked page) is still from 3 July.

For some reason, the [the Release Pipeline](https://dev.azure.com/git-for-windows/git/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?_a=release-pipeline-progress&releaseId=39) was not triggered automatically (granted, I worked all night and all morning on fixing things, so maybe it did not trigger when [the rerun of the Git artifacts Pipeline](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=58957) succeeded).

**Comment by krryan** [comment]
OK, thanks, I see that’s running now. Much appreciated.

**Comment by dscho** [comment]
It's [there](https://wingit.blob.core.windows.net/files/index.html) now.

**Comment by krryan** [comment]
@dscho OK, that seems to fix the problems, thank you.
