### ISSUE TITLE
Typo in git for Windows 2.27.0 installer

### ISSUE THREAD

**Issue by bmshort** [git-for-windows/git#2740]
In the "Choose the default behavior of `git pull`" dialog in the Windows installer for Git 2.27.0, there is a typo in the 3rd option.  It reads "Only ever fast-forard" and should read "Only ever fast-forward".  Screenshot attached.
![git_windows_installer_typo](https://user-images.githubusercontent.com/3130300/86978247-68e90b80-c14c-11ea-8b7e-bfc2398532f5.png)

**Comment by rimrul** [comment]
Duplicate of #2652 and others. Fixed in git-for-windows/build-extra#291

**Comment by dscho** [comment]
Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).
