### ISSUE TITLE
Typo in the Git 2.27.0 setup installer for windows 10 64-bit

### ISSUE THREAD

**Issue by SaulHarwin** [git-for-windows/git#2744]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?
I kept the defaults.

### Details

 - Typo found in the windows git 2.27.0 setup installer. 

 - Option **"Choose the default behavior of git pull"** 

"**Only ever fast-forard**" Should be "**fast-forward**"

### Image 

 - Third option
![image](https://user-images.githubusercontent.com/56323217/87222656-76311080-c36d-11ea-80b3-899ab1b9550a.png)

**Comment by rimrul** [comment]
Duplicate of #2652 and others. Fixed in git-for-windows/build-extra#291. Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).
