### ISSUE TITLE
Duplicate entry in 2.28.0-rc0 release notes

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#2746]
https://github.com/git-for-windows/git/releases/tag/v2.28.0-rc0.windows.1

* Comes with MSYS2 runtime (Git for Windows flavor) based on Cygwin 3.1.5.
...
* Comes with MSYS2 runtime (Git for Windows flavor) based on Cygwin 3.1.6.

**Comment by dscho** [comment]
Thank you!

**Comment by dscho** [comment]
Fixed in https://github.com/git-for-windows/build-extra/commit/84b7f10473beac81cfd569b6f6ec4aa3043920d4
