### ISSUE TITLE
git bash can't find npm  but npm -v worked

### ISSUE THREAD

**Issue by Huberyfight** [git-for-windows/git#2749]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 win10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.18362.959]       
(c) 2019 Microsoft Corporation。保留所有权利。
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

C:\\SoftWare\\Git\\bin\\bash.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
npm run dev
```
 - What did you expect to occur after running these commands?

that command(npm run dev) work in CMD now, and npm -v also worked in bash.exe.
PS D:\vue-element-admin> npm run dev

> vue-element-admin@4.4.0 dev D:\vue-element-admin
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 16257ms                                                                9:38:11 ├F10: AM┤

  App running at:
  - Local:   http://localhost:9527/
  - Network: http://192.168.3.7:9527/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

 - What actually happened instead?

> vue-element-admin@4.4.0 dev D:\vue-element-admin
> vue-cli-service serve

'"node"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 9009
npm ERR! vue-element-admin@4.4.0 dev: `vue-cli-service serve`
npm ERR! Exit status 9009
npm ERR! 
npm ERR! Failed at the vue-element-admin@4.4.0 dev script.   
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hubery\AppData\Roaming\npm-cache\_logs\2020-07-18T01_38_49_445Z-debug.log
The terminal process "C:\SoftWare\Git\bin\bash.exe '-c', 'npm run dev'" terminated with exit code: 49.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/PanJiaChen/vue-element-admin.git
![微信截图_20200718094359](https://user-images.githubusercontent.com/23059411/87841888-3fae4500-c8db-11ea-89f5-1b6a729359ae.png)

**Comment by rimrul** [comment]
Since `npm` is obviously outputting error messages, `Git bash` seems to find `npm` that also explains why `npm -v` works.

>npm ERR! code ELIFECYCLE
npm ERR! errno 9009
npm ERR! vue-element-admin@4.4.0 dev: vue-cli-service serve
npm ERR! Exit status 9009

This looks like `npm` is trying to launch `vue-cli-service`, but fails. The 9009 seems to indicate a `File not Found` error. Either way, this doesn't seem to be a `Git for Windows` issue.

**Comment by Huberyfight** [comment]
Thanks a lot for your reply.
