### ISSUE TITLE
Can't authenticate to Azure DevOps server ?

### ISSUE THREAD

**Issue by fmiermont** [git-for-windows/git#2752]
Hello,

It seems that after some GPO's change on the AD related to NTLM we cannot push nor clone any of our Repos on premise. (latest Git for windows version 2.27.0.windows.1)
Got the error 
`Cloning into 'C:\Projets\Git\MyProject...
Error encountered while cloning the remote repository: Git failed with a fatal error.
Authentication failed for 'https://mytfs.mydomain.lan:8443/DefaultCollection/Test/_git/Test/'`

On the mytfs server, I've also got a audit failure (Logon) event ID 4625 :

> An account failed to log on.
> 
> Subject:
> 	Security ID:		NULL SID
> 	Account Name:		-
> 	Account Domain:		-
> 	Logon ID:		0x0
> 
> Logon Type:			3
> 
> Account For Which Logon Failed:
> 	Security ID:		NULL SID
> 	Account Name:		mylogin
> 	Account Domain:		mydomain
> 
> Failure Information:
> 	Failure Reason:		An Error occured during Logon.
> 	Status:			0x80090302
> 	Sub Status:		0xC0000418
> 
> Process Information:
> 	Caller Process ID:	0x0
> 	Caller Process Name:	-
> 
> Network Information:
> 	Workstation Name:	myworkstation
> 	Source Network Address:	192.168.1.60
> 	Source Port:		56366
> 
> Detailed Authentication Information:
> 	Logon Process:		NtLmSsp 
> 	Authentication Package:	NTLM
> 	Transited Services:	-
> 	Package Name (NTLM only):	-
> 	Key Length:		0

Of course we revert back the change on GPO but without success. Maybe it's not related after all ?
I really struggle to get more log to know where to look, any help would be greatly appreciated !

Current git config:
```
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
credential.helper=manager
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
core.autocrlf=true
user.name=John Doe
user.email=jdoe@mydomain.fr
http.sslbackend=schannel
gui.recentrepo=C:/Projets/TeamGit/TravelGit
credential.helper=wincred
credential.modalprompt=true
```

Also, U've also tried to create a new azure dev ops server from a scratch VM, using single server modele (SQL Express, no report server, basic installation) to avoid any complication. Same issue, my git refuse to auth.

Regards,

**Comment by Tanato** [comment]
I've had some similar issues today. Updated my Git version to 2.28 RC1 and checked the Git Credentials Core option when installing and it worked for me.

**Comment by fmiermont** [comment]
I've tried with 2.28 RC1 with the new Credentials Core option without success (and tried without still with this RC1 to be sure).

I've forget to mention that I could access the repos using my browser without any issue.

**Comment by fmiermont** [comment]
Ok I found where the problem was... 

So, what was the step to reproduce the authentication failure :
1. Enable GPO "Network Security: Restrict NTLM: NTLM authentication in this domain" to Define : Deny all
2. have authentication issues with Git server. Found NTLM related event on the devops server (Event ID 4625, Logon)

> An account failed to log on.
> 
> Subject:
> 	Security ID:		NULL SID
> 	Account Name:		-
> 	Account Domain:		-
> 	Logon ID:		0x0
> 
> Logon Type:			3
> 
> Account For Which Logon Failed:
> 	Security ID:		NULL SID
> 	Account Name:		user@mydomain.fr
> 	Account Domain:		
> 
> Failure Information:
> 	Failure Reason:		An Error occured during Logon.
> 	Status:			0x80090302
> 	Sub Status:		0xC0000418
> 
> Process Information:
> 	Caller Process ID:	0x0
> 	Caller Process Name:	-
> 
> Network Information:
> 	Workstation Name:	WORKSTATION
> 	Source Network Address:	192.168.8.66
> 	Source Port:		61759
> 
> Detailed Authentication Information:
> 	Logon Process:		NtLmSsp 
> 	Authentication Package:	NTLM
> 	Transited Services:	-
> 	Package Name (NTLM only):	-
> 	Key Length:		0
> 
> This event is generated when a logon request fails. It is generated on the computer where access was attempted.
> 
> The Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.
> 
> The Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).
> 
> The Process Information fields indicate which account and process on the system requested the logon.
> 
> The Network Information fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.
> 
> The authentication information fields provide detailed information about this specific logon request.
> 	- Transited services indicate which intermediate services have participated in this logon request.
> 	- Package name indicates which sub-protocol was used among the NTLM protocols.
> 	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.

As all the developpers cannot work anymore, revert the GPO by uncheck the define checkbox. Force gpupdate. Check with RSOP.msc that the GPO does not apply anymore, and the devops server AND any DC.
Still having the same behaviour (no authentication, same event on server).
After hours and hours, realize that you have to set the GPO to check the define checkbox with "Disable" choice. This WILL authorise NTLM again....
And now everytings work again.

I have now to investigate to understand why devops server does not use Kerberos, but that's completly unrelated.

Hope this could help someone on day, the last day drive me completly mad...
