### ISSUE TITLE
"Welcome to bplaced" showing after running git bash

### ISSUE THREAD

**Issue by constantinDev** [git-for-windows/git#2755]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10, 64 bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.959]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Actually none, the issue just came up
```
 - What did you expect to occur after running these commands?

Just starting the git bash normally

 - What actually happened instead?

It showed `Welcome to bplaced!` and then continued. I never installed anything like bplaced on my machine and a reinstall wont help.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

-

**Comment by rimrul** [comment]
Sounds like you have a `~/.bashrc`, `~/.bash_profile` or `~/.profile` file that prints this message.

**Comment by constantinDev** [comment]
> Sounds like you have a `~/.bashrc`, `~/.bash_profile` or `~/.profile` file that prints this message.

Thanks, I found the file and removed the line. That fixed it! Honestly I thought I installed a virus or something, thank god!
