### ISSUE TITLE
Error during 'git checkout my_branch' resulted in changes being made to the current branch. 

### ISSUE THREAD

**Issue by ArnoSoontjens** [git-for-windows/git#2759]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
Running a 64 bit windows 10, git version 2.27.0.windows.1
```
$ git --version --build-options
git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18363.959]
```
```
Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

`git status` showed my current working tree was clean. All files committed, nothing left in staging.
```
git checkout my_branch
```
 - What did you expect to occur after running these commands?
I got an error saying that I had no permission to create a directory. (`fatal: cannot create directory at 'Frontend/src/app/contacts/earNoseThroatPhysicians/detail': Permission denied`)I expected git to role back the changes that were made up to this point and abort the checkout, or at least move me to some undefined state.

 - What actually happened instead?
Instead the changes that were made up to the point where the new directory was to be created, all showed up on my current working branch, that I was trying to change from. This left me with a whole bunch of files and directories that were not supposed to be on this branch.

**Comment by dscho** [comment]
Welcome to the Git for Windows project!

The issue you reported seems not to be a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
