### ISSUE TITLE
Chinese display garbled code in "git reset" command above 2.27.0

### ISSUE THREAD

**Issue by Xiphin** [git-for-windows/git#2760]
When I use git-bash.exe(above 2.27.0) to run "git reset --hard origin/master" command , Chinese display garbled code. But running it in 2.26.2(below 2.26.2) is normal.

**Comment by Taswen** [comment]
I have a similar problem. In git bash(git version 2.27.0.windows.1 64bit), the 'git status' can't show display Chinese correctly.But in cmd, everything is fine.
I have set the .gitconfig file, but it doesn‘t work. The same goes for relinstalling. 
I don’t know if I’m the only one with this problem. 
![批注 2020-07-26 002020](https://user-images.githubusercontent.com/30777327/88461811-6111c100-ced9-11ea-9915-61c9f2fa75c4.jpg)

**Comment by lourdas** [comment]
This must be related with issues #2648 and #2734.

**Comment by xianghongai** [comment]
## Chinese characters are garbled, setting utf-8 is also garbled

Hi,

There are some problems here.

I have configured the character encoding in .gitconfig:

```yaml
[core]
  quotepath = false
[gui]
  encoding = utf-8
[i18n]
  commitencoding = utf-8
  logoutputencoding = utf-8
```

and Git Bash configed: `Options` > `Text` > Locale: `zh_CN`, Character set: `UTF-8`

However, when executing `git pull/reset/status`, Chinese characters still appeared garbled.

`git reset`:

```bash
Xiang@Xiang MINGW64 /c/me/front-end-note (master)
$ git reset --hard df576e2
HEAD is now at df576e2 doc: 琛ュ厖 ES5 缁ф壙
```

`git pull`:

```bash
Xiang@Xiang MINGW64 /c/me/front-end-note (master)
$ git pull
Updating df576e2..bd2894b
Fast-forward
 AngularJS/assets/AngularJS-Component-LifeCycle.png | Bin 0 -> 154433 bytes
 AngularJS/chapter/Components.md                    |   2 +
 AngularJS/chapter/Scopes.md                        |  18 ++-
 ESLint.md                                          | 118 ++++++++++++++
 NPM.md                                             | 173 +++++++++++++--------
 React/Context.md                                   |   3 +
 React/Refs.md                                      |  47 ++++++
 React/react-architecture.png                       | Bin 0 -> 56624 bytes
 React/react-lifecycle-methods-diagram.png          | Bin 0 -> 41677 bytes
 React/鍗忚皟.md                                    |  33 ++++
 i18n 瑙ｅ喅鏂规.md                               |  76 +++++++++
 浠ｇ爜鐩綍鏂囦欢缁撴瀯.md                        |  15 ++
 娣卞叆鐞嗚ВES6/9.JavaScript涓殑绫?md           |  13 +-
 13 files changed, 426 insertions(+), 72 deletions(-)
 create mode 100644 AngularJS/assets/AngularJS-Component-LifeCycle.png
 create mode 100644 ESLint.md
 create mode 100644 React/Context.md
 create mode 100644 React/Refs.md
 create mode 100644 React/react-architecture.png
 create mode 100644 React/react-lifecycle-methods-diagram.png
 create mode 100644 React/鍗忚皟.md
 create mode 100644 i18n 瑙ｅ喅鏂规.md
 create mode 100644 浠ｇ爜鐩綍鏂囦欢缁撴瀯.md
```

`git status`:

```bash
Xiang@Xiang MINGW64 /c/me/front-end-note (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   浜夎涓庢帰绱?md

no changes added to commit (use "git add" and/or "git commit -a")
```

`git log` command is correct:

```bash
Xiang@Xiang MINGW64 /c/me/front-end-note (master)
$ git log --oneline -3
bd2894b (HEAD -> master, origin/master) i18n
73dceea 代码目录文件结构
89121aa 更新 NPM
```

My environment:

- windows 10 home chinese edition
- git version 2.28.0.windows.1

This problem did not appear in the previous version, and we look forward to fixing it.

Thanks.

**Comment by dscho** [comment]
Maybe this has something to do with the console output code page? Can you try running the same command, after running `cmd /c chcp 65001`?

**Comment by xianghongai** [comment]
> Maybe this has something to do with the console output code page? Can you try running the same command, after running `cmd /c chcp 65001`?

Tried it, but it doesn't work.

**Comment by azige** [comment]
I encountered similar problems in 2.28.0

![20200925154352](https://user-images.githubusercontent.com/1646859/94241284-0c291000-ff47-11ea-917b-9988d66bf1b9.png)

I tried 2.28.0.windows.1.52.gbcabfe850c.20200924200432 later. It seems that it has been fixed.

![20200925154845](https://user-images.githubusercontent.com/1646859/94241814-bc971400-ff47-11ea-8872-ab9c44714bee.png)

**Comment by dscho** [comment]
@Xiphin Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

If the problem persists, please publish a repository to demonstrate the issue.

**Comment by Xiphin** [comment]
> @Xiphin Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).
> 
> If the problem persists, please publish a repository to demonstrate the issue.
I tried git version 2.29.1.windows.1. It seems that it has been fixed.

**Comment by dscho** [comment]
> I tried “git version 2.29.1.windows.1”. It has been fixed.

Perfect!

**Comment by chucklu** [comment]
@dscho  I encounter the garbled code problem after I installed `git version 2.31.0.windows.1`. And the installer also broke the font setting of my notepad++ editor and TortoiseDiff. Currently the git bash can not show file name and file content which contains Chinese characters.

**Comment by dscho** [comment]
> 
> 
> @dscho I encounter the garbled code problem after I installed `git version 2.31.0.windows.1`. And the installer also broke the font setting of my notepad++ editor and TortoiseDiff. Currently the git bash can not show file name and file content which contains Chinese characters.

Please file a new ticket, including all the information necessary to reproduce/understand the problem.
