### ISSUE TITLE
Git 2.27.0 32-bit on Windows 7 SP1 32 bit: Git Bash not running and produces mintty.exe.stackdump

### ISSUE THREAD

**Issue by escherstair** [git-for-windows/git#2763]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git 2.27.0 32-bit

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: i686
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 4

```

 - Windows 7 SP1 32-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - Options chosen: Defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

n.a.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
n.a.
```
 - What did you expect to occur after running these commands?

Bash to start ;-)

 - What actually happened instead?

Bash did not start ;-)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

all repositories

This behavior is identical to #2761 but on a different architecture.

**Comment by LassazVegaz** [comment]
I am having the same problem, but operating system is Windows 10

**Comment by rimrul** [comment]
Could you test if the Issue still occurs with version 2.28.0?

**Comment by escherstair** [comment]
Version 2.28.0 fixed the issue.
Thanks a lot
