### ISSUE TITLE
GIt for Windows cannot checkout long (>256 char) path names.

### ISSUE THREAD

**Issue by akrieger** [git-for-windows/git#277]
It seems like this was fixed in older versions of msysgit, but this doesn't seem to work anymore. When trying to rebase a node module repo I was working in, I get this and the rebase fails.

warning: unable to access 'node_modules/flow-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/.gitattributes': Filename too long
error: unable to create file node_modules/flow-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/index.js (Filename too long)
error: unable to create file node_modules/flow-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/package.json (Filename too long)
error: unable to create file node_modules/flow-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/readme.md (Filename too long)
fatal: cannot create directory at 'node_modules/flow-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite': Filename too long

**Comment by dscho** [comment]
Details. Lots of details. Details, that are not in the bug report ;-)

Most important detail: is your [`core.longpaths`](https://github.com/git-for-windows/git/blob/1687e38d2d35101dca475096014775e067e66a55/Documentation/config.txt#L724-L729) set appropriately?

**Comment by akrieger** [comment]
Ah, you got me there. I thought it was supported out of the box (based on what I'd read in earlier bug reports in the msysgit repo, eg https://github.com/msysgit/msysgit/issues/52). Setting core.longpaths true makes it work. Sorry!

I'll note that despite you trying to make it so in that issue, I didn't 'get the message' about longpaths :/ Honestly at that point though instead of just glossing over it and thinking 'ok I see fixes attached, therefore it works' I could've read a bit more closely :(

**Comment by dscho** [comment]
> I thought it was supported out of the box (based on what I'd read in earlier bug reports in the msysgit repo, eg msysgit/msysgit#52). Setting core.longpaths true makes it work.

Good to hear that it works.

Now, you could help me here a bit: would you mind adding an entry to [our FAQ](https://github.com/git-for-windows/git/wiki/FAQ) and/or to [our ReleaseNotes' *Known Issues* section](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues)?

**Comment by akrieger** [comment]
Done, added it to the FAQ, and linked to the wiki page in the msysgit repo for additional information.
