### ISSUE TITLE
2.28: git pull and git fetch opening a new Git Bash window that does nothing

### ISSUE THREAD

**Issue by krryan** [git-for-windows/git#2771]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.959]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am using Microsoft Visual Studio Code, which has a “Source Control” tab that interacts with Git. I haven’t actively used it in any way since installing 2.28, and I doubt it matters, but since I am having trouble reproducing this behavior myself I figured I’d mention everything.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
git fetch --all
```

However, these commands work correctly on a fresh Git Bash; they only started acting up after I had been working for some time. During that time, I used `git checkout`, `git checkout -b`, `git status`, `git add .`, `git commit`, `git commit -a`, and `git branch -m`. I also used `git checkout - && git pull`, which is when I noticed the problem.

Starting a new Git Bash, I was not able to reproduce this bug, even when messing with similar commands in a new window. I do not know what triggered this state where these commands failed.

 - What did you expect to occur after running these commands?

Git would pull or fetch, respectively, or at least an error would be raised.

 - What actually happened instead?

A new Git window opens, and after several seconds, disappears. For `git pull`, this window remains empty. For `git fetch --all`, it says `Fetching origin`. Nothing is pulled or fetched in either case.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Doesn’t seem related to any repository.

**Comment by dscho** [comment]
Could you see whether it has anything to do with starting `vim` and closing it?

Also, could you test whether the issue continues to exist if you reinstall v2.28.0, disabling the Pseudo Console support?

**Comment by krryan** [comment]
@dscho I have never seen this effect if I open `vim` manually—I don’t do that _often_, but I do sometimes, and in any event I tested it some. Only after `git commit`. It also seems to persist for a little while after—I do a lot of merging of PRs where I might adjust something, use `git commit`, then `git checkout - && git pull` followed by `git merge --no-ff whatever-branch`. The output from `git commit` would be messed up, the output from `git checkout -` would be messed up, but the output from `git pull` (in the same expression) and `git merge` would not.

I haven’t tested disabling pseudo-console support yet.

**Comment by dscho** [comment]
> I haven’t tested disabling pseudo-console support yet.

I bet that would work around it, that's why I suggested testing it.

**Comment by PStoner3** [comment]
I am experiencing the same issue with version 2.28.0. When this does happen, frequently, as @krryan describes, I have to close the Git Bash terminal and start over. Also, I never enable the pseudo-console feature and this still occurs.

I've only started seeing this behavior with 2.28.0.

**Comment by dscho** [comment]
@PStoner3 please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html). This is a shot in the dark, but there have been _some_ patches since v2.28.0 that _might_ fix this (or at least work around it).

**Comment by dscho** [comment]
Closing as stale.
