### ISSUE TITLE
"up to date" spelling inconsistency 

### ISSUE THREAD

**Issue by dj-ryan** [git-for-windows/git#2773]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.959]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

n/a

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
git pull
```
 - What did you expect to occur after running these commands?

The only problem being `git push` when there is nothing committed displays `Everything up-to-date` and `git pull` displays `Already up to date.` when there nothing to pull. This is a small spelling inconsistency with the phrase "up to date"

 - What actually happened instead?

See above.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by PhilipOakley** [comment]
If you look though the code base, the two usages are roughly equally common. Any changes would need to be proposed and discussed upstream on the git@vger.kernel.org list (see https://lore.kernel.org/git/ for the list archive)

I suspect that it will be seen as user facing code churn, and that all occurrences would need fixed (once the right choice has been decided, if found), along with associated patch submission. 

However it's probably still worth raising the issue at least to get clarification.

**Comment by rimrul** [comment]
`am/up-to-date` in 2017 already set a bit of a precedent when to use `up to date` and when to use `up-to date`. 

>Follow the Oxford style, which says to use "up-to-date" before the noun,
but "up to date" after it. Don't change plumbing (specifically
send-pack.c, but transport.c (git push) also has the same string).

>I figure "Already up-to-date." is "[X is|I am] already up to date." as
opposed to "Already [have] up-to-date [X].".

That's the internal reasoning for this inconsistency: The `git push` message is a plumbing message that should not be changed and the `git pull` message is a porcelain message following Oxford style.

See [`7560f547 (treewide: correct several "up-to-date" to "up to date", 2017-08-23)`](https://github.com/git/git/commit/7560f547e614244fe1d4648598d4facf7ed33a56) and the corresponding [mailing list discussion](https://lore.kernel.org/git/CAJXxHvVzTrhJk6pFsOzUKBuU2VcW41-tMk5A7s+rxXsacXpppw@mail.gmail.com/t/#u).
