### ISSUE TITLE
In git-gui I cannot stage hunks of files added with 'git add --intent-to-add' anymore since 2.28

### ISSUE THREAD

**Issue by pascalmuller** [git-for-windows/git#2779]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.959]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

NO

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ echo "test" > text.txt
$ git add -N text.txt
$ git gui
I then try to stage the hunk or a line in the test.txt file in git gui using the right click menu. 
```
 - What did you expect to occur after running these commands?

I expected that I could add a hunk or line in the new file, instead nothing happens after clicking one of these options in the context menu. To make sure you understand me, I added a screenshot of the context menu in question:

![context-menu-git-gui](https://user-images.githubusercontent.com/831387/89200091-d4899180-d5af-11ea-9e9f-88e1fc054c55.png)

 - What actually happened instead?

The hunk can not be added through the GUI. (nothing happens after clicking this option in the right click menu) Also note that the terminal prints the following errors as well while starting git gui: 
```
error: no icon for .vpane.files.workdir.list state={A} text.txt
error: no desc for state={AA} text.txt
```
I downgraded to 2.27.0 to validate if the recent upgrade broke this. In 2.27.0 everything works fine! No error is printed when starting git gui and i can add a hunk or line using the right click menu. 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I can replicate this problems in multiple repositories.

**Comment by dscho** [comment]
This might be related to https://lore.kernel.org/git/20200808074959.35943-1-ray@ameretat.dev/. Would you be able to [build Git](https://github.com/git-for-windows/git/wiki/Building-Git) from scratch? If so, you could test whether merging the `rp/ita-diff-modefix` branch from https://github.com/gitster/git fixes the issue (and in that case, you could open a PR and we'd get that fix really quickly).

**Comment by pascalmuller** [comment]
@dscho I have never built Git before, but I decided to give it a shot. 

Unfortunately, it does not seem to solve the bug described here. 

Just to be certain I did this correctly; these are the steps I've done. 
```
** INSTALL GIT SDK
$ sdk cd git
$ git checkout -b test
$ git fetch https://github.com/gitster/git.git rp/ita-diff-modefix
$ git merge FETCH_HEAD
$ make install
** RUN STEPS TO REPRODUCE in another directory, as outlined in ticket
```
To be certain I was using the version of Git I built, I added an extra line of output to git status and repeated the steps. As I saw my change, I am quite certain the steps above have worked; but the merge of `rp/ita-diff-modefix` did not solve it.

**Comment by dscho** [comment]
Thanks for testing! And: bummer that it did not fix it. Let me give it a whirl.

**Comment by dscho** [comment]
Oh my. I totally wrote the wrong branch name: `rp/apply-cached-with-i-t-a` is the one I _actually_ meant.

But even then, things don't work, there need to be a couple fixes in Git GUI's code itself.

**Comment by dscho** [comment]
I have a tentative fix that I just submitted to the Git mailing list for review: https://github.com/gitgitgadget/git/pull/699

**Comment by pascalmuller** [comment]
Happy I could help a little bit; thanks for looking into it so quickly!

Hope it'll be fixed soon.

**Comment by dscho** [comment]
@pascalmuller As I merged this, there will hopefully soon be a new [snapshot](https://wingit.blob.core.windows.net/files/index.html) for you to test. It would be good if you could verify that it works (ideally within the next 24h, i.e. before v2.29.0 is due).

**Comment by dscho** [comment]
(FWIW the installer and friends are [being built right now](https://dev.azure.com/git-for-windows/git/_build/results?buildId=64500&view=results) and [this Release Pipeline](https://dev.azure.com/git-for-windows/git/_release?_a=releases&view=mine&definitionId=2) should then automatically upload the snapshot, in case you are interested to see the progress.)

**Comment by pascalmuller** [comment]
@dscho I verified that the scenario I described in this ticket is working in the latest snapshot. I'm really happy that this is working again, thanks for your efforts and those of everyone involved.

**Comment by dscho** [comment]
Excellent, thank you!!!
