### ISSUE TITLE
git commands terminate mid operation

### ISSUE THREAD

**Issue by uNiversaI** [git-for-windows/git#278]
When Im using Windows I use github desktop whatever the latest release is, Ive reported this to them and was suggested it is a gt issue rather than a github desktop application issue.

Windows 7 Sp1
Notepad++ 6.8.1 as default editor
Github Desktop 3.0.3
(any more information requested please specify and let me know how to retrieve it).

This issue happens when using cmd/poweshell terminal and running commands like ```git rebase -i HEAD~#``` and am squashing a few commits into one.

Notepad++ is triggered 1st time and file opens and Im midway into editing file e.g which commits to squash/reword and before I get a chance to finish in cmd terminal it skips the operation to end. whatever the file I was editing is left as a uncommitted change and has to be discarded or deleted.

This repeats sometimes 3 or 4 times in a row before it sticks.

Ive noticed this also happens in other operation like ```git commit --amend``` so anything that opens the editor to edit some file save and close.

Expected behavior is edit whats needed when files trigger open, save changes & close  notepad++ and wait for git to takeover and finish operation to the end.

**Comment by GuentherVIII** [comment]
Try setting your editor to "notepad++ -multiInst". Plain notepad++ will only tell the already running instance to open the file before exiting, which looks as if you finished editing the file in record time.

**Comment by uNiversaI** [comment]
Lets see if that nugget is gold, ran
```git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst"``` and confirm added.

Ill report back with results.

**Comment by dscho** [comment]
@uNiversaI any news?

**Comment by uNiversaI** [comment]
I wanted to test more in depth with a few actual operations but a superficial test is yielding positive results at this time, so its encouraging.

**Comment by dscho** [comment]
Good! I plan to move https://github.com/msysgit/msysgit/issues/218 to the new Git for Windows org.

Would you be interested in working on the installer so it can detect notepad and auto-configure it as commit message (and rebase -i and ...) editor?

**Comment by uNiversaI** [comment]
> Good! I plan to move msysgit/msysgit#218 to the new Git for Windows org.
> 
> Would you be interested in working on the installer so it can detect notepad and auto-configure it as commit message (and rebase -i and ...) editor?

who moi?

**Comment by dscho** [comment]
@uNiversaI yep, I think you

- have the need
- have the knowledge
- have my support

so... what could go wrong? :smiley:

**Comment by uNiversaI** [comment]
have the need :heavy_check_mark: 
have the knowledge :x: 
have my support :question: 

So no idea what I would be doing there to begin with, not familiar with installers or the source code, so Im hardly the right person for this task.
However if I were it would already be done. :)

**Comment by dscho** [comment]
Well, okay. I am sure you don't mind that I close this ticket now, given that it is not a Git for Windows bug (yet, because the installer does not autodetect Notepad yet).

**Comment by uNiversaI** [comment]
Well it is a issue even if not a bug, but close it I dont mind even though there really was no opportunity to test the ***fix*** properly.

Ide be willing to have a look at fixing this properly if you point me in right direction

**Comment by dscho** [comment]
>  there really was no opportunity to test the fix properly

Yes there was... Teach the Git for Windows installer to be more user-friendly and offer to configure Notepad++ as the default editor...

That would have the benefit of not having to clutter the ProGit book with information relevant only to a tiny fraction of users...

**Comment by uNiversaI** [comment]
> Yes there was... Teach the Git for Windows installer to be more user-friendly and offer to configure Notepad++ as the default editor...

Not if you dont know what you doing, you half expected me to do that when I havent a clew, so unless you do then thers no other solution now.

**Comment by dscho** [comment]
@uNiversaI just ask and I tell you what to do.

First of all, follow the description on our wiki how to build your own installer: https://github.com/git-for-windows/git/wiki/Making-an-installer

Then patch `/usr/src/build-extra/installer/install.iss.in` to add a new installer page similar to https://github.com/git-for-windows/build-extra/commit/cbcf69b9aaa4d5a0ba90a3cd3c150b0418608b23

After that, you can easily add code to detect the presence of Notepad++:

```pascal
if DirExists(ExpandConstant('{pf}\Notepad++')) then begin
    ...
end;
```

(see http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_direxists and http://www.jrsoftware.org/ishelp/index.php?topic=consts for more information)

You probably also want to replace the use of `TCheckBox` by `TRadioButton` because we want to allow the user to choose one of several editors, not multiple editors.

You will want to imitate the fscache code to configure the editor in the end.

And then test, test, test.

After that: Pull Request and eternal fame.

**Comment by uNiversaI** [comment]
You seriously give me too much credit and assume Im interested in wasting hours on end for a 2 second gain.

I should have said this from the beginning. Sorry for wasting your time.

**Comment by uNiversaI** [comment]
> Try setting your editor to "notepad++ -multiInst". Plain notepad++ will only tell the already running instance to open the file before exiting, which looks as if you finished editing the file in record time.

thx for that solved it with

> git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst"

**Comment by PhilipOakley** [comment]
> You seriously give me too much credit and assume Im interested in wasting hours on end for a 2 second gain.

It wouldn't be a "waste". It would save the hours of many in their similar searches for the right invocation for the notepadd++ editor (been there...).

> I should have said this from the beginning. Sorry for wasting your time.

Hopefully you will have some spare time eventually that can be fed back into a suitable FOSS project. All the best.
--
Philip

**Comment by uNiversaI** [comment]
> It wouldn't be a "waste". It would save the hours of many in their similar searches for the right invocation for the notepadd++ editor (been there...).

Yes sure, I have no interest in learning about windows installers, I dont use it often, I am willing to contribute to documentation  and hopefully help people find a solution faster assuming they RTFM.

> Hopefully you will have some spare time eventually that can be fed back into a suitable FOSS project. All the best.

Even with time, there's no interest, people who seemingly more interested for over a year havent touched it, and while I appreciated being canvassed for the task it simply boils down to knowledge, not being a developer and not having interest to get that involved with something I use in windows rarely.

This is why I am willing to contribute to documentation it seems straight forward and if thats not desired then oh well then.

**Comment by dscho** [comment]
@uNiversaI please note that what you just said several times is a big slap into the face of all the contributors who made Git for Windows possible. Essentially, what you said -- repeatedly, to add insult to injury -- is: "You worked hard to make my life easier. Now I will not do anything for you in return. Not a single thing."

I am sure that was not your intention, yet that is exactly what everybody else understands, loud and clear.

If that is the message you are comfortable sending, then I guess I have nothing else to add to this conversation.

**Comment by uNiversaI** [comment]
Not at all, I dont have time to learn the necessary knowledge to contribute here on something I incidentally used a couple of times when Im using Windows OS.

> "You worked hard to make my life easier. Now I will not do anything for you in return. Not a single thing."

Not true, Not true at all, that is just silly.
**And to reiterate, Ill be happy to spend some time in documentation and opened https://github.com/progit/progit2/issues/365 for discussion on which way is best to go about that.**

If you cant understand what Im saying, then I regret it immensity and will terminate this now uncomfortable repartee here and now.

Accpet my apologies and goodbye now.
