### ISSUE TITLE
GitPortable (installer) is Not a Valid Win32 Application

### ISSUE THREAD

**Issue by Radon8472** [git-for-windows/git#2780]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
```
- PortableGit-2.28.0-32-bit.7z.exe

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows XP [Version 5.1.2600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

NONE
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

NONE

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

    **Method 1**
    - Download https://github.com/git-for-windows/git/releases/download/v2.28.0.windows.1/PortableGit-2.28.0-32-bit.7z.exe e.g. with Firefox
    - DoubleClick on PortableGit-2.28.0-32-bit.7z.exe when download is completed

    **Method 2**
    ```
    wget https://github.com/git-for-windows/git/releases/download/v2.28.0.windows.1/PortableGit-2.28.0-32-bit.7z.exe
    PortableGit-2.28.0-32-bit.7z.exe
    ```

 - What did you expect to occur after running these commands?

**I expected that Instalation of GitPortanle should start**

 - What actually happened instead?

**A Windows Alert Dialog opened with the message:** `D:\Download\PortableGit-2.28.0-32-bit.7z.exe ist keine zulässige Win32-Anwendung` (in english this means `PortableGit-2.28.0-32-bit.7z.exe is Not a Valid Win32 Application`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

## What I already did:
- I tried to download the installer multiple times to ensure it is no download Problem
- Completed a Virus Scan on the downloaded file (no curruption)
- I Checked the sha-checksum: it is `11b854e9246057a22014dbf349adfc160ffa740dba7af0dbd42d642661b2cc7f`
  that matches the sha-checksum in the Readme-area for this download here in this Repo

## Suggestion to fix this
- Offer a zip archiv as download option for git portable too

**Comment by rimrul** [comment]
>Microsoft Windows XP [Version 5.1.2600]

No. Absolutely no.

>As of Git for Windows v2.10.1, Windows Vista or later are required.

Just to remind you, we're nearing the fourth aniversary of that release. Git for Windows 2.10.1 was released on October 4th 2016.

Newer windows versions don't seem to complain about this file being invalid.

>ist keine zulässige Win32-Anwendung (in english this means ... is Not a Valid Win32 Application

Slight misstranslation here (not sure if it's yours or microsofts) "zulässig" tends to mean "permitted" rather than "valid"

If you still want to unpack it on XP (and then move the resulting Portable Git to some other machine, because it won't run on XP), you might be able to do so using 7-zip.

**Comment by mfriedrich74** [comment]
His translation "Not a Valid Win32 Application" is correct.

**Comment by Radon8472** [comment]
> > ist keine zulässige Win32-Anwendung (in english this means ... is Not a Valid Win32 Application
> 
> Slight misstranslation here (not sure if it's yours or microsofts) "zulässig" tends to mean "permitted" rather than "valid"
> 
I am using a german windows, so I am not 100% sure what the exact translation of this error would be in an english windows.
But
1. I found this error-message string view google, so I thing that is the microsoft translation for this error
2. in this context "valid" is a well matching synonym for "zulässig"

But I agree the best translation for `valid` would be 'gültig' in my language.

**Comment by rimrul** [comment]
Either way, let's not get stuck on the translation.

I've verified that XP Professional SP3 does indeed throw said error message, but Windows 7 32 bit does not. I don't have a convenient Windows 10 32bit at my disposal atm, but will check with Vista.

**Comment by rimrul** [comment]
Windows 10 and Windows Vista don't complain either.

**Comment by mfriedrich74** [comment]
The PE header could be incompatible. E.g. the subsystem version. If it is
6.0 it does not run on XP anymore. See msdn, wiki or maybe
https://stackoverflow.com/questions/16455855/exe-is-not-a-valid-win32-application-on-windows-xp/16460035#16460035

**Comment by dscho** [comment]
Windows XP is not supported by Git for Windows. See https://gitforwindows.org/requirements.html

**Comment by dscho** [comment]
> Offer a zip archiv as download option for git portable too

The idea of the Portable Git being a self-extracting 7-Zip archive is that you _can_ unpack it with 7-Zip, without using the self-extracting part.

You will still not have much joy with Git for Windows on XP, though, as there are so many instances of Git Bash _and_ `git.exe` using Win32 API functions that are simply not supported by Windows XP.
