### ISSUE TITLE
Git tag error despite using hint

### ISSUE THREAD

**Issue by WildCard65** [git-for-windows/git#2785]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19041.423]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

[Windows OpenSSH preview V8.1.0.0p1](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell 7

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git tag -f 2.1.1 v2.1.1^{}
```
Note: This was provided by GIT itself as a hint
```
hint: You have created a nested tag. The object referred to by your new tag is
hint: already a tag. If you meant to tag the object that it points to, use:
hint:
hint:   git tag -f 2.1.1 v2.1.1^{}
hint: Disable this message with "git config advice.nestedTag false"
```

 - What did you expect to occur after running these commands?

[Expected results](https://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag/16251698)

 - What actually happened instead?

```error: switch `n' expects a numerical value```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Unknown ATM.

**Comment by PhilipOakley** [comment]
That error message appears to be from `static int context_callback` in grep.c 
Not sure why that's happening. 

Does the tag already exist, or are your arguments in the reverse order? Ultimately, what were you trying to do?

**Comment by WildCard65** [comment]
Tag 'v2.1.1' exists while '2.1.1' is the new name.

The command was provided by GIT itself, so if its the wrong order, blame GIT.

The expected results link answers your last one.

**Comment by dscho** [comment]
Try quoting `v2.1.1^{}`, like so:

`git tag -f 2.1.1 "v2.1.1^{}"`

**Comment by WildCard65** [comment]
@dscho You're suggestion is correct, on the flip side, I needed to surround BOTH tag values in quotes:
```git tag -f "2.1.1" "v2.1.1^{}"```

**Comment by dscho** [comment]
Okay. In my tests, it was not necessary to quote the "2.1.1", but maybe I hold this thing wrong.

In any case, I think this is to be expected. Git cannot possibly guess that you're in a PowerShell instead of a POSIX shell (such as Bash), therefore it cannot really make sure that the command-line you are presented with uses PowerShell quoting rules.

So unless anybody here has any splendid ideas, I think we will need to close this ticket without having a better solution.

**Comment by WildCard65** [comment]
How about a warning stating the hint is geared for a POSIX shell and that changes like quoting would be required.

**Comment by PhilipOakley** [comment]
Possibly c/should be part of our FAQ's (user editable) or the Known issues of the Release notes (PR against the BuildExtra repo that holds that bit.
