### ISSUE TITLE
Problem with git version 2.28.0.windows.1 : Experiencing 'the remote end hung up unexpectedly' for most clone operations.

### ISSUE THREAD

**Issue by georgealverson** [git-for-windows/git#2787]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing::
the remote end hung up unexpectedly

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.19041.450]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

** insert your machine's response here **
```
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 git clone --recursive ssh://git@gitlab.cern.ch:7999/path-to-repo
 - What did you expect to occur after running these commands?

** insert here **
Have a successfully cloned local repo
 - What actually happened instead?

** insert here **
...
19:07:59.169089 git.c:444               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 13616 on HOSTNAME' --check-self-contained-and-connected
remote: Total 1082 (delta 6), reused 0 (delta 0), pack-reused 1066
fatal: the remote end hung up unexpectedlyMiB | 4.66 MiB/s
fatal: early EOF
fatal: index-pack failed
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **
Sorry, this is a private GitLab repo

This worked fine with Git-2.26.2 (can't use 2.27 due to the bad svn module). Reverting to it gives working installation.

Tried increasing all the possible parameters, ssh.postBUffer, pack.windowMemory,  core.compression, etc., without  success.

More complete trace:
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (16/16), done.
19:07:59.110088 run-command.c:663       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 13616 on HOSTNAME' --check-self-contained-and-connected
19:07:59.164088 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
19:07:59.169089 git.c:444               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 13616 on HOSTNAME' --check-self-contained-and-connected
remote: Total 1082 (delta 6), reused 0 (delta 0), pack-reused 1066
fatal: the remote end hung up unexpectedlyMiB | 4.66 MiB/s
fatal: early EOF
fatal: index-pack failed

**Comment by dscho** [comment]
This sounds like it could be potentially a cURL problem.

Since this has nothing to do with Subversion, you could try bisecting the [snapshots](https://wingit.blob.core.windows.net/files/index.html) (https://github.com/git-for-windows/git/commit/4267c88d0d8936ae723bba55e0576b1c4f3d4e1a corresponds to v2.26.2). For bisecting, I recommend using the portable Git edition.

Or you could drop in the `libcurl-4.dll` from a working portable Git's `mingw64\bin` folder into a non-working portable Git (it _might_ be present also in `mingw64\libexec\git-core`) to see if that fixes it.

**Comment by georgealverson** [comment]
Dear Johannes,

Thank you very much for this tip. I’ll give it a try and report back to the list.

Best regards,
George Alverson

**Comment by georgealverson** [comment]
Hi,

Thanks for your help, the portable installation makes things so much easier.

I tried replacing the curl libraries using 2.26.2, and that didn't help.
[
PortableGit_2_27_0_rc0> cp ..\PortableGit_2_26_2\mingw64\bin\libcurl-4.dll .\mingw64\bin\
PortableGit_2_27_0_rc0> cp ..\PortableGit_2_26_2\mingw64\libexec\git-core\libcurl-4.dll .\mingw64\libexec\git-core\
PortableGit_2_27_0_rc0> cp ..\PortableGit_2_26_2\usr\bin\msys-curl-4.dll .\usr\bin\
]

I then started stepping through the snapshots.

The last one that works for me is Fri, 29 May 2020 15:21:30 +0200
(commit 2dbd94394b53865fbebc2125f8ac4dd5f8ac088c).

The very next one, Mon, 1 Jun 2020 20:17:08 +0200
(commit 907ab1011dce9112700498e034b974ba60f8b407), fails. This is the 2.27.0 release, I think.

Is there a next step?

Best regards,
George

**Comment by dscho** [comment]
> Is there a next step?

I only see this red flag in the release notes between v2.26.2 and v2.27.0 that _might_ help you resolve the issue:

> * The transport protocol version 2, which was promoted to the default in Git 2.26 release, turned out to have some remaining rough edges, so it has been demoted from the default.

**Comment by georgealverson** [comment]
Hi,

I tried v2.25.1, hoping that version might predate the switch to transport protocol 2. It dies.

$ git --version
git version 2.25.1.windows.1

Here is the output with GIT_TRACE and GIT_CURL_VERBOSE set to 1:

$ git clone --recursive ssh://git@gitlab.cern.ch:7999/tdr/papers/TOP-18-013
08:31:08.537272 exec-cmd.c:237          trace: resolved executable dir: H:/GitTest/PortableGit_2_25_1/mingw64/bin
08:31:08.538272 git.c:439               trace: built-in: git clone --recursive ssh://git@gitlab.cern.ch:7999/tdr/papers/TOP-18-013
Cloning into 'TOP-18-013'...
08:31:08.585272 run-command.c:663       trace: run_command: unset GIT_DIR; ''\''C:\Windows\System32\OpenSSH\ssh.exe'\''' -p 7999 git@gitlab.cern.ch 'git-upload-pack '\''/tdr/papers/TOP-18-013'\'''
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
remote: Enumerating objects: 557, done.
08:31:10.804440 run-command.c:663       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 26492 on Rover7' --check-self-contained-and-connected
remote: Counting objects: 100% (557/557), done.
08:31:10.855135 exec-cmd.c:237          trace: resolved executable dir: H:/GitTest/PortableGit_2_25_1/mingw64/libexec/git-core
08:31:10.858170 git.c:439               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 26492 on Rover7' --check-self-contained-and-connected
remote: Compressing objects: 100% (118/118), done.
fatal: the remote end hung up unexpectedlyMiB | 4.71 MiB/s
fatal: early EOF
fatal: index-pack failed

I tried it more that once, though, and in one instance it actually managed to do the first level before attempting to fetch the submodules.

Best,
George

**Comment by dscho** [comment]
> C:\Windows\System32\OpenSSH\ssh.exe

Ooooh. That's some new information that was _distinctly_ missing from this part of the original report:

>     * Any other interesting things about your environment that might be related
>       to the issue you're seeing?
> 
> 
> ** insert your response here **

That sounds very familiar, as it seems to be at least related, maybe even identical, to https://github.com/PowerShell/Win32-OpenSSH/issues/1322.

**Comment by georgealverson** [comment]
Hi,

It is the standard for me  :)

I turned on ssh debugging, as at the end of the SSH thread. It seems to have just gotten the end of data, but I don't really have a good idea of what it is doing at this level (eow=? end of window?).

Best,
George

Receiving objects:  54% (809/1497), 2.8debug2: channel 0: window 1989951 sent adjust 81920
debug2: channel 0: window 1989951 sent adjust 74433 MiB/s
debug2: channel 0: window 1992497 sent adjust 32768
debug2: channel 0: window 1966080 sent adjust 102400
debug2: channel 0: window 1986560 sent adjust 102400MiB/s
debug2: channel 0: window 1990656 sent adjust 106496MiB/s
...
debug2: channel 0: window 1982464 sent adjust 81920
debug2: channel 0: window 1982464 sent adjust 655364 MiB/s
debug2: channel 0: window 1982464 sent adjust 983044 MiB/s
debug3: receive packet: type 98497), 4.72 MiB | 1.54 MiB/s
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug2: channel 0: rcvd eow
debug2: channel 0: close_read
debug2: channel 0: input open -> closed
remote: Total 1497 (delta 469), reused 522 (delta 439), pack-reused 940
debug3: receive packet: type 96
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug3: channel 0: will not send data after close
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

debug3: send packet: type 1
debug3: fd 0 is not O_NONBLOCK
debug3: fd 1 is not O_NONBLOCK
debug3: fd 2 is not O_NONBLOCK
Transferred: sent 5344, received 6132256 bytes, in 4.4 seconds
Bytes per second: sent 1224.3, received 1404861.3
debug1: Exit status 0
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by dscho** [comment]
@georgealverson have you even looked at https://github.com/PowerShell/Win32-OpenSSH/issues/1322? The common resolution is to switch to Git for Windows' internal SSH.

**Comment by georgealverson** [comment]
Apologies for replying to the wrong ticket.

Hi,
Yes, of course. That's where I got the '-vvv' to try.
If I unset my normal ssh config, I will have to migrate the pertinent keys (and figure how to set up key-agent again, maybe), so that will not be today.
Best,
G.
$ git clone --recursive ssh://git@gitlab.cern.ch:7999/tdr/papers/TOP-18-013
16:12:19.936320 exec-cmd.c:237 trace: resolved executable dir: H:/GitTest/PortableGit_2_28_0_pristine/mingw64/bin
16:12:19.937319 git.c:444 trace: built-in: git clone --recursive ssh://git@gitlab.cern.ch:7999/tdr/papers/TOP-18-013
Cloning into 'TOP-18-013'...
16:12:19.985287 run-command.c:663 trace: run_command: unset GIT_DIR; ssh -p 7999 git@gitlab.cern.ch 'git-upload-pack '''/tdr/papers/TOP-18-013''''
git@gitlab.cern.ch: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by dscho** [comment]
> [git@gitlab.cern.ch](mailto:git@gitlab.cern.ch): Permission denied (publickey).
> fatal: Could not read from remote repository.

That looks like a very different problem than the original one.

**Comment by dscho** [comment]
Also, have you tried to use Git for Windows' own copy of OpenSSH instead of the PowerShell one?

**Comment by georgealverson** [comment]
The internal version of ssh does appear to work, at the cost of having to reconfigure ssh-agent. I would prefer to use the system ssh, but I guess this will do if necessary.

Best,
George

PS: Let me know if there is any information I can supply on attacking this problem.

$ git clone --recursive ssh://git@gitlab.cern.ch:7999/tdr/papers/TOP-18-013
Cloning into 'TOP-18-013'...
OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
debug1: Reading configuration data /c/Users/galve/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "gitlab.cern.ch" port 7999
debug2: ssh_connect_direct
...
debug1: Local version string SSH-2.0-OpenSSH_8.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.10
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.10 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
...
debug3: send packet: type 1
debug3: fd 0 is not O_NONBLOCK96), 4.00 MiB | 4.00 MiB/s
debug3: fd 1 is not O_NONBLOCK
debug3: fd 2 is not O_NONBLOCK
Transferred: sent 4680, received 8265836 bytes, in 2.4 seconds
Bytes per second: sent 1968.2, received 3476293.2
debug1: Exit status 0
Receiving objects: 100% (596/596), 7.86 MiB | 5.79 MiB/s, done.
Resolving deltas: 100% (305/305), done.
Submodule path 'utils': checked out 'c92ac966afadf0fb3f15ffe8d5750d332df73ffb'

**Comment by dscho** [comment]
> The internal version of ssh does appear to work, at the cost of having to reconfigure ssh-agent

Good.

> I would prefer to use the system ssh

Then you might want to try to raise more attention to https://github.com/PowerShell/Win32-OpenSSH/issues/1322.

In any case, it appears to me that we now pinpointed the problem to a bug in a component we do not control, therefore I will close this ticket.

**Comment by georgealverson** [comment]
Sounds good. Thanks for your help.
