### ISSUE TITLE
error with $HOSTFILE command

### ISSUE THREAD

**Issue by david-shiko** [git-for-windows/git#2789]
I'm not sure that is the right place for this bug, but anyway, I just tried to execute $HOSTFILE command, nothing more, and this is what the happened

1. I,m falling to vim (filename: text.txt)
![image](https://user-images.githubusercontent.com/27439358/90309118-04109600-deee-11ea-885b-3756453892f1.png)

2. After exiting from git I'm falling to git sample (and after that returning again to vim), so I leaved out vim with 'ctrl z' after all

3. The nextsteps I will describe with just screenshots 
![image](https://user-images.githubusercontent.com/27439358/90309209-1939f480-deef-11ea-910b-7a4c7dcb3831.png)
![image](https://user-images.githubusercontent.com/27439358/90309211-2951d400-deef-11ea-8d81-49254ee9308e.png)

**Comment by dscho** [comment]
Oh, so you mean `$HISTFILE`? That is an environment variable (described [here](https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html)), _not_ a command. You can inspect it via `echo $HISTFILE` and `less $HISTFILE` and it is not really meant for direct consumption by the end-user, but rather via the `history` Bash builtin.

**Comment by david-shiko** [comment]
> Oh, so you mean `$HISTFILE`? That is an environment variable (described [here](https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html)), _not_ a command. You can inspect it via `echo $HISTFILE` and `less $HISTFILE` and it is not really meant for direct consumption by the end-user, but rather via the `history` Bash builtin.

I get you, but it is leading for unexpected behavior, so it should to be just ignored (like undefined variable) or implemented (at least echo "this veriable is not implemented yet" )

**Comment by dscho** [comment]
Umm. `$HISTFILE` _cannot_ be a command. Whenever you call `$<variable>`, that variable is expanded and the result is then executed as shell commands.

What you experienced is intended, well-documented behavior.

**Comment by david-shiko** [comment]
Thanks!
