### ISSUE TITLE
Error installing Git for Windows 2.28.0

### ISSUE THREAD

**Issue by dscottie** [git-for-windows/git#2791]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit 2.28.0

```
$ git --version --build-options

N/A - could not install
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.418]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Could not install - none of these files exists
Default options except selected Notepad++ as comment editor
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

New machine, no previously installed copy of git

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

N/A

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Attempted to install by running Git-2.28.0-64-bit.exe
```
 - What did you expect to occur after running these commands?

Successful install

 - What actually happened instead?

After installer unpacks files and is almost complete, the following dialog appears:
![image](https://user-images.githubusercontent.com/16665988/90399328-b08b7d00-e092-11ea-9950-e03d0cbb3de9.png)

Git for Windows appears in the Add/Remove Programs, and cannot be removed.
Git Bash does not start (`Item referred to by this shortcut cannot be accessed` - in both regular and admin mode - doesn't appear to have been installed)
Git doesn't start from command prompt and not added to PATH

Note: 32-bit installer for 2.28.0 works successfully (however, I can confirm this is on a 64-bit processor running 64-bit Windows!)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Hmm. The path `C:\WINDOWS\system32\config\systemprofile\AppData\Local\Programs\Git\dev\fd` looks like some very funny "user profile" of a system user. Did you run the installer impersonated as some kind of administrator?

**Comment by dscottie** [comment]
I tried initially not as Administrator, then tried Run As Administrator for subsequent attempts

**Comment by dscho** [comment]
Have you tried Run As Administrator on the uninstaller (which is installed in the same directory as `git-bash.exe` as `unins001.exe`)?

**Comment by Neutrino-Sunset** [comment]
I'm having problems with the 2.28 installer too. One of the problems I've had that's possibly path related and so perhaps related to this is that if I select to add the Unix tools to the system path that never happens, even after a system reboot. This on Win 10 Home.

My main issue wihich is probably unrelated to this is that no matter what SSL option I choose (OpenSSL or Windows credential store) I cannot connect to my repo on visualstudio.com

**Comment by dscho** [comment]
Closing as stale.
