### ISSUE TITLE
Incorrect cyrillic filenames encoding 2.28.0

### ISSUE THREAD

**Issue by yaugenka** [git-for-windows/git#2792]
Git-2.28.0-64-bit on Windows 10.
In git bash with `core.quotepath` being unset cyrillic filenames are displayed like this

`\320\224\320\276\320\272\321\203\320\274\320\265\320\275\321\202.txt`

this above is correct, but with `core.quotepath=false` the filesnames are still unreadable

`╨Ф╨╛╨║╤Г╨╝╨╡╨╜╤В.txt`

Setting Locale to `ru_RU` and Character set to `UTF-8` (or KOI8-R, CP1251, CP866) in git bash options does not help.

At the same time the `ls` command prints the filename correctly:

```
$ ls
Документ.txt
```

The old version Git-2.21.0-64-bit works as expected.

**Comment by dscho** [comment]
Seems that there is a work-around: `cmd //c chcp 65001`, but I think we have a good grasp on https://github.com/msys2/MSYS2-packages/issues/1974 and once that is resolved, this here bug will be fixed, too.

**Comment by dscho** [comment]
Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by yaugenka** [comment]
Looks fixed in Git-prerelease-2.28.0.windows.1-51-g87c86a26de-20200923135803-64-bit
