### ISSUE TITLE
Can not pull push fetch.....in LAN but can work in mobile network。

### ISSUE THREAD

**Issue by FalconWu2017** [git-for-windows/git#2794]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit.

```
$ git --version --build-options

git version 2.25.0. windows.1
cpu: x86 64
s izeof- long: 4
sizeof-size_ t: 8
built from commit: 7c71c859c97853ed057 da5cbab12f3c13b55 54df

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windows 10  64bit
```
$ cmd.exe /c ver
Microsoft Windows [版本10.0.18362. 1016]
```

I don't know why I can't push commits on the LAN.When I push the information it will show me the following information  
![image](https://user-images.githubusercontent.com/34147999/91016113-d67ac980-e61e-11ea-84b5-8430ffd0310b.png)   
I'm sure the user credentials are correct and pull,fetch are same.    
If I switch to the mobile network, everything will be OK.   
Our network administrators don't know why.  

Can someone help me find out why???

**Comment by dscho** [comment]
[403](https://en.wikipedia.org/wiki/HTTP_403) seems to indicate "Forbidden". Can you access that URL in the LAN via browser?

**Comment by FalconWu2017** [comment]
Yes,I can.I can access the URL by gitea(it is same with gitlab) and I can access this URL in other networks such as my home, only this LAN can't, other places can

**Comment by dscho** [comment]
@FalconWu2017 is it possible that there is a proxy that is auto-configured by Windows? That would work for the browser, but not for Git, and would result in that symptom that you see. To find out, you could run `proxy-lookup <fetch-url>` in your Git Bash.

**Comment by FalconWu2017** [comment]
There was no any result.   

![image](https://user-images.githubusercontent.com/34147999/91157312-ba972680-e6f7-11ea-9632-a5473311d85d.png)

**Comment by dscho** [comment]
You _might_ find out more by setting `GIT_TRACE_CURL=1` and re-running both wired and wireless connections.
