### ISSUE TITLE
How to find more information on CRLF Option: CRLFAlways

### ISSUE THREAD

**Issue by cagross** [git-for-windows/git#2795]
- [ X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.27.0 64 bit

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win 10
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.900]
(c) 2019 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
I can't remember :-/
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

cat /etc/install-options.txt
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

N/A

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
If I open the file C:\Program Files\Git\etc\install-options.txt I believe it lists the Git Bash settings. One of them is: `CRLF Option: CRLFAlways` What exactly does this indicate, and what are the allowed values? Can these settings be overridden anywhere, or is this the only place they can be set?  I cannot find any information on it with a Google search.


```
 - What did you expect to occur after running these commands?

N/A

 - What actually happened instead?

N/A

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by rimrul** [comment]
> If I open the file C:\Program Files\Git\etc\install-options.txt I believe it lists the Git Bash settings.

Not quite. It's the file we use to store your previous choices in the setup so we have them around when you upgrade (or reinstall).  The values in `/etc/install-options.txt` don't have an effect on a running GIt for Windows installation. They just influence the installer when it is next launched.

The `CRLF Option` in particular controls the "How should Git treat line endings in text files?" radio buttons and corresponds to the value of `core.autocrlf` in your system wide config. 

| CRLF Option | core.autocrlf |  How should Git treat line endings in text files? |
|---|---|---|
| CRLFAlways  |  true |  Checkout Windows-style, commit Unix-style line endings |
|  CRLFCommitAsIs |  false |  Checkout as-is, commit as-is |
|  LFOnly | input  | Checkout as-is, commit Unix-style line endings  |

**Comment by rimrul** [comment]
See also [`git config`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf).

**Comment by cagross** [comment]
OK thanks for that.  But I'm a little confused. 

> It's the file we use to store your previous choices in the setup so we have them around when you upgrade (or reinstall). The values in /etc/install-options.txt don't have an effect on a running GIt for Windows installation. They just influence the installer when it is next launched.

OK I understand all that.

> The CRLF Option in particular controls the "How should Git treat line endings in text files?" radio buttons and corresponds to the value of core.autocrlf in your system wide config.

From this it sounds like, if I change `core.autocrlf` in my system config, that the value of `CRLF Option` in `install-options.txt` will also change.  Is that correct, or not?  I think the latter but just want to confirm.  I say that because currently, the value of `CRLF Option` in `install-options.txt` is `CRLFAlways`, yet the value of `core.autocrlf` in my system config is `false`.

**Comment by rimrul** [comment]
No, changing the system config does not change the install options.

The system config has an immediate effect on git,  but the installer will usually present you with presets based on the install options file on the next run.

There are some config options though, where we prefer the value in the system config nowadays, because they might have been changed intentionally.

**Comment by cagross** [comment]
OK understood on all.  Thanks for the explanation.  We can consider this resolved :-)

**Comment by tboegi** [comment]
As a side-note:
Did you consider to use a 
.gitattributes 
file ? That allows to have a repo-wide configuration, that travels with `git push` and `git pull`
and makes sure that all work stations use the same handling for CRLF.

**Comment by cagross** [comment]
@tboegi Sorry for the late reply.  But thanks, I"ll look into that.
