### ISSUE TITLE
Git can't load submodules via SSH (TortoiseGitPlink)

### ISSUE THREAD

**Issue by remittor** [git-for-windows/git#2798]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

v2.28.0 x64
```
$ git --version --build-options
git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Win7 x64
```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Path Option: BashOnly
Plink Path: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SSH Option: Plink
Tortoise Option: true
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

GitBash and TortoiseGit

 - What commands did you run to trigger this issue?

```
git clone --recurse-submodules git@github.com:remittor/paxz.wcx.git
```

 - What actually happened instead?

```
Cloning into 'paxz.wcx'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 422 (delta 49), reused 70 (delta 34), pack-reused 325
Receiving objects: 100% (422/422), 274.61 KiB | 844.00 KiB/s, done.
Resolving deltas: 100% (233/233), done.
Submodule 'extlibs/lz4' (https://github.com/lz4/lz4.git) registered for path 'extlibs/lz4'
Submodule 'extlibs/zstd' (https://github.com/facebook/zstd.git) registered for path 'extlibs/zstd'
Cloning into 'D:/dev/github/test/paxz.wcx/extlibs/lz4'...
fatal: unable to access 'https://github.com/lz4/lz4.git/': Could not resolve host: github.com
fatal: clone of 'https://github.com/lz4/lz4.git' into submodule path 'D:/dev/github/test/paxz.wcx/extlibs/lz4' failed
Failed to clone 'extlibs/lz4'. Retry scheduled
Cloning into 'D:/dev/github/test/paxz.wcx/extlibs/zstd'...
fatal: unable to access 'https://github.com/facebook/zstd.git/': Could not resolve host: github.com
fatal: clone of 'https://github.com/facebook/zstd.git' into submodule path 'D:/dev/github/test/paxz.wcx/extlibs/zstd' failed
Failed to clone 'extlibs/zstd'. Retry scheduled
Cloning into 'D:/dev/github/test/paxz.wcx/extlibs/lz4'...
fatal: unable to access 'https://github.com/lz4/lz4.git/': Could not resolve host: github.com
fatal: clone of 'https://github.com/lz4/lz4.git' into submodule path 'D:/dev/github/test/paxz.wcx/extlibs/lz4' failed
Failed to clone 'extlibs/lz4' a second time, aborting
```

 - If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing?

git@github.com:remittor/paxz.wcx.git

**Comment by remittor** [comment]
Git trying to download submodules via git-remote-https.exe

**Comment by dscho** [comment]
But the submodules' URLs are recorded _with_ the HTTPS protocol! See here: https://github.com/remittor/paxz.wcx/blob/HEAD/.gitmodules

If you insist on using SSH instead, you will have to use the [`url.<base>.insteadOf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) trick to override that.

**Comment by remittor** [comment]
> But the submodules' URLs are recorded _with_ the HTTPS protocol!
Ohh. Thanks!

Is it possible to get the `git-remote-https.exe` to work through socks5 proxy?

**Comment by dscho** [comment]
> Is it possible to get the `git-remote-https.exe` to work through socks5 proxy?

Since `git-remote-https.exe` uses cURL for communication, that's more of a cURL question. According to https://blog.emacsos.com/use-socks5-proxy-in-curl.html, it should be possible.
