### ISSUE TITLE
SkipDowngrade flag for Git on Windows does not exit

### ISSUE THREAD

**Issue by solankisamir** [git-for-windows/git#2801]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: i686
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** NONE**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**CMD**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**%~dp0\Git-2.19.2-32-bit.exe /VERYSILENT /LOG="gitinstall_%RANDOM%.log" /LOADINF="%~dp0\gitconfig.ini" /DIR="%ProgramFiles(x86)%\Git" /SKIPDOWNGRADE=1**
```
 - What did you expect to occur after running these commands?

```
 I was running a cmd on a machine that had a higher version of GIT installed with the **SKIPDOWNGRADE** flag. 
The GIT cmdline never exits and blocks the process.
 As you can see from below log, that **Log closed** never occurs
```

 - What actually happened instead?

**Here is the log file data**
```
 2020-08-30 07:49:24.859   Log opened. (Time zone: UTC+00:00)
    2020-08-30 07:49:24.859   Log opened. (Time zone: UTC+00:00)
   2020-08-30 07:49:24.859   Setup version: Inno Setup version 5.6.1 (u)
2020-08-30 07:49:24.859   Original Setup EXE: C:\Bootstrapper\0.13.1048.0\Git\Git-2.19.2-32-bit.exe
2020-08-30 07:49:24.859   Setup command line: /SL5="$600FC,43327813,224256,C:\Bootstrapper\0.13.1048.0\Git\Git-2.19.2-32-bit.exe" /VERYSILENT /LOG="gitinstall_29737.log" /LOADINF="C:\Bootstrapper\0.13.1048.0\Git\\gitconfig.ini" /DIR="D:\Program Files (x86)\Git" /SKIPDOWNGRADE=1
2020-08-30 07:49:24.859   Windows version: 10.0.14393  (NT platform: Yes)
2020-08-30 07:49:24.859   64-bit Windows: Yes
2020-08-30 07:49:24.859   Processor architecture: x64
2020-08-30 07:49:24.859   User privileges: Administrative
2020-08-30 07:49:25.119   64-bit install mode: No
2020-08-30 07:49:25.119   Created temporary directory: C:\Resources\temp\e3db6fc6a39a463ead31cb5d9e001f0a.Proxy.Host.WebRole\RoleTemp\is-VKFTE.tmp

2020-08-30 07:49:25.150   Successfully imported the DLL function. Delay loaded? No
2020-08-30 07:49:25.150   Message box (OK):
                          Skipping downgrade from 2.27.0 to 2.19.2
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**NA**

**Comment by rimrul** [comment]
Where did you get this `/SKIPDOWNGRADE` flag from? I don't think there is such a flag.

**Comment by solankisamir** [comment]
@rimrul [here](https://github.com/git-for-windows/build-extra/commit/c7bc72a157960ee9eef644141f116060c6c31c14)

**Comment by rimrul** [comment]
Oh. I've missed that. It does log the 'Skipping downgrade from X to Y' message, so it should have reached `ExitEarlyWithSuccess()`. Looks like it got stuck trying to delete the temp files. Not sure what to do about that.

**Comment by dscho** [comment]
I could imagine that you need both `/SILENT` and `/VERYSILENT` flags.

Oh, and you almost certainly want to use the `/NORESTART` flag, too.

**Comment by solankisamir** [comment]
No did not help. The log file still got stuck at exactly the same point. 
We unblocked ourselves by checking installed version in the registry and skipping installation if it is a downgrade.

**Comment by dscho** [comment]
>  We unblocked ourselves by checking installed version in the registry and skipping installation if it is a downgrade.

Great! I will close this ticket, then.
