### ISSUE TITLE
Git 2.28.0: The content of diff containing CJK strings cannot be displayed correctly in conhost

### ISSUE THREAD

**Issue by fcharlie** [git-for-windows/git#2802]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19042.450]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git diff
```
 - What did you expect to occur after running these commands?

The CJK string is displayed correctly as in Mintty.

![image](https://user-images.githubusercontent.com/6904176/92221534-38191e80-eed0-11ea-88b9-9b28341f839b.png)

 - What actually happened instead?

Windows Terminal snapshot:

![image](https://user-images.githubusercontent.com/6904176/92220521-bd9bcf00-eece-11ea-95ab-396ee3c7b8a6.png)

Git CMD snapshot:

![image](https://user-images.githubusercontent.com/6904176/92220897-37cc5380-eecf-11ea-9116-75c39e77dda0.png)

**Comment by dscho** [comment]
This probably has the same underlying root cause as msys2/MSYS2-packages#1974. Could you call `cmd /c chcp 65001` and try again?

**Comment by dscho** [comment]
Oh, Windows Terminal... What is the value of `LANG`? And of `LC_ALL` and `LC_CTYPE`?

**Comment by fcharlie** [comment]
> Oh, Windows Terminal... What is the value of ? And of and ?`LANG``LC_ALL``LC_CTYPE`

Windows Terminal(Powershell) not set `LANG` `LC_ALL` and `LC_CTYPE`

**Comment by dscho** [comment]
> Path Option: BashOnly

This suggests that `git` should not even be found when you try to call it in PowerShell. However, it is obviously found. Which makes me wonder, _where_ it is found. In Bash, of course, `LANG` is configured in `/etc/profile.d/lang.sh`, which is why it works there.

I vividly remember that we tried, once upon a time, to configure `LC_CTYPE=C.UTF-8` as a fall-back and that really messed up some use cases, which is why we now fall back to `LC_CTYPE=C`: https://github.com/git-for-windows/git/blob/77982caf269b7ee713a76da2bcf260c34d3bf7a7/compat/mingw.c#L3372-L3373

Not sure whether there is anything we can do to help this situation better, not if we want to avoid similar breakages...

**Comment by dscho** [comment]
Just to make sure, could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by fcharlie** [comment]
@dscho Thanks. It seems that git diff is working properly.

![image](https://user-images.githubusercontent.com/6904176/94135698-68802700-fe96-11ea-9259-81cf06040e63.png)

**Comment by dscho** [comment]
Could you push that `cjk` repository somewhere, for easy testing?

**Comment by fcharlie** [comment]
> Could you push that `cjk` repository somewhere, for easy testing?

Open Windows Terminal  (PowerShell Core) ：

```powershell

git clone https://github.com/fcharlie/cjkdemo.git
cd cjkdemo
git diff f789f9f390c80ce6cc59b7770fe833554140d83f
```

**Comment by dscho** [comment]
Okay, I gave it a try and could verify that:

- `git -P diff f789f9` works, suggesting that the problem lies with the pager, and
- after setting `LC_ALL=C.UTF-8`, it works as expected.

**Comment by dscho** [comment]
@fcharlie I think I have half a fix here: https://github.com/git-for-windows/git/pull/2834

**Comment by dscho** [comment]
> I think I have half a fix here: #2834

@fcharlie I hope you have a good idea how to fix the other half because I sure don't.

**Comment by fcharlie** [comment]
@dscho I have a solution here. In git wapper, we always set LANG to **.UTF-8 according to the user's locale when LANG is not set.

**Comment by dscho** [comment]
> I have a solution here. In git wapper, we always set LANG to **.UTF-8 according to the user's locale when LANG is not set.

Unfortunately, I do not remember the details, and failed to dig up the context, but I vividly remember that we tried that and that it wreaked havoc.

We cannot just set `LANG=**.UTF-8` unless we know that the code page supports it.

Unfortunately, Windows Terminal does not set the code page to UTF-8, otherwise my fix would work without any additional work.

**Comment by fcharlie** [comment]
> > I have a solution here. In git wapper, we always set LANG to **.UTF-8 according to the user's locale when LANG is not set.
> 
> Unfortunately, I do not remember the details, and failed to dig up the context, but I vividly remember that we tried that and that it wreaked havoc.
> 
> We cannot just set unless we know that the code page supports it.`LANG=**.UTF-8`
> 
> Unfortunately, Windows Terminal does not set the code page to UTF-8, otherwise my fix would work without any additional work.

Maybe we should reimplement functions like fprintf in git in Windows to support git encoding completely as UTF-8, and then let all be processed in accordance with UTF-8, no longer consider the LANG setting. To be honest, I think that now to evaluate CodePage, this thing is completely dross.

File not tty: fprintf -- UTF-8 --> WriteFile 
File is console: fprintf -- UTF-8 to UTF-16 --> WriteConsoleW

```cpp
//
#include <cstdio>
#include <io.h>
#include <bela/strcat.hpp>
#include <bela/match.hpp>
#include <bela/str_split.hpp>
#include <bela/terminal.hpp>

namespace bela::terminal {
// Is console terminal
bool IsTerminal(HANDLE fd) {
  DWORD mode = 0;
  if (GetConsoleMode(fd, &mode) != TRUE) {
    return false;
  }
  return mode != 0;
}

bool TerminalEnabled(HANDLE fd) {
  DWORD dwMode = 0;
  if (GetConsoleMode(fd, &dwMode) != TRUE) {
    return false;
  }
  dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
  if (SetConsoleMode(fd, dwMode) != TRUE) {
    return false;
  }
  return true;
}

bool IsTerminal(FILE *fd) {
  auto FileHandle = reinterpret_cast<HANDLE>(_get_osfhandle(_fileno(fd)));
  return IsTerminal(FileHandle);
}

// Is cygwin terminal
bool IsCygwinTerminal(HANDLE fd) {
  if (GetFileType(fd) != FILE_TYPE_PIPE) {
    return false;
  }
  constexpr unsigned int pipemaxlen = 512;
  WCHAR buffer[pipemaxlen] = {0};
  if (GetFileInformationByHandleEx(fd, FileNameInfo, buffer, pipemaxlen * 2) != TRUE) {
    return false;
  }
  auto pb = reinterpret_cast<FILE_NAME_INFO *>(buffer);
  std::wstring_view pipename{pb->FileName, pb->FileNameLength / 2};
  std::vector<std::wstring_view> pvv = bela::StrSplit(pipename, bela::ByChar(L'-'), bela::SkipEmpty());
  if (pvv.size() < 5) {
    return false;
  }
  constexpr std::wstring_view cyglikeprefix[] = {L"\\msys", L"\\cygwin", L"\\Device\\NamedPipe\\msys",
                                                 L"\\Device\\NamedPipe\\cygwin"};
  constexpr std::wstring_view ptyprefix = L"pty";
  constexpr std::wstring_view pipeto = L"to";
  constexpr std::wstring_view pipefrom = L"from";
  constexpr std::wstring_view master = L"master";
  if (std::find(std::begin(cyglikeprefix), std::end(cyglikeprefix), pvv[0]) == std::end(cyglikeprefix)) {
    return false;
  }
  if (pvv[1].empty()) {
    return false;
  }
  if (!bela::StartsWith(pvv[2], ptyprefix)) {
    return false;
  }
  if (pvv[3] != pipeto && pvv[3] != pipefrom) {
    return false;
  }
  if (pvv[4] != master) {
    return false;
  }
  return true;
}
bool IsCygwinTerminal(FILE *fd) {
  auto FileHandle = reinterpret_cast<HANDLE>(_get_osfhandle(_fileno(fd)));
  return IsCygwinTerminal(FileHandle);
}
// Is same terminal maybe console or Cygwin pty
bool IsSameTerminal(HANDLE fd) { return IsTerminal(fd) || IsCygwinTerminal(fd); }
bool IsSameTerminal(FILE *fd) {
  auto FileHandle = reinterpret_cast<HANDLE>(_get_osfhandle(_fileno(fd)));
  return IsTerminal(FileHandle) || IsCygwinTerminal(FileHandle);
}

bool TerminalSize(HANDLE fd, terminal_size &sz) {
  CONSOLE_SCREEN_BUFFER_INFO bi;
  if (GetConsoleScreenBufferInfo(fd, &bi) != TRUE) {
    return false;
  }
  sz.columns = bi.dwSize.X;
  sz.rows = bi.dwSize.Y;
  return true;
}
bool TerminalSize(FILE *fd, terminal_size &sz) {
  auto FileHandle = reinterpret_cast<HANDLE>(_get_osfhandle(_fileno(fd)));
  return TerminalSize(FileHandle, sz);
}

// Write data to windows terminal (windows console)
bela::ssize_t WriteTerminal(HANDLE fd, std::wstring_view data) {
  DWORD dwWrite = 0;
  if (!WriteConsoleW(fd, data.data(), (DWORD)data.size(), &dwWrite, nullptr)) {
    return -1;
  }
  return static_cast<ssize_t>(dwWrite);
}
// Write data to same file not windows terminal
bela::ssize_t WriteSameFile(HANDLE fd, std::wstring_view data) {
  auto ndata = bela::ToNarrow(data);
  DWORD dwWrite = 0;
  if (!::WriteFile(fd, ndata.data(), (DWORD)ndata.size(), &dwWrite, nullptr)) {
    return -1;
  }
  return static_cast<ssize_t>(dwWrite);
}

enum class TerminalMode {
  File, //
  ConPTY,
  Cygwin
};

class Filter {
public:
  Filter(const Filter &) = delete;
  Filter &operator=(const Filter &) = delete;
  static Filter &Instance() {
    static Filter filter;
    return filter;
  }
  bela::ssize_t WriteAuto(FILE *fd, std::wstring_view data) {
    if (fd == stderr) {
      return WriteAutoInternal(fderr, errmode, data);
    }
    if (fd == stdout) {
      return WriteAutoInternal(fdout, outmode, data);
    }
    auto FileHandle = reinterpret_cast<HANDLE>(_get_osfhandle(_fileno(fd)));
    return WriteSameFile(FileHandle, data);
  }

private:
  Filter() {
    fdout = GetStdHandle(STD_OUTPUT_HANDLE);
    if (fdout != nullptr) {
      if (TerminalEnabled(fdout)) {
        outmode = TerminalMode::ConPTY;
      } else if (IsCygwinTerminal(fdout)) {
        outmode = TerminalMode::Cygwin;
      }
    }
    fderr = GetStdHandle(STD_ERROR_HANDLE);
    if (fderr != nullptr) {
      if (TerminalEnabled(fderr)) {
        errmode = TerminalMode::ConPTY;
      } else if (IsCygwinTerminal(fderr)) {
        errmode = TerminalMode::Cygwin;
      }
    }
  }
  bela::ssize_t WriteAutoInternal(HANDLE fd, TerminalMode mode, std::wstring_view data) {
    if (fd == nullptr) {
      return -1;
    }
    if (mode == TerminalMode::ConPTY) {
      return WriteTerminal(fd, data);
    }
    return WriteSameFile(fd, data);
  }
  HANDLE fdout{nullptr};
  HANDLE fderr{nullptr};
  TerminalMode outmode{TerminalMode::File};
  TerminalMode errmode{TerminalMode::File};
};

bela::ssize_t WriteAuto(FILE *fd, std::wstring_view data) { return Filter::Instance().WriteAuto(fd, data); }

bela::ssize_t WriteAutoFallback(FILE *fd, std::wstring_view data) {
  auto FileHandle = reinterpret_cast<HANDLE>(_get_osfhandle(_fileno(fd)));
  if (IsTerminal(FileHandle)) {
    return WriteTerminal(FileHandle, data);
  }
  return WriteSameFile(FileHandle, data);
}
} // namespace bela::terminal
```

**Comment by fcharlie** [comment]
Implementation of golang:

https://github.com/golang/go/blob/1f4d035178d2d792a74b6b872f6a213bf5fd9326/src/internal/poll/fd_windows.go#L650-L691

```go
// Write implements io.Writer.
func (fd *FD) Write(buf []byte) (int, error) {
	if err := fd.writeLock(); err != nil {
		return 0, err
	}
	defer fd.writeUnlock()
	if fd.isFile {
		fd.l.Lock()
		defer fd.l.Unlock()
	}

	ntotal := 0
	for len(buf) > 0 {
		b := buf
		if len(b) > maxRW {
			b = b[:maxRW]
		}
		var n int
		var err error
		if fd.isFile {
			switch fd.kind {
			case kindConsole:
				n, err = fd.writeConsole(b)
			default:
				n, err = syscall.Write(fd.Sysfd, b)
				if fd.kind == kindPipe && err == syscall.ERROR_OPERATION_ABORTED {
					// Close uses CancelIoEx to interrupt concurrent I/O for pipes.
					// If the fd is a pipe and the Write was interrupted by CancelIoEx,
					// we assume it is interrupted by Close.
					err = ErrFileClosing
				}
			}
			if err != nil {
				n = 0
			}
		} else {
			if race.Enabled {
				race.ReleaseMerge(unsafe.Pointer(&ioSync))
			}
			o := &fd.wop
			o.InitBuf(b)
			n, err = execIO(o, func(o *operation) error {
				return syscall.WSASend(o.fd.Sysfd, &o.buf, 1, &o.qty, 0, &o.o, nil)
			})
		}
		ntotal += n
		if err != nil {
			return ntotal, err
		}
		buf = buf[n:]
	}
	return ntotal, nil
}

// writeConsole writes len(b) bytes to the console File.
// It returns the number of bytes written and an error, if any.
func (fd *FD) writeConsole(b []byte) (int, error) {
	n := len(b)
	runes := make([]rune, 0, 256)
	if len(fd.lastbits) > 0 {
		b = append(fd.lastbits, b...)
		fd.lastbits = nil

	}
	for len(b) >= utf8.UTFMax || utf8.FullRune(b) {
		r, l := utf8.DecodeRune(b)
		runes = append(runes, r)
		b = b[l:]
	}
	if len(b) > 0 {
		fd.lastbits = make([]byte, len(b))
		copy(fd.lastbits, b)
	}
	// syscall.WriteConsole seems to fail, if given large buffer.
	// So limit the buffer to 16000 characters. This number was
	// discovered by experimenting with syscall.WriteConsole.
	const maxWrite = 16000
	for len(runes) > 0 {
		m := len(runes)
		if m > maxWrite {
			m = maxWrite
		}
		chunk := runes[:m]
		runes = runes[m:]
		uint16s := utf16.Encode(chunk)
		for len(uint16s) > 0 {
			var written uint32
			err := syscall.WriteConsole(fd.Sysfd, &uint16s[0], uint32(len(uint16s)), &written, nil)
			if err != nil {
				return 0, err
			}
			uint16s = uint16s[written:]
		}
	}
	return n, nil
}
```

**Comment by dscho** [comment]
We already write bytes to files as-are, without re-encoding. The winansi code you found targets the Win32 Console and _needs_ to re-encode (in particular ANSI control sequences).

That still does not answer the question how we could discern the case where Windows Terminal pretends not to handle Unicode but actually _does_ handle Unicode.

**Comment by fcharlie** [comment]
@dscho In fact, the internal behavior of git is not consistent. For example, git commit can be displayed correctly, but git log/git diff cannot

![image](https://user-images.githubusercontent.com/6904176/94534715-4d852c80-0273-11eb-909a-c497f30c27c4.png)

I use the [blobview](https://gist.github.com/fcharlie/2dde5a491d08dbc45c866cb370b9fa07) program written by golang to check the commit, but it is actually UTF-8

![image](https://user-images.githubusercontent.com/6904176/94535373-15321e00-0274-11eb-80c4-e5ae1d7e2434.png)

**Comment by dscho** [comment]
> git commit can be displayed correctly, but git log/git diff cannot

That's because `git commit` does not use the pager, but `git log`/`git diff` do. And that pager is `less.exe` provided by the MSYS2 project, which really needs to know the output encoding (because it does _not_ take `git.exe`'s shortcuts that may or may not be appropriate).

**Comment by fcharlie** [comment]
> > git commit can be displayed correctly, but git log/git diff cannot
> 
> That's because does not use the pager, but / do. And that pager is provided by the MSYS2 project, which really needs to know the output encoding (because it does _not_ take 's shortcuts that may or may not be appropriate).`git commit``git log``git diff``less.exe``git.exe`

So can we reimplement less?

**Comment by dscho** [comment]
> So can we reimplement less?

Oh my. If you want to. I'll not get into this, though...

**Comment by fcharlie** [comment]
> > So can we reimplement less?
> 
> Oh my. If you want to. I'll not get into this, though...

Or patch less?

**Comment by dscho** [comment]
> Or patch less?

Or patch the MSYS2 runtime.

But how? That is the big question.

Because you _can_ get `less.exe` to work correctly, by setting `LC_CTYPE` (or `LANG`) in a specific way. As my PR demonstrates, we can do that even in `git.exe`. But the biggest problem remains: how to discern the situations when it is appropriate (when the code page is UTF-8) vs when it is _not_ appropriate (IIRC there was a problem when the code page was set to something non-ASCII, non-UTF-8).

**Comment by dscho** [comment]
> IIRC there was a problem when the code page was set to something non-ASCII, non-UTF-8

I think I found the original report: https://groups.google.com/g/git-for-windows/c/9_abrdlqi48/m/S9pJE56ZDgAJ

However, I just re-tested with ConEmu and cannot replicate that behavior. Therefore, I will go ahead and just replace the `"C"` by `"C.UTF-8"` and hope that it does not break anyone's scenario.

**Comment by dscho** [comment]
@fcharlie I went ahead and updated https://github.com/git-for-windows/git/pull/2834. When you get a chance, please test this:

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd git`,
3. `git pull https://github.com/dscho/git/ lctype-should-adapt-to-console-code-page`
4. build Git via `make -j$(nproc)`
5. copy `git.exe` into a portable Git and test

**Comment by fcharlie** [comment]
> @fcharlie I went ahead and updated #2834. When you get a chance, please test this:
> 
> 1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
> 2. `sdk cd git`,
> 3. `git pull https://github.com/dscho/git/ lctype-should-adapt-to-console-code-page`
> 4. build Git via `make -j$(nproc)`
> 5. copy `git.exe` into a portable Git and test

Good I will try it out and give you feedback, thank you.

**Comment by fcharlie** [comment]
@dscho After testing, your patch is effective. Thanks.

![image](https://user-images.githubusercontent.com/6904176/94584147-d66e8900-02b0-11eb-8e0d-9312d3df70c5.png)

**Comment by dscho** [comment]
Very good!
