### ISSUE TITLE
Issue with formatting and weird characters in responses using UTF-8

### ISSUE THREAD

**Issue by gdemarcosSFDC** [git-for-windows/git#2806]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git for Windows 64-bit

```
$ git --version --build-options

** git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh **
```

 - Windows 10 64-bit

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.18363.1049] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue, you're seeing?

** N/A **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Git Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** sfdx force:org:list **
```
 - What did you expect to occur after running these commands?

** Well formatted output **

 - What actually happened instead?

** Got strange characters **

See image (red is Git Bash terminal, orange is VS code terminal)
![image](https://user-images.githubusercontent.com/8474333/92416623-03050a00-f124-11ea-9445-11bd3b6324b5.png)

**Comment by dscho** [comment]
It looks like the same issue as msys2/MSYS2-packages#1974. Could you try whether running `cmd /c chcp 65001` works around the issue?

**Comment by dscho** [comment]
@gdemarcosSFDC coud you?

**Comment by mittus** [comment]
> It looks like the same issue as [msys2/MSYS2-packages#1974](https://github.com/msys2/MSYS2-packages/issues/1974). Could you try whether running `cmd /c chcp 65001` works around the issue?

I had similar problem. After running command `cmd /c chcp 65001` nothing.
![image](https://user-images.githubusercontent.com/711179/92777064-8171de00-f3a8-11ea-8f7a-1b4287d7e244.png)

When I use git-cmd or cmd, I have correct encoding.
![image](https://user-images.githubusercontent.com/711179/92777418-dada0d00-f3a8-11ea-9ac4-8c87935cad97.png)

**Comment by mittus** [comment]
Needed command `cmd //c chcp 65001`, it's fix problem, but only for the current session :((

![image](https://user-images.githubusercontent.com/711179/92778271-aca8fd00-f3a9-11ea-9da1-1ad71515fc56.png)

**Comment by scrumvisualize** [comment]
I am facing the same problem. While running cypress test in headless mode in **git bash** weird characters are displaying (please refer the screenshot attached). 

note: There is no issue while running in Windows 10 command prompt.

**Cypress version : 5.1.0**

**Git Bash terminal:**  git version 2.28.0.windows.1

**System: Windows 10 Home 64 bit operating system**



![image](https://user-images.githubusercontent.com/5972626/92984825-99ed1000-f4f0-11ea-93f7-1ce121bf288e.png)

**Comment by gabrielbarr0s** [comment]
I am facing the same problem. Version 2.26 is the last one working.

![Screenshot 2020-09-15 165657](https://user-images.githubusercontent.com/13933767/93258314-7b974680-f774-11ea-8bc8-bb5bbcfd10fa.png)

**Comment by alexander-placidi** [comment]
I'm facing the same issue here. 
![2020-09-16 13_09_17-MagentaForce_SalesForce_SalesCloud - Visual Studio Code](https://user-images.githubusercontent.com/52330461/93330166-a9d16080-f81e-11ea-822d-333aa19e5b64.png)

System: Windows 10 Enterprise, 64 Bit
Git version 2.28

I noticed that Windows Power Shell shows the same weird characters. There is no issue in the standard Windows command prompt.

**Comment by dscho** [comment]
Yes, of course, the `chcp 65001` trick is only a workaround, we still need to figure out how to solve this problem on a more fundamental level. However, having your confirmation means that resolving msys2/MSYS2-packages#1974 will most likely resolve your problem, too, so we can focus on that ticket.

**Comment by dscho** [comment]
Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by mittus** [comment]
Now it's works correctly
![image](https://user-images.githubusercontent.com/711179/94153140-1682d580-fe85-11ea-9044-28d9597b9ccd.png)
