### ISSUE TITLE
git-bash reports "WARNING: terminal is not fully functional" and backspace does not delete

### ISSUE THREAD

**Issue by anb0s** [git-for-windows/git#281]
Versions: Git for Windows 2.5.0
Windows 7 x64
I've started it in bin folder with "bash --login -i" the just tried some git extensions and see the output:
"WARNING: terminal is not fully functional" from msys2 ? Second i cannot use backspace - it prints spaces (4 times) and then nothing more.

Cannot see the issues with 2.4.5.1

**Comment by dscho** [comment]
If you insist on calling the bash directly, it is your duty to set `TERM` and `MSYSTEM` appropriately...

The Git Bash would do all this automatically, so why not stick to it?

**Comment by dscho** [comment]
Ah, I think I understand... You started this *in cmd.exe*... That was some really important information that was missing. Happily, it was not missing from https://github.com/git-for-windows/git/issues/282 which describes essentially the same problem, but in more detail.

**Comment by anb0s** [comment]
I'm using the "PortableGit" version and have no "Git Bash" and other menues if yopu mean this. I've tried git-bash.exe, bash-exe, sh.exe but always the same issue. How did it worked in version 2.4.5.1 ?

After some googling I've found one workaround for me: added to my .bash_profile:
export TERM=xterm-color

May i ask for the proper MSYSTEM value?

Thank You for your support!

**Comment by anb0s** [comment]
I've started it from shortcuts, e.g.:
D:\Programme\PortableGit\git-bash.exe
OR
d:\Programme\PortableGit\bin\bash.exe" --login -i

And the same from ConEmu:
-new_console:d:F:\git"d:\Programme\PortableGit\bin\bash.exe" --login -i

**Comment by dscho** [comment]
`git-bash.exe` should open a new `mintty` window...

In any case, I am uploading new installers with [the hotfix](https://github.com/git-for-windows/build-extra/commit/47ff821f65a0ab45e12aa6712825d31448381f0a).

**Comment by dscho** [comment]
Uploaded. Can you test, please?

**Comment by dscho** [comment]
> May i ask for the proper MSYSTEM value?

Yes, of course: it should be `MINGW64` (or `MINGW32` for 32-bit Git for Windows).

**Comment by anb0s** [comment]
I've just downloaded and tested "PortableGit-2.5.0-64-bit.7z.exe" without the line "export TERM=xterm-color" and it works!

Thank You :+1:

**Comment by dscho** [comment]
Perfect, thanks for confirming!
