### ISSUE TITLE
git hangs on most commands

### ISSUE THREAD

**Issue by AvrumFocus** [git-for-windows/git#2815]
* [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 64bit

```
The below command is the output from git bugreport output
git version 2.28.0.windows.1
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.18363.959]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**CMD**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Almost all git commands trigger this issue, even commands not related to a repo. For example:
git version
```

 - What actually happened instead?

git hangs indefinitely 

I attached the output from a process monitor capture I ran. Extension needs to be renamed to `pml`

[Logfile.txt](https://github.com/git-for-windows/git/files/5236173/Logfile.txt)

**Comment by dscho** [comment]
This is related to https://groups.google.com/g/git-for-windows/c/hHzDoeVLHSI, right?

>     * What commands did you run to trigger this issue? If you can provide a
>       [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
>       this will help us understand the issue.
> 
> 
> ```
> Almost all git commands trigger this issue, even commands not related to a repo. For example:
> git version
> ```

![image](https://user-images.githubusercontent.com/127790/93437832-ba401480-f8cc-11ea-9897-fb5e5d194a3b.png)

Seriously, this really does not happen over here, i.e. it is not reproducible.

From your email:

> Since somewhere last week git has started to freeze on most commands issued. 

That sounds very suspicious. It looks as if there was some event that is independent from Git for Windows that however impacts Git for Windows in some way. Maybe your anti-malware goes haywire?

**Comment by AvrumFocus** [comment]
@dscho Thanks for taking your time to look into the issue and even try reproducing the issue.

Yes that thread is also by me. 👍 

I was working through the night yesterday to try to figure out what was causing it. Thanks to ProcessMonitor from sysinternals I managed to track it down to a piece of software (malware?) that was on my computer that was injecting a dll in the thread and causing the hang. 

So case closed.

p.s.
1. I understood that it might not be git at fault as I had it working fine myself on multiple other computers. I was concerned it was a race condition in git and was looking for ways to find it.

2. Serious question: in a case like this what is considered a good mcve?

**Comment by dscho** [comment]
I am so glad you figured it out!

>     2\. in a case like this what is considered a good mcve?

That is a real good question for which I lack a real good answer 😄
