### ISSUE TITLE
gitbash > vim - :set cursorcolumn not working

### ISSUE THREAD

**Issue by dfnk5516** [git-for-windows/git#2816]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```  

$ git --version --build-options

** insert your machine's response here **
```
git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.14393]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
I use ssh to virtual machine(oracle virtualbox - centos7) and execute vim command

 - What did you expect to occur after running these commands?

** insert here **
In vim,
:set cursorcolumn 
command not worked.
however the other bash program(such as putty) working

 - What actually happened instead?

** insert here **
not working

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by amitbhardwaj-coder** [comment]
I am using 64 bit

**Comment by dscho** [comment]
>  :set cursorcolumn

It would be good to explain what that feature does: keep in mind that most readers are aware of only a fraction of vim's features, if at all.

I went ahead and just tried it, although I have to admit that I SSHed into an Ubuntu VM. This is what it looks like over here: 
![image](https://user-images.githubusercontent.com/127790/93439747-350a2f00-f8cf-11ea-9920-cddc3e814dc4.png)

I assume that _does_ look like it is working?

FWIW my environment variable `TERM` seems to be set to `screen` when I ssh into that VM. Not sure what your's is.

**Comment by chrisbra** [comment]
> I use ssh to virtual machine(oracle virtualbox - centos7) and execute vim command
> In vim,
> :set cursorcolumn
> command not worked.
> however the other bash program(such as putty) working

Are you sure, that the remote vim actually supports `cursorcolumn`?  Please show the `:version` output, cursorcolumn needs the syntax feature, so if you are using a minimal vim, it may not support it. But you should get an error message in that case.
Also, please mention any error messages.

**Comment by dfnk5516** [comment]
after nothing happend just avail to move cursor with arrow key(or jkhl)
 
with putty program in same server 
works clear.
 
 
my vim version is 7.4
 
 
-----Original Message-----

**Comment by amitbhardwaj-coder** [comment]
Utiroes cb8d8didnr

**Comment by dfnk5516** [comment]
![image](https://user-images.githubusercontent.com/52561899/94538396-f1280a00-027e-11eb-93b7-e55d7cd283fc.png)
It worked on my home desktop.

![image](https://user-images.githubusercontent.com/52561899/94538497-0ac95180-027f-11eb-8b66-0c0d8d057d85.png)
But it still doesn't work on the academy's computer

![image](https://user-images.githubusercontent.com/52561899/94538526-11f05f80-027f-11eb-896d-0c8f3d0564ae.png)
 while putty works.

![image](https://user-images.githubusercontent.com/52561899/94538606-2a607a00-027f-11eb-85dc-d05829676e93.png)
The git version is 2.28 and the vim version is 7.4.

**Comment by dscho** [comment]
Aren't you comparing Windows Terminal with MinTTY in the first two screenshots?

**Comment by chrisbra** [comment]
try playing around with $TERM

**Comment by chrisbra** [comment]
Anyhow, I think this is a vim configuration problem and not a git-for-windows one.

**Comment by dfnk5516** [comment]
> Aren't you comparing Windows Terminal with MinTTY in the first two screenshots?

Oh my god I thought the windows terminal was the same because it also uses git. Using pure git, I confirmed that it does not work the same. How are you going to work?

**Comment by dfnk5516** [comment]
I'm not sure how to make this work with $TERM. Anyway, I found out that it's not a problem with git bash. Thanks!

**Comment by dscho** [comment]
> I'm not sure how to make this work with $TERM

The first step would be to figure out the values of `TERM` when connecting via `ssh` in all of the cases you showed, the working as well as the non-working. It's quite possible that you can "fix" this by setting the `TERM` variable in a non-working scenario to the value shown in a working scenario.

**Comment by dfnk5516** [comment]
> The first step would be to figure out the values of `TERM` when connecting via `ssh` in all of the cases you showed, the working as well as the non-working. It's quite possible that you can "fix" this by setting the `TERM` variable in a non-working scenario to the value shown in a working scenario.

Thanks a lot, I'll try it as you said :)
