### ISSUE TITLE
Unable to use SSH commands in git-bash

### ISSUE THREAD

**Issue by bsudhir6** [git-for-windows/git#2825]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

**git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh**

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.17763.1457] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

** $ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** git-cmd is working fine but git-bash is not working. **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**git-bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** Sudhir@DESKTOP-HNPAF0V MINGW64 /
$ ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]

Sudhir@DESKTOP-HNPAF0V MINGW64 /
$ ssh -V
OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

Sudhir@DESKTOP-HNPAF0V MINGW64 /
$ ssh-add
Could not open a connection to your authentication agent.

Sudhir@DESKTOP-HNPAF0V MINGW64 /
$ ssh-agent

Sudhir@DESKTOP-HNPAF0V MINGW64 /
$ ssh-add -l
Could not open a connection to your authentication agent.

Sudhir@DESKTOP-HNPAF0V MINGW64 /
$ eval `ssh-agent -s`

Sudhir@DESKTOP-HNPAF0V MINGW64 /

 **
```
 - What did you expect to occur after running these commands?

** for ssh-agent I am expecting to see list of commands or start the command.
for ssh-add it should return error for providing key location instead it is showing blank
for ssh-add -l should show the keys I have added which is working fine in git-cmd but not working in git-bash
for eval `ssh-agent -s` it should return a process id but its not returning anything. basically all ssh commands ending either with nothing or the error.**

 - What actually happened instead?

** for ssh-agent not working
for ssh-add not working
for eval `ssh-agent -s` not working **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Thank you for the report, and welcome to the community!

The SSH agent needs to be started first, and the output needs to be `eval`ed initially, i.e. before running `ssh-add`. See https://github.com/git-for-windows/git/wiki/Auto-launching-ssh-agent-when-git-starts for a thorough description of the steps to take to auto-start the SSH agent.

**Comment by bsudhir6** [comment]
Hello dscho,,

 still it is not working pls check below output:


Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$ start-ssh-agent.cmd

Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$ ssh-add -l

Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$ ssh-add
Could not open a connection to your authentication agent.

Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$ ssh-agent

Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$ ssh-agent -k
SSH_AGENT_PID not set, cannot kill agent

Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$ eval `ssh-agent`

Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$ ssh-agent -k
SSH_AGENT_PID not set, cannot kill agent

Sudhir@DESKTOP-HNPAF0V MINGW64 ~
$
![mintty_V9p7Ufqf5x](https://user-images.githubusercontent.com/2923168/93750719-8f7df500-fc19-11ea-81fb-68e7e8e1cc57.png)

**Comment by dscho** [comment]
> Sudhir@DESKTOP-HNPAF0V MINGW64 ~
> $ start-ssh-agent.cmd

This command is not intended to be run in Git Bash (I think the wiki page has it wrong). For Git Bash, you will have to follow the advice in the ["Manually" section](https://github.com/git-for-windows/git/wiki/Auto-launching-ssh-agent-when-git-starts#manually).

**Comment by bsudhir6** [comment]
Still facing same problem
![image](https://user-images.githubusercontent.com/2923168/93972740-7c416580-fd90-11ea-8ea9-44138c7b89d9.png)

**Comment by bsudhir6** [comment]
pls help

**Comment by dscho** [comment]
Have you tried running `eval "$(ssh-agent -s)"` and _then_ `ssh-add`?

**Comment by bsudhir6** [comment]
Yes I ran like that also it was same i am getting empty response for these commands.

**Comment by dscho** [comment]
> i am getting empty response for these commands.

That usually means "success"...
