### ISSUE TITLE
garbage encoding in 2.27.0 and 2.28

### ISSUE THREAD

**Issue by zchrissirhcz** [git-for-windows/git#2826]
Problem description: `git status` doesn't show unicode chars correctly for some latest git bash versions.

OS: Windows 10

| git bash version | `git status` correctly show unicode chars? |
| ----------------   | ---------- |
| 2.24.0.2              |  Yes         |
| 2.26.2                 |  Yes         |
| 2.27.0                 |  No         |
| 2.28                    |  No         |

Note: 
My ~/.gitconfig:
```
[core]
        autocrlf = true
        quotePath = false
```
My git bash options for locale:
![image](https://user-images.githubusercontent.com/3831847/93728330-1323eb80-fbf2-11ea-8f72-ed373bd00aa7.png)

My expectation: git bash 2.27.0 & 2.28 can show unicode chars correctly

What I get:
![image](https://user-images.githubusercontent.com/3831847/93728356-2e8ef680-fbf2-11ea-80fd-7fa99cfce785.png)

![image](https://user-images.githubusercontent.com/3831847/93728365-3a7ab880-fbf2-11ea-97c8-221f47bafcf9.png)

**Comment by dscho** [comment]
Thank you for opening this ticket. This issue looks as if it could have the same underlying cause as https://github.com/msys2/MSYS2-packages/issues/1974. Could you try the suggested workaround (`cmd //c chcp 65001`)?

**Comment by zchrissirhcz** [comment]
@dscho Tested with the latest git-for-windows (2.28). After executing `cmd //c chcp 65001`, `git status` show correctly for unicode chars.

I've also noticed that, VSCode Insider 1.49 is complaining git's version is not >= 1.27 for its git extension. Though I don't use VSCode's git extension, other people may use, don't know if my mentioned garbage encoding will affect them.

Seems like I have to execute `cmd //c chcp 65001` each time I open git bash. Looing forward for the fix for mintty. For convenience, I now switch to git-for-windows 1.26.2.

**Comment by dscho** [comment]
> For convenience, I now switch to git-for-windows 2.26.2.

Sounds good. I really hope we will have resolved this by the time v2.29.0 comes out (which [is due around October 19th](https://tinyurl.com/gitCal)).

**Comment by dscho** [comment]
Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by zchrissirhcz** [comment]
@dscho Tested with Git-prerelease-2.28.0.windows.1-51-g87c86a26de-20200923135803-64-bit.exe, the `git status` not correctly show unicode chars.

**Comment by zchrissirhcz** [comment]
@dscho  However I found it strange that several git commands are not working now.

e.g. `git push origin xxx_branch` gives no response, and `git remote show origin` gives empty result while my local project is actually cloned from my github repo.

**Comment by zchrissirhcz** [comment]
Still fallback to use 2.26.2.

**Comment by dscho** [comment]
>  I found it strange that several git commands are not working now.
> 
> e.g. `git push origin xxx_branch` gives no response, and `git remote show origin` gives empty result while my local project is actually cloned from my github repo.

Is this the reason you reopened this issue? That would be misleading, as the ticket does not even talk about `git push`...

As it were, I can reproduce, and I figured out that `/mingw64/bin/libzstd.dll` is missing. Working on it.

**Comment by zchrissirhcz** [comment]
@dscho Yes, you correctly point out why I re-opened this issue.  Closed according to your advice.

**Comment by dscho** [comment]
The newest snapshot seems to fix the `git push`/`git remote show` bug for me. @zchrissirhcz could I ask you to test the latest snapshot?

**Comment by zchrissirhcz** [comment]
@dscho Tested with Git-prerelease-2.28.0.windows.1-52-gbcabfe850c-20200924200432-64-bit.exe

- `git status` correctly show unicode chars
- `git remote show origin` and `git push` correctly response.
