### ISSUE TITLE
git push failed when using a https upstream url with password

### ISSUE THREAD

**Issue by TooYoungTooSimp** [git-for-windows/git#2832]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
`MinGit-2.28.0-64-bit.zip`

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 2004 64bit

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19041.508]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

No, I'm using portable git and its /etc dir doesn't have this file.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

On my another computer running `git version 2.19.1.windows.1` (also mingit), it runs well.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
```
 - What did you expect to occur after running these commands?

git asks password just like it in msys2 terminal
![image](https://user-images.githubusercontent.com/6648049/94130713-99109280-fe8f-11ea-93ae-bf1f2da32ec7.png)

 - What actually happened instead?

![image](https://user-images.githubusercontent.com/6648049/94130546-66669a00-fe8f-11ea-9355-d388839d4ea3.png)

**Comment by TooYoungTooSimp** [comment]
Although I found some related issue, but they are too old to explain why 2.19 can work while 2.28 can't.

**Comment by TooYoungTooSimp** [comment]
Another thing: When I `git push` in vscode's terminal, vscode popped up a box to let me input password
![image](https://user-images.githubusercontent.com/6648049/94131351-64510b00-fe90-11ea-80db-eba33d9cb38d.png)

**Comment by dscho** [comment]
MinGit is not intended for interactive usage, but instead for use by applications (which either have to provide their own credential manager, or use the bundled Git Credential Manager (Core), or provide the credentials via `http.extraHeaders`).

The fact that it works in VS Code is not by design, but by pure sheer luck (which may turn in the future).

Please use the Portable Git edition of Git for Windows if you want to use Git interactively.

**Comment by TooYoungTooSimp** [comment]
Thanks for your very fast answer. I understand the situation now. But I still missed the old days when mingit can also ask me for a password just like it was in 2.19😭

**Comment by dscho** [comment]
> But I still missed the old days when mingit can also ask me for a password just like it was in 2.19😭

I _think_ you could create the `dev` folder, then the `dev\shm` and `dev\mqueue` folders, and it _might_ work again.

**Comment by TooYoungTooSimp** [comment]
> > But I still missed the old days when mingit can also ask me for a password just like it was in 2.19😭
> 
> I _think_ you could create the `dev` folder, then the `dev\shm` and `dev\mqueue` folders, and it _might_ work again.

sadly I'v tried this but don't work. I think I can just use it with msys2 terminal or vscode currently😥
