### ISSUE TITLE
ship zstd compression program for use with tar

### ISSUE THREAD

**Issue by esskov** [git-for-windows/git#2836]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.508]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Tar help indicates support for zstd.

```
$ tar --help | grep zst
      --zstd                 filter the archive through zstd
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ tar -xv --zstd -f archive.tar.zst
$ tar -cv --zstd -f archive.tar.zst xxx
```
 - What did you expect to occur after running these commands?

Expected the tar command to complete successfully.

 - What actually happened instead?

```
/bin/sh: zstd: command not found
tar: archive.tar.zst: Cannot write: Broken pipe
tar: Child returned status 127
tar: Error is not recoverable: exiting now
```

**Comment by rimrul** [comment]
`tar` help indicates support for many compression programms. It just means `if you have it you can use it`.  

There is a `zstd` MinGW package, so we could ship `zstd` fairly easily, if it doesn't add to much to the size of the installer.

**Comment by rimrul** [comment]
@dscho does the reason you specifically excluded `zstd.exe` [on your recent fix for `libcurl`'s dependency on `libzstd`](https://github.com/git-for-windows/build-extra/commit/d76e46e70f5904c0732411f98b5ae3b4577f1449#diff-6859b7c801fd9376747ed5062ff840a3) go beyond the fact it isn't needed for `libcurl`? Or would we probably just need a PR with a commit that changes [this `*` to a `+`](https://github.com/git-for-windows/build-extra/blob/main/make-file-list.sh#L133) and has a commit message that describes the advantages of shipping `zstd.exe` and what impact this has on the installer [similar to this one](https://github.com/git-for-windows/build-extra/commit/62ec21788a7f9c60d0feca3d135c07d631be4b37#diff-6859b7c801fd9376747ed5062ff840a3)?

**Comment by dscho** [comment]
> does the reason you specifically excluded `zstd.exe` [on your recent fix for `libcurl`'s dependency on `libzstd`](https://github.com/git-for-windows/build-extra/commit/d76e46e70f5904c0732411f98b5ae3b4577f1449#diff-6859b7c801fd9376747ed5062ff840a3) go beyond the fact it isn't needed for `libcurl`?

Well, `zstd.exe` _does_ weigh in with 845K...

Having said that, I would be fine including it, but only if we still exclude it in MinGit. In other words, it would make sense to me to move the exclusion of `zstd.exe` specifically to [this code block](https://github.com/git-for-windows/build-extra/blob/47b09663791ed936d07395d777d2f542210107f4/make-file-list.sh#L188-L261).

**Comment by esskov** [comment]
> `tar` help indicates support for many compression programms. It just means if you have it you can use it

Fair enough. However, I would consider zstd a useful addition, not just for tar. Its performance it noticeably better than good old gzip.

**Comment by dscho** [comment]
> > `tar` help indicates support for many compression programms. It just means if you have it you can use it
> 
> Fair enough. However, I would consider zstd a useful addition, not just for tar. Its performance it noticeably better than good old gzip.

That's a good point, but an even better point is: Git for Windows' mission is to bring *Git* to Windows, it's not a general-purpose distribution of all kinds of useful Unix tools. That would be [MSYS2](https://msys2.github.io/). You'll probably be much better off using MSYS2, it even comes with _many_ more packages than just Git.

**Comment by esskov** [comment]
Right, I see. Or perhaps the real alternative these days is [WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git).

**Comment by dscho** [comment]
@esskov are you still interested in this? If so, I tried to outline in https://github.com/git-for-windows/git/issues/2836#issuecomment-700683049 what it would take...

**Comment by dlong500** [comment]
I'm definitely interested in this especially since zstd is now the default for all MSYS2 packages.  Not including this in the Git for Windows release means anyone manually installing any other excluded MSYS2 package now has to first manually install `zstd` and probably also `libzstd` and `libxxhash` because of the system-wide migration to zstd.  I'd love to see those three packages included in Git for Windows.

I completely understand that Git for Windows' mission is centered on "Git", but the MSYS2 move to zstd now makes it harder for users to manually customize installs by requiring even more missing packages to be installed for pretty common use cases.  I'd argue that `zstd` (and related libraries) are now a "core" part of the MSYS2 foundation (as much as something like `tar` already is).  Would you still be willing to take a PR on something like this?

**Comment by dscho** [comment]
@dlong500 see https://github.com/git-for-windows/git/issues/2836#issuecomment-709589486

**Comment by MagicJack** [comment]
I saw that 'mingw-w64-x86_64-zstd 1.5.2-1' was listed in file `/etc/package-versions.txt`.
But, why there's no zstd.exe in package of Git-2.35.1.2-64-bit ?

**Comment by dscho** [comment]
> I saw that 'mingw-w64-x86_64-zstd 1.5.2-1' was listed in file `/etc/package-versions.txt`. But, why there's no zstd.exe in package of Git-2.35.1.2-64-bit ?

That's because we [exclude it specifically](https://github.com/git-for-windows/build-extra/blob/a17cf373fe240e168545038a8cba8906298a7e87/make-file-list.sh#L133): it weighs in with 933kB and Git for Windows does not need it.

Let's give this ticket its well-deserved rest; If there had been enough interest, [the work](https://github.com/git-for-windows/git/issues/2836#issuecomment-700683049) would have been completed already.
