### ISSUE TITLE
git for windows doesn't support for sshfs mount

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#2846]
X:\work\study\base-library\rulibc>git submodule
/mingw64/libexec/git-core/git-sh-setup: line 189: cd: //sshfs/root@192.168.199.1/shared/work/study/base-library/rulibc: No such file or directory
Cannot chdir to $cdup, the toplevel of the working tree

Windows 10 2004
install https://github.com/billziss-gh/sshfs-win

net use X: \\sshfs\root@192.168.199.1\shared

clone to rulibc that have submodule

x64 version

```
X:\work\study\base-library\rulibc>git --version
git version 2.28.0.windows.1
```

```
X:\work\study\base-library\rulibc>git rev-parse --show-toplevel
//sshfs/root@192.168.199.1/shared/work/study/base-library/rulibc
```

**Comment by dscho** [comment]
@lygstate I have to ask you, once again, to fill out the full bug reporting template. In particular, your report is missing such crucial information as: where on earth does your sshfs mount come from? Like, what is `X`? What software did you install to have that mount? How did you configure it?

**Comment by lygstate** [comment]
maybe sshfs not stable yet, close this first,

**Comment by dscho** [comment]
Unforhunately, this does not answer any of my questions.
