### ISSUE TITLE
Git Checkout Failed during clone or reset when there is illegal character from remote

### ISSUE THREAD

**Issue by kaovilai** [git-for-windows/git#2849]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.508]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

   - Nope.. but to create this bug requires that another system (ie, WSL2 Ubuntu 20.04) not having same characters as illegal characters be the ones adding files to the remote prior to cloning/reset

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Minimal
```
git clone https://github.com/kaovilai/gitFW-checkout-failed-issue-urlfolder/
```
 - What did you expect to occur after running these commands?
    - Successful clone of remote repository or explanation about illegal characters

 - What actually happened instead?
   - Checkout failed

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

   - [https://github.com/kaovilai/gitFW-checkout-failed-issue-urlfolder](https://github.com/kaovilai/gitFW-checkout-failed-issue-urlfolder)

**Comment by dscho** [comment]
This is actually a known issue, and there have been valuable discussions around it already. In [the most recent report](https://github.com/git-for-windows/git/issues/2803), I wrote up a detailed analysis/project plan: https://github.com/git-for-windows/git/issues/2803#issuecomment-689621560

It might make sense to continue our discussion in that ticket; To that end, I will mark this here ticket as a duplicate.

> https/wikipedia.com was commited from a Windows machine.

This sounds as if you had created that not necessarily just on "a Windows machine", but either using Cygwin's or MSYS2's shell tools. Cygwin (and by extension, the MSYS executables in MSYS2) use a trick to work around illegal file name characters: they are mapped into a private Unicode page, and that's what you are seeing here. Neither WSL nor regular Win32 tools (such as `git.exe`) know that they are expected to map those characters back to ASCII.

**Comment by kaovilai** [comment]
> > https/wikipedia.com was commited from a Windows machine.
> 
> This sounds as if you had created that not necessarily just on "a Windows machine", but either using Cygwin's or MSYS2's shell 

Nope.. I just cloned the repo from WSL Ubuntu and the resulting folder (shared between two systems via WSL) in Windows is committed and pushed. I have not installed cygwin or msys myself unless its something WSL does in the backend regarding files.

So.. running the curl on ubuntu
git add *, commit and push from Windows creates https://github.com/kaovilai/gitFW-checkout-failed-issue-urlfolder/tree/main/https%EF%80%BA/wikipedia.com
pull and git add * commit and push creates https://github.com/kaovilai/gitFW-checkout-failed-issue-urlfolder/tree/main/https:/wikipedia.com
I was able to still add from ubuntu because whatever was pushed from Windows is different (and invisible to Ubuntu??)
