### ISSUE TITLE
Submit all of the Windows-specific patches upstream

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#285]
This is a _huge_ undertaking. At the moment, Git for Windows carries 200+ commits, organized in 20+ topic branches, on top of upstream Git.

**Comment by dscho** [comment]
The first patch series was contributed [already last year](http://thread.gmane.org/gmane.comp.version-control.git/280190), containing miscellaneous patches that are actually not specific to Windows at all.

I also ported the `pull --rebase=interactive` patches to the builtin `git pull` and [contributed them yesterday](http://thread.gmane.org/gmane.comp.version-control.git/283904).

And finally, I contributed the first *true* Git for Windows patch series [yesterday](http://thread.gmane.org/gmane.comp.version-control.git/283915).

**Comment by pclouds** [comment]
Sorry for the noise, but dscho is now truly back ;-)

**Comment by dscho** [comment]
@pclouds that's the kind of noise I like ;-)

**Comment by nalla** [comment]
:bow: @dscho

**Comment by dscho** [comment]
The first two patch series made it into the 'next' branch.

And I contributed [the third batch](http://thread.gmane.org/gmane.comp.version-control.git/284664) today, which finally should allow the source code of git.git to be compiled and to pass the test suite in MSYS2 out of the box, i.e.without additional patches and make options.

**Comment by dscho** [comment]
Update: the first two patch series were combined into a single topic branch and are already merged into `master`: https://github.com/git/git/compare/116a866bf50da9b893623ebb940e1c6bff7a29bc%5E...116a866bf50da9b893623ebb940e1c6bff7a29bc%5E2

**Comment by dscho** [comment]
And the third batch of patches was also accepted: https://github.com/git/git/compare/4b589e5b28^...4b589e5b28^2

Next batch submitted: http://thread.gmane.org/gmane.comp.version-control.git/292207

**Comment by dscho** [comment]
Next cherry-picked patch: [let Git detect MSYS2's pseudo terminals correctly](http://thread.gmane.org/gmane.comp.version-control.git/292731).

**Comment by dscho** [comment]
Next cherry-picked patch: [hiding `.git/` by default](http://thread.gmane.org/gmane.comp.version-control.git/293549).

**Comment by dscho** [comment]
> Next batch submitted: http://thread.gmane.org/gmane.comp.version-control.git/292207

Was accepted, too: https://github.com/git/git/compare/f9dd74134ad98c80f36d2cf57cd368f5efc8df08%5E...f9dd74134ad98c80f36d2cf57cd368f5efc8df08%5E2

**Comment by dscho** [comment]
> Next batch submitted: http://thread.gmane.org/gmane.comp.version-control.git/292207

Accepted: https://github.com/git/git/compare/f12fffd347ac1efc11381dfdce5aa4108731742d^...f12fffd347ac1efc11381dfdce5aa4108731742d

> Next cherry-picked patch: hiding .git/ by default.

As was this: https://github.com/git/git/compare/bfc99b63fe859e16ddcfcbe6ac09f98b8d06b34e%5E...bfc99b63fe859e16ddcfcbe6ac09f98b8d06b34e

That currently leaves only the isatty patch in flight.

**Comment by dscho** [comment]
And now also the isatty patch was merged: https://github.com/git/git/compare/07ffe87%5E...07ffe87

**Comment by dscho** [comment]
This is a constant effort. So a ticket is actually not really a good way to track this. I'll just close it.
