### ISSUE TITLE
Option for docx2txt to output to stdout

### ISSUE THREAD

**Issue by romangrothausmann** [git-for-windows/git#2856]
The common Linux gitconfig entry for textdiff of DOCX files 

```
[diff "docx"]
    binary = true
    textconv = sh -c 'docx2txt "$0" -'
```

does not work with git-for-windows because `docx2txt` there is a wrapper around  `docx2txt.pl` which does not handle `-`
to output to stdout. It would be greate if that could be added such that a repo with a `.gitconfig` for Linux does alos work for windows (e.g. pdftotxt does work for both). 

My current workaround was to  `mv /usr/bin/docx2txt /usr/bin/docx2txt.sh` and `cp /usr/bin/docx2txt.pl /usr/bin/docx2txt`.

### Setup

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1082]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

cat /etc/install-options.txt
Editor Option: Nano
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** sh -c 'docx2txt $0 -'  myDoc.docx **
```
 - What did you expect to occur after running these commands?

** docx converted to text printed on stdout (not into file) **

 - What actually happened instead?

** got usage info (because current docx2txt writes to file and does not accept - for printing to stdout **

**Comment by dscho** [comment]
Good find! Any chance you can install Git for Windows' SDK and run `pacman -Qo /usr/bin/docx2txt` (also with the `.pl`) to find out which package needs to be fixed?

**Comment by romangrothausmann** [comment]
Thanks @dscho for looking into this. I'll try to get the package names but probably won't find the time before next weekend. Odd though that nobody had this problem before.

**Comment by dscho** [comment]
```
$ pacman -Qo /usr/bin/docx2txt*
/usr/bin/docx2txt is owned by docx2txt 1.4-1
/usr/bin/docx2txt.pl is owned by docx2txt 1.4-1
```

**Comment by dscho** [comment]
From the beginning of `/usr/bin/docx2txt`:

```
# A simple .docx to .txt converter
#
# This script is a wrapper around core docx2txt.pl and saves text output for
# (filename or) filename.docx in filename.txt .
```

So apparently, it is intentional?

**Comment by dscho** [comment]
After having a look at http://docx2txt.sourceforge.net/, I am rather convinced that the `docx2txt` wrapper is intentionally _not_ handling `stdout` because it wants to write the output into a `.txt` file next to the original `.docx` file. So it _does_ need a path. I get the impression from the `docx2txt` project page that the streaming use case is intentionally handled by `docx2txt.pl`.

So there is actually no bug in Git for Windows?

**Comment by romangrothausmann** [comment]
Thanks @dscho for checking the packages and the sources.

 > So there is actually no bug in Git for Windows?

I would not call it a bug but an inconsistency with the common config under Linux where `docx2txt.pl` is installed as `docx2txt` and used as such for defining textdiffs of DOCX. It would be great if the common config under Linux would also work under git for win, such that repos created under Linux do get a docx textdiff even if cloned under windows. 
Currently, DOCX textdiffs work out of the box under windows (which is great) but as soon as a .gitconfig from Linux is added to the repo textdiffs for DOCX do not work any more (due to the described problem). PDF text are not effected because `pdftotext` accepts the `-` for outputting to stdout (only difference to `pdftotext` under Linux that I noticed is that under windows the input PDF needs to be provided after the options, which also works under Linux but this order is not mandatory under Linux).

**Comment by dscho** [comment]
> an inconsistency with the common config under Linux where `docx2txt.pl` is installed as `docx2txt`

An inconsistency it is, indeed. The `docx2txt` project itself does not seem to install it that way.

So if we did what you ask for, we would now _intentionally_ disagree with the `docx2txt` project. I am not sure that I am prepared to do that. Every such disagreement comes with a maintenance burden (that _I_ would have to carry, of course, so I will pay the price of our decision, whichever way it falls).

**Comment by romangrothausmann** [comment]
Yes, I fully understand that. The issue is meant as a suggestion. Perhaps others might have another idea how this inconsistency could be solved better. I just find it a pity that a working `textconv` config for DOCX on Linux does break on windows, whereas all other `textconv` (e.g. PDF) keep working. It seem something similar is needed on MacOS: https://stackoverflow.com/questions/22190208/version-control-word-docx-files-with-docx2txt-with-git-on-mac-os-x#23421457.

**Comment by dscho** [comment]
Closing as stale.
