### ISSUE TITLE
windows installer installs under the wrong user directory

### ISSUE THREAD

**Issue by perryjr** [git-for-windows/git#2858]
windows 10 home - 64 bit

![image](https://user-images.githubusercontent.com/24496245/96356377-57a08b00-10bb-11eb-83ea-972dd1cd40a4.png)

 There are three user accounts on the OS.  I am logged in as "user A" which is an administrator account

downloaded and ran https://github.com/git-for-windows/git/releases/download/v2.28.0.windows.1/Git-2.28.0-64-bit.exe

get through the entire install process and I notice it is not installing into a directory under "user A"

![image](https://user-images.githubusercontent.com/24496245/96356340-f4165d80-10ba-11eb-9953-a7ae03c7f69d.png)

the install ends with an error message:

![image](https://user-images.githubusercontent.com/24496245/96356350-0abcb480-10bb-11eb-9a3f-40478aa29f83.png)

and if i attempt to "launch git bash" from the setup app, the previous error message is followed with the following error message:

![image](https://user-images.githubusercontent.com/24496245/96356367-350e7200-10bb-11eb-86cd-2ea15e725a54.png)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I chose all default installation options

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

the following are present under the start menu of "user A"

![image](https://user-images.githubusercontent.com/24496245/96356392-8fa7ce00-10bb-11eb-8cb2-6b844afee35a.png)

but attempting to open the item "git bash" results in the following:

![image](https://user-images.githubusercontent.com/24496245/96356394-9f271700-10bb-11eb-953c-3c342c71d51f.png)

the errant installation of gitbash does open perfectly fine after logging into the other user. in this case it was the "test" user

**Comment by dscho** [comment]
Hi @perryjr! That's indeed not good.

If I remember correctly, the installer does show the installation location when installing afresh, right after the license page. Did that happen in your case?

Anyhow, it _is_ an unintended default.

The installer is built using InnoSetup, and this is the line specifying the default location: https://github.com/git-for-windows/build-extra/blob/b3b6d2e67e84001d7f11fe80ddfadd5883801b1b/installer/install.iss#L64

The `{pf}` constant is no longer documented at https://jrsoftware.org/ishelp/index.php?topic=consts, but https://github.com/jrsoftware/issrc/blob/767dbb835d4420887f0f99e137f70e0bedf08418/Projects/SetupTypes.pas#L281-L282 suggests that it is merely an alias for `{commonpf}` now, which is the correct thing to do.

Now, the thing I don't understand is: why does InnoSetup think that your common Program Files is not `C:\Program Files`, but instead looks more like your user-specific Program Files? I _suspect_ this to be a special feature of your local setup...

**Comment by perryjr** [comment]
Greetings,

I don't specifically remember being prompted to choose an installation location on that "first run" but I definitely wasn't prompted on subsequent attempts.  I probably should have uninstalled and reinstalled.  Anyway the portable version of the tool works fine. Thank you
