### ISSUE TITLE
Unable to pass parameters to c:\windows\system32\cmd.exe

### ISSUE THREAD

**Issue by JohnPSYMQEPDFQ** [git-for-windows/git#2862]
$ git --version --build-options
git version 2.29.0.windows.1
cpu: x86_64
built from commit add3cebdf89e93784955b34e1c1ffcba308b89cc
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.1139]

$ cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Disabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

### Details

Running the following command from the bash shell doesn't work:

**cmd /c dir**

The results is to simply present the Windows CMD shell prompt, as follows:

**John@Dell01 MINGW64 /**
**$ cmd /c dir**                                                   <<< this should run the Windows CMD shell and do a "dir" command and return
**Microsoft Windows [Version 10.0.18362.1139]**
**(c) 2019 Microsoft Corporation. All rights reserved.**

**C:\Program Files\Git>**                                   <<< Instead, it starts the Windows CMD shell as if no parameters were supplied.

I've also tried this:

**c:/windows/system32/cmd /c dir**
-and-
**c:/windows/system32/cmd.exe /c dir**

Which also doesn't work.     

AND,  running the following does exactly the same thing:

**$ git-cmd /c dir**                                             <<<  the git-cmd program

**C:\Program Files\Git>**                                    <<<  the command prompt instead of the "dir" results.

HOWEVER, when running from the git-cmd shell, the following command DOES work:

**C:\Program Files\Git>cmd /c dir**
**cmd /c dir**
 **Volume in drive C is OS**
 **Volume Serial Number is 52D3-3C90**

 **Directory of C:\Program Files\Git**

**10/20/2020  03:11 PM    <DIR>          .**
**10/20/2020  03:11 PM    <DIR>          ..**
**10/19/2020  05:18 PM    <DIR>          bin**
**10/19/2020  05:19 PM    <DIR>          cmd**
**10/19/2020  05:19 PM    <DIR>          dev**
**10/19/2020  05:19 PM    <DIR>          etc**
**10/19/2020  08:28 PM           152,128 git-bash.exe**
**10/19/2020  08:28 PM           151,616 git-cmd.exe**
**--etc--**

It seems when the cmd command is run from the bash shell the parameters are not passed.

I've looked for other cmd programs accidently in the path:

**John@Dell01 MINGW64 /**
**$ which cmd**
**/c/windows/system32/cmd**

**John@Dell01 MINGW64 /**
**$ which cmd.exe**
**/c/windows/system32/cmd.exe**

But there are none.

I've looked for a function named cmd:

**$ set | grep -E '\(.*\)|function' | grep -i cmd
BASH_CMDS=()
    local word cmdline=$(__git config --get "alias.$1");
    if [ -n "$(__git_find_on_cmdline "--no-track")" ]; then
    last_option="$(__git_find_last_on_cmdline "--guess --no-guess")";
    test -n "$__git_all_commands" || __git_all_commands=$(__git --list-cmds=main,others,alias,nohelpers)
__git_find_last_on_cmdline ()
__git_find_on_cmdline ()
                    __gitcomp "$(__git --list-cmds=list-mainporcelain,others,nohelpers,alias,list-complete,config)";
    test -n "$__git_cmds_with_parseopt_helper" || __git_cmds_with_parseopt_helper="$(__git --list-cmds=parseopt)";
        options=" $incl $(__git ${cmd/_/ } $completion_helper) " || return;
    if test -n "$(__git_find_on_cmdline "-u --update")"; then
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
            if [ -n "$(__git_find_on_cmdline "-b -B -d --detach --orphan")" ]; then
                if [ -n "$(__git_find_on_cmdline "--track")" ]; then
        __gitcomp "$GIT_TESTING_ALL_COMMAND_LIST $(__git --list-cmds=alias,list-guide) gitk";
        __gitcomp "$(__git --list-cmds=main,nohelpers,alias,list-guide) gitk";
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
    local subcommand="$(__git_find_on_cmdline "$subcommands save")";
    if [ -z "$subcommand" -a -n "$(__git_find_on_cmdline "-p")" ]; then
                if [ -z "$(__git_find_on_cmdline "$save_opts")" ]; then
                if [ -z "$(__git_find_on_cmdline "$save_opts")" ]; then
            if [ -n "$(__git_find_on_cmdline "--ignored")" ]; then
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
    local subcommand="$(__git_find_on_cmdline "$subcommands")";
            if [ -n "$(__git_find_on_cmdline "--orphan")" ]; then
            if [ -n "$(__git_find_on_cmdline "-c -C -d --detach")" ]; then
                if [ -n "$(__git_find_on_cmdline "--track")" ]; then
    subcommand="$(__git_find_on_cmdline --show-idx "$subcommands")";**

I don't see any named 'cmd'

And no aliases named 'cmd'.

So, I'm guessing it's a bug.

This does work in cygwin, btw:

**$ cmd /c dir**
 **Volume in drive C is OS**
 **Volume Serial Number is 52D3-3C90**

 **Directory of C:\Users\John**

**10/20/2020  04:22 PM    <DIR>          .**
**10/20/2020  04:22 PM    <DIR>          ..**
**09/29/2013  02:56 PM    <DIR>          .android**
**--etc--**

Not sure if this is a bug or a configuration issue on my side.

**Comment by dscho** [comment]
From our [Release Notes' "Known Issues" section](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
>
>  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
>
>  Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "`//usr/bin/bash.exe`".

Have you tried `cmd //c dir`?

**Comment by JohnPSYMQEPDFQ** [comment]
Yup,  that was the problem.   Sorry for the waste of time.   I looked at the open bug list, but forget to check for "known issues".

Thanks.

**Comment by dscho** [comment]
No worries! I'm glad there was no need to hunt an unknown bug.
