### ISSUE TITLE
Git 2.29.0: Problems with Git Credential Manager Core intermittently showing error message "Unhandled exception: System.ComponentModel.Win32Exception: Invalid windows handle" (was: and not storing credentials)

### ISSUE THREAD

**Issue by jnareb** [git-for-windows/git#2867]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.29.0.windows.1
cpu: x86_64
built from commit: add3cebdf89e93784955b34e1c1ffcba308b89cc
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows 10 Home 64-bit, version 1909, build 18363.1139

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1139]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The computer in question was not rebooted after upgrading Git for Windows from 2.28.

There are intermittent problems with my user account, where MS Windows looses the Microsoft account information; I need to go to settings, and click to fix it (providing PIN) - but those might be unrelated to the problem in question.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git push

Unhandled exception: System.ComponentModel.Win32Exception: Invalid windows handle
   w MS.Win32.ManagedWndProcTracker.HookUpDefWindowProc(IntPtr hwnd)
   w MS.Win32.ManagedWndProcTracker.OnAppDomainProcessExit()
   w MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 683 bytes | 683.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
To https://bitbucket.org/<user>/<repository>.git
   858e6af..05947f9  master -> master
```
Any Git command that requires password-based authentication, like syncing to remote Git repository via HTTPS protocol.

 - What did you expect to occur after running these commands?

I expected to have to provide username and password *once*, and for [Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core) ("GCM Core") to store credentials. Subsequent connections to the same repository should not require providing the password.

 - What actually happened instead?

Each time I got asked about credentials: username and password.

One time after providing credentials I got an error message, but the operation was anyway a success.

```
Unhandled exception: System.ComponentModel.Win32Exception: Invalid windows handle
   w MS.Win32.ManagedWndProcTracker.HookUpDefWindowProc(IntPtr hwnd)
   w MS.Win32.ManagedWndProcTracker.OnAppDomainProcessExit()
   w MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
```
Actually the first line is in the Polish locale (local language):
```
Wyj▒tek nieobs▒u▒ony: System.ComponentModel.Win32Exception: Nieprawid▒owe doj▒cie okna
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Any repository with HTTPS access that requires credentials.

I would be satisfied with an explanation how to go back to Git Credential Manager for Windows. It is unfortunate that it got deprecated because new Git Credential Manager Core does not look like is fully ready.

**Comment by derrickstolee** [comment]
@mjcheetham for awareness. This might need to be transferred to microsoft/git-credential-manager-core.

@jnareb: Have you tried going to Windows Credential Manager and deleting your old credential? If that helps you acquire a new credential, then that gives us a place to look for this issue (perhaps it is an issue with compatibility between GCM-Windows and GCM-Core.)

![image](https://user-images.githubusercontent.com/570044/96944253-5a7af180-14a8-11eb-83ca-e7501bd47000.png)

**Comment by jnareb** [comment]
OK, the Bitbucket credentials (for the repository I discovered this problem with) had credentials modification time to before time of upgrading Git (if I remember it correctly). I have removed both main credential and refresh token (for git, hg and sourcetree-rest - only the `git:` one was modified recently). ~Looking at password length it looks like they stored old password, either from before password change or from first try when I have entered the wrong password.~ (it always show 8 dots for password, my mistake).

Then I have run `git pull` twice, and was **twice** asked for credentials. I will try it again after rebooting (but not right now).

I have checked Windows Credential Manager again, and after those two `git pull`s it stores `git:https://bitbucket.org`, but for some reason not `git:https://bitbucket.org/refresh_token`.

**Comment by jnareb** [comment]
Below there is result of running `GIT_TRACE=1 git pull`, maybe it would help:

```
$ GIT_TRACE=1 git pull
10:16:11.809114 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:16:11.809114 git.c:444               trace: built-in: git pull
10:16:11.809114 run-command.c:663       trace: run_command: git fetch --update-head-ok
10:16:11.824737 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:11.824737 git.c:444               trace: built-in: git fetch --update-head-ok
10:16:11.824737 run-command.c:663       trace: run_command: GIT_DIR=.git git remote-https origin https://jnareb@bitbucket.org/<user>/<repo>.git
10:16:11.855991 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:11.855991 git.c:729               trace: exec: git-remote-https origin https://jnareb@bitbucket.org/<user>/<repo>.git
10:16:11.855991 run-command.c:663       trace: run_command: git-remote-https origin https://jnareb@bitbucket.org/<user>/<repo>.git
10:16:11.887237 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:16.739454 run-command.c:663       trace: run_command: 'git credential-manager-core get'
10:16:16.788621 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:16.788621 git.c:729               trace: exec: git-credential-manager-core get
10:16:16.788621 run-command.c:663       trace: run_command: git-credential-manager-core get
10:16:49.649568 run-command.c:663       trace: run_command: 'git credential-manager-core store'
10:16:49.704314 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:49.704314 git.c:729               trace: exec: git-credential-manager-core store
10:16:49.704314 run-command.c:663       trace: run_command: git-credential-manager-core store
10:16:50.016814 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
10:16:50.048070 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
10:16:50.048070 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:50.048070 git.c:444               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
10:16:50.079318 run-command.c:1617      run_processes_parallel: preparing to run up to 1 tasks
10:16:50.079318 run-command.c:1649      run_processes_parallel: done
10:16:50.079318 run-command.c:663       trace: run_command: git maintenance run --auto --no-quiet
10:16:50.094944 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:50.094944 git.c:444               trace: built-in: git maintenance run --auto --no-quiet
10:16:50.110564 run-command.c:663       trace: run_command: git merge FETCH_HEAD
10:16:50.110564 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:50.126202 git.c:444               trace: built-in: git merge FETCH_HEAD
Already up to date.
```

**Comment by jnareb** [comment]
I have just noticed **my mistake**, which might make first part of this issue / bug report irrelevant. I have switched to `credential.helper=manager`, ran `git pull`... and this time I have used the same username as embedded in HTTPS URL of the repository, using "jnareb" instead of email "jnareb@gmail.com" - both work with Atlassian login system. Second `git pull` didn't require credentials. (This added `git:https://jnareb@bitbucket.org` credential to Windows Credential Manager.)

Then I switched back `credential.helper=manager-core`, ran `git pull` once again, and didn't have to provide credentials either.

As a final check I have again deleted credentials in Windows Credential Manager, and with `credential.helper=manager-core` ran `git pull` twice... and had to provide credentials only once.

As the error message that I got once is something hopefully rare, I will be closing this bug report soon.

**Comment by dscho** [comment]
> This might need to be transferred to microsoft/git-credential-manager-core.

@derrickstolee [Sadly](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/transferring-an-issue-to-another-repository):

> [...] You can only transfer issues between repositories owned by the same user or organization account. [...]
