### ISSUE TITLE
Can't run rebaseall: Permission denied

### ISSUE THREAD

**Issue by insin** [git-for-windows/git#287]
After uninstalling my previous 1.9-preview version and installing 2.5.0 on 32 bit Windows 7 Enterprise, I encountered this while trying to run `git svn dcommit`:

```
$ git svn dcommit
      1 [main] perl 9256 child_info_fork::abort: unable to remap msys-svn_wc-1-0.dll to same address as parent (0x2910000) - try running rebaseall
```

t I'm familiar with dealing with it from Cygwin, but I'm unable to run `rebaseall` from an Administrator command prompt:

```
C:\Program Files\Git>usr\bin\dash.exe -c "usr/bin/rebaseall -p"
usr/bin/dash: 1: usr/bin/rebaseall: Permission denied
```

Any tips on how I can get around this?

**Comment by dscho** [comment]
Hmm. rebaseall is called as part of the installation process... Did you install via the installer or unpack the portable Git?

**Comment by dscho** [comment]
Regarding the failed command:

> ```
> C:\Program Files\Git>usr\bin\dash.exe -c "usr/bin/rebaseall -p"
> usr/bin/dash: 1: usr/bin/rebaseall: Permission denied
>```

Try `usr\bin\dash.exe -c 'usr/bin/dash usr/bin/rebaseall -p' instead.

**Comment by insin** [comment]
I used the installer.

Your alternative command worked, thanks!

**Comment by dscho** [comment]
Did it fix the `git svn` problem?

**Comment by insin** [comment]
That did the trick, thanks.
