### ISSUE TITLE
Broken ssh-copy-id after update to 2.29.1

### ISSUE THREAD

**Issue by mhoyer** [git-for-windows/git#2873]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

See https://github.com/git-for-windows/git/issues?q=is%3Aissue+ssh-copy-id

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```bash
$ git --version --build-options

git version 2.29.1.windows.1
cpu: x86_64
built from commit: e6d53c456169235fe72602e2b4d985934fa9ad23
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.1139]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```bash
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing special

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

The `bash` that comes with git-for-windows

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
$ ssh-copy-id server
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
/usr/bin/ssh-copy-id: line 251: warning: here-document at line 251 delimited by end-of-file (wanted `EOF')
/usr/bin/ssh-copy-id: line 250: warning: here-document at line 250 delimited by end-of-file (wanted `EOF')
/usr/bin/ssh-copy-id: line 254: /dev/null`: Permission denied
/usr/bin/ssh-copy-id: line 260: EOF: command not found
user@server's password:

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'server'"
and check to make sure that only the key(s) you wanted were added.

$ ssh server
user@server's password:        # should not ask here
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-122-generic x86_64)

Last login: Tue Oct 27 10:31:41 2020 from x.x.x.x
user@server:~$ ls -la | grep ssh
# No `~./ssh` folder created :-(
```
 - What did you expect to occur after running these commands?

That `ssh-copy-id` actually really copies the key (as stated in the output) and `ssh user@server` does not let me enter the password afterwards.

 - What actually happened instead?

Key not copied and password is still required.

**Comment by mhoyer** [comment]
I found the issue related to my problem: https://github.com/openssh/openssh-portable/pull/206/commits/66f16e5425eb881570e82bfef7baeac2e7accc0a

✔️ I locally fixed my `C:\Program Files\Git\usr\bin\ssh-copy-id` according to the patch above and it's working again.

**Comment by dscho** [comment]
> I found the issue related to my problem: [openssh/openssh-portable#206](https://github.com/openssh/openssh-portable/pull/206)
> 
> ✔️ I locally fixed my `C:\Program Files\Git\usr\bin\ssh-copy-id` according to the [patch above](https://github.com/openssh/openssh-portable/pull/206/commits/66f16e5425eb881570e82bfef7baeac2e7accc0a) and it's working again.

Excellent find! Would you mind porting this to our `MSYS2-packages` and opening a PR at https://github.com/git-for-windows/MSYS2-packages?
