### ISSUE TITLE
startup of git bash on win10 is extremely slow! ! !

### ISSUE THREAD

**Issue by twang284** [git-for-windows/git#2875]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

version 2.29.0.windows.1
cpu: i686
built from commit: add3cebdf89e93784955b34e1c1ffcba308b89cc
sizeof-long: 4
sizeof-size_t: 4
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.18362.1139] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** default **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** git bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** just startup git bash too too too slowly **
```
 - What did you expect to occur after running these commands?

** much faster **

 - What actually happened instead?

** startup too slow too slow
[bf15d46ba28072bcf1f082c17ac36b72.zip](https://github.com/git-for-windows/git/files/5463120/bf15d46ba28072bcf1f082c17ac36b72.zip)

 **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Maybe https://github.com/git-for-windows/git/wiki/Diagnosing-performance-issues#trace-executions-in-the-bash-startup helps you diagnose this in more detail?

**Comment by dscho** [comment]
> cpu: i686

Also, have you tried the 64-bit version?

**Comment by twang284** [comment]
> > cpu: i686
> 
> Also, have you tried the 64-bit version?

**Comment by twang284** [comment]
I add "set -x" in profile file, the startup process execute many many commands, see the record video in attachment.
[dcf70317767ac205d03bb047d5cc3527.zip](https://github.com/git-for-windows/git/files/5468418/dcf70317767ac205d03bb047d5cc3527.zip)

**Comment by dscho** [comment]
> I add "set -x" in profile file, the startup process execute many many commands, see the record video in attachment.
> [dcf70317767ac205d03bb047d5cc3527.zip](https://github.com/git-for-windows/git/files/5468418/dcf70317767ac205d03bb047d5cc3527.zip)
> 

I can't, not when reading on the phone. Is there really no way that you can investigate a bit further and distill your findings into a succinct comment in this ticket?

**Comment by PhilipOakley** [comment]
@twang284 also have a look at the wiki https://github.com/git-for-windows/git/wiki/Diagnosing-performance-issues for some pointers, even if it's just looking at the timings from the Trace command.
