### ISSUE TITLE
pack.packsizelimit cannot be unset

### ISSUE THREAD

**Issue by tacker66** [git-for-windows/git#288]
Steps to reproduce:

    git --version
    git config pack.packsizelimit
    git config --unset --global pack.packsizelimit
    git config --unset --system pack.packsizelimit
    git config --unset --local pack.packsizelimit
    git config pack.packsizelimit

Output:

    git version 2.5.0.windows.1
    2g
    2g

I use the 64bit version of Git-for-Windows on Win7 64bit.
This works with 2.5.0 on cygwin and worked with 1.9.5-preview20150319.

Seems to be related to #264.

Thomas

**Comment by dscho** [comment]
Please study https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines thoroughly and then augment the bug report accordingly.

**Comment by tacker66** [comment]
Sorry for the terse first version of this issue.

**Comment by dscho** [comment]
This version looks much better! And it points to a bug: the 64-bit version of Git should not set the 2g limit. FWIW it is set in `C:\ProgramData\Git\config` and is supposed to be a pretty hard limit that cannot be changed easily. But of course it only makes sense for 32-bit.

Now, we will of course want to lift this limit for all the 64-bit users who installed Git for Windows with that limit imposed. Let me see whether I can come up with an easy patch...

**Comment by dscho** [comment]
I have to leave for today. @tacker66 please feel free to follow the description in https://github.com/git-for-windows/git/wiki/Making-an-installer (except for checking out `build-extra`'s `2g-64-bit` branch) to test my proposed fix (I do not have time to do that today)!

**Comment by dscho** [comment]
Hmm. @tacker66 No feedback whatsoever? I worked hard on this, you know?

**Comment by tacker66** [comment]
Sorry, I had no possibility to build and create an installer yet. Now I tried to install the SDK but didn't succeed due to a weird proxy which gives my a 407. Any hints?

**Comment by dscho** [comment]
> Now I tried to install the SDK but didn't succeed due to a weird proxy which gives my a 407. Any hints?

Yep. Open a new issue and try to give as much context as possible. See https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines for inspiration.

**Comment by dscho** [comment]
For lurkers, @tacker66 reported this as https://github.com/git-for-windows/git/issues/309.

**Comment by dscho** [comment]
With #309 fixed, @tacker66 may I ask you to test my proposed fix?

**Comment by dscho** [comment]
@tacker66 please note that I wait for your feedback.

**Comment by tacker66** [comment]
I finally found some time to test your fix ...

With current master of src/git and your 2g-64-bit branch rebased on current master of src/build-extra I get the follwing error:

	Error on line 1361 in ...\git-sdk-64\usr\src\build-extra\installer\install.iss: Column 140: Invalid number of parameters.

where line 1361 is the third line of:

	#ifdef IS64
        FileName:=ExpandConstant('{tmp}')+'\packsize.txt';
        if not Exec(AppDir+'\{#MINGW_BITNESS}\bin\git.exe','config -f config pack.packsizelimit  > "'+FileName+'"',SW_HIDE,ewWaitUntilTerminated,i) then begin
            Msg:='Unable to read packsize limit';

BTW: Successfully creating an installer obviously requires to build also src/git/contrib/subtree. But this is not documented in the Wiki.

**Comment by dscho** [comment]
> Successfully creating an installer obviously requires to build also src/git/contrib/subtree.

No, this should not be needed. If it does, that is a bug. What it should do is pick up the contents of `mingw-w64-<arch>-git` which does include `subtree`.

**Comment by tacker66** [comment]
OK; the problem seems to be, that `make install-html` in src/git does a

	rm -f /mingw64/share/doc/git-doc/git-subtree.html

**Comment by dscho** [comment]
Is subtree a feature that is crucial to test my suggested fix? If not, could you investigate how to fix my fix so it compiles and actually works?
