### ISSUE TITLE
Feature Request: During interactive rebase allow commit-messages to be edited from the rebase control file

### ISSUE THREAD

**Issue by Brondahl** [git-for-windows/git#2881]
- [Y] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Feature Request, hence Machine Context is N/A

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Bash, with Notepad++ as editor.

### Details

When you do an interactive rebase, you are presented with a file listing all the commit hashes, their current message, and the command/operation to perform.

To edit the commit message you set operation `r` and then are later given the opportunity to set the message.

That file already has the commit hashes, so the message text in that file isn't being used to identify the message.
So can we allow the user to (optionally) set the message directly in the that file?

It would make the flow a lot quicker (don't have to open a new editor instance each time.), and would make it a lot easier to make similar changes to a bunch of commits (e.g. prefixing them all with Ticket number, or fixing a consistent typo in a bunch of commits.)

Indicator that the commit-rename should use the text in the control file (rather than the later editor prompt) could either be A) a new command (rename-inline, or similar) or B) existing rename command + "the text on this line is different from the text on the original commit".

**Comment by Brondahl** [comment]
Apologies if this functionality is part of git itself, not git-for-windows; I'm very unsure of where the boundaries of the 2 parts are.

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
