### ISSUE TITLE
Feature Request: During interactive rebase allow "fixdown" command, similar to "fixup"

### ISSUE THREAD

**Issue by Brondahl** [git-for-windows/git#2882]
- [Y] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Machine Setup not relevant to Feature Request.

The `f` = `fixup` command does a squash, but automatically retains the commit message from the first commit. To make it easy to say "oh, I missed that one thing", I assume.

Can we have a similar convenience-command that squashes, and retains the _second_ commit's message?

Am happy to suggest names and/or shorthand keys for it, if the idea is acceptable.

**Comment by Brondahl** [comment]
Apologies if this functionality is part of git itself, not git-for-windows; I'm very unsure of where the boundaries of the 2 parts are.

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
