### ISSUE TITLE
Utf-8 in gitk tags 

### ISSUE THREAD

**Issue by boscogh** [git-for-windows/git#2884]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.29.2.windows.1
cpu: x86_64
built from commit: cbf8e7474ba2529d5e7269d0cacab6b4e59579db
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.508]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I use utf-8 in console
$ cat ~/.bashrc
/c/WINDOWS/system32/chcp.com 65001
export LANG=ru_RU.UTF-8

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
gitk --all &

```
 - What did you expect to occur after running these commands?

I expect to see all commits in Russian to be displayed correctly, and also all tags and annotations to them are also correctly shown

 - What actually happened instead?

Commits are fine, I can see Russian letters as expected, but at the same time, all tags are displayed using Cp1251 (default windows encoding in Rusia), while actual text is in utf-8, so it's impossible to read it as it shown by gitk.

I believe this is an old / a long standing issue, I was just too lazy to describe it before, sorry for that.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Would you have any idea whether the same issue occurs on Linux in some form? Or maybe Tcl/Tk has to be told in a different way that the current encoding is `ru_RU.UTF-8`?

**Comment by boscogh** [comment]
it is hard to tell how it will behave in Linux, I'm not that fluent with gui apps and linux, and don't have them set up.
that I could tell is in the same gitk window, if I select commit or branch, it will be shown correctly in Russian/utf-8, but if I select tag, then it's try to display it using Cp1251/Windows-1251 codepage, ie default for windowed apps. So I guess it works a little bit different for commits and tags in terms of specifying the encoding

**Comment by dscho** [comment]
Maybe you could set up a minimal example repository, publish it on GitHub and then ask for assistance on [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently)?

**Comment by dscho** [comment]
Closing as stale.
