### ISSUE TITLE
"Could not resolve host" for company vpn host

### ISSUE THREAD

**Issue by cwansart** [git-for-windows/git#2885]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

git version 2.29.2.windows.1 64 bit

```
$ git --version --build-options

git version 2.29.2.windows.1
cpu: x86_64
built from commit: cbf8e7474ba2529d5e7269d0cacab6b4e59579db
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.610]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am using Cisco VPN client to connect. ~It seems that restarting Windows works.~ Nevermind, did not work this time.
Okay, what seems to work is to reconnect the wifi.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash and IntelliJ IDEA's git integration.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Any command that interacts with the server.
For example clone:

$ git clone https://company-tfs/project-name
Cloning into 'project-name'...
fatal: unable to access 'https://company-tfs/project-name': Could not resolve host: company-tfs

$ curl https://company-tfs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: company-tfs

Although it says it cannot resolve, using any browser works. Even git in WSL 2 works.
```
 - What did you expect to occur after running these commands?

Reaching the service.

 - What actually happened instead?

The remote commands were not able to be run.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Since it's in a vpn I cannot.

**Comment by dscho** [comment]
Does it work with `nslookup`? Can you try the clone again with `GIT_TRACE_CURL=1` and then see whether you find anything illuminating in the log?

**Comment by cwansart** [comment]
Currently it works again after reconnecting wifi. I'll test it as soon as this happens again.

**Comment by cwansart** [comment]
Okay, here is the output:
```
$ nslookup company-tfs
Non authorized response:
Server:  dns.company-tfs
Address:  10.10.10.10 (internal IP address is used here, I replaced it)

Name:    server.company-tfs
Address:  10.10.10.130 (internal IP i used here, I replaced it)
Aliases:  company-tfs


$ ping company-tfs
Ping request could not find host company-tfs. Please check the name and try again.
```

Running `git clone` with `GIT_TRACE_CURL=1` returned: 
```
$ GIT_TRACE_CURL=1 git clone https://company-tfs/project-name/
Cloning into 'project-name'...
08:00:08.304626 http.c:774              == Info: Couldn't find host company-tfs in the .netrc file; using defaults
08:00:08.306133 http.c:774              == Info: Could not resolve host: company-tfs
08:00:08.306133 http.c:774              == Info: Closing connection 0
fatal: unable to access 'https://company-tfs/project-name/': Could not resolve host: company-tfs
```

**Comment by dscho** [comment]
My _guess_ is that something goes wrong using a regular DNS lookup. Unfortunately, not even the [Everything Curl](https://ec.haxx.se/libcurl/libcurl-names) book has anything to say how to debug this. All I know is that cURL can optionally use the `c-ares` library for DNS lookups, but I don't think that Git for Windows' version does that.

Could you maybe see whether it has anything to do with IPv4 vs IPv6 (e.g. by calling `curl -4 <url>` and `curl -6 <url>` to see whether the former fails and the latter succeeds)?

**Comment by cwansart** [comment]
With curl 4, it is unable to get the local issuer whereas with curl 6 it is unable to resolve the host:

````
$ curl -4 https://company-tfs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Christian Wansart@cw MINGW64 ~
$ curl -6 https://company-tfs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: company-tfs

````

**Comment by dscho** [comment]
Ah, so it works with IPv4, still. And cURL prefers IPv6. A workaround might be to use `git clone -4 <...>`, then.

**Comment by cwansart** [comment]
This works! Interesting. Thank you. Now I have to find out how to tell my IntelliJ how to append the `-4` parameter. But thanks so far!

**Comment by dscho** [comment]
> Now I have to find out how to tell my IntelliJ how to append the `-4` parameter.

Or try to gently nudge [this patch](https://lore.kernel.org/git/20200915135428.GA28038@pflmari/) forward which implements support for `transfer.ipversion`, but which seems to be stalled for almost two months now. To offer your support, maybe you could reply to  [@peff's mail](https://lore.kernel.org/git/20200922050331.GB528837@coredump.intra.peff.net/) (no HTML! otherwise this will be dropped, instructions how to reply are [on the bottom](https://lore.kernel.org/git/20200922050331.GB528837@coredump.intra.peff.net/#R)) mentioning that you have a use case for this and would like it to move further.

Another possibility that _might_ work is to add `--ipv4` to your `~/.curlrc` (as mentioned in [this Gist](https://gist.github.com/ianhomer/b50bd81316f1e008608b)). If that file does not exist, you could initialize it like this:

```sh
echo --ipv4 >>~/.curlrc
```

**Comment by dscho** [comment]
Did that work? I'd like to close out this ticket, if possible.

**Comment by cwansart** [comment]
Yes, it did work. Thank you.
