### ISSUE TITLE
Bash (mintty) crash when font change

### ISSUE THREAD

**Issue by greenpeas** [git-for-windows/git#289]
When i click "Select..." button on Text->Font section, bash everytime crashed.
x32 bit only. Windows 10 Home x32.

**Comment by dscho** [comment]
Do you mean the `Text->Font` section when right-clicking on the windows icon and choosing *Options...*?

**Comment by greenpeas** [comment]
![image](https://cloud.githubusercontent.com/assets/3856344/9358243/a6fc26de-4693-11e5-9622-b6d273e50845.png)

**Comment by greenpeas** [comment]
How start it with debug mode? How do I get the error log?

**Comment by dscho** [comment]
> How start it with debug mode?

I think you will want to [install the Git SDK](https://git-for-windows.github.io/) first -- give it a while, it will download quite a bit of data and then build Git.

Once you have that, you have a GNU debugger and can start mintty with it (the bug is most likely happening in mintty, I suspect: you did not *quite* verify that you are speaking about mintty's window options, but the screenshot strongly indicates that):

```sh
gdb -args /usr/bin/mintty /usr/bin/bash --login -i
```

Once the debugger is up, use the `run` command to start the process, then trigger the crash. You can then obtain a stack trace with the `bt` command.

**Comment by greenpeas** [comment]
Yes, we are talking about mintty. I understood you. I'm afraid I have little time that would have install the SDK. But if I do, I'll be sure to let you know.

**Comment by dscho** [comment]
@greenpeas I cannot reproduce the crash with Windows Server R2012 R2, and neither with Windows 7, both 64-bit:
![font-selection-mintty](https://cloud.githubusercontent.com/assets/127790/9360324/e397b516-4695-11e5-98fe-84cbfcc04eed.png)
Maybe you are missing some fonts that mintty expects to be available?

**Comment by dscho** [comment]
I now also tried it with Windows 10 Education N 32-bit, and I get this:
![font-select-mintty-10](https://cloud.githubusercontent.com/assets/127790/9360960/7e76dafa-4699-11e5-8ff6-5bbb249b222f.png)
In other words, I cannot reproduce the crash...

Maybe it has something to do with locales?

**Comment by greenpeas** [comment]
I installed the SDK, but what to do next, I do not know.

**Comment by dscho** [comment]
> I installed the SDK, but what to do next, I do not know.

Quoting from [my earlier comment](https://github.com/git-for-windows/git/issues/289#issuecomment-132614408) ;-)


> Once you have that, you have a GNU debugger and can start mintty with it [...]:
> 
> `gdb -args /usr/bin/mintty /usr/bin/bash --login -i`
> 
> Once the debugger is up, use the run command to start the process, then trigger the crash. You can then obtain a stack trace with the bt command.

**Comment by greenpeas** [comment]
Exception: STATUS_ACCESS_VIOLATION at eip=685BEA77
eax=0034F006 ebx=00000000 ecx=00001904 edx=00000904 esi=0000006F edi=00000300
ebp=0024BBD8 esp=0024BBB4 program=C:\git-sdk-32\usr\bin\mintty.exe, pid 2192, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0024BBD8  685BEA77 (0034DF64, 000001AC, 00000419, 0000FFFF)
0024BC5C  685C4F0B (0286A528, 00000001, 00000001, 0286A528)
0024BCA4  685BE214 (0286A528, 0024BD68, 685BCC20, 0286A528)
0024BD68  685BCC39 (02862CC8, 0286A528, 00000000, 0286A528)
0024BD80  685BCB4C (02862CC8, 0286A528, 02862C60, 02862CC8)
0024BDA0  685BCAD7 (02862CC8, 0286A528, 0024BE28, 02862C60)
0024BDE4  685BC764 (0024BE28, 02865028, 0034DD18, 0034DE0C)
0024BE0C  685BC5E2 (00000001, 0034DD18, 0034DE0C, 00000000)
0024BE48  685C146D (00000000, 0034DD18, 0034DD18, 685C1294)
0024BF3C  685C136B (75A17398, 00000005, 0056FBD8, 00573688)
0024BF74  75A01E98 (0056FBD8, 0024C094, 0056FBD8, 0024C008)
0024BFA0  759EBC3C (00000000, 759EBA80, 0024C074, 2005F8C0)
0024C008  759EBA80 (0024C094, 2006F140, 00000020, 00650076)
0024C0E8  0040C020 (00000111, 0000040F, 00020882, 00000001)
0024C1F4  00401D9E (00401800, 00060842, 00000111, 0000040F)
0024C280  77944C7F (00060842, 00000111, 0000040F, 00020882)
End of stack trace (more stack frames may be present)

**Comment by dscho** [comment]
That looks different from `gdb` output... Have you tried running in `gdb` yet?

**Comment by dscho** [comment]
@greenpeas If this ticket is to go anywhere, I really need you to work with me. In particular, [as I asked](https://github.com/git-for-windows/git/issues/289#issuecomment-132614408) I would like to have a backtrace from the crash (which you can obtain by running `gdb -args /usr/bin/mintty /usr/bin/bash --login -i`, then issuing the `run` command, and when it stops due to the crash, calling `bt`).

**Comment by greenpeas** [comment]
Tell me how to run gdb on Windows.
C:\git-sdk-32\mingw32\bin\gdb.exe -args /usr/bin/mintty /usr/bin/bash --login -i
???

**Comment by greenpeas** [comment]
May be 
C:\git-sdk-32\mingw32\bin\gdb.exe -args "C:\Program Files\Git\git-bash.exe" /usr/bin/bash --login -i
What should be the sequence of actions?

**Comment by greenpeas** [comment]
If I do C:\git-sdk-32\mingw32\bin\gdb.exe -args "C:\git-sdk-32\usr\bin\mintty.exe" "C:\git-sdk-32\usr\bin\bash.exe" --login -i
then run C:\git-sdk-32\usr\bin\mintty.exe and set font settings. mintty.exe crashed and there is a new file mintty.exe.stackdump near mintty.exe

**Comment by greenpeas** [comment]
Exception: STATUS_ACCESS_VIOLATION at eip=69C3EA77
eax=00DEF00A ebx=00000000 ecx=00001904 edx=00000904 esi=0000006E edi=00000300
ebp=0024BCA8 esp=0024BC84 program=C:\git-sdk-32\usr\bin\mintty.exe, pid 5768, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0024BCA8  69C3EA77 (00DEDF5C, 000001AC, 00000419, 0000FFFF)
0024BD2C  69C44F0B (021CA528, 00000001, 00000001, 021CA528)
0024BD74  69C3E214 (021CA528, 0024BE38, 69C3CC20, 021CA528)
0024BE38  69C3CC39 (021C2CC8, 021CA528, 00000000, 021CA528)
0024BE50  69C3CB4C (021C2CC8, 021CA528, 021C2C60, 021C2CC8)
0024BE70  69C3CAD7 (021C2CC8, 021CA528, 0024BEF8, 021C2C60)
0024BEB4  69C3C764 (0024BEF8, 021C5028, 00DEDD10, 00DEDE04)
0024BEDC  69C3C5E2 (00000001, 00DEDD10, 00DEDE04, 00000000)
0024BF18  69C4146D (00000000, 00DEDD10, 00DEDD10, 69C41294)
0024C00C  69C4136B (75A17398, 00000005, 005463A8, 0054F930)
0024C044  75A01E98 (005463A8, 0024C164, 005463A8, 0024C0D8)
0024C070  759EBC3C (00000000, 759EBA80, 0024C144, 2005F458)
0024C0D8  759EBA80 (0024C164, 2006ECD8, 00000020, 00650076)
0024C1B8  0040C020 (00000111, 0000040F, 00050156, 00000001)
0024C2C4  00401D9E (00401800, 003507CC, 00000111, 0000040F)
0024C350  77944C7F (003507CC, 00000111, 0000040F, 00050156)
End of stack trace (more stack frames may be present)

**Comment by dscho** [comment]
> gdb -args /usr/bin/mintty /usr/bin/bash --login -i

This is how you should be able to start `gdb` (I mentioned that twice... :smiley:)...

**Comment by dscho** [comment]
So you got an unhelpful Windows exception again, that does not help me. Also: I have no idea (you probably want me to guess? :stuck_out_tongue_winking_eye:) when this happens, i.e. is it the mintty call? Is it gdb itself? Or Git CMD? No idea. And no, I won't guess... :smiley:

**Comment by dscho** [comment]
Did you type `run` *in the `gdb` session*?

**Comment by greenpeas** [comment]
![image](https://cloud.githubusercontent.com/assets/3856344/9519337/78b02814-4cc6-11e5-95f9-856ae0056877.png)

**Comment by dscho** [comment]
`run`

**Comment by greenpeas** [comment]
hmmm.....
![image](https://cloud.githubusercontent.com/assets/3856344/9519359/b5a23e7e-4cc6-11e5-9f79-36554d565a04.png)

**Comment by dscho** [comment]
Did you install from the installer or do you run portable Git?

**Comment by greenpeas** [comment]
from installer
my skype artyomov.antnon 
write to me on Skype

**Comment by dscho** [comment]
Sorry, I forgot the state of the affairs. Could you please record here whether mintty as included in MSys2 works? And the one in Cygwin?

**Comment by dscho** [comment]
@greenpeas ping.

**Comment by dscho** [comment]
ping.

**Comment by greenpeas** [comment]
pong

**Comment by dscho** [comment]
So what are the answers to my questions I asked 13 days ago, @greenpeas?

**Comment by greenpeas** [comment]
I already did not remember, but it seems MSys2  does not work either.

**Comment by dscho** [comment]
That is bad. Unfortunately, I cannot continue to pour hours on end into a ticket that affects but a single person. Unless you plan to work on this yourself, I will have to close this ticket as WONTFIX. Sorry.

**Comment by greenpeas** [comment]
Unfortunately now there is no free time, so let's close issue
