### ISSUE TITLE
Windows 2004 Container git fetch without depth will BSOD

### ISSUE THREAD

**Issue by luthermonson** [git-for-windows/git#2891]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64-bit, pulled from the releases

```
PS C:\Users\ContainerAdministrator\test> git --version --build-options
git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
us-west2 AMI: `Windows_Server-2004-English-Core-ContainersLatest-2020.10.14`

```
administrator@EC2AMAZ-CUG0GAU C:\Users\Administrator>ver

Microsoft Windows [Version 10.0.19041.572]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults? Downloaded from releases page.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing? This is functional in 1809/1903/1909, but 2004 gives us a BSOD

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

 - What did you expect to occur after running these commands?

Expected git to to fetch and checkout the repo at the appropriate tag.

 - What actually happened instead?

BSOD and Memory Dump

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing? 

https://github.com/drone/drone-git/blob/master/windows/clone-tag.ps1#L2-L13
This is the script the drone job is running to clone, if depth is passed this will fetch and be successful.

I need to explain a bit of what I'm seeing, it's very weird. We make containers for all windows builds 1809/1903/1909 and we're adding 2004 which is now causing this dmp and just for this one repo github.com/rancher/rancher. We have 5+ smaller repos working fine, but this larger one dies.

I understand if you can't really reproduce this which is is why I'm providing the attached dmp/bugcheck/logs. When we run this through our CI it dies every time during the git fetch until we set the depth to 1, then it succeeds. Not sure what the error will tell you but if you want me to test more things please tell me and I will happily try something as this breaks 100% of the time without depth being set.

Please see attached for 
* [container.log](https://github.com/git-for-windows/git/files/5497653/container.log) log from docker container running the git job with git trace and everything turned on, note this is truncated the rest of the output is 350mb+ of what looks like the contents of a pack file and then the logs stop
* [dump-debug.txt](https://github.com/git-for-windows/git/files/5497658/dump-debug.txt) (windbg !analyze -v of the dmp file from the server)
* [bugcheck.txt](https://github.com/git-for-windows/git/files/5497660/bugcheck.txt)
 bugcheck from `Get system logs` in aws console

**Comment by dscho** [comment]
Hmm. Is Git for Windows really the best place to report a Blue Screen of Death? There is no kernel code in Git for Windows, therefore it strikes me more like a bug in Windows and/or Docker that a simple `git fetch` can trigger this?

**Comment by luthermonson** [comment]
@dscho i don't disagree with you, it's the only insight i have. If you think I can put this elsewhere let me know where that might be. The errors all came from git.exe and I'm not really a windows debugger, doing the best I can here.

**Comment by dscho** [comment]
Shouldn't this be reported to the Windows engineering team, e.g. via https://community.windows.com/?

**Comment by luthermonson** [comment]
i will try these guys https://github.com/microsoft/windows-containers and see what happens. Thanks for your time.
