### ISSUE TITLE
Git 2.29.2 difftool no longer working

### ISSUE THREAD

**Issue by bit-bash** [git-for-windows/git#2893]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.657]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am trying to invoke BeyondCompare with git difftool -d HEAD~1
Section in ~/.gitconfig is:
```
[diff]
        tool = bc4
[difftool "bc4"]
        cmd = \"c:/program files/beyond compare 4/bcompare.exe\" \"$LOCAL\" \"$REMOTE\"

```
Note, this WORKS when I downgrade to git 2.28.0, and there are no other changes.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git difftool -d HEAD~1
```
 - What did you expect to occur after running these commands?

I expected BeyondCompare to launch, showing the differences between working dir and previous commit.

 - What actually happened instead?

There is a slight delay, then nothing happens and I'm back to the shell prompt.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Tried many different repo, I can reproduce on any of them.

I have reproduced this issue on two different Windows 10 systems.
Current workaround is to use git 2.28.0.

**Comment by dscho** [comment]
Have you looked whether the log produced with `GIT_TRACE` contains anything interesting?

**Comment by bit-bash** [comment]
> Have you looked whether the log produced with `GIT_TRACE` contains anything interesting?

I've installed 2.28.0, but when I get a chance, I'll re-install 2.29.2 and run again with GIT_TRACE.

**Comment by dscho** [comment]
> I've installed 2.28.0, but when I get a chance, I'll re-install 2.29.2

FWIW if you want to keep your v2.28.0 but just want to run the test I asked for with v2.29.2, you can install a Portable Git (which will not overwrite your existing installation).

**Comment by bit-bash** [comment]
Good suggestion!  Results are inconclusive - I can't see any smoking gun in the trace logs.

Installed 2.28.0 works with: git difftool -d HEAD~1
Portable (or previously installed 2.29.2) does not work with: git difftool -d HEAD~1

[trace2.28.0.txt](https://github.com/git-for-windows/git/files/5520667/trace2.28.0.txt)
[trace2.29.2.txt](https://github.com/git-for-windows/git/files/5520668/trace2.29.2.txt)

**Comment by dscho** [comment]
Okay, I _think_ I know what is going on: 83bbf9b92ea8a10a60f44369a200b39ce5db78cd, contributes via https://lore.kernel.org/git/20200729213113.15927-2-rogi@skylittlesystem.org/, broke it. Basically, it overrides the user setup because `bc4` and `bc` sound _so_ similar. My current working hypothesis is that this fixes it:

```diff
diff --git a/git-mergetool--lib.sh b/git-mergetool--lib.sh
index 2defef28cd93..7225abd81122 100644
--- a/git-mergetool--lib.sh
+++ b/git-mergetool--lib.sh
@@ -138,6 +138,10 @@ setup_user_tool () {
 	merge_cmd () {
 		( eval $merge_tool_cmd )
 	}
+
+	list_tool_variants () {
+		echo "$tool"
+	}
 }
 
 setup_tool () {
```

If you get a chance, would you mind making that change manually (by editing `/mingw64/libexec/git-core/git-mergetool--lib`, you might need administrator privileges, adding the `list_tool_variants ()` definition at the end of the `setup_user_tool ()` function)?

I will try to get this patch into a mergeable and submittable form in the meantime.

**Comment by bit-bash** [comment]
> If you get a chance, would you mind making that change manually (by editing `/mingw64/libexec/git-core/git-mergetool--lib`, you might need administrator privileges, adding the `list_tool_variants ()` definition at the end of the `setup_user_tool ()` function)?
I made the edit (using portable git) and I can confirm this fixes the issue!  Yay!

**Comment by dscho** [comment]
Good, thanks for testing!

**Comment by dscho** [comment]
@bit-bash if you want to run a fixed version, please install the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).
