### ISSUE TITLE
Git bash limited to 32 windows

### ISSUE THREAD

**Issue by Its-Just-Nans** [git-for-windows/git#2900]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.18363.1198]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**No I try on others computers too**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Bash Git**

### Problem
I wanted to know if this is normal and wanted, if git bash is limited
to 32 windows at the same time.
In theory this is not a problem, it is normal that there are limits
but why there are no explicit error messages.

For example, when I use git bash in Visual Code Studio, it produces
output error '256' but no message like 'Too many Git bash at one
time'.
If we do it from a terminal, we get no message.

From a certain point of view, we can say that it is normal if there is
no error because we could say 'who runs 64 git bash and does not
realize it?'.But in some cases, for example in Visual Code Studio,
there is only a small number that shows how many git bashs are
running.

Here is Visual Code's response to this problem:
https://github.com/microsoft/vscode/issues/109982

If you want to give it a try, here's a command that may come in handy:

```
for((i=1;i<=32;i++)); do start ./git-bash.exe; done
//Now start a new git bash an it will crash
```

**Comment by dscho** [comment]
> git bash is limited
> to 32 windows at the same time.

Do you see the same problem when calling [Cygwin](https://cygwin.com)'s MinTTY 33 times?

**Comment by Its-Just-Nans** [comment]
I don't know what is Cygwin's. I just dowloaded GIT for windows and install the terminal porposed during the installation.

And recently, I discovered this bug with Visual Sutido Code

If you want here is the file produced by Visual  Studio Code  (or bash.exe,  I don't know) :
```
bash.exe.stackdump
```

```
Stack trace:
Frame        Function    Args
00800000010  0018006401E (001802839A0, 0018026EFD1, 00000000058, 000FFFFB730)
00800000010  0018004973A (00180000000, 00100000000, 00000000000, 00000000001)
00800000010  00180049772 (00000000000, 00000000000, 00000000058, 00180353A80)
00800000010  00180070FE9 (001800D6FDE, 000FFFFC800, 0000000000B, 00000000000)
00800000010  001800712A0 (00000000003, 000FFFFC920, 00180045BCF, 000FFFFC920)
00800000010  00180072AB9 (000FFFFC920, 00180271795, 001801004A7, 0000000000D)
00800000010  0018005B2A3 (000FFFF0000, 00000000000, 00000000000, 008FFFFFFFF)
00800000010  0018005C655 (00000000002, 00180353400, 00000000000, 00000030201)
00800000010  0018005CB3F (000FFFFCCE0, 00800071C10, 000FFFFCC70, 000FFFFCC70)
000FFFFCBEC  0018005CF06 (0000000002F, 000FFFFCDF0, 00000000030, 00000000000)
000FFFFCCE0  00180049EE8 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

**Comment by dscho** [comment]
It would be good if you could invest a bit more time investigating both issues. The 32 window limitation might be a Cygwin one that we inherit via MSYS2.

The stack dump does not provide enough information; it needs an MCVE (https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by landstander668** [comment]
My guess is that there's some sort of resource limit being reached. I tried opening 40 incarnations of Git Bash with GfW version 2.29.2.windows.3 64-bit, and ended up with 38 windows to exit. So 2 attempts failed for some reason, but we made it well past 32 before that point.

For reference, here's the quick & dirty CMD.exe commands I used for the test.

```
cd /d "C:\Program Files\Git"
FOR /L %i IN (1,1,40) DO (
  start git-bash
)
```

I didn't get any error messages from the CMD window, nor did I see anything listed in Event Viewer. So no idea what the limiting factor actually was.

**Comment by Its-Just-Nans** [comment]
Yes it's a limit with MinTTY I think :

I did some tests and that appened when I start C:/Program Files/Git/bin/bash.exe
[Images](https://postimg.cc/3W0Hy2V9)

**Comment by dscho** [comment]
@Its-Just-Nans you may want to paste text as text instead of as a screenshot. And probably do a web search for that error message.

**Comment by Its-Just-Nans** [comment]
@dscho 
- I took an images because this messages appears during some fractions of seconds
- Yes you can see some results for this message `fatal error console device allocatoion failure` (but no real explanations). Here some results  :
> - https://stackoverflow.com/questions/60343796/mycode-exe-fatal-error-console-device-allocation-> failure-too-many-conso
> - https://stackoverflow.com/questions/53974197/vs-code-opens-a-new-debug-console-every-time-i-> build-run

**Comment by dscho** [comment]
I actually expected at least _some_ results pointing to Cygwin...

**Comment by Its-Just-Nans** [comment]
Actually, the first result point to Cygwin, because he use an Cygwin Compiler :slightly_smiling_face:

**C:\cygwin64\bin\g++.exe**

https://stackoverflow.com/questions/60343796/mycode-exe-fatal-error-console-device-allocation-failure-too-many-conso
