### ISSUE TITLE
nano editor ctrl and arrow keys don't working when editing merge message

### ISSUE THREAD

**Issue by BIMartingo** [git-for-windows/git#2905]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
$ git --version --build-options
git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh


 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [Version 10.0.15063]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
file not found 

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
The issue did not exist on previous version 
git version 2.28.0.rc1.windows.1
cpu: x86_64
built from commit: 25517c96553c05979b0697eb8d627f9420c48022

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Mintty terminal with bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
nano

 - What did you expect to occur after running these commands?

** insert here **
be able to edit the file

 - What actually happened instead?

** insert here **
the keyboard acted strangely, could not use ctrl-keys or arrow keys. Had to Kill entire Mintty session.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
I tried to reproduce, but <kbd>Ctrl</kbd><kbd>←</kbd> jumps word-wise, as I would have expected.

**Comment by BIMartingo** [comment]
Sorry, you are right. I've reviewed my steps and clearly The issue happens
when nano is called by git commit or git merge without the -m parameter.
That means when git calls the nano editor for editing the commit message.

All ^- commands do not work and the ctrl-arrows work as normal arrows in
this case.

Actually, when I press ctrl-z I get a sigpacket:: process: suppressing
signal 18 to win32 process.

Should correct or register this issue again?


Johannes Schindelin <notifications@github.com> schrieb am Fr., 20. Nov.
2020, 12:59:

**Comment by BIMartingo** [comment]
Ths issue doesn't occur with version 2.28.0.rcl.windows.1



Martin Goebbels <bi.martingo@gmail.com> schrieb am Fr., 20. Nov. 2020,
13:42:

**Comment by dscho** [comment]
> Sorry, you are right.

I don't understand. Here, you say that I am right, but then...

> I've reviewed my steps and clearly The issue happens when nano is called by git commit or git merge without the -m parameter. [...]
>
> All ^- commands do not work and the ctrl-arrows work as normal arrows in this case.

... you continue by directly contradicting that statement. For me, Ctrl+Arrow works _by jumping word-wise_. I.e. _not_ as normal arrows.

So my statement stands, I cannot reproduce the reported behavior.

**Comment by BIMartingo** [comment]
Sorry, was my mistake. I created a new folder for the 2.29 version and copied the configuration files from the old folder. So git core editor was still pointing to the old portable version. After fixing this, everything is working fine, what this issue is concerned.
with issue:
```
$ git config --global --get core.editor
C:/Users/Public/app/PortableGit-2/usr/bin/nano`
```
after correcting the config file, issue was gone
```
$ git config --global --get core.editor
C:/Users/Public/app/PortableGit-3/usr/bin/nano
```

**Comment by dscho** [comment]
Why not simply set `core.editor=nano`?

**Comment by BIMartingo** [comment]
Thanks for the suggestion. Clearly the right and best option.

Johannes Schindelin <notifications@github.com> schrieb am Fr., 27. Nov.
2020, 18:10:
