### ISSUE TITLE
Let the installer detect available editors and give the user a choice between them

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#291]
Windows users are more used to GUI tools than command-line tools, and vim falls safely into the latter category. It was even suggested as a perfect source of entropy to sit unsuspecting in front of vim and ask them to quit the editor.

On Windows, there are lovely choices of editors available that can be instead, e.g. Notepad++, Sublime Text, Atom, etc. Let's detect their presence and offer to configure them as default editor in Git's installer.

We could also try to make `notepad.exe` work, of course, or even `wordpad.exe` and offer them as alternative choices.

And we could bundle @patthoyts' [`notepad.tcl`](https://github.com/dscho/notepad.tcl/) (but only after addressing [this issue](https://github.com/dscho/notepad.tcl/issues/2), of course).

**Comment by fourpastmidnight** [comment]
@dscho I thought about this, too, and share the same sentiment. This was on my radar for in the future--but before this is tackled, I want to finish #682 and #462.

**Comment by whoisj** [comment]
:+1: this would be a lovely feature :smile:

**Comment by jrood** [comment]
+1

**Comment by dscho** [comment]
Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of comments, unless you are really adding a real comment. Thanks.
