### ISSUE TITLE
[2.29.2] fetch from repo on github -> git: 'maintenance' is not a git command. See 'git --help' 

### ISSUE THREAD

**Issue by dpap** [git-for-windows/git#2910]
- [  ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
$ cmd.exe /c ver

Windows 8.1
Microsoft Windows [Version 6.3.9600]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

- Details

  Was already signed in to githun when when Git Credential Manager redirected me to browser 
  Deleted old credentials for github in Windows Credentials

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch origin master
From https://github.com/dpap/FitnessRecorder
 * branch            master     -> FETCH_HEAD
git: 'maintenance' is not a git command. See 'git --help'.
```

 - What did you expect to occur after running these commands?

To fetch project without "git: 'maintenance' is not a git command" error

 - What actually happened instead?
Message after fetch from github repo 
```
git: 'maintenance' is not a git command. See 'git --help'.
```
Message not output when syncing from other git servers. 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I tried on a private and a public repo 
public repo 
https://github.com/dpap/FitnessRecorder

**Comment by dscho** [comment]
Is it possible that you had/have [Scalar](https://github.com/microsoft/Scalar#what-is-scalar) installed? The `maintenance` command is indeed not (yet) in Git for Windows.

**Comment by derrickstolee** [comment]
There _is_ a maintenance builtin in 2.29.2, but it does very little. One thing it _does_ do is [run `git maintenance run --task=gc` instead of `git gc --auto`](https://github.com/git/git/commit/a95ce124305adcc4980241b8877e06db1d6ed411#diff-481b97787e26e351309fb51deeab50081d90ed19155d21eea385aa97285dd341).

What is likely happening here is that you have a `PATH` problem and the `git fetch` command is shelling out to an older version of Git!

Let's try running the same test, but as follows (in Git bash):

```ShellSession
$ GIT_TRACE2_PERF="$(pwd)/log.txt" git fetch origin master
$ cat log.txt
```

In `log.txt`, you'll be looking for lines with columns "version" or "start", such as these in my logs:

```
$ grep -F "version" log.txt
08:20:58.655924 common-main.c:48             | d0 | main                     | version      |     |           |           |              | 2.29.0.vfs.0.0.36.g3abff69
08:20:58.729922 common-main.c:48             | d1 | main                     | version      |     |           |           |              | 2.29.0.vfs.0.0.36.g3abff69
08:20:58.913922 common-main.c:48             | d2 | main                     | version      |     |           |           |              | 2.29.0.vfs.0.0.36.g3abff69
08:21:05.220797 common-main.c:48             | d1 | main                     | version      |     |           |           |              | 2.29.0.vfs.0.0.36.g3abff69
08:21:05.403599 common-main.c:48             | d1 | main                     | version      |     |           |           |              | 2.29.0.vfs.0.0.36.g3abff69
08:21:07.625888 read-cache.c:2288            | d0 | main                     | data         | r1  |  8.982837 |  0.000666 | index        | ..read/version:2

/c/_git/git (maintenance/macOS)
$ grep -F "start" log.txt
08:20:58.656924 common-main.c:49             | d0 | main                     | start        |     |  0.013729 |           |              | 'C:\Program Files\Git\mingw64\bin\git.exe' fetch origin master
08:20:58.688921 run-command.c:736            | d0 | main                     | child_start  |     |  0.046119 |           |              | ..[ch0] class:remote-https argv:[git remote-https origin https://github.com/gitster/git]
08:20:58.729922 common-main.c:49             | d1 | main                     | start        |     |  0.019537 |           |              | git remote-https origin https://github.com/gitster/git
08:20:58.756925 run-command.c:736            | d1 | main                     | child_start  |     |  0.046574 |           |              | [ch0] class:dashed argv:[git-remote-https origin https://github.com/gitster/git]
08:20:58.914921 common-main.c:49             | d2 | main                     | start        |     |  0.030658 |           |              | git-remote-https origin https://github.com/gitster/git
08:21:05.166488 run-command.c:736            | d0 | main                     | child_start  |     |  6.523265 |           |              | ..[ch1] class:? argv:[git index-pack --stdin -v --fix-thin '--keep=fetch-pack 14960 on stolee-desk2' --pack_header=2,74]
08:21:05.221796 common-main.c:49             | d1 | main                     | start        |     |  0.013658 |           |              | git index-pack --stdin -v --fix-thin '--keep=fetch-pack 14960 on stolee-desk2' --pack_header=2,74
08:21:05.371957 run-command.c:736            | d0 | main                     | child_start  |     |  6.729444 |           |              | ..[ch2] class:? argv:[git rev-list --objects --stdin --not --all --quiet --alternate-refs]
08:21:05.404601 common-main.c:49             | d1 | main                     | start        |     |  0.010605 |           |              | git rev-list --objects --stdin --not --all --quiet --alternate-refs
```

**Comment by dpap** [comment]
Οκ. 

@derrickstolee you were right. The version lines contained the previous version (2.26.2)

Did a reboot and everything ok 

Had to do the reinstall in a rush (github changed their credential policy on the 13th Nov 2020) and I couldn't login
The installer explicitly told me to reboot but this is the first time I have needed to reboot after more the 4 years of using Git for Windows. Keep up the good work.
