### ISSUE TITLE
connect.exe missing from build 2.5.0

### ISSUE THREAD

**Issue by lourdas** [git-for-windows/git#293]
Before the official 2.5.0 release, I used `connect.exe` in my `.ssh/config` file to connect through a http proxy to push and pull from remote hosts. Now, after I installed the latest version, I see that `connect.exe` is missing from this build. How am I going to be able to push and pull behind a http proxy in this version?

**Comment by dscho** [comment]
Thank you for your report. Indeed, we shipped `connect.exe` with Git for Windows 1.x, I had completely forgotten about that. Let me see...

**Comment by lourdas** [comment]
Since I need connect.exe for my corporate workstation, do you think you could provide the exe somewhere to download it or would it take much more than that and require a minor release update that includes it? Or perhaps could I use the one from the 1.x branch?

**Comment by dscho** [comment]
So the proper way to support this is to make a mingw-w64-connect package in `/usr/src/MINGW-packages` (after initializing it with `(cd /usr/src/MINGW-packages && git fetch origin && git checkout master)`). I found that the source code for connect.c is maintained in https://bitbucket.com/gotoh/connect. You would need to craft a `PKGBUILD` file to match similar ones in the other subdirectories.

**Comment by lourdas** [comment]
I see. It does not seem easy to me. I will probably have to install the previous version until a new release comes out. Thanks.

**Comment by dscho** [comment]
@lourdas or get involved, like a good Open Source citizen ;-)

**Comment by nalla** [comment]
Workaround: get the exe from the old msysgit env: https://github.com/msysgit/msysgit/raw/master/mingw/bin/connect.exe

**Comment by lourdas** [comment]
@nalla Your suggestion to use connect.exe from the old branch worked like a charm. Thank you!
