### ISSUE TITLE
exception by libre-core pull

### ISSUE THREAD

**Issue by rhaberecht** [git-for-windows/git#2931]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

 igit version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4 
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.630]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

C:\Program Files\Git\etc\install-options.txt
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

have make pull in the libre-core folder per right-click   
![grafik](https://user-images.githubusercontent.com/75733563/101631334-7882be00-3a24-11eb-94bf-14260dee8d56.png)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
pull libre-core
```
 - What did you expect to occur after running these commands?

meldung warning: failed to restrict file handles (2)

handle #0: 000000000000014c (type 2, handle info (1) 0
handle #1: 0000000000000130 (type 3, handle info (1) 1
handle #2: 0000000000000648 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn .git/hooks/post-merge: No such file or directory

 - What actually happened instead?

these exception cames but it is Success   

But when ic build it in cygwin it cames:

checking for active Antivirus software... not found
configure: setting up the build environment variables...
configure: creating ./config.status
.in'ig.status: error: cannot find input file: `config_host.mk
Error running configure at /cygdrive/c/sources/libo-core/autogen.sh line 316.

i do not have the config_host.mk in my libre-core folder. Can you help me?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> warning: failed to restrict file handles (2)

This will most likely be fixed via an upgrade to a current Git for Windows (v2.29.2(3) was released yesterday, and you will want to upgrade to that because it fixes a critical CVE).

> But when ic build it in cygwin it cames:
> 
> checking for active Antivirus software... not found
> configure: setting up the build environment variables...
> configure: creating ./config.status
> .in'ig.status: error: cannot find input file: `config_host.mk
> Error running configure at /cygdrive/c/sources/libo-core/autogen.sh line 316.

This is a problem that is unrelated to Git for Windows. If I were you, I would try to find the right channels in the libo-core project to ask for help (I don't know that project or I would route you).

**Comment by rhaberecht** [comment]
i have updated git, but it cames 

72 files changed, 647 insertions(+), 308 deletions(-)
create mode 100644 sc/qa/unit/data/xlsx/tdf138741_externalLinkSkipUnusedsCrash.xlsx
create mode 100644 starmath/source/xparsmlbase.cxx
create mode 100644 starmath/source/xparsmlbase.hxx
create mode 100644 sw/qa/uitest/data/hiddenRow.ods
create mode 100644 sw/qa/uitest/table/sheetToTable.py
error: cannot spawn .git/hooks/post-merge: No such file or directory

Success (10032 ms @ 10.12.2020 10:27:23)

What must I do?

**Comment by dscho** [comment]
But that is yet a *different* issue! The hook message means that you somehow managed to install a `post-merge` hook into your `.git\hooks` folder that does not work. Git for Windows does not do that, so either you did it, or some program you called. Potentially the `libo-core` build system. Have you contacted that project for help yet?
