### ISSUE TITLE
Intermittent errors with big merge on samba network share

### ISSUE THREAD

**Issue by krskrs** [git-for-windows/git#2935]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I understand this is, most likely, not properly an issue, however I have no clues on what I can do to debug it, and I hope you could give me some hints to further investigate in some direction.

We use a repository (git running on windows10) on a samba share mounted on a centos 7 machine.

Overall everything was working but lately we had to do a big merge, and we found out it's randomly failing, with messages like the ones below. 

I think it's due to some races/synch/performance(?) issues with samba, but is there anything I can do about it? On multiple executions of the same command, it can work, or fail with almost the same error messages on random files/folders. 

Do such errors tell anything to you? For example the last one, which doesn't happen always, says: Function not implemented, while the most common ones are unable to unlink.. No such file or directory.

Thank you in advance for any insights you might provide.

```
git merge nlu
error: unable to unlink old 'branch_id': No such file or directory
error: unable to create file js/vendor/codemirror-5.58.1/addon/comment/comment.js: No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/comment/continuecomment.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/fold/brace-fold.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/fold/comment-fold.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/fold/foldcode.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/fold/foldgutter.css': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/fold/foldgutter.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/fold/indent-fold.js': No such file or directory
error: unable to create file js/vendor/codemirror-5.58.1/addon/fold/markdown-fold.js: No such file or directory
error: unable to create file js/vendor/codemirror-5.58.1/addon/fold/xml-fold.js: No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/merge/merge.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/search/match-highlighter.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/search/matchesonscrollbar.css': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/search/matchesonscrollbar.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/addon/search/search.js': No such file or directory
error: unable to unlink old 'js/vendor/codemirror-5.58.1/mode/htmlembedded/index.html': No such file or directory
error: unable to unlink old 'js/vendor/jquery-3.5.1.slim.js': No such file or directory
error: unable to unlink old 'ssslim-app/libraries/BillingProviders/BillingProviderFactory.php': No such file or directory
fatal: cannot opendir 'ssslim-app/libraries/BillingProviders/PayPalBillingProvider.php': Function not implemented
```

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git --version --build-options
git version 2.29.2.windows.3
cpu: x86_64
built from commit: d054eb1fc46ff23e7c95756a7c747e2f2864b478
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Versione 10.0.19042.630]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

**Comment by dscho** [comment]
If I were you, I would try to crank up the debug level of Samba and look for  tell-tale there.

Since this might not even be a bug in Git for Windows, shall we convert this ticket to a discussion?

**Comment by krskrs** [comment]
Hi @dscho ,
after further investigating and analyzing the issue with Process Monitor, I was able to nail down the issue to a Samba caching mechanism which can interfere with GIT for operations requiring an high number of consecutive file system operations.

You can find more information on this cache in this SO post: https://stackoverflow.com/a/9935126/1886048, and here https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/ff686200(v=ws.10)#details . Although the Microsoft article refers to older versions of Windows, it's still valid for the latest Windows 10 version.

I'm updating this issue in the hope it will be useful to others encountering the same problem, or maybe if you'd like to add it to some wiki/faqs, etc. or even look into further the issue to see if it could be patched/mitigated in Git for windows itself. 

Feel free to ask if you need any further info.

**Comment by dscho** [comment]
@krskrs do you think there is anything Git for Windows can do to work around this? I suspect not, in which case I would like to convert this issue to a discussion (because it is not a bug in Git for Windows, then).

**Comment by krskrs** [comment]
Hi @dscho apologies for the late reply. So, I don't know if this issue can be in some way prevented with a git for windows specific patch (like seeing if there's a way to disable that caching behavior at the application level and implementing a git switch/configuration option), and  I'm not even sure if you'd be interested into looking into it. Let's say that, first, I just wanted to raise the discussion, because this is a quite nasty issue, but with a relatively simple solution, and it looks like there's no clear information about it on internet. So I will leave it up to you how you'd like to proceed. And if I can be of some help by providing further details on the issue, on how to reproduce, or on how to fix it by disabling specific SAMBA caches, etc. I'm available.

**Comment by dscho** [comment]
@krskrs thanks! For now, I'd like to leave things as-are. If anybody else experiences the same issue, at least they can now find this ticket with helpful information, and we could then potentially still consider trying to think of ways to help users more directly.
