### ISSUE TITLE
be identified as 

### ISSUE THREAD

**Issue by fengshenme** [git-for-windows/git#2939]
C:\Program Files\Git\usr\share\vim\vim82\tools\shtags.pl Identify as a Trojan horse

**Comment by fengshenme** [comment]
git version 2.29.2.windows.2

**Comment by dscho** [comment]
> Identify as a Trojan horse

By who.

Please spend the time and effort to craft a high-quality report.

Also, have you actually looked at the contents? See https://github.com/git-for-windows/git-sdk-64/blob/HEAD/usr/share/vim/vim82/tools/shtags.pl for yourself.

**Comment by chrisbra** [comment]
Note: neither https://github.com/git-for-windows/git-sdk-64/blob/HEAD/usr/share/vim/vim82/tools/shtags.pl nor the upstream https://github.com/vim/vim/blob/HEAD/runtime/tools/shtags.pl has been detected as a virus by virustotal:
- [git results](https://www.virustotal.com/gui/url/0ecaa405c143f6232b8849e1ab9b28a842c1b7ec0b7b5c0e595e15747b33e2bb/detection)
- [vim results](https://www.virustotal.com/gui/url/28fb89d7645c8d88afcd1e3450e458f1d2a66a46c70901bf4f61d50982923d18/detection)

(file should be the same in both instances)

**Comment by dscho** [comment]
@chrisbra thanks. I think it is safe to close this.
