### ISSUE TITLE
git.exe causes a command-line window to flash on the screen when it is launched

### ISSUE THREAD

**Issue by mmcintyre123** [git-for-windows/git#294]
This appears to be the same issue as in the old version, reported in https://github.com/msysgit/git/issues/316

Problem:
Running git.exe causes a command-line window to flash on the screen (open then immediately close) when it is launched.  It can be very annoying as the (very useful) package GitGutter calls git.exe (I think to run git diff), so every time I save a file in Sublime Text 3 a command line window (with title C:\Program Files\Git\bin\git.exe) flashes on the screen.  Sometimes for unknown reasons (perhaps when saving very large files or working on a lot of files over the course of the day....) it gets slower, which makes it harder to work.
     
Environment/Setup:
Windows 7 using Git 2.5.0, Sublime Text 3.  In my user PATH I have C:\Program Files\Git\bin, which is the only git-related directory in my PATH.  During installation I configured Git commands to be available globally on my system, so they are also available in the normal windows command prompt.  
  
Note -- I also use ST3 with GitGutter in Ubuntu and this isn't happening there.
  
Expected behavior: 
Running git.exe should not open a separate command-line window.  
  
I've also reported this on jisaacks/GitGutter#246
  
Any possible fix to this would be much appreciated!

**Comment by mmcintyre123** [comment]
By the way, does it matter that I installed git from 
https://git-scm.com/downloads
and not
http://git-for-windows.github.io/?

**Comment by linquize** [comment]
They point to the same link on github

**Comment by mmcintyre123** [comment]
Well... it looks to me like they point to different links:
https://git-scm.com/download/win
vs
https://github.com/git-for-windows/git/releases/latest

My hunch is there's no difference - although, the second seems more legit... Unfortunately I came across the former first though so unless they're different I'm staying put.

**Comment by dscho** [comment]
The git-scm page redirects to the releases page. So @linquize was correct: they both download from exactly the same URL.

**Comment by dscho** [comment]
@mmcintyre123 `git.exe` is a console program, so it is correct to show the console by default. If you want to suppress that, I think you have to tell `CreateProcess()` that you do not want to see a console. See [my comment in the `GitGutter` issue tracker](https://github.com/jisaacks/GitGutter/issues/246#issuecomment-133104301).

**Comment by dscho** [comment]
Moving to https://github.com/jisaacks/GitGutter/issues/246.
