### ISSUE TITLE
installers named backwards for at least the 2.5.0 and 2.4.6 

### ISSUE THREAD

**Issue by torrey1028** [git-for-windows/git#295]
The download marked 64 bit installer installs Git into C:\Program Files and the one marked 32 bit installs Git in C:\Program FIles (x86). Didn't check if PortableGit downloads are the same way

**Comment by linquize** [comment]
This is the convention of 64-bit and 32-bit installation locations on Win64.

**Comment by torrey1028** [comment]
Apologies, I had that backwards
