### ISSUE TITLE
Git opens Vim in Unix mode instead of DOS mode in Windows

### ISSUE THREAD

**Issue by Skaytacium** [git-for-windows/git#2962]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.30.0.windows.1
cpu: x86_64
built from commit: 18da6dbba950f8cc7b7d07057f7c30bf7cf207b6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows (20H2) [Version 10.0.19042.685] 64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using Windows Terminal 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** PowerShell with oh-my-posh v3 **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config -e
```
 - What did you expect to occur after running these commands?

I expected it to open Vim in DOS mode
![image](https://user-images.githubusercontent.com/58383260/103362429-7968b600-4adf-11eb-87da-835684292044.png)

 - What actually happened instead?

It opened Vim in Unix mode
![image](https://user-images.githubusercontent.com/58383260/103362747-8f767680-4adf-11eb-85ee-97a748dceee0.png)
This resulted in my plugins not working and Vim giving me errors and wrong paths when I ran `:scriptnames` inside vim

**Comment by chrisbra** [comment]
This just shows the filetype of the currently edited file, which I think should be okay.
Can you please clarify what problems you are exactly facing with vim? plugins should always be working in Unix line ending mode, while dos style line endings may cause problems when sourcing those files with a linux Vim.

**Comment by Skaytacium** [comment]
Oh, I thought that was the mode that Vim is in.

The problem isn't with the Vim plugins or the line endings, the problem is that because Vim opens up in Unix mode instead of DOS mode, it messes up the position of the `.vimrc` file, therefore causing problems with plugins and customizations and so on.

When I run `:scriptnames` after launching Vim normally, I get the following: 
```
  1: ~\.vimrc
  2: ~\vimfiles\autoload\plug.vim
  3: C:\Program Files (x86)\Vim\vim82\filetype.vim
  4: ~\.vim\plugged\tern_for_vim\ftdetect\tern.vim
  5: ~\.vim\plugged\vim-fugitive\ftdetect\fugitive.vim
  6: C:\Program Files (x86)\Vim\vim82\ftplugin.vim
  7: C:\Program Files (x86)\Vim\vim82\indent.vim
  8: C:\Program Files (x86)\Vim\vim82\syntax\syntax.vim
  9: C:\Program Files (x86)\Vim\vim82\syntax\synload.vim
 10: C:\Program Files (x86)\Vim\vim82\syntax\syncolor.vim
...
```
But when I run `:scriptnames` after launching Vim with `git config -e`, I get:
```
  1: /etc/vimrc
  2: /usr/share/vim/vim82/defaults.vim
  3: /usr/share/vim/vim82/filetype.vim
  4: /usr/share/vim/vim82/ftplugin.vim
  5: /usr/share/vim/vim82/indent.vim
  6: /usr/share/vim/vim82/syntax/syntax.vim
  7: /usr/share/vim/vim82/syntax/synload.vim
  8: /usr/share/vim/vim82/syntax/syncolor.vim
  9: ~/.vimrc
 10: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
...
```
It also gives me a launch error saying:
```
Error detected while processing /c/Users/Sid K/.vimrc:
line    1:
E117: Unknown function: plug#begin
line    3:
E492: Not an editor command: Plug '(plugin)'

...

E117: Unknown function: plug#end
```

I also tried putting `core.editor` to `vim -f`, but that didn't work.

Sorry for the confusion!

**Comment by chrisbra** [comment]
looks like this are two different Vims that are used. Can you make sure, that you are opening the same Vim? Check `v:progpath` and `:version` output.

**Comment by dscho** [comment]
> I also tried putting `core.editor` to `vim -f`, but that didn't work.

Try setting it to the absolute, quoted path of your Vim in Program Files (x86).

**Comment by Skaytacium** [comment]
> looks like this are two different Vims that are used. Can you make sure, that you are opening the same Vim? Check v:progpath and :version output.

When I use normal Vim I get:
```

**Comment by Skaytacium** [comment]
> looks like this are two different Vims that are used. Can you make sure, that you are opening the same Vim? Check v:progpath and :version output.

When I use normal Vim I get
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:19:27)
MS-Windows 32-bit console version
Compiled by mool@tororo
```

When I use Vim with `git config -e`, I get:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 25 2020 11:44:06)
Included patches: 1-1895
Compiled by <https://www.msys2.org/>
```

> Try setting it to the absolute, quoted path of your Vim in Program Files (x86).

That worked!

I didn't exactly do that, but what I did was:

1. I ran `where.exe vim`, which resulted in `C:\Windows\vim.bat` (might differ for you, not sure)
2. I then ran `git config core.editor "C:/Windows/vim.bat"` (Note the forward slashes)
3. That worked!

Why didn't I think of this before. Thanks a lot!
