### ISSUE TITLE
Request: provide a generic Link to the latest Windows release

### ISSUE THREAD

**Issue by hamlibdk** [git-for-windows/git#2963]
Is it possible to provide a "generic link" to the latest releases (especially Windows releases) so that utilities that use tools such as  cURL or PowerShell Invoke-RestMethod can always point to the same file yet always download the very latest GIT release?

i.e. current Windows release is 2.29.2.3. Versions change frequently. Can a static link - as an example. Git-LATEST-x64.exe -  be provided to this latest release and maintained always to the latest release?

This allows the general programming community to create generic environments where static version coding is eliminated - hence reducing maintenance required on scripts and code. This also allows us to better fit in with current and future licensing requirements

Thanks.

Hamlib SDK Development Team
(Maintainer of the JTSDK for building WSJT-X and forks)

**Comment by PhilipOakley** [comment]
One option is the [git-scm](https://git-scm.com/) page which has an actively updated link https://git-scm.com/download/win 
I believe it the GitHub staff that maintain that page.

**Comment by dscho** [comment]
GitHub Pages does not have redirects, as far as I know. So there isn't any easy way to do that, I don't think. We do update https://gitforwindows.org/latest-version.txt (and `-tag`) though.

**Comment by dscho** [comment]
hrm. I seem to be unable to convert this issue to a discussion. :disappointed:

**Comment by derrickstolee** [comment]
> hrm. I seem to be unable to convert this issue to a discussion. 😞

That feature was having some trouble (dropping comments or something) so they disabled it until they can fix it after the holiday break.

**Comment by hamlibdk** [comment]
Apologies for lack of response but I have been on limited Internet Resources in Central Australia ... The https://gitforwindows.org/latest-version.txt is highly useful and will be used as the basis for experiments taking place.

**Comment by hamlibdk** [comment]
Further issue....

Yes ... https://gitforwindows.org/latest-version.txt is great... But what about the download release path?

The Path nomenclature is inconsistent in its structure... and cannot be calculated as far as I can see easily from just the version data.

Is there any way easily determining this from/for a PowerShell script?

**Comment by hamlibdk** [comment]
PowerShell Script as deployed..... The only issue is if some nomenclature changes....

```
Set-Location -Path $PSScriptRoot

Write-Host ""
Write-Host "* Downloading Git Installer"

# Get current Git-SCM Version
Write-Host ""
$appName="latest-version.txt"
$appURL="https://gitforwindows.org/latest-version.txt"
Invoke-RestMethod -Uri $appURL -Method Get -OutFile $appName

$content = [IO.File]::ReadAllText("$PSScriptRoot\latest-version.txt")
Write-Host "  --> Determining latest Git-SCM version: $content "

# Array seperating version details 
$verArr = @($content.split('.'))

# Actually get current Git-SCM Version
$appName="Git-" + $content + "-64-bit.exe"

# Intemediate to calculate the path
# Sample: https://github.com/git-for-windows/git/releases/download/v2.30.0.windows.2/Git-2.30.0.2-64-bit.exe

$calcPath="v" + $verArr[0] + "." + $verArr[1] + "." + $verArr[2] + ".windows." + $verArr[3]
$appURL="https://github.com/git-for-windows/git/releases/download/" + $calcPath + "/" + $appName

Write-Host "  --> Path: $appURL"

Write-Host "  --> Downloading Git $content Installer"

$appCurrent="Git-Current-x64.exe"
Write-Host "  --> Saving as $appCurrent"
Invoke-RestMethod -Uri $appURL -Method Get -OutFile $appCurrent

Write-Host "  --> Git Download Complete."

exit(0)
```

**Comment by dscho** [comment]
Two comments:

- If you use `latest-tag.txt` _in addition_ to `latest-version.txt`, the logic gets _much_ simpler (and more robust).
- You can convert that logic to modify [the script that adjusts `latest-tag.txt` and `latest-version.txt`](https://github.com/git-for-windows/git-for-windows.github.io/blob/8c46971425eca087f740723c100bb0b5f5c0ad73/bump-version.js#L15) to _also_ write, say, `latest-installer.url` and open a PullRequest. That way, you will get something much more reliable, and so will others.

**Comment by dscho** [comment]
> 
> 
> hrm. I seem to be unable to convert this issue to a discussion. 😞

Seems that now I can!
