### ISSUE TITLE
.exe.exe files generated when doing MSVC build

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/git#2965]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
(Using the Git for Windows SDK)

$ git --version --build-options
git version 2.30.0.windows.1
cpu: x86_64
built from commit: 18da6dbba950f8cc7b7d07057f7c30bf7cf207b6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.685]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
N/A, using Git SDK 64
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git SDK Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

As part of the Git for Windows arm64 work (see https://github.com/git-for-windows/git/issues/2346#issuecomment-751687623 for details), I'm trying to build `mingw32` and then overwrite some executables by native arm64 executables, by following the steps outlined here: https://github.com/git-for-windows/git/pull/2915#issuecomment-739538291

```
cd /usr/src/git
mkdir -p contrib/buildsystems/out
cd contrib/buildsystems/out
cmake ../ -DCMAKE_GENERATOR_PLATFORM=arm64 -DVCPKG_ARCH=arm64-windows -DCMAKE_INSTALL_PREFIX="C:\gitbuild"

# Build the Git executables
msbuild git.sln -property:Configuration=Release

# Link the Git executables
msbuild INSTALL.vcxproj -property:Configuration=Release
```
 - What did you expect to occur after running these commands?

I expected the generated executables in `C:\gitbuild\libexec\git-core` to end with `.exe`.

 - What actually happened instead?

Many generated executables end with `.exe.exe`:

![image](https://user-images.githubusercontent.com/17739158/103657129-cb8b5a80-4f69-11eb-99e1-2d3033c06ff0.png)

This can also be seen in `cmake_install.cmake`:

![image](https://user-images.githubusercontent.com/17739158/103656576-0c36a400-4f69-11eb-9aa6-64872e45da1f.png)

Not sure what is causing this behavior and how I can fix it. Does anyone have any pointers as to what this might be?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Oy... This is most likely a problem in https://github.com/git-for-windows/git/blob/v2.30.0.windows.1/contrib/buildsystems/CMakeLists.txt#L829-L832; I suspect that the `${b}` already has the `${EXE_EXTENSION}`. I did not look closely, though, the bug might be elsewhere, but still a superfluous `${EXE_EXTENSION}`.

Also, could you paste text as text, please? I wanted to quote-reply, but that does not work with images.

**Comment by dennisameling** [comment]
Thanks for the hint! Fixed in https://github.com/git-for-windows/git/pull/2966
