### ISSUE TITLE
Unable to connect to GitHub repository via SSH

### ISSUE THREAD

**Issue by cdemyanovich** [git-for-windows/git#297]
I've followed GitHub's [instructions](https://help.github.com/articles/generating-ssh-keys/) for generating an SSH key. In [Step 5: Test the connection](https://help.github.com/articles/generating-ssh-keys/#step-5-test-the-connection), I get an error connecting to GitHub:
```
$ ssh -T git@github.com
ssh: Could not resolve hostname github.com: Non-recoverable failure in name resolution
```
In GitHub Desktop and via Git 2.5.0 on OS X, I don't experience these errors. What's more, I didn't experience this error on the Git for Windows 1.9.5 preview. I'm running Windows 10.

**Comment by cdemyanovich** [comment]
I should be more specific: I'm running Windows 10 inside VMWare Fusion 7.1.2 Pro on OS X 10.10.5.

**Comment by shiftkey** [comment]
@cdemyanovich could you turn up the verbosity when running that command?

`ssh -T git@github.com -vvv -o LogLevel=DEBUG3`

**Comment by cdemyanovich** [comment]
@shiftkey Sure thing. Here it is:
```
$ ssh -T git@github.com -vvv -o LogLevel=DEBUG3
OpenSSH_6.9p1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /etc/ssh/ssh_config
ssh: Could not resolve hostname github.com: Non-recoverable failure in name resolution
```

**Comment by shiftkey** [comment]
Just installed from chocolatey into a Win10 VM in Parallels and ran that same command (haven't setup certificates or anything, as I don't think that's relevant here):

```
PS C:\Users\shifkey\Documents> ssh -T git@github.com -vvv -o LogLevel=DEBUG3
OpenSSH_6.9p1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: ssh_connect: needpriv 0
debug1: Connecting to github.com [192.30.252.131] port 22.
debug1: Connection established.
...
```

So that seems fine at least for my setup.

Anything interesting from the output of `nslookup -debug github.com`?

**Comment by cdemyanovich** [comment]
Maybe. Look at those domains. Not sure why they're like that, since I haven't knowingly customized anything.
```
$ nslookup -debug github.com
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NXDOMAIN
        header flags:  response, auth. answer
        questions = 1,  answers = 0,  authority records = 0,  additional = 0

    QUESTIONS:
        2.141.16.172.in-addr.arpa, type = PTR, class = IN

------------
Server:  UnKnown
Address:  172.16.141.2

------------
Got answer:
    HEADER:
        opcode = QUERY, id = 2, rcode = NXDOMAIN
        header flags:  response, auth. answer
        questions = 1,  answers = 0,  authority records = 0,  additional = 0

    QUESTIONS:
        github.com.pekininsurance.com, type = A, class = IN

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 3, rcode = NXDOMAIN
        header flags:  response, auth. answer
        questions = 1,  answers = 0,  authority records = 0,  additional = 0

    QUESTIONS:
        github.com.pekininsurance.com, type = AAAA, class = IN

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 4, rcode = NOERROR
        header flags:  response, auth. answer
        questions = 1,  answers = 1,  authority records = 0,  additional = 0

    QUESTIONS:
        github.com.localdomain, type = A, class = IN
    ANSWERS:
    ->  github.com.localdomain
        internet address = 192.30.252.131
        ttl = 5 (5 secs)

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 5, rcode = NOERROR
        header flags:  response, auth. answer
        questions = 1,  answers = 1,  authority records = 0,  additional = 0

    QUESTIONS:
        github.com.localdomain, type = AAAA, class = IN
    ANSWERS:
    ->  github.com.localdomain
        internet address = 192.30.252.131
        ttl = 5 (5 secs)

------------
Name:    github.com.localdomain
Addresses:  192.30.252.131
          192.30.252.131
```

I also found this Cygwin discussion thread, [Cygwin unable to resolve hostnames](https://www.cygwin.com/ml/cygwin/2015-07/msg00350.html).

**Comment by cdemyanovich** [comment]
Tried an install via chocolatey and got the same error trying to resolve github.com hostname. Seems like there's a configuration problem with my Windows VM. I'll try to set up a new one and report back. Thanks.

**Comment by cdemyanovich** [comment]
When I connect to VPN using the Cisco AnyConnect VPN client, I don't have any problems. When I disconnect, the problems return. This wasn't the case before. I wonder if the VPN client is not resetting something like it should.

**Comment by cdemyanovich** [comment]
[When using VMWare Fusion: DNS lookup on Windows 7 guest appends localdomain](http://superuser.com/questions/944332/when-using-vmware-fusion-dns-lookup-on-windows-7-guest-appends-localdomain) could also be relevant, though it has no answers yet.

**Comment by dscho** [comment]
Did you ever override `github.com` via `C:\Windows\system32\drivers\etc\hosts`?

**Comment by dscho** [comment]
> When I connect to VPN using the Cisco AnyConnect VPN client, I don't have any problems. When I disconnect, the problems return. This wasn't the case before. I wonder if the VPN client is not resetting something like it should.

This indicates that the DNS returns bogus answers. You could try to switch to 8.8.8.8 (Google's DNS) in your advanced network settings.

The really strange thing is that you say it worked with 1.9.5... No idea why!

**Comment by cdemyanovich** [comment]
@dscho I haven't changed `C:\Windows\system32\drivers\etc\hosts`, I haven't changed network settings, and I don't recall any installers or programs asking me to change them. I'll keep digging this afternoon or evening as time permits. Thanks.

**Comment by dscho** [comment]
@cdemyanovich You *could* add the entry for github in that file, and that would work around it ;-)

**Comment by dscho** [comment]
I just added the label "unclear" because it is not obvious whether this is a bug in Git, in any of the SDK packages, or in the setup.

**Comment by cdemyanovich** [comment]
@dscho That label makes sense. I'm sorry for the radio silence yesterday. My office was without Internet access for half the day due to fiber being cut by some construction project. :-/

I just performed a fresh install of Windows 10 in VMWare Fusion 7.1.2 Professional. Then, I installed Git-2.5.0-64-bit. Unfortunately, the problem still occurs for me:
```
$ ssh -T git@github.com
ssh: Could not resolve hostname github.com: Non-recoverable failure in name resolution

**Comment by dscho** [comment]
Does it work when passing `-o AddressFamily=inet` to `ssh`?

**Comment by cdemyanovich** [comment]
@dscho Yes!

**Comment by dscho** [comment]
Okay, I guess, then, that it is some kind of IPv6 problem :-(

**Comment by dscho** [comment]
So I just remembered that `nslookup` is provided by Windows itself, and that the DNS lookup mechanism of MSys2 is different.

Could you run this Perl script and report back the results, please?

```perl
#!/usr/bin/perl
use Socket;

($name, $aliases, $addrtype, $length, @addrs) = gethostbyname "github.com";
print "Host name is $name\n";
print "Aliases is $aliases\n";
print "Type is $addrtype\n";
print "Address(es): " . join(', ', map { inet_ntoa($_) } @addrs) . "\n";
```

**Comment by cdemyanovich** [comment]
@dscho Here you go:
```
$ ./inet-test.pl
Host name is github.com
Aliases is
Type is 2
Address(es): 192.30.252.128
```

**Comment by cdemyanovich** [comment]
@dscho and @shiftkey, I've been wondering if this is somehow a VMWare Fusion issue, since @shiftkey [mentioned](https://github.com/git-for-windows/git/issues/297#issuecomment-133264075) that he had no problems in a fresh Windows 10 install on Parallels. I'm reminded of this because I learned that Fusion 8 is available now. I may be trying that soon. If I do, I'll report back. Thanks again for all of your help.

**Comment by cdemyanovich** [comment]
I upgraded to Fusion 8 Pro earlier, and, unfortunately, it did NOT change anything.

**Comment by dscho** [comment]
Well, the main clue is still that this `AddressFamily` setting worked around the issue, i.e. when disabling IPv6, it worked.

**Comment by dscho** [comment]
Maybe the solution is this: according to the VM Fusion documentation, [IPv6 is only supported in bridged networking](http://pubs.vmware.com/fusion-4/index.jsp?topic=%2Fcom.vmware.fusion.help.doc%2FGUID-E498672E-19DD-40DF-92D3-FC0078947958.html). Since the easiest setup uses NAT networking instead, I assume that IPv6 simply does not work.

Now, in Git for Windows 1.x we shipped an `ssh` that simply could not talk IPv6, but the `ssh` in 2.x does. Therefore, you either need to set `AddressFamily = inet` at the top of your `$HOME/.ssh/config`, or [disable IPv6 in your VM client](https://support.microsoft.com/en-us/kb/929852), or switch to bridged networking.

At least that is my guess.

**Comment by cdemyanovich** [comment]
@dscho Switching to bridged networking in VMWare Fusion 8 Pro settings did the trick. I suspect it would've worked in version 7 Pro, too. I'll leave the issue open in case there's anything else you'd like me to investigate or document. Otherwise, we can close it as resolved. Thanks for all of your help!

**Comment by dscho** [comment]
I think we have all the information now, thank you for being so responsive!

**Comment by breiter** [comment]
FYI. Problem also occurs with VMWare Fusion 8 Professional, despite it being supposed to have IPv6 NAT support. Creating ~/.ssh/config to force ipv4 with `AddressFamily = inet` works to resolve the problem.

**Comment by cdemyanovich** [comment]
@breiter Changing the Network Adapter settings on each VM to Bridged Networking -> Autodetect has worked for my entire team. Can you switch to bridged networking?

**Comment by breiter** [comment]
@cdemyanovich I'd prefer not to do that because it exposes the guest OS to any network that the host machine is attached to. It works for me using NAT and `AddressFamily=inet`, so I'm good with that for now. Thanks.

**Comment by dscho** [comment]
@breiter thanks for reporting this. It is good that we have this on public record so people can find this resolution via a simple web search.
