### ISSUE TITLE
DLLs missing when building Git using CMake 

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/git#2970]
When following the steps in https://github.com/git-for-windows/git/pull/2915#issuecomment-739538291 to generate native `arm64` binaries for Git for Windows, all DLLs like `iconv-2.dll` and `zlib1.dll` are missing in the folders with the generated binaries:

![image](https://user-images.githubusercontent.com/17739158/104066198-4c17b880-5201-11eb-95fa-cdfbad3958cf.png)

When I copy the required DLLs manually from `C:\git-sdk-64\usr\src\git\compat\vcbuild\vcpkg\installed\arm64-windows\bin`, all is good:

![image](https://user-images.githubusercontent.com/17739158/104066298-7a959380-5201-11eb-86dc-ae3126dfa73a.png)

Same goes for `/arm64/libexec/git-core` - manually adding the DLLs works.

Does anyone have an idea how we can copy the DLLs during the CMake build process as well? I assume this needs to happen in `INSTALL.vcxproj` somehow? Happy to provide a PR if someone could put me in the right direction 😊

**Comment by dscho** [comment]
Maybe we have to imitate the approach outlined in the first response of https://stackoverflow.com/questions/44650008/cmake-install-third-party-dll-dependency ?

**Comment by jeffhostetler** [comment]
(i'm on my ipad here, so i'm doing this from memory.)

Look in compat/win32/copy_dlls.bat 

it will copy them into those two directories.
it may be that we need to add a call to it in the vcproj step.

jeff

**Comment by dscho** [comment]
We may need to imitate the `copy_dlls.bat` steps as outlined [here](https://stackoverflow.com/a/39807774):

```cmake
add_custom_command(TARGET mylib POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy mylib.dll ${myapp_BINARY_DIR}/. )
```

**Comment by dscho** [comment]
(But I still hope that we find a way to do this in an `install()` step...)

**Comment by dscho** [comment]
Oooh, ooh, it might be controlled by `set(VCPKG_APPLOCAL_DEPS ON)`...

**Comment by dennisameling** [comment]
That works @dscho - thanks! Created a PR: https://github.com/git-for-windows/git/pull/2971
