### ISSUE TITLE
Context menu entries should only be shown when pressing ALT

### ISSUE THREAD

**Issue by mirh** [git-for-windows/git#2977]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.30.0.windows.1
cpu: x86_64
built from commit: 18da6dbba950f8cc7b7d07057f7c30bf7cf207b6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19042.685]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

### Details
I don't think most people appreciate git entries when they right click on their desktop, or in any other mundane activity. 
Rather, just like windows does with cmd/powershell, they should only be shown if the right click was done together with the ALT button pressed (or alternatively if the current folder is a git repository). 
This is also similar to tortoisegit's behaviour IIRC.

**Comment by rimrul** [comment]
If we go this step, I'd prefer that we make this behaviour configurable in the installer.

A good place to start is [here](https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss#L3068-L3101)

**Comment by mirh** [comment]
I don't think there's really much.. variance about the preference for this option, but sure that could do it too.

**Comment by dscho** [comment]
Let's close this for now. The next step would be a PR by @mirh, anyway.

**Comment by Youw** [comment]
Maybe this is not a PR, but I hope it is still helpfull:
To hide entry by default, one must create an empty string value named "Extended" under untext menu key, e.g.:
![image](https://user-images.githubusercontent.com/5939659/111001367-533b7e00-838c-11eb-807b-35f68612971c.png)

NOTE: on my machine it requies to hold "Shift" key, not "Alt" as mentioned in this ticket, to show extended/optional menu entries.
