### ISSUE TITLE
failed to restrict file handles

### ISSUE THREAD

**Issue by liu-sen** [git-for-windows/git#2982]
warning: failed to restrict file handles (5)

handle #0: 0000000000000008 (type 2, handle info (1) 0
handle #1: 0000000000000374 (type 2, handle info (1) 1
handle #2: 0000000000000378 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

**Comment by PhilipOakley** [comment]
What Git version are you using? Filling in the template would help.

Are you up to date?

**Comment by rimrul** [comment]
I'm closing this issue due to lack of usable information and feedback to request for said information.
Feel free to reopen this issue after submitting more information.
