### ISSUE TITLE
Spurious error: "fatal: bad numeric config value 'xterm' for 'GIT_PAGER_IN_USE': invalid unit"

### ISSUE THREAD

**Issue by jnareb** [git-for-windows/git#2985]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.30.0.windows.2
cpu: x86_64
built from commit: f8cbc844b81bf6b9e72178bbe891a86c8bf5e9e7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows 10 Home 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1316]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git grep --no-index 'gpuslides' -- '*.tex'
```
 - What did you expect to occur after running these commands?

```
GPU_wyklad05-OpenACC.tex:\input{gpuslides_settings.tex}
GPU_wyklad06-CUDA_opt_1.tex:\input{gpuslides_settings.tex}
```

 - What actually happened instead?

```
fatal: bad numeric config value 'xterm' for 'GIT_PAGER_IN_USE': invalid unit
```

When trying to diagnose the source of error by prefixing the command with `GIT_TRACE=1`, and on subsequent repetitions of said command, the error vanished without trace.

This was the first time using Git after update (automatically triggered).

**Comment by dscho** [comment]
> `fatal: bad numeric config value 'xterm' for 'GIT_PAGER_IN_USE': invalid unit`

Have you looked whether your `GIT_PAGER_IN_USE` really is set to `xterm`?

I've looked for way longer than I cared to, and did not find anything in Git for Windows that could cause this. It looks to me as if that problem was caused from _outside_ Git for Windows.

**Comment by jnareb** [comment]
I think that might be a Heisenbug that is very hard to reproduce.

Neither `printenv` nor `git var -l` show any value for `GIT_PAGER_IN_USE` (or even the variable itself). Moreover, it looks like `GIT_PAGER_IN_USE` should be unset automatically, if I understand the command trace correctly:
```
$ GIT_TRACE=1 git grep --no-index 'gpuslides' -- '*.tex'
17:32:46.039749 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
17:32:46.092730 git.c:444               trace: built-in: git grep --no-index gpuslides -- '*.tex'
17:32:46.094698 run-command.c:664       trace: run_command: unset GIT_PAGER_IN_USE; LESS=FRX LV=-c less
```

So I guess this is 'cannot reproduce' bug...

**Comment by dscho** [comment]
The problem does not seem that it is "not unset". The value `xterm` is bogus. Maybe one of your scripts or smudge filters erroneously sets `GIT_PAGER_IN_USE=${GIT_PAGER_IN_USE:-$TERM}` or some such.

**Comment by dscho** [comment]
Closing as stale.
