### ISSUE TITLE
'bash: code: command not found'

### ISSUE THREAD

**Issue by MD2901** [git-for-windows/git#2987]
Hi,

I'm using git version 2.30.0.2 for Windows. 
I keep getting this problem in VS code: 'bash: code: command not found' when I type 'code' in the terminal.
I'm trying to set up a server but I think this is why the port won't listen. Git and code seem to have a disconnect somewhere.

It seems like an issue with the path? but I'm not sure how to fix that.
Asking here is my last recourse.. googling and like 10 hours of trying later..
Getting git bash to work in VS code shouldn't be this hard lol.. any suggestions?

Thanks,

**Comment by rimrul** [comment]
IIRC VS Code only installs `code.bat` on the `PATH`.

`bash.exe` does not consider batch files when trying to execute a command, so you'll need to call `code.bat` or setup an alias.

**Comment by dscho** [comment]
Works for me:

```shellsession
$ which code
/c/Users/me/AppData/Local/Programs/Microsoft VS Code/bin/code
```

Maybe VS Code was installed without adding it to the `PATH`.
