### ISSUE TITLE
2)DLL rebasing may be required; see 'rebaseall / rebase --help'.

### ISSUE THREAD

**Issue by usha-ui** [git-for-windows/git#2989]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by usha-ui** [comment]
> * [ ] error showing in git terminal ------->
**Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.**


> ### Setup
> * Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
> 
> ```
> $ git --version --build-options
> 
> ** 32 bit **
> ```
> 
> * Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
> 
> ```
> $ cmd.exe /c ver
> 
> ** insert your machine's response here **
> ```
> 
> * What options did you set as part of the installation? Or did you choose the
>   defaults?
> 
> ```
> # One of the following:
> > type "C:\Program Files\Git\etc\install-options.txt"
> > type "C:\Program Files (x86)\Git\etc\install-options.txt"
> > type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> $ cat /etc/install-options.txt
> 
> **  > type "C:\Program Files\Git\etc\install-options.txt" **
> ```
> 
> * Any other interesting things about your environment that might be related
>   to the issue you're seeing?
> 
> ** i have installed once it got installed, on running "git status" in git terminal, it is showing many things in red color, I uninstalled git bash and installed it once again this time it got installed in "c:\users\git ** in other location, because it was not fully uninstalled previously, so i installed it in c:\users location, after installing git terminal is showing these two errors.
> 
> ### Details
> * Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
> 
> ** insert your response here **
> 
> * What commands did you run to trigger this issue? If you can provide a
>   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
>   this will help us understand the issue.
> 
> ```
> ** insert your commands here **
> ```
> 
> * What did you expect to occur after running these commands?
> 
> ** insert here **
> 
> * What actually happened instead?
> 
> ** insert here **
> 
> * If the problem was occurring with a specific repository, can you provide the
>   URL to that repository to help us with testing?
> 
> ** insert URL here **

**Comment by usha-ui** [comment]
please help me to fix the problem

**Comment by rimrul** [comment]
Have you tried [DLL rebasing](https://github.com/git-for-windows/git/wiki/32-bit-issues#adjusting-msys-20dlls-address-range-manually) like the error message suggests?

**Comment by CaptainMaxD** [comment]
Error: No se pudo bifurcar el proceso hijo: Recurso temporalmente no disponible (-1).
Es posible que se requiera reajuste de DLL; consulte 'rebaseall / rebase --help'.

Hola, tengo windows 10 de 64 bits, instalé la versión git de 64.
En las multiples instalaciones, puse las 3 opciones:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
Ejecuté tanto en bash como en cmd y no hay caso. Sigue saliendo:
Error: No se puede lanzar proceso hijo: Resource temporarily unavailable (-1).
Se requiere rebasing de la DLL; más información 'rebaseall / rebase --help'.
Me bajé el sdk y lo mismo. 
Gracias.

**Comment by rimrul** [comment]
> Hi, I have windows 10 64 bit, I installed the git 64 version.
In the multiple installs, I put all 3 options:

>I ran both bash and cmd and there is no case. It keeps coming up:
Error: Unable to launch child process: Resource temporarily unavailable (-1).
DLL rebasing is required; more information 'rebaseall / rebase --help'.
I downloaded the sdk and the same.
Thanks.

Lo siento por la traducción automática de esto, pero no hablo español. ¿Intentaste volver a basar las DLLs?

Para solucionar el problema de los solapamientos de rangos de direcciones, MSYS2 ofrece una utilidad llamada rebase.exe (que confusamente no tiene nada que ver con git rebase) para ajustar el rango de direcciones de un conjunto dado de archivos .dll.

Desgraciadamente, el síntoma no se produce tan raramente, por lo que existe incluso un script para hacer que rebase.exe sea más cómodo de usar: /usr/bin/rebaseall. Este script está pensado para ser ejecutado a través de Dash en lugar de Bash, para evitar los problemas del huevo y la gallina de que Bash no pueda ejecutarse correctamente a menos que el rango de direcciones ya esté fijado. Normalmente no es necesario ejecutar este script manualmente porque se ejecuta como parte del proceso de instalación de Git para Windows. Si el síntoma se produce en algún momento mucho después de la instalación de Git para Windows, reinstalar Git para Windows es la forma más conveniente de solucionarlo.

Si aún así insistes en arreglarlo manualmente, por favor, entiende que esto no es recomendable sin conocimiento de los aspectos internos de MSYS2 (léase: si te quedas atascado, por favor, no abras un ticket para aprender más sobre MSYS2; usa la forma recomendada en su lugar: reinstalar Git para Windows). La forma manual es la siguiente

    cerrar todas y cada una de las ventanas de mintty

    terminar todos y cada uno de los Bash

    terminar incluso los procesos en segundo plano que utilizan el tiempo de ejecución de MSYS2, como ssh-agent

    abrir cmd.exe, cambiar el directorio al nivel superior de Git y luego ejecutar

    usr\bin\dash -c '/usr/bin/dash /usr/bin/rebaseall -p'

En el caso de que el runtime de MSYS2 necesite ser rebasado también, necesitarás llamar a algo como esto

copy usr\bin\msys-2.0.dll copy-msys-2.0.dll
usr\bin\rebase.exe -b 0x67000000 copy-msys-2.0.dll
copy copy-msys-2.0.dll usr\bin\msys-2.0.dll
usr\bin\dash.exe -c 'cd / && /usr/bin/dash.exe /usr/bin/rebaseall'

Estos comandos deben ser ejecutados en el directorio de nivel superior, y la dirección (0x67000000) podría necesitar ser ajustada.

**Comment by ravik694** [comment]
> how di i uninstall git and github completely please let me know,
> i am getting again dll rebase error

Disabling mandatory ASLR fixed it for me. https://github.com/git-for-windows/git/issues/2872#issuecomment-757441615

I had to disable it system-wide, the PowerShell included in the known issues page didn't seem to do it for me.

**Comment by usha-ui** [comment]
MY ERROR FIXED, THANKS

**Comment by dscho** [comment]
> ERROR FIXED, THANKS

For other people who might come about this ticket in a web search, it would be nice to add some explanation here: it might help resolve others' issues, too.
