### ISSUE TITLE
git GUI open repository automatically

### ISSUE THREAD

**Issue by albertorivelli** [git-for-windows/git#299]
I almost work always on the same repository and when I launch git GUI I'd like to open that repository automatically.
Is it possible to open a repository automatically without the additional step of opening the repository in git GUI? (without modifying source code)
It'd be a nice feature to have.

**Comment by dscho** [comment]
@albertorivelli this is the first time that I heard this request. So far, it seems as if people are happy with the choice of the three most recent repositories when starting Git GUI outside any Git repository.

Read: the most likely way to get what you want is to dive in and make happen what you want.

OTOH it might also be possible that you are satisfied with creating a shortcut to the `C:\Program Files\Git\cmd\git-gui.exe` command, then open the *Properties...* in the context menu of the shortcut and change the *Start in* directory to the top-level directory of your working directory in question. This is regular Windows functionality, BTW, nothing fancy required of Git for Windows.

Does this help you?

**Comment by albertorivelli** [comment]
oh yes, that's what I wanted. Sorry If I put this here, I asked on stackoverflow but got no answers.
Thank you very much.
