### ISSUE TITLE
uninstalling git and github

### ISSUE THREAD

**Issue by usha-ui** [git-for-windows/git#2990]
- [ ]

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.30.0, windows 7, 32 bit **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

**  "C:\Program Files\Git\etc\install-options.txt"
 "C:\user\Git\etc\install-options.txt" **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**  not able to uninstall git completely, getting again and again error
                   1)Error: Could not fork child process: Resource temporarily unavailable (-1).(#2988) 
                     2)DLL rebasing may be required; see 'rebaseall / rebase --help'. (#2989) **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
This report, as well as the one preceding it, are so incomplete as to prevent anybody from helping out.

**Comment by PhilipOakley** [comment]
@usha-ui The uninstall has a short-name, and on my system is at `C:\Program Files\Git\unins001.exe`. 
Try that.

Maybe we need it to be called "`uninstall.exe`", or maybe a shortcut with that plain name.
