### ISSUE TITLE
ERROR IN GIT-BASH TERMINAL---error: src refspec main does not match any error: failed to push some refs to 'github.com:usha-ui/git-repo-harry.git'

### ISSUE THREAD

**Issue by usha-ui** [git-for-windows/git#2992]
- [x ] I was not able to find an issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

**$ git --version --build-options
git version 2.30.0.windows.2
cpu: i686
built from commit: f8cbc844b81bf6b9e72178bbe891a86c8bf5e9e7
sizeof-long: 4
sizeof-size_t: 4
shell-path: /bin/sh **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

**Microsoft Windows [Version 6.1.7600],  32bit.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** type "C:\Program Files\Git\etc\install-options.txt" **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**whenever i an running command  --- $ git push -u origin main - i am getting error--
error: src refspec main does not match any
error: failed to push some refs to 'github.com:usha-ui/git-repo-harry.git'

  **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** git-bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** N/A **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> ```shellsession
> $ git push -u origin main
> ```
> i am getting error--
> ```
> error: src refspec main does not match any
> ```

Are you sure that you have a `main` branch to work with? What does `git branch` show?

**Comment by usha-ui** [comment]
sir, git branch shows--- master branch.   during installation git-bash, it was showing,installing in main branch.

**Comment by usha-ui** [comment]
$ git push -u origin master
The authenticity of host 'github.com (13.234.176.102)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? no
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rimrul** [comment]
>The authenticity of host 'github.com (13.234.176.102)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? **no**
Host key verification failed.
fatal: Could not read from remote repository

You chose to stop connecting and are now wondering that that push didn't go through?

**Comment by usha-ui** [comment]
respected SIR
thanks a lot sir, your attention helped me lot, i was matching it with key
and it was not matched so i entered NO,
thankyou sir
