### ISSUE TITLE
Only override pacman-mirrors for Git for Windows

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#30]
A really nice feature of the pacman mirrorlists is that you can specify multiple locations for package indexes and all of them will be used.

That means that we actually do not have to override anything in `/etc/pacman.conf` because we can just piggy-back our Bintray repositories via the `pacman-mirrors` package that provides the `mirrorlist.*` files.

All we have to do is to make sure that the package index is actually not called `git-for-windows.db.tar.xz`, but `mingw32.db.tar.xz`, `mingw64.db.tar.xz` and `msys2.db.tar.xz`, respectively.

**Comment by dscho** [comment]
@sschuberth I think that would be a much more light-handed way to handle the situation than to override `pacman` altogether, don't you think?

**Comment by sschuberth** [comment]
> A really nice feature of the pacman mirrorlists is that you can specify multiple locations for package indexes and all of them will be used.

I was in fact looking for that feature being documented somewhere, but I was unable to find anything authoritative. In principle, it could be that pacman expects all servers within a single mirrorlist file to be full mirrors, just uses them to sort by connection speed, and only falls back to another mirror if a previous one is not reachable, but no if a specific package could not be found on the original server.

Do you have a link stating that pacman actually "merges" the package databases of all mirrors?

**Comment by sschuberth** [comment]
> All we have to do is to make sure that the package index is actually not called git-for-windows.db.tar.xz, but mingw32.db.tar.xz, mingw64.db.tar.xz and msys2.db.tar.xz, respectively.

You're right in that it would be easier in terms of fewer initial changes that we need to do to the pacman(-mirror) packages. But we already did these changes. And as @t-b said, we should ensure that we're able to build all our required packages from source anyway. Finally, I believe upstream MSYS2 did not a good job at naming their repository sections and splitting between `mingw32` and `mingw64` (That should be done via $arch in the URL, or?).

**Comment by dscho** [comment]
Okay, your call. I am just reluctant to keep our `pacman` up-to-date (just have a look how fast `MSYS2-packages`' `pacman/` history moves). I hope that you will take care of that?

**Comment by sschuberth** [comment]
> I hope that you will take care of that?

I don't intend to :-) More seriously, by now we already have a bunch of changes against upstream. The addition of the `git-for-windows` config section is not the only one. If it was, I'd probably follow your suggestion.

**Comment by dscho** [comment]
> > I hope that you will take care of that?
> 
> I don't intend to :-)

Well, that leaves us between a rock and a hard place. You suggest changes that will be a real pain to maintain, and I am not willing to bear that pain myself. Instead, I suggested something much less heavy-handed that should allow us to give users access to our Pacman repositories but does not require us to update our own fork of the `pacman` package every couple of days, but you reject that.

> More seriously, by now we already have a bunch of changes against upstream. The addition of the git-for-windows config section is not the only one. If it was, I'd probably follow your suggestion.

The idea is of course to get our changes upstream, but who knows how long that will take. The point is that we should decide upon a proper course of action. I know I won't have time (nor fun) keeping `pacman` up-to-date, so I want to steer clear from that direction. Unless you have a better solution that convinces me :grinning:

**Comment by sschuberth** [comment]
> The idea is of course to get our changes upstream, but who knows how long that will take.

Exactly. But unless my config change is the only one against upstream, we would need to keep up with upstream all the time anyway. My goal of course is to *also* the get config change upstream. And I think there's a good chance getting that done, as it takes the burden off of upstream to maintain the mingw-git package.

**Comment by dscho** [comment]
> But unless my config change is the only one against upstream, we would need to keep up with upstream all the time anyway.

No, not if we change *only* the `pacman-mirrors` package. That one is slow moving. Glacial, even.

My point stands: I will be very unhappy if I am the one to get stuck with keeping a forked `pacman` package up-to-date.

**Comment by sschuberth** [comment]
> No, not if we change only the pacman-mirrors package. That one is slow moving. Glacial, even.

Yes, I understand. Again, my point is that that my config change is not the only one against the pacman package that we have compared to upstream. We currently have:

$ git log --oneline HEAD --not upstream/master -- pacman
45ad3cd pacman: Bump the pkgver
4936bf5 Move the git-for-windows package server URL to a mirrorlist file
7a7b0ed pacman: work around Git checkout with core.symlinks = false
f132193 Merge remote-tracking branch 'origin/master'
e7f38ad pacman: Bump the pkgver/rel via makepkg
d4c2420 pacman: Add missing makedepends to the PKGBUILD
7298f93 Fixup the MD5 for pacman.conf due to the recent changes
99afcae pacman.conf: Make use of $repo for git-for-windows
46b8737 Consolidate identical pacman.conf.{i686,x86_64} files into one
8c42369 Introduce the git-for-windows repository to pacman

Unless *all* of these are upstream we would need to keep up with the fast-moving pacman from upstream anyway.

How about this: I promise to try taking all of the above which are mine to upstream as quickly as possible, and if not possible, I'll drop them in favor of a different solution that does not require us to rebuild pacman.

**Comment by dscho** [comment]
The bumps of the pkgver do not at all need to be pushed upstream.

**Comment by dscho** [comment]
> I promise to try taking all of the above which are mine to upstream as quickly as possible, and if not possible, I'll drop them in favor of a different solution that does not require us to rebuild pacman.

Okay, closing this ticket for now, then.

**Comment by sschuberth** [comment]
> The bumps of the pkgver do not at all need to be pushed upstream.

Ok, but how you you then easily see from a binary package's file name from which source code it was built?

**Comment by dscho** [comment]
> how you you then easily see from a binary package's file name from which source code it was built?

From the last part of the version number. For example, pacman version 4.2.0.6096.*df5ce98* was built from Alexpux/MSYS2-pacman@df5ce98.

Once we have everything upstream, our `master` becomes dormant, but still reflects the commits that are there right now.

**Comment by sschuberth** [comment]
> From the last part of the version number.

Doh, of course :-)

**Comment by dscho** [comment]
@sschuberth I got really, really bad news: *only* the first `Server` line from the mirror list is heeded.

That means several things:

- all of the effort to split up our repository into four different ones is probably for naught, *unless* we add *four different mirrorlists with corresponding entries in the `pacman.conf`* (and soon even five because we have an upcoming package that does not even fit into those categories!
- we cannot only override `pacman-mirrors`. Which is a major shame because now we are most likely stuck with a really annoying maintenance burden (because it is highly unlikely that upstream MSys2 will let us add our repositories to their `pacman.conf` – and possibly override their `msys2-runtime`).

So now I am even more convinced that while it was worth a try to be overzealous, i.e. to split our repositories into so many, we should simplify the structure ([*"perfection is finally attained not when there is no longer anything to add, but when there is no longer anything to take away"*](http://en.wikiquote.org/wiki/Antoine_de_Saint_Exup%C3%A9ry)) and have a *single* Pacman repository that contains all of our packages, whether they be MinGW or MSys2, i686 or x86_64 or "any". The idea of Pacman is that the *tool* knows these things and can handle them, after all. We will just need to add the `Architecture = auto` line to the `[git-for-windows]` section.

**Comment by dscho** [comment]
Oh, and for the record: upstream only makes the difference between the MinGW and the MSys2 repositories because they want to allow to install 64-bit *and* 32-bit MinGW packages, while they can only allow installation of MSys2 packages of the same architecture as the current `msys2-runtime`. So for them, the split makes sense.

For us, the split does not make sense. We would never want to run a 64-bit Git with a 32-bit Bash. There is no good reason for that. The only reason to run Git with a 32-bit Bash is if we are on a processor that cannot handle 64-bit, i.e. *both* Git and Bash would have to be 32-bit.

**Comment by sschuberth** [comment]
> only the first Server line from the mirror list is heeded.

I was already reckoning that, see my skepticism and question in [this comment](https://github.com/git-for-windows/git/issues/30#issuecomment-77824376).

So keeping mirrorlist files for us would only make sense if we planned to maintain GitHub and Bintray with both having the full list of packages. I guess this is not what we want, we want Bintray only. So as we now need to have a custom `pacman` package anyway, now about directly adding our servers there without `Include` and not override `pacman-mirrors` at all? That we we at least would have only one pacman package to maintain.

> have a single Pacman repository that contains all of our packages

Can we than handle programs for which we might have both an MSYS2 and a MinGW version without a clash in filenames (my guess it yes, as MinGW packages seem to be prefixed by `mingw-w64-{i686,x86_64}-`).

**Comment by dscho** [comment]
> So as we now need to have a custom pacman package anyway, now about directly adding our servers there without Include and not override pacman-mirrors at all?

That's how I did things [here](https://github.com/git-for-windows/MSYS2-packages/compare/master...dscho:pacman-flat), but note: there is an *even worse* problem. We **cannot** have a single flat repository. When calling `repo-add` with packages of the same name but for different architectures, the latter packages will *override* the former ones.

So we have to have at least an `i686` and an `x86_64` repository. Bummer.

> MinGW packages seem to be prefixed by mingw-w64-{i686,x86_64}-

Yes, that is the convention we need to heed, too.

**Comment by sschuberth** [comment]
> they want to allow to install 64-bit and 32-bit MinGW packages

Actually, doesn't that mean we should revert https://github.com/git-for-windows/MSYS2-packages/commit/bedbdf1f053a2380364ac7d92fb6416525492226 as we should be able to run MinGW 32- and 64-bit shells no matter what the MSYS2 bitness is?

**Comment by dscho** [comment]
I would not revert it. Remember: we do not try to develop MSys2. We try to develop  Git for Windows. And since Git requires a Perl and a Bash, still, we need to ship those packages *with* Git. IMO it only makes sense to ship those packages for the exact same architecture. That also means that you should develop (and test) the `mingw-w64-git` package within an MSys2 of the same architecture you are targeting.

So for us, the maintainers, that means that we will always have to have a 32-bit SDK to build 32-bit Git for Windows, and a 64-bit SDK to build 64-bit Git for Windows.

**Comment by sschuberth** [comment]
> we will always have to have a 32-bit SDK to build 32-bit Git for Windows, and a 64-bit SDK to build 64-bit Git for Windows.

Agreed, for us this change makes sense an keeps things a bit simpler. So that change is not something I would propose for upstream.

For other none-GfW specific changes, I just created [this PR](https://github.com/Alexpux/MSYS2-packages/pull/191) to bring things upstream and Alex was very quick at merging it.

**Comment by dscho** [comment]
Nice!!!
