### ISSUE TITLE
Gitk branch label background color

### ISSUE THREAD

**Issue by albertorivelli** [git-for-windows/git#300]
Gitk branches labels background color is very dark in 2.5.0, so much that it's very hard to read the label's text. The color is set to 'green' in gitk config as in 1.9.3 but the result is completely different.

**Comment by dscho** [comment]
@albertorivelli please take the time to follow the advice in our [wiki page on reporting bugs](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines), linked from our home page in the [Contribute](https://git-for-windows.github.io/#Contribute) section. It is definitely not something I ask just for fun. You definitely want to help me reproduce your problem as quickly as possible.

As it stands, I cannot reproduce:

![gitk-branch-color](https://cloud.githubusercontent.com/assets/127790/9413338/8cb95270-4831-11e5-85cc-41c3678744b2.png)

This is on Windows Server 2012 R2.

**Comment by albertorivelli** [comment]
this is correct, it's very dark compared to the old version.
![gitk](https://cloud.githubusercontent.com/assets/13906192/9413637/5e5e8a56-4833-11e5-9b9e-56ccd9b556c3.png)

**Comment by dscho** [comment]
> I set the 'headbgcolor' value to #00ff00 to fix it.

You mean in `$HOME/.config/git/gitk`? If so, yes, that is a good place to modify it locally.

If you want to fix it for other people, too, the best way to go about it is to patch `gitk` directly, and send the patch upstream (git@vger.kernel.org). In that case, I would recommend using `lime` instead of `"#00ff00"`, but that is a matter of taste, really.

**Comment by dscho** [comment]
Oh, completely forgot to mention: I think this is a change in Tk 8.6 described [here](http://wiki.tcl.tk/1424): *From Tcl/Tk 8.6 on, Tk uses Web colours instead of X11 ones, where they conflict.*

**Comment by albertorivelli** [comment]
that's what I was asking myself, why the same color value was rendered differently.
So the only way is to change the color in the configuration file to 'lime'.
I don't know if this setting is good for other people too, I'm not sending a patch for it, also I don't have the code on my machine.
Thanks

**Comment by quinte17** [comment]
in my opinion it is a regression. the underlying api (value of green) has changed.

**Comment by dscho** [comment]
@quinte17 The real question is: do you care enough about it to [make the changes](https://github.com/git-for-windows/git/wiki/Good-commits#commit-messages) in [`gitk`](https://github.com/git-for-windows/git/blob/master/gitk-git/gitk) (replace `green` with `lime`, but make sure to remove `~/.config/git/gitk` before testing) and open a Pull Request [with a nicely written (and signed-off) commit message](https://github.com/git-for-windows/git/wiki/Good-commits#commit-messages)?

**Comment by quinte17** [comment]
@dscho yeah one could do that. but that color change depends on the tcl/tk version. i am not familiar with tcl/tk, so does lime also exist for older versions? alternate solution would be to define all colors with their hexcode, so a change in the future wouldnt hurt. i dont think that this would be accepted.

**Comment by dscho** [comment]
@quinte17 you know, there are ways to find out whether `lime` is supported by older Tcl/Tk versions... Why don't you do that? If the result of that research is clearly outlined in the commit message, as well as the rationale for the change, the patch would *most* likely be accepted with gratitude.

**Comment by PhilipOakley** [comment]
This recently came up on the main Git list. http://thread.gmane.org/gmane.comp.version-control.git/285589 and http://thread.gmane.org/gmane.comp.version-control.git/285629. (which links back here!)

As @dscho says, the change was in the underlying change in Tcl/Tk (see the final thread http://article.gmane.org/gmane.comp.version-control.git/285653) which brought the colour names into alignment with the actual color (against one particular standard). http://www.tcl.tk/cgi-bin/tct/tip/403.html has some details about the colour names.

The X11 colurs are listed/shown in the Wikipedia article https://en.wikipedia.org/wiki/X11_color_names#Color_name_clashes

There are scripts to show the colours in context at https://wiki.archlinux.org/index.php/X_resources#Color_scheme_scripts

colour setting can be adjusted in your `$HOME/.config/git/gitk` (see the other answers in this thread)

Hopefully having all the links together will help some.
