### ISSUE TITLE
VISUAL STUDIO CODE ---- ERROR--

### ISSUE THREAD

**Issue by usha-ui** [git-for-windows/git#3012]
in visual studio code--- view -> command palette ->it is not showing Git: ADD REMOTE command.

- whenever i am typing  Git: ADD REMOTE command, it is showing --> no matching command found.
- how to fix it.

**Comment by rimrul** [comment]
Not a Git for Windows issue.

**Comment by tboegi** [comment]
did you try 
git add remote
(lowercase)

**Comment by usha-ui** [comment]
yes sir previously also i was typing lower case only, sir thanks for helping , but still the problem is not  solved, thanks for your precious time. but problem is not solved.
