### ISSUE TITLE
Git bash task bar icon broken after installing git into a different location on the same machine

### ISSUE THREAD

**Issue by orgi** [git-for-windows/git#3014]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options
git version 2.30.0.windows.2
cpu: x86_64
built from commit: f8cbc844b81bf6b9e72178bbe891a86c8bf5e9e7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.746]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Initially, with the old git installation, I did a non-admin installation into the user folder (some older git version, presumably 2.24.1 or 2.26):
```
C:\Users\<username>\AppData\Local\Programs\Git
```
I installed the new version using the global location:
```
C:\Program Files\Git
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MinTTY

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Trying to pin the git bash link to the task bar using
* The white -ish icon which appear after starting the git bash
* The git bash icon from the start menu

When I switch back to the non-admin installation of Git I can get the icon back working properly.
```
 - What did you expect to occur after running these commands?

Link to the git bash pinned + icon visible + link and icon indicating any running git bash instances

 - What actually happened instead?

After starting the git bash, the icon is missing.
* Instead there's just this Windows default icon used (the blank document icon). I can still pin that icon - however it would be nice to have the actual git bash icon there.
* When I pin the git bash icon from the start menu - the pinned icon is correct. However, after starting the git bash using that icon, it would create again that blank icon next to the original icon in the task bar.

There seems to be something wrong with the path. It still seems to pick up the old installation path for the icon. When I check the properties of the blank-ish icon I can still see the old path in there:

![image](https://user-images.githubusercontent.com/926216/106588719-6ff1c400-654b-11eb-9b93-86f80b4b6b97.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by orgi** [comment]
It looks like this will happen whenever you install Git a second time using a different path. At least I encountered the same issue when installing to `%USERPROFILE%\AppData\Local\Programs\Git2`.

**Comment by dscho** [comment]
I _think_ this is a [MinTTY](https://github.com/mintty/mintty) issue. The way `git-bash.exe` calls `mintty.exe` is shown [here](https://github.com/git-for-windows/MINGW-packages/blob/eca72dc00f56ffeb6eb1facba11021a86f09b772/mingw-w64-git/git-bash.rc#L3):

> `0 "APP_ID=GitForWindows.Bash ALLOC_CONSOLE=1 usr\\bin\\mintty.exe --nodaemon -o AppID=GitForWindows.Bash -o AppLaunchCmd=""@@EXEPATH@@\\git-bash.exe"" -o AppName=""Git Bash"" -i ""@@EXEPATH@@\\git-bash.exe"" --store-taskbar-properties -- /usr/bin/bash --login -i"`

@orgi maybe you can figure out how this should be called instead? [Here](https://mintty.github.io/mintty.1.html) is MinTTY's official manual.

**Comment by orgi** [comment]
Thanks for the swift response. I'll try to see whether this is related.

**Comment by orgi** [comment]
Ok, could figure out the following:
1. I was able to reproduce the behavior even when replacing the `@@EXEPATH@@` with the actual paths
```bat
cd C:\Users\<USERNAME>\AppData\Local\Programs\Git-new
C:\Users\<USERNAME>\AppData\Local\Programs\Git-new>set ALLOC_CONSOLE=1
C:\Users\<USERNAME>\AppData\Local\Programs\Git-new>set APP_ID=GitForWindows.Bash
C:\Users\<USERNAME>\AppData\Local\Programs\Git-new>usr\bin\mintty.exe --nodaemon -o AppID=GitForWindows.Bash -o AppLaunchCmd="C:\\Users\\<USERNAME>\\AppData\\Local\\Programs\\Git-new\\git-bash.exe" -o AppName="Git Bash" -i "C:\\Users\\<USERNAME>\\AppData\\Local\\Programs\\Git-new\\git-bash.exe" --store-taskbar-properties -- /usr/bin/bash --login -i
```
2. I was able to get the icon working (for the very call to MinTTY) after changing the `AppID` as follows: `AppID=GitForWindows.Bash2`. However - while the icon for the opened terminal was correct - after opening a new instance, the blankish icon again was there for the new instance (including the wrong paths in its properties):
```
cd C:\Users\<USERNAME>\AppData\Local\Programs\Git-new
C:\Users\<USERNAME>\AppData\Local\Programs\Git-new>set ALLOC_CONSOLE=1
C:\Users\<USERNAME>\AppData\Local\Programs\Git-new>set APP_ID=GitForWindows.Bash
C:\Users\<USERNAME>\AppData\Local\Programs\Git-new>usr\bin\mintty.exe --nodaemon -o AppID=GitForWindows.Bash2 -o AppLaunchCmd="C:\\Users\\<USERNAME>\\AppData\\Local\\Programs\\Git-new\\git-bash.exe" -o AppName="Git Bash" -i "C:\\Users\\<USERNAME>\\AppData\\Local\\Programs\\Git-new\\git-bash.exe" --store-taskbar-properties -- /usr/bin/bash --login -i
```

Maybe the reason for this would be that the new instance - when called from the icon - will always use the command line you quoted?

If that'd the case - the AppID will be the one who causes this issue. I never dealt with this before - so I don't have a clue how Windows internally handles that AppID - and who is supposed to take care for a possible cleanup. Anything else I could try?

**Comment by orgi** [comment]
Ok, I found the following in the MinTTY documentation:
> Warning: Using this option for a mintty window started from a Windows shortcut (desktop, taskbar, start menu) may cause trouble with taskbar grouping behaviour. If you need to do that, the shortcut itself should also get attached with the same AppId.
> 
> Note: Since 2.9.6, if mintty is started via a Windows shortcut which has its own AppID, it is reused for the new mintty window in order to achieve proper taskbar icon grouping. This takes precedence over an explicit setting of the AppID option.
>
> Explanation: Note that Windows shortcut files have their own AppID. Hence, if an AppID is specified in the mintty settings, but not on a taskbar-pinned shortcut for invoking mintty, clicking the pinned shortcut will result in a separate taskbar item for the new mintty window, rather than being grouped with the shortcut.
>
> Hint: To avoid AppID inconsistence and thus ungrouped taskbar icons, the shortcut’s AppID should to be set to the same string as the mintty AppID, which can be done using the winappid utility available in the mintty utils repository https://github.com/mintty/utils . As noted above, since mintty 2.9.6, the mintty AppID does not need to be set anymore in this case.

Not sure how to fix it, though...

**Comment by orgi** [comment]
Can you point me to the documentation about how to create the MinTTY binary? That way I could play around with different AppIDs.

**Comment by rimrul** [comment]
Apparently Windows expects the relaunch details for an application not to change once it's been pinned. There are workarounds to [change them for an existing appid](https://stackoverflow.com/a/28388958), though.

**Comment by rimrul** [comment]
>So maybe git bash should use a new AppID for every new installation?

Maybe some sort of hash of the installation directory?

**Comment by orgi** [comment]
@rimrul Thanks for the hint.

Now I got a workaround:
After removing the respective old shortcut - and its folder in 
```
C:\Users\<username>\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\ImplicitAppShortcuts
```

**Comment by dscho** [comment]
Closing as stale.
