### ISSUE TITLE
Git Credential Manager Core missing in ARM64 libexec folder

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/git#3015]
The final thing I'm missing in [the PortableGit package](https://github.com/git-for-windows/git/pull/2586#issuecomment-770292710) for ARM64 is the Git Credential Manager Core. Because of this, when doing operations like `git push` from within a `cmd`/`powershell` terminal, results in:

```
PS C:\repos\test> git push
Username for 'https://github.com':
```

Notice the difference in the amount of items in the `arm64/libexec` vs `mingw32/libexec`:

![image](https://user-images.githubusercontent.com/17739158/106590528-7c771c00-654d-11eb-88f5-34e9c8ef87d7.png)

I found [a reference](https://github.com/git-for-windows/build-extra/blob/afc620b574e003599c9b9dd2e87d3065d76f0d46/please.sh#L2492-L2521) to `git-credential-manager-core` in `please.sh`, but not entirely sure where in the whole build process it is invoked. Could someone point me in the right direction as to where this is added to `libexec`? We should be able to use the `gcmcore-win-x86` (x86) version on ARM because it can leverage 32-bit emulation.

Thanks in advance!

**Comment by rimrul** [comment]
It gets added to libexec [here](https://github.com/git-for-windows/build-extra/blob/main/mingw-w64-git-credential-manager-core/PKGBUILD#L25-L30)

**Comment by dscho** [comment]
> I found [a reference](https://github.com/git-for-windows/build-extra/blob/afc620b574e003599c9b9dd2e87d3065d76f0d46/please.sh#L2492-L2521) to `git-credential-manager-core` in `please.sh`, but not entirely sure where in the whole build process it is invoked.

Right, the entire process _is_ a bit complex.

As @rimrul pointed out, Git Credential Manager Core is built as  separate Pacman package. (In reality, it is actually not built, but the pre-built binaries are copied from https://github.com/microsoft/Git-Credential-Manager-Core/releases.

Since there is no ARM64 support in MSYS2 yet, it would be relatively tough to provide `mingw-w64-git-credential-manager-core` packages for that architecture.

One thing we could easily do as a work-around for ARM64, though, would be to drop a shell script into `/mingw32/bin/git-credential-manager-core` which would read like this:

```sh
#!/bin/sh

exec /mingw32/libexec/git-core/git-credential-manager-core.exe "$@"
```

**Comment by dennisameling** [comment]
@dscho I can confirm that approach works 👍🏼  had to run `git-credential-manager-core configure` in Bash and then it set my `.gitconfig` to `helper = C:/Program\\ Files\\ \\(x86)\\)/Git/mingw32/libexec/git-core/git-credential-manager-core.exe`.

Would it make sense to provide a PR against `build-extra` which adds this Shell script in the [`PKGBUILD/package()`](https://github.com/git-for-windows/build-extra/blob/main/mingw-w64-git-credential-manager-core/PKGBUILD) script?

**Comment by dscho** [comment]
I'd rather generate it, to be honest. It's only a workaround until we get a proper solution.

**Comment by dennisameling** [comment]
What do you mean by `generate it`, where would we do that? In the `PKGBUILD` or in `please.sh`? 😊

**Comment by dscho** [comment]
Hmm. I thought we could generate it in `installer/release.sh`, but you're right: we _also_ need it in the other `*/release.sh`. Hmpf.

But I _really_ don't want it in non-ARM64 artifacts... or for that matter, in the SDKs.

**Comment by dennisameling** [comment]
What about we add it to `please.sh` in the `--include-arm64-artifacts` section? That way, it'll only be included when an ARM64 build is requested, plus it applies to all `*/release.sh` scripts 🚀 

https://github.com/git-for-windows/build-extra/blob/3e9f5d8030c2fa775bcd8db1ace0c29b0534211b/please.sh#L4824-L4826

**Comment by dscho** [comment]
> What about we add it to `please.sh` in the `--include-arm64-artifacts` section? That way, it'll only be included when an ARM64 build is requested, plus it applies to all `*/release.sh` scripts 🚀

I think that could work, if we put the script into the provided directory's `/bin/` subdirectory.
