### ISSUE TITLE
Unkillable git-rev-parse.exe processes

### ISSUE THREAD

**Issue by insin** [git-for-windows/git#302]
Git 2.5.0, Windows 7 Enterprise, 32 bit.

If I run `git clone` or `git gc` it hangs whichever command prompt I've run it from and I end up with an unkillable `git-rev-parse.exe` process - End Process and `taskkill /pid ... /f` do nothing to it.

**Comment by dscho** [comment]
When I run `git clone` and hit Ctrl+C, it stops. Do you have any more clues how I might reproduce the problem here?

**Comment by dscho** [comment]
@insin anything?
