### ISSUE TITLE
The argument "--recurse-submodules=no" when doing "fetch --all" is not passed to the following commands

### ISSUE THREAD

**Issue by DomLatr** [git-for-windows/git#3027]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 
```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows 10.0.18363
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
GIT_TRACE2=1 git fetch --all --recurse-submodules=no
```
 - What did you expect to occur after running these commands?
 
I expected the submodules to **not** be fetched and to see this command from the Trace:
```
git fetch --append --no-auto-gc --recurse-submodules=no --no-write-commit-graph origin
```

 - What actually happened instead?

The command shown in the Trace was the following and the submodules were fetched later on.
```
git fetch --append --no-auto-gc --no-write-commit-graph origin
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Here are some repro steps with a repository on GitHub.

1. Clone with git bash https://github.com/DomLatr/RepoWithSubmodule
2.  In the repo, run the following command : "git submodule update --init"
3. In the file .git\packed-refs, remove the line "f5165dbd5441d97e7fba6b55917a4c7865e5d7ee refs/remotes/origin/change-submodule" to simulate that the repository does not have the branch.
3a. If the line is not present in "packed-refs" or is straight up absent, you can remove the file ".git\refs\remotes\origin\change-submodule", that will have the same result.
4. Run the command : "GIT_TRACE2=1 git fetch --all --recurse-submodules=no"
5. Notice that the submodules **are** fetched since it uses "--recurse-submodules=on-demand" instead

It happens in a repository with submodules that needs would need to be fetched. The value of "fetch.recurseSubmodules" by default is "on-demand", which translate to "yes" when you need to fetch a new SHA that you don't have locally. I tried the 3 commandline possibilities with --recurse-submodules and GIT_TRACE2=1. Here is the following results:
```
GIT_TRACE2=1 git fetch --all --recurse-submodules=no
=> git fetch --append --no-auto-gc --no-write-commit-graph origin
```
```
GIT_TRACE2=1 git fetch --all --recurse-submodules=on-demand   
=> git fetch --append --no-auto-gc --no-write-commit-graph --recurse-submodules=on-demand origin
```
```
GIT_TRACE2=1 git fetch --all --recurse-submodules=yes
=> git fetch --append --no-auto-gc --no-write-commit-graph --recurse-submodules origin
```

Since the  "--recurse-submodules=no" is not passed to the following commands that are ran automatically, it will use the default value of "--recuse-submodules=on-demand", which will end up fetching the submodules in this case.

**Comment by dscho** [comment]
Could you verify (e.g. via WSL) that this is a Windows-specific bug?

**Comment by phil-blain** [comment]
Then it's a general Git issue, which you could submit to the Git mailing list, see https://git-scm.com/community

**Comment by dscho** [comment]
Indeed, then this is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
