### ISSUE TITLE
Implement paging when using Windows PowerShell

### ISSUE THREAD

**Issue by jethas-bennettjones** [git-for-windows/git#3028]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows [Version 10.0.19042.746]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

None of these above files exists

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am SSH-ing from a Windows machine into another Windows machine, and this happens both locally and remotely

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

When using `git add -p` to view changes to files, if a long file has had significant changes that can't be broken up into hunks, then the file's content scrolls off the top of the page. I have a vague recollection that the Linux implementation of git pages the response in this situation.

 - What did you expect to occur after running these commands?

A paged response, rather than needing to scroll to see the change.

 - What actually happened instead?

The entire hunk is output to the screen at once, requiring scrolling up and down to view all of the changes.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by rimrul** [comment]
I've tested git 2.17.1 on Linux (local), git 2.20.0 on Linux (SSH) and git 2.30.0.452.gfb7fa4a1fd on Linux (local) and they all behave the same as the Git forWindows 2.30.0(2) I compared them to.

**Comment by dscho** [comment]
Maybe a difference between built-in vs scripted `git add -p`?

**Comment by rimrul** [comment]
I don't think builtin interactive add was in 2.17. So that linux test should be scripted interactive add.

My Linux build from current master was explicitly tested with builtin add. 

They behaved the same.
