### ISSUE TITLE
RStudio won't start up after installing Git - windows 10 - 64 bit

### ISSUE THREAD

**Issue by BarbiMarkus** [git-for-windows/git#3039]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
**64**
```
$ git --version --build-options

** cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Versión 10.0.19041.804]
(c) 2019 Microsoft Corporation. Todos los derechos reservados.**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: Nano
Custom Editor Path: 
Default Branch Option:  
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** None for now, as I have just installed GIT and haven't done anything with it yet **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** I was trying to open a new project in R Studio: 
File\New Project\Version Control\Git
Here I got the error message Git is not connected to R studio- please restart R studio
So I closed R Studio and when restarted the attached screetshots show what happened - nothing - R Studio wont start up **
```
 - What did you expect to occur after running these commands?

** R studio shoot start but it wont**

 - What actually happened instead?

** R Studio is showing a grey panel and only menu comes up**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** I was trying to create a repository when this happened, so there is none created yet **

![Error grey](https://user-images.githubusercontent.com/78806989/107648678-e5147600-6c7c-11eb-959a-6e0197d9a18a.jpg)

WHen I do right click and press reload this happens:

![error R Studio](https://user-images.githubusercontent.com/78806989/107648984-450b1c80-6c7d-11eb-8e11-aa04853a127d.jpg)

I am DESPERATE as I am doing an online course of data science on EDX platform with HarvardX and cannot continue the course because of this issue
Thanks you very much for looking into this issue!
Cheers
Barbara

**Comment by rimrul** [comment]
Not a Git for Windows issue.

Contact the Rstudio support to see why Rstudio doesn't work as expected.
