### ISSUE TITLE
Python 2 text encoding compatibility issue with pseudo console support

### ISSUE THREAD

**Issue by Vynce** [git-for-windows/git#3043]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.804]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Python 2.7.18 64-bit installed for all users.
https://www.python.org/ftp/python/2.7.18/python-2.7.18.amd64.msi

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash shortcut from the Start Menu.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ /c/Python27/python -c 'import sys; print "works".decode(sys.stdout.encoding)'
```
 - What did you expect to occur after running these commands?

```
$ /c/Python27/python -c 'import sys; print "works".decode(sys.stdout.encoding)'
works
```

 - What actually happened instead?

```
$ /c/Python27/python -c 'import sys; print "works".decode(sys.stdout.encoding)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
LookupError: unknown encoding: cp65001
```

This issue only occurs in MinTTY with the experimental pseudo console support enabled.

**Comment by Vynce** [comment]
This appears to be a Python<3.6 issue and there may not be much that can be done about it in MinTTY (?).
https://bugs.python.org/issue1602
https://bugs.python.org/issue6058
https://stackoverflow.com/questions/878972/windows-cmd-encoding-change-causes-python-crash
https://stackoverflow.com/questions/35176270/python-2-7-lookuperror-unknown-encoding-cp65001

**Comment by dscho** [comment]
Isn't Python 2 _waaaaay_ past its end of life?

**Comment by Vynce** [comment]
This issue also affects Python 3.5... but that's also end-of-life 🙂.
