### ISSUE TITLE
rm: cannot remove: Invalid argument in docker volume folder

### ISSUE THREAD

**Issue by ZFail** [git-for-windows/git#3044]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1757]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Dockerfle reproducer
```Dockerfile
FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN powershell iex(iwr -useb https://chocolatey.org/install.ps1)
RUN choco install git -y --params "/GitAndUnixToolsOnPath"
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
docker build -t git-bin-test .
docker run -it --rm -v c:\test -w c:\test git-bin-test
c:\test>touch a
c:\test>ls -la a
-rw-r--r-- 1 ContainerAdministrator 380929 0 Feb 13 10:58 a
c:\test>rm a
rm: cannot remove 'a': Invalid argument
c:\test>unlink a
unlink: cannot unlink 'a': Invalid argument
c:\test>mv a c:\
mv: cannot remove 'a': Invalid argument
c:\test>where rm
C:\Program Files\Git\usr\bin\rm.exe
```
 - What did you expect to occur after running these commands?

rm should delete the file

 - What actually happened instead?

rm returns an error

**Comment by dscho** [comment]
Does that also happen with a regular [MSYS2](https://msys2.github.io/) installation? If so, please [report it with that project)(https://github.com/msys2/MSYS2-packages/issues/new).

**Comment by ZFail** [comment]
Report to msys2: https://github.com/msys2/MSYS2-packages/issues/2342

**Comment by dscho** [comment]
> Report to msys2: [msys2/MSYS2-packages#2342](https://github.com/msys2/MSYS2-packages/issues/2342)

Excellent. Let's continue there.
