### ISSUE TITLE
Suggestion: Include GNU make

### ISSUE THREAD

**Issue by christianhujer** [git-for-windows/git#3046]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

make (specifically GNU make) is a popular build and automation tool. A lot of teams and projects use it as a glue between their CI/CD pipeline and the actual project build system (which then might be maven, gradle, sbt, go build, or whatever). The lives of a lot of teams would get easier if make would not be treated as a project-specific build system but part of the common configuration management infrastructure and thus become part of git for Windows.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.804]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option: trunk
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
$ make
bash: make: command not found
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

(git) bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ make
bash: make: command not found
```
 - What did you expect to occur after running these commands?

I expected `make` to be found.

 - What actually happened instead?

```
$ make
bash: make: command not found
```

**Comment by dscho** [comment]
You're looking for [MSYS2](https://msys2.github.io/). `make` is not required to run Git commands, so it has no place in Git for Windows.

Besides, even if you say you only want GNU make to be included, that's hardly the end of the story. If we _did_ include it and you ran `make`, you would most likely see `gcc: command not found` or something like that. So we also would have to include GCC. Oh, and bison. And probably also all the gettext tools. What the hay, let's include autoconf and automake, too. And of course libtool!

And before you know it, the Git for Windows installer grows from ~45 megabyte to ~450 megabyte in size.

The backlash would be swift, and it would all hit me, the Git for Windows maintainer. Therefore I will close this ticket without fulfilling your wish.

Having said that, I think you really can fulfill your wish yourself by switching to [MSYS2](https://msys2.github.io/): it comes with a proper package management system, Pacman. You can easily install packages you're missing via `pacman -Sy <package>`. And if a package that you want isn't provided by MSYS2, well, you simply contribute a package definition (which gives you a fantastic opportunity to give back).

**Comment by christianhujer** [comment]
I get the point, but I still don't agree, I feel the request is misunderstood. I'm really not looking for MSYS2 or similar things (like Cygwin). Every single project I'm working on faces the following situation:
• It builds on Linux just fine.
• It builds on Mac OS just fine.
• It doesn't build on Windows or requires extra work because of exactly one missing binary: `make`.

Git already contains far more than is required to just run git. The /bin directory is full of useful stuff like sed and awk. `make` is just a wrapper around bash which has a lot of defaults and behaviors that make `make` more attractive than plain `sh` or `bash` for CI/CD and DevOps automation.

The other thing is the fact that MSYS2 has a package manager is not only a benefit, it's also a drawback. In restricted environments, using something like MSYS2 requires far more IT support to setup proxies for the package manager than just git, which can be provided by IT support as-is.

My request is also, let me be clear, not coming from a C background. Not a single project in which I encounter this issue is a C project. So, no request for gcc, automake, autoconf, yacc, nasm, whatever. All projects in which I'm missing make for Windows and face distribution issues (which I usually solve by smuggling a MinGW GNU make into a ./bin directory) are Java, Kotlin, Golang, Python, Node or whatever projects, often mixed language.

**Comment by dscho** [comment]
> All projects in which I'm missing make for Windows and face distribution issues (which I usually solve by smuggling a MinGW GNU make into a ./bin directory) are Java, Kotlin, Golang, Python, Node or whatever projects, often mixed language.

By that reasoning, we would _also_ have to include a JDK, Go, Python and Node in Git for Windows. (And that is ignoring the fact that Java projects usually use Maven or Gradle instead of GNU make, Python uses `setuptools` and Node uses `npm` or `yarn`.)

That's not the purpose of Git for Windows. It is supposed to be _part_ of your development tools, not the delivery vehicle for all of them. You are asking a whole lot of one overworked maintainer here.

**Comment by christianhujer** [comment]
If I may quote myself from the initial request:
> A lot of teams and projects use it as a glue between their CI/CD pipeline and the actual project build system (which then might be maven, gradle, sbt, go build, or whatever).
It is not about projects which use `make` as the primary build system. It is about projects which use `make` instead of `bash` as the glue piece between the CI/CD pipeline and the actual build system because `make` is much more fit for the purpose (`set -e` is implied, and a concise structure supporting dependencies is part of the syntax, to name just a few).

I have, in fact, waited for years before making the request. For years, I have filled in the gaps of Git for Windows by providing GNU make from Cygwin or MinGW to teams.

If all that you're asking for is support for an overworked maintainer, I'm ready to commit to supporting this feature from the initial PR through many years of maintenance, keeping GNU make within Git for Windows uptodate. Because that alone would already be less effort for me than all the other options that I'm currently implementing with the various teams that I'm supporting.

**Comment by dscho** [comment]
I don't buy this argument.

If you need `make` as glue between CI/CD, use MSYS2. It is already installed in AppVeyor, Azure Pipelines and GitHub Actions (and I'd wager in many other CI/CD systems).

It is not worth the additional maintenance burden (new versions, anyone?) nor the payload for regular Git for Windows users who do not need `make` _at all_. You are asking for Git for Windows to be used improperly as a delivery vehicle of GNU make, and that's just not the way to go forward. If you need `make` in CI/CD, install it there. If you need it in your projects, install it. If you need Git for Windows, install it.

Again, nowhere in Git is `make` required. It would improper to bundle it.
