### ISSUE TITLE
git failes with symlinked/hardlinked directory inside a repo

### ISSUE THREAD

**Issue by kxrob** [git-for-windows/git#3051]
Reproduce Problem:

```
clone ...  prj
cd prj 
# swap in subdir which was previously laborously file synced (e.g. with small changes):
rename subdir _subdir_org

mklink [/D | /J]  subdir   path/to/testrun_subdir
git status
```
( `/D` for symlink dir requires admin shell, slower)

-> Ok with hardlinked junction directory, but with symlinked dir, all files in subdir are seen as gone even with CWD below though they are there!

```
cd subdir
git status
```

-> Both variants fail terribly meanwhile! :

`fatal: not a git repository (or any of the parent directories): .git`

With hardlinked dirs it worked formerly - so it got worse or this route is completely dead now!?
Could at least hardlink dirs be made working again - as it already did and as it does with hard linked files?

-- 
Git - nothing special, same everywhere:
git version 2.30.0.windows.2 
cpu: x86_64
built from commit: f8cbc844b81bf6b9e72178bbe891a86c8bf5e9e7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

**Comment by dscho** [comment]
Closing as stale.
