### ISSUE TITLE
first character of the branch name converted to uppercase automatically

### ISSUE THREAD

**Issue by pratikkulshreshth** [git-for-windows/git#3057]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.804]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Atom
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

``No``

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Both CMD and PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git checkout -b task/3293
git branch
```
 - What did you expect to occur after running these commands?

Branch name should be task/3293 in the branch list

 - What actually happened instead?

Branch name is Task/3293 (t is in uppercase)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

a private repo

**Comment by pratikkulshreshth** [comment]
I addition to the issue description:

the problem occurs specifically with these branch name. For Eg. these branch names works perfectly fine:
``sub/3434``
``bug/83283``

**Comment by dscho** [comment]
> git checkout -b task/3293
> git branch

This MCVE is not verifiable, as it misses a repository to work with.

My _suspicion_ is that there are _already_ branches whose names start with `Task/`: branch names are stored as files, and on Windows (using NTFS at least), the file names are case-insensitive. Which means that if a folder `Task` exists and you write `tasks\2323`, that won't change the case of the `Task` folder, and the path will actually read `Task\2323`.

**Comment by pratikkulshreshth** [comment]
> 
> 
> > git checkout -b task/3293
> > git branch
> 
> This MCVE is not verifiable, as it misses a repository to work with.
> 
> My _suspicion_ is that there are _already_ branches whose names start with `Task/`: branch names are stored as files, and on Windows (using NTFS at least), the file names are case-insensitive. Which means that if a folder `Task` exists and you write `tasks\2323`, that won't change the case of the `Task` folder, and the path will actually read `Task\2323`.

This was exactly by usecase. I deleted all the branches with **Task/** prefix and retried. And it worked. Thanks @dscho
