### ISSUE TITLE
In the interactive mode of "git clean", "ask each" is not working 

### ISSUE THREAD

**Issue by kkurkiewicz** [git-for-windows/git#3068]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1379]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I think not.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
> mkdir test
> cd test
> git init
> git config --local clean.requireForce false    (Optional, see below)
> echo *.test>> .gitignore
> touch test.test
> git clean -X -i
Would remove the following item:
  test.test
*** Commands ***
    1: clean                2: filter by pattern    3: select by numbers
    4: ask each             5: quit                 6: help
What now> a
Remove test.test [y/N]? y
> 
```
 - What did you expect to occur after running these commands?

Remove the file test.test.

 - What actually happened instead?

Nothing (the command just quit reverting to the original ">" command prompt, seemingly without performing any action).
I tried changing the default "requireForce" behaviour to see if the problem might be caused by "--interactive" not implying "--force" but it didn't help. Running "git clean -X -f" works just fine.

**Comment by dscho** [comment]
Thank you for your report!

I did not manage to reproduce the problem, though:

```console
me@work MINGW64 ~
$ git version
git version 2.31.0.rc0.windows.1

me@work MINGW64 ~
$ git init repros/clean-i-3068
Initialized empty Git repository in C:/Users/me/repros/clean-i-3068/.git/

me@work MINGW64 ~
$ cd repros/clean-i-3068

me@work MINGW64 ~/repros/clean-i-3068 (main)
$ echo *.test>> .gitignore

me@work MINGW64 ~/repros/clean-i-3068 (main)
$ touch test.test

me@work MINGW64 ~/repros/clean-i-3068 (main)
$ git clean -X -i
Would remove the following item:
  test.test
*** Commands ***
    1: clean                2: filter by pattern    3: select by numbers
    4: ask each             5: quit                 6: help
What now> a
Remove test.test [y/N]? y
Removing test.test

me@work MINGW64 ~/repros/clean-i-3068 (main)
$ ls -la
total 49
drwxr-xr-x 1 me 4096 0 Mar  1 11:36 ./
drwxr-xr-x 1 me 4096 0 Mar  1 11:35 ../
drwxr-xr-x 1 me 4096 0 Mar  1 11:35 .git/
-rw-r--r-- 1 me 4096 7 Mar  1 11:36 .gitignore
```

Maybe an upgrade would help in your case? FWIW the latest pre-release (v2.31.0-rc0) should be plenty stable enough to use for regular work.

**Comment by kkurkiewicz** [comment]
@dscho I upgraded to the latest non-insiders version (2.30.1.windows.1). The problem disappeared.

**Comment by dscho** [comment]
Great!
