### ISSUE TITLE
envsubst.exe doesn't respect locale

### ISSUE THREAD

**Issue by linde12** [git-for-windows/git#3070]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 2.30.1 64 bit, same for older versions

```
$ git --version --build-options

git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1757]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Swedish locale on Windows - might explain why i'm getting ISO 8859-1?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
> cat input
< hej ${LALA}
> locale
< LANG=C.UTF-8
< LC_CTYPE="C.UTF-8"
< LC_NUMERIC="C.UTF-8"
< LC_TIME="C.UTF-8"
< LC_COLLATE="C.UTF-8"
< LC_MONETARY="C.UTF-8"
< LC_MESSAGES="C.UTF-8"
< LC_ALL=

# envsubst uses iso-8859-1 character encoding instead of the configured utf-8
> LALA=åäö envsubst < input > output && file -i output
< output: text/plain; charset=iso-8859-1

# echo works just fine
> echo "åäö" > output2 && file -i output2
< output2: text/plain; charset=utf-8

```
 - What did you expect to occur after running these commands?

I expect envsubst to respect the configured locale and produce UTF-8.

 - What actually happened instead?

envsubst encoded characters as ISO 8859-1

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

-

Probably not all that related to git bash on Windows, but it affects "Git bash" and i'm not sure where to turn. I tried installing "Cygwin" and using envsubst.exe from there which worked just fine. I understand that Git bash uses MinGW, but again i'm not entirely sure where to turn - please feel free to close and maybe give me a hint if you don't want it on your tracker. 😄

**Comment by dscho** [comment]
Welcome to the Git for Windows project!

When I call this in a [Git for Windows SDK](https://gitforwindows.org/#download-sdk):

```console
$ pacman -Qo $(which envsubst.exe)
/mingw64/bin/envsubst.exe is owned by mingw-w64-x86_64-gettext 0.19.8.1-10
```

It tells me that this file is shipped via the package `mingw-w64-gettext`, which is maintained as part of https://github.com/msys2/MINGW-packages. Maybe report the bug there?

**Comment by linde12** [comment]
Thank you @dscho, i will report it there as well. You can close the issue here if you want!
