### ISSUE TITLE
ARM64: cannot read/write system gitconfig 

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/git#3071]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

**This is not an urgent issue, since ARM64 Windows is only in the testing phase right now, and no official builds have been published yet.**

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

ARM64 Windows test build: https://github.com/dscho/git/actions/runs/597692856

```
$ git --version --build-options
git version 2.30.1.GIT
cpu: AMD64
no commit associated with this build
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 10 ARM64
Microsoft Windows [Version 10.0.19042.804]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

ARM64 😉 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
denni@DESKTOP-8HTP3NV ARM64 /c/repos
$ git config --list

denni@DESKTOP-8HTP3NV ARM64 /c/repos
$ git config --system http.sslbackend schannel
error: could not lock config file C:/Program Files (x86)/Git/arm64/etc/gitconfig: No such file or directory
```
 - What did you expect to occur after running these commands?

`git config --list` should show the Git configuration.

 - What actually happened instead?

`git config --list` doesn't return anything. However, after I copied `/etc/gitconfig` to `/arm64/etc/gitconfig`, `git config --list` started showing the correct output:

```
denni@DESKTOP-8HTP3NV ARM64 /c/repos
$ git config --list
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
```

... so the ARM64 Git for Windows (Bash at least) looks for `gitconfig` in the wrong folder.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
This is intentional. The system config is located within `C:\Program Files*`, and therefore only writable if you run Git in elevated mode (you can, for example, hit the Windows key, then type "Git Bash" and then hit <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd>).

**Comment by dscho** [comment]
Oh, and please note that it is not _really_ intended for users to write stuff into the system config, that config really is "owned" by Git for Windows. Use `git config --global` (i.e. `$HOME/.gitconfig`) to configure things instead.

**Comment by dennisameling** [comment]
That's my bad, sorry, but `git config --global` doesn't work either:

```
$ git config --global
C:/Program Files (x86)/Git/arm64/bin/git.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

maybe that's why `--list` doesn't return anything as well! Windows logs refer to `msvcrt.dll` - does this mean we'll need to link Git ARM64 statically instead? Happy to close this issue and create a new one specifically for this issue if that helps. Currently, running anything `git` related from `cmd` just crashes... Something must have changed recently that broke this 😞 

```
Naam van toepassing met fout: git.exe, versie: 2.30.0.2, tijdstempel: 0x60366296
Naam van module met fout: msvcrt.dll, versie: 7.0.19041.789, tijdstempel: 0xc68c05ae
Uitzonderingscode: 0xc0000005
Foutmarge: 0x000d7dd8
Id van proces met fout: 0x510c
Starttijd van toepassing met fout: 0x01d70faef14328b2
Pad naar toepassing met fout: C:\Program Files (x86)\Git\cmd\git.exe
Pad naar module met fout: C:\WINDOWS\System32\msvcrt.dll
Rapport-id: a47f5bcf-a83d-4aa3-b19f-1c6d9d7478ae
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 
```

**Comment by dennisameling** [comment]
Bingo: zlib1.dll and iconv-2.dll are missing:

![image](https://user-images.githubusercontent.com/17739158/109721221-5f188a80-7bab-11eb-97df-b86add052805.png)

![image](https://user-images.githubusercontent.com/17739158/109721236-63dd3e80-7bab-11eb-9946-e7917838d307.png)

**Comment by dennisameling** [comment]
The DLLs are included in the `portable-arm64` artifacts:

![image](https://user-images.githubusercontent.com/17739158/109721485-b3236f00-7bab-11eb-9db1-1f19ff05016b.png)

But not in the installer apparently:

**Comment by dennisameling** [comment]
Got the issue with missing DLLs fixed by [working with a more recent build](https://github.com/dscho/git/actions/runs/597692856), sorry for the confusion.

The issue with the Git config is still present though. Please consider these differences:

x64 Windows machine with 32-bit Git for Windows (used Windows Sandbox to ensure clean environment):

```
C:\Users\WDAGUtilityAccount>git config --list --global
fatal: unable to read config file 'C:/Users/WDAGUtilityAccount/.gitconfig': No such file or directory

C:\Users\WDAGUtilityAccount>git config --list --system
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor=nano.exe
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
```

ARM64 Windows machine with ARM64 Git for Windows installed (build: https://github.com/dscho/git/actions/runs/597692856)

```
(todo paste here)
```

**Comment by dscho** [comment]
> C:\Users\WDAGUtilityAccount>git config --list --global
> fatal: unable to read config file 'C:/Users/WDAGUtilityAccount/.gitconfig': No such file or directory

That looks correct. If there is no `~/.gitconfig`, that command will fail, while `git config --list` won't.

> denni@DESKTOP-8HTP3NV ARM64 /
> $ git config --system --list
> fatal: unable to read config file 'C:/Program Files (x86)/Git/arm64/etc/gitconfig': No such file or directory

That does not look correct. I _think_ this because the CMake-based build is missing this:https://github.com/git-for-windows/git/blob/c1778565869b74b2c0ac225802a53f7b8a4133ec/config.mak.uname#L436-L440

This will most likely have to be implemented in one form or another here: https://github.com/git-for-windows/git/blob/c1778565869b74b2c0ac225802a53f7b8a4133ec/contrib/buildsystems/CMakeLists.txt#L208

**Comment by dennisameling** [comment]
Alright, got that working, curious to hear what you think of my approach: https://github.com/git-for-windows/git/pull/3078
