### ISSUE TITLE
M1 MBP Big Sur 11.2.2 Updated git error：zsh killed git

### ISSUE THREAD

**Issue by liuyi2614** [git-for-windows/git#3081]
I update my m1 mbp to Big Sur 11.2.2 in this week, after that, I develop my code work and use git in terminal as usual. And I found terminal feedback an error: zsh killed git.

I tried to use command brew reinstall git and install other command tool like iterm2 and also like this. apple service call give useless solution.

Now my code can not submit to github, I trans my code to my i5 mbp Big Sur 11.2.2 to submit(it can be worked).

So someone can help?

<img width="272" alt="20210305-163246" src="https://user-images.githubusercontent.com/17721362/110088993-8a2ff380-7dd0-11eb-9f89-95905dca19e8.png">

**Comment by rimrul** [comment]
This is the Git **for Windows** Project. Sorry, but thos is the wrong address for issues on macOS.

**Comment by dscho** [comment]
@liuyi2614 here are tips how to report bugs in upstream Git: https://git-scm.com/community
