### ISSUE TITLE
Git for Windows branch name contain double quotes

### ISSUE THREAD

**Issue by wtask** [git-for-windows/git#3084]
We have new developer who creates the branches like this
```
bla-bla-bla_again_bla_bla_bla_"something_special"
```
So if I try to fetch that branch under windows, I'll get an error (unable to update local ref) related to lock file creation due to double quotes is a part of branch name and also the lock file name under Windows.

`git version 2.30.1.windows.1`

**Comment by PhilipOakley** [comment]
I guess the developer is working under Linux.

The double quote is not a valid character for a filename on Windows, so when Git tries to create the branch-file 'implementation detail' of the same name, Windows won't allow it, so Git fails to create the local branch of that same name.

You may need to implement some "Windows specific" policies for any project that requires to be Windows compatible (reserved file names, reserved characters in branches, case sensitivity, etc).

E.g. https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3 - first google hit.

**Comment by wtask** [comment]
I think git-for-**windows** should avoid using branch name as is, without filtering special chars or converting into hash

**Comment by PhilipOakley** [comment]
> I think git-for-**windows** should avoid using branch name as is, without filtering special chars or converting into hash

It sort of does. It is Git itself that uses the branch name as a filename as a matter of implementation and referential detail, so... 

Maybe look up refspecs, so that you can rename things as the pass from remote server to local repository.

**Comment by PhilipOakley** [comment]
> Maybe look up refspecs, so that you can rename things as the pass from remote server to local repository.

The latest versions of Git have negative refspecs available to deselect the specific refnames that have 'bad characters' in them. See VonC's answer at https://stackoverflow.com/questions/44333437/git-what-is-refspec/44333810

**Comment by dscho** [comment]
Closing as stale.
