### ISSUE TITLE
Make an MSys2 package for the extra files we ship with Git for Windows

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#31]
There are a bunch of really useful files shipped with *Git for Windows*, such as a sensible default `gitconfig`, a `vimrc`, etc. To make it easy to bundle them into a Portable Application/installer, we should make these files available as a package.

To make things even nicer for users – who might want to update their packages every once in a while – we could write out default versions of the files in a `post_install`/`post_upgrade` script *only* if the user does not have these files yet, but leave the (possibly modified) existing files alone.

**Comment by nalla** [comment]
I guess that should be a `msys2` package and not a `mingw` one, right?

**Comment by dscho** [comment]
@nalla Yeah, I think you're right. And it should be of `any` architecture. Question then is: where to put it. We only have architecture-dependent Pacman repositories...

**Comment by nalla** [comment]
@dscho what about a `dl.bintray.com/git-for-windows/pacman/msys2/any` repository?

**Comment by dscho** [comment]
Good idea. @sschuberth what do you think?

**Comment by sschuberth** [comment]
Fine with me.

**Comment by nalla** [comment]
What I tried so far was to clone `MSYS2-packages`, added a new subdirectory `git-for-windows-extra-files`. Added a `PKGBUILD` (https://gist.github.com/nalla/fe43017af6aa0cf401ad) and ran `makepkg -s`. Maybe someone can give me feedback if this is at least the right direction. This produced `git-for-windows-extra-files-1.0.20.77ed12e-1-any.pkg.tar.xz`

**Comment by dscho** [comment]
> Maybe someone can give me feedback if this is at least the right direction.

Absolutely!

**Comment by dscho** [comment]
One suggestion: use the package name `git-extra` instead. It is shorter...

**Comment by nalla** [comment]
Jeah, the name was just a starting point. I won't be able to continue till thurdsday. Hope thats all right.

**Comment by dscho** [comment]
@nalla No worries! The other tickets will keep me busy ;-)

**Comment by nalla** [comment]
I added https://github.com/nalla/MSYS2-packages/tree/git-extra if someone wants to participate.

**Comment by dscho** [comment]
@nalla thanks!

**Comment by nalla** [comment]
I was thinking about the way the package should work. Either in a rather static way or maybe we could add some dynamics.
I see two reasonable options. Either you add a new file to the build-extra repo and then maintain the `PKGBUILD` file or the repo has some sort of mapping file the `PKGBUILD` is parsing.
What do you think?

**Comment by dscho** [comment]
I think it would make sense for `build-extra` to sprout a new `install-extra.sh` script (accepting a destination top-level directory) that is essentially [what the `package()` function executes now](https://github.com/git-for-windows/MSYS2-packages/blob/0b38d0711ceba92df7bd1e8650f6effa7593ec37/git-extra/PKGBUILD#L33-L37).

But we can do that incrementally, by developing the code in `PKGBUILD` first and then moving it into the `build-extra` repository (IMHO it should live in the latter repository, but developing it is *much* faster as long it is living in the `PKGBUILD` script itself.

**Comment by nalla** [comment]
I have a working version in my [branch](https://github.com/nalla/MSYS2-packages/tree/git-extra). Yo can test this package by running `makepkg-s && pacman -U git-extra-1.0.20.77ed12e-1-any.pkg.tar.xz`. Is this PR-ready in your eyes?

**Comment by nalla** [comment]
I was thinking about the metadata of the package.
```bash
url=''
license=('GPL')
groups=('base')
```
The `git` packages is in the `VCS` group. Should the `git-extra` package be in that group too? The license should correspond with the *Git for Windows* license. `url` could be the GitHub page of *Git for Windows*

**Comment by dscho** [comment]
Well, maybe the URL should point to the GitHub repository directly? The license corresponds to *Git for Windows*' already, and you are right about the group, it is probably better in the `VCS` one.

**Comment by dscho** [comment]
With the merge of git-for-windows/build-extra#8, I declare this ticket closed.
