### ISSUE TITLE
there is an error on Github Desktop..

### ISSUE THREAD

**Issue by jysong-dev** [git-for-windows/git#3101]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64bit

$ git --version --build-options

git version 2.29.2.windows.4
cpu: x86_64
built from commit: 85cdea6673504d3c1a6882efb0d45c427f259644
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows10 64bit

$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1379]
(c) 2019 Microsoft Corporation. All rights reserved.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Github Desktop

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

push origin

 - What did you expect to occur after running these commands?

push to master branch

 - What actually happened instead?

warning: failed to restrict file handles (5)

handle #0: 0000000000000124 (type 3, handle info (1) 0
handle #1: 000000000000024c (type 3, handle info (1) 1
handle #2: 0000000000000940 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

	SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn C:\Users\송지유\AppData\Local\GitHubDesktop\app-2.6.6\resources\app\static\ask-pass-trampoline.bat: Permission denied
fatal: could not read Password for 'https://jysong-dev@github.com': terminal prompts disabled

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/coaslab/modooshop.git

**Comment by dscho** [comment]
@jysong-dev welcome to the Git for Windows project!

This issue seems to be a GitHub Desktop one. Does this help? https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors

**Comment by dscho** [comment]
Closing as stale.
