### ISSUE TITLE
No newline character at end of output for "cat-file -p" command against stash reference

### ISSUE THREAD

**Issue by mundifex** [git-for-windows/git#3102]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.30.2.windows.1
cpu: x86_64
built from commit: 37f0a4afad027cf030747a1ef45537ba86162960
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19042.844]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None I can think of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git show-ref
git cat-file -p <master>;echo FOO
git cat-file -p <stash>;echo FOO
```
 - What did you expect to occur after running these commands?

I expected `FOO` to appear on a new line after the output from _both_ `cat-file  -p` commands.

 - What actually happened instead?

FOO appeared on a new line only after executing `cat-file -p` against the master ref. Against the stash ref, there was no newline at the end of git's output and FOO appeared in-line instead.

```
$ git show-ref
3295f7b18b8c6087b045d427e7d3243af07330aa refs/heads/master
93af06674c05021a70848dabc92dc0471b1d90b1 refs/stash

$ git cat-file -p 3295;echo FOO
tree d87cbcba0e2ede0752bdafc5938da35546803ba5
author John Doe <john.doe@none.invalid> 1615441433 -0600
committer John Doe <john.doe@none.invalid> 1615441433 -0600

Add bar
FOO

$ git cat-file -p 93af;echo FOO
tree efbc17e61e746dad5c834bcb94869ba66b6264f9
parent 3295f7b18b8c6087b045d427e7d3243af07330aa
parent 8765559d574f145fab02aaf6e9dfc0fa0af846db
author John Doe <john.doe@none.invalid> 1615441454 -0600
committer John Doe <john.doe@none.invalid> 1615441454 -0600

WIP on master: 3295f7b Add barFOO

```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None I can provide but setting up your own is fairly simple:

```
mkdir foo
cd foo
git init
touch bar
git add bar
git commit -m "Add bar"
echo foo >> bar
git stash
```

Proceed with `show-ref` and `cat-file -p` commands as detailed in trigger section.

**Comment by dscho** [comment]
Hi @mundifex! While it might look like a bug, this is not actually a bug.

It just so happens that `git stash` [does not append a newline to its commit message](https://github.com/git/git/blob/v2.31.0-rc2/builtin/stash.c#L1228) (it uses `pp_commit_easy()` to render the commit subject ("oneline") of `HEAD`, and this mode [skips that newline](https://github.com/git/git/blob/v2.31.0-rc2/pretty.c#L2014).

At the same time, regular commits' messages are typically written in a text editor that does enforce a newline at the end of the message.

Git is pretty faithful in handling the data users pass to it, including the preservation of a newline at the end of the commit message, or, well, preserving a missing one.
