### ISSUE TITLE
Weird characters in terminal commands output, using Git Bash

### ISSUE THREAD

**Issue by nasko** [git-for-windows/git#3106]
- [x ] I was able to find a closed #2806  issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Note: It's 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.804]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path: 
Default Branch Option: develop
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

It is strange that the output of `git --version` above shows `git version 2.28.0.windows.1`, but I have actually the most recent version of Git for Windows installed: 2.30.2

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I'm using Git-Bash

Terminal Settings:

* Terminal
  * Type: xterm
* Text
  * Locale: en_US
  * Character set: UTF-8
  * Font: Lucida Console

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I'm using [sfdx CLI](https://developer.salesforce.com/tools/sfdxcli) commands to deploy metadata to a Salesforce org.

```
 sfdx force:source:deploy -p force-app/main/default/ -u myOrgAlias --checkonly
```
 - What did you expect to occur after running these commands?

The output of this command consists not only of text, but it also renders a progress bar, using non-letter symbols. Refer to this screenshot:

![git-bash-code-page-65001](https://user-images.githubusercontent.com/283257/110921247-02de0500-8327-11eb-8e8d-bc7901d5b558.png)

 - What actually happened instead?

But unless I type this command in the terminal, prior to executing my SFDX command, I'm seeing weird characters in place of the progress bar symbols. 

```
cmd //c chcp 65001
```

Refer this screenshot:

![git-bash-weird-characters](https://user-images.githubusercontent.com/283257/110921248-03769b80-8327-11eb-82d3-856f2efd88f9.png)

I've noticed that a similar problem is discussed in #2806, but according to the issue page, it should be fixed in v2.29.0. 
Now, this is what confuses me:
* I have the 2.30.2 app version installed
* My `git --version` output is: `2.28.0.windows.1`

... and I'm not sure whether the issue is expected to have been fixed in my installed version of Git Bash.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by nasko** [comment]
I'm not sure if this is a Git-, or Git Bash issue, but since both executables are delivered by git-for-windows, I posted the issue here.

**Comment by dscho** [comment]
> * I have the 2.30.2 app version installed
> * My `git --version` output is: `2.28.0.windows.1`

That's odd. Maybe you have multiple Git installations? The output should be `2.30.2.windows.1`. And upgrading _might_ fix the issue, there had been some work in that area late last year.

**Comment by nasko** [comment]
Yesterday I upgraded my application using: 

```
git update-git-for-windows
```

... because had an older version: 2.14-something. Noticing the #2806 issue, I decided to upgrade in hope that this would fix the problem for me, but to no avail.

**Comment by nasko** [comment]
As to the possibility that I have multiple Git installations:

* No other Git folders are present in neither Program Files, nor Program Files (x86)
* I've checked whether I hadn't installed a git version in the past using Node - none found:

```
$ npm -g list | grep git

```

I can't think of any other way of identifying other Git installations.

**Comment by nasko** [comment]
Ok, it turned out that Smartgit was the culprit.

Ifter uninstalling both Git for windows and Smartgit, I then re-installed Git for Windows 2.30.2 and now the output of git --version is 2.30.2.windows.1, and the non-ascii characters are being rendered correctly.

Closing this one.
