### ISSUE TITLE
Missing folder background context menus after major Windows update

### ISSUE THREAD

**Issue by Youw** [git-for-windows/git#3109]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing, except https://github.com/git-for-windows/git/issues/875 which is unhelpful.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.30.2.windows.1
cpu: x86_64
built from commit: 37f0a4afad027cf030747a1ef45537ba86162960
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.21332.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using Windows 10 Pro Insider Preview.

### Details

When I install Git-For-Windows, I always include Windows Explorer integration:
![image](https://user-images.githubusercontent.com/5939659/110963583-e956b080-835a-11eb-9f38-e0ac5ad6c898.png)

As expected, I get context menus when right-click on a folder: (1)
![image](https://user-images.githubusercontent.com/5939659/110963758-228f2080-835b-11eb-8db9-b6c611dbc7da.png)
And on the background inside folder: (2)
![image](https://user-images.githubusercontent.com/5939659/110963894-4a7e8400-835b-11eb-8aa7-5f7035f4cb1a.png)

Issue happenes after _major_ Windows Update.  Folder background context menus (2) are missing, forder context menus (1) are still present.

By "_major_" update I mean cases, when Windows build number is updated (C:\Windows.old is created, etc.).

While most Windows users don't experience this often (they don't get major updates often), as a user of Insider Preview, I'm getting major updates every aproximately few weeks, this becomes annoing.

### Workaround

A workaround to get menu entries back is to install Git-For-Windows again after update.

**Comment by Youw** [comment]
Last time I got major Windows Update was this morning, and I already reinstalled Git-For-Windows, so I cannot investigate what was the state of my machine right after Update, when entries where missing.

Next time when it happens, I'll try to gather as much info as I can, specially if someone could give me a hint where and what to look for.

**Comment by rimrul** [comment]
Those context menu entries should just be a couple of registry entries under HKLM/HKCU (depending on permissions).

Since you're missing the background entries you should look for 

`HKLM\SOFTWARE\Classes\Directory\Background\shell\git_shell`, `HKLM\SOFTWARE\Classes\Directory\Background\shell\git_shell\command`, `HKLM\SOFTWARE\Classes\Directory\Background\shell\git_shell\Icon`, `HKLM\SOFTWARE\Classes\LibraryFolder\background\shell\git_shell`, `HKLM\SOFTWARE\Classes\LibraryFolder\background\shell\git_shell\command` and `HKLM\SOFTWARE\Classes\LibraryFolder\background\shell\git_shell` or their HKCU counterpart for the `Git Bash` entry. replace `git_shell` with `git_gui` for the `Git GUI` entry.

https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss#L3064-L3097

**Comment by Youw** [comment]
Today I've got another major (weekly) windows upgrade, and after it:
![image](https://user-images.githubusercontent.com/5939659/111875375-2695f080-89a2-11eb-9f3d-39bff6cc433d.png)

I woulder is there any scripts or hooks that are executed during the upgdate, where a Git-for-Windows installer could add a script to restore those values.

**Comment by PhilipOakley** [comment]
some general comments: 
Each install is a full install, so it's only those things that have an option that can be chosen. 

I do not think that the git-gui is an option.

The shell aspect may just be a change in layout within the installer.

**Comment by dscho** [comment]
Maybe [that checkbox in the second installer page](https://github.com/git-for-windows/build-extra/blob/4dfcae554dd036efd81fe06ec7c8305305a45c91/installer/install.iss#L105) ("Components") got turned off for some reason?

**Comment by Youw** [comment]
> I do not think that the git-gui is an option.

This option?
![image](https://user-images.githubusercontent.com/5939659/111900547-e8e5a600-8a3b-11eb-839d-fe6e3654d585.png)

> got turned off for some reason?

At least each time I run the installer, the option is always selected.
But does the installer actually run during the Windows upgrade? And there is no disctinct options for Directory/ or Directory/Background 

More I think about it, more I coming to conclusion that this is a Windows installer "bug" - maybe it just clears all entries in HKLM\SOFTWARE\Classes\Directory\Background\shell and fills them up with the defaults.

The question here - is there a workaround for it, or not.

**Comment by PhilipOakley** [comment]
> > I do not think that the git-gui is an option.
> 
> This option?

Ah, yes. My mistake for not checking. I normally have the 'keep existing options' button ticked, so my memory failed me.

**Comment by dscho** [comment]
> The question here - is there a workaround for it, or not.

I fear the best workaround is to simply reinstall Git for Windows.

Though I'm puzzled that the registry entries seem to be removed during a _Windows_ upgrade. That strikes me as unusual.

**Comment by Youw** [comment]
> I fear the best workaround is to simply reinstall Git for Windows.

Yeah, so I did... for the first few months.... every week... That's a bit inconvenient. That's why I have this ticket created. Maybe community can help.

BTW: now I have a small .reg script, that simply restores those registry entries, but that is still a workaround.

**Comment by dscho** [comment]
Wait, you upgrade Windows _every week_?

**Comment by Youw** [comment]
> While most Windows users don't experience this often (they don't get major updates often), as a user of Insider Preview, I'm getting major updates every aproximately few weeks, this becomes annoing.

More or less.

**Comment by dscho** [comment]
> > While most Windows users don't experience this often (they don't get major updates often), as a user of Insider Preview, I'm getting major updates every aproximately few weeks, this becomes annoing.
> 
> More or less.

Urgh... ;-)

> `HKLM\SOFTWARE\Classes\Directory\Background\shell`

I had another look, and found one [StackOverflow post](https://stackoverflow.com/a/29769228) that suggested that our use of `HKLM` is incorrect here, we should use `HKCR` instead.

Would you be able to test that theory? Like, modify your script to register in `HKEY_CLASSES_ROOT` instead of `HKEY_LOCAL_MACHINE`, and then see

1. whether it works, and
2. whether the next Windows upgrade leaves those entries alone?

> 
>

**Comment by Youw** [comment]
> that suggested that our use of `HKLM` is incorrect

Well, it doesn't exactly say it is incorrect, it just says it requires to be an Admin, bacause it is a Syste-wide change, as opposed to User-wide config.

1) Yes, that works. But, naturally, only for my current user (yes, I have a multi-user development machine, so this kind-of affects me).

2) So we wait a week or so, and I'll share my findings.

**Comment by rimrul** [comment]
HKCR should be system wide as well.

**Comment by Youw** [comment]
My appology. For some reason I confused `HKCR` with `HKCU`.

**Comment by Youw** [comment]
> we should use HKCR instead

That won't help. `HKCR` effectively is a merge of `HKEY_LOCAL_MACHINE\Software\Classes` and `HKEY_CURRENT_USER\Software\Classes`.

If you're an Admin and you're writing to `HKEY_CLASSES_ROOT\<subkey>` you're effectively writing to `HKEY_LOCAL_MACHINE\Software\Classes\<subkey>`.

If you delete an entry under `HKEY_CLASSES_ROOT\` you're effectively deleting an untry under `HKLM\Software\Classes` or under `HKCU\Software\Classes`, depending where it originally came from.

**Comment by dscho** [comment]
@Youw I did not even know that `HKCR` was a virtual domain. Do you have any idea where we should configure this Background stuff instead so that it is safe from a Windows upgrade?

**Comment by Youw** [comment]
I have two ideas so far:
1) 
> I wounder is there any scripts or hooks that are executed during the upgdate, where a Git-for-Windows installer could add a script to restore those values.

2) Try to use `shellex` instead of `shell`. This require some WinAPI/COM coding. I may be able to try it, just don't know when.

**Comment by dscho** [comment]
What's your first idea?

Also, do you have any idea whether `shellex` would be _any_ safer than `shell_? And what about TortoiseGit, what do _they_ do?

**Comment by Youw** [comment]
> What's your first idea?

To find if Windows has some kind of script/hook that is executed during upgrade and add some logic there that would restore missing values.

>  whether `shellex` would be any _safer_ than `shell`?

Not sure I understand the meaning of "_safer_ " in this context.

> And what about TortoiseGit, what do _they_ do?

They have `shellex` plugin. Good that you mentioned it.
https://github.com/TortoiseGit/TortoiseGit/blob/master/architecture.txt#L21
Now I have TortoiseGit installed and can check the behavior for `shellex` after the upgrade.

**Comment by dscho** [comment]
> > whether `shellex` would be any _safer_ than `shell`?
> 
> Not sure I understand the meaning of "_safer_ " in this context.

"safer" as in: "an upgrade won't delete it"

> Now I have TortoiseGit installed and can check the behavior for `shellex` after the upgrade.

👍

**Comment by Youw** [comment]
Its been a while since my last update. Here is a short summary:
1) After the next major upgrade TortoiseGit context menus (that are implemented with `shellex`) did not disappear;
2) But Git for Windows context menus _didn't disappear_ either!
2) I did another test: completely removed TortoiseGit (so no custom `shellex` extries) and waited another 2 major upgrades) - the original issue wasn't reproducable anymore;

I'm starting to think that the original issue really was just a Windows Upgrade bug that has need fixed. I din't note the windows version where I've seen the issue for the last time, or the version where it was fixed for the first time. Right now I'm on 10.0.21390.1010 build and context menu entries don't dissappear during the upgrade over the last... well, since the last failure I've seen in March.

As I mentioned earlier, I'm on Windows Preview branch. Before closing the issue I guess would be breat to verify the behavior on a streamline consumer Windows branch, but major upgrades on those happening so rarle, that maybe it is not worth to search for a volonteer/monitor/wait.

**Comment by rimrul** [comment]
> Before closing the issue I guess would be breat to verify the behavior on a streamline consumer Windows branch, but major upgrades on those happening so rarle, that maybe it is not worth to search for a volonteer/monitor/wait.

I happen to have a Windows 10 device on the regular update channel with Git for Windows installed that's currently asking me to install 21H1. That should work.

**Comment by rimrul** [comment]
The context menu entries survived the upgrade, so I think we're good.
