### ISSUE TITLE
Simulate core.filemode

### ISSUE THREAD

**Issue by dra27** [git-for-windows/git#311]
Given the lovely addition of support for symbolic links, is there any intention/desire to add support for `core.filemode = true` for Windows Git?
I'm wondering if it would be practical to have a cache (say .git/chmods) which record the names of files which are 755 rather than 644 and a Windows-only git chmod command which allows it to be changed. I can see that there might be some idiosyncrasies with renaming (although if git commit is able to identify a file as having been renamed, it might be possible to move the 755 mask with it too).
While obviously 755 is never going to mean anything on Windows, being able to have `core.filemode = true` would be nice for cross-platform repos.
Is this desirable (and should be a feature on Git itself?)

**Comment by dscho** [comment]
Well, given that this `chmod` would do nothing to make any script executable on Windows, would that not be rather confusing to users?

**Comment by tboegi** [comment]
You can update the execute flag like this: 
git update-index --chmod +x build.sh

**Comment by dscho** [comment]
@tboegi true, but that still is only affecting Git´s internal operation... Windows ignores that bit...

**Comment by dra27** [comment]
My thinking is that it removes the real confusion of git diff reporting 755/644 differences in files (even with core.filemode set to false, this can crop up when diff'ing commits). What I'm really humbly suggesting is that core.filemode is a poor solution to the problem as it stands!

At the moment, it is tricky (given that update-index is plumbing, not porcelain) sat at a Windows box to commit scripts to a cross-platform repository where you're worried about +x *in the repository*. For example, if a script is renamed and changed sufficiently that git's rename tracking gets confused, it'll lose the +x attribute if core.filemode is false. The emulation I'm proposing would at least allow `git mv` to ensure that the +x is kept in the renamed file, regardless of how changed it is, because it would be tracking the +x in the *working directory* as well as the index. Obviously there is still potential for gotchas - and it relies on a developer sat in either msys or Cygwin to remember to set the +x when creating new scripts, but it at least provides the capability.

Cygwin wallpapers over the issue of being able to execute the scripts by making pretty much everything executable, so I don't think a Windows-user is ever going to use git chmod +x and expect that to make a script executable? Also, isn't a Windows-user looking at this kind of thing surely going to be Unix-savvy already, and so less likely to be confused?

core.filemode works around the problem (well, it's not a problem as much an architectural difference!) in the underlying file system basically by ignoring it - I'm thinking that emulation would be better?

**Comment by PhilipOakley** [comment]
Any `chmod +x` trick would also have to cope with the `git gui` effect of staging and unstaging of a file. This is very easy to do (as a user) as both a mistaken click, and as a deliberate way of picking up new changes (unstage/restage said file), and it is here that one can easily loose the `+x`.

I've certainly had it as a problem on a recent patch series where a script lost its +x while tweaking/amending during a rebase.

As an aside, I have an aspiration to get the `git gui` (and `gitk`) to highlight in red (or suitable warning colour) any changes to the file mode bits when the core.filemode set to false - i.e. if you can't trust the filemode then always warn about the changes. `gitk` warnings are needed for looking at patch series.

**Comment by dscho** [comment]
My thinking: we need two things

- better support for `core.filemode` in, say, `merge-recursive` (but I realize that there is no clear demonstration of the bug reported by @j6t yet, not in t3030, t3032, t6024 nor t6031)
- maybe an option `--mode=+/-x` for `git add`?

I guess these ideas are actually best discussed on the Git mailing list. @dra27 how about summarizing this discussion so far in a mail to git@vger.kernel.org?

**Comment by dscho** [comment]
> I guess these ideas are actually best discussed on the Git mailing list. @dra27 how about summarizing this discussion so far in a mail to git@vger.kernel.org?

@dra27 I still would encourage you to do that.
