### ISSUE TITLE
After installing Git 2.31.0-rc2, PowerShell reports an error 

### ISSUE THREAD

**Issue by DustinWin** [git-for-windows/git#3111]
**Git version:** 2.31.0-rc2
**Operating system version:** Windows 10 21H1
**PowerShell version:** comes with the system
**oh-my-posh version:** 3.111.2
**Steps to reproduce:**
1. Run PowerShell as an administrator and run the following command:
```
Set-ExecutionPolicy RemoteSigned
Install-Module posh-git
Install-Module oh-my-posh
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme PowerLine
```
2. Enter the folder C:\Users\ [your username] \Documents\WindowsPowerShell, edit the text document, and enter the following:
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme PowerLine
```
And save as Microsoft.PowerShell_profile.ps1
3. Close PowerShell, and open PowerShell again
**Expected results:**
PowerShell will not report errors
**Actual results:**
PowerShell reports an error, and the content of the error:
Warning: You appear to have an unsupported Git distribution; setting $GitPromptSettings.AnsiConsole = $false. posh-git recommends Git for Windows.
![QQ截图20210314104430](https://user-images.githubusercontent.com/45238096/111055583-49ac3600-84b2-11eb-879b-b244d468566f.png)
**Remarks:**
If you install Git v2.30.2 version, no error will be reported.

**Comment by dscho** [comment]
Thanks for the report.

Does this happen with _every_ -rc version? (If you could install, say, v2.30.0-rc2.windows.1 and see whether posh-git complains in the same way, that would be helpful)

**Comment by DustinWin** [comment]
> 谢谢你的报告。
> 
> 每个-rc版本_都会_发生这种情况吗？（如果你能安装，比如说，v2.30.0-rc2.windows.1，看看豪华的git是否以同样的方式抱怨，这将是有帮助的）



> Thanks for the report.
> 
> Does this happen with _every_ -rc version? (If you could install, say, v2.30.0-rc2.windows.1 and see whether posh-git complains in the same way, that would be helpful)

Indeed, I installed the 2.31.0 rc1, 2.31.0 rc0, and 2.30.0 rc2 versions, and all encountered this problem. I installed the 2.30.1 and 2.30.2 version again and did not encounter this problem.

**Comment by dscho** [comment]
Okay, so this is a problem in posh-git.

I could not find anything at https://github.com/dahlbyk/posh-git/issues?q=is%3Aissue+is%3Aopen+rc, but maybe you can? Or maybe there is already a PR addressing this? Or you want to give it a try?

**Comment by DustinWin** [comment]
> Okay, so this is a problem in posh-git.
> 
> I could not find anything at https://github.com/dahlbyk/posh-git/issues?q=is%3Aissue+is%3Aopen+rc, but maybe you can? Or maybe there is already a PR addressing this? Or you want to give it a try?

Okay, I will try.

**Comment by dahlbyk** [comment]
Is there a particular reason the rc build `--version` doesn't include the usual `.windows` suffix? That's how we identify G4W (which works) vs Cygwin or other builds.

**Comment by dscho** [comment]
> Is there a particular reason the rc build `--version` doesn't include the usual `.windows` suffix?

It does include the `.windows.1` suffix, but it also has a `.rc<N>` infix. See https://github.com/dahlbyk/posh-git/issues/845#issuecomment-798988322 for what I _think_ should fix the issue.

**Comment by dahlbyk** [comment]
We'll patch this in posh-git. Go ahead and close here.
