### ISSUE TITLE
Running the installer from the notification toast can result in just an error box

### ISSUE THREAD

**Issue by Tragetaschen** [git-for-windows/git#3118]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
git version 2.30.2.windows.1
cpu: x86_64
built from commit: 37f0a4afad027cf030747a1ef45537ba86162960
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.18363.1379]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I chose to activate the regular update checks.

### Details

I have a `git gui` instance running.

I have activated Git's regular update check that notifies me with a Windows notification toast if one is available.
Just now, I got one for `2.31`.

When I start the update by clicking on the notification, there is just a single error message (`Setup cannot continue until you close at least those applications in the list that are marked as "closing is required"`) and nothing else happens.
![image](https://user-images.githubusercontent.com/1947968/111285620-9eca8200-8641-11eb-82bf-bcd51db6534f.png)

I would have expected to land in the installer where the actual list "closing is required" is visible and continue manually from there. As it is, I have to wait until tomorrow when the toast appears again and remember to close `git gui` before clicking the notification or run the update manually today.

**Comment by rimrul** [comment]
Interessting. The `ProcessesPage` custom wizard page gets hidden, because the installer is executed with `/SILENT`. I'm not sure how we could prevent this.

**Comment by dscho** [comment]
I wonder whether we can use the `Show()` method of the wizard form (https://jrsoftware.org/ishelp/topic_scriptclasses.htm#TWizardForm).

**Comment by dscho** [comment]
> I wonder whether we can use the `Show()` method of the wizard form (https://jrsoftware.org/ishelp/topic_scriptclasses.htm#TWizardForm).

Unfortunately, that does not work. It does show the wizard form, but it exits immediately after the <kbd>OK</kbd> button was pressed.

**Comment by rimrul** [comment]
I could imagine detecting silent install with `WizardSilent()` and then showing a slightly tweaked message box, that shows the offending processes (might become a tall MessageBox) and allows the user to retry from the MessageBox.

**Comment by dscho** [comment]
> 
> 
> I could imagine detecting silent install with `WizardSilent()` and then showing a slightly tweaked message box, that shows the offending processes (might become a tall MessageBox) and allows the user to retry from the MessageBox.

That's precisely what I am doing ;-)

**Comment by dscho** [comment]
See https://github.com/git-for-windows/build-extra/pull/332 for the proposed fix.

**Comment by Tragetaschen** [comment]
I like the new behavior. Thanks!
