### ISSUE TITLE
Line 3105: Unable to delete "git-lfs.exe" on 2.31.0 install

### ISSUE THREAD

**Issue by Molkree** [git-for-windows/git#3120]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.31.0.windows.1
cpu: x86_64
built from commit: 959b2f0c6fb12f8ba13f9015c4482fa8133b7f9c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
I am pretty sure I was updating from 2.30.2.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19042.867]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
I don't know.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell, but it shouldn't matter in this case.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I just ran Git for Windows 2.31.0 installer and got this warning message when it finished. It looks like it finished installing though.
 - What did you expect to occur after running these commands?

No warnings during installation.

 - What actually happened instead?

When installation finished I got a warning window with the text "Line 3105: Unable to delete "git-lfs.exe"."

![image](https://user-images.githubusercontent.com/12860284/111309820-604abc80-866d-11eb-8f67-ee96a787b87d.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not valid for this issue.

**Comment by dscho** [comment]
Hi @Molkree, thank you for reporting this issue.

I suspect that you still had a running Git LFS. You could check for that yourself by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd> to start the Task Manager, and then looking for "Git LFS" or "git-lfs.exe".

**Comment by Molkree** [comment]
That's possible I guess? I don't see it running now but it's been some time since I updated.
Either way, should I get a warning message if it's running and I update Git for Windows if it's not causing problems? Or maybe installer should pause/close-reopen it?

**Comment by Molkree** [comment]
Just to clarify: this machine has 4 repos in total and none of them use Git LFS.

**Comment by dscho** [comment]
> 
> 
> Just to clarify: this machine has 4 repos in total and none of them use Git LFS.

Hrm. Then I really have no idea how we could potentially reproduce (and subsequently fix) the problem.

**Comment by dscho** [comment]
Closing as stale.
