### ISSUE TITLE
%USERPROFILE%: No such file or directory

### ISSUE THREAD

**Issue by mriehema** [git-for-windows/git#313]
I just updated to git-for-windows 2.5.0 (64bit) on my Windows 7 (64bit). My .bashrc is not working, so I was looking for my %USERPROFILE% and I get "No such file or directory". 
If I'm running Git Bash as Administrator, it works. Why do I have to run Git Bash as Administrator?

**Comment by dscho** [comment]
Do you have environment variables `HOMEDRIVE` and `HOMEPATH`? And `USERPROFILE`? These are typically all set by Windows by default, unless you removed them from your environment.

If everything else fails, I recommend setting `HOME` in your user environment variables to the directory you want to use as your home directory.

**Comment by mriehema** [comment]
Yes, I have all three enviroment variables `HOMEDRIVE`, `HOMEPATH` and `USERPROFILE`.
My Useraccount is a local Administrator, but Git Bash is reading my `.bashrc` only, if I'm running it as Administrator (with the annoying User Account Control Popup). I used 1.9.5 in 32bit before and didn't have the problem. Is it a 64bit issue?

**Comment by dscho** [comment]
> Is it a 64bit issue?

I do not have enough information to form an opinion on that.

> I have all four enviroment variables HOME, HOMEDRIVE, HOMEPATH and USERPROFILE.

So if you start `Git Bash`, does `env | grep -e HOME -e USERPROFILE` show them correctly?

Are the environment variables set as user environment variables or as system ones?

Please volunteer such information, it is very tedious having to ask for every detail specifically.

**Comment by eyecatchup** [comment]
I have almost the exact same setup. Updated from 1.9.5 32bit on Win 7 64bit to 2.4.6 64bit.

I don't have this problem though. Just to make sure.. Are you trying to cd from the git bash into `%USERPROFILE%` or `$USERPROFILE`?

```
ssc@Stephan-Ultrabook MINGW64 /c/xampp/htdocs/workshop-slides_mastering-git_2015_de (develop)
$ cd %USERPROFILE%
bash: cd: %USERPROFILE%: No such file or directory

ssc@Stephan-Ultrabook MINGW64 /c/xampp/htdocs/workshop-slides_mastering-git_2015_de (develop)
$ cd $USERPROFILE

ssc@Stephan-Ultrabook MINGW64 ~
```

**Comment by eyecatchup** [comment]
> Are the environment variables set as user environment variables or as system ones?

The `USERPROFILE` environment variable is set by Windows for each user profile automatically, isn't it?

**Comment by dscho** [comment]
@eyecatchup it *should* be. Under certain circumstances, it contains a bogus path, though, so we prefer looking at `HOMEDRIVE`\`HOMEPATH`: https://github.com/git-for-windows/git/blob/5e906e91ea3ca29a8916c34905662563ff2b2437/compat/win32/git-wrapper.c#L55-L87

**Comment by mriehema** [comment]
> So if you start Git Bash, does env | grep -e HOME -e USERPROFILE show them correctly?

Yes.
```
$ env | grep -e HOME -e USERPROFILE
HOMEPATH=\Users\mriehema
GRADLE_HOME=C:\Program Files\Java\gradle-2.4
PATH=/%USERPROFILE%/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Skype/Phone:/c/Program Files/Perforce:/c/Program Files/nodejs:/c/Program Files/Java/gradle-2.4/bin:/c/Program Files:/c/Program Files (x86):/c/Program Files/Java/jre7/bin:/c/Program Files/Java/jdk1.7.0/bin:/c/Program Files/Java/apache-maven-3.3.3/bin:/c/Program Files (x86)/phantomjs/bin:/c/Users/mriehema/AppData/Roaming/npm:/usr/bin/vendor_perl:/usr/bin/core_perl
MAVEN_HOME=C:\Program Files\Java\apache-maven-3.2.5
JAVA_HOME=C:\Program Files\Java\jdk1.7.0
USERPROFILE=C:\Users\mriehema
M2_HOME=C:\Program Files\Java\apache-maven-3.2.5
HOME=/%USERPROFILE%
HOMEDRIVE=C:
```
> Are the environment variables set as user environment variables or as system ones?

user environment variables 

> @eyecatchup: Are you trying to cd from the git bash into %USERPROFILE% or $USERPROFILE

No, I want to use my aliases, defined in my `.bashrc` file. But it is not loaded, if I'm not running Git Bash as Administrator.

Example:
```
mriehema@xxx MINGW64 /
$ ~
bash: /%USERPROFILE%: No such file or directory
```

Same as Administrator:
```
mriehema@HAM-ITS0642 MINGW64 /
$ ~
bash: /c/Users/mriehema: Is a directory
```

**Comment by mriehema** [comment]
OK, i got it. If I remove my `HOME=%USERPROFILE%`, it works.

**Comment by dscho** [comment]
Ah. Yeah, if you want to define `HOME`, it has to be set to a path. If you set it to `%<name-of-an-environment-variable>%`, that won't work because it won't be expanded.
