### ISSUE TITLE
git-cmd and git-bash cannot run executables in usr/bin 

### ISSUE THREAD

**Issue by crowne** [git-for-windows/git#3130]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.0.windows.1
cpu: x86_64
built from commit: 959b2f0c6fb12f8ba13f9015c4482fa8133b7f9c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.867]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files (x86)\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Disabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I noticed the error when I was trying to do >git rebase -i HEAD~4
I did this a new test repository with 5 commits
The error that I was getting is :
hint: Waiting for your editor to close the file... error: There was a problem with the editor 'vi'.

After that I have been trying to work through the issue and I found that none of the mingw executables seem to work.

The problem was initially on Git-2.23.0-64-bit, then I upgraded to the latest Git-2.31.0-64-bit,
but the problem seems to persist.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I have tried cmd, PowerShell, git-cmd, git-bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
start C:\Program Files (x86)\Git\git-cmd.exe
>usr\bin\ls -l

```
![image](https://user-images.githubusercontent.com/3218673/111862496-5e7b4480-895e-11eb-919a-6b585c902454.png)

```
start C:\Program Files (x86)\Git\git-bash.exe
>usr/bin/ls -l
... blank output - no response
```

 - What did you expect to occur after running these commands?

Directory listing of C:\Program Files (x86)\Git

 - What actually happened instead?

Please see errors above : error popup & blank response

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I created a new test repo with 5 commits, to test the rebase -i, however I don't think that the problem is repo related,
it seems to be an issue with the mingw tools.

**Comment by dscho** [comment]
Hi @crowne! Sorry to hear that you ran into a snag

> `start C:\Program Files (x86)\Git\git-cmd.exe`

Given that you report a 64-bit Git for Windows, it is somewhat curious to see that `(x86)` in the command-line. Is there maybe _another_ `git-cmd.exe` in `C:\Program Files\Git`?

**Comment by crowne** [comment]
No, it seems to be only installed under C:\Program Files (x86)\Git
No git folder under C:\Program Files

**Comment by dscho** [comment]
> cpu: x86_64

I wonder how you get this output if all you have is a 32-bit Git...

**Comment by crowne** [comment]
It is a 64 bit version of git installed in C:\Program Files (x86)
I have verified by inspecting the contents with Notepad++
The superuser answer below explains how to tell 32 vs 64 
https://superuser.com/questions/358434/how-to-check-if-a-binary-is-32-or-64-bit-on-windows

![image](https://user-images.githubusercontent.com/3218673/114045587-69076a80-9888-11eb-8377-0744137ee65d.png)

**Comment by rimrul** [comment]
>It is a 64 bit version of git installed in C:\Program Files (x86)

That probably means we can't trust anything in this installation. Could you also verify that `ls.exe` and `msys2-1.dll` are also 64bit?

**Comment by crowne** [comment]
I can't find `msys2-1.dll` , however I do see the following :
C:\Program Files (x86)\Git\usr\bin\ls.exe             is compiled 64bit
C:\Program Files (x86)\Git\usr\bin\msys-2.0.dll   is compiled 64bit
C:\Program Files (x86)\Git\bin\msys-2.0.dll         is compiled 32bit

I tried replacing the 32bit msys-2.0.dll with the 64bit version,
and then launched git-cmd.exe and tried to run `usr\bin\ls.exe -l`
but the error still remains

**Comment by rimrul** [comment]
>I can't find msys2-1.dll

Yes, I meant `msys-2.0.dll`

>C:\Program Files (x86)\Git\usr\bin\ls.exe is compiled 64bit
C:\Program Files (x86)\Git\usr\bin\msys-2.0.dll is compiled 64bit
C:\Program Files (x86)\Git\bin\msys-2.0.dll is compiled 32bit

There shouldn't be a `C:\Program Files (x86)\Git\bin\msys-2.0.dll` at all.

This all sounds very odd.

**Comment by dscho** [comment]
> C:\Program Files (x86)\Git\usr\bin\msys-2.0.dll is compiled 64bit
> C:\Program Files (x86)\Git\bin\msys-2.0.dll is compiled 32bit

This means that you have a mixed installation. There should not be any `.dll` in the latter directory _at all_.

The safest way to fix this would be to

- uninstall Git
- ensure that nothing remains at `C:\Program Files (x86)\Git`. This directory should not exist anymore. If it exists, delete it.
- install Git again

When you call Git Bash after that, it should report that `cygpath -aw /` is pointing to `C:\Program Files\Git`, and your woes should be gone.

I have _no_ idea how your setup got into the state it got into, I am not aware of any previous version of Git for Windows whose installer was so broken as to allow 64-bit to be installed into the 32-bit Program Files, and I have no inkling how that `msys-2.0.dll` got into that `bin` folder in the first place.

**Comment by crowne** [comment]
Thanks dscho, the uninstall and reinstall has fixed the issue.
I have no idea how it got into that mixed up state previously.
