### ISSUE TITLE
invalid --pretty format: '' - Different output in cmd and in bash

### ISSUE THREAD

**Issue by rluvaton** [git-for-windows/git#3131]
when running:
```console
$ git -C ./ log --follow --format='' --name-only '*'
```
I get the following error in CMD:
```
fatal: invalid --pretty format: ''
```

And in bash and PowerShell, I get the expected result.

**Comment by dscho** [comment]
CMD has different quoting rules than Bash. Have you tried without the quotes altogether, i.e. `git -C ./ log --follow --format=​`?

**Comment by rluvaton** [comment]
> CMD has different quoting rules than Bash. Have you tried without the quotes altogether, i.e. `git -C ./ log --follow --format=​`?

Thank you for the quick replay 🤦🏻‍♂️
