### ISSUE TITLE
git mergetool LOCAL, BASE, REMOTE temporary files are not created

### ISSUE THREAD

**Issue by roaladje** [git-for-windows/git#3140]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 - 64bit

```
$ git --version --build-options

git version 2.25.0.windows.1
cpu: x86_64
built from commit: 7c71c859c97853ed057da5cbab12f3c13b5554df
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10, 64bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.867]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults, and also tried other options (like all Unix tools, didn't help)

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I can think of

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git mergetool
```
 - What did you expect to occur after running these commands?

git to create LOCAL, BASE, REMOTE temp files, and open those in the mergetool

 - What actually happened instead?

mergetool opened with the correct path, but those files do not exist (so, mergtool shows "FILES NOT EXISTS")

1. I even tried to check with Procmon, and it looks like those files never got created. In another PC of mine with a similar configuration, I can see mv.exe created those temp files. in the problematic PC, it's not
2. Tried both BeyondCompare and meld as mergetool, but it doesn't seem related to the tool itself, as explained above.

I tried to upgrade git, but I get other issues with newer git (mergetool/difftool does not exist error. i.e., a newer version of git also breaks the difftool becuase of other unrelated issues, which now works)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Any repo

**Comment by dscho** [comment]
> git version 2.25.0.windows.1

There have been quite a few changes in `mergetool` between that version and the current one (v2.31.0), including bug fixes. Could you try again with v2.31.0?

**Comment by roaladje** [comment]
Tried, as explain in the bug, but can't due to 
https://github.com/git-for-windows/git/issues/3141 (BeyondCompare as difftool/mergetool does not work in v2.31.0 (but does in v2.25) #3141).

I.e., in 2.25 I can use `git difftool` but not `git mergetool`,
in 2.31 I can't use both,


Thanks.

**Comment by dscho** [comment]
Let's close this in favor of #3141 because Git for Windows does not support older release trains (read: there won't be any v2.25.x that fixes this).
