### ISSUE TITLE
Maven: mvn release:prepare changes line endings for core.autocrlf=input

### ISSUE THREAD

**Issue by kriegaex** [git-for-windows/git#315]
This is a regression from Git 1.9.5. I do not want my Git to change UNIX line endings to Windows ones even when working on Windows. Git 1.9.5 respected this setting, but in connection with Maven (v3.3.3), Git 2.5.0 does not.

I think this is a major issue. And please do not blame Maven because the only element on my system which changed was Git.

**Update:** My Maven POM even uses the *jgit* provider, i.e. I have no idea why the locally installed Git changes the behaviour of Maven. The symptom is that I get full-file diffs for the first of two commits made by Maven.

**Comment by dscho** [comment]
Output? What Maven goals/plugins do you use? Please be less terse.

**Comment by dscho** [comment]
Also, what is your `core.autocrlf` setting (i.e. what line ending policy did you choose in the installer)?

**Comment by kriegaex** [comment]
Guys, both questions are answered in the subject:
* `mvn release:prepare` implies Maven Release Plugin (v2.5.2, by the way). And as I also said, I use the *jgit* SCM provider.
* `core.autocrlf=input` implies exactly what it says.

The Maven output is normal (build success), but the problem symptom is that the first of the two usual commits (change POMs to release version) shows full file diffs due to all files being switched from LF to CRLF line endings (with `core.safecrlf`and `core.eol` unset). The second commit changing the POMs to the next snapshot version shows one-line diffs again because CRLF stays CRLF.

I will be happy to be less terse if you tell me what else you need to know. But please also carefully read what I have written so as to avoid the need for repetition. Thank you for your swift reaction.

**Comment by dscho** [comment]
If you have a [Minimal, Complete and Verifiable Example](http://stackoverflow.com/help/mcve), I would make time to look at this today.

**Comment by kriegaex** [comment]
I will have to recreate the situation in a new project because my client's project is confidential. If you want to recreate the situation, I would think that any Maven project with the configuration I just described will do, but I cannot say for sure.

**Comment by kriegaex** [comment]
Just to be on the safe side, do this:

    git config --global --unset core.autocrlf
    git config --global --unset core.safecrlf
    git config --global --unset core.eol

    git config --global core.autocrlf input
    git config --global core.eol lf

Now, look at https://github.com/kriegaex/git-maven-problem and/or clone https://github.com/kriegaex/git-maven-problem.git

One should expect now that *pom.xml* is cloned with UNIX line endings (LF). So far, so good.

Now do this:

     mvn release:prepare -DpushChanges=false -DpreparationGoals=clean

Now check the diff for the first commit. It should be one changed line, but actually the full file has changed in the local Git repo.

**Comment by dscho** [comment]
Okay, with this MCVE (and almost 2h of work on this bug) I figured out that this is *not* Git for Windows' fault. It appears that somewhere along the line, the `maven-release-plugin` forgot to respect the line endings it saw in the `pom.xml` and just decided to use the default line endings as per the `line.separator` property: https://github.com/apache/maven-release/blob/98c2f4765c97cadb658592fc7773872b4f9296a8/maven-release-manager/src/main/java/org/apache/maven/shared/release/util/ReleaseUtil.java#L124-L152 (`LS` is set here: https://github.com/apache/maven-release/blob/98c2f4765c97cadb658592fc7773872b4f9296a8/maven-release-manager/src/main/java/org/apache/maven/shared/release/util/ReleaseUtil.java#L62).

There is even a pretty prominent StackOverflow post about this: http://stackoverflow.com/questions/11868590/maven-release-plugin-and-windows-line-breaks

The best demonstration that this is *not* Git for Windows' fault is by showing that the following command-line (execute in Bash) "fixes" the behavior.

```sh
mvn release:prepare -DpushChanges=false -DpreparationGoals=clean -Dline.separator=$'\n'
```

**Comment by kriegaex** [comment]
No no, not so fast. How then do you explain that Maven behaves correctly with Git 1.9.5 and uncorrect with Git 2.5.0?

**Comment by kriegaex** [comment]
I just checked my installation protocol (a series of screenshots I made for the rest of the team when I initially installed Git 2.5.0). There is the page "Configuring the line ending conversions" in the installer. I chose option no. 3, "Check out as-is, commit Unix-style line endings":

![image](https://cloud.githubusercontent.com/assets/1537384/9488874/2bbe6bea-4bdd-11e5-923b-3c4e0f23fd0f.png)

The thing is: CRLF line endings are being committed during Maven release, so the question boils down to: why? Git does not what I selected in the installer. Maybe if you can help me answer this question we find out what breaks backward compatibility between the two Git versions. Any idea?

**Comment by dscho** [comment]
It's nice that my hard work is appreciated.

It appears that JGit is indeed doing the commit work, as you can see from the output with Maven's `-X` flag. And JGit tries to be clever and reuse Git for Windows' system `gitconfig`: https://github.com/eclipse/jgit/blob/b5941c74e59e64c5fd374a09067e74e26eed2612/org.eclipse.jgit/src/org/eclipse/jgit/util/FS.java#L555-L574

 This is not proper, as the file system layout of Git for Windows is not really any of JGit's business. A similar discussion with libgit2 revolved about the same subject and it was decided that the best way forward would be to define a system-wide place where Git configuration that is not implementation-specific would be put. The location we settled on was `%PROGRAMDATA%\Git\config`. JGit simply needs to adapt to that, instead of meddling with Git for Windows' own files.

You have several options how to work around it (of course, assuming that you do not go and fix JGit), simplest first:

- use a repository-specific `core.autocrlf` setting
- copy `%PROGRAMDATA%\Git\config` into Git for Windows' location (`mingw64/etc/gitconfig` for 64-bit)
- switch your Maven configuration to use Git for Windows instead of JGit
- switch to a `maven-release-plugin` version that does not meddle with the line endings of an existing `pom.xml` (but from my logs, it appears that the newest version, 2.5.2, exposes this behavior)
- augment the phase via a custom execution to `dos2unix`, possibly conditional on the OS and/or the `line.separator` property's value.

**Comment by kriegaex** [comment]
Thanks, @dscho. I did something similar to your second suggestion: I started Git 2.5 Bash as administrator and issues this command:

    ln -sf /c/ProgramData/Git/config /mingw64/etc/gitconfig

JGit still commits with CRLF, but the diffs look good (as in small).

**Comment by dscho** [comment]
> ln -sf /c/ProgramData/Git/config /mingw64/etc/gitconfig

I doubt that Java (and therefore JGit) knows how to follow such a symbolic link. Therefore in my book, that is not a solution.

**Comment by kriegaex** [comment]
You are right insofar as this is not a solutuion but IMO just a workaround in order to keep me going. The solution would be to reopen the ticket and implement backward-compatible behaviour.

You are also right with regard to the symbolic link. I double-checked what MSYS2/MINGW *ln -s* actually does: Unfortunately it does not create a Windows-style NTFS symlink (junction) as could be expected from a Windows port for UNIX tools. Thus, I tried *ln* in hard link mode and this one works by creating actual hardlinks on Windows:

    ln -f /c/ProgramData/Git/config /mingw64/etc/gitconfig

How to test the result:

    $ fsutil hardlink list /c/ProgramData/Git/config
    \Program Files\Git\mingw64\etc\gitconfig
    \ProgramData\Git\config

BTW, I also edited each file and double-checked the the other one is also changed. It does work.

**Comment by dscho** [comment]
> The solution would be to reopen the ticket and implement backward-compatible behaviour.

I am glad that you are volunteering. When can I expect the fix?

**Comment by kriegaex** [comment]
Dear Johannes, polemic answers will not get us very far. I am a user, not a contributor, and providing a patch or pull request is beyond my technical abilities. I have spent my time in order to describe the problem as good as I can, and if there is anything else I can do to provide more detailed info, such as debug logs or whatever, please let me know. I hope you understand. I was patient and willing to help as much as I can by providing a sample repository for you by means of which you could reproduce the problem, by providing command line code snippets, screenshots etc. This is my contribution as a client in order to help you do your job as a maintainer. I do hope this is okay for you.

**Comment by kriegaex** [comment]
Sorry to bother you again, but I noticed that Git 2.5.0 itself cannot read its own system configuration:

    Alexander@Xander-PC MINGW64 /
    $ git config --list --system
    fatal: unable to read config file 'C:\Program Files\Git\mingw64/etc/gitconfig': No such file or directory
    
    Alexander@Xander-PC MINGW64 /
    $ git config --system user.name "Alexander Kriegisch"
    error: could not lock config file C:\Program Files\Git\mingw64/etc/gitconfig: Permission denied

Don't you think this is a real bug? Should I open a new ticket for it?

**Comment by kriegaex** [comment]
Okay, I performed some more tests. This is it!

If `core.autocrlf=input` is set at ***global*** or ***llocal*** level, `mvn release:prepare` commits only changed lines. But if the setting is on ***system*** level, JGit (just like core Git) cannot find it, consequently committing a full diff because it thinks that `auocrlf` is empty.

I double-checked by cloning JGit 3.2.0 (old version used by Maven Release) and calling

    org.eclipse.jgit.pgm/target/jgit config --list | grep 'autocrlf'

This yields an empty result even though

    git config --list | grep 'autocrlf'

(please note the missing `--system` parameter) shows that the property is actually set.

After

    git config --global core.autocrlf input

it works:

    $ org.eclipse.jgit.pgm/target/jgit config --list | grep 'autocrlf'
    core.autocrlf=input

My conclusion is that `git config --list --system` should be repaired. I am expecting this Git regression bug also to repair the Maven Release Plugin as a consequence.

**Comment by kriegaex** [comment]
I found that upgrading Maven Release + JGit in my POM helps avoid this problem, see https://github.com/git-for-windows/git/issues/337#issuecomment-743970276.
