### ISSUE TITLE
Setup overwrites global (user) setting for core.editor on update

### ISSUE THREAD

**Issue by schtandard** [git-for-windows/git#3153]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

    ```
    $ git --version --build-options
    git version 2.31.1.windows.1
    cpu: x86_64
    built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
    sizeof-long: 4
    sizeof-size_t: 8
    shell-path: /bin/sh
    feature: fsmonitor--daemon
    ```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

    ```
    $ cmd.exe /c ver

    Microsoft Windows [Version 10.0.19042.868]
    ```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

    ```
    $ cat /etc/install-options.txt

    Editor Option: Atom
    Custom Editor Path:
    Default Branch Option:
    Path Option: Cmd
    SSH Option: OpenSSH
    Tortoise Option: false
    CURL Option: OpenSSL
    CRLF Option: CRLFAlways
    Bash Terminal Option: MinTTY
    Git Pull Behavior Option: Merge
    Use Credential Manager: Core
    Performance Tweaks FSCache: Enabled
    Enable Symlinks: Disabled
    Enable Pseudo Console Support: Disabled
    ```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

   Nope.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

    Bash.

 - What's the problem?

    Due to an issue with Atom, I have to reconfigure `core.editor`, which I did using
    ```bash
    git config --global core.editor "atom --wait --new-window"
    ```
    which is then reflected in the corresponding `%UserProfile%\.gitconfig` file as
    ```gitconfig
    [core]
      editor = atom --wait --new-window
    ```
    However, whenever I update Git for Windows, this is reverted to
    ```gitconfig
    [core]
      editor = \"C:\\Users\\wilde\\appdata\\Local\\atom\\app-1.55.0\\atom.exe\" --wait
    ```
    and I have to reconfigure it anew.

    I would have expected the installer to only change the `system` level settings, not the `global` ones. This is also indicated by [this comment][comment] to #2818. (An implementation to that feature request would also provide a way to get around this problem, but still this seems to be unintended behavior, which is why I am reporting it separately.)

[comment]: https://github.com/git-for-windows/git/issues/2818#issuecomment-694104225

**Comment by dscho** [comment]
@schtandard since you require custom options, I don't think you can use this:

> ```
> Editor Option: Atom
> Custom Editor Path:
> ```

But why not configure this as a custom editor? You already have the absolute path, and can then also specify the editor options.

> I would have expected the installer to only change the `system` level settings, not the `global` ones.

Git for Windows will only configure editors in the system config which are installed system-wide. But Atom only comes in a user-wide flavor, therefore Git for Windows configures it in the user-wide config.

**Comment by schtandard** [comment]
> Git for Windows will only configure editors in the system config which are installed system-wide. But Atom only comes in a user-wide flavor, therefore Git for Windows configures it in the user-wide config.

Ah, that makes sense.

> But why not configure this as a custom editor? You already have the absolute path, and can then also specify the editor options.

That works, thanks. However, I did find another issue in the process (#3155).
