### ISSUE TITLE
Unable to change git install location

### ISSUE THREAD

**Issue by ajl223** [git-for-windows/git#3161]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.867]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
(I have set my PATH variable to the folder I want to test if git will install to, and it didnt)

I believe the reason this is happening because git is trying to get my system config via a file that doesnt exist inside a temp/tmp folder (the temp/tmp folder gets created when the installation starts, it is named `is-[RANDOM6LETTERS]`
I have a video of these errors that give this off to me at the start

https://user-images.githubusercontent.com/70416702/113216731-c5480a00-924a-11eb-8805-8cf8dad8a619.mp4
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
Git Bash
```

**Comment by ajl223** [comment]
didnt mean to click close, heres the video that didnt embed because it was in markdown
https://user-images.githubusercontent.com/70416702/113216731-c5480a00-924a-11eb-8805-8cf8dad8a619.mp4

**Comment by ajl223** [comment]
> I believe the reason this is happening because git is trying to get my system config via a file that doesnt exist inside a temp/tmp folder (the temp/tmp folder gets created when the installation starts, it is named `is-[RANDOM6LETTERS]`
I have a video of these errors that give this off to me at the start
- from earlier in the post, if you need me to explain more other than these images than be specific and ill give you the details

1. upon opening the install I get this error (Unable to get system config)
![image](https://user-images.githubusercontent.com/70416702/113217295-b9a91300-924b-11eb-881d-d71dd717b1c9.png)

2. then I get this error (Could not read 'C:\Users\AJ\AppData\Local\is-7VBJG.tmp\git-config-get.txt')
![image](https://user-images.githubusercontent.com/70416702/113217345-cf1e3d00-924b-11eb-851c-bd479e099a68.png)

3. then I get the first error again

4. then I get the second error again

5. then it opens the install menu, I searched up how to change the git install directory and apparently I am supposed to get an option to change it after clicking next when I read the license, however I did not get it.

**Comment by rimrul** [comment]
If the installer detects a previous Git for Windows installation it hides the page where you select the installation target directory. You can force it to install to a new location by passing `/DIR="C:\new location\for\git"` as a command line argument.

I think that previous location might not exist anymore and that seems to be the reason for the other two error messages.

**Comment by dscho** [comment]
The first error message comes from here: https://github.com/git-for-windows/build-extra/blob/81eaf1b02ac175fedb431068424d0ffc0b5b781a/installer/install.iss#L744

The best fix would probably be to test whether the `git.exe` does not even exist before showing that error message, and in that case be quiet and write an empty temp file.

**Comment by dscho** [comment]
I'm AFK for the next few days, so why not give this a try yourself @ajl223?

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `install.iss`
4. build a new installer via `sdk build installer`
5. verify that that installer works as expected?
6. open a PR?

To test whether a file exists, you can use the [`FileExists()`](https://jrsoftware.org/ishelp/topic_isxfunc_fileexists.htm) function, and you could use [the `SaveStringToFile()`](https://jrsoftware.org/ishelp/topic_isxfunc_savestringtofile.htm) function to write an empty file.

**Comment by ajl223** [comment]
> You can force it to install to a new location by passing `/DIR="C:\new location\for\git"` as a command line argument.

command line where? in SDK?

**Comment by dscho** [comment]
> > You can force it to install to a new location by passing `/DIR="C:\new location\for\git"` as a command line argument.
> 
> command line where? in SDK?

On the command-line, when calling the installer.

**Comment by ajl223** [comment]
I am running the installer from an exe I have no command line as far as I can see

**Comment by rimrul** [comment]
You'd have to start that exe from a command line of some sort (cmd, powershell, ...) to pass it command line arguments.

**Comment by ajl223** [comment]
Did that, how would I pass the arguments? I am not very experienced with cmd

**Comment by rimrul** [comment]
basically just the filename of the exe, followed by a space, followed by the arguments.

**Comment by ajl223** [comment]
yeah I got it working, it installs to the correct location I just did
```
start git-install.exe /DIR="C:\Users\AJ\Desktop\workspace"
```
while in the place where the exe is, but how can I uninstall the other versions git is detecting?
