### ISSUE TITLE
Use of uninitialized value in sprintf at C:/Program Files/Git/mingw64/libexec/git-core\git-add--interactive line 564

### ISSUE THREAD

**Issue by dletozeun** [git-for-windows/git#3162]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.867]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add -i
```
 - What did you expect to occur after running these commands?

Show the list of local modifications, nothing more.

 - What actually happened instead?

List of local modifications with for some modifications interleaved prints of:
Use of uninitialized value in sprintf at C:/Program Files/Git/mingw64/libexec/git-core\git-add--interactive line 564

Making difficult the readability of the output.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It is probably related to the printed local changes strings however I can't provide the repository. However the error is clear even providing the line of code in fit source code.

**Comment by dscho** [comment]
Does it work as desired after you call `git config --global add.interactive.useBuiltin true`?

> I can't provide the repository. However the error is clear even providing the line of code in fit source code.

That will make it almost impossible to reproduce the problem for others. You would at least have to try to describe the scenario better, ideally trying to recreate it in a fresh, new repository to which you add files that are roughly in the same shape as the files that cause the issue.

Just providing the line number helps not at all, there is nothing obviously wrong with https://github.com/git-for-windows/git-sdk-64/blob/da569dfa33591d8cc392d2532afcbbc80d0fb64a/mingw64/libexec/git-core/git-add--interactive#L564

**Comment by dletozeun** [comment]
Hello,

Thank you for  your feedback. `git config --global add.interactive.useBuiltin true` did fixed the issue! What does it do differently?

I'll try to recreate the scenario with dummy files but for now I can't find a way to reproduce it outside of this particular repo.

I actually managed to produce 2 errors now in two different locations:
`Use of uninitialized value in string eq at C:/Program Files/Git/mingw64/libexec/git-core\git-add--interactive line 393.` 
`Use of uninitialized value in sprintf at C:/Program Files/Git/mingw64/libexec/git-core\git-add--interactive line 564.`

The cause of the error is unclear however couldn't or shouldn't the code make sure the values are defined before using them?
https://perldoc.perl.org/functions/defined

**Comment by rimrul** [comment]
> git config --global add.interactive.useBuiltin true` did fixed the issue! What does it do differently?

It switches to the new builtin interactive add (i.e. the old perl script ported to C).

> The cause of the error is unclear however couldn't or shouldn't the code make sure the values are defined before using them?
> https://perldoc.perl.org/functions/defined

Sure, feel free to figure out what value is undefined there (under certain circumstances) and submit a patch. Calling defined for every variable before every function call would require five calls to defined just for that single call to `sprintf()`.
I guess you could do something like 

```perl
if (defined($status_fmt)){
    if (defined($print)){
         if(defined($print->{INDEX})){
             if(defined($print->{FILE})){
                  if(defined($value)){
                       $print = sprintf($status_fmt,
				                   $print->{INDEX},
		                  		 $print->{FILE},
			                  	 $value);
                   } else {
                       BUG("$value not defined");
               }} else {
                 BUG("$print->{FILE} not defined");
          }} else {
             BUG("$print->{INDEX} not defined");
    }} else {
        BUG("$print not defined");
}} else {
    BUG("$status_fmt not defined");
}
```

but that seems a little over the top for a single `sprintf()`.

**Comment by dscho** [comment]
The code obviously assumes that these variables are defined, and they usually are, too.

That is why it will be crucial to reproduce the issue reliably, so that the code path can be identified (and fixed) where they aren't.

A good starting point might be to start with a fresh repository, copying over the modified files' contents from the index (`git show :<filename>`), commit them, then copy over the modified files and see whether `git -c add.interactive.useBuiltin=false add -i` reproduces the issue.

If it does, try to reduce the problem surface by removing a few files, or by reducing the file contents. Reducing is the name of the game here.

**Comment by dletozeun** [comment]
Hello,

> A good starting point might be to start with a fresh repository, copying over the modified files' contents from the index (git show :<filename>), commit them, then copy over the modified files and see whether git -c add.interactive.useBuiltin=false add -i reproduces the issue.

Indeed, but to give you are really detailed answer: This is happening in a git repo made from a [Unity editor](https://unity.com/) project so it is not possible to isolate the files that cause the problem without breaking the Unity project which needs to work to generate these local modifications. It is all generated by the editor itself on files where mainly some line endings have changed.

> Sure, feel free to figure out what value is undefined there (under certain circumstances) and submit a patch. Calling defined for every variable before every function call would require five calls to defined just for that single call to sprintf().

Sure, I have added some debugging in the Perl script and for the particular issue happening on line 564 the problem is that `$print->FILE` is undefined. I have no idea why as I am not familiar with the git project but if you think it is worth further investigation, I can with your help debug further if you need more information.

Meanwhile I am very happy with your workaround. Just asking candidly, why is it not the default configuration yet, if the Perl script is the old implementation?

Thank you for your help.

**Comment by dscho** [comment]
For the purpose of the reproducer, the Unity project is totally irrelevant. The reproducer can be totally dysfunctional, as long as it reproduces the Git issue.

In fact, once you're done, it won't look like a Unity project at all. It could turn into a repository with two files called "rain" and "sunshine" containing just a few lines generated via `seq`, a `.gitattributes` file and probably having some line ending issues.

As to the built-in not yet being the default: we only changed `feature.experimental` to enable it one or two versions ago. Things don't change too quickly in Git.

**Comment by rimrul** [comment]
The scripted version of `git add -i` is being removed with v2.40.0.
