### ISSUE TITLE
Get error  error:1408F10B:SSL routines:ssl3_get_record:wrong version number" on win 10 2004

### ISSUE THREAD

**Issue by jjqtony** [git-for-windows/git#3169]
when git clone any repo, get error:
 error:1408F10B:SSL routines:ssl3_get_record:wrong version number 

git for windows 2.31 on windows 10 2004.

Two months ago, it works well on my computer, but now,  it cannot work.

**Comment by rimrul** [comment]
We provide an issue template for a reason.

>when git clone any repo, get error:
 error:1408F10B:SSL routines:ssl3_get_record:wrong version number

I'd be willing to bet you only get this error message for `https://` remotes.

This doesn't sound like a git error message. `ssl3_get_record()` is a method from openssl, so I'd guess the message is from there (or less likely from curl) as well. Does it work if you switch the curl backend to winssl?
