### ISSUE TITLE
Home directory incorrect, bashrc not running

### ISSUE THREAD

**Issue by erquhart** [git-for-windows/git#317]
In msysgit, I could run the bash and it would accurately default to my user account folder as the home directory, and would pick up config files there such as .bashrc automatically. Git for Windows 2.x does not do this, although it does echo the tilde character as the proper folder, and manually executing the `bash` command does trigger evaluation of my .bashrc file.

I ended up reverting back to msysgit just to get things going again after a clean Win10 install.

Am I missing something? Also, the old bash worked great with conemu, while Mintty simply doesn't. The option would be nice, I think.

**Comment by dscho** [comment]
@erquhart probably similar to https://github.com/git-for-windows/git/issues/313: what's `env | grep -e HOME -e USERPROFILE` say?

**Comment by dscho** [comment]
Feel free to reopen if you have a chance to perform more investigation.
