### ISSUE TITLE
Git clone freezes indefinitely without errormessage

### ISSUE THREAD

**Issue by arndtp** [git-for-windows/git#3173]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.28.0.windows.1
cpu: x86_64
built from commit 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

also tested on gitversion: 
2.24.1
2.26.1
2.27.0
2.29.0
2.31.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19042.906]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

install-options.txt:
```
Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```
system gitconfig:
```
[diff "astextplain"]
	textconv = astextplain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[http]
	sslBackend = openssl
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[core]
	autocrlf = false
	fscache = true
	symlinks = true
	editor = \"C:\\\\Program Files (x86)\\\\Notepad++\\\\notepad++.exe\" -multiInst -notabbar -nosession -noPlugin
[pull]
	rebase = false
[credential]
	helper = manager
```

global .gitconfig:
```
[http]
	sslVerify = false
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The repository is hosted on a self-hosted gitlab-server. We also tried copying it to the Azure DevOps-Cloud but it did not help the issue.
The repository contains 6397 LFS-files.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone git@git.pdv-software.de:pdv-software/entwicklung.net.git
```
 - What did you expect to occur after running these commands?

successful clone of the repository

 - What actually happened instead?

During the steps "updating files" or "filtering content" the process freezes without any errormessage. The freeze is indefinite. We let it run over night without any progress. The repository is missing most of the LFS-files when the freeze happens.
The freeze doesn't occur everytime and it's also not deterministic at which time/percentage it's freezing.
When we exit the console the git-lfs process does not exit properly, we need to terminate it via the task-manager.
If you need logs we can provide the ones you need. 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It's a private repository, we cannot give you access to it.

**Comment by dscho** [comment]
>  The freeze doesn't occur everytime and it's also not deterministic at which time/percentage it's freezing.

That's worrisome.

Maybe you can try the same in `Git CMD`? (Sometimes, problems occur with terminal output in Git Bash)

And you could also set `GIT_LFS_PROGRESS` to an absolute path of a log file, then inspect that. More ideas here: https://github.com/git-lfs/git-lfs/blob/bc59f83228ae055a69f1fd2c2f3ae60fa8160bc6/docs/man/git-lfs-config.5.ronn

**Comment by arndtp** [comment]
Most of the time the process freezes in "Updating files" when the `GIT_LFS_PROGRESS`-log hasn't been created yet.  
We have been running a frozen process on `Git CMD` for the past 15 minutes without any more output. We will test some more git-lfs config options now.

**Comment by arndtp** [comment]
The windows `Git CMD` does not behave any different after 45 minutes.  
We have changed the following git-config lines to no avail.  
```
[lfs "transfer"]
	maxretries = 4
	maxretrydelay = 2
	maxverifies = 2
[lfs]
	cachecredentials = false
	storage = D:/git/lfs/
	concurrenttransfers = 4
	basictransfersonly = true
	skipdownloaderrors = true
```
The `GIT_LFS_PROGRESS` does not provide useful information on successful tries and has not been written on the failed tries.

**Comment by dscho** [comment]
Hmmm. I have no clue. Maybe loop in the Git LFS team, they might have ideas?

**Comment by dscho** [comment]
Thank you for opening this ticket!

**Comment by dscho** [comment]
Seems to have been yet another Microtrend issue.
