### ISSUE TITLE
Add Man Pages?

### ISSUE THREAD

**Issue by naveen521kk** [git-for-windows/git#3180]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

*Sorry for not following the template seems unnecessary.*

- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

On an MSYS2 shell, doing `man git` or `man git commit` will open git's manpage which I like using mostly. When I tried the same on Git For Windows's shell, it said 
```sh
$ man git
bash: man: command not found
```
Should it be fine to add [`man-db`](https://packages.msys2.org/base/man-db) to Git for Windows also? It also needs to install git's man pages.

**Comment by dscho** [comment]
>  I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I was able to find https://github.com/git-for-windows/git/issues/696 ;-) And what [I said there](https://github.com/git-for-windows/git/issues/696#issuecomment-196515495) is still true:

> Man pages are something for developers who seek a software distribution that is based on a package management software. Git for Windows is not such a software distribution. You are looking for [MSYS2](https://msys2.github.io).

**Comment by naveen521kk** [comment]
(forgot to see closed issues)
