### ISSUE TITLE
Taskbar icon displays incorrectly on large monitor

### ISSUE THREAD

**Issue by bmcdonnell-fb** [git-for-windows/git#3184]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.928]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
Plink Path: c:\Program Files\PuTTY\plink.exe
SSH Option: Plink
Tortoise Option: true
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Windows display settings:

![image](https://user-images.githubusercontent.com/81983488/115064006-5f01ef00-9eba-11eb-8931-ffac8ec79b34.png)

Display 1

![image](https://user-images.githubusercontent.com/81983488/115064045-704afb80-9eba-11eb-8fa8-8d8055ed633b.png)

Display 2

![image](https://user-images.githubusercontent.com/81983488/115064128-91135100-9eba-11eb-8fed-990b66feb6fa.png)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
[none]
```
 - What did you expect to occur ~~after running these commands~~?

Git Bash taskbar icons appear the same on all displays, with the image filling most of the space, like this.

![image](https://user-images.githubusercontent.com/81983488/115064992-945b0c80-9ebb-11eb-807c-95a37266346d.png)

 - What actually happened instead?

Git Bash icon on taskbar of high resolution display (1) appears shrunken.

![image](https://user-images.githubusercontent.com/81983488/115065064-ad63bd80-9ebb-11eb-9439-cb4390175c03.png)

It appears correctly on the lower resolution displays (2 & 3).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by rimrul** [comment]
We really don't have much influence over how Windows renders the taskbar icon. The only thing we can do, is change the resolutions we include in our application icon, but Windows should scale the ones we do include to the resolution it needs, if we don't include the needed size. While not always pretty, it should be able to generate an icon in the desired size, if needed.

We currently include 256x256, 128x128, 64x64, 48x48, 32x32, and 24x24. We could include more resolutions, but we'd need to know what resolution you need. For me it looks good, even at 250% UI scaling.

[This forum thread](https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings-winpc/taskbar-icons-some-are-normal-sized-some-are-so/be95f0c6-c736-4981-ab5f-73831be9cab4) seems to indicate that this behaviour might also be related to which monitor is configured as your primary monitor.

**Comment by dscho** [comment]
Maybe @bmcdonnell-fb could provide an updated icon, generated from the `.svg` we have in `build-extra` (I think)?

**Comment by bmcdonnell-fb** [comment]
> [This forum thread](https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings-winpc/taskbar-icons-some-are-normal-sized-some-are-so/be95f0c6-c736-4981-ab5f-73831be9cab4) seems to indicate that this behaviour might also be related to which monitor is configured as your primary monitor.

Indeed, the issue only occurs when the higher resolution monitor (with upscaling) is *not* set as the primary. And only with the "Use small taskbar buttons" option set to Off.

![small-taskbar-buttons-off](https://user-images.githubusercontent.com/81983488/115115249-5ca6a000-9f61-11eb-9574-f3cce5443239.png)



Additionally, I see that it affects some other programs, too. KDiff3 and PuTTY are affected similarly, for example. Notepad++ looks to be the right size, but uses a different icon.

![taskbar-icon-comparison](https://user-images.githubusercontent.com/81983488/115115376-39302500-9f62-11eb-8661-be465b9ee480.png)

**Comment by bmcdonnell-fb** [comment]
@dscho 

> Maybe @bmcdonnell-fb could provide an updated icon, generated from the `.svg` we have in `build-extra` (I think)?

Can you instead use the `.svg` file as the icon directly? That should theoretically resolve the problem in all situations, instead of just for some range of setups.

This page suggests you can: [Icons for Windows apps](https://docs.microsoft.com/en-us/windows/uwp/design/style/icons#use-a-scalable-vector-graphics-svg-file).

> ## Use a Scalable Vector Graphics (SVG) file.
> SVG resources are ideal for icons, because they always look sharp at any size or resolution. Most drawing applications can export to SVG. For instructions, see [SVGImageSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.svgimagesource).

> ## You can also use a bitmap image, such as PNG, GIF, or JPEG, although we don't recommend it.
> Bitmap images are created at a specific size, so they have to be scaled up or down depending on how large you want the icon to be and the resolution of the screen. When the image is scaled down (shrunk), it can appear blurry; when it's scaled up, it can appear blocky and pixelated. If you have to use a bitmap image we recommend using a PNG or GIF over a JPEG.

**Comment by dscho** [comment]
Can you first make sure that Windows 7, 8, and 8.1 support `.svg` as icons (otherwise we can't use this)?

**Comment by rimrul** [comment]
> Namespace: Windows.UI.Xaml.Media.Imaging 

There's no way that works for native applications. .NET might be plausible, but it's probably just for UWP apps.

**Comment by bmcdonnell-fb** [comment]
@dscho 

> Can you first make sure that Windows 7, 8, and 8.1 support `.svg` as icons (otherwise we can't use this)?

My bad. Apparently [not](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.svgimagesource?view=winrt-19041#windows-10-requirements).

I found some more relevant info; coming soon.

**Comment by bmcdonnell-fb** [comment]
> > Namespace: Windows.UI.Xaml.Media.Imaging
> 
> There's no way that works for native applications. .NET might be plausible, but it's probably just for UWP apps.

Sorry, I'm not that familiar with the various platforms and versions in Windows app development.

On further reading, it seems my previously-posted links might not have even been relevant on supported platforms. This one looks to be more on-target, but I'm not sure if it's relevant for your development platform.

[App icons and logos - UWP Applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos)

**Comment by rimrul** [comment]
That also seems to only apply to UWP apps, not classic desktop applications.

**Comment by rimrul** [comment]
Ok, looking into it some more we probably can't use any vector graphics. We can add more resolutions, though.

Windows 10 technically allows you to freely specify scaling factors from 100% to 500% and seems to suggest 25% increments below 200% and 50% increments above that. So I've gone ahead and added some more layers to our `.xcf`:
* 16x16 (small icons at 100%)
* 20x20 (small icons at 125%)
* 28x28 (small icons at 175%)
* 40x40 (small icons at 250%, medium icons at 125%)
* 56x56 (small icons at 350%, medium icons at 175%)
* 60x60 (large icons at 125%)
* 72x72 (small icons at 450%, large icons at 150%)
* 80x80 (small icons at 500%, medium icons at 250%)
* 84x84 (large icons at 175%)
* 96x96 (medium icons at 300%, large icons at 200%)
* 112x112 (medium icons at 350%)
* 144x144 (medium icons at 450%, large icons at 300%)
* 160x160 (medium icons at 500%)
* 168x168 (large icons at 350%)
* 192x192 (large icons at 400%)
* 216x216 (large icons at 450%)
* 240x240 (large icons at 500%)

And, due to the magic of PNG compression (that should be supported since vista, so we're probably fine there) the `.ico` file even comes out ~15% smaller than our original.

I'll prepare a PR, so we can create a test build.

**Comment by bmcdonnell-fb** [comment]
@rimrul 

> That also seems to only apply to UWP apps, not classic desktop applications.

For future reference, where would one find the relevant platform documentation? (Analogous to the UWP links I had posted above.)

**Comment by rimrul** [comment]
https://docs.microsoft.com/en-us/windows/win32/, mostly.

**Comment by dscho** [comment]
Closed via https://github.com/git-for-windows/build-extra/pull/337

**Comment by bmcdonnell-fb** [comment]
I installed the latest version, and rebooted. This issue persists.

```
$ git --version
git version 2.32.0.windows.1
```

![image](https://user-images.githubusercontent.com/81983488/121428946-5f5fb900-c944-11eb-9428-5ecf0dac3f17.png)

**Comment by rimrul** [comment]
I'll take a look at the notepad++ sources and see if I can find anything special they do with their icon...

**Comment by rimrul** [comment]
Scratch that. The SDKs didn't pick up the new icon. The icon in 2.32.0 is the old icon. 

Great.

**Comment by rimrul** [comment]
Ok, `mingw-w64-git` would have needed an update as well.
