### ISSUE TITLE
There is a lack of packages for the good functioning of the extensions.

### ISSUE THREAD

**Issue by Evgenioni** [git-for-windows/git#319]
Many developers use git flow and legit in their work. The packeges getopt and python are required for those extensions.
Really miss pacman…

**Comment by dscho** [comment]
> Really miss pacman…

Why don't you just install [MSys2](https://msys2.github.io/)? Its `mingw-w64-git` package will be the same as ours [Real Soon Now](https://github.com/git-for-windows/git/issues/284).

BTW there is a terribly nice search function in GitHub's issues ;-)
