### ISSUE TITLE
"E: Unable to locate package coccinelle" with the projects github actions

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#3193]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Summary, the CI job didn't find coccinelle. I'm not sure why, given the same jobs, I believe, run OK for the main Git for Windows. Maybe there's some special button or option I need to preset?

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

(n/a) but
git version 2.29.2.windows.1.1.g3464b98ce6
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.928]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This is a short patch https://github.com/PhilipOakley/git/tree/vs-sln on top of the git-for-windows/git `main` tree, being pushed to my GitHub repo, triggering the CI, with email response "Run failed: CI/PR - main (aa53eac)".
https://github.com/PhilipOakley/git/runs/2409185889?check_suite_focus=true

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Push was via the `git gui` started from `bash`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here ** `push` ..?
```
 - What did you expect to occur after running these commands?

Coccinelle to be found by the CI

 - What actually happened instead?

CI didn't find Coccinelle 
```
Reading package lists...
+ sudo apt-get -q -y install coccinelle libcurl4-openssl-dev libssl-dev libexpat-dev gettext make
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package coccinelle
Error: Process completed with exit code 100.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/PhilipOakley/git/tree/vs-sln

**Comment by PhilipOakley** [comment]
A quick follow up search on the Git List found https://lore.kernel.org/git/CACPHW2WbY+c914vHV8cjfBC1GstF7PxfQFr-NF=EUhcF0YaCzQ@mail.gmail.com/ reporting a similar issue, but no reply on that thread.

**Comment by dscho** [comment]
Umm, are you running this based on an old version? https://github.com/PhilipOakley/git/commit/aa53eac68c4a200b91b3d3bba705f3264f41cb59 is `v2.30.0-rc1.windows.1^0`. And yes, there have been updates to the GitHub workflow in the meantime, most notably c6102b758572c7515f606b2423dfe38934fe6764

**Comment by PhilipOakley** [comment]
I thought I'd rebased the patch 'series' on top of your master but I must have made a mistake somewhere with that (probably setting the upstream). I'll try again.

I'm also trying to create a clean "Visual Studio" so I can test from a clean start, just to avoid fall out from the various tool caches. "90% complete, 50% to go..."

**Comment by PhilipOakley** [comment]
@dscho 
I think I've solved my PEBCAK problem. It looks like that `push` I mentioned actually pushed two branches, one of which (`main`) was old, and is the one that failed. (commonly I'm using the git-gui for the commit/push aspects, but not that time)

Meanwhile my original and rebased `vs-sln` branch pushes both also triggered a CI run, but without failure, so I was confused by the single failure notification email as no email was sent for the passed tests and I mistook the failure notification as being for the vs-sln branch. I hadn't paid much attention to the https://github.com/PhilipOakley/git/actions page before.

Thanks for your feedback.
