### ISSUE TITLE
commits attributed to no account

### ISSUE THREAD

**Issue by WilliamDAssafMSFT** [git-for-windows/git#3198]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

10 64bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.928]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

1.	New laptop. I set up my work account in gitbash.
2.	Installed and used Github Desktop with a personal Github account, for external repositories.
3.	My commits for work account to work repositories were being recorded as personal account. I realized the issue was with the github user.name and user.email, I fixed them.
4.     Including the above only because they were unusual. Not sure if related at all to the below unattributed commits.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Gitbash in VS Code

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
 git commit -m "20210416 1034"
```
 - What did you expect to occur after running these commands?

Commits are attributed to my account as usual.

 - What actually happened instead?
**Commits are not attributed to anyone.**
https://github.zendesk.com/attachments/token/RT3I8P5lQZBFspjwOUU4OLq30/?name=image.png
https://github.zendesk.com/attachments/token/7QuoJi9c9vVxZbRMemGO1aRXK/?name=image.png

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It is a private repository unfortunately.

**Comment by rimrul** [comment]
Github associates the committer account using the email. It looks like you configured `user.email` to some address that is not associated with your account.

You also seem to have configured your `user.name` to be `=`. While that isn't a problem for Git or GitHub, your coworkers might not be impressed by that.

**Comment by WilliamDAssafMSFT** [comment]
@rimrul  thanks for the reply. I understand what it appears to look like, but both `git config --global user.name` and `git config --global user.email` return valid, correct values. The user.email is the noreply email copy-pasted from my github profile.

**Comment by rimrul** [comment]
Maybe `git config --get-all --show-origin user.email` can shed some light onto this?

**Comment by WilliamDAssafMSFT** [comment]
I see three entries... One for each of my accounts, and two are duplicates. What should I have?

**Comment by dscho** [comment]
> The user.email is the noreply email copy-pasted from my github profile.

That is not the email address you want to use. Instead, you want to use any email listed in https://github.com/settings/emails (they need not be public in that list to fix the attribution).

Please note that the reported problem is actually not a Git for Windows one, but seems to be a GitHub usage question instead.
