### ISSUE TITLE
Please clarify "Use a TrueType font in all console windows" option in installer.

### ISSUE THREAD

**Issue by user1568891** [git-for-windows/git#321]
What are the pros and cons to selecting "Use a TrueType font in all console windows"? I did some Googling and could only find vague explanations that it would make fonts look better in the console, but nothing about possible negative side effects or what the alternative is. I apologize if this is the wrong place to ask this- let me know if not and I'll post this question somewhere else.

Thanks!

**Comment by dotchaydobe** [comment]
gfrdfr

**Comment by dscho** [comment]
@dotchaydobe let's try to be a bit more helpful, okay?

@user1568891 Typically a better place to ask questions is the mailing list (linked on the top right of [Git for Windows' home page](http://git-for-windows.github.io/)).

Having said that, [here](https://github.com/git-for-windows/build-extra/blob/8d0f0486c811d8e5422436acc99183a96e1cdf1f/installer/ReleaseNotes.md#bugfixes-25) is an explanation why we introduced that option: to support non-ASCII characters better. E.g. when the user wants to use filenames made up of Chinese or Cyrillic characters, TrueType is a must.

Now, I do not know of any downside (apart from certain individuals preferring the default font), so I always use the TrueType option myself.

Please note also that this concerns only the standard Windows console, not the mintty terminal emulator we use by default in Git for Windows 2.x.

Hopefully this addressed your questions?

**Comment by user1568891** [comment]
@dscho It did- thanks for the explanation.

**Comment by linquize** [comment]
Because in git-for-windows 2.0, mintty is used by default

**Comment by Fish-Git** [comment]
> Having said that, here is an explanation why we introduced that option: to support non-ASCII characters better. E.g. when the user wants to use filenames made up of Chinese or Cyrillic characters, TrueType is a must.

I'm not sure why you feel the correct resolution of this issue is to have your  _installer_ mess with the user's Command Prompt font settings (seems silly to me), but I've personally written console apps on Windows that appear to display UNICODE/UTF8 characters just fine.

You just need to build your app as a UNICODE app and then set the console mode appropriately at the very beginning of `_tmain`:

```C++
    // UNICODE support...

    // The following allows special characters to display properly
    // for _UNICODE builds.

    #ifdef _UNICODE
      #define CONMODE   _O_U16TEXT      // (i.e. 'UNICODE' mode)
    #else
      #define CONMODE   _O_TEXT         // (regular 'text' mode)
    #endif
```

```C++
    int _tmain( int argc, _TCHAR* argv[] )
    {
        // (the following ensures proper display of UNICODE characters)

        _setmode( _fileno( stdout ), CONMODE );
        _setmode( _fileno( stderr ), CONMODE );

        [...]
```

Does this technique not work for you?

**Comment by dscho** [comment]
> I'm not sure why you feel the correct resolution of this issue is to have your installer mess with the user's Command Prompt font settings (seems silly to me)

Let's tone down the rest of the conversation. (If your intention is to convince me that I am wrong, I have to tell you that this way won't work.)

The installer only modifies the settings when that checkbox is checked.

> Does this technique not work for you?

If it works for you, the appropriate thing would be to open a Pull Request.
