### ISSUE TITLE
git bisect is broken

### ISSUE THREAD

**Issue by 89z** [git-for-windows/git#3211]
If I run these commands:

~~~
git bisect start
git bisect new
git bisect old @~10
git bisect skip
~~~

With this Git:

~~~
Git-2.31.1-64-bit.exe
~~~

Nothing happens. However if I use older version:

~~~
Git-2.30.0-64-bit.exe
~~~

I get correct result:

~~~
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[9af12f451c4b15a6a5fe108c509e20236fb4a1b1] Move code outside of a lock
~~~

**Comment by 89z** [comment]
I did some more testing, this is the last good version:

https://github.com/git-for-windows/git/releases/tag/v2.30.2.windows.1

I will be using that until this is fixed.

**Comment by rimrul** [comment]
Specifically, `git bisect skip` is broken when you use terms other than `good` and `bad`. A fix is in the works [on the git mailing list](https://lore.kernel.org/git/fa098676-a56c-cbb9-28cb-e57d4a8a5d77@ramsayjones.plus.com/).

**Comment by dscho** [comment]
@89z it has been integrated into upstream's `next` branch as https://github.com/git/git/commit/4cd66e7d6b423d3c5b161b55afb07cb1df59e75f.

I triggered a `git-artifacts` build which should produce the PortableGit and the installer artifacts: https://github.com/git-for-windows/git/actions/runs/816164406

You could verify whether this fixes your problem by downloading one of the two artifacts (once the build finished) and running the commands you mentioned.

**Comment by 89z** [comment]
Thanks. I will assume this is fixed, as I am not going to run this installer again to try to test it. I use my [own package installer][1] to install Git. Side note, the Git for Windows installer is way too complicated. It has at least 10 screens:

1. Information
2. Select Destination Location
3. Select Components
4. Select Start Menu Folder
5. Choosing the default editor used by Git
6. Adjusting the name of the initial branch in new repositories
7. Adjusting your PATH environment
8. Choosing HTTPS transport backend
9. Configuring the line ending conversions
10. Configuring the terminal emulator to use with Git Bash

[1]:https://github.com/89z/sienna/tree/master/cmd/install-msys2

**Comment by dscho** [comment]
Wow, if you ever wanted to show your appreciation for other people's hard work, there would have been better ways.
