### ISSUE TITLE
Failed to restrict file handles

### ISSUE THREAD

**Issue by awsunit** [git-for-windows/git#3215]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.928]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt



Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

Visual Studio Code

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
erroneous command of:
git checkoutfeature/movieCubeResurrection
```
 - What did you expect to occur after running these commands?
 - 

would checkout the branch feature/movieCubResurrection

 - What actually happened instead?
 - 
Told me this was a bug and to report it. Printed:

warning: failed to restrict file handles (2)
handle #0: 0000000000000054 (type 2, handle info (1) 7ffb
handle #1: 0000000000000124 (type 2, handle info (1) 1
handle #2: 0000000000000128 (type 2, handle info (1) 1

https://github.com/git-for-windows/git/issues/new

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'checkoutfeature/movieCubeResurrection' is not a git command. See 'git --help'.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by awsunit** [comment]
under what did I expect to happen:

I expected to checkout the branch IFF I had typed the command correctly

**Comment by rimrul** [comment]
> 2.16.2

Please try upgrading to a recent version of Git for Windows. That should fix it.

**Comment by dscho** [comment]
> > 2.16.2
> 
> Please try upgrading to a recent version of Git for Windows. That should fix it.

In addition, it will fix quite a number of critical vulnerabilities.

**Comment by awsunit** [comment]
confirming that updating fixed the issue
