### ISSUE TITLE
Windows installation error setting configurations

### ISSUE THREAD

**Issue by pnojai** [git-for-windows/git#3226]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
```

git version 2.32.0.rc0.windows.1.4.gde4a643419.20210517161711
cpu: x86_64
built from commit: de4a643419c7ab387ce8121c03a60e6211e0cf26
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
```
Microsoft Windows [Version 10.0.18363.1500]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```

Defaults:
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I looked closed issue #2384. The explanation seemed familiar, since I have installed, uninstalled, and reinstalled Anaconda Python multiple times. However, the orphaned registry key behind that issue is not present in my registry anyway. Therefore, I presume my issue is new.

[HKEY_CURRENT_USER\Software\Microsoft\Command Processor]

### Details
Per the resolution of #2384, I run the latest snapshot of the Windows installer as an Administrator. At the end of the installation, there are a series of configuration entries made using the Windows command shell. It raises a series of errors like this screenshot, which say that permission is lacking on the etc directory, even though I ran the installer as an Administrator.

![image](https://user-images.githubusercontent.com/31191450/118688055-afc77900-b7d3-11eb-8d43-3df3d2948cf7.png)

Is this related? I noticed when I first ran Git Bash, there were errors that it couldn't create symbolic links. I tried running Git Bash as an Administrator and got this output before the prompt.

'C:\WINDOWS\system32\drivers\etc\hosts' -> '/etc/hosts'
'C:\WINDOWS\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\WINDOWS\system32\drivers\etc\services' -> '/etc/services'
'C:\WINDOWS\system32\drivers\etc\networks' -> '/etc/networks'

Now when I run Git Bash again, not as an Administrator, I no longer get the error messages about creation of symbolic links.

I didn't encounter the installation issue or the Git Bash issue when I last installed Git on this device. I don't remember what version that was, but it was the current release as of October 2020.

**Comment by dscho** [comment]
Thank you for your report!

And darn, is that "Unable to set system config" issue back? I hoped we had solved that once and for all. I do see that the current installer still runs `cmd` with `/d` to disable the `AutoRun`, so that's probably not it.

Can you verify that you can run run the following commands in a PowerShell as administrator?

```powershell
cd "C:\Program Files\Git"
cmd /d /c .\mingw64\bin\git.exe config --system hello.world hi
```

> Microsoft Windows [Version 10.0.18363.1500]

I have "Microsoft Windows [Version 10.0.19043.985]", which looks substantially newer. Maybe that has anything to do with anything?

Or maybe you have an especially clamped-down `C:\Program Files`?

And maybe I should ask this first, because you indicated that running the installer as administrator made a difference: did the installer ask to be run elevated? (It should.)

**Comment by pnojai** [comment]
Yes to the installer asking about running with elevated rights.

To execute the installer, I right-click it and select to run it as an Administrator. Then I get 3 challenges about running elevated. I see it trying to run the command shell. After those, I advance to the screen with the GNU License. I take the default components and all the default configurations. The installation proceeds with the progress bar showing all the extracted files.

At the end, I get the elevation challenges again as the installer attempts to execute from the command shell. Each time I get the challenge, I confirm the execution, but nevertheless get an error message such as the one I pasted in the ticket.

**PowerShell**

No, I got this message when I tried to run the `hello.world` command:

error: could not lock config file C:/Program Files/Git/etc/gitconfig: Permission denied

Yes, I believe I do have an especially clamped down `C:\Program Files`! This is a corporate device and it's hard to install tools. 

However, when I installed Git last October, I didn't encounter an issue. I upgraded now in hopes of resolving another thing going on (not this issue). It made me think the installer had changed. Considering your PowerShell it, it makes me wonder if it could be my environment that changed. I know the enterprise has rolled out changes and maybe those are behind this. Perhaps this isn't a Git issue really.

**Comment by dscho** [comment]
Perhaps. To get you unblocked, could you try running with Portable Git instead of the installer? You will have to add the `<Git>\cmd` directory to your `PATH` manually, and if you want a Start Menu item, add one pointing to `<Git>\git-bash.exe`. It should work even in clamped-down environments.

**Comment by pnojai** [comment]
Beautiful. I uninstalled Git and installed Portable Git within my Windows user directory. I can configure by hand with git config in Bash. I'm good to go.

I don't know if you want to keep this issue open. It isn't a bug exactly. It's a matter of what kind of support the installer can provide in an enterprise environment that restricts access to the directory of installation.

If you want that on your wish list, it's up to you. Otherwise, this alternative resolves the issue for me and you could close it.

Thanks for you help. It worked out great. I can give this solution to my team, too.

**Comment by dscho** [comment]
I would be happier if I knew _why_ it failed in the first place, but it would probably take way too much time and effort to investigate that, and since you're unblocked, I'll just close this ticket. Thank you for your feedback!

**Comment by pnojai** [comment]
I feel confident your hypothesis about a locked down Programs directory is it. On my enterprise device, I have a hard time with that.

I’m able to authorize some actions by running installers as an Administrator. I think the Git installer differs from others in that it runs command prompt commands in new processes at the end. Those are the ones my device complains about. I don’t know how to develop this, but my impression is that if the configuration file edits could somehow execute under the spawned process that already got granted Administrator authority at the beginning of the installation, then it wouldn’t raise the additional security challenges by the multiple command shell executions at the end. Just a brainstorming idea.

Anyway, this is a real edge case, isn’t it? I find the Portable Git alternative wholly effective and I appreciate it.

**Comment by dscho** [comment]
> I think the Git installer differs from others in that it runs command prompt commands in new processes at the end.

Indeed. But it tries to do that with the same credentials, i.e. as administrator: https://github.com/git-for-windows/build-extra/blob/7b657a7d585479d0420d4bce946cf8c45678e90d/installer/install.iss#L712. The reason this is called via `cmd` is that we need to redirect the output...

If it was just `stdout`, we could ask `git` to run a pager that outputs to a given file, but we are _especially_ interested in `stderr`...

_*thinking pause*_

But now that I think about it, we do have an opportunity here: https://github.com/git-for-windows/git/blob/v2.31.1.windows.1/compat/mingw.c#L3660-L3668

If we set `GIT_REDIRECT_STDOUT` and `GIT_REDIRECT_STDERR`, then we do not need `cmd` at all.

It is sadly a bit complicated to do that in InnoSetup, apparently [`Exec()`](https://jrsoftware.org/ishelp/index.php?topic=isxfunc_exec) does not have any facility to override the environment _just_ for the spawned process. So we would have to declare the Win32 API function:

```pascal
function SetEnvironmentVariableW(lpName: string; lpValue: string): BOOL;
  external 'SetEnvironmentVariableW@kernel32.dll stdcall';
```

We probably should _unset_ that environment variable immediately after `Exec()`, too...

**Comment by pnojai** [comment]
I don't think I know any of this programming, but if you wanted help testing this, or if you can think of any way that I can help, I would be happy to do it.

Like, I run my own hypervisor server at home. I can spin up VMs in various OSs (if I have an installer, usually it's Linux flavors, but if I can get Windows trials I suppose I could test those, too). I could also try out a test version of the Git installer on my work computer and see what sticks.

**Comment by dscho** [comment]
> It is sadly a bit complicated to do that in InnoSetup, apparently [`Exec()`](https://jrsoftware.org/ishelp/index.php?topic=isxfunc_exec) does not have any facility to override the environment _just_ for the spawned process. So we would have to declare the Win32 API function:
> 
> ```pascal
> function SetEnvironmentVariableW(lpName: string; lpValue: string): BOOL;
>   external 'SetEnvironmentVariableW@kernel32.dll stdcall';
> ```

Apparently, we already have this in `modules.inc.iss`, as `SetEnvironmentVariable()`. And we need not worry about problems with passing `NULL` to unset variables (which seems to be a notorious issue with InnoSetup: if you want to call an external function that takes an `LPWSTR` and you want to pass `NULL`, you have to declare it as a `LongInt` and pass `0` instead): Git for Windows already interprets an empty value the same as if the environment variable was turned off.

**Comment by dscho** [comment]
But I fear that this would only work when we spawn `git.exe` and not, say, when we spawn `schtasks.exe` (to register the daily check for updates).

Therefore, the redirection should probably be solved by calling `CreateProcessW()` directly, after `CreatePipe()` to handle `hStdError` and `hStdOutput`. Then we would need a busy loop that reads from the read ends of the pipe until hitting EOF. Some parts of this are implemented [here](https://github.com/conquerjoomla/android/blob/bdb976105b355f318999e9dff0ce63d70a9e4628/Source/Installer/binno/utility.iss#L685-L726).

**Comment by dscho** [comment]
Here is some _beginning_ of implementing this: https://github.com/git-for-windows/build-extra/pull/363

**Comment by dscho** [comment]
This should be fixed via merging that PR. Once the [Git artifacts run](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=80930&view=results) has completed, the [Snapshots release pipeline](https://dev.azure.com/Git-for-Windows/git/_apps/hub/ms.vss-releaseManagement-web.hub-explorer-2?definitionId=2&view=mine&_a=releases) should be triggered automatically to upload a new [snapshot](https://wingit.blob.core.windows.net/files/index.html).

@pnojai once this snapshot is available, could I ask you to test?

**Comment by pnojai** [comment]
Of course. Sounds awesome. Thank you.
