### ISSUE TITLE
Global .gitignore doesn't work

### ISSUE THREAD

**Issue by xahon** [git-for-windows/git#3227]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64 (maybe)

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10 - 64bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.985]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
nothing. Clean windows 10 i just installed

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global core.excludesfile $env:USERPROFILE\.gitignore_global
echo ".idea/" > $env:USERPROFILE\.gitignore_global 
mkdir test
cd test
git init
mkdir .idea/
cd .idea/
echo "a" > testfile
git status -s
```
i see `?? testfile`
expect to see no output

 - What actually happened instead?
prints `?? testfile`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
no

**Comment by dscho** [comment]
Thank you for your report.

I have a quick hunch (and not much time for anything else at the moment) that the issue might be the backslashes in the path. Could you edit the `core.excludesfile` setting (via `git config -e --global`) so that it is recorded with forward slashes instead, and then try again?

**Comment by rimrul** [comment]
No. The issue seems to be more subtle than that. I have my `core.excludesfile` configured to an absolute windows path (`C:\ …`) and it works fine for filename entries, but not directory entries.

**Comment by rimrul** [comment]
Oh. It's even dumber than that. `echo "foo">bar` in powershell produces the wrong file encoding.

**Comment by rimrul** [comment]
You'll want to use `echo ".idea/" | Out-File -Encoding utf8 $env:USERPROFILE\.gitignore_global`.

**Comment by dscho** [comment]
> 
> 
> Oh. `echo "foo">bar` in powershell produces the wrong file encoding.

🤦 of course! Thank you @rimrul for being more attentive than me.

**Comment by xahon** [comment]
Thank you all folks. It was due to encoding. I'm using neovim and it looks like it uses UTF-16 by default which git can't figure out
