### ISSUE TITLE
fatal: Authentication failed.

### ISSUE THREAD

**Issue by Satwikram** [git-for-windows/git#3229]
I have this version of git installed on my PC.

My Username and Password are correct but still, when I push my code from my PC it says Logon Failed.

I tried installing the latest version, but the latest version requires dot net 4.7.2 which is not supported on my PC.

Fix these issues. Both old and new version has bugs.

**Comment by Satwikram** [comment]
Logon failed, use ctrl+c to cancel basic credential prompt.
remote: Invalid username or password.

After Changing the password. Its shows like this. 

I even changed the windows credential manager also.

**Comment by rimrul** [comment]
> I have this version of git installed on my PC.

What version?

> My Username and Password are correct but still, when I push my code from my PC it says Logon Failed.

How are you trying to to push? SSH? HTTPS? 
Where are you trying to push? Github? Gitlab? Bitbucket? Some local server?

> I tried installing the latest version, but the latest version requires dot net 4.7.2

Git for Windows doesn't require .NET 4.7.2

Git Credential Manager Core does, but that's optional.

> which is not supported on my PC.

Ok, so you're on Vista.

> Fix these issues. Both old and new version has bugs. 

What old version? What new version? 

How can I reproduce the issue to figure out if there is indeed a bug?


We provide an issue template for a reason. Please provide some details about the affected Git for Windows Version(s) and an MCVE so we can reproduce your issue.

**Comment by Satwikram** [comment]
Hi Sorry, I taught I was raising the issue with a particular version of Git.

Here are my detailed problems I faced.

I was using git older version 2.14.2 on my Windows 10 Pro Version 1511.

It was working fine, but when I tried pushing the code it was asking me to enter my Credentials. 

When I entered my credentials, always it was throwing fatal: Authentication failed.

I asked a couple of folks and they asked me to upgrade to the latest version of Git.

In the latest version, it was showing Git Credential Manager Core requires .Net Version 4.7.2 in order to push the code.

I tried installing .Net 4.7.2 but it was not supporting as my windows version has blocking issues.

I Upgraded my Windows to the latest version 21H1 and now Git is working fine. 

But in the older version, it wasn't working.

I am surprised that the same Git version was showing fatal: Authentication failed on Windows Version 1511. but it is working fine in my Latest version of Windows 21H1. Maybe this issue might continue for Windows Version 1511 Users.

**Comment by dscho** [comment]
From https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10#net-framework-48:

> The .NET Framework 4.8 is not supported on:
>
> * Windows 10 1507
> * Windows 10 1511
>
> If you're using Windows 10 1507 or 1511 and you want to install the .NET Framework 4.8, you first need to upgrade to a later Windows 10 version.

So I think you did the right thing by upgrading your Windows version. I guess this ticket is thereby addressed and can be closed?

**Comment by Satwikram** [comment]
My issues Solved. Please close it.
