### ISSUE TITLE
Behavior of core.editor changed (broken)

### ISSUE THREAD

**Issue by Maximus5** [git-for-windows/git#323]
I use Far Manager as editor for commits and things.
`farrun.exe` is a wrapper which calls `far.exe` with proper arguments.

    > git config core.editor
    farrun -e1:1

But after updating to last version 2.5 it is broken:
the path of editing file is not conformable with Windows standards at all.
We are not on Unix. Windows applications require drive letter with colon.

    git version 2.5.0.windows.1
    C:\Utils\farrun.exe -e1:1 /c/Sources/ConEmu/.git/rebase-merge/git-rebase-todo
    
    git version 2.4.6.windows.1
    C:\Utils\farrun.exe -e1:1 C:/Sources/ConEmu/.git/rebase-merge/git-rebase-todo

**Comment by Maximus5** [comment]
Sorry for the noise.
Unexpectedly, cygwin binaries were found in the %PATH% first.

**Comment by dscho** [comment]
Which explains why I could not reproduce the problem ;-)
