### ISSUE TITLE
Installer cannot proceed if Sublime Text is selected, but ST4 is installed, not ST3.

### ISSUE THREAD

**Issue by SpacePotatoBear** [git-for-windows/git#3248]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

x64

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```
Windows 10

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1023]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: "C:\Program Files\Sublime Text\subl.exe" "-w"
Default Branch Option:  
Path Option: Cmd
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

```
 - What did you expect to occur after running these commands?

select sublime text, be able to hit next and install

 - What actually happened instead?

next greyed out, had to use a custom editor to work around it.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by rimrul** [comment]
Yes. The installer expects sublime text sytem installs to be located in "C:\Program Files\Sublime Text 3\". The fix should be fairly easy. I'll submit a PR later today.

**Comment by SpacePotatoBear** [comment]
> 
> 
> Yes. The installer expects sublime text sytem installs to be located in "C:\Program Files\Sublime Text 3". The fix should be fairly easy. I'll submit a PR later today.

Thanks,

**Comment by SpacePotatoBear** [comment]
Sorry not used to github's ui, Thanks @rimrul
