### ISSUE TITLE
Git clone freezes when trying to chcekout via ssh using plink and pagent when putty hasn't accepted the host's key

### ISSUE THREAD

**Issue by SpacePotatoBear** [git-for-windows/git#3249]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 64bit

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 Windows 10

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1023]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: "C:\Program Files\Sublime Text\subl.exe" "-w"
Default Branch Option:  
Path Option: Cmd
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

All three present the issue, including sublime merge.

the set up was followed, putty installed, with plink option, private key loaded into pagent.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone ssh://git@repo.url:7999/repo/name
```
 - What did you expect to occur after running these commands?

a prompt to accept the host key

 - What actually happened instead?

a text prompt appeared, but could not send any input (y/n/i/return)
git was frozen and had to be force killed.

resolve by using putty to ssh to the host, and accepting the host, and retrying the clone.

**Comment by dscho** [comment]
From our [Release Notes' "Known Issues" section](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * If configured to use Plink, you will have to connect with putty first and accept the host key.

I have no idea how to solve this any differently than describing the issue in the "Known Issues" section.

**Comment by SpacePotatoBear** [comment]
oh my apologies dscho I didn't see that. Feel free to close this as dup.

**Comment by dscho** [comment]
> oh my apologies dscho I didn't see that. Feel free to close this as dup.

If you have any idea how to resolve this in a better manner, please don't be shy and mention it :-)
