### ISSUE TITLE
git mv on non empty dir failed with bad source 

### ISSUE THREAD

**Issue by DimRochette** [git-for-windows/git#3250]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [version 10.0.19043.1023]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue?
```
mkdir test
cd test
git init
mkdir dir1\dir2
cd dir1\dir2
echo "something" >> somefile.txt
git add somefile.txt
cd ..
git mv * ../
```
 - What did you expect to occur after running these commands?

Command to work. 
In WSL on the same folder the `git mv * ../` pass.

 - What actually happened instead?
```
fatal: bad source, source=dir1/*, destination=*
```

**Comment by dscho** [comment]
> `fatal: bad source, source=dir1/*, destination=*`

In shells other than `cmd.exe`, it is the _shell_ that expands the wildcard. But in `cmd.exe`, nothing gets expanded. So the wildcard is interpreted as a literal file name.

I am afraid that Git does what it is expected here, and you simply need to either use a different shell, or a different method to specify what needs to be moved.

**Comment by DimRochette** [comment]
Thanks a lot for your answer.
My 3 options on windows are cmd, powershell and pwsh and none works like that. 
Will have to expand myself the wildcard on windows and linux if I want to have a portable script.

**Comment by dscho** [comment]
>  Will have to expand myself the wildcard on windows and linux if I want to have a portable script.

The (not quite optimal) usual recommendation is to use a shell script, or a shell script snippet to make things portable. It is not ideal, but a POSIX shell _is_ required by Git anyway, to run aliases. Therefore, this _might_ work in a portable manner:

```console
$ git -c alias.sh='!sh' sh -c git mv * ..
```

**Comment by dscho** [comment]
> Therefore, this _might_ work in a portable manner:
> 
> ```
> $ git -c alias.sh='!sh' sh -c git mv * ..
> ```

Sadly, it is a bit more complicated than that:

- single-quotes are not accepted by `cmd.exe` to quote arguments. But an exclamation mark inside double-quotes will be mishandled by an interactive Bash (it will try to expand into something found in the interactive history).
- when running aliases, Git automatically changes the working directory to the top-level directory of the worktree. You have to `cd "$GIT_PREFIX"`.

Therefore, in a `cmd.exe` (or a `.bat` script), this works:

```cmd
git -c alias.sh=!sh sh -c "cd \"$GIT_PREFIX\" && git mv * .."
```

It is not elegant, I will admit that.

**Comment by DimRochette** [comment]
Even if it's frustrating that same command don't bring the same results depending on OS/shell, I understand it's out of scope of the tool. 
I think we can close the issue.
