### ISSUE TITLE
Bash completion for aliases not working since Git 2.30.0

### ISSUE THREAD

**Issue by pbodnar** [git-for-windows/git#3253]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

After upgrading from Git 2.25, the bash completion stopped working - see details below.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.30.0.windows.1
cpu: x86_64
built from commit: 18da6dbba950f8cc7b7d07057f7c30bf7cf207b6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.985]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ alias g="git"
$ __git_complete g _git

$ g st<tab>
```
 - What did you expect to occur after running these commands?

The usual autocomplete function, i. e. the last line should change to:

```
$ g status
```

 - What actually happened instead?

With versions 2.30.x, the output looks like this:

```
$ g stbash: _git: command not found
```

With versions 2.31.x, the output seems to be equivalent to pressing `<enter>` instead of `<tab>`, i. e. Git help is shown in the command line.

 - Workaround

Downgrade to 2.29.x.

**Comment by dscho** [comment]
> ```
> $ alias g="git"
> $ __git_complete g _git
> 
> $ g st<tab>
> ```

This seems to pretend that the completion function `__git_complete` presents a public API, but that is not so. If `git st<tab>` still completes as it should, I fail to see a bug in Git for Windows here, just incorrect assumptions.

If you _do_ think that Git should support your use case, I would like to encourage you to take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently): This is not a Windows-specific issue at all.

**Comment by pbodnar** [comment]
@dscho, I'm sorry, but this _is_ the way how to setup Git aliases for a long time. I would expect more guidance here, moreover when Git authors drop such a feature "silently", even if it was never meant to be a public API... Thanks for responding anyway, at least now we know this will be a big issue on Linux as well. So I will just downgrade for now, although it is not good the best for security reasons...

**Comment by dscho** [comment]
To be honest, I rarely encounter users making a Bash alias for `git`...

**Comment by pbodnar** [comment]
Well, ok, although once one get used to it... At least your note made me retest _for other aliases_ - and strangely enough, it works for example for this one (tested with Git 2.30.0 and 2.31.1):

```
$ alias gp="git push"
$ __git_complete gp _git_push
```

So at least the problem is reduced just to aliasing `git` now. :)

**Comment by dscho** [comment]
Sure, I have my share of idiosyncratic usage patterns :-)

But really, I'd like to impress on you that the best avenue to discuss this _is_ the Git mailing list.
