### ISSUE TITLE
git-for-windows installer removed git from path.

### ISSUE THREAD

**Issue by WORMSS** [git-for-windows/git#326]
I had git in my %PATH% before running the new 2.5.0 installer. (I think I had 1.9.5.msys before).

I made sure I clicked the "Bash only" as the description says **"you PATH will not be modified at all."**

Then I guess during the uninstallation of the 1.9.5 version, it **did** modify my path.

It obviously did not install it again since I selected Bash-Only. But the only reason I selected it was because I did not want my path to be changed AT ALL. I have everything in a specific order, and I thought if I did "Git from the windows command prompt" it would move it's position.

Can there not be a "DONT TOUCH MY PATH AT ALL" option during installation that actually does what it says and does not modify the path?

**Comment by dscho** [comment]
The problem really is that the PATH is modified by the *uninstaller* of the previously installed Git for Windows.

I warmly invite you to make the appropriate changes to our InnoSetup configuration and contribute the fix. You would need to change these lines:

https://github.com/git-for-windows/build-extra/blob/1370d95452efa9904874284bee39aa1e150deabe/installer/install.iss.in#L1431-L1464

(I guess you would want [this `If` guard](https://github.com/git-for-windows/build-extra/blob/1370d95452efa9904874284bee39aa1e150deabe/installer/install.iss.in#L1442) to span the entire `PATH` modification block.)

Also, at uninstalling time you would want to fix the `PATH` modification:

https://github.com/git-for-windows/build-extra/blob/1370d95452efa9904874284bee39aa1e150deabe/installer/install.iss.in#L1787-L1805

probably after retrieving the previously selected options like it is done here:

https://github.com/git-for-windows/build-extra/blob/1370d95452efa9904874284bee39aa1e150deabe/installer/install.iss.in#L603-L604

(you would guard the `PATH` modification behind something like `If Data<>'BashOnly'`)

The easiest way to make these modifications is to follow this wiki page: https://github.com/git-for-windows/git/wiki/Making-an-installer

(You would need to test this, anyway, so it makes sense to install the Git SDK.)

**Comment by dscho** [comment]
(In order to test, you would need to install Git for Windows *twice*: the uninstaller also needs to be the one from the newly-generated installer.)

**Comment by WORMSS** [comment]
I did not call the previous uninstaller. It was the current installer that uninstalled my previous version of git. Unless for some reason the current installer is what called the original uninstaller. Which I never asked for it to do.

**Comment by dscho** [comment]
> I did not call the previous uninstaller.

Not explicitly. But implicitly: https://github.com/git-for-windows/build-extra/blob/1370d95452efa9904874284bee39aa1e150deabe/installer/install.iss.in#L1171-L1178

**Comment by dscho** [comment]
@WORMSS is your silence your way to tell me that you are not going to do anything about this ticket?

**Comment by WORMSS** [comment]
My silence is because I do not have enough c skills to even build the project let alone change things without breaking them.
I even failed to figure out why git says it's doing a fast forward merge when doing an octopus merge which did not involve a fast forward.

**Comment by dscho** [comment]
> My silence is because I do not have enough c skills to even build the project let alone change things without breaking them.

Then you could just have asked for clarification of [my suggestions](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines).

Even without C knowledge, you should be able to follow this suggestion, for example:

> The easiest way to make these modifications is to follow this wiki page: https://github.com/git-for-windows/git/wiki/Making-an-installer

And actually, you do not need to know C at all for this entire ticket...

**Comment by dscho** [comment]
Hmpf.
