### ISSUE TITLE
Unable to open editor with `git rebase -i` or `git commit` in CMD

### ISSUE THREAD

**Issue by Diogo-Rossi** [git-for-windows/git#3265]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I found this [answer](https://superuser.com/questions/1310383/conemu-error-when-trying-to-git-commit-a-merge-after-conflict) in some forum, but the solution does not work

### Setup
____
 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?   

64 bit system
```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
____
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

64 bit system
```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.17763.1879]
```
____
 - What options did you set as part of the installation? Or did you choose the
   defaults?

Default options. Only the installation folder is changed (a custom folder inside %USERPROFILE%)
```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```
____
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.
____
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD
____
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Any command that tries to open the editor. I've tried 2 commands below 
```
git commit
```
```
git rebase -i master
```
____
 - What did you expect to occur after running these commands?

I expect the editor opens and wait for closing
____
 - What actually happened instead?

With the default editor (VIM) the following output shows
```
hint: Waiting for your editor to close the file...       0 [main] vim 1220 cygwin_exception::open_stackdumpfile: Dumping stack trace to vim.exe.stackdump
Aborting commit due to empty commit message.
```
With the editor set to notepad (with `git config --global core.editor notepad`), the following output shows
```
hint: Waiting for your editor to close the file... error: There was a problem with the editor 'notepad'.
Please supply the message using either -m or -F option.
```
____
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not specific repository, but the problem occurs **only with CMD**.
Using git bash, the commands runs ok.

**Comment by dscho** [comment]
I tried to reproduce, but it works here. The most notable difference I see from your setup is my Windows version: `Microsoft Windows [Version 10.0.19043.1052]`.

So I am not sure what the culprit could be. To narrow it down, could you verify that you don't have any VIM (other than Git for Windows') installed, that a regular [MSYS2](https://msys2.github.io)'s VIM works, and if it doesn't, check whether a [Cygwin](https://cygwin.com) VIM works in your setup?

**Comment by Diogo-Rossi** [comment]
> So I am not sure what the culprit could be. To narrow it down, could you verify that you don't have any VIM (other than Git for Windows') installed, that a regular [MSYS2](https://msys2.github.io)'s VIM works, and if it doesn't, check whether a [Cygwin](https://cygwin.com) VIM works in your setup?

I don't have any other VIM installed, just the one with Git for Windows. I'm not sure how I can verify if VIM is "regular MSYS2" or "Cygwin", I think I'll need help on that. All I can tell now is that VIM works fine from Git Bash and that the error message mentions "cygwin_exception".

But the error occurs even when I setup the editor to notepad, and it used to work with notepad in the past. So I think that the error may be related the process of Git opening the editor from CMD (in Git bash, it works fine).

**Comment by dscho** [comment]
> it used to work fine with notepad in the past.

Oh, that's interesting. You could try to bisect through the [snapshots](https://wingit.blob.core.windows.net/files/index.html) (which do contain the full releases in between non-releases), to figure out when the issue started rearing its head.

**Comment by Diogo-Rossi** [comment]
I think the problem is something related to the system used inside my company, maybe the anti-virus, firewall, etc.
Past week I tested in two different PCs  in my company and had the same problem. I also had problems with the command `git subtree` (I tested subtree in version 2.31.1 because of the issue #3260).

Today I tested in a particular PC and there's no problem at all. So, in the end, I think the bug is something related with the system of my company that is blocking something inside git to work properly. Sorry for the inconvenience and thanks for help, You may close the issue.

**Comment by dscho** [comment]
Yes, we ran into issues with anti-malware software in the past :-(

**Comment by chucklu** [comment]
I have a similar issue

> hint: Waiting for your editor to close the file... "C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin: C:\Program Files (x86)\Notepad++\notepad++.exe: No such file or directory
> error: There was a problem with the editor '"C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin'.
> Please supply the message using either -m or -F option.
> error: could not commit staged changes.

It seems the exe path for notepad++ is not correct, The correct path should be C:\Program Files\Notepad++\notepad++.exe.
@dscho  Is there a way to configure the editor path?

**Comment by chucklu** [comment]
I find the solution here https://stackoverflow.com/a/1431003/13338936

> git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"
