### ISSUE TITLE
Using Ctrl+R as the first command on git bash, makes it unresponsive

### ISSUE THREAD

**Issue by tsamridh86** [git-for-windows/git#3277]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 

```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemo
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.1052]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Occurs only on Git Bash for windows

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash for windows

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Ctrl + R
<type anything>
<press tab to bring in the result>
<cursor becomes unresponse>
```
 - What did you expect to occur after running these commands?

I should be able to type / move my cursor/ fire any command

 - What actually happened instead?

Nothing - it got stuck

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
> <press tab to bring in the result>

Aren't you supposed to hit <kbd>Return</kbd> to "bring in the result"? At least that's what I do all the time, and it works here.

**Comment by dscho** [comment]
FWIW I tried to replicate this, and for me, yes, it takes a while because it tries to tab-complete what is there before the cursor which is... nothing. So it tries to tab-complete the empty string, and upon the first attempt, yes, it can take a while to enumerate the many possibilities to tab-complete this.

**Comment by dscho** [comment]
Closing because something else, besides the terminal, became unresponsive :grin:

**Comment by tsamridh86** [comment]
It isn't about that, the issue arises once the command has been loaded, you can hit Return on the command, but it will not execute and the bash window would remain unresponsive. I don't think there is an issue with the enumeration.

**Comment by dscho** [comment]
> If you hit `tab` instead, it should allow you to modify the command

Has this actually ever worked for you? It certainly did not for me. I usually have to use the Cursor keys to get back to the edit mode.

**Comment by tsamridh86** [comment]
Yes, but I haven't been able to repeat the working consistently. This is feature is supported in the normal linux `/bin/bash` settings though.

**Comment by tsamridh86** [comment]
apologies, instead of pressing `Tab`, it's better to use the arrow keys to make it work more consistently.
