### ISSUE TITLE
Unable to configure SSL CA info:http.sslCAInfo "C:/Program File/Git/mingw64/ssl/certs/ca-bundle.crt

### ISSUE THREAD

**Issue by Young-Phoenix** [git-for-windows/git#328]
Hi,
I am install git 2.5.0 in windows7 system,at the end of install ,show the title info.when I input git in cmd line,show Access denied. Please help me,THKS

**Comment by dscho** [comment]
Do you have any special restrictions in place, such as: executables installed by users cannot be called, or some such?

Does the portable Git work?

**Comment by Young-Phoenix** [comment]
I try to install Git-2.5.0-32-bit,it work normally,but my system is 64bit. why the Git-2.5.0-64-bit not work?

**Comment by Young-Phoenix** [comment]
I install 32bit and 64bit in same environment

**Comment by dscho** [comment]
@Young-Phoenix please understand that I cannot help you if you do not answer my questions.

**Comment by Young-Phoenix** [comment]
@dscho not any restrictions,and the portable git is not work.when i click,it's not respond

**Comment by dscho** [comment]
Could you please run the installer from the command line, adding the option `/log=install.log`, then paste the contents of that file here?

**Comment by dscho** [comment]
> Ok,i will send it tomorrow.

Good.

> And I need to go to bed now.,because i am a Chinese guy. ☺

Heh, I *think* you meant to say that you need to go to bed now because your local time is rather late... (IOW you still would need to go to bed now even if you were native Australian.) :smirk:

**Comment by Young-Phoenix** [comment]
@dscho Today,I install Git-2.5.0-64-bit again, it work normally.I don't know the reason,Maybe because I restart the computer. ho ho,Thank you for your patience.

**Comment by jnareb** [comment]
I am getting the same error at the end of upgrade to Git 2.18.0 (on Windows 10).

![git_for_windows_ssl_ca_info_bug](https://user-images.githubusercontent.com/2706/41794740-abe600f2-7660-11e8-8b14-519d0858cfc4.png)

**Comment by dscho** [comment]
@jnareb can you please re-run with `/LOG:<path-to-log-file>` and inspect the log (I might have mentioned this before)?

**Comment by jnareb** [comment]
All right.

Two things:

- The installer was started from the notification popup about new version, i.e. via the autocheck / autoupdate service. I will be running ordinary installer with logging enabled; I hope that they exhibit the same behaviour.
- After halfway done upgrade restart is necessary for Git to work again; at least links and Start Menu entries do not work as they do not find corresponding executables (e.g. Git Bash).

**Comment by jnareb** [comment]
@dscho : Unfortunately for diagnosing this issue I didn't get the same error. Git installer noticed instead that there is halfway done install / upgrade and asked for reboot:

![git_for_windows-installer_reboot_needed](https://user-images.githubusercontent.com/2706/41844976-2e79ef66-7872-11e8-8696-0c5b25228d0d.png)

Here is my `install.log` contents, HTH:  
[install-2.18.0.log](https://github.com/git-for-windows/git/files/2132686/install-2.18.0.log)

> 2018-06-25 12:14:12.646   Log opened. (Time zone: UTC+02:00)
> 2018-06-25 12:14:12.646   Setup version: Inno Setup version 5.5.9 (u)
> 2018-06-25 12:14:12.646   Original Setup EXE: C:\Users\jnare\Downloads\Git\Git-2.18.0-64-bit.exe
> 2018-06-25 12:14:12.646   Setup command line: /SL5="$4C06EE,40493661,224256,C:\Users\jnare\Downloads\Git\Git-2.18.0-64-bit.exe" /SPAWNWND=$A808A4 /NOTIFYWND=$DE07BE /log=install-2.18.0.log
> 2018-06-25 12:14:12.646   Windows version: 10.0.17134  (NT platform: Yes)
> 2018-06-25 12:14:12.646   64-bit Windows: Yes
> 2018-06-25 12:14:12.646   Processor architecture: x64
> 2018-06-25 12:14:12.646   User privileges: Administrative
> 2018-06-25 12:14:12.803   64-bit install mode: Yes
> 2018-06-25 12:14:12.803   Created temporary directory: C:\Users\jnare\AppData\Local\Temp\is-R6456.tmp
> 2018-06-25 12:14:59.609   Found pending rename or delete that matches one of our files: c:\program files\git\cmd\git.exe
> 2018-06-25 12:14:59.609   PrepareToInstall failed: The installation/removal of a previous program was not completed. You will need to restart your computer to complete that installation.
>                          
>   After restarting your computer, run Setup again to complete the installation of Git.
> 2018-06-25 12:14:59.609   Need to restart Windows? Yes
> 2018-06-25 12:17:19.922   Will not restart Windows automatically.
> 2018-06-25 12:17:19.922   Deinitializing Setup.
> 2018-06-25 12:17:20.407   Log closed.

**Comment by dscho** [comment]
Hmm. Something made `...\cmd\git.exe` still be in use, despite the fact that we must have tested for this during the installation and it *not* being in use. (Maybe some VS Code background job or some such.) I guess that that is somehow conflicting with the post-install scripts.

**Comment by jnareb** [comment]
For some reason running `Git-2.18.0-64-bit.exe /log:install-2.18.0-rebooted.log` after required reboot didn't leave `install-2.18-rebooted.log` logfile...

**Comment by dscho** [comment]
On Tue, 26 Jun 2018, Jakub Narębski wrote:

> For some reason running `Git-2.18.0-64-bit.exe /log:install-2.18.0-rebooted.log` after required reboot didn't leave `install-2.18-rebooted.log` logfile...

Probably this relative path is relative to the temporary directory that
InnoSetup uses. And is removed together with said directory at the end of
the installation.

Solution: use an absolute path.

Or maybe the option is called `/LOG=...` instead of `/log:...`?

*clicketyclick*

Yep: http://www.jrsoftware.org/ishelp/topic_setupcmdline.htm#LOG

**Comment by jnareb** [comment]
Ooops. I'll try it if / when I encounter this problem again, but I worry that it is specific to autoupgrade path.
