### ISSUE TITLE
Emojis (😁) are replaced by unicode replacement character (�) on Windows Terminal

### ISSUE THREAD

**Issue by RafaelKuhn** [git-for-windows/git#3281]
### Setup

 - Git version: 2.32.0
```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Windows: 10
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1052]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I installed windows terminal and then reinstalled git for windows (so that it includes automatically the profile in terminal)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal (ver 1.7 I think)

 - What commands did you run to trigger this issue?

I was trying to paste an emoji or access it using the windows emoji pallete-ish thingy with 'windows key + . '
both failed, trying to run
```
git commit -m "testing 😁"
```
but when pasting it displays as
```
git commit -m "testing �"
```
And some other emoji are displayed as a double quote ( " )

I find it odd that these characters display correctly on windows terminal.
When testing on Ubuntu (WSL)'s default shell or even PowerShell, it works
(in PowerShell it kind of works, emojis are displayed as '??' when pasting but can be echoed / are not replaced by any weird character (just to compare) ).

Also, in both three of them I'm using the same font (Cascadia Mono)

It only happens to be bugged when I connect 'Git Bash' with Windows Terminal (by installing git for windows and marking the checkbox)

 - What did you expect to occur after running these commands?

I expected for it to display (when pasted)
```git commit -m "testing 😁"```

 - What actually happened instead?

message I was trying to paste displayed like
```git commit -m "testing �"```

**Comment by AlttiRi** [comment]
Do you have enabled **"Beta: Use Unicode UTF-8 for worldwide language support"** checkbox?
Which sets the default Windows code page to 65001 (UTF-8).
https://stackoverflow.com/a/57134096/11468937

**Comment by AlttiRi** [comment]
> CMD/PowerShell

They can't display emoji (the most part of it) even with that option enabled. Even with non-default fonts.

Git-Bash and "Windows Terminal" can.

![image](https://user-images.githubusercontent.com/16310547/122646073-18cd4400-d126-11eb-8420-350c21947504.png)

**Comment by RafaelKuhn** [comment]
> Do you have enabled **"Beta: Use Unicode UTF-8 for worldwide language support"** checkbox?
> Which sets the default Windows code page to 65001 (UTF-8).
> https://stackoverflow.com/a/57134096/11468937

Well that's what bothers me, I have that option marked already.

And in Powershell they actually work
![image](https://user-images.githubusercontent.com/47254941/122656763-1a9e0400-d134-11eb-86f7-fa148d298ec3.png)

Also work in WSL (Ubuntu 20.4 I guess)

But when I try to do it on the shell that comes embedded  with git for windows...
![image](https://user-images.githubusercontent.com/47254941/122656815-8b452080-d134-11eb-9a27-30511ad91474.png)
Then I select it (or paste it)
![image](https://user-images.githubusercontent.com/47254941/122656832-9e57f080-d134-11eb-884e-5785b6d19afe.png)

That's what bugs me

(Also thank you for your time)

**Comment by RafaelKuhn** [comment]
microsoft/terminal#10055

**Comment by RafaelKuhn** [comment]
Maybe related to this

microsoft/terminal#10055

**Comment by dscho** [comment]
Or maybe `LC_CTYPE` or `LC_ALL` or `LANG` aren't set correctly. I _think_ that `export LC_CTYPE=de_DE.UTF-8` _might_ fix the issue. But then, it might already be set to a `.UTF-8` value, in which case I could believe that ticket 10055 is pointing to the actual root cause.

**Comment by RafaelKuhn** [comment]
Double-checked my locale config and I think it's all correct.

![image](https://user-images.githubusercontent.com/47254941/122939641-2ebb4e80-d34a-11eb-8c0e-def24a390a74.png)


> I could believe that ticket 10055 is pointing to the actual root cause.

Yeah, or something else related to MinGW - Windows Terminal interaction, subscribing to that ticket tho haha.

**Comment by kgybels** [comment]
The problem is in the msys2 runtime, reading the console input doesn't handle surrogate pairs, so anything outside the BMP doesn't work.

The code converts the low and high code units by themselves instead of as a pair:
```
nread = con.con_to_str (tmp + 1, 59, unicode_char);
```

https://github.com/git-for-windows/msys2-runtime/blob/cygwin-3_1_6-release/winsup/cygwin/fhandler_console.cc#L721

Pasting using inputrc's paste-from-clipboard works and mintty handles paste and input correctly.

**Comment by Okeanos** [comment]
So, I just ran some semi-related tests and I am wondering what the difference between `MinTTY` and `default console window` (aka `cmd.exe`) is, when it comes to the Windows Terminal integration (in general).

See exhibit "A" (`MinTTY`) and exhibit "B" (`cmd.exe`) below:

![git-mintty](https://user-images.githubusercontent.com/887496/129781899-882d4949-9ee6-4829-84cf-b38abdca7c29.png)

`MinTTY` above

![git-cmd](https://user-images.githubusercontent.com/887496/129782029-35f6c133-b6d7-4dd5-8aa2-a2c615a680b4.png)

`cmd.exe` above

Based on the description from the installation option I would've assumed that the `cmd.exe` wouldn't look exactly the same as the `MinTTY` one. Not to mention that text reflow etc. wouldn't work as they do (spoiler: they appear to work the same between `MinTTY` and `cmd` embedded into the Terminal).

**Comment by dscho** [comment]
> The code converts the low and high code units by themselves instead of as a pair:
> 
> ```
> nread = con.con_to_str (tmp + 1, 59, unicode_char);
> ```

@kgybels great find!

I have to admit that I don't know how we could fix this, given that we might receive the `WCHAR`s in separate chunks: https://github.com/git-for-windows/msys2-runtime/blob/12e88192b84673b81c6550e48fb7df9b607dada3/winsup/cygwin/fhandler_console.cc#L628-L631

For the record, this is the exact same behavior as in current Cygwin: https://github.com/msys2/msys2-runtime/blob/cygwin-3_2_0-release/winsup/cygwin/fhandler_console.cc#L821-L824 and https://github.com/msys2/msys2-runtime/blob/cygwin-3_2_0-release/winsup/cygwin/fhandler_console.cc#L916

So maybe this is a Cygwin issue to begin with, and we may find more guidance by reporting the issue in that project?

**Comment by kgybels** [comment]
>@Okeanos So, I just ran some semi-related tests and I am wondering what the difference between `MinTTY` and `default console window` (aka cmd.exe) is, when it comes to the Windows Terminal integration (in general).

It configures the terminal used when running `C:\Program Files\Git\git-bash.exe`, it makes no difference when using _Windows Terminal_.

**Comment by dscho** [comment]
Okay, so I finally broke down and tested _Cygwin_ myself. It seems to expose the very same problem:

![image](https://user-images.githubusercontent.com/127790/130585337-02d30364-bf8e-4c9c-b791-2c72ac2b27d4.png)

This is the JSON snippet I added to the Windows Terminal settings in the `"profiles"` section:

```json
            {
                "commandline": "C:\\cygwin64\\bin\\bash.exe -li",
                "icon": "C:\\cygwin64\\Cygwin-Terminal.ico",
                "name": "Cygwin",
                "tabTitle": "Cygwin"
            }
```

So I really think that this problem needs to be reported to the Cygwin project. @RafaelKuhn here is some guidance how you can do that: https://cygwin.com/problems.html (and please do make sure to include as much information from this ticket as possible, of course in a more digestable form than a mere URL).

**Comment by Okeanos** [comment]
Just wondering whether the discussion in [Terminal#8302](https://github.com/microsoft/terminal/issues/8302) is related?

**Comment by dscho** [comment]
I tried this with MSYS2 v3.3.2, and the issue persists.

**Comment by dscho** [comment]
I noticed that this regresses with the newest MSYS2 runtime. A work-around is to enable the experimental pseudo console support in the installer (or by writing `MSYS=enable_pcon` into `/etc/git-bash.config`).

**Comment by hehuahuang** [comment]
0910210507

Johannes Schindelin ***@***.***> 於 2022年1月21日 週五 20:37 寫道：

**Comment by hehuahuang** [comment]
1

黃俊一 ***@***.***> 於 2022年1月21日 週五 20:57 寫道：

**Comment by hehuahuang** [comment]
黃俊一 ***@***.***> 於 2022年1月21日 週五 20:57 寫道：
