### ISSUE TITLE
Why does my [Escape] binding in inputrc have a delay?

### ISSUE THREAD

**Issue by Jehoel** [git-for-windows/git#3282]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

* I searched for "inputrc" "escape" and relevant-looking results for "slow".
* I am unsure if this is an issue/behaviour in MINGW64, mintty, bash, or something else.

### Setup

* Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
  * Git-for-Windows **2.31.1**. 64-bit.
    ```
    $ git --version --build-options
    git version 2.31.1.windows.1
    cpu: x86_64
    built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
    sizeof-long: 4
    sizeof-size_t: 8
    shell-path: /bin/sh
    feature: fsmonitor--daemon
    ```

* Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
  * Windows 10 Pro for Workstations 20H2 19042.1052
    ```
    $ cmd /c ver
    Microsoft Windows [Version 10.0.19042.1052]
    (c) Microsoft Corporation. All rights reserved.
    C:\Program Files\Git>
    ```

* What options did you set as part of the installation? Or did you choose the defaults?
    * ```
      $ cat /etc/install-options.txt
      Editor Option: VIM
      Custom Editor Path:
      Default Branch Option:
      Path Option: Cmd
      SSH Option: OpenSSH
      Tortoise Option: false
      CURL Option: OpenSSL
      CRLF Option: CRLFAlways
      Bash Terminal Option: MinTTY
      Git Pull Behavior Option: Merge
      Use Credential Manager: Core
      Performance Tweaks FSCache: Enabled
      Enable Symlinks: Disabled
      Enable Pseudo Console Support: Disabled
      ```

* Any other interesting things about your environment that might be related to the issue you're seeing?
  * Nothing I can think of.

### Details

* Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
  * mintty and bash

* What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example] http://stackoverflow.com/help/mcve) this will help us understand the issue.

  1. I wanted to configure the `[Escape]` key on my keyboard to clear the current command-line in bash.
  2. I saw this QA: https://superuser.com/questions/298150/how-do-i-make-esc-clear-a-line-in-bash-under-windows-instead-of-ctrlu
  3. I followed its instructions to create the file `~/.inputrc` with the contents `Escape: unix-line-discard`.
  4. I restarted git-bash.
  5. I entered gibberish on the command-line and then pressed `[Escape]`
  6. After a delay of about 500ms-1000ms? the line was cleared.
  7. I want to know why there's a delay and how I can eliminate or reduce it.
  8. I found these QAs but they didn't seem relevant nor help (e.g. using `.tmux-conf` didn't make a difference):
      * https://unix.stackexchange.com/questions/23138/esc-key-causes-a-small-delay-in-terminal-due-to-its-alt-behavior
      * https://unix.stackexchange.com/questions/318433/bash-urxvt-delay-after-esc-in-vi-mode

* What did you expect to occur after running these commands?
  * I expected `unix-line-discard` to be applied instantly, not after an annoying delay.

* What actually happened instead?
  * I had to wait.

* If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing?
   * N/A

**Comment by dscho** [comment]
> I am unsure if this is an issue/behaviour in MINGW64, mintty, bash, or something else.

It might be an [MSYS2](https://msys2.github.io/) or even a [Cygwin](https://cygwin.com/) issue. Can you test whether it works with Cygwin?

**Comment by Jehoel** [comment]
@dscho Is it possible to have side-by-side installs of MSYS2 and Cygwin though?

**Comment by dscho** [comment]
> 
> 
> @dscho Is it possible to have side-by-side installs of MSYS2 and Cygwin though?

Absolutely. They install into different directories by default (`C:\msys64` and `C:\cygwin64`, respectively).

**Comment by Jehoel** [comment]
@dscho Thanks - I installed the current release of Cygwin - I noticed that Cygwin uses `C:\cygwin64\home\$me\` instead of my Windows profile directory.

Anyway - I added the `Escape: unix-line-discard` line to the Cygwin `.inputrc` file and restarted the Cygwin shell and indeed, the same ~500ms delay is there too.

**Comment by Jehoel** [comment]
I found out it's by-design in bash due to the widespread use of Escape as a modifier key throughout the *nix world - it was carried-over into the Windows builds of bash for reasons unknown.

Unfortunately despite Escape being commonly used as an escape key, there's no _standard_ way to control the double-press delay: each program that watches the Escape key does it in its own way.

A compromise was suggested in this Unix/SE posting, [double-tap Escape instead](https://unix.stackexchange.com/questions/30987/windows-shell-escape-key-delete-whole-line-equivalent-in-bash):

> [Wilson F](https://unix.stackexchange.com/a/157121/129512):
> [...]
> And that explains why I said that the behaviour you get is almost Windows-like: when you press Esc, bash checks to see if you're using it in combination with another key; so, if you bind it to kill-whole-line, there's a bit of a delay between pressing (or rather, releasing) Esc and bash clearing the line for you.

> [j_random_hacker](https://unix.stackexchange.com/questions/30987/windows-shell-escape-key-delete-whole-line-equivalent-in-bash#comment805069_157121):
> 
> In the end I found mapping `"\e\e"` to `kill-whole-line` (i.e., tap Esc twice to clear the line) a nice compromise

**Comment by dscho** [comment]
Thank you for investigating and writing it all down!
