### ISSUE TITLE
Git bash on windows doesn't prompt in case github authentication is required and commands freeze indefinitely.

### ISSUE THREAD

**Issue by sumanjitsg** [git-for-windows/git#3284]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```

$ git --version --build-options

** git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19042.1052] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
** Issue isn't reproducible on Git Windows command line. It prompts for github authentication with two options (web/token). On successful authentication, commands start working on Git Windows and Git Bash as well. **
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
** Bash **
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** git pull, git push, git pull --rebase origin master **
```
 - What did you expect to occur after running these commands?
```
** Expected local branch updates from remote **
```

 - What actually happened instead?
```
** Commands freeze forever **
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
```
** insert URL here **
```

**Comment by dscho** [comment]
FWIW this strikes me as a problem with Git Credential Manager Core more than with Git, so I would like to suggest following the advice in https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/docs/development.md#collect-trace-output to debug further.

**Comment by mjcheetham** [comment]
@sumanjitsg can you try setting the following environment variables and re-running one of the commands that hangs?

```text
GIT_TRACE=1
GCM_TRACE=1
```

For example from Git Bash:

```shell
$ GIT_TRACE=1 GCM_TRACE=1 git fetch
```

Please note that the trace output from `GCM_TRACE` may contain sensitive information like URLs and usernames. Please consider redacting any information before sharing.

**Comment by dscho** [comment]
@sumanjitsg just in case you _are_ reading what Matthew and I are writing here: I was able to reproduce the issue and I think you can work around the issue until a full fix is released by calling the command with `winpty`, e.g. `winpty git fetch`.

**Comment by dscho** [comment]
@sumanjitsg please download and install https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.475 to fix this.
