### ISSUE TITLE
Git push hangs after CredentialHelperSelector (2.32.0.1 portable)

### ISSUE THREAD

**Issue by bgue** [git-for-windows/git#3294]
- [ X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 Bit portable 
```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19042.985]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
All defaults.

BMGue@29J33364 MINGW32 /etc
$ cat /etc/
DIR_COLORS            msystem               profile.d/
bash.bash_logout      mtab                  protocols
bash.bashrc           nanorc                rebase.db.i386
docx2txt.config       networks              services
fstab                 nsswitch.conf         ssh/
gitattributes         package-versions.txt  tigrc
gitconfig             pkcs11/               vimrc
hosts                 pki/
inputrc               profile

BMGue@29J33364 MINGW32 /etc
$ cat /etc/package-versions.txt
apr 1.7.0-1
apr-util 1.6.1-1
bash 4.4.023-1
bzip2 1.0.8-2
ca-certificates 20190110-1
coreutils 8.32-1
diffutils 3.7-1
docx2txt 1.4-1
dos2unix 7.4.1-1
expat 2.2.9-1
file 5.38-3
findutils 4.7.0-1
gawk 5.0.0-1
gcc-libs 9.3.0-1
gettext 0.19.8.1-1
git-extra 1.1.502.c1ab8c2-1
git-flow 1.12.3-1
glib2 2.54.3-3
gmp 6.2.0-1
gnupg 2.2.23-1
grep 3.1-1
gzip 1.10-1
heimdal-libs 7.5.0-3
icu 65.1-1
less 551-1
libasprintf 0.19.8.1-1
libassuan 2.5.3-1
libbz2 1.0.8-2
libcbor 0.8.0-1
libcrypt 2.1-2
libcurl 7.73.0-1
libedit 20191231_3.1-1
libexpat 2.2.9-1
libffi 3.3-1
libfido2 1.5.0-1
libgcrypt 1.8.6-1
libgettextpo 0.19.8.1-1
libgnutls 3.6.15-1
libgpg-error 1.38-1
libhogweed 3.6-1
libiconv 1.16-2
libidn2 2.3.0-1
libintl 0.19.8.1-1
libksba 1.3.5-1
liblz4 1.9.2-1
liblzma 5.2.5-1
libmetalink 0.1.3-2
libnettle 3.6-1
libnghttp2 1.40.0-1
libnpth 1.6-1
libopenssl 1.1.1.h-1
libp11-kit 0.23.20-2
libpcre 8.44-1
libpcre2_8 10.34-1
libpsl 0.21.0-1
libreadline 8.0.004-1
libsasl 2.1.27-1
libserf 1.3.9-5
libsqlite 3.30.0-1
libssh2 1.9.0-1
libtasn1 4.16.0-1
libunistring 0.9.10-1
libutil-linux 2.35.1-1
libxml2 2.9.10-4
libxslt 1.1.34-3
mingw-w64-i686-antiword 0.37-2
mingw-w64-i686-brotli 1.0.9-2
mingw-w64-i686-bzip2 1.0.8-1
mingw-w64-i686-ca-certificates 20200601-2
mingw-w64-i686-c-ares 1.16.1-1
mingw-w64-i686-connect 1.105-1
mingw-w64-i686-curl 7.73.0-1
mingw-w64-i686-expat 2.2.10-1
mingw-w64-i686-gcc-libs 10.2.0-5
mingw-w64-i686-gettext 0.19.8.1-9
mingw-w64-i686-git 2.29.2.2.3464b98ce6-1
mingw-w64-i686-git-credential-manager 1.20.0-1
mingw-w64-i686-git-credential-manager-core 2.0.280.19487-1
mingw-w64-i686-git-doc-html 2.29.2.2.3464b98ce6-1
mingw-w64-i686-git-lfs 2.12.1-1
mingw-w64-i686-gmp 6.2.0-3
mingw-w64-i686-gnutls 3.6.15-2
mingw-w64-i686-jansson 2.13.1-1
mingw-w64-i686-jemalloc 5.2.1-1
mingw-w64-i686-libffi 3.3-1
mingw-w64-i686-libiconv 1.16-1
mingw-w64-i686-libidn2 2.3.0-1
mingw-w64-i686-libmetalink 0.1.3-3
mingw-w64-i686-libssh2 1.9.0-2
mingw-w64-i686-libsystre 1.0.1-4
mingw-w64-i686-libtasn1 4.16.0-1
mingw-w64-i686-libtre-git r128.6fb7206-2
mingw-w64-i686-libunistring 0.9.10-2
mingw-w64-i686-libwinpthread-git 9.0.0.6029.ecb4ff54-1
mingw-w64-i686-libzip 1.7.3-1
mingw-w64-i686-mpc 1.2.0-2
mingw-w64-i686-mpfr 4.1.0-3
mingw-w64-i686-nettle 3.6-2
mingw-w64-i686-nghttp2 1.41.0-1
mingw-w64-i686-odt2txt 0.5-2
mingw-w64-i686-openssl 1.1.1.h-2
mingw-w64-i686-pcre 8.44-1
mingw-w64-i686-pcre2 10.33-1
mingw-w64-i686-tcl 8.6.10-1
mingw-w64-i686-tk 8.6.10-2
mingw-w64-i686-wineditline 2.205-3
mingw-w64-i686-xz 5.2.5-1
mingw-w64-i686-zlib 1.2.11-7
mingw-w64-i686-zstd 1.4.5-1
mintty 1~3.4.2-1
mpfr 4.0.2-1
msys2-runtime 3.1.7-4
nano 4.9.2-1
ncurses 6.2-1
nettle 3.6-1
openssh 8.4p1-2
openssl 1.1.1.h-1
p11-kit 0.23.20-2
patch 2.7.6-1
perl 5.32.0-2
perl-Authen-SASL 2.16-2
perl-Convert-BinHex 1.125-1
perl-Encode-Locale 1.05-1
perl-Error 0.17029-1
perl-File-Listing 6.04-2
perl-HTML-Parser 3.72-4
perl-HTML-Tagset 3.20-2
perl-HTTP-Cookies 6.08-1
perl-HTTP-Daemon 6.01-2
perl-HTTP-Date 6.05-1
perl-HTTP-Message 6.22-1
perl-HTTP-Negotiate 6.01-2
perl-IO-Socket-SSL 2.066-1
perl-IO-stringy 2.111-1
perl-JSON 2.97001-1
perl-libwww 6.44-1
perl-LWP-MediaTypes 6.02-2
perl-MailTools 2.21-1
perl-MIME-tools 5.509-1
perl-Net-HTTP 6.19-1
perl-Net-SMTP-SSL 1.04-1
perl-Net-SSLeay 1.88-4
perl-TermReadKey 2.38-4
perl-TimeDate 2.32-1
perl-Try-Tiny 0.30-1
perl-URI 1.76-1
perl-WWW-RobotRules 6.02-2
pinentry 1.1.0-2
sed 4.8-1
ssh-pageant-git 1.4.12.g6f47092-1
subversion 1.14.0-3
tar 1.32-1
tig 2.5.1-1
unzip 6.0-2
vim 8.2.0592-1
which 2.21-2
winpty 0.4.3-1
zlib 1.2.11-1
filesystem 2020.02-2
dash 0.5.10.2-1
rebase 4.4.4-1
util-linux 2.35.1-1
unzip 6.0-2
mingw-w64-i686-xpdf-tools 4.00-1


```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
 
Using the portable build

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git push --set-upstream origin main

```
 - What did you expect to occur after running these commands?

1.  Prompt for gh credentials
2. push to remote origin

 - What actually happened instead?

1. CredentialHelperSelector presented
2. Selected any credential helper (default of manager-core)
3. Invoked Select button
4. git push hangs

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not specific to one repository; happened for most participants in a class.

**Comment by dscho** [comment]
Could you please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by goslackware** [comment]
Could this issue be related to:
https://github.com/microsoft/Git-Credential-Manager-Core/issues/364

**Comment by dscho** [comment]
> 
> 
> Could this issue be related to:
> [microsoft/Git-Credential-Manager-Core#364](https://github.com/microsoft/Git-Credential-Manager-Core/issues/364)

That's what I think, but we will only know for sure when the latest snapshot has been tested.

**Comment by build6** [comment]
I think I am experiencing a similar issue but on the installed (not portable) version of git-for-windows - should I open a new issue or just tack it on here - 

when trying to push to a repository on github using command line git-for-windows, after issuing the command (e.g. git push origin main), it hangs indefinitely - there is NO prompt (expected a GUI window to appear) for username/password, if I installed with the option of the new credential manager-core.  However, if I uninstall and reinstall and choose to ignore the deprecation warning and use the old credential manager, everything works.  This issue exists with the current 2.32 and has happened for me since at least 2.28 (I didn't have time/energy to report, just found the reinstall workaround and didn't think about it again until now, tried 2.32 and issue is still here).  

64 bit Windows 10 [Version 10.0.19042.1055]
MINGW64 /
$ git --version --build-options
git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

**Comment by dscho** [comment]
@build6 Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) before opening a new issue.

**Comment by dscho** [comment]
Since the original poster did not respond, I will just claim that this is the same bug as https://github.com/git-for-windows/git/issues/3268.
