### ISSUE TITLE
got-for-windows is unable to handle file or directory names that end with a space

### ISSUE THREAD

**Issue by joanise** [git-for-windows/git#3298]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.24.1.windows.2
cpu: x86_64
built from commit: 992f0773022527b1b0cb1e0c13aec97dd5248053
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1440]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir file-with-space
cd file-with-space
git init
touch "file "
git add "file "
```

Please note that the name of the file ends with a single space.

 - What did you expect to occur after running these commands?

File `file ` added to index

 - What actually happened instead?

```
error: open("file "): No such file or directory
error: unable to index file 'file '
fatal: adding files failed
```

Similarly, if I create a directory with a trailing space in the directory name, I cannot add files it contains:

```
mkdir "dir "
touch "dir /file"
git add "dir /file"
fatal: pathspec 'dir /file' did not match any files
```

Expected behaviour: `"dir /file" added to the index.

I have tested both of these scenarios on Linux and in Cygwin and its Git installation, and in each case the file is added to the index as expected. This bug only occurs on git-for-windows.

**Comment by joanise** [comment]
This bug was discovered trying to answer a question on StackOverflow: https://stackoverflow.com/a/68136322/3216427

**Comment by dscho** [comment]
> git version 2.24.1.windows.2

Before anything else: [you _want_ to upgrade](https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version) (for five critical versions already).

> touch "file "

While it is tempting to _think_ that this works all right, it does not. Open a CMD, `cd` to the directory and then call `type "file "`:

```console
C:\Users\me>type "space "
The system cannot find the file specified.
```

The reason why this does not work is that trailing spaces are not allowed in Windows (although Cygwin ignores this rule and uses some technical tricks to create such files or directories, and our Bash inherits this by virtue of using the MSYS2 runtime, which is a close fork of the Cygwin runtime). The rest of the Windows world does conform, though. From https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file:

> * Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

So the bug is not in Git, but in the assumption that it is okay to use a file name on Windows which ends in a space.

**Comment by joanise** [comment]
@dscho Thanks for the clear explanation. I got similar feedback on SO since, and I can confirm indeed that the files with the spaces at the end don't work correctly outside Git Bash and Cygwin Bash. So agreed, this is not a bug in Git for Windows, but maybe rather a bug in MSYS2 runtime for allowing me to create these files in the first place.
Closing this issue.

**Comment by dscho** [comment]
No, it is not a bug in MSYS2, but an inherited feature from Cygwin: as long as you stay within Cygwin/MSYS, you *can* use filenames with trailing spaces.
