### ISSUE TITLE
Push or Pull with remote takes very long time

### ISSUE THREAD

**Issue by cabird** [git-for-windows/git#330]
I just installed the latest version of git-for-windows on my win 10 laptop.  While local operations are quite fast, remote operations like push or pull take a VERY long time.  It's not uncommon for this to take 10 minutes when on other machines talking to the same remote, it takes only a few seconds.  I have no idea why this is or what to try to do to fix it.  Has anyone else run into this?

**Comment by dscho** [comment]
What kind of remote is this? `http://`, `https://`, `git://` or SSH? Please volunteer as much information about your setup as possible.

**Comment by TheBels** [comment]
I also noticed much slower performance with the 2.x round of installers. I am comparing against the embedded SourceTree version of git that it drops into my AppData directory. It is on version `1.9.5.msysgit.0`. I tested by opening a Windows cmd shell into a previously-cloned repository. I then prepended the `1.9.5.msysgit.0` version to my PATH and ran fetch. It returns in sub-second time.

If I do the same test with a 2.x version (install, open cmd shell in the same directory, run `git fetch`) it takes around 40-60 seconds. I also tried with [2.3.5.windows.4](https://github.com/git-for-windows/git/releases/tag/v2.3.5.windows.4) and the same delay is present.

This is against a small repository hosted on Team Foundation Server over http. I am on a 64 bit version of Windows 8.1 Pro.

I tested again with an empty repository (also via http and TFS) and the same behavior is observed.

Cloning is also similarly slow: cloning the empty repository with `1.9.5.msysgit.0` was roughly sub-second time. But with the latest, `2.5.2.windows.2`, it has the same 30+ second delay.

**Comment by TheBels** [comment]
Upon further investigation I am not entirely convinced it is a problem with a remote. With the 1.9.5 version I cloned the empty repository. Then with the 2.5.2 version I cloned that into another directory (all local disks). That clone took around 20 seconds. And even a fetch from that local clone is taking 20+ seconds - not as long as the 40-50s as above, but still way longer than I'd expect given both repos are local.

**Comment by TheBels** [comment]
As I test more, it is speeding up. Now a local fetch is taking maybe a few seconds instead of the 20. I enabled GIT_TRACE and the `git-unload-pack` line looks to take up a lot of time:

> D:\temp\tfs-slow>git version
> 15:21:05.280182 git.c:348               trace: built-in: git 'version'
> git version 2.5.2.windows.2
> 
> D:\temp\tfs-slow>git fetch
> 15:21:09.337797 git.c:348               trace: built-in: git 'fetch'
> 15:21:09.338797 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/tfs'\'''
> 15:21:11.832007 run-command.c:335       trace: run_command: 'gc' '--auto'
> 15:21:11.853162 git.c:348               trace: built-in: git 'gc' '--auto'


And for completness' sake, the same command using 1.9.5:

> D:\temp\tfs-slow>git version
> trace: built-in: git 'version'
> git version 1.9.5.msysgit.0
> 
vD:\temp\tfs-slow>git fetch
> trace: built-in: git 'fetch'
> trace: run_command: 'git-upload-pack '\''D:/temp/tfs'\'''
> trace: run_command: 'gc' '--auto'
> trace: built-in: git 'gc' '--auto'

**Comment by dscho** [comment]
@TheBels thanks for the substantially more detailed report.

The fact that you see two seconds spent in `upload-pack` without even packing any objects is pretty worrisome. However, I did not experience that slowness, so I would like to know more about the differences in your setup vs mine.

Is `D:` a local disk, or is it a mapped drive? Do you have a long `PATH`? Is there a virus scanner running? Do you see anything in [Process Monitor](https://technet.microsoft.com/en-us/library/bb896645.aspx) that sticks out during the execution of `git upload-pack` (it might make most sense to filter Process Monitor's output by `.../bin/git-upload-pack.exe`)?

**Comment by TheBels** [comment]
Hi @dscho - no problem on the details. These "it's slower" bugs are not straight forward to diagnose for sure. To your questions:

1. `D:` is a local disk
2. The `PATH` is 1120 characters (including path separators). If I add the `1.9.5.msysgit.0` git version in AppData then it is 1187 (also including path separators). If I remove those separators it is 1157.
3. AV is running yes - we run Symantec Endpoint Protection version 12.1.4013.4013
4. When filtering by `git-upload-pack.exe` I see a ton of registry key hits (~2500 rows) for locale-related information. It looks to be querying the various languages - I see hits for both `HKLM\System\CurrentControlSet\Control\Nls\CustomLocale` and `HKLM\System\CurrentControlSet\Control\Nls\ExtendedLocale` across `en-US`, `af-ZA`, `am-ET`, `ar-AE`, and on. But, that said, the duration between the first and last is small. In terms of a higher level look, it looks to be doing these basic things:
  * some file and registry hits for what I assume is init-related work. I see `Path`s for `C:\Program Files\Git\mingw64\libexec\git-core\libiconv-2.dll`, `C:\Program Files\Git\mingw64\bin\libiconv-2.dll`, `C:\Program Files\Git\mingw64\libexec\git-core\libpcre-1.dll` and some other dlls in the git folder.
  * Then some registry hits for language configurations, e.g. `HKCU\Control Panel\Desktop\LanguageConfiguration`, `HKCU\Control Panel\Desktop\PreferredUILanguages`, and `HKCU\Control Panel\Desktop\MuiCached\MachinePreferredUILanguages`
  * Then `git-upload-pack.exe` does a `CreateFile` operation followed by 230 `ReadFile` operations
  * This is followed by what appears to be git walking up the directory tree scanning for something (`.gitconfig` maybe...??); it starts in `C:\Program Files\Git\mingw64\libexec\git-core` and makes its way up the parents to `C:\Program Files`
  * Then it scans in the `C:` and `C:\Windows` with other file-based operations, e.g. `CreateFile`, `QueryDirectory`, and `QueryBasicInformationFile`
  * Then it hits those locale-related rows (~2500)
  * And finally it gets to what seems more familiar to me - accessing files from the local remote, searching/loading my `.gitconfig` etc

**Comment by TheBels** [comment]
The above was with a slightly-modified remote clone - it was no longer empty and instead has 3 files totaling 8.53KB. That said... I tested it again with an empty (not bare) repository and observed basically the same output (I captured the second call to `git fetch`):

    D:\temp\slow-test-remote-empty-client>git version
    08:23:07.206124 git.c:348               trace: built-in: git 'version'
    git version 2.5.2.windows.2

    D:\temp\slow-test-remote-empty-client>git remote -v
    08:23:10.449137 git.c:348               trace: built-in: git 'remote' '-v'
    origin  D:/temp/slow-test-remote-empty (fetch)
    origin  D:/temp/slow-test-remote-empty (push)

    D:\temp\slow-test-remote-empty-client>git fetch
    08:23:12.511135 git.c:348               trace: built-in: git 'fetch'
    08:23:12.512635 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/slow-test-remote-empty'\'''
    08:23:15.003823 run-command.c:335       trace: run_command: 'gc' '--auto'
    08:23:15.029043 git.c:348               trace: built-in: git 'gc' '--auto'

    D:\temp\slow-test-remote-empty-client>git fetch
    08:23:34.874200 git.c:348               trace: built-in: git 'fetch'
    08:23:34.878204 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/slow-test-remote-empty'\'''
    08:23:37.488209 run-command.c:335       trace: run_command: 'gc' '--auto'
    08:23:37.577208 git.c:348               trace: built-in: git 'gc' '--auto'

**Comment by TheBels** [comment]
OK for completeness' sake I tested with a bare remote and observed the same behavior and similar captured events (again, I captured the second `git fetch`):

    D:\temp>git init --bare slow-test-remote-bare
    08:28:30.775626 git.c:348               trace: built-in: git 'init' '--bare' 'slow-test-remote-bare'
    Initialized empty Git repository in D:/temp/slow-test-remote-bare/

    D:\temp>git clone slow-test-remote-bare slow-test-remote-bare-client
    08:28:44.838997 git.c:348               trace: built-in: git 'clone' 'slow-test-remote-bare' 'slow-test-remote-bare-client'
    Cloning into 'slow-test-remote-bare-client'...
    08:28:44.856999 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/slow-test-remote-bare'\'''
    warning: You appear to have cloned an empty repository.
    done.

    D:\temp>cd slow-test-remote-bare-client

    D:\temp\slow-test-remote-bare-client>
    D:\temp\slow-test-remote-bare-client>git fetch
    08:28:59.994032 git.c:348               trace: built-in: git 'fetch'
    08:28:59.995033 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/slow-test-remote-bare'\'''
    08:29:02.484066 run-command.c:335       trace: run_command: 'gc' '--auto'
    08:29:02.506036 git.c:348               trace: built-in: git 'gc' '--auto'

    D:\temp\slow-test-remote-bare-client>git fetch
    08:29:29.294107 git.c:348               trace: built-in: git 'fetch'
    08:29:29.298109 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/slow-test-remote-bare'\'''
    08:29:31.903107 run-command.c:335       trace: run_command: 'gc' '--auto'
    08:29:31.991976 git.c:348               trace: built-in: git 'gc' '--auto'

**Comment by TheBels** [comment]
I tested against `1.9.5.msysgit.0` (a `git fetch` from the clone of the bare repository) and, when filtering for `git-upload-pack.exe` one immediate thing I noticed was those 2300 language scans are absent. The other logic I laid out above looks roughly the same.

Let me know if anything is helpful and perhaps what other events I could look into.

Thanks for digging!

**Comment by dscho** [comment]
Hmm. Could you test again with `LC_ALL=C` and `LANG=C`?

**Comment by TheBels** [comment]
Sure, though I am not sure that changed the output. Let me know if I did this incorrectly:

    D:\temp\slow-test-remote-bare-client>set GIT_TRACE=1

    D:\temp\slow-test-remote-bare-client>set LC_ALL=C

    D:\temp\slow-test-remote-bare-client>set LANG=C

    D:\temp\slow-test-remote-bare-client>git version
    10:20:10.607144 git.c:348               trace: built-in: git 'version'
    git version 2.5.2.windows.2

    D:\temp\slow-test-remote-bare-client>git fetch
    10:20:15.362100 git.c:348               trace: built-in: git 'fetch'
    10:20:15.363099 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/slow-test-remote-bare'\'''
    10:20:17.851680 run-command.c:335       trace: run_command: 'gc' '--auto'
    10:20:17.871679 git.c:348               trace: built-in: git 'gc' '--auto'

**Comment by dscho** [comment]
Does it still hit that insane number of registry entries?

**Comment by TheBels** [comment]
Ah - yes they are not present; however, the execution time didn't change unfortunately:

    D:\temp\slow-test-remote-bare-client>git fetch
    11:27:36.897338 git.c:348               trace: built-in: git 'fetch'
    11:27:36.900339 run-command.c:335       trace: run_command: 'git-upload-pack '\''D:/temp/slow-test-remote-bare'\'''
    11:27:40.096344 run-command.c:335       trace: run_command: 'gc' '--auto'
    11:27:40.150347 git.c:348               trace: built-in: git 'gc' '--auto'

Maybe the time is elsewhere - i.e. not in `git-upload-pack.exe`? The time I see in procmon doesn't seem long:

With the above test, the first and last times are:

    9/16/2015 11:27:40.0492451 AM
    9/16/2015 11:27:40.0919969 AM

And the first and last times on 1.9.5 

    9/16/2015 8:44:09.7753945 AM
    9/16/2015 8:44:09.8164282 AM

Which is basically the same diff:

    0.0919969 - 0.0492451 = 0.0427518
    0.8164282 - 0.7753945 = 0.0410337

Any suggestions on where to dig? I can look at all `git-` commands and see if any Durations are crazy long..?

**Comment by dscho** [comment]
Hmm. Maybe you can instrument the `start_command()`/`finish_command()` functions to see which child takes all the time, if any?

**Comment by TheBels** [comment]
I am not really setup unfortunately to modify the source and try from there (unless I misunderstood what you mean).

Do you have any other avenues of investigation before getting into the source?

**Comment by dscho** [comment]
> Do you have any other avenues of investigation before getting into the source?

Unfortunately, no.

Fortunately, however, it is really easy to compile Git for Windows from scratch: just install the [Git for Windows SDK](https://git-for-windows.github.io/#download-sdk); this will run unsupervised for a couple of minutes and when it is done, you will have executables built from the current `master`.

I rather doubt that we will get any further without that because the assumption that `git upload-pack` makes the fetch hang turned out to be wrong, as per [your comment](https://github.com/git-for-windows/git/issues/330#issuecomment-140780032).

**Comment by TheBels** [comment]
Gotcha- ok that makes sense. I'll take a look at the SDK and advise if I have any questions.

Thanks again for the help.

**Comment by dscho** [comment]
> Thanks again for the help.

Thanks for being persistent and not running away :-)

**Comment by TheBels** [comment]
No worries - I'm happy to help diagnose; wrt timing: I'll likely be able to dive into this early next week.

**Comment by dscho** [comment]
Thanks for the heads-up!

**Comment by dscho** [comment]
@TheBels I just invited to the team so I can assign this ticket to you. Is that okay with you?

**Comment by TheBels** [comment]
Sure, that works.

**Comment by dscho** [comment]
@TheBels any progress? We could meet in https://gitter.im/git-for-windows/git if you'd like to work on this with me.

**Comment by TheBels** [comment]
Hi @dscho - no progress yet. This happens at work (the only place I can reproduce) and I haven't gotten the time yet to sit down and dig.

I also though of revisiting - assuming you don't think it a waste of time - the procmon timings to see if I can identify what could be taking up so much time.

I got the code on my laptop at home and took a brief look at the `start_command()` and `finish_command()` methods. The idea would be to log everything that comes into those methods? And that is separate from the current TRACE logging we see in the output above?

**Comment by dscho** [comment]
> I also though of revisiting - assuming you don't think it a waste of time - the procmon timings to see if I can identify what could be taking up so much time.

I do not think that procmon gives us fine-grained enough information. The delay happens *somewhere*, but where? It is not enough to pinpoint one executable, although that would be a good start.

> I got the code on my laptop at home and took a brief look at the start_command() and finish_command() methods. The idea would be to log everything that comes into those methods? And that is separate from the current TRACE logging we see in the output above?

The idea would be to patch in a `start_time` into the `child_process` structure, so that you can output not only the complete command line and PID, but also how long *that particular* invocation took.

TBH I am not even sure that the delay is from the fetch itself as opposed to the prompt that is shown just after the fetch (and which might hit a really cold cache or some such).

**Comment by TheBels** [comment]
I messed around a bit and got my first segfault. I'm brushing up on my C and plan to take a stab at adding the `start_time` field. I'll take a look this weekend and report back Monday.

**Comment by TheBels** [comment]
Apologies on the late reply.

I tried using `time.h` methods to get a `time_t` but I don't believe that has the precision we need. I then changed it to use `clock_t` but I don't think that worked as expected, either. I did more searching and found references to use `ftime` from `sys\timeb.h`.

Probably we can just sit down together, @dscho, and bang this out. From your above, this looks relatively straight forward (once you get the right methods!). Then once tested I can patch my code at work and run through the tests.

I am typically free M-F evenings (eastern time) around say 8pm. Let me know!

**Comment by dscho** [comment]
How about using [`GetTickCount()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724408%28v=vs.85%29.aspx)?

> I am typically free M-F evenings (eastern time) around say 8pm.

Surprisingly, I am in a different timezone. Your 8pm is my 2am.

**Comment by TheBels** [comment]
Cool, i will look at `GetTickCount()`, thanks.

Yea I figured the chances were good we'd be in different zones. We can do it on the weekend. Probably nowish on Saturday or Sunday would work. Or barring that, I can also likely do noon your time on Tuesdays or Thursdays.

**Comment by dscho** [comment]
If you get stuck somewhere, let's aim for Tuesday (although 6am is pretty early for you, isn't it?)

**Comment by TheBels** [comment]
I wake up around that time anyways, so it's not a big deal. I can just drink my coffee a bit earlier than usual :). If we chat, heads up I will only be able to work for about an hour though - I need to start my day a bit before 7am.

**Comment by TheBels** [comment]
OK I ended up getting the clock time to work properly. I captured them both and they are almost identical, which makes sense. On my laptop I set `export GIT_TRACE=1` and ran a `git fetch` from within the git SDK. Here is the output. I expected a print statement around each line; is the below expected?

    $ git fetch
    13:38:00.805983 git.c:348               trace: built-in: git 'fetch'
    13:38:00.821609 run-command.c:340       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/git-for-windows/git'
    13:38:01.227874 run-command.c:340       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
    finish_command: clock time elapsed : 125.000000000000000
    finish_command: tick time elapsed  : 125.000000000000000
    13:38:01.352866 run-command.c:340       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
    13:38:01.415387 git.c:348               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
    finish_command: clock time elapsed : 63.000000000000000
    finish_command: tick time elapsed  : 63.000000000000000
    finish_command: clock time elapsed : 609.000000000000000
    finish_command: tick time elapsed  : 610.000000000000000
    13:38:01.430993 run-command.c:340       trace: run_command: 'gc' '--auto'
    13:38:01.477887 git.c:348               trace: built-in: git 'gc' '--auto'
    finish_command: clock time elapsed : 47.000000000000000
    finish_command: tick time elapsed  : 46.000000000000000

**Comment by dscho** [comment]
This output is pretty nice already. Maybe add the `pid` so that the time that was spent in a subprocess can be connected with the exact command line?

**Comment by TheBels** [comment]
Added. I then captured the output again via ProcMon and filtered by the PID. I did not find any of them though. This was via the MINGW64 shell. Are the PIDs reported by my output not the same as the PIDs reported by ProcMon?

FYI I then tried via the Windows cmd shell by updating the `PATH` to include `git-sdk-64/usr/src/git` and I receive an error message: `The program can't start because libiconv-2.dll is missing from your computer.`

Thoughts?

**Comment by dscho** [comment]
> I then tried via the Windows cmd shell by updating the PATH to include git-sdk-64/usr/src/git and I receive an error message: The program can't start because libiconv-2.dll is missing from your computer.

This is to be expected: the `.dll` files all live in `/mingw64/bin/`, the eventual place where `git.exe` will be installed. So if you want to run things directly after building, in place, you gotta append the `/mingw64/bin` directory to the `PATH` yourself.

> Are the PIDs reported by my output not the same as the PIDs reported by ProcMon?

They should be.

But my idea was more to look for a process that took a long time, then find the corresponding log entry with the command-line of the process with the corresponding PID.

**Comment by TheBels** [comment]
What corresponding log? You mean something else besides procmon?

I tried capturing the output when running the fetch command butbi didn't
see the PID. Perhaps I missed it or filtered it out on accident.

**Comment by dscho** [comment]
> What corresponding log?

If I were to tackle this problem, I would log both when a child was started and when it finished, and in both cases I would log the PID so that I can connect the command-line (logged at start time) with the run time (logged when the process finished).

**Comment by TheBels** [comment]
OK sounds good. The command itself is `argv` within `child_process`?

**Comment by dscho** [comment]
> The command itself is argv within child_process?

The `argv` is actually an array with the already-split command line.

**Comment by TheBels** [comment]
OK great. that should be straight forward to print out. I will let you know
how it goes.

Thanks again for the help

**Comment by TheBels** [comment]
OK here we go - it looks like from the output it's `git-remote-https` that takes the most time. I will run the modified code on my work box and see if that is any more telling.

    $ git version
    21:03:23.671451 git.c:348               trace: built-in: git 'version'
    git version 2.6.0.windows.1.6.g2bf148c.dirty

    $ git fetch
    21:01:56.426608 git.c:348               trace: built-in: git 'fetch'
    21:01:56.442232 run-command.c:340       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/git-for-windows/git'
    6156] start_command: git-remote-https
    21:01:56.864130 run-command.c:340       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
    5452] start_command: rev-list
    5452] finish_command: tick time elapsed  : 125.000000000000000
    21:01:56.989095 run-command.c:340       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
    5604] start_command: rev-list
    21:01:57.051615 git.c:348               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
    5604] finish_command: tick time elapsed  : 63.000000000000000
    6156] finish_command: tick time elapsed  : 625.000000000000000
    21:01:57.067223 run-command.c:340       trace: run_command: 'gc' '--auto'
    6480] start_command: gc
    21:01:57.129742 git.c:348               trace: built-in: git 'gc' '--auto'
    6480] finish_command: tick time elapsed  : 63.000000000000000

**Comment by dscho** [comment]
In that case, `GIT_CURL_VERBOSE=1` might shed more light into the matter.

**Comment by dscho** [comment]
@TheBels any news how it goes with `GIT_CURL_VERBOSE=1`?

**Comment by TheBels** [comment]
Hi Johannes-

Apologies for the radio silence over the holidays. Since the crazy long
delay stopped, I've put this on the back-burner.

I will pick this back up and see if the curl output conveys anything
helpful.

**Comment by TheBels** [comment]
Hi Johannes - FYI I've put this into the background again given I haven't seen the slowness since early September. Perhaps there is still something fishy happening within the network calls.. if I see this again I'll update this thread and advise.

Thanks for all the help!

**Comment by dscho** [comment]
@TheBels how about closing it for now?

**Comment by TheBels** [comment]
Sure, that works. I will reopen once I am able to reproduce it properly.

**Comment by dscho** [comment]
:-)

**Comment by TheBels** [comment]
Thanks @dscho for all the help!
