### ISSUE TITLE
Incomplete output of 'git log --pretty=oneline -<n>'

### ISSUE THREAD

**Issue by Peter-76** [git-for-windows/git#3310]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1052]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"

Editor Option: VisualStudioCodeInsiders
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Bug was introduced with git version `2.32.0.windows.1`, up to git version `2.31.0.windows.2` the behavior was as expected.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Problem occurs with all of these (started directly as well as started via Windows Terminal):
&nbsp;&nbsp; - PowerShell 7.1.3
&nbsp;&nbsp; - PowerShell 7.2.0-preview.7
&nbsp;&nbsp; - CMD
&nbsp;&nbsp; - Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
rem my terminal size is 40 rows, 180 columns
> cd c:\git\github\git
> git log --pretty=oneline -30
```

 - What did you expect to occur after running these commands?

30 lines of git command history should be displayed

 - What actually happened instead?

Output stops in line 22, waiting for user input showing `:`

![image](https://user-images.githubusercontent.com/33368620/124540988-ce83dc80-de20-11eb-8a5d-9fadadbd681c.png)

The number of shown lines depends on terminal size (and on the history itself (commit comment length?)) but in all cases the output does not match the terminal size.

Interestingly these commands work correct:
```
> git log --oneline -30
> git log --oneline -n 30
> git log --pretty=oneline -30 --abbrev-commit
> git log --pretty=oneline -n 30 --abbrev-commit
```

![image](https://user-images.githubusercontent.com/33368620/124541198-363a2780-de21-11eb-9fb7-71ef8706fe2a.png)

Bug was introduced with git 2.32, up to git version 2.31.0 the output was correct.

![image](https://user-images.githubusercontent.com/33368620/124541780-6afaae80-de22-11eb-9f38-86537030acff.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Tested with `https://github.com/git-for-windows/git.git`, but this is not repository-specific.

**Comment by rimrul** [comment]
This sounds like it might be fixed by #3272. Could you test the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by Peter-76** [comment]
Tested with `git version 2.32.0.windows.1.20.gef510a35fa.20210705143525` -> fixed!

**Comment by rimrul** [comment]
Thanks for confirming it's fixed.
