### ISSUE TITLE
Git diff unusable in v 2.32.0 64 bit

### ISSUE THREAD

**Issue by SamanthaAdrichem** [git-for-windows/git#3311]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

$ git --version --build-options
git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1081]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Noope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Git diff
```
 - What did you expect to occur after running these commands?

A normal diff where you scroll down and see the next line

 - What actually happened instead?

When you press down, You get to the end of the line of that new line and you can't even read any of the diff, see screenshot.
![image](https://user-images.githubusercontent.com/9433667/124553057-9090b380-de34-11eb-8dce-63f77482f2d0.png)

Downgrading back to 2.31.1 resolves the issue.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by rimrul** [comment]
Could you check wether this is fixed in the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html)? There's been a bit of an issue with `less` on terminals that aren't 80 columns wide in 2.32.0

**Comment by SamanthaAdrichem** [comment]
Yes it seems to work fine in the latest snapshot

```
git version 2.32.0.windows.1.20.gef510a35fa.20210705143525
cpu: x86_64
built from commit: ef510a35fa97108e4f6790bdf35fd64ae7a4382d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

**Comment by rimrul** [comment]
That's great to hear.

**Comment by bambams** [comment]
I don't know when this is scheduled for release, but I'm lucky to have found this thread and upgraded because I had just reformatted my development laptop and so I had no reason to suspect the bug was in Git for Windows. I'd say rush that fix out if it's simple and stable. I think I had automatic updates enabled, but I was still affected this evening until installing the latest snapshot (Git-prerelease-2.32.0.windows.2-4-g37796bca76-20210715122133-64-bit.exe).

**Comment by Naine** [comment]
@bambams v2.32.0.windows.2 has already released with the fix.

**Comment by bambams** [comment]
How embarrassing. Sorry. I jumped to conclusions when I didn't see any CI in the thread or other mention of release towards the end. But that makes sense and I'm just tired. Please ignore. I've installed the latest stable instead. Thanks for correcting me!
