### ISSUE TITLE
`Unable to install Windows Terminal Fragment to C:\ProgramData\Microsoft\Windows Terminal\Fragments\Git\git-bash.json` error while updating

### ISSUE THREAD

**Issue by darkred** [git-for-windows/git#3312]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1081]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

(nothing)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MINGW64

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I just ran Git-2.32.0.2-64-bit.exe to upgrade from Git-2.32.0-64-bit.exe

 - What did you expect to occur after running these commands?

No error, just to complete.

 - What actually happened instead?

I got this error:

```
Line 2798: Unable to install Windows Terminal Fragment to C:\ProgramData\Microsoft\Windows Terminal\Fragments\Git\git-bash.json
```

![2021-07-07_004135](https://user-images.githubusercontent.com/723651/124671052-91b9f300-debd-11eb-8444-a1b21348e81e.jpg)

Note: there is no `C:\ProgramData\Microsoft\Windows Terminal` path in my system.
But, I have Windows Terminal 1.8.1521.0 installed via Microsoft Store.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

(nothing)

**Comment by jeremyd2019** [comment]
I saw this too.  It seems to be an upgrade situation when the fragment was installed by old version and is trying to be installed by the new version.  Re-running the installer resulted in it successfully installing the fragment.

**Comment by dscho** [comment]
Hmm. I guess we cannot rely on the directory to exist when [`InstallWindowsTerminalFragment()`](https://github.com/git-for-windows/build-extra/blob/012a1e23fd35083fae7b8b61f6d8da611fafe103/installer/install.iss#L2775-L2800) is running? Even if [it should have been created](https://github.com/git-for-windows/build-extra/blob/012a1e23fd35083fae7b8b61f6d8da611fafe103/installer/install.iss#L141-L142) (but maybe that comes _after_ [what we do in the post-install phase](https://github.com/git-for-windows/build-extra/blob/012a1e23fd35083fae7b8b61f6d8da611fafe103/installer/install.iss#L3328-L3329). Puzzled.

It would probably paper over the issue if we called [`ForceDirectories()`](https://jrsoftware.org/ishelp/topic_isxfunc_forcedirectories.htm) in `InstallWindowsTerminalFragment()`, but I would love to understand how this is happening.

**Comment by rimrul** [comment]
`[Dirs]` is processed during the so called ["actual installation process"](https://jrsoftware.org/ishelp/index.php?topic=installorder), [`ssPostInstall` happens after that](https://jrsoftware.org/ishelp/index.php?topic=scriptevents), so the directory should exist.

**Comment by darkred** [comment]
> `[Dirs]` is processed during the so called ["actual installation process"](https://jrsoftware.org/ishelp/index.php?topic=installorder), [`ssPostInstall` happens after that](https://jrsoftware.org/ishelp/index.php?topic=scriptevents), so the directory should exist.

No, the `C:\ProgramData\Microsoft\Windows Terminal` parent directory didn't exist for me yesterday that I did the upgrade.
It was only created just now, when I re-ran the installer, as @jeremyd2019 described:

> Re-running the installer resulted in it successfully installing the fragment.

and contains just 1 file, `git-bash.json`:

<details>
<summary>screenshot (click to expand)</summary>

![2021-07-07_123619](https://user-images.githubusercontent.com/723651/124737246-6e745f80-df20-11eb-849e-3bb1a9b6e330.jpg)


</details>

**Comment by liayn** [comment]
I do get the same error message. Let me know if you need system details which help to narrow the root cause.

**Comment by rimrul** [comment]
> No, the `C:\ProgramData\Microsoft\Windows Terminal` parent directory didn't exist for me yesterday that I did the upgrade.

Sorry, I wasn't clear there. I didn't mean to say the directory exists on your computer.

I meant to clarify to dscho that our understanding of what part of the `iss` file gets proccessed in what order was as documented and the issue seems to be that processing of the  `[Dirs]` section can apparently silently fail to create the expected directories under certain conditions.

**Comment by rimrul** [comment]
I found a slight discrepancy between `[Dirs]` and `InstallWindowsTerminalFragment()` but from my understanding it can't be the cause of this error.

We check `IsAdminInstallMode()` in `InstallWindowsTerminalFragment()`, but `IsAdminLoggedOn()` in `[Dirs]`. If I understand the difference correctly, this could cause us to create the directory for a System install and then fail to put the file into the target directory for a per-user install, under cetrain circumstances, but the resulting error message would be about `C:\users\xyz\appdata\local\Microsoft\Windows Terminal\Fragments\Git\git-bash.json` (or similar).

I don't think `IsAdminInstallMode()` can return true without `IsAdminLoggedOn()` also returning true, though.

**Comment by dscho** [comment]
Oh, I think I know what it is: during an upgrade, we uninstall the previous version. That also happens during `ssPostInstall`.

I actually started putting together a PR (using the occasion for some other improvements in the installer I've been meaning to work on for ages), but got side-tracked by a vaccination.

Watch this space for updates from my side.

**Comment by dscho** [comment]
Here is the update: https://github.com/git-for-windows/build-extra/pull/363

**Comment by dscho** [comment]
Once the [Git artifacts run](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=80930&view=results) has completed, the [Snapshots release pipeline](https://dev.azure.com/Git-for-Windows/git/_apps/hub/ms.vss-releaseManagement-web.hub-explorer-2?definitionId=2&view=mine&_a=releases) should be triggered automatically to upload a new [snapshot](https://wingit.blob.core.windows.net/files/index.html).

@darkred once this snapshot is available, could I ask you to test?

**Comment by darkred** [comment]
@dscho Yes, of course, I'd gladly help!

So, I just ran the new snapshot from [here](https://wingit.blob.core.windows.net/files/Git-prerelease-2.32.0.windows.2-4-g37796bca76-20210715122133-64-bit.exe), both as an update and as clean install(after uninstalling),
and in both cases I had checked the `NEW Add a Git Bash Profile to Windows Terminal` during installation
*(I mean the last checkbox in:*
![2021-07-15_162421](https://user-images.githubusercontent.com/723651/125796320-e5a2a017-613d-4d12-b272-e1b1dd2ff888.jpg)
and it completed successfully(=without errors) in both cases.

**Comment by dscho** [comment]
Yay! Thanks for verifying the fix.

**Comment by Ronald-G-Andrade** [comment]
Hello dear people. I encounter this error in the latest v2.33.0-rc1

Runtime Error (at 325:19181)
Could not call proc.

Thanks a lot :) !!

**Comment by dscho** [comment]
> Runtime Error (at 325:19181)
> Could not call proc.

That error message, as you most likely guessed, does not help. A full bug report, with as much information as you can provide, would most likely help more.

**Comment by dscho** [comment]
(For the record, I cannot reproduce the reported issue.)

**Comment by Ronald-G-Andrade** [comment]
> 
> 
> > Runtime Error (at 325:19181)
> > Could not call proc.
> 
> That error message, as you most likely guessed, does not help. A full bug report, with as much information as you can provide, would most likely help more.

Hello dear friend, sorry I don't know (yet) how to dump a full bug report :( 

I've just installed the new version 2.33.0 RC2, previously (on version 2.33.0 RC0) I checked the option to install the Git Bash of the Windows Terminal (Release version - Not Preview version). Everything did well.

But since the installation of 2.33.0 RC1 I'm facing this issue. I still have the Git Bash on Windows Terminal

![imagen](https://user-images.githubusercontent.com/68496378/129274423-0bcfdc4c-0436-4f17-8be2-800a3b657829.png)

**Comment by dscho** [comment]
Looking at the code, from the shown status message "Writing Windows Terminal Profile" I deduce that this error must happen some time during [the `InstallWindowsTerminalFragment()`](https://github.com/git-for-windows/build-extra/blob/77843591f050d564031b9acaaa83fb6c884c7c5e/installer/install.iss#L2781) function.

But I can't see where it would cause a "Could not call proc", as we're not calling any native function directly.

I also don't see this error in my setup, therefore I assume that there is something very special about _your_ setup. Searching around for "could not call proc", I could imagine that you try to run this via Wine or Crossover?

**Comment by Ronald-G-Andrade** [comment]
> 
> 
> Looking at the code, from the shown status message "Writing Windows Terminal Profile" I deduce that this error must happen some time during [the `InstallWindowsTerminalFragment()`](https://github.com/git-for-windows/build-extra/blob/77843591f050d564031b9acaaa83fb6c884c7c5e/installer/install.iss#L2781) function.
> 
> But I can't see where it would cause a "Could not call proc", as we're not calling any native function directly.
> 
> I also don't see this error in my setup, therefore I assume that there is something very special about _your_ setup. Searching around for "could not call proc", I could imagine that you try to run this via Wine or Crossover?

Hello dear friend, first, thank you very much for your reply 😃

No dear @dscho, I'm using:
**Windows 10 21H2 (19044.1165)**. I have the **Host File with Only-Read mode** (the file cannot be written unless I approve it).

The part of my Windows Terminal settings where Git Bash is configured is:
```
"guid": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}",
 "hidden": false,
"name": "Git Bash",
"source": "Git"
```

When I open Windows Terminal and the Git Bash Console, I'm facing this issue:
![Captura de pantalla 2021-08-13 185016](https://user-images.githubusercontent.com/68496378/129427765-672f8345-527d-462b-8a19-ccd53e72d88c.png)

**Comment by dscho** [comment]
I guess it doesn't like only-read mode.

**Comment by dscho** [comment]
>  I have the **Host File with Only-Read mode**

@Ronald-G-Andrade For my curiosity: how do you turn this mode on or off?

**Comment by Ronald-G-Andrade** [comment]
> 
> 
> I guess it doesn't like only-read mode.

🤔😕

> 
> 
> > I have the **Host File with Only-Read mode**
> 
> @Ronald-G-Andrade For my curiosity: how do you turn this mode on or off?

![Captura de pantalla 2021-08-14 135203](https://user-images.githubusercontent.com/68496378/129457413-60f091ea-3faf-4fa5-af11-f8274b922e04.png)

**Comment by dscho** [comment]
Now I understand better what you meant by "Host File", but I am more puzzled why this should have anything to do with writing the Windows Terminal Profile... Strange.

**Comment by Ronald-G-Andrade** [comment]
Dear mate @dscho the bug is still present 😞 
I installed the latest version 2.33.0 and the error dialog still appear.

**Comment by jeremyd2019** [comment]
> Hello dear people. I encounter this error in the latest v2.33.0-rc1
> 
> Runtime Error (at 325:19181)
> Could not call proc.
> 
> Thanks a lot :) !!

I just got this error message upgrading from 2.32.0.2 to 2.33.0 installing the 32-bit version on a Raspberry Pi 4 running Windows 10 21H1 ARM64.  I don't know if it matters, but I had Windows Terminal open at the time.  After the install, the Git Bash profile was still present in Windows Terminal, even after restarting it.

**Comment by dscho** [comment]
For the record, I cannot reproduce with the 64-bit version, even after setting the `C:\Windows\system32\drivers\etc\hosts` file to read-only, as this report suggested. The installation passes without problems.
