### ISSUE TITLE
Git doesn't exit properly when run in the context of a repository

### ISSUE THREAD

**Issue by Nirmal4G** [git-for-windows/git#3313]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using?

```
> git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running?

```
> ver

Microsoft Windows [Version 10.0.21390.2025]
```

 - What options did you set as part of the installation?

```
> type "%ProgramFiles%\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

   Versions older than v2.32 worked fine.

### Details

 - Which terminal/shell are you running Git from?

   Shell: Windows Terminal
   Console: PowerShell/CMD/Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
> git status
```

   If possible, run the above command or any other git command over multiple repos at once,
   either in parallel or sequential to see the Git processes being created but not destroyed.

   Observe this behaviour in Windows Task Manager or your preferred task monitoring tool!

 - What did you expect to occur after running these commands?

   Git should exit successfully.

 - What actually happened instead?

   Git stays in the background after successful execution.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

   Any repository is fine.

**Comment by rimrul** [comment]
> Enable FSMonitor: Enabled

I think you're experiencing the builtin file system monitor at work.

**Comment by Nirmal4G** [comment]
I suspected that might be the case.

**Comment by dscho** [comment]
> I think you're experiencing the builtin file system monitor at work.

Yep, and I think that feature works as designed. If you don't want it, reinstall Git for Windows and uncheck that checkbox for the built-in file system watcher.

**Comment by Nirmal4G** [comment]
This shouldn't happen when the fsmonitor is enabled. Is there anyway to debug and fix it?

**Comment by dscho** [comment]
> This shouldn't happen when the fsmonitor is enabled. Is there anyway to debug and fix it?

Why shouldn't it happen? The FSMonitor runs as a background process. It can't monitor anything if it's not running.

**Comment by Nirmal4G** [comment]
I think, either you misunderstood what I was talking about or I might've not explained properly.

Let me clarify this issue…

It didn't happen with the previous versions. So, this is a regression. Everytime I invoke `git`, it performs the requested operation and keeps monitoring the repo but only one process will remain in the background but now every invoke remains in the background even in the same repo. It results in explosion of `git` processes, so when it hits a certain amount (_depending on storage, memory, processing of your PC_) the last created process hangs and spews out some `fsmonitor` error. So, to be on the safe side, I had to kill all the `git` processes everytime.

**Comment by dscho** [comment]
> and spews out some `fsmonitor` error.

It would make a lot of sense to impart with the exact error message.
