### ISSUE TITLE
fatal: failed to stat - HOME on Windows Share

### ISSUE THREAD

**Issue by virtualdreams** [git-for-windows/git#3314]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
   64-bit

```
$ git --version --build-options
git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
   Windows 2016 Server

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
None, i use `PortableGit-2.32.0.2-64-bit.7z.exe`

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

HOME ist set to remote share. AD-User.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
 - Bash or CMD

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ cd
# -> /u

$ git config --list
fatal: failed to stat '                       //server_name/user$/': Permission denied

$ ls -la
total 411806
drwxr-xr-x 1 username 1049089         0 Jul  8 08:56  ./
drwxr-xr-x 1 username 1049089         0 Jul  8 09:26  ../
-rw-r--r-- 1 username 1049089      2978 Jul  8 09:31  .bash_history
-rw-r--r-- 1 username 1049089        94 Jul  7 16:43  .gitconfig

$ cat .gitconfig
[user]
        name = User Name
        email = username@example.com
[pull]
        ff = only
```

**Comment by dscho** [comment]
I have to admit that I have a really hard time even starting to figure out how to turn this into a Verifiable example.

**Comment by virtualdreams** [comment]
I can understand that completely. I am also completely missing the reason. Likewise, a meaningful log is also missing.

I can only say, if I am in a repository and call the same command so this error does not come. Maybe this helps a little bit.

```sh
username@servername MINGW64 /u
$ git config --list --global --show-origin
fatal: failed to stat '                       //server_name/user$/': Permission denied

username@servername MINGW64 /u
$ cd -
/u/Repos/notes-core

username@servername MINGW64 /u/Repos/notes-core (master)
$ git config --list --global --show-origin
file:U://.gitconfig     user.name=User Name
file:U://.gitconfig     user.email=user.name@example.org
file:U://.gitconfig     pull.ff=only
file:U://.gitconfig     http.sslbackend=schannel
file:U://.gitconfig     core.autocrlf=false
```

**Comment by dscho** [comment]
> I can understand that completely. I am also completely missing the reason.

I was not talking about the reason. I was talking about the description of what was claimed to be a Minimal, Complete and Verifiable Example. It is minimal all right, so minimal in fact that I do not know enough to even understand what I would have to set up to even attempt to reproduce (AKA "verify") the problem.

**Comment by virtualdreams** [comment]
Then I need options that allow me to provide more information.
Unfortunately the error message is not meaningful nor is there a log.
The example described in the last comment is the best possible example I can provide under the circumstances.


Operating environment is a Windows 2016 terminal server with user rights only.The user profiles are offloaded to user shares (Active Directory settings).  I don't have administrative rights and for anything else I don't get any information from the IT department, unfortunately.

**Comment by rimrul** [comment]
In CMD or poweshell, could you check the contents of these environment variables:

* `HOME`
* `HOMEDRIVE`
* `HOMEPATH`
* `USERPROFILE`

which of these are set? Do they point to `U:\` or `\\server_name\user$\`? Does the share name actually end in a dollar sign? 

Do you know any details about the share? Is it provided by a Windows server? 2016? What's the underlying filesystem? Are you using SMB3?

Maybe `GIT_TRACE` reveals something interesting.

**Comment by virtualdreams** [comment]
```sh
HOMESHARE=\\server_name\user$\username
HOME=/u/
HOMEDRIVE=U:
HOMEPATH=\
USERPROFILE=C:\Users\username
```

```sh
username@servername MINGW64 /u/Tools/PortableGit
$ GIT_TRACE=1 git config --global --list
13:37:08.658340 exec-cmd.c:237          trace: resolved executable dir: //server_name/user$/username/Tools/PortableGit/mingw64/bin
fatal: failed to stat '                       //server_name/user$/': Permission denied
```

The remote share is a Windows 2016 server, so NTFS. SMB1 and SMB2 are additionally enabled. I assume that SMB3 is used, but I can't check it (`Get-SmbConnection` needs higher permissions).

Hidden shares end with a dollar sign, so that is correct.

Note: **servername (terminal server)**, **server_name (shares server)** and **username** are replaced. However, these are always correct in any case.

**Comment by rimrul** [comment]
> GIT_TRACE=1 git config --global --list
13:37:08.658340 exec-cmd.c:237          trace: resolved executable dir: //server_name/user$/username/Tools/PortableGit/mingw64/bin
fatal: failed to stat '                       //server_name/user$/': Permission denied

Ok, that tells us two interesting things. a) The issue happens before we get to the [second expected trace message in `run_builtin()`](https://github.com/git/git/blob/master/git.c#L455)

and b) `$HOME` might have been a red herring since the executable dir is also under `\\server_name\user$\`

could you test copying the `PortableGit` folder somewhere local?

**Comment by virtualdreams** [comment]
Ok, this is really interesting...

```sh
username@servername MINGW64 /
$ GIT_TRACE=1 git config --global --list
14:59:49.401733 exec-cmd.c:237          trace: resolved executable dir: C:/Test/PortableGit/mingw64/bin
14:59:49.409735 git.c:455               trace: built-in: git config --global --list
14:59:49.415252 run-command.c:667       trace: run_command: unset GIT_PAGER_IN_USE; LESS=FRX LV=-c less
user.name=User Name
user.email=user.name@example.org
pull.ff=only
http.sslbackend=schannel
core.autocrlf=false
```

**Comment by mfriedrich74** [comment]
Hi,

Are you sure HOMESHARE=\\server_name\user$\username is correct?

My company uses HOMESHARE=\\server_name\user$

And with that i am wondering if the U drive is mapped to
HOMESHARE=\\server_name\user$
and you would see a U:\username folder. Or wether it's mapped to the
subfolder directly.

Also the traverse permission may have been forgotten to grant for the root
share.

**Comment by virtualdreams** [comment]
Yes, that is correct. There are other users under //server_name/user$/. U: is mapped to the user name.

But I think that there is a lot of "weird" configuration.

**Comment by mfriedrich74** [comment]
Ok,

I believe your IT did not grant you the traverse folder permission for the
user$ share/root folder.

I do not know if it needs to be removed so you don't see other users
folders. But this is my guess.

Other option is that your company enabled the Bypass traverse checking user
policy.

Then from the git side a question, why would git need traverse through
that? Maybe that is automatic and can't be avoided, i don't know.

Best regards, Mike

**Comment by mfriedrich74** [comment]
My company uses username$ shares, that prevents the traverse issue from a
curing.

**Comment by dscho** [comment]
Closing as stale.
