### ISSUE TITLE
Mistakes in /etc/nanorc - Git for Windows 2.32.0.2

### ISSUE THREAD

**Issue by julianxhokaxhiu** [git-for-windows/git#3315]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```sh
$ git --version --build-options
git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```sh
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19043.1081]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```sh
$ cat /etc/install-options.txt
Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing special, fresh install.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash and Windows Terminal, both present the same issue.

Git Bash:
![image](https://user-images.githubusercontent.com/1237070/124943649-f899f200-e00c-11eb-8de1-dfb3b46034c0.png)

Windows Terminal:
![image](https://user-images.githubusercontent.com/1237070/124944045-4dd60380-e00d-11eb-90f4-8ba348b7afc4.png)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```sh
$ nano
```
 - What did you expect to occur after running these commands?

Nano colorizes based on the syntax.

 - What actually happened instead?

Nano doesn't colorize and print an error message on the bottom.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by landstander668** [comment]
The actual error (visible in mintty after exiting nano) is:
```
Error in /etc/nanorc on line 237: Error expanding /usr/share/nano/*.nanorc: No such file or directory
```
The offending line contains `include "/usr/share/nano/*.nanorc"`, and sure enough the `/usr/share/nano` directory doesn't exist on my system. I haven't checked the previous release yet to determine whether or not it included the directory yet.

**Comment by landstander668** [comment]
I can confirm that  GFW 2.32.0.windows.1 portable **does** include the `/usr/share/nano` directory, which contains a number of small files, and the error in question no longer occurs. Line 237 of `/etc/nanorc` is identical for both versions.

I'll be pretty time constrained over the next few days, but can probably take a stab at fixing this on Monday/Tuesday of next week if no one tackles it first. Guessing it'll just require a relatively small tweak to https://github.com/git-for-windows/build-extra.

**Comment by julianxhokaxhiu** [comment]
Yes, I've come to the very same conclusion, but I just wanted to report it so it could be fixed in time for the next release :)

Thank you!
