### ISSUE TITLE
You can't create branch when also a subversion exists

### ISSUE THREAD

**Issue by Codeversum** [git-for-windows/git#332]
You can't create a branch containing a / when there is already a "parent branch" with the same but not the lowest "child":

    git checkout -b feat/something
    git checkout -b feat/something/else # Fails with error
Fails with the error:

    error: there are still refs under 'refs/heads/feat/something'
    fatal: Failed to lock ref for update: Is a directory
This is because (on Windows at least) you can't have a file and a directory in a directory with the same name. It also happens when you switch both commands aroung

**Comment by dscho** [comment]
Unfortunately, this is by design, and not even Windows-specific. You probably want to take this question to the Git mailing list: git@vger.kernel.org.
