### ISSUE TITLE
Incorrect and inconsistent End-Of-Line characters in .gitmodules after "git submodule set-branch --branch <branch_name>"

### ISSUE THREAD

**Issue by rosti-il** [git-for-windows/git#3321]
- [*] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1083]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Seems like an old bug. Seen it in the git version 2.31.1.windows.1 as well.
All repositories were cloned from a local disk on Windows.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git submodule set-branch --branch master -- ms1
```
 - What did you expect to occur after running these commands?

The .gitmodules file will be updated properly with consistent and correct End-Of-Line characters.

 - What actually happened instead?

The .gitmodules file is updated with a proper text but with inconsistent End-Of-Line characters.
All original lines are with DOS EOL and the added "branch = master" line is with UNIX EOL characters.
See attached screenshots:

binary view of the .gitmodules files:
![image](https://user-images.githubusercontent.com/45571812/125704575-b34e9230-4d40-414c-a7b4-8a21d80dac99.png)

vi view of the .gitmodules files (DOS EOL are shown as "^M" characters):
![image](https://user-images.githubusercontent.com/45571812/125704633-d66224c7-aa80-4526-ab28-2487097ff3a3.png)

**Comment by dscho** [comment]
I don't believe that Git considers its config files free game regarding line endings. Therefore, I think that having DOS line endings in there is already a violation of Git's assumptions. In any case, this is not a Windows-specific issue, even if DOS line endings are much more prevalent on Windows than on other platforms. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

**Comment by rosti-il** [comment]
Attaching an archive with Git repositories to reproduce this issue by others 
[git-tryouts.tar.gz](https://github.com/git-for-windows/git/files/6835344/git-tryouts.tar.gz)

**Comment by dscho** [comment]
Closing, as this should be discussed on the Git mailing list, as I had indicated.
