### ISSUE TITLE
built in fs monitor spawns tons of processes

### ISSUE THREAD

**Issue by Sil3ntStorm** [git-for-windows/git#3326]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1083]
64 bit of course (who runs 32 bit OS in 2021?)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related to the issue you're seeing?

Issue is there when `core.usebuiltinfsmonitor = true` and is gone when `core.usebuiltinfsmonitor = false`
The repository in question has a few dozen sub modules (which may contain submodules themselves), which contain a majority of the tracked files.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

[cmder](https://cmder.net) -> bash (from the git install)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global core.usebuiltinfsmonitor true
git status
```
 - What did you expect to occur after running these commands?

Show a report on the status of the working directory

 - What actually happened instead?

It does what is expected, however it also spawns about 80 processes of `mingw64\libexec\git-core\git.exe fsmonitor--daemon run` for the repository in question.
All of these processes keep running indefinitely and need to be manually killed eventually, as bash won't exit otherwise. This is due to all the git processes that are still running. Hitting Ctrl + C will kill all those git processes and allow bash to exit.
From the looks of it, it appears as though it might be starting an fsmonitor daemon for every git tree. The amount of `.git` files and folders roughly matches the number of processes spawned.

As it stands the fsmonitor feature is pretty useless, due to the sheer number of processes spawned and the fact that you can no longer exit the shell and have to (more or less) manually kill these processes before being able to exit the shell.
It does however make `git status` return in an acceptable time frame (roughly 10-20x faster in the given repository).

**Comment by dscho** [comment]
> From the looks of it, it appears as though it might be starting an fsmonitor daemon for every git tree. The amount of `.git` files and folders roughly matches the number of processes spawned.

This is expected. The FSMonitor _has_ to have one instance per Git tree. Of course, the FSMonitor feature is primarily designed to help with _large_ worktrees, therefore you would need a pretty large disk to support 80+ large worktrees. Maybe the FSMonitor in its current design is not quite the right tool to help your use case.

> All of these processes keep running indefinitely and need to be manually killed eventually, as bash won't exit otherwise.

This "bash won't exit otherwise" is definitely a bug. @jeffhostetler do you have any idea how we could handle this? I think we have to somehow spawn the background process with `DETACHED_PROCESS` or something like that.

**Comment by Sil3ntStorm** [comment]
> This is expected. The FSMonitor _has_ to have one instance per Git tree. Of course, the FSMonitor feature is primarily designed to help with _large_ worktrees, therefore you would need a pretty large disk to support 80+ large worktrees. Maybe the FSMonitor in its current design is not quite the right tool to help your use case.

I would have expected there to be a single process that simply manages all the folders that need to be managed. It shouldn't really be much of a high intensity work load that it couldn't be handled by a single process simply watching all the directories that need watching?
When I saw the feature, I was kind of expecting that it spawns a single process that then simply gets told which folders to watch. If any additional directories need to be watched, it would simply see that a fs monitor process already exists and tells the running process to also watch these additional directories.

**Comment by jeffhostetler** [comment]
For it to spawn 80 processes, you would need to be active and have run Git commands in all 80 repos.  Unless of course there's a bug where processes aren't exiting and you have more than one associated with a single repo.  Do you have ~80 active repos??

WRT spawning detached, I thought we were handling that, but I will double check.

I want to get to the point where we have 1 daemon process handling multiple repos instead of each process handling one repo, but I don't have it in the V1 version.

**Comment by Sil3ntStorm** [comment]
I simply do a `git status` in the root of the repository.
The repository is a non-trivial repo that has a few submodules (which in turn also have submodules themselves).
As soon as you run a single git status it spawns those ~80 processes. If you then press Ctrl + C all of them disappear.

I only tried it in that single repository, and only did a single git status. Subsequent git status do not spawn additional processes (that I can tell) and return quite fast.

**Comment by jeffhostetler** [comment]
ok, if you have 1 "parent" repo and it recursively contains ~80 submodules, I could see you having a bunch of fsmonitor processes running in the background.  that usage wasn't really anticipated.  or rather, it wasn't expected that fsmonitor would be turned on in all submodules.

do you have `core.useBuiltinFSMonitor` set to true globally `git config --list --show-origin` ?

I would unset it there and then explicitly set it locally in just the large repo(s).
(There is a certain amount of overhead in doing the IPC and for small repos, the IPC overhead costs can outweigh the savings.)

**Comment by Sil3ntStorm** [comment]
From my understanding that is one of the most promising use cases however. The other promising use-case being huge mono repos with tens of thousands of tracked files. The latter use-case seems to be the only one it really helps with (although I have not personally tried as I don't have a huge mono repo).
A `git status` takes forever on Windows due to the slow(ish) file system operations on Windows in general.  
My previous workaround used to be to exclude submodules when doing a git status. That however has its own downsides, such as potentially overseeing changes in submodules.

With the fs monitor description I figured I could revert back to including submodules in a git status. While it does what it's supposed to. the sheer amount of processes makes it feel bad/wrong.

I will need to check performance of `git status` with enabling the fs monitor only for the parent repo and having it disabled globally, especially with changes in some submodule.

Still the issue of there being a process that prevents the shell from closing remains regardless.

**Comment by jeffhostetler** [comment]
Having 80 submodules is going to be sluggish on Windows (as you already know) regardless -- status spawns a child process to run status within each submodule -- with or without FSMonitor daemons listening, Git still has to do each repo's status in a separate process.  IIRC, work is underway to allow a single process to have multiple repos in memory, but IIUC that is won't be ready for a while.

Yes, I need to look at the shell closing problem.  I filed a bug on that.

And yes, I've been thinking about having a minimum repo size for which the daemon would not be used.  Much like it makes not sense to start it on a bare repo.

Thanks for your comments (and testing).  Let us know if you have further issues or suggestions.

**Comment by dscho** [comment]
Closing as stale.

**Comment by Sil3ntStorm** [comment]
The shell not closing issue has been fixed in subsequent versions of git it would seem. However the issue with the sheer number of monitor processes remains.

Now I occasionally run into the issue that file operations are blocked by Windows due to some process having open handles on these locations. By now I have a hotkey that simply executes `taskkill /F /IM git.exe` which makes the open handles held by the monitor disappear.

It would still be nice to eventually be able to get rid of that issue, but it is far less of an annoyance these days.
