### ISSUE TITLE
Non UTF-8 encoded .gitignore files are silently ignored.

### ISSUE THREAD

**Issue by KarelPeeters** [git-for-windows/git#3329]
There is the related issue #3227, but that was just closed since the issue creator's problem was "solved".
  
### Setup
<details>
<summary> Collapsed because I'm pretty sure non of this matters for this issue</summary>

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
> git --version --build-options
git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.65]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

</details>

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell, I'm not using the integrated git terminal. This makes it easy to accidentally cause this issue but it's not the root problem.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Start in an empty directory:

```
git init
echo "foo" > test
echo "test" > .gitignore
git status
```
Note that in Powershell this causes .gitignore to have encoding `UTF-16 LE BOM`, not the standard utf-8.

 - What did you expect to occur after running these commands?

Probably an error saying that `.gitignore` was not UTF-8 encoded.

 - What actually happened instead?

The `.gitignore` file was *silently* ignored. In my opinion programs should never silently ignore bad inputs, this is pretty dangerous.

**Comment by dscho** [comment]
> Note that in Powershell this causes .gitignore to have encoding `UTF-16 LE BOM`, not the standard utf-8.

Git does not handle UTF-16. This is an upstream issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

**Comment by dscho** [comment]
@KarelPeeters I could imagine that a viable way forward would be to teach Git to detect the UTF-16LE BOM (0xff 0xfe) and automatically convert it to UTF-8 internally.

This is probably the place to do it: https://github.com/git/git/blob/v2.32.0/dir.c#L1100 (here, we read the `.gitignore` in full, and after that, `buf` will contain the verbatim contents.)

You can use something like this:

```c
if (size > 1 && buf[0] == 0xff && buf[1] == 0xfe) {
    char *reencoded = reencode_string_len(buf, size, "UTF-8", "UTF16-LE-BOM", &size);
    if (!reencoded)
        die(_("could not convert contents of '%s' from UTF-16"), fname);
    free(buf);
    buf = reencoded;
}
```

This will also require updates to the documentation, of course, and could use a new testcase in `t/t0008-ignores.sh`.

If your C skills are pretty good, I would suggest to simply implement it and open a PR at https://github.com/git/git, then ping me so I can help with the contribution to the Git mailing list.

Even if you think that your C skills could use improvement: If you want to work on this, I will assist you.

**Comment by rimrul** [comment]
>I could imagine that a viable way forward would be to teach Git to detect the UTF-16LE BOM (0xff 0xfe) and automatically convert it to UTF-8 internally.

There is already some BOM detection and encoding conversion code in [`utf8.c`](https://github.com/git/git/blob/master/utf8.c) that might give a good starting point.

**Comment by dscho** [comment]
> There is already some BOM detection and encoding conversion code in [`utf8.c`](https://github.com/git/git/blob/master/utf8.c) that might give a good starting point.

Right, so the condition should not be `size > 1 && buf[0] == 0xff && buf[1] == 0xfe` but rather `size >= sizeof(utf16_le_bom) && !memcmp(buf, utf16_le_bom, sizeof(utf16_le_bom))`.

It might even make sense to introduce a helper, say, `char *wide_unicode_to_utf8(const char *in, size_t in_len, size_t &out_len)` that specifically detects the encoding from the BOMs.

**Comment by jamesbraza** [comment]
> Git does not handle UTF-16. This is an upstream issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

I have created [this mailing thread](https://groups.google.com/g/git-for-windows/c/wZyANi_eyi4/m/DanvPffIAAAJ) 🚀

**Comment by dscho** [comment]
> > Git does not handle UTF-16. This is an upstream issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
> 
> I have created [this mailing thread](https://groups.google.com/g/git-for-windows/c/wZyANi_eyi4/m/DanvPffIAAAJ) 🚀

@jamesbraza that's the Git _for Windows_ mailing list. And it is just repeating what has been said here, ignoring all the advice how to get started implementing it.

Wouldn't it feel much better if you actually sat down, cloned the Git source code, and implemented this? You would be featured as a new contributor, and you would get the nice and cozy feeling that you did something good, something lasting, something that made Git better?

If you struggle to get started, or face any hurdle while implementing the feature, I am more than happy to help you.
