### ISSUE TITLE
`git pull`/`git fetch` sometimes fail

### ISSUE THREAD

**Issue by fauxpark** [git-for-windows/git#3333]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1110]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

n/a
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am using MSYS2 with Git for Windows installed by following: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper. I was using the stock `msys2-runtime` but the issue also occurs with the GfW-supplied version.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

zsh, but shell seems unrelated - also happens in bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull <remote> <branch>
```
or
```
git fetch <remote> <branch>
```
 - What did you expect to occur after running these commands?

The commands complete successfully every time.

 - What actually happened instead?

`git pull <remote> <branch>` sometimes returns 1 without performing any action. `git fetch <remote> <branch>` sometimes returns 128 without performing any action. `git pull` and `git fetch` with no arguments seem unaffected.
![image](https://user-images.githubusercontent.com/4781841/126889456-277b3322-ae7a-44fe-9c78-4b1196a349d7.png)

I also see WER entries in Event Viewer for git-remote-https.exe with exception code `0xC0000005`, however they don't appear to be created every time the commands fail. I'm not sure if it is related.
```
Faulting application name: git-remote-https.exe, version: 2.32.0.2, time stamp: 0x60e4aa4b
Faulting module name: git-remote-https.exe, version: 2.32.0.2, time stamp: 0x60e4aa4b
Exception code: 0xc0000005
Fault offset: 0x00000000000db8e0
Faulting process ID: 0x332c
Faulting application start time: 0x01d7807bbc7b6230
Faulting application path: C:\msys64\mingw64\libexec\git-core\git-remote-https.exe
Faulting module path: C:\msys64\mingw64\libexec\git-core\git-remote-https.exe
Report ID: 27fb0503-d307-487f-b9fb-6de0377caa2d
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Fault bucket 2281282627242420479, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: git-remote-https.exe
P2: 2.32.0.2
P3: 60e4aa4b
P4: git-remote-https.exe
P5: 2.32.0.2
P6: 60e4aa4b
P7: c0000005
P8: 00000000000db8e0
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2C1.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2F1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC302.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC302.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC312.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_git-remote-https_91cb27e7451cfeb7615024bfccb333d238fd7f41_e7f0cc03_19958502-bcbd-4bae-bb79-45cac6c5a6b8

Analysis symbol: 
Rechecking for solution: 0
Report Id: 962fac52-b89c-4bf4-9e08-a857f4b92e55
Report Status: 268435456
Hashed bucket: 8554a8f4db0046f20fa8be76750de8ff
Cab Guid: 0
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by dscho** [comment]
> I am using MSYS2 with Git for Windows installed by following: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper. I was using the stock `msys2-runtime` but the issue also occurs with the GfW-supplied version.

As pointed out by that wiki page, this is not an officially supported scenario.

Does the same issue occur with a regular Git for Windows installation?

**Comment by fauxpark** [comment]
Yep, I understand that, and now I have just seen the last line of the second paragraph - I don't think that was there when I initially followed it, sorry. But I'd like to try to help and provide as much information as I can if it helps anyone.

I've just installed GfW proper, it seems to behave well so I guess this can be closed, and I'll try to figure out what's going on on my own.

**Comment by fauxpark** [comment]
Update: after my last comment I noticed I wasn't actually following the guide to the letter; I had the git-for-windows repo *below* the stock MSYS2 repos - probably in an attempt to *only* grab the git package(s).
After moving it where the guide says it should be, and running pacman (which downgraded `msys2-runtime` and `bash`), I haven't noticed any problems thus far. So, I suspect the problem is/was `msys2-runtime`.
