### ISSUE TITLE
rogue bitcoin address on the FAQ page of the wiki

### ISSUE THREAD

**Issue by lun-moon** [git-for-windows/git#3334]
- [ X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

na/this is a problem with the wiki

### Details
 - What commands did you run to trigger this issue? If you can provide a

```
load

https://github.com/git-for-windows/git/wiki/FAQ

in a browser 
```
 - What did you expect to occur after running these commands?
expect no link to a rogue bitcoin address on the FAQ page of the wiki

 - What actually happened instead?
 - there is a link on the right hand side bar that says "bitcoin address", the link is to page:
 - 
https://github.com/git-for-windows/git/wiki/Bitcoin-address/_history
"""
someone possibly unknown put a bitcoin address on the wiki, that someone is:
https://github.com/MegoyTambayan
"Revisions

Created Bitcoin address (markdown)

@MegoyTambayan MegoyTambayan committed 20 hours ago

"

revision content:
[bc1q7wedv4zdu5smt3shljpu5mgns48jn299mukymc](https://live.blockcypher.com/btc/address/bc1q7wedv4zdu5smt3shljpu5mgns48jn299mukymc/)
"""

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/git-for-windows/git/wiki/FAQ (contains the link)
https://github.com/git-for-windows/git/wiki/Bitcoin-address (is the rogue page)

**Comment by rimrul** [comment]
Thanks for notifying us. I deleted the rogue page. @dscho, can we ban the wiki vandals?

**Comment by dscho** [comment]
> 
> 
> Thanks for notifying us. I deleted the rogue page. @dscho, can we ban the wiki vandals?

Done. There was more vandalism (somebody had deleted the Symbolic Links page). I reinstated the page and banned them, too.

**Comment by PhilipOakley** [comment]
[Re-opening because:] The FAQ page looks to have completely disappeared. The FAQ link at the top of the https://gitforwindows.org/ page goes to a "Create new page".

How do we/I roll back the FAQ page to it's pre-'roque address' version. My foo on this is minimal.

**Comment by PhilipOakley** [comment]
> My foo on this is minimal.

Google/StackOverflow provides: https://stackoverflow.com/questions/24797429/how-do-i-undo-deleting-a-github-wiki-page and https://github.com/isaacs/github/issues/1265 so looks like I need to plan in some time for the extra steps (clone the wiki repo and revert stuff), rather than just a few browser clicks.. [not in today's schedule]

**Comment by rimrul** [comment]
I've reverted the faq back to it's pre-deletion state. I'll write up how to do it when I get home.

**Comment by PhilipOakley** [comment]
> I've reverted the faq back to it's pre-deletion state. I'll write up how to do it when I get home.

Many thanks!   Now it's back to my backlog ;-)
