### ISSUE TITLE
Getting "fatal: this operation must be run in a work tree" when repository is on a mapped home folder / drive

### ISSUE THREAD

**Issue by jacobq** [git-for-windows/git#3337]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

<details>
<summary>Setup</summary>

 - Which version of Git for Windows are you using? Is it 32-bit or **64-bit**?

```
$ git --version --build-options

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, **10**? Is it 32-bit or **64-bit**?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1110]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> H:\>type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I suspect that the problem is related to my user profile being mapped to a network drive through Active Directory. e.g. when I open `cmd.exe` the default location is `H:\`, doing `cd ~/Documents/` in Git Bash takes me to `/h/Documents/`, etc.

</details>

<details>
<summary>Details</summary>

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Normally I use git bash, but when I encountered this I also tried `cmd.exe` and observed the same problem.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git diff
git stash
```
 - What did you expect to occur after running these commands?

Wanted to see diff / stash changes.

 - What actually happened instead?

Got error message `fatal: this operation must be run in a work tree`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Repository is not publicly available.
</details>

Similar symptom to [stackoverflow 1456923](https://stackoverflow.com/questions/1456923/why-am-i-getting-the-message-fatal-this-operation-must-be-run-in-a-work-tree) in that running things like `git diff` resulted in `fatal: This operation must be run in a work tree`, but my repository was not bare. 
Also checked https://github.com/git-for-windows/git/issues/2569 but in this case there was no `worktree` option being set in `.git/config`. I tried adding one as well as using `--work-tree=.` (and similar with full path) per [stackoverflow 21639396](https://stackoverflow.com/questions/21639396/git-working-tree-in-mapped-windows-drive), but neither of these helped. I also tried updating git to latest (version info shown in setup/details above) and saw no difference.

Finally, I moved the repository folder to a local disk (i.e. `mv /h/Documents/my-repo /c/Users/me/Documents`) and the problem went away. I tried to reproduce the problem by creating a repository on the mapped drive using `git init`, but I did not observe the problematic behavior when I did this. I also tried cloning the same repository to that network drive but could not reproduce the problem.

If this issue is not actionable or whatever, feel free to close it. However, I thought it might be good to report the odd behavior nonetheless. Perhaps the next person to encounter it will then find this and be able to shed more light on it.

**Comment by dscho** [comment]
> Finally, I moved the repository folder to a local disk (i.e. `mv /h/Documents/my-repo /c/Users/me/Documents`) and the problem went away. I tried to reproduce the problem by creating a repository on the mapped drive using `git init`, but I did not observe the problematic behavior when I did this. I also tried cloning the same repository to that network drive but could not reproduce the problem.

That's interesting. The biggest question this throws up is: how do the contents of the `.git` directory differ between the working and the non-working case.

**Comment by jacobq** [comment]
> That's interesting. The biggest question this throws up is: how do the contents of the `.git` directory differ between the working and the non-working case.

I don't think they do. I think there is something different about how git is figuring the current working directory when working with a mapped drive, but I am going on a hunch. If I have the time bandwidth next month I'll try moving it back to see if the problem returns.

**Comment by dscho** [comment]
> I think there is something different about how git is figuring the current working directory when working with a mapped drive

But didn't you state that a freshly cloned repository _works_, as well as a freshly `git init`ialized one?

**Comment by dscho** [comment]
Closing as stale.
