### ISSUE TITLE
`git cat-file` and `git show` fail when using backslash as path separator

### ISSUE THREAD

**Issue by akaihola** [git-for-windows/git#3344]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.1052]
```

 - What options did you set as part of the installation? Or did you choose the defaults?

```
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash and CMD

 - What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

With Bash (escaping backslashes as double backslashes):
```shell
$ mkdir testrepo
$ cd testrepo
$ git init
Initialized empty Git repository in C:/Users/Me/AppData/Local/Temp/testrepo/.git/
$ mkdir subdir
$ touch subdir/file.txt
$ git add subdir/file.txt
$ git commit -m "Initial commit"
[master (root-commit) 1405312] Initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 subdir/file.txt

$ git cat-file -t HEAD:subdir/file.txt        # works with forward slash
blob
$ git cat-file -t HEAD:subdir\\file.txt       # but not with backslash
fatal: Not a valid object name HEAD:subdir\file.txt

$ git ls-files subdir\\non-existing-file.txt
$ git ls-files subdir/file.txt
subdir/file.txt
$ git ls-files subdir\\file.txt               # ls-files does work with backslash
subdir/file.txt
```
With CMD.EXE (using single backslashes):
```cmd
>REM                                          # cat-file fails
>git cat-file -t HEAD:subdir\file.txt
fatal: Not a valid object name HEAD:subdir\file.txt

>REM                                          # but ls-files works
>git ls-files subdir\file.txt
subdir/file.txt
```

 - What did you expect to occur after running these commands?

For `git cat-file`, see the output "`blob`" when using backslashes (in CMD.EXE) or double backslashes (in Bash) as path separators.

 - What actually happened instead?

Git gave the error message
```
fatal: Not a valid object name HEAD:subdir\file.txt
```

Note: As seen above, `git ls-files` does accept backslashes as path separators, but `git cat-file` does not.

**Comment by akaihola** [comment]
I tested a few other Git subcommands and found that `git show` also fails with backslashes.

These subcommands seem to work fine with backslashes:
- `git log`
- `git ls-files`
- `git diff`

**Comment by dscho** [comment]
> ```batchfile
> >git cat-file -t HEAD:subdir\file.txt
> ```

This assumes that `HEAD:` points to a Windows file system. But it does not. It points into a Git tree, where directory separators are firmly forward slashes and nothing else.

> ```batchfile
> >git ls-files subdir\file.txt
> ```

This is a bit special in that it is supposed to look into the Git index (which has the same rules as Git trees regarding the forward slash). But Git handles the backslash on Windows as if it were a forward slash. If you want to consider this a bug, I would agree, and would encourage you to feel free to work on a fix.

> These subcommands seem to work fine with backslashes:
> 
>     * `git log`
> 
>     * `git ls-files`
> 
>     * `git diff`

Apart from `ls-files`, those commands take pathspecs, which are inherently related to the current worktree. Therefore, I would not consider the current behavior a bug.

**Comment by akaihola** [comment]
> It points into a Git tree, where directory separators are firmly forward slashes and nothing else.

Ah, that explains it.

But I would argue that for a user not familiar with what happens under the hood in Git, this easily causes confusion. As Git users, we're still creating directories and files on the filesystem first, and handing them over to Git for version control. When cloning a repository and checking out a revision, a past state of the filesystem is restored. So for me it would make sense that we could refer to both Git trees as well as filesystem paths (which the trees do represent after all) in the same way.

From that point of view it is confusing that I can start working with Git and do (in CMD.EXE):
```
> echo text >subdir\file.txt
> git add subdir\file.txt
> git commit -m "add file"
> git log subdir\file.txt
> echo more text >>subdir\file.txt
> git diff subdir\file.txt
```
but suddenly e.g. this doesn't work:
```
> git show HEAD:.\subdir\file.txt
```

To illustrate the confusion using my personal experience:

As a non-Windows user willing to support Windows in my project which calls Git, I first figured that Git for Windows is happy with backslash separated paths (which is what Python's `Path` objects automatically become when converted to strings on Windows). But when I needed to add a call to `git cat-file`, things started to break. It took a good long afternoon of debugging (using GitHub Actions on Windows hosts) to understand that what I had learned earlier didn't hold for all Git subcommands.

Fortunately in Python it's trivial to force conversion of `Path` objects into POSIX slash-separated path strings, so for consistency I can just switch to using them everywhere even on Windows, and forget about backslash separated paths completely.

Anyway, I do appreciate the technical reasoning behind the current design, even though it leads to a slightly confusing user experience. And the inconsistency between behavior of `git cat-file` and `git ls-files` is just a minor wart.

**Comment by dscho** [comment]
Things are more complicated, of course. In filenames in a Git tree, a backslash is perfectly allowed a character.

If your wish was granted, and we offered to "magically" treat backslashes as directory separators in Git trees, we would totally mess up access to such Git trees.

Granted, you cannot check out such trees in Windows. But you can still clone commit histories where such trees are reachable.

I guess you could take this to the Git mailing list if you still think that it would be a viable way forward, to solicit advice how to implement it.

**Comment by akaihola** [comment]
I think I'm happy with everything I learned here. My project can successfully support Windows users wtih Git as is, and I have no further personal interest towards Windows as an environment.

Thanks @dscho for the time and effort you took to explain the details, and I hope this discussion will turn up in web searches for anyone who might face similar confusion as I did. Cheers!
