### ISSUE TITLE
Git for windows is a constant memory hog

### ISSUE THREAD

**Issue by helloWorldPsyduck** [git-for-windows/git#3351]
idea里创建一个前后端分离（前端vue，后端spring boot）的项目，正确配置gitignore，但是有时候在idea里点“Refresh”后，会有一个“Git for Windows”的进程一直占用内存直到电脑死机。
![image](https://user-images.githubusercontent.com/57513292/128466455-71fcf75b-ef65-4e55-8c69-e1db9377d4f6.png)
git之前是2.30版本，今天刚刚升级了2.32版本，并没有解决问题。
如果是没有vue的项目，不会出现这个问题。但是确实是正确配置了gitignore了。

**Comment by rimrul** [comment]
> I have created a project with a front-end and back-end separation (front-end vue, back-end spring boot) in idea and configured gitignore correctly, but sometimes after clicking "Refresh" in idea, there is a "Git for Windows " process that keeps taking up memory until the computer dies.
![image](https://user-images.githubusercontent.com/57513292/128466455-71fcf75b-ef65-4e55-8c69-e1db9377d4f6.png)
The previous version of git was 2.30, but I just upgraded to 2.32 today and it didn't fix the problem.
If it was a project without vue, this problem would not have occurred. But it does have gitignore configured correctly.

Translated with www.DeepL.com/Translator (free version)

**Comment by dscho** [comment]
Sadly, this is not enough information to go on.

One way to obtain more information would be to go to the Details tab to find out the process ID, then call `wmic process where processid=<id> get commandline`
