### ISSUE TITLE
Cannot support local repos with none-ASCII characters in path

### ISSUE THREAD

**Issue by lychichem** [git-for-windows/git#336]
For example, I have a repo which locates in "D:\Onedrive\文档\Github\Firefox-zh-CN-locale", there are Chinese characters in path, then git for Windows 2.5 cannot set it as a workspace. But in git for Windows 1.9.5 preview it CAN work properly. Hope you'll fix this problem.

**Comment by techstay** [comment]
我问题和你一样，目前只能先滚回了1.9……:sob:

**Comment by lychichem** [comment]
@techstay 你应该养成所有路径名都使用英文的习惯
And hope you developers can fix it. I don't know how many people uses their locale language with none ASCII characters as repo path.

**Comment by linquize** [comment]
WinXP (Chinese) desktop folder is `C:\Documents and Settings\User\桌面`
If you put your work inside desktop, you cannot avoid path containing Chinese.

**Comment by lychichem** [comment]
Right, and for Onedrive, in Chinese the document folder is called "文档“, like what I report.

**Comment by rikaunite** [comment]
Steps to reproduce the problem? Looks fine to me.
```
rikaunite@RIKAUNITE-LT MINGW64 ~
$ mkdir 测试

rikaunite@RIKAUNITE-LT MINGW64 ~
$ cd 测试

rikaunite@RIKAUNITE-LT MINGW64 ~/测试
$ git clone https://github.com/lychichem/Firefox-zh-CN-locale.git
Cloning into 'Firefox-zh-CN-locale'...
remote: Counting objects: 2655, done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 2655 (delta 66), reused 0 (delta 0), pack-reused 2503
Receiving objects: 100% (2655/2655), 2.00 MiB | 819.00 KiB/s, done.
Resolving deltas: 100% (1421/1421), done.
Checking connectivity... done.

rikaunite@RIKAUNITE-LT MINGW64 ~/测试
$ cd Firefox-zh-CN-locale/

rikaunite@RIKAUNITE-LT MINGW64 ~/测试/Firefox-zh-CN-locale (master)
$ touch 测试

rikaunite@RIKAUNITE-LT MINGW64 ~/测试/Firefox-zh-CN-locale (master)
$ ls
README.md  browser/  chrome/  chrome.manifest  install.rdf  测试

rikaunite@RIKAUNITE-LT MINGW64 ~/测试/Firefox-zh-CN-locale (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "\346\265\213\350\257\225"

nothing added to commit but untracked files present (use "git add" to track)

rikaunite@RIKAUNITE-LT MINGW64 ~/测试/Firefox-zh-CN-locale (master)
$ git add 测试

rikaunite@RIKAUNITE-LT MINGW64 ~/测试/Firefox-zh-CN-locale (master)
$ git commit -m 测试
[master 4425ebf] 测试
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 "\346\265\213\350\257\225"

rikaunite@RIKAUNITE-LT MINGW64 ~/测试/Firefox-zh-CN-locale (master)
$ git log -n 1
commit 4425ebfd61a2977fdeeab5c67d74a47bdcba4b43
Author: Your Name <you@example.com>
Date:   Sun Aug 30 13:11:32 2015 +0800

    测试
```
My system is Windows 10 English version with Chinese locale.

**Comment by lychichem** [comment]
DId you ever try to use git GUI? Under git GUI if you open a work zone containing Chinese character in path it will throw a error report.

**Comment by rikaunite** [comment]
OK, looks like Git GUI read path with wrong encoding.
![capture](https://cloud.githubusercontent.com/assets/841940/9566043/125ef890-4f25-11e5-9d67-6d23fddf5765.PNG)
Save as UTF-8:
![capture0](https://cloud.githubusercontent.com/assets/841940/9566101/eabcd138-4f27-11e5-8f4d-149f0e2ed7bf.PNG)
Load with GB2312(Current system locale):
![capture1](https://cloud.githubusercontent.com/assets/841940/9566102/ed24dd30-4f27-11e5-93c6-b7ae9b17a832.PNG)

**Comment by dscho** [comment]
> Hope you'll fix this problem.

Please note that throwing your problem my way, leaning back and munching peanuts is not exactly something I find highly motivating.

At least you could pretend that you are interested in participating actively in the resolution of this bug, it is an Open Source project, after all, not a paid-for product.

17 days are a long time. Long enough, certainly, to at least ask for advice how to start diagnosing one's own problem.

**Comment by dscho** [comment]
Everybody who has this problem should download `msys-2.0.dll` from https://github.com/dscho/msys2-runtime/releases/tag/home-non-ascii, replace the local file of the same name (it is in `Git\usr\bin`) and test.
