### ISSUE TITLE
Windows 7 installation error

### ISSUE THREAD

**Issue by greenozon** [git-for-windows/git#3368]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

 git --version --build-options
git version 2.33.0.windows.1
cpu: x86_64
built from commit: fb59c1de9fd599a3eeb8459eb7cab731c6672ea3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

![image](https://user-images.githubusercontent.com/765343/129724291-9ca7fced-b66e-4109-8fa4-c290c9f37cbe.png)

**Comment by dscho** [comment]
Was this an upgrade? Do any previous versions install without problems? If so, could you pinpoint which [snapshot](https://wingit.blob.core.windows.net/files/index.html) is the first one where it broke?

**Comment by acohenOT** [comment]
I'm having the same exact problem using Windows Server 2016 trying to upgrade from 2.32 to 2.33.

**Comment by rimrul** [comment]
We've had an [earlier report about the exact same error message](https://github.com/git-for-windows/git/issues/3312#issuecomment-897989946) on windows 10 during a different part of `ssPostInstall` with `2.33.0-rc1`.

And it seems I can reproduce the issue by installing 32bit Git for Windows 2.33.0 on 64bit Windows 10.

I think we're accidentally trying to load an external Function for `ExecWithCapture` from a 64bit DLL.

**Comment by greenozon** [comment]
@dscho  I did have git some time ago, then removed
It might leave some stuff in user dir, I don't know
but today it was fresh install

PS Issue is not critical, it might be a warning?  git itself is fully functional

**Comment by dscho** [comment]
No, it is not a warning, it is a real error. Your Git might work most of the time, though. Without digging deeper, I cannot say what operations might be affected.

**Comment by acohenOT** [comment]
Not sure if it matters, but when I recreated the error, the only options I chose were to use Visual Studio Code as the default editor and to override the branch name to `main`. All other options were left at the defaults.

**Comment by dscho** [comment]
> I think we're accidentally trying to load an external Function for `ExecWithCapture` from a 64bit DLL.

That sounds quite plausible...

However, the installer _is_ 32-bit. So I would expect the same problems no matter whether installing a 32-bit or a 64-bit Git for Windows.

**Comment by rimrul** [comment]
It doesn't happen for me with the 64bit installer, but it happens reliably with the 32bit installer. No matter what options I choose I always get the error message. If I choose to install the terminal fragment it happens on that step, otherwise on the explorer integration step.

**Comment by acohenOT** [comment]
I'm using the 64-bit installer and I get the error in the Explorer Integration step.

**Comment by rimrul** [comment]
If I select neither LFS nor the terminal fragment it happens on "Removing bundled Git LFS".

**Comment by dscho** [comment]
Could you rebuild the installer, with `LogError(...)` debug statements thrown in liberally, to pinpoint _which_ call fails?

**Comment by rimrul** [comment]
Yes.

**Comment by ChloeESG** [comment]
I am having the same error message too. May I know if this is still usable or should I just reinstall?

**Comment by rimrul** [comment]
>this is still usable 

We don't currently know how usable this is.

> or should I just reinstall?

That'll likely produce the same error again.

**Comment by worstpractice** [comment]
![error](https://user-images.githubusercontent.com/54796463/129949612-a5bbf09d-cce4-4977-8348-5de1524194b7.png)
Can confirm this issue when upgrading from previous version on Windows 10 Pro (v. 10.0.19042 Build 19042).

**Comment by Purpzie** [comment]
Also experiencing this on Windows 10.

```
Microsoft Windows [Version 10.0.18363.1500]
```
```
git version 2.33.0.windows.1
cpu: x86_64
built from commit: fb59c1de9fd599a3eeb8459eb7cab731c6672ea3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
```
Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled```

**Comment by TectonicTMI** [comment]
Same issue as OP, but OS is Windows 8 Pro. 

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>git --version --build-options
git version 2.33.0.windows.1
cpu: x86_64
built from commit: fb59c1de9fd599a3eeb8459eb7cab731c6672ea3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

C:\Windows\system32>cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]

C:\Windows\system32>
```

Had an update notification, clicked on it, and this was the error at the end. 

![image](https://user-images.githubusercontent.com/19977061/130158895-234ed431-408e-40b9-8e54-d6d790449c11.png)

Went to the website and downloaded the latest installer (64-bit) and received the exact same error.

**Comment by DustinWin** [comment]
I have the same problem.
System version: Windows 11 22000.160
Git version: 2.33.0
Operation steps: Installing 2.33.0 from 2.32.0 overlay.
![QQ截图20210821100603](https://user-images.githubusercontent.com/45238096/130307351-9947e814-5c96-4b89-b83d-88e8a91884de.png)

**Comment by PetSerAl** [comment]
I have the same error on Microsoft Windows [Version 10.0.19043.1165].

I tested it in clean installation of Widows in VM:
Clean install: git setup working.
Removing OpenSSH client Windows capability: git setup fails.
Reinstalling OpenSSH client Windows capability: git setup working again.

So I reinstall OpenSSH client Windows capability on my main PC, and git successfully installed now. Hope this help others.

**Comment by PetSerAl** [comment]
It seems mere existence of `ssh.exe` in directories of the `PATH` environment variable is enough to solve this issue.

**Comment by PetSerAl** [comment]
Looks like this is root of the issue:
https://github.com/git-for-windows/build-extra/blob/f1854b8bb8e5e572658f5a626eb2525bf29cf5aa/installer/install.iss#L3368

`if` condition should additionally check for `SSHChoicePage<>NIL`.

**Comment by aicarambazigalo** [comment]
but please notice the context of the error is different for example in the above two comments:
https://github.com/git-for-windows/git/issues/3368#issuecomment-902330600
https://github.com/git-for-windows/git/issues/3368#issuecomment-903038300

I'm guessing it's another context than the above two for this comment also: https://github.com/git-for-windows/git/issues/3368#issuecomment-903056274

**Comment by PetSerAl** [comment]
@aicarambazigalo What exact difference you are pointing to?

**Comment by aicarambazigalo** [comment]
> 
> 
> @aicarambazigalo What exact difference you are pointing to?

I've edited my comment with the pointed-to difference for each comment

**Comment by rimrul** [comment]
>but please notice the context of the error is different for example in the above two comments:

The progress text depends on the features you want to install, but it does seem to always be the last step before the openssh step.

**Comment by aicarambazigalo** [comment]
> 
> 
> > but please notice the context of the error is different for example in the above two comments:
> 
> The progress text depends on the features you want to install, but it does seem to always be the last step before the openssh step.

perhaps it's still the openssh step the culprit, but the context text doesn't get updated as fast, and maybe that's why it seems like it's previous steps??

**Comment by rimrul** [comment]
And the potential fix by @PetSerAl supports that, as it would happen right before the Text switches to the openssh text.

**Comment by aicarambazigalo** [comment]
> 
> 
> And the potential fix by @PetSerAl supports that, as it would happen right before the Text switches to the openssh text.

this is like 4 steps earlier https://github.com/git-for-windows/git/issues/3368#issuecomment-902330600 [Initializing Explorer integration](https://github.com/git-for-windows/build-extra/blob/f1854b8bb8e5e572658f5a626eb2525bf29cf5aa/installer/install.iss#L3282)

**Comment by aicarambazigalo** [comment]
> 
> 
> > > but please notice the context of the error is different for example in the above two comments:
> > 
> > 
> > The progress text depends on the features you want to install, but it does seem to always be the last step before the openssh step.
> 
> perhaps it's still the openssh step the culprit, but the context text doesn't get updated as fast, and maybe that's why it seems like it's previous steps??

ah it must be all the 'if' conditionals, so it only shows the previous step as text, which in some cases it's the `Initializing Explorer integration", and just doesn't get to repaint with the ssh text step

**Comment by rimrul** [comment]
> this is like 4 steps earlier #3368 (comment)

I know, but, depending on the features you choose to install, the steps in between get skipped and thus do not change the text.

**Comment by aicarambazigalo** [comment]
> 
> 
> > this is like 4 steps earlier #3368 (comment)
> 
> I know, but, depending on the features you choose to install, the steps in between get skipped and thus do not change the text.

you're right, I've [realized ](https://github.com/git-for-windows/git/issues/3368#issuecomment-903071684)that now.

**Comment by rimrul** [comment]
I built an Installer with the proposed fix, and it installed without error. 🎉

**Comment by greenozon** [comment]
Had an interesting debug session like building git installer from scratch under Win7

Looks like the above idea is right, it's failing over here:

![image](https://user-images.githubusercontent.com/765343/130319031-5dee7df7-2dc7-47a8-b9d5-4331c48aad82.png)

**Comment by greenozon** [comment]
My understanding of the issue is as follows:
SSHChoicePage is a Wizard Page
it is conditional object, I bet in majority of cases (those, who reported this bug)  it is equal to NIL. In my case 100% it is NIL.
Thus, we hit a so-called AV (AccessViolation) error because RdbSSH array is also NIL

here is proposed fix:  (ref to underlined added code)

![image](https://user-images.githubusercontent.com/765343/130335437-ce165fd3-324f-4cc3-b4a9-c11bf315da48.png)

With this addage setup finishes smoothly

**Comment by aicarambazigalo** [comment]
https://github.com/git-for-windows/build-extra/pull/374

**Comment by dscho** [comment]
> NIL

Excellent analysis!

@Okeanos thank you so much for implemeting and testing https://github.com/git-for-windows/build-extra/pull/374!

**Comment by mohamadsheam** [comment]
I have turned back to git version 2.32.0.windows.2

**Comment by dscho** [comment]
> 
> 
> I have turned back to git version 2.32.0.windows.2

Please note that this comment does not really add anything to value to the discussion.

What _would_ add value is if you had built an installer and verified the fix yourself.

As it happens, I intend to merge an existing PR (or to find a nice and easy change I can open a PR for) so that a new [snapshot](https://wingit.blob.core.windows.net/files/index.html) can be built that y'all are respectfully asked to test.

It will probably be a good idea to release a new Git for Windows version, _after_ I get a couple more reactions that verify the fix.

**Comment by greenozon** [comment]
@dscho where is the latest build with the fix?
I just tried the one from your snapshot link x64 installer (Tue, 17 Aug 2021 00:17:32 +0200
(commit fb59c1de9fd599a3eeb8459eb7cab731c6672ea3)

but it has the same error as reported in this issue thread...

**Comment by dscho** [comment]
> where is the latest build with the fix?

I do not have any as of yet. I started a `git-artifacts` workflow run [here](https://github.com/git-for-windows/git/actions/runs/1158833518), which should produce the installers, but they are not code-signed by me (unlike the snapshots would be).

> I've seen that v2.33.0 milestone is closed, so should we xpected a 2.33.1 or event 2.34?

The v2.33.0 milestone is closed because that version has been released ;-)

I am thinking about releasing a v2.33.0(2) soon-ish, including this fix.

**Comment by dscho** [comment]
Okay, there is now a current [snapshot](https://wingit.blob.core.windows.net/files/index.html) _with_ this fix.

**Comment by PetSerAl** [comment]
> Okay, there is now a current [snapshot](https://wingit.blob.core.windows.net/files/index.html) _with_ this fix.

This one fix issue for me.

**Comment by mohamadsheam** [comment]
> > I have turned back to git version 2.32.0.windows.2
> 
> Please note that this comment does not really add anything to value to the discussion.
> 
> What _would_ add value is if you had built an installer and verified the fix yourself.
> 
> As it happens, I intend to merge an existing PR (or to find a nice and easy change I can open a PR for) so that a new [snapshot](https://wingit.blob.core.windows.net/files/index.html) can be built that y'all are respectfully asked to test.
> 
> It will probably be a good idea to release a new Git for Windows version, _after_ I get a couple more reactions that verify the fix.

Agreed.

**Comment by greenozon** [comment]
Confirming - fixed installer (x64) worked like a charm!

![image](https://user-images.githubusercontent.com/765343/130482258-01aac6db-ba0e-469b-aec5-9b9aa902b9ae.png)

**Comment by aicarambazigalo** [comment]
Confirmed working now: installed over the existing one without errors(i've noticed this did the auto removed prev. version), then I manually uninstalled it and installed it again w/o errors(Windows Explorer Integration was selected, if it matters, and use OpenSSH library).

used the aforementioned snapshot "Mon, 23 Aug 2021 16:47:37 +0200
(commit 626897c0eab7a84b497e87c8bf6abb910e3e6b90)

    Git for Windows installer: 64-bit"
`61e6a032a6339d4915eaf96c75544528e49fe5ea05835629b8aade527b703375 *Git-prerelease-2.33.0.windows.1-2-g626897c0ea-20210823145343-64-bit.exe`

I thank everyone involved for your work and time!

**Comment by dscho** [comment]
All of you who worked on thorough bug reports, on the analysis and finally on the fix of this bug, and on verifying the fix: you are amazing. Thank you so much!

It is a bit too late in the day for me to start the release process, and besides, I want to make sure first that there might not be an upstream v2.33.1 lurking around the corner. My current plan, therefore, is to first make sure I get a feel about the upstream situation, and then go ahead and release v2.33.0(2). Hopefully tomorrow, definitely this week, I promise 😄...

**Comment by Okeanos** [comment]
Thank you as well from my side to the reporters, in particular @PetSerAl, for pointing out what broke during my pull request and enabling me to offer a fix so quickly. Also a mea culpa for not testing the changes on an expected configuration (Windows pre Win32 OpenSSH) that could've prevented this ordeal.

**Comment by dscho** [comment]
@Okeanos for the record: I do not see anything "tua culpa" about this. It was a really good contribution, a bug snuck in that nobody noticed, not even during -rc0, -rc1 _and_ -rc2, then it was identified and fixed efficiently. I could not wish for any better. Experiences like this one let me keep going, with gratitude.

My sincere thanks go to you, to @greenozon, @rimrul, @PetSerAl, and everybody who jumped on verifying the analysis and the fix!

Here is the outcome of your lovely effort: https://github.com/git-for-windows/git/releases/tag/v2.33.0.windows.2

**Comment by jeremyd2019** [comment]
This was apparently also what I was seeing on Windows 10 ARM64, as the "Could not call proc" error is gone there too with 2.33.0(2)

**Comment by mtymoshenko-CLGX** [comment]
Having same issue on Windows Server 2016 with v.2.33.0: https://superuser.com/questions/1670609/git-for-windows-unattended-installation-issue

**Comment by MartinLeuthold** [comment]
I had the same issue. We install it with SCCM. We choose plink. The solution was to create the "HKEY_CURRENT_USER" "SOFTWARE\SimonTatham\PuTTY\Sessions\Default%20Settings\..." Keys for the system Account.
