### ISSUE TITLE
Cannot delete files/folders on Windows 11 when fsmonitor--daemon running.

### ISSUE THREAD

**Issue by thargy** [git-for-windows/git#3370]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-op

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.132]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Clean install of Windows 11

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

All the above

 - What commands did you run to trigger this issue?

Tried to delete files/folders in Windows Explorer and/or from command line

 - What did you expect to occur after running these commands?

Expected to be able to delete them

 - What actually happened instead?

Was told couldn't delete as files/folders were in use by another process.

### Workaround

Deleting the `.git` subfolder allowed deletion to occur.

**Comment by dscho** [comment]
FSMonitor does not access files or folders, as far as I understand, it only holds a handle on the top-level directory (and on the `.git` directory). @jeffhostetler please correct me if I am wrong.

If I am right, then the problem is more likely another process, maybe Defender, maybe an editor such as VS Code (which calls `git status` semi-frequently, which _would_ temporarily lock the files and folders).

**Comment by thargy** [comment]
> FSMonitor does not access files or folders, as far as I understand, it only holds a handle on the top-level directory (and on the `.git` directory). @jeffhostetler please correct me if I am wrong.
> 
> 
> 
> If I am right, then the problem is more likely another process, maybe Defender, maybe an editor such as VS Code (which calls `git status` semi-frequently, which _would_ temporarily lock the files and folders).

I killed VSCode and Defender when trying to figure out what was holding locks.  I only discovered it was `fsmonitor` when I opened up Resource Manager and searched for the handles.

**Comment by thargy** [comment]
OK, so some more diagnoses.  Here's a fully reproducible set of steps that seems to work pretty reliably.  I enter each command one at a time (rather than running a batch):

```bash
# Clone github repro (contains only README.md)
$ gh repo clone Code-Institute-Solutions/SampleREADME
Cloning into 'SampleREADME'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), 4.87 KiB | 4.87 MiB/s, done.

# Empty README.md
$ > SampleREADME/README.md

# Check status
$ git -C SampleREADME/ status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")

# Check log (checking status then log seems to reliably trigger locking)
$ git -C SampleREADME/ log
commit 982e3b0e0086ced89d9a643d9e4d9d0c6f938ec2 (HEAD -> master, origin/master, origin/HEAD)
Author: Matt Rudge <mrudge@gmail.com>
Date:   Mon May 11 15:55:31 2020 +0000

    docs: Initial README.md commit

# Wait until git.exe grabs handles
# Grab below screenshot

# Try to delete directory
$ rm -rf SampleREADME/
rm: cannot remove 'SampleREADME/': Device or resource busy

# Sometimes the handles will terminate on there own, after seconds or minutes, otherwise the following works

# Remove .git directory
$ rm -rf SampleREADME/.git

# Can now delete
$ rm -rf SampleREADME/

```

Here's the screenshot referenced above:
<img width="503" alt="fsmonitor-daemon lock" src="https://user-images.githubusercontent.com/1908506/129809705-6d5e1f57-a959-42a9-a960-e949fa2ed280.png">

As you can see, I never enter the directory directly in bash, or use `VSCode`.  Also, you can see that code is not running from the arrow on the Processes view (sorted alphabetically).  Most importantly `git.exe` holds all the handles, and mostly on `.git\fsmonitor--daemon.ipc`.

**Comment by jeffhostetler** [comment]
The fsmonitor-daemon process has a handle on the root of the working directory to receive notification events and it's CWD is set to that directory.  The CWD is a problem and is probably the reason you can't delete the directory.

There is code in there to detect if the .git directory is deleted and auto shutdown.  So there's a race there (since the recursive rmdir will delete the .git dir first and then the root directory) so sometimes the rmdir succeeds and sometimes not.

I'm have a todo item to have the daemon cd out of the root dir after it gets started up.  that should fix the problem.

**Comment by thargy** [comment]
Thanks, @jeffhostetler, hopefully, my repro-steps will help you test the scenario to see if it resolves the issue.  If you tag this issue when merged I'm happy to confirm it WFM too.

**Comment by mcardia** [comment]
I've tested as well, and I confirm that the bug was fixed.

The git process with fsmonitor--daemon no longer locks files, and it ends itself when the repository is deleted.

Thank you.
