### ISSUE TITLE
failed with Azure CLI command on gitforwindows

### ISSUE THREAD

**Issue by jacktong** [git-for-windows/git#3371]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** $ git --version --build-options
git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19043.1165] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** $ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** NO **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Bash
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ id=$(az keyvault show --name kv-manged --query "properties.privateEndpointConnections[?contains(id,'adf-maged')].id" --output tsv)
$ az keyvault private-endpoint-connection approve --id $id
```
 - What did you expect to occur after running these commands?

private endpoint should be approved.

 - What actually happened instead?
the variable id should be in the following value.
$ echo $id
/subscriptions/99a369d3-9fdd-4b3d-8f77-1855c4cb3484/resourceGroups/magedrs/providers/Microsoft.KeyVault/vaults/kv-manged/privateEndpointConnections/adf-maged.AzureKeyVault1-conn

However, I can see bash add "C:/Program Files/Git/" automatically in front of value above, which caused this problem happens.
------------------------------
$ az keyvault private-endpoint-connection approve --id $id --debug
cli.knack.cli: Command arguments: ['keyvault', 'private-endpoint-connection', 'approve', '--id', 'C:/Program Files/Git/subscriptions/99a369d3-9fdd-4b3d-8f77-1855c4cb3484/resourceGroups/magedrs/providers/Microsoft.KeyVault/vaults/kv-manged/privateEndpointConnections/adf-maged.AzureKeyVault1-conn', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
------------------------------

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by rimrul** [comment]
https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues

>If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so: 

>> `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc` 

>Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "`//usr/bin/bash.exe`".
