### ISSUE TITLE
Error when rebase branch handle #0: 0000000000000d50 (type 3, handle info (1) 0

### ISSUE THREAD

**Issue by cnmade** [git-for-windows/git#3373]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.33.0.windows.1
cpu: x86_64
built from commit: fb59c1de9fd599a3eeb8459eb7cab731c6672ea3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Error when rebase branch
```git.exe -c "credential.helper=C:/Program\ Files/SmartGit/lib/credentials.cmd" rebase myproject/dev  xxxx_yyyy_with_a_long_commit_msg
failed to restrict file handles (5)
handle #0: 0000000000000d50 (type 3, handle info (1) 0
handle #1: 0000000000000128 (type 3, handle info (1) 1
handle #2: 0000000000000124 (type 3, handle info (1) 1
This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new
```

**Comment by dscho** [comment]
> failed to restrict file handles (5)

This `5` means [`ERROR_ACCESS_DENIED`](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-).

Wasn't there any suggestion in the issue reporting template to describe in detail how the error was triggered?

**Comment by cnmade** [comment]
The directory is my code directory, i can read/write code into my disk.

Is it any disk failure ? 

I can not see any problem with my other app(Such vscode, and sublime) to edit files.

Just git throw this error message. 
What can i do ?

**Comment by cnmade** [comment]
![image](https://user-images.githubusercontent.com/278153/130028640-aef99748-4399-4c0d-b586-9e49fb20315b.png)
Looks like my disk is health.

**Comment by dscho** [comment]
>  What can i do ?

As I pointed out earlier, you need to describe how you got there. Not just report what Git said. Nobody has a chance to help you if you only report a symptom without describing how to reproduce it.

**Comment by cnmade** [comment]
Hello, I describe it before error message. 
```
git rebase master
```

**Comment by cnmade** [comment]
This issue not always occurs .It will show sometime.

**Comment by cnmade** [comment]
https://github.com/git-for-windows/git/search?q=failed+to+restrict+file+handles
I can see about 93 issue like me.

**Comment by rimrul** [comment]
>https://github.com/git-for-windows/git/search?q=failed+to+restrict+file+handles
I can see about 93 issue like me. 

And most of them are 2.16 and long fixed.

**Comment by rimrul** [comment]
>Hello, I describe it before error message. 
> git rebase master

That really doesn't help.

**Comment by dscho** [comment]
> This issue not always occurs .It will show sometime.

This is a problem when you are asking other people to help. Therefore, I would _strongly_ recommend that you work on turning that into a reliable recipe to reproduce the issue. Otherwise, there is little hope that _anybody_ can help you, except you yourself.

**Comment by cnmade** [comment]
I am not ask for help. Whether it works or not. 

```
This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new
```

These useless word can be remove safely. non sense.

**Comment by dscho** [comment]
No, you _did_ encounter a bug. The error message is not useless: there was an unexpected `ERROR_ACCESS_DENIED`, and the correct thing for Git for Windows was to suggest to report the bug.

However, you reported the error message.

That is a far cry from a bug report. We have a detailed template that was carefully crafted to help you write an excellent bug report that would then not only allow others to reproduce the issue, but also to fix it for you.

Instead of cutting corners by deleting over half of the template without addressing, the right thing would have been to put in the same effort as all the developers have who made Git into what it is today. You can still do that, it's not too late for that.
