### ISSUE TITLE
Request to include jq tool for json processing

### ISSUE THREAD

**Issue by aiafrasinei** [git-for-windows/git#3374]
Request to include the jq tool in the gitbash utilities.

jq is a lightweight and flexible command-line JSON processor.
https://github.com/stedolan/jq

This will be really useful to have by default.

Is this acceptable from project side ? i can do myself but first i need to figure out how those utilities arrive in the install.

**Comment by rimrul** [comment]
There has been previous discussion on bundling jq in #2124.

**Comment by dscho** [comment]
> lightweight

From https://github.com/stedolan/jq/releases/tag/jq-1.6:

<img width=75% src=https://user-images.githubusercontent.com/127790/130039741-b70cd036-1ff3-44f0-a59b-61fc35ba310e.png />

Adding over 3MB to the Git for Windows installer that has increased in size from [just under 30MB](https://github.com/git-for-windows/git/releases/tag/v2.5.0.windows.1) to [already almost 48MB](https://github.com/git-for-windows/git/releases/tag/v2.33.0.windows.1) is not something I find acceptable, certainly not when the added payload has nothing at all to do with Git.

**Comment by aiafrasinei** [comment]
Just to make you aware, there are valid use cases for gitbash outside of just git.
Like a replacement linux environment on windows.

So we have bash, gawk, sed, grep, perl and all other linux tools.
C:\Program Files\Git\usr\bin

So this will help the project, by adding just another useful tool.

There you go, a user point of view.

**Comment by rimrul** [comment]
>Just to make you aware, there are valid use cases for gitbash outside of just git.
Like a replacement linux environment on windows.

You mean entirely unintended and largely unsupported use cases? We're aware.

**Comment by aiafrasinei** [comment]
I rest my case.
gitbash is just awesome in this "unsupported" use case :)

**Comment by dscho** [comment]
> So we have bash, gawk, sed, grep, perl and all other linux tools.

We have `awk`, `grep` and Perl. They are all used by Git's own code.

We definitely do not have all other Linux tools.

**Comment by dscho** [comment]
>  gitbash is just awesome in this "unsupported" use case :)

If you truly think that they are not _really_ unsupported, you put a really big burden on my shoulders. Not sure whether you intended that, but you did.

**Comment by aiafrasinei** [comment]
open gitbash
cd "C:\Program Files\Git\usr\bin"

and run ls in the prompt, full of ports of linux programs

$ where dos2unix
C:\Program Files\Git\usr\bin\dos2unix.exe
$ where cat
C:\Program Files\Git\usr\bin\cat.exe
$ where ls
C:\Program Files\Git\usr\bin\ls.exe

etc

**Comment by dscho** [comment]
> [...] They are all used by Git's own code.

Still true of all the ones you mentioned.

> We definitely do not have all other Linux tools.

What about ImageMagick? GNU screen? Ghostscript?

We have almost the _bare minimum_ of Linux tools, enough to run Git's commands that are not yet ported to C, and very little more.

Also, I am not sure that the direction this discussion has taken is particularly productive. At this point, I find it more annoying than anything else, and definitely failing in convincing me to bundle `jq` or any other tool Git does not need to work properly.
