### ISSUE TITLE
Ctrl-C on rebase leaves behind a stale index.lock file

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#338]
It happens to me frequently that in the middle of a rebase I cancel it using Ctrl-C, and then it leaves a stale index.lock, which must be removed manually.

IIRC I had it with other operations as well, but I can't tell for sure.

**Comment by orgads** [comment]
Any news? This happens to me quite frequently...

**Comment by dscho** [comment]
> Any news? This happens to me quite frequently...

I guess I do not cancel rebases, so the bug does not affect me...

To be honest, I have no idea what is *really* going on. I know what *should* be going on: Inside MinTTY, an MSys2 Bash is running. From this Bash, you call a shell script, which is handled by the same Bash via forking a new MSys2 process. This process in turn wants to fork a new process for every external executable called by the script, e.g. `git.exe`. Now, `git.exe` is *not* an MSys2 process, so it has no idea about signal handling or other POSIX niceties. Therefore, a POSIX wrapper process is started that in turn runs `git.exe` and tries to handle signals for it, e.g. accepting a SIGTERM and killing the process.

And here is where things went wrong in my tests earlier this year: `git.exe` would be killed, *but none of its child processes*. One symptom of this behavior was that quitting the pager of `git log` would *not* stop the `git-log.exe` process at all.

To remedy this, I implemented [this patch series](https://github.com/git-for-windows/msys2-runtime/compare/63863a1f5a5ccfee904047ff0abf3eaf16385fc9%5E...63863a1f5a5ccfee904047ff0abf3eaf16385fc9%5E2) that makes sure that children of non-MSys2 processes are killed when a SIGTERM was received.

My *guess* is that we would need to do something different there, such as sending a different kind of "signal" via `TerminateProcess()` to give Git a chance to run [its signal handler](https://github.com/git-for-windows/git/blob/c6f19b078bf05643c4d50dd520280a80f19f0002/tempfile.c#L81-L86) to remove the temporary files.

Hopefully this provides you with enough information to go further.

**Comment by dscho** [comment]
To be clear: I have unfortunately no time to spend on this ticket in the foreseeable future.

**Comment by dscho** [comment]
@orgads would you have time to drive this issue a bit? I *think* that I know what is going on, but I am too short on time to investigate.

**Comment by sxlijin** [comment]
I can't reproduce it; am on Win7 x64:

```$ g --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```

**Comment by dscho** [comment]
@orgads this has been tough to fix, and it would not have happened without @whoisj's excellent guidance. The newest [snapshot](https://wingit.blob.core.windows.net/files/index.html) should fix this issue. Please test.

**Comment by orgads** [comment]
Looks good. Thanks!
