### ISSUE TITLE
git sdk question

### ISSUE THREAD

**Issue by greenozon** [git-for-windows/git#3381]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.33.0.windows.1
cpu: x86_64
built from commit: fb59c1de9fd599a3eeb8459eb7cab731c6672ea3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

```

I've installed git-sdk-installer-1.0.8-64.7z.exe  on my system
but when I run c:\git-sdk-64\git-bash.exe   it has some kind of issues:

```
Could not set path
Error: The parameter is incorrect.
Welcome to the Git for Windows SDK!

The common tasks are automated via the `sdk` function;
See `sdk help` for details.


$ sdk init git
fatal: cannot change to '/usr/src/git': No such file or directory

```
at the same time dir /usr/src/git exists (empty)
What am I missing here...

**Comment by dscho** [comment]
> Could not set path
> Error: The parameter is incorrect.

This most likely happens [when creating the shortcut](https://github.com/git-for-windows/build-extra/blob/f1854b8bb8e5e572658f5a626eb2525bf29cf5aa/git-extra/create-shortcut.c#L130) for the Git SDK Bash on your Desktop.

Try to call `sdk create-desktop-icon` and see if it says the same. If it does, call `set -x` and then call the `sdk` command again, to see with what parameters `create-shortcut.exe` is called. If the problem does not become obvious then, please do report back with more information.

**Comment by greenozon** [comment]
Thank you for reply!

I've executed the command you mentioned above, here is the output
I've a feeling that this issue is somehow related to backslaches in Windows.. but how

```
after executing  set -x:


$ sdk create-desktop-icon
+ sdk create-desktop-icon
+ case "$1" in
+ force=t
+ case "$1" in
+ shift
+ case "$1" in
+ break
+ case "$(uname -m)" in
++ uname -m
+ bitness=' 64-bit'
+ desktop_icon_path='Git SDK 64-bit.lnk'
++ create-shortcut.exe -n --desktop-shortcut /git-bash.exe 'Git SDK 64-bit.lnk'
++ sed -n 's/^destination: //p'
+ desktop_icon_path='C:\Users\user\Desktop\Git SDK 64-bit.lnk'
+ test -n t
+ create-shortcut.exe --icon-file /msys2.ico --work-dir / /git-bash.exe 'C:\Users\user\Desktop\Git SDK 64-bit.lnk'
Could not set path
Error: The parameter is incorrect.
++ __git_ps1
++ local exit=1
++ local pcmode=no
++ local detached=no
++ local 'ps1pc_start=\u@\h:\w '
++ local 'ps1pc_end=\$ '
++ local 'printf_format= (%s)'
++ case "$#" in
++ printf_format=' (%s)'
++ local ps1_expanded=yes
++ '[' -z '' ']'
++ '[' -z '4.4.23(1)-release' ']'
++ shopt -q promptvars
++ local repo_info rev_parse_exit_code
+++ git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree --short HEAD
++ repo_info='.git
false
false
true
30cb37718'
++ rev_parse_exit_code=0
++ '[' -z '.git
false
false
true
30cb37718' ']'
++ local short_sha=
++ '[' 0 = 0 ']'
++ short_sha=30cb37718
++ repo_info='.git
false
false
true'
++ local inside_worktree=true
++ repo_info='.git
false
false'
++ local bare_repo=false
++ repo_info='.git
false'
++ local inside_gitdir=false
++ local g=.git
++ '[' true = true ']'
++ '[' -n '' ']'
++ local sparse=
++ '[' -z '' ']'
++ '[' -z '' ']'
+++ git config --bool core.sparseCheckout
++ '[' '' = true ']'
++ local r=
++ local b=
++ local step=
++ local total=
++ '[' -d .git/rebase-merge ']'
++ '[' -d .git/rebase-apply ']'
++ '[' -f .git/MERGE_HEAD ']'
++ __git_sequencer_status
++ local todo
++ test -f .git/CHERRY_PICK_HEAD
++ test -f .git/REVERT_HEAD
++ __git_eread .git/sequencer/todo todo
++ test -r .git/sequencer/todo
++ return 1
++ '[' -f .git/BISECT_LOG ']'
++ '[' -n '' ']'
++ '[' -h .git/HEAD ']'
++ local head=
++ __git_eread .git/HEAD head
++ test -r .git/HEAD
++ IFS='
'
++ read head
++ b=refs/heads/main
++ '[' 'ref: refs/heads/main' = refs/heads/main ']'
++ '[' -n '' ']'
++ local w=
++ local i=
++ local s=
++ local u=
++ local h=
++ local c=
++ local p=
++ '[' true = false ']'
++ '[' true = true ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ local 'z= '
++ '[' -n '' ']'
++ b=main
++ '[' no = yes ']'
++ local f=
++ local gitstring=main
++ '[' no = yes ']'
++ printf -- ' (%s)' main
++ return 1

```

**Comment by dscho** [comment]
> + create-shortcut.exe --icon-file /msys2.ico --work-dir / /git-bash.exe 'C:\Users\user\Desktop\Git SDK 64-bit.lnk'

Question is: what does `cygpath -aw /` say, i.e. where was your SDK installed?

**Comment by greenozon** [comment]
it says the following:

```
$ cygpath -aw /
+ cygpath -aw /
C:\git-sdk-64
++ __git_ps1
++ local exit=0
++ local pcmode=no
++ local detached=no
++ local 'ps1pc_start=\u@\h:\w '
++ local 'ps1pc_end=\$ '
++ local 'printf_format= (%s)'
++ case "$#" in
++ printf_format=' (%s)'
++ local ps1_expanded=yes
++ '[' -z '' ']'
++ '[' -z '4.4.23(1)-release' ']'
++ shopt -q promptvars
++ local repo_info rev_parse_exit_code
+++ git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree --short HEAD
++ repo_info='.git
false
false
true
30cb37718'
++ rev_parse_exit_code=0
++ '[' -z '.git
false
false
true
30cb37718' ']'
++ local short_sha=
++ '[' 0 = 0 ']'
++ short_sha=30cb37718
++ repo_info='.git
false
false
true'
++ local inside_worktree=true
++ repo_info='.git
false
false'
++ local bare_repo=false
++ repo_info='.git
false'
++ local inside_gitdir=false
++ local g=.git
++ '[' true = true ']'
++ '[' -n '' ']'
++ local sparse=
++ '[' -z '' ']'
++ '[' -z '' ']'
+++ git config --bool core.sparseCheckout
++ '[' '' = true ']'
++ local r=
++ local b=
++ local step=
++ local total=
++ '[' -d .git/rebase-merge ']'
++ '[' -d .git/rebase-apply ']'
++ '[' -f .git/MERGE_HEAD ']'
++ __git_sequencer_status
++ local todo
++ test -f .git/CHERRY_PICK_HEAD
++ test -f .git/REVERT_HEAD
++ __git_eread .git/sequencer/todo todo
++ test -r .git/sequencer/todo
++ return 1
++ '[' -f .git/BISECT_LOG ']'
++ '[' -n '' ']'
++ '[' -h .git/HEAD ']'
++ local head=
++ __git_eread .git/HEAD head
++ test -r .git/HEAD
++ IFS='
'
++ read head
++ b=refs/heads/main
++ '[' 'ref: refs/heads/main' = refs/heads/main ']'
++ '[' -n '' ']'
++ local w=
++ local i=
++ local s=
++ local u=
++ local h=
++ local c=
++ local p=
++ '[' true = false ']'
++ '[' true = true ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ local 'z= '
++ '[' -n '' ']'
++ b=main
++ '[' no = yes ']'
++ local f=
++ local gitstring=main
++ '[' no = yes ']'
++ printf -- ' (%s)' main
++ return 0

```

**Comment by dscho** [comment]
> ```
> + cygpath -aw /
> C:\git-sdk-64
> ```

Hmm. That sounds legit. Looking back at [the code](https://github.com/git-for-windows/build-extra/blob/f1854b8bb8e5e572658f5a626eb2525bf29cf5aa/git-extra/create-shortcut.c#L130), it seems that the `/git-bash.exe` might be the problem. Does that file exist for you? And more importantly, can you run that executable?

**Comment by greenozon** [comment]
Yes, it definitely exists - 

![image](https://user-images.githubusercontent.com/765343/130452692-66bfd53f-cb2b-4f6c-8f0f-5b1ced4e9bc8.png)

BTW, which shell binary do you recommend to use?
I see plenty of choices... 6 options

all the commands I show above was executed inside git-bash.exe

**Comment by dscho** [comment]
> Yes, it definitely exists -

Hmm. Then I am out of ideas what the problem could be. FWIW when I call the same command (obviously adjusting for my user name), it succeeds!

So maybe, since this is not really a critical problem, you could simply create the `Git SDK 64-bit' shortcut on your Desktop manually? That would work around the problem.

If you want to investigate further, I think the only way would be for you to try to re-build `create-shortcut.exe` via:

```console
$ sdk cd git-extra
[... edit create-shortcut.c to provide a more detailed error message ...]
$ make create-shortcut.exe
```

I do not exactly remember off-hand whether COM requires a different way to obtain more information about errors than `GetLastError()`, though, so I cannot help you on that endeavor...

**Comment by greenozon** [comment]
Good point!
I"ll follow your idea and provide my findings in a little while then

**Comment by greenozon** [comment]
OK, update: 
added hres to printout, rebuilt the  create-shortcut binary, replaced

got this:

```
Error code: 0x80070057; arg: /git-bash.exe
Could not set path
Error: The parameter is incorrect.
```

**Comment by greenozon** [comment]
Heh,

here is the culprit!!!

ENV VAR 
```
MSYS_NO_PATHCONV=1
```

I dont remember why I needed it in the past, but gut feeling just told me silently - you've got some old crap :)

If you remove it or set to 0, things automagically strated to work!!!
eg:

```
Error code: 0x00000000; arg: C:/git-sdk-64/git-bash.exe
Welcome to the Git for Windows SDK!

The common tasks are automated via the `sdk` function;
See `sdk help` for details.

```

**Comment by dscho** [comment]
Nice! Well done analyzing this problem and finding the root cause.

The big question now is: what do we do with this knowledge. Do we complain in the welcome message if `MSYS_NO_PATHCONV` is set? It is prone to cause more problems than just creating the desktop item.

What do you think?

**Comment by greenozon** [comment]
Thanks for great support

well, my thinking is as follows - I've just grepped though the issues DB here, though opened and closed ones, there are dozens (!) of issues referring to this or simlar case, all about that naughty env var

I believe it deserve some print out banner with regards to this env var name!
if we have dozens of issues now, we'll have a magnitude more in the future...

You are absolutely right, creating a desktop link is just a drop in the ocean
Please add some banner about it at least in create-shortcut binary!

Feel free to close it, thanks once again

**Comment by dscho** [comment]
> there are dozens (!) of issues referring to this or simlar case, all about that naughty env var

Note that some are referring to that environment variable because it is sometimes _needed_ (which is the opposite problem of what you had).

> I believe it deserve some print out banner with regards to this env var name!

Feel free to do so. The place to edit is [here](https://github.com/git-for-windows/build-extra/blob/b9f3f9e23b96e3592b30db34a6dac0798d0f77fc/git-extra/git-sdk.sh#L47-L60). It is a shell script snippet that is shown when the Git SDK Bash starts up, and you'd need something like `test -z "$MSYS_NO_PATHCONV" || echo "..."`, test, then open a PR.

**Comment by greenozon** [comment]
Thanks for tip
Testing shows that in case var is present, enduser will be warned (and potentially will save tons of time)

![image](https://user-images.githubusercontent.com/765343/130600178-44956ef0-ae2d-41df-83ee-010d9f8f0398.png)

I've created PR

**Comment by veqryn** [comment]
I have also ran into this problem.  For me, it was caused by having `MSYS2_ARG_CONV_EXCL=*` set.  I had both `MSYS_NO_PATHCONV=1` and `MSYS2_ARG_CONV_EXCL=*` set because without them I can't seem to get any manual mount commands to work with the docker cli. Unsetting MSYS_NO_PATHCONV was not enough to fix the problem, I had to unset both.
But this also raises a question (@dscho) : why is a desktop shortcut getting created every time I start my mingw64 terminal?

**Comment by dscho** [comment]
The SDK is intended to help contributors contribute to Git for Windows. The shorcut is part of facilitating that.

You might have a different use case in mind, and might therefore not have any use for that shortcut. But that's not a use case I am willing to spend time supporting myself, you will have to work yourself on making this work for you.
