### ISSUE TITLE
Git 2.33.0 Runtime error 325:19181

### ISSUE THREAD

**Issue by mohamadsheam** [git-for-windows/git#3382]
# Can not install Git 2.33.0 64 bit
**PC Config**
![pc config](https://i.postimg.cc/B6gyJDK2/Screenshot-1.png)

### [download from here](https://github.com/git-for-windows/git/releases/download/v2.33.0.windows.1/Git-2.33.0-64-bit.exe)

![Error screenshot ](https://i.stack.imgur.com/1A8lp.png)

**Comment by PetSerAl** [comment]
Duplicate of #3368
