### ISSUE TITLE
Wildcards do not work with 'git am' outside of bash

### ISSUE THREAD

**Issue by admsteck** [git-for-windows/git#339]
I cannot get `git am` to work on more than one file at a time outside of bash.  I should be able to run `git am *.patch` to apply all the patch files in the directory.  However when I run it inside PowerShell or cmd.exe I get `C:\Program Files\Git\mingw64/libexec/git-core\git-am: line 200: *.patch: No such file or directory`.  It works if I specify each file individually, but not with the wildcard.

Windows 7 Enterprise 64 bit
version 2.5.0.windows.1 and 2.5.1.windows.1
running inside PowerShell with posh-git or in cmd.exe

Reproduction:
I have a repository which I simply copied and renamed the containing folder.  So now I have c:\repo1 and c:\repo2 which are identical.
1. Create a couple of commits in the first repository.
2. Create patches for the commits in the first repo.... in this example the last two commits.
`git format-patch HEAD~~`
3. Copy the two .patch files to the working directory of the other repo.
4. Try to apply the patches
`git am *.patch`
fails
`C:\Program Files\Git\mingw64/libexec/git-core\git-am: line 200: *.patch: No such file or directory`

Running the same commands in bash works, but not in PowerShell or cmd.exe.

**Comment by dscho** [comment]
> Running the same commands in bash works, but not in PowerShell or cmd.exe.

This is expected because neither PowerShell nor cmd.exe nor git.exe expand wildcards. Those examples you found were written with a shell in mind, and the shell expands wildcards (hence Git does not think it needs to).
