### ISSUE TITLE
No .bash_profile created automatically in Git for Windows 2.5.1

### ISSUE THREAD

**Issue by calle2010** [git-for-windows/git#341]
Hi,

I installed Git-2.5.1-64-bit.exe as update over my existing msysGit 1.9.5 installation.

I had only a .bashrc, but Git 2.5.1 does not create a .bash_profile automatically as intended by https://github.com/git-for-windows/build-extra/pull/71 

No file `/etc/profile.d/bash_profile.sh` was created:

```
$ ls -al /etc/profile.d/
total 20
drwxr-xr-x 1 christian.schaefer DIR+Group(513)    0 Sep  1 09:28 ./
drwxr-xr-x 1 christian.schaefer DIR+Group(513)    0 Sep  1 09:28 ../
-rw-r--r-- 1 christian.schaefer DIR+Group(513)  234 Aug  5 18:50 aliases.sh
-rw-r--r-- 1 christian.schaefer DIR+Group(513)   94 Aug  5 18:50 env.sh
-rw-r--r-- 1 christian.schaefer DIR+Group(513) 1045 Aug  5 18:50 git-prompt.sh
-rw-r--r-- 1 christian.schaefer DIR+Group(513)  822 Apr 26 10:32 lang.sh
-rw-r--r-- 1 christian.schaefer DIR+Group(513)  699 Jun 18 06:37 perlbin.csh
-rw-r--r-- 1 christian.schaefer DIR+Group(513)  668 Jun 18 06:37 perlbin.sh

$ git --version
git version 2.5.1.windows.1

$ ls ~/.bash* ~/.profile
ls: cannot access /c/Users/christian.schaefer/.profile: No such file or directory
/c/Users/christian.schaefer/.bash_history  /c/Users/christian.schaefer/.bashrc*
```

Next I try to manually uninstall and install Git 2.5.1 again to see if this file will be created.

**Comment by calle2010** [comment]
Manual uninstall done, verified that `C:\Program Files\Git` was completely removed.
New install (with conhost option, if that matters) done, but same result: File `/etc/profile.d/bash_profile.sh` is not created.

**Comment by calle2010** [comment]
references #191

**Comment by dscho** [comment]
D'oh. I forgot to package `git-extra`. Did that now, the next release will fix this bug.

**Comment by calle2010** [comment]
Thank you!
