### ISSUE TITLE
Uexpected evaluation of alias arguments

### ISSUE THREAD

**Issue by Yankes** [git-for-windows/git#3421]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1165]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config alias.y-echo '!f() { echo "$@"; }; f'
git y-echo '*'
```
 - What did you expect to occur after running these commands?

output:
```
*
```

 - What actually happened instead?
 
output:
```
file1 file2 file3 file4
```
same as running `echo *`
`*` get evaluated by console even when escaped on in initial command

Text should be passed verbatim to inner command.
This prevent use of globs like `**/file.txt` in arguments to alias commands as bash and git interpreted this differently.

**Comment by landstander668** [comment]
Can you give the [current release](https://github.com/git-for-windows/git/releases/tag/v2.33.0.windows.2) a try? Your test case works as expected for me under that version.

You can use Portable Git variant without disrupting the current installation, if needed.

**Comment by PhilipOakley** [comment]
Is this a case of double shell expansion. The initial `'*'` is likely passed OK, but then it maybe re-expanded in the alias itself.

**Comment by Yankes** [comment]
@landstander668 Indeed, after updating to new version this bug was fixed, now correctly handle arguments,
Thanks for checking it.
