### ISSUE TITLE
git clone error when the path ends with a dot

### ISSUE THREAD

**Issue by LautaroMoreira01** [git-for-windows/git#3428]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options


**git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19043.1237]
 **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

**Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**git clone https://github.com/LautaroMoreira01/tps_laboratorio_ii..git  **
```
 - What did you expect to occur after running these commands?

** clone the repo without errors**

 - What actually happened instead?

** fatal: could not create work tree dir 'tps_laboratorio_ii.': Invalid argument
 **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** https://github.com/LautaroMoreira01/tps_laboratorio_ii..git
![Screenshot 2021-09-16 114534](https://user-images.githubusercontent.com/52410384/133676437-4bc3382e-f936-45bd-ac5d-9d8ef9095e27.png)
 **

**Comment by derrickstolee** [comment]
You can use `git clone <url> <dir>` to specify a new name that is valid for the filesystem. For your example, you could run

```shell
git clone https://github.com/LautaroMoreira01/tps_laboratorio_ii..git tps_laboratorio_ii
```

And the repo will be created in `tps_laboratorio_ii`.
