### ISSUE TITLE
Can't push via ssh with 2.5.1 

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#343]
I can't push via ssh with git 2.5.1.  However I could with 2.5.0 and I verified that I can still push with 1.9.5 via SourceTree just fine.

If I try to push with 2.5.1 I see:

    Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

**Comment by kjeremy** [comment]
This also applies to fetch.  Reverting to 2.5.0 seems to fix it.

**Comment by dscho** [comment]
This looks as if your `HOME` setting got messed up somehow. Could you provide more hints as to your setup, please (as requested in our [guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines))?

**Comment by dscho** [comment]
Or at least you could state what `echo $HOME` says in Git Bash. I would need a little more feedback to try to resolve this problem...

**Comment by dscho** [comment]
Closing as the OP clearly has lost interest, or became mute, or both.
