### ISSUE TITLE
git-askpass error when cloning via SSH

### ISSUE THREAD

**Issue by joel-speedwell** [git-for-windows/git#3434]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1801]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone git@some.gitlab.com/blah.git
```
 - What did you expect to occur after running these commands?

Perform a clone and prompt me to enter my SSH key password.

 - What actually happened instead?

An error dialog was shown:
https://i.imgur.com/QMll9Nl.png

The error dialog has a title "Error!" and message "Usage: git askpass <prompt>"
I believe the error is caused by the git-askpass.exe being executed without a prompt argument?

I have uninstalled and reinstalled Git for Windows many times and can't seem to figure out how to solve this. Is some part of the Git for Windows code not passing the prompt argument to git-askpass.exe? Does anyone have any ideas for how to solve this? I remember I used to be prompted in the terminal itself to enter my password, and I would prefer being able to do that.

Thanks for any help you can provide.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I don't think the repository matters.

**Comment by rimrul** [comment]
I'm sorry, I missed that OpenSSH doesn't always pass a prompt to `git-askpass` and `git-askpass` should have a default prompt for that. I've created a PR to fix this.

**Comment by joel-speedwell** [comment]
Hi @rimrul thanks for the quick fix. I ended up figuring out the Git for Windows SDK, rebuilt `git-askpass.exe` from your branch and now it's working fine for me. Hopefully someone merges your PR soon. Cheers!
