### ISSUE TITLE
git log, git diff hangs when quitting

### ISSUE THREAD

**Issue by JohanM84** [git-for-windows/git#3438]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1237]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
I'm using git bash in the Windows terminal

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Windows Terminal Version: 1.10.2383.0

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log
git diff
git show HEAD
```
 - What did you expect to occur after running these commands?

I should be able to scroll up and down in the git log (or diff) using arrow keys or PgUp, PgDn, then quit using the 'q' key

 - What actually happened instead?

When I scroll and then press 'q', git bash hangs. It doesn't appear that any process spawned by the windows terminal has become unresponsive. I can close the git bash tab in and open other tabs. 

This works in other terminals, like PowerShell.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is not repo specific

**Comment by dscho** [comment]
> I should be able to scroll up and down in the git log (or diff) using arrow keys or PgUp, PgDn, then quit using the 'q' key

It works here..

> This is not repo specific

Can you create a new repository (`git init test3438` followed by `cd test3438` and a couple of `git commit --allow-empty -m test` in a row) and verify that your issue reproduces there, too?

**Comment by jamesjb** [comment]
This issue has also been intermittently affecting me using Windows terminal with any Git command that uses a pager. I am able reproduce it eventually by running `git log`, hitting space a few times, then `q` to exit `less`. Sometimes it takes quite a few tries to occur.

Running the pager externally using `git --no-pager log --color | less -r` seems to work around the issue.

**Comment by zeroxia** [comment]
I have this issue too.

I installed Git on a company laptop, without admin privilege, the install location is at `%LocalAppdata%\Programs\Git`.
Environment:
* Windows 10: version 21H1 OS Build 19043.1415
* git version 2.35.0.windows.1 64 bit (Git-2.35.0-64-bit.exe)

With git bash in MinTTY, no issues.

If I use Windows Terminal Preview, or cmd, hung would happen:

The following commands would hang, press 'q' is not working, Ctrl-C won't interrupt, Ctrl-Pause can interrupt
$ git branch  # Content fit in one screen
$ git log -1  # Content fit in one screen
$ git log -3  # although content not fit in one screen, but pressing 'q' still hang.

For a repo with long history, the following command won't hang, pressing 'q' can quit:
$ git log

With the cmd.exe console, after Ctrl-Pause to break, clicking the window "close" cross at top-right would hang a while and then window is closed.

`git config core.pager cat` would not hung, but of course you don't have a pager now...

Tried a former version (Git-2.32.0.2-64-bit.exe), the same.

I downloaded another standalone "less.exe" from: https://github.com/jftuga/less-Windows/releases, replaced the "/usr/bin/less.exe" from the git install, then most of the situations there is no hung. But this less seems unable to show Chinese characters (e.g. log messages containning Chinese)

**Comment by dscho** [comment]
Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html). It might "accidentally" fix the issue reported in this here ticket, too.

**Comment by zeroxia** [comment]
> 

No, this snapshot build does not fix the issue on my system.

Tested version: Git-prerelease-2.35.1.windows.2-4-gbfc55a2345-20220215094111-64-bit.exe

`git log -1`, `git branch` (with two branches output only), `git diff` all hung.

An interesting point: `git diff` does not hung for the first run ("first run" probably is after reboot). Does it relate to the fsmonitor?

When hung happens, CTRL+C can't break it, but CTRL+Pause can, however, the "git XXX" process is still seen in task manager.

**Comment by KevinHake** [comment]
I can repro what I think is the same issue 100% of the time with the following:
1. open git bash for windows (v 2.35.1.windows.2) to a git repo
2. `git log`
3. **resize the bash window** (seems to be any direction)
4. try to quit (`q`). Hangs in returning to the terminal prompt

**Comment by dscho** [comment]
> the "git XXX" process is still seen in task manager.

@zeroxia can you see the full command line (e.g. via `wmic process where 'CommandLine like "%git%"' get commandline` or something similar)?

Also, a new hunch: is maybe an environment variable `LESS` defined on your system (this is also a question for you, @KevinHake)?

**Comment by KevinHake** [comment]
@dscho, `env | grep -i less` shows nothing for me, and `which less` gives me `/usr/bin/less`
Also notable that straight up `less` doesn't give me this problem, it exits just fine whether I resize my window or not.

I'm starting to wonder if there's actually a bug in pager.c somewhere. The last commit ([f917f57](https://github.com/git-for-windows/git/commit/f917f57f40a22b64ab5354e99dbf32bb48d9fc0a) on Nov 24, 2021) even references an issue with crashing on exit. That commit is in this version, so the fact it's related to the problem we're seeing suggests it wasn't a perfect commit.
The first tag I see from before that commit is **v2.34.1.windows.1** - I've yet to test it and see if 2.34 gives me the same issue.

**Comment by KevinHake** [comment]
also noticing now, the original user reports an issue in v2.33, but the issue I'm describing starts in v2.35, so it's not identical (I've verified I don't have the issue in v2.33 or v2.34). Looks like I should be in https://github.com/git-for-windows/git/issues/3683

**Comment by zeroxia** [comment]
> > the "git XXX" process is still seen in task manager.
> 
> @zeroxia can you see the full command line (e.g. via `wmic process where 'CommandLine like "%git%"' get commandline` or something similar)?
> 
> Also, a new hunch: is maybe an environment variable `LESS` defined on your system (this is also a question for you, @KevinHake)?

As I allow git to be run system-wide (this is the default option offered durting installation).
The problem is observed in Windows Terminal with powershell, cmd.exe. etc. but not present if I launch the git-bundled "mintty".

I do have a `.bashrc` file located at `%UserProfile%`, in it I set: `export LESS=-girWMFX`.
I commented out this "export" line, the problem still persists. `git branch` would hang in cmd.exe or powershell in Windows Terminal.

Then I renamed the `.bashrc` to `bak.bashrc`. Then go back to cmd.exe, press CTRL-Break to kill the hung `git branch` command (CTRL-C won't work), and I run `git branch` again, curiously, for this time it did not hang. I immediately run this `git branch` again, it is still hung.

After several tests, I run this: `wmic process where 'CommandLine like "%git%"' get commandline`:

```
>wmic process where 'CommandLine like "%git%"' get commandline
CommandLine
git fsmonitor--daemon run --free-console --ipc-threads=8
git.exe branch
git.exe  branch
git  branch
git.exe  branch
git.exe branch
git.exe  branch
wmic  process where 'CommandLine like "%git%"' get commandline
```

![second "git branch" command did not hang](https://i.imgur.com/TT7LxGM.png)

**Comment by jessey-git** [comment]
I believe I'm running into the same problem... and have been for quite some time now. I routinely encounter hangs after running `git log` or `git diff` and they occur both with ConHost.exe as well as the new Windows Terminal. No "bash" shenanigans here.

It occurs **_very_** frequently if I resize the terminal window as stated above by others but there's some cases where it will hang even if not doing so.

Would a dump of less.exe or git.exe in this state be useful?

```
git version 2.39.0.windows.1
cpu: x86_64
built from commit: de9501c66f93785f7eaf10d02ef08d231eb11688
```

**Comment by dsullins** [comment]
I also sporadically run into issues of git's broken less.exe hanging. I usually use cmd.exe within ConEmu as my shell. For me it's been happening before less.exe outputs anything to the screen, which doesn't match the original description. I'm commenting here because it might be related, but let me know if I should file this as a separate issue instead.

I have a workaround that might help anyone with less.exe issues: I've downloaded less.exe built from here https://github.com/jftuga/less-Windows, I put it in my path, and I rename or delete the one git installs to `C:\Program Files\Git\usr\bin\less.exe`. Then git will find the not-broken less.exe installed on my machine and use that instead. I know the issue still isn't fixed, because every time I upgrade Git for Windows I forget to delete the new less.exe that gets installed and eventually I'll have a git command hang again.

I use Process Explorer to find which process is hanging. Rarely I've seen git's sh.exe hung as well. So it might be an msys bug, or maybe that's just a coincidence.
