### ISSUE TITLE
[MinGit] Need latest busybox for newer `wget` command which downloads from HTTPS 

### ISSUE THREAD

**Issue by tigerinus** [git-for-windows/git#3439]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1237]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Manually unzipped MinGit-2.33.0.2-busybox-64-bit.zip and updated PATH accordingly.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
~/AppData/Local/Programs/MinGit/etc $ cat package-versions.txt | grep busybox
mingw-w64-x86_64-busybox 1.28.0pre.16550.0b3cdd76c-1
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`busybox bash` + Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

` wget https://google.com`

 - What did you expect to occur after running these commands?

```
$ wget https://google.com
Connecting to google.com (172.217.165.14:443)
Connecting to www.google.com (172.217.165.4:443)
saving to 'index.html'
'index.html' saved
```
 - What actually happened instead?

```
$  wget https://google.com
wget: not an http or ftp url: https://google.com
```

### other commands works in newer `busybox` but not in current `busybox`

- `base64` does not support `-w0` for one-line encoding

**Comment by dscho** [comment]
It looks as if you want to download BusyBox-w32 manually from https://frippery.org/busybox/. The BusyBox-w32 version bundled in MinGit(BusyBox) is still an experimental version, and while I am occasionally working on updating to a newer BusyBox-w32 version, it is only a side project of mine, interrupted by many more pressing issues.

The primary issue with upgrading to a newer BusyBox version is that we would have to gain some confidence that its POSIX shell is able to run Git's scripted commands and test suite. I tried to do so, in https://github.com/dscho/git/commits/busybox, but did not have time to finish that project yet.

If your knowledge of C is good enough, you might want to consider helping the effort.
