### ISSUE TITLE
Uninstalling remove explorere.exe and cmd.exe icons from taskbar/start menu

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#344]
I have explorer pinned to the task bar in Windows 7.  When uninstalling git 2.5.1 it turned the icon from the typical explorer icon to the default windows icon.  I have cmd in my start menu recent's list and it did the same thing.

**Comment by kjeremy** [comment]
![windows-default-shortcut-icon](https://cloud.githubusercontent.com/assets/4325700/9612869/fbf387a0-50b5-11e5-97e8-6d86b9d922b8.png)

**Comment by dscho** [comment]
Did you pin Git Bash or Git CMD to the task bar? Please be generous in the information you provide with bug reports.

**Comment by kjeremy** [comment]
No. Git Bash and Git cmd are not pinned.

What other info would be useful?

**Comment by dscho** [comment]
> What other info would be useful?

All of it :stuck_out_tongue_winking_eye:

**Comment by dscho** [comment]
Okay, I tested with 2.5.0, 2.5.1 and 2.5.2(2), both 64-bit, on a Windows 7 (64-bit) box. While I can see the usual flicker of the icons during uninstall if I look really closely, they flick right back to the correct icons. This demonstrates that unfortunately:

> I have explorer pinned to the task bar in Windows 7.  When uninstalling git 2.5.1 it turned the icon from the typical explorer icon to the default windows icon.  I have cmd in my start menu recent's list and it did the same thing.

is not precise enough a description to allow me to reproduce despite my having ~~wasted~~ spent more than 10x as much time on reproducing than it could have taken to write that bug description.

Please be more considerate of other people's time next time you report a bug. Be precise, verbose, and complete. And of course follow [our guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) (I will not tire to point you to this document...).

**Comment by kjeremy** [comment]
I finally figured this one out so am leaving it here for the next person.

This had nothing to do with git for windows.  My `PATH` environment variable was too large.  Cutting it down to a reasonable size fixed this.

**Comment by dscho** [comment]
Thanks for following up!
