### ISSUE TITLE
Changes sometimes not detected on file move leaving tree in partially broken state

### ISSUE THREAD

**Issue by evanunderscore** [git-for-windows/git#3441]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1237]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None, also replicated on second machine. I was unable to reproduce on Linux.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Replicated in Git Bash and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# Setup
git init mvtest
cd mvtest
echo a > a.txt
echo b > b.txt
git add .
git commit -m 'add files'

# Commands to trigger the bug (may need to paste as a block multiple times to trigger the bug)
git status
mv b.txt a.txt
git status
git checkout .
cat a.txt
cat b.txt
```
 - What did you expect to occur after running these commands?

Git should detect modification of `a.txt` and deletion of `b.txt`, both if which are undone by `git checkout .`.

```
$ git status
On branch master
nothing to commit, working tree clean

$ mv b.txt a.txt

$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   a.txt
        deleted:    b.txt

no changes added to commit (use "git add" and/or "git commit -a")

$ git checkout .
Updated 2 paths from the index

$ cat a.txt
a

$ cat b.txt
b
```

 - What actually happened instead?

Sometimes the modification to `a.txt` is not detected; `git checkout .` does not reset the contents of `a.txt`, and `git status` shows no changes.

```
$ git status
On branch master
nothing to commit, working tree clean

$ mv b.txt a.txt

$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    b.txt

no changes added to commit (use "git add" and/or "git commit -a")

$ git checkout .
Updated 1 path from the index

$ cat a.txt
b

$ cat b.txt
b
```

Once you are in this broken state, you can `touch a.txt` to have the change actually be detected.

```
$ touch a.txt

$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   a.txt

no changes added to commit (use "git add" and/or "git commit -a")

$ git checkout .
Updated 1 path from the index

$ cat a.txt
a
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None

**Comment by evanunderscore** [comment]
Apologies, I've just noticed this is a duplicate of #2769. This provides the MVCE requested in [this comment](https://github.com/git-for-windows/git/issues/2769#issuecomment-671959831).

**Comment by dscho** [comment]
> this is a duplicate of #2769.

So let's close it?
