### ISSUE TITLE
CA file outdated 

### ISSUE THREAD

**Issue by ruben-herold** [git-for-windows/git#3450]
hi.

after installing git for windows I try to access my git via https with letsencrypt certificate.
I got: 

fatal: unable to access 'https://gitserver.test.de/repo': SSL certificate problem: certificate has expired

ssllabs confirmed that my certificate is valid. For me it looks like: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ is the problem.

after switching to schannel all workes fine. So please update the ca file

**Comment by PhilipOakley** [comment]
You forgot to search the closed issues (the issue search annoyingly provides the `is:open` condition; try deleting it ;-)

#3375 "Add the Let's Encrypt Root & Intermediate certificates to the installer" discussion is worth a review. I think It has the answer, though it's not my area.

HTH.

**Comment by rimrul** [comment]
Our certificate bundle includes the self-signed `ISRG Root X1`. And I can successfully connect to the letsencrypt X1 test server

```bash
openssl s_client -connect valid-isrgrootx1.letsencrypt.org:443
```

Is your server potentially configured to distribute the cross-signed `ISRG Root X1` as an intermediary?

**Comment by krilor** [comment]
Lets Encrypt will continue to serve the cross-signed chain as a default until Jan 11th ( https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html ). I see that users with DST Root X1 still in their ca bundle will have connectivity issues with connecting to services that use the default chain.

This is one of the reasons why it is removed from the ca-certificates packages ( https://ubuntu.com/security/notices/USN-5089-1 ).

I think it is wise to update the CA file in git-for-windows as well.

**Comment by rimrul** [comment]
Ok, taking a closer look at this, the changes to `ca-certificates` should be rather simple and I don't see much danger in blacklisting thr expired certificate. `mingw-w64-ca-certificates` has diverged a bit from the msys2 package and might need some work, though.

**Comment by rimrul** [comment]
> Lets Encrypt will continue to serve the cross-signed chain as a default until Jan 11th

That is January 11th **2021**, though.

**Comment by rimrul** [comment]
The `ca-certificates` change is a PR now: https://github.com/msys2/MSYS2-packages/pull/2653

The changes to `mingw-w64-ca-certificates` changes will follow after the msys2 team is happy with the PR.

**Comment by krilor** [comment]
> > Lets Encrypt will continue to serve the cross-signed chain as a default until Jan 11th
> 
> That is January 11th **2021**, though.

Oh, my bad. I guess I found a bad/old reference. I was observing DST in the chain and went out find a reason for why :) guess I found a wrong one. Sorry. This might be a better reference: https://community.letsencrypt.org/t/providing-a-longer-certificate-chain-by-default/148738

What I am observing is that users using git with https on the default Lets Encrypt chain are hitting ssl cert expiry errors. Seeing it on git-for-windows and on Ubuntu. On ubuntu it was solved by updating CA certificates to get rid of the DST root.

**Comment by krilor** [comment]
> The `ca-certificates` change is a PR now: [msys2/MSYS2-packages#2653](https://github.com/msys2/MSYS2-packages/pull/2653)
> 
> The changes to `mingw-w64-ca-certificates` changes will follow after the msys2 team is happy with the PR.

Thanks for the quick turnaround :)

**Comment by dscho** [comment]
> The changes to `mingw-w64-ca-certificates` changes will follow after the msys2 team is happy with the PR.

Seems it was merged 6h ago, and `ca-certificates` is listed on https://packages.msys2.org/queue as: "Ready for upload but waiting for dependencies"

**Comment by dscho** [comment]
@rimrul what's your plan regarding `mingw-w64-*`?

**Comment by rimrul** [comment]
Pulling it up to 20210119 and patching out DST X3, so that it's basically the same as `ca-certificates`.

**Comment by dscho** [comment]
> 
> 
> Pulling it up to 20210119 and patching out DST X3, so that it's basically the same as `ca-certificates`.

Thank you for your untiring efforts! It was a good feeling to know you'd be holding down the fort while I was away.

**Comment by rimrul** [comment]
And here's the PR for `mingw-w64-ca-certificates`: https://github.com/msys2/MINGW-packages/pull/9722

**Comment by rimrul** [comment]
> The last update [seems to be months ago](https://github.com/git-for-windows/git-sdk-32/commit/b8950fdedd9ced59fb6bcebeb70ae9bc72221feb#diff-25f39759b76f539c6a757b1cbec6e57996d269553150f7388c479c2b0c95ceb5), and that was a lot of packages at once.

And the reason is that that was the last and only time in 2021 any packages where uploaded to https://repo.msys2.org/msys/i686/.

I guess that means we'll have to keep track of all Msys2-Packages in the SDK in `please.sh`and our component monitoring

**Comment by dscho** [comment]
You know what? It occurred to me that we can set up a new GitHub workflow to specifically build and upload i686 packages, without trying to upgrade their definitions to the latest component version. That way, we could sync, say, `less/PKGBUILD` with MSYS2's version, ensure that it builds for i686, push and have Actions take care of the rest. How does that plan sound to you, @rimrul ?

**Comment by rimrul** [comment]
Yes, I don't think I'll add `asciidoc` to the list. It's neither a package we bundle nor a package that's all that relevant to building Git for Windows. It just happens to be at the top of the list, because `pacman -Q` lists packages in alphabetical order.

> I hope we can do with a more manual approach

I'm just thinking the semi-automatic approach can help us keep the package-maintenance burden reasonably low while also keeping the 32bit and 64bit releases as similar as possible, to prevent issues that only affect one version.

**Comment by dscho** [comment]
The newest [snapshot](https://wingit.blob.core.windows.net/files/index.html) has the fix.

**Comment by cforce** [comment]
Issue is still existent
>git --version
git version 2.36.0.windows.1

**Comment by rimrul** [comment]
> Issue is still existent
> 
> > git --version
> > git version 2.36.0.windows.1

No, DST X3 is not in the ca bundle for that version.
