### ISSUE TITLE
echo "\n" into file will be recognized as two letter not a lf or crlf

### ISSUE THREAD

**Issue by algorithmlover2016** [git-for-windows/git#3454]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git-2.33.0.2-64-bit
mintty 3.5.0(x86_64-pc-msys)[windows 19043]
```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon


 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
win10, 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1237]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

at the bash terminal, I run the command : echo "\n\n\n" > log.txt
 - What did you expect to occur after running these commands?

there are four blank lines in log.txt

 - What actually happened instead?
actually, log.txt is as follows:
\n\n\n

**Comment by algorithmlover2016** [comment]
The bash in git bash terminal, can not parse '\n' to LF(linux) correctly.

**Comment by rimrul** [comment]
This is working as intended. The `echo` command in question is the bash builtin `echo`. 

> echo [-neE] [arg …]
>
> Output the args, separated by spaces, terminated with a newline. The return status is 0 unless a write error occurs. If -n is specified, the trailing newline is suppressed. If the -e option is given, interpretation of the following backslash-escaped characters is enabled. 

https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html
