### ISSUE TITLE
Problem in install GIT 

### ISSUE THREAD

**Issue by hr250054** [git-for-windows/git#3461]
![image](https://user-images.githubusercontent.com/89356891/137094651-3551cae8-297f-486e-8f1c-dccbe9b13648.png)

Not able to install latest GIT .  WIN 10 64 bit . 

Would appreciate help .

thanks
hanan

**Comment by hr250054** [comment]
same error code . issue not solved .

**Comment by dscho** [comment]
> same error code . issue not solved .

Okay, then please provide substantially more information. You deleted the entire issue reporting template instead of spending much effort on it, which tempts me to respond in kind. Also, run the installer with the `/LOG` option and investigate whether there are any clues in the log.

**Comment by dscho** [comment]
> when i tried to do git --version not get nothing .

That is probably what you need to dig deeper into.
