### ISSUE TITLE
Git 2.33.1 breaks rsa/sha-1 negotiation over ssh

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#3468]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

The [release notes](https://www.openssh.com/txt/release-8.8) of openssh 8.8, which is shipped with this version, say:
> This release disables RSA signatures using the SHA-1 hash algorithm by default. This change has been made as the SHA-1 hash algorithm is cryptographically broken, and it is possible to create chosen-prefix hash collisions for <USD$50K [1]

Our (internal) Git servers still use this algorithm, so we can not connect to any of them with this version of Git. This is the default key that is created by Gerrit, even on version 3.4, which is the latest stable (it was replaced and then [reverted](https://bugs.chromium.org/p/gerrit/issues/detail?id=14676)).

If you consider this upgrade necessary, please at least postpone it for a major release.

**Comment by orgads** [comment]
> That is wrong, IMHO. Your example updates the **_client_** keys, while the incompatibility is with host keys on the **_server_** side. The workaround in ~/.ssh/config just allows those server-side host keys to be accepted.

At least on my machine, the host keys were Ok. Regenerating my client keys solved the issue for me.

**Comment by rimrul** [comment]
>That is wrong, IMHO. Your example updates the **_client_** keys, while the incompatibility is with host keys on the **_server_** side. The workaround in ~/.ssh/config just allows those server-side host keys to be accepted.

The issue isn't really an issue of either side, but an incompatibility between the two sides. 

* Updating the Server allows both sides to use RSA/SHA-256/512

* Changing to a different key type allows both both sides to switch to that encryption

* Re-enabling RSA/SHA1 allows both sides to communicate in the old deprecated way. 

All three are solutions, but the first two should be prefered for security reasons.

> %PROGRAMFILES%\Git\etc\ssh\ssh_config

That works, but will be overwriten when updating or reinstalling Git for Windows.

**Comment by Eddy555** [comment]
> > %PROGRAMFILES%\Git\etc\ssh\ssh_config
> 
> That works, but will be overwriten when updating or reinstalling Git for Windows.

Yeah, I'm just puzzling over this.....

**Comment by dscho** [comment]
>  it does work with `~/.ssh/config`

Excellent.

**Comment by fcharlie** [comment]
As far as I know, many code hosting platforms will use golang to develop their Git Over SSH server(Gitea, Gogs, Gitee, CODING, Ant Code, CodeUp .....). Because golang x/crypto does not support the HostKey algorithm of `rsa-sha2-256`/`rsa-sha2-512`, starting from OpenSSH 8.8, ssh-rsa It has been disabled. Users who originally used RSA HostKey need to manually set the permission RSA key, or replace the RSA key, and the code hosting platform also needs to add other types of keys.

see: [x/crypto/ssh: support RSA SHA-2 host key signatures](https://github.com/golang/go/issues/37278)

**Comment by heartacker** [comment]
```
Unable to negotiate with 172.28.165.** port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
any body can help me to

> @xiayitian1003您可能错过了解决方案：
> 
> ```
> Host old-host
>   HostkeyAlgorithms +ssh-rsa
>   PubkeyAcceptedAlgorithms
> ```

i add this to config file but this is not useful. some body help me please

**Comment by dscho** [comment]
> i add this to config file but this is not useful. some body help me please

@heartacker you need to adjust `old-host` to the actual name of the host you are trying to connect to.

**Comment by heartacker** [comment]
> > i add this to config file but this is not useful. some body help me please
> 
> @heartacker you need to adjust `old-host` to the actual name of the host you are trying to connect to.

yes i have change old-host to ip:
```
Host 172.28.165.105
	HostkeyAlgorithms +ssh-rsa
	PubkeyAcceptedAlgorithms
	
```

```output
$ git push
/c/Users/ATC6194/.ssh/config line 3: no argument after keyword "pubkeyacceptedalgorithms"
/c/Users/ATC6194/.ssh/config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by Eddy555** [comment]
You appear to be missing the +ssh-rsa on PubkeyAcceptedAlgorithms
`Host stash.company.org
  HostkeyAlgorithms +ssh-rsa
  PubkeyAcceptedAlgorithms +ssh-rsa`

**Comment by heartacker** [comment]
> You appear to be missing the +ssh-rsa on PubkeyAcceptedAlgorithms `Host stash.company.org HostkeyAlgorithms +ssh-rsa PubkeyAcceptedAlgorithms +ssh-rsa`

Thank, it Work

```
Host xxx.xxx.xx.xxx
	HostkeyAlgorithms +ssh-rsa
	PubkeyAcceptedAlgorithms +ssh-rsa
```

**Comment by catteneo** [comment]
The suggested change on the `~/.ssh/config` worked for ssh connection
But stopped working on VSCode while using Remote-SSH with the error
Got the error `Bad configuration option: pubkeyacceptedalgorithms`

**Comment by rimrul** [comment]
Looks like that vscode extension is using an old version of OpenSSH (pre 8.5). You can probably use the old deprecated name of that config option: `PubkeyAcceptedKeyTypes`.

**Comment by Th1983** [comment]
> * [x] Tôi không thể tìm thấy vấn đề [mở](https://github.com/git-for-windows/git/issues?q=is%3Aopen) hoặc [đóng](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) phù hợp với những gì tôi đang gặp
> 
> Các [ghi chú phát hành](https://www.openssh.com/txt/release-8.8) của openssh 8.8, được vận chuyển cùng với phiên bản này, nói:
> 
> > Bản phát hành này vô hiệu hóa chữ ký RSA bằng cách sử dụng thuật toán băm SHA-1 theo mặc định. Thay đổi này đã được thực hiện do thuật toán băm SHA-1 bị phá vỡ về mặt mật mã và có thể tạo ra các xung đột băm tiền tố đã chọn với giá <USD $ 50K [1]
> 
> Máy chủ Git (nội bộ) của chúng tôi vẫn sử dụng thuật toán này, vì vậy chúng tôi không thể kết nối với bất kỳ máy chủ nào trong số chúng bằng phiên bản Git này. Đây là khóa mặc định được tạo bởi Gerrit, ngay cả trên phiên bản 3.4, là phiên bản ổn định mới nhất (nó đã được thay thế và sau đó được [hoàn nguyên](https://bugs.chromium.org/p/gerrit/issues/detail?id=14676) ).
> 
> Nếu bạn cho rằng bản nâng cấp này là cần thiết, ít nhất hãy hoãn nó lại để có một bản phát hành chính.

Da vang ,xin cho em run moi nguoi nhe

**Comment by python-telegram** [comment]
[Git 2.33.1 breaks rsa/sha-1 negotiation over ssh](https://github.com/git-for-windows/git/issues/3468#)
#3468

**Comment by zrav** [comment]
@orgads FWIW, Gerrit 3.6 fixes this incompatibility.
