### ISSUE TITLE
V2.33.1: LFS broken with BitBucket server up to 7.16.0 

### ISSUE THREAD

**Issue by calle2010** [git-for-windows/git#3470]
Not actually an issue of Git for Windows, but an incompatibility of Git LFS 3.0.1 with Bitbucket Data Center/Server before release 7.16.1: https://community.atlassian.com/t5/Bitbucket-articles/Git-LFS-v3-0-1-includes-backwards-incompatible-changes-with/ba-p/1819819

I ran into this problem today. It doesn't happen with Git 2.33.0(2). 

Version 2.33.1 of Git for Windows updated Git LFS to 3.0.1. 

I'm not aware of a workaround, so we have to defer the Git upgrade until our BitBucket Server has been updated.

**Comment by calle2010** [comment]
Thanks for the hint, specifying ```.lfsconfig``` seems to fix it:

```
[lfs]
url=git@internal.company.com:project/repository.git
```

This works with BitBucket 7.14.1 and Git for Windows 2.33.1 and 2.32.0(2)

**Comment by Xfactor947** [comment]
t/t7108-reset-stdin.sh
