### ISSUE TITLE
Release 2.33.1 breaks opening visual code by git commit command

### ISSUE THREAD

**Issue by hansschuijff** [git-for-windows/git#3471]
After upgrading to version 2.33.1 I some git-commands didn't work any more on my win10 machine. 
The reason seem to be the spaces in the path to code.cmd.

I tried reinstalling first, but the problem persisted and now I have reinstalled the previous version 2.33.0(2) and the problem is solved. I didn't know how to solve it otherwise and am stuck for now with the prev version.

I could still open vscode using the code command, but when git normally opens the editor (for instance in "git commit --amend" or even just "git commit") the response was an error about the path. I don't know if there are other commands too that open code and are broken, but the commit didn't work anymore after this update..

For instance this was the response to "git commit --amend" in git version 2.33.1.

C:\Users\Hans\Local Sites\sandbox\app\public\wp-content\plugins\genesis-connect-sensei-lms>git commit --amend
hint: Waiting for your editor to close the file... 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
error: There was a problem with the editor '"C:\\Program Files\\Microsoft VS Code\\bin\\code.cmd" --wait'.
Please supply the message using either -m or -F option.

### Setup

 -  2.33.1  64-bit
 -  vscode version 1.61.0
 -  windows 10 64 bits

**Comment by dscho** [comment]
This seems to have been missed in https://github.com/git-for-windows/build-extra/pull/384. @segevfiner, help?

**Comment by rimrul** [comment]
> error: There was a problem with the editor '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'.

This does look like the path is combined correctly and then quoted correctly, but that quoting gets messed up along the way.

**Comment by segevfiner** [comment]
Weird... I haven't touched the quotes in the command after all. I will try and repro.

**Comment by segevfiner** [comment]
P.S. As a workaround you can overwrite you can change your `core.editor` setting after installing Git, just note that it will be overwritten on Git for Windows upgrades AFAIK.

**Comment by segevfiner** [comment]
@hansschuijff Your `.gitconfig` will help, strip any private data in it, of course.

**Comment by dscho** [comment]
> Your `.gitconfig` will help, strip any private data in it, of course.

That would apply if VS Code was installed user-wide. But it is installed system-wide, hence the `core.editor` configuration goes into `C:\Program Files\Git\etc\gitconfig`.

**Comment by dscho** [comment]
@hansschuijff could you start Git Bash as Administrator (e.g. hitting the Windows key, typing "Git Bash" and then pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd>), then call `code /etc/gitconfig`, delete the `.cmd` suffix in the `core.editor` setting, save, and try whether that works?

**Comment by segevfiner** [comment]
Something is messed up with `git config` perhaps, doing `git config --global core.editor '"C:\Users\Segev\With Spaces\foo.cmd" --wait'` (From PowerShell BTW, cause escaping rules might matter here). Causes it to **add another** `core.editor` setting with `C:\Users\Segev\With`.

**Comment by dscho** [comment]
> @segevfiner how about including the information I provided in the commit message, and opening a PR?

Oh, I see, there is already https://github.com/git-for-windows/build-extra/pull/385... 😄
