### ISSUE TITLE
 docker-compose cli output broken in Git-Bash

### ISSUE THREAD

**Issue by fkluthe** [git-for-windows/git#3475]
Hey,

i opened an issue on Docker/docker-compose a while ago: https://github.com/docker/compose/issues/8180

Apperently it will not be fixed by Docker. Is there anything to fix/workaround this issue form git-for-windows side?

**Comment by rimrul** [comment]
Have you tried `winpty docker-compose`?

**Comment by dscho** [comment]
This issue is listed specifically in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]
