### ISSUE TITLE
Git-2.5.1-64-bit crashes windows 8.1

### ISSUE THREAD

**Issue by birdy247** [git-for-windows/git#348]
When I open git bash on my windows 8.1. machine (i7, 32Gig ram).  WIndows instantly goes to a blue screen with a unexpected kernel mode trap error.  Then shuts down.

**Comment by shiftkey** [comment]
Could you see what the [BSOD message] contains? http://www.nirsoft.net/utils/blue_screen_view.html

**Comment by dscho** [comment]
@birdy247 I agree with @shiftkey: could you please try to provide as much information about this as possible? E.g. what else did you try, does Git CMD work, for example, if you tell the installer to use the conhost-based terminal emulator instead, does that work, does Git GUI work?

**Comment by birdy247** [comment]
Hi, sorry for the late reply!

I will install the above application and see what I get. Post it here.

GIT CMD worked as did GIT GUI.

I tried both 32 and 64 bit.  I also uninstalled and re-installed a few times.  In the end, I tried an older version 1.9.x just to make sure it wasn't my PC.  This works fine.  Feel free to ask me to help test anything else.

Thanks

**Comment by birdy247** [comment]
==================================================
Dump File         : 090215-40093-01.dmp
Crash Time        : 02/09/2015 09:41:21
Bug Check String  : UNEXPECTED_KERNEL_MODE_TRAP
Bug Check Code    : 0x0000007f
Parameter 1       : 00000000`00000008
Parameter 2       : ffffd001`99a08230
Parameter 3       : ffffd000`22693000
Parameter 4       : fffff800`82dd95d7
Caused By Driver  : ntoskrnl.exe
Caused By Address : ntoskrnl.exe+14f9a0
File Description  : 
Product Name      : 
Company           : 
File Version      : 
Processor         : x64
Crash Address     : ntoskrnl.exe+14f9a0
Stack Address 1   : 
Stack Address 2   : 
Stack Address 3   : 
Computer Name     : 
Full Path         : C:\Windows\Minidump\090215-40093-01.dmp
Processors Count  : 8
Major Version     : 15
Minor Version     : 9600
Dump File Size    : 286,536
Dump File Time    : 02/09/2015 09:43:24
==================================================

**Comment by dscho** [comment]
From the article at https://msdn.microsoft.com/en-us/library/windows/hardware/ff559244(v=vs.85).aspx it appears that this is a div-by-zero that somehow could not be caught. Could you follow the hints in the *Resolution* section on that page and see e.g. whether the [`!analyze`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff562112(v=vs.85).aspx) command helps to figure out what is going on?

**Comment by eezhal92** [comment]
Same problem here, when I open Git 2.5.1, i got blue screen with UNEXPECTED_KERNEL_MODE_TRAP error message.

**Comment by dscho** [comment]
@eezhal92 I would appreciate more than a "me-too" message if you could follow that *Resolution* section as [I indicited earlier](https://github.com/git-for-windows/git/issues/348#issuecomment-137359116).

**Comment by birdy247** [comment]
dscho thanks.  Really keen to help out as much as possible with this.  I have been trying to understand !analyze but not really sure how I should use it and where.  Have you any experience with this?

**Comment by dscho** [comment]
@birdy247 I have no experience with this, but the description in https://msdn.microsoft.com/en-us/library/windows/hardware/ff559244%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396 seems clear enough to me. The first sentence on the *Resolution* section reads:

```
Debugging: Always begin with the [!analyze](https://msdn.microsoft.com/en-us/library/windows/hardware/ff562112%28v=vs.85%29.aspx) extension.
```

It contains a link: https://msdn.microsoft.com/en-us/library/windows/hardware/ff562112%28v=vs.85%29.aspx. This link suggests that the `!analyze` extension is part of WinDbg, I believe.

In case that WinDbg is too cumbersome to use, you could also follow the shot in the dark that your memory might be bad (which some reports of that same error message suggest). You should be able to verify that using http://memtest86.com/.

**Comment by shiftkey** [comment]
> Debugging: Always begin with the `!analyze` extension.

Yep, this is the easiest way to get started with analyzing the crash dump.

**Comment by dscho** [comment]
Sooo... any progress on this front?

**Comment by dscho** [comment]
@birdy247 @eezhal92 any progress?

**Comment by dscho** [comment]
ping.

**Comment by whoisj** [comment]
`!analyze` and `.kb` are probably the most useful windbg commands available.

That said, no user-mode application should be causing a kernel panic. Period.

This is likely not the fault of Git-for-Windows but a symptom of another problem, either in Windows itself, or more likely, in a device driver on @birdy247 system.

A stack trace would go a long way towards helping us determine the source of the fault.

In my limited experience debugging Windows kernel-mode panics, anti-virus (usually Symantec but they were not the only culprits) would do something horrible and cause the OS to BSOD to protect itself.

@birdy247 do you have AV installed? If so, does excluding your Git repos from the AV resolve the issue? #things_to_think_about
