### ISSUE TITLE
Ship with git-flow

### ISSUE THREAD

**Issue by sschuberth** [git-for-windows/git#349]
This is a follow-up to https://github.com/msysgit/git/issues/125 (and https://github.com/msysgit/git/issues/243). As [people are still having issues installing git-flow on Windows](https://stackoverflow.com/questions/32355523/simple-method-for-installing-gitflow-windows), and the [official instructions still refer to msysgit](https://github.com/nvie/gitflow/wiki/Windows#msysgit), I think we should make it easier for people to use git-flow.

This is even more true now that we have 32- and 64-bit versions of Git for Windows 2.x, and git-flow requires the `getopt.exe`, `libintl3.dll` and `libiconv2.dll` binaries to be installed. There is a risk that users might pick the wrong bitness for these.

Also, I do not think the "git-flow does not come with Git on other platforms either, so it doesn't make sense to me to bundle it with Git for Windows" [argument](https://github.com/msysgit/git/issues/243#issuecomment-54532252) is a good one. Just because other Git distributions are less convenient is not an excuse for us to not do a better job. After all git-flow is lightweight, so it should not add too much to the installer.

**Comment by dscho** [comment]
Please open a Pull Request with a commit message that details this rationale, what was tested to ensure that it works correctly, and the size delta of the installer. Thank you.

**Comment by dscho** [comment]
I close this ticket, looking forward to a Pull Request.

**Comment by sschuberth** [comment]
I don't intend to work on closed issues, just open ones. [The PR is supposed to close the issue](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by dscho** [comment]
Please work on it, then.

**Comment by dscho** [comment]
(For example, you should assign yourself if you want to work on it, giving other people -- myself included -- some sort of indication that you do want to work on it, and that this ticket is not going stale.)

**Comment by sschuberth** [comment]
I'll work on it when and if I have the time. I'll not assign it to myself until I'm confident that I'll be able to complete the task in reasonable time (because unlike you, I have to work on this in my free time, and I'm not getting paid for it). Until then the issue should stay open and unassigned, so it's free to pick for interested contributors.

**Comment by dscho** [comment]
Sorry, I disagree. You should be honest and straight-forward whether you intend to address this ticket (and assign it to yourself) or you should state clearly that you do not intend to do so, and then let others do with that ticket what they deem appropriate.

**Comment by sschuberth** [comment]
I truthfully said that I'm *planning* to work on this issue. There's nothing dishonest about still not assigning it to myself if I haven't started yet, and if I cannot *promise* to address it soonish. So please stop indirectly calling my a liar, that is unendurable.

**Comment by linquize** [comment]
The main point is to ship the necessary dependencies, such as `getopt.exe`, `libintl3.dll` and `libiconv2.dll`.

**Comment by dscho** [comment]
> The main point is to ship the necessary dependencies, such as getopt.exe, libintl3.dll and libiconv2.dll.

@linquize That would be the main point if nothing had changed from msysgit. I challenge you to look at the output of `ldd $(which getopt.exe)` and then guess what made me say that.

**Comment by hameno** [comment]
Why are you shipping a development version of gitflow-avh? 2.6.3 ships 1.9.0-dev.59 (AVH Edition), and it seems there is a bug which prevents deleting the remote branch after feature finish. Could you please switch to a stable release version?

**Comment by dscho** [comment]
@hameno first of all: you are welcome for all the hard work that makes your using Git possible.

> Could you please switch to a stable release version?

How about doing something about this yourself? It is easy: https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages

**Comment by hameno** [comment]
@dscho Wow, you are really rude. I made a separate ticket for it #536

**Comment by rimrul** [comment]
>@hameno first of all: you are welcome for all the hard work that makes your using Git possible.

>>Could you please switch to a stable release version?

>How about doing something about this yourself? It is easy: https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages

Basically there are 7 steps:
* Download and install the [Git for Windows SDK](https://github.com/git-for-windows/build-extra/releases)
* Fork the [MSYS2-Packages Repo](https://github.com/Alexpux/MSYS2-packages/)
* Edit the [git-flow PKGBUILD](https://github.com/Alexpux/MSYS2-packages/blob/master/git-flow/PKGBUILD) to use the master branch
* [Rebuild the Package](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages)
* Test the Package
* Repeat the previous three steps as nescessary
* Submit a nice Pull Request

**Comment by hameno** [comment]
@rimrul Thanks, but not everyone has the time to submit pull requests, I just noticed this and thought you would appreciate the info...

**Comment by rimrul** [comment]
>@rimrul Thanks, but not everyone has the time to submit pull requests, I just noticed this and thought you would appreciate the info...

I fully understand being short on time, but others are short on time, too. We appreciate the info and will posssibly do the switch to stable versions, but due to said shortage in time it might take a while.

> @dscho Wow, you are really rude. I made a separate ticket for it #536

He just tends to interprete issues that have a short text, start with "Why are you" and/or show little effort (due to watever potentially legitimate reasons) to solve the issue as "Do this for me. Now. And don't expect a 'thank you'.". This combined with currently very little time and a bunch of duplicate tickets can result in a bit of a harsh tone, but  you haven't met the kernel team yet. Creating a separate ticket seems like the right way to me. Resurecting a closed issue , that's been closed for three months is not usually good. Linking it as related is fine though.
