### ISSUE TITLE
git-bash.exe from 2.5.1 release detected as malware

### ISSUE THREAD

**Issue by chrullrich** [git-for-windows/git#350]
According to VirusTotal, seven engines detect git-bash.exe (SHA256: 38cbe1bd8bc81318c657205daea4db1f0bd15079411340d788012a6a9e72b272) as "Gen:Trojan.Heur.FU.bKW@aWV@U2kG".

False positive, no doubt.

**Comment by dscho** [comment]
Yeah, I guess. However, this is still disconcerting. Maybe we have to sign *all* executables... That would add quite a bit to the installer size, though, and also would impact the performance no doubt (what with all the signatures needing to be verified). Hmm.

**Comment by dscho** [comment]
@chrullrich since you are a customer of VirusTotal, could you contact their support to verify their claims? I am pretty certain that my development machine is virus free.

**Comment by chrullrich** [comment]
VirusTotal (https://www.virustotal.com/) is run by Google. It is a service that feeds submitted files to several dozen antivirus engines and reports their results, it is not a vendor itself, so there is no one to contact there. They tell me that "Ad-Aware", "Arcabit", "BitDefender", "Emsisoft", "F-Secure", "GData" and "MicroWorld-eScan" identify the sample as the thing I mentioned above ("Arcabit" has a slightly different name for it). See https://www.virustotal.com/en/file/38cbe1bd8bc81318c657205daea4db1f0bd15079411340d788012a6a9e72b272/analysis/ for the exact result.

I just sent the file to the vendor of the tool that I actually run, so they can fix their detection.

**Comment by dscho** [comment]
> I just sent the file to the vendor of the tool that I actually run, so they can fix their detection.

Thank you!

**Comment by chrullrich** [comment]
The response was "we do not currently detect that file, please update your signatures". Apparently my submission came just after a signature update that fixed the detection. According to VirusTotal, six of the seven engines that triggered on it before (the six where it had the same name) now give it a clean bill of health.

The two engines that still misidentify it are "Arcabit" (from Poland) and "Rising" (from China). If their user community overlaps with that of Git for Windows, someone will speak up. Until then, I think this immediate issue is solved.

**Comment by dscho** [comment]
Thanks!
