### ISSUE TITLE
Unwanted files in home directory

### ISSUE THREAD

**Issue by sryze** [git-for-windows/git#3503]
Git for Windows keeps creating a file in my home directory:

```
C:\Users\username\.git-for-windows-updater
```

Firstly, on Windows it does not make sense to name files like this (beginning with a `.`). Secondly, the file should not be put in the home directory - Git for Windows should use the AppData directory for storing configuration. For example, `C:\Users\username\AppData\Roaming\Git\git-for-windows-updater.ini`.

**Comment by rimrul** [comment]
The code that does that is [here](https://github.com/git-for-windows/build-extra/blob/main/git-extra/git-update-git-for-windows#L136-L147), Feel free to submit a convincing pull request.

**Comment by sryze** [comment]
OK, thanks. Here is the pull request: https://github.com/git-for-windows/build-extra/pull/387
