### ISSUE TITLE
[MinGit 2.33.1] less.exe missing when using git diff

### ISSUE THREAD

**Issue by WolfgangAndreas** [git-for-windows/git#3516]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-Bit

```
$ git --version --build-options

git version 2.33.1.windows.1
cpu: x86_64
built from commit: 05d80adb775077d673fab685009ede4a1003ed92
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Win10_64

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1288]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults (portable)

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

N/R
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/R

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

(USING MINGIT HERE)

$ git diff
error: cannot spawn less: No such file or directory

```
 - What did you expect to occur after running these commands?

A diff between the working dir and last commit is displayed.

 - What actually happened instead?

nothing. it seems, that less.exe could not be found.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

local repository

**Comment by dscho** [comment]
> ```console
> $ git diff
> error: cannot spawn less: No such file or directory
> ```

That's using `git diff` interactively, which is not supported by MinGit. You will need the Portable Git or a full Git for Windows installation for that.
