### ISSUE TITLE
Git-bash v2.5.1-64-bit can't launch ipython

### ISSUE THREAD

**Issue by sergeychipiga** [git-for-windows/git#352]
I seem, it forwards stdout somewhere.

**Comment by dscho** [comment]
This is a really short report, given that we ask explicitly for much more information in our [guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines). Nevertheless, it seems that the [known issues section of our release notes](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues) might shed light into the issue: you probably want to run Python through `winpty` or switch from `mintty` to the `ConHost`-based terminal.

**Comment by sergeychipiga** [comment]
Yep! You are right. I launched ipython via mintty without winpty. Now I fixed that. Thanks!
