### ISSUE TITLE
`git <command> --help` opens the browser

### ISSUE THREAD

**Issue by fekir** [git-for-windows/git#3527]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.1.windows.1
cpu: x86_64
built from commit: 05d80adb775077d673fab685009ede4a1003ed92
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1082]
```

Windows 10 x64

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (also tested from cmd and powershell)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull --help && echo a
```
 - What did you expect to occur after running these commands?

Show the help in the terminal, and block execution until help is closed, then print `a`.

 - What actually happened instead?

Browser is opened with URI `file:///C:/Program%20Files/Git/mingw64/share/doc/git-doc/git-pull.html`, `a` is printed immediately afterwards, before the browser has been closed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Repository not needed

### Additional notes:

Other git version executed on Windows (Linux versions with wsl, wsl2, or windows executable provided by cygwin and msys2) all behave as expected (they do not open the browser).
git-for-windows is AFAIK the only version that open the browser.

I know that people might find the current behavior better than showing the help in the terminal, and some are surely accustomed to it.
But I could not even find a setting for controlling this behavior.

**Comment by rimrul** [comment]
>  - What did you expect to occur after running these commands?
> 
> Show the help in the terminal, and block execution until help is closed, then print `a`.
> 
>  - What actually happened instead?
> 
> Browser is opened with URI `file:///C:/Program%20Files/Git/mingw64/share/doc/git-doc/git-pull.html`, `a` is printed immediately afterwards, before the browser has been closed.

This is worrking as intended. Git for Windows does not ship the git manpages or a way to view manpages.

> ### Additional notes:
> 
> Other git version executed on Windows (Linux versions with wsl, wsl2, or windows executable provided by cygwin and msys2) all behave as expected (they do not open the browser).
> git-for-windows is AFAIK the only version that open the browser.

They all open the browser when configured to do so.

> I know that people might find the current behavior better than showing the help in the terminal, and some are surely accustomed to it.
> But I could not even find a setting for controlling this behavior.

The config option is `help.format`, but remember we don't include non-html formats or viewers for those formats.
