### ISSUE TITLE
Run script

### ISSUE THREAD

**Issue by CrackerakiUA** [git-for-windows/git#354]
Before latest updated(i guess before update from 1.x.x to 2.x.x) i could have a file "pull" without extension and inside for example "git pull origin master" and it was working normally. Now it's not working, i tried all options i could. If there somewhere i can download old version or somewhere where i can fix that problem?
Error i have is: "bash: pull: command not found"

**Comment by dscho** [comment]
This report is incomplete. At least I, for one, have truly troubles to make any sense of it.

You might want to follow our [guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) to come up with an easier-to-follow description what is going wrong, what you expect to happen instead, how to reproduce, etc etc.

**Comment by CrackerakiUA** [comment]
Well, what i expect is when i have file with name "pull" and inside it "git pull origin master", i expect that when i write on console "pull", it run "git pull origin master". It's clear enough.

**Comment by nalla** [comment]
Please post the exact content of your file `pull`.

**Comment by CrackerakiUA** [comment]
`git pull origin master`

**Comment by nalla** [comment]
try this instead:

```bash
#!/bin/dash
git pull origin master
```

**Comment by CrackerakiUA** [comment]
i have, same result

**Comment by nalla** [comment]
see updated comment.

**Comment by CrackerakiUA** [comment]
ok, let me try this, give me 4 minutes

**Comment by CrackerakiUA** [comment]
same result :(
let me show you how it was working before: 
![screenshot 2015-09-07 18 02 43](https://cloud.githubusercontent.com/assets/6815721/9719271/682ef92a-558b-11e5-94ea-19cf2f90943b.png)

**Comment by nalla** [comment]
Well.. then I cannot reproduce.. this works for me:

```bash
$ printf '#!/bin/bash\necho "test"' > test
$ ./test
test
```

**Comment by CrackerakiUA** [comment]
ok, i figure it out, i was wrote wrong the first line. But still, can i somehow remove the `./` and make it like it was before?

**Comment by nalla** [comment]
```
$ abc
bash: abc: command not found
$ printf '#!/bin/bash\necho "test"' > ~/bin/abc
$ abc
test
```
works for me

**Comment by CrackerakiUA** [comment]
Great, thanks
