### ISSUE TITLE
Updating git changes explicitly set global "core.editor" value.

### ISSUE THREAD

**Issue by technicalviking** [git-for-windows/git#3543]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.34.0.windows.1
cpu: x86_64
built from commit: 7dad2af5e8ae15d5f1e1ce1980d1d873b9e00cb5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1348]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD (as administrator)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I chose to update git by clicking the desktop notification that shows up near the systray
```
 - What did you expect to occur after running these commands?

values I set via `git config --global ...` should remain what I set them to after an update.  Specifically, 
I use `git config --global core.editor "vim"` 

 - What actually happened instead?

the value for `core.editor` changed to visual studio code.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
>     * What did you expect to occur after running these commands?
> 
> 
> values I set via `git config --global ...` should remain what I set them to after an update. Specifically, I use `git config --global core.editor "vim"`

But you asked the installer (probably in an earlier round) for another editor:

> Editor Option: VisualStudioCode

You can fix this by reinstalling the version explicitly, which lets you click through the option pages. On one of the pages, you can specify your current editor preference.
