### ISSUE TITLE
Incorrect German translation for "'%s' is aliased to '%s'"

### ISSUE THREAD

**Issue by jottkaerr** [git-for-windows/git#3548]
https://github.com/git-for-windows/git/blob/7dad2af5e8ae15d5f1e1ce1980d1d873b9e00cb5/po/de.po#L16983-L16986
The German translation for "'%s' is aliased to '%s'" is incorrect. It switches the order of alias name and alias definition.

A better translation would be "'%s' ist ein Alias für '%s'". (Full stop removed intentionally, because the original does not use one either.)

**Comment by dscho** [comment]
I think this is incorrect (full disclosure: I am a native German speaker, and relatively fluent in English).

"A is aliased to B" means that B is an alias for A. But "A ist ein Alias für B" would say that A is an alias for B.

Therefore, the current version has the correct order, and your suggested translation has it backwards.

**Comment by dscho** [comment]
Actually, now that I looked at the code that uses the original string, I am somewhat confused: "A is aliased to B" is apparently not trying to say what I understood:

https://github.com/git/git/blob/cd3e606211bb1cf8bc57f7d76bab98cc17a150bc/builtin/help.c#L551

and

https://github.com/git/git/blob/cd3e606211bb1cf8bc57f7d76bab98cc17a150bc/builtin/help.c#L562

Clearly, `cmd` was an alias and `alias` is not actually the alias, but what it resolves to.

Which means that I was incorrect, and you were correct. However, this is not a Windows-specific issue. It is a translation issue in Git itself, and according to https://github.com/git/git/blob/v2.34.0/po/README.md, contributions to the translations should be submitted in the form of a Pull Request, see https://github.com/git/git/blob/v2.34.0/po/README.md#contributing-to-an-existing-translation for details.

The correct [repository to target](https://github.com/git/git/blob/v2.34.0/po/TEAMS#L13-L17) would appear to be https://github.com/ruester/git-po-de.

**Comment by jottkaerr** [comment]
Thanks for the direction to https://github.com/ruester/git-po-de. I will open an issue over there.

**Comment by dscho** [comment]
> 
> 
> https://github.com/ruester/git-po-de. I will open an issue over there.

Why not a Pull Request?

**Comment by jottkaerr** [comment]
PR created just now. (I had some problems pushing to my fork of https://github.com/ruester/git-po-de.)

**Comment by dscho** [comment]
Here it is: https://github.com/ruester/git-po-de/pull/18. Thank you for contributing!

**Comment by jottkaerr** [comment]
Gern geschehen. :-)
