### ISSUE TITLE
Issue on unzip cmd in windows

### ISSUE THREAD

**Issue by symeonmattes** [git-for-windows/git#3549]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1348]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

I have a peculiar behaviour on unzipping through git bash in Windows 10. The result is that for some files "a.exe" is considerered the same as "a". However in some other cases this is not the case. The command I execute is:

unzip -l -qq myzip.zip | awk '{print $4}'

mydir/
mydir/glassfish4/
mydir/glassfish4/mq/
mydir/glassfish4/mq/bin/
mydir/glassfish4/mq/bin/imqbridgemgr.exe
mydir/glassfish4/mq/bin/imqadmin
mydir/glassfish4/mq/bin/imqbridgemgr
mydir/glassfish4/mq/bin/imqadmin.exe
if I do the following:

  unzip myzip.zip
    
  creating: mydir/
  creating: mydir/glassfish4/
  creating: mydir/glassfish4/mq/
  creating: mydir/glassfish4/mq/bin/
  inflating: mydir/glassfish4/mq/bin/imqbridgemgr.exe
  inflating: mydir/glassfish4/mq/bin/imqadmin
  replace mydir/glassfish4/mq/bin/imqbridgemgr? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: mydir/glassfish4/mq/bin/imqbridgemgr
  inflating: mydir/glassfish4/mq/bin/imqadmin.exe
As you notice because "imqadmin" is before "imqadmin.exe" there is no issue. But for "imqbridgemgr.exe" which is before "imqbridgemgr" there is.


```
 - What did you expect to occur after running these commands?

To unzip fully the folder

 - What actually happened instead?

conflict on names

In linux I don't have such a weird behaviour. The same if I unzip it from GUI in windows.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

nothing

**Comment by dscho** [comment]
I _think_ this is a feature of MSYS2 (or even Cygwin). It pretends that `imqbridgemgr.exe` really is `imqbridgemgr` because when you call the latter, it does resolve to the former. I've definitely run into that before, and did not find any workaround.

_clicketyclick_

Turns out that this was configurable, via the `CYGWIN=notransparent_exe` setting, but that was removed in cygwin/cygwin@9bf7c7e96cf97fb10054775cfc84a92b4f45dea0. Now it is always on.

**Comment by dscho** [comment]
Since you are on a recent Windows version, you should be able to use PowerShell as a workaround:

```sh
powershell -command "Expand-Archive -LiteralPath \"$(cygpat -aw /path/to/zip)\" -DestinationPath ."
```

Seeing as this was an explicit decision by the Cygwin project to drop support for turning off the `transparent_exe` option, I do not really see how we could deviate from that in Git for Windows. Therefore I will close this ticket.
