### ISSUE TITLE
UAC elevation issue with upgrade 2.33.1 to 2.34.0

### ISSUE THREAD

**Issue by dbaileyut** [git-for-windows/git#3550]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

git version 2.33.1.windows.1
cpu: x86_64
built from commit: 05d80adb775077d673fab685009ede4a1003ed92
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10, 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1348]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Running as a non-admin user but installed machine wide

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

N/A but usually PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

With Git 2.33.1 previously installed to Program Files\Git. Running as non-admin
```

.\Git-2.34.0-64-bit.exe  "/LOG=gitupgrade.log"
```
 - What did you expect to occur after running these commands?

Setup wizard prompt for UAC elevation as a different user since the current install is \Program Files\Git, wizard upgrades Git successfully

 - What actually happened instead?

1. Wizard proceeds normally
2. UAC prompt occurs to uninstall from C:\Program Files\Git as expected
3. However the install of the new version fails to elevate (or use the previous elevation). 'Setup was unable to create the directory "C:\Program Files\Git\dev". 
  Error 5: Access Denied'
4. Left with Git mostly uninstalled except for "C:\Program Files\Git\etc\gitconfig"
5. Have to run the installer with Run As Administrator

See screenshots and log:

![UpgradeFail01](https://user-images.githubusercontent.com/7095040/142679884-24f4a29d-09b9-4b2d-a2d0-b6496dd21df3.png)
![UpgradeFail02](https://user-images.githubusercontent.com/7095040/142679872-788e1132-a273-4c43-8417-452c6ed0c4dc.png)
![UpgradeFail03](https://user-images.githubusercontent.com/7095040/142680775-56213054-390c-40b1-8735-3e3d368b0e6c.png)
![UpgradeFail04](https://user-images.githubusercontent.com/7095040/142679819-ea9fb795-bd58-4646-91fd-133910a99600.png)
![UpgradeFail05](https://user-images.githubusercontent.com/7095040/142679729-2f629e39-428a-4439-9945-28aa74af8133.png)

[gitupgrade.log](https://github.com/git-for-windows/git/files/7572508/gitupgrade.log)

**Comment by dscho** [comment]
I feel that this describes the problem, but does not lead us to a better understanding why this is happening:

> ```
> 2021-11-19 13:07:13.435   User privileges: None
> 2021-11-19 13:07:13.488   Administrative install mode: No
> ```

When I run it, I see this instead:

> ```
> 2021-11-19 21:30:25.075   User privileges: Administrative
> 2021-11-19 21:30:25.124   Administrative install mode: Yes
> ```

After an extensive web search, it would appear that our use of the [`PrivilegesRequired` directive](https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequired) is non-canonical. We use the value `none`, which is [apparently undocumented and does not elevate for non-admin users](https://stackoverflow.com/questions/21556853/make-inno-setup-installer-request-privileges-elevation-only-when-needed).

I guess we should switch this to `admin`?

**Comment by dbaileyut** [comment]
You got "User privileges: Administrative" while running the installer as a non-admin? 
i.e. Do you have to enter a different user that has administrator rights in the UAC prompt than the one you're logged into Windows interactively with?

With regard to Inno Setup, I'm not at all familiar with it. But I just came across [PrivilegesRequiredOverridesAllowed](https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequiredoverridesallowed). I think having that set to "dialog" with PrivilegesRequired "admin" is probably the way to go. I see a lot of setup wizards that have radio selection choices of something like "Install for all users" and "Install for only me" and that makes sense.

**Comment by dscho** [comment]
> You got "User privileges: Administrative" while running the installer as a non-admin?

No, my account isn't non-admin.

> I see a lot of setup wizards that have radio selection choices of something like "Install for all users" and "Install for only me" and that makes sense.

We specifically opted out of allowing that, I forgot the details why, but essentially it boiled down to problems if both system and user installations existed.

> I think having that set to "dialog" with PrivilegesRequired "admin" is probably the way to go.

Would you mind making that change in [`install.iss`](https://github.com/git-for-windows/build-extra/blob/HEAD/installer/install.iss), testing the heck out of it to ensure that it does what it is supposed to do (you will want to [download Git for Windows' SDK](https://gitforwindows.org/#download-sdk), and run `sdk build installer` in it), then open a PR?

**Comment by dbaileyut** [comment]
I tested using `PrivilegesRequired=admin`. It works for my use case but will break non-admin user installs because it forces the installer run as administrator no matter what.

Perhaps it's worth revisiting `PrivilegesRequiredOverridesAllowed`, combined with [UsePreviousPrivileges](https://jrsoftware.org/ishelp/index.php?topic=setup_usepreviousprivileges), and whatever scripting is required to mitigate side by side installs?

Also, I'm curious - what's stopping both system and user installs as it is today?

**Comment by dscho** [comment]
> Also, I'm curious - what's stopping both system and user installs as it is today?

As I mentioned earlier, I do not recall the details, but I do remember that we had too many problems with allowing user-wide installations that we switched to _only_ allowing system-wide installations.

One obvious problem is that Git-related applications are frequently looking into Git for Windows' system config. Which is in `C:\Program Files\Git\etc\gitconfig`. Allowing users to install Git for Windows into their AppData renders that assumption incorrect, after it was correct for most of Git for Windows' existence.

Having said that, if you want to experiment with allowing user-wide installations of Git for Windows, I am not all that opposed to review and merge a PullRequest.

**Comment by dbaileyut** [comment]
If the desired behavior is to disallow user-wide installs, `PrivilegesRequired=admin` is definitely the way to go and that works as I expect it to. I'll open a PR to use `admin`. 

>  we switched to only allowing system-wide installations

While I'm fine with requiring system-wide installs, FYI, that's not the actual behavior today with `PrivilegesRequired=none`.  See the screenshots below. I ran the uninstaller and deleted `%ProgramFiles%\Git`. `%LOCALAPPDATA%\Programs\Git` is the default install path as a non-admin and it installs there without error.

![Non-admin-install01](https://user-images.githubusercontent.com/7095040/142902018-0fc9fe1f-d62c-43bc-b469-245ed7f3c2f8.png)
![Non-admin-install02](https://user-images.githubusercontent.com/7095040/142902034-ef349f8d-91e0-4985-9b5f-a6909ac3163a.png)

**Comment by dscho** [comment]
> > we switched to only allowing system-wide installations
> 
> While I'm fine with requiring system-wide installs, FYI, that's not the actual behavior today with `PrivilegesRequired=none`.

After looking at git-for-windows/build-extra@23672af723da18e5bc3c679e52106de3c2dec55a, I fear I have to admit that I misremembered, and we tried to enforce system-wide installs _for users with admin privileges_. It is those who ran into troubles mixing system-wide with user-wide installations, I guess.

**Comment by DaleStan** [comment]
I am told that this issue is why the Git for Windows automatic updater has turned into an automatic uninstaller instead. I'm waiting for an explanation from Admin by Request on how exactly they manage to allow the uninstaller to elevate but then prevent the updater from elevating. In the meantime, is there anything I can do (e.g. investigation/configuration/logs) to help figure out what, if anything, needs to happen on the Git for Windows side of the problem?

**Comment by DaleStan** [comment]
I installed Git myself, and everything was working fine for years. (We migrated to Git five years ago.) The update popup appeared, I clicked Yes, Next (if applicable), and Install, and then Yes again on the UAC prompt.

A couple months ago, my IT department (reasonably enough) decided they needed more visibility into what people were running as admin, so they installed a tool called Admin By Request. I installed 2.36.0 while Admin By Request was in audit mode, and the only change I noticed from previous updates was that the UAC prompt appeared on the interactive desktop instead of the secure desktop.

Sometime last week, IT activated Admin By Request. When the 2.36.1 update came along, I did everything as usual. Instead of a UAC prompt, I (as expected) saw a little notification that AbR had noticed the Git installer wanted to elevate, and had approved that for me. But then the error message appeared, and I discovered the Git installer had deleted the old files and errored out instead of installing the new files. I assumed AbR had broken something, but the AbR folks shrugged their shoulders, claimed it wasn't their fault, and pointed me to this issue.


I can preemptively elevate the installer to get it to work properly, but that isn't ideal, since there isn't a "Yes, and also preemptively elevate the installer" button on the update notification.

**Comment by dbaileyut** [comment]
@DevonMiller-tfo's description lines up with my experience.

> @dscho 
> The assumption of Git for Windows' installer is that it runs elevated

It shouldn't assume that but should prompt for elevation if it needs it.

I've worked around the issue by making my own scheduled task to check for updates and run them fully elevated but I don't think that should be deployed widely or anything.

I think the root of the problem is in Inno Setup and it needs to maintain its elevated process for the entire uninstall/install upgrade process of a system-wide install initiated from a non-admin user.

**Comment by dbaileyut** [comment]
> > the workaround is to set `PrivilegesRequired=admin`
> 
> This would definitely break the expectation of some users that they can install Git for Windows into their home directory in unelevated mode, though, correct?

Unfortunately, yes

**Comment by DevonMiller-tfo** [comment]
Looking at inno setup's docs, this is why the uninstall always works.
From: [https://jrsoftware.org/ishelp/index.php?topic=admininstallmode](https://jrsoftware.org/ishelp/index.php?topic=admininstallmode):

> If the installation is running in non administrative install mode, but administrative privileges are available anyway then Setup or the [Code] section might still make use of these privileges. For this reason **_the uninstaller will always be marked as requiring administrative privileges_** in this case, just as if the installation was running in administrative install mode.

**Comment by dscho** [comment]
That `PrivilegesRequired=admin` setting is interpreted while compiling the installer, not while running it.

**Comment by davaya** [comment]
> > > the workaround is to set `PrivilegesRequired=admin`
> > 
> > 
> > This would definitely break the expectation of some users that they can install Git for Windows into their home directory in unelevated mode, though, correct?
> 
> Unfortunately, yes

This is a major and unfortunate change that should be reversed.  According to https://github.com/git-lfs/git-lfs/issues/1964, git-2.11.1 is installable by users without admin.  However, Git-2.37.0-64-bit.exe raises the UAC login with no way to avoid or bypass it.

Addressing edge cases of admin users choosing to install locally by disenfranchising the normal case of users in a work or school environment with no admin rights seems shortsighted.  If not reversed, it at least warrants a big red-letter entry in the FAQ saying "Git For Windows can no longer be installed by non-admin users!".

Please reconsider.

**Comment by dscho** [comment]
I invite everybody in this thread to see what they can do over in https://github.com/jrsoftware/issrc (i.e. in InnoSetup). Some time ago, I did work on CI builds and have a way to test whatever patches you want me to test. Or you install Embarcadero yourself to compile it, up to you.

As the reported issue is not something Git for Windows can address without work on InnoSetup, I will close this ticket.
