### ISSUE TITLE
TLSv1.3 support when installing with Schannel

### ISSUE THREAD

**Issue by Galaxy0419** [git-for-windows/git#3558]
According to [this document](https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-), TLSv1.3 is supported in windows 11.  Is there any plans for TLSv1.3 support when installing with Schannel?  Currently, when I use curl with ```--tlsv1.3```, it shows ```curl: (35) Schannel: TLS 1.3 is not yet supported```,

**Comment by rimrul** [comment]
Probably. Seeing as the message says "not yet". But that seems like a question for the curl mailing list.

**Comment by rimrul** [comment]
Ok, I've had a closer look. That message was introduced with

https://github.com/curl/curl/commit/6448f98c1857de521fb2dd3f9d4e5659845b5474 in 2016, when schannel didn't support TLS 1.3 yet.

It's probably time for an update to the logic in `lib/vtls/winssl.c`. I think they'll appreciate a pull request.

**Comment by dscho** [comment]
https://github.com/curl/curl/issues?q=1.3 comes in handy. I think https://github.com/curl/curl/pull/7784 might lead to support landing at some stage.

**Comment by dscho** [comment]
That PR has not seen updates since Oct 5, though, and not only the commit history looks in dear need of some TLC, but also the [tests](https://cirrus-ci.com/task/4691265032814592?logs=test#L87), e.g.:

```
-------e--- OK (23  out of 1426, remaining: 07:00, took 0.093s, duration: 00:06)
test 0024...[HTTP GET fail silently on HTTP error return]
```

@Galaxy0419 if you have any expertise in C, or can gain it quickly enough, there is your chance to help.

**Comment by Galaxy0419** [comment]
There's a [new pr](https://github.com/curl/curl/pull/8419) implementing the feature, probably going to be merged soon.

**Comment by Galaxy0419** [comment]
Okay, the pr is now merged, looking forward to have it in the next release.

**Comment by dscho** [comment]
> Okay, the pr is now merged, looking forward to have it in the next release.

Is it in any official cURL version?

**Comment by rimrul** [comment]
Not yet, but it should be part of curl 7.85 on August 31st, so it should be in time for the next version of Git.

**Comment by Galaxy0419** [comment]
The feature is now included in [7.85.0](https://github.com/curl/curl/releases/tag/curl-7_85_0).

**Comment by dscho** [comment]
Yes, and the next [snapshot](https://wingit.blob.core.windows.net/files/index.html) will have it.

In the meantime, you can also try [the artifacts](https://github.com/git-for-windows/git-sdk-64/actions/runs/2983104512#artifacts) that are now continuously built by the freshly added `git-artifacts` workflow. The latest artifacts already come with the new cURL version.

**Comment by Galaxy0419** [comment]
Sure, just tested the version you linked:
- [x] TLSv1.3 is working, verified by: ```curl --tlsv1.3 'https://tls13.akamai.io/'```
- [x] Git is working, verified by clone a repository, rebase a branch and push it to the remote.

**Comment by dscho** [comment]
> just tested the version you linked:
> 
>     * [x]  TLSv1.3 is working, verified by: `curl --tlsv1.3 'https://tls13.akamai.io/'`
> 
>     * [x]  Git is working, verified by clone a repository, rebase a branch and push it to the remote.

Yes!
