### ISSUE TITLE
mingw_strftime: wrong calling convention

### ISSUE THREAD

**Issue by lazka** [git-for-windows/git#3560]
drive-by find when looking into https://github.com/msys2/MINGW-packages/issues/10152

Because strftime in msvcrt is bad git4windows tries to find strftime from ucrt if possible: https://github.com/git-for-windows/git/blob/7dad2af5e8ae15d5f1e1ce1980d1d873b9e00cb5/compat/mingw.c#L1217

which uses https://github.com/git-for-windows/git/blob/7dad2af5e8ae15d5f1e1ce1980d1d873b9e00cb5/compat/win32/lazyload.h#L28-L32

which uses `WINAPI` afaics, but strftime is `CDECL`.

cmake did the same thing which started to crash for us.

**Comment by rimrul** [comment]
Yes, we definitely missed that when I implented that feeature. I'll prepare a patch series and send it to the mailing list.
