### ISSUE TITLE
Cannot commit to network repo from root directory - libgit2 could not find repository from network path - includes workaround

### ISSUE THREAD

**Issue by glhey** [git-for-windows/git#3562]
What did you do before the bug happened? (Steps to reproduce your issue)
- from repo root, git commit to new repo in mapped network drive 

What did you expect to happen? (Expected behavior)
- files get committed
- ("git add ." did succeed)

What happened instead? (Actual behavior)
- libgit2 error "libgit2 returned: could not find repository from network path"

What's different between what you expected and what actually happened?
- failed to commit files

Anything else you want to add:

- workaround: create subfolder, move into subfolder, re-run git commit - SUCCESS see [https://gitlab.com/tortoisegit/tortoisegit/-/issues/2911](https://gitlab.com/tortoisegit/tortoisegit/-/issues/2911)
- once first commit succeeds, commit from root will succeed.

[System Info]
git version:
git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
uname: Windows 10.0 19043
compiler info: gnuc: 11.2
libc info: no libc information available
$SHELL (typically, interactive shell): C:\Program Files\Git\usr\bin\bash.exe

[Enabled Hooks]
~

**Comment by glhey** [comment]
Note - having incomplete or non-conforming global user info may be associated.

**Comment by rimrul** [comment]
> libgit2 error "libgit2 returned: could not find repository from network path"

This doesn't sound like a Git for Windows issue. Git for Windows doesn't use libgit2.

> commit to new repo in mapped network drive

What kind of network drive?

**Comment by glhey** [comment]
Using QNAP NAS. Possible an authorization problem, Will continue to explore and advise.
