### ISSUE TITLE
Failed processing /etc/vimrc when $VIMRUNTIME is set

### ISSUE THREAD

**Issue by eight04** [git-for-windows/git#3566]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19043.1348]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

[VIM on Windows](https://www.vim.org/download.php)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

    CMD. This happens when I launches cmd from VIM (the one I installed from vim.org, not the git editor), for example:
    
      * `:!start cmd` - which launches a new external CMD
      * `:term` - which starts the builtin terminal in VIM

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
   
Acutually, any command that opens the editor is broken, you can modify a file, stage it, and run `git commit` to open the editor.
   
```
echo foo > test.txt
git add .
git commit
```
 - What did you expect to occur after running these commands?

Open the editor so I can modify commit message.

 - What actually happened instead?

```
hint: Waiting for your editor to close the file...
--- Autocommands ---
Error detected while processing /etc/vimrc:
line   43:
E10: \ should be followed by /, ? or &
line   44:
E10: \ should be followed by /, ? or &
line   45:
E10: \ should be followed by /, ? or &
line   46:
E10: \ should be followed by /, ? or &
line   47:
E10: \ should be followed by /, ? or &
line   48:
E10: \ should be followed by /, ? or &
line   53:
E10: \ should be followed by /, ? or &
line   54:
E10: \ should be followed by /, ? or &
Press ENTER or type command to continue
```
After pressing ENTER, the editor is opened without syntax.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

All repos.

----

Currently, I wrote a plugin to strip those env variables before running CMD:
https://github.com/eight04/vim-start-cmd/blob/103ea39905998d64a30e7a88adef6230f334c6e0/plugin/start-cmd.vim#L4

**Comment by dscho** [comment]
> * Any other interesting things about your environment that might be related
>       to the issue you're seeing?
> 
> 
> [VIM on Windows](https://www.vim.org/download.php)

How is VIM _on Windows_ able to access the _Unix_ path `/etc/vimrc`? That file is for the MSYS2 `vim.exe` bundled in Git for Windows, and it should be read by any other VIM implementation. Could you trace/log how your copy of VIM gets to that file?

**Comment by rimrul** [comment]
Could you quickly test if `git -c core.editor="vim -N" commit` shows the same behaviour (without the plugin)?

**Comment by rimrul** [comment]
> > * Any other interesting things about your environment that might be related
> >       to the issue you're seeing?
> > 
> > 
> > [VIM on Windows](https://www.vim.org/download.php)
> 
> How is VIM _on Windows_ able to access the _Unix_ path `/etc/vimrc`?

No. They're executing `git` from within that `vim` and `git` calls the bundled `vim`. 
 And the bundled `vim` seems to go into `vi` compatibility mode for some reason, which causes it to fail parsing `/etc/vimrc`.

**Comment by eight04** [comment]
> How is VIM _on Windows_ able to access the _Unix_ path `/etc/vimrc`?

I guess that path refers to `"C:\Program Files\Git\etc\vimrc"`. Here is the content of that file:
<details>

```
" Setting some decent VIM settings for programming
" This source file comes from git-for-windows build-extra repository (git-extra/vimrc)

ru! defaults.vim                " Use Enhanced Vim defaults
set mouse=                      " Reset the mouse setting from defaults
aug vimStartup | au! | aug END  " Revert last positioned jump, as it is defined below
let g:skip_defaults_vim = 1     " Do not source defaults.vim again (after loading this system vimrc)

set ai                          " set auto-indenting on for programming
set showmatch                   " automatically show matching brackets. works like it does in bbedit.
set vb                          " turn on the "visual bell" - which is much quieter than the "audio blink"
set laststatus=2                " make the last line where the status is two lines deep so you can see status always
set showmode                    " show the current mode
set clipboard=unnamed           " set clipboard to unnamed to access the system clipboard under windows
set wildmode=list:longest,longest:full   " Better command line completion

" Show EOL type and last modified timestamp, right after the filename
" Set the statusline
set statusline=%f               " filename relative to current $PWD
set statusline+=%h              " help file flag
set statusline+=%m              " modified flag
set statusline+=%r              " readonly flag
set statusline+=\ [%{&ff}]      " Fileformat [unix]/[dos] etc...
set statusline+=\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})  " last modified timestamp
set statusline+=%=              " Rest: right align
set statusline+=%l,%c%V         " Position in buffer: linenumber, column, virtual column
set statusline+=\ %P            " Position in buffer: Percentage

if &term =~ 'xterm-256color'    " mintty identifies itself as xterm-compatible
  if &t_Co == 8
    set t_Co = 256              " Use at least 256 colors
  endif
  " set termguicolors           " Uncomment to allow truecolors on mintty
endif
"------------------------------------------------------------------------------
" Only do this part when compiled with support for autocommands.
if has("autocmd")
    " Set UTF-8 as the default encoding for commit messages
    autocmd BufReadPre COMMIT_EDITMSG,MERGE_MSG,git-rebase-todo setlocal fileencodings=utf-8

    " Remember the positions in files with some git-specific exceptions"
    autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$")
      \           && &filetype !~# 'commit\|gitrebase'
      \           && expand("%") !~ "ADD_EDIT.patch"
      \           && expand("%") !~ "addp-hunk-edit.diff" |
      \   exe "normal! g`\"" |
      \ endif

      autocmd BufNewFile,BufRead *.patch set filetype=diff

      autocmd Filetype diff
      \ highlight WhiteSpaceEOL ctermbg=red |
      \ match WhiteSpaceEOL /\(^+.*\)\@<=\s\+$/
endif " has("autocmd")

```
</details>

> Could you quickly test if `git -c core.editor="vim -N" commit` shows the same behaviour (without the plugin)?

I don't get the error message anymore but the editor is opened without syntax.
![image](https://user-images.githubusercontent.com/1324510/144404197-7141c724-e1e2-42d7-bf77-5057484caf2e.png)
Compare to CMD which is launched outside of VIM:
![image](https://user-images.githubusercontent.com/1324510/144404298-c8f5d9f7-737e-4db5-8cf0-4d22378d57fb.png)

**Comment by rimrul** [comment]
> I don't get the error message anymore but the editor is opened without syntax.

That unfortunately seems to be how `$VIMRUNTIME` is supposed to work. The `vim` developers didn't anticipate people running nested `vim` instances with different default runtime directories.

The inner `vim` gets told to look in the `$VIMRUNTIME` of the outer `vim` for it's syntax files and doesn't find files for `COMMIT_EDITMSG` there. `$VIMRUNTIME` doesn't add an additional search location, but replaces the default.

**Comment by rimrul** [comment]
I'll prepare a fix for the error messages and have a quick talk with the vim developers if they'd be willing to modify how `$VIMRUNTIME` behaves in this situation.

**Comment by rimrul** [comment]
Looking at this some more, our `/usr/share/vim/vim82/syntax/*.vim` files seem to come from vim/vim directly. So the Vim on Windows `$VIMRUNTIME` should contain more or less the same files. So the inner `vim` should pick up the outer `vim`s copy of `$VIMRUNTIME/syntax/gitcommit.vim`.

**Comment by chrisbra** [comment]
> So the inner vim should pick up the outer vims copy of $VIMRUNTIME/syntax/gitcommit.vim

It should, but I am not sure if the inner vim can read `c:\Program Files\vim\vim82\vimrc` (since that one expects unix paths)

Note: if you use vims terminal, you can check $VIM_TERMINAL to see if you are running from within vims terminal.

I am not sure what vim/vim can do against this specific use case however.

**Comment by rimrul** [comment]
> > So the inner vim should pick up the outer vims copy of $VIMRUNTIME/syntax/gitcommit.vim
> 
> It should, but I am not sure if the inner vim can read `c:\Program Files\vim\vim82\vimrc` (since that one expects unix paths)

MSYS path conversion should convert that to a unix path, so it should be fine.

**Comment by chrisbra** [comment]
BTW: I do not see this when explicitly using bash from Vims (8.2.3434) terminal. $VIMRUNTIME is not there and gits vim just starts fine. When running a cmd terminal, %VIMRUNTIME% is there, but again this doesn't seem to be a problem. BTW: you may want to use updated Windows builds from https://github.com/vim/vim-win32-installer/

**Comment by dscho** [comment]
Closing as stale.
