### ISSUE TITLE
Trailing slash being added to the end of remote URL when pushing

### ISSUE THREAD

**Issue by giulianisanches-inbev** [git-for-windows/git#3567]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [versão 10.0.19042.1110]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash and PowerShell (7.2)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# only a git push (git clone/pull works just fine)
$ git push
```
 - What did you expect to occur after running these commands?

My code being pushed to the remote repository

 - What actually happened instead?

A trailing slash is being added to the end of the URL that causes the repository URL to be invalid.

```
remote: Repository not found.
fatal: repository 'https://github.com/MyOrg/My_Repo.git/' not found
```

This happens only with https repositories and for this specific case, I can't use ssh to clone.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It's private repository, can't share the URL.

**Comment by dscho** [comment]
> * What commands did you run to trigger this issue? If you can provide a
>       [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
>       this will help us understand the issue.
> 
> 
> ```
> # only a git push (git clone/pull works just fine)
> $ git push
> ```

That is not a Verifiable example: it totally succeeds over here.

> * If the problem was occurring with a specific repository, can you provide the
>       URL to that repository to help us with testing?
> 
> 
> It's private repository, can't share the URL.

The best option you have now is to work on a reproducer that works with a public repository.

The alternative is to wait for a witch or a wizard with a crystal ball, as the information provided in this ticket is far too insufficient to even allow for an educated guess.

**Comment by mjcheetham** [comment]
> fatal: repository 'https://github.com/MyOrg/My_Repo.git/' not found

Can you try using a remote URL that does not end with `.git` at all? I know GitHub will do a redirect from `My_Repo` to `My_Repo.git` for you.. perhaps that might help with the extra trailing slash appearing?
