### ISSUE TITLE
Projects with branches with symbols '>', '<' in names can't work

### ISSUE THREAD

**Issue by altro3** [git-for-windows/git#3573]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1387]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

defaults
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What actually happened instead?

This is a rare case, but today I ran into a problem: my colleague in Linux created a branch called usd-> aed and after that this project could no longer be updated. The problem is that Windows cannot use symbols '>', '<' in file names. And the git could not create the lock file. Here is the error that was displayed to me:
```
15:53 Update failed
cannot lock ref 'refs / remotes / origin / usd-> aed': Unable to create 'project/.git/modules/module/refs/remotes/origin/ usd-> aed.lock ': Invalid argument
From <repo URL>
! [new branch] usd-> aed -> origin / usd-> aed (unable to update local ref)
```

**Comment by dscho** [comment]
`>` is not a legal filename character on Windows, and branches are currently represented as files, so this is unfortunately a known problem.

One work-around to fetch such refs is to fetch them into local refs whose names are legal filenames on Windows, e.g. `git fetch origin 'refs/heads/usd->aed:refs/heads/use2aed'`.

I am not currently aware of any other way to resolve this, therefore I suggest to take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

**Comment by altro3** [comment]
The problem is that I use the Intellij Idea and cannot customize the work with the git in IDE :-(

**Comment by dscho** [comment]
> The problem is that I use the Intellij Idea and cannot customize the work with the git in IDE :-(

You can always use the command-line Git to update your worktree.

**Comment by altro3** [comment]
Yes, of course. We in the team will no longer use special characters in branch names. I just wanted to report a problem. But, if this is a known problem and they are not going to fix it, then you can close this ticket

**Comment by dscho** [comment]
> if this is a known problem

This is a known problem

> and nobody going to fix it,

That is more a question for you, as well as for other users who have that problem. Git is Open Source, which means that it is exactly as good as its contributors (read: you) make it.

> then you can close this ticket

So can you ;-)
