### ISSUE TITLE
submodule set-branch/set-url doesn't format path separator

### ISSUE THREAD

**Issue by eight04** [git-for-windows/git#3575]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [版本 10.0.19043.1348]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

C:\Users\eight04\dev>md git-test

C:\Users\eight04\dev>cd git-test

C:\Users\eight04\dev\git-test>git init
Initialized empty Git repository in C:/Users/eight04/dev/git-test/.git/

C:\Users\eight04\dev\git-test>git submodule add -b master https://github.com/githubtraining/hellogitworld.git foo\bar
Cloning into 'C:/Users/eight04/dev/git-test/foo/bar'...
remote: Enumerating objects: 306, done.
Receiving objects:  54% (166/306)ed 0 (delta 0), pack-reused 306Receiving objects:  53% (163/306)
Receiving objects: 100% (306/306), 95.82 KiB | 1.29 MiB/s, done.
Resolving deltas: 100% (69/69), done.
warning: LF will be replaced by CRLF in .gitmodules.
The file will have its original line endings in your working directory

C:\Users\eight04\dev\git-test>git submodule set-branch -b master foo\bar

C:\Users\eight04\dev\git-test>git submodule set-url foo\bar https://github.com/githubtraining/hellogitworld.git

C:\Users\eight04\dev\git-test>type .gitmodules
[submodule "foo/bar"]
        path = foo/bar
        url = https://github.com/githubtraining/hellogitworld.git
        branch = master
[submodule "foo\\bar"]
        branch = master
        url = https://github.com/githubtraining/hellogitworld.git
```
 - What did you expect to occur after running these commands?

`set-url` and `set-branch` should probably convert `foo\bar` to `foo/bar` like `submodule add`.

 - What actually happened instead?

A new entry `foo\\bar` is added to `.gitmodules`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Since `git submodule` not only touches the worktree, but also the Git index, you need to use the correct directory separator in the first place: the forward slash.

The reason is that the Git index can very well contain filenames containing a backslash character, which is a totally legal (non-directory separator) character in filenames on, say, Unix.

It is the same thing as if you use `set-url` on the path `Foo/Bar` vs `foo/bar`: those two names refer to separate entities on Unix, and you need to use the correct filename spelling for Git to understand you.

**Comment by eight04** [comment]
Good to know. Though it feels a little awkward that they behaves differently.
![image](https://user-images.githubusercontent.com/1324510/144863398-80620ba6-2032-4d97-959e-3a75ef8d4f11.png)

**Comment by dscho** [comment]
> it feels a little awkward that they behaves differently.

Agreed.
