### ISSUE TITLE
Strange characters are shown in the terminal after `git config -e --global`

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#3579]
When using MSYS2 runtime v3.3.3 in a regular Git Bash, after `git config -e --global` launched `vim` and the editor was closed, seemingly random characters are "ghost-typed".

This _might_ be a "funny" interaction between the MSYS2 runtime, MinTTY and `vim`.

Concretely, I see 1R77;30502;0c10;rgb:bfbf/bfbf/bfbf11;rgb:0000/0000/0000 being "ghost-typed" every time Git has called vi for editing a file.

To be precise, the hexdump -C output is this:

```
00000000  1b 5b 32 3b 32 52 1b 5b  33 3b 31 52 1b 5b 3e 37  |.[2;2R.[3;1R.[>7|
00000010  37 3b 33 30 35 30 32 3b  30 63 1b 5d 31 30 3b 72  |7;30502;0c.]10;r|
00000020  67 62 3a 62 66 62 66 2f  62 66 62 66 2f 62 66 62  |gb:bfbf/bfbf/bfb|
00000030  66 07 1b 5d 31 31 3b 72  67 62 3a 30 30 30 30 2f  |f..]11;rgb:0000/|
00000040  30 30 30 30 2f 30 30 30  30 07                    |0000/0000.|
```

Originally reported in https://github.com/git-for-windows/build-extra/pull/399#issuecomment-987957809

**Comment by dscho** [comment]
Running Git for Windows' `git config -e --global` from within a regular MSYS2 reproduces the issue for me.

Contrary to my suspicion, the culprit is neither https://github.com/git-for-windows/msys2-runtime/blob/70d23484c10a2f093a11e28085099c972cd1e72d/winsup/cygwin/fhandler_tty.cc#L2126 nor https://github.com/git-for-windows/msys2-runtime/blob/70d23484c10a2f093a11e28085099c972cd1e72d/winsup/cygwin/fhandler_tty.cc#L3145 nor https://github.com/git-for-windows/msys2-runtime/blob/70d23484c10a2f093a11e28085099c972cd1e72d/winsup/cygwin/fhandler_tty.cc#L3624.

**Comment by dscho** [comment]
Turns out that there is a much easier way to trigger this: launch `vim` through `git-cmd.exe`, like so:

```console
$ /git-cmd.exe --command=/usr/bin/vim.exe ~/.gitconfig; hexdump -C
```

Side note: Maybe unrelated, but maybe not, if the file to be edited is empty, there are no strange characters showing up. If it is not empty, but less than a screen-full of content, only something like `\x1b[2;2R\x1b[3;1R` or even only `\x1b[2;2R` is "ghost-typed". If the file is longer, I see the more characters than that, including the `rgb` parts showing up.

Another side note: if `TERM` is set to `screen`, I do not see those characters, only if it is set to `xterm` or to `cygwin`.

**Comment by dscho** [comment]
> ```
> /git-cmd.exe --command=/usr/bin/vim.exe ~/.gitconfig; hexdump -C
> ```

The idea behind this is, of course, to launch the MSYS2 program `vim` from the MSYS2 program `bash` via the _non_-MSYS2 program `git-cmd`. That's got to do something with the problem.

**Comment by dscho** [comment]
Another data point: the problem occurs with https://repo.msys2.org/msys/x86_64/msys2-runtime-3.2.0-13-x86_64.pkg.tar.zst, but not with https://repo.msys2.org/msys/x86_64/msys2-runtime-3.1.7-8-x86_64.pkg.tar.zst (those are the most adjacent versions still available on repo.msys2.org).

**Comment by chrisbra** [comment]
Is that with mintty? 

```
00000000  1b 5b 32 3b 32 52 1b 5b  33 3b 31 52 1b 5b 3e 37  |.[2;2R.[3;1R.[>7|
00000010  37 3b 33 30 35 30 32 3b  30 63 1b 5d 31 30 3b 72  |7;30502;0c.]10;r|
00000020  67 62 3a 62 66 62 66 2f  62 66 62 66 2f 62 66 62  |gb:bfbf/bfbf/bfb|
00000030  66 07 1b 5d 31 31 3b 72  67 62 3a 30 30 30 30 2f  |f..]11;rgb:0000/|
00000040  30 30 30 30 2f 30 30 30  30 07                    |0000/0000.|
```

Okay let's see:
 - `CSI2;2R` and `CSI3;3R` -> Cursor Position Report. Vim uses that to detect wide characters IIRC
(see `:h t_u7`) 
- `CSI[>77;30502;0c` -> Terminal Version String (Vim tries to identify the terminal type)
- `ESC]10;rgb:bfbf/bfbf/bfbf` Terminal Foreground Color (see `:h v:termrfgresp`)
- `ESC]11;rgb:0000/0000/0000` Terminal Background Color (see `:h vtermrbgresp`) 



I think Vim would only send those, if a terminal pretends to be xterm (so $TERM=xterm), if I recall correctly. Not sure why vim wouldn't consume those on startup.  Perhaps those are returned too late?

All of those request strings can be explicitly disabled, see `:h t_RV` and below for disabling those.

**Comment by dscho** [comment]
> Is that with mintty?

Yes.

> I think Vim would only send those, if a terminal pretends to be xterm (so $TERM=xterm), if I recall correctly.

That would make sense.

> Not sure why vim wouldn't consume those on startup.

Precisely! Very rarely, I even see `vim` being confused by these sequences being sent _to `vim`_, directly after opening a file.

> Perhaps those are returned too late?

That's a safe guess, I think. I see e.g. [this hack](https://github.com/git-for-windows/msys2-runtime/blob/70d23484c10a2f093a11e28085099c972cd1e72d/winsup/cygwin/fhandler_tty.cc#L3645-L3646) in the Cygwin runtime that has an arbitrary, hard-coded timeout, but this particular code seems not to be involved with the breakage.

> All of those request strings can be explicitly disabled, see `:h t_RV` and below for disabling those.

That's good to know! If all else fails, I will have to do that for Git for Windows.

My preference, though, would be to figure out where the MSYS2/Cygwin runtime is broken as of v3.2.0.

**Comment by dscho** [comment]
So after spending a _lot_ of time, I managed to identify the commit that introduced the regression: git-for-windows/msys2-runtime@f206417894273ef73c7bca0f00213866945d8b4d.

Unfortunately, it looks as if that commit tries to do many things at the same time. At least to me, the intention is not at all clear. Even worse, I cannot put my finger on the spot that causes the strange characters to be sent to the terminal instead of `vim`. The commit message gives me an idea what is going wrong, but the diff is indecipherable.

@tyan0 any insights from your side?

**Comment by dscho** [comment]
> @tyan0 any insights from your side?

Thank you for [this reply](https://sourceware.org/pipermail/cygwin-patches/2021q4/011589.html). The included patch works around the issue. I will now work on integrating it (even if I am still unhappy to say that even the diff failed to clarify the problem and the solution, conceptually).

**Comment by dscho** [comment]
Our trusted Azure Pipeline [is building and uploading the `msys2-runtime` package](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=90928&view=results).

**Comment by dscho** [comment]
> Our trusted Azure Pipeline [is building and uploading the `msys2-runtime` package](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=90928&view=results).

And it succeeded!
