### ISSUE TITLE
Git 2.5.1 fail to access HTTP/HTTPS from IPv6 only environment to IPv4/IPv6 server

### ISSUE THREAD

**Issue by aefimov** [git-for-windows/git#358]
If you have IPv6 only Windows host with installed Git 2.5.1, then `git clone https://some-host/repo.git` will failed with `Network unreachable` error.

The host `some-host` has both IPv4 and IPv6 addresses.

**Comment by aefimov** [comment]
SSH protocol on the same host work fine: `git clone ssh://some-host/repo.git` this is OK.

**Comment by dscho** [comment]
Could you please find an IPv6-only host from which *I* can clone, too?

**Comment by aefimov** [comment]
http://superuser.com/questions/332333/can-we-disable-ipv4-and-use-purely-ipv6-on-windows-xp-2003
The second one answer.

**Comment by dscho** [comment]
```sh
$ git clone http://superuser.com/questions/332333/can-we-disable-ipv4-and-use-purely-ipv6-on-windows-xp-2003
Cloning into 'can-we-disable-ipv4-and-use-purely-ipv6-on-windows-xp-2003'...
fatal: repository 'http://superuser.com/questions/332333/can-we-disable-ipv4-and-use-purely-ipv6-on-windows-xp-2003/' not found
```

Seriously again, if I wanted to chase the answer for my question myself, I would not have asked you, @aefimov :stuck_out_tongue_winking_eye:

**Comment by aefimov** [comment]
Sorry, not understand that does you mean. If you have Windows PC, just turn off IPv4 support to reproduce that.

**Comment by dscho** [comment]
From what little information I got, I guess this ticket would be addressed by https://github.com/git-for-windows/git/issues/370, too, so please test.
