### ISSUE TITLE
Vim fails to load buffers in Windows Console on Windows Server 2019 17763.2330

### ISSUE THREAD

**Issue by breiter** [git-for-windows/git#3581]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options
git version 2.34.1.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.2330]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Windows SChannel
Use Windows console

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm running Windows Server 2019 in a VMWare Fusion VM on macOS host. 
I think the issue began after Windows Update installed  KB5007266 (OS Build 17763.2330) Preview

### Details

 - Which terminal/shell are you running Git from? bash

** insert your response here **

- vi/vim hangs and never fills the text buffer. `[esc]:q!` will allow exiting and then it will dump the text that should have displayed.

```
vi
vim
git commit 
anything that invokes the default text editor, which is vim.
```
 - What did you expect to occur after running these commands?

interactive text editing in vim.

 - What actually happened instead?

terminal freezes

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I was able to restore the functionality of vim by right-clicking on the console window icon and selecting properties from the menu. Then checking the "Use legacy console (requires relaunch, affects all consoles" option. 

![image](https://user-images.githubusercontent.com/3965197/145370350-18eea379-e85c-4703-b006-32636ca957a6.png)

Or setting the same setting in the .lnk file.
![image](https://user-images.githubusercontent.com/3965197/145370402-96b0ad4b-218a-424d-91f0-8f82ab781673.png)

**Comment by dscho** [comment]
Does this also happen with a regular [MSYS2](https://msys2.org/) installation?

**Comment by breiter** [comment]
I just installed msys in order to check this out for you. The answer is yes.

The long answer is that msys always uses the mintty console when invoked from the Start Menu shortcuts that it installs. Also vim is not installed until you do `pacman -S vim`.

Confirm that Powershell console not in legacy mode. Then from Powershell:

```
cd c:\msys64\usr\bin
./vim.exe
```

Vim is unable to write to the console properly and is hung:
![image](https://user-images.githubusercontent.com/3965197/145392231-7b70045c-b416-45c1-9df8-fd4d1a176d98.png)

`[esc]:q!`
![image](https://user-images.githubusercontent.com/3965197/145392252-a3d1e27d-6524-44fc-a2d5-f83853b3d2c1.png)

**Comment by dscho** [comment]
The next question is whether this also hangs in Cygwin (from which the MSYS2 runtime is derived).

**Comment by hehuahuang** [comment]
Johannes Schindelin ***@***.***> 於 2021年12月10日 週五 21:53 寫道：

**Comment by breiter** [comment]
Yes. The behavior is identical in Cygwin64 cygwin-3.3.3-1.

**Comment by dscho** [comment]
> Yes. The behavior is identical in Cygwin64 cygwin-3.3.3-1.

The Cygwin project accepts bug reports as [described here](https://cygwin.com/problems.html).
