### ISSUE TITLE
Missing screen output from running git commands on git bash

### ISSUE THREAD

**Issue by tongah91** [git-for-windows/git#3583]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```
![image](https://user-images.githubusercontent.com/11732587/145523196-745f8a56-7fa1-4a90-908a-c83c9fab8a50.png)
do nothing. no response

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.19042.1387]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Default!


# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Bash!

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
1)git --version, git status --> do nothing
2)current branch is invisible
3)Git gui.exe  error -> cannot parse Git version string

 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Can you run `git version` in CMD? And what does `where git.exe` show in CMD?

If all else fails, I would suggest running [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) while launching `git version`, to find out what is going on.

**Comment by tongah91** [comment]
When I use CMD, the result is as below.
![image](https://user-images.githubusercontent.com/11732587/145669618-7aae8560-39a5-4499-9228-aa189dc4ffc8.png)

When I use 'git bash',
![image](https://user-images.githubusercontent.com/11732587/145669652-2ff2ab81-9142-43a7-aea7-464ac0984892.png)

**Comment by hlovdal** [comment]
I would suggest editing the title to describe the problem (e.g. "missing screen output from running git commands" or something similar.

One thing that would be interesting to test is running

```shell
git --version > ver.txt
cat ver.txt
```
or
```shell
git --version | cat
```
because I suspect this to be related to stdout being a tty or not.

Also, what is the output from `stty -a`?

**Comment by tongah91** [comment]
@hlovdal 
Thanks for comment!
Also, i changed title,too!

See the following below, please.
![image](https://user-images.githubusercontent.com/11732587/147434633-2cf6c556-bd56-43d8-953d-b54e2a817c8f.png)

**Comment by hlovdal** [comment]
Hm, I was expecting `git --version > ver.txt` and `git --version | cat` to behave the same. There are some [differences between pipes and redirects](https://askubuntu.com/questions/172982/what-is-the-difference-between-redirection-and-pipe) where I guess inter process buffering is the most significant and perhaps the differentiating factor here?

Anyhow, it would be interesting to figure out further what works or not. Could you run the following commands:

```shell
git --version > /dev/stdout
git --version > /dev/stderr
git --version > /dev/fd/1
git --version > /dev/fd/2
git --version | tee /dev/stdout
git --version | tee /dev/stderr

git --version 1>&2
git --versionzzzzzzzzzzzzzzz

echo $(git --version)

(git --version)
(git --version) | cat

exec 3>&1
exec > /dev/stdout
git --version
exec 1>&3
```

(Tip: to save yourself from having to redact username/hostname afterwards, you can just run with `PS1='$ '`

The stty output is identical with what I get on the machine I am sitting on now, so there is nothing wrong there.

**Comment by PhilipOakley** [comment]
Not sure about your particular problem, but it's worth noting that a number of git commands will detect if the stdout is a terminal or not, so that it only sends human informational output to the terminal device. 

This can be confusing if you are looking at informational output that's not a core output of the command.

Do any other commands produce their expected output in both bash and CMD, or is it a general problem with your bash ?

**Comment by rimrul** [comment]
> Not sure about your particular problem, but it's worth noting that a number of git commands will detect if the stdout is a terminal or not

[`git version` doesn't do that](https://github.com/git/git/blob/f443b226ca681d87a3a31e245a70e6bc2769123c/help.c#L701-723), though. So that shouldn't play a role here.

> Do any other commands produce their expected output in both bash and CMD, or is it a general problem with your bash ?

`cat ver.txt` and `stty -a` produced the expected output. So MSys2 applications seem to be fine, presumably shell builtins are also fine.

Could you test wether other mingw-w64 applications are affected? Does `antiword` produce output?

**Comment by tongah91** [comment]
@hlovdal @PhilipOakley @rimrul 
I am really sorry to bother you.
I found that a internal program which our company made for security blocks the git....
Really thank you for your concern!!

**Comment by PhilipOakley** [comment]
> I found that a internal program which our company made for security blocks the git....

Thank you for providing the feedback. It is useful to have such data points.
