### ISSUE TITLE
"git log" for path with wrong casing

### ISSUE THREAD

**Issue by csware** [git-for-windows/git#359]
Run `git log -- path-with-wrong-case` and see an empty log. `core.ignorecase` is `true`.

Example:
Clone `https://github.com/TortoiseGit/TortoiseGit.git` and run `git log -- src/TortoisePlink/windows`, works for `git log -- src/TortoisePlink/Windows`. However, after clone Windows Explorer shows the path `windows` lowercased.

**Comment by dscho** [comment]
Please remember that `core.ignorecase` only affects *file system* operations. When you run `git log`, it operates on the internal database (which is *always* case sensitive, therefore there is not even an option to ignore the case).

> However, after clone Windows Explorer shows the path windows lowercased.

As far as `git log` is concerned, it does not matter how the file is stored in the file system. In fact, you do not even have to have a working directory checked out for `git log` to work: it works on the *repository*, where the files are stored with a specific case. You really need to use that spelling, not any random spelling.
