### ISSUE TITLE
Add pv utility

### ISSUE THREAD

**Issue by superbonaci** [git-for-windows/git#3596]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Request to add the utility `pv` to MINGW64. There is already `dd` but has no progress capabilities.

**Comment by dscho** [comment]
I never heard of `pv`. And this ticket does a poor job of convincing me that Git for Windows users would want it, even if it described what the tool is about and where it can be downloaded. Besides, Git for Windows is not meant as a "let's include All The Things!" package, but as a package that delivers _Git_ (and a few tools that are relevant to Git).

**Comment by superbonaci** [comment]
website: http://www.ivarch.com/programs/pv.shtml
