### ISSUE TITLE
Git for windows throws an error when running any git command in a directory that contains a git.py file

### ISSUE THREAD

**Issue by froilson** [git-for-windows/git#3597]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Versión 10.0.19044.1415]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Folder with a git.py file

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Running any git command (git, git status, git branch, etc.) in a directory that contains a git.py file.
```
 - What did you expect to occur after running these commands?

The normal output of the git command.

 - What actually happened instead?

Traceback (most recent call last):
  File "D:\cygwin64\home\****\powerline-shell\powerline_shell\segments\git.py", line 3, in <module>
    from ..utils import RepoStats, ThreadedSegment, get_git_subprocess_env
ImportError: attempted relative import with no known parent package

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/b-ryan/powerline-shell

**Comment by rimrul** [comment]
Did you mess with your `PATHEXT` environment variable? This sounds like you prepended .py to that variable.

**Comment by rimrul** [comment]
Also what does `where git` say?

**Comment by froilson** [comment]
Yes, PATHEXT has a .py append no prepend, so running git in the command line makes execute the git.py in that folder, because take precedence. Is the only solution removing the .py in the PATHEXT?

**Comment by dscho** [comment]
@froilson it is a well-known fact that regular CMD will execute `git` from the current directory if there is one. What you _really_ wanted to do is to run this from `Start Menu>Git>Git CMD`. The sole reason for us to ship a `Git CMD` to you is so that you can use it _in order_ to prevent `git` from the current directory to be executed.

**Comment by dscho** [comment]
@froilson do you think you would have seen this information if it had been added to the "Known Issues" section of Git for Windows' release notes?

**Comment by froilson** [comment]
Yes, I would

**Comment by dscho** [comment]
> Yes, I would

Good! Then you have the excellent opportunity on your hands to contribute a PR to https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues.
