### ISSUE TITLE
non-error output is sent to stderr instead of stdout

### ISSUE THREAD

**Issue by rkitover** [git-for-windows/git#3598]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22523.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell:

```console
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22523
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I want to suppress normal output in a script, but still allow error output. So I tried this:

```powershell
git clone https://github.com/scopatz/nanorc | out-null
```
.

However, this does nothing, because the output goes to `stderr`, e.g.:

```powershell
ri -r -fo nanorc
git clone https://github.com/scopatz/nanorc 2>$null
```
.

 - What did you expect to occur after running these commands?

I expected normal informational output to go to `stdout` and only error output to go to `stderr`.

 - What actually happened instead?

All output goes to `stderr`.

**Comment by rimrul** [comment]
Allow me to quote [a recent message on the git mailing list](https://lore.kernel.org/git/20211202223110.22062-1-sunshine@sunshineco.com/) by Eric Sunshine:

> It has long been practice on this project for a command to emit its primary output to stdout so that it can be captured to a file or sent down a pipe, and to emit "chatty" messages (such as those reporting progress) to stderr so that they don't interfere with the primary output. 

That describes fairly well how most git commands handle stdout/stderr and why they do it that way.

What you're looking for seems to be along the lines of the [`--quiet` option](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---quiet).

**Comment by rkitover** [comment]
I did not know that was normal behavior, thank you.
