### ISSUE TITLE
Tab completion and arrow keys don't work in GHCI in Git Bash

### ISSUE THREAD

**Issue by ploeh** [git-for-windows/git#360]
Please accept my apologies if this is a duplicate, but I've done a bit of searching, and I haven't found anything that sheds light on my problem.

The following is cross-posted from http://stackoverflow.com/q/32369805/126014, but since I've had little reaction to that post, I'm cross-posting it here in the hope of thereby reaching a more appropriate audience.

When I open `ghcii.sh` (Glasgow Haskell Compiler Interactive) in Git Bash, normal tab, backspace, and arrow keys don't work as expected.

For example, if I type `:lo` + <kbd>Tab</kbd>, I'd expect it to complete the statement to `:load`. What instead happens is that the cursor jumps to the right (to the next tab stop, I guess).

Then, if I use <kbd>Backspace</kbd> to go back and fill out the command 'manually', this happens:

    Prelude> :load PrettyJSON.hs
    
    <interactive>:2:1:
        Not in scope: `ad'
        Perhaps you meant one of these:
          `and' (imported from Prelude), `id' (imported from Prelude)
    
    <interactive>:2:4: Not in scope: `PrettyJSON.hs'

This is when I'm *lucky*. Sometimes, I can't even <kbd>Backspace</kbd> all the way back, but instead get stuck somewhere to the right of `:lo` (or whatever other command I'm attempting to issue). I can still hit <kbd>Enter</kbd>, though, to try again.

The arrow keys don't invoke command history. If I press <kbd>&#9650;</kbd>, the cursor moves up, but I'd have expected it to cycle through my command history.

This issue seems to be related to Git Bash, because GHCI works correctly in PowerShell on the same machine. On other machines where I'm running an earlier version of Git Bash (git version 1.9.5.msysgit.1), I don't have this problem, so it seems to be related to this particular version (git version 2.5.1.windows.1).

My operating system is Windows 10 64-bit. At first I thought that this issue was related to 64-bit Git Bash, because this is the first time I've seen a 64-bit Git Bash on Windows, but I've also tried installing the 32-bit Git Bash, and it exhibits the exact same behaviour.

Is it possible to make GHCI behave correctly in this environment?

**Comment by dscho** [comment]
@ploeh could you test whether the problem disappears if you reinstall Git for Windows choosing the "ConHost" based terminal emulator instead of the "mintty" one?

**Comment by ploeh** [comment]
That seems to solve the problem, thank you :+1: 

The only problem with that solution is that now the window has the boring CMD icon, instead of the nice Git icon:

![image](https://cloud.githubusercontent.com/assets/242165/9743280/be3aa06e-5665-11e5-91c3-054d489ef95a.png)

**Comment by dscho** [comment]
> The only problem with that solution is that now the window has the boring CMD icon, instead of the nice Git icon

Yeah, that is a big problem :wink: 

Actually, I find the bigger problem that the solution is not obvious to power users who want to do other stuff than run Git commands. If you can think of a way to notify users better when this issue arises, and give a meaningful hint how to solve it, that would be very much appreciated.
