### ISSUE TITLE
Question about changing a System configuration default setting in the installer

### ISSUE THREAD

**Issue by RobertKlohr** [git-for-windows/git#3603]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
git version 2.33.1.windows.1
cpu: x86_64
built from commit: 05d80adb775077d673fab685009ede4a1003ed92
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
Microsoft Windows [Version 10.0.19043.1348]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

SSL teardown inspection uses certificates that are not signed by any of the trusted root certificate authorities included in the certificate bundle tls-ca-bundle.pem used by openssl for TLS.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

This issue should be tagged as a question.

I looked around this and related repositories and was not able to figure out where and how the gitconfig file installed with Git for Windows at "C:\Program Files\Git\etc\gitconfig" is maintained and it also seemed like this question is specific to the Windows build of Git.

What I want to understand is how I can raise the issue and have the discussion for changing one of the default System settings in the gitconfig file for the Git for Windows package. Specifically changing:
````
http.sslbackend=openssl
to
http.sslbackend=schannel
````

In case this is the best place to have this discussion, here is my reasoning for this proposed change.

I understand that this can be overridden with a Global but that will not work in our use case as we have some processes that specifically pull the System level settings. This is further complicated since most developers do not have local administrator access and so they are not able to change the System level settings, which is why we purposely pull System level settings. We obviously have a workaround in place now to make System Level changes but I am proposing a change to the build/installer that I think will benefit the entire community. 

1. Given the update frequency of the certificate bundle in this package, it can be several months between updates and which could be longer if the user does not update the Git client. The Windows certificate store is automatically updated at least monthly. From at security stand point, setting the default behavior to use the certificate store that is automatically more frequently is the better solution.
2. The added benefit in corporate environments is that the certificate bundle used by openssl will always be a subset of the certificates in the Windows certificate store as it will not include any corporate self-signed certificates that are published the trusted root certificate store.

The other option would be to add a task to the installer package that could then be used on the installer command line to toggle this setting as part of the install. This would allow us to maintain the status quo for home and non-corporate installs and allow overriding the setting for corporate installs that need it.

If this is not the appropriate venue for this discussion please point me to that location in your response and close the issue and I will start the conversation where it needs to happen.

Thanks to everyone working to maintain this package!

**Comment by rimrul** [comment]
> This issue should be tagged as a question.

Done.

> I looked around this and related repositories and was not able to figure out where and how the gitconfig file installed with Git for Windows at "C:\Program Files\Git\etc\gitconfig" is maintained 

https://github.com/git-for-windows/build-extra/blob/main/git-extra/gitconfig

But that doesn't include the config value you're curious about.

> and it also seemed like this question is specific to the Windows build of Git.

Yes, yes it is.

> 
> What I want to understand is how I can raise the issue and have the discussion for changing one of the default System settings in the gitconfig file for the Git for Windows package. Specifically changing:
> ````
> http.sslbackend=openssl
> to
> http.sslbackend=schannel
> ````
 
Defaulting to `schannel` brings its own downsides, including no TLS 1.3 support for now (not yet implemented in curl for that backend).

> The other option would be to add a task to the installer package that could then be used on the installer command line to toggle this setting as part of the install. This would allow us to maintain the status quo for home and non-corporate installs and allow overriding the setting for corporate installs that need it.

We have a setting in the installer UI already and your original post mentioned it:

> CURL Option: OpenSSL

I'm not sure if there's a way to set it from a command line argument, though. It should be possible, I'll look up the details on that.

**Comment by RobertKlohr** [comment]
Just to clarify one point about the changing the setting during the install.

While you can change the setting in the UI during the install there is no command line option to make this change. Having the ability to set this value, possibly others, by passing them on the command line to the installer what we need to enterprise deployments.

Another possibility, aside from making a change to the exe installer that would allow for this setting to be made on the command line, would be to package this as an MSI installer which opens up other advantages for enterprise installs.

**Comment by dscho** [comment]
> While you can change the setting in the UI during the install there is no command line option to make this change.

That's incorrect. You have several options:

* You can use `/SAVEINF="filename"` to save the choices to an `.ini`-style file, then run the installer with `/LOADINF="filename"` to replay them. Call the installer with `/?` for more details.
* You can use [`/o:<key>=<value>`](https://github.com/git-for-windows/build-extra/commit/8764c72d83cd05a709fcb21700e42081d226037b) to manually override the default for the settings. The `<key>` corresponds to the key passed to [`ReplayChoice()`](https://github.com/git-for-windows/build-extra/blob/8d440603f664af5e94f90f85fae966d1656c8d28/installer/install.iss#L2203) without spaces.

> Another possibility, aside from making a change to the exe installer that would allow for this setting to be made on the command line, would be to package this as an MSI installer which opens up other advantages for enterprise installs.

You probably missed the fact that this project has started a long time ago already: https://github.com/git-for-windows/build-extra/tree/HEAD/msi. It already has stalled a long time ago, too, so if you are interested, feel very welcome to rekindle it.

In any case, I think the original question has been addressed, so I will close this ticket.

**Comment by RobertKlohr** [comment]
Thanks for the details on the installer configuration. I was unable to find that information on the project web site and it solves our problem!
