### ISSUE TITLE
new Version of Git for Windows Crashing upon instal and start up

### ISSUE THREAD

**Issue by simyking** [git-for-windows/git#3606]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64bit 2.34.1
```
$ git --version --build-options

'git' is not recognized as an internal or external command,
operable program or batch file.
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1415]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
 
  bash SSH 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh ubuntu@ahbkdsb.com
``` 
 - What did you expect to occur after running these commands?

 to connect to the instance

upon installation of git on windows 10 it doesnt start .

 - What actually happened instead?

git closed  

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
This report is unfortunately way too short to allow anybody to help.
