### ISSUE TITLE
Git editor disables conhost QuickEdit and Insert Mode

### ISSUE THREAD

**Issue by kevinoid** [git-for-windows/git#3607]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 2.34.1 64-bit

```
$ git --version --build-options

git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? 10 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1415]
```

 - What options did you set as part of the installation? Or did you choose the defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related to the issue you're seeing?

Issue occurs with [Vim 8.2.3951](https://github.com/vim/vim-win32-installer/releases/download/v8.2.3951/gvim_8.2.3951_x64.exe) (not the bundled version)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD/PowerShell/pwsh (all conhost-based)

 - What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

Steps to reproduce:

1. Open `cmd`, or `powershell`, or `pwsh` (PowerShell 7).  (the issue occurs in [Legacy Console Mode](https://docs.microsoft.com/windows/console/legacymode) and non-legacy mode)
2. Open Properties and confirm both "QuickEdit Mode" and "Insert Mode" are checked.  (Or confirm text can be selected by clicking and dragging in the window.)
3. Run `git -c core.editor="C:\\Program\ Files\\Vim\\vim82\\vim.exe" config --system --edit`
4. Open Properties and confirm both "QuickEdit Mode" and "Insert Mode" are no longer checked.  (Or confirm text can **not** be selected by clicking and dragging in the window.)

 - What did you expect to occur after running these commands?

The console would remain in QuickEdit and Insert Modes.

 - What actually happened instead?

QuickEdit and Insert Mode are disabled.

#### If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing?

Issue occurs in any repository or outside of a repository.

 - Additional Details

The issue only occurs with some editors:

1. `core.editor="C:\\Program\ Files\\Vim\\vim82\\vim.exe"` Leaves QuickEdit
2. `core.editor="C:\\Program\ Files\\Vim\\vim82\\gvim.exe"` Stays in QuickEdit
3. `core.editor=C:\\Windows\\notepad.exe` Stays in QuickEdit
4. `core.editor="C:\\Program\ Files\\Git\\usr\\bin\\vim.exe"` Stays in QuickEdit
5. `core.editor="C:\\Program\ Files\\Git\\usr\\bin\\nano.exe"` Stays in QuickEdit
6. `core.editor="C:\\Path\\To\\micro.exe"` ([Micro](https://github.com/zyedidia/micro/releases/tag/v2.0.10)) Leaves in QuickEdit

It appears that the issue occurs for non-Cygwin console applications?

I had initially reported the issue as https://github.com/microsoft/terminal/issues/12077 thinking it was an issue in conhost.  Now that it appears to be caused by something Git is doing, I've opened this issue.

Thanks,
Kevin

**Comment by dscho** [comment]
> Issue occurs with [Vim 8.2.3951](https://github.com/vim/vim-win32-installer/releases/download/v8.2.3951/gvim_8.2.3951_x64.exe) (not the bundled version)

Are you saying that it does _not_ occur with the bundled version? Or did you not test?

**Comment by DHowett** [comment]
This is likely a bad interaction between the runtime constantly calling `Get/SetConsoleMode` and Vim [patch 8.2.2913](https://github.com/vim/vim/commit/6ef5ab59043681a51e8ca2ab0a1e4ff8f0f4bb47) disabling quickedit mode.

Vim should be re-enabling it on exit (which I believe it is) -- so I'm curious who's re-disabling it. Transitioning between cmd and vim seems to handle quickedit mode properly.

**Comment by kevinoid** [comment]
Thanks @DHowett, that's a good find!  I don't see `ENABLE_QUICK_EDIT_MODE` in [micro](https://github.com/zyedidia/micro/search?q=ENABLE_QUICK_EDIT_MODE) so it may be a different cause there (or it's enabled some other way).  I'll check whether the issue occurs with older versions of Vim.

**Comment by kevinoid** [comment]
I can confirm that vim 8.2.2907 stays in QuickEdit Mode and vim 8.2.2914 leaves QuickEdit Mode.  Sounds like you were spot on about patch 8.2.2913.

**Comment by DHowett** [comment]
I added a trace point in `SetConsoleMode`. Here's what I found!

<img width="844" alt="image" src="https://user-images.githubusercontent.com/189190/147976080-7775912f-7992-4125-9e20-577e56aec23e.png">

In order, by the number in Line#, starting with 2.

2. cmd enables 0x80 (`EXTENDED_FLAGS`) but doesn't change other modes (`INSERT`, `QUICK_EDIT` and `AUTO_POSITION` are on)
3. sh enables 0x100 (`VIRTUAL_TERMINAL_INPUT`)
4. sh disables 0x100
5. sh enables 0x8 (`WINDOW_INPUT`)
6. sh clears all modes except 1, 2, 4,  8 (`PROCESSED`, `LINE`, `ECHO`, `WINDOW`)
   * **IMPORTANT:** Since sh did not use `EXTENDED_FLAGS`, the `INSERT`, `QUICK_EDIT` and `AUTO_POSITION` flags are not touched.
7. vim sets `EXTENDED_FLAGS`, disabling the three modes mentioned in "6-Important"

23. vim restores the mode it got on startup, keeping `EXTENDED_FLAGS` set to as to leave `INSERT`, `QUICK_EDIT` and `AUTO_POSITION` disabled.

Looking at the logic in conhost, it seems as though it _might_ be our fault in the end. 😁 When you call SetConsoleMode without specifying `EXTENDED_FLAGS`, we will never reply to you by _including_ `EXTENDED_FLAGS` (and therefore, none of the extended flags). In step 6, sh calls `SetConsoleMode(0xF)` -- no `EXTENDED_FLAGS` -- so when vim calls `GetConsoleMode` we gladly report that all extended flags are turned off. . . which vim remembers until it exits, and when it restores them to what it thought it should... it turns them off.

**Comment by dscho** [comment]
@DHowett great find! I _bet_ that the code in question is not actuall Bash's, but Cygwin's (or: the MSYS2 runtime's): https://github.com/git-for-windows/msys2-runtime/blob/6e0141cf6151d9cfe74dd0196cf9698a2a6cbfcb/winsup/cygwin/fhandler_console.cc#L470-L517

**Comment by rimrul** [comment]
I think this might be fixed by https://github.com/git-for-windows/msys2-runtime/commit/a6f441c8d22a38dd8b8bee1190fa391abde57522

**Comment by dscho** [comment]
> I think this might be fixed by [git-for-windows/msys2-runtime@a6f441c](https://github.com/git-for-windows/msys2-runtime/commit/a6f441c8d22a38dd8b8bee1190fa391abde57522)

Good find! On the assumption that it is, let's close this here ticket.

**Comment by kevinoid** [comment]
I can confirm that I'm unable to reproduce the issue using [Vim 9.0.44](https://github.com/vim/vim-win32-installer/releases/tag/v9.0.0044) and [Git for Windows 2.37.0](https://github.com/git-for-windows/git/releases/tag/v2.37.0.windows.1) after extracting the [build for git-for-windows/msys2-runtime@4ca643e](https://github.com/git-for-windows/msys2-runtime/actions/runs/2635000418) over the Git for Windows installation.  Thanks!

**Comment by kevinoid** [comment]
> Could you test v2.37.1? That should work without any msys-2.0.dll copying.

Oh nice!  I can confirm that I'm also unable to reproduce the issue with v2.37.1.
