### ISSUE TITLE
Pop/Apply Stash fails to restore added files when conflict occurs

### ISSUE THREAD

**Issue by AJH16** [git-for-windows/git#3609]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Windows 10 64 bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Mix of TortoiseGit, process execution from a custom Visual Studio extension and direct command line.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
   1. Stash changes with files that are added and files that already exist.
   2. Make changes to the existing files so that a pop will have a conflict.
   3. Attempt to pop/apply the stash.
```
 - What did you expect to occur after running these commands?

Added files should be restored and the conflict should be setup for resolution.

 - What actually happened instead?

The conflict is setup for resolution, however the added files are not restored.  They are accessible if we directly access the log of the stash head and we can export the files from this as a work around, but the pop/apply fails to restore the working folder to the pre-push state.  This has been observed on 3 separate occurrences so far on two different developers' machines.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This has occured on multiple repositories and they are all internally hosted.  It also is a local only problem.

**Comment by PhilipOakley** [comment]
There does appear to be an issue with that version. It is being looked at on the main Git mailing list, such as this thread https://lore.kernel.org/git/9749fa2c-b08d-c08b-ce43-041d13852d02@web.de/

**Comment by AJH16** [comment]
Not sure if that one might be related or not, but I've also submitted my own report to the git mailing list as well.  Couldn't really tell if this was something Windows specific or not since I don't have any Linux boxes to test on.

**Comment by dscho** [comment]
@PhilipOakley I am unsure that `git stash` mishandling added files has anything to do with `git pull --rebase` ignoring the `rebase.autostash` flag when fast-forwarding...

**Comment by dscho** [comment]
> 1. Stash changes with files that are added and files that already exist.
>    2. Make changes to the existing files so that a pop will have a conflict.
>    3. Attempt to pop/apply the stash.

@AJH16 could you turn that into a small scriptlet, preferably in the same shape as the test cases in https://github.com/git-for-windows/git/blob/main/t/t3903-stash.sh?

**Comment by dscho** [comment]
Closing as stale.
