### ISSUE TITLE
connect command fails with /usr/bin/bash: C:/Program: No such file or directory

### ISSUE THREAD

**Issue by mikeKuester** [git-for-windows/git#3617]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1977] (single user install)
and
Microsoft Windows [Version 10.0.17763.1935] (all user install)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: C:\Eigene Programme\Notepad++\notepad++.exe
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
connect -H xx.xx.xx.xx:8080 github.com 443
```
 - What did you expect to occur after running these commands?

A dialog window should open and ask for my proxy credentials.

 - What actually happened instead?

Depending on the Git for Windows installation type (single user / all users) or the windows version it works, or it works not:

- On a computer Microsoft Windows [Version 10.0.18363.1977], with an installation without admin rights (%USERPROFILE%\AppData\Local\Programs\Git) the dialog windows opens.
- On a computer Microsoft Windows [Version 10.0.17763.1935], with an installation with admin rights (C:\Program Files\Git) I got this error:
  - Der Befehl "C:\Program" ist entweder falsch geschrieben oder konnte nicht gefunden werden. (original in german)
  - /usr/bin/bash: C:/Program: No such file or directory   (should be english one)

I started with a failing `ssh github.com -v` connection test and could drill it down to the connect command. It seems, that it has a path problem with the whitespace in the path "C:\Program Files".

**Comment by rimrul** [comment]
On my machine it seems to find `connect` just fine.

```
$ connect
connect --- simple relaying command via proxy.
Version 1.105
usage: C:\Program Files\Git\mingw64\bin\connect.exe [-dnhst45] [-p local-port]
          [-H proxy-server[:port]] [-S [user@]socks-server[:port]]
          [-T proxy-server[:port]]
          [-c telnet-proxy-command]
          host port
```
That's with the same version of Git for Windows
```
$ git --version --build-options
git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
on a slightly different version of windows:
```
 cmd //c ver

Microsoft Windows [Version 10.0.19043.1415]
```

But that message doesn't sound like it's comming from bash. Because bash wouldn't convert that path to a Windows path wenn producing the message. It would output

```
$ connect
bash: /mingw64/bin/connect: No such file or directory
```

So there seems to be some broken step in between on your system. what does `which connect` say for you? it should say 

```
$ which connect
/mingw64/bin/connect
```

**Comment by dscho** [comment]
Since `/mingw64/bin/connect` is a regular executable, and since the reported error message explicitly mentions `/usr/bin/bash`, I highty suspect a Bash script in `~/bin/` which is called `connect` to be in the way. And this script probably contains an incorrectly-quoted command, which would explain the reported error message.

**Comment by mikeKuester** [comment]
Hi,

@rimrul 
I got the same response:
```
$ which connect
/mingw64/bin/connect
```

@dscho 
Any idea how I can test this? On the machines with the error, the prompt for the credentials doesn't open. Could the "askpass" call be the reason?

**Comment by rimrul** [comment]
> On the machines with the error, the prompt for the credentials doesn't open. Could the "askpass" call be the reason?

That actually sounds like it could be the issue at hand. Since I didn't have a proxy at hand (and assumed the command that couldn't be found was `connect` itself) I invoked `connect` without args, so it didn't get to that stage.

It looks like `mingw-w64` `popen()` expects spaces in paths to be escaped in some way, and `connect` just passes the values it gets from `getenv()` (almost) straight into `popen()`.

**Comment by rimrul** [comment]
After some testing, I think we could trick `connect` into finding the right `git-askpass` by setting `SSH_ASKPASS` to just `git-askpass` instead of `/mingw64/bin/git-askpass`.

**Comment by mikeKuester** [comment]
Ok, I will try it soon.

**Comment by dscho** [comment]
> It looks like `mingw-w64` `popen()` expects spaces in paths to be escaped in some way, and `connect` just passes the values it gets from `getenv()` (almost) straight into `popen()`.

You mean this, right? https://github.com/gotoh/ssh-connect/blob/b65b09a0ee06950972233e8ea86ef87c4e63b3c9/connect.c#L2042

Yes, it should quote the result from `askpass`. OpenSSH itself [uses `SSH_ASKPASS` as `argv[0]`](https://github.com/openssh/openssh-portable/blob/03190d10980c6fc9124e988cb2df13101f266507/readpass.c#L80). So we need to patch goto/ssh-connect, and then https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-connect/PKGBUILD.

**Comment by rimrul** [comment]
> > It looks like `mingw-w64` `popen()` expects spaces in paths to be escaped in some way, and `connect` just passes the values it gets from `getenv()` (almost) straight into `popen()`.
> 
> You mean this, right? https://github.com/gotoh/ssh-connect/blob/b65b09a0ee06950972233e8ea86ef87c4e63b3c9/connect.c#L2042

yes, or at least that general area.

**Comment by mikeKuester** [comment]
`SET SSH_ASKPASS = git-askpass` did the trick :)

Now the ssh github.com works as expected!

**Comment by dscho** [comment]
Closing as stale.
