### ISSUE TITLE
Rebase after amending someone else's commit (merge base) removed the changes introduced in amend

### ISSUE THREAD

**Issue by vaibhavdangayachvd** [git-for-windows/git#3618]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.0.windows.1
cpu: x86_64
built from commit: 959b2f0c6fb12f8ba13f9015c4482fa8133b7f9c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1977]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git checkout main
git checkout -b myBranch (added a function to a file which already had some code )
git add .
git commit --amend --no-edit (also tried git commit --amend -m "My Commit")
git rebase main (successfully rebased)
```
 - What did you expect to occur after running these commands?

I have two branches which looks like this

```
A->B->C - Master
A->B->C - Branch ( branched from Master )
```

Now I have amended to C commit in 'Branch'

```
A->B->C - Master 
A->B->C' - Branch
```

When I rebase 'Branch' with 'Master', I was expecting 'Branch' to be `A->B->C->C'`

 - What actually happened instead?

it became `A->B->C`.

PS : If I don't rebase directly but first soft reset the commit C' and make a fresh commit

```
A->B->C - Master
A->B->C'' - Branch
```

Now if I do a rebase with 'Master', it correctly becomes `A->B->C->C''`

```
git checkout main
git checkout -b myBranch (added a function to a file which already had some code )
git add .
git commit --amend --no-edit
git reset --soft HEAD~1
git commit -m "New commit"
git rebase main (successfully rebased) 
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not able to reproduce this on a small example. The file in which the amend is made has 4000 lines and the commit belongs to a different user.

**Comment by rimrul** [comment]
Please don't ask people to go lookup all the info about your issue on stacoverflow. I've inlined the information from stackoverflow into the issue description.

**Comment by dscho** [comment]
> Not able to reproduce this on a small example.

That is pretty much a non-starter. If you cannot provide any way to easily reproduce for others, how do you reasonably expect them to help you?

**Comment by vaibhavdangayachvd** [comment]
> > Not able to reproduce this on a small example.
> 
> That is pretty much a non-starter. If you cannot provide any way to easily reproduce for others, how do you reasonably expect them to help you?

You're right but I can't provide the repository as it doesn't belong to me and I am even not able to reproduce this.
I am confused. On other repos it's working correctly.

**Comment by dscho** [comment]
> You're right but I can't provide the repository as it doesn't belong to me and I am even not able to reproduce this.

Well. The cheap way out is to close the ticket, then.

A much better way is to create a minimal repository that exposes the issue, preferably as a small script.

If a first draft of said script does not reproduce the issue, you need to make it more similar to the repository you cannot share, e.g. using a (minimal!) subset of the file contents in question. Iterate, until you can reproduce.

**Comment by vaibhavdangayachvd** [comment]
I tried to do what you said then only I closed the ticket because it was not reproducible. Max I can do rn it to record a video of this happening if that helps somehow.

**Comment by PhilipOakley** [comment]
> git commit --amend --no-edit (also tried git commit --amend -m "My Commit")

What was the size/scale of the amendment? was it just white space changes to match local linting requirements? Are there End of Line changes? (e.g. the prime repo is on Linux LF while you are on Windows CRLF)

If you try to cherry-pick the commit `C'` onto the `C` commit, does it work?

What does the various diffs look like? 

It's mainly a case of finding little clues to start solving your mystery.

**Comment by vaibhavdangayachvd** [comment]
@PhilipOakley Thanks for the guidance. 
I just realized that I had amended to a merge commit.
This is reproducible. Is this the behavior of rebase ?

**Comment by dscho** [comment]
`git rebase` does not rebase merges. And `git rebase --rebase-merges` does not (yet) try to figure out amended changes, it recreates the merges from scratch.

**Comment by vaibhavdangayachvd** [comment]
@dscho So its an issue ? It shouldn't just complete the rebase (dropping the changes) without warning.

**Comment by dscho** [comment]
Yes, it's a known caveat. No, the tool cannot guess that you misread the documentation :-)
