### ISSUE TITLE
Git doesn't detect file changes

### ISSUE THREAD

**Issue by GabriG86** [git-for-windows/git#3631]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.34.1.windows.1 
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea <br>
sizeof-long: 4 
sizeof-size_t: 8 
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Versione 10.0.19043.1466]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**This issue has been raised again https://stackoverflow.com/questions/64037860/git-doesnt-detect-file-changes-on-windows-10. However, modify or eliminate core.ignoreStat does not solve the issue**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
It is not a command. Any file modification is not detected then I cannot add/commit. However, If you create new files they are detected. Tried same repository on Mac everything work smoothly
```
 - What did you expect to occur after running these commands?

**I was expecting to see changes with the command .git status**

 - What actually happened instead?

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Any**

**Comment by dscho** [comment]
> It is not a command. Any file modification is not detected then I cannot add/commit. However, If you create new files they are detected. Tried same repository on Mac everything work smoothly

This is very, very unclear.

What is the scenario? How do you modify the files? If you want others to help you, do spend some time to explain how to reproduce the issue. By asking for help, you are asking for something of quite a bit of value, and you might want to craft your question with the same care you wish anybody answering it to exert (the report falls short of that).

**Comment by Drogo210** [comment]
It wasn't my intent to be very very unclear.

Let's say you have a local repository with some folder and several files (for semplicity let's assume it's one .html file) that you have pushed, successfully, into GitHub.

Now inside the main branch you start modifing the .html (vi filename.html) and then you save the modifications. Now by git status you should see the changes, this does not happen and then you are unable to git add and commit.

I have tried the same procedure on a Mac and this issue does not appear.

**Comment by GabriG86** [comment]
It wasn't my intent to be very very unclear.  

Let's say you have a local repository with some folder and several files (for semplicity let's assume it's one .html file) that you have pushed, successfully, into GitHub.  

Now inside the main branch you start modifing the .html (vi filename.html) and then you save the modifications. Now by git status you should see the changes, this does not happen and then you are unable to git add and commit.  

I have tried the same procedure on a Mac and this issue does not appear.

**Comment by dscho** [comment]
When I edit `.html` files with `vi` which I track in my Git repositories, they are very much marked as modified by Git for me. So the issue you report does very much _not_ reproduce on my side. Assuming that you are not making up this report, there must be _something_ unusual in your setup, something that causes Git not to see the modifications you made.

**Comment by dscho** [comment]
> built from commit: 2ca94ab318509b3c271e82889938816bad76dfea <br>

What's that spurious `<br>` about?

**Comment by GabriG86** [comment]
> When I edit `.html` files with `vi` which I track in my Git repositories, they are very much marked as modified by Git for me. So the issue you report does very much _not_ reproduce on my side. Assuming that you are not making up this report, there must be _something_ unusual in your setup, something that causes Git not to see the modifications you made.

As I wrote I do the same steps on a MAC and there I do not have any issue (same repository by git clone). 
Since I still have this issue and you don't there must be something wrong on my side at the software level, since on MAC I have no issue.
Anyway thank you very much for your time. At least I can exclude something inside git. Assuming that you are writing the truth.


> > built from commit: [2ca94ab](https://github.com/git-for-windows/git/commit/2ca94ab318509b3c271e82889938816bad76dfea)
> 
> What's that spurious `<br>` about?

Nothing, at first I have tried to seprate lines with <br> then by looking at preview I saw it wasn't needed.

**Comment by dscho** [comment]
> * Any other interesting things about your environment that might be related
>       to the issue you're seeing?

See whether your `git config -l --show-origin` shows anything unusual.

**Comment by GabriG86** [comment]
This was helpful, I guess. If I compare with Mac. The following are present/different:

- file:C:/Program Files/Git/etc/gitconfig core.symlinks=false (not on Mac)
- file:C:/Program Files/Git/etc/gitconfig pull.rebase=false (not on Mac)
- file:.git/config        core.filemode=false (true on Mac) "Could be this one the problem"

In Mac I also have file:.git/config        core.precomposeunicode=true but I do not think it's related to the issue

**Comment by dscho** [comment]
None of those settings could explain why Git does not see modifications. Git should see differences in size, and differences in the Modified Time.

**Comment by GabriG86** [comment]
I wrote it in the first message. So I just reiterate it. New files (touch filename) are seen by git and I can corrctly add/commit them.

**Comment by dscho** [comment]
I said it before, and will repeat it once: both new and modified files are seen by Git here. And apparently this experience is shared with millions other Git for Windows users, too. Otherwise this bug tracker would fill up pretty quickly with complaints about it.

There must be something in your use case that's uncommon. And nobody else but you has a chance to figure out what that something is.

**Comment by GabriG86** [comment]
Fine. Thanks

**Comment by dscho** [comment]
Have you looked if you can clone, say, https://github.com/git-for-windows/build-extra, modify the `README.md` by adding a few characters, and if `git status` _still_ shows no modifications?

**Comment by GabriG86** [comment]
I am sorry for the deleyed responce. I can see the modifications in README.md after cloning this repository. What I do not understand now is the following. If I clone my repository I can see the modifications on a Mac, but by cloning it into WIN I cannot see them. Thanks for the help.

**Comment by dscho** [comment]
> If I clone my repository I can see the modifications on a Mac, but by cloning it into WIN I cannot see them.

So it _is_ repository-specific. You could try to use [`git fast-export --anonymize`](https://git-scm.com/docs/git-fast-export#Documentation/git-fast-export.txt---anonymize) and import the result into a fresh repository, to see whether it reproduces the issue. If it does, you could then try to reduce the scope (e.g. by restricting the number of commits and the paths processed by `fast-export`), all while retaining the reported issue. Once you have a small example, you either will figure out what is going wrong yourself, or you can then post the result and ask others for help.

**Comment by dscho** [comment]
Closing as stale.
