### ISSUE TITLE
vim uses unix style EOL which breaks plugin usage and conflicts with native vim

### ISSUE THREAD

**Issue by rmrfchik** [git-for-windows/git#364]
Vim shipped with git uses unix style EOL. 
Git uses windows style EOL (it can be configured, but convenient way is to use windows styIe on Windows).
if user want to use plugin manager (for example vim-plug) with shipped vim, it will break vim experience:
vim uses git to checkout plugin, git uses CRLF, vim can't load checkouted plugin.

**Comment by dscho** [comment]
Isn't this a duplicate?

**Comment by rmrfchik** [comment]
Did some digging and found https://github.com/git-for-windows/git/issues/272
Issue is closed, but what is resolution? seems like MSYS2-packages/vim isn't fixed.
So, "won't fix", "invalid", "resolved"?

**Comment by dscho** [comment]
More like "help wanted": https://github.com/git-for-windows/git/issues/272#issuecomment-137661438

**Comment by rmrfchik** [comment]
Well, trying to fix using instructions in #272:
```
paul@nb-paulu MSYS /
$ cd /usr/src/MSYS2-packages/vim

paul@nb-paulu MSYS /usr/src/MSYS2-packages/vim (master)
$ makepkg -s
==> ОШИБКА: Не удалось найти исполняемый файл strip, необходимый для очистки объектных файлов.

paul@nb-paulu MSYS /usr/src/MSYS2-packages/vim (master)
$ strip
bash: strip: команда не найдена

paul@nb-paulu MSYS /usr/src/MSYS2-packages/vim (master)
$
```
The error is _command not found_. There is `strip` in mingw thought:
```
paul@nb-paulu MINGW64 /usr/src/MSYS2-packages (master)
$ strip --version
GNU strip (GNU Binutils) 2.25.1
Copyright (C) 2014 Free Software Foundation, Inc.
```
Any ideas?

**Comment by dscho** [comment]
You need to install `binutils` via

```sh
pacman -S binutils
```

(I thought that the Git for Windows SDK already installed that by default.)

**Comment by dscho** [comment]
I fixed the comment as well as the wiki page about Package management.

**Comment by rmrfchik** [comment]
Sorry, I'm very new to windows git sdk and msys, so I can't handle it correctly

paul@nb-paulu MSYS /usr/src/MSYS2-packages/vim (master)
$ git pull
Already up-to-date.

paul@nb-paulu MSYS /usr/src/MSYS2-packages/vim (master)
$ LANG=C makepkg -s
==> Making package: vim 7.4.728-1 (Fri Sep 11 09:24:38 MSK 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> ERROR: vim-7.4.728.tar.xz was not found in the build directory and is not a URL.

paul@nb-paulu MSYS /usr/src/MSYS2-packages/vim (master)

**Comment by dscho** [comment]
Have a look in the `PKGBUILD` file. It should be relatively easy to follow where the URL is specified from which it tries to download the `vim` sources. It is quite possible that they are no longer available at that version, so you could simply try to upgrade to a newer version. Just find out what the newest version is from `vim`'s home page and adjust the URL accordingly.

**Comment by dscho** [comment]
Please note that upstream just updated vim to a newer version. You might want to verify first that the newer version *still* exposes the problem (call `pacman -Syu` in your SDK to update all packages to the current version), and if it does, you need to `git pull origin master` in `/usr/src/MSYS2-packages/` first, before calling `makepkg -s` in the `vim/` subdirectory again.

**Comment by dscho** [comment]
As of `vim-7.4.872-2`, this is fixed.
