### ISSUE TITLE
Skipping during rebase is slow

### ISSUE THREAD

**Issue by kgybels** [git-for-windows/git#365]
Noticed that doing `git rebase --skip` is slower using `v2.5.1.windows.1` (5s vs 1m40s in one case). 

[`Updating the index`](/git-for-windows/git/blob/v2.5.1.windows.1/git-am.sh#L617) is taking a long time, because the timestamps in the index are all zero, as a result of the [`read-tree`](/git-for-windows/git/blob/v2.5.1.windows.1/git-am.sh#L515) introduced in this [commit](/git/git/commit/f8da6801e2fb3e46a42031b860c6411ef76a0335#diff-e2c10c7cecbd7bb6a9f27ba9c0db7213).

Currently, I am using this local fix:

    KGybels@PC-KG MINGW64 /mingw64/libexec/git-core
    $ diff -u git-am.backup git-am
    --- git-am.backup       2015-08-30 17:20:08.000000000 +0200
    +++ git-am      2015-09-08 16:09:11.719668300 +0200
    @@ -512,7 +512,7 @@
                    git read-tree --reset -u $head_tree $head_tree &&
                    index_tree=$(git write-tree) &&
                    git read-tree -m -u $index_tree $head_tree
    -               git read-tree $head_tree
    +               git read-tree -m $head_tree
                    ;;
            ,t)
                    if test -f "$dotest/rebasing"

Hopefully, this will be fixed in `v2.6` because [git-am](/git/git/blob/v2.6.0-rc0/builtin/am.c) has now become a builtin.

**Comment by dscho** [comment]
Does t4151 still pass with that patch?

> Hopefully, this will be fixed in v2.6 because git-am has now become a builtin.

Unlikely, without your help, because @pyokagan introduced the `read-tree` call in preparation for making it a builtin.

Please do not just wait for things to become better magically. You obviously have the talents to contribute. So if you want something to happen, just make it so.

**Comment by kgybels** [comment]
@dscho 
>Does t4151 still pass with that patch?

I had some time to try the _Git for Windows SDK_ for the first time.
If I'm doing this right, then the answer is: yes, t4151 still passes with that patch.

    KGybels@PC-KG MINGW64 /usr/src/git (master)
    $ git diff
    diff --git a/git-am.sh b/git-am.sh
    index b66fc2b..f4061e1 100755
    --- a/git-am.sh
    +++ b/git-am.sh
    @@ -512,7 +512,7 @@ then
                    git read-tree --reset -u $head_tree $head_tree &&
                    index_tree=$(git write-tree) &&
                    git read-tree -m -u $index_tree $head_tree
    -               git read-tree $head_tree
    +               git read-tree -m $head_tree
                    ;;
            ,t)
                    if test -f "$dotest/rebasing"
    
    KGybels@PC-KG MINGW64 /usr/src/git (master)
    $ make
        GEN git-am
        BUILTIN all
        SUBDIR git-gui
        SUBDIR gitk-git
        SUBDIR perl
    Manifying 8 pod documents
        SUBDIR templates
    
    KGybels@PC-KG MINGW64 /usr/src/git (master)
    $ cd t
    
    KGybels@PC-KG MINGW64 /usr/src/git/t (master)
    $ ./t4151-am-abort.sh
    ok 1 - setup
    ok 2 - am stops at a patch that does not apply
    ok 3 - am --skip continue after failed am
    ok 4 - am --abort goes back after failed am
    ok 5 - am -3 stops at a patch that does not apply
    ok 6 - am -3 --skip continue after failed am -3
    ok 7 - am --abort goes back after failed am -3
    ok 8 - am -3 --skip removes otherfile-4
    ok 9 - am -3 --abort removes otherfile-4
    ok 10 - am --abort will keep the local commits intact
    ok 11 - am -3 stops on conflict on unborn branch
    ok 12 - am -3 --skip clears index on unborn branch
    ok 13 - am -3 --abort removes otherfile-4 on unborn branch
    ok 14 - am -3 --abort on unborn branch removes applied commits
    ok 15 - am --abort on unborn branch will keep local commits intact
    # passed all 15 test(s)
    1..15
    
    KGybels@PC-KG MINGW64 /usr/src/git/t (master)
    $ git rev-parse HEAD
    a6803cd62bba2238d6d42115f6db9d8e22811a54

>Unlikely, without your help, because @pyokagan introduced the read-tree call in preparation for making it a builtin.

I didn't know it was in preparation for making it a builtin, the [commit message](/git/git/commit/f8da6801e2fb3e46a42031b860c6411ef76a0335) says it is to support unborn branches.

>Please do not just wait for things to become better magically. You obviously have the talents to contribute. So if you want something to happen, just make it so.

I don't believe in magic either. I had a look at the builtin implementation of git-am and if I understand the code correctly, then this problem is not present.

`am_skip` calls [`clean_index(head, head)`](/git/git/blob/v2.6.0-rc0/builtin/am.c#L2081).
The call to [`merge_tree(remote_tree)`](/git/git/blob/v2.6.0-rc0/builtin/am.c#L2046) in `clean_index` is the equivalent for [`git read-tree $head_tree`](/git/git/blob/v2.6.0-rc0/contrib/examples/git-am.sh#L515) in the script. However, unlike the script it does specify [opts.merge = 1;](/git/git/blob/v2.6.0-rc0/builtin/am.c#L1999)

If I have more time, I will try testing the builtin to see if it works. I logged this issue before doing all the extra work, because it might already help out other people.

**Comment by pyokagan** [comment]
Hi @kgybels ,

> Updating the index is taking a long time, because the timestamps in the index are all zero, as a result of the read-tree introduced in this commit.

Ah, right >< Sorry for the mess.

> Currently, I am using this local fix:

Yes, this fix is correct, because as you already found out it sets opts.merge = 1;

> I don't believe in magic either. I had a look at the builtin implementation of git-am and if I understand the code correctly, then this problem is not present.

It *was* present, but thankfully Linus noticed it and it got fixed in https://github.com/git/git/commit/3ecc7040eff29fea0051df9faf21b0a73ee6d911

Those who are staying on 2.5 would still be affected though, so since you have done all the work already, would you like to submit your patch upstream to the [Git mailing list](https://github.com/git/git/blob/master/Documentation/SubmittingPatches) so that we can hopefully get this fix into the 2.5.2 maintenance release? [submitGit](https://submitgit.herokuapp.com/) may help.

Thanks again!

**Comment by dscho** [comment]
> Those who are staying on 2.5 would still be affected though, so since you have done all the work already, would you like to submit your patch upstream to the Git mailing list so that we can hopefully get this fix into the 2.5.2 maintenance release?

Yes, I agree.

@kgybels it would have been nice to get a contribution from you, e.g. as a Pull Request. Next time, maybe? I would help you to get the contribution upstream, of course.

For now, I committed it myself (when I really should have worked on three other critical bugs...).

**Comment by kgybels** [comment]
@dscho 
> it would have been nice to get a contribution from you, e.g. as a Pull Request. Next time, maybe?

I'm still learning how to correctly contribute. I'm already familiar with GitHub, but contributing to Git is different than what I'm used to.

I also didn't know what to do with my fix, because the problem is already fixed in git@master, it seemed silly to submit a patch for what is now just an example shell script.

I was wondering where you got kim.gybels@engilico.com from? I prefer to use kgybels@infogroep.be.

@pyokagan
>get this fix into the 2.5.2 maintenance release? submitGit may help.

 Thank you, I will definitely try out submitGit. On which branch do I need to base my work to get this fix in the 2.5.2 maintenance release?

**Comment by kgybels** [comment]
>On which branch do I need to base my work to get this fix in the 2.5.2 maintenance release?

@pyokagan After reading the fine documentation, I figured out that the answer to my own question is 'maint'.

I was just wondering, do I still need to submit my patch to 'maint'? Or will @dscho's commit to 'master' be put on both 'master' and 'maint'?

**Comment by dscho** [comment]
> I'm still learning how to correctly contribute. I'm already familiar with GitHub, but contributing to Git is different than what I'm used to.

Yep,  I figured from your GitHub profile.

FWIW in the Git for Windows project, we follow the GitHub Pull Request workflow. You can always submit patches to the Git for Windows project first and I'll try my best to "trickle them upstream".

> I also didn't know what to do with my fix, because the problem is already fixed in git@master, it seemed silly to submit a patch for what is now just an example shell script.

There are multiple branches, and you can easily base any topic branch on a tag.

> I was wondering where you got kim.gybels@engilico.com from? I prefer to use kgybels@infogroep.be.

I stole that from your recent [Pull Request to `gitextension`](https://github.com/gitextensions/gitextensions/pull/2937) (which made me very excited, BTW, because it seems you know more about WiX than I do, and I might be able to learn a ton from you).

> I will definitely try out submitGit.

Whoops, sorry... I already took this route: https://submitgit.herokuapp.com/git/git/pull/173 and https://github.com/git/git/pull/173...

**Comment by kgybels** [comment]
>Whoops, sorry... I already took this route: https://submitgit.herokuapp.com/git/git/pull/173 and git#173...

So there is nothing else left to do for this issue, right? Just want to make sure.
