### ISSUE TITLE
Git error.

### ISSUE THREAD

**Issue by caohuang1989** [git-for-windows/git#3660]
![Untitled](https://user-images.githubusercontent.com/74083794/151516025-66045768-a7d9-4698-9b0d-6a4c54b21629.png)
------------------------------

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
    It is 64 bit.
```
$ git --version --build-options

C:\Users\Office>git --version --build-options
git version 2.35.0.windows.1
cpu: x86_64
built from commit: 853373155dce195a91e6e41a58c8b8e5c5a94652
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1466]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled


 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using TortoiseGit for windows.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

**Comment by dscho** [comment]
This report is very unclear. What is the problem?

**Comment by caohuang1989** [comment]
hello.
I can't input access token into git

**Comment by caohuang1989** [comment]
Following is error message.
How can I set the access token in git.

=======================================
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/devnsw/nsw-user/'


git did not exit cleanly (exit code 128) (81718 ms @ 1/28/2022 6:49:30 PM)

**Comment by dwettstein** [comment]
Hey @caohuang1989 

This has nothing to do with GitForWindows. It's because GitHub doesn't allow password authentication anymore, as you can read in the blog article.

I would suggest to use an SSH key for authentication. Otherwise, you can also create a personal access token (see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

Cheers

**Comment by dscho** [comment]
> I would suggest to use an SSH key for authentication. Otherwise, you can also create a personal access token

Or just use Git Credential Manager. That's by far the most convenient option I know.
