### ISSUE TITLE
Opening files by ctrl-clicking it Git Bash does not work because of removed backslashes

### ISSUE THREAD

**Issue by paranoiq** [git-for-windows/git#3665]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1466]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue?

```
Ctrl-clicking a file path with backslashes
```
eg:
![image](https://user-images.githubusercontent.com/146912/151660698-a24f770d-4c20-48a2-8a53-4326225671d4.png)

 - What did you expect to occur after running these commands?

the file would open

 - What actually happened instead?

file path is crippled by removing backslashes and does not open

eg: 
![image](https://user-images.githubusercontent.com/146912/151660740-55f1d2ad-4ccc-4110-b986-8bb042c021bc.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

it is a general problem

**Comment by dscho** [comment]
Does this also happen with [msys2](https://msys2.github.io/)? And if yes, does it happen in [Cygwin](https://cygwin.com/) when you open a MinTTY?

**Comment by rimrul** [comment]
Closing as stale
