### ISSUE TITLE
ls not recognized on windows 10 cmd line

### ISSUE THREAD

**Issue by impfireball** [git-for-windows/git#3666]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options
2.35.1.windows.1  
** insert your machine's response here **

'ls' is not recognized as an internal or external command,
operable program or batch file.
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windows 10
```
$ cmd.exe /c ver

'cmd.exe' is not recognized as an internal or external command,
operable program or batch file.

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Components;
- Windows Explorer Integration
 - Git Bash here
 -Git GUI here
- Git LFS 
- Associate .git* configuration files with the default text editor
- ASsociate .sh files to be run with Bash

Default Editor;
- Vim

Initial Branch name after Git Init;
- Let Git decide ("master")

Path Environment, or using Git from the commmand line;
- Git from the command line, and also from 3rd party software (middle option)

HTTPS transport backend;
- Use the OpenSSL library

Configuring line ending conversions;
- Checkout Windows-style, commit Unix-style line endings

Configuring the terminal emulator to use with Git Bash;
- Use Windows' default console window

Git pull behavior;
- Default (fast-forward or merge)

Credential manager;
- None

Extra options;
- Enable file system caching

Experimental options;
- Enable experimental built-in file system monitor

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
C:\Program Files\Git\etc\install-options.txt
bash: C:Program: command not found

C:\Program Files (x86)\Git\etc\install-options.txt
bash: syntax error near unexpected token `('

 %USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt
bash: fg: %USERPROFILE%AppDataLocalProgramsGitetcinstall-options.txt: no such job

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

windows CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

expected to be able to run commands like 'ls' from cmd line, as demonstrated in a youtube lecture video on git commands

 - What actually happened instead?

** insert here **

It just said you cannot do that.  Dunno why.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by rimrul** [comment]
> Path Environment, or using Git from the commmand line;
> - Git from the command line, and also from 3rd party software (middle option)

To run `ls` from cmd you want the third option.

**Comment by impfireball** [comment]
"Warning: This will override Windows tools like 'find' and 'sort'.  Only use this option if you understand the implications."

**Comment by impfireball** [comment]
It works now though, so thank you for that!
