### ISSUE TITLE
installing git-sdk-1.0.1-x64 fails due to download package error

### ISSUE THREAD

**Issue by max630** [git-for-windows/git#367]
I tried twice, looks like persistent issue

the error messages are:

error: failed retrieving file 'mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz' from downloads.sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
Could not install the remaining packages

**Comment by max630** [comment]
worked around by manually downloading and copying the file into /var/cache/pacman/pkg

**Comment by nalla** [comment]
Thanks for the report. For future reference [here is the link](http://repo.msys2.org/) to the official msys2 repository.
