### ISSUE TITLE
FSMonitor prevents renaming of the repository folder without killing the right git.exe process from Windows Task Manager

### ISSUE THREAD

**Issue by fourpastmidnight** [git-for-windows/git#3670]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Search terms: `is:issue mv cannot move`

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
2.33.0.windows.2

```

I'm using 64-bit version of Git for Windows.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.804]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash in Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git init management.infrastructure
$ cd management.infrastructure
starting fsmonitor-daemon in .../management.infrastructure
$ cd ..
$ mv management.infrastructure/ management.infrastructure.windows
mv: cannot move 'management.infrastructure/' to 'management.infrastructure.windows/': Device or resource busy

```
 - What did you expect to occur after running these commands?

I expected the folder to be moved/renamed.

 - What actually happened instead?

As can be seen from the sample above, I received an error.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A. The steps above can be repro'd very easily on any repository where the FSMonitor is in use. The simplest repro is:

```
$ cd my-git-repo
starting fsmonitor-daemon in absolute_path_to/my-git-repo
$ cd ..
$ mv my-git-repo my-renamed-git-repo
```

Just enter the git repo, which starts the `fsmonitor-daemon`, then attempt some file-level operation on the folder housing the repo and this error is triggered.

While the FSMonitor is helpful, it should not stop me from performing other tasks on the repo as a whole. I'm not sure how such an issue might be resolved.

The current "solution" is to kill the `git.exe` executable in Windows Task Mangaer (but, the trick there is you basically have to _guess_ which git process to kill because currently, there are several running because I also have a couple of instances of VS Code running). Once you kill the correct `git.exe` process, one can rename/move the folder. Note that it is not simply enough to exit the current Git Bash shell, as the `git.exe` process running the FSMonitor daemon continues to run even after exiting the Git Bash shell. (Though, I'm unsure if that's as a result of there being other `git.exe` processes running due to VS Code instances running which have spawend other `git.exe` processes, and so the process running the FSMonitor is not stopped when the shell that created it terminates.)

**Comment by jeffhostetler** [comment]
Try upgrading to 2.34 or later.

Prior to that the fsmonitor daemon's CWD was set to the root of the working directory and thus implicitly holding lock on that directory and prevented it from being deleted or moved.

Thanks.

**Comment by fourpastmidnight** [comment]
Ah, thanks @jeffhostetler. I perused the release notes for that release and wasn't sure if that contained a fix for this issue. I'll give that a try and report back.

**Comment by fourpastmidnight** [comment]
OK, I updated to the latest available stable Git for Windows version and this error does not occur anymore. Thanks everybody, closing the issue.

**Comment by jeffhostetler** [comment]
Thanks for the confirmation!
