### ISSUE TITLE
Feature request: call diff drivers with "--quiet" options, if possible?

### ISSUE THREAD

**Issue by adswa** [git-for-windows/git#3673]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 11 Pro for Workstations
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.22000.434]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This issue occurs in conjunction with the tool [git-annex](git-annex.branchable.com/), which is build upon Git and allows to version control large files without checking their content into Git. In the joint Git/git-annex repositories I am cloning, files that correspond to the file types the ``build-extra``'s diff driver [``astextplain``](https://github.com/git-for-windows/build-extra/blob/main/git-extra/astextplain) acts upon (e.g., PDFs) are version-controlled with git-annex instead of Git. In practice, this means that file contents of files managed by git-annex are not locally available after a clone. An explicit ``git-annex get <file>`` retrieves file contents from their remote registered sources. Under the hood, version control works by git-annex committing a pointer to the file content of the file (instead of the file contents), and managing the file's content in its internal object tree within ``.git/annex/objects``. Typically, this works with symlinks, but on Windows, this process involves [additional workarounds](https://git-annex.branchable.com/design/adjusted_branches) which might also confuse the diff drivers.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash or CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone git@github.com:datalad-datasets/machinelearning-books.git
cd machinelearning-books
git annex init
```
 - What did you expect to occur after running these commands?

No more output than the messaging of ``git annex init``.
<details><summary>Typical git annex init output</summary>

```
$ git annex init
init
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.

  Disabling core.symlinks.
starting fsmonitor-daemon in 'C:/Users/datalads/pdftest2'

  Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.

Switched to branch 'adjusted/master(unlocked)'

  Unable to parse git config from origin

  Remote origin does not have git-annex installed; setting annex-ignore

  This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin
ok
(recording state in git...)
```
</details>

 - What actually happened instead?

Internal failures of the [``astextplain``](https://github.com/git-for-windows/build-extra/blob/main/git-extra/astextplain) script bubble up. I don't know all potential causes for these failures, but in the present case, the fact that the file contents of annexed files are not locally available yet is certainly a reason.

<details><summary>A git annex init in a repository with annexed PDFs</summary>

```
datalads@bnbdatalad MINGW64 ~/machinelearning-books (master)
$ git annex init
init
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.

  Disabling core.symlinks.
starting fsmonitor-daemon in 'C:/Users/datalads/machinelearning-books'

  Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.

Updating files: 100% (10/10), done.
Switched to branch 'adjusted/master(unlocked)'
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

  Unable to parse git config from origin

  Remote origin does not have git-annex installed; setting annex-ignore

  This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin
ok
(recording state in git...)
```
</details>

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

An example repository to illustrate the problem is https://github.com/datalad-datasets/machinelearning-books. Commonly, I work with very large repository hierarchies that easily contain hundreds of PDFs. There, the length of emitted syntax errors is quite substantial.

I was wondering whether you would consider the possibility to silence the output of those diff drivers, where their parametrization allows it. For example, patching the ``astextplain`` script like this silences the flood of syntax errors for me.

```diff
adina@muninn in ~/repos/build-extra on git:main
❱ git diff
diff --git a/git-extra/astextplain b/git-extra/astextplain
index ab26ecd..e7d660d 100755
--- a/git-extra/astextplain
+++ b/git-extra/astextplain
@@ -18,7 +18,7 @@ case "$1" in
                docx2txt.pl "$1" -
                ;;
        *.pdf | *.PDF)
-               pdftotext -layout -enc UTF-8 "$1" - | sed "s/(\^M$)|(^\^L)//"
+               pdftotext -q -layout -enc UTF-8 "$1" - | sed "s/(\^M$)|(^\^L)//"
                ;;
        # TODO add rtf support
        *.rtf | *.RTF)
adina@muninn in ~/repos/build
```

Silencing any errors would of cause also conceal errors that have more practical relevance than those that I face, so I am unsure whether my convenience/UX warrants this change. Nevertheless, I reasoned that the work of these scripts is internal, and one may question if a user has the need or means to fix legitimately broken files they are alerted to via such failures. Therefore, I at least wanted to get in touch with this proposal.

**Comment by rimrul** [comment]
I'm not sure if passing `-q` to `pdftotext` is apropriate here or not, but we should probably in some way inform `git diff` about a failed textconv. Instead of having it try to diff the errror messages.

On a different note though, why is `git annex init` running a `git diff` here with external diff drivers on files it knows aren't the types of files `git` would expect to be there?

Would it show an actual diff to the user here with other types of annexed files/on a different filesystem? Or is it trying to generate some diff for scripted use? If it's trying to do the latter, it should probably at least use `--no-textconv` there.

**Comment by adswa** [comment]
I am not sure, but I will file a companion issue with git-annex. Thanks much for your quick response.

**Comment by adswa** [comment]
Filed a companion issue at https://git-annex.branchable.com/bugs/init__58___syntax_warnings_in_diff_driver_on_Windows/

**Comment by rimrul** [comment]
I've thought about this some more and a passing a quiet flag seems to match the spirit of that file and its history. I've created a PR for this.

**Comment by adswa** [comment]
Thanks!
