### ISSUE TITLE
bad sha1 file: .git/objects/xx/desktop.ini

### ISSUE THREAD

**Issue by fnkr** [git-for-windows/git#368]
Git for Windows should ignore Windows system files like `desktop.ini`.

```
.git/objects/xx/desktop.ini
```

```
error: bad ref for desktop.ini
```

**Comment by dscho** [comment]
Whoa.

Now, if you could follow [proper procedures](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) and tell me how to reproduce this issue?

If you went out of your way to direct your Windows Explorer into the *hidden* `.git/` directory, then you probably would agree that this is a really rare problem, and actually self-made...

**Comment by fnkr** [comment]
The problem occurred during a `git gc` and `git prune` and is 100% reproducible if there is a `desktop.ini` in the mentioned locations. I'm not sure why there is a `desktop.ini` (in my case) but in my opinion any application that is running on Windows should be fine with that. The same applies for `thumbs.db` files. These files are part of the operating system and should be handled properly.

**Comment by dscho** [comment]
> if there is a desktop.ini in the mentioned locations

That is the question, indeed. What business does the `desktop.ini` file living there.

> The same applies for thumbs.db files. These files are part of the operating system and should be handled properly.

By that reasoning, the `.DS_Store` files on MacOSX would also need to be excluded explicitly.

Worse, even if you make the argument that you don't care and you just want to have your cookies and stomp on the ground, the simple fact that `desktop.ini` is a perfectly valid branch name makes your wishes moot: we cannot "fix" that.

If you do not believe me, have a look here: https://github.com/dscho/git/tree/desktop.ini

You can even create such a branch yourself:

```sh
$ git checkout -b desktop.ini
```

Summary: You need to find out which program left those files where they don't belong and make them stop.
