### ISSUE TITLE
git p4 commands fail with fatal error.

### ISSUE THREAD

**Issue by rickeerickson** [git-for-windows/git#3680]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** 
git version 2.35.1.windows.1
cpu: x86_64
built from commit: 8084c8c201ddb28eaff22bdd9c8344339eddab73
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon 
**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** 
Microsoft Windows [Version 10.0.18363.2039]
**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

**
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
**
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** None **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**
CMD
**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** 
git p4
git p4 clone
**
```
 - What did you expect to occur after running these commands?

**
I expected help to print.
**

 - What actually happened instead?

**
c:\Program Files\Git>git p4
fatal: 'p4' appears to be a git command, but we were not
able to execute it. Maybe git-p4 is broken?
**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**
None
**

**Comment by dscho** [comment]
From our [Release Notes](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues):

> As Git for Windows is shipped without Python support, `git p4` (which is backed by a Python script) is not supported.

**Comment by dscho** [comment]
There is talk over [in this discussion](https://github.com/git-for-windows/git/discussions/3661) how the situation could be remedied, feel free to contribute your expertise there.
