### ISSUE TITLE
pager hangs when quitting for versions >= 2.35

### ISSUE THREAD

**Issue by codeling** [git-for-windows/git#3683]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
(started seeing this first after installing git 2.35.0)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1466]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not really. Though I did see this behavior only on on 3 out of 4 systems I installed git on - the main differences I can think of at the moment for the system where it *didn't* occur being that it:
  - has a AMD processor instead of intel
  - is _not_ part of a domain (whereas the other 3 ones are)
  - maybe the Win10 versions differs from the one specified above, have to check

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

    Consistently the same problem in Git Bash, Powershell and Command Prompt

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log
```
(and other commands where a pager is involved).

 - What did you expect to occur after running these commands?

    The paging through the log works as expected. When I press 'q', the paging stops immediately and I'm back at the shell prompt

 - What actually happened instead?

    After pressing 'q', the shell is stuck and doesn't react to keypresses for about one minute. Only then the shell prompt comes up again.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

    Happens for any repository.

  - I guess the problem is somehow related to the msys update; so I thought that https://github.com/git-for-windows/git/issues/3657 might be related; but adding `export MSYS=enable_pcon` to `C:\Program Files\Git\etc\git-bash.config` changed nothing.

**Comment by rimrul** [comment]
It might also be related to #3438.

>Though I did see this behavior only on on 3 out of 4 systems I installed git on - the main differences I can think of at the moment for the system where it *didn't* occur being that it:
  - has a AMD processor instead of intel
  - is _not_ part of a domain (whereas the other 3 ones are)
  - maybe the Win10 versions differs from the one specified above, have to check

I don't think these are the cause. I tried it on a 10.0.19044.1415 machine with an i7-10510U,  that's in a domain and it seems to exit normally.

**Comment by codeling** [comment]
> It might also be related to https://github.com/git-for-windows/git/issues/3438.

Yes, that describes a quite similar issue. Only there, it seems to only occasionally happen, and with git < 2.35. For me, it happens every time i exit a pager, and it started to happen consistently when installing 2.35 (just tested: after downgrading to 2.34.1, the problem is gone for me).

**Comment by rimrul** [comment]
A user in that thread describes a workaround:

> Running the pager externally using git --no-pager log --color | less -r seems to work around the issue.

Could you test wether that works around the issue for you?

**Comment by codeling** [comment]
> A user in that thread describes a workaround:
> 
> > Running the pager externally using git --no-pager log --color | less -r seems to work around the issue.
> 
> Could you test wether that works around the issue for you?

No, this has exactly the same issue. Even when just starting less, this happens. So my problem seems to be directly in the `less` executable shipped with versions >= 2.35.0

**Comment by codeling** [comment]
Some more info: I just downgraded to 2.34 as a workaround, but then had the same problem.
I realized I had forgotten during the installation to close a git shell; I think it told me to restart to fix the problem.
But I decided to copy the current installation folder instead, uninstall and re-install, and check the differences. The less.exe is actually not different, but the msys-2.0.dll is. So the problem seems to be in there somewhere. Not sure if that helps, but I wanted to share anyway...

**Comment by dscho** [comment]
@codeling could you please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)? We integrated a couple of fixes that might implicitly address your problem, too.

**Comment by codeling** [comment]
@dscho yes, the pager issue seems fixed!
I do however now get the following message in the shell:
```
bash: /h//.bash_profile: Too many levels of symbolic links
```
H: is a mapped network drive, which is I think set up as home drive - on both affected machines, maybe this has to do with my issue? Accessing /h in the git bash leads to similar problems:
```
$ ls -al /h
ls: /h: Too many levels of symbolic links
ls: cannot open directory '/h': Too many levels of symbolic links
```
I believe accessing /h used to work in previous versions...

**Comment by codeling** [comment]
I have now experimented with setting the `HOME` environment variable in windows. And even with git 2.35.1, when setting the HOME to a folder to some local folder on C drive, the pager doesn't hang.
Strangely enough, the /h drive is actually accessible in 2.35.1 (ls -al /h correctly lists the files there). So I'm thoroughly confused what the actual problem is now:

  - 2.35.1 seems to have a problem with a network drive as home folder (but will happily read from and write to it)
  - the snapshot however seems to have a problem with **accessing** the network drive at all (but it tells about this in a warning message, making it easy to spot)

**Comment by dscho** [comment]
> ls: /h: Too many levels of symbolic links

This might be related to https://github.com/git-for-windows/git/issues/3709#issuecomment-1053764735.

Can you investigate whether [Cygwin](https://cygwin.com) _also_ has the same problem?

**Comment by KevinHake** [comment]
FYI I just built and tested the latest locally (2.35.1.windows.2.7.g158a30d60b), my issue with hang after window resize in pager is fixed.

**Comment by miuliano** [comment]
Running into this myself. There's either a long delay after quitting out of the pager or I need to CTRL-C to get out. Using git version 2.36.1.windows.1, PowerShell 7.2.4. Tried the workaround above and had the same problem

```powershell
> git --no-pager diff master somebranch | & 'C:\Program Files\Git\usr\bin\less.exe' -r
```

also had the same problem piping to `more`, so `less` may not be the culprit here

```powershell
> git --no-pager diff master somebranch | more
```

**Comment by TTT-3** [comment]
In my case the pager I use is `less.exe`, and that is what runs when I type `git log`. When it hangs, if I kill `less.exe` I get my prompt back. I wonder if the bug is actually in `less`?
