### ISSUE TITLE
Executing git <cmd> -h crashes if git doesn't run inside a reporsitory

### ISSUE THREAD

**Issue by dodmi** [git-for-windows/git#3688]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19044.1466]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
I'm using MinGit busybox without installer
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not in my environment. But the problem didn't occur with MinGit 2.34.1 busybox (2.34.1.windows.1)
The problem started with version 2.35.0

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell 5

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
With the commands checkout, fetch, pull, restore, switch, pack-objects, run OUTSIDE of a repository:
git <command> -h 

e.g. git switch -h
```
 - What did you expect to occur after running these commands?

The help for the corresponding command should be displayerd

 - What actually happened instead?

git crashes with error:
BUG: repo-settings.c:23: Cannot add settings for uninitialized repository

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> I'm using MinGit busybox without installer

It also happens with a regular install.

As a matter of fact, it even happens with a Linux version of Git.

**Comment by dscho** [comment]
I opened https://github.com/gitgitgadget/git/pull/1139 and plan on sending it to the Git mailing list as soon as the PR build gives me confidence in addition to the passing test suite on my machine.
