### ISSUE TITLE
Regression : Git bash hangs for commands that need user interactions

### ISSUE THREAD

**Issue by fdiedler** [git-for-windows/git#3699]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
`Git for windows x64 bits`

```
$ git --version --build-options

```
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? 
 `Windows 10 x64`

```
$ cmd.exe /c ver
Microsoft Windows [version 10.0.19044.1526]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

`All default options`

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`Git Bash`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
heroku run php bin/console doctrine:migrations:migrate
```
 - What did you expect to occur after running these commands?

Pressing "y" for "yes" and then the command executes

 - What actually happened instead?

Pressing "y" for "yes" and then Git Bash hangs (no response) and impossible to kill the process with Ctrl + C

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**`This issue does not occur for Git version 2.33.0 x64 bits`**

So I think it is a regression.

Thanks,

**Comment by dscho** [comment]
This issue is listed specifically in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]

**Comment by dscho** [comment]
In case this is not worked around via running it via `winpty`, please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) because we just integrated some fixes that might cover this issue, too.
