### ISSUE TITLE
rebaseall script tries to use ash instead of dash (child_info_fork::abort)

### ISSUE THREAD

**Issue by stahta01** [git-for-windows/git#371]
I just started using "git version 2.5.1.windows.1" and git svn info failed with
"child_info_fork::abort: address space needed by 'msys-svn_wc-1-0.dll' (0x310000) is already occupied".

From the Cygwin FAQ I found I have to use "rebaseall" to fix it.

From dash shell I tried "/bin/rebaseall" but it failed for two reasons.
Windows permission and it tried to use ash instead of dash.
I changed the first line to "#!/usr/bin/dash" by adding the "d"
Can you either add the d upstream or add ash to the install.

The permission issue was solved by adding my user to the Git folder and granting myself modification rights. 

Tim S.

**Comment by dscho** [comment]
This is not Cygwin. So the Cygwin FAQ was not really the appropriate place to look for information. But even so, it probably suggested to call it the way we call it: by using `dash` as the executable and `rebaseall` as the argument.

As a matter of fact, we have precise documentation about the cause and the ways to fix this issue: https://github.com/git-for-windows/git/wiki/32-bit-issues

BTW the reason that `ash` is not installed is that we tried to ship with the *minimal* set of files allowing us to run `rebaseall`. And while `ash.exe` is simply a copy of `dash.exe`, making that copy seemed like unnecessary work given that the recommended way for end users is to fix the DLL address problem is to simply reinstall Git for Windows.
