### ISSUE TITLE
mintty doesn't set terminal io properly

### ISSUE THREAD

**Issue by julie777** [git-for-windows/git#3713]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using?  64-bit
 - Which version of Windows are you running? 10 64-bit

The problem is not with git, but rather with mintty which is used to start git bash. Given that you have a forked copy of msys I am repeating the bug that I created for the msys repo here.

This appears to be a bug in the msys mintty compile. I can run the same version of mintty (3.5.2) from cygwin and it works correctly.

Reproduce by starting MSYS2 MSYS from the start menu on Windows 10. The terminal window opens and bash starts correctly.

Run the windows version of python
```
 python -c "import os,sys; print(os.isatty(sys.stderr.fileno()))"
```
and it returns False. Doing the same thing with cygwin returns True.

Possibly related?
When MSYS bash starts most of the windows path has been removed instead of converted. All that gets converted is
```
/c/Windows/System32
/c/Windows
/c/Windows/System32/Wbem
/c/Windows/System32/WindowsPowerShell/v1.0
```
I don't know if this is by design or a problem.

**Comment by julie777** [comment]
I found the answer. Cygwin has different settings for mintty and I couldn't tell because it doesn't use an ini file for them.

Add `ConPTY=on` to your minttyrc and isatty will be true.

**Comment by dscho** [comment]
An alternative would be to use `winpty`, as outlined in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

Or avoid MinTTY as the installer offers (on the page titled "Configuring the terminal emulator to use with Git Bash"):

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]
