### ISSUE TITLE
Bundled ssh is terminating at Ctrl-C rather than passing it to remote host

### ISSUE THREAD

**Issue by cebu23** [git-for-windows/git#3716]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git-2.35.1.2-64-bit

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Windows 11 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.527]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Running from Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh target-server
```
 - What did you expect to occur after running these commands?
 - What actually happened instead?

The ssh session opens and operates just fine - however, pressing Ctrl-C within an active session (for instance to terminate a long-running command on the target-server) terminates the entire ssh session instead, returning me to the Git bash command prompt.  

Executing `/c/Windows/System32/OpenSSH/ssh` from within the Git bash session works fine, so the issue appears to be with the bundled ssh.  Workaround was to re-install Git for Windows and select the "Use external OpenSSH" option and bypass use of the bundled ssh.

**Comment by rimrul** [comment]
Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html). It should fix the issue.

**Comment by tripl3a** [comment]
Thank you @rimrul, the snapshot fixed it on my machine! 💯

**Comment by cebu23** [comment]
Thanks @rimrul , confirming that the latest snapshot fixed it for me as well.
