### ISSUE TITLE
upgrade to 2.35.1.2 breaks source control section of VSCode

### ISSUE THREAD

**Issue by kaiseruncc** [git-for-windows/git#3723]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?  2.35.1.2

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?  10, 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.1348]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

PS C:\Program Files\Git\etc> cat .\install-options.txt
Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?  

This issue is happening both with repos that were working prior to the upgrade as well as new Repos i'm trying to use in VS Code

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
clone a repo in VS Code 
```
 - What did you expect to occur after running these commands?

be able to use/view features of VSCode Source Control tab

 - What actually happened instead?

Source control section of VSCode broken and not showing branches or remotes.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> `clone a repo in VS Code `

You mean by <kbd>Control</kbd>+<kbd>P</kbd> and then choosing `Git Clone`? That works for me, and the Source Control section totally works for me, too.

**Comment by kaiseruncc** [comment]
Yes even that way.  Also this has impacted other working folders (for other projects) that already had repo's setup correctly prior to the 2.35 upgrade.
