### ISSUE TITLE
[Vim] Git Commit Message Window Changes Vim `fileencodings` Option

### ISSUE THREAD

**Issue by KSR-Yasuda** [git-for-windows/git#3725]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2.7.g158a30d60b.20220224121117
cpu: x86_64
built from commit: 158a30d60b1676f8e52457478eaf7b4db95e9949
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing special.

It makes trouble with Vim plugins, but it is not related with the failure itself.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git commit --allow-empty
# It opens Vim to edit commit message.

# And type vim command `set fileencodings?`
# (Need **`s`** in the tail; not `fileencoding` without `s`).

# Then, it returns `fileencodings=utf-8`.
```

Vim's `fileencodings` (`s` exists) is candidates list for file char code presumptions.
The default value of `fileencodings` is `ucs-bom,utf-8,default,latin1`.

(The opening file encoding, that is probably they care, is `fileencoding` (without `s`) option.)

Although, it resets the option to `utf-8` only.
This means it assume opening file encoding is `utf-8` no matter what char encoding is used the opening file.

Using git command with Vim plugin such as [fugitive][],
it opens the git commit message window in the running Vim process
(e.g. Running `:G commit --allow-empty` Vim command of fugutive).

[fugitive]: https://github.com/tpope/vim-fugitive

Because it overrides `fileencodings` option,
Vim fails file encoding prediction with assuming `utf-8`.

Especially, in Japan, common file encodings are `utf-8`, `cp932` (`sjis`), `euc-jp`, `iso-2202-jp`.
If the file is not `utf-8`, you are forced to see character corruption.

On Ubuntu, it did not happen.
Do they do something about it in Git-for-Windows?

 - What did you expect to occur after running these commands?

Do not change Vim `fileencodings` option.

 - What actually happened instead?

Vim `fileencodings` option is overwrote to `utf-8`.

**Comment by dscho** [comment]
Thank you for the report! I opened a tentative PR at https://github.com/git-for-windows/build-extra/pull/409.

Could you verify that it works as intended (only defaulting to UTF-8, not enforcing it) if you edit `C:\Program Files\Git\etc\vimrc` as administrator and simply remove the `s` from [the `setlocal fileencodings=utf-8` statement](https://github.com/git-for-windows/build-extra/blob/a17cf373fe240e168545038a8cba8906298a7e87/git-extra/vimrc#L39)? (The simplest way to edit it as administrator might be to press the Windows key, type "Git Bash" and then press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> to start it in elevated mode, then run `vi /etc/vimrc`).

**Comment by KSR-Yasuda** [comment]
Yes, it correctly works with leaving `fencs` untouched. Thank you!

**Comment by dscho** [comment]
The build of the `git-extra` package [is running](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=95822&view=results), and any [snapshot ](https://wingit.blob.core.windows.net/files/index.html )created after today should automatically get the fix.

**Comment by KSR-Yasuda** [comment]
The latest release ver.2.35.2.windows.1 (64-bit) seems being without this change.
Is it not applied yet?
Or regression?

**Comment by carenas** [comment]
> Is it not applied yet?

It is applied for future releases as commented above, the following should have it:

  https://wingit.blob.core.windows.net/files/Git-2.36.0-rc1-64-bit.exe

> Or regression?

2.35.3.windows.1 is a maintenance release, so it won't have this fix unless it gets backported to that branch as well, but considering 2.36 is going to be released soon, and you have a very simple workaround, it might not be high priority to do so IMHO

**Comment by KSR-Yasuda** [comment]
I see. Thank you.

**Comment by dscho** [comment]
From what I can tell, Git for Windows v2.36.0 will be available either later today or tomorrow.
