### ISSUE TITLE
Error at tag creation over local network when name includes directory "{dir}/{name}" : cannot lock ref

### ISSUE THREAD

**Issue by pgrmega** [git-for-windows/git#3727]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

(please notice that we tested with older versions like Git 2.15.0.)

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.2565]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The git repository is not stored on the machine but accessed on a shared directory available into the local network.
The error does not occur on other machines accessing the same shared resource, it is to say the only thing is that we created new machines with a more recent OS (Windows Server 2012R2 => Windows Server 2019), all other things being equal.
The error does not occur with a repository locally stored on the machine hard drive. 
The error occurs only for creation of a new tag including a directory : "{dir}/{name}".
It does not occurs if the directory already exists in the ".git\refs\tags".
It does not occurs if we create a tag not including a directory name : "{name}".

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

We use PowerShell.
We tested on Bash/CMD/Powershell and have the same issue.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

PS X:\wa\code-1700_000.dev\relman_tools> git tag -a -m "automatic tag creation"  test_dir/test_tag
fatal: cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory
PS X:\wa\code-1700_000.dev\relman_tools> git tag -a -m "automatic tag creation"  test_dir/test_tag
fatal: cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory
PS X:\wa\code-1700_000.dev\relman_tools> git tag -a -m "automatic tag creation"  test_dir/test_tag
PS X:\wa\code-1700_000.dev\relman_tools>

```
 - What did you expect to occur after running these commands?

We expect the tag to be created.

 - What actually happened instead?

An error : fatal: cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It occurs with any repository.

**Comment by dscho** [comment]
> fatal: cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory

First of all, could you verify that `git for-each-ref` does _not_ contain `refs/tags/test_dir` as a tag?

**Comment by pgrmega** [comment]
Hi,

If I do this just after the error it does not return a line for test_dir.
If I do this after a second try, waiting few seconds, it returns a ref, see belown :
```
PS X:\wa\code-1700_000.dev\relman_tools> git for-each-ref | ?{ $_ -match "test_" }
87cbf7ebe8af210a3fee234dddfba710a70c40f2 tag    refs/tags/test_dir/test_tag
```

**Comment by dscho** [comment]
> But seems that git does not detect it immediately.

Wait, Explorer sees the update immediately, but `git.exe` does not? What does `dir` in a CMD say?

**Comment by pgrmega** [comment]
What we experimented is that explorer sees the update immediately and git complains with this message : "cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory".

Does it means that git does not see the directory immediately or it is another problem ... I can't say. It's a supposition.
CMD => OK
PowerShell => OK

Could it comes from the API used by Git ?

**Comment by dscho** [comment]
> What does `dir` in a CMD say?

The answer to that question would still be quite useful.

> What we experimented is that explorer sees the update immediately and git complains with this message : "cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory".

You could [build a custom Git for Windows](https://github.com/git-for-windows/git/wiki/Building-Git) where you instrument [the code that produces that error message](https://github.com/git-for-windows/git/blob/5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6/refs/files-backend.c#L640-L712) to find out in more detail what is going on. The culprit might be that something like [`EAGAIN`](https://stackoverflow.com/questions/4058368/what-does-eagain-mean) needs to be handled, but isn't.

> CMD => OK
> PowerShell => OK

Are you saying that running `dir` in those works, directly after creating the directory? Or are you saying that the `git` command works? Sorry, this is not clear to me.

**Comment by pgrmega** [comment]
I'll try to be clearer by illustrating with a script and the output.

The script (batch file test.bat executed in the CMD terminal) :
```
x:
cd X:\wa\code-1700_000.dev\relman_tools

for /L %%n in (1,1,3) do (
  echo "------------------------------------------------------------------------
  echo "- ITERATION %%n"
  echo "------------------------------------------------------------------------
  git tag -a -m "automatic tag creation"  test_dir/test_tag
  dir X:\wa\code-1700_000.dev\relman_tools\.git\refs\tags
  timeout 4 > NUL
)
```

The output :
```
X:\wa\code-1700_000.dev\relman_tools>(
echo "------------------------------------------------------------------------
 echo "- ITERATION 1"
 echo "------------------------------------------------------------------------
 git tag -a -m "automatic tag creation"  test_dir/test_tag
 dir X:\wa\code-1700_000.dev\relman_tools\.git\refs\tags
 timeout 4  1>NUL
)
"------------------------------------------------------------------------
"- ITERATION 1"
"------------------------------------------------------------------------
fatal: cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory
 Volume in drive X is Data
 Volume Serial Number is 9422-CEDE

 Directory of X:\wa\code-1700_000.dev\relman_tools\.git\refs\tags

03/16/2022  12:08 PM    <DIR>          .
03/16/2022  12:08 PM    <DIR>          ..
03/16/2022  12:08 PM    <DIR>          test_dir
               0 File(s)              0 bytes
               3 Dir(s)  1,921,131,634,688 bytes free

X:\wa\code-1700_000.dev\relman_tools>(
echo "------------------------------------------------------------------------
 echo "- ITERATION 2"
 echo "------------------------------------------------------------------------
 git tag -a -m "automatic tag creation"  test_dir/test_tag
 dir X:\wa\code-1700_000.dev\relman_tools\.git\refs\tags
 timeout 4  1>NUL
)
"------------------------------------------------------------------------
"- ITERATION 2"
"------------------------------------------------------------------------
fatal: cannot lock ref 'refs/tags/test_dir/test_tag': unable to resolve reference 'refs/tags/test_dir/test_tag': Not a directory
 Volume in drive X is Data
 Volume Serial Number is 9422-CEDE

 Directory of X:\wa\code-1700_000.dev\relman_tools\.git\refs\tags

03/16/2022  12:08 PM    <DIR>          .
03/16/2022  12:08 PM    <DIR>          ..
03/16/2022  12:08 PM    <DIR>          test_dir
               0 File(s)              0 bytes
               3 Dir(s)  1,921,131,630,592 bytes free

X:\wa\code-1700_000.dev\relman_tools>(
echo "------------------------------------------------------------------------
 echo "- ITERATION 3"
 echo "------------------------------------------------------------------------
 git tag -a -m "automatic tag creation"  test_dir/test_tag
 dir X:\wa\code-1700_000.dev\relman_tools\.git\refs\tags
 timeout 4  1>NUL
)
"------------------------------------------------------------------------
"- ITERATION 3"
"------------------------------------------------------------------------
 Volume in drive X is Data
 Volume Serial Number is 9422-CEDE

 Directory of X:\wa\code-1700_000.dev\relman_tools\.git\refs\tags

03/16/2022  12:08 PM    <DIR>          .
03/16/2022  12:08 PM    <DIR>          ..
03/16/2022  12:08 PM    <DIR>          test_dir
               0 File(s)              0 bytes
               3 Dir(s)  1,921,131,622,400 bytes free
```

**Comment by dscho** [comment]
Okay. I fear that the only way to diagnose this better is the approach I detailed above where you rebuild Git after instrumenting it with debug printf statements.

**Comment by dscho** [comment]
> It gave me 20 => ENOTDIR.

Yes, that looks [correct](https://github.com/git-for-windows/git-sdk-64/blob/2362f7168962eb4f3e8df287deb8dfca52f9754b/mingw64/include/errno.h#L43).

> ![image](https://user-images.githubusercontent.com/22399601/158644848-0a4565c9-f4e3-4807-b04e-f26e88fed512.png)
> 
> If you have any idea were to add output

The most promising path forward would be to follow the code path into `files_read_raw_ref()`. Something in there sets that `errno`, and that something might be a function in `compat/mingw.c` that translates the result of `GetLastError()` into a POSIX-style `errno` (and maybe it does so incorrectly).

**Comment by pgrmega** [comment]
Hello,
I've tried to add some informations to understand what is going on.
What I've done is in this patch :
[0001-debug-git-for-windows-git-issue-3727.zip](https://github.com/git-for-windows/git/files/8314856/0001-debug-git-for-windows-git-issue-3727.zip)

Before each test I delete the existing tags and tags directories.

By adding a FindFirstFileW before GetFileAttributesExW in mingw.c , the tag creates without git complaining.
```
$ git tag -a -m "automatic tag creation" test100/test100
[DEBUG] stat_ref_count : 1
[DEBUG] lstat call : .git/HEAD
[DEBUG] lstat > 0
[DEBUG] stat_ref_count : 2
[DEBUG] lstat call : .git/refs/heads/1700_000.dev
[DEBUG] mingw_lstat : .git/refs/heads/1700_000.dev
[DEBUG] mingw_lstat FindFirstFile failed (2)
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 3
[DEBUG] lstat call : .git/refs/HEAD
[DEBUG] mingw_lstat : .git/refs/HEAD
[DEBUG] mingw_lstat FindFirstFile failed (2)
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 4
[DEBUG] lstat call : .git/refs/tags/HEAD
[DEBUG] mingw_lstat : .git/refs/tags/HEAD
[DEBUG] mingw_lstat FindFirstFile failed (2)
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 5
[DEBUG] lstat call : .git/refs/heads/HEAD
[DEBUG] mingw_lstat : .git/refs/heads/HEAD
[DEBUG] mingw_lstat FindFirstFile failed (2)
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 6
[DEBUG] lstat call : .git/refs/remotes/HEAD
[DEBUG] mingw_lstat : .git/refs/remotes/HEAD
[DEBUG] mingw_lstat FindFirstFile failed (2)
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 7
[DEBUG] lstat call : .git/refs/remotes/HEAD/HEAD
[DEBUG] mingw_lstat : .git/refs/remotes/HEAD/HEAD
[DEBUG] mingw_lstat FindFirstFile failed (3)
[DEBUG] mingw_lstat error : 3
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 8
[DEBUG] lstat call : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat FindFirstFile failed (3)
[DEBUG] mingw_lstat error : 3
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 9
[DEBUG] lstat call : .git/HEAD
[DEBUG] lstat > 0
[DEBUG] stat_ref_count : 10
[DEBUG] lstat call : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat FindFirstFile failed (2)
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
```

If I don't do the FindFirstFileW, I have the error
```
$ git tag -a -m "automatic tag creation" test100/test100
fatal: cannot lock ref 'refs/tags/test100/test100': unable to resolve reference 'refs/tags/test100/test100': Not a directory
[DEBUG] stat_ref_count : 1
[DEBUG] lstat call : .git/HEAD
[DEBUG] lstat > 0
[DEBUG] stat_ref_count : 2
[DEBUG] lstat call : .git/refs/heads/1700_000.dev
[DEBUG] mingw_lstat : .git/refs/heads/1700_000.dev
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 3
[DEBUG] lstat call : .git/refs/HEAD
[DEBUG] mingw_lstat : .git/refs/HEAD
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 4
[DEBUG] lstat call : .git/refs/tags/HEAD
[DEBUG] mingw_lstat : .git/refs/tags/HEAD
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 5
[DEBUG] lstat call : .git/refs/heads/HEAD
[DEBUG] mingw_lstat : .git/refs/heads/HEAD
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 6
[DEBUG] lstat call : .git/refs/remotes/HEAD
[DEBUG] mingw_lstat : .git/refs/remotes/HEAD
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 2
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 7
[DEBUG] lstat call : .git/refs/remotes/HEAD/HEAD
[DEBUG] mingw_lstat : .git/refs/remotes/HEAD/HEAD
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 3
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 8
[DEBUG] lstat call : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 3
[DEBUG] lstat < 0
[DEBUG] lstat errno = 2
[DEBUG] stat_ref_count : 9
[DEBUG] lstat call : .git/HEAD
[DEBUG] lstat > 0
[DEBUG] stat_ref_count : 10
[DEBUG] lstat call : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat : .git/refs/tags/test100/test100
[DEBUG] mingw_lstat The first file found is relman_tools
[DEBUG] mingw_lstat error : 3
[DEBUG] lstat < 0
[DEBUG] lstat errno = 20
```

If I try to FindFirstFileW with ".", ".git/refs/tags" or ".git/refs/tags/test100", it fails.
If I FindFirstFileW with ".git/refs/tags/test100/test100" it succeeds.

Anyone having any idea ?

Thank you

**Comment by pgrmega** [comment]
Hello,

I don't know what to do with the result of my analysis.

My conclusion is that the following line consider that any error different from ENOENT leads to the error that I experiment :
https://github.com/git-for-windows/git/blob/158a30d60b1676f8e52457478eaf7b4db95e9949/refs/files-backend.c#L385

whereas ENOENT is caught by the caller :
https://github.com/git-for-windows/git/blob/158a30d60b1676f8e52457478eaf7b4db95e9949/refs/files-backend.c#L640-L642

mingw_lstat seems to consider that ERROR_PATH_NOT_FOUND leeds to ENOTDIR when the parent directory exists in the path given in parameter (this is may case when I create a tag in the form "<parent>/<tag>") :
https://github.com/git-for-windows/git/blob/158a30d60b1676f8e52457478eaf7b4db95e9949/compat/mingw.c#L1059-L1063

In the end, it could mean that ENOTDIR should be managed in the caller of lstat, that is to say files_read_raw_ref or lock_raw_ref.

Do you agree ?

Thank you.

**Comment by dscho** [comment]
> If I replace `if (myerr != ENOENT)` by `if (myerr != ENOENT && myerr != ENOTDIR)` in files-backend.c here :
> 
> https://github.com/git-for-windows/git/blob/158a30d60b1676f8e52457478eaf7b4db95e9949/refs/files-backend.c#L385

That sounds like a really good fix!

Would you mind writing up the problem, the context, and the analysis in a commit message and then open a PullRequest?

**Comment by pgrmega** [comment]
Yes, I will.

**Comment by dscho** [comment]
@pgrmega thank you!

**Comment by pgrmega** [comment]
Hello,

For information...

As I said in the description of the issue, the problem occurs only on our Windows Server 2019 VMs but not on the Windows Server 2012R2.
In parallel of debuging git, which led to the fix I pushed, we had a look on the machine configuration side.

We found that : http://woshub.com/slow-network-shared-folder-refresh-windows-server/.

After applying those commands (that disable caches), the problem disappeared :
```
Set-SmbClientConfiguration -DirectoryCacheLifetime 0
Set-SmbClientConfiguration -FileInfoCacheLifetime 0
Set-SmbClientConfiguration -FileNotFoundCacheLifetime 0
```
