### ISSUE TITLE
error: Could not read 0000000000000000000000000000000000000000 on "git gc"

### ISSUE THREAD

**Issue by cmr-paul-rigas** [git-for-windows/git#3729]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1556]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
"git reflog expire --all" 
```

demonstrates the issue, as does "git gc" (through its use of git reflog expire)

 - What did you expect to occur after running these commands?

Commands before their activities error-free

 - What actually happened instead?

"error: Could not read 0000000000000000000000000000000000000000"

- Additional information:

Git reflog seems to be getting confused by a specific file under [repo]/.git/logs/refs/remotes/origin . This particular file has different capitalisation but otherwise identical spelling to an extant branch.

Removing the offending file under .git/logs/refs/remotes/origin causes the error to no longer be reported and `git reflog` and `git gc` to behave normally. Similarly altering the capitalisation of the filename under [repo]/.git/logs/refs/remotes/origin/  to match that of the existing remote branch name prevents the error. Because this relates to the capitalisation of a filename, I infer that it related to Windows' file system case-insenstivity in some way. I assume the original remote branch was deleted after it had been fetched to my repo and then re-created with identical spelling, but different capitalisation in the affected remote repo.

**Comment by dscho** [comment]
Thank you for the report!

Unfortunately, Git's design originally did not anticipate case-insensitive file systems at all, and it shows. While I would love to see those issues addressed in a systematic manner, I lack the time to do it myself. Do you have some spare time to work on this?

**Comment by dscho** [comment]
Closing as stale.
