### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by Wrathchyld** [git-for-windows/git#3733]
Merge 

_Originally posted by @Wrathchyld in https://github.com/git-for-windows/git/issues/3732#issuecomment-1064885494_ morning01000000000102a9c86f4fdf194555b14bbb2f1fb4e7b670ffa6d103c5688da1625a1ec98926e80100000000ffffffff1073d01e7ec1ce8e24d515dcdfa486a1ec29853e42ee54fdaac3b6d2fa81c3370100000000ffffffff0200e1f5050000000017a9148e702a6a45c38867caf27fda5909e7f06151fac98789d38b8e06000000220020677dc5b4cdd67b0fc82451ecce101af1aa42acbb761b90d4c370c653bac3340e04004730440220425274a7b4a3e6327ebb453a68d9f65c62c4067ac8fc648e92ac07baf7ff346c02205970133adb379839f7b803057c927ee958115e834610de5456e831442921d1150147304402203cf1859a3e3d8644966ff32fefd311db60f86fb63bd1e3a0e97cfe36b895dc7f0220660912a46cfbd824d1701281c300c3452905daf7940214320c426d38857aa32801695221029096d7c0a1214d7d2046294546fa55b9771600b7fae34ef1111110707349f3e421024603562a452e3f8ca2b7132c910354de232e0e557e9b07de3a935585bac6a26f2102926378515ac9831b133eb53801cb16a12fa78d0ac8599ddb58888a37328f7c0353ae040047304402205ae27d6678ecd2e672ef97e8583cb879fa34c05342bc1ccb3da5cf09c261db3302207040477e36a174874de5b33de6827e2ff7f04902dc3c29a73265aea8bd6697200148304502210096f21b7ca576aac71751291270d3ee2789260d136af839154249ba9e9bc6177b0220474d592d5062e2a04b3c7143b463914bdbf022863bf1934c326ad18fb759a01e01695221038ea29f66ffd9828715e02e4125b447a7deb28bf46549bb9112886eaafe7c9a142103cdf2605da5a9d6110fdbd2f6bc3a1af6a05e5ac9dc0bc0e1ffb09bbfd7486b1d210382eaf9693fd796b753176de7f69356d0f213fa21f762fdc96666d6f9417aa53053ae00000000

**Comment by Wrathchyld** [comment]
Help me

**Comment by rimrul** [comment]
> Help me

what do you need help with?

**Comment by Wrathchyld** [comment]
I don't know exactly what I'm doing but I'm trying to transfer crypto or at least verify my crypto.

**Comment by rimrul** [comment]
I don't think we can help you with that. The Git for Windows project doesn't have anything to do with crypto currency. Sorry.
