### ISSUE TITLE
Up/Down arrows don't work when running Git-for-Windows `git log` from Cygwin

### ISSUE THREAD

**Issue by mitchhentges** [git-for-windows/git#3737]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm executing `git` from within a separate Cygwin environment, rather than from a Command Prompt or Git Bash directly.
This is because I'm [shipping a Cygwin-based environment](https://wiki.mozilla.org/MozillaBuild) to end-users, but I'm leaning on the installed Git rather than shipping Cygwin-native `git` so that users' system configuration is used.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Cygwin, with the Command Prompt as the Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

1. [Install Cygwin](https://cygwin.com/install.html) (select any mirror when prompted, otherwise choose all defaults)
2. Run `C:\cygwin-dev\Cygwin.bat`
3. Run the following commands:
```
$ which git # verify that it's pointing to your Git for Windows at something like /cygdrive/c/Program Files/Git/cmd/git
$ git init test-repo
$ cd test-repo
$ git config user.email "a@a.com"
$ git config user.name "user"
$ for i in {1..30}; do echo a >> file && git add . && git commit -m "commit $i"; done
$ git log
# Now, use your up arrow and down arrow keys: instead of moving the pager, you'll hear the "terminal ding" noise instead
```
 - What did you expect to occur after running these commands?

After pressing the down/up arrows, I expect `less` to go down/up one line per-keypress

 - What actually happened instead?

The pager did not move up or down, but a terminal ding did sound off instead

**Comment by dscho** [comment]
Since some of Git for Windows' components (including the pager, `less.exe`) comes from the MSYS2 project and use the MSYS2 runtime (a close derivative of the Cygwin runtime), it is kind of known and expected that Git for Windows and Cygwin do not play well together.

The assumption is that you use Cygwin's _own_ Git instead of Git for Windows. That will improve your experience rather dramatically.

**Comment by dscho** [comment]
Git for Windows' SDK is a close fork of MSYS2, and yes, it has a MINGW version of `git`.

However, for Git's test suite to pass, a couple of patches are required to the MSYS2 runtime, which is why we're not yet at the point where Git for Windows can contribute an always up to date `mingw-w64-git` to the MSYS2 project.

**Comment by rimrul** [comment]
While I can't promise general cygwin compatibility, I think the up/down arrow issue is the same as #3657.

The latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) has a fix for that issue.

**Comment by dscho** [comment]
@rimrul can this be closed?

**Comment by rimrul** [comment]
probably.

**Comment by dscho** [comment]
Thanks!
