### ISSUE TITLE
Upgrade Subversion

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#374]
We are shipping with Subversion 1.8.13 bindings right now, but 1.9.1 is out.

**Comment by dscho** [comment]
Current progress: https://github.com/git-for-windows/MSYS2-packages/compare/master...dscho:subversion

The main problem is `apr` right now: its test suite is failing because it is configured without threads.

**Comment by dscho** [comment]
Oh yeah, mustn't forget: the main reason why I want to rebuild `apr` is because `apr-1-config --link-libtool` prints options including `-R /usr/lib/` which is readily ingested into `serf`'s `/usr/lib/pkgconfig/serf-1.pc` -- which is incorrect because while `libtool` can grok the `-R` option, GCC's linker cannot.

**Comment by nalla** [comment]
@dscho https://github.com/Alexpux/MSYS2-packages/commit/746166913939e7520baddf1e8b8b4fd2e56013bf

**Comment by dscho** [comment]
Indeed! I just saw it...

**Comment by nalla** [comment]
I did a (64bit)
```
/usr/bin/time prove -j 5 --state=failed,save ./t91*.sh
```
against 0c51399ed604ac72935377eb1fba10c69f1bc01a. Seems to introduce no side effects.

**Comment by dscho** [comment]
Thanks for confirming!
