### ISSUE TITLE
East Asian symbols don't display as full width

### ISSUE THREAD

**Issue by blue-wing** [git-for-windows/git#3741]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I'm using the portable installation.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
$ cat ~/.minttyrc
Font=MS Gothic
FontHeight=12
Locale=ja_JP
Charset=UTF-8
```
```
$ locale
LANG=ja_JP.UTF-8
LC_CTYPE="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_ALL=
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

The bug only appears in Bash. CMD works fine.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ echo ☆☆☆
```

 - What did you expect to occur after running these commands?

The output displays correctly in `2.34.1`. This appears to be a regression.
![PortableGit-2 34 1-64-bit](https://user-images.githubusercontent.com/16507492/158419019-2aebbdc1-14d1-4961-91a5-918d062a853e.png)

 - What actually happened instead?

The output displays incorrectly in `2.35.0` and onward. Symbols like `☆` are treated as half width instead of full width despite the locale. Normal text like `あ` still displays correctly.
![PortableGit-2 35 1 2-64-bit](https://user-images.githubusercontent.com/16507492/158418643-a75049db-3b7a-4961-84a8-183500fc7e1f.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Related Mintty ticket: https://github.com/mintty/mintty/issues/615

**Comment by dscho** [comment]
> Related Mintty ticket: [mintty/mintty#615](https://github.com/mintty/mintty/issues/615)

But we're running with a pretty recent MinTTY, way newer than the version that addressed that bug report...

BTW in my MinTTY, those characters seem to be single-width:

![image](https://user-images.githubusercontent.com/127790/158429043-0a0f72a4-6fd9-49ce-b0ea-964a6b38a1a5.png)

**Comment by dscho** [comment]
> BTW in my MinTTY, those characters seem to be single-width:

And the reason might be this part of `~/.minttyrc`:

> ```
> Font=Lucida Console
> ```

So I am unsure whether MinTTY can actually handle character widths that depend on the font?

**Comment by blue-wing** [comment]
I don't think Mintty is the problem because Git `2.34.1` and `2.35.0` use the same Mintty build. I linked to the ticket because it documents how Mintty handles symbols whose widths depend on locale -- sorry if that was confusing.

The font shouldn't be the problem because Mintty forces the width change based on locale.

This behavior has been working correctly for a long time and only broke in the most recent Git version. Maybe something was configured differently in Cygwin.

**Comment by dscho** [comment]
> Seems like adding this line to `~/.minttyrc` fixes the issue.
> 
> ```
> Charwidth=ambig-wide
> ```

Oooh, nice find. I did not even know that existed. And yes, I believe that's the best way to address the issue.

> Feel free to close the issue.

Okay! Thank you for providing such a clear resolution.
