### ISSUE TITLE
bug on invalid path for windows when cherry-picking commits from non-windows devices

### ISSUE THREAD

**Issue by PassionPenguin** [git-for-windows/git#3750]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

NTFS storage restriction

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd, powershell, webstorm-embed, github-embed

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git cherry-pick <hash>
```
 - What did you expect to occur after running these commands?

Cherry pick the commit to the current branch

 - What actually happened instead?

```sh
error: unable to create file article/2021/Which type of loop is fastest in JavaScript?.md: Invalid argument
fatal: cherry-pick failed
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

[xitu/gold-miner](https://github.com/xitu/gold-miner)

**Comment by PassionPenguin** [comment]
i do not have a mac right now so i couldnt have another test...

**Comment by PassionPenguin** [comment]
the hash is ccf457c4

**Comment by dscho** [comment]
> error: unable to create file article/2021/Which type of loop is fastest in JavaScript?.md: Invalid argument

The `?` character is not allowed on Windows. Read: we are not really talking about a bug in Git for Windows, but a problem related to cross-platform development where some non-Windows developers are unaware of file name restrictions.

The easiest way to work around this is to use WSL to cherry-pick, and immediately rename this file, then commit.

More complicated ways involve working on a temporary Git index without a working tree, overriding `core.protectNTFS`. If you have no access to WSL, that might be the necessary.

**Comment by PassionPenguin** [comment]
> > error: unable to create file article/2021/Which type of loop is fastest in JavaScript?.md: Invalid argument
> 
> The `?` character is not allowed on Windows. Read: we are not really talking about a bug in Git for Windows, but a problem related to cross-platform development where some non-Windows developers are unaware of file name restrictions.
> 
> The easiest way to work around this is to use WSL to cherry-pick, and immediately rename this file, then commit.
> 
> More complicated ways involve working on a temporary Git index without a working tree, overriding `core.protectNTFS`. If you have no access to WSL, that might be the necessary.

i tried to override `core.protectNTFS` but failed....

thank for your answer, and i will simply create a new file without the suffix ?
