### ISSUE TITLE
empty git version in Git Gui & Git Bash!!!

### ISSUE THREAD

**Issue by twinskds** [git-for-windows/git#3759]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
This is Git Bash:
$ git --version --build-options
dongseok.kim@WMRRD11-NA1057G MINGW64 /
$ git --version --build-options

dongseok.kim@WMRRD11-NA1057G MINGW64 /
$

This is Git Cmd :
C:\Users\admin>git --version --build-options
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

C:\Users\admin>
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

dongseok.kim@WMRRD11-NA1057G MINGW64 /
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1083]

dongseok.kim@WMRRD11-NA1057G MINGW64 /

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash/CMD/PowerShell/Git cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
https://github.com/desktop/desktop/issues/14193

Git-gui.exe -> pop up window below
fatal error occures
Cannot parse Git version string:

git-bash -> empty stdout(empty)
dongseok.kim@WMRRD11-NA1057G MINGW64 /
$ git --version

dongseok.kim@WMRRD11-NA1057G MINGW64 /
$

```
 - What did you expect to occur after running these commands?

```
Git version output to stdout, like Git cmd.
 
Git-cmd -> git version output OK
C:\Users\admin>git version
git version 2.35.1.windows.2

C:\Users\admin>
```

 - What actually happened instead?

```
empty git version output in bash but stdout redirection to file , we find the output well. 

dongseok.kim@WMRRD11-NA1057G MINGW64 /
$ git --version

dongseok.kim@WMRRD11-NA1057G MINGW64 /
$ git --version > 1

dongseok.kim@WMRRD11-NA1057G MINGW64 /
$ cat 1
git version 2.35.1.windows.2

dongseok.kim@WMRRD11-NA1057G MINGW64 /
$

```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by rimrul** [comment]
This sounds related to #3583.

Could you check if you have some anti-malware software interfering with gits output?

**Comment by twinskds** [comment]
> This sounds related to #3583.
> 
> Could you check if you have some anti-malware software interfering with gits output?

Thanks!
I'll ask to my company.

**Comment by twinskds** [comment]
@rimrul @dscho 
It was blocked by the company's security program.
Thanks for your help.
