### ISSUE TITLE
Error in startup script for GIT GUI (v.2.5.2)

### ISSUE THREAD

**Issue by johngraciliano** [git-for-windows/git#376]
After installing v2.5.2 (64-bit), I tried executing GIT GUI from windows menu and I received back an error message:
>**Error in sartup script**
>couldn't read file "C:\Progam Files\Git\cmd\mingw64\libexec\git-core\git-gui": no such file or directory

Indeed the reference is bad because there is no *cmd* between *Git* and *mingw64*.

**Comment by dscho** [comment]
Thanks for the report; I can reproduce the issue!

**Comment by dscho** [comment]
I will see how many other problems need hotfixes, and release a new version soon.

In the meantime, as a work-around you could right-click on the `Git GUI` shortcut (you can right-click the icon in the Windows menu and open the file location to get there), select `Properties...` and change the `Target:` from

```
"C:\Program Files\Git\cmd\git-gui.exe"
```

to

```
"C:\Program Files\Git\cmd\git.exe" gui
```

It will open an ugly, unnecessary console until the next Git for Windows version is available, but at least it will work until then.

**Comment by Beanow** [comment]
For the equivalent of this workaround for the explorer integration:

Run `regedit.exe`,
Change `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\Background\shell\git_gui\command\(Default)`
from `"C:\Program Files\Git\cmd\git-gui.exe" "--working-dir" "%v."`
to `"C:\Program Files\Git\cmd\git.exe" "gui" "--working-dir" "%v."`
