### ISSUE TITLE
defaulting TERM to xterm-256color causes some remote curses app (over git's ssh) to lose arrow keys

### ISSUE THREAD

**Issue by leonyu** [git-for-windows/git#3760]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

    * Bug can be reproduced with
      * PowerShell 5 or CMD inside Windows Terminal 
      * PowerShell 5 or CMD inside vanilla Windows console
      * Git-bash inside Windows Terminal
    * Working combination
      * Git-bash inside Mintty

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```sh
ssh some-linux-server

echo $TERM # output: xterm-256color

find | less # observe that up/down does not work
htop # observe that up/down does not work

find | TERM=cygwin less # observe that up/down arrow keys work
TERM=cygwin htop # observe that up/down arrow keys work
```
 - What did you expect to occur after running these commands?

    * I expect up/down key to work for `less` or `htop` for all combinations of term & shell, remote or local
    * TERM setting to be correctly set for remote ncurses application to work
    * TERM should probably be `cygwin` if terminal is not mintty

 - What actually happened instead?

    * Incompatible TERM setting causing remote curses apps to not work
    * Namely arrow keys no longer work in remote `less` or `htop` over ssh

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

--- 

* Remote `vim` appears to work fine
* I remember previously git system's TERM was set to `cygwin`
* OpenSSH client from Microsoft (via WindowsCapability) does not have this issue

**Comment by dscho** [comment]
Thank you for reporting this issue. Could you check whether the same issue occurs if you do this using [Cygwin](https://cygwin.com/) instead of Git Bash?

**Comment by leonyu** [comment]
Interesting, Cygwin works for all combinations, and it defaults to `xterm-256color` as well. 

* Cygwin Terminal, invoke `ssh` - TERM=xterm 
* PowerShell inside Windows Terminal, invoking `C:\cygwin\bin\ssh.exe` - TERM=xterm-256color
* PowerShell inside vanilla console, invoking `C:\cygwin\bin\ssh.exe` - TERM=xterm-256color
* CMD inside vanilla console, invoking `C:\cygwin\bin\ssh.exe` - TERM=xterm-256color

Just installed cygwin - version: `CYGWIN_NT-10.0 neptune 3.3.4(0.341/5/3) 2022-01-31 19:35 x86_64 Cygwin`

**Comment by dscho** [comment]
Thank you for verifying that. Next stop: [MSYS2](https://msys2.github.io/). Would you kindly test with that, too? That would be very helpful.

**Comment by leonyu** [comment]
MSYS2 works for all combinations, and it defaults to `xterm-256color` as well.

MSYS2 Terminal (mintty), invoking `ssh` - TERM=xterm
PowerShell inside Windows Terminal, invoking `C:\msys64\usr\bin\ssh.exe` - TERM=xterm-256color
PowerShell inside vanilla console, invoking `C:\msys64\usr\bin\ssh.exe` - TERM=xterm-256color
CMD inside vanilla console, invoking `C:\msys64\usr\bin\ssh.exe` - TERM=xterm-256color

Just installed MSYS2- version: `MINGW32_NT-10.0-19044 machine-name 3.3.4-341.x86_64 2022-02-15 17:24 UTC x86_64 Msys`

**Comment by leonyu** [comment]
Breakage happened between RC0 and RC1
* Git for Windows 2.34.1 (GOOD)
* Git for Windows 2.35.0-rc0 (GOOD)
* Git for Windows 2.35.0-rc1 (BAD)

**Comment by rimrul** [comment]
I think this could be the same issue as #3657.

Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by leonyu** [comment]
Thanks, it is same issue. Fixed for both local `less` and remote `less` and `htop`. 

Closing since fix has been committed.
