### ISSUE TITLE
Backslashes are eaten in `.gitconfig` but not with the `-c` switch

### ISSUE THREAD

**Issue by signed-log** [git-for-windows/git#3765]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.556]
```
(NOTE: Wrongly reports as Windows 10, I am on Windows 11)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell 5 and 7

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh-keygen -f ~/.ssh/ssh_key
# Add this key to your ssh remote
# Set core.sshCommand globally (make sure to escape the "\")
git config --global core.sshCommand "ssh -i C:\\Users\\example\\.ssh\\ssh_key"
# Make sure that the escaping is preserved, if it isn't re-escape it
type ~/.gitconfig
git clone <ssh-remote>
# Returns : 
# Warning: Identity file C:Usersexample.sshssh_key not accessible: No such file or directory.
```

 - What did you expect to occur after running these commands?

Escaping to be taken into account and ssh recieving correct path (`C:\Users\example\.ssh\ssh_key`)

 - What actually happened instead?

ssh recieved the `C:Usersexample.sshssh_key` without the escaped backslashes

- Note :

Using the same config command at clone time with 
```
git -c core.sshCommand="ssh -i C:\\Users\\example\\.ssh\\ssh_key" clone <ssh-remote>
``` 
works normally and ssh recieve the correct path

**Comment by signed-log** [comment]
> Therefore, I believe that you will need to either use forward-slashes (easy solution)

Tried it, not working, Windows def needs those backslashes

> or escape the backslashes by the escape character (read: use quadruple backslashes, i.e. C:\\\\Users\\\\example\\\\.ssh\\\\ssh_key) when using the global config.

This work, I believe that that should be noted (if there is) in the doc for git-for-windows

**Comment by dscho** [comment]
Excellent. Since the question is answered, I will close this ticket.
