### ISSUE TITLE
Lines after SET /P in bat script are not working in latest git version

### ISSUE THREAD

**Issue by Kusuma-Yadav** [git-for-windows/git#3766]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
I chose defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Im seeing this issue only in latest git version i.e., git version 2.35.1.windows.2

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
First upgraded git to latest version
Opened git bash and executed .bat files which are having SET /P command

Ex: I ran following file in git bash
./test.bat

@echo OFF
call git version
echo line before set command
SET /P name= Enter your name: 
echo Name is: %name%
echo script not working
 
```
 - What did you expect to occur after running these commands?
I expected the bat script to print the name user entered for SET /P command

 - What actually happened instead?
Batch script stopped working after taking user input and showed blinking cursor for hours
ctrl +c used to terminate the process is also not working so forcefully closed the git bash.
After few workarounds I found that lines in bat scripts after SET /P command stopped working in git bash
Same script is working fine in older git version and in cmd prompt

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Issue is occurring in all git bash after upgrading to latest version

Output image:
![gitbash](https://user-images.githubusercontent.com/62874772/161503856-3cb21b47-c949-420f-a1b8-e20f9b152728.jpg)

**Comment by dscho** [comment]
I have to admit that I did not even know the `/p` option, but it is clearly [described](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1) to set "the value of `<variable>` to a line of input entered by the user."

As to the problem you observed, I believe it is covered in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]

The reason is that `cmd.exe` believes that it has a Win32 Console to work with, and since it is running in Git Bash, it only has a hidden one that was created on-demand (and is not connected to MinTTY's pseudo terminal in any way). You need to use `winpty` to create an instance of such a Win32 Console and to interact with it.

**Comment by Kusuma-Yadav** [comment]
Thanks @dscho,  
Selecting **Use Windows default console window** option while installation resolved the issue.
