### ISSUE TITLE
Output of utilities installed by git does not do carriage-return under CMD

### ISSUE THREAD

**Issue by alexolog** [git-for-windows/git#3774]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1526]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Of two machines with similar installation, only one exhibits the issue.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`CMD`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
clear --help
```
But it happens with the output of *all* the utilities in `C:\Program Files\Git\usr\bin`

 - What did you expect to occur after running these commands?

![image](https://user-images.githubusercontent.com/2112513/162265716-9c444c6b-2421-4160-a7f6-199df67e7cad.png)

 - What actually happened instead?

![image](https://user-images.githubusercontent.com/2112513/162265842-8933b1a1-8bce-4cf0-ad66-0161097541e8.png)

This happens with the output of *all* the utilities in `C:\Program Files\Git\usr\bin`

**Comment by dscho** [comment]
Does this also happen with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by alexolog** [comment]
It's a work computer, can't install a snapshot.
But it does not happen on another machine.  Maybe there's a setting?

**Comment by dscho** [comment]
> It's a work computer, can't install a snapshot.

You can always extract a PortableGit.

**Comment by alexolog** [comment]
While playing with the portable snapshot, I noticed that it was only that particular instance of the command window that was exhibiting the issue.  I opened another command widow and the problem did not occur.

Still don't know what caused it in the first place.

**Comment by carenas** [comment]
an incorrectly terminated (ex: crashing) vi or similar console application could have that effect.

since you seem to have all mingw64 commands in your path, calling `reset` might solve it

**Comment by dscho** [comment]
Closing as stale.
