### ISSUE TITLE
git log --invert-grep doesn't seem to work

### ISSUE THREAD

**Issue by emanpal** [git-for-windows/git#3777]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.vfs.0.0
cpu: x86_64
built from commit: 16dbd919ecfd018cd2d5e4cee985b3155ad1e953
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.25092.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

NO

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git.exe --no-pager log --author="\(gittrain\)" --invert-grep -1
```
 - What did you expect to occur after running these commands?

one commit listed, whose author *was not* gittrain

 - What actually happened instead?

one commit was listed, whos author *was* gittrain

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://microsoft.visualstudio.com/DefaultCollection/OS/_git/os.2020

**Comment by dscho** [comment]
As per [the documentation](https://git-scm.com/docs/git-log#Documentation/git-log.txt---invert-grep):

> **`--invert-grep `**
> Limit the commits output to ones with log message that do not match the pattern specified with `--grep=<pattern>`.

And `--author=<pattern>` is _not_ a `--grep` pattern. While it _is_ a regex, it does not grep through the commit message, and `--invert-grep` really is only about that.

Since Git for Windows comes with PCRE support, you could use a negative-lookahead pattern in conjunction with [`--perl-regexp`](https://git-scm.com/docs/git-log#Documentation/git-log.txt--P) to achieve what you want to achieve.
