### ISSUE TITLE
safe.directory setting issue

### ISSUE THREAD

**Issue by DoveBoy** [git-for-windows/git#3787]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.2.windows.1
cpu: x86_64
built from commit: 518ccba2352ce721cabbbf2933869c3c3313d1c3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.22000.593]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

scoop install git
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell7

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
 - What did you expect to occur after running these commands?

The process of `git pull` working properly

 - What actually happened instead?

```
fatal: unsafe repository ('E:\Program Files\Scoop\apps\scoop\current' is owned by someone else) To add an exception for this directory, call:

        git config --global --add safe.directory E:\Program Files\Scoop\apps\scoop\current

```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

The original repo cannot be manipulated by any `git` related command, and must be forced to set `git config --global --add safe.directory` for each repo in order to work, as we currently know from the `2.35.2` update in order to fix a [security issue](https://github.blog/2022-04-12-git-security-vulnerability-announced/). How to set global trust for all repo in `.gitconfig`, instead of having to set it for each repo individually, because there are too many repo's and it's too tedious to set each one.

**Comment by derrickstolee** [comment]
Hello, @DoveBoy. The per-repository assignment is by design. There is no setting to completely ignore this protection.

If you have a list of these repositories, then some automation (such as a shell script) can assist in running these commands.

**Comment by derrickstolee** [comment]
I am working on a modification to `safe.directory` to allow an opt-out of the feature: https://github.com/gitgitgadget/git/pull/1215

**Comment by derrickstolee** [comment]
@t-b: thanks for helping here with an additional symptom. That's actually a problem with the config parser that skips the `safe.directory` key and checks all config values. It's being fixed now.

**Comment by AlexDanault** [comment]
If an option to disable this feature entirely is being worked on, pleanse make sure it also disabled the owner check itself, because on a Windows machine, the owner check crashes when running commands in a command prompt (windows) for anything related to WSL :

```
L:\home\alex\Code\vtcloud>git status
error: failed to get owner for '//wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud' (1)
fatal: unsafe repository ('//wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory '//wsl$/Ubuntu20.04LTS/home/alex/Code/vtcloud'
```

Running the `git config (...)` command als crashes (same message) is ran from a command prompt in a WSL folder. The command works if it is ran from a regular folder, and the config stays, bu has no impact at all, because git crasher at the owner check anyway.

**Comment by gitfool** [comment]
FYI: https://github.com/actions/checkout/issues/760#issuecomment-1098615112
> Looks like with git 2.35.3, git config --global --add safe.directory * will work to opt-out of the safe directory check.
 https://github.com/git/git/commit/1ac7422e39b0043250b026f9988d0da24cb2cb58#diff-c62827315018c95283562ab55db59c26e544debaad579b77a7f96ffed09c45c2R18

**Comment by DoveBoy** [comment]
> Looks like with git 2.35.3, git config --global --add safe.directory * will work to opt-out of the safe directory check.
> [git@1ac7422#diff-c62827315018c95283562ab55db59c26e544debaad579b77a7f96ffed09c45c2R18](https://github.com/git/git/commit/1ac7422e39b0043250b026f9988d0da24cb2cb58#diff-c62827315018c95283562ab55db59c26e544debaad579b77a7f96ffed09c45c2R18)

It would be nice if the update afterwards could really be set up in this way, without being too overbearing

**Comment by DoveBoy** [comment]
> The `safe.directory=*` handling made it into [`v2.35.3.windows.1` (release)](https://github.com/git-for-windows/git/releases/tag/v2.35.3.windows.1), I believe, therefore I am closing this ticket.

Updated git to the latest version
$ git --version --build-options

git version 2.35.3.windows.1
cpu: x86_64
built from commit: b952ed2af65bd726a4d21270bc3911db79873fe2
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

Use `git config --global --add safe.directory=*` to set the error, change it to `git config --global --add safe.directory =*` to set no error, but use git related commands still prompt you must set `safe.directory`

![image](https://user-images.githubusercontent.com/19201447/164125365-2a9a9e1f-1b00-47a9-8e88-213ca03ef14c.png)
![image](https://user-images.githubusercontent.com/19201447/164125231-19e4d38b-b0ae-496c-8a5a-ec4df0f00dfd.png)
![image](https://user-images.githubusercontent.com/19201447/164125510-e172de58-dd19-4328-87e4-e1bc6831ee88.png)
![image](https://user-images.githubusercontent.com/19201447/164125435-dbbd32f7-1386-4fd7-8212-2268b5b4fe31.png)

**Comment by Naine** [comment]
@DoveBoy You do not use an `=` on the `git config` command line:

```
git config --global --add safe.directory *
```

**Comment by DoveBoy** [comment]
> `git config --global --add safe.directory *`

@Naine excellent

**Comment by orgads** [comment]
Better have the `*` quoted:

```
git config --global --add safe.directory '*'
```

**Comment by phil-blain** [comment]
@orgads I saw somewhere else that using the quoted form in CMD resulted in the quotes making it to the config file and so the setting then didn't work. So I would advise to single quote in Git Bash but not in CMD (I'm not sure about PowerShell).

**Comment by orgads** [comment]
Yes, I referred to Git Bash. I'll clarify that in my original message.
