### ISSUE TITLE
Options... Cursor... color setting is ignored if UI theme is not "none"

### ISSUE THREAD

**Issue by mbratch** [git-for-windows/git#3799]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git for Windows 64-bit version 2.35.2

```
$ git --version --build-options
git version 2.35.2.windows.1
cpu: x86_64
built from commit: 518ccba2352ce721cabbbf2933869c3c3313d1c3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? WIndows 11

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.613]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

```
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Nothing in particular

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash with a theme selected for the UI. Note that this issue does not occur if theme "none" is selected.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

No commands were run exactly. When I run Git Bash and select Options... then Cursor... and try to change the cursor color. I select a new color, click Save or Apply. Nothing happens.

 - What did you expect to occur after running these commands?

I expected cursor color to change.

 - What actually happened instead?

Nothing

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

NA

**Comment by rimrul** [comment]
This does seem to work for me. Are you selecting a pre-defined colour on the left or adding a custom colour from the right?
And if you're adding a custom colour, do you click "add colour" on the bottom right and then select it on the bottom left?

**Comment by mbratch** [comment]
Thanks for the quick reply! It doesn’t seem to matter whether I choose a pre-defined or custom color. Also, I can save a custom color (“add color”) at the bottom, but if I exit Git Bash and restart it, it doesn’t remember my custom color addition. Sent from Mail for Windows From: Matthias AßhauerSent: Thursday, April 14, 2022 12:54 PMTo: git-for-windows/gitCc: Mark Bratcher; AuthorSubject: Re: [git-for-windows/git] Options... Cursor... color setting is ignored (Issue #3799) This does seem to work for me. Are you selecting a pre-defined colour on the left or adding a custom colour from the right?And if you're adding a custom colour, do you click "add colour" on the bottom right and then select it on the bottom left?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mbratch** [comment]
Oh I see what's going on...

I had chosen the dlat-uo theme. Evidently when a theme is selected,I can't change the cursor color. I can change it if the theme is none.

⁣Get TypeApp for Android ​

**Comment by mbratch** [comment]
Whoops (fat thumbs) I mean the flat-ui theme.

⁣Get TypeApp for Android ​

On Apr 14, 2022, 4:35 PM, at 4:35 PM, Mark Bratcher ***@***.***> wrote:
>Oh I see what's going on...
>
>I had chosen the dlat-uo theme. Evidently when a theme is selected,I
>can't change the cursor color. I can change it if the theme is none.
>
>⁣Get TypeApp for Android ​
>
>On Apr 14, 2022, 12:54 PM, at 12:54 PM, "Matthias Aßhauer"

**Comment by dscho** [comment]
Since you found the culprit, I am going to close this issue.

If you still think that this needs some sort of fix in the software, please report it at https://github.com/mintty/mintty/issues/.

**Comment by mbratch** [comment]
@dscho Thank you.

I did find the case in which the option is ignored, but should it be ignored in that case? Is that by design, or a defect? I can't answer that question.
