### ISSUE TITLE
Error running git add --interactive when GIT_EXEC_PATH uses backslashes

### ISSUE THREAD

**Issue by bzuillsmith** [git-for-windows/git#3800]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.3.windows.1
cpu: x86_64
built from commit: b952ed2af65bd726a4d21270bc3911db79873fe2
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue?

1. Set my GIT_EXEC_PATH using \  separator instead of /.   eg `C:\Program Files\Git\mingw64\libexec\git-core`
2. Ran `git add filename -i`
3. Got the following error

```
Invalid system path ():  at C:\Program Files\Git\mingw64\libexec\git-core\git-add--interactive line 34.
BEGIN failed--compilation aborted at C:\Program Files\Git\mingw64\libexec\git-core\git-add--interactive line 37.
```

### My Diagnosis

This is an error in a generated perl file, typically at `C:\Program Files\Git\mingw64\libexec\git-core\git-add--interactive`. Since it is generated I can't provide a link to it in the repo here.

There are a couple issues:

### 1. Unset Variables used in error handling
The error message occurs at `(-e $perllibdir) || die("Invalid system path ($relpath): $path"` which references unset variables `$relpath` and `$path`. The die call should probably be something like `die("Invalid system path ($perllibdir)` because $relpath and $path don't appear to be defined causing the error message to be unhelpful.

### 2. Backslashes cause `git add -i` to fail
The function `sub __git_system_path` is responsible for figuring paths relative to the git exec path. It pulls from $ENV{GIT_EXEC_PATH) but does not normalize the slashes. It strips `libexec/git-core` to get a $prefix path, but this is does not work if the GIT_EXEC_PATH contains `libexec\git-core`

I'm not sure what to modify since the code is generated or I would have attempted a pull request

**Comment by rimrul** [comment]
>This is an error in a generated perl file, typically at C:\Program Files\Git\mingw64\libexec\git-core\git-add--interactive. Since it is generated I can't provide a link to it in the repo here.

That file is generated from [git-add--interactive.perl](https://github.com/git-for-windows/git/blob/main/git-add--interactive.perl)

**Comment by carenas** [comment]
the source code is at:

  https://github.com/git-for-windows/git/blob/main/git-add--interactive.perl

but that code is soon to be retired; do you still have problems if using the builtin that is planned to replace it?

```
  git config --global add.interactive.useBuiltin true
```

**Comment by rimrul** [comment]
Closing as stale. Also the scripted implementation of `git add -i` is being removed in v2.40.0
