### ISSUE TITLE
Directories added to the [Safe] section in .gitconfig probably should not be treated case-sensitive on Windows.

### ISSUE THREAD

**Issue by ZonderP** [git-for-windows/git#3801]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.3.windows.1
cpu: x86_64
built from commit: b952ed2af65bd726a4d21270bc3911db79873fe2
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Windows - other than that none...

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Powershell 5,1 and Powershell Core 7.2.2 mainly, but also CMD.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Not directly related to a specific command...

It's about that well known issue introduced in 2.35.2 where the error about non safe directories was introduced.
After finding out the correct syntax for this "(%prefix)/" thingy (which is now fixed in 2.35.3), I prepared a code snippet for some of my colleagues which they should use to put into the [Safe] section of their .gitfonfig file.
It was about some directories on a shared drive and what I put into the [Safe] section were lines like:
directory = %(prefix)///server/QA/Tests/v5/Standard
directory = %(prefix)///server/QA/Tests/v4/Special
Those lines worked for me, but they didn't work for one of my colleagues.
First I didn't understand at all, but then I found out, that for my colleague who still had problems with e.g. pulling on one of those directories, his Powershell displayed something like '//server/qa/Tests/v5/Standard' for the directory where he was just in and tried to execute the pull command. Note that 'QA' for him was written with non capital letters.

 - What did you expect to occur after running these commands?

When 'directory = %(prefix)///server/QA/Tests/v5/Standard' is in the [Safe] section of the .gitconfig file,
then 'git pull' on that directory should work without an error, even if the directory where one is currently in
is in different casing.

 - What actually happened instead?

The error about the none-safe directory appeared and 'git pull' couldn't be executed successfully.

**Comment by dscho** [comment]
The underlying issue is that Git uses the [`core.ignoreCase` setting](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase) to determine whether to match case-sensitively or not. And at this stage, we haven't read the config yet! Meaning, while your suggestion makes sense from a usage scenario, from the implementation's point of view it is a Catch-22.

**Comment by ZonderP** [comment]
Okay - no clue how this exactly is implemented in Git, but I would have thought that when e.g. a 'git pull' gets executed that then first the config file would be read in and later on - when actually doing this security check, the 'core.ignoreCase' could be applied when comparing the actual directory with the directories [Safe]? I mean using something like 'toLower()' for both directories, the actual one and one item from the [Safe] directories list?

**Comment by dscho** [comment]
No, when `git pull` is executed, Git first has to verify that the directory is safe before even reading the config.

**Comment by ZonderP** [comment]
I see - this [core.ignoreCase](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase) is per repo in 'config' under '.git'. I thought it would be in 'C:\Users\[UserName]\.gitconfig'...
Now I can clearly see the Catch-22 nature of this issue.

**Comment by ZonderP** [comment]
Just an idea:
As far as I understand, the security warning would only be displayed after a check about the directory owner.
At the point of this check it might be possible to also somehow detect the file system of that directory and possibly use a sensible 'default' for ignoring or not the casing?

**Comment by dscho** [comment]
> At the point of this check it might be possible to also somehow detect the file system of that directory and possibly use a sensible 'default' for ignoring or not the casing?

How would that work, concretely?

**Comment by ZonderP** [comment]
Sorry, I have no idea how git is written - I'm not involved in development.
I'm just a regular user. And I wrote '... it might be possible...'.
Thus I cannot explain concretely how this could work.
My feeling only was that at some point - when the directory for e.g. 'pull' is known (be it that it was passed in a parameter or the current working directory) - then there seems to be this check, if the directory is safe. At least I think that in this check the owner of that directory is by some means evaluated. If I'm the owner, then all is good, otherwise there is a lookup in the [Safe] directories of a user's '.gitignore' file. If there 'was' an API for detecting the file system of that directory - same as there seems to be an API for detecting the owner of that directory - then I thought, that it might be possible that the internal variable 'ignoreCase' (which later will be read in from 'config' in '.git' of that directory, if it is regarded as 'safe') could temporarily be set to whatever seems to be 'appropriate' for the file system where the questionable directory is on - for use in the following comparison of the directory with the directories in the [Safe] section of the user's '.gitconfig'.
I hope this was somewhat more understandable.

**Comment by dscho** [comment]
The more I think about this, the more I dislike watering down the check, lest some future change will make us regret that decision. The safe option is to require the path to be specified in the same way as it is stored on-disk.

So I am going ahead to close this ticket.

**Comment by ZonderP** [comment]
Even if closed without really understanding the nature of the problem, it is still quite a problem.
Just trapped into it again today and it really is very annoying!
Under Windows, I'd say there is not such a thing as 'the same way as it is stored on-disk' when it comes to users using Windows. Folders and files are treated case-insensitive! (Might be under the hood it is stored case-sensitive, but all Windows related functionality regarding folders and files is case insensitive).
And the bug occurs regardless of how it might be stored (under the hood) on Windows.
It occurs, if a user specifies the folder with other case then specified in [Safe] section of the .gitconfig.
This has nothing to do with 'how it is stored on-disk'.
