### ISSUE TITLE
Win10 system AMD64 architecture has the following problems

### ISSUE THREAD

**Issue by jiaxiaoxu** [git-for-windows/git#3802]
### Once installed, run Git, the following error appears
- Version used: Git-2.35.3-64-bit.exe

```
C:\Users\Administrator>git
fatal: could not open '/dev/null' for reading and writing: No such file or directory
```

**Comment by rimrul** [comment]
Can't reproduce this here.

**Comment by dscho** [comment]
Looks like a duplicate of https://github.com/git-for-windows/git/issues/1016
