### ISSUE TITLE
`git reset HEAD^` triggers a prompt in CMD

### ISSUE THREAD

**Issue by carenas** [git-for-windows/git#3804]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.35.3.windows.1
cpu: x86_64
built from commit: b952ed2af65bd726a4d21270bc3911db79873fe2
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.22598.100]
(c) Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I don't see the issue with msys git or even git bash with the same version

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git reset --hard HEAD^
```
 - What did you expect to occur after running these commands?

last commit (in a lineal history) gets discarded, the somehow equivalent HEAD~ works

 - What actually happened instead?

got an interactive prompt that seems probably unrelated printing:
More?

any input to that prompt seems to replace the "^" and be added to the "HEAD" word, maybe some leftover debugging?

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

doesn't seem to depend on the repository or its contents

**Comment by carenas** [comment]
After more debugging, concluded it is not a problem with git but with the system

**Comment by dscho** [comment]
It's not even a bug. [`^` is the continuation character in CMD](https://stackoverflow.com/a/69079/1860823).
