### ISSUE TITLE
Git for Windows installer overwrites customised editor command line

### ISSUE THREAD

**Issue by richardcox13** [git-for-windows/git#3808]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.3.windows.1
cpu: x86_64
built from commit: b952ed2af65bd726a4d21270bc3911db79873fe2
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

> gc "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Run the instakller, selecting option to only prompt for new options, but occurs going through selecting the options.

```
 - What did you expect to occur after running these commands?

If my `.gitconfig` has a customised setting of `core.editor` there would be an ability to *not change it*. Eg. in the installer the editor can be set to "do not change existing configuration".

 - What actually happened instead?

The setting of `core.editor` is overwritten.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A.

**Comment by dscho** [comment]
> Editor Option: VisualStudioCode

This is the culprit. Just reinstall Git for Windows, and change this setting according to your actual wishes.

**Comment by richardcox13** [comment]
There is no "Do not change the editor" option. Hence this issue.

![image](https://user-images.githubusercontent.com/4578827/164391188-73c3edd5-349e-43fb-9a4a-9997df18d349.png)

**Comment by dscho** [comment]
> There is no "Do not change the editor" option. Hence this issue.
> 
> ![image](https://user-images.githubusercontent.com/4578827/164391188-73c3edd5-349e-43fb-9a4a-9997df18d349.png)

It is admittedly communicated poorly, but "Vim" is essentially that option.

**Comment by dscho** [comment]
@richardcox13 maybe you want to give it a try to change [the label of that option](https://github.com/git-for-windows/build-extra/blob/2c1a5c03ed84a0f8a8d0aa73ec6858e66b0c1632/installer/install.iss#L1888) to make it easier to understand?

**Comment by yuslepukhin** [comment]
I have the same issue. Every time it updates, it changes my editor to code. I have to fix it again.

**Comment by richardcox13** [comment]
Selecting VIM has worked for me. Just go through the options (not just changed options) the next time you update.
