### ISSUE TITLE
Get `notepad.exe` to work as editor

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#381]
Yep, it is ugly, but it is more intuitive than `vim`...

**Comment by linquize** [comment]
But `notepad.exe` does not know `LF` as line ending

**Comment by dscho** [comment]
I would call it unfortunate, but yes, this is one thing I need to address (and talking about it won't fix it...).

**Comment by Dirk1966** [comment]
I know a lot of Windows users and I always recommended them of installing Notepad++, where you can find a lot of hints how to do it (see at bottom).
If you want to implement this, then git.exe should analyze the text and replace CRLF by LF?!?  Or do you plan to provide a wrapper script which does this by configuration?

32 bit NotePad++
git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"
 
64 bit NotePad++
git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"

**Comment by PhilipOakley** [comment]
Just to confirm that those four Notepad++ options  "-multiInst -notabbar -nosession -noPlugin" have worked well for me. And they appear to the lead advice on StackOverflow.

I even have the same quoting inside my .gitconfig ;-)

**Comment by Dirk1966** [comment]
Hi all, I created a perl wrapper for notepad, which replaces the stuff and checks for errors.
I did not put it in the git-queue, this I will try today.  Had problems with the perl output with LF instead of CRLF only although I used binmode and used a "hackaround" with dos2unix.

**Comment by Dirk1966** [comment]
My perl shell script seems to work now also under Windows 10.
I did not identify why I had problems there last night.  I tested it
under the current "git for Windows 2" under "Windows 10" and
"Windows 8.1".  Shall I put the perl script somewhere?

**Comment by Dirk1966** [comment]
An extensive log shows that I might have a perl problem on "Windows 10", but I was able to check in there.

**Comment by dscho** [comment]
> Shall I put the perl script somewhere?

If you want anybody else to benefit from it, I would highly recommend that. Maybe as a Pull Request? It could live in [`git-extra`](https://github.com/git-for-windows/build-extra/tree/master/git-extra), just like e.g. `vi`...

> An extensive log shows that I might have a perl problem on "Windows 10",

I had problems on Windows 10, too, recently, but only in 32-bit mode. It would display the famous [32-bit problems](https://github.com/git-for-windows/git/wiki/32-bit-issues) and it would need [some trickery](https://github.com/git-for-windows/build-extra/commit/7bc16f5d3c9442059fda39d7b1a4cf6559885b9d).

You did not let us know, however, what the nature of your emergency was, nor much of any context. In any case, different problems are better discussed in different tickets.

**Comment by Dirk1966** [comment]
I created my first real repo and put the solution including some docu and two additional test files there:
    https://github.com/Dirk1966/NotPad.git
I tested it now successfully under 64bit Windows 7, 8.1 and could use notepad.exe under Windows 10, 32 bit, but it seems that CRLF is not replaced by LF after editing the file with notepad.exe.

Unfortunately, I could not push to git-extra.  Will try this evening again.

$ git push --set-upstream origin perl-wrapper-notepad.exe-as-commit-editor
Username for 'https://github.com': Dirk1966
Password for 'https://Dirk1966@github.com':
remote: Permission to git-for-windows/build-extra.git denied to Dirk1966.
fatal: unable to access 'https://github.com/git-for-windows/build-extra.git/': The requested URL returned error: 403

**Comment by Dirk1966** [comment]
Got the stuff in with the web interface.
If you call the script without a file name, there is a small description/explanation.
Create NotPad.sh
[https://github.com/git-for-windows/build-extra/pull/76]

**Comment by dscho** [comment]
> Got the stuff in with the web interface.

Probably you forked only during that edit; you can now push into the forked repository, now that you have it.

**Comment by dscho** [comment]
And here is my shell script version of that wrapper: git-for-windows@ master...dscho:notepad

**Comment by dscho** [comment]
Fixed via git-for-windows/build-extra@69b301bbd7c18226c63d83638991cb2b7f84fb64

**Comment by Simon-Krull** [comment]
How can i install the Command "wget" in Git?

**Comment by dscho** [comment]
@Simon-Krull please follow proper procedure. Your question has *nothing* to do with this ticket, so you need to start a new conversation. Since you are not even referring to a bug or enhancement in Git for Windows, you should use the mailing list. You can easily find the information on the top right of [our home page](https://git-for-windows.github.io/) -- and also some guide lines how to contribute properly in its *Contribute* section.
