### ISSUE TITLE
core.useBuiltinFSMonitor will be deprecated soon; use core.fsmonitor instead

### ISSUE THREAD

**Issue by Stanzilla** [git-for-windows/git#3813]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64bit

```
$ git --version --build-options

git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Win11 64bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22598.200]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
 - What did you expect to occur after running these commands?

no warning

 - What actually happened instead?

`core.useBuiltinFSMonitor will be deprecated soon; use core.fsmonitor instead`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

So I understand that the builtin FS monitor is not actually deprecated, just that the name in the config is going to change, is there, on the current version, any way to use the new name or is the only way to get rid of the message to disable it via the provided command?

**Comment by jeffhostetler** [comment]
Yes, just set `core.fsmonitor` to `true` and Git will use the new builtin `git fsmonitor--daemon` 
and not complain any more.  (And you can unset `core.useBuiltinFSMonitor`).

**Comment by dscho** [comment]
I guess we should clarify by saying `core.useBuiltinFSMonitor=true was experimental, please set `core.fsmonitor=true` instead.

@jeffhostetler what do you think?

**Comment by Stanzilla** [comment]
or just auto migrate?

**Comment by jeffhostetler** [comment]
yeah, that would help.

**Comment by jeffhostetler** [comment]
We can't really auto-migrate.  the `core.useBuiltinFSMonitor` was the setting that we used during our experimental releases in GFW.  With the feature going upstream into core Git, a decision was made to overload the existing `core.fsmonitor` setting to take a hook-pathname or a boolean value for the builtin FSMonitor.  However, users may have multiple versions of Git installed on their systems on Windows.  One in the C:/program files/... and hidden versions installed by tools like Visual Studio.  And these may be at different revision levels, so one install might only understand the old keyword and one version might understand both (during the transition).  So, auto transitioning it would break whichever one is the older release.  So it's safer to just warn the user and let them decide.  (And if they know they have multiple versions, they can just set both for now.)
