### ISSUE TITLE
Highlight feature in gitk broken since version 2.36.0

### ISSUE THREAD

**Issue by voodoo66** [git-for-windows/git#3815]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1645]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

file does not exists, using portable package.
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Highlighting a single file in gitk.

 - What did you expect to occur after running these commands?

With git version 2.35.3, only commits, which contains changes for the highlighted file, will get a bold font.

 - What actually happened instead?

Since git version 2.36.0 every commit gets a bold font. Which makes the highlighting feature unusable.

**Comment by rimrul** [comment]
> Since git version 2.36.0 every commit gets a bold font. Which makes the highlighting feature unusable.

I can kinda reproduce this. It isn't always all commits. In fact, in my tests the first commit that only added a `.gitignore` file was never highlighted. Which commits get highlighted doesn't seem to be quite deterministic though.

**Comment by dscho** [comment]
Next question: is this a Windows-only bug?

**Comment by rimrul** [comment]
It's an upstream regression. I can reproduce it on git 2.36.0 on Linux. I'll try to bisect it later.

**Comment by rimrul** [comment]
The bisection results are in: `git bisect` says that

> 244c27242f44e6b88e3a381c90bde08d134c274b is the first bad commit

**Comment by rimrul** [comment]
I've sent the information to the mailing list:
https://lore.kernel.org/git/AM0PR04MB6019ECF053F1FB7B29D75AB7A5F69@AM0PR04MB6019.eurprd04.prod.outlook.com/T/#u

**Comment by dscho** [comment]
> I've sent the information to the mailing list: https://lore.kernel.org/git/AM0PR04MB6019ECF053F1FB7B29D75AB7A5F69@AM0PR04MB6019.eurprd04.prod.outlook.com/T/#u

Let's continue the discussion there.
