### ISSUE TITLE
Is it possible (optionally) to treat symlinks as normal files and do not store the fact that it’s a symlink?

### ISSUE THREAD

**Issue by Mercury13** [git-for-windows/git#3816]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19043.1645]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Both CMD and Git Extensions

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

File u_Strings.h is symlinked from somewhere else.
```
git add u_Strings.h
```
 - What did you expect to occur after running these commands?

Version it as a normal file

 - What actually happened instead?

It it marked as a symlink

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

NO.

**Comment by Mercury13** [comment]
I want to make a really small (<30k) faux-submodule that’s only for me. The rest people will see a normal file.

**Comment by Mercury13** [comment]
Why…
1. File is taken from unrelated or even private repository.
2. Submodules require Git and will not work with “Download ZIP”. It is just easier for others.

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
