### ISSUE TITLE
Cannot run 64-bit git-gui on Windows 8.1

### ISSUE THREAD

**Issue by BrianCook** [git-for-windows/git#382]
I installed the 64-bit Windows version 2.5.2 on my Windows 8.1 desktop.  

I can run Git Bash and Git CMD, but Git-Gui fails with Error in startup script: 'couldn't read file "C:\Program Files\Git\cmd\mingw64\libexec\git-core\git-gui": no such file or directory'.

I think it is looking in the wrong path because there is such a file at "C:\Program Files\Git\mingw64\libexec\git-core\git-gui" (note the 'cmd' part of the path is the difference).

I guess I will have to uninstall and find another version?

**Comment by BrianCook** [comment]
This problem also occurs in 32-bit 2.5.2.

It seems to be working OK in 2.5.1 so something broke it.

**Comment by strigona-worksight** [comment]
Same issue on Win10 x64

**Comment by gregorius** [comment]
An easy temporary solution, until it  is fixed in the next version, is to
open an ordinary cmd command shell (run as admin), go to the git directory
and create a link.
"mklink  /D mingw64 cmd\mingw64".

12. sep. 2015 1.14 a.m. skrev "Simon Trigona" <notifications@github.com>:

**Comment by dscho** [comment]
This is a duplicate of https://github.com/git-for-windows/git/issues/376.

**Comment by alexd3d** [comment]
@gregorius for me worked this:
" go to the **git\cmd** directory
and create a link.
**"mklink  /D mingw64 ..\mingw64".** "
