### ISSUE TITLE
Unable to push (ssh keys problem)

### ISSUE THREAD

**Issue by ymakux** [git-for-windows/git#383]
"Could not create directory '/c/Users/\336\360\340/.ssh'.
Failed to add the host to the list of known hosts (/c/Users/\336\360\340/.ssh/known_hosts).
Permission denied (publickey).
fatal: Could not read from remote"

I'm getting this error when I try to push to remote from UI or command line. As I understand the program unable to find the ssh keys. I've read some SO topics, all they advised to set correctly Windows "HOME" variable. I set to C:\Users\Юра (confirmed by echo $HOME). It doesn't help. Any other suggestions?

UPD: Windows 7, 32bit, Git for win 2.5.2

**Comment by ymakux** [comment]
The problem was that I had non-latin characters in the user profile path. I think it's a bug

**Comment by stenin-nikita** [comment]
I had the same problem. Corrected by adding variable HOME. This path must not contain Latin characters.

**Comment by dscho** [comment]
This is most likely the same problem as https://github.com/git-for-windows/git/issues/331

**Comment by ymakux** [comment]
Here is a temporary solution. How to properly rename a profile path

http://social.technet.microsoft.com/wiki/contents/articles/19834.how-to-rename-a-windows-7-user-account-and-related-profile-folder.aspx

**Comment by dscho** [comment]
> Here is a temporary solution.

Let's call it a work-around, okay? :smiley:

**Comment by fbehrens** [comment]
Just had the same problem on windows 8.1 even with pure acsii in `%USERPROFILE%`,
setting `%HOME%` didn't help either. So I hat to revert to 2.5.0. 

Would be nice when this is fixed to find some documentaion about, where to have the .ssh keys.
I more or less used trial and error fiddling with %HOME%,%HOMEDRIVE%,%HOMEPATH%

**Comment by dscho** [comment]
> So I hat to revert to 2.5.0.

So you're saying 2.5.0 works? What about [2.5.1](github.com/git-for-windows/git/releases/tag/v2.5.1.windows.1) and [2.5.2(1)](github.com/git-for-windows/git/releases/tag/v2.5.2.windows.1)?

**Comment by dscho** [comment]
Sorry, not #331 but #336. But the resolution is similar in both cases.

**Comment by dscho** [comment]
Everybody who has this problem should download `msys-2.0.dll` from https://github.com/dscho/msys2-runtime/releases/tag/home-non-ascii, replace the local file of the same name (it is in `Git\usr\bin`) and test.

**Comment by ymakux** [comment]
Thanks @dscho , I'll try
