### ISSUE TITLE
perl version doesn't support windows like paths

### ISSUE THREAD

**Issue by fdncred** [git-for-windows/git#3835]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.613]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCodeInsiders
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
rust-analyzer in visual studio code on https://github.com/nushell/nushell
```
 - What did you expect to occur after running these commands?

I expected the build to succeed

 - What actually happened instead?

rust-analyzer calls cargo which calls perl.exe which is part of the git-for-windows distribution, as part of the build script for openssl, which promptly fails with
```
******************************************************************************
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.34.0 for x86_64-msys-thread-multi
******************************************************************************
thread 'main' panicked at '
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by rimrul** [comment]
Yes, this is MSYS2 perl, which definitely expects Unix style paths. Since our perl is really only intended to run the parts of git that are written in perl, there is no need to change this.

**Comment by fdncred** [comment]
lol, forget you windows users, we don't care about you, even though this is git-for-windows. why not include a perl that understands and works with windows? then people like me wouldn't have problems when other toolchains on windows try to use your tools like rust with openssl.

**Comment by rimrul** [comment]
You're correct. This is **Git** for Windows. Not **Perl** for Windows. Or **rust-analyzer** for Windows.

The fact we bundle a `perl` at all is an implementation detail. It's not intended for use by external tools. On a well configured System, such external toolchains shouldn't even see our `perl`.

We bundle a `perl` that meets our needs for a perl, because some of our features require us to do so. We'd love to not bundle a `perl` at all, but sadly that's easier said than done. 

The fact that `rust-analyzer` uses any `perl` it finds without making sure it meets their needs is hardly our fault.

**Comment by fdncred** [comment]
i understand your points. if i were in your shoes i probably wouldn't want to help either. either way, i thought you should know that this just started happening with the latest version. i didn't use to have this problem. but that could be a cargo change, a rust-analyzer change, a git-for-windows change, an openssl change. who knows.

**Comment by dscho** [comment]
@fdncred for somebody who wants something from somebody else, you sure have a funny way to express the desire for that somebody else to help you.

If you are so keen on having support for MSYS2's Perl to support Windows-style paths, you should first note that this is Open Source, baby, and do something about said support yourself.

Second, you should be more careful when reporting a "bug". MSYS2's Perl _does_ support Windows-style paths. See e.g.

```console
$ perl -lne '/^\[(.*)\]$/ && print $1' 'C:\Users\me\.gitconfig'
user
core
push
alias
[...]
```

See how it totally accepts a Windows-style path as command-line parameter? In other words, the claim that MSYS2's Perl does not support Windows-like paths is provably incorrect.

But again, I find the way you ask for help quite a bit unfortunate. After reading what you wrote, I'm not particularly eager to lend my hard-won expertise to help you with an issue that is not even part of a supported workflow. There are enough users who ask for help more respectfully, and there are plenty of things for me to work on that are part of the supported workflow. Next time you ask for help from someone whose knowledge and expertise you hope to benefit from, you might want to consider a different tone.
