### ISSUE TITLE
Critical : git rebase --autostash, failed, no trace in reflog, no visible stash created but modifications lost

### ISSUE THREAD

**Issue by Baccanno** [git-for-windows/git#3839]
- What commands did you run to trigger this issue? 

```
git rebase --autostash origin/main
```
 - What did you expect to occur after running these commands?

Stash being created, rebase initiated, reflog keeping the history

 - What actually happened instead?
   - None of the above
   - **An unknown quantity of modified files where rollback to a previous version**. 
   - Reflog has only last commit
   - Last stash is 2 weeks old 

I unfortunately didn't kept the log, but as I recall it was saying something like :

```
Created autostash: XXX
Error on a LFS pointer #It happens quite regularly and most of the time I can recover, can be due to Unity3D not being closed or related
```
and this happens, note the rebasing bash header is `(|REBASE)`
```
XXX@XXX-DESKTOP MINGW64 /d/Development/REPO (|REBASE)
$ git st
On branch feature/FEATURE
You are currently rebasing.
  (all conflicts fixed: run "git rebase --continue")
```

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1645]
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using GIT LFS `git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)`

### Details

 - Which terminal/shell are you running Git from? 

Git bash via VSC

**Comment by dscho** [comment]
> XXX@XXX-DESKTOP MINGW64 /d/Development/REPO (|REBASE)
> $ git st
> On branch feature/FEATURE
> You are currently rebasing.
>   (all conflicts fixed: run "git rebase --continue")

Did you run `git rebase --continue` to finalize the rebase? The stash will _not_ be re-applied before the rebase is done.

**Comment by Baccanno** [comment]
Unfortunately the rebase --continue fails : `warning: could not read '.git/rebase-merge/head-name': No such file or directory`
I'm not aware of how the autostash differs from a regular stash, I would have expected to see it in the stash list, I found this, so the stash might still be created but "hidden" ?

```
$ cat .git/rebase-merge/autostash 
b5195462fe17eec179ab529c5f44fcb109b257bf
```

**Comment by Baccanno** [comment]
The stash seems to indeed exists as a git diff on the hash shows the modified files. Quite releaved that the work is not lost. Question now is how to revert to a working state.

**Comment by Baccanno** [comment]
Would `git rebase --quit` be safe in this situation ? Would I need to checkout the stash files manually ?

**Comment by Baccanno** [comment]
```
git rebase --quit
Autostash exists; creating a new stash entry.
Your changes are safe in the stash.
You can run "git stash pop" or "git stash drop" at any time.
```
I'm good to go, thanks for the hint @dscho. Closing this
