### ISSUE TITLE
PortableGit  ldh.exe have a TR/Cryot,XPACK.Gen virus 

### ISSUE THREAD

**Issue by kay54068** [git-for-windows/git#384]
I use antivirus software(AVIRA) to scan PortableGit I detect the following information:
ldh.exe have a TR/Cryot,XPACK.Gen virus

**Comment by PhilipOakley** [comment]
From: kay54068 
  To: git-for-windows/git 
  Sent: Saturday, September 12, 2015 4:02 PM
  Subject: [git] PortableGit ldh.exe have a TR/Cryot,XPACK.Gen virus (#384)


  I use antivirus software(AVIRA) to scan PortableGit I detect the following information:
  ldh.exe have a TR/Cryot,XPACK.Gen virus


As a paid customer of AVIRA, can you report the issue to them? 

dscho has plans regarding keeping the code signing up to date, but false positive AV reports are a perennial problem. Unfortunately it needs to be the AV customers who do the reporting...

**Comment by dscho** [comment]
> As a paid customer of AVIRA, can you report the issue to them?

@kay54068 it would be really nice if you could answer this question.
