### ISSUE TITLE
git bash on windows 11 task bar is not working if two git bash are open.

### ISSUE THREAD

**Issue by Mizar01** [git-for-windows/git#3841]
Hello.
I recently bought a Windows 11 pc and installed git bash from https://gitforwindows.org

The bash is working well and I pinned it to the windows taskbar. But when I open a second or third git bash, clicking on the git bash icon does nothing, it does not show the choice of what window I want and it doesn't move git window on top.
Steps to reproduce:
- Click git bash from taskbar (a new git bash window will open)
- Right click on git bash icon on the task bar and open another git window (a new git bash window will open)
- Open any other app (ex. chrome or edge) that comes on top, hiding both bash windows.
- If you click on the git icon in the taskbar nothing happens 

A workaround is to use alt+tab, but that's very slow if you have ten apps or more opened.

**Comment by nikeedev** [comment]
@Mizar01, does it still happen?
