### ISSUE TITLE
SSH intermittent issues in Git Bash 2.34.1 for windows 10 

### ISSUE THREAD

**Issue by pockdm** [git-for-windows/git#3842]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 -64-bit version

```
$ git --version --build-options

** C:\Users\rm01>git --version --build-options
git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
 **
```

 - Windows 10 64 bit

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.22000.613] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
   Default
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** C:\Users\rm01>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Git Bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** ssh root@ip addrs **
```
 - What did you expect to occur after running these commands?

** ssh should work **

 - What actually happened instead?

** It gives bad address even though entry is present in known_hosts file. If i do ssh -v root@ip addrs it lets me ssh to the machine sometimes and sometimes give bad address however ssh root@ip addrs doesnt work and gives below error. If i try 6-t times i get the option to enter the password and login to server.  

OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
debug1: Reading configuration data /c/Users/rm01/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
gethostname: Bad address

**

**Comment by pockdm** [comment]
Tried to Upgrade to Git-2.36.0-64-bit but still same issue.

**Comment by pockdm** [comment]
C:\Users\rm01>git --version --build-options
git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

if i try ssh 
$ ssh root@ip addr
gethostname: Bad address

Again if i try it lets me login 
RM01@D7YYQ93 MINGW64 ~
$ ssh root@ip addr
root@ip addr's password:

Then again denies
logout
Connection to ip addr closed.

RM01@D7YYQ93 MINGW64 ~
$ ssh root@ip addr
gethostname: Bad address

**Comment by dscho** [comment]
Hmm. It might not be the remote host that fails to be looked up. Maybe adding a couple `-v` options sheds light into the conundrum?

**Comment by pockdm** [comment]
> Hmm. It might not be the remote host that fails to be looked up. Maybe adding a couple `-v` options sheds light into the conundrum?

$ ssh -v root@ip addr
OpenSSH_8.9p1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /c/Users/rm01/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
gethostname: Bad address

I have also tried to add Host ip addr HostkeyAlgorithms +ssh-rsa  PubkeyAcceptedAlgorithms +ssh-rsa in /etc/ssh/ssh_config but still no luck.

**Comment by pockdm** [comment]
@dscho : Any update on this issue?

**Comment by dscho** [comment]
No updates from my side: I still get the hunch that `ssh` tries to look up something different than the IP provided on the command-line, but don't see enough evidence to assess that hunch.

FWIW you can throw in _many_ more `-v`s than just two (just be careful to analyze the output yourself, I'm not sure whether it'd contain secrets).

**Comment by Kiclark1** [comment]
https://github.com/git-for-windows/git/issues/3842#issuecomment-1118920916
