### ISSUE TITLE
Typing git rest then pressing on TAB button didn't suggest git restore command on powershell

### ISSUE THREAD

**Issue by ManikandanMani** [git-for-windows/git#3844]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
  **64-bit**
```
$ git --version --build-options

**git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon**
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
   **Windows 10 pro 64 bit**
```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19044.1682] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
    defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

** Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled**
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
     **PowerShell (native & using powershell on windows terminal)**

 - What commands did you run to trigger this issue? 
    ```  git restore ```

 - What did you expect to occur after running these commands?

**Typing git rest then pressing on TAB button should suggest as git restore command on powershell**

 - What actually happened instead?

**Typing git rest then pressing on TAB button didn't suggest git restore command on powershell**

**Comment by phil-blain** [comment]
The Git for Windows project does not ship tab-completion functionality for PowerShell, only for Git Bash. There it uses the completion from the upstream: project https://github.com/git/git/blob/master/contrib/completion/git-completion.bash.

**Comment by dscho** [comment]
For PowerShell users, there exists https://github.com/dahlbyk/posh-git/.

**Comment by ManikandanMani** [comment]
I use oh-my-posh, typing git rest then pressing tab did suggest git restore before upgrading from version 2.34.~ to current version.

**Comment by dscho** [comment]
> I use oh-my-posh, typing git rest then pressing tab did suggest git restore before upgrading from version 2.34.~ to current version.

Since Git for Windows does not offer those completions for PowerShell, maybe report it over at posh-git (or oh-my-posh, if that's the actual culprit)?

**Comment by dscho** [comment]
Since Git for Windows has no control over the code that needs fixing, I'll close this ticket.
