### ISSUE TITLE
clone Repository with Submodule lost LFS  lockable attribute

### ISSUE THREAD

**Issue by rcdevice** [git-for-windows/git#3847]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
System Info]

64-bit
```
$ git --version --build-options

git version:
git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
uname: Windows 10.0 19044 
compiler info: gnuc: 11.2
libc info: no libc information available
$SHELL (typically, interactive shell): C:\Program Files\Git\usr\bin\bash.exe
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 Windows 10.0 19044  21H2
```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19044.1645]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash，Tortoisegit

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

1. I have  a Repository (A) to save LFS files ,the .gitattributes as following
```
*.sldprt  filter=lfs diff=lfs merge=lfs -text lockable
```

To avoid accidental modification, I use the lockable attribute, so next ,someone clone the repository ,all LFS files should be READ ONLY, if they want edit it ,unless use LFS->lock .

Following the normal process to cloning the repository, everything happened as I expected, all LFS files are READ ONLY ,perfect!

2. BUT， when I put same repository(A) as Submodule insert to another repository(B),the (B) have LFS files too, use same .gitattributes , when I use B's url to cloning again, all LFS files in (B) all are READ ONLY ,BUT in Submodule DIR, all files LOST READ ONLY attributes.

Conclusion: LFS files in submodules may be accidentally modified due to missing read-only attributes.
```
$ git clone --recursive https://github.com/rcdevice/testlfs.git
Cloning into 'testlfs'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 1), reused 11 (delta 1), pack-reused 0
Receiving objects: 100% (11/11), done.
Resolving deltas: 100% (1/1), done.
Filtering content: 100% (3/3), 336.10 KiB | 129.00 KiB/s, done.
Submodule 'lfssub' (https://github.com/rcdevice/lfssub.git) registered for path 'lfssub'
Cloning into 'E:/work/BV01/BV01_3D/testlfs/lfssub'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (8/8), done.
Submodule path 'lfssub': checked out 'ca0c4b12dc0f9acf135aacff6dd142e1677c05de'

```
 - What did you expect to occur after running these commands?

I want the cloning behavior in the submodule with LFS files to be the same as normal cloning, if use lockable attribute ,that all LFS file should be READ ONLY .

 - What actually happened instead?

BUT in Submodule DIR, all files LOST READ ONLY attributes

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/rcdevice/testlfs.git   (B)

the testlfs.git have a submodule lfssub.git （A)
https://github.com/rcdevice/lfssub.git

**Comment by dscho** [comment]
Isn't this a Git LFS problem (i.e. to be reported [here](https://github.com/git-lfs/git-lfs/issues/)? Or do you mean to say that it is a submodule problem (i.e. to be reported to [the Git mailing list](mailto:git@vger.kernel.org), please send plain-text messages, HTML messages are dropped silently)? In either case, it would not be a Windows-specific problem, correct?

**Comment by dscho** [comment]
No answer is also an answer, as the saying goeth.
