### ISSUE TITLE
Git installer should not set the deprecated config `useBuiltinFSMonitor`

### ISSUE THREAD

**Issue by sachinjoseph** [git-for-windows/git#3853]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 git version 2.36.1.windows.1

```
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon 
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 11-x64
```
Microsoft Windows [Version 10.0.25117.1000]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
C:\Users\WDAGUtilityAccount>type "C:\Program Files\Git\etc\install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
![image](https://user-images.githubusercontent.com/6994498/168405358-3e5d81ae-a6b2-4653-a08e-298b7f8746c8.png)
```
1. Install the latest version (2.36.1 at the time of writing) of git-for-windows, enable the experimental File System Monitor during installation.

2. Run `git clone https://github.com/sachinjoseph/lfs-test.git`
```
 - What did you expect to occur after running these commands?

The command would clone the repo without warnings - was not expecting a warning about `useBuiltinFSMonitor`.

 - What actually happened instead?

The git-for-windows installer sets the deprecated config `core.useBuiltinFSMonitor` in the global git config. I was not able to open an issue on https://github.com/git-for-windows/build-extra.
![image](https://user-images.githubusercontent.com/6994498/168405272-e17e456f-2468-489a-8c51-6ab5ccfb105e.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

NA

**Comment by dscho** [comment]
Oh wow, you're right, I thought we had adjusted that in v2.36.0.

**Comment by dscho** [comment]
Fixed via https://github.com/git-for-windows/build-extra/commit/fbea60b3bb6fab6ce649db9bc9cc09c42600a6f4. The next [snapshot](https://wingit.blob.core.windows.net/files/index.html) will have the fix.
