### ISSUE TITLE
tilde_expand: No such user \\.ssh\\rsa (since update to 2.36.1, not occuring in 2.35.3)

### ISSUE THREAD

**Issue by picks44** [git-for-windows/git#3855]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** 
$ git --version --build-options
git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon 
**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** 
$ cmd.exe /c ver
Microsoft Windows [version 10.0.19044.1645]
 **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

**
$ cat /etc/install-options.txt
Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Git Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** $ ssh MY_USER@MY_MACHINE_IP -v   **
```
 - What did you expect to occur after running these commands?

** Connect to my distant VM with SSH **

 - What actually happened instead?

```
** 
$ ssh MY_USER@MY_MACHINE_IP -v                                         
OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
debug1: Reading configuration data /c/Users/ME/.ssh/config
debug1: /c/Users/ME/.ssh/config line 48: Applying options for MY_MACHINE_IP
debug1: /c/Users/ME/.ssh/config line 53: Applying options for MY_MACHINE_IP
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to MY_MACHINE_IP[MY_MACHINE_IP] port 22.
debug1: Connection established.
tilde_expand: No such user \\.ssh\\rsa
 **
```

My SSH config line
```
Host MY_MACHINE_IP
 IdentityFile ~\.ssh\_rsa
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> IdentityFile ~\.ssh\_rsa

Please try to use forward-slashes with OpenSSH. It does originate from Unix, where backslashes aren't directory separators.

A strong indicator that you _meant_ to use a Unix-y path is that you used the tilde, which would not make sense in any Windows-style path at all.
