### ISSUE TITLE
Turn off fast-forward merge by default

### ISSUE THREAD

**Issue by class101** [git-for-windows/git#3858]
Hello, I'm wondering why the fast-forward merge option is enabled by default with the Windows installer and I would like to suggest for a change, ideally with informations on why it is recommended to turn the option off.

[merge] ff = false
[pull] ff = true

After this change and a merge on master, you get a more understandable graph with the starting and merging point of the branch and all commit message made to the branch, they won't be showing as if you did the commit on master but on the branch instead, even when the branch gets deleted.

There is an excellent article, explaining why it should be turned off ever for all teammates !

https://betterdev.blog/turn-off-git-fast-forward-merge/

*Worth noticing is that when we merge branches from pull requests on GitHub or GitLab, they are also done in no fast-forward mode. This ensures we have true repository history preserved.*

So why isn't it the default behavior on Git for Windows ?

**Comment by rimrul** [comment]
> I would like to suggest for a change, ideally with informations on why it is recommended to turn the option off

Is it? I don't see any such recommendation in any of the official documentation.

> So why isn't it the default behavior on Git for Windows ?

Because this ist the default behavior on git on any other platform, either.

**Comment by class101** [comment]
It is with Gitlab and GitHub. Windows imo is just another client to simply things for users, recording history for me is part of simplifying a usage.

Thé Windows version of Git for me is closer to the client usage we make of it with GitHub and Gitlab rather than comparing to git from scratch

For example: you already set this in the installer by default [merge] rebase = false alongs with some other options

You should do the same imo and/or inform in the installer that using fast forward will record less information than not using it.

**Comment by rimrul** [comment]
> If you don't see the advantage, then read my post again and click the link.

I did. Neither your issue descriptoion nor the linked blog post convince me that this is a good idea.

> It is with Gitlab and GitHub. 

I fail to see their relevance in this case.

>Windows imo is just another client to simply things for users, recording history for me is part of simplifying a usage.

A commit history with fast-forward merges is still a history.

> Thé Windows version of Git for me is closer to the client usage we make of it with GitHub and Gitlab rather than comparing to git from scratch

Ok, that's how you use Git for Windows. There are other users, too.

> For example: you already set this in the installer by default [merge] rebase = false alongs with some other options

We do set some config options based on user choices in the installer, yes. I'm not sure if that one is the default for that particular choice, but if it is, it's because it closely resembles a default behaviour users got used to over the decades.

> You should do the same imo and/or inform in the installer that using fast forward will record less information than not using it.

We could add an option to the installer to disable fast-forward merges, but they should stay enabled by default.

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

**Comment by class101** [comment]
The installers that sets default values in this git configuration file is Windows specific.

You are setting default values in git config with the Windows installer and when you feel a setting does not fit in, you redirect the suggestion author to bother the original devs of Git that don't car about Windows and will inevitably redirect back to Windows git.

You just looks like lazy guys, you do not deserves any help to enhance this project, shame on you

**Comment by rimrul** [comment]
Insulting people does not help in any way.

**Comment by dscho** [comment]
It also violates our code of conduct, meaning that the contributor removes themselves from the community.
