### ISSUE TITLE
Mouse scrolling in less no longer works in Windows Terminal on 2.36.1 (works on 2.36.0)

### ISSUE THREAD

**Issue by nathpete-msft** [git-for-windows/git#3860]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
   - Appears related but different to #3657

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1706]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

N/A - Installed via Scoop
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
   - `core.pager = less --mouse`

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
   - PowerShell 7.2.4
   - Windows Terminal 1.14.1371.0

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log
git diff
```
 
- What did you expect to occur after running these commands?
  - Being able to scroll the git log or a long diff with the mouse

 - What actually happened instead?
   - Scrolling with the mouse does not work

Scrolling with mouse in this setup started working for me with git 2.36.0, but stopped working with 2.36.1. It also works fine either within git bash or when piping the output of git to `less --mouse` (less v590 installed via Scoop).
Mouse scrolling also works if change the pager to point to the version of less I have installed in Windows: `core.pager = /c/Users/nathpete/scoop/shims/less.exe --mouse`

| Git Version | Less Mouse Scrolling Works |
|-|-|
| 2.35.3 | No |
| 2.36.0 | Yes |
| 2.36.1 | No |

**Comment by dscho** [comment]
Could you bisect through the latest [snapshots](https://wingit.blob.core.windows.net/files/index.html) (which include v2.36.0 and v2.36.1) to pinpoint a bit more where this issue might come from?

**Comment by nathpete-msft** [comment]
@dscho, I tested with each of the snapshots between v2.36.0 and v2.36.1 and the issue first appears in the snapshot for commit https://github.com/git-for-windows/git/commit/60d4d758f4bc3032a7e3e57d0fbeb657bbc53a5c

The snapshot before that one (https://github.com/git-for-windows/git/commit/dc88e3cd72a2f0bbe2fe513acfc72bd66b577851) works as expected.

**Comment by dscho** [comment]
What about copying the file from the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by dscho** [comment]
> no change with [c5ca16f](https://github.com/git-for-windows/git/commit/c5ca16f7d97c11c75cc9a86461a91cedd593ce7b), scrolling is still broken there

Darn.

> copying `/usr/bin/msys-2.0.dll` from [dc88e3c](https://github.com/git-for-windows/git/commit/dc88e3cd72a2f0bbe2fe513acfc72bd66b577851) to [60d4d75](https://github.com/git-for-windows/git/commit/60d4d758f4bc3032a7e3e57d0fbeb657bbc53a5c) does seem to "fix" it.

According to the included `/etc/package-version.txt` files, dc88e3c comes with msys2-runtime 3.3.4-2 while 60d4d75 comes with 3.3.4-3. The corresponding patches can be found [here](https://github.com/git-for-windows/MSYS2-packages/commit/f4aa6e9612cea72ed623e9373b17dafec1098e35).

Sadly, there are _tons_ of individual patches in that update.

Even [the overall diff](https://github.com/git-for-windows/msys2-runtime/compare/f0cc1ed522e422070c6f98302844f29c50963894..df18b6b1f849d0934f6836b9c37d68bc91313ad8) is _large_.

Maybe you can spot anything in the [list of patches](https://github.com/git-for-windows/MSYS2-packages/tree/f4aa6e9612cea72ed623e9373b17dafec1098e35/msys2-runtime) that might fix things? We could then try to revert individual commits (e.g. in a PR at https://github.com/git-for-windows/msys2-runtime, which will build the runtime and offer the build artifacts for download/testing).

Usually I would give this a thorough analysis before unleashing such a large set of changes onto a bug reporter, but I am currently a bit short on time...

**Comment by crash5** [comment]
If you set the TERM environment variable to empty "" value or some invalid value then the scrolling works. I hope this will help somehow to investigate the bug. (it will show some error message about unsupported terminal but it works at least :D)

eg: `TERM="" git diff <somehash>`

**Comment by dscho** [comment]
> If you set the TERM environment variable to empty "" value

What is the value of that environment variable for you if you do not override it?

**Comment by crash5** [comment]
> > If you set the TERM environment variable to empty "" value
> 
> What is the value of that environment variable for you if you do not override it?

"xterm-256color"

**Comment by dscho** [comment]
> > > If you set the TERM environment variable to empty "" value
> > 
> > 
> > What is the value of that environment variable for you if you do not override it?
> 
> "xterm-256color"

@crash5 Wait, that should work, and according to some testers it works with the latest MSYS2 runtime. Are you running this in Git for Windows v2.37.1?

**Comment by crash5** [comment]
> > "xterm-256color"
> 
> @crash5 Wait, that should work, and according to some testers it works with the latest MSYS2 runtime. Are you running this in Git for Windows v2.37.1?

Latest win. terminal and git, mouse scrolling is not working. (keyboard scrolling works with pg-up/-down and up/down)

```
Windows Terminal Version: 1.14.1962.0

git --version --build-options:
git version 2.37.1.windows.1
cpu: x86_64
built from commit: 323a69709944b193bb5cee81ff09fe9a4a686df5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

**Comment by crash5** [comment]
I'm using the bin/bash.exe -i -l, not the powershell as in the first comment.

**Comment by dscho** [comment]
@crash5 for completeness' sake, could you try the same with [Cygwin](https://cygwin.com/)? I ask because the regression is most likely caused by one of their patches, and if it reproduces in plain Cygwin, we have good chances that they will fix it swiftly.

**Comment by crash5** [comment]
> @crash5 for completeness' sake, could you try the same with [Cygwin](https://cygwin.com/)? I ask because the regression is most likely caused by one of their patches, and if it reproduces in plain Cygwin, we have good chances that they will fix it swiftly.

I don't have cygwin and I can't install it. If I replace the original /usr/bin/msys-2.0.dll with the dll from dc88e3cd72a2f0bbe2fe513acfc72bd66b577851 the scrolling works but every few minutes it's show some error message about a fork() call crash.

**Comment by crash5** [comment]
I tested it with the Windows Terminal preview 1.15.1862 and it looks like the scrolling works again with it.

**Comment by crash5** [comment]
I tested it under cygwin. No mouse scroll with less under git. But scrolling with mouse works in less alone, without git (eg: less <filename.txt>).

**Comment by dscho** [comment]
Closing as stale.
