### ISSUE TITLE
2.36.1 installer hangs up, progres bar is not moving

### ISSUE THREAD

**Issue by sysmat** [git-for-windows/git#3861]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - 64-bit?

```
$ git --version --build-options

can not run 2.35.1.2 is removed
```

 - win 10? 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1645]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by sysmat** [comment]
when rerunning it hangs on git-for-windows.ico

**Comment by sysmat** [comment]
When manually delete previous version of Git (C:\Program Files\Git) then installation works

**Comment by dscho** [comment]
> when rerunning it hangs on git-for-windows.ico

Sorry, this is way too little information to go on. Please provide a proper bug report, with enough detail that people other than you can make sense of it.
