### ISSUE TITLE
Use Windows proxy settings

### ISSUE THREAD

**Issue by filmor** [git-for-windows/git#387]
It would be really nice if git-for-windows could make use of the Windows proxy settings. Something like this: https://github.com/LoginPeople/Windows-proxy-settings/blob/master/proxyparser.cpp may be of use. Is this feasible?

**Comment by nalla** [comment]
The problem is that there are so many "sub programs" that depend on correct `http_proxy` and `https_proxy` environment variables. For the _Git for Windows SDK_ installer we have https://github.com/git-for-windows/build-extra/blob/master/sdk-installer/setup-git-sdk.bat#L47 in place. 

You could add a page to the installer where the user could enter the proxy or could choose "use system proxy". Then add a little helper program that then would read the current proxy settings inside `/etc/profile.d/env.sh` and setting those values accordingly for each _Git Bash_ startup.

**Comment by filmor** [comment]
Are there really? It seems to me that setting the relevant settings in `gitconfig` is enough. I'm mostly interested in per-hostname proxy settings.

**Comment by dscho** [comment]
> I'm mostly interested in per-hostname proxy settings.

Please clarify.

**Comment by dscho** [comment]
@filmor if you want your problem to be addressed, I strongly advise to spend an effort to describe clearly what that problem is. Otherwise we won't be able to help you.

**Comment by filmor** [comment]
We have a proxy server in the company that doesn't recognize internal host names. I want to use Github, BitBucket and a few different internal servers. Also I want to be able to seamlessly transfer to a no-proxy setup which should still be able to use Github and BitBucket.

Windows itself handles all of these using the proxy auto-configuration so it would be nice to just forward this information to git. It could be possible to hook into the call that gets the proxy configuration for a specific host and resolve the proxy server through the win32api like it is done in the link in the OP.

**Comment by dscho** [comment]
Good. This is a much better description and helped me finally understand what you want and why.

The biggest challenge is that this support will not fall from the sky. It will not even happen randomly, and waiting for somebody else to step up to the task [won't work, either](https://github.com/bagder/curl/issues/352).

So here is the question: how much time can you dedicate to your goal?

**Comment by dscho** [comment]
@filmor that question was for you, BTW. And I am serious: After this comment, I will not work on this any longer unless you chip in, too.

So here is an example program that can be used to look up the proxies for given URLs specified as command-line parameters:

```c
#include <stdio.h>
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <winhttp.h>
#include <shellapi.h>

LPCWSTR get_proxy_for_url(LPCWSTR url)
{
	WINHTTP_CURRENT_USER_IE_PROXY_CONFIG config;
	WINHTTP_AUTOPROXY_OPTIONS options;
	WINHTTP_PROXY_INFO info;

	memset(&config, 0, sizeof(config));

	if (!WinHttpGetIEProxyConfigForCurrentUser(&config))
		config.fAutoDetect = FALSE;
	else if (config.lpszAutoConfigUrl)
		config.fAutoDetect = TRUE;

	if (config.fAutoDetect) {
		HINTERNET handle = WinHttpOpen(L"Proxy Lookup/1.0",
				WINHTTP_ACCESS_TYPE_NO_PROXY,
				WINHTTP_NO_PROXY_NAME,
				WINHTTP_NO_PROXY_BYPASS, 0);

		memset(&options, 0, sizeof(options));

		options.fAutoLogonIfChallenged = TRUE;
		options.dwFlags = options.lpszAutoConfigUrl ?
			WINHTTP_AUTOPROXY_CONFIG_URL :
			WINHTTP_AUTOPROXY_AUTO_DETECT;
		if (!options.lpszAutoConfigUrl)
			options.dwAutoDetectFlags =
				WINHTTP_AUTO_DETECT_TYPE_DHCP |
				WINHTTP_AUTO_DETECT_TYPE_DNS_A;


		config.fAutoDetect = WinHttpGetProxyForUrl(handle, url,
				&options, &info );

		WinHttpCloseHandle(handle);
	}

	if (config.fAutoDetect)
		return info.lpszProxy;
	return config.lpszProxy;
}

int main(int argc, char **argv)
{
	LPWSTR *wargv;
	int i, wargc;

	wargv = CommandLineToArgvW(GetCommandLineW(), &wargc);
	wprintf(L"Proxy lookup\n");

	for (i = 1; i < wargc; i++)
		wprintf(L"URL: %s, proxy: %s\n",
				wargv[i], get_proxy_for_url(wargv[i]));

	return 0;
}
```

You need to compile it with `gcc -Wall -Werror -o lookup.exe lookup.c -lshell32 -lwinhttp` and then you need to report back whether it manages to find the correct proxies (in particular `(null)` for local addresses).

**Comment by nalla** [comment]
FWIW this is my output with an _Windows automatic proxy detection setup_

```shell
nalla@dev MINGW64 /usr/src/lookup
$ make
gcc -c -o obj/lookup.o lookup.c -Wall -Werror
gcc -o lookup obj/lookup.o -Wall -Werror -lshell32 -lwinhttp

nalla@dev MINGW64 /usr/src/lookup
$ ./lookup.exe https://github.com
Proxy lookup
URL: https://github.com, proxy: 10.0.0.1:80;10.0.0.1:80

nalla@dev MINGW64 /usr/src/lookup
$ ./lookup.exe localhost
Proxy lookup
URL: localhost, proxy: (null)

nalla@dev MINGW64 /usr/src/lookup
$ ./lookup.exe another.local
Proxy lookup
URL: localhost, proxy: (null)
```

For documentation, my `Makefile`
```Makefile
CC=gcc
CFLAGS=-Wall -Werror
LIBS=-lshell32 -lwinhttp
ODIR=obj

_OBJ = lookup.o
OBJ= $(patsubst %,$(ODIR)/%,$(_OBJ))

$(ODIR)/%.o: %.c
        $(CC) -c -o $@ $< $(CFLAGS)

lookup: $(OBJ)
        gcc -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
        rm -f $(ODIR)/*.o
```

**Comment by dscho** [comment]
Hrm... So you get *two* (identical) proxy entries?

**Comment by dscho** [comment]
Wow, sorry @nalla I forgot to thank you for picking up the ball!

**Comment by nalla** [comment]
> Hrm... So you get two (identical) proxy entries?

no! I made a mistake when I replaced the sensetive data! Those are two separate IPs - I'll edit.

**Comment by dscho** [comment]
Okay. Now the question is what to do with *two* proxies. Try both? Just the first one?

**Comment by nalla** [comment]
The second one is the fall back proxy. The first one takes preference.

**Comment by dscho** [comment]
Okay. I hope that there is a concept of a "fallback proxy" in cURL...

**Comment by 19379** [comment]
@dscho thanks for that code snippet. my local library has a proxy and every tip i found on google all reported a direct connection. using your app gave the proxy server ip and port. i'm happy enough launching git-bash with 2 different batch files depending on where i am. one sets the HTTPS_PROXY environment variable and the other one doesn't.

**Comment by dscho** [comment]
@19379 the idea would be to use the code snipped to enhance cURL, of course, so you would not need to do all of that HTTPS_PROXY dance.

There are a couple of issues with this, though. Most importantly: how to enable this automatic proxy lookup? It should be opt-in, certainly. Or not?

The next problem is: how to deal with multiple entries? It might be a semicolon-separated list of proxies, and we might need to fall back to the second, and third, etc. I have no idea whether there is already code in cURL allowing for multiple fallback proxies...

In any case, @19379 would you like to work on this? I'd like to assist, but I cannot do it myself because I have other bugs I need to squash much more urgently...

**Comment by 19379** [comment]
given direct instructions, i can compile things. that's about my limit. sorry if my previous post was misleading. i was just posting to thanks for a solution i hadn't been able to find elsewhere.

**Comment by quanghung231078** [comment]
[1448107740825Tai lieu san pham iGate AW300N.pdf](https://github.com/git-for-windows/git/files/243731/1448107740825Tai.lieu.san.pham.iGate.AW300N.pdf)

**Comment by quanghung231078** [comment]
eWallet apps
