### ISSUE TITLE
Git push on remote sever (samba share) - wrong permissions

### ISSUE THREAD

**Issue by AlmAck** [git-for-windows/git#388]
With the old msysgit 1.9.5 I never had issues when pushing on a local server (Linux with samba, mounted locally in a windows7 64bit).
I'm using git for windows 2.5.1 (64bit). Seems that git creates the tmp file but then is not able to rename it because the permission are read only. If I use the old version 1.9.5 I'm always able to push commits without issues.
I think my bug is also releated to this one #236 

The 9de29bb2 file is generated from windows using git during a push, and text.txt is generated manually from the same windows machine.
```
 ll test.git/objects/e6/
total 4
-r--r--r-- 1 abcd aqusers 15 Sep 10 11:43 9de29bb2d1d6434b8b29ae775ad8c2e48c5391
-rw-rw-r-- 1 cdba users    0 Sep 14 11:09 test.txt
```

The error I receive from git gui is:
```
Rename from '.objects/dd/tmp_obj_vaHR8d' to
'./objects/dd/b3a0a9ae0844a5cec83179e25655681c79e' failed. Should I try again?
```

This is the output on the console:
```
$ git push GitManager master
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.04 KiB | 0 bytes/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: error: unable to write sha1 filename ./objects/b8/f4e73eac5b00e3809da26cd02eb5016b9bf417: Permission denied
remote: fatal: failed to write object
error: unpack failed: unpack-objects abnormal exit
To //cedata/qac/REPO/GitManager.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to '//cedata/qac/REPO/GitManager.git'
```

**Comment by dscho** [comment]
> I'm using git for windows 2.5.1 (64bit)

Please test again with 2.5.2(2).

**Comment by AlmAck** [comment]
yes same problem, also with 2.5.2(2). Note: I'm using the portable version.

Here the directory structure of a test repository:
```
$ ls -laR
.:
total 0
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 ./
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 ../
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:36 2f/
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 info/
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 pack/

./2f:
total 1024
drwxr-xr-x 1 giambolu 1049089   0 Sep 14 15:36 ./
drwxr-xr-x 1 giambolu 1049089   0 Sep 14 15:34 ../
-r--r--r-- 1 giambolu 1049089 165 Sep 14 15:36 tmp_obj_KhGB5a

./info:
total 0
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 ./
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 ../

./pack:
total 0
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 ./
drwxr-xr-x 1 giambolu 1049089 0 Sep 14 15:34 ../
```
Do you think can be a server configuration issue? what is strange it that with the old git version I never had this problem.
The tmp file mechanism was already implemented? or has been introduced with version 2.5.x?

**Comment by dscho** [comment]
> Do you think can be a server configuration issue?

It is possible, but unlikely.

> what is strange it that with the old git version I never had this problem.

Well, there have been a couple of changes in how Git does things.

> I think my bug is also releated to this one #236

Unlikely because it was fixed by a change that made it into 2.5.1.

> Rename from '.objects/dd/tmp_obj_vaHR8d' to
> './objects/dd/b3a0a9ae0844a5cec83179e25655681c79e' failed. Should I try again?

This is a smoking gun for a file handle that needs to be released before the file can be renamed.

**Comment by dscho** [comment]
Please note that I cannot do anything about this problem until I can reproduce it here. If you can help me reproduce it quicker, please do so, by all means.

**Comment by ned-martin** [comment]
Same problem, git version 2.6.3.windows.1

Files hosted on Linux, shared via Samba to Windows. Make new repo on Windows. Attempt to commit files.

```
$ git add -A
Rename from '.git/objects/a0/tmp_obj_uRPFra' to '.git/objects/a0/71491d6b88084ae384a76ab7c7f06db011f2c0' failed. Should I try again? (y/n)
error: unable to write sha1 filename .git/objects/a0/71491d6b88084ae384a76ab7c7f06db011f2c0: Permission denied
error: .htaccess: failed to insert into database
error: unable to index file .htaccess
fatal: adding files failed
```

**Comment by rimrul** [comment]
@ned-martin Please provide us with a [MCVE](http://stackoverflow.com/help/mcve) or at least give us as many details as possible(Windows version, Windows bitness, Linux Distro,Linux version, Linux bitness, Samba version and Packet source, Git bitness, Portable Git?). Make it easy for us to reproduce your problem, so we can find a fix. Bumping an issue with "Same Problem here" posts that don't provide additional details to solve the issue doesn't usually help anyone.

**Comment by AlmAck** [comment]
Ok, I managed to get it working. The problem was on the configuration of the samba server.
By adding the flags **force directory mode** and **force create mode** fixed my problem. Here the current configuration I'm using on the server:
```
[mygroup]
        comment = GIT repository
        path = /FileServer/CESMB/GIT
        write list = @myusres
        browseable = no
        read only = yes

        create mask = 0664
        force create mode = 0664
        directory mask = 0775
        force directory mode = 0775
```

**Comment by dscho** [comment]
@AlmAck good job! Thanks for sharing the solution!
