### ISSUE TITLE
git /w spnego authentication

### ISSUE THREAD

**Issue by tkoeller** [git-for-windows/git#389]
Although libcurl is apparently built to support spnego authentication (curl --negotiate works), git is obviously not. I guess it would not be too difficult to enable this feature?

**Comment by dscho** [comment]
Since there is no easy example to reproduce this issue, I am throwing this right back into your court.

Please [install the Git for Windows SDK](https://git-for-windows.github.io/#download-sdk), and test with `/mingw64/bin/curl.exe`. If that works, test Git again with `GIT_CURL_VERBOSE=1`.

**Comment by tkoeller** [comment]
O.K., I did that. As I already wrote, the --negotiate option to curl appears to be working as expected, the server supplies the requested document without requesting credentials. 

Next, I attempted to clone a git repository:

-----------------------------------------------------

$ HTTP_PROXY= GIT_CURL_VERBOSE=1 git clone http://tkoeller@bhr156s.basler.corp:8080/tfs/TWA/TeamDev/_git/pylon
Klone nach 'pylon' ...
* Couldn't find host bhr156s.basler.corp in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying 172.16.21.156...
* Connected to bhr156s.basler.corp (172.16.21.156) port 8080 (#0)
> GET /tfs/TWA/TeamDev/_git/pylon/info/refs?service=git-upload-pack HTTP/1.1
Host: bhr156s.basler.corp:8080
User-Agent: git/2.5.2.windows.2
Accept: */*
Accept-Encoding: gzip
Accept-Language: de-DE, *;q=0.9
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Content-Type: text/html
< Server: Microsoft-IIS/8.5
< X-TFS-ProcessId: f43a2e0e-cb9e-4da2-beb5-40443fbdb01a
< X-FRAME-OPTIONS: SAMEORIGIN
< WWW-Authenticate: Negotiate
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< X-Content-Type-Options: nosniff
< Date: Tue, 15 Sep 2015 08:54:55 GMT
< Content-Length: 1293
<
* Ignoring the response-body
* Connection #0 to host bhr156s.basler.corp left intact
* Issue another request to this URL: 'http://tkoeller@bhr156s.basler.corp:8080/tfs/TWA/TeamDev/_git/pylon/info/refs?service=git-upload-pack'
* Couldn't find host bhr156s.basler.corp in the _netrc file; using defaults
* Found bundle for host bhr156s.basler.corp: 0x9f61d0
* Re-using existing connection! (#0) with host bhr156s.basler.corp
* Connected to bhr156s.basler.corp (172.16.21.156) port 8080 (#0)
> GET /tfs/TWA/TeamDev/_git/pylon/info/refs?service=git-upload-pack HTTP/1.1
Host: bhr156s.basler.corp:8080
User-Agent: git/2.5.2.windows.2
Accept: */*
Accept-Encoding: gzip
Accept-Language: de-DE, *;q=0.9
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Content-Type: text/html
< Server: Microsoft-IIS/8.5
< X-TFS-ProcessId: f43a2e0e-cb9e-4da2-beb5-40443fbdb01a
< X-FRAME-OPTIONS: SAMEORIGIN
< WWW-Authenticate: Negotiate
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< X-Content-Type-Options: nosniff
< Date: Tue, 15 Sep 2015 08:54:55 GMT
< Content-Length: 1293
<
* Ignoring the response-body
* Connection #0 to host bhr156s.basler.corp left intact
* Issue another request to this URL: 'http://tkoeller@bhr156s.basler.corp:8080/tfs/TWA/TeamDev/_git/pylon/info/refs?service=git-upload-pack'
* Couldn't find host bhr156s.basler.corp in the _netrc file; using defaults
* Found bundle for host bhr156s.basler.corp: 0x9f61d0
* Re-using existing connection! (#0) with host bhr156s.basler.corp
* Connected to bhr156s.basler.corp (172.16.21.156) port 8080 (#0)
* Server auth using Negotiate with user 'tkoeller'
> GET /tfs/TWA/TeamDev/_git/pylon/info/refs?service=git-upload-pack HTTP/1.1
Host: bhr156s.basler.corp:8080
Authorization: Negotiate TlRMTVNTUAABAAAAt4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw==
User-Agent: git/2.5.2.windows.2
Accept: */*
Accept-Encoding: gzip
Accept-Language: de-DE, *;q=0.9
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Content-Type: text/html; charset=us-ascii
< Server: Microsoft-HTTPAPI/2.0
< WWW-Authenticate: Negotiate TlRMTVNTUAACAAAADgAOADgAAAA1goniPgf6QazUrqEAAAAAAAAAAJIAkgBGAAAABgOAJQAAAA9HAEUAUgBNAEEATgBZAAIADgBHAEUAUgBNAEEATgBZAAEADgBCAEgAUgAxADUANgBTAAQAFgBiAGEAcwBsAGUAcgAuAGMAbwByAHAAAwAmAEIASABSADEANQA2AFMALgBiAGEAcwBsAGUAcgAuAGMAbwByAHAABQAWAGIAYQBzAGwAZQByAC4AYwBvAHIAcAAHAAgAFLAIMZTv0AEAAAAA
< Date: Tue, 15 Sep 2015 08:54:55 GMT
< Content-Length: 341
<
* Ignoring the response-body
* Connection #0 to host bhr156s.basler.corp left intact
* Issue another request to this URL: 'http://tkoeller@bhr156s.basler.corp:8080/tfs/TWA/TeamDev/_git/pylon/info/refs?service=git-upload-pack'
* Couldn't find host bhr156s.basler.corp in the _netrc file; using defaults
* Found bundle for host bhr156s.basler.corp: 0x9f61d0
* Re-using existing connection! (#0) with host bhr156s.basler.corp
* Connected to bhr156s.basler.corp (172.16.21.156) port 8080 (#0)
* Server auth using Negotiate with user 'tkoeller'
> GET /tfs/TWA/TeamDev/_git/pylon/info/refs?service=git-upload-pack HTTP/1.1
Host: bhr156s.basler.corp:8080
Authorization: Negotiate TlRMTVNTUAADAAAAGAAYAHgAAABKAUoBkAAAAAAAAABYAAAAEAAQAFgAAAAQABAAaAAAABAAEADaAQAANYKI4gYBsR0AAAAPalpY683Kwaxx0XoioXgZR3QAawBvAGUAbABsAGUAcgBHAEUAUgBEADAANwA2ADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKT1giSgr4icSgvNHdPZykgEBAAAAAAAAFLAIMZTv0AGxmMpwNEqZ/gAAAAACAA4ARwBFAFIATQBBAE4AWQABAA4AQgBIAFIAMQA1ADYAUwAEABYAYgBhAHMAbABlAHIALgBjAG8AcgBwAAMAJgBCAEgAUgAxADUANgBTAC4AYgBhAHMAbABlAHIALgBjAG8AcgBwAAUAFgBiAGEAcwBsAGUAcgAuAGMAbwByAHAABwAIABSwCDGU79ABBgAEAAIAAAAIADAAMAAAAAAAAAAAAAAAADAAAAwxTy+PB+JY3Ez9Bvql/9FuE40Y33LuDZqi/YnkjLw5CgAQAAAAAAAAAAAAAAAAAAAAAAAJADAASABUAFQAUAAvAGIAaAByADEANQA2AHMALgBiAGEAcwBsAGUAcgAuAGMAbwByAHAAAAAAAAAAAAAAAAAA8eWJJYJ682kxjpgDLXTo1w==
User-Agent: git/2.5.2.windows.2
Accept: */*
Accept-Encoding: gzip
Accept-Language: de-DE, *;q=0.9
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Content-Type: text/html
< Server: Microsoft-IIS/8.5
< X-TFS-ProcessId: f43a2e0e-cb9e-4da2-beb5-40443fbdb01a
< X-FRAME-OPTIONS: SAMEORIGIN
< WWW-Authenticate: Negotiate
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< X-Content-Type-Options: nosniff
< Date: Tue, 15 Sep 2015 08:54:55 GMT
< Content-Length: 1293
<
* Connection #0 to host bhr156s.basler.corp left intact
Password for 'http://tkoeller@bhr156s.basler.corp:8080':

-----------------------------------------------------

I am prompted to enter a password, which normally indicates that negotiation failed.

**Comment by kostix** [comment]
Couldn't it be related to cURL interpreting URI components in a special way -- just like it had been observed to do [here](https://github.com/git-for-windows/git/issues/234#issuecomment-120440150)?

I'd re-try with the sole `@` in the URI string, like in

     http://@bhr156s.basler.corp:8080

**Comment by tkoeller** [comment]
No, that did not work. Note that I have direct access to the server and there is no proxy involved, unlike the scenario discussed in issue #234, and that I am using plain HTTP w/o SSL/TLS. Also, the command line I used works on a Linux box that is also a member of the same windows domain.

**Comment by kostix** [comment]
Oh, I did not meant proxy, I've just assumed the mechanics cURL uses in both cases may be the same. Since SSO mean you did *not* provide an explicit user name (and the command-line `curl` client has the `-u` and `--proxy-user` options which should be passed the single `:` character to denote empty user name and password to signify they should be taken from the system) I guessed that may be in this case the same logic applies.

**Comment by dscho** [comment]
> I've just assumed the mechanics cURL uses in both cases may be the same.

So would I.

BTW I think it is `:@`, not just `@`. IOW, the clone URL would be something like `https://:@my-server/blub.git`.

**Comment by tkoeller** [comment]
Indeed, the ':@' variant did the trick. Thanks a lot!

**Comment by dscho** [comment]
This sounds like an excellent opportunity to get involved, @tkoeller, by writing an entry for the [Frequently Asked Questions](https://github.com/git-for-windows/git/wiki/FAQ). Would you do that, please?

**Comment by tkoeller** [comment]
I did. Thanks again!

**Comment by dscho** [comment]
Thank you so much!

**Comment by kostix** [comment]
@tkoeller, a minor nitpick: is "domain authentication" is the language used by TFS configuration tools?

I'm asking because what you seem to be using (and the title of this bug implies that) is either Kerberos or SPNEGO (also dubbed Negotiate sometimes) which is a meta mechanism which negotiates either Kerberos or NTLM.  Hence all these three mechanisms stand for "domain authentication" in a sense that they provide SSO when the host is joined a Windows domain.

To may be put this into a different perspective, NTLM can be used to provide SSO on Windows as well as Kerberos and SPNEGO. That is, in most cases, for a client program the actual mechanism being used is irrelevant.  Hence the inability to use NTLM might be a glitch in TFS or a version disparity beteween the client and the server (see [this](https://www.imss.caltech.edu/node/396)).

IOW, I'd try to figure out what's the actual culprit in this case and may be add a note that when saying "domain authentication" you imply Kerberos and NTLM.

**Comment by tkoeller** [comment]
First of all, I am not into Windows administration, and my knowledge in this area is very limited. I am also quite unfamiliar with the terminology. It has always been my understanding that a Windows domain is built upon Kerberos for authentication and LDAP (Active Directory) for everything else. I am also not the administrator of the TFS server.

In its configuration, the TFS server offers a choice of four methods: NTLM, Negotiate, Negotiate/Kerberos and Negotiate/something (I do not remember because it seemed irrelevant to me). I know that in our domain, every server and every user is also a Kerberos principal, and wanted to provide SSO to users on Windows and Linux machines alike (where the Linux machines are also domain members).

Our domain here very definitely uses Kerberos for authentication, which is a boon as it is well supported by Linux. I have no idea if I could have found a solution based on NTLM, and I never pursued this option, because it is of no practical value to me.
