### ISSUE TITLE
"credential-cache unavailable; no unix socket support"

### ISSUE THREAD

**Issue by hickford** [git-for-windows/git#3892]
I tried to run [git-credential-cache]( https://git-scm.com/docs/git-credential-cache) but got an error:

```
> git credential-cache
fatal: credential-cache unavailable; no unix socket support
```

Others have reported the same error https://stackoverflow.com/questions/67951554/error-fatal-credential-cache-unavailable-no-unix-socket-support

A **workaround** is to install and configure [Git Credential Manager](https://github.com/GitCredentialManager/git-credential-manager#windows) `git-credential-manager-core --configure`. The [default credential store](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/credstores.md#windows-credential-manager) Windows Credential Manager works well.

* * *

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19043.1682]
```

**Comment by dscho** [comment]
> fatal: credential-cache unavailable; no unix socket support

Well, it is true. Windows does not have Unix socket support in general. As per [this comment](https://github.com/GitCredentialManager/git-credential-manager/issues/723#issuecomment-1146817218):

> echnically, since Git v2.34.0, `git-credential-cache.exe` [_can_ be built and run on Windows](https://github.com/git/git/commit/c2e799012b3). Unix Sockets support [has been introduce into Windows](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/). The problem is that you need Windows 10 build 17061 or later, and Git for Windows still supports even Vista (although [it has been announced that Git for Windows will drop supporting Vista really soon now](https://github.com/git-for-windows/build-extra/commit/c7e2c3cda90f4681400852d1207f74e96d8b1ff6)).

Now, the question is: _how much_ are you interested in getting Git for Windows to support `credential-cache` on Windows versions that support Unix sockets @hickford? Interested enough to work on a PullRequest? If so, I will be glad to assist, but I won't be able to justify the time to work on it myself.

**Comment by hickford** [comment]
How might that work? I don't have much C experience. Is it possible to change an optional compile-time dependency to a conditional runtime dependency? Or would Git for Windows have to compile credential-cache with and without sockets, and install the appropriate copy for the system?

**Comment by rimrul** [comment]
It is possible to query for unix socket support at runtime and we have ways to load CRT functions at runtime if available, so that approach is theoretically feasible.

**Comment by hickford** [comment]
> ways to load CRT functions at runtime if available

@rimrul Do you have any examples to follow?  Presumably this would in the Git for Windows repo rather than upstream Git? 

According to @carenas [credential-cache functions on Windows](https://lore.kernel.org/git/20210914072600.11552-1-carenas@gmail.com/ ), if you compile it.

**Comment by rimrul** [comment]
Yes, of course. Sorry for not providing you with more actionable info on this.

We have the macros `DECLARE_PROC_ADDR()` and `INIT_PROC_ADDR()` defined in [compat/win32/lazyload.h](https://github.com/git-for-windows/git/blob/main/compat/win32/lazyload.h). 

You can see them in use in [t/helper/test-drop-caches.c](https://github.com/git-for-windows/git/blob/main/t/helper/test-drop-caches.c#L90-L111),  [compat/winansi.c](https://github.com/git-for-windows/git/blob/main/compat/winansi.c#L49-L73), [compat/win32/trace2_win32_process_info.c](https://github.com/git-for-windows/git/blob/main/compat/win32/trace2_win32_process_info.c#L146-L153) and two times in [compat/mingw.c](https://github.com/git-for-windows/git/blob/main/compat/mingw.c#L1279-L1288).

**Comment by hickford** [comment]
@rimrul interesting.  This seems different. If I understand correctly, the winsock2.h [`socket` function](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-socket) Ws2_32.dll is available on all versions of Windows. 

What happens currently if you build with sockets on Windows 10 then try to run on Windows 7?

**Comment by dscho** [comment]
> What happens at runtime if you build with sockets on Windows 10 then try to run on Windows 7?

@hickford It won't work. Likewise if you run on older Windows 10 that lack support for `AF_UNIX`. Something we need to test specifically, to ensure that the users will see a helpful error message (and not, say, a crash).

**Comment by rimrul** [comment]
> > What happens at runtime if you build with sockets on Windows 10 then try to run on Windows 7?
> 
> @hickford It won't work. Likewise if you run on older Windows 10 that lack support for `AF_UNIX`. Something we need to test specifically, to ensure that the users will see a helpful error message (and not, say, a crash).

I did some testing. Running Git for Windows 2.43.0 built without `NO_UNIX_SOCKETS` on Windows 8.1 we don't get a crash. Directly calling `git credential-cache` produces the usage message as it would on systems with unix sockets. Actually using the credential helper as a credential helper in `git clone` produces this not great error message:
> fatal: unable to connect to cache daemon: Unknown error

I think we could improve that error message with a runtime check.

* The simplest check would be to see if `GetVersion()` reports that we're on Windows 10 build 17063 or newer. That should work for most cases, but might not work in certain edge cases.
* Microsoft recommends checking [`sc query afunix`](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/), but I'd rather not shell out to a new process if we don't have to. We could probably achieve the same result using `OpenServiceA()`/`OpenServiceW()` and `QueryServicestatus()`/`QueryServiceStatusEx()`,
* We could also just try wether we can successfully create a unix socket at startup.

**Comment by abc1000200** [comment]
> I tried to run [git-credential-cache](https://git-scm.com/docs/git-credential-cache) but got an error:
> 
> ```
> > git credential-cache
> fatal: credential-cache unavailable; no unix socket support
> ```
> 
> Others have reported the same error https://stackoverflow.com/questions/67951554/error-fatal-credential-cache-unavailable-no-unix-socket-support
> 
> A **workaround** is to install and configure [Git Credential Manager](https://github.com/GitCredentialManager/git-credential-manager#windows) `git-credential-manager-core --configure`. The [default credential store](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/credstores.md#windows-credential-manager) Windows Credential Manager works well.
> 
> ### Setup
> * Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
> 
> ```
> $ git --version --build-options
> git version 2.36.1.windows.1
> cpu: x86_64
> built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
> sizeof-long: 4
> sizeof-size_t: 8
> shell-path: /bin/sh
> feature: fsmonitor--daemon
> ```
> 
>  * Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
> 
> ```
> $ cmd.exe /c ver
> Microsoft Windows [Version 10.0.19043.1682]
> ```

### KAMPANAT THUMWONG

**Comment by hickford** [comment]
@rimrul Exciting ideas!

> Git for Windows 2.43.0 built without NO_UNIX_SOCKETS

Please could you share `git-credential-cache.exe` and `git-credential-cache--daemon.exe` here?

**Comment by rimrul** [comment]
> > Git for Windows 2.43.0 built without NO_UNIX_SOCKETS
> 
> Please could you share `git-credential-cache.exe` and `git-credential-cache--daemon.exe` here?

I could do that, but Do you really want my locally built binaries that are just without `NO_UNIX_SOCKETS`? Wouldn't it make more sense to extract the binarie with the dynamic detection from the `windows-artifacts` CI build artifact at https://github.com/git-for-windows/git/actions/runs/7491375798?

**Comment by hickford** [comment]
@rimrul I can't find the binaries in windows-artifacts.zip.

**Comment by ogauge** [comment]
some one stole all my files and just so happens it was done by google
