### ISSUE TITLE
Invoking /usr/bin/bash with -li and -c flag doesn't provide an interactive-login shell

### ISSUE THREAD

**Issue by StarkRights** [git-for-windows/git#3897]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64bit

```
$ git --version --build-options

git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
 Windows 11, 64 bit | Version 21H2, OS Build 22000.675

$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.675]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am running in Win11 from the windows terminal, however, I'm using the default Windows Powershell, so there shouldn't be anything funky there afaik. 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git-Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:/Program Files/git/usr/bin/bash.exe -i -l -c "echo 'test'"
or
Start-Process -FilePath "./sh.exe" -ArgumentList "-l","-i","-c echo 'test'"
```
 - What did you expect to occur after running these commands?

I expected that an interactive-login shell would've been spawned, with "this is a command" echoed in it. 

 - What actually happened instead?

The command is echoed and the shell exits.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

 ## Issue writeup:
 For context, I've found this issue while trying to create a startup action within Windows terminal that'll open a new Git-Bash instance, and then run `git fetch; git status`. It's my understanding that this should be pretty simply accomplished by providing a `-c "<command>"` argument to the bash executable, but it seems like whatever I do it refuses to both run the commands *and* give me an interactive shell.
 
 I've isolated the issue away from the potential issues with windows terminal, and have tested straight from powershell, running the command given in the "What commands did you run" section, with the most minimal command I can, a simple echo, provided to it. 
 
 Testing has shown that:
  - The bash shell runs fine. I can run `'C:/Program Files/Git/usr/bin/bash.exe' -i -l` and get the bash shell perfectly fine. (See Fig. 1)
  - It also runs fine with the powershell `Start-Process` applet, using `Start-Process -FilePath "./sh.exe" -ArgumentList "-l","-i"` (See Fig. 2)
  - When running the `bash.exe` directly with the `-c` flag, bash is apparently launched and the command run, but an interactive/login shell is not given. (See Fig. 3)
  - When running the `Start-Process` applet & adding `,"-c echo 'test'"` to the end of `-ArgumentList`, the process appears to spawn, run the command, and then die- effectively resulting in 'nothing' being done. (See Fig. 4)
 
### Images & Figures
  
  
  <details>
    <summary><b>Fig. 1</b></summary>

    ```
    PS C:\Program Files\Git\usr\bin> Start-Process -FilePath "./bash.exe" -ArgumentList "-l","-i","-c echo 'testing'"
    PS C:\Program Files\Git\usr\bin>
    ```
  

  ![image](https://user-images.githubusercontent.com/19852222/173692064-e2d45f7b-ef33-4640-844b-bc74b733a25d.png)
  </details>
   
  
  <details>
  <summary><b>Fig. 2</b></summary>

  ```
  PS C:\Program Files\Git\usr\bin> Start-Process -FilePath "./bash.exe" -ArgumentList "-l","-i" 
  bash: cut: command not found 
  xxxx@DESKTOP-G0C4LRT  /usr/bin  $
  ```
  

  
  ![image](https://user-images.githubusercontent.com/19852222/173692299-35f12af5-7b33-4b37-9353-238b0fb75f06.png)
  The `MSYS:/usr/bin` tab is a bash shell that was spawned by the command 
  </details>
    
  
  <details>
  <summary><b>Fig. 3</b></summary>

   ```
  PS C:\Program Files\Git\usr\bin> ./bash.exe -i -l -c "echo 'im working'"
  im working
  PS C:\Program Files\Git\usr\bin>
  ```
  
  ![image](https://user-images.githubusercontent.com/19852222/173691619-ded58245-f390-42a5-ba57-3d57a7c58444.png)
  
  </details>
  
  
  
  <details>
  <summary><b>Fig. 4</b></summary>

  ```
  PS C:\Program Files\Git\usr\bin> Start-Process -FilePath "./bash.exe" -ArgumentList "-l","-i","-c echo 'testing'"
  PS C:\Program Files\Git\usr\bin>
  ```
  
  
  ![image](https://user-images.githubusercontent.com/19852222/173693937-f806dc24-853c-4a0d-a5b8-8f4f9220e5a5.png)
  This one very, very briefly opens another tab in terminal- presumably a bash shell with a lifetime long enough to run `echo testing` and die- but ultimately leaves me with no shell
  </details>

**Comment by StarkRights** [comment]
A couple of things of note:
 - In the [bash documentation](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Invoking-Bash), `-c` invocation "read[s] and execute[s] commands from the first non-option argument command_string, then exit[s]". Maybe this means that, even if you 'force' an interactive shell with `-i`, -c will force an exit?
 - There is a flag, `--rcfile <filename>` to run commands from a file other than your `.bashrc`, but I don't necessarily want to *not* run my own .bashrc in favor of running a different one

**Comment by rimrul** [comment]
>  - There is a flag, `--rcfile <filename>` to run commands from a file other than your `.bashrc`, but I don't necessarily want to *not* run my own .bashrc in favor of running a different one. 

One approach would be sourcing `~/.bashrc` from the file that's passed in.

**Comment by rimrul** [comment]
> I _think_ this'll end up being closed as "not-a-bug", but I'd love a clarification on whether or not this really is the intended interaction between the -c and -li flags though before it gets closed out.

I've checked this against a bash on linux, and it does behave the same. 

> The "then exit" part of `-c`'s doc and the "forces interactive shell" if `-i` seem kind of "immovable object meets unstoppable force"-y

I think bash doesn't take "interactive shell" to mean "can't exit before any user interaction", but rather "[enable these behaviours](https://www.gnu.org/software/bash/manual/html_node/Interactive-Shell-Behavior.html)". And with that definition suddenly the immovable object is very movable.

**Comment by dscho** [comment]
> * In the [bash documentation](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Invoking-Bash), `-c` invocation "read[s] and execute[s] commands from the first non-option argument command_string, then exit[s]". I guess it's probably intended that, even if you 'force' an interactive shell with `-i`, -c will force an exit.

Yes, that's my read on it, too.

> I guess you could also workaround this just via invoking two commands, a la `./bash.exe -c <command>; ./bash.exe -li`, but it feels.. "Hacky" implies too much jank, I guess just not quite as one would expect.

The best I can offer is this: `& 'C:/Program Files/Git/usr/bin/bash.exe' -l -c "echo hello && bash -i"`.

Also, [this StackOverflow post](https://unix.stackexchange.com/questions/277312/is-the-shell-created-by-bash-i-c-command-interactive) seems relevant.

**Comment by StarkRights** [comment]
Thanks for all the feedback & confirmation gent, much appreciated :)

I'll get this closed out then!
