### ISSUE TITLE
"Out of memory" error on `git clone` with self-signed certificate

### ISSUE THREAD

**Issue by dpeger** [git-for-windows/git#3899]
- [x]  I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.2928]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Issue is not shell related and occurs on all different shells.

 - What commands did you run to trigger this issue? If you can provide a  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)  this will help us understand the issue.

I run Gitlab CE edition in Docker Desktop for Windows (https://github.com/danieleagle/gitlab-https-docker). As described (https://github.com/danieleagle/gitlab-https-docker/blob/master/README.md#generating-a-self-signed-certificate) I created a private key and a certificate for SSL communication. In Gitlab I created a new repository with a single small yaml file in it.

I tried to clone the repo and specified the local path to the self signed certificate with the clone command. But when I executed the command I got an "Out of memory" error:

```
git -c http.sslcainfo=C:\path\to\server-cert.pem clone https://host.docker.internal:10443/my-group/my-repo
Cloning into 'my-repo'...
fatal: unable to access 'https://host.docker.internal:10443/my-group/my-repo/': Out of memory
```

I also tried to set the `GIT_SSL_CAINFO` environment variable. But cloning resulted in the same "Out of memory" issue. I tried to clone the repo on linux (inside a debian Docker container) amd it worked without issues.

On Windows I was only able to clone the repo by disabling SSL verification for the respective server:

```
git -c http.sslverify=0 clone https://host.docker.internal:10443/my-group/my-repo
Cloning into 'my-repo'...
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
git: 'credential-manager' is not a git command. See 'git --help'.

The most similar command is
        credential-manager-core
warning: redirecting to https://host.docker.internal:10443/my-group/my-repo.git/
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), done.
Resolving deltas: 100% (1/1), done.
```

 - What did you expect to occur after running these commands?

I expected the repo to be cloned without the need to disable SSL verification.

 - What actually happened instead?

As said, git reports an "Out of memory" error for the repo

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Its a local repo running inside Docker Desktop (see [attached docker-compose file](https://github.com/git-for-windows/git/files/8918070/docker-compose.yaml.txt)). Its setup from scratch with Gitlab CE (latest/15.0) no special config applied.

**Comment by dscho** [comment]
Oh wow, what a terrible bug!

To be honest, this is a new one for me, and I have no idea where this might be coming from. Would you kindly run the failing command again, after setting `GIT_TRACE=1`? I _think_ the error message might be produced by `git-remote-https.exe`, but I am not 100% certain.

**Comment by dpeger** [comment]
Here you go. I set `GIT_CURL_VERBOSE=1` and `GIT_TRACE=1`

```
git -c http.sslcainfo=C:\path\to\server-cert.pem clone https://host.docker.internal:10443/my-group/my-repo

12:59:07.602540 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
12:59:07.603539 git.c:459               trace: built-in: git clone https://host.docker.internal:10443/my-group/my-repo
Cloning into 'my-repo'...
12:59:07.620539 run-command.c:654       trace: run_command: git remote-https origin https://host.docker.internal:10443/my-group/my-repo
12:59:07.632535 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
12:59:07.634533 git.c:748               trace: exec: git-remote-https origin https://host.docker.internal:10443/my-group/my-repo
12:59:07.634533 run-command.c:654       trace: run_command: git-remote-https origin https://host.docker.internal:10443/my-group/my-repo
12:59:07.649926 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
12:59:07.667533 http.c:689              == Info: Couldn't find host host.docker.internal in the (nil) file; using defaults
12:59:07.676534 http.c:689              == Info:   Trying 10.88.1.90:10443...
12:59:07.676534 http.c:689              == Info: Connected to host.docker.internal (10.88.1.90) port 10443 (#0)
12:59:07.677092 http.c:689              == Info: ALPN, offering h2
12:59:07.677599 http.c:689              == Info: ALPN, offering http/1.1
12:59:07.677639 http.c:689              == Info:  CAfile: C:\path\to\server-cert.pem
12:59:07.677639 http.c:689              == Info:  CApath: none
12:59:07.678158 http.c:689              == Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):
12:59:07.687630 http.c:689              == Info: TLSv1.3 (IN), TLS handshake, Server hello (2):
12:59:07.687630 http.c:689              == Info: TLSv1.2 (IN), TLS handshake, Certificate (11):
12:59:07.687630 http.c:689              == Info: TLSv1.2 (IN), TLS handshake, Server key exchange (12):
12:59:07.688170 http.c:689              == Info: TLSv1.2 (IN), TLS handshake, Server finished (14):
12:59:07.688170 http.c:689              == Info: TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
12:59:07.688170 http.c:689              == Info: TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
12:59:07.688170 http.c:689              == Info: TLSv1.2 (OUT), TLS handshake, Finished (20):
12:59:07.689316 http.c:689              == Info: TLSv1.2 (IN), TLS handshake, Finished (20):
12:59:07.689316 http.c:689              == Info: SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
12:59:07.689316 http.c:689              == Info: ALPN, server accepted to use h2
12:59:07.689316 http.c:689              == Info: Server certificate:
12:59:07.689316 http.c:689              == Info:  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=host.docker.internal
12:59:07.689316 http.c:689              == Info:  start date: Jun 15 14:20:44 2022 GMT
12:59:07.689316 http.c:689              == Info:  expire date: Jun 15 14:20:44 2023 GMT
12:59:07.689316 http.c:689              == Info: Closing connection 0
12:59:07.689316 http.c:689              == Info: TLSv1.2 (OUT), TLS alert, close notify (256):
fatal: unable to access 'https://host.docker.internal:10443/my-group/my-repo/': Out of memory
```

**Comment by dscho** [comment]
Do you think you could provide a small reproducer, e.g. a node.js script with a hard-coded self-signed certificate? (That HTTPS server does not even need to serve any Git repository, as we're only interested in the handshaking phase.)

Alternatively, I could offer assistance with debugging this in `gdb` in your setup.

**Comment by dscho** [comment]
I added `127.0.0.1 host.docker.internal` to my `C:\Windows\system32\drivers\etc\hosts`, verified with `ping host.docker.internal` that I can ping it, then repeated the exercise, but I still get the Git message about a missing git repository, i.e. _not_ an out-of-memory.

**Comment by dpeger** [comment]
My setup is pretty much the same.

Maybe the certificates make the difference?? Here is the key and the 2 self-signed certificates I was able to reproduce the issue with:

* [server-key.pem](https://github.com/git-for-windows/git/files/8974009/server-key.pem.txt)
* [server-cert.pem](https://github.com/git-for-windows/git/files/8974010/server-cert.pem.txt)
* [server-cert-san.pem](https://github.com/git-for-windows/git/files/8974011/server-cert-san.pem.txt)

Otherwise we will need a debugging session...

**Comment by dscho** [comment]
> ```
> $ git -c http.sslcainfo=server-cert.pem clone https://host.docker.internal:8000/my-repo
Cloning into 'my-repo'...
fatal: https://host.docker.internal:8000/my-repo/info/refs not valid: is this a git repository?
> ```

Same thing...

Do you have some anti-malware running, perchance? If that's the case, I have a hunch that they might do infernal things with the Git process that might cause this.

**Comment by dpeger** [comment]
Sure, there MS Defender running I think.

However I'm wondering how it's possible that the cert without SAN causes the OOM and the one with SAN is working without issues?!

I'm going to setup an isolated VM and will try to reproduce there...

**Comment by dscho** [comment]
@dpeger the route I would take is to try to debug this in `gdb`. If you want to give this a try, [this wiki page](https://github.com/git-for-windows/git/wiki/Debugging-Git#debugging-git-using-the-gnu-debugger-gdb) should get you started. After Git for Windows v2.37.0 is out (most likely later today, following Git v2.37.0 which is [scheduled for today](https://tinyurl.com/gitcal)), I might have a little time and we could set up a pairing session if you'd like.

**Comment by dpeger** [comment]
I just tried the certificates in a virtual Windows 2019 environment and it's working as expected (i.e. no OOM for both certificates...)

I installed the SDK and compiled the project without optimizations and stuff, but I'm not familiar with gdb at all...

**Comment by dpeger** [comment]
Ok, I updated to git 2.37.0 yesterday and can't reproduce the issue any longer. Now I can issue git command against a server without OOM no matter which self-signed certificate (with or without SAN) the server is using.

**Comment by dscho** [comment]
> Ok, I updated to git 2.37.0 yesterday and can't reproduce the issue any longer. Now I can issue git commands against a server without OOM no matter which self-signed certificate (with or without SAN) the server is using.

It is good news that you no longer have the issue! I would have loved to understand better what was going on, but it is probably not necessary to investigate further (unless somebody else _also_ experiences the issue, in which case we can tap into this here ticket to get a head start).
