### ISSUE TITLE
Git does not read `.config/git/config` in certain cases

### ISSUE THREAD

**Issue by hoang-himself** [git-for-windows/git#3907]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.160]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

### Details

 - Which terminal/shell are you running Git from?

Windows Terminal, PowerShell

 - Description

I have my gitconfig file symlinked to `~/.config/git/config`. Git for Windows still reads this file normally, even though the Git Book does not state this explicitly. Proof:

1. Open Windows Terminal from the Start menu
2. Open Pwsh 7.2.4 in Windows Terminal
3. `git config user.email`

 - Expected

```
PS> git config user.email
user@example.com
```

<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/10150902/174839196-288bff95-7180-4907-ac4d-bd366fb49359.png)

</details>

Running `pwsh` as Admin also works.

<details><summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/10150902/174840044-e4963063-09b7-4a53-9c34-97191adefa00.png)

</details>

However, I usually right click a folder then choose `Open in Terminal` or just use the `pwsh` terminal in VSCode.

<details><summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/10150902/174841860-fd538057-5ff7-49b1-964b-9796931dd473.png)

</details>

<details><summary>Screenshot 4</summary>

![image](https://user-images.githubusercontent.com/10150902/174842001-6247f57a-aef7-4006-91fe-c54cdc99013a.png)

</details>

Git does not read `.config/git/config`. I tried copying the real file instead of the symlink and nothing changes. I also tried working with folders on the `C` drive and nothing changes.

**Comment by hoang-himself** [comment]
Respectively

<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/10150902/174953787-7aeae862-5344-4b3f-987c-d72bc53e6bf0.png)

</details>

<details><summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/10150902/174953874-b9cc22c3-6a33-4f98-9d0b-12e15c70bbf5.png)

</details>

<details><summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/10150902/174953965-518030c4-d829-44ee-bb03-2d0451a8ff4a.png)

</details>

<details><summary>Screenshot 4</summary>

![image](https://user-images.githubusercontent.com/10150902/174954073-de25535f-94a2-45f7-880e-bfd4a0373a70.png)

</details>

**Comment by dscho** [comment]
Hmm. That does not shed enough light into the issue for me. Maybe throw `--show-scope` into the fray?

**Comment by rimrul** [comment]
Could you also check the contents of theses environment variables in all environments:

`$env:HOME`, `$env:HOMEDRIVE`, `$env:HOMEPATH`, `$env:USERPROFILE`

**Comment by hoang-himself** [comment]
`--show-scope` doesn't seem to help much

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10150902/175042768-5e56b26f-950f-42a8-890c-e61445b82257.png)

</details>

---

My computer doesn't have `$env:HOME`, other variables are the same in all environments.

**Comment by siprbaum** [comment]
`~/.config/git/config` is handeled directly by git, according to https://git-scm.com/docs/git-config#FILES
So symlinking might not be necessary.

But it could be that `XDG_CONFIG_HOME` environment variable is configured differently.
