### ISSUE TITLE
Install for all users impossible, Win7 pro, Administrator, 2.5.2

### ISSUE THREAD

**Issue by Laro88** [git-for-windows/git#391]
I can't get install for all to work, binaries and all keeps going into users local folder breaking the path.
So I keep ending up with bin, cmd, dev and all the other subfolders in here:
```
C:\Users\u32083\AppData\Local\Programs\Git
```
Installer: Git-2.5.2.2-64-bit.exe

running the installer as admin does not solve the problem, recent installs (~+1 month ago) was fine - meaning that they wen't into c:\program files\ as expected.

I can't recollect if there was a "for all users" earlier on - but I can't find one now :-)

GitExtensions seems to work fine after update and path fixin therein, however it is a single user install only.

**Comment by dscho** [comment]
> I can't get install for all to work, it keeps going into users local folder breaking the path.

I do not understand. What keeps going into users' local folders, and what is breaking the path? Render me utterly confused.

**Comment by dscho** [comment]
@Laro88 please note that I cannot help you if you do not respond.

**Comment by Laro88** [comment]
Dear Hr. Schindelin.
 
I updated both issues (install going in local & global .gitignore) without writing a new post - I actually thought owners were notified upon changes in posts - apologies. 

Best regards
Jes Ramsing
 
Date: Tue, 15 Sep 2015 23:42:22 -0700

**Comment by dscho** [comment]
According to [this StackOverflow post](http://stackoverflow.com/questions/15605659/inno-setup-default-install-folder-change) (which came up as first hit in my web search), this can happen if you installed Git into a funny directory previously. I could imagine that you ran the installer as plain user first, and since it could not write into `C:\Program Files\Git` it fell back to a directory it *could* write to. And subsequent installations just remember that location and use it.

The same StackOverflow post suggests that uninstalling the program and installing it again should fix the issue. Have you tried that?

**Comment by Laro88** [comment]
I was googling after an explanation, without finding that mentioned.
My previous installation was default all the way, and it was using Program Files\Git - at least that was in the path.
The installer ran the uninstaller from the old version as part of the flow - could this be the cause?
I will try to uninstall and then run the Installer again.

**Comment by dscho** [comment]
> The installer ran the uninstaller from the old version as part of the flow - could this be the cause?

No, because the installer has read the information about the previous installation by the time the uninstaller runs. Besides, if anything, it would *fix* the issue, according to the StackOverflow post.

**Comment by dscho** [comment]
> I will try to uninstall and then run the Installer again.

It's been a while... Any news?

**Comment by Laro88** [comment]
Actually while investigating another issue I think that my HOME and USERPROFILE globals has changed which could be the cause. We had an Active Directory push to our machines between the two installations, and I suspect that one of the two variables changed in this - without being certain though.
I am doing some clean installs on some machines in the near future, and there I will keep a close eye on the installation directories.
