### ISSUE TITLE
Uninstall of Git 2.36.1 isn't complete

### ISSUE THREAD

**Issue by rosti-il** [git-for-windows/git#3922]
To install the new 2.37.0 release I wanted to uninstall the previously installed 2.36.1 version. Before starting the uninstall I closed Git Bash and IntelliJ IDEA. The uninstall process in the "Control Panel --> Programs and Features" finished without any error, however `C:\Program Files\Git\mingw64\bin` and `C:\Program Files\Git\mingw64\libexec\git-core` directories with many executable files were not removed. I thought that maybe after my computer reboot they will be removed but reboot didn't help. During the reboot there was a message that some git related process can't be shut down, but after a few seconds it disappeared by itself (without my intervention) and Windows finished the reboot process.

OS version: Windows 10 Enterprise 21H2
This is corporate computer with Sophos antivirus, BeyondTrust Privilege Management and many corporate policies that I can't change. Maybe one of those corporate things prevented the uninstall process to work properly. But why no error was printed out? I suppose the uninstall processes should check that its own work done properly.

**Comment by dscho** [comment]
Thank you for the report.

However, this is very, very strange. Maybe you had enabled the FSMonitor and it was still running?

As to the files, [all the `.exe` files in `bin` and `libexec\git-core` are expected to be deleted](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L230-L234).

[Even the hard-linked (or copied) `.dll` files in `libexec\git-core` are expected to be deleted](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L239-L240).

Finally, the [`libexec\git-core`, the `libexec`, as well as the `mingw64` directory itself are expected to be deleted](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L277-L279), as long as they are empty. (Note: there should probably be an entry for the `bin` directory, too. Would make for a fine first code contribution...)

@rosti-il you would not happen by any chance to be able to repeat installing v2.36.1 and the uninstalling it with logging enabled, would you? The uninstaller is located in `C:\Program Files\Git\unins???.exe` (with `???` typically being `000` or `001`), and it understands [a `/LOG` option](https://jrsoftware.org/ishelp/index.php?topic=uninstcmdline&anchor=LOG)).

**Comment by dscho** [comment]
> Maybe you had enabled the FSMonitor and it was still running?

No, I don't think that could be the problem because [`ShutdownFSMonitorDaemons()`](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L584-L651) is called [from `RefreshProcessList()`](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L677), which is in turn called [in `InitializeUninstaller()`](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L3707).

**Comment by rosti-il** [comment]
I tried to reproduce this bug now again with both the latest 2.37.0 and the previous 2.36.1 versions on the same computer and this time uninstall worked properly - only the `etc/gitconfig` reminded after uninstall that is correct.

Could this bug be related to Windows hibernate? Before this bug happened today my computer (laptop) was booted after a yesterday's hibernation.

**Comment by dscho** [comment]
> Could this bug be related to Windows hibernate?

I don't see how that could be the case...

> I tried to reproduce this bug now again with both the latest 2.37.0 and the previous 2.36.1 versions on the same computer and this time uninstall worked properly

Hmm. Maybe the hard-linked `.exe` files _somehow_ got write-protected in the faulty run?

In any case, it's good to know that the issue does not simply repeat every time.

> - only the `etc/gitconfig` reminded after uninstall that is correct.

Hmm. I am not sure that we should keep it there... We [do delete the `git-bash` config](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L283), and we should probably do the very same for the system gitconfig.

**Comment by rosti-il** [comment]
> > I tried to reproduce this bug now again with both the latest 2.37.0 and the previous 2.36.1 versions on the same computer and this time uninstall worked properly
> 
> Hmm. Maybe the hard-linked `.exe` files _somehow_ got write-protected in the faulty run?

Or locked by the Sophos antivirus or some other corporate stuff like that? The interesting fact is that only (some?) `.exe` files were not removed. All other, including `.dll`, were removed.

> In any case, it's good to know that the issue does not simply repeat every time.

Could the installer check the uninstall process is finished properly?

> > * only the `etc/gitconfig` reminded after uninstall that is correct.
> 
> Hmm. I am not sure that we should keep it there... We [do delete the `git-bash` config](https://github.com/git-for-windows/build-extra/blob/ed94eb0f284709b7cfe410f99f266c3a61cfaf74/installer/install.iss#L283), and we should probably do the very same for the system gitconfig.

I remember there was another bug report, maybe even by me, about system gitconfig should not be deleted. I still think this is a more correct behavior. What happen in a regular Linux distro if the Git package is uninstalled? Does it also uninstall its system configuration or keep it?

**Comment by rosti-il** [comment]
@dscho Now it happened again with 2.37.0 version. After Git is already uninstalled (from Control Panel | Programs and Features) and the appropriate message about a successful uninstall was already displayed Git still appears in the "Programs and Features". If try to uninstall it again this message is shown:
![image](https://user-images.githubusercontent.com/45571812/178708221-b18323f6-8fcb-4d5a-a165-a793d0513bc0.png)
At the same time I see some `git.exe` process in suspended mode in the Task Manager:
![image](https://user-images.githubusercontent.com/45571812/178708496-9afc0fd4-12eb-4d11-93ae-4d3d46fe6c31.png)
This suspended process seems locking the `git.exe` file and all of its hard links inside the `mingw64` sub directory:
```cmd
C:\Program Files\Git\mingw64\bin>fsutil hardlink list git.exe
\Program Files\Git\mingw64\libexec\git-core\git-am.exe
\Program Files\Git\mingw64\libexec\git-core\git-add.exe
\Program Files\Git\mingw64\libexec\git-core\git-apply.exe
\Program Files\Git\mingw64\libexec\git-core\git-archive.exe
\Program Files\Git\mingw64\libexec\git-core\git-annotate.exe
\Program Files\Git\mingw64\bin\git.exe
\Program Files\Git\mingw64\libexec\git-core\git-bisect--helper.exe
\Program Files\Git\mingw64\libexec\git-core\git-blame.exe
\Program Files\Git\mingw64\libexec\git-core\git-branch.exe
\Program Files\Git\mingw64\libexec\git-core\git-bugreport.exe
\Program Files\Git\mingw64\libexec\git-core\git-bundle.exe
\Program Files\Git\mingw64\libexec\git-core\git-cat-file.exe
\Program Files\Git\mingw64\libexec\git-core\git-check-attr.exe
\Program Files\Git\mingw64\libexec\git-core\git-check-ignore.exe
\Program Files\Git\mingw64\libexec\git-core\git-check-mailmap.exe
\Program Files\Git\mingw64\libexec\git-core\git-check-ref-format.exe
\Program Files\Git\mingw64\libexec\git-core\git-checkout--worker.exe
\Program Files\Git\mingw64\libexec\git-core\git-checkout-index.exe
\Program Files\Git\mingw64\libexec\git-core\git-checkout.exe
\Program Files\Git\mingw64\libexec\git-core\git-clean.exe
\Program Files\Git\mingw64\libexec\git-core\git-clone.exe
\Program Files\Git\mingw64\libexec\git-core\git-column.exe
\Program Files\Git\mingw64\libexec\git-core\git-commit-graph.exe
\Program Files\Git\mingw64\libexec\git-core\git-commit-tree.exe
\Program Files\Git\mingw64\libexec\git-core\git-commit.exe
\Program Files\Git\mingw64\libexec\git-core\git-config.exe
\Program Files\Git\mingw64\libexec\git-core\git-count-objects.exe
\Program Files\Git\mingw64\libexec\git-core\git-credential-cache--daemon.exe
\Program Files\Git\mingw64\libexec\git-core\git-credential-cache.exe
\Program Files\Git\mingw64\libexec\git-core\git-credential-store.exe
\Program Files\Git\mingw64\libexec\git-core\git-credential.exe
\Program Files\Git\mingw64\libexec\git-core\git-describe.exe
\Program Files\Git\mingw64\libexec\git-core\git-diff-files.exe
\Program Files\Git\mingw64\libexec\git-core\git-diff-index.exe
\Program Files\Git\mingw64\libexec\git-core\git-diff-tree.exe
\Program Files\Git\mingw64\libexec\git-core\git-diff.exe
\Program Files\Git\mingw64\libexec\git-core\git-difftool.exe
\Program Files\Git\mingw64\libexec\git-core\git-env--helper.exe
\Program Files\Git\mingw64\libexec\git-core\git-fast-export.exe
\Program Files\Git\mingw64\libexec\git-core\git-fast-import.exe
\Program Files\Git\mingw64\libexec\git-core\git-fetch-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-fetch.exe
\Program Files\Git\mingw64\libexec\git-core\git-fmt-merge-msg.exe
\Program Files\Git\mingw64\libexec\git-core\git-for-each-ref.exe
\Program Files\Git\mingw64\libexec\git-core\git-for-each-repo.exe
\Program Files\Git\mingw64\libexec\git-core\git-fsck.exe
\Program Files\Git\mingw64\libexec\git-core\git-fsmonitor--daemon.exe
\Program Files\Git\mingw64\libexec\git-core\git-gc.exe
\Program Files\Git\mingw64\libexec\git-core\git-get-tar-commit-id.exe
\Program Files\Git\mingw64\libexec\git-core\git-grep.exe
\Program Files\Git\mingw64\libexec\git-core\git-hash-object.exe
\Program Files\Git\mingw64\libexec\git-core\git-help.exe
\Program Files\Git\mingw64\libexec\git-core\git-hook.exe
\Program Files\Git\mingw64\libexec\git-core\git-index-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-init-db.exe
\Program Files\Git\mingw64\libexec\git-core\git-interpret-trailers.exe
\Program Files\Git\mingw64\libexec\git-core\git-log.exe
\Program Files\Git\mingw64\libexec\git-core\git-ls-files.exe
\Program Files\Git\mingw64\libexec\git-core\git-ls-remote.exe
\Program Files\Git\mingw64\libexec\git-core\git-ls-tree.exe
\Program Files\Git\mingw64\libexec\git-core\git-mailinfo.exe
\Program Files\Git\mingw64\libexec\git-core\git-mailsplit.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge-base.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge-file.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge-index.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge-ours.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge-recursive.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge-tree.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge.exe
\Program Files\Git\mingw64\libexec\git-core\git-mktag.exe
\Program Files\Git\mingw64\libexec\git-core\git-mktree.exe
\Program Files\Git\mingw64\libexec\git-core\git-multi-pack-index.exe
\Program Files\Git\mingw64\libexec\git-core\git-mv.exe
\Program Files\Git\mingw64\libexec\git-core\git-name-rev.exe
\Program Files\Git\mingw64\libexec\git-core\git-notes.exe
\Program Files\Git\mingw64\libexec\git-core\git-pack-objects.exe
\Program Files\Git\mingw64\libexec\git-core\git-pack-redundant.exe
\Program Files\Git\mingw64\libexec\git-core\git-pack-refs.exe
\Program Files\Git\mingw64\libexec\git-core\git-patch-id.exe
\Program Files\Git\mingw64\libexec\git-core\git-prune-packed.exe
\Program Files\Git\mingw64\libexec\git-core\git-prune.exe
\Program Files\Git\mingw64\libexec\git-core\git-pull.exe
\Program Files\Git\mingw64\libexec\git-core\git-push.exe
\Program Files\Git\mingw64\libexec\git-core\git-range-diff.exe
\Program Files\Git\mingw64\libexec\git-core\git-read-tree.exe
\Program Files\Git\mingw64\libexec\git-core\git-rebase.exe
\Program Files\Git\mingw64\bin\git-receive-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-receive-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-reflog.exe
\Program Files\Git\mingw64\libexec\git-core\git-remote-ext.exe
\Program Files\Git\mingw64\libexec\git-core\git-remote-fd.exe
\Program Files\Git\mingw64\libexec\git-core\git-remote.exe
\Program Files\Git\mingw64\libexec\git-core\git-repack.exe
\Program Files\Git\mingw64\libexec\git-core\git-replace.exe
\Program Files\Git\mingw64\libexec\git-core\git-rerere.exe
\Program Files\Git\mingw64\libexec\git-core\git-reset.exe
\Program Files\Git\mingw64\libexec\git-core\git-rev-list.exe
\Program Files\Git\mingw64\libexec\git-core\git-rev-parse.exe
\Program Files\Git\mingw64\libexec\git-core\git-revert.exe
\Program Files\Git\mingw64\libexec\git-core\git-rm.exe
\Program Files\Git\mingw64\libexec\git-core\git-send-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-shortlog.exe
\Program Files\Git\mingw64\libexec\git-core\git-show-branch.exe
\Program Files\Git\mingw64\libexec\git-core\git-show-index.exe
\Program Files\Git\mingw64\libexec\git-core\git-show-ref.exe
\Program Files\Git\mingw64\libexec\git-core\git-sparse-checkout.exe
\Program Files\Git\mingw64\libexec\git-core\git-stash.exe
\Program Files\Git\mingw64\libexec\git-core\git-stripspace.exe
\Program Files\Git\mingw64\libexec\git-core\git-submodule--helper.exe
\Program Files\Git\mingw64\libexec\git-core\git-symbolic-ref.exe
\Program Files\Git\mingw64\libexec\git-core\git-tag.exe
\Program Files\Git\mingw64\libexec\git-core\git-unpack-file.exe
\Program Files\Git\mingw64\libexec\git-core\git-unpack-objects.exe
\Program Files\Git\mingw64\libexec\git-core\git-update-index.exe
\Program Files\Git\mingw64\libexec\git-core\git-update-ref.exe
\Program Files\Git\mingw64\libexec\git-core\git-update-server-info.exe
\Program Files\Git\mingw64\bin\git-upload-archive.exe
\Program Files\Git\mingw64\libexec\git-core\git-upload-archive.exe
\Program Files\Git\mingw64\bin\git-upload-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-upload-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-var.exe
\Program Files\Git\mingw64\libexec\git-core\git-verify-commit.exe
\Program Files\Git\mingw64\libexec\git-core\git-verify-pack.exe
\Program Files\Git\mingw64\libexec\git-core\git-verify-tag.exe
\Program Files\Git\mingw64\libexec\git-core\git-worktree.exe
\Program Files\Git\mingw64\libexec\git-core\git-write-tree.exe
\Program Files\Git\mingw64\libexec\git-core\git-cherry.exe
\Program Files\Git\mingw64\libexec\git-core\git-cherry-pick.exe
\Program Files\Git\mingw64\libexec\git-core\git-format-patch.exe
\Program Files\Git\mingw64\libexec\git-core\git-fsck-objects.exe
\Program Files\Git\mingw64\libexec\git-core\git-init.exe
\Program Files\Git\mingw64\libexec\git-core\git-maintenance.exe
\Program Files\Git\mingw64\libexec\git-core\git-merge-subtree.exe
\Program Files\Git\mingw64\libexec\git-core\git-restore.exe
\Program Files\Git\mingw64\libexec\git-core\git-show.exe
\Program Files\Git\mingw64\libexec\git-core\git-stage.exe
\Program Files\Git\mingw64\libexec\git-core\git-status.exe
\Program Files\Git\mingw64\libexec\git-core\git-switch.exe
\Program Files\Git\mingw64\libexec\git-core\git-whatchanged.exe

C:\Program Files\Git\mingw64\bin>
```
P.S. this is a corporate computer where my user is not a local administrator. However I can right-click on any executable file and run it as administrator and this is how I installed Git on this computer. If I try to install it without running the installer as administrator it installs Git somewhere in my home directory, probably because my user is not a local administrator. Don't know if this information related to this issue. This bug is not always reproducible.

Could that suspend status of the `git.exe` process be related to Windows hibernation?

**Comment by dscho** [comment]
> Could that suspend status of the `git.exe` process be related to Windows hibernation?

Potentially. Would you be able to grab the full command-line of that process e.g. via `wmic process where ProcessID=<pid> get CommandLine`?

**Comment by rosti-il** [comment]
According to the previously attached screenshot of the Windows Task Manager the command-line of that `git.exe` process is empty.

**Comment by dscho** [comment]
> According to the previously attached screenshot of the Windows Task Manager the command-line of that `git.exe` process is empty.

I had hoped that the `wmic` invocation would reveal more about it.

But yes, a running process that squats on that `.exe` will prevent its deletion (and since the others are hardlinked versions, I could imagine that the uninstaller failed to delete them because of that, too).

**Comment by rosti-il** [comment]
I still don't know how to reproduce it but it happened now again, at least I've noticed there is one suspended `git.exe` process in the Task Manager, although I closed everything related to Git - Intellij and Git Bash. Seems like there is some command line arguments and at leas one of them looks wrong - `--null`. The `git.exe` process seems to be stuck with one single thread.
```cmd
C:\>wmic process where ProcessID=14228 get commandline
CommandLine
git.exe -c core.quotepath=false -c log.showSignature=false config --null --get user.name
```
![image](https://user-images.githubusercontent.com/45571812/186685884-68a2fd41-cad5-4029-945d-edc150035dce.png)
All the above taken before trying to uninstall Git. Now I'm going to uninstall to see what will happen... and it happened again - the `mingw64` directory with many `*.exe` files were not uninstalled/removed. At least there is a warning about that:
![image](https://user-images.githubusercontent.com/45571812/186688277-c2e1bb63-6816-4ffe-a6eb-196f57f3c763.png)

**Comment by dscho** [comment]
> Maybe during my laptop was entering into the hibernation?

That's possible, and maybe somehow the pipe got stuck where it reads the result, or maybe IntelliJ misinterpreted the signal it received while reading the result. But it is _really_ strange, as that command's output should be really, really short and it should be near impossible to interfere with its operation due to hibernation.

**Comment by rosti-il** [comment]
My work laptop (where this issue was originally happened) was upgraded from Windows 10 to Windows 11. Sophos antivirus and other corporate stuff remained the same. After that OS upgrade this issue has never happened after already two upgrades of Git. So it seems to be Windows 10 specific.

**Comment by dscho** [comment]
@rosti-il would you be okay with closing this ticket, then? I do not see any reasonable way to diagnose this further, and it does not seem super critical to me to work on this.
