### ISSUE TITLE
Git failed to build with "error LNK2019: unresolved external symbol crc32 referenced in function #crc32$exit_thunk (EC Symbol)" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [git-for-windows/git#3925]
Git failed to build with "error LNK2019: unresolved external symbol crc32 referenced in function #crc32$exit_thunk (EC Symbol)" with MSVC on Windows arm64ec. It can reproduce on latest version on main branch. Could you please help look at this issue?

**Repro steps:**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/git-for-windows/git F:\gitP\git-for-windows\git
3. Change "set arch=x64-windows" to "set arch=arm64-windows"in vcpkg_install.bat
4. set PATH=F:\PortableGit\bin;%PATH%
5. cd F:\gitP\git-for-windows\git\compat\vcbuild
6. vcpkg_install.bat 
7. cd F:\gitP\git-for-windows\git\contrib\buildsystems\out
8. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DZLIB_LIBRARY=F:\gitP\git-for-windows\git\compat\vcbuild\vcpkg\installed\arm64-windows\lib\zlib.lib .. 
9. msbuild /p:Platform=ARM64EC /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.22618.0 git.sln /t:Rebuild

**Error log:**
[Git_build_fail.log](https://github.com/git-for-windows/git/files/9009996/Git_build_fail.log)

**Error info:**
```
index-pack.obj : error LNK2019: unresolved external symbol crc32 referenced in function #crc32$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(csum-file.obj) : error LNK2001: unresolved external symbol crc32 (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(pack-check.obj) : error LNK2001: unresolved external symbol crc32 (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(archive-zip.obj) : error LNK2001: unresolved external symbol crc32 (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflate referenced in function #deflate$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateEnd referenced in function #deflateEnd$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflate referenced in function #inflate$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function #inflateEnd$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateBound referenced in function #deflateBound$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateInit_ referenced in function #deflateInit_$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflateInit_ referenced in function #inflateInit_$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol deflateInit2_ referenced in function #deflateInit2_$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(zlib.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function #inflateInit2_$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(archive-tar.obj) : error LNK2019: unresolved external symbol gzdopen referenced in function #gzdopen$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(archive-tar.obj) : error LNK2019: unresolved external symbol gzwrite referenced in function #gzwrite$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
libgit.lib(archive-tar.obj) : error LNK2019: unresolved external symbol gzclose referenced in function #gzclose$exit_thunk (EC Symbol) [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.exe : fatal error LNK1120: 13 unresolved externals [F:\gitP\git-for-windows\git\contrib\buildsystems\out\git.vcxproj]
```

**Comment by rimrul** [comment]
> I do not usually build for ARM64... @dennisameling would you happen to have seen this error message before?

I think Dennis usually builds for the regular ARM64 ABI, not ARM64EC.

There was a brief discussion in one of the ARM64 threads about ARM64EC, but IIRC we decided against going down that route.

**Comment by dennisameling** [comment]
Yeah I only build against `ARM64`. Building for `ARM64EC` is only beneficial if you need to load `x64` stuff in-process, which AFAIK Git for Windows doesn't do, as it launches those executables in separate processes.

**Comment by YangYang129** [comment]
@dscho Thank you for your info. If I delete this -DZLIB_LIBRARY option, display error "Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")".

**Comment by dscho** [comment]
Oh wow, I completely missed the `EC` part and was totally unaware of any distinction between ARM64 and `ARM64EC`.

@YangYang129 based on @rimrul's and @dennisameling's explanation, would you agree that ARM64 EC is _not_ what you need, but ARM64 _is_?

**Comment by YangYang129** [comment]
@dscho I build pass on ARM64EC when not change "set arch=x64-windows" to "set arch=arm64-windows"in vcpkg_install.bat.
