### ISSUE TITLE
Installer to default to default branch "main" with optional "master"

### ISSUE THREAD

**Issue by theking2** [git-for-windows/git#3926]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using?
64-bit 2.37.9

 - Which version of Windows are you running?
Windows 11, 64 bit

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.25145.1011]

```

The installer still offers the option to select the name of the intial branch "main" : It is about time that this is reversed. Branchname "main" is the initial default branch name allowing users to select something else as alternative

**Comment by rimrul** [comment]
I don't think we want to deviate from upstream git in our default here.
There has been discussions on the mailing list in the past about changing the default name, but I'm not sure what the latest on that is.

**Comment by rimrul** [comment]
> git grep -w --count master v2.37.0 -- 'Documentation/*.txt' ':(exclude)Documentation/RelNotes/*'
v2.37.0:Documentation/MyFirstContribution.txt:15

I think this one mostly refers to the master branch in git.git, so it probably should not be changed, unless Junio renames that branch.

**Comment by dscho** [comment]
> > git grep -w --count master v2.37.0 -- 'Documentation/_.txt' ':(exclude)Documentation/RelNotes/_'
> > v2.37.0:Documentation/MyFirstContribution.txt:15
> 
> I think this one mostly refers to the master branch in git.git, so it probably should not be changed, unless Junio renames that branch.

Right, this is the tricky bit: some of these instances refer to actual branches whose name really is `master`.

In the case of git.git, Junio (the Git maintainer) actually publishes both `main` and `master`, and they are kept in sync. So technically we _could_ replace `master` by `main` in that document.

But even in cases where the documentation refers to a concrete branch, I would maintain that it might be more future-proof to refer to it as "the primary branch" or "the main branch". Having said that, arguing for this probably not the hill on which anybody wants to die. There are better, more straight-forward ways to push forward with the project to eventually flip the default branch name to `main`.

For example, in other grep hits, it is more clear cut that mentioning `master` is the correct thing to do, e.g. [here](https://github.com/git/git/blob/v2.37.0/Documentation/config/fmt-merge-msg.txt#L22): it specifically refers to a fall-back if that setting is not configured. But once you dig deeper, even here things are not quite as clear cut, [because the code actually disagrees with the documentation: it uses both `main` and `master` as fall-back, not just `master`](https://github.com/git/git/blob/v2.37.0/fmt-merge-msg.c#L646-L649).

So yeah, it's probably a good idea to leave `MyFirstContribution.txt` and similar not-so-obvious instances of the term `master` in the Documentation as-are and focus on things that _do_ need to be changed, e.g. [here](https://github.com/git/git/blob/v2.37.0/Documentation/config/push.txt#L47-L52).

**Comment by theking2** [comment]
> > I don't think we want to deviate from upstream git in our default here.
> 
> Indeed, I would _love_ for this to happen in upstream Git, and for Git for Windows to simply benefit from said change.
> 
> 
> 
> > There has been discussions on the mailing list in the past about changing the default name, but I'm not sure what the latest on that is.
> 
> The last word is, I think, that I got the test suite to pass no matter what the default branch name is.
> 
> The biggest haul will be to adjust the documentation so that it does not refer to the branch name `master` all the time:
> 
> ```console
> $ git grep -w --count master v2.37.0 -- 'Documentation/*.txt' ':(exclude)Documentation/RelNotes/*'
> v2.37.0:Documentation/MyFirstContribution.txt:15
> v2.37.0:Documentation/MyFirstObjectWalk.txt:2
> v2.37.0:Documentation/config/fmt-merge-msg.txt:1
> v2.37.0:Documentation/config/push.txt:2
> v2.37.0:Documentation/config/receive.txt:2
> v2.37.0:Documentation/config/transfer.txt:4
> v2.37.0:Documentation/git-archimport.txt:1
> v2.37.0:Documentation/git-bisect-lk2009.txt:2
> v2.37.0:Documentation/git-branch.txt:1
> v2.37.0:Documentation/git-bundle.txt:22
> v2.37.0:Documentation/git-checkout.txt:19
> v2.37.0:Documentation/git-cherry-pick.txt:17
> v2.37.0:Documentation/git-cherry.txt:11
> v2.37.0:Documentation/git-clone.txt:2
> v2.37.0:Documentation/git-config.txt:2
> v2.37.0:Documentation/git-cvsimport.txt:3
> v2.37.0:Documentation/git-cvsserver.txt:3
> v2.37.0:Documentation/git-diff.txt:7
> v2.37.0:Documentation/git-fast-export.txt:12
> v2.37.0:Documentation/git-fast-import.txt:4
> v2.37.0:Documentation/git-fetch-pack.txt:1
> v2.37.0:Documentation/git-fetch.txt:6
> v2.37.0:Documentation/git-filter-branch.txt:1
> v2.37.0:Documentation/git-fmt-merge-msg.txt:2
> v2.37.0:Documentation/git-format-patch.txt:1
> v2.37.0:Documentation/git-imap-send.txt:1
> v2.37.0:Documentation/git-init.txt:1
> v2.37.0:Documentation/git-log.txt:3
> v2.37.0:Documentation/git-ls-remote.txt:2
> v2.37.0:Documentation/git-merge-base.txt:16
> v2.37.0:Documentation/git-merge.txt:5
> v2.37.0:Documentation/git-name-rev.txt:2
> v2.37.0:Documentation/git-p4.txt:15
> v2.37.0:Documentation/git-pull.txt:8
> v2.37.0:Documentation/git-push.txt:26
> v2.37.0:Documentation/git-rebase.txt:26
> v2.37.0:Documentation/git-receive-pack.txt:6
> v2.37.0:Documentation/git-reflog.txt:2
> v2.37.0:Documentation/git-remote-fd.txt:6
> v2.37.0:Documentation/git-remote.txt:16
> v2.37.0:Documentation/git-request-pull.txt:6
> v2.37.0:Documentation/git-rerere.txt:26
> v2.37.0:Documentation/git-reset.txt:3
> v2.37.0:Documentation/git-restore.txt:3
> v2.37.0:Documentation/git-rev-parse.txt:6
> v2.37.0:Documentation/git-revert.txt:2
> v2.37.0:Documentation/git-send-email.txt:1
> v2.37.0:Documentation/git-show-branch.txt:11
> v2.37.0:Documentation/git-show-ref.txt:9
> v2.37.0:Documentation/git-show.txt:2
> v2.37.0:Documentation/git-stash.txt:2
> v2.37.0:Documentation/git-svn.txt:9
> v2.37.0:Documentation/git-switch.txt:3
> v2.37.0:Documentation/git-symbolic-ref.txt:3
> v2.37.0:Documentation/git-tag.txt:3
> v2.37.0:Documentation/git-update-ref.txt:2
> v2.37.0:Documentation/git-upload-archive.txt:1
> v2.37.0:Documentation/git-worktree.txt:7
> v2.37.0:Documentation/gitcore-tutorial.txt:69
> v2.37.0:Documentation/gitcvs-migration.txt:5
> v2.37.0:Documentation/giteveryday.txt:30
> v2.37.0:Documentation/githooks.txt:2
> v2.37.0:Documentation/gitremote-helpers.txt:2
> v2.37.0:Documentation/gitrepository-layout.txt:1
> v2.37.0:Documentation/gittutorial-2.txt:5
> v2.37.0:Documentation/gittutorial.txt:26
> v2.37.0:Documentation/gitworkflows.txt:17
> v2.37.0:Documentation/glossary-content.txt:3
> v2.37.0:Documentation/howto/coordinate-embargoed-releases.txt:1
> v2.37.0:Documentation/howto/keep-canonical-history-correct.txt:8
> v2.37.0:Documentation/howto/maintain-git.txt:46
> v2.37.0:Documentation/howto/rebase-from-internal-branch.txt:25
> v2.37.0:Documentation/howto/rebuild-from-update-hook.txt:3
> v2.37.0:Documentation/howto/revert-a-faulty-merge.txt:3
> v2.37.0:Documentation/howto/revert-branch-rebase.txt:33
> v2.37.0:Documentation/howto/separating-topic-branches.txt:12
> v2.37.0:Documentation/howto/setup-git-server-over-http.txt:3
> v2.37.0:Documentation/howto/update-hook-example.txt:3
> v2.37.0:Documentation/howto/using-merge-subtree.txt:5
> v2.37.0:Documentation/pretty-formats.txt:3
> v2.37.0:Documentation/revisions.txt:17
> v2.37.0:Documentation/technical/http-protocol.txt:3
> v2.37.0:Documentation/technical/pack-protocol.txt:4
> v2.37.0:Documentation/technical/protocol-capabilities.txt:2
> v2.37.0:Documentation/technical/reftable.txt:2
> v2.37.0:Documentation/technical/repository-version.txt:1
> v2.37.0:Documentation/urls-remotes.txt:1
> v2.37.0:Documentation/user-manual.txt:83
> ```
> 
> That's almost 800 instances:
> 
> ```console
> $ echo $(($(git grep -w --count master v2.37.0 -- 'Documentation/*.txt' ':(exclude)Documentation/RelNotes/*' | sed 's/.*://' | tr '\n' +)0))
> 795
> ```
> 
> The good news is that anybody can start at any file to decouple the documentation from the exact default branch name.
> 
> @theking2 would you be interested in helping this ginormous effort? (I am hoping for a "yes!"... 😊)

Yes I would! I don't see a problem. I will however look upstream to find why this is still a thing.

**Comment by dscho** [comment]
> I will however look upstream to find why this is still a thing.

I _think_ I can fill in the details here: I basically ran out of steam (and felt that there was undue push-back on the Git mailing list, not from the majority, but only from a few, very loud voices, which _can_ be wearisome).

> > @theking2 would you be interested in helping this ginormous effort? (I am hoping for a "yes!"... 😊)
> 
> Yes I would!

Okay, then! Do you have everything you need to get started? Feel free to Cc: me on the patches.

**Comment by devwith-kev** [comment]
> > I will however look upstream to find why this is still a thing.
> 
> I _think_ I can fill in the details here: I basically ran out of steam (and felt that there was undue push-back on the Git mailing list, not from the majority, but only from a few, very loud voices, which _can_ be wearisome).
> 
> > > @theking2 would you be interested in helping this ginormous effort? (I am hoping for a "yes!"... 😊)
> > 
> > 
> > Yes I would!
> 
> Okay, then! Do you have everything you need to get started? Feel free to Cc: me on the patches.

Reopening the conversation :)

I found this open issue as I've faced that problem while trying to automate some task through scripting. Most of the SCM are now defaulting to main branch which caused a side effect in my workflow while initializing a Git repo on my local environment (default master branch).

Is there anything I can help on here on the documentation to decouple the wording master from the default branch?

**Comment by dscho** [comment]
Seeing as this ticket got no traction, I sadly conclude that there is somewhat of a consensus that agrees with aforementioned voices on the Git mailing list, and with a heavy heart, I will close this ticket.
