### ISSUE TITLE
scp defaults to sftp starting with 2.36.1, breaking things

### ISSUE THREAD

**Issue by zrav** [git-for-windows/git#3938]
Starting with 2.36.1 the included scp defaults to sftp transfers with no way of forcing scp, breaking things for systems that do not support sftp. Gerrit in our case.

### Setup

Git-2.36.1-64-bit

```
$ git --version --build-options
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Windows 10 64 bit.

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19042.1706]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? 

```
scp -v -p user@my.domain.com:file .
```
 - What did you expect to occur after running these commands?

```
With 2.36.0 and earlier:
...
Authenticated to my.domain.com ([1.2.3.4]:22) using "publickey".
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: Sending command: scp -v -p -f file
Sink: C0755 2272 file
file                                                                                              0%    0     0.0KB/s   --:-- ETAs
cp: debug1: fd 8 clearing O_NONBLOCK
file                                                                                            100% 2272    21.5KB/s   00:00
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3692, received 5248 bytes, in 0.7 seconds
Bytes per second: sent 5486.4, received 7798.6
debug1: Exit status 0
```

 - What actually happened instead?

```
With 2.36.1 and later:
...
Authenticated to my.domain.com ([1.2.3.4]:22) using "publickey".
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: Sending subsystem: sftp
subsystem request failed on channel 0
scp: Connection closed
```

**Comment by zrav** [comment]
Just found in https://www.openssh.com/txt/release-9.0 that there is a flag to force scp transfers: -O
Leaving this issue in case someone stumbles upon the same issue.

In the case of the Gerrit commit message hook installation command, it should be overridable with the gerrit.installCommitMsgHookCommand option.

**Comment by dscho** [comment]
Thank you, @zrav, for not only reporting the issue, but also to investigate and figure out a work-around.

Having said that...

> Just found in https://www.openssh.com/txt/release-9.0 that there is a flag to force scp transfers: -O
> Leaving this issue in case someone stumbles upon the same issue.

... the switch to the `sftp` protocol seems to be intentional. From the same release notes:

> ## Potentially-incompatible changes
>
> This release switches scp(1) from using the legacy scp/rcp protocol
> to using the SFTP protocol by default.

So I think Git for Windows does the right thing here in leaving it to OpenSSH to determine its best defaults.
