### ISSUE TITLE
git clone is failing when run inside an application using core.askPass 

### ISSUE THREAD

**Issue by manig28** [git-for-windows/git#3939]
Hi,

I am seeing a strange behaviour. We are using core.askPass to pass the access token while cloning a repository using batch file.
When the batch file is run from CMD, it completes succesfully but when we are running it from inside of an application, it fails with the following error :

error: unable to read askpass response from 'C:\Program Files\TEST\1_test1_PAT.bat'
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://dev.azure.com': No such file or directory

GIT_TRACE and GCM_TRACE logs :

```
10:37:39.515874 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:37:39.527876 git.c:460               trace: built-in: git clone --bare https://dev.azure.com/MyTestOrg/test1/_git/test1 
10:37:39.665876 run-command.c:654       trace: run_command: git remote-https origin https://dev.azure.com/MyTestOrg/test1/_git/test1
10:37:39.718877 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:37:39.725877 git.c:749               trace: exec: git-remote-https origin https://dev.azure.com/MyTestOrg/test1/_git/test1
10:37:39.725877 run-command.c:654       trace: run_command: git-remote-https origin https://dev.azure.com/MyTestOrg/test1/_git/test1
10:37:39.809876 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:37:40.391317 run-command.c:654       trace: run_command: ''C:\Program Files\TEST\1_test1_PAT.bat' 'Username for '\''https://dev.azure.com/MyTestOrg/test1/_git/test1'\'': '
10:37:40.441322 run-command.c:654       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
```

git version :

```
$  git --version --build-options
git version 2.37.0.windows.1
cpu: x86_64
built from commit: 989c3a6832b035f6124b0a23da9c0f8f18afa550
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

**Comment by dscho** [comment]
> We are using core.askPass to pass the access token while cloning a repository using batch file.

I am not quite sure that I understand this completely.

Are you saying that you have a PAT and you pass it to Git by letting it call back via a custom [`core.askPass`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreaskPass) program? If so, I am afraid that it seems the wrong thing to do: this feature is meant for interactive use, not for use by an application.

The symptom you see is that Git expects a Win32 Console in the interactive case, and you probably do not provide one when calling Git.

If you want to provide credentials in a non-interactive manner, you will probably want to pass `-c credential.helper= -c credential.helper=<program>` (the first parameter is meant to reset the credential helpers list, to make sure that only the second one is called).

Alternatively, you may wish to pass the PAT via [`http.extraHeader`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpextraHeader), e.g. `-c http.extraHeader="Authorization: Bearer <PAT>"`.

**Comment by dscho** [comment]
> We cannot use -c http.extraHeader="Authorization: Bearer " because we don't want to pass the PAT in the command itself (for security reasons).

Makes sense. So the `credential.helper` solution works for you?

**Comment by manig28** [comment]
Yes, that worked. Appreciate your response!

**Comment by dscho** [comment]
Out of curiosity, can you share details?
