### ISSUE TITLE
EVP_aes_128_ctr entry point not found

### ISSUE THREAD

**Issue by Chocobo1** [git-for-windows/git#394]
I downloaded `PortableGit-2.5.2.2-64-bit.7z.exe` on `Windows 8.1 x64`, and extract it at `C:\Git`.
Then I issued `git fetch` on my qbittorrent git repo, the error occurs and git crashed.

Here is a screenshot:
![error](https://cloud.githubusercontent.com/assets/9395168/9897166/ea1de99e-5c77-11e5-9071-5041690e7c56.png)

Translation:
```
The procedure entry point EVP_aes_128_ctr could not be located in the dynamic link library C:\Git\mingw64\bin\libssh2-1.dll
```

**Comment by nalla** [comment]
See http://www.libssh.org/archive/libssh/2015-05/0000011.html

**Comment by dscho** [comment]
How can I reproduce this?? I.e. what is the URL I need to clone to experience the same error?

**Comment by Chocobo1** [comment]
>what is the URL I need to clone to experience the same error?

I am not sure if you could reproduce this, anyway here is the info:
```
git remote -v
origin  https://chocobo1@github.com/Chocobo1/qBittorrent.git
```

**Comment by dscho** [comment]
Unfortunately, I cannot reproduce:

```sh
$ git clone https://chocobo1@github.com/Chocobo1/qBittorrent.git
```

Just Works. Maybe you have a strange proxy sitting in front of the internets?

**Comment by Chocobo1** [comment]
I found out it's my fault. It works correctly when I double-click and install it (using the bundled sfx extractor).
My previous attempt was using `7-zip 15.05 beta x64` right-click menu -> extract to..., obviously that broke something... sorry for the noise.

**Comment by dscho** [comment]
@Chocobo1 ah! The `post-install.bat` script!

Thanks for the reminder; I *really* need to mention this in `README.portable`.

**Comment by Chocobo1** [comment]
BTW, a suggestion:
looking at https://github.com/git-for-windows/build-extra/blob/master/portable/release.sh#L30

it might be possible to change `-m0=lzma` to `-m0=LZMA2`
Here is from the 7z document:
```
LZMA2 is modified version of LZMA. it provides the following advantages over LZMA:
Better compression ratio for data than can't be compressed. LZMA2 can store such blocks of data in uncompressed form. Also it decompresses such data faster. 
Better multithreading support. If you compress big file, LZMA2 can split that file to chunks and compress these chunks in multiple threads. 
```

**Comment by dscho** [comment]
> it might be possible to change -m0=lzma to -m0=LZMA2

Could you compare the size before and after this change?

**Comment by dscho** [comment]
> I really need to mention this in README.portable.

See 676be9a398cacd152fca4152bb0cfee217bc73cd

**Comment by Chocobo1** [comment]
>Could you compare the size before and after this change?

LZMA2:
```
7z a -m0=lzma2 -mx=9 -md=64M new.7z Git
7-Zip [64] 15.06 beta : Copyright (c) 1999-2015 Igor Pavlov : 2015-08-09

Scanning the drive:
577 folders, 5169 files, 196706699 bytes (188 MiB)
Creating archive: new.7z
Items to compress: 5746

Files read from disk: 5169
Archive size: 28532184 bytes (28 MiB)
Everything is Ok
```

LZMA:
```
7z a -m0=lzma  -mx=9 -md=64M old.7z Git
7-Zip [64] 15.06 beta : Copyright (c) 1999-2015 Igor Pavlov : 2015-08-09

Scanning the drive:
577 folders, 5169 files, 196706699 bytes (188 MiB)
Creating archive: old.7z
Items to compress: 5746

Files read from disk: 5169
Archive size: 28523741 bytes (28 MiB)
Everything is Ok
```

Seems LZMA2 is a bit larger :\
