### ISSUE TITLE
in windows 11 git pull stuck

### ISSUE THREAD

**Issue by ylq5126** [git-for-windows/git#3951]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.1.windows.1
cpu: x86_64
built from commit: 323a69709944b193bb5cee81ff09fe9a4a686df5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.22000.795
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD/PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull  
git fetch 


```
 - What did you expect to occur after running these commands?

Normal output results

 - What actually happened instead?

![image](https://user-images.githubusercontent.com/9344601/179488006-243b5d67-8206-4c7f-a9bb-f79dab9302e3.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Is there any Git process burning some CPU? If so, what is the command-line? (Use e.g. [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and/or [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to find out).

**Comment by ylq5126** [comment]
> Is there any Git process burning some CPU? If so, what is the command-line? (Use e.g. [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and/or [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to find out).
[Process_Logfile.zip](https://github.com/git-for-windows/git/files/9194567/Process_Logfile.zip)
[Process Explorer.txt](https://github.com/git-for-windows/git/files/9194589/Process.Explorer.txt)

**Comment by ylq5126** [comment]
it seems case by this command 
` git maintenance run --auto --no-quiet`

**Comment by dscho** [comment]
> ` git maintenance run --auto --no-quiet`

If this command takes a long time it typically means that the repository is in a bad shape and letting the command finish will remedy that.

**Comment by ylq5126** [comment]
> If this command takes a long time it typically means that the repository is in a bad shape and letting the command finish will remedy that.

when use  git bash , can work well， in windows command is blocked

**Comment by ylq5126** [comment]
> > ` git maintenance run --auto --no-quiet`
> 
> If this command takes a long time it typically means that the repository is in a bad shape and letting the command finish will remedy tha

**Comment by ylq5126** [comment]
![image](https://user-images.githubusercontent.com/9344601/181241256-15085009-47d3-48a2-a287-8af32787606c.png)
the exec command of process tree
`git  pull`
  `git.exe  pull`
    `ssh -o SendEnv=GIT_PROTOCOL -p 2288 git@gitlab.com "git-upload-pack '/walt/demo_test.git'"`
    `git rev-list --objects --stdin --not --all --quiet --alternate-refs`

**Comment by lishunan246** [comment]
Same Issue

git version 2.39.1.windows.1
Microsoft Windows 10.0.22621.1194
Lenovo Yoga Pro 14s

**Comment by dscho** [comment]
> SSH Option: ExternalOpenSSH

Together with ` ssh -o SendEnv=GIT_PROTOCOL -p 2288 git@gitlab.com "git-upload-pack '/walt/demo_test.git'"`, this sounds very much like a problem with https://github.com/PowerShell/Win32-OpenSSH/.

How certain are you that the `ssh.exe` in the Windows Command Prompt is the exact same executable as the one that is used in the Git Bash?

**Comment by dscho** [comment]
> How certain are you that the `ssh.exe` in the Windows Command Prompt is the exact same executable as the one that is used in the Git Bash?

I am almost certain that I'll never learn the answer to this question.
