### ISSUE TITLE
Git can't fork child process: resource temporarily unavailable

### ISSUE THREAD

**Issue by wboswall** [git-for-windows/git#3952]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

``` 
 64 Bit Git-2.37.1-64-bit
$ git --version --build-options

```

Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

``` 
Version 21H2 (OS Build 19044.1826) Windows 10 Home
$ cmd.exe /c ver
```

Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.

 - What options did you set as part of the installation? Or did you choose the
   defaults?
   I choose the defaults. 

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

``` 

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
 the last files were unavailable on computer.  

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing I even uninstalled cygwin since it was blocking git and also changed the security settings.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I did try bash and then tried cmd and then powershell but still the same error: 
Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I was unable to run anything so I switched to the command prompt and ran the rebaseall /rebase -help and it said - C:\>git rebeseall
git: 'rebeseall' is not a git command. See 'git --help'.

C:\>git rebaseall /rebase --help
git: 'rebaseall' is not a git command. See 'git --help'. 
```

 - What did you expect to occur after running these commands?

That it would rebase git and get it working again

 - What actually happened instead?

C:\>git rebeseall
git: 'rebeseall' is not a git command. See 'git --help'.

C:\>git rebaseall /rebase --help
git: 'rebaseall' is not a git command. See 'git --help'.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

nope it effecting all repositories and git software. Please see attachment of git bash problem.
![2022-07-18](https://user-images.githubusercontent.com/34065293/179628081-eb365829-c4ee-420b-ad30-cf3aede2ad6e.png)

**Comment by PhilipOakley** [comment]
The "DLL rebasing may be required; see 'rebaseall / rebase --help'" message is not part of Git, rather it's the DLL in Windows that needs it's base address moved ("rebased") as part of it's installation. 

It is easy to confuse the two types of 'rebase'.

**Comment by rimrul** [comment]
> I even uninstalled cygwin since it was blocking git

Could you re-run the Git for Windows installer? That should probably fix this issue.

**Comment by wboswall** [comment]
@PhilipOakley @rimrul Thanks guys for replying.  The windows version is working but can't update properly.  When attempt to update it says that it's unable to update because the cygwin is ...I forget the rest.  I think it can't find it.  Do I have to go into the windows path and add the link to it? Or something similar?  Also is there an easy fix to get the bash version working again?  Again Much appreciated.

**Comment by dscho** [comment]
> The windows version is working but can't update properly.

What does that mean?



> When attempt to update it says that it's unable to update because the cygwin is ...I forget the rest.

It would be more helpful to re-run the failing command and copy the error message precisely.

> Also is there an easy fix to get the bash version working again?

@rimrul already pointed out that you could re-run the Git for Windows installer.

> [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

When I search for the _exact_ error message, I find [19 closed tickets](https://github.com/git-for-windows/git/issues?q=%22could+not+fork+child+process%22+is%3Aclosed+).

This issue typically occurs in 32-bit setups, but we have had a couple of 64-bit setups with the same issue, too. For more details about the problem, see [this wiki page](https://github.com/git-for-windows/git/wiki/32-bit-issues).

**Comment by wboswall** [comment]
@dscho Thanks for replying,  A few years ago and up to now windows git ran fine but now it doesn't want to run properly.  However I switched over to the portable version and it works fine.  So there is a problem with both the installer version and the github version installer.  But the portable version of git runs fine without a hitch ... for now.

**Comment by wboswall** [comment]
@dscho The exact error is: Error: Could not fork child process: Resource temporarily unavailable (-1). DLL rebasing may be required; see 'rebaseall / rebase --help
Also I did run the installer again but again failed with the above error.  However I tried to run the rebase command but the bash terminal didn't respond and eventually closed by itself.  Very strange.

**Comment by wboswall** [comment]
@dscho @PhilipOakley @rimrul @bbolli Thank you for all of your advice but I chose a different way of install git on windows and was by installing  winget through powershell with admin rights and after installing recloned my repos and updated them all and voila git is now working.

**Comment by dscho** [comment]
> git is now working.

Great! And now this ticket together with your resolution can be found by others experiencing similar issues, which is also good.

**Comment by wboswall** [comment]
@dscho I got another computer and installed git for windows and it worked seamlessly without an issue.  Pretty strange.

**Comment by soyfrien** [comment]
The most convincing explanation I heard was ASLR. I can't find the convincing posts, but someone is making a list as a random example: https://github.com/SadPencil/ASLR-incompatible-windows-apps

Not sure where ASLR lives, but maybe it's only psuedo-random and still not so autonomous.
