### ISSUE TITLE
Git hangs on clone for jenkins-ssh and ansible at git-upload-pack

### ISSUE THREAD

**Issue by DaveWK** [git-for-windows/git#3961]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

 git --version --build-options
git version 2.37.1.windows.1
cpu: x86_64
built from commit: 323a69709944b193bb5cee81ff09fe9a4a686df5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon


```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 2022 Datacenter Base (AWS AMI), x64-bit

```
$ cmd.exe /c ver

cmd /c ver
Microsoft Windows [Version 10.0.20348.825]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults with fsmonitor-daemon, hav
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt


type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am using the Windows Native OpenSSH ssh.exe, Windows OpenSSH key Agent and Windows OpenSSH Server.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell, have also tried cmd.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I am using a Windows 2022 AMI from AWS. I install git for windows, enable the windows openssh agent from services.msc, and add and configure the windows OpenSSH server add-on from the control panel. 

If I clone from powershell while logged in via remote desktop or an interactive ssh window, the clone works fine.

When I use ansible or jenkins (which I assume has some kind of non-interactive terminal set), it will start the clone by creating the directory, then add the `.git` subdirectory with some of the generic HEAD/Index files in it, but then hangs. When I enable traces/logs, the last message in the logs refers to it running an initial `git-upload-pack`.  but it sits there and hangs indefinitely. I see there are two `git.exe` processes running, but neither is using more than about 1000k of memory, and no change in CPU utilization. 

**Note: I have already included the proper entries in the known_hosts file for git@github.com, and running ssh git@github.com runs cleanly without any prompts, so this is not simply an issue where git is prompting for credentials**

**Comment by dscho** [comment]
@DaveWK could you try running `git.exe` through `winpty`?

**Comment by DaveWK** [comment]
> @DaveWK could you try running `git.exe` through `winpty`?

Same result -- hangs on git-upload-pack

**Comment by dscho** [comment]
My hunch is that there is some sort of interactive login prompt that is blocking the clone.

**Comment by DaveWK** [comment]
the issue is that when I log in via ssh over a command line and run "git clone" and "git pull" by hand, it works fine with the same user account. I have already added github the known_hosts, and can do the ssh test with github no problem

 I am suspicious that either this is due to either the fact that this is a non-interactive terminal, or somehow git for windows is not interacting properly with the windows socket. When I do not have permissions on a repo (or the repo doesn't exist), or there's a pop-up, then git will exit gracefully before it even attempts to make any files on the filesystem.

**Comment by dscho** [comment]
> or somehow git for windows is not interacting properly with the windows socket

Can you verify that Git's copy of `ssh.exe` is _not_ used? According to the line `SSH Option: ExternalOpenSSH` in your report, `C:\Program Files\Git\usr\bin\ssh.exe` should not exist, but if it does, that might be an explanation for what you see.

**Comment by Nice7118** [comment]
My name name is Nick Urrabazo . NU federal agency that this repository is fetching and collecting information  for a group of people. Joseph Samudio,Joey Urrabazo, Bobby Urrabazo and a few others. These people do not own the information they are having you collect. They are stealing from a federal agency. Have no credentials to do so. They are collecting my passwords and taking over my email and access to my business. I own ABC! I own NC,Rnuc And Keep Us Together America, and a few other executive agencies and associated companies. Please contact me at 2105024220. Thank you.

**Comment by DaveWK** [comment]
yes sorry I moved to an all-linux setup so dont have a way to reproduce anymore

**Comment by dscho** [comment]
> yes sorry I moved to an all-linux setup so dont have a way to reproduce anymore

I am glad you found a solution to your problem.
