### ISSUE TITLE
post-commit hook: git command fails

### ISSUE THREAD

**Issue by kulowf** [git-for-windows/git#3963]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64

```
[System Info]
git version:
git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
uname: Windows 10.0 19044 
compiler info: gnuc: 11.3
libc info: no libc information available
$SHELL (typically, interactive shell): C:\Program Files\Git\usr\bin\bash.exe


[Enabled Hooks]
post-commit

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled# One of the following:

```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

  - my task: after commit set a other working copy (in directory bitten) also to this HEAD

```
git worktree add ../bitten
```
  - create a .git/post-commit:

```
#!/bin/sh
id=$(git log -1 --format=%h)
cd ../bitten
git reset --hard $id
```

  - commit my changes
```
git commit -amtest
``` 

 - What did you expect to occur after running these commands?

     - other working copy (in directory bitten) is also on HEAD

 - What actually happened instead?

```
fatal: Unable to create 'C:/home/bitten/.git/index.lock': No such file or directory
```
  - is this a bad message for `repository inclusive worktrees is locked` or a bug?

---------------

- if i start a `git bash` in bitten `git reset` is possible.
- The behaviour of `git reset` is different if is called in `post-commit`.

- `post-commit` hook is working if
  -  i use a cloned git repository in bitten
  -  add `git fetch --all` in `post-commit` hook

**Comment by dscho** [comment]
> * create a .git/post-commit:
> 
> 
> ```
> #!/bin/sh
> id=$(git log -1 --format=%h)
> cd ../bitten
> git reset --hard $id
> ```

If you insert the command `env | grep GIT` into that script, you will notice this line in the output:

```
GIT_INDEX_FILE=.git/index
```

This is [intentional](https://github.com/git/git/blob/v2.37.1/commit.c#L1743) (really, [_very_ intentional](https://github.com/git/git/commit/130fcca63fe8e7e087e7419907e018cbbaf434a3#diff-9243f158d7ae85d8804e96080c2dc901f35cd0d9a866794cf42ef90b3c6026eaR255-R260)) and the reason why the hook fails for you.

You will want to insert this line somewhere in your `pre-commit` hook, _before_ the `git reset` invocation:

```sh
unset GIT_INDEX_FILE
```

**Comment by kulowf** [comment]
Hallo Johannes,

`.git/index.lock` is in this case not possible, because it is on a worktree.

`.git` is textfile with content:
         `gitdir: C:/home/wc/.git/worktrees/bitten`

Frank

**Comment by dscho** [comment]
> `.git/index.lock` is in this case not possible, because it is on a worktree.

Indeed. And the root of the problem is, as I said, that the `GIT_INDEX_FILE` environment variable is in the way. You need to `unset` it. Have you actually tried what I suggested?

**Comment by kulowf** [comment]
before and after  `cd ../bitten` is
`GIT_INDEX_FILE=.git/index`

`unset GIT_INDEX_FILE` solve the problem.

Thanks, Frank
