### ISSUE TITLE
--global --add safe.directory does not work

### ISSUE THREAD

**Issue by michelwigbers** [git-for-windows/git#3976]
I get an error while I think the syntax is correct

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 -  2.37.1 64 bit

$ git --version --build-options

```
D:\IBM\WebSphere\wp_profile\config>git --version --build-options
error: unknown switch `?'
usage: git version [<options>]

    --build-options       also print build options
```

This command gives as well as an error. 

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows server 2012 R2

$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Editor Option: Wordpad
Custom Editor Path: 
Default Branch Option:  
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global --add safe.directory D:/IBM/WebSphere/wp_profile/config

below are the commands I used before  this result
SET PORTAL_CONFIG_BASE=D:\IBM\WebSphere\wp_profile\config
SET GIT_CONFIG_DIR=D:\IBM\git-backup\config
FOR /F "usebackq tokens=*" %d IN (`DIR D:\IBM\WebSphere\wp_profile\config\cells /B /A:D /O:N`) DO (SET  CELLNAME="%~nxd")
SET CELL=D:\IBM\WebSphere\wp_profile\config\cells\%CELLNAME%
mkdir %GIT_CONFIG_DIR%
d:
cd %PORTAL_CONFIG_BASE%
git init --separate-git-dir %GIT_CONFIG_DIR%
git config --global user.name "test test"
git config --global user.email test@test.com
```

 - What did you expect to occur after running these commands?

safe directory added to config 

 - What actually happened instead?

D:\IBM\WebSphere\wp_profile\config>git config --global --add safe.directory D:/I
BM/WebSphere/wp_profile/config
error: wrong number of arguments, should be 2
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
etc

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no repos

**Comment by rimrul** [comment]
> $ git --version --build-options
> 
> ```
> D:\IBM\WebSphere\wp_profile\config>git --version --build-options
> error: unknown switch `?'

This is weird. There is no `-?` in that `git` invokation. 

> D:\IBM\WebSphere\wp_profile\config>git config --global --add safe.directory D:/I
> BM/WebSphere/wp_profile/config
> error: wrong number of arguments, should be 2

Here git also seems to be complaining about an argument that isn't there.

It almost as if something is appending some weird arguments to the commands you call.

**Comment by rimrul** [comment]
Could you check the output of `where git` and 

```batch
set GIT_TRACE=1
git version --build-options
```

**Comment by dscho** [comment]
> It almost as if something is appending some weird arguments to the commands you call.

Could there be a `doskey` command involved? Is this [Git CMD's doing](https://github.com/git-for-windows/MINGW-packages/blob/main/mingw-w64-git/git-cmd.rc#L3)?

**Comment by rimrul** [comment]
> Could there be a `doskey` command involved?

Good call. Could you check the output of `doskey /macros`

**Comment by michelwigbers** [comment]
I am going to close this issue, as I am now thinking it is related to my environment. Don't know why yet, but I got correct results now. 

my cmd output:

D:\tools\Git\cmd>git --version --build-options
git version 2.37.1.windows.1
cpu: x86_64
built from commit: 323a69709944b193bb5cee81ff09fe9a4a686df5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

D:\tools\Git\cmd>git config --global --add safe.directory D:/IBM/WebSphere/wp_profile/config

D:\tools\Git\cmd>
