### ISSUE TITLE
Can't run script usin git-bash.exe

### ISSUE THREAD

**Issue by smougenot** [git-for-windows/git#398]
Migrating to Git 2.5.2 (from Git 2.4) on windows 7 pro 64 bits I can not run script from cmd using git-bash.exe anymore.

```cmd
E:
cd E:\dev\src
"C:\Program Files\Git\git-bash.exe" --login lst_git.sh
```

The result is a popup shell that desapears immediately (can't read if there is an error message)

I tried to find documentation about git-bash.exe options but could not find any 
```cmd
"C:\Program Files\Git\git-bash.exe" --help
```
or 
```cmd
"C:\Program Files\Git\git-bash.exe" -h
```
or 
```cmd
"C:\Program Files\Git\git-bash.exe" /?
```
have the same behaviour (useless to read what ever the vanishing popup shell might tells)

but 
```cmd
"C:\Program Files\Git\git-bash.exe"
```
works fine

Please help fixing this

**Comment by dscho** [comment]
> lst_git.sh

What is in this file? Can you insert an `echo 123 && read x` at the top?

**Comment by dscho** [comment]
Also, if you want to run this in a console window, could you try

```cmd
"C:\Program Files\Git\bin\bash.exe" --login lst_git.sh
```

instead?

**Comment by smougenot** [comment]
Content of the file lst_git.sh
```bash 
#!/bin/sh
# Lister les repo git
find . -maxdepth 3 -type d -name '.git' | sort > lst_git.txt
```

The script shell works fine if I launch the script inside the git-bash shell (launching the shell manually from start menu)

Works with bash.exe ... but can't run git commands
```bash
git fetch
```
> Could not create directory '/home/smougenot/.ssh'.

**Looks like home path is not set properly for ssh**
```cmd
"C:\Program Files\Git\bin\bash.exe" --login -c "cd ~ && pwd"
```
>/c/Users/smougenot

but
```cmd
"C:\Program Files\Git\bin\bash.exe" --login -c "ssh git@gitlab.sglk.local"
```
>Could not create directory '/home/smougenot/.ssh'

**Comment by nalla** [comment]
Could you try `"C:\Program Files\Git\git-bash.exe" lst_git.sh` instead of `"C:\Program Files\Git\git-bash.exe" --login lst_git.sh`?

**Comment by dscho** [comment]
> Could not create directory '/home/smougenot/.ssh'.

That's concerning. Your `HOME` should be user regular Windows home directory.

If you run `Git Bash` from the Start Menu, what does `echo $PATH` say?

**Comment by smougenot** [comment]
I'll try it as soon as possible (in less than 2h)
I needed git on windows so I downgraded

**Comment by dscho** [comment]
Oops, I meant `echo $HOME`. Sorry.

**Comment by dscho** [comment]
And for good measure, `echo $HOMEDRIVE///$HOMEPATH///$USERPROFILE`?

**Comment by smougenot** [comment]
```bash
echo $HOMEDRIVE///$HOMEPATH///$USERPROFILE
```
> C:///\Users\smougenot///C:\Users\smougenot

**Comment by dscho** [comment]
That is strange. It *should* be picked up by `git-bash.exe`. How did you install Git for Windows? (Yep, I am stabbing in the dark here.) Does your `/etc/nsswitch.conf` read

```
# Begin /etc/nsswitch.conf

passwd: files db
group: files # db

db_enum: cache builtin

db_home: env windows cygwin desc
db_shell: env windows # cygwin desc
db_gecos: env # cygwin desc

# End /etc/nsswitch.conf
```

?

**Comment by smougenot** [comment]
Installation was done using Git-2.5.2.2-64-bit.exe
I removed former Git installation (using control pannel) before installation.
No special options chosen (I think). But the 'new' (at least for me) caching feature.

/etc/nsswitch.conf is exactly what is in your comment

```
# Begin /etc/nsswitch.conf

passwd: files db
group: files # db

db_enum: cache builtin

db_home: env windows cygwin desc
db_shell: env windows # cygwin desc
db_gecos: env # windows cygwin desc

# End /etc/nsswitch.conf
```

**Comment by dscho** [comment]
Do you have any funny stuff in your `$HOME/bin` or in your `$HOME/.profile`?

(The first line of your `$PATH` suggests that we see the correct `$HOME` at some stage, but then your `$HOME` gets set incorrectly. Or does it? What is the output of `echo $HOME` again?)

**Comment by dscho** [comment]
> Do you have any funny stuff in your $HOME/bin or in your $HOME/.profile?

This is the only explanation I could imagine (there is nothing in Git for Windows 2.5.3's `/etc/` directory that would modify `HOME`. Do you have anything there?

**Comment by dscho** [comment]
Also, the originally reported issue might be due to picking the default Windows console over mintty. @smougenot did you?

**Comment by smougenot** [comment]
for the moment I'm due to work on git so I've not tried again.
Sorry

2015-09-24 11:52 GMT+02:00 Johannes Schindelin <notifications@github.com>:

**Comment by dscho** [comment]
I'll just assume that it was fixed by the same code change as https://github.com/git-for-windows/git/issues/396
