### ISSUE TITLE
(Some) interactive commands unusable with git-bash.exe

### ISSUE THREAD

**Issue by harriha** [git-for-windows/git#399]
Hi,

Did a bit of searching, but couldn't find an issue about this - which, to be honest, is surprising. If there's an issue about this already, please feel free to close this one.

- Have latest portable version available (2.5.2.2, 64bit) (reproducable also in 2.5.1, didn't test other 2.x releases)
- Have PostgreSQL installed and configured properly (= binaries in PATH) with a password
- Open git-bash.exe from Explorer
- Type `psql`

Expected:

- There's a prompt asking the user to type in the password

Actual: 

- Shell does nothing, seems to hang, need to exit with Ctrl-C

The same works fine if running the command from `bin/bash.exe`. Also, with the old 1.9.5 version of msysgit this works fine. I'm on Windows 8.1.

Encountered this with `psql`, but this might be a common thing with some other similar interactive programs?

```
$ git --version
git version 2.5.2.windows.2

$ psql --version
psql (PostgreSQL) 9.4.1

$ which psql
/c/Program Files/PostgreSQL/9.4/bin/psql

$ psql
 // nothing...
```

**Comment by dscho** [comment]
Isn't this covered in the [Release Notes](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues)?

> * Some console programs interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

**Comment by harriha** [comment]
Oh shoot, of course it is - and *now* I remember reading that multiple times earlier. Yeah, never mind, sorry for the noise, closing.

**Comment by dscho** [comment]
@harriha Maybe you have an idea how to solve that? Maybe we could set some aliases, e.g. something like

```sh
case "$TERM" in
xterm*)
    # The following programs are known to require a Win32 Console
    # for interactive usage, therefore let's launch them through winpty
    # when run inside `mintty`.
    for name in node php php5 psql python2.7
    do
        alias $name="winpty $name.exe"
    done
    ;;
esac
```

in `/etc/profile.d/aliases.sh`? Could you test whether that works okay?

**Comment by harriha** [comment]
@dscho Seems to work fine based on a quick test, thanks. Looks like a nice workaround, but I guess that doesn't really scale too well? Obviously, if there's no other ways to around this, this is much better than nothing - just should make it very clear (everywhere) that "if your interactive program seems to hang, do this-and-this". Otherwise, and probably even with such notice, there's going to be these kind of issues popping in continuously :).

**Comment by dscho** [comment]
> Otherwise, and probably even with such notice, there's going to be these kind of issues popping in continuously :).

I agree. It is of no use pointing out that we try to support Git here, and not a bazillion of interactive consoles for other software.

BTW can you think of more interactive interpreters than the ones I had listed?

**Comment by dscho** [comment]
Let's continue the discussion in https://github.com/git-for-windows/build-extra/pull/78
