### ISSUE TITLE
Use App Paths instead of appending to Path Environment variable

### ISSUE THREAD

**Issue by agowa** [git-for-windows/git#3990]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.1.windows.1
cpu: x86_64
built from commit: 323a69709944b193bb5cee81ff09fe9a4a686df5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.25182.1010]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell 7.2.6

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Feature Request
```
 - What did you expect to occur after running these commands?

The setup should not set the Path variable on Win11. It should use the more modern "App Paths" replacement.
App Paths allows the user to later select for each individual exe via the GUI (Settings, Apps, Advanced app settings, app execution aliases) if it should be resolved or not.
It is, therefore, more advanced than the old Path variable. Also, it allows to speed up command resolution and more importantly doesn't clutter the path variable (mine is currently extremely long and some applications are throwing errors in the setup because it exceeds their maximum expected length).
For App Path only a registry key needs to be created within `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths`. It would be great if the setup would be able to do this on its own.
An additional benefit all the Linux shell tools that ship with git could be registered too and a user could easily disable individual ones via the Settings UI.

 - What actually happened instead?

git changes the path variable and appends its directories to it.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> The setup should not set the Path variable on Win11. It should use the more modern "App Paths" replacement.

Is that even an _option_ for non-Store applications? Sure, you can play registry games, but that does not feel like the proper route.

@agowa338 do feel free to show what you mean by editing https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss accordingly and then opening a PR.

**Comment by rimrul** [comment]
> > The setup should not set the Path variable on Win11. It should use the more modern "App Paths" replacement.
> 
> Is that even an _option_ for non-Store applications? 

According to my research it's an option since _Windows XP_, so it slightly pre-dates the store. 

https://helgeklein.com/blog/how-the-app-paths-registry-key-makes-windows-both-faster-and-safer/

I'm not sure that it actually results in the `application aliases` entries mentioned above, though.

> Sure, you can play registry games, but that does not feel like the proper route.

That seems to be the only route for this. And if we add this, we need to put some thought into migration paths. Do we need a way from application paths back to `$PATH`? Can we get away with only migrating one way? Do we properly handle new or removed entries in `AppDir+'\{#MINGW_BITNESS}\bin'` and `AppDir+'\usr\bin'` on an upgrade? How do we need to warn the user if we would override existing app paths for existing executables of the same name? Do we leave app paths for non-"Git for Windows" executables of the same name alone on uninstall? The timing of removing registry entries and executables on uninstall might also become important.

**Comment by dscho** [comment]
This was up for grabs in over two years. I take the lack of enthusiasm for picking up this idea and opening a PR to mean that nobody really wants this.
