### ISSUE TITLE
GitBash Terminal does not work with AnsiConsole read commands. Throws System.InvalidOperationException

### ISSUE THREAD

**Issue by JMolisani** [git-for-windows/git#3996]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.1.windows.1
cpu: x86_64
built from commit: 05d80adb775077d673fab685009ede4a1003ed92
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1826]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: trunk
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

This problem occurs strictly within the C:\Program Files\Git\git-bash.exe terminal. If I run the C:\Program Files\Git\bin\bash.exe shell inside another terminal, like Windows terminal, I don't have any problems.
![git-bash.exe](https://user-images.githubusercontent.com/112415100/187255740-34d70ada-365c-4962-8c62-ae157e3c850e.png)
![bash.exeInWindowsTerminal](https://user-images.githubusercontent.com/112415100/187255765-be6ca5c6-7a0e-43df-8bbf-793e9024b534.png)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I built and ran the following [.NET 6 C# Console App](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)

```
using Spectre.Console;

bool done = false;

while (!done)
{
	AnsiConsole.WriteLine("Hello, world!");
	done = AnsiConsole.Confirm("Would you like to exit?");
}
```
While this was the simplest way to reproduce the issue, I can reproduce with any of the [AnsiConsole](https://spectreconsole.net/) input methods: `AnsiConsole.Ask()`, `AnsiConsole.Prompt()`, etc

 - What did you expect to occur after running these commands?

I expected `AnsiConsole.Confirm()` to display the prompt and wait for the user response, like it does in every other terminal I tested this with:
```
$ dotnet run
Hello, world!
Would you like to exit? [y/n] (y): y
```

 - What actually happened instead?

`AnsiConsole.Confirm()` displayed the prompt and then hit an uncaught exception while trying to wait for the user's response:
```
$ dotnet run
Hello, world!
Would you like to exit? [y/n] (y): Unhandled exception. System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
   at System.Console.get_KeyAvailable()
   at Spectre.Console.DefaultInput.ReadKeyAsync(Boolean intercept, CancellationToken cancellationToken) in /_/src/Spectre.Console/Internal/DefaultInput.cs:line 41
   at Spectre.Console.AnsiConsoleExtensions.ReadLine(IAnsiConsole console, Style style, Boolean secret, IEnumerable`1 items, CancellationToken cancellationToken) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Input.cs:line 22
   at Spectre.Console.TextPrompt`1.<>c__DisplayClass55_0.<<ShowAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Prompts/TextPrompt.cs:line 122
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.TextPrompt`1.ShowAsync(IAnsiConsole console, CancellationToken cancellationToken) in /_/src/Spectre.Console/Prompts/TextPrompt.cs:line 111
   at Spectre.Console.ConfirmationPrompt.ShowAsync(IAnsiConsole console, CancellationToken cancellationToken) in /_/src/Spectre.Console/Prompts/ConfirmationPrompt.cs:line 69
   at Spectre.Console.ConfirmationPrompt.Show(IAnsiConsole console) in /_/src/Spectre.Console/Prompts/ConfirmationPrompt.cs:line 54
   at Spectre.Console.AnsiConsole.Confirm(String prompt, Boolean defaultValue) in /_/src/Spectre.Console/AnsiConsole.Prompt.cs:line 57
   at Program.<Main>$(String[] args) in C:\***************\Program.cs:line 16

```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, I hadn't gotten to the point of adding git commands to this framework yet.

**Comment by dscho** [comment]
You seem to have run onto a common issue that is so common as to be listed in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]

**Comment by JMolisani** [comment]
I see, running the code with `winpty dotnet run` does fix this issue. Closing, thanks!
