### ISSUE TITLE
Node Console not loading on Win 8.1

### ISSUE THREAD

**Issue by radulemnaru** [git-for-windows/git#400]
I have the latest release of Node installed on Windows 8.1 and unfortunately the console does not load when I run >node. Running JS scripts directly with the node commands works fine but the console is not accessible.

**Comment by dscho** [comment]
This is a duplicate of https://github.com/git-for-windows/git/issues/399

**Comment by dscho** [comment]
@radulemnaru Did you have a look at the other ticket?

**Comment by radulemnaru** [comment]
Thanks the previous solution worked out well.
