### ISSUE TITLE
Installer hides PuTTY SSH client option

### ISSUE THREAD

**Issue by SLDiggie** [git-for-windows/git#4006]
Using installer Git-2.37.3-64-bit.exe , I've had to provide support to others in my organization who are setting up new systems and attempting to transfer SSH keys or recreate their prior setup with Git for Windows underpinning TortoiseGit.

They are running into significant problems because on a fresh system Git for Windows will not offer the option to use Putty's plink for SSH, and their key is in PuTTY's ppk format, which the bundled OpenSSH client does not support.

The problem is this code in the Inno Setup script /build-extra/installer/install.iss
https://github.com/git-for-windows/build-extra/blob/4f80d179aa51552ad347f76d16195967f1f87c40/installer/install.iss#L2103

```
    if (RegGetSubkeyNames(HKEY_CURRENT_USER,'Software\SimonTatham\PuTTY\Sessions',PuTTYSessions) and (GetArrayLength(PuTTYSessions)>0)) or
       (FileSearch('ssh.exe', GetEnv('PATH')) <> '') then begin
        SSHChoicePage:=CreatePage(PrevPageID,'Choosing the SSH executable','Which Secure Shell client program would you like Git to use?',TabOrder,Top,Left);
        // 1st choice
        RdbSSH[GS_OpenSSH]:=CreateRadioButton(SSHChoicePage,'Use bundled OpenSSH','This uses ssh.exe that comes with Git.',TabOrder,Top,Left);
        // 2nd choice
        if (GetArrayLength(PuTTYSessions)=0) then begin
            RdbSSH[GS_Plink]:=TRadioButton.Create(SSHChoicePage);
```

Unless the user has actually opened the PuTTY client and proceeded to save a session, which is something that's absolutely not needed to use PuTTY with TortoiseGit, the Git for Windows installer won't offer to use plink even though it's installed.

For now I have written a guide instructing users to install PuTTY, open it, and save a dummy session before installing Git for Windows. But this is silly and Google shows there are lots of people struggling to get Git to work properly with PuTTY. That's a shame because as long as the installer presents this option it works flawlessly.

So this bug is a request to make sure the installer offers to use Putty's plink as long as it's installed, which is surely what people should expect.

**Comment by dscho** [comment]
> Unless the user has actually opened the PuTTY client and proceeded to save a session, which is something that's absolutely not needed to use PuTTY with TortoiseGit, the Git for Windows installer won't offer to use plink even though it's installed.

We had way too many support requests that were simply due to PuTTY issues, that is why the reason we no longer offer PuTTY as an option _unless_ the user already set up a working session.

So what you reported is very much intentional, and it has saved us a lot of time hence.
