### ISSUE TITLE
Tab completion works differently after update

### ISSUE THREAD

**Issue by sryze** [git-for-windows/git#4012]
I noticed that in version 2.37.3 Bash completion for directories (cd command) works differently from 2.35 and it makes me press the TAB key twice instead of once when opening a directory (which I do a lot), i.e. causes loss of productivity.

If you create a symlink to a directory, i.e.
```
mklink /D %USERPROFILE%/Work /d/Work
```
and then you try to open it:
```
cd ~/W<TAB>
```
Bash completes the command as `cd ~/Work` instead of `cd ~/Work/`, as before. This means that you need to either type in the slash manually or press TAB again. 

I think that Git Bash should be able to detect if the symlink goes to a directory and append the `/` automatically, like it was doing before (not sure how that was implemented).

 - [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.3.windows.1
cpu: x86_64
built from commit: c4992d4fecabd7d111726ecb37e33a3ccb51d6f1
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1949]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM                        
Custom Editor Path:                       
Default Branch Option:                    
Path Option: Cmd                          
SSH Option: OpenSSH                       
Tortoise Option: false                    
CURL Option: OpenSSL                      
CRLF Option: CRLFCommitAsIs               
Bash Terminal Option: MinTTY              
Git Pull Behavior Option: Merge           
Use Credential Manager: Disabled          
Performance Tweaks FSCache: Enabled       
Enable Symlinks: Enabled                  
Enable Pseudo Console Support: Disabled   
Enable FSMonitor: Disabled                
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu or Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cd ~/W<TAB>
```
 - What did you expect to occur after running these commands?

Expected to see:
```
cd ~/Work/
```

 - What actually happened instead?

```
cd ~/Work
```
i.e. without the `/`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No

**Comment by dscho** [comment]
I see the described behavior in [MSYS2](https://msys2.github.io/) as well as in [Cygwin](https://cygwin.com/). Therefore, I assume that this is an intentional change.

If you pinpoint the exact [Git for Windows snapshot](https://wingit.blob.core.windows.net/files/index.html) that introduced this behavior, we might have an easier time to figure out how you can get the previous behavior back.

**Comment by sryze** [comment]
Thanks 

I found a workaround on StackExchange:

Add this to `~/.inputrc`:

```
set mark-symlinked-directories on
```

**Comment by sryze** [comment]
I will stick with 2.35 for now... Git for Windows 2.36 and up doesn't work well with ConEmu for some reason - keeps crashing on git pull/push/fetch.

**Comment by dscho** [comment]
Please note that the situation is unlikely to get better unless you choose to do something about it. Open source is only ever as good as its contributors make it.

**Comment by sryze** [comment]
Yeah, that's true. But the thing is, it will probably take me forever to find what causes the bug in a project as complex as ConEmu, and I don't have a lot of free time - but code maintainers, on the other hand, can probably pinpoint the issue much faster than me, so I'm just stick to reporting bugs when I see them, and hope to get a fix in the next release 😃 

And based on my past experience submitting fixes to big projects on GitHub, sadly the PR has a pretty good chance of being ignored for a few months (or years) because the company/author has other priorities or is no longer active (or maybe my code is crap).
