### ISSUE TITLE
Improve FAQ: SSH agent conflict when running in CMD/PowerShell terminals (with solution)

### ISSUE THREAD

**Issue by 2bam** [git-for-windows/git#4016]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.3.windows.1
cpu: x86_64
built from commit: c4992d4fecabd7d111726ecb37e33a3ccb51d6f1
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1889]    
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt


Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD/PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh-add <private-key-path>
git clone <private-repo-url>
```
 - What did you expect to occur after running these commands?

To be able to authenticate and clone the repo.

 - What actually happened instead?

Rejected due to "Permission Denied (publickey)". Notice it works perfectly with Git Bash, just not with CMD/PowerShell.

With a vanilla installation with everything default (next next next...) it doesn't work out of the box with CMD/PowerShell because there is a conflict: 

The default ssh path is `C:\WINDOWS\System32\OpenSSH` while git uses the installed path.  
It takes some time to figure out `ssh-add` is adding keys to the Windows service agent instead the one used by git.

Also, git depends on the env vars `SSH_AGENT_PID` & `SSH_AUTH_SOCK` that are set by `start-ssh-agent.cmd` otherwise it will not work, silently. The necessity to call that script is not stated with the importance it should.  
I think it should be documented in the FAQ that the `start-ssh-agent.cmd` should be called for that permission rejection message, and to explain it sets some magic env vars dependencies.  
And that spawns a new cmd with them, as just calling the script doens't work, you need to stay calling inside that subprocess.

A lot of solutions on the web are to just "use an `~/.ssh/id_rsa` filename" but that forces you to input the passphrase on each git call as it's loading it each time git is called and the agent is not found (I guess). That's very inconvenient.

I think a ssh-agent diagnostics script could go really far in terms of user experience (I could try to provide one).

These are the steps I had to figure out to make it work: https://gist.github.com/2bam/33347ff54be8088943450f20323fde53

I know using Git Bash was the easier solution but I couldn't use it:
I call git from an automation program, didn't want to spawn a new git bash instance per call, and didn't want to run on an git bash env. I had to copy `start-ssh-agent.cmd` behavior from within my program (find pid and pipe heuristics) in order to successfully set the env vars and do several automated git calls from it. This is very cumbersome.

Thanks for your time.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No

**Comment by dscho** [comment]
> I think it should be documented in the FAQ that the `start-ssh-agent.cmd` should be called for that permission rejection message, and to explain it sets some magic env vars dependencies.

Could you suggest a concrete text that should be added?

**Comment by 2bam** [comment]
Hi dscho, sure I can try.  
I'd put it inside the already present "_I get "Permission denied (publickey)." when using git pull_"
adding "git clone" to the title.

English is not my native language so you might need to correct it.

> If you choose to use OpenSSH that comes with git during installation (default option) and wish to work from Windows' Command Prompt (cmd) or PowerShell instead of Git Bash you should make sure:
>
>1. You're calling the correct executables.  
>Windows comes with a different OpenSSH distribution and by default you might be calling it while git commands use its own.
Set the environment PATH to use the git installation ssh commands first, those are usually at `C:\Program Files\Git\usr\bin`.  
In CWD: `set PATH=C:\Program Files\Git\usr\bin;%PATH%`  
In PowerShell: `$Env:PATH = "C:\Program Files\Git\usr\bin;$Env:PATH"`  
This will make sure, for example, that you add the private keys to the correct _ssh-agent service_ when calling `ssh-add`.
Otherwise you might be asked to introduce the passphrase on each git command call that connects to a remote repository.
>
>2. Git's ssh is able to connect to the ssh-agent.  
>In order to connect to the _ssh-agent service_, git's ssh needs to know _how_. This is accomplished by two environment variables called `SSH_AGENT_PID` and `SSH_AUTH_SOCK`.
Luckily, there is a convenient script `start-ssh-agent.cmd` included with the git installation you can call to set this up. The values are dynamic and only valid after calling the script. Forgetting to set them will fail silently, so be sure to call the script each time you open a new command prompt.

What do you think?

**Comment by dscho** [comment]
> English is not my native language so you might need to correct it.

English is not my native language, either.

> What do you think?

Sounds good to me! Please [make those edits](https://github.com/git-for-windows/git/wiki/FAQ/_edit).

**Comment by dscho** [comment]
Fixed via https://github.com/git-for-windows/git/wiki/FAQ/_compare/4c978c2c8953dbd68726216326bf61c52ecd960b...37363ba88a406f1f01d7ff1507ebf0f93aead1a8?short_path=c7bd425#diff-c7bd425fd98aad1f9fef20099637bcbdcfadeb566ba1f83bb40ce484f195b8cf. Thanks, @2bam!

**Comment by 2bam** [comment]
Happy to help
