### ISSUE TITLE
Line 3444: Run Post-Install scripts fix

### ISSUE THREAD

**Issue by TrifaldiPribadi** [git-for-windows/git#4019]
![Screenshot 2022-09-14 033332](https://user-images.githubusercontent.com/113425339/190003775-a318f405-5c66-40c2-a717-3ea7cd96c3c8.png)

How can i fix this?after i click ok, i can't open the git bash

**Comment by dscho** [comment]
Run the installer using the `/LOG=log.txt` option and then inspect the `log.txt` file to find out what is going wrong.

**Comment by TrifaldiPribadi** [comment]
> /LOG=log.txt

how to run the installer with that?im newbie

**Comment by TrifaldiPribadi** [comment]
i already run the post.install.bat, but the system say "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item"

**Comment by dscho** [comment]
> > /LOG=log.txt
> 
> how to run the installer with that?im newbie

You press Windows+R, type `cmd` and then press Enter. Then, you type `cd Downloads` and press Enter. This will get you into the directory where your downloads are. Then, you type `Git-2` and press Tab so that it can complete the full installer name, then append ` /LOG=log.txt` and press Enter. After the installation, you look at the contents of the newly-created `log.txt` file in the Downloads folder.

> i already run the post.install.bat, but the system say "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item"

This script must be run with the same privileges as the installer, which typically has elevated permissions. You cannot run it just like that.

**Comment by TrifaldiPribadi** [comment]
> 

i already do that and the log is like this

2022-09-18 01:47:45.285   Line 3441: Executing C:\Program Files\Git\post-install.bat
2022-09-18 01:47:45.364   Message box (OK):
                          Line 3444: Unable to run post-install scripts:
                          
                          C:\Program Files\Git>	@IF 10 LEQ  @(
2022-09-18 01:47:48.752   User chose OK.
2022-09-18 01:47:48.752   Line 3444: Unable to run post-install scripts:
                          
                          C:\Program Files\Git>	@IF 10 LEQ  @(
2022-09-18 01:47:48.918   Need to restart Windows? No
2022-09-18 01:47:51.470   -- Run entry --
2022-09-18 01:47:51.470   Run as: Original user
2022-09-18 01:47:51.470   Type: Exec
2022-09-18 01:47:51.470   Filename: C:\Program Files\Git\git-bash.exe
2022-09-18 01:47:51.470   Parameters: --cd-to-home
2022-09-18 01:47:52.498   Deinitializing Setup.
2022-09-18 01:47:52.517   Log closed.

**Comment by dscho** [comment]
Maybe your problem is the same as was diagnosed [here](https://github.com/git-for-windows/git/issues/1585#issuecomment-377004605)?

**Comment by dscho** [comment]
I don't feel that this ticket is going anywhere, so I'm going to close it.
