### ISSUE TITLE
Forget git-gui localization in letest releases in regular installer

### ISSUE THREAD

**Issue by tonal** [git-for-windows/git#403]
In releases 2.5.1 and 2.5.2 forget localization files *.msg for git-gui and gitk-git
Installer:
Git-2.5.2.2-32-bit.exe
Git-2.5.2.2-64-bit.exe

**Comment by dscho** [comment]
This is a duplicate of your very own ticket: https://github.com/git-for-windows/git/issues/378, and my point from there stands: it was still [a conscious decision to leave the localization out](https://github.com/git-for-windows/git/issues/262).
