### ISSUE TITLE
Git add fails when trying to stage tracked files in an ignored folder

### ISSUE THREAD

**Issue by AJH16** [git-for-windows/git#4030]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

This is a change between:
git version 2.24.0.windows.1
cpu: x86_64
built from commit: 6a3fa2a1833f3c7ac71cefefe44b3a4b4138e220
sizeof-long: 4
sizeof-size_t: 8

and

git version 2.30.2.windows.1
cpu: x86_64
built from commit: 37f0a4afad027cf030747a1ef45537ba86162960
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
64 bit Windows Server 2019 Standard
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.3406]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

It is a build server hosting multiple Azure Devops Agents.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Issue shows in both cmd and from within the Azure Devops agent.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add
```

Specifically, I am doing an add to stage changes within a folder that is in the .gitignore file (as any new files in the folder should be ignored), however a subset of files which we do care about are tracked already and should be staged.

 - What did you expect to occur after running these commands?

Add happens normally and without error, as it has in the past.

 - What actually happened instead?

The add occurs successfully, however an informational message is sent to stderr and the error level is set to 1.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happens in multiple repositories.

Details I have tracked down so far:
The underlying problem appears to have to do with the behavior of dir.  Based on the logic for add in 2.24.0, there doesn't seem to be any significant change between then and 2.30.2, however the behavior observed in 2.24.0 means that the dir.ignored_nr value must have resolved as 0 in 2.24.0, but now resolves as a >0 value in 2.30.2 and newer.  I attempted to dig further down in to this, but had trouble following it down that far.  Any insights that might help with further trouble shooting would be helpful.  

Worst case scenario, I can always switch to using a git add -f -u instead, but this means that a lot more understanding of the environment is necessary to choose the proper staging commands than was needed before this change and it seems like an odd removal of functionality that I couldn't find anything that seemed to indicate this change was intentional, so I figured I should bring it up.

**Comment by dscho** [comment]
Thank you for writing up this report. It looks as if the described issue is not specific to Windows, though Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently). You may want to provide a [Minimal, Complete & Verifiable Example](https://stackoverflow.com/help/mcve) and paste the informational message verbatim, to avoid forcing the reader to guess.
