### ISSUE TITLE
html pages are not 'hyperlinked'

### ISSUE THREAD

**Issue by snaewe** [git-for-windows/git#404]
I'm on Win7, git-for-windows 2.5.2.windows.2

The html pages that come with Git for Windows are note hyperlinked.
Take a look at the man page (html page that is) of 'git' itself.
In the second paragraph of the 'Description' section, I see

    See linkgit:gittutorial[7] to get started, then see linkgit:giteveryday[7] for a useful minimum set of commands.

Which is not quite correct I presume.

**Comment by snaewe** [comment]
Oh. I just noticed that in the next sentence of the above mentioned paragraph the link to "Git Users' Manual" is correct.

**Comment by dscho** [comment]
Let's put some precision into this description. Do I understand correctly that you meant to instruct me to

1. run `git help git` in a Git Bash,
2. observe the following paragraph below the synopsis: 
![incorrect-linkgit](https://cloud.githubusercontent.com/assets/127790/9953879/e6c3caca-5de4-11e5-94f6-a8c39e4d07db.png)

If so, then good: I can reproduce.

Now, this is what you can do about it:

1. install the [Git for Windows SDK](http://git-for-windows.github.io/#download-sdk)
2. [build the Git package](https://github.com/git-for-windows/git/wiki/Building-Git)
3. debug why [the `linkgit`](https://github.com/git-for-windows/git/blob/0c51399ed604ac72935377eb1fba10c69f1bc01a/Documentation/git.txt#L24) is not interpreted while [the `link`](https://github.com/git-for-windows/git/blob/0c51399ed604ac72935377eb1fba10c69f1bc01a/Documentation/git.txt#L26) is

You could also debug that in `/usr/src/git/Documentation`, but you need to make sure to copy the ASCIIDOC settings from `/usr/src/MINGW-packages/mingw-git/PKGBUILD`.

**Comment by dscho** [comment]
I just added the label `unclear` because it is not clear whether the bug is in the `PKGBUILD` settings or in the ASCIIDOC invocation in Git's repository. As soon as you find out and let us know, I will replace that label with the correct one.

**Comment by nalla** [comment]
it seems to be the invocation. `cd /usr/src/git/Documentation && asciidoctor --verbose --trace -I/mingw64/lib/asciidoctor-extensions -rman-inline-macro git.txt` seems to work.

**Comment by nalla** [comment]
Found it. If you run `make clean && make -j8 html SHELL='sh -x'` you can see the output. There you can see `asciidoctor '-alitdd=&#45;&#45;' -a git-asciidoc-no-roff '-I/mingw64/lib/asciidoctor-extensions -rman-inline-macro' -agit_version=2.5.2.windows.2 -b html5 -d manpage -o git.html.new git.txt`

If you remove the two `'`s in the include and library invocation it works again.

**Comment by dscho** [comment]
@nalla you are truly awesome!

**Comment by nalla** [comment]
OT: @dscho is it faith that issue #404 is `html` related?

**Comment by dscho** [comment]
@nalla it is part of the Greater Scheme of the Universe, for sure!
