### ISSUE TITLE
git not recognicing network drive 

### ISSUE THREAD

**Issue by Naeaeaeaeae** [git-for-windows/git#4045]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.3.windows.1
cpu: x86_64
built from commit: c4992d4fecabd7d111726ecb37e33a3ccb51d6f1
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.2006]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

i have an unraid server with a network smb drive attached to my machine.
The drive works with all Programms as intended but not with git

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD/Poweshell/VS Code/VS Code Insider preview

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init and git clone, doenst matter, create/clone a repo on the network drive. The creation works but then nothing else.

if I try git pull:
fatal: detected dubious ownership in repository at '//fibre.norcunas.de/Projects/stableDiffusion'
'//fibre.norcunas.de/Projects/stableDiffusion' is owned by:
        'S-1-5-21-1249446848-000000000-0000000000-0000'
        but the current user is:
                'S-1-5-21-2386680829-000000000-0000000000-0000'
                To add an exception for this directory, call:

                        git config --global --add safe.directory '%(prefix)///fibre.norcunas.de/Projects/stableDiffusion'

Ich changed the last numbers manually to zero before copying
I dont know what to change, i have rights to change files, ... but idk where to change the user.

I tried to add the directory to the safe ones:
git config --global --get-all safe.directory
'%(prefix)///fibre.norcunas.de/Projects/
'*'
'*'
'*'
O:\
O:\stableDiffusionAPI
'%(prefix)///fibre.norcunas.de/Projects/'
'%(prefix)///fibre.norcunas.de/Projects/stableDiffusionAPI'
```
 - What did you expect to occur after running these commands?

a usable git repo. Absolute nothing works. If I copy the folder on a local drive all works fine.

 - What actually happened instead?

look above

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

all repos, local, new cloned, doesn`t matter

**Comment by dscho** [comment]
> git config --global --get-all safe.directory
> '%(prefix)///fibre.norcunas.de/Projects/
> '*'
> '*'
> '*'
> O:\
> O:\stableDiffusionAPI
> '%(prefix)///fibre.norcunas.de/Projects/'
> '%(prefix)///fibre.norcunas.de/Projects/stableDiffusionAPI'

Since Git cannot detect from which interactive terminal it is invoked, it cannot determine what quoting convention needs to be used, and therefore it defaults to POSIX shell quoting conventions (single quotes).

However, you are using CMD or PowerShell, where you need to use double quotes. If you use single quotes, they end up in the config and are treated as if they were part of the config value/directory name.

This should fix it on your side:

```console
git config --global --add safe.directory "%(prefix)///fibre.norcunas.de/Projects/stableDiffusion"
```

(note the double quote character `"` instead of the single quote character `'`)
