### ISSUE TITLE
Windows 11 SmartScreen

### ISSUE THREAD

**Issue by ohhmm** [git-for-windows/git#4046]
Installation of 2.37.3 downloaded from https://git-scm.com/downloads is failing with multiple SmartScreen notifications. 
Visual Studio bundled git works.

**Comment by ohhmm** [comment]
Any plans for adding git firewall rules to installer?

**Comment by dscho** [comment]
> Any plans for adding git firewall rules to installer?

I was not even aware that such rules might be needed.

**Comment by ohhmm** [comment]
For default blocking firewall setup, Windows installers may tell which executable use which ports.
Otherwise admins do this manually.
That would be convenient. Thanks.

**Comment by dscho** [comment]
> For default blocking firewall setup, Windows installers may tell which executable use which ports.
> Otherwise admins do this manually.

But Git does not use any specific ports by default, unless you count 443 (and potentially 80) for cloning/fetching/pushing.

**Comment by ohhmm** [comment]
Yes, every used port including 443 for git-connector-https.exe and 22

**Comment by mfriedrich74** [comment]
Hi, I am confused, you talk about target ports, not local ports, correct?
Don't these depend on the user or server the user wants git to connect to?

**Comment by rimrul** [comment]
> Hi, I am confused, you talk about target ports, not local ports, correct?
> Don't these depend on the user or server the user wants git to connect to?

Yes, all the ports we mentioned are remote ports. Those definitely depend on the remotes the user wants to connect to, but there are certain standard ports fir the supported protocols that are commonly used.

We obviously can't add rules for every port a user might theoretically want to use.
