### ISSUE TITLE
git clone ssh key -i error

### ISSUE THREAD

**Issue by pcouas** [git-for-windows/git#4049]
Hi,

I use git 2.37 on Windows 10 and i have an problem with git clone ssh

This command is Ok

ssh git@127.0.0.1 -v -p 2223 -i Z:\zpoubelle\tssh4\id_rsa
But following command failed

set GIT_SSH_COMMAND="ssh -p 2223-i Z:\zpoubelle\tssh4\id_rsa"
git clone git@127.0.0.1:2223/srv/git/your-repo.git --verbose

"ssh -p2223-i Z:\zpoubelle\tssh4\id_rsa": line 1: ssh -p 2223-i Z:\zpoubelle\tssh4\id_rsa: No such file or directory

Regards

**Comment by rimrul** [comment]
> Hi,
> 
> I use git 2.37 on Windows 10 and i have an problem with git clone ssh
> 
> This command is Ok
> 
> ssh git@127.0.0.1 -v -p 2223 -i Z:\zpoubelle\tssh4\id_rsa

That's probably the `ssh.exe` bundled with Git for Windows, called from Git CMD, which means the Windows to Posix path conversion turns this into 
`ssh git@127.0.0.1 -v -p 2223 -i /z/zpoubelle/tssh4/id_rsa` internally.

> But following command failed
> 
> set GIT_SSH_COMMAND="ssh -p 2223-i Z:\zpoubelle\tssh4\id_rsa"
> git clone git@127.0.0.1:2223/srv/git/your-repo.git --verbose

Could you try

 ```
set GIT_SSH_COMMAND="ssh -p 2223-i /z/zpoubelle/tssh4/id_rsa"
git clone git@127.0.0.1:2223/srv/git/your-repo.git --verbose
```

> 
> "ssh -p2223-i Z:\zpoubelle\tssh4\id_rsa": line 1: ssh -p 2223-i Z:\zpoubelle\tssh4\id_rsa: No such file or directory
> 
> 
> Regards

**Comment by pcouas** [comment]
Hisame problem, sorryenvoyé : 4 octobre 2022 à 08:06de : Matthias Aßhauer ***@***.***>à : git-for-windows/git ***@***.***>cc : pcouas ***@***.***>, Author ***@***.***>objet : Re: [git-for-windows/git] git clone ssh key -i error (Issue #4049) Hi,I use git 2.37 on Windows 10 and i have an problem with git clone sshThis command is Okssh ***@***.*** -v -p 2223 -i Z:\zpoubelle\tssh4\id_rsaThat's probably the ssh.exe bundled with Git for Windows, called from Git CMD, which means the Windows to Posix path conversion turns this into ssh ***@***.*** -v -p 2223 -i /z/zpoubelle/tssh4/id_rsa internally.But following command failedset GIT_SSH_COMMAND="ssh -p 2223-i Z:\zpoubelle\tssh4\id_rsa" git clone ***@***.***:2223/srv/git/your-repo.git --verboseCould you tryset GIT_SSH_COMMAND="ssh -p 2223-i /z/zpoubelle/tssh4/id_rsa"
git clone ***@***.***:2223/srv/git/your-repo.git --verbose
"ssh -p2223-i Z:\zpoubelle\tssh4\id_rsa": line 1: ssh -p 2223-i Z:\zpoubelle\tssh4\id_rsa: No such file or directoryRegards—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dscho** [comment]
@pcouas if you truly have the same problem, I wonder whether you feel up to trying the indicated commands that could potentially help resolve the problem for you.
