### ISSUE TITLE
Git-2.38.0 can not use ctrl+v shotcut in windows10

### ISSUE THREAD

**Issue by profection** [git-for-windows/git#4054]
I update my git for windows from version 2.20.1 to version 2.38.0 and find one problem :
newer version can not use ctrl+v shotcut to paste text.
I tried several times, the older version can do ctrl+v while newer version failed to do the work, can you fix that?

**Comment by profection** [comment]
> > newer version can not use ctrl+v shotcut to paste text.
> 
> This never worked in Git Bash. Care to clarify @profection? It is a bit disappointing that you deleted the bug reporting template instead of filling it out. All of this information is now unavailable, and therefore there is little anybody else can do to help you.

### version 2.20.1 can use ctrl+v to paste, why newer version can't ?

the following is the form, I filled it up this time

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.0.windows.1
cpu: x86_64
built from commit: 0355083fbe5582f6d3f819afc130ed2f2375e0bd
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.2075]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled


```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Right click menu option 'Git Bash Here'

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ctrl+V
```
 - What did you expect to occur after running these commands?

Paste things from clipboard

 - What actually happened instead?

After using shotcut key 'ctrl+V', I only can see '^V' printed in command line. I need to use right click or 'ctrl+ins' command If I want to paste from clipboard

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I am using the older version 2.20.1 now and the ctrl+V command can do paste from clipboard, while this newer version can't ,  can someone change it back ?

**Comment by dscho** [comment]
At least for me, <kbd>Ctrl</kbd>+<kbd>V</kbd> _never_ pasted the clipboard, I always had to use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd>. That is of course behavior well-known on Unix/Linux. Maybe https://www.quora.com/Why-does-CTRL-V-not-paste-in-a-Bash-Linux-shell will shed more light into the problem.
