### ISSUE TITLE
Create a new release without libssp dependency

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#4064]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

libssp was removed in MSYS2. See msys2/MINGW-packages#13401 and https://www.msys2.org/news/#2022-10-10-libssp-is-no-longer-required

Git fails to execute when updating the base packages. Rebuilding Git solves the issue.

Please release 2.38.0(2) version without libssp dependency.

Thanks!

**Comment by labkeeper** [comment]
+1 
After initial SDK installation. Installed today (2022-10-12) from file git-sdk-installer-1.0.8-64.7z.exe
```
'C:\WINDOWS\system32\drivers\etc\hosts' -> '/etc/hosts'

'C:\WINDOWS\system32\drivers\etc\protocol' -> '/etc/protocols'

'C:\WINDOWS\system32\drivers\etc\services' -> '/etc/services'

'C:\WINDOWS\system32\drivers\etc\networks' -> '/etc/networks'

C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory

                                                                Could not initialize /usr/src/git

C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory

                                                                Could not initialize /usr/src/build-extra

C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory

                                                                Could not initialize /usr/src/MINGW-packages

C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory

                                                                Could not initialize /usr/src/MSYS2-packages
```
Unable to sdk init git:
```
$ sdk init git

C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory

                                                                                                                                                Could not initialize /usr/src/git
```

**Comment by labkeeper** [comment]
> +1 After initial SDK installation. Installed today (2022-10-12) from file git-sdk-installer-1.0.8-64.7z.exe
> 
> ```
> 'C:\WINDOWS\system32\drivers\etc\hosts' -> '/etc/hosts'
> 
> 'C:\WINDOWS\system32\drivers\etc\protocol' -> '/etc/protocols'
> 
> 'C:\WINDOWS\system32\drivers\etc\services' -> '/etc/services'
> 
> 'C:\WINDOWS\system32\drivers\etc\networks' -> '/etc/networks'
> 
> C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory
> 
>                                                                 Could not initialize /usr/src/git
> 
> C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory
> 
>                                                                 Could not initialize /usr/src/build-extra
> 
> C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory
> 
>                                                                 Could not initialize /usr/src/MINGW-packages
> 
> C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory
> 
>                                                                 Could not initialize /usr/src/MSYS2-packages
> ```
> 
> Unable to sdk init git:
> 
> ```
> $ sdk init git
> 
> C:/git-sdk-64/mingw64/bin/git.exe: error while loading shared libraries: libssp-0.dll: cannot open shared object file: No such file or directory
> 
>                                                                                                                                                 Could not initialize /usr/src/git
> ```

Fixed. It seems I have collision between GIT-SCM installation and gitforwindows. Git for windows bash has GIT-SCM first in path.

**Comment by orgads** [comment]
You don't need to drop `-fstack-protector`. Just build with the latest gcc and it will work.

**Comment by BasixKOR** [comment]
Workaround commit: https://github.com/git-for-windows/git-sdk-64/commit/706bd79657552828851df823edf8a189461bcd7d

**Comment by dscho** [comment]
> You don't need to drop `-fstack-protector`. Just build with the latest gcc and it will work.

Which means that if you had installed the `pkg-x86_64` artifact of the latest [`git-artifacts` run](https://github.com/git-for-windows/git-sdk-64/actions/workflows/git-artifacts.yml), it would have worked around the issue?

I ask because I specifically want to stress that you reported an issue in a scenario that was explicitly marked as "you're on your own, if you can help others using the same scenario, that's great, but do not bother opening a ticket in the Git for Windows bug tracker":

![image](https://user-images.githubusercontent.com/127790/196186672-b7b04c2d-6db3-4507-b070-4d06c61973af.png)

So: figuring out all of this is safely in the "this distracts an already overloaded maintainer, and the contributors really should try harder to avoid that" court.

**Comment by orgads** [comment]
> > You don't need to drop `-fstack-protector`. Just build with the latest gcc and it will work.
> 
> Which means that if you had installed the `pkg-x86_64` artifact of the latest [`git-artifacts` run](https://github.com/git-for-windows/git-sdk-64/actions/workflows/git-artifacts.yml), it would have worked around the issue?

It does, I searched but didn't know where to find it. Thank you.

> I ask because I specifically want to stress that you reported an issue in a scenario that was explicitly marked as "you're on your own, if you can help others using the same scenario, that's great, but do not bother opening a ticket in the Git for Windows bug tracker":
> 
> ![image](https://user-images.githubusercontent.com/127790/196186672-b7b04c2d-6db3-4507-b070-4d06c61973af.png)
> 
> So: figuring out all of this is safely in the "this distracts an already overloaded maintainer, and the contributors really should try harder to avoid that" court.

I see your point, and I wasn't aware of this page either (before you brought it to my attention). Thanks and sorry for disturbing.
