### ISSUE TITLE
File ownership under permanent admin rights

### ISSUE THREAD

**Issue by jdnewmil** [git-for-windows/git#4068]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.0.windows.1
cpu: x86_64
built from commit: 0355083fbe5582f6d3f819afc130ed2f2375e0bd
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.2006]
```

 - What options did you set as part of the installation? Or did you choose the defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related to the issue you're seeing?

> I am in an enterprise environment, and my company has instituted
> BeyondTrust to contain cyber threats, but that solution is not practical for me, so I am compelled to run
> with "permanent admin rights" in order to perform "data science" tasks.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

> Until now, mostly Anaconda CMD and Cygwin Bash. Git Bash has the
> same issue. The only CLI that doesn't have the issue at the
> moment is WSL2 Bash.

What commands did you run to trigger this issue? If you can provide a  Minimal, Complete, and Verifiable example this will help us understand the issue.

```
mkdir test_dir
cd test_dir
git init
ls -la .git
```

What did you expect to occur after running these commands?

```
# Cygwin Bash
$ ls -la .git
total 11
drwx------+ 1 JNEWM Domain Users   0 Oct 13 10:40 .
drwx------+ 1 JNEWM Domain Users   0 Oct 13 10:40 ..
-rwx------+ 1 JNEWM Domain Users  23 Oct 13 10:40 HEAD
drwx------+ 1 JNEWM Domain Users   0 Oct 13 10:40 branches
-rwx------+ 1 JNEWM Domain Users 112 Oct 13 10:40 config
-rwx------+ 1 JNEWM Domain Users  73 Oct 13 10:40 description
drwx------+ 1 JNEWM Domain Users   0 Oct 13 10:40 hooks
drwx------+ 1 JNEWM Domain Users   0 Oct 13 10:40 info
drwx------+ 1 JNEWM Domain Users   0 Oct 13 10:40 objects
drwx------+ 1 JNEWM Domain Users   0 Oct 13 10:40 refs

# Git Bash - this is the same repo as the Cygwin Bash just shown
$ ls -la .git
total 11
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 10:40 ./
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 10:40 ../
-rw-r--r-- 1 JNEWM 1049089  23 Oct 13 10:40 HEAD
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 10:40 branches/
-rw-r--r-- 1 JNEWM 1049089 112 Oct 13 10:40 config
-rw-r--r-- 1 JNEWM 1049089  73 Oct 13 10:40 description
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 10:40 hooks/
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 10:40 info/
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 10:40 objects/
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 10:40 refs/
```

What actually happened instead?

```
# Cygwin Bash
$ ls -la .git
total 11
drwxrwx---+ 1 Administrators Domain Users   0 Oct 13 09:12 .
drwx------+ 1 JNEWM          Domain Users   0 Oct 13 09:14 ..
-rwxrwx---+ 1 Administrators Domain Users  23 Oct 13 09:12 HEAD
-rwxrwx---+ 1 Administrators Domain Users 130 Oct 13 09:12 config
-rwxrwx---+ 1 Administrators Domain Users  73 Oct 13 09:12 description
drwxrwx---+ 1 Administrators Domain Users   0 Oct 13 09:12 hooks
drwxrwx---+ 1 Administrators Domain Users   0 Oct 13 09:12 info
drwxrwx---+ 1 Administrators Domain Users   0 Oct 13 09:12 objects
drwxrwx---+ 1 Administrators Domain Users   0 Oct 13 09:12 refs

# Git Bash - same repo as just shown - problem not visible here
$ ls -la .git
total 11
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 09:12 ./
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 09:14 ../
-rw-r--r-- 1 JNEWM 1049089  23 Oct 13 09:12 HEAD
-rw-r--r-- 1 JNEWM 1049089 130 Oct 13 09:12 config
-rw-r--r-- 1 JNEWM 1049089  73 Oct 13 09:12 description
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 09:12 hooks/
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 09:12 info/
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 09:12 objects/
drwxr-xr-x 1 JNEWM 1049089   0 Oct 13 09:12 refs/
```

 - If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing?

> Not specific to a particular repo.

### Narrative

When I enter

```
git init
```

an empty repository is created, but all files and directories thus created are marked as being owned by (local) Administrators. Development tools such as VSCode then fail to recognize the repo. If I use "File Manager Properties Security Advanced" then I can alter the owner, and VSCode will see the repo. In addition, once the repo ownership has been corrected, I can use VSCode (started from the CMD window from which I initialized the window) to manipulate the repo without introducing ownership problems. But every time I use the CLI to make changes I get ownership problems with newly-introduced files.

```
# from same CMD shell
C:\test> whoami
ourdomain\jnewm
```

I have tried
```
git config --global core.sharedRepository false
```

but the files still come up owned by (local) Administrators, interfering with using other tools.

**Comment by jdnewmil** [comment]
When I download `git-sdk-64` and compile git commit `5ff6506c5` for [debugging](https://github.com/git-for-windows/git/wiki/Debugging-Git) in `gdb`, the ownership problem goes away (kind of hard to find the problem that way). Is this behavior specific to the Visual Studio build of Git? I don't have VSCE... my install restrictions are getting in the way.

Here are my git-config settings:

```
C:\Users\JNEWM\Documents\tmp\gittest\permissions\test21>git config --list
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=jdnewmil
user.email=jnewm@ourdomain.com
merge.tool=TortoiseMerge
diff.guitool=winmerge
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
core.autocrlf=true
core.longpaths=true
core.sharedrepository=false
difftool.winmerge.path=C:/Program Files (x86)/WinMerge/winmergeu.exe
difftool.winmerge.cmd="C:/Program Files (x86)/WinMerge/winmergeu.exe" -e -u "$LOCAL" "$REMOTE"
mergetool.TortoiseMerge.path=C:/Program Files/TortoiseGit/bin/TortoiseGitMerge.exe
mergetool.TortoiseMerge.cmd="C:/Program Files/TortoiseGit/bin/TortoiseGitMerge.exe" -base:"$BASE" -mine:"$LOCAL" -theirs:"$REMOTE" -merged:"$MERGED"
gui.recentrepo=C:/Users/JNEWM/Documents/tmp/GitTmp/Perryman
alias.adog=log --all --decorate --oneline --graph
credential.helper=wincred
init.defaultbranch=master
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
```

**Comment by dscho** [comment]
> I am compelled to run
> with "permanent admin rights"

I guess I do not quite understand how to replicate this on my machine.

Also, `ls -l` is usually a poor fit when trying to determine file permissions because `ls -l` operates under the incorrect assumption of the simplistic Unix permission model where each file has read/write/executable bits for user/group/other. It might make more sense to use [`icacls`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/icacls) to determine file permissions.

**Comment by jdnewmil** [comment]
File permissions are not really relevant... file ownership is the issue, and dir /q is probably the best indicator that agrees with cygwin above.

I can't say how you could reproduce this error either, but if you can tell me how to stop GfW from touching anything related to file ownership or group permissions then I think my problem would be manageable.

On November 22, 2022 12:26:25 AM PST, Johannes Schindelin ***@***.***> wrote:
>> I am compelled to run
>> with "permanent admin rights"
>
>I guess I do not quite understand how to replicate this on my machine.
>
>Also, `ls -l` is usually a poor fit when trying to determine file permissions because `ls -l` operates under the incorrect assumption of the simplistic Unix permission model where each file has read/write/executable bits for user/group/other. It might make more sense to use [`icacls`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/icacls) to determine file permissions.
>

-- 
Sent from my phone. Please excuse my brevity.

**Comment by dscho** [comment]
> I can't say how you could reproduce this error either

I meant: could you provide detailed instructions how to enable permanent admin rights?

> if you can tell me how to stop GfW from touching anything related to file ownership or group permissions then I think my problem would be manageable.

Git for Windows has to create the files _somehow_. And I believe that that is where things get hairy: Git uses the standard API functions for that, and does not go out of its way to change ownership. It simply uses the default, is all. So I'd need to reproduce the issue locally to form a better understanding where the ownership is determined, and what Cygwin does differently.
