### ISSUE TITLE
wish.exe doesn't support cygpaths

### ISSUE THREAD

**Issue by ModifiedDog** [git-for-windows/git#4078]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.2006]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I'm aware of

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
gitk
```

 - What did you expect to occur after running these commands?

See gitk window

 - What actually happened instead?

Error message window:
Title: Error in startup script
Message: couldn't read file "/mingw64/bin/gitk": no such file or directory

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Local personal repo

This appears to be a problem with wish.exe. I'm not able to pass it any cygpath without error. I am able to work around this by running

```
wish "$(cygpath -w /mingw64/bin/gitk)"
```

**Comment by dscho** [comment]
I cannot reproduce. If I open `gitk` in a Git Bash, it works, and I do not see that problem. Can you elaborate what `which wish` says? Is this in WSL instead of Git Bash?

**Comment by ModifiedDog** [comment]
```
$ which wish
/mingw64/bin/wish
```

**Comment by ModifiedDog** [comment]
I'm an idiot

```
$ env | grep MSYS_NO_PATHCONV
MSYS_NO_PATHCONV=1
```
