### ISSUE TITLE
Follow Semver Rules when git version is run

### ISSUE THREAD

**Issue by vbjay** [git-for-windows/git#4086]
[SemVer Org site](https://semver.org/)

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 

```
$ git --version --build-options

git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver


Microsoft Windows [Version 10.0.19044.2130]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git version
```
 - What did you expect to occur after running these commands?

```
2.38.1+windows.1

example with rc:
2.23.0-rc0+windows.1

```

There are two problems:
1. If  I am running git version, I know I am asking for git's version.  Should not prefix 'git version '
2. The SemVer rule says build metadata is prefixed with a +.  So the windows.# info should be  <version info>+windows.#
   - 2.23.1+windows.2
   - 2.23.1-rc0+windows.125
   -  and so on

See [version comparisons](https://semvercompare.azurewebsites.net/?version=2.38.1%252Bwindows.1&version=2.23.0-rc0%252Bwindows.1&version=2.23.1%252Bwindows.1&version=2.23.0%252Bwindows.1&version=2.23.0-rc1%252Bwindows.1&version=2.23.0%252Bwindows.2) for a sample sort of versions.

 - What actually happened instead?

git version 2.38.1.windows.1

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by vbjay** [comment]
```c#

string output = @"2.23.0-rc0+windows.1";
output.Dump();
Semver.SemVersion v = Semver.SemVersion.Parse(output, Semver.SemVersionStyles.Any);
v.Dump();
v.ToString().Dump();

```

![image](https://user-images.githubusercontent.com/3629489/198900878-37b67cbb-dd3b-429d-965a-bf18230360e8.png)

**Comment by rimrul** [comment]
Git does not follow semver and neither does Git for Windows.

**Comment by vbjay** [comment]
Git's versioning like below most certainly follow semver

2.38-rc2
2.23.0-rc0
2.38.1

![image](https://user-images.githubusercontent.com/3629489/198946742-82fbc85c-1461-41ea-a2b4-32f46b61f28c.png)

Please show where git doesn't follow semver?

**Comment by rimrul** [comment]
Yes, Git uses a version number that looks like a semver vesion number, but they do not adhere to the semver rules on when and how to increment that version number.

**Comment by vbjay** [comment]
I see.  Thanks.

**Comment by rimrul** [comment]
> 2. The SemVer rule says build metadata is prefixed with a +.  So the windows.# info should be  <version info>+windows.#
>    - 2.23.1+windows.2
>    - 2.23.1-rc0+windows.125
>    -  and so on
> 

The semver rules also state

>Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. 

That alone disqualifies the `windows.#` part from being semver build metadata.
 It MUST NOT be ignored when determinng version precedence.

**Comment by vbjay** [comment]
Good point.
