### ISSUE TITLE
Can't force color output using color.ui=always

### ISSUE THREAD

**Issue by xim** [git-for-windows/git#4095]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
[Version 10.0.19044.2006]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

None, using PortableGit

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm trying to wrap the execution of git in some black magic that redirects stdout.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I'm executing `bash -c 'git -c color.ui=always log'` using fork/exec, with stdout redirected. The same happens when running from `git-bash.exe` though, as described below.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```sh
git init repo
cd repo
touch new
git -c color.ui=always status | cat
```

 - What did you expect to occur after running these commands?

Colors. In the specific example, the text `new` highlighted in red.

 - What actually happened instead?

It's all black and white.

**Comment by dscho** [comment]
Hmm. That's strange. In a locally-built Git, I do not get that behavior, but with v2.38.1 and even with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) I can reproduce (although I used `git -c color.ui=always log | less`).

**Comment by xim** [comment]
I notice that `git -c color.log=never log` also outputs colors. So the problem appears to be that the config isn't heeded.

I just tried installing instead of using the portable version, and there the config is heeded.

**Comment by xim** [comment]
Other configs like `core.pager` are respected normally.

**Comment by xim** [comment]
Certainly looks like something about how the portable git is set up causes the problem. What seems really weird to me that it affects config parsing, though. Setting the configs using `git config` or passing it with `git -c` seem to both fail to affect output.

**Comment by dscho** [comment]
I think I figured it out. [`color.ui`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-colorui) only determines the default of `color.diff`. If the latter is set, it overrides the former. And `color.diff` is set [in `/etc/gitconfig`](https://github.com/git-for-windows/git-sdk-64/blob/HEAD/etc/gitconfig#L5).

That is also the explanation why it works in a self-built `git.exe` because running it in place will not allow it to find `/etc/gitconfig`. As soon as you copy it to `/mingw64/bin`, it will expose the same behavior.

So the solution is _not_ to use `color.ui` but `color.diff` in that command-line incantation.
