### ISSUE TITLE
Fix `git gui` when the current directory's path contains non-ASCII characters

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#410]
Steps to reproduce:

```cmd
set HOMEDRIVE=C:
set HOMEPATH=\百川
set HOME=%HOMEDRIVE%%HOMEPATH%
if not exist %HOME% mkdir %HOME%
cd %HOME%
if not exist .git c:\Progra~1\Git\cmd\git init
echo Hello >world.txt
c:\Progra~1\Git\cmd\git-gui
```

**Comment by GOlaf71** [comment]
It also applies to Swedish characters like Å, Ä an Ö.
![git gui error swedish char in path](https://cloud.githubusercontent.com/assets/16164799/11607544/e85a60f8-9b4a-11e5-99d9-53aa27d83488.png)

**Comment by dscho** [comment]
@GOlaf71 sadly there are more pressing tickets I have to focus on. If you have time to work on a deeper analysis of this issue, please, by all means, give it a go. The alternative is to wait patiently until I resolved the other tickets and can come back to this one.

**Comment by kisstkondoros** [comment]
For me the issue could be solved by changing the proc
https://github.com/git-for-windows/git/blob/master/git-gui/git-gui.sh#L270
to
proc is_Cygwin {} {
	global _iscygwin
	set _iscygwin 0
	return $_iscygwin
}

For installed versions git-gui.tcl#L270 can be changed for a quick workaround.

change in https://github.com/git-for-windows/git/commit/88f4ba9b9547e9c341cc602883e97fda9960554b
is probably related.

Unfortunatelly I don't have time / environment setup / knowledge to fix it properly.

**Comment by dscho** [comment]
@kisstkondoros could you open a Pull Request at https://github.com/git-for-windows/git just with your Work-In-Progress (you could even use the online editor to paste in your local file)? It really does not need to be perfect, but could serve as an excellent start for a proper fix.

**Comment by kisstkondoros** [comment]
Hi, I've opened a Pull Request, I hope the description will be also useful :)
