### ISSUE TITLE
git svn rebase does not accept --revision option

### ISSUE THREAD

**Issue by light** [git-for-windows/git#4100]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

```
$ git --version --build-options
git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.19045.2130]
```

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: develop
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Disabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled
```

### Details

I'm using Git Bash.

Option `-r` or `--revision` is not recognized for `git svn rebase` :

```
$ git svn rebase -r198:
Unknown option: r
Unknown option: 1
Unknown option: 9
Unknown option: 8
Unknown option: :
```

```
$ git svn rebase --revision 198:
Unknown option: revision
```

**Comment by dscho** [comment]
Hmm. This does not strike me as a Windows-specific issue. It seems that `git svn rebase` does _not_ support `--revision` at all, contrary to the documentation: [The documentation of the `--revision` parameter](https://git-scm.com/docs/git-svn#Documentation/git-svn.txt---revisionltarggt) states that it is for use with the `fetch` command, and [the documentation of the `rebase` subcommand](https://git-scm.com/docs/git-svn#Documentation/git-svn.txt-emrebaseem) claims that it "accepts all options that git svn fetch and git rebase accept", which is untrue as you can easily verify by looking at the source code ([#1](https://github.com/git/git/blob/v2.38.1/git-svn.perl#L268-L276), [#2](https://github.com/git/git/blob/v2.38.1/git-svn.perl#L130C5-L145), [#3](https://github.com/git/git/blob/v2.38.1/git-svn.perl#L124-L129)).

There are lots of conversations on the interwebs about this, e.g. [this StackOverflow post](https://stackoverflow.com/questions/10220374/can-i-git-svn-rebase-to-a-certain-svn-revision-similar-to-svn-up-r). One of the answers suggests to use `git svn find-rev`, and that's probably your safest bet:

```console
$ git svn fetch -r 198

$ git rebase $(git svn find-rev r198)
```

In any case, if you require further assistance, I strongly recommend to take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently), as it really is not specific to Windows.
