### ISSUE TITLE
Installer forces choosing an editor (even on reinstall), and appears to overwrite existing settings 

### ISSUE THREAD

**Issue by LightCC** [git-for-windows/git#4101]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.2130]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad       
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false       
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Corporate environment with various security apps/infrastructure. Domain network with admin access on account.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

N/A

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Ran the install
```
 - What did you expect to occur after running these commands?

During an install, especially a reinstall, Git should not force me to choose an editor or have defaults that overwrite any existing settings, and certainly shouldn't be installing another app (if I choose an editor) - perhaps, at best, offer a link or something. I should be able to click through a window asking for setting up git config, especially on a reinstall, without having git download, install, or setup any particular config.

I already have instructions/scripts to setup git for my team/company for secondary items like this. The number of options multiplying in the git install, especially for reinstalls, is causing more problems for me rather than solving problems as picking the wrong thing or changing from what is already setup will create issues for the team members whos settings are changed.

Perhaps a wizard option should be present at the start for simple install (gives them the defaults?), reinstall (make no updates to anything), or advanced?

 - What actually happened instead?

During install, git asks a lot of options with defaults and recommendations that sometimes don't work for my team. One of the questions also asks which editor you'd like Git to use, but there is no option to move forward without choosing an editor - even on a reinstall, with config already setup, it forces you to choose one. Upon choosing VS Code, it says basically that it will install it if I continue, and install the user version. But it's already installed. This is very confusing and hard to document and guide my team through upgrading what to choose here. The default should be do nothing, especially on reinstall.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
The editor choice does not override any existing settings, it only configures the default editor in the system config (which is owned by Git for Windows). Any `core.editor` configured in user-wide ("global") or repository-wide ("local") configs override that system config setting.

Besides, the default setting ("Vim") specifically says that it will leave `core.editor` unset at the bottom of the description: 
![image](https://user-images.githubusercontent.com/127790/200932339-3d9ef1f4-e3fb-4ee3-9ef9-c95787fb3b5a.png)

**Comment by LightCC** [comment]
> The editor choice does not override any existing settings, it only configures the default editor in the system config (which is owned by Git for Windows). Any `core.editor` configured in user-wide ("global") or repository-wide ("local") configs override that system config setting.
> 
> Besides, the default setting ("Vim") specifically says that it will leave `core.editor` unset at the bottom of the description

I guess all that's fine, but it is still confusing. The first line says to pick the editor for git and there is a dropdown. You have to read all the detailed notes to get a different impression. There isn't any option or a checkbox to do nothing.

This is especially odd on a reinstall. Why am I answering any option that isn't new on a reinstall? I already have Git installed and setup. If it's not a new feature I really don't want to see it.  This really hampers reinstalls and makes me hesitate because I know it's going to take a bit to click through everything rather than just run an installer.  And the list is getting longer and longer.

In my case, it's more than just me, I have a bunch of users in my company that regularly message me with questions on this kind of stuff. Some option to just do a clean install or to detect it is a reinstall would add a lot of user value.

I hate having to tell my users on a reinstall to do 10 different things or look back at the instructions to decide exactly which settings to use, or to ignore 5 things in the dialogue boxes. For a brand new install for a brand new user, this flow isn't bad, but on a reinstall it almost forces me to rethink and double check every setting when I already have this all setup already.

**Comment by dscho** [comment]
I feel you, @LightCC. And it is really sad. And it does not have to be that way. Open Source is as good as its contributors make it.

**Comment by dscho** [comment]
I'll close this ticket, as the next logical step would be for the reporter to [modify the `Editor` page](https://github.com/git-for-windows/git/wiki/Making-an-installer#debuggingdeveloping-a-single-installer-wizard-page) and open a Pull Request.
