### ISSUE TITLE
Symlink issues with Git Bash during and after install

### ISSUE THREAD

**Issue by LightCC** [git-for-windows/git#4102]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.2130]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad       
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false       
CURL Option: WinSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Corporate environment with various security apps/infrastructure. Domain network with admin access on account.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

N/A for install, and Git Bash post-install.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Ran the installer for 64-bit Windows (non-portable). This is an update from 2.37.0 to 2.38.1.

Ran Git Bash after install without any commands.
```
 - What did you expect to occur after running these commands?

Successful install without error messages. Afterward, for Git Bash to run without errors.

 - What actually happened instead?

I got pop-up windows with an error multiple times during install. The same error - not blocking, the install completed successfully otherwise. I didn't capture the message but it was complaining about a bad return value with $0 at the end.

Git appeared to fully upgrade okay. However, when I ran Git Bash, it failed at the start with a bunch of the same pop-up window error messages (4 or more), but in the window it said it was trying to create symlinks.

Git is installed in Program Files so it would need admin to create files there - so on a hunch I ran Git Bash as an administrator and then got 4 symlink creation messages when it ran without any errors. Upon running Git Bash without administrator, it runs successfully now.

It appears that Git or Git Bash has a script to create several symlinks that are failing during install, and it continues to fail when running Git Bash after install with this version. I did choose the symlink support during install. If you run Git Bash (or possibly the installer?) as an administrator, it appears to fix the problem, and once the files (or symlinks, rather) are created, then the issue is resolved.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
> I didn't capture the message

Unfortunately, this information is quite crucial to act on this bug report.

> in the window it said it was trying to create symlinks

I can guess what the exact message was, but it is a good idea not to leave readers of bug reports guessing unless really necessary.

These symlinks are indeed supposed [to be created](https://github.com/git-for-windows/build-extra/blob/0b25881dffc7d1bd27d0138af8614b1dca969d6c/installer/install.iss#L2993-L2997) as part of the `post-install` phase of the Git installer.

**Comment by dscho** [comment]
Let's close this ticket until we receive the necessary information to address it.
