### ISSUE TITLE
Issues with cooperatation with Visual Studio Code

### ISSUE THREAD

**Issue by lychichem** [git-for-windows/git#411]
Bad, using Git for windows 2.5.1 and above x64 edition
![default](https://cloud.githubusercontent.com/assets/9316590/9975124/c50813ce-5ee2-11e5-9c70-008308aebe06.PNG)
Good, using Git for windows 2.5.0 x64 edition
![1](https://cloud.githubusercontent.com/assets/9316590/9975125/c5628f20-5ee2-11e5-9eec-09ec55cef048.PNG)
The output shows there is something wrong with SSH. I've set the git path in Visual studio Code to use git for windows x64, and VSC is the latest version. The testing machine is running Windows 10 x64 build 10532 and 10547

**Comment by dscho** [comment]
Can you fetch in Git Bash?

**Comment by lychichem** [comment]
Using git bash/git command/git GUI are all Okay. I don't know how VSC works. I think it should also use command line with just a GUI wrap.

**Comment by dscho** [comment]
Can you see what's in the `PATH`?

**Comment by lychichem** [comment]
In users environment variables, PATH is D:\Downloads\ffmpeg-20150916-git-cbbd906-win64-static\bin;C:\Program Files (x86)\Microsoft VS Code\bin; in system environment variables, PATH is C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd; in Visual Studio Code, I set git.path to be C:\\progra~1\\Git\\mingw64\\libexec\\git-core\\git.exe

**Comment by dscho** [comment]
> in Visual Studio Code, I set git.path to be C:\\progra~1\\Git\\mingw64\\libexec\\git-core\\git.exe

Do you do that manually? If so, you really want to set it to `C:\PROGRA~1\Git\cmd` instead.

**Comment by dscho** [comment]
> Do you do that manually?

I guess I am really asking for a description what you installed (exact download links, please), and how.

**Comment by lychichem** [comment]
Okay, I've made a wrong configuration to git.path in Visual Studio Code. Now by using PATH you given all works well. But I wonder why you don't change git exec dir path in About Git GUI panel.

**Comment by dscho** [comment]
> I wonder why you don't change git exec dir path in About Git GUI panel.

It is actually the correct path, as far as Git GUI is concerned. It is just not the *user*-facing location, that is `/cmd/git-gui.exe`.

Maybe you can fix the documentation, or raise some ticket, so that others do not fall into the same trap?

**Comment by lychichem** [comment]
Okay, I'll post something on Visual Studio Code forum.
