### ISSUE TITLE
Wrong permission for temp files created by "git mergetool"

### ISSUE THREAD

**Issue by olegkhr** [git-for-windows/git#4117]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

 git --version --build-options
git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.2274]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git mergetool -g CMakeLists.txt
```
 - What did you expect to occur after running these commands?

merge tool opens and shows 3-way merge

 - What actually happened instead?

merge tool opens but complains that cannot read temp files
CMakeLists_BASE_1674.txt
CMakeLists_LOCAL_1674.txt
CMakeLists_REMOTE_1674.txt

Windows permissions for these files look wrong (actual domain and user name replaced by [Domain] and [User])

icacls CMakeLists_REMOTE_1674.txt
CMakeLists_REMOTE_1674.txt NULL SID:(DENY)(Rc,S,REA,WEA,X,DC)
                           [Domain]\[User]:(DENY)(S,RD,WD,AD,REA,WEA,X,DC)
                           [Domain]\[User]:(D,Rc,WDAC,WO,RA,WA)
                           [Domain]\Domain Users:(Rc,S,RA)
                           NT AUTHORITY\Authenticated Users:(RX,W,DC)
                           NT AUTHORITY\SYSTEM:(RX,W,DC)
                           BUILTIN\Administrators:(RX,W,DC)
                           BUILTIN\Users:(RX)
                           Everyone:(Rc,S,RA)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by olegkhr** [comment]
mergetool creates 3 temp files and launches GUI, but these tempfiles are not accessible/readable.

I was able to "fix" this issue by re-cloning my repo.

**Comment by dscho** [comment]
@olegkhr The problem is still unclear to me.

Could you provide clear, complete steps how to reproduce the problem?

**Comment by olegkhr** [comment]
I don't have clear, complete steps to reproduce the issue. Any suggestion how I can do that?

**Comment by dscho** [comment]
> I don't have clear, complete steps to reproduce the issue. Any suggestion how I can do that?

http://stackoverflow.com/help/mcve has advice how to construct that.

**Comment by PhilipOakley** [comment]
> Any suggestion

In addition to the [MVCE](http://stackoverflow.com/help/mcve) advice, if you you can determine contributing issues, but don't know how to set them up, then include the commands that at least report those statuses, such as permissions, ownerships, etc. and then point out which particular factor you think is the one, even if you cannot set-up specific conditions. (e.g. set by someone else's policy..). 

Often these extra commands and their results give extra information that helps guide the debugging.
