### ISSUE TITLE
Git Bash doesn't pass arguments in the correct encoding

### ISSUE THREAD

**Issue by seishun** [git-for-windows/git#412]
Tested using the following Node.js program:

```js
console.log(process.argv)
```

It just dumps the arguments to the standard output.

In cmd:

```
C:\Users\Nikolai\Desktop>node test.js 殺す
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\Nikolai\\Desktop\\test.js',
  '殺す' ]
```

In MSYS2 (version 20150916):

```
$ node test.js 殺す
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\Nikolai\\Desktop\\test.js',
  '殺す' ]
```

In Git Bash:

```
$ node test.js 殺す
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\Nikolai\\Desktop\\test.js',
  'ærºa??' ]
```

It's a clean install of Git for Windows 2.5.3 on Windows 10 x64. I will gladly provide any other information that might be needed.

**Comment by dscho** [comment]
Well, to be honest, we do not even ship with `node`. So you will have to help support this use case.

So this is what you could do, for starters: compare the output of `env` in both MSys2 and Git Bash. If that does not reveal any major problems, you need to run

```cmd
set MSYSTEM=MINGW64
usr\bin\mintty.exe usr/bin/strace.exe -o log.txt usr/bin/bash.exe -l -I
```

from a `cmd` in the top-level directory of both MSys2 and Git Bash, and then compare the `log.txt` files.

> I will gladly provide any other information that might be needed.

You could have volunteered a bit more information already, e.g. which locale you run on, and whether the *Git for Windows SDK* exposes the same behavior as MSys2 or as Git Bash. Basically, err on the side of verbosity because having to ask for every piece of information can be a bit of a drag.

**Comment by seishun** [comment]
https://www.diffchecker.com/mnofzobw Git Bash is to the right.

>If that does not reveal any major problems, you need to run

When running the commands inside `c:\Program Files\Git`, it creates a console window that disappears immediately. There is no output whatsoever in `cmd` and no `log.txt` file is created. There is no such issue with MSYS2, but I'm not sure if a single `log.txt` file from MSYS2 would be useful.

>You could have volunteered a bit more information already, e.g. which locale you run on, and whether the Git for Windows SDK exposes the same behavior as MSys2 or as Git Bash.

The locale is "English (United States)".

`git-bash.exe`, `mingw32_shell.bat`, `mingw64_shell.bat`, `msys2_shell.bat` all have the same behavior as Git Bash. `git-cmd.exe` works correctly.

**Comment by seishun** [comment]
The reason was that I was running a non-Administrator command prompt, which doesn't have write access in `c:\Program Files\Git`. Also, I've discovered that the problem only occurs when running `node` and not when specifying the full path:

```
Nikolai@DESKTOP-24M7K77 MINGW64 ~/Users/Nikolai/Desktop
$ node test.js バカ
6

Nikolai@DESKTOP-24M7K77 MINGW64 ~/Users/Nikolai/Desktop
$ "/c/Program Files (x86)/nodejs/node.exe" test.js バカ
2
```

From a look at [log.txt](https://dl.dropboxusercontent.com/u/1725104/log.txt), it looks like Git Bash thinks バカ is a path and doesn't convert it properly.

**Comment by dscho** [comment]
> https://www.diffchecker.com/mnofzobw

Is that supposed to help me? I get this:

```
ERROR

The request could not be satisfied.

The origin closed the connection. 

Generated by cloudfront (CloudFront)
Request ID: TYiLrRsMMPEmt9m8Pgo8_SwGPJrca0fJOeYEplZFo1rwJu2Tr0Hm_g==
```
Given that you can eve drag & drop images into GitHub tickets' comments, providing an external link, and a non-working one at that, is not exactly helpful.

> When running the commands inside c:\Program Files\Git, it creates a console window that disappears immediately.

What are you talking about? I asked you to run `env`, and that does not create a console window. Unless you have a really funky way to run `env`, i.e. not inside Git Bash.

Or did you refer to the `mintty` call? Then you should quote *that* unless you want to confuse me. By now, things in this ticket are utterly unclear to me.

And to make things worse, my comment that `node` is not even supported by Git for Windows has been left completely unaddressed.

I fear I cannot help you.

**Comment by seishun** [comment]
>Given that you can eve drag & drop images into GitHub tickets' comments, providing an external link, and a non-working one at that, is not exactly helpful.

Would you have preferred an image with the diff? Anyway, `env` is irrelevant.

>And to make things worse, my comment that node is not even supported by Git for Windows has been left completely unaddressed.

As it turns out, the problem has nothing to do with Node.js, but rather with the `node` command, which was given special treatment in https://github.com/dscho/build-extra/commit/44ed99b47f564d0b89784ae8008627f5c3d06d69. It's winpty that passes arguments in the wrong encoding.

**Comment by dscho** [comment]
Ah! Now. *that* makes sense.

And even better: That hint should make it possible for me to reproduce. (Tomorrow... I am on a phone right now)

**Comment by dscho** [comment]
Sorry, forgot to update this ticket. I was able to reproduce the issue and am in the middle of debugging where things go awry.

**Comment by dscho** [comment]
@seishun please test by installing the [SDK](https://git-for-windows.github.io/#download-sdk) and installing [the package I uploaded for you to test](https://github.com/dscho/MSYS2-packages/releases/download/tmp-winpty-locale/winpty-git-1.1.1.160.0c1e064-1-x86_64.pkg.tar.xz) via `pacman -U winpty-git-1.1.1.160.0c1e064-1-x86_64.pkg.tar.xz`.

**Comment by seishun** [comment]
It receives arguments correctly now, but I've found that there also was (and still is) a problem with output encoding.

test.js:

```js
console.log('こんにちは世界')
```

```
Nikolai@DESKTOP-24M7K77 MINGW64 ~/Desktop
$ node.exe test.js
こんにちは世界

Nikolai@DESKTOP-24M7K77 MINGW64 ~/Desktop
$ node test.js
???????
```

The behavior is the same in SDK's Git Bash (with upgraded winpty) and plain Git Bash.

Another problem is that winpty doesn't allow piping to files:

```
Nikolai@DESKTOP-24M7K77 MINGW64 ~/Desktop
$ node.exe test.js > lol.txt

Nikolai@DESKTOP-24M7K77 MINGW64 ~/Desktop
$ node test.js > lol.txt
output is not a tty
```

Same with `python2.7`. Should these be submitted as separate issues?

**Comment by dscho** [comment]
Yep, I saw the output encoding issue, too. But I thought it was a CodePage issue (my code page is consistent with the country I live in). Any chance you can spend any time at all to work on this issue? I mean, it's not like I twiddled thumbs, I spent several days on this issue, even if it does not affect me, personally.

**Comment by dscho** [comment]
@seishun just to make it clear: I hoped that my substantial work on this issue would inspire you to invest as much time and energy.

**Comment by seishun** [comment]
To be honest, I'm not sure fixing winpty is worth the effort. Normally interactive consoles are launched when the command is run without arguments. Perhaps it would make more sense to simply not use winpty when there are arguments?

**Comment by dscho** [comment]
> Perhaps it would make more sense to simply not use winpty when there are arguments?

`python -i`.

> To be honest, I'm not sure fixing winpty is worth the effort

In contrast, I think it is worth the effort, in particular if you have problems with it. And you do. I don't. ;-)
