### ISSUE TITLE
env --igonore-environment command behaves differently from Linux (coreutils 8.22)

### ISSUE THREAD

**Issue by ermingol23** [git-for-windows/git#4126]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.2130]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Optioon: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

As far as I can tell none.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ type bash
bash is /usr/bin/bash
$
$ # Command fails unless explict path to executable file is given
$ env --ignore-environment -v bash
cleaning env
executing bash
   arg[0]= 'bash'
env: 'bash': No such file or directory
$ 
$ # Command works when explicit path is given.
$ env --ignore-environment -v /usr/bin/bash
cleaning env
executing /usr/bin/bash
   arg[0]= '/usr/bin/bash'
$
```
 - What did you expect to occur after running these commands?

A new Bash shell is started by env command as it does in Linux (at least in CentOS 7.9 with Linux coreutils 8.22). In Windows Git Bash with coreutils 8.32 I have to give the explcit path to bash. This causes problems when scripts are shared between Linux and Windows environments.

 - What actually happened instead?

The env command failed as shown above

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Does this also happen with plain [MSYS2](https://msys2.org)?

**Comment by ermingol23** [comment]
Honestly I do not know that as I am not allowed to install anything in the environment we are running Git Bash in. And I do not have any personal Windows machine at home where I could installing MSYS2 and try it out. :(

**Comment by dscho** [comment]
I just tested this in MSYS2:

```console
$ env --ignore-environment -v bash
cleaning environ
executing: bash
   arg[0]= ‘bash’
env: ‘bash’: No such file or directory
```

Seems to work. This is running with tht MSYS2 version:

```console
$ uname -a
MINGW64_NT-10.0-22621 johasc-thinkpad 3.3.6-341.x86_64 2022-10-24 08:25 UTC x86_64 Msys
```

So now off to Git Bash, and lo and behold:

```console
$ env --ignore-environment -v bash
cleaning environ
executing: bash
   arg[0]= ‘bash’
env: ‘bash’: No such file or directory
```

Of course, this is with a much, much newer Git version than you reported:

```console
$ git version
git version 2.38.1.windows.1
```

The report talks about "git version 2.31.1.windows.1", which makes me shudder because [our FAQ](https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version) talks about 5 (!) really important security fix releases since then.

In any case, this does not seem to be a bug that is present in the current Git for Windows version.

**Comment by rimrul** [comment]
[env calls `execvp`](https://git.savannah.gnu.org/cgit/coreutils.git/tree/src/env.c#n895) with all environment variables unset. [Glibc `execvp` falls back to `/bin:/usr/bin`](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/confstr.h;h=15859c3b2759878e636dba5e2744a2601648db98;hb=59aa41585f668b70b86a8e2617057da08f3291cc) if `PATH` is unset, but that is implementation defined behaviour and Cygwin/Msys2 `execvp` doesn't have this fallback.
