### ISSUE TITLE
Git-2.5.3-64-bit.exe Git Bash MINGW64 Terminal Console Backspace and Up Arrow keys not working as expected

### ISSUE THREAD

**Issue by cwpjr** [git-for-windows/git#413]
My system is Windows 7 Pro. I installed Git-2.5.3-64-bit.exe. I have uninstalled and re installed 5 times in case it was an install error. No errors reported.

When I launch Git Bash from the start menu the MINGW64 Terminal Console Backspace and Up Arrow keys not working as expected.

I had an install where the backspace key would erase characters to the left, and the up arrow would replicate the history of individual command lines.

In this install the backspace emits what looks like a space, and (I saw this tip/analysis somewhere) if I then type Control-l (lower case L) the preceding character is erased and the remaining string is replicated in a new prompted line. Example of backspace then control-l of the t in --list in the initial prompt:
cwpjr@cwpjr-Dellm4800 MINGW64 ~
$ git config --list

cwpjr@cwpjr-Dellm4800 MINGW64 ~
$ git config --lis
Yet the command line with --lis executes properly.

The up arrow function of command line recall now concatenates command line history on the same line, instead of bringing up separate lines of command history. Example of four up arrows:
cwpjr@cwpjr-Dellm4800 MINGW64 ~
$ git config --list$ echo $TERM       $ git config --list
The first reproduced the git config --lis, the second added the t to the end of list.

echo $TERM returns msys (whereas I thought it would be msys2).

**Comment by dscho** [comment]
I need more details to understand the issue. What command do you start? Is this in a minty or in a ConHost window? How come `$TERM` returns `msys`, did you set that yourself (normally, inside mintty, it returns `xterm` or `xterm+256color`, in a ConHost it returns `cygwin`)

**Comment by cwpjr** [comment]
Hi Johannes,

Please let me know if you need more!

I updated the issue I posted and attached a screen shot:

---

My system is Windows 7 Pro. I installed Git-2.5.3-64-bit.exe. I have
uninstalled and re installed 5 times in case it was an install error. No
errors reported.

When I launch Git Bash from the start menu the MINGW64 Terminal Console
Backspace and Up Arrow keys not working as expected.

I had an install where the backspace key would erase characters to the
left, and the up arrow would replicate the history of individual command
lines.

In this install the backspace emits what looks like a space, and (I saw
this tip/analysis somewhere) if I then type Control-l (lower case L) the
preceding character is erased and the remaining string is replicated in a
new prompted line. Example of backspace then control-l of the t in --list
in the initial prompt:
cwpjr@cwpjr-Dellm4800 MINGW64 ~
$ git config --list

cwpjr@cwpjr-Dellm4800 MINGW64 ~
$ git config --lis
Yet the command line with --lis executes properly.

The up arrow function of command line recall now concatenates command line
history on the same line, instead of bringing up separate lines of command
history. Example of four up arrows:
cwpjr@cwpjr-Dellm4800 MINGW64 ~
$ git config --list$ echo $TERM $ git config --list
The first reproduced the git config --lis, the second added the t to the
end of list.

echo $TERM returns msys (whereas I thought it would be msys2).
---

**Comment by cwpjr** [comment]
<img width="960" alt="screenshot 2015-09-20 13 35 35" src="https://cloud.githubusercontent.com/assets/5290693/9982312/c7f0a08c-5f9c-11e5-80a5-08f786e9afeb.png">

**Comment by dscho** [comment]
Please note that it makes it hard for me to follow changes if existing comments or reports change all of a sudden 😀

**Comment by cwpjr** [comment]
Noted. When I receive an email from you should I come here and reply or reply to the email and not here?

**Comment by dscho** [comment]
Both ways of replying end up both here and inbox IIUC.

**Comment by cwpjr** [comment]
So I'll do one !AND the other!

**Comment by dscho** [comment]
> echo $TERM returns msys (whereas I thought it would be msys2).

It now looks like I am a moron asking for the `TERM` value (because it is no longer obvious that this information was missing at the time I was asking)...

In any case, that `TERM`'s value should be `xterm+256color` if you started Git Bash in a mintty, and `cygwin` if started in a regular Windows console. That depends on your choices when you installed Git for Windows.

`msys` was the value in Git for Windows 1.x. Mixed installation?

**Comment by cwpjr** [comment]
No prob. I am getting better at expressing myself.

Mixed installation came to mind but not as I'm the culprit. I started with
a github download a few months ago (vs Git) and after a while concluded I
wanted local svc software to start with. Unless github installs the older
versions you point out.

Anywho so then I installed Git-2.5.3-64-bit.exe.

I thought maybe the initial GitHub install may have setup defaults that
components of Git would acknowledge so I un installed Github. Problem is
I'm not sure if I un installed it and that's when the issue started, or I
did this after the re installs.

And when I began un/re installing I thought it was curious that my "git
config"s were persisting thru uninstall all options. Tracking down what and
where the .configthis&that files in windows issue there.

**Comment by cwpjr** [comment]
And I may have pulled a slight of hand adding info by modifying the
original message.... so thanks for the pass. If twas the case it won't
happen agin!

**Comment by dscho** [comment]
> I am getting better at expressing myself.

So do I!

> When I launch Git Bash from the start menu the MINGW64 Terminal Console Backspace and Up Arrow keys not working as expected.

I guess if you manually fix `TERM=cygwin`, it should be fixed.

However, there is something else going on, something very funky. We have a *specific* workaround for the `TERM=msys` setting: it is [automagically converted into a `TERM=cygwin` setting](https://github.com/git-for-windows/msys2-runtime/commit/c2459b8019e7a4c6ad2e0c31a9fde52a5ca05d11).

And indeed, if I start a `cmd`, `set TERM=msys`, then start `"C:\Program Files\Git\bin\bash.exe" -l -i`, an `echo $TERM` yields `cygwin`.

Did you set `TERM` somewhere in your `$HOME/.profile` or some such?

**Comment by cwpjr** [comment]
Look like I did set TERM, if this is not standard to the install:
$ grep msys .*
grep: .: Is a directory
grep: ..: Is a directory
grep: .android: Is a directory
grep: .atom: Is a directory
.bashrc:export TERM=msys

So after removing that (and restarting):




*cwpjr@cwpjr-Dellm4800 MINGW64 ~$ echo $TERMxterm*


*And backspace and the up arrow key work!*


*So I must apologize. As far as I'm concerned this issue is closed.*


*And "git help commit" launches notepad.I know this is bad form but I think
I got screwed up trying to follow search results on setting notepad++ as
the comment editor and trying to set firefox to display the *

*"git help commit" html content (which isn't readable in notepad - or
notepad++).*


*At least I know what not to do! Thanks!!!*

**Comment by dscho** [comment]
> As far as I'm concerned this issue is closed.

Next time, feel free to hit the "Close" button yourself ;-)
