### ISSUE TITLE
Adding 'script' command (from util-linux) to git-bash.exe

### ISSUE THREAD

**Issue by bartosz-jarmuz** [git-for-windows/git#4132]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64bit
```
$ git --version --build-options
git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win1064bit
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19044.2130]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

Hello,

I would like to install a script (https://man7.org/linux/man-pages/man1/script.1.html) command in my git-bash terminal.
This is in order for me to create an automatic log of all the commands I enter into git-bash
Unfortunately, trying to run it I get the following error:

bash: script: command not found

I have installed latest cygwin and tried dropping the script.exe into c:\Program Files\Git\usr\bin\ folder, however when I do that, I get the following error:

C:/Program Files/Git/usr/bin/script.exe: error while loading shared libraries: cygintl-8.dll: cannot open shared object file: No such file or directory

If I continue dropping the required dlls, I end up with a following error:

C:/Program Files/Git/usr/bin/script.exe: error while loading shared libraries: ? : cannot open shared object file: No such file or directory

Is it possible to add 'script' command to git-bash?

Kind regards,
Bartosz

**Comment by dscho** [comment]
The purpose of [Git for Windows](https://git-for-windows.github.io/) is really to bring *Git* to Windows.

While that implies that we have to ship quite a few Unix-like tools, it does not mean that we will include such tools unless they are needed for Git's own operations, or at least for historical reasons (needs of active contributors are sometimes a factor in deciding whether to include a tool or not).

Having said that, what you really are looking for is [MSYS2](https://msys2.github.io/). Git for Windows leverages MSYS2 and ships with a subset of its files. MSYS2 even sports a package management system called "pacman" to install more tools (including Git...), so why don't you give it a whirl?
