### ISSUE TITLE
GPG provided by git uses wrong character set

### ISSUE THREAD

**Issue by bjornbouetsmith** [git-for-windows/git#4137]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64bit
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19044.2251]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

English windows, but Danish international settings/keyboard

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

```
gpg.exe --full-generate-key
```
 - What did you expect to occur after running these commands?

I create a key using the above command and enter "Bjørn Bouet Smith" as the name.

I then expect GPG to actually detect the correct characteset (UTF-8) - but instead it seems like it is either hardcoded to use ISO-8859-1 or detects that

 - What actually happened instead?

So when pinentry shows the name of the key my name show up all garbled because windows/visual studio etc expects utf-8

~~~
pub   rsa4096 2022-11-25 [SC]
      E6860DB5B0F8271698EC1412834E186576CB4AB0
uid           [ultimate] BjÃ¸rn Bouet Smith <me@r00t.dk>
sub   rsa4096 2022-11-25 [E]
~~~

I have tried the exact same commands with a official gpg installer and the provided binary from that (same version) - and there it behaves as expected - and uses utf-8 as the character set. And then it shows up correctly in pinentry.

I know this is not a git issue per say, but the gpg.exe is provided by the same package

**Comment by dscho** [comment]
> `gpg.exe --full-generate-key`

Hmm. You are calling a non-Git command here, and not from a Git Bash. That's definitely off the trodden path.

Does it work if you call it in a Git Bash? And in a Git CMD? Does it work in PowerShell after setting `$env:LC_CTYPE = "C.UTF-8"`?

**Comment by bjornbouetsmith** [comment]
> > `gpg.exe --full-generate-key`
> 
> Hmm. You are calling a non-Git command here, and not from a Git Bash. That's definitely off the trodden path.
> 
> Does it work if you call it in a Git Bash? And in a Git CMD? Does it work in PowerShell after setting `$env:LC_CTYPE = "C.UTF-8"`?

Git CMD - same result
Git Bash - I get this:
~~~
pub   rsa4096 2022-11-25 [SC]
      2B6B767E943D5F075952F06D15943FE7FC9E615A
uid           [ultimate] Bj▒rn Bouet Smith <test2@me.dk>
sub   rsa4096 2022-11-25 [E]
~~~

In powershell after having set `$env:LC_CTYPE = "C.UTF-8"' the Git Bash+"powershell" version now show correct, i.e. with 'ø' and the ISO-8859-1 versions show up incorrectly.

So I guess the conclusion is that.

Git-CMD uses wrong charset, Git-Bash uses correct charset and Powershell after having set environment variable uses correct charset.

The only reason I made this bug report here was because the gpg.exe is provided in the git installer, and because the gpg.exe provided by the official installer does not have this issue.

I started using gpg signing in git recently and got annoyed that pinentry showed my name garbled - and then I started investigating and came to the conclusion that the gpg.exe provided with git behaves differently than the official versions - even with same version of the software - and I assume its compiled as part of the git compilation or something - meaning its not the "official" gpg, but a home built one specific for git.

**Comment by bjornbouetsmith** [comment]
Also I started out at gpg: https://dev.gnupg.org/T6289 - but we came to the conclusion that the official version works.

**Comment by bjornbouetsmith** [comment]
One of the people at GPG just commented this:

Looking at the hexdump of the user ID in the exported (and dearmored) public key this looks like a classic double-encoding problem, i.e. UTF-8 encoded UTF-8:
```
42 6A C3 83 C2 B8 72 6E
      ^^^^^^^^^^^
```

Correctly encoded "Bjørn" looks like this:
```
42 6A C3 B8 72 6E
      ^^^^^
```

**Comment by dscho** [comment]
The most likely reason for the discrepancy between the official GPG version and the one shipped in Git for Windows is that the latter uses the MSYS2 runtime, which is a POSIX emulation layer that sometimes bumps against incompatibilities between the Windows and the POSIX world, in this instance encodings.

> after having set `$env:LC_CTYPE = "C.UTF-8"' the Git Bash+"powershell" version now show correct

I am a bit confused. If you open a fresh Git Bash, is `LC_CTYPE` _not_ set to `C.UTF-8`, `en_US.UTF-8` or similar? [It should be](https://github.com/git-for-windows/git-sdk-64/blob/ae64c2daebdb1790717898c936c169076edcd318/etc/profile.d/lang.sh#L19).

**Comment by bjornbouetsmith** [comment]
> I am a bit confused. If you open a fresh Git Bash, is `LC_CTYPE` _not_ set to `C.UTF-8`, `en_US.UTF-8` or similar? [It should be](https://github.com/git-for-windows/git-sdk-64/blob/ae64c2daebdb1790717898c936c169076edcd318/etc/profile.d/lang.sh#L19).

On my machine its set to in git bash
~~~bash
LC_CTYPE=en_US.UTF-8
~~~

In powershell its not set at all, so I suspect it defaults to whatever is default inside the program. That default might be the issue, since I doubt anyone ever sets LC_TYPE in a windows shell or powershell - its a *nix thing to set LC_TYPE

**Comment by dscho** [comment]
> On my machine in git bash its set to:
> 
> ```shell
> LC_CTYPE=en_US.UTF-8
> ```

According to one of your earlier comments, `gpg` should work correctly in Git Bash, then?

> In powershell its not set at all, so I suspect it defaults to whatever is default inside the program.

Probably.

Do note, though, that it is highly discouraged to install Git for Windows in a way where `gpg.exe` would even be in the `$env:PATH` of PowerShell. You are reporting one of the many issues that led to this discouragement.

**Comment by bjornbouetsmith** [comment]
> Do note, though, that it is highly discouraged to install Git for Windows in a way where `gpg.exe` would even be in the `$env:PATH` of PowerShell. You are reporting one of the many issues that led to this discouragement.

I accept that, but why distribute a "windows" binary - if you can only run it via a "special" shell? - then you might as well just only distributed git.exe and the rest as linux binaries to be run via WSL.

Its pretty "weird" that a windows binary only works if you run it in a special shell - and not any of the other shells on that platform. Similar to if you distributed a linux binary and it only worked properly if you ran it in `tcsh`.

What I did with installation is whatever came with visual studio, which I suspect puts git.exe in the path and nothing else. But then I started investigating signing my commits, so I could get the nice `verified` tag in my commits on github. And since the git installation distributed a windows gpg.exe naturally I started the default shell on windows these days: `powershell` and cd'ed to the location of the gpg.exe and created a key.

I fully agree that what I did is not something most people do, most people do not even use gpg, and certainly not together with git.

But it seems fair that any binary you distribute as a windows binary should work in any shell on windows. The alternative is to only distribute the binaries that you care about, i.e. git.exe and leave the rest for download somewhere else - I mean why distribute gpg.exe if you do not intend for it to be run - or if you only want it to be run via git bash - you can modify the code to stop if its not run from a git bash.

**Comment by PhilipOakley** [comment]
> it seems fair that any binary you distribute as a windows binary should work in any shell on windows.

I think your are bumping into the realities of Git being, first and foremost, a Linux application.  Bringing Git to Windows is a non trivial task, more contributors are always welcome.

As Dscho said,

> "likely reason for the discrepancy between the official GPG version and the one shipped in Git for Windows is that the latter uses the MSYS2 runtime, which is a POSIX emulation layer that sometimes bumps against incompatibilities between the Windows and the POSIX world,"

**Comment by bjornbouetsmith** [comment]
> We ship a GPG version that works with Git and integrates well with Git for Windows' development process. We "hide" it by putting it outside of the regular PATH. We already put in enough effort to make it work.

I am not sure you can call it "Integrates well with Git for Windows" - it most certainly does not.

I think we have a very different way of looking at stuff that works well.

The fact is that the gpg.exe that is distributed together with a "Git for windows" - only works in a single shell - and not one of the default shells on windows. 

If you are unwilling to fix it, so be it, but lets not pretend it "works and integrates well".
