### ISSUE TITLE
open git and show /usr/bin/bash --login -i

### ISSUE THREAD

**Issue by leto-hub** [git-for-windows/git#4138]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

```

![661ebd3914377da602086e2af22b58a](https://user-images.githubusercontent.com/71166057/204126082-69e73a3f-4f6a-4801-bc5c-471210a98980.jpg)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

can't recognize this command


```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Details
when I downloaded git and open git bash, its interface shaped like this:

![0c1c253e67a76a1dc44a806d2ff922d](https://user-images.githubusercontent.com/71166057/204126089-60afa8be-a793-4819-aa72-9b4cbb6819a5.jpg)

I don't know why it keeps stuck and show "--login -i".

**Comment by dscho** [comment]
This looks like you may have some unintentional `~/.bash_profile` or similar. The guidance in [this wiki page](https://github.com/git-for-windows/git/wiki/Diagnosing-performance-issues#trace-executions-in-the-bash-startup) should help to diagnose this further.

**Comment by dscho** [comment]
I will assume that the guidance helped.
