### ISSUE TITLE
Git difftool not using configured diff.tool  - always using default diff tool 

### ISSUE THREAD

**Issue by phinney** [git-for-windows/git#4143]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 - 64 bit

```
$ git --version --build-options

git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 11

$ cmd.exe /c ver
Microsoft Windows [Version 10.0.22621.819]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
C:\Users\tom>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** problem occurs for both CMD & Bash shell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
  
  git difftool

 ### git debug report
Thank you for filling out a Git bug report!
Please answer the following questions to help us understand your issue.

What did you do before the bug happened? (Steps to reproduce your issue)

configured .gitignore file for using winmerge for both difftool and mergetool.
Here's what my .gitignote file contains:

[user]
	name = Tom Rutchik
	email = tom@phinneyridge.com
[filter "lfs"]
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
[diff]
	tool = winmerge
[difftool]
      prompt = true
[difftool "winmerge"]
      cmd = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$LOCAL\" \"$REMOTE\"
[merge]
      tool = winmerge
[mergetool "winmerge"]
	cmd = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$MERGED\"
[gui]
	recentrepo = C:/Temp/MyApplication
	recentrepo = C:/PR/Dev/Android/Coreq
[credential "https://prdev.corp.phinneyridge.com"]
	provider = generic
[init]
	defaultBranch = main

What did you expect to happen? (Expected behavior)

I would expect that "git difftool" would use the winmerge tool for displaying file differences and that "git mergetool" would use the winmerger tool for merging file differences

What happened instead? (Actual behavior)

The "git mergetool" command work as expected. The "git difftool" however use the default diff tool.  Here's what "git difftool displayed (please not that I have GIT_TRACE set to true):

C:\Temp\user1\core>git difftool
`13:04:53.937613 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:04:53.939658 git.c:460               trace: built-in: git difftool
13:04:53.939658 run-command.c:655       trace: run_command: GIT_EXTERNAL_DIFF=git-difftool--helper GIT_PAGER='' git diff
13:04:53.949743 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:04:53.949743 git.c:460               trace: built-in: git diff
diff --cc CoreInterfaces/src/main/java/com/phinneyridge/core/Core.java
index a0a58b9,73cd1d1..0000000
--- a/CoreInterfaces/src/main/java/com/phinneyridge/core/Core.java
+++ b/CoreInterfaces/src/main/java/com/phinneyridge/core/Core.java
@@@ -6,8 -6,14 +6,18 @@@ import com.phinneyridge.core.communicat
  import com.phinneyridge.core.crypto.DataEncryptionInterface;
  import com.phinneyridge.util.LogInterface;
  import com.phinneyridge.dummy   // this is a test
 + <<<<<<< HEAD
 + # djdkfjlas
 + =======
  import com.phinneyridge.dummy2; // this is a test
 ++<<<<<<< HEAD
  +
 ++=======
 + #xyz
 + >>>>>>> c5084de9b3a6f8d616f53d641f272ed2ce30754b
 + dsfdfd
 + rr,n,n,
 ++>>>>>>> a7b9b22916d43bfbc7e6ac12f00c9312cafd22fa

  import java.net.URL;
  import java.util.concurrent.ExecutorService;

C:\Temp\user1\core>
`

What's different between what you expected and what actually happened?

I expected that git would have use the winmerge tool to display the file differences. 

Anything else you want to add:

I have winmerge version 2.16.24.0  x86 installed 
WinMergeU.exe is installed in directory: C:\Program Files (x86)\WinMerge

Here what "git difftool --tool-help" displays: 

C:\Temp\user2\core>git difftool --tool-help
'git difftool --tool=<tool>' may be set to one of the following:
                p4merge          Use HelixCore P4Merge (requires a graphical session)
                vimdiff          Use Vim
                winmerge         Use WinMerge (requires a graphical session)

        user-defined:
                winmerge.cmd "C:\Program Files (x86)\WinMerge\WinMergeU.exe" "$LOCAL" "$REMOTE"
                winmerge.cmd "C:\Program Files (x86)\WinMerge\WinMergeU.exe" "$MERGED"

The following tools are valid, but not currently available:
                araxis           Use Araxis Merge (requires a graphical session)
                bc               Use Beyond Compare (requires a graphical session)
                bc3              Use Beyond Compare (requires a graphical session)
                bc4              Use Beyond Compare (requires a graphical session)
                codecompare      Use Code Compare (requires a graphical session)
                deltawalker      Use DeltaWalker (requires a graphical session)
                diffmerge        Use DiffMerge (requires a graphical session)
                diffuse          Use Diffuse (requires a graphical session)
                ecmerge          Use ECMerge (requires a graphical session)
                emerge           Use Emacs' Emerge
                examdiff         Use ExamDiff Pro (requires a graphical session)
                guiffy           Use Guiffy's Diff Tool (requires a graphical session)
                gvimdiff         Use gVim (requires a graphical session)
                kdiff3           Use KDiff3 (requires a graphical session)
                kompare          Use Kompare (requires a graphical session)
                meld             Use Meld (requires a graphical session)
                nvimdiff         Use Neovim
                opendiff         Use FileMerge (requires a graphical session)
                smerge           Use Sublime Merge (requires a graphical session)
                tkdiff           Use TkDiff (requires a graphical session)
                xxdiff           Use xxdiff (requires a graphical session)

Some of the tools listed above only work in a windowed
environment. If run in a terminal-only session, they will fail.

C:\Temp\user2\core>

Here are other things I've tried:

I tried to see if I could get it to work with p4merge (Rev. P4Merger/NTX4/20022.3/230885).  - same results
I also tried various other .gitconfig configuration:

alt config 1:

[user]
	name = Tom Rutchik
	email = tom@phinneyridge.com
[filter "lfs"]
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
[diff]
	tool = winmerge
[difftool]
      prompt = true
[merge]
      tool = winmerge
[mergetool "winmerge"]
	cmd = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$MERGED\"
[gui]
	recentrepo = C:/Temp/MyApplication
	recentrepo = C:/PR/Dev/Android/Coreq
[credential "https://prdev.corp.phinneyridge.com"]
	provider = generic
[init]
	defaultBranch = main

alt config 2:

[user]
	name = Tom Rutchik
	email = tom@phinneyridge.com
[filter "lfs"]
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
[diff]
	tool = winmerge
[difftool]
      prompt = true
[difftool "winmerge"]
      path = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\"
[merge]
      tool = winmerge
[mergetool "winmerge"]
	cmd = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$MERGED\"
[gui]
	recentrepo = C:/Temp/MyApplication
	recentrepo = C:/PR/Dev/Android/Coreq
[credential "https://prdev.corp.phinneyridge.com"]
	provider = generic
[init]
	defaultBranch = main

alt config 3:

[user]
	name = Tom Rutchik
	email = tom@phinneyridge.com
[filter "lfs"]
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
[diff]
	tool = winmerge
[difftool]
      prompt = true
[difftool "winmerge"]
      external = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$LOCAL\" \"$REMOTE\"
[merge]
      tool = winmerge
[mergetool "winmerge"]
	cmd = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$MERGED\"
[gui]
	recentrepo = C:/Temp/MyApplication
	recentrepo = C:/PR/Dev/Android/Coreq
[credential "https://prdev.corp.phinneyridge.com"]
	provider = generic
[init]
	defaultBranch = main

They all had the same issue.

I tried the "git difftool" command for all the configurations using both the Windows Terminal Version: 1.15.2875.0 and GitBash shell that was installed with Git for Windows (GNU bash, version 5.1.16(1)-release (x86_64-pc-msys))

By the way, I had the path for both winmerge and p4merge on my path when I executed the commands, so I also tried a simple cmd specification

      cmd = WinMergeU.exe \"$LOCAL\" \"$REMOTE\"
Though the issue might be related to spaces in the name, but that also produced the same result.

I think the trace line:

13:04:53.939658 run-command.c:655       trace: run_command: GIT_EXTERNAL_DIFF=git-difftool--helper GIT_PAGER='' git diff

might be a clue as to where the issue may be happening.  I'm not sure what git-difftool-helper is doing. Not sure if this is meaningful but here's something I tried:

C:\Temp\user2\core>git difftool--helper

C:\Temp\user2\core>set GIT_TRACE=true

C:\Temp\user2\core>git difftool--helper
13:46:10.283530 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:46:10.285554 git.c:750               trace: exec: git-difftool--helper
13:46:10.285554 run-command.c:655       trace: run_command: git-difftool--helper
13:46:10.329938 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:46:10.397688 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:46:10.398685 git.c:460               trace: built-in: git config diff.tool
13:46:10.457460 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:46:10.458483 git.c:460               trace: built-in: git config difftool.winmerge.cmd

C:\Temp\user2\core>

It seems to imply that the helper did look at the config variable "difftool.winmerge.cmd", but it doesn't look like it returned a result. If my speculation is right, that would be consistent with the explanation of why the default diff tool was used.

Here's what I get when I look at that config variable:

C:\Temp\user2\core>
C:\Temp\user2\core>git config difftool.winmerge.cmd
13:53:20.555390 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:53:20.557384 git.c:460               trace: built-in: git config difftool.winmerge.cmd
WinMergeU.exe "$LOCAL" "$REMOTE"

By the way, this is also consistent with the explanation of why "git mergetool" workd and "git difftool" doesn't.  When I looked at the git trace output for "git mergetool" it doesn't use the git-difftool-help script (nor the merge equivalant of that).

I found the git-difftool--helper script in directory: /c/Program Files/Git/mingw64/libexec/git-core.  I set current working directory to that directory.  That directory also contains
the script "git-mergetool--lib".  So I tried the following from a git-bash shell:

$ sh git-difftool--helper
git-difftool--helper: line 9: .: git-mergetool--lib: file not found

Line 9 of the "git-difftool--helper" is a line that the "git-mergetool--lib" file was being sourced. That script contains functions that are used to setup various merge and diff function and if its not sourced that would certainly explan things.  My speculation is that error I see above is likely causing the problem.  I don't understand how the file can't be found especially since its contained in the current working directory. I certainly could be wrong since I don't do alot of work with /bin/sh scripts.

I'll also point out that from my internet research of this problem, I don't seem to be the only one experiencing this issue. I'm of the opinion that 
difftool worked at one time, but got broken several release ago. I can say that I had the same problem when I was using a git 2.37 version.

Please review the rest of the bug report below.
You can delete any lines you don't wish to share.

[System Info]
git version:
git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
uname: Windows 10.0 22621 
compiler info: gnuc: 12.2
libc info: no libc information available
$SHELL (typically, interactive shell): <unset>

[Enabled Hooks]

**Comment by dscho** [comment]
> Here's what my .gitignote file contains:

This should probably go into the `.git/config` file, not into the `.gitignore` file. You can find out whether the configuration is correct by calling `git config diff.tool` (should print out `winmerge`) and `git config difftool.winmerge.cmd` (should print that command-line).

**Comment by phinney** [comment]
I'm sorry, I meant the .gitconfig file.  This is the global configuration file.  And yes, git diff.tool does print out winmerge.

I added "C:\Program Files\Git\mingw64\libexec\git-core" to my path to get around the file not found issue I mentioned.  I'm not sure if this is a problem if I had done a "git difftool" command.  I was just trying to test the "git-difftool--helper" script as standalone, and maybe the envrionment isn't set up correctly in that situation. 

My speculation is that somewhere in calling that helper command is what's causing the configured difftool not to be used.  I'm trying to debug that code and will post what I find.  What I think is happening at this time is that Git is using the key for diff.tool and not it's value "winmerge" so it's not finding the "difftool.winmerge" configuration and that's why it's choosing the default diff tool instead.  I've seen some evidence that suggests that's what's happening, but at this time I'm still trying to verify that and will post more if I end up confirming that.

**Comment by dscho** [comment]
> I added "C:\Program Files\Git\mingw64\libexec\git-core" to my path

That should not be necessary if you are calling `git.exe` in one of the supported ways.

> git diff.tool does print out winmerge.

I doubt that `git diff.tool` really prints out anything except

```
git: 'diff.tool' is not a git command. See 'git --help'.

The most similar command is
        difftool
```

> What I think is happening at this time is that Git is using the key for diff.tool and not it's value "winmerge"

You should be able to confirm that theory by running `git config --show-scope --get-all diff.tool`.

**Comment by phinney** [comment]
The problem I was having just completely went away.  In other words, "git difftool" is now working as expected.  I'm able to configure "winmerge" as the external diff tool.  The problem I was having was that I would always get the same default diff tool that you would see using "git diff".  I have no explanation as to what I did to make the problem go away.  Now that it's working, I will say that if I enable GIT_TRACE, the TRACE output is different than when the problem was occurring.  They both began the same way with:

C:\Temp\user1\core>git difftool
16:39:02.327014 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
16:39:02.329012 git.c:460               trace: built-in: git difftool
16:39:02.329012 run-command.c:655       trace: run_command: GIT_EXTERNAL_DIFF=git-difftool--helper GIT_PAGER='' git diff16:39:02.338744 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:02.338744 git.c:460               trace: built-in: git diff

When it wasn't working, that's all the trace output I got.  Now that it's working I get the following additional trace output:

16:39:02.359689 run-command.c:655       trace: run_command: GIT_DIFF_PATH_COUNTER=1 GIT_DIFF_PATH_TOTAL=1 git-difftool--helper CoreInterfaces/src/main/java/com/phinneyridge/core/Core.java 'C:\Users\tom\AppData\Local\Temp/git-blob-a24836/Core.java' a9ebf8ca293660baba6ea6ffc5604cd1c96fdb4f 100644 CoreInterfaces/src/main/java/com/phinneyridge/core/Core.java 0000000000000000000000000000000000000000 100644
16:39:02.607373 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:02.656894 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:02.658894 git.c:460               trace: built-in: git config diff.tool
16:39:02.692907 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:02.695358 git.c:460               trace: built-in: git config difftool.winmerge.cmd
16:39:02.847941 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:02.848903 git.c:460               trace: built-in: git config --bool mergetool.prompt
16:39:02.919503 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:02.920503 git.c:460               trace: built-in: git config --bool difftool.prompt
16:39:02.985088 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:02.986089 git.c:460               trace: built-in: git config difftool.winmerge.cmd
16:39:03.100982 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:03.101981 git.c:460               trace: built-in: git config difftool.winmerge.cmd
16:39:03.217456 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:03.218455 git.c:460               trace: built-in: git config difftool.winmerge.path
16:39:03.249984 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:03.250984 git.c:460               trace: built-in: git config mergetool.winmerge.path
16:39:03.312668 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:39:03.313667 git.c:460               trace: built-in: git config difftool.winmerge.cmd

Here's my GIT configuation:

C:\Temp\user1\core>cat \users\tom\.gitconfig
[user]
        name = Tom Rutchik
        email = tom@phinneyridge.com
[filter "lfs"]
        process = git-lfs filter-process
        required = true
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
[diff]
         tool=winmerge
[difftool]
      prompt = false
[difftool "winmerge"]
        cmd = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$LOCAL\" \"$REMOTE\"
[merge]
      tool = winmerge
[mergetool "winmerge"]
        cmd = \"C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe\" \"$MERGED\"
[gui]
        recentrepo = C:/Temp/MyApplication
        recentrepo = C:/PR/Dev/Android/Coreq
[credential "https://prdev.corp.phinneyridge.com"]
        provider = generic
[init]
        defaultBranch = main

I've made some changes from what I originally posted, but the configuration I originally posted also works (I verified that). So, there's a mystery here. We know that something had to change for it to start working, but I just don't know what I did to fix the problem.  I'm going to close the problem, but unfortunately, I can't explan the cause of the problem. When it wasn't working, it was a solid failure, and the problem occurred for days.

**Comment by phinney** [comment]
I now see what's happening.  I'm not sure if this is a bug or how Git is supposed to work.  It is however very confusing. Here's what causes the default diff tool to be used instead of the configured git diff tool:

I get myself into the state where the head of the remote is at least one commit ahead of the version that my local branch was checked out from.  When I try to push my local changes back to the branch, here's what happens:

C:\Temp\user2\core>git push
To c:\Temp\clone\core.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'c:\Temp\clone\core.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

So I then do a git pull, and here's what happens:

C:\Temp\user2\core>git pull
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 40 (delta 12), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (40/40), 3.13 KiB | 46.00 KiB/s, done.
From c:\Temp\clone\core
   a7b9b22..6cce36f  main       -> origin/main
Auto-merging CoreInterfaces/src/main/java/com/phinneyridge/core/Core.java
CONFLICT (content): Merge conflict in CoreInterfaces/src/main/java/com/phinneyridge/core/Core.java
Automatic merge failed; fix conflicts and then commit the result.

When this happens, my local git repository now understands that there is a git conflict.  I'm not sure of the mechanics behind git, but I've certainly learned that you must do the git pull before, git recognizes that a conflict exists.  I've certainly have observed that "git mergetool" won't work until you do a "git pull" and get the above message.

It's when I'm in this state that doing a "git difftool" that git always uses the default git diff tool regardless of whether I've got an external git tool defined in the configuration.  If I do a "git mergetool" and resolve the conflict, and then do a "git difftool", I do get a diff using my configured diff tool.  If that's what git is supposed to do, I find that behavior completely confusing.  The entire documentation about mergetool and difftool is all very confusing.  The behavior is dependent on being in some state and how you get git into the state so things work as one might expect is not well documented.  I find the documentation about $LOCAL $REMOTE and $MERGE very confusing.  The difftool man page talks about pre and post image differences, and they don't explain the relationship between a pre and post images as to working directory file, local head, remote origin and remote head.  I think the concept about images is introduced because Git internally is making hidden temporary files.  

I'm going to reopen this problem with the hope that someone can bring some clarity as to why the behavior I observed makes perfect sense.  With my current understanding, I would say this is a GIT bug, but I sure that many would say that's how it's supposed to work. I'll bet that I'm not alone in finding this behavior strange and unexpected.

**Comment by PhilipOakley** [comment]
> So I then do a `git pull`, and here's what happens:

It maybe that this `git pull` step might be tripping things up. The `git pull` is the internal concatenation of first a `git fetch`, to get that remote's commit that is ahead of your local version, and then a forced `git merge` of that remote commit and your local branch head (and her you get that conflict diff...).

In many scenarios that workflow isn't always what you want, but was common in the Linux flow, hence the `git pull` command. 

I always separate out the fetch, and the merge, so that in the middle I can determine what I really need to do. What I'm not sure of (haven't looked) is whether the pull command already, internally programmed in some way, chose a different (e.g. default) merge process.

You could try separating the `git fetch` step and the `git merge` step to see if the correct merge-tool is used in that case.

**Comment by PhilipOakley** [comment]
> it automatically side-steps the regular diff machinery

Oops, I hadn't spotted that Dscho had already noted how the issue arises when the `pull` has the conflict...
