### ISSUE TITLE
git.exe ignoring any input from keyboard

### ISSUE THREAD

**Issue by rafis** [git-for-windows/git#417]
I'm running `git pull`:

    >git pull
    The server's host key is not cached in the registry. You
    have no guarantee that the server is the computer you
    think it is.
    The server's rsa2 key fingerprint is:
    ssh-rsa 2048 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
    If you trust this host, enter "y" to add the key to
    PuTTY's cache and carry on connecting.
    If you want to carry on connecting just once, without
    adding the key to the cache, enter "n".
    If you do not trust this host, press Return to abandon the
    connection.
    Store key in cache? (y/n)

I can't press nor Yes, nor No. Only Ctrl-C works. I have tried both MinTTY and Windows cmd.exe.

Git for Windows 2.5.3
Putty 0.65

**Comment by dscho** [comment]
Isn't it mentioned somewhere in the release notes that you need to connect via Putty first before you can connect from Git?

*clicketyclick*

Yep, indeed. It is the *second from top* entry of the [Known Issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues):

> * If configured to use Plink, you will have to connect with putty first and accept the host key.

**Comment by KindDragon** [comment]
It somehow doesn't work even with this simple exe instead of plink:
```
int main(int argc, char **argv)
{
    char line[32];
    char ch = getchar();
    line[0] = ch;
    line[1] = '\0';
    printf(line);
    return 0;
}
```

**Comment by dscho** [comment]
@KindDragon you *might* have more luck when prefixing the Git command with `winpty` (which is a command that emulates a Win32 Console while still really interacting with the MinTTY window).

**Comment by KindDragon** [comment]
I've tried run `git fetch` directly from MinTTY console, but no luck.
I don't know how `ssh.exe` works without that issue with Git for Windows, but even simple console app can't get console input when called from Git.

**Comment by KindDragon** [comment]
Maybe because of `simple console app` was compiled using MSVC(?)

**Comment by dscho** [comment]
> I've tried run git fetch directly from MinTTY console, but no luck.

As I asked: please try with `winpty git fetch`.

> I don't know how ssh.exe works without that issue with Git for Windows, but even simple console app can't get console input when called from Git.

As I tried to explain, MinTTY does not use a real Win32 Console (and neither does ssh.exe, they both rely on the POSIX emulation of a tty provided by the MSYS2 runtime).

> Maybe because of simple console app was compiled using MSVC(?)

Indeed. MSVC has no idea about MSYS2's runtime and its tty emulation.

So again, please try with `winpty`.

**Comment by KindDragon** [comment]
> As I asked: please try with winpty git fetch.

Same result
