### ISSUE TITLE
no_proxy env var no more working due to curl version used

### ISSUE THREAD

**Issue by sburkard** [git-for-windows/git#4171]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.0.windows.1
cpu: x86_64
built from commit: de9501c66f93785f7eaf10d02ef08d231eb11688
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.2274]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

No options, just default 

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Git installed through Scoop package manager

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash and Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
PS C:\Users\MyAccount> **$env:no_proxy**
localhost,.[company-domain].ch
PS C:\Users\MyAccount> git clone https://gitlab.[company-domain].ch/...[reponame] .\scoop\buckets\[reponame]
Cloning into '.\scoop\buckets\[reponame]'...
fatal: unable to access 'https://gitlab.[company-domain].ch/.../[reponame]/': **Received HTTP code 504 from proxy after CONNECT**

```
 - What did you expect to occur after running these commands?

That the repository is cloned 

 - What actually happened instead?

An error because curl tries to reach the internal repository through the proxy. **It actually ignores the no_proxy environment variable**

This seems to be broken in curl and already fixed. See also https://github.com/curl/curl/issues/9884

It would be nice to have a Git for Windows Release that uses an older version of curl where the no_proxy variable is used correctly.

**Comment by rimrul** [comment]
> It would be nice to have a Git for Windows Release that uses an older version of curl where the no_proxy variable is used correctly.

Like Git for Windows 2.38.1 and earlier? Curl v7.87.0 with the fix for this regression is [expected for next week](https://curl.se/dev/release-procedure.html). I don't think we'll rollback our curl version and create a 2.39.0(2) for this minor regression.

**Comment by sburkard** [comment]
> Like Git for Windows 2.38.1 and earlier?
The point with Scoop is that it pulls the latest version. So currently fresh git installs with Scoop are stuck to this version.
There is a possibility to use `scoop install git@[version]`, but that did not work for me. 

But since the next curl release is expected for next week, this is probably not a big issue. 
Thanks!

**Comment by dscho** [comment]
@sburkard you could also backport the relevant patch(es), add them as `.patch` file(s) to https://github.com/git-for-windows/MINGW-packages/tree/HEAD/mingw-w64-curl (you will want to imitate https://github.com/git-for-windows/MINGW-packages/commit/7b39ea818c014bafcd7c75f6aefd614fef756164) and open a PR, if you care about this bug enough to put in the effort. I would be delighted to accept such a PR.

**Comment by dscho** [comment]
In anticipation of the upcoming cURL version, I added this to the "Next milestone", i.e. to the list of tickets that will go into the next official Git for Windows release.

**Comment by dscho** [comment]
This will most likely be addressed by https://github.com/git-for-windows/git/issues/4191.

**Comment by dscho** [comment]
@sburkard please test [the tentative installer](https://github.com/git-for-windows/git-sdk-64/suites/9986824331/artifacts/484622435) or [the tentative Portable Git](https://github.com/git-for-windows/git-sdk-64/suites/9986824331/artifacts/484622439).

**Comment by dscho** [comment]
/add release note bug A [regression](https://github.com/git-for-windows/git/issues/4171) that caused `no_proxy` to be ignored was fixed by [upgrading libcurl](https://github.com/git-for-windows/git/issues/4191).

**Comment by sburkard** [comment]
I tested the tentative Portable Git installer and it worked perfectly

![image](https://user-images.githubusercontent.com/6469848/208964787-11cbb063-e9a6-4f8c-9e20-f5f1cb51e0d4.png)

Thanks a lot

**Comment by dscho** [comment]
Thank you for testing. You will be delighted to learn that v2.39.0(2) was released in the meantime, containing the fix.

**Comment by sburkard** [comment]
> Thank you for testing. You will be delighted to learn that v2.39.0(2) was released in the meantime, containing the fix.

Yes, awesome! And the new version is already delivered via Scoop 😄 
Thank you very much
