### ISSUE TITLE
Feature request: silently stops ssh-agent.exe when upgrading

### ISSUE THREAD

**Issue by jeanmichel-nwsb** [git-for-windows/git#4172]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.39.0.windows.1
cpu: x86_64
built from commit: de9501c66f93785f7eaf10d02ef08d231eb11688
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Windows 10 Professional 64-bit, 22H2
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: nano
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash (but that's not relevant to the request)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Running setup for upgrading an existing git-for-windows while ssh-agent is already running in the background.

 - What did you expect to occur after running these commands?

Seamless upgrade with no or little user interaction.

 - What actually happened instead?

The installer comes up with an error message telling that ssh-agent.exe is running in the background.
User have to open the task manager, go to the "Details" tab, find ssh-agent.exe and kill it in order to continue the upgrade process.
This is a bit tedious and unfriendly

I am suggesting that the installer either silently kill the running ssh-agent.exe, or at least offers to do it on behalf of the user when popping up the message.

As far as I remember, this behavior has been consistent since I am using Git-for-Windows for the last 3 years.

Thanks
Beside that, I LOVE git-for-windows and git-bash. I prefer using that than WSL2.
Thanks for the job.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

not applicable

**Comment by dscho** [comment]
That's a great idea, and you can even contribute that change yourself:

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `modules.inc.iss`
   You will see that [there is already code identifying `ssh-agent` as a terminate-able process](https://github.com/git-for-windows/build-extra/blob/15c72a8282add1a1410a062191ae238194fc8f88/installer/modules.inc.iss#L540). To find out why that code does not work as expected, you could use `Log()` or `MsgBox()`
4. build a new installer via `sdk build installer`/test the page via `./release.sh -d Processes`
5. either add more debugging statements, or attempt to fix the bug, then repeat the previous step
6. verify that that installer works as expected?
7. open a PR?

**Comment by jeanmichel-nwsb** [comment]
Thanks for pointing me in the right direction
I will try during the holidays ;) 
Have a great end of year time

**Comment by landstander668** [comment]
@jeanmichel-nwsb If you do create a PR for this, it would probably be worth including `ssh-pageant` as well. It basically handles the same role as the OpenSSH agent, but forwarding requests to the PuTTY authentication agent (pageant) instead of managing the keys itself.

**Comment by jeanmichel-nwsb** [comment]
Oups, I haven't used Pascal since I left engineering school in 1989... 🙄 

I have identified part of the problem : the test in the line pointed by @dscho doesn't work

https://github.com/git-for-windows/build-extra/blob/15c72a8282add1a1410a062191ae238194fc8f88/installer/modules.inc.iss#L540-L541

because ` Processes[Have].Name` is not `ssh-agent` but `ssh-agent.exe` 

So I tried the following, backward compatible code:
```  Pascal
                ProcessName:=Processes[Have].Name;
                Position:=Pos('.exe',LowerCase(ProcessName));
                if (Position>0) then SetLength(ProcessName,Position-1);
                if ('ssh-add'=ProcessName) or ('ssh-agent'=ProcessName) or ('ssh-pageant'=ProcessName) or ('gpg-agent'=ProcessName) or ('scdaemon'=ProcessName) then
                    Processes[Have].ToTerminate:=True;
```

It seems more or less to do the job but not before the page that list the processes to kill have appeared once
I will PR this, inviting people to test more before merging

**Comment by jeanmichel-nwsb** [comment]
Fixed with https://github.com/git-for-windows/build-extra/pull/453

**Comment by dscho** [comment]
/add release note bug The installer is expected to stop GPG agents automatically, but there was [a bug](https://github.com/git-for-windows/git/issues/4172) that prevented that from working, which [has been fixed](https://github.com/git-for-windows/build-extra/pull/453).
