### ISSUE TITLE
Feature Request: Shortcut for Copy & Paste is customisable

### ISSUE THREAD

**Issue by Paw2Pom** [git-for-windows/git#4179]
It will be great if we can customize the shortcuts (key) for Copy and Paste, i.e.

Copy: CTRL or ALT + C
Paste: CTRL or ALT + V

**Comment by dscho** [comment]
@Paw2Pom To do this, you will most likely have to experiment with `/etc/inputrc` as described e.g. [here](https://www.saltycrane.com/blog/2008/05/how-to-paste-in-cygwin-bash-using-ctrl/).

Once you get that to work, you will need to 
1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `install.iss` to introduce the option (you could put it into the "Components" section, i.e. the first installer page that lets the users choose e.g. to automatically check once a day for Git for Windows updates) and to update the `/etc/inputrc`
4. build a new installer via `sdk build installer`/test the page via `./release.sh -d Editor`
5. verify that that installer works as expected
6. open a PR?

**Comment by Paw2Pom** [comment]
Thank you so much @dscho 

I have followed the steps in:
https://www.saltycrane.com/blog/2008/05/how-to-paste-in-cygwin-bash-using-ctrl/

(1) 
Add the following line to your ~/.bashrc:
stty lnext ^q stop undef start undef

(2) 
And add the following line to your ~/.inputrc:
"\C-v": paste-from-clipboard

But I still cannot get "CTRL + V" to work in git-terminal.

Am I missing any steps?

**Comment by Paw2Pom** [comment]
Is it possible to for the shortcuts for "Copy and Paste" to change from:

Ctrl / Shift+Ins

to 

Ctrl C / Ctrl V

<img width="380" alt="00" src="https://user-images.githubusercontent.com/21134942/208285303-040945b1-43aa-4bf8-a384-02cb905c8629.png">


?

**Comment by dscho** [comment]
Great! So no further action is required on this ticket.
