### ISSUE TITLE
Support `git mv somefile SomeFile`

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#419]

**Comment by linquize** [comment]
set `core.ignorecase` to `false`?

**Comment by tboegi** [comment]
Is this already fixed in git.git (?)
commit baa37bff9a845471754d3f47957d58a6ccc30058
Author: David Turner <dturner@twitter.com>
Date:   Thu May 8 10:23:34 2014 -0700

    mv: allow renaming to fix case on case insensitive filesystems
    
    "git mv hello.txt Hello.txt" on a case insensitive filesystem
    always triggers "destination already exists" error, because these
    two names refer to the same path from the filesystem's point of
    view, and requires the user to give "--force" when correcting the
    case of the path recorded in the index and in the next commit.
    
    Detect this case and allow it without requiring "--force".
    
    Signed-off-by: David Turner <dturner@twitter.com>
    Signed-off-by: Junio C Hamano <gitster@pobox.com>

**Comment by dscho** [comment]
I have to test this first, I got a bug report from a co-worker and did not want to lose track of it. Mentioning a commit is good, but a concrete test using a published Git for Windows version in addition would be even better 😜

**Comment by dscho** [comment]
Indeed, thanks @tboegi. I missed this because it actually hit 2.0.1 already, at that time I really ran out of y Git time budget pretty much everytime I tried to work on Git for Windows, so yeah, that one slipped through.

And a quick test indeed shows that it works as expected with the current Git for Windows version!
