### ISSUE TITLE
Issue: Shell Script dont' work on Git for Windows to start Python venv

### ISSUE THREAD

**Issue by Paw2Pom** [git-for-windows/git#4195]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
<img width="431" alt="Screenshot 2022-12-23 at 9 02 23 AM" src="https://user-images.githubusercontent.com/21134942/209250544-f8d59107-fee1-487e-a768-70406870cc6d.png">

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 - Windows 11 Enterprise 64-bit ARM 
 - Microsoft Windows [Version 10.0.22621.1037]

 - What options did you set as part of the installation? Or did you choose the
   defaults? Yes
<img width="623" alt="Screenshot 2022-12-23 at 9 04 42 AM" src="https://user-images.githubusercontent.com/21134942/209250702-b831fc4f-e49d-4a56-b445-10975eaedd09.png">

Issue:
I am using the python's venv virtual environment. I have created a simple bash file to help me execute the "source venv/Scripts/activate" command like the following:

<img width="329" alt="Screenshot 2022-12-23 at 9 06 44 AM" src="https://user-images.githubusercontent.com/21134942/209250895-e4c0f910-df68-4d0d-b135-a02d64151dbb.png">

However when I execute it in Git for Windows, nothing happens:

<img width="653" alt="Screenshot 2022-12-23 at 9 00 29 AM" src="https://user-images.githubusercontent.com/21134942/209250920-1f64d80c-8a6b-4729-8753-03e6c2653196.png">

I have to type out the "source venv/Scripts/activate" to start the virtual environment.

Question:
Why can't the shell script work?

**Comment by rimrul** [comment]
Does this work on any other operating system(or wsl)? Because my understanding of your script is that it creates the `venv` in the bash instance that executes the script. Which exits when the script ends and takes the `venv` with it.

It should work if you call `. ./start_vennv.sh`

**Comment by Paw2Pom** [comment]
omg it worked with: . ./start_vennv.sh

Thank you @rimrul 

A quick question, why do you need another dot before "./start_vennv.sh"?

**Comment by Paw2Pom** [comment]
Thank you so much @rimrul !
