### ISSUE TITLE
Fix `bsdtar` in Git for Windows' SDKs

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#4197]
@dennisameling [reported](https://github.com/msys2/MSYS2-packages/issues/3013#issuecomment-1364422150) that a recent MSYS2 upgrade of OpenSSL to v3.x broke `bsdtar`, which we need to build Pacman packages (including `mingw-w64-git`, the core package around which Git for Windows is built).

Let's address this in [the same way as we did when we had to downgrade `bash`](https://github.com/git-for-windows/git-sdk-64/commit/67fdbfeace999d2f0a99daf48add3e4546d3e44f).

Previously, in such cases @vdye or I identified which version needed to be downgraded to, downloaded it from https://repo.msys2.org/, installed it in a local `git-sdk-*` clone using `pacman -U`, preventing it from being upgraded by editing `/etc/pacman.conf`'s `IgnorePkg` line (and uncommenting it), committing and pushing.

This is a bit fragile and might not even work if a previous package was removed from MSYS2's Pacman repository (e.g. to save space). An alternative (that we had not tried before) would be to use only information already in the `git-sdk-*` commit history to downgrade.

We could use the opportunity to automate this. What I currently have in mind is a shell script in `build-extra` that takes two arguments, a package name (or even a list of package names) and a shell script snippet verifying that the downgrading fixes the underlying issue, e.g. `bsdtar -h || test $? = 1`). The script would:
- identify the current package version (by expanding the `/var/lib/pacman/local/$PACKAGE_NAME-[0-9]*` wildcard pointing to a directory)
- identify the `git-sdk-*` commit that added said directory
- remove the files of the package (the list of files is contained in a file in that directory, `tree` or `mtree` IIRC)
- run the `post_remove` (or `pre_upgrade`, or however it's called) scriptlet of the package if there is any (contained as shell function in the `install` script in the directory)
- reinstate the files of the previous package version (looking at the information of the parent commit)
- run the `post_upgrade` scriptlet for that version
- verify that the underlying issue is fixed
- commit the files and the package directory

This could be done in a partial clone (probably even shallow, with a depth of 500 or 1000) so that it can be run efficiently in a GitHub workflow.

/cc'ing @ldennington and @jeffhostetler (because I'm mostly off of the computer until the second week of January)

**Comment by dennisameling** [comment]
[Looks like](https://github.com/git-for-windows/git-sdk-64/pull/57) downgrading `bsdtar` only is not enough: https://github.com/git-for-windows/git-sdk-64/actions/runs/3771072281/jobs/6411273717. A total of [9 packages](https://github.com/git-for-windows/git-sdk-64/commits/main) were updated, so I'll probably just add all of them to `IgnorePkg` for now.

**Comment by dennisameling** [comment]
Alright, [this](https://github.com/git-for-windows/git-sdk-64/pull/57) should fix things for now in `git-sdk-64`. Currently waiting for CI to do its thing and checking some things manually as well.

**Comment by dennisameling** [comment]
Yep, that worked 🎉 @dscho ok to merge https://github.com/git-for-windows/git-sdk-64/pull/57?

**Comment by rimrul** [comment]
@dscho, we'll probably need a way to prevent `pacman` updates from undoing this (see https://github.com/git-for-windows/git-sdk-64/commit/b635d19f9aa8b0abab1c1a0698f217f39b51476)

**Comment by rimrul** [comment]
Interestingly the sync job for arm64 produced a `.pacnew` file instead of overwiting the existing config file.

**Comment by dscho** [comment]
i guess we need to add this to git-extra's post-install function?

About the `.pacnew` file: I don't understand either why it is created for arm64 but not amd64... https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave would suggest that the behavior should be identical in both...

**Comment by dscho** [comment]
> I don't understand either why it is created for arm64 but not amd64...

Ah, I do think I understand now: we use `please.sh sync` in the amd64 version (which [has special handling for `.pacnew` files](https://github.com/git-for-windows/build-extra/blob/3cda9eb70cca0e7e8de3d8c3e0076eb68e6c39d3/please.sh#L327-L367)).

In the arm64 version, I could not make the `please.sh sync` method work because that shell script was designed at a time when I still managed all of Git for Windows in a dedicated VM that had both `git-sdk-32` and `git-sdk-64` and I wanted `please.sh` to ideally update both via a single invocation. And the way I made that work was by using `git-cmd.exe --command=usr\bin\bash.exe` to avoid running into problems with mismatched `msys-2.0.dll` versions when running from a Git Bash. And that `git-cmd.exe` is naturally a _native_ Win32 program, in arm64's case an aarch64 one that won't be able to run in hosted GitHub Actions runners (because there are no arm64 runners yet), and I really wanted the `sync` job to run in hosted runners.

And in my frantic attempts to fix that `sync` job in arm64 before the holidays, I simply [recreated the `sync` command in PowerShell](https://github.com/git-for-windows/git-sdk-arm64/blob/a7c5e9606d0cdd17b8c2402b73d8414f84091147/.github/workflows/sync.yml#L34-L77), overlooking that `pacnew` handling (and also [the asciidoctor handling](https://github.com/git-for-windows/build-extra/blob/3cda9eb70cca0e7e8de3d8c3e0076eb68e6c39d3/please.sh#L308-L319)).

**Comment by dscho** [comment]
I've re-fixed this in git-for-windows/git-sdk-64@4c5ca7dbd8

**Comment by dscho** [comment]
> And in my frantic attempts to fix that `sync` job in arm64 before the holidays, I simply [recreated the `sync` command in PowerShell](https://github.com/git-for-windows/git-sdk-arm64/blob/a7c5e9606d0cdd17b8c2402b73d8414f84091147/.github/workflows/sync.yml#L34-L77), overlooking that `pacnew` handling (and also [the asciidoctor handling](https://github.com/git-for-windows/build-extra/blob/3cda9eb70cca0e7e8de3d8c3e0076eb68e6c39d3/please.sh#L308-L319)).

FWIW I think we will want to fix the arm64 version of the `sync` job to implement the same `pacnew` handling, potentially special-casing `etc/pacman.conf` by carrying over the `IgnorePkg` changes, and also the `asciidoctor` handling.

Then we will want to port those changes over to the i686 and x86_64 SDKs, and then remove the `sync` command from `please.sh`.
