### ISSUE TITLE
The directory generated by "scalar diagnose" is not ignored by default.

### ISSUE THREAD

**Issue by elpiekay** [git-for-windows/git#4199]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.0.windows.2
cpu: x86_64
built from commit: e7d4c504802f93f5914ed48944ced4e593bcaf6c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1165]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
No.
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
Bash
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init foo
cd foo
scalar register
scalar diagnose
```
 - What did you expect to occur after running these commands?

The command "scalar diagnose" creates a directory named .scalarDiagnostics under the repository root and also generates a .zip in it. I expect it to be ignored by default. Maybe the command can automatically add "/.scalarDiagnostics/", and patterns for other possible directories and files generated by the "scalar" commands, to ".git/info/exclude". Or maybe the directory can be generated at another place like under ".git/". 

 - What actually happened instead?

The generated directory .scalarDiagnostics is not ignored by default.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It's not occurring with a specific repository.

**Comment by derrickstolee** [comment]
I do not believe that `scalar diagnose` should modify the `.gitignore` file. Having it present and visible as an untracked directory helps users see that it exists and should be handled as they see fit.
