### ISSUE TITLE
git checkout -p is not working

### ISSUE THREAD

**Issue by hkdennis2k** [git-for-windows/git#420]
$ git --version
git version 2.5.2.windows.2
(I guess the bug exists since 2.5.0)

Steps to reproduce
1) change a file
2) git st
 M test/java/com/xxxx/beans.xml
3) git checkout -p 
4) press Y on all prompt for discard changes
5) git st
 M test/java/com/xxxx/beans.xml
6) git checkout test/java/com/xxxx/beans.xml
7) git st
  (blank)

Expected:
 blank result on step (5)

Actual:
 file beans.xml unchanged

**Comment by Radrik5** [comment]
I cannot reproduce this with git 2.5.3.windows.1. `git checkout -p` successfully cleans the working directory.

**Comment by dscho** [comment]
@hkdennis2k I fear that the description is a bit incomplete.

For one, you might want to describe which options you chose when installing (if you upgraded recently, the installer would have picked the same options as last time, *not necessarily the defaults*, therefore it is necessary to be precise).

Since we now have one report already that the problem cannot be reproduced (and I hereby testify that `git checkout -p` is working fine for me, as I am using it heavily myself), it is quite likely that the trigger is your particular repository.

So here is my challenge: come up with a minimal, complete and verifiable example. List precisely the commands to generate a new repository and working directory and to trigger the error. Or at least give us a repository to clone where we might reproduce the error.

Remember: if you cannot help us reproduce the error, it is unlikely that we can help you by fixing the bug.

**Comment by hkdennis2k** [comment]
I was tried to reproduce in last few days but not successful for build a reproducible steps.
`git checkout -p` does work for me on last friday.

BTW, I also get few failing to `reset / reset -p` when there is a `git svn fetch` running in the background. I am not sure are they related. But unlike checkout, reset does produce a few ".git/.....index" file locked warning message. (but it never tell the reset was unsuccess)

I'll update with more detail once I found a pattern.

**Comment by dscho** [comment]
Hmm. I think it is to be expected that running two Git operations on the same repository in parallel is prone to cause trouble, especially if both operations want to write to the repository.

In any case, this report appears to be not specifically about Windows, but about Git in general. I would therefore recommend to send a mail to [the Git mailing list](mailto:git@vger.kernel.org) once you found a reliable way to reproduce the described issues.

**Comment by hkdennis2k** [comment]
I found that the bug happens without two concurrent operations.

```
$ git add -p 
.....(only one change and answer Y)...
.....(success)...
$ git reset -p 
.....(only one change and answer Y)...
.....(success)...
$ git checkout -p
.....(only one change )...
Discard this hunk from worktree [y,n,q,a,d,/,e,?]? y
error: patch failed: test/java/com/xyz/core/Masked.java:107
error: test/java/com/xyz/core/Masked.java: patch does not apply
(the diff content)
```
when I run with GIT_TRACE=true
```
13:05:04.793252 git.c:348               trace: built-in: git 'diff-files' '-p' '--' 'test/java/com/xyz/core/ClassName.java'
13:05:04.873252 git.c:348               trace: built-in: git 'diff-files' '-p' '--color' '--' 'test/java/com/xyz/core/ClassName.java'
.....
Discard this hunk from worktree [y,n,q,a,d,/,e,?]? y
13:03:45.677752 git.c:348               trace: built-in: git 'apply' '-R' '--recount' '--allow-overlap'
error: patch failed: test/java/com/xyz/core/ClassName.java:107
error: test/java/com/xyz/core/ClassName.java: patch does not apply
diff --git a/test/java/com/xyz/core/ClassName.java b/test/java/com/xyz/core/ClassName.java
index 3d7ec08..193f801 100644
--- a/test/java/com/xyz/core/ClassName.java
+++ b/test/java/com/xyz/core/ClassName.java
@@ -107,6 +107,7 @@ import com.xyz.appl.Class0;
 import com.xyz.appl.Class1;
 import com.xyz.appl.Class2;
 import com.xyz.appl.Class3;
+import com.xyz.appl.Class4;
 import com.xyz.appl.Class5;
 import com.xyz.appl.Class6;
 import com.xyz.appl.Class7;
13:03:45.707752 git.c:348               trace: built-in: git 'update-index' '--refresh'
```

**Comment by dscho** [comment]
@hkdennis2k I doubt that this is caused by the listed commands, but it could be an issue with line endings. It is too hard to tell without a concrete example. Any chance you can come up with a minimal repository demonstrating the problem, and then publish that repository on GitHub?

**Comment by hkdennis2k** [comment]
I agree that could be an issue with line endings. The line was unix "\n" but `git diff` show me ^M at the EOL, but not showing the same on -p commands.

Will try to setup a minimal repository later.
