### ISSUE TITLE
Most recent 2.39.0.windows.2 release fails to connect to BitBucket repositories using HTTPS

### ISSUE THREAD

**Issue by jurko-gospodnetic** [git-for-windows/git#4202]
### Setup

 - does not work with 64-bit Git for Windows version `git version 2.39.0.windows.2`
```
$ git --version --build-options

git version 2.39.0.windows.2
cpu: x86_64
built from commit: e7d4c504802f93f5914ed48944ced4e593bcaf6c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
 - works with 64-bit Git for Windows version `git version 2.39.0.windows.1`
```
$ git --version --build-options

git version 2.39.0.windows.1
cpu: x86_64
built from commit: de9501c66f93785f7eaf10d02ef08d231eb11688
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

  I was using the older version successfully.
  Then got an update prompt and installed it after which it stopped working.
  Then reverted back to the original version and it worked again.
  Then reinstalled the new version and it stopped working again.
  Reboot does not fix the problem either.

 - using 64-bit Windows 10
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2364]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
Plink Path: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - running Git from the `cmd` shell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch
git fetch --all
git fetch --prune
git -C "." fetch
```

 - What did you expect to occur after running these commands?

to connect to the remote repo and fetch all the new commits from there

 - What actually happened instead?

git failed to commit with the following errors:

```
fatal: unable to access 'https://bitbucket.org/ninjarmm/lockhart.git/': Failure when receiving data from the peer
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Got it reproduced using a completely new BitBucket repository:
```
d:\Workplace>git clone https://jurko@bitbucket.org/jurko/testinggit.git
Cloning into 'testinggit'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 56 Failure when receiving data from the peer
Unpacking objects: 100% (3/3), 590 bytes | 34.00 KiB/s, done.
```

While the same problem does not occur when accessing a GitHub repository:
```
d:\Workplace>git clone https://github.com/jurko-gospodnetic/TestingGit.git
Cloning into 'TestingGit'...
warning: You appear to have cloned an empty repository.

d:\Workplace>rd /s /q TestingGit

d:\Workplace>git clone https://jurko-gospodnetic@github.com/jurko-gospodnetic/TestingGit.git
Cloning into 'TestingGit'...
warning: You appear to have cloned an empty repository.
```

I reported the same problem to BitBucket support and here because as a user, I have no way of telling whether the problem stems from something on their or your end, but there is obviously some incompatibility here and it is really inconveniencing us.

**Comment by ldennington** [comment]
@rimrul - thanks for the assist! @jurko-gospodnetic - please let us know if the workaround works. If it does, we can go ahead and close this in favor of #4194.
