### ISSUE TITLE
Still ssh key problems

### ISSUE THREAD

**Issue by fbehrens** [git-for-windows/git#421]
This is a follow up of closed issue #383. 
if have tried the there described patched msys-2.0.dll on top of 2.5.2(2)

    C:\Dropbox\scripts2\syma\boot>git --version
    git version 2.5.2.windows.2
    C:\Dropbox\scripts2\syma\boot>git pull
    git@byymir.de.bayer.cnb's password: ^C

On 2.5.0(1) it was working

    C:\Dropbox\scripts2\syma\boot>git --version
    git version 2.5.0.windows.1
    C:\Dropbox\scripts2\syma\boot>git pull
    Already up-to-date.

The new release is not working as

    C:\Dropbox\scripts2\syma\boot>git --version
    git version 2.5.3.windows.1
    C:\Dropbox\scripts2\syma\boot>git pull
    git@byymir.de.bayer.cnb's password: ^C

So I am staying on 2.5.0 as long as this is working 
The feature to have the ssh keys at a custom location is important for me, as I provide git on servers with deployment keys.
I will very responsive on this issue and would be grateful if it could be resolved

This is on Windows8.1 Enterprise with ssh keys in c:\tools\home\.ssh. 
    set HOME=c:\tools\home
    set HOMEDRIVE=c:
    set HOMEPATH=\tools\home

**Comment by Radrik5** [comment]
Didn't you forget the last `\` in `c:\tools\home.ssh`? So that it's `c:\tools\home\.ssh`.

Could you please run `ssh -v git@byymir.de.bayer.cnb`?

**Comment by dscho** [comment]
> This is a follow up of closed issue #383.

You can always re-open closed issues, but you should address the questions and concerns that have been raised there before closing, of course.

If the ticket was not opened by you, just provide new information and I will re-open it.

> if have tried the there described patched msys-2.0.dll on top of 2.5.2(2)

That is no longer necessary because the fix made it into 2.5.3, as per the release notes.

> The feature to have the ssh keys at a custom location is important for me, as I provide git on servers with deployment keys.

Could you describe that part? I did not see any information about this other than this sentence. I would like to set up as similar a scenario as possible so I stand a chance to reproduce.

> Could you please run ssh -v git@byymir.de.bayer.cnb?

Or even better `ssh -v -v -v -v -v git@byymir.de.bayer.cnb`. It is quite possible that you are using DSA keys [and that is no longer enabled by default](https://github.com/git-for-windows/git/issues/375).

**Comment by fbehrens** [comment]
Yes, it's home\\.ssh (gihub quoting :smile: )
Thanks, yes it could be that i am using DSA-Keys. I have to check tomorrow.
Anyway, here's the output of

    c:\dropbox\scripts2>ssh -v -v -v -v -v git@byymir.de.bayer.cnb

OpenSSH_7.1p1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: ssh_connect: needpriv 0
debug1: Connecting to byymir.de.bayer.cnb [10.161.45.114] port 22.
debug1: Connection established.
debug1: identity file /c/tools/home/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /c/tools/home/.ssh/id_rsa-cert type -1
debug1: identity file /c/tools/home/.ssh/id_dsa type 2
debug1: key_load_public: No such file or directory
debug1: identity file /c/tools/home/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/tools/home/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/tools/home/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/tools/home/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/tools/home/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3 pat OpenSSH_6.6.1* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to byymir.de.bayer.cnb:22 as 'git'
debug3: hostkeys_foreach: reading file "/c/tools/home/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /c/tools/home/.ssh/known_hosts:4
debug3: load_hostkeys: loaded 1 keys from byymir.de.bayer.cnb
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Ejl3OmQEMHZoznSSVHHGHSRw97X6xJjPFp6oLDRNFug
debug3: hostkeys_foreach: reading file "/c/tools/home/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /c/tools/home/.ssh/known_hosts:4
debug3: load_hostkeys: loaded 1 keys from byymir.de.bayer.cnb
debug3: hostkeys_foreach: reading file "/c/tools/home/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /c/tools/home/.ssh/known_hosts:4
debug3: load_hostkeys: loaded 1 keys from 10.161.45.114
debug1: Host 'byymir.de.bayer.cnb' is known and matches the ECDSA host key.
debug1: Found key in /c/tools/home/.ssh/known_hosts:4
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /c/tools/home/.ssh/id_rsa (0x60008ddb0),
debug2: key: /c/tools/home/.ssh/id_dsa (0x60009e1e0),
debug2: key: /c/tools/home/.ssh/id_ecdsa (0x0),
debug2: key: /c/tools/home/.ssh/id_ed25519 (0x0),
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /c/tools/home/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug1: Skipping ssh-dss key /c/tools/home/.ssh/id_dsa for not in PubkeyAcceptedKeyTypes
debug1: Trying private key: /c/tools/home/.ssh/id_ecdsa
debug3: no such identity: /c/tools/home/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /c/tools/home/.ssh/id_ed25519
debug3: no such identity: /c/tools/home/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
git@byymir.de.bayer.cnb's password:

**Comment by dscho** [comment]
> yes it could be that i am using DSA-Keys

I would indeed say so, given that the output you pasted yourself has this tell-tale:

```
debug1: Skipping ssh-dss key /c/tools/home/.ssh/id_dsa for not in PubkeyAcceptedKeyTypes
```

... which, between the two of us, is the exact same problem described, diagnosed and explained in https://github.com/git-for-windows/git/issues/375. Hence it is now safely established that this is a duplicate of that ticket. :grinning:

**Comment by fbehrens** [comment]
very unsurprisingly it works with rsa keys :+1: 
thank you so much for helping on the issues so good and fast.
It's really wonderfull to have such well maintained and supported git on windows
