### ISSUE TITLE
SSH publickey authentication broken

### ISSUE THREAD

**Issue by PAX523** [git-for-windows/git#4214]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Git for Windows 64-bit?

```
$ git --version --build-options
git version 2.39.0.windows.1
cpu: x86_64
built from commit: de9501c66f93785f7eaf10d02ef08d231eb11688
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Windows 11 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.963]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The authentication is working fine with an older Gitbash installation:

```
$ git --version --build-options
git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

With the new one this happens during authentication:

```
debug1: Next authentication method: publickey
debug1: Offering public key: /c/Users/my.user/.ssh/id_rsa RSA SHA256:...
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Trying private key: /c/Users/my.user/.ssh/id_ecdsa
debug3: no such identity: /c/Users/my.user/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /c/Users/my.user/.ssh/id_ecdsa_sk
debug3: no such identity: /c/Users/my.user/.ssh/id_ecdsa_sk: No such file or directory
debug1: Trying private key: /c/Users/my.user/.ssh/id_ed25519
debug3: no such identity: /c/Users/my.user/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /c/Users/my.user/.ssh/id_ed25519_sk
debug3: no such identity: /c/Users/my.user/.ssh/id_ed25519_sk: No such file or directory
debug1: Trying private key: /c/Users/my.user/.ssh/id_xmss
debug3: no such identity: /c/Users/my.user/.ssh/id_xmss: No such file or directory
debug1: Trying private key: /c/Users/my.user/.ssh/id_dsa
debug3: no such identity: /c/Users/my.user/.ssh/id_dsa: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
my.user@gerrit.my-server.de's password:
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
 - What did you expect to occur after running these commands?

Public key authentication succeeds with the gerrit server

 - What actually happened instead?

The RSA key is rejected

```
my.name@gerrit.my-server.de: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Sorry, no public server

**Comment by dscho** [comment]
> * I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Isn't this a duplicate of https://github.com/git-for-windows/git/issues/3468?

**Comment by PAX523** [comment]
I don't believe that this is the case, since SSH interaction with the same keys works fine with Azure and Gitlab.

**Comment by dscho** [comment]
> I don't believe that this is the case, since SSH interaction with the same keys works fine with Azure and Gitlab.

That's exactly my point. That ticket points to _host_ RSA/SHA-1 keys no longer being allowed. @PAX523 could you try the mitigations proposed on #3468 before rejecting that hypothesis, please?

**Comment by PAX523** [comment]
Yup! I'm going to check that on Monday and report you the result. Thanks.

**Comment by PAX523** [comment]
You are right! That was the cause! The server enforces an obsolete algorithm. Creating a `config` file in the user directory (`~/.ssh/config`) with the following content fixes the issue:

```
Host affected-host.de
  HostkeyAlgorithms +ssh-rsa
  PubkeyAcceptedAlgorithms +ssh-rsa

```
