### ISSUE TITLE
git help fails to open browser when used from bash

### ISSUE THREAD

**Issue by Booplicate** [git-for-windows/git#4215]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.0.windows.2
cpu: x86_64
built from commit: e7d4c504802f93f5914ed48944ced4e593bcaf6c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2364]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (`/bin/bash.exe`)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git help clone
git clone --help
```
Here's trace:
```
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/bin
git.c:460               trace: built-in: git help clone
exec-cmd.c:335          trace: exec: git web--browse -c help.browser D:/Git/mingw64/share/doc/git-doc/git-clone.html
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
git.c:750               trace: exec: git-web--browse -c help.browser D:/Git/mingw64/share/doc/git-doc/git-clone.html
run-command.c:655       trace: run_command: git-web--browse -c help.browser D:/Git/mingw64/share/doc/git-doc/git-clone.html
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
git.c:750               trace: exec: git-sh-i18n--envsubst --variables 'usage: $dashless $USAGE'
run-command.c:655       trace: run_command: git-sh-i18n--envsubst --variables 'usage: $dashless $USAGE'
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
git.c:750               trace: exec: git-sh-i18n--envsubst 'usage: $dashless $USAGE'
run-command.c:655       trace: run_command: git-sh-i18n--envsubst 'usage: $dashless $USAGE'
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
git.c:460               trace: built-in: git config help.browser
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
git.c:460               trace: built-in: git config web.browser
exec-cmd.c:237          trace: resolved executable dir: D:/Git/mingw64/libexec/git-core
git.c:460               trace: built-in: git config browser.start.path
```
If I had to guess, git fails to find my default browser (Vivaldi btw). If that is the case, I think it should throw an error instead of launching cmd.

 - What did you expect to occur after running these commands?

Should open `/doc/git-doc/git-clone.html` in default browser.

 - What actually happened instead?

It seems `cmd` is being launched instead with this output right after the command above:
```
Microsoft Windows [Version 10.0.19045.2364]
(c) Microsoft Corporation. All rights reserved.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

The problem isn't specific to a repository.

**Comment by Booplicate** [comment]
Can be "fixed" by:
```
git config --global web.browser vivaldi
git config --global browser.vivaldi.cmd vivaldi
```
But in older versions I didn't have to configurate it. It's also only an issue in bash - powershell/cmd work.

**Comment by dscho** [comment]
@Booplicate could you call

```sh
export GIT_EXEC_PATH=/mingw64/libexec/git-core/ &&
PATH=$GIT_EXEC_PATH:$PATH &&
sh -x $GIT_EXEC_PATH/git-web--browse -c help.browser 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'
```

in a Git Bash and see what that says? It should print something like the following, before opening the correct `.html` page in the browser:

```
[...]
+ test -n mintty
+ browser_candidates='open firefox iceweasel google-chrome chrome chromium chromium-browser konqueror opera seamonkey iceape w3m elinks links lynx dillo xdg-open'
+ test -x /bin/start
+ browser_candidates='start open firefox iceweasel google-chrome chrome chromium chromium-browser konqueror opera seamonkey iceape w3m elinks links lynx dillo xdg-open'
+ test -x /usr/bin/cygstart
+ for i in $browser_candidates
+ init_browser_path start
++ git config browser.start.path
+ browser_path=
+ test -z ''
+ test start = chromium
+ : start
+ type start
+ browser=start
+ break
+ test -z start
+ case "$browser" in
+ exec start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'
```

**Comment by Booplicate** [comment]
Sure, seems to be trying to choose a text web browser?
<details>
  <summary>output</summary>

```
+ USAGE='[--browser=browser|--tool=browser] [--config=conf.var] url/file ...'
+ NONGIT_OK=Yes
+ . git-sh-setup
++ unset CDPATH
++ IFS='
'
+++ git --exec-path
++ . /mingw64/libexec/git-core//git-sh-i18n
+++ TEXTDOMAIN=git
+++ export TEXTDOMAIN
+++ test -z ''
+++ TEXTDOMAINDIR=/mingw64/share/locale
+++ export TEXTDOMAINDIR
+++ GIT_INTERNAL_GETTEXT_SH_SCHEME=fallthrough
+++ test -n fallthrough
+++ GIT_INTERNAL_GETTEXT_SH_SCHEME=fallthrough
+++ export GIT_INTERNAL_GETTEXT_SH_SCHEME
+++ case "$GIT_INTERNAL_GETTEXT_SH_SCHEME" in
++ test -n ''
+++ basename -- /mingw64/libexec/git-core//git-web--browse
+++ sed -e 's/-/ /'
++ dashless='git web--browse'
++ '[' -z '' ']'
+++ eval_gettext 'usage: $dashless $USAGE'
+++ printf %s 'usage: $dashless $USAGE'
++++ git sh-i18n--envsubst --variables 'usage: $dashless $USAGE'
+++ export PATH dashless USAGE
+++ git sh-i18n--envsubst 'usage: $dashless $USAGE'
++ LONG_USAGE='usage: git web--browse [--browser=browser|--tool=browser] [--config=conf.var] url/file ...'
++ case "$1" in
++ case $(uname -s) in
+++ uname -s
++ test -x /usr/bin/sort
++ test -x /usr/bin/find
++ type builtin
++ test -z Yes
+ test 3 '!=' 0
+ case "$1" in
+ case "$#,$1" in
+ conf=help.browser
+ shift
+ shift
+ test 1 '!=' 0
+ case "$1" in
+ break
+ test 1 = 0
+ test -z ''
+ for opt in "$conf" "web.browser"
+ test -z help.browser
++ git config help.browser
+ browser=
+ test -z ''
+ for opt in "$conf" "web.browser"
+ test -z web.browser
++ git config web.browser
+ browser=
+ test -z ''
+ test -n ''
+ test -z ''
+ test -n ''
+ browser_candidates='w3m elinks links lynx'
+ test -n ''
+ test -n ''
+ test -x /bin/start
+ browser_candidates='start w3m elinks links lynx'
+ test -x /usr/bin/cygstart
+ for i in $browser_candidates
+ init_browser_path start
++ git config browser.start.path
+ browser_path=
+ test -z ''
+ test start = chromium
+ : start
+ type start
+ browser=start
+ break
+ test -z start
+ case "$browser" in
+ exec start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'
```

</details>

**Comment by rimrul** [comment]
> Sure, seems to be trying to choose a text web browser?

That should not be a problem in practice.

> […]
> + test -x /bin/start
> + browser_candidates='start w3m elinks links lynx'

it does find `start`

> […]
> + exec start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'

And does call `start` with the expected arguments. That should in turn call the default browser associated with `.html` files.

**Comment by Booplicate** [comment]
Just in case I checked that too.
![screenshot](https://user-images.githubusercontent.com/53382877/212960995-c8559b9d-b7f1-45fd-b4e4-8d2fdeb7ce24.PNG)

**Comment by dscho** [comment]
Note the exact command line here:

> * exec start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'

and then there:

> If I then do `start "C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html"` in cmd, it works.

Those are different, yes? Can you try the former (in Git Bash)?

**Comment by Booplicate** [comment]
Technically, they are different, but both do the same thing - just launch cmd.

`exec` replaces current process with the new one - cmd in this case. That said, I don't think the arguments (`"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'`) are being passed to cmd or at least it doesn't seem to process arguments.

**Comment by dscho** [comment]
@Booplicate they are different, even if _in the end_ they are supposed to do the same thing.

However, they don't do the same thing, otherwise this ticket would not exist.

When I fire up my Git Bash and call `start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'` in that Bash, it works as intended: it opens that HTML page in my web browser.

On your end, it obviously does not seem to do that. And that is where we need to dig deeper, otherwise we will never solve this riddle!

So, first step is to verify that `start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'` indeed only opens a CMD window on your end. Once we established that, let's figure out whether `/usr/bin/start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'` does the same. And if that's _also_ the case, start tracing the commands: `bash -x /usr/bin/start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'`. And if we keep digging, we will figure this out.

**Comment by Booplicate** [comment]
Thanks for helping me debugging this!

> Once we established that, let's figure out whether `/usr/bin/start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'` does the same. 

Yep, also just starts cmd. Just in case: `which start` returns `/usr/bin/start`, so `start` *is* `/usr/bin/start` when invoked through bash.

> And if that's also the case, start tracing the commands: `bash -x /usr/bin/start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'`

This is the output before it launches cmd:
```
+ 'C:\Windows\system32\cmd.exe' //c start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'
```

**Comment by dscho** [comment]
Hmm. Is it possible that you have a custom MSYS2 runtime in your installation? I only saw such a behavior either with custom `msys-2.0.dll` or when there was only one slash before the `c`, i.e. `/c` instead of `//c`...

**Comment by Booplicate** [comment]
> Is it possible that you have a custom MSYS2 runtime in your installation? I only saw such a behavior either with custom `msys-2.0.dll`

Not that I'm aware of. I have github desktop installed by side (which I believe also uses git for windows, thus MSYS2), could that be the root of the issue? Although, I'm using git I installed separately:
![Capture](https://user-images.githubusercontent.com/53382877/214530303-9ab3c54d-2ad8-4eae-95bd-d2aa169d0d1e.PNG)

**Comment by Booplicate** [comment]
Somehow `$COMSPEC //c start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'` fails to open html file (or start any program for that matter) and just starts cmd. **But** `$COMSPEC /c start '"web-browse"' 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-clone.html'` does work!

Single `/` is what it needs, but again, I'm not sure how it worked before just fine with the double `/`.

**Comment by Booplicate** [comment]
Kids, don't be fools like me, never set `MSYS_NO_PATHCONV=1`, it's only going to cause headache LOL.

Thanks for the help guys, it was an issue with my configs.

**Comment by dscho** [comment]
> never set `MSYS_NO_PATHCONV=1`

Ah! _That_ would explain things nicely 😁
