### ISSUE TITLE
can't run sh scripts on latest git version 2.5.3, command not found

### ISSUE THREAD

**Issue by maletsiri** [git-for-windows/git#422]
On git 1.9.4 I can run .sh scripts fine.

on git 2.5.3 the .sh* have a star at the end of a filename. I can't run any sh scripts. (uses mintty)
bash: scriptname.sh: command not found

**Comment by Radrik5** [comment]
Try with dot in the beginning: `./scriptname.sh`.

**Comment by maletsiri** [comment]
it worked.

Thanks.

**Comment by dscho** [comment]
> on git 2.5.3 the .sh* have a star at the end of a filename

If you are referring to the output of `ls`, then yes, this is expected.

> I can't run any sh scripts.

I can:

```sh
$ printf '#!/bin/sh\n\necho Hello, where is your MCVE?\n' >issue-422.sh

me@work MINGW32 ~
$ ./issue-422.sh
Hello, where is your MCVE?

me@work MINGW32 ~
$
```

So: where is your *Minimal, Complete and Verifiable Example* (suggested by [our bug reporting guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines)?

**Comment by dscho** [comment]
Oh, never mind. While I was spending some appropriate time to respond, the ticket was just closed without any further explanation.

**Comment by Radrik5** [comment]
Probably Git 1.9 added `.` to the PATH, so you could run scripts from the current directory without `./`.

**Comment by dscho** [comment]
@Radrik5 maybe. I really miss pretty much all details in the report, and I am a bit too tired of guessing ;-)

**Comment by sawong** [comment]
I had the exact same problem (couldn't run sh scripts on latest git 2.70, but could run them from 1.9.5).  Adding ./ before the scriptname worked for me as well.  

However, it would be really nice if I didn't have to type the ./ every time I run the script.  Any chance this could be fixed?

**Comment by dscho** [comment]
> it would be really nice if I didn't have to type the ./ every time I run the script. Any chance this could be fixed?

Unfortunately, your fix would break other things again. For example, if some cunning person talked you into cloning their repository and have a look at the history, sneaking in a `git` script in the top-level directory, all of a sudden your `git log` call would not call Git for Windows but their script. And in that script, they could do whatever silly or malicious as they wanted with all of your privileges.

Therefore, changing the `PATH` to include `.` again would be a serious mistake.

**Comment by sawong** [comment]
Thank you for the explanation.  My present workaround is to just use an alias command in my .bash_profile.  For example:

alias scriptname.sh='./scriptname.sh'

If there is a better workaround, please let me know

**Comment by davidovich** [comment]
Executing shell scripts with the leading ./ is the standard way.
This is not a bug, and you should train your fingers to add the ./ in a
unix shell environment, as it is ubiquitous.

The concepts that you know from the cmd command prompt do not translate to
the git-bash prompt.

**Comment by dra27** [comment]
You can also add this to your `.bashrc`:
```sh
export PATH="$PATH:."
```
This is considered *dreadful* Unix practice, though.
