### ISSUE TITLE
Stabilize changes and secure before breaking support Windows 7-8

### ISSUE THREAD

**Issue by proxy-m** [git-for-windows/git#4232]
### Introduction to breaking changes.

Git 2.39.1 sounds like first test version. May you firstly stabilize changes and security fixes before breaking support for Windows 7, 8.1?

**Comment by proxy-m** [comment]
Windows 10, 11, ... 99 already has native Git via WSL, so when you drop support for older Windows this project will be less useful.

**Comment by dscho** [comment]
> Git 2.39.1 sounds like first test version.

That's incorrect. It is as official a Git for Windows release as they get.

**Comment by proxy-m** [comment]
2.40 is same buggy like 2.39
