### ISSUE TITLE
How to run drush 7 with Git for Windows in Windows 10

### ISSUE THREAD

**Issue by jsibley2** [git-for-windows/git#424]
I'm sorry if there is a better place to ask this question, but I'm trying to run drush 7 in Windows 10 and am having some difficulties.
At a minimum, it seems like php isn't found when I try to run drush. I get:
line 128: php: command not found
line 129: [: -le: unary operator expected
line 137: exec: php: not found

Is this just a matter of paths? Any thoughts?
Thank you.

**Comment by jsibley2** [comment]
If this is clearly a pure drush for windows issue that doesn't have anything to do with Git for Windows, just let me know and I'll ask this in Drupal Answers.

**Comment by jsibley2** [comment]
Based on www.drupal.org/node/1843176 (which I have updated) I added the paths below (where ... represents the path to the windrush extracted from the zip file):

C:\...\windrush\vendor\drush\drush\;C:\...\windrush\vendor\bin;C:\...\windrush\php

This seems to work, so far. 

Rsync needs an additional path (at least) but when I added C:\...\windrush\tools\bin Rsync just seemed to hang.

**Comment by maoueh** [comment]
@jsibley2 Sadly, this is indeed not the right place to ask such questions. You could get more help in Drupal Answers.

I will try to help you anyway. First, I will assume you have installed both PHP (from http://windows.php.net/download/) and composer (https://getcomposer.org/doc/00-intro.md#globally and follow Linux steps).

To ensure everything is configured correctly, open a terminal an issue `php -v` and `composer -V`, you should obtain output similar to me:

```
Matt@WORKSTATION ~
$ php -v
PHP 5.6.5 (cli) (built: Jan 21 2015 16:27:34)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

Matt@WORKSTATION ~
$ composer -V
Composer version 1.0-dev (9f2e562e48145f10bf224f93f561e762df980638) 2015-09-20 18:44:55
```

If you don't get this, your `PATH` is not set correctly and does not contains paths where `php` and composer` are installed. You will need to fix this.

Then, this is how I installed `drush`:

```
Matt@WORKSTATION ~
$ composer global require drush/drush:7.*
Changed current directory to C:/Users/Matt/AppData/Roaming/Composer
....
```

This installed scripts in `C:/Users/Matt/AppData/Roaming/Composer/vendor/bin`, so I added this to my `PATH` and then ran `drush -h`:

```
Matt@WORKSTATION ~
$ export PATH=~/AppData/Roaming/Composer/vendor/bin/:$PATH

Matt@WORKSTATION ~
$ drush -h
Drush provides an extensive help system that describes both drush commands and topics of general interest.  Use `drush help --filter` to present a
list of command categories to view, and `drush topic` for a list of topics that go more in-depth on how to use and extend drush.

...
```

So, this all seems like a `PATH` issue to me. Once `php` and `composer` will work from terminal, it should go like a breeze.

Please close this issue. We could meet on https://gitter.im/git-for-windows/git if you need more help.

Regards,
Matt

**Comment by dscho** [comment]
I agree with the helpful suggestions of @maoueh (in particular about Gitter since this is more a request for help than a bug report) and would like to add two more remarks:

- for `rsync`, it might be necessary to run it via `winpty` if it is not the MSys2 version,
- speaking of MSys2: there are unfortunately no `php` or `composer` packages available, but maybe this is your door to become an Open Sourcerer.
