### ISSUE TITLE
Links in installer unreadable in high contrast mode

### ISSUE THREAD

**Issue by jernejs** [git-for-windows/git#4248]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git-2.39.1-64-bit.exe

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 11 22H2 x64 (22621.1105)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

n/a

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm running Windows in high contrast mode (with custom colour scheme). The installer has a lot of helpful URLs in text, which are unfortunately hardcoded to blue, which unfortunately makes them completely unreadable – see the screenshot:

![image](https://user-images.githubusercontent.com/1800143/214351576-dc2b86f3-b45c-498e-b381-2b1a1d1a7071.png)

**Comment by rimrul** [comment]
Yes, that's not ideal. Do we have a way to  detect this situation and get a better colour?

**Comment by jernejs** [comment]
Instead of hardcoding blue, you should use GetSysColor(COLOR_HOTLIGHT), that'll use the link colour from the Windows theme.

**Comment by dscho** [comment]
@jernejs good idea! Could you try that?

Unfortunately, [`GetSysColor`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsyscolor) is not part of [the functions supported by InnoSetup](https://jrsoftware.org/ishelp/index.php?topic=scriptfunctions), so you'll have to access the function as an `external` much like we handle [`ExitProcess()`](https://github.com/git-for-windows/build-extra/blob/2112e2093797393c25fe851c46ab6928b533ffaa/installer/install.iss#L971-L972).

The link color itself is set [here](https://github.com/git-for-windows/build-extra/blob/2112e2093797393c25fe851c46ab6928b533ffaa/installer/install.iss#L1462) and [here](https://github.com/git-for-windows/build-extra/blob/2112e2093797393c25fe851c46ab6928b533ffaa/installer/install.iss#L1484),

To build an installer, follow [this wiki page](https://github.com/git-for-windows/git/wiki/Making-an-installer).

**Comment by dscho** [comment]
> To build an installer, follow [this wiki page](https://github.com/git-for-windows/git/wiki/Making-an-installer).

Maybe a quicker method in this instance would be to:
1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `install.iss`
4. build a new installer via `sdk build installer`/test the page via `./release.sh -d Editor`
5. verify that that installer works as expected?
6. open a PR?

**Comment by jernejs** [comment]
This was simple enough:
![image](https://user-images.githubusercontent.com/1800143/214404219-da5d533d-46ae-41af-90a3-bab623062a47.png)

```
diff --git a/installer/install.iss b/installer/install.iss
index b803974..abcdbb8 100644
--- a/installer/install.iss
+++ b/installer/install.iss
@@ -1345,6 +1345,12 @@ begin
     Result:=1+StringChangeEx(S,#13,'',True);
 end;

+const
+       COLOR_HOTLIGHT = 26; // Hyperlink color from Windows theme
+
+function GetSysColor(nIndex: Integer): DWORD;
+external 'GetSysColor@user32.dll stdcall';
+
 {
     Description can contain pseudo tags <RED>...</RED> and <A HREF=...>...</A>
     (which cannot be mixed).
@@ -1459,7 +1465,7 @@ begin
                     SubLabel.Left:=GetTextWidth(RowPrefix,Result.Font)+ScaleX(Left+24);
                     SubLabel.Width:=ScaleX(405);
                     SubLabel.Height:=ScaleY(13);
-                    SubLabel.Font.Color:=clBlue;
+                    SubLabel.Font.Color:=GetSysColor(COLOR_HOTLIGHT);
                     SubLabel.Font.Style:=[fsUnderline];
                     SubLabel.Cursor:=crHand;
                     SubLabel.OnClick:=@OpenHyperlink;
@@ -1481,7 +1487,7 @@ begin
                 SubLabel.Left:=GetTextWidth(RowPrefix,Result.Font)+ScaleX(Left+24);
                 SubLabel.Width:=ScaleX(405);
                 SubLabel.Height:=ScaleY(13*CountLines(SubLabel.Caption));
-                SubLabel.Font.Color:=clBlue;
+                SubLabel.Font.Color:=GetSysColor(COLOR_HOTLIGHT);
                 SubLabel.Font.Style:=[fsUnderline];
                 SubLabel.Cursor:=crHand;
                 SubLabel.OnClick:=@OpenHyperlink;
```

Will try to figure out a pull request later.

**Comment by dscho** [comment]
I have come to the decision to stop looking forward to merging that PR because I expect it never to materialize.
