### ISSUE TITLE
Add CACert.org certificate to `mingw64/ssl/certs/ca-bundle.crt`

### ISSUE THREAD

**Issue by koppor** [git-for-windows/git#425]
I am using an SSL certificate created by the [CACert.org system](http://www.cacert.org/). After upgrading from git 1.9.x to 2.5.0 (and 2.5.3), a connection to my server stops with

    SSL certificate problem: unable to get local issuer certificate

An [ack](http://beyondgrep.com/) for the first line of the certificate (`MIIHPTCCBSWgAwIBAgIBADANBgkqhkiG9w0BAQQFADB5MRAwDgYDVQQKEwdSb290`) at `C:\Program Files\Git` reveals multiple files. I know that I can [disable SSL verification](http://stackoverflow.com/a/25151794/873282), but that is not a real solution is it?

**Comment by ErwinHamann** [comment]
I'm not sure, but I think you got the same problem I already had.
Please see at Git for Windows Mailing List -> "15 certificate files at Git program folder needed?"
https://groups.google.com/forum/#!topic/git-for-windows/mlqn5J4OLlw

I think, the certificate file you have to handle is found via git config -l

**Comment by koppor** [comment]
Oh, yes, it really is `http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt`. And there, the CACert.org certificate is missing. Thus, I propose to add it there, too. (See https://github.com/msysgit/msysgit/issues/37 for the discussion in the context of msysgit)

**Comment by dscho** [comment]
@koppor ![I can haz Pull Request?](https://github.com/dscho/images/raw/master/i-can-haz-pull-request.png?raw=true)

**Comment by dscho** [comment]
Umm... @koppor ... you there?

**Comment by koppor** [comment]
Yeah, I'm here. Forked `git` and no searching for `ca-bundle.crt`, but nothing found. Now trying to understand the build process.

**Comment by dscho** [comment]
> Now trying to understand the build process.

Most important resource: https://github.com/git-for-windows/git/wiki (about the general setup), followed by https://github.com/git-for-windows/git/wiki/Package-management and then https://github.com/git-for-windows/git/wiki/Making-an-installer.

For you, https://github.com/git-for-windows/git/wiki/Package-management#list-packages should be *particularly* interesting.

**Comment by koppor** [comment]
I didn't find time and it won't look better the next weeks. To reduce the number of open issues, I'll close this one. Maybe someone else will take over. I posted a pointer to this issue it at the @CAcertOrg mailing list.
