### ISSUE TITLE
Portable Git 2.5.3 32-bit reported as infected by Trojan

### ISSUE THREAD

**Issue by dczarnec** [git-for-windows/git#426]
Files cmd\gitk.exe and cmd\git-gui.exe from PortableGit-2.5.3-32-bit.7z.exe are reported as infected.

See VirusTotal report for gitk.exe file:
https://www.virustotal.com/en/file/a2ece0281077e0d23b4bb6fa04c509387f20159ce4849404f832cc98c95c665f/analysis/1442906180/

**Comment by dscho** [comment]
We had so many false positive (and not even once a true positive) that I am going to dismiss this without any further evidence than "VirusTotal indicates this might contain a Trojan".

Feel free to provide further evidence...
