### ISSUE TITLE
installer: establish a stable registry key for the location and installer options

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#427]
This will be helpful for add-on tools, possibly add-on localization, too.

**Comment by dscho** [comment]
In particular, there needs to be a standardized way to look up the directory where to install additional helpers, such as credential and remote helpers.

**Comment by kjeremy** [comment]
Should the keys go under HKCU instead if installed for the local user?

**Comment by mikofski** [comment]
+1 @kjeremy just ran into this issue, yes please use `HKCU` if installing in `~/AppData/Local/Git`

**Comment by dscho** [comment]
@mikofski ummm.... wrong ticket????

**Comment by dscho** [comment]
@mikofski a *little* research would be nice: it is not even far away, it is the third most recent updated (and already fixed!) issue: https://github.com/git-for-windows/git/issues/455

**Comment by mikofski** [comment]
@dscho so sorry about that. comment nixed. :)

**Comment by dscho** [comment]
@mikofski that's not what I asked... I asked to comment on the correct ticket. @kjeremy also commented here by mistake, but then went on to open that new ticket, and things were resolved. The trick about mistakes is not to hide them, but to learn from them...
