### ISSUE TITLE
Version 2.39.2 introduces annoying "Waiting for data..." bar at bottom of screen

### ISSUE THREAD

**Issue by kaiyoma** [git-for-windows/git#4289]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.1.windows.1
cpu: x86_64
built from commit: b03dafd9c26b06c92d509a07ab01b01e6d0d85ee
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 11 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1265]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ 

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash via Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git grep
```
 - What did you expect to occur after running these commands?

No weird message

 - What actually happened instead?

![image](https://user-images.githubusercontent.com/10719780/218879892-5082297e-346d-424e-9bc8-58b95a0ed889.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by kaiyoma** [comment]
I downgraded to 2.39.1 and confirmed that the "Waiting for data..." message no longer appears.

**Comment by dscho** [comment]
This is an intentional change in `less`, apparently: https://github.com/gwsw/less/commit/a5bdb609aa33605eee544ab4fa24524d8f41b1da. I do not see any option for turning it off; If you want one, it might be the best idea to register your wish with that project.

**Comment by rimrul** [comment]
> This is an intentional change in `less`, apparently: https://github.com/gwsw/less/commit/a5bdb609aa33605eee544ab4fa24524d8f41b1da. I do not see any option for turning it off; If you want one, it might be the best idea to register your wish with that project.

That's just about adding the "^X or " bit in the parantheses. The first part of that Message is in `less` since the first commit dated 1994.

**Comment by dscho** [comment]
> That's just about adding the "^X or " bit in the parantheses. The first part of that Message is in `less` since the first commit dated 1994.
> 
> [gwsw/less@fe6f798](https://github.com/gwsw/less/commit/fe6f798541833aac6d69e6568debc4bcf474312c)

@rimrul thank you for double-checking my claims, I missed that.
