### ISSUE TITLE
Include `$HOME\bin` into Git's `PATH` when launched from `/cmd/git.exe`

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#429]
We should teach the Git wrapper to not only add `/mingw../bin;/usr/bin/` but also `$HOME/bin` to the `PATH`. That way, users can install additional executables and scripts into their `%USERPROFILE%\bin` folder and they will be picked up not only from Git Bash, but also from Git CMD, and really from every application that uses `/cmd/git.exe` to call Git for Windows.

This is particularly useful when users want to install their add-on remote and/or credential helpers.

**Comment by bviktor** [comment]
Nice!

**Comment by dscho** [comment]
> Does this mean that I only need to add the cmd folder to PATH and everything will be available?

No, it just means that Git will find the executables in `$HOME/bin/`. It won't find *everything* :stuck_out_tongue_winking_eye:

**Comment by bviktor** [comment]
> not only add /mingw../bin;/usr/bin/ but also $HOME/bin

Fair enough ;)
