### ISSUE TITLE
cygwin_exception when cloning git repo over ssh with PKCS11Provider

### ISSUE THREAD

**Issue by dzhus** [git-for-windows/git#4296]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

#### Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
PS C:\Users\dima\AppData\Roaming> git --version --build-options
git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

#### Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

PS C:\Users\dima\AppData\Roaming> cmd.exe /c ver

Microsoft Windows [version 10.0.22621.1105]
```

#### What options did you set as part of the installation? Or did you choose the defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

PS C:\Users\dima\AppData\Roaming> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

#### Any other interesting things about your environment that might be related to the issue you're seeing?

I am trying to use YKCS11 lib to use my SSH key stored on my Yubikey.

My `~/.ssh/config` is:
```
PKCS11Provider "C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll"
```

When using ssh for Windows (OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3) to authenticate with hosts that have the corresponding public key, it works fine. The problem arises only when I am using git for Windows (which I think bundles its own ssh.exe?)

#### Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

#### What commands did you run to trigger this issue?

```
git clone git@github.com:dzhus/dotfiles.git
```

#### What did you expect to occur after running these commands?

Git repository being cloned.

#### What actually happened instead?

```
Cloning into 'dotfiles'...
      0 [main] ssh 491 cygwin_exception::open_stackdumpfile: Dumping stack trace to ssh.exe.stackdump
fatal: Could not read from remote repository.
```

Attached is the stack trace dump:

<details>
<summary>ssh.exe.stackdump</summary>

```
cat ssh.exe.stackdump 
Exception: STATUS_ACCESS_VIOLATION at rip=00100478811
rax=00007FFCDA449000 rbx=00000008000B11E0 rcx=0000000000000000
rdx=000000000000003A rsi=00000000FFFFB298 rdi=00000000FFFFB2A0
r8 =FFFFFFFFFFFF1C10 r9 =0000000000000000 r10=0000000000000000
r11=0000000000000000 r12=00000008000A2D00 r13=00007FFCDA420000
r14=0000000000000000 r15=0000000000000000
rbp=00007FFCDA42B9B0 rsp=00000000FFFFB040
program=C:\Program Files\Git\usr\bin\ssh.exe, pid 491, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
7FFCDA42B9B0  00100478811 (0080009E730, 000000303E9, 00000000000, 00100000001)
008000A2880  0010049F01A (000FFFFCC30, 000FFFFCC30, 00000000030, 00000000000)
000FFFFCD30  00210049B91 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00210047716 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  002100477C4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```
</details>

#### If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Only tested with Github repositories.

**Comment by dzhus** [comment]
This looks like an issue with ssh bundled with git for Windows rather than git itself. I can work around it via 
```
 $env:GIT_SSH="C:\Windows\System32\OpenSSH\ssh.exe"
 git clone git@github.com:dzhus/dotfiles.git
```

As such this turns out to not be a pressing issue for me. I'm happy to help debug the original problem though.

**Comment by dscho** [comment]
Could you test whether the same issue arises with [Cygwin](https://cygwin.com/)'s `ssh.exe`?

**Comment by dzhus** [comment]
Indeed, I can reproduce the issue with `ssh` from Cygwin:

```
PS > C:\cygwin64\bin\ssh.exe -I "C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll" git@github.com
      0 [main] ssh 1271 cygwin_exception::open_stackdumpfile: Dumping stack trace to ssh.exe.stackdump
PS > C:\cygwin64\bin\ssh.exe -V
OpenSSH_9.2p1, OpenSSL 1.1.1s  1 Nov 2022
```
(ssh from Windows works fine with the above example (OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3))

**Comment by dscho** [comment]
> I can reproduce the issue with `ssh` from Cygwin

Good. Please follow the guidelines at https://cygwin.com/problems.html and report the problem there.
