### ISSUE TITLE
Error when core.editor is set to notepad but format.commitMessageColumns not set

### ISSUE THREAD

**Issue by bdukes** [git-for-windows/git#430]
I had been using notepad as my editor without any problem, but after upgrading to 2.5.3, I get an error after saving a commit message:

>fmt: invalid width: ''
>error: There was a problem with the editor 'notepad'.
>Please supply the message using either -m or -F option.

Calling ` git config --global format.commitMessageColumns 80` caused the error to go away

**Comment by dscho** [comment]
Oops. Thanks for the report!
