### ISSUE TITLE
Block rename folder after closing git in cmd.

### ISSUE THREAD

**Issue by barkep** [git-for-windows/git#4307]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1265]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option:  
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git stash
```
 - What did you expect to occur after running these commands?
 - 
The command works fine.

 - What actually happened instead?

After closing cmd, the process "Git for windows" remains in the task manager, which blocks the ability to rename the folder from the repository and parent folders. After killing the process everything works fine.

**Comment by dscho** [comment]
> the process "Git for windows" remains in the task manager

That's most likely because of:

> Enable FSMonitor: Enabled

The FSMonitor is expected to keep running. You can stop it gracefully by calling `git fsmonitor--daemon stop` in the worktree.

**Comment by barkep** [comment]
Thanks for the help. After changing to "Enable FSMonitor: Disabled" it works fine.
