### ISSUE TITLE
Problem with Git 2.5.3 "Start In" folder location

### ISSUE THREAD

**Issue by qcGold** [git-for-windows/git#431]
Hi, I just downloaded the latest Git release; 2.5.3 and I can't seem to make the Git Bash open in my correct projects folder.

I go to `Properties` > `Start in`
and add a valid Path: `C:\Users\*me*\Desktop\Projects` 
but it still opens in my Document (default folder) instead of the specified folder.

**Comment by dscho** [comment]
Are you talking about the *Start Menu* item called *Git Bash*? If so, please note that the value of `Properties>Target` reads:

```
"C:\Program Files\Git\git-bash.exe" --cd-to-home
```

(or similar). If you remove the `--cd-to-home` parameter, it will probably start working as you would like it.

However, please note that these settings will be overwritten during the next install/upgrade.

**Comment by maoueh** [comment]
Another trick is to use your `~/.bash_profile` at your advantage. From Git Bash:

```
echo 'cd ~/Desktop/Projects` >> ~/.bash_profile
```

Then, when you will start Git Bash again, it will directly change directory to `~/Desktop/Projects`.

**Comment by dscho** [comment]
@maoueh a good trick, but please note that the `Git Bash Here` context menu entry in the Windows Explorer extension will stop working properly if you do that.

**Comment by maoueh** [comment]
@dscho Indeed, I did not think of that. Thanks for mentioning it as a disadvantage (and a problem for standard use cases).

**Comment by dscho** [comment]
@maoueh I like the simplicity of your solution, though. Hopefully you will keep them coming!

**Comment by qcGold** [comment]
Thanks for both your responses, highly appreciated :)
