### ISSUE TITLE
Winget MinGit installation faulty Path environment variable

### ISSUE THREAD

**Issue by abtesk** [git-for-windows/git#4319]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

fails to run
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1265]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
winget install MinGit
```

Winget installs Version: 2.39.2.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git
```
 - What did you expect to occur after running these commands?

The git manpage to appear after restarting the terminal.

 - What actually happened instead?

Error message, `git` is not found in the path. When checking the Path environment variable, following path is added for MinGit
```
~\AppData\Local\Microsoft\WinGet\Packages\Git.MinGit_Microsoft.Winget.Source_8wekyb3d8bbwe
```
missing the final bit `\cmd`.

This is easily fixed for personal use on an individual basis, of course, by simply modifying the path. But I would like to integrate this installation in a setup for staff and make the installation as simple as possible.

**Comment by rimrul** [comment]
>  - What actually happened instead?
> 
> Error message, `git` is not found in the path. When checking the Path environment variable, following path is added for MinGit
> ```
> ~\AppData\Local\Microsoft\WinGet\Packages\Git.MinGit_Microsoft.Winget.Source_8wekyb3d8bbwe
> ```
> missing the final bit `\cmd`.

MinGit probably should't be on the `PATH`, since it is not intended for interactive use. Either way, the WinGet package is not provided by Git for Windows and the underlying MinGit zip file does not modify your `PATH` at all. This is not a Git for Windows issue. Feel free to open an issue at https://github.com/microsoft/winget-pkgs/issues.

**Comment by abtesk** [comment]
Sorry for my confusion. Thank your for your help!

If I may ask, I did read that MinGit is meant for applications instead of interactive use. Would you say MinGit is valid to use in combination with VSCode?

Alternatively, (I ask because I want to make the installation as simple as possible for new users) is it possible to modify the installation options of proper Git for Windows through the command line? Such that, I can set `--override` in `winget`?

(If it is inappropriate to ask here and it makes sense, I can open a new issue.)
