### ISSUE TITLE
Cannot create branch named #!/bin/sh

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#432]
Git for Windows 2.5.3 x64
Win 7

I want to create a branch named `#!/bin/sh` in Git Bash, but it failed.
Using Windows Command Prompt is OK.

I tried several escape strings but did not succeed.

Git Bash Win64
```
$ git branch #!/bin/sh
* master
$ echo $?
0
# branch actually not created
```

Git Bash Win64
```
$ git branch \#\!/bin/sh
fatal: '#!C:/Program Files/Git/usr/bin/sh' is not a valid branch name.
```

Git Bash Win64
```
$ git branch "\#\!/bin/sh"
fatal: '\#\!/bin/sh' is not a valid branch name.
```

Git Bash Win64
```
$ git branch "#!/bin/sh"
bash: !/bin/sh: event not found
```

Windows Command Prompt
```
C:\git>git branch #!/bin/sh
C:\git>git branch
  #!/bin/sh
* master
```

**Comment by dscho** [comment]
Yes, it is important to keep Bash (and MSys2!) operators in mind. You ran into

- `#`: comment
- MSys2 path mangling, converting POSIX paths to Windows ones
- `'...'`: special quote that leaves even backslashes intact
- `!`: history lookup

In short: you demonstrated in a fine way why it is a splendid idea to keep to letters, digits and dashes when inventing branch names.

Besides, wisely chosen branch names usually carry much more intuitively-understood meaning than `%4!*&` or `#!/bin/sh`

**Comment by dscho** [comment]
For the record, a double slash or `MSYS_NO_PATHCONV` would have fixed the operation. but the branch name still would convey pretty little meaning.
