### ISSUE TITLE
REST API Calls to Bitbucket Missing Context Path

### ISSUE THREAD

**Issue by drolander** [git-for-windows/git#4332]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.1574]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: C:\Users\drolander\_Apps\SublimeText\sublime_text.exe
Default Branch Option: develop
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Our Bitbucket URL: https://jira.mycompany.com/stash

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash and CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch --all
```
 - What did you expect to occur after running these commands?

Our bitbucket server has a context path for stash (aka bitbucket) off of the same host used for Jira. For example, our jira URL is https://jira.mycompany.com and our bitbucket server URL is https://jira.mycompany.com/stash. I would expect the git command would execute properly by calling the Bitbucket REST API including the context path in the URL.

 - What actually happened instead?

 With GIT_TRACE and GCM_TRACE set to 1, I can see that the REST endpoints are being called with only the host name and not the context path. This is resulting in failed or incorrect results.

```
Example:
https://jira.mycompany.com/rest/api/1.0/users should be https://jira.mycompany.com/stash/rest/api/1.0/users

git.c:460               trace: built-in: git fetch --all
run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin https://jira.mycompany.com/stash/scm/gis/myproject.git

...tbucketRestApi.cs:52 trace: [GetUserInformationAsync] HTTP: GET https://jira.mycompany.com/rest/api/1.0/users
...tbucketRestApi.cs:55 trace: [GetUserInformationAsync] HTTP: Response 401 [Unauthorized]
...tHostProvider.cs:422 trace: [ValidateCredentialsWork] Failed to validate existing credentials using Basic Auth
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It happens with all repositories

**Comment by rimrul** [comment]
> ...tbucketRestApi.cs:52 trace: [GetUserInformationAsync] HTTP: GET https://jira.mycompany.com/rest/api/1.0/users
> ...tbucketRestApi.cs:55 trace: [GetUserInformationAsync] HTTP: Response 401 [Unauthorized]
> ...tHostProvider.cs:422 trace: [ValidateCredentialsWork] Failed to validate existing credentials using Basic Auth

That issue seems to be in [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager). It sounds like it might be related to https://github.com/git-ecosystem/git-credential-manager/issues/807

**Comment by dscho** [comment]
> Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

Or even better: the latest release candidate at https://github.com/git-for-windows/git/releases/tag/v2.40.0-rc2.windows.1

**Comment by drolander** [comment]
Thanks for the quick replies, but I just tried the RC and I am still having the same problem. The issue is with this call:

```
...tHostProvider.cs:393 trace: [ValidateCredentialsWork] Validate credentials (drolander/********) are fresh for https://jira.mycompany.com/ ...
...tbucketRestApi.cs:52 trace: [GetUserInformationAsync] HTTP: GET https://jira.mycompany.com/rest/api/1.0/users
```

That is not a valid URL. It returns:

```
<status>
<status-code>404</status-code>
<message>null for uri: https://jira.mycompany.com/rest/api/1.0/users</message>
</status>
```

If I manually make the call with a "stash" context path in it it works:

```
https://jira.mycompany.com/stash/rest/api/1.0/users
returns:
{"size":25,"limit":25,"isLastPage":false,"values":[{"name": [...]
```

and if I add my user id you can see that I am in the users list:

```
https://jira.mycompany.com/stash/rest/api/1.0/users/drolander
returns

{"name":"drolander","emailAddress":"Dan.Rolander@mycompany.com","id":nnnn,"displayName":"Dan Rolander","active":true,"slug":"drolander","type":"NORMAL","links":{"self":[{"href":"https://jira.mycompany.com/stash/users/drolander"}]}}
```

When this occurs, it prompts me for my credentials, even though it initially found them in the credential manager, tries to connect with the newly entered creds, the connection times out after 5 minutes, then it attempts to reconnect and issue another request and at that point it ultimately succeeds. Interestingly, on the reconnect it does not send the call to `/rest/api/1.0/users` again. Is there a way to prevent that step from occuring to begin with (i.e. GetUserInformationAsync)?

**Comment by drolander** [comment]
I found the solution [here](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/environment.md#gcm_bitbucket_validate_stored_credentials).

Setting this:  SET GCM_BITBUCKET_VALIDATE_STORED_CREDENTIALS=0

Fixes the issue.
