### ISSUE TITLE
ssh-add ~/.ssh/ not working

### ISSUE THREAD

**Issue by wboswall** [git-for-windows/git#4333]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64 bit

```
$ git --version --build-options
git version 2.39.2.windows.1
```
git version 2.39.2.windows.1

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

windows 11 64 bit

```
$ cmd.exe /c ver
git bash
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 i chosed the defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
```
$ ssh-add ~/.ssh/id_ed25519
/c/Users/wbosw/.ssh/id_ed25519: No such file or directory
```

 - What did you expect to occur after running these commands?

for the ssh key to go into my .ssh folder
instead I had to manually cut and paste them into the directory and then ran the command again and then it worked but I already added it so it was useless.  

 - What actually happened instead?

It couldn't see the ssh key and therefore No such file or directory

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

As far as I know or think it is only affecting one repo but not sure.  

I assume it's just this one git@github.com:wboswall/unb-bootcamp.git

**Comment by rimrul** [comment]
> ```
> $ ssh-add ~/.ssh/id_ed25519
> /c/Users/wbosw/.ssh/id_ed25519: No such file or directory
> ```
> 
>  - What did you expect to occur after running these commands?
> 
> for the ssh key to go into my .ssh folder

That's simply not what [`ssh-add`](https://manpages.ubuntu.com/manpages/xenial/man1/ssh-add.1.html) does.

> instead I had to manually cut and paste them into the directory and then ran the command again and then it worked

So it's working as intended.

**Comment by dscho** [comment]
In case the purpose of `ssh-add` is still unclear, see e.g. https://superuser.com/a/360706 and https://linux.die.net/man/1/ssh-add:

> `ssh-add` adds private key identities (from your `~/.ssh` directory) to the authentication agent (`ssh-agent`), so that the ssh agent can take care of the authentication for you, and you don't have type in passwords at the terminal.

**Comment by wboswall** [comment]
@dscho Well I guess Github's steps on adding ssh keys are wrong.  Could you give me the right way in adding the ssh key?  I did the exact same thing as the command should have done, and it worked.

**Comment by dscho** [comment]
> I guess Github's steps on adding ssh keys are wrong.

Link, please?
