### ISSUE TITLE
installer: does not create file-association for `.gitconfig` files

### ISSUE THREAD

**Issue by skaravos** [git-for-windows/git#4337]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.2604]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# defaults
```

### Details

The [`install.iss`](https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss) script creates registry entries that mark `.gitattributes`, `.gitignore` and `.gitmodules` as plain text. This is great as it allows these files to be opened by the default editor when double-clicked in file explorer.

However, it does not create a file association for `.gitconfig` files.
This *appears* to be a deliberate choice as there is a [comment](<https://github.com/git-for-windows/build-extra/blob/ce89f8e0754854aa11846816e7cc46a981849c17/installer/install.iss#L188>) in the install script where the registry entries are defined that says:

> ; File associations for configuration files that may be contained in a repository (so this does not include ".gitconfig").

Why was the decision made to single out the `.gitconfig` file as the one git file extension not deserving of a file-association?

**Comment by dscho** [comment]
> Why was the decision made to single out the `.gitconfig` file as the one git file extension not deserving of a file-association?

Let's have a look at [`View git blame`](https://github.com/git-for-windows/build-extra/blame/ce89f8e0754854aa11846816e7cc46a981849c17/installer/install.iss#L188). It first leads to https://github.com/git-for-windows/build-extra/commit/6bed1bce83736b09b7db42c91e78df9d9f31791e. Following the file to its parent, we can see that [the final git blame](https://github.com/git-for-windows/build-extra/blame/5875e44af9b52fad5a0ae1a2094632e283de1530/installer/install.iss.in#L127) says that this file [was copied from msysGit (i.e. Git for Windows 1.x' SDK)](https://github.com/git-for-windows/build-extra/commit/3f5ad4910a9694021bbb9fe0671f44dfb04c8ae2). We can follow the `git blame` there, too: https://github.com/msysgit/msysgit/blame/master/share/WinGit/install.iss#L110. This leads to https://github.com/msysgit/msysgit/commit/360eded25a80b3b255467c82c06864693a54577d and I admit that this commit message leaves me wanting. It talks about an "issue 397", but back in 2010 we were using Google Code (remember that site? Long [gone](https://code.google.com/archive/p/msysgit/)...), so we have no record. Booh.

**Comment by skaravos** [comment]
Wow, wasn't expecting such a quick response!
I appreciate the sleuthing effort, as well as the nicely hyperlinked trail. It's always interesting to poke back through time. 
It's a shame it lead to a dead-end in this case.

This isn't really a high priority item and I have no strong feelings either way on whether the `.gitconfig` file should actually have a file-association added. I just stumbled upon this curiosity while creating a PR for [scoop](https://github.com/ScoopInstaller/Main/issues/4462).

I leave it up to you whether to close as "Won't Fix".

**Comment by dscho** [comment]
I think I'll just leave this as a "Won't Fix" lest I introduce problems for users who already associated the `.gitconfig` file with something different, such as an INI viewer.
