### ISSUE TITLE
Git doesn't look for correct .ssh folder when terminal is launched from SourceTree

### ISSUE THREAD

**Issue by theodorejb** [git-for-windows/git#434]
When I manually open a command prompt and run Git, it correctly picks up the public/private key and known hosts in the .ssh folder in my user profile.

However, when I open the Git console by clicking the Terminal button in SourceTree, push/pull/fetch doesn't work since it appears to be looking for a .ssh folder in the root of the C: drive.

I think this is a bug in Git since it worked perfectly in version 2.5.2, but stopped working after I upgraded to Git 2.5.3 (SourceTree hasn't changed).

**Comment by dscho** [comment]
Searching for the term "sourcetree" in the GitHub issues reveals that there is already a ticket for this: https://github.com/git-for-windows/git/issues/414
