### ISSUE TITLE
Scrolling text input locks terminal when window is resized

### ISSUE THREAD

**Issue by jgwinner** [git-for-windows/git#4340]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I checked

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
[C:\c] git --version --build-options

git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10, 64 bit. 
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2673]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: CmdTools
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

It seems to be any command shell - but only on Windows. WSL worked fine, for example.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I tried nearly everything. 
CMD/PowerShell/TCC (4NT / 4DOS's successor). 

Same results

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

1. Go into a folder for a project with a lot of branches.
2. Make sure your window is default size or at least smaller than the amount of text expected.
3. Generate a lot of text, so git's scrolling (less like) triggers. e.g.

```
git branch -a -v
```

4. Assuming you have output that has to be paged, _before_ paging, resize the window.

 - What did you expect to occur after running these commands?

I expected the window to resize, and the paging to adjust, or at least continue if I press the space bar. Or even exit the git command if I entered a break.

 - What actually happened instead?

It locks up the command window. It's as if it's expecting input, but never receives it. Even break doesn't do anything. The `:` also disappears.

Note that resizing a scrolling window works fine with WSL / Ubuntu. It also works fine with a PC port of 'less'. 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Seems like all repo's, but you do need a repo with a lot of branches. 

Oh, this one seems to overwhelm a standard size command window:
bitbucket.org/wowmodelviewer/wowmodelviewer.git 

Note that if you resize the window ahead of time so that there is no scrolling, the bug doesn't trigger, keyboard input resumes.

**Comment by dscho** [comment]
> CMD/PowerShell/TCC (4NT / 4DOS's successor).

I tried with [the most recent release candidate](https://github.com/git-for-windows/git/releases/tag/v2.40.0-rc2.windows.1) of Git for Windows, using a regular `Git CMD` and it does not hang up for me. Could you try the same Git for Windows version?

**Comment by jgwinner** [comment]
Sure! Doing that now.

Funny as after posting that an update request popped up. I'll try both.

Ah, looks like the most recent release fixed the ability to continue scrolling, but typing "q" to quit still locks up the terminal.

The RC fixes both issues! I'll close this issue. 

Thank you!

== John ==
