### ISSUE TITLE
Installer GUI bugs for Git-2.39.2-64-bit.exe on Windows 10, 64-bit

### ISSUE THREAD

**Issue by is-eouellette** [git-for-windows/git#4345]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options

git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

10, 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2673]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I just installed Git using Git-2.39.2-64-bit.exe on Windows 10.
Windows' OpenSSL was added to my PATH, and Git was NOT added to my
PATH even though in the GUI config, I selected "Git from the command line
and also from 3rd party software" and "Use bundled OpenSSH"

Would you please fix these issues in the next release?
Thanks, Ed

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```

 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

Hi,
I just installed Git using Git-2.39.2-64-bit.exe on Windows 10.
Windows' OpenSSL was added to my PATH, and Git was NOT added to my
PATH even though in the config, I selected "Git from the command line
and also from 3rd party software" and "Use bundled OpenSSH"

Would you please fix these issues in the next release?
Thanks,
Ed Ouellette

**Comment by dscho** [comment]
> Windows' OpenSSL was added to my PATH,

You mean `openssl.exe`? I am not aware of any such executable that would be shipped with Windows out of the box.

> and Git was NOT added to my PATH

That is strange. We extend `PATH` [here](https://github.com/git-for-windows/build-extra/blob/ce89f8e0754854aa11846816e7cc46a981849c17/installer/install.iss#L3231-L3258), handing of to [this code](https://github.com/git-for-windows/build-extra/blob/ce89f8e0754854aa11846816e7cc46a981849c17/installer/environment.inc.iss#L56-L115) to configure the environment variable.

Could you have a look at the `Path` key in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment` and see whether `C:\Program Files\Git\cmd` was added to it?

**Comment by rimrul** [comment]
> > Windows' OpenSSL was added to my PATH,
> 
> You mean `openssl.exe`? I am not aware of any such executable that would be shipped with Windows out of the box.

They're probably talking about `OpenSSH`, which is on the `PATH` by default.

**Comment by is-eouellette** [comment]
Yes, "C:\Program Files\Git\cmd" was added to my PATH environment variable.
Yes, I meant OpenSSH, not OpenSSL.
"C:\Windows\System32\OpenSSH\" is listed in my PATH before "C:\Program
Files\Git\cmd"

Thanks,
Ed

**Comment by rimrul** [comment]
> Yes, "C:\Program Files\Git\cmd" was added to my PATH environment variable.

There should be a `git.exe` In that folder, which would mean that Git is on your `PATH`.

> "C:\Windows\System32\OpenSSH\" is listed in my PATH before "C:\Program
> Files\Git\cmd"

That's pretty normal. Windows adds "C:\Windows\System32\OpenSSH\" by default and we append "C:\Program
 Files\Git\cmd" later.

**Comment by is-eouellette** [comment]
Since "C:\Windows\System32\OpenSSH" is listed in my PATH first, before
"C:\Program
Files\Git\cmd", doesn't that mean that OpenSSH will use the Windows
version, and not the one found in Git for Windows (as I had selected
during install)?

Thanks,
Ed

**Comment by rimrul** [comment]
When you run `ssh` from `CMD`? Yes. When Git runs `ssh`? No, thanks to some trickery where we put the paths we need to the front for our processes.

**Comment by is-eouellette** [comment]
I see, thanks for the helpful explanation.

**Comment by dscho** [comment]
I guess that closes this ticket.
