### ISSUE TITLE
Git cannot be used under system account.

### ISSUE THREAD

**Issue by VHaravy** [git-for-windows/git#435]
When I attempt to run Git from Windows command line under Windows system account (e.g. `psexec /s /i cmd` and then `git pull` from command prompt) I get the following error:

```
C:\Projects\Test>git pull
Could not create directory '/home/SYSTEM/.ssh'
```

With MSYSGit run under system account all paths defaulted to `C:\Program Files (x86)\Git` (e.g. `C:\Program Files (x86)\Git\.ssh\known_hosts`).

**Comment by dscho** [comment]
Does this account not have a proper `%USERPROFILE%`?

**Comment by VHaravy** [comment]
```

**Comment by kostix** [comment]
On a side note, running Git under the system account is really ill-considered. @VHaravy, consider creating a dedicated regular local user account for this task or at least using LOCAL SERVICE account rather than LOCAL SYSTEM.

**Comment by dscho** [comment]
Not that I think it is a good idea, but now I am curious to know *just how* you get to run Git Bash as `SYSTEM`?

**Comment by kostix** [comment]
@dscho, `psexec` is a tool from the (must-have IMO) suite called [Sysinternals](https://technet.microsoft.com/en-us/sysinternals/bb842062).

When run with the `-s` command-line option and without the remote host to connect to, it spawns the specified command locally using the system account.

You must be an administrator, of course.

**Comment by dscho** [comment]
Thanks @kostix; I knew about the Sysinternals tools, of course (I use them *extensively* when debugging Git for Windows issues), but somehow I doubt that @VHaravy used `psexec`.

**Comment by kostix** [comment]
@dscho, surely they did -- re-read the original bug report ;-)

**Comment by dscho** [comment]
Whoops, you're correct. Somehow it did not register that the PSTools were used. FWIW this is what I get:

```sh
me@work $ whoami
SYSTEM
me@work $ cd
me@work $ pwd -W
C:/windows/system32/config/systemprofile
me@work $
```

**Comment by dscho** [comment]
Ah, but `ssh` sees the wrong home directory:

```sh
me@work $ ssh git@bitbucket.org
Could not create directory '/home/SYSTEM/.ssh'.
The authenticity of host 'bitbucket.org (131.103.20.168)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by VHaravy** [comment]
Originally the problem was encountered when I tried to upgrade Git on Windows machine running Jenkins Slave installed as a service under local system account.

**Comment by dscho** [comment]
Ah, now that makes sense! Thanks for that information!

FWIW I am in the middle of debugging why the home directory is wrong (as far as `ssh` is concerned, as I demonstrated `$HOME` is fine).

**Comment by dscho** [comment]
BTW please feel generous about providing such background information in future bug reports. It really helps assess the priorities.
