### ISSUE TITLE
Git Gui Error: explorer.exe not found in PATH

### ISSUE THREAD

**Issue by deanwiles** [git-for-windows/git#4356]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? `64-bit`

```
$ git --version --build-options

git version 2.40.0.windows.1
cpu: x86_64
built from commit: 1d90ca2906dd4b7ddaf0669a13c173ec579d794a
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
![image](https://user-images.githubusercontent.com/4119940/226638559-674b73db-6e7e-4063-9f9d-6179a00c788f.png)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? `64-bit`

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2728]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

> I have reproduced this error on multiple PCs running Windows 10, 64-bit Git Gui. 
> The error was first noticed in Git version 2.39.1 and later versions (2.39.2, 2.40.0), but worked correctly in Git version 2.38.1. (I have not tried other 2.38.x versions to see exactly when it started.)
> 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Gui

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
1. Launch Git Gui
2. Open an existing repository
3. From the Menu bar, select Repository > Explore Working Copy
```
 - What did you expect to occur after running these commands?

Windows Explorer used to open showing the repository root directory and files.

 - What actually happened instead?

This error dialog was displayed:
![image](https://user-images.githubusercontent.com/4119940/226641470-5a8fa029-dbbe-40de-bec5-de1e482f0491.png)

Expanding the Details>> shows:
![image](https://user-images.githubusercontent.com/4119940/226641717-184dee88-ab31-4d7c-80a1-dd19ac2d5924.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Error occurs with multiple repositories.

**Comment by Hattes** [comment]
I had the same issue, and the suggested fix worked for me.

**Comment by dscho** [comment]
/add relnote bug Git GUI's `Repository>Explore Working Copy` [was broken since v2.39.1](https://github.com/git-for-windows/git/issues/4356), which has been fixed.

**Comment by dscho** [comment]
@Hattes @deanwiles please note that the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) has the fix. Git for Windows' snapshots are identical to full releases except for the funny-looking version number. In all other respects, I consider snapshots like "micro releases", as I aim to keep the main branch in an always-releasable state. So maybe you want to run with the latest snapshot until the next full Git for Windows version is released?
