### ISSUE TITLE
Feature: Allow to stash push and pop file modification times to avoid rebuilds

### ISSUE THREAD

**Issue by ridilculous** [git-for-windows/git#4358]
`git stash push`
later followed by
`git stash pop`
does restore files but doesn't restore file modification times.

It would be great if there would be an option to opt in for stashing and restoring the file modification times because not restoring them potentially triggers rebuilds for many IDEs (MSVC in my case) which can be quite expensive for big projects.

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
