### ISSUE TITLE
maybe we can persist the bash.bashrc file into the user directory?

### ISSUE THREAD

**Issue by lijian12345** [git-for-windows/git#4379]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** 2.40.0.windows.1 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** 10.0.22621.1485 **
```

This is not a bug report, just a discussion. I often used scoop to install git, and I noticed that the bash.bashrc file is put into the software root directory. Then everytime we upgrade git, we must copy the old bash.bashrc file to the new software root directory. It seems not that convenient, so maybe we can persist the bash.bashrc file into the win user directory?

**Comment by rimrul** [comment]
It seems like `~/.bashrc` Is what youre lolking for.

**Comment by lijian12345** [comment]
> It seems like `~/.bashrc` Is what youre looking for.

yeah, this actually worked. But after set this, when I opend bash on the first time, it reported an error and generated a file named `.bash_profile`. Thus next time I open bash, everything looks fine. If only these files are auto-generated.

**Comment by dscho** [comment]
> this actually worked. But after set this, when I opend bash on the first time, it reported an error

I _highly_ doubt that it was an error: https://github.com/git-for-windows/git-sdk-64/blob/HEAD/etc/profile.d/bash_profile.sh clearly renders this as a _warning_.

In any case, this seems to have been addressed.
