### ISSUE TITLE
printf of the included bash is bugged

### ISSUE THREAD

**Issue by ale5000-git** [git-for-windows/git#4381]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.40.0 64-bit
```
$ git --version --build-options

git version 2.40.0.windows.1
cpu: x86_64
built from commit: 1d90ca2906dd4b7ddaf0669a13c173ec579d794a
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Versione 10.0.19045.2788]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash of Git for Windows

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

The sh files are associated to "C:\Program Files\Git\usr\bin\bash.exe"
I double click on this script (saved as shelltest.sh):
```
#!/usr/bin/env sh

readonly SCRIPT_SHORTNAME='Test'
readonly SCRIPT_VERSION='0.2'

printf '%s\n' "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<!--
    SPDX-FileCopyrightText: none
    SPDX-License-Identifier: CC0-1.0
    SPDX-FileType: SOURCE
-->

<!-- Generated by ${SCRIPT_SHORTNAME:?} v${SCRIPT_VERSION:?} -->
"

IFS='' read 1>&2 -r -s -n 1 -p 'Press any key to continue...' _
```

 - What did you expect to occur after running these commands?

```
<?xml version="1.0" encoding="utf-8"?>
<!--
    SPDX-FileCopyrightText: none
    SPDX-License-Identifier: CC0-1.0
    SPDX-FileType: SOURCE
-->

<!-- Generated by Test v0.2 -->

Press any key to continue...
```

 - What actually happened instead?

```
<--
<-- Generated by ${SCRIPT_SHORTNAME:?} v${SCRIPT_VERSION:?} -->
<?xml version="1.0" encoding="utf-8"?>
<--
    SPDX-FileCopyrightText: none
    SPDX-License-Identifier: CC0-1.0
    SPDX-FileType: SOURCE
-->

<-- Generated by Test v0.2 -->

Press any key to continue...
```

**Comment by rimrul** [comment]
I notices it seems to not print the `!` in <!--`, so I've tested a stripped down version of your commands and entered it directly into Git Bash:

```bash
printf '%s\n' "<!--"
```

That gave me this error message:

`bash: !-: event not found`.

Googling that error message told me that there is bash history substitution at play here. You can disable the history substitution using `set +H` or escape the exclamation marks as `\!`.

**Comment by ale5000-git** [comment]
@rimrul
Looking over the internet I see that history substitution is enabled by default only in interactive shells, so why here is enabled also for scripts?
