### ISSUE TITLE
git clone not honoring -q

### ISSUE THREAD

**Issue by jeremiahmoree-adot** [git-for-windows/git#4387]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 64-bit?

```
$ git --version --build-options

git version 2.40.0.windows.1
cpu: x86_64
built from commit: 1d90ca2906dd4b7ddaf0669a13c173ec579d794a
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.4131]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

tested Powershell and Tested in CMD 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd and powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cmd
C:\temp>git init foo
Initialized empty Git repository in C:/temp/foo/.git/

C:\temp>git clone -q foo bar
warning: You appear to have cloned an empty repository.

C:\temp>git clone -q foo bar7 2>throwawayfile.txt

C:\temp>type throwawayfile.txt
warning: You appear to have cloned an empty repository.

C:\temp>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\temp> git init baz
Initialized empty Git repository in C:/temp/baz/.git/
PS C:\temp> git clone -q baz buz
warning: You appear to have cloned an empty repository.
PS C:\temp> $WarningPreference = 'silentlycontinue'
PS C:\temp> git clone -q baz buz2
warning: You appear to have cloned an empty repository.
PS C:\temp> git clone -q baz buz3 | out-null
warning: You appear to have cloned an empty repository.
PS C:\temp> git clone baz buz8 2>.\throwawayfile2.txt
PS C:\temp> gc .\throwawayfile2.txt
git : Cloning into 'buz8'...
At line:1 char:1
+ git clone baz buz8 2>.\throwawayfile2.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cloning into 'buz8'...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

warning: You appear to have cloned an empty repository.
done.
```
 - What did you expect to occur after running these commands?

when using -q no output should show unless there is an actual error.  I would even live with NO output if there IS an error as the return code of the program should indicate the error and the -q should be honored--especially since the output is NOT an error.  it's just a warning.

 - What actually happened instead?

A message about the empty repo clone is always output--forcing post processing to handle this and potentially other cases.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

na

**Comment by rimrul** [comment]
> -q --quiet 

> Operate quietly. Progress is not reported to the standard error stream.

From  [git help clone](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt--q)

Like the documentation implies, `-q` on `git clone` only suppresses progress output.

**Comment by jeremiahmoree-adot** [comment]
Implies?  Should documentation imply or explicitly document behavior?

what constitutes progress?  Is a warning not part of progress? 

Is this a limitation of stream support?  In powershell warnings should be output to the appropriate stream.

**Comment by rimrul** [comment]
> Should documentation imply or explicitly document behavior?

Sure, it should. But Documentation isn't always perfect, and that sentence could be read like "Among other things, there is also no progress output.", but with `git clone` that  is really the only output that gets suppressed.

If you have an idea how to improve that documentation, I'm all ears.

> Is a warning not part of progress?

I wouldn't say so, no. I'd define progress output as output that makes it obvious how far along a certain long running process is. Like "downloading file 591/1200" or similar. 

The `git clone` command also does not seem to consider warnings something that gets affected by `q`. There are multiple warnings in `builtin/clone.c`, and none on them get suppressed by `-q`.

> Is this a limitation of stream support? In powershell warnings should be output to the appropriate stream.

I'm not quite sure I understand what you're talking about here. Are we talking about IO streams (`stdin`/`stdout`/`stderr`)? If so, `stderr` is the appropriate stream for warnings.

**Comment by jeremiahmoree-adot** [comment]
powershell has more than 3 io streams.  Warning is one of them.  The best place to send warning output is to the warning stream.   Since git is native to *nix and shells that have only 3 streams I understand the current behavior but don't like it for the same reason that powershell has more than 3 streams.     

Seems that we can close this bug as invalid or I can convert it to a request to have git on windows in powershell output warnings to the WARNING IO stream.

**Comment by dscho** [comment]
Indeed, Git is not a PowerShell component and therefore cannot use anything specific to PowerShell. If you care to look at https://learn.microsoft.com/en-us/windows/console/getstdhandle you will notice that there is nothing "*nix or shells" about having a standard input, a standard output and a standard error stream (and no warning stream).

If you want to improve Git's documentation, I encourage you to submit a patch to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
