### ISSUE TITLE
Git bash (2.40) works wrong under Windows 7-8 (unstable)

### ISSUE THREAD

**Issue by proxy-m** [git-for-windows/git#4388]
```
      1 [main] bash 442 dofork: child -1 - forked process 5116 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
                                         bash: fork: retry: Resource temporarily unavailable
```

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 
Windows 7, same under 8. **32-bit**.

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt (same error for other configs)
Editor Option: VIM
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled


** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Win 32 only

PS C:\Users\User> $PSVersionTable
[All updates installed. PS Just for info about system, I do not run from it.]
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Just start (or fork) Git Bash several times. You can answer me about windows memory protection, but I tried to disable it, wrong answer.

```
 - What did you expect to occur after running these commands?

Stable work!

 - What actually happened instead?
 
Periodically random error about forks, died unexpectedly, 0xC0000005, errno 11, retry: Resource temporarily unavailable ... (Cygwin.dll error on previous git bash versions with suggestion restart system every time.)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, it is not about repositories. It's about broken build.

**Comment by dscho** [comment]
> $ git --version --build-options
> 
> ** insert your machine's response here **

Do note that this is less helpful than necessary.

> I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
>
> 0xC0000005

You could have found this ticket, had you searched as instructed: https://github.com/git-for-windows/git/issues/1200

So I'll close this as duplicate, assuming that [the comment in the seemingly unrelated ticket about the 32-bit deprecation](https://github.com/git-for-windows/git/issues/4279#issuecomment-1509852809) means that this is about 32-bit more than about Windows 7 or 8.

**Comment by proxy-m** [comment]
May you fix the issue before closing?

**Comment by PhilipOakley** [comment]
> May you fix the issue before closing?

Help yourself. It's available. That's the beauty of open source. 😃
