### ISSUE TITLE
Git bash (2.40) works wrong under Windows 7-8 (totally unstable)

### ISSUE THREAD

**Issue by proxy-m** [git-for-windows/git#4392]
```
      1 [main] bash 442 dofork: child -1 - forked process 5116 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
                                         bash: fork: retry: Resource temporarily unavailable
```

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.40.0.windows.1
cpu: i686
built from commit: 1d90ca2906dd4b7ddaf0669a13c173ec579d794a
sizeof-long: 4
sizeof-size_t: 4
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 
Windows 7, same under 8. **32-bit**.

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt (same error for other configs)
Editor Option: VIM
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled


```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Win 32 only

PS C:\Users\User> $PSVersionTable
[All updates installed. PS Just for info about system, I do not run from it.]
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Just start (or fork) Git Bash several times. You can answer me about windows memory protection, but I tried to disable it, wrong answer.

```
 - What did you expect to occur after running these commands?

Stable work!

 - What actually happened instead?
 
Periodically random error about forks, died unexpectedly, 0xC0000005, errno 11, retry: Resource temporarily unavailable ... (Cygwin.dll error on previous git bash versions with suggestion restart system every time.)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, it is not about repositories. It's about broken build.

**Comment by dscho** [comment]
@proxy-m please at least _try_ to provide an _actual_ MCVE.

**Comment by rimrul** [comment]
This also seems like a verbatim duplicate of #4388.

**Comment by proxy-m** [comment]
Close instead fix. "Perfect".

**Comment by dscho** [comment]
> Close instead fix. "Perfect".

@proxy-m please note that this behavior is not tolerated here. After reading [this article](https://www.404media.co/xz-backdoor-bullying-in-open-source-software-is-a-massive-security-vulnerability/) I realize that I have been far too lenient in enforcing Git for Windows' [code of conduct](https://github.com/git-for-windows/git?tab=coc-ov-file#readme).

Even if this here ticket was not closed as a duplicate, even then, offering a snarky comment like this is incompatible with a welcoming and inspiring community.

If you want to help the project, that is definitely welcome. If you want to make people feel bad about lacking the time to address your problem, that's not acceptable. If you want to cheer on people to help you and motivate them to fix your problem, that's of course totally okay.
