### ISSUE TITLE
No puedo clonar un repositorio

### ISSUE THREAD

**Issue by Alfonso1954** [git-for-windows/git#4395]
Cuando intento clonar un repositorio, me aparece en la terminal de visual code, el siguiente mensaje:
acionscraping> git clone https://github.com/mariokarajallo/curso-webscraping.git
Cloning into 'curso-webscraping'...
fatal: unable to access 'https://github.com/mariokarajallo/curso-webscraping.git/': Failed , que debo hacer

**Comment by rimrul** [comment]
> When I try to clone a repository, I get the following message in the visual code terminal:

> acionscraping> git clone https://github.com/mariokarajallo/curso-webscraping.git

> Cloning into 'curso-webscraping'...

> fatal: unable to access 'https://github.com/mariokarajallo/curso-webscraping.git/': Failed , what should I do?

I assume you made sure you can access 
https://github.com in a browser on the affected machine. Are you using a proxy?

**Comment by dscho** [comment]
There is too little information (and most likely too much lost in translation) to have a prayer at helping.
