### ISSUE TITLE
Incorrect path resolution when folder name contains == at the end

### ISSUE THREAD

**Issue by chill-was-taken** [git-for-windows/git#4403]
- [*] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.40.1.windows.1
cpu: x86_64
built from commit: ceee26d5cac05a3437097b43d034c4ad2e99d571
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.22621.1555]
```

 - What options did you set as part of the installation?

```
$ cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from?

Bash through MINGW64 - the default one when installing Git Bash.

 - What commands did you run to trigger this issue?

```
# A minimal example that demonstrates the path resolution error for add, rm, and reset

mkdir double_equality_example && cd double_equality_example
git init
mkdir error_trigger== && cd error_trigger\=\=
echo "anything" > anyname.anyformat
cd ..

git add error_trigger\=\=/anyname.anyformat
# fatal: pathspec 'error_trigger==C:/Program Files/Git/anyname.anyformat' did not match any files

git add -A
# success

git rm --cached error_trigger\=\=/anyname.anyformat
# fatal: pathspec 'error_trigger==C:/Program Files/Git/anyname.anyformat' did not match any files

git commit -m "set up to demonstrate restore"
cat error_trigger\=\=/anyname.anyformat
# anything
echo "it works with echo and cat" > error_trigger\=\=/anyname.anyformat
cat error_trigger\=\=/anyname.anyformat
# it works with echo and cat

git restore  error_trigger\=\=/anyname.anyformat
# error: pathspec 'error_trigger==C:/Program Files/Git/anyname.anyformat' did not match any file(s) known to git

git restore 'error_trigger==/anyname.anyformat'
# same error pathspec

git restore "error_trigger==/anyname.anyformat"
# same error pathspec
```
Seems like `=/` resolves as `=C:/Program File/Git/` for some reason.
Further testing showed that if "==" is in the middle of the folder name, there are no problems.

 - What did you expect to occur after running these commands?

Git successfully uses commands `git add/rm/reset <file>`

 - What actually happened instead?

Git failed to resolve the path to the file correctly.

**Comment by dscho** [comment]
Hey @chill-was-taken, thank you for the report.

While it may look as if the equal signs are the culprit, that's only half of the truth. The topic is covered in [the release notes](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues):

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
>
>  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
>
>  Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "`//usr/bin/bash.exe`".

It may look as if there is no command-line parameter that starts with a slash, but the equal sign makes it look to the MSYS2 runtime as _if_ the slash before "anyname" _was_ the start of a command-line parameter.

Unfortunately, the path conversion implicitly performed by the MSYS2 runtime is both a crucial part of what makes the shell scripting part of Git work relatively smoothly as well as being fraught with ambiguities such as the reported one, where sometimes `MSYS_NO_PATHCONV` has to be called to the rescue.

**Comment by chill-was-taken** [comment]
Thank you for the info!
