### ISSUE TITLE
Installer incorrectly states that (effectively) `pull.rebase=false` is the default `git pull` behavior

### ISSUE THREAD

**Issue by kaste** [git-for-windows/git#4407]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```

$ git --version --build-options                                                                               
git version 2.40.1.windows.1                                                                                  
cpu: x86_64                                                                                                   
built from commit: ceee26d5cac05a3437097b43d034c4ad2e99d571                                                   
sizeof-long: 4                                                                                                
sizeof-size_t: 8                                                                                              
shell-path: /bin/sh                                                                                           
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1635]
```

On a new machine I installed git and followed without thinking the defaults.

It resulted in `system  pull.rebase=false` in the config.  

In https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss#L2262-L2284 
you state the default `git pull` behavior is "Default (fast-forward or merge)" which is not correct
if I'm not mistaken.  (Introduced via https://github.com/git-for-windows/build-extra/pull/287) 

Now, the default is obviously `not-set` and may print out nag messages, and you want to save the user
from the hassle.  But the default mode actually is `ff-only`, t.i. git will *not* print the nag messages
when a fast-forward is possible.  (See also https://git-scm.com/docs/git-pull#Documentation/git-pull.txt---ff-only)

I was bitten by the default here as I did a `git pull` on a dirty main branch just now which resulted in a merge 
commit.  I expected to fail in that case as I just forgot to start a feature branch as it seems.

Regards

**Comment by dscho** [comment]
> In https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss#L2262-L2284
> you state the default `git pull` behavior is "Default (fast-forward or merge)" which is not correct
> if I'm not mistaken. (Introduced via [git-for-windows/build-extra#287](https://github.com/git-for-windows/build-extra/pull/287))

How about opening a PR to fix it? (IIRC it used to be the default, but at some stage was "unmade the default".)

**Comment by Skylerspencer** [comment]
That's because it's made up by someone who just stole a contract from me on OK link second. Biggest amount I. The history of Ethereum Slot of things are being put in place S a cover up for theft  and fraud they just wiped out my pow and pos not going to work so you guys stop acting like your putting things in place to help me it's the opposite it you .who is vadlik that put his name on my Oklink when I told him they were trying cto act like they were burning my contract to keep the Ethereum and he turned around and changed ownership with himself being owner now?

**Comment by kaste** [comment]
Let's see if I'm green at https://github.com/git-for-windows/build-extra/pull/498
