### ISSUE TITLE
Git bash 'explorer here' does not open exact directory 

### ISSUE THREAD

**Issue by wahidshafique** [git-for-windows/git#441]
Is there a way to open up a sub folder directly? For example using the command on '~/Documents/BitBucket/Test' simply opens up 'Documents' in explorer mode.

**Comment by SEAPUNK** [comment]
`explorer $(cmd //c echo %cd%)`

**Comment by nak5124** [comment]
run 'start ~/Documents/BitBucket/Test' not 'explorer ~/Documents/BitBucket/Test'

**Comment by SEAPUNK** [comment]
@nak5124 Oh, I forgot `start` existed, neat!

**Comment by wahidshafique** [comment]
Thanks guys :)

**Comment by maoueh** [comment]
Another trick related to this but probably not exactly it, if you chose `Use MinTTY (the default terminal of MSys2)` option at installation, in the terminal, you can `Ctrl+Left Mouse Click` on path and urls and it will automatically launch Windows default associated program. For directory, this launches `explorer`, for url the default browser and for files, the default program for file extension.
