### ISSUE TITLE
git-bash doesnt run in my win 11 device. Error: Could not fork child process: Resource temporarily unavailable (-1)

### ISSUE THREAD

**Issue by mhdshameel** [git-for-windows/git#4419]
I am facing the same issue with git-bash in my win 11 device. I tried almost all the mentioned fixes here to no avail. 

I can't find any `bash.exe` or `ssh-agent.exe` processes. I also tried running the `post-install.bat` and again running it with changing `mingw32` to `mingw64` then I get an error stating:
`rebase: Invalid Baseaddress 0x64000000, must be > 0x200000000`
This error statement itself is illogical as the 0x200000000 actually crosses the 64 bit address range (easy way to figure out is to count the zeros in it).
After echoing this it goes on to fork bash.exe processes and all fails.

```
 0 [main] bash 1382 dofork: child -1 - forked process 9844 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
usr/bin/bash: fork: retry: Resource temporarily unavailable
1194468 [main] bash 1382 dofork: child -1 - forked process 30320 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
usr/bin/bash: fork: retry: Resource temporarily unavailable
3399427 [main] bash 1382 dofork: child -1 - forked process 28608 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
usr/bin/bash: fork: retry: Resource temporarily unavailable
7611246 [main] bash 1382 dofork: child -1 - forked process 12080 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
```

_Originally posted by @mhdshameel in https://github.com/git-for-windows/git/issues/910#issuecomment-1544971701_

**Comment by dscho** [comment]
This report does not mention Git for Windows version nor Windows version. Please fill in the missing information. In general, do try to overshare in bug reports, as every additional back and forth makes it more likely that people who want to help lose steam.
