### ISSUE TITLE
ssh-agent.exe STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by lafsar** [git-for-windows/git#442]
I have been using Cmder with Git for Windows 7 x64 and have been getting these stackdumps every time ssh-agent.exe is called:

MSYS-1.0.12 Build:2012-07-05 14:56
Exception: STATUS_ACCESS_VIOLATION at eip=68062B8A
eax=00000000 ebx=0A015430 ecx=7EFDD000 edx=00000000 esi=00000000 edi=00000001
ebp=0028FBFC esp=0028FBE4 program=C:\Users\my.name\Downloads\cmder\vendor\msysgit\bin\ssh-agent.exe
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028FBFC  68062B8A  (0A015430, 00000001, 00000020, 00290000)
0028FC2C  00405D1F  (0A015430, 00000003, 00000002, 00000000)
0028FD2C  00403F59  (00000000, 0A010D9C, 0A010278, 00000000)
0028FEE8  68004B08  (00000000, 00000000, 0028FF28, 00446B40)
0028FF08  68004C5F  (00403330, 00000000, 00000000, 00000000)
0028FF28  68004C98  (00000000, 00000000, 00000000, 00000000)
0028FF58  00446A48  (00403330, 00000000, 00000000, 00000000)
0028FF88  0040103D  (7EFDE000, 0028FFD4, 77C39882, 7EFDE000)
0028FF94  774A336A  (7EFDE000, 750B96A6, 00000000, 00000000)
0028FFD4  77C39882  (00401000, 7EFDE000, FFFFFFFF, 77CC7990)
0028FFEC  77C39855  (00401000, 7EFDE000, 00000000, 00905A4D)
End of stack trace

Interestingly, I have been able to commit/clone repos from/to stash with SSH just fine though, it is just a nuisance that I'm getting this message everytime when starting Cmder:

 0 [main] ssh-agent.exe" 6504 open_stackdumpfile: Dumping stack trace to ssh-agent.exe.stackdump
Could not open a connection to your authentication agent.

Same thing happens when trying to run ssh-agent directly through command prompt.

I have tried replacing the ssh-agent executable that comes with Cmder with the ssh-agent.exe that comes with my installed copy of Git, but I still get these messages. I also reinstalled Git.

Taking a look at the windows task manager processes list, every time I do an ssh clone or commit, ssh.exe (not ssh-agent.exe) process shows up briefly and then disappears. The clones and commits are always successful even if the initial startup of ssh-agent fails.

**Comment by dscho** [comment]
Which Git for Windows version? Installer or portable? Does it occur without Cmder? Can you please spend time to describe in precise words the exact steps how to reproduce the problem?

**Comment by dscho** [comment]
@lafsar ping.

**Comment by lafsar** [comment]
My git version is 1.9.5.msysgit.1 via the installer.  The stackdumps for ssh-agent occur without Cmder.

Steps to reproduce without Cmder:

-Open windows command prompt (Winkey + R, input "cmd", enter)
-type cd C:\Program Files (x86)\Git\bin then hit enter
-type ssh-agent then hit enter
-stackdump is generated

Steps to reproduce with Cmder:
-simply Run cmder.exe and stackdump is generated

**Comment by dscho** [comment]
> My git version is 1.9.5.msysgit.1 via the installer

The version 1.9.5 is deprecated. Git for Windows 2.x is a completely revamped Git for Windows, and this is indeed the bug tracker of Git for Windows 2.x. Please download a current version from [our home page](https://git-for-windows.github.io/).
