### ISSUE TITLE
git add --update file       is case sensitive

### ISSUE THREAD

**Issue by jscooksey** [git-for-windows/git#4431]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.40.1.windows.1
cpu: x86_64
built from commit: ceee26d5cac05a3437097b43d034c4ad2e99d571
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1413]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not really

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
$ git commit
[main ebc1774] yep
 1 file changed, 4 insertions(+)
$ git diff --name-only --cached
$ nano netbox/wip/UpperCase.py
#
# Changed the content 
#
$ git add --update netbox/wip/uppercase.py
fatal: pathspec 'netbox/wip/uppercase.py' did not match any files
$ git diff --name-only --cached
$ git add --update netbox/wip/UpperCase.py
warning: in the working copy of 'netbox/wip/UpperCase.py', LF will be replaced by CRLF the next time Git touches it
$ git diff --name-only --cached
netbox/wip/UpperCase.py
$ git commit
[main 3291f08] again
 1 file changed, 1 insertion(+), 1 deletion(-)
$
```
 - What did you expect to occur after running these commands?

UpperCase.py to be added in both cases.

 - What actually happened instead?

Only gets added when using UpperCase.py in the add command

The above was done with core.ignorecase=false
When set to **true** I just don't get the **did not match any files** error

```bash
$  git diff --name-only --cached
$ git add --update netbox/wip/uppercase.py
$  git diff --name-only --cached
$ git add --update netbox/wip/UpperCase.py
warning: in the working copy of 'netbox/wip/UpperCase.py', LF will be replaced by CRLF the next time Git touches it
$  git diff --name-only --cached
netbox/wip/UpperCase.py
```

This may be the way it is, but just wondering....

**Comment by dscho** [comment]
While your _file system_ may be case-insensitive, that is not the case for Git. So that is very much intended behavior. 
In any case, this is not a Windows-specific issue. If you want to discuss this topic further, maybe take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently)>
