### ISSUE TITLE
fsmonitor doesn't detect changes to files in case insensitive manor

### ISSUE THREAD

**Issue by stevenh** [git-for-windows/git#4447]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.40.1.windows.1
cpu: x86_64
built from commit: ceee26d5cac05a3437097b43d034c4ad2e99d571
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1702]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Disabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Files are in a directory which `git` shows as a different case to that of the files in the local workspace.
The inconsistency wasn't introduced locally, this was how git checked out the repository from GitHub.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Any of the following commands fail to show the correct behaviour
```
git diff <filename>
git status
git checkout <filename>
git add <filename>
```
 - What did you expect to occur after running these commands?

Changes to the file I've edited.

 - What actually happened instead?

No changes detected

 - Example proving its fsmonitor
# Filesystem monitor enabled
```
$ git config core.fsmonitor true
$ git diff Assets/Scripts/test.cs
$ git checkout Assets/Scripts/test.cs
Updated 0 paths from the index
```
# Filesystem monitor disabled
```
$ git config core.fsmonitor false
$ git diff Assets/Scripts/test.cs
diff --git a/Assets/Scripts/test.cs b/Assets/Scripts/test.cs
index 819fa62520..b0f4a1ba13 100644
--- a/Assets/Scripts/test.cs
+++ b/Assets/Scripts/test.cs
@@ -29,7 +29,7 @@ namespace test

         private void MyFunc()
         {
-            Log("test1");
+            Log("test2");
         }


$ git checkout Assets/Scripts/test.cs
Updated 1 path from the index
```

In this case the `Scripts` directory was actually `SCripts` on the local filesystem.
```
ls -l Assets/ |grep -i Scripts
drwxr-xr-x 1 myuser mygroup       0 May 25 19:59 SCripts/
```

**Comment by stevenh** [comment]
Having the core of git non functional seems a bit of an issue.

Two ideas:
1.  Disable if it's a case insensitive FS, require a "I really want it" flag to enable?
2.  Have a separate mode to take the hit on performance, but still at least some of the benefit?

**Comment by dscho** [comment]
> Having the core of git non functional seems a bit of an issue.

That is a mischaracterization of the issue. Git itself _does_ handle file names case-sensitively. And FSMonitor reports the paths with the case that is recorded on disk. Arguably the bug is that the user checked out the file using a different case than what is in the Git index.

Calling what Git does "non functional" pretends that it would not work when using the correct case, either. But it does work when the case recorded on disk matches the one recorded in the Git index.

**Comment by stevenh** [comment]
I think there may be a miss-understanding, let me try to clarify:
In the repository there are files in two different directories with different casing because they were committed from a case sensitive OS.

Now on the case insensitive OS the later files are checked out by git into the existing directory hence are not in the right place.

Because of this, changes are not noticed as detailed in the initial report, hence "git non functional" as changes will be missed from commits and it could result in changes being lost which is the core responsibility of git.

I agree that checking the files into two directories is an issue, but would still expect git to identify the changes.

I totally acknowledge this is and edge case, but given the impact to the user I think it's worth at least considering how to warn users of the risks.

As a final note I was going to workaround by making the FS case sensitive, which is pretty easy to do, but the code is for Unity which annoyingly specifically tests for a case sensitive filesystem on Windows and refuses to load it its detected.

**Comment by stevenh** [comment]
Should we document this some how?

**Comment by dscho** [comment]
> Should we document this some how?

That, or try your hand at a fix based on the pointers I provided.
