### ISSUE TITLE
Homepage 'Tools & Features' section should include Git Credential Manager

### ISSUE THREAD

**Issue by hickford** [git-for-windows/git#4449]
Git for Windows includes Git Credential Manager  as an optional extra during installation. This is a fantastic feature. It should be mentioned on the homepage under "Tools & Features"  https://gitforwindows.org/

**Comment by PhilipOakley** [comment]
The link to the repo of that homepage is given at the bottom of the page.

"To contribute/update this web page, see its [Repository](https://github.com/git-for-windows/git-for-windows.github.io)."

PRs welcome 😉
