### ISSUE TITLE
SDK: Use fit-commit to help craft better commit messages 

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#445]
This is an idea at this stage, not a concrete plan. https://github.com/m1foley/fit-commit allows to define community rules for commit messages, requiring an extra question to be answered with "yes" to violate the conventions.

Maybe a good idea to install that into `/usr/src/git` as well as `/usr/src/build-extra`?

**Comment by dscho** [comment]
The cleanest way to do this would probably be to extend `git-extra`'s post-install script to install this hook, after creating a new package for `git-fit-commit` and making it a dependency of `git-extra` (taking pains to exclude it from the GIt-for-WIndows installer).

**Comment by PhilipOakley** [comment]
Do we already have the Ruby  >= 1.9 pre-requisite? 

I wasn't aware of having it. (I'd tried installing Ruby in the Msysgit days and failed...)

Also the Git upstream does not follow the rule
* **Capitalize Subject**: Begin all subject lines with a capital letter

The subject is often the command or function name (lower case)

If it is all customisable then it could be a useful help, but then again devs & rules don't always mix well ;-)

**Comment by dscho** [comment]
> Do we already have the Ruby >= 1.9 pre-requisite?

Yep, to support `asciidoctor`.

> Also the Git upstream does not follow the rule
> 
> * Capitalize Subject: Begin all subject lines with a capital letter
> 
> The subject is often the command or function name (lower case)
> 
> If it is all customisable then it could be a useful help, but then again devs & rules don't always mix well ;-)

As far as I understand `fit-commit`, *everything* is configurable. You can turn the rules on and off as you like. And add some.

For example, I will add a rule to "strongly suggest" a Sign-off, and one to discourage one-liner commit messages. But I will have to find time to play with the fit-commit thing first...

**Comment by nalla** [comment]
What if you do a `rm -rf /usr/src/git && git clone https://github.com/git-for-windows/git.git`. The hook will be lost again I presume.

**Comment by dscho** [comment]
> What if you do a rm -rf /usr/src/git && git clone https://github.com/git-for-windows/git.git. The hook will be lost again I presume.

Yes. And the next `git-extra` update would reinstall it ;-)

**Comment by dscho** [comment]
Hrm, after giving this considerable time to simmer, I guess it is time to close this ticket:

![](https://imgs.xkcd.com/comics/is_it_worth_the_time.png)
