### ISSUE TITLE
Invoking Git bash loses single quotes

### ISSUE THREAD

**Issue by sigoden** [git-for-windows/git#4460]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 
```
$ git --version --build-options

git version 2.41.0.windows.1
cpu: x86_64
built from commit: ff94e79c4724635915dbb3d4ba38f6bb91528260
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2846]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Suppor
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

None,  just upgraded to 2.41.0.

 - What did you expect to occur after running these commands?

Run git bash in powershell
```ps1
 & 'C:\Program Files\Git\bin\bash.exe' test.sh 'abc''def'
```
The content of test.sh is `echo $1`.

The output is `abcdef` other than `abc'def`, single quote is lost.

Same result with CMD:
```cmd
"C:\Program Files\Git\bin\bash.exe" test.sh abc'def
```

**Comment by dscho** [comment]
That's regular PowerShell quoting rules, see https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3 for more details.

In this instance, you have a string that is quoted in single quotes, which can contain verbatim single quotes by doubling them.

If you want to pass a string with single quotes from PowerShell to _any_ program (including Bash), you will have to quote them as PowerShell expects it, e.g. `"C:\Program Files\Git\bin\bash.exe" test.sh "abc'def"`.

**Comment by dscho** [comment]
I did this in a Git for Windows SDK Bash:

```console
$ cat >echo-back-command-line.c <<\EOF
#include <stdio.h>

int main(int argc, char **argv)
{
        int i;

        for (i = 0; i < argc; i++)
                fprintf(stderr, "arg #%d: '%s'\n", i, argv[i]);

        return 0;
}
EOF

$ gcc -Wall -o echo-back-command-line.exe echo-back-command-line.c

```

Then, in a PowerShell:

```console
PS C:\Users\me\test> .\echo-back-command-line.exe 'abc''def'
arg #0: 'C:\Users\me\test\echo-back-command-line.exe'
arg #1: 'abc'def'
```

You see that the single quotes are stripped, even if there is no Bash involved in the last call.

**Comment by dscho** [comment]
> But in git bash, the middle single quote is unexpected stripped.

Well, it is half expected, if you know how Windows command-line parsing works.

The truth is that it is very different from the way Unix works. On Unix, the process really gets passed an array of command-line parameters. And on Windows, a _command-line_. No array. The program has to do the command-line parsing themselves.

And Bash (or more correctly: the POSIX emulation layer called the MSYS2 runtime) does it differently than what is Windows' custom because it adheres to Unix conventions.

Therefore, you have to use _two_ layers of quoting if you want to pass a parameter to a Unix shell script from PowerShell. One for PowerShell, one for Bash. This one works:

```console
PS C:\Users\me\test> & 'C:\Program Files\Git\bin\bash.exe' echo-back-command-line.sh '"abc''def"'
#0: 'echo-back-command-line.sh'
#1: 'abc'def'
```

**Comment by sigoden** [comment]
@dscho 
This has nothing to do with command-line parsing.

I pass the parameters directly through the program call, and the result is the same.

```rust
use std::process::Command;

fn main() {
    let output = Command::new("C:\\Program Files\\Git\\bin\\bash.exe")
        .arg("test.sh")
        .arg("abc'def")
        .output()
		.unwrap();

    println!("{output:?}");
}
```

```
$ cargo run
Output { status: ExitStatus(ExitStatus(0)), stdout: "abcdef\n", stderr: "" }
```

git bash just can't handle single quotes in the middle of the string.

**Comment by dscho** [comment]
> This has nothing to do with command-line parsing.

Yes it does, it's just not _Git_'s command-line parsing, but _Bash_'s.
