### ISSUE TITLE
commit operation fails when used with both `-a` and `-m`

### ISSUE THREAD

**Issue by baudronp** [git-for-windows/git#4462]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.40.1.windows.1
cpu: x86_64
built from commit: ceee26d5cac05a3437097b43d034c4ad2e99d571
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19044.2965]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir test_repo
cd test_repo
git init
echo test > file1.txt
echo test > file2.txt
git add --all
git commit -m "first commit"
del file1.txt
del file2.txt
git commit -m "remove files" -a
```

 - What did you expect to occur after running these commands?

Both deleted files (`file1.txt` and `file2.txt`) are automatically staged (`-a`) and the commit is created with the description `remove files`.

 - What actually happened instead?

Starting with version 2.40.0, Git report that nothing is present in the staging area:
```
>git commit -m "remove files" -a
On branch main
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    file1.txt
        deleted:    file2.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

With an older version like 2.39.2 it works as expected:

```
>2.39.2\cmd\git.exe commit -m "remove files" -a
[detached HEAD d555039] remove files
 2 files changed, 2 deletions(-)
 delete mode 100644 file1.txt
 delete mode 100644 file2.txt
```

If we remove the `-m` option it works.
If we only have one delete file it works.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It can be reproduced on a locally initialized repository.

**Comment by baudronp** [comment]
Hi,
Is it the good place to raise this issue?
If not, don't hesitate to point me to the right one 🙂

**Comment by dscho** [comment]
> >2.39.2\cmd\git.exe commit -m "remove files" -a

Could you check if putting `-a` _before_ the `-m "remove files"` argument make things work?

**Comment by baudronp** [comment]
The same thing happen:

**Comment by dscho** [comment]
Aha! I implemented this as a new test case for Git's test suite and at first could not get it to fail. The crucial part to make it fail was to ensure that _no tracked file is left after staging the deletions_. And I can confirm that it is a Git upstream issue, it's not specific to Git for Windows.

Will keep you posted.

**Comment by dscho** [comment]
https://github.com/gitgitgadget/git/pull/1554 seems to be cruising along. Once that's accepted upstream, we can either backport it into Git for Windows or get it via the next upstream Git version.

**Comment by baudronp** [comment]
Thanks for the fix and the update!
On my side there is no urgency it could wait for the next upstream version 🙂
