### ISSUE TITLE
Enable Windows Terminal integration by default

### ISSUE THREAD

**Issue by mwisnicki** [git-for-windows/git#4468]
When installing Git with winget windows terminal integration seems disabled.

Can you please flip it to be on by default?

According to Terminal devs it is perfectly safe to do so even if Terminal is not installed: https://github.com/microsoft/terminal/issues/15559 

Given that Terminal and WinGet are both preinstalled in Windows 11 this seems like a best way forward.

**Comment by dscho** [comment]
Git for Windows does not officially support winget. Please report this issue with winget instead (or even better, contribute a PR to make the change you want to see).

**Comment by mwisnicki** [comment]
It's not strictly related to winget although most problematic for winget users.

Terminal is now default terminal. Why not provide useful defaults?

**Comment by rimrul** [comment]
> Terminal is now default terminal. Why not provide useful defaults?

That's only true for Windows 11 AFAIK, but we currently still support Windows 7 and newer, so it wouldn't make much sense as a general default, but I guess it could be implemented as a default on Windows 10 and newer.

**Comment by dscho** [comment]
@mwisnicki are you talking about the checkbox in the installer?

**Comment by BrandonWanHuanSheng** [comment]
I think it is so.

**Comment by dscho** [comment]
> I think it is also. So the answer could be yes.

Indeed, if there is more active interest, the answer could be "yes". To get started:
1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `install.iss`
   The [`windowsterminal`](https://github.com/git-for-windows/build-extra/blob/e95621eef7a2e9e5d91ee9b166a9cd5c54f68621/installer/install.iss#L115) component will need a [`Check`](https://jrsoftware.org/ishelp/index.php?topic=scriptcheck&anchor=Check) parameter pointing to a new function similar to [the `EnableSymlinksByDefault()` function](https://github.com/git-for-windows/build-extra/blob/e95621eef7a2e9e5d91ee9b166a9cd5c54f68621/installer/install.iss#L1250-L1266), in particular imitating the part that looks for a minimum Windows version.
4. build a new installer via `sdk build installer`/test the page via `./release.sh -d wpSelectComponents`
5. verify that that installer works as expected?
6. open a PR?

@BrandonWanHuanSheng hopefully you are motivated to enough to get started with this project?

**Comment by BrandonWanHuanSheng** [comment]
No, I am not interest in Github SDK Project.
