### ISSUE TITLE
create-shortcut.exe command not found

### ISSUE THREAD

**Issue by DakshKK** [git-for-windows/git#4481]
I'm running Git SDK, and tried using Msys2 shell.

On launching the shell, before prompt printing, the shell diligently informs me of no create-shortcut.exe command found.

I have gone through the git-sdk.sh file in build-extra. Is there any fix to this, or manner to supress this error?

**Comment by dscho** [comment]
> the shell diligently informs me of no create-shortcut.exe command found.

It should be there, though: https://github.com/git-for-windows/git-sdk-64/blob/HEAD/mingw64/bin/create-shortcut.exe

Maybe you could clarify what steps reproduce the issue you're seeing (hint: this was suggested in the bug reporting issue template, and not meant to be deleted just like that).

**Comment by DakshKK** [comment]
Created new issue #4486. Closing this one.
