### ISSUE TITLE
Git fails on mounted APFS file system

### ISSUE THREAD

**Issue by dsl101** [git-for-windows/git#4482]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.41.0.windows.1
cpu: x86_64
built from commit: ff94e79c4724635915dbb3d4ba38f6bb91528260
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3086]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Repository is in a mounted APFS file system, mapped as `M:/`

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal running PowerShell 7.2.11

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Edit a single file, then add—e.g.:
```
git add .\app.json
```
 - What did you expect to occur after running these commands?

The file would be staged

 - What actually happened instead?

Error: `Rename from '.git/objects/31/tmp_obj_B1ugIR' to '.git/objects/31/f3444f8cb349e367661b6c6c659cd0934884fd' failed. Should I try again? (y/n)`

I believe this is because git is creating its intermediate files 'read only', and that has the effect of setting the `uchg` flag on APFS, which then means the file can't be renamed or deleted. If I manually remove that flag, and then hit 'y' to the prompt, git will continue.

I haven't found any way to remove that `uchg` feature on the APFS side, or in the way the drive is mapped on the windows side.

**Comment by dscho** [comment]
Oh wow, that's an obscure use case ;-) Quite honestly, I have no viable idea how to address that from Git's side: Its assumption that it can create read-only files and then rename them once finished is pretty firm.

**Comment by dsl101** [comment]
Yes, I'm basically using the mac in order to run iOS simulator, but my main dev machine & tooling is all on windows and I couldn't face trying to setup & configure it all on the mac :).

I'm assuming there's implicit or explicit ordering there—create file, write contents, set to read only, rename. It would require reversing the last 2 I guess. But I don't know if that's done in one place or everywhere...

**Comment by dsl101** [comment]
Looks like somewhere around [here](https://github.com/git-for-windows/git/blob/ff94e79c4724635915dbb3d4ba38f6bb91528260/compat/mingw.c#L2688) is the shared code for this kind of thing. Perhaps something like this?
```
diff --git a/compat/mingw.c b/compat/mingw.c
index 274346e5c5..74ffa7e709 100644
--- a/compat/mingw.c
+++ b/compat/mingw.c
@@ -2687,7 +2687,8 @@ int mingw_accept(int sockfd1, struct sockaddr *sa, socklen_t *sz)
 #undef rename
 int mingw_rename(const char *pold, const char *pnew)
 {
-       DWORD attrs = INVALID_FILE_ATTRIBUTES, gle;
+       DWORD attrs = INVALID_FILE_ATTRIBUTES, gle, attrsold;
+       bool resetattrs;
        int tries = 0;
        wchar_t wpold[MAX_LONG_PATH], wpnew[MAX_LONG_PATH];
        if (xutftowcs_long_path(wpold, pold) < 0 ||
@@ -2695,8 +2696,18 @@ int mingw_rename(const char *pold, const char *pnew)
                return -1;

 repeat:
+       /* check if file is read-only and change if necessary */
+       resetattrs = false;
+       attrsold = GetFileAttributesW(wpold);
+       if (attrsold & FILE_ATTRIBUTE_READONLY) {
+    SetFileAttributesW(wpold, attrsold & ~FILE_ATTRIBUTE_READONLY);
+               /* flag to change back after rename */
+    resetattrs = true;
+       }
        if (MoveFileExW(wpold, wpnew,
                        MOVEFILE_REPLACE_EXISTING | MOVEFILE_COPY_ALLOWED))
+               if (resetattrs)
+           SetFileAttributesW(wpnew, attrsold);
                return 0;
        gle = GetLastError();

@@ -2719,7 +2730,7 @@ int mingw_rename(const char *pold, const char *pnew)
        if (attrs == INVALID_FILE_ATTRIBUTES &&
            (attrs = GetFileAttributesW(wpnew)) != INVALID_FILE_ATTRIBUTES) {
                if (attrs & FILE_ATTRIBUTE_DIRECTORY) {
-                       DWORD attrsold = GetFileAttributesW(wpold);
+                       attrsold = GetFileAttributesW(wpold);
                        if (attrsold == INVALID_FILE_ATTRIBUTES ||
                            !(attrsold & FILE_ATTRIBUTE_DIRECTORY))
                                errno = EISDIR;
```
Unfortunately I don't think I have the wherewithal to build & test that, but would be happy to try it if someone can take a look.

**Comment by dsl101** [comment]
OK, well that was easier than I thought it would be. Downloaded the SDK and built, and my version now works as expected on APFS :). I'll submit a PR in case it's useful for others.
