### ISSUE TITLE
bash: create-shortcut.exe: command not found

### ISSUE THREAD

**Issue by DakshKK** [git-for-windows/git#4486]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.41.0.windows.1
cpu: x86_64
built from commit: ff94e79c4724635915dbb3d4ba38f6bb91528260
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.25393.1]
(c) Microsoft Corporation. All rights reserved.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Git SDK 64-bit installation

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

From Run Dialog ( `Win+R` ) / cmd.exe
```
c:\git-sdk-64\msys2_shell.cmd -msys2
```
 - What did you expect to occur after running these commands?

Just the prompt to appear.

 - What actually happened instead?

Prompt is preceded by error in title.

 - If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing?

I think this stems from [`build-extra` (`git-extra` package)](https://github.com/git-for-windows/build-extra/tree/main/git-extra).

Inspecting [`PKGBUILD` L143](https://github.com/git-for-windows/build-extra/blob/main/git-extra/PKGBUILD#L143) - `create-shortcut.exe` is installed under `/mingw64/bin`, making it available only to `mingw-w64` shell.

Possible solutions that I could think of are:
1. Install under global directory on `$PATH` - `/usr/bin` or `/bin`.
2. Install for every `MSYS2` environment.
3. Edit [`git-sdk.sh create-desktop-icon` (`desktop_icon_path` variable)](https://github.com/git-for-windows/build-extra/blob/main/git-extra/git-sdk.sh#L96) to run `create-shortcut.exe` as `/mingw64/bin/create-shortcut.exe`
4. Install all relevant `git-sdk.sh` files under [`$pkgdir${MINGW_PREFIX}/etc/profile.d`](https://github.com/git-for-windows/build-extra/blob/main/git-extra/PKGBUILD#L154) or `$pkgdir${MINGW_PREFIX}/bin` making it execute only in the [MSYS environment where it is installed](https://github.com/git-for-windows/git-sdk-64/blob/main/etc/profile#L100C3-L104C5).

I have no idea of how we can setup 2 or 4 correctly, but I can create a pull request to achieve either of 1 or 3.

**Comment by dscho** [comment]
> `c:\git-sdk-64\msys2_shell.cmd -msys2`

The canonical way to run Git for Windows' SDK would be `git-bash.exe`. Can you try that?

**Comment by DakshKK** [comment]
> The canonical way to run Git for Windows' SDK would be `git-bash.exe`. Can you try that?

That works without any issue, since I assume `git-bash.exe` is a properly configured shell of your SDK bitness.

Though this would help cover the use case of [Install inside MSYS2 proper](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper) as well. If relevant I can post the same thread to msys2/MINGW-packages#16383.

**Comment by dscho** [comment]
> this would help cover the use case of [Install inside MSYS2 proper](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper) as well.

# [Please note that this scenario is not officially supported by Git for Windows](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper#please-note-that-this-scenario-is-not-officially-supported-by-git-for-windows)

I have enough stuff to support and cannot take on more. Time for others to step up, if they're serious about it.

**Comment by DakshKK** [comment]
> I have enough stuff to support and cannot take on more. Time for others to step up, if they're serious about it.

I'll undertake the task, though I will need some guidance. This could help resolve such issues for other people as well.

I just need help understanding how can I develop/test the package, or install it from a local folder. Tried googling couldn't find anything relevant to help though. If possible would also like to understand where the relevant `makepkg-mingw` commands are.

**Comment by rimrul** [comment]
> Though this would help cover the use case of Install inside MSYS2 proper as well

How? `git-sdk.sh` shouldn't be a part of that scenario.

**Comment by DakshKK** [comment]
> How? `git-sdk.sh` shouldn't be a part of that scenario.

The wiki states that we need to install `mingw-w64-x86_64-git-extra`, which also includes `git-sdk.sh`. This is where the issue crops up from, when we run any shell, which is not mingw64, since `git-sdk.sh` is installed under [/etc/profile.d](https://github.com/git-for-windows/build-extra/blob/main/git-extra/PKGBUILD#L154), and `git-sdk.sh` uses `create-shortcut.exe`.

**Comment by DakshKK** [comment]
> I have enough stuff to support and cannot take on more. Time for others to step up, if they're serious about it.

If you could add some labels which help us know necessary but basic work into the repo, I can sit on the same.

Git is essential and would love to help with the work.

**Comment by rimrul** [comment]
> > How? `git-sdk.sh` shouldn't be a part of that scenario.
> 
> The wiki states that we need to install `mingw-w64-x86_64-git-extra`, which also includes `git-sdk.sh`. This is where the issue crops up from, when we run any shell, which is not mingw64, since `git-sdk.sh` is installed under [/etc/profile.d](https://github.com/git-for-windows/build-extra/blob/main/git-extra/PKGBUILD#L154), and `git-sdk.sh` uses `create-shortcut.exe`.

Ah, I see. It might make sense to split `git-extra` into multiple packages. One package with sdk specific things (`git-sdk.sh`, `sdk.completion`, `cyg-dlls.sh`, `update-via-pacman.bat`, `zzz_rm_stackdumps.sh`, `create-shortcut.exe`) and one with the user facing things (pretty much the rest).

**Comment by dscho** [comment]
> It might make sense (from a Git for Windows in Msys2 perspective) to split `git-extra` into multiple packages. One package with sdk specific things (`git-sdk.sh`, `sdk.completion`, `cyg-dlls.sh`, `update-via-pacman.bat`, `zzz_rm_stackdumps.sh`, `create-shortcut.exe`) and one with the user facing things (pretty much the rest).

Indeed.

Or we could move parts of `mingw-w64-git-extra` into `mingw-w64-git`, so that `mingw-w64-git-extra` is only needed in the Git for Windows SDK.

I guess for the most part, that's already the case. For example, replacing the builtins with the "Git wrapper" is only necessary if you want to build a Git for Windows installer (because users are frequently fooled by the hardlinked versions of `mingw-w64-git`, thinking that they are copies).

But there is still some work left, e.g. the `/cmd/git.exe` copy of the Git wrapper & friends, which are currently installed via `mingw-w64-git` (preventing i686 and x86_64 variants from being installed side-by-side, among other issues). This should probably move to `mingw-w64-git-extra`.

There's a lot of work left there, and any help is appreciated.

**Comment by DakshKK** [comment]
> But there is still some work left, e.g. the `/cmd/git.exe` copy of the Git wrapper & friends, which are currently installed via `mingw-w64-git` (preventing i686 and x86_64 variants from being installed side-by-side, among other issues). This should probably move to `mingw-w64-git-extra`.
> 
> There's a lot of work left there, and any help is appreciated.

I have a minor working fix already ready to go. If you could give me some idea about how specific configurations are to be done, or what I need to keep in mind. I'll also do those.

I'll also open up a PR with the relevant changes then.

**Comment by dscho** [comment]
> I have a minor working fix already ready to go.

Nice.

> If you could give me some idea about how specific configurations are to be done, or what I need to keep in mind.

I have no idea what you need from me, I do not understand what you mean.
