### ISSUE TITLE
echo $var returns extra chars when using az cli cmd's

### ISSUE THREAD

**Issue by spawnmarvel** [git-for-windows/git#4497]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.41.0.windows.2**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19045.3086], 64 bit**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt" ---
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Default **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** Dont think so **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** MING64 bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

``` I was trying to store a vm host name using az cli into a bash var 
** resourceGroup="Rg-iac-linux-fu-0982" **
** az vm list --resource-group $resourceGroup --query [].name ** 

output
[
  "simpleLinuxVM-13392"
]

** Storing the same cmd in a var**
** vmNameLocal=$(az vm list --resource-group $resourceGroup --query [].name)** 
**echo $vmNameLocal** 
output
 ]simpleLinuxVM-13392"
```
 - What did you expect to occur after running these commands?

** I expected that the var $vmNameLocal would have the same result as the az cli list result  **

 - What actually happened instead?

** The result was different, not able to use that var vmNameLocal as input to new command**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

Regards

**Comment by dscho** [comment]
Isn't this the regular CR/LF issue? What does `echo "$vmNameLocal" | xxd` say?

**Comment by spawnmarvel** [comment]
Hi, If I run echo $vmNameLocal
The output is:
]simpleLinuxVM-13392"
containing one '[' and one ' " ', should it not be either simpleLinuxVM-13392 or ["simpleLinuxVM-13392"?

**Comment by spawnmarvel** [comment]
# Just a var
vmNameLocal="simpleLinuxVM-13392"
echo $vmNameLocal
simpleLinuxVM-13392

# Using az vm list --resource-group $resourceGroup --query [].name
resourceGroup="Rg-iac-linux-fu-0982" 
vmNameLocal=$(az vm list --resource-group $resourceGroup --query [].name)
echo $vmNameLocal
]simpleLinuxVM-13392"

This is what happens

**Comment by spawnmarvel** [comment]
I will test with your suggestion shortly

**Comment by spawnmarvel** [comment]
resourceGroup="Rg-iac-linux-fu-0982"
vmNameLocal=$(az vm list --resource-group $resourceGroup --query [].name)
echo "$vmNameLocal" | xxd
00000000: 5b0d 0a20 2022 7369 6d70 6c65 4c69 6e75  [..  "simpleLinu
00000010: 7856 4d2d 3134 3137 3522 0d0a 5d0a       xVM-14175"..].
