### ISSUE TITLE
Installation of ver 2.41.0.2 shows entry "Git for Windows" from Windows Installed App list

### ISSUE THREAD

**Issue by georgegom** [git-for-windows/git#4499]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit
```
$ git --version --build-options

git version 2.41.0.windows.2
cpu: x86_64
built from commit: 330483e35cabcdd966e0d4fee29153caaa9a2129
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 11 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1928]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

1. Previous version installed on same Windows 11 system was version 2.40.0
2. After installation, noticed a Git For Windows listed with a File Directory icon (see embedded screen shot)
3. Right click on the icon to open the file location, and it opens C:\Users\[user]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs where a shortcut with the same name and icon.
4. The shortcut points to c:\Program Files\Git\mingw64\bin
5. When this icon is selected from the app menu, it attempts to open a window but closes immediately.

<img width="296" alt="image" src="https://github.com/git-for-windows/git/assets/35473900/3964a20c-ded7-4766-94c3-d6c0c42963f7">

**Comment by dscho** [comment]
This looks like the shortcut that is created by the `wintoast` application when a notification about a new version is displayed. See also https://github.com/git-for-windows/git/issues/3126.

We could, of course, delete it as part of the uninstaller. This would only work if the uninstaller is run as the same user who installed Git for Windows, though, as the update check runs [as a scheduled task](https://github.com/git-for-windows/build-extra/blob/1bb44bc37abea0af95308bcffbdc2928cd3d4ee0/installer/install.iss#L2756-L2792), i.e. in the logged-in user's context, and therefore the shortcut is installed into `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Git for Windows` (which is a path that changes from user to user). Still, this would likely catch most of the scenarios.

@georgegom if you would like to experiment with this idea, please:

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `install.iss`, e.g. by adding a statement to [the `UninstallAutoUpdater` function](https://github.com/git-for-windows/build-extra/blob/1bb44bc37abea0af95308bcffbdc2928cd3d4ee0/installer/install.iss#L2796) (probably using [`DeleteFile()`](https://jrsoftware.org/ishelp/index.php?topic=isxfunc_deletefile) and `ExpandConstant('...{localappdata}...')` similar to [how it is used here](https://github.com/git-for-windows/build-extra/blob/1bb44bc37abea0af95308bcffbdc2928cd3d4ee0/installer/install.iss#L2807))
4. build a new installer via `sdk build installer`
5. verify that that (un-)installer works as expected?
6. open a PR?

**Comment by georgegom** [comment]
I was able to find a directory with the lists of icons shortcuts for the listed installed apps list, and it was a simple as hitting delete on that shortcut.  I will keep your suggestion for the next update.

Thank you heaps for the assistance.
