### ISSUE TITLE
Git 2.41.0.windows.2 -> fatal: Missing 'username' input argument

### ISSUE THREAD

**Issue by Balkoth** [git-for-windows/git#4500]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version
git version 2.41.0.windows.2
cpu: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3086]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git remote show origin
git clone
git push
```
 - What did you expect to occur after running these commands?

```
$ git remote show origin
* remote origin
  Fetch URL: https://server.domain.de/Test.git
  Push  URL: https://server.domain.de/Test.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

 - What actually happened instead?

```
$ git remote show origin
fatal: Missing 'username' input argument
* remote origin
  Fetch URL: https://server.domain.de/Test.git
  Push  URL: https://server.domain.de/Test.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

Since the update git complains `fatal: Missing 'username' input argument`

**Comment by dscho** [comment]
@mjcheetham does this ring a bell? Is this maybe a new thing in Git Credential Manager?

**Comment by mjcheetham** [comment]
Correct @dscho, this issue is actually https://github.com/git-ecosystem/git-credential-manager/issues/1331, and we have a fix for this [in place](https://github.com/git-ecosystem/git-credential-manager/pull/1332) already.
