### ISSUE TITLE
Installing Git-2.41.0.3-64-bit.exe fails to complete successfull

### ISSUE THREAD

**Issue by jaltman** [git-for-windows/git#4506]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git-2.41.0.3-64-bit.exe

$ git --version --build-options

error launching git: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

x64   Windows 11 [Version 10.0.22621.1992]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Chose the defaults.  The install complained that global config settings could not be set but that is likely because the Windows believes the installed git is malware.

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"

$ cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Same error from multiple shells

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git without any arguments

 - What did you expect to occur after running these commands?

execution of git displaying usage

 - What actually happened instead?

error launching git: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by jaltman** [comment]
Reinstall of Git-2.41.0.2-64-bit.exe results in successful execution

**Comment by leechaojie** [comment]
Unfortunately I'm having this problem as well.

**Comment by PaulNeumann** [comment]
Same issue here, unfortunately.

**Comment by PhilipOakley** [comment]
It sounds like it could be an anti-virus problem where the very new version hasn't yet propagated through the AV ecosystem, and the AV thinks that some of the normal Git operationare suspicious,

> error launching git: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Comment by jrqams** [comment]
I ran into the same issue with Windows defender flagging this as a trojan last night.

Hybrid analysis flags this as malicious with a threat score of 98/100

[https://hybrid-analysis.com/sample/d7059a66b4598384ccd7df4556ad59a516ee99a722c0d38e5de75c1bad39ba6c](https://hybrid-analysis.com/sample/d7059a66b4598384ccd7df4556ad59a516ee99a722c0d38e5de75c1bad39ba6c)

It didn't run to completion in their sandbox. Throws memory access error

[https://hybrid-analysis.com/file-inline/64b0b01b8730eeb6a8034086/screenshot/screen_5.png](https://hybrid-analysis.com/file-inline/64b0b01b8730eeb6a8034086/screenshot/screen_5.png)

**Comment by derrickstolee** [comment]
Thanks for all the reports here. We are taking this seriously and have demoted the release to a pre-release to discourage new installs until we full understanding.

**Comment by derrickstolee** [comment]
Hello, all! Quick update here.

We take security very seriously and wanted to get to the bottom of these reports as soon as possible.

The first action we took was to demote the (2) and (3) releases to pre-releases and change `git-for-windows.org` and `git-scm.com` to point to the v2.41.0.windows.1 release instead, in order to minimize the number of installs.

Second, we investigated the different places that reported issues.

> Hybrid analysis flags this as malicious with a threat score of 98/100
> 
> https://hybrid-analysis.com/sample/d7059a66b4598384ccd7df4556ad59a516ee99a722c0d38e5de75c1bad39ba6c
> 
> It didn't run to completion in their sandbox. Throws memory access error
> 
> https://hybrid-analysis.com/file-inline/64b0b01b8730eeb6a8034086/screenshot/screen_5.png

This analysis looked particularly scary, but it has similar results for the .1 release, so we are considering this to be a false positive case. Another third-party scanner reported no concerns.

The last piece of the puzzle is to investigate why Windows Defender complained. As @PhilipOakley mentioned, this is most likely an issue with not enough users installing the file, which paired with @dscho's personal certificate can cause some defender setups to complain. We hope that this is the reason.

To be extra sure, we submitted the .3 release binaries to Windows Defender for a full analysis. That check is still ongoing, so I'll update (and hopefully close) this issue when we hear back.

Thanks, everyone!

**Comment by bricss** [comment]
Cannot confirm any of that.
Installed on 2️⃣  machines with `Microsoft Windows NT 10.0.22621.1992 x64` with 0️⃣ issues so far 👾

**Comment by jaltman** [comment]
I reinstalled the Git-2.41.0.3-64-bit.exe package that I installed when first released.   The install package completed successfully and without warning dialogs unlike the original install.   git --version can be successfully executed.

**Comment by derrickstolee** [comment]
We have gotten a complete report from Windows Defender stating that this was a false alarm. Thanks for the reports, everyone!

The .3 release is again available as a full release.
