### ISSUE TITLE
Can't use git after running first command.

### ISSUE THREAD

**Issue by jcassuleAfricell** [git-for-windows/git#4514]
After I init a new git repo, I can run one command(such as branch or add).
After I try running any new commands, i get the message "fatal: not a git repository (or any of the parent directories): .git"

I'm using windows 10, btw.

![MINGW64__c_Users_jcassule_OneDrive - Africell_Documents_Projects_Teste 7_19_2023 7_34_42 AM (2)](https://github.com/git-for-windows/git/assets/139790301/e5d7a2db-f76a-4c55-9526-fcafe744890f)

If anyone has an idea, please help me.

**Comment by rimrul** [comment]
> ~/OneDrive

Could you try that again in a folder not managed by OneDrive or similar cloud sync services? Those are known to corrupt git repositories.

https://lore.kernel.org/git/xmqq1qxpcd08.fsf@gitster.g/T/#m8ed4b9ff8a04865f41bf3cda37a7f230b04fa196

https://lore.kernel.org/git/CAMhVC3acU06uBDAjd5LEiCvuf8=XW_1RYVVt7CdKr-JqB7cRFA@mail.gmail.com/T/#u

https://lore.kernel.org/git/9A165840-280C-43C4-B92B-3349E07AC0B1@webssup.com/

**Comment by jcassuleAfricell** [comment]
Hey. Thanks for your feedback.
It is working!

**Comment by jcassuleAfricell** [comment]
solved
