### ISSUE TITLE
Having problems with loading assemblies for git-tf

### ISSUE THREAD

**Issue by Haacked** [git-for-windows/git#452]
In setting up `git-tf` when we run the `tfs bootstrap` command, we get the following error.

> Could not load file or assembly 'StructureMap, Version=2.6.1.0, Culture=neutral, PublicKeyToken=e60ad81abae3c223' or one of its dependencies. The system cannot find the file specified.

I see the assembly is there. This could well be an error on my side, but I've double checked everything I know to double check. I wanted to see if this works for any of you before I go crazy deep into it.

**Comment by dscho** [comment]
Wrong bug tracker? ;-)

**Comment by Haacked** [comment]
> Wrong bug tracker? ;-)

Ha! Probably.

I figured I'd ask here in case I'm doing something obviously wrong because this worked before with our msysgit setup. We have a portable git package we ship with GitHub Desktop (for Windows) and I put the git-tfs folder in the `share` folder and it doesn't work.

I'll look for the git-tfs repo and ask there, but if you happen to have any thoughts on what I should check, I'd be happy to hear them. :smil:

**Comment by dscho** [comment]
Well, your description left me utterly puzzled... I would not even begin to know how to start trying to reproduce the issue... Git for Windows version and architecture, download link for the exact tool you tried, as well as a step-by-step description to replicate how you installed it, all that would be necessary...

**Comment by Haacked** [comment]
Sorry about that. That's all I need to know. I just need to find time to put together a minimal repro and I'll log an issue on the Git-tfs repo. Thanks!
