### ISSUE TITLE
[BUG] `warning: failed to restrict file handles (5)` when committing changes

### ISSUE THREAD

**Issue by Rabbit0w0** [git-for-windows/git#4529]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.41.0.windows.3
cpu: x86_64
built from commit: 4a1821dfb0c2160a4fcc85d2845f095c54339578
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.2070]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit -a -m "bump version"
git push
(Note: Both trigger this problem.)
```
 - What did you expect to occur after running these commands?

Normally run `git commit`

 - What actually happened instead?

```
warning: in the working copy of 'build.gradle', LF will be replaced by CRLF the next time Git touches it
warning: failed to restrict file handles (5)

handle #0: 0000000000000194 (type 3, handle info (1) 0
handle #1: 0000000000000198 (type 3, handle info (1) 1
handle #2: 0000000000000160 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1


```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

[Private repository](https://github.com/RhineLabLLC/BungeeParty). Contact if requires access.

**Comment by dscho** [comment]
> warning: failed to restrict file handles (5)

Haven't seen this in quite a while, and am quite puzzled by it. 5 means `ERROR_ACCESS_DENIED` which makes no sense with your Windows version (but then, I see that it is an Insider version?)

**Comment by dscho** [comment]
> (but then, I see that it is an Insider version?)

I guess that it is.
