### ISSUE TITLE
git diff in terminal shows spurious ^M output for valid CRLF line ending in CRLF file

### ISSUE THREAD

**Issue by nothings** [git-for-windows/git#4530]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

**_There are a lot of issues with "diff" and "crlf" in them, so while I tried looking, it's possible I missed something. So this could be a known and accepted behavior for all I know._**

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.41.0.windows.3
cpu: x86_64
built from commit: 4a1821dfb0c2160a4fcc85d2845f095c54339578
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

**_I also verified that this happened on a 2018 release, Git-2.17.1.2-64-bit_**

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```
**_But I also got people on Twitter to reproduce on other versions of the OS, such as Windows 11._**

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I set global autocrlf to false before cloning this specific project. More in the repro example.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

observed in both cmd and bash (which i have set to use windows console). other users who attempted to reproduce it saw in it cmd, but not in bash; possibly they don't send bash to windows console.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global core.autocrlf false
git clone https://github.com/automatic1111/stable-diffusion-webui
cd stable-diffusion-webui
git ls-files --eol webui.bat
echo foo >> webui.bat
git diff
```
 - What did you expect to occur after running these commands?

A diff should be shown with "foo" as an added line.

 - What actually happened instead?

A diff is shown with "foo^M" as an added line.

![image](https://github.com/git-for-windows/git/assets/7525026/42329c32-3bb0-481b-8808-afb9163dfa7d)
![image](https://github.com/git-for-windows/git/assets/7525026/2ac92be1-5d15-4c55-8976-c40509fbaae6)

**_In general, all added or changed lines show a ^M at the end. Doing diffs on pairs of commits (by other people) in the repo history show ^M on every change in the history for crlf files (the repo has a mix)._**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I assume it happens with any repository that uses CRLF, but it could be specific to that repository: [https://github.com/automatic1111/stable-diffusion-webui](https://t.co/bOp6GM8nF6)

### additional discussion

All of my previous git usage has been with autocrlf=true, and I've never had a problem with the crlf-containing files showing ^M in diffs. I'm guessing this is specific to autocrlf=false, or more specifically to the "i/crlf w/crlf" case vs. the "i/lf w/crlf" case. In all the historical diffs I looked at, I only saw ^M in diffs for i/crlf files, and not for i/lf files.

Here is an example screenshot someone sent me with different results for cmd vs bash; I don't know what their setup was though.

![image](https://github.com/git-for-windows/git/assets/7525026/e31d5536-9f8a-467a-b7ad-b6707b086765)

**Comment by tboegi** [comment]
That is expected,
git ls-files --eol show this:
i/crlf  w/crlf  attr/                   webui.bat
i/crlf  w/crlf  attr/                   webui.py
i/lf    w/lf    attr/                   webui.sh

A better way to will be to set up a correct
.gitattributes
file and to run
git add --renormalize .
after that.

**Comment by rubberbaron** [comment]
> That is expected, git ls-files --eol show this: i/crlf w/crlf attr/ webui.bat i/crlf w/crlf attr/ webui.py i/lf w/lf attr/ webui.sh

Yes, that's why my repro example includes "git ls-files --eol" in it. Why do you think it is expected that a file with format "i/crlf w/crlf" in which you modify a single character will show a ^M in the diff in cmd and not in bash?

**Comment by nothings** [comment]
> That is expected, git ls-files --eol show this: i/crlf w/crlf attr/ webui.bat i/crlf w/crlf attr/ webui.py i/lf w/lf attr/ webui.sh

Yes, that's why my repro example includes "git ls-files --eol" in it. Why do you think it is expected that a file with format "i/crlf w/crlf" of which you modify a single character without changing the line endings will show a ^M in the diff in cmd and not in bash?

**Comment by nothings** [comment]
I suspect the bash vs cmd results from other people were invalid; I suspect that, as in the screenshot, they ran "echo foo >> filename" under bash as well, and maybe that only wrote an LF for some reason. I only used the echo as an easy repro case; it actually happens when you edit the files, from adding a line, changing a line, to hex-editing a single character on a single line so that line-endings are obviously untouched. Not to mention that it happens in diffs of any two old commits.
