### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by JBPEJohn** [git-for-windows/git#4532]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

2.41.0.3 
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows Server 2019 (Microsoft Windows [Version 10.0.17763.4645])
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\inetcstall-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Installed to the D: drive, default path otherwise.

B:\ESB\SWIFT\Interface\Builds>type "D:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad
Custom Editor Path:
Default Branch Option: Development
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

BASH and Visual Studio 2019.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
PUSH from Visual Studio 2019
```
 - What did you expect to occur after running these commands?

Completed push.

 - What actually happened instead?

unable to access 'https://gitlab.aws-gafg.com/risk-and-investments/enterprise-service-bus/ESB.SWIFT.Interface/': error setting certificate verify locations:  CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt CApath: none

The issue is that the gitconfig has the specified path, but the certificates were installed to "C:/Program Files/Git/usr/ssl/certs/ca-bundle.crt".  There are two problems - the path where the certs were installed is usr instead of mingw64, and the path points to the C: rather than the specified D: drive where Git was installed (gitconfig wasn't modified/created using the correct drive).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
> $ git --version --build-options
> 
> 2.41.0.3

This is not the output of Git for Windows.

> CURL Option: WinSSL

With this option, no CAfile should be specified.

Maybe the output of `git config --get-all --show-origin http.sslCAInfo` sheds light into this.
