### ISSUE TITLE
Record the installer options selected to allow later read back for bug reports

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#454]
#427 'establish a stable registry key for the location and installer options' recored various paths, however a common request to those who report bugs, is what "install options did they select?".

This *suggestion* is that the broader install options also be recorded, and that a small helper app be provided to read them back, so that consistent bug reports info can be provided (the helper app may well be able to say what processes & OS it was being run from to clear up those issues as well ;-)

Just a thought (does it even have any mileage?)..

**Comment by dscho** [comment]
Good idea! I actually had a similar idea recently, but forgot to open a ticket for it. Thanks!
