### ISSUE TITLE
.gitignore ignored

### ISSUE THREAD

**Issue by MichaelHechtDH** [git-for-windows/git#4548]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - git version

```
$ git --version --build-options

git version 2.41.0.windows.3
cpu: x86_64
built from commit: 4a1821dfb0c2160a4fcc85d2845f095c54339578
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3324]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git check-ignore -v *
```
 - What did you expect to occur after running these commands?

see infos on content and rules of .gitignore in the same directory as the .git folder
.gitignore:
./bak/
./.vscode/
./\_\_pycache\_\_/
.gitignore

 - What actually happened instead?

Nothing. No respose, so it seems .gitignore is ignored

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No. Just some local repository where all other git commands work. I removed the items of .gitignore manually.

**Comment by dscho** [comment]
> ./bak/
> ./.vscode/
> ./__pycache__/
> .gitignore

Have you tried to remove the leading `.`? Like, `/__pycache__/`? (And you don't want to add `.gitignore`...)

**Comment by dscho** [comment]
> It "feels" like git is not aware of `.gitignore`.

You're supposed to commit it.

> I tried e.g. `./bak/` and `bak/`

The `./bak/` variant is simply incorrect, and the `bak/` variant will also match directories in subdirectories of the current one. The correct variant is `/bak/`.

> VSCODE also shows all files in all subdirectories

Visual Studio Code is not supposed to respect `.gitignore`.

**Comment by MichaelHechtDH** [comment]
**You're supposed to commit it.** ... ok, this was the hint. Well, I also liked VSCode to respect the `.gitignore`, but finally the most important is, that it works now. Thank You!
