### ISSUE TITLE
warning: failed to restrict file handles

### ISSUE THREAD

**Issue by jonypeixoto** [git-for-windows/git#4554]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

Windows 64-bit
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 11 64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Error on Clone GitHub Desktop

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

GitHUb Desktop directly

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
GitHub Desktop directly
```
 - What did you expect to occur after running these commands?

Cloning into 'D:\Programs\xampp\htdocs\jonypeixoto.github.io\full-stack-web2-projects'...
warning: failed to restrict file handles (5)

handle #0: 0000000000000174 (type 3, handle info (1) 0
handle #1: 000000000000018c (type 3, handle info (1) 1
handle #2: 0000000000000bac (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

	SUPPRESS_HANDLE_INHERITANCE_WARNING=1

remote: Enumerating objects: 7179, done.        
remote: Counting objects: 100% (2257/2257), done.        
remote: Compressing objects: 100% (1030/1030), done.        
remote: Total 7179 (delta 1435), reused 1877 (delta 1105), pack-reused 4922        
Receiving objects: 100% (7179/7179), 1.07 GiB | 9.12 MiB/s, done.
Resolving deltas: 100% (2839/2839), done.
Updating files: 100% (4178/4178), done.

 - What actually happened instead?

Cloning into 'D:\Programs\xampp\htdocs\jonypeixoto.github.io\full-stack-web2-projects'...
warning: failed to restrict file handles (5)

handle #0: 0000000000000174 (type 3, handle info (1) 0
handle #1: 000000000000018c (type 3, handle info (1) 1
handle #2: 0000000000000bac (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

	SUPPRESS_HANDLE_INHERITANCE_WARNING=1

remote: Enumerating objects: 7179, done.        
remote: Counting objects: 100% (2257/2257), done.        
remote: Compressing objects: 100% (1030/1030), done.        
remote: Total 7179 (delta 1435), reused 1877 (delta 1105), pack-reused 4922        
Receiving objects: 100% (7179/7179), 1.07 GiB | 9.12 MiB/s, done.
Resolving deltas: 100% (2839/2839), done.
Updating files: 100% (4178/4178), done.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not have.

**Comment by jonypeixoto** [comment]
Anyone help me?

**Comment by dscho** [comment]
Can you reproduce with the current Git for Windows?
