### ISSUE TITLE
Call "podman run" with the option to mount a directory doesn't work in Windows bash

### ISSUE THREAD

**Issue by mowolf2000** [git-for-windows/git#4556]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
```
git --version --build-options
git version 2.41.0.windows.3
cpu: x86_64
built from commit: 4a1821dfb0c2160a4fcc85d2845f095c54339578
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Windows 11 64-bit

```
cmd /c ver
Microsoft Windows [Version 10.0.22621.2134]
(c) Microsoft Corporation. Alle Rechte vorbehalten.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
cat /etc/install-options.txt
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

I'm using the bash, delivered with Git.

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
podman run --rm -v .:/myfolder ubi8-micro ls /myfolder
```
 - What did you expect to occur after running these commands?

I got this error message from podman.

```
Error: invalid container path "\\Program Files\\Git\\myfolder", must be an absolute path
```
If I run the same command from Window command cmd.exe, I got this output instead:

```
C:\Program Files\Git>podman run --rm -v .:/myfolder ubi8-micro ls /myfolder
LICENSE.txt
ReleaseNotes.html
bin
cmd
dev
etc
git-bash.exe
git-cmd.exe
mingw64
tmp
unins001.dat
unins001.exe
unins001.msg
usr
```

The bash command seems to change the second part of the mount folder parameter "/myfolder" into a Windows path instead of passing it to the podman command unchanged.

**Comment by rimrul** [comment]
>If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "/usr/bin/bash.exe" to "C:\Program Files\Git\usr\bin\bash.exe". When that is not desired -- e.g. "--upload-pack=/opt/git/bin/git-upload-pack" or "-L/regex/" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:

>> `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`

> Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "//usr/bin/bash.exe".

From https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues
