### ISSUE TITLE
Executing last scripts freeze

### ISSUE THREAD

**Issue by XxGonanxX** [git-for-windows/git#4557]
Once the installer is on the last step (executing post-installation scripts) it freezes and never finishes.

**Comment by dscho** [comment]
This report is too terse to be certain but I suspect that it's a duplicate of https://github.com/git-for-windows/git/issues/3636. In any case, with this little information (the entire issue reporting template was simply deleted without bothering to fill in the blanks), the best I can do is close this ticket.
