### ISSUE TITLE
wrong package GitLFS 3.4.0(now 3.3.0)

### ISSUE THREAD

**Issue by miyazakiyuma** [git-for-windows/git#4567]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.42.0.windows.1
cpu: x86_64
built from commit: a2e49ec355ae22e74288fa74f50821f3cc1a1551
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.2134]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git lfs --version
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
```
The release text says "Comes with [Git LFS v3.4.0](https://github.com/git-lfs/git-lfs/releases/tag/3.4.0).", but in fact there are "git-lfs/3.3.0"

**Comment by rimrul** [comment]
> ```
> $ git lfs --version
> git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
> ```
> The release text says "Comes with [Git LFS v3.4.0](https://github.com/git-lfs/git-lfs/releases/tag/3.4.0).", but in fact there are "git-lfs/3.3.0"

Right. That's my mistake. I've fixed the package definition for Git LFS 3.4.0, merged https://github.com/git-for-windows/build-extra/pull/514 and added the release note, but somehow missed the step of actually deploing the package. Sorry about that.

**Comment by bricss** [comment]
May we expect quickfix 🩹  released for this? 🙂

**Comment by dscho** [comment]
> May we expect quickfix 🩹 released for this? 🙂

You are allowed to expect anything you'd like ;-)

My current plan is to wait for a few days to see whether any other problems show up that also need to be fixed, maybe even Git ones, and then to release a new Git for Windows version.

**Comment by dscho** [comment]
/add relnote bug Git for Windows v2.42.0's release notes claimed that it ships with Git LFS v3.4.0, [which is incorrect](https://github.com/git-for-windows/git/issues/4567) and has been fixed in this release.
