### ISSUE TITLE
Git Gui Clone Existing Repository cannot use Browse to specify new Target Directory

### ISSUE THREAD

**Issue by deanwiles** [git-for-windows/git#4569]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? `64-bit`

```
$ git --version --build-options

git version 2.42.0.windows.1
cpu: x86_64
built from commit: a2e49ec355ae22e74288fa74f50821f3cc1a1551
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
![image](https://github.com/git-for-windows/git/assets/4119940/051c6845-0000-44a6-862a-be9216bc4e2e)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? `64-bit`

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3324]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

> This behavior has occurred in all versions of Git Gui that I have used (2.38.1, 2.39.x, 2.40.0, 2.42.0)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

> Git Gui

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
1. Launch Git Gui
2. Click Clone Existing Repository
3. For Target Directory, click Browse
4. Navigate to an existing folder, type a new sub folder name and click Select Folder
```
 - What did you expect to occur after running these commands?

> The Git Repository dialog should close and the complete path for the new sub folder would be entered in the Target Directory text box.

 - What actually happened instead?

> An error message was displayed and the sub folder name was not accepted:
![image](https://github.com/git-for-windows/git/assets/4119940/15795a6f-fcdc-44d3-beb8-83df942a73eb)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

> Error occurs with any repository.

### Additional Notes

> It works OK to just type in the full path of the new Target Directory in the Clone Existing Repository dialog,
> but it would be helpful if the Browse button could be used to navigate and enter the new Target Directory path.
> Otherwise that Browse button isn't useful since you cannot use an existing directory.
>
> I'm not that familiar with tcl, but I did try to look through the code to see if there was anything obvious. 
> In https://github.com/git-for-windows/git/blob/main/git-gui/lib/choose_repository.tcl, 
> the _new_local_path method calls tk_chooseDirectory with -mustexist false,
> so it appears that it should accept a new folder, but it only accepts existing folders,
> which purposefully get rejected by the subsequent _new_ok call.

**Comment by PhilipOakley** [comment]
> 2. Click Clone Existing Repository

*Existing*   is probably the clue word in the command option. 

I think you are expecting additional functionality to create new sub-directories and repositories, which is separate.

**Comment by deanwiles** [comment]
Hi @PhilipOakley,
Actually I'm just trying to use the Browse button to specify the Target Directory for where to clone the existing repository to.
I can type the path for the Target Directory and that works fine, but using the Browse button/dialog to specify the Target Directory does not work.
Does that make sense?

**Comment by rimrul** [comment]
> tk_chooseDirectory with -mustexist false,
so it appears that it should accept a new folder

It looks like you found a bug in Tk on Windows Vista and later.

They [create a `FileOpenDialog`](https://github.com/tcltk/tk/blob/c19a751a1942aaa39d82119a02243ecd8966b4a0/win/tkWinDialog.c#L1243-L1245), get [its default options](https://github.com/tcltk/tk/blob/c19a751a1942aaa39d82119a02243ecd8966b4a0/win/tkWinDialog.c#L1258) and then [explicitly set `FOS_FILEMUSTEXIST` for `-mustexist true`](https://github.com/tcltk/tk/blob/c19a751a1942aaa39d82119a02243ecd8966b4a0/win/tkWinDialog.c#L1291-L1292), but [`FOS_FILEMUSTEXIST` is enabled by default](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions) and should be disabled for `-mustexist false`.

**Comment by dscho** [comment]
Excellent analysis @rimrul!

@deanwiles can you take this to the Tcl/Tk project, please?
