### ISSUE TITLE
Tabs to spaces

### ISSUE THREAD

**Issue by miikka75** [git-for-windows/git#457]
I'd like to see support for feature described here:
http://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs

I think this would require adding 2 new binaries (expand and unexpand). Additionally, conversion option could be added to UI (wizard).

**Comment by nalla** [comment]
If you install the SDK. You will be able to use this out of the box.

**Comment by dscho** [comment]
@miikka75 This is not a feature of Git. As it is, I have enough to do to support Git for Windows. Therefore, without your help, I do not see support for `expand` and `unexpand` coming to Git for Windows.

I will close this tentatively, but feel free to put in some real work to add the support.
