### ISSUE TITLE
GfW Installer still labels FSMonitor as experimental

### ISSUE THREAD

**Issue by jeffhostetler** [git-for-windows/git#4570]
The installer still lists FSMonitor as being experimental.  We should change that.  However, since FSMonitor is only really needed very large repos, we may not want to default it on or set the flag globally.  We might just want to advise them to set it locally on their monorepos, for example.

**Comment by dscho** [comment]
/add relnote feature The [FSMonitor feature](https://github.com/git-for-windows/git/discussions/3251) is no longer experimental, and therefore no longer offered as installer option. Users are encouraged to enable this on a per-repository basis, via the config setting `core.fsmonitor=true` (`scalar clone` does this automatically).
