### ISSUE TITLE
GfW Installer option "experimental support for pseudo consoles" is inverted

### ISSUE THREAD

**Issue by fadein** [git-for-windows/git#4571]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.1
cpu: x86_64
built from commit: a2e49ec355ae22e74288fa74f50821f3cc1a1551
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running?
  
Win11 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1702]
(c) Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

* I've installed the Windows native build of Python from python.org.
* My setup is running within VirtualBox.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MinTTY/Bash

 - What commands did you run to trigger this issue?
```
python
```
 - What did you expect to occur after running these commands?

In the past when I've installed GfW with Pseudo Console Support enabled, I can use the Python REPL.  However this time Python freezes unless I invoke it as `winpty python`.

On a whim, I re-installed GfW and left the checkbox next to Pseudo Console Support unchecked; now I can interact with Python.

**Comment by dscho** [comment]
@fadein wooow. What an awful bug you found there! Thank you so much for reporting it.

I had a look and it would appear that this bug was introduced with Git for Windows v2.41.0...

**Comment by fadein** [comment]
Thank you!
