### ISSUE TITLE
Git Bash does not work, plus Fetch and Pull don't work.

### ISSUE THREAD

**Issue by kiyochin9** [git-for-windows/git#4579]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

 git --version

git version 2.42.0.windows.2

```
$ git --version --build-options

git --version --build-options
git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

64-bit

```
$ cmd.exe /c ver


Microsoft Windows [Version 10.0.19045.3393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt


Microsoft Windows [Version 10.0.19045.3393]
Install option
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I was using the Bash before. But I am now using Windows PowerShell due to the issue. But GIT fetch and pull are still not working 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
fetch and pull
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

I am using GIT on Windows 10 machine. Issue is that Git-Bash stopped working with this comment at the header portion of the command window, "Failed to run '/usr/bin/bash': No such file or directory". It was working until 2 weeks ago. I reinstalled the latest GIT, but the symptom is the same.
However, I can run git on the Window PowerShell. From a local branch, if I fetch a remote branch, it says this, "fatal: 'remote-https' appears to be a git command, but we were not able to execute it. Maybe git-remote-https is broken?".
I can pull the same remote branch into a new local branch, but fetch and push does not work as described above.
Here is information about my system and GIT.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
Try to unpack the Portable Git, make sure that `usr\bin\bash.exe` exists, and then run `git-bash.exe` from the top-level directory where you extracted the Portable Git to. There is a chance that some overzealous anti-malware is quarantining or even deleting your files.

**Comment by kiyochin9** [comment]
Hi, I just tried your suggestion. I confirmed "usr/bin/bash.exe". Then I ran the git-bash from the directory. But it failed with this message, " Failed to run 'usr/bin/bash': No such file or directory".

**Comment by dscho** [comment]
Can you run this executable directly, from a PowerShell window?

**Comment by kiyochin9** [comment]
I just did it from the directory with this command, ".\git-bash.exe". A result is the same as before.

**Comment by dscho** [comment]
No, I meant running `usr\bin\bash.exe` directly.

**Comment by kiyochin9** [comment]
Hi,
I ran it and got this message.
PS C:\GIT_Portable\PortableGit\usr\bin> bash.exe
Program 'bash.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ bash.exe
+ ~~~~~~~~.
At line:1 char:1
+ bash.exe
+ ~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by dscho** [comment]
In PowerShell you need to call `& .\bash.exe` if I remember correctly.

**Comment by kiyochin9** [comment]
PS C:\GIT_Portable\PortableGit\usr\bin> .\bash.exe
Program 'bash.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ .\bash.exe
+ ~~~~~~~~~~.
At line:1 char:1
+ .\bash.exe
+ ~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by dscho** [comment]
And with an `&` before that?

Also, what are the symptoms in [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) when it fails? In particular when `git-remote-https.exe` fails to execute?

**Comment by kiyochin9** [comment]
Hi, Thanks for the prompt response.
 Here is the result.
PS C:\GIT_Portable\PortableGit\usr\bin> & .\bash.exe
Program 'bash.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ & .\bash.exe
+ ~~~~~~~~~~~~.
At line:1 char:1
+ & .\bash.exe
+ ~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

About the second question, are you asking me to run "git-remote-https.exe" in a local branch? I looks like I have to install "Process Monitor". Is it correct?

**Comment by kiyochin9** [comment]
Hi, About the "git-remote-https.exe", I went to the registry editor and found that data of name of "Debugger" under "git-remote-https.exe" is "C:\WINDOWS\SoftwareDistribution\Download\Install\patchmypc-preventstart.exe" /StopProcess /ApplicationName="git-remote-https.exe" It says preventstart and StopProcess. Are they related to the issue? A reason being for that at the same time of this issue started, VScode stopped working. After I googled it, a solution was to clear the same data of VScode, Then it started working. When I saw the GIT stopped working, I did the same thing for "git-bash.exe". But it did not help, I sent this messsage that it may help you to understand what is going on.

**Comment by kiyochin9** [comment]
PS C:\GIT_Portable\PortableGit\usr\bin> .\git-remote-https.exe
.\git-remote-https.exe : The term '.\git-remote-https.exe' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.

At line:1 char:1
+ .\git-remote-https.exe
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\git-remote-https.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by dscho** [comment]
> I went to the registry editor and found that data of name of "Debugger" under "git-remote-https.exe" is "C:\WINDOWS\SoftwareDistribution\Download\Install\patchmypc-preventstart.exe" /StopProcess /ApplicationName="git-remote-https.exe"

Could you clarify? I have no idea what registry key you're looking at.

**Comment by kiyochin9** [comment]
Hi, I have no idea neither about it. I went there because of a solution to fix the issue on VScode. VScode issue happened. at the same time when GIT stopped working. I kind of remember that this issue started after new Windows patches were installed. 
Here is a link about it. https://en.wikipedia.org/wiki/Windows_Registry

**Comment by dscho** [comment]
> I have no idea neither about it

What is the exact registry key?

**Comment by kiyochin9** [comment]
Sorry but it is my bad. When I cleared it, I did not save it prior to that. However, it should be similar to that of git-remote-https.exe, because "git-remote-https.exe", git-credential-manager.exe" and "git-cmd.exe" all have the same data except for their names. Here is their data.
"C:\WINDOWS\SoftwareDistribution\Download\Install\patchmypc-preventstart.exe" /StopProcess /ApplicationName="git-remote-https.exe"
"C:\WINDOWS\SoftwareDistribution\Download\Install\patchmypc-preventstart.exe" /StopProcess /ApplicationName="git-credential-manager.exe"
"C:\WINDOWS\SoftwareDistribution\Download\Install\patchmypc-preventstart.exe" /StopProcess /ApplicationName="git-cmd.exe".  
So, I assume that data for "git-bash.exe" was ""C:\WINDOWS\SoftwareDistribution\Download\Install\patchmypc-preventstart.exe" /StopProcess /ApplicationName="git-bash.exe".

**Comment by dscho** [comment]
I still do not know which registry key you are looking at. Those keys typically start with something like `HKEY_LOCAL_MACHINE\SYSTEM\...`.

From the file name of the executable that prevents your Git Bash from starting, though, I gather that this is [Patch My PC](https://patchmypc.com/)'s doing. I do not see how Git for Windows can help there.

**Comment by kiyochin9** [comment]
For your information, the registry key is HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/WindowsNT/CurrentVersion/Image File Execution Options/git-bash.exe. Under it, there are name "Debugger" and data.
Thanks for your help.

**Comment by dscho** [comment]
As you can see [here](https://github.com/search?q=org%3Agit-for-windows%20%22execution%20options%22&type=code), Git for Windows does not touch that registry key.

**Comment by rimrul** [comment]
> From the file name of the executable that prevents your Git Bash from starting, though, I gather that this is [Patch My PC](https://patchmypc.com/)'s doing. I do not see how Git for Windows can help there.

Certainly sounds like external software that's explicitly configured to interfere with Git for Windows operation. Not much we can do there.

**Comment by kiyochin9** [comment]
OK, thanks for your help, anyway. My IT guy just confirmed that some people in my company are having the same issue. So, I am hoping that they will find a solution soon.
