### ISSUE TITLE
Git for Windows SDK 1.0.1 - error: failed to update mingw32 (error invoking external downloader)

### ISSUE THREAD

**Issue by marsoltys** [git-for-windows/git#458]
After running this:
https://github.com/git-for-windows/build-extra/releases/download/git-sdk-1.0.1/git-sdk-installer-1.0.1-64.7z.exe 

I've got this output: 
```
:: Synchronizing package databases...
 git-for-windows         1996.0   B  1949K/s 00:00 [#####################] 100%
error: failed retrieving file 'mingw32.db' from repo.msys2.org : Connection time
d out after 10009 milliseconds
error: failed retrieving file 'mingw32.db' from downloads.sourceforge.net : Conn
ection timed out after 10006 milliseconds
error: failed retrieving file 'mingw32.db' from www2.futureware.at : The request
ed URL returned error: 404
error: failed to update mingw32 (unexpected error)
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Connection time
d out after 10013 milliseconds
error: failed retrieving file 'mingw64.db' from downloads.sourceforge.net : Conn
ection timed out after 10004 milliseconds
error: failed retrieving file 'mingw64.db' from www2.futureware.at : The request
ed URL returned error: 404
error: failed to update mingw64 (unexpected error)
error: failed retrieving file 'msys.db' from repo.msys2.org : Connection timed o
ut after 10013 milliseconds
error: failed retrieving file 'msys.db' from downloads.sourceforge.net : Connect
ion timed out after 10014 milliseconds
error: failed retrieving file 'msys.db' from www2.futureware.at : The requested
URL returned error: 404
error: failed to update msys (unexpected error)
error: failed to prepare transaction (could not find database)

There was a problem accessing the MSys2 repositories
If your setup requires an HTTP proxy to access the web,
please specify it here, otherwise leave it empty.

HTTP proxy:
```
I have proxy user environment variable set (HTTP_PROXY and HTTPS_PROXY) but anyway I have provided proxy in format: http://user:passs@proxy.example.com:8000 and after it hangs for quite long time and throws :

```
HTTP proxy: proxydata
        1 file(s) copied.
:: Synchronizing package databases...
error: failed to update mingw32 (error invoking external downloader)
```

I've tried  @galehar solution from here https://github.com/git-for-windows/git/issues/373#issuecomment-144088283

Deleted db.lck file from ```C:\git-sdk-64\var\lib\pacman``` and .part files from ```C:\git-sdk-64\var\lib\pacman\sync```

but result is still the same.

**Comment by dscho** [comment]
Could you remove the `-s` from the `XferCommand` line in your `/etc/pacman.conf` and try again?

**Comment by marsoltys** [comment]
Since today morning I've got one more error message regarding PGP signature:

```
error: git-for-windows: key "BB3AA74136C569BB" is unknown
error: key "BB3AA74136C569BB" could not be looked up remotely
:: Synchronizing package databases...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1996  100  1996    0     0   4743      0 --:--:-- --:--:-- --:--:--  4868
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   543  100   543    0     0   1615      0 --:--:-- --:--:-- --:--:--  1660
error: git-for-windows: key "BB3AA74136C569BB" is unknown
error: key "BB3AA74136C569BB" could not be looked up remotely
error: failed to update git-for-windows (invalid or corrupted database (PGP sign
ature))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:24 --:--:--     0
```

**Comment by dscho** [comment]
@marsoltys hmpf. The text version was much better. And by hiding this new, unrelated issue in a comment in this ticket, we now have a duplicate thread: https://github.com/git-for-windows/git/issues/465

I would really prefer to fix bugs than to sort out disorganized tickets...

**Comment by marsoltys** [comment]
I'm sorry @dscho but I didn't hide anything.
This "duplicated" issue popped out in addition to my first comment so there is still issue with installer.

In my first attempt (weirdly) GPG signature wasn't downloaded at all ...

Anyway, I'm trying to help ...

**Comment by elieux** [comment]
@marsoltys, the signatures were introduced few days ago, so that's probably why they didn't appear in your first attempt. Anyway, your error isn't related to signatures.

Did you try what @dscho suggested in [his previous comment about `XferCommand`](https://github.com/git-for-windows/git/issues/458#issuecomment-144765391)?

**Comment by marsoltys** [comment]
@elieux , yes.

I've included screenshot of output with -s option removed -> https://github.com/git-for-windows/git/issues/458#issuecomment-144945235

**Comment by dscho** [comment]
> I've included screenshot

Screenshots are really not a good method to convey text. It is much superior to cut and paste.

> I didn't hide anything.

Yes, you did. You hid a second bug report in the same ticket as the first. Now we have [diverging discussions](https://github.com/git-for-windows/git/issues/465) about the very same issue, but only I am participating in both, which puts an undue burden on me. This is not acceptable, therefore I will discuss this issue only in the other ticket. By now, this ticket is really messed up, is it not? I could imagine that the originally reported error message:

> failed retrieving file 'mingw32.db' from repo.msys2.org : Connection time d out after 10009 milliseconds

... simply indicates either that the server was not really reachable (which you could have verified by pasting the address `repo.msys2.org` into a web browser of your choice), or alternatively suggests that your network connection/proxy does not like that address. It is pretty unclear to me by now what issues persist and what do not, so I will hold back with more comments until the confusion clears.

**Comment by marsoltys** [comment]
> Screenshots are really not a good method to convey text. It is much superior to cut and paste.

Changed back to text (fresh run).

> Yes, you did. You hid a second bug report in the same ticket as the first. Now we have diverging discussions about the very same issue, but only I am participating in both, which puts an undue burden on me. This is not acceptable, therefore I will discuss this issue only in the other ticket. By now, this ticket is really messed up, is it not? I could imagine that the originally reported error message:

I've only indicated that since my first comment (and as you wanted output without -s) another issue popped up. That's all.
You've mentioned another ticket here so you could leave it as is to be sorted there rather diving in why I have mentioned it and that I shouldn't do that :)

>... simply indicates either that the server was not really reachable (which you could have verified by pasting the address repo.msys2.org into a web browser of your choice

Verified in browser and works fine (installer run and address verified just before posting this comment,)

**Comment by marsoltys** [comment]
I've found the reason of problem.

It was on my end.

As I mentioned in my first comment I had user environment variables set for HTTP_PROXY and HTTPS_PROXY (mainly for git and git-bash purposes).

Removing both from environment variables helped with connection.

I've hope that will help someone in the same situation.
