### ISSUE TITLE
Installer is not installing gcm even when checked

### ISSUE THREAD

**Issue by makinbacon21** [git-for-windows/git#4581]
- [✅] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
   64-bit
```
$ git --version --build-options

git version 2.41.0
cpu: x86_64
no commit associated with this build
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
   11 insider 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.23531.1001]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
   Enabled gcm, fs monitor, pseudo console support, checkout as-is, vscode as editor, and windows conhost

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

   Nothing I can think of--the binary just doesn't seem to be in program files. I am running an insider 
   build.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

   PowerShell Core

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push -f origin HEAD:lineage-18.1
```
 - What did you expect to occur after running these commands?

   I expected the gcm modal to show up

 - What actually happened instead?

   It prompted for username and password (doesn't work because 2FA)
   The binary for gcm is just not in the Git folder and I don't see it anywhere else

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

   Repo is irrelevant here

**Comment by dscho** [comment]
I cannot reproduce here:

```console
me@work MINGW64 ~
$ which git-credential-manager.exe
/mingw64/bin/git-credential-manager.exe

me@work MINGW64 ~
$ git version
git version 2.42.0.windows.2
```

This is in a Git Bash, for what it's worth.

**Comment by dscho** [comment]
What's your `git config --show-origin --get-all credential.helper` look like?

**Comment by makinbacon21** [comment]
Don't worry about it, I fixed it. I did need to manually add the git config entry though (that entry was blank) and I had to manually add the directory to PATH for git to find the command. Thanks for the help!
