### ISSUE TITLE
Git v2.42.0.windows.2 raises an error `LoadLibraryExW() failed with: Specified procedure not found`

### ISSUE THREAD

**Issue by KSR-Yasuda** [git-for-windows/git#4582]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit.

```
# Failed ver.
$ git --version --build-options
git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

# Successfull ver.
$ git --version --build-options
git version 2.42.0.windows.1
cpu: x86_64
built from commit: a2e49ec355ae22e74288fa74f50821f3cc1a1551
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19045.3324]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Added `pacman` module to Git-for-Windows env, and have updated packages through it.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
# Git v2.42.0.2 Failure
% git version
git version 2.42.0.windows.2

% git remote update 2>&1 | nkf -w
Fetching origin
error: LoadLibraryExW() failed with: 指定されたプロシージャが見つかりません。?
                                    # Saying "Specified procedure not found."

Fetching mine
error: LoadLibraryExW() failed with: 指定されたプロシージャが見つかりません。?

# The target repositories are accessed via HTTPS
# (https://github.com/simeji/winresizer.git).


# Downgrade Git to v2.42.0.1
% pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-git-2.42.0.1.a2e49ec355-1-any.pkg.tar.xz
loading packages...
warning: downgrading package mingw-w64-x86_64-git (2.42.0.2.2f819d1670-1 => 2.42.0.1.a2e49ec355-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-git-2.42.0.1.a2e49ec355-1

Total Installed Size:  49.66 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                          [------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                        [------------------------------------------------------------] 100%
(1/1) loading package files                                                                             [------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                       [------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                     [------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) downgrading mingw-w64-x86_64-git                                                                  [------------------------------------------------------------] 100%

% git --version
git version 2.42.0.windows.1
yasuda@Kujira3 MINGW64 ~/.vim/bundle/winresizer (develop)

% git remote update
Fetching origin
Fetching mine
    # v2.42.0.windows.1 works fine.


# Pacman Status
% pacman -Qu
groff 1.22.4-4 -> 1.23.0-1 [ignored]
mingw-w64-x86_64-git 2.42.0.1.a2e49ec355-1 -> 2.42.0.2.2f819d1670-1
```

Also `git fetch` fails.

 - What did you expect to occur after running these commands?

`git remote update` and `git fetch` work well.

 - What actually happened instead?

Fails by `LoadLibraryExW()` error as above.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

----

See <https://github.com/msys2/MSYS2-packages/issues/4003> (msys2 repo).

Is https://github.com/git-for-windows/git/issues/4573 related with this issue?

```
% pacman -F /mingw64/bin/libcurl-4.dll
mingw64/bin/libcurl-4.dll is owned by git-for-windows/mingw-w64-x86_64-curl 8.0.1-2
mingw64/bin/libcurl-4.dll is owned by git-for-windows/mingw-w64-x86_64-curl-gnutls 8.0.1-2
mingw64/bin/libcurl-4.dll is owned by git-for-windows/mingw-w64-x86_64-curl-winssl 8.0.1-2
mingw64/bin/libcurl-4.dll is owned by mingw64/mingw-w64-x86_64-curl 8.0.1-1
mingw64/bin/libcurl-4.dll is owned by mingw64/mingw-w64-x86_64-curl-gnutls 8.0.1-1
mingw64/bin/libcurl-4.dll is owned by mingw64/mingw-w64-x86_64-curl-winssl 8.0.1-1

% pacman -Ss mingw-w64-x86_64-curl
git-for-windows/mingw-w64-x86_64-curl 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-gnutls 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-gnutls-alternate 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-gnutls-pdb 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-openssl-alternate 8.2.1-1 [installed]
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-pdb 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-winssl 8.2.1-1 [installed]
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-winssl-alternate 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
git-for-windows/mingw-w64-x86_64-curl-winssl-pdb 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
mingw64/mingw-w64-x86_64-curl 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
mingw64/mingw-w64-x86_64-curl-gnutls 8.2.1-1
    Command line tool and library for transferring data with URLs (mingw-w64)
mingw64/mingw-w64-x86_64-curl-winssl 8.2.1-1 [installed]
    Command line tool and library for transferring data with URLs (mingw-w64)
```

**Comment by KSR-Yasuda** [comment]
This commit https://github.com/git-for-windows/git/commit/2f819d1670fff9a1818f63b6722e9959405378e3 causes this?

**Comment by KSR-Yasuda** [comment]
https://github.com/git-for-windows/git/issues/4573 was due to user-local install into non-ascii char named user home dir?

About it, I'm not in the case: installed globally into `C:\Program Files`.

```
% cygpath -w /
C:\Program Files\Git\
```

**Comment by dscho** [comment]
> This commit [2f819d1](https://github.com/git-for-windows/git/commit/2f819d1670fff9a1818f63b6722e9959405378e3) causes this?

Yes. But I don't understand how it can cause a problem. This commit replaces a `LoadLibraryExA()` call with a `LoadLibraryExW()` one, and it is common knowledge that the former function is essentially a wrapper around the latter one. So how on Earth can the former be present on your system but the latter be missing?

According to https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw, this function is in `kernel32.dll` and has been there since Windows Server 2003, i.e. for quite a while now.

And indeed, using the `dumpbin` tool from Visual Studio's Developer Prompt, I see both in my setup:

```console
C:\Program Files\Microsoft Visual Studio\2022\Community>dumpbin \Windows\system32\kernel32.dll /exports | find "LoadLibraryEx"
        998  3E5 00018350 LoadLibraryExA
        999  3E6 00014090 LoadLibraryExW
```

And if you have a Git for Windows SDK handy, you can try `objdump`:

```console
$ objdump -x  /c/Windows/system32/kernel32.dll  | grep LoadLibraryEx
        b3be8      24  LoadLibraryExA
        b3aa6      25  LoadLibraryExW
        [ 997] LoadLibraryExA
        [ 998] LoadLibraryExW
```

**Comment by KSR-Yasuda** [comment]
Yes, `LoadLibraryEx{A,W}` are of course found in my env.

```
% objdump -x  /c/Windows/system32/kernel32.dll  | grep LoadLibraryEx
    aec8e      24  LoadLibraryExW
    aee76      23  LoadLibraryExA
    [ 969] LoadLibraryExA
    [ 970] LoadLibraryExW
```

So, converted wide-char path for `LoadLibraryExW()` looks doubtful...

**Comment by dscho** [comment]
@KSR-Yasuda could you analyze with [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon)? (For testing, you should be able to use a Portable Git v2.42.0(2), so as to leave your working setup alone.)

**Comment by KSR-Yasuda** [comment]
@dscho Sorry for late reply.

[`PortableGit-2.42.0.2-64-bit.7z.exe`](https://github.com/git-for-windows/git/releases/download/v2.42.0.windows.2/PortableGit-2.42.0.2-64-bit.7z.exe) worked successfully.

So take logs on both of PortableGit v2.42.0.2 and Git-for-Win with git v2.42.0.2.

* [ProcessMonitor_Log.zip](https://github.com/git-for-windows/git/files/12508302/ProcessMonitor_Log.zip)
    * `Logfile_Git_Normal.PML`
        - PrtableGit v2.42.0.2 (works fine)
    * `Logfile_PortableGit.PML`
        - Git-for-Windows with Git v.2.42.0.2 package (`mingw-w64-x86_64-git-2.42.0.2.2f819d1670-1-any.pkg.tar.xz`; fails)

**Comment by KSR-Yasuda** [comment]
Change filter condition (Process name `git*`):

* [ProcessMonitor_Log_20230905_102509.zip](https://github.com/git-for-windows/git/files/12517769/ProcessMonitor_Log_20230905_102509.zip)

**Comment by KSR-Yasuda** [comment]
Change filter condition (Process Name `git*`):

* [ProcessMonitor_Log_20230905_104235.zip](https://github.com/git-for-windows/git/files/12517872/ProcessMonitor_Log_20230905_104235.zip)

**Comment by dscho** [comment]
> So take logs on both of PortableGit v2.42.0.2 and Git-for-Win with git v2.42.0.2.
> 
>     * [ProcessMonitor_Log.zip](https://github.com/git-for-windows/git/files/12508302/ProcessMonitor_Log.zip)
>       
>       * `Logfile_PortableGit.PML`
>         
>         * PrtableGit v2.42.0.2 (works fine)
>       * `Logfile_Git_Normal.PML`
>         
>         * Git-for-Windows with Git v.2.42.0.2 package (`mingw-w64-x86_64-git-2.42.0.2.2f819d1670-1-any.pkg.tar.xz`; fails)

I don't see any entries with Process Name `git-remote-https.exe` in those logs.

> Change filter condition (Process Name `git*`):
> 
>     * [ProcessMonitor_Log_20230905_104235.zip](https://github.com/git-for-windows/git/files/12517872/ProcessMonitor_Log_20230905_104235.zip)

So... portable Git's `git-remote-https.exe` succeeded:

![image](https://github.com/git-for-windows/git/assets/127790/0cb44c36-89a0-4f1f-8475-5b698e52fe76)

And so did regular Git for Windows v2.42.0(1):

![image](https://github.com/git-for-windows/git/assets/127790/6b3fd3aa-7526-428b-8deb-b16eaaf716e0)

... but so did Git for Windows v2.42.0(2)?!?!?

![image](https://github.com/git-for-windows/git/assets/127790/550a5ce1-73ea-4f5c-86e7-2e13b444357c)

I thought the claim was that v2.42.0(2) did _not_ work?

**Comment by KSR-Yasuda** [comment]
Replacing `/mingw64/libexec/git-core/git-remote-https.exe` with v2.42.0.windows.1 binary, it works.
I think surely `git-remote-https.exe` v2.42.0.windows.2 is failing...

**Comment by dscho** [comment]
> rechecked process / thread exit results of git-remote-https.exe, but they say SUCCESS.

Can you verify that the fetch works? E.g. by cloning a repository?

> Although, the LoadLibraryExW() failed log is appearing.

The exit status, though...

 How familiar are you with `gdb`?

**Comment by rimrul** [comment]
There is a [fallback layer here](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L184-L193).
This could be [the first `load_library()`](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L188) failing, while [the second one](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L191) succeeds.

You don't get the `fatal: failed to load library 'libcurl-4.dll'` error message, right?

**Comment by KSR-Yasuda** [comment]
@dscho

> Can you verify that the fetch works? E.g. by cloning a repository?

It looks fetch itself is working.
`git clone https://...` shows `LoadLibraryExW()` error, but cloned working dir is generated.

> How familiar are you with `gdb`?

GDB debugging looks hard for me to trace `git-remote-https.exe` process forked from `git.exe`.

If https://github.com/git-for-windows/git/issues/4573 is the cause, could you make `git-remote-https.exe` binary with some debug log there?

@rimrul

> You don't get the `fatal: failed to load library 'libcurl-4.dll'` error message, right?

No.
I can see only
`error: LoadLibraryExW() failed with: 指定されたプロシージャが見つかりません。?`
error message once for each https remote access.

**Comment by KSR-Yasuda** [comment]
> There is a [fallback layer here](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L184-L193).
> This could be [the first `load_library()`](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L188) failing, while [the second one](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L191) succeeds.

Then, the error message
`error: LoadLibraryExW() failed with: 指定されたプロシージャが見つかりません。?`
itself is not so much problem, right?

If so, could you suppress the error message?
It looks as if something terrible is happening...

**Comment by dscho** [comment]
What `http.sslBackend` are you using?

> This could be [the first `load_library()`](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L188) failing, while [the second one](https://github.com/git-for-windows/git/blob/2f819d1670fff9a1818f63b6722e9959405378e3/compat/lazyload-curl.c#L191) succeeds.

Indeed. Let me add something to clarify the error message.

**Comment by dscho** [comment]
> It's `openssl`.

In that case, the fallback is not supposed to work at all, as `libcurl-4.dll` should link only to Secure Channel.

Can we first compare a couple of file hashes?

```console
$ sha256sum.exe /mingw64/bin/libcurl* /mingw64/libexec/git-core/libcurl*
e389b4833c03054b9598ed1c3204fe09ad4f88fd3bcf2990dd0590be78cd9aef */mingw64/bin/libcurl-4.dll
2cf709b98336df9feff9c09e67d0e55bdce8293529515eb400d4bac1f4410f5e */mingw64/bin/libcurl-openssl-4.dll
e389b4833c03054b9598ed1c3204fe09ad4f88fd3bcf2990dd0590be78cd9aef */mingw64/libexec/git-core/libcurl-4.dll
2cf709b98336df9feff9c09e67d0e55bdce8293529515eb400d4bac1f4410f5e */mingw64/libexec/git-core/libcurl-openssl-4.dll
```

**Comment by dscho** [comment]
> If so, could you suppress the error message?

BTW about this: we already suppress this error message, we even suppress the `LoadLibraryExW()` call [when the file cannot even be found](https://github.com/git-for-windows/git/blob/v2.42.0.windows.2/compat/lazyload-curl.c#L59).

You only see the error message because the DLL exists but cannot be loaded, but the fall-back `libcurl-4.dll` exists, can be loaded _and apparently links to OpenSSL_. But that cannot be the `libcurl-4.dll` shipped with Git for Windows v2.42.0(2) because that one does _not_ link to OpenSSL. Here is an `ldd` call (from the Git for Windows SDK because `ldd` is not shipped as part of regular Git for Windows):

```console
$ ldd /c/Program\ Files/Git/mingw64/bin/libcurl-4.dll | grep mingw
        libbrotlidec.dll => /c/Program Files/Git/mingw64/bin/libbrotlidec.dll (0x7ff9aef70000)
        libbrotlicommon.dll => /c/Program Files/Git/mingw64/bin/libbrotlicommon.dll (0x7ff9a6010000)
        libidn2-0.dll => /c/Program Files/Git/mingw64/bin/libidn2-0.dll (0x7ff9a5d90000)
        libpsl-5.dll => /c/Program Files/Git/mingw64/bin/libpsl-5.dll (0x7ff9a5d60000)
        libssh2-1.dll => /c/Program Files/Git/mingw64/bin/libssh2-1.dll (0x7ff9a5bb0000)
        libiconv-2.dll => /c/Program Files/Git/mingw64/bin/libiconv-2.dll (0x7ff9644a0000)
        libintl-8.dll => /c/Program Files/Git/mingw64/bin/libintl-8.dll (0x7ff964470000)
        libunistring-5.dll => /c/Program Files/Git/mingw64/bin/libunistring-5.dll (0x7ff980e20000)
        libunistring-5.dll => /c/Program Files/Git/mingw64/bin/libunistring-5.dll (0x1ed78360000)
        zlib1.dll => /c/Program Files/Git/mingw64/bin/zlib1.dll (0x7ff964370000)
        libzstd.dll => /c/Program Files/Git/mingw64/bin/libzstd.dll (0x7ff9924e0000)
```

That is opposed to `libcurl-openssl-4.dll`:

```console
$ ldd /c/Program\ Files/Git/mingw64/bin/libcurl-openssl-4.dll | grep mingw
        libbrotlidec.dll => /c/Program Files/Git/mingw64/bin/libbrotlidec.dll (0x7ff9aef70000)
        libbrotlicommon.dll => /c/Program Files/Git/mingw64/bin/libbrotlicommon.dll (0x7ff9a74e0000)
        libidn2-0.dll => /c/Program Files/Git/mingw64/bin/libidn2-0.dll (0x7ff9a6030000)
        libpsl-5.dll => /c/Program Files/Git/mingw64/bin/libpsl-5.dll (0x7ff9a6d50000)
        libssh2-1.dll => /c/Program Files/Git/mingw64/bin/libssh2-1.dll (0x7ff9a5fe0000)
        libiconv-2.dll => /c/Program Files/Git/mingw64/bin/libiconv-2.dll (0x7ff9644a0000)
        libintl-8.dll => /c/Program Files/Git/mingw64/bin/libintl-8.dll (0x7ff964470000)
        libunistring-5.dll => /c/Program Files/Git/mingw64/bin/libunistring-5.dll (0x7ff98ae60000)
        zlib1.dll => /c/Program Files/Git/mingw64/bin/zlib1.dll (0x7ff964370000)
        libzstd.dll => /c/Program Files/Git/mingw64/bin/libzstd.dll (0x7ff9a2240000)
        libnghttp2-14.dll => /c/Program Files/Git/mingw64/bin/libnghttp2-14.dll (0x7ff9a5d80000)
        libssl-3-x64.dll => /c/Program Files/Git/mingw64/bin/libssl-3-x64.dll (0x7ff9a5b50000)
        libcrypto-3-x64.dll => /c/Program Files/Git/mingw64/bin/libcrypto-3-x64.dll (0x7ff980b50000)
        libcrypto-3-x64.dll => /c/Program Files/Git/mingw64/bin/libcrypto-3-x64.dll (0x24187140000)
```

Here, you can clearly see that it links to `libcrypto-3-x64.dll` (which is part of OpenSSL v3.1.2 shipped with Git for Windows).

**Comment by KSR-Yasuda** [comment]
> Can we first compare a couple of file hashes?

```
% sha256sum.exe /mingw64/bin/libcurl* /mingw64/libexec/git-core/libcurl*
e389b4833c03054b9598ed1c3204fe09ad4f88fd3bcf2990dd0590be78cd9aef */mingw64/bin/libcurl-4.dll
2cf709b98336df9feff9c09e67d0e55bdce8293529515eb400d4bac1f4410f5e */mingw64/bin/libcurl-openssl-4.dll
4bd7e6dff2956580239f3f517b469a8ffe0e65c3ac1c619dc864ea1eeef0f071 */mingw64/libexec/git-core/libcurl-4.dll
```

`/mingw64/bin/libcurl{,-openssl}-4.dll` are the same;
but `/mingw64/libexec/git-core/libcurl{,-openssl}-4.dll` files are different.

**Comment by dscho** [comment]
> 4bd7e6dff2956580239f3f517b469a8ffe0e65c3ac1c619dc864ea1eeef0f071 */mingw64/libexec/git-core/libcurl-4.dll

That corresponds to the one from `mingw-w64-x86_64-curl 7.88.1-1`. Whose `libcurl-4.dll` was included in Git for Windows v2.40.0 and v2.40.1.

I get the suspicion that you're trying to upgrade via `pacman` instead of via installing Git for Windows via the installer, which is the only officially supported way.

Is my suspicion correct @KSR-Yasuda?

**Comment by KSR-Yasuda** [comment]
> I get the suspicion that you're trying to upgrade via `pacman`

Yes.

So, correct `/mingw64/libexec/git-core/libcurl{,-openssl}-4.dll` binaries are not updated via `pacman`?

**Comment by dscho** [comment]
> > I get the suspicion that you're trying to upgrade via `pacman`
> 
> Yes.

That's bad. Using `pacman` in `C:\Program Files\Git` is even less supported than [installing Git for Windows in MSYS2 proper](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper#please-note-that-this-scenario-is-not-officially-supported-by-git-for-windows).

Basically, you are messing with files that Git for Windows assumes are under its installer's control, and hence you run into problems like these, where you end up using obsolete versions of software components without knowing, until you hit a bug that is simply explained by inconsistencies that are caused by this kind of meddling.

So why is running `pacman` in `C:\Program Files` even worse than installing Git for Windows into MSYS2 proper? Because you need to do the former _as administrator_, running all the pre-install and post-install scripts in elevated mode, and those scripts are not nearly as well vetted as whatever commands Git for Windows' installer runs. Those are carefully vetted, reviewed over and over again, to make sure that nothing gets executed as administrator that could make the machine vulnerable.

> So, correct `/mingw64/libexec/git-core/libcurl{,-openssl}-4.dll` binaries are not updated via `pacman`?

The `/mingw64/libexec/git-core/*.dll` files are hard-linked copies of `/mingw64/bin/*.dll`, and they exist mainly as a safeguard against DLL search directory attacks.

These copies are not deemed necessary in the Git for Windows SDK, under the assumption that the SDK is used only by developers experienced enough not to allow any DLL search directory attacks to be launched on their machines.

Therefore, [those copies are made by the end user-facing installer](https://github.com/git-for-windows/build-extra/blob/0e38d129f8a4cdee42d4c2998f3d317cff0f545d/installer/install.iss#L2723-L2744).

So, in the interest of saving time in the future (just imagine the amount of time we spent in this here ticket, this was time I could not spend on fixing actual bugs, for example) I strongly suggest to switch back to the officially-supported way to upgrade Git for Windows: via the installer.

**Comment by KSR-Yasuda** [comment]
@dscho Okay, I got it.
Sorry for taking your time too much.
Thank you.
