### ISSUE TITLE
Connection refused while trying to mount a ssh-agent sock created in another container

### ISSUE THREAD

**Issue by lmb-djaquier** [git-for-windows/git#4587]
Hello,

I have that strange issue, while trying to use an ssh-agent sock created in a container (Intellij teamcity build agent, running in a container, using a native git settings, that means it uses a "real" install of mingit in c:\git\...

The agent starts, and SSH_AUTH_SOCK and SSH_AGENT_PID are well set, available, and can be use in the agent container.

for example, a
`ssh-add -l`

prints

`ssh-ed25519 <superthing> <superusername>`

But, I would like to build our software in a separated container (using docker-out-of-docker). 

**_The sock is well mount in the build container. (same permissions, same mount point, same user runing the container, etc...)._**

Teamcity launches the agent with that kind of command:
`ssh-agent -s -a C:\buildAgent\temp\buildTmp\ssh11386611635240999197sock`

a mingw LS command in the teamcity agent container:

`srw-r--r-- 1 ContainerAdministrator 380929 0 Sep  5 16:09 C:\buildAgent\temp\buildTmp\ssh11386611635240999197sock`

and the same in the build container

`srw-r--r-- 1 380929 380929 0 Sep  5 16:09 C:\buildAgent\temp\buildTmp\ssh11386611635240999197sock`

I set an env var in the build container with the same value as the teamcity agent.

But, when I try to 
`ssh-add -l`

I get that error
`Error connecting to agent: Connection refused`

and when I try to do a push

```
ContainerAdministrator@<hostname>: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Both git setup are aligned, with the same version (MinGit-2.42.0.2-64-bit.zip).

I did exactly the same thing with ubuntu docker images, sharing a .sock file and it works like a charm. The only difference is that I mount the .sock directly with linux. With windows I can only mount a directory. Could it makes the difference in file addressing? 

I know it's not a pure "git" issue, but it's an issue with something distributed with git (ssh-agent).

Thanks in advance if someone could help me.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.4737]
-> Windows 2019 docker images
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

MinGit-2.42.0.2-64-bit.zip default setup
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**Comment by dscho** [comment]
The SSH agent communicates via Unix sockets. The MSYS2 variant of OpenSSH therefore uses MSYS2's emulated Unix sockets, which only work as long as server and client are using the same MSYS2 runtime heap, i.e. they _must_ live in the same process space.

If you want an SSH agent to be shared across a container boundary, you will have much better luck using the [pure Win32 version of OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) than the one bundled in Git for Windows (which, for backwards compatibility, must work on Windows 7, something Win32-OpenSSH can conveniently choose not to support).

**Comment by lmb-djaquier** [comment]
thanks @dscho , that was unfortunately one of my suppositions.

I'll give a try with the pure win32 version. Do you know if it matches the version bundled with windows server 2019 containers? Because that version was unfortunately not compatible with Teamcity agent "ssh-agent" build feature, as it cannot be run by cli with a command like  

`ssh-agent -s -a <socket path>`

**Comment by dscho** [comment]
I am not familiar with that space, therefore I cannot answer that question.

**Comment by dscho** [comment]
Closing, as that use case is outside the responsibility of Git for Windows.
