### ISSUE TITLE
Download and install Git for Windows pop-up window

### ISSUE THREAD

**Issue by krisanathema** [git-for-windows/git#4591]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.1
cpu: x86_64
built from commit: a2e49ec355ae22e74288fa74f50821f3cc1a1551
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not sure if this is related, but I also cannot download packages from sources in R, a different software, potentially indicating some issues on my machine to allow software connections to the Internet?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

After starting my Windows 10 laptop, I get a pop-up window from Git for Windows. It states: “Download and install Git for Windows v2.42.0.windows.2?” and has two choice buttons: “Yes” and “No”. The version number is irrelevant: I had this issue for many versions. When I click on “Yes”, nothing happens. I am just wondering whether this is normal and, if so, why it is asking to download and install and then not doing it. If I want to update, I need to do it directly from Git Bash.

- What did you expect to occur after running these commands?

I would have expected that clicking on “Yes” would start the downloading process and also install the new version.

 - What actually happened instead?

Nothing.

**Comment by dscho** [comment]
> After starting my Windows 10 laptop, I get a pop-up window from Git for Windows. It states: “Download and install Git for Windows v2.42.0.windows.2?” and has two choice buttons: “Yes” and “No”. The version number is irrelevant: I had this issue for many versions. When I click on “Yes”, nothing happens. I am just wondering whether this is normal and, if so, why it is asking to download and install and then not doing it. If I want to update, I need to do it directly from Git Bash.

I cannot reproduce, it works here.

@krisanathema can you execute the following command CMD in `C:\Program Files\Git`?

```cmd
cmd\git.exe update-git-for-windows --testing --gui
```

**Comment by krisanathema** [comment]
Thanks @dscho. Yeah, I assume it will not be reproducible for most users, because it seems to be a problem with my machine, but I cannot find the solution and not even identify the problem.

Here is the output of the command:

```
C:\Users\Christophe Bousquet>git update-git-for-windows --testing --gui
Git for Windows 2.42.0.windows.1 (64-bit)
Update 2.42.0.windows.2 is available
```

It also launched the Git for Windows pop-up window. Then, when I clicked on "Yes", it adds the following message in the CMD:

```
Git for Windows 2.42.0.windows.1 (64-bit)
Update 2.42.0.windows.2 is available
The user clicked on action #0
################################################################################################################ 100.0%
/usr/bin/start: line 8: C:\WINDOWS\system32\cmd.exe;C:\Users\Christophe Bousquet\AppData\Roaming\Python\Python39\Scripts: No such file or directory
```

So it seems to recognize that I clicked on "Yes", but then does not find a file somewhere...

**Comment by dscho** [comment]
Oh, is that a multi-value `COMSPEC` I'm seeing there?

**Comment by dscho** [comment]
[This](https://github.com/git-for-windows/git-sdk-64/blob/93cb6b4b7b8806e8d9b88bb7589e53c2275432ec/usr/bin/start#L8) is that mentioned line 8, with that `COMSPEC` I talked about.

**Comment by dscho** [comment]
But Microsoft's own [documentation of the CMD built-in](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start) `start` says:

> If you run a command that contains the string CMD as the first token without an extension or path qualifier, CMD is replaced with the value of the COMSPEC variable. This prevents users from picking up `cmd` from the current directory.

That reads to me as if `COMSPEC` is not intended as a semicolon-separated, multi-valued variable. Instead, it should be the absolute path to the `cmd.exe` that should be used in `start cmd [...]` invocations (to prevent a `cmd.bat` in the current directory from being picked up by mistake).

So `git-update-for-windows` (or better: `/usr/bin/start`) got it right, methinks.

**Comment by dscho** [comment]
> `C:\WINDOWS\system32\cmd.exe;C:\Users\Christophe Bousquet\AppData\Roaming\Python\Python39\Scripts`

The second part does not even looks like an executable.

@krisanathema maybe your `~/.profile` appends the `Scripts` directory to `COMSPEC` but wants to do that to `PATH` instead?

**Comment by krisanathema** [comment]
Thanks @dscho. By specifying ComSpec correctly [only 1 value and without a semi-column], I manage to solve this Git for Windows issue, but also another one related to installing packages from source in R, both apparently related to this mispecification.
