### ISSUE TITLE
Git-2.42.0.2  bash Chinese characters are garbled

### ISSUE THREAD

**Issue by ouyang7923** [git-for-windows/git#4595]
Git-2.42.0.1  bash is all ok

Git-2.42.0.2 , It is no problem to enter the command in Chinese, 
![image](https://github.com/git-for-windows/git/assets/105358618/a1267c33-a247-49bc-ad2f-bc69cc965cd2)

after executing the java mvn command, the internal Chinese characters are all garbled.
![image](https://github.com/git-for-windows/git/assets/105358618/91f36694-b235-4f83-9f42-018a4b41f941)

**Comment by dscho** [comment]
@ouyang7923 the issue reporting template (which you deleted instead of populating it) asked for information that would have come in handy here.

As that information is lacking, I only have the suggestion to you to reinstall Git for Windows, toggling the "Enable Pseudo Console support" checkbox.

**Comment by ouyang7923** [comment]
@dscho  After following your method, the characters are displayed normally. The strange thing is that the previous version was also installed by clicking next all the way, and I have never encountered this problem

**Comment by dscho** [comment]
The previous version had a bug and inadvertently interpreted that checkbox in the opposite way.
