### ISSUE TITLE
Git Setup Fails with Error "Unable set set system config"

### ISSUE THREAD

**Issue by msitt** [git-for-windows/git#4604]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

I am attempting to install `Git-2.42.0.2-64-bit.exe`.

```
$ git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.4252]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

In my environment I do have `GIT_CONFIG` and `GIT_CONFIG_GLOBAL` environment variables set. They are both set to `C:\Users\msitt\.gitconfig`.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

N/A

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Run the installer and choose any custom option.

 - What did you expect to occur after running these commands?

The setup completes and options are set successfully.

 - What actually happened instead?

The setup errors every time it tries to set the custom options. There is a popup for each option with an error. For instance, the first one states:
```
Unable to set system config "diff.astextplain.textconv":="astextplain": exit code 129

stderr:
error: only one config file at a time
usage: git config [<options>]
...
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
> In my environment I do have `GIT_CONFIG` and `GIT_CONFIG_GLOBAL` environment variables set. They are both set to `C:\Users\msitt\.gitconfig`.

That will probably break much more than just the Git for Windows installer.

> Unable to set system config "diff.astextplain.textconv":="astextplain": exit code 129
> 
> stderr:
> error: only one config file at a time
> usage: git config [<options>]
> ...

I guess that could be addressed by https://github.com/git-for-windows/build-extra/pull/529

**Comment by msitt** [comment]
Thanks for the quick response. After reading more about GIT_CONFIG, I believe this was used to force the location of the .gitconfig file, because our corporate network has the HOME dir on a network drive.

I have removed these vars and am able to rerun the installer successfully.
