### ISSUE TITLE
Problem with "until" statement in Bash script running on Windows...

### ISSUE THREAD

**Issue by htartisan** [git-for-windows/git#4613]
- [ ] I was trying to run a Bash script in the Windows GIT Bash shell, and it hangs at at "until" statement (that is not an issue on the Linux Bash shell).... see below:

#echo "Waiting for fastbootd over TCP from Recovery, pinging $1"
until $(ping -c1 $1 &>/dev/null); do :; done

### Setup

- GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)

```
$ git --version --build-options

git version 2.41.0.windows.1
cpu: x86_64
built from commit: ff94e79c4724635915dbb3d4ba38f6bb91528260
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 11 64 bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.2283]
(c) Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

*type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
#echo "Waiting for fastbootd over TCP from Recovery, pinging $1"
until $(ping -c1 $1 &>/dev/null); do :; done

```

 - What did you expect to occur after running these commands?

The script should pause at the "unitl" statement, waiting for the "ping" to succeed, and then proceed with the rest of the script/

 - What actually happened instead?

The script hangs at the "until" statement indefinitly

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by rimrul** [comment]
> $(ping -c1 $1 &>/dev/null)

I don't think we ship a `ping.exe`, so that's probably [Microsoft ping](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ping), so you'd need something like 

```bash
$(ping //n 1 $1 &>/dev/null)
```

**Comment by dscho** [comment]
I'll assume that the problem was the expectation that Windows' `ping.exe` supports the same command-line arguments as Linux' `ping`.
