### ISSUE TITLE
.gitconfig with another drive than the C:

### ISSUE THREAD

**Issue by 0-Sacha** [git-for-windows/git#4621]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.2283]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No, execpt the fact that I have one Windows 11 Pro 22H2 and a Pop!OS 22.04 LTS, with a shared partition D: drive on FAT32, not encrypted. My C: Windows drive and my Pop!OS root partition are encrypted.

The encryption detail isn't really interesting but my C: and D: drives will makes sense later.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell 7.3.7 on Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

It is a litlle bit complicated to explain in one short example (BTW I have firstly publish that under a stackoverflow, but this place is probably more adequate, sorry for the duplicate : https://stackoverflow.com/questions/77212554/git-config-issue-on-another-drive, but I have reinstalled git in the meantime)

So I have setup a git config to have a work folder and a personal folder:

-It work fine for my personal folder witch is on my C drive (NTFS), it use my personal@email.com
-Not for my work folder witch is on my D drive (FAT32), it use the default@email.com (located in my .gitconfig) but didn't used my work@email.com

Here it is my .gitconfig (I've tested to inverse the order of the two and that changed nothing)
```ini
[user]
    email = default@email.com
    name = Default

[includeIf "gitdir/i:D:/Work/**"]
    path = ~/.gitconfig-work
[includeIf "gitdir/i:C:/Personal/**"]
    path = ~/.gitconfig-personal
```

Here is my .gitconfig-work
```ini
[user]
	email = work@email.com
	name = Work
```

Here is my .gitconfig-personal
```ini
[user]
	email = personal@email.com
	name = Personal
```

 - What did you expect to occur after running these commands?

So here it is the result of my Personal config (This one works : it use my personal@email.com)
```
PS C:\Personal> mkdir test

    Directory: C:\Personal

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           10/2/2023 12:17 AM                test

PS C:\Personal> cd .\test\
PS C:\Personal\test> git init
Initialized empty Git repository in C:/Personal/test/.git/
PS C:\Personal\test> git config --show-origin --get user.email
file:C:/Users/Sacha/.gitconfig-personal        personal@email.com
PS C:\Personal\test>
```

I was expecting for my work folder to use the .gitconfig-work, I should be getting work@email.com

 - What actually happened instead?

And this one is the result for my Work config and it didn't work (it use default@email.com)
```
PS D:\Work> mkdir test

    Directory: D:\Work

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           10/2/2023 12:16 AM                test

PS D:\Work> cd .\test\
PS D:\Work\test> git init
Initialized empty Git repository in D:/Work/test/.git/
PS D:\Work\test> git config --show-origin --get user.email
file:C:/Users/Sacha/.gitconfig  default@email.com
PS D:\Work\test>
```

I've tested when assigning a true path to my D drive (so I could use it like C:/Shared) but didn't changed anythings.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This issue is for all my repository, even newly created ones.

BTW : thanks for maintaining this project and thanks to all people that will help.

**Comment by dscho** [comment]
What gitdir path does `git rev-parse --absolute-git-dir` report?

**Comment by 0-Sacha** [comment]
Ok so for my personal folder I got this :
```
PS C:\Personal> cd .\test\
PS C:\Personal\test> git rev-parse --absolute-git-dir
C:/Personal/test/.git
```

And for my Work I got this :
```
PS D:\Work> cd .\test\
PS D:\Work\test> git rev-parse --absolute-git-dir
fatal: detected dubious ownership in repository at 'D:/Work/test'
'D:/Work/test' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory D:/Work/test
PS D:\Work\test>
```

But after adding the path as safe to my .gitconfig it work well :
```
PS D:\Work\test> git config --show-origin --get user.email
file:C:/Users/Sacha/.gitconfig-work     work@email.com
PS D:\Work\test>
```


And by adding this in my .gitconfig:
```
[safe]
	directory = *
```
Now every repository works :
```
PS D:\Work> cd .\newtest\
PS D:\Work\newtest> git init
Initialized empty Git repository in D:/Work/newtest/.git/
PS D:\Work\newtest> git config --show-origin --get user.email
file:C:/Users/Sacha/.gitconfig-work     work@email.com
```

Though I can't make it working with 
```
[safe]
    directory = D:/Work/
    directory = D:/Work/*
    directory = D:/Work/**
```
Is there an option to specify all subdirectories of a directory ?

At least thanks that works fine, you can close if you want, I will send the answer to my previous stackoverflow post.

**Comment by rimrul** [comment]
> Is there an option to specify all subdirectories of a directory ?

No. There is only `*`, `~` expansion and `%(prefix)` expansion.

**Comment by 0-Sacha** [comment]
Ok thanks, I will leave *. Thanks for your help!
