### ISSUE TITLE
 Microsoft Smart App Control - Git - git-bash.exe

### ISSUE THREAD

**Issue by goseecal99** [git-for-windows/git#4627]
Hi Git Team,

We're part of the Microsoft team that owns Smart App Control ([Smart App Control - Windows apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/apps/develop/smart-app-control/overview)), which requires applications to sign all of their executable files (exe, dll, msi, tmp, and a few other file formats). 
 
We found during internal testing and/or from user feedback that your app, git-bash.exe, is not correctly signed. 
 
Block Event: FileName: \Device\HarddiskVolume7\Program Files\Git\git-bash.exe
Calling Process: \Device\HarddiskVolume7\Windows\explorer.exe
Sha256 Hash: 42F2E685686FB6356A195709AF912C7B9D424466BD7C6D69258AADA5E80AC3C2
 
Signing your app is in your best interest, as it positively identifies you as the developer of your application to your customers installing and running your apps, and they can rest assured that your app hasn't been tampered with. For the purposes of Smart App Control, all app binaries including .exe, .dll, .tmp files, and uninstallers all need to be signed.
 
For more information on code signing, please refer to: [Sign your app for Smart App Control compliance - Windows apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/apps/develop/smart-app-control/code-signing-for-smart-app-control)
 
Please confirm if the unsigned file(s) will be signed in this or a future build, or if there is no intent to rectify the unsigned executable file(s).executable file(s).

Thanks,

Enterprise & Security - Platform Integrity Team
v-roswing@microsoft.com

**Comment by rimrul** [comment]
> requires applications to sign all of their executable files (exe, dll, msi, tmp, and a few other file formats).

Which other formats are we talking about?

> We found during internal testing and/or from user feedback that your app, git-bash.exe, is not correctly signed.

There is a [signing step](https://github.com/git-for-windows/MINGW-packages/blob/6204770b17d0c774fa26536b157100f57d9dc6bc/mingw-w64-git/PKGBUILD#L218) that should [sign that executable](https://github.com/git-for-windows/MINGW-packages/blob/6204770b17d0c774fa26536b157100f57d9dc6bc/mingw-w64-git/mingw-w64-git.mak#L60). I could see the Conhost installer option invalidating that signature, though.
Which Git for Windows Version are we talking about? Which installer options did you choose?

> For the purposes of Smart App Control, all app binaries including .exe, .dll, .tmp files, and uninstallers all need to be signed.

That's a lot of files that would need signing. A significant portion of those `.exe` and `.dll` files come directly from 3rd parties ( [Msys2](https://github.com/msys2/), [Git LFS](https://github.com/git-lfs/git-lfs/), [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager/)). Some 3rd party binaries are already signed by their originaating parties, most aren't. Ideally we'd probably want all binaries signed by their originating parties (as opposed to us signing 3rd party binaries), right?

**Comment by goseecal99** [comment]
Hi Matthias,

The only file of which we are currently aware is Git\git-bash.exe, but that doesn't mean others may not be flagged as the Smart App Control program moves from Windows Insider to the public in coming months. 

In speaking with a Git Hub contact, we understand this is a pretty big ask, apologetically. He mentioned there are over 400 exe files and 250 dll files, which would make signing them all burdensome.  Perhaps with automation it might be a bit easier.  

We don't have testing info to share unfortunately - this exe was reported via a Windows Insider Program participant so context is minimal. We don't have version info or installer option choice to share with you. We would advise it's best that 3rd party binaries are the best signatories of their unsigned files, yes. 

Thanks,

Enterprise & Security - Platform Integrity Team
[v-roswing@microsoft.com](mailto:v-roswing@microsoft.com)

**Comment by goseecal99** [comment]
Hi Matthias,

I think better we take this conversation off the forum to private email. Could you please email me your message above at v-roswing@microsoft.com?

Thanks,

Enterprise & Security - Platform Integrity Team
[v-roswing@microsoft.com](mailto:v-roswing@microsoft.com)

**Comment by dscho** [comment]
> better we take this conversation off the forum to private email.

I am the Git for Windows maintainer and I do _not_ approve of taking such discussions private. This is an _open_ source project, not a private source project.

As to `git-bash.exe` not being signed, I fail to understand what the problem is supposed to be:

|![image](https://github.com/git-for-windows/git/assets/127790/2cdb9b58-4e44-4d73-95ea-dbfc2e323459)|![image](https://github.com/git-for-windows/git/assets/127790/54e5dcd7-e350-417e-a0a2-2e5f4a03dd85)|![image](https://github.com/git-for-windows/git/assets/127790/3c81c35e-ba61-4626-b227-c1bba8547db4)|
|---|---|---|

As to code-signing the 3rd-party `.dll`/`.exe` files: That would send the message that the Git for Windows project testifies that all those files were vetted, which is impractical. So: Respectfully I decline the suggestion that the Git for Windows project should code-sign those.
