### ISSUE TITLE
Feature Request: Please add a comprehensive command line example for installing Git for Windows unattended

### ISSUE THREAD

**Issue by SetTrend** [git-for-windows/git#4630]
I need administrators to install Git for Windows with particular settings. For us, it's particularly important to use Git with the Windows certificate store.

At this time, https://github.com/git-for-windows/build-extra does not provide a comprehensive example in the [`ReadMe.md`](https://github.com/git-for-windows/build-extra) file, demonstrating what arguments to provide to the installer when installing Git for Windows non-interactively.

Please, add a comprehensive example to the `ReadMe.md` file, providing arguments for all installation parameters with default or alternative values.

---

 - [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
> git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
> cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3448]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled

**Comment by rimrul** [comment]
> At this time, https://github.com/git-for-windows/build-extra does not provide a comprehensive example in the [`ReadMe.md`](https://github.com/git-for-windows/build-extra) file, demonstrating what arguments to provide to the installer when installing Git for Windows non-interactively.

The `README.md` in `build-extra` would be an odd place for that, as users probably wouldn't look in `build-extra` and it currently barely talks about the installer at all. Maybe the `README.md` in this repo would be more appropriate.

The installer basically accepts all arguments listed [here](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline) plus `/o`. `/o` allows you to provide the options usually found in the `.inf` files used by `/LOADINF` and `/SAVEINF` on the command line in the format `/o:key=value`.

For an unattended install from the commandline you'll typically want something like `/VERYSILENT /SUPPRESSMSGBOXES /NORESTART`.

> I need administrators to install Git for Windows with particular settings. For us, it's particularly important to use Git with the Windows certificate store.

So that would be `/o:CurlOption=WinSSL` in addition to the options for an unattended install.

**Comment by SetTrend** [comment]
Thanks for clarifying!

Yet, where can we find all `/o` keys and values listed?

**Comment by rimrul** [comment]
|Key|Values|Default|Remark|
|---|---|---|---|
|EditorOption|Nano, VIM, Notepad++, VisualStudioCode, VisualStudioCodeInsiders, SublimeText, Atom, VSCodium, Notepad, Wordpad, CustomEditor|VIM||
|CustomEditorPath|||Path and options for custom text editor (only in combination with `EditorOption=CustomEditor`)|
|DefaultBranchOption|||Default branch name|
|PathOption|BashOnly, Cmd, CmdTools|Cmd||
|SSHOption|OpenSSH, ExternalOpenSSH, Plink|OpenSSH||
|TortoiseOption|true, false|false|Only in combination with `SSHOption=Plink`|
|CurlOption|OpenSSL, WinSSL|OpenSSL||
|CRLFOption|LFOnly, CRLFAlways, CRLFCommitAsIs|CRLFAlways||
|BashTerminalOption|MinTTY, ConHost|MinTTY||
|GitPullBehaviorOption|Merge, Rebase, FFOnly|Merge||
|UseCredentialManager|Enabled, Disabled, Core|Enabled|`Core` does exactly the same as `Enabled` and exists for historical reasons|
|EnableSymlinks|Auto, Enabled, Disabled|Auto||
|AddmandatoryASLRsecurityexceptions
|Auto, Enabled, Disabled|Auto||
|EnableBuiltinDifftool
|Auto, Enabled, Disabled|Auto||
|EnableBuiltinRebase
|Auto, Enabled, Disabled|Auto||
|EnableBuiltinStash
|Auto, Enabled, Disabled|Auto||
|EnableBuiltinInteractiveAdd
|Auto, Enabled, Disabled|Auto||
|EnablePseudoConsoleSupport
|Auto, Enabled, Disabled|Auto||
|EnableFSMonitor
|Auto, Enabled, Disabled|Auto||

**Comment by Okeanos** [comment]
I am surprised no one linked to [Git For Windows' own Wiki](https://github.com/git-for-windows/git/wiki/Silent-or-Unattended-Installation) yet concerning this topic as getting started point.

I personally like the `/LOADINF` approach because it lets us specify the `Components` part as well (see [here](https://github.com/Okeanos/dotfiles-windows/blob/main/winget_git.ini#L8) and [usage here](https://github.com/Okeanos/dotfiles-windows/blob/main/winget.ps1#L29)).

**Comment by SetTrend** [comment]
Thanks so much, @rimrul, for this utterly helpful and comprehensive table!! 👍❤️👍

Back to OP: Shouldn't this list be more prominently published, so other enterprise users may benefit from this intriguing information?

**Comment by SetTrend** [comment]
I failed matching the following installer options to the above list of options.

Would you mind elaborating on these, please:

<br/>

I couldn't quite relate `CRLFOption` to the following GUI screenshot. How to they relate?
![Line ending configuration](https://github.com/git-for-windows/git/assets/9283914/e58e6212-ca87-4e7d-b235-b9087329423d)

How would I set below mentioned option:
![Enable file system caching](https://github.com/git-for-windows/git/assets/9283914/93f3e67e-a692-4740-ba06-4f36f6c90cc8)

How would I set below mentioned option:
![Enable file system monitor](https://github.com/git-for-windows/git/assets/9283914/c18a6f4b-de48-4d55-8fc1-f1602a7736f8)

<br/>

Your answer is very much appreciated.

**Comment by rimrul** [comment]
> I couldn't quite relate `CRLFOption` to the following GUI screenshot. How to they relate? ![Line ending configuration](https://user-images.githubusercontent.com/9283914/275584891-e58e6212-ca87-4e7d-b235-b9087329423d.png)

From top to bottom:

* CRLFAlways
* LFOnly
* CRLFCommitAsIs

> How would I set below mentioned option: ![Enable file system caching](https://user-images.githubusercontent.com/9283914/275584924-93f3e67e-a692-4740-ba06-4f36f6c90cc8.png)

Ah. I missed an option when creating the table. `/o:PerformanceTweaksFSCache=Enabled`

> How would I set below mentioned option: ![Enable file system monitor](https://user-images.githubusercontent.com/9283914/275584951-c18a6f4b-de48-4d55-8fc1-f1602a7736f8.png)

`/o:EnableFSMonitor=Enabled`

**Comment by dscho** [comment]
> Shouldn't this list be more prominently published, so other enterprise users may benefit from this intriguing piece of information?

Yes. Will you maintain it?

**Comment by SetTrend** [comment]
@rimrul: Top! Thanks a lot for this very helpful piece of information! 👍

@dscho:

> Will you maintain it?

Unfortunately, I'm not a member of this repository. From Matthias' table I could very easily create a Markdown page, but …

- I wouldn't know where to put it
- I wouldn't know of any amendments made to the installer

From my experience, this would result in numerous merge request comments, back and forth.

So, the administrative overhead of me doing this instead of a project member doing this is way too high.

Nonetheless is this piece of information crucial for enterprise users of Git for Windows.

**Comment by dscho** [comment]
As pointed out, the wiki seems a good place. Also, PRs are a good option.

But what I am really reading is a "no".

**Comment by Okeanos** [comment]
> As pointed out, the wiki seems a good place. Also, PRs are a good option.
> 
> But what I am really reading is a "no".

I just updated the wiki entry with the information presented in this issue in the hopes that it improves the status quo of the documentation. (I won't be regularly updating it though)

**Comment by dscho** [comment]
Thank you @Okeanos! This is the kind of proactive contribution that really helps overworked open source maintainers, much appreciated.

**Comment by SetTrend** [comment]
Excellent work, @Okeanos! 👍👍👍

Just for the sake of completing this issue, and for anyone who is probably find this through Google/Bing, here's the link to the Wiki page:

https://github.com/git-for-windows/git/wiki/Silent-or-Unattended-Installation

**Comment by SetTrend** [comment]
I created a Wiki page explaining the mapping between the Git for Windows installer GUI settings and command line arguments:

https://github.com/git-for-windows/git/wiki/Mapping-between-Git-Installer-GUI-Settings-And-Command-Line-Arguments

I couldn't find a comprehensive list of available packages, so I used what I could find. Anyone who feels like adding missing information to this list, please add.
