### ISSUE TITLE
Weird terminal output on git pull in version 2.6.0

### ISSUE THREAD

**Issue by csvbox** [git-for-windows/git#464]
```
$ git pull
Enter passphrase for key 'xxxxxxxx':
remote: Counting objects: 234, done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 234 (delta 131), rReceiving objects: e u56% (132/234sed 37 (delta 37)), p, 212.0ack-reus0 KiBed 43 K
Receiving objects: 100% (234/234), 294.28 KiB | 389.00 KiB/s, done.
Resolving deltas: 100% (149/149), completed with 27 local objects.
....
```

Note the line starting with **remote: Total 234 (delta 131)**

FYI:
```
$ git --version
git version 2.6.0.windows.1
```

**Comment by dscho** [comment]
Details about your setup, please. Needless to say: it does not happen here.

**Comment by csvbox** [comment]
Sorry, which details do you mean? If you mean the git installer setup, I have used all the default options.

Also this happened only once for a specific repo, haven't seen it since. I'm on a different machine now, I'll try to reproduce it again later, if it doesn't re-occur, I'll close it.

**Comment by dscho** [comment]
To avoid frustration on both sides, you should always try to come up with a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve).

**Comment by dscho** [comment]
@csvbox do you think you will eventually be able to provide that MCVE I asked for?

**Comment by csvbox** [comment]
Closing as non-reproducible, sorry for the delay in response.
