### ISSUE TITLE
Git GitHub Authentication Pop-up Reappears Every Time You Run a Git Command Despite Already being Authenticated

### ISSUE THREAD

**Issue by guyjohn-pti** [git-for-windows/git#4644]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.19045.3448]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
We use GitHub EMU
I tried using credential.helper = manager and the git-credential-manager both produced the same results.  When I used store it seems to work fine.  It is like git is ignoring what is in windows credential manager or the git-credential-manager. 

Verified the id exists in both credential managers

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
git clone <repo>
git pull
 - What did you expect to occur after running these commands?

** insert here **
Commands to execute without having to reauthenticate for every command
 - What actually happened instead?

** insert here **
Each command popped up the GitHub authentication window.
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **
All GH urls.

**Comment by dscho** [comment]
> ** insert your machine's response here **

It is really hard to read this report with all those placeholders left in. Please do make an effort to avoid this in the future.

> I tried using credential.helper = manager and the git-credential-manager both produced the same results. When I used store it seems to work fine. It is like git is ignoring what is in windows credential manager or the git-credential-manager.
> 
> Verified the id exists in both credential managers

Maybe multiple credential helpers are configured? Find out with `git config --show-origin --get-all credential.helper`.

Also, try setting `GCM_TRACE=1` and study the log, maybe some obvious explanation for the current behavior pops out.

**Comment by guyjohn-pti** [comment]
git config --show-origin --get-all credential.helper only shows one credential helper
file:C:/Users/<user>/.gitconfig  C:/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe

Verified the id is in git-credential-manager  ran git-credential-manager github list  - the result returned My id

It found my account in git-credential-manager but then returned a no cred found

HostProvider.cs:142 trace: [GetCredentialAsync] Found 1 accounts in the store for service=https://github.com:
HostProvider.cs:145 trace: [GetCredentialAsync]   <MY ID>
HostProvider.cs:218 trace: [FilterAccounts] Account filtering is enabled.
HostProvider.cs:226 trace: [FilterAccounts] Filtering based on WWW-Authenticate header information...
HostProvider.cs:229 trace: [FilterAccounts] Matched 0 accounts with public domain:
HostProvider.cs:181 trace: [GetCredentialAsync] No existing credentials found.
HostProvider.cs:184 trace: [GetCredentialAsync] Creating new credential...

**Comment by guyjohn-pti** [comment]
We have a tentative fix.  We had to run the git config --global credential.github.com.provider generic. That has fixed the issue for a couple of our users.  A couple of users using Windows Credential manager  and one using the GCM appear to be working fine.
