### ISSUE TITLE
mingit uses git lfs without it being present

### ISSUE THREAD

**Issue by kaldevian** [git-for-windows/git#4652]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.4645]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

None, i used MinGit-2.42.0.2-64-bit.zip
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I used the MinGit-2.42.0.2-64-bit.zip Release

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add --all
```
 - What did you expect to occur after running these commands?

All files in the folder get added to the repository

 - What actually happened instead?
```
git-lfs filter-process: line 1: git-lfs: command not found
fatal: the remote end hung up unexpectedly
On branch master
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

It seems mingit is configured to use git lfs without it beeing present. 

```
Snip from etc/gitconfig
...
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```

Removing this block seems to resolve the error, maybe this should be configured as the default?

**Comment by dscho** [comment]
> * If the problem was occurring with a specific repository, can you provide the
>       URL to that repository to help us with testing?
> 
> 
> ** insert URL here **

Unfortunately, this makes it impossible to know if the repository's `.gitattributes` define a given file as being LFS-managed. If there is such an attribute you won't be able to `git add` this using MinGit without also installing Git LFS.

However, there is a much larger issue at play:

> I used the MinGit-2.42.0.2-64-bit.zip Release
> [...]
> 
>     * What commands did you run to trigger this issue? If you can provide a
>       [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
>       this will help us understand the issue.
> 
> 
> ```
> git add --all
> ```

Leaving aside that this is not a verifiable example at all, it suggests that you are using MinGit interactively. This is distinctly _not_ a supported use case. MinGit is [_Git for Windows Applications_](https://github.com/git-for-windows/git/wiki/MinGit).
