### ISSUE TITLE
Please include cygpath.exe in MinGit

### ISSUE THREAD

**Issue by canstand** [git-for-windows/git#4657]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

MinGit  [Git for Windows v2.42.0.windows.2](https://github.com/git-for-windows/git/releases/tag/v2.42.0.windows.2)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 11 

---
When I call `pnpm lint` using `simple-git-hooks`, pnpm requires **cygpath.exe**. 

Manually extracting it from PortableGit into `usr/bin` works.

Is it possible to include it directly in the MinGit package? Thanks

**Comment by dscho** [comment]
MinGit is intended to provide Git for use by 3rd-party applications. If you can show me a legimitate 3rd-party application's Git invocation that requires `cygpath`, I might reconsider, even if it goes against all that MinGit stands for (indeed, there is a version that comes without an MSYS2 Bash at all, instead it uses BusyBox' `ash` where `cygpath` makes very little sense, if it makes sense at all).

Aren't you using Git and/or `pnpm` interactively? Then Git for Windows is for you, not MinGit.

**Comment by alefduarte** [comment]
This is a scenario where cygpath is required. MinGit is used by Visual Studio and we're unable to use pre-commit hooks without manual tinkering with the installed version.
[Missing cygpath.exe in git](https://developercommunity.visualstudio.com/t/Missing-cygpathexe-in-git/1393876)

**Comment by dscho** [comment]
> [Missing cygpath.exe in git](https://developercommunity.visualstudio.com/t/Missing-cygpathexe-in-git/1393876)

For the benefit of readers who do not like to follow breadcrumbs until they have all the relevant information, here is a summary of that page: There is a Git hook that uses `cygpath` to turn a pseudo-Unix path into a proper Windows path.

I do not understand why this hook needs to convert that path, though. The MSYS2 Bash that executes the hook is fully capable and willing to automatically convert the command-line involving a call to `node.exe` and passing the full (pseudo-Unix) path to a script as argument. No `cygpath` required.
