### ISSUE TITLE
Git-2.42.0.2-64-bit.exe show as name of ("255edd25-cca0-4294-909c-b46bced63e3f:) , ( corrputed exe extension)

### ISSUE THREAD

**Issue by sayedbakeer3** [git-for-windows/git#4668]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - 64-bit

```
$ Git-2.42.0.2-64-bit.exe

```
show as ("255edd25-cca0-4294-909c-b46bced63e3f")

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 11
```
$ cmd.exe /c ver

** None**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
** I can't open exe it's show **Git-2.42.0.2-64-bit.exe show as name of ("255edd25-cca0-4294-909c-b46bced63e3f:) **

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
I didn't know but 32 bit is work but 64 bit not work like his extension is corrupted
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** powershell too can't download 64 bit**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**i didn't know **
```
 - What did you expect to occur after running these commands?

**i didn't know **

 - What actually happened instead?

** Git-2.42.0.2-64-bit.exe show as name of ("255edd25-cca0-4294-909c-b46bced63e3f:) no .exe **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** i can't open git 64 bit**

**Comment by dscho** [comment]
Please show a screenshot. It is unclear where that `.exe` is displayed incorrectly.

**Comment by sayedbakeer3** [comment]
I'm so sorry guys for not my clear definitions for issues , i had screenshot for problem
screenshot >
![explorer_5WsoILHdom](https://github.com/git-for-windows/git/assets/97993670/226d855d-5638-4b27-ad58-542a4fd7e11f)

**Comment by sayedbakeer3** [comment]
i try download again next day , and it's work i can download file as 64-bit Git for Windows Setup.

**Comment by sayedbakeer3** [comment]
### i want **close** issue but i want to know what's happened , how ?

**Comment by dscho** [comment]
I suspect that you have some anti-malware that got a little ahead of itself. That's happened before, and the symptoms look similar to what you observed.
