### ISSUE TITLE
git update-git-for-windows is unresponsive when started from a non-existent folder

### ISSUE THREAD

**Issue by ssvine** [git-for-windows/git#4669]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.2
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3570]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir test
cd test
rm -rf ../test
git update-git-for-windows
```
 - What did you expect to occur after running these commands?

git checks for updates and exits

 - What actually happened instead?

git becomes fully unresponsive, even pressing Ctrl-C doesn't help

**Comment by ssvine** [comment]
It turned out that this is a bug in msys2. Someday it should be fixed

https://github.com/msys2/msys2-runtime/commit/60d1eeac6c6185ac77b181929c773015a2772fe8

**Comment by dscho** [comment]
> Someday it should be fixed

![Image](https://github.com/git-for-windows/git/assets/127790/047508ae-73e5-4539-bc75-d9d1e6b4e8d0)

All it would take is a PR in git-for-windows/msys2-runtime and testing the result by downloading the build artifact and overwriting the local `msys-2.0.dll`.
