### ISSUE TITLE
Different amount of modified tracked files after branch checkout of supposedly clean branch

### ISSUE THREAD

**Issue by cdrfun** [git-for-windows/git#4680]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.1
cpu: x86_64
built from commit: a2e49ec355ae22e74288fa74f50821f3cc1a1551
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3570]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
> type .\.gitattributes

# Auto detect text files and perform LF normalization
*          text=auto

*.cs       text diff=csharp
*.cshtml   text diff=html
*.csx      text diff=csharp
*.sln      text eol=crlf
*.csproj   text eol=crlf
```

### Details
 - PowerShell with [git posh](https://github.com/dahlbyk/posh-git) inside of [windows terminal](https://github.com/microsoft/terminal)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
> git clone https://redacted Project
Cloning into 'Project'...
remote: Azure Repos
remote: Found 57799 objects to send. (385 ms)
Receiving objects: 100% (57799/57799), 779.81 MiB | 54.44 MiB/s, done.
Resolving deltas: 100% (47237/47237), done.
Updating files: 100% (2975/2975), done.
> cd .\Project\
[main ≡]> git checkout Prod
Updating files: 100% (1597/1597), done.
Switched to a new branch 'Prod'
branch 'Prod' set up to track 'origin/Prod'.
[Prod ≡ +0 ~974 -0 !]> git checkout main -f
Updating files: 100% (1597/1597), done.
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
[main ≡]> git checkout Prod
Updating files: 100% (1597/1597), done.
Switched to branch 'Prod'
Your branch is up to date with 'origin/Prod'.
[Prod ≡ +0 ~336 -0 !]> git checkout main -f
Updating files: 100% (1597/1597), done.
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
[main ≡]> git checkout Prod
Updating files: 100% (1597/1597), done.
Switched to branch 'Prod'
Your branch is up to date with 'origin/Prod'.
[Prod ≡ +0 ~223 -0 !]> git checkout main -f
Updating files: 100% (1597/1597), done.
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
[main ≡]> git checkout Prod
Updating files: 100% (1597/1597), done.
Switched to branch 'Prod'
Your branch is up to date with 'origin/Prod'.
[Prod ≡ +0 ~90 -0 !]> git checkout main -f
Updating files: 100% (1597/1597), done.
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
[main ≡]> git checkout Prod
Updating files: 100% (1597/1597), done.
Switched to branch 'Prod'
Your branch is up to date with 'origin/Prod'.
[Prod ≡ +0 ~959 -0 !]> git version
git version 2.42.0.windows.1
[Prod ≡ +0 ~959 -0 !]> git diff <redacted>\ILandDao.cs
diff --git a/<redacted>/ILandDao.cs b/<redacted>/ILandDao.cs
index e9e70eb3..3e403dd3 100644
--- a/<redacted>/ILandDao.cs
+++ b/<redacted>/ILandDao.cs
@@ -1,23 +1,23 @@
-﻿using System.Collections.Generic;
-using Project.Entity.Entities;
-
-namespace Project.Entity.Daos.Interfaces
-{
-    public interface ILandDao
-    {
-        #region methods
-
-        #region public methods
-
-        void Delete(LandEntity entity);
-        LandEntity GetById(int id);
-
-        IList<LandEntity> GetList();
-
-        int Save(LandEntity entity);
-
-        #endregion
-
-        #endregion
-    }
+﻿using System.Collections.Generic;
+using Project.Entity.Entities;
+
+namespace Project.Entity.Daos.Interfaces
+{
+    public interface ILandDao
+    {
+        #region methods
+
+        #region public methods
+
+        void Delete(LandEntity entity);
+        LandEntity GetById(int id);
+
+        IList<LandEntity> GetList();
+
+        int Save(LandEntity entity);
+
+        #endregion
+
+        #endregion
+    }
 }
\ No newline at end of file
```
 - What did you expect to occur after running these commands?

My expectation was to checkout the Prod branch and having a clean Prod branch afterward.

 - What actually happened instead?

As you can see in the git posh status summary, there are modified tracked files directly after checkout. Even worse: there is a different amount of modified tracked files after each Prod checkout I did:
- `[Prod ≡ +0 ~974 -0 !]`
- `[Prod ≡ +0 ~336 -0 !]`
- `[Prod ≡ +0 ~223 -0 !]`
- `[Prod ≡ +0 ~90 -0 !]`
- `[Prod ≡ +0 ~959 -0 !]`

I diffed a smaller file of the repo to understand the changes, but there are no (visiable) changes.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Sorry I can't, it's a private repo.

**Comment by dscho** [comment]
> Sorry I can't, it's a private repo.

You could always put in a little effort to make it easier for others to reproduce.

As it is, I suspect that end-of-line issues are the culprit. @tboegi could I ask you to take a look?

**Comment by tboegi** [comment]
Yes, that could be a CRLF problem.
What does 
git ls-files --eol | grep ILandDao.cs
give you ?

**Comment by cdrfun** [comment]
> > Sorry I can't, it's a private repo.
> 
> You could always put in a little effort to make it easier for others to reproduce.
> 
> As it is, I suspect that end-of-line issues are the culprit. @tboegi could I ask you to take a look?

I'll try to make something.

> Yes, that could be a CRLF problem. What does git ls-files --eol | grep ILandDao.cs give you ?

I had to resort to `git ls-files --eol | select-string ILandDao.cs`, as I'm using PowerShell. Here is the output:
`i/crlf  w/crlf  attr/text               PawasNT3/PawasNT3/Entity/Daos/Interfaces/ILandDao.cs`

**Comment by tboegi** [comment]
@cdrfun 
That line describes the problem.
i/crlf means that the file has been commited with CRLF.
attr/text means to Git "please convert CRLF into LF when commiting".
(And depending on the timestamps of files on disk, Git will detect this or not.)
The clean solution would be

```
git add --renormalize .
git commit -m "Normalize line endings in the repo"


```

**Comment by cdrfun** [comment]
This seems to have worked. Thank you very much @tboegi 

What irritated me was the changing number of modified files. Do you know why this is the case?

**Comment by tboegi** [comment]
Which files are noted as modified and which not is dependent on the
timestamps on your disk.
And that is very much machine dependent, and feel like random for a user.
