### ISSUE TITLE
Colon disappearing from string

### ISSUE THREAD

**Issue by erenaud3** [git-for-windows/git#4689]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.19043.1889]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: C:\Users\erenaud\AppData\Local\Programs\Microsoft VS Code\Code.exe
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** Nothing that I am aware of. My issue may have appear when I began to use some bash script modifying IFS value. But I am not so sure. **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
url=https://github.com/topics/git-bash
echo $url
```
 - What did you expect to occur after running these commands?

I was expecting following output : 
```
https://github.com/topics/git-bash
```

 - What actually happened instead?

Instead, I have this (missing colon) : 
```
https //github.com/topics/git-bash
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

I think this problem appeared 2 or 3 weeks ago.

**Comment by rimrul** [comment]
> My issue may have appear when I began to use some bash script modifying IFS value

That seems plausible. What does `echo "$IFS"` give you?
