### ISSUE TITLE
Shipped perl incompatible for building OpenSSL, inconsistent behavior with Strawberry Perl

### ISSUE THREAD

**Issue by akrieger** [git-for-windows/git#469]
Basically what the title says. When trying to compile OpenSSL 1.0.1p, using the builtin perl that ships with 2.6.1, I get weird errors in the early configuration steps.
```
$ pwd
/c/Personal/src/.../openssl-1.0.1p

$ ms/do_nasm.bat

C:\Personal\src\...\openssl-1.0.1p>perl util\mkfiles.pl  1>MINFO

C:\Personal\src\...\openssl-1.0.1p>perl util\mk1mf.pl nasm VC-WIN32  1>ms\nt.mak
no rule for apps\\ at util\mk1mf.pl line 961.

C:\Personal\src\...\openssl-1.0.1p>perl util\mk1mf.pl dll nasm VC-WIN32  1>ms\ntdll.mak
no rule for apps\\ at util\mk1mf.pl line 961.

C:\Personal\src\...\openssl-1.0.1p>perl util\mk1mf.pl nasm BC-NT  1>ms\bcb.mak
no rule for apps\\ at util\mk1mf.pl line 961.

C:\Personal\src\...\openssl-1.0.1p>perl util\mkdef.pl 32 libeay  1>ms\libeay32.def
File ssl/tls1.h: cannot parse: ()

#INFO::;
File ssl/tls1.h: cannot parse: ()

#INFO::;
```

And then it hangs. So, I tested by installing Strawberry Perl, setup my PATH variable such that the Strawberry Perl installation is first, and re-ran the script to completion (again, from inside Git for Windows). Both perl installations report the almost the same --version output.

```
$ /usr/bin/perl --version

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-msys-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

$ /c/Personal/Strawberry/perl/bin/perl.exe --version

This is perl 5, version 22, subversion 0 (v5.22.0) built for MSWin32-x64-multi-thread

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

Any ideas? Should I just stick with Strawberry perl and move on with life?

**Comment by nalla** [comment]
> built for x86_64-msys

1. What console did you open? `msys` or `mingw` ?
2. Are you in the GfW SDK?
3. Please provide an [MVCE](http://stackoverflow.com/help/mcve)

**Comment by nalla** [comment]
Inside the _SDK_ I get the following outpint inside a `mingw64` shell

```shell
nalla@dev MINGW64 /usr/src/openssl-1.0.1p
$ ms/do_nasm.bat

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mkfiles.pl  1>MINFO

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mk1mf.pl nasm VC-WIN32  1>ms\nt.mak
unknown option - static-engine

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mk1mf.pl dll nasm VC-WIN32  1>ms\ntdll.mak
unknown option - static-engine

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mk1mf.pl nasm BC-NT  1>ms\bcb.mak
unknown option - static-engine

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mkdef.pl 32 libeay  1>ms\libeay32.def

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mkdef.pl 32 ssleay  1>ms\ssleay32.def
```

After that both `cat MINFO` and `cat ms/libeay32.def` contains tons of stuff.

So I can't reproduce.

**Comment by Dirk1966** [comment]
Every Windows perl, Strawberry perl as well as ActiveState perl MUST be incompatible to the perl which is shipped with "git for Windows 1/2" (gfW).  This is because of Windows perl assume, that a line ends with CRLF while gfW expects an LF only.
If you communicate with other servers, this can really kill the application you want to write.

I saw this from client and from server side where we did not understand, why a command was not issued correctly.

So you must not expect the perl versions to behave similarly.

I would not wonder if such a re

**Comment by akrieger** [comment]
@nalla 

1) All commands were run from inside the git-bash.exe console that ships with Git for Windows. I'm not sure how to tell what the precise underlying shell is, but I recall using default versions for the installation. I'm not sure how to get the information you need. I presume this means I'm using msys.
2) No, I was using the user distribution, with the option selected for 'use Git from cmd.exe' as well (but I tend to do all my Git operations from within git-bash.exe).
3) I gave as complete and minimal of a repro as I could. I reinstalled GfW, updated to the most recent version, and double-checked that /usr/bin/perl exhibited the issue and Strawberry perl did not. The only other thing I can think of is that the openssl-1.0.1p source was extracted from a .zip using the Windows extractor, so the line endings should be crlf.

**Comment by akrieger** [comment]
After re-downloading and un-tarring openssl-1.0.1p using GfW tar, following the suggestion of @Dirk199

**Comment by akrieger** [comment]
I compared the version of openssl in our repo (which has auto-crlf = true) vs. a clean download and the only difference was line endings. So, I imagine this comes down to a line endings issue like @Dirk1966 indicated.

In that case, I want to ask what the reasoning is for shipping a unix-only version of perl with GfW. Granted, I'm using the user distribution, and not the SDK. But I imagine I and others are going to be using GfW for pseudo-cross-platform development anyway. At the very least, the shell is far better to work with than cmd.exe. Plus, Strawberry Perl works correctly on either version (LF or CRLF).

**Comment by nalla** [comment]
> I presume this means I'm using msys

The default shell is `MINGW`.

I don't think that you have a problem with `CRLF` vs `LF`

```shell
$ unix2dos.exe ms/do_nasm.bat
unix2dos: ms/do_nasm.bat MODE 0100644  (regular file)
unix2dos: using ms/d2utmpw9q1AU as temporary file
unix2dos: converting file ms/do_nasm.bat to DOS format...

$ unix2dos util/mkfiles.pl
unix2dos: util/mkfiles.pl MODE 0100755  (regular file)
unix2dos: using util/d2utmp843q4q as temporary file
unix2dos: converting file util/mkfiles.pl to DOS format...

$ unix2dos util/mk1mf.pl
unix2dos: util/mk1mf.pl MODE 0100755  (regular file)
unix2dos: using util/d2utmpN73f1P as temporary file
unix2dos: converting file util/mk1mf.pl to DOS format...

$ unix2dos util/mkdef.pl
unix2dos: util/mkdef.pl MODE 0100755  (regular file)
unix2dos: using util/d2utmppG0Ggs as temporary file
unix2dos: converting file util/mkdef.pl to DOS format...

$ ms/do_nasm.bat

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mkfiles.pl  1>MINFO

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mk1mf.pl nasm VC-WIN32  1>ms\nt.mak
unknown option - static-engine

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mk1mf.pl dll nasm VC-WIN32  1>ms\ntdll.mak
unknown option - static-engine

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mk1mf.pl nasm BC-NT  1>ms\bcb.mak
unknown option - static-engine

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mkdef.pl 32 libeay  1>ms\libeay32.def

C:\git-sdk-64\usr\src\openssl-1.0.1p>perl util\mkdef.pl 32 ssleay  1>ms\ssleay32.def
```

@akrieger please try using the _SDK_ the _GfW_ release is shipping a minimal set of files that is required to support the running of `git`.

I rather think that there are some files missing in your setup.

**Comment by dscho** [comment]
Let's make one thing clear: the main purpose of Git for Windows is to provide a Git. For Windows. Last time I checked, Git does not require support for building custom OpenSSL versions, and certainly not *outside* of MSys2/MinGW.

Another thing should also be very clear: if you actually work on supporting your use case (no matter how obscure it may be) and can demonstrate that it does not affect Git for Windows *too* negatively, your work will be accepted, with thanks, into this project.

**Comment by akrieger** [comment]
Sorry if my tone came across as harsh or judgemental. I wasn't aware until now there was a separate GfW SDK, but I have found it now. I'm just trying my hardest to get by in a very unfamiliar world of Windows development. I see something that looks like perl, talks like perl, and does most of the things like perl but fails in some obscure reason, but this other version of perl works and looks almost identical, I think 'this looks like a bug, ideally both versions should work, lets try to figure this out'. I'm really sorry it sounds like I'm making demands on supporting my random development environment, my frustration with the issues I am running into must be coloring my words. Thank you all, again, for your patience. I'll make sure to think twice and check three times before posting an issue in the future.

@nalla, it wasn't that the specific scripts were `CRLF` or `LF` but the source files they are attempting to parse are.

**Comment by akrieger** [comment]
I recursively ran dos2unix on the entire openssl-1.0.1p directory and re-ran the build scripts without issue.

**Comment by dscho** [comment]
@akrieger I would have preferred it if you had worked on making MSys2's Perl compatible in the way you wished. Quite possible a task, really.
