### ISSUE TITLE
Net installer preview 1 fails with command not found error

### ISSUE THREAD

**Issue by kappa7194** [git-for-windows/git#47]
When trying to run the installer `git-sdk-64-installer-preview.7z.exe` from https://github.com/git-for-windows/build-extra/releases/tag/net-installer-preview-1 the setup fails with the message `bash: __git_ps1: command not found`.

You can find the full log at https://gist.github.com/kappa7194/fe652bef133f6f511c10

**Comment by dscho** [comment]
This is a known issue: it was fixed in [the newest net installer](https://github.com/git-for-windows/build-extra/releases/tag/PortableGit-2.3.4) by [adding the `--login` flag](https://github.com/git-for-windows/build-extra/commit/484f8d092d9ef55806b20c6585fe9f5e81d156ff).

**Comment by dscho** [comment]
@kappa7194 could you give the new installer a try?

**Comment by kappa7194** [comment]
>@kappa7194 could you give the new installer a try?

It seems this installer is still affected by the [proxy issue]; I can't switch to the mobile phone hotspot at the moment because I need the corporate network for work, so I'm going to postpone this issue until I've been able to fix that one.

  [proxy issue]: https://github.com/git-for-windows/git/issues/46
