### ISSUE TITLE
Symbolic Link Support Broken in Windows ARM64

### ISSUE THREAD

**Issue by ElectricalBoy** [git-for-windows/git#4707]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```text
$ git --version --build-options

git version 2.43.0.windows.1
cpu: aarch64
built from commit: 4b968f3ea3b32a7bc50846bab49f3f381841d297
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
Also occurred in the ARM64 build of `GfW 2.42.0.windows.1`

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
    > Windows 11 23H2 (build 22631.2428)

 - What options did you set as part of the installation? Or did you choose the defaults?

```text
Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related to the issue you're seeing?

   > - Device used: Surface Pro X (SQ1)
   > - Developer mode enabled in Windows (for symlink permission)
   > - [ARM64 build](https://github.com/dennisameling/git/releases/tag/v2.43.0.windows.1) by `@dennisameling` used
   >   - Related issue: #3107
   > - Issue not present in x64 build of GfW
   > - Creating symlinks in Windows on ARM (via `mklink` in `cmd`) works without issues

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

   > Windows Powershell

 - What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

   1. Clone <https://github.com/ElectricalBoy/symlink-test>
   2. `cd` to the cloned repository
   3. Run `git config --local -l` and observe output.
   4. Run `git config core.symlinks true` (Reason described below)
   5. Perform a hard reset (via `git reset --hard`) to https://github.com/ElectricalBoy/symlink-test/commit/5c18b50ba96afbd6a467e18f385cf68be64b8701
       (Last commit with no symlink in the reproducer repository)
   7. Run `git pull`

 - What did you expect to occur after running these commands?

   - At step 3:
     - There is no entry with the key `core.symlinks`
   - At step 7:
     - Local repository updated to the latest commit (i.e., https://github.com/ElectricalBoy/symlink-test/commit/cbd0ba825fe67d70341d57af7a3c2d5292975844)

 - What actually happened instead?

   - With x64 build of GfW: _As expected_ in both steps 3 and 7
   - With ARM64 build of GfW:
     - At step 3: `core.symlinks=false` entry present
     - At step 7:
       ```text
       error: unable to create symlink bar.txt: Permission denied
       error: unable to create symlink dir/bar2.txt: Permission denied
       ```

 - If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing?
   > N/A - occurs in all repositories. See above for the link to the reproducer.

- Workarounds found so far:
  - Do not use symlinks in repositories (not ideal, but okay)
  - Disable symlinks entirely, i.e., set `core.symlinks` to `false` (also not ideal, but okay)
  - Use WSL and the upstream Git inside it (works, but requires virtualization running)

**Comment by dscho** [comment]
Have you enabled Developer Mode? See https://github.com/git-for-windows/git/wiki/Symbolic-Links#allowing-non-administrators-to-create-symbolic-links for details.

**Comment by dscho** [comment]
> > Have you enabled Developer Mode?
> 
> Yup, and it's already mentioned in the issue description above. 😄

Right, I only spotted the "Permission denied" and didn't look further, sorry.

I wonder, though, whether in the ARM build specifically, we somehow do not get the benefit of [this code](https://github.com/git-for-windows/git/blob/v2.43.0.windows.1/compat/mingw.c#L3971-L3983). If that flag is _somehow_ not set, that would explain that "Permission denied" error.

**Comment by rimrul** [comment]
> Is that code connected (and/or related) to the behavior of GfW silently inserting core.symlinks=false to the local Git config when it "thinks" that it is needed? As mentioned in my issue description above, this is one of the abnormal outcomes I have observed (see step 3 of my MCVE above).

That is pretty standard `git` behaviour. `git clone` detects the same failure that leads to the error message in step 7 of the MVCE and sets `core.symlinks` accordingly.

That code is related in that it sets the relevant `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` flag for symlink creation in developer mode.

> core.symlinks
>
> [...]
>
> The default is true, except git-clone[1] or git-init[1] will probe and set core.symlinks false if appropriate when the repository is created.

The relevant excerpt from https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks

**Comment by rimrul** [comment]
> > > Have you enabled Developer Mode?
> > 
> > Yup, and it's already mentioned in the issue description above. 😄
> 
> Right, I only spotted the "Permission denied" and didn't look further, sorry.
> 
> I wonder, though, whether in the ARM build specifically, we somehow do not get the benefit of [this code](https://github.com/git-for-windows/git/blob/v2.43.0.windows.1/compat/mingw.c#L3971-L3983). If that flag is _somehow_ not set, that would explain that "Permission denied" error.

That hunch seems to be correct. `GetVersion()` seems to return `0x23F00206`, while we expect it to be ≥ `0x3A7C0000`.
