### ISSUE TITLE
Installer window truncates words on right side

### ISSUE THREAD

**Issue by gitname** [git-for-windows/git#4727]
There's a typo (or a layout bug) in the installer (highlight added by me).

![image](https://github.com/git-for-windows/git/assets/7143133/a5837ef6-b8c0-4446-a15b-29c1131ab874)

I expected it to say "and" instead of "an".

> Side note: I recommend switching to active voice instead of passive voice; i.e. from "it is recommended to" to "we recommend that you". That'll give readers more information about who is doing the recommending.

--- 

- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 
https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.2715]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
(I haven't completed the installation yet.)
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

**Comment by gitname** [comment]
One of the subsequent steps also contains a similar "typo" (shown below; with highlighting added by me). I expected it to say "the" instead of "th".

![image](https://github.com/git-for-windows/git/assets/7143133/a7a2a0f5-f2f9-4196-9be6-eb9728ccdbae)

Given this additional occurrence, I think the underlying issue is a **layout bug** as opposed to a typo.

**Comment by gitname** [comment]
Another subsequent step has occurrences. I am confident it's a layout bug as opposed to a typo, since this one has "partial characters."

![image](https://github.com/git-for-windows/git/assets/7143133/07f4c9a2-ace8-4229-97c6-7a4ba6d45b71)

**Comment by dscho** [comment]
Fixed via https://github.com/git-for-windows/build-extra/pull/536

**Comment by dscho** [comment]
/mention relnote bug The Git for Windows installer [showed cut-off text in some setups](https://github.com/git-for-windows/git/issues/4727). This [has been fixed](https://github.com/git-for-windows/build-extra/pull/536).

**Comment by dscho** [comment]
/add relnote bug The Git for Windows installer [showed cut-off text in some setups](https://github.com/git-for-windows/git/issues/4727). This [has been fixed](https://github.com/git-for-windows/build-extra/pull/536).
