### ISSUE TITLE
pull with stale index.lock causes fatal: BUG: get_tempfile_fd() called for inactive object

### ISSUE THREAD

**Issue by karlthepagan** [git-for-windows/git#474]
I originally saw this after ctrl-c'ing a pull which was taking too long (in order to verify my connection to the host).

I was using core.fscache and core.preloadindex during the command which produced the first index.lock. Turning these features off did not resolve the issue nor did disabling the experimental features produce a more useful error message.

git version 2.6.0.windows.1

System information:
```
         Operating System: Windows 10 Enterprise 64-bit (10.0, Build 10240) (10240.th1.150819-1946)
                Processor: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 CPUs), ~2.6GHz
                   Memory: 24576MB RAM
      Available OS Memory: 24526MB RAM
                Page File: 7309MB used, 18751MB available
```

Steps to reproduce: (on this system, works every time)
1. On Windows 10, in the root of any repository, simulate a canceled update by touching index.lock
```touch .git/index.lock```
2. Attempt a pull
```git pull```

**Expected**: message indicating presence of a stale index.lock (similar to checkout)
```
    fatal: Unable to create 'D:/git/sandbox/.git/index.lock': File exists.
    
    If no other git process is currently running, this probably means a
    git process crashed in this repository earlier. Make sure no other git
    process is running and remove the file manually to continue.
```

**Actual**: after a significant delay, file descriptor error message
```fatal: BUG: get_tempfile_fd() called for inactive object```

**Comment by dscho** [comment]
I followed those steps, but `git pull` just says "Already up-to-date."

**Comment by karlthepagan** [comment]
A reboot has cleared this up for me.

I did reproduce this across two separate repositories before the reboot, but as @dscho observed: no repro.

**Comment by dscho** [comment]
Oh, I am sure that there is a way to reproduce. But not just in *any* repository. I am pretty certain that the current branch must be out-of-date to trigger this behavior.

**Comment by karlthepagan** [comment]
Thanks, I did try that @dscho - https://github.com/karlthepagan/git-issues-474

I couldn't repro with the trivial changes in that repo. Perhaps new files? I'll see if I come up with anything this evening.
