### ISSUE TITLE
Issue in pulling or pushing codes for windows

### ISSUE THREAD

**Issue by vivtiwary** [git-for-windows/git#4757]
warning: failed to restrict file handles (87)

handle #0: 0000000000000204 (type 3, handle info (1) 0
handle #1: 0000000000000208 (type 3, handle info (1) 1
handle #2: 00000000000001cc (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

**Comment by dscho** [comment]
This is too little information, by a large margin, to act on.
