### ISSUE TITLE
Installer does not allow selection of install location

### ISSUE THREAD

**Issue by gnif** [git-for-windows/git#476]
The installer does not give the option to choose the install location, this is an issue in restricted environments where the user does not have enough permissions to write to `Program Files`.

**Comment by Pacoup** [comment]
As a “workaround”, if you install as a user, the installer will automatically select the user folder instead of Program Files. Non-administrator users should be able to install the software just fine (assuming it hasn't already been installed on the computer by an administrator).

That's relatively standard Windows installer behaviour as far as I know.

**Comment by gnif** [comment]
Agreed, I have already worked around the issue, but thought I would be helpful and point out the missing feature.

**Comment by dscho** [comment]
Actually, I suspect that quite a bit of information is missing from this ticket. The reason for my suspicion: we set [`DisableDirPage` to `auto`](https://github.com/git-for-windows/build-extra/blob/0a12cc0e519ba91efdb88dc74906df252951abc8/installer/install.iss.in#L43) and [the documentation for that setting](http://www.jrsoftware.org/ishelp/index.php?topic=setup_disabledirpage) says:

> If this is set to auto, at startup Setup will look in the registry to see if the same application is already installed, and if so, it will not show the Select Destination Location wizard page.

So I assume that Git for Windows had been installed on your computer at some stage, and the installer detects that and helpfully hides that page.

**Comment by gnif** [comment]
No, this machine has never had Git for windows installed on it

**Comment by dscho** [comment]
> No, this machine has never had Git for windows installed on it

Okay. This is valuable information.

Please fill in the other, really necessary information, as per [our guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines).

**Comment by gnif** [comment]
OS: 32bit Windows 7 Enterprise
Extra: Domain member using unprivileged account
Git: 2.6.1 32bit

Issue, installer never prompts for the install path, assumes "C:\Program Files" which is unwritable by the current user.

**Comment by PhilipOakley** [comment]
Slight bikeshed..

In the past (Msysgit days) the installer had a similar habit of simply installing upgrades in the same place as the previous install, even if one wanted to change the location. It wasn't at all obvious to a regular user how to make the change, nor if it was even possible.

In most cases the 're-install at same location' is a good choice, but not always. 

If I had some time, I'd probably try and detect a previous install and display a note, on the screen that precedes the location selection, of the current install location and add an option button that the user can selcet if they want to change the location, whereupon the regular new install location selection would show.

One question for @gnif and @Pacoup would be if that would be sufficient for the cases they have seen / are concerned about.

Hopefully, because I had to rebuild my machine, I no longer have the problem, but if the thought process helps others..

**Comment by dscho** [comment]
Well, if somebody comes up with a kick-ass Pull Request whose commit message does an excellent job of convincing me that the install location should be always shown, I would certainly merge it.

**Comment by Pacoup** [comment]
@PhilipOakley Could be, although in practice, there's a reason for this install behaviour.

Re-installing the application at the same location allows administrators to install software and prevent non-admin users from installing and managing their own version. This can be desirable in enterprise environments, even if everyone here is likely to dislike it (Google Chrome and FileZilla also work like this).

In a well working scenario, if this becomes undesirable, having the admin uninstall the application would then allow the non-admin user to install it in his user folder.

So the question is, I think, is more, does this currently work correctly. For me it does; it's always installed in Program Files when the setup is run by an admin and in AppData when run by a non-admin user, but I never tried uninstalling the admin-installed version and then trying a user install.

@gnif, your scenario is kind of strange. You're saying Git was never installed before, but that you're trying to install it as a non-admin user, and it wants to install in Program Files. So something sounds broken but at the OS level. It's like the non-admin user is not properly set as non-admin.

**Comment by dscho** [comment]
> Re-installing the application at the same location allows administrators to install software and prevent non-admin users from installing and managing their own version.

@Pacoup InnoSetup allows you to override the installation location via a command-line option. Just call the installer with the "/?" option from the command line.

**Comment by PhilipOakley** [comment]
> @ <https://github.com/PhilipOakley> PhilipOakley Could be, although in practice, there's a reason for this install behaviour.
> Re-installing the application at the same location allows administrators to install software and prevent non-admin users from installing and managing their own version. This can be desirable in enterprise environments, even if everyone here is likely to dislike it (Google Chrome and FileZilla also work like this).
This may not be the original reason ;-) But it is a reasonable scenario outline. Unfortunately it wasn’t my scenario.
In my case I had personally installed it (at home) at a named sub-directory that included the version number in its name (that was then). After a few updates that became an untenable historic ‘mistake’ that required a change of the install directory (to be done by me), hence my support for the request that at least it be a potential option.
In my enterprise’s scenario, apps are installed in the background so are completely silent. It feels odd that the regular installer would be the right thing given that it still offers some options to the [dumb?] user, yet denies choice of directory/programme/version name. (just saying)
[snip..]

**Comment by Pacoup** [comment]
@dscho Oh... I didn't know that. Okay, then I guess it's just up to someone to make a PR for a GUI-based option in the installer like you said.

**Comment by PhilipOakley** [comment]
> > Re-installing the application at the same location allows administrators to install software and prevent non-admin users from installing and managing their own version.
> @Pacoup InnoSetup allows you to override the installation location via a command-line option. Just call the installer with the "/?" option from the command line.

Didn't know that.. Is that general to all typical innosetup installations, or special to G4W's?

**Comment by dscho** [comment]
> Is that general to all typical innosetup installations, or special to G4W's?

@PhilipOakley it is an InnoSetup feature.

**Comment by PhilipOakley** [comment]
@dscho Thanks. Useful to know the "/?" option!

**Comment by dscho** [comment]
I just installed Git for Windows on a freshly installed Windows 10. These are the first three wizard pages with which I was greeted:

![wizard-welcome](https://cloud.githubusercontent.com/assets/127790/10563760/7d7dc028-7597-11e5-9bfb-87587cd16d09.png)

![wizard-license](https://cloud.githubusercontent.com/assets/127790/10563761/82a0f8c2-7597-11e5-9626-1dbd18985c4b.png)

![wizard-destination](https://cloud.githubusercontent.com/assets/127790/10563762/86295246-7597-11e5-99b3-43749540ede8.png)

@gnif So I really do not understand why you could not choose the destination if Git for Windows was really not installed on that machine before.

**Comment by PhilipOakley** [comment]
Reviewing @gnif 's original comment, and comparing it with my experiences and the report of @dscho for a regular clean start, it feels to me that @gnif may have had a hidden install of Git sometime in the past via some other third party app (of which there a number, though most mention Git in their title: GitExtensions, TortoiseGit, SmartGit, ..) 

If @gnif is in a corporate envoronment, who knows what corporate IT have done in the background?

These things do happen (quick trial install of something that then isn't used and forgotten about, or even part uninstalled, but the residues are still there..).

@dscho 's suggestion of 'call the installer with the "/?" option from the command line' should be useful. (rhetorical: what does it do (in terms of dialogs) if one already has the install present - does it show the default destination or the current destination?).

If @gnif has enough permissions (corporate environment) then may be testing the command line version may give an insight.

**Comment by linquize** [comment]
To clearify, as of TortoiseGit 1.8.15.0, It does NOT ship git-for-windows.
The users have to manually download and install git-for-windows.

**Comment by dscho** [comment]
It appears that this issue is resolved: the installer *does* show the destination selection unless Git for Windows has been installed previously. We even provided a workaround via command-line option. Obviously, there is not enough interest to open a Pull Request to show the destination selection page always, else that Pull Request would have been opened in the meantime.
