### ISSUE TITLE
Publish MSI installer

### ISSUE THREAD

**Issue by CameronGo** [git-for-windows/git#4761]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3803]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

We are using Microsoft Endpoint Management to deploy applications.

### Details

It would be very useful to publish an MSI installer either in addition to or instead of the executable installer. When distributing patched versions to address vulnerabilities, endpoint management services will automatically update only the endpoints which have the application installed. With the exe installers Admins must create a series of detection, uninstall, install scripted behaviors. As vulnerability management is elevating in visibility and importance, being able to quickly and easily patch applications is critical. I can't see any downside to publishing the installer as an MSI rather than an EXE.

**Comment by dscho** [comment]
There is code to generate `.msi` versions of Git for Windows in https://github.com/git-for-windows/build-extra/tree/HEAD/msi. It has been last updated 2 years ago (!!!). Keeping the installer and the `.msi` in sync is no small feat and would require volunteers to accomplish, and as you can see, that has not materialized.
