### ISSUE TITLE
SSH key exchange issue when tunneling through corporate proxy

### ISSUE THREAD

**Issue by avpjanm** [git-for-windows/git#4768]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.43.0.windows.1
cpu: x86_64
built from commit: 4b968f3ea3b32a7bc50846bab49f3f381841d297
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3448]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using git behind a company proxy (Zscaler) which does package inspection.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Git bash and cmd**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone ssh://<URL>
```
- **Description of the issue**

I use git behind a coporate proxy (Zscaler) which does package inspection. The Zscaler root CA certificate has to be trusted.
I achieved this for https by setting.
```
http.sslbackend=schannel
```

But I have troubles configuring this for SSH. My ssh configuration is using wingw64 connect.exe to tunnel trough the corporate proxy.
But it is not clear to me how to adjust the trusted certificates of connext.exe.
Here the ssh configuration:

```
ProxyCommand "C:/Program Files/Git/mingw64/bin/connect.exe" -H localhost:9000 %h %p
```

Thanks a lot in advance!

**Comment by dscho** [comment]
The `connect.exe` program is compiled from the source code that is hosted at https://github.com/gotoh/ssh-connect. I did not find anything about certificates anywhere in that source code, but maybe `connect.exe` is only able to speak HTTP, not HTTPS? In any case, your best bet is to ask over in https://github.com/gotoh/ssh-connect, as the issue is safely outside Git for Windows' maintainers' expertise.

**Comment by avpjanm** [comment]
I agree - I thought that this might be a common issue..

I will talk to ssh-connect.

**Comment by dscho** [comment]
> I agree - I thought that this might be a common issue..

Not _that_ common :grin:

To be honest, this is the only `connect`-related issue in quite a while that I can remember.

> I will talk to ssh-connect.

:+1:

Would you mind linking to that issue just in case some other user needs to find the answer in the future?

**Comment by avpjanm** [comment]
[Issue opened in ssh-connect](https://github.com/gotoh/ssh-connect/issues/6)

**Comment by rimrul** [comment]
> To be honest, this is the only `connect`-related issue in quite a while that I can remember.

The only other `connect` related issue I remember is #3617

> > I will talk to ssh-connect.
> 
> :+1:
> 
> Would you mind linking to that issue just in case some other user needs to find the answer in the future?

https://github.com/gotoh/ssh-connect/issues/6

I doubt they'll get an answer there, tough. That repository hasn't seen any activity in years.

**Comment by dscho** [comment]
> > To be honest, this is the only `connect`-related issue in quite a while that I can remember.
> 
> The only other `connect` related issue I remember is #3617

Right. There was also https://github.com/git-for-windows/git/security/advisories/GHSA-g4fv-xjqw-q7jm

> > > I will talk to ssh-connect.
> > 
> > :+1:
> > 
> > Would you mind linking to that issue just in case some other user needs to find the answer in the future?
> 
> https://github.com/gotoh/ssh-connect/issues/6
> 
> I doubt they'll get an answer there, tough. That repository hasn't seen any activity in years.

Hmm. We could study the source code, I guess :wink:

**Comment by avpjanm** [comment]
thanks for your help :)
I will stick with using https instead.
