### ISSUE TITLE
Error viewing documentation

### ISSUE THREAD

**Issue by mbtools** [git-for-windows/git#4775]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.43.0.windows.1
cpu: x86_64
built from commit: 4b968f3ea3b32a7bc50846bab49f3f381841d297
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19045.3930]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: CustomEditor
Custom Editor Path: C:\Program Files\TextPad\TextPad.exe
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? 

```
PS C:\GitHub> git credential-manager --help
fatal: 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-credential-manager.html': documentation file not found.
```

Indeed, `git-credential-manager.html` does not exist in this folder. Maybe it should be `gitcredentials.html`?

 - What did you expect to occur after running these commands?

Show the correct doc in browser

 - What actually happened instead?

error

**Comment by dscho** [comment]
Thank you for opening this ticket, @mbtools, after I failed to transfer https://github.com/git-ecosystem/git-credential-manager/issues/1517!

From https://github.com/git-ecosystem/git-credential-manager/issues/1517#issuecomment-1904069599:

> Indeed, the documentation is not there. It's in `C:/Program Files/Git/mingw64/doc/git-credential-manager/README.md`, which is not even in HTML format but in Markdown instead.

> This should probably be fixed in https://github.com/git-for-windows/build-extra/blob/HEAD/mingw-w64-git-credential-manager/PKGBUILD: The `markdown` package needs to be added as build-time dependency, and then the file should be rendered using `markdown` into the path indicated in the report, using `${pkgdir}` as the relative root directory instead of `C:/Program Files/Git`.

**Comment by dscho** [comment]
@mbtools how about giving the fix a try?

**Comment by mbtools** [comment]
Which fix? The markdown file? I'm good with that

**Comment by dscho** [comment]
> Which fix?

Patching `PKGBUILD` so that `markdown` is used to render the Markdown file as HTML and put the result in the location where `git help git-credential-manager` (which `git credential-manager --help` is implicitly converted to) expects to find it.

**Comment by mbtools** [comment]
Sorry, the C/Make world is out of my league

**Comment by dscho** [comment]
> Sorry, the C/Make world is out of my league

Well, there was no C nor `make` involved ;-)

**Comment by dscho** [comment]
/add relnote bug The `git credential-manager --help` command previously would not find a page to display in the web browser, [which has been fixed](https://github.com/git-for-windows/build-extra/pull/542).

**Comment by mbtools** [comment]
thanks for the quick fix 😺
