### ISSUE TITLE
Password request triggers an OpenSSH window

### ISSUE THREAD

**Issue by Siron777** [git-for-windows/git#478]
Hi,

I have just install git 2.6.1.windows.1 (on windows 7). Now, when git requires a password, it triggers an openssh window to get it instead of asking it in the terminal:

![git_openssh](https://cloud.githubusercontent.com/assets/15027951/10359847/880990f6-6d9c-11e5-8c16-efdde24a490e.PNG)

I guess this is not normal ?

**Comment by dscho** [comment]
Hmm. This disagrees with the documentation of the `SSH_ASKPASS` variable. That documentation says that as long as a terminal is available, it is preferred, and the graphical utility will be only called if there is no terminal.

As a work-around, you can remove the `SSH_ASKPASS` lines from `/etc/profile.d/env.sh`.

**Comment by albertosantini** [comment]
I don't know if it is related to this issue, but executing a `ssh` command, it returns to the prompt immediately.

I tried to unset `SSH_ASKPASS`, but the result is the same.

**Comment by dscho** [comment]
> executing a ssh command, it returns to the prompt immediately.

@albertosantini the graphical prompt or the one on the terminal? Kinda important..

**Comment by albertosantini** [comment]
On Windows 10 using the stock windows terminal (after the command `C:\Git\bin\bash.exe --login -i`).

**Comment by dscho** [comment]
@albertosantini so by "prompt", you did not refer to the password prompt, but to the prompt in the console window? Sorry that I ask, I find the language a little too imprecise and need to make sure that I understand you correctly.

**Comment by dscho** [comment]
Okay, and here is [what I tried](http://whathaveyoutried.com/):

On Windows Server 2008 R2, in *Git Bash*, *Git CMD* and yes, also in `cmd.exe` after calling `C:\Program Files\Git\bin\bash -l-i`, I called

```
git ls-remote user@my-machine
```

where `user@my-machine` obviously refers to a user account for an SSH server which is not equipped with a private key.

In all three cases, I got the password prompt inside the console window, as expected. In Git Bash, the `SSH_ASKPASS` variable was set as expected:

```sh
$ echo $SSH_ASKPASS
/mingw64/libexec/git-core/git-gui--askpass
```

as was the `DISPLAY` variable:

```sh
$ echo $DISPLAY
needs-to-be-defined
```

So then I thought maybe Windows 10 is different, but no, I tested the same three things on Windows 10, with the same outcome.

So I should not have trusted blindly that this is a bug, because it ain't a bug here.

But I see that you referred to `C:\Git` as the installation path, which is definitely not the default, and now I start wondering what else is non-standard in your setup that might cause this.

**Comment by albertosantini** [comment]
My setup is Portable Git (64 bit) installed in `C:\Git`.
No changes to the config files in that folder.

```
$ ssh 10.0.0.1
$
$ echo $SSH_ASKPASS
/mingw64/libexec/git-core/git-gui--askpass
$ echo $DISPLAY
needs-to-be-defined
$
```

With putty I can login correctly.

I tried to execute `ssh` using the terminal started from `git-bash.exe` and `git-cmd.exe`.
Same result: ssh command returns to the prompt immediately.

**Comment by albertosantini** [comment]
there is a problem with the known_hosts

```
$ ssh -v 10.0.0.1
OpenSSH_7.1p1, OpenSSL 1.0.2d 9 Jul 2015
...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256: ...
Please contact your system administrator.
...
ECDSA host key for 10.0.0.1 has changed and you have requested strict checking.
Host key verification failed.
$
```

I created a new server (the remote endpoint, 10.0.0.1) with the same ip.

I was wondering that warning or error is not displayed without `-v` option, at least `Host key verification failed
`
For me, it is closed. Thanks for your effort and sorry for the noise.

**Comment by dscho** [comment]
It is funny, indeed, that the message should not be shown.

So I tested now, by installing `PortableGit-2.6.1-64-bit.7z.exe` to `C:\Git`, then replacing one RSA key in one line of my `$HOME/.ssh/known_hosts` with the key of another line, then connecting to the corresponding host in a *Git Bash*:

```sh
$ ssh my-machine
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:iF55aoSyR7skcrx0GRE092RTB5tYDoQZ0qvpcFOst8E.
Please contact your system administrator.
Add correct host key in /c/Users/me/.ssh/known_hosts to get rid of this message.
Offending RSA key in /c/Users/me/.ssh/known_hosts:6
RSA host key for my-machine has changed and you have requested strict checking.
Host key verification failed.
```

So there is still something funny going on.

**Comment by frohman-wd** [comment]
I've been seeing this same issue on both Windows 7 and Windows 10 machines running Git 2.6.0 and 2.6.1.  Both SSH_ASKPASS and DISPLAY contain the values mentioned in comments a few back.  I'm not using SSH keys for remote access.  I'm using a normal HTTP connection to a local Bitbucket Server 4.0 instance and an HTTPS connection to Bitbucket.org, which both exhibit this issue.

**Comment by dscho** [comment]
Are you still seeing this issue, with the Git Credential Manager that is shipped and enabled by default since Git for Windows 2.7.3?

**Comment by albertosantini** [comment]
After months I understood the issue about ssh not displaying the banner.
In `~/.ssh/config` the line `LogLevel QUIET`.

I am very sorry for the noise.

**Comment by dscho** [comment]
@albertosantini no worries!
