### ISSUE TITLE
Unable to fetch nonbare submodule repository from share with readonly permissions

### ISSUE THREAD

**Issue by ezijp** [git-for-windows/git#479]
With git-for-windows 1.9.5 I could fetch from the submodule repositories of my coworkers. For these repositories I only have readonly permissions. Since I and one of my coworkers upgraded to git-for-windows 2.5 I am only able to fetch from readonly submodule repositories that are also on git-for-windows 2.5. When I try to fetch a submodule from a coworker who is still on 1.9.5 I get the following error message:

fatal: could not open //coworkerpc/source/repo/submodulelib/../.git/modules/submodulelib/gitdir for writing: Permission denied

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by dscho** [comment]
Could you provide a *Minimal*, Complete & Verifiable Example, please?

**Comment by ezijp** [comment]
As it appears I can succesfully fetch from yeat another coworker with git 1.9.5 it seems it has nothing to do with git 2.5 vs git 1.9.5
