### ISSUE TITLE
Using / as a value for a parameter becomes a path after parse_args() in gitbash

### ISSUE THREAD

**Issue by ewongbb** [git-for-windows/git#4798]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.41.0.windows.3
cpu: x86_64
built form commit:  4a1821dfb0c2160a4fcc85d2845f095c54339578
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 8.1 pro  64 bit  (this is also reproducible in Windows 11 using the same version of git-for-windows)
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
```
```
``
import argparse
import sys

def get_options():
    opts = argparse.ArgumentParser(description="get options")
    opts.add_argument("-d",
                                   help="specify dir",
                                   dest="use_dir",
                                   default=None,
                                   type=str)
    return opts.parse_args()

def main():
    opts = get_options()
    if opts.use_dir is not None:
        print("use_dir : %s" % opts.use_dir)
        print(sys.argv)

if __name__ == "__main__":
    main()
```

 - What did you expect to occur after running these commands?

I expected the following to be printed:
```
/
['t2.py', '-d', '/']

```
 - What actually happened instead?
the following was printed instead:
```
j:/git/
['t2.py', '-d', 'j:/git/']
```

**Comment by dscho** [comment]
From our [Release Notes' "Known Issues" section](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
>
>  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
>
>  Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "`//usr/bin/bash.exe`".

**Comment by ewongbb** [comment]
My apologies for missing that release note.

**Comment by dscho** [comment]
> My apologies for missing that release note.

TBH it's easy to miss. If you have any idea how to make these hints easier to find, please mention it here.
