### ISSUE TITLE
Suggestion for PortableGit to closely fit the Installer version

### ISSUE THREAD

**Issue by silverkorn** [git-for-windows/git#480]
I've create a little set of scripts to make a PortableGit similar as the installer version but under the user's scope, so no administration access should be required (to confirm, I have admin access so I can't totally confirm): https://github.com/silverkorn/gfw-portablegit-extuserenv

If it works properly and if you would like to integrate it into `build-extra/portable/root/`, I could create a PR under that repository with a proper structure to fit in.

Thanks!

**Comment by dscho** [comment]
> I've create a little set of scripts to make a PortableGit similar as the installer version but under the user's scope, so no administration access should be required

Sorry, I do not understand which problem is solved.

**Comment by silverkorn** [comment]
Generally:
https://github.com/git-for-windows/build-extra/blob/master/portable/root/README.portable#L28 &
https://github.com/git-for-windows/build-extra/blob/master/portable/root/README.portable#L36
In a single execution.

**Comment by dscho** [comment]
I still have no idea what you are talking about. I am sure that it would be good for me to understand, and a concise description in pleasant English prose might be the best way to get me there.

**Comment by silverkorn** [comment]
I'm sorry, English is not my native language and I thought you had read the Feature/Setup section of the suggested repository.

The scripts are used to add `Git Bash` and `Git Gui` in the right-click menu from a PortableGit setup using the `HKEY_CURRENT_USER` hive instead of the `HKEY_CLASSES_ROOT` which requires administrator rights. It also adds the `cmd/` directory in the %PATH% of the user environment variable in a persistent way (still applicable after a reboot), which doesn't require admin rights either.

Doing so, it configures a similar environment as the one with the installer which is system wide but it stays in the user's one, it doesn't require admin rights and it can applied simply by executing the `tools\portablegit-install.cmd` which could be renamed to fit better in the `build-extra/portable/root/` structure (if this is the correct path for custom files included only in the PortableGit distribution).

Let me know if it stills cryptic.
Thanks.

**Comment by dscho** [comment]
Ze English langwhich is also not my first langwhich. :stuck_out_tongue_winking_eye: 

The primary purpose of the portable Git installer is to provide a portable application (we already violate that by heeding files in `$HOME` and `$PROGRAMDATA`). I guess it is already frowned upon just how non-portable we are already, so I guess purists would take objections with installing registry keys for a portable Git.

But now I am curious: why does PortableGit need to become more like the Git installer? Does the latter not do the job for you?

**Comment by silverkorn** [comment]
Haha!
I totally understand your point with PortableGit.

Let me indicate my motivations about this:
- I used to work in companies restricting installation of softwares on a machine by a normal user, which I understand because they could install viruses affecting the whole operating system and for other security purpose. Since PortableGit is a standalone which is not system-wide, I would not see why they should be restricted to not have a simple and pleasant usage just like the the installer, that's harsh! :stuck_out_tongue_closed_eyes: 

- I do not consider PortableGit only as a USB portable application but more as a user space application, just like if I would run let say a copy of `nginx` as my user in my `/home/silverkorn/apps/nginx` without a need of root or sudo. (with the permitted non-admin ports, of course :smile:)

- Still about user space application, the `HKEY_CURRENT_USER` is directly part of the user's profile path (`%USERPROFILE%\ntuser.dat`), it's a registry hive that affect only this user. Technically, many applications plays directly in this hive for saving configurations and information instead of using a file. This is convenient when you share an application and want to avoid file flooding or mangling in the %USERPROFILE%, %LOCALAPPDATA%, %APPDATA% and/or in the relative path of the executable.

- I'm currently working on a tool to install and update user spaced applications which doesn't need admin rights. This has the advantage to step out of waiting an IT staff interaction for the main installation and for updating the application on each user's machine. You guessed it, Git for Windows is intended to be part of that set.

I hope this explains well the reasons and I want to remind you that this tool is not mandatory to be run, it would be to the user's discretion, and in no way I want to impose you to integrate it in the main repository.

Thanks!

**Comment by dscho** [comment]
> I hope this explains well the reasons and I want to remind you that this tool is not mandatory to be run, it would be to the user's discretion, and in no way I want to impose you to integrate it in the main repository.

It does. And with that explanation, I could see the value of having that script (it is only one, right?) in the portable Git distribution.

**Comment by silverkorn** [comment]
It is split into 2 WSH scripts which are called by a `.cmd` file, one for "installation" and another for "uninstalling" (So a total of 4 WSH scripts and 2 cmd files). 
I can crunch all into 1 WSH script and use arguments to reduce the number of files if desired.

**Comment by dscho** [comment]
@silverkorn feel free to open a Pull Request whenever you are ready.

**Comment by silverkorn** [comment]
Yeah, sorry, I will! :smile:
