### ISSUE TITLE
Can't add ssh key to cache with git bash under windows and putty

### ISSUE THREAD

**Issue by T3rm1** [git-for-windows/git#482]
Version: 2.6.1.windows.1
OS: Windows 7
GIT_SSH is set to plink.exe

The first time I connect to a server I'm asked to add the host fingerprint to the local cache. I have to type y or n.
It's not possible to enter either. Nothing happens. When I press ctrl+c to abort the shell tries to execute the command "y".

>The server's host key is not cached in the registry. You
>have no guarantee that the server is the computer you
>think it is.
>The server's rsa2 key fingerprint is:
>ssh-rsa 2048 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>If you trust this host, enter "y" to add the key to
>PuTTY's cache and carry on connecting.
>If you want to carry on connecting just once, without
>adding the key to the cache, enter "n".
>If you do not trust this host, press Return to abandon the
>connection.
>Store key in cache? (y/n)

**Comment by dscho** [comment]
See https://github.com/git-for-windows/git/issues/462: The PuTTY option is not shown by default, unless you have saved connections.

We also have this in our release notes' [known issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues) (shown by default at the end of every installtion):

> * If configured to use Plink, you will have to connect with putty first and accept the host key.

**Comment by T3rm1** [comment]
Oh sorry, I didn't read that. Just did a quick search here.
