### ISSUE TITLE
includeif does not work, normal include does though

### ISSUE THREAD

**Issue by schlechtOptimiziert** [git-for-windows/git#4823]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.43.0.windows.1
cpu: x86_64
built from commit: 4b968f3ea3b32a7bc50846bab49f3f381841d297
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.3155]
Windows 11, I guess.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

🤷‍♀️ Not that I know.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I am trying to use the following in my .gitconfig:
```
 [includeIf "gitdir:C:/private/repos/"]
     path = ~/.gitconfig-personal
```
 - What did you expect to occur after running these commands?

To change my Email conditionally.

 - What actually happened instead?

Did not work. No E-Mail was displayed if I use "git config user.email". (I do not have an Email configured in the .gitconfig)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, is not Repo related.

- I will Provide additional Information which will help, I guess.
.gitconfig:
```
#[user]
#	name = Dominik von Haller
#	email = not@in.use
[push]
	default = simple
[core]
    autocrlf = true
	editor = \"C:\\Users\\myName\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code\" --wait
[includeIf "gitdir:C:/private/repos/"]
    path = ~/.gitconfig-personal
[include]
     path = ~/.gitconfig.aliases
[filter "lfs"]
	clean = git-lfs clean %f
	smudge = git-lfs smudge %f
	required = true
[credential]
	helper = wincred
	provider = generic
[credential "dev.azure.com"]
	provider = azure-repos
[credential "github.com"]
	provider = github
```

gitconfig-personal:
```
[user]
	name = My name
	email = my@email.address
```

**Comment by schlechtOptimiziert** [comment]
I saw a lot of issues with this related to network hard drives. This is not it for me. C: is my internal hard drive and I do not mount anything in that.

**Comment by squidfall** [comment]
I'm just speculating, but you might check if `safe.directory` changes the behaviour. You should be able to set it temporarily as a test, by doing something like:

```
cd C:/private/repos/reponame
git -c safe.directory='*' config --list --show-origin | grep email
```

**Comment by dscho** [comment]
> ` [includeIf "gitdir:C:/private/repos/"]`

Try changing `gitdir` to `gitdir/i`?

**Comment by schlechtOptimiziert** [comment]
Tryed:
```
[includeIf "gitdir/i:C:/private/repos/"]
    path = ~/.gitconfig-personal
```
Not working.
![image](https://github.com/git-for-windows/git/assets/107460536/29c6c663-8601-4e1a-ab5b-a5e0f078eacc)

Tryed:
```
[safe]
	directory = *
```
Not working.
![image](https://github.com/git-for-windows/git/assets/107460536/1d006ac7-db75-4cda-9e16-94c9e0e1b270)

Tryed both at the same time:
Not working.
![image](https://github.com/git-for-windows/git/assets/107460536/502a4e1b-49c1-4688-94b2-4c60170a4672)

**Comment by dscho** [comment]
What does `git rev-parse --absolute-git-dir` say?

**Comment by schlechtOptimiziert** [comment]
Duo to me being in an not git tracked folder in C:\private\repos I get:
![image](https://github.com/git-for-windows/git/assets/107460536/091d4b1f-f646-42f3-b27c-09656bdc1a4c)

Is it necessary for me to be in an git tracked Folder?
![image](https://github.com/git-for-windows/git/assets/107460536/1b38fbf3-5f20-489e-9f0b-fdfd34d44617)
Well... I will be damned.

Why though? If I just configure my email in the Config without the includeif or just the include I can get my email with "git config user.email" just fine.

**Comment by schlechtOptimiziert** [comment]
I also tryed it really quick without the "[save]\n\r    directory = *" works fine.

**Comment by dscho** [comment]
> Why though?

Because `gitdir` needs, well, a Git directory.

> If I just configure my email in the Config without the includeif or just the include I can get my email with "git config user.email" just fine.

Sure. The `includeIf` makes only sense if you have multiple repositories in that location, and others in a different location which do not want the same user.email.

**Comment by schlechtOptimiziert** [comment]
Yea, I see your point. gitdir needs a GITdir.

I just don't entirely understand the reason why to implement it this way. Why not like [includeif "dir:[path]"]? Is there a technical reason to this?
I mean you could argue that you would never access the email in a "not git dir" in the first place. And that is probably true. I just don't get the reason why an "if in path" is only working in git directories.
Would be nice to understand, you know.

Either way thanks for the great help . If I where to write a google review I would give 5 stars. :)

**Comment by dscho** [comment]
> I just don't entirely understand the reason why to implement it this way.

This is a question to the larger Git project, not just Git for Windows. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

> Either way thanks for the great help . If I where to write a google review I would give 5 stars. :)

Thank you!!! ❤
