### ISSUE TITLE
Diff with cached textconv fails outside of repository

### ISSUE THREAD

**Issue by imbrish** [git-for-windows/git#4835]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4046]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Global `.gitattributes`:

```
*.txt diff=test
```

Global `.gitconfig`:

```
[diff "test"]
    textconv = cat
    cachetextconv = true
```

File `foo.txt`:

```
$ cat foo.txt

Foo bar baz
```

File `bar.txt`:

```
$ cat bar.txt

Foo bar qux
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**git-cmd.exe**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git --no-pager diff --no-index foo.txt bar.txt
```

 - What did you expect to occur after running these commands?

```
diff --git a/foo.txt b/bar.txt
index f6a4b70..2b24d27 100644
--- a/foo.txt
+++ b/bar.txt
@@ -1 +1 @@
-Foo bar baz
+Foo bar qux
```

 - What actually happened instead?

```
BUG: refs.c:2095: attempting to get main_ref_store outside of repository
```

The command gives the expected output when `cachetextconv` is disabled:

```
git --no-pager -c diff.test.cachetextconv=false diff --no-index foo.txt bar.txt
```

On git `2.43.0.windows.1` it also failed, but did print the error message reliably,
the command output was most often empty.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Not in repository**

**Comment by dscho** [comment]
This strikes me as maybe not Windows-specific. If you agree, please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

**Comment by imbrish** [comment]
I do agree and have submitted the bug report to the mailing list instead. Thanks!
