### ISSUE TITLE
Slow on Windows 10

### ISSUE THREAD

**Issue by breinjhel** [git-for-windows/git#484]
Running normal git commands take upto 15 seconds before it responds. Even just running git --version takes 15 seconds normally. 

Im using v 2.6.1. Does anybody else have also experienced this?

Thanks.

**Comment by shiftkey** [comment]
@breinjhel could you tell us a bit more about your setup? 

 - What platform and version of Git for Windows have you installed?
 - Could you attach some example commands and run them in Git Bash to help us understand more?

e.g.

```
brendanforster@SHIFTKEY52CD MINGW64 ~
$ time git version
git version 2.6.1.windows.1

real    0m0.025s
user    0m0.000s
sys     0m0.000s
```

 - Do you notice anything interesting about where you're running the command (perhaps some repositories are behaving differently to others)?

**Comment by breinjhel** [comment]
Hi,

Thanks for the fast response. 

1. Im running git 2.6.1.windows.1
2. 
$ time git --version
 git version 2.6.1.windows.1
```
real    0m6.312s
user    0m0.000s
sys     0m0.015s
```
3. I did alot of reinstalling and sometimes it works fast. Usually when I install it using "Run as administrator". After that git runs smoothly but after I restart my pc it goes back to slow git.

**Comment by shiftkey** [comment]
What version of Windows 10 are you running?
And are you using the 32-bit or 64-bit build?

**Comment by breinjhel** [comment]
64 bit

**Comment by breinjhel** [comment]
I also used Git 64 bit but i tried 32 bit and still the same

**Comment by whoisj** [comment]
As a data point I see moderate differences in values with 32 vs 64 bit. Nothing slow.

Given that Git Bash executes under Conhost, any chance you've got something funky happening with your command configuration @breinjhel ?

```
jwyman@JWYMAN-SURFACE MINGW32 ~
$ time git version
git version 2.5.0.windows.1

real    0m0.043s
user    0m0.000s
sys     0m0.015s
```

```
jwyman@JWYMAN-SURFACE MINGW64 /
$ time git version
git version 2.5.0.windows.1

real    0m0.034s
user    0m0.000s
sys     0m0.015s
```

**Comment by breinjhel** [comment]
I really am not sure why this is happening. Before I upgraded to windows 10 it was working fine. I just recently found out its slow. Are you guys using windows 10? Am I the only one experiencing this. And also I noticed when installing git it takes too long to finish like it hangs for several minutes

**Comment by breinjhel** [comment]
I think I already figured it out. Its the UAC settings in windows 10. I turned it off before. Then I tried setting it to default then reboot my pc. That fixed it. Its really weird.

**Comment by whoisj** [comment]
> I think I already figured it out. Its the UAC settings in windows 10. I turned it off before. Then I tried setting it to default then reboot my pc. That fixed it. Its really weird.

That is very weird. If can reproduce this issue on my Windows 10 setup, I'll forward this to the Windows team in Redmond and have them investigate.

Thanks

**Comment by breinjhel** [comment]
Thanks @whoisj  @shiftkey

**Comment by breinjhel** [comment]
Hi,

It seems that the issue is recurring. Things that I have noticed:
1. I can fix it when turning off the UAC then restarting pc. It also works vice versa like turning on UAC then restart. As long as theres a change setting in UAC then restarting pc git will be fast on next boot up.

2. The issue occurs after few hours after the restart. I dont really know how much time passes before git slows down again. After that I need to change UAC settings again then restart. It wont work if i dont change UAC settings first.

This is really weird and annoying at the same time. I cant work well restarting my pc everytime.

**Comment by Radrik5** [comment]
You can try using [Process Monitor](https://technet.microsoft.com/en-us/library/bb896645.aspx) to understand which operations take most of the time.

**Comment by breinjhel** [comment]
Hi,

I figured out whats causing the issue. It was Avast Anti virus. It seems its scanning git whenever I run it so after I disabled its file scanning my Git runs normally now.

**Comment by dscho** [comment]
@breinjhel thanks for letting us know, and: good work!
