### ISSUE TITLE
Seeing "BUG: refs.c:2083: reference backend is unknown" when attempting to clone

### ISSUE THREAD

**Issue by exoosh** [git-for-windows/git#4843]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? -> **Its 64-bit**
  ```
  $ git --version --build-options
  git version 2.44.0.windows.1
  cpu: x86_64
  built from commit: ad0bbfffa543db6979717be96df630d3e5741331
  sizeof-long: 4
  sizeof-size_t: 8
  shell-path: /bin/sh
  feature: fsmonitor--daemon
  ```
 - Windows 10 Pro, to be more precise 10.0.19045 Build 19045 (aka 22H2)
  ```
  $ cmd.exe /c ver
  Microsoft Windows [Version 10.0.19045.4046]
  (c) Microsoft Corporation. All rights reserved.
  ```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
Plink Path: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SSH Option: Plink
Tortoise Option: true
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I am aware of

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash within Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git -C test_helper clone https://github.com/bats-core/bats-core.git
Cloning into 'bats-core'...
BUG: refs.c:2083: reference backend is unknown
```
 - What did you expect to occur after running these commands?

I expected the clone to commence and succeed (the directory `test_helper` existed!).

 - What actually happened instead?

It aborted with the message:

```
BUG: refs.c:2083: reference backend is unknown
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/bats-core/bats-core.git

**Comment by exoosh** [comment]
It should be noted that this works with the `2.43.0.windows.1` version of Git for Windows! I just downgraded back to it.

```
Z:\temp$ git -C test_helper clone https://github.com/bats-core/bats-core.git
Cloning into 'bats-core'...
remote: Enumerating objects: 9764, done.
remote: Counting objects: 100% (2750/2750), done.
remote: Compressing objects: 100% (321/321), done.
remote: Total 9764 (delta 2561), reused 2535 (delta 2415), pack-reused 7014
Receiving objects: 100% (9764/9764), 2.34 MiB | 7.23 MiB/s, done.
Resolving deltas: 100% (6024/6024), done.
Z:\temp$ git --version
git version 2.43.0.windows.1
```

**Comment by assarbad** [comment]
This is definitely not limited to Git for Windows. I am seeing the exact same thing on Manjaro:

```
$ git clone https://github.com/kee-org/keepassrpc.git
Cloning into 'keepassrpc'...
BUG: refs.c:2083: reference backend is unknown
error: git-remote-https died of signal 6
$ git --version
git version 2.44.0
```

@dscho Clearly someone created an issue in version 2.44.0 of Git and it _also_ appears in Git for Windows.

**Comment by assarbad** [comment]
* https://lore.kernel.org/all/72771da0-a0ef-4fd9-8071-6467cd7b6a6b@kernel-space.org/T/
* https://gitlab.com/gitlab-org/git/-/merge_requests/115

**Comment by dscho** [comment]
@assarbad would you be so kind as to provide a backport PR?

**Comment by dscho** [comment]
/add relnote bug A [regression](https://github.com/git-for-windows/git/issues/4843) where `git clone` no longer worked in the presence of `includeIf.*.onbranch` config settings [has been fixed](https://github.com/git-for-windows/git/commit/199f44cb2ead34486f2588dc32d000d17e30f9cc).
