### ISSUE TITLE
rerunning update-git-for-windows returns a curl error when git is already up-to-date

### ISSUE THREAD

**Issue by locture** [git-for-windows/git#4849]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 11 64bit
Microsoft Windows [Version 10.0.22631.3155]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git update-git-for-windows
```
 - What did you expect to occur after running these commands?

Message talking about git being up-to-date already.

 - What actually happened instead?

Curl error: curl: (100) A value or data field grew larger than allowed

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
I cannot reproduce, what am I doing wrong?

```console
$ git update-git-for-windows
Git for Windows 2.44.0.windows.1 (64-bit)
Up to date
```

**Comment by dscho** [comment]
> Did you do a fresh install or update from a previous version?

The latter.

Could you run `bash -x /mingw64/bin/git-update-git-for-windows`? This should give you the `curl` invocation that caused the problems. You could then run the same command interactively, adding the [`--head` option](https://curl.se/docs/manpage.html#-I) to hopefully see the output that explains why you are seeing what you are seeing (and that I am not).

**Comment by dscho** [comment]
How certain are you that the intended `curl` executable is called? I.e. what does `type curl` say?

**Comment by dscho** [comment]
> I figured out the root cause of this problem. I have an antivirus (Kaspersky standard 2024) installed on this machine and god knows why but it is doing something weird to my curl request - I temporarily turned off its protection and everything worked out smoothly.

I got reminded about this in another ticket where a user figured out that their anti-malware switches their `stdout` to fully buffered, requiring an explicit `fflush(stdout)` at the end. Maybe this is the case here, too? Like, if `curl.exe` is not sending the complete reply back to the `update-git-for-windows` script, it would potentially explain what you observed.
