### ISSUE TITLE
Encoding problems with non-ASCII characters with Git 2.44.0

### ISSUE THREAD

**Issue by inosik** [git-for-windows/git#4851]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

There's something wrong w.r.t. encoding in Git Bash. Non-ASCII characters (German Umlauts in my case) appear garbled in the terminal output.

Git 2.43.0:

```
$ git add -p
diff --git a/test.txt b/test.txt
index a3ea8e6..0e54281 100644
--- a/test.txt
+++ b/test.txt
@@ -1 +1,2 @@
 äöü
+change
(1/1) Stage this hunk [y,n,q,a,d,e,?]?
```

Git 2.44.0:

```
$ git add -p
diff --git a/test.txt b/test.txt
index a3ea8e6..0e54281 100644
--- a/test.txt
+++ b/test.txt
@@ -1 +1,2 @@
 ├ñ├Â├╝
+change
(1/1) Stage this hunk [y,n,q,a,d,e,?]?
```

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3930]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I installed Git using Scoop, which just extracts `PortableGit-2.44.0-64-bit.7z.exe`.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing I can think of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash inside of the Windows Terminal App. But this is also reproducible using CMD, PowerShell and git-bash.exe.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add -p
```
 - What did you expect to occur after running these commands?

Non-ASCII characters should be displayed properly .

 - What actually happened instead?

Non-ASCII characters are garbled.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No specific repository, [but here's a Gist with the test file.](https://gist.github.com/inosik/bb3f218cf02ad7e2484011d02a4aa2b4)

**Comment by dscho** [comment]
I can reproduce this, and work around it by using `MSYS=disable_pcon`:

```console
$ MSYS=disable_pcon git add -p
diff --git a/test.txt b/test.txt
index a3ea8e6..0e54281 100644
--- a/test.txt
+++ b/test.txt
@@ -1 +1,2 @@
 äöü
+change
(1/1) Stage this hunk [y,n,q,a,d,e,?]?

$ MSYS=enable_pcon git add -p
diff --git a/test.txt b/test.txt
index a3ea8e6..0e54281 100644
--- a/test.txt
+++ b/test.txt
@@ -1 +1,2 @@
 ├ñ├╢├╝
+change
(1/1) Stage this hunk [y,n,q,a,d,e,?]?
```

I can also work around it by calling `chcp 65001`:

```console
$ cmd //c chcp 65001
Active code page: 65001

me@work MINGW64 ~/repros/umlauts-4851 (main)
$ MSYS=enable_pcon git add -p
diff --git a/test.txt b/test.txt
index a3ea8e6..0e54281 100644
--- a/test.txt
+++ b/test.txt
@@ -1 +1,2 @@
 äöü
+change
(1/1) Stage this hunk [y,n,q,a,d,e,?]?
```

I guess that we'll want to always change the code page to 65001 in the `enable_pcon` mode?

**Comment by Kirill** [comment]
I found this bug too. 
Folder in Explorer
![image](https://github.com/git-for-windows/git/assets/302940/e448952f-3f17-4869-9f00-21598218cd0d)

This screenshot I see in Git bush, Terminal, FAR Manager
![image](https://github.com/git-for-windows/git/assets/302940/e9c23ed4-d464-4fff-a333-d9e986002988)
![image](https://github.com/git-for-windows/git/assets/302940/277d6505-3110-4731-852f-326e355e5692)

I downgrate to 2.21.0 and it's work correctly.
![image](https://github.com/git-for-windows/git/assets/302940/1b24737c-e74a-4c93-93d0-08669bfc64bb)

I update to 2.44.0, but bug lost (I try reproduce in newer version after downgrade, but I see again correct filename in last version)
![image](https://github.com/git-for-windows/git/assets/302940/7aa3cddb-5451-48a4-bf34-90f5d89583c0)

**Comment by MrMarvel** [comment]
Same here utf-8 filenames wrong encoded in git 2.44.0.
![image](https://github.com/git-for-windows/git/assets/24212110/e9339406-77f1-44dc-af8b-a5c4a6af6dd4)
It works in git 2.42.0

**Comment by zzfhadr** [comment]
same +1
![image](https://github.com/git-for-windows/git/assets/57316428/10b3ea09-2513-4822-b4c2-2c625584259a)
but if use git bash it will work... but i don't want to use it.. not convinient for copy cand paste
![image](https://github.com/git-for-windows/git/assets/57316428/671207c6-107a-460e-a310-94799e7e6bb4)

**Comment by stenretni** [comment]
I added `chcp.com 65001 > /dev/null` to my `git-prompt.sh` as a workaround. Will see how it goes.

**Comment by drq001out** [comment]
In Chinese, VS Code & CMD, same problem!!!

**Comment by inosik** [comment]
Same behavior with Git 2.45.0.

**Comment by dscho** [comment]
@inosik I have to be honest: due to shifts in priorities at my day job, I am stretched a little too thin to work on this. Maybe you can? It would require a little bit of C++ knowledge (not C# or F#) to work on the MSYS2 runtime, which is a bit tricky to navigate, I'd try my best to assist with guidance.

**Comment by inosik** [comment]
I never did any C++ coding, but I could give it a shot. Can you tell me where I should start looking?

**Comment by dscho** [comment]
@inosik the first thing would not even be C++, but to verify that dropping the `usr\bin\msys-2.0.dll` from v2.43.0 into, say, a Portable Git v2.44.0 "fixes" the problem.

**Comment by inosik** [comment]
> verify that dropping the usr\bin\msys-2.0.dll from v2.43.0 into, say, a Portable Git v2.44.0 "fixes" the problem.

Moving `msys-2.0.dll` around didn't fix the problem, but copying `/mingw64/bin/git.exe` from Git 2.43.0 to 2.45.0 did.

**Comment by dscho** [comment]
@inosik thank you for testing! This led me into the right direction. It still took over a day to bisect, but at least now I have a fix in https://github.com/git-for-windows/git/pull/4968. Could you please verify that this works for you? You should be able to extract the `git.exe` from the PR build's artifacts, once the build finishes.

**Comment by inosik** [comment]
I've downloaded the snapshot from yesterday (2024-05-26), and this bug seems to be fixed for me. Thank you @dscho!

I've tried it inside a Windows 10 VM as well, which is a bit different of a setup than my actual machine. In the VM, the bug seems to still be reproducible, but this also might have to do with something else. Here's a screenshot:

![VirtualBoxVM_2024-05-27_08-13-56](https://github.com/git-for-windows/git/assets/11393003/a76ae5bb-5b2d-480f-86bb-c14f053f1bed)

**Comment by dscho** [comment]
> In the VM, the bug seems to still be reproducible, but this also might have to do with something else.

Looks like the diff suggests ISO-8859-1 encoding. You may need to [specify the `working-tree-encoding` accordingly](https://git-scm.com/docs/gitattributes#_working_tree_encoding).
