### ISSUE TITLE
Installer links to non-existent symbolic links wiki page

### ISSUE THREAD

**Issue by Thk54** [git-for-windows/git#4852]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

Haven't gotten that far
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win 10 64-bit

```
$ cmd.exe /c ver

cmd didn't know what /c was.
ver gave: Microsoft Windows [Version 10.0.19045.3930]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Still in setup choosing options
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

N/A
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

2.44.0 64-bit installer exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Clicked on the symbolic links link in the Enable symbolic links checkbox' description
```
 - What did you expect to occur after running these commands?

to be taken to something that said something about symbolic links

 - What actually happened instead?

Got taken to https://github.com/git-for-windows/git/wiki/Symbolic-Links which doesn't exist and thus prompts the creation of such a wiki page.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
> * What actually happened instead?
> 
> 
> Got taken to https://github.com/git-for-windows/git/wiki/Symbolic-Links which doesn't exist and thus prompts the creation of such a wiki page.

That you for bringing this to my attention. The reason is [vandalism](https://github.com/git-for-windows/git/wiki/_compare/6ffc9b132e445d74bfeb9c286eacb2db1d94e81c...5f1351c000c251805419dfb0af33821d918cc86a).

Fixed by force-pushing after blocking the perpetrator.
