### ISSUE TITLE
`wsl` command hangs indefinitely in `git-bash.exe`

### ISSUE THREAD

**Issue by HosseinMarvi** [git-for-windows/git#4856]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4046]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
WSL version:
```
$ wsl --version

WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.4046
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (Git Bash)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
wsl
```
 - What did you expect to occur after running these commands?

WSL interface to launch or to receive an error message if it couldn't launch.

 - What actually happened instead?

The command simply hangs until it's manually interrupted.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

1. `wsl` command worked without issues in version `v2.42.0.windows.1`.
2. This issue is specific to `git-bash.exe`. The `wsl` command functions as expected in other environments like `git-cmd.exe`, PowerShell, etc.

**Comment by dscho** [comment]
This issue is listed specifically in the [Known Issues in our Release Notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

The installer even suggests (on the page titled "Configuring the terminal emulator to use with Git Bash") to

> Use Windows' default console window
> [...] which works well with Win32 console programs such as interactive Python or node.js [...]

**Comment by HosseinMarvi** [comment]
Thank you @dscho
Both running `winpty wsl` and reinstalling git with the suggested config worked for me.
