### ISSUE TITLE
GUI window only appears when maximised

### ISSUE THREAD

**Issue by Rob190** [git-for-windows/git#4861]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Not shown under 'About' but it's using mingw64 so I assume 64 bit.

$ git --version --build-options

git-gui 0.21.GUTGUI
git versuib 2.44.0.windows.1
TCL 8.6.13 TK 8.6.12

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10 64 bit

$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4046]
(c) Microsoft Corporation. All rights reserved.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Mostly defaults. Using plink.

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: BashOnly
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using 2 monitors which I am told is a possible cause of the problem. (I don't know any details)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Windows GUI

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Started the GUI
```
 - What did you expect to occur after running these commands?

Expected the GUI window to appear

 - What actually happened instead?

The window did not appear even though the icon was present in the taskbar. Hovering the mouse over the icon showed a window but it would not restore. It did respond to maximize and that works as expected.

I have tried uninstalling, followed by reboot, followed by reinstall, followed by a 2nd reboot. No improvement.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not specific to a repo.

**Comment by dscho** [comment]
What does `git config --show-origin gui.geometry` say?

**Comment by dscho** [comment]
Git GUI specifically stores the window position and size ("geometry") in the Git config, another way to fix it would have been to edit that setting manually.
