### ISSUE TITLE
[Feature Request]: Provide documentation on using PowerShell for git hooks on Windows

### ISSUE THREAD

**Issue by SetTrend** [git-for-windows/git#4870]
Currently, there is no official documentation available for using PowerShell on Windows with git hooks.

<br/>

Using `pre-commit` file name with content …
```powershell
. 'C:\PowerShell\Test-Hook.ps1'
```
… results in `error: cannot spawn .git/hooks/pre-commit: No such file or directory`

<br/>

Using `pre-commit` file name with content …
```powershell
#!/usr/bin/env pwsh

. 'C:\PowerShell\Test-Hook.ps1'
```
… results in `Processing -File '.git/hooks/pre-commit' failed because the file does not have a '.ps1' extension. Specify a valid PowerShell script file name, and then try again.`

<br/>

Using `pre-commit.ps1` file name with content …
```powershell
#!/usr/bin/env pwsh

. 'C:\PowerShell\Test-Hook.ps1'
```
… Is not getting processed at all

<br/>

It cannot be reasonable to be compelled to launch a Unix shell runtime session first for starting a PowerShell runtime session next just for the sake of being able to use PowerShell for git hooks.

Please clarify.

---

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```powershell
PS> git --version --build-options

git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```powershell
PS> Get-ComputerInfo -Property OSName, OSVersion

OsName                   OsVersion
------                   ---------
Microsoft Windows 10 Pro 10.0.19045
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rimrul** [comment]
> Currently, there is no official documentation available for using PowerShell on Windows with git hooks.

There is generic documentation that apploes to everything.

> Using `pre-commit` file name with content …
> ```powershell
> . 'C:\PowerShell\Test-Hook.ps1'
> ```
> … results in `error: cannot spawn .git/hooks/pre-commit: No such file or directory`

Without a shebang the file probably gets executed in bash.

> Using `pre-commit` file name with content …
> ```powershell
> #!/usr/bin/env pwsh
> 
> . 'C:\PowerShell\Test-Hook.ps1'
> ```

This looks correct as far as Git is concerned

> … results in `Processing -File '.git/hooks/pre-commit' failed because the file does not have a '.ps1' extension. Specify a valid PowerShell script file name, and then try again.`

And that's unfortunate powershell behaviour, that disqualifies powershell from being used for Git hooks.

> Using `pre-commit.ps1` file name with content …

That's not a hook file.

> It cannot be reasonable to be compelled to launch a Unix shell runtime session first for starting a PowerShell runtime session next just for the sake of being able to use PowerShell for git hooks.

Something like that is your only option.

**Comment by SetTrend** [comment]
Thanks for clarifying, @rimrul.
