### ISSUE TITLE
git send-email not working with big emails

### ISSUE THREAD

**Issue by DJm00n** [git-for-windows/git#489]
When I tried to send email via:

    $ git send-email outgoing/*
It properly sent cover letter email and then stopped at patch email (around 75kb) with message:

    Connection closed at /usr/lib/git-core/git-send-email line 1369, <FIN> line 5
In .git/config I have:

    [sendemail]
        smtpEncryption = tls
        smtpServer = smtp.gmail.com
        smtpUser = ******@gmail.com
        smtpServerPort = 587
-
    $ git --version
    git version 2.6.1.windows.1
Same story in msys2 git. I don't know who is responsible for that: upstream or git-for-windows team.

PS: Workaround from [this thread](http://www.spinics.net/lists/git/msg256511.html) is working.

**Comment by dscho** [comment]
This has been reported upstream.

Actually, much much better: [a patch has been sent upstream](http://thread.gmane.org/gmane.comp.version-control.git/278840/focus=278848).

Even better: it has been [applied to the `next` branch](https://github.com/git/git/commit/f60c483d1d135a1f5f7c6067198a6207f1e59dc6) (which is the second step before hitting the next version, after being applied into `pu`).
