### ISSUE TITLE
Running Git Bash from the Git GUI always launches it within a Windows default console

### ISSUE THREAD

**Issue by tomyy** [git-for-windows/git#490]
During installation of git 2.6.1 on the page "Configure the terminal emulator to use with Git Bash" I selected the option "Use MinTTY".

This works fine if I have a folder open in the Windows Explorer and select the option "Git Bash Here".

However, if I launch the Git GUI by using "Git GUI Here" and then start "Git Bash" from within the Git GUI, Git Bash will start with a Windows default console window.

This is a computer running Windows 8.1 (64 bit) and git version 2.6.1.windows.1 (also 64 bit)

**Comment by dscho** [comment]
@tomyy the easiest way to move forward with this is to use the command

```sh
grep "Git Bash" /mingw64/share/git-gui/lib
```

in a Git Bash, then figure out which call site is responsible, and then imitate https://github.com/git-for-windows/git/commit/c930764ce4ac91a3ff9535a9a5f76cb8faae0e66 to call `git-bash.exe` instead of `bash.exe`.

**Comment by tomyy** [comment]
For me this change did the trick:
```
$ git diff
diff --git a/git-gui/git-gui.sh b/git-gui/git-gui.sh
index ce167d4..b8a7090 100755
--- a/git-gui/git-gui.sh
+++ b/git-gui/git-gui.sh
@@ -2670,7 +2670,7 @@ if {[is_Windows]} {
        .mbar.repository add command \
                -label [mc "Git Bash"] \
                -command {eval exec [auto_execok start] \
-                                         [list "Git Bash" bash --login -l &]}
+                                         [list "Git Bash" "c:\\Program Files\\git\\git-bash.exe" &]}
 }

 if {[is_Windows] || ![is_bare]} {
```
Not sure however on how to implement this independent of the installation directory of Git and how to bring back this change into the git-gui project...

**Comment by dscho** [comment]
@tomyy This is promising! The way I did things in c930764ce4ac91a3ff9535a9a5f76cb8faae0e66 was to use the absolute path of the script itself and transform it into the path of the desired executable, then detect whether it actually exists (because Git GUI can be run in many more setups than Git for Windows, and `/cmd/git-gui.exe` is not available everywhere). The equivalent should be possible here, too:

```tcl
# Use /git-bash.exe if available 
set normalized [file normalize $::argv0] 
regsub "/mingw../libexec/git-core/git-gui$" \ 
	$normalized "/git-bash.exe" cmdLine 
if {$cmdLine != $normalized && [file exists $cmdLine]} { 
	set cmdLine [list "Git Bash" $cmdLine &]
} else { 
	set cmdLine [list "Git Bash" bash --login -l &]
} 

.mbar.repository add command \
                -label [mc "Git Bash"] \
                -command {eval exec [auto_execok start] $cmdLine}
```

Could you test whether that works, too?

**Comment by tomyy** [comment]
I tested that too and it works fine with the Windows command prompt and with MinTTY.

I've created a pull request: https://github.com/git-for-windows/git/pull/492

**Comment by dscho** [comment]
Perfect, thanks!
