### ISSUE TITLE
Resolve .cmd/.bat files from `PATH` without extension as `core.editor`

### ISSUE THREAD

**Issue by segrey** [git-for-windows/git#4902]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4170]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config --global core.editor my-notepad
git commit
```
 - What did you expect to occur after running these commands?

my-notepad.cmd:
```
notepad.exe %1
```

I would expect that Git runs `my-notepad.cmd` which in its turn runs `notepad.exe COMMIT_EDITMSG`.

 - What actually happened instead?

```
hint: Waiting for your editor to close the file... error: cannot spawn my-notepad: No such file or directory
error: unable to start editor 'my-notepad'
Please supply the message using either -m or -F option.
```

Please note: everything works if `my-notepad.cmd` is specified as `core.editor`:
```
PS C:\Users\serge\example> git config --global core.editor my-notepad.cmd
PS C:\Users\serge\example> git commit
hint: Waiting for your editor to close the file...
C:\Users\serge\example>notepad.exe C:/Users/serge/example/.git/COMMIT_EDITMSG
[master 09365c7] 8
 1 file changed, 1 insertion(+), 1 deletion(-)
```

When running manually, both `my-notepad.cmd` and `my-notepad` are resolved from `PATH` correctly and work as expected. Maybe Git doesn't support `PATHEXT` properly when resolving `my-notepad`? It's default in my case:
```
echo $env:PATHEXT
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, the problem is not specific to a particular repository.

**Comment by rimrul** [comment]
> Maybe Git doesn't support PATHEXT properly

A more acurate description would be that we don't support `PATHEXT` at all. Where looking for files with a `.exe` extension or no extension (preferably with a shebang in that case).

See also #2255, #546
