### ISSUE TITLE
git bash recognizes mkdir parameter error when using yarn command

### ISSUE THREAD

**Issue by SeepMystery** [git-for-windows/git#4909]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [version 10.0.19045.4291]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
no
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
Bash
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# bug triggered by mkdir [-p] [--parents]
# installed yarn version 1.22.22
yarn build
# package.json details
# "scripts": {
#  "build": "yarn cp && parcel build ./src/*.html --dist-dir xxxxxxxx",
#  "cp": "yarn clean && mkdir -p xxxxxxxx && cp -r ./src/static/* xxxxxxxx",
#  "clean": "rm -rf .parcel-cache && rm -rf dist && rm -rf xxxxxxxx",
# }
# then trigger in mkdir -p
# mkdir -p create a new folder named -p
# If I change the argument to --parents, it creates the --parents folder
```
 - What did you expect to occur after running these commands?

**The `yarn build` will run successfully**

 - What actually happened instead?
```
$ yarn build
yarn run v1.22.22
$ yarn cp && parcel build ./src/*.html --dist-dir xxxxxxxx
$ yarn clean && mkdir --parents xxxxxxxx && cp -r ./src/static/* xxxxxxxx
$ rm -rf .parcel-cache && rm -rf dist && rm -rf xxxxxxxx
The subdirectory or file --parents already exists.
Error handling: --parents.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

[Can test in this repository url](https://github.com/up209d/ResourcesSaverExt/tree/master)

**Comment by dscho** [comment]
The POSIX standard [says nothing about `--parents`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/mkdir.html). Only about `-p`. Are you sure you're looking at portable code?

**Comment by SeepMystery** [comment]
Problems occur even with the -p parameter

**Comment by dscho** [comment]
@SeepMystery can you reduce this to a _Minimal_, Complete & Verifiable Example? Having to use `yarn` is adding a big complexity that no longer qualifies your MCVE for being minimal.

**Comment by SeepMystery** [comment]
After my examination of the yarn source code, the problem shouldn't be in the git bash terminal, and it doesn't seem to be in yarn either, this could be caused by something more underlying
