### ISSUE TITLE
Weird issue with python input prompt after upgrading to 2.6.1

### ISSUE THREAD

**Issue by fletchowns** [git-for-windows/git#491]
Any python program I run that prompts for user input doesn't seem to work anymore in MINGW64 after upgrading to Git for Windows 2.6.1

Take the following snippet for example:
```python
test = raw_input('this is a test: ')
print(test)
```

When I run it it's just blank, until I hit enter and then I see "this is a test:" but then the program exits.

I first noticed this when trying to run a fabric script that prompts for user input.

**Comment by dscho** [comment]
> after upgrading to Git for Windows 2.6.1

From which version.

> Any python program I run

Using which Python.

Please provide a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve) that let's Git for Windows developers reproduce the issue efficiently.

**Comment by fletchowns** [comment]
Can't remember which version I was on before exactly, maybe 1.8.5 or 1.9.4.

Python version is 2.7.8.

I've found it does work correctly if I run ```winpty python test.py```

**Comment by fletchowns** [comment]
Looks to be a duplicate of this ticket: https://github.com/git-for-windows/git/issues/399

**Comment by dscho** [comment]
@fletchowns it appears that we do not override `python`, but only `python2.7`. We would somehow need to detect whether the first `python` refers to an MSys2 Python or not, and [add an alias](https://github.com/git-for-windows/build-extra/blob/master/git-extra/profile.d/aliases.sh#L13-L16) in the latter case (and *only* in the latter case).

**Comment by fletchowns** [comment]
@dscho interesting! Thanks for taking a look. Should I re-open this ticket?

I also ran into the issue when running the [fab](http://www.fabfile.org/) command - should that be added to the aliases as well?

**Comment by dscho** [comment]
@fletchowns since I cannot really test your use cases, it would be better to open a Pull Request.

**Comment by fletchowns** [comment]
@dscho I'm not sure how to detect whether or not ```python``` refers to an MSys2 Python.

Why not just run everything through ```winpty```? It seems like maintaining a list of specific programs will be cumbersome long term.

**Comment by dscho** [comment]
> how to detect whether or not python refers to an MSys2 Python.

@fletchowns that is easy:

```sh
case "$(type python.exe 2>/dev/null)" in
/mingw64/bin/python.exe|/usr/bin/python.exe)
    # This Python knows about the MSys2 console;;
*)
    ... <override python with winpty python
    ;;
esac
```

> Why not just run everything through winpty?

@fletchowns measure it. No, seriously, measure the difference in startup time.
