### ISSUE TITLE
bash --login skips the loading of .bashrc file, even with .bash_profile

### ISSUE THREAD

**Issue by SeepMystery** [git-for-windows/git#4910]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.44.0.windows.1
cpu: x86_64
built from commit: ad0bbfffa543db6979717be96df630d3e5741331
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [version 10.0.19045.4291]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
no
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
Bash
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# loaded .bashrc file and .bash_profile
bash
# Doesn't load .bashrc and .bash_profile file
bash --login

# Contents of .bash_profile file (unix (LF) utf-8)
if [ -f '~/.bashrc' ]; then
    . ~/.bashrc
fi

# Contents of .bashrc file (unix (LF) utf-8)
HISTSIZE=1000
```

**Comment by dscho** [comment]
The purpose of [Git for Windows](https://git-for-windows.github.io/) is really to bring *Git* to Windows. I am not sure that it is a wise idea trying to load the Git for Windows tracker with questions and reports that have very little to do with _Git_.

As to the `.bashrc` file: we do have https://github.com/git-for-windows/build-extra/blob/HEAD/git-extra/bash_profile.sh which gets installed into `/etc/profile.d/` and tries to help un-confuse users.

However, as is documented in https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html, Bash is not supposed to source `.bashrc` in login shells.
