### ISSUE TITLE
commit bug

### ISSUE THREAD

**Issue by suraj7974** [git-for-windows/git#4912]
While commit if our device time is not correct ( eg: one day before the current) it will store commit in the previous day

**Comment by dscho** [comment]
Does not seem like a bug in Git for Windows to me, but in your setup. Nothing we can do over here to adjust your computer's clock.

**Comment by suraj7974** [comment]
But from this someone can commit to any date many number of times to manipulate someone.

**Comment by dscho** [comment]
Yes, and this is a known issue, and it is not specific to Git _for Windows_. If you feel strongly enough about it, please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
