### ISSUE TITLE
Git clone fails with 'error: RPC failed; curl 23 Failed writing received data to disk/application'

### ISSUE THREAD

**Issue by Zayyy01** [git-for-windows/git#4942]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.45.0.windows.1
cpu: x86_64
built from commit: b5d0511969ccd9ab86395c37e5a7619d8b4e7c32
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.3447]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: CustomEditor
Custom Editor Path: C:\Program Files\Beyond Compare 4\BCompare.exe
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Only fails if the git server uses (http) compression

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Only fails if the git server uses (http) compression
git clone https://username:pwd@host.xyz/username/repository.git
```
 - What did you expect to occur after running these commands?

clone the repository successfully

 - What actually happened instead?

error: RPC failed; curl 23 Failed writing received data to disk/application

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Repository is private.

There is a known curl issue (https://github.com/curl/curl/issues/13212) which can be related to this. It's present both in 8.7.0 and 8.7.1 curl versions.
It has been fixed in https://github.com/curl/curl/pull/13219 but there is no new curl release yet.

**Comment by dscho** [comment]
> It has been fixed in [curl/curl#13219](https://github.com/curl/curl/pull/13219) but there is no new curl release yet.

@Zayyy01 could you try your hand at a backport? It's a [single commit](https://github.com/curl/curl/pull/13219/commits) that could be integrated like this backport: https://github.com/git-for-windows/MINGW-packages/commit/e5725f2db88e1e217d15a2d1e8a46b29ffea479b. If you then open a PR, the PR build will produce build artifacts including a Pacman package (which is really just a glorified `.tar` archive) whose contents you could unpack over a portable Git to verify that the fix works in your scenario (I cannot help testing that scenario because the repository is private).

If you can do that and confirm that this patch fixes your issue, I will gladly merge the PR!

**Comment by Zayyy01** [comment]
@dscho thank you for the detailed answer. As I see curl 8.7.2 is planned to be released on May 22, 2024. As it's only a week from now, I'll wait for the official release and in the meantime temporarily switch off http compression in our internal git server.

**Comment by dscho** [comment]
@Zayyy01 if we wait for 8.7.2, we might miss the Git v2.45.2 train. The next Git version (and hence also the next Git for Windows version) is [scheduled for end of July](https://gh.io/gitCal).
