### ISSUE TITLE
gibberish output after installed in msys2

### ISSUE THREAD

**Issue by MMMMMoris** [git-for-windows/git#4943]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

    ```
    $ git --version --build-options
    
    git version 2.45.0.windows.1
    cpu: x86_64
    built from commit: b5d0511969ccd9ab86395c37e5a7619d8b4e7c32
    sizeof-long: 4
    sizeof-size_t: 8
    shell-path: /bin/sh
    feature: fsmonitor--daemon
    ```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
   Windows 11 x64 23H2
    ```
    $ cmd.exe /c ver
    
    Microsoft Windows [Version 10.0.22631.3527]
    (c) Microsoft Corporation. All rights reserved.
    ```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

    ```
    # One of the following:
    > type "C:\Program Files\Git\etc\install-options.txt"
    > type "C:\Program Files (x86)\Git\etc\install-options.txt"
    > type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
    > type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
    $ cat /etc/install-options.txt
    ```
   I didn't use a regular installation method, I installed git-for-windows following [this doc](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper/).

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

    Here is `$OutputEncoding` of my powershell
    ```log
    Preamble          :
    BodyName          : utf-8
    EncodingName      : Unicode (UTF-8)
    HeaderName        : utf-8
    WebName           : utf-8
    WindowsCodePage   : 1200
    IsBrowserDisplay  : True
    IsBrowserSave     : True
    IsMailNewsDisplay : True
    IsMailNewsSave    : True
    IsSingleByte      : False
    EncoderFallback   : System.Text.EncoderReplacementFallback
    DecoderFallback   : System.Text.DecoderReplacementFallback
    IsReadOnly        : True
    CodePage          : 65001
    ```
    And my system locale is Chinese.
![image](https://github.com/git-for-windows/git/assets/63332824/a38a5d92-b77e-4a3b-95ff-e4f4bb287990)
 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

   **PowerShell**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

    ```shell
    git
    ```
 - What did you expect to occur after running these commands?

   **Normal output from git, no gibberish**

 - What actually happened instead?

   ![image](https://github.com/git-for-windows/git/assets/63332824/48a355aa-7770-4c98-be12-7e23396d4aa2)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

   **I am using the latest version of git install following [this doc](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper/)**

**Comment by dscho** [comment]
> * I am using the latest version of git install following [this doc](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper/)

That document literally starts with:

## Please note that this scenario is not officially supported by Git for Windows
