### ISSUE TITLE
git fsck not working on private network path, safe directory is set with parent path

### ISSUE THREAD

**Issue by Xargas** [git-for-windows/git#4944]
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 git version 2.45.0.windows.1

```
$ git --version --build-options

git version 2.45.0.windows.1
cpu: x86_64
built from commit: b5d0511969ccd9ab86395c37e5a7619d8b4e7c32
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Microsoft Windows 11 Pro
10.0.22631
64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.3447]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Disabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
Using Beyond Compare for diff, all other settings are default.
I think this should not be related
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
 I tried cmd.exe, Git Bash, PowerShell. All with the same result
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
```
(User-IDs anonymized)

git fsck --progress
fatal: detected dubious ownership in repository at '//192.168.0.2/repositories/app1.git'
'//192.168.0.2/repositories/app1.git' is owned by:
        (inconvertible) (S-X-X-XX-XXXYYYZZZZ-XXXXYYYZZZ-XXXXYYYYZZ-XXXX)
but the current user is:
        DESKTOP/Xargas (S-Z-Z-ZZ-ZZZYYYZZZZ-ZZZZYYYZZZ-XXXXYYYYZZ-XXXX)
To add an exception for this directory, call:

        git config --global --add safe.directory '%(prefix)///192.168.0.2/repositories/app1.git'
```

 - What did you expect to occur after running these commands?
```
Running the git file system check as usual, as the global git config contains the line for the safe directory, specifying the parent directory as safe, so all sub directories should be accepted as safe git repositories.
[safe]
    directory = %(prefix)///192.168.0.2/*
```

 - What actually happened instead?
```
Error message as above. No file system check
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
```
Repository is on a private network. There I have a folder where only I have access. I use it to automatically backup repository data.
(nightly, weekly, monthly)
```

**Comment by rimrul** [comment]
There is no pattern matching in `safe.directory`. There is only `*` and explicit names.

**Comment by dscho** [comment]
See also https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory.

Besides, this is not a Windows-specific issue. @Xargas if you feel that this should be changed, please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
