### ISSUE TITLE
perl one-liners doing substitution with s|pattern|replacement| called from webpack.config.js apparently try to run "pattern" as a program

### ISSUE THREAD

**Issue by coderextreme** [git-for-windows/git#4949]
This is not a problem on WSL2 or MacOS apparently.  This is just a heads up, as I'd like to do development under Git Bash, and it has this problem, with it's version of perl or webpack. I haven't tested another perl version that I know of.  Nor have I tested perl outside of webpack.

things that fail might be:

```
`perl -p0e 's|\\/\\*.*?\\*\\/||sg' src/x_ite.css | npx sass --stdin --style compressed > dist/x_ite.css`,
`perl -p0i -e 's|^|/* X_ITE v'$npm_package_version' */|sg' dist/x_ite.css`,
`perl -p0i -e 's|".*?"|'\`npm pkg get version\`'|sg' src/x_ite/BROWSER_VERSION.js`,
`perl -p0i -e 's/export default (?:true|false);/export default false;/sg' src/x_ite/DEVELOPMENT.js`,
`perl -p0i -e 's|"X_ITE.X3D"|"X_ITE.X3D-'$npm_package_version'"|sg' dist/x_ite{,.min}.js`,
`perl -p0i -e 's|^(/\\*.*?\\*/)?\\s*|/* X_ITE v'$npm_package_version' */|sg' dist/x_ite{,.min}.js`,
`perl -p0i -e 's|sourceMappingURL=.*?\\.map||sg' dist/x_ite{,.min}.js`,
`perl -p0i -e 's/export default (?:true|false);/export default true;/sg' src/x_ite/DEVELOPMENT.js`,
`perl -p0i -e 's|".*?"|'\`npm pkg get version\`'|sg' src/x_ite/BROWSER_VERSION.js`,
`perl -p0i -e 's/export default (?:true|false);/export default false;/sg' src/x_ite/DEVELOPMENT.js`,
`perl -p0i -e 's|"X_ITE.X3D"|"X_ITE.X3D-'$npm_package_version'"|sg' dist/x_ite{,.min}.mjs`,
`perl -p0i -e 's|^(/\\*.*?\\*/)?\\s*|/* X_ITE v'$npm_package_version' */|sg' dist/x_ite{,.min}.mjs`,
`perl -p0i -e 's|sourceMappingURL=.*?\\.map||sg' dist/x_ite{,.min}.mjs`,
`perl -p0i -e 's/export default (?:true|false);/export default true;/sg' src/x_ite/DEVELOPMENT.js`,
`perl -p0i -e 's|"X_ITE.X3D"|"X_ITE.X3D-'$npm_package_version'"|sg' dist/assets/components/${name}{,.min}.js`,
`perl -p0i -e 's|^(/\\*.*?\\*/)?\\s*|/* X_ITE v'$npm_package_version' */|sg' dist/assets/components/${name}{,.min}.js`,
`perl -p0i -e 's|sourceMappingURL=.*?\\.map||sg' dist/assets/components/${name}{,.min}.js`,
`perl -p0i -e 's|("./index.js"\\).*?\\})|$1.bind({})|sg' dist/assets/components/${name}{,.min}.js`,
`perl -p0i -e 's/[,;]*(var\\s+)?(CharLS|OpenJPEG)\\s*=\\s*function/;module.exports=function/sg' dist/assets/components/${name}{,.min}.js`,
```
These are from X_ITE X3D Brower's webpack.config.js which is designed to run on macs. Note that even pattern alternation with | tries to run a program.

Again, this is not a show stopper, as I've moved development to WSL2, but WSL2 can't really use the Windows file system without upgrading the Linux kernel, which is at 5.15

Here's a typical webpack config example:

         new WebpackShellPluginNext ({
            logging: false,
            onBuildStart: {
               scripts: [
                  `echo 'Bundling x_ite ...'`,
                  `perl -p0e 's|\\/\\*.*?\\*\\/||sg' src/x_ite.css | npx sass --stdin --style compressed > dist/x_ite.css`,
                  `perl -p0i -e 's|^|/* X_ITE v'$npm_package_version' */|sg' dist/x_ite.css`,
                  `perl -p0i -e 's|".*?"|'\`npm pkg get version\`'|sg' src/x_ite/BROWSER_VERSION.js`,
                  `perl -p0i -e 's/export default (?:true|false);/export default false;/sg' src/x_ite/DEVELOPMENT.js`,
               ],
               blocking: true,
               parallel: false,
            },
            onBuildEnd: {                                                                                                              scripts: [
                  // Version
                  `perl -p0i -e 's|"X_ITE.X3D"|"X_ITE.X3D-'$npm_package_version'"|sg' dist/x_ite{,.min}.js`,
                  `perl -p0i -e 's|^(/\\*.*?\\*/)?\\s*|/* X_ITE v'$npm_package_version' */|sg' dist/x_ite{,.min}.js`,
                  // Source Maps
                  `perl -p0i -e 's|sourceMappingURL=.*?\\.map||sg' dist/x_ite{,.min}.js`,
                  // Debug
                  `perl -p0i -e 's/export default (?:true|false);/export default true;/sg' src/x_ite/DEVELOPMENT.js`,
                  // Licenses
                  `cp LICENSE.md dist/LICENSE.md`,
                  `echo '\`\`\`' >> dist/LICENSE.md`,
                  `touch dist/x_ite.min.js.LICENSE.txt`,
                  `cat dist/x_ite.min.js.LICENSE.txt >> dist/LICENSE.md`,
                  `rm dist/x_ite.min.js.LICENSE.txt`,
                  `echo '\`\`\`' >> dist/LICENSE.md`,
               ],
               blocking: false,
               parallel: false,                                                                                                     },                                                                                                                  }),

I hope this gets fixed...

**Comment by rimrul** [comment]
So these commands get called from javascript code, right? Presumably through `nodejs`? In that case where do you get that `nodejs` from and how does it execute these commands? If it's a native Windows `nodejs` I suspect that these get passed to `cmd.exe` (as opposed to any sort of POSIX-ish shell) which does not follow POSIX shell quoting rules. I don't think there is anything we can fix about that.

**Comment by coderextreme** [comment]
I'm running whatever webpack runs internally.  I'm not sure if that's
node.exe or some wrapper.

John

**Comment by rimrul** [comment]
The [webpack installation guide starts with](https://webpack.js.org/guides/installation/) starts with

> Before we begin, make sure you have a fresh version of Node.js installed. The current Long Term Support (LTS) release is an ideal starting point.

So there's probably a `node` involved somewhere along the line.

This `WebPackShellPluginNext` thing uses [`exec`](https://github.com/s00d/webpack-shell-plugin-next/blob/7b5c5861322d48c90cd824c4ae0028dd523f948f/src/index.ts#L142)/[`spawn`](https://github.com/s00d/webpack-shell-plugin-next/blob/7b5c5861322d48c90cd824c4ae0028dd523f948f/src/index.ts#L149) and [`execSync`](https://github.com/s00d/webpack-shell-plugin-next/blob/7b5c5861322d48c90cd824c4ae0028dd523f948f/src/index.ts#L126)/[`spawnSync`](https://github.com/s00d/webpack-shell-plugin-next/blob/7b5c5861322d48c90cd824c4ae0028dd523f948f/src/index.ts#L132) to run those scripts. At that point `node` seems to pass on your commands to `cmd`.

**Comment by coderextreme** [comment]
Good point.  I installed via npm, and didn’t read the installation guide.

I was guessing something like that.  My upstream request was rejected that
patched this.  The patch wasn’t perfect.

Mac snob I guess.  I have 2 old macs gathering dust.

John

**Comment by dscho** [comment]
I'll close this here, as it is not a Git for Windows bug.
