### ISSUE TITLE
gitk - arrow keys do not work anymore in text input fields of main window

### ISSUE THREAD

**Issue by harndt** [git-for-windows/git#495]
Since updating to git 2.6.1 (64 bit) on Windows 7 (64 bit) the left and right arrow keys do not work anymore in text input fields of the main window of gitk (SHA1 ID, find, search). To reproduce, start gitk, click into the SHA1 ID text field and try to move the cursor with the left and right arrow keys.

Changing lines 2547/2548 in gitk from

    bindkey <Key-Right> "goforw"
    bindkey <Key-Left> "goback"

to

    bindkey <<NextChar>> "goforw"
    bindkey <<PrevChar>> "goback"

seems to fix the problem.

This seems to be a byproduct of updating tcl/tk to 8.6. Tk Changes / New Events near the bottom of http://wiki.tcl.tk/21276 mentions newly introduced events NextChar/PrevChar which inspired me to try the above fix. This probably means this bug affects other operating systems too.

**Comment by dscho** [comment]
> Since updating to git 2.6.1 (64 bit)

From which version?

> Changing lines 2547/2548 in gitk from
> 
> bindkey <Key-Right> "goforw"
> bindkey <Key-Left> "goback"
> 
> to
> 
> bindkey <<NextChar>> "goforw"
> bindkey <<PrevChar>> "goback"
> 
> seems to fix the problem.

Good. The trick will be to do this in a backwards-compatible manner...

**Comment by dscho** [comment]
> The trick will be to do this in a backwards-compatible manner...

Did you have any luck figuring out a way to fix this so that it does not break setups with older Tcl/Tk?
