### ISSUE TITLE
package-versions.txt file missing from build-extra and 2.45.1-32-bit.7z.exe

### ISSUE THREAD

**Issue by mcgitty** [git-for-windows/git#4955]
For the 2.45.1 release, file 'package-versions-2.45.1.txt' is missing from repo folder: [build-extra/versions](https://github.com/git-for-windows/build-extra/tree/main/versions)

File 'package-versions.txt' does exist in release asset: [PortableGit-2.45.1-64-bit.7z.exe](https://github.com/git-for-windows/git/releases/download/v2.45.1.windows.1/PortableGit-2.45.1-64-bit.7z.exe). However, that file is missing from the 32-bit asset: [PortableGit-2.45.1-32-bit.7z.exe](https://github.com/git-for-windows/git/releases/download/v2.45.1.windows.1/PortableGit-2.45.1-32-bit.7z.exe)

Something related to generating the package-versions.txt file is broken for this release.

**Comment by dscho** [comment]
I simply didn't get around to doing it earlier, because of the many follow-up tasks I had to do (and still have to). Now I pushed the changes: https://github.com/git-for-windows/build-extra/compare/90ca2c156...51c8a7664

I honestly do not know why it's not in the 32-bit version, though. Did you see that happen before?

**Comment by mcgitty** [comment]
No, only in that 32-bit asset. For example, that file exists in the previous version asset [PortableGit-2.45.0-32-bit.7z.exe](https://github.com/git-for-windows/git/releases/download/v2.45.0.windows.1/PortableGit-2.45.0-32-bit.7z.exe). That means only one of two issues reported here is fixed, unless it shows up again in newer 32-bit assets.

**Comment by dscho** [comment]
> That means only one of two issues reported here is fixed, unless it shows up again in newer 32-bit assets.

I've opened https://github.com/git-for-windows/build-extra/pull/555 that I still would love for you to review @mcgitty.
