### ISSUE TITLE
Chinese display garbled characters when use git reset

### ISSUE THREAD

**Issue by aengusjiang** [git-for-windows/git#4957]
git version: Git-2.45.1-64-bit

windows:
![image](https://github.com/git-for-windows/git/assets/22406984/a3e2d440-8c85-4009-9e91-4ca4fe99bb84)

windows terminal version:1.20.11271.0

issue :
run git reset:
![image](https://github.com/git-for-windows/git/assets/22406984/27283b46-a5f2-4ab5-acec-8cfe665b6b8b)

run git log:
![image](https://github.com/git-for-windows/git/assets/22406984/8eb8c492-f660-497b-a96a-416b69351f91)

git config:
[user]
	email = aengusjiang@hotmail.com
	name = Aengus.Jiang
[commit]
	gpgSign = false
[pull]
	rebase = false
[gui]
	pruneduringfetch = true
	encoding = utf-8
[smartgit "submodule"]
	fetchalways = false
	update = true
	initializenew = true
[push]
	recurseSubmodules = check
[color]
	ui = true
[core]
	fileMode = false
	autocrlf = false
	quotepath = false
[i18n]
	commitEncoding = utf-8
	logoutputencoding = utf-8
[fetch]
	prune = false
[rebase]
	autoStash = false
	autosquash = false
	updateRefs = false
[i18n "commit"]
	encoding = utf-8

**Comment by dscho** [comment]
Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by aengusjiang** [comment]
the latest snapshot work well for this issue.

**Comment by dscho** [comment]
> the latest snapshot work well for this issue.

Thank you for testing. I am now convinced that this is the same issue as #4851.
