### ISSUE TITLE
Cannot click on lower checkbox or Next, Install, Finish buttons. (Focus with TAB and pressing enter works)

### ISSUE THREAD

**Issue by rocknowradio** [git-for-windows/git#4964]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.45.1.windows.1
cpu: x86_64
built from commit: 965b16798dab6962ada5b0d8cf0dca68f385c448
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4412]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

N/A
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Upgrading from git version 2.37.2.windows.2

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Double-clicked the downloaded file:
C:\Users\**username**\Downloads\Git-2.45.1-64-bit.exe
```
 - What did you expect to occur after running these commands?

Able to click on Install button after setup launches (or click on Finish after completes).

 - What actually happened instead?

The buttons do not respond to mouse click or spacebar. Positioning with TAB the ENTER works.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Hmm. I have no idea what happens here. The main difference I see between the report and my setup is:

> ```console
> $ cmd.exe /c ver
>
> Microsoft Windows [Version 10.0.19045.4412]
> ```

I get "Version 10.0.22631.3593" with that command.

> Upgrading from git version 2.37.2.windows.2

There have been quite a couple of versions in between. Do you see the same behavior when starting, say, [v2.37.3](https://github.com/git-for-windows/git/releases/tag/v2.37.3.windows.1)'s installer?

**Comment by rocknowradio** [comment]
Windows 10 x64 (VM Hypervisor) 

2.37.2.2 Downloaded from releases/download/v2.37.2.windows.2/Git-2.37.2.2-64-bit.exe into Downloads directory. Launched with double-click and use only the default options, Next ... Next Install and finished normally.
2.37.3 Same steps. No error.
2.45.1 Same steps. No error.

Seems a some form of glitch I encountered on my machine (it was running Spy++, antimalware in debug, debug view, 4 visual studio, HyperV-M, TGitCache and opened TGit log windows - a lot of other things not helpful for an installation).

I will try again on a subsequent release, but until then I'm closing this as Cannot reproduce.

**Comment by rocknowradio** [comment]
Cannot reproduce on other machines.
