### ISSUE TITLE
Git for Windows 2.41.1 Release

### ISSUE THREAD

**Issue by danielsiegl** [git-for-windows/git#4965]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Is there a plan to release a Git for Windows 2.41.1 with the latest vulnarability fixes?

**Comment by rimrul** [comment]
Probably not. We have done the occasional `maint` release in the past, but we typically don't. Seeing as Git 2.41.1, Git 2.45.1, Git for Windows 2.45.1 and a few other versions of Git where developed under the same embargo and released at the same time, a Git for Windows 2.41.1 would have probably been released along with them, if we had any plans.

**Comment by dscho** [comment]
> Probably not.

Correct. As per [our security policy](https://github.com/git-for-windows/git?tab=security-ov-file#supported-versions):

> While Git maintains several release trains (when v2.19.1 was released, there were updates to v2.14.x-v2.18.x, too, for example), Git for Windows follows only the latest Git release.

Which means that Git for Windows v2.45.* is the release train we are following.

For technical reasons, there has been a Git for Windows v2.44.1, but that was never marked as the latest release. And there won't be a Git for Windows v2.44.2 even if Git is likely to release such a version.

Please consider asking questions like this in [the discussions](https://github.com/git-for-windows/git/discussions) in the future; I like to keep the bug tracker for bug reports.
