### ISSUE TITLE
Unable to install when shell folder constant localappdata unavailable.

### ISSUE THREAD

**Issue by Walter-Gates-Bose** [git-for-windows/git#4967]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.44.0.windows.1                                                                                            
cpu: x86_64                                                                                                             
built from commit: ad0bbfffa543db6979717be96df630d3e5741331                                                             
sizeof-long: 4                                                                                                          
sizeof-size_t: 8                                                                                                        
shell-path: /bin/sh                                                                                                     
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.20348.2340]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
The following command as part of a Chocolatey install script.

Git-2.44.0-64-bit.exe /VERYSILENT /SUPPRESSMSGBOXES /ALLUSERS /NORESTART /SP- /DIR="C:\Program Files\Git" /COMPONENTS=*ext,gitlfs,assoc,assoc_sh,scalar /LOG="C:\Windows\TEMP\chocolatey\git.2.44.0.20240423.MsiInstall.log"
```

[git.2.44.0.20240423.MsiInstall.log](https://github.com/git-for-windows/git/files/15439803/git.2.44.0.20240423.MsiInstall.log)

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
PS > Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" -Name "Local AppData"
Get-ItemProperty: Property Local AppData does not exist 
```

The machine is an AWS EC2 instance. The user is the default admin user. All tests that the user is in admin mode returned true.

I looked through https://github.com/git-for-windows/build-extra to try to find a reason this could be happening and one set of paths ( [1](https://github.com/git-for-windows/build-extra/blob/34a82b52c89920c425b691e8ae61a8eed47152dd/installer/install.iss#L142) [2](https://github.com/git-for-windows/build-extra/blob/34a82b52c89920c425b691e8ae61a8eed47152dd/installer/install.iss#L286) [3](https://github.com/git-for-windows/build-extra/blob/34a82b52c89920c425b691e8ae61a8eed47152dd/installer/install.iss#L142) ) I found that looked like they might be trying to access the localappdata constant were for the windowsterminal component, so I made sure I was not selecting that component; those code paths also were only looking at localappdata when not in admin install mode so I double checked that my terminal was in admin mode. Another [section](https://github.com/git-for-windows/build-extra/blob/34a82b52c89920c425b691e8ae61a8eed47152dd/installer/helpers.inc.iss#L71) looks to be only call as part of after install [cleanup](https://github.com/git-for-windows/build-extra/blob/34a82b52c89920c425b691e8ae61a8eed47152dd/installer/install.iss#L128) that the log indicates the process never reached.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Git-2.44.0-64-bit.exe /VERYSILENT /SUPPRESSMSGBOXES /ALLUSERS /NORESTART /SP- /DIR="C:\Program Files\Git" /COMPONENTS=*ext,gitlfs,assoc,assoc_sh,scalar /LOG="C:\Windows\TEMP\chocolatey\git.2.44.0.20240423.MsiInstall.log"
```
 - What did you expect to occur after running these commands?

Git installed.

 - What actually happened instead?

Error message.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
I could imagine that it is actually the [`DeleteFromVirtualStore()` function that looks up the path of `LocalAppData`](https://github.com/git-for-windows/build-extra/blob/34a82b52c89920c425b691e8ae61a8eed47152dd/installer/helpers.inc.iss#L71).

Having said that, I think that [InnoSetup assumes that `LocalAppData` is always there](https://jrsoftware.org/ishelp/topic_consts.htm#localappdata), just like I did before this report came in. How can it be missing?

**Comment by dscho** [comment]
Seems like the warning shown in the log is produced by [this code](https://github.com/jrsoftware/issrc/blob/e44a1b94e35697a28c815591d5617847b3ba1828/Projects/Src/Main.pas#L1587-L1588), and the error by [this code](https://github.com/jrsoftware/issrc/blob/e44a1b94e35697a28c815591d5617847b3ba1828/Projects/Src/Main.pas#L1254).

I guess the best course of action would be to report this issue [in the InnoSetup forum](https://groups.google.com/g/innosetup) and hopefully they have a clear idea how to fix it.

**Comment by dscho** [comment]
I'll close this ticket because it is now clear that this is an InnoSetup bug, not a Git for Windows bug, and needs to be addressed there instead.
