### ISSUE TITLE
Can't run Git-2.6.2-64-bit.exe as local user

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#497]
When I run the installer for git 2.6.2: `Git-2.6.2-64-bit.exe` it prompts me for elevated privileges so that I have to install it as an admin user.

This is not the case for `Git-2.6.1-64-bit.exe`.

**Comment by dscho** [comment]
I *guess* the culprit is https://github.com/git-for-windows/build-extra/commit/ec4947544385c555f4b53b6c3a4329a6c7047026

The problem is that http://www.innosetup.org/ishelp/topic_setup_privilegesrequired.htm says that `none` is not even a valid value...

**Comment by dscho** [comment]
I guess http://jrsoftware.github.io/issrc/whatsnew.htm recommends:

> If you were using PrivilegesRequired=none before, it is recommended to switch to PrivilegesRequired=lowest.

Feel free to test the change and open a Pull Request if the test is successful.

**Comment by kjeremy** [comment]
I tested the installer from the above pull request (as my normal user) and everything appears to be working.

**Comment by VictorVG** [comment]
Version 2.5.2 in decompiled Innounp v0.43 script (in the source code installation script, I did not find, so had to read it - suddenly there is a mistake and I can fix it?) In the section [Setup] I see the string * PrivilegesRequired = poweruser *, therefore must be requested privileges Power Users group is lower than the privilege level of the Administrators group, even though the idea to write to the registry key responsible for starting the operating system must have the privileges of the Administrators group as newcomers are able to made a lot of blunders. However, the level of rights of the Power Users group initially above the rights of the Users group and the challenge mechanism Elevation in this case natural.

**Comment by dscho** [comment]
> Version 2.5.2 in decompiled Innounp v0.43 script
> [...]
> 
>```
> [Setup]
> AppName=Git
> AppVersion=2.6.2
>```

Umm. You probably meant "Version 2.6.2". Makes kind of a difference to say "Version 2.5.2" here.

> in the source code installation script, I did not find, so had to read it - suddenly there is a mistake and I can fix it?

EPARSE. Render me confused.

> check the level of privilege and if it is lower than the Administrators group to block any attempt to write to [HKLM] / [HKLM\SOFTWARE\Classes]

We [do](https://github.com/git-for-windows/build-extra/blob/9d623b4900653d11e3b187a414fa9d87e99695be/installer/install.iss#L112) that [already](https://github.com/git-for-windows/build-extra/blob/9d623b4900653d11e3b187a414fa9d87e99695be/installer/install.iss#L115) by [checking whether we're running as an administrator](http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_isadminloggedon).

> It is easy to implement means of NSIS

We use InnoSetup and I see no advantage in spending a lot of time to switch to another installer, just to incur a different set of challenges ;-)

**Comment by VictorVG** [comment]
It is clear, just for myself the past few years I use NSIS (previously, fifteen years ago enjoyed Wise Install Maker, after Inno Setup, and then began to use NSIS, well, got used to it) and brought it as an example of how familiar my instrument. While yes, there I can write a fairly complex logic, but in view of my own habits to remove comments from the code is often easier for me to write all over again than to understand their old code. :)
