### ISSUE TITLE
Adopt Git Extensions as Git GUI replacement

### ISSUE THREAD

**Issue by ismyrnow** [git-for-windows/git#499]
Just wanted to start a conversation about the potential adoption the Git Extensions project as the official Git Gui application. It seems like it's trying to solve the same problems, and has a much nicer GUI. I've been using it for years, and it's very robust and easy to use.

I'm not a maintainer of Git Extensions, but I've supported it financially in the past, and would hate to see that project die off (it has an issue list a mile long) when it seems to be preferable to Git GUI.

**Comment by lawrence-dol** [comment]
I'm an Atlassian SourceTree user myself, and quite like it. However, I just took a look at Git Gui distributed with Git for Windows, and have to say it's truly *awful*. I don't mean to offend anyone, but it's aesthetically and functionally way behind the SourceTree. Just my two cents. If Git Extensions is an improvement, I say go for it.

**Comment by linquize** [comment]
You should install GitExtensions directly (SetupComplete.msi), which bundles Git for Windows.
Rather than include it here.

**Comment by VictorVG** [comment]
I liked more TortoiseGit and I take it as a shell. But why not do both in PC-BSD / TrueOS Server - the core of one FreeBSD UNIX, shell and everyone can choose to suit your needs and taste. What sense to impose all their personal habits? I was completely satisfied with for example the possibility of using universaplnoe instrumental core of the package put together for specific tasks without thinking that someone of my choice colleagues may not like.

I do not impose their views just expressed my opinion and if the maintainer of the project will make changes - will develop new methods of work take account of them, well, old sent to landfill. Honestly after SVN I'm still getting used to very carefully Git, but I hope I'm in the minority.

**Comment by dscho** [comment]
It seems there is enough contention which GUI to use/is better/rocks/sucks that it is safer to keep things as-are than to make *everybody* angry.

**Comment by PhilipOakley** [comment]
Personally, I use the 'git gui' (and 'gitk') as my main visualisation tool. I did try GitExtensions for a while but it felt too much like it was trying to be an old style VCS. I still have it installed and occassionally look at it.. but usually fall back to the bash git-cli [command line interface] for whatever tricky problem I have.

It's a "horses for course" sort of thing. I would not want the 'git gui' dropped. If the GitExtensions was included I wouldn't complain.

In the longer term, once (if) the automated packaging  eventually becomes a reality, then it shouldn't be any problem to have both a minimal G4W package, and a 'Kitchen sink' package (Though I doubt we'll ever reach that tevel of perfection, given the length of the tool chain and the shifting ground of their communities/corporations)

</$0.02>

**Comment by dscho** [comment]
> If the GitExtensions was included I wouldn't complain.

You would not, others would, and I would be stuck with maintaining yet another piece of software ;-)

**Comment by shiftkey** [comment]
:thumbsup: to keeping this simple and based on upstream Git wherever possible.

It's rather easy to extend the Git SDK and build your own flavour of distribution, but that's a story for another day...

**Comment by dscho** [comment]
> It's rather easy to extend the Git SDK and build your own flavour of distribution, but that's a story for another day...

@shiftkey true, I should probably write something up. Or maybe we can do that together? But as you say, another day...

**Comment by shiftkey** [comment]
@dscho you have enough on your plate right now. I'm happy to sketch something out later this week or next week.

**Comment by kostix** [comment]
I'm ambivalent about adding Git Extensions (or whatever) to GfW, but please don't remove the trusty default tools in favour of anything else. `git gui` and `gitk` might look odd to WPF and metro fanboys but they have two killer features: 1) they're well known; 2) they are supported upstream.

The mere fact Pat Thoyts could be asked to help with problems in those tools makes me confident in their good future :-)
(On a side note, I'm rather well versed in Tcl/Tk and might be of help just in case.)

**Comment by linquize** [comment]
Since `gitk`/`git gui` is cross platform, the user experience should be consistent. @kostix mentioned a good point: supported upstream by `git-core`

**Comment by ismyrnow** [comment]
I didn't know that git gui has upstream support or works cross platform.
Very good to know.
