### ISSUE TITLE
Installing wget in git for Windows SDK does not work anymore

### ISSUE THREAD

**Issue by Dirk1966** [git-for-windows/git#4995]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64-bit Git for Windows SDK

```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.45.1.windows.1
cpu: x86_64
built from commit: 965b16798dab6962ada5b0d8cf0dca68f385c448
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.22631.3593] (same behaviour on several Windows 11 and 10 releases)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```
Not applicable, installed git for Windows SDK or updated it with pacman -Suy
Afterwards installed wget with pacman -S wget
wget --version will exit without output with error code 127

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

mc (midnight commander) exits also with error code 127

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Happens in Bash (all terminals) **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
pacman -S wget
$ WGET=$(which wget); echo $WGET --version; $WGET --version || echo $?; echo strace $WGET --version; strace $WGET --ver>
/usr/bin/wget --version
127
strace /usr/bin/wget --version
--- Process 1540 created
--- Process 1540 loaded C:\Windows\System32\ntdll.dll at 00007ffb4f6d0000
--- Process 1540 loaded C:\Windows\System32\kernel32.dll at 00007ffb4eb90000
--- Process 1540 loaded C:\Windows\System32\KernelBase.dll at 00007ffb4cd00000
--- Process 1540 thread 9808 created
--- Process 1540 thread 7192 created
--- Process 1540 thread 10360 created
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-iconv-2.dll at 00000005603f0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-gnutls-30.dll at 0000000400950000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-intl-8.dll at 0000000430b30000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-idn2-0.dll at 0000000522bb0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-psl-5.dll at 00000004a92e0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-2.0.dll at 0000000210040000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-nettle-8.dll at 00000005b89f0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-pcre2-8-0.dll at 00000005d1c20000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-uuid-1.dll at 00000004ba2f0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-z.dll at 0000000522fe0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-gcc_s-seh-1.dll at 00000005e8160000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-gmp-10.dll at 00000005928b0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-unistring-5.dll at 00000004a2860000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-hogweed-6.dll at 00000005665d0000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-unistring-5.dll at 0000000000600000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-p11-kit-0.dll at 00000004dd800000
--- Process 1540 unloaded DLL at 0000000000600000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-tasn1-6.dll at 0000000561390000
--- Process 1540 loaded D:\Prg\git-sdk-64\usr\bin\msys-ffi-8.dll at 00000004a5930000
--- Process 1540 thread 7192 exited with status 0x0
--- Process 1540 thread 10360 exited with status 0x0
--- Process 1540, exception c0000139 at 00007ffb4f7df77d
--- Process 1540 thread 6912 exited with status 0xc0000139
--- Process 1540 exited with status 0xc0000139
```
=>
[wget.exe - Entry Point Not Found]                         [x]
The procedure entry point mbrtoc32 could not be located in the

```
 - What did you expect to occur after running these commands?

** Show version description of wget, error code 0 **

 - What actually happened instead?

** wget stopped without output, error code 127 **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> `pacman -S wget`

The purpose of [Git for Windows](https://git-for-windows.github.io/) is really to bring *Git* to Windows.

While that implies that we have to ship quite a few Unix-like tools, it does not mean that we will include such tools unless they are needed for Git's own operations, or at least for historical reasons (needs of active contributors are sometimes a factor in deciding whether to include a tool or not).

Having said that, what you really are looking for is [MSYS2](https://msys2.github.io/). Git for Windows leverages MSYS2 and ships with a subset of its files. MSYS2 even sports a package management system called "pacman" to install more tools (including Git...), so why don't you give it a whirl?

**Comment by Dirk1966** [comment]
I am using the 64 but version.
I am aware of that the SDK is not meant as msys2 replacement. 
Because wget and mc are currently failing in this way, I just wanted to make aware that.

**Comment by dscho** [comment]
> Because wget and mc are currently failing in this way, I just wanted to make aware that.

@Dirk1966 Thank you for making me aware of that! I'd like to return the favor and make you aware of [this](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper):

> # Please note that this scenario is not officially supported by Git for Windows
> [...]
> This guide assumes you are comfortable using the command line and you are willing to completely re-install your MSYS2 if something goes wrong. You can contact @Elieux for advice in the git-for-windows/git Gitter room or through the contact channels for MSYS2. Please don't file issues with Git for Windows installed this way until you verify them in an official Git for Windows distribution.

I would like to draw your attention in particular to that last sentence.
