### ISSUE TITLE
issue with cd command

### ISSUE THREAD

**Issue by jpmaza** [git-for-windows/git#502]
try cd [some directory] then append a . (dot) || .. (dots)

	cd D:/temp..
	
then try

	pwd
	
and the result will be

	D:/temp..

expected output when cd D:/temp..

	sh.exe": cd: D:/temp..: No such file or directory

notes:
	- i use git-1.9.5-preview20150319.exe
	- D:/temp is a existing folder
	- when trying ls inside D:/temp.. nothing is there

**Comment by hkdennis2k** [comment]
unable to reproduce on git version 2.6.2.windows.1.  Should you update before reporting bug

**Comment by dscho** [comment]
Yes, this bug tracker is only for Git for Windows 2.x. Git for Windows 1.x was retired with the switch to 2.x.

**Comment by jpmaza** [comment]
sorry my bad
