### ISSUE TITLE
can't push to  a usb key (formated as exFat)

### ISSUE THREAD

**Issue by net1957** [git-for-windows/git#5020]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
`git version 2.45.2.windows.1
cpu: x86_64
built from commit: 91d03cb2e4fbf6ad961ace739b8a646868cb154d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon`

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

$ cmd.exe /c ver

** insert your machine's response here **
`Microsoft Windows [version 10.0.19045.4529]`

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
````
Editor Option: Notepad++

Custom Editor Path:

Default Branch Option:

Path Option: Cmd

Plink Path: C:\Program Files\PuTTY\plink.exe

SSH Option: Plink

Tortoise Option: true

CURL Option: OpenSSL

CRLF Option: CRLFAlways

Bash Terminal Option: MinTTY

Git Pull Behavior Option: Rebase

Use Credential Manager: Disabled

Performance Tweaks FSCache: Enabled

Enable Symlinks: Disabled

Enable Pseudo Console Support: Disabled

Enable FSMonitor: Disabled
````

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** I push to a USB key formatted as exFAT. It worked with version 2.44.0.
 if I  apply the given advice to add an exception for this directory, the problem is the same
**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** bash or UI **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

** git push sk-cle **

 - What did you expect to occur after running these commands?

** a successful push **

 - What actually happened instead?

The following message is displayed:

````
Pushing to M:\dvlt\Db_presenter
fatal: detected dubious ownership in repository at 'M:\dvlt\Db_presenter.git'
'M:\dvlt\Db_presenter.git' is on a file system that does not record ownership
To add an exception for this directory, call:

git config --global --add safe.directory 'M:\dvlt\Db_presenter.git'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
This is intentional, as the repository on the USB key could be crafted such that it executes code as part of the push, code that is defined on that drive.

If you are 100% certain that it is safe to push to that key, you need to indicate it e.g. via `git -c safe.directory=\* push /m/dvlt/Db_presenter <branch>`.

**Comment by net1957** [comment]
Thanks for the reply, but this don't change anything.
If I use your example ` git -c safe.directory=\* push sk-cle`
or if I execute `git config --global --add safe.directory 'M:\dvlt\Db_presenter.git'` followed with `git push sk-cle`

the command always fail with the same message

**Comment by dscho** [comment]
> If I use your example ` git -c safe.directory=\* push sk-cle`

Right, I forgot that the config values provided via `-c` do not extend to the `git-receive-pack` sub-process that is spawned from `git push`.

> if I execute `git config --global --add safe.directory 'M:\dvlt\Db_presenter.git'`

In my tests, this failed as long as backslashes were used. As soon as forward slashes were used, it worked as expected. As far as I remember, the error message specifically replaces backslashes with forward slashes, but I might be wrong.
