### ISSUE TITLE
Omit tar.exe when C:\Windows\System32\tar.exe exists

### ISSUE THREAD

**Issue by hickford** [git-for-windows/git#5022]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Windows 10 build 17063 and later include bsdtar at C:\Windows\System32\tar.exe https://ss64.com/nt/tar.html . IMHO this is superior to GNU tar at "C:\Program Files\Git\usr\bin\tar.exe" https://unix.stackexchange.com/a/104035/7732

```
C:\>"C:\Windows\System32\tar.exe" --version
bsdtar 3.6.2 - libarchive 3.6.2 zlib/1.2.5.f-ipp liblzma/5.2.5 bz2lib/1.0.8 libzstd/1.5.4

C:\>"C:\Program Files\Git\usr\bin\tar.exe" --version
tar (GNU tar) 1.35
```

Is it necessary to install C:\Program Files\Git\usr\bin\tar.exe when C:\Windows\System32\tar.exe exists? Could it be omitted?

I use install option "Use Git and optional Unix tools from the Command Prompt" because I prefer Unix tools "find" and "sort", but I prefer Windows "tar".

<img width="375" alt="unix-tools" src="https://github.com/git-for-windows/git/assets/105314/df2438e8-d6ed-4a19-9cc4-0432859056dd">

**Comment by dscho** [comment]
> Windows 10 build 17063 and later include bsdtar at C:\Windows\System32\tar.exe https://ss64.com/nt/tar.html . IMHO this is superior to GNU tar at "C:\Program Files\Git\usr\bin\tar.exe"

Whether or not bsdtar is superior to GNU tar is a highly contentious question, and I am the opposite of eager to take sides.

A question I _am_ eager to take sides, however, is whether or not to break well-established expectations. [Hyrum's law](https://www.hyrumslaw.com/) is a thing, after all, a really big thing. Therefore I tend to err quite clearly on the side of keeping things as-are, unless there are good reasons not to. And in this instance, personal opinions are less likely to convince me.

**Comment by hickford** [comment]
Good point.

**Comment by dscho** [comment]
To give you _a_ workaround: If all you want is to let interactive `tar` invocations default to `bsdtar`, you could set a Bash alias `tar` that points to the one you want to use, in `~/.profile`.
