### ISSUE TITLE
git --literal-pathspecs add -u says "fatal: pathspec ':/' did not match any files"

### ISSUE THREAD

**Issue by npostavs** [git-for-windows/git#504]
```
C:\tmp>c:\Git-2.x\cmd\git.exe init
Initialized empty Git repository in C:/tmp/.git/

C:\tmp>c:\Git-2.x\cmd\git.exe --literal-pathspecs add -u
fatal: pathspec ':/' did not match any files

C:\tmp>c:\Git-2.x\cmd\git.exe --version
git version 2.6.2.windows.1
```

Not sure if it's relevant, but I see the same error using both Cygwin's and MSys2's gits.

It works without error using `git version 1.9.5.msysgit.1`.

**Comment by dscho** [comment]
The same happens when run via [Vagrant](https://github.com/git-for-windows/git/wiki/Vagrant), therefore it is platform-independent. For that reason, please report this [upstream](mailto:git@vger.kernel.org).
