### ISSUE TITLE
`Git` commands return nothing in elevated prompt.

### ISSUE THREAD

**Issue by poa00** [git-for-windows/git#5041]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or <b><ins>64-bit</ins></b>? 

```console
$ git --version --build-options

git version 2.45.2.windows.1
cpu: x86_64
built from commit: 91d03cb2e4fbf6ad961ace739b8a646868cb154d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10, <b><ins>WIN 11 Enterprise</ins></b>? 
  
 - Is it 32-bit or <b><ins>64-bit</ins></b>?

```console
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.3737]
```

 - What options did you set as part of the installation? Or did you choose the
   <b><ins>defaults</b></ins>?
   
```console
# One of the following:
$ type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
> cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

   The issue occurs exclusively when `git` commands are run from an elevated prompt (despite Git for Windows being installed for all users (machine scope) rather than a per-user install).  When run from a standard (non-elevated) PowerShell prompt, `git` functions as expected.  When run from an elevated prompt, a `cmd` console flashes open for a split-second before closing, and the prompt in PowerShell moves down to the next line - no output.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/<b><ins>PowerShell</ins></b>/other

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
$ git -v
```
 - What did you expect to occur after running these commands?

```console
$ git -v
git version 2.45.2.windows.1
```
 - What actually happened instead?

```console
$ git -v
$ 
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

`<none>`

**Comment by dscho** [comment]
I cannot reproduce:

![Image](https://github.com/user-attachments/assets/0c65009d-8f7f-4be4-99a3-fff0160398bd)

I am also on Microsoft Windows [Version 10.0.22631.3737] according to `cmd /c ver`. Maybe you have some sort of anti-malware running that only kicks in in elevated mode?

**Comment by poa00** [comment]
That's very possible.  It is a company machine.  I didn't realize I was due for an upgrade anyway and it's since been replaced.  I appreciate your effort though - thank you.
