### ISSUE TITLE
"git blame -L /regex/"  does not work in git-bash

### ISSUE THREAD

**Issue by elpiekay** [git-for-windows/git#5047]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
#!/bin/bash

# init the test repository
export GIT_AUTHOR_NAME=foo
export GIT_AUTHOR_EMAIL=foo@bar.com
export GIT_AUTHOR_DATE="Mon July 4 10:00:00 2024 +0800"
export GIT_COMMITTER_NAME=foo
export GIT_COMMITTER_EMAIL=foo@bar.com
export GIT_COMMITTER_DATE="Mon July 4 10:00:00 2024 +0800"

rm -rf foo
git init foo
cd foo
touch a.txt
git add a.txt
git commit -mroot
git branch new
echo hello > a.txt
git commit -am'hello'
git switch new
echo world > a.txt
git commit -am'world'
git checkout -
git merge new

# trigger the issue
git blame -L '/<<<<<<</,/>>>>>>>/' a.txt

unset GIT_AUTHOR_NAME
unset GIT_AUTHOR_EMAIL
unset GIT_AUTHOR_DATE
unset GIT_COMMITTER_NAME
unset GIT_COMMITTER_EMAIL
unset GIT_COMMITTER_DATE
```
 - What did you expect to occur after running these commands?
```
00000000 (Not Committed Yet 2024-07-08 09:51:39 +0800 1) <<<<<<< HEAD
fcdd805f (foo               2024-07-04 10:00:00 +0800 2) hello
00000000 (Not Committed Yet 2024-07-08 09:51:39 +0800 3) =======
2dc41277 (foo               2024-07-04 10:00:00 +0800 4) world
00000000 (Not Committed Yet 2024-07-08 09:51:39 +0800 5) >>>>>>> new
```

 - What actually happened instead?

It prints the following line and the exit code is 129.
```
usage: git blame [<options>] [<rev-opts>] [<rev>] [--] <file>
```

I tried the command in 3 forms:
```
git blame -L '/<<<<<<</,/>>>>>>>/' a.txt
git blame -L "/<<<<<<</,/>>>>>>>/" a.txt
git blame -L /<<<<<<</,/>>>>>>>/ a.txt
```
In PowerShell, the command works as expected with single quotes or double quotes or no quotes.

In CMD, the command works as expected with double quotes only.

In Ubuntu shell (git version 2.39.0), the command works as expected with single quotes or double quotes.

In git-bash, the command does not work at all. I expect it to behave the same with it in Ubuntu shell or work with at least one of the 3 forms.

I also tried `git blame -L /hello/ a.txt` and it did not work at all in git-bash.

I tried the local `foo` repository at `/e/foo`, `/e/xxx/foo`, `/c/foo`, `/c/xxx/foo`, and all failed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not with a specific repository.

**Comment by rimrul** [comment]
Looks like you're running afoul of automatic path conversion. 

https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues

**Comment by elpiekay** [comment]
> Looks like you're running afoul of automatic path conversion.
> 
> https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues

Thanks! `MSYS_NO_PATHCONV=1` solves the issue. Doubling the first slash does not in this case.
