### ISSUE TITLE
Please include git-lfs in MinGit

### ISSUE THREAD

**Issue by iahung** [git-for-windows/git#5058]

**Comment by dscho** [comment]
MinGit is _already_ much larger than I would prefer. As of time of writing, the 64-bit version weighs in with 44 megabytes. Compare that to the 21 megabytes it weighed in [v2.9.2](https://github.com/git-for-windows/git/releases/tag/v2.9.2.windows.1)!

Git LFS weighs 11MB, which is a hefty price tag in comparison. I must balance that price against the benefit. And that balance tips against including Git LFS, quite clearly so. Therefore no, I won't include Git LFS in MinGit, you will have to do that yourself if you need it (much like you have to add other 3rd-party components that are not included in MinGit, either).
