### ISSUE TITLE
Stop using display: block for synopsis elements in documentation

### ISSUE THREAD

**Issue by xparadoxical** [git-for-windows/git#5063]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.45.2.windows.1
cpu: x86_64
built from commit: 91d03cb2e4fbf6ad961ace739b8a646868cb154d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.3737]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: SublimeText
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

windows terminal, command prompt in VS

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git <any> --help
```
 - What did you expect to occur after running these commands?

![image](https://github.com/user-attachments/assets/629fc850-d79b-4735-94df-3461fc6d5908)

 - What actually happened instead?

![image](https://github.com/user-attachments/assets/0c6f9e8a-14e6-486d-abd1-c1cc039b4275)
It was changed to look like this recently and it's really hard to read.

**Comment by dscho** [comment]
Oh wow, I can reproduce it, that's terrible! I'm on it.

**Comment by dscho** [comment]
I bisected it down to 76880f0510c6be9f6385f2d43dcfcba4eca9ccbc, i.e. v2.45.0-rc0~42^2~1, so this is a regression in v2.45.0, and it is specific to `git-clone` and it only affects AsciiDoctor-based builds, not AsciiDoc-based ones.

**Comment by dscho** [comment]
Aha! The `display: block` is coming from [here](https://github.com/git-for-windows/git-sdk-64/blob/93d5ec21fc88752d6e0acd2f34759d2d62be29fb/mingw64/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.23/data/stylesheets/asciidoctor-default.css#L109).

**Comment by rimrul** [comment]
> it is specific to `git-clone`

I don't think it is. `git-init.html` looks just as  bad and probably bisects down to https://github.com/git-for-windows/git/commit/5cf7dfe93ed69b2a9c4826c1ee8bf980bd44e66b (i.e. the parent of the commit that you found for `git-clone.html`). There seems to be a small [patch series](https://lore.kernel.org/git/pull.1702.v2.git.1711711181.gitgitgadget@gmail.com/#t).

**Comment by dscho** [comment]
@rimrul could you have a look at https://github.com/git-for-windows/git/pull/5064? I tried to run `/git-artifacts`, forgetting that it wouldn't work because the PR branch is based on that small patch series that broke the rendering.

**Comment by dscho** [comment]
/add relnote bug As of v2.45.0, the manual pages of `git clone` and `git init` [were broken](https://github.com/git-for-windows/git/issues/5063), which has been fixed.

**Comment by dscho** [comment]
And I verified that the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html) fixes this.
