### ISSUE TITLE
Incorrect installation directory for redirectors (e.g. /bin/git.exe) in package mingw-w64-git if cygdrive is not mounted to /

### ISSUE THREAD

**Issue by A2uria** [git-for-windows/git#5067]
## Problem

If cygdrive is mounted to something other than / (e.g. /mnt), upgrading mingw-w64-git using pacman will result in redirectors (e.g. /bin/git.exe) being installed to an incorrect path. (e.g. "C:/Program Files/Git/bin" to "C:/Program Files/Git/C/Program Files/Git/bin")

Note that I'm using the latest Git installer with Git SDK as overlay so pacman is accessible, and I use `none /mnt cygdrive binary,posix=0,noacl,user 0 0` in /etc/fstab for easier interop with wsl.

https://github.com/git-for-windows/MINGW-packages/blob/648d103cf7afec31b17f16c04d1ebf6ed6d4442e/mingw-w64-git/git.install#L7

## Solution

https://cygwin.com/cygwin-ug-net/using.html

> To simplify scripting, Cygwin also provides a /proc/cygdrive symlink, which allows to use a fixed path in scripts, even if the actual cygdrive prefix has been changed, or is different between different users.

https://cygwin.com/cygwin-ug-net/cygpath.html

> The -U option allows to use cygpath to create unambiguous Unix paths pointing outside the Cygwin tree andf thus having no explicit POSIX path. Those paths usually use the cygdrive prefix. However, the cygdrive prefix can be changed by the user, so symbolic links created using the cygdrive prefix are not foolproof. With -U cygpath will generate such paths prepended by the virtual /proc/cygdrive symbolic link, which will never change, so the created path is safe against changing the cygdrive prefix.

```patch
--- a/mingw-w64-git/git.install
+++ b/mingw-w64-git/git.install
@@ -4,7 +4,7 @@
 }

 bin_path () {
-       echo "$(cygpath -am / | sed 's/^\([A-Z]\):/\/\1/')/bin"
+       echo "$(cygpath -am / | sed 's/^\([A-Z]\):/\/proc\/cygdrive\/\1/')/bin"
 }

 copy_files () {
```

This should probably work.

**Comment by dscho** [comment]
> upgrading mingw-w64-git using pacman

Are you using the setup described in https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper? I suspect so, because Git for Windows does not install with `pacman.exe`, for a good reason. As mentioned in that wiki page:

> ## Please note that this scenario is not officially supported by Git for Windows
> [...]
> Please don't file issues with Git for Windows installed this way until you verify them in an official Git for Windows distribution.

Having said that, if you close this ticket and instead open a proper PR at https://github.com/git-for-windows/MINGW-packages (i.e. if you reduce my maintenance burden instead of increasing it), I will gladly review and merge it.

**Comment by A2uria** [comment]
```
$ git --version --build-options
git version 2.46.0.rc1.windows.1
cpu: x86_64
built from commit: e94ef1d9db481244d9e109f6bb8ea014a4f49eb9
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.8.0
OpenSSL: OpenSSL 3.2.2 4 Jun 2024
zlib: 1.3.1
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.22631.3880]
$ cat /etc/install-options.txt
Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
$ ls -l /etc/profile.d/git-sdk.sh
-rw-r--r-- 1 Administrator 197121 11916 Jun 12 22:57 /etc/profile.d/git-sdk.sh
$ which pacman
/usr/bin/pacman
```

Actually it's Git for Windows + Git SDK, not MSYS2. So this issue may occur to others with pacman bootstraped and /etc/fstab modified.

Nevermind, I'll create a pr.
