### ISSUE TITLE
git pull failed

### ISSUE THREAD

**Issue by renzfan** [git-for-windows/git#5069]
git -c credential.helper= -c core.quotepath=false -c log.showSignature=false pull --no-stat -v --progress origin main
warning: failed to restrict file handles (5)
handle #0: 0000000000000124 (type 3, handle info (1) 0
handle #1: 0000000000000128 (type 3, handle info (1) 1
handle #2: 0000000000004750 (type 3, handle info (1) 1
This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new
To suppress this warning, please set the environment variable
	SUPPRESS_HANDLE_INHERITANCE_WARNING=1

**Comment by renzfan** [comment]
when I pull code from origin, it shows failed. details showed on up.

**Comment by dscho** [comment]
Please upgrade Git for Windows.
