### ISSUE TITLE
sshd.exe does not install

### ISSUE THREAD

**Issue by hidromagnetismo** [git-for-windows/git#5094]
This Windows v2.46.0 version does not install the sshd.exe binary that raises the ssh service.

**Comment by rimrul** [comment]
Yes. (See https://github.com/git-for-windows/build-extra/pull/571)

**Comment by dscho** [comment]
The purpose of [Git for Windows](https://git-for-windows.github.io/) is really to bring *Git* to Windows.

While that implies that we have to ship quite a few Unix-like tools, it does not mean that we will include such tools unless they are needed for Git's own operations, or at least for historical reasons (needs of active contributors are sometimes a factor in deciding whether to include a tool or not).

Having said that, what you really are looking for is [MSYS2](https://msys2.github.io/). Git for Windows leverages MSYS2 and ships with a subset of its files. MSYS2 even sports a package management system called "pacman" to install more tools (including Git...), so why don't you give it a whirl?
