### ISSUE TITLE
File changes lost after merging branch back to its parent branch, despite file not getting touched on parent branch in the meantime?

### ISSUE THREAD

**Issue by Noshire** [git-for-windows/git#5098]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.45.2.windows.1
cpu: x86_64
built from commit: 91d03cb2e4fbf6ad961ace739b8a646868cb154d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.3880]
(c) Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I am using Fork as my git client, but we managed to reproduce the exact same issue via commandline git and visual studio as a client.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Issue tested on Fork (visual git client), Visual Studio (visual git client), and commandline (MINGW64 installed through Fork)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git-merge
```
 - What did you expect to occur after running these commands?

I forked a new branch `branch_b` from branch `branch_a`. After some commits, I merged `branch_b` into `branch_a`.
I expected all changes to get merged, in context and scope of the usual merge logic. Most notably: If a commit on branch `branch_b` adds lines of code to file `foo.txt`, and no commits on `branch_a` after branching off `branch_b` ever touch `foo.txt`, I expect branch `branch_a` to contain these added lines of code after merging `branch_b` into `branch_a`.

 - What actually happened instead?

While most changes got merged correctly, the changesets of two commits on "B" got completely ignored, as if the commits never happened.

If I open the current state of file `foo.txt` after the merge, I see that the lines are not present in it.
If I open the git history of file `foo.txt`, I can see that the latest commit in the history **did** add these lines.

I tried to dig a bit deeper. Here's some facts that I was able to verify, with the proper commits (authors and commit messages and filenames have been anonymized):

* current HEAD (right after merging the two branches) is `dcc40a6`
* the commit where the line (`public bool CanPlantOnPoisonedFields`) was added is `2f7f05d`:
```
$ git show 2f7f05d -- Foo.cs
commit 2f7f05d0c118be69abf3431a955725d92de03f38
Author: AAA <aaa@aaa.com>
Date:   Fri Aug 2 10:57:52 2024 +0200

    redacted commit message

diff --git a/Foo.cs b/Foo.cs
index 66764254d..79f9a0bd9 100644
--- a/Foo.cs
+++ b/Foo.cs
@@ -295,6 +295,7 @@ public struct PlantReproducibleSettings
 public struct PlantPlantableSettings
 {
     public float PlantDuration;
+    public bool CanPlantOnPoisonedFields;
 }

 [Serializable]
```
* I verified that `2f7f05d ` is an ancestor of `dcc40a6`:
```
$ git merge-base --is-ancestor 2f7f05d dcc40a6; echo $?
0
```
* I verified that, despite what I want, the line `public bool CanPlantOnPoisonedFields` is not present on `dcc40a6`:
```
$ git show dcc40a6:"Foo.cs"| sed -n '295,298p'
public struct PlantPlantableSettings
{
    public float PlantDuration;
}
```
* the line was apparently removed between `2f7f05d` and `dcc40a6`:
```
$ git diff 2f7f05d dcc40a6 -- Foo.cs
diff --git a/Foo.cs b/Foo.cs
index 79f9a0bd9..66764254d 100644
--- a/Foo.cs
+++ b/Foo.cs
@@ -295,7 +295,6 @@ public struct PlantReproducibleSettings
 public struct PlantPlantableSettings
 {
     public float PlantDuration;
-    public bool CanPlantOnPoisonedFields;
 }

 [Serializable]
```
* if I try to find out in which commit the line was removed, I don't get any results:
```
$ git log -p 2f7f05d..dcc40a6 -- Foo.cs
$
```
* I suspected that the merge commit might be responsible, but I don't get anything:
```
$ git show dcc40a6 -- Foo.cs
$
```
* I also re-did the merge and observed the console output, but the file in question, `Foo.cs`, neither appears in any `Auto-merging` line, nor is it part of a `CONFLICT`. It is completely untouched by the merge.

This leaves me in the current situation.
I have opened a branch, changed a file there (that wasn't touched since on the parent branch), then merged the branch back. The change to the file is not reflected after the merge. I see when the desired change was made, but I don't see anything in the history showing where the change got reverted. I'm at a loss.

I know this would all be more helpful with a minimal repro-case or access to the repository - but I didn't manage to reproduce it in a clean minimal environment yet, and the repository is private. I'll keep trying to establish a good repro-case and will do what I can to help and provide more info. Similar cases happened around 4-5 times during the last year already, and we're really unsure what could be causing them. We don't know if it is some specific intended git behaviour that we can't understand, or an actual git bug, or human error (we checked that all our machines create sensible timestamps etc., but maybe we overlooked something?).

I appreciate any help or pointers. Thanks for reading!

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I'm afraid I can't, since this is a private repository.

**Comment by Noshire** [comment]
I dug a bit deeper, and I think I managed to trace this down to human error.

I noticed that one of the branches contained a strange merge commit without any file changes by another team member:
```
$ git show ae4d53c
commit ae4d53c1fd4741f9d18d17c3627bd7dfc02e2f1b
Merge: a80b555ae aa5371aac
Author: BBB <bbb@bbb.com>
Date:   Tue Aug 6 10:51:34 2024 +0200

    Merge branch 'parent_branch' of https://bitbucket.org/therepository into parent_branch

    # Conflicts:
    #       SomeUnrelatedFile.png
```

I then checked back with the team member, and found out that they resolved the conflict and **discarded all changes** (including everything in the actual merge) before committing. This includes my changes to `Foo.cs` that were made in a commit in one of the ancestors leading up to this faulty merge.

I'm pretty sure this is the human error that caused the misbehaviour.

Just leaving this here for anyone else who may stumble upon such a case, and to get confirmation that this would indeed be a valid cause for the symptoms we've experienced.

The remaining question is how to best resolve this situation.

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
