### ISSUE TITLE
./objects/pack: Function not implemented

### ISSUE THREAD

**Issue by honik6** [git-for-windows/git#510]
Hello, I constantly get the following errors when using the Git-2.6.2-64-bit (mingw64) on my win10 64bit if my repository is on the AFS filesystem. The error messages are in many git commands (see also below): 

error: unable to open object pack directory: ./objects/pack: Function not implemented

Fortunately the commands otherwise work fine, so these messages seem to be more warnings than errors, but I would like to avoid future conflicts if I have larger repositories. 
Below is the minimal working example how to reproduce the errors. It seems that the problem is caused only if the repository is on the network drive (OpenAFS, in the example S:),
if I create a repository on the local drive (D:), I do not get the errors at all. Is there a problem with repositories on shared network drives?

$ git --version
git version 2.6.2.windows.1

# create repository on the network drive (OpenAFS, S:)
$ mkdir -p /s/git/example.git 
$ cd /s/git/example.git
$ git init --bare
Initialized empty Git repository in S:/git/example.git/

# create repository on the local drive (D:)
$ mkdir -p /d/git/example.git 
$ cd /d/git/example.git
$ git init --bare
Initialized empty Git repository in D:/git/example.git/

# prepare a workspace
$ mkdir -p /d/workspace/example
$ cd /d/workspace/example
$ echo hello > README.txt
$ git init
Initialized empty Git repository in D:/workspace/example/.git/
$ git add README.txt
$ git commit -m "hello" README.txt
[master (root-commit) 9e7a941] hello
 1 file changed, 1 insertion(+)
 create mode 100644 README.txt

# work with two identical workspaces:
$ cd /d/workspace
$ cp -r example example1
$ cp -r example example2

# attach example 1 to the network drive repsitory
$ cd /d/workspace/example1
$ git remote add origin /s/git/example.git
$ git remote -v
origin  S:/git/example.git (fetch)
origin  S:/git/example.git (push)
$ git push --set-upstream origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 226 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: error: unable to open object pack directory: ./objects/pack: Function not implemented
error: unable to open object pack directory: ./objects/pack: Function not implemented
error: unable to open object pack directory: ./objects/pack: Function not implemented
error: unable to open object pack directory: ./objects/pack: Function not implemented
To S:/git/example.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ git pull
error: unable to open object pack directory: ./objects/pack: Function not implemented
Already up-to-date.

# attach example 2 to the local drive repsitory
$ cd /d/workspace/example2
$ git remote add origin /d/git/example.git
$ git remote -v
origin  D:/git/example.git (fetch)
origin  D:/git/example.git (push)
$ git push --set-upstream origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 226 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To D:/git/example.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ git pull
Already up-to-date.

What is the difference? Is there a problem with having shared repository on AFS filesystem? How to avoid this behaviour? From other OS (linux, macosx) I do not get this error when working with the same repository on the AFS, so I think that there is a problem with the windows version. 

Thank you very much for your help in advance.

Kind regards
Jan

**Comment by dscho** [comment]
You probably cannot come up with a way to reproduce this without a full-fledged OpenAFS setup, eh?

**Comment by honik6** [comment]
All right, I tried other network drives, for example samba shares, NFS, windows network, and they all work fine, like the local drive (D:) above. As for the OpenAFS, if I work with the repository on AFS filesystem in other OSes (Linux Debian, Mac OSX, ...) they are fully operational without any error. The only troublemaker is the windows client as described above. So the answer to your question is no, I do not know how to reproduce the error without OpenAFS. 

If you tell me how could I debug the above git session to understand in more details why this error occurs, I can try to provide more details. 

BTW, what does the source code tells? When an error message 
error: unable to open object pack directory: ./objects/pack: Function not implemented
can happen?

For example git gc does not return the above error, so I think that git can access the object pack directory without problems. Or shall it access rather .git/objects/pack? In other words is the above error message correct? It definitely is not very informative.

Thank you for your help.
Jan

**Comment by remcoros** [comment]
I'm no expert here, but "Function not implemented" seems to be an error from AFS, not git.

Especially since the problem occurs only on windows, it might be an issue with afs on windows.

**Comment by tboegi** [comment]
you can rebuild Git ?
Have a look at

compat/mingw.c
int err_win_to_posix(DWORD winerr)
{
	int error = ENOSYS;
	switch(winerr) {
...

===============
It seems that there is an error code returned from Windows calling opendir(), 
that is translated into ENOSYS, 
which is printed as  "Function not implemented".
(I may be wrong here, I don't have AFS)

Could it be possible to add a printf() printing the DWORD winerr ?

**Comment by jaltman** [comment]
Function not implemented will be from msys or cygwin, not from AFS

**Comment by dscho** [comment]
> Function not implemented will be from msys or cygwin, not from AFS.

No, it won't, because the `error:` line comes from Git's own C code, which is *never* linked to MSys2 or Cygwin.

> If you tell me how could I debug the above git session to understand in more details why this error occurs, I can try to provide more details.

@honik6 could you have a look at https://github.com/git-for-windows/git/wiki/Debugging-Git? If there are any questions left, please let us know.

**Comment by honik6** [comment]
All right. I tried stracent, but probably I do not know how to use it:

$ stracent git pull
Error: The request is not supported.
Do I need to put something special into stFilter.txt?
 
I also could not read anything from procmon, the only interesting lines are probably
git.exe QueryDirectory ...\.git\objects\pack NO MORE FILES
git.exe CreateFile ...\.git\packed-refs NAME NOT FOUND
But I could not find any error similar to the studied error.

Finally I upgraded the openafs-client to 1.7.3301 and the error completely disappeared
in all workspaces/repositories. I am happy that the upgrade solved this issue, although it is not quite obvious what changes in the latest openafs-client release were involved.

Anyway, thank you all for your suggestions and help.

**Comment by buecklers** [comment]
Had the same issue and after upgrading the openafs-client to 1.7.3301, I have a new problem that happens already when I try to commit:

`error: Couldn't set refs/Heads/master
fatal: cannot update HEAD ref`


I have a HEAD fiel in .git, I can delete it, create it again, The problem still exists.

Any suggestions how I could solve this?

**Comment by dscho** [comment]
@buecklers I can only point you to https://github.com/git-for-windows/git/wiki/Debugging-Git because I cannot help more actively with this issue.

**Comment by jaltman** [comment]
@buecklers From the AFS side please use the SysInternals Process Monitor tool to trace the git.exe or sh.exe process that is failing and identify the specific file system level operation that is failing.
