### ISSUE TITLE
git format parameter not creating newlines ( %rr is broken )

### ISSUE THREAD

**Issue by kphillisjr** [git-for-windows/git#512]
I was needing to change how some logs printed and noticed that the newline argument is not working. This is honestly should be fairly quick to fix seeing as how it effects the --format parameter mainly.

Example usage of this parameter:
```
git log --format="I am a Custom Format Message%rr that has two lines."
```
Current output:
```
WARNING: terminal is not fully functional
I am a Custom Format Message%rr that has two lines.
I am a Custom Format Message%rr that has two lines.

```

Expected Output:
```
WARNING: terminal is not fully functional
I am a Custom Format Message
 that has two lines.
I am a Custom Format Message
 that has two lines.

```

**Comment by dscho** [comment]
`%r` is not listed as a valid interpolation at http://git-scm.com/docs/pretty-formats because it is not supported. So this is not a bug, but an incorrect usage. You might want to use `%n` instead.
