### ISSUE TITLE
Portable archive for "immutable" use

### ISSUE THREAD

**Issue by bastianeicher** [git-for-windows/git#513]
Hi all,

I'm a dev working on [Zero Install](http://0install.de/), a cross-platform package manager. It "installs" packages by downloading unmodified upstream archives and extracting them to directories named for the cryptographic hash of their contents. This makes side-by-side installs easy but also requires installed apps to be immutable.

I previously [packaged](http://0install.de/feeds/msysgit.xml) the portable 7z version of Msysgit. When updating to the current Git for Windows releases I noticed the `/etc/post-install` scripts. Unfortunately they don't mesh well with Zero Install's approach of "extract the archive and then immediately lock down the directory".

As far as I understand it, the main job of these scripts is to create [Cygwin-style symlinks](http://cygwin.com/cygwin-ug-net/using.html#pathnames-symlinks) which cannot be expressed in a 7z archive. Zero Install has special-case handling for symlinks in ZIP and TAR archives: they are extracted as "real" symlinks on Unixoid systems and as Cygwin-style symlinks on Windows.

I was wondering whether you would be open to extending your release process to include a "zero-installable" .tar.bz2 archive. Basically this would entail running the `/etc/post-install` scripts and then executing a Zero Install helper tool that creates a suitable .tar.bz2 preserving the symlinks. I'd be happy to take care of any scripting required.

Regards
Bastian

**Comment by dscho** [comment]
Sure! Have a look at the script I use to make the portable installers: https://github.com/git-for-windows/build-extra/blob/master/portable/release.sh

But it might be easier to just unpack the `.7z`, run the `post-install.bat` and then pack the result using `tar`, no?

**Comment by alexkrauss** [comment]
+1. A plain tarball would be suitable for all kinds of unattended install scenarios.

**Comment by bastianeicher** [comment]
@dscho: You are right, simply capturing the directory using a Mingw/Cygwin `tar` would be the most straightforward approach. :) I'll give adjusting the `release.sh` a go and create a pull request some time this week.

**Comment by bastianeicher** [comment]
Resolved by git-for-windows/build-extra#89
