### ISSUE TITLE
windows installer should recommend to not touch files

### ISSUE THREAD

**Issue by soloturn** [git-for-windows/git#5130]
currently installer recommends "core.autocrlf true" for windows development, and "core.autocrfl=input" for mixed projects. both settings are with trouble in daily life, as developers do not really expect that git tinkers with line endings. in linux/windows mixed project this setting should be "core.autocrlf false" so the files stay as they are, untouched.  there is one place where linux default should be set: the editor.  or, editorconfig.

**Comment by dscho** [comment]
> developers do not really expect that git tinkers with line endings.

It depends how you interpret "tinkers with". Developers on Windows do not expect the CR/LF line endings that many editors and IDEs still write on this operating system to be changed by Git. Git, on the other hand, does not expect any line endings other than LF-only ones in the Git object database (being quite firmly rooted in the Linux world, this bias should be less than surprising). This is a friction point that cannot just be configured away with one global config setting.

Back to the suggestion: At this stage, the default of `core.autoCRLF=true` cannot be changed, seeing as many a tutorial on the internet relies on it. Trying to change it after well over a decade of people coming to rely on it is a non-starter.

Do note, though, that `core.autoCRLF` is nowadays considered the wrong thing to focus on. The current wisdom is to [configure your Git attributes correctly](https://www.edwardthomson.com/blog/git_for_windows_line_endings.html).

If you want to propose better [wording of the description](https://github.com/git-for-windows/build-extra/blob/a6f5e16f48f922c4a8e88783d5dd58c46051d17a/installer/install.iss#L2309-L2322) in the installer, feel free to open a PullRequest.

In anticipation of such a PullRequest, I will close this here ticket.
