### ISSUE TITLE
Bug: Can't prevent shell expansion of globs

### ISSUE THREAD

**Issue by nzakas** [git-for-windows/git#5131]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.46.0.windows.1
cpu: x86_64
built from commit: 2e6a859ffc0471f60f79c1256f766042b0d5d17d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.9.0
OpenSSL: OpenSSL 3.2.2 4 Jun 2024        
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4780]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

The defaults.

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
node example.js "**/*.js"
```
 - What did you expect to occur after running these commands?

That I could access the string `"**/*.js"` from my program.

 - What actually happened instead?

I received `"'**C:/Program Files/Git/*.js'", which is useless to me.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

You can reproduce this using any Node.js version. Copy this into a file named `example.js`:

```js
console.log(process.argv[2]);
```
Then run `node example.js "**/*.js"` or `node example.js '**/*.js'`.

**Comment by rimrul** [comment]
This isn't globbing, this is path conversion. Run `MSYS_NO_PATHCONV=1 node example.js "**/*.js" instead.

**Comment by nzakas** [comment]
That works for my simple example, but in this case, I discovered this behavior while working on ESLint. We can't expect everyone using ESLint in a Git Bash console to set an environment variable. Is there a reason this is the default behavior?

**Comment by dscho** [comment]
> Is there a reason this is the default behavior?

Yes. Most people invoking non-MSYS programs from Git Bash _want_ those Unix-y paths to be resolved to Windows ones. Find more information [here](https://www.msys2.org/docs/filesystem-paths/).

**Comment by nzakas** [comment]
Oh yeah, I get that. I guess I'm just wondering why *quoted* patterns are expanded. I can understand why unquoted ones would be, but doesn't quoting those patterns imply that the user wants to pass the literal value?

**Comment by dscho** [comment]
> doesn't quoting those patterns imply that the user wants to pass the literal value?

Not if you consider absolute paths that contain spaces. Think, for example, `/home/Nicholas Zakas/bin`. That _has_ to be quoted. Yet that quoting indicates not at all that it should remain in its Unix-y form when passed as command-line argument to a Win32 program.

**Comment by rimrul** [comment]
> > doesn't quoting those patterns imply that the user wants to pass the literal value?
> 
> Not if you consider absolute paths that contain spaces. Think, for example, `/home/Nicholas Zakas/bin`. That _has_ to be quoted. Yet that quoting indicates not at all that it should remain in its Unix-y form when passed as command-line argument to a Win32 program.

Doesn't bash also accept  escaping in the form of `/home/Nicholas\ Zakas/bin`?

**Comment by dscho** [comment]
> > > doesn't quoting those patterns imply that the user wants to pass the literal value?
> > 
> > 
> > Not if you consider absolute paths that contain spaces. Think, for example, `/home/Nicholas Zakas/bin`. That _has_ to be quoted. Yet that quoting indicates not at all that it should remain in its Unix-y form when passed as command-line argument to a Win32 program.
> 
> Doesn't bash also accept escaping in the form of `/home/Nicholas\ Zakas/bin`?

True. In this instance, you found an alternative. But the quoted form is as legitimate (and much more legible).

When you think about paths stored in environment variables, it gets much less "work-aroundable". Think about `"$HOME/bin/*"`, for example.

**Comment by nzakas** [comment]
Ah gotcha. I suppose the spaces in paths really does make things more complicated. Thanks for the explanation.
