### ISSUE TITLE
`git show` can't work with dotfiles under gitbash

### ISSUE THREAD

**Issue by Greewil** [git-for-windows/git#5139]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.46.0.windows.1
cpu: x86_64
built from commit: 2e6a859ffc0471f60f79c1256f766042b0d5d17d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.9.0
OpenSSL: OpenSSL 3.2.2 4 Jun 2024
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.4037]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash (under CMD and PowerShell works fine)
```
$ bash --version
GNU bash, version 5.2.26(1)-release (x86_64-pc-msys)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git show origin/main:.gitignore
```
 - What did you expect to occur after running these commands?

to show .gitignore file from origin/main

 - What actually happened instead?

```
fatal: ambiguous argument 'origin\main;.gitignore': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
So ':.' had been automatically replaced with ';.' and revision syntax became incorrect.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Problem occurring with any repository.
F.e. with https://github.com/git-for-windows

**Comment by dscho** [comment]
> ```
> git show origin/main:.gitignore
>
> fatal: ambiguous argument 'origin\main;.gitignore': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> ```

This is an unfortunate interaction of [MSYS2's automatic path conversion](https://www.msys2.org/docs/filesystem-paths/#automatic-unix-windows-path-conversion) from Unix-y paths (and path lists) to Windows ones.

In this instance, MSYS2 mistakes `origin/main:.gitignore` for a path list (think `PATH`, i.e. a colon-separated list of paths on Unix, a semicolon-separated one on Windows), and does its best to convert it to Windows format.

The easiest way to avoid this is to prefix `.gitignore` by a `./`, i.e.

```
git show origin/main:./.gitignore
```

Another way out is mentioned in our [Release Notes' "Known Issues" section](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:
>
>  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`

**Comment by Greewil** [comment]
Thanks for answer!

I didn't want to turn off path conversions totally, because seems like it still could be helpful. Conversions just not working intuitively enough for me in this case.
Don't actually understand why MSYS2 doesn't also think that `origin/main:./.gitignore` is a path list (as in case without prefix). But prefix `./` seems like working solution for me, thanks!
