### ISSUE TITLE
chmod permissions not being retained

### ISSUE THREAD

**Issue by archenovalis** [git-for-windows/git#5144]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.46.0.windows.1
cpu: x86_64
built from commit: 2e6a859ffc0471f60f79c1256f766042b0d5d17d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.9.0
OpenSSL: OpenSSL 3.2.2 4 Jun 2024
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4894]
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

"Open Git Bash here"

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
chmod -c 777 file
python -m zipfile -c test.zip file
zipinfo test.zip
```
 - What did you expect to occur after running these commands?

permissions set and retained

 - What actually happened instead?

permissions were not retained. this was working until a week or so ago. i was using 2.43 but the issue persisted after upgrading to 2.46
![image](https://github.com/user-attachments/assets/c6b0e80f-bf4c-45d2-9c04-99f30a3d99b1)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by dscho** [comment]
This is sadly nothing we can change because Windows' permission system is so vastly different from Unix' simplistic permission model (and honestly, Windows' ACLs are _quite_ a bit more powerful).

In any case, this feature would have to be addressed by the Cygwin project, because the underlying POSIX emulation layer is implemented in the Cygwin runtime (which Git for Windows uses in the form of the MSYS2 runtime).

If you want to report this with the Cygwin project, please use [this link](https://cygwin.com/problems.html).
