### ISSUE TITLE
Git GUI / Gitk 2.6.1 : Stage Lines fails with patch error when byte 0xA9 is in file

### ISSUE THREAD

**Issue by clone** [git-for-windows/git#515]
I tried to stage lines from within the Git GUI / Gitk tool in a particular file.
I got a strange patch error, and staging lines was impossible.
Just committing the file worked fine.
When examing the file, it contained a 0xA9 byte (copyright symbol).
When I removed that, and tried again, I could stage lines without any errors.

**Comment by dscho** [comment]
As far as I can tell, `0xa9` refers to the copyright symbol only in ISO-8859-1 and ISO-8859-15. That is a very narrow, biased view on things, yet still legitimate. Legitimate if you tell Git (GUI) that your expected encoding is ISO-8859-1 (the standard these days is *not* ISO-8859-1 but UTF-8).

I suspect that this encoding has not been set. See e.g. `gui.encoding` in http://git-scm.com/docs/git-config.

Further, I suspect that this problem is not even specific to Windows, so it should be reported to [the Git mailing list](mailto:git@vger.kernel.org) instead.

And lastly, it is *so* much easier to help when being provided with a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve). Therefore I would *highly* recommend coming up with such an example.

**Comment by clone** [comment]
> As far as I can tell, |0xa9| refers to the copyright symbol only in ISO-8859-1 and ISO-8859-15. That is a very narrow, biased view on things, yet still legitimate. Legitimate if you tell Git (GUI) that your expected encoding is ISO-8859-1 (the standard these days is /not/ ISO-8859-1 but UTF-8).

Sure it's a narrow view, that's how the target application wants to interpret this file. I understand your remark, but it is not directly related to the reported problem.
 
> I suspect that this encoding has not been set. See e.g. |gui.encoding| in http://git-scm.com/docs/git-config.

gui.encoding=utf-8

This is what I usually use. In this case, (only) this file MUST use ISO-8859-1. Even so, the GUI does show a copyright symbol. Furthermore, as I understand it, GUI encodings are about interpreting the symbols by the GUI. I don't mind if it would have been rendered incorrectly, but I do mind that I cannot use 'stage lines'. And the error is not reported by the GUI, but by the patch tool(?).

> Further, I suspect that this problem is not even specific to Windows, so it should be reported to the Git mailing list <mailto:git@vger.kernel.org> instead.

Might be, but I can only report the issue I see, I don't know what its cause is.

> And lastly, it is /so/ much easier to help when being provided with a Minimal, Complete & Verifiable Example <http://stackoverflow.com/help/mcve>. Therefore I would /highly/ recommend coming up with such an example.

The provided link points to creating a CVE for code. My report is not about code.
I clearly gave the steps to reproduce the problem on my side.
If you need extra information I will be glad to help out.

As extra information, I created a new archive, added an innocent file, committed.
Then added 1 0xA9 character. Git diff from the command-line shows

    test ISO-8859-1 characters.
    +<A9>

so no problem there.
Git GUI shows a copyright symbol in green (=added), so no problem either.
If I do a 'stage line' on that, I get

    'fatal: corrupt patch at line 5'

A slightly different error message from the one I saw earlier, but still 'stage line' fails.
Git add and commit succeeds.
Adding another line, git diff

    test ISO-8859-1 characters.
    -<A9>
    \ No newline at end of file
    +<A9>
    +test ISO-8859-1 characters.
    \ No newline at end of file

No problem again. A similar view is shown in Git GUI, but with a copyright symbol.
If I 'stage line' on the last line only, I again get an error message

    error: patch failed t:1
    error: t: patch does not apply

Which was the same as the error message I saw from my initial description.

So it seems my description on how to reproduce it, was quite to the point.
Hope this helps to find and solve the issue.

Thanks!

**Comment by dscho** [comment]
> So it seems my description on how to reproduce it, was quite to the point.

I will bite the bullet and try to reproduce here. For future record: I can work quicker on any bug when there is a repository that I can clone readily, and that has the minimal set of files/revisions to reproduce the problem.

**Comment by dscho** [comment]
Note that the 0xA9 was a red herring. The bug happened with any string on the second line. Read: it should not have been a part of a *Minimal*, Complete & Verifiable Example.

**Comment by clone** [comment]
My original example had multiple lines to be staged. When it contained 0xA9 it would not stage, when I removed it, it would. Did not seem like a red herring to me.

**Comment by dscho** [comment]
> My original example had multiple lines to be staged. When it contained 0xA9 it would not stage, when I removed it, it would. Did not seem like a red herring to me.

Well, when I tried to reproduce, it turned out that it *was* a red herring. So maybe you did not try to reduce the problematic condition hard enough?
