### ISSUE TITLE
git pull error after upgrade to 2.46.1

### ISSUE THREAD

**Issue by wendal** [git-for-windows/git#5156]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.46.1.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.22631.4169]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

nothing

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

vscode

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```
 - What did you expect to occur after running these commands?

pull ok

 - What actually happened instead?

```
2024-09-18 21:11:10.118 [info] > git fetch [83ms]
2024-09-18 21:11:10.118 [info] hint: core.useBuiltinFSMonitor=true is deprecated;please set core.fsmonitor=true instead
hint: Disable this message with "git config advice.useCoreFSMonitorConfig false"
/c/Users/Administrator/.ssh/config line 1: Bad key types 'ssh-dss,ssh-rsa'.
/c/Users/Administrator/.ssh/config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no

head of my config file

```
PubkeyAcceptedKeyTypes ssh-dss,ssh-rsa
#Host github.com
#  ProxyCommand=nc -X 5 -x 127.0.0.1:1080 %h %p
Host air32.cn
  HostName air32.cn
  User root
```

--------------------------------------------

downgrade to 2.44.1, it works.

**Comment by wendal** [comment]
just remov `ssh-dss,`, it fixed

**Comment by dscho** [comment]
> /c/Users/Administrator/.ssh/config line 1: Bad key types 'ssh-dss,ssh-rsa'.

I suspect that you upgraded from Git for Windows v2.45.2, not from v2.46.0? If so, this is expected. As per OpenSSH's [release notes](https://www.openssh.com/releasenotes.html#9.8p1):

> Future deprecation notice
> =========================
>
> OpenSSH plans to remove support for the DSA signature algorithm in
> early 2025. This release disables DSA by default at compile time.
>
> DSA, as specified in the SSHv2 protocol, is inherently weak - being
> limited to a 160 bit private key and use of the SHA1 digest. Its
> estimated security level is only 80 bits symmetric equivalent.
>
> OpenSSH has disabled DSA keys by default since 2015 but has retained
> run-time optional support for them. DSA was the only mandatory-to-
> implement algorithm in the SSHv2 RFCs, mostly because alternative
> algorithms were encumbered by patents when the SSHv2 protocol was
> specified.
>
> This has not been the case for decades at this point and better
> algorithms are well supported by all actively-maintained SSH
> implementations. We do not consider the costs of maintaining DSA
> in OpenSSH to be justified and hope that removing it from OpenSSH
> can accelerate its wider deprecation in supporting cryptography
> libraries.
>
> This release, and its deactivation of DSA by default at compile-time,
> marks the second step in our timeline to finally deprecate DSA. The
> final step of removing DSA support entirely is planned for the first
> OpenSSH release of 2025.

In short, your local configuration has not kept up with the times, and for security reasons, the feature your local configuration asks for is no longer supported.

Since you already fixed your config, I will close this ticket.

Note that you also have another deprecated config setting, the `useBuiltinFSMonitor` one. You may want to fix that one, too.
