### ISSUE TITLE
Stuck on post-install script

### ISSUE THREAD

**Issue by MattBDev** [git-for-windows/git#5158]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

2.46.1.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.4169]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I have previously uninstalled Git before and attempted to reinstall it. Each time I try to reinstall or upgrade git constantly gets stuck in Git Setup on "Running post-install script"

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell via Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I double clicked the .exe file and used the setup as expected. I didn't change anything weird. 

 - What did you expect to occur after running these commands?

The post-install script would finish running and continue to finish installing. 

 - What actually happened instead?

I am stuck on the "Running post-install script." screen. 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not applicable.

**Comment by MattBDev** [comment]
I just resolved it by removing all git directories that were left over and moving Git to my C:/ drive instead of my external drive.

**Comment by wencan** [comment]
@MattBDev 
I use bottles to install git for windows.
I created a clean environment.
According to the suggestion above, I copied the installation package to the C drive and then executed the installation package through the installer in the control panel.
Unfortunately, the installer is still stuck at the post-install stage
