### ISSUE TITLE
Empty folder not commit ti github

### ISSUE THREAD

**Issue by riteshe63** [git-for-windows/git#516]
I am create new repo and commit a some file and folder but file is committed and folder is not committed
It's a public repo

**Comment by yaras** [comment]
Git does not version folders, only files.

**Comment by Radrik5** [comment]
See http://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository

**Comment by dscho** [comment]
If you want to ignore empty directories, the canonical way is to commit an empty `.gitignore` file in that directory.

In any case, this question would be more appropriate [upstream](mailto:git@vger.kernel.org) because it is not at all specific to Windows.
