### ISSUE TITLE
Notepad2 as editor gives logs and errors

### ISSUE THREAD

**Issue by GerjanOnline** [git-for-windows/git#517]
I am using:
Windows 10 x64
Git version 2.6.2.windows.1
Notepad2 x64 (this one overrides notepad)

.gitconfig
<pre>
[core]
	editor = notepad
	autocrlf = true (also tried false)
  ...
</pre>

When I do `git config -e --global`:
<pre>
git config --global -e
unix2dos: C:/Users/user/.gitconfig MODE 0100644  (regular file)
unix2dos: using C:/Users/user/d2utmphK5NvM as temporary file
unix2dos: converting file C:/Users/user/.gitconfig to DOS format...
dos2unix: C:/Users/user/.gitconfig MODE 0100644  (regular file)
dos2unix: using C:/Users/user/d2utmpW2rV1K as temporary file
dos2unix: converting file C:/Users/user/.gitconfig to Unix format...
</pre>

When i do `git commit --amend` (just to do a commit):

<pre>
git commit --amend
unix2dos: path/public/.git/COMMIT_EDITMSG MODE 0100644  (regular file)
unix2dos: using path/public/.git/d2utmpX1LaLG as temporary file
unix2dos: converting file path/public/.git/COMMIT_EDITMSG to DOS format...
dos2unix: path/public/.git/COMMIT_EDITMSG MODE 0100644  (regular file)
dos2unix: using path/public/.git/d2utmpn8txZW as temporary file
dos2unix: converting file path/public/.git/COMMIT_EDITMSG to Unix format...
error: There was a problem with the editor 'notepad'.
Please supply the message using either -m or -F option.
</pre>

Why do I get these messages? When I have `atom` as my editor it doesn't give me these messages...

**Comment by GerjanOnline** [comment]
Related to https://github.com/git-for-windows/git/issues/430 and https://github.com/git-for-windows/git/issues/381

**Comment by GerjanOnline** [comment]
After some digging it seems that:

`C:\Program Files\Git\usr\bin\notepad`

is the problem. 

<pre>
#!/bin/sh

die () {
	echo "$*" >&2
	exit 1
}

test $# = 1 ||
die "Usage: $0 <file>"

if test -f "$1"
then
	unix2dos.exe "$1"
fi &&
notepad.exe "$1" &&
dos2unix.exe "$1" &&
case "$1" in
*/COMMIT_EDITMSG|*\\COMMIT_EDITMSG)
	columns="$(git config format.commitmessagecolumns)" &&
	if test -z "$columns"
	then
		msg="$(fmt.exe -s -w "$columns" "$1")" &&
		printf "%s" "$msg" >"$1"
	fi
	;;
esac
</pre>

This is new? Some kind of helper?

**Comment by shiftkey** [comment]
https://github.com/git-for-windows/build-extra/commit/69b301bbd7c18226c63d83638991cb2b7f84fb64

**Comment by kgybels** [comment]
@GerjanOnline Yes, it is a helper for using plain notepad.

Since you are using Notepad2 instead, maybe setup your editor like this:

**Comment by GerjanOnline** [comment]
https://github.com/git-for-windows/build-extra/commit/69b301bbd7c18226c63d83638991cb2b7f84fb64 makes sense.

Thanks

**Comment by domenic** [comment]
Can I turn this off somehow? I am used to being able to just type `notepad foo.txt` and edit my files in Notepad2. But now it converts all their line feeds when it does so, which is pretty strange...

I can just delete the /usr/bin/notepad script for now, I guess, but it will presumably come back in an upgrade. Can we add an option to remove it entirely?

**Comment by kgybels** [comment]
@domenic Maybe you can create an alias to work around your issue:
`$ alias notepad='/c/Program\ Files/Notepad2/Notepad2.exe'`

You could even use `n` instead of `notepad`, then you don't have to type as much :)

**Comment by dscho** [comment]
> ```
> unix2dos: path/public/.git/COMMIT_EDITMSG MODE 0100644 (regular file)
> unix2dos: using path/public/.git/d2utmpX1LaLG as temporary file
> unix2dos: converting file path/public/.git/COMMIT_EDITMSG to DOS format...
> dos2unix: path/public/.git/COMMIT_EDITMSG MODE 0100644 (regular file)
> dos2unix: using path/public/.git/d2utmpn8txZW as temporary file
> dos2unix: converting file path/public/.git/COMMIT_EDITMSG to Unix format...
> error: There was a problem with the editor 'notepad'.
> Please supply the message using either -m or -F option.

From this output, together with the original lines:

> ```sh
> if test -f "$1"
> then
>     unix2dos.exe "$1"
> fi &&
> notepad.exe "$1" &&
> dos2unix.exe "$1" &&
> case "$1" in
> */COMMIT_EDITMSG|*\\COMMIT_EDITMSG)
>     columns="$(git config format.commitmessagecolumns)" &&
>     if test -z "$columns"
>     then
>         msg="$(fmt.exe -s -w "$columns" "$1")" &&
>         printf "%s" "$msg" >"$1"
>     fi
>     ;;
> esac

it appears that `notepad.exe` is run correctly, as is `dos2unix.exe`, but then a problem occurs because the exit status is not zero.

The really interesting part would be to investigate *which* command fails (is it `dos2unix.exe`, without an error message? Or `fmt.exe`? Or `printf`? Or is it impossible to write to `"$1"`?

These questions need to be answered instead of papering over the problem by deleting the `/usr/bin/notepad` file (which would reappear with the next upgrade, as has been suspected correctly).

**Comment by kgybels** [comment]
@dscho `git config format.commitmessagecolumns` will exit with code 1 if the section or key is invalid. The way the notepad script is written that will cause the whole script to also exit with code 1.

Also, `if test -z "$columns"` shouldn't this be `if test -n "$columns"`?

**Comment by dscho** [comment]
> git config format.commitmessagecolumns will exit with code 1 if the section or key is invalid. The way the notepad script is written that will cause the whole script to also exit with code 1.
> 
> Also, if test -z "$columns" shouldn't this be if test -n "$columns"?

Yep, those are both bugs.
