### ISSUE TITLE
Git SCM - Windows Explorer.EXE context menu is giving "Application not found" error.

### ISSUE THREAD

**Issue by Padmahas** [git-for-windows/git#5179]
- [ ] I was able to find a [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] https://github.com/git-for-windows/git/issues/957

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.46.2.windows.1
cpu: x86_64
built from commit: 1e20af0e809e08cca5714727dfa0fb50c0c4664d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** git version 2.46.2.windows.1
cpu: x86_64
built from commit: 1e20af0e809e08cca5714727dfa0fb50c0c4664d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
 **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** Git was working fine until my company encrypted all drives of the Hard disk with Bit Locker. **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Git bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** Not commands. It's from UI. Just go to some folder in any drive and right click -> "Git bash here". And then this error shows. **
```
 - What did you expect to occur after running these commands?

** Git was working fine until my company encrypted all drives of the Hard disk with Bit Locker. But later, I tried uninstalling Git completely. But for some reason, it is not removing all the installation changes made. I tried several times to uninstall Git completely unsuccessfully. Even reinstalling new Git version is not overwriting the erroneous behavior.**

 - What actually happened instead?

** Even after completely uninstalling and Re-installing updated version of Git, the context menu "Git bash here" is showing error "Application not found". **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> the context menu "Git bash here" is showing error "Application not found".

It works over here, though.

> Git was working fine until my company encrypted all drives of the Hard disk with Bit Locker.

That is strange. My laptop has BitLocker-encrypted drives and everything is working as expected.

So let's dig a bit deeper. [Here](https://github.com/git-for-windows/build-extra/blob/227a87ac02e5cd211022c43916961cecd3e47636/installer/install.iss#L3420-L3435) is the code that installs this shortcut:

```pascal
    if IsComponentSelected('ext\shellhere') then begin
        Msg:='Open Git Ba&sh here';
        Cmd:='"'+AppDir+'\git-bash.exe" "--cd=%1"';
        Ico:=AppDir+'\git-bash.exe';
        if (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_shell','',Msg)) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_shell\command','',Cmd)) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_shell','Icon',Ico)) or
           (StringChangeEx(Cmd,'%1','%v.',false)<>1) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\Background\shell\git_shell','',Msg)) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\Background\shell\git_shell\command','',Cmd)) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\Background\shell\git_shell','Icon',Ico)) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\LibraryFolder\background\shell\git_shell','',Msg)) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\LibraryFolder\background\shell\git_shell\command','',Cmd)) or
           (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\LibraryFolder\background\shell\git_shell','Icon',Ico)) then
            LogError('Line {#__LINE__}: Unable to create "Git Bash Here" shell extension.');
    end;
```

As you can see, the trick is to add a bunch of registry entries, most notably `SOFTWARE\Classes\Directory\shell\git_shell\command` and `SOFTWARE\Classes\Directory\Background\shell\git_shell\command`. The `RootKey` [should refer to `HKEY_LOCAL_MACHINE`](https://github.com/git-for-windows/build-extra/blob/227a87ac02e5cd211022c43916961cecd3e47636/installer/install.iss#L3414-L3418).

Can you see whether this registry entry exists in your setup (e.g. via <kbd>🪟</kbd>+<kbd>R</kbd> and then running `regedit`), and whether it either has a strange value, or whether the referenced command may no longer exist on your machine? For the record, in my (working) setup, the value is `"C:\Program Files\Git\git-bash.exe" "--cd=%1"` (and it should be the same in your setup).

**Comment by Padmahas** [comment]
> > the context menu "Git bash here" is showing error "Application not found".
> 
> It works over here, though.
> 
> > Git was working fine until my company encrypted all drives of the Hard disk with Bit Locker.
> 
> That is strange. My laptop has BitLocker-encrypted drives and everything is working as expected.
> 
> So let's dig a bit deeper. [Here](https://github.com/git-for-windows/build-extra/blob/227a87ac02e5cd211022c43916961cecd3e47636/installer/install.iss#L3420-L3435) is the code that installs this shortcut:
> 
> ```pascal
>     if IsComponentSelected('ext\shellhere') then begin
>         Msg:='Open Git Ba&sh here';
>         Cmd:='"'+AppDir+'\git-bash.exe" "--cd=%1"';
>         Ico:=AppDir+'\git-bash.exe';
>         if (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_shell','',Msg)) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_shell\command','',Cmd)) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\shell\git_shell','Icon',Ico)) or
>            (StringChangeEx(Cmd,'%1','%v.',false)<>1) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\Background\shell\git_shell','',Msg)) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\Background\shell\git_shell\command','',Cmd)) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\Directory\Background\shell\git_shell','Icon',Ico)) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\LibraryFolder\background\shell\git_shell','',Msg)) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\LibraryFolder\background\shell\git_shell\command','',Cmd)) or
>            (not RegWriteStringValue(RootKey,'SOFTWARE\Classes\LibraryFolder\background\shell\git_shell','Icon',Ico)) then
>             LogError('Line {#__LINE__}: Unable to create "Git Bash Here" shell extension.');
>     end;
> ```
> 
> As you can see, the trick is to add a bunch of registry entries, most notably `SOFTWARE\Classes\Directory\shell\git_shell\command` and `SOFTWARE\Classes\Directory\Background\shell\git_shell\command`. The `RootKey` [should refer to `HKEY_LOCAL_MACHINE`](https://github.com/git-for-windows/build-extra/blob/227a87ac02e5cd211022c43916961cecd3e47636/installer/install.iss#L3414-L3418).
> 
> Can you see whether this registry entry exists in your setup (e.g. via 🪟+R and then running `regedit`), and whether it either has a strange value, or whether the referenced command may no longer exist on your machine? For the record, in my (working) setup, the value is `"C:\Program Files\Git\git-bash.exe" "--cd=%1"` (and it should be the same in your setup).

Hello @dscho ,

I checked the above registry key and it is showing the exact value as you have in your system. "C:\Program Files\Git\git-bash.exe" "--cd=%1",

Another observation is, when the Git is uninstalled, these keys are also being removed. But the context menu option still exists even when Git is uninstalled, but it will be having a dummy icon.

When Git is reinstalled, these registry keys are re-created with the same value. But still context menu option still shows with dummy icon and same error is shown.

**Comment by Padmahas** [comment]
I also tried searching with the keywords "Git-" and "Bash" and  found below additional keys and removed them. Still the context menu is showing with dummy icons. The "Git Bash Here" whole string search didn't give any results.

Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache

Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\106
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\107
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\108

Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\67
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\68
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\69

Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\90
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\91
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UFH\SHC\92


Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store\E:Git-4.26

Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store\C:Program files\Git\git-bash.exe

![image](https://github.com/user-attachments/assets/5335759d-e5c5-4d85-aad2-017c4703c69f)

**Comment by Padmahas** [comment]
Found it @dscho !!!.

The same search string "Git-" gave further results and these 2 are the one which finally removed context menu.

Computer\HKEY_USERS\S-1-5-21-3321480885-1230807834-3379218511-13136\SOFTWARE\Classes\Directory\Background\shell\git_gui

Computer\HKEY_USERS\S-1-5-21-3321480885-1230807834-3379218511-13136\SOFTWARE\Classes\Directory\Background\shell\git_shell

For anyone else who is facing this issue, after "HKEY_USERS" the id "S-1-5-21-3321480885-1230807834-3379218511-13136" could vary.
So you need to find the proper registry key by searching the registry itself with "Git-" and carefully decide whether to remove the Key OR Not. Because all keys matching "Git-" may not be removable.

Thank you.
