### ISSUE TITLE
[winpty] output is not a tty

### ISSUE THREAD

**Issue by kmelia** [git-for-windows/git#519]
Hi,
I have an issue with the ``winpty`` aliases: it brokes the TTY ?

How to reproduce:
```sh
$ unalias php
```
```sh
$ winpty php -i | grep "PHP Version"
output is not a tty
```
```sh
$ php -i | grep "PHP Version"
PHP Version => 5.6.15
PHP Version => 5.6.15
```

Is it necessary to use winpty ?

**Comment by kmelia** [comment]
Meanwhile some explications, you can remove all the winpty alias with this command on your ``~/.bashrc`` file :
```sh
# remove winpty alias
unalias $(alias | grep winpty | cut -d"=" -f1 | cut -d" " -f2)
```

**Comment by dscho** [comment]
FWIW there is a much, much easier workaround than to unalias anything:

```
php.exe -i | grep "PHP Version"
```

And no, we cannot simply abandon `winpty`. PHP can be run interactively, i.e. it requires a proper Win32 Console. Running PHP without `winpty` in MinTTY would *not* provide that Console instance, leaving you with a seemingly unresponsive terminal. See git-for-windows/build-extra@44ed99b47f564d0b89784ae8008627f5c3d06d69, https://github.com/git-for-windows/git/issues/399 and https://github.com/git-for-windows/git/issues/400 to understand what havoc you would wreak by simply removing those aliases.

**Comment by kmelia** [comment]
> FWIW there is a much, much easier workaround than to unalias anything:
```php.exe -i | grep "PHP Version"```

I cannot specify ``php.exe`` for some commands, it is not cross platform safe!

> PHP can be run interactively

Yes, but it is not the default use of PHP, it requires : ``php -a`` 
So maybe we could create an other alias name ``phpi`` or ``phpa`` just for ``winpty php``?

What do you think about it?

**Comment by dscho** [comment]
> Yes, but it is not the default use of PHP, it requires : php -a
> So maybe we could create an other alias name phpi or phpa just for winpty php?

No, that would break it again for the people who reported those issues! They call `php -a` as you suggested, and nothing seems to happen!

**Comment by kmelia** [comment]
> No, that would break it again for the people who reported those issues!

Maybe I am wrong, but I have not found reported issues for PHP? 

> They call ``php -a`` as you suggested, and nothing seems to happen!

But with ``winpty`` I call ``php | grep `` and nothing happens ;)

**Comment by dscho** [comment]
> > They call php -a as you suggested, and nothing seems to happen!
> 
> But with winpty I call php | grep and nothing happens ;)

If you seriously suggest I should break other people's setups to unbreak yours, this conversation is pretty much over ;-)

**Comment by kmelia** [comment]
Not at all! Please read carefully my last comment: I explain two things: first, I have not found reported issues for PHP and second, the current setup do break PHP! Not just my little setup ;)

So we have: 
* without ``winpty``: setup KO for ``php -a``
* with ``winpty``: setup KO for ``php``

We must find a fix to all the setup!

**Comment by kmelia** [comment]
Hi @dscho,

I have done some research on the **PHP Interactive shell**:
http://php.net/manual/en/features.commandline.interactive.php:
> As of PHP 5.1.0, the CLI SAPI provides an interactive shell using the -a option if PHP is compiled with the --with-readline option. 

> If you type 'php -a' and get a response of 'Interactive Shell' followed by a 'php>' prompt, you have interactive shell available (PHP was compiled with readline support). If instead you get a response of 'Interactive mode enabled', you DO NOT have interactive shell available and this article does not apply to you.

I try and I have got:
```
$ winpty php -a
Interactive mode enabled
```

So I try to install **readline**, http://php.net/manual/en/intro.readline.php:
> Note: This extension is not available on Windows platforms.

And now I am lost: how ``winpty`` could be useful on **Git for Windows** whereas PHP Interactive shell is not available on Windows?

**Comment by kmelia** [comment]
No more comments?

**Comment by dscho** [comment]
I do not recall where I read a comment of a PHP user who did have an interactive console, but I am pretty certain that we have at least one user who installed PHP using some integrated installer and expects to be able to call that from a Git Bash.

**Comment by kmelia** [comment]
OK then.

I close this issue, but if somebody has the same issue a solution is provided on the [2nd comment](#issuecomment-154025497)

**Comment by galopin** [comment]
@dscho @kmelia Just came across this. It is a real conundrum. It took me several hours to find out how to bypass the `winpty` thingy…

Actually the solution is pretty simple:

```
$ 'php' --ini | cat
Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         C:\php\5445\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

$ 'php' -i | grep "PHP Version"
PHP Version => 5.4.45
PHP Version => 5.4.45
```

Or much shorter?

```
$ \php --ini | cat
Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         C:\php\5445\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

$ \php -i | grep "PHP Version"
PHP Version => 5.4.45
PHP Version => 5.4.45
```

Or more verbose?

```
$ command php --ini | cat
Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         C:\php\5445\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

$ command php -i | grep "PHP Version"
PHP Version => 5.4.45
PHP Version => 5.4.45
```

🍌 It's pretty nifty, isn't it? 🍌

**Comment by dscho** [comment]
Or `php.exe`.

**Comment by galopin** [comment]
Indeed. But `php.exe` is not portable while `\php` or `'php'` are guaranteed to work. Whether you author a makefile or a Bash script, it will work the same across all POSIX-compliant operating systems…

**Comment by dscho** [comment]
@galopin true. You could also work with the `winpty` project to try to make `winpty <command> | <other-command>` work as expected.
