### ISSUE TITLE
[REG 2.46.0 -> 2.47.0] Git hangs on fetch

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#5199]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.47.0.windows.1
cpu: x86_64
built from commit: 8e380191abeda7a995e87abf4acc9e1702fdc698
sizeof-long: 4
sizeof-size_t: 8
shell-path: F:/git-sdk-64/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.4355]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch
```
 - What did you expect to occur after running these commands?

It should be done successfully after a while.

 - What actually happened instead?

It *sometimes* hangs. I see the following spawned process, which doesn't use any CPU, and doesn't terminate:
```
git index-pack --stdin -v --fix-thin "--keep=fetch-pack 4272 on my-pc" --pack_header=2,291
```

The output is:
```
remote: Counting objects: 195, done
remote: Finding sources: 100% (292/292)
<nothing happens>
<when I press Ctrl-C>
fetch-pack: unexpected disconnect while reading sideband packet
```

**Comment by dscho** [comment]
> * What commands did you run to trigger this issue? If you can provide a
>   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
>   this will help us understand the issue.
> 
> ```
> git fetch
> ```

To make this example a little more complete, could you describe from where you are fetching? Is it github.com, a self-hosted `git daemon`, from a network share? Is it a big fetch, i.e. have already dozens of megabytes been transferred, or is it a small fetch? Did you try to [disable sideband](https://github.com/git-for-windows/git/pull/2375)?

**Comment by orgads** [comment]
It's a hosted gerrit 3.8 server. 

I can try to disable sideband tomorrow.

**Comment by jfcherng** [comment]
I tried to clone my https://github.com/jfcherng/copilot-node-server .

It seems to alway hang if I clone `git@github.com:jfcherng/copilot-node-server.git`. But it's okay if I clone `https://github.com/jfcherng/copilot-node-server.git`.

**Comment by orgads** [comment]
Ah right, my case was ssh too.

**Comment by EemilAhonen** [comment]
We are having this same problem with SSH on multiple machines that upgraded to the latest 2.47.0. All clones over 1mb from Gitlab are failing, the Git window just freezes at random points.
Uninstalling 2.47.0 and reinstalling 2.44.0 solved the issue.

**Comment by dscho** [comment]
Does it work if you copy the `usr\bin\ssh.exe` over from v2.46.2?

**Comment by jfcherng** [comment]
> Does it work if you copy the `usr\bin\ssh.exe` over from v2.46.2?

In my case, no.

**Comment by dscho** [comment]
> > Does it work if you copy the `usr\bin\ssh.exe` over from v2.46.2?
> 
> In my case, no.

How about copying over `usr\bin\msys-2.0.dll`?

**Comment by jfcherng** [comment]
> How about copying over `usr\bin\msys-2.0.dll`?

Yes, that's the culprit. I tried in a fresh portable build. No need to replace `ssh.exe`.

**Comment by dscho** [comment]
I feared as much. There is a rather big jump in the MSYS2 runtime upgrade between Git for Windows v2.46.2 and v2.47.0. And MSYS2 runtime issues are notoriously hard to fix.

You wouldn't happen to have a good reproducer that other people might be able to use, would you? I am afraid that `git fetch` as an MCVE does not pass muster.

**Comment by elindoorn** [comment]
A git pull from a azure repo consistently hung for me today until i reverted to 2.46.2

> git pull
remote: Azure Repos
remote: Found 308 objects to send. (757 ms)

the trace suggests it can collect branches/tags and such before it hangs

`> git pull
13:28:53.108594 exec-cmd.c:266          trace: resolved executable dir: C:/s/git/mingw64/bin
13:28:53.118594 git.c:479               trace: built-in: git pull
13:28:53.157446 run-command.c:667       trace: run_command: git merge-base --fork-point refs/remotes/origin/redacted redacted
13:28:53.157446 run-command.c:928       trace: start_command: git merge-base --fork-point refs/remotes/origin/redacted redacted
13:28:53.197744 run-command.c:667       trace: run_command: git fetch --update-head-ok
13:28:53.197744 run-command.c:928       trace: start_command: git fetch --update-head-ok
13:28:53.209496 exec-cmd.c:266          trace: resolved executable dir: C:/s/git/mingw64/libexec/git-core
13:28:53.219721 git.c:479               trace: built-in: git fetch --update-head-ok
13:28:53.223755 run-command.c:667       trace: run_command: unset GIT_PREFIX; GIT_PROTOCOL=version=2 ssh -o SendEnv=GIT_PROTOCOL git@ssh.dev.azure.com 'git-upload-pack '\''v3/redacted'\'''
13:28:53.224873 run-command.c:928       trace: start_command: ssh -o SendEnv=GIT_PROTOCOL git@ssh.dev.azure.com 'git-upload-pack '\''v3/redacted'\'''
13:28:53.987805 pkt-line.c:86           packet:        fetch< 191d8833b443043e99cd2d3184f4b66c154d3847 HEAD\0 multi_ack thin-pack side-band side-band-64k no-progress multi_ack_detailed no-done shallow allow-tip-sha1-in-want filter symref=HEAD:refs/heads/develop
...
13:28:54.115251 pkt-line.c:86           packet:        fetch< NAK
13:28:54.136540 pkt-line.c:86           packet:        fetch< ACK eb10cf30356d9de23600c64368d94d664db97888
13:28:54.138227 pkt-line.c:86           packet:     sideband< \2Azure Repos
remote: Azure Repos
13:28:54.139224 pkt-line.c:86           packet:     sideband< \2\15Found 303 objects to send. (12 ms)
remote: Found 303 objects to send. (12 ms)

nothing after this`

**Comment by ryanmkurtz** [comment]
I'm having the same issue too with the move from `2.46.0` to `2.47.0`.  Both `clone` and `fetch` now hang:
```
$ git fetch
remote: Enumerating objects: 8510, done.
remote: Counting objects: 100% (5831/5831), done.
remote: Compressing objects: 100% (782/782), done.
<hang>
```

**Comment by derrickstolee** [comment]
I was able to reproduce the failing clones and have a workaround:

```
git -c core.sshCommand="'C:\Windows\System32\OpenSSH\ssh.exe'" clone ...
```

or

```
git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
git clone ...
```

This configures Git to use the SSH agent built into Windows instead of the OpenSSL-based one provided by MSYS2.

**Comment by b12k** [comment]
Same here.
Hangs on `clone` with 2.47.0

@derrickstolee Solution helped 👆

**Comment by Nbc66** [comment]
Can Confirm  `git clone` & `git push` hang when trying to call em this only happens on version `2.47.0` the other version like `2.46.2` work just fine

this might be related to the `MSYS2` upgrade on the latest version

**Comment by goostleek** [comment]
I can confirm, I thought it was specific to my repo only, but using an example provided at https://github-debug.com/

```bash
GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone git@github.com:github/debug-repo /tmp/debug-repo-ssh
```
causes the SSH connection to freeze



> [!NOTE]
> The possible workaround is to temporarily switch from `ssh://` to `https://` when feasible
> ```bash
> git remote set-url origin 'https://<repo-url>'
> ```

**Comment by mm65de** [comment]
After installing _Git-2.47.0-64-bit.exe_ the git commands _clone_ and _fetch_ also hang on my machine.
My previous installation without that problem was based on this setup file: _Git-2.46.2-64-bit.exe_

Here is an example of this problem:

```
2024-10-10 11:24:35  c:\Tmp\git_test_folder> git clone git@github.com:git-for-windows/git.git
Cloning into 'git'...
remote: Enumerating objects: 622752, done.
remote: Counting objects: 100% (7374/7374), done.
remote: Compressing objects: 100% (2904/2904), done.

```
Now nothing happens anymore.
If I press Ctrl-C then I get this:

```
fetch-pack: unexpected disconnect while reading sideband packet
fatal: fetch-pack: invalid index-pack output

2024-10-10 11:26:13  c:\Tmp\git_test_folder>
```

Here comes the _System Info_ section of the text file generated by the command _git bugreport_:

```
[System Info]
git version:
git version 2.47.0.windows.1
cpu: x86_64
built from commit: d53e4648cb65eb75dd8d8a093d17400a18a9a15d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
uname: Windows 10.0 19045 
compiler info: gnuc: 14.2
libc info: no libc information available
$SHELL (typically, interactive shell): <unset>
```

After executing the setup file _Git-2.46.2-64-bit.exe_ and accepting the downgrade warning the command _git clone_ worked well again:

```
2024-10-10 11:51:53  c:\Tmp\git_test_folder> git clone git@github.com:git-for-windows/git.git
Cloning into 'git'...
remote: Enumerating objects: 622752, done.
remote: Counting objects: 100% (7379/7379), done.
remote: Compressing objects: 100% (2905/2905), done.
remote: Total 622752 (delta 6166), reused 4919 (delta 4472), pack-reused 615373 (from 1)
Receiving objects: 100% (622752/622752), 310.19 MiB | 5.87 MiB/s, done.
Resolving deltas: 100% (450376/450376), done.
Updating files: 100% (4589/4589), done.

2024-10-10 11:53:16  c:\Tmp\git_test_folder>
```

**Comment by Nbc66** [comment]
> After installing _Git-2.47.0-64-bit.exe_ the git commands _clone_ and _fetch_ also hang on my machine. My previous installation without that problem was based on this setup file: _Git-2.46.2-64-bit.exe_
> 
> Here is an example of this problem:
> 
> ```
> 2024-10-10 11:24:35  c:\Tmp\git_test_folder> git clone git@github.com:git-for-windows/git.git
> Cloning into 'git'...
> remote: Enumerating objects: 622752, done.
> remote: Counting objects: 100% (7374/7374), done.
> remote: Compressing objects: 100% (2904/2904), done.
> ```
> 
> Now nothing happens anymore. If I press Ctrl-C then I get this:
> 
> ```
> fetch-pack: unexpected disconnect while reading sideband packet
> fatal: fetch-pack: invalid index-pack output
> 
> 2024-10-10 11:26:13  c:\Tmp\git_test_folder>
> ```
> 
> Here comes the _System Info_ section of the text file generated by the command _git bugreport_:
> 
> ```
> [System Info]
> git version:
> git version 2.47.0.windows.1
> cpu: x86_64
> built from commit: d53e4648cb65eb75dd8d8a093d17400a18a9a15d
> sizeof-long: 4
> sizeof-size_t: 8
> shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
> feature: fsmonitor--daemon
> libcurl: 8.10.1
> OpenSSL: OpenSSL 3.2.3 3 Sep 2024
> zlib: 1.3.1
> uname: Windows 10.0 19045 
> compiler info: gnuc: 14.2
> libc info: no libc information available
> $SHELL (typically, interactive shell): <unset>
> ```
> 
> After executing the setup file _Git-2.46.2-64-bit.exe_ and accepting the downgrade warning the command _git clone_ worked well again:
> 
> ```
> 2024-10-10 11:51:53  c:\Tmp\git_test_folder> git clone git@github.com:git-for-windows/git.git
> Cloning into 'git'...
> remote: Enumerating objects: 622752, done.
> remote: Counting objects: 100% (7379/7379), done.
> remote: Compressing objects: 100% (2905/2905), done.
> remote: Total 622752 (delta 6166), reused 4919 (delta 4472), pack-reused 615373 (from 1)
> Receiving objects: 100% (622752/622752), 310.19 MiB | 5.87 MiB/s, done.
> Resolving deltas: 100% (450376/450376), done.
> Updating files: 100% (4589/4589), done.
> 
> 2024-10-10 11:53:16  c:\Tmp\git_test_folder>
> ```

Its an issue with the latest MYSYS2 update they did

**Comment by mm65de** [comment]
If it helps, here are more configuration details of my machine:
```
2024-10-10 12:10:46  c:\Tmp\git_test_folder> git config --list --system
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=false
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
pull.rebase=true
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master

2024-10-10 12:11:18  c:\Tmp\git_test_folder>
```

If I use the HTTPS URL instead of the SSH URL to clone the repository, then the command _git clone_ even works with the new version _2.47.0.windows.1_.

**Comment by david-siegert** [comment]
After update to 2.47 I get the same error "unexpected disconnect while reading sideband packet" when trying to use **git clone** using ssh. After rolling back to 2.46 it works fine.

**Comment by jeremyVignelles** [comment]
> You wouldn't happen to have a good reproducer that other people might be able to use, would you? I am afraid that `git fetch` as an MCVE does not pass muster.

For reference, I came across this issue from https://github.com/mutagen-io/mutagen/issues/511 :
Mutagen detects the ssh from git-for-windows and tries to use it to connect to the remote server. The update in git-for-windows broke the mutagen detection as well, and we had to revert msys-2.0.dll.

I don't know what kind of reproduction project you need, but our use case is just a virtualbox VM and trying to sync something with mutagen `mutagen sync create...`

**Comment by dscho** [comment]
I can reproduce the issue, and am bisecting now. Experience suggests that it might take a couple of days to get to the bottom of this, so please have patience.

**Comment by dscho** [comment]
Okay, I have [a fix in hand](https://github.com/git-for-windows/msys2-runtime/pull/75): It seems to be a regression in Cygwin v3.5.3, and while I am not completely happy about the extent to which I understand what is going wrong, it seems safe enough to revert to the working behavior (even if it should not completely reflect how Linux would behave in the same situation).

Y'all, could I ask you to download [the `install.zip` artifact](https://github.com/git-for-windows/msys2-runtime/actions/runs/11279394319/artifacts/2041778605) produced by the PR build, and extract its `usr/bin/msys-2.0.dll` over your existing one, then verify that it fixes the issue not only for me, but also for all of you gentle people?

**Comment by jfcherng** [comment]
> Y'all, could I ask you to download [the `install.zip` artifact](https://github.com/git-for-windows/msys2-runtime/actions/runs/11279394319/artifacts/2041778605) produced by the PR build, and extract its `usr/bin/msys-2.0.dll` over your existing one, then verify that it fixes the issue not only for me, but also for all of you gentle people?

That `usr/bin/msys-2.0.dll` works on my end. Thanks.

**Comment by orgads** [comment]
Works for me. Thank you very much!

Did you report the issue to cygwin?

**Comment by dscho** [comment]
> Works for me. Thank you very much!

Awesome!

> Did you report the issue to cygwin?

Not yet, I first wanted to be sure that I have something that works not only for me, but for all others, too.

**Comment by inflamously** [comment]
Oh my god, had I just found this. Nearly lost a day since I've recently reinstalled windows 11 (24H2) latest build whatsoever and git  v2.47.0.windows.1. Couldn't for life clone a repository with using git clone when using a ssh url. Now I've downgraded for now, but the tips above are also helpful. Thanks.

**Comment by dscho** [comment]
/add relnote bug A [regression](https://github.com/git-for-windows/git/issues/5199) where clones, fetches and pushes via SSH would dead-lock was fixed.

**Comment by nga888** [comment]
FYI: I also ran into this issue and fixed it with this patch:
```
--- a/winsup/cygwin/select.cc
+++ b/winsup/cygwin/select.cc
@@ -674,7 +674,8 @@ pipe_data_available (int fd, fhandler_base *fh, HANDLE h, int flags)
          paranoid_printf ("fd %d, %s, write: size %u, avail %u", fd,
                           fh->get_name (), fpli.InboundQuota,
                           fpli.WriteQuotaAvailable);
-         return fpli.WriteQuotaAvailable;
+         return (flags & PDA_SELECT) ? MAX (PIPE_BUF, fpli.WriteQuotaAvailable)
+                                     : fpli.WriteQuotaAvailable;
        }
       /* TODO: Buffer really full or non-Cygwin reader? */
     }
```
I also emailed Corinna Vinschen about the issue along with this patch.

**Comment by david-siegert** [comment]
> Okay, I have [a fix in hand](https://github.com/git-for-windows/msys2-runtime/pull/75): It seems to be a regression in Cygwin v3.5.3, and while I am not completely happy about the extent to which I understand what is going wrong, it seems safe enough to revert to the working behavior (even if it should not completely reflect how Linux would behave in the same situation).
> 
> Y'all, could I ask you to download [the `install.zip` artifact](https://github.com/git-for-windows/msys2-runtime/actions/runs/11279394319/artifacts/2041778605) produced by the PR build, and extract its `usr/bin/msys-2.0.dll` over your existing one, then verify that it fixes the issue not only for me, but also for all of you gentle people?

Maybe redundant but I also confirm that the fix works on my end too.

**Comment by nga888** [comment]
> I also emailed Corinna Vinschen about the issue along with this patch.

I'm not particularly familiar with Cygwin development, so I'm not sure that I have reported the issue "correctly", i.e. I haven't had any response to my email from over 2 weeks ago, so it's probably worth reporting this issue "properly".

Sorry, I didn't mention this issue earlier on GFW. I don't use the "official" GFW release but have my own UCRT64 based build with "mainline" MSYS2, so hit this issue a bit earlier after the MSYS2 runtime updated to 3.5.4.

**Comment by dscho** [comment]
> I'm not sure that I have reported the issue "correctly", i.e. I haven't had any response to my email from over 2 weeks ago

Given that I cannot find the patch in https://inbox.sourceware.org/cygwin-patches/?q=WriteQuotaAvailable nor in https://inbox.sourceware.org/cygwin/?q=WriteQuotaAvailable, I suspect that you sent this as a private mail (which is a pretty big no-no in open source)?

The lack of response might be due to a vacation, which is even more reason not to send patches a private emails to maintainers.

**Comment by dscho** [comment]
Please note that there is now [a snapshot](https://wingit.blob.core.windows.net/files/index.html) with the fix, as I am planning on holding off from releasing a new Git for Windows version because I anticipate a Git v2.47.1 to be released soon, with even more bug fixes.

**Comment by rescenic** [comment]
In my machine, I fixed it using msys-2.0.dll from GitKraken then copy it to Git folder.

**Comment by kun2001github** [comment]
I'm running into this issue as well, I downgraded it to version 2.45.2

**Comment by dscho** [comment]
> I'm running into this issue as well, I downgraded it to version 2.45.2

@kun2001github I would strongly suggest to upgrade to the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) instead.

**Comment by t-b** [comment]
> Please note that there is now [a snapshot](https://wingit.blob.core.windows.net/files/index.html) with the fix, as I am planning on holding off from releasing a new Git for Windows version because I anticipate a Git v2.47.1 to be released soon, with even more bug fixes.

I can confirm that the snapshot from friday fixes the issue.

**Comment by radnvlad** [comment]
> > I'm running into this issue as well, I downgraded it to version 2.45.2
> 
> @kun2001github I would strongly suggest to upgrade to the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) instead.

FYI, I upgraded to the snapshot and the original issue is gone, but it still didn't get to work fully, it failed at the end and got back

```
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: unpack-objects failed

```


Downgrading to 2.46.0 fixed the issue. 

It's possible that this is something from my end though.

**Comment by dscho** [comment]
@radnvlad since yours is the only report where the issue is _not_ fixed by the snapshot, you are likely hitting a different bug. Please open a separate issue for that, providing ample amounts of information about your specific scenario. It would also be good if you could bisect through the [snapshots](https://wingit.blob.core.windows.net/files/index.html) (always replacing the `msys-2.0.dll` with the version from v2.46.0) to see when your particular bug was introduced.

For all other readers stumbling over this here issue: please upgrade to the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by henryduong26** [comment]
same issue. rollback to version 2.45

**Comment by dscho** [comment]
> same issue. rollback to version 2.45

I really wonder why my advice to upgrade to the latest snapshot goes _so_ unheeded, and I wonder even more why people document publicly that they ignored this advice.

I do try to fix those bugs, you know? It's not exactly motivating to see how little regard these efforts earn.

**Comment by dscho** [comment]
To help all readers stumbling over this here issue: please upgrade to the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), it fixes this issue.

**Comment by AngusMcGyver** [comment]
> > same issue. rollback to version 2.45
> 
> I really wonder why my advice to upgrade to the latest snapshot goes _so_ unheeded, and I wonder even more why people document publicly that they ignored this advice.
> 
> I do try to fix those bugs, you know? It's not exactly motivating to see how little regard these efforts earn.

there are cases where it is not a feasible option to use the latest snapshot.
e.g. i administrate ~50 pcs and use the [chocolatey package](https://community.chocolatey.org/packages/git) to install/update and there is no package for latest snapshot. so at least for me the way to go, with an reasonable effort, is to downgrade, pin and wait for release of 2.47.1.

anyway, thanks for providing those bug fixes, good work :bow:

**Comment by Stijnwingens** [comment]
Nice work @dscho 💪

**Comment by ava-fred** [comment]
> > same issue. rollback to version 2.45
> 
> I really wonder why my advice to upgrade to the latest snapshot goes _so_ unheeded, and I wonder even more why people document publicly that they ignored this advice.
> 
> I do try to fix those bugs, you know? It's not exactly motivating to see how little regard these efforts earn.

There might also be others like me who very much appreciate your efforts @dscho but don't feel the need to add yet another me-too post to this issue.

**Comment by dscho** [comment]
Just so this does not get lost between the comments, to help all readers stumbling over this here issue: please upgrade to the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), it fixes this problem.

**Comment by dscho** [comment]
For the record: I plan on releasing Git for Windows v2.47.0(2) tomorrow, with the fix for this issue.

**Comment by mm65de** [comment]
I just installed [Git-2.47.0.2-64-bit.exe](https://wingit.blob.core.windows.net/files/Git-2.47.0.2-64-bit.exe) [^1]
Cloning and fetching worked perfectly! :+1:
**Many thanks!** :green_heart:
:smile:

[^1]: $ git --version
git version 2.47.0.windows.2

**Comment by AmelieKuo** [comment]
Using Git-2.47.0-64-bit, the git clone command gets stuck at "remote object done" with no error messages, but the project does not download successfully; only a folder with the root directory as ".git", and the other files are not downloaded.

However, using Git-2.46.0-64-bit.exe allows the git clone command to execute successfully.

**Comment by orgads** [comment]
@dscho Better lock this issue...

**Comment by dscho** [comment]
> @dscho Better lock this issue...

@orgads is it too heated for you? 🤭

I could also hide the new reports about a now-outdated version as Resolved. That might make for a bit nicer an experience, given that we're still aiming to be a welcoming place and those reports are not spam or abure, what do you think?

**Comment by orgads** [comment]
I would add to the "updated" note above (and maybe also a new comment that will conclude the discussion) something like "if you still encounter problems with version 2.47.0(2) and up, please file a new issue" and lock this one. This will hopefully lead users to actually read the updates and realize that it was solved before posting "me too".

**Comment by dscho** [comment]
@orgads I hope that the updated title is enough.

**Comment by rotu** [comment]
What's the right way to update this in a github-hosted runner?

The following workflow step fails with "Error: Process completed with exit code 2.". I experience similar problems with `shell:pwsh` and `shell:powershell`:

```yaml
- name: Update git for windows
    if: runner.os == 'Windows'
    run: git update-git-for-windows --yes
    shell: cmd
```

```
2024-10-24T17:31:41.3652735Z [36;1mgit update-git-for-windows --yes[0m
2024-10-24T17:31:41.3677331Z shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
2024-10-24T17:31:41.3678050Z ##[endgroup]
2024-10-24T17:31:43.6864522Z Git for Windows 2.47.0.windows.1 (64-bit)
2024-10-24T17:31:44.0033217Z Update 2.47.0.windows.2 is available
2024-10-24T17:31:44.5000031Z Downloading Git-2.47.0.2-64-bit.exe
...
2024-10-24T17:31:44.9470534Z ######################################################################## 100.0%
2024-10-24T17:31:51.5451678Z ##[error]Process completed with exit code 2.
```

**Comment by rotu** [comment]
I had success with this:
```yaml
 - name: Install git for windows
   if: runner.os == 'Windows'
   shell: pwsh
   run: |
     Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.47.0.windows.2/Git-2.47.0.2-64-bit.exe" -OutFile "${{runner.temp}}/git-for-windows.exe"
     Start-Process -Filepath "${{runner.temp}}/git-for-windows.exe" -ArgumentList  @("/VERYSILENT","/NORESTART","/NOCANCEL","/SP-","/CLOSEAPPLICATIONS","/RESTARTAPPLICATIONS","/o:PathOption=CmdTools","/o:BashTerminalOption=ConHost","/o:EnableSymlinks=Enabled","/COMPONENTS=gitlfs") -NoNewWindow -Wait
```

I still have no idea why `git update-git-for-windows` failed.

**Comment by mikeKuester** [comment]
I can confirm, that this fixes also my problem with `git push` and active Git Lfs: https://github.com/git-lfs/git-lfs/issues/5893

**Comment by stefan-muc** [comment]
> For the record: I plan on releasing Git for Windows v2.47.0(2) tomorrow, with the fix for this issue.

Thanks for releasing this as version! I wouldn't have found this bug report as easily otherwise. My colleague and me stumbled on this bug but first suspected changed firewall policies as root cause. During debugging I upgraded git, and the bug was gone.

Regarding your question why people rather do a downgrade: I use a package manager (chocolatey) for software like git. Doing a downgrade is an one liner. Using a snapshot from somewhere and clicking through the installer is more work.

**Comment by prashanth2060** [comment]
I am using the latest git version 2.48.1.windows.1 and still I see too much of slowness with git clone of a repo. Receiving objects will reach 96% in 3 minutes and then remaining 4% completion will take around 15 minutes. Its too slow but does not hang or error out. is this fix not working? is my issue different than this issue? why it becomes slow after 96%?

**Comment by orgads** [comment]
If I understand correctly, Git downloads objects sorted by size. So if you're repo has some very large objects, it can take a while. This doesn't look related to this issue anyway.

**Comment by Itja** [comment]
On a Windows I installed today, cloning our repository with 2.50.0.windows.1 froze indefinetely at 38%, while when swapping to the ssh.exe from Windows via

```
git config --global core.sshCommand "C:/Windows/System32/OpenSSH/ssh.exe"
```

the clone went through smoothly. If this here is not the issue, something else is.

**Comment by dscho** [comment]
@Itja you are actually reporting  _different_ bug, one that has been reported in #5688 already.

**Comment by WyrickC** [comment]
> I was able to reproduce the failing clones and have a workaround:
> 
> ```
> git -c core.sshCommand="'C:\Windows\System32\OpenSSH\ssh.exe'" clone ...
> ```
> 
> or
> 
> ```
> git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
> git clone ...
> ```
> 
> This configures Git to use the SSH agent built into Windows instead of the OpenSSL-based one provided by MSYS2.

Thank you kindly! This worked for me

**Comment by Saibamen** [comment]
@WyrickC: Please upgrade your git

**Comment by DanielRowe1** [comment]
This problem seems to be back with git 2.50.0 on windows. Tested on Win 11, 2.49 works, 2.50 does not.

**Comment by dscho** [comment]
@DanielRowe1 it's supposed to be fixed in v2.50.0(2). How about giving it a try?

**Comment by DanielRowe1** [comment]
@dscho Yes, fixed. Thanks you. Didn't notice the new version.

**Comment by CleytonJrB** [comment]
> Consegui reproduzir os clones com falha e tenho uma solução alternativa:
> 
> ```
> git -c core.sshCommand="'C:\Windows\System32\OpenSSH\ssh.exe'" clone ...
> ```
> 
> ou
> 
> ```
> git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
> git clone ...
> ```
> 
> Isso configura o Git para usar o agente SSH integrado ao Windows em vez do agente baseado em OpenSSL fornecido pelo MSYS2.

Thanks you
