### ISSUE TITLE
3c806913 *docs: improve external scanner details and fix conflicting tokens details*

### ISSUE THREAD

**Issue by Sec-p101** [git-for-windows/git#5209]
3c806913 *docs: improve external scanner details and fix conflicting tokens details*
* Removed convention notes introduced in #1947 due to:
  * It doesn't so strict for bindings and they may need to obey to some target language conventions.
  * For language grammars there is a note that states the same in the `Creating Parsers` section.
* Removed `External Scanning` item introduced in 87a0517 commit  originated from #1612 due to unclear consistency with other 5 original statements. There is a similar explanation in the  `Other External Scanner Details` section.

613382c7 *docs: update badges; fix markdown lint complains*

Linter config `.vscode/settings.json`:
```json
{
    "[markdown]": {
        "files.trimTrailingWhitespace": false,
    },
    "markdownlint.config": {
        "default": true,
        // "ul-style": {
        //     "style": "asterisk"
        // },
        "MD001": false,
        "MD024": false,
        "MD025": false,
        "MD033": false,
        "MD041": false,
        "MD053": false,
    },
}
```

Fixes: #2210 

_Originally posted by @ahlinc in https://github.com/tree-sitter/tree-sitter/pull/2211_

**Comment by dscho** [comment]
Please use your own fork for practicing how to use GitHub.
