### ISSUE TITLE
'git clean -fdx' returns errorlevel 1

### ISSUE THREAD

**Issue by talcloudshare** [git-for-windows/git#521]
Running 'git clean -fd' or 'git clean -fx' works properly (i.e., errorlevel is 0 at the end of the execution)

Seems to only happen with certain (large) repositories

**Comment by talcloudshare** [comment]
Before anyone asks, this does not happen with the linux Git cli

**Comment by dscho** [comment]
> Before anyone asks, this does not happen with the linux Git cli

@talcloudshare that is not at all the first question I have... my first question is: are you absolutely sure you do not want to describe this issue in substantially more detail, including Git for Windows version, exact paste of the output of the command, URL to a repository with which this issue can be reproduced reliably?

**Comment by talcloudshare** [comment]
I am using the latest version of git for windows (2.6.2)

When running 'git clean -xfd' there's no output other than the removed folders/files, running 'echo %errorlevel%' returns 1

```
C:\code\cloudshare>git clean -xfd                                               
Removing ...                                         
...                                                
Removing ...                                           
                                                                                
C:\code\cloudshare>echo %errorlevel%                                            
1
```

Unfortunately the repository is private and cannot be shared, however I will attempt to debug this myself and try to narrow down the problem so that I can provide more information. Will be helpful if you could guide me, currently following https://github.com/git-for-windows/git/wiki/Debugging-Git

**Comment by kgybels** [comment]
@dscho  I can reproduce if I create long paths:

    KGybels@PC-KG MINGW64 /c/git/bug
    $ ls
    steps.sh*
    
    KGybels@PC-KG MINGW64 /c/git/bug
    $ cat steps.sh
    #!/bin/bash
    longname=$(printf '%*s' 100 | tr ' ' a)
    git init test
    cd test
    mkdir -p $longname/$longname/$longname
    touch $longname/test.txt
    touch $longname/$longname/$longname/test.txt
    git clean -xdf
    echo $?
    KGybels@PC-KG MINGW64 /c/git/bug
    $ ./steps.sh
    Initialized empty Git repository in C:/git/bug/test/.git/
    Removing aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/test.txt
    1

@talcloudshare Can you check for long paths in your case?

**Comment by kgybels** [comment]
@talcloudshare Enabling `core.longpaths` fixes it for my example.

Can you try:

**Comment by talcloudshare** [comment]
Thanks, this works for me
Was suspicious of a long path that cannot be cleaned, but there was no indicative output

**Comment by dscho** [comment]
So the issue is the missing error message.

The next steps would be:
1. turn @kgybels' MCVE (thank you *so* much, this was the most helpful thing in this entire ticket) into a proper regression test, best would be `t/t7300-clean.sh`, using `test_expect_success MINGW ...`
2. debug into the issue where the failure happens and why no error is shown
3. add the error message
4. open a Pull Request
