### ISSUE TITLE
Latest version of Git breaks LFS pushes if SSH Authentification is used

### ISSUE THREAD

**Issue by bomborant** [git-for-windows/git#5210]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git --version --build-options
git version 2.47.0.windows.1
cpu: x86_64
built from commit: d53e4648cb65eb75dd8d8a093d17400a18a9a15d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.5011]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

- Nothing out of the norm

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git add "Path To LFS Item"
git commit -m "Some Message"
git push (here is the problem)
```
 - What did you expect to occur after running these commands?

Pushing the LFS items to the repository as it had always done before.

 - What actually happened instead?

$ git push
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
batch request: unexpected end of JSON input
error: failed to push some refs to 'bitbucket.org:mycompany/myrepo.git'

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Unfortunately it's a private company's repo.

EXTRA INFO:
If we swap to HTTP Authentification we can keep working. This seems to be a SSH x LFS issue

**Comment by dscho** [comment]
Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by bomborant** [comment]
> Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

Yep! That fixed it!
Thanks for the quick reply! 🙏

**Comment by dscho** [comment]
For the record, I consider this a duplicate of #5199 (even if it may not be obvious from the reports, the underlying root cause is the very same).
