### ISSUE TITLE
Profile for Windows Terminal

### ISSUE THREAD

**Issue by apodtele** [git-for-windows/git#5211]
This is a feature request to add Git Bash profile to Windows Terminal during installation. This seems trivial by adding the following to `settings.json`.
```
            {
                "commandline": "%ProgramFiles%\\Git\\bin\\bash -l",
                "startingDirectory": "~",
                "name": "Git Bash",
                "icon": "%ProgramFiles%\\Git\\mingw64\\share\\git\\git-for-windows.ico"
            }
```
The main motivation is ditching `mintty`.

**Comment by dscho** [comment]
duplicate of https://github.com/git-for-windows/git/issues/3183

**Comment by apodtele** [comment]
What keeps mintty around? This should be the default considering #4360?

**Comment by rimrul** [comment]
> What keeps mintty around?

Among other things: The fact that Windows 8.1 exists.

> This should be the default considering https://github.com/git-for-windows/git/issues/4360?

I fail to see how you having issues with `mintty` influences wether we should install the terminal fragment (in addition to regular Git Bash) by default. I'm not opposed to installing it by default, but the linked issue seems unrelated.

**Comment by apodtele** [comment]
I am just happy to find a workaround for the mintty issues. Besides the keyboard focus interference, mintty locks up occasionally due to antivirus or whatever.
