### ISSUE TITLE
ssh-sk-helper (FIDO2/U2F ssh support) missing dependencies

### ISSUE THREAD

**Issue by peterh** [git-for-windows/git#5213]
`ssh-sk-helper.exe` cannot run, because it is missing a handful of dependencies. To work around this issue, I copied the following DLLs from `C:\Program Files\Git\usr\bin` to `C:\Program Files\Git\usr\lib\ssh`:

```
msys-2.0.dll
msys-cbor-0.11.dll
msys-crypto-3.dll
msys-fido2-1.dll
msys-gcc_s-seh-1.dll
msys-z.dll
```

Full environment details:

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

#2525 appears to be the original feature request, but does not say anything about this issue.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
C:\> git --version --build-options

git version 2.47.0.windows.1
cpu: x86_64
built from commit: d53e4648cb65eb75dd8d8a093d17400a18a9a15d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
```

(Same with the previous couple of versions too)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 11 22H2
```
C:\> cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.4169]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
C:\> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Tested a YubiKey "Security Key C NFC" (not to be confused with the YubiKey "5C NFC", which looks the same but has more features) and a Hypersecu "HyperFIDO Pro Mini"

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

`ssh-keygen -t ed25519-sk`, add the id_ed25519_sk.pub to github, gitlab, or "servername", `ssh servername`

 - What did you expect to occur after running these commands?

Prompt to touch security key, followed by ssh connection to server.

 - What actually happened instead?

ssh-sk-helper.exe crashed, there was no security key prompt, and the ssh connection did not complete.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No specific repository.

**Comment by peterh** [comment]
> That seems not exactly to be a supported scenario. Have you not installed this via the official installer? 

That one was installed by Corporate IT via... Software Center? Some automated deployment thing.

Trying on my personal machine (Windows 10 22H2) with the official 2.47.0 installer freshly downloaded from git-scm.com has the same result (and the same `shell-path: D:/git-sdk-64-build-installers/usr/bin/sh`, which is clearly something baked into the installer because I don't have a writable D:\)

> I ask because when I run ssh-keygen -t ed25519-sk from a regular Git Bash

Hmm. I use cmd.exe (configured for "Git from the command line and also from 3rd-paty software (Recommended)"), not Git Bash.

Using Git Bash works. Presumably because /usr/bin is on the path inside Git Bash.

Re-installing git and selecting "Use Git and optional Unix tools from the Command Prompt `Warning: This will override Windows tools like "find" and "sort".`" makes ssh work as expected with the security keys. But it also clobbers "find" and "sort"...

**Comment by dscho** [comment]
> I use cmd.exe

Could you see where that executable lives via `where ssh-keygen.exe`?

**Comment by peterh** [comment]
> Could you see where that executable lives via where ssh-keygen.exe?

It's not on the path. I have to specify the full path to ssh-keygen in order to run it.

I now believe that I'm "holding it wrong". If I'm specifying a full path, it's not really any more effort to open a Git Bash prompt for the rare occasion when I need to ssh-keygen (or ssh, for that matter).

Thanks for your attention, and sorry for the noise.

Background: What prompted me to open this is that a "git push" didn't work. But I can't reproduce the issue now. I suspect the problem was caused by my workaround of copying msys-*.dll files, and the issue only happened because stale msys-*.dll files were on the path after an upgrade of git.

**Comment by dscho** [comment]
> I suspect the problem was caused by my workaround of copying msys-*.dll files, and the issue only happened because stale msys-*.dll files were on the path after an upgrade of git.

That is very plausible.

The -sk helper lives in a _different_ directory than `msys-2.0.dll`, so the `PATH` matters (and Git Bash sets it up so that the MSYS2 DLL is found in the expected place).

Let's close this issue then, I'm glad that it works again on your side.
