### ISSUE TITLE
Git Bash on Windows misinterprets escape sequences

### ISSUE THREAD

**Issue by dmelikhov** [git-for-windows/git#5217]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.47.0.windows.1
cpu: x86_64
built from commit: d53e4648cb65eb75dd8d8a093d17400a18a9a15d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.22631.4317]
(c) Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: SublimeText
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable FSMonitor: Disabled
```

### Details
I'm writing a cross-platform nodejs script that executes bash commands. It should work the same way on Linux/MacOS/Windows, but on my Windows machine with Git Bash there seems to be an issue with escape sequences.

While trying out the [child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) function, I encountered a strange behavior that I was able to reproduce in Windows cmd.exe:

```
d:\>bash -c "echo $'this is \a test'"
this is  test

d:\>bash -c "echo $'this is \\a test'"
this is  test
```

The first output is expected, but in the second it looks like `\\a` is treated as the `\a` escape sequence.

Running the same commands in an interactive bash session yields correct results:

```
$ echo $'this is \a test'
this is  test

$ echo $'this is \\a test'
this is \a test
```

**Comment by dmelikhov** [comment]
Please also see related issue: https://github.com/google/zx/issues/873

**Comment by dmelikhov** [comment]
Thanks for your detailed answer, it's much more clear to me now.

> cmd.exe has entertaining quoting rules. In this particular case, you seem to assume that cmd.exe handles double-quoted parameters in the same way as Bash would. That is not so.

As I mentioned, the issue comes from the nodejs environment where I don't control quoting. But looking at the result, I guess the command-line built by the nodejs spawn function is identical to the one I was trying to run in cmd.exe.

In this case, would you suggest opening a bug report for nodejs? Because this code works differently on Linux and Windows:
```js
spawn(
    "echo $'this is \\\\a test'",
    [],
    { shell: "bash" } // assuming it's in path
);
```

> it is actually bash.exe that parses the command-line, and it does so differently from what you expect. If you pass four backslashes instead of just two, it will do what you expect. [...] you will need to experiment with quoting until you get the right result

What would be the universal way to quote a command? Does Bash see this argument (`"echo $'this is \\a test'"`) as a double quoted string? If so, should I look at [Double Quotes section in Bash Manual](https://www.gnu.org/software/bash/manual/bash.html#Double-Quotes) for quoting rules?

**Comment by dscho** [comment]
> the issue comes from the nodejs environment where I don't control quoting.

Well, to some extent, it _can_ be controlled, the [documentation](https://nodejs.org/api/child_process.html) mentions the `windowsVerbatimArguments` attribute.

> What would be the universal way to quote a command?

I am afraid that there is obviously no universal way, not if you want to use `shell: "bash"`. If you want to do that, you will need to have OS-specific code (i.e. alternate code paths depending on the value of [`process.platform`](https://nodejs.org/api/process.html#processplatform)).

Please do understand, though, that we have ventured _quite far_ away from what this here bug tracker is all about, which is to support _Git for Windows_. And while many a user seems to perceive Git for Windows as a convenient way to get a Linux-like environment on Windows, that is absolutely outside of what Git for Windows supports, and therefore I consider this here ticket as done.
