### ISSUE TITLE
wiki is throwing errors

### ISSUE THREAD

**Issue by end-user** [git-for-windows/git#5219]
Not a code bug, rather the wiki documentation on github appears to have errors in the rendering.

**Comment by dscho** [comment]
Thank you for the report! It seems that this is the regular [defacement](https://github.com/git-for-windows/git/wiki/_compare/ed85cfd1e861d787063c9422b60db010c3c242b5...de4dd01e6e7ca85eb27c985ff0c53874edab5886) we're suffering every once in a while:
![Image](https://github.com/user-attachments/assets/b0f1ef59-b94f-47c7-b86b-b3cc919a6cd9)

I am on it.

**Comment by dscho** [comment]
@end-user I force-pushed a previous state. Could you verify that it looks okay now for you? I have no idea what you looked at specifically, so I would not know whether you are referring to the same thing as I did. For the record, this is what I was seeing:

![Image](https://github.com/user-attachments/assets/5c4414b2-9304-412c-a47f-455c6ac557aa)

After my fix, it now looks like this:

![Image](https://github.com/user-attachments/assets/5b61d92b-6252-4318-9493-5393f22482c5)
