### ISSUE TITLE
Opening git-bash from git-gui and cd'ing to the root of the filesystem results in git-bash thinking it is at the top-level of the repo

### ISSUE THREAD

**Issue by solstice333** [git-for-windows/git#5234]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64
```
$ git --version --build-options

git version 2.45.0.windows.1
cpu: x86_64
built from commit: b5d0511969ccd9ab86395c37e5a7619d8b4e7c32
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? 10, 64
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3208]
```
 - What options did you set as part of the installation? Or did you choose the
   defaults? defaults, at least for the most part. See below.
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing? No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other? Bash
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
1. Open git-gui **from the Windows start menu**
2. In git-gui, click on `Open Existing Repository` and select an existing repo, or select any of the repos listed under `Open Recent Repository`
3. In git-gui, click on `Repository` in the top menu bar
4. Click on `Git Bash`
5. In git-bash, execute `cd /`
6. In git-bash, execute `git status` at the root of the filesystem
 - What did you expect to occur after running these commands?
```
fatal: not a git repository (or any of the parent directories): .git
```
 - What actually happened instead?
```
On branch foo
Your branch is up to date with 'origin/foo'.

nothing to commit, working tree clean
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
N/A

**Comment by dscho** [comment]
This probably means that `GIT_DIR` is still set. I'm not sure that this is Windows-specific behavior.

**Comment by solstice333** [comment]
@dscho oh yeah, you're right. I see `GIT_DIR` being set to the repo path that I select on the initial git-gui dialog (when opening git-gui from the start menu). I do not have a Linux machine available to me at the moment. Should I report this issue to [git@vger.kernel.org](mailto:git@vger.kernel.org) instead, and close this one?

**Comment by dscho** [comment]
I don't currently have a way to test Git GUI on Linux or macOS to verify that the issue isn't Windows-specific. Maybe report it to the Git mailing list (no HTML, please, it'll get dropped otherwise!) with the caveat that it may be specific to Windows, but if it isn't, ask for help?

**Comment by solstice333** [comment]
Ok, yeah, will do. Thanks for the redirection/guidance! I'll close this issue for now, but if it ends up being Windows-specific, I'll reopen it.
