### ISSUE TITLE
Winget doesn't get "Windows-only" releases

### ISSUE THREAD

**Issue by avandorp** [git-for-windows/git#5235]
Currently winget installs a broken version of Git for Windows. With Git for Windows v2.47.0.windows.2 several Windows only fixes were released. Unfortunately winget doesn't list and can't install that release:
`winget show git.git --versions --verbose
Git [Git.Git]
Version
--------
2.47.0
2.46.2
2.46.1
2.46.0
[...]`
`winget show git.git` gives URL and version of the v.2.47.0.windows.1 release as well. I'm not sure whether the release versioning scheme should be changed for winget to see new Windows-only releases or if some other meta data has to be changed.

**Comment by dscho** [comment]
Please understand that Git for Windows does not currently offer a Winget package. The package you got is maintainer by a third party. You need to take it up with them.

**Comment by avandorp** [comment]
Interesting. Your even mentioned as author in the winget package. Seems like anyone can put any meta data into winget... Will open an issue with winget.

**Comment by dscho** [comment]
> Your even mentioned as author in the winget package.

And so I am, the author of the software. But not the maintainer of the winget package.
