### ISSUE TITLE
Tab completion of git checkout terribly slow when looking for branches

### ISSUE THREAD

**Issue by jolar2** [git-for-windows/git#524]
A tab completion for "git checkout beginning_of_branch_name<tab_pressed_here>" on the same repository takes less than a second on linux with git version 2.3.6 but takes ~11 seconds with git version 2.6.3.windows.1 and the process seems to hang during this time.

If one adds -- to the command, e.g., git checkout -- beginning_of_file_name<tab_pressed_here>, the tab completion is fast, so pure file completion seems to be unaffected.

**Comment by dscho** [comment]
Could you `set -x` and tab complete again to see which command it hangs on?

**Comment by jolar2** [comment]
The set -x command gave interesting output. It seems as though the completion script does not hang but is actually working (although in total it is very slow compared to the Linux case). The repository in question in a very old CVS migrated repository with _many_ branches (more than 4000). If I remove many fetched branches, the completion goes faster.

I tried cloning other open source repositories, and in this case the tab completion is good enough to be of help, but there are not as many branches in these repositories. To summarize: The tab completion is working on Git for Windows, but it does not scale with many branches as well as it does on Linux because it is slower.

The short term solution here will probably be to archive the old branches on a new remote server. A long term solution, I guess, would involve timing in order to identify the bottle neck(s) and then one could attempt to optimize the process.

**Comment by dscho** [comment]
So if it really works, but is slow with many refs, did you call `git gc` at some point to pack the refs?

**Comment by jolar2** [comment]
Yes, but it is still slow.

**Comment by dscho** [comment]
@jolar2 you might want to spend a little time to come up with a repository that you can share via GitHub and that displays the slowness.

**Comment by linquize** [comment]
Do you install anti-virus? Anti-virus may make git-for-windows very slow

**Comment by jolar2** [comment]
I tried deactivating anti virus. I will do what @dscho says for an open source repository so that you can compare as well, but I am quite busy with other tasks. My plan is to make a script which creates random branches, and lots of random branches (4000 - 6000 should do) and then do the comparison again.

**Comment by kgybels** [comment]
@jolar2 When doing something like `git checkout t<TAB>` the bash completion will execute `__git_refs '' 1` defined in [git-completion.bash](https://github.com/git/git/blob/v2.6.3/contrib/completion/git-completion.bash#L337) to get all the candidate branches.

The part that becomes slow when you have lots of branches is the calls to `git for-each-ref` to get all the [references](https://github.com/git/git/blob/v2.6.3/contrib/completion/git-completion.bash#L356) and a second time for the [tracking branch](https://github.com/git/git/blob/v2.6.3/contrib/completion/git-completion.bash#L356) candidates.

@dscho Here is an MCVE to demonstrate:

    Kim@Kim-PC MINGW64 /c/git/bug
    $ git --version
    git version 2.6.3.windows.1
    
    Kim@Kim-PC MINGW64 /c/git/bug
    $ ls -a
    .  ..  steps.sh
    
    Kim@Kim-PC MINGW64 /c/git/bug
    $ cat steps.sh
    #!/bin/bash
    
    zerosha1=$(printf '%*s' 40 | tr ' ' 0)
    
    git init demo
    cd demo
    seq -f "$zerosha1 refs/remotes/origin/test%g" 10000 > .git/packed-refs
    
    echo Listing remote refs is fast:
    time git --git-dir=".git" for-each-ref --shell --format="ref=%(refname)" "refs/remotes/" | wc -l
    
    echo Listing remote refs in short format is slow:
    time git --git-dir=".git" for-each-ref --shell --format="ref=%(refname:short)" "refs/remotes/" | wc -l
    
    Kim@Kim-PC MINGW64 /c/git/bug
    $ ./steps.sh
    Initialized empty Git repository in C:/git/bug/demo/.git/
    Listing remote refs is fast:
    10000
    
    real    0m0.077s
    user    0m0.000s
    sys     0m0.000s
    Listing remote refs in short format is slow:
    10000
    
    real    0m5.282s
    user    0m0.015s
    sys     0m0.000s

Having lots of references under `refs/heads` will also become slow, but having them under `refs/remotes/origin` is even slower.

After playing around with the code, I found that most of the time is spend at checking if a [shortened  reference exists or not](https://github.com/git/git/blob/master/refs.c#L4495). The check causes lots of disk activity: lstats, etc. With procmon you can see that a lot of loose references are being checked for existence. Funny enough, with procmon monitoring active, the time goes up to 30s for my example.

Here are the timings for my linux box:

    kgybels@spaceball:~/bug/demo$ time git --git-dir=".git" for-each-ref --shell --format="ref=%(refname)" "refs/remotes/" | wc -l
    10000
    
    real    0m0.034s
    user    0m0.028s
    sys     0m0.004s
    kgybels@spaceball:~/bug/demo$ time git --git-dir=".git" for-each-ref --shell --format="ref=%(refname:short)" "refs/remotes/" | wc -l
    10000
    
    real    0m0.215s
    user    0m0.140s
    sys     0m0.072s

You can see that it's also a lot slower for the short format, but it doesn't balloon nearly as much as on Windows.

**Comment by jolar2** [comment]
Did you try this with a garbage collected repo or a repo where the refs existed as actual files?

**Comment by jolar2** [comment]
The same test on Linux vs Windows. I think you can easily tell which one is which OS:

$ time git --git-dir=".git" for-each-ref --shell --format="ref=%(refname:short)" "refs/remotes/" | wc -l
2750

real    0m0.055s
user    0m0.030s
sys     0m0.020s

$ time git --git-dir=".git" for-each-ref --shell --format="ref=%(refname:short)" "refs/remotes/" | wc -l
2750

real    0m1.341s
user    0m0.015s
sys     0m0.031s

**Comment by jolar2** [comment]
Allright, so if you want to reproduce the issue, just grab a random open source repository and create lots of branches. For example:

git clone https://github.com/bneumeier/binutils
# Make a branch copy of each tag
git tag | awk '{print $1 "_branch1 " $1}' | xargs -n 2 git branch
git tag | awk '{print $1 "_branch2 " $1}' | xargs -n 2 git branch
git tag | awk '{print $1 "_branch3 " $1}' | xargs -n 2 git branch
git tag | awk '{print $1 "_branch4 " $1}' | xargs -n 2 git branch

One may now try tab completion and compare performance between Linux/Windows.

**Comment by dscho** [comment]
The best way to provide the [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve) would be to add a perf test, as per https://github.com/git-for-windows/git/blob/master/t/perf/README

**Comment by jolar2** [comment]
After wandering around a bit in the t directory I notice that there is a completion test already called t9902-completion.sh. Perhaps one could copy this to the perf directory and convert it to a performance test without too much work? It would however be important to run the test against a repo with many branches/tags.

**Comment by dscho** [comment]
> there is a completion test already called t9902-completion.sh. Perhaps one could copy this to the perf directory and convert it to a performance test

The purpose of t9902 is to verify that the functionality of tab completion is provided correctly. It is unlikely that this would help us here, in particular since we already determined that the problem is not the tab completion per se: while *you* noticed the performance problem in tab completion, the bug is really not in the tab completion at all, but in the code that implements `--format="ref=%(refname:short)"`.

I would wager a bet that you would have a much easier time to write a new performance test from scratch, using bits and pieces from the surrounding shell scripts, that tests `--format="ref=%(refname:short)"` *specifically*.

**Comment by jolar2** [comment]
You are most likely correct about the writing from scratch part (I know next to nothing about the git source code), but I am however not fully convinced that all time is spent during that specific part, so I think one should also add a holistic tab completion test. I am not sure I can do this during office hours, but I will see what I can do.

**Comment by dscho** [comment]
> I am however not fully convinced that all time is spent during that specific part, so I think one should also add a holistic tab completion test.

@jolar2 if I were maintainer of Git proper, I would not accept such an "integration test" into the performance benchmarks, because it is way too difficult to analyze and fix performance regressions from such a test. Instead, I would insist on more specific performance tests, starting with the one I suggested earlier.

If tab completion is *still* slow after that, we will need to diagnose further, and add appropriate *additional* performance tests.

**Comment by dscho** [comment]
Good news! @peff just explained what the culprit is, and indicated the way forward: http://marc.info/?l=git&m=145458634210788&w=2

**Comment by jolar2** [comment]
Lovely! I am sorry I have not contributed with a performance test yet, but as long as the problem is solved, I am happy with that.

**Comment by dscho** [comment]
> I have not contributed with a performance test yet

We still need that. Like, really badly now.
