### ISSUE TITLE
Make portable version really portable

### ISSUE THREAD

**Issue by bviktor** [git-for-windows/git#525]
The current portable version needs install scripts to function that are run upon the first run of the git bash. I enclose the diff.

[gitdiff.txt](https://github.com/git-for-windows/git/files/31748/gitdiff.txt)

Portable should not be agnostic of the running environment, normally it behaves the same way for different users on different computers. Making one-time, persistent configuration changes to the install directory based on the current system is the opposite of this idea.

1. Git makes a copy of system files (such as hosts) in the install folder.
2. Git copies (or hardlinks) around a bunch of random binaries from mingw64/bin to mingw64/libexec/git-core.
3. Git generates "devices".

Making configuration changes based on the specific running system is fine, as long as it's

a) Only stored in memory for the lifetime of the session.
b) Stored in the specific environment. That means `%AppData%`, `%HOME%/.gitconfig` or something else under `%HOME%`.

Instead, current Git for Windows checks the current settings and files once on the first system it is run on, then makes changes to the **install** folder that you're supposed to carry around different computers.

1) Making a local copy of hosts (or any other system file) is troublesome. If it's used instead of the system-wide hosts, then it's bad because making changes to the system hosts will not be reflected later. If it's unused, then it's pointless to copy it. If I move this instance of Git to another computer, then it's just plain wrong because the system hosts may be completely different from the one carried over from the previous computer.

2) If those binaries really need to be there **twice**, then I think they'd have a better place in the package instead of copying them over at first run. OTOH if you put the same binaries in multiple folders, you could also use envvars to deal with that, or modify the binaries to look for them in these hardcoded folders. Actually, I'm not quite sure what the purpose of the current directory structure is. In Git1 there were 2 folders with executables, now you have at least 7. Was that really necessary? Apparently it makes eveyone's life harder.

3) Again, if it's needed for every instance, why script it? You can put it in the archive and be done with it. I was thinking that maybe these "devices" are agnostic of the current running instance but that can't be since they're only generated upon the first run, then the script responsible for these are even deleted permanently. Or if it really depends on the specific system it's being run on, then again, it's not portable.

We deploy Git Portable with robocopy from a read-only network share, so there's at least 3 paths where it's available: local path on the server (`S:\tools\git2`), network path on the server (`\\\whatever.domain\tools\git2`), and local path when synced to the workstation (`X:\whatever\path\they\use\tools\git2`). Besides, they're also pushed to Jenkins nodes with almost identical paths but different drive letters in some cases. So in this case, I have 2 choices with deployment:

a) Do a first-run on my local comp, "generate" a portable Git instance which reflects my local comp and its files like hosts, then deploy it on the network share. Then all nodes will get my system's environment.

b) Do not do a first-run. Then the scripts will be run the first time they're started on the other comps where it's robocopied to, and then after every time a robocopy (update) occurs because it will remove the newly generated files every time it's run, so Git will generate them again and it goes over and over.

I think we can agree that neither of these are desirable.

What's your take on this?

**Comment by dscho** [comment]
> Making a local copy of hosts (or any other system file) is troublesome. If it's used instead of the system-wide hosts, then it's bad because making changes to the system hosts will not be reflected later.

True. Could you please investigate where this file is used in MSys2?

> If those binaries really need to be there twice, then I think they'd have a better place in the package instead of copying them over at first run.

Please find the commit in `build-extra/` that explains why these files are copied (I am awfully short on time, sorry, otherwise I would spend the 5 minutes to find it and link to it myself).

> if it's needed for every instance, why script it?

There is no way to store hardlinks and symlinks in `.7z` files. That's why.
