### ISSUE TITLE
Problem installing git

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#526]
Hi when I download Git-2.6.3-64-bit and try to install it in the C:\Program Files folder I get the specified installation directory does not seem to be writable Please choose another directory or restart setup as a user with sufficient permission.

I reset my computer thinking it was my computer but it is the programme please fix it.

**Comment by paladox** [comment]
git 2.6.2 installs fine.

**Comment by davidovich** [comment]
It happened to me today, and I closed every explorer and re-ran. Seems that
Windows does it's thing with keeping file handles around.

**Comment by paladox** [comment]
Yes i even went to resetting the computer but that didn't work. It is the program because git 2.6.2 installs perfectly in that directory.

**Comment by dscho** [comment]
Could you try to uninstall Git 2.6.2 completely, then *remove* `C:\Program Files\Git` manually and then install Git 2.6.3?

**Comment by paladox** [comment]
Yes I have I reset my whole computer meaning everything to default or files and programmes deleting everything the default and still happends. I am running Windows 10 64-but may be because I use a Microsoft account not a local account but not sure about that. But git 2.6.2 installs got 2.6.3 doesn't. It will install in a different location which it suggests in git 2.6.3 but won't install in the programs folder.

**Comment by linquize** [comment]
See also #528

**Comment by dscho** [comment]
> I have I reset my whole computer meaning everything to default or files and programmes deleting everything

No, resetting the computer just restarts the Operating System, it does not reset anything to default settings.

> git 2.6.2 installs got 2.6.3 doesn't. It will install in a different location

In which location does it install? Did 2.6.1 install?

**Comment by paladox** [comment]
I mean I click on reset to default meaning it reinstalls the os and deletes all files including personal and programes.

**Comment by dscho** [comment]
Fixed by git-for-windows/build-extra@23672af723da18e5bc3c679e52106de3c2dec55a
