### ISSUE TITLE
Problems with v2 git bash and node

### ISSUE THREAD

**Issue by ihinckle** [git-for-windows/git#529]
I am not sure how to provide logs for this kind of issue. If someone could instruct me to get some for them I would be more than happy to. The first issue that I am seeing is when running 'npm init', it takes me through all the steps but then hangs after I confirm the changes and does not exit back to accept input again until I have pressed 'ctrl+c'.

The second issue I have noticed is that when running 'npm search <package>' the results are terribly formatted and impossible to decipher.

I have attempted this across versions of node 5, 4.2, and 0.12. All provide the same results.

If anyone has any steps for me to provide more information I will do it.

**Comment by nalla** [comment]
did you try `winpty npm`?

**Comment by dscho** [comment]
@ihinckle Additionally (or alternatively) to @nalla's comments, you might want to reinstall Git and choose the default Windows console for *Git Bash* instead of the MinTTY one.
