### ISSUE TITLE
Git timeout with VPN

### ISSUE THREAD

**Issue by kmelia** [git-for-windows/git#530]
Hi,

When I am working with a VPN Cisco (on Windows), some git commands has timeout.
It is very very strange ;-)

***Explaination:***
The git status command has no timeout, run on 0.065 second
```sh
$ export GIT_TRACE=1 && time git status
10:59:06.348991 git.c:348               trace: built-in: git 'status'
On branch develop
Your branch is ahead of 'origin/develop' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

real    0m0.065s
user    0m0.000s
sys     0m0.015s
```
But the git diff command has a timeout of **21 seconds**!
```sh
$ export GIT_TRACE=1 && time git diff
10:59:25.621991 git.c:348               trace: built-in: git 'diff'
10:59:25.628991 run-command.c:338       trace: run_command: 'less'

real    0m21.072s
user    0m0.000s
sys     0m0.015s
```

If you have an idea, I can test some stuff for you.

**Comment by dscho** [comment]
`git diff` has no timeout.

Your best bet is to follow the [wiki page on debugging Git](https://github.com/git-for-windows/git/wiki/Debugging-Git) and interrupt with Control-C the `git diff` call in `gdb` while it spends those 21 seconds doing something dubious.

**Comment by kmelia** [comment]
> Your best bet is to follow the wiki page on debugging Git

I will try this on monday at work! Thanks.

**Comment by kmelia** [comment]
It's very hard to get simple and real results. Sometimes it works?!
