### ISSUE TITLE
Running `git shortlog --summary --numbered --all --no-merges` outside of a repository triggers a segmentation fault

### ISSUE THREAD

**Issue by MatejKafka** [git-for-windows/git#5301]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.47.0.windows.1
cpu: x86_64
built from commit: d53e4648cb65eb75dd8d8a093d17400a18a9a15d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.5198]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Not relevant.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Not relevant.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git shortlog --summary --numbered --all --no-merges
```
 - What did you expect to occur after running these commands?

Show error that I'm not in a repository.

 - What actually happened instead?

Segmentation fault (git exits with code 0xC0000005). Note that this does not happen on Linux.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not applicable.

**Comment by dscho** [comment]
> Segmentation fault (git exits with code 0xC0000005). Note that this does not happen on Linux.

Oh, but it does.

The fix is in https://github.com/git/git/commit/b33001645e9a1b042f5bc843b76e0e8a28a91223, which is slated for Git v2.48.0, but has not been included in Git v2.47.1 for some reason or other.

**Comment by MatejKafka** [comment]
Ah, apologies, apparently I have an older version of Git in my WSL.

**Comment by dscho** [comment]
@MatejKafka could you please test https://github.com/git-for-windows/git/releases/tag/v2.48.0-rc0.windows.1?

**Comment by MatejKafka** [comment]
Yes, I can confirm that the issue is fixed on latest rc.
