### ISSUE TITLE
unable to resolve domains when invoking SSH

### ISSUE THREAD

**Issue by shiftkey** [git-for-windows/git#532]
My Setup:

 - VMWare Fusion (I have Professional Version 7.1.2 (2779224) - but I know this isn't the latest version)
 - Windows 8.1
 - Internet Sharing enabled for the Network Adapter 
 - Git for Windows 2.6.3 (system installed, not Portable)

Trying a simple SSH command:

```
shiftkey@WIN-P38A613P7N9 MINGW64 ~
$ nslookup github.com
Server:  UnKnown
Address:  172.16.233.2

Name:    github.com.localdomain
Addresses:  192.30.252.129
          192.30.252.129

shiftkey@WIN-P38A613P7N9 MINGW64 ~
$ ssh -T git@github.com -vvv -o LogLevel=DEBUG3
OpenSSH_7.1p1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /etc/ssh/ssh_config
ssh: Could not resolve hostname github.com: Non-recoverable failure in name resolution
```

I believe this is related to receiving a `github.com.localdomain` record. And given the big bump in OpenSSH I think there's something in there we're looking for. It's been [reported elsewhere](https://communities.vmware.com/message/2551583) but I'm unsatisfied with how that ended, so I'm still digging into it.

**Workaround:** You can switch the networking adapter over to **Bridge Networking** and then `nslookup` behaves as expected (no `.localdomain` records returned).

For reference, here's the output from Git 1.9.x (the `ssh_config` mentions are just [this file](https://github.com/github/msysgit/blob/devel/etc/ssh/ssh_config)):

```
$ nslookup github.com
Server:  UnKnown
Address:  172.16.233.2

Name:    github.com.localdomain
Addresses:  192.30.252.131
          192.30.252.131

$ ssh -T git@github.com -vvv -o LogLevel=DEBUG3
OpenSSH_6.6.1, OpenSSL 1.0.1i 6 Aug 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 1: Applying options for *
debug1: /etc/ssh/ssh_config line 5: Applying options for github.com
debug2: ssh_connect: needpriv 0
debug1: Connecting to github.com [192.30.252.129] port 22.
debug1: Connection established.
...
```

I'm going to dig into this a bit and see if I can understand what OpenSSH is complaining about. Just wanted it logged for posterity.

**Comment by dscho** [comment]
Related to https://github.com/git-for-windows/git/issues/297 maybe?

**Comment by shiftkey** [comment]
Looks very, very similar. I'll close this one in favour of that (and thanks for reminding me!)
