### ISSUE TITLE
When $TERM is set to 'msys', git-bash with mintty has several issues

### ISSUE THREAD

**Issue by gmahomarf** [git-for-windows/git#535]
OS: Win 10 (Version 10.0.10240)
Git: 2.6.3.windows.1

I just installed git for windows 2.6.3 x64. I ran git bash and immediately noticed several issues:

- Anything that involves moving the cursor (except typing) causes weird display behavior
    * Backspace apparently inserts spaces, while in reality it removes the last character from the buffer. (e.g. `ld<backspace>s` results in `ld s` visually, but if I hit enter, `ls` is run as expected)
    * Using the arrow keys to move left or right shows no feedback that the cursor has moved, and when typing after moving, it redraws from the inserted character to the end of the buffer. (e.g. `git cone <left*4>` results in `git cone lone`, and hitting enter correctly runs `git clone`)
- Color output from commands (e.g. `ls`) does not work
- `clear` fails with `'msys': unknown terminal type.` (this is how I figured out the issue).
- Running vi(m) results in `E437: terminal capability "cm" required Press ENTER or type command to continue` and draws the vim interface like so (you can still edit if you mentally keep track of the cursor):

![vim screenshot](http://i.snag.gy/6dkF6.jpg)

Those are all the issues I've found so far. Chances are there are others. As soon as I set $TERM to xterm, everything worked fine. Maybe that should be the default? For now, I've added an `export TERM=xterm` call to the end of my `.bashrc` and that allows me to use it properly.

**Comment by dscho** [comment]
The default *is* `TERM=xterm`. I suspect that you hardcoded `TERM` in your environment, or that you start Git Bash differently than via the Start Menu.

**Comment by gmahomarf** [comment]
My bad. Not sure what or who (it sure wasn't me...) added TERM to my user env vars on Windows. I'm also not sure why it wasn't an issue before I upgraded to 2.6.3. Oh well.

/me shrugs

Closing this. Thanks, and sorry for the false issue.

**Comment by dscho** [comment]
@gmahomarf no worries! As far as I am concerned, you did exactly the right thing.
