### ISSUE TITLE
Switch to stable version of gitflow-avh

### ISSUE THREAD

**Issue by hameno** [git-for-windows/git#536]
Currently git-for-windows ships with a (possibly buggy) development version of gitflow-avh. Also there is already a stable release which is newer than the shipped dev version.

**Comment by rimrul** [comment]
I've written a comment on this in #349, just as @hameno mentioned this new Ticket. For those who are Interessted, here is the main part:

>Basically there are 7 steps:
* Download and install the [Git for Windows SDK](https://github.com/git-for-windows/build-extra/releases)
* Fork the [MSYS2-Packages Repo](https://github.com/Alexpux/MSYS2-packages/)
* Edit the [git-flow PKGBUILD](https://github.com/Alexpux/MSYS2-packages/blob/master/git-flow/PKGBUILD) to use the master branch
* [Rebuild the Package](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages)
* Test the Package

**Comment by anb0s** [comment]
I'm using git-flow too and want to give a try (at Saturday, 21.11.15) to test the stable version 1.9.1.
I cannot assign myself, so my question @hameno and others interested: if you want start earlier, please inform...

**Comment by anb0s** [comment]
Updated package meta to use master branch --> version 1.9.1 of git-flow. Tested git-flow locally with some feature and release branches.

thanks @rimrul for the clear steps, just one step i missed, but found with google:
how to use locally builded package: inside the package folder just run "makepkg -i" or if you have more than one builded "pacman -U pkgname-pkgver.pkg.tar.xz"
P.S.: First i used "pacman -S git-flow", but it installs the "old" version, i know yet because of online install from repository :)

**Comment by anb0s** [comment]
Created pull request: https://github.com/Alexpux/MSYS2-packages/pull/392

Are there more steps to do for include it in Git for Windows?

Thanks.

**Comment by rimrul** [comment]
>Created pull request: Alexpux/MSYS2-packages#392
Are there more steps to do for include it in Git for Windows?

Yes. It's got to be merged and uploaded to the package repository. I don't think there are steps reguired in the code of Git for Windows though. After that I think @dscho can close this issue.

**Comment by dscho** [comment]
Precisely. As I always update the Pacman packages before releasing a new Git for Windows, and as the [x86_64](http://repo.msys2.org/msys/x86_64/git-flow-1.9.1-1-x86_64.pkg.tar.xz) and the [i686](http://repo.msys2.org/msys/i686/git-flow-1.9.1-1-i686.pkg.tar.xz) packages were already uploaded, this ticket is addressed.

The next Git for Windows release will ship with Git Flow v1.9.1.

@anb0s thank you so much. It has been a very welcome pleasure to receive your contribution!

**Comment by anb0s** [comment]
It's included in 2.6.4 now: 1.9.1 (AVH Edition)
