### ISSUE TITLE
setup-git-sdk.bat fails in Git For Windows SDK 1.0.1 installer

### ISSUE THREAD

**Issue by Astrophizz** [git-for-windows/git#537]
The installer fails in setup-git-sdk.bat with this written to the terminal:
```
:: Synchronizing package databases...
 git-for-windows         2000.0   B  1953K/s 00:00 [#####################] 100%
 mingw32                  215.3 KiB  1764K/s 00:00 [#####################] 100%
 mingw32.sig               96.0   B  0.00B/s 00:00 [#####################] 100%
      0 [main] pacman 15144 C:\git-sdk-64\usr\bin\pacman.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
   6138 [main] pacman 15144 cygwin_exception::open_stackdumpfile: Dumping stack trace to pacman.exe.stackdump
      0 [main] pacman 2500 fork: child -1 - forked process 15144 died unexpectedly, retry 0, exit code 0x100, errno 11
error: GPGME error: Invalid crypto engine
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
 mingw64                  214.2 KiB  1713K/s 00:00 [#####################] 100%
 mingw64.sig               96.0   B  93.8K/s 00:00 [#####################] 100%
error: GPGME error: Invalid crypto engine
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
 msys                     126.2 KiB  3.85M/s 00:00 [#####################] 100%
 msys.sig                  96.0   B  0.00B/s 00:00 [#####################] 100%
error: GPGME error: Invalid crypto engine
error: failed to update msys (invalid or corrupted database (PGP signature))
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

There was a problem accessing the MSys2 repositories
If your setup requires an HTTP proxy to access the web,
please specify it here, otherwise leave it empty.

HTTP proxy:
```
which would appear to come from this line:
[`@"%cwd%"\usr\bin\pacman -Sy --needed --force --noconfirm msys2-runtime`](https://github.com/git-for-windows/build-extra/blob/94e0b94ae0e7c994930171e8536e5955b5201f53/sdk-installer/setup-git-sdk.bat#L68)

Here is the stack trace mentioned by the error output, if it's any use:
```
Stack trace:
Frame        Function    Args
00000000000  0018007198E (0018020EF9C, 0018020EE46, 00000400000, 000005FEDE0)
00000000000  00180046E22 (000005FFE48, 000006E482C, 000005FFE90, 00000002000)
00000000000  00180046E62 (00000600000, 00000800000, 00000400000, 00000600000)
00000000000  0018004705B (00000277000, 000005FFEE0, 00000000000, 001801E78C0)
00000000000  001800470AA (00000000000, 00100401000, 00000277000, 00000000000)
00000000000  0018004717E (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001007452D1 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
00000000000  7FFD2EA28102 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFD2EB8C264 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

Running the pacman command by hand after the fact appears to work fine:
```
C:\git-sdk-64\usr\bin>pacman -Sy --needed --force --noconfirm msys2-runtime
:: Synchronizing package databases...
 git-for-windows is up to date0   B  0.00B/s 00:00 [---------------------]   0%
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) msys2-runtime-2.2.1.33619.e87aaa7-1

Total Download Size:   2.27 MiB
Total Installed Size:  8.42 MiB

:: Proceed with installation? [Y/n]
warning: no /var/cache/pacman/pkg/ cache exists, creating...
:: Retrieving packages ...
 msys2-runtime-2.2.1...     2.3 MiB   542K/s 00:04 [#####################] 100%
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
(1/1) installing msys2-runtime                     [#####################] 100%
```

I've reproduced this on two different machines. Both have Windows 10 x64 with the recent, large "Version 1511" November update applied.

**Comment by dscho** [comment]
Hmm. This is obviously 64-bit, but it looks pretty much like the 32-bit problem I worked around in git-for-windows/build-extra@918a119f993fe5d43638e11efd1f5897cc891bfc...

**Comment by dscho** [comment]
@Astrophizz could you please unpack the SDK manually, change the line 19 from

```cmd
@IF MINGW32 == %MSYSTEM% @(
```

to 

```cmd
@IF MINGW64 == %MSYSTEM% @(
```

and then run `setup-git-sdk.bat` in a `cmd` window manually and report back whether this fixes the problem?

**Comment by dscho** [comment]
@Astrophizz and if it does not, could you have a look at the ticket @elieux referenced?

**Comment by Astrophizz** [comment]
@dscho That worked! Would you like a pull request to remove the check against MINGW32?

The next thing that fails in the SDK installer is the installation of 3 packages that don't seem to be in the pacman repo (anymore?):
* git-extra
* mingw-w64-x86_64-git-doc-html
* mingw-w64-x86_64-git
I've opened an issue at #548.

**Comment by dscho** [comment]
> That worked (editing the line)! Would you like a pull request to remove the check against MINGW32?

No, this was just a work-around. The real fix is to remove the extra level testing for MINGW32. If you could open a Pull Request with *that* change (with a [good commit message](https://github.com/git-for-windows/git/wiki/Good-commits#commit-messages), please), that would be awesome!

**Comment by Astrophizz** [comment]
Right, that's what I meant. I'll try to get that ready soon.

After generating a 7z installer for #548 it occurred to me to test this fix from an installer and, sadly, it still fails in that context. Extracting the archive and running `setup-git-sdk.bat` does work though. I'm puzzled as to why that would make a difference.

**Comment by dscho** [comment]
I guess it might have something to do with the `.7z` self-extractor being a 32-bit executable itself. Not sure how to verify that, though (or how to work around it if that is the case).

**Comment by Astrophizz** [comment]
I've made a pull request with #90.

**Comment by chapulin2760-art** [comment]
> El instalador falla en setup-git-sdk.bat con esto escrito en la terminal:
> 
> ```
> :: Synchronizing package databases...
>  git-for-windows         2000.0   B  1953K/s 00:00 [#####################] 100%
>  mingw32                  215.3 KiB  1764K/s 00:00 [#####################] 100%
>  mingw32.sig               96.0   B  0.00B/s 00:00 [#####################] 100%
>       0 [main] pacman 15144 C:\git-sdk-64\usr\bin\pacman.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
>    6138 [main] pacman 15144 cygwin_exception::open_stackdumpfile: Dumping stack trace to pacman.exe.stackdump
>       0 [main] pacman 2500 fork: child -1 - forked process 15144 died unexpectedly, retry 0, exit code 0x100, errno 11
> error: GPGME error: Invalid crypto engine
> error: failed to update mingw32 (invalid or corrupted database (PGP signature))
>  mingw64                  214.2 KiB  1713K/s 00:00 [#####################] 100%
>  mingw64.sig               96.0   B  93.8K/s 00:00 [#####################] 100%
> error: GPGME error: Invalid crypto engine
> error: failed to update mingw64 (invalid or corrupted database (PGP signature))
>  msys                     126.2 KiB  3.85M/s 00:00 [#####################] 100%
>  msys.sig                  96.0   B  0.00B/s 00:00 [#####################] 100%
> error: GPGME error: Invalid crypto engine
> error: failed to update msys (invalid or corrupted database (PGP signature))
> error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
> error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
> error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
> 
> There was a problem accessing the MSys2 repositories
> If your setup requires an HTTP proxy to access the web,
> please specify it here, otherwise leave it empty.
> 
> HTTP proxy:
> ```
> 
> que parecería provenir de esta línea: [`@"%cwd%"\usr\bin\pacman -Sy --needed --force --noconfirm msys2-runtime`](https://github.com/git-for-windows/build-extra/blob/94e0b94ae0e7c994930171e8536e5955b5201f53/sdk-installer/setup-git-sdk.bat#L68)
> 
> Aquí está el seguimiento de la pila mencionado por la salida de error, si es de alguna utilidad:
> 
> ```
> Stack trace:
> Frame        Function    Args
> 00000000000  0018007198E (0018020EF9C, 0018020EE46, 00000400000, 000005FEDE0)
> 00000000000  00180046E22 (000005FFE48, 000006E482C, 000005FFE90, 00000002000)
> 00000000000  00180046E62 (00000600000, 00000800000, 00000400000, 00000600000)
> 00000000000  0018004705B (00000277000, 000005FFEE0, 00000000000, 001801E78C0)
> 00000000000  001800470AA (00000000000, 00100401000, 00000277000, 00000000000)
> 00000000000  0018004717E (00000000000, 00000000000, 00000000000, 00000000000)
> 00000000000  001007452D1 (00000000000, 00000000000, 00000000000, 00000000000)
> 00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
> 00000000000  7FFD2EA28102 (00000000000, 00000000000, 00000000000, 00000000000)
> 00000000000  7FFD2EB8C264 (00000000000, 00000000000, 00000000000, 00000000000)
> End of stack trace
> ```
> 
> Ejecutar el comando pacman manualmente después del hecho parece funcionar bien:
> 
> ```
> C:\git-sdk-64\usr\bin>pacman -Sy --needed --force --noconfirm msys2-runtime
> :: Synchronizing package databases...
>  git-for-windows is up to date0   B  0.00B/s 00:00 [---------------------]   0%
>  mingw32 is up to date
>  mingw64 is up to date
>  msys is up to date
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (1) msys2-runtime-2.2.1.33619.e87aaa7-1
> 
> Total Download Size:   2.27 MiB
> Total Installed Size:  8.42 MiB
> 
> :: Proceed with installation? [Y/n]
> warning: no /var/cache/pacman/pkg/ cache exists, creating...
> :: Retrieving packages ...
>  msys2-runtime-2.2.1...     2.3 MiB   542K/s 00:04 [#####################] 100%
> (1/1) checking keys in keyring                     [#####################] 100%
> (1/1) checking package integrity                   [#####################] 100%
> (1/1) loading package files                        [#####################] 100%
> (1/1) checking for file conflicts                  [#####################] 100%
> (1/1) checking available disk space                [#####################] 100%
> (1/1) installing msys2-runtime                     [#####################] 100%
> ```
> 
> He reproducido esto en dos equipos diferentes. Ambos tienen Windows 10 x64 con la reciente y extensa actualización de noviembre "Versión 1511".

https://github.com/git-for-windows/git/issues/537#issue-117980503
