### ISSUE TITLE
Cryptic error message "unable to join threaded lstat"

### ISSUE THREAD

**Issue by veita** [git-for-windows/git#538]
It happens with various commands that Git issues the error "unable to join threaded lstat". At least in some cases `git config core.preloadIndex false` or `git config --global core.preloadIndex false` can solve that issue.

Please provide a more user-friendly error message that helps users solving the problem.

Git for Windows v2.6.3
git version 2.1.4

Also see https://issues.jenkins-ci.org/browse/JENKINS-31644

**Comment by dscho** [comment]
Thank you for your bug report.

> Git for Windows v2.6.3
> git version 2.1.4

Unfortunately, this makes little sense.

> It happens with various commands that Git issues the error "unable to join threaded lstat".

Please provide more background about your setup, in particular about your repository/worktree. How many files/directories are there, how many revisions, which exact commands, what is the exact error message, is this on NTFS or FAT or something else entirely? Which Windows version? What architecture?

You see, the problem is that I cannot reproduce the issue here (in fact, your report is the *first time* I saw that error message). So I marked this ticket as requiring a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve). Hopefully we can move this ticket forward together!

**Comment by linquize** [comment]
Is such feature considered experimental?

**Comment by dscho** [comment]
@linquize if you refer to `core.preloadindex` (please ask more precise questions, this would help me a lot), then: yes.

**Comment by veita** [comment]
>> Git for Windows v2.6.3
>> git version 2.1.4
>
> Unfortunately, this makes little sense.

OK. I've recently uninstalled MSysGit and installed Git for Windows. The first version number is the version from the ReleaseNotes.html. The second is the version that is displayed at the Windows cmd prompt. If the two numbers must match, there must be another version of Git present on the system. I will investigate this further.

OS: Windows Server 2012 with NTFS
The repository size is about ~230 MB.

**Comment by dscho** [comment]
> If the two numbers must match, there must be another version of Git present on the system.

Yes, they must.

Git for Windows 2.1.4 was never officially released, although msysGit (i.e. the *development environment* of Git for Windows 1.x) managed to compile 2.1.4 within the old environment. Maybe that's what you got. `git --exec-path` might give you more of a clue there.

**Comment by dscho** [comment]
> there must be another version of Git present on the system

FWIW you should be able to figure out where this Git comes from by running

```cmd
git --exec-path
```

Could you do that, please, and report back your findings?

**Comment by veita** [comment]
It turned out that there was another Git installation (Cygwin) on the server. The binary was executed when Git was called from the Windows command prompt, and by Jenkins (but not from MinTTY). This produced the error message. With Git for Windows v2.6.3 the error message cannot be reproduced with the same repository. Sorry for this misinformation.

However, the "unable to create threaded lstat" message is located in https://github.com/git-for-windows/git/blob/master/preload-index.c and might show up under different circumstances.

**Comment by dscho** [comment]
> the "unable to create threaded lstat" message is located in https://github.com/git-for-windows/git/blob/master/preload-index.c and might show up under different circumstances.

That is true. And until it does show up under different circumstances, I would like to take care of other bug reports ;-)
