### ISSUE TITLE
Sign the uninstaller, too

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#540]
InnoSetup has a helpful option to sign the uninstaller, let's use that option. Of course, while at it, we could use InnoSetup's option to sign the installer instead of doing that manually, afterwards. So let's do that, too.

**Comment by shiftkey** [comment]
![](https://cloud.githubusercontent.com/assets/359239/11320499/c49e37c2-904e-11e5-97e9-1d2fa23ee9c7.gif)

**Comment by dscho** [comment]
@shiftkey LOL. You crack me up ;-)

**Comment by dscho** [comment]
Fixed via https://github.com/git-for-windows/build-extra/commit/2871154b8dcd862b4a3295269d625864f9e799e3
