### ISSUE TITLE
"git add -p" displays a perl locale warning

### ISSUE THREAD

**Issue by agwells** [git-for-windows/git#541]
Hi all,

I'm running git version 2.6.3.windows.1, on Windows 10 Pro, 64 bit, having installed via the Windows installer on https://git-for-windows.github.io/. This was an upgrade from a previous version, although unfortunately I can't recall exactly what my old version number was (I think 2.4 or less).

I'm finding that, out of the box, when I run "git add -p", I see the following warning message from perl:

```
aaron@aadell14 MINGW64 ~/Documents/GitHub/DotDash Keyboard (styling-take-2)
$ git add -p
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = (unset),
        LANG = "en"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
diff --git a/res/values/style.xml b/res/values/style.xml
index 8bd9647..28f6348 100644
--- a/res/values/style.xml
+++ b/res/values/style.xml
@@ -39,25 +39,25 @@
         <item name="android:layout_marginBottom">20dp</item>
     </style>

-    <style name="dotdash_ics">
```

The git add program works fine after showing the warning. And I was able to get rid of this warning on my machine but creating a .bashrc file with `export LANG="en_US.UTF-8"` in my home directory. So, it's hardly a severe issue, but I thought I'd let you know. :)

To replicate:
1. Install Git for Windows 2.6.3
2. Open a git bash session.
2. `cd` into a git workspace.
3. Run `git add -p`

Expected result: Runs `git add` in interactive mode
Actual result: Displays a perl warning, and then runs `git add` in interactive mode.

**Comment by dscho** [comment]
I do not receive this warning at all here.

Possible clue: when I run `echo $LANG`, it outputs `en_US.UTF-8` here, and `echo $LC_ALL` is also empty, as for you.

Maybe your environment set this `LANG` variable to an incomplete one, i.e. `en` instead of `en_US.UTF-8`?

**Comment by agwells** [comment]
Yes, my LANG in bash for git was "en" after installation. I didn't manipulate it myself, though, so I don't know how it got set to that.

Is there code in the installer that sniffs the Windows locale setting and bases LANG on that? My Windows locale is "English (New Zealand)", which is probably an unusual one; maybe the installer didn't recognize it so it fell back to "en"?

**Comment by dscho** [comment]
> Yes, my LANG in bash for git was "en" after installation.

The question is: where? Is it in your user environment (This PC>Properties>Advanced system settings>Environment Variables...)? Or did something touch your `$HOME/.bashrc`? Or yet another thing that changes your environment?

> Is there code in the installer that sniffs the Windows locale setting and bases LANG on that?

No.

There is code in Git Bash's startup section that "sniffs" whether there is a `LANG` variable and leaves it alone if there is already one:

```sh
# if no locale variable is set, indicate terminal charset via LANG
test -z "${LC_ALL:-${LC_CTYPE:-$LANG}}" && export LANG=$(/usr/bin/locale -uU)
```

But maybe `/usr/bin/locale -uU` prints `en` in your setup?

**Comment by agwells** [comment]
Thanks, I'm away from my Windows machine at the moment but I'll try to remember to check those when I get home this evening.

**Comment by agwells** [comment]
Yep, turns out I had a Windows environment variable with "LANG" set to "en". Not sure where that came from, but I have installed a lot of software on this machine over the years, so it may be leftover from something I did earlier.

**Comment by dscho** [comment]
@agwells okay, thanks! BTW feel free to close tickets you opened when you feel they are addressed.
