### ISSUE TITLE
Git pull and push commands never end

### ISSUE THREAD

**Issue by liayn** [git-for-windows/git#543]
On most calls of pull and push (via git bash) the commands never end, but mostly finish their work.
I have to CTRL+C the command and reissue it, then it can finish almost always.

I suspect some locking or so that hinders the commands to finish the first time, but that's just a blind guess.

Example:
```
Markus@klein-lap MINGW64 /c/.../shariff-backend-php (composerimprovements)
$ git push my
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 358 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
```
It hangs here.

I'm using git version 2.6.3.windows.1 on Windows 10 Pro 64bit

**Comment by dscho** [comment]
@liayn thank you for your bug report.

As you probably guess, though, this does not happen here, otherwise I would certainly never have released that Git for Windows version.

So it must be a quirk in your setup that causes this.

I could imagine that more light would be shed into this issue if you set the environment variable `GIT_TRACE=1` before running `git push my`.

**Comment by liayn** [comment]
Afaik I nothing special in my setup here. I will add the `GIT_TRACE` to my `.bash_profile` and report back, once I know more. Thanks for your fast respone.

**Comment by liayn** [comment]
```
$ git pg
15:37:59.491242 git.c:560               trace: exec: 'git-pg'
15:37:59.491242 run-command.c:343       trace: run_command: 'git-pg'
15:37:59.491242 git.c:282               trace: alias expansion: pg => 'push' 'origin' 'HEAD:refs/publish/master'
15:37:59.507376 git.c:348               trace: built-in: git 'push' 'origin' 'HEAD:refs/publish/master'
15:37:59.510879 run-command.c:343       trace: run_command: 'C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe' '-p' '29418' 'someuser@review.typo3.org' 'git-receive-pack '\''/Packages/TYPO3.CMS.git'\'''
15:38:01.395930 run-command.c:343       trace: run_command: '.git/hooks/pre-push' 'origin' 'ssh://someuser@review.typo3.org:29418/Packages/TYPO3.CMS.git'
15:38:01.461960 git.c:348               trace: built-in: git 'rev-list' '-n' '1' '--grep' '\[SECURITY\]' 'origin/master..a8500ff05d36c9c528a0b344d7ef499c88e8e028'
15:38:01.480596 run-command.c:343       trace: run_command: 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
15:38:01.502237 git.c:348               trace: built-in: git 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
Counting objects: 19, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (19/19), 1.39 KiB | 0 bytes/s, done.
Total 19 (delta 15), reused 0 (delta 0)
remote: Resolving deltas: 100% (15/15)
remote: Processing changes: new: 1, refs: 1, done
```

Had the issue now again. As you can see the trace output is not really helpful. The push completed successfully on the server (Gerrit).

**Comment by dscho** [comment]
> As you can see the trace output is not really helpful.

What I can see is a wealth of information to which I had no access before.

A couple of gems:

- The push uses `TortoisePLink.exe`. We had tons of problems with `plink`, so a very valid idea is to test with OpenSSH instead.
- it is run via an alias (which might cause problems).
- a pre-push hook is run. If written improperly, this hook might pretend to end but block the overall push from finishing. To test whether this is true, a push from a different repository should be performed, taking pains *not* to enable the same pre-push hook (it might be copied via the templates upon `git init` or `git clone`).
- It pushes to Gerrit. To exclude Gerrit from the list of suspects, a different push should be performed, taking pains *not* to push to *another* Gerrit instance but a regular OpenSSH one. This could be done e.g. by using [Vagrant](https://github.com/git-for-windows/git/wiki/Vagrant) and installing an OpenSSH server, but that can be admittedly tricky if you have never done that before.
- the `remote: Processing changes` is not produced by Git itself. It may be a tell-tale of a post-receive hook on the server side that is blocking the client from finishing.

**Comment by liayn** [comment]
Hey!

* I actually like tortoisegit a lot, which uses plink of course, so I want to avoid running two key agents in parallel
* aliases can cause problems??? Sorry I don't get that. If that is an issue, then there is some serious problem in the handling/parsing of parameters I would say.
* The pre-push hook was added only a week ago. The problems were the same before, so I can rule that one out.
* Since this does not happen on every push and I mostly push to gerrit, I'll try to capture the next push to a normal repo.
* I know that this is a remote message and I since the push actually seems to finish on the server side (the commit shows up on gerrit properly), I suspect some lowlevel issue. That's why I said "the output is not really helpful", as there is no trace what happens at the low level.

**Comment by dscho** [comment]
@liayn I disagree that the output is not really helpful. It clarified a lot that you left unclear before.

Also, with the information I gave you, I believe you are more than just well equipped to diagnose the underlying problem.

**Comment by liayn** [comment]
My conclusion so far is that the issue must be something with closing down the connection (either by the remote or local), since the actual job seems to succeed.

It would be nice of you, @dscho, if you could elaborate a bit more on your concerns about aliases and how this should relate to the communication problem, which it obviously is.

**Comment by dscho** [comment]
> concerns about aliases and how this should relate to the communication problem

The more obvious things to test are pushes from repositories without the hook, and to remote repositories that are not Gerrit instances.

**Comment by dscho** [comment]
(I meant to say: to test *first*)

**Comment by liayn** [comment]
I did more tests now, pushed to various systems and it seems it boils down to plink.
Pushing directly from phpstorm works as expected, but it uses its own built-in ssh client.

Does anyone know what the difference between those files is?
"C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe"
"C:\Program Files\TortoiseGit\bin\TortoisePlink.exe"
"C:\Program Files (x86)\PuTTY\plink.exe"

Currently git is using the first one.

**Comment by indrora** [comment]
I'm encountering this without ssh. It looks like git pack-objects is getting lost. 

```
morga@fennec MINGW32 ~/src/9track (master)
git pack-objects --all-progress-implied --revs --thin --progress --stdout > ../foo
12:52:29.631083 git.c:348               trace: built-in: git 'pack-objects' '--all-progress-implied' '--revs' '--thin' '--progress' '--stdout'
```
It just hangs there, quietly stalling. the file `../foo` gets touched, but is zero-size.

**Comment by liayn** [comment]
It works for me flawlessly with openssh.
I managed to get rid of *plink in my workflow.

**Comment by dscho** [comment]
> [`pack-objects`] just hangs there, quietly stalling.

Not really... Since you passed the `--revs` option, it waits for *you*... From [the man page](https://github.com/git-for-windows/git/blob/583206e958d10a1269431981dfc823c0aa46c78a/Documentation/git-pack-objects.txt#L61-L63):

> --revs::
>   Read the revision arguments from the standard input, instead of
>   individual object names.

**Comment by dscho** [comment]
> It works for me flawlessly with openssh.
> I managed to get rid of *plink in my workflow.

Okay, I read this as "I do not care about this ticket any longer". Thanks.

**Comment by liayn** [comment]
@dscho: That's not true. I would still care about it, but it is obviously a problem of the plink implementations, so I doubt you can do much about it.

**Comment by dscho** [comment]
> it is obviously a problem of the plink implementations, so I doubt you can do much about it.

Just for the record: plink is Open Source, therefore everybody can change it in any way they want.

**Comment by liayn** [comment]
https://gitlab.com/tortoisegit/tortoisegit/issues/2683

**Comment by dscho** [comment]
Again for the record: Reporting the problem elsewhere instead of diving into the code is not at all what I meant by "plink is Open Source, therefore everybody can change it in any way they want".

**Comment by liayn** [comment]
For the record: Not everybody is able or has the time to dig into such low-level issues, which arise due to combination of multiple products. Speaking for myself, I'm digging into various OS products already and simply can't add yet another one. Reporting issues and being responsive to questions is already a big and positive step in OS.

(1% of people will tell you that you make good work; 2% will tell you if you make a mistake or something does not work; 97% will tell everybody else that you messed it up; I tend to value the feedback from those 2% very high.)
