### ISSUE TITLE
Git removes files when pulling and it encountered a permission denied error

### ISSUE THREAD

**Issue by jvanoostveen** [git-for-windows/git#544]
*Situation*:
There are changes to a file and there are incoming changes to it, I do a `stash` and a `pull`. During the pull (pull rebase is enabled), Git shows errors that it can't create a file because of permission denied.
```
> git pull
First, rewinding head to replay your work on top of it...
error: unable to create file src/some/file.ts (Permission denied)
```
The files are being watched by a compiler which is started when I do the stash. The pull then can't change the files as they have been locked by the Windows filesystem.
Git reports the pull as successful. When doing a `git status` now, it shows the file it wasn't able to create as being deleted.

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    src/some/file.ts

no changes added to commit (use "git add" and/or "git commit -a")
```

The file should not have been deleted at all, and when not taking extra care (for example not doing a `status` but directly applying the stash again), one ends up in a strange situation and accidentally removing files that should have been kept.

Either Git should wait for the file to become available again and continue (with a timeout I guess) or it should fail the `pull`.

Environment: git version 2.6.2.windows.1, Windows 10, PowerShell.

**Comment by dscho** [comment]
> Either Git should wait for the file to become available again and continue (with a timeout I guess) or it should fail the pull.

I agree that a "permission denied" should fail the pull. As far as I can tell, the exit code reflects exactly that, though... Have you checked `%ERRORLEVEL%` after the borked `git pull`?

**Comment by jvanoostveen** [comment]
No I have not (as I ran `git status` after it). I will check this when it happens again. But if the exit code does signal an error, then I would also assume the pull didn't happen, but yet it did with unwanted side effects...

**Comment by dscho** [comment]
@jvanoostveen many commands are actually not transactional, including `git pull`. If you would like to see that improved, I can help you to implent it (but I cannot be the driving force behind that project, that would fall into your court).
