### ISSUE TITLE
mintty doesn't close/exit

### ISSUE THREAD

**Issue by sledgehammer999** [git-for-windows/git#545]
I am using 2.6.3 64bits on Windows 7. I updated yesterday from 2.4.something. (I can't remember if it was 64bits too).

Here's my problem. Sometimes, but often enought to become an annoyance, the mintty window refuses to close no matter how many times I click on the "X" button. Even issuing `exit` in the terminal doesn't do something.
My only option is to kill the `bash.exe` from Task Manager.

How can I help you debug this?

**Comment by dscho** [comment]
Is `bash.exe` still running some command inside the MinTTY?

**Comment by sledgehammer999** [comment]
Not that I know of. I mean, that I hadn't issued any command. If there is some background task I don't know.

**Comment by dscho** [comment]
@sledgehammer999 please try to list every detail you can think of (waiting for me to ask all of the things I can think of is just a bit tedious for both of us). So for example, you should consider trying to run things after clicking the X. And maybe test more systematically in order to get a reliable way to trigger the problem. You may also want to mention whether the cursor is still blinking, whether the letters you type still show up, etc, etc.

**Comment by sledgehammer999** [comment]
OK, I figured out how I can reproduce it. If I just open the terminal window and then close it, it doesn't have any problem. If I run any command either git command(eg `git status`) or regular (`ls`) AND then try to close it, it doesn't close. Furthermore, after it doesn't close no matter which command I issue it gets stuck there after the "enter". The cursor blinks at all times but the command doesn't finish. It doesn't even respond to "control-c". While stuck, if I write letters or hit enter they show up in the terminal.
However, if I don't try to close it, it executes every command.

Also another reliable way to make it exit is to issue `exit` in the terminal. `exit` gets stuck if I first try to close via "X".

I don't know how this works but I suppose mintty forwards things to bash, right? So maybe mintty does something weird (deadlock?) when clicking on "X".

I don't see any CPU activity on bash.exe or mintty.exe when they're stuck. Nor disk activity.

**Comment by dscho** [comment]
Hrm. I still cannot reproduce. If I open a Git Bash, run `ls` and click the X as quickly as possible (the `ls` command has finished by that time, of course), it closes Just Fine.

So I still think that there must be something odd in your setup that you did not think to mention yet.

**Comment by sledgehammer999** [comment]
I also checked with 2.6.2, 2.6.1, 2.6.0 and 2.5.3 **64bits** same problem.
Then I randomly installed 2.6.3 **32bits** and I no longer encounter the problem.

**Comment by dscho** [comment]
That is even stranger now!

The last idea I have about this is: is there an aggressive anti virus or other monitoring process running?

**Comment by sledgehammer999** [comment]
I tested in a VM with clean install of Win 7 sp2 and 64bit git. It works. So it surely is something wrong in my current setup.
I disabled my antivirus and firewall but it didn't fix it. I don't have any other monitoring app.
Hmm, I know this is hard for you to guess now.
Could you tell me how the interaction between mintty and bash works? Or at least how the "click on X" is handled by mintty and forwarded to the bash process? Or point me to the relevant code in the repo?
I might get an idea on what to look for in my machine...

**Comment by dscho** [comment]
> how the "click on X" is handled by mintty

That code is in the `mintty` project. I guess the `X` is handled here: https://github.com/mintty/mintty/blob/1477cbd67e31882a2c812ae1307e1cd2de389c79/src/winmain.c#L962-L965

As you can see, there is a slightly different behavior if the Shift key is pressed (or if mintty *thinks* that it is pressed).

If I were in your shoes, I would install [the Git for Windows SDK](https://git-for-windows.github.io/#download-sdk), then build the MSys2 package `mintty` [as described here](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages), then instrument the code in a way similar to this patch:

```diff
diff --git a/src/winmain.c b/src/winmain.c
index 1a9c5ab..ad43985 100644
--- a/src/winmain.c
+++ b/src/winmain.c
@@ -688,7 +688,9 @@ win_proc(HWND wnd, UINT message, WPARAM wp, LPARAM lp)
     }
     when WM_CLOSE:
       if (!cfg.confirm_exit || confirm_exit())
+{ FILE *f = fopen("C:\\git-sdk-64\\mintty.log", "a"); fprintf(f, "WM_CLOSE received (shift: %x)\n", GetKeyState(VK_SHIFT) & 0x80); fclose(f);
         child_kill((GetKeyState(VK_SHIFT) & 0x80) != 0);
+}
       return 0;
     when WM_COMMAND or WM_SYSCOMMAND:
       switch (wp & ~0xF) {  /* low 4 bits reserved to Windows */
```

then run `make` in `/usr/src/MSYS2-packages/mintty/src/mintty-2.1.5`, and then copy the `src/mintty.exe` file into a fresh PortableGit for further testing.

**Comment by sledgehammer999** [comment]
I have more info.
Last known working **64bit** release from you guys, was 2.5.1.
I copied `bash.exe`, `git-bash.exe` and `mintty.exe` from 2.5.1 to 2.6.3 but the problem persists. Does that mean that mintty isn't at fault here?

**Comment by dscho** [comment]
It may be an issue with `msys-2.0.dll`, too.

Please note that 2.5.1 -> 2.6.3 is a pretty large jump, and much larger still when you realize that the individual packages we packaged went through their own sets of releases (check `/etc/package-versions.txt` for details).

**Comment by sledgehammer999** [comment]
The problem is between 2.5.1 and 2.5.2 and I imagine the jump isn't great there. I'll try the `msys-2.0.dll` from 2.5.1 into the 2.5.2 installation and report back.

**Comment by sledgehammer999** [comment]
Finally! Replacing `msys-2.0.dll` from 2.5.1 into 2.5.2 or 2.6.3 fixes the problem.

**Comment by dscho** [comment]
Good progress! Do you have the `msys2-runtime` version from the respective `/etc/package-versions.txt` handy, perchance? (I *hope* the versions were recorded there...)

**Comment by sledgehammer999** [comment]
Unfortunately the 2.5.1 file contains info only for 3 packages: filesystem, dash, rebase

**Comment by dscho** [comment]
Yeah, I feared so much. I introduced a bug that resulted in incorrect package-versions.txt files.

So the next route would be to call `sha256sum.exe /usr/bin/msys-2.0.dll` and compare to the unpacked `msys-2.0.dll` files of the `msys2-runtime` packages hosted at https://dl.bintray.com/git-for-windows/pacman/x86_64/.

**Comment by sledgehammer999** [comment]
Do they have another page showing timestamps for each package? (to not try them all)

**Comment by dscho** [comment]
Hmpf... I really wanted to release Git for Windows 2.6.4 today. Apparently not.

```sh
for package in $(curl https://dl.bintray.com/git-for-windows/pacman/x86_64/ |
    sed -n 's|.*":\(msys2-runtime-[0-9][^"]*\.xz\).*|\1|p')
do
    test -f $package ||
    curl -sLO https://dl.bintray.com/git-for-windows/pacman/x86_64/$package

    echo "$package: $(tar Oxf $package usr/bin/msys-2.0.dll | sha256sum.exe)"
done
```

outputs this:

```
msys2-runtime-2.0.16652.eb1d093-1-x86_64.pkg.tar.xz: 8795e97f7a33e0d5fd4710597a0643718aa582a7ba12c79fba94636e3f4fba19 *-
msys2-runtime-2.1.0.32946.ce3a5e8-1-x86_64.pkg.tar.xz: e81ae8ee6755d421045fc4e0a8981911088de51d5c76dbff1755d9ee61fb4e84 *-
msys2-runtime-2.1.0.32947.d5c2bb6-1-x86_64.pkg.tar.xz: 30a3222a86ae9ec1175790253dd58d53f30ca30f202f20c9bdabd870408c0bf1 *-
msys2-runtime-2.1.0.33061.d2ce049-1-x86_64.pkg.tar.xz: 136c57a8c205ed9fd005905ce1ec73f28b7a600f3d81a40681e1966915974fcd *-
msys2-runtime-2.1.0.33102.63331f9-1-x86_64.pkg.tar.xz: ff628d11d3ef92f1153a35a84ca3000182f218a02a96bbc2c4a13a2f6524dbd8 *-
msys2-runtime-2.1.0.33104.e0d5f4b-1-x86_64.pkg.tar.xz: 04dd0a91427d4a82d30b081bc8312328421ca2f5b6839aeb0b818aeb3be11f5b *-
msys2-runtime-2.1.0.33105.aae52e6-1-x86_64.pkg.tar.xz: 6b4c7d6bec7821c3c95c595afddf0d2208bfd1c0a4d0e60c920f246f9224ce42 *-
msys2-runtime-2.1.0.33143.356e478-1-x86_64.pkg.tar.xz: 38914f5f85ac8d35d3121f22212f252b3d8928a3615b63fa028a2a1a1d15380f *-
msys2-runtime-2.1.0.33189.510cd1c-1-x86_64.pkg.tar.xz: 4f95017c40bd8a39f666a78f090357f9a21acfdc026fa978f37b55db55bc3f5c *-
msys2-runtime-2.1.0.33191.833e388-1-x86_64.pkg.tar.xz: 78baa8e2e2967e5d3969077058c360f552ff3cbb4c4c0dc8fa3a4e3c2effc476 *-
msys2-runtime-2.1.0.33193.e80f57c-1-x86_64.pkg.tar.xz: 8d938d827c0556ebffdae9ba861ce2a498323cb3cbc9cc414b9521a3b49f41bd *-
msys2-runtime-2.1.0.33407.cd22500-1-x86_64.pkg.tar.xz: ded6ec87ee667afac704649d2b98f70db650e30fc9c46cfcb976882751079f76 *-
msys2-runtime-2.2.1.33553.f87f2bc-1-x86_64.pkg.tar.xz: d1bc1a2ce2c42408113382011c6f3347047a7a062107a16e687e0c15b6c5161c *-
msys2-runtime-2.2.1.33617.df1f0a9-1-x86_64.pkg.tar.xz: 482ba717e629ff3b8795889d445cb0ade57d3f13e40f79077798a673668d5885 *-
msys2-runtime-2.2.1.33619.e87aaa7-1-x86_64.pkg.tar.xz: 7e925835359a1ae4d9f05a7a50ea1958095dff30f698c9b5f9986d9c3fe0d517 *-
```

**Comment by sledgehammer999** [comment]
My dll is:
`ded6ec87ee667afac704649d2b98f70db650e30fc9c46cfcb976882751079f76 *msys-2.0.dll`

**Comment by dscho** [comment]
@sledgehammer999 you do not need me to make the connection to this line:

```
msys2-runtime-2.1.0.33407.cd22500-1-x86_64.pkg.tar.xz: ded6ec87ee667afac704649d2b98f70db650e30fc9c46cfcb976882751079f76 *-
```

As you probably guessed, the last part of the version refers to a commit. In this case, to git-for-windows/msys2-runtime@cd22500.

The next step would be to look at the history in https://github.com/git-for-windows/msys2-runtime leading up from that commit to the one corresponding to the `msys-2.0.dll` that displays the bug.

If nothing obvious sticks out, it is `git bisect` time.

Note that upstream MSys2 rebases a couple of commits on top of Cygwin's `master` every couple of days. I found that the easiest way to bisect the MSys2 runtime is therefore to squash those changes on a topic branch and then `cherry-pick -n` and `stash` those changes while bisecting before and after, respectively, [building](https://github.com/git-for-windows/git/wiki/Building-msys2-runtime) and testing the MSys2 runtime (`msys-2.0.dll`).

**Comment by dscho** [comment]
@sledgehammer999 are you waiting for me to bisect this?

**Comment by sledgehammer999** [comment]
@dscho I am terribly sorry. I know that you have limited time. Me too. I am focusing on qBittorrent development on my limited time and forgot about this.

I will try the different dlls now. I can then search the git history for something obvious. However, I really doubt that I'll find the nerve/time to build msys myself (to test commits).

**Comment by sledgehammer999** [comment]
Ok it fails with next in line release aka `msys2-runtime-2.2.1.33553.f87f2bc-1-x86_64.pkg.tar.xz`
I am going to see what changes were made between `cd22500` and `f87f2bc` and report back.

**Comment by dscho** [comment]
Thanks for pursuing this!

**Comment by sledgehammer999** [comment]
OK, from the commit messages I found 3 somewhat relevant:
```
c33175f83f5374287c7f9d1a935f598f91701a2c - Kill also children of the process to be killed via Ctrl+C
a7c0c92542b2625677591e945c6d9c424457675c -  Export the `kill_process_tree()` function
5e24104106f787b9a04add9bddf1c029a97b8295 - kill: Handle Win32 console processes' children, too
```

If you could provide binaries from bisecting I would happily test them.

On another note: Does the SDK include a compiler? If I install it under a VM (Windows 7) will I be able to do build with much fuss?

**Comment by dscho** [comment]
> Does the SDK include a compiler?

Yes. Two, as a matter of fact, one for [MSys2 and MinGW](https://github.com/git-for-windows/build-extra/blob/master/README.md#the-difference-between-msys2-and-mingw), each.

> If I install it under a VM (Windows 7) will I be able to do builds without much fuss?

That is the idea. See https://github.com/git-for-windows/git/wiki/Building-msys2-runtime

**Comment by sledgehammer999** [comment]
I just updated to 2.7.1.2. I am happy to announce that the problem seems fixed now. Closing this issue.
