### ISSUE TITLE
[Feature Request] Add support for running other filetypes, like .cmd or .js

### ISSUE THREAD

**Issue by jamesqo** [git-for-windows/git#546]
It would be nice if Git Bash were able to run other executable filetypes (all the ones in `$PATHEXT`), like .js, in `$PATH` without having to switch to CMD.

For example, for .cmd files Git Bash would run something analogous to this:

``` bash
cmd /c "$file.cmd"
```

**Comment by dscho** [comment]
@jamesqo if we were overrun with volunteers, you could reasonably hope for others to fulfill your wishes.

But there is hope! It is relatively easy for a motivated contributor to implement this feature. You can be that motivated contributor. All you need to do is to use the information on [this page](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages) to rebuild the `bash` package, then look through the source code in `/usr/src/MSYS2-packages/bash/src/bash-4.3/` where scripts are launched (`grep` is your friend) and patch that to handle `.cmd`, `.bat` and `.js` files specially. If you get stuck anywhere, I will assist you.

**Comment by jamesqo** [comment]
@dscho Sounds great! Although I don't have too much time on my hands right now, I'd definitely be willing to help. I'll let you know if I need assistance.

**Comment by Jan-Bruun-Andersen** [comment]
You could ease the pain by defining a function in Bash, say R, like this:

R() { case $1 in *.cmd ) SHELL="$COMSPEC" "$COMSPEC" /c "$@";; esac; }

Now whenever you want to run a CMD-file, all you have to do is:

$ R xxx.cmd

I will leave it as an exercise for the reader to extend R to also handle JavaScript and pure Java.

**Comment by dscho** [comment]
> a function in Bash, say *R*

Given that R is a completely different language, this would be completely misleading.

> `"$COMSPEC" /c "$@"`

You will find that that does not work once you test it.

Additionally, requiring a function to launch scripts is only marginally better than requiring the interpreter to be specified explicitly.

It will be better to fix this for real, in the way [I suggested previously](https://github.com/git-for-windows/git/issues/546#issuecomment-159195402).

**Comment by davidovich** [comment]
Hi, 

In a stock git-for-windows installation and a small modification to /etc/fstab, I am able to directly call .cmd files from the bash shell. I believe starting batch files is already a feature of msys2:

```bash
> cat /etc/fstab 
# For a description of the file format, see the Users Guide
# http://cygwin.com/cygwin-ug-net/using.html#mount-table

# DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path
#none / cygdrive binary,posix=0,noacl,user 0 0 # commented in favor of the line below
none / cygdrive binary,posix=0,user 0 0 # note the absence of noacl
none /tmp usertemp binary,posix=0,noacl 0 0
```

Note the removal of **noacl**. 

Now I cannot recall how I got to this, it is related to how acls are emulated between the two systems. I run almost all my batch files this way, including auto-completion, and never leave the bash prompt. Your milage may vary.

**Comment by dscho** [comment]
Good point. I can verify that this is the case (with an `a1.cmd` containing the line `echo Hello`):

```cmd
$ ./a1.cmd

C:\Users\me>echo Hello
Hello
```

For the record, the MSys2 runtime handles `.bat` and `.cmd` files [here](https://github.com/git-for-windows/msys2-runtime/blob/e87aaa7d59deb2f4e5bff9cb114a0c45d1ae1a5e/winsup/cygwin/spawn.cc#L1094).

**Comment by Jan-Bruun-Andersen** [comment]
Okay.... So COMSPEC needs to be converted to Unix format. And some weird argument handling by CMD.exe tacks an " at the end of the command. So it needs to be something like this:

R() { case $1 in *.cmd ) $(cygpath --unix "${COMSPEC}") "/c $@ & ::";; esac; }

**Comment by dscho** [comment]
@Jan-Bruun-Andersen no. The `/c` is the problem: it will be translated to `C:/`.

And the additional problems still persist, of course (hence it is not really my top priority to fix the `/c` problem):

- `R` is a well-known language, completely different from CMD, Javascript, whatever else
- Introducing a letter to launch scripts is not much better from a usability view point than requiring the user to prefix the script invocation with `cmd //c`

So, as you see, I remain entirely convinced that my original suggestion is what we should pursue, if. that is, anybody feels enough of a need for this feature to do some coding.
