### ISSUE TITLE
SCP could not resolve hostname C: name or service unknown

### ISSUE THREAD

**Issue by hgonzalez94** [git-for-windows/git#547]
When I try using SCP in order to remotely edit files from vim, I keep receiving this error everytime I try to edit a file. It seems to be confused with the windows path. Does anyone have a work around for this?

**Comment by dscho** [comment]
More details, please.

(A simple `scp test.txt my-host:` works here, as expected, so it must be something on your side that is odd, and you will need to tell us more so we have a chance to see which thing exactly is odd on your side.)

**Comment by hgonzalez94** [comment]
I'm using windows 10 and installed the windows git unix command tools. I'm also using gvim. 

I have added a host with an identity file in my .ssh/config with a host. 

Normally when I'm going to edit a file I access the remote directory this way: gvim +E scp://host//directory/in/server/, but each time I try to edit a file after browsing the directory, it says that it could not resolve the hostname C: . Name or service unknown. 

Any thoughts?

**Comment by dscho** [comment]
Whoa. gvim?

```sh
$ gvim
bash: gvim: command not found
```
