### ISSUE TITLE
Pacman packages not found during Git For Windows SDK installation

### ISSUE THREAD

**Issue by Astrophizz** [git-for-windows/git#548]
The following three packages aren't found by pacman during the installation:
- git-extra
- mingw-w64-x86_64-git-doc-html
- mingw-w64-x86_64-git

Here is the output from the final attempt to install the packages:

```
:: There are 39 members in group base:
:: Repository msys
   1) bash  2) bash-completion  3) bsdcpio  4) bsdtar  5) bzip2  6) catgets
   7) coreutils  8) crypt  9) curl  10) dash  11) file  12) filesystem
   13) findutils  14) flex  15) gawk  16) gcc-libs  17) grep  18) gzip
   19) inetutils  20) info  21) less  22) lndir  23) mintty  24) msys2-keyring
   25) msys2-launcher-git  26) msys2-runtime  27) ncurses  28) pacman
   29) pacman-mirrors  30) pax-git  31) pkgfile  32) rebase  33) repman-git
   34) sed  35) tftp-hpa  36) time  37) tzcode  38) util-linux  39) which

Enter a selection (default=all):
warning: bash-4.3.042-2 is up to date -- skipping
warning: bzip2-1.0.6-2 is up to date -- skipping
warning: coreutils-8.24-1 is up to date -- skipping
warning: curl-7.45.0-1 is up to date -- skipping
warning: findutils-4.5.14-4 is up to date -- skipping
warning: gcc-libs-4.9.2-6 is up to date -- skipping
warning: gzip-1.6-1 is up to date -- skipping
warning: info-6.0-1 is up to date -- skipping
warning: less-481-1 is up to date -- skipping
warning: msys2-keyring-r9.397a52e-1 is up to date -- skipping
warning: msys2-runtime-2.4.0.16752.6eb10ef-1 is up to date -- skipping
warning: ncurses-6.0.20151121-1 is up to date -- skipping
warning: pacman-4.2.1.6258.f5bbd79-1 is up to date -- skipping
warning: pacman-mirrors-20150722-2 is up to date -- skipping
warning: sed-4.2.2-2 is up to date -- skipping
warning: which-2.21-2 is up to date -- skipping
warning: less-481-1 is up to date -- skipping
warning: ca-certificates-20150426-1 is up to date -- skipping
warning: skipping target: mintty
error: target not found: git-extra
error: target not found: mingw-w64-x86_64-git-doc-html
error: target not found: mingw-w64-x86_64-git
Could not install the remaining packages
```

I couldn't local the packages through `pacman -Ss <package name>` or by browsing the package repository sites.

**Comment by elieux** [comment]
It looks like `pacman -Sy` didn't succeed. Is the `git-for-windows` repo included in `/etc/pacman.conf`?

**Comment by Astrophizz** [comment]
No, just the below:
```
[mingw32]
Include = /etc/pacman.d/mirrorlist.mingw32

[mingw64]
Include = /etc/pacman.d/mirrorlist.mingw64

[msys]
Include = /etc/pacman.d/mirrorlist.msys
```

Did I need to run `pacman-helper.sh` (and/or other scripts) before `release.sh`?

**Comment by dscho** [comment]
Hrm. This is what I get with a freshly downloaded SDK 1.0.1 installer:

```sh
$ 7za x -so ~/Downloads/git-sdk-installer-1.0.1-64.7z.exe etc/pacman.conf 2> /dev/null | sed -n '/^\[[^o]/,$p'
[git-for-windows]
Server = https://dl.bintray.com/$repo/pacman/$arch
SigLevel = Optional

[mingw32]
Include = /etc/pacman.d/mirrorlist.mingw32

[mingw64]
Include = /etc/pacman.d/mirrorlist.mingw64

[msys]
Include = /etc/pacman.d/mirrorlist.msys

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
```

**Comment by dscho** [comment]
(Note the `[git-for-windows]` section...)

**Comment by dscho** [comment]
Ah, I *think* I know what happened. You reported an error elsewhere where `pacman` could not update some files correctly. I am assuming that it managed to install the `pacman` package *itself* correctly, but not the `git-extra` package.

Unfortunately, this will always break our setup: directly after `pacman` installed (which simply overwrites `/etc/pacman.conf`), we *have to* install `git-extra` (which edits `/etc/pacman.conf` because there is unfortunately no way to insert the `[git-for-windows]` repository with highest priority; we need it to be highest priority because we ship with a modified msys2-runtime for now).

Your best bet is to unpack the `etc/pacman.conf` file from the installer and overwrite your copy, followed by a clean `pacman -Syu`.

**Comment by Astrophizz** [comment]
That worked, though I'm not sure I understand the relationship between `git-extra` and `pacman.conf`. The conf as found in the installer generated by `release.sh` doesn't include `[git-for-windows]` and if `git-extra` is supposed to add `[git-for-windows]`, it's caught in a catch-22 because `git-extra` comes from the `[git-for-windows]` repo.

Anyways, I'm satisfied that the problem is probably on my end somewhere.

**Comment by elieux** [comment]
If I understood the process correctly from @dscho's description, it's like this:

1. extract base system including pacman and modified `/etc/pacman.conf` with `[git-for-windows]`
2. run pacman to upgrade the base system including pacman and also install `git-extra`
3. pacman downloads everything from correct places, re-writes `/etc/pacman.conf` during upgrade of pacman, and then the installation of `git-extra` adds `[git-for-windows]` back, all in one run

If the script in step 3 failed, the `git-extra` package needs to be re-installed. One way was described by @dscho, as cited below; another way -- if my hypothesis is correct -- would be to install directly from the downloaded `git-extra` package by `pacman -U /var/cache/pacman/pkg/git-extra-*.pkg.tar.xz`.

> Your best bet is to unpack the `etc/pacman.conf` file from the installer and overwrite your copy, followed by a clean `pacman -Syu`.

**Comment by Astrophizz** [comment]
If that's the case, then I think `release.sh` is missing code to ensure step 1 happens and `setup-git-sdk.bat` is missing the second half of step 2.

**Comment by dscho** [comment]
@Astrophizz the *real* problem is that step 1 fails. We need to fix that, for sure. Everything else is a fall-out from that problem.

**Comment by Astrophizz** [comment]
@dscho My understanding is that with step 1 there is no modified `pacman.conf` to be extracted, unless the user manually modifies `etc\pacman.conf` in their Msys2 environment before generating a release of the SDK. I apologize if I'm being dense.

**Comment by dscho** [comment]
> with step 1 there is no modified pacman.conf to be extracted, unless the user manually modifies etc\pacman.conf in their Msys2 environment before generating a release of the SDK.

@Astrophizz the `pacman.conf` is indeed modified.

The trick is that I myself installed `git-extra` after `pacman`. There are [these lines](https://github.com/git-for-windows/build-extra/blob/649aa13dcfa2fde6ea3a3c5cbcb884008799f43e/git-extra/git-extra.install#L67-L68) in `git-extra`'s post-install script:

```sh
grep -q git-for-windows etc/pacman.conf ||
sed -i -e '/^\[mingw32\]/i[git-for-windows]\nServer = https://dl.bintray.com/$repo/pacman/$arch\nSigLevel = Optional\n' etc/pacman.conf
```

In other words, we (ab-)use the post-install feature of Pacman packages to insert a higher-priority Pacman repository, for lack of a cleaner solution.

Now, when the SDK runs and `pacman` is actually *updated*, it *overwrites* the `pacman.conf` file with its own version. So between the update of `pacman` and the update of `git-extra`, the `pacman.conf` file is actually wrong.

The only valid work-around I can think of is to insert a similar construct as those two lines from `git-extra`'s post-install script into `setup-git-sdk.bat`, but that is slightly involved: `sed.exe` and `grep.exe` are *both* not yet available at the point when the `pacman` package is installed. Funnily enough, it is not `sed.exe` but *`grep.exe`* that is the bigger problem, as it depends on `msys-pcre-1.dll` and `msys-gcc_s-1.dll` in addition to the dependencies that *just so happen* to be required for `pacman.exe` to work properly already.

So what I would do (if I had the time) is to write a `sed` script that basically replaces those two lines, and then include `sed.exe` in the SDK installer. The `sed` script would probably look *somewhat* like this:

```sh
sed -i -e '/^\[/{/^\[options\]/b;/^\[git-for-windows\]/{:1;n;b1};};/^\[mingw32\]/i[git-for-windows]\nServer = https://dl.bintray.com/$repo/pacman/$arch\nSigLevel = Optional\n' /etc/pacman.conf
```

Of course this is all written in the browser and completely untested, and I really need to get to other tasks now ;-)

**Comment by Astrophizz** [comment]
@dscho Yes, that makes sense.

I too am constrained for time, so I understand. If copying `sed.exe` and `msys-2.0.dll` out of the msys2 environment as part of `release.sh` and figuring out the appropriate `sed` script to add the repository reference is what is needed then I will try to put together a pull request at some point.

Is `usr\bin` the preferred directory for the binaries as extracted by the installer? I'm curious whether that could cause a conflict with the later `pacman` msys2 installations and if you don't know off the top of your head I'm sure I'd find out.

**Comment by dscho** [comment]
> Is usr\bin the preferred directory for the binaries as extracted by the installer?

It happens to be. The preferred directory is the one in which those binaries live in the MSys2 packages.

> that could cause a conflict with the later pacman msys2 installations

In the worst case, an unused binary would be left lying around. Not a big deal, methinks.

**Comment by shiftkey** [comment]
Closing this out as stale. Please open a new issue for anything related to the SDK setup.
