### ISSUE TITLE
Generate Git documentation, too

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#55]
We need to include the documentation in the `mingw-w64-git` packages, too.

**Comment by sschuberth** [comment]
Generating the docs should be possible as of https://github.com/git-for-windows/build-extra/pull/18, but it still needs to be bundled to the package, I guess.

**Comment by dscho** [comment]
The documentation of Git is tightly tied to the Git version. Therefore generating and bundling it anywhere else than in `MINGW-packages`' `mingw-w64-git/PKGBUILD` would be unnecessarily fragile.

I assigned this ticket to myself for a reason, though: I already solved it (I think, the full build now takes a while before it may confirm my claim).

**Comment by sschuberth** [comment]
I just wanted to point out that the docs should be packaged *as part of* `mingw-w64-git/PKGBUILD` in case that involves any extra work that hasn't been done yet. Still after all the recent discussions IMO there's not need to react surly or see criticism where there is none.

**Comment by dscho** [comment]
`mingw-w64-git/PKGBUILD` does not need that PR because it has a `makedepends` section where I already specified `asciidoc` and `xmlto` as dependencies.

**Comment by sschuberth** [comment]
Hm, but why did `setup-git-sdk.bat` require it then, as it installs `mingw-w64-git`, which should also install `asciidoc` and `xmlto` automatically.

@nalla Can you elaborate?

**Comment by dscho** [comment]
@sschuberth it is clear that `setup-git-sdk.bat` sets up a development environment to develop Git for Windows. It will even build it right away so that testing and developing can begin right away.

Now, it is possible that developers want to work on the documentation, too. That is why @nalla added the required packages to the setup.

In *any* case, however, the dependencies have to be added to the `PKGBUILD` script because it will hopefully eventually be used by upstream, too, who do *not* set up a Git SDK.

So we need both. But @nalla's PR is not required for *this* ticket, strictly speaking.

**Comment by sschuberth** [comment]
Right, I simply confused `depends` with `makedepends`, i.e. run time vs. build time dependencies.

**Comment by nalla** [comment]
Correct. If you want to manually build the `doc` without building the package first, you need to install those dependencies. While building the package would resolve the dependency for you.

**Comment by dscho** [comment]
Fixed in git-for-windows/MINGW-packages@0bca87a.
