### ISSUE TITLE
Bring back Explorer / Shell extension for switching branches

### ISSUE THREAD

**Issue by DDReaper** [git-for-windows/git#556]
One feature I loved from the old Git for Windows was the ability to switch branches directly from the explorer shell.

However with the new git for windows, all I'm left with is Git bash Here and Git GUI.

Any chance we can get the old shell extension back?

**Comment by dscho** [comment]
> Any chance we can get the old shell extension back?

There is a chance, but it won't be cheap (i.e. just asking for it will not bring it back). You need to either take over maintainership of [Git-Cheetah](https://github.com/msysgit/Git-Cheetah) or entice someone else to do so.

**Comment by dscho** [comment]
Closing due to obvious lack of interest.
