### ISSUE TITLE
Could not resolve hostname github.com

### ISSUE THREAD

**Issue by drusellers** [git-for-windows/git#557]
Not sure where else to post this issue, but since upgrading to 2.6.3 from 1.9.x git is no longer working for me. 

```
ssh: Could not resolve hostname github.com: Non-recoverable failure in name resolution
fatal: Could not read from repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

![image](https://cloud.githubusercontent.com/assets/63355/11563380/427fe890-9999-11e5-83dd-d3dddcb08bf4.png)

- I have tried this with public and private repositories
- I have tried 2.6.3, 2.6.1, and 2.5.3
- I have revoked and reissued my SSL keys
- I have double checked my remote urls
- I have tried to google the error but I have had no luck

Options
- Select Components: Default Options
- Use Git from Git Bash Only
- Checkout as-is, commit as-is
- Use MinTTY

Operating System

- x64
- Windows 8.1 Enterprise
- All Updates applied

Update

- Successfully cloned `git clone https://bitbucket.org/fenics-project/dolfin.git`
- Successfully cloned `git clone https://github.com/MassTransit/MassTransit.git`
- FAILED to clone `git clone git@github.com:MassTransit/MassTransit.git`

Update 2

`ssh git@github.com` gives me the same error unsurprisingly.

```
Could not resolve hostname github.com: Non-recoverable failure in name resolution
```

https://cygwin.com/ml/cygwin/2014-04/msg00476.html makes me think there is a bad cygwin dll?

----

Thank you in advance,

-d

**Comment by shiftkey** [comment]
Sounds a bit similar to #297 - @drusellers are you running this in a VM?

Anyway, need more info. Could you try these commands and see if they yield anything interesting:

> GIT_TRACE=1 GIT_CURL_VERBOSE=1 g fa
> nslookup -debug github.com

**Comment by drusellers** [comment]
@shiftkey yeah, its the same issue. Thank you.
