### ISSUE TITLE
Release 2.6.3 installer doesn't set the root certificate path

### ISSUE THREAD

**Issue by mindplay-dk** [git-for-windows/git#558]
I installed Git release 2.6.3 (64bit build) several times these past few days, on Windows 10, before I finally figured out what was wrong.

Today, I uninstalled, rebooted, and then re-installed to a new destination path (`C:\Git`) to make sure everything was clean - and finally I discovered, the installer doesn't configure the path to the root certificates during install.

[This answer on SO](https://stackoverflow.com/questions/3778042/github-error-cloning-my-private-repository/3778244#3778244) provided the solution:

    git config --system http.sslcainfo "C:\Git\bin\curl-ca-bundle.crt"

I guess either the installer should correct this setting, or at least warn you if that setting is pointing to a non-existent folder?

**Comment by dscho** [comment]
Thank you for your report. There is already an existing ticket for this, though: https://github.com/git-for-windows/git/issues/531
