### ISSUE TITLE
Installing as "nt authority\system" does not create HKLM:\..\Uninstall entry

### ISSUE THREAD

**Issue by alx9r** [git-for-windows/git#560]
I have been experimenting with unattended installation for all users.  The rough criteria for this kind of installation is as follows:

* install occurs without user interaction by the `nt authority\system` account
* after installation (and perhaps after a reboot), git is accessible to all users of the system

IME the above installation strategy is customary amongst applications deployed organization-wide using configuration management automation.  Indeed, [Git for Windows Version 2.6.3](https://github.com/git-for-windows/git/releases/download/v2.6.3.windows.1/Git-2.6.3-64-bit.exe) can also be made to install in a way that adheres to the above criteria using the command

    psexec -s Git-2.6.3-64-bit.exe /SILENT

where `psexec` is [the sysinternals tool](https://technet.microsoft.com/en-us/sysinternals/psexec.aspx) and `Git-2.6.3-64-bit.exe` is the Git for Windows installer.  `psexec -s` causes the installation to occur as `nt authority\system`.

I noticed, however, that installing `Git-2.6.3-64-bit.exe` as `nt authority\system` means that there is no `Git 2.6.3` entry in [`appwiz.cpl`](https://www.youtube.com/watch?v=F4sR0SZXNSQ).  As best I can tell, `appwiz.cpl` populates its entries from `HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall` and `HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`.  (I don't have a reference for this.  I'm basing this on the approximately 100 or so common applications whose installations I have examined.)  Indeed, when `Git-2.6.3-64-bit.exe` is installed as `nt authority\system` it does not seem to create an entry in either of the `HKLM:\...\Uninstall` nodes.

I don't think this is a huge deal, but it makes me wonder the following:

* Is there some other method to achieve unattended installation for all users that creates the correct entries to populate `appwiz.cpl`?
* If not, should the installer be altered such that it creates the customary `appwiz.cpl` entries when run as `nt authority\system`?

**Comment by dscho** [comment]
Could you [make an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer) from the current sources and verify that the bug persists? I ask because I think this issue is [already resolved](https://github.com/git-for-windows/build-extra/commit/23672af723da18e5bc3c679e52106de3c2dec55a).

**Comment by alx9r** [comment]
@dscho It seems your suspicion is correct.  I built from current sources and tested installation using the resulting installer.  That installation produced a node at `HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Git_is1`.  Git also shows up in `appwiz.cpl`:

![image](https://cloud.githubusercontent.com/assets/11237922/11637037/1d66a95c-9cd4-11e5-859f-d05766d66a5f.png)

As long as this change will be included in future releases, I'd say this problem is already resolved. Thanks for your help.

**Comment by dscho** [comment]
Perfect. Thank you so much for going the length to verify the resolution. And yes, I guarantee that this problem will not be reintroduced.

**Comment by alx9r** [comment]
@dscho No problem.  Knowing that this will be fixed in the future makes my job easier.
