### ISSUE TITLE
Packaged echo.exe removing braces from cmdline arguments

### ISSUE THREAD

**Issue by asottile** [git-for-windows/git#561]
Version info:
```
C:\Users\Anthony>git --version
git version 2.6.3.windows.1
```

---

```
C:\Users\Anthony> C:\Users\Anthony\AppData\Local\Programs\Git\usr\bin\echo.exe hi{1}
hi1
```

Expected:

```
hi{1}
```

Interestingly enough, this works:

```
# With a space between the text and the braces
C:\Users\Anthony> C:\Users\Anthony\AppData\Local\Programs\Git\usr\bin\echo.exe 'hi {1}'
hi {1}
```

**Comment by Radrik5** [comment]
It's not because of space but because of quotes:
```
e:\Projects> "C:\Program Files\Git\usr\bin\echo.exe" 'x{1}'
x{1}

e:\Projects> "C:\Program Files\Git\usr\bin\echo.exe" "x{1}"
x{1}
```

Not reproducible in Git Bash:
```
~ $ /c/Program\ Files/Git/usr/bin/echo.exe x{1}
x{1}
```

**Comment by dscho** [comment]
I agree with @Radrik5 that you need to quote arguments you do not want to be interpolated in any way.

**Comment by asottile** [comment]
I assure you this is not a situation where interpolation should be happening.  But first let me convince you of it:

First, expected behaviour from ubuntu:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
$ echo hi{1}
hi{1}
```

Using cmd.exe's builtin:

```
C:\Users\Anthony>echo hi{1}
hi{1}
```

Avoiding the shell with python subprocess:

```
C:\Users\Anthony>python -c "import subprocess; print(subprocess.check_output((r'C:\Users\Anthony\AppData\Local\Programs\Git\usr\bin\echo.exe', 'hi{1}'), shell=False))"
hi1
```

**Comment by dscho** [comment]
> I assure you this is not a situation where interpolation should be happening

I know that `{1}` should not be interpolated.

But since you do not want the argument to be interpolated, you should quote it. And since that works around the curly braces problem, I cannot afford to spend time fixing this issue ("wontfix").

Of course you should feel more than welcome to give it a shot yourself. The first thing to do, if you choose to accept this task, is to run the command through `strace.exe` to try to figure out where things go wrong. If you get stuck anywhere, just present what you found out so far and explain where you are stuck.

**Comment by asottile** [comment]
If the goal is to provide a conforming implementation of echo (which I believe it is), this is actually a bug.

I can't just go quoting strings, this'll lead to another class of bugs with over-quoting (I'm not even using a shell in the first place!):

```
C:\Users\IEUser>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> print(subprocess.check_output((r'C:\Program Files\Git\usr\bin\echo.exe', '"hi{1}"')))
\hi{1}"

>>>
```

That said, looking at the strace output: http://paste.pound-python.org/show/Kv30PQaptsi0IFEstkfS/ it seems the problem is here (you can see it receives the correct arguments, then munges them):

```
  230   45754 [main] echo 3012 build_argv: cmd = '"C:\Program Files\Git\usr\bin\echo.exe" hi{1}', winshell = 1, glob = 1
  214   45968 [main] echo 3012 build_argv: argv[0] = 'C:\Program Files\Git\usr\bin\echo.exe'
  165   46133 [main] echo 3012 lstat64: entering
  124   46257 [main] echo 3012 normalize_posix_path: src hi1
```

**Comment by dscho** [comment]
Is it possible that there is actually a file `hi1` in the current directory?

**Comment by dscho** [comment]
Never mind, I just verified that such a file does not need to exist for that behavior.

**Comment by dscho** [comment]
Try

```cmd
> set MSYS=noglob

> "\Program Files\git\usr\bin\echo.exe" hi{1}
hi{1}
```

**Comment by bukzor** [comment]
@dscho Is that thing (`$MSYS`) documented somewhere? It certainly doesn't seem to be POSIX.
 
Also, where exactly is git-for-windows getting its coreutils from?
The version posted by MSYS is `5.97.3` but we see `8.24` in this environment.
http://sourceforge.net/projects/mingw/files/MSYS/Base/coreutils/

**Comment by bukzor** [comment]
Found it: https://github.com/git-for-windows/MSYS2-packages/tree/master/coreutils

**Comment by bukzor** [comment]
I can't find any reference to 'noglob' in that repo.

**Comment by bukzor** [comment]
There's a `noglob` defined for the `$CYGWIN32` environment variable which seems to match this behavior: https://cygwin.com/cygwin-ug-net/using-cygwinenv.html

```
(no)glob[:ignorecase] - if set, command line arguments containing UNIX-style file wildcard characters (brackets, braces, question mark, asterisk, escaped with \) are expanded into lists of files that match those wildcards. This is applicable only to programs run from non-Cygwin programs such as a CMD prompt. That means that this setting does not affect globbing operations for shells such as bash, sh, tcsh, zsh, etc. Default is set.
```

The intent seems to be to have bourne-shell-like glob behavior when not using the bourne shell.

**Comment by dscho** [comment]
> There's a noglob defined for the $CYGWIN32 environment variable

Correct. Since MSys2 is a (friendly) fork of Cygwin, the environment variable has been renamed (to avoid interfering with Cygwin when trying to mix and match MSys2 with Cygwin).

> The intent seems to be to have bourne-shell-like glob behavior when not using the bourne shell.

Indeed. Unix users seem to expect globs to work when running from `cmd.exe`, I guess.

**Comment by Radrik5** [comment]
I think it shouldn't expand braces without comma: `x{1}`. Bash doesn't expand such expressions.

**Comment by bukzor** [comment]
The fact that it expands '"{1}"' to  \{1}" is entirely wrong, as well.

**Comment by dscho** [comment]
Hey, feel free to fix this and contribute the fix to the Cygwin project.
