### ISSUE TITLE
git submodule foreach cannot be properly aborted with Ctrl-C

### ISSUE THREAD

**Issue by jobor** [git-for-windows/git#565]
Using git version 2.6.3.windows.1 on Windows 10, 64 bit.

### How to reproduce:
  - open git bash
  - cd into a repository with lots of submodules, e.g. https://code.qt.io/qt/qt5.git
  - run `git submodule foreach "sleep 3"`
  - abort the run with Ctrl-C

### What happens:
Control is given back to the shell but the foreach loop is still running in the background.
Every three seconds another "Entering 'thisandthatrepo'" message is printed.

### What should happen:
The whole foreach loop should be aborted.

**Comment by linquize** [comment]
Win 10 only?

**Comment by jobor** [comment]
It's also reproducable on a Win7 machine.

The issue is *not* reproducable with git-cmd.exe.

**Comment by linquize** [comment]
Have you checkout the submodules?

Clone with submodules: `git clone --recursive`
or
Checkout submodules after clone: `git submodule update --init`

**Comment by jobor** [comment]
Yes, the submodules are checked out.

**Comment by linquize** [comment]
Could you provide an MCVE?

**Comment by jobor** [comment]
mkdir bla
cd bla
git init
git submodule add http://code.qt.io/qt/qlalr.git
git submodule add http://code.qt.io/qt-labs/jom.git
git submodule add http://code.qt.io/qt/qtchooser.git
git submodule foreach "sleep 3"
--> press Ctrl-C

**Comment by rimrul** [comment]
>mkdir bla
cd bla
git init
git submodule add http://code.qt.io/qt/qlalr.git
git submodule add http://code.qt.io/qt-labs/jom.git
git submodule add http://code.qt.io/qt/qtchooser.git
git submodule foreach "sleep 3"

I can confirm this behaviour with Git for Windows 1.9.4 on Windows 8.1 Pro, so it doesn't seem to be a v2/MinTTY issue.

**Comment by rimrul** [comment]
I can't reproduce the issue in Vagrant, so it doesn't seem to be an upstream issue.

**Comment by rimrul** [comment]
This sounds a bit like Alexpux/Cygwin#7

**Comment by dscho** [comment]
I will reopen as soon as there is a MCVE.

**Comment by jobor** [comment]
An MCVE can be found in the "How to reproduce" section of this issue's first comment.

**Comment by dscho** [comment]
> cd into a repository with lots of submodules, e.g. https://code.qt.io/qt/qt5.git

@jobor do you really call that *Minimal*? I do not.

**Comment by jobor** [comment]
My comment from 10 Dec 2015 provides a much smaller example.
I have to admit, it is also not minimal in a mathematical sense.

**Comment by jobor** [comment]
MCVE without need for network access:

1. Create ten non-empty repos
`for i in $(seq 10); do mkdir $i; cd $i; git init; echo x>x; git add x; git commit -m x x; cd ..; done`

2. Add them as submodules to another repo
`mkdir super; cd super; git init; for i in $(seq 10); do git submodule add ../$i; done`

3. Run the submodule foreach command
`git submodule foreach "sleep 3"`

4. Press Ctrl-C and watch how the "Entering so-and-so" messages are still printed in the background while you're working in bash.
