### ISSUE TITLE
Add language selector

### ISSUE THREAD

**Issue by steswi** [git-for-windows/git#566]
Yes I am german but I program everything in english and so I expect that my gui is also in english.
Please notice that it is totally uncommon at least to our developer team to have german speaking developer tools. Often translations are misleading and poor. Please let me choose the gui language.

**Comment by kostix** [comment]
Make sure you have an environment variable named "LANG" set to the
string "en" in your profile (or system-wide), and the standard GUI Git
tools will start to show their UI in English.

You can try locally first.  Say, in Git Bash do

    LANG=en gitk

or in `cmd.exe` do

    set LANG=en
    gitk

**Comment by steswi** [comment]
Thanks. This solution I figured out, too.
It is really annoying to find this solution after I have installed the tool the second time. 
Please add an FAQ about this topic since most german developers I know choose the english version of development tools. This topic is permanent annoyance to many non-english developers.
My bulgarian and estonian co-workers run into the same topics all the time. 

Maybe it is better to modify the launch target inside the windows launcher to instead of your solution:
C:\Windows\System32\cmd.exe /c "set LANG=en_GB && start C:\git-sdk-64\git-bash.exe && exit"
so the cmd window does not stay open.

**Comment by dscho** [comment]
1. we do not ship Git for Windows with locales. But then, maybe you installed something different (you did not say)
2. if you want to see the FAQ improved, just do so. Do not ask others to do your bidding, please.

**Comment by steswi** [comment]
Actually it was the Git SDK I had installed. 
I was not aware that I could contribute to the FAQ page. 
I have added this solution to the FAQ page.

**Comment by dscho** [comment]
> Actually it was the Git for Windows SDK I had installed.

I spend an insane amount of time preparing end user-facing installers. The Git for Windows SDK is intended for contributors who want to improve Git for Windows. Could you please point out how to improve the wording on https://git-for-windows.github.io/, preferably as a Pull Request to https://github.com/git-for-windows/git-for-windows.github.io? Thanks.

**Comment by steswi** [comment]
dscho, I had made a mistake by clicking the the wrong download button and maybe you are annoyed about that. At least I am. Why you don't state this in the frist place. People make mistakes. 

About: "Could you please point out how to improve the wording on https://git-for-windows.github.io/,"
In case you really wonder how this may happen to users here is a short description: I was in a hurry to get the git-bash for windows. So I googled and run just in the frist thing I saw. This was the page https://git-for-windows.github.io/. I was just srcolling down and watched out for the screenshots. These screenshots convinced me to click the nearest download button while scrolling down. Yes I have not read a single word. I was just focused on the screenshots. Since some humans are lead by pictures instead of words I think the wording does not need to be improved. Just simply place the download button in same section as the screenshots or repeat the download butten in the Tools & Feature section.

I won't create a pull request cause I am not experienced in javascript. 

I was annoyed in the frist place about the language settings cause the german version of git gui
fails on "Projektarchive"/"Alle Zweige darstellen" ("Repository"/"Visualize All Branch History")  of my git repository. This error message was presented: 
![gitgui](https://cloud.githubusercontent.com/assets/16242242/11741486/b550ba28-9ff9-11e5-9841-4e53d75f060f.png)
Due to the appearance of a few german words in the error message I tried to switch to the english version. The english version works.

**Comment by dscho** [comment]
> About: "Could you please point out how to improve the wording on https://git-for-windows.github.io/,"
> In case you really wonder how this may happen to users here is a short description: I was in a hurry to get the git-bash for windows. So I googled and run just in the frist thing I saw. This was the page https://git-for-windows.github.io/. I was just srcolling down and watched out for the screenshots.

Makes sense. So adding a screenshot next to the big Download button on the top would have done it?

> I won't create a pull request

If you are satisfied with the way things are, I certainly am, too. Thanks.

**Comment by steswi** [comment]
I guess arranging the screenshots in the same frame near to the download button will help.
I won't create a pull request since I am new to git and I have no real skills in html and javascript. You will reject it anyway. So if you think it is ok to ignore this topic and also this bug in the german version so go ahead.

**Comment by dscho** [comment]
I will never reject good work. And I am not ignoring any topic. What I did, though, is evaluate how interested you are in resolving this issue by estimating how many hours/days of your own time you are willing to spend on a resolution.

**Comment by kostix** [comment]
@steswi, that bug is known, it's not related to Git for Windows (it's found in the upstream Git version as well), and was unfortutately detected after the release was done (as most folks, sadly me included) usually test only what's released so you sort of get what you test :-)

All in all, this bug is already fixed in the upstream Git and the next GfW release won't contain it.

**Comment by steswi** [comment]
@dscho, I have stated that I cannot contribute much due to my limited abilities in git, javascript or tcl. This is why I think you would reject my pull request. Also I guess it will not meet your quality expectation anyway. To be honest I wonder if this is the right method to evaluate how much time people want to spend on an open source project. But maybe it had to be this way. I don't know. But I know for sure I would not join a open source project if it is not a bit of fun or satisfying to a certain extend.

**Comment by steswi** [comment]
@kostix. Thank you for this background information.
