### ISSUE TITLE
XP: Comment -  Path /usr/local/bin:/usr/bin:/bin: isn't on XP

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#57]
While testing on my little XP netbook I noticed that the `echo $PATH` has moved relative to the old MsysGit, so that my personal little BringUptodate script wasn't found. This is with the install from issue #42.

    Philip@PhilipOakley MINGW32 ~
    $ !Br
    BringGitUptodate.sh
    bash: BringGitUptodate.sh: command not found`

i.e. (new)

    Philip@PhilipOakley MINGW32 ~
    $ echo $PATH
    /mingw32/bin:/usr/local/bin:/usr/bin:/bin:/d/Program Files/Windows Resource Kits/Tools:/c/Tcl/bin:[...]

v.s. (old)

    Philip@PHILIPOAKLEY ~
    $ echo $PATH
     /c/Documents and Settings/Philip/bin:.:/usr/local/bin:/mingw/bin:/bin:/d/Program Files/Windows Resource Kits/Tools/:/c/Tcl/bin:[...]

I haven't done any looking yet....

**Comment by nalla** [comment]
The `$PATH` is being constructed by the `/etc/profile` file. If you compare those two files, you'll find out that `export PATH="$HOME/bin:$PATH"` was present in the `msysgit` one. As a workaround if you want to edit your `$PATH`, maybe put that line in your `.bashrc` file.
