### ISSUE TITLE
Windows Installer fails when ssh-agent.exe is running

### ISSUE THREAD

**Issue by nemchik** [git-for-windows/git#574]
To preface this, I use [chocolatey](https://github.com/chocolatey/choco) for installations/upgrades.

When I'm upgrading from one version to the next (today for example 2.6.3 to 2.6.4) the installer fails and complains that a process is in use (without specifying which one). I have found that it is ssh-agent.exe and if I end this process and then rerun the upgrade it succeeds.

Can you please have the installer check for processes like this (not sure if there are any others aside from ssh-agent.exe) and prompt to end the process in order for the installation/upgrade to succeed?

**Comment by dscho** [comment]
This issue is already discussed here: https://github.com/git-for-windows/git/issues/312

**Comment by dscho** [comment]
@nemchik please feel free to continue the discussion in the original ticket.
