### ISSUE TITLE
Unable to install via make

### ISSUE THREAD

**Issue by Pharap** [git-for-windows/git#576]
I've got a copy of the windows version of make and tried to build git-for-windows using make.

I tried make all, make install and make makefile.

It tried to execute sed and sh.exe so presumably either the files haven't been translated from the linux version or there are windows versions of these that aren't packaged with the sources.

**Comment by dscho** [comment]
Please be *very* precise.

From where did you get `make`? *Which* source did you try to build? *What* was the exact output? Have you looked at our [instructions how to build Git at all](https://github.com/git-for-windows/git/wiki/Building-git)?

These are just a couple of all the questions that are still left wide open.

**Comment by dscho** [comment]
This is still unclear, and there has not been any attempt at clearing things up, so I am moving this ticket out of my sight until that changes.
