### ISSUE TITLE
Icons for Shell menu items

### ISSUE THREAD

**Issue by dogancelik** [git-for-windows/git#582]
Right now when you install Git 2.6.4, you don't get icons for shell menu items.

### Before

![a1](https://cloud.githubusercontent.com/assets/486818/12002988/20bf604c-ab18-11e5-9384-e01ba81c045f.png)

### After

![a2](https://cloud.githubusercontent.com/assets/486818/12002989/236b30c8-ab18-11e5-8cc9-4ad2ffde6da3.png)

It is useful to have icons because our eyes catches colors faster.

Reg file for testing:

```ini
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\git_gui]
"Icon"="%SystemDrive%\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico"

[HKEY_CLASSES_ROOT\Directory\shell\git_gui]
"Icon"="%SystemDrive%\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico"

[HKEY_CLASSES_ROOT\Directory\Background\shell\git_shell]
"Icon"="%SystemDrive%\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico"

[HKEY_CLASSES_ROOT\Directory\shell\git_shell]
"Icon"="%SystemDrive%\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico"
```

**Comment by stamepicmorg** [comment]
thnx, apply that. awesome.

**Comment by dscho** [comment]
@dogancelik how about making the correct change to `build-extra` (e.g. around [here](https://github.com/git-for-windows/build-extra/blob/ecc41ae4b69bb992095388a128bd68fc52fbfbab/installer/install.iss#L1535-L1545)), committing with a [good commit message](https://github.com/git-for-windows/git/wiki/Good-commits#commit-messages), testing to verify that everything works as intended and then opening a Pull Request?

**Comment by dogancelik** [comment]
Yes I wanted to open a pull request first after I found the setup file but I didn't know how to edit that file. I'll look into it again :)

**Comment by kisstkondoros** [comment]
Hi I've updated the pull request https://github.com/git-for-windows/build-extra/pull/97
