### ISSUE TITLE
Git for windows broke after restart.

### ISSUE THREAD

**Issue by ZetaHunter** [git-for-windows/git#583]
So I rebooted my system and when I tried to use git-bash or any other form of git all I was getting is
```
fatal: open /dev/null or dup failed: No such file or directory
```
It's actually been a week since this started happening but I've decided I want it to work again.
I am on Windows 10 x64.

**Comment by ZetaHunter** [comment]
I have reinstalled git about 5 times now, that did not yield any result.

**Comment by dscho** [comment]
Hmm. This report does not contain a whole lot of information to go on. Maybe Git for Windows failed to install properly and the Git Bash has to be run as administrator once to fix this.

**Comment by ZetaHunter** [comment]
Running git-bash as administrator did not yield any results...
All I have is mintty.exe.stackdump file:
```
Exception: STATUS_ACCESS_VIOLATION at rip=00100405BAF
rax=FFFFFFFFFFFFFFFF rbx=000000000024C390 rcx=0000000000000000
rdx=03FFFFFFFFFFFFFF rsi=000000010042DE00 rdi=000000000024C38C
r8 =0000000000000001 r9 =0000000000000001 r10=8000000000000000
r11=0000000000000246 r12=000000010042DDA8 r13=000000010042E900
r14=000000000024CA78 r15=000000000024C4E0
rbp=000000000024C398 rsp=000000000024C350
program=C:\git\usr\bin\mintty.exe, pid 3600, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000024C398  00100405BAF (0000024C470, 7FFF962DA4C0, 7FFF9631A890, 00600000001)
0000024C470  0010041AC01 (001800CE772, 0000000002F, 006000420E7, 0000000000B)
0000024CBC0  001800483C1 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0018004603C (0000024CD00, 0000024CD00, 0000024CD00, 00000000002)
00000000000  001800460D4 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100419641 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
00000000000  7FFF95852D92 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFF97BE9F64 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

**Comment by dscho** [comment]
> Running git-bash as administrator did not yield any results...

I did not mean for you to wait for me to suggest every possible fix or every piece of information that might be helpful to understand or resolve the issue. Slavishly trying out exactly what I say (and nothing else) will most likely not lead to a solution in anything remotely resembling a timely manner.

Having said that, here is another suggestion: run Git CMD. If that works, run `C:\Program Files\Git\bin\bash.exe -l -i` from that cmd (but please adjust the path accordingly if it is different in your setup before running the command...!).

Also, the exact Windows 10 version has *not* been provided, nor the bitness of the Git for Windows version installed, so I have no idea whether it is possible that [this work-around](https://github.com/git-for-windows/git/wiki/32-bit-issues#adjusting-msys-20dlls-address-range-manually) is required. But it might.

With these suggestions, my quota of wild shots in the blue is expended.

**Comment by ZetaHunter** [comment]
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10240 N/A Build 10240
System Type:               x64-based PC
```
Git for Windows x64, that command above returned `bash: /dev/null: No such device or address`
It seems that everything that is from Unix world will crash and fail because somehow /dev/null doesn't exist on my system.

I am sorry for lack of details but its just this is the weirdest bug I've ever seen and reinstalling git for windows didn't yield any result.

I am nearing the answer that the only way to make it work is to reinstall windows...

**Comment by ZetaHunter** [comment]
Closing this as I reinstalled windows which fixed the issues.
