### ISSUE TITLE
russian and other locales support

### ISSUE THREAD

**Issue by stamepicmorg** [git-for-windows/git#584]
Hello.
Is it possible to add language support for the Russian language in the new version?
It was at all "msysgit" pre-releases, and it exists in the current SDK.

Thanks.

**Comment by Aleks-Z** [comment]
Same trouble

**Comment by kostix** [comment]
@Aleks-Z, please refrain from "me too"-style comments.  They pollute the issue tracker, add nothing to the discussion and actually do not affect the motivation of those who are able to fix things -- quite contrary, they might get them angry.

**Comment by kostix** [comment]
@stamepicmorg, #496, #403, #378 were not enough? What warranted creating another issue?

**Comment by stamepicmorg** [comment]
ok. thanks. sorry.

**Comment by stamepicmorg** [comment]
What prevents the installer to create a second with only localizations?

Or, as has been previously suggested to make two versions of the installer - light (current) and complete?

At each issues a new answer.

**Comment by stamepicmorg** [comment]
hmmm. ok. can i try to create standalone installer of languages and if it will be work fine i will add it as pull request at "build-extra" repository?

**Comment by dscho** [comment]
These questions have been answered already, with `WITH_L10N=1` being the flag to use when generating the installers and portable Gits.

If you truly care about this issue, here is the way to go forward:

1. [make an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer)
2. patch the script that is used to put together new Git for Windows releases ([`/usr/src/build-extra/please.sh`](https://github.com/git-for-windows/build-extra/blob/master/please.sh)) to generate localised installers/portable Gits, too (basically just search for `PortableGit-`, bonus points for refactoring the enumeration of the installer/portable Git files).
3. verify that your changes work (you will need both 32-bit and 64-bit SDKs for that)
4. commit, push & open a Pull Request

I am curious to see your progress.

**Comment by stamepicmorg** [comment]
@dscho Thank you for answer! I will really try it.

Sorry for my bad English, Merry Christmas and Happy New Year!
