### ISSUE TITLE
Git for Windows misses nested submodules (submodule in submodule)

### ISSUE THREAD

**Issue by pal1000** [git-for-windows/git#585]
Encountered with v2.6.4. 

Everything started when I wanted to get my copy of <a href='https://github.com/hrydgard/ppsspp'>PPSSPP</a> repository up-to-date and to build from it.  I updated my copy as usual:
<code>
git pull -v --progress "origin"
git submodule update --init
</code>
and then built. Build came failed with ppsspp\ext\armips\ext\tinyformat\tinyformat.h not found.
I checked the <a href='http://buildbot.orphis.net/ppsspp/'>Official buildbot</a>. No problem there.
The only obvious difference is that I have Visual Studio 2015 November update installed while the buildbot doesn't have it as I heard.
I then decided to dive in that folder to see if that file is there. Both ext and tinyformat folders exist but no files. I thought it was a glitch so I wiped my local copy and cloned anew. Same problem stroke again. Manually browsed to ppsspp\ext\armips and performed 
<code>
git submodule update --init
</code>
Git finally cloned ext/tinyformat nested submodule resulting in successful build.
Expected behavior for git clone is to pick up nested submodules as well.

**Comment by linquize** [comment]
Did you enter `--recursive` option?
