### ISSUE TITLE
include column.exe from util-linux package

### ISSUE THREAD

**Issue by JanSchulz** [git-for-windows/git#586]
The git-extras package currently has the problem that some of the commands depend on `column`, which is included in msys util-linux package. Unfortunately, it is not included in the git for windows install and you have to copy the file from a msys install. Would it be possible to include `column.exe`?

https://github.com/tj/git-extras/blob/master/Installation.md

> Last, to use git-line-summary, git-summary and git-ignore-io, you need to copy column.exe from a msys2 installation from folder-your-msys2-installed/usr/bin to folder-your-git-installed/usr/bin .

**Comment by JanSchulz** [comment]
I can send a PR for this against git-for-windows/build-extra by adding that as a new exception in https://github.com/git-for-windows/build-extra/blob/master/make-file-list.sh#L103

**Comment by dscho** [comment]
Sure, a PR would be appreciated, especially with [a kick-ass commit message](https://github.com/git-for-windows/git/wiki/Good-commits#commit-messages) (including the fact that `column.exe` weighs only 25K and depends only on `msys-2.0.dll` and `msys-intl-8.dll`, both of which we ship already).

**Comment by JanSchulz** [comment]
@dscho: done, here: https://github.com/git-for-windows/build-extra/pull/92
