### ISSUE TITLE
[Feature Request] Add other unix command line utilities: wget, nano, grep, etc...

### ISSUE THREAD

**Issue by webmaster442** [git-for-windows/git#587]
Git Bash is great, but it misses utilities like wget, nano or grep. These Utilities are available in the default installation of any MinGW environment. Please include them in the GIT Bash.

**Comment by dscho** [comment]
> Git Bash is great

It is.

> but it misses utilities like wget, nano

Those utilities are not part of Bash, nor of Git. So it is unreasonable to expect Git for Windows to ship them.

> or grep.

Not true:

```sh
$ grep
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

Do not rely on this, though: It is only a historical wart that `grep` is distributed with Git for Windows.

> Please include them in the GIT Bash.

You clearly desire a full-blown Open Source distribution such as [MSys2](https://msys2.github.io/), not Git for Windows (whose sole mission is to provide Git, and only Git, to Windows users).
