### ISSUE TITLE
Insaller - provide a msi file for installing git for windows

### ISSUE THREAD

**Issue by bleissem** [git-for-windows/git#589]
Hello everyone, 
To be able to deploy a MSI package through GPO, the installer should generate a MSI file in addition to the exe files that are available for download under https://github.com/git-for-windows/git/releases .
Regards 
Alex B.

**Comment by dscho** [comment]
@bleissem thanks for your suggestion. At this point, however, the Git for Windows project suffers no shortage of tasks that really need to be completed. That is because the balance between people who ask for things to do vs people who actually do them is seriously out of whack.

Therefore I have to close this ticket unaddressed, unfortunately.

**Comment by bleissem** [comment]
@dscho thanks for your fast reply. Can I (somehow) contribute to this as a developer ?

**Comment by dscho** [comment]
@bleissem you can! Best would be to coordinate with @robmen via https://github.com/robmen/gitsetup/issues/1, though, I guess, because he already has some WiX setup working and was open to working with me (or you :smile:) to integrate it into Git for Windows' release process.

**Comment by kostix** [comment]
@bleissem, also see [this](https://github.com/msysgit/git/issues/333).

**Comment by dscho** [comment]
@kostix there is unfortunately no useful information in that ticket except your hint at using WiX and working around the lack of an `.msi` via `/SAVEINF`/`/LOADINF`. So it might be more useful to concentrate on gitsetup (which already has a working setup to create `.msi` files).

**Comment by kwill** [comment]
@dscho In light of the this issue/request and those linked above, could you update https://github.com/git-for-windows/git/wiki/FAQ with (something like) "When will you provide an MSI for installation via Group Policy?" ... it would be nice to be able to point Windows network admins to an official answer and/or use it to motivate for development time or even just testing.

**Comment by kwill** [comment]
You might also want to explicitly mention the Portable version in the answer as an alternative in the meanwhile. Users could simply run the portable version, or network admins could deploy it via a GPO script. Not as tightly integrated as an MSI, but it may be "good enough" for some use cases.

**Comment by PhilipOakley** [comment]
> @dscho In light of the this issue/request and those linked above, could you update https://github.com/git-for-windows/git/wiki/FAQ with (something like) "When will you provide an MSI for installation via Group Policy?" ... it would be nice to be able to point Windows network admins to an official answer and/or use it to motivate for development time or even just testing.

David,

You could just edit the FAQ pages directly with your ideal answer to the appropriate Question (It's worked for me in the past ;-).

Philip

**Comment by dscho** [comment]
> could you update https://github.com/git-for-windows/git/wiki/FAQ with (something like) "When will you provide an MSI for installation via Group Policy?"

I can't because there is no concrete timeline for that feature.

**Comment by kwill** [comment]
@PhilipOakley @dscho I have contributed https://github.com/git-for-windows/git/wiki/FAQ#is-there-an-msi-for-installation-via-group-policy (with no mention of timeline)

**Comment by PhilipOakley** [comment]
> @PhilipOakley @dscho I have contributed https://github.com/git-for-windows/git/wiki/FAQ#is-there-an-msi-for-installation-via-group-policy (with no mention of timeline)

Looks like a good start. 

I added a few words to suggest folks should/could try testing the current dev msi (which was the last point in the issues, and something dscho had mentioned ;-)

Good to have a FAQ on the issue.

Philip
