### ISSUE TITLE
Missing bison

### ISSUE THREAD

**Issue by pzion** [git-for-windows/git#591]
First, thanks for all the hard work making a great git environment for Windows.

I'm installing a new machine here with the latest msys git and I've noticed that it no longer installs bison (at least by default).  Is there a way to have bison installed with recent versions, or do I have to go back to the older version I was using (I believe it was 1.9.1)?

**Comment by sprintr** [comment]
You can copy the binaries from the pre 2.x build and use it in the new environment or [download](http://gnuwin32.sourceforge.net/packages/bison.htm) then.

**Comment by pzion** [comment]
Thanks!

**Comment by dscho** [comment]
For the record: please do not confuse *Git for Windows* for a software distribution. You most likely want to switch to [MSys2](https://msys2.github.io/). The mission of *Git for Windows* really is to provide a working Git to Windows users, and all the tools we ship are merely intended to support Git. Read: everything that is not strictly necessary to run Git is fair game for removal in future versions of Git for Windows.

**Comment by dscho** [comment]
> You can copy the binaries from the pre 2.x build

Please note that this usage is not at all supported. Git for Windows 2.x is based on MSys2 (which sports its own `bison` package), and I would appreciate if problems would *not* be brought to my attention when they are incurred solely from trying to mix and match MSys2 with whatever random other software you find in the world wild web.

**Comment by pzion** [comment]
Yes, when I tried to mix-and-match in fact it didn't work.  We simply reverted to using msys git 1.9.5.  Thanks!

**Comment by linquize** [comment]
What git for windows 2.x is better than 1.x is that 
it ships more up-to-date and more basic Unix utilities so that many shell scripts can work.

**Comment by dscho** [comment]
> We simply reverted to using msys git 1.9.5.

@pzion you are of course free to do that.

It's a bad solution, though, because you are reverting several critical security fixes, and you are reverting to a project (msysgit) that has been retired for almost half a year now, which is eons by Git's standards.

Worse, I already presented a better option, and I see no reasoning why that should have been rejected.

But as I said, it's your freedom to do whatever you like. And now I will get out of your hair and not take any more of your time.

**Comment by pzion** [comment]
I'm experimenting now with simply having both 2.6.x and 1.9.5 installed at the same time, and simple putting 2.6.x first on the path so that the old bison gets picked up with the right DLLs.  It seems like this might be the best solution in the long term, keeping us up-to-date with git as well as providing us with a working bison.

**Comment by pzion** [comment]
Oh, and thanks for the tip re: using msys2 instead.  I will take a look at this as an option as well.

**Comment by PhilipOakley** [comment]
@pzion, @sprintr I think what is needed (for your usage style) is [appears to be] somewhere between the G4W SDK and the plain G4W, which would have the MSYS2, the basic utils you expect and G4W (as an install). That is, something that mimics the expected packages from the old Msysgit...  

That said, it would need someone to create and test such an intermediate package, though there may even be better places to host such a package. It may be an interesting activity if you want to have a go (it's your itch to scratch)... as @dscho has noted, it's a 'wontfix' from the core dev side.
--
Philip

**Comment by pzion** [comment]
Just an FYI, msys2 seemed to work well at first but then I hit a problem where it wasn't converting the \ to / in the bison output which created compile errors (escape sequences in strings).  Since I don't want to actually make any changes to our code (I'm migrating to a new build machine and I must be getting identical output with no source code changes), I'm simply going to go with msysgit-1.9.5 with which bison just works.  Thank again for everyone's feedback!
