### ISSUE TITLE
Ship git-p4 with Git for Windows

### ISSUE THREAD

**Issue by hickford** [git-for-windows/git#594]
Hi. Are there any plans to ship [git-p4](https://git-scm.com/docs/git-p4) with [Git for Windows]( https://git-for-windows.github.io/)?

    >git p4
    fatal: 'p4' appears to be a git command, but we were not
    able to execute it. Maybe git-p4 is broken?

    >git version
    git version 2.7.0.windows.1

**Comment by linquize** [comment]
But this needs python dependency that makes g4w larger.

**Comment by PhilipOakley** [comment]
@hickford Pehaps look at installing the G4W SDK and checking if a suitable Python is available there. 

I have a vague mamory that it may already be available in the SDK (i.e. a package on top of MSYS2, in the same way that Git is apackage on top of MSYS2 ;-)

**Comment by dscho** [comment]
Yes, Python is already in the SDK, and yes, it would make Git for Windows substantially larger.

Having said that, @hickford: Git for Windows is about empowering the community. As such, you can [make your own installer](https://github.com/git-for-windows/git/wiki/Making-an-installer), and you can even [help us bundle larger installers in addition to the current one](https://github.com/git-for-windows/build-extra/blob/master/installer/release.sh).

**Comment by hickford** [comment]
Thanks for your replies. I have Python on my computer already, can I use git-p4 with that?

    >py -2 "C:\Program Files\Git\mingw64\libexec\git-core\git-p4"
    usage: C:\Program Files\Git\mingw64\libexec\git-core\git-p4 <command> [options]

    valid commands: clone, rollback, debug, commit, rebase, branches, sync, submit

    Try C:\Program Files\Git\mingw64\libexec\git-core\git-p4 <command> --help for command specific help.

**Comment by dscho** [comment]
The honest answer: no idea. It depends, most likely, how well your Python plays with the expectations of Git for Windows. As there are multiple Pythons out there, you are pretty much on your own if you want to use an existing Python (you would not be on your own if you instead decided to help with the installer business so that others can benefit from `git-p4`, too).

**Comment by linquize** [comment]
I concern the size of installer.
If someone has not been using `git-svn` for years, then he probably does not want to ship perl either.

**Comment by dscho** [comment]
> If someone has not been using git-svn for years, then he probably does not want to ship perl either.

That statement incorrectly assumes that `git svn` is the only user of Perl in Git for Windows. That is incorrect. `git ls-files \*.perl` in `/usr/src/git/` will tell you the true story.

**Comment by dscho** [comment]
@hickford are you interested at all in helping us provide installers including `git-p4`?
