### ISSUE TITLE
scp.exe run into error on ver 2.7.0 64bit on Windows 10

### ISSUE THREAD

**Issue by neoedmund** [git-for-windows/git#595]
```
> scp xxx yyy
      0 [main] scp 3248 D:\Program Files\Git\usr\bin\scp.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
    463 [main] scp 3248 cygwin_exception::open_stackdumpfile: Dumping stack trace to scp.exe.stackdump
      0 [main] scp 2304 fork: child -1 - forked process 3248 died unexpectedly, retry 0, exit code 0x100, errno 11
fork: Resource temporarily unavailable
```
occurs on `Git-2.7.0-64-bit` on `Windows 10 64bit`

However I tried `Git-2.7.0-32-bit` on `Windows 10 64bit`, it works normally.

**Comment by neoedmund** [comment]
```
> set
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
```

I **guess** the problem is related on the `env ` variables makes the Windows looks like 32bit arch?

**Comment by dscho** [comment]
Unlikely. However, it might be a bug that was fixed recently in the MSys2 runtime. Maybe you can download https://dl.bintray.com/git-for-windows/pacman/x86_64/:msys2-runtime-devel-2.3.1.33884.84870b7-1-x86_64.pkg.tar.xz, extract `msys-2.0.dll` from it, overwriting the existing one, and test again.

**Comment by neoedmund** [comment]
The problem is because run scp(64bit) in 32bit command line(opened by 32bit Console[http://sourceforge.net/projects/console]). 
So it seems nothing need to be fixed.
Sorry about that.
