### ISSUE TITLE
Windows install appends rather than prepends to PATH

### ISSUE THREAD

**Issue by staff0rd** [git-for-windows/git#599]
In the Git 2.7.0 install wizard on Windows 10, the following options are presented;

<img width="371" alt="git" src="https://cloud.githubusercontent.com/assets/6289998/12316477/3755488a-badb-11e5-87f9-67a28d507baf.PNG">

Selecting the third option warns that it will:

> override Windows tools like "find" and "sort".

However, because the installer appends the `bin` directories to `PATH`, it does not override these tools, and the user (expecting to override these tools) then needs to manually edit the `PATH` and move the `bin` paths to a higher precedence (than the path to the windows tools).

**Comment by dscho** [comment]
I am pretty certain that we should *not* prepend the `PATH` (because many batch scripts rely on `find` having Windows' own behavior), and that therefore the warning is bogus.

**Comment by dscho** [comment]
@staff0rd are you quietly agreeing? :smile:

**Comment by staff0rd** [comment]
@dscho not neccessarily - I just assume you know more of the problem space than I do.  Personally I have no issue with the warning as it stands, and as such expected it to prepend.  I guess if you were to take the stance that the warning is bogus, and you'll never prepend the path, then there almost needs to be a warning that points out that adding the path will not supersede the shell tools that already exist in your path.

**Comment by staff0rd** [comment]
Also I think by closing this you're implying a new issue should be opened pointing out that the warning is bogus?

**Comment by dscho** [comment]
> > @staff0rd are you quietly agreeing? :smile:

> not neccessarily

Sorry, then, I am not a mind reader.

> Also I think by closing this you're implying a new issue should be opened pointing out that the warning is bogus?

I would really appreciate it if you could spend the time to work on a Pull Request ([make an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer) first, then patch [the section in install.iss](https://github.com/git-for-windows/build-extra/blob/e35b60c3cc0148cb052f64a2d2a9b06b9b5681f8/installer/install.iss#L657-L669) accordingly, then test using the [`--debug-wizard-page=PathOption`](https://github.com/git-for-windows/build-extra/commit/3106bcfda82bdafa505d12baa855c524c35d82fe) before opening the Pull Request).
