### ISSUE TITLE
quotes backslashes in path in a diff textconv are not passed to the called command

### ISSUE THREAD

**Issue by JanSchulz** [git-for-windows/git#601]
```
[diff "ipynb"]
    textconv = "test.bat -f C:\\Users\\jschulz\\Dropbox\\Programme\\cmder\\vendor\\jasc\\nbflatten.jq --arg show_output 0"
```

with `test.bat` simple 
```
@echo %* >> test.txt 
```

In this case `test.bat` will be called with `-f C:UsersjschulzDropboxProgrammecmdervendorjascnbflatten.jq --arg show_output 0 Example.ipynb`

-> the escaped backslashes are removed

Adding quote around the path (which shouldn't be needed here as there are no spaces?) let this work:

```
[diff "ipynb"]
    textconv = "test.bat -f \"C:\\Users\\jschulz\\Dropbox\\Programme\\cmder\\vendor\\jasc\\nbflatten.jq\" --arg show_output 0"
```

**Comment by dscho** [comment]
I *think* this is by design, as the filter settings are *shell* commands. You could also escape the backslashes by backslashes (which admittedly looks very ugly).

An alternative would be to use POSIX-style paths:

```ini
[diff "ipynb"]
    textconv = "test.bat -f $HOME/Dropbox/Programme/cmder/vendor/jasc/nbflatten.jq --arg show_output 0"
```

(Untested, as I lack an easy way to reproduce the issue.)

**Comment by dscho** [comment]
@JanSchulz I will simply assume that the alternative worked for you.

**Comment by JanSchulz** [comment]
yep, sorry for not responding here.
