### ISSUE TITLE
Merely changing file type from normal file to symlink does not commit

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#602]
For any committed files,
If I merely change file type from normal file to symlink,
`git commit` does not commit
```
nothing to commit, working directory clean
```

```
$ git diff-index master
:100644 120000 e7b4ad382349ff96dd8199000580b9b1e2042eb0 e7b4ad382349ff96dd8199000580b9b1e2042eb0 T      lib/1.txt
```

However, `git commit` works if I mark executable bit instead of changing to symlink
```
$ git diff-index master
:100644 100755 e7b4ad382349ff96dd8199000580b9b1e2042eb0 e7b4ad382349ff96dd8199000580b9b1e2042eb0 M      lib/1.txt
```

There is no problem for newly added files that mark as symlink immediately.
This means if I did not mark as symlink during initial commit, I fail to commit the change afterwards.

**Comment by dscho** [comment]
MCVE, please.

**Comment by linquize** [comment]
Case 1:
```
mkdir lib
echo 1 > lib/1.txt
echo 2 > lib/2.txt
git init
git add .
git commit -m "initial commit"
```
Then mark `lib/1.txt` as symlink (modify index using libgit2 using TortoiseGit shell property page)
```
git add lib/1.txt
git commit -m "Mark 1.txt as symlink"     # commit failure
nothing to commit, working directory clean
```

Case 2:
```
echo 1 > 1.txt
echo 2 > 2.txt
git init
git add .
git commit -m "initial commit"
```
Then mark `1.txt` as symlink (modify index using libgit2 using TortoiseGit shell property page)
```
git add 1.txt
git commit -m "Mark 1.txt as symlink"
```
commit success, however an empty commit is created, that means file mode 120000 is not committed.

If you re-run case 1, case 2 with **mark as executable bit** instead of symlink, it works without problem.

Case 3:
```
mkdir lib
echo 1 > lib/1.txt
echo 2 > lib/2.txt
git init
git add .
```
Now modify index mark symlink, then do initial commit
```
git commit -m "initial commit"
```
Case 3 OK, committed file is marked as symlink.

**Comment by dscho** [comment]
> modify index using libgit2 using TortoiseGit shell property page

Umm. I asked for a *Minimal*, Complete & Verifiable Example.

Sorry, cannot help.

**Comment by linquize** [comment]
Please run my above case1, case2, case3 as MCVE.

**Comment by dscho** [comment]
> Please run my above case1, case2, case3 as MCVE.

@linquize you and I have very, very different ideas of what makes something "minimal", apparently. So no, I decline. I won't run above cases because that would require me to download and install TortoiseGit and then find some property page setting you vaguely refer to. I am busy enough as it is, thankyouverymuch.

If you come up with a truly minimal example, such as a tiny shell script I can verify and run, then I may give this another shot.

But hey, maybe you can find someone else to help you. :stuck_out_tongue_winking_eye:

**Comment by Radrik5** [comment]
@linquize could you try marking the file as a symlink using `git update-index`?
See example in https://github.com/git/git/blob/master/t/t2102-update-index-symlinks.sh

**Comment by linquize** [comment]
`git update-index` does not have an option to mark as symlink. I did not know the method as  @Radrik5 mention. So I manipulated the index file directly by just changing the **mode field** in the index file,  but  **without changing the mtime field** in the index file.

**Comment by Radrik5** [comment]
I cannot reproduce the problem using Git commands and default `core.symlinks=false`. Maybe there is something wrong with TortoiseGit or libgit2 or your Git configuration is different.
```
~ $ git version
git version 2.7.0.windows.1

~ $ git init symlink_test && cd symlink_test
Initialized empty Git repository in C:/Users/Radrik5/symlink_test/.git/

~/symlink_test $ echo -n 2.txt > 1.txt
~/symlink_test $ echo -n test > 2.txt
~/symlink_test $ git add 1.txt 2.txt
~/symlink_test $ git commit -m "Initial commit"
[master (root-commit) 8dd39b8] Initial commit
 2 files changed, 2 insertions(+)
 create mode 100644 1.txt
 create mode 100644 2.txt

~/symlink_test $ git ls-files -s
100644 6757339cac0a67e64bdcc143cf7e317dde35deab 0       1.txt
100644 30d74d258442c7c65512eafab474568dd706c430 0       2.txt

~/symlink_test $ git update-index --cacheinfo 120000,6757339cac0a67e64bdcc143cf7e317dde35deab,1.txt

~/symlink_test $ git add 1.txt # Not needed but it was in the example

~/symlink_test $ git diff-index master
:100644 120000 6757339cac0a67e64bdcc143cf7e317dde35deab 6757339cac0a67e64bdcc143cf7e317dde35deab T      1.txt

~/symlink_test $ git commit -m "Mark 1.txt as a symlink"
[master 117fe75] Mark 1.txt as a symlink
 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite 1.txt (100%)
 mode change 100644 => 120000
```
