### ISSUE TITLE
gitk loads the commit list very slowly

### ISSUE THREAD

**Issue by bogdanb** [git-for-windows/git#604]
There’s something screwy going on with gitk: for the last few weeks, it started taking a very long time to start up. 

I just ran it with “gitk --all &”, and it took nine seconds before it finishes reading the commits. This is on a pretty small repository (.git is ~11MB, git ls-files shows 200 files, and there are about 450 commits). 

(Unlike other reports I’ve seen, it’s only gitk that’s slow. On the same repo, “time git log --all > /dev/null” for example shows 0.154s real, 0.0s user and 0.016s sys time.) 

After it finishes loading, it works well as far as I can tell, until I tell it to updat (F5) or reload (Shift-F5), when it locks up for ~ten seconds again.

During this time, Windows shows me the “working” cursor, and I can’t even move or minimize the gitk window. (Although I can Alt-Tab or click to switch to other windows, and the rest of the system works normally.) Process Explorer doesn’t show anything suspicious (the wish and git processes never rise above 3-4% processor, and I/O is low as well).

Start-up and reload was very fast (<1s) a few weeks ago.

I don’t know how to investigate further. This is a work machine for Java development, and I don’t have much in the way of debugging tools for other languages.

For the record, the OS is Window 7 Enterprise (Service Pack 1) 64bit. The slow down was happening with git-for-windows 2.5.1 as well as with 2.7.0, which I just installed (both 64bit).

I have a suspicion that it’s something network related: my workplace has some pretty paranoid network admins, and one issue I’ve hit in the past is that the proxy sometimes just ignores requests it doesn’t like (without explicitly rejecting them), and that can cause some software to just lock up for a while until its requests time-out. I have no idea how to check if this is indeed causing the problem or how to fix it. 

There are also about a dozen network shares mounted as drives letters; I don’t use them personally, but if gitk for some reason tries to read them I’m pretty sure they’re slow enough to cause the issue. “ls /{each mounted drive letter}” takes 30 seconds. I don’t know how to unmount them in mingw to test.

**Comment by dscho** [comment]
Why don't you run [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor) to find out?

**Comment by bogdanb** [comment]
@dscho: I didn’t because I didn’t know it existed. But I tried right now and it doesn’t run. As far as I can tell, it needs to load a device driver at runtime, and the domain configuration in my workplace doesn’t allow it. (I can only install user-mode software, the security department here is really paranoid.)

**Comment by bogdanb** [comment]
I don’t know TCL, but looking through the gitk sources I found some commented out log messages. 

There’s one in “proc chewcommits” that says “overall 8863 ms for 355 commits” (bit more if I add more logging), then “8 arcs, 355 commits”. I tried adding a few more trace messages, but I couldn’t yet identify exactly where it spends the time.

I’m appending a log recorded during the startup with some trace messages added by me. Maybe someone can suggest other points that would be useful to trace exactly what causes the delay.

(The number at the start is the number of milliseconds elapsed since start, where “start” means a global variable initialized with “[clock clicks -milliseconds]” right below the “package require” at the top.)

[output.txt](https://github.com/git-for-windows/git/files/92277/output.txt)

**Comment by bogdanb** [comment]
@dscho: I happened to restart the computer today for unrelated reasons, and after the reboot the problem disappeared completely. No idea what was wrong. I guess you could file this under “can’t reproduce”, although I’d still like advice on logging what gitk does, in case it comes back.

**Comment by kjeremy** [comment]
This definitely occurs for me as well but not always.  I've been trying to find out why but it's not 100% reproducible.
