### ISSUE TITLE
permission to write the file on version 2.7

### ISSUE THREAD

**Issue by marklmh** [git-for-windows/git#605]
Hi, 

Basically, I used Tortoise Git on the window and the output folder on the Linux shared driver.  

I used Git-1.8.5.2-preview20131230.exe before, and didn't have any issue.

However, after I upgraded to Git-2.7.0-64-bit.exe, I can't do git clone for any git deposit, it's showed error message to write file something like .git\objects\XXXX18588c7e4463b8541b1bd2eb7cbf5930cf8fb014XXX, and permission deny.

Summery of issue for Git-2.7.0-64-bit.exe
It's no issue on the local disk, but had issue with Linux shared driver. And previous version as I listed above didn't have any issue. 

I like this tool, but I can't update to Git-2.7.0-64-bit.exe

**Comment by dscho** [comment]
Sorry, without precise information, there is nothing anybody can do to help. Error messages should be pasted verbatim, not repeated vaguely in prose.
