### ISSUE TITLE
ASLR not enabled for Git for Windows executables

### ISSUE THREAD

**Issue by xiaoyinl** [git-for-windows/git#608]
It seems most of the executables of Git for Windows didn't have ASLR enabled, such as git-bash.exe, git-cmd.exe, unins000.exe, bin/bash.exe, bin/git.exe, bin/sh.exe, etc. Are there any reasons for not enabling ASLR for these files?
Version: 2.6.3.windows.1

**Comment by dscho** [comment]
Hmpf. Would have been nice to clarify that acronym. And also how you found out that those executables do not use randomization.

BTW `unins000.exe` is completely uninteresting in this context because it requires administrator privileges to run and takes no input.

> Are there any reasons for not enabling ASLR for these files?

Yes. People wanting it have not contributed a patch enabling it :stuck_out_tongue_winking_eye:

**Comment by kostix** [comment]
@dscho, that's Address Space Layout Randomization: a technique to mitigate certain kinds of attacks which rely on particular addresses of the mapped libraries to jump to (after stack smashing etc).

See [this](https://github.com/rust-lang/rust/issues/16514) for instance (I'd say, ASLR is not there yet ;-) ).

**Comment by geraldcombs** [comment]
GNU ld's ASLR support is currently broken: https://sourceware.org/bugzilla/show_bug.cgi?id=19011

**Comment by ismail** [comment]
@geraldcombs that bug says the defaults are insecure hence this bug. If you look at the ffmpeg patches there it just manually adds flags for aslr and such.

**Comment by dscho** [comment]
@kostix thanks for spelling it out (I actually knew what it was, but I found it bad form to post an incomplete report).

@ismail I would really love it if you could open a Pull Request that adds the respective settings to the `BASIC_LDFLAGS` in the [respective section of `config.mak.uname`](https://github.com/git-for-windows/git/blob/78ce6bc19e6b7ce9433b889b2a67d53b8fbeb557/config.mak.uname#L543-L567).

**Comment by ismail** [comment]
@dscho Please have a look at https://github.com/git-for-windows/git/pull/612 but sadly I can't test this. If you can do a test build I can check.
