### ISSUE TITLE
Integrated OpenSSH_6.6.1 vulnerable.

### ISSUE THREAD

**Issue by Haocen** [git-for-windows/git#613]
According to:
http://www.openssh.com/security.html
OpenSSH_6.6.1 is affected.

**Comment by dscho** [comment]
Please follow our [issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) as asked politely on our [home page](http://git-for-windows.github.io/#contribute).

In particular, be as verbose as necessary to understand the issue (no, just slapping a link into the report does not do the job).

And to avoid unnecessary churn on the side of those who actually do the actual work, you really need to search the existing tickets. In this particular case, you would have found #603.

**Comment by Haocen** [comment]
Hi, sorry for bothering you with not including enough information.
As you mentioned, I really should have searched closed tickets as well.
Currently at 2:26 AM Monday, January 18, 2016 UTC time,
What I have found is:
1. I download latest version for windows x86_64 from https://git-for-windows.github.io/ :
<img width="481" alt="hash" src="https://cloud.githubusercontent.com/assets/10842569/12381878/924eef16-bd60-11e5-8db5-32aa28f91b13.png">
Here is the hash info for the specific executable I downloaded.
2. I installed it over previous version on my windows server 2012r2 :
<img width="645" alt="win2012r2" src="https://cloud.githubusercontent.com/assets/10842569/12381882/bb84f6fa-bd60-11e5-94dc-d09f4cc5c5b4.png">
3. I checked the version of OpenSSH:
<img width="668" alt="openssh" src="https://cloud.githubusercontent.com/assets/10842569/12381885/c7878ce2-bd60-11e5-84e4-cb1ee4f3d0fd.png">
It said its version is 6.6.1.

So I think an update to the binaries is necessary as the source code already fixed the problem.

**Comment by linquize** [comment]
2.7.0.windows.1 has the old binary .Please wait for next release

**Comment by dscho** [comment]
Also note that pasted text is much better than images. Your pasted images render the notification mails next to useless.

**Comment by rimrul** [comment]
Oftopic: Did we intentionally remove the following message on the switch to 2.X?

>Welcome to Git (version 1.9.4-preview20140929)
Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

**Comment by dscho** [comment]
> Did we intentionally remove the following message on the switch to 2.X?
> 
> > Welcome to Git (version 1.9.4-preview20140929)
> > Run 'git help git' to display the help index.
> > Run 'git help ' to display help for specific commands.

No, it was not intentional (but then, the message was not really *removed* but rather *not ported*).
