### ISSUE TITLE
Tilde (~) at start of filename triggers username expansion on Windows

### ISSUE THREAD

**Issue by clone** [git-for-windows/git#614]
In Git 2.7.0.1 if in a working copy a filename starts with a tilde (~xxxxxx), and Git interprets it as a references to a user's home directory and generates the error message "Error loading file: user xxxxxx doesn't exist". Such files are regularly generated by Microsoft Office, so this is quite annoying.

**Comment by dscho** [comment]
How about making it easier to reproduce? Something like a step-by-step script that triggers the error?

**Comment by clone** [comment]
I thought it was clear from the description that this will happen with ANY file that starts with a ~.
Try to add e.g. ~WRL0005.tmp to your working copy.

**Comment by clone** [comment]
A (temporary) workaround is to globally ignore these files. Still, Git should not produce an error message.

**Comment by dscho** [comment]
No, your description is not clear at all. For one, you did not even state which Git command triggered the error, let alone paste the error message verbatim.

You might want to make it easier for me to help you.

**Comment by clone** [comment]
Reproduce:
1. Add said file to working copy
2. Open working copy in Git Gui
3. Rescan (if needed)

**Comment by rimrul** [comment]
Ok, I tried

````bash
touch ~test
git status
git add ~test
git status
rm ~test
git status ~test
git add ~test
git status ~test
````

on Win7 pro x64/GfW 2.7.0 x64 without any error in git-bash. You have to be more precise to help us to help you.

**Comment by clone** [comment]
Git Bash? Step 2 : "Open working copy in Git GUI"

**Comment by rimrul** [comment]
I'm sorry. I missed that step.
Am 19.01.2016 20:17 schrieb "clone" <notifications@github.com>:

**Comment by dscho** [comment]
@clone please note that @rimrul gave you a perfect example how to be precise and clear in giving a step-by-step account of the exact commands you executed. For future record: It *will* save a lot of time to include such precise step-by-steps in the original bug report right away. (Point in favor: We *just* arrived at the point where somebody other than you can hope to reproduce the issue, but by now the time budget I could afford on this ticket is exhausted, just to get there.)

**Comment by clone** [comment]
Thanks for the feedback. I appreciate your work on this. About reproducing; before rimrul added his step-by-step account of commands, I already supplied a 3-step procedure, which I think is very clear, still it was not used to reproduce. That's also burning time. Looking back, I should have mentioned Git Gui in my original report.

**Comment by rimrul** [comment]
I tested your procedure. The error is triggered by selection the file in
git gui i.e. it des not instantly show up if you have other changed files.
I'll have another look at this on a Linux system in the evening. This might
be an upstream issue.
Am 20.01.2016 10:33 schrieb "clone" <notifications@github.com>:

**Comment by dscho** [comment]
@clone sorry to have to point this out, but [this description](https://github.com/git-for-windows/git/issues/614#issuecomment-172883673) is nowhere near [this precise step-through](https://github.com/git-for-windows/git/issues/614#issuecomment-172933435). Not even close.

**Comment by rimrul** [comment]
>I'll have another look at this on a Linux system in the evening. This might be an upstream issue.

It is indeed an upstream issue. Strangely enough, files starting with a tilde in a subdirectorry don't cause this.

I also got you a MVCE. With git 2.7.0 installed navigate to an empty folder in a POSIX terminal window. Run these commands:

````bash
git init
touch ~test
git gui
````

Select `~test` in git gui.

**Comment by dscho** [comment]
Thanks @rimrul!

Closing here, as it is not specific to the Windows port of Git.

@clone feel free to take this issue [upstream](mailto:git@vger.kernel.org).
