### ISSUE TITLE
Some file names create conflicts in windows

### ISSUE THREAD

**Issue by ericol** [git-for-windows/git#615]
Some file names generate conficts in windows. For instance, in a certain folder you cannot have 2 files that have the same name irrespective of caps and smalls (E.g., you cannot have a file named `README.md` and another file named `Readme.md`)

Also, Git for windows cannot handle files that end in a period (.)

How to reproduce:

Clone this repository https://github.com/ericol/windows-issues.git

Depending on your version of Git / windows, you might get this error when cloning the repo (git version 1.9.5.msysgit.0 WinXP 64 bits):

```
$ git clone https://github.com/ericol/windows-issues.git
Cloning into 'windows-issues'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.
error: Invalid path 'something stupid.'
```

right after cloning this is the result of `git status` (Results differ depending on Git / windows version):

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    something stupid.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   README.md

$ ls -la
total 1
drwxr-xr-x    4 Administ Administ        0 Jan 19 16:57 .
drwxr-xr-x   32 Administ Administ        0 Jan 19 16:57 ..
drwxr-xr-x   12 Administ Administ        0 Jan 19 18:15 .git
-rw-r--r--    1 Administ Administ       10 Jan 19 16:57 Readme.md
````

Versions Tested:
* Windows XP 64 bits
 * git version 1.9.5.msysgit.0
* Win7 Service Pack 1
 * git version 2.7.0.windows.1
 * git version 1.9.4.msysgit.2

All 3 vrsions tested fail to handle the file names properly. Results from 2.7.0 differ from the one above, but has problems handling both file names nonetheless.

**Comment by dscho** [comment]
These issues are incurred by the use of a case-insensitive file system and have little to do with Git, so I am at a loss what we could do about it.

**Comment by PhilipOakley** [comment]
@ericol, As @dscho said, this is part of a wider issue of the difference between the case sensitive and case insenitive file systems. The core Git **assumes** case sensitivity, and at present has no easy way of detecting these issues. As far as Git is concerned (I'm over summarising) they are not issues at all. It's a problem of bad OS decisions.

One question is, given a repo from *nix environment, what should be done about 'bad' filenames (there being no right answer, it's a politics question). Likewise when a user creates case conflict situation say with branches (checkout WrongCASE,  or delete WrongCASE), then what should be done.

Finding a solution which is codeable and acceptable to all is a big job. I did have a look at the code to see if there was an easy solution and found a bit of a tar pit.

Philip

https://groups.google.com/forum/#!topic/git-users/EryCnwKL4_E (16/dec/2015)
http://thread.gmane.org/gmane.comp.version-control.git/284022 (14/jan/2016)
'tar pit' see "mythical man month"

**Comment by dscho** [comment]
@PhilipOakley thanks for adding this very informative context.

After having thought about it a bit more, I am now convinced that it is indeed not a Windows-specific problem (HFS+ on MacOSX would show the same case sensitivity problems). As such, I will close it as an upstream problem.

@ericol please feel free to take this problem up with [the Git mailing list](mailto:git@vger.kernel.org).

**Comment by kostix** [comment]
> Also, Git for windows cannot handle files that end in a period (.)

Actually, from my own experience it's even worse: Win32 API is able to create a file ending in a period, but it performs "folding" of several periods into a single one.

My take on this is that Git can't sensibly do anything about this.

The same applies to attempts at creating files with special names such as `NUL`, `CON` etc, IIRC.
