### ISSUE TITLE
Annoying application event logging

### ISSUE THREAD

**Issue by nalla** [git-for-windows/git#616]
I noticed in my event log some annoying messages that seems to be related to the msys2 environment.

![digest-anoyance](https://cloud.githubusercontent.com/assets/688191/12441929/28d1d560-bf4c-11e5-8ece-d68776aa54f2.png)

After some hunting I found https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1372451.html that led to the conclusion that the issue is `libsasl2` related. I found out that when I issue `svn` commands the respective message appears.

Since we can not disable the log messages that easily in the `msys2` environment, maybe a removal is the best course of action.

**Comment by nalla** [comment]
With the next upstream recompile and publish of `cyrus-sasl` and `subversion` this behavior should stop.

**Comment by dscho** [comment]
Great! An alternative would have been to suppress `syslog()` debug messages in `subversion`:

```diff
diff --git a/subversion/svn/svn.c b/subversion/svn/svn.c
index 058be70..d372db8 100644
--- a/subversion/svn/svn.c
+++ b/subversion/svn/svn.c
@@ -29,6 +29,7 @@
 
 #include <string.h>
 #include <assert.h>
+#include <syslog.h>
 
 #include <apr_strings.h>
 #include <apr_tables.h>
@@ -3114,6 +3115,9 @@ main(int argc, const char *argv[])
   int exit_code = EXIT_SUCCESS;
   svn_error_t *err;
 
+  /* Avoid debug messages of cyrus-sasl */
+  setlogmask(LOG_UPTO(LOG_INFO));
+
   /* Initialize the app. */
   if (svn_cmdline_init("svn", stderr) != EXIT_SUCCESS)
     return EXIT_FAILURE;
```

**Comment by dscho** [comment]
Seems that as of right now, it has not been fixed (`libsasl` is still at 2.1.26-7).

**Comment by nalla** [comment]
just did a `pacman -Syu` and `libsasl` was updated to `libsasl-2.1.26-8`. Just did a quick test and the messages are gone now.

**Comment by dscho** [comment]
Thanks for following up!
