### ISSUE TITLE
Sometimes the text gets out off place

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#617]
Hi sometimes the text keeps going outplace by going to the top and down again causing the text to overlap the other text making it harder to read the text please see picture below.

**Comment by paladox** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/5727000/12445457/3f73b60c-bf5c-11e5-8af4-7c47308d7c25.png)

**Comment by paladox** [comment]
Sorry I doint have steps to reproduce since I just do what is normaly done it just does this sometimes.

**Comment by dscho** [comment]
What is this? No precise description of what you see and what you expect to see instead, not even a vague indicator what you are doing "normally" to get there?

And to top things off, an *uncropped* screenshot (rather than pasted text) showing some political statement?

Dude.

**Comment by paladox** [comment]
Hi this is not a political statement I did it infront of a hompage. Sorry. I am not sure how I get it I just do my normal stuff like 
git add -A --all
git commit 

and some times I get the screen above.

And I did give a descryption maybe not clear but is one.

**Comment by dscho** [comment]
> I am not sure how I get it I just do my normal stuff

http://whathaveyoutried.com (this is also mentioned in our [issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) which I will keep pointing you to).
