### ISSUE TITLE
Gitk: `Warning: encoding utf8 is not supported by Tcl/Tk`

### ISSUE THREAD

**Issue by NIA** [git-for-windows/git#618]
I have installed Git for Windows on one more Win7x64 machine and noticed that I cannot normally view commit messages with UTF-8 chars in **gitk**. Settings are correct: I have `git config --global gui.encoding utf-8` set, and **git gui** displays UTF-8 commit messages and file contents normally.

:warning: BUT

When I open **gitk** in the same repository, it shows cyrillic unicode symbols as `РІС‹С‡РёСЃР»РµРЅРёРµ...` and warns in the shell:

    Warning: encoding utf8 is not supported by Tcl/Tk

Interestingly enough, _diff contents_ in **gitk** display UTF-8 symbols correctly, just as **git gui**. :hushed:

Looks like some **gitk** problem, huh?

---
Windows 7 SP1 64 bit **Russian** / Git for Windows v.2.6.3 _or_ v2.7.0 (with Tcl/Tk 8.6)

**Comment by dscho** [comment]
Can you please make it easy to reproduce this by at least providing a clone'able repository that demonstrates this bug?

**Comment by NIA** [comment]
Sure, here you are: NIA/xprmntal@75c0e9d0779e90a13c411722db2a324f76934bbc

![cyrillic-gitk](https://cloud.githubusercontent.com/assets/26939/12473667/44f5d4d8-c025-11e5-86db-dbc446491db0.png)

Forgotten an important note: WIndows system language is Russian :ru:

![image](https://cloud.githubusercontent.com/assets/26939/12473689/70911670-c025-11e5-8fe5-de5cf3eee899.png)

**Comment by dscho** [comment]
Here's hoping that maybe for somebody fluent in the Russian language it is easy to reproduce now.

**Comment by NIA** [comment]
Well, actually any >00FF UTF-8 symbols cause this behavior on my machine, not only Russian letters. Here is another commit without Russian letters at all: NIA/xprmntal@aec69a761ab32fae01df91f1011607f61a4636cb

Each UTF-8 triple is displayed as three Win32 ANSI characters.

![image](https://cloud.githubusercontent.com/assets/26939/12480771/c3239b3a-c055-11e5-82b1-8c85d40da497.png)

The most fascinating thing for me is that the same symbols are displayed both right and wrong in the same window of Gitk, in different panes.

More system info:

    C:\Users\Ivan>wmic os get Caption,Version,CSDVersion,MUILanguages,OSLanguage /value

    Caption=Microsoft Windows 7 Professional
    CSDVersion=Service Pack 1
    MUILanguages={"ru-RU"}
    OSLanguage=1049
    Version=6.1.7601

**Comment by GuentherVIII** [comment]
Does it matter whether you configure "utf-8" or "utf8"?

**Comment by NIA** [comment]
@GuentherVIII , for commit messages - no. But interesting that warning is printed twice in case of `utf8` in settings and once in case of `utf-8`

### For Git Gui:

no difference

---

### For Gitk & `utf-8` _with_ dash

    NIA@NIA-Work$ git config --global gui.encoding utf-8

    NIA@NIA-Work$ gitk
    Warning: encoding utf8 is not supported by Tcl/Tk

![image](https://cloud.githubusercontent.com/assets/26939/12483432/1391a8f4-c066-11e5-9478-74402b96242c.png)

---

### For Gitk & `utf8` _without_ dash

    NIA@NIA-Work$ git config --global gui.encoding utf8
    NIA@NIA-Work$ gitk
    Warning: encoding utf8 is not supported by Tcl/Tk
    Warning: encoding utf8 is not supported by Tcl/Tk

![image](https://cloud.githubusercontent.com/assets/26939/12483486/55d2e534-c066-11e5-9dc8-c33869b9f373.png)

**Comment by Rizam** [comment]
Sori.. 

iPhone 4

Pada 21/01/2016, at 14:59, Ivan Novikov <notifications@github.com> menulis:

**Comment by kisstkondoros** [comment]
Just my two cents.

Tried it to reproduce the problem with no luck.

Caption=Microsoft Windows 10 Pro
CSDVersion=
MUILanguages={"en-US"}
OSLanguage=1033
Version=10.0.10586

wish
1 % encoding names
cp860 cp861 cp862 cp863 tis-620 cp864 cp865 cp866 gb12345 gb2312-raw cp949 cp950 cp869 dingbats ksc5601 macCentEuro cp874 macUkraine jis0201 gb2312 euc-cn euc-jp macThai iso8859-10 jis0208 iso2022-jp macIceland iso2022 iso8859-13 jis0212 iso8859-14 iso8859-15 cp737 iso8859-16 big5 euc-kr macRomania macTurkish gb1988 iso2022-kr macGreek ascii cp437 macRoman iso8859-1 iso8859-2 iso8859-3 macCroatian koi8-r iso8859-4 ebcdic iso8859-5 cp1250 macCyrillic iso8859-6 cp1251 macDingbats koi8-u iso8859-7 cp1252 iso8859-8 cp1253 iso8859-9 cp1254 cp1255 cp850 cp1256 cp932 identity cp1257 cp852 macJapan cp1258 shiftjis utf-8 cp855 cp936 symbol cp775 unicode cp857

git version 2.7.0.windows.2 

git clone https://github.com/NIA/xprmntal.git xprmntal
git config --global gui.encoding utf-8
gg
 - no issue

gitk
  - no issue
  - https://github.com/NIA/xprmntal/commit/f4e93e7bfee5f711210165796c2d6ca67187a8a2 It's the same as presented by github

![image](https://cloud.githubusercontent.com/assets/14231157/12794867/89125d20-cab7-11e5-86a3-2cb6b342f9f8.png) 
![image](https://cloud.githubusercontent.com/assets/14231157/12795018/57a31e04-cab8-11e5-84d0-d0e7f9cdf4b4.png)

**Comment by dscho** [comment]
@NIA seems that your MCVE is not verifiable?

**Comment by NIA** [comment]
@dscho sad, but yes. seems like some unique combination of glitches

**Comment by dscho** [comment]
@NIA I disagree. I do not think that there are any glitches. It is more likely a problem in your setup, but as long as you do not have the time to investigate, we will never know.

**Comment by NIA** [comment]
@dscho I meant "combination of glitches **of Windows & Tcl/Tk**" :smiley: no complaints to Git for Windows :wink:
