### ISSUE TITLE
Edge browser reports corrupt or invalid signature when downloading Git-2.7.0-64-bit.exe

### ISSUE THREAD

**Issue by tjmoore** [git-for-windows/git#619]
When downloading 2.7.0 on Windows 10 64 bit using Edge browser I get a report when it does a security check on the download saying "The signature of Git-2.7.0-64-bit.exe is corrupt or invalid", with an option to delete the download or view the downloads.

**Comment by kostix** [comment]
@tjmoore is the possibility of an antivirus software interfering ruled out?

**Comment by tjmoore** [comment]
Not certain, although if I download through Chrome there is no issue. If I scan the file manually with the AV software I'm using it comes up clean. I'm just using the built in Windows Defender which I believe Edge does also.

It looks like Edge is checking an embedded digital signature after download.

I've done an sha256sum on the file and it matches the published SHA256 signature, so went ahead with install and no issues raised there. Usually Windows and/or the installer will complain at that point if any embedded signature is invalid. I can see the digital signature on the installer properties and that looks okay and the certificate shows as valid.

Suggests and Edge issue then perhaps. I'm not sure what additional checks Edge is doing after downloads.

**Comment by dscho** [comment]
It's most likely due to my certificate being SHA-1, and Edge/Internet Explorer now require SHA-2. Unfortunately, my provider of free-for-OSS certificates does not issue SHA-2 certificates for OSS developers.

**Comment by whoisj** [comment]
I can confim that the issue does happen.

It looks likes the SHA-1 vs SHA-2 problem which is a [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) issue.

**Comment by dlptoo** [comment]
I'm running Windows 10 Pro, and I get the signature corrupt/invalid message with both the Edge browser and with IE.  When double-clicking on the .exe to install Git, Windows blocks the installation but then lets you proceed.

Assuming that the download is actually safe to install, it could be good for someone to post a FAQ about it saying it's safe.  Right now, it looks unsafe.

**Comment by dscho** [comment]
> it could be good for someone to post a FAQ about it saying it's safe.

Why don't you verify the SHA-256 with the one posted on the download page at https://github.com/git-for-windows/git/releases/latest?

**Comment by dscho** [comment]
Duplicate of https://github.com/git-for-windows/git/issues/592
