### ISSUE TITLE
Add an /etc/inputrc file like in the msysgit-based Git

### ISSUE THREAD

**Issue by elyscape** [git-for-windows/git#62]
Distributions of Git built with msysgit include [an /etc/inputrc file](https://github.com/msysgit/msysgit/blob/master/etc/inputrc) that, among other things, [makes command-line completion case-insensitive](https://github.com/msysgit/msysgit/blob/master/etc/inputrc#L9-L12), which makes sense for a Windows application as that's how the rest of the system behaves.  [The developers' preview build made with the Git for Windows SDK](https://github.com/git-for-windows/git/releases/tag/v2.3.4.windows.2) does not include such a file.  The resultant behavior changes are likely to confuse users who upgrade or are new to Git and/or Bash.  I recommend bring [lines 1-25 of msysgit's inputrc file](https://github.com/msysgit/msysgit/blob/master/etc/inputrc#L1-L25) into the Git for Windows SDK and distributions based on it.

I apologize if this isn't the right place to create the issue, but issues weren't active on [the build-extra repo](https://github.com/git-for-windows/build-extra).

**Comment by dscho** [comment]
> I apologize if this isn't the right place to create the issue, but issues weren't active on the build-extra repo.

This is on purpose: we have a *single* bug tracker for all of Git for Windows.

However, Pull Requests are available. And since you downloaded the developers' preview -- and since you understand that the described problems need to be addressed in the build-extra repository -- you are a developer and can make those changes and submit a Pull Request.

Thank you.

**Comment by elyscape** [comment]
Indeed. I just wasn't quite sure what the process for building the distribution was, so I wasn't quite sure where to add the file.

**Comment by dscho** [comment]
The `git-extra` package can be built by [downloading](http://git-for-windows.github.io/#download-sdk) & running the SDK (will take a while and download something in the order of 200-400 megabyte, then build Git), then initializing the `build-extra` clone:

```bash
cd /usr/src/build-extra
git fetch
git checkout master
```

and then calling

```bash
cd git-extra
makepkg-mingw -s
```

The build product is called something like `git-extra-x86_64-...pkg.tar.xz` and you can install it with `pacman -U git-extra*.pkg.tar.xz` and then test (the SDK will have installed a shortcut on your desktop, meaning that you can easily start another Git Bash by double-clicking that icon).

**Comment by elyscape** [comment]
Thanks for the help.  I'm reading the patch submission guidelines now as I wait for the initial build to complete and I should have a pull request ready tomorrow.

**Comment by elyscape** [comment]
Tomorrow became tonight somehow!  Fix submitted as git-for-windows/build-extra#21.
