### ISSUE TITLE
CTRL+Z and 'fg' support?

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#623]
During a merge, I wanted to "fork" the shell and run some commands, then switch back. What I tried was CTRL+Z, output said "Stopped" and then I tried running `fg` to return back but it said "current: no such job".

Is this the proper mechanism to do what I'm trying to do? I'm not even sure if these commands are supported.

**Comment by rcdailey** [comment]
I'll assume based on the labels you added that this is currently not supported behavior.

**Comment by dscho** [comment]
Ctrl+Z is not a feature of Git. So naturally, yes, you are correct, it is currently not supported behavior.
