### ISSUE TITLE
I need ssh-keygen and ssh-copy-id commands

### ISSUE THREAD

**Issue by gintares** [git-for-windows/git#624]
I need ssh-keygen and ssh-copy-id commands,
practically i need to Perform SSH Login Without Password  with Magellanes to deploy Symfony 2 project to remote server.

This forum recommends git for this command:
http://stackoverflow.com/questions/11771378/ssh-keygen-is-not-recognized-as-an-internal-or-external-command

C:\Users\Gintare>ssh-keygen
C:\Users\Gintare>ssh-keygen.exe
C:\Users\Gintare>git ssh-keygen
C:\Users\Gintare>git ssh-keygen.exe
All these commands gives an error :  is not a git command. See 'git --help'.

C:\Users\Gintare>git --version
git version 2.7.0.windows.1

I have found only these commands available:
C:\Users\Gintare>git
These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Forward-port local commits to the updated upstream head
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch

   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.

*****

C:\Users\Gintare>git help -a
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

available git commands in 'C:\Program Files\Git\mingw64/libexec/git-core'

  add                 gc                  receive-pack
  add--interactive    get-tar-commit-id   reflog
  am                  grep                relink
  annotate            gui                 remote
  apply               gui--askpass        remote-ext
  archimport          gui--askyesno       remote-fd
  archive             gui.tcl             remote-ftp
  bisect              hash-object         remote-ftps
  bisect--helper      help                remote-http
  blame               http-backend        remote-https
  branch              http-fetch          repack
  bundle              http-push           replace
  cat-file            imap-send           request-pull
  check-attr          index-pack          rerere
  check-ignore        init                reset
  check-mailmap       init-db             rev-list
  check-ref-format    instaweb            rev-parse
  checkout            interpret-trailers  revert
  checkout-index      log                 rm
  cherry              ls-files            send-email
  cherry-pick         ls-remote           send-pack
  citool              ls-tree             sh-i18n--envsubst
  clean               mailinfo            shortlog
  clone               mailsplit           show
  column              merge               show-branch
  commit              merge-base          show-index
  commit-tree         merge-file          show-ref
  config              merge-index         stage
  count-objects       merge-octopus       stash
  credential          merge-one-file      status
  credential-store    merge-ours          stripspace
  credential-wincred  merge-recursive     submodule
  cvsexportcommit     merge-resolve       submodule--helper
  cvsimport           merge-subtree       subtree
  cvsserver           merge-tree          svn
  daemon              mergetool           symbolic-ref
  describe            mktag               tag
  diff                mktree              unpack-file
  diff-files          mv                  unpack-objects
  diff-index          name-rev            update-index
  diff-tree           notes               update-ref
  difftool            p4                  update-server-info
  difftool--helper    pack-objects        upload-archive
  fast-export         pack-redundant      upload-pack
  fast-import         pack-refs           var
  fetch               patch-id            verify-commit
  fetch-pack          prune               verify-pack
  filter-branch       prune-packed        verify-tag
  fmt-merge-msg       pull                web--browse
  for-each-ref        push                whatchanged
  format-patch        quiltimport         worktree
  fsck                read-tree           write-tree
  fsck-objects        rebase

**Comment by rimrul** [comment]
> C:\Users\Gintare>ssh-keygen
C:\Users\Gintare>ssh-keygen.exe
C:\Users\Gintare>git ssh-keygen
C:\Users\Gintare>git ssh-keygen.exe
All these commands gives an error : is not a git command. See 'git --help'.

Impossible. this error can only occur for the last two. And it is correct for the last two comands. My Git for Windows 2.7.0 on Windows 7 shows me this:

````
which ssh-keygen
/usr/bin/ssh-keygen
````
````
which ssh-copy-id
/usr/bin/ssh-copy-id
````

for completenes:

````
git --version
git version 2.7.0.windows.1
````
````
uname
MINGW64_NT-6.1
````

This was explicitly tested on a Computer I don't use for Git developmenmt. Try to do a clean reinstall of Git for Windows. it does ship with `ssh-keygen` and `ssh-copy-id`.

**Comment by gintares** [comment]
Thank you!

regards,

On 25 January 2016 at 15:30, Matthias Aßhauer <notifications@github.com>
wrote:

> C:\Users\Gintare>ssh-keygen
> C:\Users\Gintare>ssh-keygen.exe
> C:\Users\Gintare>git ssh-keygen
> C:\Users\Gintare>git ssh-keygen.exe
> All these commands gives an error : is not a git command. See 'git --help'.
>
> Impossible. this error can only occur for the last two. And it is correct
> for the last two comands. My Git for Windows 2.7.0 on Windows 7 shows me
> this:
>
> which ssh-keygen
> /usr/bin/ssh-keygen
>
> which ssh-copy-id
> /usr/bin/ssh-copy-id
>
> for completenes:
>
> git --version
> git version 2.7.0.windows.1
>
> uname
> MINGW64_NT-6.1
>
> This was explicitly tested on a Computer I don't use for Git developmenmt.
> Try to do a clean reinstall of Git for Windows. it does ship with
> ssh-keygen and ssh-copy-id.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/git-for-windows/git/issues/624#issuecomment-174544008>
> .
>



-- 










*Gintare StatkuteMob: +447443241609Skype: gintare.statkuteE-mail:
g.statkute@gmail.com
<g.statkute@gmail.com>http://www.researcherid.com/rid/E-5096-2011
<http://www.researcherid.com/rid/E-5096-2011>https://www.linkedin.com/in/gintare-statkute-55910950
<https://www.linkedin.com/in/gintare-statkute-55910950>https://connect.innovateuk.org/web/g.statkute
<https://connect.innovateuk.org/web/g.statkute>---https://www.couchsurfing.com/people/gintare
<https://www.couchsurfing.com/people/gintare>*

**Comment by dscho** [comment]
This looks like a pilot error: Git CMD only knows how to call `git.exe`, not any of the Unix-y tools. You probably want to use the Git Bash.
