### ISSUE TITLE
Git for Windows within Cygwin - trouble?

### ISSUE THREAD

**Issue by larsxschneider** [git-for-windows/git#625]
Hi,

I have a user who wants/needs to use CSH with Git for Windows. Is it OK to use Git for Windows within the latest Cgywin or does this cause potential trouble? Git Bash shipped with Git for Windows does not work for him.

Thanks,
Lars

**Comment by dscho** [comment]
Please use the bug tracker only for bugs. Cygwin and MSYS2 are known not to work too well together, and Git for Windows is based on MSYS2. For some, mixing both environments seems to work okay but it is definitely not something I can put resources into supporting.
