### ISSUE TITLE
'git svn fetch' fails with checksum error if PERLIO=crlf is set

### ISSUE THREAD

**Issue by mschlaeffer** [git-for-windows/git#626]
For interoperability reasons I have set 'PERLIO=crlf'. In this case, git-svn creates directorys with 'cr' (or '^M') at the end. The problem is, 'git svn fetch' or 'git svn clone' will not fail when fetching the directory. It fails later on when fetching a file into that directory by showing a (misleading) 'checksum mismatch' on the file, rather than on the directory.

MCVE where 'ls | cat -A' shows 'trunk^M' instead of 'trunk' and the checksum mismatch is on file.txt:

```shell
#!/bin/sh
export PERLIO=crlf
mkdir /c/test
cd /c/test
svnadmin create svnrep
svn mkdir -m "Create trunk" file:///c:/test/svnrep/trunk
echo test > file.txt
svn import -m "Add file trunk/file.txt" file.txt file:///c:/test/svnrep/trunk/file.txt
git svn init file:///c/test/svnrep gitrep
cd gitrep
git svn fetch -r 0:1
ls | cat -A
git svn fetch -r 2
```

**Comment by dscho** [comment]
Thanks for the MCVE. However, it fails for me:

```
[...]
+ svn mkdir -m 'Create trunk' file:///c:/test/svnrep/trunk
svn: E170013: Unable to connect to a repository at URL 'file:///c:/test/svnrep'
svn: E180001: Unable to open repository 'file:///c:/test/svnrep'
```

**Comment by dscho** [comment]
Just to make sure:

```
$ ls -la /c/test/svnrep/
total 14
drwxr-xr-x 1 me 1049089   0 Jan 27 16:47 ./
drwxr-xr-x 1 me 1049089   0 Jan 27 16:47 ../
drwxr-xr-x 1 me 1049089   0 Jan 27 16:47 conf/
drwxr-xr-x 1 me 1049089   0 Jan 27 16:47 db/
-r--r--r-- 1 me 1049089   2 Jan 27 16:47 format
drwxr-xr-x 1 me 1049089   0 Jan 27 16:47 hooks/
drwxr-xr-x 1 me 1049089   0 Jan 27 16:47 locks/
-rw-r--r-- 1 me 1049089 246 Jan 27 16:47 README.txt
```

**Comment by mschlaeffer** [comment]
Do you use Windows or Cygwin svn? Try with Cygwin path 'file:///c/test/svnrep/trunk' (c: replaced by c).

**Comment by dscho** [comment]
I try with MSYS2 svn, because MSYS2 is what Git for Windows uses.

**Comment by dscho** [comment]
And with the POSIX path, I can reproduce the issue.

**Comment by dscho** [comment]
The first issue (the `ls | cat -A` one) can be worked around via

```diff
diff --git a/perl/Git/SVN.pm b/perl/Git/SVN.pm
index b2c14e2..98aca66 100644
--- a/perl/Git/SVN.pm
+++ b/perl/Git/SVN.pm
@@ -1311,6 +1311,7 @@ sub mkemptydirs {
        if (open my $fh, '<', "$self->{dir}/unhandled.log") {
                binmode $fh or croak "binmode: $!";
                while (<$fh>) {
+                       s/\r$//;
                        scan($r, \%paths_table, $_) or last;
                }
                close $fh;
```

However, it does not fix your issue because now there is another mismatch:

```
+ git svn fetch -r 2
Checksum mismatch: trunk/file.txt
expected: d8e8fca2dc0f896fd7cb4cb0031ba249
    got: 9f06243abcb89c70e0c331c61d871fa7
```

Maybe you can take it from here? I am not certain, though, that this issue can be addressed without substantial work on your side. It might be easier to disable the `PERLIO` setting when calling `git svn`.

**Comment by mschlaeffer** [comment]
Disabling `PERLIO` for `git svn` works of course. That's fine for me. If there is no easy fix, the issue is at least documented here if somebody else stumbles upon it.

**Comment by dscho** [comment]
Never mind, I guess nobody is volunteering for this possibly involved task anyway.
