### ISSUE TITLE
Getting error using GUI

### ISSUE THREAD

**Issue by Andrewkha** [git-for-windows/git#628]
Hi!

When using the Git GUI I get an error when pushing to github.
![git](https://cloud.githubusercontent.com/assets/9628186/12639265/50bd52de-c5b4-11e5-973d-99824d7e3718.PNG)

**Comment by dscho** [comment]
Could you please fill in the information we ask for in our [issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines)?

**Comment by dscho** [comment]
(In particular, it would make it more likely to receive help if you trimmed down the problem to a [*Minimal* Complete & Verifiable Example](http://stackoverflow.com/help/mcve), in this case try to push from the command-line.)

**Comment by Venomed** [comment]
If this user is having exactly what I'm having as well, he's giving you more information that I'm able to provide even! In my case as soon as you type `git` even for help output, I get an instant CTD. This is a recent event for sure. I was working with 2.6.4 installer just fine and then I updated myself yesterday to 2.6.5 (64 bit) and started seeing instant CTDs. This could have something to do with recent windows update which happened pretty recently as well (Windows 10 Build 14251).

I thought I had messed up windows somehow so i did a fresh build of Windows 10 Build 14251 and even on that clean install I have instant CTD right now. I tried downgrading to 2.6.4 which I know had been working fine, but that is instant CTD as well. So something has changed during 2.6.5 install that has not cleaned itself up after uninstall and is now causing 2.6.4 to crash as well. I'll continue to fiddle with things to see if I can narrow this behaviour down, but right now given how little input I have to causing CTD (as well as how little information I'm getting out of the crash), I'm not sure how to help out further.

**Comment by Venomed** [comment]
Digging through eventlog, I have the following two events regarding crash (2.6.4 64bit install that was working fine originally):

```
Faulting application name: git.exe, version: 2.6.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process ID: 0x1868
Faulting application start time: 0x01d15dc043453998
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: bcd925a7-0668-4742-b2c0-88a0dac4e0e4
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Faulting application name: git.exe, version: 2.6.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process ID: 0x350
Faulting application start time: 0x01d15dc0a1a23fcd
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: 44d23e3b-03d2-468c-979e-599119d84c9a
Faulting package full name: 
Faulting package-relative application ID: 
```

The fact that ntdll.dll is the culprit in there makes my suspicion grow even stronger that something may have changed in 14251 to trigger this problem.

I'm also attaching the [Windows Error Report](https://github.com/git-for-windows/git/files/114033/Report.zip) that is being sent to MS with these crashes.

**Comment by dscho** [comment]
> If this user is having exactly what I'm having as well, he's giving you more information that I'm able to provide even!

@Venomed the original report said nothing about the Windows version, while you were very precise. You mentioned that you use the Insider Preview 14251, which is exactly what #627 is about (and that ticket also mentions the official resolution: downgrade until a newer build becomes available; 14253 already fixed it, so if you can get anything newer than 14252 already, you can upgrade right away).

**Comment by Venomed** [comment]
Oh awesome! I haven't seen those builds yet but good to know it's already sorted in upcoming build. Thank you for such a swift response. I thought I wasn't really helping providing enough information (i know I've been on the receiving end of frustrating bug reports too) but glad to have been wrong. I'll figure this out now. Thank you again :+1:

**Comment by Andrewkha** [comment]
I'm using Win 8.1, so not sure it's the same...

**Comment by dscho** [comment]
@Andrewkha I am not willing to pull out every single bit of information about your setup from your nose... :smile: Why not volunteer that information up-front? After all, you want me to do my best helping you resolve your problem, yes? So why not do your best to describe your setup?

I am sure that after reading the [issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) you will have no problem whipping up an excellent report.

**Comment by Andrewkha** [comment]
Well, I do not think it's **only **my problem. If I found a bug in some software, the developer should also be interested in getting this fixed, shouldn't he? At least if he wants to have a perfect product. 
Basically there's nothing else to add, let me summarize.
I use Win 8.1 64 bit and git 2.7.0.0. When I use Git Gui to push the code to github (remote -> Push), I get the error like on the screenshot in the first message.

If I try to do the push via command line, it doesn't display any errors, but the push doesn't happen.
![git](https://cloud.githubusercontent.com/assets/9628186/12752992/076cd5fc-c9d6-11e5-965c-89bb2de55b2b.png)
Have no idea what else is needed, please let me know

**Comment by dscho** [comment]
> If I found a bug in some software, the developer should also be interested in getting this fixed, shouldn't he?

First of all, let's not assume that all developers are male. Second of all, I *am* interested, as is obvious because I am talking to you. Third of all, there is nothing I can do about bug reports lacking enough information. It frustrates me, yes. I would love to fix the bug, yes. But if the information is missing, I *simply cannot do anything about it*.

> I use Win 8.1 64 bit and git 2.7.0.0.

There is no git 2.7.0.0. There is a Git for Windows installer called `Git-2.7.0-64-bit.exe`, that may be what you meant. But then, there is also a `PortableGit-2.7.0-64-bit.7z.exe`. To help efficiently, I would need to know which one you refer to.

It is good that you tried the command-line. Now try again, with `GIT_TRACE=1` and `GIT_CURL_VERBOSE=1` and after it exits, just to make sure, display the exit status with `echo $?`.

And please paste the text, not an image.

**Comment by Andrewkha** [comment]
> First of all, let's not assume that all developers are male.

Sorry, this is just a specific of my native language, my English is not perfect.
> Third of all, there is nothing I can do about bug reports lacking enough information. It frustrates me, yes. I would love to fix the bug, yes. But if the information is missing, I simply cannot do anything about it.

That's why I expected some specific questions about which specific piece of information is missing.
OK, coming back to your questions. Yes, I'm using `Git-2.7.0-64-bit.exe`.

`$ git push
19:07:08.392564 git.c:348               trace: built-in: git 'push'
19:07:08.396564 run-command.c:343       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/Andrewkha/sportforecast.git'
* Couldn't find host github.com in the _netrc file; using defaults
* Input domain encoded as `cp1251'
`

**Comment by Andrewkha** [comment]
Also with this variables enabled I can't start Git GUI. the error is:

`Cannot determine Git version: 19:10:59.756159 git.c:348 trace built-in: git version
Git Gui requires Git 1.5.0 or later`

Hope this helps

**Comment by dscho** [comment]
> I expected some specific questions about which specific piece of information is missing.

You will agree that this here ticket has seen a lot of effort spent just on talking back and forth, and we are still in no way near any resolution. That is why I suggesting to volunteer information unasked.

> with these variables enabled I can't start Git GUI

I never suggested starting the Git GUI again. We want to get at the root of the problem, correct? The problem has nothing to do with Git GUI because you can already reproduce it on the command-line.

BTW the exit status has not been reported yet.

Unfortunately, I exhausted the time budget I could allow myself to work on this ticket for now.

**Comment by Andrewkha** [comment]
> I never suggested starting the Git GUI again. We want to get at the root of the problem, correct?

Yes, and as per above I'm trying to provide as much information as possible

> BTW the exit status has not been reported yet.

Sorry I'm not a guru in Unix command line and assumed the info I provided is what's required. Now I realize what's needed.
$ echo $?
128

**Comment by dscho** [comment]
@Andrewkha Seeing as you [expect a lot of others](https://github.com/git-for-windows/git/issues/628#issuecomment-178614876), I think it is only fair that I expect a lot from you in return. So I decided to put you into the driver's seat: you have everything you need to diagnose and fix this issue (see below), and it will be your responsibility to see it done.

First of all, it looks as if the issue is related to https://github.com/git-for-windows/git/issues/390. After all, the symptoms seem to be pretty identical.

So here is what I suggest you do: study the conversation in #390 and see whether you can replicate the DLL problem with the `depends.exe` tool. If that's not it, then you will need to follow [these instructions](https://github.com/git-for-windows/git/issues/390#issuecomment-140304906) to diagnose further where the problem occurs.

**Comment by Andrewkha** [comment]
I did use `dependency walker` and here's the result. It looks similar to issue #390 but some dlls are different. Not sure I can interpret this correctly
![depwalker](https://cloud.githubusercontent.com/assets/9628186/12783594/80e0bf94-ca93-11e5-905f-269cd3e68955.PNG)

**Comment by dscho** [comment]
@Andrewkha the section you show (can you make the window any larger before taking a screenshot?) does not display anything relevant to the mentioned ticket. I expect you to understand what that ticket talks about and then to find the relevant parts in the dependency tree, and then to determine whether it is the same issue or not.

**Comment by Andrewkha** [comment]
I'm not so technically skilled... Not sure if I do the right thing. I open the dependency walker, open the git-remote-https.exe, then Profile->start profiling. After that the Windows error window appeared with information:

`Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	GIT-REMOTE-HTTPS.EXE
  Application Version:	2.7.0.0
  Application Timestamp:	35316130
  Fault Module Name:	msvcrt.dll
  Fault Module Version:	7.0.9600.17415
  Fault Module Timestamp:	545055fe
  Exception Code:	c0000005
  Exception Offset:	000000000000184b
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	1412
  Additional Information 2:	1412e3b868a640437f32333c0d259fe9
  Additional Information 3:	23ee
  Additional Information 4:	23ee9538cc20b43c6e65adbd1dea6893

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt
`
When I closed it, the dependency walker stopped on the CONHOST.EXE file with the following details
![depwalker](https://cloud.githubusercontent.com/assets/9628186/12784482/73643dbe-ca98-11e5-807e-d7a3dbffdbdf.PNG)

**Comment by dscho** [comment]
> I'm not so technically skilled

There is nothing you cannot learn.

If you read #390 carefully, you will see that the culprit were DLL files in `C:\Windows\system32` that have the same name as DLL files required by `libcurl-4.dll`, but obviously with different function signatures.

**Comment by dscho** [comment]
This ticket seems to go nowhere, so let's just bury it gracefully.
