### ISSUE TITLE
git 2.3.5 error - post-checkout line ending problem

### ISSUE THREAD

**Issue by webmaster33** [git-for-windows/git#63]
I got unknown option 'refresh error, when using git 2.3.5.
I installed using net-installer:
https://github.com/git-for-windows/build-extra/releases/tag/net-installer-1.0.0-rc-1

git --version
git version 2.3.5.windows.2.1.g9a5c96c

git.exe checkout "lib_dev"
Already on 'lib_dev'
Your branch is up-to-date with 'lib/dev'.
'rror: unknown option 'refresh
usage: git update-index [options] [--] [<file>...]

    -q                    continue refresh even when index needs update
    --ignore-submodules   refresh: ignore submodules
    --add                 do not ignore new files
    --replace             let files replace directories and vice-versa
    --remove              notice files missing from worktree
    --unmerged            refresh even if index contains unmerged entries
    --refresh             refresh stat information
    --really-refresh      like --refresh, but ignore assume-unchanged setting
    --cacheinfo <mode>,<object>,<path>
                          add the specified entry to the index
    --chmod (+/-)x        override the executable bit of the listed files
    --assume-unchanged    mark files as "not changing"
    --no-assume-unchanged
                          clear assumed-unchanged bit
    --skip-worktree       mark files as "index-only"
    --no-skip-worktree    clear skip-worktree bit
    --info-only           add to index only; do not add content to object database
    --force-remove        remove named paths even if present in worktree
    -z                    with --stdin: input lines are terminated by null bytes

    --stdin               read list of paths to be updated from standard input
    --index-info          add entries from standard input to the index
    --unresolve           repopulate stages #2 and #3 for the listed paths
    -g, --again           only update entries that differ from HEAD
    --ignore-missing      ignore files missing from worktree
    --verbose             report actions to standard output
    --clear-resolve-undo  (for porcelains) forget saved unresolved conflicts
    --index-version <n>   write index in this format
    --split-index         enable or disable split index

Any idea what is the problem?

**Comment by webmaster33** [comment]
In .git\hooks\post-checkout file the content is the following:
```
#!/bin/bash
mtimestore -r
git update-index --refresh
```

But "git update-index --refresh" alone executes without error.
If I delete the "mtimestore -r" from post-checkout file, then the error still happens.

So the problem must have in line
#!/bin/bash
or in executing post-checkout file.

PROPOSAL:
post-checkout line ending are wrong.

FOUND the BUG:
Currently the line endings of  post-checkout file is Windows \n\r.
I converted the line endings to Unix \n, and the error if gone.
SUCCEED.


However I think, that under Windows the \n\r line endings should be allowed & HANDLED.

Please fix this bug.

**Comment by dscho** [comment]
> "lib_dev"

Where does that come from?

**Comment by dscho** [comment]
> .git\hooks\post-checkout

Where does that come from? We do not ship any post-checkout hook that I am aware of. Please try to follow the [the bug submission guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines). It is very frustrating for a developer who wants to help when she cannot get enough information to even try to reproduce the problem.

**Comment by webmaster33** [comment]
lib_dev = a branch
post-checkout = edited by myself to add "mtimestore -r" call (restores file modification date) - but this does not impact to the problem reported.

As I reported, the Windows linefeeds were caused problem, and the problem went away, when I converted the post-checkout file to have Unix linefeeds.

**Comment by dscho** [comment]
Without a precise account what to do, I will have not a prayer at reproducing the problem. Brownie points for providing a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve).

**Comment by dscho** [comment]
@webmaster33 are you still working on this ticket, or should I close it?

**Comment by webmaster33** [comment]
Well, I found the bug with line endings.
It was reproducible by me.

It should be fixed.
I think it should not be closed until it's not fixed.

**Comment by dscho** [comment]
@webmaster33 it is true that it should be fixed. But you have to *work with me* on getting it fixed.

That means that my request for [an account what you have tried, in a detailed, reproducible step-by-step description](http://whathaveyoutried.com/) must not go unheard, and neither my request for a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve).

I am offering to help you. You might want to grab that offer. If not, I have no option but to close this ticket.

**Comment by webmaster33** [comment]
Of course, I want to help you.

**Comment by webmaster33** [comment]
I tried to reproduce the bug in the newly compiled environment (git version 2.3.5.windows.6).
Bug was not reproducible.

Likely the bug was related to badly compiled git.

Closing bug.
