### ISSUE TITLE
Git 2.7.0 64bit becomes slow and unresponsive on Windows 10 v10.0.10586 after Hibernation

### ISSUE THREAD

**Issue by Robban1980** [git-for-windows/git#631]
I am having trouble with Git 2.7.0 64bit version on Windows 10 v10.0.10586.
Every time after my computer wakes up from hibernation Git becomes unresponsive and slow if i try to use it, the only remedy now is to reboot my computer to fix it.

At first i thought it was that i am running SourceTree as Gui. But when running command line Git and also Git Gui the result is the same. It is not that it freezes completely, if i wait for about 10 minutes for each command i try, Git will respond. 

Let me know if more information is needed.

**Comment by dscho** [comment]
> Let me know if more information is needed.

More information is needed ;-)

Maybe the hints at https://github.com/git-for-windows/git/wiki/Diagnosing-performance-issues help diagnosing this further?

**Comment by Rumo-Arf** [comment]
I think I have same kind problem. When I typed a 'git' then git bash respond "segmentation fault"
![default](https://cloud.githubusercontent.com/assets/11865340/12718478/3092367e-c932-11e5-9960-f3fe6a9f882c.PNG)

**Comment by dscho** [comment]
> I think I have same kind problem. When I typed a 'git' then git bash
respond "segmentation fault"

@Rumo-Arf no, I think you experienced a different problem: #627. You might want to extend your bug reports in the future, this one was very, very incomplete.

**Comment by dscho** [comment]
@Robban1980 still there?
