### ISSUE TITLE
Segfault on Windows 10 build 10251

### ISSUE THREAD

**Issue by milesje** [git-for-windows/git#633]
Git will segfault on Windows 10 build 10251.  Not sure if this is an issue with Windows or something that will need to be changed to work with newer builds.  I just received the update to Build 10251 and now git segfaults every time it is opened.

**Comment by dscho** [comment]
@milesje we politely ask to check existing bugs before reporting new ones in [our issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines). If I have to close duplicate bugs, it is simply taking time away from fixing the bugs themselves. Not anything either of us wants, yes?

**Comment by milesje** [comment]
I did perform a search in the GitHub issues and did not find an existing
issue, I do apologize for the inconvenience.

On Fri, Jan 29, 2016, 08:15 Johannes Schindelin <notifications@github.com>
wrote:

> Closed #633 <https://github.com/git-for-windows/git/issues/633>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/git-for-windows/git/issues/633#event-531285917>.
>
-- 
Jacob Miles
www.about.me/milesje

**Comment by dscho** [comment]
For the record, this is a duplicate of https://github.com/git-for-windows/git/issues/627
