### ISSUE TITLE
(trivial) 'git init' fails to create .git\branches directory

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#635]
(Totally Trivial issue)
While investigating the possible licence terms of an empty repository (http://thread.gmane.org/gmane.comp.version-control.git/284715/) I noticed that the git version 2.7.0.windows.1 (installed in c:\program files from the G4W download/installer) does not create the .git\branches directory, while the git version in the SDK (I have git version 2.6.2.windows.1) did create the directory. 

This was on a Windows XP Sp3 netbook (Samsung N130).

I ran
```
$ pwd -W
 C:/Documents and Settings/Philip
$ git init InitTemplate
Initialized empty Git repository in C:/Documents and Settings/Philip/InitTemplate/.git/

Philip@PhilipOakley MINGW32 ~/InitTemplate/.git (GIT_DIR!)
$ ls
config  description  HEAD  hooks/  info/  objects/  refs/
```
I inspected the created .git directory and there was no /branches directory

meanwhile via the SDK,
```
$ pwd -W
 C:/git-sdk-32
$ git init InitTemplateSDK
Initialized empty Git repository in C:/git-sdk-32/InitTemplateSDK/.git/

Philip@PhilipOakley MINGW32 /c/git-sdk-32/InitTemplateSDK/.git (GIT_DIR!)
$ ls
branches/  config  description  HEAD  hooks/  info/  objects/  refs/
```
did create the directory. 

I also used Beyond Compare's binary comparison, and everything else was identical.

While browsing the template files I did spot https://github.com/git/git/commit/c8a58ac5a52b from 2009 which indicates that the directory is just used for some tests, which is not a normal G4W user activity (but would be for the SDK user), so the directory's omission is probably no loss.

Tracking this down may be something for someone as a small getting-started project...
This may even be a g4w common sense difference.

**Comment by shiftkey** [comment]
@PhilipOakley a good first step would be to verify what upstream Git is doing with a `git init` - unfortunately I don't see a quick way for getting [v2.7.0](https://github.com/git/git/releases/tag/v2.7.0) up and running without building it locally...

**Comment by shiftkey** [comment]
Found it on Homebrew, so here's what I found:

>
$ git --version
git version 2.7.0
$ mkdir foo && cd foo && git init
Initialized empty Git repository in /Users/shiftkey/src/foo/.git/
$ ls .git
HEAD        description **info**        **refs**
config      **hooks**       **objects**
$ 

Given this is the same behaviour as upstream Git, I'm not really interested in looking into this further unless someone is curious...

**Comment by dscho** [comment]
Heh, I guess that Homebrew has the same packaging problem as we do: the `/mingw64/share/git-core/templates/branches/` directory is empty, and we only bundle files, [not directories](https://github.com/git-for-windows/build-extra/blob/69307a640f311f1c87d5404e2d5d411882b20dfb/make-file-list.sh#L26).

To fix this, we would have to teach all consumers of `make-file-list.sh`'s output to treat lines with a trailing slash specially: most archivers/packagers would include all contents, including subdirectories, and `make-file-list.sh`'s output would contain many non-empty directories (including of course e.g. `mingw-w64-x86_64-git /mingw64/`) which we definitely do not want to package wholesale!

In this particular case, we are talking about `branches/`, which is a directory that is not used by Git directly, anyway, but was only introduced for compatibility with [Cogito](https://en.wikipedia.org/wiki/Cogito_%28software%29) (which has been abandoned in 2007). So I'll just go ahead and declare this bug unworthy of fixing ;-)

**Comment by PhilipOakley** [comment]
@dscho, I approve of your decision, and thank you for clarifying the reason, which I didn't have time to research.
