### ISSUE TITLE
provide PDBs

### ISSUE THREAD

**Issue by MagicAndre1981** [git-for-windows/git#637]
Can you please provide the PDBs (Debug symbols) for all compiled files? This is helpful to debug crashes (WIndbg) and perf issues (xperf/WPRUI).

The best way would be a symbol server (https://msdn.microsoft.com/en-us/library/ms680693%28v=vs.85%29.aspx) and even better to also share the source via source server:

http://hamishgraham.net/post/GitHub-Source-Symbol-Indexer.aspx

**Comment by dscho** [comment]
We build things with GNU C, which does not output PDB files.

If you are volunteering to [help Git for Windows compile with Visual Studio](https://github.com/git-for-windows/git/pull/256), that's great.

Or if you research how to turn GNU C's debug information into PDBs and then help make this a part of the build process, that's also great!

**Comment by linquize** [comment]
If you build with VS, link C library statically or dynamically?

**Comment by dscho** [comment]
@linquize since `libgit.a` does *not* sport an API, it is most definitely unsuited to be linked dynamically. Whether we do that or not, however, is something you can easily find out yourself by studying the code affected by #256.
