### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by webmaster33** [git-for-windows/git#64]
I installed git v2.3.5 using net-installer:
https://github.com/git-for-windows/build-extra/releases/tag/net-installer-1.0.0-rc-1

- Started git-gui.exe
- started from menu Repository/Git Bash
- display git version:
```
user@PC MINGW64 /w/Dev/test
$ git --version
Segmentation fault

user@PC MINGW64 /w/Dev/test
$ git --version
Segmentation fault

user@PC MINGW64 /w/Dev/test
$ git --version
git version 2.3.5.windows.2.1.g9a5c96c

user@PC MINGW64 /w/Dev/test
$ git --version
Segmentation fault
```

It seems, that in MINGW64 bash sometimes it is executed fine, sometimes gives error:
```Segmentation fault```

I debugged it down, that 2 MINGW64 bash.exe was running in the memory.
When I closed the second one, all went fine, no seg fault.
But only if I executed one at a time.

It seems, that if I execute 
```git --version```
multiple times quickly, then the
```Segmentation fault```
error happens sometimes.

It seems it might be something spawning problem.

This bug should be fixed.

**Comment by dscho** [comment]
Which architecture? Have you called `autorebase.bat` first? Have you built debug versions? Have you tried to get a stack trace via `gdb`?

**Comment by webmaster33** [comment]
- x64
- no
- no
- no

How can I help you?

**Comment by dscho** [comment]
> How can I help you?

Please build debug versions by deleting `-O2` from the `CFLAGS` in `/usr/src/git/Makefile` and then calling `make` in `/usr/src/git` to rebuild.

Then run `gdb -args /usr/src/git/git.exe version`, call `r` and when it segfaults, obtain a stacktrace via `bt`.

**Comment by webmaster33** [comment]
Result:
```c:\git-sdk-64\usr\src\git>make
GIT_VERSION = 0
                   * new build flags
                                          0 [main] mkdir 6572 stdio_init: couldn't make stderr distinct from stdout
    CC credential-store.o```

**Comment by dscho** [comment]
Whoa. The only thing I can think of is to use DuckDuckGo for the rescue. And it came up with a possible explanation: http://stackoverflow.com/questions/11868017/couldnt-make-stderr-distinct-from-stdout-when-running-cygwin-commands

**Comment by webmaster33** [comment]
I think make should be fine, as it is a cygwin make.
Maybe 64bit make is the problem?
```
c:\winprg\git-sdk-64\usr\src\git>make --version
GNU Make 4.1
Built for x86_64-unknown-cygwin
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by dscho** [comment]
Is it a fatal error, or more like a warning?

**Comment by webmaster33** [comment]
It's an error:
```c:\git-sdk-64\usr\src\git>make
Makefile:1872: recipe for target 'credential-store.o' failed
make: *** [credential-store.o] Error 1
```

**Comment by webmaster33** [comment]
I think it misses ssh or zlib source.

**Comment by webmaster33** [comment]
It may be also caused by path.

**Comment by webmaster33** [comment]
Added 
c:\cygwin64\bin\
to path, instead of:
c:\GnuWin32\bin\
so different version of make is found, and also unix command are also available now.

Now shows following error:
```
c:\git-sdk-64\usr\src\git>make
    * new build flags
    CC credential-store.o
                             CC archive-tar.o
                                                 CC archive-zip.o
                                                                 Makefile:2052:
recipe for target 'GIT-PREFIX' failed
make: *** [GIT-PREFIX] Error 1
```

**Comment by dscho** [comment]
> Added
> c:\cygwin64\bin\
> to path, instead of:
> c:\GnuWin32\bin\
> so different version of make is found

The intention is to use *MSys2*'s own `make`. No other `make` is supported, if they fail for you, you are on your own.

**Comment by dscho** [comment]
> It's an error:
> 
> ```
> Makefile:1872: recipe for target 'credential-store.o' failed
> make: *** [credential-store.o] Error 1
> ```

So here is a valuable lesson learned: do not truncate error messages. It will only result in useless back and forth until the complete error message is known anyway.

**Comment by webmaster33** [comment]
>The intention is to use MSys2's own make. No other make is supported, if they fail for you, you are on your own.
So I should add 
c:\git-sdk-64\usr\bin\
to the path, right?

**Comment by webmaster33** [comment]
Ok, changed make path to c:\git-sdk-64\usr\bin\:
```
c:\winprg\git-sdk-64\usr\src\git>make --version
GNU Make 4.1
Built for x86_64-pc-msys
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Make error:
```
c:\git-sdk-64\usr\src\git>make
FIND: Hibás paraméterformátum. (translated: bad parameter format or invalid argument)
    * new build flags
Makefile:1872: recipe for target 'credential-store.o' failed
make: *** [credential-store.o] Error 127
```

**Comment by dscho** [comment]
> So I should add
> 
> c:\git-sdk-64\usr\bin\
> 
> to the path, right?

If you have to add that manually, I have to ask: do you use the Git SDK *at all*?

**Comment by webmaster33** [comment]
The current Git for Windows release is 1.9.5, so I want to compile latest git version to use it.

**Comment by dscho** [comment]
The Git for Windows 1.x project is still maintained elsewhere: https://github.com/msysgit.

This here issue tracker concerns Git for Windows 2.x, the successor, switching from the development environment called "msysgit" to the development environment we henceforth will call "Git SDK".

I am afraid that you really will have to specify *exactly* what you did, based on what software, to avoid a conversation that is as frustrating to both of us as the above one.

**Comment by dscho** [comment]
> I installed git v2.3.5 using net-installer:
> [...]
> I don't use the SDK itself, just want to compile latest git version to use it, because the current Git for Windows release is only 1.9.5.

Whoa, now I am really, really confused. These two statements are contradicting each other.

**Comment by webmaster33** [comment]
>Whoa, now I am really, really confused. These two statements are contradicting each other.

Well, I suppose SDK is for developing & testing GIT itself.
I don't develop GIT, just want to compile GIT to use it in my developments.

**Comment by webmaster33** [comment]
>This here issue tracker concerns Git for Windows 2.x, the successor, switching from the development environment called "msysgit" to the development environment we henceforth will call "Git SDK".

Ok, this is more clear now. 
It was renamed.

**Comment by webmaster33** [comment]
I followed instructions on this page:
https://github.com/git-for-windows/git/issues/13#issuecomment-85359841

```
For the ones who does want to try out the current state of development, and even want to help test it, here is a little HOWTO:
 - Download net-installer for the Git for Windows SDK and install it.
 - Startup the MinGW Git for Windows SDK shell (Look for shortcuts in the Git for Windows SDK install folder)
 - Clone the build-extra repository and checkout the feature branch portable-release within the Git for Windows SDK.
 - Change in the portable directory of the new clone.
 - Run the ./release.sh <version-no> shell script. That should create you a portable installer for Git for Windows in your home directory.
 - Test it!
```

Well, after using net-installer, everything went fine, but I got seg-fault in command line, when starting a git command.

I will now try again net-installer, after the path conflict was fixed.

**Comment by dscho** [comment]
> Well, I suppose SDK is for developing & testing GIT itself.
> I don't develop GIT, just want to compile GIT to use it in my developments.

Well, the SDK is for developing, *building* and testing. From my point of view it makes no sense to refuse to use the SDK when one wants to build Git.

In any case, you reported a bug that I cannot reproduce, so if you want to see this bug fixed, I am afraid that you *have* to do something about it, i.e. build with debug information and then debug in the way I patiently described.

**Comment by webmaster33** [comment]
I will now try net-installer again, after the path conflict was fixed.
It might happen, that path conflict was the cause of seg-fault.

**Comment by webmaster33** [comment]
OK. Successful install.
No more seg-fault.

```
c:\git-sdk-64\cmd>git --version
git version 2.3.5.windows.6
```

Likely the path conflict caused the seg-fault, while was built using libraries not in the SDK itself.

Thanks for your help.

I learned something again.
