### ISSUE TITLE
Git 2.7.0 64bit becomes Segmentation fault on Windows 10 v10.0.14251

### ISSUE THREAD

**Issue by xuzhuoyi** [git-for-windows/git#642]
I am having trouble with Git 2.7.0 64bit on Windows 10 v10.0.14251 that was published on 5 days ago.
In both `git-bash.exe` and `git-cmd.exe`, when I enter `git clone` or `git -v`, it comes out `Segmentation fault`.
Maybe Git 2.7.0 is incompatible with Windows 10 Build 14251.

**Comment by dscho** [comment]
This is the seventh duplicate of #627.
