### ISSUE TITLE
XDG config confusion

### ISSUE THREAD

**Issue by csware** [git-for-windows/git#643]
Create a .config directory in the user profile folder and then execute `git config --global user.name test`, see that a ".config/.git/config" is created. According to the git documentation, the file should be `.config/git/config` (without the dot before git). Also, the  `.config/git/config` file should not be created if it does not exist and .gitconfig exists.

The ".config/git/config" file is also read, but with less priority?!

See http://man7.org/linux/man-pages/man1/git-config.1.html.

**Comment by dscho** [comment]
I cannot reproduce this behavior. For me, a fresh `~/.gitconfig` is created and `.config/` is still empty. FWIW tested with Git for Windows 2.7.1(2) on Win7 64-bit.

**Comment by csware** [comment]
ok, I just found why a .git directory appeared. Run "git config bla.bla bla" and git will create a .git/config file - even it is not in a repository.

**Comment by dscho** [comment]
Oh, okay, so the bug report was incorrect in that it specified the `--global` flag.

Maybe change the ticket's title to "`git config key value` misbehaves outside of repositories"?

**Comment by dscho** [comment]
Fix submitted: http://article.gmane.org/gmane.comp.version-control.git/287180

**Comment by csware** [comment]
I did lots of testing with the global flag, but the confusion started when I issued git config w/o global.
