### ISSUE TITLE
Update the installer git uses to 5.5.8 please

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#647]
Hi please update Inno Setup to 5.5.8

The change log for changes is http://www.jrsoftware.org/files/is5-whatsnew.htm

The main changes I think are good are 

•The [Setup] section may now list multiple SignTool directives which will be executed in order of appearance. This can be used to dual sign (SHA1 & SHA256) Setup and Uninstall. This requires a recent signtool.exe version and a SHA256 (SHA-2) certificate. Inno Setup's own installer is now also dual signed. See the help file for a dual sign example. Without dual signing Windows will no longer trust any of your new installers if they are downloaded. See http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx for more information.

Which we are doing.

•The Compiler IDE's New Script Wizard now offers to create a shortcut to the main executable in the common Start Menu Programs folder instead of creating a new Start Menu folder especially for the application. This option is enabled by default and is recommended by Microsoft unless you install a suite of applications rather than a single application.

**Comment by dscho** [comment]
We are dual signing without the need for the new feature. And we do not use the IDE.

**Comment by paladox** [comment]
Oh ok.

**Comment by dscho** [comment]
> The main changes I think are good

This completely misses that we are using 5.5.6, still, and it is quite possible that our use of `git-edit-bash.dll` is broken by this change in *5.5.7* (which you did not mention at all):

> ;* The Setup and Uninstall programs are now marked as DEP and ASLR compatible. This can be disabled by setting the new DEPCompatible and ASLRCompatible [Setup] section directives to no. Doing this for DEP compatibility might be needed if you're using a buggy third-party DLL from [Code], like isxdl.dll.

That would be a rather dramatic regression, and it would have been good if you would have tested this before opening this ticket (you have been around long enough to know how to [make an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer)).

**Comment by dscho** [comment]
> This completely misses that we are using 5.5.6, still, and it is quite possible that our use of git-edit-bash.dll is broken by this change in 5.5.7 (which you did not mention at all)

I did the menial work of testing this and found `edit-git-bash.dll` to be safe and still working with 5.5.9-dev. For the record: anybody testing such things relieves me greatly.
