### ISSUE TITLE
Git-Gui multiple language versions.

### ISSUE THREAD

**Issue by XhstormR** [git-for-windows/git#648]
I was using msysgit version, Git-Gui have a Chinese version. But now I upgraded to git-for-windows version found Git-GUI has no Chinese version.

I've searched for this [Web site](http://repo.or.cz/git-gui/git-gui-i18n.git/tree/refs/heads/mob:/po).

Can someone help me?

**Comment by XhstormR** [comment]
I discovered that this `PortableGit-2.7.0-64-bit.7z\mingw64\share\git-gui\lib` folder is missing `Msgs` folder, msysgit version have this folder，so I copied it over.It Works!

**Comment by kostix** [comment]
See: #378, #386, #403, #496, #584.

**Comment by XhstormR** [comment]
Oh,i see.
This is my solution:
Path: PortableGit-2.7.0-64-bit.7z\mingw64\share\git-gui\lib\msgs
![msgs](https://cloud.githubusercontent.com/assets/10527522/12846453/bb5630ae-cc47-11e5-882a-a3e8b5fe7917.png)
Save as 7z，Unzip it，Copy it to path，Finish.

**Comment by dscho** [comment]
That's not a solution, it is a workaround. I will definitely welcome Pull Requests that add a proper solution.
