### ISSUE TITLE
Output from pre-receive hook does not echo to client.

### ISSUE THREAD

**Issue by csimons** [git-for-windows/git#652]
Hook output should echo at the client side, and does indeed when using the (non-Windows) Git client, but does not echo when using git-for-windows.  For verification, output from the same push for both Git for Windows and the regular Git client (from Cygwin) appears below for comparison.

pre-receive hook on server:

```
#!/usr/bin/env bash
echo 'foo'
exit 1
```

Git 2.5.3 from Cygwin distribution (correct output):

```
$ git version
git version 2.5.3
$ echo foo > foo
$ git add foo
$ git commit -m 'foo' > /dev/null
$ git push
Counting objects: 3, done.
Writing objects: 100% (3/3), 267 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: foo
To git://viadevgit01/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git://viadevgit01/test.git'
$
```
Note the hook output emitted in the fourth-from-last line above, "remote: foo".

Git for Windows version 2.7.0.windows.2 64-bit, run on Windows 7 (incorrect output):

```
$ git version
git version 2.7.0.windows.2
$ echo foo > foo
$ git add foo
$ git commit -m 'foo' > /dev/null
$ git push
Counting objects: 3, done.
Writing objects: 100% (3/3), 267 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git://viadevgit01/test.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git://viadevgit01/test.git'
$
```

Note that the line "remote: foo" is absent in the git-for-windows output.

**Comment by dscho** [comment]
Is it possible to trigger this error with a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve)?

**Comment by csimons** [comment]
@dscho I'm not sure how to make this more minimal, though I'm happy to carry out any suggestions.  Thoughts?

**Comment by PhilipOakley** [comment]
There was some documentation updates on the main list in this area. a quick search found this possibility https://public-inbox.org/git/xmqqlgiwpgst.fsf_-_@gitster.mtv.corp.google.com/

For the MVCE, maybe see if you can develop a very short local method of setting up the scenario. I'm guessing that creating the setup is the hardest, if one doen't have the right stuff to hand. I don't know enough about the hooks and remote service to advise here.

**Comment by dscho** [comment]
> Git for Windows version 2.7.0.windows.2 64-bit, run on Windows 7 (incorrect output):
> 
> ```
> $ git version
> git version 2.7.0.windows.2
> $ echo foo > foo
> $ git add foo
> $ git commit -m 'foo' > /dev/null
> $ git push
> Counting objects: 3, done.
> Writing objects: 100% (3/3), 267 bytes | 0 bytes/s, done.
> Total 3 (delta 0), reused 0 (delta 0)
> To git://viadevgit01/test.git
> ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git://viadevgit01/test.git'
> $
> ```
> 
> Note that the line "remote: foo" is absent in the git-for-windows output.

From another vague memory, I seem to recall that `push` via `git://` requires the sideband to be turned off. And my guess is that that is precisely where the output would be transmitted.

There is a stalled ticket about this here: https://github.com/git-for-windows/git/issues/2376. I will close this here ticket in favor of that ticket.
