### ISSUE TITLE
prompt for email using "(none)" no longer works, directly commits

### ISSUE THREAD

**Issue by shiftkey** [git-for-windows/git#653]
I found a twitter discussion today where @nguerrera uses [this ~/.gitconfig value](https://github.com/nguerrera/.dot/blob/e8ffec206bfcec667cf290762bab0d7e344f898e/.gitconfig#L4-L6) to ensure his repos are setup with explicit email addresses when committing:

> [user]
> email = (none)

It's a cool trick, but @jasonmalinowski indicated this isn't working on Git 2.7. Here's the script I used to create a blank repo and make the commit:

```
$ git init foo
$ cd foo
$ touch BAR
$ git add .
$ git commit -m "something"
```

On Git 2.5.3.windows.1, you get the prompt and the right `fatal` step:

```
$ git commit -m "something"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '(none)')
```

On version `2.7.1.windows.1` you don't get the prompt, and it successfully commits with `(none)`:

```
$ git commit -m "something"
[master (root-commit) 6e54538] something
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 BAR

$ git show HEAD
commit 6e54538d314f581d107f0091fdd4604e24742a7a
Author: Brendan Forster <(none)>
Date:   Thu Feb 11 10:20:55 2016 +1100

    something

diff --git a/BAR b/BAR
new file mode 100644
index 0000000..e69de29
```

I haven't tested upstream yet to see if the same behaviour is there, but I suspect that is the case.

EDIT: this is testing 32-bit releases, not sure that's a factor here.

**Comment by jasonmalinowski** [comment]
Maybe this was broken by 19ce497cf594a3c01af33a65b27b19e7459212d6? It looks like the (none) trick was a side effect of the implementation.

**Comment by shiftkey** [comment]
@jasonmalinowski the prompt also occurs in `2.6.4.windows.1` so I think you're on to something there...

**Comment by nguerrera** [comment]
If this was just an implementation detail we were abusing, please consider any suitable replacement for the scenario.

**Comment by jasonmalinowski** [comment]
Looks like we're not the only one to recently notice this. This [StackOverflow comment](http://stackoverflow.com/questions/12292582/how-do-i-make-git-block-commits-if-user-email-isnt-set#comment58043721_25050535) points to a [Git mailing list discussion](http://www.spinics.net/lists/git/msg267006.html) where a proper feature is being reimplemented.

**Comment by shiftkey** [comment]
As this is an upstream issue, I'm happy to close it out as being investigated with those links to refer back to.

@jasonmalinowski @nguerrera any objections?

**Comment by jasonmalinowski** [comment]
Does upstream have a reasonable bug tracker we can link to? Otherwise I have no objections.

**Comment by shiftkey** [comment]
@jasonmalinowski I think [the mailing list thread](http://www.spinics.net/lists/git/msg267006.html) should be good enough context - a number of the core contributors have followed up and they're working through the right way to fix this - rather than restoring the old behaviour.
