### ISSUE TITLE
commit issue on windows network share(fatal: xxx is not a valid object)

### ISSUE THREAD

**Issue by ryrun** [git-for-windows/git#654]
Hi, i've a problem with git on a network share of my windows server. I'm not able to commit changes. I always get the "is not a valid object" error message.

```cmd
W:\Test>git version
git version 2.7.1.windows.1

W:\Test>git init
Initialized empty Git repository in W:/Test/.git/

W:\Test>git add .htaccess
warning: LF will be replaced by CRLF in .htaccess.
The file will have its original line endings in your working directory.

W:\Test>git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   .htaccess


W:\Test>git commit -m test
fatal: 6beedf63fd5b5220d5d63eaccdbe292ead89c01b is not a valid object
```

I've set following flag to get it working on linux samba shares, but it doesn't help for windows servers:

```cmd
git config --global --add core.createobject link 
```

I found some useful discussions, maybe it can help here?
http://git.661346.n2.nabble.com/trouble-on-windows-network-share-td7581547.html

There is a hint, that compiling git with NO_MMAP=1 would work as workaround. Is it possible to set this as config flag, too?

**Comment by ryrun** [comment]
Issue #554 could be related.

**Comment by dscho** [comment]
So I go and export my 64-bit SDK's `/usr/bin/git` directory as network share, map it on the same computer as `W:` and then I try to commit first an empty `.htaccess` and then one that contains the line `Hi, you`. Both commits succeed.

Which means that
1. information is missing (such as: Windows version of the computer, Windows version of the server whose share you map, details about the connection to the server, etc), and
2. without a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve), it is unlikely that *anybody* can help you.

**Comment by ryrun** [comment]
Sorry for being not detailed enough. Server: Windows 2013, PC: Windows 7 64bit, Connection is just Gbit-LAN. Your test from a linux environment is not comparable, as i mentioned that this is working for me, when a special flag is set. Did you check the discussion from the link i provide? Sure its about an older git version, but its exactly the same issue.

**Comment by dscho** [comment]
> Your test from a linux environment is not comparable

I tested this on Windows 10, serving both as "server" as well as client.

Not from Linux at all. (Which I thought was obvious from my use of the `W:` drive: Linux does not have drive letters at all.)

> without a Minimal, Complete & Verifiable Example, it is unlikely that anybody can help you.

FWIW this is still the main problem. Have you tried to narrow down your problem by replicating my test, where you export a share from the same PC on which you map it to a drive?

I strongly encourage you to come up with that MCVE. I, for one, won't be able to assist you further without such an example because I simply lack the time to try for days on end to reproduce something I might never be able to reproduce to begin with.

**Comment by dscho** [comment]
> Connection is just Gbit-LAN.

Just in case it was not clear: if you cannot replicate this issue by mapping a share from the same PC, It is important to know how close this connection is (i.e. whether the server has to be on a WAN to replicate the issue).

**Comment by ryrun** [comment]
I did some more testing. It seems, git needs admin rights to get this working. I use git as domain user on network shares, something i've forgot to mentioned in my bug report (sorry about that). I've most rights on the network sahre, only the last one labled as "Spezielle Berechtigunen" (special rights) is not set.

```cmd
Windows 7 -> LAN -> Windows 7 (other PC)
Without admin rights: fatal error
With admin rights: everything is fine
```

```cmd
Windows 7 -> LAN -> Windows Server 2013
Without admin rights: fatal error
With admin rights: everything is fine
```

So it's not a windows specific issue, more an user-rights problem.

**Comment by dscho** [comment]
Maybe monitoring the `git commit` call with [ProcMon](https://technet.microsoft.com/en-us/sysinternals/bb896645) will shed light into the reason why it fails?

**Comment by dscho** [comment]
Okay, I misread, sorry.
