### ISSUE TITLE
using stand-alone vim : `'C:\Program' is not recognized...` error

### ISSUE THREAD

**Issue by srustamo** [git-for-windows/git#658]
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿I'm trying to use a stand-alone vim on Win Server 2008 with git-for-windows. 
I moved `/usr/bin/vim.exe` out of the way to `/usr/bin/vim.exe.bak` and set up `/usr/bin/vim` script:

    #!/bin/sh  
    exec '/c/Program Files (x86)/Vim/vim74/vim.exe' "$@"
Now, running `vim` from within ﻿﻿`﻿﻿﻿﻿﻿MINGW64` mintty gives me this error:
    
    ﻿'C:\Program' is not recognized as an internal or external command,operable program or batch file.

**Comment by srustamo** [comment]
It appears the process `vim.exe *32` actually gets launched, but `mintty` freezes and I need to use `taskmgr` to kill the `vim.exe *32` process, which hogs 99% of CPU.

**Comment by dscho** [comment]
Have you heeded the advice in the [known issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues):

> Some console programs interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

Alternatively, you should consider using the option "Use Windows' default console window" instead of "Use MinTTY (the default terminal of MSys2)"?

Also, there is a vim shipped with Git for Windows that is known to be good, why make everybody's life (including mine!) harder than necessary by going out of your way to *not* use that?

**Comment by srustamo** [comment]
I actually (apparently wrongly) thought that using the stand-alone vim is a simpler option. My bad. The initial problem I actually had was that `git-for-windows` did not see my `{USERNAME}\vimfiles`, although it finds `_vimrc` in the same dir. Any idea where the `vimfiles` should go?

**Comment by dscho** [comment]
First time I hear of `{USERNAME}\vimfiles`. Care to explain?

**Comment by srustamo** [comment]
Sorry, just getting into Win. The stand-alone vim looks for, say, Admin user's `_vimrc` and `vimfiles` in `C:\Users\Admin\` dir. Hope this makes a bit more sense.

**Comment by dscho** [comment]
> Hope this makes a bit more sense.

Not really. I never heard about this feature. So I am mildly doubtful that it is a feature of vim itself. But you can check it out: simply follow the instructions [how to rebuild packages](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages) (in this case, the MSYS package `vim`) and then search through the source code whether you find any mention of this `vimfiles` feature.

**Comment by dscho** [comment]
And while I am usually not keen to do research for others, in this case I was curious enough to try to find this curious `vimfiles` thing. Apparently, it is an intentional incompatibility of the stand-alone vim, for some reason that escapes me, at least I get the impression from [this StackOverflow answer](http://stackoverflow.com/a/851167).

**Comment by rimrul** [comment]
>Any idea where the vimfiles should go?

According to various sources<sup>[1](http://superuser.com/questions/729368/where-is-vimfiles-directory-on-mac-os), [2](http://agateau.com/2007/note-to-self-path-to-vim-files-on-windows/), [3](https://github.com/scrooloose/vimfiles)</sup> the `vimfiles` are located in `~/.vim` on every system except the Windows stand-alone vim. Sice the Git for windows vim doesn't know it's not running on a POSIX system that's the place it's searching. This translates to `C:\Users\Admin\.vim\` in your case. We should keep that location for UNIX compatibility. Maybe you could add a patch file that adds `~/vimfiles` as a secondary search location to our [vim package](https://github.com/git-for-windows/MSYS2-packages/tree/master/vim)?

**Comment by rimrul** [comment]
>Maybe you could add a patch file that adds ~/vimfiles as a secondary search location to our vim package?

I've had a quick look at the vim source code. I think the interesting code is found in [os_unix.h#L373-L379](https://github.com/vim/vim/blob/d99df423c559d85c17779b3685426c489554908c/src/os_unix.h#L373-L379).

**Comment by srustamo** [comment]
Barring a quick fix for this issue I would like to avoid maintaining two different sets of `.vim` (or `vimfiles`) on one machine (one for `git-for-windows` vim, and the other for the stand-alone vim). Perhaps a symlink (or hardlink) of `C:\Users\Admin\vimfiles` to `/usr/bin/.vim` possible?

AFAIK `vimfiles` were introduced to deal with the fact that Win does not allow dot files (files beginning with a dot).

**Comment by dscho** [comment]
@srustamo the way [outlined by @rimrul](https://github.com/git-for-windows/git/issues/658#issuecomment-184350913) is the correct way to go.

**Comment by srustamo** [comment]
@dscho could you please check the link, does not seem to work.

**Comment by srustamo** [comment]
@dscho, no worries, the link is OK.

**Comment by srustamo** [comment]
I'm not sure I can help with creating a patch as @rimrul seems to suggest, but I tried to create a symlink from within mintty, with `ln -s vimfiles A` and then `mv A .vim`. It seems to work, but I need to see if this is not just a copy of the `vimfiles`. `ln` in mintty would not allow to name the target link `.vim`, hence the two step. Any idea if this is a sustainable solution?

**Comment by rimrul** [comment]
> AFAIK vimfiles were introduced to deal with the fact that Win does not allow dot files (files beginning with a dot). 

This was a problem with 8.3 filenames. that should not be a problem anymore on systems that support VFAT (Windows 95 and newer).

>I'm not sure I can help with creating a patch as @rimrul seems to suggest, but I tried to create a symlink from within mintty, with ln -s vimfiles A and then mv A .vim. It seems to work, but I need to see if this is not just a copy of the vimfiles. ln in mintty would not allow to name the target link .vim, hence the two step. Any idea if this is a sustainable solution?

A symlink (or even a hard link for that matter) is not exactly a solution, but a workaround. I'll do a quick attempt at a patch for the default runtime path in a few hours and link you a new test executable. I'd test it myself, but I my vi knowledge is limited to basic text file editing. I don't have any vimfiles if those are not installed by default. I don't really know how to see if vim found my vimfiles or what content they're supposed to have so that vim understands any of them.

**Comment by srustamo** [comment]
>  I don't have any vimfiles if those are not installed by default. I don't really know how to see if vim found >  my vimfiles or what content they're supposed to have so that vim understands any of them.

I'll be happy to test with my `vimfiles` config. Thanks for your time.

**Comment by rimrul** [comment]
I can't get vim to compile. It always fails with `
checking --with-tlib argument... ncursesw
checking for linking with ncursesw library... configure: error: FAILED
`
this might take longer than expected.

**Comment by dscho** [comment]
@rimrul is it really your own itch you are trying to scratch here? Just saying... if you use `stash` a lot, it might make more sense to concentrate on your Pull Request to make `stash` a builtin, and leave the opportunity for @srustamo to grow by tackling the issue. (I am *slightly* selfish here, of course, as I am a heavy user of `stash`).

**Comment by dscho** [comment]
In any case, I close this ticket because the `vimfiles` issue that the discussion has turned to is a completely different matter than the reported issue.

**Comment by srustamo** [comment]
I agree, I'll open a proper `vimfiles` issue.

**Comment by dscho** [comment]
> I'll open a proper vimfiles issue.

@srustamo why lean on others? You can give it a shot yourself... Of course, if you get stuck, you can still open that ticket and describe your progress so far and ask for assistance.

**Comment by kgybels** [comment]
@srustamo You can just change vim's runtimepath in your vimrc.

You can check your runtimepath with `:set rtp?`. This is what I get on my system for the standalone Vim:
`runtimepath=~/vimfiles,C:\Program Files (x86)\Vim/vimfiles,C:\Program Files (x86)\Vim\vim74,C:\Program Files (x86)\Vim/vimfiles/after,~/vimfiles/after`

If you add `set rtp^=~/.vim` to the top of your vimrc file, it will add `~/.vim` to the front of the path.

For more information about it, you can run `:help rtp`.

**Comment by srustamo** [comment]
@kgybels Thanks!
