### ISSUE TITLE
openssl stuck in mintty

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#660]
Example openssl command:

`openssl req -new > cert.csr`

If I run in `mintty`, `openssl` will get stuck.

If I run in `cmd.exe`, no problem. (It will ask you to fill in certificate details)

Git 2.7.0.2 64-bit, Win 7 x64

**Comment by dscho** [comment]
Did you try to run it through `winpty`?

**Comment by linquize** [comment]
Run winpty redirecting stdout
```
$ winpty openssl req -new > 1.csr
output is not a tty
```

Run winpty without redirecting stdout
```
$ winpty openssl req -new
```

**Comment by linquize** [comment]
Run winpty redirecting stdout
```
$ winpty openssl req -new > 1.csr
output is not a tty
```

Run winpty without redirecting stdout
```
$ winpty openssl req -new
Generating a 2048 bit RSA private key
.......................................................................+++
..............................+++
writing new private key to 'privkey.pem'
Enter PEM pass phrase:
```
It works

**Comment by dscho** [comment]
Okay, so it seems that `/mingw64/bin/openssl.exe` wants to talk directly to the Win32 Console. And MinTTY has no such Console instance, not without the help of `winpty`.

Care to open a Pull Request adding a known issue about `openssl` to the release notes?

**Comment by wengyulin** [comment]
aaa
