### ISSUE TITLE
Git bash fails to forward user PATH envvar to child processes

### ISSUE THREAD

**Issue by Marshallx** [git-for-windows/git#663]
I emailed this issue (before I figured out the cause) according to website instructions, then found this tracker so not sure where is the right place to report issues! Please update website to make this clear.

On to the problem:

1. Launch git bash
2. echo $PATH - user PATH is displayed
3. cmd
4. echo %PATH% - only system PATH is displayed

This only happens on one system and the reason is:
user PATH contains the following path: %VPROJECT%..\bin
But VPROJECT environment variable doesn't exist.
Removing the path or adding VPROJECT fixes the problem.
Presumably one or more of git-bash.exe, bash.exe and sh.exe cannot cope with expanding non-existent environment variables and so fail to concatenate user PATH to system PATH.

The problem may be seen in various child processes depending on how bash was launched. For example,
git-bash.exe -> cmd (problem)
bash.exe -> cmd (no problem)
bash.exe -> sh (no problem)
bash.exe -> sh -> cmd (problem)
git-bash.exe -> node (no problem)
git-bash.exe -> sh -> node (problem)

Obviously, the simple work-around is to remove the offending path or add the missing environment variable, however I don't think git/bash should silently fail on this - I lost almost an entire day trying to figure out what was wrong.

Incidentally, the problem only arose after I updated git to the latest version (sorry, I have no idea what version I was on before, could be several months to a year old)

**Comment by dscho** [comment]
@Marshallx didn't you figure out that there was some invalid directory in the user PATH or some such?

**Comment by dscho** [comment]
Oops, forget that I said anything, I just saw that you described the problem somewhere in the middle of the report.

Do you think you will have a chance to investigate exactly where (as in: code location) things go wrong?

**Comment by Marshallx** [comment]
Sorry, wish that I could help more, but I'm not familiar with C and I'm super swamped right now.

**Comment by dscho** [comment]
@Marshallx no worries. I think this issue can now be easily found through a web search, and we can close it for now.
