### ISSUE TITLE
git checkout branch does not checkout remote branches automatically

### ISSUE THREAD

**Issue by welnanick** [git-for-windows/git#666]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 64-bit

```
$ git --version
git version 2.7.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 10 Home 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

**Select Components:**
[ ] Additional icons
    [ ] On the Desktop
[ ] Windows Explorer integration
    [ ] Git Bash Here
    [ ] Git GUI Here
[x] Associate .git* configuration files with the default text editor
[x] Associate .sh files to be run with Bash
[x] Use a TrueType font in all console windows

**Adjusting your PATH environment:**
( ) Use Git from Bash only
(x) Use Git from the Windows Command Prompt
( ) Use Git and optional Unix tools from the Windows Command Prompt

**Configuring the line ending conversions:**
(x) Checkout Windows-style, commit Unix-style line endings
( ) Checkout as-is, commit Unix-style line endings
( ) Checkout as-is, commit as-is

**Configuring the terminal emulator to use with Git Bash:**
( ) Use MinTTY (the default terminal of MSYS2)
(x) Use Windows' default console window

**Configuring experimental performance tweaks:**
[ ] Enable file system caching

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git remote
origin
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/client
  remotes/origin/master
$ git checkout client

$ git branch
* master
```
 - What did you expect to occur after running these commands?
Same as if I ran these commands
```
$ git branch client origin/client
$ git checkout client

```

 - What actually happened instead?

Nothing

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repository, sorry.

**Comment by nalla** [comment]
Hello. I do not unterstand the issue here. Can you try to make your case clearer? The command you provided and their output are looking good as they are

**Comment by dscho** [comment]
> Private repository, sorry.

Then you need to come up with another way how to reproduce this issue.

You could start by testing whether you yourself can reproduce the issue with a public repository to begin with.

**Comment by welnanick** [comment]
I feel so dumb. I should have checked the behaviour on my linux machine, this is working exactly as it should. I was imagining features that don't exist. Closing the issue.
