### ISSUE TITLE
git add should gracefully fail for files with wrong case

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#669]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64-bit

```
$ git --version
```

2.7.1.windows.2
- Which version of Windows are you running? 32-bit or 64-bit?

64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

File-system caching
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

Nope
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
git init
echo a > file
git add file
echo b > file
git add File
```
- What did you expect to occur after running these commands?

Since the file case is incompatible with Git's index, and add has no effect, I'd expect it to fail like it would for a non-existing file
- What actually happened instead?

It seems to succeed, but file is not updated in the index.

**Comment by dscho** [comment]
I think that this same issue is most likely occurring on MacOSX' HFS+.

**Comment by dscho** [comment]
I had thought about this long and hard, and I came to the conclusion that on case-insensitive file systems, adding the file to the index (even if it was specified with a different case than recorded in the index) should succeed, and Git does that.

If you disagree, please do raise the discussion on [the Git mailing list](mailto:git@vger.kernel.org) because the issue is not specific to Windows.
