### ISSUE TITLE
The msys2 should package with ssh.exe and ssh-agent.exe

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#67]
When using git to do ssh pull, it's cause the following error:
```
C:\Users\lygstate>git pull
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
```

I am using the 64bit version of Git, maybe the result will differ in 32bit version.

The cmd\start-ssh-agent.cmd scripts are calling to ssh-agent.exe

**Comment by dscho** [comment]
Again, please feel free to start contributing by installing the SDK, fixing the bugs you find, and opening Pull Requests. You followed the call of the *developers'* preview, therefore it is fair to treat you as a developer.

**Comment by lygstate** [comment]
@dscho  Where is the place to config which msys2 package should be included in git-installer?

**Comment by dscho** [comment]
@lygstate please have a look at https://github.com/git-for-windows/git/wiki/Package-management and at https://github.com/git-for-windows/build-extra/tree/master/installer.

**Comment by dscho** [comment]
For the record, a much appreciated relief would be if you would compare all of the files contained in the portable applications (1.9.5 vs the one generated from a fully up-to-date SDK). Any file in one of them that has no equivalent in the other would need to be explained. Thank you for your help.

**Comment by dscho** [comment]
I would *really* have appreciated help with this: I, too, am busy, and instead of lightening my load (in the way I outlined in detail, the way I wish this report had been crafted), I had to spend the hours to figure things out myself: https://github.com/git-for-windows/build-extra/commit/de383fdb2e87a15247d095bc0260c846aa9c081a
