### ISSUE TITLE
OpenSSL version out of sync from Git and Ming

### ISSUE THREAD

**Issue by thezoggy** [git-for-windows/git#671]
Windows 7 x64 I upgraded Git-2.5.1-64-bit to Git-2.7.2-64-bit, noticed that openssl versions are out of sync.. using Windows CMD or Git CMD:

```
C:\>where openssl
C:\Program Files\Git\mingw64\bin\openssl.exe
C:\Program Files\Git\usr\bin\openssl.exe
```

```
C:\>"C:\Program Files\Git\mingw64\bin\openssl.exe" version
OpenSSL 1.0.2e 3 Dec 2015
C:\>"C:\Program Files\Git\usr\bin\openssl.exe" version
OpenSSL 1.0.2d 9 Jul 2015
```

why this is coming into play, I see the older ssl version being linked from python:

```
C:\>python -c "import ssl;import OpenSSL;print ssl.OPENSSL_VERSION;"
OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by dscho** [comment]
@thezoggy why not give it a try to update the MSYS2 OpenSSL package? [This wiki page](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages) has all the information to get going.

**Comment by Dirk1966** [comment]
Got the following in the git sdk (Win10-32, git version 2.7.1.windows.2):
$ where openssl
C:\git-sdk-32\usr\bin\openssl.exe
C:\git-sdk-32\mingw32\bin\openssl.exe
$ /C/git-sdk-32/usr/bin/openssl.exe version
OpenSSL 1.0.2d 9 Jul 2015
$ /C/git-sdk-32/mingw32/bin/openssl.exe version
OpenSSL 1.0.2e 3 Dec 2015

**Comment by shiftkey** [comment]
These seem to be back in sync again:

```
$ git --version
git version 2.11.0.windows.1
$ /mingw64/bin/openssl version
OpenSSL 1.0.2j  26 Sep 2016
$ /usr/bin/openssl version
OpenSSL 1.0.2j  26 Sep 2016
```

Closing this out due to inactivity.
