### ISSUE TITLE
Git GUI hangs when staging modified files

### ISSUE THREAD

**Issue by cztomczak** [git-for-windows/git#673]
It hangs quite often - once or twice per commit I would say. UI is unresponsive/freezes. I have to kill the "wish.exe" process in the task manager.

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

Tried both 32-bit and 64-bit and it hangs on both. 

Issue occurs in 2.7.0, 2.7.1 and 2.7.2.

```
$ git --version
git version 2.7.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit Windows 7 Pro SP1

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

I had a fresh install of Windows 7 recently.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git GUI from context menu.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Git GUI from context menu.

 - What did you expect to occur after running these commands?

To let me do my work smoothly.

 - What actually happened instead?

Hang/freeze of the process.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/cztomczak/cefpython

**Comment by dscho** [comment]
I fail to follow the indicated MCVE. Care to add a bit more detail so that I have a chance of reproducing the bug here?

**Comment by dscho** [comment]
Okay, I really went quite to an unreasonable length trying to reproduce this very, very incompletely described issue.

I tried to reproduce the hang by cloning the indicated repository, adding a line to the `AUTHORS.txt` file, opening the directory in a Windows Explorer, right-clicking in the empty area, choosing `Git GUI Here` from the context menu, then either clicking the blue icon next to the modified file or right-clicking into the diff and then selecting `Stage Hunk` from the context menu. There was no hang.

Closing this ticket for now. Should there be enough information at some stage that allows anybody to reproduce the problem, it is easy enough to reopen it.

**Comment by cztomczak** [comment]
@dscho What OS were you testing it on?

**Comment by cztomczak** [comment]
@dscho the steps, you are doing it right. But like I said in the report, it is not always reproducible. I am staging lots of files, not one or two, but about 50.

**Comment by dscho** [comment]
> What OS were you testing it on?

Microsoft Windows [Version 10.0.10586]

> @dscho the steps, you are doing it right. But like I said in the report, it is not always reproducible. I am staging lots of files, not one or two, but about 50.

Well, I went by the indicated MCVE:

> - What commands did you run to trigger this issue? If you can provide a Minimal, Complete, and Verifiable example this will help us understand the issue.
> 
> Git GUI from context menu.

It does not say 50. It does not even say "stage", actually :grinning:

**Comment by cztomczak** [comment]
@dscho The title says it "Git GUI hangs when staging modified files". Issue occurs on Windows 7 and you were testing on a different OS.

**Comment by dscho** [comment]
I am not interested in arguing whether or not you mentioned the number 50 before. This ticket's lack of information is unfortunately deciding for me that I cannot spend more time on it.

Here are a couple of pointers so you can help yourself:
- if Git GUI from the context menu displays that problem, it most likely will also display the problem if started from the Git Bash as `git gui`
- when starting from the Git Bash, it is easy to tell Git to show you a trace of internally executed commands, by setting the environment variable `export GIT_TRACE=1` (and that log should tell you where Git is spending its time, or is hanging).

Sorry that I cannot be of more help.
