### ISSUE TITLE
Git GUI: push, username dialog - asterisks when typing username

### ISSUE THREAD

**Issue by cztomczak** [git-for-windows/git#675]
The username dialog shows asterisks when typing username. Asterisk hidden characters (*****) should be displayed when typing password. Not for username. When typing I saw asterisks and instantly deleted first characters of my username and started typing my password instead. Then the next dialog showed asterisks as well so I started typing my password again. Then a dialog appeared with error about wrong username/password - and it showed my password in plain-text. If there was a person sitting next to me he or she would know my password! And that's my secret, I definitely don't like this feature.

- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

32-bit.

```
$ git --version
git version 2.7.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit. Win7 Pro SP1 .

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git GUI from context menu.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
from menu > remote > push
```
 - What did you expect to occur after running these commands?

To see a field to enter username.

When I type "cztomczak" i expect to see:
```
cztomczak
```

 - What actually happened instead?

When I type "cztomczak" i see in the field:
```
*******
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/cztomczak/phpdesktop

**Comment by yaras** [comment]
> The username dialog shows asterisks when typing username. Asterisk hidden characters (*****) should be displayed when typing password. Not for username.

That's true. 

I think the problem is in `credential_getpass` (`credentials.c`). I'll try to fix this issue next week and if I succeed I'll send a pull request with fix and I'll put comment here.

**Comment by cztomczak** [comment]
Just tested and it worked only on first push (a nice Windows credentials dialog appeared). When doing second push to an another GitHub repository I was presented with the old dialog with username input as asterisks. Attaching screenshot. Git version 2.7.3.windows.1 . Should this issue be reopened or a new issue be submitted?

![username-dialog-asterisks-again](https://cloud.githubusercontent.com/assets/1187415/14397475/d4328c68-fddd-11e5-9dd1-733ddf4986ed.jpg)

**Comment by dscho** [comment]
You need to retest this with 2.8.1. My guess is that it will no longer be an issue because the Git Credential Manager is now enabled by default.

**Comment by cztomczak** [comment]
@dscho with 2.8.1 Windows Credentials window doesn't show anymore even on first push. I see a blank window with "Working... please wait..." for about 2 minutes and then the error "Fatal: TaskCancedledException" as seen on the screen above. Username is with asterisks.

Git version: 
```
MINGW64 /c/github/cefpython (master)
$ git --version
git version 2.8.1.windows.1
```
This issue needs to be reopened.

**Comment by dscho** [comment]
> This issue needs to be reopened.

Aren't you experiencing a totally different issue now?

**Comment by cztomczak** [comment]
@dscho Two issues: 1) two minute delay and TaskCancelException - a new issue 2) Asterisks in username - old issue
