### ISSUE TITLE
fatal: BUG: your vsnprintf is broken (returned -1)

### ISSUE THREAD

**Issue by Todd-Weed** [git-for-windows/git#676]
### Setup

- architechture: 32-bit
- git version: 2.7.0.windows.1.13.g06d0ace
- options, environment: default (except for custom `~/.bashrc`, `~.minttyrc`)
- shell: bash

### Description of how error occurred

I have been using this Git for Windows for about two months and today I went to push one of my repositories and got this message:

    $ git push
    fatal: BUG: your vsnprintf is broken (returned -1)
    error: failed to push some refs to 'git@github.com:ToddWeed/general-scripts.git'

I am not really sure what caused this bug as it has been working fine until know. I have probably pushed about 10 repositories over these last two months at various intervals.

The only reference I found that might help with the bug was [this](http://git.661346.n2.nabble.com/Breakage-in-master-td7246740.html). Unfortunately, it is a bit above my ability to understand... I do get that setting `NO_GETTEXT=YesPlease` in the Makefile may fix this; however, I have not tried it. I have not tried it because the post is four years old and because apparently no one else is having this bug.

Any advice or questions would be appreciated.

Thank you for your time,

Todd Weed

**Comment by dscho** [comment]
> 2.7.0.windows.1.13.g06d0ace

How did you install Git for Windows? Did you try one of [our official releases](https://github.com/git-for-windows/git/releases) instead?

**Comment by ToddWeed** [comment]
My apologies, I am using the Git SDK.

I tried the official release and it `git push` does work. For reference, I tried [rebuilding git](https://github.com/git-for-windows/git/wiki/Building-Git).. I was not able to pull, I got the same error. Rebuilt anyway with the `make install` command but am still getting the same error.

**Comment by dscho** [comment]
> I tried rebuilding git.

Hrm. Are you sure you are using Git for Windows' latest `master`? In that case, `git version` would report:

> `git version 2.7.2.windows.1.6.g4f91362`

For the record, the `vsnprintf()` error is fixed by f0f4d75bd08c1f4236cb3dc16eb45cda2e845671. If you do not have that change (or the equivalent, rebased one), then you get the `vsnprintf is broken (returned -1)` error.

**Comment by ToddWeed** [comment]
I had to download the zip because `git pull` did not work:

    # curl -L https://github.com/git-for-windows/git/archive/master.zip | bsdtar xvf - -C /usr/src/
    # cd /usr/src/git-master

... and then rebuild git.

Thanks for pointing out the bug. The git build has a bug in it currently so it won't build but I imagine this will fix it. Thank you.

**Comment by dscho** [comment]
> git pull did not work

How? What was the precise output?

> The git build has a bug in it currently

Not here. As I said, I do not know how you ended up with the HEAD that you had. I really make a point of *at least* compile testing before pushing to `git-for-windows/git`'s `master`.

Now, if you were checking out upstream's `master`, I would understand: [the fix](https://github.com/git/git/commit/f9206ce26818c3fc1cfd12cfce0acf0bd582270a) was only [merged](https://github.com/git/git/commit/4b589e5b28af077ddbdd5b72b6217c7447d45cb5) on February 17th ...

Maybe we can still figure out what went wrong?

**Comment by ToddWeed** [comment]
`git pull` generated the same error message regarding vsnprintf that `git push` did.

As for the error, I am likely mistaken. The build ended with with a lot of HTML code that I 

As for the building git error, the build ended by outputting HTML code which I mistakenly took to be an error. Sorry about this, it was the end of my day and I judged it quicker than I should.

I am learning how the Git-for-Windows SDK is built and it appears there are two version of git on my machine: the pacman installed version (`/usr/bin/git.exe is owned by git 2.7.2-1`), and the one build by the installer and just compiled and installed by me:

    $ ls -l /mingw32/bin/git.exe
    -rwxr-xr-x 2 public 1049089 8657990 Mar  7 09:51 /mingw32/bin/git.exe

Unfortunately, and I hope I hope to goodness I am using this correctly, I am still getting the same vsnprintf error running this:

    $  /mingw32/bin/./git.exe pull

**Comment by dscho** [comment]
Yeah, the difference between MINGW and MSYS2 needs explaining: https://github.com/git-for-windows/git/wiki/The-difference-between-MINGW-and-MSYS2

The good news is that in the SDK you will always be able to rely on `/usr/bin/git` when `/mingw32/bin/git` does not work.

I still think that your `/usr/src/git` is not at the correct revision (47d64e6fbe8295cf6ed30d24c38431c83881f6c2 as of time of writing)
