### ISSUE TITLE
freezes randomly when exiting

### ISSUE THREAD

**Issue by Hand-E-Food** [git-for-windows/git#680]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

git version 2.7.2.windows.1

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 7 Enterprise x64

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Installed using Chocolaty defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell and Windows Command Prompt

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

    git pull

and even just the basic

    git

It works the first two or three times, then the next one freezes after displaying output.

 - What did you expect to occur after running these commands?

The command to perform, then return control to the shell.

 - What actually happened instead?

After executing the command, the application froze with two git.exe processes still running at 0% CPU.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It fails on different repositories.

**Comment by dscho** [comment]
I *never* have something like that happen to me, and those commands do not reproduce the problem for me.

It might be possible that things become clearer by looking what happens during these freezes using the [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/bb896645).

**Comment by dscho** [comment]
Closing for now. It is really easy to reopen the ticket should the discussion turn live again.
