### ISSUE TITLE
Integrate ssh-pageant

### ISSUE THREAD

**Issue by klaernie** [git-for-windows/git#683]
Hi there,

thanks for the nice package. In my environment I often have pageant or a pageant-protocol speaking replacement running.

Could you please integrate [ssh-pageant](https://github.com/cuviper/ssh-pageant)? As I am told in cuviper/ssh-pageant#41 this should be pretty easy.

**Comment by cuviper** [comment]
It's already present in git-for-windows/MSYS2-packages, so I would imagine it's mostly just a matter of deciding whether you want to build it.

**Comment by dscho** [comment]
> Could you please integrate ssh-pageant? As I am told in cuviper/ssh-pageant#41 this should be pretty easy.

@klaernie As it should be pretty easy, let me play the ball back into your court. Give it a try, and then open a Pull Request (even if you get stuck at some point, I can assist you so you can finish the job).

**Comment by albertosantini** [comment]
@klaernie Of course, I am missing something.

I have been using the following setup:

- You need a ppk key converted from id_rsa one, using puttygen.
- Start `pageant.exe`. I run it automatically when Windows starts - Startup folder - add the key once and finally insert the passphrase.
- Set `GIT_SSH=C:\Putty\plink.exe`.

Now I can use git with ssh key.

Reference: http://wazem.blogspot.it/2007/11/how-to-convert-idrsa-keys-to-putty-ppk.html

**Comment by dscho** [comment]
Please also note that PuTTY support in Git for Windows has traditionally caused quite a few problems so that we only even offer it when there are *saved sessions*. One rather nasty problem was that using PuTTY to connect to a new host asked for a password but did not even let the user *enter* the password.

That, combined with the fact that there were only volunteers when it came to claim how easy the integration would be (as opposed to volunteers to actually integrate the thing), make me pretty certain that I should just close this ticket and move on.

**Comment by cuviper** [comment]
Note that ssh-pageant is just a drop-in replacement for ssh-agent.  You'd
still be connecting with openssh, so I think your password concern doesn't
apply.

I use Cygwin myself, which is why I haven't volunteered here.  But as the
author, I have made sure it works on MSYS2, which is why I think it will be
easy to integrate.  *shrug*  It's up to you.

**Comment by klaernie** [comment]
Hi @dscho, Sorry I did not intend to upset you. I am not knowledgeable in msys2 or how packaging/integration works. I will try to integrate ssh-pageant as soon as my time permits. Still the question @cuviper mentioned stands: would you want to support it?

I also took a look at the instructions for using plink, but that seems overly complex and moves it to the wrong place. Openssh is the clearly superior ssh package, but in corporate environments putty is loved for its easy deployment, a job this project solves really beautifully. My company for example uses central LDAP accounts built from the active directory, also the automatic provisioning deploys SSL client certificates to every client machine. A company-built tool implements the pageant protocol and provides the client certificate as putty key. This is the reason why I want to see pageant keys in the git bash, as everything else inside the company is deployed automatically. Sadly there is no way my company provides support for this directly.

I will do my best to not disappoint you.

**Comment by dscho** [comment]
> You'd still be connecting with openssh, so I think your password concern doesn't apply.

@cuviper I believe that when I see it.

> I am not knowledgeable in msys2 or how packaging/integration works.

@klaernie Ask and ye shall receive: https://github.com/git-for-windows/git/wiki/Package-management

> I will try to integrate ssh-pageant as soon as my time permits.

Nice! Please note that the MSYS2 package `ssh-pageant-git` might be usable as-is.

If that is the case, you just need to integrate it into the installer. That would entail the following:

1. adding it to [the script that generates of the files to package](https://github.com/git-for-windows/build-extra/blob/master/make-file-list.sh) (also for Portable Git and maybe in the future `.msi`), and
2. adding support in [the InnoSetup-based installer](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss).

> Still the question @cuviper mentioned stands: would you want to support it?

Ideally you would support that feature (and I could assist with that), as I am not exactly underwhelmed with work (just have a look at all the open issues in this bug tracker despite my best efforts to keep them at bay).

**Comment by klaernie** [comment]
@dscho Thanks for the pointers. I'll see how far I get as soon as my time allows.
Of course I'll help support the feature from my end, I'm already the "everything ssh" support guy at work ;)

**Comment by dscho** [comment]
@klaernie any luck so far?

**Comment by klaernie** [comment]
@dscho didn't have the time yet, I read the docs, and I have to say getting started seems quite complex.

**Comment by dscho** [comment]
@klaernie let's just close this ticket, to get the pressure off of you. Feel free to work on this whenever/if you have time, and when you get stuck, just open a Pull Request and mark it as "[DO NOT MERGE YET]", describing where you got stuck.

**Comment by landstander668** [comment]
While it doesn't directly address integration, I've added a Wiki page explaining [how to manually configure ssh-pageant](https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant). It's working beautifully for me with version 2.8.1 64-bit on Windows 7.

If time allows, I might take a stab at proper integration over the next several weeks if @klarnie doesn't beat me to it. As he mentioned, this project seems pretty complex... from my newbie perspective, at least.

**Comment by landstander668** [comment]
@dscho If you want to reopen this issue, I'll try to run with it (see pull request above).

**Comment by landstander668** [comment]
@dscho I believe the necessary changes are now all in order, and have therefore removed the DO NOT MERGE YET tag from my pull request. With the _ssh-pageant_ utility already being packaged for MSYS2, the diff only includes 5 lines of changes to the _build-extra_ repository.

On a related note, I'm really digging your SDK setup. While Git for Windows looks really complex from the outside, making these changes and building new installers (normal, portable, and SDK) ended up being surprisingly simple. I won't hesitate to try again, next time the opportunity arises. (-;

**Comment by landstander668** [comment]
I've added a [second pull request](https://github.com/git-for-windows/MINGW-packages/pull/17) against the [git-for-windows/MINGW-packages](https://github.com/git-for-windows/MINGW-packages) repository. This one adds a`start-ssh-pageant.cmd` script, based upon `start-ssh-agent.cmd`, to simplify starting the PuTTY agent at logon time. This also makes it easy to use with git operations performed outside of Git Bash... I've tested under both Git CMD and directly from the command prompt, without encountering any breakage.

**Comment by dscho** [comment]
@landstander668 thanks for your outstanding contributions!

**Comment by landstander668** [comment]
@dscho I've updated both pull requests per your request. Please let me know if any additional changes are needed.

**Comment by landstander668** [comment]
@klaernie Both pull requests have been merged, so _ssh-pageant_ support should be included in the next Git for Windows release. :)

@dscho I'll update the Wiki page to match within the next few days... not sure if I'll have an opportunity before Monday. If you think a release might occur before then, let me know and I'll try to find the time to knock it out earlier.

**Comment by dscho** [comment]
> I'll update the Wiki page to match within the next few days...

@landstander668 thanks!

**Comment by landstander668** [comment]
The [Wiki entry](https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant) has been updated. I'll probably tweak it slightly when the next Git for Windows release becomes officially available, but I think we can call the ssh-pageant addition essentially complete at this point. (-;

**Comment by dscho** [comment]
Thanks!

**Comment by landstander668** [comment]
The Wiki document has been updated to indicate that _ssh-pageant_ support landed in the 2.8.2 release. I also added a note that setting the global **SSH_AUTH_SOCK** variable (which is optional) could potentially conflict with other Uinx-esque software (Cygwin, GitHub?, etc.).

**Comment by dscho** [comment]
@landstander668 You are awesome.
