### ISSUE TITLE
`git show` not working with files beginning with periods

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#685]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

Windows 8 x64, running 64-bit git

```
$ git --version
git version 2.7.2.windows.1
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

File caching set to enabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Happens on Windows only, works fine on Ubuntu 15

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Default bash shell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git show origin/develop:.gitmodules
```

 - What did you expect to occur after running these commands?

I expect the contents of the `.gitmodules` file on ref `origin/develop` to be printed.

 - What actually happened instead?

No output

Note on Ubuntu 15 I get this output:

```
$ GIT_TRACE=1 git show origin/develop:.gitmodules
10:49:09.589883 git.c:348               trace: built-in: git 'show' 'origin/develop:.gitmodules'
10:49:09.590826 run-command.c:338       trace: run_command: 'less'
```

I obtained this output by running `ssh user@ubuntumachine` FROM an actual Git Terminal on my Windows machine. So this should rule out any issue with the terminal itself, right?

The corresponding command run in a repository ON my windows machine using the git terminal:

```
$ GIT_TRACE=1 git show origin/develop:.gitmodules
10:48:00.961265 git.c:348               trace: built-in: git 'show' 'origin\develop;.gitmodules'
10:48:00.968267 run-command.c:343       trace: run_command: 'less'
```

The only observable difference I see is that on Windows a `;` (semicolon) is used in the trace output, but a `:` (colon) used on Ubuntu. Note that show works fine as long as the file doesn't begin with a period. For example, both platforms output fine if I do `git show origin/develop:CMakeLists.txt`.

**Comment by whoisj** [comment]
Confirmed.

Works as expected from PowerShell, but with Git Bash there is no output.

**Comment by dscho** [comment]
The culprit is the POSIX <-> Windows path conversion, mentioned in our [release notes](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues):

> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:

>  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`

>  Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion.

Granted, it does not talk about colons followed by a dot per se, but it is essentially the same problem. To the Bash, you see, it looks as if you are passing a *path list* of the form `<path1>:<path2>:<path3>`, using the standard POSIX path separator `:`, and it sees that you want to pass this path list to the non-POSIX program `git.exe`, so it assumes that `git.exe` wants this path list to have the standard *Windows* path separator `;`. The `MSYS_NO_PATHCONV=1` trick helps in this case. Not using the Bash would also help in this case, of course.

**Comment by dscho** [comment]
As changing the POSIX <-> Windows path conversion according to this ticket's wishes would break more things than it would fix, I am closing this as "wontfix".

**Comment by rcdailey** [comment]
I'm sad to see that this will never be fixed. Are you saying this is
impossible to fix? It's ok to just leave it broken? A valid working command
does not work out of the box on Windows. I see that as a huge problem.

**Comment by rcdailey** [comment]
Your workaround does work, but unfortunately it requires me to type it each time I do `git show`. This gets rather annoying. Would be nice if I could stuff this into an alias, but that isn't early enough. I can't switch it off completely otherwise it breaks other commands.

How am I supposed to live with this issue? You mentioned switching shells, but I don't see zsh bundled with Git for Windows, for example. I'm not sure what options I have here. I am also not sure what the pros/cons are for changing my shell.

Is there some reading material on this? Could you explain in more detail here? What would you recommend in these situations? The two slashes in the front would be an improvement, but unfortunately in this case I don't think it will since I have no slash at the beginning (only the middle). 

According to your release notes, it's supposed to only check slash at the start. In this case, there is only a slash in the middle of `origin/develop` (just `develop` doesn't have this issue). The slash triggers this conversion. But it's in the middle. Does the location of the slash not matter?

**Comment by drizzd** [comment]
Note that `MSYS_NO_PATHCONV=1` works only with git-for-windows patches to the msys2-runtime. Users of the upstream msys2-runtime can use `MSYS2_ARG_CONV_EXCL='*'` instead, documented at https://github.com/msys2/msys2/wiki/Porting#filesystem-namespaces.

    $ git rev-parse --sq-quote origin/develop:.gitmodules
    'origin\develop;.gitmodules'
    $ MSYS2_ARG_CONV_EXCL='*' git rev-parse --sq-quote origin/develop:.gitmodules
    'origin/develop:.gitmodules'

@dscho I agree that changing the path conversion would only cause issues elsewhere. Just for the record, here is an example that would break:

    $ MSYS2_ARG_CONV_EXCL='*' git ls-files /home/drizzd/git/README.md
    fatal: Not a git repository (or any of the parent directories): .git

But if 'origin\develop;.gitmodules' does not match a file literally, we could interpret it as <rev>;<path>, same as we interpret origin/develop:.gitmodules as <rev>:<path> if it does not match a file.
