### ISSUE TITLE
how can git bash remember password??

### ISSUE THREAD

**Issue by simonbaker** [git-for-windows/git#688]
how can git bash remember password??
because every time I pull or push,git bash want me to enter password.
and I had try some ways,but cant resolve my problem.
some ways like:
1 http://stackoverflow.com/questions/22267764/automatically-cache-git-credentials-from-a-windows-batch-script
2 http://stackoverflow.com/questions/19029987/git-asks-for-password-for-each-commit-and-pull/19030243#19030243
3 http://my.oschina.net/u/140714/blog/193557?fromerr=PvubNd96

my git version is "2.6.4.windows.1"

**Comment by nalla** [comment]
You can create {{_netrc}} file in your {{~/}} directory. Within that file you can put something like

```
machine github.com login <username> password <password>
```

**Comment by whoisj** [comment]
I'll plug for [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) here.

**Comment by dscho** [comment]
Both comments are excellent advice and address this request for assistance.

**Comment by simonbaker** [comment]
I try but still not success.
Maybe it's my computer problem.
Thanks.

**Comment by dscho** [comment]
> I try but still not success.

This is quite little in the way of information. Maybe you want to get into the habit of being more verbose, at least telling us enough so we can help? :smile:
