### ISSUE TITLE
Binary tarballs are wrongly packaged, causing git crashes (both 32- and 64-bit versions affected)

### ISSUE THREAD

**Issue by yukoff** [git-for-windows/git#689]
- [+] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64-bit version of git, extracted from binary package Git-2.7.2-64-bit.tar.bz2

But the issue applies to 32-bit version as well

```
$ git --version
git version 2.7.2.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

64-bit Windows 10
- What options did you set as part of the installation? Or did you choose the
  defaults?

Binary package extracted, no installation
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

Seems none of such
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Mostly CMD
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
git clone ...
```
- What did you expect to occur after running these commands?

Cloned repo
- What actually happened instead?

Git crushes complaining about bad image for several dlls (following are under `<git_install_dir>/mingw[32|64]/libexec/git-core/`):
- libiconv-2.dll
- libpcre-1.dll
- zlib1.dll

As I can see, some dlls are of zero size (at least those mentioned above), please find `ls -lah` result in [binary-dlls.txt](https://github.com/git-for-windows/git/files/159703/binary-dlls.txt)

**Comment by fourpastmidnight** [comment]
Did you manually unzip the tarball? If so, did you run `post-install.bat` after unzipping the tarball? Please see the `README` for the portable Git for Windows distribution for more information.

**Comment by dscho** [comment]
> 64-bit version of git, extracted from binary package Git-2.7.2-64-bit.tar.bz2

I used MSYS2's `tar` to unpack this archive and everything works perfectly.

What procedure did you use, @yukoff, to unpack the archive?

**Comment by dscho** [comment]
> What procedure did you use, @yukoff, to unpack the archive?

Well, without an answer I cannot help.

**Comment by yukoff** [comment]
Sorry, missed previous comments. @dscho, I unzipped it with tar -xf under msys2. Rechecked with current 2.11.1 - seems not an issue currently. Thanks!

**Comment by yukoff** [comment]
@fourpastmidnight,

> Did you manually unzip the tarball? If so, did you run post-install.bat after unzipping the tarball? Please see the README for the portable Git for Windows distribution for more information.

Git-2.X.X-64-bit.tar.bz2 doesn't ship neither post-install.bat nor README, I guess you were referring to PortableGit-2.X.X-XX-bit.7z.exe, but that was not the case of this issue. Anyway, thanks!
