### ISSUE TITLE
Problem with Visual Studio 2013/2015 native git plugin

### ISSUE THREAD

**Issue by rfnx** [git-for-windows/git#691]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

Hello,

I'm not sure if this question should be here or on a Microsoft forum, sorry if I'm at the wrong place.

I'm trying to use Visual Studio (2013/2015) git features but it does not detect Git if I'm using PortableGit, even if I set up the environment variable correctly (exactly like after using the installer) : VS asks for installation of git tools.

It's important for me because it works at home where I have admin rights, but I can't install Git on my company computer.

My question is : what are the magic steps the installer does that make Visual Studio detects git if I'm using the installer but not PortableGit ?

I did some tests and here are my results : 

- VS only works with 32 bits version of Git
- It does not matter where I install Git with the installer (even on another drive), VS will detect it.
- But if I'm using PortableGit, it never works. Even with the PATH set up exactly like after using the installer (to the cmd subfolder & same position in the PATH variable, "echo %path%" gives the same output)
- Even if I rename "PortableGit" folder to "Git", it does not work.

I'm using Windows 10 (64 bits) for these tests but I use Windows 7 (64 bits) at work.

Thanks for reading

**Comment by linquize** [comment]
Does VS only work with 1.9.5 or earlier?

**Comment by rfnx** [comment]
No, VS (2013/2015) works with latest version for windows : 2.7.2 (32 bit only) . But only with the installer, not with the portable version PortableGit.

**Comment by linquize** [comment]
What kind of operations do VS use `git.exe` to perform?
Many functions use the `libgit2` library.

**Comment by rfnx** [comment]
You can commit, create branches, etc... in the VS UI. But my question is : what is the installer exactly doing ? Or what is PortableGit not doing after extracting ?

**Comment by rfnx** [comment]
I understand what you meant, I don't need to install git for Windows (or PortableGit) to use it in VS... But that warning everytime I opened the Team Explorer is really misleading. I still don't know with which feature it is required but it seems to work (I can commit, etc...). Thanks for your answers.

**Comment by dscho** [comment]
> I'm trying to use Visual Studio (2013/2015) git features but it does not detect Git if I'm using PortableGit, even if I set up the environment variable correctly (exactly like after using the installer) : VS asks for installation of git tools.

You are referring to the Team Explorer, correct? If so: yes, it looks for registry keys to figure out whether Git is installed or not. PortableGit does not set these registry keys.

However, you should be able to install Git for Windows as regular user (in which case it gets installed inside your home directory).

**Comment by linquize** [comment]
What is the purpose of detecting git installed? Such as finding system-wide config?

**Comment by rfnx** [comment]
@linquize I'm using git in VS with the native plugin (Team Explorer) since yesterday and it works really well (even with git tools not detected) ! Sorry for wasting your time...

@dscho Thanks for the explanation ! About the installer, I can't launch it without admin right.

**Comment by dscho** [comment]
> About the installer, I can't launch it without admin right.

Hmm. It should be possible at least to launch with power user rights...

**Comment by rfnx** [comment]
I don't know how to start an app as a power user, and I'm sure I won't have these rights on my company computer. It's a very strict environment and I only have a normal user account.

Of course if you find a way to use the installer as normal user it is better, but for the moment it's OK, I can use VS with git in Team Explorer and I can launch a cmd anywhere because git is in my path.

**Comment by whoisj** [comment]
@rfnx Team Explorer's Git functionality does not actually depend on Git.exe being present in the system. VS 2015 LibGit2. The notifications about installing Git.exe can be annoying, but should not block your usage of VS for Git operations.

**Comment by rfnx** [comment]
@whoisj Yes it is working really well but I keep the portable version of git because I can get more info with the cmd (Windows command line).

Thank you all for your help.

**Comment by whoisj** [comment]
@rfnx thanks for the confirmation.

I'm going to close this issue for now as there's not much we can do from the Git for Windows side to stop Visual Studio from relying on Registry entries to detect if Git is installed or not.
