### ISSUE TITLE
64-bit git bash sees directory as a file, so "cd" fails with "Not a directory"

### ISSUE THREAD

**Issue by syntien** [git-for-windows/git#693]
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

64-bit
git version 2.7.2.windows.1

```
$ git --version
git version 2.7.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 7 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

File system is IBM DFS presented as an SMB share point.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash (MINGW64)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cd Dev
```
 - What did you expect to occur after running these commands?

Current working directory should be Dev

 - What actually happened instead?

This message appeared:
bash: cd: Dev: Not a directory

Please note that when I issue an "ls" command I see:

Dev/

indicating Dev is a directory, but when I issue "ls -l" I see:

-rw-r--r--  6 pscott 197121        0 Oct 12 14:16 Dev

indicating that Dev is a regular file. Of course, that is wrong, and it's inconsistent with the normal "ls" output which indicates Dev is a directory; and Dev *is* a directory, as I can change to it in the 32-bit git bash shell or in Windows cmd prompt.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
> cd Dev

This is not a Verifiable Example.

**Comment by syntien** [comment]
And yet, those are actual results copied right from the screen. git is unusable on this file system either from bash or from Windows cmd window. As I reported, the file system is IBM DFS presented as an SMB share point. But keep in mind that neither Eclipse git nor Atlasssian SourceTree have any problems with this file system (or any other software for that matter), and earlier versions of this software didn't either. It is clear that this version of the tool is now broken when used with this file system.

If there is anything I can do to make this problem "verifiable" please let me know.

**Comment by kostix** [comment]
I wonder which product is used to provide CIFS/SMB shares on the server machine.

Another dumb question: do I assume correctly that other 64-bit software capable of filesystem browsing running on the client machine are fine with classifying that "Dev" directory as such and are able to select it as current ("change into it")?

**Comment by kostix** [comment]
I'd say it's also interesting to know if Git itself has any problems with this directory (while running from another shell, say, plain `cmd.exe`).

**Comment by syntien** [comment]
kosti, the file system is IBM DFS (distributed file system) running on a z/OS LPAR. No other software has a problem with this file system (nor did a prior version of git-bash, although, I forgot which one I replaced).We've been using this file system with Windows and Mac workstations for years without any issues. I can go into cmd.exe (Windows 7) and cd to the directories just fine. And a directory list (dir) will show the directories as directories. The same is true when mounting the file system on a Mac. Also keep in mind that when I do an "ls" in git-bash, it ALSO shows directories as a directory (trailing slash), but when I do "ls -l" it shows it as a file (a dash in the directory column rather than a d). And, of course, in git-bash when I cd to a directory, say Dev for example, it says "bash: cd: Dev: Not a directory".

**Comment by syntien** [comment]
kosti: no, git itself seems to be fine.

**Comment by dscho** [comment]
> those are actual results copied right from the screen

@syntien what makes you think that this fact makes the example verifiable? It is not verifiable at all. Give me a chance to help you, will ya?

**Comment by syntien** [comment]
dscho, what makes you think i think that makes the example verifiable? It's 100% reproducible, but short of you sitting next to me, it's not verifiable. I provided all the empirical information I have. And, as I have already stated, "If there is anything I can do to make this problem 'verifiable' please let me know." Perhaps you didn't read that part. Or do you have trouble with comprehension?

The problem only seems to exist with the DFS file system on a company intranet, and I cannot grant you or anyone else access. If anyone else has access to a DFS file system perhaps they can verify it.

Perhaps there's some kind of trace that can be activated? Perhaps there's some diagnostic code that I can test with? Why would the bash shell show a directory as a directory with "ls" but not as a directory with "ls -l"? That seems like a big clue. Obviously, the "cd" command sees the file system the way "ls -l" sees it. Seems like a place to add diagnostic or trace code that I can run to make this problem "verifiable" while also pointing to the cause.

**Comment by dscho** [comment]
> Perhaps there's some kind of trace that can be activated?

You could try running [ProcMon](https://technet.microsoft.com/en-us/sysinternals/bb896645). And/or `strace`.

**Comment by dscho** [comment]
> > cd Dev
> 
> This is not a Verifiable Example.

It is still not a Verifiable Example, therefore it still fails to be an MCVE (Minimal, Complete & *Verifiable* Example).

Unless you provide such an MCVE, or alternatively step up to the task and diagnose further with ProcMon and strace, there is nothing anybody else can do to help you.

So I will close this ticket for now. It is really very easy to reopen it as soon as there are new developments.
