### ISSUE TITLE
Git says there are local changes, but there are no changes.

### ISSUE THREAD

**Issue by ben-page** [git-for-windows/git#694]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64-bit

```
$ git --version
git version 2.7.2.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 10 64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

Defaults except:
Deselected Windows Explorer Integration
Use Git and optional Unix tools from the Windows Command Prompt
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

The projects that have the issue are Visual Studio projects. Visual Studio has it's own git client.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu (cmd)
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

Repo is behind the remote.

```
>git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
        modified: XXXXXXX
no changes added to commit (use "git add" and/or "git commit -a")

>git pull 
Updating cebdb13..076de5e
error: Your local changes to the following files would be overwritten by merge:
        XXXXXXX
Please, commit your changes or stash them before you can merge.
Aborting
```

I don't care about the changes, so checkout the file (restore from index).

```
>git checkout XXXXXXX
```

Still says there are changes.

```
>git pull
Updating cebdb13..076de5e
error: Your local changes to the following files would be overwritten by merge:
        XXXXXXX
Please, commit your changes or stash them before you can merge.
Aborting
```

Maybe index is corrupt, so reset the index and working tree:

```
>git reset --hard
HEAD is now at cebdb13 Commit Message
```

Still says there are changes.

```
>git pull 
Updating cebdb13..076de5e
error: Your local changes to the following files would be overwritten by merge:
        XXXXXXX
Please, commit your changes or stash them before you can merge.
Aborting
```
- What did you expect to occur after running these commands?

The working tree to be overwritten and the pull to succeed.
- What actually happened instead?

I'm not sure, but the pull fails. However, if I manually delete the index and the file, it works.

```
>rm .git\index
>rm XXXXXXX
>git reset --hard
>git pull
Updating cebdb13..076de5e
Fast-forward
```

The repos that exhibit this behavior are Visual Studio projects and the problem files are text files. I don't think the problem is related to line endings. `git diff` returns nothing and the projects have `* text=auto` in the `.gitattributes` file and `core.autocrlf` set to `true`.

I believe the caused of the problem to be Visual Studio. This never happens on any project that doesn't use it.

But my understanding is that even if VS messed up the git index, `git reset` should fix it. And if VS messed up the file (line endings or otherwise), the `git reset --hard` should revert it. So it may be a bug in git for Windows.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

It's a private repo my employer will not allow me to upload it.

**Comment by Radrik5** [comment]
`git reset --hard` may not fix the broken entry in the index. Could you try removing the index file and running `git reset`? Could you also try adding the file to the index? Does it change the output of `git status`?

**Comment by tboegi** [comment]
I'm nearly sure that the repo has file committed CRLF line endings, and
Git want to normalize them to LF, and shows them as modified.
Possible workaround:
use "* text -crlf" instead of "* text=auto"
Possible solution:
"normalize" the repo.

**Comment by mikhailmaximov** [comment]
I have the same or similar isssue.
When I open project in Visual Studio and it senses Git repo, it creates .gitattribute file.
It looks innocent, but lead to consequences described above.
If you remove .gitattributes, everything returns back to normal.

**Comment by mikhailmaximov** [comment]
Here is the file:
[gitattributes.zip](https://github.com/git-for-windows/git/files/178666/gitattributes.zip)

The file itself has Windows CRLF line endings.
Files, git status points as changed, has Linux origin, checked in on Linux computer, checked out on my Windows computer with proper Windows CRLF.
The biggest problem that this case is quite spontaneous. I repeat the sequence couple times, only first run produced the result.

I'll try to reproduce the issue more times for cases like computer reboot, etc...

MS Visual Studio Professional  2012 + SP5
Visual Studio Tools for Git version 1.0.1.0

1) Freshly checked out project has no changes at all. Checked by "git status"
2) Open project by Visual Studio, got message "Source Control - Git\n\nThe current solution has projects that are located outside the solution folder..." and have .gitattribute created.
3) "git status" immediately shows two files as changed
4) rename ".gitattribute" to "_._gitattribute"
5) "git status" shows no files as changed
4) rename "_._gitattribute" back to  ".gitattribute"
6) "git status" shows no files as changed
7) Close project without saving solution, kill ".gitattribute"
8) "git status" shows no files as changed
9) Open project by Visual Studio, got message "Source Control - Git..." again and have .gitattribute created again.
10) "git status" shows no files as changed
11) Checked out the same project again to separate folder
12) "git status" shows no files as changed
13) Copy ".gitattribute" from the former one
12) "git status" shows no files as changed
13) Open project by Visual Studio, got message "Source Control - Git..." again and have .gitattribute created again.
14) "git status" shows no files as changed

**Comment by tboegi** [comment]
@mikhailmaximov 
This comes from the Git plugin from VS, right ?
This is based on libgit2, so you may want to report it there.

Beside that, you may want to contact the vendor of VS, why they create a .gitattributes file ?
Besides that, everybody is welcome to put up a public repo, so that we can reproce it.

And beside that, did anybody ever try to use the .gitattributes file, 
and normalize the repo as described here:
https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html

**Comment by PhilipOakley** [comment]
Isn't this a case of the repo already being normalised but that at start-up the VS viewpoint is 'wrong'.

What's the config settings for CRLF / EOL's?

Philip
  From: tboegi 


  @mikhailmaximov 
  This comes from the Git plugin from VS, right ?
  This is based on libgit2, so you may want to report it there.

  Beside that, you may want to contact the vendor of VS, why they create a .gitattributes file ?
  Besides that, everybody is welcome to put up a public repo, so that we can reproce it.

  And beside that, did anybody ever try to use the .gitattributes file, 
  and normalize the repo as described here:
  https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html

**Comment by ben-page** [comment]
mikhailmaximov's issue is NOT the issue I'm having. I've been waiting until it happened again, so I could provide more information.  Again, I have a repository that I can't pull. reset and checkout don't resolve the problem.

**Reset:**
```
c:\path>git status
On branch master
Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   XXXXXXXXXXXXXX

no changes added to commit (use "git add" and/or "git commit -a")

C:\path>rm .git\index

C:\path>git reset --hard
HEAD is now at a270665 minor cleanup for publish

C:\path>git pull
Updating a270665..2d7eebe
error: Your local changes to the following files would be overwritten by merge:
        XXXXXXXXXXXXXX
Please, commit your changes or stash them before you can merge.
Aborting
```

**Checkout:**
```
C:\path>git checkout master --force
Already on 'master'
Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

C:\path>git pull
Updating a270665..2d7eebe
error: Your local changes to the following files would be overwritten by merge:
        XXXXXXXXXXXXXX
Please, commit your changes or stash them before you can merge.
Aborting
```
**Checkout File:**
```
C:\path>git checkout -- XXXXXXXXXXXXXX

C:\path>git status
On branch master
Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   XXXXXXXXXXXXXX

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by ben-page** [comment]
I even tried deleting all files, deleting the index, git reset --hard, and git pull still fails.

**Comment by dscho** [comment]
@ben-page what does `git diff --raw` say?

**Comment by Dirk1966** [comment]
Such stuff can happen when you have a git repository for a mixed Windows/Unix environment.
I also saw such problems when users mixed upper/lower case of file names (a rename, ...).
In these cases git for Windows has no real chance.

**Comment by dscho** [comment]
I had a similar issue happening to me when the file in question was still opened in an editor. The output of `git diff --raw` should help diagnose this better.

**Comment by ben-page** [comment]
```
C:\path>git diff --raw
100644 100644 81b8bc5... 0000000... M  XXXXXXXXXXXXXX
```

**Comment by ben-page** [comment]
I agree that it's likely a line ending issue, but autocrlf is true and I verified the committed file has Unix line endings. Locally, diff shows no difference including line endings. But git diff says everything line was deleted and every line was added.

**Comment by dscho** [comment]
Yes, the index says that the file was deleted. Which makes me suspect that the `reset --hard` complained about the file, too, but who reads those pesky error messages, anyway.

Note: I am also vaguely aware that similar issues can occur with clean/smudge filters, such as are used by Git LFS. However, I feel that the information I read here is too scarce for me to help any further, with no indication of improving ("Repo is behind the remote."? Is this supposed to be a diligently crafted MCVE?).

**Comment by ben-page** [comment]
@dscho, `reset --hard` did not provide any error messages. I provided the entire console output. The only change I made is censoring the file names (this is the policy of my employer).

I completely followed your issue template. And I provide every relevant piece of information that I think of. I think that I've provided a lot of information (complete console output, all of relevant configuration, multiple attempts to resolve the issue). And I didn't just say "Repo is behind the remote." That was the first line in nearly 60 lines of console output and explanation.

Clearly this isn't enough, but simply tell saying the info provided isn't unclear is very unhelpful. I'm not the git expert. You are. What else would you like to know?

**Comment by ben-page** [comment]
A MCVE is impossible at this time. I can't create a new clean repo and cause it to enter this state, because I don't understand cause of the problem. I'm asking for help to figure that out., then I will happily provide a MCVE.

**Comment by dscho** [comment]
> A MCVE is impossible at this time

@ben-page you can always start from the existing repository, make a new orphan branch, then `git checkout @{-1} -- .` to add the entire tree of the previous branch, then remove all non-problematic files, then replace the contents by an empty string, then rename the file to an innocuous name, and commit & test where things break along the way. If the problem persists until the end, you have a repository you can safely share, and which would then constitute a Minimal, Verifiable & Complete Example. So it is everything except impossible.

**Comment by tajmone** [comment]
I'm experiencing the same problem with git version `2.31.1.windows.1`, but in my case I'm sure the problem is not due to line endings but to file permission. I have set to executable a Bash script on `master` branch, and now I can't checkout to my dev branch because of that script (which in the dev branch is still without the executable permission).

**Comment by tajmone** [comment]
I actually managed to work around the problem by setting again permissions on the script, so it would now show up as a changed file, which allowed me to stash it and then checkout.

I hope this might help to further isolate the problem or work around it when some operations are blocked.
