### ISSUE TITLE
Cannot add file with trailing space in name

### ISSUE THREAD

**Issue by max630** [git-for-windows/git#699]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

Portable Git for Windows 2.7.3 32-bit (from https://github.com/git-for-windows/git/releases/download/v2.7.3.windows.1/PortableGit-2.7.3-32-bit.7z.exe )

```
$ git --version
git version 2.7.3.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 7 home basic service pack 1

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Just unzip and start git-bash.exe

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing I think worth attention

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

the "git-bash.exe", as it starts by default (with mintty)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ mkdir /tmp/repo
$ cd /tmp/repo
$ git init
$ touch "file "
$ git add .
```
 - What did you expect to occur after running these commands?

The file "file " is added successfully. I can see it by ls for example, so msys2 utilities work normally with it:
```
$ ls -l file*|cat -E
-rw-r--r-- 1 user_2 197121 0 апр 29 12:05 file $
```

 - What actually happened instead?

```
$ git add .
fatal: unable to stat 'file ': No such file or directory
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by dscho** [comment]
File names with a trailing space are not even allowed file names on NTFS, are they?

**Comment by max630** [comment]
It's hard to find an authoritative reference, but at least [this page](https://support.microsoft.com/en-us/kb/303079) claims that "Directories or files that contain leading or trailing spaces are perfectly legal from an NTFS file system perspective".

I would expect them to be as legal as long paths.

**Comment by max630** [comment]
Actually it's very funny nowadays in msys2: https://github.com/Alexpux/Cygwin/commit/8802178fddfd280 So you can create file with, for example, newlines in name.

But the trailing space seems to be native. And I can remove it with `del "\\?.....\file "` from cmd.exe

**Comment by dscho** [comment]
If you want to use MSYS2, there is no problem. Git for Windows tries to *not* use the MSYS2 runtime whenever possible, to enhance performance. Therefore the link you provided does not help Git.

> But the trailing space seems to be native. And I can remove the file with del "\\?.....\file " from cmd.exe, for example.

Yes, you have to use the `\\?` workaround to access that file. That is a strong indicator that you are running into issues with this file name.

**Comment by dscho** [comment]
> It's hard to find an authoritative reference, but at least [this page](https://support.microsoft.com/en-us/kb/303079) claims that "Directories or files that contain leading or trailing spaces are perfectly legal from an NTFS file system perspective".

You know, selective quoting can be very misleading. Very, very misleading. Very, very, *very* misleading, e.g. if you choose to stop quoting just before...

> `but are not legal from a Win32 subsystem point of view`

So there you have it. Directories or files that contain leading or trailing spaces are perfectly legal from an NTFS file system perspective but are not legal from a Win32 subsystem point of view.

Should you choose to work on support for such files, I am definitely willing to review and accept a Pull Request. Before then, I will close this ticket, though.

**Comment by max630** [comment]
You asked about NTFS support, I was commenting that. For Win32 they are obviously not allowed, and neither are long paths.

Well anyway, thanks for checking. It does not really bother me, just hit while running around some tests.
