### ISSUE TITLE
The installer's Windows Explorer integration is not works

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#70]
either disable it or enable it, for enable it, we need
Git\git-cheetah\git_shell_ext64.dll
Git\git-cheetah\git_shell_ext.dll.new

**Comment by dscho** [comment]
> Windows Explorer integration is not works

This leaves a lot of room for misinterpretation. Please clarify, i.e. describe *exactly* what steps you performed, *precisely* what you expected to see, and *accurately* what you saw instead.

Without a thorough description of what you think is a bug, and how to reproduce the issue, it is simply impossible to resolve anything.

**Comment by dscho** [comment]
> describe exactly what steps you performed

For inspiration how to improve this bug report to a point where it can be addressed, have a look at this page: http://mattgemmell.com/what-have-you-tried/
