### ISSUE TITLE
Path conversion in git bash

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#702]
I'm running git version 2.7.4. I run the following command:

    $ adb push "C:/System/settings" "/data/settings"

For some reason, the terminal/shell is converting "/data/settings" to "C:/Git/data/settings". I have git installed at "C:/Git".

I understand in most cases, this conversion makes sense. However in this context, "/data/settings" is a path on a REMOTE device, not the current filesystem. Is there a way to tell it not to convert the path?

**Comment by davidovich** [comment]
Double the slash on the path to escape msys path conversion:

    adb push "C:/System/settings" "//data/settings"

**Comment by dscho** [comment]
Please use the bug tracker only for bugs, not for questions. See https://git-scm.com/community for resources how to obtain help with using Git for Windows.

**Comment by rcdailey** [comment]
What about questions specific to the Windows environment, like this one?
The official GIT mailing list is pretty baron even for straight GIT
questions. Historically they won't help with these kinds of questions.
