### ISSUE TITLE
Problem with index.lock file

### ISSUE THREAD

**Issue by Cunhazera** [git-for-windows/git#703]
Everytime I kill a proccess at my bash console I have to delete the index.lock file.

Full message:
```
If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

**Comment by dscho** [comment]
Could you test this after replacing the `msys-2.0.dll` file with the one from http://repo.msys2.org/msys/x86_64/msys2-runtime-2.5.0.16933.bc14e45-1-x86_64.pkg.tar.xz?

**Comment by Cunhazera** [comment]
In which dir is the `msys-2.0.dll` file ?

**Comment by dscho** [comment]
> In which dir is the msys-2.0.dll file ?

`<GIT>\usr\bin`

**Comment by Cunhazera** [comment]
I forced the error and it still happens

**Comment by dscho** [comment]
> I forced the error and it still happens

Do you mean with the `msys-2.0.dll` file from the indicated archive? Please talk to me.

**Comment by Cunhazera** [comment]
Correct.

**Comment by Cunhazera** [comment]
For example

![checkout](https://cloud.githubusercontent.com/assets/8171351/14150375/1b6839c2-f67f-11e5-8b6f-2e6ef53e005d.png)

**Comment by Cunhazera** [comment]
I can `git status` and `diff`, but I can't `checkout` any file.

**Comment by dscho** [comment]
How do you kill the processes?

**Comment by Cunhazera** [comment]
Ctrl + C

Let me explain this error: I tryed to `git checkout` a jar that was running at my server, but it sent me a message saying that I could not `checkout` the file, because it was running. Ok, no problems.
But when I killed the process git didn't let me checkout anything anymore unless I delete the index.lock file.

**Comment by Cunhazera** [comment]
OBS: I can not use that dll that you sent me, it generates problem to find the ssh path when I pull something.

**Comment by dscho** [comment]
> OBS: I can not use that dll that you sent me, it generates problem to find the ssh path when I pull something.

Why make it sooooo hard for me? Why not *paste* the error message? This description tells me nothing.

**Comment by Cunhazera** [comment]
```
Could not create directory '/home/myuser/.ssh'.
The authenticity of host 'myrepo (ip)' can't be established.
ECDSA key fingerprint is...
Are you sure you want to continue connecting (yes/no)? fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Cunhazera** [comment]
Sorry :)

**Comment by dscho** [comment]
Are you sure that you only run a `git status` or `git log` when you get that error message?

Seriously, this entire ticket gets more and more, not less, confusing. Very random, like, and pretty much everything you say is just one or two words, expecting me to read your mind. I am crap at reading minds, and frankly, this game gets a little old.

**Comment by Cunhazera** [comment]
I agree with you.
Well, Im going to close this issue, this is not a big trouble.
Thank's for trying help, see you.
