### ISSUE TITLE
Add unicode to MINGW64 when using cmd.exe

### ISSUE THREAD

**Issue by drozzy** [git-for-windows/git#705]
When I choose cmd.exe as my shell during install process - my system does not support unicode.
Choosing the other option - I get no interaction in my repl interpretations (i.e. python, erl etc).

This is like being between scylla and charybdis!

**Comment by dscho** [comment]
> When I choose cmd.exe as my shell during install process - my system does not support unicode.

Care to elaborate?

> Choosing the other option - I get no interaction in my repl interpretations (i.e. python, erl etc).

The [release notes say this](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

**Comment by dscho** [comment]
BTW please take care to fill out the issue reporting template next time. It really helps you craft better bug reports.

**Comment by drozzy** [comment]
Ok, I'll give winpty option a try.

Still - why doesn't it work by default? It used to work before.

**Comment by dscho** [comment]
@drozzy Why don't you answer all of my questions before asking new ones of your own?

To answer your question, still: we switched to a new terminal emulator (mintty) which does not handle all of the cases that the cmd window handles (hence the option to switch back to that terminal emulator).

But please note that your report is still lacking crucial information, and that I am still waiting for your clarification.

**Comment by drozzy** [comment]
Sorry, to answer your questions:

> Care to elaborate?

The terminal emulator does not handle unicode. It says so in the install wizard.
The other option - mintty, does not handle interactive shells (it also says so in the install wizard).

I just wanted to draw your attention that you have two options in the install, and both are lacking of some features.

**Comment by dscho** [comment]
> The terminal emulator does not handle unicode. It says so in the install wizard.

Have you actually validated that claim?

> The other option - mintty, does not handle interactive shells (it also says so in the install wizard).

And it says in the *known issues* how to work around it: `winpty`. [I pointed that out earlier](https://github.com/git-for-windows/git/issues/705#issuecomment-202396519). Have you tried that yet?

**Comment by drozzy** [comment]
Thanks, I'll try it out.

**Comment by drozzy** [comment]
Here is what I see in MINGW64.
![unicode](https://cloud.githubusercontent.com/assets/140710/17272934/063d274e-5672-11e6-901e-79a56d5198db.png)
