### ISSUE TITLE
32 bet not that good on compter so I do need help

### ISSUE THREAD

**Issue by giforum438** [git-for-windows/git#707]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 _TODO_

```
$ git --version
_TODO_
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 _TODO_

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 _TODO_

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 _TODO_

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 _TODO_

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
TODO
```
 - What did you expect to occur after running these commands?

 _TODO_

 - What actually happened instead?

 _TODO_

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 _TODO_

**Comment by shiftkey** [comment]
@giforum438 unless you can provide more information about the problem you are encountering - this is what the issue template is for - I can't really help you out here.

**Comment by giforum438** [comment]
Yes I need Help

**Comment by giforum438** [comment]
yes I do need some help not very good with computers my sons are always on so they're the ones that scatter messy things up for me all the time but whatever you can help you with it would be really appreciated

**Comment by giforum438** [comment]
okay had called Microsoft and they told me that they had a new virus downloaded they can download there I guess is Microsoft's new download and so I went ahead and purchased it from Microsoft one of their texts working on my computer and installed the new antivirus Microsoft and now having nothing but trouble I don't know what he did or what he didn't do I know he was on the computer doing some kinda scene that he had on the remote control and since that two days ago so I've been having trouble and have been fighting with this Microsoft is closed during the weekends so I can get any help until Monday so I started trying to see what what I can do myself
