### ISSUE TITLE
Git 2.8.0

### ISSUE THREAD

**Issue by laukstein** [git-for-windows/git#709]
Has been released Git 2.8.0 https://github.com/git/git/blob/v2.8.0/Documentation/RelNotes/2.8.0.txt
Missing Git 2.8.0 for Windows.

**Comment by nalla** [comment]
Please be paitient. Note that the release branch is rebased, tested and released by a single person. To quote a popular force sensetive fictive person: "You want the impossible".

Furthermore this is not an issue at all but a request. This is not the place for those.

**Comment by dscho** [comment]
@laukstein note that you can help next time.
