### ISSUE TITLE
doesn't support https connection cause lack of libgnutls-28.dll

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#71]
This because we didn't install libgnutls

**Comment by dscho** [comment]
Oh darn. And there I thought that cURL listing *both* OpenSSL and GNU TLS as dependencies was a mistake. This is bad, because that bloats our installer.

**Comment by lygstate** [comment]
Even I installed libgnutls, still crash git, don't know why.

**Comment by dscho** [comment]
Fixed in https://github.com/git-for-windows/build-extra/commit/e3cb2f2a4b4b9f24eac5a8199bf8adf6acf68735

**Comment by lygstate** [comment]
@dscho  Please do not fixes issue without verify it,
now it's lack of librtmp-1.dll

**Comment by dscho** [comment]
@lygstate you're right of course. But I had to write good commit messages instead of testing.

**Comment by dscho** [comment]
> Please do not fixes issue without verify it

BTW I really appreciate the irony of you saying that :smile:
