### ISSUE TITLE
when i git rebase -i error

### ISSUE THREAD

**Issue by yunyu2019** [git-for-windows/git#710]
### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

```
$ git --version
git for window 2.7.4  64-bit
```

 - Which version of Windows are you running? 32-bit or 64-bit?

```
Windows 7 x64
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
defaults
```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
no
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
 git Bash
```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git log
commit f2554fdc36e45b6dc95e60163964ffdc153b9777
Author: yunyu2019 <yunyu2010@yeah.net>
Date:   Fri Apr 1 10:30:58 2016 +0800

    git

commit 593154b42c33d8b34ef694bd4f9edfbfbd9e3325
Author: yunyu2019 <yunyu2010@yeah.net>
Date:   Fri Apr 1 10:30:35 2016 +0800

    456

commit 52069a73521918d80584f9d7aa4cea3c8b792679
Author: yunyu2019 <yunyu2010@yeah.net>
Date:   Fri Apr 1 10:30:17 2016 +0800

    123
$ git rebase -i HEAD^^
/mingw64/libexec/git-core/git-rebase--interactive: line 125: + : syntax error: operand expected (error token is "+ ")
```
 - What did you expect to occur after running these commands?

```
pick 593154b 456
pick f2554fd git                   i want modify f2554fd  pick to s

# Rebase 52069a7..f2554fd onto 52069a7 (2 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out

last when it's successful,the message is :
$ git rebase -i HEAD^^
[detached HEAD 6793cce] git
 Date: Fri Apr 1 10:30:35 2016 +0800
 1 file changed, 3 insertions(+), 1 deletion(-)
Successfully rebased and updated refs/heads/master.
```

 - What actually happened instead?
```
give me the error message:/mingw64/libexec/git-core/git-rebase--interactive: line 125: + : syntax error: operand expected (error token is "+ ")
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
```
 this is my local env,i can't provide a url.
```
###  more information
this issues  happend on git for window 2.7.4 64bit,then I upgrade to git for window 2.8.0 64bit,this issues is still.
when i build a new repository,then i merge some commit use git rebase -i ,this question is still.last i use git for windows 2.7.0 64bit to avoid this issues.

**Comment by yunyu2019** [comment]
I use git for windwo 2.7.0 is no this question

**Comment by yaras** [comment]
Unfortunately there is no way we can reproduce this issue, unless you provide more information.

Read please [Issue-reporting-guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) and provide more information. When creating new issue there should be an issue template, which tells what information is essential to begin diagnosing your issue, so please do not skip this step.

**Comment by yunyu2019** [comment]
1.when i use git rebase -i HEAD^^2，this issues is happend,this error message is:
`/mingw64/libexec/git-core/git-rebase--interactive: line 125: + : syntax error: operand expected (error token is "+ ")`.
2.this issues is happend on git for window 2.7.4 64bit,then I upgrade to git for window 2.8.0 64bit,this issues is still.
when i build a new repository,then i merge some commit use git rebase -i ,this question is still.

**Comment by yaras** [comment]
> i have modify my issue

Thanks. It gave us more insights, but I'm still not able to reproduce your problem.

I don't understand what you want to achieve. You say you want to merge commits, but on the other line you say you used `rebase`. Could you describe this in more detail?

Command `git rebase -i HEAD^^2` seems to be a bit complicated, so are you sure you're using right command to achieve your goal? If you want to seek more information about revision selection there is a chapter about [Ancestry-References](https://git-scm.com/book/tr/v2/Git-Tools-Revision-Selection#Ancestry-References) in manual.

**Comment by yunyu2019** [comment]
this is my  operating process：
```
$ git log
commit f2554fdc36e45b6dc95e60163964ffdc153b9777
Author: yunyu2019 <yunyu2010@yeah.net>
Date:   Fri Apr 1 10:30:58 2016 +0800

    git

commit 593154b42c33d8b34ef694bd4f9edfbfbd9e3325
Author: yunyu2019 <yunyu2010@yeah.net>
Date:   Fri Apr 1 10:30:35 2016 +0800

    456

commit 52069a73521918d80584f9d7aa4cea3c8b792679
Author: yunyu2019 <yunyu2010@yeah.net>
Date:   Fri Apr 1 10:30:17 2016 +0800

    123
git rebase -i HEAD^^
/mingw64/libexec/git-core/git-rebase--interactive: line 125: + : syntax error: operand expected (error token is "+ ")
```
why i use this command,i just want to merge the lastest two commits(git,456) to one commit,when i use the command git rebase -i HEAD^^ ,then the issue happend,i have show the error message,when i use git for windows 2.7.0 or linux os git  2.7.4,no the  problem,now do you understand me?my english is just so so.

**Comment by dscho** [comment]
```sh
$ git rebase -i HEAD^^2
fatal: Needed a single revision
invalid upstream HEAD^^2
```

Is there a chance to put your repository onto GitHub so I can try to reproduce the error here?

**Comment by yaras** [comment]
> i just want to merge the lastest two commits(git,456) to one commit

Now I see what you meant. In fact, what you want to do is *squashing commits* (not *merging commits*) and `rebase` is a proper tool to achieve this.

@dscho 

```
$ git rebase -i HEAD^^2
```

indeed seems to be invalid, but given in last @yunyu2019's comment `HEAD^^` seems to be valid and returns single revision.

@yunyu2019:

After you run `git rebase -i HEAD^^` appeared your editor or immediately after this command occurred this error?

**Comment by tanmatra** [comment]
Have the same problem here. Just rebasing two commits on old parent, with second commit "fixup" command.

Is it possible just fix line 125?

**Comment by dscho** [comment]
> Is it possible just fix line 125?

@tanmatra I see nothing wrong with line 125. The arithmetic operation's arguments should not be empty, but they are apparently empty.

So this is what you can do to help resolve this issue: Come up with a simple example where you can reliably reproduce the problem, then publish that repository, then mention the public URL of this repository here.

**Comment by tanmatra** [comment]
Hmmm... Probably it is a bug in bash from mingw

    $ cat "/etc/fstab" | wc -l
    6

    $ echo count = $(cat "/etc/fstab" | wc -l)
    count = 6

    $ count=$(cat "/etc/fstab" | wc -l)

    $ echo count=$count
    count=

**Comment by tanmatra** [comment]
If someone do not believe in it:

![git-bash-bug](https://cloud.githubusercontent.com/assets/708023/14251916/c1c32bda-fa8d-11e5-8900-51033de07aab.png)

I also have standalone MinGW environment, and tried same code there - it works as it should.

So, in line 123 of `git-rebase--interactive` variable `new_count` is probably set to empty string, and thus script is failing after it in line 125.

**Comment by dscho** [comment]
> Probably it is a bug in bash from mingw
> 
> $ cat "/etc/fstab" | wc -l
> 6
> 
> $ echo count = $(cat "/etc/fstab" | wc -l)
> count = 6
> 
> $ count=$(cat "/etc/fstab" | wc -l)
> 
> $ echo count=$count
> count=

@tanmatra that does not reproduce here:

```sh
$ count=$(cat "/etc/fstab" | wc -l)

$ echo count=$count
count=6
```

**Comment by yunyu2019** [comment]
i'm sorry,i have Three-day holiday, i start working today,Are you  sure  this is a bug now?I,m sure when i run this command then  this error occurred.

**Comment by dscho** [comment]
@yunyu2019 I believe that you see something going wrong. Now we need to make it so that I can reproduce the same problem here.

But I cannot. It simply does not fail for me in the way you described.

Which leads me to the conclusion that there is something different in your setup that you have not mentioned yet, and that is the reason for the difference in behavior.

**Comment by dscho** [comment]
> @tanmatra that does not reproduce here:
> 
> ```sh
> $ count=$(cat "/etc/fstab" | wc -l)
> 
> $ echo count=$count
> count=6
> ```

@tanmatra could you call `set -x` before repeating these two commands? Maybe that would shed more light into the matter.

**Comment by tanmatra** [comment]
After `set -x`

    Admin@Eldorado MINGW64 /bin
    $ count=$(cat "/etc/fstab" | wc -l)
    + count=
    ++ __git_ps1
    ++ local exit=127
    ++ local pcmode=no
    ++ local detached=no
    ++ local 'ps1pc_start=\u@\h:\w '
    ++ local 'ps1pc_end=\$ '
    ++ local 'printf_format= (%s)'
    ++ case "$#" in
    ++ printf_format=' (%s)'
    ++ local ps1_expanded=yes
    ++ '[' -z '' ']'
    ++ '[' -z '4.3.42(5)-release' ']'
    ++ shopt -q promptvars
    ++ local repo_info rev_parse_exit_code
    +++ git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree --short HEAD
    ++ repo_info=
    ++ rev_parse_exit_code=128
    ++ '[' -z '' ']'
    ++ return 127

    Admin@Eldorado MINGW64 /bin
    $ echo count=$count
    + echo count=
    count=

(similar lines skipped)

But following works:

    Admin@Eldorado MINGW64 /bin
    $ count=$(wc -l <"/etc/fstab")
    ++ wc -l
    + count=6

So, I guess, it's something wrong with pipe simbol (`|`)

**Comment by dscho** [comment]
> I guess, it's something wrong with pipe simbol (|)

@tanmatra could you try the same commands without `| wc -l` (yes, I know, the output would not be a count then, but I need to know *where* things go wrong)?

**Comment by tanmatra** [comment]
Admin@Eldorado MINGW64 /bin
    $ count=$(cat "/etc/fstab")
    ++ cat /etc/fstab
    + count='# For a description of the file format, see the Users Guide
    # http://cygwin.com/cygwin-ug-net/using.html#mount-table

    # DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path
    none / cygdrive binary,posix=0,noacl,user 0 0
    none /tmp usertemp binary,posix=0,noacl 0 0'
    ++ __git_ps1

...

    Admin@Eldorado MINGW64 /bin
    $ echo count=$count
    + echo count=# For a description of the file format, see the Users Guide '#' http://cygwin.com/cygwin-ug-net/using.html#
    mount-table '#' DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path none / cygdrive binary,posix=0,noacl,user 0
     0 none /tmp usertemp binary,posix=0,noacl 0 0
    count=# For a description of the file format, see the Users Guide # http://cygwin.com/cygwin-ug-net/using.html#mount-tab
    le # DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path none / cygdrive binary,posix=0,noacl,user 0 0 none /tm
    p usertemp binary,posix=0,noacl 0 0

**Comment by dscho** [comment]
Hmm. And if you add `| cat`, does it still work?

**Comment by dscho** [comment]
(Sorry, I am really stabbing in the dark here, and I really appreciate your help.)

**Comment by tanmatra** [comment]
Roman@Eldorado MINGW64 /
    $ count=$(cat /etc/fstab | cat); echo count=$count
    count=

Maybe git shipped with some buggy bash version?
I have separate mingw installation, and there it all works fine.

**Comment by dscho** [comment]
> Maybe git shipped with some buggy bash version?

Why is it working for me, then? :-(

Next attempt to bring light into this issue: would you please run [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/bb896645) while executing this statement? Hopefully the log will contain something interesting that makes us understand what's going wrong.

**Comment by dscho** [comment]
ping

**Comment by tanmatra** [comment]
Thanks to info in #704, I added `bash.exe` to MacType utility exclusion list, now all is good.

**Comment by whoisj** [comment]
> Thanks to info in #704, I added bash.exe to MacType utility exclusion list, now all is good.

Great! :tada:

**Comment by dscho** [comment]
@tanmatra are you sure snowie2000/mactype is functional? It looks to me as if there is no code, no downloads, only a wiki whose download link redirects to spam.

**Comment by tanmatra** [comment]
@dscho It certainly not in good state, though looks like repo belongs to original author. You can try to find valid download links in issues, for example https://github.com/snowie2000/mactype/issues/136 or https://github.com/snowie2000/mactype/issues/137
