### ISSUE TITLE
Blank VIM window from Windows Command Prompt

### ISSUE THREAD

**Issue by TaleTN** [git-for-windows/git#711]
After updating to v2.8.0 64-bit (git version 2.8.0.windows.1) VIM doesn't seem to work anymore from the Windows Command Prompt. If I e.g. try to edit a commit message I just get a blank (black) terminal window. Pressing Esc a couple of times seems to make it display a single line at the bottom of the window saying something like:

"C:/foo/.git/COMMIT_EDITGMSG" [converted][unix] 14L, 280C

Sometimes (I am not sure how/why) the VIM commit editor window does appear, but without the usual syntax highlighting, and it doesn't seem to respond to any of the usual keyboard commands.

Note that from the Git Bash terminal everything seems to work fine. Rolling back to Git v2.7.4 also seems to fix the issue, but if I then reinstall v2.8.0 the issue returns.

I am running Win10 Pro x64. I haven't installed any additional components, I use Git from the Windows Command Prompt, for Git Bash I use MinTTY, and I haven't enabled file system caching nor Git Credential Manager.

**Comment by nguymin4** [comment]
@TaleTN Same issue on Window 10 x64.

I found out that, vim run smoothly when starting it with git-bash.exe. But with bash.exe, it starts really slowly and usually breaks.

**Comment by dscho** [comment]
Could you test whether this problem occurs also with [MSYS2](https://msys2.github.io/)?

**Comment by TaleTN** [comment]
Sure. Well, at least I can try... I have just installed msys2-i686-20160205.exe, and then reinstalled Git v2.8.0. Basically this seems to work i.e. I see a commit message with correct syntax highighting, but I can't save my message or quit VIM (the Insert key doesn't seem to work, :x doesn't seem to work, etc.). But I also get this with Git v2.7.4 in the MSYS2 Shell, so I guess I simply don't know how VIM works under MSYS2.

**Comment by chriscollinsboxuk** [comment]
I've just updated to 2.8 and I'm seeing the same issue.

I see a blank window when running `git commit` from a:

cmd prompt
cmd prompt inside ConEmu
git bash prompt inside ConEmu

I see the VIM interface as normal when starting Git bash from the start menu.

**Comment by lennylxx** [comment]
+1, using Windows 10 64 bit, version 1511, build 10586.164.
I replaced the vim binaries of older version, but it's doesn't work.
Downgraded to 2.7.4.

**Comment by dscho** [comment]
> Sure. Well, at least I can try... I have just installed msys2-i686-20160205.exe, and then reinstalled Git v2.8.0.

@TaleTN well, what I meant is: does `vim` work *in* MSYS2. I.e. when you installed MSYS2 and ran `pacman -Syu vim` and then ran `C:\msys64\usr\bin\bash.exe -l -i`, does `vim` *still* freeze? (Of course I could test this myself, but my plate is real full...)

**Comment by TaleTN** [comment]
Oh I see... I have just reinstalled MSYS2 (64-bit this time), and then did as you said, and I think it works as expected (i.e. I see a text file, and I can exit using :x, but I can't seem to switch to insert mode; PEBKAC I guess).

**Comment by dscho** [comment]
@TaleTN okay, what if you replace `usr\bin\msys-2.0.dll` in Git for Windows with MSYS2's version? Does it fix the problem?

**Comment by TaleTN** [comment]
@dscho No, it does not.

**Comment by koraktor** [comment]
I’m having the same problem on Windows 7 (64 bit) as well since upgrading to 2.8.0.windows.1.
I’m usually using it in combination with ConEmu and Bash, but the problem is also occurring in cmd.exe.
The only option that worked for me is using the plain `git-bash.exe`. The only difference I can tell is that it’s not sourcing `.profile` et al. Disabling those configs for my normal setup does not work, though.

According to [this Git mailing list posting](http://permalink.gmane.org/gmane.comp.version-control.git/290357) the problem seems to be fixed when using a default `vim.exe` from vim.org. I didn’t try that, yet.

**Comment by csmager** [comment]
I'm also having the same issue (Windows 10 x64, Git for Windows 2.8.0).  

I can confirm that overwriting `vim.exe` in `Program Files\Git\usr\bin` with the one included in the latest vim 7.4 package as suggested in the message linked to by @koraktor does resolve the problem.

I also noticed in my trials and error that removing `set nocompatible` from `vimrc` in `Program Files\Git\etc` does allow it to start and behave (reasonably) normally.

**Comment by dscho** [comment]
> I also noticed in my trials and error that removing set nocompatible from vimrc in Program Files\Git\etc does allow it to start and behave (reasonably) normally.

Thanks for this hint. Unfortunately, it does not fix it in my case...

**Comment by dscho** [comment]
So far, I only found that recompiling vim does not change a thing (not very surprising, given that the vim of Git for Windows v2.7.4 still worked, and it is exactly the same vim version as v2.8.0 ships).

However, replacing `msys-2.0.dll` with the version from 2.7.4 *does* fix the problem.

**Comment by jfcherng** [comment]
Sadly, replacing `msys-2.0.dll` from 2.7.4 gives me a start-able vim but not a usable vim.

**Comment by dscho** [comment]
@jfcherng Replacing `msys-2.0.dll` breaks many more things than just *some aspects* of `vim.exe` (and for future record, your statement is awfully vague, you might want to step up the precision and detail in future comments). For example, `ls.exe` exits with exit code 127, indicating a DLL problem (indeed, a symbol expected by `ls.exe` is not found in that version). The point of my remark was to indicate that the problem was not introduced by `vim`, but by an upgrade in the `msys2-runtime`. And while we are speaking, I am bisecting the issue to get closer to the root cause. I am keeping you updated as a matter of courtesy.

**Comment by holodoc** [comment]
Windows 8.1 x64. Git for Windows 2.8.0 breaks Vim (7.4.168) when used with cmder (ConEmu) but it does work fine with Mintty. Running vim just opens a blank screen initially and it takes some time and a couple of keypresses for vim to actually appear. Exiting is however impossible.

**Comment by dscho** [comment]
> Git for Windows 2.8.0 breaks Vim (7.4.168)

Did you mean 7.4.1*4*68?

**Comment by holodoc** [comment]
> Did you mean 7.4.1468?
Yes, my bad. A typo. It's vim 7.4.1468.

**Comment by dscho** [comment]
Progress: turns out that https://github.com/git-for-windows/msys2-runtime/commit/734656818aa571c8f0d8d3e73e391c8ae26d79f1 might be the problematic change.

**Comment by dscho** [comment]
Indeed, the culprit is https://github.com/git-for-windows/msys2-runtime/commit/734656818aa571c8f0d8d3e73e391c8ae26d79f1 and reverting it fixes the issue. Will continue tomorrow.

**Comment by TaleTN** [comment]
@dscho That sounds very promising. Thanks!

**Comment by dscho** [comment]
Uploaded into the Pacman repository of the Git for Windows SDK.

You can fix it locally by downloading https://dl.bintray.com/git-for-windows/pacman/x86_64/:msys2-runtime-2.4.1.34115.1ca92fa-1-x86_64.pkg.tar.xz and extracting `usr\bin\msys-2.0.dll` into your existing Git for Windows.

**Comment by mmalolepszy** [comment]
The link above doesn't work. This one should: https://dl.bintray.com/git-for-windows/pacman/x86_64/msys2-runtime-2.4.1.34115.1ca92fa-1-x86_64.pkg.tar.xz

**Comment by moosekaka** [comment]
I can confirm that it fixes the issue after running pacman -Syuu. Thank you!

**Comment by seanzer** [comment]
Is this fix released in git 2.13.0? I'm still having problems

**Comment by TaleTN** [comment]
I am on 2.13.0 also, and everything seems fine here. BTW, I think this specific issue was fixed in 2.8.1, and I haven't seen the issue again since, so maybe what you are seeing is another issue?
