### ISSUE TITLE
Show git help in console

### ISSUE THREAD

**Issue by Zitrax** [git-for-windows/git#712]
Any plans to support this ? I could not find an existing request for this as mentioned below.

 - [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

However [SO](http://stackoverflow.com/a/5517857/11722) refers to an old issue nr 187, but I don't know what happened to it. Even tried to check web.archive.org for that.

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

2.7.2 64-bit.

```
$ git --version
2.7.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

other

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git help log
```
 - What did you expect to occur after running these commands?

Help in console

 - What actually happened instead?

Help in browser

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No

**Comment by kostix** [comment]
Looks like #696 to me.

**Comment by dscho** [comment]
> Looks like #696 to me.

Concur.
