### ISSUE TITLE
Git Bash seems to have problems with input values from external applications

### ISSUE THREAD

**Issue by mwiora** [git-for-windows/git#713]
### Setup
$ git --version
git version 2.8.0.windows.1
64 bit variant running on Windows 10 (Build 10586)
64 bit variant running on Windows 7
64 bit variant running on Windows Server 2012 R2

Installed with default values beside of using plink (tested with 0.66 and 0.67 beta) instead of openssh, 
tested on two separate environments

### Details

Testing with "Git Bash" (works fine with cmd or cygwin)
Running "git clone git@github.com:mwiora/namebench.git" I'm asked for if I want to accept the provided ssh-key.

![git_issue](https://cloud.githubusercontent.com/assets/2744285/14167754/cb97b234-f71d-11e5-85cf-6722c55d1883.png)

Expecting that the application takes my answer it does nothing.

The application seems not to accept the keys, but after pressing ctrl+c to abort the operation the system is going on with the inputs.

![git_further](https://cloud.githubusercontent.com/assets/2744285/14167833/37abf5d4-f71e-11e5-87ec-f768af5e9932.png)

P.S.: 

I've tested a read-script:
```
#!/bin/bash
echo "Enter value: "
read test
echo $test
```
Works fine.

I had a similar issue when writing a bash-python compination - the python was expecting an input, but the git bash covered the Read-Out as well as was not accepting the read. If needed I can provide a sample script.

Workaround:

connect to the git destination on SSH using putty - accept it's ssh-host-key (this procedure stores the fingerprint information in your registry) and from now the git bash will continue to clone without asking user for inputs.

**Comment by dscho** [comment]
This is exactly the problem that made us discourage the use of PLink. In fact, the option to use PLink is only offered if you have saved connections (and for saved connections, everything is fine). It is mentioned in the [known issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues):

* If configured to use Plink, you will have to connect with [putty](http://www.chiark.greenend.org.uk/~sgtatham/putty/) first and accept the host key.

I will close this as a wontfix. If you have great ideas how to fix it, I am all ears, though, and if we ever find a way to fix this for real, we can easily reopen this ticket.
