### ISSUE TITLE
Git2.8.0 install error :unable to run post-install script

### ISSUE THREAD

**Issue by iwits** [git-for-windows/git#714]
While installing Git 2.8.0, an error was encountered .
line 1654 :Unable to run post-install script.

I don't know what it‘s mean,and how to deal with it.
I would appreciate it if you help me.
![default](https://cloud.githubusercontent.com/assets/15440081/14214650/ca078fc6-f870-11e5-9a06-5025cc6e6cf3.JPG)

**Comment by shiftkey** [comment]
@iwits which version of Windows are you running? 32-bit or 64-bit?

**Comment by dscho** [comment]
@iwits it would have been better to fill out the issue reporting template instead of deleting it.

Be that as may, you can ask the installer to write a log using the `/LOG=...` option.

**Comment by iwits** [comment]
I work in windows7 64bits
2016年4月2日 05:07，"Brendan Forster" <notifications@github.com>写道：

**Comment by dscho** [comment]
@iwits what about the `/LOG=` option? What about the missing information as per the issue reporting template?

**Comment by dscho** [comment]
Closing due to stalled conversation.
