### ISSUE TITLE
Add arc command to git for windows please

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#715]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

I am running git for windows version 2.8 64-bit

```
$ git --version
git version 2.8.0.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 I chose the default.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
None except from arc is not supported
```
 - What did you expect to occur after running these commands?

 That arc should work

 - What actually happened instead?

 The command is not supported

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 No the problem happends with all because it is not supported.

Hi please could we add support for arc

https://secure.phabricator.com/book/phabricator/article/arcanist/

https://secure.phabricator.com/book/phabricator/article/arcanist_windows/

**Comment by rimrul** [comment]
>Hi please could we add support for arc
https://secure.phabricator.com/book/phabricator/article/arcanist/
https://secure.phabricator.com/book/phabricator/article/arcanist_windows/

That second article seems to contain all information you need to get your arcanist running from Git Bash. It even says this at the top:

>Arcanist runs on Windows, either in cmd.exe or the Git Bash environments. However, it will take a little effort to get working. This document explains what you need to do in order to get it running.
**NOTE:** Windows support is relatively new and incomplete, file bugs when you run into issues.

Git for Windows usually only ships unix commands that fit into at least one of these four categories

* It's a Git command like `git bisect` or `git add`

* It's a command required to run parts of Git for Windows like `perl` or `bash`

* It's included for legacy reasons

* It's a part of something from the two categories above like `ls`

`arc` fits none of those categories. If you don't have a good reason `arc` would be usefull for git related tasks for a substantial amount of users I'm afraid this will be closed as "wontfix", "question" and/or "invalid".

**Comment by dscho** [comment]
@paladox you have been around enough to expect the following answer:

Git for Windows' purpose is not to ship all kinds of random software some users may want to use. Its purpose is to make Git work on Windows, and work well.

As @rimrul pointed out, given this purpose, `arc` is in no way required or even desirable.

Having said that, I understand that a flexible package management/build system that also includes a package for `arc` is what you really crave.

This system exists, and Git for Windows makes excellent use of it: [MSYS2](https://msys.github.io/).

Like Git for Windows, MSYS2 is Open Source, meaning that it empowers its users to use and enhance the software in every way they see fit.

And now comes the part that you might not like as much: with every freedom comes a responsibility. In this case, your responsibility is to put your own effort and your own ability behind fixing bugs you encounter, behind adding new features you desire. Of course you can always ask others to do your bidding, and that comes with its own set of consequences.

Should you choose to exercise your freedom to enhance MSYS2, here is the most important pointer:

- https://github.com/git-for-windows/git/wiki/Package-management

You will probably want to follow the example of `/usr/src/MSYS2-packages/zip/` (if that directory does not exist, you probably did not study the *Package management* wiki page enough).

**Comment by dscho** [comment]
@paladox BTW if you start working on this, feel free to open a Pull Request (even for a work in progress, e.g. to discuss and request help) at https://github.com/git-for-windows/MSYS2-packages

**Comment by paladox** [comment]
@dscho ok, doing it here https://github.com/git-for-windows/MSYS2-packages/pull/17 would you be able to review it, since this is my first time doing it and I'm not sure what I should do.
