### ISSUE TITLE
Vim integration broke with 2.8 release

### ISSUE THREAD

**Issue by beautifulcoder** [git-for-windows/git#716]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

PortableGit-2.8.0-64-bit.7z.exe

```
$ git --version
git version 2.8.0.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Didn't go through the installer

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
vim
```
 - What did you expect to occur after running these commands?

The `vim` command should continue to work.

 - What actually happened instead?

Vim no longer works as expected in CMD. It lags and sometimes doesn't even come up. I will be sticking to the outdated version of git until this is fixed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I think this is related to a build issue. Please help.

**Comment by TaleTN** [comment]
See https://github.com/git-for-windows/git/issues/711

**Comment by shiftkey** [comment]
Closing this in favour of the investigation already underway in #711
