### ISSUE TITLE
Git not installing

### ISSUE THREAD

**Issue by thereefus** [git-for-windows/git#717]
When I loaded up the launcher I download it and as soon as it was done at the very last time it froze but still said it was downloading I left it over night still not done. No it's not my computer speed.

**Comment by dscho** [comment]
The description is not detailed enough to enable me to help.

**Comment by dscho** [comment]
@thereefus please do not just ignore the advice how to [report bugs](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines). Without a clearer presentation what this ticket is about, I will be forced to close it unaddressed.

**Comment by thereefus** [comment]
What did you not read what I said how is that not addressed?

**Comment by dscho** [comment]
> If you need anymore information ask.

I need more information?

Seriously, I have no clue what "loading up the launcher" means. Nor what you mean by "it froze but still said it was downloading". What was downloading what? Is there a screenshot of the freezing? Did you mean to refer to a webbrowser not finishing the download or what?

This is all very, very unclear.
