### ISSUE TITLE
Git Bash terminal not handling movement to beginning of line properly

### ISSUE THREAD

**Issue by moosekaka** [git-for-windows/git#719]
- [&#x2713;] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 
```
$ git --version
git version 2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?
     
    64bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

    I have observed problems using default Git for Windows installer and also Git SDK Windows    package.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

    I normally run Conemu but I observe this behavior also just using the Git Bash program.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Press Ctrl+A or Home when cursor at the end of a line.
```
 - What did you expect to occur after running these commands?

 Cursor  moves to beginning of line.

 - What actually happened instead?

    Cursor offset from beginning of line.
![qspejnwigs](https://cloud.githubusercontent.com/assets/4260594/14261793/2c1c4970-fa67-11e5-9e32-16e5fef1b650.gif)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 _TODO_

**Comment by moosekaka** [comment]
This might be possibly related to issue [#353](https://github.com/git-for-windows/git/issues/353), but in my case it is even simply, I just cannot get consistent movement behavior with Ctrl+A or Home. Also I cannot get reverse history search to cycle consistently using Ctrl+R because of the offset from beginning of the line issue.

**Comment by dscho** [comment]
> Any other interesting things about your environment that might be related
> to the issue you're seeing?

Well, you also have a custom prompt. That might mess things up a little...

**Comment by moosekaka** [comment]
Ahh, Ok, thanks for the hint, I was setting my colors using GREEN =$(tput setaf 2) for example, and it was somehow messing up PROMPT_COMMAND.... (I'm also using posh-git). Hardcoding the colors using the ANSI escape sequences fixed the problem.
