### ISSUE TITLE
doesn't support https connection

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#72]
Please verify the https can really getting clone or pulled,

**Comment by lygstate** [comment]
By using http://curl.haxx.se/gknw.net/7.40.0/dist-w64/curl-7.40.0-devel-mingw64.7z 
libcurl.dll to replace libcurl-4.dll in mingw64, the https connection works now,
and this version if very minimal. That's a advantage.

**Comment by dscho** [comment]
I do not really want to pull random binaries from all sorts of places. We use Pacman for a reason.

**Comment by lygstate** [comment]
@dscho how do I know which curl version currently using?

**Comment by lygstate** [comment]
```
$ curl https://github.com/git-for-windows/git/raw/0160e8e2a1c128153c7d1dc3df2050acbc96a6e6/compat/win32/git-wrapper.c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: C:/CI-Tools/vcs/Git-SDK/mingw64/ssl/certs/ca-bundle.crt
  CApath: none

```

So the curl doesn't work at all

**Comment by dscho** [comment]
@lygstate have you looked at the referenced file? I found that under certain (as yet unclear) circumstances, that `ca-bundle.crt` file is empty, but that reinstalling via `pacman -S mingw-w64-x86_64-ca-certificates` helps. See also https://github.com/git-for-windows/build-extra/commit/1047cf223553a14cac7cc1b9318e4356a61b252a.

**Comment by dscho** [comment]
> how do I know which curl version currently using?

```bash
curl --version
```

**Comment by lygstate** [comment]
@dscho Can you spend sometime to testing does mingw-git support for https connection, I am still failed, but the msys-git works fine.

**Comment by dscho** [comment]
> Can you spend sometime to testing

Sorry, no, I have spent all of the past three hours trying to address shortcomings in issue reports and commit messages. The tasks I actually had to take care of have waited patiently, but I have to address them now.

**Comment by dscho** [comment]
My, my, aren't you the lucky one. The crashes in HTTP/HTTPS/FTP were caused by enabling nedmalloc, [as predicted by @kblees](https://github.com/git-for-windows/git/pull/38#issuecomment-86219338). Dumb idiot me followed [the request to enable it](https://github.com/git-for-windows/git/pull/38#issuecomment-86219338) nevertheless.

**Comment by dscho** [comment]
@lygstate you should be able to test the fix yourself by pulling and rebuilding. The relevant commit is 5ccd51f85ea0e8ce3d77b0952f71fb6e50c63016

**Comment by lygstate** [comment]
Now it's fixed, I've test it.
