### ISSUE TITLE
Fix using windows path in git for windows

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#720]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

git for windows 2.8.1

git version 2.8.1.windows.1

```
$ git --version
git version 2.8.1.windows.1

```

 - Which version of Windows are you running? 32-bit or 64-bit?

 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 I choose the default

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Nope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Doing just for example c:\Users 
```
 - What did you expect to occur after running these commands?

I thought it would be able to search in that folder like if you were to do it from cmd.

 - What actually happened instead?

 I get this error

$ c:\users
bash: c:users: command not found

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happends to all repos.

Other details is

That slashes such as \ is not supported because bash is unix. But could there some how be supported please. so that doing something like you want to run from a bin. You can do /c/Users/ but in programes that we install and use in git some doin't work properly because they use the windows path not unix. In cmd it works because it uses the windows path.

I'm running windows 10.

**Comment by paladox** [comment]
In arc it doesn't work correctly with git because of this code.

  public function execPassthru($pattern /* , ... */) {
    $args = func_get_args();

    static $git = null;
    if ($git === null) {
      if (phutil_is_windows()) {
        // NOTE: On Windows, phutil_passthru() uses 'bypass_shell' because
        // everything goes to hell if we don't. We must provide an absolute
        // path to Git for this to work properly.
        $git = Filesystem::resolveBinary('git');
        $git = csprintf('%s', $git);
      } else {
        $git = 'git';
      }
    }

    $args[0] = $git.' '.$args[0];

    return call_user_func_array('phutil_passthru', $args);
  }

But changing

      if (phutil_is_windows()) {
        // NOTE: On Windows, phutil_passthru() uses 'bypass_shell' because
        // everything goes to hell if we don't. We must provide an absolute
        // path to Git for this to work properly.
        $git = Filesystem::resolveBinary('git');
        $git = csprintf('%s', $git);
      } else {
        $git = 'git';
      }

to

        $git = 'git';

Fixed it because git doesn't support windows path. Could there be a converter in git that can convert the windows path into Linux path please.

**Comment by dscho** [comment]
> git doesn't support windows path

That is incorrect. `git.exe` supports Windows paths.

The problem seems to be a misunderstanding how Bash works. In Bash, the backslash is an *escape* character and it expects forward slashes and POSIX paths instead.

> - What commands did you run to trigger this issue? If you can provide a Minimal, Complete, and Verifiable example this will help us understand the issue.
>
> ``` 
> Doing just for example c:\Users 
> ```
> 
> - What did you expect to occur after running these commands?
> 
> I thought it would be able to search in that folder like if you were to do it from cmd.
> 
> - What actually happened instead?
> 
> rI get this error
> 
> ```
> $ c:\users
> bash: c:users: command not found
> ```

When I do this in `cmd.exe`, it fails, too:

```cmd
C:\>c:\users
'c:\users' is not recognized as an internal or external command,
operable program or batch file.
```

> ```php
> $git = Filesystem::resolveBinary('git');
> ```

I am lost here. How do you call Arcanist? From within the Git for Windows SDK's Bash? Which PHP do you use, where does it come from, is it on the `PATH`? If so, `which git` should work and give you `/mingw64/bin/git.exe`, and if that works, so should PHP's `Filesystem::resolveBinary`. If it does not work, it needs to be fixed.

Regarding where PHP comes from, I noticed that there is no `php` package in http://repo.msys2.org/msys/x86_64/ and neither a `mingw-w64-x86_64-php` package in http://repo.msys2.org/mingw/x86_64/. So I believe you need to provide such a package first, before even trying to build an `arcanist` package.

**Comment by paladox** [comment]
Hi well I use php 7.0.4 but I also tried with php 5.6.

Also arcanist you doin't call from git but instead you add it to the path so when you call for example arc land it should work. But arc is based on git. So when you use arc in git for windows bash it works differently to then doing it through cmd.

**Comment by paladox** [comment]
https://secure.phabricator.com/book/phabricator/article/arcanist/

https://secure.phabricator.com/book/phabricator/article/arcanist_windows/

**Comment by dscho** [comment]
> I use php 7.0.4 but I also tried with php 5.6.

I really wanted to know from *where* you get those. The version numbers are quite uninteresting in this context...

> Also arcanist you doin't call from git but instead you add it to the path so when you call for example arc land it should work. But arc is based on git. So when you use arc in git for windows bash it works differently to then doing it through cmd.

I do not understand, sorry.

Are you saying that you call `arc land` in CMD and it does not find `git.exe`? I would understand that, if you have not chosen the appropriate option when installing Git for Windows (you would want to add `git` to the `PATH`).

However, when you call `Git Bash` and then add the directory which contains Arcanist to the `PATH`, it should work.

BTW just posting links without any explanation is not going to appeal to me: I have way too else much to do. If you want me to assist you, you will have to summarize and clarify what you do and what you want to do. I simply cannot afford the time to read up on PHP stuff that does not have any relation to Git at all.

**Comment by paladox** [comment]
Ok, sorry, Well arcanist you download a save it to any folder you also have to download libutil which is required but then you add arcanist bin to the system path meaning variables to be able to find arc and run it.

But in git for windows it fails with something to do with proc_open I doint know why but I found it to do with this code

  if (phutil_is_windows()) {
    // NOTE: On Windows, phutil_passthru() uses 'bypass_shell' because
    // everything goes to hell if we don't. We must provide an absolute
    // path to Git for this to work properly.
    $git = Filesystem::resolveBinary('git');
    $git = csprintf('%s', $git);
  } else {
    $git = 'git';
  }

Chaning to just

    $git = 'git';

fixed it.

arc land you can run it in git for windows but it seems to not work if I have 

  if (phutil_is_windows()) {
    // NOTE: On Windows, phutil_passthru() uses 'bypass_shell' because
    // everything goes to hell if we don't. We must provide an absolute
    // path to Git for this to work properly.
    $git = Filesystem::resolveBinary('git');
    $git = csprintf('%s', $git);
  } else {
    $git = 'git';
  }

but changing to
    $git = 'git';

fixed it.

Arc I'm not sure if it finds git with that code but it doesn't error out with any git errors just that the code above this comment looks like it trying to add the path to git so maybe it carn't find git or is looking in the wrong place.

**Comment by paladox** [comment]
Also the php I tried the official one on windows.php.net and also tried php from bitnami wamstack.

**Comment by dscho** [comment]
I am still unclear whether `git.exe` is in your `PATH` when you call that PHP script that then calls `Filesystem::resolveBinary`.

You could debug this issue yourself, though, by breaking it down: simply make a new script that only calls `Filesystem::resolveBinary` and then [debugging this](http://php.net/manual/en/debugger.php).

**Comment by paladox** [comment]
git is in my path.

But it is going for the cmd folder. Should it go for the bin folder.

**Comment by paladox** [comment]
Adding the bin folder still brings the error.

**Comment by paladox** [comment]
Oh wait, git for windows doesn't support the where command so doing where git wont work whereas it would on cmd.

  /**
   * Locates the full path that an executable binary (like `git` or `svn`) is at
   * the configured `$PATH`.
   *
   * @param   string  Binary name, like `'git'` or `'svn'`.
   * @return  string  The full binary path if it is present, or null.
   * @task    exec
   */
  public static function resolveBinary($binary) {
    if (phutil_is_windows()) {
      list($err, $stdout) = exec_manual('where %s', $binary);
      $stdout = phutil_split_lines($stdout);

      // If `where %s` could not find anything, check for relative binary
      if ($err) {
        $path = self::resolvePath($binary);
        if (self::pathExists($path)) {
          return $path;
        }
        return null;
      }
      $stdout = head($stdout);
    } else {
      list($err, $stdout) = exec_manual('which %s', $binary);
    }

    return $err === 0 ? trim($stdout) : null;
  }

See above for windows it does where git, which is not supported in git for windows so on Linux it does which git.

Could we add support for the where command please.

**Comment by paladox** [comment]
Maybe add something that converts where into which.

**Comment by dscho** [comment]
> But it is going for the cmd folder. Should it go for the bin folder.

No, the `cmd/` folder is correct. You do *not* want the `mingw64/bin/` folder in your `PATH`.

> Could we add support for the where command please.

The `where` command is supported by Windows, is it not? If you add Git's `cmd/` directory to your `PATH`, `where git.exe` should find it. If not, there is a bug somewhere (outside of Git).

**Comment by paladox** [comment]
@dscho but as I use git bash it wont find the where command even if your running git on windows because the command would not be in use on Linux.

**Comment by paladox** [comment]
where command does find git.exe in cmd but not in git for windows bash. I have to do which git to find it.

So doing 

$ where git
bash: where: command not found

in git for windows bash results in command not found where as doing it in cmd results in
c:\>where git
C:\Program Files\Git\cmd\git.exe

but doing which git works in git
$ which git
/mingw64/bin/git

but doesn't on cmd

c:\>which git
'which' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dscho** [comment]
> where command does find git.exe in cmd but not in git for windows bash. I have to do which git to find it.

But PHP does not use the Bash, does it? It should use `cmd` to call `where` because `where` is a `cmd` builtin.

**Comment by paladox** [comment]
@dscho no php does not use bash but you can execute scripts in php by using proc_open or exec. But arc uses the where command in windows to find git. 

I would presume cmd would not work in git for windows bash since bash is not windows.

**Comment by dscho** [comment]
> I would presume cmd would not work in git for windows bash since bash is not windows.

Uh, what? Git for Windows' Bash is a Windows executable. It runs on Windows. And you call PHP from it, at which point it should not at all matter how you called it. Unless there is a "feature" in PHP, that is.

> > where command does find git.exe in cmd but not in git for windows bash. I have to do which git to find it.
> 
> But PHP does not use the Bash, does it? It should use cmd to call where because where is a cmd builtin.

And indeed, `Filesystem::resolveBinary()` is defined here: https://github.com/wikimedia/phabricator-libphutil/blob/103dc7e39093a51a091189b43790771efd0f10e5/src/filesystem/Filesystem.php#L902-L929

It calls `exec_manual()` which is defined here: https://github.com/wikimedia/phabricator-libphutil/blob/103dc7e39093a51a091189b43790771efd0f10e5/src/future/exec/execx.php#L21-L38

That function instantiates `ExecFuture` via `newv()` which is defined here: https://github.com/wikimedia/phabricator-libphutil/blob/103dc7e39093a51a091189b43790771efd0f10e5/src/utils/utils.php#L625-L666

The `ExecFuture` class is defined here: https://github.com/wikimedia/phabricator-libphutil/blob/103dc7e39093a51a091189b43790771efd0f10e5/src/future/exec/ExecFuture.php

The `ExecFuture` is a `Future` and it is a bit convoluted how it does its job. Its [`resolve()` method](https://github.com/wikimedia/phabricator-libphutil/blob/103dc7e39093a51a091189b43790771efd0f10e5/src/future/Future.php#L26-L64) indirectly [calls `proc_open()`](https://github.com/wikimedia/phabricator-libphutil/blob/103dc7e39093a51a091189b43790771efd0f10e5/src/future/exec/ExecFuture.php#L646-L651).

Now, according to the [documentation of the `proc_open()` function](http://php.net/manual/en/function.proc-open.php) you have to pass `[ 'bypass_shell' => true ]` as `other_option` for `cmd.exe` to be bypassed.

Maybe that is broken? Or maybe the `PATH` is broken at that point, somehow?

You should be able to figure out whether Bash is called (incorrectly: on Windows, `proc_open()` should *always* call `cmd.exe` instead of `bash.exe` because `bash.exe` is not usually even available) or `cmd.exe` is called (correctly) by running [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/bb896645) while running the failing PHP script.

**Comment by dscho** [comment]
BTW it did cost me some time to follow the code through php.net/GitHub's search function, hence I wrote it up in as much detail so that you can perform similar analyses yourself in the future and do not need to rely on me to do it for you.

**Comment by paladox** [comment]
Ok thanks.

**Comment by paladox** [comment]
@dscho I had a look at this code

**Comment by paladox** [comment]
@dscho I had a look at 

    if (phutil_is_windows()) {
      // Without 'bypass_shell', things like launching vim don't work properly,
      // and we can't execute commands with spaces in them, and all commands
      // invoked from git bash fail horridly, and everything is a mess in
      // general.
      $options['bypass_shell'] = true;
    }
code and so I removed it to see if it would make a difference it does since it may be bypass_shell not working properly.

**Comment by paladox** [comment]
Using trace 

[2016-04-06 06:15:25] EXCEPTION: (Exception) Failed to passthru proc_open(): proc_open(): CreateProcess failed, error code - 87 at [<phutil>\src\future\exec\PhutilExecPassthru.php:101]
arcanist(), phutil()
  #0 PhutilExecPassthru::execute() called at [<phutil>\src\future\exec\execx.php:50]
  #1 phutil_passthru(string, string, string) called at [<arcanist>\src\repository\api\ArcanistGitAPI.php:46]
  #2 ArcanistGitAPI::execPassthru(string, string, string) called at [<arcanist>\src\land\ArcanistGitLandEngine.php:139]
  #3 ArcanistGitLandEngine::fetchTarget() called at [<arcanist>\src\land\ArcanistGitLandEngine.php:14]
  #4 ArcanistGitLandEngine::execute() called at [<arcanist>\src\workflow\ArcanistLandWorkflow.php:296]
  #5 ArcanistLandWorkflow::run() called at [<arcanist>\scripts\arcanist.php:392]

It fails with error 87 for proc_open.

**Comment by paladox** [comment]
Maybe this

process php

High Resolution Date & Time:	06/04/2016 14:21:01.3800585
Event Class:	Registry
Operation:	RegOpenKey
Result:	NAME NOT FOUND
Path:	HKLM\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION\Image File Execution Options\cmd.exe
TID:	6948
Duration:	0.0000177
Desired Access:	Query Value, Enumerate Sub Keys

**Comment by paladox** [comment]
Or this one

process php

High Resolution Date & Time:	06/04/2016 14:21:01.3724546
Event Class:	File System
Operation:	CreateFile
Result:	NAME NOT FOUND
Path:	C:\php\cmd.exe
TID:	6948
Duration:	0.0000815
Desired Access:	Read Attributes
Disposition:	Open
Options:	Open Reparse Point
Attributes:	n/a
ShareMode:	Read, Write, Delete
AllocationSize:	n/a

**Comment by paladox** [comment]
It seems that it looks for cmd.exe in php.

**Comment by paladox** [comment]
And here

High Resolution Date & Time:	06/04/2016 14:21:01.3728845
Event Class:	File System
Operation:	CreateFile
Result:	NAME NOT FOUND
Path:	C:\Users\patrick\differential-testing\cmd.exe
TID:	6948
Duration:	0.0001369
Desired Access:	Read Attributes
Disposition:	Open
Options:	Open Reparse Point
Attributes:	n/a
ShareMode:	Read, Write, Delete
AllocationSize:	n/a

**Comment by dscho** [comment]
> I had a look at
> 
> if (phutil_is_windows()) {
>   // Without 'bypass_shell', things like launching vim don't work properly,
>   // and we can't execute commands with spaces in them, and all commands
>   // invoked from git bash fail horridly, and everything is a mess in
>   // general.
>   $options['bypass_shell'] = true;
> }
> 
> code

Where is that code?

**Comment by paladox** [comment]
@dscho here https://github.com/wikimedia/phabricator-libphutil/blob/103dc7e39093a51a091189b43790771efd0f10e5/src/future/exec/PhutilExecPassthru.php#L84

**Comment by dscho** [comment]
If that is really hit by the `Filesystem::resolveBinary()` code path (which I am not at all certain that it is), then the `where` needs to be changed into a `cmd /c where`, I guess.

**Comment by paladox** [comment]
@dscho hi thanks for that but chaning to  cmd /c where still results in the proc_open error

**Comment by paladox** [comment]
cmd command in git bash doesn't work. Results in unkown command.

**Comment by paladox** [comment]
@dscho is there a way for me to detect if we are currently using git for windows.

So on git for windows open not just using git commands. So only code within this detection will work in git for windows not cmd even if you use git there.

**Comment by dscho** [comment]
> cmd command in git bash doesn't work.

It does work here, though!

```
me@work MINGW64 ~
$ cmd
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\johasc>
```

**Comment by paladox** [comment]
Oh doesn't for me. Do you have cmd.exe in your path.

**Comment by dscho** [comment]
> Oh doesn't for me. Do you have cmd.exe in your path.

Of course. It lives in `C:\Windows\system32\cmd.exe` for me, and `%SystemRoot%\system32` is part of the system `PATH` (which I did not change).

**Comment by paladox** [comment]
Oh ok. cmd doesn't work for me. Returns command cannot be found.

**Comment by paladox** [comment]
$ cmd
bash: cmd: command not found

**Comment by dscho** [comment]
> $ cmd
> bash: cmd: command not found

So why is it not in your `PATH`? Did you compare whether your settings are different [from mine](https://github.com/git-for-windows/git/issues/720#issuecomment-206897710)? And if so, why (mine are the default settings of Windows)?

**Comment by Radrik5** [comment]
I saw error "bash: reg: command not found" because the user had Reg folder in System32.
Maybe here is a similar problem. @paladox could you try cmd.exe?

**Comment by paladox** [comment]
@Radrik5 ok, I tried cmd.exe and same error.

**Comment by Radrik5** [comment]
Then I agree with @dscho. You probably don't have it in PATH.

**Comment by whoisj** [comment]
@paladox if `%windir%\system` is not on your `%path%`, I have a difficult time believing your install of Windows can boot properly. Even the shell depends on it. 

If you `echo %ComSpec%` what do you get?

The "Command Prompt", also known as cmd.exe, lives in `%windir\system%` but is not actually required for ConHost to operate a console (assuming you have a replacement for cmd.exe, and you do git-bash.exe). The fact that it might be missing makes me rather concerned.

Do you have AV installed? Is this a personal machine or a corporate IT managed system? If IT managed, can you contact your IT dept to see if they've done something with cmd.exe - and if so, inform them that they should not have?

**Comment by dscho** [comment]
Okay, I think everybody agrees by now that this is not a bug in Git.
