### ISSUE TITLE
Can not login to bitbucket.org by Git Credential Manager for Windows

### ISSUE THREAD

**Issue by jerrybk108** [git-for-windows/git#721]
Hello dev team,

I have just installed Git 2.8.0 X64 on windows 10, then the Windows Security pop-up window always show on my screen to input username and password then login to bitbucket.org by Git Credential Manager for Windows, but it seems that the credential can not login or save my credential token in cache, and the pop-up windows always shows on my screen.

![a1f3dfa0-fa53-11e5-9a95-a2d27dc29c2a](https://cloud.githubusercontent.com/assets/6925456/14273501/6aa07b34-fb35-11e5-8df0-5b9a57001307.png)

Refer: https://github.com/progit/progit2/issues/583
Thanks and best regards,
Hieu Tran

**Comment by dscho** [comment]
Please report this in [Git Credential Manager's own bug tracker](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/) (after making sure that this has not been reported there already).

**Comment by gongbudaizhe** [comment]
The temporary solution would be:
`git config --unset credential.helper`

**Comment by vkotovv** [comment]
@gongbudaizhe did not work for me.
I just hit Cancel in this Credential manager dialog, and the got another one prompting for password from OpenSSH, after that it worked.
Here is the ouput:
>Logon failed, use ctrl+c to cancel basic credential prompt.

**Comment by whoisj** [comment]
This issue should be fixed in v1.9.1 of the Credential Manager which co-shipped with Git for Windows 2.12.2(2).

**Comment by FelschR** [comment]
I still have this issue with v2.14.1.1.

**Comment by whoisj** [comment]
@FelschR any chance you have GCM explicitly installed and that is overriding the GCM which ships with GfW?

**Comment by FelschR** [comment]
@whoisj I checked the execution path of the popup window and got the version information from there.

But I also just noticed that I might have another issue. I have SourceTree installed and get this popup in a custom Atlassion/Bitbucket/SourceTree design.

I couldn't find a similar issue in their bug tracker and this issue was the closest I could find.

**Comment by whoisj** [comment]
@FelschR yes the Atlassian, Bitbucket, and SourceTree logos have all been contributed by Atlassian, as has the authentication code.

Thanks for the follow up. @mminns to help triage this issues.

**Comment by FelschR** [comment]
@whoisj @mminns
Any update on this?
