### ISSUE TITLE
confusing sentence in governance model

### ISSUE THREAD

**Issue by Bananeweizen** [git-for-windows/git#727]
> ... but the general strategic line is drawn by the benevolent dictator. In case of disagreement, they have the last word.

I'm not a native English speaker, but I'm confused by "the dictator... they have". I'd expect "he has".

**Comment by rimrul** [comment]
"they have" is correct. It's a [singular they](http://en.wikipedia.org/wiki/Singular_they).

**Comment by dscho** [comment]
Tongue-in-cheek: @Bananeweizen there is an "n" missing in your name. It should be "Bananenweizen" to be correct German.
