### ISSUE TITLE
Mount: Python and MingW do not exist and git not found error

### ISSUE THREAD

**Issue by i2000s** [git-for-windows/git#728]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.
  
  Just installed Git for Windows v2.8.1. 64-bit.

```
$ git --version
git version v2.4.5
```

Note: I cannot run git on the bash window. This output was from my Windows Command Prompt.
- Which version of Windows are you running? 32-bit or 64-bit?
  
  64-bit Windows 10 Pro N.
- What options did you set as part of the installation? Or did you choose the
  defaults?
  
  Only change the default option to allow me use Git on both Git Bash and Windows Command line. It said it will override the default windows `find` and `sort` command lines.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?
  
  Don't think so. I indeed have Python and MingW installed for sure.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
  
  Bash (MINGW64) is failing.
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

By opening the Git bash tool, it shows the mount error and then I used 

```
git status
```
- What did you expect to occur after running these commands?
  
  The status of the repo.
- What actually happened instead?
  
  ```
  mount: warning - /python does not exist.
  mount: warning - /mingw does not exist.
  
  qxd@QC3 MINGW64 /
  $ cd /F/Code/Matlab/
  
  qxd@QC3 MINGW64 /F/Code/Matlab/
  $ git status
  bash: git: command not found
  ```
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?
  
  Repo independent. Basically it says `git` command line is not working in the bash window, but I can use git command in the Windows Command Prompt without any problems.

Git was working on the bash window in the earlier version that I installed (I think it's v2.4.5). Then it failed to work starting for v2.8.1 and the last version before it. I am not sure if this is a problem of my OS or setting. I appreciate if you can guide me to narrow this problem down. Thanks.

**Comment by dscho** [comment]
What does `echo $PATH` say?

> Git was working on the bash window in the earlier version that I installed (I think it's v2.4.5)

Unlikely. Git for Windows never released an installer for v2.4.5.

**Comment by dscho** [comment]
FWIW the example is not reproducible here (it shows the status as expected), therefore it is not yet complete.

**Comment by i2000s** [comment]
```
F:\Code\Matlab>echo $PATH                                                   
$PATH 
```
This is from the Winodows Command Prompt. From the Git bash window, I got 
```
qxd@QC3 MINGW64 ~
$ echo $PATH
/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python
```
And I was wrong about "git works on Windows Command Prompt". Git actually cannot add changes to a commit, no commit can be even registered as well. I figured out that `.git/objects` folder doesn't grant me the permission to write. I tried to change the permission for writing, but it pops up errors to forbid my changing for some reason on Windows. I also installed the GitHub desktop app, which seems fines fine and I don't know if it matters.

**Comment by dscho** [comment]
> F:\Code\Matlab>echo $PATH

In CMD, you need to call `PATH` instead of `echo $PATH`, of course.

> /usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python

Are you positively certain that you got the correct Git for Windows? This looks like Git for Windows 1.x.

> Just installed Git for Windows v2.8.1. 64-bit.
> 
> $ git --version
> git version v2.4.5

Umm. That is not Git for Windows v2.8.1. You can download the correct Git for Windows from https://git-for-windows.github.io/.

**Comment by i2000s** [comment]
Sorry for the late response. With the latest git V2.11.4 installed (downloaded from the official site), this problem persists:
```
$  $PATH
bash: /usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python: No such file or directory
$ git --version
bash: $'\302\203git': command not found
```
Now git is not on the path or something went wrong completely.

**Comment by dscho** [comment]
> /mingw/bin

You still have the wrong `PATH`.

Does `/cmd/git.exe version` work?

**Comment by i2000s** [comment]
```
$ /cmd/git.exe version
git version 2.11.0.windows.3
```
You are right, the `PATH` is not registered properly on my system. I couldn't figure out how to make it work, because those git paths are in the UNIX style. Any idea?

**Comment by dscho** [comment]
> You are right, the PATH is not registered properly on my system.

Git for Windows should take care of that, but as you said earlier:

> ```sh
> $ echo $PATH
> /usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python
> ```

This looks different than what Git for Windows would have done. So it seems that *something* in your setup re-sets the `PATH`. Maybe you have some `.bashrc` or `.bash_profile` file in your home directory?

In any case, prepending `/path/to/git/cmd:` to the POSIX-style `PATH` should fix it. I.e. something like

```sh
export PATH="/c/Program Files/Git/cmd:$PATH"
```

at the end of your `$HOME/.bashrc`. Do not blindly copy this, though, adjust it to your particular setup.

**Comment by i2000s** [comment]
@dscho Thank you very much for the solution. It works now! 

I have noticed that there indeed the `.bashrc` and `.bash_profile` files in my user directory. They might have been added by `ssh` and other programs I use. Also, in the `.bashrc` file, two lines in the beginning might have caused the mounting error:

```
mount E:/Base/SysTools/Python2.7 /python
mount E:/Base/SysTools/MinGW/mingw64 /mingw
export PATH="/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python:/E/Base/SysTools/Git/cmd:$PATH"
```

Anyway, as you can see, I have added the path for Git in the file and it worked. It might be good to let the installation program of Git on windows add the correct path to the `.bashrc` file if there is the file...

**Comment by dscho** [comment]
> It works now!

Please feel free to close tickets whose issues have been addressed. You do not need me to do that. 

> It might be good to let the installation program of Git on windows add the correct path to the .bashrc file if there is the file...

That is not possible, as Git for Windows installs for all users, and the `.bashrc` file is a per-user file. It is the users' responsibility to make sure that their startup files are correct...
