### ISSUE TITLE
Alt Gr + Space should not pop a menu in Git Bash

### ISSUE THREAD

**Issue by Watilin** [git-for-windows/git#729]
Hi folks!

I’d like to address an issue that might be very specific, considering my situation. First, I’m french – sorry about that. And what’s even worse, I’m using Bépo, an alternate keyboard layout inspired from Dvorak.

As a matter of fact, in order to type a `_` with this layout, one must hit `AltGr` (the right `Alt`) + `Space`. Now if you read the title, you see me coming: in the Git Bash, I can’t write any `_` because `AltGr` + `Space` behaves exactly like `Alt` + `Space`, that is, it opens the title bar’s menu.

I still can issue a `_` by hitting `Ctrl` + `Alt` + `Space` which, I admit, is not that hard, but there is a problem anyway. Other exotic keyboard layouts may suffer from this problem as well.

Form filling time :)

---

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

I use the 64-bit version of Git for Windows

```
$ git --version
git version 2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Don’t remember precisely to be honest. I guess I left the defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Bépo keyboard layout. It’s a software layout, I used the `bepo.exe` installer from [this page](http://bepo.fr/wiki/Windows).

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Just hit `AltGr` + `Space`. The problem occurs systematically.

 - What did you expect to occur after running these commands?

I expect to type a `_`. 

 - What actually happened instead?

The title bar’s menu popped up.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No specific repository.

**Comment by dscho** [comment]
If I hit AltGr+Space in a regular CMD window, it *also* opens that window.

So it is really expected behavior, and your choice of keyboard layout is just interfering with the expected behavior.

Having said that, mintty (which is the terminal emulator used by Git Bash unless you change the default in the installer) allows you to disable this shortcut:

1. hit AltGr+Space to open the window's context menu *one last time*
2. choose the *Keys* page
3. uncheck the *Menu and Full Screen* option
4. Hit *Apply* and *OK*.

All Git Bash windows opened from now on will have that keyboard shortcut disabled (the setting is stored in your `%HOME%\.minttyrc` file).

**Comment by Watilin** [comment]
> 3\. uncheck the Menu and Full Screen option

This worked, thanks!
For what it’s worth, in a regular CMD window I’m able to type a `_` by hitting `AltGr` + `Space`.

What’s annoying though is that I can’t open the menu with *left* `Alt` anymore. But I reckon it’s more of a bug in mintty than in Git-windows.

Thanks again :)

**Comment by rimrul** [comment]
>If I hit AltGr+Space in a regular CMD window, it also opens that window.

> So it is really expected behavior, and your choice of keyboard layout is just interfering with the expected behavior.

I can not confirm this behaviour with a standard ISO DE layout on Windows 8.1 or Windows 7, but I can confirm the original issue.
