### ISSUE TITLE
.gitconfig not being recognised

### ISSUE THREAD

**Issue by CeramicTitan** [git-for-windows/git#731]
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.
Git-2.8.1-64-bit

```
$ git --version

git version 2.8.1.windows.1

```

 - Which version of Windows are you running? 32-bit or 64-bit?

64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git config --global user.name username
 - What did you expect to occur after running these commands?

 I expected it to update the global config. As a result of this, my programs i.e IntelliJ cannot recognise my git details and I cannot use the version control.

- The file .gitconfig does exist though, therefore it should update upon command?

 - What actually happened instead?

 http://puu.sh/oiSgS/7938a7fe12.png

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by PhilipOakley** [comment]
Can you actually paste the text of the png into the thread? It's a banned site ("media sharing") from my current location.

**Comment by CeramicTitan** [comment]
@PhilipOakley 
```
maxine@Ryan-PC MINGW64 /c/Users/maxine/Desktop
$ git config --global user.name CeramicTitan
error: could not lock config file C:/users/ryan/.gitconfig: No such file or directory

```

**Comment by snaewe** [comment]
The first line says: `/c/Users/maxine/Desktop` but git wants to put the .gitconfig file into `c:/users/ryan`.
What's your username on that machine ? 
I guess posting the output of `echo $USERNAME $USERPROFILE $HOME` would help.

**Comment by CeramicTitan** [comment]
@snaewe 
`$ echo $USERNAME $USERPROFILE $HOME
maxine C:\Users\maxine /c/users/ryan
`

**Comment by snaewe** [comment]
I'd say `HOME` doesn't match the rest. Did you set `HOME` explicitly (system wide? .bashrc ?) ?

**Comment by CeramicTitan** [comment]
@snaewe 
It's set system wide

**Comment by snaewe** [comment]
Why ?

**Comment by CeramicTitan** [comment]
I was trying to change the name of the pc from Maxine to another name

**Comment by snaewe** [comment]
You have to make sure the directory `$HOME` exists.

**Comment by CeramicTitan** [comment]
@snaewe In theory, if the $userprofile variable and the $variable match, my problem should be fixed?

**Comment by snaewe** [comment]
Well, `$HOME` must exist and if it matches `$USERPROFILE` that would be the case, wouldn't it ?

**Comment by CeramicTitan** [comment]
Well yeah, it worked so I guess it is the case ;)

**Comment by snaewe** [comment]
This issue can be closed then.
