### ISSUE TITLE
git doesn't connect from git bash but works in cmd.exe - 503 from proxy after CONNECT

### ISSUE THREAD

**Issue by rofrol** [git-for-windows/git#732]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

```
git version 2.8.1.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?
  64
- What options did you set as part of the installation? Or did you choose the
  defaults?
  - Use a TrueType font
  - Use Git from Windows Command Prompt
  - Checkout as-is, commit as-is
- Any other interesting things about your environment that might be related
  to the issue you're seeing?
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash and cmd.exe
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

Why I try to connect from git bash I got:

```
$ /mingw64/bin/git fetch
fatal: unable to access 'https://example.com/repo.git/': Received HTTP code 503 from proxy after CONNECT
$ /mingw64/bin/git version
git version 2.8.1.windows.1
```

Works with cmd.exe:

```
> "C:\Program Files\Git\mingw64\bin\git.exe" fetch
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 13 (delta 5), reused 9 (delta 1)
Unpacking objects: 100% (13/13), done.
"C:\Program Files\Git\mingw64\bin\git.exe" version
git version 2.8.1.windows.1
```

It also works when I use git version from github for windows:

```
$ ~/AppData/Local/GitHub/PortableGit_25d850739bc178b2eb13c3e2a9faafea2f9143c0/cmd/git fetch
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 6), reused 0 (delta 0)
Unpacking objects: 100% (13/13), done.
$ ~/AppData/Local/GitHub/PortableGit_25d850739bc178b2eb13c3e2a9faafea2f9143c0/cmd/git version
git version 2.7.4.windows.1
```

Also when I got the same config when run `git config -l` from `git bash` and `cmd.exe`
- What did you expect to occur after running these commands?

works
- What actually happened instead?

503 from proxy after CONNECT
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

It's a private server to which I connect via vpn. We also have proxy in work. It looks like it connect to different IP when run in git bash, when I run with `GIT_CURL_VERBOSE=1 git fetch`

bad:

```
$ GIT_CURL_VERBOSE=1 git fetch
* Couldn't find host example.com in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying <ip_of_proxy>...
* Connected to proxy (<ip_of_proxy>) port 8080 (#0)
* Establish HTTP proxy tunnel to example.com:443
> CONNECT example.com:443 HTTP/1.1
Host: example.com :443
User-Agent: git/2.8.1.windows.1
Proxy-Connection: Keep-Alive

< HTTP/1.1 503 Service Unavailable
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Proxy-Connection: close
< Connection: close
< Content-Length: 732
<
* Received HTTP code 503 from proxy after CONNECT
* Closing connection 0
fatal: unable to access 'https://user@example.com/repo.git/': Received HTTP code 503 from proxy after CONNECT
```

good:

```
git fetch
* Couldn't find host example.com in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying <ip_of_example.com>...
* Connected to example.com (<ip_of_example.com>) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: <some_code>
; OU=E-Services; CNexample.com
*        start date: Jun  8 00:00:00 2015 GMT
*        expire date: Jun  8 23:59:59 2016 GMT
*        subjectAltName: example.com matched
*        issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Sym
antec Class 3 EV SSL CA - G3
*        SSL certificate verify ok.
```

also good:

```
$ GIT_CURL_VERBOSE=1 git fetch
* Couldn't find host example.com in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying <ip_of_example.com>...
* Connected to example.com (<ip_of_example.com>) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\user\AppData\Local\GitHub\PortableGit_25d850739bc178b2eb13c3e2a9faafea2f9143c0\mingw32/ssl/certs/ca-bundle-ghfw.crt
  CApath: none
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: <some code>
*        start date: Jun  8 00:00:00 2015 GMT
*        expire date: Jun  8 23:59:59 2016 GMT
*        subjectAltName: example.com matched
*        issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 EV SSL CA - G3
*        SSL certificate verify ok.
```

**Comment by dscho** [comment]
Did you ever find out what was going wrong?

**Comment by rofrol** [comment]
No

**Comment by dscho** [comment]
After brooding over these logs, it would appear as if the good traces had no proxy call at all... maybe the proxy is defined only in your ~/.bashrc? If not, please describe in as much detail as possible how you configure the proxy?

**Comment by rofrol** [comment]
I don't have access to this system anymore.

**Comment by dscho** [comment]
> I don't have access to this system anymore.

When the reported issue stops to be an issue, please just close the ticket.
