### ISSUE TITLE
ssh-agent.exe *** fatal error cygheap base mismatch detected

### ISSUE THREAD

**Issue by RandomlyKnighted** [git-for-windows/git#734]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

```
git version 2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I had updated NodeJS to v4 not long before that. I tried removing NodeJS but the issue is still there.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash and PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
None just opened Powershell and Git Bash
```
 - What did you expect to occur after running these commands?

N/A

 - What actually happened instead?

When I open PowerShell I get the following message: 
```
      0 [main] ssh-agent (3736) C:\Program Files (x86)\git\usr\bin\ssh-agent.exe: *** fatal error - cygheap base mismatc
h detected - 0x1363400/0x1143400.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] ssh-agent 13368 fork: child -1 - forked process 3736 died unexpectedly, retry 0, exit code 0xC0000142, er
rno 11
fork: Resource temporarily unavailable
Could not open a connection to your authentication agent.
```

and then when I open Git Bash I get this message:
```
Failed to fork child process: Resource temporarily unavailable.
DLL rebasing may be required. See 'rebaseall --help'.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
You don't really say it, but it looks as if you have the 32-bit version of Git for Windows installed. Please try the 64-bit version.

**Comment by RandomlyKnighted** [comment]
You're right, I apparently downloaded the wrong version. I'll reinstall it and will let you know if that fixes the issue.

**Comment by RandomlyKnighted** [comment]
Once I removed the 32-bit version and installed the 64-bit version everything started working like it should.
