### ISSUE TITLE
Git\bin directory is not set correctly in PATH environment variable

### ISSUE THREAD

**Issue by jvalkeejarvi** [git-for-windows/git#739]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

- Git for Windows version 2.8.1 (64 bit)

```
$ git --version
git version 2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 7/8 64-bit

- What options did you set as part of the installation? Or did you choose the
   defaults?

 - Use Git and optional Unix tools from the Windows Command Prompt
 - Checkout as-is, commit as-is
 - Use MinTTY
 - Enable file system caching

### Details

PATH environment variable is not set correctly when Git is installed. Following entries are added to PATH:

- C:\Program Files **(x86)**\Git\bin
- C:\Program Files\Git\cmd
- C:\Program Files\Git\mingw64\bin
- C:\Program Files\Git\usr\bin

First one is incorrect. It should have `Program Files` instead of `Program Files (x86)`.

I've been able to reproduce this on PCs running Windows 7 and Windows 8.

**Comment by dscho** [comment]
It does not do that here. It appends

```
C:\Program Files\Git\cmd
C:\Program Files\Git\mingw64\bin
C:\Program Files\Git\usr\bin
```

here. Maybe you upgraded from an old 32-bit version that did not remove its PATH entry correctly?

**Comment by jvalkeejarvi** [comment]
I re-tested this and PATH variable is set correctly as you said. Some of our own scripts seems to cause this.
