### ISSUE TITLE
Git Bash replaces forward slashes with backslashes when running "node"

### ISSUE THREAD

**Issue by seishun** [git-for-windows/git#740]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

2.8.1, 64-bit

```
$ git --version
git version 2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 10, 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Compile the following C program, save it as `node.exe`, make a copy named `node2.exe`, make sure they're both in PATH.

```c
#include <stdio.h>

int main(int argc, char* argv[]) {
	for (int i = 0; i < argc; i++) {
		puts(argv[i]);
	}
}
```

Then run the following:

```
node a/b
node.exe a/b
node2 a/b
node2.exe a/b
```

 - What did you expect to occur after running these commands?

Same output for all four commands, printing out the executable path and the argument as-is.

 - What actually happened instead?

```
Nikolai@DESKTOP-BF4LIO9 MINGW64 ~
$ node a/b
node.exe
a\b

Nikolai@DESKTOP-BF4LIO9 MINGW64 ~
$ node.exe a/b
C:\Users\Nikolai\Desktop\node.exe
a/b

Nikolai@DESKTOP-BF4LIO9 MINGW64 ~
$ node2 a/b
C:\Users\Nikolai\Desktop\node2.exe
a/b

Nikolai@DESKTOP-BF4LIO9 MINGW64 ~
$ node2.exe a/b
C:\Users\Nikolai\Desktop\node2.exe
a/b
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
This is not Git's behavior, most likely, but Bash's, and it is inherited from the MSYS2 runtime that is used by Git's Bash to emulate POSIX functionality. The reason for this behavior is that Bash expects POSIX paths (forward slashes) and when calling non-MSYS2 programs, it expects them not to be able to handle them correctly, but instead to prefer Windows' native directory separators (backslashes).

So it is very much by design what you are seeing.

If you need to pass options containing forward slashes, there are several ways to do that:

- use Git CMD instead of Git Bash.
- if you need to pass an option with a leading slash, you can double it to tell MSYS2 that you really want to keep that slash.
- you can set the `MSYS_NO_PATHCONV` variable (use with caution), as per our [known issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues) (yes, I know, nobody reads release notes, except the poor soul writing them).

**Comment by seishun** [comment]
>This is not Git's behavior, most likely, but Bash's, and it is inherited from the MSYS2 runtime that is used by Git's Bash to emulate POSIX functionality.

No, MSYS2 doesn't have the behavior I described.

>The reason for this behavior is that Bash expects POSIX paths (forward slashes) and when calling non-MSYS2 programs, it expects them not to be able to handle them correctly, but instead to prefer Windows' native directory separators (backslashes).

No, command-line arguments have nothing to do with paths. And if you read the issue description carefully, you'll see that this only happens in the specific case where the program being run is "node" and not in the generic case.

>if you need to pass an option with a leading slash, you can double it to tell MSYS2 that you really want to keep that slash.

As you can see in the example I provided, Git Bash replaces slashes regardless of their position.

**Comment by Radrik5** [comment]
This is probably caused by winpty: https://github.com/git-for-windows/build-extra/commit/44ed99b47f564d0b89784ae8008627f5c3d06d69

**Comment by dscho** [comment]
> No, MSYS2 doesn't have the behavior I described.

@seishun are you absolutely certain? I ask because I'd like you to point me to code in `winpty` that converts slashes.

> This is probably caused by winpty: git-for-windows/build-extra@44ed99b

@Radrik5 good conjecture. If that is the problem, using `node.exe` on the command-line will work around the problem. And break interactive consoles again.

**Comment by seishun** [comment]
>@seishun are you absolutely certain? I ask because I'd like you to point me to code in winpty that converts slashes.

https://github.com/rprichard/winpty/blob/a22f493982bb9847c48200912df7a66d23750a02/src/unix-adapter/main.cc#L152 would be my guess.

**Comment by dscho** [comment]
> https://github.com/rprichard/winpty/blob/a22f493982bb9847c48200912df7a66d23750a02/src/unix-adapter/main.cc#L152 would be my guess.

But this *only converts `argv[0]`*! See for yourself: https://github.com/rprichard/winpty/blob/a22f493982bb9847c48200912df7a66d23750a02/src/unix-adapter/main.cc#L361

**Comment by seishun** [comment]
Well what do you know. Indeed, vanilla winpty doesn't replace slashes in the remaining arguments. But MSYS2 provides a patched version that [does](https://github.com/Alexpux/MSYS2-packages/blob/master/winpty-git/0001-Apply-POSIX-to-Win-conversion-on-all-arguments-on-MSYS.patch). I can see the intention behind it, but it's inconsistent with how MSYS2 itself handles path conversions when running non-MSYS2 programs.
