### ISSUE TITLE
Windows10 Git Problem

### ISSUE THREAD

**Issue by RuiweiLee** [git-for-windows/git#742]
### Setup

$ git --version
 git 2.8.1 version
- Which version of Windows are you running? 32-bit or 64-bit?
- 64-bit windows10
- What options did you set as part of the installation? Or did you choose the
  defaults?

default options
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

my windows user name use Chinese word, which appear strangely in the bash window.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
  
  Git bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.
  
  git config --global user.email xx@qq.com
- What did you expect to occur after running these commands?
  
  it can declare the user
- What actually happened instead?

error:could not lock config file C:/Users/xx/.gitconfig No such file or directory

and i open the directory  but didn't find the gitconfig file.It is only found in C:\Program Files\Git\mingw64\etc
so i copy it to the C:/Users/xx/ but i still don't work

**Comment by linquize** [comment]
Do you use Git Bash or cmd.exe to run this command?

**Comment by dscho** [comment]
@RuiweiLee do not simply delete the template. Fill it out. Your report is seriously lacking in detail, prone to frustrate anybody who would like to help you.
