### ISSUE TITLE
Package requests: perl-rename and autojump

### ISSUE THREAD

**Issue by Todd-Weed** [git-for-windows/git#744]
I like both of these packages and find them beneficial; they do respectively:

1) rename multiple files using Perl regular expressions
2) a faster way to navigate your filesystem from the command line

Their original package sources can be found [here](https://www.archlinux.org/packages/community/any/perl-rename/) and [here](https://www.archlinux.org/packages/community/any/autojump/).

This is just a request so take it as you want to.

Both are basically scripts so no additional packages are pulled in.

I have edited the PKGBUILDs for linking, built, installed, and tested them.

perl-rename:

```bash
# $Id$
# Maintainer: Florian Pritz <flo@xinu.at>

pkgname=perl-rename
pkgver=1.9
pkgrel=1
pkgdesc="Rename multiple files using Perl regular expressions"
arch=(any)
url="http://search.cpan.org/~pederst/rename/"
license=('unknown')
depends=(perl)
options=(!emptydirs)
source=(http://search.cpan.org/CPAN/authors/id/P/PE/PEDERST/rename-$pkgver.tar.gz)
md5sums=('16df2adde955a6867701564e3d7c6a52')

build() {
    cd "$srcdir/rename-$pkgver"

    perl Makefile.PL PREFIX=/usr INSTALLDIRS=vendor
    make
}

package() {
    cd "$srcdir/rename-$pkgver"

    make DESTDIR="$pkgdir"/ install
    mv "$pkgdir"/usr/bin/vendor_perl/{rename,perl-rename}
    mv "$pkgdir"/usr/share/man/man1/{rename,perl-rename}.1p
}
```

autojump:

```bash
# $Id$
# Maintainer: Jaroslav Lichtblau <svetlemodry@archlinux.org>
# Contributor: graysky <graysky AT archlnux DOT us>
# Contributor: Geoffroy Carrier <geoffroy@archlinux.org>
# Contributor: Jo├½l Schaerer <joel.schaerer@laposte.net>
# Contributor: Daniel J Griffiths <ghost1227@archlinux.us>

pkgname=autojump
pkgver=22.3.0
pkgrel=1
pkgdesc="A faster way to navigate your filesystem from the command line"
arch=('any')
url="https://github.com/wting/autojump"
license=('GPL3')
depends=('python')
source=($pkgname-$pkgver.tar.gz::https://github.com/wting/$pkgname/archive/release-v$pkgver.tar.gz)
sha256sums=('800f444b820b3a985e1da2d183fb5e2e23753a2ade53d6e1195678c650379a03')

prepare() {
  cd $pkgname-release-v$pkgver
  sed -i "s:/env python:/python3:g" bin/$pkgname
}

package() {
  cd $pkgname-release-v$pkgver

  SHELL=/bin/bash ./install.py --destdir "$pkgdir" \
                               --prefix 'usr/'     \
                               --zshshare 'usr/share/zsh/site-functions'

  cp "$pkgdir"/usr/share/$pkgname/"$pkgname"* "$pkgdir"/etc/profile.d/

#https://github.com/joelthelion/autojump/pull/339
  sed -i "s:/usr/local/:/usr/:g" "${pkgdir}"/etc/profile.d/$pkgname.sh
  sed -i "s:/build/autojump/pkg/autojump/:/:g" "${pkgdir}"/etc/profile.d/$pkgname.sh
#FS#43762
  sed -i '27,31d' "${pkgdir}"/etc/profile.d/$pkgname.sh
}
```

**Comment by dscho** [comment]
Why not use MSYS2 (with any package you like, instead of Git for Windows with the minimal set of packages necessary to run Git), and contribute the package definitions [to that project](https://github.com/Alexpux/MSYS2-packages)?

> Jo├½l Schaerer

Encoding? :smiley:

**Comment by Todd-Weed** [comment]
OK, I understand better how this works now. Thank you for explaining.

I will pass on this recommendation to them.

**Comment by dscho** [comment]
> I will pass on this recommendation to them.

That is not at all what I suggested. At least if you are thinking about telling the MSYS2 maintainers what they should work on. I was thinking more along the lines of you opening a proper Pull Requests.

Seeing as perl-rename and autojump are not really related to running Git on Windows, I think it is safe to close this ticket now.
