### ISSUE TITLE
Missing make.exe 

### ISSUE THREAD

**Issue by SteveALee** [git-for-windows/git#746]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 64 bit
```
$ git --version
2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 defaults except use check in LF checkout AS IS

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Nope
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Git Bash in windows 10 terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
NA
```
 - What did you expect to occur after running these commands?

 NA

 - What actually happened instead?

 NA

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 NA

Q: Is there are particular reason ```make``` is missing from the msys distribution? I use it. Having a separate installation of MINGW just to get make  is probably going to be a pain.

thanks

**Comment by landstander668** [comment]
Most likely it's because the "normal" installation isn't meant to be a full development environment. If you want/need make and friends, then my guess is that you should install the [Git for Windows SDK](https://github.com/git-for-windows/build-extra/releases) instead.

**Comment by shiftkey** [comment]
@SteveALee it exists as an [MSYS package](https://github.com/git-for-windows/MSYS2-packages/tree/master/make) however it's not included as part of Git for Windows - likely as the purpose of GfW is to be a minimal environment (it doesn't include compilers like `gcc`, for example) and focused on just what Git needs.

The Git for Windows SDK will give you an environment where you can install additional upstream packages locally using `pacman` and then build a custom version of Git for Windows, if you want to distribute it.

**Comment by SteveALee** [comment]
@landstander668 @shiftkey Thanks. It's many years since I last used MionGW/Msys and in those days there was only the one package :) I see the project has now moved on (forked). There used to be 2 diffeent makes to make life more fun ;( 

Anyway thanks for answer. It certainy makes sense and in the end I set up a Ubuntu VM an build the JS package I needed there. 

Soon I'll be able to use Bash for Windows FTW!

**Comment by dscho** [comment]
@SteveALee please note that you were really looking for [MSYS2](https://msys2.github.io/) (or our [SDK])http://git-for-windows.github.io/#download-sdk) which is a friendly fork), as you were looking for *substantially more* than just Git.

You probably will find that the SDK, combined with the power of the included `pacman` might fill your needs. Unless you are under such time pressure again that you cannot even research the gems to which we point you, of course :wink:

**Comment by SteveALee** [comment]
@dscho You are correc tabout the time pressure. I need to build something for AWS JS client access 'yesterday' so took the safe 'build' on linux' route whithout waiting for your replies. Turns out the build needs perl and java so all getting a bit iffy. ;)

I will try on windows with the SDK at some point

Oh I did find MSYS2 in my search for a native maxe exe 

Tanks for your help
