### ISSUE TITLE
git compiled using the the git-for-windows-sdk does not clone https repositories

### ISSUE THREAD

**Issue by tareqak** [git-for-windows/git#749]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64 bit

```
$ git --version
git version 2.8.2.windows.1.1.g85fb4ba
```
- Which version of Windows are you running? 32-bit or 64-bit?

64 bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

Default installation of git-for-windows SDK
- Any other interesting things about your environment that might be related
  to the issue you're seeing?
  
  I don't think so.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
$ GIT_TRACE=1 git clone https://github.com/rupa/z
11:53:26.060365 git.c:350               trace: built-in: git 'clone' 'https://github.com/rupa/z'
Cloning into 'z'...
11:53:26.131674 run-command.c:336       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/rupa/z'
```
- What did you expect to occur after running these commands?
  
  A folder called z.sh should appear with the contents of the repository.
- What actually happened instead?
  
  No folder was created, nothing was cloned down.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

I tried a few differnt https repositories on github.

https://github.com/rupa/z/
https://github.com/phacility/arcanist

**Comment by dscho** [comment]
This looks like the good ole system DLL problem. To work around this, try to call

```sh
for dll in /mingw64/bin/*.dll; do ln $dll /mingw64/libexec/git-core/; done
```

and then run the clone again.

**Comment by tareqak** [comment]
Thanks a lot! That worked for me. There was some garbled text in the output when cloning though, which I didn't get from the normal Git for Windows. The main reason I was using the SDK was for zsh.

**Comment by dscho** [comment]
@tareqak thanks for confirming.

Now, it would be a really big help if you could patch https://github.com/git-for-windows/build-extra/blob/master/sdk-installer/setup-git-sdk.bat, make an SDK installer by running the `release.sh` script in the same directory, test that it works for you and prepare a Pull Request. I'd be very grateful if you could do that for me.
