### ISSUE TITLE
git-svn: Cannot accept non-LF line endings in 'svn:log' property

### ISSUE THREAD

**Issue by ebousse** [git-for-windows/git#750]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

I am using Git version 64-bit (`Git-2.8.1-64-bit.exe`).

```
$ git --version
git version 2.8.2.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

I do not remember, probably the default options.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

I am trying to use `git-svn` to have a local git repo of a remote VisualSVN Server repository. I want to be able to use both `rebase` and `dcommit`to communicate with this server.

I have no control on this remote server and I don't know which version of VisualSVN is used.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Cmd for the clone, Git Bash for the commit.
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

Using Git Cmd (because I had an unrelated problem Git Bash):

```
$ git svn clone http://<repo_url>
```

Then I make changes in the repo and make some git commits.
Finally, using Git Bash:

```
$ git svn dcommit
```
- What did you expect to occur after running these commands?

A set of svn commits (one per git commit) and no errors
- What actually happened instead?

I have the following error:

```
$ git svn dcommit
Committing to https:/<repo_url> ...

ERROR from SVN:
Wrong or unexpected property value: Cannot accept non-LF line endings in 'svn:log' property
W: 8c3b57666e783bfcf5e469ab234bf52a83758d10 and refs/remotes/git-svn differ, using rebase:
:040000 040000 71fe362fa754f8e9f3ecdf160098ab94a5d9f06d acbc7b74098b75d70a49b8faa8c83498982fec11 M      Software
Current branch master is up to date.
ERROR: Not all changes have been committed into SVN, however the committed
ones (if any) seem to be successfully integrated into the working tree.
Please see the above messages for details.
```
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

Unfortunately I cannot, since I have no access to this company hosted SVN server. Sorry :(.

**Comment by dscho** [comment]
> Using Git Cmd (because I had an unrelated problem Git Bash):
> 
> $ git svn clone http://<repo_url>
> 
> Then I make changes in the repo and make some git commits.
> Finally, using Git Bash:
> 
> $ git svn dcommit

I doubt that you will be able to reproduce this problem if you follow these instructions. I know for a fact that other people perform exactly these steps and do not run into your problem.

> Unfortunately I cannot, since I have no access to this company hosted SVN server. Sorry :(.

You could always initialize your own SVN repository in the file system and zip it up. I am afraid that I won't be able to help you unless you make it substantially easier for me to reproduce your problem.

**Comment by dscho** [comment]
Okay, no reaction, even after a year, that's frustrating.

To wrap this up, the closest account of a similar issue I found was http://subversion.1072662.n5.nabble.com/Cannot-accept-non-LF-line-endings-in-svn-ignore-property-after-mirroring-with-SVM-tp154924p154926.html, suggesting that there may be issues with the Subversion repository.

**Comment by ebousse** [comment]
My apologies for the lack of input, I stopped working on this project hence I stopped using windows and git-for-windows.

And unfortunately, I had no access to the repository itself, locked on the server of another company...

If I happen to manage to provide a way to reproduce the issue someday, I'll be sure to post it here.

**Comment by dscho** [comment]
Thanks for letting us know!
