### ISSUE TITLE
Clean up ReleaseNotes.css handling in build-extra

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#751]
It should live next to the `ReleaseNotes.md` file, and the path in the `.html` file needs to be configurable. (Earlier, I tried to make the release notes to work in place, but that was misguided and is no longer necessary, as we have the `--render-release-notes` option.) Refactor the rendering code out into its own shell script.

Needs to wait until https://github.com/git-for-windows/build-extra/pull/113 gets merged.

**Comment by fourpastmidnight** [comment]
@dscho: Looks like this issue could be closed due to the merge of PR113?

**Comment by dscho** [comment]
Absolutely correct! Thanks!
