### ISSUE TITLE
not working on windows10

### ISSUE THREAD

**Issue by akhilesh-kk2** [git-for-windows/git#753]
installation process is not completing on windows 10.

**Comment by shiftkey** [comment]
Please provide more information about your setup using the [Issue Template](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md) we have defined...

**Comment by akhilesh-kk2** [comment]
I am trying to install git 64 bit on my system having window 10.
Please find screen shot.
Setup is not able to go further from this stage.
[image: Inline image 1]

On Wed, May 11, 2016 at 6:00 PM, Brendan Forster <notifications@github.com>
wrote:

> Please provide more information about your setup using the Issue Template
> <https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md>
> we have defined...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/git-for-windows/git/issues/753#issuecomment-218444986>
>



-- 
With regards,
Akhilesh Kumar
Sr. software engineer

**Comment by shiftkey** [comment]
@akhilesh-kk2 I can't really help out without more information being provided.

**Comment by akhilesh-kk2** [comment]
What information do you want.
Please let me know so that i will provide you.

On Thu, May 12, 2016 at 11:54 AM, Brendan Forster <notifications@github.com>
wrote:

> @akhilesh-kk2 <https://github.com/akhilesh-kk2> I can't really help out
> without more information being provided.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/git-for-windows/git/issues/753#issuecomment-218670568>
>



-- 
With regards,
Akhilesh Kumar
Sr. software engineer

**Comment by shiftkey** [comment]
@akhilesh-kk2 the [Setup](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md#setup) section has a number of details which are relevant, and the screenshot didn't attach from the previous reply.

**Comment by dscho** [comment]
> What information do you want.

@akhilesh-kk2 you first deleted the issue reporting template, ignoring it altogether. Then you ignored @shiftkey's [comment that clarified where to find that template again](https://github.com/git-for-windows/git/issues/753#issuecomment-218444986). So the answer to your question has been pointed out already twice before you asked it.

**Comment by akhilesh-kk2** [comment]
I am sorry for inconvenient. 
Version of git is Git-2.8.2-64-bit
Version of window is 64 bit (Windows 10)
![unnamed](https://cloud.githubusercontent.com/assets/11919157/15238301/1dbb60a4-18f4-11e6-9448-e6324967da0c.png)

Please find screen shot above. 
Setup is not completing at all. 
This is the final screen from where installation is not proceeding to next stage.

**Comment by dscho** [comment]
> I am sorry for inconvenient.

It is not inconvenient for me, but I am sorry that you will not be able to resolve your problem any time soon at this pace.

You could try to find out what processes are running, e.g. using the Task Manager or [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/bb896645). This might help you to identify the cause of your problem.
