### ISSUE TITLE
install mingw-get by default

### ISSUE THREAD

**Issue by eromoe** [git-for-windows/git#754]
### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

64-bit

```
$ git --version
git version 2.7.0.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

  64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Git-Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ wget http://git-for-windows.github.io/#download-sdk
bash: wget: command not found
$ mingw-get install msys-wget
bash: mingw-get: command not found

```

I wish git can install mingw-get/ wget  by default.
I have search around, still can't get how to install wget in git-bash

**Comment by dscho** [comment]
You are mistaking this project for a general-purpose installer for many, many different packages. However, this project is about offering Windows users Git's functionality. No more, no less. `wget` in particular seems to be not at all required for that.

And FWIW `mingw-get`'s packages are not very well supported, and therefore we abandoned the idea to base Git for Windows 2.x' SDK on that package management system.

You probably want to go with [MSYS2](https://msys2.github.io/) instead. Which sports `pacman` and a lot of really well-maintained packages.
