### ISSUE TITLE
Pull not prompting for authentication when scripted

### ISSUE THREAD

**Issue by ChipJust** [git-for-windows/git#760]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.
  
  64-bit

```
$ git --version
git version 2.8.2.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 8.1 64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

Defaults
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

I did not have the problem when using version 1.9.5.
A coworker sees this problem with 2.5.0.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Running the script from the windows CMD shell.
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

This script can recreate the issue, when you run it from a git directory.

```
def git_pull():
    import os
    import subprocess
    r = None
    try:
        r = subprocess.check_output(
                    ['git', 'pull'],
                    cwd=os.getcwd(),
                    stderr=subprocess.STDOUT).decode('ascii').strip()
    except Exception as e:
        print (e)
        print (e.output.decode('ascii'))
    print (r)
```
- What did you expect to occur after running these commands?

I expected to be prompted for my password and then that git would update the repository.
- What actually happened instead?

Script gives this output

```
Command '['git', 'pull']' returned non-zero exit status 1
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

None
```
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

The remote is using ssh://. Not sure about what happens with other protocols.

**Comment by ChipJust** [comment]
Forgot to mention that clone does prompt for the password when called in the same way from a Python script.

**Comment by bbolli** [comment]
Does the prompt appear if you run your script via `winpty`?

**Comment by whoisj** [comment]
If you use `cmd /c git pull` do you get the prompt?

This is potentially a TTY detection issue. It is likely that Git is attempting to not deadlock a non-interactive process with prompts a user will never see.
