### ISSUE TITLE
fatal: could not create work tree dir 'agario-driver': Permission denied

### ISSUE THREAD

**Issue by bollidtzo** [git-for-windows/git#765]
### Setup

using  64-bit
git version 2.8.3.windows.1

 - Which version of Windows are you running? 

. windows 10 home 64-bit oem

 - What options did you set as part of the installation? Or did you choose the
   defaults?

. git from git bash only (no path changes)
. did not install credential manager -- not developing, only grabbing 

 - Which terminal/shell are you running Git from?

 . Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

git clone https://github.com/scaljeri/agario-driver.git

 - What did you expect to occur after running these commands?

. stuff download

 - What actually happened instead?

fatal: could not create work tree dir 'agario-driver': Permission denied

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/scaljeri/agario-driver

.............

**Comment by nalla** [comment]
As the error message indicates `fatal: could not create work tree dir 'agario-driver': Permission denied` do you have the required privileges?

what happens if you execute `mkdir agario-driver` in the `shell`?

**Comment by dscho** [comment]
> > What commands did you run to trigger this issue? If you can provide a Minimal, Complete, and Verifiable example this will help us understand the issue.
> 
> git clone https://github.com/scaljeri/agario-driver.git

Works for me (in a Git Bash, just after opening it, i.e. the current working directory is the home directory):

```sh
me@work MINGW64 ~
$ git clone https://github.com/scaljeri/agario-driver.git
Cloning into 'agario-driver'...
remote: Counting objects: 620, done.
remote: Total 620 (delta 0), reused 0 (delta 0), pack-reused 620
Receiving objects: 100% (620/620), 2.76 MiB | 1.55 MiB/s, done.
Resolving deltas: 100% (273/273), done.
Checking connectivity... done.
```

Since it is working for me, it is not a verifiable example. Please be more careful to provide examples that are likely to be verifiable by others, too.

**Comment by dscho** [comment]
I guess the original poster tried to clone into `C:\Program Files`, but the communication in this ticket is too broken to verify.
