### ISSUE TITLE
Git bash here won't work when $HOME directory is a .git repository

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#77]
When the $HOME directory is a git repository, Right click popup menu in Windows Explorer at the target directory; then click `Git Bash Here`, the git bash won't locate to the
target(current) git repository, but at the $HOME git respository.

**Comment by dscho** [comment]
> git bash won't locate to the target(current) git repository, but at the $HOME git respository.

???

**Comment by lygstate** [comment]
Hard to describe it, my poor English,
My $HOME directory is a .git directory, which means
there is a path $HOME/.git, and when I trying to using 
Windows explorer to do `Git Bash Here` work at $SOME_DIR, then after the bash
script start, the `PWD` `CWD` will be `$HOME` but `$SOME_DIR`

**Comment by dscho** [comment]
So if I understand correctly, right-clicking on the `Documentation` directory in `/usr/src/git` and choosing `Git Bash Here`, you would expect the working directory to be `/usr/src/git`, *not* `/usr/src/git/Documentation`? But that's by design...

**Comment by lygstate** [comment]
No, the working directory is located to `%UserProfile%` or `$HOME`, cause 
there is a git repository at %UserProfile% or `C:\Users\Administraot`

**Comment by dscho** [comment]
@lygstate I really would like it if you could follow the steps described at http://whathaveyoutried.com/.

This is what I did:

1. install Git 2.3.5.6 (64-bit)
2. open the Explorer
3. select `C:`
4. select `Users` (on Win7)
5. right-click my user directory
6. open a Git Bash (it opens in `~` as I expected)
7. call `git init` in that Bash
8. back in the Explorer, right-click *again* on my user directory
9. open a second Git Bash (it opens in `~` as I expected, again)
10. back in the Explorer, double-click on my user directory
11. right-click a *subdirectory* of my user directory
12. open a Git Bash (it opens in `~/<subdirectory>`, again as I expected)

So I guess I have no idea what problem you are talking about.

**Comment by lygstate** [comment]
OK, I's my fault, my environment is not correct with wrong .bashrc file.
