### ISSUE TITLE
Git pull Issue

### ISSUE THREAD

**Issue by cibi246** [git-for-windows/git#774]
git.exe pull -v --no-rebase --progress "origin"

fatal: Out of memory, malloc failed (tried to allocate 3788345344 bytes)
fatal: write error: Invalid argument

git did not exit cleanly (exit code 1) (10093 ms @ 6/7/2016 2:56:57 PM)

------------------------------------------------------------------------------------------------

I am getting the above issue when taking pull from git repo. I suspected its because of insufficient memory. So i free my RAM space and restarted my system. But still it doesn't work. 

Googled this and tried adding some params in .git/config file. But no luck.. 

Any solution on this? Thanks in advance..

**Comment by dscho** [comment]
There is unfortunately too little information here (it would probably have saved time all around to fill out the issue reporting template instead of ignoring and deleting it).

**Comment by cibi246** [comment]
Please find my .git/config file below:

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
	 packedGitLimit = 512m
  packedGitWindowSize = 512m
[remote "origin"]
	url = <repo Url>
	fetch = +refs/heads/*:refs/remotes/origin/*
	puttykeyfile = ""
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "X.X"]
	remote = origin
	merge = refs/heads/X.X
[pack]
  threads = 1
  deltaCacheSize = 1024m
  packSizeLimit = 1024m
  windowMemory = 1024m

Kindly reply what else information needed to resolve this.

**Comment by cibi246** [comment]
Hi.  

I got resolved this issue by myself. Actually i have increased http.postBuffer size to clone a big module in my local. After that i was facing this issue. 

Now i restored http.postBuffer back to default value. Now i can able to take latest in git. 

Thanks..
