### ISSUE TITLE
Issues with some files in Windows platform

### ISSUE THREAD

**Issue by mahesh18389** [git-for-windows/git#777]
I am facing a serious problem in GIT Bash for some files. These files are showing as 'modified' in git status, even it is not modified. I couldn't track actually whats happening. This happens only in Windows platform. crlf config is set as false. It dint help. For a newly cloned repo also these files are popping up. Because of this, i couldn't able to checkout to other branch, stash, or rebase. But, i could do a force checkout with -f option. Did anyone come across similar issue like this? Whats the issue here. Please help!
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

$ git --version
git version 2.8.4.windows.1

64-bit package.
- Which version of Windows are you running? 32-bit or 64-bit?

64 bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

defaults
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

No
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash
- What commands did you run to trigger this issue? 

git status, git checkout <branch_name>, git stash, git pull --rebase
- What did you expect to occur after running these commands?

to show only the edited files. 
- What actually happened instead?

It shows unmodified files as modified and not allowing to do anything. 
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Without being able to have a look at the files, I have no chance to diagnose the issue.

So here are a few ideas how  you can diagnose yourself:
- look whether the files in question really have no CR/LF
- look at the attributes
- switch off both the autocrlf config and the eol attribute
- investigate using `git ls-files --eol`

Good hunting!

**Comment by shiftkey** [comment]
Closing due to lack of information.
