### ISSUE TITLE
git bash: Query console details of standard handles through Win32 API results in invalid handle error

### ISSUE THREAD

**Issue by markfinal** [git-for-windows/git#778]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

The issue I see is in the 64-bit

```
$ git --version
git version 2.8.4.windows.1
```

whereas I don't see the issue in a (much) older version

```
$ git --version
git version 1.9.5.mysysgit.1
```

This version appears to be 32-bit as it's in Program Files (x86) and dumpbin confirms this on sh.exe.
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 8.1 Pro, 64bit for git 2.x
Windows 8.1, 64-bit, for git 1.x
- What options did you set as part of the installation? Or did you choose the
  defaults?

I always just enable git in git bash (never CMD), and line endings are unchanged in and out. Otherwise, defaults.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

Both are C/C++ development machines, with VisualStudio (various versions) installed.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

It isn't git commands that I see the issue in, but instead, an effect of running a program in git bash invoking the Win32 console API. The issue is fetching console related data for any of the standard handles results in an invalid handle error.

I first spotted the issue from some C# I've written, that writes to stdout, and then moves the cursor back (it's implementing a progress update that just overwrites itself). I've converted the code to C, which invokes `GetConsoleScreenBufferInfo`with the standard handles, and I can replicate the issue.

I've attached the source code, VisualStudio 2013 project file for a reproducible, and a release build executable.
[ConsoleTestC.zip](https://github.com/git-for-windows/git/files/308745/ConsoleTestC.zip)

The test source is derived from the .NET source code at http://referencesource.microsoft.com/#mscorlib/system/console.cs,cc823e361f57c987.
- What did you expect to occur after running these commands?

This is what I see when run in git bash 1.9.5.msysgit.1:

```
$ ./ConsoleTestC.exe
stdout console screen buffer size is 150x500
```

In my larger C# test application, this shell does allow cursor positioning successfully.
- What actually happened instead?

This is what I see when run in git bash 2.8.4.windows.1

```
$ ./ConsoleTestC.exe
failed to get console screen buffer info for stdout, error code 6
failed to get console screen buffer info for stdout, error code 6
failed to get console screen buffer info for stdin, error code 6
```

where error code 6 is the Win32 error "The handle is invalid", which is what I see in my C# test app.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?
  
  N/A

**Comment by dscho** [comment]
Could you test the following two things:

- run `winpty ./ConsoleTestC.exe`
- reinstall Git for Windows, choosing the "default Windows console" instead of "MinTTY" and then run `./ConsoleTestC.exe` again?

**Comment by markfinal** [comment]
```
$ git --version && winpty ./ConsoleTestC.exe
git version 2.8.4.windows.1
stdout console screen buffer size is 270x3000
```

So using `winpty `works. I'd not heard about it before, and from a bit of internet reading, it appears to run the process in a normal CMD shell, and then sends the output back to bash.
(FYI prefixing my C# app with `winpty `also makes my initial use case of progress updates work.)

I probably should have pointed out earlier that a normal CMD shell works fine with the test app. So that would help explain why it works with `winpty`.

```
C:\Users\Mark\Documents\Visual Studio 2013\Projects\ConsoleTestC\ConsoleTestC>.\ConsoleTestC.exe
stdout console screen buffer size is 200x3000
```

I am a fan of bash so work almost exclusively in the bash shell, so it's nice that it works in all shells.


Before I reinstall Git for Windows, as you are asking to integrate it with the default Windows console, then I presume you wanted me to run the test app _in a CMD shell_ after the reinstall? (I wasn't sure from your request.)
If that's the case, then I think the above output covers it.
However, if you meant me to _repeat the test in bash_ (without winpty) after the reinstall (perhaps you are aware of something that changes in the bash install), then I still need to do that.
Please let me know what you meant so I can test the right thing. Thanks.

**Comment by dscho** [comment]
> Before I reinstall Git for Windows, as you are asking to integrate it with the default Windows console, then I presume you wanted me to run the test app in a CMD shell after the reinstall? (I wasn't sure from your request.)

No, if you reinstall it that way, you can run Git Bash and it will start in a "CMD window" (it is really a ConHost window, but the difference is lost on the internet ;-)).

If you are fine with `winpty`, there is no need to test this (it would work, of course).

> So using `winpty` works.

Good. It is probably too obscure [in our release notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through `winpty` (e.g. the Python console needs to be started as `winpty python` instead of just `python`).

It would be really good if you could think of a clearer way to express this, preferably in a way that would have helped you think of `winpty` for your use case.

**Comment by markfinal** [comment]
I am fine with using `winpty`. I would like to understand the issue, from a technical perspective, but I should probably first read up on why `winpty `was written in the first place.

I will broadcast this solution on my software website so that my users are aware of it too (this is the C# tool I hinted at).

I definitely missed the connection with this issue with the mention in the release notes.

I just modified the test app, to query whether the standard handles are valid (you'd hope they are), e.g.

```
    HANDLE hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
    if (INVALID_HANDLE_VALUE == hStdOut)
    {
        printf("stdout is invalid\n");
    }
```

No message is output running in git bash 2.8.4. So the input to `GetConsoleScreenBufferInfo` is fine

```
    CONSOLE_SCREEN_BUFFER_INFO csbi;
    BOOL success = GetConsoleScreenBufferInfo(hStdOut, &csbi);
```

The MSDN help for this function (https://msdn.microsoft.com/en-us/library/windows/desktop/ms683171(v=vs.85).aspx) doesn't report any particular errors it will return, so it's a bit of a mystery which handle is invalid and why.

 A couple of notes:

- I can run _non-interactive_ python (standard installer of 2.7.9) in the bash shell without the need for `winpty`. I use it for a lot of scripting. However, interactive python does need `winpty `to show anything.

- I've run a lot of standard Windows tools through bash and only with this console manipulation has it ever come back with an error. I might have wondered why commands weren't printing output, but not linked it to the console itself.

So perhaps the release note should mention something like this in addition to the existing note:

> If you run a non-MSYS2 application that requires user interaction on the console _but does not display a prompt_, or manipulates the console's cursor _resulting in an invalid handle error_, then running your application though `winpty `may be necessary to work correctly with MinTTY. 

I think that would cover both interactive Python, and covers my use case of needing to manage the cursor.

Hope that is of help.

**Comment by fourpastmidnight** [comment]
Maybe we could just add one sentence:
> If you experience issues running a console program when using mintty as your terminal emulator, please try running your program via `winpty` in an attempt to resolve the problem before reporting the issue: `winpty your_console_app`.

**Comment by markfinal** [comment]
Instead of 'If you experience issues...' which is quite broad, would it be better to be more specific, e.g. 'If you experience console input or output issues...'?

**Comment by fourpastmidnight** [comment]
@markfinal Perhaps. I think my suggestion may be a bit too generic. Yours may be too specific in the other hand. For instance, is that the only error one could expect to receive from any console application that doesn't work properly from the mintty terminal emulator?

**Comment by markfinal** [comment]
@fourpastmidnight Indeed. I've seen two different manifestations of why winpty sometimes needs to be used (hence my input and output mentions to cover them), but I'll have to hold my hands up and say I don't know if there are others symptoms.

My specialisation was to avoid anyone reading that and thinking that any crash bug could be attributed to it.

But then, if it was an arbitrary bug, using winpty wouldn't fix it as your proposed text requests, and they'd still report an issue.

So perhaps I'm being too fussy. I was also thinking of text that would've prompted me to try it in my reported case.

**Comment by dscho** [comment]
> would like to understand the issue, from a technical perspective

MinTTY does not use Win32 Console instances. It uses Cygwin's (or in our case, MSYS2's) pseudo terminals, a concept originating from Unix. To use those pseudo terminals, a program would need to be linked to the Cygwin (or the MSYS2) runtime.

So when you run console programs in MinTTY, they have no access to any Win32 Console because there is none.

`winpty` creates a "shadow" Win32 Console and tries to synchronize between Cygwin's (or MSYS2's) pseudo terminals and that shadow Console. When running console programs that do access the Win32 Console, they write into the one known by `winpty` which dutifully updates the terminal seen in the MinTTY.

Needless to say, this synchronization comes at a price (it is slow), which is the reason why we try to avoid using `winpty`.

**Comment by markfinal** [comment]
@dscho Thank you for the explanation.

**Comment by dscho** [comment]
> Thank you for the explanation.

Of course!

As to the rewording/addition to the "Known Issues", I am eagerly awaiting the compromise with which you two native speakers will come up ;-)

**Comment by markfinal** [comment]
Defer to @fourpastmidnight's proposal (as he's right, too specific can be limiting), but definitely add back in the known problem applications mentioned already (including my test case), i.e.

> If you experience issues running a console program when using `mintty `as your terminal emulator, please try running the console program via `winpty `in an attempt to resolve the problem before reporting the issue: `winpty your_console_app`
> Programs known to be affected by this are non-MSYS2 Python, PHP, Node and OpenSSL, and applications manipulating the console's cursor.


This does refer to both mintty and MSYS2, so perhaps the correct terminology should be used - I'm afraid I don't know which one is more correct in this context.

Thoughts?

**Comment by fourpastmidnight** [comment]
So, based on our discussion, I would like to leave out any mention of potential causes for errors in console programs being run from mintty (e.g. cursor manipulation). Since when using mintty there is no ConHost terminal backing it, programs that expect to do anything with the standard Windows terminal explicitly (such as cursor manipulation) most likely will not work unless run through `winpty`.

> If you experience issues running Windows console programs when using `mintty` as your terminal emulator for Git for Windows, please try running the console program via `winpty` to attempt to resolve the problem before reporting an issue: `winpty the_console_app.exe`  
> Programs which are not MSYS2-based console applications, such as the Windows versions of Python, PHP, NodeJS, and OpenSSL, are examples of such console-based programs which must be run through `winpty` in order to display their output correctly.  
> Windows console programs expect a ConHost terminal to be present to display and manipulate their output. mintty does not use ConHost for terminal output. `winpty` is a program provided with Git for Windows which provides the ability for ConHost terminal-based programs to display their output in mintty terminals.

I think this is about as detailed as we want to get.

**Comment by markfinal** [comment]
@fourpastmidnight Sounds great!

**Comment by dscho** [comment]
Sorry for the long delay, this fell off of my radar.

I meant to comment that it is a little verbose, given that we already have quite a few known issues and users *already* stop reading them because they think this is too long and they cannot be bothered and then they open tickets here instead... :smile: 

So maybe we can reduce that to one paragraph?

**Comment by markfinal** [comment]
Apologies also from me for not replying until now.

I don't disagree that users generally don't read release notes and skip to opening tickets, since that's what I did!
The proposed text @fourpastmidnight wrote I think is very useful and interesting for the techie savvy reader, which ought to be 99% users of git IMO. So perhaps the full text can be kept as a footnote?

I think if I had read just the first paragraph of the proposal in the release notes, I would have tried winpty in my case.

**Comment by dscho** [comment]
@markfinal maybe prepare a PR to help with the burden of maintaining this project? I'll close this ticket in the meantime.
