### ISSUE TITLE
"Fatal: Exception encountered." on Azure Websites

### ISSUE THREAD

**Issue by vincent** [git-for-windows/git#779]
On a 32bits Windows Azure box, from Bash or PowerShell.
```
$ git --version
git version 2.8.1.windows.1
```

`git fetch` or `git pull origin branch` triggers a "Fatal: Exception encountered." but `git status` does not trigger it:
```
$ git pull origin test
Fatal: Exception encountered.
# rest of the normal output, for example:
From https://bitbucket.org/owner/project
 * branch            test       -> FETCH_HEAD
Already up-to-date.
```

Moreover, `git clone repo.git` also triggers the error - shown just after the "cloning into .." line - but still import files.
```
$ git clone https://user:pass@bitbucket.org/owner/repo.git
Cloning into 'repo'...
Fatal: Exception encountered.
```

The same commands, against the same repo, work from Macos, Linux, and local Windows machines.

I guess it is linked with the recent msysgit upgrade on Azure - from 1.8.4 to 2.8.1 - but I cannot find how to debug it as it's an Azure "black box". I've tried ntstrace with no luck.

I'm not good enough to read the Git source, but maybe someone knows what it executed at these steps ?

**Comment by dscho** [comment]
I am pretty certain that this exception comes from the credential manager. Can you `set GIT_TRACE=1` before running one of those commands again?

**Comment by vincent** [comment]
I think you're right @dscho 

```
13:49:32.094178 git.c:351               trace: built-in: git 'fetch'
13:49:32.141055 run-command.c:336       trace: run_command: 'git-remote-https' 'origin' 'https://user:pas@bitbucket.org/owner/project.git'
13:49:33.188350 run-command.c:336       trace: run_command: 'git credential-manager store'
13:49:33.298588 git.c:564               trace: exec: 'git-credential-manager' 'store'
13:49:33.298588 run-command.c:336       trace: run_command: 'git-credential-manager' 'store'
Fatal: Exception encountered.
13:49:33.464360 run-command.c:336       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
13:49:33.558135 run-command.c:336       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
13:49:33.620636 git.c:351               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
13:49:33.651891 run-command.c:952       run_processes_parallel: preparing to run up to 1 tasks
13:49:33.651891 run-command.c:984       run_processes_parallel: done
13:49:33.651891 run-command.c:336       trace: run_command: 'gc' '--auto'
13:49:33.729993 git.c:351               trace: built-in: git 'gc' '--auto'
```

**Comment by dscho** [comment]
Okay, good. Now, you said that this is a "black box" Git for Windows? Does that mean you cannot upgrade? I am pretty certain that Git Credential Manager v1.3.0 (bundled in Git for Windows v2.8.2) fixed that very problem...

**Comment by vincent** [comment]
Sad news, that the Azure native version differs by one minor with the fixed one :)

Nope, I don't have write access to C:/, and I had to downgrade the "coreutils" part of msysgit to the old one, because it broke many scripts..

Isn't there a way to "bypass" the `git-credential-manager store`, since I provide user:pass in the repo url ?

**Comment by davidebbo** [comment]
@vincent Testing on Azure Web App, I found the following:

- this issue only seems to occur when doing a fetch/clone on an authenticated repo via http. This does not normally occur on Azure Web Apps. We either deal with public repos, or use ssh for private repos. Can you explain how you get into this situation?
- the error appears benign, as the repo is still clones. Are you seeing any ill effect beyond the message?
- upgrading to the latest v2.8.4 does *not* make a difference
- installing git with credential store disabled *does* fix the issue

So we can try to do that in a future deployment on Azure Web App.

**Comment by vincent** [comment]
thank you for the report @davidebbo 
 
- I'm not sure why we used the https for this internal tooling project. I'll dig that deeper, if we can do ssh I guess we'll use it.
- no, I'm not seeing errors beyond this error, so I guess it's benign indeed

**Comment by vincent** [comment]
I guess I'll close this, if it has been _supposedly_ fixed in v2.8.4.

Thanks !

**Comment by davidebbo** [comment]
This is more an Azure issue in how we install git. Might make sense to open issue on https://github.com/projectkudu/kudu/ to track.

**Comment by davidebbo** [comment]
@dscho do you know how we can disable credential store when installing git from the command line?

Currently, we pass the following flags: `/VERYSILENT /SP- /SUPPRESSMSGBOXES`

**Comment by dscho** [comment]
Git for Windows never configured the credential store itself, so I think it is probably configured elsewhere. Maybe use the new `--show-origin` flag of `git config` to find out?

**Comment by davidebbo** [comment]
I'm referring to the installer, e.g. `Git-2.8.4-32-bit.exe`. It has UI to select all kind of things (line endings, mintty, cred store, etc...), and typically for automated installs (that can't have UI), there are alternate ways of making those choices. I think it's via the `/COMPONENTS` flag (see http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline), and it's a matter of figuring out what to pass to it.

WHere are the sources for the installer? Maybe we can figure it out from there.

**Comment by dscho** [comment]
The installer only has an option to configure the Git Credential Manager by default. The sources are here: https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss
