### ISSUE TITLE
Regression with version 2.3.5 and 1.8.1 - fatal: unrecognized input

### ISSUE THREAD

**Issue by castortech** [git-for-windows/git#78]
When trying to do a rebase with 2.3.5 i got:
 git rebase --onto origin/ba  0b7200c
First, rewinding head to replay your work on top of it...
Applying: blah blah
fatal: unrecognized input
Repository lacks necessary blobs to fall back on 3-way merge.
Cannot fall back to three-way merge.
Patch failed at 0001 Moved heat index field to shared abstract class for import/export and
The copy of the patch that failed is found in:
   C:/eclipse/git/irisba/.git/rebase-apply/patch

and I switched back to 1.8.1 and the rebase happened without any error or warning.

Looking at the patch file, it looks like it contains a lot of non printable characters. Please advise if there is anything I should be looking for.

Thanks
Alain

**Comment by dscho** [comment]
This looks indeed like a bug. Would you please help me reproduce it by stripping down your example to a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)?

**Comment by dscho** [comment]
@castortech it would be really good if you could come up with that Minimal, Complete, and Verifiable Example I asked for. Otherwise you will force me to close this ticket unaddressed.
