### ISSUE TITLE
Editor (or pager) with spaces in it's path fails to be ran by Git

### ISSUE THREAD

**Issue by charlesmilette** [git-for-windows/git#782]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 _64-bits_

```
$ git --version
git version 2.8.3.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 _Windows 10 build 14342, 64-bits_

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 _Set `core.editor` to `C:\Program Files\Notepad2\Notepad2.exe`
The file actually exists and is working._

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 _Windows Command Prompt_

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

_Anything that triggers the editor to open will also do that._

```
git config --global --edit
```

 - What did you expect to occur after running these commands?

 _I expected Notepad2 to open the config file_

 - What actually happened instead?

```
C:\Program Files\Notepad2\Notepad2.exe: C:Program: command not found
error: There was a problem with the editor 'C:\Program Files\Notepad2\Notepad2.exe'.
```

**Comment by charlesmilette** [comment]
Same happens with the pager (set as `C:\Program Files\Git\usr\bin\cat.exe`)

But strangely enough, `gpg.program` is set to `C:\Program Files (x86)\GNU\GnuPG\pub\gpg.exe` and everything works OK when signing commit and/or tags.

**Comment by dscho** [comment]
Could you try again with a quoted `core.editor` path? The difference to `gog.program` is that the latter expects a path while the former expects a partial command-line (to support passing command-line options to the editor's executable).

**Comment by charlesmilette** [comment]
Yep. It worked.

But I think those things should be handled within git.

Your favorite text editor is not forcibly in your PATH

**Comment by dscho** [comment]
> But I think those things should be handled within git.

They are. You just have to keep in mind that the `core.editor` does *not* refer to a path, but to a command-line. Read: you have to remember that Git will interpret unquoted spaces in your setting as separators between command-line arguments.

Existing users rely on this behavior. I trust you agree that it is in our best interest to keep things running smoothly by leaving this behavior as-is.
