### ISSUE TITLE
Time stamp locking after amending commit

### ISSUE THREAD

**Issue by futagoza** [git-for-windows/git#783]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

Git 64-bit, v2.8.3.windows.1

- Which version of Windows are you running? 32-bit or 64-bit?

Windows 10 Home, 64-bit

- What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

- Any other interesting things about your environment that might be related
   to the issue you're seeing?

UTC London Time zone

### Details

- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I use Git GUI for all git tasks, and only use CMD for Node/NPM and make tasks

- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.
````
Example of what I do using Git GUI and Sublime Text 3:

  1) Commit change: chore(build) updated scripts
  2) Altered a build script slightly
  3) Amend last commit, adding in altered script
  4) Optionally push changes
  5) Repeated this process

After that I check commit history either through GitHub or
through Git GUI's "Visulize master's history"
````
- What did you expect to occur after running these commands?

Correct time stamps

- What actually happened instead?

Time stamps are all the same as the amended commit

- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

So far It has occurred in 4 separate and unrelated repositories

**Comment by dscho** [comment]
Can you see with `git log --pretty=fuller` whether the commit time stamps are as you would expect them?

**Comment by futagoza** [comment]
The commit log shows the time stamps for the AuthorDate the same as the amended commit time stamp, but the CommitDate for each of them is correct.

I don't seem to be having any issues with the date or time in any other application or the OS, and this bug only pops up when I commit after an amended commit.

**Comment by dscho** [comment]
> I don't seem to be having any issues with the date or time in any other application or the OS, and this bug only pops up when I commit after an amended commit.

This is intended behavior. The `--amend`, `-c` and `-C` options use the original author information *including timestamp*. See e.g. `-C`'s documentation:

> -C <commit>::
> --reuse-message=<commit>::
>      Take an existing commit object, and reuse the log message and the authorship information (including the timestamp) when creating the commit.

In any case, this is not Windows-specific, therefore this bug tracker is a suboptimal place to discuss this. If you want to see this behavior changed, you need to take the issue to [the Git mailing list](mailto:git@vger.kernel.org).
