### ISSUE TITLE
Git log for specific branch

### ISSUE THREAD

**Issue by mahesh18389** [git-for-windows/git#784]
Hi All,

How to list all the commits done in a specific branch. As you all know, git log list the commits from all the branches (actual commits in that branch+ topic branches which got merged into).

Also, how to get the commits for a "particular file only in a specific branch"

Thanks & Regards,
Mahesh

**Comment by dscho** [comment]
Please direct your questions about Git usage to one of the mailing lists listed here: https://git-scm.com/community (probably you want to use the Git users mailing list).
