### ISSUE TITLE
Cannot use local credential.helper if Git Credentials Manager is enabled

### ISSUE THREAD

**Issue by Dohbedoh** [git-for-windows/git#787]
### Setup

git version 2.8.3.windows.1
Windows Server 2012
Default installation (with the **Enable Git Credentials Manager** enabled by default)

### Issue

With recent version of `git-for-windows`, there is an option **Enable Git Credentials Manager** enabled by default. With this option, it is impossible to use a local configuration.

### How to Reproduce

I noticed this issue using Jenkins first but this could be reproduced in a terminal. I initialize a repo as following - my credentials are store in the file `gittest.credentials`:

```
 > git init C:\Users\vagrant\win-node-test-2\workspace\test-git-for-windows
 > git config --local credential.username dohbedoh
 > git config --local credential.helper store --file=\"C:\Users\vagrant\test-git-for-windows\gittest.credentials\"
```

Here is the local configuration inside that repo:

```
$ git config --local -l
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
credential.username=dohbedoh
credential.helper=store --file=\"C:\Users\vagrant\test-git-for-windows\gittest.credentials\"
```

Then I try to fetch a repository using this local config:

> git -c core.askpass=true fetch --tags --progress https://github.com/user/repo.git +refs/heads/*:refs/remotes/origin/*

And encounter the following issue:

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\Program Files\Git\mingw64\libexec\git-core\git-credential-store.exe
File: exec_cmd.c, Line 23

Expression: argv0_path
remote: Invalid username or password.
```

Git tries to use the Credential Manager even though I have a local config.

### More Details

Checking the system configuration, I can see that the `credential.helper` is setup:

```
$ git config --system -l
credential.helper=manager
```

I believe this has some kind of priority over the local config?

### Workaround

The only workaround I found is to unset the property:

> git config --system --unset credential.helper

Otherwise uninstall/install git-for-windows and ensure to disable the option **Enable Git Credentials Manager**

**Comment by dscho** [comment]
This seems to be a duplicate: https://github.com/git-for-windows/git/issues/766

Would you be able to [build Git](https://github.com/git-for-windows/git/wiki/Building-git) from [my credstore-assertion branch](https://github.com/msysgit/git/compare/master...dscho:credstore-assertion) and verify that it fixes your problem? I would then finish my work on that patch and include it in the next official Git for Windows version.

**Comment by Dohbedoh** [comment]
It seems to work! Thanks @dscho

**Comment by Dohbedoh** [comment]
Oh sorry. Actually my credentials were in the credentials store. I still hit this issue with 2.9.2. Running the same command:

> git -c core.askpass=true fetch --tags --progress https://github.com/user/repo.git +refs/heads/:refs/remotes/origin/

The output I have is:

```
remote: Invalid username or password.
fatal: Authentication failed for ' https://github.com/user/repo.git'
```

The same command works without using the `credential.helper=manager`.

**Comment by dscho** [comment]
@Dohbedoh is it possible that the Git Credential Manager (which uses a completely different backend from the credential-store) simply has stored incorrect credentials? (`git credential-manager`'s output should give you enough hints how to debug this further.)

**Comment by Dohbedoh** [comment]
@dscho No credentials are stored in GCM.

With the latest version of Git For Windows 2.10.1 I am still hitting the same issue. It is not possible to use a local configuration of credential helper. Git always tries to use GCM although I don't want to. This makes Git for Windows unusable with Jenkins if GCM is enabled.

Only workaround is to uninstall GCM: 

> git credential-manager uninstall

**Comment by Dohbedoh** [comment]
@dscho Should we re-open this or is this an expected behavior - that if GCM is enabled it is enforced?

**Comment by dscho** [comment]
> Git always tries to use GCM although I don't want to

This is an option in the installed (opt-out) IIRC. Maybe you want to turn it off during installation?
