### ISSUE TITLE
Windows Explorer crashes when opening Git Bash/GUI in Explorer Integration

### ISSUE THREAD

**Issue by ascchrvalstr** [git-for-windows/git#788]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

64-bit.

```
$ git --version
git version 2.9.0.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 10 Pro Insider Preview
Build 14361.rs1_release.160603-1700
64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

The defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I tried to launch Git Bash and Git GUI from the Explorer Integration feature. (Right-click and use Git * Here)

 - What did you expect to occur after running these commands?

I expected that a window occured.

 - What actually happened instead?

The Explorer was blocked for a while, then it crashed and restarted. No window opened.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It happens to all repositories.

There's the event log.

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-06-15T16:19:56.455929400Z" /> 
  <EventRecordID>804</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>ascchrvalstr</Computer> 
  <Security /> 
  </System>
 <EventData>
  <Data>Explorer.EXE</Data> 
  <Data>10.0.14361.0</Data> 
  <Data>57524526</Data> 
  <Data>windows.storage.dll</Data> 
  <Data>10.0.14361.0</Data> 
  <Data>5752453a</Data> 
  <Data>c0000005</Data> 
  <Data>00000000003546df</Data> 
  <Data>2700</Data> 
  <Data>01d1c721119a9f9c</Data> 
  <Data>C:\WINDOWS\Explorer.EXE</Data> 
  <Data>C:\WINDOWS\System32\windows.storage.dll</Data> 
  <Data>4e7ae730-0f6f-498f-bb89-dbee6c11759e</Data> 
  <Data /> 
  <Data /> 
 </EventData>
</Event>

**Comment by speedwaystar** [comment]
I'm also in the Windows 10 Pro Insider fast ring and I can confirm that the latest Insider Preview crashes on accessing ANY explorer context menu invoked by HKCR/Directory/background/shell,  not just those created by Git for Windows.

![registry](http://i.imgur.com/XZ6np2k.png)

in my case **Search using AstroGrep**, **Bash prompt here** (my own Cygwin invocation), **Git GUI here,** and **Git bash here** all crash Explorer.

![blah](http://i.imgur.com/L1JNDCM.png)

**Comment by speedwaystar** [comment]
feedback-hub:?contextid=395&feedbackid=9fda9081-c4de-4472-b33e-3ab90cdd3ded&form=1&src=2

**Comment by speedwaystar** [comment]
upvote this bug report on Windows 10 Feedback Hub. The link only works in MS Edge: 
feedback-hub:?contextid=395&feedbackid=9fda9081-c4de-4472-b33e-3ab90cdd3ded&form=1&src=2

**Comment by ilmax** [comment]
Same here, with the very same configuration. As a workaround I was able to open git bash from start menu and cd into the desired directory. 
The explorer integration however keep faulting expoler.exe.

**Comment by speedwaystar** [comment]
workaround is to right click on the parent folder and select Bash Shell Here -- Directory/Shell commands in registry don't crash Explorer, only Directory/Background/Shell (i.e. right click on empty space). over to you, Microsoft!

**Comment by speedwaystar** [comment]
fixed in Insider Preview Build 14367.rs1
