### ISSUE TITLE
core.hideDotFiles=false not working

### ISSUE THREAD

**Issue by wdscxsj** [git-for-windows/git#789]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

  32-bit

```
$ git --version
git version 2.9.0.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

  Windows 7 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

  Extract from PortableGit-2.9.0-32-bit.7z.exe with 7-Zip, and manually run post-install.bat.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

  No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

  CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init
```
 - What did you expect to occur after running these commands?

  With `core.hideDotFiles = false` in .gitconfig, the .git directory should not be hidden, as described here: http://comments.gmane.org/gmane.comp.version-control.git/293549.

 - What actually happened instead?

 .git is hidden.

  On my machine, **this happens to v2.8.4 as well as v2.9.0. v2.8.3 works fine.**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 Nothing to provide here.

**Comment by dscho** [comment]
Thank you for the report!

I have a working fix here: https://github.com/git-for-windows/git/compare/master...dscho:unhidden-git

However, I am not happy with the repeated code (the `core.hidedotfiles` handling was *copied* from `config.c`) and I will need to think about the best way to address that issue.

**Comment by wdscxsj** [comment]
Any plan of including this fix into an upcoming release?  Thanks!

**Comment by dscho** [comment]
Thanks for the prod.

**Comment by dscho** [comment]
For the record, the fix is in Git for Windows v2.9.3.
