### ISSUE TITLE
git bundle create does not close handle to *.lock file

### ISSUE THREAD

**Issue by glhez** [git-for-windows/git#790]
Hello,

I am running Git 2.9.0 x64 on Windows 7 and git is run under ConEmu 160612 [x64]. 
Problem arise in mintty too.

```
$ git version
git version 2.9.0.windows.1
```

I tried to generate a bundle based on two branch (sync and develop) which are at the same point.
Git fails because the bundle is empty, but it does not remove the lock file because there is still an open handle on it:

```
git bundle create zeta-bash.2016-06-19.develop.1.home.bundle sync..develop
fatal: Refusing to create empty bundle.
Unlink of file 'E:/git/bundles/zeta-bash.2016-06-19.develop.1.home.bundle.lock' failed. Should I try again? (y/n) n
warning: unable to unlink E:/git/bundles/zeta-bash.2016-06-19.develop.1.home.bundle.lock: Invalid argument
```
Note: it works on any repository, simply use something like master..master.

I think the problem is here: https://github.com/git-for-windows/git/blob/master/bundle.c#L449

I've forked the git repo: https://github.com/glhez/git/commit/c9d30827cac71e953c5286c431ab5007ff9a1792 but did not have time to test it yet.

**Comment by dscho** [comment]
> The condition is strange: why going to error label when having `ref_count` negative, while having no `ref_count` is also an error ?

The condition `ref_count < 0` means that `write_bundle_refs()` returned an error (printing an error message already). When it is zero instead, the function actually succeeded, and the `atexit()` handler called implicitly by `die()` is responsible to roll back the transaction.

**Comment by glhez** [comment]
Okay, I've pushed another commit (in fact, I amended it several times) with the removal of curly brace (I do love them, you don't understand the beauty of them :)), with tabs instead of space and with a "better" commit message.

I've created a test, but I don't know if it's well named (tgfw790 for "<git for windows> issue 790").

**Comment by dscho** [comment]
Thank you! I will hopefully soon get around to submitting this change upstream, together with other `.lock` file fixes. Will keep you Cc:ed!
