### ISSUE TITLE
Filters should be parallelized if needed cf lfs needs

### ISSUE THREAD

**Issue by lcsthom** [git-for-windows/git#791]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)

### Setup

- 2.9.0.windows.1 x6

- on a windows 7 16g ram, ssd

No particular installation settings, default.

### Details

 - running git from both a cmd and GitExtensions

 - What commands did you run to trigger this issue? If you can provide a
   Issue encountered while staging or checkout of lfs files. Please do not answer me to move my issue to the lfs project, this is clearly a git issue/improvment.

Files are proccessed sequentially which is too slow for thousands files, while lfs offer in some cases a way to run it from the command line in parallel, I think the git filters should be run in parallel. Especially because there is no need (or I am forgetting something) to run it sequentially.

 - What did you expect to occur after running these commands?

 A parallel run which can switch the perf in my case from 1h30min to 1min30!

 - What actually happened instead?

 This is a no go for our enterprise to use git-lfs because this is too slow.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 Can't do that, this is confidential.

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
