### ISSUE TITLE
Git For Windows Installation Issue

### ISSUE THREAD

**Issue by antoops** [git-for-windows/git#792]
- [ ] While installing git for windows, i have changed the installation directory. It threw and alert saying 

> The specified installation directory does not seem to be writable. Please choose another directory or restart setup as a user with sufficient permissions.

The folder i have given was not there, but installation wizard created it and still showing this error. If we continue, it is okay to go ahead. So i guess, installation no need to show this unncessary alert if not required. 

### Setup

My OS is Win7 - 64bit

```
$ git --version
2.9.0

 - Which version of Windows are you running? 32-bit or 64-bit?
64bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

i changed the folder which was didn't exists but it got created by installation wizard still it threw an alert saying not able to write.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Nothing special 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 This is about installation

**Comment by dscho** [comment]
By default, the installer does not let the user choose the target folder. How did you choose it?

**Comment by antoops** [comment]
For the first installation, it shown a default path editable which i modified, hence the alert came. 

> ---------------------------
Git 2.9.0 Setup
---------------------------
The specified installation directory does not seem to be writable. Please choose another directory or restart setup as a user with sufficient permissions.
---------------------------
OK   
---------------------------

I couldnt take the screenshot that time but copied the alert to clipboard. Now when i try to install, it is not asking, so i guess it might be for fresh installation.

**Comment by dscho** [comment]
I cannot reproduce the issue, unfortunately.
