### ISSUE TITLE
Unsigned executables!!!

### ISSUE THREAD

**Issue by Logmytech** [git-for-windows/git#798]
Git bash is Unsigned.

I always check executables for Signatures and was surprised to see git-bash.exe and git-cmd.exe unsigned.

Please sign the official releases with a signature for Windows.

**Comment by dscho** [comment]
The installer is signed.

There are Do you actually realize what you are asking? There are over 400 `.exe` files and over 250 `.dll` files. Apart from your pleasure, what would be the benefit of me spending that insane amount of time to sign them all?

**Comment by Logmytech** [comment]
I wasn't aware that there were that many exes and DLLs

If possible please sign the basic executables Git-bash and Git-GUI.

Thank you.
