### ISSUE TITLE
CAN NOT CONECT WITH HEROKU, THE LOGIN IS FALIED... HELP

### ISSUE THREAD

**Issue by FernandoAguilarR** [git-for-windows/git#799]
i cant connect with heroku, i have a counnt in this web site, i can login in the same, but when i go at git and i enter the command:

heroku login

appears this:

$ heroku login
Enter your Heroku credentials.
Email: ###############
Password (typing will be hidden):
 !    Login is currently incompatible with git bash/cygwin
 !    In the meantime, login via cmd.exe
 !    https://github.com/heroku/cli/issues/84

in the part of "#############" i put my email, i press enter and inmediatly git show the message, help me please

**Comment by dscho** [comment]
Heroku is not a core functionallty of Git, let alone Git for Windows. Therefore this is not a bug in Git for Windows.

Having said that, if you can come up with a way to reproduce it easily for people who do *not* use Heroku, there is a chance that some people will still help you.

I could also imagine that `winpty heroku login` works. YMMV
