### ISSUE TITLE
Adjust colors in git-bash terminal?

### ISSUE THREAD

**Issue by mindplay-dk** [git-for-windows/git#801]
The blue color in git-bash is unreadable, almost invisible, just as it is by default under Windows in the standard console window.

The standard windows console lets you customize the standard color palette, but it appears there is no equivalent option in git-bash? And it does not respect the terminal color settings defined for the standard console window.

Is there some way to adjust the colors?

If not, I'd like to suggest you adjust the dark blue to a more visible color, such as `rgb(0,100,255)` which is more readable and still contrasts visibly with the other blue color in the standard palette.

**Comment by PhilipOakley** [comment]
the normal window in use for bash is the 'mintty' (minimal tty), so have a browse for the .minttyrc file on the web. It provides the configs for colourisation (I feel your pain for the unreadable blues - it's worse if you also have f.lux installed which dims the blues at night!)

**Comment by dscho** [comment]
I assume that @PhilipOakley's answer addressed this issue.

**Comment by mindplay-dk** [comment]
All good, thanks - also this article was useful:

https://www.rafaelhart.com/2015/07/minttyrc-colour-schemes-fonts-2015/
