### ISSUE TITLE
Installer has problems when AppLocker is enabled

### ISSUE THREAD

**Issue by KjartanThor** [git-for-windows/git#802]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 2.9.0 64-bit

```
 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 10 Enterprise, 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 Installer can't run on machines with AppLocker enabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 AppLocker is enabled by a DomainPolicy

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 none

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Trying to run the installer on a machine with AppLocker enabled results in the error message:
Unable to execure file in the temporary directory. Setup aborted.
Error 1260: This program is blocked by group policy.
```
 - What did you expect to occur after running these commands?

 The installation wizard should appear.

 - What actually happened instead?

I got an error message as described.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by kostix** [comment]
> Error 1260: This program is blocked by group policy.

Do you really mean the Git installer should somehow be armed with something which would allow it to bypass group policies set by admins at your `$dayjob`?  The whole point of group policies is to enforce whatever they define.

If I understand the essense of the problem correctly, I'd say it's not a bug.

**Comment by KjartanThor** [comment]
No I don't think that would be possible. But it would be good if it were possible to run the exe with a parameter that tells the installer where to extract itself so that you can override the default temp location.

**Comment by kostix** [comment]
@KjartanThor, sorry, I have completely missed the bit about executing file in a temporary directory.

**Comment by kostix** [comment]
[See also](https://github.com/msysgit/msysgit/issues/202).

**Comment by kostix** [comment]
@KjartanThor, does overriding the `TEMP` environment variable helps?

Something like this (in `cmd.exe` or PowerShell or whatever):

    C:\> set TEMP=%USERPROFILE%\foo
    C:\> mkdir "%TEMP%
    C:\> git-setup.exe

**Comment by KjartanThor** [comment]
That might help, I completed the install by redirecting the variable for all processes, but that is a bad Idea. I will try to override the temp variables for the current instance of the command line and see if that does the trick. That would be a proper workaround since one really doesn't want to accidentally allow execution of temporary files of any sort.

**Comment by KjartanThor** [comment]
This works as a proper workaround :)
