### ISSUE TITLE
Cannot apply patches to files encoded in UTF-8 BOM

### ISSUE THREAD

**Issue by IanKemp** [git-for-windows/git#804]
Git is unable to apply patches to files that are encoded using the UTF-8 byte order mark.
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

Git-2.9.0-64-bit.exe

```
> git --version
git version 2.9.0.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 8.1 x64, fully updated
- What options did you set as part of the installation? Or did you choose the
  defaults?

`core.autocrlf = true`
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

N/A
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell 4

```
> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```
- What commands did you run to trigger this issue?
1. Created a patch by running `git format-patch <sha1> -o ../` in a source repository.
2. Attempted to validate the patch on the same respository cloned into a different directory by running `git apply --check ../<patch-filename>`
- What did you expect to occur after running these commands?

Patch should be applied.
- What actually happened instead?

Every file to be patched gives output of the following:

```
error: patch failed:<filename>:<line-number>
error: <filename>: patch does not apply
```

and the patch is not applied.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Could you provide a script that demonstrates this? Or a repository? I suspect that this is not specific to Windows, but I am too busy with other Git stuff to chase this one down.
