### ISSUE TITLE
Filename too long when cleaning a repo

### ISSUE THREAD

**Issue by songdongsheng** [git-for-windows/git#806]
### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

git version 2.8.1.windows.1, 64 bit.

```
$ git --version
git version 2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64 bit Windows 10.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://github.com/dotnet/cli.git
cd cli
build.cmd
git clean -dfx
```
 - What did you expect to occur after running these commands?

D:\var\vcs\git\dotnet\cli>C:\cygwin64\bin\git clean -dfx
Removing test/Microsoft.DotNet.Cli.Utils.Tests/bin/
Removing test/dotnet-publish.Tests/bin/

 - What actually happened instead?

git clean -dfx
...
warning: Could not stat path 'test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/CrossPublishingSucceedsAndHasExpectedArtifacts/PortableTests/StandaloneApp/packages_cross_publish_test/System.Runtime.Extensions/4.1.0-rc2-24008/ref/netcore50/ja/System.Runtime.Extensions.xml': Filename too long
...

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

git clone https://github.com/dotnet/cli.git
cd cli
build.cmd
git clean -dfx

**Comment by nalla** [comment]
have you tried `git -c core.longPaths=true clean -dfx`?

**Comment by songdongsheng** [comment]
Thanks for your workaround, it works fine.

D:\var\vcs\git\dotnet\cli> git -c core.longPaths=true clean -dfx
Removing test/Microsoft.DotNet.Cli.Utils.Tests/bin/
Removing test/Microsoft.DotNet.ProjectModel.Loader.Tests/bin/
Removing test/Performance/bin/
Removing test/dotnet-publish.Tests/bin/

I'm wondering why it isn't default setting ?

**Comment by nalla** [comment]
Have a look at the [release notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md). One (including myself) should always read release notes when installing software.

This is the section explaining things

> Many Windows programs (including the Windows Explorer) have problems with directory trees nested so deeply that the absolute path is longer than 260 characters. Therefore, Git for Windows refuses to check out such files by default. You can overrule this default by setting `core.longPaths`, e.g. `git clone -c core.longPaths=true ...`.
