### ISSUE TITLE
Cannot be displayed with Multi-language menu

### ISSUE THREAD

**Issue by kashewnuts** [git-for-windows/git#809]
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

```
$ git --version
git 2.9.0.windows.1, 64bit
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows7Pro(64bit)
- What options did you set as part of the installation? Or did you choose the
  defaults?

Defaults, though I enabled support for Git from default cmd.exe.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

Nothing
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD, PowerShell, Git Bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
$ git gui
or
$ gitk
```
- What did you expect to occur after running these commands?

When you start `git gui` or `gitk`, I expected the menu is displayed with Japanese.
Because I use in Japanese environment, and the menu has been displayed in Japanese when Ver1.9.5.
- What actually happened instead?
  
  It displayed the menu with english only.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?
  
  N/A

**Comment by dscho** [comment]
The reason for this is that we had to strip out localized messages to give the installer a "diet": it was growing too large, and too many users complained about non-English messages.

Having said that, if you want to help me, we could offer *additional* installers that do contain the localized messages. This would require a little effort from you, as I am too busy with too many other Git things. Are you prepared for that?

**Comment by dscho** [comment]
My offer was open long enough, I think ;-)

**Comment by kashewnuts** [comment]
I'm sorry that I left it.
Thank you for considering.
