### ISSUE TITLE
git executables die silently in Windows container

### ISSUE THREAD

**Issue by nicholasdille** [git-for-windows/git#813]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

I have installed Git in a Windows Container in Windows Server 2016 TP5 manually as well as with docker. I have used Git version 2.9.0 and 2.8.4 64-bit. I have tested the installer (.exe) as well as the the archive download (.tar.bz2).

The installer was executed with the following command line:

`c:\Git-64-bit.exe /VERYSILENT /NORESTART /NOCANCEL /SP- /SUPPRESSMSGBOXES /DIR=c:\git`

The archive was added using a Dockerfile:

```Dockerfile
FROM windowsservercore
ADD Git-64-bit-tar-bz2 /git
CMD [ "c:\\git\\cmd\\git.exe", "--version" ]
```

After entering the container (`docker run -it git powershell`), I tried running the following commands:

1. c:\git\cmd\git.exe
1. c:\git\git-bash.exe
1. c:\git\bin\bash.exe

In all tests, the executables die without any message or error.

I'll be happy to provide more details when necessary!

**Comment by nicholasdille** [comment]
I found an event in the application event log describing the issue. Does this help?

```
Message              : Faulting application name: git.exe, version: 2.9.0.1, time stamp: 0xaa20aa08
                       Faulting module name: KERNELBASE.dll, version: 10.0.14300.1000, time stamp: 0x56f4a81d
                       Exception code: 0xc0000006
                       Fault offset: 0x000000000002b946
                       Faulting process id: 0xf44
                       Faulting application start time: 0x01d1d790821f82b7
                       Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
                       Faulting module path: C:\Windows\system32\KERNELBASE.dll
                       Report Id: cf2a55f2-eea0-4406-9cab-c74ecf4ffc06
                       Faulting package full name: 
                       Faulting package-relative application ID: 
Id                   : 1000
Version              : 
Qualifiers           : 0
Level                : 2
Task                 : 100
Opcode               : 
Keywords             : 36028797018963968
RecordId             : 59
ProviderName         : Application Error
ProviderId           : 
LogName              : Application
ProcessId            : 
ThreadId             : 
MachineName          : WIN-SHSNAVDV03B
UserId               : 
TimeCreated          : 7/6/2016 7:13:02 AM
ActivityId           : 
RelatedActivityId    : 
ContainerLog         : application
MatchedQueryIds      : {}
Bookmark             : System.Diagnostics.Eventing.Reader.EventBookmark
LevelDisplayName     : Error
OpcodeDisplayName    : Info
TaskDisplayName      : Application Crashing Events
KeywordsDisplayNames : {Classic}
Properties           : {System.Diagnostics.Eventing.Reader.EventProperty, 
                       System.Diagnostics.Eventing.Reader.EventProperty, 
                       System.Diagnostics.Eventing.Reader.EventProperty, 
                       System.Diagnostics.Eventing.Reader.EventProperty...}
```

**Comment by StefanScherer** [comment]
@nicholasdille I have started with this [Dockerfile.windows](https://github.com/docker/docker/blob/master/Dockerfile.windows) to build the Docker Engine inside a Docker container. It evolved over the months, but Git is part of it since its beginning as golang also needs to clone some repos.

**Comment by StefanScherer** [comment]
And this is a smaller [Dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/master/golang/Dockerfile) with only Git and Golang. Worked for me as well.

**Comment by nicholasdille** [comment]
Thanks, @StefanScherer. Good to know that you got it working ... I'll close this issue but I may have to get back to you as soon as I look into your code!

**Comment by nicholasdille** [comment]
For documentation purposes, I'll let you know that the crash seems to be caused by Build 14300.1043 (updates as of now). I have posted a detailed description in the Microsoft Container forum: https://social.msdn.microsoft.com/Forums/en-US/76926957-2662-46c3-bd79-0df04ab7a358/git-does-not-work-in-new-container-with-kernel-build-143001043?forum=windowscontainers
