### ISSUE TITLE
The SDK doesn't include a man page viewer - so updated docs can't be checked

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#816]
- [ N] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
#696 is not quite the same as it's for the regular git, not the SDK.
#79 is about which asciidoc vs asciidoctor to use.
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

32 bit

Philip@PhilipOakley MINGW32 /
$ git version
git version 2.8.4.windows.1.3.ge328a54
- Which version of Windows are you running? 32-bit or 64-bit?

Win XP Sp3.  32 bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

bash only, defaults otherwise, for both SDK and regular G4W.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

no
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
Philip@PhilipOakley MINGW32 /
$ git help --man revisions
warning: failed to exec 'man': No such file or directory
fatal: no man viewer handled the request

```
- What did you expect to occur after running these commands?

a man viewer to come up, so that I can check if the patched documentation formats well 
e.g http://article.gmane.org/gmane.comp.version-control.git/299289 
- What actually happened instead?

fatal: no man viewer handled the request
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

n/a
# 

A recommendation as to the best viewer to integrate would be a great help. I'd be happy to take it from there.

**Comment by rimrul** [comment]
>A recommendation as to the best viewer to integrate would be a great help. I'd be happy to take it from there.

How about the classic [MSYS2 package `man`](https://github.com/git-for-windows/MSYS2-packages/tree/master/man)?

**Comment by PhilipOakley** [comment]
> How about the classic MSYS2 package  man ?

@rimrul Thanks. Though I may need some extra help getting it set up right for use with the SDK.

I'd initially got confused after close reading of #696 which mentions  mingw-w64-x86_64-git-doc-man (note it's under mingw, not msys2, or it would be if I could find it..) .

I did install the  MSYS2 package  man package, but than found I needed to set up some database, and even then (within the git SDK) it didn't appear to pick up the newly created man pages I thought I'd generated (I was trying to create some upstream man page patches, where a review mentioned that the man view wasn't right - normally I just check the regular generated g4w HTML).

The aim would be to include it with the SDK, and the git make file to 'just work' when generating documentation for viewing immediately view a `git help --man revisions` (to access the gitrevisions man page)

**Comment by rimrul** [comment]
I've had another look, and upstream also has a [`man-db` package](https://github.com/Alexpux/MSYS2-packages/tree/master/man-db) that claims to be a new and improved replacement for `man`. I've never installed `man` on any system or created my own `man` pages, though. [`man-db` seems to be a common choice](http://www.nongnu.org/man-db/) among linux distributions. It might be easier to set up.

**Comment by PhilipOakley** [comment]
@rimrul Thanks, I'll remove the man package I tried (and hopefully the mandb generated files IIRC). and then try installing man-db, and see what I get. It's a big learning curve!

**Comment by PhilipOakley** [comment]
@rimrul I had a look and it looks like pacman already installed the newer man-db package. That is, when I asked to remove 'man' it said it didn't have it, even though my history shows it loaded it - which tends to suggest there was a message I didn't read too closely saying that man-db was installed as being newer and better!

All I have to now is work out how the Git make file creates the man pages, where it puts then and how to get the man-db to pick them up.

**Comment by rimrul** [comment]
I tried some of this. `pacman -S man` really installs `man-db`. After `make install` I tried `git help --man add` and it claimed there's no man page for `git-add`, but `man git-add` works fine.

**Comment by PhilipOakley** [comment]
@rimrul Thanks for confirming that install issue, and even more for that tidbit that the `man git-add` works. I have in the past dug into the `git help` (I did the `-g` option to list the guides) so I'll have a look at how the `--man` option is invoked. Progress!

**Comment by PhilipOakley** [comment]
@rimrul PS. Did you check that `man` wasn't finding the regular git man pages, rather than those made via the SDK?

**Comment by rimrul** [comment]
Yeah, seems to be default git man pages. Still found them after a `make clean`, `mandb` and a reinstall of `man-db`.

**Comment by PhilipOakley** [comment]
> Yeah, seems to be default git man pages. Still found them after a make clean, mandb and a reinstall of man-db.

The `man -d <page>` looks to be the command to show all the gory search details, which I've still to look at properly.
--
Philip

**Comment by dscho** [comment]
So this ticket is all settled now?

**Comment by rimrul** [comment]
No it isn't we have to look at some details. I'll give you a more in depth response when I'm back home on Wednesday.



-------- Ursprüngliche Nachricht --------
Von: Johannes Schindelin
Datum:08.09.2016 9:48 (GMT+02:00)
An: git-for-windows/git
Cc: Matthias Asshauer ,Mention
Betreff: Re: [git-for-windows/git] The SDK doesn't include a man page viewer - so updated docs can't be checked (#816)


So this ticket is all settled now?

-

**Comment by PhilipOakley** [comment]
The extra thing (above and beyond including the `man-db` package into the SDK) will be to set the relevant MAN_PATH variable, and do the initial database of man-pages generation (which took some while for me). The last step may need some tweaking so that only a limited set of directories is considered so it runs quickly.

Sorry I didn't pursue it further.

**Comment by dscho** [comment]
Hmm. I just tested `man git` in an SDK I installed here for CI purposes and indeed, `man` is not installed. However, I never initialized any MANPATH manually, nor did I have to generate the man pages myself. Maybe that is done as part of `pacman -S base-devel msys2-devel`?

**Comment by dscho** [comment]
> Hmm. I just tested man git in an SDK I installed here for CI purposes and indeed, man is not installed.

Actually, what I meant was that there *is* a `man` executable installed.

In any case, maybe you want to clone the (newly published) [Git repository mirroring the 32-bit Git for Windows SDK](https://github.com/git-for-windows/git-sdk-32)?

**Comment by dscho** [comment]
I'll just close this ticket, as we now have something similar to the msysgit.git repository of the bad old Git for Windows 1.x days (with the major difference that git-sdk-32.git is a *mirror* of a fully populated MSYS2 setup modified to develop Git for Windows).

Maybe somebody with a little more time than myself can document on the wiki/website that you can initialize your own copy of the SDK via `git clone --depth=1 https://github.com/git-for-windows/git-sdk-64` (or `...-32` for 32-bit)...

**Comment by PhilipOakley** [comment]
----- Original Message -----

**Comment by dscho** [comment]
@PhilipOakley thanks! I guess we should also update the Git for Windows home page to suggest cloning the SDK instead of using the installer, eh?
