### ISSUE TITLE
About Notepad, COMMIT_MESSAGE with Cyrillic chars, UTF-8 and BOM

### ISSUE THREAD

**Issue by dimztimz** [git-for-windows/git#818]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

Tested on 2 versions: portable version that comes with Github for Windows (2.8.1) and latest 64 bit Git 2.9

```
$ git --version
git version 2.8.1.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 10 x64

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
core.editor=notepad
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Tested with CMD and Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init
echo Hello world! > hello.txt
git add .
git config --global core.editor notepad
git commit
<Notepad opens, i write
Здраво
i save and exit>
```

 - What did you expect to occur after running these commands?

A successful commit with message `Здраво`

 - What actually happened instead?

I get a commit with messge ```Çäðàâî```

This is the output

```
unix2dos: converting file D:/repo/.git/COMMIT_EDITMSG to DOS format...
dos2unix: converting file D:/repo/.git/COMMIT_EDITMSG to Unix format...
Warning: commit message did not conform to UTF-8.
You may want to amend it after fixing the message, or set the config
variable i18n.commitencoding to the encoding your project uses.
[master (root-commit) 48a2b6f] Çäðàâî
```

### Solution

The thing is that when commit is initiated this happens:

1. Git creates file COMMIT_MESSAGE encoded in utf-8 without BOM and contains only Latin characters with codes smaller than 128. Such file is actually compatible with many 1 byte encodings.
2. Notepad opens the file. Because every char is single byte, Notepad detects it as some of the old ANSI related 1 byte encodings and it opens it in that one, in my case it is Windows-1251. It probably check the option under regional settings.
3. I write Cyrillic letters and i save. Since the file was opened in ANSI mode it is also saved in ANSI mode, more precisely in Windows-1251.
4. Git tries to read the file as UTF-8. Bad things happen.

The solution is COMMIT_MESSAGE to be generated with UTF-8 with BOM. This way Notepad is forced to open the file in UTF-8 and save it in the same mode. After that git should ignore the first three bytes (the BOM).

This is what gitpad does. When gitpad is configured as editor, it opens the COMMIT_MESSAGE, reads it as UTF-8, writes a temp file as UTF-8-BOM with CRLF line endings, opens the temp file with notepad and waits. After notepad exits, gitpad rewrites the temp file to COMMIT_MESSAGE as UTF-8 with LF line endings.

ATM there are actually those 2 tools, unix2dos and dos2unix. The first tool should add the BOM and that's all. The second tools seems to strip the BOM succesfully.

**Comment by fourpastmidnight** [comment]
Did you try explicitly saving the commit message as UTF-8?

For example, when issuing `git commit` which opens notepad, after typing your commit message, choose **File | Save as...**. In the **Save as...** dialog, there's an **Encoding** dropdown box. Choose _UTF-8_ and the click **Save**. Then, press <kbd>ALT+F4</kbd> to close notepad.

Does this resolve the issue?

**Comment by fourpastmidnight** [comment]
Well, I just tried it out. It does _not_ resolve the issue.

**Comment by rimrul** [comment]
>ATM there are actually those 2 tools, unix2dos and dos2unix. The first tool should add the BOM and that's all. The second tools seems to strip the BOM succesfully.

I think `unix2dos` and `dos2unix` mainly care about line endings.

**Comment by dimztimz** [comment]
> Did you try explicitly saving the commit message as UTF-8?
> 
> For example, when issuing git commit which opens notepad, after typing your commit message:
> 
>     Choose File | Save as....

This procedure works. I tried this one before I posted the issue but I skipped the third step and Notepad added .txt to the filename.

--------

> I tried this, but it didn't seem to work; but this may be because my language settings are en-US

Language settings should be irrelevant when saving in utf-8 or utf-16 in notepad.

-------

> I think unix2dos and dos2unix mainly care about line endings.

New versions of those tools have some BOM related options, -m -b and -r.
```
unix2dos --help
-b, --keep-bom        keep Byte Order Mark (default)
-m, --add-bom         add Byte Order Mark (default UTF-8)
-r, --remove-bom      remove Byte Order Mark


dos2unix --help
-b, --keep-bom        keep Byte Order Mark
-m, --add-bom         add Byte Order Mark (default UTF-8)
 -r, --remove-bom      remove Byte Order Mark (default)
```

**Comment by dimztimz** [comment]
For a complete solution, one should take into consideration the variable `i18n.commitencoding` of `git config`, see the section Discusion here: https://git-scm.com/docs/git-commit .

I've searched and as I see only one file in build-extra should be modified, https://github.com/git-for-windows/build-extra/blob/master/git-extra/notepad

The fix should be the following:
```
if i18n.commitencoding is unset or set to utf-8
    call unix2dos -m
else
    call unix2dos
```

**Comment by fourpastmidnight** [comment]
> Language settings should be irrelevant...

Well, that's not necessarily true. IIRC, `git log` output is run through the `less` pager, which is impacted by the setting of `LANG` primarily (and if that's empty, then `LC_*`). If your `LANG` environment variable value is set incorrectly, then this _could_ have an impact. However, by default, I believe it's set to `en_US-utf8`--in which case, you would be correct, this should not have any relevancy to the problem at hand.

Now, with respect to BOM, I think that's a red herring. BOM only helps readers know the byte order of the Unicode surrogate code points in a UTF-8 or UTF-16 file. The real issue seems to me to be that the encoding of the commit message file is not correct on saving the file or, upon reading the commit message, the encoding used to read the file is wrong. Now, since git by default reads commit messages as UTF-8, I am suspect of the original encoding of the commit message that git ultimately stored.

You mentioned you didn't do step 3 in my procedure above. That's actually pretty important; I made the same mistake. If you don't do step 3, then notepad will save the file as `COMMIT_EDITMSG.txt` instead of `COMMIT_EDITMSG`, and either no message will be saved, aborting the commit, or if amending, the amended message will not be saved and the original will be used as is (because it never changed because your changes were saved to a different file).

Please try my steroids exactly and see if that resolved the issue. Thanks.

**Comment by dimztimz** [comment]
> You mentioned you didn't do step 3 in my procedure above.

I tried without step 3 and with step 3. The second time it worked. So yes, we have a workaround which is not very user-friendly.

It would be nice to have more lean out of the box experience. The solution I proposed in the previous post, modifying the sh script is fine solution. It is notepad specific, it won't affect other editors.
