### ISSUE TITLE
Use continuous integration to test pull requests

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#82]
@sschuberth mentioned at Git Merge that it would be a good idea to use continuous integration to test Pull Requests automatically (much like CloudBees does, but using Windows to build and test instead of Linux).

This would throw the door wide open for cool new stuff even for crazy things like continuous releases (i.e. automatic deployments of packages to the Pacman repository and even of end user installers of Git for Windows).

**Comment by weakcamel** [comment]
As @sschuberth has provided me with installer from CI, I'm guessing it's already in place?

**Comment by sschuberth** [comment]
Basic CI jobs are in place, however they are not hooked up to GitHub pull requests, which is what this issue is about.

I'm anyway in the process of considering AppVeyor instead of our Jenkins for CI now as I cannot count on the VM running Jenkins anymore.

**Comment by weakcamel** [comment]
I see. If for some reason we stay with Jenkins, I can lend my hand.
Of course only if you need me to.

**Comment by sschuberth** [comment]
@weakcamel Thanks for the offer, but I think Jenkins-expertise-wise we're fine ;-)

**Comment by weakcamel** [comment]
@sschuberth Cool :-)

**Comment by dscho** [comment]
The Jenkins jobs still leave room for improvement: they are deliberately wasteful with resources (pretty much nothing is incremental, preventing me from using them to make new releases because I am substantially faster releasing manually), they do not update using pacman beforw bui

**Comment by sschuberth** [comment]
> they are deliberately wasteful with resources

They are not in general deliberately wasteful on resources, but they are deliberately non-incremental. The primary goal of CI builds is not to be faster than local builds, but to be automated and deterministic, with full access to all logs. Incremental builds introduce the risk of a problem because something did not get compiled, and it also has the risk of not being able to recreate a build.

In other words, CI is a tool to help improve and maintain the quality of the software. It's not a tool to speed up or distribute builds.

> they do not update using pacman before building the packages

If you want that (which I agree would make sense) that should be part of the release scripts as another good practice is to not let manual and CI builds diverge too much.

> they cannot build installers based on the `master` branch

`master` branch of which repository? For `git-for-windows/build-extra` for sure they can, and for `git-for-windows/git` too, it's just that pacman packages do not yet get automatically built and uploaded. That's more advanced stuff, and I first wanted to see how the basic jobs gain credence. But as there seems to be no appreciation for the work I've done so far I guess I'll spend my time otherwise.

**Comment by dscho** [comment]
> They are not in general deliberately wasteful on resources, but they are deliberately non-incremental.

Sorry, I should have really spent that extra two minutes to clarify that the Jenkins jobs are deliberately non-incremental, implying that they require more resources than my poor VM can afford right now. Thanks for clarifying that for me.

> The primary goal of CI builds is not to be faster than local builds, but to be automated and deterministic, with full access to all logs

As far as my work is concerned, the primary goal of CI is to help development. If it can do so by being automated and deterministic, with full access to all logs, all the better. If that automation and resource spending interferes with the project's *development*, however, it is not helping, it is interfering. At this point, I am still in the phase where I stumble over problems *only* because I use the software myself, interactively. That would simply not be possible using *only* Jenkins jobs. And it is *unnerving* how slow my main development VM becomes when even one of those non-incremental jobs runs, which is why I had to disable it. This is an imperfect world, and we have to make the best of it, and I did.

> another good practice is to not let manual and CI builds diverge too much.

Actually, the good practice *is* to let CI make the builds. As it is, I still have to spend a lot of time to whip the Jenkins jobs into helping my development, and I simply do not have that time right now because there are still open issues which need to be addressed, and there are still so many discussions I have to participate in, such as this here discussion. It is a matter of priorities, and the CI really excels at a later stage of the project while it simply has to wait right now.

> > they cannot build installers based on the master branch
> 
> master branch of which repository?

Is it not obvious that I meant *all* of our repositories? I mean, we are here, on the issue tracker, knowing fully well, that the resolutions require commits to solve the problems reported here, and those commits do not always necessarily go into `git.git`, but sometimes we need to adjust the `PKGBUILD` of `git-extra` (`build-extra.git`), sometimes we need to patch up the `msys2-runtime` (both `msys2-runtime.git` and `MSYS2-packages.git`), sometimes we need to patch cURL (`MINGW-packages.git`), etc.

Now, in many cases (actually, almost all of the fixes I provided in the past two weeks) we cannot test those fixes in an automated way. Certainly not without some manual setup as to compiling packages and then building new installers using those temporarily forked packages.

It would have been nice, of course, to have a CI in place where I basically just hit a couple of checkboxes to make a new installer. It would be nice, of course, to have a development machine that is fast enough that I can do all of that completely non-incrementally, from scratch, without interfering with my fixing the next bug because the CPU is bogged down to a halt. But pigs cannot fly, wishes are not horses, beggars don't ride.

> it's just that pacman packages do not yet get automatically built and uploaded.

Yes, that would be *HORRIBLE*! To upload pacman packages before they are tested, just *so* they can be tested? That is a terrible, terrible idea.

> But as there seems to be no appreciation for the work I've done so far I guess I'll spend my time otherwise.

You are free to spend the time as you wish, of course. I would have wished that you had tackled other problems where I could have used your help much more. We cannot change the past, we can only change the future, and only on our side.

By not assigning this ticket to yourself, you have made clear your priorities, and that's fine. I will take it from here. Thanks for all of your past contributions to the *Git for Windows* project, and I hope that you will occasionally contribute fixes for problems you encounter yourself.

**Comment by sschuberth** [comment]
> Actually, the good practice is to let CI make the builds.

Build for (snapshot) releases, yes. Builds for developers to use / debug on, no.

> Is it not obvious that I meant all of our repositories?

No. Otherwise I wouldn't have bothered to ask.

> To upload pacman packages before they are tested, just so they can be tested? That is a terrible, terrible idea.

Well, of course (in an enterprise-like setup) they would first get uploaded to some staging area for testing, and then promoted once found to be good.

> I hope that you will occasionally contribute fixes for problems you encounter yourself.

I'll certainly do that. Thanks, and farewell.

**Comment by weakcamel** [comment]
Ouch. Now I wish I hadn't asked :-(
I hope that will not be a permanent decision; in any case, @sschuberth thank you for your support here to keep me going/started. I really appreciate it.

**Comment by dscho** [comment]
I will try to find some time to set up some Jenkins jobs myself that work well with the VM that I still use heavily for development.

**Comment by dscho** [comment]
We have to be realistic. Testing Pull Requests via Continuous Integration would be worth it only if we
1. get many Pull Requests, and
2. have somebody competent and motivated to work on the Continuous Integration part.

But we do not get many Pull Requests, and I do think that my time is spent much better elsewhere than to set this up (I also do not have a machine to spare, so it would have to be a very gentle-load solution running in my Azure VM).

Therefore I'll just close this.

**Comment by shiftkey** [comment]
@dscho :thumbsup: as someone who has spent a non-trivial amount of time building Git for Windows in the past, I'm fine with leaving this until there's significant pain...
