### ISSUE TITLE
the http proxy config is not work since the password has special chars 

### ISSUE THREAD

**Issue by dicolancy** [git-for-windows/git#821]
### Setup
git version 1.9.5.msysgit.1

### Details

 i've got a problem when i trying to config http proxy for git in Bash 
  with username and password which includes some special chars such as '@',
   can you give me some advice?

    example cmd: `git config http.proxy http://username:123@456@proxyserver:port` ,
   the password is "123@456" in this example.
   
  
thanks for your efforts, and look forward to your reply.

**Comment by BladeMight** [comment]
encode them as they encodes in http

**Comment by dscho** [comment]
Indeed, URL-encoding the special characters [should work](http://www.cyberciti.biz/faq/unix-linux-export-variable-http_proxy-with-special-characters/). In the above-mentioned example:

```sh
git config http.proxy http://username:123%40456@proxyserver:port
```
