### ISSUE TITLE
Windows 10 Compatibility Issue?

### ISSUE THREAD

**Issue by bstarostka** [git-for-windows/git#824]
Version:  Git for Windows version 2.9.0

Output:  git version 2.9.0.windows.1

Windows:  Windows 10 64-bit

Install Steps:

Selected "Run Git from the Windows Command Prompt" and "Checkout Windows-style, commit Unix-style endings" as part of the installation...the remaining options were the default options

Environment Details:

Using TortoiseGit version 2.1.0.0
Intel HD Graphics 5500, driver version 10.18.15.4256
Symantec Endpoint Protection
BitLocker Drive Encryption

Issue Details:

Our data integration team uses TortoiseGit with Bitbucket as our remote repository.  Two members of the team recently got new laptops with Windows 10 and after installing TortoiseGit and Git they were able to push/pull/commit/etc. without any issues.  After a day or two (no pattern noticed), they are unable to push/pull/commit/etc. as they get the following:

_warning: invalid credential line:  [0x7FFB463CFD50]  ANOMALY:  meaningless REX prefix used_

Once the issue begins and they navigate back to the version information they see the following:

_TortoiseGit 2.1.0.0 (C:\Program Files\TortoiseGit\bin)
[0x7FFB463CFD50] ANOMALY: meaningless REX prefix used
[0x7FFB463D2F90] ANOMALY: meaningless REX prefix used
git version 2.9.0.windows.1_

They also see the same strange syntax when opening Windows PowerShell:

_[0x7FFB463CFD50] ANOMALY: meaningless REX prefix used
[0x7FFB463D2F90] ANOMALY: meaningless REX prefix used
Windows PowerShell_

The only solution to the problem is restarting their computer.  Once they restart, they usually only get a day or two at most before the issue returns.

The strange part is that none of our team members using Windows 7 have ever experienced these issues so I'm not certain if perhaps it's related to Windows 10, the graphic cards they are using (see details above) or BitLocker (the Win7 machines use Symantec Encryption Desktop).

Any insight at all would be greatly appreciated as we are struggling to crack the code.  If you need any additional information, please let me know.

Thanks for the assistance!

**Comment by whoisj** [comment]
Sounds like a bug in TortoiseGit and not Git for Windows.

Also, any chance the Win7 installations were 32-bit while the Win10 installations are 64-bit?

**Comment by bstarostka** [comment]
Possibly, I've opened an issue with GitLab to specifically review TortoiseGit as well.

And yes, the Git for Windows Win7 installations are 32-bit while the Win10 installations are 64-bit.

**Comment by whoisj** [comment]
> And yes, the Git for Windows Win7 installations are 32-bit while the Win10 installations are 64-bit.

I asked that, because while I don't know a ton about assembly, I vaguely remember REX having to do with long address or something like that. Seems that a 32-bit application attempting to use REX on a 64-bit OS might run into conflicts. Again, not my area of expertise. :smirk:

**Comment by bstarostka** [comment]
I might have misunderstood your question as the Win10 users who are experiencing the issue have a 64-bit OS and both TortoiseGit and Git for Windows are 64-bit applications.

**Comment by dscho** [comment]
@bstarostka an MCVE is really necessary for others to help. To provide one, you need to narrow down where the issue comes from, i.e. try to skip TortoiseGit, try to push pull against a local repository, etc.

It is just a little bit too much to ask others to chase geese...

**Comment by bstarostka** [comment]
C'mon, who doesn't like to chase geese?  ;-)

Sadly, I'm not certain I can provide an MCVE as we are struggling to narrow down where the issue is coming from.  I was hoping that perhaps someone has seen this issue before and could help us point us in the right direction but we aren't having much luck in any forum.  It's also challenging not having the issue on my computer so I can't quite troubleshoot and monitor things as I'd like.

**Comment by dscho** [comment]
@bstarostka C'mon, you cannot even try to reproduce using the command-line? Using other repositories? With Symantec disabled? Etc etc etc

**Comment by bstarostka** [comment]
We will definitely try to reproduce using other methods and by removing some of the variables (if we can).  Unfortunately, some of the programs (e.g. Symantec) are very locked down by Corporate so our troubleshooting options may be somewhat limited but we'll certainly explore everything we can.  We've got a TS session setup for Monday and I'll make sure to send out an update afterwards.

**Comment by jeffhostetler** [comment]
FWIW, the text "ANOMALY: meaningless REX prefix used" has lots of hits in a google search in a wide variety of applications -- but they were generally in the direction of a video driver issue.  I've not personally experienced it, but it may be worth doing a broader search than assuming it is strictly a Git for Windows or Tortoise Git issue.

**Comment by bstarostka** [comment]
Certainly not making any assumptions @jeffhostetler, just trying to explore everything we can.  We dug through a ton of the google search results but didn't have much luck.  We also had some troubleshooting sessions with our corporate desktop support team specifically focusing on the video card driver but unfortunately didn't make any progress.

**Comment by dscho** [comment]
@bstarostka you need to drill down by eliminating possible causes, as I mentioned earlier. The simplest thing to try is the command-line, taking TortoiseGit out of the picture. You do not need IT's approval for that.

**Comment by whoisj** [comment]
> @bstarostka you need to drill down by eliminating possible causes, as I mentioned earlier. The simplest thing to try is the command-line, taking TortoiseGit out of the picture. You do not need IT's approval for that.

I second this. My point was that it is most likely a TortoiseGit issue as REX generally pertains to graphics, and Git doesn't really use any graphics (it's a command line application after all).

**Comment by bstarostka** [comment]
Understood gentlemen, thanks for the insight.

**Comment by fourpastmidnight** [comment]
In case any one comes here looking at this issue, I too, just today, experienced this issue. The one thing _I know for sure to be true_ is that this is _definitely video driver related_. I recently updated my NVidia GeForce drivers from 368.x to 373.06, and now 375.x. Since the update from 368.x, I've had nothing but problems. I can't hibernate my laptop anymore (it just crashes on next boot). With respect to Git for Windows, I just issued a simple `git status` command and got `[0x7FFFFCB170E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)`.

**Comment by freyzheng** [comment]
I meet the same problem.

`C:\Windows\System32>git --version
[0x7FFAEF6BD3B0] ANOMALY: meaningless REX prefix used
[0x7FFAEF6BD3B0] ANOMALY: meaningless REX prefix used
git version 2.30.0.windows.2`

it leads to a error in IDEA when indexing a project.
