### ISSUE TITLE
Cloning bash-completion fails with "fatal: cannot create directory at ..."

### ISSUE THREAD

**Issue by imgx64** [git-for-windows/git#828]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup
 - git 64-bit, `git version 2.9.2.windows.1`
 - Windows 10 Enterprise 64-bit
 - Default install. Installed via Chocolatey.

### Details

Cloning https://github.com/scop/bash-completion.git produces the below error. Tried with "Git Bash Here" and "Git GUI Here".

```
$ git clone 'https://github.com/scop/bash-completion.git'
Cloning into 'bash-completion'...
remote: Counting objects: 22529, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 22529 (delta 2), reused 0 (delta 0), pack-reused 22519
Receiving objects: 100% (22529/22529), 3.27 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (16332/16332), done.
Checking connectivity... done.
fatal: cannot create directory at 'test/fixtures/_filedir/a"b': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Retrying with `git checkout -f HEAD` produces the same error.

Interestingly, I could clone this repository with Cygwin's version of git. But when I tried to run Git for Windows in that directory, I get the below output (Cygwin git says `nothing to commit, working directory clean` instead):
```
$ git status
test/fixtures/_filedir/a"b/d: Invalid argument
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   doc/bashrc
        modified:   doc/inputrc
        modified:   doc/makeHtml.sh
        modified:   extra/make-changelog.py
        deleted:    test/fixtures/man/man3/Bash::Completion.3pm.gz
        modified:   test/fixtures/mount/bin/showmount
        modified:   test/fixtures/shared/bin/arp
        modified:   test/fixtures/shared/bin/ifconfig
        modified:   test/generate
        modified:   test/run
        modified:   test/runCompletion
        modified:   test/runInstall
        modified:   test/runLint
        modified:   test/runUnit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "test/fixtures/_filedir/a\357\200\242b/"
        "test/fixtures/man/man3/Bash\357\200\272\357\200\272Completion.3pm.gz"

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by dscho** [comment]
Quotes are not legal as parts of file names on Windows. Cygwin uses a dirty trick by mapping invalid characters into the "private" page of Unicode characters. It won't work with any real Windows program, though, you really can only work within Cygwin if you use such file names.

In short, this file name *is* invalid on Windows.

FWIW the subject line is a little misleading: it is not the `clone` of said repository per se that is failing, but rather the `checkout` of its current tip of its `master` branch.
