### ISSUE TITLE
install blocked by avg behaviour detection

### ISSUE THREAD

**Issue by kitsguru** [git-for-windows/git#830]
install is blocked - using a fresh download of the installer

### Setup

Trying to install git-2.9.2-64-bit.exe on Windows 7-64bit with Avg antivirus free edition with recent virus database. Throws a behavior detection error on git-2.9.2-64-bit.tmp

**Comment by shiftkey** [comment]
@kitsguru can you provide specific details of:

 - the AVG Antivirus product you're using 
 - the antivirus database version
 - what it claims to have found

**Comment by kitsguru** [comment]
AVG Antivirus Free Edition
V 19.91.7688
AVG Zen version 1.72.2.24716
Database version 4627/12656 (21/07/2016, 10:31AM)

Identity protection originally reported git.exe was infected (Behaviour Detection) - clicked on the link referred to a generic virus. It then removed git.exe.
I attempted to reinstall from the download I saved earlier this week and the install was blocked with the same error (Behaviour Detection).
I then deleted the entire folder and previously downloaded installer and re-downloaded a fresh copy. The install was blocked again.

A complete scan of the computer using AVG as specified above reports no threats found but the install is still blocked.

AVG also reported my Sublime Text was infected and deleted that as well. A reinstall of Sublime went without incident. The only two applications I ran this morning were sublime text and git.

StopZilla found 44 threats and removed them all. Everything was clean yesterday. 

Threats only showed with new virus and malware databases today.

**Comment by dscho** [comment]
This sounds more like a serious bug in AVG to me, than a problem of Git for Windows.

**Comment by dscho** [comment]
And it seems that even AVG disagrees with your report, based on the output of Virus Total: https://www.virustotal.com/en/file/006d971bcbe73cc8d841a100a4eb20d22e135142bf5b0f2120722fd420e166e5/analysis/1469175955/

**Comment by kitsguru** [comment]
The total virus report is on the portable version not the desktop install. When I install the desktop version, And only after installing this, I am infected across many .exe files. Spotzilla then finds major threats. So it is not just AVG that is reporting an issue.

Is it possible the desktop version of the installer has been infected but not the portable one?

**Comment by kitsguru** [comment]
Is there a link to older versions of the installer?

**Comment by kitsguru** [comment]
Git-2.9.0-64-bit.exe installs fine so I switched back to it.

**Comment by dscho** [comment]
> The total virus report is on the portable version not the desktop instal

No, it is not. It says

```
SHA256: 	006d971bcbe73cc8d841a100a4eb20d22e135142bf5b0f2120722fd420e166e5 
File name: 	Git-2.9.2-64-bit.exe
```

Please note that the SHA256 matches *precisely* the one from https://github.com/git-for-windows/git/releases/tag/v2.9.2.windows.1(and not of the PortableGit, but of the Git installer).

> Is it possible the desktop version of the installer has been infected but not the portable one?

Absolutely not. I prepare these installers in a VM that is used for nothing else. The *very same* files are included in the portable version as are in the desktop version. If you do not believe me, simply run the files through a checksummer of your choice.

> Git-2.9.0-64-bit.exe installs fine so I switched back to it.

It that is satisfactory for you, please close this ticket.

**Comment by kitsguru** [comment]
I agree that the sha256 matches, didn't see that until I looked at the releases. My apologies. 

Using 2.9.0 for now is satisfactory. I ran the sha256 generator against the copies I have downloaded and they both match your published versions. Must be a false positive from AVG. Still unclear as how I got infected though. I am clean now so all is good.

**Comment by dscho** [comment]
> I ran the sha256 generator against the copies I have downloaded and they both match your published versions.

I meant checksumming the contents of the installers.

> Must be a false positive from AVG. Still unclear as how I got infected though.

Well, it is either a false positive, or you got infected. Can't be both.

**Comment by kitsguru** [comment]
Actually it can be both. I was infected with several different threats and now am clean according to scans today. I still can't install 2.9.2 as AVG blocks it.

**Comment by kitsguru** [comment]
None of the scans indicate that the installer is infected but it is still prevented from performing the installation. This is outside my scope. Could you try setting up a VM with AVG and trying an install?

**Comment by dscho** [comment]
@kitsguru I am not a customer of AVG. So even if I did as you ask me to, even if I had the time to do so, what would be the use? AVG would not listen to me.
