### ISSUE TITLE
File name too long during (initial) checkout

### ISSUE THREAD

**Issue by GyrosGeier** [git-for-windows/git#831]
Hi,

I'm building Boost from Jenkins, and am getting an error during the initial checkout:

    error: unable to create file doc/html/boost_regex/background_information/performance/section_Testing_simple_leftmost_longest_matches_platform_Windows_x64_compiler_Microsoft_Visual_C_version_14_0_.html: Filename too long

This problem goes away with the next checkout for some reason, probably because parts of the path now already exist and git uses a shorter name to create the file.

### Setup

 - git is being called from a Jenkins slave, extracting the boost submodules:

```
$ git --version
git version 2.9.0.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Windows 7 SP1 64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The base directory already has a fairly long name.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

This is running from a .bat file under cmd.exe.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
    md C:\Jenkins\workspace\windows-boost-msvc\build\release\cpu\amd64\label\windows
    git init C:\Jenkins\workspace\windows-boost-msvc\build\release\cpu\amd64\label\windows
    cd C:\Jenkins\workspace\windows-boost-msvc\build\release\cpu\amd64\label\windows
    git -c core.askpass=true fetch --tags --progress https://github.com/boostorg/boost.git +refs/heads/*:refs/remotes/origin/*
    git config remote.origin.url https://github.com/boostorg/boost.git
    git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    git checkout -f a89d865a504c59a0fea96ffbb22bd983da470104
    git submodule init
    git submodule sync
    git submodule update --init --recursive

```
 - What did you expect to occur after running these commands?

Fully unpacked Boost source tree

 - What actually happened instead?

Error message from git about being unable to create a file because the file name is too long

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

    https://github.com/boostorg/boost.git

**Comment by dscho** [comment]
Have you experimented with the `core.longpaths` config setting, as suggested by [our release notes](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues) and [our FAQ](https://github.com/git-for-windows/git/wiki/FAQ#i-get-errors-trying-to-check-out-files-with-long-path-names)?

**Comment by GyrosGeier** [comment]
Seems to work, thanks!

**Comment by piercerob** [comment]
have you tried long path tool? it can help.

**Comment by dscho** [comment]
Please don't listen to that "long path tool" spam.
