### ISSUE TITLE
Shortlog is hanging

### ISSUE THREAD

**Issue by Djabx** [git-for-windows/git#834]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

```
$ git --version
git version 2.9.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Running on windows 7 64bits

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Default.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope...

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cd <not a git repo>
git shortlog
```
 - What did you expect to occur after running these commands?

Tell me there is an error because it's not a git repository.

 - What actually happened instead?

The command is hanging forever.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Nope, any directory witch is not a git repo.

**Comment by dscho** [comment]
This is actually by design. Outside of any Git repository, `git shortlog` expects you to provide a commit log via `stdin`. See for yourself in the help (via `git help git-shortlog`):

> If no revisions are passed on the command line and either standard input is not a terminal or there is no current branch, git shortlog will output a summary of the log read from standard input, without reference to the current repository.

It actually even says so, but the `(reading log message from standard input)` message is hidden by the pager. If you run `git --no-pager shortlog`, you will see actually it.

**Comment by Djabx** [comment]
Oups sorry about that !
And thnaks for your answer !
