### ISSUE TITLE
Fresh install does not find git in path, forces use of git.exe

### ISSUE THREAD

**Issue by seanfdnn** [git-for-windows/git#838]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

MINGW64 would not recognize git command. Uninstalled git, manually checked environment variables, re-installed Git for Windows fresh. Issue persists. 

### Setup

 - 64 bit 2.9.2.windows.1
 - Default options. Tried uninstalling and reinstalling with and without in windows path. 

### Details

 - Using MINGW64

Some commands I ran:

$ git version
Error connecting to agent: Protocol wrong type for socket
bash: /usr/bin/git: No such file or directory

$ git.exe version
git version 2.9.2.windows.1

$ git
Error connecting to agent: Protocol wrong type for socket
bash: /usr/bin/git: No such file or directory

$ where git
C:\Program Files\Git\mingw64\bin\git.exe

$ which git
/mingw64/bin/git

$ echo $PATH
/c/Users/Sean/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Sean/bin:/c/Program Files/Java/jdk1.7.0_60:/c/ant/bin:/c/Program Files/Common Files/Microsoft Shared/Windows Live:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/python27:/c/python27/scripts:/c/Program Files (x86)/QuickTime/QTSystem:/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:/c/Program Files/Docker Toolbox:/usr/bin/vendor_perl:/usr/bin/core_perl

$ git.exe clone https://github.com/rmccue/test-repository.git
Cloning into 'test-repository'...
remote: Counting objects: 9, done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 9
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.

**Comment by dscho** [comment]
Do you maybe have an alias named `git`? If these commands were run in *Git Bash*, try `set -x` and/or `export GIT_TRACE=1` to diagnose further.

**Comment by cchan** [comment]
Also, try running `which git --all`.

**Comment by dscho** [comment]
No feedback -> closing.
