### ISSUE TITLE
Unable to add symlinked directorty to the index

### ISSUE THREAD

**Issue by spacemonkey1337** [git-for-windows/git#839]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Git 
    - 1.9.5.msysgit.1
    - 2.9.2.windows.1 64-bit
    - 2.9.2.windows.1 32-bit

 - Fresh installation with default options

 - Windows 10 Pro 64-bit

### Details

 - Using Bash

 - Scenario

  ```
1. Create new empty working dir
2. Make symlink inside this dir (mklink /d "symlink-test" "c:\path\to\outside\dir")
3. Open bash in working dir
4. Init git repository (git init)
5. Add linked directory to the index (git add symlink-test/)
  ```

 - Results

  - 1.9.5.msysgit.1

    All contents of "symlink-test" dir added to the index as expected.

  - 2.9.2.windows.1 64-bit and 2.9.2.windows.1 32-bit

    Error:

    ```
error: readlink("symlink-test"): Function not implemented
error: unable to index file symlink-test
fatal: adding files failed
    ```

**Comment by fourpastmidnight** [comment]
By default, for a while now, the setting `core.symlink` is set to `false` when you install Git For Windows. Try setting that to true, either in the local repo or globally, and see if that resolved your issue.

**Comment by spacemonkey1337** [comment]
In 2.9.2 if `core.symlink` is set to `true` then symlinks will be added to index as a file, but not as a directory.

**Comment by spacemonkey1337** [comment]
If `core.symlink` is set to `true` in 2.9.2 then symlink treated as a file, not as a directory.

**Comment by dscho** [comment]
@spacemonkey1337 that is exactly how the symlink support is intended to work.
