### ISSUE TITLE
Specific repository fails to be cloned / have a working tree.

### ISSUE THREAD

**Issue by VitorCBSB** [git-for-windows/git#843]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 64-bit.

```
C:\Users\Vitor Coimbra>git --version
git version 2.9.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 64 bit.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 Defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Maybe? My home directory has a space character in it. This has actually broken a surprising amount of projects, I wouldn't be surprised if this had anything to do with the issue I'm experiencing.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 CMD.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone --recursive https://github.com/ucsd-progsys/liquidhaskell.git
```
 - What did you expect to occur after running these commands?

 A normal clone with initialized submodules.

 - What actually happened instead?

 Full output of what was shown:
````
C:\Users\Vitor Coimbra>git clone --recursive https://github.com/ucsd-progsys/liquidhaskell.git
Cloning into 'liquidhaskell'...
remote: Counting objects: 49574, done.
remote: Compressing objects:  57% (117/204)   R
remote: Compressing objects: 100% (204/204), done.
rRemote: Total 49574 (delta 91), reused 0 (delta 0), pack-reused 49353
Receiving objects: 100% (49574/49574), 20.20 MiB | 2.01 MiB/s, done.

Resolving deltas: 100% (29556/29556), done.
Checking connectivity... done.
error: unable to create file benchmarks/wouter-swierstra-xmonad-7715ec2/src/Aux.v: No such file or directory
error: unable to create file tests/logs/regrtest_results_goto_Fri_Sep_21_17:19:54_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Mon_Feb__4_08:25:21_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Mon_Oct_22_15:45:04_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Mon_Oct_22_20:52:56_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sat_Feb_23_18:38:19_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sun_Jan_13_17:11:09_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sun_Jul_13_22:12:12_2014_post_errormsg_parseparens: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sun_Oct_28_17:24:34_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Wed_Nov_20_15:28:50_2013-master: Invalid argument
error: unable to create file tests/logs/regrtest_results_nikiL_Fri_Mar_29_12:56:37_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Fri_Jul_29_17:38:55_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Mon_Dec__5_03:32:39_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Sun_Sep_11_15:52:57_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Sun_Sep_11_19:38:55_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Sun_Sep_11_20:12:06_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Thu_Dec_22_02:51:46_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Tue_Jul_19_10:07:18_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_03:11:45_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_03:14:29_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_16:45:26_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_18:09:31_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_18:42:19_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_19:13:26_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_19:14:10_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Sep__7_14:45:19_2011: Invalid argument
Checking out files: 100% (2405/2405), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'


C:\Users\Vitor Coimbra>
````

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 [LiquidHaskell](https://github.com/ucsd-progsys/liquidhaskell).

**Comment by PhilipOakley** [comment]
The second and subsequent errors are due to having the colon (:) character in the filenames e.g. `tests/logs/regrtest_results_goto_Fri_Sep_21_17:19:54_2012` which are simply invalid Windows filenames.

No exactly sure what the first error is caused by.

**Comment by dscho** [comment]
> error: unable to create file benchmarks/wouter-swierstra-xmonad-7715ec2/src/Aux.v

The name `AUX` is invalid on Windows, even with a suffix `.V`.

Together with the issues @PhilipOakley correctly identified, this means that the file names tracked in that repository are simply illegal on Windows.

If you want to work around it, you have a couple of options:
- use Cygwin's Git (which emulates the file names; the actual filenames use a private Unicode page and are only really usable from within Cygwin, which may be enough for your use case)
- use the sparse checkout feature (see https://git-scm.com/docs/git-read-tree for details)
- use Bash on Ubuntu on Windows (available in Windows 10 through the Anniversary Update, your report failed to include the Windows version, so I do not know whether you have access to that)

**Comment by whoisj** [comment]
Please see the list of [forbidden file and folder names on Windows](https://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/).

The file "aux" is the problem. There's a good chance that Bash on Ubuntu on Windows won't allow for the AUX file (not sure if this is a file system or shell limitation). If that's the case, sparse-checkout is your best friend.

**Comment by dscho** [comment]
> There's a good chance that Bash on Ubuntu on Windows won't allow for the AUX file (not sure if this is a file system or shell limitation).

I just tested this, and Bash on Ubuntu on Windows allows it.

FWIW it is a shell limitation, the file system does not have that restriction. Which means that you can use Bash on Ubuntu on Windows to check out such files, but when you direct any Windows application, it might result in very funny errors (such as not being able to modify or even delete the file).
