### ISSUE TITLE
git bash hangs on open with /usr/bin/bash --login -i on top window bar

### ISSUE THREAD

**Issue by carlcodes** [git-for-windows/git#849]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

Git for Windows v2.9.2

```
$ git --version
git version 2.9.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

not that I know of. I uninstalled and reinstalled git though, and the issue still persists so it is probably something with my environment, I just can't pinpoint it.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 git bash and cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

No commands ran, I only tried to open git bash via the start menu.

```
git rebase -i HEAD~3
```
could be a related issue.

 - What did you expect to occur after running these commands?

For git-bash to open in my home directory.

 - What actually happened instead?

![image](https://cloud.githubusercontent.com/assets/5365860/17558975/10ef3272-5ee2-11e6-8752-4871896888ae.png)
It hangs on this screen. I can ctrl-c out of it and bash-4.3$ appears. 

I can however use windows command line w/ git, however some commands hang (push and rebase), which could be related to this issue. I used GIT_TRACE after reading #600, and that fixed my issue with git push. I had a pre-push hook that didn't do anything, once deleting the hook, pushing worked. But rebase still hangs. The output of the rebase trace is: 

 ```
C:\git\ux>git rebase -i HEAD~3
09:49:28.144027 git.c:563               trace: exec: 'git-rebase' '-i' 'HEAD~3'
09:49:28.144027 run-command.c:336       trace: run_command: 'git-rebase' '-i' 'HEAD~3'
09:49:28.446176 git.c:350               trace: built-in: git 'rev-parse' '--parseopt' '--stuck-long' '--' '-i' 'HEAD~3'
^C
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 I don't think it's repo specific

Let me know if any other information is needed.

**Comment by carlcodes** [comment]
`git log` also hangs on cmd, with trace of:

```
C:\git\ux>git log
10:21:08.225162 git.c:350               trace: built-in: git 'log'
10:21:08.228168 run-command.c:336       trace: run_command: 'less'
^C
```

**Comment by dscho** [comment]
Is this Windows Server, or some Insider Preview? Do you have Windows File Protection enabled, perchance?

**Comment by dscho** [comment]
Also, could you give https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c a try?

**Comment by carlcodes** [comment]
![image](https://cloud.githubusercontent.com/assets/5365860/18561263/c73b9114-7b44-11e6-86ad-d892b1c2231f.png)

This is a print scrn of my system settings. 

I haven't touched the file protection setting, until just now. It looks like windows enables it by default correct? I just disabled it to see if it would fix. (Are you implying that it should be enabled, or disabled?)

...But nonetheless, it looks like disabling that fixed my problems! I can now open git bash and use log and rebase.

I am running into this issue on open of git bash,

```
ln: failed to create symbolic link '/etc/mtab': Permission denied
'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
/usr/bin/cp: cannot create regular file '/etc/hosts': Permission denied
'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
/usr/bin/cp: cannot create regular file '/etc/protocols': Permission denied
'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
/usr/bin/cp: cannot create regular file '/etc/services': Permission denied
'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
/usr/bin/cp: cannot create regular file '/etc/networks': Permission denied
rm: cannot remove '/etc/post-install/01-devices.post': Permission denied
rm: cannot remove '/etc/post-install/03-mtab.post': Permission denied
rm: cannot remove '/etc/post-install/06-windows-files.post': Permission denied
rm: cannot remove '/etc/post-install/99-post-install-cleanup.post': Permission denied
```

Although I can still use it fine after the error. I have yet to try to prerelease.

Thanks, though.

**Comment by dscho** [comment]
I was asking about the pre-release because it ships with a newer MSYS2 runtime that may fix the hang (I suspect AD issues).

**Comment by dscho** [comment]
> I haven't touched the file protection setting, until just now. It looks like windows enables it by default correct? I just disabled it to see if it would fix. (Are you implying that it should be enabled, or disabled?)

Seeing as you use an Enterprise version of Windows, it is most likely enforced by your IT department. In my installations, WFP is disabled by default.

> ...But nonetheless, it looks like disabling that fixed my problems! I can now open git bash and use log and rebase.

Perfect!

Please note that Windows File Protection handles code-signed `.exe` files much better than unsigned ones, and as a consequence I decided to code-sign Git's `.exe` files (this is in effect as of Git for Windows v2.9.3).

Sadly, this does not fix `rebase`, as that Git component is still implemented as a set of shell scripts (which still call unsigned `.exe` files). At least interactive rebase is now partially a builtin, so it should run relatively fast nonetheless.

> I am running into this issue on open of git bash,
> 
> ```sh
> ln: failed to create symbolic link '/etc/mtab': Permission denied
> 'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
> ...
> ```

Nothing to worry about. These failures are non-fatal and should be hidden by default, as they should run as part of the installation procedure. However, I suspect that they simply did not complete in your case. However, these messages should appear only once (if not, try running Git Bash as administrator once).
