### ISSUE TITLE
git gui no longer respects [commit] gpgsign = true

### ISSUE THREAD

**Issue by retep998** [git-for-windows/git#850]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 Git 2.9.2 64-bit.
 
 ```
> git --version
git version 2.9.2.windows.1
```
 
 Still broken as of `git version 2.9.3.windows.1`

 - Which version of Windows are you running? 32-bit or 64-bit?

 Windows 10 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 Typical upgrade with Git in my PATH and using mintty for git bash.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 I just upgraded from Git 2.8.x which did not have this issue.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Powershell inside conhost.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config -e --global
# [commit]
#    gpgsign = true
git gui
# Create a commit and push it to github
# Notice the lack of a verified stamp
git commit --amend
# Push this commit to github instead
# Notice the verified stamp does exist
```
 - What did you expect to occur after running these commands?

 I expect commits created by git gui to be gpg signed. This is the behavior that happened in previous versions of Git without issue.

 - What actually happened instead?

 The commits were not gpg signed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 Happens to any git repo

**Comment by dscho** [comment]
Is this a Windows-specific issue? I guess you have no easy way to test on Linux...

**Comment by retep998** [comment]
I have no idea whether it is Windows specific. I just know that the issue does exist in Git for Windows.

**Comment by landstander668** [comment]
From a quick test using Ubuntu 16.04 x86_64 on VirtualBox, this issue does not appear to occur on Linux.

```
:) adric@adric-VirtualBox ~
$ git version
git version 2.9.3

:) adric@adric-VirtualBox ~
$ git init foo && cd foo
Initialized empty Git repository in /home/adric/foo/.git/

:) adric@adric-VirtualBox foo (master)
$ git config --local commit.gpgsign true

:) adric@adric-VirtualBox foo (master)
$ git commit --allow-empty -m "Empty"

You need a passphrase to unlock the secret key for
user: "Adric Norris <adric.norris@egov.com>"
4096-bit RSA key, ID 65D3F218, created 2014-05-06

[master (root-commit) 11a3db5] Empty

:) adric@adric-VirtualBox foo (master)
$ git log --show-signature
commit 11a3db5304c8b10fcca3b116ff84846ac46a8fd6
gpg: Signature made Thu 08 Sep 2016 11:30:05 AM CDT using RSA key ID 65D3F218
gpg: Good signature from "Adric Norris <adric.norris@egov.com>"
Author: Adric Norris <adric.norris@egov.com>
Date:   Thu Sep 8 11:30:05 2016 -0500

    Empty
```

**Comment by retep998** [comment]
@landstander668 Did you create the commit with `git gui`? `git commit` works fine and isn't the issue.

**Comment by landstander668** [comment]
No, I somehow managed to completely overlook that detail. :( Sorry for the noise.

**Comment by dscho** [comment]
@landstander668 if you get a chance, could you try with `git gui` on Linux?

**Comment by landstander668** [comment]
I can reproduce this issue using `git gui` on Linux, using the same Ubuntu environment with Git 2.9.3 as the previous test. I tried setting _commit.gpgsign_ to _true_ at the local and global levels, both of which resulted in an unsigned commit.

**Comment by dscho** [comment]
Thanks for testing this!

My guess is that the culprit is described in [this part of 2.9.0's release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L19-L23):

> "git commit-tree" plumbing command required the user to always sign
> its result when the user sets the commit.gpgsign configuration
> variable, which was an ancient mistake, which this release corrects.
> A script that drives commit-tree, if it relies on this mistake, now
> needs to read commit.gpgsign and pass the -S option as necessary.

So I guess we would have to patch `git gui` accordingly.

Most likely, we will have to patch [`git-gui/lib/commit.tcl`'s `commit_committree` function](https://github.com/git-for-windows/git/blob/master/git-gui/lib/commit.tcl#L390--393) to insert the lines

```tcl
	# -- Create the commit.
	#
	set cmd [list commit-tree $tree_id]
+	if {[is_config_true commit.gpgsign]} {
+		lappend cmd -S
+	}
	foreach p [concat $PARENT $MERGE_HEAD] {
		lappend cmd -p $p
}
```

@landstander668 could you test this? The `commit.tcl` file should be in `<prefix>/share/git-gui/lib/`, so you could even patch it in an already-installed Git.

**Comment by retep998** [comment]
I can confirm patching my `commit.tcl` fixes the issue on Windows.

**Comment by dscho** [comment]
There is now a prerelease with the fix: https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c

**Comment by hasufell** [comment]
Shouldn't this be relayed to the main [git repo](https://github.com/git/git) as well? It basically has the same problem.

**Comment by dscho** [comment]
@hasufell of course. That's what I did, too: https://public-inbox.org/git/550e7de5e08e53b5893e1ce021bffee468adfc9d.1473424091.git.johannes.schindelin@gmx.de/
