### ISSUE TITLE
unable to download releases

### ISSUE THREAD

**Issue by isamuelson** [git-for-windows/git#853]

**Comment by isamuelson** [comment]
trying to download a release from: https://github.com/git-for-windows/git/releases

**Comment by PhilipOakley** [comment]
trying to download a release from: https://github.com/git-for-windows/git/releases
—
Don’t forget to scroll down to locate the version you want/need. Clicking the green button simply gets you back to the latest release page ;-)
 
P.

**Comment by isamuelson** [comment]
i am trying to download the latest one 64 bit exe. 

url: https://github.com/git-for-windows/git/releases/download/v2.9.3.windows.1/Git-2.9.3-64-bit.exe

**Comment by PhilipOakley** [comment]
i am trying to download the latest one 64 bit exe. 
  url: https://github.com/git-for-windows/git/releases/download/v2.9.3.windows.1/Git-2.9.3-64-bit.exe


But what are the failure messages, what OS are you on, What browser, etc. ?

**Comment by isamuelson** [comment]
OSX, windows, tried chrome, safari and edge

**Comment by isamuelson** [comment]
it looks like a AWS issue

**Comment by dscho** [comment]
@isamuelson you might think that it saves you time to be so concise with your messages. In fact, it does not save time. To the contrary. As we *still* do not know the *exact* symptom of what is going wrong, now I have to ask you again to provide either a detailed description, or a screenshot. Preferably both.
