### ISSUE TITLE
UriFormatException on remotes with port number caused by Microsoft Git Credential Manager shipped with Git for Windows 2.9.3 

### ISSUE THREAD

**Issue by whut** [git-for-windows/git#854]
### Setup
Git [2.9.3](https://github.com/git-for-windows/git/releases/tag/v2.9.3.windows.1) with default installation options, that is with the [Microsoft Git Credential Manager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) installed.

### Details

There is an issue Microsoft/Git-Credential-Manager-for-Windows#271 that is now shipped with Git for Windows 2.9.3 with the [1.6](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v.1.6.0) release of the credential manager: asking for credentials crashes for all remotes with port number in the URL (both from Bash and cmd.exe, for example during each `git fetch`).

I created this issue only to note that when upstream release a fix, Git for Windows should also be updated.

### Workaround
Either downgrade to 2.9.2 or override default "system-level" configuration and use the plain old [wincred](https://help.github.com/articles/caching-your-github-password-in-git/) using below commands:

```bash
git config --global credential.helper ""
git config --global --add credential.helper "wincred"
```

**Comment by bartread** [comment]
Nice - thanks for the workaround.

**Comment by dscho** [comment]
This should be fixed by including an updated Git Credential Manager already in 2.9.3(2).
