### ISSUE TITLE
Git GUI using --ignore-space-at-eol do not hide files where the only difference is an end-of-line at the end of the file and keeps showing the "No differences detected ... A rescan will be automatically restarted" pop-up.

### ISSUE THREAD

**Issue by kiewic** [git-for-windows/git#856]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64-bit

```
> git --version
git version 2.9.3.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

Defaults, but using git from the Windows command line.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

none
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

I am using `gut gui` with `--ignore-space-at-eol` in _Options_ | _Additional Diff Parameters_ in both, _MyRepoName Repository_ and _Global (All Repositories)_
- What did you expect to occur after running these commands?

Git GUI should not show files where the only difference is an extra end-of-line at the end of the file.

Alternatively, if Git GUI cannot hide these files, the "No differences detected" windows should not pop up every time I click on of these files.
- What actually happened instead?

Git GUI shows the files in the _Unstaged Changes_ panel, and when I select one of these files, I get the following error dialog:

```
---------------------------
Git Gui (MyRepoName)
---------------------------
No differences detected.

myfile.txt has no changes.

The modification date of this file was updated by
another application, but the content within the file
was not changed.

A rescan will be automatically started to find other
files which may have the same state.
---------------------------
OK   
---------------------------
```

If I click on _OK_, the list is reloaded and these files are still in the list. When I click on them again, I get the same dialog again and the list is reloaded again.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

The error only happens with unstaged changes with an extra line feed at the end of the file.

**Comment by dscho** [comment]
Unfortunately, I am swamped with work right now. But as this is not necessarily a Windows-specific problem, maybe you can raise the issue on [the Git mailing list](mailto:git@vger.kernel.org)? Hopefully somebody there will have enough time to at least point you in the right direction to get this fixed...
