### ISSUE TITLE
Upgrade the latest Git flow version

### ISSUE THREAD

**Issue by dkirrane** [git-for-windows/git#857]
How can I upgrade to the latest Git Flow AVH 1.10.0 version?

Currently it provides 1.9.1
```
$ git --version
git version 2.9.3.windows.1

$ git flow version
1.9.1 (AVH Edition)
```

It would make since to bundle an upgrade script similar to the Cygwin installer
https://raw.github.com/petervanderdoes/gitflow/develop/contrib/gitflow-installer.sh

**Comment by anb0s** [comment]
You have to update the MSYS2-packages, see #536 and https://github.com/Alexpux/MSYS2-packages/pull/392

**Comment by anb0s** [comment]
https://github.com/Alexpux/MSYS2-packages/pull/675

**Comment by anb0s** [comment]
It was merged to MSYS2, please close if available in next Git for Windows release...

**Comment by dscho** [comment]
For the record, it was not included in v2.10.0: that git-flow is still at version 1.9.1.

**Comment by dscho** [comment]
Will be included in v2.10.1, due later today.

**Comment by anb0s** [comment]
It's there, thanks!

$ git --version
git version 2.10.1.windows.1

$ git flow version
1.10.1 (AVH Edition)

**Comment by dscho** [comment]
Thanks for confirming!
