### ISSUE TITLE
Doesn't work when launched from within the symlink

### ISSUE THREAD

**Issue by ildar-shaimordanov** [git-for-windows/git#858]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

Both versions: 32-bit and 64-bit

```
$ git --version
git version 2.9.3.windows.1

$ git version
git version 2.9.3.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 7 Enterprise SP1 64-bit

```
C:\>ver

Microsoft Windows [Version 6.1.7601]
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

Install from PortableGit to the directory `C:\PortableGit`
Create symlink:

```
mklink /d git C:\PortableGit
```

Run `C:\git\git-bash.exe`.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?
  
  _Something was broken between 2.7.2 and 2.9.3 because this was working properly under 2.7.2 and doesn't work under 2.9.3._
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash.exe
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
$ cd / ; ls
bash: cd: /: No such file or directory
ls: cannot open directory '.': No such file or directory
```
- What did you expect to occur after running these commands?
  
  _Change to the root directory and show the directory listing. At the same time this does work if it is running as `C:\PortableGit\git-bash.exe`_

**Comment by dscho** [comment]
It is unclear what happened there, and sadly I do not have time right now to investigate. However, 2.7.2 to 2.9.3 is a rather large jump, so maybe you find time to narrow that down more.

**Comment by dscho** [comment]
It would appear that this issue no longer persists.

**Comment by ildar-shaimordanov** [comment]
I would like to reopen this issue becoause it is still not resolved. A day ago I have downloaded the latest version of PortableGit 2.15.0 and tested it. I can confirm that the issue is still there. Please have a look into the proofs below.

The downlaoded `.7z.exe` file was installed into some directory. After that I have created the junction and two symbolic links -- one is symlink to the full path and the second one is relative symlink to the same directory (see Initial state and Final state). 

In the case of the junction and the full path symlink the PortableGit is working properly. 

In the case of relative symlink it doesn't work. If you have a look on the last case, you will see that the relative symlink refers to a subdirectory, not to the real path as it is done in the case of junction and full path symlink. 

## Initial state ##

```
C:\zzz>dir
 Volume in drive C is PC COE
 Volume Serial Number is DC8B-7390

 Directory of C:\zzz

2017-11-01  12:52    <DIR>          .
2017-11-01  12:52    <DIR>          ..
2017-11-01  12:39    <DIR>          PortableGit-2.15.0-32-bit
2017-11-01  12:40    <DIR>          PortableGit-2.15.0-64-bit
               0 File(s)              0 bytes
               4 Dir(s)   9 107 095 552 bytes free
```

## Final state ##

```
C:\zzz>dir
 Volume in drive C is PC COE
 Volume Serial Number is DC8B-7390

 Directory of C:\zzz

2017-11-01  12:53    <DIR>          .
2017-11-01  12:53    <DIR>          ..
2017-11-01  12:53    <SYMLINKD>     git-df [C:\zzz\PortableGit-2.15.0-32-bit]
2017-11-01  12:53    <SYMLINKD>     git-ds [PortableGit-2.15.0-32-bit]
2017-11-01  12:53    <JUNCTION>     git-j [C:\zzz\PortableGit-2.15.0-32-bit]
2017-11-01  12:39    <DIR>          PortableGit-2.15.0-32-bit
2017-11-01  12:40    <DIR>          PortableGit-2.15.0-64-bit
               0 File(s)              0 bytes
               7 Dir(s)   9 106 321 408 bytes free

C:\zzz>
```

# Testing with the junction #

## Create ##

```
C:\zzz>mklink /j git-j PortableGit-2.15.0-32-bit
Junction created for git-j <<===>> PortableGit-2.15.0-32-bit
```

## Launch ##

```
C:\zzz>git-j\git-bash.exe
```

## Within environment ##

```
$ cygpath -w /
C:\zzz\PortableGit-2.15.0-32-bit\

$ ls /
bin/  dev/  git-bash.exe*  LICENSE.txt  post-install.bat  tmp/
cmd/  etc/  git-cmd.exe*   mingw32/     README.portable   usr/

$ ( cd / ; pwd )
/
```


# Testing with the full path symbolic link #

## Create ##

```
C:\zzz>mklink /d git-df %cd%\PortableGit-2.15.0-32-bit
symbolic link created for git-df <<===>> C:\zzz\PortableGit-2.15.0-32-bit
```

## Launch ##

```
C:\zzz>git-df\git-bash.exe
```

## Within environment ##

```
$ cygpath -w /
C:\zzz\PortableGit-2.15.0-32-bit\

$ ls /
bin/  dev/  git-bash.exe*  LICENSE.txt  post-install.bat  tmp/
cmd/  etc/  git-cmd.exe*   mingw32/     README.portable   usr/

$ ( cd / ; pwd )
/
```


# Testing with the short symbolic link #

## Create ##

```
C:\zzz>mklink /d git-ds PortableGit-2.15.0-32-bit
symbolic link created for git-ds <<===>> PortableGit-2.15.0-32-bit
```

## Launch ##

```
C:\zzz>git-ds\git-bash.exe
```

## Within environment ##

```
$ cygpath -w /
C:\zzz\git-ds\PortableGit-2.15.0-32-bit\

$ ls /
ls: cannot access '/': No such file or directory

$ ( cd / ; pwd )
bash: cd: /: No such file or directory
/c/zzz
```

**Comment by dscho** [comment]
> ```
> $ ls /
> ls: cannot access '/': No such file or directory
> ```

I can confirm that this is the case, but I have to point out that this is not a Git issue, but more of an [MSYS2](https://msys2.github.io/) issue...
