### ISSUE TITLE
[git gui] Focus of files listed in "Unstaged Changes" should be possible

### ISSUE THREAD

**Issue by koppor** [git-for-windows/git#859]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing. I searched for "Unstaged"
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

```
$ git --version
git version 2.9.3.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

Defaults of `choco install git`.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?
  
  No.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash and CMD inside [ConEmu](https://conemu.github.io/)
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.
1. `git init`
2. `echo "line1" > f1.txt`
3. `echo "line1" > f2.txt`
4. `git add .`
5.  `git commit -m"first commit"`
6. `echo "line2" >> f1.txt`
7. `echo "line2" >> f2.txt`
8. `git gui&`
9. Click on field "Commit Message"
10. Click on f1.txt at "Unstaged Changes"
11. Press <kbd>cursor-down</kbd>

![grabbed_20160820-090629](https://cloud.githubusercontent.com/assets/1366654/17829631/65477318-66b5-11e6-879c-ec5da5d969a0.png)
- What did you expect to occur after running these commands?

f2.txt is focused
- What actually happened instead?

Nothing happens

Note: Similar expectations exist for <kbd>CTRL</kbd>+<kbd>T</kbd>. See http://stackoverflow.com/questions/3535019/git-gui-moving-keyboard-focus-to-changed-files.

**Comment by patthoyts** [comment]
The current design of the application has the focus assigned to the commit message text field so what is actually happening is your keystroke was sent to the commit box. If you add to lines into the commit message then click on the files box and use key-up and key-down you'll see the cursor moving in the commit message field.

However, permitting keyboard control of the files control seems like a useful and worthwhile enhancement. This is not really a Git for Windows issue though but there's not currently a better place to hold this. Maybe @dscho can assign it to me.

**Comment by patthoyts** [comment]
You might like to try out [https://github.com/patthoyts/git-gui/tree/pt/non-mouse-usage](pt/non-mouse-usage) which is a branch to address this. Note you need to use Ctrl-Tab to get out of the commit box as Tab just inserts a tab character.

**Comment by koppor** [comment]
Code looks good, but I have to investigate how to build the branch on Windows...

**Comment by dscho** [comment]
@koppor maybe this helps? https://github.com/git-for-windows/git/wiki/Building-git

**Comment by koppor** [comment]
Works with git 2.11.0.windows.1 🎉 . Thank you for implementing @patthoyts.

However, <kbd>Ctrl</kbd> + <kbd>T</kbd> does not work on multiple entries anymore. Think, I have to submit another issue... 🎱 

![grabbed_20161208-100941](https://cloud.githubusercontent.com/assets/1366654/21003972/73dbeb96-bd2e-11e6-9555-f8898ef0d028.png)

**Comment by koppor** [comment]
Not yet submitted an issue, but wrote a comment at https://github.com/git-for-windows/git/issues/1012#issuecomment-280396844

**Comment by EthelEleanor** [comment]
bash: vn@Eth: command not found


$ $ gt vson 2.9.3.wndows.1
bash: $: command not found


$ bash: gt: coand not ond
bash: bash:: command not found


bash: vn@Eth: command not found


$ $ choco nsta gt
bash: $: command not found


$ bash: choco: coand not ond
bash: bash:: command not fou

bash: vn@Eth: command not found


$ $ gt nt
bash: $: command not fou
$ gt add .
bash: gt: command not found

$ gt cot -"st cot"
bash: gt: command not found


$ cho "n2" >> 1.txt
bash: cho: command not found


$ cho "n2" >> 2.txt
bash: cho: command not found


$ gt g&bash: gt: coand not ond
[1] 15516
bash: gt: command not found
bash: bash:: command not found
[1]+  Exit 127               
bash: vn@Eth: command not found


$ $ cho "n1" > 1.txt
bash: $: command not found
$ bash: cho: coand not ond
bash: bash:: command no
bash: vn@Eth: command not found

$ $ cho "n1" > 2.txt
bash: $: command not found

$ bash: cho: coand not ond
bash: bash:: command not found

bash: vn@Eth: command not found


$ $ gt add .
bash: $: command not found


$ bash: gt: coand not ond
bash: bash:: command not found


bash: vn@Eth: command not found

$ $ gt cot -"st cot"
bash: $: command not found

 bash: gt: coand not ond
bash: bash:: command not found


bash: vn@Eth: command not found

 $ cho "n2" >> 1.txt
bash: $: command not found


$ bash: cho: coand not ond
bash: bash:: command not found




$ $ cho "n2" >> 2.txt
bash: $: command not found


$ bash: cho: coand not ond
bash: bash:: command not found



bash: vn@Eth: command not found


$ $ gt g&
[1] 17140
bash: $: command not found
[1]+  Exit 127                $ gt
