### ISSUE TITLE
ssh-agent mkdtemp private socket dir permission denied

### ISSUE THREAD

**Issue by abelhegedus** [git-for-windows/git#86]
I just switched from 1.9.5 (32 bit) to 2.3.5.8 (64 bit) and found that .bashrc was not loaded by default when starting Git Bash, so I added a .bash_profile in my home directory with the following content
`if [ -f ~/.bashrc ]; then . ~/.bashrc; fi`

However, my .bashrc contains the ssh-agent setup from https://help.github.com/articles/working-with-ssh-key-passphrases/#auto-launching-ssh-agent-on-msysgit

When starting Git Bash, I get the following:
```
mkdtemp: private socket dir: permission denied
Could not open a connection to your authentication agent.
bash: __git_ps1: command not found
```

The last I fixed by adding `source "c:/Program Files/Git/mingw64/share/git/completion/git-prompt.sh"` to the beginning of .bashrc (from http://stackoverflow.com/a/17508424/2315334 ).
 * Is this required? Shouldn't this work out-of-the-box?
 * Would it be better to use `source "c:/Program Files/Git/etc/profile.d/git-prompt.sh"`?

I think the second error comes from ssh-add, since ssh-agent could not start.

The first error occurs also if invoking `ssh-agent` from Git Bash. After looking around, I found http://stackoverflow.com/a/25068967/2315334 and found that there is an empty `AppData\Local\VirtualStore\Program Files (x86)\Git\etc\` folder, but it may be unrelated, since now I use a 64 bit version.

As a workaround, I tried running Git Bash in Administrator mode, which worked and ssh-agent could start successfully. Also, changing the security settings and adding modification rights to users on the Git folder also worked.

As a sidenote, I had a GIT_HOME environment variable pointing to Git/bin (of 1.9.5), but that no longer exists. Which folder should I use from now on?

Thanks in advance for any help!

**Comment by dscho** [comment]
> I just switched from 1.9.5 (32 bit) to 2.3.5.8 (64 bit) and found that .bashrc was not loaded by default when starting Git Bash, so I added a .bash_profile in my home directory with the following content
> `if [ -f ~/.bashrc ]; then . ~/.bashrc; fi`

First of all, thank you for such a precise report, it is really nice.

As to `~/.bashrc`, I guess we need to clean up [this msysgit patch](https://github.com/msysgit/msysgit/pull/301) and apply it here. (Unless you beat me to it, I will take care of that after taking off this weekend.)

> When starting Git Bash, I get the following:
> 
> ```
> mkdtemp: private socket dir: permission denied
> Could not open a connection to your authentication agent.
> bash: __git_ps1: command not found
> ```
>
> The last I fixed by adding source "c:/Program Files/Git/mingw64/share/git/completion/git-prompt.sh" to the beginning of .bashrc (from http://stackoverflow.com/a/17508424/2315334 ).

That should not be necessary... How do you call the Git Bash? By double-clicking the `git-bash` executable in the root directory of the portable Git? That should work, as it passes the `--login` option to Bash which triggers the `git-prompt.sh` to be read via `/etc/profile.d/git-prompt.sh`.

If you are calling `sh` inside the Git Bash, yeah, I heard about that, but did not think that this is a terribly common operation. I guess we could work around it by sourcing `git-prompt.sh` in `/etc/bash.bashrc` but keep in mind that this file is sourced everytime Bash is started, *even when it is not interactive*...

Maybe something like

```bash
test ! -t 0 ||
case "$(type __git_ps1)" in
*"shell function"*) ;; # already defined
*) source /etc/profile.d/git-prompt.sh;;
esac
```

in `/etc/bash.bashrc`? Feel free to play variations on this theme to figure out whether it would fit your needs.

> I think the second error comes from ssh-add, since ssh-agent could not start.

That is quite likely. As to `ssh-agent`, can you start it manually with the `-d` option and see whether it tries to write somewhere it is not supposed to? 2.3.5.8 *should* refrain from overriding the `TMP` variable, but that might not be the case. If it overrides `TMP`, it is set to `/tmp/` which translates to `c:\Program Files\Git\tmp` in default installations (which is not a valid destination to write to for non-admins).

As to `GIT_HOME`, what is that variable supposed to contain? I found no reference to it in Git's source code...

**Comment by abelhegedus** [comment]
Thanks for getting back to me so fast!

> As to GIT_HOME, what is that variable supposed to contain? I found no reference to it in Git's source code...

I have probably added it for https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin it says `GIT_HOME => Folder where your git.exe is located` so that will be `Git/cmd` in 2.3.5. I have not tried Jenkins since the update, but we can safely say it is unrelated to Git for Windows (apart from the fact that the executable moved since 1.9.5).

> As to ~/.bashrc, I guess we need to clean up this msysgit patch and apply it here. (Unless you beat me to it, I will take care of that after taking off this weekend.)

Yes, I can see how the issue applies here. Is it normal that it worked in 1.9.5 without needing to create a `.bash_profile` (and it was not created either since the file was missing)?

> That should not be necessary... How do you call the Git Bash?

Actually, I tried to test my `.bashrc` by calling `bash` after starting Git Bash. Previously, this didn't cause any errors (as far as I can remember, but I think in 1.9.5 the Bash was a bit different: no MinGW and `@hostname` in the prompt). I removed the line and it seems to work, so that's a non-issue (and you are aware of the case when calling bash inside bash :smiley:).

> As to ssh-agent, can you start it manually with the -d option and see whether it tries to write somewhere it is not supposed to?

`mkdtemp: private socket dir: Permission denied` This is the only message I get.

**Comment by abelhegedus** [comment]
Additional information: I have `TMP` environment variable defined as `%USERPROFILE%\AppData\Local\Temp` and I can see several `ssh-gibberishcharacters` folders with  `agent.somenumber` file in them (somenumber seems to be some process id). But there is no folder created here, although I think it should be able to create here, if it is not overridden.

**Comment by abelhegedus** [comment]
Further investigation (tell me if I should stop or if the information is not useful):
* `echo $TMP` results in empty string (so does `echo $TEMP`)
* in `etc/profile` I can see:

```
ORIGINAL_TMP=$TMP
ORIGINAL_TEMP=$TEMP
unset TMP TEMP
tmp=$(cygpath -w "$ORIGINAL_TMP" 2> /dev/null)
temp=$(cygpath -w "$ORIGINAL_TEMP" 2> /dev/null)
#TMP="/tmp"
#TEMP="/tmp"
```

However, I can also see, that when ssh-agent could write to `Git/tmp`, it created its temporary directories. In addition, I can also see a `git-wrapper.exe` in there (creation date is the same as `git-cmd.exe`, 2015.04.10. 06:53)

It seems like ssh-agent is using `tmp` or `/tmp` instead of `$tmp`.

**Comment by abelhegedus** [comment]
Is there a reason why `-w` (Windows style with backslashes) are used in `cygpath -w "$ORIGINAL_TMP"` instead of `-m` (mixed) or `-u` (unix) (http://cygwin-lite.sourceforge.net/html/cygpath.html).

Using `ssh-agent -a $ORIGINAL_TMP/.ssh-agent.$$` works correctly, however `ssh-agent -a $tmp/.ssh-agent.$$` results in `SSH_AUTH_SOCK` set to `cUsers<UserName>AppDataLocalTemp/.ssh-agent.<socketnumber>` (note the missing slashes) and causes ssh-add to fail since it cannot find the path (naturally).

**Comment by dscho** [comment]
> > As to GIT_HOME, what is that variable supposed to contain? I found no reference to it in Git's source code...
> 
> I have probably added it for https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin it says GIT_HOME => Folder where your git.exe is located so that will be Git/cmd in 2.3.5. I have not tried Jenkins since the update, but we can safely say it is unrelated to Git for Windows (apart from the fact that the executable moved since 1.9.5).

Well, `git.exe` moved, but from `bin/` to `mingw??/bin/`. The idea for *any* external users is to use the Git wrapper in `cmd/`; that has not changed since 1.9.5.

> > As to ~/.bashrc, I guess we need to clean up this msysgit patch and apply it here. (Unless you beat me to it, I will take care of that after taking off this weekend.)
> 
> Yes, I can see how the issue applies here. Is it normal that it worked in 1.9.5 without needing to create a .bash_profile (and it was not created either since the file was missing)?

Well, that behavior is a *bug* in 1.9.5, from what I gather from that other PR... `~/.bashrc` is apparently not supposed to be sourced automatically upon login, but only upon spawning a new *non-login* shell.

> > As to ssh-agent, can you start it manually with the -d option and see whether it tries to write somewhere it is not supposed to?
> 
> mkdtemp: private socket dir: Permission denied This is the only message I get.

Hmm. What about `strace ssh-agent -d`? That should trace all the calls into the MSys2 runtime.

> It seems like ssh-agent is using tmp or /tmp instead of $tmp. (also backed by http://en.wikipedia.org/wiki/Ssh-agent#Security_issues and http://stackoverflow.com/a/27184401/2315334)

I saw that MSys2 makes a difference between `$tmp` and `$TMP` (but Win32 API does not). Could you make sure that `TMP` is set correctly (i.e. all upper-case)?

> Is there a reason why -w (Windows style with backslashes) is used in cygpath -w "$ORIGINAL_TMP" in etc/profile instead of -m (mixed) or -u (unix) (http://cygwin-lite.sourceforge.net/html/cygpath.html).

Probably. But since `$ORIGINAL_TMP` is not used by anything, it should not matter.

> Using ssh-agent -a $ORIGINAL_TMP/.ssh-agent.$$ works correctly, however ssh-agent -a $tmp/.ssh-agent.$$ results in SSH_AUTH_SOCK set to cUsers<UserName>AppDataLocalTemp/.ssh-agent.<socketnumber> (note the missing slashes) and causes ssh-add to fail since it cannot find the path (naturally).

Can you try with `$tmp` quoted in double-quotes?

**Comment by abelhegedus** [comment]
> Hmm. What about `strace ssh-agent -d`? That should trace all the calls into the MSys2 runtime.

See https://gist.github.com/abelhegedus/66469ba28a370079d3b9 however, I think the important part is (from https://gist.github.com/abelhegedus/66469ba28a370079d3b9#file-strace-log-L512):

```
normalize_posix_path: src /tmp/ssh-RzBbLVHPby90
src_path /tmp/ssh-RzBbLVHPby90, dst C:\Program Files\Git\tmp\ssh-RzBbLVHPby90
mkdir: -1 = mkdir(/tmp/ssh-RzBbLVHPby90, 448), errno 13
```

> Can you try with $tmp quoted in double-quotes?

```
$ ssh-agent -a "$tmp"/.ssh-agent.$$
SSH_AUTH_SOCK=C:\Users\<UserName>\AppData\Local\Temp/.ssh-agent.2036; export SSH_AUTH_SOCK;
SSH_AGENT_PID=7688; export SSH_AGENT_PID;
echo Agent pid 7688;
```

However, both `SSH_AUTH_SOCK` and `SSH_AGENT_PID` evaluate to empty string after that, so this is not good.

> Probably. But since $ORIGINAL_TMP is not used by anything, it should not matter.

Sorry, I meant this line `tmp=$(cygpath -w "$ORIGINAL_TMP" 2> /dev/null)` in `etc/profile`.

> I saw that MSys2 makes a difference between `$tmp` and `$TMP` (but Win32 API does not). Could you make sure that `TMP` is set correctly (i.e. all upper-case)?

What do you mean by "set correctly"? It is set in Windows, but in /etc/profile, you call `unset TMP TEMP` so it is empty afterwards. As for `$tmp` it will contain Windows style path:
```
$ echo $tmp
C:\Users\<UserName>\AppData\Local\Temp
```

**Comment by dscho** [comment]
> in /etc/profile, you call unset TMP TEMP

Just quickly: that was an oversight, this `unset` call should be commented out, too.

**Comment by dscho** [comment]
> > Can you try with $tmp quoted in double-quotes?
> 
> ```sh
> $ ssh-agent -a "$tmp"/.ssh-agent.$$
> SSH_AUTH_SOCK=C:\Users\<UserName>\AppData\Local\Temp/.ssh-agent.2036; export SSH_AUTH_SOCK;
> SSH_AGENT_PID=7688; export SSH_AGENT_PID;
> echo Agent pid 7688;
> ```
>
> However, both SSH_AUTH_SOCK and SSH_AGENT_PID evaluate to empty string after that, so this is not good.

Just for the record: the output of `ssh-agent` is supposed to be `eval`ed, not just printed to the console. Printing it to the console is good for debugging, though. However, if you want `SSH_AUTH_SOCK` and `SSH_AGENT_PID` to be set correctly, you will have to call

```sh
> eval $(ssh-agent -a "$tmp"/.ssh-agent.$$)
```

(The reason is that calling scripts in Bash -- unlike cmd -- does not affect the environment variables of the caller)

> > Probably. But since $ORIGINAL_TMP is not used by anything, it should not matter.
> 
> Sorry, I meant this line tmp=$(cygpath -w "$ORIGINAL_TMP" 2> /dev/null) in etc/profile.

Right, that assignment looks also fishy. It is most likely another oversight on my behalf, sorry. I guess the entire section (including the `unset TMP` and the `tmp=` line) should be commented out. Can you do that and try again, please?

> > I saw that MSys2 makes a difference between $tmp and $TMP (but Win32 API does not). Could you make sure that TMP is set correctly (i.e. all upper-case)?
> 
> What do you mean by "set correctly"? It is set in Windows, but in /etc/profile, you call unset TMP TEMP so it is empty afterwards. As for $tmp it will contain Windows style path:
> 
> $ echo $tmp
> C:\Users\<UserName>\AppData\Local\Temp

By "set correctly", I meant that the `TMP` (not the `tmp`) variable is set, and that it contains forward slashes instead of backward slashes.

I guess that we should actually also append these two lines after the TMP section in the `/etc/profile` file (which we need to comment out, as I mentioned above):

```sh
case "$TMP" in *\\*) TMP="$(cygpath -m "$TMP")";; esac
case "$TEMP" in *\\*) TEMP="$(cygpath -m "$TEMP")";; esac
```

**Comment by dscho** [comment]
@abelhegedus I would like to ask you to replace the `TMP` section in your `/etc/profile` with the following and try again:

```sh
# TMP and TEMP as defined in the Windows environment must be kept
# for windows apps, even if started from msys2. However, leaving
# them set to the default Windows temporary directory or unset
# can have unexpected consequences for msys2 apps, so we define 
# our own to match GNU/Linux behaviour.
ORIGINAL_TMP=$TMP
ORIGINAL_TEMP=$TEMP
#unset TMP TEMP
#tmp=$(cygpath -w "$ORIGINAL_TMP" 2> /dev/null)
#temp=$(cygpath -w "$ORIGINAL_TEMP" 2> /dev/null)
#TMP="/tmp"
#TEMP="/tmp"
case "$TMP" in *\\*) TMP="$(cygpath -m "$TMP")";; esac
case "$TEMP" in *\\*) TEMP="$(cygpath -m "$TEMP")";; esac
```

If your test is successful, I will make the necessary changes to the `git-extra` package and the bug will be fixed in the next Git for Windows 2.x version.

**Comment by abelhegedus** [comment]
> @abelhegedus I would like to ask you to replace the TMP section in your /etc/profile with the following and try again

I did, the results are the following:
```
$ echo $TMP
/c/Users/dustman/AppData/Local/Temp
$ echo $ORIGINAL_TMP
/c/Users/dustman/AppData/Local/Temp
$ echo $tmp

```

> `eval $(ssh-agent -a "$TMP"/.ssh-agent.$$)`

This also works correctly and indeed the environment variables are set with forward slashes.

However, `ssh-agent -d` still results in the original error: 
```
$ eval $(ssh-agent -d)
mkdtemp: private socket dir: Permission denied
```
In my opinion, this happens since by default, ssh-agent wants to write into `/tmp` and not `$tmp` or `$TMP`.

**Comment by dscho** [comment]
> In my opinion, this happens since by default, ssh-agent wants to write into /tmp and not $tmp or $TMP.

I fear you are correct. Darn.

So now we will have to dig into the msys2-runtime because it seems that `mkdtemp()` as called from the *MSys2* program `ssh-agent` does not respect the `TMP` environment variable.

**Comment by dscho** [comment]
Hah! I found something. The `mkdtemp()` function actually does not make an absolute path from a relative one, i.e. `mkdtemp("ssh-agent.XXXXXX")` would create a directory in the *current* working directory. Therefore, `ssh-agent` has to provide a template with the complete, absolute path of the directory. It does so by using the `mktemp_proto()` function in `misc.c` which reads like this:

```c
/* Make a template filename for mk[sd]temp() */
void
mktemp_proto(char *s, size_t len)
{
	const char *tmpdir;
	int r;

	if ((tmpdir = getenv("TMPDIR")) != NULL) {
		r = snprintf(s, len, "%s/ssh-XXXXXXXXXXXX", tmpdir);
		if (r > 0 && (size_t)r < len)
			return;
	}
	r = snprintf(s, len, "/tmp/ssh-XXXXXXXXXXXX");
	if (r < 0 || (size_t)r >= len)
		fatal("%s: template string too short", __func__);
}
```

As you can see, it actually looks at the `TMPDIR` variable, *not* the `TMP` variable.

So I would really like to ask you to test one more thing and hope that we will have everything we need once you report success. Could you please add the following line after that section you already edited in your `/etc/profile` and run that `ssh-agent -d` command again?

```sh
test -d "$TMPDIR" || test ! -d "$TMP" || {
    TMPDIR="$TMP"
    export TMPDIR
}
```

**Comment by abelhegedus** [comment]
Yep, works like a charm!

calling ssh-agent -d succeeds, it prints out the path (correctly pointing to a newly created subfolder in `$TMP` - AppData/Local/Temp) and then hangs as expected (and closes the socket on interruption).

Calling from .bashrc with my original setup works correctly.

**Comment by dscho** [comment]
Perfect. I will edit the `git-extra` post-install script accordingly (and will let you know when that's done).

**Comment by dscho** [comment]
Fixed as per https://github.com/git-for-windows/build-extra/commit/081b0cc19421c6f8def715ecb0edee38327c959b.

**Comment by abelhegedus** [comment]
Thanks! Do you still intend to port https://github.com/msysgit/msysgit/pull/301 as well to create .bash_profile if it does not exist?

**Comment by dscho** [comment]
@abelhegedus I forgot about that, and I also have no time right now, unfortunately. The change would need to be made as part of [`git-extra`](https://github.com/git-for-windows/build-extra/tree/master/git-extra).
