### ISSUE TITLE
Cannot use parentheses `()` in file name

### ISSUE THREAD

**Issue by oak-tree** [git-for-windows/git#864]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - 64-bit? 

```
$ git --version
git version 2.9.3.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?
```
Windows 10 64 bit 
```
 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
   defaults 

```
 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```

```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
Bash
```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ vim ./tmp/myfile(1).jpeg


```
 - What did you expect to occur after running these commands?

```
Open the file in the editor

```

 - What actually happened instead?
```
$ vim ./tmp/myfile(1).jpeg
bash: syntax error near unexpected token `('
```

Note that on `windows default cmd` the command above does work

**Comment by kostix** [comment]
A non-issue: in `bash` — as in any POSIX-compatible shell — `(command ...)` means a command run in a subshell process.

@oak-tree , to work with such names, escape those names.  Either encose them in quotes (preferably single quotes `'`, but double quotes `"` will work in most cases, too) or put a backslash before each character you want to escape, like in `filename\(`\).jpg`.

**Comment by oak-tree** [comment]
Thanks this  `vim test\(\).jpg` works :+1:
