### ISSUE TITLE
CTRL-D for (reading log message from standard input) after "git commit -F -" is not working

### ISSUE THREAD

**Issue by BinaryNectar** [git-for-windows/git#867]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64-bit

```
$ git --version
git version 2.9.3.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?
  
  Windows 10 64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

defaults
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

Nothing special.  Consistent with other users.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
git commit -F -
```
- What did you expect to occur after running these commands?

I expected that I would enter my message for the log, hit Ctrl-D, and have the commit submit successfully.
- What actually happened instead?
  
  Entering Ctrl-D provides no change at all
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

Happening with other workstations for other users, including this guy (username: blockloop) who helped me verify the issue (http://chat.stackoverflow.com/transcript/122353)

**Comment by dscho** [comment]
Have you tried running `winpty git commit -F -`?

**Comment by BinaryNectar** [comment]
I don't believe I have `winpty ` installed on my machine.  After skimming the [README](https://github.com/rprichard/winpty), it may take a while before I can get back to you and say if it's working.

**Comment by BinaryNectar** [comment]
Now I'm confused if I have it installed or not...  If I type in `winpty` on the Git Bash prompt I get the following:
```
$ winpty
Usage: winpty [options] [--] program [args]

Options:
  -h, --help  Show this help message
  --mouse     Enable terminal mouse input
  --showkey   Dump STDIN escape sequences
  --version   Show the winpty version number
```

If I type `winpty get commit -F -`, I get the following error:
```
$ winpty get commit -F -
Error 0x2 starting get commit -F -
```

**Comment by BinaryNectar** [comment]
Interesting!

If I type `winpty git commit -F -`, I get the same "standard input" as before, except now if I enter `ctrl-D` I actually see a `^D` appear on screen.  However, nothing happens, even if I hit `enter` afterwards.  

So after playing around with it a bit I noticed that if I hit `ctrl-Z` and `enter` on its own line, the commit goes through!  `^Z` will appear after pressing `ctrl-Z`, but the text is stripped out when saving the commit log message.  If I press `ctrl+Z` on the same line as my message, then `^Z` will be entered as text next to the message and nothing else will happen.  You need to press `ctrl-Z` on a separate and empty line.

Thank you for your help!

**Comment by dscho** [comment]
Another idea: if you want to type your message without spawning an editor, you could switch to typing something like this:

```sh
git commit -m 'This message starts with a single quote

Which means that you can hit Enter in order to type a multi-line
argument. The command will only run when hitting the Enter key
after an end quote. If you need to embed a single quote in the
message, you can do that by an end quote followed by a
double-quoted single quote, followed immediately by a single
quote to continue the quoted message with embedded
new-lines. Example:

    '"'"'This looks a little funny'"'"', admittedly.

But it works. And it avoids the problem where `git.exe`,
which is a pure Win32 executable, does not know how
to handle `/dev/stdin`, which is an MSYS2-emulated
POSIX construct only understood by MSYS2 executables.'
```

**Comment by BinaryNectar** [comment]
Thanks!  I will keep that in mind.  Honestly, all I wanted to do was report the issue since the [documentation ](https://git-scm.com/docs/git-commit ) doesn't mention it.  But, that is definitely good to know.

**Comment by kgybels** [comment]
When working with mintty, `cat | git commit -F -` works well.

**Comment by dscho** [comment]
So it seems that with this workaround, there is no pressing need to resolve this. I'll close the ticket for now, then. Anybody who has any good idea how to fix the Ctrl+D problem: please do speak up in this ticket, we can *easily* reopen when that happens.
