### ISSUE TITLE
Very slow push over https

### ISSUE THREAD

**Issue by llehn** [git-for-windows/git#869]
### Setup

git version 2.9.2.windows.1 x64
git version 2.9.3.windows.2 x32
same behaviour.

Win7 x64. 
Win 8.1 x64

30 Mbit symmetrical bandwidth.
### Details

Git is running git from cmd/tortoise. Same behaviour.

I'm experiencing a weird issue of slow https push to github and gitlab and othe hosts.
I have a newly made local repo with a large binary file in it. I push that repo to github.
I get ~200 KB/s over https. 
If I change to ssh, I get 3.5 MB/s.
If I use https from the browser (tried chrome and ie) I get upload speeds of 3.5 MB/s
If I upload with https through a ssh tunnel (to rule out any local network firewalls) I get 200 KB/s.
If I upload with ssh over a ssh tunnel I get 3.5 MB/s

I tried everything. Uninstalled anything which may be related to antivirus. I tried a built-in git client of VS2013 which uses a 1 year old libgit2 - it is slow too. 

I tried several windows machines, they all show the same behaviour. On a linux machine git push over https is fast.

I have no explanation and no clues where to look further, any ideas?

**Comment by llehn** [comment]
The speed increases massively if I increase http.postBuffer to a very large value.

I think this should not work that way. With 30Mbit/s and default buffer size of 1 MiB there should be no performance difference between default buffer and a large buffer size.

**Comment by dscho** [comment]
@llehn there has been *some* work on the HTTP/HTTPS transport in the meantime.

Could you test again with v2.10.0?

If the problem still persists, try setting the environment variable `GIT_TRACE_CURL=2` and run your commands again. That should give you a better idea how Git spends all that time.

**Comment by dscho** [comment]
Or maybeyou could test  https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c ?

**Comment by llehn** [comment]
I tried with the build you linked, did not notice a major improvement.

Here's the illustration of what it looks like:
![2016-09-13 10_16_15-networx alle verbindungen](https://cloud.githubusercontent.com/assets/10240910/18466222/250ff3d0-799b-11e6-94d1-c42cfb7ec1f9.png)

The first graph is the result of a simple git push with a https remote.

The second graph is the same push, but with ````git config http.postBuffer 1000000000````

The third graph is the push to the same repository via ssh.

The whole thing is not very scientific, I share the bandwidth with many other people and I don't know what they are doing, but the results are representative.

I tried GIT_TRACE_CURL=2 and compared the output of the pushes with and without a large buffer.
There are two differences: 
-without the large postBuffer there is an additional POST request sending "0000" just before starting to send the data, this request is completely absent when using large buffer

````
Send header: POST /scm/dwd/test1.git/git-receive-pack HTTP/1.1
Send header: Host: bitbucket.kardex.com
Send header: Authorization: Basic <redacted>
Send header: User-Agent: git/2.10.0.windows.1.11.geda474c
Send header: Content-Type: application/x-git-receive-pack-request
Send header: Accept: application/x-git-receive-pack-result
Send header: Content-Length: 4
Send header:
Send data, 0000000004 bytes (0x00000004)
Send data: 0000
Info: upload completely sent off: 4 out of 4 bytes
````

The second difference is in the actual POST request which sends the data, here the version without large buffer uses this:

````
Send header: Transfer-Encoding: chunked
````

whereas the version with large buffer sets the content-size (as it should probably)

````
Send header: Content-Length: 134937188
````

Apart from that there are no differences in the log output (timestamps and encrypted stuff put aside)

Anything else I can try? I tried comparing with curl (since git uses libcurl I understand), current curl does not have any major slowdowns when doing large POST over https

**Comment by dscho** [comment]
> What I see is that when not using a large buffer size, there data flows from "git pack-objects" to "git send-pack" to "git-remote-https". I.e. when I open the process statistics for each of those, I can see each reading/writing with the same rate as data goes over the network.

Hmm. I never thought that maybe communication between processes could be so slow. But given that it becomes relatively fast when you use a large postBuffer, I do not think that it is *actually* the IPC that is slow, I think it is just clogged up because `remote-https` does not drain its input fast enough.

I guess at this point, my expertise in the workings of the HTTPS transport are insufficient to help you further. Therefore I would like to suggest to summarize the findings in a mail to [the Git mailing list](mailto:git@vger.kernel.org) which has some active contributors with intimate knowledge of the inner workings of the transport layer.

**Comment by llehn** [comment]
Sounds good, I'll try that.
