### ISSUE TITLE
Git for Windows icon missing in 2.10.0

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#870]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Select Components: only select Windows Explorer integration - Git Bash Here
PATH: Use Git from the Windows Command Prompt
core.autocrlf: true
Terminal: MinTTY
Extra: Enable file-system caching

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Right click a directory in Windows Explorer. `Git Bash` is present but the icon is missing.
```
 - What did you expect to occur after running these commands?

`C:\Program Files\Git\mingw64\share\git\git-for-windows.ico` file exists after install.

 - What actually happened instead?

`C:\Program Files\Git\mingw64\share\git\git-for-windows.ico`  is missing

**Comment by CharlesCross** [comment]
Yes - the icon file is definitely missing from the 64-bit download.

**Comment by CharlesCross** [comment]
WORKAROUND:

Don't know what else might be missing - your probably safer downloading Git-2.9.3.2-xx-bit.exe from section Git for Windows 2.9.3(2) in [https://github.com/git-for-windows/git/releases/](url).

Alternatively, you could try unziping and copy the attached file (git-for-windows.zip) to "C:\Program Files\Git\mingw64\share\git\git-for-windows.ico".  I have not tested this but it might work.

[git-for-windows.zip](https://github.com/git-for-windows/git/files/453535/git-for-windows.zip)

**Comment by dscho** [comment]
Yep, the file was removed by mistake. However there is no good reason to suggest a downgrade or to download a .zip.

The best workaround is to download the .ico directly from Git for Windows' repository: https://raw.githubusercontent.com/git-for-windows/MINGW-packages/636d775bde99e91f66071c84592ead18be6ad359/mingw-w64-git/git-for-windows.ico and move it to the location indicated in the initial report.

**Comment by dscho** [comment]
Let's wait a couple of days to see whether other bugs show up, before releasing v2.10.0(2).

Please use +1/-1 reactions on this comment to vote whether I should release a new version even if the missing icon should turn out to be the only major bug.

**Comment by dscho** [comment]
There is a prerelease now, please test: https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c

**Comment by knittl** [comment]
The pre-release fixed the problem for me (Windows 7 64 bit)

**Comment by sxlijin** [comment]
@dscho The prerelease installer works if I "Run as Administrator", but it's unhappy with me if I run it as a normal user (and also completely borks my existing Git installation):

![image](https://cloud.githubusercontent.com/assets/512410/18639449/954f2630-7e59-11e6-9591-cf87490bc971.png)

As a note, I do get a UAC prompt in the middle of the process

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64

$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

**Comment by manolenso** [comment]
Little Batch to restore icon in a 
right place 
[Restore Icon](http://www.testproject.manolenso.fr/restore-git-for-windows-icon.zip)

**Comment by dscho** [comment]
@manolenso please do not suggest to download random `.zip` files from untrusted sources. The proper work-around *really* is to download and install the pre-release: https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c

**Comment by manolenso** [comment]
Ok I’ll edit post.


De : Johannes Schindelin [mailto:notifications@github.com]
Envoyé : mardi 20 septembre 2016 16:17
À : git-for-windows/git <git@noreply.github.com>
Cc : LAURENT Rémy <rlaurent@tvmag.com>; Mention <mention@noreply.github.com>
Objet : Re: [git-for-windows/git] Git for Windows icon missing in 2.10.0 (#870)


@manolenso<https://github.com/manolenso> please do not suggest to download random .zip files from untrusted sources. The proper work-around really is to download and install the pre-release: https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c

**Comment by sxlijin** [comment]
@dscho another slight problem: if I uninstall `2.10.0.windows.1.11.geda474c` after installing it as an Administrator, the `%PROGRAMFILES%/Git` folder gets left behind, which makes the local user installer default to `%PROGRAMFILES%/Git` for an install location. I don't have this issue with `version 2.10.0.windows.1`.

**Comment by dscho** [comment]
@sxlijin if this problem persists with v2.10.1, please open a new ticket with a detailed report. Thank you!
