### ISSUE TITLE
Git for Windows 2.10.0 lost the icon file

### ISSUE THREAD

**Issue by wuyumin** [git-for-windows/git#872]
Git for Windows 2.10.0 lost the icon file “git-for-windows.ico” in path mingw64\share\git

**Comment by dscho** [comment]
Duplicate of https://github.com/git-for-windows/git/issues/870.

**Comment by cgrandsjo** [comment]
A manual workaround:

- Download **https://codeload.github.com/git-for-windows/build-extra/zip/master**
- In the ZIP file browse to **build-extra-master\portable\root\usr\share\git**
- Copy **git-for-windows.ico** to **%SystemDrive%\Program Files\Git\mingw64\share\git**
- Browse to **%SystemDrive%:\ProgramData\Microsoft\Windows\Start Menu\Programs\Git**
- Right click on the **Git Bash** shortcut
- Select **Properties**
- Click on  **Change Icon...**
- Select the **Git Bash** icon
- Click **OK**
- Click **OK**
- Now the correct icon should be associated with the Git Bash shortcut

**Comment by dscho** [comment]
A much better work-around is to download the prerelease: https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c

And please do not add comments to tickets marked as duplicates; add the comments to the ticket indicated as the original ticket describing the problem.
