### ISSUE TITLE
Icons not installed on Windows

### ISSUE THREAD

**Issue by rob-spoor** [git-for-windows/git#873]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.10586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install_options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

The icons that are supposed to be located in /mingw64/share/git, most notably git-for-windows.ico, are not installed. As a result, the Windows shortcuts show a generic icon instead of the Git icon.

**Comment by fourpastmidnight** [comment]
Please make sure you search open and closed issues before reporting an issue. Please see #872 where this was already been reported. Thanks.

**Comment by dscho** [comment]
Actually, it is a duplicate of https://github.com/git-for-windows/git/issues/870 (872 is itself a duplicate).
