### ISSUE TITLE
npm packages which come with CLI through git-bash return errors

### ISSUE THREAD

**Issue by h404bi** [git-for-windows/git#874]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing.
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

_I used version 2.9.4, then upgrade to  2.10.0, still have the problem. (reinstall doesn't resolve)_
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows 10 Build 14393.rs1_release_inmarket. 160819-1924
x86_64
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install_options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
Mintty / Bash
```
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
1. install git-for-windows
2. install node.js (I use LTS version v4.5.0)
3. install gulp through npm
   $ npm install -g gulp
4. run gulp in git-bash
   $ gulp -v
```
- What did you expect to occur after running these commands?

```
$ gulp -v
[22:05:33] CLI version 3.9.1
```
- What actually happened instead?

```
$ gulp -v
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\node_modules\gulp\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

ref:
1. [pipe is returning empty string in bash in git for windows](https://stackoverflow.com/questions/37643385/pipe-is-returning-empty-string-in-bash-in-git-for-windows) (_[Revisions](https://stackoverflow.com/revisions/37643385/11)_)
2. [Can't get Gulp to work on Git Bash](https://stackoverflow.com/questions/38258825/cant-get-gulp-to-work-on-git-bash)
3. [basedir incorrectly resolved on msysgit](https://github.com/ForbesLindesay/cmd-shim/issues/16)
4. [hexo init can't find module](https://github.com/hexojs/hexo/issues/1984)
5. [Other related Google search result](https://www.google.com/#q=%22C:%5CProgram+Files%5CGit%5Cnode_modules%22)

**Comment by dscho** [comment]
Does it work in `cmd`? In `Git CMD`?

**Comment by h404bi** [comment]
@dscho It works on `cmd` and `powershell`, but .

###### Git CMD
![image](https://cloud.githubusercontent.com/assets/5764917/18253087/9a7902d8-73c4-11e6-85cc-4b36a15f7173.png)

###### Mintty
![image](https://cloud.githubusercontent.com/assets/5764917/18253127/e2141ab0-73c4-11e6-9215-20f5511a698c.png)

**Comment by tiexo** [comment]
Cannot find module 'C:\Program Files\Git\node_modules\hexo-cli\bin\hexo

I encountered this problem more than six months, has repeatedly tried to resolve the last to nothing. Now after seeing your feedback gave me new ideas, before I do not know in cmd which is normal.

Do not know if there is a solution? Git bash still can not be used

![qq 20161010164222](https://cloud.githubusercontent.com/assets/8164505/19230703/8ae153de-8f08-11e6-800c-ce8ae2978c01.png)

**Comment by h404bi** [comment]
@tiexo Thanks for your feedback. I know there is a *workaround*, which enforce to let the `basedir` variable in the shell script to `.`

###### e.g. gulp:
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
basedir=.   <----------------------------------------------------

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/gulp/bin/gulp.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/gulp/bin/gulp.js" "$@"
  ret=$?
fi
exit $ret
```

I guess it maybe the msys runtime's problem. no idea..

**Comment by tiexo** [comment]
@h404bi thanks
After reading your solution, I think I am more suitable to use cmd ...
![image](https://cloud.githubusercontent.com/assets/8164505/19231636/b13933e4-8f0d-11e6-9b57-7efd64398181.png)

**Comment by h404bi** [comment]
Add references (that might be related): 
1. [Error on yo webapp Cannot find module 'C:\Program Files\Git\node_modules\yo\lib\cli.js'](https://github.com/yeoman/generator-webapp/issues/530) (git: unknown)
2. [grunt is throwing error in Git Bash - “cannot find module 'C:\Program Files\Git\node_modules\grunt\bin\grunt'”](http://stackoverflow.com/questions/39580561/grunt-is-throwing-error-in-git-bash-cannot-find-module-c-program-files-git) (git: 2.10.0 x64)
3. [git bash安装gulp报错，Error: Cannot find module](https://segmentfault.com/q/1010000007014204) (git: unknown)
4. [Script error on Git Bash (Windows)](https://github.com/bahmutov/pre-git/issues/68) (git: 2.7.1)

**Comment by dscho** [comment]
Please note that Git Bash primarily supports *Git* operations. So I throw the ball right back into node.js users' court.

But not without a couple of hints:

- As it works in cmd, I imagine calling `which gulp` in Bash will point to a *Unix shell script*, while calling `where gulp` in cmd probably points to a `.cmd` script.
- If it is a Unix shell script, calling it with `bash -x /path/to/gulp ...` might clarify where things go wrong.
- The absolute path to `node_modules` is the pseudo root `/` of Git Bash. Therefore, I assume something goes wrong from determining the current working directory to turning it into an absolute path in the `gulp` script.
