### ISSUE TITLE
Version 2.10.0 installer does not install Windows Icons

### ISSUE THREAD

**Issue by marcbaas** [git-for-windows/git#876]
I'm runing:
Windows 10 x64 Pro (anniversary edition)
Git for Windows x64, version 2.10.0

It seems that the 2.10.0 installer does not install icons for Windows.
When editing the thumbnail to change the icon it gives a warning that it cannot find the file
`%SystemDrive%\Program Files\Git\mingw64\share\git\git-for-windows.ico`

Manually checking that path reveals that no .ico files are present, nor could I find them somewhere else. The only present icons are git-gui.ico and msys2-32.ico.

Not critical, but it looks a bit off to have all Git related icons showing up 'white'.

**Comment by fourpastmidnight** [comment]
Please don't ignore the issue those and search for an open or closed issue before routing. Thank you for reporting this, though, please see issue #872 for more details.
