### ISSUE TITLE
v2.10.0 Mintty crash on options and missing icons

### ISSUE THREAD

**Issue by vmuriart** [git-for-windows/git#877]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

`2.10.0 64bit`

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

`Microsoft Windows [Version 6.3.9600] 64bit`

 - What options did you set as part of the installation? Or did you choose the
   defaults?

`Tried multiple including default`

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Fresh install

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

`Bash`

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Right click on explorer - Missing icon on context menu
Select > GIT GUI HERE
Open Options - Sometimes crashes here
Open Options\Terminal - Always Crashes


```
 - What did you expect to occur after running these commands?

Context menu have icons.  
Mintty not crash when looking at options

 - What actually happened instead?

Icons missing on `%SystemDrive%\Program Files\Git\mingw64\share\git\`

Mintty crashes

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

Verified by inspecting the tar.bz2 files and icon files are missing there as well.
Its possible that both issues are related.

Reverted to fresh install using 2.9.2 and no issues seen.

![image](https://cloud.githubusercontent.com/assets/13303020/18372751/b8acaba2-75f3-11e6-82b7-740f5ea7dbf2.png)

**Comment by vmuriart** [comment]
Verified that 2.9.3.tar.bz2 contains icons.

![image](https://cloud.githubusercontent.com/assets/13303020/18372792/07ddeccc-75f4-11e6-8528-49c7ba4427f2.png)

**Comment by fourpastmidnight** [comment]
Please see #872. This will be fixed in an upcoming release.
