### ISSUE TITLE
Suggestion: git submodule remove

### ISSUE THREAD

**Issue by webmaster33** [git-for-windows/git#88]
Hi GIT devs,

I really miss the
git submodule remove
command.

This should be handle all the tasks what are needed to remove a submodule.
- Delete the relevant line from the .gitmodules file.
- Delete the relevant section from .git/config.
- Run git rm --cached path_to_submodule (no trailing slash).
- Delete the now untracked submodule files.

These tasks should be handled automatically.
Currently you can only remove a submodule manually, no way to do it automatically with one command.
"Removing submodules" and "unsubmodule a submodule" are still a pain to do in GIT, even in v2.3.5.

Please consider implementing the "git submodule remove" command.

Thanks,
Konrad Lorinczi

**Comment by dscho** [comment]
This issue is not specific to Windows. Please report it to the Git mailing list: git@vger.kernel.org. Thanks!
