### ISSUE TITLE
Git-2.10.0-64-bit.exe can't find icons - Windows 10 Millenial

### ISSUE THREAD

**Issue by peterennis** [git-for-windows/git#880]
![capture001](https://cloud.githubusercontent.com/assets/140737/18402344/cf7f7878-7693-11e6-8633-492762a04a17.PNG)

**Comment by fourpastmidnight** [comment]
This will be fixed in an upcoming release. See #872.

**Comment by dscho** [comment]
Could you give https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c a try?

**Comment by peterennis** [comment]
This release worked.
Windows 10 MA with updates from yesterday.
Icons are good.

--------------------------------------------
On Sat, 9/10/16, Johannes Schindelin <notifications@github.com> wrote:

 Subject: Re: [git-for-windows/git] Git-2.10.0-64-bit.exe can't find icons - Windows 10 Millenial (#880)
 To: "git-for-windows/git" <git@noreply.github.com>
 Cc: "peterennis" <peterennis@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Saturday, September 10, 2016, 1:40 AM
 
 Could you give https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c
 a try?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
