### ISSUE TITLE
Error cloning https://github.com/IIJ-NetBSD/netbsd-src.git

### ISSUE THREAD

**Issue by Karlson2k** [git-for-windows/git#883]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

````
> git config core.longpaths
true
````

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD, TortoiseGit

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://github.com/IIJ-NetBSD/netbsd-src.git
```
 - What did you expect to occur after running these commands?

Cloned repo.

 - What actually happened instead?

````
fatal: cannot create directory at 'external/mit/xorg/lib/xcb-util/aux': Invalid argument
````
Download and deltas resolving is fine, error only on checkout.
Same error if later called `git reset --hard`
Moved repo to the root directory for testing - same result.
Without `core.longpaths` result is still the same.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/IIJ-NetBSD/

**Comment by sschuberth** [comment]
It fails because `aux` is an invalid file name on Windows. Also see [here](https://github.com/git-for-windows/git/issues/700#issuecomment-212488582) and [here](https://github.com/git-for-windows/git/issues/843#issuecomment-238658258).

**Comment by Karlson2k** [comment]
Thanks!
