### ISSUE TITLE
Git bash.exe is very slow on Windows 10

### ISSUE THREAD

**Issue by oyljerry** [git-for-windows/git#884]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

    2.10 64bit portable.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

  windows 10 64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?
   
   yes, default.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

   As check previous issue. I also installed Trend Micro Internet Security, when I disable it. bash.exe will run very quickly. but another interesting thins is that, I have installed git 2.8 version which can run very quickly even Trend Micro Internet Security enabled. but 2.10 version will run very slow when  Trend Micro Internet Security. 

   what is difference between these versions?

**Comment by PhilipOakley** [comment]
Some random thoughts...

Is this with the same version of Trend Micro Internet Security or has the versions of that kept pace with the Git versions?

One area that some have mentioned is the endless checking of the repository objects (blobs and packs etc) which are read only, and should be marked as being not a risk (if you can do that).

The other possibility is that the newer compilations just happen to be close to some virus file heuristic that means that the virus chacker spends more time on it.


  ----- Original Message ----- 
  From: Jerry 
  To: git-for-windows/git 
  Sent: Wednesday, September 14, 2016 10:01 AM
  Subject: [git-for-windows/git] Git bash.exe is very slow on Windows 10 (#884)


  Setup
    a.. Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

    2.10 64bit portable.

    b.. Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

    windows 10 64 bit

    c.. What options did you set as part of the installation? Or did you choose the
    defaults?

    yes, default.

    d.. Any other interesting things about your environment that might be related
    to the issue you're seeing?

    As check previous issue. I also installed Trend Micro Internet Security, when I disable it. bash.exe will run very quickly. but another interesting thins is that, I have installed git 2.8 version which can run very quickly even Trend Micro Internet Security enabled. but 2.10 version will run very slow when Trend Micro Internet Security. 

    what is difference between these versions?

**Comment by dscho** [comment]
My guess is that some changes in the MSYS2 runtime are responsible.

@oyljerry I am afraid I have to ask you to try a couple more versions from https://github.com/git-for-windows/git/releases in order to pinpoint *where* things get slow.

**Comment by fourpastmidnight** [comment]
FWIW, I use Trend Micro on my home machine and I do not experience any of this slowness.

There was a similar issue a while back: #786. When I initially installed v2.9.3 (I believe), the bash shell seemed to be ridiculously slow for me. But, after about a day, it mysteriously went away and I haven't had a problem since. It'll be interesting to see if anything else can be found with respect to this seemingly "random" issue. Perhaps @PhilipOakley is on to something with A/V not skipping checking the packs and objects...I should check that and report back.

**Comment by oyljerry** [comment]
@dscho 
When I run git-bash.exe, it is very slow, and I get below error message. 

'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libatomic-1         .dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libatomic-1.dll' and 'D:\Tools\PortableGit\mingw64/         libexec/git-core/libatomic-1.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libatomic-1.dll D:\Tools\PortableG         it\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libcares-2.         dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libcares-2.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libcares-2.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libcares-2.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libcurl-4.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libcurl-4.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libcurl-4.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libcurl-4.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libexpat-1.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libexpat-1.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libexpat-1.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libexpat-1.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libgcc_s_seh-1.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libgcc_s_seh-1.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libgcc_s_seh-1.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libgcc_s_seh-1.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libgmpxx-4.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libgmpxx-4.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libgmpxx-4.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libgmpxx-4.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libgomp-1.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libgomp-1.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libgomp-1.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libgomp-1.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libhogweed-4-1.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libhogweed-4-1.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libhogweed-4-1.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libhogweed-4-1.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libidn-11.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libidn-11.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libidn-11.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libidn-11.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libminizip-1.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libminizip-1.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libminizip-1.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libminizip-1.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libp11-kit-0.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libp11-kit-0.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libp11-kit-0.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libp11-kit-0.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/librtmp-1.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/librtmp-1.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/librtmp-1.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/librtmp-1.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libssp-0.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libssp-0.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libssp-0.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libssp-0.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libsystre-0.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libsystre-0.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libsystre-0.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libsystre-0.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libtre-5.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libtre-5.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libtre-5.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libtre-5.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/libvtv_stubs-0.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/libvtv_stubs-0.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/libvtv_stubs-0.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/libvtv_stubs-0.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/ssleay32.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/ssleay32.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/ssleay32.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/ssleay32.dll D:\Tools\PortableGit\mingw64/libexec/git-core
ln: failed to create hard link 'D:\Tools\PortableGit\mingw64/libexec/git-core/tk86.dll': File exists
cp: 'D:\Tools\PortableGit\mingw64/bin/tk86.dll' and 'D:\Tools\PortableGit\mingw64/libexec/git-core/tk86.dll' are the same file
ERROR: could not link D:\Tools\PortableGit\mingw64/bin/tk86.dll D:\Tools\PortableGit\mingw64/libexec/git-core

**Comment by oyljerry** [comment]
I found a very strange thing.
When I use 2.8.0, it works fine. however, when I use 2.10.1, it will be slow. however, after I copy all files in 2.10.1 folder to 2.8.0 folder, then start git-bash, but if I directly run git-bash.exe in 2.10.1 folder, it will be slow.

**Comment by dscho** [comment]
@oyljerry Is `git-bash.exe` slow also when you start it the second time?

The thing is, the portable version of Git needs to set up a few things when it runs the first time (such as hard-linking or copying certain `.dll` files so that files with the same name but living in the system directory cannot interfere with them. This is what you see when it says that the hard-linking failed.

Once this one-time task is done, however, the corresponding script will be deleted (unless there is a bug) and the second time, the Git Bash should start up as quickly as you'd expect.

**Comment by oyljerry** [comment]
@dscho when I download PortableGit-2.10.1-64-bit.7z.exe from website today, and click it to run, Trend Micro security will block it, and said "suspicious file block".

**Comment by dscho** [comment]
@oyljerry I have it from good authority (myself, I have "a very good brain" :laughing:) that the portable Git v2.10.1 is good. Since you are a customer of Trend Micro, you may want to notify them of their mistaken software?

**Comment by oyljerry** [comment]
Since I can copy and replace files of new version into old installed version, then it works fine, I have no problem about this issue now.
