### ISSUE TITLE
QuickEdit Mode Git 2.10

### ISSUE THREAD

**Issue by ncore21** [git-for-windows/git#887]
I've recently downloaded and installed Git 2.10 on Windows,  but I couldn't find the "QuickEdit Mode" check in Git Bash Options Windows, in order to copy and paste easily. 

Can you help me guys !!? , Please
Thanks in advance!

**Comment by nalla** [comment]
See http://superuser.com/a/138907

especially:
> First, consider using mintty instead of the standard console window. In mintty, selecting with the left-mouse also copies, and middle-mouse pastes. It couldn't be easier!
