### ISSUE TITLE
`git remote rename origin upstream` fails to fully rename

### ISSUE THREAD

**Issue by AArnott** [git-for-windows/git#888]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
  Windows 10, 64-bit

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```
- What options did you set as part of the installation? Or did you choose the
  defaults?
  All defaults.

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

No.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
git clone https://github.com/Microsoft/vscode-languageserver-node.git
cd .\vscode-languageserver-node\
git remote rename origin upstream
git remote rename upstream origin

```
- What did you expect to occur after running these commands?

Just one remote: `origin`
Also, if I add a `git remote` command in between the two renames, to see just one remote (`upstream`), but instead I see two (upstream and origin).
- What actually happened instead?

```
fatal: remote origin already exists.
```
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

It happens to all repos.

**Comment by shiftkey** [comment]
I've not been able to reproduce this with the same setup (Win10 14393, Powershell) on either the same build or the latest public release (2.11.0):

```
PS C:\Users\shiftkey\src\vscode-languageserver-node> git --version
git version 2.10.0.windows.1
PS C:\Users\shiftkey\src\vscode-languageserver-node> git remote -v
origin  https://github.com/Microsoft/vscode-languageserver-node.git (fetch)
origin  https://github.com/Microsoft/vscode-languageserver-node.git (push)
PS C:\Users\shiftkey\src\vscode-languageserver-node> $env:GIT_TRACE=1
PS C:\Users\shiftkey\src\vscode-languageserver-node> git remote rename origin upstream
14:53:57.835843 git.c:350               trace: built-in: git 'remote' 'rename' 'origin' 'upstream'
PS C:\Users\shiftkey\src\vscode-languageserver-node> git remote rename upstream origin
14:54:05.179284 git.c:350               trace: built-in: git 'remote' 'rename' 'upstream' 'origin'
PS C:\Users\shiftkey\src\vscode-languageserver-node> git remote -v
14:54:14.882547 git.c:350               trace: built-in: git 'remote' '-v'
origin  https://github.com/Microsoft/vscode-languageserver-node.git (fetch)
origin  https://github.com/Microsoft/vscode-languageserver-node.git (push)
PS C:\Users\shiftkey\src\vscode-languageserver-node>
```

@AArnott have you seen this since reporting this?

**Comment by AArnott** [comment]
Yes. I still see this. I'm currently running git for windows 2.10.2.windows.1

**Comment by AArnott** [comment]
My git configuration is as follows, in case that's relevant.

```
git config --list --global
alias.co=checkout
alias.ci=commit
alias.st=status
core.safecrlf=warn
core.preloadindex=true
core.fscache=true
core.autocrlf=true
push.default=simple
credential.helper=manager
user.email=andrewarnott@gmail.com
user.name=Andrew Arnott
remote.origin.prune=true
diff.tool=vsdiffmerge
difftool.prompt=true
difftool.vsdiffmerge.cmd="C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\vsdiffmerge.exe" "$LOCAL" "$REMOTE" //t
difftool.vsdiffmerge.keepbackup=false
merge.tool=vsdiffmerge
mergetool.prompt=true
mergetool.vsdiffmerge.cmd="C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\vsdiffmerge.exe" "$REMOTE" "$LOCAL" "$BASE" "$MERGED" //m
mergetool.vsdiffmerge.trustexitcode=true
mergetool.vsdiffmerge.keepbackup=false
rebase.autosquash=true
rerere.enabled=true
gui.recentrepo=C:/git/roslyn
```

**Comment by AArnott** [comment]
@jrbriggs identified the problem as my `remote.origin.prune=true` config setting. He advised I replace it with `fetch.prune=true`.
This eliminated the repro.

**Comment by shiftkey** [comment]
@AArnott thanks for following up, and I'm glad you were able to get to the bottom of it!
