### ISSUE TITLE
3e

### ISSUE THREAD

**Issue by RahmadaniBayuAji** [git-for-windows/git#890]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
_TODO_
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
_TODO_
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
_TODO_
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 _TODO_

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 _TODO_

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
TODO
```
 - What did you expect to occur after running these commands?

 _TODO_

 - What actually happened instead?

 _TODO_

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 _TODO_

**Comment by PhilipOakley** [comment]
Accidental pocket dial response?? @RahmadaniBayuAji could you close this or fill in the template please.
