### ISSUE TITLE
Git Bash not starting on Windows 10 x64

### ISSUE THREAD

**Issue by doctapp** [git-for-windows/git#891]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x64
```
Note that I'm currently running x86 version which works on Windows 10 and x64 doesn't (tested with another user/Windows 10 64-bit setup).

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.10586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```
Tried various options with same problem.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

We are two users with the same problem running two separate Windows 10 64-bit setups.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash (CMD works, but Bash window just won't start)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git-bash.exe from CMD
Double-click Git-Bash shortcut
```
 - What did you expect to occur after running these commands?

Git Bash/MING64 window opens with bash prompt.

 - What actually happened instead?

Nothing

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Any

**Comment by vmuriart** [comment]
Have you tried the [pre-release](https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c)? I had a similar issue that was fixed there.

**Comment by doctapp** [comment]
I tried the latest pre-release (Git-prerelease-2.10.0.windows.1.11.geda474c-64-bit.exe) and have the same behavior: Git Bash window just won't start. 32-bit works fine.
Any other idea I can try?

**Comment by CameronGo** [comment]
@doctapp You didn't mention an error message in your issue, but I'm curious if your issue is at all related to the one I just posted: https://github.com/git-for-windows/git/issues/898

**Comment by doctapp** [comment]
@CameronGo I didn't mention any as there are none: when I double-click the Git Bash link or exe, nothing happends. On the 32-bit version, the terminal window starts normally. On Windows 7, everything worked fine.

**Comment by CameronGo** [comment]
ok must be a different issue then

**Comment by dscho** [comment]
@doctapp does the task manager show git-bash.exe running?

**Comment by doctapp** [comment]
No, nothing.

**Comment by vmuriart** [comment]
Does 2.9 work ?

**Comment by dscho** [comment]
> No, nothing.

Next try: what happens when you call

```cmd
git -c alias.b=!bash b -l -i
```

in Git CMD?

**Comment by doctapp** [comment]
That worked, I can now start Git Bash! Don't know why this alias is
required, but that a fix I can live with.

Thanks

**Comment by dscho** [comment]
That is not the correct alias. It is the alias for starting Git Bash with the default Windows console (instead of MinTTY, which is Git Bash's default). It will require more work to find out what is going wrong there...

The next thing to try out would be `mintty.exe bash -l -i` in the Bash you successfully launched.

**Comment by doctapp** [comment]
That also worked starting a new MINGW64 window as a bash.exe.

**Comment by itsnotvalid** [comment]
Did you install [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about)?

**Comment by doctapp** [comment]
No, I didn't install bash on Ubuntu on Windows.

**Comment by dscho** [comment]
> git-bash.exe from CMD

Next question: If you start this, what is the `%ERRORLEVEL%`? Also: could you run [ProcMon](https://technet.microsoft.com/en-us/sysinternals/bb896645) while trying to launch `git-bash.exe`? Maybe that would shed some light into the mystery...

**Comment by doctapp** [comment]
Since I ran the line `git -c alias.b=!bash b -l -i` everything works, so I don't know how I can reproduce the "old" environment to help out. How can I revert back?

**Comment by dscho** [comment]
@doctapp you mean to say that the regular *Git Bash* works now, too?

**Comment by doctapp** [comment]
Yes since I ran that command.

**Comment by dscho** [comment]
What I meant: running `git -c alias.b=!bash b -l -i` in *Git CMD* fixed running *Git Bash* from the Start Menu? I assume it did, but now I do not think we have any means to get at the root of the original problem anymore...

So let's close this ticket until the time when we can reproduce the problem again.
