### ISSUE TITLE
Git installation also installs Bash, even though I opted out explicitly

### ISSUE THREAD

**Issue by amn** [git-for-windows/git#892]
Noticed that even though I cleared all installation options (checkboxes), I still got the whole Mingw thing apparently, including vim (?!) and a whole lot of UNiX tools and of course Bash. I expected minimal installation excluding Bash, but instead it seems I got a whole lot of stuff. I wonder if it is as minimal as it gets? Still strange what Vim is doing there?

I have Cygwin installed from before, if I knew that Git for Windows is basically a contained UNiX environment with Git built on/for Windows, I would probably have skipped it :)

git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
Windows 10 Pro x64
Microsoft Windows [Version 10.0.10586]

All options were _cleared_ (i.e. no options selected, minimal installation)

C:\Program Files\Git\etc\install-options.txt:
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled

Terminal/shell: cmd.exe

**Comment by whoisj** [comment]
Git needs Bash. You did not opt out of getting Bash, you opt'd into putting Git into your CMD %PATH% variable.

Perhaps the verbiage on the Bash vs Command Prompt vs MinTTY needs some help, but Git needs Bash. Even MinGit (the smallest cross section of components to make a functional Git package) needs Bash.

**Comment by dscho** [comment]
To clarify, core Git commands such as `git submodule` and `git rebase` *require* Bash. Must be a misunderstanding that you can opt out of Bash.
