### ISSUE TITLE
git-for-windows icon is missing !

### ISSUE THREAD

**Issue by manolenso** [git-for-windows/git#893]
### Setup

 - Git-2.10.0-64-bit
- Windows seven

git-for-windows icon is missing !
context menu & desktop link

 git-for-windows.ico is  missing in " Program Files\mingw64\share\git\"

![gitbash](https://cloud.githubusercontent.com/assets/3215438/18645920/8cfd9d76-7eaf-11e6-91f3-87288e8a2dc8.png)

 

```

**Comment by PhilipOakley** [comment]
It's a known issue that has lots of other reports (try the search box?)

There is an interim fix linked in one of those other issues.

Philip
  ----- Original Message ----- 
  From: Laurent Rémy 
  To: git-for-windows/git 
  Sent: Monday, September 19, 2016 8:22 PM
  Subject: [git-for-windows/git] git-for-windows icon is missing ! (#893)


  Setup
    a.. Git-2.10.0-64-bit 
  git-for-windows icon is missing !
  in Program Files\mingw64\share\git\git-for-windows.ico

    a.. Windows seven

**Comment by dscho** [comment]
See #870 (which also did not simply delete the template, and hence has much more information than this here report).
