### ISSUE TITLE
upgrade 2.9->2.10, the icon in Right-button menu and task bar is incorrectly.

### ISSUE THREAD

**Issue by wugf0990** [git-for-windows/git#894]
After upgrade to 2.10 git-for-windows, in Win7 x64-bit system, I found the icon in Right-Button menu and task bar is incorrectly. It looks like that the icon of git has lost, and just display the default icon of windows.
But it's normal in v2.9.

**Comment by fourpastmidnight** [comment]
Please see #870 .
