### ISSUE TITLE
Support outputting help without a browser

### ISSUE THREAD

**Issue by mathstuf** [git-for-windows/git#895]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

#696 is about manpages specifically; I'm fine with just the text asciidoc output if that's more acceptable.

As part of some of our scripts, we run `git cmd --help | grep -e --some-option` to detect if an option is supported or not (since version checks are harder in Bash), but Git for Windows instead pops up the browser. I have tried to coax it into using `cat` as a man viewer (`git -c man.viewer=cat -c man.cat.cmd=`which cat` cmd --help`, but it just complains that it cannot execute `C:/Program Files/Git/usr/bin/cat` followed by the same for `man`).

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

x86_64

```
$ git --version --build-options
git version 2.9.0.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 x86_64

```
$ cmd.exe /c ver
6.1.7601
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I know of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push --help | grep -c -e '--option'
```
 - What did you expect to occur after running these commands?

Exit code to indicate that the option exists or not.

 - What actually happened instead?

Browser popped up

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No specific repo.

**Comment by kostix** [comment]
I think you just want `-h` not `--help` like with

    git push -h | grep -- --option

The `-h` command-line option makes the command itself output its usage summary.

And by the way, what exactly is hard with version checks in bash?
Could you please elaborate?

I mean, your present approach stinks IMO;
I think it would be better try to fix your version processing.

**Comment by mathstuf** [comment]
There's `sort -V`, but that doesn't work on macOS :( . `-h` does seem to work though.

**Comment by kostix** [comment]
But "what have you tried?"
I mean, [this](http://stackoverflow.com/a/39454220/720999) solution which is withing the first 3 hits of google search for version+sort+mac+os seems to work OK for me:

````
$ sort -t. -n -s
1.2.1
2.1.1
1.2.2
2.1.2
^D
1.2.1
1.2.2
2.1.1
2.1.2
````

That's GNU sort but I did not use `-V`.

**Comment by mathstuf** [comment]
Well, I was probably too invested in the old approach rather than trying to get a real version sort to work, but that does not work the same (though this could be fixed with `cut -d' ' -f3`, at this point just grepping `-h` is, IMO, less gymnastics. Anyways, `-h` is sufficient for me; closing, thanks.

`sort -V`:

```sh
% sort -V
git version 1.8.5      
git version 1.10.3
git version 2.8.4
git version 1.20.5
^D
git version 1.8.5
git version 1.10.3
git version 1.20.5
git version 2.8.4
```

`sort -t.`:

```sh
% sort -t. -n -s
git version 1.8.5
git version 1.10.3
git version 2.8.4
git version 1.20.5
^D
git version 1.8.5
git version 1.10.3
git version 2.8.4
git version 1.20.5
```
