### ISSUE TITLE
Windows 10 and Azure AD - Error: could not fork child process: There are no available terminals (-1).

### ISSUE THREAD

**Issue by CameronGo** [git-for-windows/git#898]
I believe this is the same issue reported and resolved with Cygwin here: https://cygwin.com/ml/cygwin/2016-08/msg00346.html and discussed here:
https://github.com/mintty/mintty/issues/563

If you run git-bash by opting to "Run as Administrator" and then accept the UAC prompt, then it opens as expected.

I wasn't able to determine whether there is a way to update the Cygwin package for this independently of a Git for Windows update.

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Joined to Microsoft Azure AD

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash mintty

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Execute git-bash.exe while logged in to an Azure AD user account
```
 - What did you expect to occur after running these commands?

arrive at git-bash prompt

 - What actually happened instead?

Error: could not fork child process: There are no available terminals (-1).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Please have a go with the prerelease: https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c

**Comment by dscho** [comment]
Ping?

**Comment by CameronGo** [comment]
Sorry for the delay.  I just tested and that version does fix the problem.  Thanks for the heads up!

**Comment by dscho** [comment]
Excellent!
