### ISSUE TITLE
Cygwin with git version 2.10.0.windows.1 keeps saying bash: /dev/tty: No such device or address, when doing `git push`

### ISSUE THREAD

**Issue by evandrocoan** [git-for-windows/git#903]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393.222]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"

$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Cygwin.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

### Cygwin with git version 2.10.0.windows.1 keeps saying bash: /dev/tty: No such device or address, when doing `git push`v

    $ git push
    bash: /dev/tty: No such device or address 
    error: failed to execute prompt script (exit code 1)
    fatal: could not read Username for 'https://github.com': Invalid argument

I found those related threads:

1. http://stackoverflow.com/questions/22147574/fatal-could-not-read-username-for-https-github-com-no-such-file-or-directo
1. http://stackoverflow.com/questions/21786633/init-script-dev-tty-no-such-device-or-address-error-on-redirect
1. http://stackoverflow.com/questions/6565357/git-push-requires-username-and-password

But I am not interested on their kludges as:

1. Not clone or use remotes not with `https://`.
1. Set up SSH keys.
1. Use wincred helper.
1. Use the build-in git for Cygwin.

I simply want to be able to clone with `https://` and to do my pushes with Git for Windows asking my username and password. This basically does not seens a git problem, but a Cygwin's one, as looks there is no `/dev/tty` input available to be read from. 

When I was using the Cynwin git, it was working fine, but that version is too old and bugged for subtrees and submodules working. So I uninstalled it and installed the latest git for windows from: git-scm.com/download/win

1. Is this impossible to be accomplished with Cygwin?
1. To get this problem solved without kludges, do I need to open feature request/bug report for Cygwin or for Git for windows?

___
 - What did you expect to occur after running these commands?

 To do the push.

 - What actually happened instead?

    $ git push
    bash: /dev/tty: No such device or address 
    error: failed to execute prompt script (exit code 1)
    fatal: could not read Username for 'https://github.com': Invalid argument

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 All cloned with `https://github.com/user/repo`.

**Comment by dscho** [comment]
Sadly, Cygwin's runtime and the MSYS2 runtime bundled in Git for Windows are incompatible, hence the `/dev/tty` emulation expected by Git for Windows is different from the `/dev/tty` emulation provided by Cygwin.

You can still use a credential helper as long as it has a GUI, though.

**Comment by evandrocoan** [comment]
Could git for windows provide support for the Cygwin `/dev/tty` emulation?

**Comment by nalla** [comment]
No. git for windows is based upon *msys2* which is itself is a fork of *msys*, with itself is a fork of *cygwin* but with a lot of improvements. You might want to look into *msys2* if it fits your needs where you are at the moment still *cygwin* depended.

**Comment by dscho** [comment]
Having said that, there *might* be a chance to support accessing Cygwin's emulation from MSYS2. However, this will require quite a bit of effort to bring about. @evandrocoan how prepared are you to spend time on this project?

**Comment by evandrocoan** [comment]
For now, I have no time.

Actually, I set up both ssh and wincred and I saving time not typing the username and password all the time. However, the git distributed with cygwin is working fine for this (it is just a old version). So I would just to take its latest version as 2.8.2 and to do a diff from windows default git.

Therefore, on the cygwin's git, it does not use the terminal to prompt the username and password. It opens a dialog box asking for the password. So, we could just to do the same, as cygwin's systems are not mean to be accessed by ssh connections.
