### ISSUE TITLE
[Portable] git pull doesn't work from git-cmd.bat

### ISSUE THREAD

**Issue by panta82** [git-for-windows/git#91]
I get this error:

```
The program can't start because libiconv2.dll is missing from your computer
```

There are lots of threads around the internet from 3-4 years ago with similar error. I don't think this is the same problem.

Either way, I followed their solution and copied the dll-s from `msysgit/bin` to `msysgit/libexec/git-core`. This is the error now:

```
trace: built-in: git 'rev-parse' '--git-dir'
trace: built-in: git 'rev-parse' '--is-bare-repository'
trace: built-in: git 'rev-parse' '--show-toplevel'
trace: built-in: git 'ls-files' '-u'
trace: built-in: git 'symbolic-ref' '-q' 'HEAD'
trace: built-in: git 'config' 'branch.master.rebase'
trace: built-in: git 'config' 'pull.rebase'
trace: built-in: git 'rev-parse' '-q' '--verify' 'HEAD'
trace: built-in: git 'fetch' '--update-head-ok'
trace: run_command: 'ssh' 'git@pantas.net' 'git-upload-pack '\''geogrid.git'\'''
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
```

As `git-bash.bat` works fine, it seems like it just doesn't get the proper %PATH% variable more than any problem with repository, config or binaries.

I played a bit with `/msysgit/libexec/git-core/pull`. The best I can tell, the pull bash script gets the correct environment when it is executed. So the problem is probably when `git-pull` calls `git-fetch.exe` and it tries to return from `bash` to `cmd`. Or something?

I tried manually mangling the PATH inside `git-pull` and also the trace env variable. Not sure what else can I try.

Version: Git-1.9.5-preview20150319
Tried on Windows 8.1 64-bit

**Comment by dscho** [comment]
> Git-1.9.5-preview20150319

You got the wrong bug tracker, then. This here project is the *successor* of msysgit (but maintained by the same people). Feel free to give [this](https://git-for-windows.github.io/#download) a spin.

**Comment by panta82** [comment]
Ok, got it. Managed to make it work with the 2.3 version.

If you're still maintaining 1.x family, though, you should probably still give that bug a look.

**Comment by nalla** [comment]
If you are happy with the solution @dscho layed out for you, I think this issue can be closed. If you think this is a bug in the *msysgit* environment, feel free to report it [here](https://github.com/msysgit/git/issues).

**Comment by panta82** [comment]
Yes, right. Closing the issue here.

**Comment by dscho** [comment]
@panta82 thanks for reporting the issue and for verifying that it works correctly in Git for Windows 2.x. Unfortunately, work on that latter project is taking all of my Git time these days. If you require Git for Windows 1.x to work, still, please feel free to give fixing https://github.com/msysgit/msysgit/blob/master/git-cmd.bat a try and open a Pull Request in that project if you are successful (I will gladly merge that work, possibly helping the Pull Request to get into a shape that it can be merged first).
