### ISSUE TITLE
Git 2.10.1 32-bit doesn't work on Windows XP

### ISSUE THREAD

**Issue by Eli-Zaretskii** [git-for-windows/git#911]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```32-bit
$ git --version --build-options
_TODO_
```
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86

I installed the latest version 2.10.1 for Windows, the 32-bit version, but it refuses to run on Windows XP SP3.  It pops up an error dialog saying "The procedure entry point CancelSynchronousIo could not be located in the dynamic link library KERNEL32.dll."

I very much hope Git for Windows will continue supporting Windows XP.

Thanks.

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
_TODO_
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
_TODO_
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 _TODO_

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 _TODO_

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
TODO
```
 - What did you expect to occur after running these commands?

 _TODO_

 - What actually happened instead?

 _TODO_

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 _TODO_

**Comment by nalla** [comment]
Please have a look at the [FAQs](https://github.com/git-for-windows/git/wiki/FAQ#which-versions-of-windows-are-supported). Windows XP is not supported anymore due to changes in the msys2-runtime.

**Comment by Eli-Zaretskii** [comment]
If the problem is with MSYS2 (as opposed to MinGW compiled Git programs), then how about not updating to the newer MSYS2 runtime?  Or at least making a separate installer that includes the latest msysgit with the MSYS2 runtime and programs that still support XP?
There are still many working installations of XP around the globe.  It would be nice if msysgit could continue supporting them.
Thanks.

**Comment by nalla** [comment]
@Eli-Zaretskii please read [the maintainers comment about this](https://github.com/git-for-windows/git/issues/906#issuecomment-251939610).

If you are willing to help, you could be that person responsible of maintaining a backwards compatibility release strung.

**Comment by dscho** [comment]
Duplicate of #906.

**Comment by dscho** [comment]
> It would be nice if msysgit could continue supporting them.

I said this before, and I will say this again, as often as necessary:

1. msysgit is dead. And you got it wrong, you were not talking about msysgit. Seriously, you talk about Git for Windows.
2. I agree that it would be nice to have XP support. But that does not come for free. If you want it, you have to do more than plea for others to put in the effort.

Mind you, I am not opposed to reinstate XP/2003 support. I would welcome it. I am just really opposed to doing it myself because I do not need it (and this is Open Source, if you want some feature, you make it happen).

**Comment by nalla** [comment]
@mfriedrich74 see my earlier comment: https://github.com/git-for-windows/git/issues/906#issuecomment-251902786

It was not in the release notes because the change was in latest cygwin release which we integrated via a recend msys2-runtime upstream rebase. So it was a bit hard to detect.
