### ISSUE TITLE
GIT_PROXY_COMMAND (and core.gitproxy)

### ISSUE THREAD

**Issue by ciis0** [git-for-windows/git#912]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen gitproxy OR git_proxy_command)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed gitproxy OR git_proxy_command) issue
   matching what I'm seeing.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git Bash, 64bit
```
$ git --version --build-options
git version 2.9.0.windows.1
```

MSYS2, 64bit
```
$ git --version --build-options
git version 2.9.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7, 64bit

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Can't use `https_proxy` with a HTTP Authentication proxy, Proxy keeps sending 407 and git fails with  `Unknown SSL protocol error in connection to ...`

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

  - Git Bash
  - MSYS2 (via ConEmu)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ env GIT_PROXY_COMMAND=echo git clone https://gist.github.com/dc59a80d4408424699ecde7b67095ab7.git
```
or
```
$ git config --global core.gitproxy echo
$ git clone https://gist.github.com/dc59a80d4408424699ecde7b67095ab7.git
```

 - What did you expect to occur after running these commands?

 See git failing because it cannot successfully `CONNECT` through `echo`.

 - What actually happened instead?

 Git uses the `https_proxy`, if set, otherwise still ignores `GIT_PROXY_COMMAND` / `core.gitproxy`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 https://gist.github.com/dc59a80d4408424699ecde7b67095ab7.git

**Comment by dscho** [comment]
> ```sh
> $ git config --global core.gitproxy echo
> $ git clone https://gist.github.com/dc59a80d4408424699ecde7b67095ab7.git
> ```
> 
> * What did you expect to occur after running these commands?
> 
> See git failing because it cannot successfully CONNECT through echo.

From https://git-scm.com/docs/git-config:

> [...]
> core.gitProxy::
>   A "proxy command" to execute (as 'command host port') instead of establishing direct connection to the remote server when using the Git protocol for fetching. [...]

In other words, the `core.gitproxy` config variable, as well as the `GIT_PROXY_COMMAND` variable, are supposed to affect Git's operation *when using the `git://` protocol*, not the HTTP/HTTPS protocols.

From the same page:

> http.proxy::
>   Override the HTTP proxy, normally configured using the *http_proxy*, *https_proxy*, and *all_proxy* environment variables (see `curl(1)`). In addition to the syntax understood by curl, it is possible to specify a proxy string with a user name but no password, in which case git will attempt to acquire one in the same way it does for other credentials. See gitcredentials[7] for more information. The syntax thus is *[protocol://][user[:password]@]proxyhost[:port]*. This can be overridden on a per-remote basis; see remote.<name>.proxy

My guess is that you wanted to use the `http.proxy` (or `remote.proxy` or `remote.<name>.proxy`) config variable.
