### ISSUE TITLE
Git Bash reuses Cygwin bash

### ISSUE THREAD

**Issue by rbenzinger** [git-for-windows/git#914]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.10586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I've installed Cygwin with its bash.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Start Git Bash.
```
 - What did you expect to occur after running these commands?

"MINGW64"

 - What actually happened instead?

"Cygwin ready."

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by dscho** [comment]
Are you absolutely sure that this is Cygwin's Bash? You can find out by calling `cygpath -w /` and `bash -version`.

**Comment by rbenzinger** [comment]
Hmm, sorry, you're right - I was confused by the looks, but this is, of course, shared between both bashes. m)

(My actual motivation behind this ticket was that Cygwin bash has issues with Cloud Foundry's cf command. It now turns out that Git Bash has, too.)
