### ISSUE TITLE
Could git provide multiple processing within one command

### ISSUE THREAD

**Issue by max-tian** [git-for-windows/git#916]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
MinGW

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
git clone

 - What did you expect to occur after running these commands?
I want to use one command to clone all of what I need repositories into one directory.

 - What actually happened instead?
I have to clone them one by one in different MinGW windows or create a bash script to combine each of git clone commands and execute it.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
It isn't for a specific repository.

**Comment by shiftkey** [comment]
> I want to use one command to clone all of what I need repositories into one directory.

This isn't the place to submit requests for new features. I think scripting is a "good enough" solution for this problem, but perhaps someone in [the Git community](https://git.wiki.kernel.org/index.php/GitCommunity) is sympathetic.

**Comment by max-tian** [comment]
So, this is just the place which only allowed to report issue to git-for-windows, not for git. Am I right?

**Comment by dscho** [comment]
@max-tian this bug tracker is intended to track bug reports that are Windows-specific, yes. And as the ratio between "people who ask" and "people who do" in this project is a little tilted, we try to steer people with feature requests toward the (non-Windows-specific) Git developer community.
