### ISSUE TITLE
:@ style credentials are not anymore supported

### ISSUE THREAD

**Issue by nilleb** [git-for-windows/git#92]
With git 1.9.5, I was able to type the following command
<pre>git clone http://<b>:@</b>server/_git/repo</pre>
the part `:@` was meaning: <i>use the credentials of the currently logged user</i>.
When the remote server exposes a website protected by windows authentication, git 1.9.5 uses the  KERBEROS ticket of the current user to authenticate.

I'm using portable git version 2.3.5.windows.8, x64.

I'm sorry, the server I'm using is not publicly accessible. I regret not to know a publicly accessible server doing kerberos authentication..

**Comment by dscho** [comment]
Could you run that with `GIT_TRACE=1`? I have the impression that the URL might get mangled by the overzealous POSIX-to-Win32 path conversion.

**Comment by nilleb** [comment]
K:\temp>git --version
trace: built-in: git 'version'
git version 1.9.5.msysgit.0

K:\temp>git clone http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository
trace: built-in: git 'clone' 'http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository'
Cloning into 'Repository'...
trace: run_command: 'git-remote-http' 'origin' 'http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository'
trace: run_command: 'fetch-pack' '--stateless-rpc' '--stdin' '--lock-pack' '--thin' '--check-self-contained-and-connected' '--cloning' 'http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository/'
trace: built-in: git 'fetch-pack' '--stateless-rpc' '--stdin' '--lock-pack' '--thin' '--check-self-contained-and-connected' '--cloning' 'http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository/'
remote:
remote:                    fTfs
remote:                  fSSSSSSSs
remote:                fSSSSSSSSSS
remote: TSSf         fSSSSSSSSSSSS
remote: SSSSSF     fSSSSSSST SSSSS
remote: SSfSSSSSsfSSSSSSSt   SSSSS
remote: SS  tSSSSSSSSSs      SSSSS
remote: SS   fSSSSSSST       SSSSS
remote: SS fSSSSSFSSSSSSf    SSSSS
remote: SSSSSST    FSSSSSSFt SSSSS
remote: SSSSt        FSSSSSSSSSSSS
remote:                FSSSSSSSSSS
remote:                  FSSSSSSs
remote:                    FSFs    (TM)
remote:
remote:  Microsoft (R) Visual Studio (R) Team Foundation Server
remote:
trace: run_command: 'index-pack' '--stdin' '-v' '--keep=fetch-pack 13744 on cgddsk18468' '--check-self-contained-and-connected' '--pack_header=2,27312'
trace: built-in: git 'index-pack' '--stdin' '-v' '--keep=fetch-pack 13744 on cgddsk18468' '--check-self-contained-and-connected' '--pack_header=2,27312'
Receiving objects: 100% (27312/27312), 67.36 MiB | 4.96 MiB/s, done.
Resolving deltas: 100% (22708/22708), done.

**Comment by nilleb** [comment]
K:\temp>set GIT_TRACE=1

K:\temp>git version
10:03:28.705027 git.c:348               trace: built-in: git 'version'
git version 2.3.5.windows.8

K:\temp>git clone http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository
10:05:03.718299 git.c:348               trace: built-in: git 'clone' 'http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository'
Clonage dans 'Repository'...
10:05:03.840747 run-command.c:351       trace: run_command: 'git-remote-http' 'origin' 'http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository'
fatal: Authentication failed for 'http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository/'

**Comment by dscho** [comment]
Ah, so it is *not* the POSIX-to-Windows path mangling.

I guess that our OpenSSL is not compiled with Kerberos support. If you do not mind, would you please re-run with `GIT_CURL_VERBOSE=1` and possibly trying `curl http://:@server:8080/tfs/COLLECTION/TeamProject/_git/Repository`?

**Comment by nilleb** [comment]
a bit longer:
2.3.5: https://gist.github.com/nilleb/7baab45de966c3f0b750
1.9.5: https://gist.github.com/nilleb/6e40ed16259e5a0b72e1

**Comment by dscho** [comment]
This looks indeed as if cURL needs to be compiled with some specific options.

At the moment, I have no time to look into this. If you want to to give it a try, please do not hesitate to install the [SDK](https://git-for-windows.github.io/#download-sdk), run the following commands to build a current cURL:

```sh
pacman -S base-devel
cd /usr/src/MINGW-packages
git fetch
git checkout master
cd mingw-w64-curl
makepkg-mingw -s
```

and then study [the history of Git for Windows 1.x' cURL](https://github.com/msysgit/msysgit/commits/master/src/openssl) to figure out which patch you need. My *guess* is that it is [this one](https://github.com/msysgit/msysgit/commit/d60a74aa6619f1ef3c051f75c5fc31d0a717e4df#diff-e1fc363fd3cfbb41e23d2308c212bea3R33).

**Comment by nalla** [comment]
You have to build with `MINGW_PACKAGE_PREFIX=mingw-w64-x86_64 MINGW_PREFIX=/mingw64 makepkg -s --skippgpcheck`. I created the package with the `--enable-sspi` added to the `PKGBUILD` file. But I have no way of testing it.

**Comment by dscho** [comment]
> You have to build with MINGW_PACKAGE_PREFIX=mingw-w64-x86_64 MINGW_PREFIX=/mingw64 makepkg -s --skippgpcheck.

Are you sure `makepkg-mingw -s --skippgpcheck` wouldn't do?

**Comment by nalla** [comment]
[`PKGBUILD#L7`](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-curl/PKGBUILD#L7) would imply it. Furthermore if you leave `MINGW_PREFIX` in [`PKGBUILD#L73`](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-curl/PKGBUILD#L73) out you would install the package in `usr/bin/curl` but that file belongs to the [MSYS2-package curl](https://github.com/git-for-windows/MSYS2-packages/tree/master/curl).

**Comment by nalla** [comment]
Jeah your're right. I forget about `makepkg-mingw` every time.

**Comment by dscho** [comment]
@nilleb I kinda wait for your answer... were you able to fix the problem?

**Comment by nilleb** [comment]
Sorry, I haven't enough time to investigate. I've been able to build
curl/libcurl using the commands you've suggested (warn: the pgp key is
unkown when building).

I've enabled sspi, by modifying the PKGBUILD script in
/usr/src/MINGW-packages/mingw-w64-curl.
`/usr/src/MINGW-packages/mingw-w64-curl/pkg/mingw-w64-x86_64-curl/mingw64/bin/curl
--version` says it supports SPNEGO, but I can't see any authentication
exchanges in the network traces (when called with --negotiate or with a :@
in the uri).

I must admin that I don't know how to recompile git using the produced
libcurl (and I haven't the time to RTFM).

Perhaps tomorrow.

On Mon, Apr 20, 2015 at 7:09 PM, dscho <notifications@github.com> wrote:

> @nilleb <https://github.com/nilleb> I kinda wait for your answer... were
> you able to fix the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/git-for-windows/git/issues/92#issuecomment-94511308>.
>



-- 
http://www.nilleb.com

**Comment by dscho** [comment]
> I must admin that I don't know how to recompile git using the produced libcurl

Once you rebuilt curl, you should be able to install it using `pacman -U mingw-w64-x86_64-curl-*.pkg.tar.xz`. After that, the Git executable should automatically use the updated curl.

**Comment by nilleb** [comment]
Thanks.
It works.

As a resume:
$ git diff PKGBUILD
diff --git a/mingw-w64-curl/PKGBUILD b/mingw-w64-curl/PKGBUILD
index 16164f3..cf8698e 100644
--- a/mingw-w64-curl/PKGBUILD
+++ b/mingw-w64-curl/PKGBUILD
@@ -77,6 +77,7 @@ build() {
     --without-random \
     --enable-static \
     --enable-shared \
+    --enable-sspi \
     "${_variant_config[@]}" \
     "${extra_config[@]}"
   make

**Comment by dscho** [comment]
@nilleb would you care to verify that 2.3.6.2 works correctly?

**Comment by nilleb** [comment]
works great.

**Comment by dscho** [comment]
Thanks for the feedback and your contribution!
