### ISSUE TITLE
If ssh-agent.exe is running, it prevents upgrades of Git for Windows 

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#920]
As we know that `ssh-agent.exe` is a daemon, we should simply kill it and move on.

The main problem I had with this is that it appears as if there _may_ be an `ssh-add.exe` running at the same time, _and_ a second `ssh-agent.exe` process, both of which are not shown by MSYS2's own `ps -W`. But the Task Manager sees them and the user can kill them interactively.

Hopefully we can teach the installer to kill silently any of Git's own `ssh-agent.exe` and/or `ssh-add.exe`. The chances are good: We already show such processes successfully in the wizard page that prevents the installer from running, after all.

**Comment by landstander668** [comment]
For what it's worth, _ssh-pageant.exe_ should probably be handled in the same way. It has essentially the same impact and is reported the same way when upgrading, although I wouldn't expect to find the _ssh-add.exe_ and/or second agent processes in that case.
