### ISSUE TITLE
Let's add an install option to turn on `core.symlinks`

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#921]
It is possible to allow users other than administrators to create symlinks, via modifying [the corresponding group policy](https://github.com/git-for-windows/git/wiki/Symbolic-Links#allowing-non-administrators-to-create-symbolic-links).

So let's offer this as an option on the "advanced option" page, and for extra goodness, let's use InnoSetup's [`ExecAsOriginalUser()` function](http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_execasoriginaluser) to test whether the calling user account is permitted to create symbolic links.

We may need to be careful to handle the case where the installer is run from an elevated account to begin with, in which case the test would be meaningless. We should detect that situation and fall back to the previously chosen setting, defaulting to "false".

Granted, the group policy could be changed later, or other users who lack the permission may run into trouble, but we do need to trust people who run the installer to know what they are doing.

**Comment by rienaldie** [comment]
Aktifkan
