### ISSUE TITLE
PortableGit-2.10.1-64-bit.7z.exe fails to install and causes a loop of appcrashes of doskey.exe

### ISSUE THREAD

**Issue by Drugoy** [git-for-windows/git#922]
- [v] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

PortableGit-2.10.1-64-bit.7z.exe
Windows 7SP1x64 (Microsoft Windows [Version 6.1.7601])

Luckily, I know why those crashes occur:
I like to have my custom aliases for cmd.exe.
Aliases are created using doskey command.
One may create a .bat or .cmd shell script with his lovely aliases, but it is a PitA to manually execute that script each time one uses cmd shell, so there's a way to make it autostart for each cmd shell session. This way requires creating a key `"AutoRun"="c:\\path\\to\\this\\file.cmd"` in `HKEY_CURRENT_USER\Software\Microsoft\Command Processor` section of registry, which I did.

So, please, teach your installers to backup that key, then remove it, then unpack the stuff needed to install git-for-windows and then restore that key.

**Comment by dscho** [comment]
Given that this is a very specific setup, and given that it is kind of self-inflicted, I will have to defer the solution to you: if you can come up with a clean, correct Pull Request to fix the portable Git in your scenario, I will gladly merge it.

For documentation how to get started making your own portable Git, please refer to our wiki: https://github.com/git-for-windows/git/wiki/Making-a-portable-Git

**Comment by landstander668** [comment]
@Drugoy Does your alias script produce any output when it's run? A quick test under Windows 7 64-bit seems to indicate that it causes some sort of issue when installing PortableGit in that case (although I didn't see any crashes), but everything worked as expected when the script was completely silent. 

If that's the case, please be aware that a chatty AutoRun script can apparently [cause problems](https://gist.github.com/vladikoff/38307908088d58af206b#gistcomment-1846915) completely unrelated to Git for Windows. So it's probably a good idea to ensure that it runs silently in any event.

**Comment by landstander668** [comment]
For reference, here's what I did for my test.

- Create an aliases script as `%USERPROFILE%\aliases.cmd`

```
@echo off
doskey ls=dir $*
echo test
```

- Configure it to be run automatically via registry key

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Command Processor]
"AutoRun"="%USERPROFILE%\\aliases.cmd"
```

- Install PortableGit-2.10.1-64-bit.7z.exe in the usual manner (double-click and select a destination). No errors were reported.

- Run _git-bash.exe_ from the newly installed portable directory. The first invocation (only) yields the following messages, immediately before displaying the shell prompt.

```
mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue': Permission denied
'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
```

If I delete the installation and repeat all of the above steps with the `echo test` line removed from _aliases.cmd_ (or commented out), then the first run of _git-bash.exe_ goes immediately to the shell prompt without displaying any of the messages above.

Please note that I haven't checked for breakage in the various Git commands, in the case of the chatty AutoRun script... just that there's a visible post-install difference which includes some error messages. So I don't know the full impact.

**Comment by Drugoy** [comment]
@landstander668
> Install PortableGit-2.10.1-64-bit.7z.exe in the usual manner (double-click and select a destination). No errors were reported.

That's the step on which I got the errors (maybe not an eternal loop, but just a bunch of them).

I guess it's not about the script being chatty (mine one is silent too, it has `@echo off`), it's probably about creating using unix utils names for aliases: I have created aliases for `find`, `ls`, `ifconfig`, `grep` , `cat`, `mv`, `cp` and `cd` and they rely on `find`, `dir`, `ipconfig`, `findstr`, `type`, `move` and `copy` respectively.

Feel free to close this issue if you think it's not worth doing, as I'm not competent enough as to propose a pull request with a fix for the installer.

**Comment by dscho** [comment]
> Feel free to close this issue if you think it's not worth doing, as I'm not competent enough as to propose a pull request with a fix for the installer.

I have little hope for this issue if you do not indicate even a willingness to learn enough to fix the issue for yourself...

**Comment by Drugoy** [comment]
The fix should be trivial, but no, I'm not going to manually learn how to create config scripts for 7zip self extracting archives.
