### ISSUE TITLE
Where is the git html documenation created and stored (within the github repos)

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#923]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

Where in the guthub repositories is the HTML help pages stored that are included in the regular installations?

in http://public-inbox.org/git/xmqqa8dyeebj.fsf@gitster.mtv.corp.google.com/T/#t I reported to the main Git list the potential tool chain issue with the ascii art in git-merge-base. This fault is evident both on git-scm and in my GfW installation, however Junio reports no problem with his tool chain output https://htmlpreview.github.io/?https://github.com/gitster/git-htmldocs/blob/master/git-merge-base.html 

This is a quick question to begin tracking down the divergence of the tool chains in their processing of tabs within ascii art (I remember when tabs are/were 1" spaced on teletypes!)

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git version 2.10.0.windows.1  (XP 32 bit)
```
$ git --version --build-options
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
XP sp3 32 bit
```
$ cmd.exe /c ver

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults, but bash only
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
_TODO_
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

have SDK also installed

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git help merge-base
```
 - What did you expect to occur after running these commands?

the criss-cross merge ascii art would be formatted correctly (8 space tabs)

 - What actually happened instead?

the arms of the criss-cross are not aligned when viewing the displayed html
file:///C:/Program Files/Git/mingw32/share/doc/git-doc/git-merge-base.html
(this maybe the clue - need to look at the MinGW32 repo?)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no.

**Comment by nalla** [comment]
The html help pages are being generated by asciidoctor.

**Comment by PhilipOakley** [comment]
I'm generally wondering: Where is the generation step in the release process, and where is it stored? Or is it only created temporarily and then stored within the release.exe file? i.e. is there a github page that shows the created GfW html code?

I did a bit more search and found that aciidoc and asciidoctor may be incompatible for this case https://github.com/git/git/blob/master/Documentation/git-merge-base.txt#L119-L123 vs https://git-scm.com/docs/git-merge-base (look at the same diagram).

http://asciidoctor.org/docs/user-manual/#migrate-deprecated (#96.3) and http://asciidoctor.org/docs/user-manual/#normalize-block-indentation (#31.6) suggest that the leading tabs vs spaces produces differing answers (you need an editor that show the distinct spaces and tabs to easily see the difference).

It will all depend on how friendly Junio is to the aciidoc / asciidoctor compatibility issues.

**Comment by dscho** [comment]
> Where is the generation step in the release process,

https://github.com/git-for-windows/MINGW-packages/blob/23d89486c108cb158e3ce9055d2f2216881ae530/mingw-w64-git/PKGBUILD#L111-L124

> and where is it stored?

Not on GitHub, but in our Pacman repository: https://bintray.com/git-for-windows/pacman/mingw-w64-x86_64-git-doc-html

> is there a github page that shows the created GfW html code?

No.

> It will all depend on how friendly Junio is to the aciidoc / asciidoctor compatibility issues.

Yes, this is indeed the tricky question.

**Comment by PhilipOakley** [comment]
@dscho Thank you for that info. I see that the documentaion is all tar'd and gzipped up, so not easy to use as a public reference to html files in the same way as Junio's https://github.com/gitster/git-htmldocs. Junio has now taken the patch, so that's one down. I'm reviewing the other ascii art where possible - it's not easy to detect automatically. 

@nalla thank you for the updated answer with the links. I hadn't seen it earlier, as it was an edit rather than a reply (one of those github small failings).

Philip

**Comment by dscho** [comment]
> I see that the documentaion is all tar'd and gzipped up, so not easy to use as a public reference to html files in the same way as Junio's https://github.com/gitster/git-htmldocs.

Unfortunately true...
