### ISSUE TITLE
64-bit Git for Windows installer appears to install wrong binaries for winpty

### ISSUE THREAD

**Issue by jkobylec** [git-for-windows/git#926]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

64-bit Windows 7

```
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing in particular.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
winpty
node (which Git Bash adds an alias to, to run under winpty)
```

 - What did you expect to occur after running these commands?

winpty: show winpty usage
node: run node under winpty

 - What actually happened instead?

```
C:/Program Files/Git/mingw64/bin/winpty.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no specific repository.

I was able to resolve the problem by replacing the winpty binaries installed by the Git for Windows 64-bit installer with the winpty 0.4.0 binaries for 64-bit MSYS2. The timestamp of the files installed by the Git installer appears to match that of the 32-bit binaries (although I haven't done checksum...)

Is it possible the Git for Windows 64-bit installer is installing the wrong winpty binaries?

**Comment by dscho** [comment]
I just tested this and it seems to work here...

```sh
me@work MINGW64 ~
$ which winpty
/usr/bin/winpty

me@work MINGW64 ~
$ sha256sum.exe /usr/bin/winpty.exe
347511476833c756b45d50e6ef1f073ec80b62a04f4f7075be6c22b5eeafd8bd */usr/bin/winpty.exe

me@work MINGW64 ~
$ winpty
Usage: winpty [options] [--] program [args]

Options:
  -h, --help  Show this help message
  --mouse     Enable terminal mouse input
  --showkey   Dump STDIN escape sequences
  --version   Show the winpty version number

me@work MINGW64 ~
$ winpty --version
winpty version 0.2.2-dev
commit none
```

This is Git for Windows v2.10.1 on Windows 10...

**Comment by dscho** [comment]
FWIW the next Git for Windows version will ship with an updated `winpty` (as a rule, I always update the MSYS2 packages before building the newest Git for Windows installer).

**Comment by jkobylec** [comment]
I reapplied the installer and it's still the correct binary, so we may not have a repro here. Sorry about raising a red herring...

**Comment by dscho** [comment]
Are you saying it is magically fixed? 😃 If so, yay!, and let's close it.

**Comment by jkobylec** [comment]
Non-reproable environment issue...

**Comment by jkobylec** [comment]
Meant to close :)

**Comment by mriehema** [comment]
Hi @dscho, I have problem with winpty since some time. Today I removed Git and installed a fresh copy if it. 

My Setup:
```
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
Microsoft Windows [Version 6.1.7601]
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled

$ which winpty
/usr/bin/winpty

$ sha256sum.exe /usr/bin/winpty.exe
aa2bf55f7f444ad5a0e64033a3ec54cba722756634bf8b51b320e55b0d73291b */usr/bin/winpty.exe

$ winpty
Usage: winpty [options] [--] program [args]

Options:
  -h, --help  Show this help message
  --mouse     Enable terminal mouse input
  --showkey   Dump STDIN escape sequences
  --version   Show the winpty version number

$ winpty --version
winpty version 0.4.0-dev
commit none
```

But when I run `$ winpty node --version` my Git-Bash is broken. No response and it just jumpes bach to $. But no I can't enter anything. All I can do is CTRL+D to close it. It is the same behavoir to call node without winpty.

```
$ which node
/c/Program Files/nodejs/node

C:\Users\mriehema>node --version
v6.9.1
```

Any ideas?

**Comment by dscho** [comment]
@mriehema is this a separate problem? If so, it would be the correct thing to open a new ticket (and diligently fill out  the issue reporting template).

**Comment by mriehema** [comment]
Done, see #961.
