### ISSUE TITLE
Default HOME path changes when running as an administrator or an unprivileged user when HOMEDRIVE points to a share

### ISSUE THREAD

**Issue by splatteredbits** [git-for-windows/git#927]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git: 2.10.0.windows.1 64-bit. Windows 

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Our IT department points our home drives to an Windows file share that gets mapped to a drive, e.g.

```
\\file_server\Users\me -> H:\
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD.exe and PowerShell.exe

 - What commands did you run to trigger this issue? 
* Create a drive that points to a Windows file share.
* Set the HOMEDRIVE environment variable to `DRIVELETTER:`. Set the HOMEPATH environment variable to `\`.
* Put your SSH keys in %USERPROFILE%\.ssh.
* Open an elevated command prompt (i.e. Run as Administrator). `cd` into a Git repository that uses SSH. Run `git pull`. Notice that the command succeeds.
* Open an unprivileged command prompt. `cd` into the same Git repository from the previous step and run `git pull`. Notice that the command fails because it can't find your ssh keys. If you open Process Monitor (from Sysinternals) you'll see that when running from an unprivileged command prompt, ssh keys are read from %HOMEDRIVE%%HOMEPATH%.

 - What did you expect to occur after running these commands?

I expect that my ssh keys are read from the same location no matter what type of prompt I'm running from. This location should be `%USERPROFILE%\.ssh`.

 - What actually happened instead?

My SSH keys are read from different locations depending if I'm running as an administrator or not.

**Comment by dscho** [comment]
> I expect that my ssh keys are read from the same location no matter what type of prompt I'm running from. This location should be %USERPROFILE%\.ssh.

That is an incorrect assumption, as you are changing the user account from which you run, and SSH configuration is stored per user.

> If you open Process Monitor (from Sysinternals) you'll see that when running from an unprivileged command prompt, ssh keys are read from %HOMEDRIVE%%HOMEPATH%.

This is by design and you can easily override it by setting your `HOME` variable explicitly to the path you want Git to use as your home directory.

We introduced that handling *specifically* to account for setups with roaming home directories where `%USERPROFILE%` points to a directory that the users do *not* want to use as their home directories.

**Comment by splatteredbits** [comment]
I'm not changing my  user account. I'm elevating a process and changing my security token.

From an unprivileged PowerShell prompt:

````
> whoami ; $env:USERNAME ; $env:HOMEDRIVE; $env:HOMEPATH ; $env:USERPROFILE
DOMAIN\USERNAME
USERNAME
H:
\
C:\Users\USERNAME
````

From a privileged, elevated PowerShell prompt:

```
> whoami ; $env:USERNAME ; $env:HOMEDRIVE; $env:HOMEPATH ; $env:USERPROFILE
DOMAIN\USERNAME
USERNAME
H:              
\               
C:\Users\USERNAME
```

In most cases, HOMEDRIVE and HOMEPATH point to USERPROFILE, except when it doesn't (for us). In our case, we now have to maintain all our Git and SSH configuration in two spots: HOMEDRIVE/HOMEPATH and USERPROFILE.

I noticed the HOME environment variable, but it is a generic-enough name that I'm worried how it will affect other software. I wish it was called GIT_USER_HOME or something.

**Comment by dscho** [comment]
Elevating a process means running it as administrator, I.e. as a different user.

And unfortunately, we are not only talking about Git here: ssh, or for that matter, the Bash, also want to use that environment variable, so it would be inappropriate to have a GIT_ prefix.

Besides, we use HOME for years now. Changing it would break quite a few setups.

You *could* write a simple .cmd script that overrides HOME and then starts the Git Bash, of course. That way, you do not have to define that variable globally.

**Comment by jberezanski** [comment]
@dscho I do not disagree with your decision regarding this issue (I understand your concern for backward compatibility; myself I work around the issue by setting HOME in my PowerShell $profile), however I do not fully agree with this statement:

> Elevating a process means running it as administrator, I.e. as a different user.

Elevating a proces means running it with a security token that contains the Administrators group SID, not neccessarily as a different user. There are two scenarios possible here:

1) The user account is not a member of the Administrators group. When the user attempts to elevate a process, the system requests the user to provide credentials of another account, one that is a member of the Administrators group. The elevated process runs under the identity of the second user account.

2) The user account is a member of the Administrators group. When the user logs on, the system creates two access tokens: a normal, full token (containing SIDs of all groups, including Administrators) and a restricted token, in which the SID of the Administrators group is marked as "deny only", i.e. may only be used to deny access, not to grant it. Explorer and all processes started from it by the user run under the restricted token. When the user attempts to elevate a process, the system requests permission from the user, and, upon obtaining it, starts the process using the full token of the user. The elevated process runs under the identity of the same user account that started the elevation (same user SID, same %USERPROFILE%), but with higher privileges (thanks to having the SID of the Administrators group fully enabled in the token). The process is detailed [here](https://technet.microsoft.com/en-us/library/dd835561(v=ws.10).aspx).

The second one is probably the most typical home user scenario, but will also be encountered at businesses when employees are allowed administrative access to their workstations (common for developers). It is also the scenario that @splatteredbits described.

@splatteredbits a tip: for logging purposes, `whoami /all | sls S-1-5-32-544` will clearly show the difference between the state of the Administrators group SID in both tokens.
