### ISSUE TITLE
clone fails as checkout encounters folders with trailing space

### ISSUE THREAD

**Issue by shiftkey** [git-for-windows/git#929]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
$ git clone https://github.com/hakkens/precious-plastic-kit
```
- What did you expect to occur after running these commands?

Clone completes without error.
- What actually happened instead?

```
Cloning into 'precious-plastic-kit'...
remote: Counting objects: 283, done.
remote: Total 283 (delta 0), reused 0 (delta 0), pack-reused 283
Receiving objects: 100% (283/283), 78.68 MiB | 157.00 KiB/s, done.
Resolving deltas: 100% (72/72), done.
fatal: cannot create directory at '1. Intro/Logo /Flag': No such file or directory
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

I'll come back with more information about how far back this goes to then isolate where this might have been introduced, but I wanted to open this up first to confirm there isn't some limitation with the Windows APIs that we cannot work around in GfW for repositories like this.

**Comment by shiftkey** [comment]
Reproducible on `git version 2.6.4.windows.1` 🤔

**Comment by PhilipOakley** [comment]
Probably invalid characters in the path name, either the '/' or the trailing space 'Logo '.
  ----- Original Message ----- 
  From: Brendan Forster 
  To: git-for-windows/git 
  Sent: Friday, October 28, 2016 8:35 PM
  Subject: [git-for-windows/git] clone fails as checkout encounters folders with trailing space (#929)


    a..  I was not able to find an open or closed issue matching what I'm seeing 
  Setup
    a.. Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
a.. Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? 
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
a.. What options did you set as part of the installation? Or did you choose the defaults? 
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Details
    a.. Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other 
  Bash

    a.. What commands did you run to trigger this issue? If you can provide a Minimal, Complete, and Verifiable example this will help us understand the issue. 
$ git clone https://github.com/hakkens/precious-plastic-kit
a.. What did you expect to occur after running these commands? 
  Clone completes without error.

    a.. What actually happened instead? 
Cloning into 'precious-plastic-kit'...
remote: Counting objects: 283, done.
remote: Total 283 (delta 0), reused 0 (delta 0), pack-reused 283
Receiving objects: 100% (283/283), 78.68 MiB | 157.00 KiB/s, done.
Resolving deltas: 100% (72/72), done.
fatal: cannot create directory at '1. Intro/Logo /Flag': No such file or directory
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
I'll come back with more information about how far back this goes to then isolate where this might have been introduced, but I wanted to open this up first to confirm there isn't some limitation with the Windows APIs that we cannot work around in GfW for repositories like this.

**Comment by shiftkey** [comment]
`2.5.3.windows.1` (first stable release of Git 2.x) also fails, but interestingly `1.9.5.msysgit.1` fails in a different way:

```
$ git clone https://github.com/hakkens/precious-plastic-kit.git
Cloning into 'precious-plastic-kit'...
remote: Counting objects: 283, done.
remote: Total 283 (delta 0), reused 0 (delta 0), pack-reused 283
Receiving objects: 100% (283/283), 78.68 MiB | 939.00 KiB/s, done.
Resolving deltas: 100% (72/72), done.
Checking connectivity... done.
error: Invalid path '1. Intro/Logo /Flag/flag_color.eps'
error: Invalid path '1. Intro/Logo /Flag/flag_color.png'
error: Invalid path '1. Intro/Logo /Flag/flag_lasercut version.eps'
error: Invalid path '1. Intro/Logo /Flag/flag_lasercut version.png'
error: Invalid path '1. Intro/Logo /Name/Name.eps'
error: Invalid path '1. Intro/Logo /Name/Name_black.png'
error: Invalid path '1. Intro/Logo /Name/Name_white.png'
error: Invalid path '1. Intro/Logo /Precious Plastic Logo.eps'
error: Invalid path '1. Intro/Logo /Precious Plastic Logo.png'
```

These are probably the same underlying error, just Git 2.x is a bit more clear about what's happening...

**Comment by jeffhostetler** [comment]
The Win32 layer does not allow a final space (or dot) in a component name.  And it may trim them off.  The NTFS layer does, but you have to use the whack-whack-question-mark syntax to get them.  But doing that just sets you up for tool problems.

I'm on my iPad here, so it's difficult to look at the source and respond here, but I wonder if this error message change was part of the long-paths stuff.

**Comment by jeffhostetler** [comment]
See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by shiftkey** [comment]
@jeffhostetler yeah, I feared we'd end up discussing `\\?\` and how that would break things downstream...

**Comment by dscho** [comment]
> I feared we'd end up discussing \\?\ and how that would break things downstream...

Actually. I got reports that the `\\?\` syntax makes things substantially faster by sidestepping certain validating layers (such as "trailing space?"). I just did not find time yet to brush up my `scale` branch and test the performance implications.

**Comment by dscho** [comment]
Okay, so I did investigate this in https://github.com/git-for-windows/git/compare/master...dscho:bbqb and after a lot of work had to conclude that `\\?\` makes things faster when working on absolute paths, but not when working on relative paths.

That is, when the path you want to access is relative, turning it into a `\\?\`-prefixed absolute path slows things down, while accessing an already absolute path is slower than the equivalent `\\?\`-prefixed path (you still have to take care of normalization, e.g. `\` instead of `/`, strip out `.` components, resolving `..` components by stripping the latest component, etc).

But Git accesses its worktree files as relative paths, i.e. the `\\?\` prefixing would make things slower, not faster.

Besides, as pointed out by @ethomson in a very passionate argument in a private discussion, it would not be an improvement to allow paths to be checked out that are illegal in Win32. It would break things left and right.

So it turns out that this is not something we want to have.
