### ISSUE TITLE
git format-patch --stdout bugged in powershell

### ISSUE THREAD

**Issue by xtreamwayz** [git-for-windows/git#930]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

.gitignore:
[user]
    name = ...
    email = ...
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
// Running this while in develop branch
git format-patch master --stdout > my.patch
```
- What did you expect to occur after running these commands?

I've been running the command in Git Bash, CMD and PowerShell. I expect the same patch to be generated for all terminals/shells.
- What actually happened instead?

PowerShell generated an unusable binary file that is about twice the size of the other shells/terminals. Git Bash and CMD created proper usable text files.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

First I thought something was wrong with that specific private repository but it happens with all repositories. Pick one that has multiple branches (I've tested master and develop), all had extra changes in the develop branch and while I was in that develop branch I tried to create a patch against the master branch. One of the opensource repo's I tested with is: https://github.com/xtreamwayz/html-form-validator
- Example patches:
  [patch-examples.zip](https://github.com/git-for-windows/git/files/559389/patch-examples.zip)

**Comment by PhilipOakley** [comment]
Encoding.....

UTF-8 for the small ones.
UCS-2 LE BOM for the large one

I opened them in Notepad++ and then checked the encoding indication...
  ----- Original Message ----- 
  From: Geert Eltink 
  To: git-for-windows/git 
  Sent: Friday, October 28, 2016 9:52 PM
  Subject: [git-for-windows/git] git format-patch --stdout bugged in powershell (#930)


    a..  I was not able to find an open or closed issue matching what I'm seeing 
  Setup
    a.. Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
a.. Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? 
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
a.. What options did you set as part of the installation? Or did you choose the defaults? 
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
a.. Any other interesting things about your environment that might be related to the issue you're seeing? 
  .gitignore:
  [user]
  name = ...
  email = ...

  Details
    a.. Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other 
  PowerShell

    a.. What commands did you run to trigger this issue? If you can provide a Minimal, Complete, and Verifiable example this will help us understand the issue. 
// Running this while in develop branch
git format-patch master --stdout > my.patch
a.. What did you expect to occur after running these commands? 
  I've been running the command in Git Bash, CMD and PowerShell. I expect the same patch to be generated for all terminals/shells.

    a.. What actually happened instead? 
  PowerShell generated an unusable binary file that is about twice the size of the other shells/terminals. Git Bash and CMD created proper usable text files.

    a.. If the problem was occurring with a specific repository, can you provide the URL to that repository to help us with testing? 
  First I thought something was wrong with that specific private repository but it happens with all repositories. Pick one that has multiple branches (I've tested master and develop), all had extra changes in the develop branch and while I was in that develop branch I tried to create a patch against the master branch. One of the opensource repo's I tested with is: https://github.com/xtreamwayz/html-form-validator

    a.. Example patches: patch-examples.zip

**Comment by dscho** [comment]
It appears that Powershell's redirection is the culprit: it insists on re-encoding the output into UTF-16 (or at least something very similar).

Have you considered using the `-o <directory>` option instead? If, for some reason, you need a single mbox file in UTF-8 format instead, and this need is recurring, you could use an alias similar to this (warning! untested!):

```ini
[alias]
    format-patch-to-mbox = '!sh -c "git format-patch \"$@\" | iconv -f utf-16 -t utf-8 >mbox"'
```

**Comment by xtreamwayz** [comment]
`-o <directory>` is working as expected. However in this case it had to be a single file.

I can't get the alias to work. But that's probably caused by the way I've setup git for windows. My solution at the time was running the command in a cmd terminal.

Since it's an issue with PowerShell only, I'm not sure if this is a bug in git for windows.  Feel free to close this report.

**Comment by dscho** [comment]
> I can't get the alias to work.

Maybe because the alias uses `sh` and therefore does not even have to pipe to `iconv` (because only Powershell re-encodes redirected streams to UTF-16).

In any case, when you say you cannot get something to work, it may be a good idea to paste some output so that others can have a crack at helping you?

**Comment by xtreamwayz** [comment]
I appreciate the help but it's not needed any more. As I said, the command is working in Bash/CMD, only not in PowerShell. That's why I reported it here. But since it's caused by PowerShell and it's not considered a bug I'll just close this issue so people don't spend more time on something I already had a workaround for.
