### ISSUE TITLE
close the repo,  fork from git/git, but from msysgit/git

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#932]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
_TODO_
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
_TODO_
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
_TODO_
```
- Any other interesting things about your environment that might be related
  to the issue you're seeing?
  
  _TODO_
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
  
  _TODO_
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
TODO
```
- What did you expect to occur after running these commands?
  
  _TODO_
- What actually happened instead?
  
  _TODO_
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?
  
  _TODO_

**Comment by PhilipOakley** [comment]
@lygstate Please  can you expand on what you mean? "close the repo, fork from git/git, but from msysgit/git".

Do you mean that you think that Git-for-Windows should show as being a fork of git/git (as displayed at the top left of this Github page)?

The actual history is that Git-for-Windiows is an evolution from msysgit/git, which was forked from git/git..

They (Git,, GfW,  & MsysGit) do have a common base and the current GfW does merge in (in it's own special way) the changes from upstream Git.

If that (my explanation and guess at the reason) is not correct, could you expand on what you had hoped to happen.

**Comment by lygstate** [comment]
Yeap,
```
Do you mean that you think that Git-for-Windows should show as being a fork of git/git (as displayed at the top left of this Github page)?

```
This is I am thinking of.

**Comment by dscho** [comment]
@lygstate please note that the bug report you left (i.e. no information filled into the template) was not informative. Next time try harder?

That said, we have no way to change what is reported as the forked repository.

**Comment by shiftkey** [comment]
@dscho

> That said, we have no way to change what is reported as the forked repository.

If you reach out to GitHub support I think they can address this - I gather you want to just update it to be forked from `git/git`...

**Comment by nalla** [comment]
Seems the GitHub support already addressed this. Thanks!
