### ISSUE TITLE
Unicode characters are not showing up correctly in Vim 7.4

### ISSUE THREAD

**Issue by beautifulcoder** [git-for-windows/git#933]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

Used the .zip portable install.
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

None.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
vim any_files.md
```
- What did you expect to occur after running these commands?

Unicode characters should appear correctly.
- What actually happened instead?

I am getting 'â' instead of proper characters.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

This feature worked fine in previous releases.

**Comment by dscho** [comment]
> What commands did you run to trigger this issue? If you can provide a Minimal, Complete, and Verifiable example this will help us understand the issue.
> 
> vim any_files.md

This is not a reproducible example. Please provide one.

**Comment by beautifulcoder** [comment]
I have vim on my PATH

    >where vim
    C:\Apps\Git\usr\bin\vim.exe

It just points to the vim provided by this installation of git. Since it's a portable xcopy install, the path is arbitrary.

**Comment by nalla** [comment]
> the path is arbitrary.

quite the contrary! The path is being prefixed with `/mingw64/bin` and `/bin` when a `Git-Bash` opens.

**Comment by dscho** [comment]
@beautifulcoder this is not really a bug in Git for Windows, but in your usage. Please note that we do *not* expose `vim.exe` to CMD, on purpose. *The* suggested way to use Portable Git is via calling `...\cmd\git.exe`.

As such, `vim.exe` will only be in your `PATH` if you go through the *Git Bash* (where the exact bug you mention does not occur).

The problem you are seeing is caused by VIM expecting the `LC_ALL` variable to define the encoding. No doubt your environment does not have that variable. Try this:

```cmd
set LC_ALL=en_US.UTF-8
vim anyfile.md
```

**Comment by snively** [comment]
I had the same problem, and was able to resolve it as follows:

1. In your Git Bash window, access "Options..." from the context menu in the title bar
2. In the Options dialog, elect "Text" from the list on the left
3. Make sure that the selected font supports Unicode ("Lucida Console" works well, for example)
4. Under "Character set", make sure that "UTF-8" is selected.

**Comment by dscho** [comment]
@snively you did not try my suggestion to unset `LC_ALL`?
