### ISSUE TITLE
Install generates errors

### ISSUE THREAD

**Issue by quantbo** [git-for-windows/git#936]
The following errors were generated when the terminal window came up following install:

WARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.

This looks like an incorrect setup.
A ~/.bash_profile that loads ~/.bashrc will be created for you.
bash: $'\377\376alias': command not found

Main@LAPTOP_32G_01 MINGW64 ~
$

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git-2.10.1-64-bit.exe
```
$ git --version --build-options
_TODO_
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win 7 64 bit

```
$ cmd.exe /c ver
_TODO_
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults.
Except that I installed in C:\Git.

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled


 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
Not that I know of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 _TODO_

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
TODO
```
 - What did you expect to occur after running these commands?

 _TODO_

 - What actually happened instead?

 _TODO_

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 _TODO_

**Comment by quantbo** [comment]
When I close Git Bash and reopen it I get the following:

bash: $'\377\376alias': command not found

Main@LAPTOP_32G_01 MINGW64 ~

**Comment by dscho** [comment]
That looks like you have a UTF-8 marker at the beginning of your `~/.bashrc`. Maybe try to remove it?

**Comment by quantbo** [comment]
I uninstalled and reinstalled using GitHubDesktop and that works without errors.

**Comment by dscho** [comment]
Okay, seems to be worked around differently than suggested. In any case, seems not to be a problem anymore.
