### ISSUE TITLE
SIGINT during log crashes git for windows

### ISSUE THREAD

**Issue by rcorre** [git-for-windows/git#937]
- [-] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14931]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log --oneline origin/master --author=ryrode --no-merges --grep=ngen
```

Before seeing any results, I hit \<ctrl-c\>. This crashed git.

**Comment by kostix** [comment]
Could you elaborate on that "crashed" term a bit?

I'd expect Ctrl-C delivered to Git to certainly kill it.  So, did killing that Git instance look strange -- say, a dialog about a program having performed an invalid operation popped or something like this?

**Comment by rcorre** [comment]
I expected to kill it, not crash it :)
I'm talking about getting a dialog like this:
```
[Window Title]
Git for Windows

[Main Instruction]
Git for Windows has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Debug] [Close program]
```

**Comment by dscho** [comment]
Hmm. I just tried with a lengthy `log` process, in `cmd.exe`, and it just stops, with a `^C` printed to the terminal...

But then, I am using Git for Windows v2.10.1 and Windows 10.0.14393 (i.e. slightly behind your Windows version). Maybe that is the culprit? Are you on an Insider build, maybe?

**Comment by rcorre** [comment]
> Are you on an Insider build, maybe?

Yes, that could be it.

**Comment by whoisj** [comment]
I can reproduce this: 
![image](https://cloud.githubusercontent.com/assets/11578325/22163450/d88e471e-df20-11e6-8a58-a756428bf628.png)

git version 2.11.0.windows.3

Windows Version 10.0.14393 Build 14393 (x64)

Reproducible with `git fetch`, `git checkout`, `git log`, etc. 

Reproducible with Command Prompt and PowerShell

With Git-bash I get 'Segmentation fault' in the shell output.

**Comment by dscho** [comment]
I meant to come back to this earlier: the Ctrl+C handling was redone recently, and I wonder whether this bug was fixed implicitly... @rcorre @whoisj could I ask you to re-test?

**Comment by rcorre** [comment]
I'm not on Windows any more, so I'm of no help. Sorry!

**Comment by dscho** [comment]
Thanks for the update! I'll close the ticket, then, and will reopen when/if we encounter the issue again.
