### ISSUE TITLE
x64 build: internal error reading the windows environment - too many environment variables

### ISSUE THREAD

**Issue by brainsucker-na** [git-for-windows/git#942]
Issue:
```
D:\Dev\test>git --version
git version 2.10.2.windows.1

D:\Dev\test>git stash
      0 [main] sh 16144 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - internal error reading the windows environment - too many environment variables?
    619 [main] sh 16144 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump

D:\Dev\test>git pull
      0 [main] sh 17292 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - internal error reading the windows environment - too many environment variables?
    514 [main] sh 17292 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
      1 [main] bash 15432 C:\Program Files\Git\usr\bin\bash.exe: *** fatal error - internal error reading the windows environment - too many environment variables?
   4502 [main] bash 15432 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump
      1 [main] sh 24216 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - internal error reading the windows environment - too many environment variables?
   3977 [main] sh 24216 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
```

git version:
```
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

windows version:
```
win 10 x64 ver 1607 (OS Build 14393.321)
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393

```
Install options:
```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

x86 git build of the same version (2.10.2) works fine.
Had the same issue with 2.9.0 build somewhere in June (same up-to-date Win10), also fixed by installing x86 build, never reported.
I understand that is not a git issue (probably cygwin or msys2, etc.), however x64 build is suggested as default one by website, I'm not sure about issue spread.

Some related information:
https://cygwin.com/ml/cygwin/2015-07/msg00429.html
https://github.com/Alexpux/MSYS2-packages/issues/25

**Comment by brainsucker-na** [comment]
[bash.exe.stackdump.txt](https://github.com/git-for-windows/git/files/568923/bash.exe.stackdump.txt)
[sh.exe.stackdump.txt](https://github.com/git-for-windows/git/files/568922/sh.exe.stackdump.txt)

**Comment by dscho** [comment]
> too many environment variables?

So how many environment variables *do* you have?

**Comment by brainsucker-na** [comment]
set > env
5275 bytes, 60 vars.
5417 bytes, 64 var elevated.

I don't think this is close enough to any reasonable limit, also amount of variables doesn't explain why x86 version is working fine (IMHO).
Again this looks very similar to issue described in cygwin thread I linked above, which mentions the same error message, "x64/x86", "Enabling High Address" (16GB ram, if that matters), etc. etc. and finally some "bugs fixed". However that was in July 2015, so I would expect recent git builds to include these patches long time ago.

https://cygwin.com/ml/cygwin/2015-07/msg00434.html

Sorry I'm not yet in position to check if these patches were ever applied, and are they used in current msys2 / git distributive build (or generally spend a lot of time to investigate this). Just decided to report that, since I fallen down into the same pit (downloading automatically suggested x64 version) at least two times in a row now :)
Let me know if any further information is required.

**Comment by dscho** [comment]
Hrm. That is indeed not a huge environment at all.

> "Enabling High Address"

So are you saying that your Windows setup has this flag set to true?

> However that was in July 2015, so I would expect recent git builds to include these patches long time ago.

Indeed. Git for Windows 2.x was released for the first time in August 2015, with a freshly updated MSYS2 runtime that was freshly updated to the most recent Cygwin runtime version, so I would not expect *this* particular problem to have cropped back up.

Could you try current [MSYS2](https://msys2.github.io/) and current [Cygwin](https://cygwin.com) on the same setup, to see whether they share the flaw?

**Comment by dscho** [comment]
There was really enough time to try on Cygwin and drive this ticket to a satisfactory resolution.
