### ISSUE TITLE
Make Git CMD and Git Bash icons distinct

### ISSUE THREAD

**Issue by kwill** [git-for-windows/git#943]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git CMD and Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

1. Launch Git CMD
2. Launch Git Bash

 - What did you expect to occur after running these commands?

1. Both appear on Windows task bar
2. Icons are visually distinct

 - What actually happened instead?

1. Both appear on Windows task bar (correct)
2. Icons are identical

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Attempted workaround:**

I tried assigning my own icon to Git Bash. This works for pinning it to the task bar. But when I launch it, it creates a new task bar icon that is again identical to the Git CMD icon.

**Other notes:**

The Git GUI icon is distinct when Git GUI is running, but it appears identical in the Start Menu.

**Comment by dscho** [comment]
Please install the Git for Windows SDK, and [build an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer) for yourself. Then you can change `/usr/src/build-extra/install.iss` (look for `.ico`) according to your wishes, build another installer, and verify that it works fine. Lastly, commit, push, open a Pull Request and earn eternal fame.

**Comment by kwill** [comment]
Are there existing style or "brand" guidelines that I (or someone else keen on eternal fame) should follow?

**Comment by dscho** [comment]
No guidelines :-)

**Comment by dscho** [comment]
@kwill still interested? Or can we close this ticket?

**Comment by kwill** [comment]
After all that I'm afraid I don't have capacity. Hopefully someone else or my future self rediscovers your helpful pointers.
