### ISSUE TITLE
Installing Git for Windows overwrites existing system configuration

### ISSUE THREAD

**Issue by Nightfirecat** [git-for-windows/git#947]
* [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64

$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MinTTY Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

`git config --system --edit` to make changes to the system configuration, followed by a new Git for Windows installation. (same or other versions as installed)

 - What did you expect to occur after running these commands?

Any configurations set in this file would be maintained, with additional configurations appended or overwritten in their specific sections, allowing users to maintain a system-level configuration between Git for Windows installations/upgrades.

 - What actually happened instead?

The file was fully replaced (or removed, if no configs chosen during install) with a file containing only the installation configurations chosen.

**Comment by dscho** [comment]
Unfortunately, this is by design. If you need to provide system configuration you need not to be overwritten, you need to edit `C:\ProgramData\Git\config`.
