### ISSUE TITLE
Git Bash crashes when trying to view options dialog.

### ISSUE THREAD

**Issue by MAdrianMattocks** [git-for-windows/git#949]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
No commands.
I can rep it by:
1. Launch Git Bash
2. Right click the icon in the top left of the window.
3. Click "Options..."
```
 - What did you expect to occur after running these commands?
To see the options for the bash terminal.

 - What actually happened instead?
Git bash crashes.  No errors, no nothing.  The windows simply disappears and the process does not show in task manager.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by landstander668** [comment]
For what it's worth, this works as expected for me under Windows 7 Professional SP1 using the same version of Git for Windows.

**Comment by MAdrianMattocks** [comment]
I have tried reinstalling Git and the app still crashes.  Git commands run fine.

**Comment by Nightfirecat** [comment]
FWIW, I also can't reproduce on Windows 7; haven't tested on Windows 10.

**Comment by dscho** [comment]
@MAdrianMattocks any chance you can have a look at it via [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer) and maybe produce a dump of the crashed process?

**Comment by MAdrianMattocks** [comment]
@dscho Sure.

A full dump is too big so I've attached the mini.

What I did was:

- Launch Git Bash.
- Use PE to suspend the process and produce a mini dump (labeled 'before' in the file name)
- Follow the rep procedure above (Git Bash crashed), I then produced another mini dump (labeled 'after' in file name).

The reason for suspending is that was the only way that I can get the dump after trying to get to the options dialog.

[bashDumpMini.zip](https://github.com/git-for-windows/git/files/595446/bashDumpMini.zip)

**Comment by dscho** [comment]
@MAdrianMattocks unfortunately, this dump does not shed any light into the matter. There are three threads, two stuck waiting for objects, the third trying to read a file (apparently from within `sigfillset()` which in turn is supposedly called from `setprogname()` even if I cannot see that call).

Shot in the dark: could you test whether the same issue occurs with [MSYS2](https://msys2.github.io/)'s Bash?

**Comment by MAdrianMattocks** [comment]
The issue does not occur with MSYS2.  I don't like the way MSYS2 handles bash profiles (unnecessarily complicated imo).

I'll try some voodoo.  I'm going to completely remove MSYS2 and Git and do a fresh install of Git and see what happens.  The reinstall a week ago did not involve an uninstall.  I just ran the installer again.

**Comment by MAdrianMattocks** [comment]
So I did the uninstall (I also deleted the Git directory in program files) and the reinstall.

The crash still happens but here's a wrinkle:

1. Launch Git bash.
1. After the window comes up click the icon in the top left and select "New"
1. A new window comes up.  Click the icon in the top left and select "Options..."

The options window will come up but it is fragile.  Sometimes the window (just that window, the first windows remains) will crash immediately (i.e. the dialog will appear briefly and then it and the associated window will disappear) but about 95% of time I will have enough time to make at least one change in the options dialog and hit apply and those changes will be honored (even after I exit and restart the app).

Don't know if I would call this a work around but by using this method I was able to make the changes to the window that I want.

**Comment by dscho** [comment]
> The issue does not occur with MSYS2.

Then it must be a bug in Git for Windows' files.

As the bug occurs safely in MinTTY/msys-2.0.dll land, I suspect that a recent change in the MSYS2 runtime *may* have fixed this. If that is the case, the prerelease at https://github.com/git-for-windows/git/releases/tag/v2.11.0-rc1.windows.1 would have the fix. Could you test this version (the portable Git should be enough, no need to overwrite your Git for Windows installation with an experimental one)?

**Comment by MAdrianMattocks** [comment]
@dscho I tried the portable version and it crashes when I try to access the Options dialog.  Mintty dropped a stackdump which is attached.
[mintty.exe.zip](https://github.com/git-for-windows/git/files/604108/mintty.exe.zip)

**Comment by chadjoan** [comment]
I also have this issue.

For me, it happens intermittently, so I made a video of the behavior: https://www.youtube.com/watch?v=42Yh1iYMfJc

I also reported it to the mintty project: https://github.com/mintty/mintty/issues/610

Found on Windows 7 Pro 64-bit. Mintty 2.6.2, Git Bash v2.10.2 64-bit install.

Please see the mintty bug report if you need more details about my specific report.

Good luck and thank you for writing this software.

**Comment by MAdrianMattocks** [comment]
When I refer to it being "fragile" in my post above @chadjoan is showing what happens to me, when it works.  Though I never get the options dialog on the first window opened.  I always have to open a second window then it's as I said in the post 4 days ago.

**Comment by chadjoan** [comment]
Update:

Using the 2.11.0.rc1.windows.1 prerelease did not solve the problem on my system.  I still get crashing.

```
$ git --version --build-options
git version 2.11.0.rc1.windows.1
sizeof-long: 4
machine: x86_64
```

**Comment by dscho** [comment]
@chadjoan thank you for opening the MinTTY ticket. I hope that they can fix that component, and maybe provide useful hints how to debug this further. Speaking of which... have you tried running [ProcMon](https://technet.microsoft.com/en-us/sysinternals/bb896645) while triggering the crash? You could filter the output by the path to `mintty.exe`. Maybe the log has some interesting clues?

**Comment by mintty** [comment]
For a stackdump to be any useful, you'd have to `make DEBUG=1` an MSYS/Git debug version first, and then translate the stackdump information using addr2line with the debug exe at hand.
I tried to reproduce the issue on Windows 7 and Windows 10 systems but without any such effect; I'll check any other clues provided but that will be guesswork.

**Comment by mintty** [comment]
See https://github.com/mintty/mintty/issues/610#issuecomment-263294951 please for a debug attempt.

**Comment by fourpastmidnight** [comment]
I can confirm that this behavior does indeed occur with the MinTTY version distributed with GitForWindows-2.10.2.

Repro steps:

1. Open Git Bash
2. Open the MinTTY Options dialog
3. Your open MinTTY terminal crashes.
4. Open a new Git Bash terminal
5. Now open a second Git Bash terminal
6. Open the MinTTY Options dialog from the newly opened terminal from step 5 above.
7. The Options dialog displays.
8. Change the terminal font. This works.
9. Open the Options dialog.
10. Change the number of columns/rows. The terminal session dies.

Sorry, I have no stack dumps; I just happened to run across this today when installing this version at work on a machine--Windows Server 2012 R2.

**Comment by mintty** [comment]
As said before, this isn't reproducible here. Any specific environment that you may reduce to narrow down the issue?
The current mintty repository version https://github.com/mintty/mintty/archive/master.zip includes some diagnostic output. Someone who experiences the issue will have to compile it (it may be necessary to install the Git SDK to that aim, https://github.com/git-for-windows/build-extra/releases (doesn't work behind a firewall) and also `pacman -S gcc` and use /usr/bin/gcc to compile mintty). Build with `make DEBUG=1`.

**Comment by dscho** [comment]
> Windows Server 2012 R2.

Oh, so it might be an issue with certain Windows versions... I am pretty set up with Windows 10 these days, so I cannot easily test.

**Comment by mintty** [comment]
Please try again with mintty 2.7.1.

**Comment by chadjoan** [comment]
Git for Windows devs: can you give me any instructions on how you build mintty in a way that is representative of how its done in Git for Windows?

I have been unable to repro this bug when building mintty on my own with a fresh MSYS2 environment, but it still happens with the mintty provided by Git for Windows.

At some point maybe I could download the [Git for Windows SDK](https://github.com/git-for-windows/git/wiki/Technical-overview) and somehow figure out how to replace its mintty with various versions from the mintty.  But that looks like a lot of work (relative to the amount of disposable time I have on the work computer that exhibits this bug), so I can't promise anything.  If I could get clear instructions on how to use this SDK (if that's even the right approach) to test mintty versions, it could help me do some testing.

**Comment by dscho** [comment]
> Git for Windows devs: can you give me any instructions on how you build mintty in a way that is representative of how its done in Git for Windows?

We no longer build a custom mintty but use the build provided by MSYS2.

For debugging, you can rebuild the package yourself as described here: https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages (note that you *have* to call the `makepkg -s` command line from an MSYS2 shell, i.e. by running `C:\git-sdk-64\msys2_shell.cmd -msys`).

> I have been unable to repro this bug when building mintty on my own with a fresh MSYS2 environment, but it still happens with the mintty provided by Git for Windows.

You could simply download the latest `mintty` package from MSYS2: http://repo.msys2.org/msys/x86_64/mintty-1~2.6.2-1-x86_64.pkg.tar.xz (although that is not at the suggested v2.7.1).

**Comment by mintty** [comment]
Mintty 2.7.2 includes a fix for this. (Root cause reported to cygwin mailing list.)

**Comment by mintty** [comment]
The root cause has been fixed with cygwin 2.6.1, released today.

**Comment by dscho** [comment]
> The root cause has been fixed with cygwin 2.6.1, released today

I wonder whether you could provide more thorough information, e.g. a link to the commit that fixed it, and maybe another link to the discussion that resulted in the fix.

**Comment by mintty** [comment]
It's the last bug fix mentioned in the release announcement https://cygwin.com/ml/cygwin-announce/2016-12/msg00038.html, pointing to the discussion https://cygwin.com/ml/cygwin-developers/2016-12/msg00008.html.
Commit seems to be https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=563dda82591bddb213f1771a63de534e11602cd8

**Comment by dscho** [comment]
Thanks.

**Comment by dscho** [comment]
@MAdrianMattocks the release v2.11.0(3) comes with an updates MSYS2 runtime that supposedly addresses this issue. Could you give it a whirl?

**Comment by nadams9** [comment]
I can confirm this bug on Windows 7 with Git v2.11.0.

I can also confirm that Git v2.11.0(3) fixes the bug for me.

Thanks!

**Comment by MAdrianMattocks** [comment]
@dscho Works.  No crashes.  I can change an option.  I think we're good.

**Comment by dscho** [comment]
> Works. No crashes. I can change an option. I think we're good.

Good. I'll close the ticket (in the future, please don't hesitate to close tickets that you opened yourself once you are satisfied that your problem has been addressed).
