### ISSUE TITLE
Ctrl+C kills background git processes on git bash

### ISSUE THREAD

**Issue by vincepare** [git-for-windows/git#950]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [version 6.1.7601]
```
(Windows 7 64-bit)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I have no install-options.txt file.
I'm using a portable release : PortableGit-prerelease-2.11.0.rc0.windows.1-32-bit.7z.exe

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
# Building a test repository
mkdir gitrepo
cd gitrepo
git init
for i in $(seq 1 7); do echo "$(date) : edit : $i" >> dummy.txt; git add .; git commit -m "Commit $i"; done;

# Starting up a git bisect session (to be able to use bisect visualize then)
git bisect start
git bisect bad HEAD
git bisect good HEAD~5

# Launch gitk from git, in background
git bisect visualize &
# Now, press Ctrl+C
```
 - What did you expect to occur after running these commands?

I expect to keep gitk running, because it is a background process.

 - What actually happened instead?

gitk gets killed by Ctrl+C

### Additionnal notes
This is not specific to `git bisect visualize`, this issue seems to apply on all programs launched from git, such as `git difftool` (I chose to show `git bisect visualize` in my example simply because it does not need a custom git configuration, unlike git difftool).

Furthermore, I also tested on linux, without meeting the issue (gitk keeps running).

After a few search on the internet, I suspect the PGID (bash process groups) to be responsible for the issue :
- http://stackoverflow.com/questions/18245002/ctrl-c-killing-my-background-processes-in-my-shell
- http://unix.stackexchange.com/questions/163561/control-which-process-gets-cancelled-by-ctrlc

Here are different processes running (after a `git bisect visualize &`) :
```
$ ps xao pid,ppid,pgid,sid,command
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     5952   11444    5952       9668  cons0    1062335 17:04:22 /usr/bin/ps
    12040    7016   11444      12724  cons0    1062335 17:03:54 /mingw32/bin/wish
    11444       1   11444      11444  cons0    1062335 17:01:59 /usr/bin/bash
I    9096       1    9096       9096  cons0    1062335 10:59:48 /usr/bin/bash
    11336   11444   11336      10272  cons0    1062335 17:03:52 /bin/git
     7016       1   11444       7016  cons0    1062335 17:03:53 /usr/bin/sh
```
You can see that /mingw32/bin/wish (the process holding gitk) has the same PGID than bash (11444).

The same test on linux shows that the PGID is different :
```
  PID  PPID  PGID   SID COMMAND
...
 1009     1  1009  1009 /usr/sbin/lightdm
 1049  1009  1049  1049  \_ /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
 1496  1009  1009  1009  \_ lightdm --session-child 12 19
 1819  1496  1819  1819      \_ /sbin/upstart --user
...
 8827  1819  1996  1996          \_ /usr/lib/gnome-terminal/gnome-terminal-server
 8834  8827  8834  8834          |   \_ bash
22163  8827 22163 22163          |   \_ bash
22335 22163 22335 22163          |       \_ git bisect visualize
22336 22335 22335 22163          |       |   \_ /bin/sh /usr/lib/git-core/git-bisect visualize
22350 22336 22335 22163          |       |       \_ wish /usr/bin/gitk -- --bisect --
22376 22163 22376 22163          |       \_ ps xafo pid,ppid,pgid,sid,command
```

**Comment by dscho** [comment]
I fear that there is not a whole lot we can do about this. You see, there is no such thing as a "background process" on Windows. They are all alike. So when we kill a process using Ctrl+C, we have to traverse all of its children, too, in order to kill *non*-background processes correctly. But of course, as we have no way to discern between background and non-background processes, we just kill 'em all...

**Comment by dscho** [comment]
A fix for this should be an incidental fallout of my upcoming fix for https://github.com/git-for-windows/git/issues/1491.

**Comment by dscho** [comment]
The newest snapshot at https://wingit.blob.core.windows.net/files/index.html should fix this. Please test.

**Comment by vincepare** [comment]
The issue is fixed on the [latest release](https://github.com/git-for-windows/git/releases/tag/v2.20.1.windows.1) (PortableGit-2.20.1-32-bit.7z.exe).

But this doesn't seems to be a fallout of #1491, after testing many releases from https://wingit.blob.core.windows.net/files/index.html, I can tell the first release which fixes the issue is this one :
* [Wed, 17 Jan 2018 19:43:01 +0100 (commit 4584fb7323)](https://wingit.blob.core.windows.net/files/PortableGit-prerelease-2.15.1.windows.2.409.g4584fb7323-32-bit.7z.exe)

The previous release still had the bug :
* [Fri, 12 Jan 2018 14:48:19 +0100 (commit d0192a7c4e)](https://wingit.blob.core.windows.net/files/PortableGit-prerelease-2.15.1.windows.2.407.gd0192a7c4e-32-bit.7z.exe)

And this is pretty weird because there is so little difference between these two versions, according to git :
https://github.com/git-for-windows/git/compare/d0192a7c4e...4584fb7323.

**Comment by dscho** [comment]
> And this is pretty weird because there is so little difference between these two versions, according to git :
> [d0192a7...4584fb7](https://github.com/git-for-windows/git/compare/d0192a7c4e...4584fb7323).

Please note that Git for Windows consists of more than just the build output for the Git source code. It contains parts of well over 100 packages, among them the MSYS2 runtime that is *actually* responsible for handling Ctrl+C in Git Bash. If you compare the files `/etc/package-versions.txt` from those two snapshots, you will learn what else changed (in addition to the Git source code).
