### ISSUE TITLE
git-bash.exe -c  problem with non-ASCII string 

### ISSUE THREAD

**Issue by arioso27** [git-for-windows/git#953]
- [V ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
K:\Git\git-bash.exe -c "echo 歡迎 &&read"
```

 - What did you expect to occur after running these commands?

Console show "歡迎" and wait read something

 - What actually happened instead?

Console quick close

If try ASCII string is fine, ex:
```
K:\Git\git-bash.exe -c "echo Welcome &&read"
```

And in version 2.5.3 also fine with that trigger issue command

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by PhilipOakley** [comment]
This looks very similar to https://github.com/git-for-windows/git/issues/945. I think (google translate..) you are both using the Chinese characters, so you may be able to help each other.

I suspect that this is a Windows code page character conversion issue. Often there are hidden conversion steps within the various applications and terminal displays which fight each other.

**Comment by arioso27** [comment]
Ref #945, I try **set LC_ALL=en_US.UTF-8** in CMD, and it work ^^ 
Thank you @PhilipOakley
