### ISSUE TITLE
git config overwrites symbolic links

### ISSUE THREAD

**Issue by rpaquay** [git-for-windows/git#958]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.9.2.windows.1
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.10586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

n/a

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Cmd ("As Administrator")

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
(Run cmd.exe "As Administrator" to allow symbolic link creation)
> git init
> copy .git\config git.config
> del .git\config
> mklink .git\config ..\git.config
> dir .git\config
> git config core.filemode false --replace-all
> dir .git\config
```

 - What did you expect to occur after running these commands?

The last `dir .git\config` command shows that the file is a SYMLINK:
```
11/15/2016  11:22 AM    <SYMLINK>      config [..\git.config]
```

 - What actually happened instead?

The last `dir .git\config` command shows that the SYMLINK has been replaced by a file:
```
11/15/2016  11:22 AM               148 config
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

The problem is not specific to a particular repository. Even though the example seems trivial, the issue is actually affecting "real-world" examples, specifically people using the https://code.google.com/p/git-repo/ tool to handle multiple repository. The git-repo tool create many symblic links in ".git" directories, and it does not expect these symbolic links to be replaced by regular files.

Note that git for cygwin preserves symlinks with a similar set of commands.

**Comment by dscho** [comment]
> git version 2.9.2.windows.1

This is really old by now. There have been 2.9.3, 2.9.3(2), 2.10.0, 2.10.1 and 2.10.2 in the meantime.

Nevertheless, I tested it and figured out what goes wrong: our `readlink()` implementation only tries to read symbolic links when `core.symlinks = true`. That config setting pays tribute to [various issues with symbolic links on Windows](https://github.com/git-for-windows/git/wiki/Symbolic-Links).

But we should read symbolic links whenever we encounter one, regardless of our ability to create symbolic links.

**Comment by rpaquay** [comment]
Thank you so much for the quick fix!
