### ISSUE TITLE
Node with winpty is not working

### ISSUE THREAD

**Issue by mriehema** [git-for-windows/git#961]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
$ which winpty
/usr/bin/winpty

$ sha256sum.exe /usr/bin/winpty.exe
aa2bf55f7f444ad5a0e64033a3ec54cba722756634bf8b51b320e55b0d73291b */usr/bin/winpty.exe

$ winpty
Usage: winpty [options] [--] program [args]

Options:
  -h, --help  Show this help message
  --mouse     Enable terminal mouse input
  --showkey   Dump STDIN escape sequences
  --version   Show the winpty version number

$ winpty --version
winpty version 0.4.0-dev
commit none

$ which node
/c/Program Files/nodejs/node

C:\Users\mriehema>node --version
v6.9.1
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash (git-bash.exe)

 - What commands did you run to trigger this issue?

```
$ winpty node --version
```

 - What did you expect to occur after running these commands?

Showing the version like with CMD and returning to Git-Bash.

 - What actually happened instead?

Nothing. When I run $ winpty node --version my Git-Bash is broken. No response and it just jumpes back to $ (after 2-3 seconds). But now I can't enter anything. All I can do is closing it. It is the same behavior to call node without winpty.

![winpty](https://cloud.githubusercontent.com/assets/2276886/20359297/87e467cc-ac2f-11e6-8cef-d6cee7d14dcb.gif)

*More infos:*
Running `$ node --version` in bash.exe (Git/bin/bash.exe) works, running `$ winpty node --version` leads to the same error.

![winpty-in-bash](https://cloud.githubusercontent.com/assets/2276886/20359302/8d2ec164-ac2f-11e6-8d90-f4f8492b7adc.gif)

**Comment by dscho** [comment]
I tried to reproduce, downloading node.js v6.9.1 from https://nodejs.org/ and running `winpty node --version`, but it worked as I expected it to. The only difference I see is that I use Windows 10.

Maybe there is a helpful exit code? What does `echo $?` say after your `winpty node --version` returns without printing anything?

**Comment by mriehema** [comment]
Today I removed Git and node.js. Cleaned up all folder/settings in %program files% and %appdata%. But I still get the same result. :(

The bash is not totally broken as I thought, because I can still enter something, but I can't see, what I'm typing.

```
mriehema@HAM-ITS0642 MINGW64 /c/dev
$ winpty node --version

mriehema@HAM-ITS0642 MINGW64 /c/dev (after I typed echo $?)
$ 0
```

**Comment by dscho** [comment]
Maybe the most robust solution is to switch to using ConHost (i.e. Windows' default terminal) rather than MinTTY?

**Comment by mriehema** [comment]
Maybe this problem is related to https://github.com/tjunnone/npm-check-updates/issues/136

**Comment by dscho** [comment]
@mriehema why don't you give ConHost a shot?

**Comment by mriehema** [comment]
FYI: I switched to cmder (based on conemu). Not using git-bash/MinTTY anymore and I'm happy, because node/npm and all my other daily tools work as expected. No winpty or stuff is needed. 
It's ok for me, if you close this ticket.

**Comment by dscho** [comment]
You do not need to rely on me to close your tickets after your problems have been solved... :smile:
