### ISSUE TITLE
pre-release version tag is slightly wrong

### ISSUE THREAD

**Issue by larsxschneider** [git-for-windows/git#967]
I just installed the [latest pre-release v2.11.0-rc2](https://github.com/git-for-windows/git/releases/tag/v2.11.0-rc2.windows.1) and realized that the version tag is slightly off:

```
git --version
git version 2.10.2.windows.1.967.gd2325b6
```

The hash is correct but the version should probably be `v2.11.0-rc2.windows.1.967.gd2325b6`. I think it's not a big issue - I just wanted to document it here.

**Comment by dscho** [comment]
> the version should probably be v2.11.0-rc2.windows.1.967.gd2325b6

Actually, if you want to have v2.11.0-rc2.windows.1 in the picture, it should report v2.11.0-rc2.windows.1 as version, or at least something like v2.11.0-rc2.123456.gd2325b6.

However, those prereleases are really meant to make things easier on me by relieving me of release engineering work I would have to do for full-blown releases, not harder. As such, I'd like to keep things the way they are.

If you disagree, feel free to patch [`please.sh`'s `prerelease` command](https://github.com/git-for-windows/build-extra/blob/8c2ffd9ae38a20fe33ec9ac18fd6c4240dfa7983/please.sh#L933-L1228) (I typically rebase the current `master` onto the revision tagged by upstream, via `/usr/src/build-extra/shears.sh --merging --onto v2.11.0-rc2 merging-rebase`, then build and run the tests with `make -j15 DEVELOPER=1 -k test` and then provide fixup commits for all new test failures, then run `/usr/src/build-extra/please.sh prerelease --installer+portable HEAD`).

In fact, I would welcome any improvements you can contribute!

**Comment by dscho** [comment]
Okay, I'll just close this. For v2.11.0-rc3, I first pushed the tag and then built the prerelease, which fixes the problem. Hopefully I won't forget in the future!
