### ISSUE TITLE
Git help option broken in 2.11 rc2

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#968]
I'm running the 64-bit git v2.11 rc2 and I get the following:

```
$ git diff --help
/usr/bin/start: line 8: cmd: command not found
fatal: 'web--browse' appears to be a git command, but we were not
able to execute it. Maybe git-web--browse is broken?
```

This was working just fine in 2.10 prior to upgrading.

**Comment by dscho** [comment]
Works just fine here... Any more clues as to what is different in your system (the issue reporting template is intended to help with providing this information).

**Comment by dscho** [comment]
Closing until more complete information is available.
