### ISSUE TITLE
`git clean -i` is not working

### ISSUE THREAD

**Issue by nalla** [git-for-windows/git#97]
### Reproduce
```bash
$ cd /usr/src/git
$ touch test
$ git clean -n
Would remove test
$ git clean -i
# Ctrl+C will help you out

# Verify that it's a bug in our codebase
$ /usr/bin/git clean -i
Would remove the following item:
  test
*** Commands ***
    1: clean                2: filter by pattern    3: select by numbers    4: ask each
    5: quit                 6: help
```
@dscho or someone else, could you verify this?
### Analysis
First thoughts remember the problem with the `stdin` and `stdout` problems with the `git push` via `https` that resolved to a solution with a custom `terminal_prompt`. *Maybe* the same problem exists here.

And indeed it seems that [`clean.c#L579`](https://github.com/git-for-windows/git/blob/master/builtin/clean.c#L579) seems to access `stdin` directly. But that is maybe not the problem at all since nothing is printed in the first place. Maybe `_(opts->prompt)` in [`clean.c#L574`](https://github.com/git-for-windows/git/blob/master/builtin/clean.c#L574) contains something that would break things.

Digging further I found out that [`column.c#146`](https://github.com/git-for-windows/git/blob/master/column.c#L146) seems to be one of the bottlenecks. When applying a [patch](https://gist.github.com/nalla/04c1839456291a89883b) that would parse `MSYS_TTY_HANDLES` and then uses `WriteFile` to the retrieved `out_handle`, the output is:
```bash
$ ./git clean -i
  test
    1: clean                2: filter by pattern    3: select by numbers
    4: ask each             5: quit                 6: help
q
Would remove the following item:
*** Commands ***
What now> Bye.
```

This leads to the conclusion that when running *any* builtin command that is writing to `stdout` via `printf` and then is waiting for *some* input from `stdin` has that kind of problem.

To sum things up and verify my theory, if you go to the reproduce section and run it again but instead of using `Ctrl+C` to terminate the `git clean -i` call using just the letter `q` you will get the following result.
```bash
$ git clean -i
q
Would remove the following item:
  test
*** Commands ***
    1: clean                2: filter by pattern    3: select by numbers
    4: ask each             5: quit                 6: help
What now> Bye.
```

It seems that `stdout` is unbuffered. adding a `fflush(stdout)` [here](https://github.com/git-for-windows/git/blob/master/builtin/clean.c#L577) seems to resolve the issue.

### Solution
I first tried to overwrite `printf` and `vprint` to use the `MSYS_TTY_HANDLES` but that somehow did not do the trick. So I looked for another solution. After studying [this article](http://stackoverflow.com/questions/3723795/is-stdout-line-buffered-unbuffered-or-indeterminate-by-default) I tried setting `stdout` to `unbuffered` *as soon as possible*. I did this in the `mingw_startup` function. That seems to work.

Doing this *generally* seems not to be such a good idea. @dscho pointed out that for performance reasons `stdout` is unbuffered. I opted to precede reads from `stdin` by a `fflush(stdout)`.

**Comment by dscho** [comment]
> It seems that stdout is unbuffered. adding a fflush(stdout) here seems to resolve the issue.

Yes, `stdout` is buffered. This is vastly more performant than having it unbuffered, but it means that `fflush()` is required in strategic places (that might be missed on Linux because of a different I/O model that often hides issues like the one in question).

Please add the `fflush(stdout)` call instead, I think this is the better solution, because it keeps the performance as high as possible.

**Comment by nalla** [comment]
Sounds reasonable. I already updated #98 to call `fflush` instead.
