### ISSUE TITLE
Git clone fails with message error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small

### ISSUE THREAD

**Issue by yogsodoth** [git-for-windows/git#970]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
64-bit Win7
```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Behind a corporate firewall

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone https://bitbucket.org/<user>/<repo>
```
 - What did you expect to occur after running these commands?

Repo cloned into local dir

 - What actually happened instead?

Git failed with the following:

```
fatal: unable to access 'https://bitbucket.org/<user>/<repo>': error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

All repos tested on bitbucket and guthub fail, including public ones and the repo for Git for Windows

**Comment by shiftkey** [comment]
This seems like a server-side issue: http://stackoverflow.com/questions/35984308/node-js-openssl-error-dh-key-too-small

@yogsodoth do you have a _public_ GitHub repository that fails with the same error?

**Comment by dscho** [comment]
> @yogsodoth do you have a public GitHub repository that fails with the same error?

Ping?

**Comment by yogsodoth** [comment]
Not sure what you mean by public in this context... publicly available?

**Comment by dscho** [comment]
> Not sure what you mean by public in this context... publicly available?

Public meaning: if you provide a simple way to reproduce the problem *for others*, your chances of seeing your problem resolved increase *dramatically*.

As of now, I have no idea how to trigger the problem, so I cannot help. Which is frustrating for both of us.

**Comment by dscho** [comment]
In the meantime, maybe you can follow the advice set forth in http://stackoverflow.com/questions/32267593/ssl3-error-on-git-clone-under-windows-with-git-2-5 and http://stackoverflow.com/questions/30090676/cannot-communicate-securely-with-peer-no-common-encryption-algorithms/30442395#30442395 to experiment a little. And set the environment variable `GIT_TRACE_CURL=1` for more verbose debugging information.

**Comment by yogsodoth** [comment]
Will do, and will follow up on results and add details as I get them.

**Comment by shiftkey** [comment]
Closing this out until @yogsodoth has some additional information to help with reproducing the issue.
