### ISSUE TITLE
`git clean -fd` does not clean Junctions/Symlinks

### ISSUE THREAD

**Issue by larsxschneider** [git-for-windows/git#973]
https://github.com/git-for-windows/git/issues/607 might be related.

### Setup

```
git version 2.11.0.rc3.windows.1
sizeof-long: 4
machine: x86_64
```
(I got the same behaivor for git 2.8 / 2.9 / 2.10 on Windows)

```
Microsoft Windows [Version 6.3.9600]
```

### Details

Consider this test script in CMD:

```
git --version
git init .
git config --local core.symlinks true   # I tried true/false here 
echo $null >> test1.txt
git add .
git commit -m "test"
mklink /J link C:
git clean -fd
git status
```

I expect `git clean` to remove the unstaged Junction but instead I get the following:
```
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        link/

nothing added to commit but untracked files present (use "git add" to track)
```

Is this behavior by intention or a bug?

Thanks,
Lars

**Comment by dscho** [comment]
Junction points are intentionally not handled as if they were symbolic links. See https://github.com/git-for-windows/git/pull/437#issuecomment-144588141 (or for that matter, *all* of @kblees' insightful comments on that PR) for details.
