### ISSUE TITLE
Please add '<install_path>\Git\usr\bin' to system PATH

### ISSUE THREAD

**Issue by languanghao** [git-for-windows/git#976]
After install git-for-windows, the system cmd.exe works fine, but in webstorm embedded terminal, always give errors `git: 'flow' is not a git command. See 'git --help'`.

If add the `<install_path>\Git\usr\bin` to the PATH, everything works fine.

**Comment by dscho** [comment]
You chose to delete the issue reporting template instead of filling it out correctly, so I have to guess what exactly you meant.

My take is that you probably meant this:

1. call `Git CMD`
2. in that CMD, call `git flow version`

Expected output:
```
1.10.1 (AVH Edition)
```

If so, that expected output is *exactly* what I see. In other words, I cannot reproduce your bug.

**Comment by languanghao** [comment]
@dscho 
1. Install the git-for-windows
2. Use `windows cmd` or `git cmd`, everything works fine
3. Open the webstorm(this is an ide)  embedded terminal, call `git flow version`
output
    
          git: 'flow' is not a git command. See 'git --help'

After I add the `<install_path>\Git\usr\bin` to the PATH, the webstorm embedded terminal works fine. Now I can get the expected output.

**Comment by whoisj** [comment]
@languanghao are you certain that your IDE is using the installation of Git you assume it is?

Often, IDE will ship with their own bundled Git executable, in which case it is possible that this isn't a Git for Windows issue but an issue with your IDE or the usage of the IDE.

I think we should confirm exactly the issue we're looking at, otherwise it'll be very difficult to resolve this issue. Thanks.

**Comment by shiftkey** [comment]
@languanghao this is an interesting point:

> Use `windows cmd` or `git cmd`, everything works fine

If Windows CMD is able to resolve `git flow`, then the paths should be setup correctly. Let me demonstrate.

Here's the steps:

 - opened one of my Win10 VMs - build 14986, shouldn't matter
 - installed Git for Windows `2.11.0` 64-bit with these options set (`type "C:\Program Files\Git\etc\install-options.txt"`):

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - installed Webstorm 2016.3.1

Here's the output from command prompt (**not** Git CMD):

```
Microsoft Windows [Version 10.0.14986]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\shiftkey>git --version
git version 2.11.0.windows.1

C:\Users\shiftkey>where git
C:\Program Files\Git\cmd\git.exe

C:\Users\shiftkey>git flow
usage: git flow <subcommand>

Available subcommands are:
   init      Initialize a new git repo with support for the branching model.
   feature   Manage your feature branches.
   bugfix    Manage your bugfix branches.
   release   Manage your release branches.
   hotfix    Manage your hotfix branches.
   support   Manage your support branches.
   version   Shows version information.
   config    Manage your git-flow configuration.
   log       Show log deviating from base branch.

Try 'git flow <subcommand> help' for details.

C:\Users\shiftkey>echo %PATH%
C:\Program Files (x86)\Parallels\Parallels Tools\Applications;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\ProgramData\chocolatey\bin;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
C:\Program Files\dotnet\;
C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;
C:\Program Files\Git\cmd;
C:\Users\shiftkey\AppData\Local\Microsoft\WindowsApps;
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
```

Then I switched to Webstorm and ran the same steps in their embedded terminal:

```
Microsoft Windows [Version 10.0.14986]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\shiftkey\WebstormProjects\untitled>git --version
git version 2.11.0.windows.1

C:\Users\shiftkey\WebstormProjects\untitled>where git
C:\Program Files\Git\cmd\git.exe

C:\Users\shiftkey\WebstormProjects\untitled>git flow
usage: git flow <subcommand>

Available subcommands are:
   init      Initialize a new git repo with support for the branching model.
   feature   Manage your feature branches.
   bugfix    Manage your bugfix branches.
   release   Manage your release branches.
   hotfix    Manage your hotfix branches.
   support   Manage your support branches.
   version   Shows version information.
   config    Manage your git-flow configuration.
   log       Show log deviating from base branch.

Try 'git flow <subcommand> help' for details.

C:\Users\shiftkey\WebstormProjects\untitled>echo %PATH%
C:\Program Files (x86)\Parallels\Parallels Tools\Applications;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\ProgramData\chocolatey\bin;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
C:\Program Files\dotnet\;
C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;
C:\Program Files\Git\cmd;
C:\Users\shiftkey\AppData\Local\Microsoft\WindowsApps;
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
```

Without more information about what you're seeing or how to recreate the issue on my end, I'm going to close this out as it seems to be working fine for the latest Git for Windows release on the latest build of Webstorm.
