### ISSUE TITLE
v2.11 git log is shifted incorrectly

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#977]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not reproducible on v2.10, but reproducible in v2.11

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I run through Git Bash shortcut

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

My log commands are fairly complex and I use various aliases. I'll provide a relevant snippet from my git config and provide the executed command below that.

Git config aliases for log:

```
[alias]
short-log-base = log --abbrev-commit --decorate --date=relative --format=format:'\
%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)'

    lg =    !sh -c ": git log ; git short-log-base --graph"         # One-line logs
```

And the command I ran on a local "master" branch:

```
$ git lg
```

 - What did you expect to occur after running these commands?

The very tip commit should appear in line 1 of the console (I guess it's being piped through the 'less' command, as I'm able to arrow up/down through the one line logs).

 - What actually happened instead?

The 3rd line in the log output was actually at line 1 in the console. Pressing DOWN and then back UP again caused it to properly render the correct log line. I think what's happening is that the scroll position is correct (it thinks it's at the top of the logs), but the rendering of it is offset by 2 lines (shifted up, so the top 2 lines are not visible on screen and the 3rd line appears at the top).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is in my company's repository so I can't share it. But if you are not able to reproduce I will try to replicate a repository with a similar structure. Just let me know.

**Comment by dscho** [comment]
I cannot reproduce the problem here (trying with a `build-extra` clone). The first line lists the most recent commit, as expected.

**Comment by rcdailey** [comment]
Is there a way that I can take a specific branch in my company repo, strip all changes out of each commit (basically make them empty)? This way I can send you a simplified repo of the exact use case... I can repo on master but not other branches for some reason. Since I don't know the trigger for this issue, this is the best solution I can think of.

If you can give me a script or some commands to try, I will do this for you.

**Comment by dscho** [comment]
There is an anonymization function in fast-export, I believe. But you should really try to reproduce this with a public repository, and without aliases for that matter.

**Comment by rcdailey** [comment]
What if the bug requires the alias to be reproducible?

**Comment by rcdailey** [comment]
I think I found the issue... there is some word wrapping occurring and I have no idea why:

![image](https://cloud.githubusercontent.com/assets/1768054/20843172/e4afc3fa-b87f-11e6-9e9b-02aad1a2ef8d.png)

I am not able to get the word wrapping to happen in public repos I've tried, or via `git fast-export --anonymize` (because the commit messages are modified). When I move left/right, the log properly shifts up 1 line and it is no longer word wrapped.

Maybe this is a bug in less and not git? Does this help at all?

**Comment by rcdailey** [comment]
Actually might be due to the author name... it's spanish and uses some strange characters:

![image](https://cloud.githubusercontent.com/assets/1768054/20843357/acae0984-b880-11e6-81ec-c33cd301d3b1.png)

On version 2.10, the characters render properly:

![image](https://cloud.githubusercontent.com/assets/1768054/20843421/ed4842fc-b880-11e6-8535-ceaa5d68df6e.png)

**Comment by rcdailey** [comment]
@dscho: Can you confirm if this is enough information to make this issue clear and reproducible for you? If not, let me know as soon as you can so I can provide more information. Thanks.

**Comment by dscho** [comment]
> Can you confirm if this is enough information to make this issue clear and reproducible for you?

I do not have a quick-enough recipe to reproduce (I tried to reproduce with your original information, and it did not do the job for me), so no, I do not have enough information.

**Comment by rcdailey** [comment]
Did you look at the screenshots I attached? Did you try setting author name
to the name I provided with those special characters and make a commit then
view logs?

**Comment by dscho** [comment]
> Did you look at the screenshots I attached?

Yes. And they were not helpful. I cannot even try to copy-paste the author name in question to try to make an MCVE myself (not that I have the time to do that, either, if you want this issue to be resolved, you have to do your part, and making said MCVE is safely there).

In any case, I already spent too much time on this issue, there are so many others I have not even looked at today. You have to make it easy for me, if you want my help.

**Comment by rcdailey** [comment]
I didn't realize you wanted to be spoon-fed. It's hard enough to find a break at work to give you what I already have. It's very discouraging to read you say that nothing I've provided is helpful. You could do a better job at massaging your words to be more welcoming to those taking their time to help you out.

I have linked a repository (below) with 1 commit in it that uses the same author name. The commit message subject is very long, so please make sure your terminal window's width is small enough to cause horizontal scrolling when you run logs. Please use the command I gave you earlier, the aliases are included in the repo's local config:

    $ git lg

You should see the following result:

![image](https://cloud.githubusercontent.com/assets/1768054/20929280/0bce8f7c-bb8f-11e6-9f73-a97c34dafd84.png)

Repository to test with:

https://drive.google.com/open?id=0B1OV0Szd-FT4MmxkbnN3V01KZWc

If you are still not able to reproduce this on 2.11 or this is not made easy enough for you, I have nothing else left to provide. Go ahead and close the issue, I do not have more time to invest in this.

**Comment by dscho** [comment]
Maybe somebody else wants to try to fix this.

**Comment by PhilipOakley** [comment]
@rcdailey 
Hi Robert, unfortunately dscho is rather busy, so it is common that things we may think are easy to do when we are relaxed and with a bit of spare time, do end up being one item too many for dscho to keep juggling with.

In such cases, yes, providing a spoon-fed example that can be run directly at the command line does grease the wheels of progress. It's just like doing canned demonstrations for managements at $dayjob. It needs to be slick, easy and practiced for the case to be made (it's almost as bad as trying to prepare a perfect upstream patch ;-)

Q: Does the problem repeat if you make the terminal window very small, and use a simple log command?

Can the demo repo be placed on Github? - I can't access the google drive behind my current firewall.
If it can be, the demo should be as simple as:

```
git clone https://github.com/rcdailey/badlog.git
# Set  Language settings as needed?
# narrow mintty to less than XX chars wide, yy lines long
git log -30

```
Maybe it needs the '--graph' in there.; or maybe not?

**Comment by rcdailey** [comment]
I simply decided to use an attached zip of the repository because I wanted you to have the local config as well. If I push it up you won't have it AFAIK. So I could provide the configuration here as a preformatted section, but it would require you to take an extra step of editing  your config after your clone. If you are OK with this, I have pushed it up to a github repository for you here:

https://github.com/rcdailey/test977

The git configuration I used is in `git_config.txt` inside the repository itself.

To answer your other question: Yes, when doing a normal `git log`, I see that the name is not properly rendering the special characters. Instead of seeing `Jesus Montaño` (as I do in 2.10), I see `Jesus MontaÃ±o` in 2.11.

**Comment by iegik** [comment]
```
git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

```
$ less --version
less 481 (Spencer V8 regular expressions)
Copyright (C) 1984-2015  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

Windows 10 v1511 (Build 10586.679)
PowerShell 2.0

```
$ chcp
Active code page: 65001
```

TrueType font: **Noto Mono**

```
$ git config --global --get core.quotepath
false
$ git config --global --get i18n.commitencoding
$ git config --global --get i18n.logoutputencoding
866
$ git config --global --get core.editor
cat
$ git config --global --get core.pager
iconv.exe -f cp1251 -t utf-8 | less
$ git config --get core.quotepath
false
$ git config --get i18n.commitencoding
$ git config --get i18n.logoutputencoding
866
$ git config --get core.editor
cat
$ git config --get core.pager
iconv.exe -f cp1251 -t utf-8 | less
```

`git log` or `git log --encoding=utf-8` prints messy content, otherwise `git log | less` prints normal UTF-8 log lines

Latest working version:
```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```

**Comment by dscho** [comment]
> I expected to see v2.11 as mentioned in the release page I downloaded it from. I installed twice to make sure, because this mismatch was confusing.

I would have appreciated help with making that less confusing. I finally spent some time to streamline the prerelease engineering, if everything goes well `git version` will now show a less surprising and more informative version.

> Looks like this issue might be related to #981.

Yep, it is a duplicate of that ticket (but I agree that it was hard to recognize, given the wildly different symptoms).
