### ISSUE TITLE
git-gui: problems caused by height changes

### ISSUE THREAD

**Issue by CNMan** [git-for-windows/git#980]
OS: Windows server 2016 build 10.0.14393
Git: PortableGit-2.10.2-64-bit.7z.exe and PortableGit-2.11.0-64-bit.7z.exe
git-gui 2.10.2
![2 10 2](https://cloud.githubusercontent.com/assets/8692234/20857821/d279ebdc-b971-11e6-9c1d-c495494e1c6c.png)
git-gui 2.11.0
![2 11 0](https://cloud.githubusercontent.com/assets/8692234/20857819/d15a9256-b971-11e6-8b2a-adeef9571ea5.png)

**Comment by dscho** [comment]
This seems not to be specific to Windows. Please report it on [the Git mailing list](mailto:git@vger.kernel.org).
