### ISSUE TITLE
waitpid for plink.exe fails for "No Child Processes"

### ISSUE THREAD

**Issue by jtbraun** [git-for-windows/git#983]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Path Option: BashOnly
Plink Path: C:\Program Files (x86)\PuTTY\plink.exe
SSH Option: Plink
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

GIT_SSH=C:\Program Files (x86)\PuTTY\plink.exe

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
```
 - What did you expect to occur after running these commands?

all refs to be pushed without error

 - What actually happened instead?

An error is printed:
error: waitpid for C:\Program Files (x86)\PuTTY\plink.exe failed: No child processes
And later:
error: failed to push some refs to 'ssh://git@HOST:PORT/path/to/repository.git'

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Internal.

Some other forum posts mention similar issues:
https://stackoverflow.com/questions/38624606/error-waitpid-for-c-program-files-x86-putty-plink-exe-failed-no-child-proce

**Comment by dscho** [comment]
I know it can be a challenge to provide a Minimal, Complete & Verifiable Example that makes it very easy (and more importantly, quick) for contributors with bug fixing abilities to reproduce the issue, in particular with plink.

In my case, it is a necessity because I simply cannot afford the time to try to set up a scenario where I may be able to reproduce the problem (or maybe not).

**Comment by jtbraun** [comment]
How's this?

```cmd
set GIT_SSH
GIT_SSH=C:\Program Files (x86)\PuTTY\plink.exe
"%GIT_SSH%" --version
plink: Development snapshot 2016-09-20.24da181
```

Have pageant running with your github key loaded, and have github.com in your known hosts file.

1. I created a brand new repository on GitHub (https://github.com/jtbraun/GitWindowsPlinkTest)
2. mkdir GitWindowsPlinkTest
3. cd GitWindowsPlinkTest
4. git init
5. touch README.md
6. git add README.md
7. git commit
8. git push -u origin master

The result of the push:
> Counting objects: 3, done.
> Writing objects: 100% (3/3), 220 bytes | 0 bytes/s, done.
> Total 3 (delta 0), reused 0 (delta 0)
> **error: waitpid for C:\Program Files (x86)\PuTTY\plink.exe failed: No child processes**
> To github.com:jtbraun/GitWindowsPlinkTest.git
>  * [new branch]      master -> master
> Branch master set up to track remote branch master from origin.
> **error: failed to push some refs to 'git@github.com:jtbraun/GitWindowsPlinkTest.git'**

**Comment by drujd** [comment]
This problem occurs with newer (development) versions of Putty Plink (May/June 2016 onwards, I think). When using the 0.67 version of Plink (or TortoisePlink, which is a modification of the 0.67 version), it does not occur. So the solution is to downgrade to latest stable/beta of Plink - 0.67.

HOWEVER, newer versions of Plink have performance optimizations that are VERY noticeable on high latency connections - or, to be exact, older versions were MUCH slower on these connection compared to OpenSSH. So I have to use the dev version and hope this gets fixed (as I need the better performance and pageant compatibility).

Please note that even though the error is throws, all the actions actually ARE done, so git is usable.

**Comment by jtn20** [comment]
I believe this is caused by Plink, not Git; specifically by process ACL restrictions which were added to development snapshots of Plink as of 2016-04-03.

These have been removed from newer development snapshots of Plink as of 2017-01-30 (and were not included in any release version of Plink), so you should find that the problem goes away if you switch to a version newer than that (and you get to keep any performance optimisations).

Full details of this issue are at http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/win-process-acl-finesse.html

However, I've not reproduced this issue, nor tested myself that a newer snapshot of Plink makes it go away.

**Comment by drujd** [comment]
Yes, it seems to be fixed with the latest snapshot.

**Comment by dscho** [comment]
> Yes, it seems to be fixed with the latest snapshot.

So this ticket can be closed, right? @jtbraun ?

**Comment by jtbraun** [comment]
Yes, closed.
