### ISSUE TITLE
New experimental builtin difftool doesn't seem to be working

### ISSUE THREAD

**Issue by FallenGameR** [git-for-windows/git#985]
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
» git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.14393]
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
» type "C:\Program Files\Git\etc\install-options.txt"
Path Option: CmdTools
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

GitExtensions installed after git. It registered KDiff3 in global .gitconfig. Not sure if it is related.

```
[merge]
	tool = kdiff3
[mergetool "kdiff3"]
	path = C:/Program Files/KDiff3/kdiff3.exe
[diff]
	guitool = kdiff3
[difftool "kdiff3"]
	path = C:/Program Files/KDiff3/kdiff3.exe
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I'm trying to use the new experimental difftool that is said to come with Git for Windows 2.11, but I don't see it listed upon difftool command invocation.

```
» git config --bool difftool.useBuiltin true
» git config --bool difftool.useBuiltin
true
» git difftool

Viewing (1/1): 'src/CoreXTAutomation/Text.ps1'
Launch 'kdiff3' [Y/n]? n
```

When I remove all kdiff3 reverences from the config I get the following output. Still no option to use the buildin difftool:

```
» git difftool

This message is displayed because 'diff.tool' is not configured.
See 'git difftool --tool-help' or 'git help config' for more details.
'git difftool' will now attempt to use one of the following tools:
kompare emerge vimdiff

Viewing (1/1): 'src/CoreXTAutomation/Text.ps1'
Launch 'vimdiff' [Y/n]?
```

 - What did you expect to occur after running these commands?

Diff of the changed file in the new difftool. Or option to launch it. Or warning message saying that build in difftool can't be used because of some issues with the git config setup.

 - What actually happened instead?

Can't invoke the new difftool.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Tried on several local repositories. The problem don't seem to be repository-specific.

**Comment by shiftkey** [comment]
@FallenGameR could you also run `git difftool --tool-help` and include the output of that.

This is what I see currently:

```
$ git difftool --tool-help
'git difftool --tool=<tool>' may be set to one of the following:
                vimdiff
                vimdiff2
                vimdiff3

The following tools are valid, but not currently available:
                araxis
                bc
                bc3
                codecompare
                deltawalker
                diffmerge
                diffuse
                ecmerge
                emerge
                examdiff
                gvimdiff
                gvimdiff2
                gvimdiff3
                kdiff3
                kompare
                meld
                opendiff
                p4merge
                tkdiff
                winmerge
                xxdiff

Some of the tools listed above only work in a windowed
environment. If run in a terminal-only session, they will fail.
```

This tells me a couple of things:

 - Git supports automatically launching many tools
 - the only one it really supports for me is `vimdiff`, which is fine because it's a rather vanilla setup I'm testing on

When I do `git difftool` I then get this:

```
$ git difftool

This message is displayed because 'diff.tool' is not configured.
See 'git difftool --tool-help' or 'git help config' for more details.
'git difftool' will now attempt to use one of the following tools:
opendiff kdiff3 tkdiff xxdiff meld kompare gvimdiff diffuse diffmerge ecmerge p4merge araxis bc codecompare emerge vimdiff

Viewing (1/1): 'test.txt'
Launch 'vimdiff' [Y/n]? n
```

If I press `Y` here I see `vimdiff` launch.

As I understand it, `git difftool` doesn't mean Git is shipping with its own diff tooling - it just takes away the hassle of integrating and using existing difftools. The fallback behaviour being `vimdiff` seems to be correct in this case.

**Comment by dscho** [comment]
Indeed, this seems to be a misunderstanding.

The "builtin" difftool still operates *exactly* the same way as the previous version (modulo bugs, that is). The only difference is that the command no longer runs a Perl script under the hood but native code, right up until the point when the *real* diff tool is launched.
