### ISSUE TITLE
Feature request: Publish .zip archives in addition to self-extracting 7z .exe's

### ISSUE THREAD

**Issue by friism** [git-for-windows/git#986]
The self-extracting 7z archives that are currently released (eg. for the portable version) are difficult to install in a headless manner because they require first installing 7z.

Windows/PowerShell has built-in .zip support (with `Expand-Archive`). Would it make sense to publish `.zip` archives in addition to the assorted .exe's?

**Comment by shiftkey** [comment]
> they require first installing 7z.

I don't believe this is the case. 

![](https://cloud.githubusercontent.com/assets/359239/20996338/fc0205b0-bd50-11e6-880b-5f90d500ce3c.png)

You can also control the extraction of the archive from the command line:

```
> .\PortableGit-2.11.0-64-bit.7z.exe -y -o "C:/git-for-windows"
```

This isn't an ideal solution, as it exits early and pops a progress bar. I'm sure I'm missing something from the docs...

**Comment by dscho** [comment]
> The self-extracting 7z archives that are currently released (eg. for the portable version) are difficult to install in a headless manner because they require first installing 7z.

Why not use the NuGet package: https://www.nuget.org/packages/GitForWindows/.

**Comment by dscho** [comment]
To explain my reluctance for `.zip` packages: the space difference between `.zip` and `.7z` are huge. Just look at the `.tar.bz2` files we also provide: the latter (which compress better than `.zip` files) are *still* triple the size of the `.7z` files.

That means not only wasted space, but also wasted time for me when I make new releases.

Given the workaround below, combined with this reluctance, means that I will close this ticket for now. If you feel strongly about it, please feel free to convince me compelling arguments :smiley: .

Also, to enhance on @shiftkey's response:

> You can also control the extraction of the archive from the command line:

We use the old .sfx component that used to be hosted on http://7zsfx.info. You can still see the switches in the Internet Archive: https://web.archive.org/web/20160402074100/http://www.7zsfx.info/en/switches.html. From that information, the best idea would be to use `-y -gm2 -InstallPath="C:\\use\\double\\backslashes"` (see also this helpful StackOverflow answer: http://stackoverflow.com/a/32105548).

**Comment by PhilipOakley** [comment]
I have added a wiki page with this detail, and a small link from the FAQ page.

**Comment by friism** [comment]
Posting link here for others to find: https://github.com/git-for-windows/git/wiki/Zip-Archives---extracting-the-released-archives

... thanks for this, I'll try it out shortly!

**Comment by friism** [comment]
I'm finding that the self-extractor hangs when invoked from Powershell while doing a windows container docker build:

```
FROM microsoft/windowsservercore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV GIT_VERSION=2.11.0
RUN Invoke-Webrequest "https://github.com/git-for-windows/git/releases/download/v$Env:GIT_VERSION.windows.1/PortableGit-$Env:GIT_VERSION-64-bit.7z.exe" -UseBasicParsing -OutFile C:\gitsetup.7z.exe
RUN New-Item C:\git -ItemType Directory

RUN Start-Process C:\gitsetup.7z.exe -ArgumentList '-y -gm2 -InstallPath="C:\\git"' -Wait
```

It works with powershell outside of a container build, and it also works when using `cmd.exe`

**Comment by dscho** [comment]
@friism have you tried the NuPkg? A NuPkg *is* a `.zip`, after all...
