### ISSUE TITLE
Unicode characters broken in Git 2.11

### ISSUE THREAD

**Issue by mrliptontea** [git-for-windows/git#990]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
Windows 10 Pro
64-bit
```

 - What options did you set as part of the installation?

I chose defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using ConEmu. `Git\bin\` is added to system PATH variable, hence no need for an absolute path to bash executable.

### Details

 - Which terminal/shell are you running Git from?

```
set CHERE_INVOKING=1 & bash.exe --login -i
```

 - What commands did you run to trigger this issue?

```diff
/d/www/apps/test î  fix-price-comparison
$ git --version
git version 2.11.0.windows.1

/d/www/apps/test î  fix-price-comparison
$ bash --version
GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

/d/www/apps/test î  fix-price-comparison
$ git diff
diff --git a/config/app.php b/config/app.php
index 00cd557..7c754c6 100644
--- a/config/app.php
+++ b/config/app.php
@@ -12,7 +12,7 @@ return [
     | any other location as required by the application or its packages.
     */

-    'name' => 'test',
+    'name' => '<E2><86><91><E2><86><93><E2><86><90><E2><86><92>',

     /*
     |--------------------------------------------------------------------------
```

 - What did you expect to occur after running these commands?

It should display unicode characters correctly. It was previously working in 2.10.2 with the same version of bash.

Example characters:

| Description        | Expected | Result in 2.11 |
| ------------------ | -------- | -------------- |
| star               | `★`      | `<E2><98><85>` |
| heart              | `❤`      | `<E2><9D><A4>` |
| eight note         | `♪`      | `<E2><99><AA>` |
| check mark         | `✔`      | `<E2><9C><94>` |
| cross mark         | `✘`      | `<E2><9C><98>` |
| pencil             | `✎`      | `<E2><9C><8E>` |
| arrow up           | `↑`      | `<E2><86><91>` |
| arrow up           | `↓`      | `<E2><86><93>` |
| arrow up           | `←`      | `<E2><86><90>` |
| arrow up           | `→`      | `<E2><86><92>` |
| branch (powerline) | ``      | `î `           |

 - What actually happened instead?

```diff
/d/www/apps/test  fix-price-comparison
$ git --version
git version 2.10.2.windows.1

/d/www/apps/test  fix-price-comparison
$ bash --version
GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

/d/www/apps/test  fix-price-comparison
$ git diff
diff --git a/config/app.php b/config/app.php
index 00cd557..7c754c6 100644
--- a/config/app.php
+++ b/config/app.php
@@ -12,7 +12,7 @@ return [
     | any other location as required by the application or its packages.
     */

-    'name' => 'test',
+    'name' => '↑↓←→',

     /*
     |--------------------------------------------------------------------------
```

**Comment by dscho** [comment]
This is most likely a duplicate of #981. Can  you verify that this prerelease fixes the problems? https://github.com/git-for-windows/git/releases/tag/prerelease-v2.11.0.windows.1.1

**Comment by mrliptontea** [comment]
@dscho Oh, sorry for duplicate, I was looking for issues related to "unicode", "utf-8", etc.

Yes, I can confirm that [pre-release](https://github.com/git-for-windows/git/releases/tag/prerelease-v2.11.0.windows.1.1) fixes that problem.

**Comment by dscho** [comment]
> Yes, I can confirm that pre-release fixes that problem.

Excellent!
