### ISSUE TITLE
subtree produces "Unexpected option" or nothing. 

### ISSUE THREAD

**Issue by Jackbennett** [git-for-windows/git#992]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
it version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```
### Details

 - Which terminal/shell are you running Git from? 
each Bash/CMD/PowerShell/other

 - What commands did you run to trigger this issue? If you can provide a

```
git subtree push --prefix public origin gh-pages
Unexpected option: push
```

 - What did you expect to occur after running these commands?

 upload a folder to github branch

 - What actually happened instead?

`Unexpected option: push`

a bare `subtree` produces a few blank lines, the other commands produce the above.

**Comment by shiftkey** [comment]
@Jackbennett changing the command to ` --prefix=public` works for me:

```
$ git subtree push --prefix=public origin gh-pages

git push using:  origin gh-pages
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 292 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/shiftkey/testing-gh-pages.git
   1de9ff1..943e87e  943e87ed20df130bcd64b2a7004d6dbbed0bc86f -> gh-pages
```

This seems to be what the command expects, based on the docs:

```
$ git subtree
usage: git subtree add   --prefix=<prefix> <commit>
   or: git subtree add   --prefix=<prefix> <repository> <ref>
   or: git subtree merge --prefix=<prefix> <commit>
   or: git subtree pull  --prefix=<prefix> <repository> <ref>
   or: git subtree push  --prefix=<prefix> <repository> <ref>
   or: git subtree split --prefix=<prefix> <commit...>

    -h, --help            show the help
    ...
```

**Comment by Jackbennett** [comment]
I just double checked my command history but I tried that.

##CMD
```cmd.exe
N:\Documents\src\heatmap>git subtree
usage:

N:\Documents\src\heatmap>git subtree push --prefix=public origin gp-page2
Unexpected option: push
# Hun here forever first but now states above error.
```
git-bash
```
jbennett@ITSPC02 MINGW64 /n/documents/src/heatmap
$ git subtree


jbennett@ITSPC02 MINGW64 /n/documents/src/heatmap
$ git subtree push --prefix=public origin gp-page2
# Hanging here forever
```

I normally use powershell but it's a similar result and I posted cmd and git-bash as it's probably got the least interfering with it. For completeness, that repo URL is configured to use a key that I type a password to and the network uses a MITM proxy that git if configured to use.

**Comment by shiftkey** [comment]
@Jackbennett interesting - I was testing in Git Bash, so I switched over to Git CMD and got this (which was expected, as I'd deleted the remote repository):

<img width="691" src="https://cloud.githubusercontent.com/assets/359239/21178535/110ce644-c244-11e6-91e8-b647b1017dd7.png">

It's really strange how you're not seeing the usage output for either scenario. Any clues into whether something else on your machine might be involved?

**Comment by Jackbennett** [comment]
It's windows 10 so who knows. A better answer might be I installed fresh from the source again so that subtree wasn't what I replaced initially from its github repo. no change either way. I only use powershell normally so cmd or bash have never had any tweaks from the default. 

I can't really read bash but git-subtree from 'C:\Program Files\Git\mingw64\libexec\git-core` line 144 ends up that it can't find "push", is `test` getting filled with `push` thus off by one as it should be `--prefix`?

When I ran `git-subtree` directly with `bash -x` the other day it seems to hang on something relating to git-sh-i18n. I didn't expect this to work but here's a dump of that.

```bash
jbennett@ITSPC02 MINGW64 /mingw64/libexec/git-core
$ bash -x git-subtree push --prefix="/n/documents/src/heatmap/public" origin gp-page2
+ test 4 -eq 0
+ OPTS_SPEC='git subtree add   --prefix=<prefix> <commit>
git subtree add   --prefix=<prefix> <repository> <ref>
git subtree merge --prefix=<prefix> <commit>
git subtree pull  --prefix=<prefix> <repository> <ref>
git subtree push  --prefix=<prefix> <repository> <ref>
git subtree split --prefix=<prefix> <commit...>
--
h,help        show the help
q             quiet
d             show debug messages
P,prefix=     the name of the subdir to split out
m,message=    use the given message as the commit message for the merge commit
 options for '\''split'\''
annotate=     add a prefix to commit message of new commits
b,branch=     create a new branch from the split subtree
ignore-joins  ignore prior --rejoin commits
onto=         try connecting new tree to an existing one
rejoin        merge the new branch back into HEAD
 options for '\''add'\'', '\''merge'\'', and '\''pull'\''
squash        merge subtree changes as a single commit
'
+ eval ''
++ git --exec-path
+ PATH='/n//bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/n/bin:/c/Program Files/Python35/Scripts:/c/Program Files/Python35:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/AMD/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Live/Shared:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files/nodejs:/c/Program Files (x86)/Microsoft VS Code/bin:/c/Program Files (x86)/PDFtk Server/bin:/cmd:/c/Users/jbennett/AppData/Local/Microsoft/WindowsApps:/c/Program Files (x86)/Microsoft VS Code/bin:/n/global_modules:/usr/bin/vendor_perl:/usr/bin/core_perl:C:\Program Files\Git\mingw64/libexec/git-core'
+ . git-sh-setup
++ unset CDPATH
++ IFS='
'
+++ git --exec-path
++ . 'C:\Program Files\Git\mingw64/libexec/git-core/git-sh-i18n'
+++ TEXTDOMAIN=git
+++ export TEXTDOMAIN
+++ test -z ''
+++ TEXTDOMAINDIR=/mingw64/share/locale
+++ export TEXTDOMAINDIR
+++ GIT_INTERNAL_GETTEXT_SH_SCHEME=fallthrough
+++ test -n fallthrough
+++ GIT_INTERNAL_GETTEXT_SH_SCHEME=fallthrough
+++ export GIT_INTERNAL_GETTEXT_SH_SCHEME
+++ case "$GIT_INTERNAL_GETTEXT_SH_SCHEME" in
++ GIT_QUIET=
++ test -n ''
++ dashless=
++ '[' -z '' ']'
+++ eval_gettext 'usage: $dashless $USAGE'
+++ printf %s 'usage: $dashless $USAGE'
++++ git sh-i18n--envsubst --variables 'usage: $dashless $USAGE'
+++ export PATH dashless USAGE
+++ git sh-i18n--envsubst 'usage: $dashless $USAGE'
++ LONG_USAGE='usage:  '
++ case "$1" in
++ case $(uname -s) in
+++ uname -s
++ test -z ''
++ git_dir_init
+++ git rev-parse --git-dir
fatal: Not a git repository (or any of the parent directories): .git
++ GIT_DIR=
++ exit

jbennett@ITSPC02 MINGW64 /mingw64/libexec/git-core
$```

**Comment by shiftkey** [comment]
I'm not quite sure the problem is inside this script, but let's confirm this.

Try this for me:

1. Add this line to C:\Program Files\Git\mingw64\libexec\git-core\git-subtree, before it starts parsing the input arguments (I added this before `debug () {`):

```
echo "Arguments: $@"
```

<img width="317" src="https://cloud.githubusercontent.com/assets/359239/21204038/6cd7da1e-c2a9-11e6-9b04-01338679ace4.png">

2. Run the same command but also provide a `-d` flag - this might add some interesting output:

```
git subtree push --prefix=public origin gh-pages -d
```

For reference, this is what I see now:

```
$ git subtree push --prefix=public origin gh-pages -d
Arguments: -P public -d -- push origin gh-pages
command: {push}
quiet: {}
revs: {}
dir: {public}
opts: {origin gh-pages}

git push using:  origin gh-pages
error: src refspec Arguments: -P public -- split
943e87ed20df130bcd64b2a7004d6dbbed0bc86f does not match any.
error: failed to push some refs to 'https://github.com/shiftkey/testing-gh-pages.git'
```

Note how the arguments have been flipped around. I suspect that's not the case for your setup.

**Comment by Jackbennett** [comment]
```
jbennett@ITSPC02 MINGW64 /N/Documents/src/heatmap
$ git subtree push --prefix=public origin gh-pages2 -d
Arguments: push --prefix=public origin gh-pages2 -d
Unexpected option: push
```
would be the result from git-bash and powershell.

**Comment by shiftkey** [comment]
@Jackbennett well that explains the error message at least. Not to figure out the root cause...

**Comment by Jackbennett** [comment]
Well I'll get git on some other computers and windows versions today to rule out this computer.

**Comment by jsfaint** [comment]
This issue can be reproduced on 64bit version, but on 32bit version git subtress works fine.

**Comment by Jackbennett** [comment]
Can confirm from a windows 7 Enterprise x64 machine with x64 git installed it's the same behaviour.

no output from `git subtree` --help does launch the browser but `git subtree push` is the same `unexpected option: push`

Maybe re-open to fix x64 git?

**Comment by shiftkey** [comment]
@Jackbennett I've not been able to reproduce this on either Windows 10 x64 or Windows 7 x64 vanilla VMs using the latest stable build (2.11.0) - I see the arguments being passed in correctly as shown [here](https://github.com/git-for-windows/git/issues/992#issuecomment-267178596), so I'm not sure what else I can do to recreate the issue.
