### ISSUE TITLE
use of git-for-windows bash when bash on windows is present

### ISSUE THREAD

**Issue by ranjan-ranjan** [git-for-windows/git#995]
as bash on windows is there what would be the use of git-for-windows? we can install git using `sudo apt-get update` in bash on windows.

**Comment by kostix** [comment]
@ranjan-ranjan, issue tracker is not a place to ask general questions about a product—it's for reporting and tracking problems in the product.

Please use the ["Mailing list"](http://groups.google.com/group/git-for-windows) link in the main menu of the [Git for Windows site](https://git-for-windows.github.io/) to ask your question.

Please also note that your question should supposedly be rephrased: I, for one, failed to understand its essense.  I admit English is supposedly not your native language.  That's fine—just please don't try to cram as much words as possible into a single sentence: it's better to use several simple sentences: like "I have ...", "How do I then do ...?".

**Comment by ranjan-ranjan** [comment]
ok.
everywhere issues are used to ask questions in github. that's why i asked it here.

**Comment by shiftkey** [comment]
@ranjan-ranjan currently Bash on Ubuntu on Windows is limited to those people running a specific build of Windows 10 (`10.0.14393` or later), who then enable Developer Mode (requires administration rights). This is a small subset of the current Windows userbase, and while I'm a big fan of the work the Windows Subsystem for Linux team is currently doing, it's still a work in progress (fast ring gets the latest changes, and they slowly trickle back, interoperability work between Bash and Win32 is ongoing).

Bash on Ubuntu on Windows won't ever be backported to earlier Windows releases - last I checked Git for Windows supports Windows XP and up. Lots of products using Git for Windows also need to run in environments where Bash on Ubuntu on Windows isn't available. So there remains lots of users who rely on the Git for Windows project to get stuff done.

Hope this helps!

**Comment by ranjan-ranjan** [comment]
ok.
but windows xp is no longer supported. so those users will have to use newer version of windows.

**Comment by dscho** [comment]
> but windows xp is no longer supported.

By Microsoft, and recently also by Git for Windows. The latter is an Open Source project, though, therefore it just takes one or two dedicated (and capable) developers to reinstate the support.

> so those users will have to use newer version of windows.

They do not *have* to. Users are free to do what they want. Just like Open Source developers are free to do what *they* want. Let's keep that in mind.

**Comment by PhilipOakley** [comment]
Hi @ranjan-ranjan, I'm quite happy that Microsoft is embracing these different oppotunities, such as their bash in newer versions of Windows. However, as someone who still has a little XP netbook that is still working just fine (I don't think it affects my typing speed;-) I'm grateful that there is still _some_ backward compatibility (no matter how imperfect and partial). Actually MS does some quite good backward compatibility, which can be re-assuring.

I'm quessing that the phrase you used that dscho noted, was just a figure of speech, in the way we may write a commit message (we like to command computers! ;) It is worth checking over posts for such accidental phrasing, and noting how other do (or don't) write the soft prose.

It's good to have you in the GfW camp.

--
Philip
PS I just remeber OS's that took 1kbyte, and used real punch tape, so I don't rush to get all the latest stuff these days...
