### ISSUE TITLE
Recent `isatty` changes result in TTYs no longer being detected

### ISSUE THREAD

**Issue by FraGag** [git-for-windows/git#997]
The recent changes around `isatty` implemented in 966905940ca84600dcb47d32a436742962903e94 and merged in 4af28e2fb4af1069c81a3dcfab0332498e8424de have the effect that Git no longer recognizes standard input and standard output as a TTY when it is. When using the version at 6cd98a7c65ea69403c288adb00b0d883319fd2a5, TTYs are properly recognized.

### Setup

```
$ git --version --build-options
git version 2.11.0.windows.1.353.g4af28e2
built from commit: 4af28e2fb4af1069c81a3dcfab0332498e8424de
sizeof-long: 4
machine: x86_64

$ cmd.exe /c ver

Microsoft Windows [version 6.1.7601]

$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Difftool: Disabled
```

In `~/.gitconfig`:

```
[color]
	ui = true
[core]
	pager = less -+$LESS -RS
```

I'm also running Windows with UAC disabled (always Administrator).

### Details

I've tested on Git Bash (with mintty) and Git CMD and the issue occurs on both. To reproduce, run any command that should colorize its output (e.g. `git status`, `git log`) when standard output is a terminal. On 4af28e2fb4af1069c81a3dcfab0332498e8424de, the output has no color and `git log` doesn't invoke the pager, and instead writes its output directly to the terminal.

I first noticed this issue after installing Git for Windows SDK, when master was pointing on 4af28e2fb4af1069c81a3dcfab0332498e8424de. I compiled 4af28e2fb4af1069c81a3dcfab0332498e8424de locally, built the Git for Windows installer and installed that version and that Git for Windows installation also had the problem. (I had Git for Windows 2.11.0.windows.1 installed prior to that, and it didn't have the issue.) I then compiled and installed 6cd98a7c65ea69403c288adb00b0d883319fd2a5, and that version also didn't have the issue.

**Comment by bbolli** [comment]
This is fixed in development: http://public-inbox.org/git/xmqqzijpger6.fsf@gitster.mtv.corp.google.com/T/#m2c0af63664b8c2de55899b2bff977d055af0c51e

@dscho: I can confirm that your branch `mingw-isatty-fixup-master` fixes the TTY problems in MinTTY/Bash and CMD.EXE (Windows 7, 32bit). The output of `git log` is again colorized and sent through less(1).

**Comment by dscho** [comment]
@bbolli Thanks for the feedback!

**Comment by FraGag** [comment]
I tested the branch `mingw-isatty-fixup` on top of Git for Windows's master (cf8df3d1b98f3f9633fec194aa6393076525ec0b).

First, I reverted commits 966905940ca84600dcb47d32a436742962903e94 and 042632aed104a3d17e64a00308a36f467302481e to roll back patches not yet in upstream (to avoid merge conflicts). Then, I rebased `upstream/master..dscho/mingw-isatty-fixup` on top of the reverts. The rebased commits are (most recent first):

```
2ce6060b89 mingw: replace isatty() hack
796e3c4b5b mingw: fix colourization on Cygwin pseudo terminals
ca4c61c603 mingw: adjust is_console() to work with stdin
```

The middle commit ended up being skipped as the patch is already in Git for Windows.

* `mingw: adjust is_console() to work with stdin` doesn't break anything
* `mingw: replace isatty() hack` makes the issue appear again (in both CMD and mintty).

**Comment by dscho** [comment]
@FraGag that comment leaves me puzzled. What is your finding? Do those patches fix the issue for you?

**Comment by FraGag** [comment]
No, the last patch (`mingw: replace isatty() hack`) reintroduces the issue (that stdin/stdout are not detected as TTYs).

**Comment by dscho** [comment]
@FraGag can you test the latest `master`, please? I tested that, and it fixed it here.

**Comment by FraGag** [comment]
@dscho OK, I just tested the latest `master`, and it works. The problem was that in my version, I had removed the `isatty` `#define` by doing the reverts, whereas I should have kept it.

```diff
diff --git a/compat/mingw.h b/compat/mingw.h
index a02bc4b4de..81d8f0e13e 100644
--- a/compat/mingw.h
+++ b/compat/mingw.h
@@ -472,9 +472,6 @@ int mingw_raise(int sig);
  * ANSI emulation wrappers
  */

-int winansi_isatty(int fd);
-#define isatty winansi_isatty
-
 void winansi_init(void);
 HANDLE winansi_get_osfhandle(int fd);
```

(Left is yours, right is mine.) Reintroducing these two lines fixed the issue. Sorry about that!

**Comment by dscho** [comment]
Okay, thank you for being thorough.

In the future, may I ask you to close any ticket you opened once the problem has been addressed? I kind of prefer a more equal footing than "being the big daddy" :smiley:
